### PR TITLE
update starsector to 0.96a-RC7

### PR DESCRIPTION
**Pull request by lizelive**
###### Description of changes

https://fractalsoftworks.com/2023/05/05/starsector-0-96a-release/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lizelive** [comment]
recreated #230211 without everyone being subscribed.

**Comment by wegank** [comment]
You should split it into two commits, the first one `maintainers: add lizelive`, and the second one `starsector: 0.95.1a-RC6 -> 0.96a-RC7`.

**Comment by necauqua** [comment]
fyi a hotfix [RC8](https://fractalsoftworks.com/2023/05/05/starsector-0-96a-release/) has been released

**Comment by lizelive** [comment]
> fyi a hotfix [RC8](https://fractalsoftworks.com/2023/05/05/starsector-0-96a-release/) has been released

cool ill make another pr. please approve #230913 per @wegank request

**Comment by necauqua** [comment]
Well I can't approve things, but I'm pretty sure you could've just force-pushed two consecutive commits in this pull request - and also update to RC8 at the same time

**Review by bbigras — APPROVED** [review]
builds and runs. thanks!

**Review by wegank — CHANGES_REQUESTED** [review]
Please rebase and split the commit into two commits **in this PR**, thanks.

**Comment by lizelive** [comment]
@wegank if i rebase it will notify everyone

**Comment by lizelive** [comment]
@wegank it was very rude to close #230913 after asking for that shit. I made another pr #230954 if someone wants to approve that i will reraise this pr.

**Comment by wegank** [comment]
> @wegank if i rebase it will notify everyone

Not at all.

> @wegank it was very rude to close #230913 after asking for me to split into two and blocking this pr. I made another pr #230954 if someone wants to approve that i will reraise this pr with latest version

I'm sorry for my possible rudeness.

To be clear, I never asked you to create another **PR**. What I asked for was to split a **commit** into two, each with an appropriate commit message, so that your PR would meet the standard of the repo (including [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) which you've falsely ticked). I don't think it's too difficult to do that.

**Comment by lizelive** [comment]
@wegank thank you for apology, and i had to recreate the pr anyhow because i can't reopen it.
I have to apologize as well. I initially misread the CONTRIBUTING.md and your advice was really solid and correct. i followed it in #230958

but [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) does not include a policy for having a pr that just adds someone to contributes. there is a line about it here https://nixos.org/manual/nixpkgs/unstable/#var-meta-maintainers.

thank you for your advice.

**Pull request closed without merging**
