### PR TITLE
man-pages: 6.05.01 -> 6.7

### PR DESCRIPTION
**Pull request by trofi**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by marsam — APPROVED** [review]

**Comment by marsam** [comment]
Apparently, this bump breaks `man-pages` on Darwin.  I guess /dev/stdin behaves different on Darwin. 

```
...
INSTALL         /nix/store/3s28l9ijlkmsq8256zdxjvl173gkn37c-man-pages-6.7/share/man/man3/addseverity.3
INSTALL         /nix/store/3s28l9ijlkmsq8256zdxjvl173gkn37c-man-pages-6.7/share/man/man3/adjtime.3
install: skipping file '/dev/stdin', as it was replaced while being copied
make: *** [share/mk/install/man.mk:54: /nix/store/3s28l9ijlkmsq8256zdxjvl173gkn37c-man-pages-6.7/share/man/man3/addmntent.3] Error 1
make: *** Waiting for unfinished jobs....
install: skipping file '/dev/stdin', as it was replaced while being copied
make: *** [share/mk/install/man.mk:54: /nix/store/3s28l9ijlkmsq8256zdxjvl173gkn37c-man-pages-6.7/share/man/man3/acosh.3] Error 1
install: skipping file '/dev/stdin', as it was replaced while being copied
install: skipping file '/dev/stdin', as it was replaced while being copied
install: skipping file '/dev/stdin', as it was replaced while being copied
...
```
Would you mind marking it as broken on Darwin?

**Comment by Pablo1107** [comment]
> Apparently, this bump breaks `man-pages` on Darwin. I guess /dev/stdin behaves different on Darwin.
> 
> ```
> ...
> INSTALL         /nix/store/3s28l9ijlkmsq8256zdxjvl173gkn37c-man-pages-6.7/share/man/man3/addseverity.3
> INSTALL         /nix/store/3s28l9ijlkmsq8256zdxjvl173gkn37c-man-pages-6.7/share/man/man3/adjtime.3
> install: skipping file '/dev/stdin', as it was replaced while being copied
> make: *** [share/mk/install/man.mk:54: /nix/store/3s28l9ijlkmsq8256zdxjvl173gkn37c-man-pages-6.7/share/man/man3/addmntent.3] Error 1
> make: *** Waiting for unfinished jobs....
> install: skipping file '/dev/stdin', as it was replaced while being copied
> make: *** [share/mk/install/man.mk:54: /nix/store/3s28l9ijlkmsq8256zdxjvl173gkn37c-man-pages-6.7/share/man/man3/acosh.3] Error 1
> install: skipping file '/dev/stdin', as it was replaced while being copied
> install: skipping file '/dev/stdin', as it was replaced while being copied
> install: skipping file '/dev/stdin', as it was replaced while being copied
> ...
> ```
> 
> Would you mind marking it as broken on Darwin? Edit: not a blocker for merge

Shouldn't have this been a blocker for merge tho? Since this package it's everywhere.

Is there any workarounds for us Nix Darwin users?

**Comment by trofi** [comment]
Looking at the failure.

**Comment by trofi** [comment]
Filed https://bugzilla.kernel.org/show_bug.cgi?id=218730 upstream.

**Comment by alejandro-colomar** [comment]
Huh!  I'm quite surprised that this is the only issue you experience in Darwin.  Since the fix seems easy for the man-pages project, I'll fix it.  I'll try to have a release soon, so that you don't need to be patching it.

**Comment by alejandro-colomar** [comment]
Also, would you mind reporting a bug to your install(1) vendor?  I don't think I'm doing anything unreasonable by installing /dev/stdin.

**Comment by alejandro-colomar** [comment]
Since I'm here...

Would you mind reporting any other inconveniences that you may be suffering or patching in the Linux man-pages, and which you'd like to be fixed upstream?

Have a lovely day!
Alex

**Comment by eli-schwartz** [comment]
> Would you mind reporting any other inconveniences that you may be suffering or patching in the Linux man-pages, and which you'd like to be fixed upstream?

Simple Makefiles are not actually simple. This is a pretty big inconvenience. :)

> Also, would you mind reporting a bug to your install(1) vendor? I don't think I'm doing anything unreasonable by installing /dev/stdin.

Not all the world's a cookie-cutter GNU/Linux. Why do you think it's a bug?

Note this error message comes from GNU coreutils, not Apple.

**Comment by alejandro-colomar** [comment]
> > Would you mind reporting any other inconveniences that you may be suffering or patching in the Linux man-pages, and which you'd like to be fixed upstream?
> 
> Simple Makefiles are not actually simple. This is a pretty big inconvenience. :)

If you can point to specific inconveniences of this Makefile, such as non-standard behavior, I may be able to help.

I know my simple makefiles are actually not that simple.  But I still consider them simpler than the alternatives.  We agree to disagree here.  :)
Still, I'm willing to help to make any inconveniences in them less inconvenient, if possible.  I recently reorganized them to be easier to understand.

> > Also, would you mind reporting a bug to your install(1) vendor? I don't think I'm doing anything unreasonable by installing /dev/stdin.
> 
> Not all the world's a cookie-cutter GNU/Linux. Why do you think it's a bug?

Because why would a pipe be a problem for installing?  Just create the file, suck the input file in a loop, and write to file what you get from the input file (in this case the input pipe).

> 
> Note this error message comes from GNU coreutils, not Apple.

Hmm, more reason to fix the bug.  At least we don't need to convince the fruit store.

**Comment by trofi** [comment]
Another inconvenience we had to do is to use ` "SHELL=env"`. By default `nixpkgs` passes `SHELL=/path/to/bash` which clobbered default value of:

```
GNUmakefile:SHELL       := /usr/bin/env
GNUmakefile:.SHELLFLAGS := -S '$(BASH) -Eeuo pipefail -c'
```

and the resulting errors was a big head scratch when `bash` started complaining about `-S` option.

`nixpkgs` does not provide `/usr/bin/env` binary in the build sandbox,

**Comment by eli-schwartz** [comment]
> Because why would a pipe be a problem for installing? Just create the file, suck the input file in a loop, and write to file what you get from the input file (in this case the input pipe).

It's not a pipe, it's an on-disk file that is probably a symlink to something that resolves to the same thing that the stdin file descriptor does...

**Comment by alejandro-colomar** [comment]
> Another inconvenience we had to do is to use ` "SHELL=env"`. By default `nixpkgs` passes `SHELL=/path/to/bash` which clobbered default value of:
> 
> ```
> GNUmakefile:SHELL       := /usr/bin/env
> GNUmakefile:.SHELLFLAGS := -S '$(BASH) -Eeuo pipefail -c'
> ```
> 
> and the resulting errors was a big head scratch when `bash` started complaining about `-S` option.
> 
> `nixpkgs` does not provide `/usr/bin/env` binary in the build sandbox,

Hmmm.  I can fix that one.  Since make(1) doesn't need a path, and it works with just the program name, I can use `env` instead of `/usr/bin/env`.  Out of curiosity, where do you have env(1)?

Also, since I don't need to specify the fine name, calling `bash` directly might be just as good, and we can avoid the weirdness of using env(1).

How about this?

```makefile
SHELL := bash
.SHELLFLAGS := -Eeuo pipefail -c
```

**Comment by alejandro-colomar** [comment]
Please try the following branch.  It should fix both the _install_(1) and the `$SHELL` issues.

<https://www.alejandro-colomar.es/src/alx/linux/man-pages/man-pages.git/log/?h=contrib>

If you confirm it's good for you, I'll push the changes to master.

**Comment by eli-schwartz** [comment]
> Please try the following branch. It should fix both the _install_(1) and the `$SHELL` issues.
> 
> https://www.alejandro-colomar.es/src/alx/linux/man-pages/man-pages.git/log/?h=contrib

I tried, but...

> Warning: Potential Security Risk Ahead
> 
> Firefox detected a potential security threat and did not continue to www.alejandro-colomar.es. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

Is Jia Tan in your website? What happened to https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/ ?

**Comment by alejandro-colomar** [comment]
> > Please try the following branch. It should fix both the _install_(1) and the `$SHELL` issues.
> > https://www.alejandro-colomar.es/src/alx/linux/man-pages/man-pages.git/log/?h=contrib
> 
> I tried, but...
> 
> > Warning: Potential Security Risk Ahead
> > Firefox detected a potential security threat and did not continue to [www.alejandro-colomar.es](http://www.alejandro-colomar.es). If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.
> 
> Is Jia Tan in your website?

Nope :)  It's documented here: <https://www.alejandro-colomar.es/ssl>.  You can verify the SSL certificate against my PGP key.  If you find any issues trusting my SSL cert (maybe I issued it with some unsafe parameters; I'm no SSL expert at all), please let me know.

> What happened to https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/ ?

There's the master branch, but I push changes to my own server before.  Since this change is provisional, waiting for you to test them, I haven't pushed yet to <kernel.org>.  All git commits are PGP-signed, so if the server is tampered with, the signatures would be broken.

**Comment by alejandro-colomar** [comment]
> > > Please try the following branch. It should fix both the _install_(1) and the `$SHELL` issues.
> > > https://www.alejandro-colomar.es/src/alx/linux/man-pages/man-pages.git/log/?h=contrib
> > 
> > 
> > I tried, but...
> > > Warning: Potential Security Risk Ahead
> > > Firefox detected a potential security threat and did not continue to [www.alejandro-colomar.es](http://www.alejandro-colomar.es). If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.
> > 
> > 
> > Is Jia Tan in your website?
> 
> Nope :) It's documented here: http://www.alejandro-colomar.es/ssl (Edit: changed https to http link). You can verify the SSL certificate against my PGP key. If you find any issues trusting my SSL cert (maybe I issued it with some unsafe parameters; I'm no SSL expert at all), please let me know.
> 
> > What happened to https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/ ?
> 
> There's the master branch, but I push changes to my own server before. Since this change is provisional, waiting for you to test it, I haven't pushed yet to <kernel.org>. All git commits are PGP-signed, so if the server is tampered with, the signatures would be broken.

Now that I see that cert, it has `Certificate Authority  Yes`.  That's bad.  I should emit a cert that's not a CA.  If only openssl(1) was easier to use...

**Comment by pixelb** [comment]
What version of darwin is this? I can't repro on Darwin 21.6.0 (MacOSX 12.6).
The issue is that /dev/stdin returns a varying inode which GNU install(1) doesn't like

**Comment by trofi** [comment]
> Please try the following branch. It should fix both the _install_(1) and the `$SHELL` issues.
> 
> https://www.alejandro-colomar.es/src/alx/linux/man-pages/man-pages.git/log/?h=contrib
> 
> If you confirm it's good for you, I'll push the changes to master.

I noticed it's already in `master`. Works for me as is on `darwin` test box. Tested againt commit edae09f52109d240facd2c71c2f13c062ed084ad "share/mk/: build-pdf-book: Fix chapter bookmarks".

Thank you!

One more minor problem I noticed is that darwin has a case-insensitive filesystem by default. It lumps these two together in a single file:

```
$ find -iname nan.3
./man3/NAN.3
./man3/nan.3
$ find -iname _Exit.2
./man2/_Exit.2
./man2/_exit.2
```

`git` complains that one of the file as always clobbered. And installed man page is probably incorrect.

Don't know if `man` allows for file names to differ from entries it contains.

**Comment by trofi** [comment]
> What version of darwin is this? I can't repro on Darwin 21.6.0 (MacOSX 12.6). The issue is that /dev/stdin returns a varying inode which GNU install(1) doesn't like

This one is something older:

```
$ uname -a
Darwin tests-iMac.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64
```

I'll ask what `nixpkgs` `hydra` CI uses.

**Comment by alejandro-colomar** [comment]
> > Please try the following branch. It should fix both the _install_(1) and the `$SHELL` issues.
> > https://www.alejandro-colomar.es/src/alx/linux/man-pages/man-pages.git/log/?h=contrib
> > If you confirm it's good for you, I'll push the changes to master.
> 
> I noticed it's already in `master`. Works for me as is on `darwin` test box. Tested againt commit edae09f52109d240facd2c71c2f13c062ed084ad "share/mk/: build-pdf-book: Fix chapter bookmarks".
> 
> Thank you!

You're welcome :-)

> One more minor problem I noticed is that darwin has a case-insensitive filesystem by default. It lumps these two together in a single file:
> 
> ```
> $ find -iname nan.3
> ./man3/NAN.3
> ./man3/nan.3
> $ find -iname _Exit.2
> ./man2/_Exit.2
> ./man2/_exit.2
> ```

Yup.  I knew about this one.  I guess you'll have to live with it.  I don't see a solution.  Maybe try to use a different file system.

> 
> `git` complains that one of the file as always clobbered. And installed man page is probably incorrect.

Yeah, I reproduced it in the past, when I had a macbook in a job.  Also in a Windows computer (back when I used Windows for games :).  I wasn't able to do man-pages' stuff there.

> Don't know if `man` allows for file names to differ from entries it contains.

I'm not sure if I understand what you say.  Can you reword?

**Comment by trofi** [comment]
> > Don't know if `man` allows for file names to differ from entries it contains.
> 
> I'm not sure if I understand what you say. Can you reword?

Does `man 2 _Exit` always have to imply `_Exit.2` file name? Or is there a way to encode an indirection that would allow having a different file name?

**Comment by alejandro-colomar** [comment]
> > > Don't know if `man` allows for file names to differ from entries it contains.
> > 
> > 
> > I'm not sure if I understand what you say. Can you reword?
> 
> Does `man 2 _Exit` always have to imply `_Exit.2` file name? Or is there a way to encode an indirection that would allow having a different file name?

Hmmm.  There's a way.

**If** man(7) cannot find a file with that name (ignoring case), it will try to find a page with that name by looking at the `NAME` sections of each page.

So you will need to store both pages with dummy file names, such as `_exit_lowercase_dummy.2` and `_exit_uppercase_dummy.2`, and then, it will work.

See an experiment:

```
alx@debian:~/tmp/man$ ls
foo.7  qwe.7
alx@debian:~/tmp/man$ cat foo.7 
.TH bar 7 today experiment
.SH Name
baz
\-
Store a page with a different file name
alx@debian:~/tmp/man$ cat qwe.7 
.TH Bar 7 today experiment
.SH Name
Baz
\-
Store a page with a different file name
alx@debian:~/tmp/man$ sudo cp * /usr/local/man/man7
alx@debian:~/tmp/man$ sudo mandb >/dev/null
Updating index cache for path `/usr/local/man/man7'. Wait...done.
alx@debian:~/tmp/man$ man 7 bar | cat
No manual entry for bar in section 7
alx@debian:~/tmp/man$ man 7 baz | cat
bar(7)              Miscellaneous Information Manual             bar(7)

Name
     baz - Store a page with a different file name

experiment                       today                           bar(7)
alx@debian:~/tmp/man$ man 7 Baz | cat
Bar(7)              Miscellaneous Information Manual             Bar(7)

Name
     Baz - Store a page with a different file name

experiment                       today                           Bar(7)
```

But if you store a page with the name `baz.7` or `baZ.7` or anything like that, it will have preference always.

**Comment by alejandro-colomar** [comment]
> > > > Don't know if `man` allows for file names to differ from entries it contains.
> > > 
> > > 
> > > I'm not sure if I understand what you say. Can you reword?
> > 
> > 
> > Does `man 2 _Exit` always have to imply `_Exit.2` file name? Or is there a way to encode an indirection that would allow having a different file name?
> 
> Hmmm. There's a way.
> 
> **If** man(7) cannot find a file with that name (ignoring case), it will try to find a page with that name by looking at the `NAME` sections of each page.
> 
> So you will need to store both pages with dummy file names, such as `_exit_lowercase_dummy.2` and `_exit_uppercase_dummy.2`, and then, it will work.
> 
> See an experiment:
> 
> ```
> alx@debian:~/tmp/man$ ls
> foo.7  qwe.7
> alx@debian:~/tmp/man$ cat foo.7 
> .TH bar 7 today experiment
> .SH Name
> baz
> \-
> Store a page with a different file name
> alx@debian:~/tmp/man$ cat qwe.7 
> .TH Bar 7 today experiment
> .SH Name
> Baz
> \-
> Store a page with a different file name
> alx@debian:~/tmp/man$ sudo cp * /usr/local/man/man7
> alx@debian:~/tmp/man$ sudo mandb >/dev/null
> Updating index cache for path `/usr/local/man/man7'. Wait...done.
> alx@debian:~/tmp/man$ man 7 bar | cat
> No manual entry for bar in section 7
> alx@debian:~/tmp/man$ man 7 baz | cat
> bar(7)              Miscellaneous Information Manual             bar(7)
> 
> Name
>      baz - Store a page with a different file name
> 
> experiment                       today                           bar(7)
> alx@debian:~/tmp/man$ man 7 Baz | cat
> Bar(7)              Miscellaneous Information Manual             Bar(7)
> 
> Name
>      Baz - Store a page with a different file name
> 
> experiment                       today                           Bar(7)
> ```
> 
> But if you store a page with the name `baz.7` or `baZ.7` or anything like that, it will have preference always.

However, there's a caveat: `man _exit.2` will not work.  See in my example:

```
$ man Baz.7 | cat
No manual entry for Baz.7
```

**Comment by deliciouslytyped** [comment]
@trofi @marsam Why does this remove the manpath fix?
https://github.com/NixOS/nixpkgs/pull/300797/files#diff-3ba2ce83a72b6085a66e9971f4b5187c53b36fece5a7720ac968219d1b4657b2L21

**Comment by trofi** [comment]
`man x25` seems to work as is on `NixOS`. I'll try to uninstall it systemwide, will check if `nix-shell -p` needs that `bin` back and have a look why `PATH` workaround is important.

**Comment by trofi** [comment]
Proposed the restored workaround as https://github.com/NixOS/nixpkgs/pull/308363

**Comment by trofi** [comment]
Proposed the `darwin` fix by pulling current `master` snapshot (it's a bit hard to cherry-pick an individual fix due to churn in nearby commits in makefiles): https://github.com/NixOS/nixpkgs/pull/312813

**Comment by alejandro-colomar** [comment]
I will release today, if that helps you.

**Comment by trofi** [comment]
Yeah, that would help `nixpkgs` and other distributions that allow `darwin` as a build host. Thank you!

**Comment by alejandro-colomar** [comment]
> Yeah, that would help `nixpkgs` and other distributions that allow `darwin` as a build host. Thank you!

:-)

I was delaying it a little bit becase Gentoo still hasn't released 6.7; they are (rightfully) a little bit paranoic after the xz events, and are scrutinizing all the churn I've applied to the build system lately.  :-)

**Pull request merged**
