### PR TITLE
nc4nix: init at unstable-2022-08-06

### PR DESCRIPTION
**Pull request by onny**
###### Description of changes

nc4nix is a packaging helper script for Nextcloud apps on NixOS, see https://git.helsinki.tools/helsinki-systems/nc4nix

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
@dasJ @ajs124 Could you please add a license information upstream?

**Comment by dasJ** [comment]
I'm not the author so no

**Comment by onny** [comment]
Since there's no upstream information about the license, I'm adding this here as `unfree`

**Comment by mweinelt** [comment]
The repo does not seem to be available anymore.

**Comment by happysalada** [comment]
@onny could you make a follow up PR to remive this ?

**Comment by onny** [comment]
> @onny could you make a follow up PR to remive this ?

here's my update https://github.com/NixOS/nixpkgs/pull/200885

**Comment by zimbatm** [comment]
For future reference, we should refrain from adding packages that have either:
* no release - this means the project is not stable yet
* no license - this causes some concerns regarding the distribution of the project

If you encounter this situation, try to work with upstream, or use your personal repository to hold the package. After all, Nix makes it easy to maintain different package sets.

**Comment by happysalada** [comment]
understood, thanks for taking the time to come here and explain.

**Pull request merged**
