### PR TITLE
virtualbox service: add support for vboxsf guest filesystem

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @aszlig

**Comment by aszlig** [comment]
LGTM but haven't tested it yet, feel free to merge (currently busy with other things).

**Comment by offlinehacker** [comment]
Works for us with following options:

    fileSystems."/run/secrets" = {
      device = "secrets";
      fsType = "vboxsf";
      options = "uid=0,gid=0";
    };

You have to set options option, or there will be error, this is because we are forcing "defaults,relatime" options by default, which mount.vboxsf does not accept.

**Comment by aszlig** [comment]
Going to merge this in along with a few more changes and with a test.

**Pull request closed without merging**
