### PR TITLE
organicmaps: 2023.08.18-8 -> 2023.11.17-17

### PR DESCRIPTION
**Pull request by fgaz**
Release: https://github.com/organicmaps/organicmaps/releases/tag/2023.11.17-17-android

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
I think this commit completely broke the map rendering. Depending on the driver you get a segmentation fault, black screen, or black screen with a single-colored wedge.
The only Mesa driver that somehow manages to render the map without crashing is softpipe.

It took me a while to figure this out because I had to bisect Nixpkgs including the OpenGL drivers with [nixGL](https://github.com/nix-community/nixGL):
```nix
let 
  pkgs = import /home/rnhmjoj/src/nixpkgs { };
  nixgl = pkgs.callPackage ./nixGL.nix { enable32bits = false; };
  omaps = pkgs.organicmaps;
in
  pkgs.writeShellScript "test" ''
    ${nixgl.nixGLIntel}/bin/nixGLIntel ${omaps}/bin/OMaps
  ''
```

Result:

```
   $ git bisect bad
   30f3d0d98fe5012316f80643ee8a09f9295bb053 is the first bad commit
   commit 30f3d0d98fe5012316f80643ee8a09f9295bb053
   Author: Francesco Gazzetta <fgaz@fgaz.me>
   Date:   Fri Nov 17 16:50:38 2023 +0100
   
       organicmaps: 2023.08.18-8 -> 2023.11.17-17
       
       Release: https://github.com/organicmaps/organicmaps/releases/tag/2023.11.17-17-android
   
    pkgs/applications/misc/organicmaps/default.nix | 6 ++++--
    1 file changed, 4 insertions(+), 2 deletions(-)
```

I'm now bisecting the upstream repository: 2023.09.22-27 is bad already and I guess https://github.com/organicmaps/organicmaps/commit/1adbb8b59434ef4c82580db00af8abcf75646bdc maybe the cause.

**Comment by fgaz** [comment]
Oof. Thank you for your work @rnhmjoj. Unfortunately I couldn't test this with hardware acceleration at the time because my gpu was too old

**Comment by rnhmjoj** [comment]
Ok, the issue with this commit was actually unrelated to the OpenGL one. I was thrown off by https://github.com/organicmaps/organicmaps/pull/5823, which causes an unrelated segfault and was only fixed
with https://github.com/organicmaps/organicmaps/pull/7485, in a version with the OpenGL issue.

I'm still bisecting...

**Comment by rnhmjoj** [comment]
Ok, found it: it was the update to Qt 6.7 (2c35581d1df9).

**Comment by fgaz** [comment]
Tracking issue: #331344

**Pull request merged**
