### PR TITLE
OWNERS, teams: jetbrains: add theCapypara, create jetbrains team

### PR DESCRIPTION
**Pull request by theCapypara**
I want to help with reviewing and maintaining the Jetbrains IDEs on nixpkgs. Having had a small PR stuck in limbo for a while and seeing that updates were a bit slow recently, I want to help improve this situation :)

I also thought it might be a good idea to create a team now that we already have a few people, I already talked with @leona-ya about this, but let me know if you think this isn't a good idea!

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by theCapypara** [comment]
Ah I wasn't aware of that requirement for code owners, is there anything I need to do or can/should I not be code owner in this case?

**Comment by leona-ya** [comment]
You need to be in the org. Can you add an entry for yourself in the `maintainers/maintainer-list.nix` in an extra commit, please. Then a bot will add you to the NixOS GitHub org.

**Comment by theCapypara** [comment]
I'm already in the maintainer list.

**Comment by infinisil** [comment]
@theCapypara Looks like you [missed the automated invite](https://github.com/NixOS/nixpkgs/issues/234293), but I just sent another one, check your emails. After accepting, CI should succeed :)

**Comment by theCapypara** [comment]
Ah yes, thanks! I just checked my mails, I did indeed miss it, a shame that GitHub still doesn't show notifications for this on-site, I mostly ignore mails from GitHub normally. I accepted the invite :)

**Comment by infinisil** [comment]
I triggered a rerun of the failing job :)

**Review by leona-ya — APPROVED** [review]

**Pull request merged**
