### PR TITLE
makeHardcodeGsettingsPatch: Support other constructors

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

Also move it out to a separate file since glib expression is messy enough as is. And add tests.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Weirdly, the tests do not want to eval for some reason:

```ShellSession
$ nix-build -A makeHardcodeGsettingsPatch.tests
error: cannot evaluate a function that has an argument without a value ('src')

       Nix attempted to evaluate a function as a top level expression; in
       this case it must have its arguments supplied either by default
       values, or passed explicitly with '--arg' or '--argstr'. See
       https://nixos.org/manual/nix/stable/expressions/language-constructs.html#functions.

       at /home/jtojnar/Projects/nixpkgs/pkgs/build-support/make-hardcode-gsettings-patch/default.nix:41:7:

           40|     {
           41|       src,
             |       ^
           42|       schemaIdToVariableMapping,
```

And while I am able to build it in `nix repl`:

```nix
nix-repl> :b makeHardcodeGsettingsPatch {
            src = ./pkgs/build-support/make-hardcode-gsettings-patch/test;
            schemaIdToVariableMapping = {
              "org.gnome.evolution-data-server.addressbook" = "EDS";
              "org.gnome.evolution.calendar" = "EVO";
            };
          }

This derivation produced the following outputs:
  out -> /nix/store/f3xci4y7bl3mm68bsv9w4ry9q87sa5sr-hardcode-gsettings.patch
```

But the produced output is an empty file.

**Comment by symphorien** [comment]
@GrahamcOfBorg build evolutionWithPlugins

**Comment by symphorien** [comment]
the test you added will fail if coccinnelle changes whitespace. Maybe run the code through a formatter before comparing?

**Comment by jtojnar** [comment]
Thanks, done.

**Review by symphorien — APPROVED** [review]

**Pull request merged**
