### PR TITLE
Fix monero-gui build

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Fix for #36453 

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested by running node and remote client
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rnhmjoj** [comment]
@LnL7 Sorry to bother you but could you please see what's the problem on darwin?

**Comment by LnL7** [comment]
a missing framework but qtwebengine is also broken, it's output seems to be empty not sure what's up with that.

**Comment by fpletz** [comment]
Thanks! Testing now.

**Comment by fpletz** [comment]
`monero-wallet-gui` fails to start for me:

```
app startd
available width:  1920
available height:  1080
devicePixelRatio:  1
screen height:  1920
screen width:  1080
screen logical dpi:  96
screen Physical dpi:  176.271
screen calculated ratio:  1.37712
QQmlApplicationEngine failed to load component
qrc:///main.qml:1043 Type StandardDialog unavailable
qrc:///components/StandardDialog.qml:30 module "QtQuick.Controls" version 2.0 is not installed

Error: no root objects
```

**Comment by rnhmjoj** [comment]
@fpletz: Did you install it with nix-env? Running Qt apps from `./result/bin/` doesn't generally work.
I also noticed it crashes with the cache generated by previous versions of monero-gui, so you may have to delete it: it's located in `$XDG_CACHE_HOME/monero-project`

**Comment by fpletz** [comment]
Ah, it has be installed via nix-env or in systemPackages. Works. :+1:

**Comment by rnhmjoj** [comment]
Thank you.

**Pull request merged**
