### PR TITLE
nixos/httpd: module cleanup

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
- nixos/httpd: drop `stateDir` option, hardcode to `/run/httpd`
  - module cleanup in preparation for allowing `httpd` service to run as non root user
- nixos/httpd: allow user to specify a minimal list of apache modules
  - currently no way to remove unwanted/unneeded apache `mod_` modules
  - in security certain restricted environments a goal is to reduce the number of apache modules to a bare minimum and any extra modules (`mod_dav`, for example) present an unacceptable security risk

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg test proxy

**Comment by aanderse** [comment]
@jglukasik any interest in testing and approving?

**Review by flokli — APPROVED** [review]
I agree with the changes in here (but haven't tested myself).

Thanks a lot for doing this!

We might want to also drop `logDir`, and use `LogsDirectory` aswell.

**Comment by aanderse** [comment]
The plan is to use `journald` when next release of `apache` is out. More changes coming down the pipe and I plan to address the `logDir` soon.

Thanks!

**Pull request merged**
