### PR TITLE
mattermost_6: init at 6.2.1, revert mattermost to 5.37.6

### PR DESCRIPTION
**Pull request by numinit**
###### Motivation for this change

Followup to #119200. Allow users to stay on Mattermost 5.37.6 and choose to use Mattermost 6 if they want via services.mattermost.package.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by numinit** [comment]
I think I'm going to take a stab at building the webapp ourselves next...

**Comment by mohe2015** [comment]
I assume this PR breaks your server as it would downgrade it again?

Also what about a mattermost-lts and mattermost-latest?

I think there is some work in a previous PR regarding building the webapp so search for that before starting.

**Comment by numinit** [comment]
@mohe2015 If someone was using master nixpkgs, then yes. At the same time, it's called unstable for a reason.

**Comment by numinit** [comment]
@ryantm brought up a good enough reason with the extended support release version that it's probably a good idea to stick with that anyway. I didn't know what our update policy was with Mattermost until the discussion on #119200, but I think that's a good line in the sand.

**Comment by numinit** [comment]
Confirmed that the tests are passing locally. My laptop doesn't have big-parallel so had to wait for Hydra to build QEMU.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 153141` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>mattermost</li>
    <li>mattermost_6</li>
  </ul>
</details>

**Comment by happysalada** [comment]
I don't see any problem with this PR. Leaving 2 days of grace for other people to comment, just in case.

**Comment by happysalada** [comment]
Regarding building the webapp. At the moment there is an initiative to improve the js ecosystem with something called dream2nix. Mattermost is one of the project that is aimed at being built. From my small experience trying to package it. They use the latest and greatest (nodejs 16, dependencies up to date, latest webpack). There are some weird behaviors between yarn and npm (different packages get installed depending on which package manager you use, it's relatively rare). On a positive note, I would imagine it's only a matter of time before they switch their build process to esbuild, it should make things much easier.  Just saying that if it proves a challenge, hopefully you don't burn out on trying to package the webapp.

**Comment by ryantm** [comment]
I don't think we should do this because I'd rather not break people using unstable. I'm aIso not convinced we have enough contributors to warrant  maintaining different mattermost versions. If someone really wants the ESR line, we should pick it back up after the release the one starting with 6.

**Comment by numinit** [comment]
Fair enough. Took me 15 minutes to throw together, figured we ought to have options. :smile:

**Pull request closed without merging**
