### PR TITLE
tree-wide: Switch from gnome3.maintainers to lib.teams.gnome

### PR DESCRIPTION
**Pull request by jtojnar**

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Things I found to be missing

* vala
* glib
* graphene
* gtk
* gtk-doc

All the gnome modules

**Comment by jtojnar** [comment]
I only switched from the old attribute here since it blocks its removal. Tweaking the attributes needs to be done manually so I will leave it to next update of the expressions.

**Review by worldofpeace — APPROVED** [review]
I have a PR for nixos coming.

**Comment by worldofpeace** [comment]
#84059

**Pull request merged**
