### PR TITLE
nixos: add script to automatically update nix-fallback-paths

### PR DESCRIPTION
**Pull request by Mic92**
This replicates
https://github.com/NixOS/nix/blob/68ba6ff4709d936c1a714de35da08f8ed354c710/maintainers/upload-release.pl#L241

however it can be run by everyone and not just eelco with s3 access. We often have the issue that this file goes out-of-date, so having this script in nixpkgs, now ever nixpkgs contributor can update this file.

This allows to make security releases faster without having privileged access to avoid situations as in https://discourse.nixos.org/t/nar-unpacking-vulnerability-post-mortem/52301

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Mic92** [comment]
With this change ever nix maintainer who can create tags on github, could also do a release of nixpkgs.

**Comment by edolstra** [comment]
Not sure I understand the use case. The only reason for updating `nix-fallback-paths` is when there is a new release, and those all include a `fallback-paths.nix` file.

If the issue is that not everybody can run the release script, then that's what we should fix - we shouldn't have multiple divergent release processes. (If I understand this PR correctly, it would result in releases that are tagged in Git but that don't exist on https://releases.nixos.org/ and wouldn't appear on the Nix download page.)

**Comment by Mic92** [comment]
The issue with vendoring to nix releases only is though that we not regularly can rebuild those fallback paths. i.e. let's say we would some vulnerability in curl or openssl. Nix upstream doesn't really track the security of any of its libraries and makes releases based on that. So I am wondering if we should instead have our own release builds in nixpkgs instead that can be bumped independently.

**Comment by roberth** [comment]
While I do agree with Eelco about having one release process, I think we can still use https://github.com/NixOS/nix/pull/11565 to make the process easier to understand, and easier to check, and easier to use or abuse in a pinch. It just needs to replace some perl code by a simpler download.

**Pull request closed without merging**
