### PR TITLE
Set virtualisation.libvirtd.qemuOvmf to false

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Repeating https://github.com/NixOS/nixpkgs/pull/25855
Its changes were lost somehow.

### CODE REVIEW

**Comment by bjornfor** [comment]
As far as I can tell, those changes (#25855) were never merged. Instead of setting that option to false, due to big closure size, the closure size was reduced with commit https://github.com/NixOS/nixpkgs/commit/252dcd62f39ec9163832805dd41286c75f802530.

What's the size difference with/without qemuOvmf now? Is the size a problem?

**Comment by volth** [comment]
not sure about the size yet, just tried to unset ```qemuOvmf=false``` assuming it is already the default and nix downloaded tons of packages and started build python-2.7.x from sources... so I have cancelled it.

**Comment by joachifm** [comment]
`OVMF.fd` is 4mbs. Seems more appropriate for you to set this in your own config.

**Comment by volth** [comment]
4 Mb here for a needless feature, 28Mb for needless mysql, XXMb for needless btrfs, ... then no wonder that minimal nixos is so huge. Also, each of such needless features may bring its vulnerabilities.

**Comment by joachifm** [comment]
The libvirt closure is ~600 MB. If you're going for minimalism ...

**Comment by volth** [comment]
@joachifm Yes, ```qemu = qemu-x86only``` would be a sane default too on x86 hosts
But at least it could be set in an overlay, only once.

```virtualisation.libvirtd = { enable = false; qemuOvmf = false; };``` contaminated many configs. And must be maintained as the list of enabled-by-default features could grow.

**Comment by bjornfor** [comment]
Here is my reasoning for wanting UEFI support in libvirt by default. Physical machines have UEFI. Thus virtual machines should have UEFI too.

**Comment by volth** [comment]
Then it is a strange place to add the option.
1. It is only for libvirt, qemu without libvirt (for example test-driver) lacks it
2. It is only for NixOS, not for those who use nixpkgs on Darwin or Ubuntu
3. ```withOvmf``` in qemu package is easier to override globally than a module option

**Comment by joachifm** [comment]
xen has a build-time option (`withOVMF`), but qemu supports ovmf out-of-the-box. The command-line syntax for using the split ovmf is a bit cumbersome, granted. OVMF is used in the test suite.

**Pull request closed without merging**
