### PR TITLE
 home-assistant: 0.92.2 -> 0.93.2

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
It seems the asynctest bump leads to one `mitmproxy` check failing:

Result of `nix-review pr 61754`
<details>
  <summary>1 package failed to build:</summary>

  - mitmproxy
</details>
<details>
  <summary>7 package were build:</summary>

  - home-assistant
  - home-assistant-cli
  - python37Packages.aioresponses
  - python37Packages.asynctest
  - python37Packages.pyatv
  - python37Packages.pyhomematic
  - python37Packages.zeep
</details>

---
The failing test trace:
```log
__________ TestTermLog.test_output[None-expected_out0-expected_err0] ___________

self = <test.mitmproxy.addons.test_termlog.TestTermLog object at 0x7fffeb8d4940>
outfile = None, expected_out = ['one', 'three'], expected_err = ['four']
capfd = <_pytest.capture.CaptureFixture object at 0x7fffeb8cc5c0>

    @pytest.mark.usefixtures('capfd')
    @pytest.mark.parametrize('outfile, expected_out, expected_err', [
        (None, ['one', 'three'], ['four']),
        (sys.stdout, ['one', 'three', 'four'], []),
        (sys.stderr, [], ['one', 'three', 'four']),
    ])
    def test_output(self, outfile, expected_out, expected_err, capfd):
    # ...
```

**Comment by dotlambda** [comment]
@GrahamcOfBorg test home-assistant

**Comment by dotlambda** [comment]
@c0bw3b That bump was already merged in #61880.

**Comment by dotlambda** [comment]
@GrahamcOfBorg build mitmproxy

**Comment by c0bw3b** [comment]
It still builds fine [on Hydra](https://hydra.nixos.org/job/nixpkgs/trunk/mitmproxy.x86_64-linux) so I guess my local test was a transient failure...

**Pull request merged**
