### PR TITLE
gutenberg: init at 0.3.1

### PR DESCRIPTION
**Pull request by mnacamura**
###### Motivation for this change

Reboot of #30737.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mnacamura** [comment]
Built successfully on macOS but failed on NixOS:
```
...
   Compiling rayon v0.8.2
   Compiling serde_derive_internals v0.16.0
   Compiling walkdir v0.1.8
   Compiling miow v0.1.5
   Compiling ws v0.7.3
   Compiling hyper v0.10.13
error: failed to acquire jobserver token

Caused by:
  Resource temporarily unavailable (os error 11)
builder for ‘/nix/store/6k94frs8fwk4cczdmnscy6zsfjvy9d7h-gutenberg-0.2.2.drv’ failed with exit code 101
error: build of ‘/nix/store/6k94frs8fwk4cczdmnscy6zsfjvy9d7h-gutenberg-0.2.2.drv’ failed
```

Seems related to https://github.com/rust-lang/rust/issues/46981.

**Comment by Mic92** [comment]
@GrahamcOfBorg build gutenberg

**Comment by Mic92** [comment]
At least it is reproducible.

**Comment by mnacamura** [comment]
Note: version bump from 0.2.2 to 0.3.0 needs rust 1.23 https://github.com/pest-parser/pest/issues/190

**Comment by joachifm** [comment]
@GrahamcOfBorg build gutenberg

**Comment by Mic92** [comment]
@GrahamcOfBorg build gutenberg

**Comment by Mic92** [comment]
maybe this is fixed with the latest rust update.

**Comment by mnacamura** [comment]
Bumped version to 0.3.1. It builds successfully. I think it can be merged.

**Comment by mnacamura** [comment]
Squashed.

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
