### PR TITLE
gst_all_1.gst-plugins-rs: 0.11.0+fixup -> 0.11.3

### PR DESCRIPTION
**Pull request by lilyinstarlight**
## Description of changes

Bumps gst-plugins-rs to 0.11.3: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/0.11.3/CHANGELOG.md#0113-2023-12-18

This reduces the number of hacks we need (yay!), namely the need to patch out optional/unused deps like gstreamer-webrtc or gstreamer-gl

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
  - [x] x86_64-linux -> aarch64-linux (cross)
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
Hi @lilyinstarlight, it looks like `gst-plugins-rs` has moved to a new versioning scheme.

Any chance you can update this to `gstreamer-1.23.1` tag?

**Comment by colemickens** [comment]
I guess we're not on gstreamer-1.23 yet? But anyway, there's also a `gstreamer-1.22.8` (seems to be what we have in `master`) and `gstreamer-1.22.9` tag

**Comment by lilyinstarlight** [comment]
> Hi @lilyinstarlight, it looks like gst-plugins-rs has moved to a new versioning scheme.
> 
> Any chance you can update this to gstreamer-1.23.1 tag? (If that is correct? I think that's what they've done...)

It is not a new versioning scheme and has always been done like this. Those `gstreamer-` tags just mark commits associated with a given gstreamer suite release, and is based on an older branch without much of a compelling reason for us to use

From <https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/470#note_2202772>:

> I would recommend always using the latest stable release, i.e. 0.11.2 at this point.

So upstream recommends using the newer versions, I guess (and we have the update script args matching upstream's recommendation)

> I guess we're not on gstreamer-1.23 yet?

Odd gstreamer releases like 1.23 are alpha-quality and not intended to be packaged and we would wait for 1.24

From <https://gstreamer.freedesktop.org/documentation/frequently-asked-questions/getting.html?gi-language=c#what-is-the-difference-between-versions-010-and-10>

> Odd-numbered versions such as 0.9.x, 0.11.x, 1.3.x, 1.5.x, 1.7.x etc. are unstable developer releases that should generally not be used.

**Comment by colemickens** [comment]
Oh no. :( Thanks for the very detailed explanation, and for your work on this. I'll give this a test !

**Comment by lilyinstarlight** [comment]
> Thanks for the very detailed explanation, and for your work on this.

I'll add comments explaining the tag stuff (at least that upstream recommends the non-`gstreamer-` tags) since i'm sure you're not the only person who will be confused by this. I do appreciate you checking and reviewing this PR though <3

**Comment by lilyinstarlight** [comment]
Closing in favor of #305665

**Pull request closed without merging**
