### PR TITLE
puddletag: fix wrapping

### LINKED ISSUE #212738: Puddletag fails to run
### Describe the bug
Recently, we fixed `puddletag`: https://github.com/NixOS/nixpkgs/pull/201599. However, on `nixpkgs-unstable`, `puddletag` still fails to run on my machine throughing the dreaded:

```
puddletag Version: 2.2.0
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

### Steps To Reproduce
1. nix run nixpkgs#puddletag

### Additional context
The application seems to be correctly wrapped:

```
! /nix/store/pj1hnyxhcsw1krmhnbb9rjvqssbzliw8-bash-5.2-p15/bin/bash -e
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/41yj61kv18cpx7rh4gbrzankxb0r1xd2-python3.10-PyQt5-5.15.7/bin'':'/':'}
PATH='/nix/store/41yj61kv18cpx7rh4gbrzankxb0r1xd2-python3.10-PyQt5-5.15.7/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
```
but still, it does not work.

### Notify maintainers
@peterhoeg and myself.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.89, NixOS, 23.05 (Stoat), 23.05.20230124.e10dc5b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.1`
 - nixpkgs: `/nix/store/6m80n2j1kc4px881n75sp3yx6gblsc56-source`
```

### PR DESCRIPTION
**Pull request by tejing1**
###### Description of changes

Closes #212738

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tejing1** [comment]
I'm not familiar with qt stuff, so I'd appreciate a review from someone who actually knows best practices for that ecosystem.

**Review by dschrempf — COMMENTED** [review]
See my comment at https://github.com/NixOS/nixpkgs/issues/212738.

**Comment by dschrempf** [comment]
Hi! I was referring to the comment https://github.com/NixOS/nixpkgs/issues/212738#issuecomment-1410761903.

Do you also observe the crash when checking `About`? (I think this is unrelated to this PR, but should be fixed).

**Comment by tejing1** [comment]
Yes:
```
Traceback (most recent call last):
  File "/nix/store/p780knsy1ck1bxamzjlsvfwx19bpd7cn-puddletag-2.2.0/lib/python3.10/site-packages/puddlestuff/mainwin/funcs.py", line 493, in show_about
    win = about.AboutPuddletag(parent)
  File "/nix/store/p780knsy1ck1bxamzjlsvfwx19bpd7cn-puddletag-2.2.0/lib/python3.10/site-packages/puddlestuff/about.py", line 97, in __init__
    ['%s: %s' % (lib, version) for (lib, version) in versions().items()]
  File "/nix/store/p780knsy1ck1bxamzjlsvfwx19bpd7cn-puddletag-2.2.0/lib/python3.10/site-packages/puddlestuff/about.py", line 67, in versions
    'Chromaprint': get_module_version('chromaprint'),
  File "/nix/store/p780knsy1ck1bxamzjlsvfwx19bpd7cn-puddletag-2.2.0/lib/python3.10/site-packages/puddlestuff/about.py", line 50, in get_module_version
    module = import_module(module_name)
  File "/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/hn3l9hgbh202vs0h3mi993zv0k6l1bbh-python3.10-pyacoustid-1.2.2/lib/python3.10/site-packages/chromaprint.py", line 57, in <module>
    raise ImportError("couldn't find libchromaprint")
ImportError: couldn't find libchromaprint
zsh: IOT instruction (core dumped)  ./result/bin/puddletag
```
I'm not sure how to go about fixing it, though.

**Review by dschrempf — APPROVED** [review]
I see, thank you!

**Pull request merged**
