### PR TITLE
JetBrains: 2023.1.4 -> 2023.2

### PR DESCRIPTION
**Pull request by YarekTyshchenko**
## Description of changes

Update JetBrains editors via script to 2023.2 mainly for Rider
Some plugins were updated too.

Newer version of Rider requires dotnet 7 sdk, which I switched to use from `dotnetCorePackages`.

Release notes:
- Rider: https://blog.jetbrains.com/dotnet/2023/08/02/rider-2023-2-release/
- PhpStorm: https://blog.jetbrains.com/phpstorm/2023/08/phpstorm-2023-2-is-now-available/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by YarekTyshchenko** [comment]
Result of `nixpkgs-review pr 248795` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.rider</li>
  </ul>
</details>

**Comment by dritter** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/pull/247219

**Review by namebee — APPROVED** [review]

**Comment by YarekTyshchenko** [comment]
@dritter, @raphaelr, @tymscar I assume you're interested in maintaining Rider on NixOs. Have either of you figured out how to make it detect dotnet without symlinking the combined dir into `/opt/dotnet`? I thought it might be looking at DOTNET_ROOT env var, but it isn't.

Even with the symlink rider doesn't run the project properly:
```
You must install .NET to run this application.

App: /home/yarek/Work/<snip>/bin/Debug/net7.0/<snip>
Architecture: x64
App host version: 7.0.9
.NET location: Not found
```

`dotnet --info` does look alright though.

This page explains all the gubbins required https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#net-sdk-and-cli-environment-variables

**Comment by YarekTyshchenko** [comment]
closing as duplicate

**Pull request closed without merging**
