### PR TITLE
python3Packages.pymemcache: 3.4.4 -> 3.5.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 3.5.0

Change log: https://github.com/pinterest/pymemcache/releases/tag/v3.5.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130431` at f791cbb4 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/6dc0e332d44a99d47b6b72c94da18176">buku</a></li>
    <li><a href="https://gist.github.com/a21dc85d35eb76246dc946c19de1a4b0">python38Packages.gradient</a></li>
    <li><a href="https://gist.github.com/73b9c7f73ce96471701fcbf6b26c1bc9">python38Packages.tokenizers</a></li>
    <li><a href="https://gist.github.com/d7678a79fcb76c9479676f7114cf93b0">python38Packages.transformers</a></li>
    <li><a href="https://gist.github.com/26c633f47a3a44e12d28a3cd029a70bd">python39Packages.gradient</a></li>
    <li><a href="https://gist.github.com/01a4e910853fa1525ecf6b3e9387d880">python39Packages.tokenizers</a></li>
    <li><a href="https://gist.github.com/d0a10b13d2d11a0991331e104649d630">python39Packages.transformers</a></li>
  </ul>
</details>
<details>
  <summary>39 packages skipped due to time constraints:</summary>
  <ul>
    <li>home-assistant</li>
    <li>lexicon</li>
    <li>nixops</li>
    <li>python38Packages.batchgenerators</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.clifford</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-glm</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-ml</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>103 packages built successfully:</summary>
  <ul>
    <li>azure-cli</li>
    <li>haskellPackages.nvfetcher</li>
    <li>http-prompt</li>
    <li>httpie</li>
    <li>mastodon-archive</li>
    <li>nvchecker (python38Packages.nvchecker)</li>
    <li>nvfetcher</li>
    <li>papis (python38Packages.papis)</li>
    <li>python38Packages.aplpy</li>
    <li>python38Packages.asdf</li>
    <li>python38Packages.dask</li>
    <li>python38Packages.dask-image</li>
    <li>python38Packages.datadog</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.deezer-python</li>
    <li>python38Packages.duecredit</li>
    <li>python38Packages.fastparquet</li>
    <li>python38Packages.flask-limiter</li>
    <li>python38Packages.fsspec</li>
    <li>python38Packages.gcsfs</li>
    <li>python38Packages.glymur</li>
    <li>python38Packages.gradient_statsd</li>
    <li>python38Packages.habanero</li>
    <li>python38Packages.hangups</li>
    <li>python38Packages.httpbin</li>
    <li>python38Packages.image-match</li>
    <li>python38Packages.imagecorruptions</li>
    <li>python38Packages.johnnycanencrypt</li>
    <li>python38Packages.knack</li>
    <li>python38Packages.mastodon-py</li>
    <li>python38Packages.mechanicalsoup</li>
    <li>python38Packages.pims</li>
    <li>python38Packages.pubnub</li>
    <li>python38Packages.pubnubsub-handler</li>
    <li>python38Packages.pyfftw</li>
    <li>python38Packages.pymemcache</li>
    <li>python38Packages.pyregion</li>
    <li>python38Packages.pytest-astropy</li>
    <li>python38Packages.pytest-astropy-header</li>
    <li>python38Packages.pytest-httpbin</li>
    <li>python38Packages.pytest-vcr</li>
    <li>python38Packages.python-awair</li>
    <li>python38Packages.pywemo</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.qiskit-ibmq-provider</li>
    <li>python38Packages.reproject</li>
    <li>python38Packages.restfly</li>
    <li>python38Packages.s3fs</li>
    <li>python38Packages.scikitimage</li>
    <li>python38Packages.slicedimage</li>
    <li>python38Packages.sparse</li>
    <li>python38Packages.stytra</li>
    <li>python38Packages.tensorly</li>
    <li>python38Packages.tumpa</li>
    <li>python38Packages.vcrpy</li>
    <li>python38Packages.yalexs</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.asdf</li>
    <li>python39Packages.batchgenerators</li>
    <li>python39Packages.dask</li>
    <li>python39Packages.dask-image</li>
    <li>python39Packages.datadog</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.deezer-python</li>
    <li>python39Packages.duecredit</li>
    <li>python39Packages.flask-limiter</li>
    <li>python39Packages.fsspec</li>
    <li>python39Packages.gcsfs</li>
    <li>python39Packages.glymur</li>
    <li>python39Packages.gradient_statsd</li>
    <li>python39Packages.habanero</li>
    <li>python39Packages.hangups</li>
    <li>python39Packages.httpbin</li>
    <li>python39Packages.image-match</li>
    <li>python39Packages.imagecorruptions</li>
    <li>python39Packages.johnnycanencrypt</li>
    <li>python39Packages.knack</li>
    <li>python39Packages.mastodon-py</li>
    <li>python39Packages.mechanicalsoup</li>
    <li>python39Packages.nvchecker</li>
    <li>python39Packages.papis</li>
    <li>python39Packages.pims</li>
    <li>python39Packages.pubnub</li>
    <li>python39Packages.pubnubsub-handler</li>
    <li>python39Packages.pyfftw</li>
    <li>python39Packages.pymemcache</li>
    <li>python39Packages.pyregion</li>
    <li>python39Packages.pytest-astropy</li>
    <li>python39Packages.pytest-astropy-header</li>
    <li>python39Packages.pytest-httpbin</li>
    <li>python39Packages.pytest-vcr</li>
    <li>python39Packages.python-awair</li>
    <li>python39Packages.pywemo</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-ibmq-provider</li>
    <li>python39Packages.reproject</li>
    <li>python39Packages.restfly</li>
    <li>python39Packages.s3fs</li>
    <li>python39Packages.scikitimage</li>
    <li>python39Packages.slicedimage</li>
    <li>python39Packages.tumpa</li>
    <li>python39Packages.vcrpy</li>
    <li>python39Packages.yalexs</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 130431` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.clifford</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.rl-coach</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.rl-coach</li>
  </ul>
</details>
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li>buku</li>
    <li>home-assistant</li>
    <li>lexicon</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.gradient</li>
    <li>python38Packages.imgaug</li>
    <li>python38Packages.mask-rcnn</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.tokenizers</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.gradient</li>
    <li>python39Packages.tokenizers</li>
    <li>python39Packages.transformers</li>
  </ul>
</details>
<details>
  <summary>129 packages built:</summary>
  <ul>
    <li>azure-cli</li>
    <li>haskellPackages.nvfetcher</li>
    <li>http-prompt</li>
    <li>httpie</li>
    <li>mastodon-archive</li>
    <li>nixops</li>
    <li>nvchecker (python38Packages.nvchecker)</li>
    <li>nvfetcher</li>
    <li>papis (python38Packages.papis)</li>
    <li>python38Packages.aplpy</li>
    <li>python38Packages.asdf</li>
    <li>python38Packages.batchgenerators</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.dask</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-glm</li>
    <li>python38Packages.dask-image</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.datadog</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.deezer-python</li>
    <li>python38Packages.distributed</li>
    <li>python38Packages.duecredit</li>
    <li>python38Packages.fastparquet</li>
    <li>python38Packages.flask-limiter</li>
    <li>python38Packages.fsspec</li>
    <li>python38Packages.gcsfs</li>
    <li>python38Packages.glymur</li>
    <li>python38Packages.gradient_statsd</li>
    <li>python38Packages.habanero</li>
    <li>python38Packages.hangups</li>
    <li>python38Packages.httpbin</li>
    <li>python38Packages.image-match</li>
    <li>python38Packages.imagecorruptions</li>
    <li>python38Packages.intake</li>
    <li>python38Packages.johnnycanencrypt</li>
    <li>python38Packages.knack</li>
    <li>python38Packages.mastodon-py</li>
    <li>python38Packages.mechanicalsoup</li>
    <li>python38Packages.pims</li>
    <li>python38Packages.pubnub</li>
    <li>python38Packages.pubnubsub-handler</li>
    <li>python38Packages.pyfftw</li>
    <li>python38Packages.pymemcache</li>
    <li>python38Packages.pyregion</li>
    <li>python38Packages.pytenable</li>
    <li>python38Packages.pytest-astropy</li>
    <li>python38Packages.pytest-astropy-header</li>
    <li>python38Packages.pytest-httpbin</li>
    <li>python38Packages.pytest-vcr</li>
    <li>python38Packages.python-awair</li>
    <li>python38Packages.pywemo</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.qiskit-ibmq-provider</li>
    <li>python38Packages.reproject</li>
    <li>python38Packages.restfly</li>
    <li>python38Packages.s3fs</li>
    <li>python38Packages.scikitimage</li>
    <li>python38Packages.slicedimage</li>
    <li>python38Packages.sparse</li>
    <li>python38Packages.spectral-cube</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.stytra</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.tensorly</li>
    <li>python38Packages.tumpa</li>
    <li>python38Packages.vcrpy</li>
    <li>python38Packages.yalexs</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.asdf</li>
    <li>python39Packages.batchgenerators</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.dask</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-glm</li>
    <li>python39Packages.dask-image</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.datadog</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.deezer-python</li>
    <li>python39Packages.distributed</li>
    <li>python39Packages.duecredit</li>
    <li>python39Packages.flask-limiter</li>
    <li>python39Packages.fsspec</li>
    <li>python39Packages.gcsfs</li>
    <li>python39Packages.glymur</li>
    <li>python39Packages.gradient_statsd</li>
    <li>python39Packages.habanero</li>
    <li>python39Packages.hangups</li>
    <li>python39Packages.httpbin</li>
    <li>python39Packages.image-match</li>
    <li>python39Packages.imagecorruptions</li>
    <li>python39Packages.imgaug</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.johnnycanencrypt</li>
    <li>python39Packages.knack</li>
    <li>python39Packages.mask-rcnn</li>
    <li>python39Packages.mastodon-py</li>
    <li>python39Packages.mechanicalsoup</li>
    <li>python39Packages.nvchecker</li>
    <li>python39Packages.papis</li>
    <li>python39Packages.pims</li>
    <li>python39Packages.pubnub</li>
    <li>python39Packages.pubnubsub-handler</li>
    <li>python39Packages.pyfftw</li>
    <li>python39Packages.pymemcache</li>
    <li>python39Packages.pyregion</li>
    <li>python39Packages.pytenable</li>
    <li>python39Packages.pytest-astropy</li>
    <li>python39Packages.pytest-astropy-header</li>
    <li>python39Packages.pytest-httpbin</li>
    <li>python39Packages.pytest-vcr</li>
    <li>python39Packages.python-awair</li>
    <li>python39Packages.pywemo</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-ibmq-provider</li>
    <li>python39Packages.reproject</li>
    <li>python39Packages.restfly</li>
    <li>python39Packages.s3fs</li>
    <li>python39Packages.scikitimage</li>
    <li>python39Packages.slicedimage</li>
    <li>python39Packages.spectral-cube</li>
    <li>python39Packages.streamz</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.tumpa</li>
    <li>python39Packages.vcrpy</li>
    <li>python39Packages.yalexs</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 130431` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>python38Packages.clifford</li>
<li>python38Packages.dask-jobqueue</li>
<li>python38Packages.dask-xgboost</li>
<li>python38Packages.rl-coach</li>
<li>python39Packages.dask-jobqueue</li>
<li>python39Packages.dask-xgboost</li>
<li>python39Packages.rl-coach</li>
</ul>
</details>
<details>

  <summary>12 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>buku: log was empty</li>
<li>home-assistant: log was empty</li>
<li>lexicon: log was empty</li>
<li>python38Packages.gradient: log was empty</li>
<li>python38Packages.spacy-transformers: log was empty</li>
<li>python38Packages.streamz: log was empty</li>
<li>python38Packages.tokenizers: log was empty</li>
<li>python38Packages.transformers: log was empty</li>
<li>python39Packages.gradient: log was empty</li>
<li>python39Packages.streamz: log was empty</li>
<li>python39Packages.tokenizers: log was empty</li>
<li>python39Packages.transformers: log was empty</li>
  </ul>
</details>
<details>

  <summary>77 packages failed to build and are new build failures:</summary>
  <ul>
<li>python38Packages.aplpy: log was empty</li>
<li>python38Packages.asdf: log was empty</li>
<li>python38Packages.glymur: log was empty</li>
<li>python38Packages.image-match: log was empty</li>
<li>python38Packages.imagecorruptions: log was empty</li>
<li>python38Packages.imgaug: log was empty</li>
<li>python38Packages.mask-rcnn: log was empty</li>
<li>python38Packages.pyregion: log was empty</li>
<li>python38Packages.pytest-astropy: log was empty</li>
<li>python38Packages.pytest-astropy-header: log was empty</li>
<li>python38Packages.reproject: log was empty</li>
<li>python38Packages.slicedimage: log was empty</li>
<li>python38Packages.spectral-cube: log was empty</li>
<li>python38Packages.stumpy: log was empty</li>
<li>python38Packages.stytra: log was empty</li>
<li>python38Packages.sunpy: log was empty</li>
<li>python38Packages.tensorly: log was empty</li>
<li>python38Packages.tumpa: log was empty</li>
<li>python38Packages.yalexs: log was empty</li>
<li>python39Packages.aplpy: log was empty</li>
<li>python39Packages.asdf: log was empty</li>
<li>python39Packages.batchgenerators: log was empty</li>
<li>python39Packages.caffe: log was empty</li>
<li>python39Packages.dask: log was empty</li>
<li>python39Packages.dask-gateway: log was empty</li>
<li>python39Packages.dask-glm: log was empty</li>
<li>python39Packages.dask-image: log was empty</li>
<li>python39Packages.dask-mpi: log was empty</li>
<li>python39Packages.datadog: log was empty</li>
<li>python39Packages.datasets: log was empty</li>
<li>python39Packages.deezer-python: log was empty</li>
<li>python39Packages.distributed: log was empty</li>
<li>python39Packages.duecredit: log was empty</li>
<li>python39Packages.flask-limiter: log was empty</li>
<li>python39Packages.fsspec: log was empty</li>
<li>python39Packages.gcsfs: log was empty</li>
<li>python39Packages.glymur: log was empty</li>
<li>python39Packages.gradient_statsd: log was empty</li>
<li>python39Packages.habanero: log was empty</li>
<li>python39Packages.hangups: log was empty</li>
<li>python39Packages.httpbin: log was empty</li>
<li>python39Packages.image-match: log was empty</li>
<li>python39Packages.imagecorruptions: log was empty</li>
<li>python39Packages.imgaug: log was empty</li>
<li>python39Packages.intake: log was empty</li>
<li>python39Packages.johnnycanencrypt: log was empty</li>
<li>python39Packages.knack: log was empty</li>
<li>python39Packages.mask-rcnn: log was empty</li>
<li>python39Packages.mastodon-py: log was empty</li>
<li>python39Packages.mechanicalsoup: log was empty</li>
<li>python39Packages.nvchecker: log was empty</li>
<li>python39Packages.papis: log was empty</li>
<li>python39Packages.pims: log was empty</li>
<li>python39Packages.pubnub: log was empty</li>
<li>python39Packages.pubnubsub-handler: log was empty</li>
<li>python39Packages.pyfftw: log was empty</li>
<li>python39Packages.pymemcache: log was empty</li>
<li>python39Packages.pyregion: log was empty</li>
<li>python39Packages.pytenable: log was empty</li>
<li>python39Packages.pytest-astropy: log was empty</li>
<li>python39Packages.pytest-astropy-header: log was empty</li>
<li>python39Packages.pytest-httpbin: log was empty</li>
<li>python39Packages.pytest-vcr: log was empty</li>
<li>python39Packages.python-awair: log was empty</li>
<li>python39Packages.pywemo: log was empty</li>
<li>python39Packages.qiskit: log was empty</li>
<li>python39Packages.qiskit-ibmq-provider: log was empty</li>
<li>python39Packages.reproject: log was empty</li>
<li>python39Packages.restfly: log was empty</li>
<li>python39Packages.s3fs: log was empty</li>
<li>python39Packages.scikitimage: log was empty</li>
<li>python39Packages.slicedimage: log was empty</li>
<li>python39Packages.spectral-cube: log was empty</li>
<li>python39Packages.sunpy: log was empty</li>
<li>python39Packages.tumpa: log was empty</li>
<li>python39Packages.vcrpy: log was empty</li>
<li>python39Packages.yalexs: log was empty</li>
  </ul>
</details>
<details>
<summary>
53 packages built:
</summary>
<ul>
<li>azure-cli</li>
<li>haskellPackages.nvfetcher</li>
<li>http-prompt</li>
<li>httpie</li>
<li>mastodon-archive</li>
<li>nixops</li>
<li>nvchecker (python38Packages.nvchecker)</li>
<li>nvfetcher</li>
<li>papis (python38Packages.papis)</li>
<li>python38Packages.batchgenerators</li>
<li>python38Packages.caffe</li>
<li>python38Packages.dask</li>
<li>python38Packages.dask-gateway</li>
<li>python38Packages.dask-glm</li>
<li>python38Packages.dask-image</li>
<li>python38Packages.dask-ml</li>
<li>python38Packages.dask-mpi</li>
<li>python38Packages.datadog</li>
<li>python38Packages.datasets</li>
<li>python38Packages.datashader</li>
<li>python38Packages.deezer-python</li>
<li>python38Packages.distributed</li>
<li>python38Packages.duecredit</li>
<li>python38Packages.fastparquet</li>
<li>python38Packages.flask-limiter</li>
<li>python38Packages.fsspec</li>
<li>python38Packages.gcsfs</li>
<li>python38Packages.gradient_statsd</li>
<li>python38Packages.habanero</li>
<li>python38Packages.hangups</li>
<li>python38Packages.httpbin</li>
<li>python38Packages.intake</li>
<li>python38Packages.johnnycanencrypt</li>
<li>python38Packages.knack</li>
<li>python38Packages.mastodon-py</li>
<li>python38Packages.mechanicalsoup</li>
<li>python38Packages.pims</li>
<li>python38Packages.pubnub</li>
<li>python38Packages.pubnubsub-handler</li>
<li>python38Packages.pyfftw</li>
<li>python38Packages.pymemcache</li>
<li>python38Packages.pytenable</li>
<li>python38Packages.pytest-httpbin</li>
<li>python38Packages.pytest-vcr</li>
<li>python38Packages.python-awair</li>
<li>python38Packages.pywemo</li>
<li>python38Packages.qiskit</li>
<li>python38Packages.qiskit-ibmq-provider</li>
<li>python38Packages.restfly</li>
<li>python38Packages.s3fs</li>
<li>python38Packages.scikitimage</li>
<li>python38Packages.sparse</li>
<li>python38Packages.vcrpy</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 130431` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
10 packages marked as broken and skipped:
</summary>
<ul>
<li>python38Packages.clifford</li>
<li>python38Packages.dask-jobqueue</li>
<li>python38Packages.dask-xgboost</li>
<li>python38Packages.rl-coach</li>
<li>python38Packages.spacy-transformers</li>
<li>python39Packages.clifford</li>
<li>python39Packages.dask-jobqueue</li>
<li>python39Packages.dask-xgboost</li>
<li>python39Packages.rl-coach</li>
<li>python39Packages.spacy-transformers</li>
</ul>
</details>
<details>

  <summary>6 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>python38Packages.gradient: log was empty</li>
<li>python38Packages.tokenizers: log was empty</li>
<li>python38Packages.transformers: log was empty</li>
<li>python39Packages.gradient: log was empty</li>
<li>python39Packages.tokenizers: log was empty</li>
<li>python39Packages.transformers: log was empty</li>
  </ul>
</details>
<details>
<summary>
143 packages built:
</summary>
<ul>
<li>azure-cli</li>
<li>buku</li>
<li>haskellPackages.nvfetcher</li>
<li>home-assistant</li>
<li>http-prompt</li>
<li>httpie</li>
<li>lexicon</li>
<li>mastodon-archive</li>
<li>nixops</li>
<li>nvchecker (python39Packages.nvchecker)</li>
<li>nvfetcher</li>
<li>papis (python39Packages.papis)</li>
<li>python38Packages.aplpy</li>
<li>python38Packages.asdf</li>
<li>python38Packages.batchgenerators</li>
<li>python38Packages.caffe</li>
<li>python38Packages.dask</li>
<li>python38Packages.dask-gateway</li>
<li>python38Packages.dask-glm</li>
<li>python38Packages.dask-image</li>
<li>python38Packages.dask-ml</li>
<li>python38Packages.dask-mpi</li>
<li>python38Packages.datadog</li>
<li>python38Packages.datasets</li>
<li>python38Packages.datashader</li>
<li>python38Packages.deezer-python</li>
<li>python38Packages.distributed</li>
<li>python38Packages.duecredit</li>
<li>python38Packages.fastparquet</li>
<li>python38Packages.flask-limiter</li>
<li>python38Packages.fsspec</li>
<li>python38Packages.gcsfs</li>
<li>python38Packages.glymur</li>
<li>python38Packages.gradient_statsd</li>
<li>python38Packages.habanero</li>
<li>python38Packages.hangups</li>
<li>python38Packages.httpbin</li>
<li>python38Packages.image-match</li>
<li>python38Packages.imagecorruptions</li>
<li>python38Packages.imgaug</li>
<li>python38Packages.intake</li>
<li>python38Packages.johnnycanencrypt</li>
<li>python38Packages.knack</li>
<li>python38Packages.mask-rcnn</li>
<li>python38Packages.mastodon-py</li>
<li>python38Packages.mechanicalsoup</li>
<li>python38Packages.nvchecker</li>
<li>python38Packages.papis</li>
<li>python38Packages.pims</li>
<li>python38Packages.pubnub</li>
<li>python38Packages.pubnubsub-handler</li>
<li>python38Packages.pyfftw</li>
<li>python38Packages.pymemcache</li>
<li>python38Packages.pyregion</li>
<li>python38Packages.pytenable</li>
<li>python38Packages.pytest-astropy</li>
<li>python38Packages.pytest-astropy-header</li>
<li>python38Packages.pytest-httpbin</li>
<li>python38Packages.pytest-vcr</li>
<li>python38Packages.python-awair</li>
<li>python38Packages.pywemo</li>
<li>python38Packages.qiskit</li>
<li>python38Packages.qiskit-ibmq-provider</li>
<li>python38Packages.reproject</li>
<li>python38Packages.restfly</li>
<li>python38Packages.s3fs</li>
<li>python38Packages.scikitimage</li>
<li>python38Packages.slicedimage</li>
<li>python38Packages.sparse</li>
<li>python38Packages.spectral-cube</li>
<li>python38Packages.streamz</li>
<li>python38Packages.stumpy</li>
<li>python38Packages.stytra</li>
<li>python38Packages.sunpy</li>
<li>python38Packages.tensorly</li>
<li>python38Packages.tumpa</li>
<li>python38Packages.vcrpy</li>
<li>python38Packages.yalexs</li>
<li>python39Packages.aplpy</li>
<li>python39Packages.asdf</li>
<li>python39Packages.batchgenerators</li>
<li>python39Packages.caffe</li>
<li>python39Packages.dask</li>
<li>python39Packages.dask-gateway</li>
<li>python39Packages.dask-glm</li>
<li>python39Packages.dask-image</li>
<li>python39Packages.dask-ml</li>
<li>python39Packages.dask-mpi</li>
<li>python39Packages.datadog</li>
<li>python39Packages.datasets</li>
<li>python39Packages.datashader</li>
<li>python39Packages.deezer-python</li>
<li>python39Packages.distributed</li>
<li>python39Packages.duecredit</li>
<li>python39Packages.fastparquet</li>
<li>python39Packages.flask-limiter</li>
<li>python39Packages.fsspec</li>
<li>python39Packages.gcsfs</li>
<li>python39Packages.glymur</li>
<li>python39Packages.gradient_statsd</li>
<li>python39Packages.habanero</li>
<li>python39Packages.hangups</li>
<li>python39Packages.httpbin</li>
<li>python39Packages.image-match</li>
<li>python39Packages.imagecorruptions</li>
<li>python39Packages.imgaug</li>
<li>python39Packages.intake</li>
<li>python39Packages.johnnycanencrypt</li>
<li>python39Packages.knack</li>
<li>python39Packages.mask-rcnn</li>
<li>python39Packages.mastodon-py</li>
<li>python39Packages.mechanicalsoup</li>
<li>python39Packages.pims</li>
<li>python39Packages.pubnub</li>
<li>python39Packages.pubnubsub-handler</li>
<li>python39Packages.pyfftw</li>
<li>python39Packages.pymemcache</li>
<li>python39Packages.pyregion</li>
<li>python39Packages.pytenable</li>
<li>python39Packages.pytest-astropy</li>
<li>python39Packages.pytest-astropy-header</li>
<li>python39Packages.pytest-httpbin</li>
<li>python39Packages.pytest-vcr</li>
<li>python39Packages.python-awair</li>
<li>python39Packages.pywemo</li>
<li>python39Packages.qiskit</li>
<li>python39Packages.qiskit-ibmq-provider</li>
<li>python39Packages.reproject</li>
<li>python39Packages.restfly</li>
<li>python39Packages.s3fs</li>
<li>python39Packages.scikitimage</li>
<li>python39Packages.slicedimage</li>
<li>python39Packages.sparse</li>
<li>python39Packages.spectral-cube</li>
<li>python39Packages.streamz</li>
<li>python39Packages.stumpy</li>
<li>python39Packages.stytra</li>
<li>python39Packages.sunpy</li>
<li>python39Packages.tensorly</li>
<li>python39Packages.tumpa</li>
<li>python39Packages.vcrpy</li>
<li>python39Packages.yalexs</li>
<li>tts</li>
</ul>
</details>

**Pull request merged**
