### PR TITLE
vimPlugins.vim-metamath: init at 2019-11-07

### PR DESCRIPTION
**Pull request by Taneb**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
I just merged an update a few minutes a go, do you mind rebasing, and then following https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs

you should have an update commit, then adding your package + another update

**Comment by Taneb** [comment]
Yes, sure. I'd misread the instructions, I'm afraid.

**Comment by Taneb** [comment]
@jonringer I've updated the PR

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM

```
[38 built, 1 copied, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/72990
20 package were build:
vimPlugins.ale vimPlugins.antonys-macro-repeater vimPlugins.coc-lists vimPlugins.coc-python vimPlugins.coc-tsserver vimPlugins.ctrlp-vim vimPlugins.denite-nvim vimPlugins.ghcid vimPlugins.iceberg-vim vimPlugins.ncm2-ultisnips vimPlugins.neosnippet-vim vimPlugins.neoterm vimPlugins.ultisnips vimPlugins.vim-lsc vimPlugins.vim-metamath vimPlugins.vim-pandoc vimPlugins.vim-snippets vimPlugins.vim-visual-multi vimPlugins.vimtex vimPlugins.zig-vim
```

weird that antonys-macro-repeater was added, but I don't think that was related to this PR

**Comment by jonringer** [comment]
no problem :), thanks for the PR

**Pull request merged**
