### PR TITLE
stdenv: prune libtool files by default

### PR DESCRIPTION
**Pull request by pbogdan**
###### Motivation for this change

Spotted in the wild:

```
# Generated by ltmain.sh - GNU libtool 1.5.22-OpenLDAP (1.1220.2.365 2005/12/18 22:14:06)
```

which `pruneLibtoolFiles` fails to prune as is.

/cc @orivej 

**EDIT**: now extended to pruning libtool files by default

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by orivej — APPROVED** [review]
Thank you!

Since it's already a mass rebuild, we could as well enable pruneLibtoolFiles by default. I don't expect any immediate effect, but it will make it easier to add new packages and will make it possible to unpropagate some otherwise private dependencies of existing packages.

**Comment by hedning** [comment]
:+1: on enabling by default. This seems like a pretty common issue, just recently upgrading [`hunspell`](https://github.com/NixOS/nixpkgs/issues/51297#issuecomment-443922832), [`cyrus_sasl`](https://github.com/NixOS/nixpkgs/pull/51651) and [`iptables`](https://github.com/NixOS/nixpkgs/pull/51252#issuecomment-445512680) caused downstream failures due to new `-l`s in the .la files. So there's definitely a risk with plain upgrades too.

**Comment by Mic92** [comment]
@matthewbauer I wonder if this would break `staticPkgs`?

**Comment by hedning** [comment]
It only prunes .la files where `old_library=''` which is meant to avoid breaking static builds, as I understand it.

**Comment by pbogdan** [comment]
It doesn't appear there's consensus / interest to move this forward at this time. Shall this be closed for now?

**Comment by orivej** [comment]
I'll do some testing and if there are no issues will merge to staging.

**Comment by orivej** [comment]
@pbogdan, thank you! These changes are exactly what I meant to be done.

**Comment by pbogdan** [comment]
Thank you @orivej!

**Comment by vcunat** [comment]
There were some regressions, but not too many and almost all trivial to fix: 64edccb46.

**Pull request merged**
