### PR TITLE
handheld-daemon: 1.1.0 -> 1.1.4

### PR DESCRIPTION
**Pull request by appsforartists**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by appsforartists** [comment]
@antheas would `/sys/kernel/config` suffice for this?

**Comment by antheas** [comment]
You can't create files in `/sys` as far as I know

**Comment by appsforartists** [comment]
It's already a mount-point for configfs though. You wouldn't have to create it.

I guess I should test if you can create folders inside that configfs mount-point.

**Comment by appsforartists** [comment]
```bash
mkdir /sys/kernel/config/iio
Permission denied
```
🫤

**Comment by antheas** [comment]
You can follow the steps in this file and if they work it will be fine:
https://github.com/hhd-dev/hhd/blob/c074cb0e3e13ab18fd150eb36df70044ede45038/src/hhd/controller/physical/imu.py#L415

Essentially, assume `$conf` is the mount dir.

```bash
sudo modprobe industrialio-sw-trigger
sudo modprobe iio-trig-sysfs
sudo modprobe iio-trig-hrtimer

sudo mkdir -p $conf
sudo mount -t configfs none $conf
sudo mkdir -p $conf/iio/triggers/hrtimer/hhd
```

Then at closing
```bash
sudo rmdir $conf/iio/triggers/hrtimer/hhd
```

Try running with `$conf` as `/sys/kernel/config`. Although I guess the mount command will fail if you do that.

**Comment by appsforartists** [comment]
Per @antheas:

> turns out writing to /var works fine
> so its not needed
> so you can close the PR

**Pull request closed without merging**
