### PR TITLE
Update docker-py to 1.2.2

### PR DESCRIPTION
**Pull request by np**

### CODE REVIEW

**Comment by np** [comment]
There seems to be no error in the log, just a timeout from Travis

**Comment by lethalman** [comment]
What about updating requests and websocket_client?

**Comment by domenkozar** [comment]
@np why are you using different versions of dependencies?

**Comment by domenkozar** [comment]
cc @offlinehacker

**Comment by Fuuzetsu** [comment]
@np ping? Can we get this rebased/questions answered or closed?

**Comment by np** [comment]
Looking at the requirements file for docker-py https://github.com/docker/docker-py/blob/master/requirements.txt makes explicit requirements for these versions.

**Comment by matthiasbeyer** [comment]
Commit message does not match [the guidelines](http://hydra.nixos.org/build/26115043/download/1/nixpkgs/manual.html#idm140737318595088)

**Comment by pSub** [comment]
@np are you still interested in this?

**Comment by domenkozar** [comment]
I've updated it to `1.5.0`, clsoing

**Pull request closed without merging**
