### PR TITLE
[20.09] instead: 3.3.1 -> 3.3.2; fix compilation

### PR DESCRIPTION
**Pull request by marius851000**
###### Motivation for this change
ZHF: #97479

backport of https://github.com/NixOS/nixpkgs/pull/97562

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

(note: result in the same derivation as https://github.com/NixOS/nixpkgs/pull/97562 as time of test)

### CODE REVIEW

**Comment by risicle** [comment]
When you do a cherry-pick, could you use the `-xe` flags so that we end up with a reference to the original commit in the commit message?

**Comment by jonringer** [comment]
When backporting changes, please follow https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes.

Namely, you should be doing `git cherry-pick -x <rev>` from a commit that has already landed in master. If the branches have diverged, you may alter the commit or add another commit to ensure that the package is able to still evaluate and build

**Comment by marius851000** [comment]
fixed this. Thank

**Comment by jonringer** [comment]
the referenced commit should be https://github.com/NixOS/nixpkgs/commit/43d9d1d7d8f558cbaa4ce386a7c3fb9be2b0d9c1which exists on master, the other commit was the one which existed on your fork

**Comment by marius851000** [comment]
done. Thank again

**Review by jonringer — APPROVED** [review]

**Pull request merged**
