### PR TITLE
nvidia-x11.stable: 455.45.01 -> 460.32.03

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Motivation for this change

Driver update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Tried it yesterday for Cyberpunk and AC via Proton. Not particularly more stable.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108795` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>linuxPackages_hardkernel_4_14.nvidia_x11</li>
<li>linuxPackages_hardkernel_latest.nvidia_x11</li>
</ul>
</details>
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>linuxPackages-libre.nvidia_x11: log was empty</li>
<li>python37Packages.cupy: log <a href="https://termbin.com/k2yv">https://termbin.com/k2yv</a></li>
<li>python38Packages.cupy: log <a href="https://termbin.com/o8ym">https://termbin.com/o8ym</a></li>
<li>python39Packages.cupy: log <a href="https://termbin.com/ylao">https://termbin.com/ylao</a></li>
  </ul>
</details>
<details>
<summary>
27 packages built:
</summary>
<ul>
<li>bumblebee</li>
<li>geekbench</li>
<li>linuxPackages.nvidia_x11 (linuxPackages_5_4.nvidia_x11)</li>
<li>linuxPackages_4_14.nvidia_x11</li>
<li>linuxPackages_4_19.nvidia_x11</li>
<li>linuxPackages_4_4.nvidia_x11</li>
<li>linuxPackages_4_9.nvidia_x11</li>
<li>linuxPackages_5_10.nvidia_x11 (linuxPackages_latest.nvidia_x11)</li>
<li>linuxPackages_5_9.nvidia_x11</li>
<li>linuxPackages_hardened.nvidia_x11</li>
<li>linuxPackages_latest-libre.nvidia_x11</li>
<li>linuxPackages_latest_hardened.nvidia_x11</li>
<li>linuxPackages_latest_xen_dom0.nvidia_x11</li>
<li>linuxPackages_latest_xen_dom0_hardened.nvidia_x11</li>
<li>linuxPackages_lqx.nvidia_x11</li>
<li>linuxPackages_testing_bcachefs.nvidia_x11</li>
<li>linuxPackages_xen_dom0.nvidia_x11</li>
<li>linuxPackages_xen_dom0_hardened.nvidia_x11</li>
<li>linuxPackages_zen.nvidia_x11</li>
<li>primus</li>
<li>psensor</li>
<li>python37Packages.TheanoWithCuda</li>
<li>python37Packages.pytorch-bin</li>
<li>python38Packages.TheanoWithCuda</li>
<li>python38Packages.pytorch-bin</li>
<li>python39Packages.TheanoWithCuda</li>
<li>python39Packages.pytorch-bin</li>
</ul>
</details>

**Comment by danieldk** [comment]
This version bump seems to have broken nvidia-settings.

**Comment by fabianhjr** [comment]
I aplogize, when this release landed there wasn't a corresponding release of nvidia-settings si I went with the latest 460 series  settings release.

I have no idea if passthrough settings will unbreak bumping it to `460.32.03` but could either open a revert or bump the settings version.

**Comment by baracoder** [comment]
Can confirm it working corresponding nvidia-settings version. Had it in a local branch and on my machine for a few days.

```
diff --git a/pkgs/os-specific/linux/nvidia-x11/default.nix b/pkgs/os-specific/linux/nvidia-x11/default.nix
index a57611ecb1d..423ce85e8c4 100644
--- a/pkgs/os-specific/linux/nvidia-x11/default.nix
+++ b/pkgs/os-specific/linux/nvidia-x11/default.nix
@@ -24,8 +24,7 @@ rec {
     then generic {
       version = "460.32.03";
       sha256_64bit = "0qb0f8djys55b7qgvpbwafw5lkwvmcslqz3i2kr3jm354gy248ag";
-      settingsVersion = "460.27.04";
-      settingsSha256 = "1z9ibkhyjqzhhzi3gj88f5jlpc1d76jsncsy6wxpnbdbak8ljkw5";
+      settingsSha256 = "dKBYoxbiMxWnB78VHo4gLLl5510zXBaO6S34RzTg01U=";
       persistencedSha256 = "36sM+djZmv77lGe7cdZ5tppzgkQD4IA0FJgCGsdZRI8=";
     }
     else legacy_390;
```

There is a warning in `dmesg` when starting nvidia-settings, but it works. This might be a bug in nvidia-settings
```
[162443.410254] NVRM: API mismatch: the client has the version 440.82, but
                NVRM: this kernel module has the version 460.32.03.  Please
                NVRM: make sure that this kernel module and all NVIDIA driver
                NVRM: components have the same version.

```

**Comment by greydot** [comment]
> This version bump seems to have broken `passthru.settings`:
> 
> ```
> nix-build -A linuxPackages.nvidia_x11.passthru.settings
> this derivation will be built:
>   /nix/store/4dbvnmar7mgsnpklf6jn1kly02wqf5g1-nvidia-settings-460.27.04.drv
> building '/nix/store/4dbvnmar7mgsnpklf6jn1kly02wqf5g1-nvidia-settings-460.27.04.drv'...
> unpacking sources
> unpacking source archive /nix/store/5cjb5wqp5jxmdhzldxmpywsc9gq048i6-source
> source root is source
> patching sources
> configuring
> no configure script, doing nothing
> building
> build flags: -j16 -l16 SHELL=/nix/store/zcl19h06322c3kss6bvf05w2pxg4kfll-bash-4.4-p23/bin/bash NV_USE_BUNDLED_LIBJANSSON=0
> make[1]: Entering directory '/build/source/src'
> /nix/store/zcl19h06322c3kss6bvf05w2pxg4kfll-bash-4.4-p23/bin/bash: _out/Linux_x86_64/antialias.png.h: No such file or directory
> make[1]: *** [Makefile:320: _out/Linux_x86_64/antialias.png.h] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make[1]: Leaving directory '/build/source/src'
> make: *** [Makefile:23: all] Error 2
> error: --- Error ----------------------------------------------------- nix-build
> builder for '/nix/store/4dbvnmar7mgsnpklf6jn1kly02wqf5g1-nvidia-settings-460.27.04.drv' failed with exit code 2; last 10 log lines:
>   configuring
>   no configure script, doing nothing
>   building
>   build flags: -j16 -l16 SHELL=/nix/store/zcl19h06322c3kss6bvf05w2pxg4kfll-bash-4.4-p23/bin/bash NV_USE_BUNDLED_LIBJANSSON=0
>   make[1]: Entering directory '/build/source/src'
>   /nix/store/zcl19h06322c3kss6bvf05w2pxg4kfll-bash-4.4-p23/bin/bash: _out/Linux_x86_64/antialias.png.h: No such file or directory
>   make[1]: *** [Makefile:320: _out/Linux_x86_64/antialias.png.h] Error 1
>   make[1]: *** Waiting for unfinished jobs....
>   make[1]: Leaving directory '/build/source/src'
>   make: *** [Makefile:23: all] Error 2
> ```

I don't have `passthru` enabled, but I get the same error :(

**Comment by fabianhjr** [comment]
Hey @danieldk, I observed similar errors recently but the odd thing is that rerunning the build will subsequently succeed. Seems like for some odd reason the nvidia-settings build became (or was) flaky.

**Pull request merged**
