### PR TITLE
gam: 6.25 -> 6.58

### PR DESCRIPTION
**Pull request by thanegill**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GabrielDougherty** [comment]
changelog: 

> Ross: fix crash on gam create project

from https://github.com/GAM-team/GAM/releases/tag/v6.52

**Comment by GabrielDougherty** [comment]
I got this error from `nix run nixpkgs#nixpkgs-review pr 221888`

```
error: undefined variable 'dateutil'

       at /home/gabriel/.cache/nixpkgs-review/pr-221888/nixpkgs/pkgs/tools/admin/gam/default.nix:27:5:

           26|   propagatedBuildInputs = with python3.pkgs; [
           27|     dateutil
             |     ^
           28|     distro
(use '--show-trace' to show detailed location information)
nix --experimental-features nix-command --system x86_64-linux eval --json --impure --no-allow-import-from-derivation --expr (import /nix/store/0gc4pxnrmxihkfmv4jjmmvqrpmbb42q0-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/nix/evalAttrs.nix { allowAliases = false; attr-json = /tmp/tmp78gaxfza; }) failed to run, /tmp/tmp78gaxfza was stored inspection
```

**Comment by thanegill** [comment]
@GabrielDougherty fixed the issue.

**Comment by GabrielDougherty** [comment]
Result of `nixpkgs-review pr 221888` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gam</li>
  </ul>
</details>

**Review by GabrielDougherty — APPROVED** [review]

**Pull request merged**
