### PR TITLE
README: Add badge for the # of PRs merged in 24 hours

### LINKED ISSUE #17114: Issue stats badges on readme.md don't load anymore
The "build: passing" badge works fine, but that comes from travis. The other two (that displayed stats about our PR merge rate and issue close rate) fail to load on all my devices.

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

Closes #17114 
cc: @domenkozar @copumpkin 

Should I remove the issuestats ones?

### CODE REVIEW

**Comment by grahamc** [comment]
PS: This created the branch in the nixos/nixpkgs repo, this is the first time making a PR this way and I'll be more careful next time. I'm sorry.

**Comment by bjornfor** [comment]
Merged or closed? Or just merged? (For simple PRs, I like to rebase and push on the command line. So I tend to close, not merge.)

**Comment by grahamc** [comment]
Good question. This number actually represents the PRs _closed_ within
24hrs of opening, merge or no merge.

**Comment by rasendubi** [comment]
This looks like `PRs closed in 24hrs | 56%`. I should say it's quite unintuitive and raises many questions. 

56% of what? PRs opened today? How closing two-day-old PRs influence the counter?

**Comment by grahamc** [comment]
Interesting, @rasendubi. I haven't heard that feedback before. Most feedback I've gotten has suggested it is fairly intuitive. I'd be happy to improve it if you have suggestions. It is the percent of PRs closed within 24 hours of opening.

**Comment by rasendubi** [comment]
@grahamc I must admit, I don't have any proposal. I still don't understand how two-day-old issues affect the counter.

I personally think that we already have issuestats badge and that's enough (it also provides more stats)

**Pull request closed without merging**
