### PR TITLE
neomutt: 20220429 -> 20230407

### PR DESCRIPTION
**Pull request by RaitoBezarius**
###### Description of changes

https://github.com/neomutt/neomutt/releases/tag/20230327
https://github.com/neomutt/neomutt/releases/tag/20230407

neomutt-test-files: updated to latest version.

Cleaned up old hacks (?) now that pkg-config is used. Exposes Lua feature as `enableLua` flag in function signature.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
FYI I tried this out as well, but I got stuck at https://github.com/neomutt/neomutt/issues/3773 (yes, I still have to do the proper valgrind ^^)

**Comment by RaitoBezarius** [comment]
> I've sent them a valgrind report, we'll see how it goes :)
> 
> Anyways, I'm not very keen on merging this considering that I managed to crash this in <60s (not, I'm not exaggerating and yes it's a personal record). Also, the changelog already warns about a lot of internal changes and another related issue was linked in my issue (though it's seemingly unrelated), so I'd suggest to wait and let the dust settle a bit.

Yeah, UBSAN reported some stuff on my side.
I think they are processing the crashes, Archlinux upgraded on their side.

**Comment by RaitoBezarius** [comment]
@ofborg test neomutt

**Comment by afh** [comment]
Mind updating this PR to [NeoMutt 2023-04-07](https://github.com/neomutt/neomutt/releases/tag/20230407), @RaitoBezarius?

**Comment by RaitoBezarius** [comment]
> Mind updating this PR to [NeoMutt 2023-04-07](https://github.com/neomutt/neomutt/releases/tag/20230407), @RaitoBezarius?

Done

**Comment by RaitoBezarius** [comment]
@ofborg test neomutt

**Comment by RaitoBezarius** [comment]
@Ma27 do you consider with the new release the dust has set? :P

**Comment by Ma27** [comment]
I can't deny that I have slight trust issues, but that's the only way forward. I'll try it out soonish, but considering that nixos-unstable is pretty much rolling release, I'd say if it works, let's go for it. If it turns out to have too many issues we may want to consider a revert for 23.05 though.

**Comment by RaitoBezarius** [comment]
@Ma27 I have been trying it for the last month so far (+ the recent version), have no crash (only memory leaks as always), atm. I think it's good to go.

**Comment by Ma27** [comment]
Damn, I knew I forgot about something! Testing locally....

**Comment by RaitoBezarius** [comment]
Friendly ping @Ma27 :)

**Comment by Ma27** [comment]
Rught, tl;dr still segfaulting for me when opening large maildirs.

**Comment by afh** [comment]
How large is large for you, @Ma27? 🙂

**Comment by RaitoBezarius** [comment]
If we know about "very large mailboxes", we could probably try to create a test for "large mailboxes".

**Comment by afh** [comment]
Thanks for digging in @Ma27. Will keep an eye our for any changes to this PR regarding inclusion of a fix handling the issue you are observing. My mailboxes are much smaller, yet happy to help in any way I can.

**Comment by RaitoBezarius** [comment]
Will update the PR with the patch and I will merge after CI passes.

**Comment by RaitoBezarius** [comment]
Patch added.

**Comment by afh** [comment]
Happy to report, that this PR works, for me, but did not test the large mailbox patch, as all my mailboxes are comparatively small.

**Comment by Ma27** [comment]
OK, I'll approve after having slept for a few hours. Was super-confused for a while because I encountered the segfaults again, but then I realized I accidentally cherry-picked the commit without the patch onto my nixpkgs fork :facepalm: :upside_down_face:

**Comment by afh** [comment]
@Ma27 To ensure I test the changes as they are proposed on the PR I use: `nix run github:NixOS/nixpkgs/pull/222716/merge#neomutt -- -F ~/.config/mutt/muttrc`. If I've understood your previous comment correctly that command should avoid a situation like you described. Hope this is helpfulf 🙂

**Comment by Ma27** [comment]
It was just me failing to use `hub` correctly (which I use to check out stuff and cherry-pick it onto my nixpkgs tracking branch). Anyways, I now have a patched neomutt running:

```
❯ ~ → nix why-depends /run/current-system /nix/store/3acgsi1lrykhax0w3ic41d54jb4qsik3-neomutt-20230407 
/nix/store/q1bkggar4839vgn5135j7mfxpnh363lx-nixos-system-carsten-22.11.20230425.2bbfe52
└───/nix/store/vpj0g7jdyh50qcph2vw4fnnwm7ja6j53-etc
    └───/nix/store/xph6cmm9ifdlamzvivl0283av9pabl8q-user-environment
        └───/nix/store/jay7kzs77dnfrk43f86vq9rcqxzm8061-home-manager-path
            └───/nix/store/zkndip2dywxx2abmga69cnbqk9avnjpa-nix-neomutt-20230407
                └───/nix/store/3acgsi1lrykhax0w3ic41d54jb4qsik3-neomutt-20230407
❯ ~ → nix show-derivation /nix/store/3acgsi1lrykhax0w3ic41d54jb4qsik3-neomutt-20230407 | jq '.[].env.patches' -r
/nix/store/y3swvnxh90r63yn3vzf5d7m5rsnzlb80-fix-open-very-large-mailbox.patch
```

**Review by Ma27 — APPROVED** [review]
Working fine for me now, so IMHO this is good to go now! Thanks a lot for your patience @RaitoBezarius :)

**Comment by RaitoBezarius** [comment]
> Working fine for me now, so IMHO this is good to go now! Thanks a lot for your patience @RaitoBezarius :)

Thank you for YOUR patience and your engagement on this PR. :)

**Pull request merged**
