### PR TITLE
flac: 1.4.1 -> 1.4.2

### PR DESCRIPTION
**Pull request by toonn**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Comment by vcunat** [comment]
We already have 4e74b208417

**Comment by toonn** [comment]
@vcunat, one difference is that that commit doesn't use the official release checksum as published by upstream. Would a rebase of this PR on that commit be useful or is that not considered a benefit?

**Comment by vcunat** [comment]
That's a disputed topic actually: https://github.com/NixOS/rfcs/pull/131

**Comment by toonn** [comment]
@vcunat is there anything specific about situations where upstream has an officially published hash? I'm only seeing general discussion about mandating the SRI format, might bring up the specific scenario there if it's been overlooked so far.

**Comment by vcunat** [comment]
The scenario is discussed there explicitly.  The main argument against the current proposal.  At least that's how I see it.

**Comment by toonn** [comment]
Ah, yes. It's literally the first thread of comments. When skimming it that thread seemed to be about people not knowing what SRI is.

I guess I'll just give up at this point. The expression *was* using the upstream hash until now and IMO that's a valuable thing to give up on but I don't feel like tilting at windmills.

**Pull request closed without merging**
