### PR TITLE
docker: 20.10.2 -> 20.10.6

### PR DESCRIPTION
**Pull request by mikroskeem**
###### Motivation for this change

Minor update for Docker

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123291` at 3620b33d run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built successfully:</summary>
  <ul>
    <li>charliecloud</li>
    <li>docker (docker-edge ,docker_20_10)</li>
    <li>docker-gc</li>
    <li>grype</li>
    <li>out-of-tree</li>
    <li>pipework</li>
    <li>python38Packages.jupyter-repo2docker</li>
    <li>python39Packages.jupyter-repo2docker</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM, didn't test

**Comment by jonringer** [comment]
@GrahamcOfBorg test docker docker-edge docker-tools

**Review by jonringer — APPROVED** [review]
tests on aarch64 passed

**Pull request merged**
