### PR TITLE
graalvm{8,11}-ce: init at 20.2.0

### PR DESCRIPTION
**Pull request by glittershark**
###### Motivation for this change

See #93139 - multiple packages require graalvm, but it requires significant system resources to build so it's disabled in Hydra - unfortunately as a result it is both unavailable in a pre-built form to users and it keeps breaking (see eg https://github.com/NixOS/nixpkgs/issues/98256). This packages the pre-built community edition of graalvm.

Supersedes #93139, as the original author wanted to hand it off.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by glittershark** [comment]
cc @volth @hlolli

**Comment by hlolli** [comment]
I'm relieved that this works. The top-level binaries work at first glance and seem to runs just fine from what I've tested. I don't know how the 3rd party plugin development story is with this. But knowing that we should be able the override the truffle paths.

I wonder how we should handle the llvm toolchain as is documented here https://www.graalvm.org/reference-manual/llvm/Compiling/

```
[nix-shell:~/.cache/nixpkgs-review/pr-99631]$ results/graalvm11-ce/bin/lli --print-toolchain-path
/nix/store/5qgfk0bp9byfs80vkhqsqbpfarng6cpf-graalvm11-ce-20.2.0/languages/llvm/native/bin
```

with the printed toolchain path I try to compile the hello.c

```
/nix/store/5qgfk0bp9byfs80vkhqsqbpfarng6cpf-graalvm11-ce-20.2.0/languages/llvm/native/bin/clang hello.c -o hello
Tool execution failed. Are you sure the toolchain is available at /nix/store/5qgfk0bp9byfs80vkhqsqbpfarng6cpf-graalvm11-ce-20.2.0/lib/llvm
You can install it via GraalVM updater: `gu install llvm-toolchain`

More infos: https://www.graalvm.org/docs/reference-manual/languages/llvm/
```

I doubt we are able to use the graal updater with nixos.

Could you have a look if you are able to compile to llvm bytecode with the bundled llvm toolchain?

Getting this to work would be the easiest solution by far. And since it's broken on hydra atm, just merge it for now until we have better, or we can improve this and forget about compiling graalvm from sources.

**Comment by glittershark** [comment]
> Could you have a look if you are able to compile to llvm bytecode with the bundled llvm toolchain?

I'm not sure how to do this really - I'm only using this for native-image compilation of clojure jars, which is working perfectly off of this branch.

**Comment by hlolli** [comment]
I will try to see if I can find a solution. Not having the llvm toolchain working would break the sulong support of graalvm.

**Comment by hlolli** [comment]
I was able to fix one error but I need to find out why the -fuse-ld flag is always paassed

```
env NIX_CFLAGS_LINK= NIX_CFLAGS= C_FLAGS= /nix/store/x9j3vxmad2zxi4q7hnn168j25j7wyhzz-graalvm11-ce-20.2.0/lib/llvm/bin/clang --graalvm-print-cmd test.c -o test
GraalVM wrapper script for clang
GraalVM version: 20.2.0
running: /nix/store/x9j3vxmad2zxi4q7hnn168j25j7wyhzz-graalvm11-ce-20.2.0/lib/llvm/bin/clang -I/nix/store/x9j3vxmad2zxi4q7hnn168j25j7wyhzz-graalvm11-ce-20.2.0/languages/llvm/native/include -I/nix/store/x9j3vxmad2zxi4q7hnn168j25j7wyhzz-graalvm11-ce-20.2.0/languages/llvm/include -stdlib=libc++ -Wno-unused-command-line-argument -flto=full -g -O1 -L/nix/store/x9j3vxmad2zxi4q7hnn168j25j7wyhzz-graalvm11-ce-20.2.0/languages/llvm/native/lib -fuse-ld=/nix/store/x9j3vxmad2zxi4q7hnn168j25j7wyhzz-graalvm11-ce-20.2.0/lib/llvm/bin/ld.lld -Wl,--mllvm=-lto-embed-bitcode,--lto-O0 --graalvm-print-cmd test.c -o test
```

But it seems this could be a graalvm thing and not nix https://github.com/oracle/graal/blob/3cd4bda0868432f72cc33203db598ff88eedc558/sulong/projects/com.oracle.truffle.llvm.toolchain.launchers/src/com/oracle/truffle/llvm/toolchain/launchers/common/ClangLikeBase.java#L174-L180

**Comment by glittershark** [comment]
@hlolli I'm currently depending on this in my project, and am aware of some other people who are using my fork - is there any reason we couldn't just get this merged as is and use it as a launching-off point for future work?

**Comment by hlolli** [comment]
No fine for me, I'm not using graalvm these days. So I'd not block this at this stage. Approving.

**Review by hlolli — APPROVED** [review]

**Comment by volth** [comment]
Could we unite it with `graalvm{8,11}-ee` into one nix file?

It seems that it is basically the same code and differences only in `url` and `sha256`.

Then they will be better in sync in the future.
`

**Comment by bennyandresen** [comment]
> Could we unite it with `graalvm{8,11}-ee` into one nix file?
> 
> It seems that it is basically the same code and differences only in `url` and `sha256`.
> 
> Then they will be better in sync in the future.
> `

I tried to do this at first but I reached my limits of Nix programming abilities. I wanted to parametrize them and then dispatch based on but I couldn't get the scoping to work.
I'm basically just stumbling from package to package just to get them to work and have them not look terrible.

I'm also in favor of this getting merged. I would love to update babashka and clj-kondo again for everyone using Nix and not continue using my private -bin packages.

**Comment by glittershark** [comment]
I'll give it a shot

**Comment by conferno** [comment]
> I'll give it a shot

Thank you!
There is 20.2.1 already (https://github.com/NixOS/nixpkgs/pull/101438 )

**Comment by bqv** [comment]
Keen to see this happen!

**Comment by glittershark** [comment]
@conferno 
> There is 20.2.1 already (#101438 )

So it *doesn't* look like there's a CE of 20.2.1 yet - given that, can we hold off on deduping this and graalvm-ce? I have a WIP of that up at https://github.com/glittershark/nixpkgs/commit/59d76a1b8ea1a6d6f0433275285118fbd34d6a46 if people wanna take a look, but until CE 20.2.1 is out I vote we just merge this and then do the deduping later.

cc @volth @hlolli

**Comment by volth** [comment]
yes, then let's keep them separate

**Pull request merged**
