### PR TITLE
autofirma: init at 1.6.5

### PR DESCRIPTION
**Pull request by eduardosm**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by WolfangAukang** [comment]
Result of `nixpkgs-review pr 106775` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>autofirma</li>
  </ul>
</details>

**Comment by haztecaso** [comment]
This package is really useful for spanish users and it seems to work fine for me.
Can I ask why did you close the pull request?

**Comment by haztecaso** [comment]
This package is really useful for spanish users. I'm using it with my certificate and it seems to work fine for me.
Can I ask why did you close the pr?

**Comment by eduardosm** [comment]
> This package is really useful for spanish users. I'm using it with my certificate and it seems to work fine for me.

I decided to publish it first in [NUR](https://nur.nix-community.org/repos/eduardosm/) to do some testing. I can reopen this PR if there is interest in this package.

**Comment by uningan** [comment]
Hi, Im also interested in this package but your NUR is not there anymore. Are you still interested in reopen this? or maybe we can collaborate creating a new repository (flake-ready maybe) with every spanish government tools.

**Comment by eduardosm** [comment]
> Hi, Im also interested in this package but your NUR is not there anymore. Are you still interested in reopen this? or maybe we can collaborate creating a new repository (flake-ready maybe) with every spanish government tools.

I'm not maintaining packages in nixpkgs or NUR anymore. Feel free to copy this expression and open your own PR.

**Comment by nilp0inter** [comment]
For anyone who finds this while looking for AutoFirma on NixOS:

AutoFirma is now available through a dedicated project: [autofirma-nix](https://github.com/nix-community/autofirma-nix). This repository provides Nix packages, NixOS modules, and Home Manager modules for AutoFirma and other tools needed to interact with Spain's public administration digital services.

You can find installation instructions and more details in the project's documentation: https://nix-community.github.io/autofirma-nix/.

I am one of the authors of this project, so feel free to reach out if you have any questions!

Cheers,
Roberto

**Pull request closed without merging**
