### PR TITLE
wxGTK30: rewrite

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Oh hell, mime-types is now an alias...

**Comment by jtojnar** [comment]
Looks like there is now a [conflict](https://github.com/NixOS/nixpkgs/pull/105153#issuecomment-1052081762) in this when merging `master` into `staging-next`. Do you think you would be able to resolve it?

**Comment by AndersonTorres** [comment]
What happened?
The latest change I have made on it was here https://github.com/NixOS/nixpkgs/pull/161678 following https://github.com/NixOS/nixpkgs/pull/161284 that preferred to expose Darwin inputs.

**Comment by AndersonTorres** [comment]
What happened?
The latest change I have made on it was here https://github.com/NixOS/nixpkgs/pull/161678 following https://github.com/NixOS/nixpkgs/pull/161284 that preferred to expose Darwin inputs.

**Comment by AndersonTorres** [comment]
On the other hand, how exactly can this conflict be fixed?

**Comment by jtojnar** [comment]
You would need to run

```
git checkout master
git pull
git checkout staging-next
git pull
git merge master
```

Then resolve the conflicts (marked using `<<<<<<<` in the files)

Then run `git add` for the affected files, `git commit` and finally `git push`.

**Comment by AndersonTorres** [comment]
I think it is done now...

**Comment by AndersonTorres** [comment]
Still failing? Or I should wait a bit more?

**Comment by jtojnar** [comment]
Thanks, looks like it worked, now it fails on merging `staging-next` to `staging`. Conflicting between ee2f1269d0734cafb182dc90e2848e138855e698 and b7304edb3f9ef82474796438599471e375b40f2a.

**Pull request merged**
