### PR TITLE
buildPgrxExtension: avoid empty RUSTFLAGS

### PR DESCRIPTION
**Pull request by diogotcorreia**
Setting RUSTFLAGS to an empty strings causes the linux pgvecto-rs build to fail. Therefore, it should only be set when it is non-empty.

Build failure introduced by commit 2a13929e1f191b3690dd2f2db13098b04adb9043 (#332353)

See also: https://github.com/NixOS/nixpkgs/pull/324127#discussion_r1713043056

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
Any reason we didn't use `+=` here? Or is that just not going to work with darwin?

**Comment by diogotcorreia** [comment]
@eclairevoyant I would agree with that, but I don't have a darwin machine to test, so can't know for sure it doesn't break anything.

Also, just changing the `=` to `+=` would require adding a space before (to separate what was there previously, if any), which would result in the same problem this PR is trying to fix (but for darwin this time). It would have to be conditional concatenation, not sure how to do that with bash.

**Comment by happysalada** [comment]
You could do a RUSTFLAGS="$RUSTFLAGS...." if you wanted. Addiyionaly, im happy to run a nixpkgs-rewiew on my old intel darwin if you want to try that change

**Comment by happysalada** [comment]
Otherwise this looks good i dont foresee many people overriding rust flags

**Comment by diogotcorreia** [comment]
@happysalada

> You could do a RUSTFLAGS="$RUSTFLAGS...."

Doesn't this have the same problem?

If `RUSTFLAGS` is empty, `RUSTFLAGS="$RUSTFLAGS -Clink-args=-Wl,-undefined,dynamic_lookup"` will start with a space and break `cargo-pgrx`.

**Comment by diogotcorreia** [comment]
@happysalada 
> Addiyionaly, im happy to run a nixpkgs-rewiew on my old intel darwin if you want to try that change

I'd appreciate it!

Also, it'd be nice if you could check if pgvecto-rs builds on darwin now that `buildPgrxExtension` sets `RUSTFLAGS`, but I doubt it does.

**Comment by robsliwi** [comment]
Can verify, https://github.com/NixOS/nixpkgs/commit/2a13929e1f191b3690dd2f2db13098b04adb9043 broke build of some extensions on our end.
This commit let us build them again.

**Comment by happysalada** [comment]
My nixpkgs review got stuck on something unrelated, this looks good

**Pull request merged**
