### PR TITLE
haskellPackages.gi-xlib: use xorg.* packages directly instead of xlib…

### PR DESCRIPTION
**Pull request by trofi**
…sWrapper indirection

Validated as no material change in `out` output with `diffoscope`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
This file is generated automatically using `hackage2nix`. There we have to pick an attribute based on:

```
    pkgconfig-depends: x11 >= 1.6
```

I suspect that `xlibsWrapper` is chosen, since a lot of packages declare `x11` when they want more than just `libX11`.

If you care about this strongly, you can override this in `configuration-nix.nix` by way of passing `xorg.libX11` as `xlibsWrapper`.

This PR can't be merged as is, since the changes would be rolled back. The other question is, of course, why does this change matter?

**Comment by trofi** [comment]
> This file is generated automatically using `hackage2nix`.

Oh, that was not obvious from commits to this file. The top-level comment also does not say what was used to generate the file. `cabal2nix` is a useful hint. Thanks.

> There we have to pick an attribute based on:
> 
> ```
>     pkgconfig-depends: x11 >= 1.6
> ```
> 
> I suspect that `xlibsWrapper` is chosen, since a lot of packages declare `x11` when they want more than just `libX11`.

There are exactly 3 haskell packages that use `xlibsWrapers` in `nixpkgs`:  `gi-xlib`, `greenclip`, `gtk-traymanager`. Does not sound like a lot. At least `gi-xlib` just uses `libX11`. I'll have a look at the rest, but I don't expect anything different.

> If you care about this strongly, you can override this in `configuration-nix.nix` by way of passing `xorg.libX11` as `xlibsWrapper`.
> 
> This PR can't be merged as is, since the changes would be rolled back.

I'll have a look at `cabal2nix` to generate `libX11` depends.

> The other question is, of course, why does this change matter?

I don't think there is a use case for `xlibsWrapper` today at all apart from confusing people by it's very existence. I think it was added as a convenience package right after the modular `xorg` split to postpone fixing dependencies. https://github.com/NixOS/nixpkgs/issues/194054 has a few more examples of packages that pulled it in for no specific reason and cleaned up since.

**Comment by trofi** [comment]
Proposed https://github.com/NixOS/cabal2nix/pull/589 to use `libX11` consistently.

**Comment by trofi** [comment]
Proposed https://github.com/NixOS/cabal2nix/pull/590 to hint at the tool that generates the file.

**Comment by trofi** [comment]
Closing in favour of 5bc95ac1b571a33557e52e074f2ecade7bedcb98

**Pull request closed without merging**
