### PR TITLE
prefetch-npm-deps: bail upon seeing git dependencies with install scripts

### PR DESCRIPTION
**Pull request by winterqt**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
This is basically done, I just don't feel like writing a proper description right now, so a draft it is.

**Comment by winterqt** [comment]
Maybe I should have ran the tests on the last commit before pushing... oops.

So, as far as I know, there are some dependencies (like `node-sqlite3` here) where their install script runs fine. So, we have two options here:

1. **Warn** instead of bailing
2. **Bail**, but allow the user to say "I want to try to see if this dependency works," via an environment variable or something

Would appreciate any thoughts on this.

**Comment by lilyinstarlight** [comment]
> So, as far as I know, there are some dependencies (like `node-sqlite3` here) where their install script runs fine. So, we have two options here:
> 
> 1. **Warn** instead of bailing
> 2. **Bail**, but allow the user to say "I want to try to see if this dependency works," via an environment variable or something
> 
> Would appreciate any thoughts on this.

I'm slightly inclined towards warning if it's non-fatal enough of the time and the warning would be somewhat prominent/not buried in the middle of logs

What is an example of a dependency that it breaks for?

(Also I'll do some actual testing on this PR in a bit, hopefully today or tomorrow)

**Comment by winterqt** [comment]
> What is an example of a dependency that it breaks for?

https://github.com/mongodb-js/electron-notarize, depended on by https://github.com/mongodb-js/mongosh.

**Comment by winterqt** [comment]
Superseded by #206476.

**Pull request closed without merging**
