### PR TITLE
dune: 1.4.0 -> 1.5.0

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vbgl** [comment]
Can you please enhance the `installPhase` to include the standard `runHook`s? See discussion in #49684.

**Comment by marsam** [comment]
@vbgl done

**Comment by vbgl** [comment]
@GrahamcOfBorg build reason

**Comment by marsam** [comment]
I've reverted the `runhook {preInstall,postInstall}` because it breaks [reason](https://github.com/nixos/nixpkgs/blob/6236d544146d8d447b688bdc8b3aa97afb3f20cc/pkgs/development/compilers/reason/default.nix#L27)

**Comment by vbgl** [comment]
Instead, you can fix it like this:

~~~
diff --git a/pkgs/development/compilers/reason/default.nix b/pkgs/development/compilers/reason/default.nix
index 0832d14992d..1b84b934852 100644
--- a/pkgs/development/compilers/reason/default.nix
+++ b/pkgs/development/compilers/reason/default.nix
@@ -21,12 +21,9 @@ stdenv.mkDerivation rec {
 
   buildFlags = [ "build" ]; # do not "make tests" before reason lib is installed
 
-  installPhase = ''
-    for p in reason rtop
-    do
-      ${dune.installPhase} $p.install
-    done
+  inherit (dune) installPhase;
 
+  postInstall = ''
     wrapProgram $out/bin/rtop \
       --prefix PATH : "${utop}/bin" \
       --set OCAMLPATH $out/lib/ocaml/${ocaml.version}/site-lib:$OCAMLPATH
(END)
~~~

**Comment by marsam** [comment]
@vbgl thanks, fixed

**Pull request merged**
