### PR TITLE
vimPlugins.semshi: init at 2018-12-05

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Add nice python QoL neovim plugin. It's semantically aware so it's a bit smarter about highlighting than just a regex based syntax highlighter.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
$ nix path-info -Sh /nix/store/70c3jm94h20wdp8lyl8dbr2gqm0986gr-vimplugin-semshi-2018-12-05
/nix/store/70c3jm94h20wdp8lyl8dbr2gqm0986gr-vimplugin-semshi-2018-12-05  117.3K

### CODE REVIEW

**Comment by teto** [comment]
thanks for the contribution. does it works out of the box ? or must I setup some commands ?
I wonder about the `dependencies = [ python3.pkgs.pynvim ];` efficiency since neovim must have been configured with python3 setup beforehand. I believe we reah the limit of the vim plugin system in nix.

**Comment by jonringer** [comment]
@teto i used it in my overlay without that line and it seems to work for neovim, i can do some more investigation if its actually needed

**Comment by teto** [comment]
why did you add it then ? it might be best to remove it. we don't have a good way to specify this kind of dependency anyway (I am doing some work in that direction but it won't be enough).

btw, on the semantic analysis topic: https://github.com/neovim/neovim/pull/10124

**Comment by jonringer** [comment]
It was part of the installation instructions on his page https://github.com/numirias/semshi#installation . It looks like the neovim wrapper will always include the pynvim packages, do it's not necessary. I would still  like to leave the description so that people know it doesnt work with vanilla vim though.

**Comment by jonringer** [comment]
Meh, just decided to remove all the changes to overrides.nix, doesn't really make sense to have all the packages insert an entry just for a description.

**Review by timokau — APPROVED** [review]
It would be neat to have something similar to `disable = !isPy3k` in `pythonPackages` in the future. There are more and more plugins that will only work for neovim, not for vim.

**Pull request merged**
