### PR TITLE
treewide: remove srgom

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
@SRGOM

**Comment by dotlambda** [comment]
Should they also be removed from the maintainer list?

**Comment by AndersonTorres** [comment]
I prefer to do this in a future batch.

**Comment by doronbehar** [comment]
> I prefer to do this in a future batch.

It makes sense a bit more to me to do it per maintainer. Other then that, this is good to go. Let's give @SRGOM a few days to respond. If days pass, cc me to merge this if I forget.

**Comment by AndersonTorres** [comment]
Sometimes some packages are maintained by multiple silent maintainers. It can create some strange dependency trees.

Other times some packages are being modified on Staging.

Further, some people want to adopt some packages, and I prefer to detach them so that they cam be adopted independently.

Because of this and other minor annoying things, I prefer to delete entries in maintainers set a bit later.

**Comment by bendlas** [comment]
Closing these removal PRs, since they are not grounded within community consensus. See https://github.com/NixOS/nixpkgs/pull/337478#issuecomment-2310779183

@SRGOM be sure that we value your involvement and any time you may have to spare, helping with the packages you're maintaining and others as well.

**Comment by bendlas** [comment]
> That account has been inactive for 4 years. It can be removed with no bad feelings.

The other PR got a bit hectic, so one could be forgiven for not reading all the way through. So again here in simple terms:

I'm not opposed to getting stale maintainers out. I am opposed to doing it the way it's being done in these PRs.

More on the new PR you opened, but the gist is: At that rate you could have just re-opened this one ...

**Comment by SuperSandro2000** [comment]
GitHub doesn't allow me to reopen this PR, so I opened a new one.

**Comment by superherointj** [comment]
> I'm not opposed to getting stale maintainers out.

Okay...

> I am opposed to doing it the way it's being done in these PRs.

You are only opposed to the wording of the description of the pull request, correct?

Since the PR **content** was right then. You should have never closed all these PRs, without asking first.

**Comment by superherointj** [comment]
@SigmaSquadron Tell me how all those PRs are invalid? I don't get your argument for that. Maintainers approving... So?

**Comment by AndersonTorres** [comment]
In order to not generate another flamewar in this corpse, can a moderator lock this?

**Pull request closed without merging**
