### PR TITLE
iosevka: 19.0.1 -> 20.0.0

### PR DESCRIPTION
**Pull request by lunik1**
Diff: https://github.com/be5invis/iosevka/compare/v19.0.1...v20.0.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by AndersonTorres — COMMENTED** [review]
Seven maintainers and no one fixed `meta.description`.

**Review by toastal — APPROVED** [review]
Builds for me

```sh-session
$ nixpkgs-review pr 219584                                                      
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/219584/head:refs/nixpkgs-review/1
remote: Enumerating objects: 1490, done.
remote: Counting objects: 100% (700/700), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 1490 (delta 692), reused 687 (delta 686), pack-reused 790
Receiving objects: 100% (1490/1490), 1.12 MiB | 3.54 MiB/s, done.
Resolving deltas: 100% (1023/1023), completed with 228 local objects.
From https://github.com/NixOS/nixpkgs
   03057aa1fd4..794f34657e0  master                -> refs/nixpkgs-review/0
 + 024c0dc1e44...4653526efb7 refs/pull/219584/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /home/toastal/.cache/nixpkgs-review/pr-219584/nixpkgs 794f34657e066a5e8cc4bb34491fee02240c6ac4
Preparing worktree (detached HEAD 794f34657e0)
Updating files: 100% (33809/33809), done.
HEAD is now at 794f34657e0 Merge pull request #219625 from NickCao/eigenmath
$ git merge --no-commit --no-ff 4653526efb760b7c889df4b7e1ea90e1b305a5c0
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed -f /home/toastal/.cache/nixpkgs-review/pr-219584/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/219584

1 package built:
iosevka
```

**Comment by Artturin** [comment]
change current description to longDescription and description to `Versatile typeface for code, from code.`

**Comment by lunik1** [comment]
Done

**Pull request merged**
