### PR TITLE
Fix ddclient extraConfig variable

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
###### Motivation for this change
The ddclient has a catch-all extraConfig variable that is added below the domain variable in the config script. However, the domain should always be last in the config. So I've moved it below extraConfig.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tomberek** [comment]
The documentation suggest multiple hosts can be separated in this manner:
```
For example:                                                                                                        
  protocol=hammernode1, \                                                                                           
  login=my-hn-login, password=my-hn-password  myhost.hn.org                                                         
  login=my-login, password=my-password  myhost.dyndns.org,my2nd.dyndns.org      
specifies two host definitions.
```
I use the configFile approach when the config gets too complicated. I have no issues with this PR.

**Review by matthiasbeyer — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
@LasseBlaauwbroek please rebase this PR to resolve conflicts.

**Comment by LasseBlaauwbroek** [comment]
Done

**Comment by matthiasbeyer** [comment]
Master looks different already: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/ddclient.nix#L23

**Comment by LasseBlaauwbroek** [comment]
Yes, but the lines
```
    ${lib.concatStringsSep "," cfg.domains}
    ${cfg.extraConfig}
```
still need to be exchanged. Because the domains are still expected to go below anything else.

**Comment by matthiasbeyer** [comment]
See #63087

**Comment by matthewbauer** [comment]
Thanks!

**Pull request closed without merging**
