### PR TITLE
halloy: run under wayland, if available

### PR DESCRIPTION
**Pull request by a-kenji**
Allows halloy to use it's wayland backend, if available.

NOT yet tested for darwin!

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Aleksanaa — COMMENTED** [review]
Maybe we can add an option `waylandSupport? stdenv.isLinux`?

**Comment by a-kenji** [comment]
Thank you for the suggestion @Aleksanaa 
I have added conditional checks for darwin builds.
But I don't think we should make wayland itself an configurable flag on linux.

**Review by flexiondotorg — APPROVED** [review]
I've tested this with Wayland (GNOME) and X11 (Pantheon) and it is working a treat. Thank you.

**Comment by afh** [comment]
Result of `nixpkgs-review pr 289013` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>halloy</li>
  </ul>
</details>

**Comment by a-kenji** [comment]
Thank you for checking @afh , does the current `halloy` build correctly?

**Comment by afh** [comment]
Happy to report that the changes in this PR build and halloy runs on aarch64-darwin when the following patch is applied (adds the Cocoa framework to the darwin buildInputs and includes some clean-up, which you may disagree with :)

```patch
diff --git a/pkgs/applications/networking/irc/halloy/default.nix b/pkgs/applications/networking/irc/halloy/default.nix
index 2231a7bfb396..dfe638bd1f45 100644
--- a/pkgs/applications/networking/irc/halloy/default.nix
+++ b/pkgs/applications/networking/irc/halloy/default.nix
@@ -45,15 +45,16 @@ rustPlatform.buildRustPackage rec {
     xorg.libXcursor
     xorg.libXi
     xorg.libXrandr
-  ] ++ lib.optionals stdenv.isDarwin [
-    darwin.apple_sdk.frameworks.AppKit
-    darwin.apple_sdk.frameworks.CoreFoundation
-    darwin.apple_sdk.frameworks.CoreGraphics
-    darwin.apple_sdk.frameworks.Foundation
-    darwin.apple_sdk.frameworks.Metal
-    darwin.apple_sdk.frameworks.QuartzCore
-    darwin.apple_sdk.frameworks.Security
-  ] ++ lib.optionals stdenv.isLinux [
+  ] ++ lib.optionals stdenv.isDarwin (with darwin.apple_sdk.frameworks; [
+    Cocoa
+    AppKit
+    CoreFoundation
+    CoreGraphics
+    Foundation
+    Metal
+    QuartzCore
+    Security
+  ]) ++ lib.optionals stdenv.isLinux [
     wayland
   ];
```

No, @a-kenji, the current `halloy` on `master` does not build on darwin. Are you onboard with adding Cocoa to the build inputs in this PR?

**Comment by a-kenji** [comment]
@afh 
Yes, I added `Cocoa` to the build inputs, I will keep it in a separate commit.
I assume that should be fine.

Yes, you are right, I don't see that as a cleanup :). 
Thanks for checking!

**Comment by afh** [comment]
Result of `nixpkgs-review pr 289013` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>halloy</li>
  </ul>
</details>

**Review by afh — APPROVED** [review]
The changes to the darwin build inputs look good to me and they fix the broken halloy build on the platform. Thanks, @a-kenji 🙂 

I'll review of the linux specific changes to Linux folks, if that's alright.

**Comment by afh** [comment]
Thanks for merging this so quickly, @Mic92, thanks a bunch 🥳

**Pull request merged**
