### PR TITLE
nixos/acme: Allow for time window between cert issue and activation

### PR DESCRIPTION
**Pull request by gkleen**
This PR introduces two new configuration options for `security.acme.certs.*` allowing for a configurable delay between issuance and activation of a new certificate and a shell script to execute at the start of the delay.

###### Motivation for this change
Primarily to support automatic DANE I needed a time window between getting a new certificate issued and deploying it.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] ~~Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`~~
- [ ] ~~Tested execution of all binary files (usually in `./result/bin/`)~~
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pngwjpgh** [comment]
@abbradar @fpletz @globin, care to comment?

**Comment by pngwjpgh** [comment]
*bump* ?

**Comment by pngwjpgh** [comment]
*bump*, again

**Comment by matthewbauer** [comment]
@grahamcofborg test acme

**Review by matthewbauer — CHANGES_REQUESTED** [review]
eval issues see @GrahamcOfBorg output

**Comment by pngwjpgh** [comment]
Let's see if this works for me, too:

@GrahamcOfBorg test acme

**Comment by pngwjpgh** [comment]
@matthewbauer I fixed those eval issues.

**Comment by matthewbauer** [comment]
@GrahamcOfBorg test acme

**Comment by pngwjpgh** [comment]
@matthewbauer, Pretty sure failure on aarch64 is unrelated. Ready to merge?

**Comment by matthewbauer** [comment]
Okay looks good! Make sure you are following Hydra jobs status though. Occasionally new failures will come up:

https://hydra.nixos.org/jobset/nixos/trunk-combined

**Pull request merged**
