### PR TITLE
makeNugetSource: do not substitute and build local, fix meta.description being overwritten, misc cleanup

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

We are just copying files that already exist from a to b.
In the case of ArchiSteamFarm that adds to 1.3GB which takes a good
amount of time to copy over the network.

Tested with ArchiSteamFarm.

Also naive question: Why do we copy and not just symlink?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by raphaelr — APPROVED** [review]
LGTM, works with my projects. I don't recall a reason for copy vs. symlink.

cc @NixOS/dotnet

**Review by mdarocha — APPROVED** [review]
LGTM

The copying over is probably an artifact from a time where this derivation actually unpacked the sources instead of just copying over files. If we test that such a change doesn't break any existing functionality, we can probably use it to optimize space usage

**Comment by SuperSandro2000** [comment]
Building with symlinks works just as well, so I pushed that instead.

**Review by mdarocha — APPROVED** [review]

**Comment by emilylange** [comment]
@happysalada is there a particular reason why you didn't use a merge-commit (looks like rebase and merge to me)?
This unnecessarily broke @SuperSandro2000 commit signature on those commits.

And our contributing guidelines state, we should keep those signatures intact, whenever possible.

(It also has some other downsides, like making cherry-picking slightly more difficult when copying the commit hash from the original PR.)

**Comment by happysalada** [comment]
@emilylange hey thank you for taking the time to post about this!

I wasnt aware that a rebase and merge was breaking signatures. I did this to try to save a merge commit on an already too big repo. Happy to switch to a merge commit, thanks for pointing out the problem !

**Pull request merged**
