### PR TITLE
nixos/kubernetes: Bump CoreDNS and Dashboard

### PR DESCRIPTION
**Pull request by johanot**
###### Motivation for this change
Versions of both of the bundled Kubernetes addons are getting old. We should bump those to the latest versions before 19.03 branch-off.
i.e.

* coredns 1.2.5 -> 1.3.1
* dashboard 1.8.3 -> 1.10.1

Although kubernetes-dashboard maintainers officially state that the latest version of the dashboard doesn't support k8s v1.13 (https://github.com/kubernetes/dashboard/releases/tag/v1.10.1); both components have been tested on Kubernets v1.11.6 *and* v1.13.3 and they work fine. In any case, the newest version of the dashboard must be best at supporting the newest version of k8s.

The dashboard release note also states that a new flag has been added. In order for users to be able to take advantage of this flag (and others), I've added a new option to the dashboard module, `extraArgs` with which additional cmdline args to the dashboard can be appended.

@GrahamcOfBorg test kubernetes.dns.singlenode kubernetes.dns.multinode

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by johanot** [comment]
@GrahamcOfBorg eval

**Comment by johanot** [comment]
@GrahamcOfBorg eval

**Comment by johanot** [comment]
third time's the charm
@GrahamcOfBorg eval

**Comment by johanot** [comment]
@GrahamcOfBorg test kubernetes.dns.singlenode kubernetes.dns.multinode

**Comment by srhb** [comment]
Can you elaborate a bit on your considerations regarding the dashboard compatibility chart? The fact that it has an explicit `X` and not just a question mark worries me, this seems like they _know_ there are things that do not work, doesn't it?

**Comment by srhb** [comment]
Looks like the issue at hand is the heapster v. metrics change.

**Comment by johanot** [comment]
I agree with your concerns, but on the other hand I feel that dashboard v1.10.1 by definition has to support k8s 1.13 better than v1.8.3 does (which also has the `x` next to 1.13 by the way). I somehow feel that the `x` is there only to indicate that they can't guarantee everything works. I already tested basic features on the dashboard with the 1.10, 1.13 combination, and it seems to work just fine.

IMHO, either we ship the dashboard as is, while keeping it as updated as possible, or we abandon support for the dashboard alltogether, with reference to the compatibility mismatch. I prefer the former. What do you say? :)

**Comment by srhb** [comment]
You're right, I completely overlooked the v1.8.3 issue, thanks

**Pull request merged**
