### PR TITLE
vulkan-sdk: 1.3.239 -> 1.3.243

### PR DESCRIPTION
**Pull request by PedroHLC**
###### Description of changes

- Bumps to the latest tags as seen in https://vulkan.lunarg.com/doc/sdk/1.3.243.0/linux/release_notes.html

- One of the GLSLANG patches needed to be rebased, I've included it, and added comments mentioning the upstream PR (https://github.com/KhronosGroup/glslang/pull/3067).

###### Things done

On an x86_64-linux: Tested building `vulkan-tools`, which built `vulkan-headers, vulkan-loader, spirv-headers, spirv-tools` and `glslang`. Building `vulkan-tools-lunarg` builds `vulkan-validation-layers`. I've built `vulkan-extension-layer`, then `spirv-cross` and finished by running `vkcube-wayland`.

I didn't test the `moltenvk` update (Cc @reckenrode).

### CODE REVIEW

**Comment by Kranzes** [comment]
Do you have a script that updates all of these at once?

**Review by Ralith — APPROVED** [review]
LGTM. Wouldn't mind seeing shaderc 2023.3 in here as well, but not a blocker.

**Comment by Kranzes** [comment]
> > Do you have a script that updates all of these at once?
> 
> Nope, are you considering writing one?

I wasn't planning but I did end up writing one, check this out: https://github.com/Kranzes/nixpkgs/tree/vulkan-sdk-update-script

Tell me if you would like me to create a PR.

**Comment by PedroHLC** [comment]
> Tell me if you would like me to create a PR.

You can do it, but my suggestions:
1. Don't push the version bumps, only the script. This way you can target master directly;
2. Instead of removing the version assertions, move them to `meta.broken`;
3. Add the script to `vulkan-header`'s `passthru.updateScript`. Since it's the core of the version assertions.
4. Any other

**Comment by reckenrode** [comment]
Did some testing of MoltenVK this morning on Darwin. The changes LGTM.

**Comment by trofi** [comment]
Bisect says 6cc536eb1d45960ba6ce4244945f35c843a1d1ec `vulkan-headers: 1.3.239.0 -> 1.3.243.0` broke `libplacebo` (`mpv` depend) as:

```
$ nix build --no-link -f. libplacebo -L
...
libplacebo> src/utils_gen.c: In function 'vk_res_str':
libplacebo> src/utils_gen.c:32:10: error: 'VK_ERROR_VALIDATION_FAILED' undeclared (first use in this function); did you mean 'VK_ERROR_VALIDATION_FAILED_EXT'?
libplacebo>    32 |     case VK_ERROR_VALIDATION_FAILED: return "VK_ERROR_VALIDATION_FAILED";
libplacebo>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
libplacebo>       |          VK_ERROR_VALIDATION_FAILED_EXT
```

**Comment by Kranzes** [comment]
`libplacebo` seems to be pretty outdated, we could try updating it.

**Pull request merged**
