### PR TITLE
Add temporary patches for gitlib-libgit2 and git-monitor

### PR DESCRIPTION
**Pull request by mdorman**
These (small, fairly obvious) patches have been submitted to the
upstream author as https://github.com/jwiegley/gitlib/pull/44, so this
is just to fix things up until they make it to hackage.

### CODE REVIEW

**Comment by peti** [comment]
@jwiegley, will it take long to get new versions of those packages releases? I'd prefer *not*  to incorporate those patches in Nixpkgs, if possible?

**Comment by jwiegley** [comment]
@peti I'll do it now, just getting back from a trip to Ohio.

**Comment by jwiegley** [comment]
Still trying to get the `hlibgit2` tests to pass with GHC 7.10.1.

**Comment by jwiegley** [comment]
@peti Released to Hackage as `gitlib-libgit2` 3.1.0.4 and `git-monitor` 3.1.1.4.

**Pull request closed without merging**
