### PR TITLE
libva{,-utils}: 2.1.0 -> 2.3.0, bump vaapiIntel to 2.2.0 since no 2.3.0

### PR DESCRIPTION
**Pull request by dtzWill**
Also, provide 'peg' dependency so intel-gpu-overlay is enabled in intel-gpu-tools.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Been working for me AFAICT, any input on this?

**Comment by jfrankenau** [comment]
Works fine for me as well. Would like to see this merged as I have a derivation for the Intel Media Driver in the pipeline which needs a newer libva version.

**Comment by dtzWill** [comment]
Any reason to delay this? Rebased to staging due to rebuilds.

**Review by zimbatm — APPROVED** [review]
LGTM

**Pull request merged**
