### PR TITLE
quassel-webserver: remove

### LINKED ISSUE #51614: quassel-webserver: fails to build
## Issue description

happens on ae49c73644c05f1eaf8fbd5e88d0971e3dd6a8c5

```
$ nix log /nix/store/n6xg2icz97gq27ikysmfmp6wfxyr7wvy-node-quassel-webserver-2.2.8.drv 
```

-> error log: https://gist.github.com/d2618cdad8994f6cbb531ec8f2b33782

### Steps to reproduce

```
$ nix-shell -p nodePackages.quassel-webserver
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.5, NixOS, 19.03.git.ac4a5f6 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"18.03-18.03.133375.e64482df77b, nixos-18.03-18.03.133375.e64482df77b, nur, unstable-18.03.133375.e64482df77b"`
 - channels(joerg): `"home-manager"`
 - nixpkgs: `/home/joerg/git/nixpkgs`

cc maintainer @uwap

### PR DESCRIPTION
**Pull request by Mic92**
Package is broken since a while and the original maintainer does not respond.
Unless someone wants to pick it up, I propose the removal.

fixes #51614

### CODE REVIEW

**Review by alyssais — COMMENTED** [review]
Does this need a release note, since a module is going away?

**Comment by veprbl** [comment]
cc @uwap

**Review by uwap — APPROVED** [review]

**Comment by uwap** [comment]
I don't really have time to look into it. Removing the package seems viable.

**Comment by Mic92** [comment]
deprecation release-note is here: 91a7848fe27d73d7a677fb9f606d7f7b65de16c2

**Pull request merged**
