### PR TITLE
vimPlugins.presence-nvim: init at 2021-06-08

### PR DESCRIPTION
**Pull request by natto1784**
###### Motivation
I wanted a discord rich presence for neovim, but the plugins were not available in the repo, the `coc-cord` package from `vimPlugins.coc-nvim` was causing major issues for me (since i use native lsp with neovim nightly), so I thought of using this instead and pushing it here too

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
To comply with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) please have the commit message name be of the format
```
<pkg-name>: <subject-line>
```
for more examples, please look at https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

in your case, the commit message should be:
```
vimPlugins.presence-nvim
```

**Comment by mweinelt** [comment]
And please add a motivation, the template is there for a reason.

**Comment by natto1784** [comment]
Sorry about that! Added the `motivation` in the comment and also renamed the commit message!

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 126286 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>spacevim</li>    <li>vimPlugins.presence-nvim</li>  </ul></details>

**Pull request merged**
