### PR TITLE
jq: Replace VM test

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Reduce testing turnaround, replace VM test, move logic into build phases.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Tangential to this issue: is there such a thing as a "test framework" without VM like this?

**Comment by NeQuissimus** [comment]
@AndersonTorres Not to for packages. We have tests for the function in `lib`. I believe the installCheckPhase is meant for these types of checks against the binaries in `$out`

**Comment by AndersonTorres** [comment]
@NeQuissimus I am being a bit pedantic here, but an `installCheckPhase` looks like "Here, we put the upstream tests", in the sense that if the software comes with a `make tests` then they are allocated to `installCheckPhase`.

But there is nothing like a Nix-specific testing area, where we can be bolder. (Well, we have the virtual machines, but as said before it is a bit huge...)

**Comment by NeQuissimus** [comment]
@AndersonTorres Oh no. The upstream tests are part of the `checkPhase` already. `installCheckPhase` is for checks after the derivation has been built. You can ensure the binary is wrapped correctly, calls from `/bin/bash` are replaced etc. Although I would generally only relevant commands.
Personally, I run one or two commands just to prove the binary works. And then maybe add edge cases later on as I run into issues.

**Comment by AndersonTorres** [comment]
Oh, fine then.

**Pull request merged**
