### PR TITLE
New package : fluxboxlauncher

### PR DESCRIPTION
**Pull request by mothsART**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eonpatapon** [comment]
The commit message should be: `fluxboxlauncher: init at 0.2`

I tested the build which works ok, but there is some missing runtime dependencies. When I click on 'search an application':
```
sh: rox: command not found
```

**Comment by mothsART** [comment]
@eonpatapon : I've replace rox by GtkAppChooserDialog, update fluxboxlauncher at 0.2.1 and changed commit title.

**Comment by eonpatapon** [comment]
Seems forgot to update the `sha256`:

```
hash mismatch in fixed-output derivation '/nix/store/34p534ifdq236qmmgs3c1dgvn2bj3ila-source':
  wanted: sha256:196k2lv03has2q5sr2bxxdnlyyvr8sr9hvn9az2x73n83mbmc7qb
  got:    sha256:024h1dk0bhc5s4dldr6pqabrgcqih9p8cys5lqgkgz406y4vyzvf
```

**Comment by mothsART** [comment]
@eonpatapon : right, done.

**Comment by eonpatapon** [comment]
LGTM

**Review by infinisil — APPROVED** [review]

**Pull request merged**
