### PR TITLE
plasma5: 5.10.3 -> 5.10.4

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Scheduled bugfix release.

Full changelog can be found at https://www.kde.org/announcements/plasma-5.10.3-5.10.4-changelog.php

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by ttuegel — APPROVED** [review]
I tested these changes myself. Looks good!

Let's wait to merge this until after the next `staging` merge. Everything Qt-related is broken in `master` at the moment, so if we merge this, it will just be broken too. Because it's not in master, it will only delay the channel update.

**Comment by adisbladis** [comment]
@ttuegel Sounds good! 
I'd preferably like this one https://github.com/NixOS/nixpkgs/pull/27485 merged at the same time to cause a bit less rebuilds.

**Comment by ttuegel** [comment]
> I'd preferably like this one #27485 merged at the same time to cause a bit less rebuilds.

That is my plan!

**Comment by ttuegel** [comment]
Merged via 2b29c893c12386b36a9cf9116eb6263b64bd470a.

**Comment by globin** [comment]
One of these seem to have broken plasma5/sddm tests:
https://hydra.nixos.org/build/57873795
https://hydra.nixos.org/build/57872737

**Comment by adisbladis** [comment]
@globin That breakage is unrelated to the upgrade of plasma, it's a breakage of buildenv.
I have submitted a PR with a fix: https://github.com/NixOS/nixpkgs/pull/27859

**Pull request merged**
