### PR TITLE
kanidm: 1.1.0-alpha.12 -> 1.1.0-beta.13

### PR DESCRIPTION
**Pull request by erictapen**
## Description of changes

[Changelog](https://github.com/kanidm/kanidm/releases/tag/v1.1.0-beta.13)

I selected the latest tip of the release branch instead of the tag, as it had two more commits. Also that's what we did for the last release.

Unfortunately I'm unable to build this on my workstation with 16GB RAM, 16GB Swap...

Also I'm not sure about the correct setting for the new profile settings, that are required:

- `admin_bind_path`
- `default_config_path`
- `default_unix_shell_path`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Hah, I was also working on that. 

https://github.com/NixOS/nixpkgs/commit/2b5e84897e1e78599af51664eadf52253f7ce53d

**Review by erictapen — COMMENTED** [review]
LGTM! I approve.

**Comment by Kranzes** [comment]
Tests are failing

**Comment by mweinelt** [comment]
I cannot reproduce that error. Can anyone else? I think we also had such issues on previous upgrades.

https://github.com/NixOS/nixpkgs/pull/229309#issuecomment-1571863333

Probably the extensive hardening causing weird issues in ofBorg.

**Review by adamcstephens — APPROVED** [review]
I was able to build and run tests successfully on both x86_64-linux and aarch64-linux.

**Pull request merged**
