### PR TITLE
nixos/prometheus-*-exporters: minor fixes

### PR DESCRIPTION
**Pull request by mmilata**
I've been playing with Prometheus and the NixOS modules are very nice! Run into a few problems in the exporters which this PR fixes:

* permitted values for logging options of SNMP exporter have changed in recent version (makes the NixOS test fail)
* `disableFileDelition` for mail exporter is misspelled and has no effect
* assertions that force user to either use `configuration` or `configFile` options do not work as intended, the assertion is triggered when user uses just `configFile` and doesn't touch `configuration`
* some shell arguments are not escaped so the command breaks for e.g. `unifiPassword` containing space (or filesystem path w/ space, eww)

###### Motivation for this change

NixOS prometheus experience only 98 % smooth.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @WilliButz

### CODE REVIEW

**Review by WilliButz — APPROVED** [review]
Glad to see you enjoy the prometheus modules, also thank you very much for the cleanup :+1:

**Comment by WilliButz** [comment]
backported to 20.03 in c3bb46e1796e5b240751be7b673922320bce5d88, 6673c4f5ff2464dc25e5c1e80f751e0868eaa71b, bddb1723d8a7cb1bf804648b9ab8a118d62b4e6b, f382c70e343f7db3dfdc80060a431caf95c84b88, ebb7ec3f046a4baf66acbd7ade45403c257ef22d

**Comment by mmilata** [comment]
Thank you for the swift review & taking care of backporting!

**Comment by mmilata** [comment]
@WilliButz I realized that 20.03 has the older version of the SNMP exporter so now the module options mismatch those of the package. Should we revert 6673c4f5ff2464dc25e5c1e80f751e0868eaa71b or backport bd3319d28c43580c74839a10dca5d348cc3e0b29?

**Comment by WilliButz** [comment]
Oh, thanks for noticing. The exporter version bump should have already been backported. I'll do that in a moment.

**Comment by WilliButz** [comment]
backported the exporter update in b417adb48b1a5282800093fc874eb7714d9e4dd7

**Pull request merged**
