### PR TITLE
slimevr: init at 0.13.2

### PR DESCRIPTION
**Pull request by ImUrX**
SlimeVR is used for full-body tracking on VR and is usable with multiple ways of tracking.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ImUrX** [comment]
Currently have issues with the webview not rendering correctly but it does work and I'm supposing it happens because GTK shenanigans. I'm guessing if I cherry-pick this commit to my current branch I use for my NixOS it probably will work but I dunno if that's how it's supposed to work or if it is not.

**Comment by ImUrX** [comment]
Added @C0D3-M4513R as co-maintainer as he is the [original creator of the build script]( https://github.com/C0D3-M4513R/slimevr-nixos/) and I just improved upon it with permission

**Comment by C0D3-M4513R** [comment]
I agree to be added as a maintainer and I agree to re-license all the build code nessesary under https://github.com/C0D3-M4513R/slimevr-nixos/

**Comment by C0D3-M4513R** [comment]
An auto-update from the latest github release is missing.

**Comment by C0D3-M4513R** [comment]
Also, just another concern, but does the correct version get displayed in the gui?
I remember needing do do some replacements for that in 0.13.0: https://github.com/C0D3-M4513R/slimevr-nixos/blob/aea8be98ec2a9be2c0fbda8ed70e92a6cf2c3741/packages/slimevr-server/default.nix#L46-L67

**Comment by ImUrX** [comment]
of course, because the gui is downloaded from releases, we just build the binary

**Comment by ImUrX** [comment]
i guess a fully-source compiled codebase is better than a mixed one, will leave this open but anyone with permissions may close it.

**Pull request closed without merging**
