### PR TITLE
[21.05] gitlab: 13.12.4 -> 14.0.5

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Motivation for this change

Backport of https://github.com/NixOS/nixpkgs/pull/127824 and https://github.com/NixOS/nixpkgs/pull/128963 and https://github.com/NixOS/nixpkgs/pull/129734

Note what I said in #127824

> It should be noted that this requires upgrading Postgres to >=12, which was not the default in 21.05. I still think it should be backported, since we will not be able to provide security fixes for GitLab 13.x until the end of the 21.05 release cycle.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg eval

(Sorry, ofborg's certs recently had an issue, meaning that it was unable to
react to PRs. This has been fixed, but all PRs filed in this period will need
ofborg to be manually kicked off.)

**Comment by flokli** [comment]
Assuming I am running PostgreSQL 12, on 21.05, with GitLab previously enabled? How does the upgrade path look like?

**Comment by yu-re-ka** [comment]
> Assuming I am running PostgreSQL 12, on 21.05, with GitLab previously enabled? How does the upgrade path look like?

With PostgreSQL 12 you would not have to do anything other than deploy with the new nixpkgs version. But I assume you actually meant with PostgreSQL 11: For that you would have to set `services.postgresql.package` to `pkgs.postgresql_12` or `pkgs.postgresql_13` and migrate the database state as described in the manual.

**Comment by flokli** [comment]
Hmmh - On a quick search, I didn't really find an awful lot of information on how to upgrade the PostgreSQL data state.

That's not really the fault of the GitLab module, but I'm somewhat hesitant to force users to upgrade that version mid-release, if there's not enough documentation to do so.

**Comment by yu-re-ka** [comment]
> Hmmh - On a quick search, I didn't really find an awful lot of information on how to upgrade the PostgreSQL data state.
> 
> That's not really the fault of the GitLab module, but I'm somewhat hesitant to force users to upgrade that version mid-release, if there's not enough documentation to do so.

I understand that it's not great, but my reasoning from the first post applies: Users will _have to_ upgrade their databases if they want to receive security and bug fixes until the end of the 21.05 release cycle.

The manual section for it is here: https://nixos.org/manual/nixos/stable/index.html#module-services-postgres-upgrading

**Comment by flokli** [comment]
I'm not against moving GitLab to a new major release, considering the current one won't be supported till the end of our release lifecycle.

However, we probably should link better to these notes. I assume it'd be fine if we add a section to the *21.05* release notes about GitLab being upgraded to 14, requiring a PostgreSQL upgrade, and linking to that guide.

If I'd run 21.05, update the channel and see the evaluation error, I'd probably try to find some pointers in there - and bumping the GitLab minor version probably is worth a release note entry anyways.

**Comment by yu-re-ka** [comment]
How about we link to the relevant manual section in the evaluation error?

**Comment by flokli** [comment]
Would work for me, too 👍

**Comment by flokli** [comment]
@yu-re-ka please backport the evaluation error improvement in here, then we can merge this.

**Comment by mkg20001** [comment]
For postgresql upgrades I'm currently working on a PR https://github.com/NixOS/nixpkgs/pull/129285

**Comment by yu-re-ka** [comment]
> @yu-re-ka please backport the evaluation error improvement in here, then we can merge this.

done

**Pull request merged**
