### PR TITLE
sqlite: 3.22.0 -> 3.23.1

### PR DESCRIPTION
**Pull request by dtzWill**
https://sqlite.org/releaselog/3_23_1.html

(also contains notes for 3.23.0)

Adds CLI support for SQLite archive files:
https://sqlite.org/sqlar.html

Requires zlib support, so added as dep.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Haven't looked at fallout of this yet O:).

### CODE REVIEW

**Comment by volth** [comment]
Was https://github.com/volth/nixpkgs/blob/master/pkgs/development/libraries/sqlite/sqlite3_analyzer.nix updated synchronously?

**Comment by dtzWill** [comment]
(apparently known problem re:staging, FWIW)

**Comment by xeji** [comment]
staging eval is fixed now.
@GrahamcOfBorg  eval

**Comment by xeji** [comment]
darwin looks pretty broken on staging.

**Comment by volth** [comment]
maybe we should enforce version match for ```sqlite``` + ```sqlite3_analyzer``` (and ```mercurial``` + ```tortoise-hg```) with an ```assert``` like it is done for ```libvirt``` and its perl/python bindings

**Comment by xeji** [comment]
Good idea. Or we could simply  `inherit (sqlite) version`

**Comment by dtzWill** [comment]
Should the versions used in the source URL's be similarly paired?

**Comment by yegortimoshenko** [comment]
I've pushed assert and some cleanups to this branch, including `sqlite3_analyzer` -> `sqlite-analyzer` rename to match our naming policy. If everything is OK, I will merge this into staging today. Thank you @dtzWill for the update :-)

**Comment by yegortimoshenko** [comment]
@dtzWill I've added `archiveVersion` function (if you have idea for a better name, please tell), that should handle keeping URLs in sync.

**Comment by dtzWill** [comment]
LGTM!

Wouldn't worry overly about the function/naming since it's just for these two.

Also, woohoo for computing the archive version automatically! :+1:

**Review by lukateras — APPROVED** [review]

**Pull request merged**
