### PR TITLE
[WIP] Crashplan 3.6.4 -> 3.7.0 bump

### PR DESCRIPTION
**Pull request by domenkozar**
Daemon still doesn't start, complains about null pointer exception.

### CODE REVIEW

**Comment by iElectric** [comment]
cc @ip1981

**Comment by iElectric** [comment]
cc @sztupi

**Comment by ip1981** [comment]
Sorry? :-)

**Comment by iElectric** [comment]
I see you added crashplan nixos module, making sure you know about the bump :)

**Comment by iElectric** [comment]
Ah, my bad.

**Comment by Fuuzetsu** [comment]
Presumably @sztupi is not available, can we either merge or close?

**Comment by domenkozar** [comment]
It doesn't start yet.

**Comment by domenkozar** [comment]
Closing for now.

**Pull request closed without merging**
