### PR TITLE
pocket-casts: 0.6.0 -> 0.7.0

### PR DESCRIPTION
**Pull request by ciferkey**
## Description of changes

Updates package to new [release](https://github.com/felicianotech/pocket-casts-desktop-app/releases/tag/v0.7.0).

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@wolfangaukang

### CODE REVIEW

**Comment by ciferkey** [comment]
Built locally and was able to run it without issue!

It looks like this release bumps it to electron version 27. I see in nixpkgs there is `election_27-bin` but no `electron_27`. Does that matter? `electron` looks like its 26 for now in unstable.

**Comment by yayayayaka** [comment]
> I see in nixpkgs there is `election_27-bin` but no `electron_27`

[There is](https://github.com/NixOS/nixpkgs/blob/8efd5d1e283604f75a808a20e6cde0ef313d07d4/pkgs/top-level/all-packages.nix#L18547)

**Comment by ciferkey** [comment]
Ah excellent. When I use nixpkgs search it doesn't come up. Good thing it exists though.

Does it make sense to change this to use `electron_27` or to just keep it with `electron`?

**Comment by packruler** [comment]
You will likely need to use `electron_27` because I am getting a warning about `electron-22.3.27` being EOL when I try to install.

**Review by yayayayaka — CHANGES_REQUESTED** [review]
The electron version is pinned to `electron_22` in [`pkgs/top-level/all-packages.nix`](https://github.com/NixOS/nixpkgs/blob/c781d8d24ab46c61510f88b81177fa849f33448a/pkgs/top-level/all-packages.nix#L6241). Please change it to `electron_27` to match with upstream.

**Review by yayayayaka — CHANGES_REQUESTED** [review]
Please remove the electron override in [`pkgs/top-level/all-packages.nix`](https://github.com/NixOS/nixpkgs/blob/c781d8d24ab46c61510f88b81177fa849f33448a/pkgs/top-level/all-packages.nix#L6241)

**Comment by ciferkey** [comment]
Thanks @yayayayaka. If I update the pin should I go back to use `electron` instead of `electron_27` in `default.nix`?

**Review by yayayayaka — APPROVED** [review]
Thanks, this is looking good now! I just tested on x86_64-linux and can listen to some podcasts :3

**Pull request merged**
