### PR TITLE
darwin: remove -arch from cc/ld wrapper

### PR DESCRIPTION
**Pull request by paparodeo**
`-arch` in the cc/ld wrapper causes problems when specifying different `--target` options, which would succeed except for the conflicting `-arch` specifier.

Reverts fc0456bed1372ccff51fc6fd578e5d2a09d64534 and b26e0bac8dab068e54b0c8ee1bf8fd5fe5683b39

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by paparodeo** [comment]
cc @emilazy

**Comment by emilazy** [comment]
@thefloweringash do you remember why you added these originally?

**Comment by thefloweringash** [comment]
> @thefloweringash do you remember why you added these originally?

It was long enough ago that some details have been lost. There's a little background in https://github.com/NixOS/nixpkgs/pull/114817/. At the time I was focused on bringing up `aarch64-darwin` by cross compiling stdenv from `x86_64-darwin`. For the CC wrapper I don't see why this couldn't have been covered by `-target`, but perhaps that was somehow inconvenient? For the bintools wrapper, it seems important that invocations of `ld` use the correct architecture. When invoked through clang the [Darwin toolchain driver will pass `-arch`](https://github.com/llvm/llvm-project/blob/e4c14190bb097162e15cd5822b3de97ea7bac0d6/clang/lib/Driver/ToolChains/Darwin.cpp#L176-L178), but I would want to be sure that a direct invocation in a cross compiling environment used the correct arch value.

There's precedent in the nixpkgs clang wrapper for making some flags conditional on the absence of the `--target` argument, see https://github.com/NixOS/nixpkgs/pull/291901. If the flag is still required for cross completion, perhaps it could be similarly conditional?

**Comment by emilazy** [comment]
Thanks for the reply! We’ve tested that basic Darwin–Darwin cross still works on this branch, and looking at [the `ld64` source code](https://github.com/apple-oss-distributions/ld64/blob/ld64-951.9/src/ld/Options.cpp#L6788-L6843) it seems it infers the default architecture from the format of its input files rather than the platform it’s running on or anything like that. So I think that hopefully we should be good to land this, as any invocation that doesn’t result in a default being computed would presumably fail with the Xcode toolchain anyway.

**Pull request merged**
