### PR TITLE
yubikey-personalization: 1.19.3 -> 1.20.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://developers.yubico.com/yubikey-personalization/Release_Notes.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
I starting having some issues with my yubikey this afternoon, not enough information to narrow things down yet but whereas I believe `ykinfo -a` previously reported information I'm now seeing it report no yubikey found.  So probably best to at least have this vetted by someone w/hardware and I'm optimistic my issue will be sorted soon... but let's wait a bit for now :).

**Comment by mmahut** [comment]
Moving myself to this version as part of the testing effort, given I'm using yubikey daily.

**Comment by yorickvP** [comment]
I'm getting `Yubikey core error: no yubikey present`, but this also happens on 1.19.3. Maybe ykinfo does not support this yubikey version. `ykman` from yubikey-manager does work.

**Comment by yorickvP** [comment]
Update: ykinfo only works when you have OTP enabled. It works for me as expected with 1.20.0

**Comment by dtzWill** [comment]
Oh, d'oh! Yes I recently-ish disabled OTP so that explains that.  Good catch, thanks for sharing!

:heart:

**Pull request merged**
