### PR TITLE
Uptade pytest-timeout and x265 derivations

### PR DESCRIPTION
**Pull request by jpgu-epam**
###### Motivation for this change

Update the following derivations and remove old patches on those:

pytest-timeout: 1.3.3 -> 1.4.2
x265: 3.2 -> 3.4

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by makefu — APPROVED** [review]

**Comment by ajs124** [comment]
1. nixos-20.03 is the wrong branch, even if this were a backport, it should be release-20.03
2. is this a backport? does `master` have this? if so, please backport with `git cherry-pick -x` as outlined [here](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes).

**Comment by jpgu-epam** [comment]
> 1. nixos-20.03 is the wrong branch, even if this were a backport, it should be release-20.03
> 2. is this a backport? does `master` have this? if so, please backport with `git cherry-pick -x` as outlined [here](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes).

In master [PR ](https://github.com/NixOS/nixpkgs/pull/97344) they told me these changes won't be backported. So, just need to change the target branch?

**Comment by ajs124** [comment]
backporting means that a change from the master branch gets cherry-picked into a stable release branch. It's documented [here](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes).

**Comment by FRidh** [comment]
Versions updates like these are not accepted on a stable branch. Note also that they would have to be cherry-picked from the master branch, and that the target branch would have to be `release-20.03`.

**Pull request closed without merging**
