### PR TITLE
tailscale: symlink derper to the out/bin path

### PR DESCRIPTION
**Pull request by kaleocheng**
add symlink for bin/derper  @SuperSandro2000

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
The idea was that derper does not get installed all the time because you only need it in specific scenarios. If we want to install it all the time, we might as well drop the complexity by the extra output.

**Comment by kaleocheng** [comment]
feeling  the current process for installing derper introduces unnecessary friction to the typical NixOS experience. Here's how it plays out:

1. visit the NixOS options search website and look for derper.
2. see that derper is included in tailscale, great!
3. install tailscale, but derper isn't available as expected.
4. After checking the nixpkgs definitions, find that while derper is indeed defined, it's in a subpackage and isn’t installed by default.
5.  have to reinstall it using tailscale.derper.

Steps 4 and 5 feel like unnecessary complications. Ideally the user path would avoid these extra steps.

**Comment by 06kellyjac** [comment]
Hello,

Just so you know, you do not need to check the nixpkgs definitions to see this, all the information is there in search.nixos.org output.

image

---

The tailscale packages for every other distro/package-manager I checked: Arch, Fedora, Homebrew do not include `derper` as standard, or even as a separate package.

> In general, you should not need to or want to run this code. The overwhelming majority of Tailscale users (both individuals and companies) do not.

[Tailscale - GitHub](https://github.com/tailscale/tailscale/tree/main/cmd/derper)

This is not a typical usecase, this is an advanced/exceptional usecase.
IMO it's not a deep ask for people with advanced/exceptional usecases to learn slightly more about nix to understand [multiple package outputs](https://ryantm.github.io/nixpkgs/stdenv/multiple-output/) and/or [overlays](https://ryantm.github.io/nixpkgs/using/overlays/) rather than shifting everything into the common path.
I am quite confident 99% of nixos `tailscale` installs do not need `derper`.
You can quite easily add an overlay to your system adding the `derper` output to `tailscale.meta.outputsToInstall`.

If you would like to ease the access to `derper` for the end user I would suggest making a nixos module for it (+ accompanying documentation because the `derper` README has a fair few critical requirements and is non-trivial to setup properly). It is a service and isn't intended to be installed globally as a utility but feel free add derper to the path if you want when it's module is enabled.
The README in the tailscale project also recommends running `derper` with `derpprobe` which should also not be included as-default with everyone's tailscale installs but something we can look to add to that separate derper output.

**Comment by kaleocheng** [comment]
@06kellyjac Thanks for your explanation. That indeed makes sense! Closing this PR.

**Comment by 06kellyjac** [comment]
Thank you for your understanding, it's much appreciated.

If you do feel like opening a PR to add a module you can even open it early as a draft and discuss it's development with others who would use derp.
Personally I wouldn't see much use for it but I could take a look once in a while. The tailscale staff can also be very helpful answering questions.

Another easy way to add derper wherever you need it is to refer to `tailscale.derper`/`"${tailscale.derper}/bin/derper" depending on the need

**Comment by SuperSandro2000** [comment]
Also there is a module to configure derper which you should probably take a look if you want to use it.

**Comment by 06kellyjac** [comment]
Ah, I did take a look for existing modules but either it only recently landed or I didn't click unstable.
Thanks for mentioning

**Comment by kaleocheng** [comment]
> Also there is a module to configure derper which you should probably take a look if you want to use it.

yup I'm actually using it right now. it works well!

**Comment by SuperSandro2000** [comment]
I created the module and it was only need a few weeks ago.

**Pull request closed without merging**
