### PR TITLE
muscle: init at 3.8.31

### PR DESCRIPTION
**Pull request by unode**
###### Motivation for this change
Introduces MUSCLE, a commonly used bioinformatics tool for multiple sequence alignments.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
@GrahamcOfBorg build muscle

**Comment by srhb** [comment]
Looks like there's some shebangs that need patching. There's no `/bin/bash` which `mk` refers to. :)

**Comment by unode** [comment]
Patched and built with sandbox. Not tested on NixOS yet.

**Comment by unode** [comment]
Also not entirely sure how to handle darwin. No experience with that.
Unless patching the shell also addresses the problems there.

**Comment by unode** [comment]
@GrahamcOfBorg build muscle

**Comment by srhb** [comment]
@GrahamcOfBorg build muscle

**Comment by srhb** [comment]
I guess a `meta.platforms = stdenv.lib.platforms.linux;` might be helpful here.

**Comment by srhb** [comment]
By the way, you can request access to ofborg here: https://github.com/NixOS/ofborg/issues/22

**Comment by unode** [comment]
This package is supposed to be compatible with MacOS both [Intel and PPC](https://www.drive5.com/muscle/downloads.htm) but I guess this needs further testing.
Progressing with Linux for now.

**Comment by srhb** [comment]
Looks good to me. Ready for merge?

**Comment by unode** [comment]
Just waiting on checks. Other than that :+1:

**Comment by srhb** [comment]
Thanks!

**Comment by LnL7** [comment]
Using `cc/c++` works both for gcc and clang.

**Pull request merged**
