### PR TITLE
Fix QGIS in release-19.09

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

qgis is currently broken on release-19.09.

This PR backports all necessary fixes to have it up to date and running.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
Why also update the minor version? Does it not function at 3.8.3?

**Comment by lsix** [comment]
Yes it does, but since qgis was broken since release-19.09 went out, this acts more like a new package than an update within the context of this channel.

But if you prefer, I can use pin it at 3.8.3.

**Comment by peterhoeg** [comment]
We definitely need to have a broader discussion on backports (see all the huha about firefox 70), but I'm with @lsix on this - if the released version in stable is broken anyway, we might as well bump the fix to the latest version. Any issues with that @FRidh ?

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
qgis, openscad, and tora open up fine

```
[11 built, 311 copied (1565.8 MiB), 288.8 MiB DL]
https://github.com/NixOS/nixpkgs/pull/72249
9 package are marked as broken and were skipped:
minc_widgets octave octaveFull python27Packages.qscintilla python27Packages.qscintilla-qt4 qscintilla sonic-pi sqliteman tortoisehg

8 package were build:
libsForQt5.qscintilla libsForQt511.qscintilla openscad python27Packages.qscintilla-qt5 python37Packages.qscintilla-qt5 qgis qgis-unwrapped tora
```

**Review by das-g — APPROVED** [review]

**Comment by jonringer** [comment]
I'm assuming there's no outstanding objections, I re-did the nix-review and everything still passes as it did a week ago.

**Pull request merged**
