### PR TITLE
[Backport release-24.11] ente-auth: 4.0.2 -> 4.1.6

### PR DESCRIPTION
**Pull request by niklaskorz**
Manual backport of #357503 with resolved conflicts. The `ente_auth` symlink will be kept throughout 24.11 for compatibility but might be removed from unstable before 25.05 branch-off. Unlike my previous assumption, the data directory remains unchanged with this update, making it safe to update back and forth between 4.0.2 and 4.1.6.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by niklaskorz** [comment]
The failing `cherry-pick-check` results from #363174 not having been backported to 24.11 (which I included in the update commit as part of the conflict resolution) and no release notes being added as 24.11 will keep the backwards compatible `ente_auth` alias. I'll backport 4b01903967ca7371b06af27ce2f0444f10d5b28c specifically as well but the release notes part will keep failing, which should not be a blocker for this PR.

**Review by gepbird — APPROVED** [review]
Thanks!

I agree with not backporting https://github.com/NixOS/nixpkgs/pull/363174 (that touches a few other packages) just for this package. Otherwise LGTM and tested on x86_64-linux.

Just curious, why was [`6afcee9` (#357503)](https://github.com/NixOS/nixpkgs/pull/357503/commits/6afcee95735c77f3fe99e4c013abfbc5c859aa8e) not backported? I think it's a pretty safe change.

**Comment by niklaskorz** [comment]
> Just curious, why was [`6afcee9` (#357503)](https://github.com/NixOS/nixpkgs/pull/357503/commits/6afcee95735c77f3fe99e4c013abfbc5c859aa8e) not backported? I think it's a pretty safe change.

Oh I somehow must have missed it, will add

**Review by gepbird — APPROVED** [review]
Works well, thanks!

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366513`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>ente-auth</li>
    <li>ente-auth.debug</li>
    <li>ente-auth.pubcache</li>
  </ul>
</details>

**Review by gepbird — APPROVED** [review]

**Review by schnow265 — APPROVED** [review]

**Pull request merged**
