### PR TITLE
crabfit-api: fix Rust 1.80.0 build regression

### PR DESCRIPTION
**Pull request by tomodachi94**
## Description of changes

Tracking: https://github.com/NixOS/nixpkgs/issues/332957
Upstream issue: https://github.com/GRA0007/crab.fit/issues/340
Upstream patch: https://github.com/GRA0007/crab.fit/pull/341

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
Why are so many crates being updated, not just time?

**Comment by alyssais** [comment]
This package has no maintainer — are you interested?

**Comment by tomodachi94** [comment]
> Why are so many crates being updated, not just time?

When I attempted `cargo update time`, nothing changed (I presume one of the package's other dependencies has a strict requirement for `time`), so I resorted to a full `cargo update`.

> This package has no maintainer — are you interested?

I don't personally use this package, so I don't feel that I'd adequately maintain the package.

**Comment by alyssais** [comment]
Does `cargo update --recursive time` work? I just learned about it recently in another update.

**Comment by tomodachi94** [comment]
> Does `cargo update --recursive time` work? I just learned about it recently in another update.

Partially. I had to relax the dependency on `chrono`, but it seems to work:
```
cargo update chrono
cargo update time@0.1.45 --precise 0.3.36
```

**Comment by alyssais** [comment]
There shouldn't be any need to update time 0.1.x — it's only 0.3.x that has the build failure.

**Comment by tomodachi94** [comment]
> There shouldn't be any need to update time 0.1.x — it's only 0.3.x that has the build failure.

Good catch. This PR now just bumps their copy of 0.3 `time` to the latest (and associated crates with a higher required version).

**Comment by alyssais** [comment]
It still seems a bit strange to me that so many dependencies need to be updated?  What command did you run to generate this lockfile?

**Comment by tomodachi94** [comment]
> What command did you run to generate this lockfile?

I used this command:
```sh
cargo update time@0.3.26 --precise 0.3.36
```

**Pull request merged**
