### PR TITLE
public-inbox: init at 5a4caaca8f

### PR DESCRIPTION
**Pull request by catern**
###### Motivation for this change

Adds the public-inbox application, a suite of tools for managing public archives of mailing lists.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
I would put the ```public-inbox``` application with allits patches to a separate folder.
As examples you can see ```linode-cli```, ```znapzend```, ```awstats```, ```spamassassin``` and many other applications written and perl (```grep -R perlPackages.buildPerlPackage``` will help to find others).

CPAN modules are OK to put to ```perl-packages.nix```, they will be tracked and updated by scripts.

**Comment by catern** [comment]
There are a number of bugs fixed in master which are not in the "released versions", which are only ad-hoc anyway. I'm not able to use the released version due to the bugs, so I think that will apply to most users. Therefore we can package this snapshot of git, which also obsoletes most of the patches I was carrying. The only patches left are ones for sandbox issues.

**Comment by catern** [comment]
@volth ping?

**Comment by catern** [comment]
Rebased on master, ready for merge now @volth ? Or should I retarget to staging?

**Comment by teto** [comment]
Was looking into packaging it. Could you rebase please ?

**Comment by alyssais** [comment]
fwiw there was a release recently.

Patches and hacks and stuff in here should no longer be necessary because I submitted fixes upstream to public-inbox and Xapian while working on packaging this in parallel.

I also have a NixOS module written that I can PR. :)

**Comment by catern** [comment]
@alyssais if you have a finished package for the new version I'm happy for that to be submitted instead of this PR. If your packaging isn't ready though I'm also happy to rebase and update the version in this PR.

**Comment by alyssais** [comment]
> @alyssais if you have a finished package for the new version I'm happy
> for that to be submitted instead of this PR. If your packaging isn't
> ready though I'm also happy to rebase and update the version in this
> PR.

I'll submit my package.  I don't think the module is quite finished, but
the package should be.  I'll try to get to it later today.

**Pull request closed without merging**
