### PR TITLE
gradle: cleanup

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
###### Description of changes

 * Add some comments to better explain parameters
 * Choose more descriptive variable names
 * Promote supported platforms of Gradle Native Platform to be the default

### CODE REVIEW

**Review by wamserma — APPROVED** [review]

**Comment by smancill** [comment]
This is changing the platforms for Gradle 4 and 5 from `platforms.unix` to the defined list. Is that OK?

**Comment by SuperSandro2000** [comment]
> /marvin opt-in /status needs_reviewer

marvin no longer is a thing.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Pull request merged**
