### PR TITLE
nodePackages: init sass clubhouse-cli makam inliner undollar (combine several PRs)

### PR DESCRIPTION
**Pull request by cideM**
This PR is my attempt to help with the issue (and potential, temporary solution) described in [this Discourse thread](https://discourse.nixos.org/t/call-for-nodepackages-maintainers/9176/23).

Every time someone changes the NodeJS package list and generates a new `.json` file, it results in merge conflicts for subsequent NodeJS package list modifications, since they all affect the same file.

What I did was manually go through some PRs, copy their changes but skipping the `.json` file changes and then I just ran `generate.sh` once. I included all authors through [co-authoring](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors).

These are the PRs that I combined:

- https://github.com/NixOS/nixpkgs/pull/64566
- https://github.com/NixOS/nixpkgs/pull/65006
- https://github.com/NixOS/nixpkgs/pull/63935
- https://github.com/NixOS/nixpkgs/pull/67703
- https://github.com/NixOS/nixpkgs/pull/77705

I haven't done any testing yet since I'm kinda still at work so I'd go through the checklist later, in case this approach here is considered worth doing.

I think this approach is easy to automate. Just go through a list of PRs, get their diffs, apply them but skipping the `.json` changes, accumulate the commit authors while doing so and then generate the `.json` files once.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ryantm** [comment]
Result of `nixpkgs-review pr 100606` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
<br>- rambox-pro
<br>- teleprompter
</details>
<details>
  <summary>54 packages built:</summary>
<br>- antora
<br>- bitwarden-cli
<br>- castnow
<br>- create-cycle-app
<br>- emojione
<br>- epgstation
<br>- etcher
<br>- fast-cli
<br>- gtop
<br>- image_optim
<br>- imapnotify
<br>- iosevka
<br>- joplin
<br>- lessc
<br>- lumo
<br>- mastodon-bot
<br>- mirakurun
<br>- netlify-cli
<br>- parity-ui
<br>- pm2
<br>- postcss-cli
<br>- pulp
<br>- python37Packages.batchspawner
<br>- python37Packages.dockerspawner
<br>- python37Packages.jupyterhub
<br>- python37Packages.jupyterhub-ldapauthenticator
<br>- python37Packages.jupyterhub-systemdspawner
<br>- python37Packages.jupyterhub-tmpauthenticator
<br>- python37Packages.oauthenticator
<br>- python38Packages.batchspawner
<br>- python38Packages.dockerspawner
<br>- python38Packages.jupyterhub
<br>- python38Packages.jupyterhub-ldapauthenticator
<br>- python38Packages.jupyterhub-systemdspawner
<br>- python38Packages.jupyterhub-tmpauthenticator
<br>- python38Packages.oauthenticator
<br>- redoc-cli
<br>- ripcord
<br>- shout
<br>- slack
<br>- styx
<br>- thelounge
<br>- triton
<br>- twemoji-color-font
<br>- vimPlugins.coc-eslint
<br>- vimPlugins.coc-go
<br>- vimPlugins.coc-metals
<br>- vimPlugins.coc-prettier
<br>- vimPlugins.coc-stylelint
<br>- vimPlugins.coc-tslint
<br>- vimPlugins.coc-vetur
<br>- vimPlugins.coc-yaml
<br>- wasm-text-gen
<br>- yaml-language-server
</details>

**Comment by ryantm** [comment]
I tried bitwarden-cli and lessc binaries, and the both display help messages.

**Comment by ryantm** [comment]
@cideM Any reason you see not to merge now?

**Comment by cideM** [comment]
I tried building all packages on my Macbook and `makam` fails with `attribute 'glibc' is missing. Comes from

```nix
    makam =  super.makam.override {
      buildInputs = [ pkgs.nodejs pkgs.makeWrapper ];
      postFixup = ''
        wrapProgram "$out/bin/makam" --prefix PATH : ${stdenv.lib.makeBinPath [ pkgs.nodejs ]}
        patchelf --set-interpreter ${stdenv.glibc}/lib/ld-linux-x86-64.so.2 "$out/lib/node_modules/makam/makam-bin-linux64"
      '';
    };
```

I'll have to look into the proper Darwin replacement for glibc

**Comment by cideM** [comment]
I made a change to the `makam` package. I simply wrapped the `patchelf` call in a condition so it only runs when we're on linux. The reason for this is that `otool -L ./result/lib/node_modules/makam/makam-bin-darwin64` only turns up `libSystem`. I know more or less nothing about how dynamic linking works on MacOS but I guess the `patchelf` call here is really only necessary on Linux.

I can run `makam` so it outputs help text. So from my side this is now good to merge @ryantm

**Pull request merged**
