### PR TITLE
himalaya: 1.0.0-beta.3 -> 1.0.0-beta.4

### PR DESCRIPTION
**Pull request by soywod**
## Description of changes

Release note: https://github.com/soywod/himalaya/releases/tag/v1.0.0-beta.4
Doc: https://pimalaya.org/himalaya/cli/v1.0.0-beta.4/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by soywod** [comment]
Should the package move to `pkgs/by-name/hi/himalaya/package.nix`?

**Comment by happysalada** [comment]
yes ideally, that is where the packages will be in the future.

Very selfish question, how close are we to stable on this package ? (just curiosity, I want to try it when it's stable, so no worries if it takes time).

**Comment by soywod** [comment]
> yes ideally, that is where the packages will be in the future.

I just moved it.

> Very selfish question, how close are we to stable on this package ?
> (just curiosity, I want to try it when it's stable, so no worries if
> it takes time).

There are few remaining issues for the final v1:

- Replace `imap` crate by `imap-flow`

- Improve local email support

- Implement the thread view

Also I need more users and more feedback, to see how the tool behaves in
the real world. I would say that the core tool is stable and safe to
use, except the sync feature which is still in beta. You can definitely
use it to connect to your IMAP server and interact with it.

**Comment by soywod** [comment]
> You can definitely use it to connect to your IMAP server and interact
> with it.

I mean, you don't risk anything by just connecting the tool to your IMAP
server and perform basic actions like listing folders, searching for
envelopes, moving and sending messages etc. All those core features are
really stable. The sync feature is the only beta thing, and is disabled
by default.

**Comment by soywod** [comment]
PR tracker: https://nixpk.gs/pr-tracker.html?pr=304747

**Review by toastal — APPROVED** [review]
lgtm

**Comment by happysalada** [comment]
This seems to break on darwin. I dont particularly care but im just letting you know in case you do.
If you dont we are good to go.

**Comment by soywod** [comment]
> This seems to break on darwin. I dont particularly care but im just
> letting you know in case you do.

Mmh I think I know why, let me try to fix first. Thank you for pointing
it out!

**Comment by soywod** [comment]
> Let me try to fix first.

Looks like it fixed the issue. aarch64-darwin will not work due to cross
compilation issue, so I guess we can merge the PR!

**Pull request merged**
