### PR TITLE
notmuch: 0.31 -> 0.31.3

### PR DESCRIPTION
**Pull request by bbigras**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110233` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>aerc</li>
<li>afew</li>
<li>haskellPackages.notmuch</li>
<li>lieer</li>
<li>muchsync</li>
<li>neomutt</li>
<li>notmuch</li>
<li>notmuch-addrlookup</li>
<li>notmuch-mutt</li>
<li>python37Packages.notmuch</li>
<li>python37Packages.notmuch2</li>
<li>python38Packages.notmuch</li>
<li>python38Packages.notmuch2</li>
<li>python39Packages.notmuch</li>
<li>python39Packages.notmuch2</li>
</ul>
</details>

**Comment by bbigras** [comment]
Result of `nixpkgs-review pr 110233` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>aerc</li>
    <li>afew</li>
    <li>alot</li>
    <li>astroid</li>
    <li>lieer (gmailieer)</li>
    <li>i3status-rust</li>
    <li>meli</li>
    <li>muchsync</li>
    <li>neomutt</li>
    <li>notmuch</li>
    <li>notmuch-addrlookup</li>
    <li>notmuch-mutt</li>
    <li>python37Packages.alot</li>
    <li>python37Packages.notmuch</li>
    <li>python37Packages.notmuch2</li>
    <li>python38Packages.notmuch</li>
    <li>python38Packages.notmuch2</li>
    <li>python39Packages.alot</li>
    <li>python39Packages.notmuch</li>
    <li>python39Packages.notmuch2</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110233` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>astroid: log was empty, timed out</li>
  </ul>
</details>
<details>
<summary>
20 packages built:
</summary>
<ul>
<li>aerc</li>
<li>afew</li>
<li>alot (python38Packages.alot)</li>
<li>haskellPackages.notmuch</li>
<li>i3status-rust</li>
<li>lieer</li>
<li>meli</li>
<li>muchsync</li>
<li>neomutt</li>
<li>notmuch</li>
<li>notmuch-addrlookup</li>
<li>notmuch-mutt</li>
<li>python37Packages.alot</li>
<li>python37Packages.notmuch</li>
<li>python37Packages.notmuch2</li>
<li>python38Packages.notmuch</li>
<li>python38Packages.notmuch2</li>
<li>python39Packages.alot</li>
<li>python39Packages.notmuch</li>
<li>python39Packages.notmuch2</li>
</ul>
</details>

**Comment by bbigras** [comment]
Thanks!

**Pull request merged**
