### PR TITLE
libb2: init at 0.97

### PR DESCRIPTION
**Pull request by dfoxfranke**

### CODE REVIEW

**Comment by jagajaga** [comment]
Please squash commits into one.

**Comment by dfoxfranke** [comment]
@jagajaga Are you sure you want me to do that? This isn't a matter of the second commit correcting an error in the first. They're logically separate changes. One adds me to the maintainers file, the other introduces a package which references that entry.

**Comment by dfoxfranke** [comment]
Hmm... OTOH, I just noticed the directive in maintainers.nix for the attribute name to match github user name. Let me fix that before you merge this.

**Comment by dfoxfranke** [comment]
Alright. Fixed, squashed, and ready to merge.

**Comment by jagajaga** [comment]
Thank you!

**Pull request merged**
