### PR TITLE
xfburn: 0.5.5 -> 0.6.1, tested on nixos x86_64

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by worldofpeace** [comment]
@tohl Thanks, I can backport this to 19.09. As for master, we've dissolved the multiple xfce packagesets in https://github.com/NixOS/nixpkgs/pull/72800, so I will port this update over to there.

**Comment by worldofpeace** [comment]
merged to 19.09 in 8ed1e7df1fff601eba1850853a1f8cd9aab9a7ad

**Comment by tohl** [comment]
@worldofpeace great, thanks a lot!

**Comment by tohl** [comment]
@worldofpeace
> merged to 19.09 in 8ed1e7df1fff601eba1850853a1f8cd9aab9a7ad

thanks a lot

would it be possible to cherry pick this also to master?

**Comment by worldofpeace** [comment]
I'm currently blocked on getting #72800 merged.

**Comment by tohl** [comment]
@worldofpeace
> I'm currently blocked on getting #72800 merged.

i see, thank you

**Pull request closed without merging**
