### PR TITLE
Steam: use native NixOS libraries instead of Steam Runtime

### PR DESCRIPTION
**Pull request by abbradar**
This switches off steam-runtime and instead provides all needed libraries from NixOS. I've redone all dependencies anew, so some are missing now (e.g. dpkg -- why was it needed in the first place?). Steam requires some legacy dependencies which I've added, too (stripped down as much as possible).

I've also dropped `udev-145` (it wasn't even building!) and added `udev-182`, which is, to my knowledge, the last version which provides `libudev.so.0`.

That change allows us to drop ugly PulseAudio workaround and prevent other problems like this in the future, but as a price, breakages would be more often as `nixpkgs` is constantly updated (this wouldn't be a problem for stable releases, I think). Also, this change _will_ break some games, as I've specified only packages which were required to run Steam and a few games that I was able to test.

It would be nice if other Steam users would test this on their games and report any missing libraries and/or other problems. @jagajaga?

### CODE REVIEW

**Comment by jagajaga** [comment]
I haven't checked all your PR yet. But I'm I right, that now we have to include libraries for games everytime we will be unable to launch one of them? If that is true, I disagree with such enchantment... 

Or can you explain what steam runtime is in our case?

**Comment by vcunat** [comment]
I would expect steam runtime contents is independent of the games you install.

**Comment by abbradar** [comment]
Steam runtime is their colection of libraries which are known to game vendors along with their versions, so they can link to them and test against them. There are both good and bad sides in using it:

1) If library is self-contained (doesn't interact with other things in the system), it can be more smooth experience -- you have it already tested against the game (good example would be something like libjpeg).
2) OTOH if it's not (see our PulseAudio problem), you have to resort to LD_PRELOAD or something yet more awful and hope it works. (disclosure: I've done this PR because EU4 the game broke w.r.t. audio after update, again).
3) System libraries can include more features and fixes than bundled ones. One example I've heard of is surround sound in OpenAL.
4) OTOH, if system library has a big new update that breaks a game, you'll need to add another old version of it to `nixpkgs`, and that's only after you have detected the problem in the first place. GLEW would have been an an example of this if we did this earlier.
5) One can also argue that using system native libraries instead of bundled ones is more "aesthetically pleasing", "cleaner" and such ^_^

As far as I know, their runtime is based on Ubuntu 12.04 LTS -- and in three years, only NetworkManager, GLEW (I suspect because of tigher than needed soversions) and udev have updated enough to need an old version, so maybe the last point isn't so problematic.

Adding libraries to this list would indeed be needed when you find a game that needs some library -- but steam-runtime is of finite size, so if we would do this for some time, we would have a full Runtime eventually. We can also try to just add every package in Runtime to this list, but I haven't done this because even if I get soversions right, there is no guarantee a new version of something haven't changed API without changing soversion (I'm looking at you, NetworkManager) -- so I thought that adding them one-by-one for new games with proper testing from people who own them would be better. After some thought now though this would be a bad user experience, so maybe we'll be better adding everything that's in steam-runtime, checking only soversions -- after all, I don't have any statistics on libraries' authors breaking APIs of existing soversions.

Of course, that's only if we decide we want this after all ^_^. Maybe make this opt-in or -out?

**Comment by jagajaga** [comment]
Now I think that it's looks like a good enhancement.

**Comment by abbradar** [comment]
To summarize "what we can change/decide if we want this" from a wall of text above:

* Would we want this to be opt-in or opt-out?
* Do we want to add everything in runtime, check soversions and hope that it would work, or add libraries one by one?

**Comment by jagajaga** [comment]
1. What are opt-{in,out}?
2. I would prefer to add libraries one by one. But indeed that's a bad way for other users, because they want to "download and play".. So we have a problem here :(

**Comment by abbradar** [comment]
1. Opt-in is when a feature is disabled by default, and enabled by request from user (`.override { disableRuntime = true; }` in our case), and opt-out is the opposite.
2. Well, we can try the latter and mark untested libraries with a comment; when a problem arises (and if there wouldn't be enough info in logs to determine the source), we'd ask the reporter to comment out all the "untested" libraries, add them one-by-one and tell us which are needed to ease looking for the broken one. Even "tested" ones might have some obscure API corner cases which have changed over time if its authors were slack with soversion, and which would be exposed in some rare game.

**Comment by abbradar** [comment]
https://github.com/ValveSoftware/steam-runtime/blob/master/packages.txt

This is the list of packages. Ouch, it's huge (and we certainly don't want things like libappindicator). Maybe one-by-one would be better after all...
Another idea is to look though it, pick "most common ones" (like all SDL/SDL2 libraries) and add only those.

**Comment by jagajaga** [comment]
No, I think opt-in is unneeded. If no steam runtime then no steam runtime.

We need `libappindicator` to display steam in a tray, I miss that :)

Let's add all common libraries now and after that add libs only when we have to, ok?

**Comment by abbradar** [comment]
Nice, let's do that. I'll get on it later today. Meanwhile it would be nice if you could test your games with this and report if something is missing.

**Comment by jagajaga** [comment]
I will do it this in the evening or even tomorrow. I can't do it now ---
exams...

2015-06-12 15:07 GMT+03:00 Nikolay Amiantov <notifications@github.com>:

> Nice, let's do that. I'll get on it later today. Meanwhile it would be
> nice if you could test your games with this and report if something is
> missing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/8299#issuecomment-111470945>.
>



-- 
Sincerely,
Arseniy Seroka

**Comment by abbradar** [comment]
Okay, good luck with your exams! I have a small period of rest between them now ^_^
-- 
Nikolay.

**Comment by jagajaga** [comment]
Thank you! Going to test ASAP :hamster:

**Comment by retrry** [comment]
I think this change should be opt-in. Steam-runtime was created to mitigate differences between distros and library versions, so devs could target one stable platform. Moving everything to system libraries will get rid of that stability. I remember having to do lots of workarounds when using system libraries on ArchLinux.

**Comment by abbradar** [comment]
@retrry Can you elaborate on the issues? It would be very nice to hear more from someone who has actually used Steam without a runtime. Did things break over time often? What kinds of workarounds (patches to existing libraries needed, old versions, something else)?

I would have been mostly on the opt-in side if not one thing -- our problems with sound and LD_PRELOAD-based workarounds which don't always work too, so I'm wavering. Have you encountered something like that?

On a side note, other game distributors (which I prefer when they offer no-DRM versions) de-facto assume Steam Runtime-like platform now, so if we make sufficiently compatible environment, we could make some kind of patcher/runner for those games.

**Comment by jagajaga** [comment]
You forgot to add `pkgs/tools/networking/network-manager/libnl-3.2.25.patch`.

**Comment by abbradar** [comment]
Fixed, also added more "likely needed" packages from runtime. Do we want anything else?

**Comment by abbradar** [comment]
I've also added flag, for now opt-out but let's hear out @retrry and give this more thought.

**Comment by vcunat** [comment]
> after all, I don't have any statistics on libraries' authors breaking APIs of existing soversions.

http://upstream-tracker.org looks nice for reviewing API and ABI differences; I sometimes check it before pushing non-maintenance updates (and ABI is what interests us in this case, IMO).

**Comment by jagajaga** [comment]
Problems I have:

* Fonts (they looks ugly now)
* `Dying light` can't start
* No text in `Audiosurf 2`
* Can't start `psychonauts`..

I give up testing futher, because I think there is going to be more work on this patch than real profit :(

**Comment by abbradar** [comment]
@jagajaga Thanks for the testing! Opt-out is certainly out of question then; let's leave it as an option, shall we?

**Comment by jagajaga** [comment]
@abbradar Yeah, let's do it as an opt-in.

**Comment by cpages** [comment]
I'm a bit late to the party, but I also think this should definitely be opt-in. @abbradar are there open issues for the problems you mention?

**Comment by abbradar** [comment]
@cpages Hm, I can't find it now at all, though I remember a GitHub issue about PulseAudio (where I found our current LD_PRELOAD workaround earlier). No issue about sound in EU4 -- sadly, I'm on a very limited Internet connection now and can't test if these issues are maybe already solved nor test my patches against `master`, so I'll return to this only at the end of July.

**Comment by hrdinka** [comment]
I am still testing this patch. However till now I have found out the following things:

* many older games which did not work with the default steam runtime finally work. Yay!
* stuff that is not working might be easily fixed by adding the desired libraries or workarounds without fiddling around the steam zombie mess (check the commandline output after starting a game)
* `pkgs.xlibs.xrandr` needs to be added to `targetPkgs`; the xrandr binaries are needed by some libraries like like lwjgl
* add `pkgs.xlibs.libXScrnSaver` to `multiPkgs`; this adds libXss which is needed by steam

Finally the steam store browser is not working for me which is a deal breaker for me right now. Steam claims that `libatk-1.0.so.0` is needed for the `steamwebhelper`—however NixOS ships `libatk.so.2` In the best case a simple sym-link might help, in the worst case steam does actually need atk version 1.0. I will investigate this further within the next few days.

I guess that we will see many errors where a simple sym-link will help (many devs link against specific versions of shared libraries). Such changes can easily be made within the `extraBuildCommands` and `extraBuildCommandsMulti` field. I have just noticed that `extraBuildCommandsMulti` is currently being used incorrectly (for the libcurl fix). `extraBuildCommands` will be evaluated on every FHSEnvironment installation while `extraBuildCommandsMulti` will only be evaluated on machines which install both 32 and 64bit libraries. If needed I might add a easier way of doing such fixes since one must always consider that there might or might not be a `/lib32` `/lib64` directory depending on which arch/multi-arch is used.

I do highly encourage a opt-out behavior (turn of the steam runtime and use NixOS libraries by default). All viewable steam scripts (like steam.sh) and not at least the steam-directory layout expose under which circumstances steam was brought to linux. They have built it under a lot of pressure against a certain ubuntu version which was already outdated when it steam launched. Instead of doing it right they have built a whole net of workarounds and dirty hacks around this first initial version to support newer ubuntu versions, other distributions as well as multi arch support.

Everytime I have stumbled across a non working steam game it usually referred to library issues. Then I usually created wrapper programs around the game binaries and copied libraries around to get around the steam runtime. This patch will make this fixes much easier. For a other distribution I would say that a opt-in to this feature would be better, however with mostly devs using NixOS I bet that most issues with missing libraries inferred by this patch will be flattened out rather fast.

**Comment by vcunat** [comment]
> Steam claims that libatk-1.0.so.0 is needed for the steamwebhelper—however NixOS ships libatk.so.2 In the best case a simple sym-link might help

My `pkgs.atk` on master does contain `lib/libatk-1.0.so.0` (only).

**Comment by abbradar** [comment]
With `atk` and `libXScrnSaver` added to dependencies store works for me. I've also cut dependencies for those who would use Runtime. I would definitely use this but I'm wavering whether we should make it opt-out after all. For now I've made it opt-in as discussed with @jagajaga earlier but I don't mind further discussion.

**Comment by abbradar** [comment]
@hrdinka I think an easier way to add library symlinks is not needed for now; the fix is simple and there is only one such library.

**Comment by hrdinka** [comment]
Yes your are right. Opt-In is better. I got a bit too euphoric about this changes because I am pretty annoyed by Steam and its issues. `pkgs.atk` works for me as well.

Some Valve games like Counter Strike Source ship and use `vguimatsurface.so`. This library needs the following additions in `multiPkgs`:

* pkgs.xlibs.libXxf86vm
* pkgs.xlibs.libXau
* pkgs.xlibs.libXdmcp
* llibgcrypt.so.11 when I am using NIxOS grcypt it fails with `GCRYPT_1.2 not found`; so it actually needs this version

Another idea is to ship both the steam runtime and NixOS libraries.
We could add another top level directory to the chroot which contains the official steam runtime. The Directory layout would then look like this:
```
/bin
…
/lib                 -> links to lib32
/lib32               -> NixOS 32bit libraries
/lib64               -> NixOS 64bit libraries
/steam-runtime/lib32 -> steam 32bit libraries
/steam-runtime/lib64 -> steam 64bit libraries
```

During the installation process we could strip out all library links from the steam-runtime/lib* directories. In the end the steam runtime should only consist of libraries tagged with versions. Consider this example:

```
/lib/libxyz.so   -> libxyz.so.2.3
/lib/libxyz.so.2 -> libxyz.so.2.3
/lib/libxyz.so.2.3

/steam-runtime/lib32/libxyz.so.0 -> libxyz.so.0.9
/steam-runtime/lib32/libxyz.so.0.9
```

After adding steams runtime folder to `LD_LIBRARY_PATH` as well as NixOS, apps will be able to choose which version they like. Binaries linked to specific Steam versions will use these while apps linking just against a library without a version annotation will link against the one provided by NixOS.

What do you think—should I try this out?

**Comment by abbradar** [comment]
Sounds very nice! This would improve things for Runtime users too -- no more LD_PRELOAD indecency if we would craft /lib carefully. I imagine Runtime will be disabled always and `withRuntime` would control number of overridden libraries (required vs all which we can do).

Please look into this!

On July 28, 2015 4:27:04 PM GMT+03:00, Christoph Hrdinka <notifications@github.com> wrote:
>Yes your are right. Opt-In is better. I got a bit too euphoric about
>this changes because I am pretty annoyed by Steam and its issues.
>`pkgs.atk` works for me as well.
>
>Some Valve games like Counter Strike Source ship and use
>`vguimatsurface.so`. This library needs the following additions in
>`multiPkgs`:
>
>* pkgs.xlibs.libXxf86vm
>* pkgs.xlibs.libXau
>* pkgs.xlibs.libXdmcp
>* llibgcrypt.so.11 when I am using NIxOS grcypt it fails with
>`GCRYPT_1.2 not found`; so it actually needs this version
>
>Another idea is to ship both the steam runtime and NixOS libraries.
>We could add another top level directory to the chroot which contains
>the official steam runtime. The Directory layout would then look like
>this:
>```
>/bin
>…
>/lib                 -> links to lib32
>/lib32               -> NixOS 32bit libraries
>/lib64               -> NixOS 64bit libraries
>/steam-runtime/lib32 -> steam 32bit libraries
>/steam-runtime/lib64 -> steam 64bit libraries
>```
>
>During the installation process we could strip out all library links
>from the steam-runtime/lib* directories. In the end the steam runtime
>should only consist of libraries tagged with versions. Consider this
>example:
>
>```
>/lib/libxyz.so   -> libxyz.so.2.3
>/lib/libxyz.so.2 -> libxyz.so.2.3
>/lib/libxyz.so.2.3
>
>/steam-runtime/lib32/libxyz.so.0 -> libxyz.so.0.9
>/steam-runtime/lib32/libxyz.so.0.9
>```
>
>After adding steams runtime folder to `LD_LIBRARY_PATH` as well as
>NixOS, apps will be able to choose which version they like. Binaries
>linked to specific Steam versions will use these while apps linking
>just against a library without a version annotation will link against
>the one provided by NixOS.
>
>What do you think—should I try this out?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/pull/8299#issuecomment-125605478

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hrdinka** [comment]
Ok I will :)

**Comment by hrdinka** [comment]
Here is a short update:

A first quick and dirty version revealed that this approach does actually work! :D
Both games that did only work with the original steam runtime and games that did only run with the native libs do work now. I will do some further testing and cleanup before uploading my patches.
I am currently not in the country with a tight schedule and a slow internet connection so stay tuned till next week.

**Comment by jb55** [comment]
Awesome news! Currently a lot of the games I used to play don't seem to work (starbound, etc). Looking forward to testing this once you're done.

**Comment by abbradar** [comment]
@hrdinka Sounds very nice indeed!

It would be wonderful to find a way to report all dynamically loaded libraries to stderr (`Loaded /lib64/libasound.so`, `Loaded /lib64/steam-runtime/libasound.so`). That way people who seek to improve our coverage of native libraries can find where Runtime versions are still used and attempt to fix that. Also would help very much in reporting bugs from users, I imagine. Sadly I don't know a way to do this -- if there's no ready debug option for `ld` of any kind this would be hard to implement. I'll look into this later.

**Comment by hrdinka** [comment]
@abbradar the LD_DEBUG env var should be most suitable for this. Set it to `all` to get spammed with every detail about what's gonna loaded. Setting it to help before calling an executable like a simple `ls` will explain the other options.

**Comment by hrdinka** [comment]
Hi everyone. I have just pushed my changes to [1]. I have now chosen a much simpler solution.
Instead of picking only runtime libraries that aren't present in the chroot I am now installing the whole runtime and let `ld` do the job.

All magic happens within `extraBuildCommands`. First it copies all essential files from the runtime to the chroot (into `/steamrt`). Then it creates `/steamrt/profile` which sets all environment variables:

* `/steamrt/lib**` is prepended to `LD_LIBRARY_PATH`. This means that `ld` will first look into the runtime. It will only choose NixOS libraries if they weren't found within the runtime
* `/steamrt/bin` is appended to `PATH`—NixOS binaries are prioritized. Keep in mind that there are only few shipped with the runtime.
* `STEAM_RUNTIME=0`

Prioritizing NixOS libraries did not work for me because steam's binaries rely on certain (sub) versions of them. On the other side some of NixOS binaries won't load now because of the same issue. For example `lspci` links to `libpci.so.3` while it actually needs (internal check) `libpci.so.3.20` but steam ships `libpci.so.3.18`. However problems on the NixOS side are easily fixed by wrapping those programs while wrapping all steam games/bins isn't an option.

We could even discuss wrapping all NixOS binaries to only use its own libraries. This way all steam games/stuff will favor the runtime while NixOS binaries wouldn't never leave there healthy environment. I guess this might be the best solution, however wrapping all binaries is kinda hacky.

Further I have added perl (needed by `gdialog` shipped with steam-runtime) and cleaned up a bit by adding `pkgs` into the list scope.

If this works so well for you as it does for me we could even remove all the duplicated libraries from the NixOS side. This way we will end up with an very small chroot, only containing missing libraries for some games, system libs + binaries with their dependencies and finally the steam-runtime.  I think I will try it this anyway—together with binary wrapping this sounds like the holy grail.

Please test the current patch set against your system/games. I will report back when I have tried out the other changes.

[1]: https://github.com/hrdinka/nixpkgs/tree/steam/runtime

**Comment by hrdinka** [comment]
Please notice that this isn't much different to how steam is intended to work. However by managing the runtime stuff ourselves we can finally solve all problems noted initially.

**Comment by cpages** [comment]
@hrdinka so if I understood correctly, the only difference is that nixos *binaries* are used instead of the runtime ones? Otherwise it's equivalent as having STEAM_RUNTIME=1.

**Comment by hrdinka** [comment]
@cpages Steam doesn't really ship any binaries (`cgc`, `cgfxcat`, `cginfo`, `gdialog`, `zenity`). The main difference is that NixOS does all the library handling instead of steam. This way we get rid of most problems while the remaining ones are easy to fix (we cannot fix the stuff steam does wrong). This means (accordingly to @abbradar points in one of the previous posts):

* no `LD_PRELOAD` errors; Runtime libraries do work now as they should. Deploying them via NixOS isn't really needed as the precompiled ones are good enough. We could also compile the runtime our self if precompiled ones are unwanted or replace libraries which do not infringe any version checks.
* we can replace certain steam libraries with system ones were we see benefit (OpenAL for example)
* we can add different/missing versions of libraries and add support for quirky games
* with the default runtime behavior we don't have any control about where a game looks for libraries. This is especially painful when a game launches another program like a level editor.

All in all with this patch all games I have tested till now work properly while some won't with the default steam runtime and others won't with the NixOS only runtime. This change is more a door opener for future enhancements. Further we can still use NixOS libraries while deploying original ones where it fails. However for these optimizations we need feedback and a lot of testing that is why my initial patchset does not do anything too adventurous.

**Comment by abbradar** [comment]
First of all, thank you for the hard work! While looking though it, I've stumbled across one more potentially bad problem -- some Runtime libraries are patched (e.g. [alsa-lib](http://lpaste.net/139504)) to find their own needed libraries, so in long-term using linker to do our job can be wrong. We may need to build our own Runtime and then point Steam at it with STEAM_RUNTIME variable; I'll look at this approach later today.

**Comment by abbradar** [comment]
I've made a few major changes, summary:

1. Create a separate `steamPackages` scope to hide everything but `steam-chroot` package.
2. Split `steam-runtime` by architectures.
3. Move all runtime building logic to `steam-runtime-wrapped`, which:
  * Goes though all given paths (usually runtime + a bunch of our packages) in a given order.
  * For each package it adds each file only if it does not exist in defined set of possible paths (i.e. "lib", "lib/x86_64-linux-gnu" etc for libraries, "bin" and "usr/bin" for binaries)
4. Use built that way runtime in the chroot though STEAM_RUNTIME variable.

It works very nice for me (I haven't noticed any regressions from @hrdinka's work) and should be better in terms of compatibility with Runtime. Please, test and comment!

**Comment by abbradar** [comment]
One thing I'm interested in is reduction of runtime's closure size. Those who had games with problems when played with Runtime, please try to find out which libraries are really needed for them to work. Clearing `runtimePkgs` in `steam-runtime-wrapped` and trying to start a problematic game might be a good start.

**Comment by abbradar** [comment]
More changes: now links for more generic soversions created for libraries (for a more robust override). Also we now override alsaLib, libpulseaudio, openalSoft and gcc48.cc (for its libstdc++).

**Comment by jagajaga** [comment]
Ping?

**Comment by abbradar** [comment]
Hm, I can clean this up and test later this week. It would be nice to have @yochai test this with regard for #10093 after I clean things up. I'm replacing `libstdc++` with NixOS one here, but I need to take a look and see if this is still needed (I can test it on DotA 2, but not on Civ5).

**Comment by yochai** [comment]
@abbradar I will be happy to test it, but I admit, I'm not sure how to jump into it, I see no such branch.

**Comment by hrdinka** [comment]
@abbradar I have tested the patchset with several games including civ5 (+all addons) and everything does work as expected :+1:

@yochai https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by yochai** [comment]
@hrdinka thank you, tried to follow it before commenting, typo, assumed I tried to do the wrong thing, it is working now.

@abbradar I've tested the patchset with some games (including civ 5), most of them just works, but I had the following problems.

Dota 2: 
1. Text in Hebrew doesn't show in the chat rooms on the main screen, just an empty message.
2. When you point an hero in game, you are suppose to see a box with the player's name, hero name and level, it's empty with this patchset.

Book Of Unwritten Tales: The Critter Chronicles: in the first run, the keyboard didn't work, but I didn't manage to duplicate it.

Trine 2 doesn't work, it is missing libdrm https://github.com/NixOS/nixpkgs/pull/9728.

Every other game I tried just works.

**Comment by abbradar** [comment]
This now depends on https://github.com/NixOS/nixpkgs/pull/10320
I've cherry-picked your `libdrm` fix. I'll look into Dota 2 issue later (I don't really play it, but I it's free AFAIR so I can try to fix this). @jagajaga, care to try this out?

**Comment by abbradar** [comment]
@yochai I've tried typing Russian in a chat room, it works. Can you try adding `corefonts` to the `targetPkgs` list in `pkgs/games/steam/chrootenv.nix` and test?

**Comment by yochai** [comment]
@abbradar Hebrew works now.

**Comment by jagajaga** [comment]
How to install steam and tell him to use deps from system?

**Comment by jagajaga** [comment]
Maybe let's add smthing like `steam-native` and `steam` in `all-packages.nix`? Without forcing user to override pkg if he needs to use native deps.

**Comment by jagajaga** [comment]
I still have issue with fonts. screenshot

**Comment by jagajaga** [comment]
Another thing I've noticed is the same as @yochai 
> 2. When you point an hero in game, you are suppose to see a box with the player's name, hero name and level, it's empty with this patchset.

**Comment by yochai** [comment]
@jagajaga when I've built it with corefonts the issue was solved for me, have you tried that ?

**Comment by jagajaga** [comment]
@yochai just tried that and it didn't help :(

**Comment by abbradar** [comment]
@jagajaga Indeed, we can add `steam-native` as a low priority package. I'll get to that later.
@yochai Thanks for the testing! I've added `corefonts` to the chrootenv.

Let's break down problems:

1. Ugly fonts in the Steam itself.
2. Invisible Hebrew (possibly any non-English) text in the DotA 2 chat.
3. Invisible player's name, hero name and level.

@jagajaga has all the set even with `corefonts`, for @yochai (2) and (3) were fixed with `corefonts` and (1) was not reproduced, correct? @jagajaga, sadly I can't reproduce (1) at all.

What's your `fonts` configuration in NixOS? We have `fonts.conf` from the host system propagate into the environment, so I guess differences in our `fonts` setup play a role.

**Comment by abbradar** [comment]
For the record, here is my own:
```
  fonts = {
    enableFontDir = true;
    enableGhostscriptFonts = true;
    fonts = with pkgs; [
      corefonts  # Microsoft free fonts
      cm_unicode
      stix-otf
      dejavu_fonts
      ipafont
      source-code-pro
      #symbola (in hiatus)
    ];
    fontconfig = { 
      dpi = 120;
    };
  };
```

**Comment by jagajaga** [comment]
Btw I do nt have (2). Chat is ok for me even without `corefonts`. I have only (1) and (3).
My font config is 
```nix
  fonts = {
    fontconfig.enable = true;
    enableFontDir          = true;
    enableGhostscriptFonts = true;
    fontconfig.defaultFonts.monospace = ["Terminus"];
    fonts = [
       pkgs.corefonts
       pkgs.clearlyU
       pkgs.cm_unicode
       pkgs.dejavu_fonts
       pkgs.freefont_ttf
       pkgs.terminus_font
       pkgs.ttf_bitstream_vera
    ];
  };
```

**Comment by abbradar** [comment]
I've found an AUR package with fonts specifically used by Steam (https://aur.archlinux.org/packages/steam-fonts/) and now use it instead of `corefonts`. Can you test with it?

**Comment by abbradar** [comment]
Just to be clear, here is the result I have (compare ungarbled "View" with yours): https://i.imgur.com/KcUxUPg.png

**Comment by abbradar** [comment]
Also try `rm -rf ~/.cache/fontconfig` (or move it somewhere)

**Comment by yochai** [comment]
I don't have issue 1, issue 2 and 3 are fixed for me with pushed change, @abbradar thank you for your work!
My fonts:
```
 fonts = {
     enableFontDir = true;
     enableGhostscriptFonts = true;
     fonts = with pkgs; [
       corefonts
      opensans-ttf ];
}
```

**Comment by abbradar** [comment]
@jagajaga, can you please test this with new fonts, and also check your fontconfig cache? It would be nice to fix final issues and merge this.

**Comment by jagajaga** [comment]
@abbradar with `steam-font` the problem is gone!

**Comment by abbradar** [comment]
Very nice! So, (1) (2) and (3) are all gone and we can merge? Just to be sure.

**Comment by jagajaga** [comment]
Yes.

2015-10-20 13:27 GMT+03:00 Nikolay Amiantov <notifications@github.com>:

> Very nice! So, (1) (2) and (3) are all gone and we can merge? Just to be
> sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/8299#issuecomment-149515373>.
>



-- 
Sincerely,
Arseniy Seroka

**Comment by abbradar** [comment]
I haven't squashed the commits into one because there are more than one author involved with intertwined patches (to save credits). Thank you all for the hard work!

**Comment by abbradar** [comment]
See also https://github.com/NixOS/nixpkgs/pull/10498. I intend to merge this in several days; feel free to test/comment!

**Pull request merged**
