### PR TITLE
networkmanagerapplet: default to withGnome

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
This requires us to add gcr to the module.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by andir** [comment]
Why do we want this? The motivation isn't really explicit about that.

**Comment by worldofpeace** [comment]
@andir I discovered that all of the networkmanager plugins default to withGnome, and you can't even override them in the nixos module anymore. I don't really see much point to turn this off. We have `gnome3.` attrs for these things, but I think they should be there.

**Comment by jtojnar** [comment]
Aliases:

```ShellSession
$ rg gnome3.+networkmanagerapplet
pkgs/desktops/pantheon/default.nix
159:    inherit (gnome3) networkmanagerapplet;
197:    inherit (gnome3) networkmanagerapplet;

pkgs/tools/networking/network-manager/strongswan.nix
13:  buildInputs = [ networkmanager strongswanNM libsecret gtk3 gnome3.networkmanagerapplet ];

pkgs/tools/networking/network-manager/vpnc/default.nix
27:    ++ stdenv.lib.optionals withGnome [ gtk3 libsecret gnome3.networkmanagerapplet ];

pkgs/tools/networking/network-manager/fortisslvpn/default.nix
28:    ++ stdenv.lib.optionals withGnome [ gtk3 libsecret gnome3.networkmanagerapplet ];

pkgs/tools/networking/network-manager/iodine/default.nix
28:    ++ stdenv.lib.optionals withGnome [ gtk3 libsecret gnome3.networkmanagerapplet ];

pkgs/tools/networking/network-manager/openvpn/default.nix
28:    ++ stdenv.lib.optionals withGnome [ gtk3 libsecret gnome3.networkmanagerapplet ];

```

**Comment by jtojnar** [comment]
Use of aliases:

```ShellSession
$ rg gnome3.+networkmanagerapplet
pkgs/desktops/pantheon/default.nix
159:    inherit (gnome3) networkmanagerapplet;
197:    inherit (gnome3) networkmanagerapplet;

pkgs/tools/networking/network-manager/strongswan.nix
13:  buildInputs = [ networkmanager strongswanNM libsecret gtk3 gnome3.networkmanagerapplet ];

pkgs/tools/networking/network-manager/vpnc/default.nix
27:    ++ stdenv.lib.optionals withGnome [ gtk3 libsecret gnome3.networkmanagerapplet ];

pkgs/tools/networking/network-manager/fortisslvpn/default.nix
28:    ++ stdenv.lib.optionals withGnome [ gtk3 libsecret gnome3.networkmanagerapplet ];

pkgs/tools/networking/network-manager/iodine/default.nix
28:    ++ stdenv.lib.optionals withGnome [ gtk3 libsecret gnome3.networkmanagerapplet ];

pkgs/tools/networking/network-manager/openvpn/default.nix
28:    ++ stdenv.lib.optionals withGnome [ gtk3 libsecret gnome3.networkmanagerapplet ];
```

**Comment by worldofpeace** [comment]
I don't get why eval didn't fail, we do `lib.optionalAttrs (config.allowAliases or true)` which the same for `aliases.nix`.

**Comment by jtojnar** [comment]
After some experimentations with commenting out and renaming things and running `nix-env -qa --json --file . --arg config '{ allowAliases = false; }'`, the only explanation is that attributes are accessed lazily, so their absence in the attrset is not noticed.

**Review by jtojnar — APPROVED** [review]

**Comment by worldofpeace** [comment]
@andir Lmk if you did have an issue with this.

**Pull request merged**
