### PR TITLE
haskellPackages: skip hsparql checks

### PR DESCRIPTION
**Pull request by Profpatsch**
The tests seem to be broken upstream and need to be skipped until that is fixed.

### CODE REVIEW

**Comment by bennofs** [comment]
Please don't change hackage-packages.nix directly, since that is auto-generated. Instead, edit the `configuration-....nix` files (you will find examples on how to disable tests in these files)

**Comment by peti** [comment]
Also, please report those issues upstream to make sure that the package authors fix their code! We'll pick up the new versions in Nixpkgs very quickly once they show up on Hackage.

**Comment by Profpatsch** [comment]
Gotcha! Is the configuration part documented? Maybe I missed that.

**Comment by Profpatsch** [comment]
It is corrected. cc @peti

**Comment by Profpatsch** [comment]
@peti @pikajude Now that the entry is in `configuration-common.nix`, who or what keeps track of when the bug is solved?

**Comment by lukasepple** [comment]
The only problem is that hsparql itself fails to build on `0.2.6` (the master version works for me though), so that probably will be hopefully fixed with the next hackage release.

**Comment by peti** [comment]
> Is the configuration part documented?

There is a lot of information scattered around on the mailing list, but it hasn't been compiled into a comprehensive document yet.

> Who keeps track of when the bug is solved?

You, I suppose.

**Comment by lukasepple** [comment]
The issues with hsparql and rdf4h seem to have been fixed:

* [Test PR](https://github.com/robstewart57/hsparql/pull/16)
* [Build fail](https://github.com/robstewart57/hsparql/issues/17)

**Comment by Profpatsch** [comment]
Okay, it was fixed & the `dontCheck`s are removed again.

**Comment by peti** [comment]
@Profpatsch, 

> the `dontCheck`s are removed again.

Are you sure? I still see them in `configuration-common.nix` in the current `master` branch.

**Pull request merged**
