### PR TITLE
Revert "Merge pull request #141192 from helsinki-systems/feat/improve…

### LINKED ISSUE #146727: `nixos-rebuild switch` crashes/quits DE/WM
### Describe the bug
While trying to upgrade the system using `nixos-rebuild switch`, it crashed/quit the window manager (I'm using Sway) and hang there with a black screen and a white cursor forever. I had to force the machine to shutdown.

After I reboot the machine, when I tried `nixos-rebuild switch` again, it would just say `could not find any previously installed systemd-boot` and exit the command, not doing any upgrade at all. I had to manually do `sudo bootctl install`, as suggested in [this discourse topic](https://discourse.nixos.org/t/could-not-find-any-previously-installed-systemd-boot/15627?u=rollschild) and reboot the machine _several times_ to finally get rid of this issue and be able to upgrade again. 

When I thought the issue went away, a couple of days later, during the process of `nixos-rebuild switch`, the WM just crashed again and the same thing happened again. Does anyone know what happened or what i did wrong?

I also created [a separate discourse topic](https://discourse.nixos.org/t/nixos-rebuild-switch-crashes-wm-de/16127) for this. Based on the replies from other users, this issue happened on KDE Plasma as well.

### Steps To Reproduce
1. `nixos-rebuild switch`
2. wait til the command finishes

### Expected behavior
The command successfully runs and exits, without quitting the desktop environment.

### Screenshots

IMG_20211117_173312

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.79, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(rollschild): `""`
 - channels(root): `"nixos-21.11pre332033.715f6341195, nixpkgs-21.11pre293858.141b2b111d7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

UPDATE:

There's a similar [issue](https://github.com/NixOS/nixpkgs/issues/145249) but I don't think it's the same exact issue because in my case there weren't any errors. Sway just automatically quit and all I saw was a black screen with a white cursor.

### PR DESCRIPTION
**Pull request by primeos**
…d-socket-handling2"

This reverts commit 57961d2b838cc31fa4ce89641b6a8db544a8471a, reversing
changes made to b04f913afce4419f6b777fd64ac52315dbef3aaf.
(I.e. this reverts PR #141192.)

While well-intended, this change does unfortunately introduce very
serious regressions that are especially disruptive/noticeable on desktop
systems (e.g. users of Sway will loose their graphical session when
running "nixos-rebuild switch").

Therefore, this change has to be reverted ASAP instead of trying to fix
it in "production".
Note: An updated version should be extensively discussed, reviewed, and
tested before re-landing this change as an earlier version also had to
be reverted for the exact same issues [0].

Fix: #146727

[0]: https://github.com/NixOS/nixpkgs/pull/73871#issuecomment-559783752

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
I tested this by switching back and forth between Nixpkgs revisions. `rev1 -> rev2` "crashes" Sway while `rev1 -> rev2 + this commit/revert` doesn't "crash" Sway. `nix-build -A nixosTests.switchTest` also still succeeds.

@ofborg test switchTest

**Comment by pennae** [comment]
probably also worth backporting to 21.11?

**Review by nrdxp — APPROVED** [review]
Crashing DE/WM is a pretty serious regression, so I see no choice but to go ahead and merge for now. @dasJ, I appreciate the intention here, and hopefully you can get this fixed up soon. For now I'll merge and backport.

**Comment by dasJ** [comment]
Oh boy gotta love me some fixing work 🎉

**Comment by Ma27** [comment]
FYI while updating the branch from https://github.com/NixOS/nixpkgs/pull/140669 I also found another issue:

* I have a testcase (https://github.com/NixOS/nixpkgs/pull/140669/files#diff-2c3c9f058a03d86f12ddaa23953c994c3533e9c71b5e1a62dd685479d9525f88R171) which checks whether new declarative containers are started when activating a new configuration on the host using `switch-to-configuration.pl`. The code also checks whether the network is correctly set up (i.e. whether the container's IPs are pingable).
* I confirmed that this broke with the changes from  #141192: the problem was that `$unitsToStop{$socket} = 1;` (https://github.com/NixOS/nixpkgs/pull/147609/files#diff-c5a656ad8eb4fd2a44c6523c5cfc4f0b670c231054f9f0533f78702ca06b8764R256) was missing. This caused `systemd-networkd.service` to be restarted, but the socket wasn't touched which caused an immediate restart of `systemd-networkd`, before `$out/activate` was executed (i.e. while `unitsToStop` were stopped).
* This caused another problem: networkd got restarted without knowing all new `.network`-units (including the one for the new container, these will be copied to `/etc` in an activation script). Networkd falls back to an internal unit for containers (https://github.com/systemd/systemd/blob/main/network/80-container-ve.network) which doesn't have the static IPs from the NixOS configuration and thus the container is up, but missing IPs from the configuration.

**Pull request merged**
