### PR TITLE
Update vobject 0.8.3

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by domenkozar** [comment]
I'd prefer if we relaxed strict dependency on dateutil, so we could use our `2.4.2` release

**Comment by DamienCassou** [comment]
I'm discussing it upstream already https://github.com/tBaxter/vobject/issues/12#issuecomment-152946479

**Comment by DamienCassou** [comment]
This new version of vobject breaks at least khard and pycarddav. https://github.com/tBaxter/vobject/issues/16. I recommend *not merging* my pull request yet.

**Comment by matthiasbeyer** [comment]
For me, vobject '0.8.1c' breaks khard '0.6.0'.

**Comment by DamienCassou** [comment]
@matthiasbeyer have you tried 0.8.1.d as in nixpkgs master?

**Comment by matthiasbeyer** [comment]
@DamienCassou Not yet. Will try and report back asap. I'm not on my workstation right now, so compiling from master would take some time I don't have right now.

**Comment by DamienCassou** [comment]
@matthiasbeyer Sure. But you don't have to use the master's HEAD. Just cherry-pick 979eba4010482fabcd2c5c5353620df7d2c0977e and 5d21fabdee612c1ae0584a965e8106a395b710b1

**Comment by matthiasbeyer** [comment]
@DamienCassou This still recompiles yesod for me. I really don't know why, I don't have haskell stuff in my systemPackages. I asked on the ML how to find out and I'll report back. Thank you.

**Comment by vcunat** [comment]
Ping.

**Comment by DamienCassou** [comment]
Closing this pull request as this update breaks several dependent packages.

**Pull request closed without merging**
