### PR TITLE
valgrind: fix shebang in outputs

### PR DESCRIPTION
**Pull request by oxalica**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
Please point his mass rebuild to ``staging``.

**Comment by uHOOCCOOHu** [comment]
Should I change the target branch to merge? @mmahut

**Comment by FRidh** [comment]
Perl is also in `nativeBuildInputs`. Is it needed during build-time, run-time, or both, which this PR would imply.

**Comment by uHOOCCOOHu** [comment]
Seems Perl is only required during run-time, and is now removed from `nativeBuildInputs`.

BTW: I found some absolute paths like `/usr/*lib*`, `/*lib*/` and `/*libc-2.27*.so` in `result/lib/valgrind/default.supp` not getting substituted [in `postInstall`](https://github.com/NixOS/nixpkgs/pull/67548/commits/3db523e09e9874c16d5534e78d4cf7d9e119ab84#diff-df9f6a8d19207122112c116082d61477R60). I'm not quite sure whether it is expected. Help? @eelco

**Review by ck3d — APPROVED** [review]

**Comment by worldofpeace** [comment]
merged in d22b4859a16a3f3e01cf3e6dfaeefc4424ac00cb

**Pull request closed without merging**
