### PR TITLE
ollama: add libs to wrapper's LD_LIBRARY_PATH to fix `ollama-cuda`

### LINKED ISSUE #342385: `ollama` fails to launch CUDA runner with `libcublas.so` not found
### Describe the bug
Running `ollama` fails when launching the `cuda_v12` runner: `/tmp/ollama1145927013/runners/cuda_v12/ollama_llama_server: error while loading shared libraries: libcublas.so.12: cannot open shared object file: No such file or directory`

### Steps To Reproduce
1. Install `ollama` with `nixpkgs.config.cudaSupport = true;`
2. Launch the server
3. Run a model and observe that it fails

### Expected behavior
Either `/run/opengl-driver/lib` should contain `libcublas.so.12`, or the `ollama` wrapper should add wherever `libcublas.so` is to `LD_LIBRARY_PATH`.

### Additional context

When starting, `ollama` also prints this warning: `level=WARN source=gpu.go:669 msg="unable to locate gpu dependency libraries"`.

I have 2x Quadro P5000s, using the closed drivers since open doesn't support them.

### Notify maintainers

@abysssol
@dit7ya
@elohmeier
@RoyDubnium

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.9-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20240916.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0-dev-pre20240813-f9a3bf6
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux, x86_64-v4-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/mitchell/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/mitchell/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/mitchell/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/mitchell/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/3g6dv1l653bmhahjy7s2kbfdngbdv95m-lix-2.92.0-dev-pre20240813-f9a3bf6/share`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/bvr0ffimf1a2fwq0cgnnvin94n8xwb3q-ix4ysi12wciad08x6vskj6gq3r7i266a-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by abysssol**
## Description of changes

Add `libcublas` (fixes #342385) and `cuda_cudart` (see #342127) to `LD_LIBRARY_PATH`.

@magneticflux- Please test whether this solves your issue.

@adamcstephens Please test that this doesn't actually break `ollama-cuda` again for you.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by magneticflux- — APPROVED** [review]
Tested working!

**Comment by magneticflux-** [comment]
I still get these "unable to locate gpu dependency libraries" messages in the log, but CUDA is definitely working:
```
level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama1553979802/runners
level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 cuda_v12]"
level=INFO source=gpu.go:200 msg="looking for compatible GPUs"
level=WARN source=gpu.go:669 msg="unable to locate gpu dependency libraries"
level=WARN source=gpu.go:669 msg="unable to locate gpu dependency libraries"
level=INFO source=types.go:107 msg="inference compute" id=GPU-XXX library=cuda variant=v12 compute=6.1 driver=12.6 name="Quadro P5000" total="15.9 GiB" available="15.8 GiB"
level=INFO source=types.go:107 msg="inference compute" id=GPU-YYY library=cuda variant=v12 compute=6.1 driver=12.6 name="Quadro P5000" total="15.9 GiB" available="15.8 GiB"
```

**Comment by adamcstephens** [comment]
This still works for me. I applied it, purged all old generations, and verified no cuda-merged paths still existed. :+1:

**Comment by abysssol** [comment]
@magneticflux- can you check whether the new changes I pushed fix the "unable to locate gpu dependency libraries" messages?

**Comment by magneticflux-** [comment]
I still get those messages, it seems like they're coming from this code:
https://github.com/ollama/ollama/blob/5804cf1723ef90093b0076e0069015fe7deb2a06/gpu/gpu.go#L644-L670

I'm not familiar with the Go standard library, but it seems like it's just checking for the existence of a `lib/ollama` file/folder inside one of a few locations relative to the main executable, where they store bundled libraries. If that fails, _then_ they check `LD_LIBRARY_PATH` and some other places.

**Review by magneticflux- — APPROVED** [review]

**Comment by abysssol** [comment]
@magneticflux- I did just push some small changes a few minutes ago. Have you tested that the most recent version is working correctly for you?

**Comment by adamcstephens** [comment]
This failed to build for me on x86_64-linux

```
       > + for lib in ${CUDA_LIB_DIR}/libcudart.so* ${CUDA_LIB_DIR}/libcublas.so* ${CUDA_LIB_DIR}/libcublasLt.so*
       > + cp -a '/nix/store/h637arnlnag4mqk6c9w5da6k17qmirjn-cuda-merged/lib/libcudart.so*' ../../dist/linux-amd64//lib/ollama
       > cp: cannot stat '/nix/store/h637arnlnag4mqk6c9w5da6k17qmirjn-cuda-merged/lib/libcudart.so*': No such file or directory
       > llm/generate/generate_linux.go:3: running "bash": exit status 1
       For full logs, run 'nix log /nix/store/5xqxv36knfqv55rcsfrgn74vk2zsdzyl-ollama-0.3.10.drv'.
```

**Comment by abysssol** [comment]
@adamcstephens Thanks for testing. Can you build it again with the version I just pushed? I would build it myself, but my pc is broken (again), and I only have have access at the moment to this really slow laptop that takes around two hours to build ollama-cuda.

**Review by adamcstephens — APPROVED** [review]
Built and tested.

**Review by magneticflux- — APPROVED** [review]

**Pull request merged**
