### PR TITLE
bazel-deps: remove

### PR DESCRIPTION
**Pull request by uri-canva**
###### Motivation for this change

This has been broken for a while, and now that there's an official rule set to support maven dependencies in Bazel (https://github.com/bazelbuild/rules_jvm_external) this is much less useful.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @ryantm @orivej @Profpatsch @abbradar

### CODE REVIEW

**Comment by Profpatsch** [comment]
Instead of removing it I would throw an error with basically your description if somebody tries to build the attribute.

**Comment by uri-canva** [comment]
Sounds good, do you know an example derivation that does that off the top of your head so I can see how to do that?

**Comment by uri-canva** [comment]
Figured if we're not agree on removing it, or adding a throw, might as well update it and fix it.

**Comment by uri-canva** [comment]
It's still not working with sandbox, let me fix that.

**Comment by abbradar** [comment]
@GrahamcOfBorg build bazel-deps

**Comment by Profpatsch** [comment]
So, should we try upgrading it, remove, or just mark as broken?

**Comment by uri-canva** [comment]
I think we should remove it, but I'm happy for it to be upgraded, I just got stuck on this error:

```
src/main/tools/linux-sandbox-pid1.cc:427: "execvp(external/remotejdk11_linux/bin/javac, 0x42be70)": No such file or directory
```

I think I saw it on another bazel related derivation but I can't remember which one.

**Comment by uri-canva** [comment]
What I found out is in `buildBazelPackage` when we delete all the local repositories expecting Bazel to recreate them without network we don't support the remote jdk: that is because when the local jdk repository is recreated it cannot handle is the case of the remote jdk already having being downloaded.

**Comment by uri-canva** [comment]
This is broken due to https://github.com/bazelbuild/bazel/issues/10280. I'm going to change the PR back to deleting this package.

**Comment by jamesthompson** [comment]
I believe this can be fixed if you just tell bazel to use the local jdk provisioned within the nix build env
I have this in my .bazelrc file. Not sure how you would override this in the nix bazel build function call...
```
build --host_javabase='@local_jdk//:jdk'
build --java_toolchain='@bazel_tools//tools/jdk:toolchain_hostjdk8'
```

**Pull request merged**
