### PR TITLE
hugo: remove obsolete dependencies

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

Hugo v0.50 was released 2 days ago. I also added myself to the maintainer list.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @schneefux

### CODE REVIEW

**Comment by kalbasit** [comment]
@GrahamcOfBorg build hugo

**Comment by kalbasit** [comment]
I looked at the failure on `aarch64-linux`, seems the compilation failed because it couldn't spawn more threads.

```
go tool compile: exit status 2
runtime: failed to create new OS thread (have 2 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```

**Comment by xeji** [comment]
closing as duplicate of #49525.

**Comment by kalbasit** [comment]
@xeji #49525 does not seem to remove obsolete dependencies (see deps.nix in this PR), should I refile a PR to remove those dependencies?

**Comment by xeji** [comment]
Sorry, I didn't see that. I'll reopen this so you can just rebase this branch on current master and change the commit message. The remaining changes should be in deps.nix.

**Comment by kalbasit** [comment]
@xeji done, please take another look.

**Comment by xeji** [comment]
Thanks. Actually the current deps.nix (without this PR) seems to match the `go.mod` file in the source, while yours removes some unnecessary dependencies and modifies (probably updates, I didn't check) some revisions. I'm not really sure which is better. What do you think?

**Comment by kalbasit** [comment]
if it matches go.mod, we should probably keep the upstream version in this case. Although I did test with mine and it seems to work fine.

**Comment by kalbasit** [comment]
@xeji let me give https://github.com/adisbladis/vgo2nix a try and see what would it yield.

**Comment by xeji** [comment]
I just did that. It had some crashes due to not understanding replace directives but when I manually edited the go.mod, vgo2nix essentially provided the current deps.nix.  
It's a great tool, but still in development.

**Comment by kalbasit** [comment]
oh I see. In that case, let's let upstream deal with the dependencies. Closing this for now.

**Comment by xeji** [comment]
Thank you! I think that go 1.11 modules will make packaging a log easier if they are adopted, but they're still called an experimental feature...

**Comment by kalbasit** [comment]
Definitely! I can't wait for it to go upstream. I think we can generate all of our go packages at that point.

**Pull request closed without merging**
