### PR TITLE
nixos/niri: add an option to control the inclusion of xdg-desktop-portal-gtk

### PR DESCRIPTION
**Pull request by r-vdp**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sodiboo** [comment]
Why? No other compositor module defines such an option, and there's nothing specific to niri for why you'd want to disable this portal.

Implementation looks good to me, and i do think this option makes sense, but i just don't see why it should be available in the niri module rather than being a more general wayland option, or at least part of all wayland compositors' modules equally? Do you have a particular use case where this is needed?

**Comment by r-vdp** [comment]
Yeah, this portal pulls in a huge amount of dependencies and I want to be able to disable it. But since we import the generic wayland internally in the module, I cannot easily change the options passed to it.

Maybe other compositors could also use such an option, but I'm not using those so I don't know about them.

**Comment by sodiboo** [comment]
> Yeah, this portal pulls in a huge amount of dependencies and I want to be able to disable it. But since we import the generic wayland module internally in the module, I cannot easily change the options passed to it.

I mean, you could do `xdg.portal.extraPortals = lib.mkForce [];`, and just specify exactly which portals you want installed in there? That also requires you to restate all your other portals, which ought to be like, `xdp-gnome` and `gnome-keyring`? If your concern is about dependency count, then this seems to be a good solution, actually.

> Maybe other compositors could also use such an option, but I'm not using those so I don't know about them.

I mean, is it causing some problem to *have* `xdp-gtk`? It's necessary for some portals to be implemented, such as the inhibit portal, or the Access portal (which [does not work on the GNOME implementation](https://github.com/YaLTeR/niri/commit/b9d14a9eda2a971d8a518a9fe5b31d94126fba21)). Removing it will cause issues.

And i see no reason why it is at all relevant to niri. It seems like a more general "wayland compositor" option to remove necessary portals. If you want to add it as a wider wayland option, i would not actually object to that. But it can already be accomplished with `lib.mkForce`, so i also don't see a reason to do so. But i don't think it belongs in the niri module.

**Comment by sodiboo** [comment]
> or maybe even better, an `xdg.portal.gtk.enable` option

i think this is the place it makes the most sense, yeah. something like `xdg.portal.{gtk,gnome,kde,lxqt,...}.{enable,package}` would be the nicest way to actually be able to modify this, and have every compositor module hook up to these, preferring it over `extraPortals`.

that is, if it should be in nixpkgs at all. i'm not against the idea, but i also am not fully convinced. however, if it should be implemented, i think it makes sense to put into `xdg.portal.*`

**Comment by r-vdp** [comment]
Alright, if you both don't feel that this makes sense, I'll just close this PR, thanks for the feedback.

**Pull request closed without merging**
