### PR TITLE
Disable GRUB by default

### PR DESCRIPTION
**Pull request by Madouura**
###### Description of changes
See: #171133

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Madouura** [comment]
I could be wrong, but I don't think release-notes are needed for this, as all the changes are very internal.

**Comment by Madouura** [comment]
``nixos/grub: default to disable`` _does_ change ``defaultText = literalExpression "!config.boot.isContainer";`` though... hmm...

**Comment by NickCao** [comment]
This can surprise a lot of users with a unbootable newly installed system.

**Comment by Madouura** [comment]
Isn't that part of why we have ``nixos-generate-config``, as well as just ``boot.loader.grub.enable = true;`` in the .nix of whatever system image they might want to make?

**Comment by NickCao** [comment]
> Isn't that part of why we have `nixos-generate-config` [1](https://github.com/NixOS/nixpkgs/blob/ef83e099b45a75a5aa75f1306d040cca8c9cf2fb/nixos/modules/installer/tools/nixos-generate-config.pl#L639) as well as just `boot.loader.grub.enable = true;` in the .nix of whatever system image they might want to make?

But not the case for human written configurations, if we are to change this default behavior, we would have to at least guard it behind a stateVersion.

**Comment by Madouura** [comment]
True. This does already bork the vm tests.
I agree at least a ``stateVersion`` guard would be needed.

**Comment by NickCao** [comment]
And for ensuring that exactly one bootloader is enabled, we can add more checks on `config.system.build.installBootLoader`, currently it only throws if more than one bootloader is enabled.

**Comment by Madouura** [comment]
> And for ensuring that exactly one bootloader is enabled, we can add more checks on `config.system.build.installBootLoader`, currently it only throws if more than one bootloader is enabled.

Ah, thanks for pointing that out.

**Comment by Madouura** [comment]
The thing is though, I'm not sure we should require even one bootloader to be enabled.

**Comment by Madouura** [comment]
Is there a better way to fix tests other than manually adding ``boot.loader.grub.enable = true;`` to each test?
Playing with ``testing-python.nix`` and ``build-vms.nix`` and not really getting anywhere.

**Comment by Madouura** [comment]
Actually, I only need to edit the installer tests. (duh)

**Comment by Madouura** [comment]
I'm not sure if we can guard this against ``stateVersion`` without breaking all the other commits...

**Comment by Madouura** [comment]
sourcehut and image-contents(???) test fails, but seems to be unrelated to the change made in this PR.

**Comment by Madouura** [comment]
Result of `nixpkgs-review pr 171149` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>

**Pull request closed without merging**
