### PR TITLE
Vulkan 1.3.259 bullshittery

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

SPIRV stuff gets an unstable version because tags aren't real and can't hurt you. Somehow, everything actually builds.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Also, not 1.3.260 because there's no matching loader/VVL/etc tag.

**Comment by leiserfg** [comment]
@K900  as per the vulkan-sdk distributors is not advisable to package components that are not in stable SDK (those listed in https://vulkan.lunarg.com/sdk/home).

**Comment by K900** [comment]
LunarG's "Vulkan SDK" is not _really_ an official Khronos product and isn't the only way to ship things (though at least they have tags).

**Comment by leiserfg** [comment]
Well, I asked in the [Vulkan guys](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6183) where to get the tags from and they told me that the recommended way was fetching the json from the lunar-sdk and using that, as modules not included there may be unstable (as they are not deeply tested).

**Review by PedroHLC — APPROVED** [review]
I've cherry-picked your commits over nixpkgs-unstable, and built `vulkan-tools-lunarg` and `glslang` without issues.


PS: I still think we should have `vulkanPackages_sdk` (used for everything) and `vulkanPackages_latest` (for bleeding-edge, unstable, or wip packages). But meanwhile, I'm fine with bumpings like this one and patching build-systems to ignore vulkan-headers versions.

**Comment by K900** [comment]
I should probably elaborate on what we're dealing with here.

The facts are:
- we have applications that require new Vulkan features
- the SDK components (VVL, VEL, Vulkan-Tools, etc) generally require older Vulkan and will not build with newer versions, as they autogenerate code from the XML spec and then don't handle it correctly

So our options are basically:
- stick to SDK releases and hold back application updates
- don't stick to SDK releases and risk some breakage on the development tooling
- ship two separate sets of support libraries

I personally think #2 is currently the preferable option, because #1 and #3 add a lot of maintenance overhead.

**Comment by leiserfg** [comment]
@K900 which app (excluding yuzu) "requires" a non stable SDK?

**Comment by K900** [comment]
Once again, please stop with the "non stable" thing. The headers and the loader are very much stable, and distributions and IHVs are shipping them just fine.

**Comment by leiserfg** [comment]
It's very nice when someone asks you to stop talking when you are trying to help with an issue, have a nice day.

**Comment by Ralith** [comment]
As maintainer, I oppose packaging non-SDK releases of the Vulkan stack.

> Once again, please stop with the "non stable" thing.

[Guidance from upstream](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6183#issuecomment-1648405401) is clear:
> Note: Marked version releases have undergone thorough testing but do not imply the same quality level as SDK tags.

This is illustrated by the erratic tagging we just observed. Further, there is little to no evidence of a genuine requirement (i.e. not a spuriously strict version bound) from any package for non-SDK versions.

**Comment by PedroHLC** [comment]
If someone here is going to do the next sdk bump, you may look at the "extraAttrs" in mine attrsets to see new deps, new patches and patches to remove: https://github.com/chaotic-cx/nyx/blob/main/pkgs/vulkan-versioned/default.nix

I won't have time to do the bump myself so soon...

**Comment by leiserfg** [comment]
I think we should make a script to get the refs from   [config.json](https://sdk.lunarg.com/sdk/download/1.3.261.0/linux/config.json) or better, the one matching the latest version of it.

**Comment by PedroHLC** [comment]
> I think we should make a script to get the refs from [config.json](https://sdk.lunarg.com/sdk/download/1.3.261.0/linux/config.json) or better, the one matching the latest version of it.

Previously, I considered joining all these projects under the same folder and attrset: https://github.com/NixOS/nixpkgs/pull/229897

There are some things which I would not redo from this PR:
- derivations versions as `vulkanVersions.vulkanRev or vulkanVersions.sdkRev`;
- and `vulkanPackages_latest`.

But I think the moving to a single directory, versioning in a single file, and the `vulkanPackages_sdk` (could be only `vulkanPackages`) are totally worth it.

**Pull request closed without merging**
