### PR TITLE
python311Packages.pyparted: fix build after update to 3.13.0

### PR DESCRIPTION
**Pull request by Yarny0**
## Description of changes

The [update to version 3.13.0](https://github.com/NixOS/nixpkgs/pull/251878) broke the package.  The commit at hand drops two (now unneeded) patches and adapts the third one.

Notifying pyparted maintainer @lsix

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I tested by creating some mbr and gpt disk labels and some partitions with python 3.11 and pyparted, so basic functionality seems to be restored.

## Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.pyparted</li>
    <li>python310Packages.pyparted.dist</li>
    <li>python311Packages.pyparted</li>
    <li>python311Packages.pyparted.dist</li>
  </ul>
</details>

### CODE REVIEW

**Comment by natsukium** [comment]
@ofborg eval

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 264228` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.pyparted</li>
    <li>python310Packages.pyparted.dist</li>
    <li>python311Packages.pyparted</li>
    <li>python311Packages.pyparted.dist</li>
  </ul>
</details>

Fixes https://hydra.nixos.org/build/238977938, imports fine, and pdoc doesn't complain when traversing it. LGTM

**Comment by pbsds** [comment]
@ofborg build pythonPackages.pyparted pythonPackages.pyparted.passthru.tests

**Comment by natsukium** [comment]
Can we use `pytestCheckHook` instead of `make test`?
It's a lot of work to keep the makefile patches up to date, and `make test` seems less necessary to us.

**Review by natsukium — CHANGES_REQUESTED** [review]
Could you please change the commit message and the PR title to `python311Packages` from `pythonPackages`?
`pythonPackages` means the obsolete packages for Python2.

**Comment by Yarny0** [comment]
It works fine with `pytestCheckHook`.  I reran the tests described in the PR text.

**Review by pbsds — APPROVED** [review]

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 264228` at 1e0c4226 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python310Packages.pyparted</li>
    <li>python311Packages.pyparted</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
