### PR TITLE
localsend: 1.9.1 -> 1.10.0

### PR DESCRIPTION
**Pull request by adamcstephens**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Tienisto** [comment]
Hello, since `v1.10.0`, LocalSend also provides `.tar.gz` and `.deb` binaries.

Since those are more lightweight, maybe we can use them instead?

I recently migrated the flatpak to use `.tar.gz`: https://github.com/flathub/org.localsend.localsend_app

**Review by drupol — APPROVED** [review]

**Comment by sikmir** [comment]
Result of `nixpkgs-review pr 236345` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>localsend</li>
  </ul>
</details>

**Comment by sikmir** [comment]
Fix build:
```diff
diff --git i/pkgs/applications/networking/localsend/default.nix w/pkgs/applications/networking/localsend/default.nix
index b44d0fe6a51..eb4b60ad5ee 100644
--- i/pkgs/applications/networking/localsend/default.nix
+++ w/pkgs/applications/networking/localsend/default.nix
@@ -29,11 +29,10 @@ let
       install -m 444 -D ${appimageContents}/org.localsend.localsend_app.desktop \
         $out/share/applications/${pname}.desktop
       substituteInPlace $out/share/applications/${pname}.desktop \
-        --replace 'Icon=application-vnd.appimage' 'Icon=${pname}' \
         --replace 'Exec=localsend_app' 'Exec=$out/bin/localsend'

-      install -m 444 -D ${appimageContents}/application-vnd.appimage.svg \
-        $out/share/icons/hicolor/scalable/apps/${pname}.svg
+      install -m 444 -D ${appimageContents}/localsend.png \
+        $out/share/icons/hicolor/256x256/apps/localsend.png
     '';
   };
```

**Comment by sikmir** [comment]
Result of `nixpkgs-review pr 236345` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>localsend</li>
  </ul>
</details>

**Review by sikmir — APPROVED** [review]

**Comment by adamcstephens** [comment]
> Hello, since `v1.10.0`, LocalSend also provides `.tar.gz` and `.deb` binaries.
> 
> Since those are more lightweight, maybe we can use them instead?

I think this sounds like a great idea, but is a bigger change than I'm currently ready to tackle. I'd be happy to test if someone else makes progress though.

> Fix build:

Thank you, I've verified this fixes the build on Linux and marked it ready for review.

**Comment by sikmir** [comment]
One more issue:
```sh
$ cat results/localsend/share/applications/localsend.desktop | grep Exec
Exec=$out/bin/localsend
```

Fix:
```diff
diff --git i/pkgs/applications/networking/localsend/default.nix w/pkgs/applications/networking/localsend/default.nix
index eb4b60ad5ee..5dfb520b557 100644
--- i/pkgs/applications/networking/localsend/default.nix
+++ w/pkgs/applications/networking/localsend/default.nix
@@ -29,7 +29,7 @@ let
       install -m 444 -D ${appimageContents}/org.localsend.localsend_app.desktop \
         $out/share/applications/${pname}.desktop
       substituteInPlace $out/share/applications/${pname}.desktop \
-        --replace 'Exec=localsend_app' 'Exec=$out/bin/localsend'
+        --replace 'Exec=localsend_app' "Exec=$out/bin/localsend"

       install -m 444 -D ${appimageContents}/localsend.png \
         $out/share/icons/hicolor/256x256/apps/localsend.png
```

**Pull request merged**
