### PR TITLE
openjdk{11,12,13,14}: disable JavaFX by default

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Description of changes

`openjfx11` is build with `python2`, that is going EOL.

See https://github.com/NixOS/nixpkgs/pull/201859.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emmanuelrosa** [comment]
This would break `bisq-desktop`, which uses JavaFX on openjdk11 and I could not get it to work with either openjdk17 or openjdk19.

**Comment by thiagokokada** [comment]
> This would break `bisq-desktop`, which uses JavaFX on openjdk11 and I could not get it to work with either openjdk17 or openjdk19.

We can override it for this specific package.

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 203958` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>frostwire</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>eclipse-mat</li>
    <li>mathematica</li>
    <li>mathematica-cuda</li>
    <li>mathematica10</li>
    <li>mathematica11</li>
    <li>mathematica9</li>
    <li>portfolio</li>
  </ul>
</details>
<details>
  <summary>37 packages built:</summary>
  <ul>
    <li>apache-directory-server</li>
    <li>charles (charles4)</li>
    <li>codeql</li>
    <li>conduktor</li>
    <li>cytoscape</li>
    <li>eclair</li>
    <li>erlang_javac</li>
    <li>erlang_odbc_javac</li>
    <li>fastddsgen</li>
    <li>fiji</li>
    <li>freeplane</li>
    <li>gradle_5</li>
    <li>gradle_6</li>
    <li>gremlin-console</li>
    <li>gremlin-server</li>
    <li>igv</li>
    <li>irpf</li>
    <li>janusgraph</li>
    <li>jd-gui</li>
    <li>jdk11 (openjdk11)</li>
    <li>jprofiler</li>
    <li>keystore-explorer</li>
    <li>ma1sd</li>
    <li>neo4j</li>
    <li>nzbhydra2</li>
    <li>pdfsam-basic</li>
    <li>pdfstudio2021</li>
    <li>pdfstudioviewer</li>
    <li>python310Packages.adb-enhanced</li>
    <li>python39Packages.adb-enhanced</li>
    <li>scenebuilder</li>
    <li>scenic-view</li>
    <li>shattered-pixel-dungeon</li>
    <li>smartgithg</li>
    <li>soapui</li>
    <li>stm32cubemx</li>
    <li>weka</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> This would break `bisq-desktop`, which uses JavaFX on openjdk11 and I could not get it to work with either openjdk17 or openjdk19.

FYI this will be broken after marking python27 unmaintained.

**Comment by emmanuelrosa** [comment]
It's my understanding that Python 2 is used to build the JavaFX web component, which is based on WebKit. If it's true that the rest of JavaFX doesn't depend on Python 2, then perhaps it's better to disable the web component by default.

**Comment by SuperSandro2000** [comment]
I don't know the details about that but if we disable less by just disabling some webkit stuff then I think that sounds like something we should do.

**Comment by GaetanLepage** [comment]
I don't know if this this issue is directly caused by this PR but `pdfsam-basic` is now broken:
```
❮ nix shell nixpkgs#pdfsam-basic

❯ pdfsam-basic          
Dec 06, 2022 10:51:03 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @753f5ceb'
Loading library glassgtk3 from resource failed: java.lang.UnsatisfiedLinkError: /home/gaetan/.openjfx/cache/17.0.2-ea/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/gaetan/.openjfx/cache/17.0.2-ea/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:195)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:179)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: [.]
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:301)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: [.]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:166)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:195)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:179)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:291)
	... 6 more 
```

**Comment by thiagokokada** [comment]
> I don't know if this this issue is directly caused by this PR but `pdfsam-basic` is now broken:
> ```
> ❮ nix shell nixpkgs#pdfsam-basic
> 
> ❯ pdfsam-basic          
> Dec 06, 2022 10:51:03 AM com.sun.javafx.application.PlatformImpl startup
> WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @753f5ceb'
> Loading library glassgtk3 from resource failed: java.lang.UnsatisfiedLinkError: /home/gaetan/.openjfx/cache/17.0.2-ea/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
> java.lang.UnsatisfiedLinkError: /home/gaetan/.openjfx/cache/17.0.2-ea/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
> 	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
> 	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
> 	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
> 	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
> 	at java.base/java.lang.Runtime.load0(Runtime.java:768)
> 	at java.base/java.lang.System.load(System.java:1837)
> 	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
> 	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:195)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:179)
> 	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
> 	at com.sun.glass.ui.Application.run(Application.java:146)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:291)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
> 	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Exception in thread "main" java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: [.]
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:301)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
> 	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: [.]
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
> 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
> 	at java.base/java.lang.System.loadLibrary(System.java:1873)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:166)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
> 	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:195)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:179)
> 	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
> 	at com.sun.glass.ui.Application.run(Application.java:146)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:291)
> 	... 6 more 
> ```

You can always manually `openjfx` re-enable like I did for `bisq-desktop`, but this will break soon.

**Comment by emmanuelrosa** [comment]
Here's the upstream unresolved issue: https://bugs.openjdk.org/browse/JDK-8230778
Another issue (https://bugs.openjdk.org/browse/JDK-8230779) claims that WebKit built with python3. I checked the openjdk/jfx repo (https://github.com/openjdk/jfx) and there's evidence of python3 support.

Is there a way to run a build with python3 to see what happens? I ask because doubt I can build javafx on my laptop.

**Comment by thiagokokada** [comment]
> Here's the upstream unresolved issue: https://bugs.openjdk.org/browse/JDK-8230778
> Another issue (https://bugs.openjdk.org/browse/JDK-8230779) claims that WebKit built with python3. I checked the openjdk/jfx repo (https://github.com/openjdk/jfx) and there's evidence of python3 support.
> 
> Is there a way to run a build with python3 to see what happens? I ask because doubt I can build javafx on my laptop.

Only available for `openjfx17` (I checked).

Maybe we can backport the patch, but I looked around and didn't find it.

**Pull request merged**
