### PR TITLE
python39Packages.numba-scipy: update stale substituteInPlace

### PR DESCRIPTION
**Pull request by fabaff**
###### Description of changes
Fix build (https://hydra.nixos.org/build/177078753)

ZHF: #172160

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
`aesara` needs some work too.

**Comment by fabaff** [comment]
`qiskit-*` failures are addressed in #174296.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 174152` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.graspologic</li>
    <li>python310Packages.pygbm</li>
    <li>python310Packages.shap</li>
    <li>python39Packages.graspologic</li>
    <li>python39Packages.pygbm</li>
    <li>python39Packages.shap</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python310Packages.intake</li>
  </ul>
</details>
<details>
  <summary>78 packages built:</summary>
  <ul>
    <li>python310Packages.aeppl</li>
    <li>python310Packages.aesara</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.awkward</li>
    <li>python310Packages.clifford</li>
    <li>python310Packages.cppe</li>
    <li>python310Packages.dask-ml</li>
    <li>python310Packages.datashader</li>
    <li>python310Packages.fastparquet</li>
    <li>python310Packages.ffcv</li>
    <li>python310Packages.gumath</li>
    <li>python310Packages.hyppo</li>
    <li>python310Packages.intake-parquet</li>
    <li>python310Packages.librosa</li>
    <li>python310Packages.numba</li>
    <li>python310Packages.numba-scipy</li>
    <li>python310Packages.numbaWithCuda</li>
    <li>python310Packages.numdifftools</li>
    <li>python310Packages.persim</li>
    <li>python310Packages.phik</li>
    <li>python310Packages.pygmo</li>
    <li>python310Packages.pymc3</li>
    <li>python310Packages.pynndescent</li>
    <li>python310Packages.pyscf</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-machine-learning</li>
    <li>python310Packages.resampy</li>
    <li>python310Packages.ripser</li>
    <li>python310Packages.scikit-tda</li>
    <li>python310Packages.sparse</li>
    <li>python310Packages.stumpy</li>
    <li>python310Packages.stytra</li>
    <li>python310Packages.tensorly</li>
    <li>python310Packages.timezonefinder</li>
    <li>python310Packages.trackpy</li>
    <li>python310Packages.umap-learn</li>
    <li>python310Packages.uproot</li>
    <li>python310Packages.xarray-einstats</li>
    <li>python39Packages.aeppl</li>
    <li>python39Packages.aesara</li>
    <li>python39Packages.arviz</li>
    <li>python39Packages.awkward</li>
    <li>python39Packages.clifford</li>
    <li>python39Packages.cppe</li>
    <li>python39Packages.dask-ml</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.fastparquet</li>
    <li>python39Packages.ffcv</li>
    <li>python39Packages.gumath</li>
    <li>python39Packages.hyppo</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.intake-parquet</li>
    <li>python39Packages.librosa</li>
    <li>python39Packages.numba</li>
    <li>python39Packages.numba-scipy</li>
    <li>python39Packages.numbaWithCuda</li>
    <li>python39Packages.numdifftools</li>
    <li>python39Packages.persim</li>
    <li>python39Packages.phik</li>
    <li>python39Packages.pygmo</li>
    <li>python39Packages.pymc3</li>
    <li>python39Packages.pynndescent</li>
    <li>python39Packages.pyscf</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-machine-learning</li>
    <li>python39Packages.resampy</li>
    <li>python39Packages.ripser</li>
    <li>python39Packages.scikit-tda</li>
    <li>python39Packages.sparse</li>
    <li>python39Packages.stumpy</li>
    <li>python39Packages.stytra</li>
    <li>python39Packages.tensorly</li>
    <li>python39Packages.timezonefinder</li>
    <li>python39Packages.trackpy</li>
    <li>python39Packages.umap-learn</li>
    <li>python39Packages.uproot</li>
    <li>python39Packages.xarray-einstats</li>
    <li>tts</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 174152` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.graspologic</li>
    <li>python310Packages.pygbm</li>
    <li>python310Packages.shap</li>
    <li>python39Packages.graspologic</li>
    <li>python39Packages.pygbm</li>
    <li>python39Packages.shap</li>
  </ul>
</details>
<details>
  <summary>79 packages built:</summary>
  <ul>
    <li>python310Packages.aeppl</li>
    <li>python310Packages.aesara</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.awkward</li>
    <li>python310Packages.clifford</li>
    <li>python310Packages.cppe</li>
    <li>python310Packages.dask-ml</li>
    <li>python310Packages.datashader</li>
    <li>python310Packages.fastparquet</li>
    <li>python310Packages.ffcv</li>
    <li>python310Packages.gumath</li>
    <li>python310Packages.hyppo</li>
    <li>python310Packages.intake</li>
    <li>python310Packages.intake-parquet</li>
    <li>python310Packages.librosa</li>
    <li>python310Packages.numba</li>
    <li>python310Packages.numba-scipy</li>
    <li>python310Packages.numbaWithCuda</li>
    <li>python310Packages.numdifftools</li>
    <li>python310Packages.persim</li>
    <li>python310Packages.phik</li>
    <li>python310Packages.pygmo</li>
    <li>python310Packages.pymc3</li>
    <li>python310Packages.pynndescent</li>
    <li>python310Packages.pyscf</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-machine-learning</li>
    <li>python310Packages.resampy</li>
    <li>python310Packages.ripser</li>
    <li>python310Packages.scikit-tda</li>
    <li>python310Packages.sparse</li>
    <li>python310Packages.stumpy</li>
    <li>python310Packages.stytra</li>
    <li>python310Packages.tensorly</li>
    <li>python310Packages.timezonefinder</li>
    <li>python310Packages.trackpy</li>
    <li>python310Packages.umap-learn</li>
    <li>python310Packages.uproot</li>
    <li>python310Packages.xarray-einstats</li>
    <li>python39Packages.aeppl</li>
    <li>python39Packages.aesara</li>
    <li>python39Packages.arviz</li>
    <li>python39Packages.awkward</li>
    <li>python39Packages.clifford</li>
    <li>python39Packages.cppe</li>
    <li>python39Packages.dask-ml</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.fastparquet</li>
    <li>python39Packages.ffcv</li>
    <li>python39Packages.gumath</li>
    <li>python39Packages.hyppo</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.intake-parquet</li>
    <li>python39Packages.librosa</li>
    <li>python39Packages.numba</li>
    <li>python39Packages.numba-scipy</li>
    <li>python39Packages.numbaWithCuda</li>
    <li>python39Packages.numdifftools</li>
    <li>python39Packages.persim</li>
    <li>python39Packages.phik</li>
    <li>python39Packages.pygmo</li>
    <li>python39Packages.pymc3</li>
    <li>python39Packages.pynndescent</li>
    <li>python39Packages.pyscf</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-machine-learning</li>
    <li>python39Packages.resampy</li>
    <li>python39Packages.ripser</li>
    <li>python39Packages.scikit-tda</li>
    <li>python39Packages.sparse</li>
    <li>python39Packages.stumpy</li>
    <li>python39Packages.stytra</li>
    <li>python39Packages.tensorly</li>
    <li>python39Packages.timezonefinder</li>
    <li>python39Packages.trackpy</li>
    <li>python39Packages.umap-learn</li>
    <li>python39Packages.uproot</li>
    <li>python39Packages.xarray-einstats</li>
    <li>tts</li>
  </ul>
</details>

**Comment by risicle** [comment]
@fabaff do you still intend for this to be backported to 22.05?

**Comment by risicle** [comment]
@fabaff have done a basic backport in  #175286, but don't know if perhaps more (all?) of  #174720 was intended to be backported

**Pull request merged**
