### PR TITLE
waagent: enable provisioning

### PR DESCRIPTION
**Pull request by Atry**
## Description of changes

Currently there are two issues in Azure provisioning:

1. Provisioning in `waagent` was disabled in #206974 because provisioning always failed. 
2. Azure VM will timeout after 90 seconds when mounting `/dev/sr0` during restarting an Azure VM, because `/dev/sr0` is only available the first time starting an Azure VM.

This PR fixes provisioning in `waagent` and enables it.

## Things done

- Switched Python version to 3.9, because `waagent` 2.8.0.11 is not compatible with Python 3.10. See https://github.com/Azure/WALinuxAgent/issues/2753
- Removed the call to `self.osutil.conf_sshd` because it will try to modify `/etc/sshd/sshd_config` and raise an error about read-only file system
- Stopped mounting `/dev/sr0` because it should be handled by `waagent`

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atry** [comment]
Note that the code to read `CustomData.bin` is legacy. Nowadays there is not such file at all.

**Comment by Atry** [comment]
The patch is downloaded from https://github.com/Atry/WALinuxAgent/commit/383e7c826906baedcd12ae7c20a4a5d4b32b104a.patch

**Review by zimbatm — APPROVED** [review]
Looks good, but I don't have a machine to test it right now.

Going forwards, please limit the number of people you request for review, so it's proportionate to the amount of code you change.

**Comment by Atry** [comment]
> Looks good, but I don't have a machine to test it right now.


I am using this PR to build images, which work well on Azure

**Comment by Mic92** [comment]
Can one of you test this by chance? @henrirosten @AkechiShiro
I don't have an Azure subscription and the last time I did, it screwed up my microsoft account.

**Comment by AkechiShiro** [comment]
Hi @Mic92 @Atry how can this be tested 9n Azure, an NixOS image must be built and uploaded to Azure and then booted as a VM ?

**Comment by Atry** [comment]
@AkechiShiro 
1. I use https://github.com/nix-community/nixos-generators to create the vhd file
2. Then I uploaded the vhd file to Azure Blob Storage
3. Then I created a VM Image from the vhd on the Azure Blob Storage
4. Then I created a VM from the VM image

**Comment by Atry** [comment]
@AkechiShiro @Mic92 Any updates?

If you don't have time to manually test it on Azure, do you trust me enough to merge this PR, given that it works for me.

**Comment by AkechiShiro** [comment]
Hi @Atry, I'm sorry but I couldn't easily test it, I'd need a temporary throwaway account (it's a bit of a pain to setup just for testing this PR)

**Pull request merged**
