### PR TITLE
oraclejdk8: 8u211 -> 8u241

### PR DESCRIPTION
**Pull request by volth**
Oracle JDK has not been updated since April 2019 so it should be either updated or marked with `meta.vulnerable = true`.

Besides many fixes, there are 2 changes affected packaging:

1. There are no more CPU and PSU versions, so I removed `oraclejdk8psu`. I might need to add `oraclejdk8psu =  oraclejdk8` in `aliases.nix` but I am not sure in correctness of this step.

2. it is not possible to download with `curl -b oraclelicense=a`, so `fetchurl` is back to `requireFile`. We might be able to develop an automated downloader using `selenuim` or something like.

### CODE REVIEW

**Comment by Ma27** [comment]
Thanks! Also published some release notes about this: 0c960262d159d3a884dadc3d4e4b131557dad116

Currently checking how much effort it would be to backport this :)

**Comment by Ma27** [comment]
So, travelling home from FOSDEM took a bit longer than I expected, will take care of #79129 and the backport tomorrow :)

**Comment by danbst** [comment]
> We might be able to develop an automated downloader using selenuim

wasn't OracleJDK hidden by paywall or registerwall? I'm redirected to https://login.oracle.com/mysso/signon.jsp when I try to download any release.

**Comment by conferno** [comment]
> > We might be able to develop an automated downloader using selenuim
> 
> wasn't OracleJDK hidden by paywall or registerwall? I'm redirected to https://login.oracle.com/mysso/signon.jsp when I try to download any release.

Yes, that's what I meant. It seems difficult to bypass registerwall only with `curl`.

**Comment by Ma27** [comment]
> wasn't OracleJDK hidden by paywall or registerwall? I'm redirected to https://login.oracle.com/mysso/signon.jsp when I try to download any release.

Yes. I guess this is related to their altered licensing model. But tbh I doubt that we should keep old oraclejdk versions.

> Yes, that's what I meant. It seems difficult to bypass registerwall only with curl.

I'm definetely not a lawyer, but are we sure that doesn't violate their terms of use?

**Comment by Ma27** [comment]
@NixOS/backports how would you backport this package to 19.09? On one hand we have a fairly oudated oraclejdk version there, on the other hand, this is definetely a breaking change (packages got removed and the src needs to be obtained with `requireFile` now). OTOH I'm sure that there are at least some oraclejdk users on 19.09, so simply marking this as vulnerable is IMHO not an option.

I'd suggest we enhance the error message of `requireFile` explaining why this was updated on 19.09 and simply add `oraclejdk8psu = throw ...` for the removed *psu packages, but I'm not sure if that's sufficient.

**Pull request merged**
