### PR TITLE
CODEOWNERS: Watch the maintainers lists

### LINKED ISSUE #275410: Lack of QA for changes to `maintainers/maintainer-list.nix`
## Issue description

The file `maintainers/maintainer-list.nix` seems to be randomly edited by committers who feel like doing so, thereby ignoring data protection laws governing some regions where our contributors come from (e.g. https://github.com/NixOS/nixpkgs/pull/178656, https://github.com/NixOS/nixpkgs/pull/272199, https://github.com/NixOS/nixpkgs/pull/273137 as of before the force-push) guidelines our community gave to itself (e.g. https://github.com/NixOS/nixpkgs/pull/275328, https://github.com/NixOS/nixpkgs/pull/275370). Having our community guidelines ignored at random lets NixOS look unprofessional and can scare away contributors and supporters. Having data protection laws ignored might even lead to expensive liabilities for the NixOS foundation, meaning that the money would be missing when paying for servers or incentivizing contributors. Therefore, there should be some QA when editing that file.

A straightforward suggestion regarding this would be to install one or more maintainers for that file itself. These would have to review any PRs touching it before merging would be allowed. The maintainers should provide evidence that they are aware of laws governing personal data in the different jurisdictions we work with, and aware of our community guidelines.

### Steps to reproduce

1. Wait
2. See commits happening where laws and/or community guidelines are being ignored

## Technical details

Not applicable.

### PR DESCRIPTION
**Pull request by piegamesde**
## Description of changes

Closes #275410. CC @infinisil this is an invitation for you to join, if you don't want to then I'll drop you back to only watching the README

I think that simply having a couple more critical eyes on every PR to this file should be sufficient to avoid past mistakes.

### CODE REVIEW

**Comment by JulienMalka** [comment]
For info:
```
git log --since=2023-01-10 maintainers/maintainer-list.nix | grep "Merge" | wc -l
602
```

**Comment by infinisil** [comment]
Oof no that's too much, this sends pings for _every_ PR that adds a maintainer, which is like multiple per day.

I'd also suggest you to not do that, it doesn't seem realistic to keep track of that without just ignoring all pings after like a week.

**Comment by piegamesde** [comment]
@JulienMalka Thanks for the heads up.

I just went through the PRs which edited that file, and most changes can be easily reviewed within 30 seconds, start to finish. At two per day, that's about an additional minute to my morning mails check.

Or to put it differently: With the time that I already wasted on this entire debacle, I could have reviewed a whole year's worth of changes to this file instead.

(I agree though that this could be significantly optimized with a couple of scripts)

@infinisil that's fine. If somebody else volunteers to split the work load, I'd appreciate that

**Comment by Janik-Haag** [comment]
You can add me as well, I check my notifications way too much anyways.

**Comment by Janik-Haag** [comment]
Added my self and squashed the commits. (Talked with piegames in dms). 
Also for context: I already get >100 notifications per week from github so adding ~12 more shouldn't be too much.

**Comment by infinisil** [comment]
Up to you of course, but keep in mind that these small things do add up!

**Review by JulienMalka — APPROVED** [review]
Please do remove this change if it ever becomes to painful

**Review by adamcstephens — APPROVED** [review]

**Pull request merged**
