### PR TITLE
peertube: fix with openssl 3

### PR DESCRIPTION
**Pull request by sbruder**
###### Description of changes

This fixes peertube to work with openssl 3. Two things were changed to achieve this:

Webpack needs to be run with `NODE_OPTIONS=--openssl-legacy-provider` as described in https://github.com/webpack/webpack/issues/14532. This is the case even though PeerTube already uses a recent webpack version (updating it also did not make it work without the workaround).

An [upstream patch](https://github.com/Chocobozzz/PeerTube/commit/5d7cb63ede7c4bba93954c0586f589ad9748d5ea) is applied to the source. Because it did not apply to the tagged version, I had to rebase it and include the file. Also, the yarn lockfile had to be included because fetchYarnDeps doesn’t use the patched file from the main derivation.

###### Things done

I did not test this on an actual deployment, only with the NixOS system test.

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
My guess is that adding a yarn.lock file is not recommended as it is large size. Maybe need to find another variant.

**Comment by Izorkin** [comment]
> Right, we should avoid adding large files where it is possible. Do you have any idea what other solution could be used? One approach could be to patch the source and copy only the lockfile to $out in a `runCommand` derivation, though I don’t know if that is preferred

Try to see the implementation in mastodon - https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/mastodon/source.nix



> Also, quite a number of other packages seem to include a yarn lock file and this one will be removed with the next version upgrade anyway, so it might not be that problematic.

These changes will affect the size of the history in the git repository.

**Comment by Izorkin** [comment]
@GrahamcOfBorg test peertube

**Review by Izorkin — APPROVED** [review]

**Comment by tjni** [comment]
Just saw that [v4.3.0](https://github.com/Chocobozzz/PeerTube/releases/tag/v4.3.0) was released. It also includes an update of `babel-loader`, which might remove the need for `--openssl-legacy-provider`. However, it is still affected by https://github.com/Chocobozzz/PeerTube/issues/5263.

**Comment by yu-re-ka** [comment]
Note that after #193047 you can simply `inherit src patches;` in fetchYarnDeps

**Comment by NickCao** [comment]
superseded by #194196

**Pull request closed without merging**
