### PR TITLE
systemd: enable debug info

### PR DESCRIPTION
**Pull request by alyssais**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by flokli** [comment]
How big are these?

**Comment by alyssais** [comment]
/nix/store/wg3h2lw2gj4fwgdib16wndn21rlphgc7-systemd-254.6-debug	 35.4M

**Review by flokli — APPROVED** [review]

**Comment by trofi** [comment]
I think this change broke 32-bit build of `systemd` on` staging`:

```
$  nix build --no-link -f. pkgsi686Linux.systemd -L
...
systemd> Error: failed to link 'src/core/bpf/restrict_fs/restrict-fs.bpf.unstripped.o': Invalid argument (22)
```

The failure happens because `separateDebugInfo` has an effect of passing `-ggdb -Wa,--compress-debug-sections`. both `gcc` (systemd's executables) and `clang -target bpf` (BTF programs) are built against these flags.

And `bpftool` rejects created debug sections due to alignment mismatch (probably between compressed and uncompressed alignments data?).

I rpoposed a tiny patch to improve error message around `bpftool` as https://lore.kernel.org/bpf/20231207180919.2379718-1-slyich@gmail.com/

I'm not sure where the exact bug is. I would say we should never pass `-Wa,--compress-debug-sections` to `clang -target bpf` until `bpftool` support around it is sorted.

**Comment by ElvishJerricco** [comment]
Can we revert this? This seems like something that only needs to be enabled by the few who need it, and that creates problems in other cases.

**Comment by flokli** [comment]
Yes, let's revert this for now. It can always be reenabled after tested with some less common architectures, but there's no need to keep them broken until separateDebugInfo = yes on them is figured out.

**Comment by flokli** [comment]
I didn't say we couldn't, but writing that code takes more time, while the revert is quick.

I pushed a revert at https://github.com/NixOS/nixpkgs/pull/272947, happy to review another commit that introduces debuginfo for known-working platforms afterwards, but no need to keep staging broken until someone does do that.

**Comment by trofi** [comment]
Proposed the knob to disable debug section compression and re-enable split debug data for `systemd`: https://github.com/NixOS/nixpkgs/pull/273096

**Comment by flokli** [comment]
> > I didn't say we couldn't, but writing that code takes more time, while the revert is quick.
> 
> How long does it take to conservatively write `separateDebugInfo = stdenv.hostPlatform.isx86_64 || stdenv.hostPlatform.isAarch64`? We don't need to be exhaustive at first, but we could stay at near 100% coverage with no more effort than a revert.

I meant to say, I did not have access to a beefy aarch64 builder, so I couldn't say for sure that PR *does not* also regress aarch64-linux. The report was about 32bit only, but maybe aarch64 was broken too, who knows? I figured the revert was easier, unbreaking staging, while this can be refined without too much of a rush.

**Pull request merged**
