### PR TITLE
_1password-gui: 8.0.30 -> 8.0.33-53.BETA

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

- Update 1Password.
- Use the upstream tarball rather than AppImage.
- Include the browser support and keyring helper programs.
- Fix the update script.

Many of the improvements and cleanups were provided by Savanni D'Gerinel.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121378` at f5c91665 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>_1password-gui</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/misc/1password-gui/default.nix:23:3:
```
   |
23 |   installPhase = let
   |   ^
```
</li>
  </ul>
</details>

**Comment by maxeaubrey** [comment]
1password itself still works, so yay!

I can't get browser integration to work (maybe I'm missing something that needs doing?), and the keyring helper crashes when run directly (that seems intentional):
```
WARN  2021-05-01T12:32:24.676 main(ThreadId(1)) [1P:foundation/op-linux/src/bin/keyring_helper.rs:163] failed to verify parent binary name, aborting
```

It appears the idea is for 1password to start it, but that fails too.
```
WARN  2021-05-01T12:56:04.132 op_executor:invocation_loop(ThreadId(9)) [1P:foundation/op-linux/src/kernel_keyring.rs:684] failed to initialize keyring helper, its functionality will be unavailable: Spawning(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

Additionally there's some setuid bits for the helper in the install script, but regardless I can't really test it because of the above, and I don't know where to start with any of it - no electron experience here :)

There's also a policy kit file for biometrics support, and while I don't have a working fingerprint reader (thanks Dell), it would probably be nice to include it? I can't actually speak to its need fully.

**Comment by danieldk** [comment]
> I can't get browser integration to work (maybe I'm missing something that needs doing?), and the keyring helper crashes when run directly (that seems intentional):
> 
> ```
> WARN  2021-05-01T12:32:24.676 main(ThreadId(1)) [1P:foundation/op-linux/src/bin/keyring_helper.rs:163] failed to verify parent binary name, aborting
> ```
> 
> It appears the idea is for 1password to start it, but that fails too.
> 
> ```
> WARN  2021-05-01T12:56:04.132 op_executor:invocation_loop(ThreadId(9)) [1P:foundation/op-linux/src/kernel_keyring.rs:684] failed to initialize keyring helper, its functionality will be unavailable: Spawning(Os { code: 2, kind: NotFound, message: "No such file or directory" })
> ```

Thanks for testing this! I hadn't got around to it yet. It seems that it wants to find the helper in the Electron library directory:

```
pid 98058] execve("/nix/store/1ilm922l62npx1gn6m85nq4w00l26369-electron-11.4.3/lib/1Password-KeyringHelper", ["/nix/store/1ilm922l62npx1gn6m85n"...], 0x29656a599180 /* 80 vars */ <unfinished ...>
```

@savannidgerinel do you have any hints on how we can nudge 1Password to execute `1Password-KeyringHelper` from a different directory? I added the directory to the path

```
    makeWrapper "${electron_11}/bin/electron" "$out/bin/${pname}" \
      --add-flags "$out/share/${pname}/resources/app.asar" \
      --prefix LD_LIBRARY_PATH : "${lib.makeLibraryPath runtimeLibs}" \
      --prefix PATH : "${placeholder "out"}/share/${pname}"

```

But that doesn't seem to help.

**Comment by savannidgerinel** [comment]
I don't recall how 1Password looks for the Keyring Helper, and I'm on vacation this week. I won't be able to dig into the code until I return, but I'll check with my co-workers.

**Comment by danieldk** [comment]
> I don't recall how 1Password looks for the Keyring Helper, and I'm on vacation this week. I won't be able to dig into the code until I return, but I'll check with my co-workers.

Have good vacation! And thanks for checking.

@maxeaubrey I propose that we merge this as-is, so that we are up-to-date version-wise. Then we can look into fixing integration later.

**Comment by maxeaubrey** [comment]
@danieldk Makes perfect sense to me, all existing features work as they did before so it's not any kind of step back to merge it.

**Pull request merged**
