### PR TITLE
bazel_4: 4.0.0 -> 4.1.0

### PR DESCRIPTION
**Pull request by dmivankov**
https://github.com/bazelbuild/bazel/releases/tag/4.1.0
    
other minor changes:
- grep for /bin/ rather than /bin for blanket substitute
- invoke {pre,post}{Build,Install} hooks

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123895` at 3e965a42 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>bazel_4</li>
  </ul>
</details>
<details>
  <summary>20 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/true' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/PredefinedAttributes.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env python' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:572:3:
```
    |
572 |   installPhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/PredefinedAttributes.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/true' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/PredefinedAttributes.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/true' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:542:3:
```
    |
542 |   buildPhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env python' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/PredefinedAttributes.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env python' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env python' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/PredefinedAttributes.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:170:0:
```
    |
170 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
  </ul>
</details>

**Comment by dmivankov** [comment]
Interesting suggestions about unused substitutions, will try to have a look

**Comment by jonringer** [comment]
If they are being blanket applied across a host of files, I would say you can pass over the suggestions. But some of them may warrant investigation.

**Comment by uri-canva** [comment]
Tested on macOS, works.

**Comment by dmivankov** [comment]
Had a quick look into suggestions:
- added pre/post hooks involcations
- changed `grep /bin` with `grep /bin/`
- some unused substitutions are false positive and/or about /bin/ mentioned in comments/docs
- in bazel source code there seems to be more (/usr)/bin/ references, but hard to tell if it is an issue or changed since 3.7 or 4.0
- especially unclear with [getconf on darwin](https://github.com/bazelbuild/bazel/blob/4.1.0/src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java#L55), so let's maybe rely on tests & user tests for now

**Comment by timothyklim** [comment]
Please, include patch for bazel-toolchains https://github.com/bazelbuild/bazel/issues/13099#issuecomment-846140709

**Comment by dmivankov** [comment]
@timothyklim not very familiar with code around that patch
- does it change packaged bazel binary?
- is it to be applied to user WORKSPACE files only?

My first impression is that users simply need to use patched/suitable bazel-toolchains with bazel-4.1.0 and bazel itself can't be patched to be compatible with older versions. So unless we hit an issue compiling bazel 4.1..0 with bazel 4.1.0 (&rbe?) all should be fine?

**Comment by uri-canva** [comment]
> Please, include patch for bazel-toolchains

I'd rather it wasn't included: nixpkgs bazel behaving differently from upstream makes debugging issues with it harder, and makes discussions amongst the broader bazel community less applicable.

**Comment by uri-canva** [comment]
ping @mboes @Profpatsch

**Comment by dmivankov** [comment]
fwiw, using 4.1.0 from PR works fine for me so far on NixOS

**Pull request merged**
