### PR TITLE
mitmproxy: 4.0.4 -> 5.0.1

### PR DESCRIPTION
**Pull request by arcz**
###### Motivation for this change
New mitmproxy release https://mitmproxy.org/posts/releases/mitmproxy5/.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by kamilchm — CHANGES_REQUESTED** [review]
I couldn't build it without additional deps in check phase https://github.com/NixOS/nixpkgs/commit/e9e0db1b81fe23a6d1372b145a6a18aaffef7e5b

**Comment by arcz** [comment]
@kamilchm Thanks, I've updated the code. Not sure why my macOS build passed without those dependencies...

**Review by kamilchm — APPROVED** [review]

**Comment by arcz** [comment]
is there still anything to be done by me here?

**Comment by alyssais** [comment]
Why are you adding the Python dependencies here instead of in python3Packages?

**Comment by arcz** [comment]
@alyssais no particular reason, I can move them python3Packages if it's better to have them there

**Comment by alyssais** [comment]
Artur Cygan <notifications@github.com> writes:

> @alyssais no particular reason, I can move them python3Packages if
> it's better to have them there

That's certainly what's usually done in Nixpkgs.

**Review by kamilchm — APPROVED** [review]

**Comment by arcz** [comment]
Looks like it's been already updated in https://github.com/NixOS/nixpkgs/pull/85458

**Pull request closed without merging**
