### PR TITLE
mysql: fix replication tests

### PR DESCRIPTION
**Pull request by polynomial**
Eliminate race condition in replication test
Remove replication configuration from standalone test
Improve mysql command syntax consistency

### CODE REVIEW

**Comment by polynomial** [comment]
This is related to: https://github.com/NixOS/nixpkgs/pull/7198 which broke some tests: http://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors 
cc: @garbas @fpletz

**Comment by polynomial** [comment]
Thanks to @cransom for pointing this out!

**Comment by grahamc** [comment]
LGTM can you refresh my memory on running this test locally?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/17174#-:-KNIP2d0U45dEJDaQYyt:2113190605)*

**Comment by polynomial** [comment]
Thanks @grahamc! Here is what I did:
$ nix-build nixos/tests/mysql-replication.nix
$ nix-build nixos/tests/mysql.nix

**Comment by grahamc** [comment]
Thanks! I tried building mysql and mysql-replication, and they both failed. Maybe my computer is just less powerful, and the wait time isn't long enough?

Output: https://gist.github.com/grahamc/ce215d595cf1009904ff898a7e0ea464

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/17174#-:-KNIZiDh2J_i9A4LPO8Q:2073221128)*

**Comment by cransom** [comment]
@grahamc I had similar results, in that, on my i7 MBP, it failed to start up in time. When I reran it on my desktop, it finished successfully. 

The big thing I noticed was that it took 13 seconds just to start systemd, https://gist.github.com/grahamc/ce215d595cf1009904ff898a7e0ea464#file-gistfile1-txt-L326 and thats a really long time. I verified it took that long on my laptop as well. On the desktop (its an i7-3730k with an ssd), systemd launched at the 2.25 second mark.  So. Hrm. Weird.

**Pull request merged**
