### PR TITLE
Update pkgs

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

Update packages I maintain.

I didn't do any testing yet, but will do now on my VM at my university (test building).

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by grahamc — APPROVED** [review]

**Comment by grahamc** [comment]
LGTM, is this tested @matthiasbeyer?

**Comment by matthiasbeyer** [comment]
@grahamc I started a `nix-build` job for all updated packages on a VM in the cloud of my university, though it

```
download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/2r2hb5kqqzrpir44fws2v2zy9j5b7ai5.narinfo’ (Curl error 6) 
```

all the time. I would at least wait until this job finished, though that might some time as it seems that internet connection on the VM is _really_ bad right now.

**Comment by matthiasbeyer** [comment]
Sorry, f*d up here, I thought taskwarrior 2.6 is already released, what is not the case.

**Comment by matthiasbeyer** [comment]
done.

**Comment by matthiasbeyer** [comment]
Excluded:

* sqlitebrowser
* khard
* hstr

All other packages build on my testing machine. So I'm ready to merge now.

I had to introduce a new package in this set to be able to update "rtv" - hope that's okay for you!

**Pull request merged**
