### PR TITLE
telegram-desktop: 4.14.9 -> 4.14.12

### PR DESCRIPTION
**Pull request by NickCao**
Diff: https://github.com/telegramdesktop/tdesktop/compare/v4.14.9...v4.14.12

Changelog: https://github.com/telegramdesktop/tdesktop/releases/tag/v4.14.12

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by h7x4 — APPROVED** [review]
Had a quick look through the upstream diff, didn't see anything that would require any extra action

**Comment by NickCao** [comment]
Build is failing on darwin, could use some help.

**Comment by h7x4** [comment]
Looks like it's using some deprecated API in https://github.com/desktop-app/lib_webrtc.

I guess we should notify upstream, and either patch it or tweak some compile flags? I think this would be the natural replacement: https://developer.apple.com/documentation/avfoundation/avcapturedevicediscoverysession/2361539-discoverysessionwithdevicetypes

**Comment by NickCao** [comment]
> Build is failing on darwin, could use some help.

cc @ilya-fedin

**Comment by ilya-fedin** [comment]
I don't see the build log but if deprecated API is really the cause then the right way would be to set the right deployment target I guess. Upstream supports macOS versions starting with 10.13.

**Comment by ilya-fedin** [comment]
I see only the following errors in the current build log
```
/tmp/nix-build-telegram-desktop-4.14.13.drv-0/source/Telegram/lib_webrtc/webrtc/platform/mac/webrtc_environment_mac.mm:54:14: error: use of undeclared identifier 'kAudioObjectPropertyElementMain'; did you mean 'kAudioObjectPropertyElementName'?
        .mElement = kAudioObjectPropertyElementMain,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    kAudioObjectPropertyElementName
```
It seems it's since macOS 12.0 but nixpkgs has SDK 11.0 so replacing it with `kAudioObjectPropertyElementMaster` is likely the solution

**Comment by NickCao** [comment]
@ofborg build telegram-desktop

**Pull request merged**
