### PR TITLE
Add django-hijack and dependencies

### PR DESCRIPTION
**Pull request by risicle**

### CODE REVIEW

**Comment by FRidh** [comment]
Why are you using `makeOverridable`? Is that because you would like those packages to work with all versions of `django`? If that's the case, then please let the user do a `pkgs.overridePackages` instead.
I saw that there are a couple more django packages which use `makeOverridable` but in my opinion we should get rid of that.

**Comment by risicle** [comment]
Oh - that's interesting - looking closer it looks like `overridePackages` is cleverer than I thought it was...

**Comment by risicle** [comment]
Also looks like I need to do a bit of python-version-disabling

**Comment by domenkozar** [comment]
travis-ci fails to build due to encoding issues in `setup.py`

**Comment by risicle** [comment]
yup, I'm withdrawing this for now - have discovered a much neater way of doing lots of this thanks to @FRidh 's comment. Will be back with it when I get round to fixing it up.

**Comment by risicle** [comment]
Hmm @FRidh the reason I did the `makeOverridable` has come back to me - how else is one supposed to have a package which by default depends on, say, `django_1_5`, but is overridable to depend on a different django? We wouldn't want all django packages by default depending on `django_1_5`

**Comment by risicle** [comment]
@FRidh actually, I'm not sure I understand how I'm supposed to do "deep" overriding with your suggestion. If I remove all the makeOverridable nonsense and make all django dependencies references in `python-packages.nix` to `self.django` and override my packages something like:

```
  pkgsInner = pkgs.overridePackages (pkgsSelf: pkgsSuper: {
    postgresql = pkgsSuper.postgresql94;
    python27Packages = pkgsSuper.python27Packages.override {
      self = pkgsSuper.python27Packages // {
        django = pkgsSuper.python27Packages.django_1_8;
      };
      pkgs = pkgsSelf;
    };
    apacheHttpd = pkgsSuper.apacheHttpd_2_2.override { mpm = "worker"; };
  });
```

this is great - `django_hijack` will depend on django 1.8 - but `django_hijack`'s `django_compat` dependency will itself depend on django 1.7.

**Comment by FRidh** [comment]
I knew it had to work, but it took me some time before I figured out what was going wrong.

See my example, `blaze` depends on `pandas` which depends on `scipy`. 
What you're missing is `rec`, you want `python27Packages.override { self = ...` to use the `python27Packages` you are defining right there.
```
with import <nixpkgs> {};

(let

newpkgs = pkgs.overridePackages(self: super: rec {
  python35Packages = super.python35Packages.override {
    self = python35Packages // { scipy = python35Packages.scipy_0_16;};
  };
});
in pkgs.python35.buildEnv.override{
  extraLibs = [newpkgs.python35Packages.blaze ];
}).env
```
I will add this example to the docs in #13700

**Comment by risicle** [comment]
@FRidh thanks I'll study this.

**Pull request closed without merging**
