### PR TITLE
dmd: 2.078.0 -> 2.078.1

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
Thanks!

**Comment by srhb** [comment]
I notice that the previous version wasn't backported to stable. Do you know if that's intentional, and if not, should be backport this as well?

**Comment by ThomasMader** [comment]
I think that's intentional. New versions aren't merged into stable. At least that's my impression because none of my packages were ever backported AFAIK.
Such a policy would make sense too because major version changes can break things which is not something you want.
For me it's ok if the version is frozen in 17.09 till the next release.

Btw. normally people who merge a PR trigger a Bot Build to check if everything still works. See https://github.com/NixOS/nixpkgs/pull/34326 for example.
Are you missing permissions to do so?

**Comment by srhb** [comment]
Oh, if that's a major version bump there's I agree that we shouldn't backport without reason.

I do have permissions to use ofborg, but I just built this locally. Thanks for the concern anyway! :)

**Pull request merged**
