### PR TITLE
sparrow: 1.7.1 -> 1.7.3

### PR DESCRIPTION
**Pull request by emmanuelrosa**
###### Description of changes

- This PR updates sparrow from 1.7.1 to 1.7.3 and obsoletes PR #216478 which was generated with the auto-update script. See https://github.com/sparrowwallet/sparrow/releases/tag/1.7.3 for the release details.
- sparrow 1.7.3 adds code to dynamically load a library, and said code uses a hard-coded path. Since the package doesn't build from source, I'm using `buildFHSUserEnv` to provide the library at the expected path, which I manually confirmed. But note however that I don't have the hardware to test that particular code path.
- I also incorporated changes in the upstream .desktop file.
- I enabled JavaFX. See #206643
- Sparrow 1.7.3 bundles hwi 2.2.1, which they said was updated to fix some issues with specific hardware wallets. We don't use the bundled version and instead use the one from Nixpkgs. The Nixpkgs version upon which this commit is built contains the expected hwi 2.2.1.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emmanuelrosa** [comment]
A newer version of sparrow has been released (1.7.3). I'm going to update the package so don't merge this yet.

**Comment by emmanuelrosa** [comment]
Now this package is ready for review. I haven't found any issues due to the use of `buildFHSUserEnv.`

**Comment by naturallaw777** [comment]
Thanks so much @emmanuelrosa for the hard work!

**Comment by emmanuelrosa** [comment]
I broke the udev rules when I added `buildFHSUserEnv.` That's now fixed. I also noticed that I was getting the udev rules from an outdated version of HWI. So now the package gets the udev rules from the HWI package passed in as an input.

**Comment by emmanuelrosa** [comment]
Crap! Something went wrong. I'm closing this to try again.

**Pull request closed without merging**
