### PR TITLE
llvm,mlir: Fix the incorrect MLIR_INSTALL_PACKAGE_DIR config

### LINKED ISSUE #291408: llvmPackage_17.mlir: cmake files are broken
### Steps To Reproduce

1. Build a package that depends on mlir via cmake and get the following error:
```console
CMake Error at /nix/store/zjjkxmbpwxh6w8f3gg145k9zg1wvl432-mlir-17.0.6-dev/lib/cmake/mlir/MLIRTargets.cmake:2017 (message):
  The imported target "MLIRPresburger" references the file

     "/nix/store/zjjkxmbpwxh6w8f3gg145k9zg1wvl432-mlir-17.0.6-dev/lib/libMLIRPresburger.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/nix/store/zjjkxmbpwxh6w8f3gg145k9zg1wvl432-mlir-17.0.6-dev/lib/cmake/mlir/MLIRTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /nix/store/zjjkxmbpwxh6w8f3gg145k9zg1wvl432-mlir-17.0.6-dev/lib/cmake/mlir/MLIRConfig.cmake:36 (include)
```

Now it wasn't quite obvious to me at first, but I have a theory what is happening here:
The the package has an `out` and `dev` output, thus the static libraries end up in the `out` output, while the cmake files end up in the `dev` output. I don't really know how output splitting works, but I guess that nix simply replaces all references to the `$out` path, for each output pretending there's only a single such out path, therefore creating a path where the static libraries don't actually exists.

This is further confirmed looking at the store paths of the out output:
- which mlir-tblgen
/nix/store/8qd7dxd0skkf6hqmfhqb5k9r3hgh61mp-mlir-17.0.6/bin/mlir-tblgen
- ls /nix/store/8qd7dxd0skkf6hqmfhqb5k9r3hgh61mp-mlir-17.0.6/lib/libMLIRPresburger.a
/nix/store/8qd7dxd0skkf6hqmfhqb5k9r3hgh61mp-mlir-17.0.6/lib/libMLIRPresburger.a
(out output store path + path from the cmake output above)
- ls /nix/store/8qd7dxd0skkf6hqmfhqb5k9r3hgh61mp-mlir-17.0.6/lib/cmake
ls: cannot access '/nix/store/8qd7dxd0skkf6hqmfhqb5k9r3hgh61mp-mlir-17.0.6/lib/cmake': No such file or directory
(no cmake in the out output store path)
- ls /nix/store/zjjkxmbpwxh6w8f3gg145k9zg1wvl432-mlir-17.0.6-dev/lib/
cmake
(the dev output contains only cmake in the lib directory)

### Additional context

I've built mlir locally with `outputs = ["out"]`, and the error is gone.

### Notify maintainers

@lxsameer @dtzWill @Ericson2314 @lovek323 @alyssais @RaitoBezarius @rrbutani @sternenseemann 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lxsameer**
## Description of changes
This patch will fix https://github.com/NixOS/nixpkgs/issues/291408

## Things done
Just changed the cmake configuration of mlir to fix an incorrect flag.

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
Looks like this can target master?

**Comment by Ericson2314** [comment]
Yes looks good, just should target master

**Comment by Ericson2314** [comment]
oh no, that didn't work

**Comment by lxsameer** [comment]
oh dang it. Sorry everyone :bow:

**Comment by lxsameer** [comment]
@wegank Here you are https://github.com/NixOS/nixpkgs/pull/308016

**Pull request closed without merging**
