### PR TITLE
pythonPackages.optree: init 0.11.0

### LINKED ISSUE #310612: Package request: pythonPackages.optree
**Project description**

Optimized pytree utilities

**Metadata**

* homepage URL: https://github.com/metaopt/optree
* source URL: https://github.com/metaopt/optree
* license: apache-2.0
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Pandapip1**
## Description of changes

Optimized PyTree Utilities

Closes https://github.com/NixOS/nixpkgs/issues/310612

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Pandapip1** [comment]
Result of `nixpkgs-review pr 310624` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.optree</li>
    <li>python311Packages.optree.dist</li>
    <li>python312Packages.optree</li>
    <li>python312Packages.optree.dist</li>
  </ul>
</details>

**Review by ghost — COMMENTED** [review]
Looks good. some minor comments. can use `dontUseCmakeConfigure = true;` and remove the `buildPhase`. should enable tests as well.

<details><summary>suggested-chages.diff</summary>

```diff
diff --git a/pkgs/development/python-modules/optree/default.nix b/pkgs/development/python-modules/optree/default.nix
index 3f4e82d58e95..89bdd31a2b4d 100644
--- a/pkgs/development/python-modules/optree/default.nix
+++ b/pkgs/development/python-modules/optree/default.nix
@@ -7,12 +7,13 @@
 , setuptools
 , typing-extensions
 , pybind11
+, pytestCheckHook
 }:
 
 buildPythonPackage rec {
   pname = "optree";
   version = "0.11.0";
-  format = "pyproject";
+  pyproject = true;
 
   disabled = pythonOlder "3.7";
 
@@ -23,10 +24,7 @@ buildPythonPackage rec {
     hash = "sha256-VnnnEoXkYJO+S7baH+JZvsW18Tk3TiY9+Cd230OlZWo=";
   };
 
-  buildPhase = ''
-    cd ..
-    pypaBuildPhase
-  '';
+  dontUseCmakeConfigure = true;
 
   propagatedBuildInputs = [
     typing-extensions
@@ -39,9 +37,21 @@ buildPythonPackage rec {
   pythonImportsCheck = [
     "optree"
   ];
+  nativeCheckInputs = [
+    pytestCheckHook
+  ];
+  # prevent import failures from pytest
+  preCheck = ''
+    rm -r optree
+  '';
+  disabledTests = [
+    # add reason why test fails
+    "test_treespec_pickle_missing_registration"
+  ];
 
   meta = with lib; {
     homepage = "https://github.com/metaopt/optree";
+    changelog = "https://github.com/metaopt/optree/releases/tag/v${version}";
     description = "Optimized PyTree Utilities";
     maintainers = with maintainers; [ pandapip1 ];
     license = licenses.asl20;
```
</details>

**Comment by Pandapip1** [comment]
Since this is a missing dependency in `keras` that causes an error, I think I'll add the automatic backport label.

**Comment by Pandapip1** [comment]
Result of `nixpkgs-review pr 310624` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.optree</li>
    <li>python311Packages.optree.dist</li>
    <li>python312Packages.optree</li>
    <li>python312Packages.optree.dist</li>
  </ul>
</details>

**Review by ghost — APPROVED** [review]

**Review by nicoonoclaste — APPROVED** [review]

**Pull request merged**
