### PR TITLE
bluez: 5.58 -> 5.59

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
http://www.bluez.org/release-of-bluez-5-59/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]

**Comment by maxeaubrey** [comment]
I don't have an opinion either way, just kinda curious - is there any particular reason why we do not use `--enable-external-ell` for `bluez`, the way we do for `ofono` and `iwd`? All 3 include `ell` in their distribution tarballs (though we do fetch the other two from git), so either possibility seems equally good.

Sorry if this is derailing a bit, genuinely just interested.

**Comment by jtojnar** [comment]
Good eye. Looks like nobody noticed it yet. It would definitely be good to use ell from package if `--enable-external-ell` works and document it if it does not.

**Comment by maxeaubrey** [comment]
6e3c1eb289f12111952505db827f14b8189281da

Builds and works fine with external ell, at a quick glance. I'm not actually sure how to test the mesh feature.

a52b2c7d2b06b82ca8e81e0eaba691e3e741aafc

This commit drops the `--enable-wiimote` flag. Looks like it's been default since 2012 https://github.com/bluez/bluez/commit/ff983074f8970bd60ad003f7f2f270f7aff17d27 :)

**Comment by mweinelt** [comment]
Cherry-picked, thank you!

**Pull request merged**
