### PR TITLE
`nix.gc.automatic`: default to true

### PR DESCRIPTION
**Pull request by asymmetric**
###### Motivation for this change

I assume most users want some kind of GC. Novices are the ones who would have a hard time finding out this setting, and would be surprised with their disk filling up without recourse.

Power users, on the other hand, know where to look in case they want to turn GC off..

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bb2020** [comment]
Storage is cheap these days. This change reminds me the dark ages of Windows when `winsat` kicks in randomly and bogs down the entire system :smiley:

**Comment by asymmetric** [comment]
@bb2020 I agree that storage is cheap, but I see it more as a quality of life improvement, especially for first time users/first installs: if we assume that almost every one will turn this on, then why not turn it on by default?

It's probably impossible to know whether the assumption is factually true, but in my anecdotal experience, guiding a few people through NixOS installs, it is.

**Comment by bb2020** [comment]
I only run GC when the drive is out of space, if ever. I am sure most people do the same. Also, some users mount `/nix` onto a larger and slower external drive. I personally don't like the idea of running background tasks by default (Windows flashbacks).

GC actually shines when you start deleting previous generations. Constantly removing and re-downloading imperative tools is going to put more stress on your computer and `cache.nixos.org` in the long run.

**Comment by SuperSandro2000** [comment]
> I only run GC when the drive is out of space, if ever. I am sure most people do the same.

I have a nightly cron otherwise my disk would be full every day and thing stop working.
Also you do not want to sit looking at the command 20 minutes until it cleared the gigabytes out of the way.

But I am also a special power user.

> Also, some users mount /nix onto a larger and slower external drive.

This change is not targeted at them. We want to help people who run the a close to default installation.

> Constantly removing and re-downloading imperative tools is going to put more stress on your computer 

Building is far more stress.

> cache.nixos.org in the long run.

The bandwidth used is probably a bigger concern than if it stresses amazons servers.

**Comment by bb2020** [comment]
> > Also, some users mount /nix onto a larger and slower external drive.
> 
> This change is not targeted at them. We want to help people who run the a close to default installation.
> 

I mean background GC will slow down their system even more because of external drive being slower.

> The bandwidth used is probably a bigger concern than if it stresses amazons servers.
> 
> The problem is that you don't easily know when gc is running and you might wonder why the system is slow.

Exactly my point :+1:

**Comment by michaelpj** [comment]
Garbage collecting is not totally consequence-free. Anyone who builds things ad-hoc from time to time has been bitten by garbage collection deleting something that they then want to use again. And having it be done automatically means that this will happen unpredictably, which makes it extra annoying. 

Moreover, garbage collection is most useful when it's combined with deleting generations, which the auto GC does not do. A clueless user will barely benefit from this unless they also manually delete generations... at which point they might as well also garbage collect!

> I assume most users want some kind of [automatic] GC.

Is this true? I don't think it obviously is, maybe we should ask people.

**Comment by bb2020** [comment]
> Garbage collecting is not totally consequence-free. Anyone who builds things ad-hoc from time to time has been bitten by garbage collection deleting something that they then want to use again. And having it be done automatically means that this will happen unpredictably, which makes it extra annoying.

Imagine building `gcc` or `chromium` and then it is garbage collected automatically.

**Comment by mohe2015** [comment]
Maybe instead run something like this in a systemd timer?
```sh
#!/bin/sh

avail=$(df --block-size=1G /nix | tail -1 | awk '{print $4}') # GB
if [ "$avail" -lt "1" ]; then
    notid=$(gdbus call --session     --dest=org.freedesktop.Notifications     --object-path=/org/freedesktop/Notifications     --method=org.freedesktop.Notifications.Notify     "NixOS" 0 "nix-snowflake" 'Low on disk space' 'You seem to be low on disk space. NixOS keeps old unused versions of software locally so you may want to delete them. This is called garbage collection. You may also want to delete old versions of you whole system although this prevents you from rolling back.'     '["help","Help","run-gc","Only GC","run-gc-d","Also delete old generations"]' '{"urgency": <0>}' 0 | sed -r 's/\(uint32 ([0-9]*),\)/\1/')
    echo $notid
    gdbus monitor --session --dest=org.freedesktop.Notifications --object-path=/org/freedesktop/Notifications |
    while IFS= read -r line
    do
        echo $line
        if echo $line | egrep --color "/org/freedesktop/Notifications: org.freedesktop.Notifications.NotificationClosed \(uint32 $notid, uint32 [0-9]+\)"; then
            pkill -SIGINT -P $$
            exit 0
        fi
        if echo $line | grep --color "/org/freedesktop/Notifications: org.freedesktop.Notifications.ActionInvoked (uint32 $notid, 'help')"; then
            xdg-open "https://nixos.org/guides/nix-pills/garbage-collector.html"
        fi
        if echo $line | grep --color "/org/freedesktop/Notifications: org.freedesktop.Notifications.ActionInvoked (uint32 $notid, 'run-gc')"; then
            nix-collect-garbage
        fi
        if echo $line | grep --color "/org/freedesktop/Notifications: org.freedesktop.Notifications.ActionInvoked (uint32 $notid, 'run-gc-d')"; then
            nix-collect-garbage -d
        fi
    done
fi
```

**Review by figsoda — CHANGES_REQUESTED** [review]

**Comment by milachew** [comment]
I think the garbage collector itself, as just a service that runs automatically sometime there, **is wrong**.

There is too much built around it because of the structure of NixOS, from the rollback capability to the temporary, possibly large packages that are once there downloaded via nix-shell.

I think it would be much more correct to run the garbage collector according to a certain script. For example:
- rely on the number of days of the working generation
- start collecting garbage when a certain number of generations is reached _(I don't think anyone will object here, but having 20-50 generations to roll back when you hit an unbootable system, for example, hardly solves anything. About 10 is enough)_
- start collecting garbage when it reaches a certain-occupied space and clean up to a certain free space (say, as soon as _0.5_ is occupied by `/nix/store`, start cleaning up to _0.2_).

In any case, automating something like a garbage collector in the most optimal way **will really bring NixOS one step closer to a system that "just works" :)**

**Comment by bb2020** [comment]
I loose my mind when some task starts running at background randomly. On Windows, you just open  task manager to see %80 of the CPU is being consumed by some random task. I can't believe how people accepts this as a norm.

**Comment by SuperSandro2000** [comment]
Closing this because the author went silent for over a year and this needs a more sophisticated solution, maybe something similar to https://github.com/numtide/srvos/blob/main/nixos/roles/nix-remote-builder.nix#L19

**Pull request closed without merging**
