### PR TITLE
lollypop: 0.9.514 -> 0.9.516

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
package bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
doesn't build.

**Comment by worldofpeace** [comment]
Edit: This package recieved an update again today. I changed the pr to apply this.

As for the build failure, it fails when trying to get the translations submodule
```
Submodule 'subprojects/po' (https://gitlab.gnome.org/gnumdk/lollypop-po) registered for path 'subprojects/po'
error: key does not contain a section: .url
```

I don't get this error because I'm not familar with how fetchgit works.
@xeji Any suggestions?

**Comment by worldofpeace** [comment]
Ah I see now that this is because of this https://github.com/NixOS/nixpkgs/pull/42376 right?

**Comment by xeji** [comment]
Probably. The git update was reverted. Let's see if this builds now.
@GrahamcOfBorg build lollypop

**Pull request merged**
