### PR TITLE
firefox, firefox-bin: 58.0.2 -> 59.0, firefos-esr: 52.6.0esr -> 52.7.0esr [Critical security fixes]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Critical security fixes
- Performance improvements
- Other improvements

https://www.mozilla.org/en-US/firefox/59.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2018-06/
https://www.mozilla.org/en-US/firefox/52.7.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2018-07/
https://www.mozilla.org/en-US/firefox/52.7.1/releasenotes/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

The source archive is now distributed at different URL, so I have updated the update script. The script will not work for 58.0.2 -> 59.0 but will work for 59.0 -> next update. The script should still work for ESR versions. To test the script, replace the old URL from `mirror://mozilla/firefox/releases/${version}/source/firefox-${version}.source.tar.xz` to `mirror://mozilla/firefox/releases/58.0.2/source/firefox-58.0.2.source.tar.xz` first.

### CODE REVIEW

**Comment by oxij** [comment]
@GrahamcOfBorg build firefox

**Comment by oxij** [comment]
Can you please rebase onto #37158? Master already had the `nspr` update and I stole the `nss` update into there.

**Comment by taku0** [comment]
Rebased.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build firefox

**Comment by oxij** [comment]
Thanks! Rebuilding here to see what the heck.

**Comment by oxij** [comment]
Hm. @7c6f434c Was the problem with master?

**Comment by 7c6f434c** [comment]
All the problems are timeouts, and I believe @taku0 about building before submitting, so I decided the risk-benefit is acceptable.

**Pull request merged**
