### PR TITLE
z3: 4.6.0 -> 4.7.1

### PR DESCRIPTION
**Pull request by dtzWill**
Update!

Needs testing,
not sure how many rebuilds this'll trigger
or if apps will generally be compat or not.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
```
@GrahamcOfBorg build haskellPackages.sbvPlugin haskellPackages.z3 haskellPackages.copilot-sbv cryptol haskellPackages.ntha solc dotnetPackages.Dafny seth dotnetPackages.Boogie boogie z3 haskellPackages.linearEqSolver souper fstar haskellPackages.cryptol tlaps isabelle haskellPackages.sbv cuter haskellPackages.ez3 dafny altcoins.seth
```

**Comment by Mic92** [comment]
Does not look like it has too many users.

**Comment by Mic92** [comment]
Seems non-critical: https://github.com/Z3Prover/z3/blob/master/RELEASE_NOTES#L3

**Comment by dtzWill** [comment]
I think all the "failures" are due to build timeouts?

**Comment by Mic92** [comment]
@taktoa regarding broken boogie package.

**Comment by xeji** [comment]
boogie was fixed in #41169

**Comment by dtzWill** [comment]
@GrahamcOfBorg build boogie souper isabelle haskellPackages.z3

**Comment by dtzWill** [comment]
@build haskellPackages.z3 haskellPackages.linearEqSolver haskellPackages.sbv haskellPackages.ez3 cryptol

**Comment by dtzWill** [comment]
Whoops re:summoning ofborg.  Anyway, LGTM.

**Pull request merged**
