### PR TITLE
zfs: 0.8.4 -> 0.8.5

### PR DESCRIPTION
**Pull request by hmenke**
###### Motivation for this change

Mostly bugfixes: https://github.com/openzfs/zfs/releases/tag/zfs-0.8.5

Most notably, the `__vmalloc` patch has been merged into mainline and was therefore removed from the Nix expression.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hmenke** [comment]
Result of `nixpkgs-review pr 99965` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>52 packages failed to build:</summary>
  <ul>
    <li>bareos</li>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome3.gnome-boxes</li>
    <li>grub2</li>
    <li>grub2_efi</li>
    <li>grub2_pvgrub_image</li>
    <li>grub2_xen</li>
    <li>libceph</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt_5_9_0</li>
    <li>libvmi</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixops</li>
    <li>nixopsUnstable</li>
    <li>nixops_1_6_1</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>os-prober</li>
    <li>perl530Packages.SysVirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>python27Packages.guestfs</li>
    <li>python27Packages.libvirt</li>
    <li>python37Packages.guestfs</li>
    <li>python37Packages.libvirt</li>
    <li>python38Packages.guestfs</li>
    <li>python38Packages.libvirt</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_2_5.ruby-libvirt</li>
    <li>rubyPackages_2_7.ruby-libvirt</li>
    <li>samba4Full</li>
    <li>sanoid</li>
    <li>terraform-full</li>
    <li>terraform-provider-libvirt (terraform-providers.libvirt)</li>
    <li>terraform_0_11-full</li>
    <li>terragrunt</li>
    <li>vagrant</li>
    <li>virtmanager (virt-manager)</li>
    <li>virtmanager-qt (virt-manager-qt)</li>
    <li>virt-top</li>
    <li>virtviewer (virt-viewer)</li>
    <li>virtlyst</li>
    <li>zfs</li>
    <li>zfstools</li>
  </ul>
</details>
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>linuxPackages-libre.zfs</li>
    <li>linuxPackages.zfs</li>
    <li>linuxPackages_4_14.zfs</li>
    <li>linuxPackages_4_19.zfs</li>
    <li>linuxPackages_4_4.zfs</li>
    <li>linuxPackages_4_9.zfs</li>
    <li>linuxPackages_5_7.zfs</li>
    <li>linuxPackages_5_8.zfs</li>
    <li>linuxPackages_hardened.zfs</li>
    <li>linuxPackages_latest-libre.zfs</li>
    <li>linuxPackages_latest_hardened.zfs</li>
    <li>linuxPackages_latest_xen_dom0.zfs</li>
    <li>linuxPackages_latest_xen_dom0_hardened.zfs</li>
    <li>linuxPackages_testing_bcachefs.zfs</li>
    <li>linuxPackages_xen_dom0.zfs</li>
    <li>linuxPackages_xen_dom0_hardened.zfs</li>
    <li>linuxPackages_zen.zfs</li>
  </ul>
</details>

**Comment by jonringer** [comment]
please address build failure:
```
builder for '/nix/store/r8gv15g1vq50vs5wrwf9npk50gzdmglm-zfs-user-0.8.5.drv' failed with exit code 1; last 10 log lines:
  substituteStream(): WARNING: pattern 'zfs-import-cache.service' doesn't match anything in file '/nix/store/s7f85wblnjx04amif5k0p7083hfb61mx-zfs-user-0.8.5/etc/systemd/system/zfs-zed.service'
  substituteStream(): WARNING: pattern 'zfs-import-cache.service' doesn't match anything in file '/nix/store/s7f85wblnjx04amif5k0p7083hfb61mx-zfs-user-0.8.5/etc/systemd/system/zfs.target'
  install: creating directory '/nix/store/s7f85wblnjx04amif5k0p7083hfb61mx-zfs-user-0.8.5/share/bash-completion'
  install: creating directory '/nix/store/s7f85wblnjx04amif5k0p7083hfb61mx-zfs-user-0.8.5/share/bash-completion/completions'
  'contrib/bash_completion.d/zfs' -> '/nix/store/s7f85wblnjx04amif5k0p7083hfb61mx-zfs-user-0.8.5/share/bash-completion/completions/zfs'
  post-installation fixup
  Moving /nix/store/s7f85wblnjx04amif5k0p7083hfb61mx-zfs-user-0.8.5/lib/pkgconfig to /nix/store/xn0z69cxh4ardyl7zq89gvdsxf6826zh-zfs-user-0.8.5-dev/lib/pkgconfig
  rmdir: failed to remove '/nix/store/s7f85wblnjx04amif5k0p7083hfb61mx-zfs-user-0.8.5/lib': Directory not empty
  Moving /nix/store/gryks8p55h34b6jqighzqh2hjfknhhrd-zfs-user-0.8.5-lib/lib/pkgconfig to /nix/store/xn0z69cxh4ardyl7zq89gvdsxf6826zh-zfs-user-0.8.5-dev/lib/pkgconfig
  mv: cannot overwrite non-directory '/nix/store/xn0z69cxh4ardyl7zq89gvdsxf6826zh-zfs-user-0.8.5-dev/lib/pkgconfig' with directory '/nix/store/gryks8p55h34b6jqighzqh2hjfknhhrd-zfs-user-0.8.5-lib/lib/pkgconfig'
```

**Review by jonringer — CHANGES_REQUESTED** [review]
above

**Comment by hmenke** [comment]
Result of `nixpkgs-review pr 99965` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>bareos</li>
    <li>virtmanager-qt (virt-manager-qt)</li>
  </ul>
</details>
<details>
  <summary>68 packages built:</summary>
  <ul>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome3.gnome-boxes</li>
    <li>grub2</li>
    <li>grub2_efi</li>
    <li>grub2_pvgrub_image</li>
    <li>grub2_xen</li>
    <li>libceph</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt_5_9_0</li>
    <li>libvmi</li>
    <li>linuxPackages-libre.zfs</li>
    <li>linuxPackages.zfs</li>
    <li>linuxPackages_4_14.zfs</li>
    <li>linuxPackages_4_19.zfs</li>
    <li>linuxPackages_4_4.zfs</li>
    <li>linuxPackages_4_9.zfs</li>
    <li>linuxPackages_5_7.zfs</li>
    <li>linuxPackages_5_8.zfs</li>
    <li>linuxPackages_hardened.zfs</li>
    <li>linuxPackages_latest-libre.zfs</li>
    <li>linuxPackages_latest_hardened.zfs</li>
    <li>linuxPackages_latest_xen_dom0.zfs</li>
    <li>linuxPackages_latest_xen_dom0_hardened.zfs</li>
    <li>linuxPackages_testing_bcachefs.zfs</li>
    <li>linuxPackages_xen_dom0.zfs</li>
    <li>linuxPackages_xen_dom0_hardened.zfs</li>
    <li>linuxPackages_zen.zfs</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixops</li>
    <li>nixopsUnstable</li>
    <li>nixops_1_6_1</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>os-prober</li>
    <li>perl530Packages.SysVirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>python27Packages.guestfs</li>
    <li>python27Packages.libvirt</li>
    <li>python37Packages.guestfs</li>
    <li>python37Packages.libvirt</li>
    <li>python38Packages.guestfs</li>
    <li>python38Packages.libvirt</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_2_5.ruby-libvirt</li>
    <li>rubyPackages_2_7.ruby-libvirt</li>
    <li>samba4Full</li>
    <li>sanoid</li>
    <li>terraform-full</li>
    <li>terraform-provider-libvirt (terraform-providers.libvirt)</li>
    <li>terraform_0_11-full</li>
    <li>terragrunt</li>
    <li>vagrant</li>
    <li>virtmanager (virt-manager)</li>
    <li>virt-top</li>
    <li>virtviewer (virt-viewer)</li>
    <li>virtlyst</li>
    <li>zfs</li>
    <li>zfsUnstable</li>
    <li>zfstools</li>
  </ul>
</details>

**Comment by hmenke** [comment]
@ofborg test zfs.stable zfs.unstable

Testing unstable as well, because the change in `postInstall` theoretically affects it as well.

**Comment by hmenke** [comment]
`bareos` could not be built but it's marked as `broken` anyway.

`virtmanager-qt` doesn't build as well, but I doubt that this is due to ZFS.  Here is the log output:
```
builder for '/nix/store/ic3yq25h21k6g8dqjywyshayqj4hrgcl-virt-manager-qt-0.71.95.drv' failed with exit code 2; last 10 log lines:
  [  2%] Building CXX object CMakeFiles/qt5-remote-viewer.dir/src/vm_viewer/main.cpp.o
  In file included from /build/source/src/vm_viewer/krdc_vnc_qtonly/Machine_View.h:28,
                   from /build/source/src/vm_viewer/vnc/vnc_viewer_only.h:5,
                   from /build/source/src/vm_viewer/main.cpp:6:
  /build/source/src/vm_viewer/krdc_vnc_qtonly/vncview.h:64:24: error: 'DotCursorState' has not been declared
     64 |     void showDotCursor(DotCursorState state);
        |                        ^~~~~~~~~~~~~~
  make[2]: *** [CMakeFiles/qt5-remote-viewer.dir/build.make:352: CMakeFiles/qt5-remote-viewer.dir/src/vm_viewer/main.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/qt5-remote-viewer.dir/all] Error 2
  make: *** [Makefile:149: all] Error 2
builder for '/nix/store/dxvp2gg10bvdhcas6c22jvl94ky7pr1f-bareos-17.2.7.drv' failed with exit code 2; last 10 log lines:
    550 |       if (glfs_ftruncate(m_gfd, 0) != 0) {
        |                                  ^
  In file included from ../backends/gfapi_device.h:31,
                   from gfapi_device.c:34:
  /nix/store/7icjj170dwglm9hc6h4j60hflk2vkkwi-glusterfs-7.6/include/glusterfs/api/glfs.h:768:1: note: declared here
    768 | glfs_ftruncate(glfs_fd_t *fd, off_t length, struct glfs_stat *prestat,
        | ^~~~~~~~~~~~~~
  make[1]: *** [Makefile:217: gfapi_device.lo] Error 1
  make[1]: Leaving directory '/build/bareos-17.2.7-src/src/stored/backends'
  make: *** [GNUmakefile:167: src/stored/backends] Error 2
```

**Comment by hmenke** [comment]
@jonringer Could you please take a look again?

**Comment by jonringer** [comment]
@GrahamcOfBorg test zfs

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
builder for '/nix/store/g0pwdpndk41kqmqjwnq1i9df1skib0yb-ceph-15.2.5.drv' failed with exit code 2; last 10 log lines:
  [ 86%] Building C object lib/CMakeFiles/libzstd_static.dir/build/ceph-15.2.5/src/zstd/lib/deprecated/zbuff_decompress.c.o
  [ 89%] Building C object lib/CMakeFiles/libzstd_static.dir/build/ceph-15.2.5/src/zstd/lib/decompress/huf_decompress.c.o
  [ 93%] Building C object lib/CMakeFiles/libzstd_static.dir/build/ceph-15.2.5/src/zstd/lib/compress/zstd_ldm.c.o
  [ 96%] Building C object lib/CMakeFiles/libzstd_static.dir/build/ceph-15.2.5/src/zstd/lib/compress/zstd_lazy.c.o
  [100%] Linking C static library libzstd.a
  [100%] Built target libzstd_static
  [  8%] Performing install step for 'zstd_ext'
  [  8%] Completed 'zstd_ext'
  [  8%] Built target zstd_ext
  make: *** [Makefile:160: all] Error 2
cannot build derivation '/nix/store/qqh7g7yhsp5psm37akxbzkxmb6ck4g5a-ceph-client-15.2.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0x435nwkvjngpz8z2x9vs2yphkw7iwy9-samba-4.12.6.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/q5vi6p1i83md834zrrfidgvq8sw1iv9q-env.drv': 3 dependencies couldn't be built
[28 built (1 failed)]
error: build of '/nix/store/q5vi6p1i83md834zrrfidgvq8sw1iv9q-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/99965
7 packages marked as broken and skipped:
bareos linuxPackages_5_7.zfs linuxPackages_5_7.zfsStable linuxPackages_hardkernel_4_14.zfs linuxPackages_hardkernel_4_14.zfsStable linuxPackages_hardkernel_latest.zfs linuxPackages_hardkernel_latest.zfsStable

1 package blacklisted:
tests.nixos-functions.nixosTest-test

4 packages failed to build:
ceph ceph-client libceph sambaFull

66 packages built:
collectd collectd-data docker-machine-kvm docker-machine-kvm2 easysnap gnome3.gnome-boxes grub2 grub2_efi grub2_pvgrub_image grub2_xen haskellPackages.libvirt-hs haskellPackages.libzfs libguestfs libguestfs-with-appliance libvirt libvirt-glib libvirt_5_9_0 libvmi linuxPackages-libre.zfs linuxPackages.zfs linuxPackages_4_14.zfs linuxPackages_4_19.zfs linuxPackages_4_4.zfs linuxPackages_4_9.zfs linuxPackages_5_8.zfs linuxPackages_hardened.zfs linuxPackages_latest-libre.zfs linuxPackages_latest.zfs linuxPackages_latest_hardened.zfs linuxPackages_latest_xen_dom0.zfs linuxPackages_latest_xen_dom0_hardened.zfs linuxPackages_testing_bcachefs.zfs linuxPackages_xen_dom0.zfs linuxPackages_xen_dom0_hardened.zfs linuxPackages_zen.zfs minikube minishift nixops nixopsUnstable nixops_1_6_1 os-prober perl530Packages.SysVirt perl532Packages.SysVirt python27Packages.guestfs python27Packages.libvirt python37Packages.guestfs python37Packages.libvirt python38Packages.guestfs python38Packages.libvirt rubyPackages.ruby-libvirt rubyPackages_2_5.ruby-libvirt rubyPackages_2_7.ruby-libvirt sanoid terraform-full terraform-providers.libvirt terraform_0_11-full terragrunt vagrant virt-manager virt-manager-qt virt-top virt-viewer virtlyst zfs zfsUnstable zfstools
```

**Comment by priegger** [comment]
Since linuxPackages_latest is 5.9 now on 20.09, zfs is marked as broken:
`error: Package ‘zfs-kernel-0.8.4-5.9.11’ in /nix/store/lf9697rp18zdqb7hfcg3f1a0bi6ljr03-nixos-20.09.2076.ffb3aab257e/nixos/pkgs/os-specific/linux/zfs/default.nix:179 is marked as broken, refusing to evaluate.`

Should this be backported?

**Pull request merged**
