### PR TITLE
rPackages: package updates

### PR DESCRIPTION
**Pull request by jbedo**
Last package set bump before transitioning to R 4.1.2.

﻿- rPackages: update CRAN and BIOC package sets
- fix httpgd cairo dependency missing
- rPackages: fix packages requiring home during build
- rPackages: fix compression library dependencies
- rPackages.BayesXsrc: fix build
- rPackages.RoBMA: fix missing dependency
- rPackages: fix builds requiring home
- rPackages: fix builds requiring gsl

### CODE REVIEW

**Comment by jbedo** [comment]
No, it's a staging branch which hydra builds:

https://hydra.nixos.org/jobset/nixpkgs/r-updates

Working on the next R 4.1.1 -> 4.1.2 now so will be a big change
as BioC will also change revision.

**Comment by SuperSandro2000** [comment]
Then the branch should be protected.

**Comment by jbedo** [comment]
Absolutely, who to ping for that? @domenkozar ?

**Comment by domenkozar** [comment]
done!

**Pull request merged**
