### PR TITLE
chromium: Fix the chromedriver version

### PR DESCRIPTION
**Pull request by primeos**
Chromium was updated to M116 but the ChromeDriver version wasn't.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
@networkException thanks for the Chromium updates! :) I noticed that ChromeDriver didn't get updated though - did you maybe manually create the commits and forgot to include this part/hunk (because https://github.com/NixOS/nixpkgs/pull/247128 is working fine for me)?

**Comment by networkException** [comment]
I felt unsure about also bumping chromedriver since it isn't compiled from source like chromium and since there don't appear to be tests for it (I might have missed something)

**Comment by primeos** [comment]
Ok, for the future: Feel free to ask such questions then ;)
(I'll try to answer any questions although, unfortunately, I've became quite unresponsive as I currently lack time/priority for Nixpkgs (hopefully it'll get better at some point) - sorry about that btw - I noticed your PRs and really like/appreciate them but didn't get around to reviewing and merging them (I guess I should've at least wrote brief comments as I did at least glance over them); the quick backstory: I never intended to maintain Chromium but had to take over as we needed a new maintainer and I got too impatient waiting for security updates. I'd say it worked out pretty good for years but I lack the time to maintain it properly since I finished studying and I'm trying to reduce my involvement for a while now (https://github.com/NixOS/nixpkgs/issues/197609))

Anyway, AFAIK we do indeed lack ChromeDriver tests in Nixpkgs. I never ran any manual tests and that should be fine (not ideal but if it becomes an issue then some users should step up and write tests and/or become ChromeDriver maintainers). I'm not sure if updating it caused any issues since I've handled them but not updating it does cause issues as the ChromeDriver version must match the Chromium version. So please just include it in the commit next time.

**Comment by networkException** [comment]
> Ok, for the future: Feel free to ask such questions then ;)

Will do!

> I noticed your PRs and really like/appreciate them but didn't get around to reviewing and merging them

I mean thats totally fine, I feel somewhat comfortable bumping the stable / ungoogled channel for the usual security updates at this point. That said I'm definitely not quite as knowledgeable about the nixpkgs setup yet and would probably need help in more complicated scenarios.

> I never intended to maintain Chromium but had to take over as we needed a new maintainer and I got too impatient waiting for security updates

Well I honestly never quite intended to maintain ungoogled-chromium either, I just wanted updates for my Arch install back then :^)

> I lack the time to maintain it properly since I finished studying and I'm trying to reduce my involvement for a while now

Very understandable, just maintaining ungoogled-chromium itself is pretty demanding (sifting through hundreds of mails after a few days of inactivity). I think I found my corner with chromium maintenance here though and I will (at least) try to limit myself to chromium and chromium related packages to keep the workload somewhat sane.

As said in the beginning I will definitely keep the packages up to date and in the longer term also look into improving tooling, tests, etc.

**Pull request merged**
