### PR TITLE
osu-lazer{,-bin}: 2022.1228.0 -> 2023.207.0

### PR DESCRIPTION
**Pull request by delan**
###### Description of changes

This patch updates osu-lazer and osu-lazer-bin from 2022.1228.0 to 2023.207.0. I’ve tested both on NixOS 22.05 (still no time to upgrade sorry) with the following additional patch:

```diff
diff --git a/pkgs/games/osu-lazer/default.nix b/pkgs/games/osu-lazer/default.nix
index 3a56c35fe88..ff37f988ccf 100644
--- a/pkgs/games/osu-lazer/default.nix
+++ b/pkgs/games/osu-lazer/default.nix
@@ -29,6 +29,10 @@ buildDotnetModule rec {
   projectFile = "osu.Desktop/osu.Desktop.csproj";
   nugetDeps = ./deps.nix;
 
+  # TODO remove in NixOS 22.11
+  dotnet-sdk = dotnetCorePackages.sdk_6_0;
+  dotnet-runtime = dotnetCorePackages.runtime_6_0;
+
   nativeBuildInputs = [ copyDesktopItems ];
 
   runtimeDeps = [
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] ~~For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))~~
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 216575` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>osu-lazer</li>
    <li>osu-lazer-bin</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
I would prefer two separate commits here to trigger the OfBorg CI properly, but this is fine too.

**Comment by delan** [comment]
@thiagokokada ahh i wasn’t aware it affected that, next time i will separate the commits :)

**Comment by thiagokokada** [comment]
@delan The reason this happens is because what triggers OfBorg to build a derivation in a PR is the name of the commits. So if you have 2 commits, one named `osu-lazer: 2022.1228.0 -> 2023.207.0` and another one named `osu-lazer-bin: 2022.1228.0 -> 2023.207.0`, OfBorg will parse the commit messages and triggers a build for both `osu-lazer` and `osu-lazer-bin`. 

This does not work if you name the commit as `osu-lazer{,-bin}: 2022.1228.0 -> 2023.207.0`, because OfBorg does not understand glob (maybe it should!).

Of course, in this case you can always trigger OfBorg manually and this works too. For example (quoting @ just to not trigger it):

`@`ofborg build osu-lazer osu-lazer-bin

**Comment by delan** [comment]
@thiagokokada thank you for the thorough explanation!

**Pull request merged**
