### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change
https://hydra.nixos.org/jobset/nixpkgs/staging-next#tabs-evaluations

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Since 59281f742a0ce8def71be3576129b4178ec579bb `libusb-compat` (`libusb` attribute) no longer propagates `libusb1`, which breaks some packages that use incorrect one.

**Comment by hedning** [comment]
Update to `neon-0.31.0` breaks `gst-plugins-bad`, no patch upstream for the issue as far as I can see. Patching the meson files to accept `0.31.0` seems to work though, neon says the library is backwards compatible from 0.27.x to 0.31.x, so I'm guessing that should work.

**Comment by worldofpeace** [comment]
@hedning https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1165
Commit will be pushed shortly.

**Comment by worldofpeace** [comment]
gobject-introspection on darwin is failing at checks
```
The output from the failed tests:

60/60 gitypelibtest                           FAIL     0.08 s (killed by signal 5 SIGTRAP)

--- command ---
09:28:43 GI_TYPELIB_PATH='/private/tmp/nix-build-gobject-introspection-1.64.0.drv-0/gobject-introspection-1.64.0/build/gir:/private/tmp/nix-build-gobject-introspection-1.64.0.drv-0/gobject-introspection-1.64.0/build/tests:/private/tmp/nix-build-gobject-introspection-1.64.0.drv-0/gobject-introspection-1.64.0/build/tests/scanner' LD_LIBRARY_PATH='/private/tmp/nix-build-gobject-introspection-1.64.0.drv-0/gobject-introspection-1.64.0/build/tests/scanner' /private/tmp/nix-build-gobject-introspection-1.64.0.drv-0/gobject-introspection-1.64.0/build/tests/repository/gitypelibtest
--- stderr ---

** (process:44393): WARNING **: 09:28:43.718: Failed to load shared library '/nix/store/xrafc1lfp5xd3mn19bp08p71f50xnysw-gobject-introspection-1.64.0/lib/libregress-1.0.dylib' referenced by the typelib: dlopen(/nix/store/xrafc1lfp5xd3mn19bp08p71f50xnysw-gobject-introspection-1.64.0/lib/libregress-1.0.dylib, 9): image not found
-------
```

**Comment by jtojnar** [comment]
Re `gobject-introspection`, we need to tweak the `preBuild` hook to symlink `.${stdenv.targetPlatform.extensions.sharedLibrary}`, not `.so`.

That reminds me, `libregress-1.0.so` is not actually cleaned from the `$out`. Likely because `preInstallPhases` has been already added to `phases` before any phase is run. We need to choose a different hack.

**Pull request merged**
