### PR TITLE
timetrap: add shell completions

### PR DESCRIPTION
**Pull request by jerith666**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by nicknovitski — APPROVED** [review]

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 252783` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.prl-tools</li>
    <li>linuxPackages_hardkernel_latest.prl-tools</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_latest.prl-tools (linuxKernel.packages.linux_6_5.prl-tools)</li>
    <li>linuxPackages_latest-libre.prl-tools (linuxKernel.packages.linux_latest_libre.prl-tools)</li>
    <li>linuxPackages_testing_bcachefs.prl-tools (linuxKernel.packages.linux_testing_bcachefs.prl-tools)</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.prl-tools</li>
    <li>linuxPackages_4_14_hardened.prl-tools (linuxKernel.packages.linux_4_14_hardened.prl-tools)</li>
    <li>linuxKernel.packages.linux_4_19.prl-tools</li>
    <li>linuxPackages_4_19_hardened.prl-tools (linuxKernel.packages.linux_4_19_hardened.prl-tools)</li>
    <li>linuxKernel.packages.linux_5_10.prl-tools</li>
    <li>linuxPackages_5_10_hardened.prl-tools (linuxKernel.packages.linux_5_10_hardened.prl-tools)</li>
    <li>linuxKernel.packages.linux_5_15.prl-tools</li>
    <li>linuxPackages_5_15_hardened.prl-tools (linuxKernel.packages.linux_5_15_hardened.prl-tools)</li>
    <li>linuxKernel.packages.linux_5_4.prl-tools</li>
    <li>linuxPackages_5_4_hardened.prl-tools (linuxKernel.packages.linux_5_4_hardened.prl-tools)</li>
    <li>linuxPackages.prl-tools (linuxKernel.packages.linux_6_1.prl-tools)</li>
    <li>linuxPackages_hardened.prl-tools (linuxPackages_6_1_hardened.prl-tools)</li>
    <li>linuxKernel.packages.linux_6_4.prl-tools</li>
    <li>linuxPackages_6_4_hardened.prl-tools (linuxKernel.packages.linux_6_4_hardened.prl-tools)</li>
    <li>linuxPackages-libre.prl-tools (linuxKernel.packages.linux_libre.prl-tools)</li>
    <li>linuxPackages_lqx.prl-tools (linuxKernel.packages.linux_lqx.prl-tools)</li>
    <li>linuxPackages_xanmod.prl-tools (linuxKernel.packages.linux_xanmod.prl-tools)</li>
    <li>linuxPackages_xanmod_latest.prl-tools (linuxKernel.packages.linux_xanmod_latest.prl-tools ,linuxPackages_xanmod_stable.prl-tools)</li>
    <li>linuxPackages_zen.prl-tools (linuxKernel.packages.linux_zen.prl-tools)</li>
    <li>timetrap</li>
  </ul>
</details>

**Comment by gepbird** [comment]
> Any idea why `nixpkgs-review pr` thinks it has to build all that `linux*` stuff?

Timetrap is a dependency of [prl-tools](https://github.com/nixos/nixpkgs/blob/master/pkgs/os-specific/linux/prl-tools/default.nix#L33) which is inside the linux directory. Not sure why are there so many rebuilds though

**Comment by jerith666** [comment]
CCing maintainers of `prl-tools`: @catap @wegank.

This dependency was added in f41fc22 (#179582), but it seems pretty implausible to me.  I did:

`nix-build -A pkgs.linuxKernel.packageAliases.linux_default.prl-tools`

and then neither `grep -r timetrap result/` nor `grep -rE 't($|[^a-z])' result/` turns up anything that looks like an actual attempt to execute the `timetrap` or `t` commands provided by the `timetrap` package.

**Comment by catap** [comment]
@jerith666 the issue that prl-tools is provided as binary files which has hardcoded shell scripts. I did my best to reverse enginere it and to find some setup which works...

So, if you may avoid to touch it, I'll be very appricieted :) it was quite a challenge last time, and you may see that before I did it nix has lack of updated for years.

**Comment by jerith666** [comment]
> @jerith666 the issue that prl-tools is provided as binary files which has hardcoded shell scripts. I did my best to reverse enginere it and to find some setup which works...
> 
> So, if you may avoid to touch it, I'll be very appricieted :) it was quite a challenge last time, and you may see that before I did it nix has lack of updated for years.

I can certainly appreciate that.  And I'm unable to test locally as I don't have a Parallels license or any Mac hardware.

I'm just not sure what Parallels Tools for Linux guests could possibly want with this obscure ruby time tracker!  :)

Ideally we would sever this dependency:

```diff
diff --git a/pkgs/os-specific/linux/prl-tools/default.nix b/pkgs/os-specific/linux/prl-tools/default.nix
index 7e5fca7a354b..b1dd9025a9c2 100644
--- a/pkgs/os-specific/linux/prl-tools/default.nix
+++ b/pkgs/os-specific/linux/prl-tools/default.nix
@@ -16,7 +16,6 @@
 , cups
 , gawk
 , netcat
-, timetrap
 , util-linux
 }:
 
@@ -30,7 +29,6 @@ let
     "${cups}/sbin"
     "${gawk}/bin"
     "${netcat}/bin"
-    "${timetrap}/bin"
     "${util-linux}/bin"
   ];
 in
```

At any rate, I can report that `linuxPackages_latest.prl-tools` and `linuxPackages_latest-libre.prl-tools` build cleanly for me at the tip of this PR's branch, while `linuxPackages_testing_bcachefs.prl-tools` fails in the same way at the tip of this PR's branch and its parent.  So I don't think anything that's happening here is making the situation any better or worse.

**Pull request merged**
