### PR TITLE
PULL_REQUEST_TEMPLATE: Add "Notify maintainers" section

### PR DESCRIPTION
**Pull request by steshaw**
###### Motivation for this change

I thought this would be a helpful reminder.

###### Things done

These items do not apply.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

Unsure

### CODE REVIEW

**Comment by steshaw** [comment]
@worldofpeace, I'm not sure who are the maintainers of PULL_REQUEST_TEMPLATE. Sorry to bug you but could you help out? :pray:

**Comment by worldofpeace** [comment]
> I'm not sure who are the maintainers of PULL_REQUEST_TEMPLATE. Sorry to bug you but could you help out?

Typically anyone who uses the `PULL_REQUEST_TEMPLATE` chimes in on a change like this.

(last time that did include me #58098)

---

There's currently so many ways to notify people, i.e `maintainers` in meta get automatically pinged by `ofborg` but I typically do this exact thing like

```
blah blah beginning of pr template

---

cc @someone 
```

so I don't see a reason why not to encourage people to actively find people to look after their change in this sense.

**Comment by steshaw** [comment]
Thanks. I didn't realise that maintainers are automatically notified by the `ofborg` bot. There's [a reference in the nixpkgs manual to explicitly notify maintainers](https://nixos.org/nixpkgs/manual/#submitting-changes-submitting-changes). This may have been before `ofborg` was in action.

No one is listed in `CODEOWNERS` for `PULL_REQUEST_TEMPLATE` or `.github`.

I wonder if the manual should be updated instead.

**Comment by worldofpeace** [comment]
I think it would be a good idea for someone to be listed in `CODEOWNERS` for those files.

And the manual is in fact correct in this matter, people should always notify someone of their changes.

**Comment by worldofpeace** [comment]
Added some people who should be able to give you some feedback.

**Review by infinisil — APPROVED** [review]
LGTM

**Pull request merged**
