### PR TITLE
Tahoe service

### LINKED ISSUE #25273: Tahoe-LAFS service module is broken
## Issue description
In the generated  pre-start script for introducers, the command 
```
tahoe create-introducer /var/db/tahoe-lafs/<foo>
```
is executed. However, doing this manually returns:

```
tahoe create-introducer /var/db/tahoe-lafs/a
Usage:  tahoe [global-options] create-introducer [options] NODEDIR
(use 'tahoe --help' to view global options)

Options:
      --hide-ip            prohibit any configuration that would reveal the
                           node's IP address
      --tor-launch         Launch a tor instead of connecting to a tor control
                           port.
      --i2p-launch         (future) Launch an I2P router instead of connecting
                           to a SAM API port.
  -C, --basedir=           Specify which Tahoe base directory should be used.
      --location=          Server location to advertise (e.g.
                           tcp:example.org:12345)
      --port=              Server endpoint to listen on (e.g. tcp:12345, or
                           tcp:12345:interface=127.0.0.1.
      --hostname=          Hostname to automatically set --location/--port when
                           --listen=tcp
      --listen=            Comma-separated list of listener types
                           (tcp,tor,i2p,none). [default: tcp]
      --tor-control-port=  Tor's control port endpoint descriptor string (e.g.
                           tcp:127.0.0.1:9051 or unix:/var/run/tor/control)
      --tor-executable=    The 'tor' executable to run (default is to search
                           $PATH).
      --i2p-sam-port=      I2P's SAM API port endpoint descriptor string (e.g.
                           tcp:127.0.0.1:7656)
      --i2p-executable=    (future) The 'i2prouter' executable to run (default
                           is to search $PATH).
      --version            
      --help               Display this help and exit.

Create a Tahoe-LAFS introducer.

/nix/store/d1i72m7mj3cbs0p0lawfalkfvzp29dxr-tahoe-lafs-1.12.1/bin/tahoe:  --listen=tcp requires --hostname=
```

As the error specifies, apparently --listen=tcp implies that one needs to specify `--hostname` with some valid value.

## Technical details

* System: 17.03.git.aa03833 (Gorilla)

### PR DESCRIPTION
**Pull request by MostAwesomeDude**
###### Motivation for this change

Fix #25273 and update the NixOS service for the Tahoe 1.13 CLI changes.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I have *not* dogfooded these changes, in contrast to my usual Tahoe adventures. I would greatly appreciate independent confirmation that this works for folks.

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
Looks good to me. Since some time has passed, I'll wait for your OK before merging.

**Review by rycee — APPROVED** [review]
I've been using these changes for a while now on 19.03 and they work well. As far as I can tell the module is useless without these changes so I would suggest a merge and a backport to 19.03.

**Comment by Infinisil** [comment]
Backported in 41c8f218b8bbb82c8b43ea0e9eddc477dba3f70d

**Comment by rycee** [comment]
Thanks a lot!

**Pull request merged**
