### PR TITLE
networkmanager 1.0.0 -> 1.0.2

### PR DESCRIPTION
**Pull request by DamienCassou**
@lethalman @vcunat

### CODE REVIEW

**Comment by vcunat** [comment]
So the libsoup dependency is (also) for another reason than to fix that missing include? (There are better ways to to fix the include problem.)

**Comment by lethalman** [comment]
@vcunat it's used for checking the connectivity, other distros have libsoup dep so why not us.

**Comment by vcunat** [comment]
OK, it's mainly the text in change 39b09e34be0 that made me unsure about the motivation.

**Comment by DamienCassou** [comment]
Fixes #7912

**Pull request merged**
