### PR TITLE
beam-packages: default erlangR20 -> erlangR22

### PR DESCRIPTION
**Pull request by yorickvP**
###### Motivation for this change

Last time: https://github.com/NixOS/nixpkgs/pull/44640
This has worked for us since february, it's time to upstream it. R22 was released in the meantime.

cc: @LnL7 @ankhers 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yorickvP** [comment]
Actually, R22 shouldn't break too much.

**Comment by ankhers** [comment]
I am all for this.

We should probably come up with some way to update the major version of Erlang sooner. I cannot seem to find a link at the moment, but I think the last time someone suggested updating Erlang it was somewhat shot down because we were unsure of the total changes it would have to the entire ecosystem.

**Comment by yorickvP** [comment]
@GrahamcOfBorg build cuter rabbitmq-server ejabberd couchdb2 tsung hex2nix

**Comment by yorickvP** [comment]
couchdb got fixed in https://github.com/apache/couchdb/commit/9d143bae29782e8983723ed91a66bcfd9db137d7

**Comment by yorickvP** [comment]
hex2nix fix: https://github.com/erlang-nix/hex2nix/pull/27

**Comment by yorickvP** [comment]
@GrahamcOfBorg build relxExe couchdb2

**Comment by yorickvP** [comment]
@GrahamcOfBorg build hex2nix

**Comment by yorickvP** [comment]
This is done, as far as I can tell :)

**Comment by LnL7** [comment]
I'm not super familiar with the erlang ecosystem, but for most languages we don't upgrade the default version immediately. Following n-1 might be a good rule of thumb, but I'm not aware of any particular reason not to go a bit faster.

**Pull request merged**
