### PR TITLE
python3Packages.rich: 12.4.4 -> 12.5.1

### PR DESCRIPTION
**Pull request by jyooru**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`) (rich-cli)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jyooru** [comment]
forgot staging

**Comment by risicle** [comment]
On macos 10.15, this seems to break `enrich`:

```
============================= test session starts ==============================
platform darwin -- Python 3.9.13, pytest-7.1.1, pluggy-1.0.0
rootdir: /private/tmp/nix-build-python3.9-enrich-1.2.7.drv-0/enrich-1.2.7, configfile: setup.cfg, testpaths: src
plugins: mock-3.8.1
collected 9 items                                                              

src/enrich/test/test_console.py F.......                                 [ 88%]
src/enrich/test/test_logging.py .                                        [100%]

=================================== FAILURES ===================================
_____________________________ test_rich_console_ex _____________________________

    def test_rich_console_ex() -> None:
        """Validate that ConsoleEx can capture output from print() calls."""
        console = Console(record=True, redirect=True)
        console.print("alpha")
        print("beta")
        sys.stdout.write("gamma\n")
        sys.stderr.write("delta\n")
        # While not supposed to happen we want to be sure that this will not raise
        # an exception. Some libraries may still sometimes send bytes to the
        # streams, notable example being click.
        # sys.stdout.write(b"epsilon\n")  # type: ignore
        text = console.export_text()
>       assert text == "alpha\nbeta\ngamma\ndelta\n"
E       AssertionError: assert 'alpha\nbeta\...elta\ndelta\n' == 'alpha\nbeta\ngamma\ndelta\n'
E           alpha
E           beta
E         + beta
E         + gamma
E           gamma
E           delta
E         + delta

src/enrich/test/test_console.py:23: AssertionError
----------------------------- Captured stdout call -----------------------------
alpha
beta
gamma
delta
============================= slowest 10 durations =============================

(10 durations < 3s hidden.  Use -vv to show these durations.)
=========================== short test summary info ============================
FAILED src/enrich/test/test_console.py::test_rich_console_ex - AssertionError...
========================= 1 failed, 8 passed in 0.23s ==========================
```

**Comment by SuperSandro2000** [comment]
Did the same update in python-updates run and disabled the one test on darwin.

Do you still want to be added as maintainer? if so I can cherry-pick that part over.

**Comment by jyooru** [comment]
Yes please, so I can make sure textual and rich-cli don't break with rich updates.

**Pull request closed without merging**
