### PR TITLE
nixos system-activation: support activation scripts run in a user context

### LINKED ISSUE #47577: Boot hangs with encrypted home and plasma
## Issue description

Regression introduced by #42910.

If plasma is in use and the user's home directory is on an encrypted LV, the activation script will try to access /home/$USER which is not available and will hang waiting for the user to hit esc:

```
Sep 28 15:31:26 mildred stage-2-init: running activation script...
Sep 28 15:31:26 mildred stage-2-init: setting up /etc...
Sep 28 15:31:26 mildred stage-2-init: reenter password for pam_mount:
Sep 28 15:31:26 mildred stage-2-init: (mount.c:68): Messages from underlying mount program:
Sep 28 15:31:26 mildred stage-2-init: (mount.c:72): mount: /home/peter: unknown filesystem type 'crypto_LUKS'.
Sep 28 15:31:26 mildred stage-2-init: (pam_mount.c:522): mount of /dev/mapper/vg0-lv_home_peter failed
Sep 28 15:31:26 mildred stage-2-init: Cannot execute /run/current-system/sw/bin/zsh
Sep 28 15:31:26 mildred stage-2-init: (mount.c:68): umount messages:
Sep 28 15:31:26 mildred stage-2-init: (mount.c:72): umount: /home/peter: not mounted.
Sep 28 15:31:26 mildred stage-2-init: (mount.c:888): unmount of /dev/mapper/vg0-lv_home_peter failed
Sep 28 15:31:26 mildred stage-2-init: Cannot execute /run/current-system/sw/bin/zsh
Sep 28 15:31:26 mildred stage-2-init: Activation script snippet 'plasmaSetup' failed (127)
```

Cc: @bkchr 

I consider this a blocker for 18.09 as with plymouth enabled, there is no indication that the boot isn't progressing.

### Steps to reproduce

1. Configure LUKS for user: ```users.users.peter.cryptHomeLuks = "/dev/mapper/vg0-lv_home_peter";```
2. Use plasma:   ```xserver.desktopManager.plasma5.enable = true;```
3. Reboot

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.10, NixOS, 19.03.git.e3a7474c3beM (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.2`
 - channels(root): `"nixos-18.03pre121670.4cbbecc85db"`

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Some ```system.activationScripts``` are user specific but are run by root using ```su```. That causes a number of problems:

 - if $HOME is on a dm-crypt volume, ```stage-2-init``` will try to activate the volume (and fail) during boot causing a hang until the user hits escape which isn't obvious if plymouth and KDE is enabled
 - it only works with users defined declaratively and not for those from other sources (LDAP, NIS, local)
 - the script will run for each user even if they are not logged in
 
There is now ```system.userActivationScripts``` which will be run by a systemd user service when ```$XDG_RUNTIME_DIR/.nixos-activate``` is changed.

We could easily use a different activation mechanism but the file based option chosen here is very straight forward.

I have tried it out here and tested as follows:

1. rebooted with this PR applied
2. there was no hang during boot and no ```stage-2-init``` errors
3. added ```ktorrent``` to ```environment.systemPackages```
4. ran ```nixos-rebuild switch```
5. verified that the user service ```nixos-active.service``` ran and as a consequence ```kbuildsycoca5``` as well
6. verified that ```ktorrent``` is now available in the menu

I haven't gone through all the various activation scripts but there are likely more that should be moved to ```system.userActivationScripts```.

Fixes #47577. Supersedes #45290

Cc: @vcunat @samueldr 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
Cc @bkchr @jerith666 @worldofpeace

**Comment by peterhoeg** [comment]
@GrahamcOfBorg test plasma5

**Comment by bkchr** [comment]
Should we add a test for this?

**Comment by peterhoeg** [comment]
> Should we add a test for this?

We definitely should - any good ideas?

**Comment by teto** [comment]
This might be useful for things like home-manager/nixup !

**Comment by bkchr** [comment]
Can we maybe encrypt the home directory and enable auto login?

**Comment by samueldr** [comment]
Hmmm, it works, but it looks like the activation scripts are always "one behind" here. (In addition to needing to at least `systemctl --user restart nixos-activation.path`, not sure if the `systemctl --user daemon-reload` was necessary too.)

Here's my test setup:

On top of 7f70ebf30b8ff3cb10edd593c4549700b34bcc10, applied the user-activation commit (e0e8874a8d0a55588d509641cf01c3c3d86ada65).

My configuration is as such:

```nix
{
  system.userActivationScripts.annoy = ''
    ${pkgs.libnotify}/bin/notify-send -a nixos -t 5000 -u critical "AAA"
  '';
}
```

Before doing `time sudo nixos-rebuild test`, I change the message to something (BBB, CCC, DDD...) when `test` finishes activating, I always see the previously expected message (so with the system having `BBB`, I see `AAA`).

I'm rebuilding without the patch, rebooting and checking what it takes so it works at the first `switch` adding that activation service.

**Comment by samueldr** [comment]
After a reboot, the service doesn't need any kind of massaging, but still seems to lag behind one generation.

**Comment by peterhoeg** [comment]
Yeah, probably because ```systemctl --user daemon-reload``` hasn't run yet. A slight variation of this, is instead of touching the file, that we simply activate ```nixos-activation.service``` in ```switch-to-configuration.pl``` after running daemon-reload.

**Comment by peterhoeg** [comment]
I just pushed some untested commits (I'll try them out now) that uses ```switch-to-configuration.pl``` instead.

**Comment by samueldr** [comment]
Quick update, before more in-depth testing it doesn't lag anymore!

Now testing a fresh boot without the change, if the the first switch works.

**Comment by peterhoeg** [comment]
So this is good to go despite the lack of tests? We really should have some (although I think the encryptfs test isn't relevant in this case) but it's of course your call if it's more important to ship 18.09 assuming this is the last pending blocker.

**Comment by samueldr** [comment]
I would prefer having tests for the feature; though I don't know how the testing infrastructure can be used to make this work since it seems to need a user session to be active (though I'm sure there's already good material in there).

Do you have any idea on how to proceed with a test and the time to implement it at short notice? (DO NOT feel pressured!) Otherwise I feel like I have tested it right, and with the latest changes seems solid. With another pair of eyes looking at it and testing it I would be okay to merge without tests, hoping to later see tests pop into existence. (Which I would gladly adopt into backporting.)

**Comment by peterhoeg** [comment]
> Do you have any idea on how to proceed with a test and the time to implement it at short notice? (DO NOT feel pressured!)

One way to do it would be to have the plasma test see if the ```.cache/ksycoca5_bla_bla_bla``` file is created but I will need to look at this later. Will a promise to implement that soonish be enough?

**Review by samueldr — APPROVED** [review]
Approving after successful manual testing.

Code is minimal and looks fine to me.

**Comment by chkno** [comment]
Tests popping into existence: https://github.com/NixOS/nixpkgs/pull/113241

**Pull request merged**
