### PR TITLE
[20.03] Gnome 3.34 updates

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
I have:
* ran `update.nix`
* excluded updates that didn't make sense
* did one's outside the version bound that did make sense (folks for example)
* did backports from master where possible

I haven't built anything, not sure if I should split this into a `staging-20.03` PR and a `release-20.03` PR.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
I actually think it would be best to target `staging-20.03` so we can run an eval, and in the small chance something does break, we'll see it.

**Comment by worldofpeace** [comment]
I've built select packages to find out what didn't work. Will build more today.

**Comment by vcunat** [comment]
Thank you for your contributions.
This has been automatically marked as stale... I mean, what's up with this?  I agree that minor number bumps generally can be pushed to stable releases, so the problem here is _only_ that noone here has tested these particular versions yet?

**Comment by worldofpeace** [comment]
@vcunat Thanks for checking in, yeah, I think I opened this PR as probably right before my vacation
so I couldn't test it myself. And I believe it was a bit too much for @jtojnar to test since he doesn't use the stable releases.
If we can get it in staging and I can try it out, it should be fine :crossed_fingers: Not sure if more minor updates have been made, though, making this stale.

**Comment by jtojnar** [comment]
Yeah, there has been [3.34.6](https://mail.gnome.org/archives/gnome-announce-list/2020-April/msg00010.html) and [3.34.7](https://mail.gnome.org/archives/gnome-announce-list/2020-June/msg00007.html) in the meanwhile.

**Comment by worldofpeace** [comment]
we're doing https://github.com/NixOS/nixpkgs/pull/93114 now

**Pull request closed without merging**
