### PR TITLE
google-chrome, treewide: fix patchelf usages to not crash constantly, patchelf as native

### PR DESCRIPTION
**Pull request by dtzWill**
Tired of seeing build logs telling me patchelf segfaults 20 times or
unfriendly assertion failure messages, neither of which are reasonable state of "normal".

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Tested virtualbox, google-chrome, and a number of the expressions modified but not all.

### CODE REVIEW

**Comment by xeji** [comment]
I haven't looked at the details yet, but for virtualbox it might be easier to override stdenv in all-packages.nix to replace patchelf with patchelfUnstable. Similar to overrideCC ...

**Comment by dtzWill** [comment]
Bah, I'll just drop the virtualbox fix -- although I do still move it to nativeBuildInputs since that's where it should be as long as it's anywhere.

Then we can use your PR to remove it and leave fixing it for another day (another PR) since it appears to be more involved than I originally thought :).

**Comment by xeji** [comment]
@GrahamcOfBorg build virtualbox

**Review by xeji — APPROVED** [review]

**Comment by Ericson2314** [comment]
Great stuff!

**Pull request merged**
