### PR TITLE
firefox: 88.0.1 -> 89.0

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://www.mozilla.org/en-US/firefox/89.0/releasenotes/ 
TBA

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
WFM on x86_64 wayland/pipewire. Tested webcam/microphone/screensharing/video decoding.

**Comment by vcunat** [comment]
That's [quic](https://hacks.mozilla.org/2021/04/quic-and-http-3-support-now-in-firefox-nightly-and-beta/)!  (I think)

**Comment by mweinelt** [comment]
And fission (rolling with it since 88.0.1 though): https://hacks.mozilla.org/2021/05/introducing-firefox-new-site-isolation-security-architecture/

**Comment by mweinelt** [comment]
> That's [quic](https://hacks.mozilla.org/2021/04/quic-and-http-3-support-now-in-firefox-nightly-and-beta/)! (I think)

Enabled `network.http.http3.enabled` and visited https://quic.rocks:4433/, but it uses HTTP/1.1. :man_shrugging:

**Comment by mweinelt** [comment]
@taku0 This will not cleanly backport to 20.09, as we're using rust-cbindgen_latest there.

**Comment by taku0** [comment]
@mweinelt OK, I see.

**Comment by mweinelt** [comment]
In fact I think this is the time to introduce `rust-cbindgen_latest` on release-21.05.

**Review by Atemu — APPROVED** [review]
Working as expected.

**Review by ajs124 — APPROVED** [review]
X11 x86_64 + pulseaudio works for me

**Comment by mweinelt** [comment]
https://www.mozilla.org/en-US/security/advisories/mfsa2021-23/

**Pull request merged**
