### PR TITLE
treewide: add `--enable-wayland-ime` flag to all Electron packages that uses `NIXOS_OZONE_WL`

### LINKED ISSUE #358368: Electron: Inconsistent addition of `--enable-wayland-ime` when `NIXOS_OZONE_WL` is set
## Describe the bug

I found that some packages add `--enable-wayland-ime` when `NIXOS_OZONE_WL` is set, and some do not.

- [10 Packages adding `--enable-wayland-ime`](https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20--enable-wayland-ime&type=code)
- [99 Packages using `NIXOS_OZONE_WL`](https://github.com/search?q=repo%3ANixOS%2Fnixpkgs+NIXOS_OZONE_WL&type=code)

- I am using `fcitx5` and `KDE Plasma 6` and setting `NIXOS_OZONE_WL=1`
- `vesktop` allows Japanese input, while `VS Code` and `Slack` do not. 
- If I add the `--enable-wayland-ime` flag and start `VS Code` or `Slack`, I can input Japanese.
- Therefore, I suggest adding this flag to all packages that use `NIXOS_OZONE_WL` if `NIXOS_OZONE_WL` is set.

## Steps To Reproduce

1. Use Wayland and set `NIXOS_OZONE_WL=1`
2. Install Fcitx5 and mozc
3. Open vesktop and Slack

## Expected behavior

All packages allow Japanese input

## Additional context

- About `NIXOS_OZONE_WL`: #291051
- This issue is also related to the problem that Electron does not provide the ability to override `--enable-wayland-ime` by setting an environment variable. (https://github.com/electron/electron/issues/33662#issuecomment-2211781618)
- According to Fcitx 5 wiki, it seems it is always recommended to add `--enable-wayland-ime` or `--gtk-version=4` (which is only supported in chromium/chrome) flag when launching Electron apps. (https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron)
- It is possible to add flags using `~/.config/electron-flags.conf`, but "do not work for packages that bundle their own build of Electron" (https://wiki.archlinux.org/title/Wayland#Configuration_file).

## Notify maintainers

@mmahut @teutat3s
@eadwu @Synthetica9 @bobby285271 @Enzime

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by 34j**
Closes #358368

Adds `--enable-wayland-ime` flag to all Electron packages that uses `NIXOS_OZONE_WL`

According to Fcitx 5 wiki, it seems it is always recommended to add `--enable-wayland-ime` or `--gtk-version=4` (which is only supported in chromium/chrome) flag when launching Electron apps to use text-input-v1. (https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron) See #358368 for further information.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

```python
import re

from collections import defaultdict
from pathlib import Path

# for each nix file in the pkgs directory
for path in Path('pkgs').rglob('*.nix'):
    txt = path.read_text()
    
    # find NIXOS_OZONE_WL
    # start_text = '''"\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+'''
    match = re.search(r'\${WAYLAND_DISPLAY\:\+(.+?)}}', txt)
    if match:
        if "--enable-wayland-ime" not in match.group(1):
            print(path)
            txt = txt.replace(match.group(1), match.group(1) + " --enable-wayland-ime")
            path.write_text(txt)     
```

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 34j** [comment]
Testing with random apps: 
|app|image|
|--|--|
|zulip |image|
|ytmdesktop| image|
|zettlr |image|
|postman| image|
|obsidian| image|
|drawio| image|
|bruno| image|
|altair| stuck image|

**Review by Scrumplex — APPROVED** [review]
Changes LGTM. Seems like none were missed.

**Comment by 34j** [comment]
Can it be merged now as the CI passed?

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 358620`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 7 packages marked as broken and skipped:</summary>
  <ul>
    <li>archivebox</li>
    <li>archivebox.dist</li>
    <li>logseq</li>
    <li>lx-music-desktop</li>
    <li>micropad</li>
    <li>passky-desktop</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>cider-2</li>
    <li>deltachat-desktop</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 141 packages built:</summary>
  <ul>
    <li>_1password-gui</li>
    <li>_1password-gui-beta</li>
    <li>affine</li>
    <li>altair</li>
    <li>anytype</li>
    <li>aws-azure-login</li>
    <li>bazecor</li>
    <li>beekeeper-studio</li>
    <li>beeper</li>
    <li>betaflight-configurator</li>
    <li>bitwarden-desktop</li>
    <li>bitwarden-directory-connector</li>
    <li>blockbench</li>
    <li>brave</li>
    <li>bruno</li>
    <li>caprine</li>
    <li>chatzone-desktop</li>
    <li>chromium</li>
    <li>chromium.sandbox</li>
    <li>cider</li>
    <li>code-cursor</li>
    <li>discord</li>
    <li>discord-canary</li>
    <li>discord-development</li>
    <li>discord-ptb</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>emuflight-configurator</li>
    <li>fast-cli</li>
    <li>feishin</li>
    <li>figma-linux</li>
    <li>flaresolverr</li>
    <li>framesh</li>
    <li>freetube</li>
    <li>github-desktop</li>
    <li>gitify</li>
    <li>gitkraken</li>
    <li>goofcord</li>
    <li>google-chrome</li>
    <li>gotenberg</li>
    <li>grafana-kiosk</li>
    <li>gridtracker</li>
    <li>httptoolkit</li>
    <li>icestudio</li>
    <li>inav-configurator</li>
    <li>itch</li>
    <li>jitsi-meet-electron</li>
    <li>joplin-desktop</li>
    <li>kando</li>
    <li>keybase-gui</li>
    <li>koodo-reader</li>
    <li>kuro</li>
    <li>legcord</li>
    <li>lens</li>
    <li>lunar-client</li>
    <li>mattermost-desktop</li>
    <li>mermaid-cli</li>
    <li>mermaid-filter</li>
    <li>microsoft-edge</li>
    <li>morgen</li>
    <li>mqtt-explorer</li>
    <li>muffon</li>
    <li>mullvad-vpn</li>
    <li>multiviewer-for-f1</li>
    <li>netflix</li>
    <li>nwjs</li>
    <li>nwjs-sdk</li>
    <li>obsidian</li>
    <li>onlykey</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>percollate</li>
    <li>pinegrow</li>
    <li>pinegrow6</li>
    <li>pinnwand</li>
    <li>pinnwand.dist</li>
    <li>playwright-test</li>
    <li>plexamp</li>
    <li>podman-desktop</li>
    <li>popcorntime</li>
    <li>postman</li>
    <li>proton-pass</li>
    <li>protonmail-desktop</li>
    <li>puppeteer-cli</li>
    <li>python311Packages.django-filingcabinet</li>
    <li>python311Packages.django-filingcabinet.dist</li>
    <li>python311Packages.great-tables</li>
    <li>python311Packages.great-tables.dist</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python311Packages.pytest-playwright</li>
    <li>python311Packages.pytest-playwright.dist</li>
    <li>python311Packages.shiny</li>
    <li>python311Packages.shiny.dist</li>
    <li>python312Packages.django-filingcabinet</li>
    <li>python312Packages.django-filingcabinet.dist</li>
    <li>python312Packages.great-tables</li>
    <li>python312Packages.great-tables.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.pytest-playwright</li>
    <li>python312Packages.pytest-playwright.dist</li>
    <li>python312Packages.shiny</li>
    <li>python312Packages.shiny.dist</li>
    <li>r2modman</li>
    <li>redact</li>
    <li>redisinsight</li>
    <li>revolt-desktop</li>
    <li>ride</li>
    <li>session-desktop</li>
    <li>sharedown</li>
    <li>signal-desktop</li>
    <li>single-file-cli</li>
    <li>sitespeed-io</li>
    <li>slack</li>
    <li>spotify</li>
    <li>spotifywm</li>
    <li>teams-for-linux</li>
    <li>tidal-hifi</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>ungoogled-chromium</li>
    <li>ungoogled-chromium.sandbox</li>
    <li>upscayl</li>
    <li>vhs</li>
    <li>vivaldi</li>
    <li>vscode</li>
    <li>vscode-extensions.yzane.markdown-pdf</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wavebox</li>
    <li>wayback</li>
    <li>wootility</li>
    <li>youtube-music</li>
    <li>ytmdesktop</li>
    <li>zettlr</li>
    <li>zulip</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 14 packages marked as broken and skipped:</summary>
  <ul>
    <li>archivebox</li>
    <li>archivebox.dist</li>
    <li>betaflight-configurator</li>
    <li>emuflight-configurator</li>
    <li>gridtracker</li>
    <li>icestudio</li>
    <li>inav-configurator</li>
    <li>lx-music-desktop</li>
    <li>micropad</li>
    <li>onlykey</li>
    <li>passky-desktop</li>
    <li>spotifywm</li>
    <li>uhk-udev-rules</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.django-filingcabinet</li>
    <li>python311Packages.django-filingcabinet.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 90 packages built:</summary>
  <ul>
    <li>_1password-gui</li>
    <li>_1password-gui-beta</li>
    <li>aws-azure-login</li>
    <li>beekeeper-studio</li>
    <li>bitwarden-desktop</li>
    <li>bitwarden-directory-connector</li>
    <li>blockbench</li>
    <li>brave</li>
    <li>bruno</li>
    <li>caprine</li>
    <li>chromium</li>
    <li>chromium.sandbox</li>
    <li>deltachat-desktop</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>fast-cli</li>
    <li>feishin</li>
    <li>flaresolverr</li>
    <li>freetube</li>
    <li>github-desktop</li>
    <li>gitify</li>
    <li>goofcord</li>
    <li>gotenberg</li>
    <li>grafana-kiosk</li>
    <li>httptoolkit</li>
    <li>jitsi-meet-electron</li>
    <li>kando</li>
    <li>koodo-reader</li>
    <li>kuro</li>
    <li>legcord</li>
    <li>mattermost-desktop</li>
    <li>mermaid-cli</li>
    <li>mermaid-filter</li>
    <li>mqtt-explorer</li>
    <li>mullvad-vpn</li>
    <li>obsidian</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>percollate</li>
    <li>pinnwand</li>
    <li>pinnwand.dist</li>
    <li>playwright-test</li>
    <li>podman-desktop</li>
    <li>postman</li>
    <li>puppeteer-cli</li>
    <li>python311Packages.great-tables</li>
    <li>python311Packages.great-tables.dist</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python311Packages.pytest-playwright</li>
    <li>python311Packages.pytest-playwright.dist</li>
    <li>python311Packages.shiny</li>
    <li>python311Packages.shiny.dist</li>
    <li>python312Packages.django-filingcabinet</li>
    <li>python312Packages.django-filingcabinet.dist</li>
    <li>python312Packages.great-tables</li>
    <li>python312Packages.great-tables.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.pytest-playwright</li>
    <li>python312Packages.pytest-playwright.dist</li>
    <li>python312Packages.shiny</li>
    <li>python312Packages.shiny.dist</li>
    <li>r2modman</li>
    <li>redisinsight</li>
    <li>revolt-desktop</li>
    <li>ride</li>
    <li>sharedown</li>
    <li>signal-desktop</li>
    <li>single-file-cli</li>
    <li>sitespeed-io</li>
    <li>teams-for-linux</li>
    <li>tidal-hifi</li>
    <li>ungoogled-chromium</li>
    <li>ungoogled-chromium.sandbox</li>
    <li>upscayl</li>
    <li>vhs</li>
    <li>vivaldi</li>
    <li>vscode</li>
    <li>vscode-extensions.yzane.markdown-pdf</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wayback</li>
    <li>wootility</li>
    <li>youtube-music</li>
    <li>ytmdesktop</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>micropad</li>
    <li>onlykey</li>
    <li>passky-desktop</li>
    <li>uhk-udev-rules</li>
    <li>vscode-fhs</li>
    <li>vscodium-fhs</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>element-desktop-wayland</li>
    <li>vscode</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>micropad</li>
    <li>onlykey</li>
    <li>passky-desktop</li>
    <li>uhk-udev-rules</li>
    <li>vscode-fhs</li>
    <li>vscodium-fhs</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>element-desktop-wayland</li>
    <li>vscode</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
  </ul>
</details>

**Comment by 34j** [comment]
I am not familiar with nixpkgs, but does the build failure depend on whether or not a flag is passed?

**Review by khaneliman — APPROVED** [review]

**Comment by khaneliman** [comment]
> I am not familiar with nixpkgs, but does the build failure depend on whether or not a flag is passed?

I'm just always curious to see how many packages are affected by any given change and what the current status of builds are. In this case, it shouldn't affect the outcome of a given build.

**Pull request merged**
