### PR TITLE
haskell/network: 2.6.3.4 -> 2.6.3.6 (release-18.03)

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

@peti network-2.6.3.6 fixes some bugs that I'm currently suffering from in our 18.03 production systems.

http://hackage.haskell.org/package/network-2.6.3.6/changelog

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by infinisil — CHANGES_REQUESTED** [review]
This file is autogenerated, you should put modifications to it into `pkgs/development/haskell-modules/configuration-*.nix`

**Comment by basvandijk** [comment]
Since `hackage-packages.nix` in `master` already has `network-2.6.3.6` the next time this file gets regenerated in `release-18.03` it will also get `network-2.6.3.6`. So I think making the change in that file is less of a maintenance burden than making an override in `configuration-common.nix` because that has to be removed later. Let me know if my reasoning is flawed then I'll make an override.

**Review by peti — APPROVED** [review]
I believe in this particular case it's fine (and actually preferable) to edit the `hackage-packages.nix` file directly. If we ever update the package set in the release branch, then we'll end up with that version anyway and an override does need to be removed in such a case.

**Comment by Infinisil** [comment]
I see, I didn't think of that, neat!

**Pull request merged**
