### PR TITLE
curl-impersonate-bin: 0.5.3 -> 0.5.4; follow upstream on platforms

### PR DESCRIPTION
**Pull request by 7c6f434c**
###### Description of changes

v0.5.4

Support all three platforms with upstream binaries (and don't pretend to support other Linux)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Tested that specific curl-disliking pages provide the actual content
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@deliciouslytyped — looks like ofBorg is not allowed to review-request you

**Comment by lilyinstarlight** [comment]
#194310 merged when....

> @deliciouslytyped — looks like ofBorg is not allowed to review-request you

It seems they are no longer in the NixOS org. Whether that is because of them never accepting the invite or from leaving is unclear. They can ask for a new invite in Matrix though

**Comment by 7c6f434c** [comment]
Ah, I searched through the checkout and after finding something haven't looked at GitHub…

Given the context, I'd want both bin and source available, though; not sure if it is easy to test them against each other.

I did check that there are some relatively recent PR reviews before doing a mention, so I decided that at least trying to attract maintainer attention is better than not…

**Comment by lilyinstarlight** [comment]
> Given the context, I'd want both bin and source available, though; not sure if it is easy to test them against each other.

The PR actually uses the upstream tests, which compares TLS handshakes/fingerprints from tcpdump packet captures

I'm not sure testing against the binary release would have any benefits compared to that (I'm not sure if you're just wanting to test TLS fingerprints, which is already done, or if you're meaning you want to test something else too)

> I did check that there are some relatively recent PR reviews before doing a mention, so I decided that at least trying to attract maintainer attention is better than not…

Oh yeah absolutely! I imagine they may have actually just missed the invite and need a new one

I was going to give them a few days to chime in on the PR and just review it myself if they're too busy right now

**Comment by lilyinstarlight** [comment]
> Oh right, eradicating randomness in TLS handshake is probably too large of a task, pity…

Their upstream tests already calculate a fingerprint from the handshake using the non-random parts and compares against actual captures from the versions it attempts to impersonate. So random values in the handshake isn't really the problem

> (Then I just want binary version as a quick-check if the source build ever doesn't seem to suffice, so that it's clear on which side is the issue)

So you mean attempt to run their upstream tests against the binary build too? (I'm just not following very well, my apologies)

**Comment by 7c6f434c** [comment]
No-no, if an external adversary at any point manages to distinguish the impersonation from a browser instance, to have an ability to check easily where things go wrong on the line «upstream binaries in chroot» — «upstream binaries in FHSenv» — «upstream binaries with our glibc patchelf-ed» — «Nixpkgs build».

If tests end up not detailed enough for some adversarially chosen corner cases or something.

**Comment by 7c6f434c** [comment]
Yes, I agree that we cannot do a useful test with a nix-build, but if we change the versions it is good to exclude the chance that the upstream choice of versions is non-random and better. 

But maybe setting up a FHSenv is indeed better.

**Pull request closed without merging**
