### PR TITLE
coolercontrol.*: 1.3.0 -> 1.4.0

### PR DESCRIPTION
**Pull request by codifryed**
## Description of changes

Update for CoolerControl: 1.3.0 -> 1.4.0  
Changelog: https://gitlab.com/coolercontrol/coolercontrol/-/releases/1.4.0

No breaking changes, but there are dependency changes. In particular for NVidia GPUs, `coolercontrold` will now use the NVML instead of the shell utilities `nvidia-settings` and `nvidia-smi`, if found. The NVML offers more features and is more efficient, which comes as part of the official display drivers. I am not certain however if we need any wrappers to enable that access. The Nvidia CLI utilities will still be used as a fallback.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by IldenH — APPROVED** [review]

**Comment by OPNA2608** [comment]
@ofborg build coolercontrol.coolercontrold coolercontrol.coolercontrold.passthru.tests coolercontrol.coolercontrol-liqctld coolercontrol.coolercontrol-liqctld.passthru.tests coolercontrol.coolercontrol-gui coolercontrol.coolercontrol-gui.passthru.tests

Can you tell me how the new Nvidia code is trying to find & use this NVML stuff? (Still don't have that hardware)

**Comment by codifryed** [comment]
Hi @OPNA2608 

> Can you tell me how the new Nvidia code is trying to find & use this NVML stuff? (Still don't have that hardware)

So, looks like we may need a patch/change for this. What I've discovered so far:
The nvml-wrapper rust library (aka the NVML rust binding) is using the `libloading` rust crate to dynamic load the library, if found. 

For linux it searches for `libnvidia-ml.so` set here: https://github.com/codifryed/nvml-wrapper/blob/main/nvml-wrapper/src/lib.rs#L158

Now, although the nvml-wrapper crate is not a standalone package in Nix, the official python bindings are, and they have a patch:

```
                        try:
+                            nvmlLib = CDLL("libnvidia-ml.so.1")
+                        except OSError:
+                            # Assume NixOS
+                            nvmlLib = CDLL("@driverLink@/lib/libnvidia-ml.so.1")
```
here: [pkgs/development/python-modules/nvidia-ml-py/0001-locate-libnvidia-ml.so.1-on-NixOS.patch](https://github.com/NixOS/nixpkgs/blob/35f02c744af354ff202ad829c803527b365d0ee5/pkgs/development/python-modules/nvidia-ml-py/0001-locate-libnvidia-ml.so.1-on-NixOS.patch)

I'm unsure of what `@driverLink@` is exactly doing, but maybe you have an idea.

Note, that we are currently using a fork of the nvml-wrapper library with fan control enabled, due to a lack of response from upstream. (hopefully that changes at some point) So we could make some adjustments pretty easily if needed.

**Comment by OPNA2608** [comment]
Sorry, this slipped off my radar.

> I'm unsure of what `@driverLink@` is exactly doing, but maybe you have an idea.

https://github.com/NixOS/nixpkgs/blob/35f02c744af354ff202ad829c803527b365d0ee5/pkgs/development/python-modules/nvidia-ml-py/default.nix#L20-L25

https://github.com/NixOS/nixpkgs/blob/da4ddb3be94a3b328f146d90462d2fbbfd543ca3/pkgs/build-support/add-driver-runpath/default.nix#L6-L8

```
↪ tree -la /run/opengl-driver/ -L 2
/run/opengl-driver/
├── lib -> /nix/store/g4gar0lac83yl5qnj51mhhcrnscl8lzk-mesa-24.0.7-drivers/lib
│   ├── d3d
│   ├── dri
│   ├── libEGL_mesa.so -> libEGL_mesa.so.0
│   ├── libEGL_mesa.so.0 -> libEGL_mesa.so.0.0.0
│   ├── libEGL_mesa.so.0.0.0
│   ├── libGLX_mesa.so -> libGLX_mesa.so.0
│   ├── libGLX_mesa.so.0 -> libGLX_mesa.so.0.0.0
│   ├── libGLX_mesa.so.0.0.0
│   ├── libVkLayer_INTEL_nullhw.so
│   ├── libVkLayer_MESA_device_select.so
│   ├── libVkLayer_MESA_overlay.so
│   ├── libvulkan_dzn.so
│   ├── libvulkan_intel_hasvk.so
│   ├── libvulkan_intel.so
│   ├── libvulkan_lvp.so
│   ├── libvulkan_nouveau.so
│   ├── libvulkan_radeon.so
│   ├── libvulkan_virtio.so
│   ├── libxatracker.so -> libxatracker.so.2
│   ├── libxatracker.so.2 -> libxatracker.so.2.5.0
│   ├── libxatracker.so.2.5.0
│   └── vdpau
└── share -> /nix/store/g4gar0lac83yl5qnj51mhhcrnscl8lzk-mesa-24.0.7-drivers/share
    ├── glvnd
    └── vulkan
```

Basically the prefix where the current booted system's GPU drivers are located.

I think for `libnvidia-ml.so` to be available, some CUDA setup magic in the derivation & the user's system is needed? Which I'm not at all familiar with.

> The Nvidia CLI utilities will still be used as a fallback.

Do you think it'd be fine to keep it as-is for now?

**Comment by codifryed** [comment]
> Basically the prefix where the current booted system's GPU drivers are located.

Thanks for the info @OPNA2608!

> Do you think it'd be fine to keep it as-is for now?

I do, as essentially NVidia GPU fan control will then continue to work as it did pre-1.4. To make any upstream changes would require a new patch version anyway. Note, that the following 1.4 NVidia GPU features are NVML bound and will not be available:
- Display of various Clock Frequencies
- Independent fan controls (on supporting cards)
- Reduced overhead & fault tolerance (Using the C API is much more efficient than the CLI Utils)

Nothing breaking though. 👍🏼

**Pull request merged**
