### PR TITLE
nixos/test-driver: add execute_with_timeout, add (functional) timeouts to more functions

### PR DESCRIPTION
**Pull request by cole-h**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

TODO: write release notes after all potential reviewers are satisfied with how I've approached this

Note: I tested a few different tests to make sure there were no regressions, but obviously it's not easy / possible to check them all...

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg test installer.simple installer.zfsroot doas sudo hydra nginx wireguard deluge cage

Let's just pick some random tests and see if they still work...

**Comment by cole-h** [comment]
@tfc Is there anything missing / anything I can do, or do you just need to find some time for review?

**Comment by tfc** [comment]
@cole-h looks generally good, but i would like to play with this a bit before i merge it, but do not have time for that today. let me see tomorrow.

**Comment by cole-h** [comment]
Sure thing! Thanks for your time.

**Comment by cole-h** [comment]
Ping @tfc -- I'd like to get this in sooner rather than later so that future tests can take advantage of this. Is there anything I can do to help / alleviate any concerns you may have?

**Pull request merged**
