### PR TITLE
electron: fix wrapGAppsHook usage

### LINKED ISSUE #84913: Correct electron package wrapGAppsHook usage
**Describe the bug**
The electron package tries to wrap in `buildCommand`.
Because of this the wrapper is completely void of any entries in `XDG_DATA_DIRS`.
It needs to be rewritten in whatever fashion that the `makeWrapper` call happens in `postFixup`.

This is why `riot-desktop` has needed to be wrapped recently https://github.com/NixOS/nixpkgs/commit/fe6addbbf717d4977434e81acd7535c3b074e3a3, it's because `electron` isn't wrapped correctly itself. A change should be made to stable to revert this to riot-desktop, and to backport this fix instead.

Expression: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/electron/generic.nix#L59

buildInputs should also have `glib` for it's setup-hook https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/electron/generic.nix#L37.

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/84913 by:

1. reverting the riot-desktop change
2. fixing wrapGAppsHook in electron

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Please @travisbhartwell @manveru review and test, I have very little idea of whether the change is correct.

However, I tried that applying the first commit breaks riot-desktop (opening a native file dialog will crash) and applying the second commit will fixes it again.

@worldofpeace is that what you mean by "It needs to be rewritten in whatever fashion that the `makeWrapper` call happens in `postFixup`." in #84913?

**Comment by das-g** [comment]
Result of `nixpkgs-review pr 84981`:


<details><summary>1 package marked as broken and skipped:</summary>

- hyper-haskell

</details>
<details><summary>11 package built:</summary>

- electron
- electron_5
- electron_6
- electron_7
- electron_8
- nix-tour
- rambox-pro
- riot-desktop
- stretchly
- teleprompter
- typora

</details>

**Comment by das-g** [comment]
:+1: I've tried the file open dialog (through "upload file") in the resulting `riot-desktop` application and it works fine. (I assume file open dialog is a native dialog, isn't it?)

**Comment by worldofpeace** [comment]
Here's the wrapper content
```
export LD_PRELOAD='/nix/store/wswi9pd2nc25lqd52mnd94w90l1yxxni-libXScrnSaver-1.2.3/lib/libXss.so.1'${LD_PRELOAD:+':'}$LD_PRELOAD
export GIO_EXTRA_MODULES='/nix/store/0byixyx6l833y9a7ah8ygbh4d4nfgcin-dconf-0.36.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GIO_EXTRA_MODULES='/nix/store/0byixyx6l833y9a7ah8ygbh4d4nfgcin-dconf-0.36.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GDK_PIXBUF_MODULE_FILE='/nix/store/a7dwk7qamr2j7220rsfvn8w386b8a3lc-librsvg-2.48.0/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
export XDG_DATA_DIRS='/nix/store/2chzii7gwmlcii9x73l0v3bl7lf2awvb-gtk+3-3.24.14/share/gsettings-schemas/gtk+3-3.24.14:/nix/store/2chzii7gwmlcii9x73l0v3bl7lf2awvb-gtk+3-3.24.>
exec -a "$0" "/nix/store/0in2y9m4nsbkfg3h0yp18cmam4k6xifk-electron-8.0.0/lib/electron/.electron-wrapped"  "$@"
```

it has correct entries so this is wrapped correctly :+1:

**Comment by worldofpeace** [comment]
> Please review and test, I have very little idea of whether the change is correct.
> 
> However, I tried that applying the first commit breaks riot-desktop (opening a native file dialog will crash) and applying the second commit fixes it again.
> 
> @worldofpeace is that what you mean by "It needs to be rewritten in whatever fashion that the `makeWrapper` call happens in `postFixup`." in #84913?

Yep, you've done this correctly.

**Comment by worldofpeace** [comment]
backported to 20.03 in 3ad8596931f96ea6cb77f90efad50f45b4899a97 22b5a32fad48dea2100053fdbbd64d941377ac23.

Thanks again for fixing this, it helped me out very much :+1:

**Pull request merged**
