### PR TITLE
sway: 0.13.0 -> 0.14.0

### PR DESCRIPTION
**Pull request by disassembler**
###### Motivation for this change
comment said it segfaults, but worked fine for me. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
How can I test this?

**Comment by disassembler** [comment]
It doesn't seem to work if all you do is `nix-build -A sway` and run `result/bin/sway`. I'm not exactly sure why. But if you add sway and xwayland to `environment.systemPackages` and run `nixos-rebuild -I nixpkgs=/path/to/nixpkgs` and then stop X11 and run `sway` as a user, you should have the sway background show up. hitting `super+enter` will give you a terminal. You can also switch workspaces using `super+#` (where # is the workspace you want). The sway bar doesn't seem to work with the default config on 0.14.0. Works great with 0.15-rc2 though, so maybe we just wait until that releases.

**Comment by 7c6f434c** [comment]
Just in case re: installation method: did you try adding `result/bin`
to `$PATH` without system-wide installation?

**Comment by Mic92** [comment]
I added a module with the capabilities as described in the project page, but I get a segfault as well:


```console
gdb> bt
#0  0x00007f4798edf0f7 in wl_list_remove () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#1  0x00007f47997ce3a7 in wlc_xwm_release () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#2  0x00007f47997b34c0 in xwayland_event () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#3  0x00007f47997cbafc in wlc_xwayland_terminate () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#4  0x00007f47997cc422 in destroy_event () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#5  0x00007f4798eda7bc in wl_client_destroy () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#6  0x00007f4798eda8d8 in wl_client_connection_data () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#7  0x00007f4798edcae2 in wl_event_loop_dispatch () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#8  0x00007f4798edaf8a in wl_display_run () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#9  0x00007f47997c992c in wlc_run () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#10 0x000000000040bc81 in main ()
#11 0x00007f47974f4560 in __libc_start_main () from /nix/store/yydnhs7migvlbl48wpsxan1yvq2icbr9-glibc-2.25-49/lib/libc.so.6
#12 0x000000000040be3a in _start ()
```

**Comment by disassembler** [comment]
Graphics card is `Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)` I have this in my configuration.nix:
```
      opengl.enable = true;                                                               
      opengl.extraPackages = [ pkgs.vaapiIntel ];
```

**Comment by Mic92** [comment]
I have a Broadwell CPU + graphics. The version here keeps segfaulting while the old version seems to work.

**Comment by disassembler** [comment]
using programs.sway.enable = true; I get a segfault as well, but if I just put sway and xwayland in `environment.systemPackages` it works fine for me. Here's the configuration.nix I used: https://gist.github.com/anonymous/6fab3b96d18cf6c808fafc5d0eeb05a5. Command to install was `sudo nixos-rebuild switch -I nixpkgs=/home/sam/nixpkgs`

proof of newer version of sway running:

```
sam      28275  1.0  1.5 252592 62856 tty1     S+   21:58   0:03 /run/current-system/sw/bin/sway                                                   
sam      28277  0.0  0.0 177456  1232 tty1     S+   21:58   0:00 /run/current-system/sw/bin/sway                                                   
sam      28279  0.0  0.5 150456 22384 tty1     S+   21:58   0:00 swaybg 0 /nix/store/r4g9pwhs6biyfsyaxxa2vnwbhlfwi8a0-sway-0.14.0/share/sway/Sway_Wallpaper_Blue_1920x1080.png fill
$ ls -hal `which sway`                                                                                                                             
lrwxrwxrwx 1 root root 64 Dec 31  1969 /run/current-system/sw/bin/sway -> /nix/store/r4g9pwhs6biyfsyaxxa2vnwbhlfwi8a0-sway-0.14.0/bin/sway         
```

**Comment by Mic92** [comment]
Ok. With `xwayland` in my `systemPackages` it works. But adding just prefixing `${xwayland}/bin` in the sway wrapper does not solve the problem. So it must be a different dependency, which gets propagated by this package.

**Comment by disassembler** [comment]
@Mic92 I tried propagating the `buildInputs` for wlc, and it works for me now! Can you test?

**Comment by disassembler** [comment]
I updated the nixos module to include xwayland and things work for me.

**Comment by NeQuissimus** [comment]
Should we pick this into stable?

**Comment by NeQuissimus** [comment]
I am trying to figure out how this module is supposed to work...
If I enable it and remove everything I have that is XMonad and XServer related, I land on a plain tty1 prompt upon reboot.
I log in, I say `sway` and it complains about X not running.

Ideally, this module would just replace the xserver module and give me a UI to log in to etc. right?
Am I misunderstanding its purpose?

**Comment by gnidorah** [comment]
@NeQuissimus There were efforts on this, but none got finished and merged:
https://github.com/NixOS/nixpkgs/pull/19663
https://github.com/NixOS/nixpkgs/pull/23059

**Comment by NeQuissimus** [comment]
Ah, OK.

So if we mixed #19663 with a little bit of #20385 and this one here, we should have all the ingredients to make this work, correct?

**Comment by gnidorah** [comment]
Most likely. Here's someone was able to login via slim https://github.com/NixOS/nixpkgs/pull/19663#issuecomment-275344318 
It's important not to miss `extraSessionCommands`, because many things are configured this way starting from https://github.com/swaywm/sway/wiki#input-configuration

**Comment by NeQuissimus** [comment]
I mix-and-matched the PRs together but cannot get past SLiM or SDDM...
https://gist.github.com/NeQuissimus/bce7119e985bf077eafc16d9f99bcbcb

**Comment by gnidorah** [comment]
@NeQuissimus It works for me if `services.xserver.enable = true;` It wouldn't be hard to make it work without xserver, but we need a login manager that works without X

**Comment by gnidorah** [comment]
@NeQuissimus Perhaps something is wrong with your setup. If not using your patch:
> If I enable it and remove everything I have that is XMonad and XServer related, I land on a plain tty1 prompt upon reboot.
I log in, I say sway and it complains about X not running.

If you disable xserver, then your should add
```
hardware.opengl.enable = true;
fonts.enableDefaultFonts = true;
```
to your config. But actually you don't need to disable xserver and xmonad. Just switch to console tty, login and run sway command.

**Comment by NeQuissimus** [comment]
I use this to configure sway:
https://github.com/NeQuissimus/DevSetup/blob/master/nixos-sway.nix

I updated the Gist to reflect your changes.
I still cannot log in... And I see no errors anywhere either.

**Comment by gnidorah** [comment]
@NeQuissimus Thanks. I've took your updated patch and nixos-sway.nix, did
> I import it and have no other xserver-related config

the same. And it works fine for me. To debug try following:
1. Use your normal config with xserver and xmonad
2. Put `programs.sway.enable = true;` there, do rebuild
3. Switch to console tty (ctrl+alt+f1), login here
4. Run `sway -Vd >/tmp/sway.log 2>&1`

**Comment by NeQuissimus** [comment]
I will spend some more time with this over the weekend if I can. Once I have things working, I will send a PR with the contents of my Gist...

**Pull request merged**
