### PR TITLE
pythonPackages.sasmodels: fix build

### PR DESCRIPTION
**Pull request by Ma27**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
currently running `nox-review`, but not related to the original camp :)

**Comment by xeji** [comment]
If the hash changed vor the same version it might be better to pin it to a git revision.

**Comment by dotlambda** [comment]
And `fetchFromGitHub` should be used instead.

**Comment by Ma27** [comment]
@dotlambda @xeji thanks a lot for your feedback! I applied it and performed a bump to the latest revision (for now) as it provides proper configuration for the `py.test` suite (have a look at https://github.com/SasView/sasmodels/commit/a69d8cd7ece8a1df933b123d2e032197783d80b4 and the following commits for further reference)

**Comment by xeji** [comment]
@GrahamcOfBorg build python36Packages.sasmodels python27Packages.sasmodels sasview

**Comment by xeji** [comment]
@Ma27 can you have a look at the sasview failure?

**Comment by Ma27** [comment]
`sasview` fails locally with the following message:

```
fixed-output derivation produced path '/nix/store/5dh1mdj027ad8sprk12fqa5h5bpdxs5n-sasview' with sha256 hash '12k1w4yq1mzjxcp2cqb562c7cbwzhi54rsbmgi0fax0i1660q167' instead of the expected hash '05la54wwzzlkhmj8vkr0bvzagyib6z6mgwqbddzjs5y1wd48vpcx'
```

Seems as all of their hashes changed, will fix `sasview` as well...

**Comment by Ma27** [comment]
interesting... I just pinned `sasview` against the release's revision (https://github.com/SasView/sasview/commit/d9089328dec4c154a6bac2735e52b5e6fb3c8af2) and it breaks the test suite locally.

I'm currently working on a fix, however I'm not sure what to think of that. At least in case of any further breakage we should perform some deeper investigation to see what happens in their release process.

Pinging @rprospero as he packaged the software two months ago - do you know anything about the recent issues?

**Comment by xeji** [comment]
If you like we could merge this anyway since `pythonPackages.sasmodels` builds fine, and fix `sasview` in a separate PR. Your choice...

**Comment by Ma27** [comment]
@xeji you're absolutely right, let's merge this PR for now, fixing `sasview` is basically out of scope :-)

**Comment by xeji** [comment]
just wanna see sasmodels builds from ofborg first

@GrahamcOfBorg  build python36Packages.sasmodels python27Packages.sasmodels

**Comment by rprospero** [comment]
I'll try and figure out what's going on with sasview this week.

**Pull request merged**
