### PR TITLE
haskellPackages.cabal2nix: wrap with runtime dependencies

### PR DESCRIPTION
**Pull request by sternenseemann**
~~Previously the cabal2nix derivations just expected to find
nix-prefetch-* in PATH which we now explictly ensure via `wrapProgram`.
This will increase the closure of cabal2nix, however nix will be
installed anyways usually and nix-prefetch-scripts is relatively small.~~

~~This fixes the extremely unclear message callCabal2nix was failing with
if no suitable cabal file existed which was brought up in the following
issues / PRs:~~

* https://github.com/NixOS/cabal2nix/issues/472
* https://github.com/NixOS/nixpkgs/pull/119123

~~Now at least the normal, intended message is shown (although it is not
great) instead of cabal2nix failing earlier because nix-prefetch-url is
not missing.~~

~~cc @sorki @lf-~~

~~I'm still intent on improving the situation on the cabal2nix side of things,
I think we should make it less eager to fallback to fetcher scripts which
a) need (recursive) nix to write to the store and are thus unsuitable for
import-from-derivation (in stable nix) and b) try to access the network
as part of the fallback chain which is also not possible in the sandbox.~~

~~I'll have to review the code again — either we'll make `file://` more strict
and prevent cabal2nix from ever using `nix-prefetch-*` if that protocol
is used or we add an `--offline` flag to enforce this behavior.~~
 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
Open Questions:

* Was there a genuine need for cabal2nix-unwrapped or is it okay to     
  retire?
  
* Should we use wrapProgram --suffix to somewhat preserve the behavior  
  of cabal2nix-unwrapped?
  
To do:
 
* Write a changelog entry 

What do you guys thing @NixOS/haskell?

**Comment by sternenseemann** [comment]
`callCabal2nix` actually uses `buildPackages.cabal2nix-unwrapped` which makes quite a bit of sense, i. e. it should *never* call `nix` or `nix-prefetch-*` in the context its called.

I think I'll rework this PR.

**Comment by sternenseemann** [comment]
<https://github.com/NixOS/cabal2nix/pull/489> improves the error message significantly, without fetchers present:

```
builder for '/nix/store/l01kvyjrylzcfyv1aj8nblplqddasxjh-cabal2nix-f.drv' failed with exit code 1; last 2 log lines:
  installing
  cabal2nix: user error (*** Found neither a .cabal file nor package.yaml. Exiting.)
error: build of '/nix/store/l01kvyjrylzcfyv1aj8nblplqddasxjh-cabal2nix-f.drv' failed
```

Thus I think we'll just have to cut a release with that PR to resolve the issue.

**Comment by sternenseemann** [comment]
I'm convinced now that the cabal2nix - cabal2nix-unwrapped distinction is good, so I've cut down this PR to only wrap `cabal2nix-unstable` which we don't use in a way yet where an unwrapped version would make sense.

**Review by sorki — APPROVED** [review]
LGTM!

**Review by cdepillabout — APPROVED** [review]
This seems reasonable.

**Comment by maralorn** [comment]
I am slightly confused. I don‘t think this does any harm, but in which scenario would this be needed?

**Comment by sternenseemann** [comment]
Mostly if you run `${cabal2nix-unstable}/bin/cabal2nix` and don't have `nix-prefetch-scripts` installed globally (or are using a pure shell). So not necessary for our hackage2nix setup, but I thought might as well while I'm at it…

**Pull request merged**
