### PR TITLE
mesa: don't depend on build python

### PR DESCRIPTION
**Pull request by Artturin**
`mesa-overlay-control.py` has build python in it's shebang

`pkgsCross.aarch64-multiplatform.sway`

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
@ofborg eval

**Comment by vcunat** [comment]
Uh `patchShebangs --host` can put in _build_ python?

**Comment by Artturin** [comment]
> Uh `patchShebangs --host` can put in _build_ python?
> 
> EDIT: I didn't know the flag and don't really know cross stuff well, but it certainly looks surprising at a glance.

There's a patchShebangs in postPatch without any options which implies --build.

When patchShebang is done on a store path then --host is implied, but I like it explicit.

https://github.com/NixOS/nixpkgs/blob/4b58af2fcb4199e8d4e36584701cd6eac0e0b78f/pkgs/build-support/setup-hooks/patch-shebangs.sh#L79

The --update flag was added 3 months ago and this is actually the first use of it, very useful for fixing already patchShebanged scripts.

**Comment by vcunat** [comment]
Ah, I was confused.  I don't know why I thought that you were **removing** the line with `--host` and adding to buildInputs.

**Pull request merged**
