### PR TITLE
defaultGemConfig.mathematical: fix cross compilation

### PR DESCRIPTION
**Pull request by expipiplus1**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
I suggest also passing `strictDeps = true;` as that helps determining whether the deps are in the right place.

**Comment by expipiplus1** [comment]
@FRidh I have no idea about ruby packaging, but I had to add several libraries to buildinputs and add ruby to nativebuildinputs after I enabled strictdeps.

**Review by FRidh — APPROVED** [review]

**Comment by expipiplus1** [comment]
Possible to get this merged?

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
