### PR TITLE
flutter: Move package overrides to build-support

### PR DESCRIPTION
**Pull request by hacker1024**
###### Description of changes

This moves the Flutter package overrides to the build-support directory, as decided in https://github.com/NixOS/nixpkgs/pull/228282#discussion_r1177455022.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by algorithmiker — APPROVED** [review]
lgtm after ofborg passes

**Review by FlafyDev — APPROVED** [review]
LGTM

Not sure how relevant it is to this PR, but how would the package-overrides work when build support for dart is added? Would there be 2 `package-overrides` directories (one in `build-support/flutter` and another in `build-support/dart`)?
Or will it be better to keep a single `package-overrides` directory in `build-support/dart`?

**Comment by hacker1024** [comment]
> Not sure how relevant it is to this PR, but how would the package-overrides work when build support for dart is added? Would there be 2 `package-overrides` directories (one in `build-support/flutter` and another in `build-support/dart`)? Or will it be better to keep a single `package-overrides` directory in `build-support/dart`?

That's a good point. I was thinking about build-time C dependencies for Flutter apps when I first made the override system, but it is useful for supplying runtime dependencies for all FFI applications as well.

After #229770 is merged, I think it would make sense to move the override files to `dart/package-overrides`, implement the override system in `buildDartPackage`, and then rebase `buildFlutterApplication` on top of `buildDartPackage` with a custom `buildScript`.

**Comment by SuperSandro2000** [comment]
Most other eco systems I remember (ruby, rust, python, ...) have this split, to keep the buildSupport directory generic

**Comment by wegank** [comment]
I don't think package overrides align with builders and fetchers in build-support...

**Pull request closed without merging**
