### PR TITLE
python310Packages.ansible-lint: 6.0.2 -> 6.2.1

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

Depends on #172575

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sengaya** [comment]
I tried to build it, but it fails because pytest is only available in [version 7.1.1](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pytest/default.nix#L26) while ansible-lint needs [version 7.1.2](https://github.com/ansible/ansible-lint/blob/v6.1.0/requirements.txt#L61).

**Comment by SuperSandro2000** [comment]
We are not using that file because the version pins are not working for our packaging. https://github.com/ansible/ansible-lint/blob/v6.1.0/setup.cfg is relevant for the package.

**Comment by sengaya** [comment]
> We are not using that file because the version pins are not working for our packaging. https://github.com/ansible/ansible-lint/blob/v6.1.0/setup.cfg is relevant for the package.

oh, right, I misinterpret the output... thanks. I got the same error message like in the automatic tests:
`ERROR: Could not find a version that satisfies the requirement pytest (from ansible-lint) (from versions: none)`

**Comment by SuperSandro2000** [comment]
I am going to look at this again after the mentioned PR is merged.

**Pull request merged**
