### PR TITLE
chromium: Update versions

### PR DESCRIPTION
**Pull request by bendlas**
dev: 43.0.2327.5 -> 43.0.2357.18
beta: 42.0.2311.39 -> 42.0.2311.82
stable: 41.0.2272.89 -> 42.0.2311.90

cc @aszlig

### CODE REVIEW

**Comment by aszlig** [comment]
The dev build currently fails (https://headcounter.org/hydra/build/645529), and we might need to update gyp as well. Also, there is still that execve()-failure I introduced. Will have a look at it later this day.

**Comment by aszlig** [comment]
Sorry, takes a bit longer, need to work around https://crbug.com/462153 first :unamused:

**Comment by wizeman** [comment]
Chromium stable is up to v43 now...

**Comment by bendlas** [comment]
I tried version `43.0.2357.64` with the current build script, but it fails with

```
gyp: Undefined variable GENERATOR_FLAVOR in /tmp/nix-build-chromium-43.0.2357.65.drv-0/chromium-source-43.0.2357.65/breakpad/breakpad.gyp
gyp: Undefined variable GENERATOR_FLAVOR in /tmp/nix-build-chromium-43.0.2357.65.drv-0/chromium-source-43.0.2357.65/third_party/protobuf/protobuf.gyp
```

**Comment by aszlig** [comment]
Yes, that and the other issue I pointed out. I'm currently working on a `gyp2nix` generator to not only avoid issues with build paths but also massively speed up build time. I'm trying to get this done before the branch off to the `15.06` release and do a quick & dirty fix if I don't manage to hit the deadline.

**Comment by bendlas** [comment]
I can confirm, that with https://github.com/NixOS/nixpkgs/commit/efd4fcbebc09d2c40713913de40786d8cb31ed9c the `GENERATOR_FLAVOR` error goes away. Now failing for `third_party/angle` as (probably the first one of many) an instance of https://crbug.com/462153

Looking forward to your `gyp2nix` for packaging https://code.google.com/p/webrtc/ and other chromium-related stuff.

**Comment by aszlig** [comment]
note to myself: GitHub is not able to correctly parse "until we have fixed" :unamused:

**Comment by codyopel** [comment]
I came across most of this because I have been playing around with the chromium build trying to clean up some of the unnecessary abstraction and get widevine working.

I have mostly tracked down a solution to https://crbug.com/462153.  `gyp_chromium` isn't passing
```--depth``` to `gyp` so it is never set.  `--depth` is a chromium specific workaround that is a poorly done hack.  If it isn't set if looks for a directory titled 'src' to find the source files within, which would be a nightmare to satisfy.  One option is we could add a patch `gyp` so that the depth argument also excepts an environment variable so that we wouldn't have to deal with hacking `gyp_chromium`. This would require the least modification if it works and could be done with `sed`.
https://chromium.googlesource.com/external/gyp.git/+/master/pylib/gyp/__init__.py#300
https://chromium.googlesource.com/external/gyp.git/+/master/pylib/gyp/__init__.py#424

Out of curiosity what do you mean by gyp2nix? If it is what I think it is I am not sure that it would be a clean solution.

**Comment by aszlig** [comment]
With `gyp2nix` I mean a [nix-make](https://github.com/edolstra/nix-make) like approach

**Comment by bluescreen303** [comment]
@codyopel : you mentioned you got widevine working. So does this mean we can now use netflix/

**Comment by codyopel** [comment]
@bluescreen303 
Yes, I got widevine working on the latest version of chromium, but I tore the entire chromium build apart to do it and I am not sure what @aszlig's plans are so I am holding off on adding fixes for it for the time being.

**Comment by bendlas** [comment]
Heads up @aszlig, apparently, chromium is in the process of transitioning their build from `gyp` to something called `gn`, which generates `ninja` build files. I'm no sure how well current versions are already buildable by `gn` but the current stable sure has a BUILD.gn file. Maybe we should keep fixing the current build until we successfully build it by `gn`

### References
https://code.google.com/p/chromiumembedded/issues/detail?id=1403 as well as 1404
https://chromium.googlesource.com/chromium/src/+/master/tools/gn/README.md
https://code.google.com/p/chromium/issues/detail?id=321352

**Comment by aszlig** [comment]
@bendlas: Thanks for the heads up! After experimenting with `gyp2nix`, followed by `cmake2nix` (because gyp is able to generate cmake files), I've now ended up with `ninja2nix`, which I think is probably the most common denominator here, because all of those generators are able to produce ninja rule files. Which in turn would make it not only useful for chromium but a lot of other projects.

**Comment by ambrop72** [comment]
I've made some progress on getting updated versions to build. Commit in my repo: https://github.com/ambrop72/nixpkgs/commit/e2bd4f1879a0b6db7e1e1915344e5f676a178ab0. I'm currently building this and it's at [5821/16605].

Changes:
- Update sources.
- Use gyp package not gyp_svn1977.
- Remove icu from buildInputs, since this causes a build error due to inferference with use_system_icu=false.
- Remove the hack that inserts the absolute path into gyp files, and pass `--depth .` to gyp. This resolves the `third_party/angle` gyp error.
- Do a normal copy of the source code not a symlink copy. This resolves some link error where the symlinks interfere with relative paths (seems like because gyp resolves symlinks first).
- I also changed the bucketURL in update.nix to https.

**Comment by ambrop72** [comment]
With these fixes the latest stable version works for me. I've opened a pull request: https://github.com/NixOS/nixpkgs/pull/8290

**Comment by aszlig** [comment]
Closing in favor of #8290.

**Pull request closed without merging**
