### PR TITLE
dbus_cplusplus: add musl support

### PR DESCRIPTION
**Pull request by wegank**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build pkgsMusl.dbus_cplusplus pkgsMusl.dbus_cplusplus.passthru.tests

**Comment by wegank** [comment]
@ofborg build dbus_cplusplus dbus_cplusplus.passthru.tests

**Comment by superherointj** [comment]
Do you realize how many musl packages you are fixing with this? :-)
About the draft, beyond targeting staging, is there some other change to happen?
I have tested on my host this solution and it works. It builds a ton of musl packages then get stuck somewhere else (spidermonkey, dotnet-aspnetcore). [I'm not asking you to fix these.]
It's good progress.

**Comment by wegank** [comment]
No other changes.

I'm not sure if the first patch is good to apply unconditionally. @cillianderoiste Can this PR target master? The conditions can be removed in another PR on staging.

**Comment by superherointj** [comment]
Master or staging, I would like to have this merged.
As @cillianderoiste has not answered. @wegank, can we go ahead with this?
Or maybe ask somebody else than can answer the doubt?

**Review by alyssais — APPROVED** [review]
I think all patches should be fine to apply unconditionally (but not the define for Darwin).

Please make sure to follow up with unconditionalization on staging.

**Comment by wegank** [comment]
I think I'll drop the darwin part, which isn't really important.

**Review by alyssais — APPROVED** [review]

**Comment by wegank** [comment]
@ofborg build dbus_cplusplus dbus_cplusplus.passthru.tests

**Review by superherointj — APPROVED** [review]

**Pull request merged**
