### PR TITLE
ntfs-3g: remove patch as it been fixed 

### PR DESCRIPTION
**Pull request by marenz2569**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by c0bw3b — CHANGES_REQUESTED** [review]
This patch is not needed anymore because the CVE reported in release `2016.2.22` has been fixed upstream with release `2017.3.23`

**Comment by marenz2569** [comment]
@c0bw3b The requested changes have been applied.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build ntfs3g

**Comment by c0bw3b** [comment]
Result of `nix-review pr 60697`
<details>
  <summary>29 package were build:</summary>

  - atom (gnome2.gvfs ,woeusb)
  - atom-beta (gnome2.gvfs ,woeusb)
  - cantata (gnome2.gvfs ,woeusb)
  - clementine (gnome2.gvfs ,woeusb)
  - clementineUnfree (gnome2.gvfs ,woeusb)
  - far2l (gnome2.gvfs ,woeusb)
  - gvfs (gnome2.gvfs ,woeusb)
  - gnome3.gnome-control-center (gnome2.gvfs ,woeusb)
  - gnome3.gnome-disk-utility (gnome2.gvfs ,woeusb)
  - gnome3.gvfs (gnome2.gvfs ,woeusb)
  - hal-flash (gnome2.gvfs ,woeusb)
  - ntfs3g (gnome2.gvfs ,woeusb)
  - os-prober (gnome2.gvfs ,woeusb)
  - pam_usb (gnome2.gvfs ,woeusb)
  - partclone (gnome2.gvfs ,woeusb)
  - pmount (gnome2.gvfs ,woeusb)
  - psensor (gnome2.gvfs ,woeusb)
  - rabbitvcs (gnome2.gvfs ,woeusb)
  - rapid-photo-downloader (gnome2.gvfs ,woeusb)
  - spaceFM (gnome2.gvfs ,woeusb)
  - testdisk (gnome2.gvfs ,woeusb)
  - testdisk-photorec (gnome2.gvfs ,woeusb)
  - udiskie (gnome2.gvfs ,woeusb)
  - udisks (gnome2.gvfs ,woeusb)
  - usermount (gnome2.gvfs ,woeusb)
  - wimlib (gnome2.gvfs ,woeusb)
  - winusb (gnome2.gvfs ,woeusb)
  - xfce.gigolo (gnome2.gvfs ,woeusb)
  - xfce.gvfs (gnome2.gvfs ,woeusb)
</details>

**Review by c0bw3b — APPROVED** [review]

**Pull request merged**
