### PR TITLE
linuxHeaders: Bump default to 4.15.

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by dtzWill** [comment]
Will binaries built using newer headers have problems executing on older kernels?

**Comment by shlevy** [comment]
No, we set a minimum version for glibc (3.2.0).

**Review by vcunat — APPROVED** [review]
Sounds OK to me.  4.14 would feel more natural, as that's longterm and [we plan to switch to it](https://github.com/NixOS/nixpkgs/issues/31640#issuecomment-365316248), but I know of no downside using 4.15 for headers instead.

**Comment by dtzWill** [comment]
So I re-introduced the notion of different headers as part of musl work, so as to avoid causing problems (or reviewer burden to "prove" such did not exist) on other configurations/architectures/platforms....
This especially made sense as early on I was using either patched 4.14 headers or 4.15 RC's which were particularly poorly motivated as a new default :grin:.

Would it make sense to go back to having single version, now that this is merged?

**Comment by shlevy** [comment]
@dtzWill Might be nice to have it be clear how we can add a new version in the future, but no strong opinions there.

**Pull request merged**
