### PR TITLE
staging-next 2024-06-24

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/316075
##### Mass breakages
- [x] binutils on darwin https://hydra.nixos.org/build/264347232
  https://github.com/NixOS/nixpkgs/pull/322388
- [x] glib on darwin
  https://github.com/NixOS/nixpkgs/pull/322988

### CODE REVIEW

**Comment by doronbehar** [comment]
Scipy version bump from yesterday I hope to get into this cycle:

https://github.com/NixOS/nixpkgs/pull/322340

**Comment by vcunat** [comment]
- [ ] `ffmpeg-full` fails (and maybe other variants) to find cuda_llvm
  https://hydra.nixos.org/build/264744237
  maintainers: @atemu, @jopejoe1

**Comment by Atemu** [comment]
I'm not sure I'll be able to take a look. In the worst case, just disable it for now.

**Comment by doronbehar** [comment]
> * [ ]  `ffmpeg-full` fails (and maybe other variants) to find cuda_llvm
>       [hydra.nixos.org/build/264744237](https://hydra.nixos.org/build/264744237)
>       maintainers: @Atemu, @jopejoe1

Quoting the `ffmpeg-full` error:

```
patching script interpreter paths in ./configure
configure flags: --disable-static --prefix=/nix/store/3mcpqkxq683s4x69jnrxwjsz7r9rarmm-ffmpeg-full-6.1.1 --target_os=linux --arch=x86_64 --pkg-config=pkg-config --enable-gpl --enable-version3 --disable-nonfree --disable-static --enable-shared --enable-pic --disable-thumb --disable-small --enable-runtime-cpudetect --enable-gray --enable-swscale-alpha --enable-hardcoded-tables --enable-safe-bitstream-reader --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --datadir=/nix/store/0y37spkgpdfhi07vsp8fpha27a6pr3h5-ffmpeg-full-6.1.1-data/share/ffmpeg --enable-ffmpeg --enable-ffplay --enable-ffprobe --bindir=/nix/store/cbdcmp64sz30lvhdh3kc6jlbwf3qj5v3-ffmpeg-full-6.1.1-bin/bin --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avutil --enable-postproc --enable-swresample --enable-swscale --libdir=/nix/store/x94nzknlz6l7d5f8wbyyg6bfb43nixr1-ffmpeg-full-6.1.1-lib/lib --incdir=/nix/store/l1si759vpx2ja9dvqdfaklg2458ql5w8-ffmpeg-full-6.1.1-dev/include --enable-doc --enable-htmlpages --enable-manpages --mandir=/nix/store/c11zab6b4f35pp9060fj0p41rvbfksq6-ffmpeg-full-6.1.1-man/share/man --enable-podpages --enable-txtpages --docdir=/nix/store/byxklindxw7g6j7srrk448g4dn4pjwvc-ffmpeg-full-6.1.1-doc/share/doc/ffmpeg --enable-alsa --enable-libaom --disable-appkit --enable-libaribcaption --enable-libass --disable-audiotoolbox --disable-avfoundation --enable-avisynth --enable-libbluray --enable-libbs2b --enable-bzlib --enable-libcaca --enable-libcelt --enable-chromaprint --enable-libcodec2 --disable-coreimage --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-libdav1d --enable-libdc1394 --enable-libdrm --disable-libfdk-aac --enable-ffnvcodec --enable-libflite --enable-fontconfig --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libfribidi --enable-libgme --enable-gnutls --enable-libgsm --enable-libharfbuzz --enable-iconv --enable-libjack --enable-libjxl --enable-ladspa --enable-lzma --disable-metal --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-nvdec --enable-nvenc --enable-openal --enable-opencl --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-opengl --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librtmp --enable-libsmbclient --enable-sdl2 --enable-libshaderc --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-librsvg --enable-libsvtav1 --disable-libtensorflow --enable-libtheora --enable-libtwolame --enable-libv4l2 --enable-v4l2-m2m --enable-vaapi --enable-vdpau --disable-libvpl --disable-videotoolbox --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-vulkan --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxcb --enable-libxcb-shape --enable-libxcb-shm --enable-libxcb-xfixes --enable-xlib --enable-libxml2 --enable-libxvid --enable-libzimg --enable-zlib --enable-libzmq --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
ERROR: cuda_llvm requested but not found
```

[HANDBrake people say we should add clang](https://github.com/HandBrake/HandBrake/issues/4571), but we do it already...

**Comment by K900** [comment]
Fixed that already.

**Comment by vcunat** [comment]
- [ ] `nodejs` on *-darwin still unresolved (maybe PR #262124 addresses that, I don't know)
- [ ] `_7zz.src`: something in `master..staging-next` changed the FOD result, probably as interaction with the custom postFetch

**Comment by vcunat** [comment]
`_7zz`: I think the license interpretation is unnecessarily strict here.  I wouldn't bother with removing the code before hashing.  But feel free to investigate and fix.  Maintainers: @anna328p, @eclairevoyant, @06kellyjac, @peterhoeg

**Comment by doronbehar** [comment]
I've had a bit of trouble fixing the `rocmPackages_6` packages issue with Python3.12 lacking `distutils`. The attempt is at https://github.com/NixOS/nixpkgs/pull/324235 . In any case the package could use an update. CC Maintainers:

@acowley @lovesegfault @Madouura @Flakebi @mschwaig

**Comment by jtojnar** [comment]
No, the version is the same. The archives contain the same files and metadata according to diffoscope but the archive itself is different.

Perhaps we should be using `fetchunzip` instead of re-packing, since the flags we pass to `tar` are clearly not sufficient to ensure deterministic output across versions.

**Comment by tie** [comment]
>- [ ] `nodejs` on *-darwin still unresolved (maybe PR https://github.com/NixOS/nixpkgs/pull/262124 addresses that, I don't know)

The PR builds on *-darwin (and is **ready for review**), so unless there are some other breaking changes in staging-next, it should fix *-darwin and v{18,22} builds for Node.js.

**Comment by eclairevoyant** [comment]
> No, the version is the same. The archives contain the same files and metadata according to diffoscope but the archive itself is different.

Where are you getting this information from? I was just tagged in a message with basically no context :)

> Perhaps we should be using `fetchunzip` instead of re-packing

Good idea.

**Comment by vcunat** [comment]
- [ ] `wolfssl` on aarch64-darwin segfaults during unit tests (repeatedly)
  That would block the `nixpkgs-unstable` channel: https://hydra.nixos.org/build/264903993
  Maintainers: @fabaff, @vifino

**Comment by vcunat** [comment]
Uh
- [ ] `python3Packages.afdko` blocks `trunk-combined`
  https://hydra.nixos.org/build/265208730

**Pull request merged**
