### PR TITLE
flatpak: 1.8.2 → 1.10.1

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change

**Security advisories:**
- https://github.com/flatpak/flatpak/security/advisories/GHSA-4ppf-fxf6-vxg2

﻿Changes:
- https://github.com/flatpak/flatpak/releases/tag/1.9.1
- https://github.com/flatpak/flatpak/releases/tag/1.9.2
- https://github.com/flatpak/flatpak/releases/tag/1.8.4
- https://github.com/flatpak/flatpak/releases/tag/1.9.3
- https://github.com/flatpak/flatpak/releases/tag/1.8.5
- https://github.com/flatpak/flatpak/releases/tag/1.10.0
- https://github.com/flatpak/flatpak/releases/tag/1.10.1

Also:
- Clarify license.
- Re-enable zstd compression (seems to be fixed now).
- Stop introducing GTK to scope through wrapGAppsHook.
- Clean up the DTDs and build tools we managed to fix upstream.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
`flatpak/test-summaries@system.wrap.test` seems to fail for me on this line: https://github.com/flatpak/flatpak/blob/1.10.1/tests/test-summaries.sh#L186

**Comment by jtojnar** [comment]
`flatpak/test-summaries@system.wrap.test` seems to fail for me on this line: https://github.com/flatpak/flatpak/blob/1.10.1/tests/test-summaries.sh#L186


<details>
<summary>Quick repro</summary>

```diff
diff --git a/nixos/tests/installed-tests/default.nix b/nixos/tests/installed-tests/default.nix
index e5d7009bb7b..340b38bc695 100644
--- a/nixos/tests/installed-tests/default.nix
+++ b/nixos/tests/installed-tests/default.nix
@@ -67,7 +67,7 @@ let
             '' +
             ''
               machine.succeed(
-                  "gnome-desktop-testing-runner ${testRunnerFlags} -d '${tested.installedTests}/share'"
+                  "gnome-desktop-testing-runner ${testRunnerFlags} -d '${tested.installedTests}/share' 2>&1"
               )
             '';
         }
diff --git a/nixos/tests/installed-tests/flatpak.nix b/nixos/tests/installed-tests/flatpak.nix
index 8aeeaca90f6..1abcff0fefd 100644
--- a/nixos/tests/installed-tests/flatpak.nix
+++ b/nixos/tests/installed-tests/flatpak.nix
@@ -12,5 +12,5 @@ makeInstalledTest {
     virtualisation.diskSize = 3072;
   };
 
-  testRunnerFlags = "--timeout 3600";
+  testRunnerFlags = "--timeout 3600 flatpak/test-summaries@system.wrap.test";
 }
```

</details>

**Comment by jtojnar** [comment]
Seems to work in a VM though (added flathub repo, installed and launched some software). We should probably merge this now to fix the vulnerability and debug the test later.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111613` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>libsForQt512.discover</li>
<li>libsForQt514.discover</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>pantheon.appcenter: log <a href="https://termbin.com/iezc">https://termbin.com/iezc</a></li>
  </ul>
</details>
<details>
<summary>
10 packages built:
</summary>
<ul>
<li>flatpak</li>
<li>flatpak-builder</li>
<li>gnome-builder</li>
<li>gnome3.gnome-software</li>
<li>libsForQt5.discover (libsForQt515.discover ,plasma5Packages.discover)</li>
<li>malcontent-ui</li>
<li>pantheon.sideload</li>
<li>vala-language-server</li>
<li>xdg-desktop-portal</li>
<li>xdg-desktop-portal-gtk</li>
</ul>
</details>

**Comment by jtojnar** [comment]
The `pantheon.appcenter` failure look unrelated.

**Pull request merged**
