### PR TITLE
dioxus-cli: 0.4.1 -> 0.4.3

### PR DESCRIPTION
**Pull request by benmanns**
FYI this is my first time updating a package. Let me know if I can do anything to make this easier for maintainers!

## Description of changes

* v0.4.2: https://github.com/DioxusLabs/dioxus/releases/tag/v0.4.2
* v0.4.3: https://github.com/DioxusLabs/dioxus/releases/tag/v0.4.2

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by benmanns** [comment]
There are some doc tests that seem to be breaking. Checking on them now.

**Comment by CathalMullan** [comment]
The [README examples](https://github.com/DioxusLabs/dioxus/blob/v0.4.3/packages/cli/README.md?plain=1) are being interpreted as Rust tests by `rustdoc`, since they don't specifiy a language. (e.g. ```sh).

> Please note that by default, if no language is set for the block code, rustdoc assumes it is Rust code. 

```
---- src/lib.rs - (line 32) stdout ----
 error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `install`
  --> src/lib.rs:33:7
   |
 3 | cargo install --path . --debug
   |       ^^^^^^^ expected one of 8 possible tokens
```

We could just disable `doctests` for now.

```nix
# run all tests except doctests
cargoTestFlags = [
  "--lib"
  "--bins"
  "--tests"
];
```

**Comment by benmanns** [comment]
@CathalMullan thanks! I also added `--examples` which _are_ run in the original repository and made a pull request to fix the underlying issue going forward DioxusLabs/dioxus#1706 (at least for dioxus-cli).

**Comment by CathalMullan** [comment]
Result of `nixpkgs-review pr 273172` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dioxus-cli</li>
  </ul>
</details>

**Comment by CathalMullan** [comment]
Result of `nixpkgs-review pr 273172` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dioxus-cli</li>
  </ul>
</details>

**Review by CathalMullan — APPROVED** [review]

**Comment by xanderio** [comment]
Result of `nixpkgs-review pr 273172` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dioxus-cli</li>
  </ul>
</details>

**Review by xanderio — APPROVED** [review]

**Review by CathalMullan — APPROVED** [review]

**Pull request merged**
