### PR TITLE
[Backport release-23.05]: Updates to cargo-deny

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Should we update rustc on the 23.05 release then? It would be 1.69.0 -> 1.71.1 from what I see.

**Comment by 06kellyjac** [comment]
I imagine that'll be a big pain to complete but ive not gone through a rust bump in nixpkgs.
Figsoda might know how feasible thatd be.

Whats the driving force for backporting this update to stable? Just to keep it up to date?

**Comment by matthiasbeyer** [comment]
> Whats the driving force for backporting this update to stable? Just to keep it up to date?

Yep exactly. As it's a patch release, it shouldn't break anyone but only fix bugs, so I figured we might want it.

But on the other hand it seems a lot of hassle, and I suspect that most rust+nix users use flakes and can import cargo-deny from unstable as well. So I'd say lets close this as a "wont do".

**Comment by figsoda** [comment]
It is a patch release and theoretically shouldn't have any breaking changes, but in practice it still ends up breaking things either because of fixing unsoundness, changes to the nightly feature set, or new bugs being introduced. So the usual practice is to not update rust in stable branches. If you really want cargo-deny 0.14.1 in 23.05, consider patching it so it does compile with rust 1.69.0.

**Comment by matthiasbeyer** [comment]
I meant the patch release is for cargo-deny, not rustc :laughing: 

Everything fine with me!

**Pull request closed without merging**
