### PR TITLE
gnome3.nautilus: apply interactive_search.patch (by Daniel Wyatt)

### PR DESCRIPTION
**Pull request by obadz**
Gives user the ability to type ahead to folder without recursively
searching.

Details:
https://bugzilla.gnome.org/show_bug.cgi?id=721968
https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1164016

### CODE REVIEW

**Comment by obadz** [comment]
cc @lethalman

**Comment by lethalman** [comment]
This is not an official feature. Please create a different nautilus attribute with the patch, so that people can override the package.

**Comment by lethalman** [comment]
Better, I think that the user should put this patch somewhere in the filesystem, and simply override nautilus with `.overrideDerivation (attrs: { patches = attrs.patches + ./my.patch; })`. Closing, I'm not going to add this to nixpkgs sorry.

**Comment by obadz** [comment]
Ok, fine.

FWIW, the Ubuntu guys thought fixing this regression (the feature used to be there) was fundamental enough to include.

**Comment by lethalman** [comment]
@obadz ubuntu guys are "thinking" to include or they "did" include?

**Comment by obadz** [comment]
They did include 18 months ago: http://www.webupd8.org/2014/01/nautilus-type-ahead-find-feature.html

**Comment by obadz** [comment]
I got the patch from inside their package..

**Comment by obadz** [comment]
@lethalman,

I'm not sure how to override a recursive derivation like gnome3.  This does not work:

```nix
    packageOverrides = pkgs: rec {
      gnome3 = pkgs.gnome3 // {
        nautilus = pkgs.stdenv.lib.overrideDerivation pkgs.gnome3.nautilus (oldAttrs: {
          patches = oldAttrs.patches ++ [ ./patches/Interactive_search.patch ];
        });
      };
```

How can I fix?

**Comment by lethalman** [comment]
```
packageOverrides = pkgs: rec {
      gnome3 = pkgs.gnome3.overridePackages (self: super: {
        nautilus = super.nautilus.overrideDerivation (oldAttrs: {
          patches = oldAttrs.patches ++ [ ./patches/Interactive_search.patch ];
        });
      });
```

**Comment by vcunat** [comment]
Hmm, I don't see why adding the option wasn't integrated upstream, i.e. all but switching the default, especially when that feature used to be in there until a few years ago. They just discuss it for years now and nothing happens https://bugzilla.gnome.org/show_bug.cgi?id=681871, while the patches *are* available and used all the time in Ubuntu.

Normally I'd stick closer to upstream, but in this case I would favor adding the option (and personally maybe even switching the default, but that's a low priority).

**Comment by obadz** [comment]
@lethalman,

Are you sure about this code? On pkgs.gnome3 I see .override and .overrideDerivation but no .overridePackages.

**Comment by lethalman** [comment]
Update your nixpkgs, it's quite recent.

On Sat, Jul 11, 2015 at 12:59 AM, obadz <notifications@github.com> wrote:

> @lethalman <https://github.com/lethalman>,
>
> Are you sure about this code? On pkgs.gnome3 I see .override and
> .overrideDerivation but no .overridePackages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/8704#issuecomment-120547106>.
>



-- 
NixOS Linux <http://nixos.org>

**Pull request closed without merging**
