### PR TITLE
python311Packages.openai: 1.11.0 -> 1.12.0

### PR DESCRIPTION
**Pull request by fabaff**
Diff: https://github.com/openai/openai-python/compare/refs/tags/v1.11.0...v1.12.0

Changelog: https://github.com/openai/openai-python/releases/tag/v1.12.0

## Description of changes
Fix build (https://hydra.nixos.org/build/249145723)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 287983` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages failed to build:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>maigret</li>
    <li>maigret.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python312Packages.litellm</li>
    <li>python312Packages.litellm.dist</li>
    <li>python312Packages.pyhanko</li>
    <li>python312Packages.pyhanko.dist</li>
    <li>python312Packages.xhtml2pdf</li>
    <li>python312Packages.xhtml2pdf.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>sasview</li>
    <li>sasview.dist</li>
  </ul>
</details>
<details>
  <summary>96 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>datasette (python311Packages.datasette)</li>
    <li>datasette.dist (python311Packages.datasette.dist)</li>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>github-to-sqlite (python311Packages.github-to-sqlite)</li>
    <li>github-to-sqlite.dist (python311Packages.github-to-sqlite.dist)</li>
    <li>home-assistant-component-tests.openai_conversation</li>
    <li>imaginer</li>
    <li>llm (python311Packages.llm)</li>
    <li>llm.dist (python311Packages.llm.dist)</li>
    <li>manim</li>
    <li>manim.dist</li>
    <li>open-interpreter (python311Packages.open-interpreter)</li>
    <li>open-interpreter.dist (python311Packages.open-interpreter.dist)</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.click-default-group</li>
    <li>python311Packages.click-default-group.dist</li>
    <li>python311Packages.datasette-publish-fly</li>
    <li>python311Packages.datasette-publish-fly.dist</li>
    <li>python311Packages.datasette-template-sql</li>
    <li>python311Packages.datasette-template-sql.dist</li>
    <li>python311Packages.fastapi-sso</li>
    <li>python311Packages.fastapi-sso.dist</li>
    <li>python311Packages.greynoise</li>
    <li>python311Packages.greynoise.dist</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.guidance.dist</li>
    <li>python311Packages.image-diff</li>
    <li>python311Packages.image-diff.dist</li>
    <li>python311Packages.karton-mwdb-reporter</li>
    <li>python311Packages.karton-mwdb-reporter.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>python311Packages.mwdblib</li>
    <li>python311Packages.mwdblib.dist</li>
    <li>python311Packages.prisma</li>
    <li>python311Packages.prisma.dist</li>
    <li>python311Packages.resend</li>
    <li>python311Packages.resend.dist</li>
    <li>s3-credentials (python311Packages.s3-credentials)</li>
    <li>s3-credentials.dist (python311Packages.s3-credentials.dist)</li>
    <li>python311Packages.sqlite-migrate</li>
    <li>python311Packages.sqlite-migrate.dist</li>
    <li>sqlite-utils (python311Packages.sqlite-utils)</li>
    <li>sqlite-utils.dist (python311Packages.sqlite-utils.dist)</li>
    <li>python311Packages.ward</li>
    <li>python311Packages.ward.dist</li>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.click-default-group</li>
    <li>python312Packages.click-default-group.dist</li>
    <li>python312Packages.github-to-sqlite</li>
    <li>python312Packages.github-to-sqlite.dist</li>
    <li>python312Packages.greynoise</li>
    <li>python312Packages.greynoise.dist</li>
    <li>python312Packages.image-diff</li>
    <li>python312Packages.image-diff.dist</li>
    <li>python312Packages.karton-mwdb-reporter</li>
    <li>python312Packages.karton-mwdb-reporter.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.mwdblib</li>
    <li>python312Packages.mwdblib.dist</li>
    <li>python312Packages.openai</li>
    <li>python312Packages.openai.dist</li>
    <li>python312Packages.prisma</li>
    <li>python312Packages.prisma.dist</li>
    <li>python312Packages.resend</li>
    <li>python312Packages.resend.dist</li>
    <li>python312Packages.sqlite-migrate</li>
    <li>python312Packages.sqlite-migrate.dist</li>
    <li>python312Packages.sqlite-utils</li>
    <li>python312Packages.sqlite-utils.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
    <li>shot-scraper</li>
    <li>shot-scraper.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 287983` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages failed to build:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>maigret</li>
    <li>maigret.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python312Packages.litellm</li>
    <li>python312Packages.litellm.dist</li>
    <li>python312Packages.pyhanko</li>
    <li>python312Packages.pyhanko.dist</li>
    <li>python312Packages.xhtml2pdf</li>
    <li>python312Packages.xhtml2pdf.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>sasview</li>
    <li>sasview.dist</li>
  </ul>
</details>
<details>
  <summary>96 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>datasette (python311Packages.datasette)</li>
    <li>datasette.dist (python311Packages.datasette.dist)</li>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>github-to-sqlite (python311Packages.github-to-sqlite)</li>
    <li>github-to-sqlite.dist (python311Packages.github-to-sqlite.dist)</li>
    <li>home-assistant-component-tests.openai_conversation</li>
    <li>imaginer</li>
    <li>llm (python311Packages.llm)</li>
    <li>llm.dist (python311Packages.llm.dist)</li>
    <li>manim</li>
    <li>manim.dist</li>
    <li>open-interpreter (python311Packages.open-interpreter)</li>
    <li>open-interpreter.dist (python311Packages.open-interpreter.dist)</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.click-default-group</li>
    <li>python311Packages.click-default-group.dist</li>
    <li>python311Packages.datasette-publish-fly</li>
    <li>python311Packages.datasette-publish-fly.dist</li>
    <li>python311Packages.datasette-template-sql</li>
    <li>python311Packages.datasette-template-sql.dist</li>
    <li>python311Packages.fastapi-sso</li>
    <li>python311Packages.fastapi-sso.dist</li>
    <li>python311Packages.greynoise</li>
    <li>python311Packages.greynoise.dist</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.guidance.dist</li>
    <li>python311Packages.image-diff</li>
    <li>python311Packages.image-diff.dist</li>
    <li>python311Packages.karton-mwdb-reporter</li>
    <li>python311Packages.karton-mwdb-reporter.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>python311Packages.mwdblib</li>
    <li>python311Packages.mwdblib.dist</li>
    <li>python311Packages.prisma</li>
    <li>python311Packages.prisma.dist</li>
    <li>python311Packages.resend</li>
    <li>python311Packages.resend.dist</li>
    <li>s3-credentials (python311Packages.s3-credentials)</li>
    <li>s3-credentials.dist (python311Packages.s3-credentials.dist)</li>
    <li>python311Packages.sqlite-migrate</li>
    <li>python311Packages.sqlite-migrate.dist</li>
    <li>sqlite-utils (python311Packages.sqlite-utils)</li>
    <li>sqlite-utils.dist (python311Packages.sqlite-utils.dist)</li>
    <li>python311Packages.ward</li>
    <li>python311Packages.ward.dist</li>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.click-default-group</li>
    <li>python312Packages.click-default-group.dist</li>
    <li>python312Packages.github-to-sqlite</li>
    <li>python312Packages.github-to-sqlite.dist</li>
    <li>python312Packages.greynoise</li>
    <li>python312Packages.greynoise.dist</li>
    <li>python312Packages.image-diff</li>
    <li>python312Packages.image-diff.dist</li>
    <li>python312Packages.karton-mwdb-reporter</li>
    <li>python312Packages.karton-mwdb-reporter.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.mwdblib</li>
    <li>python312Packages.mwdblib.dist</li>
    <li>python312Packages.openai</li>
    <li>python312Packages.openai.dist</li>
    <li>python312Packages.prisma</li>
    <li>python312Packages.prisma.dist</li>
    <li>python312Packages.resend</li>
    <li>python312Packages.resend.dist</li>
    <li>python312Packages.sqlite-migrate</li>
    <li>python312Packages.sqlite-migrate.dist</li>
    <li>python312Packages.sqlite-utils</li>
    <li>python312Packages.sqlite-utils.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
    <li>shot-scraper</li>
    <li>shot-scraper.dist</li>
  </ul>
</details>

**Review by malob — COMMENTED** [review]
Changes to `openai` LGTM.

**Comment by happysalada** [comment]
It looks like there are a lot of rebuilds, this should probably target staging.

**Comment by happysalada** [comment]
Otherwise this looks good, i dont see anything that jumps out at me.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 287983` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages failed to build:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>datasette (python311Packages.datasette)</li>
    <li>datasette.dist (python311Packages.datasette.dist)</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>python311Packages.datasette-publish-fly</li>
    <li>python311Packages.datasette-publish-fly.dist</li>
    <li>python311Packages.datasette-template-sql</li>
    <li>python311Packages.datasette-template-sql.dist</li>
    <li>python312Packages.litellm</li>
    <li>python312Packages.litellm.dist</li>
    <li>python312Packages.pyhanko</li>
    <li>python312Packages.pyhanko.dist</li>
    <li>python312Packages.xhtml2pdf</li>
    <li>python312Packages.xhtml2pdf.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>sasview</li>
    <li>sasview.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>
<details>
  <summary>94 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>github-to-sqlite (python311Packages.github-to-sqlite)</li>
    <li>github-to-sqlite.dist (python311Packages.github-to-sqlite.dist)</li>
    <li>home-assistant-component-tests.openai_conversation</li>
    <li>imaginer</li>
    <li>llm (python311Packages.llm)</li>
    <li>llm.dist (python311Packages.llm.dist)</li>
    <li>maigret</li>
    <li>maigret.dist</li>
    <li>manim</li>
    <li>manim.dist</li>
    <li>open-interpreter (python311Packages.open-interpreter)</li>
    <li>open-interpreter.dist (python311Packages.open-interpreter.dist)</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.click-default-group</li>
    <li>python311Packages.click-default-group.dist</li>
    <li>python311Packages.fastapi-sso</li>
    <li>python311Packages.fastapi-sso.dist</li>
    <li>python311Packages.greynoise</li>
    <li>python311Packages.greynoise.dist</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.guidance.dist</li>
    <li>python311Packages.image-diff</li>
    <li>python311Packages.image-diff.dist</li>
    <li>python311Packages.karton-mwdb-reporter</li>
    <li>python311Packages.karton-mwdb-reporter.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>python311Packages.mwdblib</li>
    <li>python311Packages.mwdblib.dist</li>
    <li>python311Packages.prisma</li>
    <li>python311Packages.prisma.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.resend</li>
    <li>python311Packages.resend.dist</li>
    <li>s3-credentials (python311Packages.s3-credentials)</li>
    <li>s3-credentials.dist (python311Packages.s3-credentials.dist)</li>
    <li>python311Packages.sqlite-migrate</li>
    <li>python311Packages.sqlite-migrate.dist</li>
    <li>sqlite-utils (python311Packages.sqlite-utils)</li>
    <li>sqlite-utils.dist (python311Packages.sqlite-utils.dist)</li>
    <li>python311Packages.ward</li>
    <li>python311Packages.ward.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.click-default-group</li>
    <li>python312Packages.click-default-group.dist</li>
    <li>python312Packages.github-to-sqlite</li>
    <li>python312Packages.github-to-sqlite.dist</li>
    <li>python312Packages.greynoise</li>
    <li>python312Packages.greynoise.dist</li>
    <li>python312Packages.image-diff</li>
    <li>python312Packages.image-diff.dist</li>
    <li>python312Packages.karton-mwdb-reporter</li>
    <li>python312Packages.karton-mwdb-reporter.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.mwdblib</li>
    <li>python312Packages.mwdblib.dist</li>
    <li>python312Packages.openai</li>
    <li>python312Packages.openai.dist</li>
    <li>python312Packages.prisma</li>
    <li>python312Packages.prisma.dist</li>
    <li>python312Packages.resend</li>
    <li>python312Packages.resend.dist</li>
    <li>python312Packages.sqlite-migrate</li>
    <li>python312Packages.sqlite-migrate.dist</li>
    <li>python312Packages.sqlite-utils</li>
    <li>python312Packages.sqlite-utils.dist</li>
    <li>shot-scraper</li>
    <li>shot-scraper.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> It looks like there are a lot of rebuilds, this should probably target staging.

I removed the commit which triggered the huge amount of rebuild.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 287983` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>python312Packages.litellm</li>
    <li>python312Packages.litellm.dist</li>
    <li>python312Packages.pyhanko</li>
    <li>python312Packages.pyhanko.dist</li>
    <li>python312Packages.xhtml2pdf</li>
    <li>python312Packages.xhtml2pdf.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>sasview</li>
    <li>sasview.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>
<details>
  <summary>100 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>datasette (python311Packages.datasette)</li>
    <li>datasette.dist (python311Packages.datasette.dist)</li>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>github-to-sqlite (python311Packages.github-to-sqlite)</li>
    <li>github-to-sqlite.dist (python311Packages.github-to-sqlite.dist)</li>
    <li>home-assistant-component-tests.openai_conversation</li>
    <li>imaginer</li>
    <li>llm (python311Packages.llm)</li>
    <li>llm.dist (python311Packages.llm.dist)</li>
    <li>maigret</li>
    <li>maigret.dist</li>
    <li>manim</li>
    <li>manim.dist</li>
    <li>open-interpreter (python311Packages.open-interpreter)</li>
    <li>open-interpreter.dist (python311Packages.open-interpreter.dist)</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.click-default-group</li>
    <li>python311Packages.click-default-group.dist</li>
    <li>python311Packages.datasette-publish-fly</li>
    <li>python311Packages.datasette-publish-fly.dist</li>
    <li>python311Packages.datasette-template-sql</li>
    <li>python311Packages.datasette-template-sql.dist</li>
    <li>python311Packages.fastapi-sso</li>
    <li>python311Packages.fastapi-sso.dist</li>
    <li>python311Packages.greynoise</li>
    <li>python311Packages.greynoise.dist</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.guidance.dist</li>
    <li>python311Packages.image-diff</li>
    <li>python311Packages.image-diff.dist</li>
    <li>python311Packages.karton-mwdb-reporter</li>
    <li>python311Packages.karton-mwdb-reporter.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>python311Packages.mwdblib</li>
    <li>python311Packages.mwdblib.dist</li>
    <li>python311Packages.prisma</li>
    <li>python311Packages.prisma.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.resend</li>
    <li>python311Packages.resend.dist</li>
    <li>s3-credentials (python311Packages.s3-credentials)</li>
    <li>s3-credentials.dist (python311Packages.s3-credentials.dist)</li>
    <li>python311Packages.sqlite-migrate</li>
    <li>python311Packages.sqlite-migrate.dist</li>
    <li>sqlite-utils (python311Packages.sqlite-utils)</li>
    <li>sqlite-utils.dist (python311Packages.sqlite-utils.dist)</li>
    <li>python311Packages.ward</li>
    <li>python311Packages.ward.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.click-default-group</li>
    <li>python312Packages.click-default-group.dist</li>
    <li>python312Packages.github-to-sqlite</li>
    <li>python312Packages.github-to-sqlite.dist</li>
    <li>python312Packages.greynoise</li>
    <li>python312Packages.greynoise.dist</li>
    <li>python312Packages.image-diff</li>
    <li>python312Packages.image-diff.dist</li>
    <li>python312Packages.karton-mwdb-reporter</li>
    <li>python312Packages.karton-mwdb-reporter.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.mwdblib</li>
    <li>python312Packages.mwdblib.dist</li>
    <li>python312Packages.openai</li>
    <li>python312Packages.openai.dist</li>
    <li>python312Packages.prisma</li>
    <li>python312Packages.prisma.dist</li>
    <li>python312Packages.resend</li>
    <li>python312Packages.resend.dist</li>
    <li>python312Packages.sqlite-migrate</li>
    <li>python312Packages.sqlite-migrate.dist</li>
    <li>python312Packages.sqlite-utils</li>
    <li>python312Packages.sqlite-utils.dist</li>
    <li>shot-scraper</li>
    <li>shot-scraper.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Some of the failures are related to the missing support for Python 3.12 of `docformatter` and `pyarrow`.

**Pull request merged**
