### PR TITLE
Add vim plugin vim-beancount

### PR DESCRIPTION
**Pull request by siriobalmelli**
Signed-off-by: Sirio Balmelli <sirio@b-ad.ch>

###### Motivation for this change

Needed beancount syntax support; added this to vim-plugins as per usual

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by siriobalmelli** [comment]
rebased onto master and added another plugin ... please feel free to shut me down if that's considered out of line on this project

**Comment by zimbatm** [comment]
@siriobalmelli can you remove the noise from the PR? `git rebase origin/master && git push -f`

**Comment by siriobalmelli** [comment]
cleaned this up, and keep periodically rebasing and pushing ... bump?

**Comment by zimbatm** [comment]
thanks!

**Pull request merged**
