### PR TITLE
zld: init at 1.3.3

### PR DESCRIPTION
**Pull request by rgnns**
###### Motivation for this change
`zld` is a faster linker than Apple's linker.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
I completely agree that we should build it from source. However in the meanwhile, no one has access to it. Let's merge this for now and then when someone has time and motivation we can improve this.

**Comment by happysalada** [comment]
@rgnns could you just rebase your changes when you have a moment ?

**Comment by rgnns** [comment]
Sorry, I hadn't had time to go back to this. I'll rebase and revisit building it later, I think I was close to getting that done.

**Comment by rgnns** [comment]
Unfortunately, seems like I made some cleanup to my Github forks and must have accidentally deleted nixpkgs which had my work. I created a new pull request with the changes: https://github.com/NixOS/nixpkgs/pull/164663

**Pull request closed without merging**
