### PR TITLE
webcord: 4.3.0 -> 4.4.0

### PR DESCRIPTION
**Pull request by huantianad**
## Description of changes
https://github.com/SpacingBat3/WebCord/compare/v4.3.0...v4.4.0
Mostly minor changes and dependency bumps.

Opened as WIP as upstream has updated to electron 26; however, that version is not yet in Nixpkgs, so waiting for that before updating.

@FlafyDev for vencord testing, might be worth waiting for electron 26 before testing tho

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Henry-Hiles — APPROVED** [review]

**Review by NotAShelf — APPROVED** [review]

**Comment by LudovicoPiero** [comment]
Result of `nixpkgs-review pr 249454` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>webcord</li>
    <li>webcord-vencord</li>
  </ul>
</details>

**Comment by huantianad** [comment]
Updated to electron 26, and also removed darwin from `meta.platforms`, as rn it currently doesn't build on darwin, and I don't have the means to maintain it. If anyone on darwin would like to help out with that, lemme know!

**Comment by huantianad** [comment]
Wups forgot to change the electron version in the webcord patch, @FlafyDev is that still needed?

**Comment by LudovicoPiero** [comment]
I think it's okay to remove the override on `webcord-vencord`. I tried to build it without the override and didn't get any segfault.
image

**Review by LudovicoPiero — APPROVED** [review]

**Pull request merged**
