### PR TITLE
imlib2: 1.7.3 -> 1.7.5

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change

Lib update ;
And use the proper license identifier (Imlib2 has its own license which is MIT-derivative)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by risicle** [comment]
On nixos x86_64:

```
builder for '/nix/store/405ivvvg23fzgd37ymxjkvvg16jv9v7i-giblib-1.2.4.drv' failed with exit code 1; last 10 log lines:
  checking whether build environment is sane... yes
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking if malloc debugging is wanted... no
  checking for imlib2-config... no
  checking for imlib2 - version >= 1.0.0... no
  *** The imlib2-config script installed by imlib2 could not be found
  *** If imlib2 was installed in PREFIX, make sure PREFIX/bin is in
  *** your path, or set the IMLIB2_CONFIG environment variable to the
  *** full path to imlib2-config.
  configure: error: Cannot find imlib2: Is imlib2-config in the path?
```

**Comment by c0bw3b** [comment]
I will look into that

**Comment by risicle** [comment]
Otherwise builds `feh` `icewm` `openbox` `libcaca` `sxiv` `qiv` `fluxbox` `w3m` `e16` `wmfs` ... on nixos x86_64

Builds `feh` `libcaca` on macos 10.15

**Comment by c0bw3b** [comment]
So `giblib` is a dead project (no more website, no sources) and the only thing depending on it (`scrot`) was updated upstream to use `imlib2` directly and drop the dependency.

So `scrot` is updated and `giblib` is removed from nixpkgs.

**Pull request merged**
