### PR TITLE
python3Packages.av: fix build

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

Many of the tests depend on sample files fetched over HTTP and they keep adding more. Since they support a caching mechanism, use it to pre‐fetch all the used samples instead.

It might be nice to have a package for the full FATE suite, but it’s over 1 GiB in size so I just did this for now.

Fixes: ca258d2d393eb240fd4eddf9a40093e422c33116

Going to run a full `nixpkgs-review` on a `master`‐based version of this, but it’s probably fine to merge optimistically.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Atemu** [comment]
We might want to reconsider running these tests at all if they require such maintenance overhead or imply huge build time closures.

**Comment by emilazy** [comment]
In this current PR it’s like 16 MiB of samples and one bash script to keep them updated in case they add more; I think it’s fine. The overhead was manually disabling every test that wants a sample file, which should no longer be necessary. There’s upstream issues at https://github.com/PyAV-Org/PyAV/issues/623 and https://github.com/PyAV-Org/PyAV/issues/955 (hi @mweinelt).

At some point it might be nice to run the full FATE test suite against our FFmpeg builds, really, at which point we’d have to start thinking about size.

**Comment by emilazy** [comment]
This breaks Home Assistant’s weird PyAV fork thing… I’ll look into it tomorrow.

**Comment by Atemu** [comment]
cc @mweinelt

**Review by drupol — APPROVED** [review]
nice!

**Comment by emilazy** [comment]
I just talked with @mweinelt on Matrix and we’re going to try replacing Home Assistant’s outdated PyAV fork with the real thing. Will report back on the `nixpkgs-review` results when I have them.

**Comment by emilazy** [comment]
Alright, this has no regressions vs. Hydra on `master` (except `whisper-ctranslate2` which doesn’t look related so it’s probably an issue with my regression testing methodology?). Should be good to merge.

**Pull request merged**
