### PR TITLE
python3Packages.qiskit-terra: fix cargo deps hash

### PR DESCRIPTION
**Pull request by delroth**
## Description of changes

Was not properly updated by c265663f819c1736ff9e7169c72192a7a7d66e61 which last bumped the version of this package. Probably not noticed since the package is marked as broken anyway.

Tested: `nix-build . -A python3Packages.qiskit-terra.cargoDeps`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by delroth** [comment]
cc @mweinelt who introduced the "regression" (if it can even be called one since it's `broken = true` anyway)

(I noticed because my vendored deps scanner is not ignoring `broken` packages at the moment. This seems worth fixing regardless...)

**Comment by mweinelt** [comment]
This is the update-python-libraries update script. It should really skip derivations it cannot properly handle.

**Comment by delroth** [comment]
```
$ grep -lr cargoDeps pkgs/development/python-modules | wc -l
50
```

Yeah... seems kinda dangerous to have tooling not recognize this.

**Comment by mweinelt** [comment]
Can you set `meta.broken = pythonAtLeast "3.11"` instead? The native code has not been updated for 3.11.

**Comment by delroth** [comment]
Done.

@ofborg build python310Packages.qiskit-terra

**Comment by mweinelt** [comment]
16 minutes in :tired_face: 

```
qiskit-terra> ============================= test session starts ==============================
qiskit-terra> platform linux -- Python 3.10.13, pytest-7.4.3, pluggy-1.3.0
qiskit-terra> rootdir: /nix/store/safwl7zzf7gcajivg1jgwclza9n93f2v-python3.10-qiskit-terra-0.25.1/lib/python3.10/site-packages
qiskit-terra> plugins: hypothesis-6.84.3
qiskit-terra> collected 21730 items / 433 deselected / 21297 selected                        
qiskit-terra> 
qiskit-terra> test/python/test_examples.py s                                           [  0%]
qiskit-terra> test/python/test_qasm_parser.py .......                                  [  0%]
qiskit-terra> test/python/test_user_config.py .............                            [  0%]
qiskit-terra> test/python/test_util.py ..                                              [  0%]
qiskit-terra> test/python/test_version.py .                                            [  0%]
qiskit-terra> test/python/algorithms/test_amplitude_estimators.py .................... [  0%]
qiskit-terra> ........................................                                 [  0%]
qiskit-terra> test/python/algorithms/test_aux_ops_evaluator.py ....                    [  0%]
qiskit-terra> test/python/algorithms/test_backendv1.py s..                             [  0%]
qiskit-terra> test/python/algorithms/test_backendv2.py ..                              [  0%]
qiskit-terra> test/python/algorithms/test_entangler_map.py ...                         [  0%]
qiskit-terra> test/python/algorithms/test_grover.py .................................. [  0%]
qiskit-terra> ................................                                         [  0%]
qiskit-terra> test/python/algorithms/test_measure_error_mitigation.py ssssssssssssss   [  0%]
qiskit-terra> test/python/algorithms/test_numpy_eigen_solver.py ............           [  0%]
qiskit-terra> test/python/algorithms/test_numpy_minimum_eigen_solver.py ..........     [  0%]
qiskit-terra> test/python/algorithms/test_observables_evaluator.py ........            [  0%]
qiskit-terra> test/python/algorithms/test_phase_estimator.py ......................... [  1%]
qiskit-terra> ............................                                             [  1%]
qiskit-terra> test/python/algorithms/test_qaoa.py ...................                  [  1%]
qiskit-terra> test/python/algorithms/test_skip_qobj_validation.py .s.                  [  1%]
qiskit-terra> test/python/algorithms/test_validation.py ....                           [  1%]
qiskit-terra> test/python/algorithms/test_vqd.py s.....s..s.......sss                  [  1%]
qiskit-terra> test/python/algorithms/test_vqe.py .s..........s...........ssssssss      [  1%]
qiskit-terra> test/python/algorithms/eigensolvers/test_numpy_eigensolver.py .......... [  1%]
qiskit-terra> ................                                                         [  1%]
qiskit-terra> test/python/algorithms/eigensolvers/test_vqd.py ........................ [  1%]
```

**Comment by mweinelt** [comment]
Tests completed after 46 minutes. @drewrisinger do you still care about qiskit in nixpkgs?

```
qiskit-terra> FAILED test/python/circuit/test_parameters.py::TestParameterExpressions::test_complex_parameter_bound_to_real - qiskit.circuit.exceptions.CircuitError: "Invalid param type <class 'complex...
qiskit-terra> FAILED test/python/circuit/test_parameters.py::TestParameterExpressions::test_expressions_of_parameter_with_constant - AssertionError: (1.408343819019456e-16+2.3j) != 2.3j
qiskit-terra> FAILED test/python/primitives/test_backend_estimator.py::TestBackendEstimator::test_bound_pass_manager - AssertionError: 0 != 2
qiskit-terra> FAILED test/python/primitives/test_backend_sampler.py::TestBackendSampler::test_bound_pass_manager - AssertionError: 0 != 2
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_6095 - AssertionError: 0.9994374927033252 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_alternative_colors - AssertionError: 0.9995340771892295 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_barrier_label - AssertionError: 0.999046559669474 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_big_gates - AssertionError: 0.9976004424462999 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_bit_conditional_with_cregbundle - AssertionError: 0.9975495633584092 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_bw - AssertionError: 0.9996773543053035 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_calibrations - AssertionError: 0.999767870131076 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_calibrations_with_control_gates - AssertionError: 0.9983131896191523 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_calibrations_with_rzz_and_rxx - AssertionError: 0.9980991468850211 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_calibrations_with_swap_and_reset - AssertionError: 0.9989448903417824 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_cnot - AssertionError: 0.999777183600713 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_conditional - AssertionError: 0.9992739446987879 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_conditional_gates_right_of_measures_with_bits - AssertionError: 0.999692392875819 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_conditions_measures_with_bits - AssertionError: 0.9997890859706161 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_conditions_with_bits_reverse - AssertionError: 0.9988371336875486 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_creg_initial - AssertionError: 0.9989719118559901 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_cswap_rzz - AssertionError: 0.9986368571632364 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_ctrl_labels - AssertionError: 0.9945965881023434 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_cz - AssertionError: 0.9987988658586925 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_figwidth - AssertionError: 0.9995465342258691 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_fold_4 - AssertionError: 0.9998495788206979 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_fold_minus1 - AssertionError: 0.999884235055119 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_fold_with_conditions - AssertionError: 0.9663832520369023 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_for_loop_op - AssertionError: 0.9996758305400945 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_ghz_to_gate - AssertionError: 0.9975189618455147 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_idle_wires_barrier - AssertionError: 0.9992740817627003 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_if_else_op - AssertionError: 0.9994871507963149 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_if_else_op_fold - AssertionError: 0.9996876569370782 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_if_else_op_nested - AssertionError: 0.9997431400683778 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_if_else_op_textbook_style - AssertionError: 0.9994871507963149 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_if_else_op_wire_order - AssertionError: 0.9997431400683778 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_if_else_with_body - AssertionError: 0.9995281025496549 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_if_op - AssertionError: 0.9992859775198084 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_init_reset - AssertionError: 0.9984021817330054 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_instruction_1q_1c - AssertionError: 0.9995421028531729 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_instruction_3q_3c_circ1 - AssertionError: 0.9980062215496223 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_instruction_3q_3c_circ2 - AssertionError: 0.9980062215496223 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_instruction_3q_3c_circ3 - AssertionError: 0.9982069000212009 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_long_name - AssertionError: 0.9956313854827863 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_meas_condition - AssertionError: 0.9992365779755705 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_measures_with_conditions - AssertionError: 0.9977811428691611 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_multi_underscore_reg_names - AssertionError: 0.997063053454851 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_no_barriers_false - AssertionError: 0.9996943185411616 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_no_ops - AssertionError: 0.9996249741361474 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_one_bit_regs - AssertionError: 0.9997739743110113 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_overwide_gates - AssertionError: 0.9985308097830784 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_partial_layout - AssertionError: 0.9977666658932176 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_pauli_clifford - AssertionError: 0.9996530372584606 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_pi_param_expr - AssertionError: 0.9985383244206774 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_plot_barriers - AssertionError: 0.999853780529617 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_plot_partial_barrier - AssertionError: 0.999823131907004 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_r_gates - AssertionError: 0.9978132317339365 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_registerless_one_bit - AssertionError: 0.9998620689655172 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_reverse_bits - AssertionError: 0.9996889561123173 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_reverse_bits_condition - AssertionError: 0.9991785018100807 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_scale - AssertionError: 0.9985310485205202 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_sidetext_with_condition - AssertionError: 0.9988529171293641 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_style_custom_gates - AssertionError: 0.9979747530657604 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_subfont_change - AssertionError: 0.9996279671147325 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_switch_case_op - AssertionError: 0.9994816535466942 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_user_ax_subplot - AssertionError: 0.9997418501862538 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_user_style - AssertionError: 0.9995563604540925 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_while_loop_op - AssertionError: 0.9997317475377248 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_wire_order - AssertionError: 0.999119871460297 not greater than or equal to 0.9999
qiskit-terra> FAILED test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py::TestCircuitMatplotlibDrawer::test_with_global_phase - AssertionError: 0.9983295597484276 not greater than or equal to 0.9999
qiskit-terra> = 69 failed, 20912 passed, 311 skipped, 433 deselected, 5 xfailed, 1388 warnings in 2774.30s (0:46:14) =

**Pull request merged**
