### PR TITLE
python310Packages.spsdk: fix build by relaxing versions

### LINKED ISSUE #204333: pynitrokey fails to build
### Steps To Reproduce
1. build `pynitrokey`

### Build log
```
[ 47%] Building C object CMakeFiles/nrf_ble_driver_obj_sd_api_v2.dir/src/sd_api_v2/sdk/components/serialization/application/codecs/s130/serializers/ble_gattc_primary_services_discover.c.o
[ 47%] Building CXX object CMakeFiles/nrf_ble_driver_obj_sd_api_v6.dir/src/common/transport/uart_transport.cpp.o
[ 48%] Building C object CMakeFiles/nrf_ble_driver_obj_sd_api_v2.dir/src/sd_api_v2/sdk/components/serialization/application/codecs/s130/serializers/ble_gattc_read.c.o
Processing ./spsdk-1.6.3-py3-none-any.whl
Requirement already satisfied: commentjson<1,>=0.9 in /nix/store/w9ga8a83hy4c3m9y0qplfy150g2hc7nf-python3.10-commentjson-0.9.0/lib/python3.10/site-packages (from spsdk==1.6.3) (0.9.0)
Requirement already satisfied: pypemicro<0.2.0,>=0.1.9 in /nix/store/8i7whx2xbd6cgcmd1f0rpkrh5mbgzn21-python3.10-pypemicro-0.1.9/lib/python3.10/site-packages (from spsdk==1.6.3) (0.1.9)
Requirement already satisfied: libusbsio>=2.1.11 in /nix/store/903jky94asmbdnfz0arxi6yy8ydsk3pg-python3.10-libusbsio-2.1.11/lib/python3.10/site-packages (from spsdk==1.6.3) (2.1.11)
Requirement already satisfied: fastjsonschema>=2.15.1 in /nix/store/igan2imwkz1xjjm2p4rvrs8g0hrq0baf-python3.10-fastjsonschema-2.16.2/lib/python3.10/site-packages (from spsdk==1.6.3) (2.16.2)
Requirement already satisfied: click<8.2,>=7.1 in /nix/store/acc0azvasyw0gg1b25bpnhb94c6c0z33-python3.10-click-8.1.3/lib/python3.10/site-packages (from spsdk==1.6.3) (8.1.3)
Requirement already satisfied: crcmod==1.7 in /nix/store/pjichbcnbcsn2y1alkjgp811p076yjy2-python3.10-crcmod-1.7/lib/python3.10/site-packages (from spsdk==1.6.3) (1.7)
Requirement already satisfied: cmsis-pack-manager in /nix/store/274i5jd3aa16cmpkpn6xfhds2vfhjqr3-python3.10-cmsis-pack-manager-0.4.0/lib/python3.10/site-packages (from spsdk==1.6.3) (0.4.0)
Requirement already satisfied: pyocd in /nix/store/qw469nx76yx1a49b5a486kikd5af2rja-python3.10-pyocd-0.34.1/lib/python3.10/site-packages (from spsdk==1.6.3) (0.0.0)
Requirement already satisfied: asn1crypto<2,>=1.2 in /nix/store/kxq55c067dyb2yc0r784vnnz85nzds1b-python3.10-asn1crypto-1.5.1/lib/python3.10/site-packages (from spsdk==1.6.3) (1.5.1)
Requirement already satisfied: click-option-group<0.6,>=0.3.0 in /nix/store/ih8b10r6krrahmmlycpwz3vh2fh8d6cd-python3.10-click-option-group-0.5.5/lib/python3.10/site-packages (from spsdk==1.6.3) (0.5.5)
Requirement already satisfied: deepmerge in /nix/store/hvl065srk564bw5wdvik6i9icz6j2mr2-python3.10-deepmerge-1.0.1/lib/python3.10/site-packages (from spsdk==1.6.3) (1.0.1)
Requirement already satisfied: jinja2 in /nix/store/c3p6yihd35mpgqgxx5jmdvsz59bf9h4g-python3.10-Jinja2-3.1.2/lib/python3.10/site-packages (from spsdk==1.6.3) (3.1.2)
Requirement already satisfied: pylink-square in /nix/store/j43a8iz48s0badbc08pcxqbxplh5w6pc-python3.10-pylink-square-0.14.2/lib/python3.10/site-packages (from spsdk==1.6.3) (0.14.2)
Requirement already satisfied: pycryptodome<4,>=3.9.3 in /nix/store/m4h033jjb4r3b8daywbi49f8gr2qwnjj-python3.10-pycryptodome-3.15.0/lib/python3.10/site-packages (from spsdk==1.6.3) (3.15.0)
Requirement already satisfied: sly==0.4 in /nix/store/ndbafpnf70zsh617d9cy8gar1wb6a1yl-python3.10-sly-0.4/lib/python3.10/site-packages (from spsdk==1.6.3) (0.4)
Requirement already satisfied: bitstring<3.2,>=3.1 in /nix/store/ha1aidz9730488ry0y766xrwcbyrk5vj-python3.10-bitstring-3.1.9/lib/python3.10/site-packages (from spsdk==1.6.3) (3.1.9)
Requirement already satisfied: hexdump~=3.3 in /nix/store/0kqhggg60v5z3qniwnd3xbjbl37q5ssh-python3.10-hexdump-3.3/lib/python3.10/site-packages (from spsdk==1.6.3) (3.3)
Requirement already satisfied: colorama<1,>=0.4.4 in /nix/store/lqcrqp828a76av6qpb2a3h722lli0dl5-python3.10-colorama-0.4.6/lib/python3.10/site-packages (from spsdk==1.6.3) (0.4.6)
ERROR: Could not find a version that satisfies the requirement bincopy<17.11 (from spsdk) (from versions: none)
ERROR: No matching distribution found for bincopy<17.11
[ 48%] Building CXX object CMakeFiles/nrf_ble_driver_obj_sd_api_v6.dir/src/common/platform/linux/serial_port_enum.cpp.o
[ 48%] Building C object CMakeFiles/nrf_ble_driver_obj_sd_api_v2.dir/src/sd_api_v2/sdk/components/serialization/application/codecs/s130/serializers/ble_gattc_relationships_discover.c.o

error: builder for '/nix/store/wqb6yk9vl9yvws8yvblz1gz9mbcvk9zl-python3.10-spsdk-1.6.3.drv' failed with exit code 1;
       last 10 log lines:
       > Requirement already satisfied: jinja2 in /nix/store/c3p6yihd35mpgqgxx5jmdvsz59bf9h4g-python3.10-Jinja2-3.1.2/lib/python3.10/site-packages (from spsdk==1.6.3) (3.1.2)
       > Requirement already satisfied: pylink-square in /nix/store/j43a8iz48s0badbc08pcxqbxplh5w6pc-python3.10-pylink-square-0.14.2/lib/python3.10/site-packages (from spsdk==1.6.3) (0.14.2)
       > Requirement already satisfied: pycryptodome<4,>=3.9.3 in /nix/store/m4h033jjb4r3b8daywbi49f8gr2qwnjj-python3.10-pycryptodome-3.15.0/lib/python3.10/site-packages (from spsdk==1.6.3) (3.15.0)
       > Requirement already satisfied: sly==0.4 in /nix/store/ndbafpnf70zsh617d9cy8gar1wb6a1yl-python3.10-sly-0.4/lib/python3.10/site-packages (from spsdk==1.6.3) (0.4)
       > Requirement already satisfied: bitstring<3.2,>=3.1 in /nix/store/ha1aidz9730488ry0y766xrwcbyrk5vj-python3.10-bitstring-3.1.9/lib/python3.10/site-packages (from spsdk==1.6.3) (3.1.9)
       > Requirement already satisfied: hexdump~=3.3 in /nix/store/0kqhggg60v5z3qniwnd3xbjbl37q5ssh-python3.10-hexdump-3.3/lib/python3.10/site-packages (from spsdk==1.6.3) (3.3)
       > Requirement already satisfied: colorama<1,>=0.4.4 in /nix/store/lqcrqp828a76av6qpb2a3h722lli0dl5-python3.10-colorama-0.4.6/lib/python3.10/site-packages (from spsdk==1.6.3) (0.4.6)
       > ERROR: Could not find a version that satisfies the requirement bincopy<17.11 (from spsdk) (from versions: none)
       > ERROR: No matching distribution found for bincopy<17.11
       > 
       For full logs, run 'nix log /nix/store/wqb6yk9vl9yvws8yvblz1gz9mbcvk9zl-python3.10-spsdk-1.6.3.drv'.
error (ignored): error: cannot unlink '/tmp/nix-build-pc-ble-driver-4.1.4.drv-0/source/build/CMakeFiles/nrf_ble_driver_obj_sd_api_v6.dir/src/sd_api_v6': Directory not empty
error: 1 dependencies of derivation '/nix/store/c9d4wm5yblbg69rfpr8yzazbbv8zxb4m-pynitrokey-0.4.27.drv' failed to build
```

### Notify maintainers

@frogamic 

### Metadata

```console
- host os: `Linux 6.0.9, NixOS, 23.05 (Stoat), 23.05.git.8bbe1bb1f73`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/home/raito/dev/github.com/NixOS/nixpkgs`
```

I will submit a PR shortly once I am back on my laptop.

### PR DESCRIPTION
**Pull request by tjni**
Fixes https://github.com/NixOS/nixpkgs/issues/204333.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
The check failures look related to the fact that this package depends on unfree packages.

**Comment by tjni** [comment]
Fixes https://github.com/NixOS/nixpkgs/issues/204333.

**Review by sbruder — APPROVED** [review]
This fixes the build error, though I can’t test if it works on real hardware.

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 203343` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python39Packages.spsdk</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>pynitrokey</li>
    <li>python310Packages.spsdk</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
For Python 3.9:
```
error: build of '/nix/store/7lcrygki8f6jlhljiimi13d2b4raak70-python3.9-spsdk-1.6.3.drv' on 'ssh://nix-community-build01' failed: builder for '/nix/store/7lcrygki8f6jlhljiimi13d2b4raak70-python3.9-spsdk-1.6.3.drv' failed with exit code 1;
       last 10 log lines:
       > configuring
       > no configure script, doing nothing
       > building
       > Executing setuptoolsBuildPhase
       > usage: nix_run_setup [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       >    or: nix_run_setup --help [cmd1 cmd2 ...]
       >    or: nix_run_setup --help-commands
       >    or: nix_run_setup cmd --help
       >
       > error: invalid command 'bdist_wheel'
       For full logs, run 'nix log /nix/store/7lcrygki8f6jlhljiimi13d2b4raak70-python3.9-spsdk-1.6.3.drv'.
error: builder for '/nix/store/7lcrygki8f6jlhljiimi13d2b4raak70-python3.9-spsdk-1.6.3.drv' failed with exit code 1;
       last 10 log lines:
       > configuring
       > no configure script, doing nothing
       > building
       > Executing setuptoolsBuildPhase
       > usage: nix_run_setup [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       >    or: nix_run_setup --help [cmd1 cmd2 ...]
       >    or: nix_run_setup --help-commands
       >    or: nix_run_setup cmd --help
       >
       > error: invalid command 'bdist_wheel'
       For full logs, run 'nix log /nix/store/7lcrygki8f6jlhljiimi13d2b4raak70-python3.9-spsdk-1.6.3.drv'.
error: 1 dependencies of derivation '/nix/store/bicqydc8as91f1g107lc4zvz4sgbk3ks-review-shell.drv' failed to build
```

**Comment by tjni** [comment]
Great catch! This is something I don't have a grasp on just yet, so I will ask for help on Matrix.

**Comment by tjni** [comment]
I tracked this down to because `pyocd` is packaged using `python3.callPackage`. Somehow, this corrupts the PYTHONPATH when building packages that depend upon it (like spsdk) using other versions of Python.

@sbruder would it be ok if I moved `pyocd` underneath `python-modules`?

**Comment by tjni** [comment]
I moved `pyocd` to `python-modules` and kept an alias to it in the top-level. From its GitHub README, it looks like it also provides a command line tool as an application.

@ofborg build python310Packages.spsdk python39Packages.spsdk

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 203343` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>pynitrokey</li>
    <li>python310Packages.pyocd</li>
    <li>python310Packages.spsdk</li>
    <li>python39Packages.pyocd</li>
    <li>python39Packages.spsdk</li>
  </ul>
</details>

**Review by RaitoBezarius — APPROVED** [review]
Thanks a lot!

**Pull request merged**
