### PR TITLE
network-interfaces.nix: escape '.' in interface names passed to sysctl

### PR DESCRIPTION
**Pull request by volth**
https://github.com/NixOS/nixpkgs/pull/62835#pullrequestreview-285094670

@lheckemann

### CODE REVIEW

**Comment by lheckemann** [comment]
It needing the absolute path to echo seems odd to me. Does it not go through the shell? echo should be a shell built-in, and if it's not going through the shell I don't see why the redirection would work…

**Comment by volth** [comment]
Without absolute path `nixos-rebuild` failed with
```
Checking that all programs called by relative paths in udev rules exist in /nix/store/mmn59rl0zcgxk6rwynwambh9286q4dbv-systemd-242/lib/udev... FAIL   
echo is called in udev rules but not installed by udev
```

**Comment by volth** [comment]
Should we merge it or fix in another way?
It is clearly a bug.
NixOS's `tinc` module creates interfaces with `.` in name and `sysctl` fails when both `tinc` and IPv6 are enabled

**Comment by lheckemann** [comment]
Sorry for the delay!

**Comment by lheckemann** [comment]
Cherry-picked to 19.09: 4dceeaad80b2783887ab0a41adecd9c8a8ddaf82 ee08175952f95edf6fb4107f4d817113ec0dd284

**Comment by vcunat** [comment]
This PR broke IPv6 tests and thus is blocking all the channels.  19.09 link: https://hydra.nixos.org/job/nixos/release-19.09/nixos.tests.ipv6.x86_64-linux

**Comment by conferno** [comment]
It could be only
```diff
- ${pkgs.psutils}/bin/sysctl net.ipv6.conf.%k.use_tempaddr=2
+ ${pkgs.coreutils}/bin/echo 2 > /proc/sys/net/ipv6/conf/%k/use_tempaddr
```
the rest changes must have no effect if interface name has no `.`

I would try
```diff
- ${pkgs.coreutils}/bin/echo 2 > /proc/sys/net/ipv6/conf/%k/use_tempaddr
+ ${pkgs.coreutils}/bin/echo -n 2 > /proc/sys/net/ipv6/conf/%k/use_tempaddr
```

If it does help:
```diff
+ ${pkgs.psutils}/bin/sysctl net.ipv6.conf.$(${pkgs.coreutils}/bin/echo -n %k | ${pkgs.coreutils}/bin/tr . /).use_tempaddr=2
```

**Comment by vcunat** [comment]
None of those worked when I tried them.  I thought perhaps it isn't interpreted by bash, but using `tee` instead of `echo` didn't help either.

**Comment by conferno** [comment]
Maybe
`${pkgs.bash}/bin/bash -c "echo -n 2 > ..."`

**Comment by vcunat** [comment]
Thanks!  That approach did work, so I pushed it to both branches.  I didn't try it before because I thought `tee` would essentially do the same and that didn't work for me...

**Pull request merged**
