### PR TITLE
nixos/nftables: add checkRuleset option

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Description of changes

Frequent failure case when fiddling with firewall rules is that the ruleset has invalid syntax and can not be loaded.
Usually this would result in the firewall failing to load at run-time, which means the host is unprotected and possibly forwarding arbitrary packets.
In the worst case it goes unnoticed.

This makes an effort to catch syntax errors in the nftables ruleset by loading them once in advance and failing the entire build when this fails.

Because nftables is fully implemented in the kernel, the LKL hijack library is used to run this in the build sandbox environment and without any special privilges.

Example output:
```
error: builder for '/nix/store/47mms8ylfhmc2jk40msgahmgxqffb7jf-nftables-rules.drv' failed with exit code 1;
       last 3 log lines:
       > ruleset.conf:6:5-16: Error: meta nfproto is only useful in the inet family
       >     meta nfproto ipv6 tcp flags syn tcp option maxseg size 1305-65535 tcp option maxseg size set 1304
       >     ^^^^^^^^^^^^
       For full logs, run 'nix log /nix/store/47mms8ylfhmc2jk40msgahmgxqffb7jf-nftables-rules.drv'.
error: 1 dependencies of derivation '/nix/store/hj42f7cr3fvhxnxal8hh74hkr0xay1h0-unit-nftables.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/640k9r9wwjimwihplhjha07c7y05p2wm-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vglbvcai4winwnp1k1wmw8fziar8ibsp-etc.drv' failed to build

```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yu-re-ka** [comment]
@ofborg build lkl

**Comment by vtuan10** [comment]
Thanks for the added checks, this is certainly helpful!

Some options such as `CONFIG_NFT_COUNTER=y` are removed in this PR. 
Is there a reason to remove these configs? I use counters in my ruleset which ultimately fails on these checks, is there a way to use counters and have these checks enabled?

**Comment by yu-re-ka** [comment]
I completely regenerated the options based on the NixOS kernel config, which apparently does not have this option: 

```
$ zcat /proc/config.gz | grep NFT_COUNTER

$
```

Was this option possibly renamed in a more recent kernel version? Does this feature work on the default NixOS kernel? We should match whatever the nixos kernel supports as closely as possible in my opinion.

Otherwise there is always the option to disable the checks.

**Comment by yu-re-ka** [comment]
Yup this option is not necessary anymore in very recent versions of linux: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/net/netfilter?h=v6.2.2&id=023223dfbfb34fcc9b7dd41e21fbf9a5d5237989

But lkl is now based on 5.15, which still needs it, and so should be enabled! Thanks for reporting this issue (:

**Comment by mweinelt** [comment]
Hey @yu-re-ka, thanks for this awesome change. I think it should come with a release notes entry.

**Comment by mweinelt** [comment]
Looks like this regressed on aarch64-linux on staging-next, which will turn into a channel blocker unless fixed.

https://hydra.nixos.org/build/211742721
https://hydra.nixos.org/build/211742732

```
/nix/store/40ic8f7lwjdrrllx2m08nd8xy0dmmafs-nftables-1.0.6/bin/nft: symbol lookup error: /nix/store/a5jx2bxmv7xy00vb1y02i3i0l0590008-lkl-2022-08-08-lib/lib/liblkl-hijack.so: undefined symbol: __aarch64_ldadd4_sync
```

**Comment by yu-re-ka** [comment]
> Looks like this regressed on aarch64-linux on staging-next, which will turn into a channel blocker unless fixed.

`nixos.tests.nat.nftables.standalone.aarch64-linux` test succeeds on master

**Comment by yu-re-ka** [comment]
Ah, it is the gcc12 upgrade

**Comment by yu-re-ka** [comment]
Alternatively, `NIX_CFLAGS_COMPILE = "-mno-outline-atomics";`

**Comment by K900** [comment]
Maybe `LDFLAGS="-lgcc_s"`?

**Comment by yu-re-ka** [comment]
LDFLAGS does not work but `NIX_CFLAGS_LINK = "-lgcc_s";` does

**Comment by yu-re-ka** [comment]
@mweinelt why not `-lgcc_s`?

**Comment by mweinelt** [comment]
Sorry, I just used +-1 to annotate, what was working in my tests.

**Comment by yu-re-ka** [comment]
> Overriding the stdenv surprisingly did not.

probably it was not applied to lklWithFirewall since that's a separate callPackage

**Comment by mweinelt** [comment]
That must be it.

**Comment by jian-lin** [comment]
@mweinelt 

> I think it should come with a release notes entry.

I encountered a checking error of my nftable ruleset.  A release note will be very helpful. I added one in https://github.com/NixOS/nixpkgs/pull/223283.

**Comment by tilpner** [comment]
I'm getting this error (with a different filename)

```
nft.conf:111:7-13: Error: Could not process rule: No such file or directory
chain ingress {
      ^^^^^^^
```

on aaef163eac75c2ac7f882c1fae4e0c08aa18d186. Unfortunately, it seems strace-ing the `nft --check --file` is difficult with the `LD_PRELOAD` (`strace: fcntl(512, F_GETFD): Bad file descriptor`), so I can't tell which file is missing.

**Comment by K900** [comment]
You might just be on a really old kernel.

**Comment by tilpner** [comment]
@K900 my host kernel is 6.1.34, but I'm not sure that matters with the LKL-based verification?

**Comment by Mic92** [comment]
Spawning an actual VM would help getting kernels into sync... We might have to see though how slow that is if a builder has no KVM support. Might be acceptable though.

**Pull request merged**
