### PR TITLE
imgbrd-grabber: 7.5.1 -> 7.6.2

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mkg20001** [comment]
Rebased, also getting the segfault after building.

**Comment by mkg20001** [comment]
qscintilla seems to be causing the segfault, I disabled that now.

**Comment by evanjs** [comment]
> qscintilla seems to be causing the segfault, I disabled that now.

Spoke to @bionus and they mentioned that Grabber doesn't currently include QScintilla on Linux, anyway, so this should be fine :+1:

**Comment by evanjs** [comment]
@mkg20001 Okay, this took me _way_ longer than it should have....
```
> nix search qscintilla

* nixos.qscintilla (qscintilla-qt4)
  A Qt port of the Scintilla text editing library

* nixpkgs.libsForQt5.qscintilla (qscintilla-qt5)
  A Qt port of the Scintilla text editing library
  ```
  
It looks like `qscintilla` refers to `qscintilla-qt4`
If we match Qt versions by using `libsForQt5.qscintilla`, the application seems to run fine

**Comment by mkg20001** [comment]
@evanjs oh well that make sense :rofl: 

maybe it would be good if the other package would get renamed to qscintilla4

**Comment by evanjs** [comment]
> @evanjs oh well that make sense 🤣
> 
> maybe it would be good if the other package would get renamed to qscintilla4

I agree; `python` -> `python2` is one thing, but from what I've seen, the Qt ecosystem on nixpkgs right now is probably better off defaulting to Qt5.  No idea what/if that would impact, if anything, though.

Also unsure how best to reference `qscintilla-qt5` in this case.

`qscintilla = libsForQt5.qscintilla` in `top-level/all-packages.nix` and import/add `qscintilla` to `nativeBuildInputs`?
Import `libsForQt5` and add `libsForQt5.qscintilla` to `nativeBuildInputs`? etc.

**Comment by evanjs** [comment]
Not critical for this PR, I don't think, but I was able to compile with Breakpad after updating `gui/CMakeLists.txt`:

Here is what it looks like with the aforementioned `libsForQt5.qscintilla` reference in `top-level/all-packages.nix`:

<details>
<summary><code>top-level/all-packages.nix</code></summary>

```patch
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index a86c88a068b..e61c78ba332 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -25836,6 +25836,7 @@ with pkgs;

   imgbrd-grabber = qt5.callPackage ../applications/graphics/imgbrd-grabber/default.nix {
     typescript = nodePackages.typescript;
+    qscintilla = libsForQt5.qscintilla;
   };

   imgcat = callPackage ../applications/graphics/imgcat { };
```

</details>

<details>
<summary><code>default.nix</code></summary>

```patch
diff --git a/pkgs/applications/graphics/imgbrd-grabber/default.nix b/pkgs/applications/graphics/imgbrd-grabber/default.nix
index e9a94d65d78..e583f43f0c2 100644
--- a/pkgs/applications/graphics/imgbrd-grabber/default.nix
+++ b/pkgs/applications/graphics/imgbrd-grabber/default.nix
@@ -18,6 +18,7 @@
 , openssl
 , rsync
 , typescript
+, breakpad
 }:

 stdenv.mkDerivation rec {
@@ -37,11 +38,11 @@ stdenv.mkDerivation rec {
     makeWrapper
     libpulseaudio
     typescript
+    breakpad
   ];

   nativeBuildInputs = [
-    # This causes a segfault for reasons unknown, leave it disabled for now
-    # qscintilla
+    qscintilla
     qtnetworkauth
     qtmultimedia
     qtbase
@@ -54,13 +55,20 @@ stdenv.mkDerivation rec {

   extraOutputsToLink = [ "doc" ];

-  patches = [ ./variableToString-instantiation.patch ];
+  patches = [
+    ./variableToString-instantiation.patch
+    ./threads.patch
+  ];

   postPatch = ''
     # the npm build step only runs typescript
     # run this step directly so it doesn't try and fail to download the unnecessary node_modules, etc.
     substituteInPlace ./sites/CMakeLists.txt --replace "npm install" "npm run build"

+    sed "s;\''${BREAKPAD}/src/client/linux;\${breakpad}/lib;" -i ./gui/CMakeLists.txt
+    sed "s;\''${BREAKPAD}/src;${breakpad}/include/breakpad;" -i ./gui/CMakeLists.txt
+    substituteInPlace ./gui/CMakeLists.txt --replace 'set(BREAKPAD "~/Programmation/google-breakpad")' 'set(BREAKPAD "${breakpad}")'
+
     # remove the vendored catch2
     rm -rf tests/src/vendor/catch
```

</details>

<details>
<summary><code>threads.patch</code></summary>

```patch
diff --git a/src/gui/CMakeLists.txt b/src/gui/CMakeLists.txt
index 03d1e797..bef25b9e 100644
--- a/gui/CMakeLists.txt
+++ b/gui/CMakeLists.txt
@@ -115,6 +115,7 @@ if(USE_BREAKPAD)
        endif()
    elseif(UNIX)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fpermissive")
+       find_package(Threads REQUIRED)
        list(APPEND LIBS "${BREAKPAD}/src/client/linux/libbreakpad_client.a")
    endif()
    message(STATUS "Using Google Breakpad from ${BREAKPAD}")
@@ -129,7 +130,7 @@ else()
    add_executable(${PROJECT_NAME} ${SOURCES} ${FORMS} ${UTILS_SOURCES})
 endif()

-target_link_libraries(${PROJECT_NAME} ${QT_LIBRARIES} ${LIBS} lib)
+target_link_libraries(${PROJECT_NAME} ${QT_LIBRARIES} ${LIBS} lib Threads::Threads)

 if(ANDROID)
    # SSL
```

</details>

**Comment by evanjs** [comment]
Also, not sure what's best in this case, but upstream _does_ specify `typescript-4.3.5` in the primary [`package.json`](https://github.com/Bionus/imgbrd-grabber/blob/b4e40fbdbd31f3ebeff7ec557322ed21c0c2d222/src/sites/package.json#L20)

If we pin to `4.3.5`, the `typescript-4.4` patch should not be necessary.

<details>
<summary>TypeScript version override example</summary>

```nix
let
  typescript_pin = typescript.override {
    version = "4.3.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/typescript/-/typescript-4.3.5.tgz";
      sha512 = "DqQgihaQ9cUrskJo9kIyW/+g0Vxsk8cDtZ52a3NGh0YNTfpUSArXSohyUGnvbPazEPLu398C0UxmKSOrPumUzA==";
    };
  };
in
```

</details>

**Comment by mkg20001** [comment]
@evanjs As a nixpkgs committer you can directly push to all PRs that have maintainer access enabled, so feel free to just directly push your patches

I'd say since the breakpad patch already has been verified to work it could just be added (and possibly submitted to upstream if not already happend)

**Comment by evanjs** [comment]
> @evanjs As a nixpkgs committer you can directly push to all PRs that have maintainer access enabled, so feel free to just directly push your patches
> 
> I'd say since the breakpad patch already has been verified to work it could just be added (and possibly submitted to upstream if not already happend)

Just tried a dry-run and checked the teams; I believe I'm still _just_ a maintainer (probably a good thing haha)
My changes are available [here](https://github.com/evanjs/nixpkgs/commits/interruptinuse/imgbrd-grabber-7.6.2)

**Comment by willcohen** [comment]
Separately, proposed #150595 moves `qscintilla` to qt5 by default and re-enables on darwin.

**Comment by evanjs** [comment]
While initial testing seemed to show some issues, #152738 seems to build and launch just fine now
Closing this and we can open a new PR for 7.7.0 -> 7.7.1, which _should_ be trivial if what was just merged works fine.

**Pull request closed without merging**
