### PR TITLE
dwarf-fortress: update themes.json

### PR DESCRIPTION
**Pull request by bbigras**
###### Motivation for this change

I wanted the vettlingr theme.

Tested build with `nix-build -I nixpkgs=/home/bbigras/nixpkgs -E 'with (import <nixpkgs>{}); pkgs.dwarf-fortress-packages.dwarf-fortress-full.override { theme = "vettlingr"; enableIntro = false; enableFPS = true; }'`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bbigras** [comment]
also tested with nix-review:

2 packages added:
dwarf-fortress-packages.themes.meph (init at 47.04_v5.5.0_V1.1.2) dwarf-fortress-packages.themes.vettlingr (init at 1.4a)

12 packages updated:
dwarf-fortress-packages.themes.afro-graphics (47.02 → 47.04) dwarf-fortress-full dwarf-fortress-packages.themes.gemset (47.02 → 47.04) dwarf-fortress-packages.themes.ironhand (47.02 → 47.04) dwarf-fortress-packages.themes.jolly-bastion (47.02 → 47.04) dwarf-fortress-packages.themes.mayday (47.01 → 47.04a) dwarf-fortress-packages.themes.obsidian (47.02 → 47.04a) dwarf-fortress-packages.phoebus-theme (47.02a → 47.04a) dwarf-fortress-packages.themes.rally-ho (47.02 → 47.04) dwarf-fortress-packages.themes.spacefox (47.02 → 47.04) dwarf-fortress-packages.themes.taffer (47.01b → 47.04) dwarf-fortress-packages.themes.wanderlust (47.02 → 47.04)

14 packages built:
dwarf-fortress-packages.dwarf-fortress-full dwarf-fortress-packages.phoebus-theme dwarf-fortress-packages.themes.afro-graphics dwarf-fortress-packages.themes.gemset dwarf-fortress-packages.themes.ironhand dwarf-fortress-packages.themes.jolly-bastion dwarf-fortress-packages.themes.mayday dwarf-fortress-packages.themes.meph dwarf-fortress-packages.themes.obsidian dwarf-fortress-packages.themes.rally-ho dwarf-fortress-packages.themes.spacefox dwarf-fortress-packages.themes.taffer dwarf-fortress-packages.themes.vettlingr dwarf-fortress-packages.themes.wanderlust

**Comment by bbigras** [comment]
@matthewbauer @shazow

**Review by shazow — APPROVED** [review]
Looks good, thank you!!

**Comment by bbigras** [comment]
Thanks everybody!

**Pull request merged**
