### PR TITLE
[WIP] freetype+fontconfig update

### PR DESCRIPTION
**Pull request by vcunat**
I thought this won't be hard, but firefox and thunderbird are showing frequent rendering glitches, e.g. colored pixels between characters on the baseline.  I haven't noticed those in other software, though.  And the overall rendering seems slightly improved (to me but the glitches are very annoying).

I'm not sure what to do about this ATM.  /cc @ttuegel (maintainer).

### CODE REVIEW

**Comment by volth** [comment]
```2.8.x``` has issues/regressions with some fonts too: https://github.com/NixOS/nixpkgs/pull/27725

**Comment by volth** [comment]
And do not forget to reverse the logic of ```useEncumberedCode``` patch, the default has been changed

**Comment by vcunat** [comment]
It's not about switching the two ways.  The upstream default is now a *new* approach "Harmony", probably without patent risks.

**Comment by ttuegel** [comment]
> I thought this won't be hard, but firefox and thunderbird are showing frequent rendering glitches, e.g. colored pixels between characters on the baseline.

Is this with pre-built binaries, or build-from-source?

**Comment by vcunat** [comment]
@ttuegel: whole system rebuilt from source.

**Comment by ttuegel** [comment]
Then I would be inclined to wait on the FreeType update until upstream fixes Firefox.

**Comment by jtojnar** [comment]
Freetype 2.9.0 is required by librsvg 2.42.3.

**Comment by abbradar** [comment]
@vcunat I don't see any visual glitches on Firefox with freetype 2.9 and fontconfig 2.15.6.

**Comment by abbradar** [comment]
screenshot_2018-03-07_03-13-23

Example of Firefox rendering. It seems different but I can't say if it's in a good or a bad way.

**Comment by volth** [comment]
@abbradar 
can you screen [this page](https://cu.wikipedia.org/wiki/Ꙗпѡньскъ_ѩꙁꙑкъ) ?
one of the weirdest in terms of font issues

**Comment by abbradar** [comment]
screenshot_2018-03-07_03-32-23

Sorry for my Japanese fonts being shit ^_^". To clarify: this is a firefox run atop [my branch](https://github.com/NixOS/nixpkgs/pull/36371) without a full system rebuild.

**Comment by volth** [comment]
I would upgrade on unstable (on 18.09)

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/36371

**Pull request closed without merging**
