### PR TITLE
maintainers: add dietmarw

### PR DESCRIPTION
**Pull request by dietmarw**
## Description of changes

Adds "dietmarw" to the list of maintainers.

### CODE REVIEW

**Comment by Janik-Haag** [comment]
Why do you want to be added to the maintainers list? Are you planning on packaging/maintaining something?

**Comment by dietmarw** [comment]
I worked on packaging [bsync](https://github.com/dooblem/bsync) and was following a packing guide that advice on adding oneself to the maintainers list in order to use `lib.maintainer.<name>`.  So that is what I did. I can understand if this is not wanted by the project not to clutter up the list. So feel free to decline the PR.

**Comment by Janik-Haag** [comment]
Feel free to add yourself to the maintainer list like here, but I would prefer if you just send the commit in the same pr where you send a commit for bsync :)l

**Review by bjornfor — APPROVED** [review]

**Comment by dietmarw** [comment]
> Feel free to add yourself to the maintainer list like here, but I would prefer if you just send the commit in the same pr where you send a commit for bsync :)l

Yes that makes sense. But I case in this case I create a separate for bsync.

**Pull request merged**
