### PR TITLE
termonad: fix pcre dependency

### PR DESCRIPTION
**Pull request by mdorman**
###### Motivation for this change

Fix currently broken build

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @peti

### CODE REVIEW

**Comment by samdoshi** [comment]
Tested with `nix-review pr 70833`.

Have run `haskellPackages.termonad/bin/termonad` and `termonad-with-packages/bin/termonad`

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM (don't package haskell much)
fixes broken build

```
[4 built, 308 copied (3028.9 MiB), 165.2 MiB DL]
https://github.com/NixOS/nixpkgs/pull/70833
2 package were build:
haskellPackages.termonad termonad-with-packages
```

cc @peti for haskell input

**Review by cdepillabout — APPROVED** [review]
This looks good to me.

@mdorman Thanks for this fix.

Thanks everyone else for the quick reviews.

---------------------------------------------------------------------------

An alternative fix for this would be to send a PR to `cabal2nix` teaching it about the `libpcre2` library:

https://github.com/NixOS/cabal2nix/blob/5325ccdedb0604d71aac2213fa0d2d018ef02e07/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs#L16-L26

(I think this is the correct place, although there might be another list for pkg-config dependencies...)

**Comment by cdepillabout** [comment]
@peti Thanks for NixOS/cabal2nix@e60526d.  In the future, I'll try to recommend people send these kinds of update to cabal2nix instead of fixing it here in nixpkgs.

**Comment by peti** [comment]
I made the necessary changes in `cabal2nix`. Thanks for pointing out that this mapping was missing. :-)

**Pull request closed without merging**
