### PR TITLE
Mark more unfree licenses as unfree.

### PR DESCRIPTION
**Pull request by Zimmi48**
See also #20256.

### CODE REVIEW

**Comment by Profpatsch** [comment]
Bear in mind that this might break (more than) a few packages, because of transitive dependencies that are now unfree.

**Comment by Zimmi48** [comment]
Break of just make them non-compiled by Hydra?

**Comment by 7c6f434c** [comment]
I wouldn't expect a widely used dependency to be under the licenses in question…

It seems to me that ofborg expects no breakage…

**Comment by Profpatsch** [comment]
Awesome.

**Comment by vcunat** [comment]
AFAIK ofborg wouldn't detect packages "disappearing".  The rebuild counts are basically newly-appearing out-hashes.

**Comment by vcunat** [comment]
The corresponding removed list on Hydra: https://hydra.nixos.org/eval/1465511#tabs-removed  (it's over fifty commits together)

**Comment by 7c6f434c** [comment]
@vcunat I do know that at some point it did at least calculate the list of removed packages; maybe there is no easily accessible statistics, though.

**Comment by vcunat** [comment]
I didn't know that.  Anyway, the list seems OK to me, mostly themes and fonts, probably easy to build.

**Comment by Zimmi48** [comment]
We could indeed have kept these licenses marked as "free" with a comment because they are non-free but redistributable, as for `redistributableFirmware`. However, I guess it would be much better to separate the two pieces of information indeed. What can be built on Hydra is a different question than what the user can install if they only want free software.

**Comment by 7c6f434c** [comment]
Note that redistributable firmware is also firmware, which also affects many users' willingness to compromise.

And missing firmware is exactly the situation that breaks WiFi (and newcomers might want to read an explanation online), so _we_ are more willing to compromise.

As long as we don't have an unfree but redistributable package with the build not dominated by unpacking, we can probably mark unfree non-firmware stuff unfree and let the endpoint machines unpack the icon themes.

**Comment by vcunat** [comment]
IMHO hydra.nixos.org might accept most of the redistributable stuff, at least legally it should be OK.  I believe it's primarily just about the degree "we" want to "support" software that is "unfree" in some sense.  There's been lots of discussion even about how (not) to list unfree packages by default.

**Pull request merged**
