### PR TITLE
leftwm: fix to also patchelf lefthk-worker

### PR DESCRIPTION
**Pull request by thled**
###### Description of changes

Since version 0.4.0 of leftwm the hotkey management is bundled in a new binary called lefthk.
This binary wasn't patched in the postInstall step because it doesn't follow the pattern of starting with leftwm*.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by leifhelm — APPROVED** [review]

**Comment by valff** [comment]
Are there any remaining issues stopping from merging this? I use leftwm as my main WM, and NixOS 22.11 release is essentially broken for me.

**Comment by justanotherariel** [comment]
Can confirm that this patch fixes the package leftwm.

**Review by yanganto — APPROVED** [review]

**Review by aitet — APPROVED** [review]

**Review by rayanpiro — APPROVED** [review]
Properly working!

**Comment by Zeerooth** [comment]
I can confirm as well that this change fixes keybinds for me, I'd be nice to have it merged to the master

**Comment by XaydBayeck** [comment]
This problem is still existed. Why this PR has not merge?
Maybe someone could provide the codes using `overlays` to fix the issue temporary?

**Comment by thled** [comment]
> This problem is still existed. Why this PR has not merge? Maybe someone could provide the codes using `overlays` to fix the issue temporary?

I use the following overlay:

```nix
nixpkgs.overlays = [
    (self: super: {
      leftwm = super.leftwm.overrideAttrs (oldAttrs: rec {
        version = "0.4.0";

        src = super.fetchFromGitHub {
          owner = "leftwm";
          repo = "leftwm";
          rev = "360834f42734125758905059f2aedb6316d176ac";
          sha256 = "sha256-mjFRGMQNTTw9G2X81EjamLL3dwMGU56t95Ao4uCAUoc=";
        };

        cargoDeps = oldAttrs.cargoDeps.overrideAttrs (lib.const {
          name = "leftwm-0.4.0-vendor.tar.gz";
          inherit src;
          outputHash = "sha256-XJdnjfeLMwdgfwegkzJY/ksWLylKS8pse2/Xs7XTtrU=";
        });

        postInstall = ''
          for p in $out/bin/left*; do
            patchelf --set-rpath "${super.lib.makeLibraryPath [super.pkgs.xorg.libXinerama super.pkgs.xorg.libX11]}" $p
          done
        '';
      });
    })
  ];
```

**Comment by VuiMuich** [comment]
Hey @stigtsp!
Leftwm-CoMaintainer here, it was brought to our attention, that the current package in Nix ist still broken and as I saw you were merging some other PR couple of minutes ago, I thought to ask for attention for a minute for this very small -fix, that has been approved by several people here.

**Comment by XaydBayeck** [comment]
Thanks for your share.

I wrote a more briefer version:
```nix
self: super:

{
  leftwm = super.leftwm.overrideAttrs (oldAttrs:
    let
      rpathLibs = oldAttrs.buildInputs;
    in
    {
      postInstall = ''
        for p in $out/bin/left*; do
          patchelf --set-rpath "${super.lib.makeLibraryPath rpathLibs}" $p
        done
      '';
    });
}
```

**Comment by VuiMuich** [comment]
Another attempt pinging someone of the currently active mainteiners @viraptor:
Could you please consider this minimal PR to get merged or at least state, whats hindering a potential merge?

**Comment by viraptor** [comment]
set-rpath instead of add seems weird here. But it's an existing thing and it works so 🤷

**Comment by viraptor** [comment]
Should be fixed in 22.11 soon as well.

**Comment by VuiMuich** [comment]
Thanks a lot for merging this!

**Pull request merged**
