### PR TITLE
vimPlugins.lazydev-nvim: fix pname

### PR DESCRIPTION
**Pull request by linsui**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Why do you want to change this ?
`lazydev-nvim` is the correct pname according to me. Isn't it @teto ?

**Comment by teto** [comment]
pname is the official name so it must be `lazydev.nvim`

**Comment by GaetanLepage** [comment]
> pname is the official name so it must be `lazydev.nvim`

Indeed, now I know !

**Review by GaetanLepage — APPROVED** [review]

**Comment by teto** [comment]
IIRC `pname` is used to create the directories in the packpath generated by nix so having a wrong packpath will prevent the plugin from working.
This oculd be checked via 
```
    doInstallCheck = true;
    vimCommandCheck = "MinimapToggle";
```
or 
`    nvimRequireCheck = "plenary";` . Could you add such a test please ?

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 320746` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.lazydev-nvim</li>
  </ul>
</details>

**Comment by linsui** [comment]
> Why do you want to change this ?

This

> IIRC pname is used to create the directories in the packpath generated by nix so having a wrong packpath will prevent the plugin from working.

Without a correct path it can't be loaded by lazy.nvim.

> Could you add such a test please ?

Do you want me to add it in this PR? I thought such check should be added to all plugins.

**Comment by teto** [comment]
> I thought such check should be added to all plugins.

I think so too hence my request :)

> Do you want me to add it in this PR?

As you prefer but it's simple to do (2 lines) and doing it here is less overhead for everyone involved ?

**Comment by linsui** [comment]
Sorry, I don't understand how it works...

**Comment by GaetanLepage** [comment]
Let's merge this, no ?

**Review by kirillrdy — APPROVED** [review]

**Comment by teto** [comment]
> Sorry, I don't understand how it works...

in pkgs/applications/editors/vim/plugins/overrides.nix, add 
```
  lazydev-nvim = super.lazydev-nvim.overrideAttrs {

  doInstallCheck = true;
  vimCommandCheck = "LazyDev";
}
```

**Comment by linsui** [comment]
Oh, so you meant to add this check to all plugins instead of something globally?

**Comment by linsui** [comment]
This has been fixed in https://github.com/NixOS/nixpkgs/pull/321039.

**Pull request closed without merging**
