### PR TITLE
[24.05] virtualbox: 7.0.18 -> 7.0.22

### PR DESCRIPTION
**Pull request by LeSuisse**
Cherry-picks of #350707, #338117 and #330796

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by FriedrichAltheide — APPROVED** [review]

**Comment by bjornfor** [comment]
Result of `nixpkgs-review pr 351261` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_5_4_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_4_hardened.virtualbox</li>
    <li>linuxPackages_5_4_hardened.virtualboxGuestAdditions</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_5_15_hardened.virtualbox (linuxKernel.packages.linux_5_15_hardened.virtualbox)</li>
    <li>linuxPackages_5_15_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_5_15_hardened.virtualboxGuestAdditions)</li>
    <li>linuxPackages_6_1_hardened.virtualbox (linuxKernel.packages.linux_6_1_hardened.virtualbox)</li>
    <li>linuxPackages_6_1_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_6_1_hardened.virtualboxGuestAdditions)</li>
    <li>linuxPackages_hardened.virtualbox (linuxPackages_6_6_hardened.virtualbox)</li>
    <li>linuxPackages_hardened.virtualboxGuestAdditions (linuxPackages_6_6_hardened.virtualboxGuestAdditions)</li>
    <li>virtualboxKvm</li>
  </ul>
</details>
<details>
  <summary>41 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_19.virtualbox</li>
    <li>linuxKernel.packages.linux_4_19.virtualboxGuestAdditions</li>
    <li>linuxPackages_4_19_hardened.virtualbox (linuxKernel.packages.linux_4_19_hardened.virtualbox)</li>
    <li>linuxPackages_4_19_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_4_19_hardened.virtualboxGuestAdditions)</li>
    <li>linuxKernel.packages.linux_5_10.virtualbox</li>
    <li>linuxKernel.packages.linux_5_10.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_10_hardened.virtualbox (linuxKernel.packages.linux_5_10_hardened.virtualbox)</li>
    <li>linuxPackages_5_10_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_5_10_hardened.virtualboxGuestAdditions)</li>
    <li>linuxKernel.packages.linux_5_15.virtualbox</li>
    <li>linuxKernel.packages.linux_5_15.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_4.virtualbox</li>
    <li>linuxKernel.packages.linux_5_4.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_6_1.virtualbox</li>
    <li>linuxKernel.packages.linux_6_1.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_6_10.virtualbox</li>
    <li>linuxKernel.packages.linux_6_10.virtualboxGuestAdditions</li>
    <li>linuxPackages_latest.virtualbox (linuxKernel.packages.linux_6_11.virtualbox)</li>
    <li>linuxPackages_latest.virtualboxGuestAdditions (linuxKernel.packages.linux_6_11.virtualboxGuestAdditions)</li>
    <li>linuxPackages.virtualbox (linuxKernel.packages.linux_6_6.virtualbox)</li>
    <li>linuxPackages.virtualboxGuestAdditions (linuxKernel.packages.linux_6_6.virtualboxGuestAdditions)</li>
    <li>linuxPackages_latest-libre.virtualbox (linuxKernel.packages.linux_latest_libre.virtualbox)</li>
    <li>linuxPackages_latest-libre.virtualboxGuestAdditions (linuxKernel.packages.linux_latest_libre.virtualboxGuestAdditions)</li>
    <li>linuxPackages-libre.virtualbox (linuxKernel.packages.linux_libre.virtualbox)</li>
    <li>linuxPackages-libre.virtualboxGuestAdditions (linuxKernel.packages.linux_libre.virtualboxGuestAdditions)</li>
    <li>linuxPackages_lqx.virtualbox (linuxKernel.packages.linux_lqx.virtualbox)</li>
    <li>linuxPackages_lqx.virtualboxGuestAdditions (linuxKernel.packages.linux_lqx.virtualboxGuestAdditions)</li>
    <li>linuxPackages_xanmod.virtualbox (linuxKernel.packages.linux_xanmod.virtualbox)</li>
    <li>linuxPackages_xanmod.virtualboxGuestAdditions (linuxKernel.packages.linux_xanmod.virtualboxGuestAdditions)</li>
    <li>linuxPackages_xanmod_latest.virtualbox (linuxKernel.packages.linux_xanmod_latest.virtualbox ,linuxPackages_xanmod_stable.virtualbox)</li>
    <li>linuxPackages_xanmod_latest.virtualboxGuestAdditions (linuxKernel.packages.linux_xanmod_latest.virtualboxGuestAdditions ,linuxPackages_xanmod_stable.virtualboxGuestAdditions)</li>
    <li>linuxPackages_zen.virtualbox (linuxKernel.packages.linux_zen.virtualbox)</li>
    <li>linuxPackages_zen.virtualboxGuestAdditions (linuxKernel.packages.linux_zen.virtualboxGuestAdditions)</li>
    <li>virtualbox</li>
    <li>virtualbox.modsrc</li>
    <li>virtualboxExtpack</li>
    <li>virtualboxHardened</li>
    <li>virtualboxHardened.modsrc</li>
    <li>virtualboxHeadless</li>
    <li>virtualboxHeadless.modsrc</li>
    <li>virtualboxWithExtpack</li>
    <li>virtualboxWithExtpack.modsrc</li>
  </ul>
</details>

**Comment by bjornfor** [comment]
> Result of `nixpkgs-review pr 351261` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 4 packages marked as broken and skipped:
> 
> 
> 7 packages failed to build:
> 
>     * linuxPackages_5_15_hardened.virtualbox (linuxKernel.packages.linux_5_15_hardened.virtualbox)
>
>     * linuxPackages_5_15_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_5_15_hardened.virtualboxGuestAdditions)
>
>     * linuxPackages_6_1_hardened.virtualbox (linuxKernel.packages.linux_6_1_hardened.virtualbox)
>
>     * linuxPackages_6_1_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_6_1_hardened.virtualboxGuestAdditions)
>
>     * linuxPackages_hardened.virtualbox (linuxPackages_6_6_hardened.virtualbox)
>
>     * linuxPackages_hardened.virtualboxGuestAdditions (linuxPackages_6_6_hardened.virtualboxGuestAdditions)

The above are already broken.

>     * virtualboxKvm

Regression!

```
$ nix-build -A virtualboxKvm

these 2 derivations will be built:
  /nix/store/rzgjh2hfqw3w1i2xlfbq77mbizlhzdji-virtualbox-7.0.22-kvm-dev-20240828.patch.drv
  /nix/store/3330f3ccsy63pphadn40g3f2djdawblg-virtualbox-7.0.22.drv
building '/nix/store/rzgjh2hfqw3w1i2xlfbq77mbizlhzdji-virtualbox-7.0.22-kvm-dev-20240828.patch.drv'...

trying https://github.com/cyberus-technology/virtualbox-kvm/releases/download/dev-20240828/kvm-backend-7.0.22-dev-20240828.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) The requested URL returned error: 404
error: cannot download virtualbox-7.0.22-kvm-dev-20240828.patch from any mirror
error: builder for '/nix/store/rzgjh2hfqw3w1i2xlfbq77mbizlhzdji-virtualbox-7.0.22-kvm-dev-20240828.patch.drv' failed with exit code 1;
```

**Comment by LeSuisse** [comment]
Yes the failure of `virtualboxKvm` is expected according to the discussion in #350707

**Review by risicle — APPROVED** [review]
`nixpkgs-review` reveals no new failures, nixos x86_64

**Pull request merged**
