### PR TITLE
ffmpeg_4: 4.3.2 -> 4.4

### PR DESCRIPTION
**Pull request by vs49688**
###### Motivation for this change

Updating. This will probably be a big rebuild.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukegb** [comment]
@ofborg build ffmpeg_4 ffmpeg_4.passthru.tests

(+darwin)

**Comment by jonringer** [comment]
This was already done in #118990, it's currently in staging and will be in the next release

**Comment by jonringer** [comment]
> Hah. Whoops, should've checked staging. Thanks Jon!

I only realized it because rebase failed :)

**Comment by vcunat** [comment]
but darwin fails (in the check you triggered and now on Hydra), so in case you have some ideas...

**Pull request closed without merging**
