### PR TITLE
treewide: remove placeholder usage

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
I keep forgetting 17.03 is not released yet, see https://github.com/NixOS/nixpkgs/commit/2abac54c033778104533a269aaa08a1e75f677ad

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
@jtojnar Can this be merged? Lots of people have been complaining about some variation of this.

Can probably end up closing #37875 with this.

**Comment by jtojnar** [comment]
I did not yet have time to test if it works (webkitgtk rebuild).

**Comment by matthewbauer** [comment]
IMO we should just merge this and test it through Hydra. The ```placeholder``` usage means that evaluation is broken for Nix 1.11 users which is pretty critical (and means they can't upgrade even if they want to).

**Comment by jtojnar** [comment]
Apparently, at least libgee was broken by this.

**Comment by jtojnar** [comment]
Okay, all the packages seem to build and the executables run.

**Comment by Infinisil** [comment]
You forgot https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/pipewire/default.nix#L37

**Comment by jtojnar** [comment]
@Infinisil does it matter? It is only used by mutter. Who would be using unstable desktop but outdated Nix?

**Comment by LnL7** [comment]
Yes, it matters for evaluation.

**Comment by jtojnar** [comment]
Is not evaluation lazy? Anyway, this broke `evolution-data-server`, will push a fix for both shortly.

**Comment by matthewbauer** [comment]
Yeah evaluation is lazy if you are using ```nix-env -iA```. Unfortunately lots of people are still in the habit of using ```nix-env -i```. Since it's still supported we aim to not break evaluation (although this is a special case because it will evaluate under Nix 2.0 which OfBorg and Hydra are on).

**Comment by jtojnar** [comment]
Fix pushed, including the one for 025881c2364

**Comment by matthewbauer** [comment]
Awesome thanks!

**Pull request merged**
