### PR TITLE
[Backport release-23.11]: Cargo tools updates

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Description of changes

This PR backports a bunch of `cargo-*` subcommands from master to the latest release (`release-23.11`).

A release maintainer should probably have a look whether this is okay to be backported.

---

The list of commits that are backported:

* [cargo-udeps: 0.1.43 -> 0.1.45](https://github.com/matthiasbeyer/nixpkgs/commit/b788592ce55c65cccbb40bd20f582fab3da5d733)                                                                                                                                                                                                                                                    
* [cargo-tally: 1.0.36 -> 1.0.38](https://github.com/matthiasbeyer/nixpkgs/commit/02eec70ed9fcc039eadc6d1acbdf6c0ef303aa82)
* [cargo-tally: 1.0.35 -> 1.0.36](https://github.com/matthiasbeyer/nixpkgs/commit/130a7fdf7b721e2d5c363de6590b92c91b9b74bc)                                                                                                                                                                                                              
* [cargo-tally: 1.0.34 -> 1.0.35](https://github.com/matthiasbeyer/nixpkgs/commit/1360af01110c87613116db7917bc447e88b3ca10)                                                                                                                                                                                                                                                    
* [cargo-tally: 1.0.33 -> 1.0.34](https://github.com/matthiasbeyer/nixpkgs/commit/29eabaf9a3bc795d0b5f58f2bc03ba1b3131f62e)                                                                                                                                                                                                                                                    
* [cargo-tally: 1.0.32 -> 1.0.33](https://github.com/matthiasbeyer/nixpkgs/commit/0c9dbdf9a5d92bcfbab9e9a357d99a6dc10c7396)                                                                                                                                                                                                                                                    
* [cargo-tally: 1.0.31 -> 1.0.32](https://github.com/matthiasbeyer/nixpkgs/commit/ffe99f3f594407d2af562c7c78689eb1a1b652c0)  
* [cargo-semver-checks: 0.27.0 -> 0.28.0](https://github.com/matthiasbeyer/nixpkgs/commit/15e70dbab75da3dd9676013c76035746dcce55b1)                                                                                                                                                                                                                                            
* [cargo-semver-checks: 0.28.0 -> 0.29.0](https://github.com/matthiasbeyer/nixpkgs/commit/043b7d3ad7735c60ffc151a515f34322e0ca1ef2)    
* [cargo-run-bin: 1.7.0 -> 1.7.2](https://github.com/matthiasbeyer/nixpkgs/commit/748aa8db1847784cb09a51f811580c9435423f79)                                                                                                                                                                                                                                                    
* [cargo-run-bin: 1.6.1 -> 1.7.0](https://github.com/matthiasbeyer/nixpkgs/commit/dffd27e489225425b3991df87ea868b7a6f9c9ef)                                                                                                                                                                                                                                                    
* [cargo-run-bin: 1.6.0 -> 1.6.1](https://github.com/matthiasbeyer/nixpkgs/commit/d1ea7f192477e69b889c7f165dbd6e818af51f93)                                                                                                                                                                                                                                                    
* [cargo-run-bin: 1.5.0 -> 1.6.0](https://github.com/matthiasbeyer/nixpkgs/commit/c0a56eb2e801c3938a6e6c1dc70ec2e8a676adad)                                                                                                                                                                                                                                                    
* [cargo-public-api: 0.33.0 -> 0.33.1](https://github.com/matthiasbeyer/nixpkgs/commit/5cdd0b9a38b8463d8210dbe092f6b5a7b1af8456)                                                                                                                                                                                                                                               
* [cargo-public-api: 0.32.0 -> 0.33.0](https://github.com/matthiasbeyer/nixpkgs/commit/e5be54d129670cd46863b9e657a6f8cecd7df6d2)                                                                                                                                                                                                                                               
* [cargo-nextest: 0.9.66 -> 0.9.67](https://github.com/matthiasbeyer/nixpkgs/commit/afc467ae76555b2199902abc031478371c821631)                                                                                                                                                                                                                                                  
* [cargo-nextest: 0.9.64 -> 0.9.66](https://github.com/matthiasbeyer/nixpkgs/commit/919d687e2e331a1a3a5a8dc12d19b3e968d14813)                                                                                                                                                                                                                                                  
* [cargo-nextest: 0.9.63 -> 0.9.64](https://github.com/matthiasbeyer/nixpkgs/commit/2ba030352fcf58482a40717e04c0306ecee14f90)                                                                                                                                                                                                                                                  
* [cargo-license: 0.6.0 -> 0.6.1](https://github.com/matthiasbeyer/nixpkgs/commit/4b595655e9284514cf0e62551402d0c187d6c0ea)                                                                                                                                                                                                                                                    
* [cargo-generate: 0.18.5 -> 0.19.0](https://github.com/matthiasbeyer/nixpkgs/commit/715d39b1b1ee6f43e4d98f55986104e87bf0c76b)                                                                                                                                                                                                                                                 
* [cargo-dist: 0.8.0 -> 0.8.2](https://github.com/matthiasbeyer/nixpkgs/commit/3a44e8302f9d7df06fdfa8d610befa4126bcc10e)                                                                                                                                                                                                                                                       
* [cargo-dist: 0.7.2 -> 0.8.0](https://github.com/matthiasbeyer/nixpkgs/commit/0a0b8c1facc8deb98c60ee92ae9046cfd0010508)                                                                                                                                                                                                                                                       
* [cargo-dist: 0.5.0 -> 0.7.2](https://github.com/matthiasbeyer/nixpkgs/commit/0c69a9bd64af0c31cc93529dd5eec01055a56550)                                                                                                                                                                                                                                                       
* [cargo-dist: 0.4.3 -> 0.5.0](https://github.com/matthiasbeyer/nixpkgs/commit/ec383f5377c76a1f3cac0edceb3ee0a7bda775df)                                                                                                                                                                                                                                                       
* [cargo-crev: 0.25.4 -> 0.25.6](https://github.com/matthiasbeyer/nixpkgs/commit/279710140a1ba327a73add25856ad8379b15f561)                                                                                                                                                                                                                                                     
* [cargo-clone: 1.1.0 -> 1.2.1](https://github.com/matthiasbeyer/nixpkgs/commit/9acfeb00f1959e2cddac9638910bc66e8ddb9997)                                                                                                                                                                                                                                                      
* [cargo-careful: 0.4.0 -> 0.4.1](https://github.com/matthiasbeyer/nixpkgs/commit/f577e0844ec514d3498268cab115044daf1c95d8)                                                                                                                                                                                                                                                    
* [cargo-about: 0.5.7 -> 0.6.0](https://github.com/matthiasbeyer/nixpkgs/commit/be7d6c2a7acdf7942f1c8faf5bf69141f2ae307f)  
* [cargo-fuzz: 0.11.4 -> 0.12.0](https://github.com/matthiasbeyer/nixpkgs/commit/896195fd6f69996baf50bdaaff5d8dcaa968aa17)
* [cargo-fuzz: use hash instead of sha256](https://github.com/matthiasbeyer/nixpkgs/commit/15d6ecf2784bbb544989b979e4f4fb0cac812d0b)
* [cargo-fuzz: 0.11.3 -> 0.11.4](https://github.com/matthiasbeyer/nixpkgs/commit/9e212d203e06742aa94ec90c5456c6493e9658eb)
* [cargo-fuzz: 0.11.2 -> 0.11.3 (#278558)](https://github.com/matthiasbeyer/nixpkgs/commit/bada7e57a83eea053e2fc4ab687b6c5e5dc2ae0d)


All of those commits are reachable from `master`.

---

CC @figsoda for an opinion on this PR.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Maybe @NickCao has time to look at this?

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 286757` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>cargo-tally</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>cargo-about</li>
    <li>cargo-careful</li>
    <li>cargo-clone</li>
    <li>cargo-crev</li>
    <li>cargo-dist</li>
    <li>cargo-fuzz</li>
    <li>cargo-generate</li>
    <li>cargo-license</li>
    <li>cargo-nextest</li>
    <li>cargo-public-api</li>
    <li>cargo-run-bin</li>
    <li>cargo-semver-checks</li>
    <li>cargo-udeps</li>
    <li>cargo-update</li>
    <li>cargo-workspaces</li>
    <li>castor</li>
    <li>eureka-ideas</li>
    <li>jujutsu</li>
    <li>python-launcher</li>
    <li>the-way</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
Interesting. I'll roll back the changes to tally as soon as I am home again!

**Comment by matthiasbeyer** [comment]
Rebased to latest `release-23.11` and removed the `cargo-tally` update patches.

The issue here was that `cargo-tally` requires an up-to-date compiler to build its dependencies, and we have a compiler that is too old to build them (namingly `clap_lex`).

The simple thing here is to not update it, which is what I did.

**Review by NickCao — APPROVED** [review]
Result of `nixpkgs-review pr 286757` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>cargo-about</li>
    <li>cargo-careful</li>
    <li>cargo-clone</li>
    <li>cargo-crev</li>
    <li>cargo-dist</li>
    <li>cargo-fuzz</li>
    <li>cargo-generate</li>
    <li>cargo-license</li>
    <li>cargo-nextest</li>
    <li>cargo-public-api</li>
    <li>cargo-run-bin</li>
    <li>cargo-semver-checks</li>
    <li>cargo-udeps</li>
    <li>cargo-update</li>
    <li>cargo-workspaces</li>
    <li>castor</li>
    <li>eureka-ideas</li>
    <li>jujutsu</li>
    <li>python-launcher</li>
    <li>the-way</li>
  </ul>
</details>

**Pull request merged**
