### PR TITLE
nikola: init at 7.8.4

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

Nikola is a static site generator written in Python. I added it as a Python application, not Python module, because it's used as an application, not as a library.

Nikola has a bunch of extra dependencies that enable some additional features. Is there some nice way to support installing Nikola with optionally all the extra dependencies? With pip, this would be done as `pip install nikola[extras]`, is there any similar support in nix or would it even be desirable?

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nixy** [comment]
In Nix extra dependencies or modes are usually specified by taking additional arguments such as `fullDependencies` or `interactive`.

You can then use this in the .nix file to tell it how it should be built differently if these are set. Users would have to specify an override for these options in their nixpkgs configuration, which isn't ideal but is possible.

**Comment by jluttine** [comment]
Ok, thanks. I'll leave that for later because I'm not sure if all the optional dependencies even exist in nixpkgs yet and it's a bit of work to add the missing ones.

**Comment by FRidh** [comment]
@jluttine while Nikola is indeed used as an application, I could very well imagine that users want to use it in conjunction with libraries that may be available only on certain Python python versions. This is also why `pelican` e.g. is inside `python-packages.nix`. Therefore, I recommend using `buildPythonPackage` and putting it in `python-modules` and calling it from `python-packages.nix`.

Regarding the extra dependencies. These are only Python libraries, right? In that case they can just use `nix-shell` or `python.withPackages` or `python.buildEnv`.

**Comment by jluttine** [comment]
Ok, I'll make that fix (application -> module) today perhaps. Anyway, I couldn't get it working with Python 2 because Nix contains only Python 3 supported version of doit, which is a dependency of Nikola. Python 2 support would require older doit 0.29.0 (which on the other hand doesn't support Python 3.3). Is there any sensible way to support Python 2 then?

**Comment by FRidh** [comment]
@jluttine doesn't seem like there is. You can disable it on Python 2.

**Comment by jluttine** [comment]
I now made it a Python module instead of an application.

**Comment by jluttine** [comment]
I also added an upgrade of a dependency ws4py because Nikola needed that in order to work properly. Ping @rickynils, the maintainer of ws4py.

**Review by FRidh — APPROVED** [review]

**Comment by jluttine** [comment]
Regarding `doit` Python 2 support, perhaps that nix definition should be written in such a way that if using Python 2, it would install a different version of itself. Or is that bad practice?

**Comment by jluttine** [comment]
Oh, actually `doit` is a Python application, not a module..

**Comment by FRidh** [comment]
@jluttine its an applicationt/tool, but in order to use it you need to write Python code, for which you need an environment where all libraries are compatible with eachother. Therefore, at least within Nixpkgs, its location is in `python-packages.nix`.

**Comment by jluttine** [comment]
It seems that Nikola uses `doit` as a Python library, that is, it imports lots of stuff from it. So perhaps `doit` should be moved to Python modules? And then, Python 2 support could perhaps be gained by using different versions of `doit` for different Python versions within the `doit` nix definition.

**Comment by jluttine** [comment]
I just rebased my commits on latest upstream/master. Is there something to fix or is this good to merge?

**Pull request merged**
