### PR TITLE
thunderbird-bin: 45.5.0 -> 45.5.1 [Critical security fix]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Critical security fix.

https://www.mozilla.org/en-US/thunderbird/45.5.1/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2016-92/

See also #20827

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Can you also submit the patches for thunderbird and firefox (ie: not `-bin`.)

**Comment by taku0** [comment]
@grahamc I will try it on the next release. I don't have knowledge and time for building Firefox for now.

**Comment by grahamc** [comment]
OK I'll get them, thank you!

**Comment by grahamc** [comment]
@taku0 while I do those updates, can you check to see if 45.5 (the ESR version) has an update?

**Comment by taku0** [comment]
OK. I'm building Firefox 45.5.1esr now.

**Comment by taku0** [comment]
I have made a PR for ESR #20841.

**Pull request merged**
