### PR TITLE
cmake: 3.11.2 -> 3.12.1

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

Keeping packages up to date. Additionally I want to use the new (as of 3.12) `target_link_libraries()` support for Object Libraries in a project.

I assume this will trigger a mass-rebuild, and so should go to staging. Do I rebase on top of current staging (or staging-next) or leave it on top of master?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by thefloweringash** [comment]
From a quick survey:
 - 3.9 is used in Darwin's stdenv bootstrapping with a comment to update the application services patch.
 - 3.10 is used in `kicad` and `kicad-unstable` to work around a breaking change in CMake 3.11

I'm testing removing both of these usages and using 3.12 only.

**Comment by thefloweringash** [comment]
Darwin student seems to be ok, still waiting to see if this breaks kicad.

**Comment by thefloweringash** [comment]
KiCad fixed their CMake 3.11 incompatibility long before the 5.0.0 release, and both `kicad` and `nicad-unstable` build locally for me. This PR should be ready to go.

(KiCad fix in git mirror of upstream: https://github.com/KiCad/kicad-source-mirror/commit/2e0b75c058d676f427328506bbf3bc10079da117)

**Comment by matthewbauer** [comment]
Is cmake not using the provided libuv? It shouldn’t be building the vendored one.

**Comment by thefloweringash** [comment]
It's only using the vendored one when building with `useSharedLibraries = false`, which is the case for the bootstrap version in the darwin stdenv.

**Comment by xeji** [comment]
@GrahamcOfBorg build cmake

**Review by vcunat — APPROVED** [review]
This seems nice.  Darwin was thoroughly tested as well, apparently.

**Pull request merged**
