### PR TITLE
llvm for windows cross compiler

### PR DESCRIPTION
**Pull request by tmcl**
###### Motivation for this change

Nixpkgs is almost capable of building GHC as an x86-64 Windows cross compiler. It just needs to useLLVM. The resulting binaries are capable of running on Windows 10 and making basic ffi calls. Note that it still fails if targeting 32-bit i686 on a 64 bit machine. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Win32 is marked as broken so you probably can't run cabal2nix to make things build. It is built as part of ghc so not a big deal.

### CODE REVIEW

**Comment by angerman** [comment]
You can just use the NCG for windows cross compilation. We (iohk) are in fact cross compiling to windows successfully using nix. 
I invite you to check out GitHub.com/input-output-hk/haskell.nix

NB: i would advise not to use the LLVM backend on x86_64. (See the GHC Release Notes)

**Review by angerman — CHANGES_REQUESTED** [review]
Please don't use LLVM for windows. Use the NCG. The GHC LLVM backend has serious flaws on x86_64. See https://downloads.haskell.org/~ghc/8.6.4/docs/html/users_guide/8.6.4-notes.html#known-issues

Use the `cross-ncg` flavour, see: https://github.com/ghc/ghc/blob/36e51406eb5c551f6fdc5b2f9e087c1d3a809141/mk/build.mk.sample#L31-L32

**Comment by matthewbauer** [comment]
Hmm... We are using ncg right now and getting this error:

```
"inplace/bin/hsc2hs" '--cc=/nix/store/gbpi592v6q4dvb94k4j0f261pjhwj5v2-x86_64-pc-mingw32-stage-final-gcc-debug-wrapper-7.4.0/bin/x86_64-pc-mingw32-cc' '--ld=/nix/store/gbpi592v6q4dvb94k4j0f261pjhwj5v2-x86_64-pc-mingw32-stage-final-gcc-debug-wrapper-7.4.0/bin/x86_64-pc-mingw32-cc'  --cross-safe  --cflag=-Wall --cflag=-fno-stack-protector   --cross-compile --cflag=-Dx86_64_HOST_ARCH --cflag=-Dmingw32_HOST_OS --cflag=-D__GLASGOW_HASKELL__=804 '--cflag=-fno-stack-protector' '--cflag=-Wall' '--cflag=-Ilibraries/Win32/dist-install/build/./autogen' '--cflag=-Ilibraries/Win32/include' '--cflag=-Ilibraries/Win32/dist-install/build/include' '--cflag=-fno-strict-aliasing' '--cflag=-Wall' '--cflag=-I/build/ghc-8.4.4/libraries/bytestring/include' '--cflag=-I/build/ghc-8.4.4/libraries/bytestring/dist-install/build/include' '--cflag=-I/build/ghc-8.4.4/libraries/bytestring/dist-install/build/include' '--cflag=-I/build/ghc-8.4.4/libraries/bytestring/dist-install/build/dist-install/build/include' '--cflag=-I/build/ghc-8.4.4/libraries/base/include' '--cflag=-I/build/ghc-8.4.4/libraries/base/dist-install/build/include' '--cflag=-I/build/ghc-8.4.4/libraries/base/dist-install/build/include' '--cflag=-I/build/ghc-8.4.4/libraries/base/dist-install/build/dist-install/build/include' '--cflag=-I/build/ghc-8.4.4/libraries/integer-gmp/include' '--cflag=-I/build/ghc-8.4.4/libraries/integer-gmp/dist-install/build/include' '--cflag=-I/build/ghc-8.4.4/libraries/integer-gmp/dist-install/build/include' '--cflag=-I/build/ghc-8.4.4/libraries/integer-gmp/dist-install/build/dist-install/build/include' '--cflag=-I/build/ghc-8.4.4/rts/dist/build' '--cflag=-I/build/ghc-8.4.4/includes' '--cflag=-I/build/ghc-8.4.4/includes/dist-derivedconstants/header' '--cflag=-Werror=unused-but-set-variable' '--cflag=-Wno-error=inline'  --cflag=-Ilibraries/Win32/dist-install/build/./autogen --cflag=-include --cflag=libraries/Win32/dist-install/build/./autogen/cabal_macros.h   libraries/Win32/./Graphics/Win32/Misc.hsc -o libraries/Win32/dist-install/build/Graphics/Win32/Misc.hs
Misc.hsc: In function '_hsc2hs_test8':
Misc.hsc:70:20: error: storage size of 'test_array' isn't constant
Misc.hsc:70:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:70:20: error: storage size of 'test_array' isn't constant
Misc.hsc:70:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:70:20: error: storage size of 'test_array' isn't constant
Misc.hsc:70:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:70:20: error: storage size of 'test_array' isn't constant
Misc.hsc:70:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:70:20: error: storage size of 'test_array' isn't constant
Misc.hsc:70:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:70:20: error: storage size of 'test_array' isn't constant
Misc.hsc:70:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:70:20: error: storage size of 'test_array' isn't constant
Misc.hsc:70:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:70:20: error: storage size of 'test_array' isn't constant
Misc.hsc:70:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:70:20: error: storage size of 'test_array' isn't constant
Misc.hsc:70:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc: In function '_hsc2hs_test10':
Misc.hsc:82:20: error: storage size of 'test_array' isn't constant
Misc.hsc:82:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:82:20: error: storage size of 'test_array' isn't constant
Misc.hsc:82:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:82:20: error: storage size of 'test_array' isn't constant
Misc.hsc:82:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:82:20: error: storage size of 'test_array' isn't constant
Misc.hsc:82:20: warning: unused variable 'test_array' [-Wunused-variable]
Misc.hsc:82:20: error: storage size of 'test_array' isn't constant
Misc.hsc:82:20: warning: unused variable 'test_array' [-Wunused-variable]
compilation failed
libraries/Win32/ghc.mk:4: libraries/Win32/dist-install/build/.depend-v-p.haskell: No such file or directory
make[1]: *** [libraries/Win32/ghc.mk:4: libraries/Win32/dist-install/build/Graphics/Win32/Misc.hs] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:127: all] Error 2
```

https://hydra.nixos.org/build/92403485

ghc-8.4.4 should cross compile to windows correct?

**Comment by angerman** [comment]
@matthewbauer I think 8.4.4 did work. But you'll need to make sure that your `hsc2hs` is recent enough. You will need `hsc2hs` with `--via-asm` support for the Win32 package to build.

Our ghc is pretty heavily patched, but I believe you'll need at least the `hsc2hs` patch for ghc < 8.6. See https://github.com/input-output-hk/iohk-nix/blob/8a5bc149b4d4cfa8704be62cf1b8755c33e8ec4d/config.nix#L20-L60

**Comment by matthewbauer** [comment]
> @matthewbauer I think 8.4.4 did work. But you'll need to make sure that your `hsc2hs` is recent enough. You will need `hsc2hs` with `--via-asm` support for the Win32 package to build.
> 
> Our ghc is pretty heavily patched, but I believe you'll need at least the `hsc2hs` patch for ghc < 8.6. See https://github.com/input-output-hk/iohk-nix/blob/8a5bc149b4d4cfa8704be62cf1b8755c33e8ec4d/config.nix#L20-L60

It looks like I misspoke on that. We're using the ```perf-cross``` backend which corresponds to LLVM. Is it safe to use ```perf-cross-ncg``` for all cross compilation?

**Comment by angerman** [comment]
> > @matthewbauer I think 8.4.4 did work. But you'll need to make sure that your `hsc2hs` is recent enough. You will need `hsc2hs` with `--via-asm` support for the Win32 package to build.
> > Our ghc is pretty heavily patched, but I believe you'll need at least the `hsc2hs` patch for ghc < 8.6. See https://github.com/input-output-hk/iohk-nix/blob/8a5bc149b4d4cfa8704be62cf1b8755c33e8ec4d/config.nix#L20-L60
> 
> @angerman
> It looks like I misspoke on that. We're using the `perf-cross` backend which corresponds to LLVM. Is it safe to use `perf-cross-ncg` for all cross compilation?

for windows/x86_64, yes! We have a proper native code generator (ncg) for x86_64, and the llvm one for x86_64 is buggy anyway.

For targets for which we don't have an ncg (arm, aarch64, ...) the only option is the llvm backend, but I believe the llvm pipeline for those backends is unaffected from the register confusion that can cause subtle bugs on x86_64 with llvm.

**Comment by cdepillabout** [comment]
@tmcl Is this PR still relevant?  Can it be closed?

If it is still relevant, what is the status of it?

**Comment by Mindavi** [comment]
I think this might be interesting for better windows support, but it doesn't seem like there's much interest from the creator. Please re-open when you still want to work on this, or when someone wants to pick this open, create a new PR :).

**Pull request closed without merging**
