### PR TITLE
Coredns add plugins

### PR DESCRIPTION
**Pull request by KFearsoff**
###### Description of changes

Solves https://github.com/NixOS/nixpkgs/issues/146603

Usage:
```
coredns-fanout = pkgs.coredns.override {
  externalPlugins = ["fanout"];
  vendorSha256 = "<sha>";
};
```

Practically speaking, it's not possible to know `vendorSha256` ahead of time in this case. Just set it to `vendorSha256 = "";`. The build will fail, but it will tell you the necessary sha256

This is not elegant, but I haven't found a better way to do it. In case you want to try solving this puzzle yourself, here's a rundown of what needs to be done:

1. Plugins should be appended to `plugin.cfg` in the source files
2. They should be downloaded via `go get`
3. Sources should be updated with `go generate`

I'm not sure how to do it better, since point 2 requires us to have internet access, which is only possible if we use fixed-output derivations (which is what buildGoModule does already), but that would mean we'd have to do the weird dance with `vendorSha256`

The weird dance is needed because of https://github.com/NixOS/nixpkgs/issues/86349

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by winterqt — CHANGES_REQUESTED** [review]
A few things:
1. This should show the use of pinned plugin versions to ensure reproducibility.
2. Additionally, to improve UX, you should introduce FOD hash validation by checking the `go.sum` files.

All in all, I'm not really sure how I feel about this. I think it *could* work, but ideally we'd do something like I did in https://github.com/NixOS/nixpkgs/issues/14671#issuecomment-1253111596, but that has its own issues.

*wishes for WebAssembly plugins to avoid all of this pain*

**Comment by KFearsoff** [comment]
> 1. This should show the use of pinned plugin versions to ensure reproducibility.

I don't quite understand. Do you want to see plugins being able to be pinned? If so, then yeah, that would be good. I'll think of ways how to do that.

> 2. Additionally, to improve UX, you should introduce FOD hash validation by checking the `go.sum` files.

I'm afraid I'm not confident enough in my Go package management to understand how that would be done. That would be really great to have, though!


> All in all, I'm not really sure how I feel about this. I think it _could_ work, but ideally we'd do something like I did in [#14671 (comment)](https://github.com/NixOS/nixpkgs/issues/14671#issuecomment-1253111596), but that has its own issues.

I think you solution looks cleaner, yeah. I think implementing it is harder, and once again, I'm not quite confident enough in my Go package management. We'd also have to write update scripts for CoreDNS plugins if we hope to have that usable, which I've never done and I'm not sure how easy it is. With some help I'm thinking we'll manage to implement it nicely.

> _wishes for WebAssembly plugins to avoid all of this pain_

Oh yeah, there is a lot of pain.

**Comment by winterqt** [comment]
> I don't quite understand. Do you want to see plugins being able to be pinned? If so, then yeah, that would be good. I'll think of ways how to do that.

It's all in how you specify the package to `go get` (so just what you pass to `externalPlugins` would be affected), see https://go.dev/ref/mod#modules-overview.

> I'm afraid I'm not confident enough in my Go package management to understand how that would be done. That would be really great to have, though!

I can work on an example when I get a chance.

I'm going to mark this as a draft since there's still some uncertainty here (if you disagree, let me know).

**Comment by de11n** [comment]
Thanks for working on this. We are also in need of this feature. However, as written, this design essentially *guarantees* that the build won't be reproducible. I think we need to find a solution that at least tries to maintain reproducibility, even if it can't guarantee it. That would probably require pinning each plugin separately and somehow injecting it into final vendored coredns build.

**Comment by bct** [comment]
The initial `go-modules` derivation fails to build for me with `mv: target directory 'vendor': No such file or directory`.

It works if I add `go mod vendor` to the end of `modBuildPhase`.

**Comment by bct** [comment]
https://github.com/NixOS/nixpkgs/pull/256710 rebases this PR and adds the ability to pin a specific version of each plugin.

**Pull request closed without merging**
