### PR TITLE
 nix: use curl with blocking resolver

### PR DESCRIPTION
**Pull request by orivej**
###### Motivation for this change

This is an alternative to #41452. Apparently curl threaded resolver enabled in 7.60 imposes additional restrictions on usage of its API that are not present with its blocking or asynchronous resolvers.

`c-ares` based asynchronous resolver does not support nsswitch plugins. This change makes Nix continue using curl with blocking resolver.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Tested that `nix-channel --update` does not wait for 10 seconds for DNS resolution.

### CODE REVIEW

**Comment by dtzWill** [comment]
LGTM, and I agree we should leave curl using default resolver (threaded) for most users.

I haven't played with Nix when using blocking resolver-- does Nix work well with it, esp. since we use a single thread to drive downloads it'd be good to check things don't end up excessively serial or something.

FWIW 7.59 had threaded resolver enabled by default as well (we used it), so I'm not sure if anyone's tried the blocking resolver? Looks like threaded was enabled by default ~7.55 bouncing through commit history.

(Thanks for putting together these fixes, we certainly need to do **something** about this)

**Comment by orivej** [comment]
> Looks like threaded was enabled by default ~7.55 bouncing through commit history.

Then https://github.com/curl/curl/issues/2636#issuecomment-394859741 is not sufficient to explain our case, and I am not sure that this is not a curl bug after all.

**Comment by dtzWill** [comment]
FWIW here's a branch that patches Nix to reduce sleep time when items are queued to the recommended duration: https://github.com/dtzWill/nixpkgs/tree/fix/nix-curl-760

(which fixes the badness I was experiencing re:7.60 vs 7.59)

I'll make a PR on the nix repo to discuss the change/idea.

**Comment by mmahut** [comment]
Any updates on this pull request, please?

**Comment by orivej-nixos** [comment]
This is no longer relevant since 51ac3db79c88d3d5e660ff3501be0fe152e146f9.

**Pull request closed without merging**
