### PR TITLE
vimPlugins.nvim-lsp: init at 2019-12-17

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change

New *out of the box* neovim lsp implementation. 
Works pretty well in my experience. Not as good as coc.nvim but pretty close and withtout the npm dependency.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
LGTM

```
[3 built, 1 copied (32.4 MiB), 6.8 MiB DL]
https://github.com/NixOS/nixpkgs/pull/76109
1 package were built:
vimPlugins.nvim-lsp
```

**Comment by timokau** [comment]
Doesn't this require a nightly neovim?

**Comment by teto** [comment]
yes it does; completely forgot about that: ther is some standard lua batteries included in nighlty neovim such as lsp/util.lua that are used in this plugin.

**Comment by timokau** [comment]
In that case I think we should have waited for the neovim release before adding this plugin.

**Comment by lifranc** [comment]
This plugin will trigger a failure when used since its vimscript plugin will try to become a build system of its own, and 'install' things.
```
Error detected while processing /nix/store/v587bnyaydim9fal8l4p7s2v276lxbxn-vimplugin-nvim-lsp-3bcc387/share/vim-plugins/nvim-lsp/plugin/nvim_lsp.vim:
  line    9:
  E5108: Error executing lua Vim:E739: Cannot create directory /homeless-shelter: permission denied
```

**Comment by ominusliticus** [comment]
Hi, 
I am not using nix. I simply installed neovim using apt.
I should also mention that I am on WSL2. 
The offending line for me is precisely line 34 in log.lua (`mkdir -p` command).
It is not clear to what the work around is.

I could remove neovim and clone neovim in a non readonly directory, but I am lazy and don't want to have to worry about making sure every future dev environment needs to have the path automatically set. So besides this suggestion, is there a solution?

**Pull request merged**
