### PR TITLE
2019 03 25 monero 14.0.2

### PR DESCRIPTION
**Pull request by thedavidmeister**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by thedavidmeister** [comment]
cleanup from #57247

tested with `nix-shell -p nix-review --run "nix-review pr 58250"`

**Comment by thedavidmeister** [comment]
```
[thedavidmeister@nixos:~/nixpkgs]$ nix-build $NIXPKGS -A monero-gui --run-env

[nix-shell:~/nixpkgs]$ monerod
2019-03-25 11:43:40.811     7f89bfa7bc40        INFO    global  src/daemon/main.cpp:287 Monero 'Boron Butterfly' (v0.14.0.2-unknown)
2019-03-25 11:43:40.811     7f89bfa7bc40        INFO    global  src/daemon/protocol.h:53        Initializing cryptonote protocol...
```

**Comment by thedavidmeister** [comment]
note the GUI is broken in master, with a pending fix in #57921

**Comment by thedavidmeister** [comment]
@rnhmjoj fyi

**Comment by rnhmjoj** [comment]
Seems good to me. Can we merge it yet?

**Comment by rnhmjoj** [comment]
Btw, you don't need to recreate a PR: you can do an interactive rebase (`git rebase -i HEAD~3` for 3 commits) and the force push.

**Comment by thedavidmeister** [comment]
@rnhmjoj yeah i'm happy to merge, thanks for the tip

i can't actually merge tho, who has the right permissions?

**Comment by rnhmjoj** [comment]
Yeah, we have to ask. Ping @Mic92 @xeji who reviewed monero stuff earlier.

**Pull request merged**
