### PR TITLE
gcc{6..11}: import a patch into nixpkgs

### PR DESCRIPTION
**Pull request by vcunat**
fetchurl can't be used on generated patches this way. The hash doesn't match anymore.  fetchpatch would be an alternative.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
FWIW, the reason the hash doesn't match is the cgit version trailer.

**Comment by vcunat** [comment]
This was discussed [in #dev chat](https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$PZ3vTKt7lUiE4AjBWR94kGkWwTQrASAS5m0_8EYaTQE?via=nixos.org&via=matrix.org&via=nixos.dev).

On 22.11 this would be a huge rebuild, so I guess we can just leave it be.  You only encounter this error if you disable using cache.nixos.org

**Comment by vcunat** [comment]
Uh, larger rebuild than I expected, but I don't think this needs to go fast.

**Review by Artturin — APPROVED** [review]
built gcc6

**Pull request merged**
