### PR TITLE
Elixir remove setup hook

### LINKED ISSUE #85265: elixir's setupHook causes compiler to emit warnings for all code
**Describe the bug**
The `setupHook` in `elixir` is causing all compilation of Elixir source files to emit warnings for files in Elixir's standard library. This only occurs when the compiler is being run inside of `nix-shell`, and does not occur when `elixir` is installed globally, eg. through `environment.systemPackages` in NixOS.

**To Reproduce**
1. Start a shell containing Elixir with `nix-shell -p elixir`
2. Run `mix new test` to generate a sample Elixir project
3. cd into the new `test` directory and run `mix compile` to compile the project.
4. Observe the large amount of warnings emitted, as shown [here](https://pastebin.com/w6gXj3XJ).

**Expected behavior**
The compiler should not emit the warnings it does, and simply output only the following:
```
Compiling 1 file (.ex)
Generated test app
```

**Additional context**
This issue seems to be caused by setting `ERL_LIBS` in Elixir's `setupHook`. Unsetting this environment variable while in the `nix-shell` does cause the compiler warnings to go away. I'm not sure what the purpose of setting this variable is, so I don't know if the solution is as simple as just removing the `setupHook`, or if there's a bit more nuance here.

This issue affects Elixir 1.8 - 1.10. Elixir 1.6 and 1.7 are not affected by this. Elixir 1.8 in particular emits absolute paths beginning with `/build/source`, which looks to me like a remnant of the build environment.

**Notify maintainers**
@the-kenny @Havvy @couchemar @ankhers @filalex77 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.2, NixOS, 20.09pre219796.f601ab37c2f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"home-manager, nixos-20.09pre219796.f601ab37c2f"`
 - channels(ruby): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - elixir
  - elixir_1_10
  - elixir_1_9
  - elixir_1_8
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

close #85265 

we do not know for sure why that hook was added. I propose to remove until we can figure out why it was added.

In case we detect a breakage, I will take the responsability to merge a fix rapidly.

@cw789 thank you for researching the issue

@ericbmerritt in case you have more information about why the hook was added in https://github.com/NixOS/nixpkgs/commit/2d6d9682bb8a910f3eb5f0be8d5687c753e9732c in the first place, that would be useful.

I will leave this open for a little longer, to give a chance for different people to test.

@NixOS/beam 
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cw789** [comment]
Thank you very very much for your efforts. 💛

**Comment by happysalada** [comment]
As much as I like praise :-) , this one is yours! Thanks a lot for researching the issue! I just applied your fix!

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 123876` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>elixir</li>
    <li>elixir_1_10</li>
    <li>elixir_1_7</li>
    <li>elixir_1_8</li>
    <li>elixir_1_9</li>
    <li>elixir_ls</li>
    <li>mix2nix</li>
    <li>rabbitmq-server</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123876` at 9e8b2161 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>elixir (elixir_1_11)</li>
    <li>elixir_1_10</li>
    <li>elixir_1_7</li>
    <li>elixir_1_8</li>
    <li>elixir_1_9</li>
    <li>elixir_ls</li>
    <li>rabbitmq-server</li>
  </ul>
</details>

**Pull request merged**
