### PR TITLE
starship: 0.44.0 -> 0.45.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
https://github.com/starship/starship/releases/tag/v0.45.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg build starship

**Comment by bbigras** [comment]
also please update to v0.45.1

**Comment by berbiche** [comment]
> You have this problem?
> 
> ```
>   failures:
>       modules::directory::tests::directory_in_home
>       modules::directory::tests::fish_directory_in_home
>       modules::directory::tests::truncated_directory_in_home
> 
>   test result: FAILED. 447 passed; 3 failed; 26 ignored; 0 measured; 0 filtered out
> ```
> 
> I spent hours yesterday trying to figure it out. (well while doing other things between rebuilds)

Judging from the tests titles, writing to $HOME should result in a failure inside the build because of the sandbox.

**Comment by bbigras** [comment]
> Judging from the tests titles, writing to $HOME should result in a failure inside the build because of the sandbox.

Yeah I know. Sorry I wasn't clear. The tests are supposed to be disabled, and they are not. That's the problem I had yesterday.

**Comment by marsam** [comment]
>The tests are supposed to be disabled, and they are not.

indeed, it's failing because `checkFlagsArray` gets quoted and treated as a single argument:
https://github.com/NixOS/nixpkgs/blob/302ef60620d277fc87a8aa58c5c561b62c925651/pkgs/build-support/rust/default.nix#L214
I'm going to submit a PR later

**Comment by bbigras** [comment]
thanks @marsam

**Pull request merged**
