### PR TITLE
dvc: add missing dependency for GCS support

### PR DESCRIPTION
**Pull request by carlthome**
###### Description of changes

DVC's GCP support doesn't only depend on the Google Cloud Python SDK, but also GCSFS.

Without GCSFS, a `dvc pull` will complain with

> ERROR: failed to pull data from the cloud - URL 'gs://' is supported but requires these missing dependencies: ['gcsfs']. Please report this bug to <https://github.com/iterative/dvc/issues>. Thank you!

E.g. this won't work

`nix-shell -p dvc 'dvc.override { enableGoogle = true; }'; dvc pull`

But this will work:

`nix-shell -p dvc 'dvc.override { enableGoogle = true; }' python3Packages.gcsfs; dvc pull`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by talyz** [comment]
Hi @carlthome! :wave:

Please fill in the PR template, so reviewers know what you have and haven't done yet.

The diff looks good to me, but I couldn't test it, because `dvc` doesn't build for an unrelated reason:

> ERROR: Could not find a version that satisfies the requirement dvc-render==0.0.5 (from dvc) (from versions: none)
> ERROR: No matching distribution found for dvc-render==0.0.5

**Comment by SuperSandro2000** [comment]
Please follow the contributing guide when naming your commits. This will also auto trigger ofborg.

---

@ofborg build dvc

**Comment by carlthome** [comment]
@talyz updated PR description from template. It said "Note that these are not hard requirements but merely serve as information for reviewers." in it so I figured it wasn't needed.

@SuperSandro2000 updated commit message (and rebased on latest `master`) with what I think is what the contributing guide specified (but please let me know if I got it wrong and I'll update it accordingly).

**Comment by SuperSandro2000** [comment]
> @talyz updated PR description from template. It said "Note that these are not hard requirements but merely serve as information for reviewers." in it so I figured it wasn't needed.

It isn't a requirement but a good guide to make sure your changes are tested and we do less review round trips.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by fabaff** [comment]
https://github.com/NixOS/nixpkgs/issues/175885 is the issue for this. Adding `gcsfs` was blocked by the last `python-updates` run.

**Comment by carlthome** [comment]
Any action needed on my part to get this fix in?

**Comment by carlthome** [comment]
Closing due to stale

**Pull request closed without merging**
