### PR TITLE
fcft: 2.3.1 -> 2.3.2

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

New minor release with a bug fix.

Also allows to disable the text shaping feature in order to not depend on harfbuzz.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@grahamcofborg build foot fuzzel

**Comment by sternenseemann** [comment]
Result of `nixpkgs-review pr 107153` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>fcft</li>
    <li>foot</li>
    <li>fuzzel</li>
  </ul>
</details>

**Comment by sternenseemann** [comment]
@ofborg eval

**Comment by sternenseemann** [comment]
Result of `nixpkgs-review pr 107153` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>fcft</li>
    <li>foot</li>
    <li>fuzzel</li>
  </ul>
</details>

**Review by fionera — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107153` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>fcft</li>
<li>foot</li>
<li>fuzzel</li>
</ul>
</details>

**Pull request merged**
