### PR TITLE
mesa: 21.1.6 -> 21.1.7

### PR DESCRIPTION
**Pull request by alyssais**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
@OfBorg test sway

**Comment by vcunat** [comment]
Mesa isn't such a large rebuild anymore.  As a compromise, we typically target `staging-next` nowadays.  (actually "we" would be `@primeos`)

**Comment by alyssais** [comment]
> Mesa isn't such a large rebuild anymore. As a compromise, we typically target `staging-next` nowadays. (actually "we" meant `@primeos` in practice)

Hmm, that makes me a bit uncomfortable, since the manual says

> t must only see non-breaking commits that are fixing issues blocking it from being merged into the `master` branch.

Are the staging next mergers okay with it?

**Review by primeos — APPROVED** [review]
> Are the staging next mergers okay with it?

No complaints so far. The Mesa updates are non-breaking, especially the patch releases and regarding other packages (i.e. not breaking other builds). In theory Mesa updates should even be fine for `master` but the amount of rebuilds is still a bit high, unfortunately. `staging` is a bit too slow for Mesa updates.

If there should ever go something wrong the staging-next mergers can ping me and I'll have a look and we can even revert the update for the meantime. And AFAIK @vcunat already does **a lot** of the `staging`/`staging-next` work anyway.

Sometimes there are GPU-specific regressions but `staging` wouldn't help with that either.

Edit: I ran the Sway test manually without the GnuPG part as the tracker3 build seems to be broken atm: https://hydra.nixos.org/build/149835405 and https://github.com/NixOS/nixpkgs/pull/131928#issuecomment-897127341.

**Pull request merged**
