### PR TITLE
python3Packages.cmarkgfm: 0.5.3 -> 0.6.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.6.0

Change log: https://github.com/theacodes/cmarkgfm/releases/tag/0.6.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 128903` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>44 packages failed to build:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>check_systemd</li>
    <li>evdevremapkeys</li>
    <li>home-assistant</li>
    <li>keepkey_agent (python39Packages.keepkey_agent)</li>
    <li>ledger_agent (python39Packages.ledger_agent)</li>
    <li>luigi</li>
    <li>mailman-web (python39Packages.mailman-web)</li>
    <li>mnemosyne</li>
    <li>python38Packages.ansible-kernel</li>
    <li>python38Packages.ansible-runner</li>
    <li>python38Packages.gtts</li>
    <li>python38Packages.keepkey_agent</li>
    <li>python38Packages.ledger_agent</li>
    <li>python38Packages.libagent</li>
    <li>python38Packages.mailman-web</li>
    <li>python38Packages.nagiosplugin</li>
    <li>python38Packages.ndjson</li>
    <li>python38Packages.postorius</li>
    <li>python38Packages.pypiserver</li>
    <li>python38Packages.python-daemon</li>
    <li>python38Packages.readme</li>
    <li>python38Packages.readme_renderer</li>
    <li>python38Packages.restview</li>
    <li>python38Packages.salmon-mail</li>
    <li>python38Packages.toggl-cli</li>
    <li>python38Packages.trezor_agent</li>
    <li>python38Packages.twine</li>
    <li>python39Packages.ansible-kernel</li>
    <li>python39Packages.ansible-runner</li>
    <li>python39Packages.gtts</li>
    <li>python39Packages.libagent</li>
    <li>python39Packages.nagiosplugin</li>
    <li>python39Packages.ndjson</li>
    <li>python39Packages.postorius</li>
    <li>python39Packages.pypiserver</li>
    <li>python39Packages.python-daemon</li>
    <li>python39Packages.readme</li>
    <li>python39Packages.readme_renderer</li>
    <li>python39Packages.restview</li>
    <li>python39Packages.salmon-mail</li>
    <li>trezor_agent (python39Packages.trezor_agent)</li>
    <li>twine (python39Packages.twine)</li>
    <li>wlc</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.cmarkgfm</li>
    <li>python39Packages.cmarkgfm</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 128903` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>home-assistant</li>
    <li>mailman-web (python39Packages.mailman-web)</li>
    <li>python38Packages.apache-airflow</li>
    <li>python38Packages.mailman-web</li>
    <li>python38Packages.postorius</li>
    <li>python38Packages.toggl-cli</li>
    <li>python39Packages.apache-airflow</li>
    <li>python39Packages.postorius</li>
    <li>python39Packages.toggl-cli</li>
  </ul>
</details>
<details>
  <summary>40 packages built:</summary>
  <ul>
    <li>check_systemd</li>
    <li>evdevremapkeys</li>
    <li>keepkey_agent (python39Packages.keepkey_agent)</li>
    <li>ledger_agent (python39Packages.ledger_agent)</li>
    <li>luigi</li>
    <li>mnemosyne</li>
    <li>onlykey-agent</li>
    <li>python38Packages.ansible-kernel</li>
    <li>python38Packages.ansible-runner</li>
    <li>python38Packages.cmarkgfm</li>
    <li>python38Packages.gtts</li>
    <li>python38Packages.keepkey_agent</li>
    <li>python38Packages.ledger_agent</li>
    <li>python38Packages.libagent</li>
    <li>python38Packages.nagiosplugin</li>
    <li>python38Packages.ndjson</li>
    <li>python38Packages.pypiserver</li>
    <li>python38Packages.python-daemon</li>
    <li>python38Packages.readme</li>
    <li>python38Packages.readme_renderer</li>
    <li>python38Packages.restview</li>
    <li>python38Packages.salmon-mail</li>
    <li>python38Packages.trezor_agent</li>
    <li>python38Packages.twine</li>
    <li>python39Packages.ansible-kernel</li>
    <li>python39Packages.ansible-runner</li>
    <li>python39Packages.cmarkgfm</li>
    <li>python39Packages.gtts</li>
    <li>python39Packages.libagent</li>
    <li>python39Packages.nagiosplugin</li>
    <li>python39Packages.ndjson</li>
    <li>python39Packages.pypiserver</li>
    <li>python39Packages.python-daemon</li>
    <li>python39Packages.readme</li>
    <li>python39Packages.readme_renderer</li>
    <li>python39Packages.restview</li>
    <li>python39Packages.salmon-mail</li>
    <li>trezor_agent (python39Packages.trezor_agent)</li>
    <li>twine (python39Packages.twine)</li>
    <li>wlc</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Should wait till #135832 arrives.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 128903` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages failed to build:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>home-assistant</li>
    <li>mailman-web (python39Packages.mailman-web)</li>
    <li>python38Packages.ansible-kernel</li>
    <li>python38Packages.ansible-runner</li>
    <li>python38Packages.apache-airflow</li>
    <li>python38Packages.mailman-web</li>
    <li>python38Packages.postorius</li>
    <li>python38Packages.toggl-cli</li>
    <li>python39Packages.ansible-kernel</li>
    <li>python39Packages.ansible-runner</li>
    <li>python39Packages.apache-airflow</li>
    <li>python39Packages.postorius</li>
    <li>python39Packages.toggl-cli</li>
  </ul>
</details>
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li>check_systemd</li>
    <li>evdevremapkeys</li>
    <li>keepkey_agent (python39Packages.keepkey_agent)</li>
    <li>ledger_agent (python39Packages.ledger_agent)</li>
    <li>luigi</li>
    <li>mnemosyne</li>
    <li>onlykey-agent</li>
    <li>python38Packages.cmarkgfm</li>
    <li>python38Packages.gtts</li>
    <li>python38Packages.keepkey_agent</li>
    <li>python38Packages.ledger_agent</li>
    <li>python38Packages.libagent</li>
    <li>python38Packages.nagiosplugin</li>
    <li>python38Packages.ndjson</li>
    <li>python38Packages.pypiserver</li>
    <li>python38Packages.python-daemon</li>
    <li>python38Packages.readme</li>
    <li>python38Packages.readme_renderer</li>
    <li>python38Packages.restview</li>
    <li>python38Packages.salmon-mail</li>
    <li>python38Packages.trezor_agent</li>
    <li>python38Packages.twine</li>
    <li>python39Packages.cmarkgfm</li>
    <li>python39Packages.gtts</li>
    <li>python39Packages.libagent</li>
    <li>python39Packages.nagiosplugin</li>
    <li>python39Packages.ndjson</li>
    <li>python39Packages.pypiserver</li>
    <li>python39Packages.python-daemon</li>
    <li>python39Packages.readme</li>
    <li>python39Packages.readme_renderer</li>
    <li>python39Packages.restview</li>
    <li>python39Packages.salmon-mail</li>
    <li>trezor_agent (python39Packages.trezor_agent)</li>
    <li>twine (python39Packages.twine)</li>
    <li>wlc</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Was introduced with #141037.

**Pull request closed without merging**
