### PR TITLE
clojure-lsp: 2021.11.02 -> 2022.01.03

### PR DESCRIPTION
**Pull request by willcohen**
###### Motivation for this change

Update `clojure-lsp` version. Possibly sidesteps #153765, if it's not an issue on hydra.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 153770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>clojure-lsp</li>
    <li>vscode-extensions.betterthantomorrow.calva</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Error log: http://ix.io/3Liq

CC @ericdallo.

**Comment by willcohen** [comment]
Hydra's errors for darwin appear similar: https://logs.nix.ci/?attempt_id=6116eb2a-5e97-4a26-858e-e971807e7cad&key=nixos%2Fnixpkgs.153770

**Comment by ericdallo** [comment]
I know what it is, with the latest clojjre-lsp version, we made it critical the classpath scan error that was already happening on nix, there is a flag to allow this error and proceed: `api exit-on-errors?`
https://clojure-lsp.io/settings/
We need to check the best way to set this, maybe just apply a patch adding this config to the integration sample test

**Comment by ericdallo** [comment]
nixpkgs-review pr 153770

**Comment by ericdallo** [comment]
Result of `nixpkgs-review pr 153770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>clojure-lsp</li>
    <li>vscode-extensions.betterthantomorrow.calva</li>
  </ul>
</details>

**Comment by ericdallo** [comment]
@willcohen I just remebered that flag will only work for api calls like `clojure-lsp clean-ns --dry`, not on editor, that is what the integration test is testing.
We can:
- Fix the classpath scan which would be the best option, but probably hard to support clojure dependency download (I never managed to achieve this successfully with clojure)
- Add a flag on clojure-lsp side to ignore those errors but I'd like to avoid this option as it doesn't makes sense for editor uses.
- Comment the tests on this derivation until we properly fix this but proceed with the bump?

Besides that I'll make the classpath scan error print on stderr not stdout (maybe this would fix all bugs, not sure)

**Comment by willcohen** [comment]
Okay, I'll poke around at it tomorrow and see if I can figure out a way to get dependencies to download!

**Comment by ericdallo** [comment]
Just FYI @willcohen, I made a commit on clojure-lsp master adding the :api :exit-on-errors to suppress most fails, but there is one test still that doesn't makes sense since it needs the classpath scan

**Comment by willcohen** [comment]
@ericdallo Quick question as I work through this -- is `clojure-lsp` what's calling the classpath lookup via `clojure -A:dev:test -Spath`, or is it `bb`?  

Where I've gotten so far: 
- Setting `DEPS_CLJ_TOOLS_DIR` and `DEPS_CLJ_TOOLS_VERSION` to the derivation's location, and `GITLIBS` and `CLJ_CACHE` to a local dir seems to help load up clojure correctly.
- From there, if I patch in `:mvn/local-repo` to `deps/bb.edn` I can then run `clojure -A:... -Spath` to export out a new classpath, which I might be able to then inject in whatever is otherwise failing. 

I've been trying various `CLASSPATH` or `BABASHKA_CLASSPATH` or injecting it into what babashka is calling etc, but it doesn't seem to help. If it's `clojure-lsp` that's having the failure, then perhaps I should try some variant of `makeWrapper` around a test version of the built `lsp` to see if that helps pass the check test?

**Comment by ericdallo** [comment]
it is clojure-lsp that is calling since the sample-test from integration-tests is a deps.edn project, [ref](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/settings.clj#L22).

**Comment by ericdallo** [comment]
> perhaps I should try some variant of makeWrapper around a test version of the built lsp to see if that helps pass the check test?

@willcohen sounds like a good approach to me.
Also, [this stale PR](https://github.com/clojure-lsp/clojure-lsp/pull/604) may give some ideas, it was a try of making a flakes derivation on the clojure-lsp project

**Comment by willcohen** [comment]
I've been unable to figure out the path issue within the check phase. An alternative possibility is what I pushed up -- using `passthru.tests` to just deal with it in its own environment. @thiagokokada I know that the last thing you want to do is add `passthru.tests` to more random stuff, but I'm not sure how else to get this solved!

@ericdallo I should note that there's still two failures I'm not quite sure how to address:

```
FAIL in (initialize) (/private/tmp/nix-build-clojure-lsp-test.drv-0/tmp.YHgoMIfysy/clojure-lsp/integration-test/integration/initialize_test.clj:10)
initialize request with default config
Actual:

{:capabilities {:workspaceSymbolProvider true, :documentFormattingProvider true, :documentRangeFormattingProvider true, :referencesProvider true, :linkedEditingRangeProvider true, :callHierarchyProvider true, :renameProvider {:prepareProvider true}, :executeCommandProvider {:commands ["add-missing-libspec" "add-import-to-namespace" "cycle-privacy" "create-test" "change-coll" "thread-last-all" "unwind-all" "move-to-let" "clean-ns" "suppress-diagnostic" "thread-last" "introduce-let" "sort-map" "unwind-thread" "thread-first-all" "thread-first" "inline-symbol" "extract-function" "cycle-coll" "expand-let" "create-function"]}, :signatureHelpProvider {:triggerCharacters []}, :experimental {:testTree true, :cursorInfo true, :serverInfo true, :clojuredocs true}, :codeActionProvider {:codeActionKinds ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"], :resolveProvider true}, :hoverProvider true, :semanticTokensProvider {:legend {:tokenTypes ["namespace" "type" "function" "macro" "keyword" "class" "variable" "method" "event"], :tokenModifiers ["definition" "defaultLibrary"]}, :range true, :full true}, :codeLensProvider {:resolveProvider true}, :textDocumentSync {:openClose true, :change 1, :save {:includeText true}}, :completionProvider {:resolveProvider true, :triggerCharacters [":" "/"]}, :documentSymbolProvider true, :definitionProvider true, :documentHighlightProvider true}}
Expected:

{:capabilities {:workspaceSymbolProvider true, :documentFormattingProvider true, :documentRangeFormattingProvider true, :referencesProvider true, :linkedEditingRangeProvider true, :callHierarchyProvider true, :renameProvider {:prepareProvider true}, :executeCommandProvider {:commands ["add-missing-libspec" "add-import-to-namespace" "cycle-privacy" "create-test" "change-coll" "thread-last-all" "unwind-all" "move-to-let" "clean-ns" "suppress-diagnostic" "thread-last" "resolve-macro-as" "introduce-let" "add-missing-import" "sort-map" "unwind-thread" "thread-first-all" "thread-first" "inline-symbol" "extract-function" "cycle-coll" "expand-let" "create-function" "add-require-suggestion"]}, :signatureHelpProvider {:triggerCharacters []}, :experimental {:testTree true, :cursorInfo true, :serverInfo true, :clojuredocs true}, :codeActionProvider {:codeActionKinds ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"], :resolveProvider true}, :hoverProvider true, :semanticTokensProvider {:legend {:tokenTypes ["namespace" "type" "function" "macro" "keyword" "class" "variable" "method" "event"], :tokenModifiers ["definition" "defaultLibrary"]}, :range true, :full true}, :codeLensProvider {:resolveProvider true}, :textDocumentSync {:openClose true, :change 1, :save {:includeText true}}, :completionProvider {:resolveProvider true, :triggerCharacters [":" "/"]}, :documentSymbolProvider true, :definitionProvider true, :documentHighlightProvider true}}
expected: (= expected (some-> actual (select-keys (keys expected))))
  actual: (not (= {:capabilities {:workspaceSymbolProvider true, :documentFormattingProvider true, :documentRangeFormattingProvider true, :referencesProvider true, :linkedEditingRangeProvider true, :callHierarchyProvider true, :renameProvider {:prepareProvider true}, :executeCommandProvider {:commands ["add-missing-libspec" "add-import-to-namespace" "cycle-privacy" "create-test" "change-coll" "thread-last-all" "unwind-all" "move-to-let" "clean-ns" "suppress-diagnostic" "thread-last" "resolve-macro-as" "introduce-let" "add-missing-import" "sort-map" "unwind-thread" "thread-first-all" "thread-first" "inline-symbol" "extract-function" "cycle-coll" "expand-let" "create-function" "add-require-suggestion"]}, :signatureHelpProvider {:triggerCharacters []}, :experimental {:testTree true, :cursorInfo true, :serverInfo true, :clojuredocs true}, :codeActionProvider {:codeActionKinds ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"], :resolveProvider true}, :hoverProvider true, :semanticTokensProvider {:legend {:tokenTypes ["namespace" "type" "function" "macro" "keyword" "class" "variable" "method" "event"], :tokenModifiers ["definition" "defaultLibrary"]}, :range true, :full true}, :codeLensProvider {:resolveProvider true}, :textDocumentSync {:openClose true, :change 1, :save {:includeText true}}, :completionProvider {:resolveProvider true, :triggerCharacters [":" "/"]}, :documentSymbolProvider true, :definitionProvider true, :documentHighlightProvider true}} {:capabilities {:workspaceSymbolProvider true, :documentFormattingProvider true, :documentRangeFormattingProvider true, :referencesProvider true, :linkedEditingRangeProvider true, :callHierarchyProvider true, :renameProvider {:prepareProvider true}, :executeCommandProvider {:commands ["add-missing-libspec" "add-import-to-namespace" "cycle-privacy" "create-test" "change-coll" "thread-last-all" "unwind-all" "move-to-let" "clean-ns" "suppress-diagnostic" "thread-last" "introduce-let" "sort-map" "unwind-thread" "thread-first-all" "thread-first" "inline-symbol" "extract-function" "cycle-coll" "expand-let" "create-function"]}, :signatureHelpProvider {:triggerCharacters []}, :experimental {:testTree true, :cursorInfo true, :serverInfo true, :clojuredocs true}, :codeActionProvider {:codeActionKinds ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"], :resolveProvider true}, :hoverProvider true, :semanticTokensProvider {:legend {:tokenTypes ["namespace" "type" "function" "macro" "keyword" "class" "variable" "method" "event"], :tokenModifiers ["definition" "defaultLibrary"]}, :range true, :full true}, :codeLensProvider {:resolveProvider true}, :textDocumentSync {:openClose true, :change 1, :save {:includeText true}}, :completionProvider {:resolveProvider true, :triggerCharacters [":" "/"]}, :documentSymbolProvider true, :definitionProvider true, :documentHighlightProvider true}}))
```

```
FAIL in (stubs-generation) (/private/tmp/nix-build-clojure-lsp-test.drv-0/tmp.YHgoMIfysy/clojure-lsp/integration-test/integration/stubs_test.clj:10)
After stub generation we find datomic.api analysis and diagnostics.
Expected 1 results, but got: 0 
--
[]
--
expected: (clojure.core/= (clojure.core/count maps__150__auto__) (clojure.core/count res__151__auto__))
  actual: (not (clojure.core/= 1 0))
```

**Comment by thiagokokada** [comment]
> I've been unable to figure out the path issue within the check phase. An alternative possibility is what I pushed up -- using passthru.tests to just deal with it in its own environment. @thiagokokada I know that the last thing you want to do is add passthru.tests to more random stuff, but I'm not sure how else to get this solved!

My issue is not using `passthru.tests` per se (after that last discussion we had it seems ugly, but kinda fine).

However using `pasthru.tests` to allow cloning a repository is a big no-no, even if it works. If you really need a clone of the repository instead of the tarball, please use `fetchFromGitHub { leaveDotGit = true; };` instead.

**Comment by willcohen** [comment]
Okay -- I'll keep poking around. Thanks!

**Comment by willcohen** [comment]
For now I disabled `checkPhase` -- I'd still like to fix this but am at a loss at the moment for how to get the tests to pass here, and it might be worth bumping the version in the meantime.

**Review by ericdallo — APPROVED** [review]
I'm ok with this for now

**Comment by willcohen** [comment]
@thiagokokada does this look okay to merge, given the caveats above?

**Pull request merged**
