### PR TITLE
kdePackages.k3b: add dynamically loaded dependencies

### LINKED ISSUE #299248: K3b doesn't find libcdparanoia nor flac encoder, again
### Describe the bug
`kdePackages.k3b` fails to find libcdparanoia and flac at runtime. This is a regression from #38325, and appears to be more or less the same issue, except for Plasma 6.

### Steps To Reproduce
1. Try to rip a CD with K3b

### Expected behavior
It works, and lists Flac as a supported format.

### Additional context
The fix from #38325 should still apply in some form? Manually adding flac to `PATH` and libcdparanoia to `LD_LIBRARY_PATH` works around the problem.

### Notify maintainers
@ilya-fedin @K900 @LunNova @mjm @NickCao @SuperSandro2000 @ttuegel
also @svanderburg (maintainer for Plasma 5 K3b)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[leo60228@desktop:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05.20240323.44d0940`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `""`
 - channels(leo60228): `""`
 - nixpkgs: `/nix/store/amxd2p02wx78nyaa4bkb0hjvgwhz1dq7-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by K900**
Fixes #299248

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by leo60228** [comment]
This doesn't seem to solve the issue for me:

Could not load libcdparanoia
Flac is also still missing from the format list, despite the wrapper configuration. Running k3b inside `nix shell nixpkgs#flac` fixes this.

**Comment by K900** [comment]
Please try the latest commit.

**Comment by leo60228** [comment]
k3b now appears to be completely broken:
```console
$ k3b
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: k3b: no version information available (required by k3b)
k3b: symbol lookup error: k3b: undefined symbol: , version
```

**Comment by K900** [comment]
Try again.

**Review by leo60228 — APPROVED** [review]
The issue seems to be fixed now, thanks!

**Pull request merged**
