### PR TITLE
wmfocus: 1.1.3 -> 1.1.5

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you please follow the PR template? Thanks.

**Comment by magnetophon** [comment]
@SuperSandro2000 This is my first PR using magit forge, still learning, sorry!
I'll fix or replace this PR as soon as I know how.

**Comment by magnetophon** [comment]
@SuperSandro2000 I copy pasted for now, even though forge [should support templates](https://github.com/magit/forge/issues/25) out of the box. I'll investigate.

**Comment by SuperSandro2000** [comment]
Don't worry about it but having it just makes things easier.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101775` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wmfocus</li>
  </ul>
</details>

**Pull request merged**
