### PR TITLE
Emacs cask version update and wrapper

### PR DESCRIPTION
**Pull request by bennyandresen**
###### Motivation for this change
emacsPackages.cask was updated to 0.8.4
cask was not properly executing the cask script, but rather https://github.com/AdrieanKhisbe/cask-package-toolset.el which is an "add-on"

We should review if a top-level cask even has a reason for existing.

emacsPackage.cask can be installed and works fine (has bin/)
emacsPackageNg.cask can be installed but lacks bin/

I've now adapted the top-level cask wrapper to reference emacsPackages.cask but I'm quite sure this reference won't update when emacsPackages.cask is updated. Only a reinstall/install will properly fix it, AFAICS.

Maintainers of the packages notificaiton:
@bendlas @jgeerds 

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bendlas** [comment]
I see, that you pinged me about this on chat. Thanks for taking care of it

**Comment by bendlas** [comment]
I'll test and merge it later in the evening ..

**Comment by matthewbauer** [comment]
Ping @bendlas

**Comment by bendlas** [comment]
Oh, sorry, totally forgot ...
OK, so it seems that I completely mistook the purpose of cask-package-toolset, and also that I was developing against `emacsPackagesNg`, due to an override in my nixpkgs-config. The only explaination I have, is that i mistakenly merged a WIP commit from my HEAD.

**Comment by bendlas** [comment]
I've created an issue for emacsPackagesNg: https://github.com/NixOS/nixpkgs/issues/43521

**Comment by bendlas** [comment]
... and I've killed the top-level cask derivation: https://github.com/NixOS/nixpkgs/commit/a6f0ff33b501323e77326f7e1fcba23c9d6035a8

**Pull request merged**
