### PR TITLE
onlyoffice-bin_latest: 7.4.1 -> 7.5.1, improve inclusion of noto fonts

### PR DESCRIPTION
**Pull request by fin444**
## Description of changes

[Changelog](https://github.com/ONLYOFFICE/DesktopEditors/blob/master/CHANGELOG.md#751). The wlroots bug is still happening, so only the `_latest` package is being updated.

[OnlyOffice gathers system fonts from `/usr/share/fonts`](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx), so I moved Noto CJK fonts into the FHS instead of using the custom packaging as previously done. This is better because updates follow the main package instead of having to be done manually here, and we get all CJK fonts instead of just Simplified Chinese.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
It starts for me but I can't click on anything. It seems unresponsive. Using it on Wayland

**Comment by fin444** [comment]
@onny are you using a wlroots-based window manager? If so, this is an upstream bug. The package has been broken up into `onlyoffice-bin` (working on wlroots, outdated) and `onlyoffice-bin_latest` (broken on wlroots, up to date).

**Comment by fin444** [comment]
Should we also implement something like https://github.com/NixOS/nixpkgs/pull/259216 to un-vendor libcef? I can't think of any reason why OnlyOffice would need its own version, and it will improve security and space usage.

**Comment by fin444** [comment]
7.5.1 has been released, but they seem to have neglected non-MacOS packaging. An issue (https://github.com/ONLYOFFICE/DesktopEditors/issues/1404) was filed, but after a week I'm going to guess it just won't happen. So, we can only go to 7.5.0.

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 262126` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>onlyoffice-bin_7_5 (onlyoffice-bin_latest)</li>
  </ul>
</details>


Noto seems to work, LGTM. Thanks!

**Pull request merged**
