### PR TITLE
qt6.full: unlink qmake6

### LINKED ISSUE #239971: qmake6 gives incorrect values with qt6.full
### Describe the bug

`qmake6` provides incorrect values to Qt bins / libs etc, when `qmake` gives correct values.

### Steps To Reproduce
1. Run `nix-shell -p qt6.full`
2. Run `qmake -query`, notice that paths are inside `qt-full`
3. Run `qmake6 -query`, notice that paths are inside `qtbase`

### Expected behavior

A step 3 for `qmake6 -query` to also use `qt-full`.

### Screenshots

qmake

```bash
[nix-shell:~]# qmake -query
Detected locale "C" with character encoding "UTF-8", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
QT_SYSROOT:
QT_INSTALL_PREFIX:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1
QT_INSTALL_ARCHDATA:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1
QT_INSTALL_DATA:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1
QT_INSTALL_DOCS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/doc
QT_INSTALL_HEADERS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/include
QT_INSTALL_LIBS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/lib
QT_INSTALL_LIBEXECS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/libexec
QT_INSTALL_BINS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/bin
QT_INSTALL_TESTS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/tests
QT_INSTALL_PLUGINS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/lib/qt-6/plugins
QT_INSTALL_QML:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/lib/qt-6/qml
QT_INSTALL_TRANSLATIONS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/translations
QT_INSTALL_CONFIGURATION:
QT_INSTALL_EXAMPLES:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/examples
QT_INSTALL_DEMOS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/examples
QT_HOST_PREFIX:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1
QT_HOST_DATA:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1
QT_HOST_BINS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/bin
QT_HOST_LIBEXECS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/libexec
QT_HOST_LIBS:/nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/lib
QMAKE_SPEC:linux-g++
QMAKE_XSPEC:linux-g++
QMAKE_VERSION:3.1
QT_VERSION:6.5.1
```

qmake6

```bash
[nix-shell:~]# qmake6 -query
Detected locale "C" with character encoding "UTF-8", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
QT_SYSROOT:
QT_INSTALL_PREFIX:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1
QT_INSTALL_ARCHDATA:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1
QT_INSTALL_DATA:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1
QT_INSTALL_DOCS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/doc
QT_INSTALL_HEADERS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/include
QT_INSTALL_LIBS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/lib
QT_INSTALL_LIBEXECS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/libexec
QT_INSTALL_BINS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/bin
QT_INSTALL_TESTS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/tests
QT_INSTALL_PLUGINS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/lib/qt-6/plugins
QT_INSTALL_QML:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/lib/qt-6/qml
QT_INSTALL_TRANSLATIONS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/translations
QT_INSTALL_CONFIGURATION:
QT_INSTALL_EXAMPLES:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/examples
QT_INSTALL_DEMOS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/examples
QT_HOST_PREFIX:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1
QT_HOST_DATA:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1
QT_HOST_BINS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/bin
QT_HOST_LIBEXECS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/libexec
QT_HOST_LIBS:/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/lib
QMAKE_SPEC:linux-g++
QMAKE_XSPEC:linux-g++
QMAKE_VERSION:3.1
QT_VERSION:6.5.1
```

### Additional context

This causes issues as it is expected for Qt tooling to be available in the `QT_INSTALL_LIBEXECS` folder, however the path that `qmake6` points to is missing tooling compared to `qmake`.

eg `qmltyperegistrar` is available under `QT_INSTALL_LIBEXECS` with `qmake` but it is not available under the folder provided by `qmake6`.

qmake
```
[nix-shell:~]# ls -l /nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/libexec/qmltyperegistrar 
lrwxrwxrwx 2 root root 88 Jan  1  1970 /nix/store/sy5dy9hqshc7smrq2q7cjnllsbkg1zla-qt-full-6.5.1/libexec/qmltyperegistrar -> /nix/store/nflaf93xf4q0q6i7b3hay6nqk7b4ksp3-qtdeclarative-6.5.1/libexec/qmltyperegistrar
```
qmake6
```
[nix-shell:~]# ls -l /nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/libexec/qmltyperegistrar
ls: cannot access '/nix/store/5vn1qrh0dh60i3hnc87adsq5llxjxzyc-qtbase-6.5.1/libexec/qmltyperegistrar': No such file or directory
```

### Notify maintainers

@wegank @wineee @NickCao (sorry don't know who the maintainers are)

### Metadata

```console
[nix-shell:~]# nix-shell -p nix-info --run "nix-info -m" 
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/a4q5glbxrskhibmhn59yqjfcid1i0h1y-nix-info
copying path '/nix/store/a4q5glbxrskhibmhn59yqjfcid1i0h1y-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.8-200.fc38.x86_64, Ubuntu, 22.04.1 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/hmdjvalbmsb9x9wir7xq8y623abjl55w-source`
```

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

Closes #239971.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for the quick fix!

**Comment by vimpostor** [comment]
@wegank Was there a reason for applying this only to `qt6.full`.
The original [downstream project that failed to build](https://github.com/KDAB/cxx-qt/issues/590#issuecomment-1609112190) before this patch, now builds with `qt6.full`, but fails to build with the very same old issue when building with `qt6.qtbase + qt6.qtdeclarative`.

Shouldn't we apply this `postBuild` for `qt6.qtbase` as well?

**Comment by wegank** [comment]
The point is that `qmake6` doesn't work when called via symlink, which basically results in the following:

- Before this PR, `${qt6.full}/bin/qmake6` is a symlink to `${qt6.qtbase}/bin/qmake6`: not OK.
- After this PR, `${qt6.full}/bin/qmake6` is a real file: OK.
- For your question, `${qt6.qtbase}/bin/qmake6` is a real file: OK. There's nothing to fix.

However, if you combine `qt6.qtbase` and `qt6.qtdeclarative`, you have to do the check yourself.

**Comment by vimpostor** [comment]
Thanks for clearing that up, makes sense. Although it is a bit cumbersome, that you then no longer can do a simple `nix-shell -p qt6.qtbase qt6.qtdeclarative` and have everything working.

**Pull request merged**
