### PR TITLE
python: editorconfig fixes

### PR DESCRIPTION
**Pull request by zowoq**
###### Motivation for this change

The `editorconfig-check` hasn't been reenabled yet (probably in the next couple of days) but I though I'd try to get this in while it isn't causing conflicts with staging/staging-next.

This covers everything in `python-modules`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
@zowoq I noticed it a while ago CI would check for formatting. As far as I know it was never announced on the mailing list (Discourse). I think it should be, especially what the intention of this is. In the past, there was the conclusion we would not enforce style until a formatter was readily available.

**Comment by zowoq** [comment]
> In the past, there was the conclusion we would not enforce style until a formatter was readily available.

If you're referring to a `.nix` formatter (e.g. `nixpkgs-fmt`) this isn't just for nix files.

**Review by drewrisinger — APPROVED** [review]
Diff LGTM

**Comment by jonringer** [comment]
looks like the rebuilds are from script blocks having their extra whitespace truncated

LGTM

for @FRidh 's suggestion (notification of format standardization), I think that's separate from the python modules getting cleaned up (this PR)

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/96438
2 packages failed to build:
python37Packages.sumo python38Packages.sumo

16 packages built:
python27Packages.palettable python27Packages.rhpl python37Packages.dftfit python37Packages.lammps-cython python37Packages.nassl python37Packages.palettable python37Packages.pymatgen python37Packages.pymatgen-lammps python37Packages.sslyze python38Packages.dftfit python38Packages.lammps-cython python38Packages.nassl python38Packages.palettable python38Packages.pymatgen python38Packages.pymatgen-lammps sslyze
```

**Pull request merged**
