### PR TITLE
audacity: Use soundtouch

### PR DESCRIPTION
**Pull request by mstrm**
This enables change pitch (without changing tempo) and change tempo
(without changing pitch) effects. It works for me.

@the-kenny

### CODE REVIEW

**Comment by davidak** [comment]
it don't build on my NixOS x86_64 (running in VirtualBox):

```
$ nox-review pr 10142
[...]
/nix/store/0jr67a6f26r02gmmqd57jxxbw376d7cn-wxGTK-2.8.12.1/include/wx-2.8/wx/dynarray.h:665:5: note: in expansion of macro '_WX_DEFINE_TYPEARRAY'
     _WX_DEFINE_TYPEARRAY(_wxArray##name, name, base, classdecl)
     ^
/nix/store/0jr67a6f26r02gmmqd57jxxbw376d7cn-wxGTK-2.8.12.1/include/wx-2.8/wx/dynarray.h:646:5: note: in expansion of macro 'WX_DEFINE_TYPEARRAY_WITH_DECL'
     WX_DEFINE_TYPEARRAY_WITH_DECL(T, name, base, class wxARRAY_DEFAULT_EXPORT)
     ^
/nix/store/0jr67a6f26r02gmmqd57jxxbw376d7cn-wxGTK-2.8.12.1/include/wx-2.8/wx/dynarray.h:823:5: note: in expansion of macro 'WX_DEFINE_TYPEARRAY'
     WX_DEFINE_TYPEARRAY(T, name, wxBaseArrayPtrVoid)
     ^
effects/ladspa/../../WaveTrack.h:50:1: note: in expansion of macro 'WX_DEFINE_ARRAY'
 WX_DEFINE_ARRAY( Region*, Regions );
 ^
g++ -o ../audacity AColor.o AboutDialog.o AudacityApp.o AudioIO.o AutoRecovery.o BatchCommandDialog.o BatchCommands.o BatchProcessDialog.o Benchmark.o CaptureEvents.o Dependencies.o DeviceManager.o Envelope.o FFmpeg.o FFT.o FileIO.o FileNames.o FreqWindow.o HelpText.o HistoryWindow.o ImageManipulation.o InterpolateAudio.o LabelDialog.o LabelTrack.o Languages.o LangChoice.o Legacy.o LoadModules.o Lyrics.o LyricsWindow.o Matrix.o Menus.o Mix.o MixerBoard.o PitchName.o PlatformCompatibility.o PluginManager.o Printing.o Profiler.o Project.o RealFFTf.o Resample.o RingBuffer.o Screenshot.o Shuttle.o ShuttleGui.o ShuttlePrefs.o Snap.o Spectrum.o SplashDialog.o SoundActivatedRecord.o Tags.o Theme.o TimeDialog.o TimeTrack.o TimerRecordDialog.o Track.o TrackArtist.o TrackPanel.o TrackPanelAx.o UndoManager.o UploadDialog.o VoiceKey.o WaveClip.o WaveTrack.o WrappedType.o commands/AppCommandEvent.o commands/BatchEvalCommand.o commands/Command.o commands/CompareAudioCommand.o commands/CommandBuilder.o commands/CommandDirectory.o commands/CommandHandler.o commands/CommandManager.o commands/CommandSignature.o commands/CommandType.o commands/ExecMenuCommand.o commands/GetAllMenuCommands.o commands/GetProjectInfoCommand.o commands/GetTrackInfoCommand.o commands/HelpCommand.o commands/ImportExportCommands.o commands/Keyboard.o commands/MessageCommand.o commands/PreferenceCommands.o commands/ResponseQueue.o commands/ScreenshotCommand.o commands/ScriptCommandRelay.o commands/SelectCommand.o commands/SetProjectInfoCommand.o commands/SetTrackInfoCommand.o effects/Effect.o effects/Generator.o effects/EffectCategory.o effects/EffectManager.o effects/SimpleMono.o effects/SBSMSEffect.o effects/TimeScale.o effects/SoundTouchEffect.o effects/LoadEffects.o effects/Amplify.o effects/AutoDuck.o effects/BassTreble.o effects/Biquad.o effects/ChangePitch.o effects/ChangeSpeed.o effects/ChangeTempo.o effects/ClickRemoval.o effects/Compressor.o effects/Contrast.o effects/DtmfGen.o effects/Echo.o effects/Equalization.o effects/Fade.o effects/FindClipping.o effects/Invert.o effects/Leveller.o effects/Noise.o effects/NoiseRemoval.o effects/Normalize.o effects/Paulstretch.o effects/Phaser.o effects/Repair.o effects/Repeat.o effects/Reverb.o effects/Reverse.o effects/ScienFilter.o effects/Silence.o effects/StereoToMono.o effects/TimeWarper.o effects/ToneGen.o effects/TruncSilence.o effects/TwoPassSimpleMono.o effects/VST/VSTEffect.o effects/Wahwah.o export/Export.o export/ExportMultiple.o export/ExportMP2.o export/ExportMP3.o export/ExportOGG.o export/ExportFLAC.o export/ExportPCM.o export/ExportCL.o import/Import.o import/ImportFLAC.o import/ImportLOF.o import/ImportMP3.o import/ImportOGG.o import/ImportPCM.o import/ImportRaw.o import/RawAudioGuess.o ondemand/ODComputeSummaryTask.o ondemand/ODDecodeTask.o ondemand/ODDecodeFFmpegTask.o ondemand/ODManager.o ondemand/ODTask.o ondemand/ODTaskThread.o ondemand/ODWaveTrackTaskQueue.o prefs/BatchPrefs.o prefs/DevicePrefs.o prefs/DirectoriesPrefs.o prefs/EffectsPrefs.o prefs/GUIPrefs.o prefs/ImportExportPrefs.o prefs/KeyConfigPrefs.o prefs/LibraryPrefs.o prefs/MidiIOPrefs.o prefs/ModulePrefs.o prefs/MousePrefs.o prefs/PlaybackPrefs.o prefs/PrefsDialog.o prefs/ProjectsPrefs.o prefs/QualityPrefs.o prefs/RecordingPrefs.o prefs/SpectrumPrefs.o prefs/ThemePrefs.o prefs/TracksPrefs.o prefs/WarningsPrefs.o prefs/ExtImportPrefs.o toolbars/ControlToolBar.o toolbars/DeviceToolBar.o toolbars/EditToolBar.o toolbars/MeterToolBar.o toolbars/MixerToolBar.o toolbars/SelectionBar.o toolbars/ToolBar.o toolbars/ToolDock.o toolbars/ToolManager.o toolbars/ToolsToolBar.o toolbars/TranscriptionToolBar.o widgets/AButton.o widgets/ASlider.o widgets/AttachableScrollBar.o widgets/ErrorDialog.o widgets/ExpandingToolBar.o widgets/FileHistory.o widgets/Grabber.o widgets/Grid.o widgets/HtmlWindow.o widgets/ImageRoll.o widgets/KeyView.o widgets/LinkingHtmlWindow.o widgets/Meter.o widgets/MultiDialog.o widgets/ProgressDialog.o widgets/Ruler.o widgets/TimeTextCtrl.o widgets/Warning.o xml/XMLFileReader.o xml/XMLWriter.o ondemand/ODDecodeFlacTask.o effects/nyquist/Nyquist.o effects/nyquist/LoadNyquist.o import/ImportFFmpeg.o export/ExportFFmpeg.o export/ExportFFmpegDialogs.o NoteTrack.o import/ImportMIDI.o  effects/ladspa/LoadLadspa.o effects/ladspa/LadspaEffect.o -rdynamic  -L/tmp/nix-build-audacity-2.0.5.drv-0/audacity-src-2.0.5/lib-src/lib-widget-extra -lwidgetextra      ../lib-src/FileDialog.a ../lib-src/libsbsms.a ../lib-src/libnyquist.a ../lib-src/libportSMF.a ../lib-src/libportaudio.a ../lib-src/libportmixer.a  libaudacity.a -L/nix/store/0jr67a6f26r02gmmqd57jxxbw376d7cn-wxGTK-2.8.12.1/lib -pthread -L/nix/store/5i693m0n32axy5wfdkq3nqy30w8r369p-libXinerama-1.1.3/lib -L/nix/store/04xapqpd8m33040h51l13anpvcwdfaf5-libSM-1.2.2/lib -lwx_gtk2u_richtext-2.8 -lwx_gtk2u_aui-2.8 -lwx_gtk2u_xrc-2.8 -lwx_gtk2u_qa-2.8 -lwx_gtk2u_html-2.8 -lwx_gtk2u_adv-2.8 -lwx_gtk2u_core-2.8 -lwx_baseu_xml-2.8 -lwx_baseu_net-2.8 -lwx_baseu-2.8 -lvorbisenc -lvorbisfile -lvorbis -logg -L/nix/store/9k5f4014lyvjzxv9z9smiib9b5zdqa2f-libmad-0.15.1b/lib -lmad -L/nix/store/9kfrvbjfps8vylqbzbpakyygwsndl6li-libsndfile-1.0.25/lib -lsndfile -lFLAC++ -lFLAC -lid3tag -lexpat  -L/nix/store/vl74hwnggf2w8dah6jh1c91iv9a1mmrq-gtk+-2.24.28/lib -L/nix/store/zy7xi64lsmnx0i0d0h8qgqigs4m85crc-glib-2.44.1/lib -L/nix/store/1r9jw84v1887s65f9rwzwfgy54my7bqm-cairo-1.14.2/lib -L/nix/store/h5yzijbwy11zq5vbd0l0rgh3l8mpjram-freetype-2.5.4/lib -L/nix/store/zzdgvabkp4ymfrslj98pj3n1z500gk55-fontconfig-2.11.1/lib -L/nix/store/5m5acj0mgl1skylqpzsbg28pxrl06jpz-pango-1.36.8/lib -L/nix/store/hiii87caikz37cph4lz3g2120lw85x7q-gdk-pixbuf-2.31.7/lib -L/nix/store/f16l072nikfr1r6x5mnfb9yx8dkx24x6-atk-2.16.0/lib -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lasound -lrt
AudioIO.o: In function `AudioIO::StartStream(WaveTrackArray, WaveTrackArray, TimeTrack*, double, double, double, AudioIOListener*, bool, double, double)':
AudioIO.cpp:(.text+0x2b04): undefined reference to `Resample::Resample(bool, double, double)'
Mix.o: In function `Mixer::Mixer(int, WaveTrack**, TimeTrack*, double, double, int, int, bool, double, sampleFormat, bool, MixerSpec*)':
Mix.cpp:(.text+0x117a): undefined reference to `Resample::Resample(bool, double, double)'
Mix.cpp:(.text+0x11d3): undefined reference to `Resample::Resample(bool, double, double)'
WaveClip.o: In function `WaveClip::Resample(int, ProgressDialog*)':
WaveClip.cpp:(.text+0x5591): undefined reference to `Resample::Resample(bool, double, double)'
effects/ChangeSpeed.o: In function `EffectChangeSpeed::ProcessOne(WaveTrack*, long long, long long)':
ChangeSpeed.cpp:(.text+0x98e): undefined reference to `Resample::Resample(bool, double, double)'
ChangeSpeed.cpp:(.text+0xa7d): undefined reference to `Resample::Process(double, float*, int, bool, int*, float*, int)'
ChangeSpeed.cpp:(.text+0xd15): undefined reference to `Resample::~Resample()'
ChangeSpeed.cpp:(.text+0xd3c): undefined reference to `Resample::~Resample()'
prefs/QualityPrefs.o: In function `QualityPrefs::GetNamesAndLabels()':
QualityPrefs.cpp:(.text+0x924): undefined reference to `Resample::GetNumMethods()'
QualityPrefs.cpp:(.text+0x941): undefined reference to `Resample::GetMethodName(int)'
prefs/QualityPrefs.o: In function `QualityPrefs::PopulateOrExchange(ShuttleGui&)':
QualityPrefs.cpp:(.text+0xea1): undefined reference to `Resample::GetFastMethodDefault()'
QualityPrefs.cpp:(.text+0xeb3): undefined reference to `Resample::GetFastMethodKey()'
QualityPrefs.cpp:(.text+0x108c): undefined reference to `Resample::GetBestMethodDefault()'
QualityPrefs.cpp:(.text+0x109b): undefined reference to `Resample::GetBestMethodKey()'
collect2: error: ld returned 1 exit status
Makefile:301: recipe for target '../audacity' failed
make[1]: *** [../audacity] Error 1
make[1]: Leaving directory '/tmp/nix-build-audacity-2.0.5.drv-0/audacity-src-2.0.5/src'
Makefile:21: recipe for target 'audacity' failed
make: *** [audacity] Error 2
builder for ‘/nix/store/sc19md4zqjc2r8m12zas68mwkf4f5df5-audacity-2.0.5.drv’ failed with exit code 2
```

**Comment by mstrm** [comment]
Im also running nixos x86_64 (desktop computer) and I cant reproduce the build error. I have tried:
nox-review wip --against <latest hydra build of master branch>
nox-review pr 10142
nix-build ~/nixpkgs -A audacity
and they all build fine.

However the log complains about missing resample functions, so maybe setting resampler explicitly with --with-libsamplerate will fix it.

Any ideas how I can reproduce this error?

**Comment by davidak** [comment]
it build successfully on another computer (also NixOS x86_64 in VirtualBox) on unstable channel.

it is this feature, right? that works as known from OS X.
bildschirmfoto 2015-10-01 um 20 17 48

i tried again on the first computer and every time i get that errors. the strange thing is that they have the same amount of RAM and build using the same configuration.nix. only this is using 15.09 channel. i tried to update to unstable but i don't get a session after login. i also tried with 4 GB instead of 2 GB of RAM. i think this will be a problem on my site that no one could ever reproduce.

**Comment by mstrm** [comment]
Yes, that feature "change pitch", and "change tempo" gets added by this commit. For me those are not available on linux without soundtouch.

It is interesting that it refuses to build on you computer. The way I thought nixos worked, is that if you have the same currentSystem and the same checkout (commit) of nixpkgs on two computers, then you are guaranted that the build either works on both of them or fails on both of them (unless the builder does something crazy like fail on a certain time). 

If you have the time you could checkout this commit in nixpkgs (you dont have to upgrade your computer), and run nix-build \<path to nixpkgs\> -A audacity (on the computer that failed). The exact currentSystem for me is "x86_64-linux", which should be the same for you.

However travis also fails so maybe something is wrong.

**Comment by davidak** [comment]
travis: `The build has been terminated.`
it could have another reason like the build takes too long or something related to travis.

i will checkout it but not now. have to sleep...
maybe also someone else could test it.

as i understand it a nix-expression should build the same package on one arch. so this is maybe a problem with my computer. the host system (OS X) crashed 3 times (Kernel Panic). 2 times with this build, one with chromium build. i don't have that again after updating VirtualBox, but this build still don't work.

**Comment by the-kenny** [comment]
Trying it out now.

**Comment by the-kenny** [comment]
It's building fine on my Nixos machine here (x86_64). I'm not sure why the build crashes your Virtualbox @davidak but I suppose that's a Virtualbox issue (especially as chromium seems to cause it too).

**Comment by the-kenny** [comment]
Merged as 63e3ec8

**Pull request closed without merging**
