### PR TITLE
sage: 10.0 -> 10.2

### LINKED ISSUE #282383: Build failure: sage
### Steps To Reproduce

1. build *sage*

### Build log

https://dpaste.com/B35XMN9GV

### Notify maintainers

@timokau @collares

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 24.05 (Uakari), 24.05.20240104.df02ad5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/var/lib/nixpkgs/hellwolf-unstable`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by collares**
## Description of changes

Surprisingly painless upgrade. I'm using an autogenerated tarball containing some configuration files (e.g., `Pipfile`, `setup.cfg`, `requirements.txt`) which are generated upstream from Sage-the-distribution files (`build/pkgs/`) via the bootstrap script. I'm glad I found this tarball, because I like the idea of being isolated from Sage-the-distro files. 

An alternative would be to pass spkg arguments to the bootstrap script as in sagemath/sage#35950, but we'd need to solve issues like `./bootstrap: line 50: /build/sage-src-10.2/build/bin/sage-package: cannot execute: required file not found` due to the use of `#!/usr/bin/env sage-bootstrap-python` as a shebang in some dependencies of the bootstrap script. There are several ways around that, but all feel kind of hacky given our current package split, so the configure tarball seems best for now.

Fixes #282383. Please check ofBorg likes the upgrade before merging.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by collares** [comment]
@ofborg build sageWithDoc

**Comment by collares** [comment]
@ofBorg build sageWithDoc

**Comment by collares** [comment]
Docbuilding failure, will look at it later:

```
[tutorial ] Extension error:
[tutorial ] Notebook execution failed (exception: [Errno 2] No such file or directory: '/nix/store/1dv5m71dgl6n8dxd7riqjz094vqmyws8-python3-3.11.7/bin/sage')
```

**Comment by timokau** [comment]
Thank you for your continued maintenance of sage! I know that this is a lot of work.

**Comment by collares** [comment]
Sage tests pass now. `pplpy` fails on x86_64-darwin, but that is also the case on Nixpkgs master.

**Comment by collares** [comment]
Rebased on top of the fpylll update. This should be good to go. 

@timokau @7c6f434c @omasanori are you happy with merging this?

**Comment by 7c6f434c** [comment]
Looks good!

**Comment by timokau** [comment]
Yes, fine by me :)

**Comment by collares** [comment]
Thank you!

**Comment by hellwolf** [comment]
I still have problem building sage from unstable:

```
$ nix build .#sage
error: builder for '/nix/store/dqs8zz45330l72r9y3kimnny070wj4gr-python3.11-primecountpy-0.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > checking for references to /build/ in /nix/store/dhf01bl49dmqj6bwdaw82nz585xyh1fy-python3.11-primecountpy-0.1.0-dist...
       > patching script interpreter paths in /nix/store/dhf01bl49dmqj6bwdaw82nz585xyh1fy-python3.11-primecountpy-0.1.0-dist
       > Executing pythonRemoveTestsDir
       > Finished executing pythonRemoveTestsDir
       > Running phase: pythonCatchConflictsPhase
       > Found duplicated packages in closure for dependency 'cython':
       >  cython 0.29.36 (/nix/store/hn15nr4k2zk2akfyv0szcwg21zdnds6k-python3.11-cython-0.29.36/lib/python3.11/site-packages/Cython-0.29.36.dist-info)
       >   cython 3.0.6 (/nix/store/xx59gyk65a4s5vrmql8dyddx69dbvwfi-python3.11-cython-3.0.6/lib/python3.11/site-packages/Cython-3.0.6.dist-info)
       >
       > Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
       For full logs, run 'nix log /nix/store/dqs8zz45330l72r9y3kimnny070wj4gr-python3.11-primecountpy-0.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/kd6ig9860k1lvls641zznvs0616k8sf5-python3-3.11.7-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rw9412qz125d7h1wfdsdzzl6vjkm3r8b-python3.11-sagelib-10.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hlcszwgsclllah0cjfmz6jkkvpy2vy43-sage-with-env-10.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l7arwkx6f3hq8i5llyzdisr4qj827335-sage-10.0.drv' failed to build
```

**Comment by 7c6f434c** [comment]
`.` is a checkout? What revision?

**Comment by collares** [comment]
Cross-referencing https://github.com/NixOS/nixpkgs/issues/282383#issuecomment-1913327430; it seems to be working now.

**Pull request merged**
