### PR TITLE
nixos/tests/qemu-vm-volatile-root: init

### PR DESCRIPTION
**Pull request by nikstur**
###### Description of changes

Add a test for mounting the root filesystem as a volatile tmpfs via the qemu-vm module.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nikstur** [comment]
@lilyinstarlight do you think it's a good idea to merge this first and then once we get it working with the systemd initrd, we parameterize the test?

**Comment by nikstur** [comment]
Created the issue: https://github.com/NixOS/nixpkgs/issues/240175

**Comment by lilyinstarlight** [comment]
@ofborg test qemu-vm-volatile-root

**Review by lilyinstarlight — APPROVED** [review]
Looks good now, thank you!

I'll see if I can find the time to debug the test with systemd-initrd in #240175. Should we maybe add that issue to one of the qemu vm or systemd stage 1 project boards?

**Comment by nikstur** [comment]
That's a good idea! I added it to the QEMU VM test refactor board. I can't see any systemd stage 1 board. Maybe only the team can see it?

**Comment by lilyinstarlight** [comment]
> That's a good idea! I added it to the QEMU VM test refactor board. I can't see any systemd stage 1 board. Maybe only the team can see it?

It's probably because it's a classic project. You should be able to see https://github.com/NixOS/nixpkgs/projects/51, but the qemu-vm test board is probably fine

**Pull request merged**
