### PR TITLE
neovim: expose the neovim-unwrapped manpage

### PR DESCRIPTION
**Pull request by 0paIescent**
###### Motivation for this change

Install the neovim manpage along with the neovim package. Before, the manpage was only installed with neovim-unwrapped.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions (Fedora, Void)
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after) (`Difference of +624`)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by doronbehar — CHANGES_REQUESTED** [review]
This wrapper gets more and more complicated, I wonder why doesn't it use `symlinkJoin` as it would just grab everything there is in `neovim-unwrapped`. But that's out of scope for this PR. Could you move your addition a bit upwards? Before `optionalString (!stdenv.isDarwin)` so Darwin users will enjoy this enhancement it as well?

**Comment by 0paIescent** [comment]
I had thought about that as well, I don't think `symlinkJoin` would be the best solution since the binary gets built from `makeWrapper`, and share is the only other folder involved. I don't see why `/share/{locale,man,nvim,pixmaps}` couldn't be symlinked, and if not on darwin then symlink and subtitute the desktop file.

I'll submit another PR to add that, but since that PR will just update what gets pushed in this one, should I just close this one and submit the other to avoid a useless commit?

**Comment by doronbehar** [comment]
Sometimes, in my own overlays, I do something like this:

```nix
          octave-wrapped = super.symlinkJoin rec {
            name = "octave-wrapped";
            paths = [ super.octave ];
            pythonEnv = super.python3.withPackages(ps: [
              ps.sympy
            ]);
            nativeBuildInputs = [ super.makeWrapper ];
            # along with some fixes to the desktop file
            postBuild = ''
              cp -L $out/bin/octave $out/bin/octave.tmp
              mv -f $out/bin/octave.tmp $out/bin/octave
              wrapProgram $out/bin/octave --prefix PATH : ${pythonEnv}/bin
              cp -L $out/share/applications/org.octave.Octave.desktop $out/share/applications/org.octave.Octave.desktop.tmp
              mv -f $out/share/applications/org.octave.Octave.desktop.tmp $out/share/applications/org.octave.Octave.desktop
              substituteInPlace $out/share/applications/org.octave.Octave.desktop \
                --replace "Terminal=false" "Terminal=true" \
                --replace "octave --gui" octave
            '';
          };
```

Which may seem a bit hacky but I think it's not that bad. If I were the original writer of the neovim wrapper function I'd do this. I think it'll be best for you to wait a few days and see what the neovim maintainers think about this.

**Comment by 0paIescent** [comment]
Right, that is much cleaner. I'll just wait and see what happens.

**Comment by teto** [comment]
https://github.com/NixOS/nixpkgs/pull/87929#issuecomment-629663425 sounds good, no need to open another PR

**Comment by 0paIescent** [comment]
@teto Sounds good to me, I might as well mention I've got another [branch](https://github.com/NixOS/nixpkgs/compare/master...0paIescent:symlinkJoin_neovim?diff=unified) where I replaced `mkDerivation` with `symlinkJoin` if we want to merge that in while we're messing with neovim.

**Comment by doronbehar** [comment]
That branch looks good. Maybe this is not related to the issue at hand, but if someone wants to wrap Neovim with a `configure` argument, isn't the end executable gets wrapped twice?

**Comment by 0paIescent** [comment]
Yeah it'll be wrapped twice, but the arguments passed to the first wrap will be propagated up to the final binary. I don't really see a clean way to only wrap once without another `optionalString`, I feel like that would clutter up the `postBuild`.

**Comment by doronbehar** [comment]
> I don't really see a clean way to only wrap once without another optionalString , I feel like that would clutter up the postBuild .

I disagree that there's no clean way to do it. The problem is that the current way the wrapper function is implemented is of low quality (if you ask me). [I once wrote](https://github.com/doronbehar/nixpkgs/blob/2aacb90748d2cfa1d64a8faf492d0ae4fc889394/pkgs/build-support/neowrap.nix) a generic wrapper Nix function that "compiles" a string which in turn becomes a list of arguments to `wrapProgram`. For Neovim's wrapper function it should be fairly easy to do something similar, it's just a bit hard to dive into the functional programming concept.

**Comment by 0paIescent** [comment]
Fair point, however that would be way over my head in terms of how skilled I am in Nix, I wouldn't even know where to start in making something like that.

**Comment by Infinisil** [comment]
With https://github.com/NixOS/nixpkgs/pull/88110, the man pages and everything else is now in the wrapped neovim

**Pull request closed without merging**
