### PR TITLE
R: regenerate CRAN and BIOC packages

### PR DESCRIPTION
**Pull request by michelk**

### CODE REVIEW

**Comment by jagajaga** [comment]
cc @peti

**Comment by peti** [comment]
Did you check that the package set evaluates properly after those updates?

**Comment by peti** [comment]
Merged in 75f6e547aad4531705043b66841905148f5e962e. The update will go to `master` once the test builds at http://hydra.cryp.to/jobset/nixpkgs/r-updates are through.

**Comment by michelk** [comment]
> Did you check that the package set evaluates properly after those updates?

Yes, after updating, I ran 

    nix-build test-evaluation.nix --dry-run

**Comment by peti** [comment]
@michelk, thank you for the update!

**Pull request closed without merging**
