### PR TITLE
inav-configurator: 5.1.0 -> 7.1.1, 6.1.0, versioned packaging

### PR DESCRIPTION
**Pull request by ilya-epifanov**
Also added 6.x branch for INAV 6 support

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ilya-epifanov** [comment]
depends on https://github.com/NixOS/nixpkgs/pull/310808

**Comment by ilya-epifanov** [comment]
@wucke13 @TilCreator  please take a look

**Comment by ilya-epifanov** [comment]
@Rose-David @MikaelFangel @marcusramberg could you please take a look at this PR?

**Comment by MikaelFangel** [comment]
This PR should be split into separate PR's one PR updating the package from 5.1.0 -> 7.1.1 and one where you suggested versioned packaging. Moreover, you should motivate the PR where you create the versioned packaging, as it is not that common. The typical way would be to use overrideAttrs if another version is needed.

**Comment by ilya-epifanov** [comment]
The rationale behind versioned packaging is very simple. INAV configurator 5.x only supports INAV 5.x, 6.x only supports INAV 6.x and so on. If the firmware flies well, there's no need to upgrade.

Regarding splitting it into separate PRs, I propose splitting it like this:
* inav-configurator: support versioned packaging
* inav-configurator: rename to inav-configurator-5
* inav-configurator-6: init at 6.1.0
* inav-configurator-7: init at 7.1.1

@MikaelFangel @marcusramberg @Rose-David what do you think?

**Comment by ilya-epifanov** [comment]
I'll do the same for https://github.com/NixOS/nixpkgs/pull/310811

**Comment by ilya-epifanov** [comment]
Please see https://github.com/NixOS/nixpkgs/pull/320052 https://github.com/NixOS/nixpkgs/pull/320054 https://github.com/NixOS/nixpkgs/pull/320055 and https://github.com/NixOS/nixpkgs/pull/320056

**Pull request closed without merging**
