### PR TITLE
solaar: add support for tray icon

### LINKED ISSUE #118622: solaar: TypeError: Argument 1 does not allow None as a value
**Describe the bug**

Solaar crashes with the following error:

```
Traceback (most recent call last):
  File "/nix/store/48hgb7x5q46xi0vgyach2p8cqirr7c3n-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/__init__.py", line 143, in <lambda>
    application.connect('startup', lambda app, startup_hook:_startup(app,startup_hook,use_tray,show_window), startup_hook)
  File "/nix/store/48hgb7x5q46xi0vgyach2p8cqirr7c3n-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/__init__.py", line 101, in _startup
    window.init(show_window, use_tray)
  File "/nix/store/48hgb7x5q46xi0vgyach2p8cqirr7c3n-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/window.py", line 744, in init
    Gtk.Window.set_default_icon_from_file(_icons.icon_file(NAME.lower()))
TypeError: Argument 0 does not allow None as a value
Traceback (most recent call last):
  File "/nix/store/48hgb7x5q46xi0vgyach2p8cqirr7c3n-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/__init__.py", line 112, in _activate
    app.add_window(window._window)
TypeError: Argument 1 does not allow None as a value
```

**Notify maintainers**

@spinus @ysndr

### PR DESCRIPTION
**Pull request by Artturin**
fix https://github.com/NixOS/nixpkgs/issues/118622

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by spinus** [comment]
@Artturin thank you, that's good stuff.
I tested and there seems to be one issue. Potentially wrapper breaks some solar arg0 detection and solaar-cli runs GUI with no argument.

**Comment by Artturin** [comment]
> @Artturin thank you, that's good stuff. I tested and there seems to be one issue. Potentially wrapper breaks some solar arg0 detection and solaar-cli runs GUI with no argument.

there's a comment that says 
```
  # the -cli symlink is just to maintain compabilility with older versions where
  # there was a difference between the GUI and CLI versions.
```
so there is no issue

**Comment by spinus** [comment]
Thanks for explaining, but that still is kind of strange. What kind of compatibility it is when you run cli tool and GUI tool starts opening?

**Comment by Artturin** [comment]
> Thanks for explaining, but that still is kind of strange. What kind of compatibility it is when you run cli tool and GUI tool starts opening?



i didn't add it it was added in 6e7fac368f9c0f4558e32fa41c406a674d722fbe

**Pull request merged**
