### PR TITLE
Elisp updates

### PR DESCRIPTION
**Pull request by bhankas**
## Description of changes

Includes and requires changes from #295805. Will keep it rebased on top of it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bhankas** [comment]
@adisbladis @AndersonTorres separate PR for grammar updates as requested.

**Comment by AndersonTorres** [comment]
Rebase and remove the elisp updates

**Comment by akirak** [comment]
@bhankas You didn't update tree-sitter grammars, did you? You've updated some elisp packages and add some grammars for updating, but didn't update grammars. If that's your intention, it would be nice if you changed the PR title.

**Comment by bhankas** [comment]
@akirak Yes, I've been meaning to update the PR but haven't been able to. Will try to fix in a day or two.

**Comment by bhankas** [comment]
Apologies for extreme late response, but I think this one is conservative enough.

This builds on top of #295805, and updates elisp packages. The change in `update-defaults.py` is same as before, as the script fails without.

Still unsure how to get `gleam-ts-mode` in nixpkgs since it is in non-default branch, also unsure if the built grammar will be available to emacs itself during runtime so `gleam-ts-mode` can make use of it if pulled via use-package.

@AndersonTorres please take a look whenever possible.

**Comment by AndersonTorres** [comment]
Remove the Elisp updates.

They mass-rebuild and therefore should go to Staging.

**Comment by AndersonTorres** [comment]
> > Remove the Elisp updates.
> > They mass-rebuild and therefore should go to Staging.
> 
> In that case this PR can be closed in favor of #295805 , what do you say?

Yes, it's even better. 
Tree-Sitter updates are useful for other users besides Emacs power users.

**Comment by bhankas** [comment]
Thanks, closing this.

**Pull request closed without merging**
