### PR TITLE
habitat: 0.30.2 -> 0.90.6

### PR DESCRIPTION
**Pull request by bhipple**
The build has been broken on master for a very long time, for want of an
upgrade. This continues the effort put forth here:
https://github.com/NixOS/nixpkgs/pull/63105

Note that while there are newer versions than this, upgrading to those requires
getting some Cargo protobuf dependencies to compile. Since this fixes the
failing build, it seems like a good start.

Also includes Rust upgrade for https://github.com/NixOS/nixpkgs/issues/79975

Changelog:
https://github.com/habitat-sh/habitat/blob/master/CHANGELOG.md#0906-2019-11-13

CC @rushmorem @boj

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bhipple** [comment]
This compiles and passes its entire test suite, but I haven't done any work beyond that to verify.

**Comment by Mic92** [comment]
@GrahamcOfBorg build habitat

**Comment by bhipple** [comment]
Hmm, Darwin is failing; should I just restrict platforms or is there a way I can test?  I only have a Linux machine, so I was carrying over some of the Darwin stuff from the previous PR's attempts.

**Comment by Mic92** [comment]
It is also not clear to me how they build the thing on macOS actually: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/hab.rb#L6
I don't see any CI code for building the macOS binary.
cc @davidMcneil ?

**Comment by bhipple** [comment]
I have updated to simply remove the Darwin variant for the time being.  Since this fixes the broken linux build it's still an improvement over the status quo.

**Comment by bhipple** [comment]
@GrahamcOfBorg build habitat

**Comment by alyssais** [comment]
Would have been nicer to mark broken on Darwin, since upstream does support the software there.

**Pull request merged**
