### PR TITLE
[WIP] systemd: patch to build on musl

### PR DESCRIPTION
**Pull request by dtzWill**
Patches largely from OE which just updated to 237,
few needed rebasing but nothing major.

NixOS uses systemd, and until now using musl
meant many things were not possible.

There are some org issues (I think?) to tackle
before it's possible to instantiate an NixOS config
using a custom localSystem parameter (aka using musl)
so I've yet to really test this in "action"
yet (container, VM).

Even so, this is a giant step for musl support!

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I was unsure how to best apply all of the patches-- you can see
previous approaches in commit history for things like:

* Last time (pre-237): https://github.com/dtzWill/nixpkgs/commit/143796ff08ac47cce2e80e9defec65816c0b2093
* Earlier today: https://github.com/dtzWill/nixpkgs/releases/tag/systemd-musl-237-1

To keep this less crazy-looking I've instead combined the patches
(well, github combines them for us) which we fetch and apply as a single
"musl support patch".

Note that patch is actually against v238-stable, not our fork,
to keep it orthogonal to our NixOS changes.

### CODE REVIEW

**Comment by dtzWill** [comment]
cc https://github.com/NixOS/rfcs/pull/23 .

This targets staging since that's where the latest systemd is (v238), not because it introduces any breakage (to supported platforms or otherwise).

**Comment by saschagrunert** [comment]
@dtzWill May I ask you if we have any update on this? I would love to see it in.

**Comment by offlinehacker** [comment]
Any updates on this?

**Comment by arianvp** [comment]
there are some parts in musl lacking that we really need in order to make it work on NixOS as far as I know.

Most importantly; the ability to dispatch calls to `nscd` so that you can use `nss` modules.  Systemd ecosystem relies heavily on `nss` and I don't see that working on NixOS + musl any time soon..

Systemd is heavily dependend on `glibc` semantics and upstream doesn't seem very warm in supporting  adaptations to work around `musl` bugs https://github.com/systemd/systemd/issues/10130

Given the `systemd` maintainer team on NixOS is already pretty spread thin and we can not piggyback on upstream helping with this either, I do not think we can do a good job at maintaining an alternative libc in a bug-free manner. We already have enough glibc/nscd bugs to manage today.

We have recently been trying really hard to reduce the custom amount of patches that we carry to below 10 and preferably to 0; so that we can keep up with `systemd-stable` better and ship updates to our users quicker. This PR introduces another 53 patches which we would have to maintain which I don't have any interest in myself.

I'm not opposed to merging this under some alternative package name; but I will not be putting time in maintaining this myself.

**Comment by Mic92** [comment]
Maybe there could be a libsystemd/libudev alternative so that more musl packages can be built at least.

**Comment by arianvp** [comment]
Hmm... and I suppose those build targets should also be easier to build than the entirety of systemd no?

I think `udev` currently is just an alias for the `systemd` package; but could just build that specific `meson` target instead...

**Comment by arianvp** [comment]
@Mic92  both `libudev` and `libsystemd` can be built statically I recently discovered.  So they'll probably (hopefully) also be more friendly to build with musl?

**Comment by jorsn** [comment]
> Maybe there could be a libsystemd/libudev alternative so that more musl packages can be built at least. – @Mic92 

For packages only using libudev and not libsystemd, there is eudev ([project page](https://wiki.gentoo.org/wiki/Project:Eudev)), the Gentoo fork of udev which is already in nixpkgs. Maybe it can be used as a drop-in for systemd-udev. The Gentoo wiki (almost?) suggests this (https://wiki.gentoo.org/wiki/Eudev#Migrating_from_udev_to_eudev), but it is unclear whether it's outdated.

From the above linked project page:

> In specific it tries to avoid glibc-specific functions and gcc-specific constructs by sticking to C99 while tracking closely the systemd-udev developments.

@arianvp you said

> @Mic92 both `libudev` and `libsystemd` can be built statically I recently discovered. So they'll probably (hopefully) also be more friendly to build with musl?

Can they be built statically with musl or only glibc?

**Comment by Mic92** [comment]
> > Maybe there could be a libsystemd/libudev alternative so that more musl packages can be built at least. – @Mic92
> 
> For packages only using libudev and not libsystemd, there is eudev ([project page](https://wiki.gentoo.org/wiki/Project:Eudev)), the Gentoo fork of udev which is already in nixpkgs. Maybe it can be used as a drop-in for systemd-udev. The Gentoo wiki (almost?) suggests this ([wiki.gentoo.org/wiki/Eudev#Migrating_from_udev_to_eudev](https://wiki.gentoo.org/wiki/Eudev#Migrating_from_udev_to_eudev)), but it is unclear whether it's outdated.
> 
> From the above linked project page:
> 
> > In specific it tries to avoid glibc-specific functions and gcc-specific constructs by sticking to C99 while tracking closely the systemd-udev developments.
> 
> @arianvp you said
> 
> > @Mic92 both `libudev` and `libsystemd` can be built statically I recently discovered. So they'll probably (hopefully) also be more friendly to build with musl?
> 
> Can they be built statically with musl or only glibc?

It might be worth to set `libudev = eudev` on in nixpkgs for musl than.

**Comment by domenkozar** [comment]
Closing as systemd has evolved in last 2 years.

**Pull request closed without merging**
