### PR TITLE
nextcloud-client: fix crash

### LINKED ISSUE #55639: nextcloud client segfaults
## Issue description
Nextcloud client app segfaults when sync starts.

This issue is similar to #52259 but this happens with nix package.

### Steps to reproduce
0. start with no config
1. enter nextcloud account info
2. select folders to sync
3. click Sync -> segfault

## Technical details
```
Received signal 11 <unknown> 000000000000
#0 0x7f2e1e800f2e <unknown>
#1 0x7f2e1e8013da <unknown>
#2 0x7f2e1e801925 <unknown>
#3 0x7f2e14fffc20 <unknown>
#4 0x7f2e1e7b303c <unknown>
#5 0x7f2e1e12e908 <unknown>
#6 0x7f2e1e12ea74 <unknown>
#7 0x7f2e1e12efe3 <unknown>
#8 0x7f2e1e478e4f <unknown>
#9 0x7f2e1e487f4d <unknown>
#10 0x7f2e1e29ae89 <unknown>
#11 0x7f2e1e29b051 <unknown>
#12 0x7f2e1e2a23c7 <unknown>
#13 0x7f2e1e2a25e1 <unknown>
#14 0x7f2e1e2829f1 <unknown>
#15 0x7f2e1e2a6fbc <unknown>
#16 0x7f2e1e2a7139 <unknown>
#17 0x7f2e1e378df6 <unknown>
#18 0x7f2e1e75e91a <unknown>
#19 0x7f2e1e78823a <unknown>
#20 0x7f2e1e788d05 <unknown>
#21 0x7f2e1e788e6a <unknown>
#22 0x7f2e1cbbb1a5 <unknown>
#23 0x7f2e16701e5b QObject::event()
#24 0x7f2e174b3a0c QApplicationPrivate::notify_helper()
#25 0x7f2e174baf90 QApplication::notify()
#26 0x7f2e166d15e8 QCoreApplication::notifyInternal2()
#27 0x7f2e166d4147 QCoreApplicationPrivate::sendPostedEvents()
#28 0x7f2e1672efa3 <unknown>
#29 0x7f2e0c6b3d6f g_main_context_dispatch
#30 0x7f2e0c6b4020 g_main_context_iterate.isra.26
#31 0x7f2e0c6b41fc g_main_context_iteration
#32 0x7f2e1672e5bf QEventDispatcherGlib::processEvents()
#33 0x7f2e166cf90a QEventLoop::exec()
#34 0x7f2e166d8de0 QCoreApplication::exec()
#35 0x5625f401d8d6 main
#36 0x7f2e14fecb5e __libc_start_main
#37 0x5625f401dcba _start
  r8: 0000000000000001  r9: 0000000000000000 r10: 0000000000000000 r11: 00007f2dac1953a2
 r12: 00005625f4ff8e40 r13: 00007fff9e0d2f50 r14: 00007fff9e0d2f70 r15: 0000000000000001
  di: 00005625f4ff8e40  si: 00007f2e21f3ffe0  bp: 00007fff9e0d2e90  bx: 00005625f4ff8e40
  dx: 00005625f4ff8e50  ax: 0030005f00000000  cx: 00005625f4ff8e50  sp: 00007fff9e0d2e90
  ip: 00007f2e1e7b303c efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000000
 trp: 000000000000000d msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```
*Nextcloud client version*
```
% nextcloud --version                      
Nextcloud version 2.5.1git
Using Qt 5.12.0, built against Qt 5.12.0
Using 'OpenSSL 1.0.2q  20 Nov 2018'
```

The backend runs Nextcloud v. 15.0.0. 

Nextcloud client v. 2.5.1 works on Arch Linux so the problem is likely NixOS-related.

### nix-info
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 19.03pre169108.36f31600749 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre169108.36f31600749"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by averelld**
###### Motivation for this change
Fixes #55639 
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by flokli** [comment]
@GrahamcOfBorg build nextcloud-client

**Comment by Ma27** [comment]
built and tested locally :+1:

**Comment by flokli** [comment]
@Ma27 can you backport to 18.09?

**Comment by Ma27** [comment]
Ok, you were slightly faster than me :sweat_smile: 

As `release-18.09` also uses 2.5.1 I guess it's affected as well and I'll backport :)

**Comment by Ma27** [comment]
(backport will be delayed, I'm currently building a lot of stuff on `release-18.09` and it'll take some more time...)

**Pull request merged**
