### PR TITLE
pahole: 1.23 -> 1.24

### PR DESCRIPTION
**Pull request by martinetd**
###### Description of changes

upstream changelog: https://git.kernel.org/pub/scm/devel/pahole/pahole.git/tag/?h=v1.24

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by martinetd** [comment]
@ofborg test bpf

**Comment by vcunat** [comment]
This broke build of some kernels: https://hydra.nixos.org/eval/1784097#tabs-now-fail
```
FAILED: load BTF from vmlinux: Unknown error -22
```

**Comment by vcunat** [comment]
I now reproduced the `linux_5_10` failure on master.

**Comment by vcunat** [comment]
I suppose we should fix or revert (for now) within several hours.

**Comment by martinetd** [comment]
ofborg unfortunately tested 5.15: https://logs.nix.ci/?key=nixos/nixpkgs.194551&attempt_id=cb2350f5-c8ae-47c9-9979-597656fd6311

..and I don't reproduce with nix develop + allnoconfig + reenable BTF, so this is going to take me quite a while to investigate in details/fix.
Let's revert for now; please say if you want me to open a PR for the revert, I'll focus on reproducing for now...

**Comment by martinetd** [comment]
Thanks!
Honest question: would it help if I'd target staging instead of master for pahole updates in the future?
I could get ofborg to build more kernels in the future (or better add these to passthru tests), but it might be better to use staging for that, I still don't understand how the branches should be used sorry.

**Comment by vcunat** [comment]
That way the issue would most likely get discovered before getting to master.  (and it would take longer time)  Either way, I can build kernels for you locally.  OfBorg can be also instructed by comments to build anything, but building all kernels is probably too expensive and would time out there.

**Comment by martinetd** [comment]
> That way the issue would most likely get discovered before getting to master. (and it would take longer time) 

If the issue ends up getting found just before merging to master with similar pressure to fix or revert quickly there isn't much point. If it's found through hydra (or similar) and there's a day or so to fix/investigate then it'd be better for me though. Well, I guess ultimately just reverting isn't such a bad thing :)

Also, thanks for the offer to build kernels, that'd really help!


So, with a real 5.10 build I could reproduce, not sure why partial build wasn't enough.
I've bisected it pahole-side, the culprit is apparently this commit: https://git.kernel.org/pub/scm/devel/pahole/pahole.git/commit/?id=35a11221b305a5204402ce7467adfdbac8971f77
so old kernel cannot handle enum64, which is reasonable enough.

With that in hand we also have a workaround: I've wrapper around pahole to `/nix/store/x97giklkshrnw71gj6zn7qpxr4wi1px7-pahole-1.24/bin/pahole "$@" --skip_encoding_btf_enum64` with v1.24's build and vmlinux builds ok.

Now for the $3 questions:
 - why does linux 5.15 appear to build? They don't have ENUM64 any more than 5.10 does (or 5.19 for that matter, it got added to v6.0 in https://git.kernel.org/torvalds/c/58a53978fdf65d12dae1798e44120efb992a3615...)
    -> Someone did the work upstream... https://git.kernel.org/stable/c/b775fbf532dc01ae53a6fc56168fd30cb4b0c658
 - I guess I'll just send something similar upstream for 5.10, are there any other stable versions we care about that require this?
   - patch sent for 5.10 https://lkml.kernel.org/r/20221027120158.2791406-1-asmadeus@codewreck.org
   - note 5.19 is EOL, so I don't consider that worth fixing (at least useless to patch upstream); we'll probably remove linux-5.19.nix soon enough.
   - conversely I don't seem to recall 5.4 and older were failing in your link, not sure if they weren't tested, if they don't have BTF enabled, or something else? Would you be able to run a build with pahole 1.24 and kernel 5.4 ?
 
Thanks!

**Comment by vcunat** [comment]
All kernels that we build should be in there.  Here's a filter making it easier to browse: https://hydra.nixos.org/eval/1784097?filter=kernels.linux_#tabs-still-succeed

**Comment by martinetd** [comment]
Thanks, then I'll just re-open (a copy of) this PR after 5.10 got updated upstream and we've picked it up, and that should be good.

**Pull request merged**
