### PR TITLE
wireguard-tools: 0.0.20190913 -> 0.0.20191012

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change
https://lists.zx2c4.com/pipermail/wireguard/2019-October/004594.html

Also decided to add myself to the maintainers list as I use WireGuard
pretty heavily for private/work-related stuff and I intend to help taking care
of the WireGuard ecosystem in NixOS as well.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Ma27** [comment]
@ofborg test wireguard wireguard-generated

**Comment by Mic92** [comment]
We usually also backport wireguard to stable, since it is still experimental.

**Comment by Ma27** [comment]
Do you want to do this? Otherwise I could do the backport tonight :)

**Comment by Mic92** [comment]
I am also in the office right now.

**Comment by Ma27** [comment]
Backported as 4ddaf40a7dc05ca2599be06e9bb7020a220f5c19.

**Pull request merged**
