### PR TITLE
wire-desktop: add ozone platform hint for wayland

### PR DESCRIPTION
**Pull request by MangoIV**
## Description of changes

added support for wayland for wire-desktop

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 335608` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by MangoIV** [comment]
Ofborg doesn’t seem request maintainer review, so please excuse me for pinging you myself.

@arianvp @toonn 

thanks for reviewing.

**Review by toonn — APPROVED** [review]
LGTM, don't have a Wayland setup to test on but I take it it's working?

P.s.: No need to apologize for pinging maintainers IMO.

**Comment by MangoIV** [comment]
> but I take it it's working

yes, the app starts.

**Comment by 1e-1xer** [comment]
just so you know, this broke wire for me while running X. it was giving me the error:

`[###/###:ERROR:wayland_connection.cc(196)] Failed to connect to Wayland display: No such file or directory (2)
[###/###:ERROR:ozone_platform_wayland.cc(264)] Failed to initialize Wayland platform
[###/###:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.`

not sure if that's just an issue with my specific setup or whatever. i fixed it for now by changing `wire-desktop` in my packages to
`(wire-desktop.overrideAttrs (oldAttrs: {
    preFixup = '''';
    })
 )`

i'm sure an if statement before the `preFixup` declaration to check if the user is on wayland would handle it, however that's done in nix. i'm not good an neither nix nor github or i'd submit a pr myself, sorry

**Comment by MangoIV** [comment]
will try to get back the old behaviour.

**Comment by JohnRTitor** [comment]
I'd note that this does work on Wayland. I am on Hyprland.

**Comment by MangoIV** [comment]
I have tried to replicate what gitkraken does and this is what I came up with: https://github.com/NixOS/nixpkgs/pull/346189

however, I'm not entirely sure why this works while it doesn't work without doing the buildPackages thing. Maybe someone can enlighten me. Perhaps also someone can try it out with `X`? :pleading_face:

**Pull request merged**
