### PR TITLE
Dlang update 2018-12

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

Updating dlang related packages to newer versions.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ThomasMader** [comment]
@grahamcofborg build ldc dmd dtools dub Literate

**Comment by ThomasMader** [comment]
https://github.com/NixOS/nixpkgs/pull/51720 is now obsolete because of this PR.

**Comment by ThomasMader** [comment]
This is ready to be merged.
The test build on linux failed but the build machine probably has a old nix version. It seems to be this problem: https://github.com/NixOS/nix/issues/2155

**Comment by xeji** [comment]
ofborg build timed out, let's try again
@GrahamcOfBorg build ldc dmd dtools dub Literate

**Comment by xeji** [comment]
builds still timed out on ofborg but succeeded locally

**Pull request merged**
