### PR TITLE
kmod: drop darwin support

### PR DESCRIPTION
**Pull request by trofi**
###### Description of changes

commit 7a2c07d29bf9b "kmod: enable on darwin" added darwin
support mostly for `depmod` to be able to build `linux` kernel
on `darwin`.

In version 30 kmod requires more and more linux syscalls to build.
Instead of patching it for darwin let's drop it's support instead.

Maybe `depmod` could be packaged using some other way if needed.

Related: https://github.com/NixOS/nixpkgs/pull/182720 removed
`kmod` use on `darwin` from rare packages that still pulled it in.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
The patch applies and builds on linux, but it's not enough to make it build on darwin :(: `clock_nanosleep()` is not a thing there. Switching to a draft.

**Comment by trofi** [comment]
Removing `kmod` from darwin depends took very little: https://github.com/NixOS/nixpkgs/pull/182720

@matthewbauer as an author of https://github.com/NixOS/nixpkgs/commit/7a2c07d29bf9bb7582e5df2dfcb879278d65a8e8 WDYT of dropping `darwin` support for `kmod` in `nixpkgs`?

**Comment by trofi** [comment]
Changed to `linux`-only `kmod`. Ready to review.

**Review by fpletz — APPROVED** [review]

**Comment by vcunat** [comment]
I wonder why it's marked with so many rebuilds.  If that's a mistake, perhaps target at `staging-next`, as the kmod update is in there already?  (PR #182386)

**Comment by wegank** [comment]
Maybe someone could wrap [this](https://rt.cpan.org/Public/Bug/Display.html?id=78656) up on Darwin, just like the `memstreamHook` stuffs...

**Pull request merged**
