### PR TITLE
gromacs: add the plumed patches

### PR DESCRIPTION
**Pull request by zimbatm**
## Description of changes

This PR integrates the plumed patches into gromacs.

plumed 2.9.0 only supports gromacs-2023 so I had to downgrade the
package as well.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sheepforce — APPROVED** [review]
Although its not super nice to have two different source versions of Gromacs, I see why it's necessary. LGTM.

**Comment by markuskowa** [comment]
I would like to avoid having two Gromacs version.
Could patching plumed be a solution? See https://github.com/plumed/plumed2/pull/961
This might already be fixed upstream.

**Comment by zimbatm** [comment]
> I would like to avoid having two Gromacs version.

What I could do is override plumed2 to use an unreleased source if you prefer. The main reason I didn't do it is because plumed2 is always going to be catching up to Gromacs. And each release of Gromacs is going to be delayed a little bit in nixpkgs because of that. But you know best what the context is for this package.

**Comment by markuskowa** [comment]
@sheepforce is there a reason we can't upgrade plumed instead? It is still on the 2.9 branch, while 2.9 has been released earlier this year.

**Comment by sheepforce** [comment]
This is a general problem with plumed,.I guess. The model of incorporation to a set.og packages is, that plumed will patch the source code of the interfaced programmes. Basically patches that are bundled with the plumed distribution. At the moment it's only gromacs, but there are other that operate in this model https://www.plumed.org/doc-v2.9/user-doc/html/_installation.html#Patching

So for diverging versions we can always think about backporting the plumed patches or pinning the MD codes. Both solutions are suboptimal but workable.

**Comment by zimbatm** [comment]
Since there is no clear best possible choice, would you agree to merge this and then learn from experience? Feel free to ping me again if it becomes annoying to deal with.

**Comment by markuskowa** [comment]
Okay. I don't have a better idea either at the moment. Let's see how it goes.

**Pull request merged**
