### PR TITLE
nixos/qemu-vm: allow use without a disk image

### PR DESCRIPTION
**Pull request by lheckemann**
###### Description of changes

Allows creating QEMU VMs without a disk image, using a tmpfs for /. <del>Draft, because I'm not happy with the interface. It's awkward to add filesystems to opt-in to persistence manually.</del> It's still a significant improvement from before.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lheckemann** [comment]
cc @T0astBread who implemented virtualisation.fileSystems in the first place

**Comment by T0astBread** [comment]
+1 for diskless VMs. You can already kind of achieve that through the use of `useDefaultFilesystems` like so:

```nix
{ config, pkgs, lib, ... }:
{
  virtualisation.vmVariant = {
    virtualisation.useDefaultFilesystems = false;

    virtualisation.diskImage = "/dev/null";

    virtualisation.fileSystems = {
      "/" = {
        fsType = "tmpfs";
      };
    };
  };
}
```

But using `/dev/null` for `diskImage` is a hack, so the changes here make sense.

We should preserve the (slightly awkward) `optionalAttrs` + `//` dance for building `fileSystems` though as that lets users override entries for default filesystems with `useDefaultFilesystems` disabled. (`mkIf` still generates values in that case that would replace user-provided definitions at `mkVMOverride` priority.)

---

Also small correction, I've only done `virtualisation.useDefaultFilesystems`, not all of `virtualisation.fileSystems`. :slightly_smiling_face:

**Comment by lheckemann** [comment]
Thanks for your review!

I don't understand the rationale for using `optionalAttrs` and `//` here. Can you share an example of a config that you don't know how to represent with the implementation I propose?

**Comment by T0astBread** [comment]
Sorry for the delay! Nevermind I thought overriding the default filesystems wouldn't work that way but I just tried it with `nixos/tests/non-default-filesystems.nix` on [`master`](https://github.com/NixOS/nixpkgs/blob/4e7604d35012de06712dd1ebd90588ad3dc37e37/nixos/tests/non-default-filesystems.nix) and on this branch and it passes on both. I haven't tried `nixos-rebuild buld-vm` but I guess it's the same. So I have nothing to add here.

**Comment by lheckemann** [comment]
I'll go ahead and merge this then, thanks!

**Pull request merged**
