### PR TITLE
nixos/gitlab: use patched git version from gitaly

### PR DESCRIPTION
**Pull request by mvnetbiz**
###### Description of changes

Build git with patches from gitlab, use it in the gitlab module.
Without this, when git-pulling I got this error

```
$ git pull
fatal: commit-graph requires overflow generation data but has none
fatal: the remote end hung up unexpectedly
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bgamari** [comment]
Indeed we have encountered this issue in the haskell.org installation. @talyz, do you think we could merge and backport this to 22.05?

**Comment by chreekat** [comment]
This version seems fragile since it will depend on always bumping the git version to precisely the right version for each update to gitlab. Is there no better way? Can we not use the build system Gitaly itself supplies? ("make git" from the gitaly repo)

**Comment by chreekat** [comment]
Ah ok I was afraid of something like that.

**Comment by talyz** [comment]
Hm, I tried cherry-picking this to stable, which solved the issue for me. Then I tried switching to 2.36.0, but saw the issue reappear. Lastly, I tried downgrading to 2.35.1 again, but without the patches, which again solved the issue, so it seems the issue was simply caused by the upgrade of git.

**Comment by talyz** [comment]
Seeing as this isn't dependent on the patches, but the version of git, I've created a simpler alternative in #177776. That gets us a more up-to-date version of git and should be easier to keep updated.

**Comment by mvnetbiz** [comment]
Not sure why it's easier to keep updated, it's just version number and sha256. Also are the gitlab patches not important anyways?

**Comment by talyz** [comment]
Mainly because it's decoupled from the version of gitaly and just implements a workaround that should be removed when the bug is fixed upstream.

**Comment by yu-re-ka** [comment]
I don't have any opinion on using the vendored / patched version of git vs our upstream git package.

However if the vendored version is introduced, it should be integrated with the gitlab update scripts, since the entire rest of the gitlab updates are automated and updating the git version / hash / patches could easily be forgotten.

**Pull request closed without merging**
