### PR TITLE
nixos-rebuild-ng: add --add-root in nix.remote_build

### LINKED ISSUE #365225: nixos-rebuild-ng: GC race condition with --build-host
## Describe the bug

There are two warnings when building with `--build-host`: `warning: you did not specify '--add-root'; the result might be removed by the garbage collector`.
The first time it is because you evaluate the config on the local host, then the second time on the build host when you realize.

The underlying problem is a race condition: the GC could delete the drv and the realization before you copy/activate them.

This problem exists in the legacy nixos-rebuild.

Relevant trace:
```
$ nixos-rebuild-ng -f default.nix -A bob switch --target-host bob --build-host bob -v
[...]
building the system configuration...
debug: nixos_rebuild.process: calling run with args=['nix-instantiate', PosixPath('default.nix'), '--attr', 'bob.config.system.build.toplevel', '-v'], kwargs={'stdout': -1}, extra_env=None
[...]
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
[...]
debug: nixos_rebuild.process: calling run with args=['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/nixos-rebuild.ehxn453f/ssh-%n', '-o', 'ControlPersist=60', 'bob', '--', 'nix-store', '--realise', '/nix/store/1g3pbhalxk7gsg99jsj4kzjg0kpsyv7d-nixos-system-bob-24.11pre-git.drv', '-v'], kwargs={'stdout': -1}, extra_env=None
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
[...]
```

## Notify maintainers

@thiagokokada

### PR DESCRIPTION
**Pull request by thiagokokada**
Fix: #365225.

Untested since I have no non-Flakes systems.

The idea of this PR is not really to remove the race conditions, only to hide the warnings. The race condition situation is really unlikely to happen, and doesn't seem to be an issue in `nixos-rebuild` right now, so I think we can ignore at least until someone starts having actual issues with it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thiagokokada** [comment]
CC @jlamur to test.

**Comment by thiagokokada** [comment]
CC @jlamur for testing.

**Comment by jlamur** [comment]
Sorry I am not in front of my PC at the moment. I will test and make a
review before tomorrow.

**Review by jlamur — APPROVED** [review]
I just tested with build-host/target-host and with only target-host: it works well!
I reviewed the code quickly and it LGTM!

Thank you again for your very appreciated work!

**Comment by thiagokokada** [comment]
> I just tested with build-host/target-host and with only target-host: it works well!
> I reviewed the code quickly and it LGTM!
> 
> Thank you again for your very appreciated work!
 Hey, can you share me the logs with `-v` or `--debug` just to make sure that everything is correct? Only for `--build-host` and `--target-host` case is enough.

**Comment by jlamur** [comment]
@thiagokokada 

Here you go :-) 
```
$ nixos-rebuild-ng switch -f default.nix -A bob --target-host bob --build-host bob --debug
debug: nixos_rebuild.process: calling run with args=['nix-instantiate', '--find-file', 'nixpkgs'], kwargs={'stdout': -1}, extra_env=None
debug: nixos_rebuild.process: captured output stdout='/nix/store/5wvrlpfrwlmg24ywkybvidyzcvki6bwx-source\n', stderr=None
debug: nixos_rebuild.process: calling run with args=['git', '-C', PosixPath('/nix/store/5wvrlpfrwlmg24ywkybvidyzcvki6bwx-source'), 'rev-parse', '--short', 'HEAD'], kwargs={'capture_output': True}, extra_env=None
debug: nixos_rebuild.process: captured output stdout='', stderr='fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n'
building the system configuration...
debug: nixos_rebuild.process: calling run with args=['nix-instantiate', PosixPath('default.nix'), '--attr', 'bob.config.system.build.toplevel', '--add-root', PosixPath('/tmp/nixos-rebuild.ya7377on/98b7b4e36121436686888e9187344654')], kwargs={'stdout': -1}, extra_env=None
debug: nixos_rebuild.process: captured output stdout='/tmp/nixos-rebuild.ya7377on/98b7b4e36121436686888e9187344654\n', stderr=None
debug: nixos_rebuild.process: calling run with args=['nix-copy-closure', '--to', 'bob', PosixPath('/nix/store/1g3pbhalxk7gsg99jsj4kzjg0kpsyv7d-nixos-system-bob-24.11pre-git.drv')], kwargs={}, extra_env={'NIX_SSHOPTS': '-o ControlMaster=auto -o ControlPath=/tmp/nixos-rebuild.ya7377on/ssh-%n -o ControlPersist=60'}
copying 0 paths...
debug: nixos_rebuild.process: calling run with args=['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/nixos-rebuild.ya7377on/ssh-%n', '-o', 'ControlPersist=60', 'bob', '--', 'mktemp', '-d', '-t', 'nixos-rebuild.XXXXX'], kwargs={'stdout': -1}, extra_env=None
debug: nixos_rebuild.process: captured output stdout='/tmp/nixos-rebuild.IsPkl\n', stderr=None
debug: nixos_rebuild.process: calling run with args=['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/nixos-rebuild.ya7377on/ssh-%n', '-o', 'ControlPersist=60', 'bob', '--', 'nix-store', '--realise', '/nix/store/1g3pbhalxk7gsg99jsj4kzjg0kpsyv7d-nixos-system-bob-24.11pre-git.drv', '--add-root', '/tmp/nixos-rebuild.IsPkl/1bb48eea92c34bb3a33b1d669b2413cc'], kwargs={'stdout': -1}, extra_env=None
debug: nixos_rebuild.process: captured output stdout='/tmp/nixos-rebuild.IsPkl/1bb48eea92c34bb3a33b1d669b2413cc\n', stderr=None
debug: nixos_rebuild.process: calling run with args=['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/nixos-rebuild.ya7377on/ssh-%n', '-o', 'ControlPersist=60', 'bob', '--', 'readlink', '-f', '/tmp/nixos-rebuild.IsPkl/1bb48eea92c34bb3a33b1d669b2413cc'], kwargs={'stdout': -1}, extra_env=None
debug: nixos_rebuild.process: captured output stdout='/nix/store/fsr5bpy8mrxzplr6cpllh9npypv0mm67-nixos-system-bob-24.11pre-git\n', stderr=None
debug: nixos_rebuild.process: calling run with args=['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/nixos-rebuild.ya7377on/ssh-%n', '-o', 'ControlPersist=60', 'bob', '--', 'rm', '-rf', '/tmp/nixos-rebuild.IsPkl'], kwargs={}, extra_env=None
debug: nixos_rebuild.process: calling run with args=['nix', 'copy', '--from', 'ssh://bob', '--to', 'ssh://bob', PosixPath('/nix/store/fsr5bpy8mrxzplr6cpllh9npypv0mm67-nixos-system-bob-24.11pre-git')], kwargs={}, extra_env={'NIX_SSHOPTS': '-o ControlMaster=auto -o ControlPath=/tmp/nixos-rebuild.ya7377on/ssh-%n -o ControlPersist=60'}
debug: nixos_rebuild.process: calling run with args=['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/nixos-rebuild.ya7377on/ssh-%n', '-o', 'ControlPersist=60', 'bob', '--', 'nix-env', '-p', '/nix/var/nix/profiles/system', '--set', '/nix/store/fsr5bpy8mrxzplr6cpllh9npypv0mm67-nixos-system-bob-24.11pre-git'], kwargs={}, extra_env=None
debug: nixos_rebuild.process: calling run with args=['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/nixos-rebuild.ya7377on/ssh-%n', '-o', 'ControlPersist=60', 'bob', '--', 'env', 'NIXOS_INSTALL_BOOTLOADER=0', '/nix/store/fsr5bpy8mrxzplr6cpllh9npypv0mm67-nixos-system-bob-24.11pre-git/bin/switch-to-configuration', 'switch'], kwargs={}, extra_env={'NIXOS_INSTALL_BOOTLOADER': '0'}
activating the configuration...
setting up /etc...
reloading user units for root...
restarting sysinit-reactivation.target
debug: nixos_rebuild.process: calling run with args=['ssh', '-o', 'ControlPath=/tmp/nixos-rebuild.ya7377on/ssh-bob', '-O', 'exit', 'dummyhost'], kwargs={'capture_output': True}, extra_env=None
debug: nixos_rebuild.process: captured output stdout='', stderr='Exit request sent.\n'
```

It looked fine to me for both the remote part (mktemp; --add-root on nix-store --realise; and rm -rf) and the local part (--add-root on nix-instantiate).

Are you searching for something else in particular? Let me know if I can help.

**Comment by thiagokokada** [comment]
> Are you searching for something else in particular? Let me know if I can help.

No, just want to double check that everything worked as expected.

Thanks, that was useful.

**Pull request merged**
