### PR TITLE
ifcopenshell: 210410 -> 0.7.0a9

### PR DESCRIPTION
**Pull request by GenericNerdyUsername**
###### Description of changes

ifcopenshell: 210410 -> 0.7.0a9

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Alizter** [comment]
This uses a ridiculous amount of memory when building. What is going on?

**Comment by GenericNerdyUsername** [comment]
How many threads were you building with?

**Comment by Alizter** [comment]
I was building with 20.

**Comment by GenericNerdyUsername** [comment]
8 was fine on my 16gb laptop, though it might have used swap, didn't check

**Comment by Alizter** [comment]
Result of `nixpkgs-review pr 217656` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>ifcopenshell (python310Packages.ifcopenshell)</li>
    <li>python311Packages.ifcopenshell</li>
  </ul>
</details>

**Review by Alizter — APPROVED** [review]

**Comment by wegank** [comment]
Merge conflict, please rebase.

**Comment by autra** [comment]
For reference, I have starting a similar work + I wanted to split the native package and the python package, so that we don't need to rebuild everything on each python version: https://github.com/NixOS/nixpkgs/pull/312381

(note, I don't mind if this one is merged before mine, as mine is not ready yet. I'll rebase if needed)

**Comment by luzpaz** [comment]
Probably should be closed in favor of https://github.com/NixOS/nixpkgs/pull/347916 ?

**Pull request closed without merging**
