### PR TITLE
doc: consistent formatting on python manual section

### PR DESCRIPTION
**Pull request by bhipple**
No material changes to docs, but trying to sanitize them for consistent
readability prior to looking at #75837.

- Use `*` for lists instead of `-`. I have no opinion one way or the other, but
  the latter was only used in 1-2 places.
- Pad the code blocks with whitespace.
- Wrap to 80 characters, except for a few 1-liners that were only slightly over.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
@bhipple can you add some rules to the `.editorconfig` matching the changes you did here?

**Review by veprbl — APPROVED** [review]
LGTM

**Comment by bhipple** [comment]
I've looked at all the `.editorconfig` settings here and don't see anything relevant:
https://editorconfig-specification.readthedocs.io/en/latest/

Are you aware of any to add?  The word wrapping around 80 characters is usually the default that most people have setup in their editrs, though I don't see a setting for it in editorconfig at any rate.

**Comment by flokli** [comment]
@bhipple I thought about maybe something like `max_line_length = 80` for `[*.md]` files.

**Comment by bhipple** [comment]
From reading the documentation, `max_line_length` does not appear to be an option in `.editorconfig`, which seems a little surprising.  That said, even if it did, I believe the default in most editors is 80 anyways.

**Comment by flokli** [comment]
@bhipple Hm, this only seems to be a suggestion, not a standard.

I see a big red line in my vim and line wrapping happens, but anyways - fine to not include it.

**Pull request merged**
