### PR TITLE
gitnuro: add libGL

### PR DESCRIPTION
**Pull request by zendo**
## Description of changes

https://github.com/JetpackDuba/Gitnuro/releases

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by zendo** [comment]
fix https://github.com/NixOS/nixpkgs/issues/278507

**Comment by AndersonTorres** [comment]
Dunno if this is the case, but recently @TomaSajt is tracking issues on determinism from Java apps:

https://github.com/NixOS/nixpkgs/issues/278518

**Comment by TomaSajt** [comment]
> Dunno if this is the case, but recently @TomaSajt is tracking issues on determinism from Java apps:
I think this package uses prebuilt jars, so there shouldn't be an issue with reproducibility

**Comment by pbsds** [comment]
Then please set `meta.sourceProvenance = with sourceTypes; [ binaryBytecode ];`

**Comment by pbsds** [comment]
Sorry, i caused a merge conflict. Please rebase.

**Comment by pbsds** [comment]
Seems like this bump drops support for previously supported platforms like aarch64-linux and darwin. Were those always broken, or can you add download urls and hashes for those platforms as well?

https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.gitnuro.aarch64-linux
https://hydra.nixos.org/job/nixpkgs/trunk/gitnuro.x86_64-darwin
https://hydra.nixos.org/job/nixpkgs/trunk/gitnuro.aarch64-darwin

**Comment by julius-boettger** [comment]
> Seems like this bump drops support for previously supported platforms like aarch64-linux and darwin. Were those always broken, or can you add download urls and hashes for those platforms as well?

I don't know if it ever ran on `aarch64-linux` or Darwin, but Gitnuro definitely changed something with [v1.3.0](https://github.com/JetpackDuba/Gitnuro/releases/tag/v1.3.0).

Before that version, they just released a single `Gitnuro-linux-X.X.X.jar`, now they release two binaries for Linux: `Gitnuro-linux-x86_64-X.X.X.jar` and `Gitnuro-linux-arm_aarch64-X.X.X.jar`. 

An extra `Gitnuro-macos-X.X.X.zip` seems to have always existed for Darwin.

At least for the two Linux `jar`s it should be enough to just download the one corresponding to your platform with the correct hash. Don't know about Darwin.

**Comment by julius-boettger** [comment]
Also: Why was #298099 merged recently, but this PR here is still open?

This PR has the desperately needed fix for #278507 / #302550, which #298099 doesn't. I can't the Gitnuro that is currently in nixpkgs `unstable` (v1.3.1 from #298099) because of said issues, so I would really like to see this PR merged :smiley: @zendo @pbsds

**Comment by pbsds** [comment]
I go between a lot of PRs, i'm sorry i didn't connect the two.

Can this PR be rebased to include the fix? Would love to have it in time for the 24.05 release.

**Comment by julius-boettger** [comment]
Looking good!

I tried adding `aarch64` support on a copy of this package in my configuration. [See this commit](https://github.com/julius-boettger/dotfiles/commit/876aaea3709f17dbe68b8894f9a4124fd67bf9cf). I don't know if this is the proper way to do what we want to do here, but it should work. At least it does for `x86_64`. I admittedly could not test it on an `aarch64` device, as I don't own one (yet).

If these circumstances are acceptable, I would appreciate it if something similar could already be part of this PR, as I plan to get an `aarch64` device rather soon. @zendo

Otherwise, this PR looks ready for another review from @pbsds. Thanks!

**Comment by pbsds** [comment]
LGTM

@julius-boettger your diff looks sane. Lets not block this PR any further, please submit it as a separate PR.

**Pull request merged**
