### PR TITLE
miniupnpc: 2.2.7 -> 2.2.8 , support static build

### PR DESCRIPTION
**Pull request by nagy**
## Description of changes

New release 

https://github.com/miniupnp/miniupnp/releases/tag/miniupnpc_2_2_8

and support building with `pkgsStatic`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by fpletz — APPROVED** [review]
LGTM. Confirmed that the removed postInstall fixes are not necessary anymore.

**Comment by K900** [comment]
This is an API break: https://github.com/miniupnp/miniupnp/issues/758

Which is likely to affect most downstreams. Reverting until addressed in some way.

**Comment by nagy** [comment]
Should we introduce a `miniupnpc_2_2_7` package and call affected packages with that?

**Comment by K900** [comment]
I genuinely don't know, it's touching a pretty core part of the API, so someone needs to investigate the real impact and see if the affected packages can be patched. If not, maybe we should just hold off on updating this.

**Comment by emilazy** [comment]
I would be interested in triaging and patching stuff here, including sending stuff upstream. Going by https://github.com/transmission/transmission/pull/6907/files#diff-5631965d253feb0720bcea80f285ac7e3fb20818fe46fc846706b3dba8e9b32c, it’s just a matter of adding `NULL, 0` to the argument list. A shame that upstream doesn’t seem to priority API stability even for a trivial case like this, though.

**Comment by K900** [comment]
Have fun, I guess. I honestly don't care which way we go as long as we don't break everything.

**Comment by emilazy** [comment]
I’ve started on this.

**Comment by emilazy** [comment]
Done: https://github.com/NixOS/nixpkgs/pull/326402

**Pull request merged**
