### PR TITLE
[Backport release-22.05] zen-kernels: 5.17.7 -> 5.18.9

### PR DESCRIPTION
**Pull request by PedroHLC**
###### Description of changes

Backports: #174577, #176194, #177951, #161773 and #180264.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Atemu — APPROVED** [review]
Diff LGTM!

Can't test stable but this "only" backports all the updates to the zen kernels to the same state as on master.

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 180275` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>136 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_lqx.akvcam</li>
    <li>linuxKernel.packages.linux_lqx.bbswitch</li>
    <li>linuxKernel.packages.linux_lqx.dddvb</li>
    <li>linuxKernel.packages.linux_lqx.dpdk</li>
    <li>linuxKernel.packages.linux_lqx.dpdk-kmods</li>
    <li>linuxKernel.packages.linux_lqx.ena</li>
    <li>linuxKernel.packages.linux_lqx.facetimehd</li>
    <li>linuxKernel.packages.linux_lqx.intel-speed-select</li>
    <li>linuxKernel.packages.linux_lqx.ixgbevf</li>
    <li>linuxKernel.packages.linux_lqx.kvdo</li>
    <li>linuxKernel.packages.linux_lqx.lttng-modules</li>
    <li>linuxKernel.packages.linux_lqx.mxu11x0</li>
    <li>linuxKernel.packages.linux_lqx.ndiswrapper</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_lqx.nvidiabl</li>
    <li>linuxKernel.packages.linux_lqx.openafs</li>
    <li>linuxKernel.packages.linux_lqx.openafs_1_8</li>
    <li>linuxKernel.packages.linux_lqx.openafs_1_9</li>
    <li>linuxKernel.packages.linux_lqx.phc-intel</li>
    <li>linuxKernel.packages.linux_lqx.r8125</li>
    <li>linuxKernel.packages.linux_lqx.r8168</li>
    <li>linuxKernel.packages.linux_lqx.rtl8188eus-aircrack</li>
    <li>linuxKernel.packages.linux_lqx.rtl8189es</li>
    <li>linuxKernel.packages.linux_lqx.rtl8192eu</li>
    <li>linuxKernel.packages.linux_lqx.rtl8723bs</li>
    <li>linuxKernel.packages.linux_lqx.rtl8812au</li>
    <li>linuxKernel.packages.linux_lqx.rtl8821ce</li>
    <li>linuxKernel.packages.linux_lqx.rtl88xxau-aircrack</li>
    <li>linuxKernel.packages.linux_lqx.sch_cake</li>
    <li>linuxKernel.packages.linux_lqx.tbs</li>
    <li>linuxKernel.packages.linux_lqx.virtualbox</li>
    <li>linuxKernel.packages.linux_lqx.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_lqx.vmware</li>
    <li>linuxKernel.packages.linux_lqx.xmm7360-pci</li>
    <li>linuxKernel.packages.linux_zen.akvcam</li>
    <li>linuxKernel.packages.linux_zen.bbswitch</li>
    <li>linuxKernel.packages.linux_zen.dddvb</li>
    <li>linuxKernel.packages.linux_zen.dpdk</li>
    <li>linuxKernel.packages.linux_zen.dpdk-kmods</li>
    <li>linuxKernel.packages.linux_zen.ena</li>
    <li>linuxKernel.packages.linux_zen.facetimehd</li>
    <li>linuxKernel.packages.linux_zen.intel-speed-select</li>
    <li>linuxKernel.packages.linux_zen.ixgbevf</li>
    <li>linuxKernel.packages.linux_zen.kvdo</li>
    <li>linuxKernel.packages.linux_zen.lttng-modules</li>
    <li>linuxKernel.packages.linux_zen.mxu11x0</li>
    <li>linuxKernel.packages.linux_zen.ndiswrapper</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_zen.nvidiabl</li>
    <li>linuxKernel.packages.linux_zen.openafs</li>
    <li>linuxKernel.packages.linux_zen.openafs_1_8</li>
    <li>linuxKernel.packages.linux_zen.openafs_1_9</li>
    <li>linuxKernel.packages.linux_zen.phc-intel</li>
    <li>linuxKernel.packages.linux_zen.r8125</li>
    <li>linuxKernel.packages.linux_zen.r8168</li>
    <li>linuxKernel.packages.linux_zen.rtl8188eus-aircrack</li>
    <li>linuxKernel.packages.linux_zen.rtl8189es</li>
    <li>linuxKernel.packages.linux_zen.rtl8192eu</li>
    <li>linuxKernel.packages.linux_zen.rtl8723bs</li>
    <li>linuxKernel.packages.linux_zen.rtl8812au</li>
    <li>linuxKernel.packages.linux_zen.rtl8821ce</li>
    <li>linuxKernel.packages.linux_zen.rtl88xxau-aircrack</li>
    <li>linuxKernel.packages.linux_zen.sch_cake</li>
    <li>linuxKernel.packages.linux_zen.tbs</li>
    <li>linuxKernel.packages.linux_zen.virtualbox</li>
    <li>linuxKernel.packages.linux_zen.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_zen.vmware</li>
    <li>linuxKernel.packages.linux_zen.xmm7360-pci</li>
    <li>linuxPackages_lqx.akvcam</li>
    <li>linuxPackages_lqx.bbswitch</li>
    <li>linuxPackages_lqx.dddvb</li>
    <li>linuxPackages_lqx.dpdk</li>
    <li>linuxPackages_lqx.dpdk-kmods</li>
    <li>linuxPackages_lqx.ena</li>
    <li>linuxPackages_lqx.facetimehd</li>
    <li>linuxPackages_lqx.intel-speed-select</li>
    <li>linuxPackages_lqx.ixgbevf</li>
    <li>linuxPackages_lqx.kvdo</li>
    <li>linuxPackages_lqx.lttng-modules</li>
    <li>linuxPackages_lqx.mxu11x0</li>
    <li>linuxPackages_lqx.ndiswrapper</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy340</li>
    <li>linuxPackages_lqx.nvidiabl</li>
    <li>linuxPackages_lqx.openafs</li>
    <li>linuxPackages_lqx.openafs_1_8</li>
    <li>linuxPackages_lqx.openafs_1_9</li>
    <li>linuxPackages_lqx.phc-intel</li>
    <li>linuxPackages_lqx.r8125</li>
    <li>linuxPackages_lqx.r8168</li>
    <li>linuxPackages_lqx.rtl8188eus-aircrack</li>
    <li>linuxPackages_lqx.rtl8189es</li>
    <li>linuxPackages_lqx.rtl8192eu</li>
    <li>linuxPackages_lqx.rtl8723bs</li>
    <li>linuxPackages_lqx.rtl8812au</li>
    <li>linuxPackages_lqx.rtl8821ce</li>
    <li>linuxPackages_lqx.rtl88xxau-aircrack</li>
    <li>linuxPackages_lqx.sch_cake</li>
    <li>linuxPackages_lqx.tbs</li>
    <li>linuxPackages_lqx.virtualbox</li>
    <li>linuxPackages_lqx.virtualboxGuestAdditions</li>
    <li>linuxPackages_lqx.vmware</li>
    <li>linuxPackages_lqx.xmm7360-pci</li>
    <li>linuxPackages_zen.akvcam</li>
    <li>linuxPackages_zen.bbswitch</li>
    <li>linuxPackages_zen.dddvb</li>
    <li>linuxPackages_zen.dpdk</li>
    <li>linuxPackages_zen.dpdk-kmods</li>
    <li>linuxPackages_zen.ena</li>
    <li>linuxPackages_zen.facetimehd</li>
    <li>linuxPackages_zen.intel-speed-select</li>
    <li>linuxPackages_zen.ixgbevf</li>
    <li>linuxPackages_zen.kvdo</li>
    <li>linuxPackages_zen.lttng-modules</li>
    <li>linuxPackages_zen.mxu11x0</li>
    <li>linuxPackages_zen.ndiswrapper</li>
    <li>linuxPackages_zen.nvidia_x11_legacy340</li>
    <li>linuxPackages_zen.nvidiabl</li>
    <li>linuxPackages_zen.openafs</li>
    <li>linuxPackages_zen.openafs_1_8</li>
    <li>linuxPackages_zen.openafs_1_9</li>
    <li>linuxPackages_zen.phc-intel</li>
    <li>linuxPackages_zen.r8125</li>
    <li>linuxPackages_zen.r8168</li>
    <li>linuxPackages_zen.rtl8188eus-aircrack</li>
    <li>linuxPackages_zen.rtl8189es</li>
    <li>linuxPackages_zen.rtl8192eu</li>
    <li>linuxPackages_zen.rtl8723bs</li>
    <li>linuxPackages_zen.rtl8812au</li>
    <li>linuxPackages_zen.rtl8821ce</li>
    <li>linuxPackages_zen.rtl88xxau-aircrack</li>
    <li>linuxPackages_zen.sch_cake</li>
    <li>linuxPackages_zen.tbs</li>
    <li>linuxPackages_zen.virtualbox</li>
    <li>linuxPackages_zen.virtualboxGuestAdditions</li>
    <li>linuxPackages_zen.vmware</li>
    <li>linuxPackages_zen.xmm7360-pci</li>
  </ul>
</details>
<details>
  <summary>110 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_lqx.kernel (linuxKernel.kernels.linux_lqx)</li>
    <li>linuxPackages_zen.kernel (linuxKernel.kernels.linux_zen)</li>
    <li>linuxPackages_lqx.acpi_call (linuxKernel.packages.linux_lqx.acpi_call)</li>
    <li>linuxPackages_lqx.apfs (linuxKernel.packages.linux_lqx.apfs)</li>
    <li>linuxPackages_lqx.asus-ec-sensors (linuxKernel.packages.linux_lqx.asus-ec-sensors)</li>
    <li>linuxPackages_lqx.asus-wmi-sensors (linuxKernel.packages.linux_lqx.asus-wmi-sensors)</li>
    <li>linuxPackages_lqx.batman_adv (linuxKernel.packages.linux_lqx.batman_adv)</li>
    <li>linuxPackages_lqx.broadcom_sta (linuxKernel.packages.linux_lqx.broadcom_sta)</li>
    <li>linuxPackages_lqx.can-isotp (linuxKernel.packages.linux_lqx.can-isotp)</li>
    <li>linuxPackages_lqx.chipsec (linuxKernel.packages.linux_lqx.chipsec)</li>
    <li>linuxPackages_lqx.cryptodev (linuxKernel.packages.linux_lqx.cryptodev)</li>
    <li>linuxPackages_lqx.ddcci-driver (linuxKernel.packages.linux_lqx.ddcci-driver)</li>
    <li>linuxPackages_lqx.digimend (linuxKernel.packages.linux_lqx.digimend)</li>
    <li>linuxPackages_lqx.evdi (linuxKernel.packages.linux_lqx.evdi)</li>
    <li>linuxPackages_lqx.fwts-efi-runtime (linuxKernel.packages.linux_lqx.fwts-efi-runtime)</li>
    <li>linuxPackages_lqx.gcadapter-oc-kmod (linuxKernel.packages.linux_lqx.gcadapter-oc-kmod)</li>
    <li>linuxPackages_lqx.hid-nintendo (linuxKernel.packages.linux_lqx.hid-nintendo)</li>
    <li>linuxPackages_lqx.isgx (linuxKernel.packages.linux_lqx.isgx)</li>
    <li>linuxPackages_lqx.it87 (linuxKernel.packages.linux_lqx.it87)</li>
    <li>linuxPackages_lqx.jool (linuxKernel.packages.linux_lqx.jool)</li>
    <li>linuxPackages_lqx.kvmfr (linuxKernel.packages.linux_lqx.kvmfr)</li>
    <li>linuxPackages_lqx.liquidtux (linuxKernel.packages.linux_lqx.liquidtux)</li>
    <li>linuxPackages_lqx.mba6x_bl (linuxKernel.packages.linux_lqx.mba6x_bl)</li>
    <li>linuxPackages_lqx.mbp2018-bridge-drv (linuxKernel.packages.linux_lqx.mbp2018-bridge-drv)</li>
    <li>linuxPackages_lqx.mwprocapture (linuxKernel.packages.linux_lqx.mwprocapture)</li>
    <li>linuxPackages_lqx.netatop (linuxKernel.packages.linux_lqx.netatop)</li>
    <li>linuxPackages_lqx.nvidia_x11 (linuxKernel.packages.linux_lqx.nvidia_x11)</li>
    <li>linuxPackages_lqx.nvidia_x11_beta (linuxKernel.packages.linux_lqx.nvidia_x11_beta)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy390 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy390)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy470 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy470)</li>
    <li>linuxPackages_lqx.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_lqx.openrazer (linuxKernel.packages.linux_lqx.openrazer)</li>
    <li>linuxPackages_lqx.rr-zen_workaround (linuxKernel.packages.linux_lqx.rr-zen_workaround)</li>
    <li>linuxPackages_lqx.rtl8814au (linuxKernel.packages.linux_lqx.rtl8814au)</li>
    <li>linuxPackages_lqx.rtl8821au (linuxKernel.packages.linux_lqx.rtl8821au)</li>
    <li>linuxPackages_lqx.rtl8821cu (linuxKernel.packages.linux_lqx.rtl8821cu)</li>
    <li>linuxPackages_lqx.rtl88x2bu (linuxKernel.packages.linux_lqx.rtl88x2bu)</li>
    <li>linuxPackages_lqx.rtw88 (linuxPackages_lqx.rtlwifi_new)</li>
    <li>linuxPackages_lqx.sysdig (linuxKernel.packages.linux_lqx.sysdig)</li>
    <li>linuxPackages_lqx.system76 (linuxKernel.packages.linux_lqx.system76)</li>
    <li>linuxPackages_lqx.system76-acpi (linuxKernel.packages.linux_lqx.system76-acpi)</li>
    <li>linuxPackages_lqx.system76-io (linuxKernel.packages.linux_lqx.system76-io)</li>
    <li>linuxPackages_lqx.systemtap (linuxKernel.packages.linux_lqx.systemtap)</li>
    <li>linuxPackages_lqx.tp_smapi (linuxKernel.packages.linux_lqx.tp_smapi)</li>
    <li>linuxPackages_lqx.tuxedo-keyboard (linuxKernel.packages.linux_lqx.tuxedo-keyboard)</li>
    <li>linuxPackages_lqx.v4l2loopback (linuxKernel.packages.linux_lqx.v4l2loopback)</li>
    <li>linuxPackages_lqx.v86d (linuxKernel.packages.linux_lqx.v86d)</li>
    <li>linuxPackages_lqx.veikk-linux-driver (linuxKernel.packages.linux_lqx.veikk-linux-driver)</li>
    <li>linuxPackages_lqx.vendor-reset (linuxKernel.packages.linux_lqx.vendor-reset)</li>
    <li>linuxPackages_lqx.vhba (linuxKernel.packages.linux_lqx.vhba)</li>
    <li>linuxPackages_lqx.virtio_vmmci (linuxKernel.packages.linux_lqx.virtio_vmmci)</li>
    <li>linuxPackages_lqx.vmm_clock (linuxKernel.packages.linux_lqx.vmm_clock)</li>
    <li>linuxPackages_lqx.xone (linuxKernel.packages.linux_lqx.xone)</li>
    <li>linuxPackages_lqx.xpadneo (linuxKernel.packages.linux_lqx.xpadneo)</li>
    <li>linuxPackages_lqx.zenpower (linuxKernel.packages.linux_lqx.zenpower)</li>
    <li>linuxPackages_lqx.zfs (linuxKernel.packages.linux_lqx.zfs ,linuxPackages_lqx.zfsStable ,linuxPackages_lqx.zfsUnstable)</li>
    <li>linuxPackages_zen.acpi_call (linuxKernel.packages.linux_zen.acpi_call)</li>
    <li>linuxPackages_zen.apfs (linuxKernel.packages.linux_zen.apfs)</li>
    <li>linuxPackages_zen.asus-ec-sensors (linuxKernel.packages.linux_zen.asus-ec-sensors)</li>
    <li>linuxPackages_zen.asus-wmi-sensors (linuxKernel.packages.linux_zen.asus-wmi-sensors)</li>
    <li>linuxPackages_zen.batman_adv (linuxKernel.packages.linux_zen.batman_adv)</li>
    <li>linuxPackages_zen.broadcom_sta (linuxKernel.packages.linux_zen.broadcom_sta)</li>
    <li>linuxPackages_zen.can-isotp (linuxKernel.packages.linux_zen.can-isotp)</li>
    <li>linuxPackages_zen.chipsec (linuxKernel.packages.linux_zen.chipsec)</li>
    <li>linuxPackages_zen.cryptodev (linuxKernel.packages.linux_zen.cryptodev)</li>
    <li>linuxPackages_zen.ddcci-driver (linuxKernel.packages.linux_zen.ddcci-driver)</li>
    <li>linuxPackages_zen.digimend (linuxKernel.packages.linux_zen.digimend)</li>
    <li>linuxPackages_zen.evdi (linuxKernel.packages.linux_zen.evdi)</li>
    <li>linuxPackages_zen.fwts-efi-runtime (linuxKernel.packages.linux_zen.fwts-efi-runtime)</li>
    <li>linuxPackages_zen.gcadapter-oc-kmod (linuxKernel.packages.linux_zen.gcadapter-oc-kmod)</li>
    <li>linuxPackages_zen.hid-nintendo (linuxKernel.packages.linux_zen.hid-nintendo)</li>
    <li>linuxPackages_zen.isgx (linuxKernel.packages.linux_zen.isgx)</li>
    <li>linuxPackages_zen.it87 (linuxKernel.packages.linux_zen.it87)</li>
    <li>linuxPackages_zen.jool (linuxKernel.packages.linux_zen.jool)</li>
    <li>linuxPackages_zen.kvmfr (linuxKernel.packages.linux_zen.kvmfr)</li>
    <li>linuxPackages_zen.liquidtux (linuxKernel.packages.linux_zen.liquidtux)</li>
    <li>linuxPackages_zen.mba6x_bl (linuxKernel.packages.linux_zen.mba6x_bl)</li>
    <li>linuxPackages_zen.mbp2018-bridge-drv (linuxKernel.packages.linux_zen.mbp2018-bridge-drv)</li>
    <li>linuxPackages_zen.mwprocapture (linuxKernel.packages.linux_zen.mwprocapture)</li>
    <li>linuxPackages_zen.netatop (linuxKernel.packages.linux_zen.netatop)</li>
    <li>linuxPackages_zen.nvidia_x11 (linuxKernel.packages.linux_zen.nvidia_x11)</li>
    <li>linuxPackages_zen.nvidia_x11_beta (linuxKernel.packages.linux_zen.nvidia_x11_beta)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy390 (linuxKernel.packages.linux_zen.nvidia_x11_legacy390)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy470 (linuxKernel.packages.linux_zen.nvidia_x11_legacy470)</li>
    <li>linuxPackages_zen.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_zen.openrazer (linuxKernel.packages.linux_zen.openrazer)</li>
    <li>linuxPackages_zen.rr-zen_workaround (linuxKernel.packages.linux_zen.rr-zen_workaround)</li>
    <li>linuxPackages_zen.rtl8814au (linuxKernel.packages.linux_zen.rtl8814au)</li>
    <li>linuxPackages_zen.rtl8821au (linuxKernel.packages.linux_zen.rtl8821au)</li>
    <li>linuxPackages_zen.rtl8821cu (linuxKernel.packages.linux_zen.rtl8821cu)</li>
    <li>linuxPackages_zen.rtl88x2bu (linuxKernel.packages.linux_zen.rtl88x2bu)</li>
    <li>linuxPackages_zen.rtw88 (linuxPackages_zen.rtlwifi_new)</li>
    <li>linuxPackages_zen.sysdig (linuxKernel.packages.linux_zen.sysdig)</li>
    <li>linuxPackages_zen.system76 (linuxKernel.packages.linux_zen.system76)</li>
    <li>linuxPackages_zen.system76-acpi (linuxKernel.packages.linux_zen.system76-acpi)</li>
    <li>linuxPackages_zen.system76-io (linuxKernel.packages.linux_zen.system76-io)</li>
    <li>linuxPackages_zen.systemtap (linuxKernel.packages.linux_zen.systemtap)</li>
    <li>linuxPackages_zen.tp_smapi (linuxKernel.packages.linux_zen.tp_smapi)</li>
    <li>linuxPackages_zen.tuxedo-keyboard (linuxKernel.packages.linux_zen.tuxedo-keyboard)</li>
    <li>linuxPackages_zen.v4l2loopback (linuxKernel.packages.linux_zen.v4l2loopback)</li>
    <li>linuxPackages_zen.v86d (linuxKernel.packages.linux_zen.v86d)</li>
    <li>linuxPackages_zen.veikk-linux-driver (linuxKernel.packages.linux_zen.veikk-linux-driver)</li>
    <li>linuxPackages_zen.vendor-reset (linuxKernel.packages.linux_zen.vendor-reset)</li>
    <li>linuxPackages_zen.vhba (linuxKernel.packages.linux_zen.vhba)</li>
    <li>linuxPackages_zen.virtio_vmmci (linuxKernel.packages.linux_zen.virtio_vmmci)</li>
    <li>linuxPackages_zen.vmm_clock (linuxKernel.packages.linux_zen.vmm_clock)</li>
    <li>linuxPackages_zen.xone (linuxKernel.packages.linux_zen.xone)</li>
    <li>linuxPackages_zen.xpadneo (linuxKernel.packages.linux_zen.xpadneo)</li>
    <li>linuxPackages_zen.zenpower (linuxKernel.packages.linux_zen.zenpower)</li>
    <li>linuxPackages_zen.zfs (linuxKernel.packages.linux_zen.zfs ,linuxPackages_zen.zfsStable ,linuxPackages_zen.zfsUnstable)</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>linuxPackages_lqx.cpupower (linuxKernel.packages.linux_lqx.cpupower)</li>
    <li>linuxPackages_lqx.hyperv-daemons (linuxKernel.packages.linux_lqx.hyperv-daemons)</li>
    <li>linuxPackages_lqx.perf (linuxKernel.packages.linux_lqx.perf)</li>
    <li>linuxPackages_lqx.ply (linuxKernel.packages.linux_lqx.ply)</li>
    <li>linuxPackages_lqx.tmon (linuxKernel.packages.linux_lqx.tmon)</li>
    <li>linuxPackages_lqx.turbostat (linuxKernel.packages.linux_lqx.turbostat)</li>
    <li>linuxPackages_lqx.usbip (linuxKernel.packages.linux_lqx.usbip)</li>
    <li>linuxPackages_lqx.x86_energy_perf_policy (linuxKernel.packages.linux_lqx.x86_energy_perf_policy)</li>
    <li>linuxPackages_zen.cpupower (linuxKernel.packages.linux_zen.cpupower)</li>
    <li>linuxPackages_zen.hyperv-daemons (linuxKernel.packages.linux_zen.hyperv-daemons)</li>
    <li>linuxPackages_zen.perf (linuxKernel.packages.linux_zen.perf)</li>
    <li>linuxPackages_zen.ply (linuxKernel.packages.linux_zen.ply)</li>
    <li>linuxPackages_zen.tmon (linuxKernel.packages.linux_zen.tmon)</li>
    <li>linuxPackages_zen.turbostat (linuxKernel.packages.linux_zen.turbostat)</li>
    <li>linuxPackages_zen.usbip (linuxKernel.packages.linux_zen.usbip)</li>
    <li>linuxPackages_zen.x86_energy_perf_policy (linuxKernel.packages.linux_zen.x86_energy_perf_policy)</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Comment by PedroHLC** [comment]
Missing backport of: https://github.com/NixOS/nixpkgs/pull/175433

**Comment by thiagokokada** [comment]
Considering that 5.17.x is EOL, I am marking this as security.

**Comment by PedroHLC** [comment]
I would call this good to go.

[linux-5.15.50.log](https://github.com/NixOS/nixpkgs/files/9050108/linux-5.15.50.log)
[linux-5.15.50.drv.txt](https://github.com/NixOS/nixpkgs/files/9050107/linux-5.15.50.drv.txt)
[zfs-kernel-2.1.5-5.15.50.log](https://github.com/NixOS/nixpkgs/files/9050110/zfs-kernel-2.1.5-5.15.50.log)
[zfs-kernel-2.1.5-5.15.50.drv.txt](https://github.com/NixOS/nixpkgs/files/9050109/zfs-kernel-2.1.5-5.15.50.drv.txt)


[linux_zen-5.18.9-zen1.log](https://github.com/NixOS/nixpkgs/files/9050098/linux_zen-5.18.9-zen1.log)
[zfs-kernel-2.1.5-5.18.9.drv.txt](https://github.com/NixOS/nixpkgs/files/9050099/zfs-kernel-2.1.5-5.18.9.drv.txt)
[zfs-kernel-2.1.5-5.18.9.log](https://github.com/NixOS/nixpkgs/files/9050101/zfs-kernel-2.1.5-5.18.9.log)
[linux_zen-5.18.9-zen1.drv.txt](https://github.com/NixOS/nixpkgs/files/9050097/linux_zen-5.18.9-zen1.drv.txt)

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
