### PR TITLE
Updated neovim to release 0.1.0.

### PR DESCRIPTION
**Pull request by smilliken**

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @garbas

**Comment by garbas** [comment]
tnx @smilliken ... nice to see neovim users :)

**Comment by vcunat** [comment]
whoa

It's a bit problem that `2015-10-12` -> `0.1.0` will be considered a downgrade by nix-env, but I suppose it's better to switch to these versions sooner than later.

**Comment by garbas** [comment]
@vcunat sorry ... this is my fault, i should choose better initial version of neovim. will know for next time.

**Comment by vcunat** [comment]
We actually officially recommend this scheme that you chose.

**Pull request closed without merging**
