### PR TITLE
arrayfire: do not use cudatoolkit at all on darwin

### PR DESCRIPTION
**Pull request by chessai**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @chessai @dmjio

### CODE REVIEW

**Comment by chessai** [comment]
This PR is an extension to #71413. In order to build properly on MacOS, cudatoolkit needs to be left out of the picture.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build arrayfire

**Comment by c0bw3b** [comment]
Couldn't you use `opencl-clhpp`, `clblas` and from nixpkgs as build inputs ?
And `clfft` too now. :)

**Comment by chessai** [comment]
Yes, they all should be inputs from nixpkgs. I'll work on that.

**Comment by chessai** [comment]
Closing. See https://github.com/NixOS/nixpkgs/pull/72142 as a replacement

**Pull request closed without merging**
