### PR TITLE
libusbmuxd, usbmuxd: bump to latest git revisions

### PR DESCRIPTION
**Pull request by moni-dz**
###### Motivation for this change
the current version of usbmuxd doesn't work right with iOS 14

`Jun 03 01:02:42 superfluous usbmuxd[1240]: [01:02:42.214][1] preflight_worker_handle_device_add: ERROR: Could not connect to lockdownd on device 00008020-001A58582283002E, lockdown error -8`

tested with an iPhone Xs running iOS 14.5.1

```
~ ^ idevice_id
00008020-001A58582283002E (USB)

~ ^ idevicename
f2k's Xs

~ ^ ideviceinfo | rg Product
ProductName: iPhone OS
ProductType: iPhone11,2
ProductVersion: 14.5.1
ProductionSOC: true
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Please follow the contributing guide when naming your commits.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125409` at 752be7c6 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/77d04af7b689c6355a0a2c504a3b68da">xmonad_log_applet</a></li>
  </ul>
</details>
<details>
  <summary>45 packages skipped due to time constraints:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>almanah</li>
    <li>calls</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cjs</li>
    <li>clementine</li>
    <li>empathy (gnome.empathy)</li>
    <li>evolution</li>
    <li>evolution-ews</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>72 packages built successfully:</summary>
  <ul>
    <li>bubblemail</li>
    <li>chrome-gnome-shell</li>
    <li>cinnamon.cinnamon-control-center</li>
    <li>cinnamon.cinnamon-session</li>
    <li>cinnamon.cinnamon-settings-daemon</li>
    <li>clight</li>
    <li>droidcam</li>
    <li>eolie</li>
    <li>evolution-data-server (gnome.evolution-data-server ,gnome.evolution_data_server)</li>
    <li>folks (gnome.folks)</li>
    <li>gfbgraph (gnome.gfbgraph)</li>
    <li>gnome-online-accounts (gnome.gnome-online-accounts ,gnome.gnome_online_accounts)</li>
    <li>gnome.cheese</li>
    <li>gnome.file-roller</li>
    <li>gnome.gnome-books</li>
    <li>gnome.gnome-maps</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gnome-online-miners</li>
    <li>gnome.gnome-panel</li>
    <li>gnome.gnome-power-manager</li>
    <li>gnome.gnome-session (gnome.gnome_session)</li>
    <li>gnome.gnome-settings-daemon (gnome.gnome_settings_daemon)</li>
    <li>gnome.gnome-shell (gnome.gnome_shell)</li>
    <li>gnome.gnome-tweaks (gnome.gnome-tweak-tool)</li>
    <li>gnome.gnome-user-share</li>
    <li>grilo-plugins (gnome.grilo-plugins)</li>
    <li>libgdata (gnome.libgdata)</li>
    <li>libzapojit (gnome.libzapojit)</li>
    <li>gnome.mutter</li>
    <li>gnome.mutter334 (pantheon.mutter)</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.totem</li>
    <li>tracker-miners (gnome.tracker-miners)</li>
    <li>gvfs (gnome2.gvfs)</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>ideviceinstaller</li>
    <li>idevicerestore</li>
    <li>ifuse</li>
    <li>kgx</li>
    <li>libgpod</li>
    <li>libimobiledevice</li>
    <li>libusbmuxd</li>
    <li>mailnagWithPlugins</li>
    <li>pantheon.elementary-dpms-helper</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.elementary-settings-daemon</li>
    <li>pantheon.extra-elementary-contracts</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>phoc</li>
    <li>power-profiles-daemon</li>
    <li>rabbitvcs</li>
    <li>upower</li>
    <li>usbmuxd</li>
    <li>xfce.xfce4-weather-plugin (xfce.xfce4_weather_plugin)</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by jonringer** [comment]
we should probably ask for upstream to cut a release

**Comment by SuperSandro2000** [comment]
Didn't want to block this PR but created two issues:

https://github.com/libimobiledevice/usbmuxd/issues/168 https://github.com/libimobiledevice/libusbmuxd/issues/116

**Pull request merged**
