### PR TITLE
dot-merlin-reader: init at 3.4.0

### PR DESCRIPTION
**Pull request by hongchangwu**
###### Motivation for this change

`dot-merlin-reader` is a new dependency for `merlin` 3.4.0 (which I plan to do in a separate PR). It serves as an external config provider for `merlin`. The intention is that future versions of `merlin` will be able to source config from different providers (e.g., `dune`).

Reference PRs:
- [Merlin change](https://github.com/ocaml/merlin/pull/1123)
- [Dune change](https://github.com/ocaml/dune/pull/3395)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions: Ubuntu
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hongchangwu** [comment]
cc @vbgl

**Comment by vbgl** [comment]
Does this need to be part of `ocamlPackages`? I.e, does the version of OCaml used to build the `dot-merlin-reader` binary matters?

If not, please move it out of that set. This will make it easier to use dot-merlin-reader with OCaml < 4.08.

**Comment by hongchangwu** [comment]
@vbgl that's a good point, I don't think the OCaml version matters at runtime. AFAICT its sole responsibility is to read `.merlin` files.

The only requirement is that the version of `dot-merlin-reader` has to match `merlin`: https://opam.ocaml.org/packages/merlin/merlin.3.4.0/

**Comment by vbgl** [comment]
I fear that the opam description does not tell you about this kind of constraints.

The `dot-merlin-reader` has at least one more responsibility: communicate (what has been read in the `.merlin` files) to `merlin`. It might be the case that the communication protocol rely on OCaml built-in serialization (aka marshaling) — which would be unfortunate…

**Comment by hongchangwu** [comment]
Took a look at the [protocol](https://github.com/ocaml/merlin/pull/1123/files#diff-863c5bb589519042022866edeaceca55), it uses `csexp` for serialization/de-serialization so should be independent of the version of OCaml used.

**Comment by vbgl** [comment]
Thanks for investigating. Then, please do move `dot-merlin-reader` out of the `ocamlPackages` attribute set.

**Comment by hongchangwu** [comment]
Done and updated title.

**Review by vbgl — APPROVED** [review]

**Comment by vbgl** [comment]
@GrahamcOfBorg build dot-merlin-reader

**Pull request merged**
