### PR TITLE
gofumpt: 0.3.1 -> 0.5.0

### PR DESCRIPTION
**Pull request by michaeladler**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ralismark** [comment]
Result of `nixpkgs-review pr 196716` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gofumpt</li>
  </ul>
</details>

Release info: https://github.com/mvdan/gofumpt/releases/tag/v0.4.0

<details>
<summary>Changelog</summary>

> This release is based on Go 1.19's gofmt, and requires Go 1.18 or later.
> We recommend building gofumpt with Go 1.19 for the best formatting results.
> 
> The jump from Go 1.18 brings diffing in pure Go, removing the need to exec diff,
> and a small parsing speed-up thanks to go/parser.SkipObjectResolution.
> 
> The following formatting fixes are included as well:
> 
> - Allow grouping declarations with comments - https://github.com/mvdan/gofumpt/issues/212
> - Properly measure the length of case clauses - https://github.com/mvdan/gofumpt/issues/217
> - Fix a few crashes found by Go's native fuzzing
</details>

---

My testing:
- formatting of simple go file works, including `-l` and `-d`
- example from https://github.com/mvdan/gofumpt/issues/217 (fixed by release) confirmed to be fixed
- running with empty PATH works successfully, confirming that `diff` is not required

**Comment by michaeladler** [comment]
Updated to 0.5.0

**Comment by rafikdraoui** [comment]
ping @rvolosatovs

**Comment by katexochen** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/274237

**Pull request closed without merging**
