### PR TITLE
Bump django-contrib, django-hijack, django-hijack-admin

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
Fairly straightforward bumps except for a couple of changes to the `checkPhase`s that were needed.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
The commit messages should be prefixed with `pythonPackages.`.

**Comment by risicle** [comment]
Ahok

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python2.pkgs.django-compat python2.pkgs.django-hijack python2.pkgs.django-hijack-admin python3.pkgs.django-compat python3.pkgs.django-hijack python3.pkgs.django-hijack-admin

**Comment by risicle** [comment]
Come to think - should these packages be using a custom `installCheckPhase` rather than `checkPhase` seeing as they're expecting the package to already be installed?

**Comment by dotlambda** [comment]
For Python packages, these are the same.

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python2.pkgs.django-compat python2.pkgs.django-hijack python2.pkgs.django-hijack-admin python3.pkgs.django-compat python3.pkgs.django-hijack python3.pkgs.django-hijack-admin

**Comment by dotlambda** [comment]
@risicle The package names use `_`, not `-`. Please correct the commit messages.

@GrahamcOfBorg build python2.pkgs.django_compat python2.pkgs.django_hijack python2.pkgs.django_hijack_admin python3.pkgs.django_compat python3.pkgs.django_hijack python3.pkgs.django_hijack_admin

**Comment by risicle** [comment]
Ah I guess we're going for the attr names here. Changed.

**Pull request merged**
