### PR TITLE
erlangR21: 21.0 -> 21.1.1

### PR DESCRIPTION
**Pull request by ejpcmac**
###### Motivation for this change

A new version is available.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build erlangR21

**Comment by xeji** [comment]
aarch64 failure is a regression, it currently builds: https://hydra.nixos.org/job/nixpkgs/trunk/erlangR21.aarch64-linux

**Comment by ejpcmac** [comment]
Let’s try again with Erlang/OTP 21.1.1.

**Comment by xeji** [comment]
@GrahamcOfBorg build erlangR21

**Comment by xeji** [comment]
@GrahamcOfBorg build erlangR21

**Comment by ejpcmac** [comment]
@xeji This is a strange error, not even the same as the previous one.

**Comment by xeji** [comment]
Let's try again, this might be a temporary issue with the builder machine.
@GrahamcOfBorg build erlangR21

**Comment by xeji** [comment]
Fine, let's call the previous error a temporary issue on the builder.

**Pull request merged**
