### PR TITLE
pulseaudio: wrong path fallout from multiple outputs

### PR DESCRIPTION
**Pull request by peterhoeg**
This isn't tested admittedly, but ShouldJustWork(tm).

needs .out appended to package

### CODE REVIEW

**Comment by ttuegel** [comment]
I fixed this on staging by instead changing the default value for `config.hardware.pulseaudio.package` so that it points to the `.out` output only. I leave it to the other reviewers to decide which solution they like better; there are probably arguments in favor of either.

**Comment by abbradar** [comment]
I think let's do it the way @peterhoeg proposes, but using `getBin` function. The reason is to save the interface -- users now have things like `package = pulseaudioFull` and they would have PulseAudio silently broken because of invalid output selected. `getBin` allows one who truly wants some output to be specified to do so: it has necessary magic so that `package = myPulseaudio.foo` would work as intended.

**Comment by abbradar** [comment]
Pushed as https://github.com/NixOS/nixpkgs/commit/5e2bb0b31c892fed5024eaf7e93faf470a6ceb38. I originally pushed this to staging, but it looks like @ttuegel's changes are already in master, so cherry-picked there.

**Comment by abbradar** [comment]
Ouch, `master` doesn't have `getBin` yet. I've reverted the patch from master for now; staging looks nearly finished building so I expect the merge will be done soon.

**Comment by peterhoeg** [comment]
@abbradar, maybe this is off-topic, but how does ```getBin``` work with packages that do not define a ```bin``` output?

**Comment by abbradar** [comment]
@peterhoeg It uses `out` and then `pkg` itself. Plus, it checks if the output has already been specified. It's easier to see in the code:
```
    if pkg.outputUnspecified or false
      then pkg.${output} or pkg.out or pkg
      else pkg;
```

**Pull request closed without merging**
