### PR TITLE
Fix Plasma NixOS tests

### PR DESCRIPTION
**Pull request by jtojnar**
Required to build with Phonon 4.11 (https://github.com/NixOS/nixpkgs/pull/71745). Not having this blocks the channels.

Phonon no longer supports Qt 4 so I marked it as broken there.

cc @ttuegel

### CODE REVIEW

**Comment by jtojnar** [comment]
Had to do more drastic changes than just update since Qt 4 is no longer supported by Phonon since #71745

**Comment by FRidh** [comment]
This needs rebasing. Note many parts of KDE are failing since the staging-next merge. https://github.com/NixOS/nixpkgs/pull/73756

**Comment by jtojnar** [comment]
Rebased.

**Comment by worldofpeace** [comment]
@jtojnar Can you change the commit message `phonon: mark as broken` to `phonon: mark as broken for qt4`? At a glance I thought phonon was completely broken.

**Comment by jtojnar** [comment]
Qt5 libraries use `libsForQt5` prefix. Anyway, I will be away from computer for the rest of the day so feel free to reword it yourself.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
https://phabricator.kde.org/D22688 says qt4 was removed there entirely.
Can we remove all withQt4 options, and the `? null` for the function arguments?

**Comment by worldofpeace** [comment]
> Qt5 libraries use `libsForQt5` prefix. Anyway, I will be away from computer for the rest of the day so feel free to reword it yourself.

I see. Will push this my changes then.

**Comment by worldofpeace** [comment]
Here were my changes
* https://github.com/NixOS/nixpkgs/compare/c9ab4901720f470c6bd9cf75563bd186370c3caa..9b236c2d567461076a83abb05629f7f6d03eb886

There was already a todo to remove it completely, so I added aliases and removed the qt4 versions and options. @jtojnar I think you kept the arguments to fail gracefully, it kinda sucks we don't have a nice thing like aliases like this. What do you think about keeping `withQt4` but instead asserting it to be false, with an assertMsg like `Qt4 support has been removed. Please remove withQt4`?

**Comment by jtojnar** [comment]
After giving it some more thought, consumers would be using the 
libraries directly as supplied through `(libsForQt5.)callPackage` so I 
would not bother keeping the arguments. It should be pretty easy to 
figure out the cause for someone who is deliberately overriding it 
directly.

What we should not do is point the aliases to the Qt5 versions – they 
are fundamentally different packages. I think changing the aliases to 
throw should work here.

**Comment by worldofpeace** [comment]
> What we should not do is point the aliases to the Qt5 versions – they
are fundamentally different packages. I think changing the aliases to
throw should work here.

I actually only considered it because it wasn't the only entry in aliases.nix that does this.
Though also, considering there's going to be a massive removal of attributes for qt4, perhaps it's like a forced upgrade to qt5? In the end, that's what a user of the alias would need this for.

But I do get the point of an alias not pointing to a fundamentally changed package, though it is still phonon.

```
phonon = throw "Please use libsForQt5.phonon, as Qt4 support in this package has been removed.";
```

**Comment by jtojnar** [comment]
Pushed, thanks.

**Review by worldofpeace — APPROVED** [review]
LGTM, going to merge right away because our channel is blocked.

**Pull request merged**
