### PR TITLE
del mesa-darwin: fossil (2012 version)

### PR DESCRIPTION
**Pull request by Anton-Latukha**
###### Main point

(2018-06-29) v18.1.3 - `mesa` 
(2012-10-24) v08.0.3 - `mesa-darwin`

I do `mesa` v18 work, and `mesa-darwin` v8 relies on `mesa` and creates conflicts during evaluation.

Good point is - from 2012 to this date it was evaluating - that shows the stability achieved by the Nix approach.
 
_###### Serious jokes_

_I really can not test `mesa-darwin` v8, both because of architecture, and because it is mesa in 2012 edition style._

_I summon the @jtojnar - daedric prince! One of your spheres of influence is guiding forces to cleanse the old, so new comes to the world._

_###### Fun time_
_I, not once, checked everything. Now is the only time I probably ever give myself that fun:_

_- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)_
_- Built on platform(s)_
_   - [x] NixOS_
_   - [x] macOS_
_   - [x] other Linux distributions_
_- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))_
_- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`_
_- [x] Tested execution of all binary files (usually in `./result/bin/`)_
_- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)_
_- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md)._

_Yes! I did it! 8)_

Seriously, it conflicts with `mesa`.

---

### CODE REVIEW

**Comment by jtojnar** [comment]
You seem to have just removed the expression without removing the package calls.

```
$ rg libGLDarwin
pkgs/top-level/all-packages.nix
10888:  libGL = libGLDarwinOr mesa_noglu.stubs;
10891:  libGLU = libGLDarwinOr mesa_glu;
10897:  libGLU_combined = libGLDarwinOr (buildEnv {
10904:  libGL_driver = libGLDarwinOr mesa_drivers;
10908:  libGLDarwin = callPackage ../development/libraries/mesa-darwin {
10914:  libGLDarwinOr = alternative: if stdenv.isDarwin then libGLDarwin else alternative;
```

Also I would like to hear from @cstrahan or someone if this relict is still needed.

**Comment by matthewbauer** [comment]
Yes we need to get latest mesa to build on macOS before we can start doing this.

**Comment by Anton-Latukha** [comment]
@matthewbauer 

Please say more.
I don't understood the message: "we need to get latest mesa build on macOS before we can start" deleting it?

**Comment by matthewbauer** [comment]
> I don't understood the message: "we need to get latest mesa build on macOS before we can start" deleting it?

Yes - the problem right now is that mesa-darwin is still used in a few places (mostly xorg stuff). It definitely should be removed because it is unmaintained & out of date but we don't have a good alternative yet.

**Comment by Anton-Latukha** [comment]
Ok. In fact I can avoid this conflict, by not cleaning the config flags.

1. I would submit pull request `mesa` that would work `mesa-darwin`, commenting legacy stuff.

2. Then would open issue for `mesa-darwin`, because there is none at the moment.

**Comment by Anton-Latukha** [comment]
Closed in favor of both: 1) #43378, 2) seems still used to some degree.

**Pull request closed without merging**
