### PR TITLE
nixos/incus: add incus-only vm and container images

### PR DESCRIPTION
**Pull request by adamcstephens**
## Description of changes

This fully decouples Incus and LXD images by building Incus-only images and using them for Incus. These new images will be provided to the official LXC imageserver once built. Immediately for unstable and then after 24.11 is released.

I've also removed the LXC team from all LXD packages and modules. My personal preference would be to deprecate all LXD resources prior to 24.11, but if others wish to pick these up for maintenance they are now encouraged. cc: @jnsgruk 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
@ofborg build incus.passthru.tests incus-lts.passthru.tests lxd.passthru.tests

**Comment by jnsgruk** [comment]
I'm happy to help keep LXD going - I don't think I've got all the skills required to carry it on my own, but I'll give it a shot, and perhaps a ping when things are changing in Incus might help? 🙂

**Comment by adamcstephens** [comment]
@ofborg build incus.passthru.tests incus-lts.passthru.tests lxd.passthru.tests

**Comment by adamcstephens** [comment]
> I'm happy to help keep LXD going - I don't think I've got all the skills required to carry it on my own, but I'll give it a shot, and perhaps a ping when things are changing in Incus might help? 🙂

The LXD module is likely already missing Incus improvements and fixes. I have not been adding them along with Incus and have not seen anybody else do so either. AFAIK LXD is still at the same point as when I forked the Incus modules. It’s enough work to keep two releases of Incus happy. 

Honestly I can’t imagine many people are still using the nixos LXD. Since LXD cannot access the LXC image server it makes little sense outside of users of Ubuntu, and most of those are probably running LXD on Ubuntu. I know there was an effort to add a Canonical third party distro image server, but last I’d seen a couple months ago that hadn’t progressed. That had left users with having to build manually anything besides Ubuntu, which means an even smaller pool of users motivated enough to stick with LXD.

**Comment by jnsgruk** [comment]
> > I'm happy to help keep LXD going - I don't think I've got all the skills required to carry it on my own, but I'll give it a shot, and perhaps a ping when things are changing in Incus might help? 🙂
> 
> 
> 
> The LXD module is likely already missing Incus improvements and fixes. I have not been adding them along with Incus and have not seen anybody else do so either. AFAIK LXD is still at the same point as when I forked the Incus modules. It’s enough work to keep two releases of Incus happy. 
> 
> 
> 
> Honestly I can’t imagine many people are still using the nixos LXD. Since LXD cannot access the LXC image server it makes little sense outside of users of Ubuntu, and those users are running LXD on Ubuntu. I know there was an effort to add a Canonical third party distro image server, but last I’d seen a couple months ago that hadn’t progressed. That had left users with having to build manually anything besides Ubuntu, which means an even smaller pool of users motivated enough to stick with LXD. 

The Canonical image server is up and running and has been for a couple of months now - so everything is still working pretty well. I for one use it daily, as do a few others I know. I'll try to encourage some other folks to help out, too.

**Comment by adamcstephens** [comment]
aarch64-linux

nix-build -A incus-lts.passthru.tests -A incus.passthru.tests -A lxd.passthru.tests --keep-going --max-jobs 2 --argstr system aarch64-linux

/nix/store/gb3krmpvbvfdbqdcswh7rvwzcl6dxxr8-vm-test-run-container-legacy-init
/nix/store/h3c98f576pjqfb6yh6z3sbzfwz18aza5-vm-test-run-container-systemd-init
/nix/store/ha2jz5fznn613niqw734s4d0yzarxmd1-vm-test-run-incusd-options
/nix/store/5n6jchg4rvbc9x36pb7zcp09xgz2ix59-vm-test-run-lxd-to-incus
/nix/store/j8abdgqd1g1np8kbgnk5zlcwjxyg5k53-vm-test-run-incus-openvswitch
/nix/store/7wqjx7kq12zq6jlzwgddklgsq16av6dn-vm-test-run-incus-socket-activated
/nix/store/b43qbkql9ams8hvdqjhddmjhaakwdz3x-vm-test-run-incus-storage
/nix/store/p4q4yyrrdcg4y6706x6g68x91mv9jn55-vm-test-run-incus-ui
/nix/store/qgbx1fx6skg7xxzrjr7jvh36450z294x-vm-test-run-container-legacy-init
/nix/store/kcbp60ldsqr49c3jfnzxzwwv1fiv6wpj-vm-test-run-container-systemd-init
/nix/store/f5zin2qkdwq0vq9vw98xp98ssb8v26bi-vm-test-run-incusd-options
/nix/store/7874gjzlb2p4z1hd58z635x2gv06d6iw-vm-test-run-lxd-to-incus
/nix/store/56kd7s0q5qfv6hpdjwdqm2wcldib1m3j-vm-test-run-incus-openvswitch
/nix/store/rhgqzmyqikwcgsyk1kq2qf36wwmjnvr8-vm-test-run-incus-socket-activated
/nix/store/d80ja2znavbgbip1afygiwk4pr44jggs-vm-test-run-incus-storage
/nix/store/l682dwlkpr3iwvfgzmdamkp9g7mbg2qc-vm-test-run-incus-ui
/nix/store/wi0kv08qrm8svh4313k90s17nbknbkmh-vm-test-run-lxd-container
/nix/store/q6nh0q9ji0pqid3kzpdb9bywppwfbx9d-vm-test-run-lxd-nftables
/nix/store/dd97zxgycq4ykhf69ck21bxgkj4ycl2i-vm-test-run-lxd-preseed
/nix/store/38srcbcc1p0jb7mwkmbq27h43b8b5qfz-vm-test-run-lxd-ui
/nix/store/7874gjzlb2p4z1hd58z635x2gv06d6iw-vm-test-run-lxd-to-incus

**Pull request merged**
