### PR TITLE
Add spatialite-tools and its missing dependency (readosm)

### PR DESCRIPTION
**Pull request by przester**

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@KrzyStar Some of the tools seem to segfault...

**Comment by 7c6f434c** [comment]
Some of them don't, though. Merged and fixed licenses

**Comment by lethalman** [comment]
@7c6f434c shall this be closed?

**Comment by Fuuzetsu** [comment]
Seems there's no point keeping it open.

**Pull request closed without merging**
