### PR TITLE
afetch: init at 2.2.0

### PR DESCRIPTION
**Pull request by dan4ik605743**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 130197` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>afetch</li>
  </ul>
</details>

**Review by 06kellyjac — APPROVED** [review]
LGTM

Might be worth adding a patches arg like dmenu though https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/dmenu/default.nix

If you want help maintaining feel free to add me (`with maintainers; [ dan4ik605743 jk ];`) or dont, up to you


I've opened an issue just to clarify if afetch is gpl3Plus or gpl3Only

**Comment by dan4ik605743** [comment]
> LGTM
> 
> Might be worth adding a patches arg like dmenu though https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/dmenu/default.nix
> 
> If you want help maintaining feel free to add me (`with maintainers; [ dan4ik605743 jk ];`) or dont, up to you
> 
> I've opened an issue just to clarify if afetch is gpl3Plus or gpl3Only

I'm sorry, I did not understand you. What would you like. Can repeat again

**Comment by dan4ik605743** [comment]
> > LGTM
> > Might be worth adding a patches arg like dmenu though https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/dmenu/default.nix
> > If you want help maintaining feel free to add me (`with maintainers; [ dan4ik605743 jk ];`) or dont, up to you
> > I've opened an issue just to clarify if afetch is gpl3Plus or gpl3Only
> 
> I'm sorry, I did not understand you. What would you like. Can repeat again

So I add you to Maintainers Package?

**Comment by 06kellyjac** [comment]
> So I add you to Maintainers Package?

only if you want to :slightly_smiling_face:

**Comment by dan4ik605743** [comment]
> > So I add you to Maintainers Package?
> 
> only if you want to

Well, now I will do.

**Pull request merged**
