### PR TITLE
cudatext: 1.142.0 → 1.143.0

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change
[Changelog](https://cudatext.github.io/history.txt)

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
I get

```
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $00000000006329A3
  $00000000006117F9
  $0000000000796CAD
  $000000000079668D
  $00000000007927C3
  $000000000069F7B1
  $000000000069F6CB
  $000000000047B6AA
  $000000000044B870
  $000000000043A21C
[FORMS.PP] ExceptionOccurred 
```

when running `cudatext` but this might be because of sway, also I have xwayland.

**Comment by sikmir** [comment]
Both qt and gtk2 variants works for me with X server. @Alexey-T, what about official wayland support?

**Comment by Alexey-T** [comment]
>@Alexey-T, what about official wayland support?

This depends on Lazarus IDE, I just use it's widgets.

**Comment by Alexey-T** [comment]
> I get
> 
> ```
> [FORMS.PP] ExceptionOccurred 
>   Sender=EAccessViolation
>   Exception=Access violation
>   Stack trace:
>   $00000000006329A3
>   $00000000006117F9
>   $0000000000796CAD

You can help (a little) if you compile the Cud __with debug information On__ (IDE dialog "Project options"). Then on crash you will see more detailed  crash log.

**Comment by sikmir** [comment]
@Mic92 I think problems with running CudaText on Wayland should not stop us from merging this PR since we have no problems on X11.

**Comment by Alexey-T** [comment]
Strange that Github has changed 'look' of checksums:
```
    "rev": "v11.3.1",
    "sha256": "1f95rdpfwqy9fipzybi17nbhq46zj45yjps21p2hplhinrr49n2p"
```
to
```
    "rev": "v11.4",
    "sha256": "sha256-jZL8lzjua033E76IL0HIk/fihC73ifCb4LqMni7vvb0="
  }
```

**Comment by sikmir** [comment]
> Strange that Github has changed 'look' of checksums:
> 
> ```
>     "rev": "v11.3.1",
>     "sha256": "1f95rdpfwqy9fipzybi17nbhq46zj45yjps21p2hplhinrr49n2p"
> ```
> 
> to
> 
> ```
>     "rev": "v11.4",
>     "sha256": "sha256-jZL8lzjua033E76IL0HIk/fihC73ifCb4LqMni7vvb0="
>   }
> ```

That's OK, nixFlake generates SRI hash.

**Pull request merged**
