### PR TITLE
coqPackages.coq-extensible-records: remove at 1.2.0

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

This library is compatible with recent versions of Coq.

cc maintainer @Ptival 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ptival** [comment]
@vbgl this library is not being maintained, I wonder whether we should just remove it rather than rely on me keeping my "fork" up to date?

**Comment by vbgl** [comment]
Do you think that there are users of this library that would be pleased to have it packaged here? If not, then let’s remove it.

**Comment by Ptival** [comment]
I honestly don't think anyone is using it. Do you want me to remove it, or are you doing it?

**Comment by vbgl** [comment]
Thanks. I’ll just update this PR to remove the package.

**Pull request merged**
