### PR TITLE
Paperwork update

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

* update paperwork
* fix paperwork-shell
* add a desktop file for paperwork

###### Things done

* add the new dependency `libinsane`
* remove `pyinsane2` as it was only needed by older versions of paperwork and is now unmaintained upstream

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
can you clean up git history, there should only be 4 commits

use `git rebase -i`

**Comment by symphorien** [comment]
It's impossible to use rebase after a merge. I can squash if you prefer.

**Comment by jonringer** [comment]
you can use `rebase -i` to remove the merge commits, and squash the related ones

**Comment by jonringer** [comment]
although i almost never do merge commits, so maybe im wrong

**Comment by symphorien** [comment]
git rebase -i lists 11058 commits. I am afraid it is unworkable. I can either squash or leave the PR as is. Feel free to edit it to you liking, as I ticked the `allow edits from maintainers` box.

**Comment by jonringer** [comment]
you can also do `git rebase --onto master HEAD~15`, after resolving the conflicts, the git history should be fixed

**Comment by symphorien** [comment]
`git rebase --onto master HEAD~15` makes one merge conflict by commit imported by the merges. That is about 11000 merge conflicts.

**Comment by jonringer** [comment]
it's listed under https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches that your git commits should be done in a way that "makes sense". Usually to make it easy for cherry-picks to release branches.

**Review by jonringer — CHANGES_REQUESTED** [review]
please groom git history, should be ~5 commits

**Pull request closed without merging**
