### PR TITLE
buildbot: 2.9.2 -> 2.10.0

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Updates buildbot to the latest version.

cc @nand0p @ryansydnor

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108145` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>9 packages failed to build and are new build failures:</summary>
  <ul>
<li>buildbot</li>
<li>(python38Packages.buildbot)</li>
<li>buildbot-full</li>
<li>(python38Packages.buildbot-full)</li>
<li>buildbot-ui</li>
<li>(python38Packages.buildbot-ui)</li>
<li>python37Packages.buildbot</li>
<li>python37Packages.buildbot-full</li>
<li>python37Packages.buildbot-ui</li>
  </ul>
</details>
<details>
<summary>
21 packages built:
</summary>
<ul>
<li>buildbot-worker (python38Packages.buildbot-worker)</li>
<li>python37Packages.buildbot-pkg</li>
<li>python37Packages.buildbot-plugins.console-view</li>
<li>python37Packages.buildbot-plugins.grid-view</li>
<li>python37Packages.buildbot-plugins.waterfall-view</li>
<li>python37Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python37Packages.buildbot-plugins.www</li>
<li>python37Packages.buildbot-worker</li>
<li>python38Packages.buildbot-pkg</li>
<li>python38Packages.buildbot-plugins.console-view</li>
<li>python38Packages.buildbot-plugins.grid-view</li>
<li>python38Packages.buildbot-plugins.waterfall-view</li>
<li>python38Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python38Packages.buildbot-plugins.www</li>
<li>python39Packages.buildbot-pkg</li>
<li>python39Packages.buildbot-plugins.console-view</li>
<li>python39Packages.buildbot-plugins.grid-view</li>
<li>python39Packages.buildbot-plugins.waterfall-view</li>
<li>python39Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python39Packages.buildbot-plugins.www</li>
<li>python39Packages.buildbot-worker</li>
</ul>
</details>

Builds failures are because of cfn-lint failing.

**Comment by lopsided98** [comment]
2.10.0 has been released, so I have updated the PR. The NixOS test succeeds locally with a cached `cfn-lint`.

cc @makefu because I had to update `sqlalchemy-migrate`.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108145` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>13 packages failed to build and are new build failures:</summary>
  <ul>
<li>buildbot: log was empty</li>
<li>(python38Packages.buildbot): log was empty</li>
<li>buildbot-full: log was empty</li>
<li>(python38Packages.buildbot-full): log was empty</li>
<li>buildbot-ui: log was empty</li>
<li>(python38Packages.buildbot-ui): log was empty</li>
<li>buildbot-worker: log <a href="https://hastebin.com/raw/ezagedeleh">https://hastebin.com/raw/ezagedeleh</a></li>
<li>(python38Packages.buildbot-worker): log <a href="https://hastebin.com/raw/ezagedeleh">https://hastebin.com/raw/ezagedeleh</a></li>
<li>python37Packages.buildbot: log <a href="https://hastebin.com/raw/ezagedeleh">https://hastebin.com/raw/ezagedeleh</a></li>
<li>python37Packages.buildbot-full: log <a href="https://hastebin.com/raw/ezagedeleh">https://hastebin.com/raw/ezagedeleh</a></li>
<li>python37Packages.buildbot-ui: log <a href="https://hastebin.com/raw/ezagedeleh">https://hastebin.com/raw/ezagedeleh</a></li>
<li>python37Packages.buildbot-worker: log <a href="https://hastebin.com/raw/ibasuleseg">https://hastebin.com/raw/ibasuleseg</a></li>
<li>python39Packages.buildbot-worker: log <a href="https://hastebin.com/raw/ucemekulof">https://hastebin.com/raw/ucemekulof</a></li>
  </ul>
</details>
<details>
<summary>
21 packages built:
</summary>
<ul>
<li>python37Packages.buildbot-pkg</li>
<li>python37Packages.buildbot-plugins.console-view</li>
<li>python37Packages.buildbot-plugins.grid-view</li>
<li>python37Packages.buildbot-plugins.waterfall-view</li>
<li>python37Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python37Packages.buildbot-plugins.www</li>
<li>python37Packages.sqlalchemy_migrate</li>
<li>python38Packages.buildbot-pkg</li>
<li>python38Packages.buildbot-plugins.console-view</li>
<li>python38Packages.buildbot-plugins.grid-view</li>
<li>python38Packages.buildbot-plugins.waterfall-view</li>
<li>python38Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python38Packages.buildbot-plugins.www</li>
<li>python38Packages.sqlalchemy_migrate</li>
<li>python39Packages.buildbot-pkg</li>
<li>python39Packages.buildbot-plugins.console-view</li>
<li>python39Packages.buildbot-plugins.grid-view</li>
<li>python39Packages.buildbot-plugins.waterfall-view</li>
<li>python39Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python39Packages.buildbot-plugins.www</li>
<li>python39Packages.sqlalchemy_migrate</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108145` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.sqlalchemy_migrate</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>pytrainer: log was empty</li>
  </ul>
</details>
<details>
<summary>
29 packages built:
</summary>
<ul>
<li>buildbot (python38Packages.buildbot)</li>
<li>buildbot-full (python38Packages.buildbot-full)</li>
<li>buildbot-ui (python38Packages.buildbot-ui)</li>
<li>buildbot-worker (python38Packages.buildbot-worker)</li>
<li>python37Packages.buildbot</li>
<li>python37Packages.buildbot-full</li>
<li>python37Packages.buildbot-pkg</li>
<li>python37Packages.buildbot-plugins.console-view</li>
<li>python37Packages.buildbot-plugins.grid-view</li>
<li>python37Packages.buildbot-plugins.waterfall-view</li>
<li>python37Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python37Packages.buildbot-plugins.www</li>
<li>python37Packages.buildbot-ui</li>
<li>python37Packages.buildbot-worker</li>
<li>python37Packages.sqlalchemy_migrate</li>
<li>python38Packages.buildbot-pkg</li>
<li>python38Packages.buildbot-plugins.console-view</li>
<li>python38Packages.buildbot-plugins.grid-view</li>
<li>python38Packages.buildbot-plugins.waterfall-view</li>
<li>python38Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python38Packages.buildbot-plugins.www</li>
<li>python38Packages.sqlalchemy_migrate</li>
<li>python39Packages.buildbot-pkg</li>
<li>python39Packages.buildbot-plugins.console-view</li>
<li>python39Packages.buildbot-plugins.grid-view</li>
<li>python39Packages.buildbot-plugins.waterfall-view</li>
<li>python39Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python39Packages.buildbot-plugins.www</li>
<li>python39Packages.buildbot-worker</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108145` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.sqlalchemy_migrate</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>pytrainer: log was empty</li>
  </ul>
</details>
<details>
<summary>
29 packages built:
</summary>
<ul>
<li>buildbot (python38Packages.buildbot)</li>
<li>buildbot-full (python38Packages.buildbot-full)</li>
<li>buildbot-ui (python38Packages.buildbot-ui)</li>
<li>buildbot-worker (python38Packages.buildbot-worker)</li>
<li>python37Packages.buildbot</li>
<li>python37Packages.buildbot-full</li>
<li>python37Packages.buildbot-pkg</li>
<li>python37Packages.buildbot-plugins.console-view</li>
<li>python37Packages.buildbot-plugins.grid-view</li>
<li>python37Packages.buildbot-plugins.waterfall-view</li>
<li>python37Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python37Packages.buildbot-plugins.www</li>
<li>python37Packages.buildbot-ui</li>
<li>python37Packages.buildbot-worker</li>
<li>python37Packages.sqlalchemy_migrate</li>
<li>python38Packages.buildbot-pkg</li>
<li>python38Packages.buildbot-plugins.console-view</li>
<li>python38Packages.buildbot-plugins.grid-view</li>
<li>python38Packages.buildbot-plugins.waterfall-view</li>
<li>python38Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python38Packages.buildbot-plugins.www</li>
<li>python38Packages.sqlalchemy_migrate</li>
<li>python39Packages.buildbot-pkg</li>
<li>python39Packages.buildbot-plugins.console-view</li>
<li>python39Packages.buildbot-plugins.grid-view</li>
<li>python39Packages.buildbot-plugins.waterfall-view</li>
<li>python39Packages.buildbot-plugins.wsgi-dashboards</li>
<li>python39Packages.buildbot-plugins.www</li>
<li>python39Packages.buildbot-worker</li>
</ul>
</details>

**Pull request merged**
