### PR TITLE
libgit2: drop 0.26

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Follow-up on https://github.com/NixOS/nixpkgs/pull/44137

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @dtzWill

### CODE REVIEW

**Comment by jtojnar** [comment]
@grahamcofborg build libgit2-glib subsurface gnome-builder stagit haskellPackages.hlibgit2 gitg gitAndTools.grv pythonPackages.pygit2

**Comment by jtojnar** [comment]
Need to check if https://github.com/NixOS/nixpkgs/issues/51416 still applies

**Comment by grahamc** [comment]
https://github.com/NixOS/nixpkgs/compare/10b50b661b8b...ac97ba25ae76

**Comment by grahamc** [comment]
Part of this PR was reverted.

**Pull request merged**
