### PR TITLE
whitebophir: 1.7.0 -> 1.9.1

### PR DESCRIPTION
**Pull request by iblech**
###### Motivation for this change

This pull request updates our whitebophir package to the newest version and also updates our whitebophir service to expose a new and very useful option, the IP address to listen on.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112689` at b4816631 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/6ef8c02e785f3610267551a8321a1ecd">whitebophir</a></li></li>
  </ul>
</details>

**Comment by iblech** [comment]
Pushed a further commit for bumping to the new release 1.9.0.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112689` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
</ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>whitebophir</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
whitebophir:
<details>


warning: attribute-typo
A likely typo in `dontNpmInstall` argument was found, did you mean `dontInstall`?

Near pkgs/development/node-packages/node-env.nix:409:14:

```
    |
409 |       inherit dontNpmInstall preRebuild unpackPhase buildPhase;
    |              ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/attribute-typo.md
warning: attribute-typo
A likely typo in `preRebuild` argument was found, did you mean `postBuild`?

Near pkgs/development/node-packages/node-env.nix:409:14:

```
    |
409 |       inherit dontNpmInstall preRebuild unpackPhase buildPhase;
    |              ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/attribute-typo.md
warning: unclear-gpl
`agpl3` is a deprecated license, check if project uses `agpl3Plus` or `agpl3Only` and change `meta.license` accordingly.

Near pkgs/servers/web-apps/whitebophir/default.nix:31:7:

```
   |
31 |       license = licenses.agpl3;
   |       ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: build-tools-in-build-inputs
util-linux is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/node-packages/node-env.nix:401:7:

```
    |
401 |       buildInputs = [ tarWrapper python nodejs ]
    |       ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md
warning: unused-argument
Unused argument: `fetchurl`.
Near pkgs/servers/web-apps/whitebophir/default.nix:4:3:

```
  |
4 | , fetchurl
  |   ^
```
</details>
</details>

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by iblech** [comment]
I just force-pushed a new commit which fixes those issues found by nixpkgs-review which concern the whitebophir package directly (as opposed to our general node package infrastructure).

**Pull request merged**
