### PR TITLE
vimPlugins.ccc-nvim: init at 2022-09-25

### PR DESCRIPTION
**Pull request by pinpox**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 193005` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.lexima-vim</li>
  </ul>
</details>
<details>
  <summary>55 packages built:</summary>
  <ul>
    <li>gnvim</li>
    <li>neovim-qt</li>
    <li>neovim-remote</li>
    <li>nvimpager</li>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.ccc-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.compiler-explorer-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.lua-dev-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-solarized-lua</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.package-info-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.tagbar</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.urlview-nvim</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-dadbod</li>
    <li>vimPlugins.vim-dadbod-ui</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-markdown</li>
    <li>vimPlugins.vim-startuptime</li>
    <li>vimPlugins.vim-toml</li>
    <li>vimPlugins.vimspector</li>
  </ul>
</details>

**Comment by figsoda** [comment]
```console
Error detected while processing command line:
E154: Duplicate tag "g:lexima_disable_abbrev_trigger" in file /nix/store/4lfnv9l5dpdpc2w8kw9kjv5fpwvww3ch-vimplugin-lexima.vim-2022-09-26/./doc/lexima.txtFailed to build help tags!
``

**Comment by figsoda** [comment]
Looks like this is a bug that has been fixed upstream: https://github.com/cohama/lexima.vim/pull/137
You might want to consider running the upgrade script again

**Comment by pinpox** [comment]
> Looks like this is a bug that has been fixed upstream: [cohama/lexima.vim#137](https://github.com/cohama/lexima.vim/pull/137) You might want to consider running the upgrade script again

@figsoda fixed now it seems

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 193005` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>71 packages built:</summary>
  <ul>
    <li>gnvim</li>
    <li>neovim-qt</li>
    <li>neovim-remote</li>
    <li>nvimpager</li>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.catppuccin-vim</li>
    <li>vimPlugins.ccc-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.compiler-explorer-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.git-blame-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.legendary-nvim</li>
    <li>vimPlugins.lexima-vim</li>
    <li>vimPlugins.litee-calltree-nvim</li>
    <li>vimPlugins.litee-filetree-nvim</li>
    <li>vimPlugins.litee-symboltree-nvim</li>
    <li>vimPlugins.lua-dev-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-solarized-lua</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.package-info-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.tagbar</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.urlview-nvim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-dadbod</li>
    <li>vimPlugins.vim-dadbod-ui</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-markdown</li>
    <li>vimPlugins.vim-rails</li>
    <li>vimPlugins.vim-signify</li>
    <li>vimPlugins.vim-startuptime</li>
    <li>vimPlugins.vim-toml</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.vimux</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]

**Pull request merged**
