### PR TITLE
feishin: 0.3.0 -> 0.4.1

### PR DESCRIPTION
**Pull request by nephalemsec**
## Description of changes

Simple update to hashes for Feishin version bump.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by avh4** [comment]
I'm getting a hash mismatch on the downloaded source when I try this:

```
❯ nix-build -A feishin
these 2 derivations will be built:
  /nix/store/f2avlgxvai0aqn53gglxwx9zrp5bxxs6-Feishin-0.4.0-linux-x64.tar.xz.drv
  /nix/store/s080fbrv6nplv9sz1c7219rdif3jg98l-feishin-0.4.0.drv
building '/nix/store/f2avlgxvai0aqn53gglxwx9zrp5bxxs6-Feishin-0.4.0-linux-x64.tar.xz.drv'...

trying https://github.com/jeffvli/feishin/releases/download/v0.4.0/Feishin-0.4.0-linux-x64.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 68.4M  100 68.4M    0     0  8223k      0  0:00:08  0:00:08 --:--:-- 9129k
error: hash mismatch in fixed-output derivation '/nix/store/f2avlgxvai0aqn53gglxwx9zrp5bxxs6-Feishin-0.4.0-linux-x64.tar.xz.drv':
         specified: sha256-KA40AJ55s2HQLCJvS7ZRJcAjlCuELRm5DRcRVJles8s=
            got:    sha256-2S2/UA9tU3wAtOwR8P82rU/wkI4neGOgAaGrEi5NstU=
error: 1 dependencies of derivation '/nix/store/s080fbrv6nplv9sz1c7219rdif3jg98l-feishin-0.4.0.drv' failed to build
```

Is this just something weird with my environment, or maybe did feishin's 0.4.0 tag change since you created the PR?

**Comment by nephalemsec** [comment]
> I'm getting a hash mismatch on the downloaded source when I try this:
> 
> ```
> ❯ nix-build -A feishin
> these 2 derivations will be built:
>   /nix/store/f2avlgxvai0aqn53gglxwx9zrp5bxxs6-Feishin-0.4.0-linux-x64.tar.xz.drv
>   /nix/store/s080fbrv6nplv9sz1c7219rdif3jg98l-feishin-0.4.0.drv
> building '/nix/store/f2avlgxvai0aqn53gglxwx9zrp5bxxs6-Feishin-0.4.0-linux-x64.tar.xz.drv'...
> 
> trying https://github.com/jeffvli/feishin/releases/download/v0.4.0/Feishin-0.4.0-linux-x64.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 68.4M  100 68.4M    0     0  8223k      0  0:00:08  0:00:08 --:--:-- 9129k
> error: hash mismatch in fixed-output derivation '/nix/store/f2avlgxvai0aqn53gglxwx9zrp5bxxs6-Feishin-0.4.0-linux-x64.tar.xz.drv':
>          specified: sha256-KA40AJ55s2HQLCJvS7ZRJcAjlCuELRm5DRcRVJles8s=
>             got:    sha256-2S2/UA9tU3wAtOwR8P82rU/wkI4neGOgAaGrEi5NstU=
> error: 1 dependencies of derivation '/nix/store/s080fbrv6nplv9sz1c7219rdif3jg98l-feishin-0.4.0.drv' failed to build
> ```
> 
> Is this just something weird with my environment, or maybe did feishin's 0.4.0 tag change since you created the PR?

Yeah seems to have changed. I meant to update it before i left for conference. Ultimately I'd love for the bot to come through and update tags for us :joy:

**Comment by avh4** [comment]
FYI, in case it matter to you personally, there's a bug in 0.4.0 upstream that makes it not consistently submit scrobbles https://github.com/jeffvli/feishin/pull/269 so I'm hoping they'll be making a new new release soon

**Comment by avh4** [comment]
Yeah, FYI upstream released 0.4.1: https://github.com/jeffvli/feishin/releases/tag/v0.4.1

**Comment by nephalemsec** [comment]
Thanks mate, I'll test and update this PR after work today 😄

**Comment by nephalemsec** [comment]
These are the hash values for anyone who doesn't want to wait for me:

```Nix
  filename =
    if stdenv.isDarwin then
      "${appname}-${version}-mac-x64.zip"
    else
      "${appname}-${version}-linux-x64.tar.xz";
  src = fetchurl {
    url =
      "https://github.com/jeffvli/feishin/releases/download/v${version}/${filename}";
    sha256 =
      if stdenv.isDarwin then
        "sha256-6GYp9uzlR1eVRYhNU3kOmcUOPFY3J9eJPqN+TucNavA="
      else
        "sha256-Y8r329rO7z8V2xP/uRsjTFJfvTn+zyeAYzq6fKDxXs4=";
  };
  ```

**Comment by Artturin** [comment]
Don't use merge in PR's here, instead rebase if you have to update the branch.

There should only be one commit in this PR

**Comment by nephalemsec** [comment]
> Don't use merge in PR's here, instead rebase if you have to update the branch.
> 
> There should only be one commit in this PR, use `git rebase` to drop the merge and fixup the commits.

Are these official instructions or your personal opinions as I don't see this in the contributing page? I just followed instructions on the contributing.md to the letter.

It states that squashing commits isn't required if they give context to an additional change.

**Comment by Artturin** [comment]
> > Don't use merge in PR's here, instead rebase if you have to update the branch.
> > There should only be one commit in this PR, use `git rebase` to drop the merge and fixup the commits.
> 
> Are these official instructions or your personal opinions as I don't see this in the contributing page? I just followed instructions on the contributing.md to the letter.

Not having merge commits is common PR hygiene.
 
> It states that squashing commits isn't required if they give context to an additional change.

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions

This line applies 

> If you have commits pkg-name: oh, forgot to insert whitespace: squash commits in this case. Use git rebase -i.


Having more than one trivial update commit to the same package in a PR is logically unnecessary.

**Comment by nephalemsec** [comment]
While I appreciate the advice I really don't think there is an overabundance of commits in here that would confuse/disorientate anyone reviewing this PR.

**Comment by Artturin** [comment]
I've done it for you, Please remember the advice for your future PRs because other reviewers will say the same.

Also fixed a deprecation warning during the desktop file build

**Comment by onny** [comment]
Result of `nixpkgs-review pr 257430` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>feishin</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you both for updating!

**Pull request merged**
