### PR TITLE
gitea: include "options" directory in "data" output

### LINKED ISSUE #49404: Gitea can't intialize repositories during creation
## Issue description

Enabling the `Initialize Repository` option during repository creation makes it fail with Internal Server Error.

Additionally, the repository creation page doesn't list `.gitignore`, `License` and `README` templates.

### Steps to reproduce

Enable `services.gitea` in NixOS configuration, open Gitea in browser, register a user, go to Create Repository page, enter repository name, check the `Initialize Repository` checkbox, click `Create  Repository`, see it fails.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(paul): `""`
 - channels(root): `"nixos-18.09.932.09195057114, nixos-unstable-19.03pre155751.45a419ab5a2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by pvgoran**
This directory contains template files needed for initializing new repositories.

Fixes #49404.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build gitea

**Comment by markuskowa** [comment]
@GrahamcOfBorg build gitea

**Comment by markuskowa** [comment]
builder issue on aarch64 is unrelated to this PR (https://github.com/NixOS/nixpkgs/pull/48128)

**Comment by pvgoran** [comment]
How about adding this to 18.09? @markuskowa?

**Comment by markuskowa** [comment]
It is a simple bug fix, so I would say yes to backporting this.
@Mic92 does this qualify for a backport?

**Comment by markuskowa** [comment]
cherry picked for release-18.09 5c1cf68a949d535d3498aa405d584fe55fe9061e

**Comment by pvgoran** [comment]
@markuskowa Thank you.

**Pull request merged**
