### PR TITLE
tree-wide: fix pulseaudio references; fix SDL expressions

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Side-effect of me building everything with `libcardiacarrest` instead of `libpulseaudio` (see #35374).
That branch has quite a lot of changes ATM and some will likely to cause bikeshedding, so I split fixes that I tested to be real nice into here.

Finally, a properly compiled SDL!

I'm building on top of an older revision so that you could just merge with this without hitting any master bugs like #36268.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
- [X] Tested compilation of many pkgs that depend on this change
- [X] Tested execution of many said pkgs
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by oxij** [comment]
Well, that last part failed, as upstream updated SDL expressions. But here's the branch that works with an older master https://github.com/oxij/nixpkgs/tree/pkgs/fix-pulseaudio-references-old before 71f899c2c3b114ecf133ee0f25e6f2ef42df1d07 of #34461

**Comment by Mic92** [comment]
@GrahamcOfBorg build SDL SDL2

**Comment by oxij** [comment]
Looking at x86_64-darwin failure
```
In file included from ./src/video/x11/SDL_x11dyn.c:96:
./src/video/x11/SDL_x11sym.h:168:17: error: conflicting types for '_XData32'
SDL_X11_SYM(int,_XData32,(Display *dpy,register long *data,unsigned len),(dpy,data,len),return)
                ^
/nix/store/w2d2cxxzbnshcv1yjkw74p20cy2nkki6-libX11-1.6.5-dev/include/X11/Xlibint.h:673:12: note: previous declaration is here
extern int _XData32(
           ^
1 error generated.
```
I say it's SDL's/Darwin's problem. Was it working before?

**Comment by 7c6f434c** [comment]
https://hydra.nixos.org/job/nixpkgs/trunk/SDL.x86_64-darwin

**Comment by 7c6f434c** [comment]
Argh, the log for a recent Darwin failure is not available.

**Comment by oxij** [comment]
2018-02-27 was a long time ago, I see no reason why specifically this could have broken it.

**Comment by 7c6f434c** [comment]
SDL expression doesn't want a rebuild daily, though. Might be the freshest version.

**Comment by 7c6f434c** [comment]
Maybe the flag `--disable-x11-shared` matters?

**Comment by oxij** [comment]
Let's see. Can you ask ofbord to rebuild it again?

**Comment by oxij** [comment]
There's also this https://bugzilla.libsdl.org/show_bug.cgi?id=1769 and https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/media-libs/libsdl/files/libsdl-1.2.15-const-xdata32.patch
But why Linux build doesn't hit it is a mystery.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build SDL SDL2 tdesktop

**Comment by oxij** [comment]
Now tdesktop broke the darwin build... Can you run "build SDL" only?

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build SDL SDL2

**Comment by 7c6f434c** [comment]
Hm. Given the existence of `meta.available`, maybe Borg could build only the supported stuff, and just list the evaluation-failures separately… no idea how much work is that.

(the fact that `tdesktop` doesn't change after the cleanup is a fact I also wanted to check)

**Comment by grahamc** [comment]
what is `meta.available`?

**Comment by oxij** [comment]
Another round of rebuilds, please.

**Comment by 7c6f434c** [comment]
@grahamc after some refactorings (by @oxij) `stdenv` adds `meta.available` which is basically «not broken, no direct platform problems, license matches the policy»

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build SDL SDL2

**Comment by oxij** [comment]
@grahamc a cheap way to check if the derivation is supported without doing `tryEval`.

**Comment by grahamc** [comment]
@oxij perhaps you'd be interested in becoming a known user like https://github.com/NixOS/ofborg/pull/97

**Comment by oxij** [comment]
Darwin, ugh.

@grahamc Do I need to sign anything to do that? :) I'm bit lazy to clone it and setup git remotes just for a one-line change. Could you please add me there?

**Comment by grahamc** [comment]
Nope, and you can just edit the file right on the github web UI.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build SDL2

**Comment by oxij** [comment]
@grahamc Ok. I didn't know such magic existed. Done https://github.com/NixOS/ofborg/pull/98

**Comment by 7c6f434c** [comment]
This PR, by the way, is a good example where platform choice for builds would be nice — I don't want the Linux builds for _every_ attempt.

**Comment by 7c6f434c** [comment]
@oxij just for fun: being a _known_ user but not _trusted_ user doesn't let you start Darwin builds…

**Comment by 7c6f434c** [comment]
Maybe it is a good idea to merge `firefox-bin` and `tdesktop` cleanups?

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build SDL

**Comment by oxij** [comment]
Hooraaay!

**Comment by oxij** [comment]
And f*ck darwin!

**Comment by oxij** [comment]
Ok, let me add some comments about this, and then lets merge.

**Comment by oxij** [comment]
Done. Please ask ofbord for the last round for both SDL and SDL2. I'm a bit paranoid that I could have broken something while cleaning up f114118842e19ced171fd634d6ff70a92746f2cb.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg SDL SDL2

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build SDL SDL2

**Comment by oxij** [comment]
Yay. Feel free to merge into master or staging then. I'm off to fixing bugs in PA apps.

**Comment by 7c6f434c** [comment]
Could you retarget this to `staging`? I hate git magic…

**Comment by 7c6f434c** [comment]
@oxij Sorry, retarget and rebase.

**Comment by oxij** [comment]
Well, the problem is that staging doesn't merge with master and this doesn't apply to staging. I tried merging those, but got an enormous merge commit and I'm uncomfortable about it. Can't we merge to master?

**Comment by oxij** [comment]
Or if any of @FRidh @dezgeg @vcunat merge master into staging I'll rebase on top of the result.

**Comment by 7c6f434c** [comment]
Merging `master` and `staging` in any direction is always a long story, of course. But what of your changes isn't cherry-pickable on staging? 

I don't like that there are many rebuilds _and_ multiple rebuilds that are both large and often used (`ffmpeg`, for example).

**Comment by oxij** [comment]
All of SDL changes don't apply after 34461

**Comment by 7c6f434c** [comment]
I wonder if separately merging #34461 to `staging` is a good idea and will it cause any problems for a real `master` merge.

**Comment by 7c6f434c** [comment]
OK, I now have an excuse to merge into master

**Comment by oxij** [comment]
#36389? That and this should work ok together, I think, but I would rebuild it another time just to be sure.

**Comment by 7c6f434c** [comment]
I think our experience here is that SDL2 is less fragile than SDL1, so I decided to believe that its point releases are not that different.

**Comment by oxij** [comment]
Well, ok. Huge thanks!

**Comment by oxij** [comment]
This still broke things on Darwin :( See #36514 for a fix.

**Pull request merged**
