### PR TITLE
wtf: 0.23.0 -> 0.24.0

### PR DESCRIPTION
**Pull request by avdv**
###### Motivation for this change

New upstream release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by marsam** [comment]
Since nixpkgs already has Go 1.13, I think we can remove the `overrideModAttrs`. Can you check if the following works for you?

```diff
diff --git i/pkgs/applications/misc/wtf/default.nix w/pkgs/applications/misc/wtf/default.nix
index 46c13408143..f20c4aff169 100644
--- i/pkgs/applications/misc/wtf/default.nix
+++ w/pkgs/applications/misc/wtf/default.nix
@@ -9,10 +9,6 @@ buildGoModule rec {
   pname = "wtf";
   version = "0.24.0";
 
-  overrideModAttrs = _oldAttrs : _oldAttrs // {
-    preBuild = ''export GOPROXY="https://gocenter.io"'';
-  };
-
   src = fetchFromGitHub {
     owner = "wtfutil";
     repo = pname;
@@ -20,10 +16,12 @@ buildGoModule rec {
     sha256 = "0jz7hjcm0hfxcih2zplp47wx6lyvhhzj9ka4ljqrx0i4l7cm9ahs";
    };
 
-  modSha256 = "03vj6q1ln71r685k2j91ycj6xxrc688pj4bdc561693r20sr49xj";
+  modSha256 = "04d8hvd90f7v853p23xcx38qz3ryv7kz7zjk9b131cjnd4mcv0sm";
 
   buildFlagsArray = [ "-ldflags=-s -w -X main.version=${version}" ];
 
+  subPackages = [ "." ];
+
   nativeBuildInputs = [ makeWrapper ];
 
   postInstall = ''
diff --git i/pkgs/top-level/all-packages.nix w/pkgs/top-level/all-packages.nix
index fb992084797..12ff6823846 100644
--- i/pkgs/top-level/all-packages.nix
+++ w/pkgs/top-level/all-packages.nix
@@ -25325,9 +25325,7 @@ in
 
   zimg = callPackage ../development/libraries/zimg { };
 
-  wtf = callPackage ../applications/misc/wtf {
-    buildGoModule = buildGo112Module;
-  };
+  wtf = callPackage ../applications/misc/wtf { };
 
   zk-shell = callPackage ../applications/misc/zk-shell { };
 
```

**Comment by avdv** [comment]
> Since nixpkgs already has Go 1.13, I think we can remove the `overrideModAttrs`. Can you check if the following works for you?

Yes, works for me! :+1:

**Comment by avdv** [comment]
@marsam I have pushed your change as a new commit on your behalf. Hope that's OK?!

**Comment by marsam** [comment]
yes, thank you for working on this

**Pull request merged**
