### PR TITLE
rbw: 1.11.1 -> 1.12.1

### LINKED ISSUE #163: failed to decrypt: failed to decrypt encrypted secret: invalid mac
Hello,

We a team using `rbw` inside `nix` + `devbox`.
It is working fine globally but on the computer of one of my coworkers, we are getting the following error:
```
rbw get default-ansible_env >.env
rbw get: couldn't find entry for 'default-ansible_env': failed to decrypt: failed to decrypt encrypted secret: invalid mac
```

It has been working weeks ago without issues, it seems that it's broken since he did latest fedora updates (can't be sure of this, since he doesn't use it a lot)

It seems that commands like `register`, `sync`, `login` are working fine, but unencrypting local database fails.

EDIT:
* he tried `cargo install rbw` instead of using `devbox` / `nix` → same issue.
* we use `vaultwarden`

### PR DESCRIPTION
**Pull request by pyrox0**
## Description of changes
https://github.com/doy/rbw/releases/tag/1.12.0
https://github.com/doy/rbw/releases/tag/1.12.1

Fixes https://github.com/doy/rbw/issues/163

Supercedes #330788

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by soopyc** [comment]
Result of `nixpkgs-review pr 333147` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>rbw</li>
    <li>rofi-rbw</li>
    <li>rofi-rbw-wayland</li>
    <li>rofi-rbw-wayland.dist</li>
    <li>rofi-rbw-x11</li>
    <li>rofi-rbw-x11.dist</li>
    <li>rofi-rbw.dist</li>
  </ul>
</details>

Couldn't test `rofi-rbw` since I don't use `rofi`, but the `rbw` executable works fine.

Some mentioned that this should be backported to 24.05, should the label be added?

**Review by soopyc — APPROVED** [review]

**Review by MaxwellDupre — APPROVED** [review]
Simple version bump.

**Comment by sedlund** [comment]
Can add backport?  The version in unstable is broken still.

**Comment by K900** [comment]
Yeah, thanks for the reminder.

**Comment by zhaochunqi** [comment]
I've noticed that the aarch64-darwin package has been missing since version v1.10.2. This can be verified at [nixos-stable-rbw](https://hydra.nixos.org/job/nixos/release-24.05/nixpkgs.rbw.aarch64-darwin).

I'm not very familiar with our packaging mechanism here. Could someone please help investigate this issue? Any assistance would be greatly appreciated.

**Comment by sedlund** [comment]
@zhaochunqi 

Bug in nixos-search https://github.com/NixOS/nixos-search/issues/748

Darwin builds are in different jobset:

https://hydra.nixos.org/jobset/nixpkgs/nixpkgs-24.05-darwin#tabs-jobs

https://hydra.nixos.org/job/nixpkgs/nixpkgs-24.05-darwin/rbw.aarch64-darwin

**Comment by zhaochunqi** [comment]
Thank you for your kindly response. Based on your guidance, I discovered that the issue was caused by my home manager not updating the software, rather than rbw not being updated.

**Pull request merged**
