### PR TITLE
libphonenumber, pn: bump and fix build on darwin

### PR DESCRIPTION
**Pull request by smancill**
###### Motivation for this change

`libphonenumber` is broken on darwin. `pn` depends on `libphonenumber` so it's also broken.

ZHF: #144627  (@NixOS/nixos-release-managers)

###### Things done

Fix `libphonenumber` build by adding missing framework to build inputs.

Since there is no point in fixing older releases, also bump both `libphonenumber` and `pn`.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
ping me when the other maintainers do not react in a couple of days please

**Review by jonringer — APPROVED** [review]
diff LGTM

cc @NixOS/darwin-maintainers

**Comment by risicle** [comment]
Hmm... I think this might break `evolution-data-server` for me on aarch64-linux.

**Comment by smancill** [comment]
> Hmm... I think this might break `evolution-data-server` for me on aarch64-linux.

Ok, I just thought that since `libphonenumber` has not been updated in almost two years (68c783cde5a),  it was appropriated to update now for the 21.11 release.

If it breaks things, I can  just re-push this with only the fix for darwin, without bumping `libphonenumber`.

**Comment by risicle** [comment]
Nope don't worry the version on `master` hates my machine too. False alarm.

**Review by McSinyx — APPROVED** [review]
The version bump for `pn` LGTM.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 146508 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>7 packages marked as broken and skipped:</summary>  <ul>    <li>gnome.gnome-documents</li>    <li>libsForQt512.plasma-dialer</li>    <li>libsForQt512.spacebar</li>    <li>libsForQt514.plasma-dialer</li>    <li>libsForQt514.spacebar</li>    <li>xmonad_log_applet</li>    <li>xmonad_log_applet_gnome3</li>  </ul></details><details>  <summary>60 packages built:</summary>  <ul>    <li>adapta-gtk-theme</li>    <li>almanah</li>    <li>bubblemail</li>    <li>calls</li>    <li>chatty</li>    <li>chrome-gnome-shell</li>    <li>dropbox-cli</li>    <li>elementary-planner</li>    <li>empathy</li>    <li>evolution</li>    <li>evolution-data-server (evolution_data_server)</li>    <li>evolution-ews</li>    <li>evolutionWithPlugins</li>    <li>folks</li>    <li>gnome.bijiben</li>    <li>gnome.file-roller</li>    <li>gnome.geary</li>    <li>gnome.gnome-applets</li>    <li>gnome.gnome-books</li>    <li>gnome.gnome-boxes</li>    <li>gnome.gnome-calendar</li>    <li>gnome.gnome-contacts</li>    <li>gnome.gnome-control-center</li>    <li>gnome.gnome-flashback</li>    <li>gnome.gnome-maps</li>    <li>gnome.gnome-panel</li>    <li>gnome.gnome-photos</li>    <li>gnome.gnome-session</li>    <li>gnome.gnome-shell</li>    <li>gnome.gnome-terminal</li>    <li>gnome.gnome-todo</li>    <li>gnome.gnome-tweak-tool</li>    <li>gnome.gnome-user-share</li>    <li>gnome.nautilus</li>    <li>gnome.nautilus-python</li>    <li>gnome.tracker-miners</li>    <li>gnomeExtensions.easyScreenCast</li>    <li>gnomeExtensions.gsconnect</li>    <li>gnomeExtensions.night-theme-switcher</li>    <li>kgx</li>    <li>libphonenumber</li>    <li>libsForQt5.plasma-dialer</li>    <li>libsForQt5.spacebar</li>    <li>pantheon.elementary-calendar</li>    <li>pantheon.elementary-greeter</li>    <li>pantheon.elementary-mail</li>    <li>pantheon.elementary-session-settings</li>    <li>pantheon.elementary-tasks</li>    <li>pantheon.extra-elementary-contracts</li>    <li>pantheon.file-roller</li>    <li>pantheon.switchboard-plug-onlineaccounts</li>    <li>pantheon.switchboard-with-plugs</li>    <li>pantheon.wingpanel-applications-menu</li>    <li>pantheon.wingpanel-indicator-datetime</li>    <li>pantheon.wingpanel-with-indicators</li>    <li>phosh</li>    <li>pn</li>    <li>synology-drive</li>    <li>vimix-gtk-themes</li>    <li>whitesur-gtk-theme</li>  </ul></details>

**Pull request merged**
