### PR TITLE
Update macOS to 10.12

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This is big enough that it probably needs its own jobset. This bumps the SDKs to 10.12, as well as adds symbols only available in 10.12. As a result, this means that Nixpkgs will only work on systems with macOS 10.12+.

Other things done:
- In addition, I've brought back the cross patch shebangs work. It needed some tweaking to get things working but the final result doesn't leak bootstrap-tools.
- Removed some old patches that should not be needed with newer SDKs.
- Update LLVM to 7 everywhere (/cc @dtzWill). Based off of #56490.
- Add libtapi support for cctools. This is just a flag to cctools-port that it can use.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
> Oh, does cf-private add `-framework CoreFoundation`? If so we can probably get rid of it in a bunch of other places.

It adds /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation to get the objc runtime. It should only be needed if you get errors like:

```
_OBJC_CLASS_$_NSArray is undefined
```

**Comment by matthewbauer** [comment]
If you are just missing _NS* symbols you just need ```-framework CoreFoundation```

**Comment by matthewbauer** [comment]
If anyone would like to help out, these are some of the things broken by the update:

- [ ] guile
- [ ] gtk+
- [ ] boost

**Comment by LnL7** [comment]
Do you think it's ready for a first eval? That should make it easier to get an overview of what still needs to happen.

**Comment by matthewbauer** [comment]
Yeah definitely!

**Comment by LnL7** [comment]
https://hydra.nixos.org/eval/1507952

**Comment by matthewbauer** [comment]
Ugh... OSXPrivateSDK is still on 10.10 and I can't find one for 10.12. I wonder if we can get by without it?

/cc @copumpkin

**Comment by LnL7** [comment]
Yeah, but didn't we get rid of almost every reference to the private sdk?

**Comment by tobim** [comment]
Boost added this patch in 1.69: https://github.com/boostorg/atomic/commit/6e14ca24dab50ad4c1fa8c27c7dd6f1cb791b534.

**Comment by matthewbauer** [comment]
@lnl7 this should be ready for a refresh once we get through the hydra backlog

**Comment by LnL7** [comment]
https://hydra.nixos.org/eval/1509598

**Comment by veprbl** [comment]
Here is a fix for boost
```diff
diff --git a/pkgs/development/libraries/boost/1.67.nix b/pkgs/development/libraries/boost/1.67.nix
--- a/pkgs/development/libraries/boost/1.67.nix
+++ b/pkgs/development/libraries/boost/1.67.nix
@@ -3,11 +3,33 @@
 callPackage ./generic.nix (args // rec {
   version = "1.67_0";
 
-  patches = [ (fetchpatch {
-    url = "https://github.com/boostorg/lockfree/commit/12726cda009a855073b9bedbdce57b6ce7763da2.patch";
-    sha256 = "0x65nkwzv8fdacj8sw5njl3v63jj19dirrpklbwy6qpsncw7fc7h";
-    stripLen = 1;
-  })];
+  patches = [
+    (fetchpatch {
+      url = "https://github.com/boostorg/lockfree/commit/12726cda009a855073b9bedbdce57b6ce7763da2.patch";
+      sha256 = "0x65nkwzv8fdacj8sw5njl3v63jj19dirrpklbwy6qpsncw7fc7h";
+      stripLen = 1;
+    })
+  ] ++ stdenv.lib.optionals stdenv.cc.isClang [
+    # Fixes https://github.com/boostorg/atomic/issues/15
+    (fetchpatch {
+      url = https://github.com/boostorg/atomic/commit/6e14ca24dab50ad4c1fa8c27c7dd6f1cb791b534.patch;
+      sha256 = "102g35ygvv8cxagp9651284xk4vybk93q2fm577y4mdxf5k46b7a";
+      stripLen = 1;
+    })
+
+    # Needed for the next patch
+    (fetchpatch {
+      url = https://github.com/boostorg/asio/commit/38cb19719748ad56b14d73ca1fff5828f36e5894.patch;
+      sha256 = "0cj9cxz9rfbsx8p8f5alxx00dq3r7g0vh23j68bbxbs9gq1arq2n";
+      stripLen = 1;
+    })
+    # Fixes https://github.com/boostorg/asio/pull/91
+    (fetchpatch {
+      url = https://github.com/boostorg/asio/commit/43874d5497414c67655d901e48c939ef01337edb.patch;
+      sha256 = "1c2ds164s2ygvpb4785p4ncv8ywbpm08cphirb99xp4mqvb693is";
+      stripLen = 1;
+    })
+  ];
 
   src = fetchurl {
     url = "mirror://sourceforge/boost/boost_1_67_0.tar.bz2";
```

**Comment by matthewbauer** [comment]
@veprbl Thanks! Will apply it tonight

**Comment by matthewbauer** [comment]
@lnl7 if you could refresh it again that would be great! Hoping to set out some time this weekend to finally get this into staging.

**Comment by LnL7** [comment]
@matthewbauer Is this rebased against another eval? That makes it easier to find the list of remaining regressions.

**Comment by softinio** [comment]
Any possibility to continue support for macos 10.11+ ?

**Comment by matthewbauer** [comment]
> Any possibility to continue support for macos 10.11+ ?

This is kind of difficult. My thinking was that 19.03 would be the last version to support 10.11. 10.11 was released in June 2015 so we are nearing Apple's support cut off. Perhaps we can try to support 19.03 for a little longer than usual for those users still stuck on 10.11 for other reasons.

**Comment by LnL7** [comment]
If there's enough interest in that we could investigate, but I think we should focus on getting this ready first.

@matthewbauer That last rebase was based on a bad commit so I aborted all the jobs.

**Comment by matthewbauer** [comment]
Ok rebased onto master.

**Comment by LnL7** [comment]
https://hydra.nixos.org/eval/1515375?compare=1515295

**Comment by ttuegel** [comment]
The Qt changes look OK to me if everything builds, but I don't feel qualified to comment on the rest.

**Comment by matthewbauer** [comment]
@lnl7 could you refresh the eval?

**Comment by matthewbauer** [comment]
Last big thing left is getting rustc to work:

https://hydra.nixos.org/build/92523224

**Comment by LnL7** [comment]
https://hydra.nixos.org/eval/1515610?compare=1515295

**Comment by softinio** [comment]
@matthewbauer if there is any help I can give though new to nix to maintain a level of 10.11 (El Capitan) support let me know. Fair point about if not possible, guess if I need the support I can stick to 19.03 at least.

**Comment by ThomasMader** [comment]
I recognized that you disabled the entire checkPhase for ldc on Darwin.
The error coming from there seems to me to be very serious. I think ldc might have trouble working correctly making it unusable on Darwin.

For dmd the commented make line in the checkPhase should work now again with your changes about the filesystem stuff in the linker and should fix https://github.com/NixOS/nixpkgs/issues/57120 .

**Comment by matthewbauer** [comment]
> I recognized that you disabled the entire checkPhase for ldc on Darwin.
> The error coming from there seems to me to be very serious. I think ldc might have trouble working correctly making it unusable on Darwin.
> 
> For dmd the commented make line in the checkPhase should work now again with your changes about the filesystem stuff in the linker and should fix #57120 .

I was able to compile and run some simple D code, but I can work on getting the tests passing as well

**Comment by LnL7** [comment]
@matthewbauer After reading your post I realised that we didn't update `MACOSX_DEPLOYMENT_TARGET`, not a big deal but perhaps we should?

**Comment by matthewbauer** [comment]
> @matthewbauer After reading your post I realised that we didn't update `MACOSX_DEPLOYMENT_TARGET`, not a big deal but perhaps we should?

Yeah that would be a good idea! Also removing the `gl_cv_func_getcwd_abort_bug` thing should be possible

**Pull request merged**
