### PR TITLE
curl: fix infinite recursion in staging-next

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

Fixes the infinite recursion in staging-next #257792. Built both Python 3 and curl.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
It's a thing not changed in this PR, but I find it confusing that the `fetchurlBoot` defined in `pkgs/stdenv/darwin/default.nix` is actually an almost-normal fetchurl, not like on linux where it's mostly built-in from nix.

**Comment by vcunat** [comment]
The recursion issue had been reverted/solved, so I think the main expected benefit of this PR should be in adding those frameworks, which supposedly fixes [some issues with macOS 14](https://github.com/curl/curl/issues/11893)?

Those issues were reported with 8.3.0 which we already had in nixpkgs master, so let's not be hasty here and keep the current `staging-next` iteration without this nontrivial change?  Hopefully it could get better review thanks to that.  (I expect it's still desirable to catch 23.11.)

**Comment by reckenrode** [comment]
> It's a thing not changed in this PR, but I find it confusing that the `fetchurlBoot` defined in `pkgs/stdenv/darwin/default.nix` is actually an almost-normal fetchurl, not like on linux where it's mostly built-in from nix.

I tried to change it when I was working on #240433, but the Darwin stdenv bootstrap has dependencies that use `fetchpatch` and `fetchFromGitHub`. Even if the patches could be moved in-tree, there’s still the problem of dependencies hosted on GitHub, which need special handling to hash deterministically.

> The recursion issue had been reverted/solved, so I think the main expected benefit of this PR should be in adding those frameworks, which supposedly fixes [some issues with macOS 14](https://github.com/curl/curl/issues/11893)?

It does that, but a more practical benefit to nixpkgs is it makes curl build (more or less) like any other normal package. It will (or should) be able to link whatever frameworks it needs. Future updates that require more should be less painful.
 
> Those issues were reported with 8.3.0 which we already had in nixpkgs master, so let's not be hasty here and keep the current `staging-next` iteration without this nontrivial change? Hopefully it could get better review thanks to that. (I expect it's still desirable to catch 23.11.)

I retargeted it to staging. I’d personally rank this change behind #241692 and #256590 for 23.11, but I otherwise agree it’s desirable because it will make backporting curl updates to 23.11 much easier (especially if they happen to require additional frameworks).

**Review by toonn — APPROVED** [review]
LGTM

**Pull request merged**
