### PR TITLE
Fixing and updating shake, the haskell make-alike.

### PR DESCRIPTION
**Pull request by krisajenkins**
Since this is a dependency of `nixpkgs.haskellPackages.hoogle`, it will probably be a more popular fix than it might first seem. :-)

### CODE REVIEW

**Comment by copumpkin** [comment]
Does the build tool have to be `gcc`? Can we shove a more generic `cc` into it?

**Comment by peti** [comment]
On second thought, this patch makes no sense to me. `gcc`/`cc` are *always* available in build environments created by `stdenv.mkDerviation`, so I can't see how adding `gcc` to the build tools stanza could possibly make any difference. In fact, the `shake` expression in `haskell-ng` does not do that, yet `shake` works fine there.

@krisajenkins, do you remember for what reason that attribute was added?

**Comment by copumpkin** [comment]
That probably just means it should be patched to just ask for cc, like most
things. Mac OS 10.10 stopped shipping with a program called gcc.

**Comment by ndmitchell** [comment]
For info, the next version Hoogle 5 will no longer require Shake, so the popularity of Shake may decrease.

**Pull request merged**
