### PR TITLE
Update openssl to 1.0.1o

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by DamienCassou** [comment]
@peti could you please check?

**Comment by peti** [comment]
Changes like this one should always go through `staging`.

**Comment by edolstra** [comment]
Thanks for the heads up, I've updated staging (which already had 1.0.1n, containing the recent CVE fixes).

**Comment by DamienCassou** [comment]
@peti what do you mean by "like this"? How do I know where a commit should go?

**Comment by peti** [comment]
@DamienCassou, commits that cause a massive number of rebuilds ought to go through `staging`. If you change a package that belongs to `stdenv`, for instance, then the patch shouldn't be merged to `master` directly.

**Pull request closed without merging**
