### PR TITLE
notmuch: add separate `emacs` output

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
Emacs takes around 150Mb in closure size. `neomutt` is a package which uses notmuch as a library and users that don't use Emacs don't need this feature enabled. Hence to reduce closure size, while still supporting Emacs users of notmuch the emacs-related binary and emacs lisp files were moved to a `notmuch.emacs` output.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Supersedes #84610.

### CODE REVIEW

**Review by doronbehar — APPROVED** [review]
I tested the build of it and `nix-store -q --references $(nix-build -A notmuch)` doesn't mention emacs. Great!

Do you know @flokli why it works? This kind of issues have been bothering me since my early days in NixOS so I'm very curios.

**Comment by flokli** [comment]
So, there's some documentation in `doc/stdenv/multiple-output.xml`, but I have to admin, it's very sparse.

I think in your previous iteration, the code moving manpages etc. was triggering a bug in `multiple-outputs.sh:127`, because there still was something else in `$out/share/…` (`$out/share/emacs`, in our case). Can you push the ref containing the example somewhere? Then we could open an issue to narrow it down and fix it proprly.

By moving things into the `emacs` output before `multiple-outputs.sh`, we might have avoided triggering this edgecase, as $out/share was empty after everything else was moved away by the default handlers.

**Comment by doronbehar** [comment]
> Can you push the ref containing the example somewhere?

TBH @flokli [I don't care enough](https://discourse.nixos.org/t/could-weve-implemented-multi-output-packages-better/6597) in order to narrow it down, sorry :/. You can trigger the bug yourself by taking the derivation as in `master` and add a `"lib"` output.

**Comment by flokli** [comment]
Yeah, I think we should move the discussion into that discourse post :-)

**Comment by lheckemann** [comment]
This breaks emacs-notmuch (surprise!) :/ opinions on adding a release notes entry?

**Comment by doronbehar** [comment]
Added ? https://github.com/NixOS/nixpkgs/pull/84663/files#diff-43de86228df91216c5cfc9446cb041fe

**Comment by lheckemann** [comment]
:see_no_evil: sorry, missed that

**Pull request merged**
