### PR TITLE
Introduce emacsPackagesNg.multiple-cursors

### PR DESCRIPTION
**Pull request by aycanirican**

### CODE REVIEW

**Comment by jagajaga** [comment]
Rename commit as it said in `CONTRIBUTING.md`.

**Comment by aycanirican** [comment]
@jagajaga I hope it looks better.

**Comment by jagajaga** [comment]
Name it as `multiple-cursors: init at 20150627`, please :)

**Comment by aycanirican** [comment]
@jagajaga hope that it is ok now.

**Pull request merged**
