### PR TITLE
autogen: 5.18.5 -> 5.18.6

### PR DESCRIPTION
**Pull request by lsix**
See http://lists.gnu.org/archive/html/info-gnu/2015-09/msg00006.html for
announcement

### CODE REVIEW

**Comment by lancelotsix** [comment]
Looks like this triggers heavy rebuilds (and causes the CI to fail due to too long build time)

**Comment by vcunat** [comment]
Staged.

**Comment by vcunat** [comment]
BTW, you seem to commit with e-mail not connected to your github account.

**Comment by lancelotsix** [comment]
Oh, thanks for noticing the e-mail issue.

**Comment by vcunat** [comment]
:-)

**Pull request closed without merging**
