### PR TITLE
[haskell/generic-builder] windows always has an active library

### PR DESCRIPTION
**Pull request by angerman**
###### Motivation for this change

Broken out of #43559

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peti** [comment]
I am sorry, but I don't understand the reason behind this change. I also read the commit message and now I am even more confused than before. Could you please re-state your reasons for making this change to help me understand what you mean by "the check is wrong"? And why is Windows different than other platforms?

**Comment by angerman** [comment]
@peti, fair point, this is a rather confusing PR. And I'm not even happy with it.

Here's the underlying issue: nixpkgs assumes that there is a library if it's either dynamic, or static, or profiling; and it's a library to begin with. This however is not correct. You can have a library that is neither `--enable-static`, nor `--enable-shared`. That is you end up with a library that is just a collection of obejct files as well as an aggregated archive.

The underlying issue is that `--enable-static` with `cabal` passes `-staticlib` to ghc, and `-staticlib` does not work on windows, and as such you can't set `enableStaticLibraries`, but at the same time if you don't want `enableSharedLibraries`, you end up with **empty** libraries, which is certainly not what you want.

**Review by peti — COMMENTED** [review]
I'll just trust your judgement going forward with this. Please do whatever you think is best. :-)

**Review by matthewbauer — APPROVED** [review]
I think this is an okay thing for now. Especially if it gets us closer to ghc/mingw support.

**Comment by angerman** [comment]
To be fair, I think the correct solution is to get rid of the `hasActiveLibrary` logic, and just go with `isLibrary`.
The reasoning is as follows:
- `enableStaticLibraries` -> `hasActiveLibrary`
- `enableSharedLibraries` -> `hasActiveLibrary`
- `enableLibraryProfiling` -> `hasActiveLibrary`
and as I outlined above, `!enableStaticLibraries && !enableSharedLibraries && !enableLibraryProfiling` should not imply `!hasActiveLibrary`.

**Comment by ryantm** [comment]
@GrahamcOfBorg eval

**Comment by ryantm** [comment]
@GrahamcOfBorg eval

**Comment by ryantm** [comment]
I didn't look at this carefully, but I'm going to merge it based on all the approval it has. Let's see how it does on Hydra!

**Pull request merged**
