### PR TITLE
citrix_workspace: add 21.04.0.11

### PR DESCRIPTION
**Pull request by adisbladis**
ChangeLog: https://docs.citrix.com/en-us/citrix-workspace-app-for-linux/whats-new.html#whats-new-in-2104

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by pmenke-de — COMMENTED** [review]
The changes to the package look good to me.
I though have some issues with the new version.
When launching applications i get multiple UI error messages:
image
image

After dismissing, the application starts normally.
I've run into the same problem, when trying to update the package myself a couple of weeks ago, but didn't have the time to debug it yet.

Does this issue also happen in your environment?
Would be good to known, if this is a general issue or only on my particular setup.

Thank you and kind regards.

**Comment by adisbladis** [comment]
> Does this issue also happen in your environment?
Would be good to known, if this is a general issue or only on my particular setup.

It doesn't happen to me but admittedly my use is very simple so I may just not have hit the same thing for that reason.

**Comment by pmenke-de** [comment]
> It doesn't happen to me but admittedly my use is very simple so I may just not have hit the same thing for that reason.

Hm. Interesting. I do get these error right away when i start any application via the `selfservice` UI, or when i launch it directly via `storebrowse  -L Controller.Outlook https://$server/citrix/citrix-ui/discovery`.
So i guess if you use the application in any capacity, but the error doesn't occur for you, it may just be a problem on my end.

@Ma27, do you still have access to a citrix environment and care to also test this PR?

**Comment by Ma27** [comment]
Just a wild guess, perhaps it's related to

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/remote/citrix-workspace/generic.nix#L119-L121

Haven't read through the changelog, but back when I wrote this, you had to use `-icaroot` for `wfica` and maybe that has changed now?

**Comment by pmenke-de** [comment]
It seems to have some relation to that.

`wfica -help` still lists `-icaroot` (with one dash) as a supported option, but triggers the above error, when it gets executed during application launch. The command line (using `pstree`) looks like this: 
`/nix/store/jcl1zxf86s7s65p7jxmcc86ghcys4shb-citrix-workspace-21.4.0.11/opt/citrix-icaclient/wfica -icaroot /nix/store/jcl1zxf86s7s65p7jxmcc86ghcys4shb-citrix-workspace-21.4.0.11/opt/citrix-icaclient -IcaSessionAddr 043bf961-6744-
465b-b1c8-b7644d6cadd9`
When i run this command manually from my shell, it just does nothing - probably because that IcaSessionAddr value isn't valid anymore and citrix does a load of DBus / IPC magic. If run without the `-IcaSessionAddr` argument it "only" complains about no ICA file being given / it being "corrupt". If then the `-icaroot` option is changed to sth. invalid like `-icarooot`, it complains about the option being invalid (like in my screenshots above).
So in conclusion: I don't really understand, what happens inside there :disappointed: 

Anyways i can get rid of the problem by removing the `-icaroot` option in 21.04:
```
diff --git a/pkgs/applications/networking/remote/citrix-workspace/generic.nix b/pkgs/applications/networking/remote/citrix-workspace/generic.nix
index 506f129d359..f93a323829a 100644
--- a/pkgs/applications/networking/remote/citrix-workspace/generic.nix
+++ b/pkgs/applications/networking/remote/citrix-workspace/generic.nix
@@ -118,10 +118,12 @@ stdenv.mkDerivation rec {
   installPhase = let
     icaFlag = program:
       if (builtins.match "selfservice(.*)" program) != null then "--icaroot"
+      # wfica from 21.04 on doesn't like the -icaroot option despite listing it in its -help output
+      else if (lib.versionAtLeast version "21.04" && builtins.match "wfica(.*)" program != null) then null
       else "-icaroot";
     wrap = program: ''
       wrapProgram $out/opt/citrix-icaclient/${program} \
-        --add-flags "${icaFlag program} $ICAInstDir" \
+        ${lib.optionalString (icaFlag program != null) ''--add-flags "${icaFlag program} $ICAInstDir"''} \
         --set ICAROOT "$ICAInstDir" \
         --prefix LD_LIBRARY_PATH : "$ICAInstDir:$ICAInstDir/lib" \
         --set LD_PRELOAD "${libredirect}/lib/libredirect.so" \
```

On my machine it works™
But i'm unsure, whether this is the best option, when the problem could not be reproduced by anyone else yet *and* the option wasn't officially removed.

**Comment by Ma27** [comment]
> wfica -help still lists -icaroot (with one dash) as a supported option, but triggers the above error, when it gets executed during application launch. The command line (using pstree) looks like this:

Does `--icaroot` work?

Also, @adisbladis what did you do to test? Perhaps you did something slightly different and that's why you haven't found the issue :) 

If the approach suggested by @pmenke-de works fine, I think we should go with it for now & report the issue to Citrix.

**Comment by pmenke-de** [comment]
> Does `--icaroot` work?

Didn't work for my, no.
Should've mentioned that :smile:

**Comment by adisbladis** [comment]
@Ma27 Only some very basic stuff:
```
storebrowse -C ~/Downloads/receiverconfig.cr
wfica ~/Downloads/foo.ica
```

which works fine.

**Comment by pmenke-de** [comment]
Meanwhile v21.06.0.28 was released.
For me the `-icaroot` issue persists there as well.
Tested on this branch: https://github.com/NixOS/nixpkgs/compare/master...pmenke-de:citrix_workspace-21_06_0_28?expand=1

**Comment by mkaito** [comment]
For what it's worth, the archlinux package has a wrapper script setting the env var `ICAROOT`.

**Comment by utdemir** [comment]
It seems like `master` is already updated to 21.06.0: https://github.com/NixOS/nixpkgs/commit/8a815af4280f3e0d5ff740faa7d489e2b9e36829#diff-b0694b94ae7fa80cbe01a40af52f589131b3a09d4648d6c69cedc528c946c256

**Pull request closed without merging**
