### PR TITLE
expo-cli: init + implement overrideNodeAttrs

### LINKED ISSUE #93399: Packaging request: expo
**Project description**
Expo is a framework and a platform for universal React applications. It is a set of tools and services built around React Native and native platforms that help you develop, build, deploy, and quickly iterate on iOS, Android, and web apps from the same JavaScript/TypeScript codebase.

**Metadata**

* homepage URL: expo.io
* source URL: https://github.com/expo/expo/
* license: MIT 
* platforms: Unix

@nicknovitski Since you have worked on expo, I was wondering if you have expo running with nix. If so could you share your code?

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Closes: https://github.com/NixOS/nixpkgs/issues/93399

Had to implement `overrideNodeAttrs` to filter out optional `@expo/traveling-fastlane-darwin` dependency that was intentionally aborting the build on Linux.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
     - [x] Successfully ran react-native app on Android using this
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
cc @FRidh who implemented `overridePythonAttrs` I based this on

cc @Scriptkiddi who was also interested in this

**Comment by FRidh** [comment]
While I am not sure whether it is the correct direction to add these language/framework-specific overrides (see https://github.com/NixOS/rfcs/pull/67#discussion_r448127555) I do think the implementation in https://github.com/NixOS/nixpkgs/pull/87394 would be preferred over us implementing our own ones every time.

**Comment by jtojnar** [comment]
Thanks, I was trying to find the PR but did not realize it was closed. I agree with you but in the meantime I would like a working, if only temporary solution.

What do you think about gating it on explicit acknowledgement that the function can be dropped at any time?

**Comment by FRidh** [comment]
Well, I say we should just use that PR. Having those override functions does not preclude having a common override function which I proposed (that could be say `overrideArgs`.

**Comment by jtojnar** [comment]
I think I will use the local internal function for now, rather than switching to a public API that would be deprecated after RFC 67. I will port to that once it gets accepted.

**Pull request merged**
