### PR TITLE
treewide: mark failing kernel modules broken

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
part of #101863
follow-up to #101736
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
oops, asciidoc isn't meant to be there

**Review by worldofpeace — APPROVED** [review]
Looks good

**Comment by Atemu** [comment]
A little helper to help find more broken modules not marked as broken:

```Nix
{ pkgs ? import <nixpkgs> { } }:

with builtins;
with pkgs.lib;

let
  matches = regex: str: match regex str != null;

  allLinuxPackages = filterAttrs (name: pkg:
    matches "linuxPackages.*" name &&
    !matches "linuxPackagesFor|linuxPackages_custom|linuxPackages_testing_hardened" name
  ) pkgs;

  notBroken = lpkgs: filterAttrs (name: module: !(module.meta.broken or false)) lpkgs;
in
mapAttrs (name: pkg: notBroken pkg) allLinuxPackages
```

Then run with something like:

    nix-build -A linuxPackages_4_9 /tmp/helper.nix --option max-jobs `nproc --all` --keep-going --no-build-output --arg pkgs 'import ./. { }' |& grep -E '^building|^builder'

**Comment by jonringer** [comment]
@Atemu a lot of these modules are also packages, so you need to check if kernel is null

**Comment by jonringer** [comment]
zfs and dpdk has to check whether or not kernel was passed

**Pull request merged**
