### PR TITLE
Kgpg: Added gnupg1 as runtime dependency

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
Like partially described in Issue #25286, kgpg need gnupg. In particular gnupg1, because the default path in the settings of kgpg is searching for gpg and results in an error on startup. Gnupg1 installs gpg2 and creates a symlinc for gpg.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
`propagatedBuildInputs` is not the right tool for this job, it has to do with the build environment. Wrapping is a more common approach to making sure a given command is available at runtime.

**Comment by joachifm** [comment]
`propagatedUserEnvPkgs` might be more appropriate, but similarly to `propagatedBuildInputs` it depends on the consumer having knowledge of that mechanism (like `buildEnv`).

**Comment by thineye** [comment]
Thanks for the hint. I am learning a lot from this. 👍 
Now, I used the shell function wrapProgram to add the binary path of gnupg1 to kgpg.

**Comment by joachifm** [comment]
LGTM :)

**Comment by ttuegel** [comment]
As this is a Qt-based program, please use `makeQtWrapper` and `wrapQtProgram` instead.

(In fact, it should already be using those, but I probably forgot to wrap it when it was upgraded from Qt 4 to Qt 5.)

**Comment by thineye** [comment]
Thanks. I changed it.
makeWrapper --> makeQtWrapper
wrapProgram --> wrapQtProgram

**Pull request merged**
