### PR TITLE
[release-23.05] github-runner: 2.307.1 -> 2.309.0

### PR DESCRIPTION
**Pull request by newAM**
## Description of changes

Hash updates from 73babca767015d92e490d8d243abe51ab78db320 and 5ee9b315dcc6b510fde80c7896807e03023611c7 backported to 23.05.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Hi, thanks for contributing with the backport. Please use `git cherry-pick -x` to keep the information from which commits the backport comes from as per the contributing guide.

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#manually-backporting-changes

**Comment by arianvp** [comment]
We should really really auto-backport these!

NixOS 23.05  is currently failing with:

```
Runner version v2.307.1 is deprecated and cannot receive messages.
```

**Comment by newAM** [comment]
The first commit in the chain has breaking changes, which I assume is undesirable for release-23.05?  Not sure if it matters.

I will look into cherry picking this weekend when I have the time, if anyone else wants to do it before then feel free to open a PR and I'll close this one.

**Comment by newAM** [comment]
We can also use more maintainers interested in this package on stable, this one is late because I was away from my computer for a few weeks.

**Comment by arianvp** [comment]
The commits can't be cherry-picked as it introduces a breaking change switching to nodejs 16 to 20

**Review by arianvp — APPROVED** [review]

**Comment by arianvp** [comment]
I think we should merge this as is. Currently NixOS 23.05 doesn't work anymore and fails with:
```
Runner version v2.307.1 is deprecated and cannot receive messages.
```

**Pull request merged**
