### PR TITLE
linuxPackages.rtl8189fs: 2022-05-20 -> 2022-10-30

### PR DESCRIPTION
**Pull request by superherointj**
linuxPackages.rtl8189fs: 2022-05-20 -> 2022-10-30

* Fixes kernel 6.1

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 214224` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.rtl8189fs</li>
    <li>linuxKernel.packages.linux_lqx.rtl8189fs</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8189fs</li>
  </ul>
</details>
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.rtl8189fs</li>
    <li>linuxKernel.packages.linux_4_14_hardened.rtl8189fs</li>
    <li>linuxKernel.packages.linux_4_19.rtl8189fs</li>
    <li>linuxKernel.packages.linux_4_19_hardened.rtl8189fs</li>
    <li>linuxKernel.packages.linux_5_10_hardened.rtl8189fs</li>
    <li>linuxKernel.packages.linux_5_15.rtl8189fs</li>
    <li>linuxKernel.packages.linux_hardened.rtl8189fs (linuxKernel.packages.linux_5_15_hardened.rtl8189fs)</li>
    <li>linuxKernel.packages.linux_5_4.rtl8189fs</li>
    <li>linuxKernel.packages.linux_6_1.rtl8189fs</li>
    <li>linuxKernel.packages.linux_6_1_hardened.rtl8189fs</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8189fs</li>
    <li>linuxKernel.packages.linux_libre.rtl8189fs</li>
    <li>linuxKernel.packages.linux_xanmod.rtl8189fs</li>
    <li>linuxKernel.packages.linux_xanmod_latest.rtl8189fs (linuxKernel.packages.linux_xanmod_stable.rtl8189fs)</li>
    <li>linuxKernel.packages.linux_zen.rtl8189fs</li>
  </ul>
</details>

**Comment by superherointj** [comment]
@ofborg build linuxKernel.packages.linux_5_10.rtl8189fs

**Comment by superherointj** [comment]
@ofborg build linuxPackages_lqx.rtl8189fs

**Review by PedroHLC — APPROVED** [review]
diff looks good, passed ofborg.

**Pull request merged**
