### PR TITLE
pwsafe: extend to Darwin platform

### LINKED ISSUE #109957: nixpkgs.pwsafe fails to build (but possibly merely a dependency problem)
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls): when I search the pulls for `pwsafe`, I see [pull 73145](https://github.com/NixOS/nixpkgs/pull/73145).  It's not obvious to me why this is relevant, but see below

###### Project name
`nix search` name: nixpkgs.pwsafe

current version: 3.53.0
desired version:

###### Notify maintainers

maintainers: @c0bw3b @pjones 

This fails to build for me, crashing out on the build of `wxwidgets` (which is presumably where the link to pull 73145 comes from).  Given this is apparently a failure in a dependency, it may be that `pwsafe` will automatically start building again once this is resolved.  If that's so, then this report is redundant; in which case, apologies.  But I'll add it nonetheless in case the fix is not that automatic (I'm a bit vague about how fixes propagate around the wonderful wonderland of Nix).

    clang++ -mmacosx-version-min=10.7 -c -o htmldll_helpdata.o  -D__WXOSX_COCOA__      -DWXBUILDING      -I./src/regex  -DWXUSINGDLL -DWXMAKINGDLL_HTML -dynamic -fPIC -DPIC -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -Wno-deprecated-declarations -D_FILE_OFFSET_BITS=64 -I/private/tmp/nix-build-wxwidgets-3.0.4.drv-0/source/lib/wx/include/osx_cocoa-unicode-3.0 -I./include -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 -O2 -fno-strict-aliasing -fno-common -fvisibility=hidden -fvisibility-inlines-hidden ./src/html/helpdata.cpp
    ./src/osx/cocoa/mediactrl.mm:470:9: fatal error: 'AVFoundation/AVFoundation.h' file not found
    #import <AVFoundation/AVFoundation.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [Makefile:39594: mediadll_osx_cocoa_mediactrl.o] Error 1
    make: *** Waiting for unfinished jobs....
    builder for '/nix/store/wm81bmbkzk2ziyk5v3spdz4647n1v5vn-wxwidgets-3.0.4.drv' failed with exit code 2
    cannot build derivation '/nix/store/y5b7m6vlp8l5046sf7g41bz88w2dv9gn-pwsafe-3.53.0.drv': 1 dependencies couldn't be built
    error: build of '/nix/store/y5b7m6vlp8l5046sf7g41bz88w2dv9gn-pwsafe-3.53.0.drv' failed

This is with the unstable channel fully updated:

    $ nix-env -qa --drv-path --out-path pwsafe
    pwsafe-3.53.0  /nix/store/y5b7m6vlp8l5046sf7g41bz88w2dv9gn-pwsafe-3.53.0.drv  /nix/store/lvikq70mprd98ny90glpsh04llzs77nz-pwsafe-3.53.0

Platform: macOS 10.15.7 (Catalina).

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change
Fixes #109957

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by c0bw3b** [comment]
It's been a while since you opened the issue @nxg

But if you can retest building `pwsafe` on macOS with those changes that would be nice. :)

**Comment by nxg** [comment]
I don't _think_ this works, but I'm not at all sure I'm doing the right thing...

    % nix-channel --update
    unpacking channels...
    created 1 symlinks in user environment
    % nix-env -qa --drv-path --out-path pwsafe
    pwsafe-1.14.0  /nix/store/bwa32mb3db6ikdxya7z1f38xz7hbcyav-pwsafe-1.14.0.drv  /nix/store/ba1i9v1mnmf6s3qzpqdmb0agkvvymq7a-pwsafe-1.14.0
    % nix-shell -p pwsafe
    these derivations will be built:
      /nix/store/nd33a5kzpr3j6fxk22b95p7jnvyg2h18-wxwidgets-3.0.5.drv
      /nix/store/bwa32mb3db6ikdxya7z1f38xz7hbcyav-pwsafe-1.14.0.drv
    these paths will be fetched (5.14 MiB download, 32.73 MiB unpacked):
      /nix/store/2826q8vlldv59hcllxr75wjkbmbpjlli-libGL-1.4.0
      /nix/store/66yxgp673p3pz2mnh8rfwwgwg9831ac9-mesa-21.3.5-drivers
      /nix/store/6wrgi1cbazbr5cyc8hwac58pk9jm8hhh-mesa-21.3.5-dev
      /nix/store/b5zsafzr5nrgw7asr1xwhihc0hr5a8pf-qrencode-4.1.1-bin
      /nix/store/g4r29y89hx86rla7nnbr655n20vdj3fk-libGL-1.4.0-dev
      /nix/store/h9g1hl37cjf8if28icq8qfjqrcs2b4h9-glu-9.0.2-dev
      /nix/store/id5khcw2q9mhdirklciy0xhz4a8fvlhf-qrencode-4.1.1-dev
      /nix/store/jsmn3b3ifc9qdfwmwwygk5gl2138cxsz-mesa-21.3.5
      /nix/store/k4mb7b2vaxi9nzcdldmv0vns6d7i2rn7-glu-9.0.2
      /nix/store/l9s25vzy0ycv5gpwd9gp8pqqz4vvppqj-qrencode-4.1.1
      /nix/store/n2llvwal5wfwm3spdgiw05ld7wh717l1-gst-plugins-base-1.18.5-dev
      /nix/store/vvgykbdb6p6yj01lk1n3gdsqw40h2vj0-gst-plugins-base-1.18.5
    copying path '/nix/store/l9s25vzy0ycv5gpwd9gp8pqqz4vvppqj-qrencode-4.1.1' from 'https://cache.nixos.org'...
    copying path '/nix/store/vvgykbdb6p6yj01lk1n3gdsqw40h2vj0-gst-plugins-base-1.18.5' from 'https://cache.nixos.org'...
    [...]
    clang++ -mmacosx-version-min=10.7 -c -o htmldll_helpdlg.o  -D__WXOSX_COCOA__      -DWXBUILDING      -I./src/regex  -DWXUSINGDLL -DWXMAKINGDLL_HTML -dynamic -fPIC -DPIC -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -Wno-deprecated-declarations -D_FILE_OFFSET_BITS=64 -I/private/tmp/nix-build-wxwidgets-3.0.5.drv-0/source/lib/wx/include/osx_cocoa-unicode-3.0 -I./include -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 -O2 -fno-strict-aliasing -fno-common -fvisibility=hidden -fvisibility-inlines-hidden ./src/html/helpdlg.cpp
    ./src/osx/cocoa/mediactrl.mm:470:9: fatal error: 'AVFoundation/AVFoundation.h' file not found
    #import <AVFoundation/AVFoundation.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [Makefile:39581: mediadll_osx_cocoa_mediactrl.o] Error 1
    make: *** Waiting for unfinished jobs....
    builder for '/nix/store/nd33a5kzpr3j6fxk22b95p7jnvyg2h18-wxwidgets-3.0.5.drv' failed with exit code 2
    cannot build derivation '/nix/store/bwa32mb3db6ikdxya7z1f38xz7hbcyav-pwsafe-1.14.0.drv': 1 dependencies couldn't be built
    error: build of '/nix/store/bwa32mb3db6ikdxya7z1f38xz7hbcyav-pwsafe-1.14.0.drv' failed
    %

I'm rather confused that the version of the `pwsafe` derivation appears to have gone from 3.53 to 1.14.0.  Am I doing something terribly wrong? (I confess that my usage of Nix is largely voodoo, rather than the result of deep understanding!)

    % nix search -u nixpkgs.pwsafe 
    * nixpkgs.pwsafe (pwsafe-1.14.0)
      A password database utility

This is on `Darwin jellicle.home 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64` (ie, macOS 11.6).  Tomorrow I should be able to try also on 12.1 on M1.

**Comment by c0bw3b** [comment]
Yes the version "downgrade" is explained in #151601
3.x are the Windows versions ; but Unix builds with wxWidgets are 1.x versions.

**Comment by nxg** [comment]
Ah – thanks for the explanation.

I've also, as promised, had a chance to run on M1, and this fails (but it looks like you were expecting that).

    % nix-channel --update
    unpacking channels...
    created 1 symlinks in user environment
    % nix-shell -p pwsafe
    error: Package ‘pwsafe-1.14.0’ in /nix/store/dg2x0651qjjlynnfs2997ggd5f71lxgi-nixpkgs-22.05pre352151.18a062b02d6/nixpkgs/pkgs/applications/misc/pwsafe/default.nix:57 is not supported on ‘aarch64-darwin’, refusing to evaluate.

**Comment by c0bw3b** [comment]
Yes with `nix-shell -p` you're trying to install or build `pwsafe` from the current unstable channel.
But there is several point with the current package definition that makes it nok for Darwin:
* `wxGTK30` is not working on Darwin, `wxmac` must be used instead
* it needs Darwin-specific frameworks like Carbon, etc...

This PR is trying to address those 2 points.
Currently failing on ofBorg builders, it seems there is a problem with upstream CMake rules.

**Comment by nxg** [comment]
...and these changes aren't in the current unstable channel – right, I think I see.  Is there anything I can usefully test here?  As I say, I'm a pretty naive user of NixPkgs, so if I'm to test with something not in that channel, I'm afraid you'll have to walk me through the process.

**Pull request closed without merging**
