### PR TITLE
[22.05] treewide: mark more packages broken

### PR DESCRIPTION
**Pull request by Mindavi**
###### Description of changes

Mark some more packages broken. Now done with more care.

###### Things done

- [x] Manually checked on hydra if the build is broken in the latest release-22.05 eval: https://hydra.nixos.org/eval/1764429
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @dasJ

### CODE REVIEW

**Comment by dasJ** [comment]
Shouldn't we do this on master as well/instead?

**Comment by Mindavi** [comment]
I wanted to prevent this going out of sync with master, hence doing it like this. My plan was to address master separately, but I'm open to suggestions :smiley:.

**Comment by Mindavi** [comment]
Probably stale now and I think we/I should make something to do this more regularly on trunk instead of doing it like this.

**Comment by jonringer** [comment]
Agreed, we should probably do it as part of staging-next

**Pull request closed without merging**
