### PR TITLE
nixos/nvidia: fix /dev/nvidia* devices minors

### LINKED ISSUE #87788: nvidia.nix provides wrong udev when nvidia is card1
**Describe the bug**
On my system the nvidia card is `/dev/dri/card1`. However the udev rules create `/dev/nvidia1` and `/dev/nvidia1`. 

**To Reproduce**
1. Have system where nvidia is card1
2. Enable nvidia configuration.nix
3. Reboot system and try to use card (e.g. run nvidia-smi)

**Expected behavior**
`/dev/nvidia0` is created

**Screenshots**
```
$ nvidia-smi 
No devices were found
$ ls /dev/nvidia*
/dev/nvidia1  /dev/nvidiactl       /dev/nvidia-uvm
/dev/nvidia2  /dev/nvidia-modeset  /dev/nvidia-uvm-tools
```

**Additional context**

**Notify maintainers**
@baracoder @matthewbauer 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.03.1822.5adf2a6c116 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1822.5adf2a6c116"`
 - channels(mpiechotka): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```
```yaml
attribute: pkgs.linuxPackages.nvidia_x11
module: hardware.nvidia
```

### LINKED ISSUE #98942: [20.09][21.03] PRIME render offload doesn't work on latest builds
## Issue description
PRIME render offload stopped working on the latest update both on 20.09 channel and unstable channel, I've found that changing the bootloader and removing nvidia-drm.modeset=1 sometimes makes it work and sometimes don't, but maybe it's something else I changed.

xrandr --listproviders
```
Providers: number : 1
Provider 0: id: 0x46 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 4 associated providers: 0 name:modesetting
```

nvidia-offload glxinfo
```
name of display: :1
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  40
```

nvidia-smi
```
No devices were found
```

### Steps to reproduce
1.- Install 20.09 or 21.03
2.- Run nixos-rebuild boot --upgrade
3.- Reboot

## Technical details
configuration.nix
```
{ config, pkgs, ... }:

let
  nvidia-offload = pkgs.writeShellScriptBin "nvidia-offload" ''
    export __NV_PRIME_RENDER_OFFLOAD=1
    export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export __VK_LAYER_NV_optimus=NVIDIA_only
    exec -a "$0" "$@"
  '';
in
{
. . .
  # Xserver configuration
  services.xserver = {
    enable = true;

    # Xserver keyboard configuration
    layout = "es";
    xkbOptions = "eurosign:e";

    # Use libinput for trackpad support
    libinput.enable = true;

    # Wacom tablet support
    wacom.enable = true;

    # Use nvidia drivers
    videoDrivers = [ "nvidia" ];

    # Gnome3 desktop configuration
    displayManager = {
      gdm = {
        enable = true;
        wayland = false;
      };
    };
    desktopManager.gnome3.enable = true;
  };

  hardware.nvidia = {
    powerManagement.enable = true;
    prime = {
      offload.enable = true;
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };
```

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.10, NixOS, 21.03pre244416.daaa0e33505 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre244416.daaa0e33505"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by matshch**
##### Description of changes
This pull request fixes creation of `/dev/nvidia0` device node by querying device minor assigned in nvidia-frontend module instead of assuming that device minor is the same as for DRI card. Aforesaid assumption is sometimes broken on hosts with GPUs from different vendors e.g. laptops with Intel and NVidia GPUs.

This change fixes #87788, fixes #98942 for me.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LunNova** [comment]
Applied this patch on an AMD + nvidia laptop. Not seeing any difference in behavior, nvidia-smi was already working prior to applying the patch.

I don't have an intel + nvidia laptop to test with.

**Comment by LunNova** [comment]
I'm curious why we grep for the major instead of hardcoding 195, since that should never change. Introduced in #29697.

**Comment by LunNova** [comment]
Looks like the hardcoded minor for nvidia-uvm-tools is wrong too, should be 1.

**Comment by matshch** [comment]
> I'm curious why we grep for the major instead of hardcoding 195, since that should never change.

I guess this was copy-paste from grep for the major of `nvidia-uvm`, because it can in fact change (and `nvidia-modprobe` discovers it the same way). Will change `nvidia-frontend` to the constant.

**Review by LunNova — APPROVED** [review]

**Comment by Mindavi** [comment]
LGTM, but leaving open for a bit to let others test this if they want.

**Comment by matshch** [comment]
For completeness tests on my own system (Dell XPS 15 9570, Intel+NVidia):

Before (right after boot, without calling any NVidia user-space programs under root):
```
crw-rw-rw- 1 root root 195, 254 Apr 28 23:36 /dev/nvidia-modeset
crw-rw-rw- 1 root root 238,   0 Apr 28 23:36 /dev/nvidia-uvm
crw-rw-rw- 1 root root 238,   0 Apr 28 23:36 /dev/nvidia-uvm-tools
crw-rw-rw- 1 root root 195,   1 Apr 28 23:36 /dev/nvidia1
crw-rw-rw- 1 root root 195, 255 Apr 28 23:36 /dev/nvidiactl
```
PRIME GPU offloading is not working.

After:
```
crw-rw-rw- 1 root root 195, 254 Apr 28 23:40 /dev/nvidia-modeset
crw-rw-rw- 1 root root 238,   0 Apr 28 23:40 /dev/nvidia-uvm
crw-rw-rw- 1 root root 238,   1 Apr 28 23:40 /dev/nvidia-uvm-tools
crw-rw-rw- 1 root root 195,   0 Apr 28 23:40 /dev/nvidia0
crw-rw-rw- 1 root root 195, 255 Apr 28 23:40 /dev/nvidiactl
```
PRIME GPU offloading is working.

Also I've checked this udev rules onto system with three NVidia GPUs, they work fine.

**Comment by Ericson2314** [comment]
Any way we can safely backport this?

**Comment by matshch** [comment]
I'm not very comfortable backporting this to stable release, because it is, in fact, breaking change, that can activate NVidia GPU on someone's host. My guess is that backporting this in a non-breaking manner (via separate option) is too much of a hassle, especially considering release schedule for 22.05.

However, if someone from the NixOS members think that it will be appropriate to backport these changes (as is or with additional work to make them non-breaking), I'm down to help with this.

**Comment by Ericson2314** [comment]
Fair enough, I guess I should just try cherry-picking for now and then wait for next month.

**Comment by nrdxp** [comment]
could this have caused #165719?

**Comment by matshch** [comment]
Well, you can try to revert it and check. These udev rules works on my laptop (with displays connecting and disconnecting from it) and with my desktop (however I have only one monitor for it and will able to test connects and disconnects only on August).

**Comment by LunNova** [comment]
@nrdxp this pr was merged after that issue got raised 🤔

**Pull request merged**
