### PR TITLE
mangohud: 0.6.4 -> 0.6.5

### PR DESCRIPTION
**Pull request by Kranzes**
###### Motivation for this change
Simple version bump.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 129761` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mangohud</li>
  </ul>
</details>

**Review by zeratax — APPROVED** [review]
tested a few applications, works ^^

**Comment by kira-bruneau** [comment]
Thanks @Kranzes! `lsof` is [no longer required](https://github.com/flightlessmango/MangoHud/pull/556/commits/f1eae9325357af29af71f088ca95ded93c92adf7), but that can just be cleaned up in the next update.

**Comment by Kranzes** [comment]
I wouldn't have known that, I don't even use mangohud and couldn't find anything about lsof in the changelogs.

**Comment by kira-bruneau** [comment]
Yeah, it's no problem! Runtime dependencies can be tricky. It doesn't really hurt to leave it in here. I usually just do a diff between versions to try to catch these kind of changes.

**Pull request merged**
