### PR TITLE
SkypeExport: init at 1.4.0

### PR DESCRIPTION
**Pull request by lukateras**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This may be controversial due to the fact that I use the same case in the attribute name (and the directory name) as the author uses in the executable's name and the project's name.

### CODE REVIEW

**Comment by rycee** [comment]
Thanks for the contribution!

> This may be controversial due to the fact that I use the same case in the attribute name (and the directory name) as the author uses in the executable's name and the project's name.

I would suggest changing these names to "skype-export" instead which is closer to the [naming guidelines](https://nixos.org/nixpkgs/manual/#sec-package-naming).

**Comment by orivej** [comment]
> I would suggest changing these names to "skype-export" instead which is closer to the [naming guidelines](https://nixos.org/nixpkgs/manual/#sec-package-naming).

No, even according to the linked section the options are `SkypeExport` and `skypeexport`.

**Review by orivej — APPROVED** [review]

**Comment by orivej** [comment]
I'd prefer `skypeexport` for the attribute in all packages and `SkypeExport` for `name`, following the convention used for VirtualBox.

**Comment by rycee** [comment]
@orivej But "skypeexport" would clash with the [directory name](https://nixos.org/nixpkgs/manual/#sec-organisation):

> Names of files and directories should be in lowercase, with dashes between words — not in camel case. For instance, it should be `all-packages.nix`, not `allPackages.nix` or `AllPackages.nix`.

I've taken this to apply also to the package names and have attempted to clarify the naming in https://github.com/NixOS/nixpkgs/pull/31668.

**Pull request merged**
