### PR TITLE
openjfx{11,17,21,22}: pin to FFmpeg 6

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

Part of my campaign to get rid of FFmpeg 4. This is stacked on top of https://github.com/NixOS/nixpkgs/pull/331514, so please ignore all but [the last commit](https://github.com/NixOS/nixpkgs/pull/331522/commits/164f9eaf8cf5df1d0bec9c1821e857070f2f2dd4).

**This is completely untested.** The builds go through successfully on `x86_64-linux` and `aarch64-darwin`, and the upstream compatibility fixes are pretty trivial, but I suspect that OpenJFX might be doing runtime dynamic library loading stuff that could mask problems. There are two relevant upstream PRs here:

* https://github.com/openjdk/jfx/pull/932 (adds support for FFmpeg 5)
* https://github.com/openjdk/jfx/pull/1259 (adds support for FFmpeg 6)

These have both been merged; FFmpeg 5 support was backported to OpenJFX ≥ 11 and FFmpeg 6 support to OpenJFX ≥ 20. I have backported the trivial FFmpeg 6 to 11 and 17 myself, although I’m not sure if it was actually necessary since they built fine without it. (I *do* get build failures for all of these versions when trying to use FFmpeg 7, so they’re not completely agnostic to the package they’re being supplied, but then I’m unsure what those version lines are doing.)

I have no real idea how to go about testing these changes – what uses OpenJFX anyway, and what would exercise the FFmpeg‐related parts of it? – so suggestions and help with that would be very useful.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>microsoft-identity-broker</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>autopsy</li>
    <li>bisq-desktop</li>
    <li>bluej</li>
    <li>cryptomator</li>
    <li>ganttproject-bin</li>
    <li>greenfoot</li>
    <li>jabref</li>
    <li>javaPackages.openjfx11</li>
    <li>javaPackages.openjfx17</li>
    <li>javaPackages.openjfx21</li>
    <li>javaPackages.openjfx22</li>
    <li>maptool</li>
    <li>mcaselector</li>
    <li>mediathekview</li>
    <li>moneydance</li>
    <li>ns-usbloader</li>
    <li>olvid</li>
    <li>pattypan</li>
    <li>pdfsam-basic</li>
    <li>quark-goldleaf</li>
    <li>scenebuilder</li>
    <li>scenic-view</li>
    <li>sparrow</li>
    <li>sparrow-unwrapped</li>
  </ul>
</details>

Result of `nixpkgs-review` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>bluej</li>
    <li>ganttproject-bin</li>
    <li>greenfoot</li>
    <li>jabref</li>
    <li>javaPackages.openjfx17</li>
    <li>javaPackages.openjfx21</li>
    <li>javaPackages.openjfx22</li>
    <li>mcaselector</li>
    <li>mediathekview</li>
    <li>moneydance</li>
    <li>ns-usbloader</li>
    <li>olvid</li>
    <li>pattypan</li>
    <li>pdfsam-basic</li>
    <li>quark-goldleaf</li>
    <li>scenebuilder</li>
    <li>scenic-view</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
(I initially had a bunch of confused stuff in the original post because I didn’t realize how far back the FFmpeg 5 patch had been backported. Fixed now.)

**Comment by thiagokokada** [comment]
My suggestion is to just disable ffmpeg for older versions and see if someone complains about them. From my experience nobody cares too much about OpenJfx, but if there is someone that comes and complains we have two alternatives:
- Try to run the program in a newer version of OpenJfx
- Backport the patches

**Comment by emilazy** [comment]
It was really easy to backport the FFmpeg 6 patch to OpenJFX 11 and 17, given that upstream already did the hard work for the FFmpeg 5 one, so I just did that. I have no idea if it’s actually necessary or not, but it should put to rest any potential concerns. I might not be so merciful when the time comes to drop FFmpeg 6, though :)

I’m running the builds again now but this should be good to go after https://github.com/NixOS/nixpkgs/pull/331514 is merged. Though, of course, it would be good if someone could try to actually run some JavaFX thing and see how it goes.

**Comment by emilazy** [comment]
The builds went fine.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
