### PR TITLE
python: updates and fixes

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
Fix some broken Python packages from https://hydra.nixos.org/eval/1434362#tabs-still-fail

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc bibtexparser maintainer @FRidh 
/cc curtsies maintainer @flokli 
/cc dbf maintainer @vrthra 
/cc prov maintainer @ashgillman

### CODE REVIEW

**Comment by ashgillman** [comment]
Thanks. Prov changes look good to me.

Looking through that list, a number of packages I work with have failed due to scipy taking too long.

**Comment by dotlambda** [comment]
One of the commtis actually replaces python-termstyle by termstyle, which is a good thing in my opinion.
However, I still have to fix green, which depends on python-termstyle.

**Comment by dotlambda** [comment]
Didn't you fix natsort somewhere?

**Comment by dotlambda** [comment]
I think I'm done here for now. Can you start another evaluation?

**Comment by dotlambda** [comment]
@rybern I had to mark pomegranate as broken. See https://github.com/jmschrei/pomegranate/issues/209.

**Comment by FRidh** [comment]
Another job at https://hydra.nixos.org/eval/1435157.

**Comment by dotlambda** [comment]
@rycee Just a ping because I fixed pytrainer.

@FRidh Most of the new failures are due to #35301. I think we should merge this one and I'll open a new PR as soon as I have accumulated some fixes again.

**Comment by dotlambda** [comment]
@garbas @domenkozar Is it okay that I removed mysql_connector_repackaged? It is currently broken and grepping through Nixpkgs didn't yield any dependents. You can use mysql-connector instead.

**Comment by garbas** [comment]
@dotlambda ok by me.

**Pull request merged**
