### PR TITLE
libvirt: 6.8.0 -> 7.0.0

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Update libvirt to version `7.0.0`. Removed unknow mesonFlags.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110874` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>collectd</li>
<li>collectd-data</li>
<li>python37Packages.guestfs</li>
<li>python38Packages.guestfs</li>
<li>python39Packages.guestfs</li>
<li>terraform-full</li>
<li>virt-manager-qt</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>perl530Packages.SysVirt: log <a href="https://termbin.com/ecc1">https://termbin.com/ecc1</a></li>
<li>perl532Packages.SysVirt: log <a href="https://termbin.com/aqoy">https://termbin.com/aqoy</a></li>
  </ul>
</details>
<details>
<summary>
6 packages built:
</summary>
<ul>
<li>docker-machine-kvm</li>
<li>haskellPackages.libvirt-hs</li>
<li>libvirt</li>
<li>python37Packages.libvirt</li>
<li>python38Packages.libvirt</li>
<li>python39Packages.libvirt</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110874` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>libvmi: log was empty</li>
  </ul>
</details>
<details>
<summary>
30 packages built:
</summary>
<ul>
<li>collectd</li>
<li>collectd-data</li>
<li>docker-machine-kvm</li>
<li>docker-machine-kvm2</li>
<li>gnome3.gnome-boxes</li>
<li>haskellPackages.libvirt-hs</li>
<li>libguestfs</li>
<li>libvirt</li>
<li>libvirt-glib</li>
<li>minikube</li>
<li>minishift</li>
<li>perl530Packages.SysVirt</li>
<li>perl532Packages.SysVirt</li>
<li>python37Packages.guestfs</li>
<li>python37Packages.libvirt</li>
<li>python38Packages.guestfs</li>
<li>python38Packages.libvirt</li>
<li>python39Packages.guestfs</li>
<li>python39Packages.libvirt</li>
<li>rubyPackages.ruby-libvirt (rubyPackages_2_6.ruby-libvirt)</li>
<li>rubyPackages_2_5.ruby-libvirt</li>
<li>rubyPackages_2_7.ruby-libvirt</li>
<li>terraform-full</li>
<li>terraform-providers.libvirt</li>
<li>vagrant</li>
<li>virt-manager</li>
<li>virt-manager-qt</li>
<li>virt-top</li>
<li>virt-viewer</li>
<li>virtlyst</li>
</ul>
</details>

**Comment by teto** [comment]
happy to see nixpkgs' libvirt catcing up after remaining stalled for so long

Nixpkgs-review
```
Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/110874

1 package failed to build:
libvmi

30 packages built:
collectd collectd-data docker-machine-kvm docker-machine-kvm2 gnome3.gnome-boxes haskellPackages.libvirt-hs libguestfs libvirt libvirt-glib minikube minishift perl530Packages.SysVirt perl532Packages.SysVirt python37Packages.guestfs python37Packages.libvirt python38Packages.guestfs python38Packages.libvirt python39Packages.guestfs python39Packages.libvirt rubyPackages.ruby-libvirt rubyPackages_2_5.ruby-libvirt rubyPackages_2_7.ruby-libvirt terraform-full terraform-providers.libvirt vagrant virt-manager virt-manager-qt virt-top virt-viewer virtlyst
```
but libvmi already fails on nixos-unstable (due to xen failing ?). I haven't tried to start the service but it looks ok

**Review by teto — APPROVED** [review]

**Comment by jonringer** [comment]
@GrahamcOfBorg test docker

**Review by jonringer — APPROVED** [review]
LGTM
```
https://github.com/NixOS/nixpkgs/pull/110874

1 package failed to build:
libvmi

30 packages built:
collectd collectd-data docker-machine-kvm docker-machine-kvm2 gnome3.gnome-boxes haskellPackages.libvirt-hs libguestfs libvirt libvirt-glib minikube minishift perl530Packages.SysVirt perl532Packages.SysVirt python37Packages.guestfs python37Packages.libvirt python38Packages.guestfs python38Packages.libvirt python39Packages.guestfs python39Packages.libvirt rubyPackages.ruby-libvirt rubyPackages_2_5.ruby-libvirt rubyPackages_2_7.ruby-libvirt terraform-full terraform-providers.libvirt vagrant virt-manager virt-manager-qt virt-top virt-viewer virtlyst
```

**Pull request merged**
