### PR TITLE
llvmPackages_git.llvm: run the tests on macOS

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

Port of c7231c0b6d8 ("llvmPackages_15.llvm: run the tests on macOS").

The sysctl native check input was taken from
6d0c87602fe ("llvmPackages_15.llvm: add in a missing check dep"), because it looks like it was supposed to be part of c7231c0b6d8 instead.

New PR for #220759, which I rebased badly.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Comment by alyssais** [comment]
@OfBorg build llvmPackages_git.llvm

**Comment by adamcstephens** [comment]
This failed for me on aarch64-darwin

<details>
<summary>FAIL: LLVM :: MC/ELF/cfi-version.ll (27957 of 44194)</summary>
-- Testing: 44194 tests, 8 workers --
FAIL: LLVM :: MC/ELF/cfi-version.ll (27957 of 44194)
******************** TEST 'LLVM :: MC/ELF/cfi-version.ll' FAILED ********************
Script:
--
: 'RUN: at line 1';   /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/llc /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll -o - -dwarf-version 2 -filetype=obj | /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/llvm-dwarfdump -v - | /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/FileCheck /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll --check-prefix=DWARF2
: 'RUN: at line 2';   /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/llc /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll -o - -dwarf-version 3 -filetype=obj | /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/llvm-dwarfdump -v - | /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/FileCheck /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll --check-prefix=DWARF3
: 'RUN: at line 3';   /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/llc /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll -o - -dwarf-version 4 -filetype=obj | /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/llvm-dwarfdump -v - | /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/FileCheck /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll --check-prefix=DWARF4
: 'RUN: at line 4';   /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/llc /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll -o - -dwarf-version 5 -filetype=obj | /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/llvm-dwarfdump -v - | /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/bin/FileCheck /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll --check-prefix=DWARF4
--
Exit Code: 1

Command Output (stderr):
--
/private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll:43:11: error: DWARF2: expected string not found in input
; DWARF2: .debug_frame contents:
          ^
<stdin>:1:1: note: scanning from here
-: file format Mach-O arm64
^
<stdin>:61:1: note: possible intended match here
.debug_line contents:
^

Input file: <stdin>
Check file: /private/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/test/MC/ELF/cfi-version.ll

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            1: -: file format Mach-O arm64 
check:43'0     X~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
            2:  
check:43'0     ~
            3: .debug_abbrev contents: 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~~~~
            4: Abbrev table for offset: 0x00000000 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            5: [1] DW_TAG_compile_unit DW_CHILDREN_yes 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            6:  DW_AT_producer DW_FORM_strp 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            .
            .
            .
           56:  DW_AT_encoding [DW_FORM_data1] (DW_ATE_signed) 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           57:  DW_AT_byte_size [DW_FORM_data1] (0x04) 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           58:  
check:43'0     ~
           59: 0x00000054: NULL 
check:43'0     ~~~~~~~~~~~~~~~~~
           60:  
check:43'0     ~
           61: .debug_line contents: 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~~
check:43'1     ?                      possible intended match
           62: debug_line[0x00000000] 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~~~
           63: Line table prologue: 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~
           64:  total_length: 0x00000036 
check:43'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~
           65:  format: DWARF32 
check:43'0     ~~~~~~~~~~~~~~~~~
           66:  version: 2 
check:43'0     ~~~~~~~~~~~~
            .
            .
            .
>>>>>>

--

********************
********************
Failed Tests (1):
  LLVM :: MC/ELF/cfi-version.ll


Testing Time: 877.59s
  Skipped          :     7
  Unsupported      :  1972
  Passed           : 48229
  Expectedly Failed:   176
  Failed           :     1
FAILED: CMakeFiles/check-all /tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/CMakeFiles/check-all 
cd /tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build && /nix/store/gl9hiqy6x9prqxs7iv6xg43bk1h9kl6c-python3-3.10.10-env/bin/python3.10 /tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/./bin/llvm-lit -svj8 --no-progress-bar --param polly_site_config=/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/tools/polly/test/lit.site.cfg --param polly_unit_site_config=/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/tools/polly/test/Unit/lit.site.cfg --param polly_site_config=/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/tools/polly/test/Unit/lit.site.cfg --param polly_site_config=/tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/tools/polly/test/UnitIsl/lit.site.cfg /tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/tools/polly/test /tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/tools/polly/test/Unit /tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/tools/polly/test/UnitIsl /tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/utils/lit /tmp/nix-build-llvm-unstable-2022-26-07.drv-0/llvm-src-unstable-2022-26-07/llvm/build/test
ninja: build stopped: subcommand failed.
</details>

**Comment by alyssais** [comment]
> it seems like a upstream bug to not skip the test on this platform.

Do you know why it might work on LLVM 15, where we already run the tests?  Maybe there's some upstream change, or maybe we're doing something different in the remaining delta?

**Comment by RaitoBezarius** [comment]
Reading https://reviews.llvm.org/D67216 seems to indicate that `.debug_frame` should always be present on ARM toolchain.
(Potentially relevant: https://reviews.llvm.org/D87011).

I will investigate more tomorrow.

**Comment by RaitoBezarius** [comment]
Switching to llvm15 revision, I have those two errors:

```
LLVM :: MC/ELF/cfi-version.ll
LLVM-Unit :: Support/./SupportTests/HostTest/getMacOSHostVersion
```

Therefore, there's still a diff indeed missing.

**Comment by rrbutani** [comment]
@RaitoBezarius I just skipped that test on Darwin in #194634: https://github.com/NixOS/nixpkgs/pull/194634/commits/0ee52512f0fd4f5b675ba9f742a300b50adf27d3 (this commit also has a fix for the `HostTest/getMacOSHostVersion` failure you're seeing).

Upstream has indeed correctly gated this test in LLVM16+: https://github.com/llvm/llvm-project/commit/3716851a84f2b4aac8afa08b2003b19cab166100.

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius I just skipped that test on Darwin in #194634: [0ee5251](https://github.com/NixOS/nixpkgs/commit/0ee52512f0fd4f5b675ba9f742a300b50adf27d3) (this commit also has a fix for the `HostTest/getMacOSHostVersion` failure you're seeing).
> 
> Upstream has indeed correctly gated this test in LLVM16+: [llvm/llvm-project@3716851](https://github.com/llvm/llvm-project/commit/3716851a84f2b4aac8afa08b2003b19cab166100).

Thanks for the details. We only need to do the same then, @alyssais.

**Comment by rrbutani** [comment]
Haven't tested locally (ofborg timed out) yet but I expect we'll also need parts of eafb8fbd3215f0fe6b1d4a0360a9c4f761677179 to get the tests to pass on `x86_64-darwin`.

---

Has anyone looked into the [`aarch64-linux` failure](https://logs.nix.ci/?key=nixos/nixpkgs.222220&attempt_id=74c86bde-9bac-46ee-9d82-04ed77788ee6) already?

**Comment by RaitoBezarius** [comment]
> Haven't tested locally (ofborg timed out) yet but I expect we'll also need parts of [eafb8fb](https://github.com/NixOS/nixpkgs/commit/eafb8fbd3215f0fe6b1d4a0360a9c4f761677179) to get the tests to pass on `x86_64-darwin`.

Got it.

> 
> Has anyone looked into the [`aarch64-linux` failure](https://logs.nix.ci/?key=nixos/nixpkgs.222220&attempt_id=74c86bde-9bac-46ee-9d82-04ed77788ee6) already?

Not yet.

**Comment by RaitoBezarius** [comment]
Tests are now fixed for aarch64-darwin, let's see what Ofborg has to say.

**Comment by adamcstephens** [comment]
This builds successfully for me now on aarch64-darwin.

**Comment by RaitoBezarius** [comment]
@ofborg build llvmPackages_git.llvm

**Comment by rrbutani** [comment]
@RaitoBezarius did you mean to squash the commits you pushed? (If so, I think it's still worth noting in the commit message that this includes fixes from 00839fea22bfa118b3897519d3a3be0f447dbeb1 and 0ee52512f0fd4f5b675ba9f742a300b50adf27d3)

Also the `aarch64-linux` FileCheck fail ofborg was seeing (our motivation for bumping `llvmPackages_git` to 15 before continuing to work on it) seems to have disappeared; pretty spooky 👀.

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius did you mean to squash the commits you pushed? (If so, I think it's still worth noting in the commit message that this includes fixes from [00839fe](https://github.com/NixOS/nixpkgs/commit/00839fea22bfa118b3897519d3a3be0f447dbeb1), [0ee5251](https://github.com/NixOS/nixpkgs/commit/0ee52512f0fd4f5b675ba9f742a300b50adf27d3), and [abba4c3](https://github.com/NixOS/nixpkgs/commit/abba4c313bcf515aceac1c9d96c61bd78b70f090))

I have left them as-is so we can decide at the end what do we want to squash. :)
But please don't hesitate to rewrite the history accordingly.

> Also the `aarch64-linux` FileCheck fail ofborg was seeing (our motivation for bumping `llvmPackages_git` to 15 before continuing to work on it) seems to have disappeared; pretty spooky eyes.

Heh. :)

**Comment by RaitoBezarius** [comment]
@ofborg build llvmPackages_git.llvm

**Review by RaitoBezarius — APPROVED** [review]
Good to go AFAIK. ofborg failures are timeouts, tested separately by contributors in this discussion.

**Comment by RaitoBezarius** [comment]
The PR is ready @alyssais @rrbutani ; formatted with the two original commits of LLVM15.

**Comment by alyssais** [comment]
Let's reference the original commit in the commit message, like I did?

**Comment by RaitoBezarius** [comment]
> Let's reference the original commit in the commit message, like I did?

Done, will do the same for the other PRs. Apologies for the formatting back'n'forth. :)

**Comment by alyssais** [comment]
Looks fine to me now.

**Comment by RaitoBezarius** [comment]
With this: tests on (aarch64|x86_64)-darwin are passing. Retargeting master.

**Review by rrbutani — APPROVED** [review]

**Pull request merged**
