### PR TITLE
openrussian-cli: fix build & misc cleanups

### PR DESCRIPTION
**Pull request by vs49688**
## Description of changes

* Backport patch to fix DB generation after SQLite's removal of "" handling
* Format
* Convert to `pkgs/by-name`
* ~Mark broken on Darwin because the mysql2sqlite script hangs.~
    - Fixed, we hit https://github.com/dumblob/mysql2sqlite/issues/75

ZHF: #265948

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vs49688** [comment]
@ofborg build openrussian-cli

**Review by onemoresuza — CHANGES_REQUESTED** [review]
# Reviewed points

Result of `nixpkgs-review pr 263916` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>openrussian-cli</li>
  </ul>
</details>

- [X] package name fits guidelines
- [ ] package version fits guidelines
- [X] package build on x86_64-linux
- [X] executables tested on x86_64-linux
- [X] all depending packages build

# Possible Improvements

1. Package version
	As of [4e4bbb01][4e4bbb01], there's a new [naming convention for
packages][convention]:
	> If a package is a commit from a repository without a version assigned,
	> then the `version` attribute should be the latest upstream version preceding
	> that commit, followed by -`unstable`- and the date of the (fetched) commit.
	> The date must be in "`YYYY-MM-DD`" format.

[4e4bbb01]: <https://github.com/NixOS/nixpkgs/blame/4e4bbb01ebfa4a1ce322f036007ec4d653071523/pkgs/README.md#L313>
[convention]: <https://github.com/NixOS/nixpkgs/blob/4e4bbb01ebfa4a1ce322f036007ec4d653071523/pkgs/README.md#package-naming>

**Comment by vs49688** [comment]
>     1. Package version
>        As of [4e4bbb01](https://github.com/NixOS/nixpkgs/blame/4e4bbb01ebfa4a1ce322f036007ec4d653071523/pkgs/README.md#L313), there's a new [naming convention for
>        packages](https://github.com/NixOS/nixpkgs/blob/4e4bbb01ebfa4a1ce322f036007ec4d653071523/pkgs/README.md#package-naming):
>        > If a package is a commit from a repository without a version assigned,
>        > then the `version` attribute should be the latest upstream version preceding
>        > that commit, followed by -`unstable`- and the date of the (fetched) commit.
>        > The date must be in "`YYYY-MM-DD`" format.

Huh, I was not aware of this change. Fixed.

**Review by onemoresuza — APPROVED** [review]

**Comment by pbsds** [comment]
@ofborg build openrussian-cli, openrussian-cli.passthru.tests

**Comment by vs49688** [comment]
Ping on this?

**Comment by vs49688** [comment]
Result of `nixpkgs-review pr 263916` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>openrussian-cli</li>
  </ul>
</details>

**Comment by pbsds** [comment]
Seems like the darwin builds keep timing out. Could you mark it broken on darwin?

**Comment by pbsds** [comment]
Instead of bumping to an unstable version, could you apply https://github.com/rhaberkorn/openrussian-cli/commit/984e555acbadbd1aed7df17ab53e2c586a2f8f68 as a patch? This is the only effective change in the revision change anyway.

**Comment by vs49688** [comment]
> Instead of bumping to an unstable version, could you apply [rhaberkorn/openrussian-cli@984e555](https://github.com/rhaberkorn/openrussian-cli/commit/984e555acbadbd1aed7df17ab53e2c586a2f8f68) as a patch? This is the only non-readme change anyway.

Alrighty, I'll do tha

> Instead of bumping to an unstable version, could you apply [rhaberkorn/openrussian-cli@984e555](https://github.com/rhaberkorn/openrussian-cli/commit/984e555acbadbd1aed7df17ab53e2c586a2f8f68) as a patch? This is the only non-readme change anyway.


Done, and I applied a few other changes too - ran it through `nixpkgs-fmt` and converted to `pkgs/by-name`.

I'm just debugging the Darwin issue now, if I can't solve it, I'll mark it as broken.

**Comment by vs49688** [comment]
This is odd, it builds successfully on my M1 when run manually in a `nix develop` shell.
When run via `nix build`, it hangs on in the `mysql2sqlite` script. Trace output:
```
+ Op_push_re
+ Op_push_i
+ Op_push_i
+ Op_field_spec_lhs
+ Op_sub_builtin
+ Op_field_assign
+ Op_pop
+ Op_push_re
+ Op_push_i
+ Op_push_i
+ Op_field_spec_lhs
+ Op_sub_builtin
```

I say hang in a loose sense - it eventually progresses to another `Op_sub_builtin`, and I'd image it'd finish eventually.

**Comment by vs49688** [comment]
Marked broken on Darwin for now.

**Comment by vs49688** [comment]
@orborg build openrussian-cli

**Comment by vs49688** [comment]
@ofborg build openrussian-cli

**Comment by vs49688** [comment]
Darwin support fixed:

Result of `nixpkgs-review pr 263916` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>openrussian-cli</li>
  </ul>
</details>

**Pull request merged**
