### PR TITLE
unpoller: 2.3.1 -> 2.4.1

### PR DESCRIPTION
**Pull request by Frostman**
###### Description of changes

https://github.com/unpoller/unpoller/releases/tag/v2.4.0
https://github.com/unpoller/unpoller/releases/tag/v2.4.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Frostman** [comment]
Result of `nixpkgs-review pr 205246` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>unifi-poller</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>unpoller</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
The passthru tests fail due to DNS. lets retry that.

@ofborg test unpoller

**Comment by Frostman** [comment]
Strange, it timed out on adding default route (or after that?)

```
unpoller # [    9.177283] systemd[1]: Reached target Multi-User System.
unpoller # [    9.178628] systemd[1]: Startup finished in 2.582s (kernel) + 6.596s (userspace) = 9.178s.
unpoller # [    9.216624] dhcpcd[677]: eth0: Router Advertisement from fe80::2
unpoller # [    9.217400] dhcpcd[677]: eth0: adding address fec0::5054:ff:fe12:3456/64
unpoller # [    9.218863] dhcpcd[677]: eth0: adding route to fec0::/64
unpoller # [    9.219498] dhcpcd[677]: eth0: adding default route via fe80::2
unpoller # [  907.303128] systemd[1]: Starting Cleanup of Temporary Directories...
unpoller # [  907.328777] systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
unpoller # [  907.329650] systemd[1]: Finished Cleanup of Temporary Directories.
unpoller # [  907.331186] systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dclean.service.mount: Deactivated successfully.
```

**Comment by Frostman** [comment]
Yeah, seems like behavior changed a bit in a new version, and it's not listening on the port if no controllers were available. I'll dig deeper and fix the test.

**Pull request merged**
