### PR TITLE
php: 7.2.28 -> 7.2.29, 7.3.15 -> 7.3.16, 7.4.3 -> 7.4.4

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
Normal package version updates.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by etu** [comment]
@GrahamcOfBorg build php72 php73 php74 nixosTests.php nixosTests.nextcloud

**Review by Ma27 — APPROVED** [review]
Builds fine locally and seems fine :+1:

**Comment by Ma27** [comment]
Currently preparing the backport :)

**Comment by etu** [comment]
> Currently preparing the backport :)

I hope it doesn't conflict too badly, because if it does it will continue doing so for the next 6 months :D

**Comment by Ma27** [comment]
Backported as 865abba6e98f378ff8af02821e07cedb4fb05a53, 185b6844256e143e472a97baa62683c98be4a927, 84926c9480c818f3628d9b47719df7f2d5d25d65

> I hope it doesn't conflict too badly, because if it does it will continue doing so for the next 6 months :D

Wasn't too bad IMHO :)

**Comment by etu** [comment]
But they probably didn't cleanly apply, so probably needed some touches... :)

**Pull request merged**
