### PR TITLE
tree-sitter-markdown: replace ikatyang parser with MDeiml parser, tree-sitter-*: update all 

### PR DESCRIPTION
**Pull request by jlesquembre**
###### Motivation for this change
Replace
https://github.com/ikatyang/tree-sitter-markdown
with
https://github.com/MDeiml/tree-sitter-markdown

With neovim, the current markdown parser crashes sometimes.
nvim-treesitter project uses MDeiml parser to avoid those crashes,
take a look to
https://github.com/nvim-treesitter/nvim-treesitter/pull/2105 and
https://github.com/nvim-treesitter/nvim-treesitter/issues/872 to see why
the picked one over the other.

I also updated all the grammars to the latest version

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ck3d — APPROVED** [review]
I can confirm, the current markdown parser is really buggy. As example, opening an empty markdown file raises an error.

**Comment by KyleOndy** [comment]
I too am having a buggy experience, I am running this this patch today to see if things improve.

https://github.com/KyleOndy/dotfiles/commit/265b68eb517238f8c1c8a7d30eeca7b516f16507

**Comment by gravndal** [comment]
@jlesquembre could you rebase and update the newly added org grammar? It's currently somewhat broken: https://github.com/nvim-orgmode/orgmode/issues/207#issuecomment-1019189754

**Comment by jlesquembre** [comment]
@gravndal done, can you confirm that the generated org grammar is the expected one?

**Comment by gravndal** [comment]
Looks good :+1:

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 154767` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>difftastic: <a href="https://termbin.com/0a7y">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/0824f192ccb063873ac5f87ab9d42422/raw/index.html">pretty log </a></li>
  </ul>
</details>
<details>
<summary>
29 packages built:
</summary>
<ul>
<li>tree-sitter-grammars.tree-sitter-c-sharp</li>
<li>tree-sitter-grammars.tree-sitter-cpp</li>
<li>tree-sitter-grammars.tree-sitter-cuda</li>
<li>tree-sitter-grammars.tree-sitter-elixir</li>
<li>tree-sitter-grammars.tree-sitter-elm</li>
<li>tree-sitter-grammars.tree-sitter-embedded-template</li>
<li>tree-sitter-grammars.tree-sitter-go</li>
<li>tree-sitter-grammars.tree-sitter-haskell</li>
<li>tree-sitter-grammars.tree-sitter-heex</li>
<li>tree-sitter-grammars.tree-sitter-java</li>
<li>tree-sitter-grammars.tree-sitter-latex</li>
<li>tree-sitter-grammars.tree-sitter-llvm</li>
<li>tree-sitter-grammars.tree-sitter-markdown</li>
<li>tree-sitter-grammars.tree-sitter-norg</li>
<li>tree-sitter-grammars.tree-sitter-org</li>
<li>tree-sitter-grammars.tree-sitter-perl</li>
<li>tree-sitter-grammars.tree-sitter-query</li>
<li>tree-sitter-grammars.tree-sitter-r</li>
<li>tree-sitter-grammars.tree-sitter-regex</li>
<li>tree-sitter-grammars.tree-sitter-rst</li>
<li>tree-sitter-grammars.tree-sitter-ruby</li>
<li>tree-sitter-grammars.tree-sitter-rust</li>
<li>tree-sitter-grammars.tree-sitter-supercollider</li>
<li>tree-sitter-grammars.tree-sitter-swift</li>
<li>tree-sitter-grammars.tree-sitter-tlaplus</li>
<li>tree-sitter-grammars.tree-sitter-tsx</li>
<li>tree-sitter-grammars.tree-sitter-typescript</li>
<li>tree-sitter-grammars.tree-sitter-vim</li>
<li>tree-sitter-grammars.tree-sitter-zig</li>
</ul>
</details>

**Comment by jlesquembre** [comment]
@SuperSandro2000 I reverted the haskell grammar update

**Comment by SuperSandro2000** [comment]
@jlesquembre please rebase

**Comment by jlesquembre** [comment]
@SuperSandro2000 done, after the rebase only the markdown grammar is updated

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 154767` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>difftastic: <a href="https://termbin.com/fylm">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/ba53e406248dc51e9dffa27c5d1c1ad4/raw/index.html">pretty log </a></li>
  </ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>tree-sitter-grammars.tree-sitter-markdown</li>
</ul>
</details>

**Pull request merged**
