### PR TITLE
nixos/mailman: wrap mailman cli to start as mailman user

### PR DESCRIPTION
**Pull request by SuperSandro2000**
This is essential when postgres socket authentication is used.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by MarcelCoding — APPROVED** [review]

**Comment by alyssais** [comment]
I'm not sure about this — it's different to upstream works, and I'm not sure NixOS should make changes like that.  Also, sudo is not necessarily available.

**Comment by SuperSandro2000** [comment]
We do the same already in some other modules like mastodon, nextcloud, bookstack, healthchecks, pretalx, etc. because those cli also need to run under the user of the application or things don't work as expected. https://github.com/search?q=repo%3ANixOS%2Fnixpkgs+%2Frun%2Fwrappers%2Fbin%2Fsudo++path%3A%2F%5Enixos%5C%2Fmodules%5C%2F%2F&type=code

> it's different to upstream works

Not really, we make things work with the module, so that people can just use it and don't get terminal pages full of trace just because mailman can't connect to the postgres.

> Also, sudo is not necessarily available.

If you are using anything else, just call mailman already as the mailman user and nothing happens.

**Comment by alyssais** [comment]
> Not really, we make things work with the module, so that people can just use it and don't get terminal pages full of trace just because mailman can't connect to the postgres.

Feels like a more correct fix would be to fix mailman to not do that, and instead explain that it's running as the wrong user…

> If you are using anything else, just call mailman already as the mailman user and nothing happens.

Maybe we could disable the wrapper if sudo is not enabled?  If we do this widely, we should have a more generic mechanism for this that takes into account doas, etc…

**Comment by SuperSandro2000** [comment]
> Feels like a more correct fix would be to fix mailman to not do that, and instead explain that it's running as the wrong user…

I don't know. Probably but I didn't plan to interact with upstream about this 😅 

> Maybe we could disable the wrapper if sudo is not enabled? If we do this widely, we should have a more generic mechanism for this that takes into account doas, etc…

Done

**Comment by SuperSandro2000** [comment]
@alyssais can we merge this?

**Pull request merged**
