### PR TITLE
treewide: update cargoSha256 hashes for cargo-vendor upgrade

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

A recent upgrade of cargo-vendor changed its output slightly, which broke all `cargoSha256` hashes in nixpkgs. See #60668 for more information.

Since then, a few hashes have been fixed in master by hand, but there were a lot still to do, so I did all of the ones left over with some scripts I wrote. Once this is merged, I can run the same scripts on the release branch that the cargo-vendor upgrade has made it into.

I’ve tested that this doesn’t break any builds on *master*. The actual target of the PR is staging, though, because of the number of rebuilds. The one hash I wasn’t able to update was `habitat`’s, because it’s currently broken and the build doesn’t get far enough to produce a hash anyway.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by alyssais** [comment]
OfBorg will fail here, because some of the packages whose dependencies I’ve fixed are broken for other reasons. Not a reason to avoid merging.

**Comment by lilyball** [comment]
Looks like it's purely just `cargoSha256` updates, so that seems simple enough. I wanted to spot-check at least one of them but trying to build it from your branch needs to rebuild a _ton_ of dependencies which I don't have time for, oh well.

**Comment by Infinisil** [comment]
I don't think staging is needed though. This is just ~100 rebuilds of modules without any reverse dependencies, which shouldn't be a problem on master. As far as I understand, staging is mostly useful to group together mass updates like stdenv or other packages deep down the dependency tree.

**Comment by alyssais** [comment]
> I don't think staging is needed though.

Agreed. I expected the rebuild count to be higher.

**Comment by alyssais** [comment]
Merged to master as 062210bdff8cd2ea3508bc0d7f3341eee913a261.

**Pull request closed without merging**
