### PR TITLE
clutter*, cogl: remove unused versions

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

This switches to the new versions as default and removes the (now) unused old versions to clean up the clutter (how fitting :laughing:)
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

 #18952 should have helped avoiding this....
If you look at the changes, you'll see that I inherit from and to `all-packages` and `gnome3` in both directions which would be avoided by reorganizing..

I'll look into cleaning the remaining stuff (clutter, cogl, eventually vala) when I find time.

Note that I did not really change the `default.nix` files but rather did overwrite it with the newest version 

CC @lethalman

### CODE REVIEW

**Comment by lethalman** [comment]
What did you test about this? Did you test gnome works?

**Comment by groxxda** [comment]
I tested the compilation with nox-review. Everything it picks up (including webkitgtk212) compiles fine. 

I'll cherry-pick my changeset on top of latest complete hydra build ([b3d7ea](http://hydra.nixos.org/eval/1294162)), rebuild my desktop and check if it still works. I'm not using all of gnome but to me it looks like the list of gnome packages affected by this change is not that big.
I'll report back after dinner

**Comment by lethalman** [comment]
It's not always enough to build. Some apps or gnome itself is javascript, so you may see troubles only at runtime. Let me know if you are able to actually test your desktop.

**Comment by groxxda** [comment]
@lethalman from the travis log:
```
Building in /run/user/1000/nox-review-yi1l_364: gnome3.gnome-contacts clutter-gst gnome3.gnome-maps libmx gnome3.libchamplain finalterm clutter_gtk libchamplain gthumb pinpoint
these derivations will be built:
  /nix/store/0yqn6fs63c8c0nkc9x7wvg0ffdmhly4j-webkitgtk-2.12.4.drv
  /nix/store/fz5g3frxiwd9nj0ia5qf6v31zq8fg0gp-gnome-online-accounts-3.20.3.drv
  /nix/store/65shyr46hb4xkc55yw9wc3zljchydmrs-gfbgraph-0.2.2.drv
  /nix/store/82k9cd3vdpzi6l9kawp6nh4n5nbhdikd-libchamplain-0.12.14.drv
  /nix/store/nyw77pv10xhm3zq7s229kaizk9qb5wpa-libgdata-0.17.4.drv
  /nix/store/m7bqyb8av7dlhj62svgwr0g2xdg883bh-evolution-data-server-3.20.5.drv
  /nix/store/dqy92vn3bdll0imw7j5mzxas56wzqhk7-folks-0.11.0.drv
  /nix/store/g5wjv8b6lkcgixva5yybn0flip891927-libmx-1.4.7.drv
  /nix/store/hyry267ba46xz74ch4dblcwbsd22k1fr-keybinder3-0.3.0.drv
  /nix/store/kv5p2ic7qvqb0qyhp1xivbxp5aiz98db-gthumb-3.4.3.drv
  /nix/store/pzl900876grahcr2s1hij4s3ir62hrkr-gnome-themes-standard-3.20.2.drv
  /nix/store/mzd1sh4vw1d02x2613k2hm2dbvb876vg-gnome-contacts-3.20.0.drv
  /nix/store/r27vmsa8zal9dhpsfn6j1bx1sq4yh800-pinpoint-0.1.8.drv
  /nix/store/rf0jh123i3djh98gqfrb8h0gzisskvas-finalterm-git-2014-11-15.drv
  /nix/store/z65h20w7439kn6qsfqxx1fmy8avfr7pv-gnome-maps-3.20.2.drv
```

I recompiled my system and can confirm working:
- contacts
- online-accounts
- pinpoint
- evolution

I'm not certain how to test evolution data server.

gnome-maps does __not__ work:
```
(org.gnome.Maps:19878): Gjs-WARNING **: JS ERROR: Error: Requiring WebKit2, version none: Typelib file for namespace 'WebKit2' (any version) not found
@resource:///org/gnome/Maps/js/application.js:29
@resource:///org/gnome/Maps/js/main.js:43
start@resource:///org/gnome/gjs/modules/package.js:176
@/nix/store/3c8w5wz3niv2hns50bphcwhlp2p7d6jr-gnome-maps-3.20.2/bin/.gnome-maps-wrapped:5
```
but this is already happening on the commit I based my work on, so I believe this is unrelated.


Anything else I should verify?

**Comment by lethalman** [comment]
Looks great, thanks!

**Pull request merged**
