### PR TITLE
[23.11] logseq 0.9.20 -> 0.10.6

### PR DESCRIPTION
**Pull request by schmittlauch**
## Description of changes

Backports several updates of logseq to unbreak it in 23.11 stable. The current version there is marked as insecure due to depending on electron-25.9.0.

Backports the following PRs: #272126 #273570 #274180 #281751 #282003 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by schmittlauch** [comment]
@GrahamcOfBorg build logseq

**Review by kilianar — APPROVED** [review]

**Comment by mfenniak** [comment]
FYI logseq 0.10.6 is now released and available in unstable (#286593).

**Comment by schmittlauch** [comment]
Thx, also includng a backport for #286593 now.

**Comment by schmittlauch** [comment]
I noted some graphics accelleration error messages in the logs when starting logseq-0.10.6, but the application itself works fine.

`[12641:0207/153638.540702:ERROR:shared_context_state.cc(99)] Skia shader compilation error`

Unfortunately that seems to be a common Electron thing (especially with bundles), see #270699. An `rm ~/.config/Logseq/GPUCache -rf` resolves this.

**Comment by davidak** [comment]
>I noted some graphics accelleration error messages in the logs

@schmittlauch I had the same messages in terminal after updating my 23.11 system while the logseq package stayed the same (0.10.5 from unstable), but only on the first start of logseq after the update. When i updated logseq from unstable, i did not see the messages again. So it seem rather related to system components than logseq itself.

<details>
  <summary>Full log</summary>
  
  ```
[davidak@gaming:~]$ logseq
(rsapi) init loggers
DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
failed to bind extensions
DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
failed to bind extensions
DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
failed to bind extensions
16:56:43.710 › Logseq App(0.10.5) Starting... 
16:56:43.723 › restore proxy settings {:type "system"}
16:56:43.724 › set proxy to {:type "system"}
[27875:0224/165646.424052:ERROR:shared_context_state.cc(99)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float4 radii_selector;in float4 corner_and_radius_outsets;in float4 aa_bloat_and_coverage;in float4 radii_x;in float4 radii_y;in float4 skew;in float2 translate_and_localrotate;in half4 color;flat out half4 vcolor_S0;noperspective out float2 varccoord_S0;void main() {// Primitive Processor FillRRectOp::Processor
vcolor_S0 = color;float aa_bloat_multiplier = 1;float2 corner = corner_and_radius_outsets.xy;float2 radius_outset = corner_and_radius_outsets.zw;float2 aa_bloat_direction = aa_bloat_and_coverage.xy;float is_linear_coverage = aa_bloat_and_coverage.w;float2 pixellength = inversesqrt(float2(dot(skew.xz, skew.xz), dot(skew.yw, skew.yw)));float4 normalized_axis_dirs = skew * pixellength.xyxy;float2 axiswidths = (abs(normalized_axis_dirs.xy) + abs(normalized_axis_dirs.zw));float2 aa_bloatradius = axiswidths * pixellength * .5;float4 radii_and_neighbors = radii_selector* float4x4(radii_x, radii_y, radii_x.yxwz, radii_y.wzyx);float2 radii = radii_and_neighbors.xy;float2 neighbor_radii = radii_and_neighbors.zw;float coverage_multiplier = 1;if (any(greaterThan(aa_bloatradius, float2(1)))) {corner = max(abs(corner), aa_bloatradius) * sign(corner);coverage_multiplier = 1 / (max(aa_bloatradius.x, 1) * max(aa_bloatradius.y, 1));radii = float2(0);}float coverage = aa_bloat_and_coverage.z;if (any(lessThan(radii, aa_bloatradius * 1.5))) {radii = float2(0);aa_bloat_direction = sign(corner);if (coverage > .5) {aa_bloat_direction = -aa_bloat_direction;}is_linear_coverage = 1;} else {radii = clamp(radii, pixellength * 1.5, 2 - pixellength * 1.5);neighbor_radii = clamp(neighbor_radii, pixellength * 1.5, 2 - pixellength * 1.5);float2 spacing = 2 - radii - neighbor_radii;float2 extra_pad = max(pixellength * .0625 - spacing, float2(0));radii -= extra_pad * .5;}float2 aa_outset = aa_bloat_direction * aa_bloatradius * aa_bloat_multiplier;float2 vertexpos = corner + radius_outset * radii + aa_outset;if (coverage > .5) {if (aa_bloat_direction.x != 0 && vertexpos.x * corner.x < 0) {float backset = abs(vertexpos.x);vertexpos.x = 0;vertexpos.y += backset * sign(corner.y) * pixellength.y/pixellength.x;coverage = (coverage - .5) * abs(corner.x) / (abs(corner.x) + backset) + .5;}if (aa_bloat_direction.y != 0 && vertexpos.y * corner.y < 0) {float backset = abs(vertexpos.y);vertexpos.y = 0;vertexpos.x += backset * sign(corner.x) * pixellength.x/pixellength.y;coverage = (coverage - .5) * abs(corner.y) / (abs(corner.y) + backset) + .5;}}float2x2 skewmatrix = float2x2(skew.xy, skew.zw);float2 devcoord = vertexpos * skewmatrix + translate_and_localrotate.xy;if (0 != is_linear_coverage) {varccoord_S0.xy = float2(0, coverage * coverage_multiplier);} else {float2 arccoord = 1 - abs(radius_outset) + aa_outset/radii * corner;varccoord_S0.xy = float2(arccoord.x+1, arccoord.y);}sk_Position = devcoord.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
flat in half4 vcolor_S0;noperspective in float2 varccoord_S0;void main() {// Stage 0, FillRRectOp::Processor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;float x_plus_1=varccoord_S0.x, y=varccoord_S0.y;half coverage;if (0 == x_plus_1) {coverage = half(y);} else {float fn = x_plus_1 * (x_plus_1 - 2);fn = fma(y,y, fn);float fnwidth = fwidth(fn);coverage = .5 - half(fn/fnwidth);coverage = clamp(coverage, 0, 1);}half4 outputCoverage_S0 = half4(coverage);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec4 radii_selector;
in highp vec4 corner_and_radius_outsets;
in highp vec4 aa_bloat_and_coverage;
in highp vec4 radii_x;
in highp vec4 radii_y;
in highp vec4 skew;
in highp vec2 translate_and_localrotate;
in mediump vec4 color;
flat out mediump vec4 vcolor_S0;
noperspective out highp vec2 varccoord_S0;
void main() {
    vcolor_S0 = color;
    highp float aa_bloat_multiplier = 1.0;
    highp vec2 corner = corner_and_radius_outsets.xy;
    highp vec2 radius_outset = corner_and_radius_outsets.zw;
    highp vec2 aa_bloat_direction = aa_bloat_and_coverage.xy;
    highp float is_linear_coverage = aa_bloat_and_coverage.w;
    highp vec2 pixellength = inversesqrt(vec2(dot(skew.xz, skew.xz), dot(skew.yw, skew.yw)));
    highp vec4 normalized_axis_dirs = skew * pixellength.xyxy;
    highp vec2 axiswidths = abs(normalized_axis_dirs.xy) + abs(normalized_axis_dirs.zw);
    highp vec2 aa_bloatradius = (axiswidths * pixellength) * 0.5;
    highp vec4 radii_and_neighbors = radii_selector * mat4(radii_x, radii_y, radii_x.yxwz, radii_y.wzyx);
    highp vec2 radii = radii_and_neighbors.xy;
    highp vec2 neighbor_radii = radii_and_neighbors.zw;
    highp float coverage_multiplier = 1.0;
    if (any(greaterThan(aa_bloatradius, vec2(1.0)))) {
        corner = max(abs(corner), aa_bloatradius) * sign(corner);
        coverage_multiplier = 1.0 / (max(aa_bloatradius.x, 1.0) * max(aa_bloatradius.y, 1.0));
        radii = vec2(0.0);
    }
    highp float coverage = aa_bloat_and_coverage.z;
    if (any(lessThan(radii, aa_bloatradius * 1.5))) {
        radii = vec2(0.0);
        aa_bloat_direction = sign(corner);
        if (coverage > 0.5) {
            aa_bloat_direction = -aa_bloat_direction;
        }
        is_linear_coverage = 1.0;
    } else {
        radii = clamp(radii, pixellength * 1.5, 2.0 - pixellength * 1.5);
        neighbor_radii = clamp(neighbor_radii, pixellength * 1.5, 2.0 - pixellength * 1.5);
        highp vec2 spacing = (2.0 - radii) - neighbor_radii;
        highp vec2 extra_pad = max(pixellength * 0.0625 - spacing, vec2(0.0));
        radii -= extra_pad * 0.5;
    }
    highp vec2 aa_outset = (aa_bloat_direction * aa_bloatradius) * aa_bloat_multiplier;
    highp vec2 vertexpos = (corner + radius_outset * radii) + aa_outset;
    if (coverage > 0.5) {
        if (aa_bloat_direction.x != 0.0 && vertexpos.x * corner.x < 0.0) {
            highp float backset = abs(vertexpos.x);
            vertexpos.x = 0.0;
            vertexpos.y += ((backset * sign(corner.y)) * pixellength.y) / pixellength.x;
            coverage = ((coverage - 0.5) * abs(corner.x)) / (abs(corner.x) + backset) + 0.5;
        }
        if (aa_bloat_direction.y != 0.0 && vertexpos.y * corner.y < 0.0) {
            highp float backset = abs(vertexpos.y);
            vertexpos.y = 0.0;
            vertexpos.x += ((backset * sign(corner.x)) * pixellength.x) / pixellength.y;
            coverage = ((coverage - 0.5) * abs(corner.y)) / (abs(corner.y) + backset) + 0.5;
        }
    }
    highp mat2 skewmatrix = mat2(skew.xy, skew.zw);
    highp vec2 devcoord = vertexpos * skewmatrix + translate_and_localrotate;
    if (0.0 != is_linear_coverage) {
        varccoord_S0 = vec2(0.0, coverage * coverage_multiplier);
    } else {
        highp vec2 arccoord = (1.0 - abs(radius_outset)) + (aa_outset / radii) * corner;
        varccoord_S0 = vec2(arccoord.x + 1.0, arccoord.y);
    }
    gl_Position = vec4(devcoord, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
flat in mediump vec4 vcolor_S0;
noperspective in highp vec2 varccoord_S0;
void main() {
    mediump vec4 outputColor_S0 = vcolor_S0;
    highp float x_plus_1 = varccoord_S0.x;
    highp float y = varccoord_S0.y;
    mediump float coverage;
    if (0.0 == x_plus_1) {
        coverage = y;
    } else {
        highp float fn = x_plus_1 * (x_plus_1 - 2.0);
        fn = ((y) * (y) + (fn));
        highp float fnwidth = fwidth(fn);
        coverage = 0.5 - fn / fnwidth;
        coverage = clamp(coverage, 0.0, 1.0);
    }
    mediump vec4 outputCoverage_S0 = vec4(coverage);
    {
        sk_FragColor = outputColor_S0 * outputCoverage_S0;
    }
}


Errors:
link failed but did not provide an info log
[27804:0224/165652.475174:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=133
DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
failed to bind extensions
DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
failed to bind extensions
DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
failed to bind extensions
[28064:0224/165652.785896:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[28064:0224/165652.790654:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[28064:0224/165652.802923:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[28064:0224/165652.810068:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[28064:0224/165652.818922:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[28064:0224/165652.819419:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[28064:0224/165652.819623:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[28064:0224/165652.824042:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[28064:0224/165652.824512:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[28064:0224/165653.108657:ERROR:shared_image_manager.cc(220)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
16:56:53.241 › :electron.handler/watch-dir {:path "/home/davidak/.logseq/config"}
16:56:53.398 › :electron.handler/unwatch-dir {:path "/home/davidak/info/notes-logseq"}
16:56:53.399 › :electron.handler/watch-dir {:path "/home/davidak/info/notes-logseq"}
  ```
  
</details>

And the application did also work for we without additional errors despite the messages. I did not have to remove anything manually. Maybe the cache is cleared on the next start automatically.

The only issues i noticed when updating from 0.10.5 to .6 was https://github.com/logseq/logseq/issues/11042 and https://github.com/logseq/logseq/issues/3373, but the developers say the right sidebar is not supposed to be persistent.

I might do a test of 0.9.20 -> 0.10.6 later.

**Review by davidak — APPROVED** [review]
Change looks good

I downgraded the package to the versions of NixOS 23.05 (0.9.6) and updated to 23.11 version (0.9.20) and at the end to version from this PR (0.10.6). I did a re-index and restart every time and did not notice any issue.

I used a graph that i had used with 0.10.6 before, so the test might not be 100% accurate.

Keep in mind that this software is [known for loosing data](https://www.reddit.com/r/logseq/comments/18xbf6n/logseq_data_loss_concerns/) (especially with their sync), so i recommend to create a backup before updating and check if changed are saved to file after an update! (i did not have any data loss so far; using syncthing for sync)

**Pull request merged**
