### PR TITLE
Nodejs updates

### PR DESCRIPTION
**Pull request by zimbatm**
Mainly to fix the security updates from https://nodejs.org/en/blog/vulnerability/december-2015-security-releases/

### CODE REVIEW

**Comment by garbas** [comment]
@zimbatm could we also do some renaming as well to "fit" nodejs new versioning model ... i've added commit on top of your feel free to cherry pick it -> https://github.com/garbas/nixpkgs/commit/3413a5e45b30cce1ac2fc9c5ba8ba84b37abfdf7

**Comment by zimbatm** [comment]
@garbas good idea, added ^

**Comment by garbas** [comment]
@zimbatm merged, i've also fix another small thing which i forgot in the first place -> https://github.com/NixOS/nixpkgs/commit/7ac0052ad59c4a826b3db8ad49518a79b0a9c03e

**Comment by zimbatm** [comment]
Thanks Rok !

**Pull request closed without merging**
