### PR TITLE
passthrough config if there are no secrets defined (address #204559)

### PR DESCRIPTION
**Pull request by jcumming**
###### Description of changes

In the case where `sharedFolders` is an empty list, simply copy through the config file. Addresses #204559. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] tested module with `sharedFolders = []`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jcumming** [comment]
@jwoudenberg, @RyanGibb, @thoughtpolice, @dali99 

were on the original PR.

**Comment by RyanGibb** [comment]
This looks good to me!

**Review by jwoudenberg — APPROVED** [review]
Sorry about this! Looks great, thanks for the fix!

**Comment by aristidb** [comment]
Can we please merge either this or #205633 ?

**Pull request merged**
