### PR TITLE
xmlsec: add library path to lt_dladdsearchdir

### PR DESCRIPTION
**Pull request by B4dM4n**
###### Motivation for this change

When linking to `libxmlsec`, the linking binary/library has to ensure that the `xmlsec` `$out/lib` directory is in the `LD_LIBRARY_PATH`, to esure `libxmlsec` can find and load the crypto libraries. `xmlsec1` uses `wrapProgram` for this, but when an intermediate library is linking `libxmlsec`, it has no control over the `LD_LIBRARY_PATH` (like [python-xmlsec](https://github.com/NixOS/nixpkgs/compare/master...B4dM4n:python-xmlsec) ).

Adding `$out/lib` to `lt_dladdsearchdir` during library initialization works around `LD_LIBRARY_PATH` and ensures the crypto libraries can always be found.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthewbauer** [comment]
I think it would be good if can avoid patching like this. These patches usually end up breaking between version updates. I think we might be able to just add `$out/lib` to RPATH for `$out/lib/libxmlsec.*` and `$out/bin/xmlsec`, and put that in the postInstal...

**Comment by B4dM4n** [comment]
Modifying the `RPATH` didn't work for me.

The xmlsec crypto libraries aren't linked dynamically, but get loaded with `lt_dlopenext`. This function uses either a libtool integrated loader, which can be influenced via `lt_dladdsearchdir`, `LD_LIBRARY_PATH` and `LTDL_LIBRARY_PATH` or it uses `dlopen` which can be influenced via `LD_LIBRARY_PATH` and the ``RPATH`` of the library that calls `dlopen`, which is `libltdl.so` in this case.

I tested the `dlopen` variant by appending `$out/lib` to the `libxmlsec1.so` library `RPATH` and `strace`ing the `xmlsec1` binary (without `wrapProgram "$out/bin/xmlsec1"`), which already includes `$out/lib` in it's `RPATH`. (strace log: https://pastebin.com/2ZBVWWbK)

It only tries to load `libxmlsec1-openssl.so` from `/nix/store/xxx-glibc-2.27/lib/` (except the sane path, which is my `LD_LIBRARY_PATH`), which is the only `RPATH` entry of `libltdl.so`.
So `dlopen` and `RPATH` don't work together when used in a library.

These are the only options I could find so far.

**Comment by austinbutler** [comment]
I'm also trying to use `python-xmlsec` and it can't load the crypto library:

```
❯ python -c "import xmlsec"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
xmlsec.Error: (1, 'cannot load crypto library for xmlsec.')
```

@jtojnar in researching this problem I've seen your name pop up on related issues elsehwere.

**Comment by austinbutler** [comment]
Looks like `pysaml2` also has trouble with `xmlsec` and does patching: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pysaml2/default.nix

**Comment by jtojnar** [comment]
The changes look reasonable. Future updates can break any customizations and I prefer when the breakage is loud so that we can be aware of it and fix it. Since this was not caught by the project tests adding a derivation checking if this still works to `passthru.tests` would be a good idea.

---

Looks like `xmlSecCryptoDLLoadLibrary` [only takes](https://github.com/lsh123/xmlsec/blob/c882d225f87194a8d457ad61ee23ff4befdb86c7/src/dl.c#L394) crypto library name like `openssl` or `nss` and then it constructs `libxmlsec1-nss` library name, which is `lt_dlopen`ed

1. https://github.com/lsh123/xmlsec/blob/c882d225f87194a8d457ad61ee23ff4befdb86c7/src/dl.c#L442
2. https://github.com/lsh123/xmlsec/blob/c882d225f87194a8d457ad61ee23ff4befdb86c7/src/dl.c#L451
3. https://github.com/lsh123/xmlsec/blob/c882d225f87194a8d457ad61ee23ff4befdb86c7/src/dl.c#L118
4. https://github.com/lsh123/xmlsec/blob/c882d225f87194a8d457ad61ee23ff4befdb86c7/src/dl.c#L252

so alternately, we could hard-code the absolute path within `xmlSecCryptoDLLibraryConstructFilename`. That might have the benefit that any future changes would complain loudly by breaking tests but it would require us to include the file extension too.

**Comment by B4dM4n** [comment]
> Looks like `pysaml2` also has trouble with `xmlsec` and does patching:

`pysaml2` only uses the `xmlsec1` binary, so nothing would change there.

> Since this was not caught by the project tests adding a derivation checking if this still works to `passthru.tests` would be a good idea.

The tests seem to only run the `xmlsec1` binary and library loading is made possible by setting `LD_LIBRARY_PATH` in the [Makefile](https://github.com/lsh123/xmlsec/blob/xmlsec-1_2_28/Makefile.am#L78).

Adding a `passthru.tests` check for library loading is a good idea. I'm currently working on such a test.

> so alternately, we could hard-code the absolute path within `xmlSecCryptoDLLibraryConstructFilename`. That might have the benefit that any future changes would complain loudly by breaking tests but it would require us to include the file extension too.

I'm not sure if hardcoding the paths has an advantage over embedding the `lib` path. If the tests can ensure that library loading works, both should fail equally fast on a breaking change.

The benefit of embedding the `lib` path would be that dependent packages can still modify the `search_dir` and load their own libraries instead of the embedded ones.

**Comment by glittershark** [comment]
@B4dM4n did you ever end up packaging python-xmlsec? I'm trying to get it built right now and running into dlopen issues

**Comment by glittershark** [comment]
> I'm also trying to use python-xmlsec and it can't load the crypto library:
> 
> ❯ python -c "import xmlsec"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> xmlsec.Error: (1, 'cannot load crypto library for xmlsec.')

this is the exact issue I'm getting, even with this patch

**Comment by glittershark** [comment]
never mind, I'm actually just running an older version of nixpkgs than when this was merged

**Pull request merged**
