### PR TITLE
vscode-extensions: update various

### PR DESCRIPTION
**Pull request by schuelermine**
###### Description of changes

Updated various VSCode extension

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 204319` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>vscode-extensions.github.vscode-pull-request-github</li>
    <li>vscode-extensions.haskell.haskell</li>
    <li>vscode-extensions.llvm-vs-code-extensions.vscode-clangd</li>
    <li>vscode-extensions.mkhl.direnv</li>
    <li>vscode-extensions.ms-pyright.pyright</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>vscode-extensions.ms-toolsai.jupyter</li>
    <li>vscode-extensions.ms-toolsai.jupyter-renderers</li>
    <li>vscode-extensions.ms-vscode.cmake-tools</li>
    <li>vscode-extensions.redhat.java</li>
    <li>vscode-extensions.redhat.vscode-xml</li>
    <li>vscode-extensions.thenuprojectcontributors.vscode-nushell-lang</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-extensions.vscjava.vscode-java-debug</li>
    <li>vscode-extensions.vscjava.vscode-java-dependency</li>
    <li>vscode-extensions.vscjava.vscode-java-test</li>
    <li>vscode-extensions.vscjava.vscode-maven</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]

**Comment by linsui** [comment]
The python extension doesn't work with vscode 1.73.

**Comment by schuelermine** [comment]
Yes, I’ve noticed this too, recently. Unfortunately upgrading VSCode is currently difficult because it stops all extensions from working. Should this PR be reverted? @figsoda

**Comment by linsui** [comment]
Does https://github.com/NixOS/nixpkgs/pull/205080 fix the problem? I don't know how to test it.

**Comment by linsui** [comment]
It works with some fixes.

**Comment by figsoda** [comment]
I'm not familiar enough to review #205080, so I opened https://github.com/NixOS/nixpkgs/pull/205661 to revert this

**Pull request merged**
