### PR TITLE
python3Packages.pytorch: 1.5.0 -> 1.5.1

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

* Update PyTorch to 1.5.1.
* Fix AArch64 build error.

* Tested CUDA build: :heavy_check_mark: 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danieldk** [comment]
@GrahamcOfBorg build python3Packages.pytorch

**Comment by danieldk** [comment]
@ofborg build python37Packages.pytorch python38Packages.pytorch

**Comment by danieldk** [comment]
cc: @drewrisinger @mweinelt since you have reviewed previous pytorch bumps and/or related packages.

**Comment by jonringer** [comment]
Needed to run the review on my server, as my desktop isn't powerful enough. but fridh beat me to it

**Pull request merged**
