### PR TITLE
signal-desktop: 6.2.0 -> 6.3.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
@urandom2 Because now the default.nix contains both releases in one file and the source in a generic.nix I think @r-ryantm is no longer able to automatically update signal-desktop. I would appreciate a different file structure or otherwise recommend to revert to only have a single release in the repository as fast updates for signal are more important in my opinion than having beta releases.

**Comment by Mic92** [comment]
In https://github.com/Mic92/nixpkgs/commit/966609236bddfe52dde86675b922f0ab6e203b1c I also add an updateScript but this still relies on having a feature in nix-update first (https://github.com/Mic92/nix-update/pull/137)

**Comment by urandom2** [comment]
I got push back from @SuperSandro2000 in #199592 when I tried to do this with two versions of `default.nix`, I am not opposed, but I agree that, considering the complexity of packaging this application, one file is the better way to manage the derivations. we could probably do something with `overrideAttrs`, but the current packaging strategy was suggested by @SuperSandro2000, so I used it. if you can be concrete in your alternative, I am happy to mock it up or review it.

I will also clarify, that there are many pre-release features that are only available on beta release, sometimes for years. so this is not a matter of simply getting a slightly newer version of the app, many people myself included want the extra functionality that only the beta version offers. one alternative, would be to build the application from source and have a "beta"/"development" build that is the stable version, but with all the bells turned on. today that is not possible with the way we unpack the `deb` file.

**Review by urandom2 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> I got push back from @SuperSandro2000 in #199592 when I tried to do this with two copies of `default.nix`, I am not opposed, but I agree that, considering the complexity of packaging this application, one file is the better way to manage the derivations. we could probably do something with `overrideAttrs`, but the current packaging strategy was suggested by @SuperSandro2000, so I used it. if you can be concrete in your alternative, I am happy to mock it up or review it.

We don't want to duplicate the entire file and using overwrites here is unnecessary.
If splitting the default.nix into a release and beta file helps updating, then we can do that.

**Pull request merged**
