### PR TITLE
libffi: 3.0.13 -> 3.1.2

### PR DESCRIPTION
**Pull request by joachifm**
Built locally, partially rebuilt revdeps. Works for me.

### CODE REVIEW

**Comment by joachifm** [comment]
Hm, travis just times out. Seems like this might cause a huge number of rebuilds, maybe I should submit against staging instead ... ?

**Comment by jagajaga** [comment]
Seems to be so..

**Comment by joachifm** [comment]
Okay, resubmitting against staging, then.

**Comment by joachifm** [comment]
Meh, nevermind, it already IS in staging.

**Pull request closed without merging**
