### PR TITLE
tonelib-jam: init at 4.6.6 && tonelib-zoom: init at 4.3.1

### PR DESCRIPTION
**Pull request by dan4ik605743**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dan4ik605743** [comment]
@SuperSandro2000 Well, I seem to have done everything right.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128164` at 1797a61b run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>tonelib-jam</li>
    <li>tonelib-zoom</li>
  </ul>
</details>

**Comment by dan4ik605743** [comment]
@SuperSandro2000 Hello. When will you push the packages?

**Comment by SuperSandro2000** [comment]
> Well, I seem to have done everything right.

You didn't squash the commits together.

**Comment by dan4ik605743** [comment]
@SuperSandro2000 Well, push 2 different ones. for 2 packages. Can't you?

**Comment by dan4ik605743** [comment]
@SuperSandro2000 If in one commit. That is the names of the commit tonelib-jam: init at 4.6.6 && tonelib-zoom: init at 4.3.1 Will it go?

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 If in one commit. That is the names of the commit tonelib-jam: init at 4.6.6 && tonelib-zoom: init at 4.3.1 Will it go?

No, in two commits. Right now this PR has 18.

**Comment by dan4ik605743** [comment]
@SuperSandro2000 I don `t understand. I named the last 2 commits correctly? If so, how can I make exactly 2 commits for PR?

**Comment by dan4ik605743** [comment]
@SuperSandro2000 what should I do now. for my PR to be pushed?

**Comment by dan4ik605743** [comment]
> > @SuperSandro2000 If in one commit. That is the names of the commit tonelib-jam: init at 4.6.6 && tonelib-zoom: init at 4.3.1 Will it go?
> 
> No, in two commits. Right now this PR has 18.

@SuperSandro2000 No, I mean. Will the names "tonelib-jam: init at 4.6.6 && tonelib-zoom: init at 4.3.1" be ok for one commit?

**Comment by SuperSandro2000** [comment]
> > > @SuperSandro2000 If in one commit. That is the names of the commit tonelib-jam: init at 4.6.6 && tonelib-zoom: init at 4.3.1 Will it go?
> > 
> > 
> > No, in two commits. Right now this PR has 18.
> 
> @SuperSandro2000 No, I mean. Will the names "tonelib-jam: init at 4.6.6 && tonelib-zoom: init at 4.3.1" be ok for one commit?

No, those should be two commits.

**Comment by dan4ik605743** [comment]
> > > > @SuperSandro2000 If in one commit. That is the names of the commit tonelib-jam: init at 4.6.6 && tonelib-zoom: init at 4.3.1 Will it go?
> > > 
> > > 
> > > No, in two commits. Right now this PR has 18.
> > 
> > @SuperSandro2000 No, I mean. Will the names "tonelib-jam: init at 4.6.6 && tonelib-zoom: init at 4.3.1" be ok for one commit?
> 
> No, those should be two commits.

@SuperSandro2000 Well, I made 2 packages with 2 commits. What then is the problem ???

**Comment by SuperSandro2000** [comment]
No, you did not make 2 commits. You made 18. 

image

**Comment by dan4ik605743** [comment]
> No, you did not make 2 commits. You made 18. 
> 
> image
> 

@SuperSandro2000 Yeah .... Okay .. How to choose only 2 commits in PR?

**Pull request closed without merging**
