### PR TITLE
release: cache all insecure packages except the worse ones

### PR DESCRIPTION
**Pull request by RaitoBezarius**
###### Description of changes

This is an alternative to #233024, this one is targeted on disallowing specific packages and allowing everything by default. It has much better UX properties.

With the help of @vcunat we figured the data on the rebuilds count, included in the commit message of the release commit.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
cc @SuperSandro2000 @delroth (as it was your proposal originally)

**Review by K900 — APPROVED** [review]
I like this. The cost to Hydra seems very small compared to the number of potential users, and if you're still going to shoot yourself in the foot even after explicitly being warned, you hopefully know what you're doing so we can make your life less painful.

**Comment by vcunat** [comment]
- My reasoning: if a package is not useful anymore, it should be dropped instead.
- This is easy, also for future cases, and it should be cheap.  (if an expensive one gets discovered, we can e.g. set `hydraPlatforms` in it as well)
- The count looks high, but most of it are `rubyPackages_2_7`.

Downside:
- This way of blacklisting doesn't work transitively, i.e. they can still get pulled by another package to get built on Hydra.  Maybe it doesn't really work now already.

**Comment by alois31** [comment]
> This way of blacklisting doesn't work transitively, i.e. they can still get pulled by another package to get built on Hydra. Maybe it doesn't really work now already.

What about blocking the offenders directly from the `allowedInsecurePredicate`?

**Comment by RaitoBezarius** [comment]
Let's revisit this in the next days, this can still make sense for 23.11.

**Comment by RaitoBezarius** [comment]
No further interest has spawned, will close, can reopen if it arise again.

**Comment by SuperSandro2000** [comment]
@delroth expressed explizit interest in this in his wishlist and I think, too, that without this, we cannot properly label insecure packages which take longer to compile or are dependencies of other things.

So in reality anything that is a dependency of a browser can never be marked with a vulnerability and we need to get away from that. (Unless we want people to compile the browser which we don't want to)

**Comment by delroth** [comment]
To be clear, I'm not 100% convinced that this is the correct solution, though I am interested in the general problem space. If we do want to track vulnerability status via `knownVulnerabilities`, we absolutely need this. But I don't know that `knownVulnerabilities` is necessarily a good idea, and I would tend to think a complete rework of the semantics is likely needed.

We already apply some weird human-heuristic-based semantics to `knownVulnerabilities` right now, except I think it's very unclear to everyone what those semantics actually are, including to the people making the decisions.

**Pull request closed without merging**
