### PR TITLE
jitterentropy: switch to cmake build, darwin support, `with lib;` cleanup, RFC format

### LINKED ISSUE #354200: Build failure: botan3 (aarch64-darwin)
### Steps To Reproduce

1. build *botan3* on aarch64-darwin

### Build log

```console
$ nix build 'nixpkgs#botan3'
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'botan-3.6.1'
         whose name attribute is located at /nix/store/np74wqp8a8jzss4z38ch34mmivl6id9k-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'buildInputs' of derivation 'botan-3.6.1'
         at /nix/store/np74wqp8a8jzss4z38ch34mmivl6id9k-source/pkgs/stdenv/generic/make-derivation.nix:383:7:
          382|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          383|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          384|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: Package ‘jitterentropy-3.6.0’ in /nix/store/np74wqp8a8jzss4z38ch34mmivl6id9k-source/pkgs/development/libraries/jitterentropy/default.nix:27 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
         package.meta.platforms = [
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.
```

With `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1`:

```console
$ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
$ nix build 'nixpkgs#botan3' --impure
error: builder for '/nix/store/lx9gxlr7jh4nd7p5i1nx0l3d8jyqmmyn-jitterentropy-3.6.0.drv' failed with exit code 2;
       last 25 log lines:
       >         ^
       > 1 warning generated.
       > In file included from src/jitterentropy-base.c:33:
       > In file included from src/jitterentropy-gcd.h:23:
       > In file included from src/jitterentropy-internal.h:45:
       > In file included from ./jitterentropy.h:148:
       > ./jitterentropy-base-user.h:125:9: warning: extension used [-Wlanguage-extension-token]
       >         asm volatile("mrs %0, cntvct_el0" : "=r" (ctr_val));
       >         ^
       > 1 warning generated.
       > In file included from src/jitterentropy-timer.c:22:
       > In file included from src/jitterentropy-timer.h:23:
       > In file included from src/jitterentropy-internal.h:45:
       > In file included from ./jitterentropy.h:148:
       > ./jitterentropy-base-user.h:125:9: warning: extension used [-Wlanguage-extension-token]
       >         asm volatile("mrs %0, cntvct_el0" : "=r" (ctr_val));
       >         ^
       > 1 warning generated.
       > 1 warning generated.
       > 1 warning generated.
       > clang -shared -Wl,-soname,libjitterentropy.so.3 -o libjitterentropy.so.3.6.0 jitterentropy-base.o jitterentropy-gcd.o jitterentropy-health.o jitterentropy-noise.o jitterentropy-sha3.o jitterentropy-timer.o -Wl,-z,relro,-z,now -lpthread  -lrt
       > ar rcs libjitterentropy.a jitterentropy-base.o jitterentropy-gcd.o jitterentropy-health.o jitterentropy-noise.o jitterentropy-sha3.o jitterentropy-timer.o
       > ld: unknown option: -soname
       > clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
       > make: *** [Makefile:69: libjitterentropy.so.3.6.0] Error 1
       For full logs, run 'nix log /nix/store/lx9gxlr7jh4nd7p5i1nx0l3d8jyqmmyn-jitterentropy-3.6.0.drv'.
error: 1 dependencies of derivation '/nix/store/1k3rh1yh19wb7gpnzqhinqsrxspdwvyr-botan-3.6.1.drv' failed to build
```

### Additional context

`jitterentropy` dependency was added in https://github.com/NixOS/nixpkgs/commit/3d69d435ba19175a76d733c96ad09a2f93483e95

### Notify maintainers

@7c6f434c
@thillux 

### Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.7.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/np74wqp8a8jzss4z38ch34mmivl6id9k-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by matteo-pacini**
- Moved `jitterentropy` from Makefile-based build to `cmake`, which has better support for Clang.
- `botan3` compiles fine as a result of that

Fixes #354200

Not sure the cross-compilation fixes are still needed, but I'd be grateful if anyone could test it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matteo-pacini** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354238`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>botan3</li>
    <li>botan3.bin</li>
    <li>botan3.dev</li>
    <li>botan3.doc</li>
    <li>botan3.man</li>
    <li>jitterentropy</li>
    <li>jitterentropy.dev</li>
    <li>keepassxc</li>
    <li>rehex</li>
    <li>rnp</li>
    <li>rnp.dev</li>
    <li>rnp.lib</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>botan3</li>
    <li>botan3.bin</li>
    <li>botan3.dev</li>
    <li>botan3.doc</li>
    <li>botan3.man</li>
    <li>jitterentropy</li>
    <li>jitterentropy.dev</li>
    <li>keepassxc</li>
    <li>rehex</li>
    <li>rnp</li>
    <li>rnp.dev</li>
    <li>rnp.lib</li>
  </ul>
</details>

**Comment by matteo-pacini** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354238`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 16 packages built:</summary>
  <ul>
    <li>botan3</li>
    <li>botan3.bin</li>
    <li>botan3.dev</li>
    <li>botan3.doc</li>
    <li>botan3.man</li>
    <li>corectrl</li>
    <li>emiluaPlugins.botan</li>
    <li>esdm</li>
    <li>jitterentropy</li>
    <li>jitterentropy.dev</li>
    <li>keepassxc</li>
    <li>rehex</li>
    <li>rng-tools</li>
    <li>rnp</li>
    <li>rnp.dev</li>
    <li>rnp.lib</li>
  </ul>
</details>

**Comment by thillux** [comment]
As a neat side effect, this also fixes building jitterentropy with musl libc. :+1:

**Review by khaneliman — APPROVED** [review]
LGTM but would be nice to hear from maintainers.

**Review by mibmo — APPROVED** [review]
How come you disable parallel builds? otherwise looks and compiles fine.

**Comment by matteo-pacini** [comment]
@mibmo it's enabled by default https://github.com/NixOS/nixpkgs/issues/142338

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354238`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 15 packages built:</summary>
  <ul>
    <li>botan3</li>
    <li>botan3.bin</li>
    <li>botan3.dev</li>
    <li>botan3.doc</li>
    <li>botan3.man</li>
    <li>corectrl</li>
    <li>emiluaPlugins.botan</li>
    <li>esdm</li>
    <li>jitterentropy</li>
    <li>jitterentropy.dev</li>
    <li>keepassxc</li>
    <li>rehex</li>
    <li>rnp</li>
    <li>rnp.dev</li>
    <li>rnp.lib</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 15 packages built:</summary>
  <ul>
    <li>botan3</li>
    <li>botan3.bin</li>
    <li>botan3.dev</li>
    <li>botan3.doc</li>
    <li>botan3.man</li>
    <li>corectrl</li>
    <li>emiluaPlugins.botan</li>
    <li>esdm</li>
    <li>jitterentropy</li>
    <li>jitterentropy.dev</li>
    <li>keepassxc</li>
    <li>rehex</li>
    <li>rnp</li>
    <li>rnp.dev</li>
    <li>rnp.lib</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>botan3</li>
    <li>botan3.bin</li>
    <li>botan3.dev</li>
    <li>botan3.doc</li>
    <li>botan3.man</li>
    <li>jitterentropy</li>
    <li>jitterentropy.dev</li>
    <li>keepassxc</li>
    <li>rehex</li>
    <li>rnp</li>
    <li>rnp.dev</li>
    <li>rnp.lib</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>botan3</li>
    <li>botan3.bin</li>
    <li>botan3.dev</li>
    <li>botan3.doc</li>
    <li>botan3.man</li>
    <li>jitterentropy</li>
    <li>jitterentropy.dev</li>
    <li>keepassxc</li>
    <li>rehex</li>
    <li>rnp</li>
    <li>rnp.dev</li>
    <li>rnp.lib</li>
  </ul>
</details>

**Pull request merged**
