### PR TITLE
haskellPackages.hopengpg-tools: Unmark broken

### PR DESCRIPTION
**Pull request by motiejus**
https://github.com/drduh/YubiKey-Guide/issues/370
https://github.com/drduh/YubiKey-Guide/issues/406

## Things done

```
$ nix build  .#legacyPackages.x86_64-linux.haskellPackages.hopenpgp-tools
$
```

### CODE REVIEW

**Comment by maralorn** [comment]
Oh, sorry. I just noticed you are manually editing hackage-packages.nix. That won’t work because that file gets frequently auto-regenerated.

The correct solution is to override this in configuration-common.nix. You can have a look at that file it has plenty of examples and your case is a very usual one.

**Comment by maralorn** [comment]
Getting there. But you need to remove the broken flag by deleting the entry in broken.yaml and then run regenerate-hackage-packages.nix

**Comment by maralorn** [comment]
Also have you tried using .override instead of .overrideScope? If the former works it is preferred, because it is much simpler.

**Comment by motiejus** [comment]
Regenerating doesn't work for me :(

```
[motiejus@fwminex:~/code/nixpkgs]$ maintainers/scripts/haskell/regenerate-hackage-packages.sh
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
these 2 paths will be fetched (2.43 MiB download, 15.92 MiB unpacked):
  /nix/store/7h0wrvl3ckgx2hc5460mjja3w7jijq6i-cabal2nix-unstable-2023-11-02
  /nix/store/2572jl8vhhimwcdy0rj5qq230l4ynw4z-distribution-nixpkgs-1.7.0.1-data
copying path '/nix/store/2572jl8vhhimwcdy0rj5qq230l4ynw4z-distribution-nixpkgs-1.7.0.1-data' from 'https://cache.nixos.org'...
copying path '/nix/store/7h0wrvl3ckgx2hc5460mjja3w7jijq6i-cabal2nix-unstable-2023-11-02' from 'https://cache.nixos.org'...
maintainers/scripts/haskell/regenerate-hackage-packages.sh: line 71: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
Obtaining Hackage data …
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
this derivation will be built:
  /nix/store/cbz1ki2rngmdgyz8fsg395inxsvsldy0-unpacked-cabal-hashes.drv
this path will be fetched (65.43 MiB download, 66.95 MiB unpacked):
  /nix/store/87bg2gniirfrz4qr1lfiw9iyb6dq07v6-all-cabal-hashes-def4ad9.tar.gz
copying path '/nix/store/87bg2gniirfrz4qr1lfiw9iyb6dq07v6-all-cabal-hashes-def4ad9.tar.gz' from 'https://cache.nixos.org'...
building '/nix/store/cbz1ki2rngmdgyz8fsg395inxsvsldy0-unpacked-cabal-hashes.drv'...
Generating compiler configuration …
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
Running hackage2nix to regenerate pkgs/development/haskell-modules/hackage-packages.nix …
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
hackage2nix: /home/motiejus/code/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix: withFile: invalid argument (cannot encode character '\8211')

[motiejus@fwminex:~/code/nixpkgs]$ git diff --stat
 pkgs/development/haskell-modules/hackage-packages.nix | 321918 +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 file changed, 1 insertion(+), 321917 deletions(-)
```

Is it because my system is on flakes, or is it a red herring?

**Comment by maralorn** [comment]
Oh, boy. My system is also on flakes. That’s not the issue. The problem is that you have an incompatible locale setup.
That’s annoying and our script should be more robust, but I currently don’t know how to fix it.
You may just remove the entry from the broken.yaml and I can run the script for you after merging the PR.

**Comment by motiejus** [comment]
> Oh, boy. My system is also on flakes. That’s not the issue. The problem is that you have an incompatible locale setup. That’s annoying and our script should be more robust, but I currently don’t know how to fix it.

Ack.

> You may just remove the entry from the broken.yaml and I can run the script for you after merging the PR.

The current version does just that, and I would appreciate a fix.

Do you need a track

**Pull request merged**
