### PR TITLE
python3Packages.robomachine: fix by using pyparsing_2 

### PR DESCRIPTION
**Pull request by bjornfor**
###### Description of changes
RoboMachine tests broke, this fixes it by using pyparsing_2 intead of default pyparsing (3.x).

Upstream issue: https://github.com/mkorpela/RoboMachine/issues/28

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bjornfor** [comment]
Any objections to merging?

**Comment by raboof** [comment]
I'm confused: the upstream issue is still open, but robomachine seems to build successfully on nixos-unstable now AFAICS.

Is this PR no longer needed or where the tests just disabled somehow?

**Comment by bjornfor** [comment]
Looks like the build was fixed by 8742e41f50277a7353c0ab5b93bf01d42a97f39f, but it also implicitly disabled running the tests? (I can't see any tests being run in the build log.) It's using pyparsing 3.x now, which I presume still breaks the tests (if run) because robomachine is still the same version as when I made this issue.

I saved [this example](https://github.com/mkorpela/RoboMachine#what-does-it-look-like) as `example.robomachine` and ran:

```
$ ./result/bin/robomachine --do-not-execute ./example.robomachine
Exception at line 16
Expected {Re:(' *\n') ^ LineEnd}
line: "${USERNAME}  any of  ${VALID_USERNAME}  ${VALID_PASSWORD}  invalid123  ${EMPTY}"
```

So it looks like 8742e41f50277a7353c0ab5b93bf01d42a97f39f traded build time failure for run time failure. If I go back to e.g. nixpkgs @ release-21.05 that example works fine.

Ping @marsam.

**Review by FRidh — CHANGES_REQUESTED** [review]
We cannot mix runtime versions in python-packages.nix as that can lead to collisions.

**Pull request closed without merging**
