### PR TITLE
Add .github/FUNDING.yml

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
Might need some manual setup from someone with heightened repository privileges.
* https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

**Review by memberbetty — APPROVED** [review]

**Comment by Infinisil** [comment]
I'm not really sure about that. From the blog post I got the feeling that "GitHub Sponsors" is for explicitly supporting the people that do the work of contributing to the project via PRs and such.

Donating to the NixOS organization however totally excludes all those people. As far as I can see that money goes mainly towards the build servers, which is of course also important, but doesn't have anything directly to do with nixpkgs development. If nobody makes or merges any PRs, the build servers would be idle.

There are many people who spend many hours of their free time during their week to help with nixpkgs, and *if* we put up such information for how to sponsor nixpkgs, I think it would only be fair to somehow see that those people are included.

**Comment by worldofpeace** [comment]
> I'm not really sure about that. From the blog post I got the feeling that "GitHub Sponsors" is for explicitly supporting the people that do the work of contributing to the project via PRs and such.
> 

> Donating to the NixOS organization however totally excludes all those people. As far as I can see that money goes mainly towards the build servers, which is of course also important, but doesn't have anything directly to do with nixpkgs development. If nobody makes or merges any PRs, the build servers would be idle.
>
> There are many people who spend many hours of their free time during their week to help with nixpkgs, and _if_ we put up such information for how to sponsor nixpkgs, I think it would only be fair to somehow see that those people are included.

---
> https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository
> Funding links provide a way for open source projects to receive direct financial support from their community.

I feel that this technically falls under that view since it would be a direct donation to the NixOS organization.
This is only one funding option that is in use in this project. If any community member would like to add their funding model for their work, the following are currently supported if they aren't GitHub sponsors enabled
* Patreon
* Open Collective
* Ko-fi
* Tidelift

Consider this a call for those people to step forward for recognition.

**Review by davidak — APPROVED** [review]

**Comment by Infinisil** [comment]
It just concerns me because in the future there might be a person or company thinking they want to support nixpkgs development, seeing the funding thing, and deciding to give $1000 to it per month. That money however doesn't help nixpkgs development directly at all though, they've essentially been misled. And I'd rather not mislead people when it has to do with money. Or would the NixOS organization employ people to work on NixOS/nixpkgs if there's enough funds?

I think we should at least mention where this money goes in `FUNDING.yml`, and that most nixpkgs developers don't have anything from it. Can you include something like this in it?

> Consider this a call for those people to step forward for recognition.

You mean people should add themselves to `FUNDING.yml` to link to their funding platform?

**Comment by worldofpeace** [comment]
> You mean people should add themselves to FUNDING.yml to link to their funding platform?

I'd like people, if they'd like to be recognized in this way, to please either make a commit somewhere so I can pick it into this pr, pull request against it, or just ask me to add them to this file.

> I think we should at least mention where this money goes in FUNDING.yml, and that most nixpkgs developers don't have anything from it. Can you include something like this in it?

As for describing the custom platform I can supply a description in the file, however someone would have to see the source file in order to receive that information. So it would be unlikely that they'd see that.

>  That money however doesn't help nixpkgs development directly at all though, they've essentially been misled. And I'd rather not mislead people when it has to do with money. Or would the NixOS organization employ people to work on NixOS/nixpkgs if there's enough funds?

NixOS foundation is a Nonprofit organization. The revenues will always be used to further achieve its prime objective which is to support
* Nix ecosystem's infrastructure
* Nix, Nixpkgs, NixOS

So it can't have anything to do with distributing the income to the organization's members.
I'm not sure what's misleading about that, the custom platform shouldn't have any similarity to `GitHub Sponsors`.

**Comment by Infinisil** [comment]
> however someone would have to see the source file in order to receive that information. So it would be unlikely that they'd see that.

Oh I see, that's too bad.

Well I'm still not a big fan of this. But in any case, *if* we do this, https://nixos.org/nixos/foundation.html should be gotten up-to-date imo.

**Comment by Infinisil** [comment]
Although it doesn't really matter for this change whether that page is up-to-date, but it would be nice.

**Comment by davidak** [comment]
@Infinisil with update you mean the "Donations/expenses history"?

That's an ongoing effort... https://github.com/NixOS/nixos-foundation/issues/1

I think this PR is good since it links the current official donation page. Anything else is another issue.

**Comment by worldofpeace** [comment]
I'm going to merge this now and ask on discourse if anyone is interested in https://github.com/NixOS/nixpkgs/pull/62338#issuecomment-497952218

**Pull request merged**
