### PR TITLE
minetest: update to 5.1.0 and build on Darwin

### PR DESCRIPTION
**Pull request by Quiark**
###### Motivation for this change
Build minetest and irrlicht on Darwin.
Update minetest to 5.1.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Profpatsch** [comment]
Usually we put the macOS versions into the same file, to avoid duplication (and use conditionals inside the file). Is this not an option here?

**Comment by Quiark** [comment]
For irrlicht, I wasn't able to get the build system based on Xcode to work so I found another one based on cmake. Therefore it's quite different in the end.

**Review by Profpatsch — APPROVED** [review]
Ready to merge?

**Comment by Quiark** [comment]
Yes, done on my side

**Pull request merged**
