### PR TITLE
Prometheus: upgrade configuration module to use the 2.x package

### PR DESCRIPTION
**Pull request by azazel75**
Although it's not possible to migrate an existing 1.x to 2.x this upgrade seems appropriate because there are no more 1.x docs available online and the configuration format changed without backward compatibility letting people installing it having serious issues.

This upgrade is conservative: it keeps all the old configuation items without introducing new ones that may be preferable to configure "alertmanager service discovery" optional feature. (It's possible to configure it specifying a configuration file)

I've personally spent some ours finding out that the configuration error reported by the prometheus daemon on my installation was really a misconfiguration due to the use of the old prometheus 1.x by the configuration module, despite the fact that the prometheus 2.x it's already available in nixpackages.

###### Motivation for this change

Configure a version of the prometheus services that you can actually find documentation for.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
I've thought about this a lot in the past. I don't think it's a good idea to update prometheus to 2.x quietly because old data won't be available anymore as you've already mentioned. On the other hand I agree that we have to update to 2.x as soon as possible.

Also, some options slightly changed but we've already made these changes in our fork (we've got a dedicated `services.prometheus2` module) and I would be happy to merge those into your PR.

If we do this like you propose, we would have to at least mention this change in the release notes because it is a backwards-incompatible change.

@vcunat & @samueldr What do you think about this change for 18.09? Do you think that adding a new `services.prometheus2` module might be better than breaking current setups?

**Comment by vcunat** [comment]
If this is about DB data, have you considered using `system.stateVersion`?

**Comment by azazel75** [comment]
@vcunat  can you elaborate please?

**Comment by bachp** [comment]
I think what @vcunat mean it to just make it depend on `system.stateVersion` which prometheus version to use. So basically for `system.stateVersion >= 18.09` it would be prometheus 2 for earlier ones it would be 1.

I actually also thought about making it depend on `system.stateVersion`, but I think creating a `prometheus2` module is probably the better way. Especially because it would support the recommended "migration strategy" of keeping prometheus running  in parallel.

**Comment by andir** [comment]
How will we continue here? I just ran into this as I read the docs and wanted to setup a new Prometheus instance.

The least invasive thing that we should do is introduce a prometheus2 module (only for prometheus, not the exporters?) that will be available in the next release. Optionally use stateVersion to support a transition between v1 & v2?

**Comment by globin** [comment]
Do we really need to create more users for prometheus2 etc.? This PR seems far to complicated, I'd personally just copy over the prometheus file, fix the options and paths for prometheus2 and deprecate the old module and remove that file after 19.03?

**Comment by andir** [comment]
I partially agree. How long is the 1.x branch still receiving updates? If
not then I am for deprecating it with 19.03.

**Comment by azazel75** [comment]
@goblin sorry  for the noise, I'm currently rebasing it on master and I haven't finished yet.
About the user, it was my first take on the problem but I'm open to suggestions ;-) 
About the deletion of the old stuff: as other said, there's no upgrade path from Prometheus 1 to Prometheus 2, so the advised way to deal with it is to run them in parallel and configure the 1.x instance as source for the 2.x

**Comment by azazel75** [comment]
So, now that I've completed the merge:  I spent the time of running the two in parallel because it seemed to me that this was the idea of most of the people that wrote here. Now that I've done this it seems that the idea has changed to trash the old 1.x service and keep the 2.x. Maybe you guys should come to an agreement ;-)

**Comment by azazel75** [comment]
Uhumm, it seems I've made some serious errors in this branch while trying to rebasing it, I'm sorry. I'll try to fix it

**Comment by globin** [comment]
I would keep both modules for the next release (to be able to run them in parallel for one release), but with actually having copied the previous module (with intended code duplication). This will make it easier to just remove prometheus(1) after the next release and not having to disentangle them again by hand.

**Comment by azazel75** [comment]
Please see #49802

**Comment by benley** [comment]
mind if we close this PR since it looks like we're continuing over in the other one now?

**Pull request closed without merging**
