### PR TITLE
python311Packages.tensordict: 0.2.1 -> 0.3.0, python311Packages.torchrl: 0.2.1 -> 0.3.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog `tensordict`: https://github.com/pytorch/tensordict/releases/tag/v0.3.0
Changelog `torchrl`: https://github.com/pytorch/rl/releases/tag/v0.3.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by samuela — APPROVED** [review]
diff lgtm, happy to merge with a clean nixpkgs-review

**Comment by GaetanLepage** [comment]
Hmmm the tests seem to be very flaky.
I can build the package just fine from the checked out branch.
However, on the exact same machine, `nixpkgs-preview` is frozen (for several hours) at the beginning of tests:
```
============================= test session starts ==============================
platform linux -- Python 3.11.7, pytest-7.4.3, pluggy-1.3.0
rootdir: /build/source
configfile: pytest.ini
testpaths: test
plugins: rerunfailures-13.0
collected 15422 items / 432 deselected / 14990 selected                        
 
test/smoke_test.py .                                                     [  0%]
test/test_actors.py .................................................... [  0%]
 .........................s                                                            [  0%]
 ```

Any idea why this happens @vmoens ?

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 285297` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.tensordict</li>
    <li>python311Packages.tensordict.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> diff lgtm, happy to merge with a clean nixpkgs-review

All good now :)

**Pull request merged**
