### PR TITLE
nixos/unifi: fix unifi ExecStop= being incompatible with systemd

### PR DESCRIPTION
**Pull request by pennae**
###### Motivation for this change

unifi does not shut down properly when stopped via systemd (it always exits with
SIGTERM exit status) because systemd wants stop commands to not exit before the
main command is gone and unifi does not comply. the easiest way around this is
to have systemd send an ignored signal after the stop command has exited.

unifi may still throw exceptions during shutdown, but it *does* exit cleanly as
far as systemd is concerned now.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
I have trouble reproducing the issue, maybe because I tested this cherry-picked ontop of 21.05.

Without this patch:

```
$ systemctl stop unifi.service
...
Stopping UniFi controller daemon...
2021-10-13 20:21:12,739 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND
2021-10-13 20:21:15,169 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
unifi.service: Main process exited, code=exited, status=143/n/a
unifi.service: Failed with result 'exit-code'.
Stopped UniFi controller daemon.
unifi.service: Consumed 6h 11min 42.251s CPU time, read 2.2G from disk, written 14.5G to disk, received 1.7G IP traffic, sent 1.3G IP traffic.
```

With this patch:

```
Stopping UniFi controller daemon...
2021-10-13 20:26:43,604 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND
2021-10-13 20:26:47,747 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"
unifi.service: State 'stop-sigterm' timed out. Killing.
unifi.service: Killing process 830448 (java) with signal SIGKILL.
unifi.service: Killing process 830799 (mongod) with signal SIGKILL.
unifi.service: Killing process 830453 (java) with signal SIGKILL.
unifi.service: Killing process 830454 (java) with signal SIGKILL.
unifi.service: Killing process 830455 (java) with signal SIGKILL.
unifi.service: Killing process 830456 (java) with signal SIGKILL.
unifi.service: Killing process 830464 (VM Thread) with signal SIGKILL.
unifi.service: Killing process 830465 (Reference Handl) with signal SIGKILL.
unifi.service: Killing process 830466 (Finalizer) with signal SIGKILL.
unifi.service: Killing process 830469 (n/a) with signal SIGKILL.
unifi.service: Killing process 830470 (C2 CompilerThre) with signal SIGKILL.
unifi.service: Killing process 830471 (C2 CompilerThre) with signal SIGKILL.
unifi.service: Killing process 830472 (C1 CompilerThre) with signal SIGKILL.
unifi.service: Killing process 830474 (VM Periodic Tas) with signal SIGKILL.
unifi.service: Killing process 830564 (n/a) with signal SIGKILL.
unifi.service: Killing process 830565 (NioBlockingSele) with signal SIGKILL.
unifi.service: Killing process 830757 (db-server) with signal SIGKILL.
unifi.service: Killing process 830800 (n/a) with signal SIGKILL.
unifi.service: Killing process 830801 (n/a) with signal SIGKILL.
unifi.service: Killing process 830802 (n/a) with signal SIGKILL.
unifi.service: Killing process 830803 (n/a) with signal SIGKILL.
unifi.service: Killing process 830812 (n/a) with signal SIGKILL.
unifi.service: Killing process 830813 (n/a) with signal SIGKILL.
unifi.service: Killing process 830814 (n/a) with signal SIGKILL.
unifi.service: Killing process 830815 (mongod) with signal SIGKILL.
unifi.service: Killing process 830816 (n/a) with signal SIGKILL.
unifi.service: Killing process 830817 (mongod) with signal SIGKILL.
unifi.service: Killing process 830818 (n/a) with signal SIGKILL.
unifi.service: Killing process 830819 (n/a) with signal SIGKILL.
unifi.service: Killing process 830820 (n/a) with signal SIGKILL.
unifi.service: Killing process 830821 (n/a) with signal SIGKILL.
unifi.service: Killing process 830864 (n/a) with signal SIGKILL.
unifi.service: Killing process 830865 (n/a) with signal SIGKILL.
unifi.service: Killing process 830866 (n/a) with signal SIGKILL.
unifi.service: Killing process 830867 (n/a) with signal SIGKILL.
unifi.service: Killing process 830868 (n/a) with signal SIGKILL.
unifi.service: Killing process 830870 (n/a) with signal SIGKILL.
unifi.service: Killing process 830872 (n/a) with signal SIGKILL.
unifi.service: Killing process 830873 (n/a) with signal SIGKILL.
unifi.service: Killing process 830876 (n/a) with signal SIGKILL.
unifi.service: Killing process 830877 (n/a) with signal SIGKILL.
unifi.service: Killing process 830878 (n/a) with signal SIGKILL.
unifi.service: Killing process 830879 (n/a) with signal SIGKILL.
unifi.service: Killing process 830880 (n/a) with signal SIGKILL.
unifi.service: Killing process 830908 (n/a) with signal SIGKILL.
unifi.service: Killing process 830910 (n/a) with signal SIGKILL.
unifi.service: Killing process 830912 (n/a) with signal SIGKILL.
unifi.service: Killing process 830916 (n/a) with signal SIGKILL.
unifi.service: Killing process 830936 (n/a) with signal SIGKILL.
unifi.service: Killing process 830937 (n/a) with signal SIGKILL.
unifi.service: Killing process 830942 (n/a) with signal SIGKILL.
unifi.service: Killing process 830943 (n/a) with signal SIGKILL.
unifi.service: Killing process 830944 (n/a) with signal SIGKILL.
unifi.service: Killing process 830945 (n/a) with signal SIGKILL.
unifi.service: Killing process 830947 (n/a) with signal SIGKILL.
unifi.service: Killing process 830948 (n/a) with signal SIGKILL.
unifi.service: Killing process 830950 (n/a) with signal SIGKILL.
unifi.service: Killing process 830951 (n/a) with signal SIGKILL.
unifi.service: Killing process 830953 (n/a) with signal SIGKILL.
unifi.service: Killing process 830979 (n/a) with signal SIGKILL.
unifi.service: Killing process 830987 (n/a) with signal SIGKILL.
unifi.service: Killing process 831026 (n/a) with signal SIGKILL.
unifi.service: Killing process 831028 (n/a) with signal SIGKILL.
unifi.service: Killing process 831029 (n/a) with signal SIGKILL.
unifi.service: Killing process 831061 (n/a) with signal SIGKILL.
unifi.service: Killing process 831064 (n/a) with signal SIGKILL.
unifi.service: Killing process 831066 (n/a) with signal SIGKILL.
unifi.service: Killing process 831067 (n/a) with signal SIGKILL.
unifi.service: Killing process 831068 (n/a) with signal SIGKILL.
unifi.service: Killing process 831071 (n/a) with signal SIGKILL.
unifi.service: Killing process 831072 (n/a) with signal SIGKILL.
unifi.service: Killing process 831073 (n/a) with signal SIGKILL.
unifi.service: Killing process 831077 (n/a) with signal SIGKILL.
unifi.service: Killing process 831082 (NioBlockingSele) with signal SIGKILL.
unifi.service: Killing process 831083 (n/a) with signal SIGKILL.
unifi.service: Killing process 831084 (n/a) with signal SIGKILL.
unifi.service: Killing process 831085 (n/a) with signal SIGKILL.
unifi.service: Killing process 831086 (n/a) with signal SIGKILL.
unifi.service: Killing process 831087 (n/a) with signal SIGKILL.
unifi.service: Killing process 831088 (n/a) with signal SIGKILL.
unifi.service: Killing process 831089 (n/a) with signal SIGKILL.
unifi.service: Killing process 831091 (n/a) with signal SIGKILL.
unifi.service: Killing process 831092 (n/a) with signal SIGKILL.
unifi.service: Killing process 831093 (n/a) with signal SIGKILL.
unifi.service: Killing process 831094 (n/a) with signal SIGKILL.
unifi.service: Killing process 831095 (n/a) with signal SIGKILL.
unifi.service: Killing process 831096 (n/a) with signal SIGKILL.
unifi.service: Killing process 831132 (n/a) with signal SIGKILL.
unifi.service: Killing process 831135 (n/a) with signal SIGKILL.
unifi.service: Killing process 831136 (n/a) with signal SIGKILL.
unifi.service: Killing process 831137 (n/a) with signal SIGKILL.
unifi.service: Killing process 831139 (n/a) with signal SIGKILL.
unifi.service: Killing process 831140 (n/a) with signal SIGKILL.
unifi.service: Killing process 831142 (n/a) with signal SIGKILL.
unifi.service: Main process exited, code=killed, status=9/KILL
unifi.service: Failed with result 'timeout'.
Stopped UniFi controller daemon.
unifi.service: Consumed 4min 42.348s CPU time, read 4.0M from disk, written 0B to disk, received 592.2K IP traffic, sent 489.7K IP traffic.
```

Is `Failed with result 'exit-code'.` the error you want to fix?

**Review by erictapen — APPROVED** [review]
Thank you!

Also would you be interested in adding yourself as a maintainer to the package/module?

**Comment by pennae** [comment]
can do, but honestly we're a little scared of the commitment

**Comment by erictapen** [comment]
I see. Are you aware of what being a maintainer in Nixpkgs means? It doesn't really come with any responsibilities. The only thing that is going to happen is that people might ping you in issues und PRs. But as far as I can tell, nobody will really expect any work from you.

If you are in to the idea, you could open a new PR adding yourself as maintainer.

**Pull request merged**
