### PR TITLE
manga-tui: init at 0.2.0

### PR DESCRIPTION
**Pull request by isabelroses**
## Description of changes

adds https://github.com/josueBarretogit/manga-tui/tree/v0.2.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by isabelroses** [comment]
Result of `nixpkgs-review` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>manga-tui</li>
  </ul>
</details>

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>manga-tui</li>
  </ul>
</details>

**Comment by donovanglover** [comment]
Can we fix the ratatui stuff upstream so we don't need to include `Cargo.lock` for a [1 line diff](https://github.com/benjajaja/ratatui-image/commit/4d3f6eb2a454fa28e452e04a9b6c7579aef02939)?

- https://github.com/josueBarretogit/manga-tui/issues/5
- https://github.com/NixOS/nixpkgs/issues/327063

**Comment by isabelroses** [comment]
> Can we fix the ratatui stuff upstream so we don't need to include `Cargo.lock` for a [1 line diff](https://github.com/benjajaja/ratatui-image/commit/4d3f6eb2a454fa28e452e04a9b6c7579aef02939)?

I'm not sure if upstreaming that diff is even worth it. Because then we would be forcing lock ratui-image upstream to a singular version when they still support many.

**Comment by isabelroses** [comment]
> The program works and is interesting (to me at least) but like @donovanglover I am reluctant to merge these big lockfiles

could we refer to the lockfile as `${src}/Cargo.lock` or is that not valid?

**Comment by a-kenji** [comment]
> could we refer to the lockfile as `${src}/Cargo.lock` or is that not valid?

I am pretty sure that would be IFD and not allowed in `nixpkgs`.

**Review by a-kenji — APPROVED** [review]

**Comment by a-kenji** [comment]
Result of `nixpkgs-review pr 334706` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>manga-tui</li>
  </ul>
</details>

**Comment by donovanglover** [comment]
Sorry I meant fixing the problem causing the version to be held back. There should be multiple ways to solve this without a big `Cargo.lock` but I'm not sure how big the time commitment would be.

In the meantime I've asked upstream for their opinion here: https://github.com/josueBarretogit/manga-tui/issues/5#issuecomment-2297648037

**Comment by SuperSandro2000** [comment]
We have no way to avoid the lock files at this point, so what shell we do? When we have one we are going to slowly drop them

**Pull request merged**
