### PR TITLE
zoom-us: 5.1 -> 5.2

### PR DESCRIPTION
**Pull request by alevy**
###### Motivation for this change

New release of Zoom for Linux ([August 17th](https://support.zoom.us/hc/en-us/articles/205759689)) , just on time for the fall semester.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
The commit message should be just like the PR title, only with accurate versions near the `->`. Other then that LGTM, but I haven't tested it.

**Comment by doronbehar** [comment]
Additionally, I noticed that the updateScript doesn't work anymore, as they probably changed something in their infrastructure. This works:

```patch
diff --git i/pkgs/applications/networking/instant-messengers/zoom-us/update.sh w/pkgs/applications/networking/instant-messengers/zoom-us/update.sh
index 6214d4e2625..3476c17486a 100755
--- i/pkgs/applications/networking/instant-messengers/zoom-us/update.sh
+++ w/pkgs/applications/networking/instant-messengers/zoom-us/update.sh
@@ -1,10 +1,10 @@
 #!/usr/bin/env nix-shell
-#!nix-shell -i bash -p curl pcre common-updater-scripts
+#!nix-shell -i bash -p curl pup common-updater-scripts
 
 set -eu -o pipefail
 
 oldVersion=$(nix-instantiate --eval -E "with import ./. {}; lib.getVersion zoom-us" | tr -d '"')
-version="$(curl -sI https://zoom.us/client/latest/zoom_x86_64.tar.xz | grep -Fi 'Location:' | pcregrep -o1 '/(([0-9]\.?)+)/')"
+version="$(curl -Ls https://zoom.us/download\?os\=linux | pup '.linux-ver-text text{}' | cut -d' ' -f2)"
 
 if [ ! "${oldVersion}" = "${version}" ]; then
   update-source-version zoom-us "$version"

```

2 things this does:

- Adheres to the docs' recommendation saying this script should avoid running `git commit` commands etc ( https://nixos.org/manual/nixpkgs/stable/#var-passthru-updateScript).
- Use `pup` to parse html of download page.

**Comment by alevy** [comment]
Wow, that update script would have saved me a bunch of trouble yesterday, thanks @doronbehar!

I updated the commit message as suggested, included your changes to the update script, then updated again (there seems to be yet another minor version update). The _new_ new version builds and runs for me still on NixOS.

**Review by doronbehar — APPROVED** [review]
Works.

**Comment by mkg20001** [comment]
@doronbehar Your other PR is ahead a few versions of this PR https://github.com/NixOS/nixpkgs/pull/97543 but it doesn't include the update script

**Comment by doronbehar** [comment]
Right.. I forgot. @alevy could you give one more update here? I have commit permissions now :angel:.

**Comment by alevy** [comment]
Done. Thanks @mkg20001 & @doronbehar for triaging and congrats @doronbehar on commit permissions :) Zoom on NixOS is in good hands.

**Review by doronbehar — APPROVED** [review]

**Pull request merged**
