### PR TITLE
mesa: 23.3.5 -> 24.0.1

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

- enable nvk
- Rust is now mandatory
- drop merged Darwin fixes
- drop unnecessary musl patch
- clean up some outdated comments
- add some slightly less outdated (hopefully) comments

Supersedes #285595.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by PedroHLC — APPROVED** [review]
Diff LGTM

I cherry-picked it over nixpkgs-unstable where it build without issues:
```console
╰─λ nix build --no-link --print-out-paths .#mesa .#pkgsi686Linux.mesa
/nix/store/mh412wkav95jfklpzxqqr2v4arjdg61c-mesa-24.0.1
/nix/store/47sgns2slypdh4nxk3xxabpyflg8xyyk-mesa-24.0.1
```

**Review by jalil-salame — APPROVED** [review]

**Comment by beh-10257** [comment]
can enabling zink be considered

**Comment by vcunat** [comment]
This nix expression does explicitly enable it on *-linux.

**Comment by vcunat** [comment]
Man, memstream on x86_64-darwin again :-(
https://hydra.nixos.org/build/250348311/nixlog/1/tail

**Comment by veprbl** [comment]
> Man, memstream on x86_64-darwin again :-( https://hydra.nixos.org/build/250348311/nixlog/1/tail
> 
> EDIT: I fail to see why it happened this time.

This happened https://gitlab.freedesktop.org/mesa/mesa/-/commit/c0dd2eabaaca939883a6c9b73ea7bfc476907e36
Let's address that in #290525

**Comment by vcunat** [comment]
Hydra suggests that there might be some cross regressions:
https://hydra.nixos.org/job/nixpkgs/cross-trunk/aarch64-musl.mesa.x86_64-linux

**Comment by K900** [comment]
I tested cross to aarch64-glibc, so it's probably some musl thing.

**Comment by vcunat** [comment]
It's also possible that some unrelated change broke that build.

**Comment by alyssais** [comment]
I've confirmed that it was definitely this change.

**Comment by MrMonotone** [comment]
I am new to NixOS. Do the tests check if NVK can be enabled? I am doing the following to try to get it working:
```
  # Enable latest testing kernel (6.8 at writing)
  boot.kernelPackages = pkgs.linuxPackages_testing;
  
  # Enable Nvidia drivers
  boot.blacklistedKernelModules = [ "nvidia" "nvidia_uvm" ];
  boot.initrd.kernelModules = [ "nouveau" ];
  boot.kernelParams = [
    "nouveau.config=NvGspRm=1"
    "nouveau.debug=info,VBIOS=info,gsp=debug"
  ];
  services.xserver.enable = true;
  services.xserver.videoDrivers = lib.mkForce [ "modesetting" ];
  hardware.opengl = {
    enable = true;
    package = (pkgs.mesa.override {
      galliumDrivers = [
        "nouveau"
        "swrast"
        "zink" 
      ];
      vulkanDrivers = [
        "nouveau-experimental"
      ];
    }).drivers;
    driSupport = true;
    driSupport32Bit = true;
  };
  ```
  Mesa fails to build with:
  ```
  FAILED: src/gallium/targets/rusticl/libRusticlOpenCL.so.1.0.0 
g++  -o src/gallium/targets/rusticl/libRusticlOpenCL.so.1.0.0 src/gallium/targets/rusticl/libRusticlOpenCL.so.1.0.0.p/target.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libRusticlOpenCL.so.1 -Wl,--whole-archive src/gallium/frontends/rusticl/librusticl.a -Wl,--no-whole-archive src/gallium/auxiliary/pipe-loader/libpipe_loader_static.a src/loader/libloader.a src/util/libxmlconfig.a src/util/libmesa_util.a src/util/libmesa_util_sse41.a src/util/blake3/libblake3.a src/c11/impl/libmesa_util_c11.a src/gallium/winsys/sw/dri/libswdri.a src/gallium/winsys/sw/kms-dri/libswkmsdri.a src/gallium/winsys/sw/wrapper/libwsw.a src/gallium/winsys/sw/null/libws_null.a src/gallium/winsys/nouveau/drm/libnouveauwinsys.a src/nouveau/codegen/libnouveau_codegen.a src/gallium/drivers/nouveau/libnouveau.a src/compiler/nir/libnir.a src/compiler/libcompiler.a src/gallium/drivers/llvmpipe/libllvmpipe.a src/gallium/drivers/softpipe/libsoftpipe.a src/gallium/drivers/zink/libzink.a src/vulkan/util/libvulkan_util.a src/compiler/spirv/libvtn.a src/gallium/frontends/rusticl/liblibc_rust_gen.rlib src/gallium/frontends/rusticl/libmesa_rust.rlib src/gallium/frontends/rusticl/libmesa_rust_gen.rlib src/gallium/auxiliary/libgallium.a src/compiler/clc/liblibmesaclc.a src/gallium/frontends/rusticl/libmesa_rust_util.rlib src/gallium/frontends/rusticl/libmesa_bindings_inline_wrapper.a src/gallium/frontends/rusticl/libsystem_bindings.a src/gallium/frontends/rusticl/librusticl_llvm_gen.rlib src/gallium/frontends/rusticl/librusticl_opencl_gen.rlib -Wl,--build-id=sha1 -Wl,--gc-sections -Wl,--version-script /build/mesa-24.0.1/src/gallium/targets/rusticl/rusticl.sym /nix/store/bnqa606cwwff6ja8l6gz7milm7ajd1zi-zlib-1.3.1/lib/libz.so -pthread -lm /nix/store/yzizaw6wqqih1zkg9q1jv0zhj8ygqxb0-zstd-1.5.5/lib/libzstd.so /nix/store/40jzf109cfnjbysbwmvaxhf2bnlf7idm-libunwind-1.8.0/lib/libunwind.so -L/nix/store/ych6zj36nla5saw00n4cglx1kvxkdii7-llvm-16.0.6-lib/lib -lLLVM-16 /nix/store/0jpykszj3h71fmfajgfzmzr167qhak7p-libdrm-2.4.120/lib/libdrm.so /nix/store/rf6ks8cj035fc6p1prv6alvnl161hilr-expat-2.6.0/lib/libexpat.so /nix/store/klgd6i59s5dgdv9j8ka78s9ggqp8ijnk-libxcb-1.16/lib/libxcb.so /nix/store/klgd6i59s5dgdv9j8ka78s9ggqp8ijnk-libxcb-1.16/lib/libxcb-randr.so /nix/store/0jpykszj3h71fmfajgfzmzr167qhak7p-libdrm-2.4.120/lib/libdrm_nouveau.so -L/nix/store/ych6zj36nla5saw00n4cglx1kvxkdii7-llvm-16.0.6-lib/lib -lLLVM-16 /nix/store/zdvnf6b6w5sdgxbzg7v6yrlijml8y4yq-libX11-1.8.7/lib/libX11-xcb.so /nix/store/zdvnf6b6w5sdgxbzg7v6yrlijml8y4yq-libX11-1.8.7/lib/libX11.so /nix/store/klgd6i59s5dgdv9j8ka78s9ggqp8ijnk-libxcb-1.16/lib/libxcb-dri3.so /nix/store/klgd6i59s5dgdv9j8ka78s9ggqp8ijnk-libxcb-1.16/lib/libxcb-present.so /nix/store/klgd6i59s5dgdv9j8ka78s9ggqp8ijnk-libxcb-1.16/lib/libxcb-xfixes.so /nix/store/klgd6i59s5dgdv9j8ka78s9ggqp8ijnk-libxcb-1.16/lib/libxcb-sync.so /nix/store/klgd6i59s5dgdv9j8ka78s9ggqp8ijnk-libxcb-1.16/lib/libxcb-shm.so /nix/store/2ihac12p9427ggs7lpkn308zkgcr50lr-libxshmfence-1.3.2/lib/libxshmfence.so /nix/store/1iixlnbx1rh7mrwdr5javns99cylgikr-wayland-1.22.0/lib/libwayland-client.so /nix/store/xc853d005nwnwngz2fh9alsay280i5rr-libXrandr-1.5.4/lib/libXrandr.so -lrt -lpthread -ldl -lutil -fPIC -L/nix/store/ych6zj36nla5saw00n4cglx1kvxkdii7-llvm-16.0.6-lib/lib -lLLVM-16 -lsensors /nix/store/vh63gsw6420sfac6cky84yxb843cnm1r-clang-16.0.6-lib/lib/libclang-cpp.so -L/nix/store/ych6zj36nla5saw00n4cglx1kvxkdii7-llvm-16.0.6-lib/lib -lLLVM-16 /nix/store/0h7qs52bxvr5lmx7wwp07fc9x1p7gwjx-SPIRV-LLVM-Translator-16.0.0/lib/libLLVMSPIRVLib.so /nix/store/dhlnq63f0hh7xz2sdq92hqcna0jr9zs2-glslang-14.0.0/lib/libSPIRV-Tools-opt.a /nix/store/dhlnq63f0hh7xz2sdq92hqcna0jr9zs2-glslang-14.0.0/lib/libSPIRV-Tools.a /nix/store/dhlnq63f0hh7xz2sdq92hqcna0jr9zs2-glslang-14.0.0/lib/libSPIRV-Tools-link.a -Wl,--end-group
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nv50_nv84_video.c.o: in function `nv84_decoder_decode_bitstream_mpeg12':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nv50/nv84_video.c:174: undefined reference to `vl_mpg12_bs_decode'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nv50_nv84_video.c.o: in function `nv84_create_decoder':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nv50/nv84_video.c:319: undefined reference to `vl_mpg12_bs_init'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nv50_nv84_video.c.o: in function `nv84_video_buffer_create':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nv50/nv84_video.c:630: undefined reference to `vl_video_buffer_create'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nv50_nv84_video.c.o: in function `nv84_screen_video_supported':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nv50/nv84_video.c:873: undefined reference to `vl_video_buffer_is_format_supported'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nouveau_video.c.o: in function `nouveau_screen_get_video_param':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nouveau_video.c:857: undefined reference to `vl_video_buffer_max_size'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: /build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nouveau_video.c:867: undefined reference to `vl_level_supported'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nouveau_video.c.o: in function `nouveau_video_buffer_create':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nouveau_video.c:795: undefined reference to `vl_video_buffer_create'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nouveau_video.c.o: in function `nouveau_create_decoder':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nouveau_video.c:637: undefined reference to `vl_create_decoder'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nouveau_video.c.o: in function `nouveau_screen_init_vdec':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nouveau_video.c:878: undefined reference to `vl_video_buffer_is_format_supported'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nouveau_vp3_video.c.o: in function `nouveau_vp3_video_buffer_create':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nouveau_vp3_video.c:104: undefined reference to `vl_video_buffer_create'
/nix/store/p0p56gzz837fgmfd7lyisghcd7x2fdlc-binutils-2.40/bin/ld: src/gallium/drivers/nouveau/libnouveau.a.p/nouveau_vp3_video.c.o: in function `nouveau_vp3_screen_video_supported':
/build/mesa-24.0.1/build/../src/gallium/drivers/nouveau/nouveau_vp3_video.c:577: undefined reference to `vl_video_buffer_is_format_supported'
collect2: error: ld returned 1 exit status
[1975/1980] Linking target src/gallium/targets/d3dadapter9/d3dadapter9.so.1.0.0
[1976/1980] Linking target src/gallium/targets/dri/libgallium_dri.so
ninja: build stopped: subcommand failed.```

Unsure if I should create an issue or am doing something incorrect.

**Comment by K900** [comment]
You do not need to override Mesa, it will be built with NVK out of the box.

**Pull request merged**
