### PR TITLE
WIP m4: propagate native dependency

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

m4 was propagated as non-native dependency. This caused native builds to build fine, but cross to fail because of a missing m4.

Should we propagate m4 to begin with? If so, which one, or both?

Replaces https://github.com/NixOS/nixpkgs/pull/108044.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by prusnak — APPROVED** [review]
ACK on the hidapi change

**Comment by FRidh** [comment]
Note this now fails because of missing m4.

I recall the discussion once that packages that propagate and are used natively, would have their propagated dependencies be added as native.

**Comment by FRidh** [comment]
Main issue resolved with bf46afde6b22942ea605983f66ee23038986ba07

**Comment by Ericson2314** [comment]
> I recall the discussion once that packages that propagate and are used natively, would have their propagated dependencies be added as native.

That is true.

**Pull request closed without merging**
