### PR TITLE
sqldiff: init at 3.33.0

### PR DESCRIPTION
**Pull request by JohnAZoidberg**
###### Motivation for this change
It's part of the SQLite tools: https://www.sqlite.org/download.html, https://www.sqlite.org/sqldiff.html
and can be built from the sources that we already have.
It generates SQL statements that represent the difference of two SQLite databases.

@pesterhazy why did you add `lowPrio` to the `sqlite-analyzer` package?
It's not included in any other derivation, right?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by bdesham — COMMENTED** [review]
After making the changes in this review, these tools build and run for me on macOS 10.13. (I haven’t done a review before; I hope this is a helpful and non-obnoxious way to propose changes 😬)

**Comment by JohnAZoidberg** [comment]
Awesome, thanks! I committed it, with you (@bdesham) as author. Can you please verify whether I didn't make any mistakes?

**Comment by bdesham** [comment]
Yep, still works fine!

**Comment by pesterhazy** [comment]
I don’t remember anything about lowPrio, feel free to remove it

**Comment by JohnAZoidberg** [comment]
Upated, to bring up to date with sqlite proper.

**Comment by Lassulus** [comment]
sadly sqlite was bumped and the assertion fals

**Comment by doronbehar** [comment]
Pushed and rebased against latest master, with 3.33.0.

**Pull request merged**
