### PR TITLE
teller: fix build

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

add HOME=$(mktemp -d) in checkPhase

ZHF: #265948
https://hydra.nixos.org/build/239074453

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kirillrdy** [comment]
fails to build for me

```
$ nix build --nix-path nixpkgs=/home/kirillvr/.cache/nixpkgs-review/pr-266224/nixpkgs nixpkgs-overlays=/tmp/tmpagq3y_gq --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed -f /home/kirillvr/.cache/nixpkgs-review/pr-266224/build.nix
error: builder for '/nix/store/hrwa9lfb7ssyi0m54vg7jp5hi907kpyc-teller-1.5.6.drv' failed with exit code 2;
       last 10 log lines:
       >     --- PASS: TestE2E/Sh_print (0.01s)
       >     --- FAIL: TestE2E/scan_entries (0.01s)
       >     --- PASS: TestE2E/Put_with_--sync_flag (0.01s)
       >     --- PASS: TestE2E/Delete_multiple_entires (0.01s)
       >     --- PASS: TestE2E/yaml (0.01s)
       >     --- PASS: TestE2E/version (0.00s)
       > FAIL
       > FAIL      github.com/spectralops/teller/e2e       0.061s
       > FAIL
       > make: *** [Makefile:44: e2e] Error 1
       For full logs, run 'nix log /nix/store/hrwa9lfb7ssyi0m54vg7jp5hi907kpyc-teller-1.5.6.drv'.
error: 1 dependencies of derivation '/nix/store/81hxsw5y9sfp26023i91km865fwdgwnm-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/266224

1 package failed to build:
teller

```

**Comment by robert-manchester** [comment]
never saw that failure -- just fixed the one listed in the hydra log, which was reproducible on my machine (x64 linux)
https://hydra.nixos.org/log/zbm3v2yyvdkzl9gyaqdb6hcggzwsh6a7-teller-1.5.6.drv

**Comment by kirillrdy** [comment]
> never saw that failure -- just fixed the one listed in the hydra log, which was reproducible on my machine (x64 linux) https://hydra.nixos.org/log/zbm3v2yyvdkzl9gyaqdb6hcggzwsh6a7-teller-1.5.6.drv

my is also x86_64-linux, let me try using your commit instead of a merge

**Comment by kirillrdy** [comment]
> > never saw that failure -- just fixed the one listed in the hydra log, which was reproducible on my machine (x64 linux) https://hydra.nixos.org/log/zbm3v2yyvdkzl9gyaqdb6hcggzwsh6a7-teller-1.5.6.drv
> 
> my is also x86_64-linux, let me try using your commit instead of a merge

@robert-manchester you commit indeed builds ,but merge fails ( i tried two times with same error )

rebase on master, you should get same error

**Comment by robert-manchester** [comment]
> > > never saw that failure -- just fixed the one listed in the hydra log, which was reproducible on my machine (x64 linux) https://hydra.nixos.org/log/zbm3v2yyvdkzl9gyaqdb6hcggzwsh6a7-teller-1.5.6.drv
> > 
> > 
> > my is also x86_64-linux, let me try using your commit instead of a merge
> 
> @robert-manchester you commit indeed builds ,but merge fails ( i tried two times with same error )
> 
> rebase on master, you should get same error

the PR is only 50 commits off master. i did pull master in and rebase and still can not reproduce the error you have above. can only reproduce the error from hydra without my change.

**Comment by kirillrdy** [comment]
> > > > never saw that failure -- just fixed the one listed in the hydra log, which was reproducible on my machine (x64 linux) https://hydra.nixos.org/log/zbm3v2yyvdkzl9gyaqdb6hcggzwsh6a7-teller-1.5.6.drv
> > > 
> > > 
> > > my is also x86_64-linux, let me try using your commit instead of a merge
> > 
> > 
> > @robert-manchester you commit indeed builds ,but merge fails ( i tried two times with same error )
> > rebase on master, you should get same error
> 
> the PR is only 50 commits off master. i did pull master in and rebase and still can not reproduce the error you have above. can only reproduce the error from hydra without my change.

can you try running `nixpkgs-review pr 266224` ?

**Comment by robert-manchester** [comment]
```
nix run .\#nixpkgs-review pr 266224 -- --print-result
```
Result of `nixpkgs-review pr 266224` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>teller</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
> nix run .\#nixpkgs-review pr 266224 -- --print-result

facinating !

`nix run .\#nixpkgs-review pr 266224 -- --print-result` passes for me

locally I would think it should be
```
nix run .\#nixpkgs-review -- pr 266224 --print-result
```

**Comment by kirillrdy** [comment]
@robert-manchester 

```
nixpkgs-review pr 266224
```
is passing for me now

is it possible that we had a regression in those 50 commits ?

**Review by wahtique — APPROVED** [review]

**Comment by wamserma** [comment]
Result of `nixpkgs-review pr 266224` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>teller</li>
  </ul>
</details>

**Review by wamserma — APPROVED** [review]

**Comment by robert-manchester** [comment]
> @robert-manchester
> 
> ```
> nixpkgs-review pr 266224
> ```
> 
> is passing for me now
> 
> is it possible that we had a regression in those 50 commits ?

i did not modify the PR to merge in master. there is one force push but that happened 5 min after i created the PR and I just put "" around the subshell. either you were triggering a different issue or there is something going on with your setup. either way, seems unrelated to this change.

**Pull request merged**
