### PR TITLE
Animdl

### PR DESCRIPTION
**Pull request by PassiveLemon**
###### Things done
Adds Animdl, a CLI scraper/streamer/downloader for anime.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Janik-Haag — COMMENTED** [review]
Does your IDE do some kind of autoformating or change the line ending or something like that because you changed every line in the `pkgs/top-level/all-packages.nix`?

**Comment by Janik-Haag** [comment]
yup seems like your editor uses another line ending: 
image

**Comment by PassiveLemon** [comment]
That's weird, I uploaded that with the GitHub editor since the repo is so big that I have trouble cloning it. I'll try again

**Comment by Janik-Haag** [comment]
Hm can why can't you clone the repo? What is the error you get?

**Comment by PassiveLemon** [comment]
I can clone it with a depth of 1, but trying to then publish the branch I made for this PR, just stops while uploading. It might be the GitHub app doing that so I'm trying to figure this out with CLI commands.

**Comment by PassiveLemon** [comment]
I didn't mean to do that. I'll reupload the PR once I get this figured out.

**Comment by Janik-Haag** [comment]
hm okay wired. Feel free to ping me in your new PR for a review.

**Pull request closed without merging**
