### PR TITLE
quantlib: 1.34 -> 1.35

### PR DESCRIPTION
**Pull request by Kupac**
## Description of changes

Upgrade quantlib and RQuantLib.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by b-rodrigues — APPROVED** [review]
Result of `nixpkgs-review pr 329781` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>quantlib</li>
    <li>quantlib.dev</li>
  </ul>
</details>


Tested the demo from the Github repo, LGTM!

**Comment by jbedo** [comment]
Everything looks fine to me and I don't see such the high memory usage mentioned on Matrix when compiling:
```
peak_rss           2.13GB ±  365KB
```
I'm possibly measuring it incorrectly. @b-rodrigues would you be able to build `rPackages.RQuantLib` to double check?

**Comment by b-rodrigues** [comment]
RAM usage during most of the process stayed between 5 to 9 gigs, but at some point, towards the end, it did reach 23 gigs for some time and then decrease to around 11 gigs until it was finished.

**Comment by Kupac** [comment]
That means it's OK to merge, or the `Set pending OfBorg status` is a problem?

**Comment by jbedo** [comment]
> That means it's OK to merge, or the `Set pending OfBorg status` is a problem?

That's fine, the darwin build seems broken but looking at the logs I don't know how to resolve it.

**Comment by adamcstephens** [comment]
This will need a rebase.

**Comment by Kupac** [comment]
OK, rebase done. I removed the rPackages.RQuantlib part, because it's been already updated in master.

**Comment by Kupac** [comment]
@ofborg build rPackages.RQuantLib

**Pull request merged**
