### PR TITLE
mypaint: 1.2.1 → 2.0.0-beta.0

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
works with python 3 and contains cool new brushes

cc @cillianderoiste 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
GIMP will need to be patched to support mypaint-brushes-2.0

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by jtojnar** [comment]
https://github.com/mypaint/mypaint/commit/bbd032445147a3ba50739cad121fa796519b07c0 in mypaint 2.0.0-alpha.11 requires https://github.com/mypaint/libmypaint/commit/635975da059506c970561e2af5ac6652401b87ac, which is not released yet.

**Comment by jtojnar** [comment]
Two new alphas since the last time http://mypaint.org/blog/2019/11/09/mypaint-2.0-alpha13/, https://github.com/mypaint/mypaint/releases/tag/v2.0.0-alpha.13

**Comment by jtojnar** [comment]
Just pasting here that [beta.0](https://github.com/mypaint/mypaint/releases/tag/v2.0.0-beta.0) has been released with stable expected at the end of January. Do not have time to bump and test it at the moment.

**Comment by jtojnar** [comment]
Delayed for week or two: http://mypaint.org/blog/2020/01/31/mypaint-2.0-postponement/

**Comment by sikmir** [comment]
[MyPaint v2.0.0 (2020-02-15)](https://github.com/mypaint/mypaint/releases/tag/v2.0.0) is out.

**Comment by sikmir** [comment]
@jtojnar Something going wrong with mypaint-2.0.0:
```sh
$  mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/nix/store/xwb4dp2s4fzmgxsz4946axgbv966n2z5-mypaint-2.0.0'
WARNING: gui.userconfig: Failed to load settings file: /home/sikmir/.config/mypaint/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: POSIX: LANG='fi_FI.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None

(.mypaint-wrapped:8116): Gtk-WARNING **: 14:41:14.015: Could not find the icon 'org.mypaint.MyPaint'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
ERROR: gui.application: Missing icon 'org.mypaint.MyPaint': check that mypaint icons have been installed into /nix/store/xwb4dp2s4fzmgxsz4946axgbv966n2z5-mypaint-2.0.0/share/icons
Traceback (most recent call last):
  File "/nix/store/xwb4dp2s4fzmgxsz4946axgbv966n2z5-mypaint-2.0.0/lib/mypaint/gui/application.py", line 133, in _init_icons
    icon_theme.load_icon(icon_name, 32, 0)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Kuvake 'org.mypaint.MyPaint' ei ole osana teemaa Adwaita (0)
ERROR: gui.application: Missing icon 'mypaint-brush-symbolic': check that librsvg is installed, and update loaders.cache
Traceback (most recent call last):
  File "/nix/store/xwb4dp2s4fzmgxsz4946axgbv966n2z5-mypaint-2.0.0/lib/mypaint/gui/application.py", line 133, in _init_icons
    icon_theme.load_icon(icon_name, 32, 0)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Kuvake 'mypaint-brush-symbolic' ei ole osana teemaa Adwaita (0)
CRITICAL: gui.application: Required icon(s) missing
ERROR: gui.application: Icon search path: ['/home/sikmir/.local/share/icons', '/home/sikmir/.icons', '/nix/store/xwb4dp2s4fzmgxsz4946axgbv966n2z5-mypaint-2.0.0/share/icons', '/nix/store/w6cqc17j0b9ibrnaa5zmfyy251r57hhm-gtk+3-3.24.14/share/gsettings-schemas/gtk+3-3.24.14/icons', '/nix/store/1xfwclrqkyxllnh8x549lj5ywn541kym-gsettings-desktop-schemas-3.34.0/share/gsettings-schemas/gsettings-desktop-schemas-3.34.0/icons', '/nix/store/1xfwclrqkyxllnh8x549lj5ywn541kym-gsettings-desktop-schemas-3.34.0/share/gsettings-schemas/gsettings-desktop-schemas-3.34.0/icons', '/nix/store/w6cqc17j0b9ibrnaa5zmfyy251r57hhm-gtk+3-3.24.14/share/gsettings-schemas/gtk+3-3.24.14/icons', '/home/sikmir/.nix-profile/share/icons', '/etc/profiles/per-user/sikmir/share/icons', '/nix/var/nix/profiles/default/share/icons', '/run/current-system/sw/share/icons', '/nix/store/xwb4dp2s4fzmgxsz4946axgbv966n2z5-mypaint-2.0.0/share/pixmaps', '/nix/store/w6cqc17j0b9ibrnaa5zmfyy251r57hhm-gtk+3-3.24.14/share/gsettings-schemas/gtk+3-3.24.14/pixmaps', '/nix/store/1xfwclrqkyxllnh8x549lj5ywn541kym-gsettings-desktop-schemas-3.34.0/share/gsettings-schemas/gsettings-desktop-schemas-3.34.0/pixmaps', '/nix/store/1xfwclrqkyxllnh8x549lj5ywn541kym-gsettings-desktop-schemas-3.34.0/share/gsettings-schemas/gsettings-desktop-schemas-3.34.0/pixmaps', '/nix/store/w6cqc17j0b9ibrnaa5zmfyy251r57hhm-gtk+3-3.24.14/share/gsettings-schemas/gtk+3-3.24.14/pixmaps', '/home/sikmir/.nix-profile/share/pixmaps', '/etc/profiles/per-user/sikmir/share/pixmaps', '/nix/var/nix/profiles/default/share/pixmaps', '/run/current-system/sw/share/pixmaps', '/nix/store/xwb4dp2s4fzmgxsz4946axgbv966n2z5-mypaint-2.0.0/share/icons']
ERROR: gui.application: MyPaint can't run sensibly without its icons; please check your installation. See https://github.com/mypaint/mypaint/wiki/FAQ-Missing-icons for possible solutions.
```

**Comment by jtojnar** [comment]
Do you have icons installed? See https://nixos.wiki/wiki/GNOME#Running_GNOME_programs_outside_of_GNOME

**Comment by sikmir** [comment]
Yes, I have `gnome3.adwaita-icon-theme` installed.

**Comment by jtojnar** [comment]
Do you have `gtk.iconCache.enable` option enabled?

**Comment by sikmir** [comment]
I've enabled `gtk.iconCache.enable`, but doesn't help(

**Comment by jtojnar** [comment]
I managed to reproduce it using `env XDG_DATA_DIRS= $(nix-build -A mypaint --no-out-link)/bin/mypaint` and fix it using `env XDG_DATA_DIRS=$(nix-build -A hicolor-icon-theme --no-out-link)/share $(nix-build -A mypaint --no-out-link)/bin/mypaint`. Should be fixed by #97416.

**Pull request merged**
