### PR TITLE
nixos/nbd: fix nbd-server config section ordering

### LINKED ISSUE #169103: services.nbd.server generates broken configuration
### Describe the bug

Configuration snippet like this:

```nix
{ config, lib, ... }:

{
  services.nbd.server = {
    enable = (lib.length (lib.attrNames config.services.nbd.server.exports)) > 0;
    listenAddress = "0.0.0.0";

    exports = {
      aarch64-ubuntu = {
        path = "/dev/zvol/htank/nbd/aarch64-ubuntu";
        allowAddresses = [ "10.122.0.0/24" ];
      };
      x86_64-ubuntu = {
        path = "/dev/zvol/htank/nbd/x86_64-ubuntu";
        allowAddresses = [ "10.122.0.0/24" ];
      };      
    };
  };
}
```
...will yield a configuration like:

```ini
[aarch64-ubuntu]
;; ...

[general]
;; ...

[x86_64-ubuntu]
;; ...
```

However nbd-server expects `[general]` section to always appear before export sections, otherwise it complains about not being able to find general section. I'd say this is upstream's fault because this order should not matter, but here we are.

### Expected behavior

`[general]` section to always appear before export sections.

### Notify maintainers

@scvalex 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.0, NixOS, 22.05 (Quokka), 22.05.20220325.30d3d79`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `""`
 - channels(mark): `""`
 - nixpkgs: `/nix/store/m2vv0bxfchzrjngx8wi0i7dhzb9q2g50-source`
```

### PR DESCRIPTION
**Pull request by scvalex**
Closes #169103

###### Description of changes

The config for `nbd-server` is an INI file, but it turns out the server will fail to start if the first section isn't the `[generic]` one.  This PR changes the way `services.nbd.server` generates the config to ensure `[generic]` is always first.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by scvalex** [comment]
@ofborg eval

**Comment by scvalex** [comment]
@pennae Would you be up for reviewing this nbd service PR?

**Review by pennae — COMMENTED** [review]
lgtm, but saying that nbd-server *fails* is a bit harsh considering that the documentation explicitly states that `generic` must be the first section. might also make sense to disallow exports named `generic` though, because when those exist it *does* fail (the server seems to completely ignore the second `generic` section)

**Comment by scvalex** [comment]
Ah.  I meant "fail to start" in the sense of "refuses to start" and "doesn't start".

I've added the assertion to disallow exports named "generic".

**Comment by scvalex** [comment]
Thank you!

**Pull request merged**
