### PR TITLE
 thunderbird, thunderbird-bin: 68.7.0 -> 68.8.0 

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Various security fixes (the security advisories are not updated yet)
- Other fixes

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by lovesegfault — APPROVED** [review]
:shipit:

**Comment by lovesegfault** [comment]
ping @vcunat

**Review by vcunat — APPROVED** [review]
On a quick try they appear to work fine.

**Comment by vcunat** [comment]
It has some "critical" security fixes.
https://www.thunderbird.net/en-US/thunderbird/68.8.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2020-18/

**Comment by vcunat** [comment]
It's in all the three branches now.

**Pull request merged**
