### PR TITLE
[20.09] privoxy: 3.0.28 -> 3.0.32

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change

Fix https://github.com/NixOS/nixpkgs/issues/128418

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via backporting `nixosTests.privoxy`
- [x] Tested compilation of all pkgs that depend on this change (`privoxy`)
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Why are we bumping all the way to 3.0.32 if the fix is in 3.0.29?

**Comment by rnhmjoj** [comment]
There are a more bug fixes and no breaking changes.

**Comment by cole-h** [comment]
@ofborg eval

(Sorry, ofborg's certs recently had an issue, meaning that it was unable to
react to PRs. This has been fixed, but all PRs filed in this period will need
ofborg to be manually kicked off.)

**Comment by rnhmjoj** [comment]
@cole-h Thank you!

**Pull request merged**
