### PR TITLE
pythonPackages: default to qt514

### PR DESCRIPTION
**Pull request by Galagora**
###### Motivation for this change
Essentially a partial revert of the changes made https://github.com/NixOS/nixpkgs/pull/97586, which fixes Python QT packages that aren't wrapped well and leaves the version configurability for those that are. This should sort out the likes of #98067 and #98069. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gebner** [comment]
FreeCAD is also broken for this reason.  It currently uses `libsForQt514`, but this breaks when using pyside2 built with Qt 5.15.  Upgrading to Qt 5.15 isn't straightforward either, because qtwebkit doesn't build.

**Comment by gebner** [comment]
cc @petabyteboy @ttuegel @raboof

**Comment by galagora** [comment]
Fixed.

**Comment by FRidh** [comment]
a4e50bb197f032ec447a13f56910ff035b32017f reverted the use of 5.15 everywhere. qt version can now be set per application by overriding `pkgs` c88f3adb1793cd3b007baff0292cf1fa8d0ab1e6. See qutebrowser as example 2daf5702c6d059976e203f2eab7ccb539dd9274d.

**Comment by gebner** [comment]
@FRidh The override doesn't seem to work for me at all (this is on current master):
```
$ nix repl .
nix-repl> python38Packages.pyqt5.buildInputs
[ «derivation /nix/store/sgkk9zpr8ans81f0g5wpi5y6yy0inq1s-dbus-1.12.20.drv»
  «derivation /nix/store/2i6wvm2jqw83qq7rcsh7acdkyisdc3bw-qtbase-5.15.0.drv»
  «derivation /nix/store/q0fg5km866036a1y86rw4bp572v7pwyx-qtsvg-5.15.0.drv»
  «derivation /nix/store/wa02900pzn8q4ylkpkzyh1bsbzgfbv6r-qtdeclarative-5.15.0.drv» ]

nix-repl> python38Packages.shiboken2.buildInputs
[ «derivation /nix/store/qfkak7qkx2cgwqrs9qy275dxfd501c5z-clang-7.1.0.drv»
  «derivation /nix/store/xy9dx0qx4gcnph7bz0g6d616ls5vm0j6-python3-3.8.5.drv»
  «derivation /nix/store/2i6wvm2jqw83qq7rcsh7acdkyisdc3bw-qtbase-5.15.0.drv»
  «derivation /nix/store/2kdzq789vahilya85jbwd1dipazvnx9g-qtxmlpatterns-5.15.0.drv» ]
```

**Comment by FRidh** [comment]
Yes, I did not test it correctly. See the discussion in https://github.com/NixOS/nixpkgs/pull/98197.

**Pull request closed without merging**
