### PR TITLE
keybase, keybase-gui, kbfs: 4.6.0 -> 4.7.2, added dependencies

### PR DESCRIPTION
**Pull request by judaew**
###### Motivation for this change
Adding:
- `fuse` or `osxfuse` as a dependency for `kbfs` (I rely on this [kbfs README.md#status](https://github.com/keybase/client/tree/master/go/kbfs#status))
- `gnupg` as a dependency for `keybase` (for command `$ keybase pgp gen`)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
@judaew Are these used during the build, or are the executable needed in PATH during runtime?
If so we need to hardcode the paths in the source code.

**Comment by judaew** [comment]
@worldofpeace Yes, executables are needed at runtime. I analyzed the code and I came to the conclusion that Keybase already has GnuPG support for Nix ([pinentry_nix.go](https://github.com/keybase/client/blob/master/go/pinentry/pinentry_nix.go)).

I was a little skeptical about `fuse`. But the experiment showed that PATH is found automatically. I previously removed `fuse` from Ubuntu and verified that `kbfs` is not working properly because of this. 

But I'm not sure about `osxfuse`, since these lines use the native osxfuse [options.go#L280-L293](https://github.com/keybase/client/blob/master/go/vendor/bazil.org/fuse/options.go#L280-L293) and maybe function in L303-313 will use osxfuse from Nix (if the native will be unavailable). I think it should work both ways.

**Comment by worldofpeace** [comment]
Well what I meant by this was, if the program needs executables from fuse to be present at runtime like
```
result/bin
├── fusermount
├── mount.fuse
└── ulockmgr_server
```

they won't be there even if they're added to `buildInputs`. They'll just be in `PATH` during the build.

Nix doesn't really manage things in this way, though perhaps it should/could. 
So what usually has to be done is substitute the calls to any of those executables with a hardcoded path within the nix store. Here's a precise example of what I usually request people to perform 
* https://github.com/NixOS/nixpkgs/pull/70512#pullrequestreview-297842523

Though I believe this approach would be rather difficult if they were to switch to go modules, or not vendor things.

---

There also seems to be some assumptions going for macos
* https://github.com/keybase/client/blob/master/go/vendor/bazil.org/fuse/options.go#L279-L293

Now if nix was sandboxed these wouldn't work because they're on the host system, but I believe with macos it would be on the safe side to just rely on these being present outside of nix.

**Comment by judaew** [comment]
Something just like this?

**Review by worldofpeace — APPROVED** [review]
It does appear you've performed the patch correctly. Will test.

**Review by ghost — APPROVED** [review]

**Comment by worldofpeace** [comment]
@judaew If you can squash your commits accordingly I can merge.

**Comment by judaew** [comment]
@worldofpeace Good, I did it.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build keybase kbfs keybase-gui

**Comment by worldofpeace** [comment]
Running checks for darwin. I had to update the keybase-gui expression because it 404'd for me.

**Comment by worldofpeace** [comment]
Thanks for your patience @judaew and the contributions :sparkles:

**Comment by judaew** [comment]
Thanks for your help @worldofpeace

**Pull request merged**
