### PR TITLE
python3Packages.[psautohint, afdko]: disable slow & failing tests

### PR DESCRIPTION
**Pull request by drewrisinger**
###### Motivation for this change

When building a NixOS build on Raspberry Pi, found that ``python3Packages.psautohint`` was taking FAR too long to build (~5 mins for native x86 build). This disables the slowest tests and fixes up a few minor issues.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Can you please squash the commits together to one per package?

**Review by sternenseemann — COMMENTED** [review]
Thanks for identifying the flaky test! I was meaning to do that.

I'm personally not too concerned about build times, but I don't think there's a reason why we absolutely _have_ to enable all tests.

How come you had to build `psautohint` btw? I was under the impression `psautohint` would only need to be built if you'd have to build `noto-fonts-emoji` or `twitter-color-emoji` from scratch…

**Comment by sternenseemann** [comment]
Result of `nixpkgs-review pr 106464` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>noto-fonts-emoji</li>
    <li>python37Packages.afdko</li>
    <li>python37Packages.nototools</li>
    <li>python37Packages.psautohint</li>
    <li>python38Packages.afdko</li>
    <li>python38Packages.nototools</li>
    <li>python38Packages.psautohint</li>
    <li>python39Packages.afdko</li>
    <li>python39Packages.nototools</li>
    <li>python39Packages.psautohint</li>
    <li>twitter-color-emoji</li>
  </ul>
</details>

**Comment by drewrisinger** [comment]
@sternenseemann I'm working on bringing up a Raspberry Pi 4 on NixOS, and the default fonts include ``noto-color-emoji``, and ``pythonPackages.psautohint`` somehow needs recompiled for the Raspberry Pi kernel (since that hasn't been transitioned yet to mainline Linux :shrug:). I didn't work out the exact dependencies. After this PR, I actually just ended up disabling ``noto-fonts-emoji`` b/c that took a VERY long time to build when cross-compiling.

**Comment by sternenseemann** [comment]
Makes sense!  The build process of `noto-fonts-emoji` (and `twitter-color-emoji` as a matter of fact) are extremely slow indeed.

Concerning the test suites: As said I don't really have an opinion on whether we should disable tests to reduce build time. As I don't have push access I'm automatically relieved of this decision at least :) 

We should however definitely disable `test_hashmap_old_version` in `psautohint`.

**Comment by drewrisinger** [comment]
@sternenseemann It'd probably help those w/ push access to merge this PR if you leave an explicit "approval" review, including your qualms about disabling some tests so they have the full context.

**Review by sternenseemann — APPROVED** [review]
We should however definitely disable `test_hashmap_old_version` in psautohint until the issue is resolved upstream.

I'm indifferent about disabling tests for build speed reasons.

**Comment by sternenseemann** [comment]
Upstream suggests that `test_hashmap_old_version` fails due to a change in pytest 6. Due to `pytestCheckHook` however you can't switch to pytest 5 if I see things correctly in this PR. An alternative solution to this issue would be #106609.

**Comment by drewrisinger** [comment]
@sternenseemann Alternatively, you CAN override ``pytestCheckHook``:

```nix
{
  ...
  checkInputs = [ (pytestCheckHook.override{ pytest = pytest_5; }) pytestcov pytest_xdist ];
  ...
}
```
Builds cleanly for me.

**Review by sternenseemann — APPROVED** [review]

**Comment by drewrisinger** [comment]
Closes #106558

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106464` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>noto-fonts-emoji</li>
    <li>python37Packages.afdko</li>
    <li>python37Packages.nototools</li>
    <li>python37Packages.psautohint</li>
    <li>python38Packages.afdko</li>
    <li>python38Packages.nototools</li>
    <li>python38Packages.psautohint</li>
    <li>python39Packages.afdko</li>
    <li>python39Packages.nototools</li>
    <li>python39Packages.psautohint</li>
    <li>twitter-color-emoji</li>
  </ul>
</details>

**Pull request merged**
