### PR TITLE
python3Packages.catboost: 1.0.5 -> 1.1.1, use ya.make

### PR DESCRIPTION
**Pull request by veprbl**
Switching to ya allows to do darwin build and fixes the cython issue (which, despite what the comment says, is not limited to the withCuda=true).

The resulting package doesn't build on darwin with sandbox, as ya-bin tool contains frozen python2 executable, which requires /usr/sbin/sysctl to detect number of CPUs in the multiprocessing module.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nviets** [comment]
Does this PR build catboost's [CLI version](https://catboost.ai/en/docs/installation/cli-installation-local-copy-installation), too? The is also an R library, which has a custom build that isn't in CRAN. If all three share the same binary shared object, could catboost be split into a library and package interfaces, similarly to how xbgoost is built in nixpkgs([library](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/xgboost/default.nix) and [python package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/xgboost/default.nix))

**Comment by nviets** [comment]
I tried building branch on aarch64-darwin, but it's failing on an IOError message. Any tips on what needs to change?

```
...
Debug: Timer get_version_info, stage vcs info: 0.0197620391846
Debug: Use conf from /private/tmp/nix-build-python3.10-catboost-1.1.1.drv-0/source/build/external_resources/ymake/resources.json
Debug: ymake: try to fetch by {'linux-ppc64le': {'uri': 'sbr:3713891164'}, 'darwin-arm64': {'uri': 'sbr:3713897652'}, 'darwin': {'uri': 'sbr:3713898277'}, 'win32-clang-cl': {'uri': 'sbr:3713894652'}, 'linux': {'uri': 'sbr:3713894735'}} for 'darwin'
Debug: ymake: will use 'darwin' platform
Debug: Fetching 3713898277 from sbr:3713898277 to /nix/store/k33axkj5vvq35b7iyq5njpf52ysl613s-catboost-ya-cache-1.1.1/tools/v3/3713898277 dir, post_process=0)
Debug: Use conf from /private/tmp/nix-build-python3.10-catboost-1.1.1.drv-0/source/build/mapping.conf.json
Debug: Running future at __exit__: ({'pattern': 'VCS', 'resource': 'base64:vcs.json:ewogICAgIkFSQ0FESUFfUEFUQ0hfTlVNQkVSIjogMCwKICAgICJBUkNBRElBX1NPVVJDRV9IR19IQVNIIjogIjA1NzcyMTU2NjQ5MDE1MzI4NjA2MDY1MTIwOTAwODI0MDI0MzEwNDIiLAogICAgIkFSQ0FESUFfU09VUkNFX0xBU1RfQVVUSE9SIjogIm9yZGluYWwiLAogICAgIkFSQ0FESUFfU09VUkNFX0xBU1RfQ0hBTkdFIjogLTEsCiAgICAiQVJDQURJQV9TT1VSQ0VfUEFUSCI6ICIiLAogICAgIkFSQ0FESUFfU09VUkNFX1JFVklTSU9OIjogLTEsCiAgICAiQVJDQURJQV9TT1VSQ0VfVVJMIjogIiIsCiAgICAiQVJDQURJQV9UQUciOiAiIiwKICAgICJCUkFOQ0giOiAidW5rbm93bi12Y3MtYnJhbmNoIiwKICAgICJCVUlMRF9EQVRFIjogIjIwMjMtMDEtMjhUMjA6NDU6NDYuMDAwMDAwWiIsCiAgICAiQlVJTERfSE9TVCI6ICJNYWNCb29rIiwKICAgICJCVUlMRF9USU1FU1RBTVAiOiAxNjc0OTM4NzQ2LAogICAgIkJVSUxEX1VTRVIiOiAiVW5rbm93biB1c2VyIiwKICAgICJESVJUWSI6ICIiLAogICAgIlBST0dSQU1fVkVSU0lPTiI6ICJBcmMgaW5mbzpcbiAgICBCcmFuY2g6IHVua25vd24tdmNzLWJyYW5jaFxuICAgIENvbW1pdDogMDU3NzIxNTY2NDkwMTUzMjg2MDYwNjUxMjA5MDA4MjQwMjQzMTA0MlxuICAgIEF1dGhvcjogb3JkaW5hbFxuICAgIFN1bW1hcnk6IE5vIFZDU1xuXG5PdGhlciBpbmZvOlxuICAgIEJ1aWxkIGJ5OiBVbmtub3duIHVzZXJcbiAgICBUb3Agc3JjIGRpcjogXG4gICAgVG9wIGJ1aWxkIGRpcjogL3ByaXZhdGUvdG1wL25peC1idWlsZC1weXRob24zLjEwLWNhdGJvb3N0LTEuMS4xLmRydi0wL3RtcC5NQXRURlFyb1l0L2J1aWxkXG4gICAgSG9zdG5hbWU6IE1hY0Jvb2tcbiAgICBIb3N0IGluZm9ybWF0aW9uOiBcbiAgICAgICAgRGFyd2luIE1hY0Jvb2sgMjIuMi4wIERhcndpbiBLZXJuZWwgVmVyc2lvbiAyMi4yLjA6IEZyaSBOb3YgMTEgMDI6MDQ6NDQgUFNUIDIwMjI7IHJvb3Q6eG51LTg3OTIuNjEuMn40L1JFTEVBU0VfQVJNNjRfVDgxMDMgeDg2XzY0XG5cbiAgICAiLAogICAgIlNDTV9EQVRBIjogIkFyYyBpbmZvOlxuICAgIEJyYW5jaDogdW5rbm93bi12Y3MtYnJhbmNoXG4gICAgQ29tbWl0OiAwNTc3MjE1NjY0OTAxNTMyODYwNjA2NTEyMDkwMDgyNDAyNDMxMDQyXG4gICAgQXV0aG9yOiBvcmRpbmFsXG4gICAgU3VtbWFyeTogTm8gVkNTXG4iLAogICAgIlZDUyI6ICJhcmMiCn0=', 'name': 'vcs'}, None), unwinding (<type 'exceptions.IOError'>, IOError(13, 'Permission denied'), <traceback object at 0x115af6be0>)
Debug: Module "dump_debug" stopped in 0.000028
...
```

**Comment by veprbl** [comment]
As-is this is only working without sandboxing. A more isolated build would require fixing external dependencies, like it's done with bazel.

**Comment by nviets** [comment]
Could we update to build that covers all of catboost's binaries, including CLI, R, Java prediction, and Scala? The binaries are not shared between them, but the source code and [build process is](https://github.com/catboost/catboost/blob/master/ci/build_all_nix_ya.shl). What's the standard strategy in nix for libraries that are set up like this? Would the package stay in python-modules? R packages, for example, can be set up anywhere - see [xgboost](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/xgboost/default.nix#L3). @PlushBeaver @mweinelt @dotlambda

**Comment by PlushBeaver** [comment]
+1 to @nviets suggestion. This was packaged for Python only mostly because I failed to figure out how to use Yamake with Nix. Unfortunately, I don't have time to maintain this package anymore, so you can remove me from the list, @veprbl. Thanks!

**Comment by nviets** [comment]
Thanks for the background, @PlushBeaver. If we were to add the additional outputs for R, spark, java, etc... should the package stay in python-modules or move somewhere else, e.g. python applications? I'm not familiar with the standards in python-modules and whether we'd be permitted to have the extra stuff live here. I'd prefer to keep the build together to match binary functionality (e.g. CUDA support) and versions. Less work to maintain, too.

**Comment by nviets** [comment]
Catboost switched from ya make to cmake in the [1.2 release](https://github.com/catboost/catboost/releases/tag/v1.2).

**Comment by nviets** [comment]
Recommending we close this PR. I'd still like to separate the catboost library and python package into separate derivations so we can build the other catboost APIs (R, CLI, spark, etc...). I had a go at the 1.2 release, but the build is a little finicky and has many options.

**Pull request closed without merging**
