### PR TITLE
pdal: 2.5.6 -> 2.6.2

### PR DESCRIPTION
**Pull request by imincik**
## Description of changes

Update PDAL to the latest version.

List of changes:

* https://github.com/PDAL/PDAL/releases/tag/2.6.0
* https://github.com/PDAL/PDAL/releases/tag/2.6.1

This PR is replacing #271463 .

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by imincik** [comment]
Result of `nixpkgs-review pr 273948` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>qgis-ltr</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>cloudcompare</li>
    <li>entwine</li>
    <li>grass</li>
    <li>pdal</li>
    <li>qgis</li>
  </ul>
</details>

**Comment by imincik** [comment]
Result of `nixpkgs-review pr 273948` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>qgis-ltr</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>cloudcompare</li>
    <li>entwine</li>
    <li>grass</li>
    <li>pdal</li>
    <li>qgis</li>
  </ul>
</details>

**Comment by imincik** [comment]
QGIS LTR needs https://github.com/qgis/QGIS/pull/54940 to be backported .

**Comment by jtojnar** [comment]
Can we merge this to staging-next? qgis-ltr will be already broken there due to pdal being broken.

**Comment by imincik** [comment]
> Can we merge this to staging-next? qgis-ltr will be already broken there due to pdal being broken.

I am not aware of PDAL being broken. What do you mean by that ?

Current blockers for merging this PR are:

* QGIS-LTR can't build with PDAL 2.6.2
* We can't run PDAL unit tests with 2.6.2 (see: https://github.com/NixOS/nixpkgs/pull/275416)

**Comment by jtojnar** [comment]
> I am not aware of PDAL being broken. What do you mean by that ?

See https://github.com/NixOS/nixpkgs/pull/275620#issuecomment-1880064723

**Comment by imincik** [comment]
Options to fix QGIS-LTR:

1. keep local version of PDAL 2.5.6 and build QGIS-LTR with that until https://github.com/qgis/QGIS/pull/54940 is backported
2. manually create working patch from https://github.com/qgis/QGIS/pull/54940 and apply it to QGIS-LTR
3. disable PDAL for QGIS-LTR

Which option would you choose ?

**Comment by imincik** [comment]
Option 1 implemented in https://github.com/NixOS/nixpkgs/pull/273948/commits/5c5e820980fe09f58eaa118d68d5eff19f466e63

**Comment by imincik** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>cloudcompare</li>
    <li>entwine</li>
    <li>grass</li>
    <li>pdal</li>
    <li>qgis</li>
    <li>qgis-ltr</li>
  </ul>
</details>

**Comment by nh2** [comment]
Changes and the mentioned build fix look good, merging.

**Pull request merged**
