### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by maralorn**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

More information about Haskell packages in nixpkgs can be found [in the nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#haskell).

---

This is the follow-up to #259060. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by vcunat** [comment]
_I assume it's OK for me to cancel non-current builds in the corresponding Hydra jobset, e.g. now it was several thousand._

**Comment by maralorn** [comment]
Hey @turion,

there is a build error in monad-bayes: https://hydra.nixos.org/build/239250533/nixlog/3

From the looks of it, it’s a classical "test files missing in hackage tar ball" problem. I would suggest temporarily disabling the checks.

**Comment by cdepillabout** [comment]
Hey @thielema,

There is a build error in coinor-clp

- https://hydra.nixos.org/build/239790474/nixlog/2
- https://hydra.nixos.org/build/239790474

It looks like it could potentially be a real error?

**Comment by thielema** [comment]
On Thu, 2 Nov 2023, Dennis Gosnell wrote:

> Hey @thielema,
> 
> There is a build error in coinor-clp
>
>  *  https://hydra.nixos.org/build/239790474/nixlog/2
>  *  https://hydra.nixos.org/build/239790474
> 
> It looks like it could potentially be a real error?

Indeed. It looks like a problem in the COIN-OR/Clp C++ library.

I reported it to the library authors:
   https://list.coin-or.org/pipermail/clp/2023-November/001805.html

I have released a work-around in the Haskell bindings to Hackage. The 
tests of coinor-clp should work, again.

**Comment by maralorn** [comment]
I think the monad-bayes situation is the only thing which needs fixing. This PR has been open quite a while.

I don’t think waiting for the upstream fix to be merged and then bumping hackage is a good option, because the branch is otherwise ready to merge. Let’s either apply the patch or disable the checks now and rip them out in the next iteration.

**Comment by turion** [comment]
Fine with me if a link to the upstream fix is mentioned: https://github.com/tweag/monad-bayes/pull/326

**Comment by ncfavier** [comment]
Applying the monad-bayes patch isn't enough because the files are still missing from the Hackage tarball, so I've disabled the tests.

**Comment by cdepillabout** [comment]
@thielema 

> I have released a work-around in the Haskell bindings to Hackage. The tests of coinor-clp should work, again.

I didn't update our `haskellPackages.coinor-clp` version in this PR (and it doesn't look like there was a commit fixing it), but it is now compiling correctly.

My guess is that the underlying COIN-OR/Clp C++ library was updated fixing the problem?

(Gotta love when QuickCheck in Haskell is able to find problems in the underlying C/C++ libraries :-))

**Comment by thielema** [comment]
On Thu, 9 Nov 2023, Dennis Gosnell wrote:

> @thielema
>
>       I have released a work-around in the Haskell bindings to Hackage. The tests of
>       coinor-clp should work, again.
> 
> I didn't update our haskellPackages.coinor-clp version in this PR (and it doesn't look like there
> was a commit fixing it), but it is now compiling correctly.
> 
> My guess is that the underlying COIN-OR/Clp C++ library was updated fixing the problem?

They have fixed something, but I do not know whether they already released 
the fix.

> (Gotta love when QuickCheck in Haskell is able to find problems in the 
> underlying C/C++ libraries :-))

I have actually also found bugs in OpenBLAS this way.

Since QuickCheck tests with random inputs, tests may fail or succeed 
randomly. Since the test failure showed up only after several runs at 
Hydra, I think the failure conditions are not met too often. Thus my 
current guess is, that neither my Haskell work-around nor the COIN/OR fix 
is used but simply the failure conditions are not triggered by accident.

**Pull request merged**
