### PR TITLE
[Backport release-23.11]: cargo-* tools updates with newer rustPlatform

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Description of changes

This was extracted from #298302 to be able to talk in a dedicated PR about the following issue:

The backports are only possible because of #298206 - that's why there are patches in this PR that make the updated attributes use the `rustPackages_1_76.rustPlatform` to build the packages. The patches that make this change are _not_ on `master`, so I don't know what the policy for such a backport is.

All other patches (the actual package update commits) are `cherry-pick -xs`ed.

I did not (yet) run this through `nixpkgs-review` as #298206 has not yet landed on `nixos-23.11`, and I don't want to recompile `rustc` on my infra :laughing: 
Once `nixos-23.11` is updated, I can of course do a `nixpkgs-review` run on this.

Lets discuss.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Friendly ping @figsoda @06kellyjac @oxalica @B4dM4n @kharji

**Comment by matthiasbeyer** [comment]
Friendly ping @figsoda @06kellyjac @oxalica @B4dM4n @kharji

**Review by 06kellyjac — COMMENTED** [review]
The hardest part was probably the rust backport.

Looks fine scanning over the code. I'll look to run the review tool to build the changes if I get the chance

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 298312` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>cargo-binstall</li>
    <li>cargo-chef</li>
    <li>cargo-component</li>
    <li>cargo-deny</li>
    <li>cargo-generate</li>
    <li>cargo-llvm-lines</li>
    <li>cargo-public-api</li>
    <li>cargo-semver-checks</li>
    <li>cargo-shuttle</li>
    <li>cargo-tally</li>
    <li>cargo-udeps</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
I guess this looks good :laughing:

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 298312` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>cargo-binstall</li>
    <li>cargo-chef</li>
    <li>cargo-component</li>
    <li>cargo-deny</li>
    <li>cargo-dist</li>
    <li>cargo-generate</li>
    <li>cargo-llvm-lines</li>
    <li>cargo-public-api</li>
    <li>cargo-semver-checks</li>
    <li>cargo-shuttle</li>
    <li>cargo-tally</li>
    <li>cargo-udeps</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 298312` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>cargo-binstall</li>
    <li>cargo-chef</li>
    <li>cargo-component</li>
    <li>cargo-deny</li>
    <li>cargo-dist</li>
    <li>cargo-generate</li>
    <li>cargo-llvm-lines</li>
    <li>cargo-public-api</li>
    <li>cargo-semver-checks</li>
    <li>cargo-shuttle</li>
    <li>cargo-tally</li>
    <li>cargo-temp</li>
    <li>cargo-udeps</li>
  </ul>
</details>

**Review by kkharji — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
I'll merge this tomorrow if there's no objections.

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 298312` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>cargo-modules</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>cargo-binstall</li>
    <li>cargo-chef</li>
    <li>cargo-component</li>
    <li>cargo-deny</li>
    <li>cargo-dist</li>
    <li>cargo-generate</li>
    <li>cargo-llvm-lines</li>
    <li>cargo-public-api</li>
    <li>cargo-semver-checks</li>
    <li>cargo-shuttle</li>
    <li>cargo-tally</li>
    <li>cargo-temp</li>
    <li>cargo-udeps</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
Turns out `cargo-modules` fails, so I'll revert these patches

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 298312` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>cargo-binstall</li>
    <li>cargo-chef</li>
    <li>cargo-component</li>
    <li>cargo-deny</li>
    <li>cargo-dist</li>
    <li>cargo-generate</li>
    <li>cargo-llvm-lines</li>
    <li>cargo-public-api</li>
    <li>cargo-semver-checks</li>
    <li>cargo-shuttle</li>
    <li>cargo-tally</li>
    <li>cargo-temp</li>
    <li>cargo-udeps</li>
  </ul>
</details>

**Pull request merged**
