### PR TITLE
gh: fix cross

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build pkgsCross.aarch64-multiplatform.gh
@ofborg build gh

**Comment by zowoq** [comment]
```diff
diff --git a/pkgs/applications/version-management/gh/default.nix b/pkgs/applications/version-management/gh/default.nix
index da32620cf58..80578fa3e47 100644
--- a/pkgs/applications/version-management/gh/default.nix
+++ b/pkgs/applications/version-management/gh/default.nix
@@ -1,4 +1,4 @@
-{ lib, fetchFromGitHub, buildGoModule, installShellFiles, testers, gh }:
+{ lib, fetchFromGitHub, buildGoModule, installShellFiles, stdenv, testers, gh }:
 
 buildGoModule rec {
   pname = "gh";
@@ -15,12 +15,6 @@ buildGoModule rec {
 
   nativeBuildInputs = [ installShellFiles ];
 
-  # upstream unsets these to handle cross but it breaks our build
-  postPatch = ''
-    substituteInPlace Makefile \
-      --replace "GOOS= GOARCH= GOARM= GOFLAGS= CGO_ENABLED=" ""
-  '';
-
   buildPhase = ''
     runHook preBuild
     make GO_LDFLAGS="-s -w" GH_VERSION=${version} bin/gh manpages
@@ -30,12 +24,14 @@ buildGoModule rec {
   installPhase = ''
     runHook preInstall
     install -Dm755 bin/gh -t $out/bin
+   '' + lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
     installManPage share/man/*/*.[1-9]
 
     installShellCompletion --cmd gh \
       --bash <($out/bin/gh completion -s bash) \
       --fish <($out/bin/gh completion -s fish) \
       --zsh <($out/bin/gh completion -s zsh)
+  '' + ''
     runHook postInstall
   '';
 

```

**Comment by amjoseph-nixpkgs** [comment]
Ofborg says: [pkgsCross.aarch64-multiplatform.gh on x86_64-linux — Success ](https://github.com/NixOS/nixpkgs/pull/225121/checks?check_run_id=12587164434)

**Review by zowoq — CHANGES_REQUESTED** [review]
I think disabling completion and man for cross is fine, please update this to match the diff I posted.

**Pull request merged**
