### PR TITLE
Kernel config: use PREEMPT_VOLUNTARY

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
zfsonlinux/zfs#8545

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
@GrahamcOfBorg build linuxPackages_5_0.zfs linuxPackages_5_1.zfs linuxPackages.zfs

**Comment by lheckemann** [comment]
Ah yes, this needs #61181 as well for it to actually fix the spl build.

**Comment by lheckemann** [comment]
cc @thoughtpolice who seems to be the only maintainer listed for the kernel, @NeQuissimus who does a lot of kernel stuff

**Comment by joachifm** [comment]
Hm, perhaps I'm missing something but on master I get
```
% grep PREEMPT $(nix-build -A linux_latest.configfile)
# CONFIG_PREEMPT_NONE is not set
CONFIG_PREEMPT_VOLUNTARY=y
# CONFIG_PREEMPT is not set
```

**Comment by lheckemann** [comment]
@joachifm it only seems to default to `y` on aarch64.

**Review by NeQuissimus — APPROVED** [review]

**Comment by NeQuissimus** [comment]
LGTM

**Comment by thoughtpolice** [comment]
Sorry about the miss here @lheckemann, thanks for the patch!

**Comment by digitalsignalperson** [comment]
hi folks, wondering about that 2d44588 commit added after the merge (use preempt voluntary only for aarch64)
If the zfs problem is isolated to aarch64, can we keep PREEMPT instead of voluntary for better default x86_64 realtime performance?

**Comment by lheckemann** [comment]
@digitalsignalperson the main reason for applying it only to aarch64 was to minimise the amount of changes to the extent that nothing even gets rebuilt on x86_64. I'd suggest setting `CONFIG_PREEMPT_VOLUNTARY` to `lib.mkForce no` for musnix, and stick to the upstream default in nixpkgs itself.

**Comment by digitalsignalperson** [comment]
@lheckemann Sorry I think I'm confused. It looks to me that  1d37727 was merged into master which applies the change to both x86_64 and aarch64. Is that not the case?

**Comment by digitalsignalperson** [comment]
in other words, on my x86_64 system on nixos-unstable, output from `zgrep PREEMPT /proc/config.gz` includes
```
CONFIG_PREEMPT_VOLUNTARY=y
# CONFIG_PREEMPT is not set
```

**Comment by lheckemann** [comment]
@digitalsignalperson yes, that is correct, _however_ this was already the case before 1d37727, the only change being that it's now explicit.

**Comment by digitalsignalperson** [comment]
Ah, I see. Thanks for clarifying

**Pull request merged**
