### PR TITLE
keepassxc: 2.6.3 -> 2.6.4

### PR DESCRIPTION
**Pull request by iAmMrinal0**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Are you sure you got the sha256 hash right?

**Comment by iAmMrinal0** [comment]
```
nix-prefetch-github keepassxreboot keepassxc --rev 2.6.4
{
    "owner": "keepassxreboot",
    "repo": "keepassxc",
    "rev": "34a78f0ec3a3c030218c71a57c6fa56e6cb0bc44",
    "sha256": "0vhbh2qi1j5dv3pc0xhjjc1jc92k5f8ynmd211dhr65lqhp64xk0",
    "fetchSubmodules": true
}
```
Release 2.6.4 points to [34a78f0ec3a3c030218c71a57c6fa56e6cb0bc44](https://github.com/keepassxreboot/keepassxc/commit/34a78f0ec3a3c030218c71a57c6fa56e6cb0bc44). Am I missing something here, @prusnak?

**Comment by prusnak** [comment]
@iAmMrinal0 See the CI output: https://github.com/NixOS/nixpkgs/pull/111627/checks?check_run_id=1812472409 

I guess this is without submodules ...

**Comment by iAmMrinal0** [comment]
@prusnak sorry for missing that. I'll fix it. If possible, could you explain how it built successfully for me locally even with the incorrect sha value?

**Comment by iAmMrinal0** [comment]
If I change the hash to one without submodules(02ajfkw818cmalvkl0kqvza85rgdgs59kw2v7b3c4v8kv00c41j3 same as the ofborg evaluation error), then I get a patch failed error when I run `nixpkgs-review wip`:
```
Applying `nixpkgs` diff...
error: patch failed: pkgs/applications/misc/keepassx/community.nix:46
error: pkgs/applications/misc/keepassx/community.nix: patch does not apply
```

**Comment by turion** [comment]
Maybe you have some wrong sources in your store? You could delete the `result` folder and all garbage collector roots, and then run `nix-collect-garbage`?

**Comment by prusnak** [comment]
> @prusnak sorry for missing that. I'll fix it. If possible, could you explain how it built successfully for me locally even with the incorrect sha value?

You "fetched" the hash via `nix-prefetch-github` above. So when you started the build, the hash was successfully resolved to the checkout tree you created earlier.

**Comment by iAmMrinal0** [comment]
@turion deleted cache for `nixpkgs-review` and ran `nix-collect-garbage` and still error at patch failed. so looks like the build works if submodules are fetched and the hash corresponding to that is used, keepassxc executed too with these changed. should I update the PR with that change? or do you suggest any other approach to this?

**Comment by prusnak** [comment]
> or do you suggest any other approach to this?

Just use the hash you see in the CI.

**Comment by turion** [comment]
Builds an executes:

```
$ results/keepassxc/bin/keepassxc --version
KeePassXC 2.6.4
```

**Review by turion — APPROVED** [review]

**Comment by turion** [comment]
See https://github.com/NixOS/nixpkgs/pull/111642 where I'm adding a test that starts keepassxc.

**Pull request merged**
