### PR TITLE
cargo-rr: fix 'list-git-tags' call

### PR DESCRIPTION
**Pull request by otavio**
Use list-git-tags with no arguments; fixes:

,----
| ...-common-updater-scripts/bin/.list-git-tags-wrapped: unknown option ‘https://github.com/danielzfranklin/cargo-rr’'
`----

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
`cargo-rr` seems to be building on `master`.

Does this fix a warning during build?

**Comment by otavio** [comment]
It fixes autoupdate error.

**Review by thiagokokada — COMMENTED** [review]
```
Going to be running update for following packages:
 - cargo-rr-0.1.3

Press Enter key to continue...

Running update for:
 - cargo-rr-0.1.3: UPDATING ...
 - cargo-rr-0.1.3: DONE.

Packages updated!
```

Doesn't seem to be working properly (note there is a 0.2.0 release already: https://github.com/danielzfranklin/cargo-rr/releases/tag/v0.2.0).

Edit: it seems the issue is that upstream changed the tag to have a `v` before the version number. And looking at the `list-git-tags` script, it seems the current code is fine.

**Review by thiagokokada — APPROVED** [review]
Approving since the issue of not updating the version seems to be because of a change in format that upstream tags its releases, so the update to 0.2.0 will have to be done manually (and them it should work automatically).

**Pull request merged**
