### PR TITLE
llvmPackages_19: 19.1.5 -> 19.1.6

### PR DESCRIPTION
**Pull request by paparodeo**
https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.6 
https://discourse.llvm.org/t/llvm-19-1-6-released/83723

also fixes https://github.com/NixOS/nixpkgs/pull/356120#issuecomment-2550339972
due to an unmatched replace after `replace` -> `replace-fail`

testing: `nix-build -A llvmPackages_19 -A tests.cc-wrapper.llvmTests.llvmPackages_19` on aarch64-darwin and x64 linux

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by philiptaron** [comment]
I still can't build `clang_{12,13,14}` with this PR on `x86_64-linux`. They all fail in `tblgen`. In process of building `clang_19`.

**Comment by paparodeo** [comment]
> I still can't build `clang_{12,13,14}` with this PR on `x86_64-linux`. They all fail in `tblgen`. In process of building `clang_19`.

I suspect tablegen issue is due to: https://github.com/NixOS/nixpkgs/pull/362384

**Review by philiptaron — APPROVED** [review]
Build and usage to build many packages (mesa, etc) went well overnight. I would like to merge.

**Comment by paparodeo** [comment]
> Build and usage to build many packages (mesa, etc) went well overnight. I would like to merge.

did you build on darwin? once the aarch64-darwin build finishes I'll mark as ready.

**Comment by paparodeo** [comment]
backport https://github.com/NixOS/nixpkgs/pull/366215

**Pull request merged**
