### PR TITLE
[staging] autoconf: 2.70 -> 2.71

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

This updates autoconf to 2.71. This version appears to be mostly a stable release handling some of the breakage of 2.70 and/or fixing compat with newer clang version (on e.g. the Apple M1 machines).

I kept the addition and the switch of the version separate so that we can just revert the switch in case this causes trouble without closing the door on packages (or platforms) requiring the newer version in the future.

###### Things done

- [x] I did run a few NixOS VM tests with with this
- [ ] Built the entire NixOS release set with this (still in process, waiting on my hydra)

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I've created https://github.com/NixOS/nixpkgs/pull/111472 to fix the eval error.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by andir** [comment]
I added one commit that touches pythonPackages.psutil as otherwise the build wouldn't work on any of my systems anymore. See the commit message for details. Would appreciate a review from @jonringer.

**Comment by jonringer** [comment]
I'll start a review on my server.. might take a while

**Comment by andir** [comment]
I've started a full NixOS release job here https://hydra.h4ck.space/eval/1918#tabs-new (IPv6-only) and you can use my binary cache to ease the load on your machines:

```
--option substituters "https://cache.nixos.org/ https://cache.h4ck.space/" --option trusted-public-keys "zeta:9zm3cHRlqz3T9HnRsodtQGGqHOLDAiB+8d0kOKnFI0M= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
```

**Comment by jonringer** [comment]
I really need to get https://github.com/jonringer/basinix going. Would make this a whole lot easier.

**Comment by thefloweringash** [comment]
I'd like to see this progress. Did those reviews complete, and were there any interesting failures? (polite bump)

**Comment by andir** [comment]
I only observed some flaky NixOS tests (due to timing etc..) but it didn't look like something major. I also only built all the nixos tests so there might be more ground to cover.

**Comment by thefloweringash** [comment]
I recently learned there's an upcoming freeze for 21.05 (see [the post on discourse](https://discourse.nixos.org/t/21-05-release-schedule/12528)). It'd be nice to have Apple Silicon support in the stable branch, so I'd like to get this supporting PR merged before the April 30 deadline.

The python change is currently conflicting, and also not directly related to the autoconf change. Maybe we should make that a different PR?

In the last autoconf update in #106663 there was some breakage, but it was also the first update in many years. This update was around 2 months after that. Hopefully all the hard work is already done there won't be much fallout. cc @alyssais as someone with experience with autoconf.

**Comment by FRidh** [comment]
@vcunat could you make a Hydra job for this?

**Comment by vcunat** [comment]
Uh, I don't get the GitHub UI, as all those commits were contained in `staging` already.

**Comment by vcunat** [comment]
Jobset: https://hydra.nixos.org/eval/1666118?compare=1666054

**Comment by jonringer** [comment]
may want to do `git rebase --onto=origin/staging HEAD~#`, then force push

**Comment by vcunat** [comment]
Uh, lots of random failures and timeouts, but after some restarts it's clearing up.  Overall it looks good to me.
- `ghcHEAD` variants are half a year old and apparently just need to be updated: https://gitlab.haskell.org/ghc/ghc/-/issues/19655#note_345257

In any case, particular packages should be able to just switch to older autoconf anytime later.  So I'm for merging to `staging`, meaning it will hopefully get into 21.05, too.

**Comment by sternenseemann** [comment]
> ghcHEAD variants are half a year old and apparently just need to be updated: https://gitlab.haskell.org/ghc/ghc/-/issues/19655#note_345257

I can probably look into a ghcHEAD update PR for staging in the next days.

**Comment by vcunat** [comment]
I assume that could even go directly to master.

**Comment by sternenseemann** [comment]
#121807

**Comment by jonringer** [comment]
yea, last autoconf bump there was a lot of breakages. but I'm fine with adding a new top-level attr

**Comment by andir** [comment]
Anything holding this back? Looks like there aren't that many failures that are out of the ordinary.

**Comment by jonringer** [comment]
do you mind cleaning up the git histhory?

**Review by bobrik — APPROVED** [review]

**Comment by bobrik** [comment]
Anything else stopping this? I believe this is one of the blockers for #105026.

**Pull request merged**
