### PR TITLE
sauerbraten: 5492 -> 2020-12-04

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
http://www.sauerworld.org/new-sauerbraten-2020-edition-released/

I haven't tested the server, the client seems to run, I'll try and see how much of my practice I've lost and mark as ready afterwards.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Please update the commit message and PR title to ``sauerbraten: 5492 -> 2020-12-04``.

**Comment by ajs124** [comment]
5492 was a random svn revision, but I can change it if you think that's really necessary. It does however not seem to store settings right now, so I'll need to fix that.

**Comment by SuperSandro2000** [comment]
> 5492 was a random svn revision, but I can change it if you think that's really necessary.

It is the current version in nixpkgs so please change it.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106033` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sauerbraten</li>
  </ul>
</details>

**Comment by teto** [comment]
passed nixpkgs-review here. I tried to run the binary and it worked fine with the exceptiuon I had no audio. It may come from my setup though so if someone could check.

**Comment by SuperSandro2000** [comment]
Replaced by #106317 because I cannot force push the commit message and noticed that to late.

**Comment by ajs124** [comment]
I'd appreciate if you'd never do that again. Thanks.

**Pull request closed without merging**
