### PR TITLE
Explicitly account for current limitations of RISC-V kernels

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by Ericson2314** [comment]
Hmm so hehe there's two things I mentioned on IRC, and I now see they were in direct conflict:

1. It's better not to push local package problems into global `lib/systems.nix`
2. It's better to allow negative reasoning in arbitrary packages

Maybe it would be a good idea to do a `meta.__badPlatforms` so `meta.platforms` stays "good" and "open world friendly" but we still keep local concerns local?

**Comment by shlevy** [comment]
@Ericson2314 Hmm I'm a bit confused, this PR both moves stuff out of lib/systems *and* allows negative reasoning in individual packages... `meta.platforms.{include,exclude}` seems isomorphic to `meta.{platforms,__badPlatforms}`, especially since `include` is the default if none are specified.

**Comment by Ericson2314** [comment]
@shlevy hahaha I meant to write "disallow" not "allow". Sorry for that. Indeed it is isomorphic, just trying to quarantine the negative stuff as much as possible.

**Comment by shlevy** [comment]
@Ericson2314 Updated

**Review by Ericson2314 — APPROVED** [review]

**Pull request merged**
