### PR TITLE
vscode-extensions.octref.vetur: init at 0.34.1

### PR DESCRIPTION
**Pull request by DenzoNL**
###### Motivation for this change

Add VSCode Extension [Vetur](https://github.com/vuejs/vetur)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Thanks for adding this!

There is one improvement that can be done if you are interested!
Currently this relies on a global install of vls. If you wanted to specify vls as a dependency to this plugin you could do something similar to https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/default.nix#L113
Let me know if you want more details

In case you have no time to go further, let me know, I'm fine to merge as is.

**Comment by DenzoNL** [comment]
@happysalada Thanks for the positive feedback! Your suggestion sounds goods! I have some time to add this tomorrow. Feel free to merge it (I can always create a new PR) as is, or leave it open if that's the preferred workflow :)

**Comment by happysalada** [comment]
I would tend to leave it open if you have time to work on this within the week.

One more thing, the way I would tend to test this would be. 
- Remove your global installation of vls (whether done through nixpkgs or npm).
- If the plugin still works without specifying for a global installation of vls,, then the dependency is correctly stated.

Feel free to ping me when you want me to have another look.

**Comment by DenzoNL** [comment]
@happysalada Took some time to figure out how to install the package from my locally cloned repo, but I've got it running locally here no. I've been testing with the [Veturpack ](https://github.com/octref/veturpack) example repo.

It seems like everything works out of the box as expected (without installing VLS through NixOS or npm)  and it looks like it just pulls VLS in through its own package.json.

Do we still need to override this behaviour by pulling in VLS as a dependency to this? Would love to hear your thoughts and if indeed we need to do that, a few more pointers would be nice :)

**Comment by happysalada** [comment]
Thanks for testing this!

After having a look, it seems that vetur doesn't rely on an external vls. Usually when plugins rely on an external dependency they specify a command to call the dependency inside the 'contributes' part of the package.json.
Since this extension is not relying on an external dependency, I think it's good to merge.

Thanks again for your contribution!

**Pull request merged**
