### PR TITLE
python.pkgs.pyqt5: 5.10.1 -> 5.11.3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
Qutebrowser complains about needing Qt 5.11 when setting `content.cookies.accept` to `no-3rdparty`.

When running qutebrowser with this version of pyqt5, I get `ModuleNotFoundError: No module named 'PyQt5.sip'`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @svanderburg

### CODE REVIEW

**Comment by nyanloutre** [comment]
I also get `ModuleNotFoundError: No module named 'PyQt5.sip'` when using the pyrcc5 tool

**Comment by nyanloutre** [comment]
This is the behavior observed with the above patch applied

```
➜ nix-shell -I nixpkgs=. -p python3Packages.pyqt5 python3

[nix-shell:~/nixpkgs]$ echo $PYTHONPATH
/nix/store/93bfhjg1cr2650in7wzqv309kdyl7i8b-python3.7-sip-4.19.13/lib/python3.7/site-packages:/nix/store/9vcy8i7mcwmcp486krc22v7851spcdqj-python3-3.7.1/lib/python3.7/site-packages:/nix/store/q4bf5k1j6xgs621jp3mxmydxjxgfbalj-python3.7-setuptools-40.6.2/lib/python3.7/site-packages:/nix/store/pgpkq47dbakpcpmkf7gsw8d9kd4pv14f-python3.7-PyQt-5.11.3/lib/python3.7/site-packages:/nix/store/93bfhjg1cr2650in7wzqv309kdyl7i8b-python3.7-sip-4.19.13/lib/python3.7/site-packages:/nix/store/9vcy8i7mcwmcp486krc22v7851spcdqj-python3-3.7.1/lib/python3.7/site-packages:/nix/store/q4bf5k1j6xgs621jp3mxmydxjxgfbalj-python3.7-setuptools-40.6.2/lib/python3.7/site-packages:/nix/store/pgpkq47dbakpcpmkf7gsw8d9kd4pv14f-python3.7-PyQt-5.11.3/lib/python3.7/site-packages

[nix-shell:~/nixpkgs]$ python
Python 3.7.1 (default, Oct 20 2018, 06:25:16)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5.sip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'
>>>

[nix-shell:~/nixpkgs]$ exit

➜ nix-shell -I nixpkgs=. -p python3Packages.sip python3

[nix-shell:~/nixpkgs]$ echo $PYTHONPATH
/nix/store/93bfhjg1cr2650in7wzqv309kdyl7i8b-python3.7-sip-4.19.13/lib/python3.7/site-packages:/nix/store/9vcy8i7mcwmcp486krc22v7851spcdqj-python3-3.7.1/lib/python3.7/site-packages:/nix/store/q4bf5k1j6xgs621jp3mxmydxjxgfbalj-python3.7-setuptools-40.6.2/lib/python3.7/site-packages:/nix/store/93bfhjg1cr2650in7wzqv309kdyl7i8b-python3.7-sip-4.19.13/lib/python3.7/site-packages:/nix/store/9vcy8i7mcwmcp486krc22v7851spcdqj-python3-3.7.1/lib/python3.7/site-packages:/nix/store/q4bf5k1j6xgs621jp3mxmydxjxgfbalj-python3.7-setuptools-40.6.2/lib/python3.7/site-packages

[nix-shell:~/nixpkgs]$ python
Python 3.7.1 (default, Oct 20 2018, 06:25:16)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5.sip
>>>

[nix-shell:~/nixpkgs]$ exit
```

I don't know why it fails in the first case because the sip module is in the PYTHONPATH and the only thing added is `python3.7-PyQt`

**Comment by veprbl** [comment]
Well, this has landed to master.

@nyanloutre I can still reproduce your issue. I think you are on the right track about solving this. It seems like your last problem is because `sip.so` needs to be in the same directory with the rest of PyQt5 module in order for it to be loadable. If they are in separate prefixes, then you'll only be able to load either `PyQt5.sip` or the real `PyQt5.<stuff>` depending on whichever instance of `PyQt5` module is discovered first. I think you could just make so that necessary parts of modified `pythonPackages.sip` are copied over in `postInstall` of the pyqt5.

**Comment by nyanloutre** [comment]
@veprbl thanks for the suggestion, I will try to simlink the sip library in the right pyqt5 directory

**Pull request closed without merging**
