### PR TITLE
vimPlugins: update

### PR DESCRIPTION
**Pull request by ivankovnatsky**
###### Motivation for this change
initial motivation is for vim-airline plugin fix: https://github.com/vim-airline/vim-airline/issues/2324

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111995` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>vimPlugins.neogit: log <a href="https://termbin.com/07ui">https://termbin.com/07ui</a></li>
  </ul>
</details>
<details>
<summary>
37 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>vimPlugins.chadtree</li>
<li>vimPlugins.coc-explorer</li>
<li>vimPlugins.coc-lua</li>
<li>vimPlugins.denite-nvim</li>
<li>vimPlugins.deoplete-vim-lsp</li>
<li>vimPlugins.fzf-lsp-nvim</li>
<li>vimPlugins.galaxyline-nvim</li>
<li>vimPlugins.git-messenger-vim</li>
<li>vimPlugins.gitsigns-nvim</li>
<li>vimPlugins.julia-vim</li>
<li>vimPlugins.lf-vim</li>
<li>vimPlugins.lspsaga-nvim</li>
<li>vimPlugins.lualine-nvim</li>
<li>vimPlugins.nvim-compe</li>
<li>vimPlugins.nvim-dap</li>
<li>vimPlugins.nvim-highlite</li>
<li>vimPlugins.nvim-lspconfig</li>
<li>vimPlugins.nvim-lsputils</li>
<li>vimPlugins.nvim-treesitter</li>
<li>vimPlugins.nvim-ts-rainbow</li>
<li>vimPlugins.packer-nvim</li>
<li>vimPlugins.plenary-nvim</li>
<li>vimPlugins.sql-nvim</li>
<li>vimPlugins.tcomment_vim</li>
<li>vimPlugins.telescope-frecency-nvim</li>
<li>vimPlugins.telescope-nvim</li>
<li>vimPlugins.vim-airline</li>
<li>vimPlugins.vim-erlang-tags</li>
<li>vimPlugins.vim-floaterm</li>
<li>vimPlugins.vim-graphql</li>
<li>vimPlugins.vim-illuminate</li>
<li>vimPlugins.vim-lsc</li>
<li>vimPlugins.vim-ruby</li>
<li>vimPlugins.vim-vsnip</li>
<li>vimPlugins.vimtex</li>
<li>vimPlugins.vista-vim</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111995` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>spacevim</li>
</ul>
</details>

**Comment by ivankovnatsky** [comment]
```console
nixpkgs-review pr 111995

38 packages built:
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111995` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
38 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>vimPlugins.chadtree</li>
<li>vimPlugins.coc-explorer</li>
<li>vimPlugins.coc-lua</li>
<li>vimPlugins.denite-nvim</li>
<li>vimPlugins.deoplete-vim-lsp</li>
<li>vimPlugins.fzf-lsp-nvim</li>
<li>vimPlugins.galaxyline-nvim</li>
<li>vimPlugins.git-messenger-vim</li>
<li>vimPlugins.gitsigns-nvim</li>
<li>vimPlugins.julia-vim</li>
<li>vimPlugins.lf-vim</li>
<li>vimPlugins.lspsaga-nvim</li>
<li>vimPlugins.lualine-nvim</li>
<li>vimPlugins.neogit</li>
<li>vimPlugins.nvim-compe</li>
<li>vimPlugins.nvim-dap</li>
<li>vimPlugins.nvim-highlite</li>
<li>vimPlugins.nvim-lspconfig</li>
<li>vimPlugins.nvim-lsputils</li>
<li>vimPlugins.nvim-treesitter</li>
<li>vimPlugins.nvim-ts-rainbow</li>
<li>vimPlugins.packer-nvim</li>
<li>vimPlugins.plenary-nvim</li>
<li>vimPlugins.sql-nvim</li>
<li>vimPlugins.tcomment_vim</li>
<li>vimPlugins.telescope-frecency-nvim</li>
<li>vimPlugins.telescope-nvim</li>
<li>vimPlugins.vim-airline</li>
<li>vimPlugins.vim-erlang-tags</li>
<li>vimPlugins.vim-floaterm</li>
<li>vimPlugins.vim-graphql</li>
<li>vimPlugins.vim-illuminate</li>
<li>vimPlugins.vim-lsc</li>
<li>vimPlugins.vim-ruby</li>
<li>vimPlugins.vim-vsnip</li>
<li>vimPlugins.vimtex</li>
<li>vimPlugins.vista-vim</li>
</ul>
</details>

**Pull request merged**
