### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Tests for cffi seem to fail.

**Comment by FRidh** [comment]
Do we have binutils 2.34 again on staging(-next)? Did something go wrong with merges? cc @flokli @Ericson2314 @vcunat

**Comment by flokli** [comment]
@FRidh staging has https://github.com/NixOS/nixpkgs/pull/85951, which is a second attempt that shouldn't break things anymore.

**Comment by FRidh** [comment]
Python's cffi fails https://github.com/NixOS/nixpkgs/pull/86954#issuecomment-629780551

**Comment by flokli** [comment]
It seems now `python3.pkgs.cython` (used by `gtk-doc`) fails. Might have been broken by 1ac5398589916a6a433e845342c9b85c4c52f5dc (cc @Ericson2314), or by a broken revert of https://github.com/NixOS/nixpkgs/pull/86954:

```
❯ nix-build -A python3.pkgs.cython
these derivations will be built:
  /nix/store/7kq52z55dhp44irxcz1j58yvv2x2k13r-python3.7-Cython-0.29.14.drv
building '/nix/store/7kq52z55dhp44irxcz1j58yvv2x2k13r-python3.7-Cython-0.29.14.drv'...
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
/nix/store/8cz3waxwnvqd1mxw3aniiwimr8kvxbsg-python3.7-pkgconfig-1.5.1/nix-support/setup-hook: line 61: export: `NIX_@wrapperName@_TARGET_HOST_@suffixSalt@=1': not a valid identifier
builder for '/nix/store/7kq52z55dhp44irxcz1j58yvv2x2k13r-python3.7-Cython-0.29.14.drv' failed with exit code 1
error: build of '/nix/store/7kq52z55dhp44irxcz1j58yvv2x2k13r-python3.7-Cython-0.29.14.drv' failed
```

**Comment by vcunat** [comment]
My "dumb" bisection showed
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
26f635d39aa69b740c938349f8034b281a6663ca
42b203573072bc0df6285c1a3dd458eaaffd84dd
c71ab32a678a98ce1ec069956bc55d6ea606f55c
f29919da616a51d805ef1cf3800d023d9d00e2dc
4b2ab665fbeb28b9837e920841ca81c570dfbdd4
We cannot bisect more!
```
and all of that are his commits around pkgconf(ig), so I'd hope he might know easily what got wrong in particular.

**Comment by vcunat** [comment]
Still, note that the error is not present in this PR, i.e. it's ATM in `staging-next..staging`.

**Pull request merged**
