### PR TITLE
spidermonkey 38: drop

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
Carrying around a 5 year old version of a javascript engine seems like a bad idea.

I didn't manage to test plowshare too well, but it should work, because it's all shell scripts calling `js` on the command line.

pyLoad could potentially be fixed, but they still haven't released 0.5.x and 0.4.x is [ancient](https://github.com/pyload/pyload/releases/tag/v0.4) (idk why that says 2017, if you click [the commit](https://github.com/pyload/pyload/commit/e921a8a45fa785db160d2b1e518e871028454d2f) you can see that it's from 2010), although [still maintained](https://github.com/pyload/pyload/issues/3520).
However, the commit currently in nixpkgs is from 2016 and as a former user of pyload a release this old is IMHO useless.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aforemny** [comment]
Result of `nixpkgs-review pr 117092` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>jsawk</li>
    <li>plowshare</li>
  </ul>
</details>

**Comment by aforemny** [comment]
LGTM!

I think I agree we could drop pyload since it does not seem to be actively maintained. If no one else beats me to it or objects, I will merge this on Friday. @2chilled do you have any objections?

**Review by aforemny — APPROVED** [review]

**Comment by 2chilled** [comment]
@aforemny In the meantime I can afford paying for media so dropping pyload doesn't affect me anymore ;)

**Comment by aforemny** [comment]
Since @2chilled replied already, I will merge now. Thank you for this, @ajs124 !

**Pull request merged**
