### PR TITLE
qt512: fix darwin patches

### PR DESCRIPTION
**Pull request by ttuegel**
###### Motivation for this change

The patches for Qt 5.12 on Darwin no longer apply. Although I cannot test the build on macOS, I can make the Darwin patches apply on all platforms because the patches target only platform-specific files.

See also: https://github.com/NixOS/nixpkgs/pull/107483#issuecomment-752998482

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by prusnak — APPROVED** [review]
I confirmed the patches do not apply on master when run on darwin (i.e. we need this PR to fix the build failure on master).
I confirmed the patches do apply in a61f20e when run on darwin and qt512 starts to build on darwin.
I have not tested the full build on darwin.

**Comment by ttuegel** [comment]
I'm still waiting on `nixpkgs-review` to verify that all the dependent packages build.

**Comment by r-burns** [comment]
Have not tested all deps, but this unblocks qtmultimedia :+1:

**Comment by ttuegel** [comment]
I didn't find any new failures in the dependent packages.

**Comment by SuperSandro2000** [comment]
I will let you know if I see any other darwin related failures in qt.

**Pull request merged**
