### PR TITLE
xserver: replace XKB_BINDIR with compile time option

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

Main motivation for this change is that new versions of gdm create a new session for the user and don't inherit the calling environment and then start x inside that session.

CC @edolstra 
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Using the configure option relieves us of the patch and passing the path
via the env var in many places. Also the env var may not be inherited
when components like gdm spawn new sessions.

### CODE REVIEW

**Comment by edolstra** [comment]
This patch in itself looks good to me, but if `gdm` doesn't inherit the environment, then presumably it will also lack the other environment variables that we pass to the X server? (`LD_LIBRARY_PATH`, `XORG_DRI_DRIVER_PATH`)

**Comment by groxxda** [comment]
@edolstra yes that may also be a problem. I'm still testing everything.
We also pass in extra flags to the xserver from our displaymanager module that are problematic (`services.xserver.displayManager.xserverArgs` -> `GDM_X_SERVER`). I have a patch for the gdm session launcher that passes this environment variable. It's still needed for the `xkbdir` and `config` parameters.
If this PR is accepted I am going to investigate further.

I guess the `XORG_DRI_DRIVER_PATH` could also be patched into the xserver since it's static @ `/run/opengl-driver/lib/dri` anyways.

We do set it to `${mesa}/lib/dri` in our wrapper for `Xvfb`, but I don't yet understand why this is an exception.

I'm always thankful for helping input :wink: 

Right now gdm 3.22 starts successfully with this PR and the mentioned patch to pass through GDM_X_SERVER.
So we could finally update gdm (it's currently stuck at 3.14 :confused:) and what's even more exciting, this setup runs x without root rights.
I'll cleanup and rewrite my history and update the gnome PR with the new state.

**Comment by groxxda** [comment]
Apart from the GDM discussion, this patch is a clear improvement in my opinion because it removes an impurity

**Comment by groxxda** [comment]
After rebooting my laptop into gdm 3.22 (previous testing was in a vm), I can confirm that DRI still works:
```
=======================================================
    glmark2 2014.03
=======================================================
    OpenGL Information
    GL_VENDOR:     Intel Open Source Technology Center
    GL_RENDERER:   Mesa DRI Intel(R) Haswell Mobile 
    GL_VERSION:    3.0 Mesa 12.0.2
=======================================================
```
I grepped `xorg.xorgserver.src` for `DRI_DRIVER_PATH` and could not find an occurence with `XORG_` prefix. This leads me to believe that setting `XORG_DRI_DRIVER_PATH` has no impact (or is it used in another xorg package?)

It works without this env var because xorgserver's configure script discovers `DRI_DRIVER_PATH` via pkg-config:
```
[nix-shell:/tmp/xorg-server-1.18.3]$ pkg-config  --variable=dridriverdir dri
/run/opengl-driver/lib/dri
```  


If someone confirms my assumptions, I'll file a PR removing `XORG_DRI_DRIVER_PATH` 

@edolstra ? :relaxed:

**Comment by edolstra** [comment]
It's certainly possible `XORG_DRI_DRIVER_PATH` no longer does anything.

I do think `LD_LIBRARY_PATH` is necessary for the proprietary NVIDIA driver and other non-Mesa drivers. A more general solution would be to generate a wrapper script for the X server that sets the required environment variables.

**Pull request merged**
