### PR TITLE
hyper-haskell: 0.1.0.2 -> 0.2.1.0

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build hyper-haskell

**Comment by xeji** [comment]
Doesn't build, missing dependency.

**Comment by vaibhavsagar** [comment]
The bounds on `aeson` are too restrictive, should I use `doJailbreak` here?

**Comment by mpickering** [comment]
That might work but I'm not sure it would. You could add the correct version of aeson to this list, https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L2370 and then when the packages are regenerated use that package explicitly `{ aeson = aeson_1_2_4_0 }`.

**Comment by peti** [comment]
@vaibhavsagar, do you still wish to pursue this PR?

You should probably report the over-specified constraints upstream so that they can fix them.

**Comment by ryantm** [comment]
Closing due to lack of response. Feel free to reopen later!

**Pull request closed without merging**
