### PR TITLE
git-machete: init at 2.12.1

### PR DESCRIPTION
**Pull request by blitz**
###### Motivation for this change

Git machete is a tool for automating rebase-based workflows. See https://github.com/VirtusLab/git-machete for details.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @tfc @jtraue

### CODE REVIEW

**Comment by tfc** [comment]
Works on macOS 10.15

**Review by tfc — APPROVED** [review]

**Comment by teto** [comment]
this looks interesting. Do you plan to add the completion files ? with installShellCompletion for instance

**Comment by blitz** [comment]
> this looks interesting. Do you plan to add the completion files ? with installShellCompletion for instance

Good point. Will do.

**Comment by blitz** [comment]
@teto I've added it unconditionally, as this is what the other git tools do as well. Tested successfully on NixOS.

**Comment by doom3wasagoodgame** [comment]
:+1: LGTM

**Review by Br1ght0ne — CHANGES_REQUESTED** [review]
You can use `installShellCompletion`:

```diff
-      install -D completion/git-machete.completion.bash $out/etc/bash_completion.d/git-machete
-      install -D completion/git-machete.completion.zsh $out/share/zsh/site-functions/_git-machete
+      installShellCompletion
+        --name git-machete completion/git-machete.completion.bash
+        --name _git-machete completion/git-machete.completion.zsh
```

**Comment by blitz** [comment]
> ```diff
> installShellCompletion
> ```

TIL. I've updated the PR to include this.

**Review by Br1ght0ne — APPROVED** [review]

**Review by worldofpeace — CHANGES_REQUESTED** [review]
This doesn't build for me because you're missing `pbr` in `nativeBuildInputs`
* https://github.com/VirtusLab/git-machete/blob/master/setup.py

Also, can we setup tests?
Those dependencies are at https://github.com/VirtusLab/git-machete/blob/master/test-requirements.txt, and belong in `checkInputs`. The test runner is `tox`.

**Comment by filalex77** [comment]
```patch
diff --git a/pkgs/applications/version-management/git-and-tools/git-machete/default.nix b/pkgs/applications/version-management/git-and-tools/git-machete/default.nix
index 353309e77a3..aafaa6659d3 100644
--- a/pkgs/applications/version-management/git-and-tools/git-machete/default.nix
+++ b/pkgs/applications/version-management/git-and-tools/git-machete/default.nix
@@ -1,4 +1,6 @@
-{ lib, buildPythonApplication, fetchPypi, python3Packages, installShellFiles }:
+{ lib, buildPythonApplication, fetchPypi
+, installShellFiles, pbr
+, flake8, mock, pycodestyle, pylint, tox }:
 
 buildPythonApplication rec {
   pname = "git-machete";
@@ -9,9 +11,12 @@ buildPythonApplication rec {
     sha256 = "114kq396zq45jlibn1lp0nk4lmanj4w1bcn48gi7xzdm0y1nkzfq";
   };
 
-  nativeBuildInputs = [ installShellFiles python3Packages.pbr ];
+  nativeBuildInputs = [ installShellFiles pbr ];
 
-  checkInputs = with python3Packages; [ flake8 mock pycodestyle pylint stestr tox ];
+  # TODO: Add missing check inputs (2019-11-22):
+  # - stestr
+  doCheck = false;
+  checkInputs = [ flake8 mock pycodestyle pylint tox ];
 
   postInstall = ''
       installShellCompletion --bash --name git-machete completion/git-machete.completion.bash
```

**Comment by worldofpeace** [comment]
Ah, merci bien @filalex77 :sparkles: 

That should be fine.

**Comment by filalex77** [comment]
@blitz You can `git apply <(curl https://github.com/filalex77/nixpkgs/commit/5d7f3dbc9f68158d890af4a40d5d93c4bae6f28a.diff)` to apply this diff.

**Comment by blitz** [comment]
@worldofpeace @filalex77 Done.

**Review by worldofpeace — APPROVED** [review]

**Pull request merged**
