### PR TITLE
imagemagick6: 6.9.12-1 -> 6.9.12-3

### PR DESCRIPTION
**Pull request by erictapen**
###### Things done

Added myself as maintainer.

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
/rebase master

Since version 7 is the default now, this won't cause a lot of rebuilds.

**Review by dotlambda — CHANGES_REQUESTED** [review]
Please rebase on master and use `imagemagick6` in the commit message.

**Comment by erictapen** [comment]
@dotlambda done

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 116330` at c528ddd2 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/71af58baa23d57082ea19512c01d44c5">cataract</a></li></li>
    <li><a href="https://gist.github.com/8f571a0da10dc857bfab17d160c03abc">cataract-unstable</a></li></li>
    <li><a href="https://gist.github.com/ff8eae090d8702c07862ad29d0b0736c">fmbt</a></li></li>
    <li><a href="https://gist.github.com/77574cd7670baca57d2a4316d9e4d5ae">imagemagick6</a></li></li>
    <li><a href="https://gist.github.com/4a021272e8ca97ed4f7d25122cc60ac2">imagemagick6Big</a></li></li>
    <li><a href="https://gist.github.com/e2ebc2022154902a092249f0c6b1df83">imagemagick6_light</a></li></li>
    <li><a href="https://gist.github.com/f824d69e72d9a91bf1b3aa516d5c76db">pfstools</a></li></li>
    <li><a href="https://gist.github.com/1c7ff9f95bdfc2b7e6673671172d51ce">rss-glx</a></li></li>
  </ul>
</details>

**Comment by dotlambda** [comment]
@erictapen Will you do the backport? That will have to go to `staging-20.09` though.

**Comment by erictapen** [comment]
@dotlambda sure!

**Pull request merged**
