### PR TITLE
Better xdg_utils

### PR DESCRIPTION
**Pull request by oxij**
The first patch here will cause a lof of rebuilds, since a lot of stuff depends on cups.

### CODE REVIEW

**Comment by lethalman** [comment]
Not really convinced to use this fork of xdg utils...

**Comment by oxij** [comment]
@lethalman it's optional, nothing changes by default

**Comment by lethalman** [comment]
Ok, the .desktop with xdg-open is basically useless to my knowledge. mime apps are recognized using the .desktop content, xdg uses the mime to open the document using that .desktop. So, it's xdg-open that uses the .desktop somehow, doesn't make sense to set xdg-open as Exec of a desktop file.

Do you have any example in any other distro/app that sets xdg-open for a .desktop?

**Comment by oxij** [comment]
Yep, that looks crazy. But if you look at the `cups.desktop` before this change you'll notice it is set to `/nix/store/*-xdg_utils-*/bin/xdg-open` there too. That works because all this `xdg-open` does is fires up a browser on the specified cups-config URL.

**Comment by lethalman** [comment]
Ok I see.... If you PR against staging I will merge.

**Comment by lethalman** [comment]
Merged into staging.

**Pull request closed without merging**
