### PR TITLE
factorio: Add Wayland support; format drv

### PR DESCRIPTION
**Pull request by amarshall**
###### Description of changes

Factorio 1.1.77 adds Wayland support, so make the necessary libs
available.

https://forums.factorio.com/viewtopic.php?p=582261

###### Things done

Tested on Sway, verified game indeed runs with Wayland (with `SDL_VIDEODRIVER=wayland`) and loads to menu and can start a game.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ocfox — COMMENTED** [review]
LGTM, but code format may not necessary, it affects the reading.

**Review by erictapen — COMMENTED** [review]
:+1: for the formatting

But I don't see wayland working?

I'm running it on Sway like this:

```
SDL_VIDEODRIVER=wayland ./result/bin/factorio
```

I'm testing it with xeyes, the eyes are still moving when I move the cursor into the factorio window. Am I missing something?

**Comment by erictapen** [comment]
I'm afraid that also the check via `swaymsg` shows xwayland for me:

```json
                {
                  "id": 146,
                  "type": "con",
                  "orientation": "none",
                  "percent": 1.0,
                  "urgent": false,
                  "marks": [
                  ],
                  "focused": false,
                  "layout": "none",
                  "border": "pixel",
                  "current_border_width": 2,
                  "rect": {
                    "x": 803,
                    "y": 80,
                    "width": 792,
                    "height": 815
                  },
                  "deco_rect": {
                    "x": 0,
                    "y": 25,
                    "width": 792,
                    "height": 25
                  },
                  "window_rect": {
                    "x": 2,
                    "y": 2,
                    "width": 788,
                    "height": 813
                  },
                  "geometry": {
                    "x": 0,
                    "y": 0,
                    "width": 1600,
                    "height": 900
                  },
                  "name": "Factorio 1.1.77",
                  "window": 20971528,
                  "nodes": [
                  ],
                  "floating_nodes": [
                  ],
                  "focus": [
                  ],
                  "fullscreen_mode": 0,
                  "sticky": false,
                  "pid": 288071,
                  "app_id": null,
                  "visible": true,
                  "max_render_time": 0,
                  "shell": "xwayland",
                  "inhibit_idle": false,
                  "idle_inhibitors": {
                    "user": "none",
                    "application": "none"
                  },
                  "window_properties": {
                    "class": ".factorio-wrapped",
                    "instance": ".factorio-wrapped",
                    "title": "Factorio 1.1.77",
                    "transient_for": null,
                    "window_type": "normal"
                  }
                },
```

Again, this is how I run it: `SDL_VIDEODRIVER=wayland  factorio`. On latest nixos-22.11, sway. Is there any other environment variable that I'm missing?

**Comment by ocfox** [comment]
```sh
Window 542f650 -> Factorio 1.1.77:
	mapped: 1
	hidden: 0
	at: 2099,21
	size: 457,696
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: .factorio-wrapped
	title: Factorio 1.1.77
	pid: 20161
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```
Work fine on my machine. Are you use 1.77? I check that the Factorio version is 1.70 on 22.11.(https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/games/factorio/versions.json)

**Comment by ocfox** [comment]
Work fine on my hyprland.
```sh
Window 542f650 -> Factorio 1.1.77:
	mapped: 1
	hidden: 0
	at: 2099,21
	size: 457,696
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: .factorio-wrapped
	title: Factorio 1.1.77
	pid: 20161
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

**Review by ocfox — APPROVED** [review]

**Comment by erictapen** [comment]
Ok cool, there seems to be some problem with my setup then. Thanks!

**Pull request merged**
