### PR TITLE
xsimd: fix cross compilation

### PR DESCRIPTION
**Pull request by superherointj**
xsimd: fix cross compilation, enable strictDeps
xsimd: move package to by-name
xsimd: add meta.changelog

Fixes #321253

### CODE REVIEW

**Comment by doronbehar** [comment]
I'm down to setting `strictDeps = true;` BTW, if a good comment is written near it.

**Comment by superherointj** [comment]
> I'm down to setting `strictDeps = true;` BTW, if a good comment is written near it.

Sorry. I don't know what to comment on `strictDeps`.
I usually think of `strictDeps` as something that should be ideally true.
If you have a suggestion, let me know.

**Comment by doronbehar** [comment]
Maybe a comment such as:

```
# Setting strictDeps helps raise the chance that xsimd will be able to be cross compiled as well
```

But format it to 80 characters please :)

**Comment by uninsane** [comment]
the first two commits (fixing cross compilation, then setting strictDeps = true) should be squashed into a single commit. otherwise, builds fine and looks good to me.

**Comment by superherointj** [comment]
> the first two commits (fixing cross compilation, then setting strictDeps = true) should be squashed into a single commit.

The commits are separate to preserve credit.

**Comment by uninsane** [comment]
> > the first two commits (fixing cross compilation, then setting strictDeps = true) should be squashed into a single commit.
> 
> The commits are separate to preserve credit.

i'd rather a clean commit history than to be credited, to be honest. you can squash the commits with you as commit author, and add to the commit message body `Co-Authored-By: Colin <colin@uninsane.org>`. or just leave yourself as commit author & don't mention me at all.

**Review by uninsane — APPROVED** [review]

**Review by tobim — APPROVED** [review]

**Comment by doronbehar** [comment]
I like how the commits are ordered now - makes it easier to track changes IMO.

**Pull request merged**
