### PR TITLE
libreoffice-fresh: 7.0.4.2 -> 7.1.0.3 & libreoffice-still: 6.3.5.2 -> 7.0.4.2

### PR DESCRIPTION
**Pull request by TredwellGit**
Merge after https://github.com/NixOS/nixpkgs/pull/111877.

###### Motivation for this change
https://wiki.documentfoundation.org/ReleaseNotes/7.1

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
Hold off on merging this even after https://github.com/NixOS/nixpkgs/pull/11187; I noticed some other things that I want to improve.

**Comment by mohe2015** [comment]
@TredwellGit does this run for you currently? I tried enabling postgresql support and updating and it doesn't run. I'm not sure if the postgresql support is the problem and I would like to avoid rebuliding.
[strace.log](https://github.com/NixOS/nixpkgs/files/5926092/strace.log)

**Comment by TredwellGit** [comment]
How did you enable PostgreSQL support?

**Comment by mohe2015** [comment]
Disregard, a full reboot fixed it. Likely a dbus thing.

**Comment by TredwellGit** [comment]
I will look into enabling PostgreSQL by default.

**Comment by TredwellGit** [comment]
Also going to update libreoffice-still.

**Comment by mohe2015** [comment]
> I will look into enabling PostgreSQL by default.

I think the main problem is that it pulls in the full postgresql library although that may be avoided using `postgresql.libs`. But it would still need to build that.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/issues/90858 https://github.com/NixOS/nixpkgs/issues/90863

**Review by 7c6f434c — APPROVED** [review]
(provided both versions build)

**Comment by TredwellGit** [comment]
They both build and work.

**Comment by 7c6f434c** [comment]
Do you still consider this a draft, or is it now ready to merge?

**Comment by TredwellGit** [comment]
This can be merged then https://github.com/NixOS/nixpkgs/pull/111877 can be closed.

**Pull request merged**
