### PR TITLE
ollama: 0.1.17 -> 0.1.21

### PR DESCRIPTION
**Pull request by peperunas**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by TanvirOnGH** [comment]
Huh? The patch fails:

```nix
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/viw7yp4v3f3207rgil61kqsivxjy7bs7-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
applying patch /nix/store/3cqcxwslq4lvrnbmqzgzvnapr9nb2wfp-disable-gqa.patch
patching file llm/llama.go
Hunk #1 FAILED at 299.
1 out of 1 hunk FAILED -- saving rejects to file llm/llama.go.rej
```

Both [disable-gqa.patch](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/ollama/disable-gqa.patch) and [set-llamacpp-path.patch](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/ollama/set-llamacpp-path.patch) fails.

**Comment by peperunas** [comment]
Yes, my bad. For some reasons, on my setup was compiling with no errors (???) and have been using 0.1.20 for a while. I am taking a look at this now. Converted to draft for the time being.

**Comment by peperunas** [comment]
@TanvirOnGH, can you try now please?

**Comment by TanvirOnGH** [comment]
@peperunas 
```nix
$ nix-env --extra-experimental-features no-url-literals --option system x86_64-linux -f <nixpkgs> --nix-path nixpkgs=/home/user/.cache/nixpkgs-review/pr-283496-4/nixpkgs nixpkgs-overlays=/tmp/tmpdmpn18g5 -qaP --xml --out-path --show-trace --no-allow-import-from-derivation --meta
1 package updated:
ollama (0.1.17 → 0.1.21)

$ nix build --nix-path nixpkgs=/home/user/.cache/nixpkgs-review/pr-283496-4/nixpkgs nixpkgs-overlays=/tmp/tmpdmpn18g5 --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed -f /home/user/.cache/nixpkgs-review/pr-283496-4/build.nix
error: builder for '/nix/store/2m27p3qlh39ya4isx54siaxhmkxmh38w-ollama-0.1.21-go-modules.drv' failed with exit code 1;
       last 10 log lines:
       > + NO_WHOLE_ARCHIVE=-Wl,--no-whole-archive
       > + GCC_ARCH=
       > + git_module_setup
       > + '[' -n '' ']'
       > + '[' -d ../llama.cpp/gguf ']'
       > + git submodule init
       > fatal: not a git repository (or any parent up to mount point /)
       > Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       > llm/generate/generate_linux.go:3: running "bash": exit status 128
       > /nix/store/v5irq7wvkr7kih0hhnch5nnv2dcq8c4f-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/2m27p3qlh39ya4isx54siaxhmkxmh38w-ollama-0.1.21-go-modules.drv'.
error: 1 dependencies of derivation '/nix/store/agfkqcjrzg8l853rxww9z5f8yzp3nmgw-ollama-0.1.21.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7k36hbypqdgr5ja9p9429biadx3kf1r9-review-shell.drv' failed to build
```

```
$ nix log /nix/store/2m27p3qlh39ya4isx54siaxhmkxmh38w-ollama-0.1.21-go-modules.drv
...
go: downloading github.com/twitchyliquid64/golang-asm v0.15.1
+ set -o pipefail
+ echo 'Starting linux generate script'
Starting linux generate script
+ '[' -z '' ']'
+ '[' -x /usr/local/cuda/bin/nvcc ']'
++ command -v nvcc
+ export CUDACXX=
+ CUDACXX=
+ COMMON_CMAKE_DEFS='-DCMAKE_POSITION_INDEPENDENT_CODE=on -DLLAMA_NATIVE=off -DLLAMA_AVX=on -DLLAMA_AVX2=off -DLLAMA_AVX512=off -DLLAMA_FMA=off -DLLAMA_F16C=off'
++ dirname ./gen_linux.sh
+ source ./gen_common.sh
+ init_vars
+ case "${GOARCH}" in
+ ARCH=x86_64
+ LLAMACPP_DIR=../llama.cpp
+ CMAKE_DEFS=
+ CMAKE_TARGETS='--target ext_server'
+ echo ''
+ grep -- -g
+ CMAKE_DEFS='-DCMAKE_BUILD_TYPE=Release -DLLAMA_SERVER_VERBOSE=off '
+ case $(uname -s) in
++ uname -s
+ LIB_EXT=so
+ WHOLE_ARCHIVE=-Wl,--whole-archive
+ NO_WHOLE_ARCHIVE=-Wl,--no-whole-archive
+ GCC_ARCH=
+ git_module_setup
+ '[' -n '' ']'
+ '[' -d ../llama.cpp/gguf ']'
+ git submodule init
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
llm/generate/generate_linux.go:3: running "bash": exit status 128
/nix/store/v5irq7wvkr7kih0hhnch5nnv2dcq8c4f-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
```

**Comment by peperunas** [comment]
I am stuck. The problem here is that they are building `llama-cpp`'s server in an unconventional way: https://github.com/ollama/ollama/blob/f63dc2db5c00de0f6b0b5ea9b53bb20e83513cea/llm/generate/gen_common.sh#L69.

I get ollama to run but then I get a segfault as soon as a request is done to the server.

**Comment by peperunas** [comment]
Update, gonna raise my hands here. I also tried no to use `llama-cpp` from nixpkgs and let `ollama`'s script to build their version of `llama-cpp`. 

Some checks are broken in that case (https://github.com/ollama/ollama/blob/f63dc2db5c00de0f6b0b5ea9b53bb20e83513cea/llm/generate/gen_linux.sh#L134). It seems this is a pretty deep rabbit hole.

**Comment by TanvirOnGH** [comment]
Will have to agree. The rabbit hole is really deep. I've put in several hours of effort, but I haven't achieved any success yet.

**Comment by natsukium** [comment]
see also https://github.com/NixOS/nixpkgs/pull/281812
Both llama-cpp and ollama seem to have upstream problems.

**Comment by TanvirOnGH** [comment]
update: 0.1.22 is the latest version. https://github.com/ollama/ollama/releases/tag/v0.1.22

**Comment by TanvirOnGH** [comment]
I've found a flake that builds ollama v0.1.23 with proper cpu, rocm and cuda support: https://github.com/abysssol/ollama-flake. Thanks to @abysssol

**Comment by drupol** [comment]
Dear @abysssol,

Do you have plan to merge your flake in `nixpkgs`, it would be amazing to have it.

**Comment by siph** [comment]
For anyone else watching this, there is another active pr for ollama here: https://github.com/NixOS/nixpkgs/pull/289108

**Pull request closed without merging**
