### PR TITLE
nixos/slim: remove

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Let's :wave: goodbye to SLIM.
We've already changed the default display manager to LightDM for the exact reasons why it's being removed here https://github.com/NixOS/nixpkgs/pull/30890. The next logical step is to remove it entirely. 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
I've already made the graphical iso use sddm https://github.com/NixOS/nixpkgs/pull/71622, which makes the most sense for a Plasma 5 desktop.

**Comment by jtojnar** [comment]
Needs release notes.

**Comment by worldofpeace** [comment]
> Needs release notes.

Did that :+1:.

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/blob/b90985c8e16c0e2816476a457cb7e32de99563ca/nixos/modules/services/x11/display-managers/default.nix#L3

**Comment by worldofpeace** [comment]
@jtojnar https://github.com/NixOS/nixpkgs/blob/b90985c8e16c0e2816476a457cb7e32de99563ca/nixos/modules/installer/cd-dvd/installation-cd-graphical-base.nix#L29-L30 was removed in c9601a67a5539b7d57b08cc017bc20c7f9bb062c, my branch needed to be rebased. 

The others were corrected in the force push.

**Review by jtojnar — APPROVED** [review]

**Comment by avnik** [comment]
;(
Any alternatives to slim, not pulling massive toolkits, like gnome or kde?
It would be sad to revert to xdm, as well as need tons of stuff need for DM only.

**Comment by Lassulus** [comment]
hmm, personally I would not remove stuff which still works and isn't maintained anymore. But I can see the point to not ship unmaintained stuff anymore and higher the burden for people to migrate to maintained grounds.

@avnik maybe something like `services.xserver.displayManager.startx.enable` is something for you?

**Comment by worldofpeace** [comment]
It doesn't work probably, in that it doesn't fully support systemd and especially logind sessions.
With NixOS being tied to systemd this is going to be an issue. All other display managers in nixpkgs support systemd properly.

**Comment by rnhmjoj** [comment]
👎  for me.

LightDM, despite the name, is not lightwight and I don't know of any other comparable software, besides no display manager at all (startx). Slim has problems and that's fine for not being the default DM but I don't see how removal should be a logical consequence of that decision.

I don't think keeping slim around requires any extra work and we have plenty of old unmaintained software that still works and is useful to some.

**Comment by worldofpeace** [comment]
Here's mostly what I had to say about this
* https://logs.nix.samueldr.com/nixos-chat/2019-11-12#2776524; (and comments after and before)

most of the discussion happened in nixos-chat.

Bottom line is unmaintained software just doesn't belong in nixpkgs, and if people rely on software that's unmaintained in nixpkgs we already have an issue. In this kind of situation we usually have to do one of two things:
1. Search for a maintainer or someone willing to step up to maintain its integration in NixOS
IMHO, we're way past that point and many years.

2. Remove SLIM
We'd be kidding ourselves presenting like we can keep up integration with it its current state.

No one anywhere has stepped up to actually maintain it, though perhaps @cleverca22 has something in mind. But at that point you might as well start from scratch and make a display-manager.

Now someone could easily add this module and package to NUR and keep using it, but it doesn't change the fact that we can't support it.

**Comment by oxij** [comment]
Ugh. A perfectly happy user of slim here.

0) Let me remind you that slim is the only display manager that actually properly works (defined as "does not leak resources after you login and does not hand after you logout") for automatic logins, see https://github.com/NixOS/nixpkgs/pull/46396 and https://github.com/NixOS/nixpkgs/pull/30890#issuecomment-419670755. So, I'd say removing it is unproductive.

As to your other arguments:

> Bottom line is unmaintained software just doesn't belong in nixpkgs, and if people rely on software that's unmaintained in nixpkgs we already have an issue.

1) Firstly, I disagree. IMHO, if it is not broken, nixpkgs should provide it. I (and you, and everyone else) use plenty on unmaintained software.

- If it just works you don't need to maintain it. E.g. Emacs minor modes that were written in 90's and still just work with zero changes.

- If it works for your inputs and it is not designed to take untrusted data it's nobody's business if it is not maintained. E.g. we keep old unmaintained versions of Firefox because some old plugins for offline use just won't ever be rewritten for the new plugin API Firefox adapted from Chromium.

2) You yourself mention in

> * https://logs.nix.samueldr.com/nixos-chat/2019-11-12#2776524; (and comments after and before)

that it is not actually unmaintaned since Gentoo guys maintain it in https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-misc/slim/files.

What is the problem with just applying those patches, exactly? Are there any open issues about slim that can't be fixed by applying those patches?

(Also, I can't stop myself from mentioning that it works perfectly fine without Gentoo patches unless you use systemd, which is telling more about systemd than about slim. But I wasn't happy with https://github.com/NixOS/nixpkgs/pull/30890 and the argument there either. So, this line of reasoning should probably be classified as an ideological argument. So, whatever.)

**Comment by worldofpeace** [comment]
> that it is not actually unmaintaned since Gentoo guys maintain it in https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-misc/slim/files.

I mentioned that Gentoo had patches from certain places, we haven't identify their sources or authorship.
My initial assumption is that they're patches left behind from various efforts to fix certain things about slim. A distro carrying patches doesn't connotate the intrinsically different type of maintenance slim needs, a developer and proper systemd support. I would mention that it's more reasonable to remove something when alternatives exist, but it stands you weren't pleased with that reasoning https://github.com/NixOS/nixpkgs/pull/30890.

---

Also, a display-manager is a much different kind of software than the examples you've mentioned.
You can say certain software requires different types of effort in upkeep. I'm easily convinced it's much more difficult than an emacs mirror mode or a Firefox plugin. I'm thinking of security too.

**Comment by oxij** [comment]
>> that it is not actually unmaintaned since Gentoo guys maintain it in https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-misc/slim/files.
>
> I mentioned that Gentoo had patches from certain places, we haven't identify their sources or authorship.
> My initial assumption is that they're patches left behind from various efforts to fix certain things about slim. A distro carrying patches doesn't connotate the intrinsically different type of maintenance slim needs, a developer and proper systemd support.

I looked over them, and all of those patches seem very sane, most are trivial.

Of those patches https://gitweb.gentoo.org/repo/gentoo.git/plain/x11-misc/slim/files/slim-1.3.5-arm.patch and https://gitweb.gentoo.org/repo/gentoo.git/plain/x11-misc/slim/files/slim-1.3.6-envcpy-bad-pointer-arithmetic.patch fix actual bugs.

Systemd support is implemented with two patches https://gitweb.gentoo.org/repo/gentoo.git/plain/x11-misc/slim/files/slim-1.3.6-systemd-session.patch and https://gitweb.gentoo.org/repo/gentoo.git/plain/x11-misc/slim/files/slim-1.3.5-disable-ck-for-systemd.patch both of which told me more about systemd than about slim, as I expected.

The rest are changes to the build scripts and Gentoo-specific things.

I'd say that's pretty high quality software, considering the date of the last release.

> I would mention that it's more reasonable to remove something when alternatives exist, but it stands you weren't pleased with that reasoning https://github.com/NixOS/nixpkgs/pull/30890.

Yes, I don't consider lightdm to be an alternative to slim. It is 6 (!) times larger. It also pretty much broken for automatic logins.

> Also, a display-manager is a much different kind of software than the examples you've mentioned.
> You can say certain software requires different types of effort in upkeep. I'm easily convinced it's much more difficult than an emacs mirror mode or a Firefox plugin.

Why? X11 authorization and session infra is set in stone, more or less. AFAICS, the only source of breakage there is systemd.

> I'm thinking of security too.

1) It's not a default.

2) It requires keyboard input. Which, pretty much, means physical access to the machine. Which makes all the usual security arguments moot.

3) Even then, I would argue that slim is _more_ secure than lightdm by any reasonable metric. It requires less libraries, thus less code, less bugs. It's login and lock screen theming mechanisms are much simpler, don't allow any scripting.

I reverted this locally, added Gentoo patches on top. Building a NixOS VM now. Will test and then PR the result later.

**Comment by oxij** [comment]
Done https://github.com/NixOS/nixpkgs/pull/75389.

I ended up making up my own fork because I was unhappy about many of the patches in Gentoo and other forks of slim available elsewhere.

**Pull request merged**
