### PR TITLE
ledger-live-desktop: fix build

### PR DESCRIPTION
**Pull request by flokli**
This patch had to be reapplied, it failed to apply with systemd 252.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
Hold off merging this yet - https://github.com/systemd/systemd/commit/c0aa23cf1ed4b3cbbcaf8b19d47e6e29dc28c9a0 might suggest we don't need this patch anymore.

**Comment by edef1c** [comment]
Upstream already seems to be relaxing this check as of v252, so I think we can drop the patch: https://github.com/systemd/systemd/commit/c0aa23cf1ed4b3cbbcaf8b19d47e6e29dc28c9a0.

**Comment by edef1c** [comment]
Upstream already seems to be relaxing this check as of v252, so I think we can drop the patch: https://github.com/systemd/systemd/commit/c0aa23cf1ed4b3cbbcaf8b19d47e6e29dc28c9a0.
Having tested without it, it connects to my Ledger device just fine.

**Comment by flokli** [comment]
> Upstream already seems to be relaxing this check as of v252, so I think we can drop the patch: [systemd/systemd@c0aa23c](https://github.com/systemd/systemd/commit/c0aa23cf1ed4b3cbbcaf8b19d47e6e29dc28c9a0). It connects to my Ledger device just fine without it.

Thanks for confirming! So looks like we can drop the patch all together. Do you want to update the PR with that and merge, or should I get to it later?

**Comment by edef1c** [comment]
On further testing, it seems to work fine entirely without `extraPackages = [ systemd ]`. The AppImage does not seem to contain any files related to systemd or udev. Maybe they dropped the libsystemd dependency?

It's not unusual for libsystemd/udev to get loaded by way of dlopen when available (without crashing if it is unavailable, like `DT_NEEDED` would), especially by Chromium-based apps, but there don't seem to be any log messages related to it being missing.

I'm not familiar enough with AppImage, but my understanding was that they're supposed to be a fully self-contained rootfs, similar to a Docker image, so I assume that even on impure distros there is no system-supplied libsystemd injected into the app environment. Presumably we were injecting _ours_ solely to override a previously-present libsystemd that didn't play well with user namespaces.

Unless I'm misunderstanding something, I think we should just drop the `systemd` dependency entirely.

**Comment by flokli** [comment]
So we should probably check ledger-live-desktop sources to see if/how they depend on udev now?

**Comment by edef1c** [comment]
I patched the AppImage wrapping to run the app under strace, and it _does_ seem to actually hunt for libudev/libsystemd. I'm not sure what _for_, given that it works entirely fine without it, but it seems prudent to at least have it written down.
I do seem to be at least somewhat mistaken about how isolated AppImages are from the ambient environment, given that there is no glibc or dynamic linker present in the image. It might be worth going for the compromise of leaving it in, in case some untested functionality in the app does rely on it, like firmware upgrades or initial device setup/discovery.

**Comment by edef1c** [comment]
Looking a little more closely, the AppImage FHS provides libudev and libsystemd, so we don't need to do anything at all at the package level either way.

**Comment by harryprayiv** [comment]
This breaks my configuration still.  

`error: 1 dependencies of derivation '/nix/store/ppj81b67wl3i66jrjp6slv5iiwslmxsi-ledger-live-desktop-2.50.0-usr-target.drv' failed to build
error: 1 dependencies of derivation '/nix/store/599dzyp8rg9mjczn7x11a8xmpz9m2hki-ledger-live-desktop-2.50.0-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cjs6azkzcdwplkjifw5bk9h7zy7ad4x1-ledger-live-desktop-2.50.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ykn56rncv12afd5frk1as1vfz8q72h05-ledger-live-desktop-2.50.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8fhbndm8pxf7jxpqbbs9m37jj2494125-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wy5w41cgvr1sh20yi298nqg8s4vnbm1r-ledger-live-desktop-2.50.0-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kz6l1w4ha5fmgqrkg3gp2iqx2ac1gcp5-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/k5bamvhf9mwvgj0dw4dn309iwxzga0sr-home-manager-generation.drv' failed to build`

ansd here's the relevant log:

`applying patch /nix/store/krabvdhsf0461lrw1yzmy8na8wmqrwc7-0012-add-rootprefix-to-lookup-dir-paths.patch
patching file src/basic/def.h
applying patch /nix/store/i8qy44l1l4qbcm2hvvzqm7bnkvf1fmp3-0013-systemd-shutdown-execute-scripts-in-etc-systemd-syst.patch
patching file src/shutdown/shutdown.c
applying patch /nix/store/61ksv4hsyi90fb9hm36qcs9qgg06ya9k-0014-systemd-sleep-execute-scripts-in-etc-systemd-system-.patch
patching file src/sleep/sleep.c
applying patch /nix/store/k8g0nxvldy3h1xjyz3mf8ywsgjkslqk6-0015-path-util.h-add-placeholder-for-DEFAULT_PATH_NORMAL.patch
patching file src/basic/path-util.h
applying patch /nix/store/6cpcq20riypmwr79vwj1rxsg3rjv69hm-0016-pkg-config-derive-prefix-from-prefix.patch
patching file src/core/systemd.pc.in
applying patch /nix/store/svhjykyn1vr61g611gb4g51fx1xyp3i2-0017-inherit-systemd-environment-when-calling-generators.patch
patching file src/core/manager.c
applying patch /nix/store/2kyl5mm7m2d24rgdi5vfp611ycv1h1w7-0018-core-don-t-taint-on-unmerged-usr.patch
patching file src/core/manager.c
applying patch /nix/store/mfnlm8xvf12c11fnpn6gkk5ikqik3fcw-systemd.patch
patching file src/libsystemd/sd-device/device-monitor.c
Hunk #1 FAILED at 445.
1 out of 1 hunk FAILED -- saving rejects to file src/libsystemd/sd-device/device-monitor.c.rej
~`

**Comment by flokli** [comment]
The build log mentions you're still trying to apply the patch that has been removed by this PR. Are you sure your nixpkgs checkout is past that merged PR?

**Comment by harryprayiv** [comment]
> The build log mentions you're still trying to apply the patch that has been removed by this PR. Are you sure your nixpkgs checkout is past that merged PR?

You're absolutely correct.  Thanks for the lesson.

**Pull request merged**
