### PR TITLE
doc: stdenv.lib -> lib

### PR DESCRIPTION
**Pull request by Profpatsch**
Part of: https://github.com/NixOS/nixpkgs/issues/108938

Changing the documentation to not refer to stdenv.lib is the first
step to make people use it directly.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
No conflicts, but it looks like there is at least one overlap already taken care of by #108970 (namely, the change in `emscripten.section.md`). Would you mind rebasing off of master?

**Comment by Profpatsch** [comment]
> No conflicts, but it looks like there is at least one overlap already taken care of by #108970 (namely, the change in `emscripten.section.md`). Would you mind rebasing off of master?

I rebased on maste, but there were no merge conflicts.

**Review by cole-h — APPROVED** [review]
Diff LGTM.

**Review by siraben — APPROVED** [review]
LGTM

**Pull request merged**
