### PR TITLE
vim: add lspsaga-nvim, zephyr-nvim, oceanic-material

### PR DESCRIPTION
**Pull request by onsails**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110747` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
25 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>vimPlugins.ale</li>
<li>vimPlugins.caw-vim</li>
<li>vimPlugins.chadtree</li>
<li>vimPlugins.coc-explorer</li>
<li>vimPlugins.coc-nvim</li>
<li>vimPlugins.denite-git</li>
<li>vimPlugins.deoplete-fish</li>
<li>vimPlugins.deoplete-khard</li>
<li>vimPlugins.deoplete-nvim</li>
<li>vimPlugins.lspsaga-nvim</li>
<li>vimPlugins.nvim-lspconfig</li>
<li>vimPlugins.oceanic-material</li>
<li>vimPlugins.oceanic-next</li>
<li>vimPlugins.plenary-nvim</li>
<li>vimPlugins.sql-nvim</li>
<li>vimPlugins.tagbar</li>
<li>vimPlugins.telescope-nvim</li>
<li>vimPlugins.vim-dadbod</li>
<li>vimPlugins.vim-floaterm</li>
<li>vimPlugins.vim-lsc</li>
<li>vimPlugins.vim-repeat</li>
<li>vimPlugins.vim-vinegar</li>
<li>vimPlugins.vimtex</li>
<li>vimPlugins.zephyr-nvim</li>
</ul>
</details>

**Comment by alyssais** [comment]
Hi @onsails, just say these commits in git log and thought you’d like to know that your name and email address are being recorded as `"Andrey Kuznetsov"` and `"fear@[...].in"` (including the quotes).  You might want to have a look at your git config file and remove the extraneous quotes. :)

**Comment by onsails** [comment]
> Hi @onsails, just say these commits in git log and thought you’d like to know that your name and email address are being recorded as `"Andrey Kuznetsov"` and `"fear@[...].in"` (including the quotes). You might want to have a look at your git config file and remove the extraneous quotes. :)

hmmm, I'l fix that, thank you!

**Comment by onsails** [comment]
actually that's the issue with `update.py`-generated configs only...

**Pull request merged**
