### PR TITLE
python3.pkgs.ruamel-base: add pythonNamespaces to remove nspkg.pth file

### PR DESCRIPTION
**Pull request by KiruyaMomochi**
## Description of changes

The Python package ruamel-* [uses legacy namespace](https://sourceforge.net/p/ruamel-base/code/ci/default/tree/setup.py#l328) which produces `ruamel.*-1.0.0-py3.10-nspkg.pth` file. This causes wrapped python applications importting `ruamel.yaml` throw a `ModuleNotFoundError` when `$PYTHONPATH` is also set to contain ruamel packages. Although I don't understand the cause, this maybe related to 
https://github.com/pypa/setuptools/discussions/3991.

For example, in a simple `devShell` with only [ansible-lint](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/admin/ansible/lint.nix) package, running `ansible-lint` command gives `ModuleNotFoundError: No module named 'ruamel.yaml'`. You can try it by running `nix develop github:KiruyaMomochi/nix-ruamel-lab` and then run `ansible-lint`.

This issue does not occurs with ruamel-yaml 0.17.21 ([update commit](https://github.com/NixOS/nixpkgs/commit/5330b05d9952aad7606d5c0658d65faf1955c659)), because both the ruamel-base and ruamel-yaml contains .pth file. The former .pth file is overridden by the latter.

This PR fixes the problem by adding `pythonNamespaces` to all ruamel-* packages. This triggers `pythonNamespacesHook`, so that [all the .pth files are removed](https://github.com/NixOS/nixpkgs/blob/05ba191efbec39d62027ba883cf220d33197de39/pkgs/development/interpreters/python/hooks/python-namespaces-hook.sh#L35) in these packages.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by tjni — COMMENTED** [review]
Thank you so much for doing this! I had no idea that the `pythonNamespaces` option does exactly what is needed here. Tangentially, it will make updating Sphinx so much easier.

Only `ruamel-base` needs this, which you can verify by looking inside the `sitePackages` directory of the built derivation. `ruamel-yaml` was updated to use implicit namespaces, and `ruamel-yaml-clib` doesn't seem to have a namespace inside of its output.

**Comment by KiruyaMomochi** [comment]
Thanks. I have removed `pythonNamespaces` in `ruamel-{yaml,yaml-clib}` packages.

This hook seems a little hard to discover, and I found it only by searching `nspkg.pth` in the full nixpkgs repository. Maybe we should mention it in nixpkgs or wiki? I can create another PR for it.

**Comment by tjni** [comment]
1. Would it be possible given the number of rebuilds to [rebase this against staging](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging)? It's the policy to help manage risk and alleviate the pressure on the build infrastructure (and it does mean it will take a week or two for the change to make it back into unstable).

2. Adding a section about it to the documentation would be great! I can see perhaps underneath the "Setup hooks" section in the Python language section for now.

I verified that this fixes the build of `pre-commit-hook-ensure-sops`, which was the only one I knew currently that was affected by this issue on Hydra.

**Review by tjni — APPROVED** [review]
Thank you!

**Comment by amjoseph-nixpkgs** [comment]
@KiruyaMomochi, thanks for submitting this PR!

In the future, when changing the base branch, I recommend first marking the PR as **draft**.  Then change the branch and force-push, then unmark it as draft.

Github's UI for changing the base branch is really terrible, and often causes a mass-review-request from everybody in the codeowners file during the branch change.  But it *won't* do this for a PR which is marked as draft at the time the base-change or force-push happens.

**Pull request merged**
