### PR TITLE
netbsd: 8.0 -> 9.1

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

<del>Heavily WIP.</del> Split out from #82131 as I'll make that one just about FreeBSD.

###### Things done

- [x] Update all versions and hashes
- [x] Everything that cross-compiled for NetBSD before the update still does
- [x] Static binaries run on NetBSD
- [x] Everything used on Darwin still works.

### CODE REVIEW

**Comment by niacat** [comment]
I'd recommend bringing this up to 9.1. It's fully compatible with 9.0 with some extra bug fixes and enhancements. We'll be releasing 9.2 in a month or so and that's going to come with another round of important bug fixes.

**Comment by Ericson2314** [comment]
@niacat Thanks for the tip. This is a plenty old commit I split off from an old WIP PR, so I am happy to go straight for 9.1 (or maybe 9.2 if I don't get to this sooner).

**Comment by alyssais** [comment]
Edited the PR body to include a checklist of things we'll need to do.

**Comment by alyssais** [comment]
Only thing failing to cross-compile to NetBSD now is the kernel:

```
/nix/store/qi2x2mmlhvhnhgfq8fp7fw8z2a58x1kc-x86_64-unknown-netbsd-binutils-2.35.1/bin/x86_64-unknown-netbsd-ld: bootia32.efi.so.tmp: error: PHDR segment not covered by LOAD segment
```

**Comment by niacat** [comment]
That's not the kernel, that's an EFI bootloader binary. It might be possible to disable -- I don't know of anyone booting NetBSD from _32-bit_ EFI on x86.

**Comment by alyssais** [comment]
I don't [see](http://cvsweb.netbsd.org/bsdweb.cgi/src/sys/arch/i386/stand/efiboot/Makefile?rev=1.5&content-type=text/x-cvsweb-markup&only_with_tag=netbsd-9-1-RELEASE) a way to disable it, but maybe we could patch it out?  I had a quick look for a way to not build a bootloader at all, but couldn't even see anything for that.

**Comment by alyssais** [comment]
@sternenseemann maybe you could help us with testing the bits of NetBSD that are used on Darwin?

**Comment by sternenseemann** [comment]
> @sternenseemann maybe you could help us with testing the bits of NetBSD that are used on Darwin?

Sure what is best to test? I can test stuff on darwin, but I am not overly familiar with darwin bootstrapping etc.

**Comment by alyssais** [comment]
@OfBorg build samba4 swtpm bash-my-aws microscheme

**Comment by alyssais** [comment]
@sternenseemann also if you could try building those packages I asked OfBorg to build, since it looks like Darwin builds on OfBorg still aren't fixed.  (Those are packages that use unixtools or other NetBSD components on Darwin.)

**Comment by sternenseemann** [comment]
Sure, I'll push them in the queue! Building the darwin bootstrap is going to be a little while longer though…

**Comment by sternenseemann** [comment]
Everything in unixtools builds:

```
$ nix-build -A netbsd.column -A netbsd.getconf -A netbsd.getent -A netbsd.locale
/nix/store/ihdyybd3hjsra8bx5xfvkb0l6y47qans-column-netbsd-9.1
/nix/store/8vp89svqlgjfp90s20jqs4y8byb43cd3-getconf-netbsd-9.1
/nix/store/d12wfd7p3qj2wzycdm0p6vbzr0c84g9c-getent-netbsd-9.1
/nix/store/1rb4nahid5lp167z1s026v4dsjsxcyd7-locale-netbsd-9.1
```

* `samba4` is marked as broken (on darwin at least).
* A dependency of `swtpm` is not supported on darwin

Started the remaining two builds just now, I'll just edit this message when they are finished.

**Comment by sternenseemann** [comment]
Actually everything except `libterminfo`, `libcurses`, `man`, `uudecode` and `libedit` builds on darwin.

**Comment by alyssais** [comment]
> Actually everything except `libterminfo`, `libcurses`, `man`, `uudecode` and `libedit` builds on darwin.

Did libterminfo build before this change?  Everything else is expected,
I think.  (Well, uudecode is new, but I never tested it on Darwin.)

**Comment by sternenseemann** [comment]
> Did libterminfo build before this change? Everything else is expected, I think. (Well, uudecode is new, but I never tested it on Darwin.)

Nope, `uudecode` also didn't build.

**Comment by alyssais** [comment]
Hmm, the x64 EFI bootloader fails to build with the same error as the 32-bit one. :(
They did work on 8.0, so I'm not really sure what to do here.  How much do we want these bootloaders, I suppose?

**Comment by alyssais** [comment]
Interesting! The NetBSD change that breaks this for us, claims to be a fix for it! http://cvsweb.netbsd.org/bsdweb.cgi/src/sys/arch/i386/stand/efiboot/bootx64/ldscript.diff?r1=1.1&r2=1.2&only_with_tag=MAIN&f=h

**Comment by alyssais** [comment]
@Ericson2314 I think this is ready now, what do you think?

I think we probably will want to squash merge this one, so we don't end up with commits with broken packages and make bisects annoying.

**Comment by Ericson2314** [comment]
Great! Thanks for taking this over from me.

**Pull request merged**
