### PR TITLE
cargo-typify: 0.0.14 -> 0.1.0

### PR DESCRIPTION
**Pull request by david-r-cox**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by david-r-cox** [comment]
Result of `nixpkgs-review pr 333558` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cargo-typify</li>
  </ul>
</details>

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 333558` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cargo-typify</li>
  </ul>
</details>

**Comment by lucasew** [comment]
IDK if that's expected

```
Error:                                                                    
0: Failed to convert JSON Schema to Rust code                          
1: Failed to format Rust code                                          
2: rustfmt is not installed                                                                                                                Location:                                                                 
cargo-typify/src/lib.rs:179
```

**Comment by pbsds** [comment]
fixes https://hydra.nixos.org/build/259477117

> IDK if that's expected

Looks like you don't have rustfmt in PATH. You could wrap cargo-typify to make it more hermetic, or not and save the rebuilds. Your call mr maintainer :)

**Review by pbsds — APPROVED** [review]

**Comment by david-r-cox** [comment]
Good catch @lucasew. I wrapped it like @pbsds suggested and it appears to be fixed.

As a quick test, here's a Dockerfile that doesn't include rustfmt and successfully runs cargo-typify:
```
FROM nixos/nix:2.24.2
RUN mkdir -p /root/.config/nix && \
    echo "experimental-features = nix-command flakes" > /root/.config/nix/nix.conf
RUN curl -O https://raw.githubusercontent.com/oxidecomputer/typify/01f3e269a01b5eda87663bd5b162304bb306ad5b/example.json
RUN nix run github:integrated-reasoning/nixpkgs/cargo-typify#cargo-typify typify ./example.json  && \
    cat example.rs
```

**Comment by david-r-cox** [comment]
Result of `nixpkgs-review pr 333558` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cargo-typify</li>
  </ul>
</details>

**Pull request merged**
