### PR TITLE
HylaFAX: fix ModemGroup, also minor metadata updates

### PR DESCRIPTION
**Pull request by Yarny0**
###### Motivation for this change

HylaFAX+ handles the ModemGroup parameter differently from the way the relevant manpage claims it is handled. This can lead to stuck jobs.
I'm using this opportunity to update/improve further minor aspects of the HylaFAX package and module.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))  *(no tests)*
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"` *(no need)*
- [ ] Tested execution of all binary files (usually in `./result/bin/`) *(no need)*
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after) *(no change)*
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

At least the ModemGroup commit should be applied to release-19.03 as well. The other might be backported also as they change metadata only. Should I open a separate pull request for 19.03 ?

### CODE REVIEW

**Comment by Infinisil** [comment]
What's the motivation behind switching from sha256 -> sha512?

**Comment by Yarny0** [comment]
> What's the motivation behind switching from sha256 -> sha512?

That's just a feeling in my gut that sha512 is certainly no less reliable, possibly more one day. There is not need for this change beyond.

We can also drop this commit .. should we? Should I replace the pull request?

**Comment by Infinisil** [comment]
Well currently the auto-update bot (@r-ryantm) at least only works for sha256, and all nix prefetching scripts output sha256 by default, so I think it might be better to keep using sha256. You don't need to replace the PR, you can just remove that commit with a `git rebase -i HEAD~4` or so

**Comment by Yarny0** [comment]
> Well currently the auto-update bot (@r-ryantm) at least only works for sha256
Aha, I didn't know that, that's a good reason to keep it sha256. Thanks for this information. I dropped the respective commit.

**Pull request merged**
