### PR TITLE
skypeforlinux: 8.51.0.92 -> 8.56.0.103

### LINKED ISSUE #81868: skype is outdated
**Current download address for the skype is outdated and has been removed**
In channel nixos-19.09, The package nixos.skype corresponds to version skypeforlinux-8.51.0.72, the download link of which has been outdated.

The oldest available version is `skypeforlinux_8.55.0.135_amd64.deb`, according to 
[https://repo.skype.com/deb/pool/main/s/skypeforlinux/](https://repo.skype.com/deb/pool/main/s/skypeforlinux/)

**To Reproduce**
1. nix-env -iA nixos.skype

**Expected behavior**
Successful installation

**Screenshots**
```bash
$> nix-env -iA nixos.skype                                                                                                  ✔  10037  14:31:35
installing 'skypeforlinux-8.51.0.72'
these derivations will be built:
  /nix/store/0q324cb687ij0czrw1xigf0mw4n6f8c0-skypeforlinux_8.51.0.72_amd64.deb.drv
  /nix/store/6v3ihz89yd8qzmbbvcn290pr81gr8k2n-skypeforlinux-8.51.0.72.drv
building '/nix/store/0q324cb687ij0czrw1xigf0mw4n6f8c0-skypeforlinux_8.51.0.72_amd64.deb.drv'...

trying https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.51.0.72_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download skypeforlinux_8.51.0.72_amd64.deb from any mirror
builder for '/nix/store/0q324cb687ij0czrw1xigf0mw4n6f8c0-skypeforlinux_8.51.0.72_amd64.deb.drv' failed with exit code 1
cannot build derivation '/nix/store/6v3ihz89yd8qzmbbvcn290pr81gr8k2n-skypeforlinux-8.51.0.72.drv': 1 dependencies couldn't be built
error: build of '/nix/store/6v3ihz89yd8qzmbbvcn290pr81gr8k2n-skypeforlinux-8.51.0.72.drv' failed
```

**Additional context**
No

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 19.09.2201.7d31bbceaa1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2201.7d31bbceaa1"`
 - channels(astrojhgu): `"nixos-19.09beta317.88f32cca5a4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by emmanuelrosa**
###### Motivation for this change

The motivation for this change is to update `skypeforlinux` to a recent version on 19.09 so that the upstream package is available. I simply cherry-picked what we already have on master.

cherry-picked 4665c94d0c3337c410ce588b10412056baa2b6b6

Closes #81868

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
This should target `release-19.09`, not `nixos-19.09`.

**Comment by emmanuelrosa** [comment]
Oh, damn.

I rebased the commit, but I don't think that's going to do the trick. I may have to abort and do a new PR.

**Comment by FRidh** [comment]
Checkout release-19.09, cherry-pick the commit, and then force push to this branch.

**Comment by FRidh** [comment]
Actually, in this case it was sufficient to just change target branch in the top :)

**Pull request merged**
