### PR TITLE
openssh: 6.9p1 -> 7.1p2

### PR DESCRIPTION
**Pull request by k0ral**
Successfully built locally.
I notably have removed 2 obsolete patches that are already included in version `7.1p2`.

### CODE REVIEW

**Comment by peti** [comment]
:+1:

**Comment by wkennington** [comment]
Ill just leave this here.
https://github.com/NixOS/nixpkgs/commit/401782cb678d2e28c0f7f2d40c6421624f410148

**Comment by fpletz** [comment]
:+1: Also had that on my TODO list.

**Comment by vcunat** [comment]
Good to know the reference. Currently we're not immediately before a release, so it's a suitable time to break compatibility (slightly).

**Comment by domenkozar** [comment]
@edolstra do you approve? Bumping openssh now is a good idea.

**Comment by edolstra** [comment]
Well, we will first have to figure out how to deal with the host key incompatibility issue (401782cb678d2e28c0f7f2d40c6421624f410148).

**Comment by vcunat** [comment]
If I understand it correctly, by default we've been using DSA keys (i.e. ssh-dss) but those recently started to be considered not secure enough. Therefore it seems to me we do want to force key regeneration to improve security.

**Comment by vcunat** [comment]
More precisely, we *eventually* want to force safer keys... and now might be a good time, or after branching-off another release.

**Comment by fpletz** [comment]
Actually, we don't need to regenerate host keys because by default there are RSA keys which are still reasonably secure. The problem is that the SSH client previously preferred DSS keys which were then stored in the user's known_hosts. The only solution would be deleting this file oder remove legacy host keys one by one with `ssh-keygen -R`. AFAIK this can't be automated trivially.

**Comment by vcunat** [comment]
Ah, I was imprecise... but from high-level point of view it seems the question remains the same: we only choose *when* to break not *if* to break (backwards compatibility, kind of).

**Comment by edolstra** [comment]
Looks like Fedora has a patch to fix the `HostKeyAlgorithms` issue: https://pkgs.fedoraproject.org/cgit/rpms/openssh.git/commit/openssh-7.1p1-hostkeyalgorithms.patch?id=c98f5597250d6f9a8e8d96960beb6306d150ef0f

**Comment by edolstra** [comment]
I'll test this with the Fedora patch.

**Comment by edolstra** [comment]
Applied with the Fedora patch, thanks!

**Comment by domenkozar** [comment]
I'm getting host mismatch errors:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:BmzQVOOWu1Ppfsg6J//75Yq8E7fMk1JNjSWIDN8z0Ys.
Please contact your system administrator.
Add correct host key in /home/ielectric/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/ielectric/.ssh/known_hosts:116
ED25519 host key for eiger.snabb.co has changed and you have requested strict checking.
Host key verification failed.
```

**Pull request closed without merging**
