### PR TITLE
bamf: 0.5.4 -> 0.5.5

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

https://git.launchpad.net/~unity-team/bamf/tree/debian/changelog

  * debian/control:
    - update default vcs to git
    - Drop B-D on dbus-x11, rather versioned build-depend on dbus (>= 1.8)
    - Bump Standards-Version: to 4.1.5.
  * debian/gbp.conf: added default settings
  * [bamf-tab: Fix spelling](https://git.launchpad.net/~unity-team/bamf/commit/?id=ce74bf28e145c954e216512e4298dd3064b82895)
  * [bamf-view: avoid overriding the `timeout` variables after setting them](https://git.launchpad.net/~unity-team/bamf/commit/?id=312c9a29db2d4b33b96d4da71393f4a95f5e78a0)
  * [Remove remnants of long-removed mono stuff.](https://git.launchpad.net/~unity-team/bamf/commit/?id=c58537994a99afe9b545e13aa1ed93dcb8bdc9dd)
  * [Run gtester2xunit.py with Python3, port libxml2/libxslt to lxml module..](https://git.launchpad.net/~unity-team/bamf/commit/?id=e397ac429ca3ba50645ee9b05e4dcf7a8d79d99e)
  * debian/control: Update B-D python-libxslt1 -> python3-lxml.
  * [_add-compile-warning-flags](https://git.launchpad.net/~unity-team/bamf/commit/?id=dc18c114c709e1342471c9748f54ad172b88fb89)

Besides things mentioned in changelog, the update also:

- [configure.ac: bump glib requirement to >= 2.38](https://git.launchpad.net/~unity-team/bamf/commit/?id=b3d127965f9b9522b4e3674a40bcb4bd76691b41) (0.5.5+21.10.20210710)
- [Fixes `g_type_class_add_private()` deprecated](https://git.launchpad.net/~unity-team/bamf/commit/?id=3caeba5e15a72adc79db2f1159de1e74dd3d58c8) (0.5.5+21.10.20210710)

###### Things done

- [x] Tested Pantheon 5.1 and Pantheon 6 with `nixos-rebuild build-vm`.
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 136750` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>bamf</li>
    <li>monitor</li>
    <li>pantheon.elementary-dock</li>
    <li>pantheon.elementary-files</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>plank</li>
  </ul>
</details>

**Comment by davidak** [comment]
Release notes say:

>New upstream release: 0.5.5

so `0.5.5` would be better as version. the suffix is ubuntu specific

maybe you can even use the tar.xz from https://launchpad.net/bamf/0.5/0.5.5?

**Comment by bobby285271** [comment]
0.5.5+21.10.20210710 fixes https://bugs.launchpad.net/bamf/+bug/1862450, this is not critical issue and the fix is not ubuntu specific. I am okay with 0.5.5 though (according to https://github.com/elementary/wingpanel-indicator-power/issues/208, I will not expcet a 0.5.6 release as this is a package previously maintained by Unity desktop team).

**Comment by davidak** [comment]
When the `0.5.5+21.10.20210710` version contains useful patches, we can use it, but let the nix package version be `0.5.5`. It does not need to show that we have additional patches.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 136750` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>bamf</li>
    <li>monitor</li>
    <li>pantheon.elementary-dock</li>
    <li>pantheon.elementary-files</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>plank</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change looks good

Builds

I merge it now so we can see how it works at runtime with elementary 6.

**Pull request merged**
