### PR TITLE
libnvme, nvme-cli: 1.4 -> 1.6, 2.4 -> 2.6

### PR DESCRIPTION
**Pull request by vifino**
## Description of changes

libnvme release: https://github.com/linux-nvme/libnvme/releases/tag/v1.6
libnvme commits: https://github.com/linux-nvme/libnvme/compare/v1.4...v1.6

nvme-cli release: https://github.com/linux-nvme/nvme-cli/releases/tag/v2.6
nvme-cli commits: https://github.com/linux-nvme/nvme-cli/compare/v2.4...v2.6

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vifino** [comment]
@ofborg build pkgsStatic.nvme-cli pkgsMusl.nvme-cli

**Comment by fogti** [comment]
```
FAILED: test/ioctl/libmock-ioctl.so.p/mock.c.o 
gcc -Itest/ioctl/libmock-ioctl.so.p -Itest/ioctl -I../test/ioctl -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -fomit-frame-pointer -D_GNU_SOURCE -include internal/config.h -fPIC -MD -MQ test/ioctl/libmock-ioctl.so.p/mock.c.o -MF test/ioctl/libmock-ioctl.so.p/mock.c.o.d -o test/ioctl/libmock-ioctl.so.p/mock.c.o -c ../test/ioctl/mock.c
../test/ioctl/mock.c:117:5: error: conflicting types for ‘ioctl’; have ‘int(int,  long unsigned int, ...)’
  117 | int ioctl(int fd, unsigned long request, ...)
      |     ^~~~~
In file included from ../test/ioctl/mock.c:9:
/nix/store/qnzi64i0hccghn024klcax1nd31s578f-musl-1.2.3-dev/include/sys/ioctl.h:115:5: note: previous declaration of ‘ioctl’ with type ‘int(int,  int, ...)’
  115 | int ioctl (int, int, ...);
      |     ^~~~~
```

it appears that the mock might need a musl-specific patch...

**Comment by vifino** [comment]
Thanks @Mic92!

**Comment by vcunat** [comment]
We can't evaluate now, as a channel-critical test is broken.  Test:
```
$ nix eval -f nixos/release-combined.nix nixos.tests.boot.uefiUsb.aarch64-linux.outPath
error: Package ‘libhugetlbfs-2.23’ in pkgs/development/libraries/libhugetlbfs/default.nix:44 is marked as broken, refusing to evaluate.
```

**Comment by vcunat** [comment]
OfBorg did build the stuff, so maybe the `broken` mark shouldn't really be there anymore?

**Comment by Mic92** [comment]
Actually libhugetblfs builds just fine on aarch64: https://github.com/NixOS/nixpkgs/pull/264439

**Pull request merged**
