### PR TITLE
Pysolfc

### PR DESCRIPTION
**Pull request by AndersonTorres**
Four commits for a Freecell Solver! They form a dependency tree, so I prefer to commit 4 commits at the same time.

### CODE REVIEW

**Comment by jagajaga** [comment]
Please resolve conflicts against master.

**Comment by AndersonTorres** [comment]
How can I do this?

**Comment by fpletz** [comment]
@AndersonTorres On your local clone you can do something like this:

```sh
$ git checkout pysolfc        # switch to your branch
$ git fetch origin            # fetch current nixpkgs master (if remote is called origin)
$ git rebase origin/master    # rebase against current master
# you will get a list of files with conflicts, fix these & add the files with `git add`
$ git rebase --continue
$ git push -f AndersonTorres  # if the remote of your github clone is called AndersonTorres
```

**Comment by AndersonTorres** [comment]
Many thanks, @fpletz !

**Comment by lethalman** [comment]
Sorry but... I don't see anywhere "Pysolfc" in those commits. Also freecell-solver and Games-Solitaire-Verify are independent. Am I understanding this right?

**Comment by AndersonTorres** [comment]
freecell-solver uses libtap and the Perl packages above. They form a dependency tree, but it isn't so smart to create four pull requests for small, auxiliary libraries.

PysolFC? Well, I am building it here, but it is not finished yet. I need some libraries not present in nixpkgs. But freecell-solver is a independent package by itself.

Maybe a change of name would be good.

**Comment by lethalman** [comment]
Ah yes I missed that those perl packages are used. Travis passed, thanks.

**Comment by AndersonTorres** [comment]
A fast, not so unrelated, question:

When I was building freecell-solver, I did it in a top-down manner: I write an expression for freecell-solver, and running nix-shell I find it needed the other libraries. 
First, it complained about libtap; then I write libtap.
Second, it complained about Games-Solitary-Verify; then I write it;
Third, Games-... complained about MooX::late; then I write it;
Finally, I got freecell-solver running.

I build 4 softwares, then I need 4 commits. There is some easy way to do it? 
My way was very ad hoc: I just "ripped off" the modifications (`mv modified-files /tmp/placeholder`) and added them to nixpkgs tree, once at a time: "add MooX::late, commit; add Games, commit; add libtap, change top-level, commit; add freecell-solver, change top-level, commit".

**Comment by lethalman** [comment]
@AndersonTorres well that's the workflow, you can also add directly to nixpkgs though, and still do 4 commits

**Pull request merged**
