### PR TITLE
autoPatchhelfHook: call addToDepCache recursive

### PR DESCRIPTION
**Pull request by milahu**
## Motivation for this change
make `autoPatchhelfHook` find `*.so` library files
not only in `$out/lib/library.so` but also in `$out/lib/path/to/library.so`

tested by patching the `findDependency` function, see [jesc-configurator/default.nix](https://github.com/milahu/random/blob/master/nixos/bugs/auto-patchelf-cannot-find-so-file/jesc-configurator/default.nix#L48)

related discourse [autoPatchhelfHook could not satisfy dependencies](https://discourse.nixos.org/t/autopatchhelfhook-could-not-satisfy-dependencies/13745)

<details>
<summary>PR merged: Bug in nwjs</summary>

there is also a bug in [nwjs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/nwjs/default.nix), PR in #144271

```
( cd /nix/store/fq45lf16xsdcz7ha7wr4wmwbwkb0imgr-nwjs-0.33.4/ && find . -name '*.so' )
./share/nwjs/lib/libnw.so
./share/nwjs/lib/libnode.so
./share/nwjs/lib/libffmpeg.so
./share/nwjs/swiftshader/libEGL.so
./share/nwjs/swiftshader/libGLESv2.so
```

at least `libnw.so` should be in `./lib/libnw.so` or `./lib/nwjs/libnw.so`

... assuming that we want to use library files only from `$out/lib`
and not from `$out/share` in this case

</details>

### refactor find

we could pass multiple directories to `find` as in

https://github.com/NixOS/nixpkgs/blob/a8a57c90b3ad901bf868c217e58fe71251567594/pkgs/build-support/setup-hooks/auto-patchelf.sh#L299-L302

### recursive rpathElem

make this recursive?

```sh
            for foundso in "$rpathElem/$soname".so*; do
                addToDepCache "$foundso"
            done
```

```sh
            find "$rpathElem" '(' -name "${soname}.so" -or -name "${soname}.so.*" ')' | while read foundso; do
                addToDepCache "$foundso"
            done
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
> ... assuming that we want to use library files only from $out/lib

I think this is the case. at least compilers only look for libs in /lib, not /share
```
$  nix-shell -p zlib nwjs
[nix-shell:/tmp]$ LANG=C gcc -xc /dev/null -lnwjs
/nix/store/5ddb4j8z84p6sjphr0kh6cbq5jd12ncs-binutils-2.35.1/bin/ld: cannot find -lnwjs
collect2: error: ld returned 1 exit status
```

**Comment by milahu** [comment]
> at least compilers only look for libs in /lib

makes sense, packages want to hide "private" libraries
for example `nwjs` has

```
./share/nwjs/lib/libnode.so
./share/nwjs/lib/libffmpeg.so
./share/nwjs/swiftshader/libEGL.so
./share/nwjs/swiftshader/libGLESv2.so
```

these should not be used to satisfy dependencies,
instead, use the original packages: node, ffmpeg, libglvnd, ...

**Comment by aszlig** [comment]
> these should not be used to satisfy dependencies,

@milahu: Yep, this is the reason why I didn't make it recursive in the first place.

I'm also not quite sure whether it makes sense to have an option to switch on recursion. Do you have any data on how often this happens?

Because if it is only a corner-case, I'd rather use `addAutoPatchelfSearchPath` in the affected packages instead.

**Comment by milahu** [comment]
> > these should not be used to satisfy dependencies,
> 
> @milahu: Yep, this is the reason why I didn't make it recursive in the first place.

... but in this case, we have a list of `buildInputs`
and it does not matter if we use, for example
`ffmpeg/lib/libffmpeg.so` or
`vlc/lib/libffmpeg.so`
as long as the ABI is compatible
... because anyway, we have both packages as dependency

also, on conflict, we could give lower priority to the deep so files
so prefer `pkg1/lib/lib.so` over `pkg2/lib/some/where/deep/lib.so`

> Do you have any data on how often this happens?

[more often than you imagine](https://www.youtube.com/watch?v=SiB8GVMNJkE) ; )

[here](https://raw.githubusercontent.com/milahu/random/master/nixos/autoPatchelfHook-recursive-find-libs/8.txt) is a 700 KByte dump, [parsed](https://github.com/milahu/random/blob/master/nixos/autoPatchelfHook-recursive-find-libs/analyze-so-files.sh) from `nix-locate`
all these are "deep" so files, where the package has no *.so files in $out/lib
column 2 shows the depth in $out/lib

one way to list the exported libraries is `pkg-config`
but only few packages have the `*.pc` files

**Comment by domenkozar** [comment]
user was banned https://github.com/NixOS/moderation/blob/main/moderation-log.md

**Pull request closed without merging**
