### PR TITLE
omake: update to 0.10.1

### PR DESCRIPTION
**Pull request by vbgl**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Any reason why you haven't merged it yourself?

**Comment by vbgl** [comment]
I waited a little bit just in case someone had a comment… I am not completely confident about the `teyjus` update.

Let’s merge and see.

**Comment by FlorentBecker** [comment]
isn't teyjus broken now?

**Comment by vbgl** [comment]
Thanks for the report. `teyjus` indeed fails to build. As I don’t understand the error, I’ve reverted two commits such that `teyjus` is kept at the older version and still use `omake-0.9.8.6-rc1`.

**Pull request merged**
