### PR TITLE
update spotify to 1.0.19.106

### PR DESCRIPTION
**Pull request by christopher-l**
I'm pretty new to NixOS, so this is mainly based on trial an error. Seems to work though, while the previous version didn't for me.

(update: add cc)
cc @edolstra @ftrvxmtrx

### CODE REVIEW

**Comment by jgillich** [comment]
Can you please change the commit message to:
> spotify: 0.9.17.1 -> 1.0.19.106

**Comment by christopher-l** [comment]
Is it OK this way?

**Comment by ftrvxmtrx** [comment]
@christopher-l I guess you removed `ffmpeg_0_10` dependency accidentally. It's still needed for local files playback, otherwise it just segfaults, please add it back.

**Comment by christopher-l** [comment]
Didn't think to test this. Thanks for pointing it out.

It seems that gnome.zenity needs to be installed in order to add local sources. Should this dependency be modeled here?

**Comment by globin** [comment]
I'm unable to add any local folders, but playing local files works.

**Comment by christopher-l** [comment]
I added `zenity` with `propagatedUserEnvPkgs`.

For some reason, spotify segfaults on my system at the moment right after starting it, but it does this for the old version as well, so it is probably unrelated to this update.

**Comment by FRidh** [comment]
While I didn't test local playback it functions without any problems for me.

**Comment by globin** [comment]
I'm testing once more

**Comment by globin** [comment]
Updated this to use makeWrapper for zenity and merged.

**Pull request closed without merging**
