### PR TITLE
[21.05] salt: 3003 -> 3003.3

### PR DESCRIPTION
**Pull request by Flakebi**
###### Motivation for this change
3003.3 was published, fixing 2 CVEs: https://docs.saltproject.io/en/latest/topics/releases/3003.3.html

Backport of 4ad4ae68c427ef8458be34051b4e545eb752811c from #136619.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Please cherry-pick every original commit with `-x` instead of doing this abbreviation.

**Comment by Flakebi** [comment]
@mweinelt I cherry-picked it with -x now. The commit message is slightly different than on the original commit, because 21.05 only had 3003 while unstable had 3003.2.

**Comment by mweinelt** [comment]
You need to pick all individual commits that led to that version.

c0b46c6b596dd25f32733ff01156d3d769640ab5
da3e6504941a8162f08a9b1e99914d807deada71
4ad4ae68c427ef8458be34051b4e545eb752811c

**Comment by Flakebi** [comment]
Okay, here we go

**Comment by Flakebi** [comment]
Thanks!

**Pull request merged**
