### PR TITLE
ollama: 0.3.9 -> 0.3.10

### LINKED ISSUE #326038: Update request: Ollama 0.1.48 → 0.2.1
- Package name: Ollama
- Latest released version: 0.2.1

- Current version on the unstable channel: 0.1.48
- Current version on the stable/release channel: 0.1.38

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@abysssol

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by abysssol**
## Description of changes

changelog: https://github.com/ollama/ollama/releases/tag/v0.3.10
diff: https://github.com/ollama/ollama/compare/v0.3.9...v0.3.10

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
Are we good to undraft this?

**Comment by abysssol** [comment]
I'm going to leave it as a draft for a while, maybe 12-24 hours, since ollama has changed what commit the release tag points to in the past (see [this comment](https://github.com/NixOS/nixpkgs/pull/331585#issuecomment-2264916039), [my reply](https://github.com/NixOS/nixpkgs/pull/331585#issuecomment-2265472669), [the incorrect pr](https://github.com/NixOS/nixpkgs/pull/331058), and [the fix](https://github.com/NixOS/nixpkgs/pull/331780)).

I don't want a repeat of that, so I'm going to wait until later today or tomorrow, then check whether the source hash has changed before undrafting. This is me [being more careful in the future](https://github.com/NixOS/nixpkgs/pull/331585#issuecomment-2265472669). 🙂

**Comment by adamcstephens** [comment]
After some more testing last night it appears that ollama 3.9 and 3.10 don't work for me on cudaPackages 12.4 (the default). I'm not sure exactly where the problem lies, but ollama 3.5 works fine with both 12.3 and 12.4. 

```
Sep 07 15:59:47 sink1 ollama[1314]: time=2024-09-07T15:59:47.696-04:00 level=INFO source=server.go:625 msg="waiting for server to become available" status="llm server error"
Sep 07 15:59:47 sink1 ollama[1314]: /tmp/ollama1289771407/runners/cuda_v12/ollama_llama_server: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory
Sep 07 15:59:47 sink1 ollama[1314]: time=2024-09-07T15:59:47.947-04:00 level=ERROR source=sched.go:456 msg="error loading llama server" error="llama runner process has terminated: exit status 127"
```

I'm curious if anyone else has seen this with the cuda variant.

**Comment by abysssol** [comment]
@adamcstephens Do you think it would be best to keep `ollama-cuda` at 0.3.5 and `ollama` at 0.3.10? I think it was [0.3.7](https://github.com/ollama/ollama/releases/tag/v0.3.7) that [made some changes to how it handles gpu related libraries](https://github.com/ollama/ollama/compare/v0.3.6..v0.3.7#diff-86f3a15d5d1f64061f2d250a9af83e3d23a4bbac7de464636c61fb18051304b6), which may have broken something in the nix package. It may be fixable, though; I can't tell yet.

**Comment by adamcstephens** [comment]
I'm still trying to (slowly) dig into the problem to figure out what's going on. I'd say we can move ahead with this PR as it doesn't make anything worse from my perspective. If we need to pin cudaPackages or downgrade ollama we can do so separately.

**Comment by abysssol** [comment]
I wonder if #333123 might be a related issue?

**Comment by adamcstephens** [comment]
I think I've narrowed down the issue to this cuda lib derivation missing from the final configuration.

https://github.com/NixOS/nixpkgs/blob/345c263f2f53a3710abe117f28a5cb86d0ba4059/pkgs/by-name/ol/ollama/package.nix#L122

I don't build ollama-cuda on the host I run ollama on, so it must be missing from the final ollama derivation. It's also an incus (lxc) container with the GPU passed in, but I suspect that the build location is the problem here. If this is the case, then I would expect others may experience this if/when they GC.

**Comment by adamcstephens** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/342127

**Pull request merged**
