### PR TITLE
mesa: 12.0.1 -> 13.0.0

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Things done

- [x] Tested using sandboxing
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using (mass rebuild)
- [x] Tested execution of all binary files (none)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

`dlopen-absolute-paths.diff ` is no longer necessary as mesa does not depend on libudev anymore.

### CODE REVIEW

**Comment by NeQuissimus** [comment]
Is this going to trigger a mass-rebuild?

**Comment by rnhmjoj** [comment]
Yes, it is. I had to come up with some trick just to rebuild my system with it (because of limited disk space).

**Comment by NeQuissimus** [comment]
OK, let's see what the staging Hydra has to say...

**Comment by vcunat** [comment]
`*.*.0` releases tend to be marked "is a new development release", so I was always waiting for `*.*.1`.

**Comment by NeQuissimus** [comment]
Would you be more comfortable if I reverted this then? Or leave it in staging and wait for a .1 before going into master?

**Comment by vcunat** [comment]
I did that now. Let's re-revert when 13.0.1 comes. That could be expected roughly in a week or two. (We'll want to merge staging soon because of security mass rebuild due to `tar`.)

**Pull request merged**
