### PR TITLE
flakes: add a module list and the script to create it

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
I wanted to override modules in flakes but
```nix
disabledModules = [ "services/desktops/pipewire/pipewire.nix" ];                          
imports = [ "${inputs.mynixpkgs}/nixos/modules/services/desktops/pipewire/pipewire.nix" ];
``` 
didn't work
```
error: infinite recursion encountered

       at /nix/store/y38w1iqhwlsa5aphd2kc1r1qii9al3aj-source/lib/modules.nix:305:28:

          304|         builtins.addErrorContext (context name)
          305|           (args.${name} or config._module.args.${name})
             |                            ^
          306|       ) (lib.functionArgs f);
```

Now it does
`nix build .#nixosConfigurations.vm.config.system.build.vm`
```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  inputs.mynixpkgs.url = "github:Artturin/nixpkgs/moduleflakes";
  #inputs.mynixpkgs.url = "path:../nixgits/my-nixpkgs";

  outputs = { self, nixpkgs, mynixpkgs }: {

    nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        mynixpkgs.nixosModules.pipewire-pipewire
        ({ pkgs, inputs, ... }: {
          disabledModules = [ "services/desktops/pipewire/pipewire.nix" ];
          
          services.pipewire.enable = true;
          
          users.users.user = {
            password = "user";
            isNormalUser = true;
          };
        })
      ];
    };
  };
}
```

`imports = [ inputs.mynixpkgs.nixosModules.pipewire-pipewire ];` Doesn't work for some reason, same issue as above. EDIT: inputs. Isn't necessary

###### Things done
removed the commented gitit entry which as been commented since 122d5e497e6d from module-list

the generated flake-module-list has the last 2 path sections to prevent collisions

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Imports wont be needed once https://github.com/NixOS/nix/issues/3421
is implemented

**Comment by colemickens** [comment]
I'm pretty sure the infinite recusion has much more to do with the way `inputs` is (maybe not) being propagated through to the nixos configuration.

This is the same behavior I'd expect to see if someone added `inputs` to their module function args without actually configuring things properly so that `inputs` is actually passed in (for example, I don't see this in the config you posted...)

**Comment by Artturin** [comment]
> I'm pretty sure the infinite recusion has much more to do with the way `inputs` is (maybe not) being propagated through to the nixos configuration.
> 
> This is the same behavior I'd expect to see if someone added `inputs` to their module function args without actually configuring things properly so that `inputs` is actually passed in (for example, I don't see this in the config you posted...)

Thanks, this works
```
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  inputs.mynixpkgs.url = "github:Artturin/nixpkgs/moduleflakes";
  #inputs.mynixpkgs.url = "path:../nixgits/my-nixpkgs";

  outputs = { self, nixpkgs, mynixpkgs }@inputs: {

    nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      specialArgs = { inherit inputs; };
      modules = [
        #mynixpkgs.nixosModules.pipewire-pipewire
        ({ pkgs, inputs, ... }: {
          disabledModules = [ "services/desktops/pipewire/pipewire.nix" ];

          imports = [ inputs.mynixpkgs.nixosModules.pipewire-pipewire ];

          services.pipewire.enable = true;

          users.users.user = {
            password = "user";
            isNormalUser = true;
          };
        })
      ];
    };
  };
}
```
and `imports = [ "${inputs.mynixpkgs}/nixos/modules/services/desktops/pipewire/pipewire.nix" ];` works too.

**Comment by roberth** [comment]
I see how this pr slightly improves ease of use, but I don't think it outweighs the costs.

- This list can go out of date.
- The modules go from having 1.5 name to 2.5 names: file name, nixosModules name and often an `enable` option path. If the goal is to rename modules entirely, to remove the needless hierarchy, I'd support that.
- Exposing these in the flake suggests that they're a dependable interface, but they're not.

The problem was with the undeclared `inputs` and its solution does not require this pr.

Did you try using the lexical scope? `specialArgs` should be unnecessary when you can use the lexical scope instead. Previously this often wasn't an option because most tools expected configs in separate files, so we have to do some unlearning :).

```diff
-  outputs = { self, nixpkgs, mynixpkgs }: {
+  outputs = inputs@{ self, nixpkgs, mynixpkgs }: {

     nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
       system = "x86_64-linux";
       modules = [
         mynixpkgs.nixosModules.pipewire-pipewire
-        ({ pkgs, inputs, ... }: {
+        ({ pkgs, ... }: {
           disabledModules = [ "services/desktops/pipewire/pipewire.nix" ];

```

**Comment by Artturin** [comment]
> I see how this pr slightly improves ease of use, but I don't think it outweighs the costs.
> 
>     * This list can go out of date.

There'd be instructions to run the script everytime a module is added to the list


>     * The modules go from having 1.5 name to 2.5 names: file name, nixosModules name and often an `enable` option path. If the goal is to rename modules entirely, to remove the needless hierarchy, I'd support that.
> 
>     * Exposing these in the flake suggests that they're a dependable interface, but they're not.
> 


> 
> The problem was with the undeclared `inputs` and its solution does not require this pr.
> 
> Did you try using the lexical scope? `specialArgs` should be unnecessary when you can use the lexical scope instead. Previously this often wasn't an option because most tools expected configs in separate files, so we have to do some unlearning :).
> 
> ```diff
> -  outputs = { self, nixpkgs, mynixpkgs }: {
> +  outputs = inputs@{ self, nixpkgs, mynixpkgs }: {
> 
>      nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
>        system = "x86_64-linux";
>        modules = [
>          mynixpkgs.nixosModules.pipewire-pipewire
> -        ({ pkgs, inputs, ... }: {
> +        ({ pkgs, ... }: {
>            disabledModules = [ "services/desktops/pipewire/pipewire.nix" ];
> ```

This does work, i assume `specialArgs = { inherit inputs; };` is still needed when importing a another config file with `imports...inputs`.

```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  inputs.mynixpkgs.url = "github:Artturin/nixpkgs/pipewirejackldpath";
  #inputs.mynixpkgs.url = "path:../nixgits/my-nixpkgs";

  outputs = inputs@{ self, nixpkgs, mynixpkgs }: {

    nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        ({ pkgs, ... }: {
          disabledModules = [ "services/desktops/pipewire/pipewire.nix" ];

          imports = [ "${inputs.mynixpkgs}/nixos/modules/services/desktops/pipewire/pipewire.nix" ];

          services.pipewire.enable = true;

          users.users.user = {
            password = "user";
            isNormalUser = true;
          };
        })
      ];
    };
  };
}
```

Could someone with flakes knowledge add it to the wiki page?
https://nixos.wiki/wiki/Flakes

I'll add the method to override modules to here
https://nixos.wiki/wiki/Nixpkgs/Reviewing_changes

**Pull request closed without merging**
