### PR TITLE
openrct2: 0.1.2 -> 0.2.0

### PR DESCRIPTION
**Pull request by oxzi**
###### Motivation for this change
Updated to current release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@GrahamcOfBorg build openrct2

**Comment by xeji** [comment]
Please fix aarch64 failure, current version build: https://hydra.nixos.org/job/nixpkgs/trunk/openrct2.aarch64-linux

**Comment by geistesk** [comment]
I'd love to fix the aarch64-build, but I do not know what causes this problems. The error log hints to SDL2, where this define seems to be missing on the aarch64-branch.

Furthermore, I am not sure if this games even runs on other platforms than x86_64, which is btw the only target on the [official website](https://openrct2.org/downloads/master/latest).

**Comment by xeji** [comment]
>  Furthermore, I am not sure if this games even runs on other platforms than x86_64, which is btw the only target on the official  website.

Good point. So let's merge it anyway, maybe someone else wants to fix it for aarch64 later.

**Pull request merged**
