### PR TITLE
python pykafka: init at 2.0.3

### PR DESCRIPTION
**Pull request by aloiscochard**
I had to disable the tests as 5 failed (30 pass) with the following error:

```
==================================== ERRORS ====================================
___________ ERROR collecting tests/pykafka/test_balancedconsumer.py ____________
tests/pykafka/test_balancedconsumer.py:11: in <module>
    from pykafka.test.utils import get_cluster, stop_cluster
pykafka/test/utils.py:3: in <module>
    from pykafka.test.kafka_instance import KafkaInstance, KafkaConnection
pykafka/test/kafka_instance.py:30: in <module>
    from testinstances import utils
E   ImportError: No module named testinstances

```

I did a manual testing it by starting a client and receiving messages in a python interpreter.

### CODE REVIEW

**Comment by domenkozar** [comment]
@aloiscochard you also need to package https://pypi.python.org/pypi/testinstances for tests

**Comment by domenkozar** [comment]
ping @aloiscochard :)

**Comment by domenkozar** [comment]
@aloiscochard friendly ping :)

**Comment by FRidh** [comment]
Please reopen if you still want to get this in.

**Pull request closed without merging**
