### PR TITLE
treewide: make many outputs that contain zip files reproducible

### PR DESCRIPTION
**Pull request by amarshall**
###### Description of changes

I simply grepped for ` zip ` and then only bothered with pkgs that were using `zip` directly in the drv build scripts. Each pkg was red-greened to verify it was already non-deterministic, ones that were deterministic were skipped. If there were other non-trivial reproducibility problems beyond the zip file (I think only `manualEpub` had other issues), I skipped it. Likely there are more pkgs that could benefit from this treatment that generate zip files internally in their build processes, but this was low-hanging fruit.

For `fetchFirefoxAddon`, I used an existing example addon drv I had to validate.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Minion3665 — APPROVED** [review]

**Review by tjni — APPROVED** [review]
For posterity, I derived two learnings from this PR:

1. `zip` should be followed by `strip-nondeterminism`.
2. `tar` should be passed `--sort=name` and `--mtime="@$SOURCE_DATE_EPOCH"` options.

Are there cases when this isn't needed and, if so, how could it be determined mechanistically.  Food for thought: could it be possible to wrap `zip` and `tar` in variants that do this for us atomically when invoked?

Thank you for persevering.

**Review by Janik-Haag — APPROVED** [review]
LGTM

**Review by GovanifY — APPROVED** [review]

**Review by emmanuelrosa — APPROVED** [review]
This works fine, but what I don't like is that it dramatically increases the build time. `strip-nondeterminism` took nearly 10 minutes to process the jar file. I'd have to disable that step during package development.

**Comment by Janik-Haag** [comment]
I will merge this since a lot of package maintainers approved it.

**Comment by linsui** [comment]
Maybe we can use something like https://github.com/timo-reymann/deterministic-zip. Unfortunately it is licensed under a weird, non-free license.

**Comment by Janik-Haag** [comment]
I feel like if you want more discussion about that you should open a issue or make a post on discourse.

**Pull request merged**
