### PR TITLE
idea.android-studio: 1.5.0.4 -> 2.0.0.0

### PR DESCRIPTION
**Pull request by spinus**

### CODE REVIEW

**Comment by jagajaga** [comment]
cc @volhovM

**Comment by spinus** [comment]
hmm, maybe this should be separate package rather than upgrade?

**Comment by volhovM** [comment]
@spinus are there any real advantages of making it separate from prev. build?

**Comment by spinus** [comment]
@volhovM I'm not sure cause I'm using 2.0, but I can imagine that can be some backward incompatible changes.

**Comment by zimbatm** [comment]
Hi @spinus, can you rebase it on top of master ?

**Comment by spinus** [comment]
Sure thing.

**Pull request merged**
