### PR TITLE
gdm: 3.14.2 -> 3.20.1

### PR DESCRIPTION
**Pull request by DamienCassou**
This is an attempt to fix issue #16063. According to someone on #gnome, gdm and gnome are developed together and should be updated together. Non-matching versions of gdm and gnome may work, but it's untested.

### CODE REVIEW

**Comment by matthewbauer** [comment]
This looks good to me. I had a branch enabling Wayland support with the old GDM but I can rebase that onto this.

**Comment by DamienCassou** [comment]
please don't merge, it doesn't work (hence the `work-in-progress` status)

**Comment by lethalman** [comment]
Good luck :) And thanks for the work.

**Comment by vcunat** [comment]
gdm-3.22 should work on staging. See https://github.com/NixOS/nixpkgs/pull/19081#issuecomment-251256745 You can "rebase" in case there's anything useful left.

**Pull request closed without merging**
