### PR TITLE
bluemail: 1.136.21-1884 -> 1.140.8-1922 and add desktop item

### LINKED ISSUE #252443: Bluemail install does not create desktop shortcut NixOS
### Describe the bug
When installed through Nix, Bluemail does not create a desktop shortcut in $out/share/applications. The program can only be run through the terminal by default. The program also fails to load unless the --disable-gpu-sandbox option is used. 

### Steps To Reproduce
1. Install Bluemail by adding `environment.systemPackages = [pkgs.bluemail];` to configuration.nix, and rebuild.
2. Look for Bluemail in the Application Launcher - not present
3. Run `bluemail` in terminal - core dumps on gpu process not usable
4. Run `bluemail --disable-gpu-sandbox` in terminal - bluemail opens with the default wayland icon

### Expected behavior
What currently happens is detailed step-by-step above. 

What I'd expect to happen is that a desktop icon is created when I rebuild to install bluemail, and that clicking the application from the Application Launcher opens bluemail without a core dump.

### Additional context
Installing from NixOS-Unstable
Running on Intel UHD Graphics (10th Gen)

### Notify maintainers

@onny 

### Metadata
```console
[user@system:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.49, NixOS, 23.11 (Tapir), 23.11.20230830.e7f38be`
```

### PR DESCRIPTION
**Pull request by FliegendeWurst**
## Description of changes

Simple update and desktop item for existing package.

Fixes #252443
cc @Lordraven19

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`): the desktop item works, and the binary also works if you pass `--disable-gpu-sandbox`
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Could you rebase the PR please. Sorry that I missed it for so long!

**Comment by onny** [comment]
```
nixpkgs-review pr 258770
```
seems to fail, the hash checksum changed

**Comment by FliegendeWurst** [comment]
> seems to fail, the hash checksum changed

Fixed now

**Comment by onny** [comment]
hm strange, still get a different hash

```
error: hash mismatch in fixed-output derivation '/nix/store/32vdvmx371d9dxsaz7llicwhcxjj25x2-BlueMail.deb.drv':
         specified: sha256-zoFcZdw+0nVZnimbtEGnksnZqS3Lb43+QSFC56+Fv6o=
            got:    sha256-dnYOb3Q/9vSDssHGS2ywC/Q24Oq96/mvKF+eqd/4dVw=
error: 1 dependencies of derivation '/nix/store/a3mpq713iymg3307351jazxamis2m43v-bluemail-1.140.8-1922.drv' failed to build
error: 1 dependencies of derivation '/nix/store/m6x6v5i4zwzz85yylrjssphz59rzzlc2-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/258770

1 package failed to build:
bluemail

error: build log of '/nix/store/a3mpq713iymg3307351jazxamis2m43v-bluemail-1.140.8-1922.drv^*' is not available
error: build log of '/nix/store/z5mfs68hdf9p743xxdwbbmw1b17r6b7c-bluemail-1.140.8-1922' is not available
```

**Comment by onny** [comment]
Result of `nixpkgs-review pr 258770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bluemail</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you @FliegendeWurst :)

**Pull request merged**
