### PR TITLE
neovim-unwrapped: Fix 'disallowedRequisites' error

### PR DESCRIPTION
**Pull request by Gerg-L**
## Description of changes
Tested on nix 2.24pre and `nixVersions.minimum` (2.3.18)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Gerg-L** [comment]
Not sure this is the correct answer, i can't get this build to fail with CA derivations which was the original reason for the postInstall patch at all

**Comment by Gerg-L** [comment]
it looks like the `disallowedRequisites` came from https://github.com/NixOS/nixpkgs/commit/9305ed35ec7f38c6fed16e9d6d0dcd788f007b4d
But with removing the `disallowedRequisites` and the `postInstall`
it builds fine with `nix-build  --arg config '{ contentAddressedByDefault = true; }' -A neovim-unwrapped`
CC: @tie you add these bits originally can you look at this?

**Comment by tie** [comment]
> CC: @tie you added these bits originally can you look at this?

👀

I'll try to take a look at this tomorrow.

We should probably keep removeReferences though since IIRC neovim embeds the path to the compiler used to build it.

**Comment by Gerg-L** [comment]
alright if that's the case https://github.com/NixOS/nixpkgs/commit/eedc7c098d7baeb03da5e610f429704852431770 should work, i'm not sure on the exact correct nix version i believe it's 2.18 that `outputChecks.<output>.disallowedReferences` was added but i'm not entirely sure

**Comment by tie** [comment]
Maybe we can set `__structuredAttrs = true` and `outputChecks` unconditionally (without `disallowedRequisites`)? 🤔
I assume this *should* work as expected for recent Nix versions that support structured attributes and be no-op otherwise.

Converting `{,dis}allowed{References,Requisites}` to `outputChecks` based on the the Nix version should probably be done in mkDerivation and not on per-package basis. Or ideally shouldn't be done at all, I'm not really a fan of discarding string context in these attributes as is currently implemented since it breaks with CA derivations, hence the PR you've mentioned—and removeReferences/nukeReferences should be enough to avoid unwanted references in the derivation outputs.

**Comment by Gerg-L** [comment]
your suggested solution works on 
- 2.3
- 2.18
- 2.24-pre
- 2.24-pre CA

**Review by tie — APPROVED** [review]

**Review by sachinchaudhary1808 — APPROVED** [review]

**Comment by Aleksanaa** [comment]
Sorry

**Review by tie — APPROVED** [review]

**Review by andrevmatos — APPROVED** [review]

**Pull request closed without merging**
