### PR TITLE
rethinkdb: 2.3.6 -> 2.3.7

### PR DESCRIPTION
**Pull request by sugar700**
###### Motivation for this change

Making this package work. Not upgrading to 2.4.0 because I have no idea how to make 2.4.0 work with Nix.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xfix** [comment]
@GrahamcOfBorg build rethinkdb python27Packages.rethinkdb python37Packages.rethinkdb python38Packages.rethinkdb

**Comment by xfix** [comment]
@GrahamcOfBorg build rethinkdb python27Packages.rethinkdb python37Packages.rethinkdb python38Packages.rethinkdb

**Comment by xfix** [comment]
@GrahamcOfBorg build rethinkdb python27Packages.rethinkdb python37Packages.rethinkdb python38Packages.rethinkdb

**Comment by xfix** [comment]
Doesn't work.

**Comment by matthias-t** [comment]
Just saw this now, but two weeks ago I got this to work in #87828. @xfix, would you be willing to try it out and leave a review? You might also be interested in the following issue that I submitted upstream: rethinkdb/rethinkdb#6867.

**Pull request closed without merging**
