### PR TITLE
bundler: 1.17.1 -> 1.17.2

### PR DESCRIPTION
**Pull request by alyssais**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by alyssais** [comment]
@grahamcofborg eval

**Comment by zimbatm** [comment]
@alyssais do you want to take my place as a ruby maintainer? I don't use ruby that much these days and you have been doing a great job taking care of the regular upgrades.

**Comment by alyssais** [comment]
Sure, happy to. Does that mean change CODEOWNERS, or are there `maintainers`s somewhere that need to be updated? (Or both?)

**Comment by zimbatm** [comment]
CODEOWNERS and maintainers in `pkgs/development/ruby-modules/**/*.nix`. /cc @manveru to give access to bundix as well (or move it to the nix-community org).

**Comment by zimbatm** [comment]
thanks @manveru! Technically you should have access to move the repo. I don't know if there are strict benefits. I would say that if you don't want to maintain the repo actively then it probably makes sense to move it.

**Comment by alyssais** [comment]
I think having it in an org means that more than one person can administer it, whereas if it's attached to a user, only they can. So having it in an org reduces bus factor.

**Pull request merged**
