### PR TITLE
Add nvim-tree.lua, nvim-web-devicons, popfix, nvim-lsputils, vim-hexokinase, ci_dark, completion-buffers, nvim-highlite, vim-qf, nlua-nvim, BetterLua-vim, nvim-treesitter-context, nvcode-color-schemes-vim

### PR DESCRIPTION
**Pull request by onsails**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 98560` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>62 packages built:</summary>
  <ul>
    <li>vimPlugins.Gist (vimPlugins.vim-gist)</li>
    <li>vimPlugins.Tagbar (vimPlugins.tagbar)</li>
    <li>vimPlugins.UltiSnips (vimPlugins.ultisnips)</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.airline (vimPlugins.vim-airline)</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.asyncomplete-vim</li>
    <li>vimPlugins.caw (vimPlugins.caw-vim)</li>
    <li>vimPlugins.ci_dark</li>
    <li>vimPlugins.coc-fzf</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-buffers</li>
    <li>vimPlugins.completion-tabnine</li>
    <li>vimPlugins.csv (vimPlugins.csv-vim)</li>
    <li>vimPlugins.ctrlp (vimPlugins.ctrlp-vim)</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.denite (vimPlugins.denite-nvim)</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.gentoo-syntax</li>
    <li>vimPlugins.gruvbox-community</li>
    <li>vimPlugins.indentLine</li>
    <li>vimPlugins.lightline-vim</li>
    <li>vimPlugins.lsp_extensions-nvim</li>
    <li>vimPlugins.ncm2-ultisnips</li>
    <li>vimPlugins.neosnippet-snippets</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-lsputils</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.polyglot (vimPlugins.vim-polyglot)</li>
    <li>vimPlugins.popfix</li>
    <li>vimPlugins.purescript-vim</li>
    <li>vimPlugins.snipmate (vimPlugins.vim-snipmate)</li>
    <li>vimPlugins.tcomment_vim</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-closetag</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-hexokinase</li>
    <li>vimPlugins.vim-javacomplete2</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-monokai-pro</li>
    <li>vimPlugins.vim-qf</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-startify</li>
    <li>vimPlugins.vim-tmux-focus-events</li>
    <li>vimPlugins.vim-twiggy</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vim-which-key</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.vista-vim</li>
    <li>vimPlugins.zig-vim</li>
  </ul>
</details>

**Comment by onsails** [comment]
@GrahamcOfBorg eval

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 98560` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>88 packages built:</summary>
  <ul>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.Gist (vimPlugins.vim-gist)</li>
    <li>vimPlugins.Tagbar (vimPlugins.tagbar)</li>
    <li>vimPlugins.UltiSnips (vimPlugins.ultisnips)</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.airline (vimPlugins.vim-airline)</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.asyncomplete-vim</li>
    <li>vimPlugins.caw (vimPlugins.caw-vim)</li>
    <li>vimPlugins.ci_dark</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-fzf</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-buffers</li>
    <li>vimPlugins.completion-tabnine</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.csv (vimPlugins.csv-vim)</li>
    <li>vimPlugins.ctrlp (vimPlugins.ctrlp-vim)</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.denite (vimPlugins.denite-nvim)</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.direnv-vim</li>
    <li>vimPlugins.echodoc (vimPlugins.echodoc-vim)</li>
    <li>vimPlugins.fugitive (vimPlugins.vim-fugitive)</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.gen_tags-vim</li>
    <li>vimPlugins.gentoo-syntax</li>
    <li>vimPlugins.gruvbox-community</li>
    <li>vimPlugins.indentLine</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.lean-vim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lightline-vim</li>
    <li>vimPlugins.limelight-vim</li>
    <li>vimPlugins.lsp_extensions-nvim</li>
    <li>vimPlugins.ncm2-ultisnips</li>
    <li>vimPlugins.neosnippet-snippets</li>
    <li>vimPlugins.nlua-nvim</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-lsputils</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.onehalf</li>
    <li>vimPlugins.polyglot (vimPlugins.vim-polyglot)</li>
    <li>vimPlugins.popfix</li>
    <li>vimPlugins.purescript-vim</li>
    <li>vimPlugins.snipmate (vimPlugins.vim-snipmate)</li>
    <li>vimPlugins.table-mode (vimPlugins.vim-table-mode)</li>
    <li>vimPlugins.tcomment_vim</li>
    <li>vimPlugins.traces-vim</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-closetag</li>
    <li>vimPlugins.vim-dirdiff</li>
    <li>vimPlugins.vim-fireplace</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-hexokinase</li>
    <li>vimPlugins.vim-javacomplete2</li>
    <li>vimPlugins.vim-jsdoc</li>
    <li>vimPlugins.vim-lawrencium</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-monokai</li>
    <li>vimPlugins.vim-monokai-pro</li>
    <li>vimPlugins.vim-ocaml</li>
    <li>vimPlugins.vim-prosession</li>
    <li>vimPlugins.vim-qf</li>
    <li>vimPlugins.vim-qml</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-startify</li>
    <li>vimPlugins.vim-terraform</li>
    <li>vimPlugins.vim-tmux-focus-events</li>
    <li>vimPlugins.vim-twiggy</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vim-which-key</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.vista-vim</li>
    <li>vimPlugins.zig-vim</li>
    <li>vimPlugins.zoomwintab-vim</li>
  </ul>
</details>

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 98560` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>115 packages built:</summary>
  <ul>
    <li>vimPlugins.BetterLua-vim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.Gist (vimPlugins.vim-gist)</li>
    <li>vimPlugins.Tagbar (vimPlugins.tagbar)</li>
    <li>vimPlugins.nerdtree (vimPlugins.The_NERD_tree)</li>
    <li>vimPlugins.UltiSnips (vimPlugins.ultisnips)</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.airline (vimPlugins.vim-airline)</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.ansible-vim</li>
    <li>vimPlugins.asyncomplete-vim</li>
    <li>vimPlugins.awesome-vim-colorschemes</li>
    <li>vimPlugins.calendar (vimPlugins.calendar-vim)</li>
    <li>vimPlugins.caw (vimPlugins.caw-vim)</li>
    <li>vimPlugins.ci_dark</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-fzf</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-buffers</li>
    <li>vimPlugins.completion-nvim</li>
    <li>vimPlugins.completion-tabnine</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.csv (vimPlugins.csv-vim)</li>
    <li>vimPlugins.ctrlp (vimPlugins.ctrlp-vim)</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.denite (vimPlugins.denite-nvim)</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.deoplete-vim-lsp</li>
    <li>vimPlugins.direnv-vim</li>
    <li>vimPlugins.dracula-vim</li>
    <li>vimPlugins.echodoc (vimPlugins.echodoc-vim)</li>
    <li>vimPlugins.editorconfig-vim</li>
    <li>vimPlugins.emmet-vim</li>
    <li>vimPlugins.flake8-vim</li>
    <li>vimPlugins.fugitive (vimPlugins.vim-fugitive)</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.gen_tags-vim</li>
    <li>vimPlugins.gentoo-syntax</li>
    <li>vimPlugins.gruvbox-community</li>
    <li>vimPlugins.gv-vim</li>
    <li>vimPlugins.hoon-vim</li>
    <li>vimPlugins.indentLine</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.lean-vim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lightline-vim</li>
    <li>vimPlugins.limelight-vim</li>
    <li>vimPlugins.lsp_extensions-nvim</li>
    <li>vimPlugins.ncm2-ultisnips</li>
    <li>vimPlugins.neosnippet-snippets</li>
    <li>vimPlugins.nerdtree-git-plugin</li>
    <li>vimPlugins.nim-vim</li>
    <li>vimPlugins.nlua-nvim</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-lsputils</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.onehalf</li>
    <li>vimPlugins.palenight-vim</li>
    <li>vimPlugins.polyglot (vimPlugins.vim-polyglot)</li>
    <li>vimPlugins.popfix</li>
    <li>vimPlugins.purescript-vim</li>
    <li>vimPlugins.skim-vim</li>
    <li>vimPlugins.snipmate (vimPlugins.vim-snipmate)</li>
    <li>vimPlugins.table-mode (vimPlugins.vim-table-mode)</li>
    <li>vimPlugins.tcomment_vim</li>
    <li>vimPlugins.traces-vim</li>
    <li>vimPlugins.tsuquyomi</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-closetag</li>
    <li>vimPlugins.vim-dirdiff</li>
    <li>vimPlugins.vim-fireplace</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-hexokinase</li>
    <li>vimPlugins.vim-javacomplete2</li>
    <li>vimPlugins.vim-jsdoc</li>
    <li>vimPlugins.vim-lawrencium</li>
    <li>vimPlugins.vim-lsc</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-monokai</li>
    <li>vimPlugins.vim-monokai-pro</li>
    <li>vimPlugins.vim-ocaml</li>
    <li>vimPlugins.vim-orgmode</li>
    <li>vimPlugins.vim-pandoc-syntax</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-prosession</li>
    <li>vimPlugins.vim-qf</li>
    <li>vimPlugins.vim-qml</li>
    <li>vimPlugins.vim-racer</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-startify</li>
    <li>vimPlugins.vim-terraform</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-tmux-focus-events</li>
    <li>vimPlugins.vim-twiggy</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vim-vsnip-integ</li>
    <li>vimPlugins.vim-which-key</li>
    <li>vimPlugins.vim-wordy</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.vista-vim</li>
    <li>vimPlugins.zig-vim</li>
    <li>vimPlugins.zoomwintab-vim</li>
  </ul>
</details>

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 98560` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>116 packages built:</summary>
  <ul>
    <li>vimPlugins.BetterLua-vim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.Gist (vimPlugins.vim-gist)</li>
    <li>vimPlugins.Tagbar (vimPlugins.tagbar)</li>
    <li>vimPlugins.nerdtree (vimPlugins.The_NERD_tree)</li>
    <li>vimPlugins.UltiSnips (vimPlugins.ultisnips)</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.airline (vimPlugins.vim-airline)</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.ansible-vim</li>
    <li>vimPlugins.asyncomplete-vim</li>
    <li>vimPlugins.awesome-vim-colorschemes</li>
    <li>vimPlugins.calendar (vimPlugins.calendar-vim)</li>
    <li>vimPlugins.caw (vimPlugins.caw-vim)</li>
    <li>vimPlugins.ci_dark</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-fzf</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-buffers</li>
    <li>vimPlugins.completion-nvim</li>
    <li>vimPlugins.completion-tabnine</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.csv (vimPlugins.csv-vim)</li>
    <li>vimPlugins.ctrlp (vimPlugins.ctrlp-vim)</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.denite (vimPlugins.denite-nvim)</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.deoplete-vim-lsp</li>
    <li>vimPlugins.direnv-vim</li>
    <li>vimPlugins.dracula-vim</li>
    <li>vimPlugins.echodoc (vimPlugins.echodoc-vim)</li>
    <li>vimPlugins.editorconfig-vim</li>
    <li>vimPlugins.emmet-vim</li>
    <li>vimPlugins.flake8-vim</li>
    <li>vimPlugins.fugitive (vimPlugins.vim-fugitive)</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.gen_tags-vim</li>
    <li>vimPlugins.gentoo-syntax</li>
    <li>vimPlugins.gruvbox-community</li>
    <li>vimPlugins.gv-vim</li>
    <li>vimPlugins.hoon-vim</li>
    <li>vimPlugins.indentLine</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.lean-vim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lightline-vim</li>
    <li>vimPlugins.limelight-vim</li>
    <li>vimPlugins.lsp_extensions-nvim</li>
    <li>vimPlugins.ncm2-ultisnips</li>
    <li>vimPlugins.neosnippet-snippets</li>
    <li>vimPlugins.nerdtree-git-plugin</li>
    <li>vimPlugins.nim-vim</li>
    <li>vimPlugins.nlua-nvim</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-lsputils</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.onehalf</li>
    <li>vimPlugins.palenight-vim</li>
    <li>vimPlugins.polyglot (vimPlugins.vim-polyglot)</li>
    <li>vimPlugins.popfix</li>
    <li>vimPlugins.purescript-vim</li>
    <li>vimPlugins.skim-vim</li>
    <li>vimPlugins.snipmate (vimPlugins.vim-snipmate)</li>
    <li>vimPlugins.table-mode (vimPlugins.vim-table-mode)</li>
    <li>vimPlugins.tcomment_vim</li>
    <li>vimPlugins.traces-vim</li>
    <li>vimPlugins.tsuquyomi</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-closetag</li>
    <li>vimPlugins.vim-dirdiff</li>
    <li>vimPlugins.vim-fireplace</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-hexokinase</li>
    <li>vimPlugins.vim-illuminate</li>
    <li>vimPlugins.vim-javacomplete2</li>
    <li>vimPlugins.vim-jsdoc</li>
    <li>vimPlugins.vim-lawrencium</li>
    <li>vimPlugins.vim-lsc</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-monokai</li>
    <li>vimPlugins.vim-monokai-pro</li>
    <li>vimPlugins.vim-ocaml</li>
    <li>vimPlugins.vim-orgmode</li>
    <li>vimPlugins.vim-pandoc-syntax</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-prosession</li>
    <li>vimPlugins.vim-qf</li>
    <li>vimPlugins.vim-qml</li>
    <li>vimPlugins.vim-racer</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-startify</li>
    <li>vimPlugins.vim-terraform</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-tmux-focus-events</li>
    <li>vimPlugins.vim-twiggy</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vim-vsnip-integ</li>
    <li>vimPlugins.vim-which-key</li>
    <li>vimPlugins.vim-wordy</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.vista-vim</li>
    <li>vimPlugins.zig-vim</li>
    <li>vimPlugins.zoomwintab-vim</li>
  </ul>
</details>

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 98560` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>44 packages built:</summary>
  <ul>
    <li>vimPlugins.BetterLua-vim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.Tagbar (vimPlugins.tagbar)</li>
    <li>vimPlugins.nerdcommenter (vimPlugins.The_NERD_Commenter)</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.airline (vimPlugins.vim-airline)</li>
    <li>vimPlugins.ci_dark</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-buffers</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-lsp</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.gitgutter (vimPlugins.vim-gitgutter)</li>
    <li>vimPlugins.lightline-bufferline</li>
    <li>vimPlugins.lsp_extensions-nvim</li>
    <li>vimPlugins.nlua-nvim</li>
    <li>vimPlugins.nvcode-color-schemes-vim</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-lsputils</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.popfix</li>
    <li>vimPlugins.tcomment_vim</li>
    <li>vimPlugins.vim-abolish</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-carbon-now-sh</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-elm-syntax</li>
    <li>vimPlugins.vim-fireplace</li>
    <li>vimPlugins.vim-hexokinase</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-manpager</li>
    <li>vimPlugins.vim-qf</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-visual-multi</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.yats-vim</li>
  </ul>
</details>

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 98560` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>vimPlugins.BetterLua-vim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.Syntastic (vimPlugins.syntastic)</li>
    <li>vimPlugins.airline (vimPlugins.vim-airline)</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.ci_dark</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-buffers</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-jedi</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.gitgutter (vimPlugins.vim-gitgutter)</li>
    <li>vimPlugins.hoon-vim</li>
    <li>vimPlugins.indentLine</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neomake</li>
    <li>vimPlugins.neoterm</li>
    <li>vimPlugins.neuron-vim</li>
    <li>vimPlugins.nlua-nvim</li>
    <li>vimPlugins.nvcode-color-schemes-vim</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-lsputils</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.oceanic-next</li>
    <li>vimPlugins.open-browser-github-vim</li>
    <li>vimPlugins.papercolor-theme</li>
    <li>vimPlugins.popfix</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.undotree</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-bsv</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-exchange</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-hexokinase</li>
    <li>vimPlugins.vim-jsx-pretty</li>
    <li>vimPlugins.vim-lsc</li>
    <li>vimPlugins.vim-mundo</li>
    <li>vimPlugins.vim-pandoc</li>
    <li>vimPlugins.vim-projectionist</li>
    <li>vimPlugins.vim-qf</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vim-vsnip-integ</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.wal-vim</li>
    <li>vimPlugins.yats-vim</li>
  </ul>
</details>

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 98560` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>vimPlugins.BetterLua-vim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.ci_dark</li>
    <li>vimPlugins.completion-buffers</li>
    <li>vimPlugins.gruvbox-community</li>
    <li>vimPlugins.lightline-vim</li>
    <li>vimPlugins.nlua-nvim</li>
    <li>vimPlugins.nvcode-color-schemes-vim</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-lsputils</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.popfix</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-hexokinase</li>
    <li>vimPlugins.vim-lsc</li>
    <li>vimPlugins.vim-qf</li>
    <li>vimPlugins.vim-visual-multi</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vimspector</li>
  </ul>
</details>

**Comment by teto** [comment]
could you regenerate the last commit (many changes in the neovim ecosystem this week).

**Comment by onsails** [comment]
@teto thanks, I've rearranged all commits. Regenerated update commit and put all new plugins and hexokinase bin on top of it.

**Pull request merged**
