### PR TITLE
surrealdb: 1.2.1 → 1.3.1

### PR DESCRIPTION
**Pull request by sikmir**
## Description of changes
https://github.com/surrealdb/surrealdb/releases

## Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 296379` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>surrealdb</li>
  </ul>
</details>

**Comment by happysalada** [comment]
There seems to be a compilation failure on the test phase
```
surrealdb>    Compiling reqwest v0.11.24
surrealdb>    Compiling tower-http v0.4.4
surrealdb>    Compiling rocksdb v0.21.0
surrealdb>    Compiling tonic v0.8.3
surrealdb>    Compiling axum-extra v0.7.7
surrealdb>    Compiling opentelemetry-proto v0.2.0
surrealdb>    Compiling opentelemetry-otlp v0.12.0
surrealdb>    Compiling rquickjs v0.5.1
surrealdb>    Compiling surrealdb-core v1.3.1 (/build/source/core)
surrealdb>    Compiling surrealdb v1.3.1 (/build/source/lib)
surrealdb>    Compiling surreal v1.3.1 (/build/source)
surrealdb> error: rustc interrupted by SIGSEGV, printing backtrace
surrealdb>
surrealdb> /nix/store/ybac1h0f1qkf2fp76816cfnw2knr9mh3-rustc-1.76.0/lib/librustc_driver-
98875b63f148d624.so(+0x7bbbd6)[0x7ffff44fabd6]
surrealdb> /nix/store/ksk3rnb0ljx8gngzk19jlmbjyvac4hw6-glibc-2.38-44/lib/libc.so.6(+0x3d
eb0)[0x7ffff3a4beb0]
surrealdb> /nix/store/qlvl2h5yihryfvjdmh3hx4s0qpm15kvn-llvm-17.0.6-lib/lib/libLLVM-17.so
(_ZNK4llvm8Constant23removeDeadConstantUsersEv+0x20)[0x7fffebeb1c70]
surrealdb> /nix/store/qlvl2h5yihryfvjdmh3hx4s0qpm15kvn-llvm-17.0.6-lib/lib/libLLVM-17.so
(_ZN4llvm13GlobalDCEPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE+0x375)[0x7fffed4c
88d5]
surrealdb> /nix/store/qlvl2h5yihryfvjdmh3hx4s0qpm15kvn-llvm-17.0.6-lib/lib/libLLVM-17.so
(+0x38bd251)[0x7fffee8e3251]
surrealdb> /nix/store/qlvl2h5yihryfvjdmh3hx4s0qpm15kvn-llvm-17.0.6-lib/lib/libLLVM-17.so
(_ZN4llvm11PassManagerINS_6ModuleENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_+0x10e)[0x
7fffec004a9e]
surrealdb> /nix/store/ybac1h0f1qkf2fp76816cfnw2knr9mh3-rustc-1.76.0/lib/librustc_driver-
98875b63f148d624.so(LLVMRustOptimize+0x8c4)[0x7ffff48a16a4]
surrealdb> /nix/store/ybac1h0f1qkf2fp76816cfnw2knr9mh3-rustc-1.76.0/lib/librustc_driver-
surrealdb> /nix/store/ybac1h0f1qkf2fp76816cfnw2knr9mh3-rustc-1.76.0/lib/librustc_driver-
surrealdb> /nix/store/ybac1h0f1qkf2fp76816cfnw2knr9mh3-rustc-1.76.0/lib/librustc_driver-
surrealdb> /nix/store/ybac1h0f1qkf2fp76816cfnw2knr9mh3-rustc-1.76.0/lib/librustc_driver-
surrealdb> /nix/store/ybac1h0f1qkf2fp76816cfnw2knr9mh3-rustc-1.76.0/lib/libstd-617774f85
surrealdb> /nix/store/ksk3rnb0ljx8gngzk19jlmbjyvac4hw6-glibc-2.38-44/lib/libc.so.6(+0x8b
surrealdb> /nix/store/ksk3rnb0ljx8gngzk19jlmbjyvac4hw6-glibc-2.38-44/lib/libc.so.6(+0x10
surrealdb>
surrealdb> note: we would appreciate a report at https://github.com/rust-lang/rust
surrealdb> thread 'main' panicked at cargo-auditable/src/rustc_wrapper.rs:91:39:
surrealdb> called `Option::unwrap()` on a `None` value
surrealdb> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
surrealdb> error: could not compile `surreal` (test "http_integration")
surrealdb> warning: build failed, waiting for other jobs to finish...
surrealdb> error: rustc interrupted by SIGSEGV, printing backtrace
surrealdb>
```
(on linux-x86_64)

**Comment by sikmir** [comment]
That's strange, linux-x86_64 builds fine for me.

**Comment by risicle** [comment]
Me too :confused: 

Along with macos 12 x86_64

**Comment by sikmir** [comment]
Looks like some tests are fluky, I've build multiple times on darwin and got 1 failed test `cli_integration::node`.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 296379` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>surrealdb</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Should we wait on the next one ?
Its either a problem with llvm17, or a problem with this release in particular, but it definitely doesnt compile for me.

**Comment by happysalada** [comment]
Ok lets do this, since the failure happens during the checkphase, lets disable the checkphase for now and see if it can be reenabled without problem on the next release

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 296379` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>surrealdb</li>
  </ul>
</details>

**Pull request merged**
