### PR TITLE
apitrace: 7.1-572-g26966134 -> 11.0

### PR DESCRIPTION
**Pull request by armeenm**
###### Description of changes
https://github.com/apitrace/apitrace/releases/tag/11.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
Result of `nixpkgs-review pr 164600` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>apitrace</li>
  </ul>
</details>

```
error: builder for '/nix/store/6cl348h0pavgcq0jydx77bpjgfj71h9b-apitrace-10.0.drv' failed with exit code 1;
       last 9 log lines:
       > qtPreHook
       > unpacking sources
       > unpacking source archive /nix/store/g8g58vj2xz65qgrc96m6fj5997nxbszh-source
       > source root is source
       > patching sources
       > applying patch /nix/store/9yb61256pdx1l412jghys3lid31j4hxm-glibc-2.34-compat.patch
       > patching file wrappers/dlsym.cpp
       > Hunk #1 FAILED at 34.
       > 1 out of 1 hunk FAILED -- saving rejects to file wrappers/dlsym.cpp.rej
       For full logs, run 'nix log /nix/store/6cl348h0pavgcq0jydx77bpjgfj71h9b-apitrace-10.0.drv'.
error: 1 dependencies of derivation '/nix/store/x7qilgsri3j0an810hh1wpfqbl9w71qj-review-shell.drv' failed to build
```

**Comment by armeenm** [comment]
Strange. `nix build .#apitrace` works fine for me but it patching fails when using `nixpkgs-review` as you found out. I'm not sure where that patching is happening because the code in this PR doesn't attempt any patches.

**Comment by Mindavi** [comment]
@ofborg build apitrace

**Comment by Mindavi** [comment]
Still needs some work to go over the finish line, still planning to do so @armeenm ?

**Comment by armeenm** [comment]
Yep, been a bit busy lately but I'll wrap this one up sometime this week.

**Comment by wegank** [comment]
Closed by #201032.

**Pull request closed without merging**
