### PR TITLE
fwupd: 1.2.8 → 1.2.10

### PR DESCRIPTION
**Pull request by jtojnar**
Reverts https://github.com/NixOS/nixpkgs/pull/67000

https://github.com/fwupd/fwupd/blob/1.2.10/data/org.freedesktop.fwupd.metainfo.xml#L35-L81

* adopt the package
* libflashrom is disabled by default since it is experimental now.
* add installed tests to passthru for easier running
* concretize patchShebags
* no changes in filesInstalledToEtc

### CODE REVIEW

**Comment by jtojnar** [comment]
Still building the polkit fix. fwupd builds eatremely slow while I am also building #67596.

**Comment by jtojnar** [comment]
The issue with the missing PolKit files in the installed tests:

```
Running test: fwupd/fwupdmgr.test
Getting the list of remotes...
PolicyKit files are missing, see https://github.com/hughsie/fwupd/wiki/PolicyKit-files-are-missing
FAIL: fwupd/fwupdmgr.test (Child process exited with code 1)
```

is that fwupd now checks for presence of the polkit actions on the system:

https://github.com/fwupd/fwupd/blob/80e02dfe21068125399b8a8cb5cb870b59ccb58c/src/fu-util.c#L2196-L2206

The path is obtained from pkg-config:

https://github.com/fwupd/fwupd/blob/80e02dfe21068125399b8a8cb5cb870b59ccb58c/src/fu-common.c#L1038-L1043

https://github.com/fwupd/fwupd/blob/80e02dfe21068125399b8a8cb5cb870b59ccb58c/meson.build#L166-L170

so we will override it with a environment variable.

It will not affect the installation, since `install_dir` paths are hard-coded:

https://github.com/fwupd/fwupd/blob/80e02dfe21068125399b8a8cb5cb870b59ccb58c/policy/meson.build#L10

**Review by worldofpeace — APPROVED** [review]
Changes look good, it builds for me on NixOS (test included).

**Comment by jtojnar** [comment]
There will be a new release soon so we might want to wait https://github.com/fwupd/fwupd/issues/1320

**Comment by jtojnar** [comment]
I also packaged [gnome-firmware-updater](https://blogs.gnome.org/hughsie/2019/08/28/gnome-firmware-updater/): https://github.com/jtojnar/nixpkgs/tree/gnome-firmware-updater
But it is probably not suitable for inclusion yet.

**Comment by jtojnar** [comment]
From the blog post:

> At the moment it’s a seporate project and binary, as we’re still prototyping the UI and working out what kind of UX we want from a power user tool. It’s mostly complete and a few weeks away from it’s first release. When it does get an official release

**Comment by superm1** [comment]
> so we will override it with a environment variable.

If you see a need to override this at runtime, can you please send a PR to look for the new variable?  Or are you meaning only in the test suite you'll hardcode to a particular location?

**Comment by jtojnar** [comment]
@superm1 we override it at build time. The pkg-config variable works for finding a path to install polkit actions but, due to the way we install global data, polkit needs to look for it in a different path.

**Comment by disassembler** [comment]
I'm fine waiting, but we may want to go ahead with this if there isn't a new release by Friday.

**Comment by jtojnar** [comment]
Merging as the release still did not happen.

**Pull request merged**
