### PR TITLE
added tldr package

### PR DESCRIPTION
**Pull request by Radvendii**

### CODE REVIEW

**Comment by Radvendii** [comment]
Forgot to change all-packages.nix. Will update and re-pull-request

**Comment by nckx** [comment]
While you're at it, there are a few other things that need fixing:
- Please use (double space) indentation:

```
{
  hiWerld = ''
    echo Hello world.
  '';
}
```
- It's customary to put `src` right under `name` for easy updating, and because it makes chronological sence.
- No need for ; at the end of lines in bash code.
- No need to close pull requests for changes, just `git push -f` to the PR branch instead.

**Comment by nckx** [comment]
- And please use `tldr: init at 1.0` as commit message.

**Comment by Radvendii** [comment]
Oops! I already sent another pull request. I can fix the other issues you sent me, but is there anything to do about this one now?
Thanks so much for the feedback :)

**Comment by nckx** [comment]
No, just keep this closed and fix up the new one. I'll add a link to this thread.

No problem :-)

**Pull request closed without merging**
