### PR TITLE
Fix "batch" command on NixOS

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change
Fix https://github.com/NixOS/nixpkgs/issues/12392

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yesbox** [comment]
Works fine now on NixOS 17.09 with this patch and looks like it shouldn't break the package on other OSes or without the NixOS module.

**Comment by yesbox** [comment]
You could also remove "batch" from the from the list of programs to be wrapped in the atd service module. It probably never worked in the first place and now doesn't serve a purpose.

**Comment by bjornfor** [comment]
Good catch. Fixed.

**Comment by bjornfor** [comment]
Applied to master and cherry-picked to release-17.09.

**Pull request merged**
