### PR TITLE
starship: 0.45.2 -> 0.46.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
https://github.com/starship/starship/releases/tag/v0.46.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Fails with the following test failures for me:

```
starship> failures:
starship> ---- modules::golang::tests::folder_with_glide_yaml stdout ----
starship> thread 'modules::golang::tests::folder_with_glide_yaml' panicked at 'assertion failed: `(left == right)`
starship>   left: `Some("via \u{1b}[1;36m🐹 v1.12.1\u{1b}[0m ")`,
starship>  right: `None`', src/modules/golang.rs:162:9
starship> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
starship> failures:
starship>     modules::golang::tests::folder_with_glide_yaml
starship> test result: FAILED. 449 passed; 1 failed; 25 ignored; 0 measured; 10 filtered out
starship> error: test failed, to rerun pass '--lib'
starship> builder for '/nix/store/rqx5mhvr897i1n13rvkx9q29nd8xpk3f-starship-0.46.0.drv' failed with exit code 101

```

**Comment by bbigras** [comment]
@Ma27 on NixOS?

**Comment by bbigras** [comment]
Result of `nixpkgs-review pr 100043` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>starship</li>
  </ul>
</details>

**Review by davidtwco — APPROVED** [review]
Result of `nixpkgs-review pr 100043` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>starship</li>
  </ul>
</details>

**Comment by Ma27** [comment]
@bbigras yes.

**Comment by Ma27** [comment]
Is there anything wrong with disabling this test?

**Comment by bbigras** [comment]
> Is there anything wrong with disabling this test?

Maybe we could but could you also run the tests directly on the upstream repo and fill an issue upstream?

```sh
git clone https://github.com/starship/starship.git
cd starship
nix-shell -p cargo
cargo test
```

**Comment by marsam** [comment]
>Is there anything wrong with disabling this test?

the test itself looks ordinary, and I'm not sure why it's failing for you.
could you please give the following a try?
```diff
--- i/pkgs/tools/misc/starship/default.nix
+++ w/pkgs/tools/misc/starship/default.nix
@@ -33,13 +33,14 @@ rustPlatform.buildRustPackage rec {
 
   cargoSha256 = "1smz7084ppz79p8migpy0cqp6azf7sixv9ga65l2f3zfna7kbk78";
 
+  cargoParallelTestThreads = false;
+
   checkFlags = [
     "--skip=directory_in_home"
     "--skip=home_directory"
     "--skip=directory_in_root"
     "--skip=truncation_symbol_not_truncated_home"
     "--skip=truncation_symbol_truncated_home"
-    "--skip=folder_with_glide_yaml"
     "--skip=shows_multiple_tfms"
     "--skip=shows_pinned_in_project_below_root_with_global_json"
   ];

```

**Comment by teto** [comment]
dunno if that helps but current release is https://github.com/starship/starship/tree/v0.46.2

**Pull request merged**
