### PR TITLE
python3Packages.phonemizer: fix build

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

ZHF: https://github.com/NixOS/nixpkgs/issues/172160

### CODE REVIEW

**Comment by WolfangAukang** [comment]
Result of `nixpkgs-review pr 172274` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.dlinfo</li>
    <li>python310Packages.phonemizer</li>
    <li>python39Packages.dlinfo</li>
    <li>python39Packages.phonemizer</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
@ofborg build python39.pkgs.phonemizer python310.pkgs.phonemizer

**Comment by WolfangAukang** [comment]
I get issues using the library but they are unrelated to `phonemizer`

```console
[nix-shell:~/.cache/nixpkgs-review/pr-172274]$ python
Python 3.10.4 (main, Mar 23 2022, 20:25:24) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from phonemizer import phonemize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/5gy8339a89dyvc0v0zlg2s0851nivv2z-phonemizer-3.1.1/lib/python3.9/site-packages/phonemizer/__init__.py", line 36, in <module>
    from .phonemize import phonemize  # pylint: disable=unused-import
  File "/nix/store/5gy8339a89dyvc0v0zlg2s0851nivv2z-phonemizer-3.1.1/lib/python3.9/site-packages/phonemizer/phonemize.py", line 30, in <module>
    from phonemizer.backend import BACKENDS
  File "/nix/store/5gy8339a89dyvc0v0zlg2s0851nivv2z-phonemizer-3.1.1/lib/python3.9/site-packages/phonemizer/backend/__init__.py", line 22, in <module>
    from .segments import SegmentsBackend
  File "/nix/store/5gy8339a89dyvc0v0zlg2s0851nivv2z-phonemizer-3.1.1/lib/python3.9/site-packages/phonemizer/backend/segments.py", line 21, in <module>
    import segments
  File "/nix/store/iwdxb7bcs5bk6wb4jgwppyplsn1k25sy-python3.9-segments-2.2.0/lib/python3.9/site-packages/segments/__init__.py", line 1, in <module>
    from segments.tokenizer import Tokenizer, Rules  # noqa: F401
  File "/nix/store/iwdxb7bcs5bk6wb4jgwppyplsn1k25sy-python3.9-segments-2.2.0/lib/python3.9/site-packages/segments/tokenizer.py", line 7, in <module>
    import regex
  File "/nix/store/nxxlxw8j0zr17xjsrs7b67piqs504cxd-python3.9-regex-2022.3.2/lib/python3.9/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/nix/store/nxxlxw8j0zr17xjsrs7b67piqs504cxd-python3.9-regex-2022.3.2/lib/python3.9/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/nix/store/nxxlxw8j0zr17xjsrs7b67piqs504cxd-python3.9-regex-2022.3.2/lib/python3.9/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
```

**Review by WolfangAukang — APPROVED** [review]
Changes LGTM

**Comment by dotlambda** [comment]
@ofborg build python39.pkgs.dlinfo python310.pkgs.dlinfo

**Comment by dotlambda** [comment]
```
_____________________________ test_dlinfo_path[c] ______________________________
lib_name = 'c'
    @pytest.mark.parametrize('lib_name', [
        'c',
        'dl',
        'python_grasp',
    ])
    def test_dlinfo_path(lib_name):
        lib_filename = ctypes.util.find_library(lib_name)
        if not lib_filename:
            pytest.xfail('lib{} not found'.format(lib_name))
        lib = ctypes.cdll.LoadLibrary(lib_filename)
        dlinfo = DLInfo(lib)
>       assert os.path.exists(dlinfo.path)
E       AssertionError: assert False
E        +  where False = <function exists at 0x10ff26cb0>('/usr/lib/libc.dylib')
E        +    where <function exists at 0x10ff26cb0> = <module 'posixpath' from '/nix/store/yd6kyg0ml79qamkhiqk1mrf3lvhcv0mb-python3-3.10.4/lib/python3.10/posixpath.py'>.exists
E        +      where <module 'posixpath' from '/nix/store/yd6kyg0ml79qamkhiqk1mrf3lvhcv0mb-python3-3.10.4/lib/python3.10/posixpath.py'> = os.path
E        +    and   '/usr/lib/libc.dylib' = <dlinfo._macosx.DLInfo object at 0x111162080>.path
```

@NixOS/darwin-maintainers Any idea what's going on? Here's the relevant upstream code: https://github.com/cloudflightio/python-dlinfo/blob/master/dlinfo/_macosx.py

**Comment by dotlambda** [comment]
I have no idea how to fix dlinfo so I'll just mark it as broken on Darwin.

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 172274` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.dlinfo</li>
    <li>python310Packages.phonemizer</li>
    <li>python39Packages.dlinfo</li>
    <li>python39Packages.phonemizer</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
