### PR TITLE
airwindows: init at 20-08-2018

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Build checked locally. But I think the package should be classified as unfree as it requires the unfree SDK. You cannot mark only the SDK as unfree since is only a local derivation, not a separate package in nixpgs. The way it is structured now, `airwindows` is unfree.

**Comment by magnetophon** [comment]
@xeji [Airwave](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/airwave/default.nix) is also using the vst sdk and has an MIT license.

**Comment by xeji** [comment]
Same thing. The author may have licensed their code under MIT. But since the derivation in nixpkgs includes the unfree sdk it should be marked unfree as they're packaged together. 

The best solution would be to make the vst sdk a separate unfree package and make `airwave` and `airwindows`  reference it as a dependency. That would correctly describe the licensing situation.

**Comment by magnetophon** [comment]
@xeji I won't be able to work on this for a while.
There is awareness of the problem [upstream](https://github.com/ech2/airwindows-ports/issues/1) though.
Should I close this PR for now, or leave it open?

**Comment by xeji** [comment]
No problem, let's leave it open, I'll mark it as WIP.

**Comment by mmahut** [comment]
Any updates on this pull request, please?

**Comment by magnetophon** [comment]
Nothing has changed, sorry.
Schall I close it?

**Comment by magnetophon** [comment]
Unfortunately not, sorry.
Shall I close it?

**Comment by magnetophon** [comment]
Unfortunately not, sorry.
Shall I close it?

**Pull request closed without merging**
