### PR TITLE
[Backport release-23.05] xivlauncher: 1.0.3 -> 1.0.6

### PR DESCRIPTION
**Pull request by keysmashes**
## Description of changes

stable backport of #258794: xivlauncher versions before 1.0.5 cannot successfully install the latest game update (which is required to play), and 1.0.6 includes a number of fixes for problems in 1.0.5.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by witchof0x20 — APPROVED** [review]

**Review by fabianhjr — CHANGES_REQUESTED** [review]
Hi, please use `git cherry-pick -x` as per the Contributing guidelines. (It helps keep track of changes)


- Instead of manually making and committing the changes, use [`git cherry-pick -x`](https://git-scm.com/docs/git-cherry-pick) for each commit from the pull request you'd like to backport.
  Either `git cherry-pick -x <commit>` when the reason for the backport is obvious (such as minor versions, fixes, etc.), otherwise use `git cherry-pick -xe <commit>` to add a reason for the backport to the commit message.
  Here is [an example](https://github.com/nixos/nixpkgs/commit/5688c39af5a6c5f3d646343443683da880eaefb8) of this.

  > **Warning**
  > Ensure the commits exists on the master branch.
  > In the case of squashed or rebased merges, the commit hash will change and the new commits can be found in the merge message at the bottom of the master pull request.

**Comment by sersorrel** [comment]
do you really care enough about that to make me redo this with two commits saying `xivlauncher: 1.0.3->1.0.4` and `xivlauncher: 1.0.4 -> 1.0.6` instead of one commit saying `xivlauncher: 1.0.3 -> 1.0.6`

I'll do it, when I have the time, but you're delaying the merge of a PR that fixes broken software for the sake of a "nicer" git history on a branch that will become obsolete in less than two months

**Comment by fabianhjr** [comment]
I'm a volunteer and help with some reviews/merges and maintaining some packages; as such my opinions (and code review) is solely mine and there are many other committers, please don't consider this review as authoritative or representing nixos foundation or other commiters.

However, there is an expectation that what committers merge adheres to the contributing guidelines so it is very likely others will request the same during review.

There are two places I know of and have used in the past to request reviewers:

- Matrix channel ( https://app.element.io/#/room/#dev:nixos.org )
- Discourse "PRs ready for review" thread ( https://discourse.nixos.org/t/prs-ready-for-review/3032/2700 )

Here is a recent manual PR example with a similar situation (missing previous backport) made with `git cherry-pick -x`: https://github.com/NixOS/nixpkgs/pull/260143

**Comment by sersorrel** [comment]
done.

**Comment by fabianhjr** [comment]
Result of `nixpkgs-review pr 259467` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>xivlauncher</li>
  </ul>
</details>

**Review by fabianhjr — APPROVED** [review]

**Pull request merged**
