### PR TITLE
python3Packages.ircstates: 0.11.5 -> 0.11.6; python3Packages.ircrobots: 0.3.5 -> 0.3.6

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

New upstream release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 105703` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python39Packages.ircrobots</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>python37Packages.ircrobots</li>
    <li>python37Packages.ircstates</li>
    <li>python38Packages.ircrobots</li>
    <li>python38Packages.ircstates</li>
    <li>python39Packages.ircstates</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/105703
1 package failed to build:
python39Packages.ircrobots

5 packages built:
python37Packages.ircrobots python37Packages.ircstates python38Packages.ircrobots python38Packages.ircstates python39Packages.ircstates
```

**Comment by jonringer** [comment]
waiting for ofborg to finish

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105703` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python38Packages.ircrobots</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>python37Packages.ircrobots</li>
    <li>python37Packages.ircstates</li>
    <li>python38Packages.ircstates</li>
    <li>python39Packages.ircrobots</li>
    <li>python39Packages.ircstates</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105703` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python39Packages.ircrobots</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>python37Packages.ircrobots</li>
    <li>python37Packages.ircstates</li>
    <li>python38Packages.ircrobots</li>
    <li>python38Packages.ircstates</li>
    <li>python39Packages.ircstates</li>
  </ul>
</details>

**Pull request merged**
