### PR TITLE
add missed internal links into haskell.section.md

### PR DESCRIPTION
**Pull request by p-alik**
Little documentation Improvement without any impact.

### CODE REVIEW

**Comment by Infinisil** [comment]
Looking at https://nixos.org/nixpkgs/manual/, it seems that these references work even without this patch

**Comment by p-alik** [comment]
> Looking at https://nixos.org/nixpkgs/manual/, it seems that these references work even without this patch

Could you refer documentation part precisely please.

I stumbled about the issue by reading [haskell.section.md](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/haskell.section.md).

**Review by infinisil — APPROVED** [review]
Oh I didn't check the markdown on GitHub, yeah it doesn't work without this patch there, thanks for the PR!

**Comment by Infinisil** [comment]
Oh but you should change the commit message to have the "haskell docs:" prefix

**Pull request merged**
