### PR TITLE
bazel: 5.2.0 -> 5.3.0

### PR DESCRIPTION
**Pull request by timothyklim**
###### Description of changes

https://github.com/bazelbuild/bazel/releases/tag/5.3.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by uri-canva — CHANGES_REQUESTED** [review]
You need to update the packages that use `buildBazelPackage` with `bazel_5`, see the ofborg failures for examples of what change to look for, you can repro them by running `nix-build -A bazel_5.tests`.

**Comment by timothyklim** [comment]
> you can repro them by running nix-build -A bazel_5.tests

```
INFO: Elapsed time: 22.599s, Critical Path: 18.60s
INFO: 404 processes: 21 internal, 380 linux-sandbox, 3 worker.
INFO: Build completed successfully, 404 total actions
INFO: Build completed successfully, 404 total actions
```

**Comment by uri-canva** [comment]
@ofborg build python3Packages.tensorflow

**Comment by uri-canva** [comment]
@ofborg build python3Packages.jaxlib

**Comment by uri-canva** [comment]
@ofborg build bazel-watcher

**Review by uri-canva — CHANGES_REQUESTED** [review]
Do you have access to a darwin machine to repro / debug this?

**Comment by timothyklim** [comment]
> Do you have access to a darwin machine to repro / debug this?

I have only x86_64-linux.

**Comment by uri-canva** [comment]
Ok. I might come back to this after https://github.com/NixOS/nixpkgs/pull/186106 is merged, can you add back the other bazel maintainers? Someone else might be able to help.

**Comment by uri-canva** [comment]
Actually let me add them.

**Comment by timothyklim** [comment]
@ofborg build python3Packages.jaxlib

**Pull request closed without merging**
