### PR TITLE
CD/DVD writing improvements

### PR DESCRIPTION
**Pull request by abbradar**
###### Things done
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Right now we have several packages depend on cdrtools and others depend on cdrkit. Both have their advantages and disadvantages: cdrtools are newer and maintained but have [possible licensing problems](https://en.wikipedia.org/wiki/Cdrtools#License_compatibility_controversy), so they and all packages using them are not built on Hydra. Meanwhile cdrkit is not maintained for 5 years but free fork of cdrtools -- it can be freely built but has bugs and problems that are not fixed.

Because all software using them have support for both packages and search for them in `PATH` I propose to defer choice to the user instead. This way Brasero and dvd-slideshow are built on Hydra and K3B doesn't force to use cdrkit. Notice that this is a breaking change: user is expected to add either cdrtools or cdrkit to his `environmentPackages`. I've noted that in the release notes.

### CODE REVIEW

**Comment by abbradar** [comment]
Notice that we can also use `libburn` but I'm not sure how much does it differ from aforementioned two.

**Comment by copumpkin** [comment]
Ugh, do we really want to add more "contextual" stuff via `systemPackages`? I'd rather we build the underlying tool in an agnostic manner, then wrap it with something that provides either `cdrtools` or `cdrkit` based on the user's choice.

**Comment by abbradar** [comment]
Hm, indeed, we can do this. I'll also investigate `libburn` more...

**Comment by abbradar** [comment]
Update: unfortunately, `libburn` is not a full replacement because it lacks tools to make CD images. Even when paired with `cdrkit` there's still no `cdda2wav`, so one may want to choose `cdrtools` instead. I'll try the wrapper approach.

**Comment by abbradar** [comment]
Ok, this is v2:

1. Add `libburn` and `libisofs` and use them for burning operations in `brasero`.
2. Relax restrictions on `cdrtools` (according to Wikipedia, building from source is widely accepted as legal).
3. Move dependency on `cdrtools` inside a wrapper for `k3b` and `brasero`.

`dvd-slideshow` doesn't support `cdrkit`, so I left it out (it's a Bash script anyway, so no long building times).

**Pull request merged**
