### PR TITLE
sourcehut.dispatchsrht: remove

### PR DESCRIPTION
**Pull request by winterqt**
###### Description of changes

dispatch has been deprecated since August (see https://sourcehut.org/blog/2022-08-01-dispatch-deprecation-plans/).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ju1m — APPROVED** [review]
LGTM, thanks!

**Comment by winterqt** [comment]
I added a changelog entry, as well as changed the wording on the removal messages. It used to say See <sourcehut blog post> for more information and alternatives," but we currently don't package those alternatives. Given this, I think it's better to just say "for more information," rather than mention something we don't provide.

@ju1m, thoughts?

**Review by tomberek — APPROVED** [review]

**Review by RaitoBezarius — APPROVED** [review]

**Comment by winterqt** [comment]
Oops, forgot to merge before 22.11...

**Comment by RaitoBezarius** [comment]
> Oops, forgot to merge before 22.11...

And forgot to ask you for changing the release notes to 23.05... :D

**Comment by RaitoBezarius** [comment]
@winterqt Too late to backport IMHO, could you do a PR to move the release notes on that? Apologies for the early merge.

**Comment by winterqt** [comment]
If you do it, it will be quicker -- I don't have time right now.

**Pull request merged**
