### PR TITLE
treewide: remove gnidorah

### PR DESCRIPTION
**Pull request by SuperSandro2000**
due to github account removal/deletion and not other mean of contact.

If anyone knows an updated email or something else please let me know and we update the maintainers entry instead which I would really prefer.

###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/121109#pullrequestreview-647820186

### CODE REVIEW

**Comment by OPNA2608** [comment]
Missed `pkgs/development/libraries/gtk-engine-bluecurve` & `pkgs/applications/audio/uade123`.

**Comment by samueldr** [comment]
Given an arbitrary issue (https://github.com/NixOS/nixpkgs/pull/67448) shows them as @ghost, we can assume it's not a case of this happening to them without them having a say in it.

**Comment by SuperSandro2000** [comment]
> Given an arbitrary issue (#67448) shows them as @ghost, we can assume it's not a case of this happening to them without them having a say in it.

GitHub changed their API and I cannot find this information anymore.

**Comment by SuperSandro2000** [comment]
> pkgs/development/libraries/gtk-engine-bluecurve

Thanks! My sed did not cover lib.maintainers.

**Pull request merged**
