### PR TITLE
certbot: 0.6.0 -> 0.9.3

### PR DESCRIPTION
**Pull request by phunehehe**
###### Motivation for this change

Because new stuff :)

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by fpletz — CHANGES_REQUESTED** [review]
This breaks simp_le, see https://travis-ci.org/NixOS/nixpkgs/jobs/184230379#L3181.

Could you test simp_le with the new certbot/acme version? You would need to patch the `requirements.txt` to allow certbot 0.9.x.

**Comment by phunehehe** [comment]
It may be a bit premature to say this, but the fact that simp_le seems unmaintained is partly the reason I'm moving to certbot.

To fix this build I think the best way is to switch to a better maintained fork https://github.com/zenhack/simp_le. I just pushed a commit that does this. The package builds, but I'll leave the testing to some real user.

**Comment by Mic92** [comment]
@phunehehe I think you can remove your last commit again.

**Comment by Mic92** [comment]
Thanks!

**Pull request closed without merging**
