### PR TITLE
tracker: patch failing test due to float comparison

### LINKED ISSUE #141728: tracker fails to build on some systems (test failure)
### Describe the bug
Not sure if this needs to be reported or going to be caught by automation anyway. Still, trying to install steam from unstable repo fails.

### Steps To Reproduce
1. Try to install steam from unstable
2. ...
3. ...

### Additional context
```
Summary of Failures:

24/33 tracker:resource / resource                     FAIL             0.21s   killed by signal 6 SIGABRT


Ok:                 32
Expected Fail:      0
Fail:               1
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to /build/tracker-3.2.0/build/meson-logs/testlog.txt
checking for XNESTMODULES... yes
checking whether to build Xnest DDX... yes
checking whether to build Xorg DDX... yes
builder for '/nix/store/d67j41d88js80c6rvk7d6fpap7ilmczd-tracker-3.2.0.drv' failed with exit code 1
cannot build derivation '/nix/store/yw942n07506d9gfkcxc2j0mz83i15j39-gtk+3-3.24.30.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vh65pnvg2h1rv5gcm6kbrk0y4cwbvv77-steam-usr-multi.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xv3xrn6fs6w2pyds8dh9hvwcp8vs2sg2-steam-fhs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1ivxvf5svrz2k27bgcrz0a5k1hfiwm3d-steam.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2g1vib9a53hlx3vn5qkgnlpm8c9mpvp5-steam.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s2zcwshs4qp1hww01y1bawi4g90q9vk1-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wjdgskrscg0s6cxz9lc1p3lrnbpzial7-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/wjdgskrscg0s6cxz9lc1p3lrnbpzial7-home-manager-generation.drv' failed
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13-zen1, NixOS, 21.05.3787.564cb4d81d4 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3787.564cb4d81d4"`
 - channels(gurkan): `"home-manager-21.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Motivation for this change

Fixes #141728, https://github.com/NixOS/nixpkgs/pull/140828#issuecomment-940979595, https://github.com/NixOS/nixpkgs/pull/139144#issuecomment-942945303, https://github.com/NixOS/nixpkgs/pull/139144#issuecomment-944068254

Tested building `tracker` locally successfully.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — COMMENTED** [review]
Could you also please try to upstream the patch?

**Comment by fabianhjr** [comment]
Upstreamed: https://gitlab.gnome.org/GNOME/tracker/-/merge_requests/469

Using fetchpatch instead of commiting a patch directly

**Review by chvp — APPROVED** [review]
This allowed me to update my system and the application that (transitively) depended on it (steam) runs without problems.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 141796` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>steam</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
Could you please also switch the target branch to master?

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
