### PR TITLE
{buildRustPackage,fetchCargoTarball,fetchCargoVendor}: respect cargoRoot

### PR DESCRIPTION
**Pull request by TomaSajt**
This PR adds `cargoRoot` support to `fetchCargoTarball` and `fetchCargoVendor` and modifies `buildRustPackage` to also pass `cargoRoot` to its fetcher.

---

`cargoRoot` was added as a way to have `cargoSetupHook` be run inside a specific directory, when `sourceRoot` wasn't enough. (e.g. when the rust code was in a subdirectory, but the main build is not started from inside that).

This support, however, was not extended to the FOD based fetchers: `fetchCargoTarball` and `fetchCargoVendor`

ATM we have to do
```nix
cargoDeps = rustPlatform.fetchCargoTarball {
  sourceRoot = "${src.name}/${cargoRoot}"
}
```
for `fetchCargoTarball` to find the `Cargo.lock` file.

Unfortunately, adding `cargoRoot` to the args passed to `buildRustPackage` doesn't forward any information to the fetcher.

This was mostly fine, since `buildRustPackage` almost never needed `cargoRoot`, and the workaround mentioned above works fine for non-`buildRustPackage` cases.

---

However, after the introduction of the `cargo-tauri.hook` -- which was supposed to work fine alongside `buildRustPackage`, overriding `cargoBuildHook` behaviour -- `cargoRoot` started becoming required to build those packages.

This was not really an issue, since most tauri apps used `cargoLock.lockFile` and a vendored `Cargo.lock` file, because tauri apps very often use git dependencies. This meant that `cargoRoot` was never required to be set.

Now that `fetchCargoVendor` is a thing, which actually works with git dependencies, this PR starts becoming more relevant than before.

---

PR where originally I encountered this issue: https://github.com/NixOS/nixpkgs/pull/348901 (rare occurence of not needing to use `cargoLock.lockfile`)

---

You might say that when using `cargo-tauri.hook` we should just manually use `cargoSetupHook` and leave `buildRustPackage` alone, which is fair.
But the fetcher should at least have a proper way to support `cargoRoot`. This way you could just to `inherit pname version src cargoRoot;` inside `fetchCargoTarball`, instead of doing the weird `sourceRoot` method

---

In this PR I have 3 commits:
1. the actual functionality change.
2. `cargo-tauri.hook` based package working fine with `fetchCargoTarball` backend
3. `cargo-tauri.hook` based package working fine with `fetchCargoVendor` backend

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nyabinary** [comment]
Need this for the build from src Dorion pr :3

**Comment by TomaSajt** [comment]
In the meantime, you can resort to just using mkDerivation with manually specifying cargoDeps and using the rust setup hook.
See mouse-actions-gui for an example.

**Comment by pluiedev** [comment]
Would love this to be merged ASAP — it's really starting to become a problem for virtually all Tauri apps

**Comment by TomaSajt** [comment]
You should have been able to do `depsExtraArgs = { sourceRoot = "${src.name}/${cargoRoot}"; }` as an alternative.
However I made a mistake and it doesn't work currently.
See https://github.com/NixOS/nixpkgs/pull/359211

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
