### PR TITLE
treewide: fetch sage patches from github instead of now-defunct trac

### LINKED ISSUE #252930: Build failure: rubiks
### Steps To Reproduce

1. build rubiks

### Build log

```
building '/nix/store/bb6ai7mn37881im72lr2xhgk576f1yaa-dietz-cu2-Makefile.patch?id=07d6c37d18811e2b377a9689790a7c5e24da16ba.drv'...

trying https://git.sagemath.org/sage.git/plain/build/pkgs/rubiks/patches/dietz-cu2-Makefile.patch?id=07d6c37d18811e2b377a9689790a7c5e24da16ba
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  9115    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download dietz-cu2-Makefile.patch?id=07d6c37d18811e2b377a9689790a7c5e24da16ba from any mirror
```

### Additional context

Since all these URLs on `git.sagemath.org` seem to fail, I changed them to corresponding `raw.githubusercontent.com` URLs: https://github.com/zeuner/nixpkgs/tree/rubiks-download-fix . However, this leads to a hash mismatch:

```
trying https://raw.githubusercontent.com/sagemath/sage/develop/build/pkgs/rubiks/patches/dietz-cu2-Makefile.patch?id=07d6c37d18811e2b377a9689790a7c5e24da16ba
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1059  100  1059    0     0   3845      0 --:--:-- --:--:-- --:--:--  3850
error: hash mismatch in fixed-output derivation '/nix/store/a6xxf5q9bh1xfhq2jk8izd14f5xw0mam-dietz-cu2-Makefile.patch?id=07d6c37d18811e2b377a9689790a7c5e24da16ba.drv':
         specified: sha256-uOKUWM6P/krhalRJdyFplN4Y2wpK0R9Sw5LgNGvgw+c=
            got:    sha256-bRU7MJ/6BgCp2PUqZOragJhm38Q3E8ShStXQIYwIjvw=
```

Unfortunately, I don't have the previous patch available, so I can't check what change leads to the hash mismatch. This one particular patch doesn't look unreasonable. I don't know how to update the hash entry, though, because it does not follow the `sha-256-` notation: https://github.com/zeuner/nixpkgs/commit/0ca86d970642a81cfeb9b3d19e944861c4abb8f5#diff-fd1b8a8025457c6f8c2fc29431ea1e4fc177a47d5ab85fc5c63bd198ff04a430L32

### Notify maintainers

@timokau @omasanori @raskin @collares 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-78-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by collares**
## Description of changes

Sage's Trac instance is no longer accessible, so this PR fetches relevant patches from Sage's GitHub repository instead as suggested in #252930. I've verified that all hashes match.

Fixes #252930. cc @zeuner

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
(we don't auto-strip `?…` from file names in fetches, which is why there are rebuilds)

**Review by omasanori — APPROVED** [review]

**Comment by omasanori** [comment]
Do we need backports?

**Comment by collares** [comment]
Good idea. I think the files are cached by Hydra, but it doesn't hurt.

**Comment by collares** [comment]
Thanks for the review!

**Pull request merged**
