### PR TITLE
qbittorrent: add aarch64-darwin and x86_64-darwin to platforms

### PR DESCRIPTION
**Pull request by willemml**
###### Description of changes

Adds a Darwin target for the qBittorrent app (binary download from sourceforge).

Unsure if I should also update the version to 4.5.0 from 4.4.5, and if I should do so in a separate PR or another commit in this one (also if in this PR what should the title be?)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by farcaller** [comment]
I'm curious, shouldn't it effectively be qbittorent-bin at this point?

**Comment by willemml** [comment]
I'm not sure, I thought that creating a separate package for the same software was a bit overkill. But I could create a new package if necessary. I did briefly attempt to get compilation working on mac.

**Comment by farcaller** [comment]
Result of `nixpkgs-review pr 209197` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>qbittorrent (qbittorrent-nox)</li>
  </ul>
</details>

**Review by farcaller — APPROVED** [review]
Does work as intended, but I can't comment on if this is how the package should look.

**Review by wegank — CHANGES_REQUESTED** [review]
I think this package can be built from source on macOS: #209224

Meanwhile, it looks good to add a qbittorrent-bin on macOS. The main reason is that Qt 6 on macOS is in a very immature state (no support for qmake in sandbox, for example), so qBittorrent might not build on darwin after the transition to Qt 6.

**Pull request closed without merging**
