### PR TITLE
libsForQt5.qtstyleplugin-kvantum: add xdg dirs support

### LINKED ISSUE #82769: 3rd party Kvantum themes not selectable
**Describe the bug**
Besides the included themes, Kvantum manager is does not allow the user to select other themes installed from packages like `arc-kde-theme` or `adapta-kde-theme`.

--

**To Reproduce**
1. Install `libsForQt5.qtstyleplugin-kvantum`
2. Install `arc-kde-theme`
3. Open Kvantum manager and try to select Arc theme

**Expected behavior**
Being able to select an installed theme.

**Screenshots**
As you can see the themes Adapta and AdaptaNokto do not appear in the drop down menu, even though they are installed in the correct folder. 

image

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 19.09.2199.d1918bb0d90 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by romildo**
###### Description of changes

Add support to xdg dirs.

Fixes https://github.com/NixOS/nixpkgs/issues/82769

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sagikazarmark** [comment]
I'd rather suggest copying the patch here

**Comment by romildo** [comment]
> I'd rather suggest copying the patch here

Done

**Comment by winterqt** [comment]
> I'd rather suggest copying the patch here

@sagikazarmark Why's that, if I may ask? The original patch was at a URL that's very unlikely to change since it's pointed at a specific commit.

**Comment by winterqt** [comment]
> From where did you took it?

It was fetched from a GitHub commit, see [here](https://github.com/NixOS/nixpkgs/commit/5be799f368b4d31629d04d5c45cc9f0449d3cea7#diff-45a7c95054e7807fd5dedb4aefa032d31b68dbc2432dd260bfc3f9e647a1cdc6R30) -- I see no issue with fetching it from there, since it points directly to a commit.

**Comment by SuperSandro2000** [comment]
> It was fetched from a GitHub commit, see [here](https://github.com/NixOS/nixpkgs/commit/5be799f368b4d31629d04d5c45cc9f0449d3cea7#diff-45a7c95054e7807fd5dedb4aefa032d31b68dbc2432dd260bfc3f9e647a1cdc6R30) -- I see no issue with fetching it from there, since it points directly to a commit.

That looks great except please use https://github.com/tsujan/Kvantum/commit/01989083f9ee75a013c2654e760efd0a1dea4a68.patch as the link.

**Comment by sagikazarmark** [comment]
I made this patch to implement the feature for myself, but there are no guarantees it will ever make it upstream.

I also suggested the author of Kvantum to make some refactors first to make changes like this easier.

Long story short: there are no guarantees that this patch will be forward compatible.

**Comment by SuperSandro2000** [comment]
thats fine. If it breaks then we need to drop it or update it.

**Pull request merged**
