### PR TITLE
pkgsStatic.aws-c-cal: Fix dlopen assertion

### PR DESCRIPTION
**Pull request by tobim**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
the patch: https://github.com/awslabs/aws-c-cal/commit/ee46efc3dd0cf300ff4ec89cc2d79f1b0fe1c8cb.patch

is not correct. all the added `assert_fatal(!module && xxx)` seem to have the logic reversed and causes the eval tests to [fail](https://gist.github.com/GrahamcOfBorg/b77d7728b7a3982c08c1259f240fd5a8)
```
Fatal error condition occurred in /build/source/source/unix/openssl_platform_init.c:145: !module && "Cannot read process symbols and libcrypto 1.0.2 HMAC symbols not found"
Exiting Application
################################################################################
Stack trace:
################################################################################
/nix/store/ma7qxgrx9k5r8z9kpb8k80nvd0dkjngq-aws-c-common-0.9.10/lib/libaws-c-common.so.1(aws_backtrace_print+0x5d) [0x7ffff796317d]
/nix/store/ma7qxgrx9k5r8z9kpb8k80nvd0dkjngq-aws-c-common-0.9.10/lib/libaws-c-common.so.1(aws_fatal_assert+0x49) [0x7ffff794dcc9]
/nix/store/495in53iscywh03fr5xybzwpqn1v4a1x-aws-c-cal-0.6.10/lib/libaws-c-cal.so.1.0.0(+0xaed5) [0x7ffff79afed5]
/nix/store/495in53iscywh03fr5xybzwpqn1v4a1x-aws-c-cal-0.6.10/lib/libaws-c-cal.so.1.0.0(+0xb430) [0x7ffff79b0430]
/nix/store/495in53iscywh03fr5xybzwpqn1v4a1x-aws-c-cal-0.6.10/lib/libaws-c-cal.so.1.0.0(+0xb505) [0x7ffff79b0505]
/nix/store/495in53iscywh03fr5xybzwpqn1v4a1x-aws-c-cal-0.6.10/lib/libaws-c-cal.so.1.0.0(aws_cal_library_init+0x39) [0x7ffff79ab9e9]
/nix/store/pn9javcjwbf295flzcj9jb9h3fnaq2w5-aws-c-io-0.13.36/lib/libaws-c-io.so.1.0.0(aws_io_library_init+0x28) [0x7ffff7af6c98]
/nix/store/rf2shlbbyq0rkw475hfnxyrvq738ad6k-aws-c-mqtt-0.9.10/lib/libaws-c-mqtt.so.1.0.0(aws_mqtt_library_init+0x20) [0x7ffff7c25f10]
/nix/store/kak1m3w6hlv6kwb5vahx541hphvn6l83-aws-crt-cpp-0.24.7/lib/libaws-crt-cpp.so(_ZN3Aws3Crt9ApiHandleC1EP13aws_allocator+0x2c) [0x7ffff7ca4e4c]
/build/source/build/src/aws-cpp-sdk-core/libaws-cpp-sdk-core.so(_ZN3Aws13InitializeCrtEv+0x2d) [0x7ffff7ec373d]
/build/source/build/src/aws-cpp-sdk-core/libaws-cpp-sdk-core.so(_ZN3Aws7InitAPIERKNS_10SDKOptionsE+0x105) [0x7ffff7ec16b5]
/build/source/build/tests/testing-resources/libtesting-resources.so(_ZN7testing9TestSuite3RunEv+0x91) [0x7ffff7f9fb11]
/build/source/build/tests/testing-resources/libtesting-resources.so(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x3e7) [0x7ffff7fa6f07]
/build/source/build/tests/testing-resources/libtesting-resources.so(_ZN7testing8UnitTest3RunEv+0x6b) [0x7ffff7f8bd4b]
/build/source/build/tests/aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests() [0x42d556]
/nix/store/2614203agy7mdbh4bc5mj0q6mvjwkrwp-glibc-2.38-44/lib/libc.so.6(+0x280ce) [0x7ffff6e3f0ce]
/nix/store/2614203agy7mdbh4bc5mj0q6mvjwkrwp-glibc-2.38-44/lib/libc.so.6(__libc_start_main+0x89) [0x7ffff6e3f189]
/build/source/build/tests/aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests() [0x44bb45]
Subprocess aborted
```

**Comment by tobim** [comment]
Thank you for the rigor! I'll run some tests with the `!` removed and update the PR if they pass.

**Comment by tobim** [comment]
As it turns out the new assertions are simply wrong. The `module` pointer should not be `NULL` if the library is a `.so`, but will be if it is. I just removed the assertions from the patch, this might result in worse abort messages, but will be easier to maintain.

**Review by ghost — APPROVED** [review]
LGTM

**Comment by a-n-n-a-l-e-e** [comment]
though -- if you only add the patch for static builds you can avoid going into staging.

**Comment by a-n-n-a-l-e-e** [comment]
@ofborg build aws-c-cal aws-c-cal.passthru.tests

**Comment by tobim** [comment]
> though -- if you only add the patch for static builds you can avoid going into staging.

I prefer using consistent sources.

**Pull request merged**
