### PR TITLE
Libmsgpack gcc7 fixes

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
These versions are not referenced anywhere in the tree and are broken with `gcc-7` (see tracking issue https://github.com/NixOS/nixpkgs/issues/31747)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
On a brief look, 2.1 seems compatible with 2.0 and not that far from compatibility with 1.4.

**Comment by adisbladis** [comment]
CCing maintainers @redbaron and @wkennington

**Comment by vcunat** [comment]
@peterhoeg: any particular reason why you kept 2.0 in #30318?

**Review by orivej — APPROVED** [review]

**Comment by peterhoeg** [comment]
*something* needed it (broke with 2.1) but it would obviously have been helpful for everyone if I had actually changed whatever derivation(s) that required it. Let me check on this.

**Comment by peterhoeg** [comment]
Everything seems to build with the default msgpack 2.1.5 so I guess we can blow away 2.0

**Pull request merged**
