### PR TITLE
buildGo{Module,Package} packages: remove enableParallelBuilding = true

### PR DESCRIPTION
**Pull request by zowoq**
`enableParallelBuilding` defaults to true.

https://github.com/NixOS/nixpkgs/blob/725c15436910c1f1c52fa79aa2816453b1b9b6ed/pkgs/development/go-modules/generic/default.nix#L29-L30

https://github.com/NixOS/nixpkgs/blob/725c15436910c1f1c52fa79aa2816453b1b9b6ed/pkgs/development/go-packages/generic/default.nix#L10-L11

### CODE REVIEW

**Comment by zowoq** [comment]
Do we even need a `enableParallelBuilding` option for `buildGo{Module,Package}?

**Review by ghost — APPROVED** [review]
LGTM

**Review by Mic92 — APPROVED** [review]

**Comment by Mic92** [comment]
> Do we even need a `enableParallelBuilding` option for `buildGo{Module,Package}`?

It does not have an effect, but maybe it should: https://github.com/NixOS/nixpkgs/issues/95595

**Comment by zowoq** [comment]
Opened a PR #95657

**Pull request merged**
