### PR TITLE
gnomeExtensions.pop-shell: unstable-2023-04-27 -> unstable-2023-11-10

### LINKED ISSUE #269687: Update request: gnomeExtensions.pop-shell unstable-2023-04-27 → unstable-2023-11-10
- Package name: gnome-shell-extension-pop-shell
- Latest released version: unstable-2023-11-10

- Current version on the unstable channel: unstable-2023-04-27
- Current version on the stable/release channel: unstable-2023-04-27

This brings about Gnome 45 support, as far as I know.

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@genofire 

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dawidd6**
## Description of changes

Closes: https://github.com/NixOS/nixpkgs/issues/269687

image

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Henry-Hiles** [comment]
Even with this PR, i still get this on GNOME 45:
image

**Comment by jtojnar** [comment]
The metadata is [up to date](https://github.com/pop-os/shell/blob/aafc9458a47a68c396933c637de00421f5198a2a/metadata.json). How did you install it? Make sure to re-log in.

**Comment by Henry-Hiles** [comment]
I installed it by adding this to my packages: `inputs.pop-shell.legacyPackages.${system}.gnomeExtensions.pop-shell`, where the pop-shell input is "github:dawidd6/nixpkgs?branch=pop-shell-bump". I did relog, yes.

**Comment by dawidd6** [comment]
I've tested it in a VM built from this PR branch, running on Wayland and it loaded successfully.

**Pull request merged**
