### PR TITLE
beets: 1.3.16 -> 1.3.17

### PR DESCRIPTION
**Pull request by Profpatsch**
one test fails, see the source comment

### CODE REVIEW

**Comment by aszlig** [comment]
I'd rather just skip the test that fails instead of disabling tests altogether.

**Comment by Profpatsch** [comment]
I tried, it looked like the tests are called from a file called `alltests.py`, which is skipped somehow. Anyhow, no other test is failing.

**Comment by aszlig** [comment]
After investigating this a bit more, the reason why this fails is that we *already* disabled the completion tests in 2acc258dff1a37974edd6475851e218bb09e281a but they were enabled again because beetbox/beets@a07cb837aa3257e1e7b6b0265e468b5fa3587df4 moved the test_completion.sh file into another place, so `echo echo completion tests passed > test/test_completion.sh` won't work here.

**Comment by Profpatsch** [comment]
See also https://github.com/beetbox/beets/issues/1876

**Comment by aszlig** [comment]
@Profpatsch: I know, but it's not an upstream issue.

**Comment by aszlig** [comment]
Even though the `bash` completion tests were re-enabled by accident here, it really seems to have been an upstream issue in the first place, see [my comment](https://github.com/beetbox/beets/issues/1876#issuecomment-182186955) on the upstream issue.

**Pull request merged**
