### PR TITLE
Ldc 1.29.0

### PR DESCRIPTION
**Pull request by Panke**
###### Description of changes

https://github.com/ldc-developers/ldc/releases/tag/v1.29.0

###### Things done

- Built on platform(s)
  - [✔] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [✔] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by applePrincess** [comment]
Result of `nixpkgs-review pr 170910` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>Literate</li>
    <li>btdu</li>
    <li>cheesecutter</li>
    <li>dmd</li>
    <li>dtools</li>
    <li>dub</li>
    <li>gtkd</li>
    <li>ldc</li>
    <li>onedrive</li>
    <li>rund</li>
    <li>sambamba</li>
    <li>tilix</li>
  </ul>
</details>

**Comment by applePrincess** [comment]
Seems like failing on x86-64-darwin but other than that it looks fine to me.

**Comment by Panke** [comment]
> Seems like failing on x86-64-darwin but other than that it looks fine to me.

dmd has the same problem, but I do not have a darwin box.

**Comment by applePrincess** [comment]
Ah this PR updates dmd and ldc that's why. Could we do this PR without dmd update or this PR is taking over the other PR #170903 ? From the error log, ldc itself should be fine.

**Comment by lionello** [comment]
> > Seems like failing on x86-64-darwin but other than that it looks fine to me.
> 
> dmd has the same problem, but I do not have a darwin box.

@Panke Indeed, LDC from this branch builds fine on my aarch64-darwin.

**Comment by Panke** [comment]
I'll rebase this to not include dmd

**Comment by applePrincess** [comment]
Result of `nixpkgs-review pr 170910` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ldc</li>
  </ul>
</details>

**Review by lionello — APPROVED** [review]

**Pull request closed without merging**
