### PR TITLE
python3Packages.pipx: 0.16.2.1 -> 0.16.3

### PR DESCRIPTION
**Pull request by yshym**
###### Motivation for this change

Update to the latest version: https://github.com/pypa/pipx/releases/tag/0.16.3

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125824` at 8476d408 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/a609995ab639472ee2704a50684bb1a0">python38Packages.pipx</a></li>
    <li><a href="https://gist.github.com/0e3030cbc97f80a46c95f293ae6cad6c">python39Packages.pipx</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by yevhenshymotiuk** [comment]
Hmm...
<details>
<summary>nixpkgs-review pr 125824</summary>

``` shell
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/125824/head:refs/nixpkgs-review/1
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 21 (delta 6), reused 6 (delta 4), pack-reused 4
Unpacking objects: 100% (21/21), 220.62 KiB | 1.61 MiB/s, done.
From https://github.com/NixOS/nixpkgs
   157aee00a5b..e5a5056b646  master     -> refs/nixpkgs-review/0
$ git worktree add /Users/yevhenshymotiuk/.cache/nixpkgs-review/pr-125824-1/nixpkgs e5a5056b6461f0696f8c2e53cf7229d12a0a6959
Preparing worktree (detached HEAD e5a5056b646)
Updating files: 100% (26377/26377), done.
HEAD is now at e5a5056b646 gixy: works on darwin platform too (#125713)
$ git merge --no-commit --no-ff 8476d40851da8e216a41379f0ad9d4d53ca77c8c
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going -f /Users/yevhenshymotiuk/.cache/nixpkgs-review/pr-125824-1/build.nix
waiting for locks or build slots...
building '/nix/store/zl1rwmsjybva65a6j4bz42hifp66gywk-python3.9-pipx-0.16.3.drv'...
building '/nix/store/s9fhnj1y2v8aslm8vm4rzwjjq0pirchi-review-shell.drv'...

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/125824

2 packages built:
python38Packages.pipx python39Packages.pipx
```

</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 125824` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>python38Packages.pipx: <a href="https://termbin.com/3rwb">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/26186d709dcb870e43ebe3ff012ac435/raw/index.html">pretty log </a></li>
<li>python39Packages.pipx: log was empty</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> Hmm...
> 
> `nixpkgs-review pr 125824`
> ```shell
> $ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/125824/head:refs/nixpkgs-review/1
> remote: Enumerating objects: 21, done.
> remote: Counting objects: 100% (17/17), done.
> remote: Compressing objects: 100% (12/12), done.
> remote: Total 21 (delta 6), reused 6 (delta 4), pack-reused 4
> Unpacking objects: 100% (21/21), 220.62 KiB | 1.61 MiB/s, done.
> From https://github.com/NixOS/nixpkgs
>    157aee00a5b..e5a5056b646  master     -> refs/nixpkgs-review/0
> $ git worktree add /Users/yevhenshymotiuk/.cache/nixpkgs-review/pr-125824-1/nixpkgs e5a5056b6461f0696f8c2e53cf7229d12a0a6959
> Preparing worktree (detached HEAD e5a5056b646)
> Updating files: 100% (26377/26377), done.
> HEAD is now at e5a5056b646 gixy: works on darwin platform too (#125713)
> $ git merge --no-commit --no-ff 8476d40851da8e216a41379f0ad9d4d53ca77c8c
> Automatic merge went well; stopped before committing as requested
> $ nix --experimental-features nix-command build --no-link --keep-going -f /Users/yevhenshymotiuk/.cache/nixpkgs-review/pr-125824-1/build.nix
> waiting for locks or build slots...
> building '/nix/store/zl1rwmsjybva65a6j4bz42hifp66gywk-python3.9-pipx-0.16.3.drv'...
> building '/nix/store/s9fhnj1y2v8aslm8vm4rzwjjq0pirchi-review-shell.drv'...
> 
> Link to currently reviewing PR:
> https://github.com/NixOS/nixpkgs/pull/125824
> 
> 2 packages built:
> python38Packages.pipx python39Packages.pipx
> ```

Did you build with sandbox enabled?

**Comment by yevhenshymotiuk** [comment]
Doesn't `nixpkgs-review` use sandbox by default?

**Comment by SuperSandro2000** [comment]
> Doesn't `nixpkgs-review` use sandbox by default?

If you are not on darwin it does.

**Pull request merged**
