### PR TITLE
http-parser: fix copying outputs for static build

### PR DESCRIPTION
**Pull request by Strum355**
## Description of changes

Fixes derivation for http-parser in a static env to `install` the static archive to `$out/lib`, based on the [following issue](https://github.com/nodejs/http-parser/issues/310) and [non-upstreamed nix solution](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@87ce692fe5a4e6a371a38f0d4295abf0b35a1376/-/blob/dev/nix/p4-fusion.nix?L16-27). 

Currently, `pkgsStatic.http-parser` only results in a shared library in `$out/lib`:
```
$ nix build nixpkgs#legacyPackages.aarch64-linux.pkgsStatic.http-parser
$ ls -l ./result/lib
total 152
lrwxr-xr-x  1 root  nixbld     23  1 Jan  1970 libhttp_parser.so@ -> libhttp_parser.so.2.9.4
lrwxr-xr-x  1 root  nixbld     23  1 Jan  1970 libhttp_parser.so.2.9@ -> libhttp_parser.so.2.9.4
-r-xr-xr-x  1 root  nixbld  76584  1 Jan  1970 libhttp_parser.so.2.9.4*
```

After this change, we only have the static archive file:
```
$ nix build .#pkgsStatic.http-parser
$ ls -l ./result/lib
total 72
-r--r--r--  1 root  wheel  35448  1 Jan  1970 libhttp_parser.a
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by FliegendeWurst — CHANGES_REQUESTED** [review]
This PR should target `staging` since it rebuilds a lot of packages.
Patch itself LGTM.

**Comment by Strum355** [comment]
> This PR should target `staging` since it rebuilds a lot of packages. Patch itself LGTM.

changed base, thx for the info :+1: @FliegendeWurst

**Review by FliegendeWurst — APPROVED** [review]

**Review by Ericson2314 — APPROVED** [review]
I coincidentally did this locally --- I combined with my version to fix conflicts but still give you credit

**Comment by Ericson2314** [comment]
eval lib tests failure is unrelated.

**Pull request merged**
