### PR TITLE
yandex-browser: 22.9.1.1110-1 -> 23.3.1.906-1

### PR DESCRIPTION
**Pull request by ionutnechita**
Description:
 - yandex-browser-beta is updated to: 23.3.1.906-1

Signed-off-by: Ionut Nechita <ionut_n2001@yahoo.com>

###### Description of changes

yandex-browser: 22.9.1.1110-1 -> 23.3.1.906-1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dan4ik605743 — APPROVED** [review]

**Comment by ionutnechita** [comment]
This commit is verified.
I have yandex browser beta installed with latest changes from master branch on my PC.

**Comment by Alizter** [comment]
Result of `nixpkgs-review pr 221047` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>yandex-browser</li>
  </ul>
</details>

**Comment by Alizter** [comment]
It appears to still be marked as broken. Is this still the case?

**Comment by ionutnechita** [comment]
I don't think that's the case. Everything should be fine. Is there anything to change in the nix file?

**Comment by Alizter** [comment]
Perhaps it is because it has a knownVulnerabilities field.

**Comment by ionutnechita** [comment]
We can keep it that way for a while.

**Comment by ionutnechita** [comment]
Hi @dan4ik605743,

It's possible to review and merge this PR?

**Comment by wegank** [comment]
src appears to be 404ed.

**Pull request merged**
