### PR TITLE
nixosTests.pantheon: port to python

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
#72828

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
cc @tfc @marijanp

**Review by jtojnar — APPROVED** [review]
LGTM

**Comment by mmahut** [comment]
@GrahamcOfBorg test pantheon

**Comment by mmahut** [comment]
@GrahamcOfBorg test pantheon

(odd timeout on 64).

**Comment by flokli** [comment]
@worldofpeace I also ran into the same timeouts / 100% cpu usage as described in https://github.com/NixOS/nixpkgs/pull/73190#issuecomment-552614886.

**Comment by worldofpeace** [comment]
@flokli Ah, I guess this is a bug... I've been trying to port the DE tests but its been practically impossible to discern whether there's something wrong in my test script with debug logging or trying the same in the driver.

**Comment by worldofpeace** [comment]
Ok, now using subtest FTW :stars:.

However can't test on ofborg because it'll just timeout rebuilding the kernel.
So holding off on merging until then, I want to be sure this one doesn't timeout like before as we confirmed that on ofborg.

**Comment by jonringer** [comment]
don't forget to squash commits :)

**Comment by flokli** [comment]
This did succeed on my box:
```
5 out of 5 tests succeeded
test script finished in 74.98s
```

**Comment by flokli** [comment]
@GrahamcOfBorg test pantheon

**Comment by flokli** [comment]
Thanks!

**Comment by flokli** [comment]
oh sorry, I forgot to do the squash :-/

**Comment by worldofpeace** [comment]
> oh sorry, I forgot to do the squash :-/

No problem. I was planning on using the squash merge feature for this.
I'll think of it as an extra few commits for descriptiveness :smile:

**Comment by worldofpeace** [comment]
So this test has timed out on hydra on the OCR step matching the bob user's description
* https://hydra.nixos.org/build/107447356

Commented it out in 406efdb9346bc309c4a97d322bb4170a69de0c5e.
Hopefully there's no other issues with OCR, it wasn't a problem in the past.

**Pull request merged**
