### PR TITLE
sddm: use tmpfiles.d to wipe QML cache

### LINKED ISSUE #43241: sddm: cannot login
## Issue description
After [this](https://github.com/NixOS/nixpkgs/pull/42768/commits/dbde7908c6b22f6b4b1ab3056829f47f44207315) got merged, and is in the nixos-unstable channel, I noticed after I rebuilt my system that when sddm starts and I type in my password it just goes black and restarts sddm. Meaning that I can never reach the desktop :(

I could also not find anything useful in the journal.

cc @peterhoeg @bkchr

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Upgrades to plasma/sddm/qt would sometimes make sddm segfault and a fix was attempted in dae260034ca which does not seem to work.

I am not sure if the reason for the previously mentioned commit not working as intended is because the script that is run has insufficient privileges to actually delete the files or other files in the ```.cache``` directory needed to be blown away as well so now we run it using a ```tmpfiles.d``` fragment (which runs as root) and we remove everything under the ```.cache``` directory.

Cc: @ttuegel as author of the original change, @bkchr, @worldofpeace 

Fixes #43241

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by worldofpeace — APPROVED** [review]

**Review by worldofpeace — APPROVED** [review]
Obviously no resistence here.

**Review by bkchr — APPROVED** [review]
I'm still not sure why this is happening, as the upstream bug was closed :( 
But it is nice to finally have a working solution!

**Comment by peterhoeg** [comment]
I'd like @ttuegel to ACK this before merging as he might have some additional insights.

**Comment by jcrben** [comment]
@bkchr if you have the upstream bug link handy I'd like to read it...

**Comment by bkchr** [comment]
@jrcben look into the diff, there is the link to the qtbug.

**Comment by ttuegel** [comment]
This seems fine to me!

> Upgrades to plasma/sddm/qt would sometimes make sddm segfault and a fix was attempted in dae2600 which does not seem to work.

At one time it did work; do we know why it stopped working? My concern is that this may stop working too; that's not a barrier to merging, but it would be nice if we could head off future problems.

**Comment by peterhoeg** [comment]
> At one time it did work; do we know why it stopped working?

I cannot confirm that the original fix ever worked for me. I remember having the issue and trying out a few different things, only having things work when I manually blew away the cache, then running a version of unstable with your commit but still seeing the problem on the next upgrade.

Manually blowing away the cache directory worked every time though.

**Comment by bkchr** [comment]
I had the same experience as @peterhoeg.

**Comment by ttuegel** [comment]
> I cannot confirm that the original fix ever worked for me. I remember having the issue and trying out a few different things, only having things work when I manually blew away the cache, then running a version of unstable with your commit but still seeing the problem on the next upgrade.
> 
> Manually blowing away the cache directory worked every time though.

I'm sorry, I never knew that! It worked on my two machines. Thanks for taking care of this!

**Comment by peterhoeg** [comment]
>   I'm sorry, I never knew that!

Well, I can hardly blame anyone for bugs I don't report... ;-)

**Pull request merged**
