### PR TITLE
sourcehut: fix #198478

### LINKED ISSUE #198478: sourcehut.buildsrht fails to build
### Steps To Reproduce
1. build *nix build github:NixOS/nixpkgs/nixos-unstable#sourcehut.buildsrht*

### Build log
```
error: builder for '/nix/store/3ls5r4wnz7fcq7jxhndd425jw8w7s8r7-python3.10-buildsrht-0.82.8.drv' failed with exit code 1;
       last 10 log lines:
       > Installing collected packages: buildsrht
       > Successfully installed buildsrht-0.82.8
       > /build/source
       > Finished executing pipInstallPhase
       > pythonOutputDistPhase
       > Executing pythonOutputDistPhase
       > Finished executing pythonOutputDistPhase
       > pythonOutputDistPhase
       > Executing pythonOutputDistPhase
       > mv: cannot stat 'dist': No such file or directory
```

### Additional context
Other sourcehut python pkgs fail in a similar manner

### Notify maintainers
@eadwu @tjni 

### Metadata
`nix flake metadata github:NixOS/nixpkgs/nixos-unstable`

```
Resolved URL:  github:NixOS/nixpkgs/nixos-unstable
Locked URL:    github:NixOS/nixpkgs/448a599c49978c2794401bfc3a2e1fba1a8663be
Description:   A collection of packages for the Nix package manager
Path:          /nix/store/hlqsxiwbmbgsp66xdlf5adlzz2y3xmh6-source
Revision:      448a599c49978c2794401bfc3a2e1fba1a8663be
Last modified: 2022-10-28 14:21:31
```

### PR DESCRIPTION
**Pull request by ju1m**
###### Description of changes
- [X] Fix https://github.com/NixOS/nixpkgs/issues/198478 by using `propagatedNativeBuildInputs` instead of manually propagating dependencies, which caused those build problems due to non-idempotent hooks being run twice.
Kudos to @winterqt for making sense of this bug in https://github.com/NixOS/nixpkgs/pull/198586

Side note: beware that there is a NixOS/sourcehut branch which GitHub is selecting by default when opening a new PR from a branch of our own repository also named `sourcehut`, which may cause to include more commits than intended and thus notify automatically and without warning unrelated people en masse...

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by winterqt — APPROVED** [review]
Definitely the better option. I originally thought this wouldn't be feasible due to cross (and prior experience with propagation), but looks like this will work fine based on the documentation.

Nit: would it be a good idea to specify which non-idempotent hook was being ran (`pythonOutputDistHook`), so it's clear in the history why this just started occurring (86ab83260fa002c3a0bab81d5965b6edff376759), or does that not really matter?

**Review by tjni — APPROVED** [review]

**Comment by ju1m** [comment]
- [X] Improve https://github.com/NixOS/nixpkgs/pull/198720/commits/7cc9cd884e1b3b35eb4e7cdd70602e41f80dd932 commit message

**Comment by eadwu** [comment]
I do not know if this is still the case, but from my memory `propagatedNativeBuildInputs` will actually inject those dependencies into your runtime configuration.

If this is still the case you will be indirectly injecting conflicting versions of `sassc` and `node` - `sassc` is not as much of a problem but `node` might be a problem.

**Comment by winterqt** [comment]
> 

Th

> I do not know if this is still the case, but from my memory `propagatedNativeBuildInputs` will actually inject those dependencies into your runtime configuration.
> 
> If this is still the case you will be indirectly injecting conflicting versions of `sassc` and `node` - `sassc` is not as much of a problem but `node` might be a problem.

This would only be at build time, AFAIK, where it's less likely to be a problem.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 198720` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>sourcehut.hubsrht</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pagessrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
  </ul>
</details>

**Comment by winterqt** [comment]
Wonder what's up with hub -- will check later.

**Comment by ju1m** [comment]
@siraben, thanks for that report on `aarch64-darwin`. Could you maybe share the logs to help identify the problem?
Just by looking at `hub.nix` I can only see a difference from other packages, `SRHT_PATH` is not set:
```bash
export SRHT_PATH=${srht}/${python.sitePackages}/srht
```
But if it were required, I currently don't see why it would not also fail on `x86_64`.

**Comment by tjni** [comment]
The error is that `pyyaml` is not found as a dependency, but I don't know why it suddenly started failing because the dependency was added back in https://git.sr.ht/~sircmpwn/hub.sr.ht/refs/0.13.2.

**Comment by ju1m** [comment]
@tjni , hmm, strange that I cannot reproduce on my `x86_64-linux` system.
The `src.sha256` is correct so it's not a caching issue on my side.
Yet you're right `pyyaml` is required by the `setup.py`.
- [X] Add `pyyaml` dependency to `hubsrht`.

**Comment by winterqt** [comment]
This happens because [`werkzeug` only propagates `pyyaml` (through `watchdog`) on non-Darwin systems](https://github.com/NixOS/nixpkgs/blob/741b917812a3fb1ca5db26148b568220d0a5dac4/pkgs/development/python-modules/werkzeug/default.nix#L32-L34), which is where it was getting it from on Linux.

**Comment by tjni** [comment]
Great find, @winterqt. It makes a lot of sense.

**Comment by winterqt** [comment]
Force pushed to fix the commit message to use the attribute name.

```diff
- sourcehut/hubsrht: fix missing pyyaml dependency
+ sourcehut.hubsrht: fix missing pyyaml dependency
```

Waiting on OfBorg...

**Pull request merged**
