### PR TITLE
pytjon.pkgs.wptserve: correctly fix build

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
cc @7c6f434c

**Comment by FRidh** [comment]
cherry-picked to staging-19.03 as well

**Comment by 7c6f434c** [comment]
To be honest, I am a bit surprised `wptserve` survived that bump (but indeed it did). Sorry, was too pessimistic.

**Comment by dotlambda** [comment]
If you want, we can use `fetchFromGitHub` or ask upstream to include the tests in the PyPI tarball in order to add a `checkPhase`.

**Comment by 7c6f434c** [comment]
Well, the only in-tree user is Marionette harness (and the end-to-end process is easy to test), and I fail to understand whether upstream wants just to switch to Rust step by step.

**Pull request merged**
