### PR TITLE
setup.sh: substitute uses only valid bash names

### PR DESCRIPTION
**Pull request by Profpatsch**
bash variable names may only contain alphanumeric ASCII-symbols and _,
and must not start with a number. Nix expression attribute names however
might contain nearly every character (in particular spaces and dashes).

Previously, a substitution that was not a valid bash name would be
expanded to an empty string. This commit introduce a check that throws
a (hopefully) helpful error when a wrong name is used in a substitution.
That was discovered by chexxor when it happened to me in a substitution.

Additionally, substituteAll previously filtered out all environment
variables starting with an uppercase letter. That increased the number
of silently(!) ignored envvars (and nix attributes) even further.
Because it was quite arbitrary, it is removed.

This will trigger a mass rebuild.

### CODE REVIEW

**Comment by vcunat** [comment]
I'm convinced the filtering is meant to reduce the risk of accidental substitution. It's a convention that standard *global* env vars are all-uppercase, and typically you have large amount of those in the env. On the other hand, the main intended purpose of `substituteAll` seems to act on converted nix variables which rarely start with an uppercase character.

**Comment by vcunat** [comment]
The first change seems good to me. It's a bit unfortunate for `subsituteAll` that we prefer to use dashes in nix bindings. For example, I now tested passing a dashed attribute to a derivation and it's just not added to the env silently (or invisible to `bash`).

**Comment by Profpatsch** [comment]
> I'm convinced the filtering is meant to reduce the risk of accidental substitution.

@aszlig brought the same objection. *However* in my opinion the worst an automatic computing system can to is **silently ignore user input**.
So unless you can think of a way to throw an error for these cases I’m in strong favor of risking wrong substitutions.
Even better would be to have a clean namespace for these substitutions in the first place. Maybe that can be done, too.

**Comment by vcunat** [comment]
If we do not change this filtering, we should at least document it in http://nixos.org/nixpkgs/manual/#fun-substituteAll

To me there seems a more pressing "silent" problem: if you forget to put `$var` into env or make a typo somewhere, any `@var@` occurrences just won't be substituted. We might make `substituteAll` check afterwards that no such references have remained.

**Comment by Profpatsch** [comment]
> if you forget to put $var into env or make a typo somewhere, any @var@ occurrences just won't be substituted.
> We might make substituteAll check afterwards that no such references have remained.

How about files where `@something@` is intended to be left as-is? It’s the classic “symbol-space used by multiple layers” problem.

**Comment by vcunat** [comment]
I don't think you should use `substituteAll` in such cases, as anyone can define `$something` for some other reason.

**Comment by Profpatsch** [comment]
@vcunat I added the filter again and included documentation.

The first fallout of the changes is already visible, the documentation travis build is failing. If I did everything right, all of these failures should have been bugs from the get-go, though.

**Comment by vcunat** [comment]
Are you sure about the failures? It seems like stdenv won't even bootstrap.
```
building path(s) ‘/nix/store/r6p6ipkqaf7ivbszwf25nnwf16fvr604-bootstrap-gcc-wrapper’

substitution variables must be valid bash names, "ccLDFlags+" isn't.
```

**Comment by vcunat** [comment]
OMG, the implementation has been crappy all along &ndash; it uses `env` call to get all env variables, but that isn't one-var-per-line if there are multi-line strings in the vars...

**Comment by vcunat** [comment]
Let me properly test a fix for that.

**Comment by vcunat** [comment]
It got to building the final gcc so far, so it's probably OK. @Profpatsch: checkout https://github.com/Profpatsch/nixpkgs/pull/1 ;-)

**Comment by Profpatsch** [comment]
@vcunat I changed it, should we make Travis build everything? :)

**Comment by Profpatsch** [comment]
@vcunat What’s the next steps here? Should we merge into staging?

**Comment by joachifm** [comment]
@Profpatsch sounds like the next logical step

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/commit/62616ec5e211d8cfbafe31c0876a1d8cdab9e98e. Thanks!

**Comment by vcunat** [comment]
I think this PR is what causes that mass-breakage on darwin: http://hydra.nixos.org/build/34945843/nixlog/1/raw I assume the bash used at that point behaves differently, or something similar, as there seem to be no larger problems on the two linux platforms.

**Comment by vcunat** [comment]
Unfortunately, this leaves me in kind-of stuck situation, as I can't well test darwin stuff and I don't like bringing that mass failure to master either...

**Comment by Profpatsch** [comment]
Hm, do you think the `set` does not work the same on darwin bash? That’s nearly all we changed. Maybe someone on Mac can post an output of `set`?

**Comment by Profpatsch** [comment]
And maybe an output of

```bash
for e in $(set); do
  if ! [[ "$varName" =~ ^[a-zA-Z_]+[a-zA-Z0-9_]*$ ]]; then
    echo "$varName"
  fi
done
```

**Comment by aszlig** [comment]
I think using `set` instead of `env` is very dangerous, because it not only shows exported variables but also shell-internal variables. In addition to that it handles different types with different syntax.

What I think is the problem on Darwin is that the contents of a function is recognized as a variable name here. For example if I run `set` within `bash` on my system I get the following along the lines:

```
command_not_found_handle () 
{ 
    local p=/run/current-system/sw/bin/command-not-found;
    if [ -x $p -a -f /nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite ]; then
        $p "$@";
        if [ $? = 126 ]; then
            "$@";
        else
            return 127;
        fi;
    else
        echo "$1: command not found" 1>&2;
        return 127;
    fi
}
```

While `command_not_found_handle` isn't usually set inside `stdenv`, other functions may have been set and whenever there is a line within that function without prior whitespace it might end up getting included in `substitute`.

**Comment by vcunat** [comment]
Aah... thanks for finding this case, Aszlig. Unfortunately, [as noted above](#issuecomment-213781609), `env` instead handles multi-line vars badly which we use heavily (e.g. for phases).

**Comment by vcunat** [comment]
We could force `set` to display only variables:
```
set -o posix
# use set to list vars
set +o posix
```
Any other/better ideas?

**Comment by aszlig** [comment]
@vcunat: We can still use `env -0` and `cut -z` to split off the name from the content.

**Comment by aszlig** [comment]
an example of a var even with a newline:
```shell
while IFS= read -r -d '' var val; do
  echo ",,$var''"
done < <(env $'foo\nbar=blah\nxxx' env -0 | cut -d= -f1 -z)
```

prints along with others the following:
```
,,foo
bar''
```

**Comment by aszlig** [comment]
I don't have time right now to implement this by myself, but the args for the substitution function can be gathered like this:

```bash
args=()
while IFS= read -r -d '' varname; do
  args+=("--subst-var" "$varname")
done < <(env -0 | cut -d= -f1 -z)
```

**Comment by aszlig** [comment]
A small test yields the correct values even with newlines:

```
foo() { for i in "$@"; do echo ">$i<"; done; }
args=()
while IFS= read -r -d '' varname; do
  args+=("--subst-var" "$varname")
done < <(env $'foo\nbar=bar\nfoo' env -0 | cut -d= -f1 -z)
foo "${args[@]}"
```

**Comment by aszlig** [comment]
The problem with `set -o posix` is that it still contains internal variables (but no functions) and they're still printed in bash syntax rather than the raw contents, which `env -0` provides.

**Comment by vcunat** [comment]
> @vcunat: We can still use `env -0` and `cut -z` to split off the name from the content.

Nice idea! I expect to try that properly tomorrow morning.

**Comment by vcunat** [comment]
I think I would filter unusual variable names anyway, probably like this:
```diff
-    # Select all environment variables that start with a lowercase character.
-    # Will not work with nix attribute names (and thus env variables) containing '\n'.
-    for envVar in $(set | sed -e $'s/^\([a-z][^=]*\)=.*/\\1/; t \n d'); do
+    # Select all environment variables that start with a lowercase character
+    # and only contain reasonable characters (see grep below).
+    # We need to be careful due to vars with multi-line contents, etc.
+    for envVar in $(env -0 | cut -z -d= -f1 | grep -z '^[a-z][a-zA-Z0-9_]*$' | tr '\000' ' '); do
```

**Comment by vcunat** [comment]
Stdenv is written in bash, so considering variables that don't have a valid bash varname probably wouldn't be good.

**Comment by Profpatsch** [comment]
@vcunat Err nopenopenope.

This whole PR only *exists* because that f* stupid function silently ignores stuff. That’s the whole point. Everything that is not a bash variable is filtered out at https://github.com/NixOS/nixpkgs/pull/14907/files#diff-7a1764865f30c6cb4c22c2654ebe9a38R412 and leads to an *explicit* crash.

**Comment by vcunat** [comment]
I somehow thought the PR was meant to address the case where those names are passed explicitly and ignored, not `substituteAll`.

**Comment by aszlig** [comment]
No matter what this PR is about, but I think it certainly makes more sense to have this check once rather than twice. So if I didn't miss something, using a bash array variable to enumerate over the env variables is still the safest option, because no matter how "garbled" the variable is, it still gets passed correctly to `substitute`, even with spaces.

However, I **did** miss something, which are variables like `_`, which we probably don't want to be substituted. Unfortunately, having a check against `^[a-zA-Z_]+[a-zA-Z0-9_]*$` *will* substitute the variable (the previous regex in `substituteAll` did only match against `[a-z]`).

**Comment by Profpatsch** [comment]
> which are variables like _, which we probably don't want to be substituted

Why? I’m waiting for the first person losing an hour or two because it doesn’t work.

**Comment by vcunat** [comment]
We really should fix the mass breakage on staging: so what... only filter `^[A-Z]` silently, I suppose?

**Comment by vcunat** [comment]
Or perhaps `^[_A-Z]`.

**Comment by abbradar** [comment]
`^([A-Z]|_$)` maybe?

**Comment by vcunat** [comment]
Why keep `_FOO` when we filter-out `BAR`?

**Comment by abbradar** [comment]
Indeed. I thought of `_foo` cases but I don't even know if they are used by anyone.

**Comment by vcunat** [comment]
I think not in nixpkgs, by reading output of `git grep '@_.*@'`.

**Comment by abbradar** [comment]
Ouch, still sleepy and haven't thought of this regex. I think we should just go with it to fix breakage...

**Comment by Profpatsch** [comment]
Why not revert the commit until we implement it correctly? Fixes breakage and we can find a good solution. :)

**Comment by vcunat** [comment]
I didn't want to undo this whole PR, given that we've invested so much energy into it and it doesn't seem anyone really wants to implement it soonish.

**Comment by vcunat** [comment]
So I opted to make an iteration. We can improve later.

**Comment by Profpatsch** [comment]
Hm, the filtering of `_ab` and `Ab` was sensible from the beginning I think. But we definitely need to document it in the manual.

**Comment by Profpatsch** [comment]
Ah, I already documented uppercase, why did we add underscores as well?

**Comment by vcunat** [comment]
That filtering was there on master already. I thought that underscore-starting variables are considered "hidden", i.e. not to be used normally.

Personally, I think that using the shell `substituteAll` function isn't good, and we should mostly replace it by something less error prone, perhaps improved `pkgs.substituteAll`.

**Comment by Profpatsch** [comment]
There is a „nix“ substituteAll, but it just calls the shell function.

**Comment by vcunat** [comment]
Yes, and I believe we should change that to call `substitute` directly with variable list explicitly passed into shell (by listing the nix-passed bindings).

**Comment by Profpatsch** [comment]
I’m preparing a patch for the manual.

**Comment by vcunat** [comment]
No, darwin again. The bootstrapping shell apparently doesn't support process substitution. http://hydra.nixos.org/build/35382446/nixlog/1/raw @copumpkin: any ideas? It would be nice if we used recent bash even during bootstrapping...

**Comment by aszlig** [comment]
@vcunat: A very ugly way of handling this would be to use something like:

```bash
varNames="$(mktemp)"
env -0 | cut ... > "$varNames"
while IFS= read -r -d '' varName; do
    ...
done < "$varNames"
rm -f "$varNames"
...
```

**Comment by aszlig** [comment]
@vcunat: Another variant with `eval`:

```bash
declare -a args=()
eval "$(env -0 | cut -z -d= -f1 | while IFS= read -r -d '' varName; do
    echo 'args+=("--subst-var" '\'"${varName//\'/\'\\\'\'}"\'')'
done)"
echo "${args[@]}"
```bash

**Comment by aszlig** [comment]
I'd personally prefer the latter... simply because I don't like temporary files :-D

**Comment by vcunat** [comment]
I also dislike temporary files, but the escaping here... I can't really parse it :-)

Hmm, null character can't be used in `$IFS`, but `=` is also disallowed in variable names (on system/C level IIRC), so this should work:
```bash
  local IFS==
  local varNames=$(env -0 | cut -z -d= -f1 | tr '\000' '=')
  for varName in $varNames; do
    args+=("--subst-var" "$varName")
  done
```
\+ the things around, e.g. filtering vars according to the first character, etc.

**Comment by vcunat** [comment]
... except that even `local IFS` will be inherited to the child, but it's easy to override it back to the default.

**Comment by vcunat** [comment]
So, pushed 62fc8859c1. Let's see if darwin's fine this time.

**Comment by vcunat** [comment]
No luck. And this time it even isn't clear to me why the substitutions didn't happen: http://hydra.nixos.org/build/35421166/nixlog/1/raw I suppose we'll have to completely revert all this for now.

**Comment by aszlig** [comment]
@vcunat: Using tr with octal escapes probably could be the problem here.
The escaping boils down to `s/'/'\\''/g` (escapeing `'` in bash) and I think it should work on Darwin as well.
@abbradar or somebody else on Darwin, can you please test whether the following one-liner works?

```bash
env $'new\nline=something' bash -c 'declare -a args=(); eval "$(env -0 | cut -z -d= -f1 | while IFS= read -r -d '\'\'' varName; do echo '\''args+=('\''\'\'\''env: '\''"${varName//\'\''/\'\''\\\'\''\'\''}"\'\'\'')'\''; done)"; for var in "${args[@]}"; do echo "$var"; done'
```

The output should be the current environment variables along with this in between:
```
env: new
line
```

**Comment by abbradar** [comment]
Sadly I'm not on Darwin, but an acquaintance is:
```
bash-3.2$ env $'new\nline=something' bash -c 'declare -a args=(); eval "$(env -0 | cut -z -d= -f1 | while IFS= read -r -d '\'\'' varName; do echo '\''args+=('\''\'\'\''env: '\''"${varName//\'\''/\'\''\\\'\''\'\''}"\'\'\'')'\''; done)"; for var in "${args[@]}"; do echo "$var"; done'
env: illegal option -- 0
usage: env [-i] [name=value ...] [utility [argument ...]]
cut: illegal option -- z
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
```
...

**Comment by vcunat** [comment]
If it's `bash-3*`, we also won't have arrays IIRC.

**Comment by abbradar** [comment]
Hm, indeed. How did it work before? (I suppose that usually we have proper Bash on Darwin, and this... thing... is used only for bootstrapping).

**Comment by vcunat** [comment]
Yes, all tools should be GNU ones, the same versions as on Linux, except that I don't know how exactly bootstrapping is done.

**Comment by abbradar** [comment]
сс @copumpkin I guess. Old code just haven't used Bash arrays. I'm out of ideas at this point again besides to bootstrap Bash on Darwin...

**Comment by abbradar** [comment]
From more reading, Bash 3 doesn't have _associative_ arrays. This, however, doesn't fix crippled `env` and `cut`...

**Comment by abbradar** [comment]
I understand that this is very ugly, but seems like a plausible workaround for now: we can check `$BASH_VERSION` and if it starts from 3, use the old code for `env` (but we can still use arrays and such, so only one line needs to be guarded I guess).

**Comment by vcunat** [comment]
> I suppose we'll have to completely revert all this for now.

OK, so I think I shall push 577fefe1d36. Feel free to find some better way later. Let me reopen as it won't be fully resolved after that commit.

**Comment by vcunat** [comment]
First there was an out-of-disk failure, but after restart we have all Hydra-built stdenvs succeeding again :-)

**Comment by aszlig** [comment]
@abbradar, @vcunat: What's the minimum bash version we should aim for if we want to support Darwin as well?

**Comment by vcunat** [comment]
I don't know, but in this case the largest stumbling block seems that `env` doesn't support `-0` at some point during the bootstrap.

**Comment by aszlig** [comment]
@vcunat: Hm, what about doing that portion in C instead... like this (untested):

```C
#include <stdio.h>

int main(int argc, char **argv, char **envp) {
    char *tmp = NULL;
    fputs("local -a args=(", stdout);
    while (*envp != NULL) {
        if (tmp != NULL) putchar(' ');
        fputs("'--subst-var' '", stdout);
        tmp = *envp++;
        while (*tmp != 0 && *tmp != '=') {
            if (*tmp == '\'')
                fputs("'\\''", stdout);
            else
              putchar(*tmp);
            tmp++;
        }
        putchar('\'');
    }
    puts(")");
    return 0;
}
```

This could then be simply `eval`ed and we directly get out the `args` variable, although it feels a bit like breaking a fly on the wheel :-D

**Comment by aszlig** [comment]
OTOH... what about replacing the whole set of substitute* functions by a single small C program (`substitute` with the same functionality as before and `substitute -i` as an alias for `substituteInPlace` and `substitute -a` as an alias for `substituteAll`)? I mean the functionality is very simple and we don't need to make it ugly to read by even uglier shell workarounds.

**Comment by vcunat** [comment]
Yeah, writing a C utility for all those substitute* functions seems a good longer-term goal. (Github won't allow to reopen this PR anymore.)

**Comment by vcunat** [comment]
Finally we might make it an error when `substituteInPlace` does no changes :-)

**Comment by aszlig** [comment]
@vcunat: Mhm, that might be a good idea for a lot of these `sed` calls as well. But let's first find if there is already something that does what we want before we start writing our own.

**Comment by domenkozar** [comment]
We really need a good DSL like Elm wraps JavaScript, but for Shell. Something simple, but well typed.

**Comment by aszlig** [comment]
http://hpux.connect.org.uk/hppd/hpux/Users/replace-2.24/man.html

**Comment by vcunat** [comment]
If you know a good typed shell-suitable language, please, tell me. (Getting further from the topic, I'm afraid.)

**Comment by eikek** [comment]
Scala with https://github.com/lihaoyi/Ammonite  ;-)

**Comment by Profpatsch** [comment]
lol scala.
Let’s put everything in a JVM and call it Noracle.

**Comment by domenkozar** [comment]
Please, let's move this discussion elsewhere (sorry for bringing it up). Let's focus on the goal of the PR. Thank you!

**Comment by copumpkin** [comment]
I'm getting  a bunch of 

```
building path(s) ‘/nix/store/cx3az6zxzzzyxzrk14bda2x9k6vb8v20-clang-wrapper-3.8.0’
WARNING: substitution variables should be valid bash names,
  "ccLDFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccCFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccLDFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccCFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccLDFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccCFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccLDFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccCFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccLDFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccCFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccLDFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
WARNING: substitution variables should be valid bash names,
  "ccCFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
```

Seemingly from:

```
      ccCFlags+=" -B${cc_solib}/lib"
```

in cc-wrapper.nix.

**Comment by edolstra** [comment]
@copumpkin Seeing the same thing.

**Comment by vcunat** [comment]
Yes, explained in 577fefe1d36.

**Comment by copumpkin** [comment]
@vcunat I'm not sure I understand what's actually happening here. Does that mean someone's trying to pass in a key called `"ccCFlags+"` from the Nix side? Isn't my example above just using the `+=` bash notation?

**Comment by vcunat** [comment]
@copumpkin: it's a false positive. The problem is that the string is in a multi-line variable (a build phase) and `env` separates the listing by newlines. As seen above, I wanted to fix that by using `env -0` but that didn't work out as the parameter wasn't supported early in bootstrap (for Darwin, IIRC).

**Comment by copumpkin** [comment]
Ah yes, if you use /usr/bin/env, we have no control (literally, the OS wouldn't let us overwrite it even if we wanted to) over where that points in Darwin 😦

**Comment by vcunat** [comment]
In this case `env` was just searched on current `$PATH`.

**Comment by copumpkin** [comment]
Hmm, then I'm confused, because we use the usual GNU `coreutils` everywhere inside of Nix:

```
[nix-shell:~]$ uname -a
Darwin truffles 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin

[nix-shell:~]$ env -0 | head -n 1
GHC_DOT_APP=/Applications/ghc-7.10.2.appTERM_PROGRAM=Apple_TerminalSSL_CERT_FILE=/Users/copumpkin/.nix-profile/etc/ca-bundle.crtNIX_CC=/nix/store/gppkhlphb093bq35l4836s378fra84w5-clang-wrapper-3.7.1__sandboxProfile=(allow file-read* (literal "/usr/lib/libncurses.5.4.dylib"))
```

**Comment by vcunat** [comment]
@copumpkin: yes, but it wasn't so at some point during *bootstrapping*, at least according to my comment on 81df035. You can try before that commit yourself.

**Pull request merged**
