### PR TITLE
Fairly complete set of packages for Pure

### PR DESCRIPTION
**Pull request by asppsa**
This updates the set of packages available for [Pure](http://purelang.bitbucket.org/) to be more or less the complete set of "official" packages.  Also, the packages are now available through the `purePackages` attribute and have their own file, instead of being listed in `all-packages.nix`.  I've attempted to mimic the conventions used for other interpreters, so hopefully the rearrange is acceptable.

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
Do you know of any other pure users here? In general the commit looks good to me and I'd be inclined to just merge it if you're the main user of them.

**Comment by asppsa** [comment]
Because of the lack of packages, I don't think there is a big user-base at the moment.  I do know however that [Karn Kallio](mailto:tierpluspluslists@gmail.com) fixed the LLVM dependency back in March (see [here](http://lists.science.uu.nl/pipermail/nix-dev/2015-March/016685.html), but I guess that he/she doesn't use github.

I can post to the mailing list if you think its appropriate.

**Comment by Fuuzetsu** [comment]
I came to same conclusion but thought I'd ask. Posting to the list shouldn't be necessary and if there are any objects, we can just deal with those as they come. It should be pretty uncontroversial.

Travis errors due to how much it has to build but I trust you tried these packages out yourself so I'm merging.

**Comment by asppsa** [comment]
Thanks!  Yep, I tested them.

**Pull request merged**
