### PR TITLE
electron_32: init at 32.1.1, bitwarden-desktop: 2024.8.2 -> 2024.9.0

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Diff: https://github.com/bitwarden/clients/compare/desktop-v2024.8.2...desktop-v2024.9.0

Changelog: https://github.com/bitwarden/clients/releases/tag/desktop-v2024.9.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by amarshall — APPROVED** [review]
Built and tested bitwarden-desktop (after rebasing this onto latest nixos-unstable branch). This included building electron_32 from source successfully on x86_64-linux.

While the other changes look good, my approval should probably not be seen as “enough” for them.

Note also that electron-chromedriver update got merged in https://github.com/NixOS/nixpkgs/pull/341973.

**Comment by dotlambda** [comment]
> Note also that electron-chromedriver update got merged in #341973.

Not the update to 32.1.1.

**Comment by dotlambda** [comment]
I successfully built

* `bitwarden-desktop`
* `chromium`
* `electron_32-bin`
* `electron-source.electron_32`

on x86_64-linux.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 343097` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>archivebox</li>
    <li>archivebox.dist</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>bilibili</li>
    <li>gotenberg</li>
  </ul>
</details>
<details>
  <summary>109 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>antares</li>
    <li>antimatter-dimensions</li>
    <li>armcord</li>
    <li>aws-azure-login</li>
    <li>bitwarden-desktop</li>
    <li>bitwarden-directory-connector</li>
    <li>blockbench</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>caprine</li>
    <li>chatd</li>
    <li>chromedriver</li>
    <li>chromium</li>
    <li>chromium.sandbox</li>
    <li>deltachat-desktop</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron (electron_32)</li>
    <li>electron-bin (electron_32-bin)</li>
    <li>electron-chromedriver (electron-chromedriver_32)</li>
    <li>electron_30</li>
    <li>electron_31</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>fast-cli</li>
    <li>fcast-receiver</li>
    <li>feishin</li>
    <li>flaresolverr</li>
    <li>freetube</li>
    <li>goofcord</li>
    <li>grafana-kiosk</li>
    <li>headset</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>httptoolkit</li>
    <li>itch</li>
    <li>jitsi-meet-electron</li>
    <li>koodo-reader</li>
    <li>logseq</li>
    <li>lx-music-desktop</li>
    <li>mattermost-desktop</li>
    <li>mermaid-cli</li>
    <li>mermaid-filter</li>
    <li>morgen</li>
    <li>mqtt-explorer</li>
    <li>nix-tour</li>
    <li>obsidian</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>percollate</li>
    <li>playwright-test</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>proton-pass</li>
    <li>protonmail-desktop</li>
    <li>puppeteer-cli</li>
    <li>python311Packages.great-tables</li>
    <li>python311Packages.great-tables.dist</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python311Packages.pytest-playwright</li>
    <li>python311Packages.pytest-playwright.dist</li>
    <li>python311Packages.shiny</li>
    <li>python311Packages.shiny.dist</li>
    <li>python312Packages.great-tables</li>
    <li>python312Packages.great-tables.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.pytest-playwright</li>
    <li>python312Packages.pytest-playwright.dist</li>
    <li>python312Packages.shiny</li>
    <li>python312Packages.shiny.dist</li>
    <li>r2modman</li>
    <li>redisinsight</li>
    <li>revolt-desktop</li>
    <li>ride</li>
    <li>selendroid</li>
    <li>selenium-server-standalone</li>
    <li>sharedown</li>
    <li>single-file-cli</li>
    <li>sitespeed-io</li>
    <li>siyuan</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>teams-for-linux</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>thedesk</li>
    <li>threema-desktop</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>undetected-chromedriver</li>
    <li>ungoogled-chromium</li>
    <li>ungoogled-chromium.sandbox</li>
    <li>vesktop</li>
    <li>vhs</li>
    <li>vieb</li>
    <li>wayback</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
    <li>webtorrent_desktop</li>
    <li>yandex-music</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
    <li>ytmdesktop</li>
  </ul>
</details>

**Review by yayayayaka — APPROVED** [review]
Thanks a lot for taking care of it! :heart:

Diff looking good to me, should be good to go.

**Pull request merged**
