### PR TITLE
hyprpaper: 0.5.0 -> 0.6.0

### PR DESCRIPTION
**Pull request by fufexan**
## Description of changes

- hyprlang: init at 0.2.1 (new dependency of hyprpaper)
- hyprpaper: 0.5.0 -> 0.6.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by geri1701 — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
remove the changes in pkgs/top-level/all-packages.nix and rebase when #278784 merges.

**Review by ghost — CHANGES_REQUESTED** [review]
i believe this needs to get rebased off master to pull in https://github.com/NixOS/nixpkgs/pull/278784
not sure why it is not registering a merge-conflict with the changes to pkgs/by-name/hy/hyprlang/package.nix and pkgs/top-level/all-packages.nix

[edit] seems this might be ok if the changes are identical to what is in master.

**Comment by fufexan** [comment]
The `hyprlang` commit is the same, I made sure of that. Probably why it doesn't trigger a conflict.

**Comment by a-n-n-a-l-e-e** [comment]
> The `hyprlang` commit is the same, I made sure of that. Probably why it doesn't trigger a conflict.

ok -- `nixpkgs-review` did the right thing too -- no merge conflicts.

however, the aarch64-linux build is [failing](https://logs.ofborg.org/?key=nixos/nixpkgs.278364&attempt_id=50b4a72f-6e40-4597-bbe4-3dfcc1424c92)
```console
/nix/store/wjkn3fmykn68rbpnamj9kzgw263xcga2-binutils-2.40/bin/ld: /nix/store/hddv2aciqs8k8pza6nsrhxki3ri60n1p-hyprlang-0.2.1/lib/libhyprlang.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_cold(char*, unsigned long, char const*, unsigned long, unsigned long)@GLIBCXX_3.4.31'
```

**Comment by a-n-n-a-l-e-e** [comment]
> however, the aarch64-linux build is [failing](https://logs.ofborg.org/?key=nixos/nixpkgs.278364&attempt_id=50b4a72f-6e40-4597-bbe4-3dfcc1424c92)
> 
> ```
> /nix/store/wjkn3fmykn68rbpnamj9kzgw263xcga2-binutils-2.40/bin/ld: /nix/store/hddv2aciqs8k8pza6nsrhxki3ri60n1p-hyprlang-0.2.1/lib/libhyprlang.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_cold(char*, unsigned long, char const*, unsigned long, unsigned long)@GLIBCXX_3.4.31'
> ```

i think this link error is due to using gcc13 for libhyprlang but hyprpaper is gcc12 on aarch64-linux, so you'll have to add the gcc13stdev to hyprpaper in all-packages.nix too.

**Comment by a-n-n-a-l-e-e** [comment]
@ofborg build hyprpaper

**Review by ghost — APPROVED** [review]

**Pull request merged**
