### PR TITLE
stdenv.mkDerivation: add -static to name if building statically

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

Mark native statically built packages with a `-static` suffix. The primary objective of this is to get rid of the cross suffix of `x86_64-unknown-linux-musl` for `pkgsStatic` which seems unnecessary as we are actually compiling natively, but to add a suitable replacement. 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
It would be better to fix this for all static packages, but this is a good temporary fix.

**Comment by sternenseemann** [comment]
> It would be better to fix this for all static packages, but this is a good temporary fix.

It should work for all static packages as long as their `hostPlatform` has `isStatic == true`. Apart from that as far as I know  there is no generic way of detecting this. The `enableStatic` input some packages take is a bit of a problem here, but unless we pass it to `mkDerivation` I don't think there's much we can do?!

**Comment by domenkozar** [comment]
@ofborg build nix staticPkgs.nix

**Comment by sternenseemann** [comment]
@ofborg build nixStatic pkgsStatic.nix

**Pull request merged**
