### PR TITLE
Wine: add several dependencies

### PR DESCRIPTION
**Pull request by abbradar**
This adds Wine Staging patchset as new derivation. Also, `gettext` is added for Wine translations and `mpg123` for MP3 playing without replacing Wine's `quartz.dll`. I have a feeling the latter was omitted because of licensing issues, so we can't just add it by default. cc @7c6f434c

### CODE REVIEW

**Comment by abbradar** [comment]
BTW, it looks like in `overrideDerivations` `nativeBuildInputs` and `buildInputs` roles are reversed (see `wineStaging` derivation). Strange! Any ideas, anyone?

**Comment by abbradar** [comment]
I've pushed `wineStaging` into `master` -- now only `mpg123` and `gettext` parts remain. I'm afraid of some kind of licensing issues with `mpg123` -- are there any problems with it?

**Comment by edolstra** [comment]
Hm, do we really need 3 different versions of Wine? Generally Nixpkgs shouldn't include pre-release versions of packages.

**Comment by abbradar** [comment]
That's not so "pre-release" as it's "a bundle of patches which may (or may not) be pulled in master". For example, core Wine developers are opposed to pulling Pulseaudio patches at all. Another very important feature of this patchset is CSMT which brings considerable performance wins to Direct3D applications -- and is not going to land anytime soon, too. This patchset is also partially included in Fedora because of these reasons.

**Comment by Fuuzetsu** [comment]
Needs rebasing

**Comment by abbradar** [comment]
I revisited this and think this should be redone adding all optional dependencies and `withX` flags with reasonable defaults. Unfortunately, scripts for Wine are a bit complex now and I don't have time to do things properly until somewhere June. Closing for now.

**Pull request closed without merging**
