### PR TITLE
pythonPackages.pygit2: 0.23.1 -> 0.24.0

### PR DESCRIPTION
**Pull request by Azulinho**
###### Motivation for this change

GH issue: https://github.com/NixOS/nixpkgs/issues/15985

fixes python2.7-powerline build which pygit2 0.23 dep required a corresponding libgit2 0.23.x version:

```

gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/nix/store/89v0gq67zsy9vlrxm5ms89s5jf02ibhy-python-2.7.11/include/python2.7 -c src/treebuilder.c -o build/temp.linux-x86_64-2.7/src/treebuilder.o
In file included from src/utils.h:34:0,
                 from src/treebuilder.c:32:
src/types.h:36:2: error: #error You need a compatible libgit2 version (v0.23.x)
 #error You need a compatible libgit2 version (v0.23.x)
  ^
error: command 'gcc' failed with exit status 1
builder for ‘/nix/store/lzs99vnjr1haihbnbdgbl34fsswppd4w-python2.7-pygit2-0.23.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/84jr9k9c95b716q9zpjcnpry6sgblln9-python2.7-powerline-2.1.4.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6mcx8fcas098y1jnwacq555p68h50mk2-all.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/6mcx8fcas098y1jnwacq555p68h50mk2-all.drv’ failed
```

```
creating build/bdist.linux-x86_64/wheel/pygit2-0.24.0.dist-info/WHEEL
installing
/tmp/nix-build-python2.7-pygit2-0.24.0.drv-0/pygit2-0.24.0/dist /tmp/nix-build-python2.7-pygit2-0.24.0.drv-0/pygit2-0.24.0
Ignoring indexes: https://pypi.python.org/simple
Processing ./pygit2-0.24.0-cp27-cp27mu-linux_x86_64.whl
Collecting six (from pygit2==0.24.0)
  Could not find a version that satisfies the requirement six (from pygit2==0.24.0) (from versions: )
No matching distribution found for six (from pygit2==0.24.0)
builder for ‘/nix/store/84kvvycmhjg6fqpnxhh6k2xh6h5zbykz-python2.7-pygit2-0.24.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/mdpmiy430cbvqmxj0lc9vvq575d6d639-python2.7-powerline-2.1.4.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/5nxmmixwf0wfml3hqqf8si1dk7j16c5r-all.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/5nxmmixwf0wfml3hqqf8si1dk7j16c5r-all.drv’ failed
```
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks for looking at this. I would think that six is actually needed during runtime, in order to be able to use it with say Python 3.x. Therefore, instead of adding it to `buildInputs` it should probably added `propagatedBuildInputs`. Try if the package actually works with all Python interpreters.

**Comment by Azulinho** [comment]
@FRidh thanks for the ubber::fast response.
I initially looked into setup.py and six wasn't listed as a dep for pygit2.
Hoever looking into the pygit2 install docs it does show up as required.

**Comment by Azulinho** [comment]
not entirely sure why travis has barked out from my changes, grabbing .travis.yaml and testing it locally on a similar ubuntu vagrant VM.

**Comment by Azulinho** [comment]
Giving up on this,

I managed to replicate the same travis build failure by using a vagrantfile that executes the same steps as .travis.yml. But I honestly don't understand the 'why' of those steps, or the root cause of that failure.

Thinking about what a typical CI process would be for a change like this, and looking to the travis setup I came up with a Vagrantfile which does build correctly.

```
\> cat Vagrantfile
vbox_version = `VBoxManage --version`

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.96", nic_type: "virtio"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "3072"
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
     vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
     vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"] if vbox_version.to_f >= 5.0
     vb.customize ["storagectl", :id, "--name", "SATAController", "--hostiocache", "on"]
     vb.customize ["modifyvm", :id, "--ioapic", "on"]
     vb.customize ["modifyvm", :id, "--cpus", `#{RbConfig::CONFIG['host_os'] =~ /darwin/ ? 'sysctl -n hw.ncpu' : 'nproc'}`.chomp]

     vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    groupadd nixbld
    usermod -G nixbld vagrant
    apt-get update
    apt-get install -y build-essential git
    test -e /swapfile || ( dd if=/dev/zero of=/swapfile bs=1M count=2048 &&  mkswap /swapfile )
    swapon /swapfile || echo
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
     git clone https://github.com/NixOS/nixpkgs.git
     cd nixpkgs
     git config --global user.email "me@example.com"
     git config --global user.name "Your Name"

     git remote add Azulinho https://github.com/Azulinho/nixpkgs.git
     set -e
     git fetch Azulinho
     git merge Azulinho/update_libgit2_to_v24

     curl https://nixos.org/nix/install | sh
    . /home/vagrant/.nix-profile/etc/profile.d/nix.sh
    nix-build nixos/release.nix -A options --show-trace
    nix-build pkgs/top-level/release.nix -A tarball --show-trace
  SHELL

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    cd /home/vagrant/nixpkgs
    . /home/vagrant/.nix-profile/etc/profile.d/nix.sh
    nix-build --option build-use-chroot true $PWD -A python27Packages.powerline -A gitfs -A python35Packages.pygit2 -A python27Packages.pygit2 -A python35Packages.powerline
  SHELL
end
```

my time is considerable more valuable than the size of this fix, so I will just cut my losses and give up on this.

**Comment by fpletz** [comment]
Not sure what went wrong on travis but this does work for me locally. I've restarted travis. I would go ahead and merge this after some more testing.

**Comment by Azulinho** [comment]
I am done with it, I am now using my own fork on my deploys.

I saw a bunch of people submitting their patch diffs to the mailling list and getting those merged straight away, so I don't see the point on having this workflow in place for github pull-requests.
Following the steps listed at the top won't prevent derivation failures on the master branch, as 'work on my machine' changes that can cause breakage are fast-tracked from the mailling lists.

Feel free to close this PR.

**Comment by fpletz** [comment]
I don't understand the hostility. And as far as I can see there was only one patch on the mailing list in the last few months that was probably merged right away because someone had some spare time. 

Travis is broken quite a lot due to space issues or changes on master unrelated to PRs. It's the responsibility of both the submitter and the contributors to check why travis is failing and if it can be ignored or not. I don't know why your PR wasn't picked up by another contributor, I was just sifting through old pull requests to get them merged…

**Comment by Azulinho** [comment]
oooooOOOooaaahhh, I wasn't being hostile in any way, have no reasons for being unhappy.
I probably sounded harsh as I was direct on why I had given up on this PR.  You happened to merge it as I was replying to your previous comment.

If the travis builds do not work, then get rid of them. They arent' providing any value, in fact most of the time I spent on this PR was spent trying to reproduce the Travis build locally so that I could understand why they here failling.

**Pull request merged**
