### PR TITLE
systemd: fix build

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

Build failed.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
How did that end up being broken without being noticed?

**Comment by alyssais** [comment]
> How did that end up being broken without being noticed?

Not a question I can answer, I'm afraid.

**Comment by ajs124** [comment]
Maybe the gcc 10.3 bump in #119219?

**Comment by andir** [comment]
Looks good to me. I would not be surprised if this isn't the only package that fails now...

**Pull request merged**
