### PR TITLE
gnupg: 2.3.7 -> 2.4.0

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by afh** [comment]
FWIW: Successfully built and tested on aarch64-darwin. Thanks for this PR.

**Comment by doronbehar** [comment]
Fixed merge conflicts.

**Comment by doronbehar** [comment]
I wonder whether we should keep the gnupg23 version. Currently this PR suggests to remove it.

**Comment by afh** [comment]
According to the [GnuPG 2.4.0 release announcement](https://lists.gnupg.org/pipermail/gnupg-announce/2022q4/000477.html) _"Version 2.2 is our LTS (long term support) version and guaranteed to be maintained at least until the end of 2024"_ and _"Version 2.4 is the current stable version with a lot of new features compared to 2.2"_.

With that in mind it might make "more" sense for nixpkgs to and replace 2.3 in with of 2.4 and provide gnupg 2.2 alongside of gnupg 2.4.

Curios what other think about that reasoning.

**Comment by ajs124** [comment]
@afh, we don't have `gnupg22` since #145434

**Comment by afh** [comment]
Thanks for chiming in, @ajs124, and providing additional context. What's your take on this? Would it make sense to re-introduce GnuPG 2.2 to offer the official LTS version? Or is it more feasible to replace GnuPG 2.3 with 2.4?

**Comment by ajs124** [comment]
Well, it seems to me that we're in the same position I already described [here](https://github.com/NixOS/nixpkgs/pull/145434#issuecomment-968173633) that nobody really cares about this package.

So I'd say, just drop 23, go with 24 and if and when a new LTS version releases, just stick to that, pointing to previous history of maintenance. If anything breaks, it breaks. I'm sure the people that decided that we shouldn't stick to the LTS release will take care of any issues.

**Comment by colemickens** [comment]
I don't have an opinion on re-introducing `gnupg-2.2`. However, we already missed that boat when we replaced it with 2.3. Thus, I'm in favor of merging this as-is (unless there's some thought that 2.3->2.4 was riskier than 2.2->2.3, but I don't see anyone trying to argue that).

Maybe a separate issue could be opened justifying the re-introduction of gnupg-2.2? In particular, I'd be curious if someone could round up what package other distros give you if you just try to install gpg latest.

**Comment by afh** [comment]
Thanks for chiming in @colemickens. For what it's worth I greatly appreciate nixpkgs offering newer version, i.e. 2.3 / 2.4 of GnuPG, yet I also see value in providing the Long Term Support (LTS) version, i.e. 2.2, as an even more stable version especially to those who rely on it.

Here's a quick round up of which version of GnuPG is installed in a few different distros, take it with a grain of 🧂

| Distro | GnuPG Version |
|---|---|
|[Alpine 3.17](https://pkgs.alpinelinux.org/packages?name=gnupg&branch=edge&repo=&arch=&maintainer=)| 2.2.41|
|[Ubuntu Kinetic (22.10)](https://packages.ubuntu.com/search?keywords=gnupg&searchon=names&suite=kinetic&section=all) | 2.2.35|
|[Debian 11 (stable)](https://packages.debian.org/search?keywords=gnupg&searchon=names&suite=stable&section=all) | 2.2.27 |
|[Gentoo](https://packages.gentoo.org/packages/app-crypt/gnupg) | 2.2.40|

**Comment by afh** [comment]
Thanks for merging, @vcunat, much appreciated 🙂

**Comment by mweinelt** [comment]
There were some interoperability concerns voiced on the distributions@ list, where gnugp with 2.4.0 is incompatible with openpgp implementations following the IETF standard.

https://lore.kernel.org/distributions/F30D6590-3E0C-4865-A944-7DE118A619CF@gentoo.org/T/#u

**Comment by afh** [comment]
Thank you for your insightful comment, @mweinelt, it inspired me to draft #215109.

Anyone that has commented here before is invited to review and chime in on #215109.
/cc @doronbehar, @ajs124, @colemickens

**Pull request merged**
