### PR TITLE
viber: add pkg

### PR DESCRIPTION
**Pull request by jagajaga**
Works fine except bug mentioned in `default.nix`
Questions:
1. What to do with url? It's not permanent, and I can't find stable one.
2. How to alert users about bug and that they have to use fix to avoid it?

### CODE REVIEW

**Comment by lethalman** [comment]
I don't think there's any solution to the download url besides creating an archive. At the same time, I think they forbid using older versions of the app?

**Comment by jagajaga** [comment]
Yes, I think so.
Indeed, I can update pkg as soon as hydra will tell me so.

**Comment by jagajaga** [comment]
@lethalman and what about warnings?

**Comment by k2s** [comment]
@agajaga the time is here :-), there is v6.0.1.5 of the deb package, 

```
sha256 = "026vp2pv66b2dlwi5w5wk4yjnnmnsqapdww98p7xdnz8n0hnsbbi"
```
but it requires more changes,in the installation expression. trying to look into it, but I am not experienced with Nix

**Pull request merged**
