### PR TITLE
texlive: add new tlpdb parser [WIP]

### PR DESCRIPTION
**Pull request by xworld21**
###### Motivation for this change
With apologies for dropping this completely out of the blue... The current `texlive.combine` approach has some pain points when you want to do your own combination, especially the fact that formats are recompiled constantly.

So I upgraded `tl2nix.sed` to a perl script that exposes all the details about hyphenation patterns, formats and font maps, and in principle metadata (disabled as it cannot be used with `combine.nix`). I have added *a lot* of error checking if something uncovered appears in `texlive.tlpdb`. The new `pkgs.nix` (now `texlive-snapshot.tlpdb.json`) is slightly larger, but not by a lot.

It is also a start towards supporting other repositories https://github.com/NixOS/nixpkgs/issues/99592#issuecomment-706809876.

This is just an idea, and certainly it is not as concise as `tl2nix.sed`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I checked that the packages come out with the same fixed hashes.

### CODE REVIEW

**Comment by xworld21** [comment]
I think this is in a good state. I have chosen to follow [json-formats.txt](https://www.tug.org/texlive/devsrc/Master/tlpkg/doc/json-formats.txt) with minimal changes to be unopinionated, but I can make it an extension of the previous `pkgs.nix` and minimize the diff.

At any rate, there is enough information to generate the correct `fmtutil.cnf` and fix #101405, generate `language.dat.lua` which is currently missing, and replace the `hyphen.sed` hack with a proper solution.

I was wondering: since the JSON file is deterministically generated with a derivation (we can even add a fixed hash), can we import it from the store path, instead of having it in nixpkgs? I gather there would be issues with pure evaluation, but maybe there is an escape hatch with `fetchurl` and the likes?

**Comment by xworld21** [comment]
@veprbl I believe this is converging to something usable. Using [json-formats.txt](https://www.tug.org/texlive/devsrc/Master/tlpkg/doc/json-formats.txt) (so the same as `tlmgr dump-tlpdb --json`) seems like a sensible replacement for the adhoc `pkgs.nix`. I have used the metadata to speed up the handling of the hyphenation patterns.

But maybe the PR was not a good place to start – what is the best way to propose ideas for texlive?

**Comment by veprbl** [comment]
@xworld21 I don't have too much time to review this right now. This is a big change, and I'm not clear on why we are worse off without this. Also, it makes me wonder if interpreting json from nix causes any regression in cpu/memory needed to evaluate the `texlive` packages. Another concern that I have is that this is written elegantly but still in Perl, and it might be harder for people in the community to maintain/review this if they don't know Perl.

**Comment by xworld21** [comment]
@veprbl many thanks for the directions. That's ok. My target for now is generating the config files properly (first `fmtutil.cnf`, then `language.*` *including lua* and font maps), and more efficiently. Then eventually run the postaction scripts for the handful of packages that need them. I believe I can do all of those with some tweaks to `tl2nix.sed`, and that should be easy to review.

Long term, a proper parser would be nice. I am concerned about `tl2nix.sed` producing valid expressions, but with wrong details, because of changes in the database invalidating the (undocumented) assumptions.

**Comment by xworld21** [comment]
The sed script is now powerful enough to extract virtually all the required information, no need to keep this around.

**Pull request closed without merging**
