### PR TITLE
home-assistant: 0.108.7 -> 0.109.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
First impression: the systemd service is running, but my web ui is not accessible. Nothing is jumping out at first glance, I'll have to look into it more later.

**Comment by colemickens** [comment]
btw, a bit off-topic, but related and people reading this might want the context: https://www.home-assistant.io/blog/2020/04/14/the-future-of-yaml/

It looks like this is going to impact some of my configuration in coming versions. I'd love to see a new lighter, declarative contender pop-up...

**Comment by colemickens** [comment]
Hm. It came up eventually. That took a _long_ time, even by HA standards.

**Comment by Mic92** [comment]
Works for me.

**Pull request merged**
