### PR TITLE
nodejs: Fix build on Darwin

### LINKED ISSUE #10109: darwin: nodejs build fails when applying patch /nix/store/...-no-xcode.patch
```
./tools/v8-prof/mac-tick-processor: interpreter directive changed from "/bin/sh" to "/nix/store/klck12hfv46k2whk0zg2ggsf086xf2lf-bash-4.3-p42/bin/sh  "
applying patch /nix/store/w9f0cqmzjgpdcyfqaihzf80bdwn7x4xg-no-xcode.patch
patching file tools/gyp/pylib/gyp/xcode_emulation.py
Hunk #1 succeeded at 446 (offset 144 lines).
Hunk #2 succeeded at 579 (offset 152 lines).
Hunk #3 succeeded at 835 with fuzz 2 (offset 153 lines).
Hunk #4 succeeded at 1043 (offset 169 lines).
Hunk #5 FAILED at 1033.
1 out of 5 hunks FAILED -- saving rejects to file tools/gyp/pylib/gyp/xcode_emulation.py.rej
builder for ‘/nix/store/xyawavmz90hkwgwr9dh1nrzz9q08gc83-nodejs-4.1.0.drv’ failed with exit code 1
error: build of ‘/nix/store/xyawavmz90hkwgwr9dh1nrzz9q08gc83-nodejs-4.1.0.drv’ failed
```

### PR DESCRIPTION
**Pull request by datakurre**
Should fix #10109 and replace #10095

@utdemir Could you test that this works for you?

I hope, the stdenvDarwin condition for libtool is correct.

### CODE REVIEW

**Comment by utdemir** [comment]
@datakurre This builds fine on me too! Thanks.

**Comment by codedmart** [comment]
@datakurre I think we need to rename the current no-xcode.patch then add yours. The current no-xcode.patch still works with v0_10 and I am assuming v0_12 which is on [staging](/nixos/nixpkgs/tree/staging).

**Comment by datakurre** [comment]
@codedmart Thanks for catching that. I added a new patch file for v41. I expect it to work, but takes some time to build confirm...

**Comment by datakurre** [comment]
This has been fixed in master. Closing.

**Pull request closed without merging**
