### PR TITLE
electrs: 0.8.12 -> 0.9.0

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- version update
- link rocksdb dynamically

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erikarvstedt** [comment]
Your PR description mentions `link rocksdb dynamically`. Is the inclusion of the macOS security framework related to dynamic linking?

**Comment by prusnak** [comment]
> Is the inclusion of the macOS security framework related to dynamic linking?

No, unrelated. The inclusion is because some new cargo dependency requires it.

**Comment by erikarvstedt** [comment]
This PR contains a bug.
@SuperSandro2000, I really appreciate your awesome work in nixpkgs, but please allow for one review by another person who is familiar with the topic at hand.

**Comment by SuperSandro2000** [comment]
> This PR contains a bug.

What bug?

**Comment by erikarvstedt** [comment]
The bug is fixed here: https://github.com/NixOS/nixpkgs/pull/140030

**Pull request merged**
