### PR TITLE
k3s: k3s_1_27 -> k3s_1_28

### PR DESCRIPTION
**Pull request by superherointj**
k3s: k3s_1_27 -> k3s_1_28

Tracking issue: https://github.com/NixOS/nixpkgs/issues/287344

ping @euank @Mic92 @yajo @wrmilling

## This PR is ready to be merged.

### CODE REVIEW

**Review by wrmilling — APPROVED** [review]
Upgrade notes for moving from k3s 1.27 -> 1.28: [1.28 Change Log](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#changelog-since-v1270). 

Mostly a few deprecations and a behavior change to be aware of for those that upgrade. 

Otherwise, LGTM.

**Comment by superherointj** [comment]
@euank Please, review.

**Comment by superherointj** [comment]
@ofborg build k3s.passthru.tests.single-node k3s.passthru.tests.multi-node

**Comment by superherointj** [comment]
Pass through tests are broken in CI.

image
```

       >     exec(self.tests, symbols, None)
       >   File "<string>", line 4, in <module>
       >   File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 469, in wait_for_unit
       >     retry(check_active, timeout)
       >   File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 134, in retry
       >     raise Exception(f"action timed out after {timeout} seconds")
       > Exception: action timed out after 900 seconds
       > kill vlan (pid 7)
       For full logs, run 'nix log /nix/store/gv3y300mfhb3ph89bkfccl64vlwqjwm2-vm-test-run-k3s-1.28.6+k3s1-multi-node.drv'.
error: build of '/nix/store/gv3y300mfhb3ph89bkfccl64vlwqjwm2-vm-test-run-k3s-1.28.6+k3s1-multi-node.drv', '/nix/store/xr15wlq6bllyapxpajpl095iylalrgxb-vm-test-run-k3s-1.28.6+k3s1-single-node.drv' failed
```

It builds this way:
nix build .#k3s.passthru.tests.single-node

Won't build this way:
nix build .#nixosTests.k3s.single-node

Would OfBorg understand as that? I think, maybe we need to rethink this.
Idk *yet*.

**Comment by euank** [comment]
Looking at ofborgs logs, the errors seem real:

```
server # [  928.439558] k3s[6224]: time="2024-02-10T16:32:43Z" level=fatal msg="Failed to validate golang version: kubernetes golang build version not set - see 'golang: upstream version' in https://github.com/kubernetes/kubernetes/blob/dev/build/dependencies.yaml"
```

(from [this link](https://logs.ofborg.org/?key=nixos/nixpkgs.287782&attempt_id=b2ba6cc8-05cd-43d0-9aa4-de023295ca0c)).

I think that means that we want to land https://github.com/NixOS/nixpkgs/pull/287792 before we land this one so the default k3s attribute works.

We accidentally broke 1_28 when https://github.com/NixOS/nixpkgs/pull/286095 merged, so before swapping the default to 1_28 we should fix that.

Apart from waiting on your fix to 1_28 to merge, this looks good to me!

**Comment by superherointj** [comment]
> I think that means that we want to land #287792 before we land this one so the default k3s attribute works.
> 
> We accidentally broke 1_28 when #286095 merged, so before swapping the default to 1_28 we should fix that.
> 
> Apart from waiting on your fix to 1_28 to merge, this looks good to me!

Yes, you are right.

A commiter needs to merge: #287792

Then I need to rebase this PR.

Can you still do merges?

**Review by euank — APPROVED** [review]
LGTM now!
As above, thanks for picking this up!

**Review by yajo — APPROVED** [review]

**Comment by superherointj** [comment]
Thanks wegank!

**Pull request merged**
