### PR TITLE
dvc: init at 0.41.3

### PR DESCRIPTION
**Pull request by jeromebaum**
###### Motivation for this change

To add the "dvc" app to nixpkgs. See https://dvc.org for a description of dvc and its use-cases.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
    - Tested execution of `dvc` executable but not the other binary files.
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
    - I don't know how to add the meta attribute.

---

### CODE REVIEW

**Comment by jeromebaum** [comment]
Looks like there's another open PR with an older version: https://github.com/NixOS/nixpkgs/pull/54530

**Comment by worldofpeace** [comment]
As far as I can tell we don't accept packages using `pypi2nix` in nixpkgs.
Perhaps you could complete https://github.com/NixOS/nixpkgs/pull/54530 which uses `buildPython*`.

> nixpkgs manual on python packaging
> https://nixos.org/nixpkgs/manual/#python

**Comment by jeromebaum** [comment]
No worries. I'm closing this in favor of #54530 and I'll just wait and see if the authors on that complete it. Thanks.

**Comment by CMCDragonkai** [comment]
Hey @jeromebaum I don't have time to finish #54530, can you take over that. There's just one change I think the reviewer wanted.

**Pull request closed without merging**
