### PR TITLE
jazzy: 0.9.6 -> 0.10.0

### PR DESCRIPTION
**Pull request by lilyball**
Also define passthru.updateScript.

###### Motivation for this change
https://github.com/realm/jazzy/releases/tag/v0.10.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by risicle** [comment]
Builds for me, macos 10.13

**Comment by lilyball** [comment]
Updated the gems again since cocoapods 1.7.3 is out now.

**Comment by lilyball** [comment]
Updated again, this time for cocoapods 1.7.4.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build jazzy

**Comment by worldofpeace** [comment]
Sorry it took so long for someone to review this, the issue was probably the small amount of macos nixpkgs reviewers.

IIRC @marsam uses macos so you should be able to ping them for review on future PRs.

@marsam Do you think you can test this?

**Pull request merged**
