### PR TITLE
jitsi: update

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
update of all jitsi components

Closes  #170058  #177975 #163778  #159517

The nixos test does not succeed, so this might need package or module changes.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
This could _definitely_ need more testing, e.g. if you can actually have a call, etc.

I've only run the test so far.

**Review by yayayayaka — APPROVED** [review]
Deployed on x86_64-linux for manual testing and was able to hear each participant.

2022-06-29T11:33:23+02:00-yunix

LGTM!

**Comment by ajs124** [comment]
@yayayayaka thanks for testing! did you also test screen sharing (ideally via the videobridge)?

**Comment by yayayayaka** [comment]
Yes. Tested screen sharing and webcam video.

**Comment by pstn** [comment]
@ajs124 I think this one should be backported to 22.05. The version in there isn't compatible with prosody-12 (only version of prosody in 22.05), leading to [some big compatibility issues](https://github.com/jitsi/jicofo/issues/895)

**Comment by yayayayaka** [comment]
I agree as I am affected by this bug.

**Pull request merged**
