### PR TITLE
Buildkite agent fixup

### PR DESCRIPTION
**Pull request by mrkkrp**
###### Motivation for this change

There are two changes:

* Update the buildkite agent version.
* Fix a bug in NixOS' buildkite agent service module so that the `services.buildkite-agent.package` actually has effect. In addition to that, version 3 allows us to set `tags="gueue=test"` which is rejected if `meta-data` is set before `tags` the whole configuration is rejected. So I figured that we should only set `meta-data` when it's actually specified by the user.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by grahamc — APPROVED** [review]
Another improvement which would be nice to make is letting openssh.privateKeyPath and openssh.publicKeyPath be optional.

**Comment by mrkkrp** [comment]
I have to go now, but if you can wait a little bit I'll make those optional. And maybe add more options that we actually use instead of putting them in extra config.

**Comment by grahamc** [comment]
How about we do that as a different PR?

A third thing which would be *really* nice is making `metadata` an attribute set:

```
metadata = {
    queue = "test";
    another-thing = "whatever";
};
```

I never remember how to set metadata, and get it wrong. If it was an attribute set like this, it would be immediately obvious.

**Comment by mrkkrp** [comment]
I’m OK with doing it in a different PR. In that case you can merge this one, unless there is something else to be done?

**Comment by grahamc** [comment]
I forgot to test that building buildkite worked, and so I tested it locally and it did :)

**Pull request merged**
