### PR TITLE
Vimplugins vim-simpledb and lightline-gruvbox-vim

### PR DESCRIPTION
**Pull request by cjab**
###### Motivation for this change

Add the vim-simpledb and lightline-gruvbox-vim vimPlugins.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126009` at 7c1f9cb4 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/1f40e6012febbdf284a6d3c965a96a9b">vimPlugins.vim-clap</a></li>
  </ul>
</details>
<details>
  <summary>35 packages built successfully:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.denite-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.dhall-vim</li>
    <li>vimPlugins.gina-vim</li>
    <li>vimPlugins.git-messenger-vim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.lightline-gruvbox-vim</li>
    <li>vimPlugins.ncm2-neosnippet</li>
    <li>vimPlugins.neosnippet-vim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lightbulb</li>
    <li>vimPlugins.nvim-toggleterm-lua</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.sideways-vim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-simpledb</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by jonringer** [comment]
Thanks for submitting your first PR :)

**Review by jonringer — APPROVED** [review]
LGTM
I'll fix vim-clap in another PR

```
https://github.com/NixOS/nixpkgs/pull/126009

1 package failed to build:
vimPlugins.vim-clap

35 packages built:
spacevim vimPlugins.aurora vimPlugins.chadtree vimPlugins.defx-nvim vimPlugins.denite-nvim vimPlugins.deol-nvim vimPlugins.deoplete-fish vimPlugins.deoplete-khard vimPlugins.deoplete-nvim vimPlugins.dhall-vim vimPlugins.gina-vim vimPlugins.git-messenger-vim vimPlugins.gitsigns-nvim vimPlugins.lightline-gruvbox-vim vimPlugins.ncm2-neosnippet vimPlugins.neosnippet-vim vimPlugins.nvim-autopairs vimPlugins.nvim-bqf vimPlugins.nvim-dap-ui vimPlugins.nvim-hlslens vimPlugins.nvim-jdtls vimPlugins.nvim-lightbulb vimPlugins.nvim-toggleterm-lua vimPlugins.nvim-tree-lua vimPlugins.nvim-treesitter-context vimPlugins.sideways-vim vimPlugins.telescope-frecency-nvim vimPlugins.telescope-fzf-writer-nvim vimPlugins.telescope-fzy-native-nvim vimPlugins.telescope-nvim vimPlugins.telescope-symbols-nvim vimPlugins.telescope-z-nvim vimPlugins.vim-autoformat vimPlugins.vim-fugitive vimPlugins.vim-simpledb
```

**Comment by cjab** [comment]
> Thanks for submitting your first PR :)

Thank you! 😄

**Pull request merged**
