### PR TITLE
vouch-proxy: 0.36.0 -> 0.37.0

### PR DESCRIPTION
**Pull request by squalus**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by em0lar** [comment]
For me the tests fail:
```
--- FAIL: Test_normalizeLoginURL (0.00s)
    --- PASS: Test_normalizeLoginURL/extra_params (0.00s)
    --- PASS: Test_normalizeLoginURL/extra_params_(blank) (0.00s)
    --- PASS: Test_normalizeLoginURL/prior_params (0.00s)
    --- PASS: Test_normalizeLoginURL/vouch-*_params_after (0.00s)
    --- PASS: Test_normalizeLoginURL/vouch-*_params_before (0.00s)
    --- PASS: Test_normalizeLoginURL/x-vouch-*_params_after (0.00s)
    --- PASS: Test_normalizeLoginURL/x-vouch-*_params_before (0.00s)
    --- PASS: Test_normalizeLoginURL/params_after_vouch-*_params (0.00s)
    --- PASS: Test_normalizeLoginURL/params_after_x-vouch-*_params (0.00s)
    --- PASS: Test_normalizeLoginURL/all_params (0.00s)
    --- PASS: Test_normalizeLoginURL/all_params_(encoded) (0.00s)
    --- FAIL: Test_normalizeLoginURL/all_params_(semicolons) (0.00s)
    --- FAIL: Test_normalizeLoginURL/all_params_(encoded,_semicolons) (0.00s)
    --- PASS: Test_normalizeLoginURL/Vouch_Proxy_README_(with_error) (0.00s)
    --- PASS: Test_normalizeLoginURL/Vouch_Proxy_README_(blank_error) (0.00s)
    --- FAIL: Test_normalizeLoginURL/Vouch_Proxy_README_(semicolons,_blank_error) (0.00s)
    --- PASS: Test_normalizeLoginURL/rd_param_appended_by_Nginx_Ingress (0.00s)
```

**Comment by erictapen** [comment]
@em0lar On which platform are you?

**Comment by erictapen** [comment]
Weird, I build it fine on x86_64-linux and ofborg doesn't see a problem as well. Maybe it's flaky? Did you try to build it twice?

**Review by erictapen — APPROVED** [review]
When @em0lar doesn't see the test failure anymore this can be merged.

**Comment by em0lar** [comment]
Okay, you can merge it.

When I build it as a standalone nix package or as package overlay in my nixfiles (nixos/nixpkgs@b06d35b406c2396dd1611dc8601138fa3d06ee60), I get the test error, but it works when I build it within nixpkgs.

**Pull request merged**
