### PR TITLE
Ghc8 upper bounds

### PR DESCRIPTION
**Pull request by deepfire**
This deals with #12727 and #12728.

### CODE REVIEW

**Comment by peti** [comment]
`hackage-packages.nix` is a generated file and any changes you make here will be lost the next time it's re-generated. The proper way to make changes such as these is to add overrides in `pkgs/development/haskell-modules/configuration-ghc-8.0.x.nix`.

**Comment by deepfire** [comment]
..but I only see `pkgs/development/haskell-modules/configuration-ghc-8.0.x.nix` *referring* to package versions, not defining them, and in the case of `circle-packing` I need a new version -- 0.1.0.5 isn't defined in `hackage-packages.nix`...

**Comment by peti** [comment]
I've pushed an update to https://github.com/peti/nixpkgs/tree/haskell-updates. Once the test builds are through, I'l merge to `master`. Then the new version will  be there.

**Comment by deepfire** [comment]
Thank you! Closing this PR, then.

**Pull request closed without merging**
