### PR TITLE
hyprpicker: init at unstable-2022-11-06

### LINKED ISSUE #199913: hyprpicker (Wayland color picker)
**Project description**
A wlroots-compatible Wayland color picker that does not suck.

**Metadata**

* homepage URL: https://github.com/hyprwm/hyprpicker
* source URL: https://github.com/hyprwm/hyprpicker
* license: [BSD 3-clause "New" or "Revised" License](https://github.com/hyprwm/hyprpicker/blob/main/LICENSE)
* platforms: linux

Just because you made [hyprpaper](https://github.com/NixOS/nixpkgs/pull/180192) available on NixOS, I wanted to point you on hyprpicker, too - if you're interested to have a look into this(?)

@wozeparrot

### PR DESCRIPTION
**Pull request by wozeparrot**
###### Description of changes

Adds [hyprpicker](https://github.com/hyprwm/hyprpicker).
Closes #199913.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by revuwa** [comment]
Don't know if this helps in any way, but I tried:

-  git clone https://github.com/NixOS/nixpkgs.git && cd nixpkgs
- nixpkgs-review pr 199917
- ./results/hyprpicker/bin/hyprpicker

and the application works great, without any problems or errors. 👍

**Comment by teutat3s** [comment]
Result of `nixpkgs-review pr 199917` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>hyprpicker</li>
  </ul>
</details>

**Review by teutat3s — APPROVED** [review]

**Comment by dit7ya** [comment]
Is this only for Hyprland? I tried it on Sway and seems to do nothing?

**Comment by revuwa** [comment]
> Is this only for Hyprland? I tried it on Sway and seems to do nothing?

It's described as "wlroots-compatible Wayland color picker", so it >should< work outside of Hyprland 🤷
Sorry for the following question, but did you manually execute it from a terminal, (to get the result in it), or piped it to clipboard for that, e. g. with `hyprpicker | wl-copy`?

**Comment by felipeqq2** [comment]
I'm on Sway and it works just fine, both with direct terminal execution and `hyprpicker | wl-copy`.

**Comment by dit7ya** [comment]
`hyprpicker | wl-copy` works but running it from the terminal apparently prints nothing ?

**Comment by Mic92** [comment]
done in https://github.com/NixOS/nixpkgs/pull/221617

**Pull request closed without merging**
