### PR TITLE
element-web: export unwrapped

### PR DESCRIPTION
**Pull request by linsui**
###### Description of changes
https://github.com/NixOS/nixpkgs/pull/196885#issuecomment-1307834210
@ajs124 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by linsui** [comment]
Looks like it's still very difficult to override it...

**Comment by linsui** [comment]
Maybe this is better. Then users can use overrideAttrs with unwrappedConf. Not sure if this is a good idea.

**Comment by linsui** [comment]
I thought it's OK. But how to solve the override problem? Is there a smart method to make the unwrapped can be overrided?

**Comment by SuperSandro2000** [comment]
Move it out of the let in and make it a top-level package.

**Review by ajs124 — APPROVED** [review]
looks better IMO, but maybe we can get some input from the maintainers?

**Review by SuperSandro2000 — APPROVED** [review]
With this patch I could change my overwrites to target element-web-unwrapped and get everything back working

**Comment by linsui** [comment]
Kindly ping. Looks like the maintainers have no interests.

**Comment by Ma27** [comment]
> Looks like the maintainers have no interests

Please avoid these kinds of accusations in the future, thanks!

**Review by sumnerevans — APPROVED** [review]

**Pull request merged**
