### PR TITLE
miniaudicle: 1.4.2.0 -> 1.5.0.7

### PR DESCRIPTION
**Pull request by matthiasbeyer**
and qt4 -> qt6

(cherry picked from commit 29902fb475f4490696f9de202e24768e9cdc9ce1)

---

Extracted from #174634
because this can be PRed independently and can land earlier than the PR above.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
This needs (something like) 717d80c63e50100ee80428fa941e35b92650baad as a prerequisite

**Comment by fgaz** [comment]
Some tips from upstream https://github.com/ccrma/miniAudicle/issues/40#issuecomment-1598589194

**Review by fgaz — COMMENTED** [review]
> `ld: library not found for -lcups`

Darwin should be fixed or marked as broken

**Comment by matthiasbeyer** [comment]
I will add a patch for this later today or tomorrow, thanks for having a look!

**Comment by matthiasbeyer** [comment]
@fgaz umm... as far as I can see, darwin is marked as broken, is it not?

**Comment by fgaz** [comment]
@matthiasbeyer looks like it's qscintilla that's broken

**Comment by matthiasbeyer** [comment]
What would you have me do? As this is a backport from @ajs124 qt4 removal branch, I would ask them to investigate, if they find time...

**Comment by fgaz** [comment]
No need to find time now, you can just mark `qscintilla-qt6` as broken

**Comment by matthiasbeyer** [comment]
Well `qscintilla-qt6` is actually still `-qt5` because we should probably port https://github.com/NixOS/nixpkgs/pull/174634/commits/5ad8338b246da6c5b1e7abbc9b6e06cf25e39a6a over as well?

**Comment by fgaz** [comment]
Let's try

**Comment by matthiasbeyer** [comment]
CI is green so far. Should we let ofborg build the thing?

**Comment by ajs124** [comment]
https://github.com/NixOS/nixpkgs/pull/245408#issuecomment-1651655056

**Comment by fgaz** [comment]
Thanks for the heads-up @ajs124. I removed the qscintilla update and marked it as broken on darwin && qt6

**Review by fgaz — APPROVED** [review]
Thanks!

**Pull request merged**
