### PR TITLE
haskellPackages.squeal-postgresql: fix build, add myself as maintainer

### PR DESCRIPTION
**Pull request by erictapen**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
I have cherrypicked and resolved the conflict onto haskell-updates.

Interestingly in contrast to your commit message you have not added yourself as a maintainer in this PR. Can you please do that in a new PR?

**Comment by erictapen** [comment]
> Interestingly in contrast to your commit message you have not added yourself as a maintainer in this PR. Can you please do that in a new PR?

Didn't this do the job? https://github.com/NixOS/nixpkgs/pull/173163/files#diff-f03d404df9c59a2cbb7f6f902247841245c97c3c6ad9096006f8e84aec81c0c0R191

**Comment by cdepillabout** [comment]
@erictapen I think you need to regenerate the packages after adding yourself as a maintainer.  But the package set has been regenerated in the meantime, so no action should be required from you for this now:

This PR https://github.com/NixOS/nixpkgs/pull/173328, contains https://github.com/NixOS/nixpkgs/pull/173328/commits/6e028bd63297a2e49305d42d67b7be4c69c59c99, which has made its way into https://github.com/NixOS/nixpkgs/pull/172982.

**Comment by erictapen** [comment]
@cdepillabout I see, thanks!

**Pull request closed without merging**
