### PR TITLE
python37Packages.tasklib: 2.2.0 -> 2.2.1

### PR DESCRIPTION
**Pull request by Chickensoupwithrice**
###### Motivation for this change
Update tasklib to 2.2.1

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please remove the already merged commit from this PR.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 100497` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python27Packages.tasklib</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.tasklib</li>
    <li>python38Packages.tasklib</li>
    <li>vit</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
```
builder for '/nix/store/hwamy5r4ilgd9nkl2zm42wa38cqx8qm1-python2.7-tasklib-2.2.1.drv' failed with exit code 1; last 10 log lines:                                                                 self.module)                                                                                                                                                                              File "/nix/store/vfd4wghhzz4afzxgwynsnbj9xzpkib4z-python-2.7.18/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
      suites = [self.loadTestsFromName(name, module) for name in names]
    File "/nix/store/vfd4wghhzz4afzxgwynsnbj9xzpkib4z-python-2.7.18/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
      module = __import__('.'.join(parts_copy))
    File "/build/tasklib-2.2.1/tasklib/__init__.py", line 1, in <module>
      from .backends import TaskWarrior
    File "/build/tasklib-2.2.1/tasklib/backends.py", line 9, in <module>
      from functools import lru_cache
  ImportError: cannot import name lru_cache
cannot build derivation '/nix/store/piayl5bl8x7xp4qpzqz513dmgqn3v7jj-env.drv': 1 dependencies couldn't be built
```

**Comment by fabaff** [comment]
Was superseded by #108368.

**Pull request closed without merging**
