### PR TITLE
poetry: apply toPythonApplication

### PR DESCRIPTION
**Pull request by aaronjheng**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
What's the motivation?

**Comment by aaronjheng** [comment]
Poetry should be installed as an application, not just a library.

**Comment by Artturin** [comment]
> Poetry should be installed as an application, not just a library.

why is this necessary?
diffoscope doesn't show a difference between before and after this pr

```
A distinction is made between applications and libraries, however, sometimes a
package is used as both. In this case the package is added as a library to
`python-packages.nix` and as an application to `all-packages.nix`. To reduce
duplication the `toPythonApplication` can be used to convert a library to an
application.
```

this is poetry is built with `poetry2nix.mkPoetryApplication` and therefore it is not necessary to use `toPythonApplication`

**Comment by aaronjheng** [comment]
Practically they are same.

> The buildPythonApplication function is practically the same as buildPythonPackage. The main purpose of this function is to build a Python package where one is interested only in the executables, and not importable modules. For that reason, when adding this package to a python.buildEnv, the modules won’t be made available. Another difference is that buildPythonPackage by default prefixes the names of the packages with the version of the interpreter. Because this is irrelevant for applications, the prefix is omitted.

Internally, `mkPoetryApplication` use `buildPythonPackage` which makes `poetry` a library. So I add the `toPythonApplication` function to convert the library to an application in the top-level package collection.

**Comment by cpcloud** [comment]
This PR breaks downstream `poetry2nix` usage involving some of the `mkdocs-*` plugin packages.

Can we revert this change? It doesn't seem necessary.

**Comment by cpcloud** [comment]
Here's a minimal reproducible example: https://github.com/cpcloud/nixpkgs-toapp-poetry-repro

**Comment by cpcloud** [comment]
cc @adisbladis

**Comment by aaronjheng** [comment]
@cpcloud Sorry for the trouble. I should have thought things through. I will try something else.

**Comment by cpcloud** [comment]
No worries!

**Pull request merged**
