### PR TITLE
configuration-ghc-9.2.x.nix: overrides

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Motivation for this change

Various updates for GHC 9.2 that I am finding in the process of working on https://github.com/gibiansky/IHaskell/pull/1283.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Hmm, I'm having trouble building `integer-logarithms` because it's not finding `ghc-bignum` as a dependency. I see that it's set to `null` in `configuration-ghc-9.2.x.nix`, however it is also set to null in `configuration-ghc-9.0.x.nix` and that seems to work just fine. Any pointers?

**Comment by sternenseemann** [comment]
> Hmm, I'm having trouble building `integer-logarithms` because it's not finding `ghc-bignum` as a dependency. I see that it's set to `null` in `configuration-ghc-9.2.x.nix`, however it is also set to null in `configuration-ghc-9.0.x.nix` and that seems to work just fine. Any pointers?

ghc-bignum should be bundled with with ghc, try checking `ghc-pkg list` in a nix shell with `haskell.compiler.ghc921`.

**Comment by vaibhavsagar** [comment]
Fixed now, thank you for your help @sternenseemann!

**Comment by vaibhavsagar** [comment]
I think I've reached a good stopping point here. There's an issue with `alex` that doesn't seem to have a corresponding `head.hackage` patch for it, so I'll have to make a separate PR if I can fix that. This is ready to review.

**Comment by sternenseemann** [comment]
@ofborg eval

**Comment by sternenseemann** [comment]
Rebased your PR with an additional fix on `haskell-updates` (eval should now be clean). Will look into packages we could test for GHC 9.2.1 on Hydra tomorrow, so we'll start getting CI (and binary cache) for the 9.2.1 set.

**Comment by sternenseemann** [comment]
Cherry-picked your commit with a small change to the commit message as e0ac27c6042622e0bb880818a22d509c45f39523.

**Comment by vaibhavsagar** [comment]
Thanks!

**Pull request closed without merging**
