### PR TITLE
idrisPackages.data: remove broken package at 2018-03-19

### PR DESCRIPTION
**Pull request by divanorama**
Package doesn't compile (same error locally on x86_65 NixOS)
https://hydra.nixos.org/build/142422494/nixlog/2
And the repository is archived with latest commits being in 2019
https://github.com/jdevuyst/dependable-data-structures

Doesn't seem to be used by any other packages

ZHF: #122042

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
please also remove the refernce to this file pkgs/development/idris-modules/data.nix': No such file or directory

```
pkgs/development/idris-modules/default.nix
78:    data = callPackage ./data.nix {};
```

**Comment by jonringer** [comment]
cc some idris people @veprbl

**Comment by veprbl** [comment]
cc @brainrape as maintainer

**Comment by brainrape** [comment]
Ok by me. Idris2 is out so Idris1 packages will all be removed or migrated soon.

**Pull request merged**
