### PR TITLE
gnomeExtensions: count naming collisions only for the last three shell versions

### LINKED ISSUE #310277: Package request: Gnome Extension - OpenWeather Refined
**Project description**

Display weather for the current or a specified location. Fork of OpenWeather. Needed as open weather isn't supported on Gnome 46.

**Metadata**

* homepage URL: https://extensions.gnome.org/extension/6655/openweather/
* source URL: https://github.com/penguin-teal/gnome-openweather
* license: GPL-3.0
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by honnip**
## Description of changes
~I will split the pull request if necessary.~ https://github.com/NixOS/nixpkgs/pull/315046

Currently, pname collisions are counted for each shell version. But `gnomeExtensions` has the extensions for the last three shell version (44, 45, 46), so there are missing collisions. 
e.g. `openweather-extension@penguin-teal.github.io` supports 45~ while `openweather-extension@jenslody.de` supports ~44 

Closes https://github.com/NixOS/nixpkgs/issues/310277, https://github.com/NixOS/nixpkgs/issues/282642 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by honnip** [comment]
I have noticed some extensions name have changed with this PR:
- `gnomeExtensions.floating-dock-2` -> `gnomeExtensions.floating-dock`
- `gnomeExtensions.true-color-window-invert` -> `gnomeExtensions.true-color-invert`
- `gnomeExtensions.volume-scroller-2` -> `gnomeExtensions.volume-scroller`
- maybe more

These are extensions that were previously renamed due to collisions, but don't need to be renamed now. Should we keep them changed?

**Comment by honnip** [comment]
@ofborg build nixosTests.gnome-extensions

**Comment by jtojnar** [comment]
> Currently, pname collisions are counted for each shell version. But `gnomeExtensions` has the extensions for the last three shell version (44, 45, 46), so there are missing collisions.
> e.g. `openweather-extension@penguin-teal.github.io` supports 45~ while `openweather-extension@jenslody.de` supports ~44

Sounds good, we probably do not want the extensions to switch willy-nilly between versions – there is no guarantee that the extension is not something completely different.

> These are extensions that were previously renamed due to collisions, but don't need to be renamed now. Should we keep them changed?

The best practice for renames is adding an alias first and then replacing it with a `throw` in the next cycle (see the aliases section in `default.nix`).

---

Also be aware that the extensions are unmaintained at the moment. If you are interested in them, might be a good idea to add yourself.

**Review by jtojnar — COMMENTED** [review]
Changes looks okay at a glance, the aliases would be nice.

**Comment by jtojnar** [comment]
Backport to allow auto-backporting future updates.

**Comment by honnip** [comment]
> The best practice for renames is adding an alias first and then replacing it with a throw in the next cycle (see the aliases section in default.nix).

Can the newer extension (e.g. `floating-dock-2`) use the name that the older extension used (e.g. `floating-dock`)?

Edit: ah I noticed that `floating-dock` and `floating-dock-2` are completely different extension, I guess it would be better to use the name it was.

**Comment by jtojnar** [comment]
> Edit: ah I noticed that `floating-dock` and `floating-dock-2` are completely different extension, I guess it would be better to use the name it was.

Well, in this case, there was no `gnomeExtensions.floating-dock` so renaming it to a shorter name would not be a problem, as long the old alias was kept.

**Review by jtojnar — APPROVED** [review]
The general idea sounds reasonable to me.

I only checked that the attributes mentioned in https://github.com/NixOS/nixpkgs/pull/314893#issuecomment-2132515487 continue to exist and that [kernel-indicator](https://extensions.gnome.org/extension/2512/kernel-indicator/) replacement makes sense.

**Comment by jtojnar** [comment]
Maybe cc @rhoriguchi, since they were interested in GNOME extensions in the past.

**Comment by honnip** [comment]
I'm about to serve in the country's military, but I think I can maintain it for at least a few months anyway

**Comment by jtojnar** [comment]
Good luck.

> I wanted to minimise the changes caused by this PR as much as possible. (and also because this will be backported)

:+1:

**Comment by SebTM** [comment]
Result of `nixpkgs-review pr 314893` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>69 packages built:</summary>
  <ul>
    <li>gnomeExtensions.alphatint</li>
    <li>gnomeExtensions.alternate-menu-for-hplip2</li>
    <li>gnomeExtensions.always-show-titles-in-overview</li>
    <li>gnomeExtensions.another-window-session-manager</li>
    <li>gnomeExtensions.applications-menu</li>
    <li>gnomeExtensions.athantimes</li>
    <li>gnomeExtensions.auto-move-windows</li>
    <li>gnomeExtensions.better-end-session-dialog</li>
    <li>gnomeExtensions.boost-volume</li>
    <li>gnomeExtensions.clipqr</li>
    <li>gnomeExtensions.crypto-price-tracker</li>
    <li>gnomeExtensions.custom-command-list</li>
    <li>gnomeExtensions.custom-command-toggle</li>
    <li>gnomeExtensions.custom-window-controls</li>
    <li>gnomeExtensions.desktop-cube</li>
    <li>gnomeExtensions.dev-tools</li>
    <li>gnomeExtensions.duckduckgo-search-provider</li>
    <li>gnomeExtensions.fedora-linux-update-indicator</li>
    <li>gnomeExtensions.forge</li>
    <li>gnomeExtensions.fullscreen-button</li>
    <li>gnomeExtensions.github-actions</li>
    <li>gnomeExtensions.gravatar</li>
    <li>gnomeExtensions.gsnap</li>
    <li>gnomeExtensions.kernel-indicator</li>
    <li>gnomeExtensions.keyboard-reset</li>
    <li>gnomeExtensions.launch-new-instance</li>
    <li>gnomeExtensions.light-style</li>
    <li>gnomeExtensions.luminus-desktop</li>
    <li>gnomeExtensions.luminus-shell</li>
    <li>gnomeExtensions.luminus-shell-y</li>
    <li>gnomeExtensions.media-progress</li>
    <li>gnomeExtensions.native-window-placement</li>
    <li>gnomeExtensions.night-light-slider-updated</li>
    <li>gnomeExtensions.openweather-refined</li>
    <li>gnomeExtensions.overview-hover</li>
    <li>gnomeExtensions.paperwm</li>
    <li>gnomeExtensions.places-status-indicator</li>
    <li>gnomeExtensions.printers</li>
    <li>gnomeExtensions.quick-lofi</li>
    <li>gnomeExtensions.quick-settings-audio-panel</li>
    <li>gnomeExtensions.quick-text</li>
    <li>gnomeExtensions.reminder-alarm-clock</li>
    <li>gnomeExtensions.removable-drive-menu</li>
    <li>gnomeExtensions.rezmon</li>
    <li>gnomeExtensions.screenshot-window-sizer</li>
    <li>gnomeExtensions.search-light</li>
    <li>gnomeExtensions.set-monitor-ddc-brightnesscontrast-extra-dimming</li>
    <li>gnomeExtensions.simple-break-reminder</li>
    <li>gnomeExtensions.somafm-internet-radio</li>
    <li>gnomeExtensions.space-bar</li>
    <li>gnomeExtensions.start-overlay-in-application-view</li>
    <li>gnomeExtensions.strings</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>gnomeExtensions.system-monitor-2</li>
    <li>gnomeExtensions.systemd-status</li>
    <li>gnomeExtensions.thinkpad-battery-threshold</li>
    <li>gnomeExtensions.tweaks-in-system-menu</li>
    <li>gnomeExtensions.usd-try</li>
    <li>gnomeExtensions.user-themes</li>
    <li>gnomeExtensions.vertical-workspaces</li>
    <li>gnomeExtensions.vim-alt-tab</li>
    <li>gnomeExtensions.vscode-search-provider</li>
    <li>gnomeExtensions.window-list</li>
    <li>gnomeExtensions.window-on-top</li>
    <li>gnomeExtensions.windownavigator</li>
    <li>gnomeExtensions.wintile-beyond</li>
    <li>gnomeExtensions.worksets</li>
    <li>gnomeExtensions.workspace-indicator</li>
    <li>gnomeExtensions.workspaces-indicator-by-open-apps</li>
  </ul>
</details>

**Review by SebTM — APPROVED** [review]
Did nixpkgs-review and checked out code tested update-script - change makes sense to me and looks overall good but didn't go into details 👍🏻

**Comment by jtojnar** [comment]
Thanks.

**Comment by SuperSandro2000** [comment]
Can someone backport this please manually? Based on feedback in Matrix

**Pull request merged**
