### PR TITLE
todoist-electron: 8.9.3 -> 8.10.1

### PR DESCRIPTION
**Pull request by pokon548**
## Description of changes
Update todoist-electron to 8.10.1. Also resolved pname issue mentioned here: https://github.com/NixOS/nixpkgs/issues/267508

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bjornfor — COMMENTED** [review]
I think it would be good to split the commit in two:
1. bugfix with pname, ref the issue
2. version bump.

**Comment by sersorrel** [comment]
I get a build failure:

```
error: builder for '/nix/store/vk5lrg3yizbvgpx19bfn0w07rhkakixj-todoist-electron.drv' failed with exit code 1;
       last 2 log lines:
       > mv: missing destination file operand after '/nix/store/qlrag7vpjadv6b1lkgb32dm95km3bzdj-todoist-electron/bin/todoist-electron'
       > Try 'mv --help' for more information.
       For full logs, run 'nix log /nix/store/vk5lrg3yizbvgpx19bfn0w07rhkakixj-todoist-electron.drv'.
error: 1 dependencies of derivation '/nix/store/gw15951bhwg9l2cj88sv959bnqzhmdww-review-shell.drv' failed to build
```

but the pname thing does appear to be fixed, thanks :)

I found #262506 in the meantime which seems like it might fix the underlying problem.

**Comment by pokon548** [comment]
> I get a build failure:
> 
> ```
> error: builder for '/nix/store/vk5lrg3yizbvgpx19bfn0w07rhkakixj-todoist-electron.drv' failed with exit code 1;
>        last 2 log lines:
>        > mv: missing destination file operand after '/nix/store/qlrag7vpjadv6b1lkgb32dm95km3bzdj-todoist-electron/bin/todoist-electron'
>        > Try 'mv --help' for more information.
>        For full logs, run 'nix log /nix/store/vk5lrg3yizbvgpx19bfn0w07rhkakixj-todoist-electron.drv'.
> error: 1 dependencies of derivation '/nix/store/gw15951bhwg9l2cj88sv959bnqzhmdww-review-shell.drv' failed to build
> ```
> 
> but the pname thing does appear to be fixed, thanks :)
> 
> I found #262506 in the meantime which seems like it might fix the underlying problem.

Fixed in latest push :)
By the way, I think the root cause is ```wrapAppImage```: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/appimage/default.nix#L41-L47, which will define `name` as `pname-version`.

**Review by keysmashes — APPROVED** [review]
Result of `nixpkgs-review pr 267602` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>todoist-electron</li>
  </ul>
</details>

**Review by kylesferrazza — APPROVED** [review]

**Comment by pokon548** [comment]
@pbsds I believe these changes are intended? Because we would like to leave the package name static, so you can easily add this package to ```nixpkgs.config.allowUnfreePredicate``` without breaking changes from every updates. See https://github.com/NixOS/nixpkgs/issues/267508 for more context.

**Comment by pbsds** [comment]
I think fixing the problem at the root is better, see #271071

**Pull request merged**
