### PR TITLE
itk: Adds RTK remote crate

### PR DESCRIPTION
**Pull request by purepani**
## Things done
ITK has a bunch of remote modules that can be used. This one enables RTK, which includes ct reconstruction. I haven't attempted adding more of them yet because this is the only one I need at the moment, but if I have time, they could be added. It might be better to get this merged first though.

As far as I can tell, building this module separately from itk is possible, but installing it is not supported: 3
https://github.com/RTKConsortium/RTK/blob/master/INSTALLATION.md

I have built it but haven't tested it yet(I am about to do so though).

Pinging @bcdarwin as a maintainer of this package.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by purepani** [comment]
My bad i forgot to rebase

**Review by bcdarwin — COMMENTED** [review]
Definitely a useful module to enable.

Some formatting nits:
 - please consider renaming to `rtkSrc` to match the other fixed-output derivations in this expression
 - please move to above `swigUnstable` next to the other fixed-output derivations and add an extra linebreak (unfortunately `nixfmt` doesn't deal with this)

**Comment by purepani** [comment]
Should be good now @bcdarwin!

**Review by bcdarwin — APPROVED** [review]
LGTM, thanks.

**Comment by purepani** [comment]
Hey @bcdarwin what else needs to be done to merge this? (I'm fine with waiting, but it's been a while since I contributed so I don't know if I need to get someone else or if it's in a pipeline somewhere to get merged)

**Comment by bcdarwin** [comment]
> Hey @bcdarwin what else needs to be done to merge this? (I'm fine with waiting, but it's been a while since I contributed so I don't know if I need to get someone else or if it's in a pipeline somewhere to get merged)

Nothing, someone with the commit bit just needs to see and merge it.

(But also see https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#practical-contributing-advice.)

**Pull request merged**
