### PR TITLE
blaze: darwin support

### PR DESCRIPTION
**Pull request by matteo-pacini**
## Description of changes

Compiles fine on Darwin without modifications.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matteo-pacini** [comment]
Result of `nixpkgs-review pr 322251` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>blaze</li>
  </ul>
</details>

**Comment by afh** [comment]
Result of `nixpkgs-review pr 322251` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>blaze</li>
  </ul>
</details>

**Review by afh — APPROVED** [review]
Thanks for this, @matteo-pacini 👍

**Comment by afh** [comment]
Thanks for merging this, @Aleksanaa, much appreciated 👍

**Comment by emilazy** [comment]
Anyone have any interest in a treewide sweep where we set `platforms.linux = platforms.unix` and migrate everything that builds on Darwin and doesn’t seem to be an obvious error? I run into overly‐conservative platform specifiers a lot and it’s a non‐trivial (but trivial) factor holding back macOS package availability.

**Comment by afh** [comment]
🙋 Happy to collaborate, @emilazy. Yet it seems this requires quite a bit of computing resources.

**Comment by emilazy** [comment]
Yes, that’s the bottleneck :) We would either need to find someone with a Mac Studio or two they’re not really using, or see if we can get some Hydra slots to slowly churn away at the endeavour. And it’s a little bit sad that a significant fraction of those CPU cycles will probably go towards builds that were doomed from the start, of course. But the end result would be nice.

Are you in the Nix on macOS Matrix room?

**Comment by matteo-pacini** [comment]
Happy to collaborate as well, I'm on Matrix.

**Pull request merged**
