### PR TITLE
python3Packages.python-igraph: 0.9.4 -> 0.9.6

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/igraph/python-igraph/blob/0.9.5/CHANGELOG.md

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126588` at fa4172e4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>python38Packages.scikit-tda</li>
  </ul>
</details>
<details>
  <summary>15 packages built successfully:</summary>
  <ul>
    <li>python38Packages.cozy</li>
    <li>python38Packages.explorerscript</li>
    <li>python38Packages.kmapper</li>
    <li>python38Packages.python-igraph</li>
    <li>python38Packages.skytemple-dtef</li>
    <li>python38Packages.skytemple-files</li>
    <li>python38Packages.skytemple-ssb-debugger</li>
    <li>python39Packages.cozy</li>
    <li>python39Packages.explorerscript</li>
    <li>python39Packages.kmapper</li>
    <li>python39Packages.python-igraph</li>
    <li>python39Packages.skytemple-dtef</li>
    <li>python39Packages.skytemple-files</li>
    <li>python39Packages.skytemple-ssb-debugger</li>
    <li>skytemple</li>
  </ul>
</details>

**Comment by risicle** [comment]
`nixpkgs-review` reports no new failures on macos 10.15

**Review by risicle — APPROVED** [review]
Same for nixos x86_64.

**Comment by risicle** [comment]
Damnit making me rebuild tensorflow again...

**Comment by dotlambda** [comment]
> Damnit making me rebuild tensorflow again...

The changes are so minimal that I don't think there's a need to.

**Comment by risicle** [comment]
Yup ok fair enough, my approval still stands.

**Pull request merged**
