### PR TITLE
tree-sitter: add org grammar

### PR DESCRIPTION
**Pull request by michaeladler**
this will soon be a dependency of orgmode.nvim; currently, it is an
optional dependency.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
excited about this but worried that it appears as an official "org" parser while it targets neovim in the description.
maybe `tree-sitter-org-nvim` would leave future options more open ?

**Comment by michaeladler** [comment]
@teto That's a good idea and I agree with you. However, when I tried it, I get an error in nvim that the 'org' parser could not be found. I don't know why and it seems strange because my understanding is that calling the parser org-nvim is purely a NixOS-thing (i.e. it boils down to a directory name and does not affect the generated parser).

**Comment by teto** [comment]
nvim-treesitter/nvim expects a parser with the filetype as name IIRC so you may need to check the installed shared library has the correct name.
maybe check pkgs/development/tools/parsing/tree-sitter/default.nix  `location = if grammar ? location then grammar.location else null;` ?

**Comment by michaeladler** [comment]
> nvim-treesitter/nvim expects a parser with the filetype as name

Yes, that's it. I was just confused because the output of the tree-sitter grammar is a file called `parser` (which is actually a shared lib). That file is then symlinked into nvim-treesitters directory and the filename of the *symlink* is used to register the parser under the appropriate name.

Now this leaves us at the same problem as before: let's say someone comes up with another org parser and we'd like to use it in neovim as well. If we want to make orgmode.nvim work, we have to call the orgmode.nvim parser `org.so`, so that name has already been taken and we cannot use it for our hypothetical org parser.

So I think if we want to use a different name for the org nvim parser, we either have to rename it upstream or patch orgmode.nvim. What do you think? Am I missing something?

**Comment by teto** [comment]
Conflicitng filenames can be solved in nix by setting priorities (look for lowPrio) for instance. So that's a non-issue. I mean even if you were not using nix, one would have to choose wich parser to use for org.

**Comment by michaeladler** [comment]
Alright, I think I have found a working solution, see my latest update.

**Comment by asymmetric** [comment]
Closed by #154350?

**Comment by asymmetric** [comment]
I'm going to close this as fixed by the above, feel free to reopen.

**Pull request closed without merging**
