### PR TITLE
[staging-next] libreoffice*: update and fix build

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change

`libreoffice*` currently [failed to build on `staging-next`](https://hydra.nixos.org/eval/1721332?filter=libreoffice&compare=1721074&full=#tabs-still-fail) due to the update of `icu` and `bison`.
This PR bumps `libreoffice-still` to include the patch for new `bison`, and uses `icu69` for both `-still` and `-fresh`.

ZHF: #144627
Related: #144730

cc @7c6f434c 

Thanks for @NickCao providing the build machine.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
I started a build on my amd epyc...

**Comment by Mic92** [comment]
```
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/joerg/.cache/nixpkgs-review/pr-145589/build.nix
error: builder for '/nix/store/m0j5f0lsvm2vg7lc1as5vx98q0f7g169-libreoffice-7.2.2.2.drv' failed with exit code 2;
       last 10 log lines:
       >     # for exception catching
       >
       > You can limit the execution to just one particular test by:
       >
       > [CUT] package2_test
       > make CPPUNIT_TEST_NAME="testXYZ" ...above mentioned params...
       >
       > make[1]: *** [/build/libreoffice-7.2.2.2/solenv/gbuild/CppunitTest.mk:125: /build/libreoffice-7.2.2.2/workdir/CppunitTest/i18npool_test_breakiterator.test] Error 1
       > make[1]: *** Waiting for unfinished jobs....
       > make: *** [Makefile:289: build] Error 2
       For full logs, run 'nix log /nix/store/m0j5f0lsvm2vg7lc1as5vx98q0f7g169-libreoffice-7.2.2.2.drv'.
error: 1 dependencies of derivation '/nix/store/ksr4d26bnjsqc3ndq0vgajrfpqhkkcd5-libreoffice-7.2.2.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vmi2xrvgjrlc1zs2d2k9i8aqyn2a4m9k-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/145589

1 package marked as broken and skipped:
odpdown

1 package failed to build:
libreoffice-qt

5 packages built:
libreoffice libreoffice-fresh libreoffice-fresh-unwrapped libreoffice-unwrapped unoconv

error: build log of '/nix/store/hr85020dz0bdb2mcvxdawzjm5gy0l5f6-libreoffice-7.1.7.2.drv' is not available
error: build log of '/nix/store/8lix29rxkbzmsl86y3dwn3b9xfafgslj-libreoffice-7.1.7.2' is not available
error: build log of '/nix/store/pws6gc8mc3wzzrcf5fbs1pgc022bjy71-libreoffice-7.2.2.2.drv' is not available
error: build log of '/nix/store/6aifavk025lr9zbrzrwvnbjjz7hkgyzd-libreoffice-7.2.2.2' is not available
```

**Comment by Mic92** [comment]
Is `libreoffice-qt` known to be broken?

**Comment by Mic92** [comment]
Here is the test failure for libreoffice-qt:

```
[_RUN_____] TestBreakIterator::testLineBreaking
TestBreakIterator::testLineBreaking finished in: 1ms
[_RUN_____] TestBreakIterator::testWordBoundaries
TestBreakIterator::testWordBoundaries finished in: 5ms
[_RUN_____] TestBreakIterator::testGraphemeIteration
TestBreakIterator::testGraphemeIteration finished in: 0ms
[_RUN_____] TestBreakIterator::testWeak
TestBreakIterator::testWeak finished in: 0ms
[_RUN_____] TestBreakIterator::testAsian
TestBreakIterator::testAsian finished in: 0ms
[_RUN_____] TestBreakIterator::testThai
TestBreakIterator::testThai finished in: 1ms
[_RUN_____] TestBreakIterator::testLao
/build/libreoffice-7.2.2.2/i18npool/qa/cppunit/test_breakiterator.cxx:865:TestBreakIterator::testLao
equality assertion failed
- Expected: 9
- Actual  : 12

TestBreakIterator::testLao finished in: 1ms
[_RUN_____] TestBreakIterator::testJapanese
TestBreakIterator::testJapanese finished in: 0ms
[_RUN_____] TestBreakIterator::testChinese
TestBreakIterator::testChinese finished in: 0ms
test_breakiterator.cxx:865:Assertion
Test name: TestBreakIterator::testLao
equality assertion failed
- Expected: 9
- Actual  : 12

Failures !!!
Run: 9   Failure total: 1   Failures: 1   Errors: 0
[CUT] package2_test

Error: a unit test failed, please do one of:

make CppunitTest_i18npool_test_breakiterator CPPUNITTRACE="gdb --args"
    # for interactive debugging on Linux
make CppunitTest_i18npool_test_breakiterator VALGRIND=memcheck
    # for memory checking
make CppunitTest_i18npool_test_breakiterator DEBUGCPPUNIT=TRUE
    # for exception catching

You can limit the execution to just one particular test by:

make CPPUNIT_TEST_NAME="testXYZ" ...above mentioned params...

```

**Comment by oxalica** [comment]
> Here is the test failure for libreoffice-qt:

That's the exact same error as `libreoffice-fresh` without `icu = icu69`. Does the override somehow ignored for `libreoffice-qt`?

**Comment by Mic92** [comment]
I think `libreoffice-qt` also needs the same override. Would it not be better to have icu69 being used inside the the libreoffice package rather than having it for all variants overridden in `all-packages.nix?`

**Comment by oxalica** [comment]
It's more complicated than I think. And `qtx11extras` is a static library which exposes `-L/path/to/icu70` flag in `.la` files, causing `libreoffice` links to `icu70`. I'm kind of worrying that if version mismatch between dependencies would cause more issues.

The failed test is [here](https://github.com/LibreOffice/core/blob/master/i18npool/qa/cppunit/test_breakiterator.cxx#L842-L860). But I'm not familiar with `icu` and can't read Lao.
I'm now trying to patch it to skip `testLao` and build it with `icu70`.

**Comment by oxalica** [comment]
For anyone concerned, I've posted the issue to the upstream mail list,
https://lists.freedesktop.org/archives/libreoffice/2021-November/088044.html

**Pull request merged**
