### PR TITLE
 {gcal,git-cola}: set meta.mainProgram 

### PR DESCRIPTION
**Pull request by thiagokokada**
## Description of changes

Just a PR setting `meta.mainProgram` for 2 packages that I use in my configuration and are missing it.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by NotAShelf — APPROVED** [review]

**Review by superherointj — APPROVED** [review]

**Review by lucasew — APPROVED** [review]

**Review by Aleksanaa — APPROVED** [review]

**Review by znaniye — APPROVED** [review]

**Review by PedroHLC — APPROVED** [review]

**Comment by Aleksanaa** [comment]
Okay let's stop on that

**Review by JohnRTitor — APPROVED** [review]
Borgy eval fast!

**Review by bclaud — APPROVED** [review]

**Review by sachinchaudhary1808 — APPROVED** [review]

**Review by itslychee — APPROVED** [review]

**Review by AndersonTorres — APPROVED** [review]

**Review by viperML — APPROVED** [review]

**Comment by Sakooooo** [comment]
Sakooooo approved these changes 1 minute ago

**Review by Pandapip1 — APPROVED** [review]

**Review by s0me1newithhand7s — APPROVED** [review]

**Comment by NotAShelf** [comment]
I think we're looking at a new record here...

**Comment by Pandapip1** [comment]
I think we need a new label for 10+ or 15+ approvals

**Comment by sachinchaudhary1808** [comment]
yeah github spamming me with emails..

**Comment by Sakooooo** [comment]
> I think we're looking at a new record here...
```

>One line pr
>look inside
>record-breaking approval count

```

**Comment by JohnRTitor** [comment]
On another note we already have `awaiting_merger` and `needs_merger` is kind of redundant. Can we remove any of the two? @Mic92

**Comment by thiagokokada** [comment]
It would be so funny if this PR had a typo or something.

**Comment by Mic92** [comment]
> On another note we already have `awaiting_merger` and `needs_merger` is kind of redundant. Can we remove any of the two? @Mic92 

We can drop both. I think they are leftover artifacts from the Marvin review bot.

**Review by Mic92 — APPROVED** [review]

**Review by NobbZ — APPROVED** [review]

**Comment by Aleksanaa** [comment]
Yes,

image

But

image

**Comment by JohnRTitor** [comment]
> We can drop both. I think they are leftover artifacts from the Marvin review bot.

I personally think they are pretty useful for me as a commiter to find PRs that have been approved but stale for a while, or have a urgency to get merged.

If a PR has been ready but stale for a while, the tag can be used to indicate it needs attention. 

(We do have `approvals: x` but still `needs_merger` is pretty useful)

**Comment by superherointj** [comment]
@Aleksanaa This explains why wasn't merged... only approved. Also, we all tested with `nixpkgs-review` + `nix run`, riiiiight? ;-)

**Review by Guanran928 — APPROVED** [review]

**Comment by thiagokokada** [comment]
> @Aleksanaa This explains why wasn't merged... only approved. Also, we all tested with `nixpkgs-review` + `nix run`, riiiiight? ;-)

`nixpkgs-review` is not really useful for `meta` changes. Generally just doing eval (e.g.: `ofborg-eval`) is sufficient.

**Comment by JohnRTitor** [comment]
All of us did! 

> `nixpkgs-review` is not really useful for `meta` changes. Generally just doing eval (e.g.: `ofborg-eval`) is sufficient.

r/whooosh

**Comment by superherointj** [comment]
> `nixpkgs-review` is not really useful for `meta` changes. Generally just doing eval (e.g.: `ofborg-eval`) is sufficient.

It's useful for downloading the branch in a easily manner. I have an alias for that, quite handy. That's what I meant.

**Review by isabelroses — APPROVED** [review]

**Comment by Aleksanaa** [comment]
The party is over

**Comment by JohnRTitor** [comment]
Not quite yet.

**Pull request merged**
