### PR TITLE
electron_{11,12,13,14}: updates

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
- electron_11: 11.4.12 -> 11.5.0
- electron_12: 12.0.18 -> 12.1.0
- electron_13: 13.2.3 -> 13.3.0
- electron_14: init at 14.0.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 136531` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>deltachat-desktop (deltachat-electron)</li>
    <li>electron (electron_13)</li>
    <li>electron_11</li>
    <li>electron_12</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>etcher</li>
    <li>freetube</li>
    <li>jitsi-meet-electron</li>
    <li>logseq</li>
    <li>nix-tour</li>
    <li>obsidian</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>todoist-electron</li>
    <li>uivonim</li>
    <li>vieb</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 136531` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>deltachat-desktop (deltachat-electron)</li>
    <li>electron (electron_13)</li>
    <li>electron_11</li>
    <li>electron_12</li>
    <li>electron_14</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>etcher</li>
    <li>freetube</li>
    <li>jitsi-meet-electron</li>
    <li>logseq</li>
    <li>nix-tour</li>
    <li>obsidian</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>todoist-electron</li>
    <li>uivonim</li>
    <li>vieb</li>
  </ul>
</details>

**Review by TredwellGit — CHANGES_REQUESTED** [review]
`electron = electron_14;` should be set in `pkgs/development/tools/electron/default.nix`. `element-desktop` should be pinned to `electron_13`.

**Comment by lovesegfault** [comment]
> `electron = electron_14;` should be set in `pkgs/development/tools/electron/default.nix`. `element-desktop` should be pinned to `electron_13`.

Done!

**Review by TredwellGit — APPROVED** [review]

**Comment by prusnak** [comment]
Backport to stable in https://github.com/NixOS/nixpkgs/pull/136676

**Pull request merged**
