### PR TITLE
[20.03] Gnome 3.34 updates (the sequel)

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
I have:
* ran `update.nix`
* excluded updates that didn't make sense
* did one's outside the version bound that did make sense
* did backports from master where possible

I haven't built anything, not sure if I should split this into a `staging-20.03` PR and a `release-20.03` PR.

---

This is a re-PR of https://github.com/NixOS/nixpkgs/pull/85974, but on a gnome-20.03 branch in nixpkgs because I need a hydra jobset.

https://hydra.nixos.org/jobset/nixpkgs/gnome-stable#tabs-evaluations

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
I've had @grahamc (our hero) setup a hydra jobset for this https://hydra.nixos.org/jobset/nixpkgs/gnome-stable#tabs-configuration. We should be able to get updates going for gnome on stable branches with some regularity if you target the branch `gnome-20.03`

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build gtk3

(hydra is doing something weird with the darwin build of gtk3, here to confirm)

**Comment by worldofpeace** [comment]
@ofborg build gtk3

**Review by jtojnar — APPROVED** [review]
Looking at the commits I would expect this to be fine, but I have already garbage collected the previous cycle from my mind. I would be wary of GTK update but the changelog looks okay except for Wayland bump (not an issue) and graphical changes (might break layout of some apps). GLib and GOM changes look okay too.

**Comment by worldofpeace** [comment]
> Looking at the commits I would expect this to be fine, but I have already garbage collected the previous cycle from my mind. I would be wary of GTK update but the changelog looks okay except for Wayland bump (not an issue) and graphical changes (might break layout of some apps). GLib and GOM changes look okay too.

Thanks, I think I'm going to go for it. Hopefully without a hitch :crossed_fingers:

**Pull request merged**
