### PR TITLE
python3Packages.xknx: 0.18.5 -> 0.18.7

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.18.6

Change log: https://github.com/XKNX/xknx/releases/tag/0.18.6

- Related Home Assistant change: https://github.com/home-assistant/core/pull/51758
- Target Home Assistant release: current (only dependency update, no code changes)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126666` at 60a02255 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.xknx</li>
    <li>python39Packages.xknx</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 126666` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.xknx</li>
    <li>python39Packages.xknx</li>
  </ul>
</details>

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/269qfdl1bs0glqhkaz6miqzjvn39q3sb-python3.9-xknx-0.18.6.drv' failed with exit code 1; last 10 log lines:
          assert binaryinput.state
          await asyncio.sleep(reset_after_sec * 1.2)
  >       assert not binaryinput.state
  E       assert not True
  E        +  where True = <xknx.devices.binary_sensor.BinarySensor object at 0x10c6800a0>.state
  
  test/devices_tests/binary_sensor_test.py:95: AssertionError
  =========================== short test summary info ============================
  FAILED test/devices_tests/binary_sensor_test.py::TestBinarySensor::test_process_reset_after
  ======================= 1 failed, 1639 passed in 11.94s ========================
```

**Comment by risicle** [comment]
On nixos x86_64:

```
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
builder for '/nix/store/pfkzxsvwz7qk2bvszvjm6chxgpm6y014-homeassistant-2021.6.3.drv' failed with exit code 1; last 10 log lines:
  tests/components/shell_command/test_init.py::test_do_no_run_forever[pyloop]
    /nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9/lib/python3.8/asyncio/unix_events.py:917: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
      warnings.warn(

  -- Docs: https://docs.pytest.org/en/stable/warnings.html
  =========================== short test summary info ============================
  FAILED tests/components/hue/test_sensor_base.py::test_hue_events[pyloop] - as...
  = 1 failed, 12062 passed, 8 skipped, 2 xfailed, 1927 warnings, 1 rerun in 2122.96s (0:35:22) =
  DEBUG:pysonos.data_structures_entry:pysonos.data_structures_entry imported
  DEBUG:pyvera:DEBUG logging is ON
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 126666` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>home-assistant</li>
<li>python38Packages.xknx</li>
<li>python39Packages.xknx</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
@risicle can't reproduce your build failure on linux.

**Comment by fabaff** [comment]
We are already limiting other Home Assistant dependencies (e.g., `snitun`). Could be an option here was to get rid of the build failure.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 126666` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.xknx</li>
    <li>python39Packages.xknx</li>
  </ul>
</details>

**Pull request merged**
