### PR TITLE
haskellPackages.{ffmpeg-light,opencv{,-extra}}: remove overrides

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

These are dead code due to the packages being marked broken, and they depend on libraries (FFmpeg 4 and OpenCV 3) we’re trying to remove from Nixpkgs. Sending this PR to `haskell-updates` accordingly, as requested in the Haskell room on Matrix.

cc @nh2 – the second commit here will need reverting and adjusting if you land https://github.com/LumiGuide/haskell-opencv/pull/157 to get this fixed (as well `cabal2nix`, of course).

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by maralorn** [comment]
Sorry, I am a bit uncertain about this. Because I don’t understand the whole situation.

Are these Haskell packages basically obsolete because they rely on a systems library which is deprecated and gone for good?

Or is it to be expected that these libraries will become usable again at which point we need to re-add these overrides?

Well, looking at the overrides probably none of them will stay as is so I assume we can drop them.
Anyway can you please also remove the referenced cached so that we don’t have dangling files?

**Comment by emilazy** [comment]
`pkgs.opencv{2,3}` are gone for good already. `pkgs.ffmpeg_4` still exists for now, but we’re trying to get rid of it entirely; see https://github.com/NixOS/nixpkgs/pull/336401 (we’re mostly just blocked on Spotify, REAPER, and ROCm).

Both Haskell packages are currently broken in Nixpkgs anyway; `opencv-extra` because of `opencv`. Both `opencv` and `ffmpeg-light` have open pull requests migrating them to newer versions of OpenCV and FFmpeg. Those PRs have positive upstream feedback and also fix the build with newer GHCs, so I presume that if these packages ever begin to work again, they would need different dependency overrides, anyway. That would require patching `cabal2nix` in the case of `opencv`.

**Comment by emilazy** [comment]
I’ve removed the patch. FWIW I’d also be happy to just comment out the parts that might want restoring at a later date with different versions. (But `cabal2nix` would need patching anyway, and I’ve pinged the Nixpkgs‐committer author of the `opencv` PR here.)

**Comment by maralorn** [comment]
I guess the fix will be straightforward enough and there will be enough expertise around, that we will be able to add the correct overrides once they are useful.

Commenting out sounds good, but honestly, I’d expect that the next person dealing will this will actually miss the comments and then we have an override + an outdated comment. :laughing: 

Thanks for bearing with me.

**Pull request merged**
