### PR TITLE
nodejs_{18,20}: fix build with LLVM 19

### PR DESCRIPTION
**Pull request by emilazy**
First commit cherry‐picked from Randy’s branch. I’ve omitted the return address signing commit as it seems there was upstream churn.

@aduh95 It seems like we try to use shared versions of these libraries? Does that not work on older versions, or not work on Darwin, or something?

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
They both build successfully, although I’d still like to understand the Zlib situation better and hopefully de‐vendor it instead if possible.

@aduh95 The V8 patches here might be worth considering for backporting to these Node releases.

**Comment by emilazy** [comment]
Fixed the rebase mishap.

**Review by paparodeo — APPROVED** [review]
patches look straightforward.

**Comment by paparodeo** [comment]
oh -- eval should get restarted. it failed due to the `compiler-rt` issue that's already been fixed.

**Comment by emilazy** [comment]
@ofborg eval

**Comment by emilazy** [comment]
@aduh95 gentle ping, if you don’t mind taking a look at this :) I feel pretty confident about the V8 backports but would like to understand why the vendored Zlib is getting used at all.

**Comment by aduh95** [comment]
I'm not sure why it's the case, it could be that the vendored one is still compiled without being included in the binary, and I'm not familiar enough with the build tooling to help.

**Comment by aduh95** [comment]
Actually I see that V8 has its own vendored version, separate from the one Node.js uses. I think `--shared-zlib` only affects Node.js own code, not V8's. There's an open issue for it, but it's quite old: https://github.com/nodejs/node/issues/33848

**Review by aduh95 — APPROVED** [review]

**Comment by emilazy** [comment]
Thanks for the insight and review. Perhaps we can devendor it one day, but it can wait.

**Pull request merged**
