### PR TITLE
zeroad: fix build with new gcc and libxml

### LINKED ISSUE #280611: Build failure: zeroad
Another victim of the recent libxml2 changes on master. @chvp 

### Build log

```
../../../source/ps/XML/RelaxNG.cpp: In member function 'bool RelaxNGValidator::ValidateEncoded(xmlDocPtr) const':
../../../source/ps/XML/RelaxNG.cpp:162:50: error: invalid conversion from 'void (*)(void*, xmlErrorPtr)' {aka 'void (*)(void*, _xmlError*)'} to 'xmlStructuredErrorFunc' {aka 'void (*)(void*, const _xmlError*)'} [-fpermissive]
  162 |         xmlRelaxNGSetValidStructuredErrors(ctxt, &relaxNGErrorHandler, NULL);
      |                                                  ^~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  void (*)(void*, xmlErrorPtr) {aka void (*)(void*, _xmlError*)}
In file included from ../../../source/ps/XML/RelaxNG.cpp:28:
/nix/store/iqjsxkcdnvvz1bfpq960ygicc5clz9hv-libxml2-2.12.3-unstable-2023-12-14-dev/include/libxml2/libxml/relaxng.h:185:66: note:   initializing argument 2 of 'void xmlRelaxNGSetValidStructuredErrors(xmlRelaxNGValidCtxtPtr, xmlStructuredErrorFunc, void*)'
  185 |                                           xmlStructuredErrorFunc serror, void *ctx);
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
Xeromyces.cpp
../../../source/ps/XML/Xeromyces.cpp: In static member function 'static void CXeromyces::Startup()':
../../../source/ps/XML/Xeromyces.cpp:59:41: error: invalid conversion from 'void (*)(void*, xmlErrorPtr)' {aka 'void (*)(void*, _xmlError*)'} to 'xmlStructuredErrorFunc' {aka 'void (*)(void*, const _xmlError*)'} [-fpermissive]
   59 |         xmlSetStructuredErrorFunc(NULL, &errorHandler);
      |                                         ^~~~~~~~~~~~~
      |                                         |
      |                                         void (*)(void*, xmlErrorPtr) {aka void (*)(void*, _xmlError*)}
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by raphaelr**
## Description of changes

Fixes #280611.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by chvp — APPROVED** [review]

**Comment by kirillrdy** [comment]
can anyone suggest why ofborg did build it ? 

@GrahamcOfBorg build zeroad

**Comment by kirillrdy** [comment]
./results/zeroadPackages.zeroad-unwrapped/bin/0ad 
Segmentation fault (core dumped)

this is on a laptop with intel graphics. Can anyone confirm on a different setup ?

**Comment by raphaelr** [comment]
You're trying to run the `zeroad-unwrapped` package; can you try running `nix-build -A zeroad` and running the `0ad` executable from that?

The executable from `zeroad-unwrapped` also segfaults for me, the one from the `zeroad` works. (i'm not sure why nixpkgs-review didn't try to build the `zeroad` package though...)

**Comment by chvp** [comment]
I can confirm that running on a laptop with intel graphics works for me.

**Review by SuperSandro2000 — APPROVED** [review]

**Review by fpletz — APPROVED** [review]

**Pull request merged**
