### PR TITLE
maintainer-list: fix a few changed github usernames

### PR DESCRIPTION
**Pull request by delroth**
###### Description of changes

I noticed a few github usernames that didn't resolve anymore, causing ofborg to not notify the maintainers on relevant PRs. I did a bulk check of all id <-> usernames mapping, found 5 name changes that had not been reflected in the list.

There are also two users that don't seem to exist at all anymore: @weebsorceress and @gordiasdot. I've not touched those entries in this PR.

cc @CyborgPotato @Flameslice @matejc @syvb @fogti 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matejc** [comment]
If you merge this, there will be two same GitHub usernames - matejc

**Comment by matejc** [comment]
I guess that Mateo Diaz is using my GitHub id

**Comment by delroth** [comment]
> I guess that Mateo Diaz is using my GitHub id

Thanks for pointing this out! I've fixed the wrong GitHub id. cc @mateodd25

**Comment by ajs124** [comment]
There's a script for this you can just run. It's `maintainers/scripts/fix-maintainers.pl`.

**Comment by delroth** [comment]
> There's a script for this you can just run. It's `maintainers/scripts/fix-maintainers.pl`.

Nice, more convenient than my curl+jq bash oneliner :) Unfortunately it's also case sensitive, which makes it generate a bunch of noisy "renames" that aren't actually renames. I've checked that with this PR applied locally it doesn't find anything else than false positives.

**Review by wegank — APPROVED** [review]

**Review by fogti — APPROVED** [review]

**Review by syvb — APPROVED** [review]

**Pull request merged**
