### PR TITLE
hyperfine: 1.1.0 -> 1.3.0

### PR DESCRIPTION
**Pull request by dywedir**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @thoughtpolice

### CODE REVIEW

**Comment by tomberek** [comment]
Failed on Ubuntu with error below. Works fine on NixOS:
```
...
  Compiling unreachable v1.0.0
   Compiling regex-syntax v0.6.2
   Compiling regex-syntax v0.5.6
error: failed to run custom build command for `num-traits v0.2.6`                                                  
could not execute process `/run/nix/nix-build-hyperfine-1.3.0.drv-0/source/target/release/build/num-traits-0bcee0243813104a/build-script-build` (never executed)
warning: build failed, waiting for other jobs to finish...    
```

**Comment by tomberek** [comment]
Looks like a temporary issue with fetching. Works okay now.

**Comment by xeji** [comment]
let's build again here to make sure
@GrahamcOfBorg build hyperfine

**Comment by xeji** [comment]
let's try darwin
@GrahamcOfBorg build hyperfine

**Pull request merged**
