### PR TITLE
idris: Recurse into attrs, fix build and remove unneeded overrides

### PR DESCRIPTION
**Pull request by infinisil**
- The gmp issue has long been fixed and closed
- The preBuild thing was never used afaik, it works no problem without
it, especially since checks don't run (To get checks to work we'd have
to compile the libraries into idris, which are currently nicely
separated)
- The dependencies overrides aren't needed anymore

###### Motivation for this change
Originally just removing the hacks, but after rebasing on master I discovered that since 69cd09f8fb2427233319883dfdc0c702b87e2bf1 it wouldn't build at all. This cleanup surprisingly (or not) just happens to fix it :).

In the second commit I also made idris packages to be included in the packages hydra builds and nix-env finds. I hope that's okay, the ~80 idris packages don't change very often and it would be very nice to have them cached because Idris can take a while to build them (and you currently don't even have any progress reporting!  Will be fixed with my https://github.com/idris-lang/Idris-dev/pull/4498 in the next Idris version though).

Ping @brainrape @mpickering @peti 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Is there a way to add packages to Hydra without making them show up in ```nix-env```? I think one package set uses this but I can’t remember which one.

I think if we do recurseIntoAttrs for idris, we should make sure all of the names are prefixed properly with something like ```idris-```. A lot of times there will be conflicts with global vs language-specific package names. This can screw up things like ```nix-env -u```.

**Comment by Infinisil** [comment]
@matthewbauer Good point, I didn't think of that, will fix that

**Comment by Infinisil** [comment]
@matthewbauer Fixed that

@GrahamcOfBorg build idrisPackages.recursion_schemes

**Comment by peti** [comment]
> Is there a way to add packages to Hydra without making them show up in nix-env?

You can add the name of the attribute set at the bottom of pkgs/top-level/release.nix, like "haskellPackages" does it.

**Comment by Infinisil** [comment]
Is this good to merge?

**Review by peti — COMMENTED** [review]
The clean up is very desirable to have, obviously. I'm not sure whether Idris packages should show up with `nix-env -qa`. Are these packages useful to users, i.e. can you install `nix-env -i idris-foo` and do something useful with it? If you can, then showing them on the index seems fine. If Idris packages need to be installed using a wrapper, like Haskell packages do, then showing them on the index make little sense IMHO.

**Comment by mpickering** [comment]
The Idris packages need to be installed using a wrapper like the Haskell packages do.

**Review by peti — CHANGES_REQUESTED** [review]
Please don't use `recurseIntoAttrs`. It seems like a bad idea to show packages to users in `nix-env` that they actually can't use in `nix-env`.

Hydra builds can be enabled by adding an appropriate entry to `release.nix`, similar to this one: https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/release.nix#L168

**Comment by brainrape** [comment]
Peti, thanks for the review and the above great points.
Idris packages with binaries (directly useful for users) can be added to `pkgs/top-level/all-packages.nix`, like with other languages.

**Comment by Infinisil** [comment]
@brainrape Are there any idris packages with binaries though?

**Comment by Infinisil** [comment]
@peti I removed recurseIntoAttrs and added it to the mentioned release.nix

**Comment by TealG** [comment]
There are use cases for idris packages with binaries, however, `build-idris-package` currently does not allow installing these in `$out/bin` (`idris --install` only installs libs). It'd be useful if `build-idris-package` would allow specifying additional commands at the end of the `installPhase` for this purpose.

**Review by peti — APPROVED** [review]

**Pull request merged**
