### PR TITLE
jetbrains.*: 2020.1.* -> 2020.2

### PR DESCRIPTION
**Pull request by LeUlukai**
###### Motivation for this change

The jetbrain products have been updated with new cool features.

Updating: I just ran `update.pl`.

Testing: CLion is the only program that I tested more extensively than just launching.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 94893 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>11 packages built:</summary>  - jetbrains.clion  - jetbrains.datagrip  - jetbrains.goland  - jetbrains.idea-community  - jetbrains.idea-ultimate  - jetbrains.mps  - jetbrains.phpstorm  - jetbrains.pycharm-community  - jetbrains.pycharm-professional  - jetbrains.ruby-mine  - jetbrains.webstorm</details>

**Comment by raboof** [comment]
Tested compiling a Scala project with idea-community - seems to work. Running the tests produces an error, but the same error as it did before on this project :D

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 94893 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>11 packages built:</summary><br>- jetbrains.clion<br>- jetbrains.datagrip<br>- jetbrains.goland<br>- jetbrains.idea-community<br>- jetbrains.idea-ultimate<br>- jetbrains.mps<br>- jetbrains.phpstorm<br>- jetbrains.pycharm-community<br>- jetbrains.pycharm-professional<br>- jetbrains.ruby-mine<br>- jetbrains.webstorm</details>

**Comment by jonringer** [comment]
hmm looks  like I forgot tomerge this last time. Sorry abou thtat

**Pull request merged**
