### PR TITLE
osu-lazer{,-bin}: 2024.1009.1 -> 2024.1115.3

### PR DESCRIPTION
**Pull request by Guanran928**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Guanran928** [comment]
test needed: I cannot start `osu-lazer` (not -bin) on my laptop

**Review by thiagokokada — APPROVED** [review]

**Comment by gepbird** [comment]
`osu-lazer-bin` fails:

> osu.AppImage> trying https://github.com/ppy/osu/releases/download/2024.1115.1/osu.AppImage
osu.AppImage>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
osu.AppImage>                                  Dload  Upload   Total   Spent    Left  Speed
osu.AppImage>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
osu.AppImage> curl: (22) The requested URL returned error: 404
osu.AppImage> error: cannot download osu.AppImage from any mirror


There's no AppImage in the release, maybe after the last release they got fed up with it and are no longer distributing it?

Also I'm curious how is `osu-lazer` running with `SDL3` already. From the logs I see "SDL3 Initialized" and we have `ppy.SDL3-CS` nuget package, but there's only an `SDL2` package in `package.nix`.

**Comment by Guanran928** [comment]
> osu.AppImage> curl: (22) The requested URL returned error: 404

I did successfully built `osu-lazer-bin` before opening this PR, perhaps upstream removed the AppImage?

`/nix/store/9qpc5n4z9a1m2343f7zzm51w0mc3zdpp-osu-lazer-bin-2024.1115.1`

**Comment by thiagokokada** [comment]
> > osu.AppImage> curl: (22) The requested URL returned error: 404
> 
> I did successfully built `osu-lazer-bin` before opening this PR, perhaps upstream removed the AppImage?
> 
> ```shellsession                                                                                                                                                                                                                                                                 
> $ nix-build -A osu-lazer-bin
> /nix/store/9qpc5n4z9a1m2343f7zzm51w0mc3zdpp-osu-lazer-bin-2024.1115.1
>                                                                                                                                                                                                                                                                        
> $ nix-build -A osu-lazer-bin.src
> /nix/store/m6r12jxf1wppva2jsmns2791yjqrch14-osu.AppImage
> ```

If this is the case they probably found some issue in this release. Maybe it is better to hold up the update until upstream release a new version.

**Comment by gepbird** [comment]
> I did successfully built osu-lazer-bin before opening this PR, perhaps upstream removed the AppImage?

Yes, I just found out they removed it like an hour ago (partly) due to Velopack issues, but it shouldn't affect us as we disabled auto updates: https://discord.com/channels/188630481301012481/188630652340404224/1306977967444070500

Even after they release it, I think we should wait a few hours before merging in case they take it down again (last release that happened 3 times)

**Comment by stepbrobd** [comment]
[2024.1115.2](https://github.com/ppy/osu/releases/tag/2024.1115.2) is out

**Comment by Guanran928** [comment]
Am I insane or the .appimage on the new release is on 2024.1009.1?
image

**Comment by gepbird** [comment]
> Am I insane or the .appimage on the new release is on 2024.1009.1? image

@Guanran928 they couldn't fix the latest AppImage so they uploaded it from an older version

> i’m going to add the app image from 1009 to the latest release
i’ve gotten three emails so far saying it’s missing
it 404s from the site

- peppy, https://discord.com/channels/188630481301012481/188630652340404224/1307061352514326690

**Comment by Guanran928** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356157`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>osu-lazer</li>
    <li>osu-lazer-bin</li>
  </ul>
</details>

**Comment by gepbird** [comment]
I just tested this PR and they got rid of the "newer version available" message.

Untitled

**Comment by gepbird** [comment]
Can you please squash the commits that update the same package? For example your commits could look like:
- osu-lazer: 2024.1009.1 -> 2024.1115.3
- osu-lazer-bin: 2024.1009.1 -> 2024.1115.3
- osu-lazer{,-bin}: add Guanran928 as maintainer

**Comment by Guanran928** [comment]
> Can you please squash the commits

Oops, didn't saw that...
Ofborg had been pretty slow recently, I think squashing it right now would cause Ofborg to re-eval this PR again.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
