### PR TITLE
nixos/klipper: add OOMScoreAdjust -999

### PR DESCRIPTION
**Pull request by sorki**
to make it unlikely that klipper gets killed by OOM killer.

CC @lovesegfault @vtuan10

### CODE REVIEW

**Review by vtuan10 — APPROVED** [review]

**Comment by peterhoeg** [comment]
What makes klipper more special than any other application part of the KDE session?

**Comment by sorki** [comment]
> What makes klipper more special than any other application part of the KDE session?

This is not KDE Klipper but a https://github.com/Klipper3d/klipper/ - 3d printer control service.

**Comment by peterhoeg** [comment]
Is there any chance we can pretend this conversion never took place? Serves me right for not looking at this in detail before opening my mouth.

**Comment by peterhoeg** [comment]
On a related note though (here we go again), isn't preventing the OOM killer from doing a Will Smith only one part of it? Presumably we would also want to set both CPU and IO priorities to prevent starvation.

**Comment by lovesegfault** [comment]
> On a related note though (here we go again), isn't preventing the OOM killer from doing a Will Smith only one part of it? Presumably we would also want to set both CPU and IO priorities to prevent starvation.

You're correct, ideally this service would use all possible things to mark it as "top priority, don't touch it under any conditions."

**Comment by sorki** [comment]
Good tip! I've added a commit with `CPUScheduling` and `IOScheduling` tweaks.

**Comment by peterhoeg** [comment]
Looks good to me.

**Pull request merged**
