### PR TITLE
Update JDK 9 and Eclipse to GTK 3

### PR DESCRIPTION
**Pull request by jerith666**
###### Motivation for this change

Eclipse's built-in browser wants webkitgtk, but the current version of webkitgtk in nixpkgs is built on gtk3.  So, we need a version of the JDK that's built on gtk3 as well.

I've run with this for a couple of days at work and not noticed any problems with Eclipse.  I also confirmed that `jconsole`, a swing app bundled with the JDK, works.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rycee** [comment]
Sweet stuff! Tried building it and Eclipse looks good! :+1:

As far as I can tell this is good to be merged and maybe even backported to 18.03.

I can't say for certain about the jdk parts, though. @edwtjo?

**Comment by rycee** [comment]
@thoughtpolice Maybe you have some throught about moving jdk9 to gtk3?

**Comment by thoughtpolice** [comment]
I think it would be fine to move jdk9 to gtk3+ personally (though I don't use a lot of the GTK/UX components admittedly, I often run headless). However, I think the `jdk9` package is not really long for this world as it's been EOL'd.

But it would be nice not to drop this patch on the floor and force a rebase, provided it can build fine and downstream packages are OK.

I wonder if this makes any (noticeable) impact on closure size...

**Comment by jerith666** [comment]
Perhaps it is pointless now that 10 is out and 9 is EOL'd; if you want me to close this and just open a PR to remove 9 entirely instead, I'm okay with that.

I have a similar patch for openjdk10 (https://github.com/jerith666/nixpkgs/commit/599071d21271de79c5c094cbb93670102516a32c), which I'll make a PR for as soon as #37870 is merged.

I've been on vacation the last couple of days, but once I'm back at work I plan to roll eclipse forward to 10 as well, and will report in the PR for 599071d2 how well that goes.  I can also try to find some time to check the closure size too.

**Comment by fpletz** [comment]
@jerith666 Sounds fine to me. Thanks! :+1:

**Comment by rycee** [comment]
I may be difficult to reach the next few weeks but if the necessary changes to Eclipse are similar to the ones in this PR then I've love to get them in as soon as possible. Thanks a lot for taking the time to work on this @jerith666!

**Comment by thoughtpolice** [comment]
@jerith666 You are awesome, thank you for the openjdk10 work! I wanted to get it in myself but hadn't found the time. I'll look into dropping JDK9 now honestly since it would be great to sort that out *before* the official 18.03 release...

**Comment by jerith666** [comment]
Actually @NeQuissimus beat me to it by about 12 hours, you should thank him instead.  :)

(What we came up with was basically identical, #37870 was all that differed.  I stupidly didn't fetch before i started working on it ...)

Unless something has changed since I opened this PR, 9 is unused in nixpkgs, so dropping it should be trivial ...

... *except* that you need it to bootstrap building 10.  :)  (I tried bootstrapping with 8, but 10 refuses to build with a non-modular bootstrap JDK.)  So, ideas on how to solve that are welcome.  I'd rather not use the approach of out-of-tree bootstrap JDKs like was done for earlier versions if it can be helped ... but, maybe that's just academic since there's always gonna be _some_ out-of-tree bootstrapper at the root ... ?

**Comment by jerith666** [comment]
#38397 is the Java 10 version of this PR.

**Pull request closed without merging**
