### PR TITLE
deepin: some trivial updates, upstream changes reviewed

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
@ofborg test deepin

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 240467` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>37 packages built:</summary>
  <ul>
    <li>deepin.dde-app-services</li>
    <li>deepin.dde-calendar</li>
    <li>deepin.dde-clipboard</li>
    <li>deepin.dde-control-center</li>
    <li>deepin.dde-daemon</li>
    <li>deepin.dde-device-formatter</li>
    <li>deepin.dde-dock</li>
    <li>deepin.dde-dock.dev</li>
    <li>deepin.dde-file-manager</li>
    <li>deepin.dde-gsettings-schemas</li>
    <li>deepin.dde-launcher</li>
    <li>deepin.dde-network-core</li>
    <li>deepin.dde-polkit-agent</li>
    <li>deepin.dde-session-shell</li>
    <li>deepin.dde-session-ui</li>
    <li>deepin.deepin-album</li>
    <li>deepin.deepin-calculator</li>
    <li>deepin.deepin-camera</li>
    <li>deepin.deepin-clone</li>
    <li>deepin.deepin-compressor</li>
    <li>deepin.deepin-draw</li>
    <li>deepin.deepin-editor</li>
    <li>deepin.deepin-image-viewer</li>
    <li>deepin.deepin-movie-reborn</li>
    <li>deepin.deepin-movie-reborn.dev</li>
    <li>deepin.deepin-music</li>
    <li>deepin.deepin-reader</li>
    <li>deepin.deepin-screen-recorder</li>
    <li>deepin.deepin-shortcut-viewer</li>
    <li>deepin.deepin-system-monitor</li>
    <li>deepin.deepin-terminal</li>
    <li>deepin.deepin-voice-note</li>
    <li>deepin.dpa-ext-gnomekeyring</li>
    <li>deepin.qt5integration</li>
    <li>deepin.qt5platform-plugins</li>
    <li>deepin.startdde</li>
    <li>deepin.util-dfm</li>
  </ul>
</details>

**Comment by NickCao** [comment]
@ofborg test deepin

**Comment by wineee** [comment]
Thanks very much for your contribution

qt5integration and qt5platform-plugins are part of the dtk development suite， they should be upgraded together and try to keep the same version.


 I upgraded dtk to 5.6.12 on `dde-nixos flake`  https://github.com/linuxdeepin/dde-nixos/commit/4d32aaebabada661ae6385697dcd64fdfc23b2a6， 

At present, the DDE v23 version is basically available, but there are still some bugs, and a lot of unstable(git) version software is used. it has not been synchronized to nixpkgs for the time being

**Comment by wineee** [comment]
You can cherry-pick qt5integration and qt5platform-plugins to a new pr and upgrade dtk together, but I am not sure whether the new dtk suite is compatible with DDE 20 software

util-dfm is generally updated together with dde-file-manager and should also be in a separate pr

We can focus on other commits first, they should be merged smoothly

**Comment by wineee** [comment]
@ofborg test deepin

**Comment by NickCao** [comment]
It went OOM:
> Kernel panic - not syncing: Out of memory: compulsory panic_on_oom is enabled

**Review by wineee — APPROVED** [review]

**Comment by wineee** [comment]
@ofborg test deepin

**Pull request merged**
