### PR TITLE
glog: 0.3.4 -> 0.3.5

### PR DESCRIPTION
**Pull request by Mankarse**
###### Motivation for this change
Updated to latest upstream version

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build glog

**Comment by c0bw3b** [comment]
Travis' Darwin job is failing in building `kinetic-cpp-client` but this was [already failing](https://hydra.nixos.org/job/nixpkgs/nixpkgs-17.09-darwin/kinetic-cpp-client.x86_64-darwin) before.

Currently running a nox-review pr on nixos-17.09

**Comment by yegortimoshenko** [comment]
@jackpot1136 Please don't abuse GitHub review system!

**Comment by c0bw3b** [comment]
nox-review completed successfully on nixos-17.09 (hhvm is a pain to build):

```shell
Result in /tmp/nox-review-djpzd4f2
total 24
lrwxrwxrwx 1 demo users 55 13 nov.  09:00 result -> /nix/store/5wf7x90243gqqzq65c8w3sdcg0lyzy7c-spark-2.1.0
lrwxrwxrwx 1 demo users 55 13 nov.  09:00 result-10 -> /nix/store/kvwkwvb8hzwnj6hikj1i5xw7jma32ns3-spark-1.6.3
lrwxrwxrwx 1 demo users 57 13 nov.  09:00 result-11-bin -> /nix/store/r48xff3929p3xbmqynlvw7j6860bayrg-caffe-1.0-bin
lrwxrwxrwx 1 demo users 58 13 nov.  09:00 result-12 -> /nix/store/z734hfk3adg2didrdgqg5frxx56mzi40-marathon-1.4.2
lrwxrwxrwx 1 demo users 55 13 nov.  09:00 result-13 -> /nix/store/slsv28lv3mv5lw770wnb46f7wmkwiv6x-mesos-1.4.0
lrwxrwxrwx 1 demo users 58 13 nov.  09:00 result-14 -> /nix/store/6pxbnm9khb41c295fbyh4l737nfpsx15-gnss-sdr-0.0.9
lrwxrwxrwx 1 demo users 71 13 nov.  09:00 result-15 -> /nix/store/2kzlx291mi9wy8hzdkl5ashnv3p2innr-openmvs-unstable-2017-05-01
lrwxrwxrwx 1 demo users 69 13 nov.  09:00 result-16 -> /nix/store/wzz0a5gj6ii74091y0lssr9n2b7zl2gj-brise-unstable-2017-09-16
lrwxrwxrwx 1 demo users 53 13 nov.  09:00 result-17 -> /nix/store/1v7g4w2q8rsfqdflymgwirchs0z5bpbl-hhvm-3.21
lrwxrwxrwx 1 demo users 57 13 nov.  09:00 result-18 -> /nix/store/hgsa5nchkm2f2yc4s68cl24jd3a7hgis-librime-1.2.9
lrwxrwxrwx 1 demo users 57 13 nov.  09:00 result-2-bin -> /nix/store/r48xff3929p3xbmqynlvw7j6860bayrg-caffe-1.0-bin
lrwxrwxrwx 1 demo users 63 13 nov.  09:00 result-3 -> /nix/store/cj167k4h0jnpxnxkqwg5lnqrsx5spfsx-ceres-solver-1.12.0
lrwxrwxrwx 1 demo users 63 13 nov.  09:00 result-4 -> /nix/store/vgydrfb8rry46cqvvv84g1yp5ijj6fwh-folly-2017.11.06.00
lrwxrwxrwx 1 demo users 73 13 nov.  09:00 result-5 -> /nix/store/jmqpayj08l4hwacpzav1kfnbyj3j8pvp-kinetic-cpp-client-2015-04-14
lrwxrwxrwx 1 demo users 54 13 nov.  09:00 result-6 -> /nix/store/z6dr9drn8fzkh90qq48i946nr7d5q4b1-glog-0.3.5
lrwxrwxrwx 1 demo users 57 13 nov.  09:00 result-7 -> /nix/store/43i8lyc0rwp3r9311mxjkvp3xhi8ww45-osquery-2.5.2
lrwxrwxrwx 1 demo users 57 13 nov.  09:00 result-8-bin -> /nix/store/n5b8xpv2wln1n58736lr89hi9af5ccbn-caffe-1.0-bin
lrwxrwxrwx 1 demo users 60 13 nov.  09:00 result-9 -> /nix/store/30yh8fpz6q1887shm57afq9jxa12wp8j-fcitx-rime-0.3.2
```

**Review by c0bw3b — APPROVED** [review]

**Pull request merged**
