### PR TITLE
vpn-slice: add iproute2,iptables to propagatedBuildInputs

### PR DESCRIPTION
**Pull request by liketechnik**
## Description of changes

Those executables are needed for correct operation of vpn-slice during runtime. Otherwise the error message "cannot execute /sbin/ip" / "cannot execute /sbin/iptables" occurrs.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jdbaldry** [comment]
Hi,

Thanks for the contribution!

I am no longer running NixOS daily and also do not have the vpn-slice software installed so am no longer best placed to review this PR.

I don't know the procedure for handing over maintainership and can't find anything with a cursory search, but I'll see what we can do to get this sorted.

Would you be interested in becoming the maintainer of this package?

**Comment by liketechnik** [comment]
> I don't know the procedure for handing over maintainership and can't find anything with a cursory search, but I'll see what we can do to get this sorted.

I also didn't find anything specific to "handing over", but the [maintainers readme](https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md) seems to indicate that it's as simple as removing the current maintainer from `meta.maintainers` and adding the new one:

> ### [How to lose maintainer status](https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md#how-to-lose-maintainer-status)
>
> Maintainers who have become inactive on a given package can be removed. This helps us keep an accurate view of the state of maintenance in Nixpkgs.
>
> The inactivity measure is currently not strictly enforced. We would typically look at it if we notice that the author hasn't reacted to package-related notifications for more than 3 months.
>
> Removing the maintainer happens by making a PR on the package, adding that person as a reviewer, and then waiting a week for a reaction.
>
> The maintainer is welcome to come back at any time.

---

> Would you be interested in becoming the maintainer of this package?

Yes.

---

P.S.: Thank you for taking the time to sort this out, even though you're not actively using NixOs anymore!

**Comment by liketechnik** [comment]
Apparently this breaks the darwin builds of the package, since iproute2 isn't available there:
```
       error: Package ‘iproute2-6.4.0’ in /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/macstadium-x86-44911507/pkgs/os-specific/linux/iproute/default.nix:75 is not available on the requested hostPlatform:
         hostPlatform.config = "x86_64-apple-darwin"
```
(https://logs.ofborg.org/?key=nixos/nixpkgs.261216&attempt_id=46c65091-33df-4778-98a5-2f831fc4a33a)

According to the vpn-slice README, it uses the `route` command on macos:

> Supported OSes:
>  - Linux kernel 3.x+ with [iproute2](https://en.wikipedia.org/wiki/iproute2) and [iptables](https://en.wikipedia.org/wiki/iptables) utilities (used for all routing setup)
>  - macOS 10.x with BSD [route](https://en.wikipedia.org/wiki/Route_(command))

Trying to figure out how to put this into a NixOs package definition now...

**Review by jdbaldry — APPROVED** [review]
From what I recall of package configuration, this looks good!

I'm gonna approve to unblock you and perhaps we can do the maintainer switch in a follow up PR?

**Comment by jdbaldry** [comment]
It seems I don't have write access to merge the PR. We might need to ask another person to merge.

**Review by delroth — CHANGES_REQUESTED** [review]
I don't think this change does what you want? Propagating the inputs doesn't mean they'll be in $PATH at runtime (and even less in `/sbin` as your error messages indicate).

Usually this is solved by patching the source of the derivation. From quick grepping: you can look at `pkgs/servers/monitoring/fusion-inventory/default.nix` for an example of how to do this with `substituteInPlace`.

**Comment by liketechnik** [comment]
Hmm. I'm unsure about this. This works locally (inside a systemd service definition) and according to the python packaging docs (`doc/languages-frameworks/python.section.md`) this is also the correct way to handle runtime dependencies (emphasis mine):

> Our example, `toolz`, does not have any dependencies on other Python packages or
system libraries. According to the manual, [`buildPythonPackage`](#buildpythonpackage-function) uses the
arguments [`buildInputs`](#var-stdenv-buildInputs) and [`propagatedBuildInputs`](#var-stdenv-propagatedBuildInputs) to specify dependencies. If
something is exclusively a build-time dependency, then the dependency should be
included in [`buildInputs`](#var-stdenv-buildInputs), but **if it is (also) a runtime dependency, then it
should be added to [`propagatedBuildInputs`](#var-stdenv-propagatedBuildInputs)**. Test dependencies are considered
build-time dependencies and passed to [`nativeCheckInputs`](#var-stdenv-nativeCheckInputs).

**Comment by liketechnik** [comment]
The error message is also slightly misleading in this case. `vpn-slice` looks up the executable in $PATH and only if doesn't find it there it uses the hardcoded path under `/sbin` (https://github.com/dlenski/vpn-slice/blob/28ace485075c0acb98650ffa3d599bde4d1563a5/vpn_slice/util.py#L6).

But if you prefer to use `substituteInPlace` for this, I'm not opposed to update the PR.

**Comment by liketechnik** [comment]
> Do you have a link to the systemd service definition, by any chance? Is it upstream in NixOS or something you've written?

It's something I've written myself: https://gitlab.com/liketechnik/nixos-files/-/blob/888e34a334715a2948155ea2cb29bba639b9a5ef/profiles/fh/default.nix#L96-110

**Comment by liketechnik** [comment]
Oh and I took another look at the python packaging docs:

> * `propagatedBuildInputs ? []`: Aside from propagating dependencies,
  `buildPythonPackage` also injects code into and wraps executables with the
  paths included in this list. Items listed in `install_requires` go here.

This is probably the magic that makes it work? But if its "magic", it's probably safer/more future-proof to go with `substituteInPlace`, right?

**Review by delroth — APPROVED** [review]

**Comment by liketechnik** [comment]
This should be more idiomatic now. Thanks for taking the time to figure this one out with me.

**Review by delroth — APPROVED** [review]

**Comment by delroth** [comment]
@ofborg build vpn-slice

**Comment by delroth** [comment]
Did you mean to keep this PR as draft, by the way?

**Comment by liketechnik** [comment]
Orignally not, now I just realized that `/sbin/iptables` matches `/sbin/ip`, thus making the replace not work :/ This should be fixed now, sorry for the noise...

**Comment by delroth** [comment]
@liketechnik feel free to ping me directly if you file a PR to update the maintainers for this derivation

**Pull request merged**
