### PR TITLE
rust-analyzer: 2020-06-01 -> 2020-06-15 and fix version display

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change
Bump version.
Fix output when it is called with `--version`. (Used to be `??????`)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
With https://github.com/NixOS/nixpkgs/pull/90211 merged, can this be rebased onto it?

Also, cc @lovesegfault on the version display. Isn't there a better way to pass this in?

**Comment by lovesegfault** [comment]
@flokli I think this approach is fine, although perhaps it could benefit from being upstreamed with an explanation of why this helps us in Nix land.

**Comment by flokli** [comment]
Humm… I thought about using the [git-version](https://crates.io/crates/git-version) crate (but didn't check if it allows overriding the version via an env variable), instead of implementing (and extending the logic on our own)

**Comment by oxalica** [comment]
Maybe we could wait for the next release to fix it.

**Pull request closed without merging**
