### PR TITLE
gnomeExtensions.gsconnect: 55 -> 56

### LINKED ISSUE #269566: Update request: gnomeExtensions.gsconnect 55 → 56
- Package name: gnomeExtensions.gsconnect
- Latest released version: 56

- Current version on the unstable channel: 55
- Current version on the stable/release channel: 55

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@NixOS/gnome 

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by kranich**
## Description of changes

Update of gnomeExtensions.gsconnect to v56 which works with Gnome 45 (unlike v55). See https://github.com/GSConnect/gnome-shell-extension-gsconnect/releases/tag/v56.

I must admit I did not know what pkgs/desktops/gnome/extensions/gsconnect/fix-paths.patch does, so I have just tried to adapt it to the new style of imports.

Fixes: https://github.com/NixOS/nixpkgs/issues/269566

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jtojnar** [comment]
With the new modules, imports in each module are resolved before running any code so just porting the code to the new syntax will not work. You need to either convert all affected import statements to regular statements using top-level await ([example](https://github.com/NixOS/nixpkgs/blob/0bd59c54ef06bc34eca01e37d689f5e46b3fe2f1/pkgs/desktops/gnome/core/gnome-shell-extensions/fix_gmenu.patch)) or move the typelib path manipulation to a separate file ([example](https://github.com/NixOS/nixpkgs/pull/269588#issuecomment-1825981800)).

**Comment by kranich** [comment]
@jtojnar Thank you for the explanation and the links to example solutions. I have decided to follow the approach of moving the typelib path manipulation to a separate file, which I find a little less intrusive.

**Comment by jtojnar** [comment]
Looks good but I did not test.

Could please double check that the preferences in the extension app work?

**Comment by kranich** [comment]
I have tested successfully that I can pair a new device and that I can change the directory in which files sent from the device to the computer are stored.

**Comment by iclanzan** [comment]
I am getting this error in the Extensions app on Gnome 45 and gsconnect 56:
```
GLib.FileError: Failed to open file “/usr/local/share/glib-2.0/schemas/gschemas.compiled”: open() failed: No such file or directory
```

**Comment by kranich** [comment]
@iclanzan I do not get any errors in the Extensions app with gsconnect 56. I have also checked that there is no `/usr/local/share/glib-2.0/schemas/gschemas.compiled` on my machine; in fact, there is no `/usr/local`. Could it be that you have a version of the extension installed at `~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/` via Gnome shell browser extension that does not have the NixOS paths?

**Comment by iclanzan** [comment]
I just tried on a fresh NixOS install on a different laptop and I am getting the same issue. Must be something about my nix config. I am installing gsconnect like this:
```
environment.systemPackages = [ pkgs.gnome45Extensions."gsconnect@andyholmes.github.io" ];
```

**Comment by iclanzan** [comment]
While it didn’t work at the time I made the original comment, this works now:
```
environment.systemPackages = [ pkgs.gnomeExtensions.gsconnect ];
```

**Pull request merged**
