### PR TITLE
powerdns-admin: 0.2.4 -> 0.3.0

### PR DESCRIPTION
**Pull request by Flakebi**
###### Description of changes
Update to 0.3.0: https://github.com/PowerDNS-Admin/PowerDNS-Admin/releases/tag/v0.3.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by zhaofengli — APPROVED** [review]
Looks reasonable, thanks!

**Comment by symphorien** [comment]
The changelog mentions no backward incompatibility and two security fixes, so I think we should backport it. But as I'm not familiar with powerdns-admin please speak up if it does not make sense.

**Comment by symphorien** [comment]
does not build because of a dependency:
```
error: builder for '/nix/store/6x2a5qdan1f6ddrqm4m5bamdr8nrd5hs-python3.10-eventlet-0.33.1.drv' failed with exit code 2;
       last 10 log lines:
       > ERROR tests/thread_test.py - AttributeError: module 'collections' has no attr...
       > ERROR tests/timeout_test.py - AttributeError: module 'collections' has no att...
       > ERROR tests/timer_test.py - AttributeError: module 'collections' has no attri...
       > ERROR tests/tpool_test.py - AttributeError: module 'collections' has no attri...
       > ERROR tests/websocket_new_test.py - AttributeError: module 'collections' has ...
       > ERROR tests/websocket_test.py - AttributeError: module 'collections' has no a...
       > ERROR tests/wsgi_test.py - AttributeError: module 'collections' has no attrib...
       > ERROR tests/zmq_test.py - AttributeError: module 'collections' has no attribu...
       > !!!!!!!!!!!!!!!!!!! Interrupted: 39 errors during collection !!!!!!!!!!!!!!!!!!!
       > ======================== 3 warnings, 39 errors in 3.94s ========================
       For full logs, run 'nix log /nix/store/6x2a5qdan1f6ddrqm4m5bamdr8nrd5hs-python3.10-eventlet-0.33.1.drv'.
error: 1 dependencies of derivation '/nix/store/828x00y46j6hgc36900ri0jmk4ar0gk3-python3.10-gunicorn-20.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4ihjxgicmxdrr1k21xnrh640jn10qqv8-powerdns-admin-assets-0.2.5.drv' failed to build
error: 2 dependencies of derivation '/nix/store/h13z5r9c6pbz4235bafaw5c0vyh28i1b-powerdns-admin-0.2.5.drv' failed to build
```

**Comment by Flakebi** [comment]
> does not build because of a dependency

The commit in this PR builds, just if you port it onto master, it doesn’t build because of the dependency.
Anyway, there has been a new release (also containing security fixes): https://github.com/PowerDNS-Admin/PowerDNS-Admin/releases/tag/v0.3.0

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, passthru tests pass on nixos x86_64.

**Pull request merged**
