### PR TITLE
Add scrolls game (unfree)

### PR DESCRIPTION
**Pull request by brodul**
I tested it against the 14.12 release branch.

https://scrolls.com/

### CODE REVIEW

**Comment by brodul** [comment]
They just updated the client today (happens rarely).

**Comment by lethalman** [comment]
Fails with `cat: /nix-support/dynamic-linker: No such file or directory`

**Comment by brodul** [comment]
Hmm, it seems while building in 14.12 the $NIX_GCC is set, but in the master is not.

So I need to change the $NIX_GCC to $NIX_CC .

Should I fix the docs or I am missing something.

**Comment by brodul** [comment]
And Travis is failing I have no clue why :D

**Comment by vcunat** [comment]
Looks good. I only added today's date as the version, so updating behaves reasonably.

**Pull request closed without merging**
