### PR TITLE
conan: 2.0.0 -> 2.0.5

### LINKED ISSUE #228361: Build failure: Conan 2.0 (`nixos-unstable`)
### Steps To Reproduce

1. Use the following `flake.nix` to create a shell with `conan`

```nix
{
	inputs = {
		nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
		flake-utils.url = "github:numtide/flake-utils";
	};

	outputs = { self, nixpkgs, flake-utils }:
		flake-utils.lib.eachDefaultSystem (system:
		let
			pkgs = import nixpkgs { inherit system; };

			build_libs = with pkgs; [
				conan
			];
		in
		{

			devShells.default = pkgs.mkShell {
				packages = build_libs;
			};
		});
}
```

The `flake.lock` revision for nixpkgs is c8018361fa1d1650ee8d4b96294783cf564e8a7f

### Build log

https://gist.github.com/JonBoyleCoding/5e8361d3af042b508cdbd286fc3e5185

```console
       > =========================== short test summary info ============================
       > FAILED conans/test/integration/command_v2/list_test.py::TestListPrefs::test_list_pkg_ids[True] - AssertionError: assert 'default\n  z...os: Windows\n' == 'default\n  z...  ...
       > FAILED conans/test/integration/command_v2/list_test.py::TestListPrefs::test_list_pkg_ids_all_rrevs[True] - AssertionError: assert 'default\n  z...os: Windows\n' == 'default\n  z...  ...
       > FAILED conans/test/integration/command_v2/list_test.py::TestListPrefs::test_list_latest_prevs[True] - AssertionError: assert 'default\n  z...os: Windows\n' == 'default\n  z...  ...
       > FAILED conans/test/integration/command_v2/list_test.py::TestListPrefs::test_list_all_prevs[True] - AssertionError: assert 'default\n  z...os: Windows\n' == 'default\n  z...  ...
```

### Notify maintainers

@HaoZeke

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.108, NixOS, 22.11 (Raccoon), 22.11.3889.f5364316e31`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(jonathan): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by fabaff**
Changelog: https://github.com/conan-io/conan/releases/tag/2.0.5

###### Description of changes
Fix build (https://hydra.nixos.org/build/220641217)

ZHF: #230712

Fixes #228361

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 233184` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>conan</li>
    <li>conan.dist</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
The darwin tests require xcrun (from xcbuild) and xattr (probably from samba).

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 233184` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>conan</li>
    <li>conan.dist</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
```
conan-aarch64-darwin> FAILED conans/test/functional/command/profile_test.py::DetectCompilersTest::test_detect_default_compilers - AssertionError: 'clang' != 'apple-clang'
conan-aarch64-darwin> FAILED conans/test/functional/tools/test_apple_tools.py::test_xcrun - Exception: 
conan-aarch64-darwin> FAILED conans/test/functional/tools/test_apple_tools.py::test_xcrun_in_tool_requires - Exception: 
conan-aarch64-darwin> FAILED conans/test/functional/tools/test_apple_tools.py::test_xcrun_in_required_by_tool_requires - Exception: 
conan-aarch64-darwin> FAILED conans/test/functional/tools/test_files.py::TestConanToolFiles::test_download - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_upload_sources_backup - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_download_origin_first - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_download_origin_last - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_sources_backup_server_error_500 - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_upload_sources_backup_creds_needed - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_download_sources_multiurl - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_ok_when_origin_breaks_midway_list - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_ok_when_origin_authorization_error - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_ok_when_origin_bad_sha256 - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/backup_sources_test.py::TestDownloadCacheBackupSources::test_export_then_upload_workflow - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/test_source_download_password.py::test_source_download_password - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/tgz_macos_dot_files_test.py::TgzMacosDotFilesTest::test_dot_files - FileNotFoundError: [Errno 2] No such file or directory: 'xattr'
conan-aarch64-darwin> FAILED conans/test/functional/command/config_install_test.py::ConfigInstallTest::test_config_install_requester - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/cache/download_cache_test.py::TestDownloadCache::test_user_downloads_cached_newtools - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/conanfile/conan_data_test.py::ConanDataTest::test_conan_data_as_source_newtools - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> FAILED conans/test/integration/lockfile/test_lock_requires_revisions.py::test_conditional_os[requires] - AssertionError: assert 'nix' not in 'Using lockf...ccessfully\n'
conan-aarch64-darwin> FAILED conans/test/integration/lockfile/test_lock_requires_revisions.py::test_conditional_os[tool_requires] - AssertionError: assert 'nix' not in 'Using lockf...ccessfully\n'
conan-aarch64-darwin> FAILED conans/test/unittests/util/apple_test.py::AppleTest::test_xcrun - conans.errors.ConanException: Command 'xcrun --find clang' failed with erro...
conan-aarch64-darwin> ERROR conans/test/functional/command/profile_test.py::DetectCompilersTest::test_detect_default_in_mac_os_using_gcc_as_default - Failed: Required 'gcc' tool version 'Any' is not available
conan-aarch64-darwin> ERROR conans/test/integration/remote/rest_api_test.py::RestApiTest::test_get_conan - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/integration/remote/rest_api_test.py::RestApiTest::test_get_package - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/integration/remote/rest_api_test.py::RestApiTest::test_remove - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/integration/remote/rest_api_test.py::RestApiTest::test_remove_packages - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/integration/remote/rest_api_test.py::RestApiTest::test_search - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/integration/remote/rest_api_test.py::RestApiTest::test_server_capabilities - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/integration/remote/rest_api_test.py::RestApiTest::test_upload_huge_conan - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestDownload::test_download - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestDownload::test_download_iterate_url - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestDownload::test_download_forbidden - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestDownload::test_download_authorized - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestDownload::test_download_retries_500_errors - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestDownload::test_download_no_retries_errors - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestGet::test_get_tgz - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestGet::test_get_tgz_strip_root - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestGet::test_get_gunzip - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestGet::test_get_gunzip_destination - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestGet::test_get_gunzip_destination_subfolder - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
conan-aarch64-darwin> ERROR conans/test/unittests/tools/files/test_downloads.py::TestGet::test_get_filename_error - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by wegank** [comment]
@ofborg build conan conan.passthru.tests

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 233184` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>conan</li>
    <li>conan.dist</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 233184` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>conan</li>
    <li>conan.dist</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 233184` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
