### PR TITLE
ethtool: 6.1 -> 6.7

### PR DESCRIPTION
**Pull request by mrgiles**
## Description of changes

This commit updates **ethtool** to [version 6.7](https://git.kernel.org/pub/scm/network/ethtool/ethtool.git/diff/NEWS?h=v6.7&id=0aadd41eab7ea76501e557ccba705a08c07ce088)

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ethtool</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by vifino — APPROVED** [review]
LGTM; long overdue!

**Comment by mrgiles** [comment]
Hello @bjornfor, would you mind taking a look at this PR when you have the chance? Thanks!

**Review by bjornfor — COMMENTED** [review]
LGTM, but should probably target the staging branch due to rebuild amount.

**Comment by mrgiles** [comment]
Thanks for reviewing @bjornfor. Do you mean close this PR and open a new one against the `staging` branch of `nixpkgs`?

**Comment by mrgiles** [comment]
@bjornfor, something went wrong here, this doesn;t look good. I followed the instructions in [Rebasing between branches](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging). I think I better close this PR before it gets worse. I hope it didn't ping all the people listed here. Sorry if it did!

**Comment by mrgiles** [comment]
@bjornfor, any idea what went wrong with the latest commit using `rebase --onto`? Have you seen this happen before?

I'm new here, so I'd like to understand to be able to continue contributing, otherwise it feels discouraging. 
Thanks!

**Comment by bjornfor** [comment]
@mrgiles: I'm sorry but I don't do that operation a lot myself, so I don't know what went wrong.

I think it's just a micro optimization; one might just as well create a new PR.

Since a lot of people get pinged in this thread now, I think its best to continue in your next PR (ping me) or ask in https://discourse.nixos.org/ about the process/docs.

**Pull request closed without merging**
