### PR TITLE
zenith: 0.8.2 -> 0.9.0

### PR DESCRIPTION
**Pull request by bbigras**
0.9.0 has "not built by default" support for nvidia gpu but I didn't figure out yet how to build it. I'll address it in another PR.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/nix/store/14knjny0mplcs3js2ivr9vjzdwcznsx6-zenith-0.8.2	  34.8M
/nix/store/1jwqjrk3w4fnqi3nacf84nlc6raavhd6-zenith-0.9.0	  33.8M

### CODE REVIEW

**Comment by bbigras** [comment]
It should build for aarch64 this time.

**Comment by bbigras** [comment]
It doesn't build on aarch64. Help would be very welcome.

**Comment by doronbehar** [comment]
As a start, I'd try to split to two different PRs the update vs "Make this work for aarch64".

**Comment by bbigras** [comment]
@doronbehar done, this PR is the update and the aarch64 stuff is in #88616.

**Review by doronbehar — APPROVED** [review]
Seems to work fine on x86-linux.

**Comment by bbigras** [comment]
Thank you very much for your time.

**Comment by bbigras** [comment]
Thanks!

**Pull request merged**
