### PR TITLE
virtualbox: use fewer vendored libraries

### PR DESCRIPTION
**Pull request by blitz**
## Description of changes

This PR prevents VirtualBox from building against its own source of `liblzma` and `libtpms` by providing `xz` and `libtpms` as inputs. This cuts down build times and also allows central patching of these libraries.

See the initial configure output to see that VBox actually uses the provided libraries instead of its own.

While I was here, I also added an option to provide extra configure flags. This will [come in handy](https://github.com/cyberus-technology/virtualbox-kvm) later...

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nikstur** [comment]
This doesn't eval. Not obvious to me why.

**Comment by wegank** [comment]
@ofborg eval

**Comment by blitz** [comment]
The VBox tests look good:

```
/nix/store/1i0i506liyh6p96skwcj9mxl8rrmw8fx-vm-test-run-virtualbox-headless
/nix/store/jm4lcy7m1v9g3d4c0ivlf324g4gz9as1-vm-test-run-virtualbox-host-usb-permissions
/nix/store/2f4aa4fz5awrklpa7c1c6zjj3wjknp0p-vm-test-run-virtualbox-net-hostonlyif
/nix/store/hsr3ml7ql78n2dbxasy7f7adzn9vz0y0-vm-test-run-virtualbox-simple-cli
/nix/store/ra1v2nh0cq87pnv3w7nw1gmx34whxmw0-vm-test-run-virtualbox-simple-gui
/nix/store/dsg3ypb29qqldxq0bcxk3qyvaczpzwj4-vm-test-run-virtualbox-systemd-detect-virt
```

**Comment by blitz** [comment]
The failing build for the hardened kernel modules are unrelated to this change. They are already broken on master.

**Comment by tfc** [comment]
@ofborg test virtualbox.headless virtualbox.simple-cli virtualbox.host-usb-permissions virtualbox.simple-gui virtualbox.net-hostonlyif pvirtualbox.systemd-detect-virt

**Pull request merged**
