### PR TITLE
Brave 1.1.23 to 1.3.113

### PR DESCRIPTION
**Pull request by JeffLabonte**
###### Motivation for this change

I needed the latest version of Brave, I made the change of version and wanted to share with the others.

###### Things done

Change the version to the latest stable and update the checksum. Add my name to the lists of maintainers

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Builds and executes.
It seems there was a newer release already though https://github.com/brave/brave-browser/releases/tag/v1.3.115.

**Comment by worldofpeace** [comment]
Will try to backport this to 20.03 as well.

**Comment by JeffLabonte** [comment]
@worldofpeace, thank you for your review! Wow! They update quite often these days!

**Review by worldofpeace — APPROVED** [review]
LGTM, also rewrote your git history for you.

**Comment by uskudnik** [comment]
Much obliged @JeffLabonte, one of the previous versions had a broken full screen mode on for i3 window manager - this one fixes that. Thank you! :heart:

**Pull request merged**
