### PR TITLE
treewide: migrate to pytest-cov-stub 

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

Migrating a couple of leaf packages to use the new pytest-cov-stub (https://github.com/NixOS/nixpkgs/pull/328550)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ofalvai** [comment]
Result of `nixpkgs-review pr 331138` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>python312Packages.batchspawner</li>
    <li>python312Packages.batchspawner.dist</li>
    <li>python312Packages.oauthenticator</li>
    <li>python312Packages.oauthenticator.dist</li>
  </ul>
</details>
<details>
  <summary>44 packages built:</summary>
  <ul>
    <li>python311Packages.aiojobs</li>
    <li>python311Packages.aiojobs.dist</li>
    <li>python311Packages.ambee</li>
    <li>python311Packages.ambee.dist</li>
    <li>python311Packages.anonip</li>
    <li>python311Packages.anonip.dist</li>
    <li>python311Packages.birch</li>
    <li>python311Packages.birch.dist</li>
    <li>python311Packages.cachier</li>
    <li>python311Packages.cachier.dist</li>
    <li>python311Packages.cemm</li>
    <li>python311Packages.cemm.dist</li>
    <li>python311Packages.githubkit</li>
    <li>python311Packages.githubkit.dist</li>
    <li>python311Packages.hickle</li>
    <li>python311Packages.hickle.dist</li>
    <li>python311Packages.pymarshal</li>
    <li>python311Packages.pymarshal.dist</li>
    <li>python311Packages.pytest-postgresql</li>
    <li>python311Packages.pytest-postgresql.dist</li>
    <li>python311Packages.toggl-cli</li>
    <li>python311Packages.toggl-cli.dist</li>
    <li>python312Packages.aiojobs</li>
    <li>python312Packages.aiojobs.dist</li>
    <li>python312Packages.ambee</li>
    <li>python312Packages.ambee.dist</li>
    <li>python312Packages.anonip</li>
    <li>python312Packages.anonip.dist</li>
    <li>python312Packages.birch</li>
    <li>python312Packages.birch.dist</li>
    <li>python312Packages.cachier</li>
    <li>python312Packages.cachier.dist</li>
    <li>python312Packages.cemm</li>
    <li>python312Packages.cemm.dist</li>
    <li>python312Packages.githubkit</li>
    <li>python312Packages.githubkit.dist</li>
    <li>python312Packages.hickle</li>
    <li>python312Packages.hickle.dist</li>
    <li>python312Packages.pymarshal</li>
    <li>python312Packages.pymarshal.dist</li>
    <li>python312Packages.pytest-postgresql</li>
    <li>python312Packages.pytest-postgresql.dist</li>
    <li>python312Packages.toggl-cli</li>
    <li>python312Packages.toggl-cli.dist</li>
  </ul>
</details>

**Comment by emilazy** [comment]
Looks good to me. There are a bunch of packages that explicitly use `pytest-cov` rather than patching it out; maybe we should switch those in this PR too?

**Comment by pbsds** [comment]
I plan to migrate bit by bit in separate PRs both to minimize merge conflicts and to catch errors early.

This pr primarily greps for `--cov`, and there are a plethora of these cases left.
I assume once i do a `s/pytest-cov/pytest-cov-stub/g` I'll run into checks that fail due to a different version than what they're expecting, if they pin `pytest-cov` as an optional dependency. I think the fix then will be `pythonRelaxDeps` rather than changing the version of pytest-cov-stub

**Comment by emilazy** [comment]
Sounds reasonable. I don’t suppose there’s anything we could do to somehow make the stub match any possible version?

**Comment by pbsds** [comment]
We could set it to the current major version and leave the minor and patch version at zero. 
I don't want to rebuild all dependents of `pytest-cov-stub` each time the version of `pytest-cov` is bumped, it kinda defeats the purpose.

**Comment by pbsds** [comment]
We could maybe add a setup hook that appends `pytest-cov` to `relaxPythonDeps`, but `relaxPythonDepsHook` is only added to the build if `relaxPythonDeps` is populated at eval time

**Comment by SuperSandro2000** [comment]
I did the remaining outside of pythonPackages occurences in #336777

**Pull request merged**
