### PR TITLE
 xserver: qtile as windowManager

### PR DESCRIPTION
**Pull request by kamilchm**
Fixed https://github.com/NixOS/nixpkgs/pull/9034
Sorry for the previous one, I didn't test it after a quick C&P for yagayaga suggestion :(
This one is tested, it works and I use it now.

### CODE REVIEW

**Comment by lethalman** [comment]
Why desktopManager instead of windowManager? Is qtile like kde or gnome?

**Comment by kamilchm** [comment]
I think I was trying to set it as windowManager without any desktopManager and I couldn't start it this way so I changed it to desktopManager. But it was some time ago when I started my work on this.
I can try it again, if you think it could work as a standalone windowManager?

**Comment by geerds** [comment]
no its a windowManager

**Comment by jagajaga** [comment]
You can run it like `exec qtile` in you .xsession.

And I'm `jagajaga` :)

**Comment by kamilchm** [comment]
OK, so I changed it locally to windowManager, but it's not clear to me what is the connection between desktop and window manager. My session menu in slim contains entries like ``xterm + qtile``, ``xfce + qtile`` and ``none + qtile`` instead of just ``qtile`` before.
What is the difference between them?

Forgive me misspelling your name @jagajaga.

**Comment by geerds** [comment]
A window manager only let you manage your application windows. A desktop environment on the other side is a complete environment (a set of packages) like an audio player, instant messenger and of course a window manager. So a window manager is a subset of a desktop environment

**Comment by jagajaga** [comment]
Move it to `windowManagers` in your commit.

**Comment by lethalman** [comment]
none+qtile should work for you, doesn't it?

**Comment by kamilchm** [comment]
Yes, ``none+qtile`` works, but ``xfce+qtile`` works too, hence my question about differences.
qtile moved to window managers.

**Comment by lethalman** [comment]
Ok thanks.

**Pull request merged**
