### PR TITLE
More trivial builderDefs translations

### PR DESCRIPTION
**Pull request by joachifm**
These are trivial translations in the sense that the build recipes have been left unaltered in almost all cases, except where noted in the commit message. As far as I can tell, this series does not break anything. For reference: https://github.com/NixOS/nixpkgs/issues/4210

### CODE REVIEW

**Comment by domenkozar** [comment]
AWESOME!

**Comment by 7c6f434c** [comment]
Thanks.

**Comment by domenkozar** [comment]
There are a bunch of eval errors, I'm fixing them now

**Comment by domenkozar** [comment]
done in https://github.com/NixOS/nixpkgs/commit/d15d1a49be3b25e28da456d4c889ea50cc9f46e1

**Comment by vcunat** [comment]
You don't need to inherit from `xlibs` or `xorg`, as `callPackage` supplies those automatically. I'm testing a cleanup of that and will push it soon.

**Comment by joachifm** [comment]
Hm, that is odd, I was able to do `nix-instantiate --strict` without any problems, and according to my notes, I was able to build each and every package without failure on my system. Granted, that was a while ago and the rebase was a bit hairy ...

**Comment by vcunat** [comment]
Incidentally, it was me who did the xlibs cleanup.

**Pull request merged**
