### PR TITLE
Ghostscript and CUPS updates

### PR DESCRIPTION
**Pull request by abbradar**
This bumps our `ghostscript`, `qpdf` and `cups`-related packages (they are somewhat related and I thought to test them in one go). Notice that while I have tested `ghostscript` somewhat and some of its reverse dependencies, I haven't done so for `cups` yet because of a much more massive rebuild. I need to at least test it on my system and actually print something to be safe.

### CODE REVIEW

**Comment by abbradar** [comment]
This progressed into a big printing update. Biggest user-facing changes in my opinion, apart from version bumps, is `gutenprint` improvements. I've managed to build and test this on my primary machine (with lots of packages, including `libreoffice`).

* CUPS, GhostScript, CUPS filters, gutenprint and other packages are updated.
* GhostScript now has its binaries placed in correct paths and found by CUPS.
* `cups-pk-helper` is now enabled in NixOS module if PolicyKit is also enabled.
* `cupsdConf` and `cupsdFilesConf` options were removed from NixOS module. They allowed one to override complete CUPS configuration, which is probably what we don't want, because we specify necesary paths and things from NixOS configuration there. Instead one can use `extraConf` and `extraFilesConf`.
* Some core "drivers" are also moved from options -- we don't want them to be overriden too.
* Gutenprint now correctly lists its drivers to CUPS (no more fiddling like in https://nixos.org/wiki/Printers , hooray!). PPDs are also updated correctly if `printing.gutenprint` option is used instead of just listing Gutenprint in `drivers`.
* Configuration directory is moved from `/etc/cups` to `/var/lib/cups` -- this is because CUPS uses its configuration directory as state directory, too. This brings us one step closer to possibility of fully immutable `/etc`. Old configurations are migrated automatically.
* `system-config-printer` is updated and patched to look into our `cups-progs` environment as CUPS binary directory.

Notice that there are some unrelated commits (`gimp`-related) -- they are there to ease load on Hydra -- GIMP would be rebuilt with this PR merged anyway.

**Comment by abbradar** [comment]
Whom can I ping for reviewing CUPS and printing-based things? Ideally it would be nice if someone else can test if it actually prints something (for me on Epson TX210 with Gutenprint it does).

**Comment by vcunat** [comment]
Noone has reacted for a full week and it didn't break anything for you. I believe we can stage it.

**Comment by abbradar** [comment]
I agree, let's wait for a few days (just in case) and merge it.

**Comment by abbradar** [comment]
I think I'll also write a few sentences about this into the changelog (about removed parameters and using `gutenprint = true` instead of `drivers = [ pkgs.gutenprint ]`.

**Comment by vcunat** [comment]
:-)

**Comment by vcunat** [comment]
I think this regression is related: http://hydra.nixos.org/build/31504318/nixlog/2/raw

**Comment by abbradar** [comment]
Fixed in 70efc87

**Pull request merged**
