### PR TITLE
minimal-bootstrap: hide for yet unsupported platforms

### LINKED ISSUE #259731: Build failure: coreutils on darwin
### Steps To Reproduce

1. git checkout a680950c8828624ddc71aadcf1e0ca20db544836
2. nix-env -f ../nixpkgs -u --dry-run  -v --show-trace

### Build log
<details>

```
...
evaluating file '/Users/monson/Projects/nixpkgs/pkgs/development/compilers/mlton/meta.nix'
evaluating file '/Users/monson/Projects/nixpkgs/pkgs/applications/editors/texmacs/common.nix'
evaluating file '/Users/monson/Projects/nixpkgs/pkgs/games/quake2/yquake2/games.nix'
error:
       … while trying to find an upgrade for 'coreutils-9.3'

       … while calling the 'getAttr' builtin

         at /builtin/derivation.nix:19:19: (source not available)

       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'coreutils-9.4'
         whose name attribute is located at /Users/monson/Projects/nixpkgs/pkgs/os-specific/linux/minimal-bootstrap/bash/2.nix:81:14

       … while evaluating attribute 'PATH' of derivation 'coreutils-9.4'

         at /Users/monson/Projects/nixpkgs/pkgs/os-specific/linux/minimal-bootstrap/bash/2.nix:93:7:

           92|       SHELL = "${bash_2_05}/bin/bash";
           93|       PATH = lib.makeBinPath ((env.nativeBuildInputs or []) ++ [
             |       ^
           94|         bash_2_05

       … from call site

         at /Users/monson/Projects/nixpkgs/pkgs/os-specific/linux/minimal-bootstrap/bash/2.nix:93:14:

           92|       SHELL = "${bash_2_05}/bin/bash";
           93|       PATH = lib.makeBinPath ((env.nativeBuildInputs or []) ++ [
             |              ^
           94|         bash_2_05

       … while calling 'makeSearchPathOutput'

         at /Users/monson/Projects/nixpkgs/lib/strings.nix:182:5:

          181|     # List of packages
          182|     pkgs: makeSearchPath subDir (map (lib.getOutput output) pkgs);
             |     ^
          183|

       … from call site

         at /Users/monson/Projects/nixpkgs/lib/strings.nix:182:11:

          181|     # List of packages
          182|     pkgs: makeSearchPath subDir (map (lib.getOutput output) pkgs);
             |           ^
          183|

       … while calling 'makeSearchPath'

         at /Users/monson/Projects/nixpkgs/lib/strings.nix:162:5:

          161|     # List of base paths
          162|     paths:
             |     ^
          163|     concatStringsSep ":" (map (path: path + "/" + subDir) (filter (x: x != null) paths));

       … while calling anonymous lambda

         at /Users/monson/Projects/nixpkgs/lib/strings.nix:163:32:

          162|     paths:
          163|     concatStringsSep ":" (map (path: path + "/" + subDir) (filter (x: x != null) paths));
             |                                ^
          164|

       … from call site

         at /Users/monson/Projects/nixpkgs/pkgs/stdenv/generic/check-meta.nix:449:16:

          448|         {
          449|           no = handleEvalIssue { inherit meta attrs; } { inherit (validity) reason errormsg; };
             |                ^
          450|           warn = handleEvalWarning { inherit meta attrs; } { inherit (validity) reason errormsg; };

       … while calling 'handleEvalIssue'

         at /Users/monson/Projects/nixpkgs/pkgs/stdenv/generic/check-meta.nix:226:38:

          225|
          226|   handleEvalIssue = { meta, attrs }: { reason , errormsg ? "" }:
             |                                      ^
          227|     let

       error: Package ‘tinycc-musl-unstable-2023-04-20-compiler’ in «unknown-file» is not available on the requested hostPlatform:
         hostPlatform.config = "x86_64-apple-darwin"
         package.meta.platforms = [
           "i686-linux"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.

```

</details>

### Additional context

I installed coreutils-9.3 on macos, but failed to evaluate nixpkgs recently.  Via `git bisact` it seems should blame a680950c8828624ddc71aadcf1e0ca20db544836 #257559 .

### Notify maintainers

@emilytrau @Ericson2314 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(monson): `"nixpkgs"`
 - nixpkgs: `/Users/monson/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by 06kellyjac**
Breaks evaluation for other platforms being visible so only
show the package set for supported platforms

## Description of changes

Attempts to resolve #259731

`nix-env -f ./. -u --dry-run -v --show-trace --argstr system x86_64-darwin` passed on x86_64-linux but i'm pretty sure this worked before the change so I'm not convinced this did anything so need to test on a real darwin machine

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Setting the platforms to linux or more specifically the supported systems should work

https://github.com/NixOS/nixpkgs/blob/42e11c898ab9a06304b5177fa82bef5399748bf0/pkgs/os-specific/linux/minimal-bootstrap/coreutils/default.nix#L87

Currently they're marked unix

**Comment by 06kellyjac** [comment]
Well the package itself probably does build for various Unix platforms, it's just the dependencies at the bottom dont yet

**Comment by Artturin** [comment]
Then their platforms can be set

**Comment by emilytrau** [comment]
Closed by #259934

**Pull request closed without merging**
