### PR TITLE
nixos/factorio: add stateDir and requireUserVerification option

### PR DESCRIPTION
**Pull request by The-M1k3y**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Tested with the following configuration:
```
{ config, pkgs, ... }:

{
	services.factorio = {
		enable = true;
		autosave-interval = 10;
		description = "example";
		game-name = "example";
		stateDir = "/data/factorio";
		requireUserVerification = false;
	};
}
```
- [X] Tested with the following configuration:
```
{ config, pkgs, ... }:

{
	services.factorio = {
		enable = true;
		autosave-interval = 10;
		description = "example";
		game-name = "example";
	};
}
```
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by The-M1k3y** [comment]
@elitak @bflyblue

**Comment by bflyblue** [comment]
Looks good to me!

**Comment by elitak** [comment]
👍

**Comment by The-M1k3y** [comment]
Good, would someone please merge it?

**Comment by orivej** [comment]
Thanks!

**Pull request merged**
