### PR TITLE
gmic: 3.2.0 → 3.2.1

### LINKED ISSUE #217082: Build failure: gmic
### Steps To Reproduce

1. build *gmic* from `master`

### Build log

```
/nix/store/cfdmgiycczhapzxgqg5m5y8a42lc7lak-cimg-3.2.1/include/CImg.h:32463:14: note:   candidate expects 7 arguments, 6 provided
/build/source/src/gmic.cpp: In instantiation of 'gmic_library::gmic_image<T>& gmic_library::gmic_image<T>::rol(const char*, gmic_library::gmic_list<T>&) [with T = float]':
/build/source/src/gmic.cpp:11742:9:   required from 'gmic& gmic::_run(const gmic_library::gmic_list<char>&, unsigned int&, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&, gmic_library::gmic_list<T>&, >
/build/source/src/gmic.cpp:5406:14:   required from 'gmic& gmic::_run(const gmic_library::gmic_list<char>&, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&) [with T = float]'
/build/source/src/gmic.cpp:4483:9:   required from 'gmic& gmic::_gmic(const char*, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&, const char*, bool, float*, bool*) [with T = float]'
/build/source/src/gmic.cpp:2901:15:   required from here
/build/source/src/gmic.cpp:1767:28: error: no matching function for call to 'gmic_library::gmic_image<float>::_fill(const char* const&, bool, int, gmic_library::gmic_list<float>*, const char [4], gmic_library::gmi>
 1767 |   return rol((+*this)._fill(expression,true,1,&images,"rol",this));
      |              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/cfdmgiycczhapzxgqg5m5y8a42lc7lak-cimg-3.2.1/include/CImg.h:32463:14: note: candidate: 'gmic_library::gmic_image<T>& gmic_library::gmic_image<T>::_fill(const char*, bool, unsigned int, gmic_library::gmic>
32463 |     CImg<T>& _fill(const char *const expression, const bool repeat_values, const unsigned int mode,
      |              ^~~~~
/nix/store/cfdmgiycczhapzxgqg5m5y8a42lc7lak-cimg-3.2.1/include/CImg.h:32463:14: note:   candidate expects 7 arguments, 6 provided
/build/source/src/gmic.cpp: In instantiation of 'gmic_library::gmic_image<T>& gmic_library::gmic_image<T>::ror(const char*, gmic_library::gmic_list<T>&) [with T = float]':
/build/source/src/gmic.cpp:11755:9:   required from 'gmic& gmic::_run(const gmic_library::gmic_list<char>&, unsigned int&, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&, gmic_library::gmic_list<T>&, >
/build/source/src/gmic.cpp:5406:14:   required from 'gmic& gmic::_run(const gmic_library::gmic_list<char>&, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&) [with T = float]'
/build/source/src/gmic.cpp:4483:9:   required from 'gmic& gmic::_gmic(const char*, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&, const char*, bool, float*, bool*) [with T = float]'
/build/source/src/gmic.cpp:2901:15:   required from here
/build/source/src/gmic.cpp:1771:28: error: no matching function for call to 'gmic_library::gmic_image<float>::_fill(const char* const&, bool, int, gmic_library::gmic_list<float>*, const char [4], gmic_library::gmi>
 1771 |   return ror((+*this)._fill(expression,true,1,&images,"ror",this));
      |              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/cfdmgiycczhapzxgqg5m5y8a42lc7lak-cimg-3.2.1/include/CImg.h:32463:14: note: candidate: 'gmic_library::gmic_image<T>& gmic_library::gmic_image<T>::_fill(const char*, bool, unsigned int, gmic_library::gmic>
32463 |     CImg<T>& _fill(const char *const expression, const bool repeat_values, const unsigned int mode,
      |              ^~~~~
/nix/store/cfdmgiycczhapzxgqg5m5y8a42lc7lak-cimg-3.2.1/include/CImg.h:32463:14: note:   candidate expects 7 arguments, 6 provided
/build/source/src/gmic.cpp: In instantiation of 'gmic_library::gmic_image<T>& gmic_library::gmic_image<T>::operator_minuseq(const char*, gmic_library::gmic_list<T>&) [with T = float]':
/build/source/src/gmic.cpp:12356:9:   required from 'gmic& gmic::_run(const gmic_library::gmic_list<char>&, unsigned int&, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&, gmic_library::gmic_list<T>&, >
/build/source/src/gmic.cpp:5406:14:   required from 'gmic& gmic::_run(const gmic_library::gmic_list<char>&, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&) [with T = float]'
/build/source/src/gmic.cpp:4483:9:   required from 'gmic& gmic::_gmic(const char*, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&, const char*, bool, float*, bool*) [with T = float]'
/build/source/src/gmic.cpp:2901:15:   required from here
/build/source/src/gmic.cpp:1666:35: error: no matching function for call to 'gmic_library::gmic_image<float>::_fill(const char* const&, bool, int, gmic_library::gmic_list<float>*, const char [11], gmic_library::gm>
 1666 |   return operator-=((+*this)._fill(expression,true,1,&images,"operator-=",this));
      |                     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/cfdmgiycczhapzxgqg5m5y8a42lc7lak-cimg-3.2.1/include/CImg.h:32463:14: note: candidate: 'gmic_library::gmic_image<T>& gmic_library::gmic_image<T>::_fill(const char*, bool, unsigned int, gmic_library::gmic>
32463 |     CImg<T>& _fill(const char *const expression, const bool repeat_values, const unsigned int mode,
      |              ^~~~~
/nix/store/cfdmgiycczhapzxgqg5m5y8a42lc7lak-cimg-3.2.1/include/CImg.h:32463:14: note:   candidate expects 7 arguments, 6 provided
/build/source/src/gmic.cpp: In instantiation of 'gmic_library::gmic_image<T>& gmic_library::gmic_image<T>::operator_xoreq(const char*, gmic_library::gmic_list<T>&) [with T = float]':
/build/source/src/gmic.cpp:13753:9:   required from 'gmic& gmic::_run(const gmic_library::gmic_list<char>&, unsigned int&, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&, gmic_library::gmic_list<T>&, >
/build/source/src/gmic.cpp:5406:14:   required from 'gmic& gmic::_run(const gmic_library::gmic_list<char>&, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&) [with T = float]'
/build/source/src/gmic.cpp:4483:9:   required from 'gmic& gmic::_gmic(const char*, gmic_library::gmic_list<T>&, gmic_library::gmic_list<char>&, const char*, bool, float*, bool*) [with T = float]'
/build/source/src/gmic.cpp:2901:15:   required from here
/build/source/src/gmic.cpp:1712:35: error: no matching function for call to 'gmic_library::gmic_image<float>::_fill(const char* const&, bool, int, gmic_library::gmic_list<float>*, const char [11], gmic_library::gm>
 1712 |   return operator^=((+*this)._fill(expression,true,1,&images,"operator^=",this));
      |                     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/cfdmgiycczhapzxgqg5m5y8a42lc7lak-cimg-3.2.1/include/CImg.h:32463:14: note: candidate: 'gmic_library::gmic_image<T>& gmic_library::gmic_image<T>::_fill(const char*, bool, unsigned int, gmic_library::gmic>
32463 |     CImg<T>& _fill(const char *const expression, const bool repeat_values, const unsigned int mode,
      |              ^~~~~
/nix/store/cfdmgiycczhapzxgqg5m5y8a42lc7lak-cimg-3.2.1/include/CImg.h:32463:14: note:   candidate expects 7 arguments, 6 provided
```

### Additional context

There are more of those function arity errors, but just a small sample since they're the same. I'm going to assume #217015 pull in today has something to do with it.

### Notify maintainers

no maintainer? @AndersonTorres merged #217015 and it shows failures for gmic. gmic is used for me in GIMP and darktable.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.12, NixOS, 23.05 (Stoat), 23.05.20230218.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(toastal): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by toastal**
###### Description of changes

Fixes #217082. Should help with broken builds for GIMP and darktable as well.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by toastal** [comment]
```console
$ nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"
...
3 packages failed to build:
gimp-with-plugins gimpPlugins.gmic gmic-qt

3 packages built:
darktable gmic photoprism
```

**Comment by toastal** [comment]
Attempted `gmic-qt` with

```nix
{
  version = "3.2.1";

  src = fetchFromGitHub {
    owner = "c-koi";
    repo = "gmic-qt";
    rev = "v.${version}";
    sha256 = "sha256-z+GtYLBcHVufXwdeSd8WKmPmU1+/EKMv26kNaEgyt5w=";
  };
}
```

But got a build failure. I don't do C++.

```
[30/96] Building CXX object CMakeFiles/gmic_qt.dir/src/FilterSelector/FiltersModelReader.cpp.o
FAILED: CMakeFiles/gmic_qt.dir/src/FilterSelector/FiltersModelReader.cpp.o 
/nix/store/l0fvy72hpfdpjjs3dk4112f57x7r3dlm-gcc-wrapper-12.2.0/bin/g++ -DGMIC_HOST=standalone -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_WIDGETS_LIB -D_IS_LINUX_ -D_IS_UNIX_ -Dcimg_appname=\"gmic\" -Dcimg_display=1 -Dcimg_use_abort -Dcimg_use_cpp11=1 -Dcimg_use_curl -Dcimg_use_fftw3 -Dcimg_use_openmp -Dcimg_use_png -Dcimg_use_vt100 -Dcimg_use_zlib -Dgmic_community -Dgmic_core -Dgmic_gui -Dgmic_is_parallel -I/build/source/build -I/build/source -I/build/source/build/gmic_qt_autogen/include -I/build/source/src -isystem /nix/store/f12pqvwk7zd90yikqsx1rp0kjsxa2fk2-qtbase-5.15.8-dev/include/QtCore -isystem /nix/store/f12pqvwk7zd90yikqsx1rp0kjsxa2fk2-qtbase-5.15.8-dev/./mkspecs/linux-g++ -isystem /nix/store/f12pqvwk7zd90yikqsx1rp0kjsxa2fk2-qtbase-5.15.8-dev/include/QtWidgets -isystem /nix/store/f12pqvwk7zd90yikqsx1rp0kjsxa2fk2-qtbase-5.15.8-dev/include/QtGui -isystem /nix/store/f12pqvwk7zd90yikqsx1rp0kjsxa2fk2-qtbase-5.15.8-dev/include/QtNetwork -DNDEBUG -Ofast -fopenmp -fPIC -std=gnu++11 -MD -MT CMakeFiles/gmic_qt.dir/src/FilterSelector/FiltersModelReader.cpp.o -MF CMakeFiles/gmic_qt.dir/src/FilterSelector/FiltersModelReader.cpp.o.d -o CMakeFiles/gmic_qt.dir/src/FilterSelector/FiltersModelReader.cpp.o -c /build/source/src/FilterSelector/FiltersModelReader.cpp
In file included from /build/source/src/FilterSelector/FiltersModelReader.cpp:41:
/nix/store/gvs63afis09j2g0h63nlralbfbcingyg-gmic-3.2.1-dev/include/gmic.h:191:21: fatal error: gmic.cpp: No such file or directory
  191 | #define cimg_plugin "gmic.cpp"
      |                     ^~~~~~~~~~
compilation terminated.
[31/96] Building CXX object CM
```

**Comment by AndersonTorres** [comment]
It is exposing a bug in gmic? O.o

**Comment by toastal** [comment]
This isn't a bug in gmic so much as it's an update to gmic to align it with the breaking changes in CImg. It compiled gmic and darktable fine for me. The other libraries need to be updated as well, but I'm not a C++ developer and I'm also not the maintainer (or a users) of any of these depending projects.

**Comment by AndersonTorres** [comment]
The message is clear to me:

> In file included from /build/source/src/FilterSelector/FiltersModelReader.cpp:41:
/nix/store/gvs63afis09j2g0h63nlralbfbcingyg-**gmic-3.2.1-dev**/include/gmic.h:191:21: fatal error: gmic.cpp: No such file or directory
  191 | #define cimg_plugin "gmic.cpp"

Somehow it exposes some bug from gmic.

**Comment by toastal** [comment]
Is this a bug in gmic or gmic-qt?

**Comment by AndersonTorres** [comment]
Now I am confused.
According to you (and the review tool) it does not break darktable, but it breaks gmic-qt.

**Comment by toastal** [comment]
Yes, this fixes darktable + photoprism, but there are lingering issues elsewhere. Someone on Matrix says Krita and GIMP are reliant on gmic-qt working which is a pretty big deal--otherwise I'd shrug and just mark gmic-qt as broken.

**Comment by lilyinstarlight** [comment]
I was the person on Matrix. Just the GMIC plugins for GIMP and Krita use gmic-qt (although it seems upstream dropped the Krita plugin so I guess it's just the GIMP plugin now). It's already broken on master so this version bump is not a regression for those and it's also just broken upstream

Fixing those 3 failing packages should not hold up merge for this PR (I'll give more context later bit I'm still on mobile)

**Comment by lilyinstarlight** [comment]
Cross-linking the open issue for gmic-qt being broken since 3.2.0: #212563

**Comment by toastal** [comment]
@lilyinstarlight thanks for popping in. You're clearly more knowledgeable than I at the topic!

**Comment by lilyinstarlight** [comment]
> @lilyinstarlight thanks for popping in. You're clearly more knowledgeable than I at the topic!

Yeah, unfortunately I dove into it when it broke with 3.2.0 because I had `gimp-with-plugins` in my config (now I just have `gimp`), but wading through cimg/gmic/gmic-qt code and commits turned out not to be the best thing for my sanity 🙃

**Comment by AndersonTorres** [comment]
Can we supercede?

https://github.com/NixOS/nixpkgs/pull/217187#pullrequestreview-1304890328

**Comment by toastal** [comment]
will be fixed by #217187

**Pull request closed without merging**
