### PR TITLE
Revert "squashfuse: init at 0.1.101"

### PR DESCRIPTION
**Pull request by Mic92**
This reverts commit 17210fee46826873a623ffd6b691da3d897277e3.

###### Motivation for this change

cc @Profpatsch @bignaux 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
context: https://github.com/NixOS/nixpkgs/pull/34663#issuecomment-364464078

**Comment by Profpatsch** [comment]
+1, @bignaux are you still interested in resubmitting the commit? I could implement my proposed changes if you want, or let’s talk about how we should proceed.

**Comment by bignaux** [comment]
@Profpatsch : feel free to propose another proposition , but i don't see why the code in the project i've mentioned was worse than your proposal.

**Comment by Profpatsch** [comment]
Okay, then feel free to open another pull request.

**Pull request merged**
