### PR TITLE
libqtav: 1.12.0 -> git-2020-09-10

### PR DESCRIPTION
**Pull request by callahad**
###### Motivation for this change

This un-breaks libqtav by upgrading it to the current upstream HEAD.
Previously, Qtav was broken by the Qt 5.12 -> 5.14 migration (#84232).
See commit 819bb63d5c1ff038f7cd39bb0fa7a4f9564ce000

This patch also re-adds libqtav to digikam's list of dependencies,
restoring support for video playback.
This effectively reverts commit 5194e7c0cbb4601df1a57531bf5955c35bbf4314

As digikam is currently the only derivation that references libqtav,
upgrading to an pre-release revision poses minimal risk.

Lastly, this un-pins ffmpeg_3; libqtav works fine with current ffmpeg.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by AndersonTorres** [comment]
Can you split the PR in two commits, one for each file?

**Comment by callahad** [comment]
@AndersonTorres Done :slightly_smiling_face:

**Review by ttuegel — APPROVED** [review]

**Comment by ttuegel** [comment]
Thanks!

**Comment by jraygauthier** [comment]
Good job :+1:

**Pull request merged**
