### PR TITLE
Add automatic generation of library function documentation

### PR DESCRIPTION
**Pull request by tazjin**
**Important**: Please also see #49275. Only one of these pull requests should be merged.

cc: @Infinisil @grahamc  

-------

Modifies the build process of the manual to invoke nixdoc
automatically to generate XML files with function documentation.

Currently documentation is present for five of the files in `lib/`.

To add another file to the generated docs, both
`doc/functions/library.xml` and `doc/lib-function-docs.nix` must be
updated.

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
I'm very much in favor of this approach. Having checked in the generated xml files wouldn't really serve any direct purpose, because they're neither nice to look at nor editable (as edits would get overridden).

**Comment by tazjin** [comment]
One note about this: The path for overrides will not work with this version (at the moment). That requires a change in `nixdoc`.

Overrides are not actually in use yet though, so it does not matter much for now.

**Review by FRidh — APPROVED** [review]
This looks very good. I think we need to update the docstrings in `attrsets` a bit with the info that's currently in the xml, and then we can have that one generated as well.

**Comment by tazjin** [comment]
> I think we need to update the docstrings in attrsets a bit with the info that's currently in the xml, and then we can have that one generated as well.

Currently there is a little blocker for that, `nixdoc` does not yet support multiple examples in the markup and we haven't been able to agree on any format to use for it so far. I have a suggestion for how it could work [in this issue](https://github.com/tazjin/nixdoc/issues/6), but it's not implemented yet.

As an alternative we have the override feature, where XML blobs can be dropped in to replace the documentation for a specific function - however, I can't figure out the syntax for multiple root-level elements in an override anymore. I'm sure this is something I tested with @grahamc at NixCon, so it does work - somehow. Going to have to dive into DocBook docs a little bit.

**Pull request merged**
