### PR TITLE
Backport #46453

### PR DESCRIPTION
**Pull request by ElvishJerricco**
Backporting #46453

Not sure if this is something we actually want to backport, since there's a chance it might break some workflows for anyone who's already upgraded to 18.09. But 18.09 is still pretty new, and this *shouldn't* break any existing code. So my preference would be to backport it.

### CODE REVIEW

**Comment by samueldr** [comment]
HI! Always nice to see backports. Though, I *do not know* whether this should be backported or not. I know next to nothing about the whole haskell world, and also close to nothing to the haskell things in Nixpkgs.

You said: "there's a chance it might break some workflows" and "this shouldn't break any existing code". When not knowing what the original PR did, and even after a quick read through the original PR description, these statements seem antithetical.

Is it possible to:

 1. Get an overview of what the PR changes. (I don't see documentation or release notes updates in the original PR)
 1. A quick overview of what kind of situation this would break a user's workflow, assuming the original workflow wasn't wrong and broken by *whatever this fixes*.

I think (hope) it would help gauge whether this update is relevant to backport.

Thanks!

**Comment by ElvishJerricco** [comment]
@samuelrivas Yea, the "chance it might break some workflows" was intended to fit within the "shouldn't" part of "shouldn't break any existing code." i.e. it is a slight change in mechanism, so it's hard to say for sure that nothing will break even though it seems unlikely that anything would break.

Basically, we've change `env` to be based on `shellFor`. `shellFor` is designed to do much the same job as `env` was originally, except to get the inputs of multiple packages instead of just one. So it's possible that in the generalization from one to many we failed to port some behavior or something along those lines. It looks to me like `shellFor` should cover everything correctly, but the fact that it's a new and different system gives me pause for backporting to a stable channel.

My preference would be to do the backport:

- This change is largely an implementation detail, so it's the kind of change that can be easily reverted if it turns out to be a bad change to shove on a stable channel.
- It's a change that I feel fairly confident is a stable change.

**Comment by samuelrivas** [comment]
quoting the right Samuel ;) @samueldr

**Comment by ElvishJerricco** [comment]
Can this be accepted?

**Pull request merged**
