### PR TITLE
 python311Packages.pysigma: 0.10.4 -> 0.10.5 

### PR DESCRIPTION
**Pull request by fabaff**
Diff: https://github.com/SigmaHQ/pySigma/compare/refs/tags/v0.10.4...v0.10.5

Changelog: https://github.com/SigmaHQ/pySigma/releases/tag/v0.10.5

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
There are a couple of projects that depend on this one that have pinned their dependency on pysigma 0.9. This part of the release notes also sounds a little scary:

- The order of ProcessingPipeline parameters has changed. New elements postprocessing_items and finalizers were added between items and vars.
- The order of ProcessingItem parameters has changed. The identifier is now located after rule_conditions and before detection item and field name conditions.

Although from the couple of projects that depend on this I sampled, they all are using named keyword arguments and are unaffected.

**Comment by fabaff** [comment]
Usually all consumers are updated after major changes in `pysigma`. MOst bachends and pipelines are under the umbrella of SigmaHQ.

**Comment by tjni** [comment]
That makes sense. Are you planning to update the others as well?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 247217` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>38 packages built:</summary>
  <ul>
    <li>python310Packages.pysigma</li>
    <li>python310Packages.pysigma-backend-elasticsearch</li>
    <li>python310Packages.pysigma-backend-elasticsearch.dist</li>
    <li>python310Packages.pysigma-backend-insightidr</li>
    <li>python310Packages.pysigma-backend-insightidr.dist</li>
    <li>python310Packages.pysigma-backend-opensearch</li>
    <li>python310Packages.pysigma-backend-opensearch.dist</li>
    <li>python310Packages.pysigma-backend-qradar</li>
    <li>python310Packages.pysigma-backend-qradar.dist</li>
    <li>python310Packages.pysigma-backend-splunk</li>
    <li>python310Packages.pysigma-backend-splunk.dist</li>
    <li>python310Packages.pysigma-pipeline-crowdstrike</li>
    <li>python310Packages.pysigma-pipeline-crowdstrike.dist</li>
    <li>python310Packages.pysigma-pipeline-sysmon</li>
    <li>python310Packages.pysigma-pipeline-sysmon.dist</li>
    <li>python310Packages.pysigma-pipeline-windows</li>
    <li>python310Packages.pysigma-pipeline-windows.dist</li>
    <li>python310Packages.pysigma.dist</li>
    <li>python311Packages.pysigma</li>
    <li>python311Packages.pysigma-backend-elasticsearch</li>
    <li>python311Packages.pysigma-backend-elasticsearch.dist</li>
    <li>python311Packages.pysigma-backend-insightidr</li>
    <li>python311Packages.pysigma-backend-insightidr.dist</li>
    <li>python311Packages.pysigma-backend-opensearch</li>
    <li>python311Packages.pysigma-backend-opensearch.dist</li>
    <li>python311Packages.pysigma-backend-qradar</li>
    <li>python311Packages.pysigma-backend-qradar.dist</li>
    <li>python311Packages.pysigma-backend-splunk</li>
    <li>python311Packages.pysigma-backend-splunk.dist</li>
    <li>python311Packages.pysigma-pipeline-crowdstrike</li>
    <li>python311Packages.pysigma-pipeline-crowdstrike.dist</li>
    <li>python311Packages.pysigma-pipeline-sysmon</li>
    <li>python311Packages.pysigma-pipeline-sysmon.dist</li>
    <li>python311Packages.pysigma-pipeline-windows</li>
    <li>python311Packages.pysigma-pipeline-windows.dist</li>
    <li>python311Packages.pysigma.dist</li>
    <li>sigma-cli</li>
    <li>sigma-cli.dist</li>
  </ul>
</details>

**Pull request merged**
