### PR TITLE
Update IPython to 3.1.0

### PR DESCRIPTION
**Pull request by utdemir**
This also updates pyzmq and tornado.

### CODE REVIEW

**Comment by utdemir** [comment]
Hi,

@bjornfor , I guess the Travis error is irrelevant of this patch. Can you review and merge if everything is okay? 

This patch finally makes IHaskell work, it'll be nice to have it on master.

**Comment by bjornfor** [comment]
Hi @utdemir,

Please bump each package in a separate commit. (I assume they are not _so_ dependent on each other, that all have to be bumped in the same commit?)

**Comment by edwtjo** [comment]
This seems to break nixops.

**Comment by utdemir** [comment]
@bjornfor I just meant to upgrade IPython, but its notebook didn't work without the new versions of pyzmq and tornado(and a new dependency, jsonschema). Should I still split this into three?

**Comment by bjornfor** [comment]
@utdemir: IMHO, yes, that's preferrable.

And +1 if you would explain (in the commit message) why jsonschema is added. Is it a new dependency, or is it actually also required for our current ipython version, but the notebook thingy doesn't actually work right now? If the latter, even the ipython commit should be split in two; one bugfix (adding jsonschema) and one feature (update package).

Sorry, I'm a git log freak :-)

**Comment by domenkozar** [comment]
@edwtjo nixops, how does nixops depend on any library in this PR?

**Comment by edwtjo** [comment]
@domenkozar AFAICT the hash change from httpretty revealed that it was missing the certifi dependency. I took the liberty of splitting the commits as per @bjornfor request and commit them in ebe3802a8f117989251f1af32ad0397e9c236c60 a5b17ecc945eda6e7248ff7cf2bd17430f003e9a c9f7c574eca907070066b75a459688433b587fb1

**Comment by utdemir** [comment]
@edwtjo Oh, I'm sorry for not following this PR. Thank you.

**Pull request closed without merging**
