### PR TITLE
a52dec: 0.7.4 -> 0.8.0

### LINKED ISSUE #296886: Build failure: a52dec
### Steps To Reproduce

try to build a52dec from source with substitutes off

### Additional context
I've had this override in place for a few weeks now and I don't think I have the original failed build log any more but I don't think anything has changed.
Working mirror:
```nix
                                           a52dec = prev.a52dec.overrideAttrs (attrs: rec {
                                             version = "0.7.4";
                                             src = prev.fetchurl {
                                               url = "https://ftp2.osuosl.org/pub/blfs/conglomeration/a52dec/a52dec-${version}.tar.gz";
                                               sha256 = "oh1ySrOzkzMwGUNTaH34LEdbXfuZdRPu9MJd5shl7DM=";
                                             };
                                           });
```
This taking it from some BLFS mirror because that's the first reasonable source I found it at.
I think the files are gone from sourceforge or some api change at sourceforge is preventing download for the src defined in nixpkgs.

### Notify maintainers
@wegank 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by wegank**
## Description of changes

Closes #296886.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sdht0** [comment]
I actually tried bumping this a week back and I was facing atleast 8 build failures, though some looked unrelated. Didn't have to investigate further. Just thought should let you know.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 296889` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>emulationstation</li>
    <li>golden-cheetah-bin</li>
    <li>gscrabble</li>
    <li>gscrabble.dist</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>badlion-client</li>
    <li>cinelerra</li>
    <li>davinci-resolve-studio</li>
    <li>hqplayerd</li>
    <li>obs-studio-plugins.advanced-scene-switcher</li>
    <li>obs-studio-plugins.obs-replay-source</li>
    <li>obs-studio-plugins.obs-source-clone</li>
    <li>paperwork</li>
    <li>paperwork.dist</li>
    <li>pureref</li>
    <li>python311Packages.paperwork-backend</li>
    <li>python311Packages.paperwork-backend.dist</li>
    <li>python311Packages.paperwork-shell</li>
    <li>python311Packages.paperwork-shell.dist</li>
    <li>radicle-upstream</li>
    <li>tiscamera</li>
  </ul>
</details>
<details>
  <summary>400 packages built:</summary>
  <ul>
    <li>Sylk</li>
    <li>a52dec</li>
    <li>altair</li>
    <li>alvr</li>
    <li>amberol</li>
    <li>anilibria-winmaclinux</li>
    <li>anki-bin</li>
    <li>anytype</li>
    <li>appimage-run</li>
    <li>arcan</li>
    <li>arcan-all-wrapped</li>
    <li>arcan-wrapped</li>
    <li>arduino-ide</li>
    <li>audio-recorder</li>
    <li>bazecor</li>
    <li>beekeeper-studio</li>
    <li>beeper</li>
    <li>beets (beetsPackages.beets ,beetsPackages.beets-stable)</li>
    <li>beets-unstable (beetsPackages.beets-unstable)</li>
    <li>beets-unstable.dist (beetsPackages.beets-unstable.dist)</li>
    <li>beets-unstable.doc (beetsPackages.beets-unstable.doc)</li>
    <li>beets-unstable.man (beetsPackages.beets-unstable.man)</li>
    <li>beets.dist (beetsPackages.beets-stable.dist ,beetsPackages.beets.dist)</li>
    <li>beets.doc (beetsPackages.beets-stable.doc ,beetsPackages.beets.doc)</li>
    <li>beets.man (beetsPackages.beets-stable.man ,beetsPackages.beets.man)</li>
    <li>beetsPackages.alternatives</li>
    <li>beetsPackages.alternatives.dist</li>
    <li>beetsPackages.beets-minimal</li>
    <li>beetsPackages.beets-minimal.dist</li>
    <li>beetsPackages.beets-minimal.doc</li>
    <li>beetsPackages.beets-minimal.man</li>
    <li>beetsPackages.copyartifacts</li>
    <li>beetsPackages.copyartifacts.dist</li>
    <li>beetsPackages.extrafiles</li>
    <li>beetsPackages.extrafiles.dist</li>
    <li>betterdiscord-installer</li>
    <li>bloomrpc</li>
    <li>bootstrap-studio</li>
    <li>bottles</li>
    <li>brasero</li>
    <li>brasero-original</li>
    <li>budgie.budgie-control-center</li>
    <li>budgie.budgie-control-center.debug</li>
    <li>buttercup-desktop</li>
    <li>buzztrax</li>
    <li>byzanz</li>
    <li>caido</li>
    <li>calls</li>
    <li>calls.devdoc</li>
    <li>caprine-bin</li>
    <li>cat9-wrapped</li>
    <li>chrysalis</li>
    <li>cider</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>cinnamon.pix</li>
    <li>clapper</li>
    <li>clementine</li>
    <li>codux</li>
    <li>cozy</li>
    <li>cozy-drive</li>
    <li>crypto-org-wallet</li>
    <li>davinci-resolve</li>
    <li>deepin.deepin-music</li>
    <li>deepin.deepin-voice-note</li>
    <li>denemo</li>
    <li>deskreen</li>
    <li>devdocs-desktop</li>
    <li>dissent</li>
    <li>dropbox-cli</li>
    <li>dropbox-cli.nautilusExtension</li>
    <li>durden-wrapped</li>
    <li>eaglemode</li>
    <li>eiciel</li>
    <li>eiciel.nautilusExtension</li>
    <li>electron-mail</li>
    <li>electronplayer</li>
    <li>eolie</li>
    <li>epiphany (gnome.epiphany)</li>
    <li>evince (gnome.evince)</li>
    <li>evince.dev (gnome.evince.dev)</li>
    <li>evince.devdoc (gnome.evince.devdoc)</li>
    <li>exactaudiocopy</li>
    <li>exaile</li>
    <li>firefly-desktop</li>
    <li>flexoptix-app</li>
    <li>fluent-reader</li>
    <li>framesh</li>
    <li>fspy</li>
    <li>game-rs</li>
    <li>glom</li>
    <li>glom.dev</li>
    <li>glom.devdoc</li>
    <li>glom.doc</li>
    <li>glom.lib</li>
    <li>gmrender-resurrect</li>
    <li>gnome-network-displays</li>
    <li>gnome-photos</li>
    <li>gnome-photos.installedTests</li>
    <li>gnome.cheese</li>
    <li>gnome.cheese.devdoc</li>
    <li>gnome.cheese.man</li>
    <li>gnome.file-roller</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-control-center.debug</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.nautilus-python.dev</li>
    <li>gnome.nautilus-python.devdoc</li>
    <li>gnome.nautilus-python.doc</li>
    <li>gnome.nautilus.dev</li>
    <li>gnome.nautilus.devdoc</li>
    <li>gnome.rygel</li>
    <li>gnome.rygel.dev</li>
    <li>gnome.sushi</li>
    <li>gnome.totem</li>
    <li>gnomeExtensions.gtk4-desktop-icons-ng-ding</li>
    <li>goodvibes</li>
    <li>gst123</li>
    <li>gst_all_1.gst-plugins-ugly</li>
    <li>gst_all_1.gst-plugins-ugly.dev</li>
    <li>gthumb</li>
    <li>hamsket</li>
    <li>handbrake</li>
    <li>heroic</li>
    <li>hifile</li>
    <li>hoppscotch</li>
    <li>hqplayer-desktop</li>
    <li>hqplayer-desktop.doc</li>
    <li>immersed-vr</li>
    <li>irccloud</li>
    <li>itch</li>
    <li>jan</li>
    <li>jbrowse</li>
    <li>jetbrains-toolbox</li>
    <li>joplin-desktop</li>
    <li>kaffeine</li>
    <li>kchat</li>
    <li>kdePackages.elisa</li>
    <li>kdePackages.elisa.debug</li>
    <li>kdePackages.elisa.dev</li>
    <li>kdePackages.kasts</li>
    <li>kdePackages.kasts.debug</li>
    <li>kdePackages.kasts.dev</li>
    <li>kdePackages.phonon-vlc</li>
    <li>kdePackages.phonon-vlc.debug</li>
    <li>kdePackages.phonon-vlc.dev</li>
    <li>keet</li>
    <li>kodiPackages.steam-launcher</li>
    <li>kooha</li>
    <li>kphotoalbum</li>
    <li>lbry</li>
    <li>ldtk</li>
    <li>ledger-live-desktop</li>
    <li>lens</li>
    <li>libreoffice (libreoffice-still)</li>
    <li>libreoffice-fresh</li>
    <li>libreoffice-fresh-unwrapped</li>
    <li>libreoffice-qt</li>
    <li>libreoffice-unwrapped (libreoffice-still-unwrapped)</li>
    <li>libsForQt5.dragon (plasma5Packages.dragon)</li>
    <li>libsForQt5.dragon.dev (plasma5Packages.dragon.dev)</li>
    <li>libsForQt5.elisa (plasma5Packages.elisa)</li>
    <li>libsForQt5.elisa.dev (plasma5Packages.elisa.dev)</li>
    <li>libsForQt5.kdenlive (plasma5Packages.kdenlive)</li>
    <li>libsForQt5.phonon-backend-gstreamer (plasma5Packages.phonon-backend-gstreamer)</li>
    <li>libsForQt5.phonon-backend-vlc (plasma5Packages.phonon-backend-vlc)</li>
    <li>libvlc</li>
    <li>listen1</li>
    <li>lollypop</li>
    <li>losslesscut-bin</li>
    <li>luakit</li>
    <li>lunar-client</li>
    <li>lunatask</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>lutris-unwrapped.dist</li>
    <li>marktext</li>
    <li>mathpix-snipping-tool</li>
    <li>megaglest</li>
    <li>mendeley</li>
    <li>minigalaxy</li>
    <li>minigalaxy.dist</li>
    <li>minitube</li>
    <li>miru</li>
    <li>mobilecoin-wallet</li>
    <li>mockoon</li>
    <li>molotov</li>
    <li>mopidy-bandcamp</li>
    <li>mopidy-bandcamp.dist</li>
    <li>mopidy-iris</li>
    <li>mopidy-iris.dist</li>
    <li>mopidy-jellyfin</li>
    <li>mopidy-jellyfin.dist</li>
    <li>mopidy-local</li>
    <li>mopidy-local.dist</li>
    <li>mopidy-mopify</li>
    <li>mopidy-mopify.dist</li>
    <li>mopidy-mpd</li>
    <li>mopidy-mpd.dist</li>
    <li>mopidy-mpris</li>
    <li>mopidy-mpris.dist</li>
    <li>mopidy-muse</li>
    <li>mopidy-muse.dist</li>
    <li>mopidy-musicbox-webclient</li>
    <li>mopidy-musicbox-webclient.dist</li>
    <li>mopidy-notify</li>
    <li>mopidy-notify.dist</li>
    <li>mopidy-podcast</li>
    <li>mopidy-podcast.dist</li>
    <li>mopidy-scrobbler</li>
    <li>mopidy-scrobbler.dist</li>
    <li>mopidy-somafm</li>
    <li>mopidy-somafm.dist</li>
    <li>mopidy-soundcloud</li>
    <li>mopidy-soundcloud.dist</li>
    <li>mopidy-spotify</li>
    <li>mopidy-spotify.dist</li>
    <li>mopidy-subidy</li>
    <li>mopidy-subidy.dist</li>
    <li>mopidy-tidal</li>
    <li>mopidy-tidal.dist</li>
    <li>mopidy-tunein</li>
    <li>mopidy-tunein.dist</li>
    <li>mopidy-youtube</li>
    <li>mopidy-youtube.dist</li>
    <li>mopidy-ytmusic</li>
    <li>mopidy-ytmusic.dist</li>
    <li>motrix</li>
    <li>mqttx</li>
    <li>museeks</li>
    <li>mycrypto</li>
    <li>nautilus-open-any-terminal</li>
    <li>nautilus-open-any-terminal.dist</li>
    <li>nautilus-open-in-blackbox</li>
    <li>neo4j-desktop</li>
    <li>netease-cloud-music-gtk</li>
    <li>nosql-workbench</li>
    <li>notable</li>
    <li>notesnook</li>
    <li>notion-app-enhanced</li>
    <li>nuclear</li>
    <li>nulloy</li>
    <li>nyxt</li>
    <li>obs-studio</li>
    <li>obs-studio-plugins.droidcam-obs</li>
    <li>obs-studio-plugins.input-overlay</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-3d-effect</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>obs-studio-plugins.obs-command-source</li>
    <li>obs-studio-plugins.obs-composite-blur</li>
    <li>obs-studio-plugins.obs-freeze-filter</li>
    <li>obs-studio-plugins.obs-gradient-source</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-hyperion</li>
    <li>obs-studio-plugins.obs-livesplit-one</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-mute-filter</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-rgb-levels-filter</li>
    <li>obs-studio-plugins.obs-scale-to-sound</li>
    <li>obs-studio-plugins.obs-shaderfilter</li>
    <li>obs-studio-plugins.obs-source-record</li>
    <li>obs-studio-plugins.obs-source-switcher</li>
    <li>obs-studio-plugins.obs-teleport</li>
    <li>obs-studio-plugins.obs-text-pthread</li>
    <li>obs-studio-plugins.obs-transition-table</li>
    <li>obs-studio-plugins.obs-tuna</li>
    <li>obs-studio-plugins.obs-vaapi</li>
    <li>obs-studio-plugins.obs-vertical-canvas</li>
    <li>obs-studio-plugins.obs-vintage-filter</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.obs-webkitgtk</li>
    <li>obs-studio-plugins.obs-websocket</li>
    <li>obs-studio-plugins.waveform</li>
    <li>obs-studio-plugins.wlrobs</li>
    <li>openlens</li>
    <li>osu-lazer-bin</li>
    <li>p3x-onenote</li>
    <li>pantheon.elementary-camera</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-music</li>
    <li>pantheon.elementary-photos</li>
    <li>pantheon.elementary-videos</li>
    <li>pantheon.epiphany</li>
    <li>pantheon.file-roller-contract</li>
    <li>parlatype</li>
    <li>parsify</li>
    <li>peek</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>pipelight</li>
    <li>pipeworld-wrapped</li>
    <li>pithos</li>
    <li>pitivi</li>
    <li>playonlinux</li>
    <li>plexamp</li>
    <li>polypane</li>
    <li>pragha</li>
    <li>prio-wrapped</li>
    <li>protontricks</li>
    <li>protontricks.dist</li>
    <li>protonup-qt</li>
    <li>pympress</li>
    <li>pympress.dist</li>
    <li>python311Packages.python-vlc</li>
    <li>python311Packages.python-vlc.dist</li>
    <li>python312Packages.python-vlc</li>
    <li>python312Packages.python-vlc.dist</li>
    <li>q4wine</li>
    <li>qt-video-wlr</li>
    <li>quodlibet</li>
    <li>quodlibet-full</li>
    <li>quodlibet-full.dist</li>
    <li>quodlibet-full.doc</li>
    <li>quodlibet.dist</li>
    <li>quodlibet.doc</li>
    <li>radiotray-ng</li>
    <li>rambox</li>
    <li>raven-reader</li>
    <li>reaper</li>
    <li>recapp</li>
    <li>remnote</li>
    <li>requestly</li>
    <li>rhythmbox</li>
    <li>rpiplay</li>
    <li>saleae-logic-2</li>
    <li>sayonara</li>
    <li>session-desktop</li>
    <li>simplex-chat-desktop</li>
    <li>sonixd</li>
    <li>sound-juicer</li>
    <li>soundconverter</li>
    <li>soundconverter.dist</li>
    <li>spacedrive</li>
    <li>ssb-patchwork</li>
    <li>station</li>
    <li>steam (steamPackages.steam-fhsenv)</li>
    <li>steam-rom-manager</li>
    <li>steam-run</li>
    <li>steam-tui</li>
    <li>steamPackages.steam-fhsenv-without-steam</li>
    <li>steamcmd (steamPackages.steamcmd)</li>
    <li>strawberry (strawberry-qt5)</li>
    <li>strawberry-qt6</li>
    <li>subtitleeditor</li>
    <li>termplay</li>
    <li>timelens</li>
    <li>timeular</li>
    <li>todoist-electron</li>
    <li>tracker-miners</li>
    <li>transcribe</li>
    <li>trezor-suite</li>
    <li>tuner</li>
    <li>tusk</li>
    <li>tutanota-desktop</li>
    <li>unoconv</li>
    <li>upscayl</li>
    <li>uxplay</li>
    <li>via</li>
    <li>vial</li>
    <li>vkd3d</li>
    <li>vkd3d-proton</li>
    <li>vlc</li>
    <li>vokoscreen-ng</li>
    <li>wine (winePackages.full ,winePackages.stableFull)</li>
    <li>wine-staging (winePackages.stagingFull)</li>
    <li>wine-wayland (winePackages.waylandFull)</li>
    <li>wine64 (wine64Packages.full ,wine64Packages.stableFull)</li>
    <li>wine64Packages.stagingFull</li>
    <li>wine64Packages.unstableFull</li>
    <li>wine64Packages.waylandFull</li>
    <li>winePackages.unstableFull</li>
    <li>wineWow64Packages.full (wineWow64Packages.stableFull)</li>
    <li>wineWow64Packages.stagingFull</li>
    <li>wineWow64Packages.unstableFull</li>
    <li>wineWow64Packages.waylandFull</li>
    <li>wineWowPackages.full (wineWowPackages.stableFull)</li>
    <li>wineWowPackages.stagingFull</li>
    <li>wineWowPackages.unstableFull</li>
    <li>wineWowPackages.waylandFull</li>
    <li>wootility</li>
    <li>wtwitch</li>
    <li>xarcan</li>
    <li>xfce.parole</li>
    <li>xfce.parole.dev</li>
    <li>xivlauncher</li>
    <li>xlights</li>
    <li>yaxg</li>
    <li>ytmdesktop</li>
    <li>zecwallet-lite</li>
    <li>zettlr</li>
    <li>zulip</li>
  </ul>
</details>

**Comment by wegank** [comment]
- [x] badlion-client: not a regression, #272828
- [x] cinelerra: not a regression
- [ ] davinci-resolve-studio: fetch failure, will retry
- [x] hqplayerd: not a regression, #296923
- [x] obs-studio-plugins.advanced-scene-switcher: not a regression, #296944
- [x] obs-studio-plugins.obs-replay-source: not a regression
- [x] obs-studio-plugins.obs-source-clone: not a regression, #296935
- [ ] paperwork
- [x] pureref: not a regression
- [ ] python311Packages.paperwork-backend
- [ ] python311Packages.paperwork-shell
- [x] radicle-upstream: not a regression, #296913
- [x] tiscamera: not a regression

**Comment by wegank** [comment]
I'm not able to build `python311Packages.paperwork-backend` both with and without this PR. Probably ofborg can help?

@ofborg build python311Packages.paperwork-backend

**Comment by wegank** [comment]
> I actually tried bumping this a week back and I was facing atleast 8 build failures, though some looked unrelated. Didn't have to investigate further. Just thought should let you know.

None of the failures are related. I haven't opened a PR for each of them, though.

**Comment by sdht0** [comment]
Nice work @wegank

**Pull request merged**
