### PR TITLE
[20.03] Fix ibus

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Backports the following PRs to stable:
https://github.com/NixOS/nixpkgs/pull/86416 https://github.com/NixOS/nixpkgs/issues/85515
https://github.com/NixOS/nixpkgs/pull/85976 (so we can test that we didn't break wrapGAppsHook on stable with the backports)
https://github.com/NixOS/nixpkgs/pull/85892 https://github.com/NixOS/nixpkgs/pull/85970  https://github.com/NixOS/nixpkgs/pull/85992

The following commits don't belong to a PR:
https://github.com/NixOS/nixpkgs/commit/76f7fc1476cb046404b97a63cb861353d6097f16
https://github.com/NixOS/nixpkgs/commit/c9d988b0e19a2c7203af3b74388c0b754ac17e39

This is another minor bugfix that I thought I might as well backport.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@ofborg test ibus

**Comment by jtojnar** [comment]
Maybe we should backport https://github.com/NixOS/nixpkgs/pull/85976 too.

**Comment by worldofpeace** [comment]
> Maybe we should backport #85976 too.

Good idea. Pushed.

**Comment by worldofpeace** [comment]
Ahh, I need to backport https://github.com/NixOS/nixpkgs/pull/85992 too

**Comment by worldofpeace** [comment]
Okay, now this backport PR got larger than I first intended.

I can now properly test if ibus is working
@ofborg test ibus

**Pull request merged**
