### PR TITLE
rubyPackages: update

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

Noticed `rubyPackages_2_6.gtk2` didn’t build any more. New version seems to fix it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by zimbatm** [comment]
nix-review built everything except:

> rubyPackages.libv8 rubyPackages_2_4.libv8 rubyPackages_2_5.libv8

I don't thing this should be a blocker to merge.

**Comment by zimbatm** [comment]
```
$ nix-build -A rubyPackages.libv8
warning: unknown setting 'experimental-features'
these derivations will be built:
  /nix/store/sp1avshcxayp723xaqfcgahwhxqc59wb-ruby2.6.5-libv8-7.3.492.27.1.drv
building '/nix/store/sp1avshcxayp723xaqfcgahwhxqc59wb-ruby2.6.5-libv8-7.3.492.27.1.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
installing
buildFlags: --with-system-v8=true
WARNING:  You build with buildroot.
  Build root: /
  Bin dir: /nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0/bin
  Gem home: /nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0
Building native extensions with: '--with-system-v8=true'
This could take a while...
ERROR:  Error installing /nix/store/n6j9aksqr2bb6vsd2aiv3i9i2q3v1ady-libv8-7.3.492.27.1.gem:
        ERROR: Failed to build gem native extension.

    current directory: /nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0/gems/libv8-7.3.492.27.1/ext/libv8
/nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/bin/ruby -I /nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/lib/ruby/2.6.0 -r ./siteconf20191228-8-101f4fp.rb extconf.rb --with-system-v8\=true
creating Makefile
/nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:83:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
        from /nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in `chdir'
        from /nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in `setup_build_deps!'
        from /nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:40:in `build_libv8!'
        from /nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0/gems/libv8-7.3.492.27.1/ext/libv8/location.rb:24:in `install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0/gems/libv8-7.3.492.27.1 for inspection.
Results logged to /nix/store/31nix2zsgnnrqn5sckfcyph4rb3nkvhy-ruby2.6.5-libv8-7.3.492.27.1/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/libv8-7.3.492.27.1/gem_make.out
builder for '/nix/store/sp1avshcxayp723xaqfcgahwhxqc59wb-ruby2.6.5-libv8-7.3.492.27.1.drv' failed with exit code 1
error: build of '/nix/store/sp1avshcxayp723xaqfcgahwhxqc59wb-ruby2.6.5-libv8-7.3.492.27.1.drv' failed
```

> unable to fetch v8 source (RuntimeError)

looks like they are ignoring the --with-system-v8=true option now...

**Comment by alyssais** [comment]
> looks like they are ignoring the --with-system-v8=true option now...

Sigh.

I guess we'll have to come up with a script to prefetch v8 for each
version of the gem or something.

**Comment by zimbatm** [comment]
I read that they are shipping the gem with libv8 pre-compiled for most platforms. Potentially we just have to patchelf the binary but I haven't checked if it's true.

**Comment by zimbatm** [comment]
image
So now we need bundix to hash all of them right?

**Comment by alyssais** [comment]
> I read that they are shipping the gem with libv8 pre-compiled for most
> platforms. Potentially we just have to patchelf the binary but I
> haven't checked if it's true.

I'd much rather build from source if possible.  I wonder how feasible it
would be.  It would be a shame to rely on unauditable binaries.  (That
might be fine for people using Bundix in their applications, but I think
we should try to avoid them in Nixpkgs.)

**Comment by zimbatm** [comment]
For that we need some infrastructure from rubygems.

1. Extend the gem spec schema to contain a set of name/URL/sha256 tuples that will be downloaded as part of the installation.
2. Extend rubygems to handle the download and put them in a pre-determined location.
3. Make a big PR campaign to convert existing gems to use that mechanism instead of doing custom downloads.
4. (bonus) Extend the bundle.lock format to also contain that information.

With that in place we will be able to take over the download part with nix.

**Comment by FRidh** [comment]
What's the status of this PR?

**Comment by zimbatm** [comment]
I would be inclined to merge this. Perfect is the enemy of good.

**Pull request merged**
