### PR TITLE
dmd: 2.97.2 -> 2.99.1

### PR DESCRIPTION
**Pull request by Panke**
###### Description of changes

https://dlang.org/changelog/2.099.1.html

###### Things done

- Built on platform(s)
  - [✔] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [✔] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Panke** [comment]
I don't have a darwin box. Can someone look into the error?

**Comment by applePrincess** [comment]
I think we can wait #163989 to fix darwin build.

**Comment by applePrincess** [comment]
Result of `nixpkgs-review pr 170903` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dmd</li>
  </ul>
</details>

**Comment by OPNA2608** [comment]
We may be blocking each other right now, my PR dies on a test that I think your bump is supposed to fix:
https://issues.dlang.org/show_bug.cgi?id=21919

(and possibly some more flaky ones, not sure because they all pass on my machine)

And ideas how to proceed? I don't use Dlang stuff myself. Would you like to try cherry-picking my fix and see if CI is happy?

**Comment by Panke** [comment]
What's the next step here?

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by OPNA2608** [comment]
[2.100.0 was released](https://dlang.org/changelog/2.100.0.html) since this was opened, should it be bumped?

Note that there is a broken test on all versions since a gdb bump, #178128 is needed to fix it.

**Pull request closed without merging**
