### PR TITLE
cmake: 3.26.4 -> 3.27.7

### PR DESCRIPTION
**Pull request by ayum**
## Description of changes

This PR updates cmake from 3.26.4 to 3.27.7 (latest stable version).

Release notes: https://cmake.org/cmake/help/latest/release/3.27.html

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ayum** [comment]
Can't really see what goes wrong from `ofborg-eval-lib-tests` check build log.

I would like to try and fix build failure if someone will point me on build error, though.

**Comment by ayum** [comment]
@ttuegel @lnl7 @AndersonTorres

Advices from you could be helpfull.

**Comment by AndersonTorres** [comment]
I admire you by your courage (or should I say reclessness?) in  trying to update cmake - a dependency of a **huge** amount of packages and therefore always shaky to build - as your first contribution.

Visually the code is OK.
However, because CMake is a dependency of many projects **and** causes a massive rebuild  when updated, it should be rebased over the staging branch.

And, guess what, staging is broken right now. https://github.com/NixOS/nixpkgs/pull/261427

**Comment by ayum** [comment]
@AndersonTorres 

Appreciate your response. Can't expect merging this. My point is different, one side of nix is hermetic build system, but latest minor version of cmake was released roughly a quarter of year now, this is a little bit annoying.

Nevetherless, thank you for your efforts.

**Pull request closed without merging**
