### PR TITLE
julia.withPackages: fix for overrides not in a registry

### PR DESCRIPTION
**Pull request by thomasjm**
## Description of changes

This is a fix for #279853, making it possible to use a package in the `packageOverrides` even if that package doesn't appear in the registry.

I'm not sure if it's a totally comprehensive solution, but I added a test to the test suite for the case presented in the issue.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
@marnym Please test.

**Comment by thomasjm** [comment]
I can't reproduce such a failure @angela-dang-src, can you provide more info such as the platform and error message?

I usually test by going to a Nixpkgs checkout and running a command like this:

```shell
nix run --impure --expr 'with import ./. {}; ((julia.withPackages) ["Distributions"])'
```

**Comment by thomasjm** [comment]
Hmm, something's going on with `DelaunayTriangulation.jl`. I typically run tests against the top 1000 most popular Julia packages, but we don't have complete coverage of all packages.

This appears unrelated to the `packageOverrides` issue, could you file a separate issue?

**Comment by marnym** [comment]
> @marnym Please test.

Tested a few different packages and it works as expected. Huge thanks!

**Comment by marnym** [comment]
A question/suggestion on the test case. Would it be better to use some other package as the test case, such as creating a simple `HelloWorld` package? 
If the author of `CellFishing.jl` decides to remove the repository it would make the test fail.

**Comment by thomasjm** [comment]
All right, updated the test to use my own `HelloWorld.jl` package.

**Comment by thomasjm** [comment]
Should be ready to go now @NickCao !

**Pull request merged**
