### PR TITLE
Jetbrains IDEs to 2017.3

### PR DESCRIPTION
**Pull request by matklad**
###### Motivation for this change

Update various Jetbrains IDEs to 2017.3 (including the freshly released GoLand)!

I've tested that at least IDEA works find on NixOS.

There were some minor problems with released tarbals earlier, but they should be fixed now. That said, I think it might be prudent to wait a couple of days before back porting this to stable, if we want to.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
We have to backport because older releases are deleted eventually. Can you send me a reminder, in some days?

**Comment by matklad** [comment]
> Can you send me a reminder, in some days?

Sure! And thanks for fixing CLion build! I've just noticed that it got broken and was about to send a PR :)

**Comment by matklad** [comment]
@Mic92 should be good to go now, no more problems were discovered with the new releases!

**Comment by Mic92** [comment]
all versions have been backported.

**Pull request merged**
