### PR TITLE
xen: 4.8.2 -> 4.8.3

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

minor bugfix release

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @oxij

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build xen

**Comment by xeji** [comment]
@7c6f434c please build build xen_4_8 xen_4_8-light xen_4_8-slim
(the default xen is still 4.5, unrelated to this pr)

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg   build xen_4_8 xen_4_8-light xen_4_8-slim

**Comment by 7c6f434c** [comment]
I looked at the build log and I don't understand what has failed. @oxij — do you see anything interesting in the log?

**Comment by xeji** [comment]
Don't understand this either. Builds on my machine.

**Comment by oxij** [comment]
> I looked at the build log and I don't understand what has failed. @oxij — do you see anything interesting in the log?

I have the same problem. I have no idea what could have broke with just this change.

Maybe try building them one by one? I have a feeling that there's an error hidden somewhere between the three of the rebuilds.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build xen_4_8 

@GrahamcOfBorg build xen_4_8-light

@GrahamcOfBorg build xen_4_8-slim

**Comment by xeji** [comment]
ok, guess i can fix that :-)

**Comment by xeji** [comment]
Weird. Looks like `nix-prefetch-git` (which I used here) stored the qemu-xen git checkout under a different hash on my machine, so the build worked on my machine with that hash. I suspect this is related to the many git submodules included in qemu-xen.

**Comment by xeji** [comment]
should build now

**Comment by 7c6f434c** [comment]
@xeji are you sure it doesn't change every time?

**Comment by xeji** [comment]
don't think so. I just started the build with a dummy hash and  got exactly the same hash as ofborg in the error log. neither the git revision nor the submodule commits have changed recently. If this was a general problem, we would have encountered it many times already when building xen. I thik it's just nix-prefetch-git.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build xen_4_8 xen_4_8-light xen_4_8-slim

**Comment by oxij** [comment]
I think the problem is that `qemu-xen`'s `fetchgit` expression depends on branch/tag instead of revision hash and xen devs move it from time to time. If you look at the log you'll notice that I had to fix that at least once before.

I'm unsure whenever this is a feature or a bug. If we change that tag to revision hash it would become deterministic. But if we leave it as is, then I would notice that they patched `qemu-xen` with some new XSA on the next mass rebuild when updating a single machine I have that uses `qemu-xen` instead of the upstream qemu :)

Feel free to do either. If you leave it as is I'll switch it to revision hash after I subscribe to XSA's :)

**Comment by xeji** [comment]
Thanks, switching to revision hash is a good idea. l would leave this as is for now and clean this up next time.

**Pull request merged**
