### PR TITLE
tor-browser: 52.8.0esr-7.5-1 -> 52.8.1esr-7.5-1

### PR DESCRIPTION
**Pull request by oxij**
- [X] Writing this using it.

### CODE REVIEW

**Comment by xeji** [comment]
@oxij does it make sense to start an ofborg build for this? Or would it time out anyway?

**Comment by oxij** [comment]
@xeji I'm semi-trusted user, so it should have been started already.

**Comment by xeji** [comment]
No, because the packages are `tor-browser-unwapped` and `firefoxPackages.torBrowser` (not `tor-browser`).

**Comment by xeji** [comment]
Let's start and see
@GrahamcOfBorg  build tor-browser-unwrapped firefoxPackages.tor-browser

**Comment by oxij** [comment]
Ah, right. I did make this PR from the resulting binary, but let's do

@GrahamcOfBorg build firefoxPackages.tor-browser

anyway, why not. :)

**Comment by oxij** [comment]
Thanks!

**Pull request merged**
