### PR TITLE
oxipng: 2.1.8 -> 2.2.0

### PR DESCRIPTION
**Pull request by dywedir**
[changelog](https://github.com/shssoichiro/oxipng/blob/master/CHANGELOG.md#version-220)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
LGTM, thanks! Failures/netural checks above are from unrelated issues/timeouts.

**Comment by vcunat** [comment]
There's [some issue](https://nix-cache.s3.amazonaws.com/log/j4mvn17qlkrfl1d534bld9c6w425cl8h-oxipng-2.2.0.drv).  My guess is that CloudFlare wasn't being careful enough about portability, as I've [seen that happen already](https://github.com/cloudflare/lua-aho-corasick/issues/12).

**Comment by dtzWill** [comment]
Eek! Should this be reverted?

**Comment by dywedir** [comment]
> If arm-always feature is set (build with --features=arm-always), ARM will be supported on Rust stable, but without a runtime check (i.e. it will crash if run on an unsupported ARM CPU).

IMHO, it's better than disabling the build on ARM.

**Pull request merged**
