### PR TITLE
perlPackages.MojoUserAgentCached: init at 1.12

### PR DESCRIPTION
**Pull request by stigtsp**
###### Motivation for this change

Adds the `Mojo::UserAgent::Cached` Perl module

dependencies:
perlPackages.AlgorithmLCSS: init at 0.01

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>perl530Packages.AlgorithmLCSS</li>
    <li>perl530Packages.MojoUserAgentCached</li>
    <li>perl532Packages.AlgorithmLCSS</li>
    <li>perl532Packages.MojoUserAgentCached</li>
  </ul>
</details>

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106255` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>perl530Packages.AlgorithmLCSS</li>
    <li>perl530Packages.MojoUserAgentCached</li>
    <li>perl532Packages.AlgorithmLCSS</li>
    <li>perl532Packages.MojoUserAgentCached</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
```
builder for '/nix/store/9q2vjvp2y3qbsdpy302imswhp1r5cjx0-perl5.30.3-Mojolicious-8.67.drv' failed with exit code 2; last 10 log lines:                                                         t/mojolicious/yaml_config_lite_app.t     (Wstat: 256 Tests: 3 Failed: 0)                                                                                                                      Non-zero exit status: 1                                                                                                                                                                     Parse errors: No plan found in TAP output                                                                                                                                                 t/test/mojo.t                            (Wstat: 65280 Tests: 1 Failed: 0)                                                                                                                    Non-zero exit status: 255                                                                                                                                                                   Parse errors: No plan found in TAP output                                                                                                                                                 Files=104, Tests=3173, 52 wallclock secs ( 1.05 usr  0.41 sys + 38.22 cusr  8.80 csys = 48.48 CPU)                                                                                          Result: FAIL                                                                                                                                                                                Failed 40/104 test programs. 4/3173 subtests failed.                                                                                                                                        make: *** [Makefile:1424: test_dynamic] Error 255                                                                                                                                         cannot build derivation '/nix/store/mizvdyiibarmfhnrygg341cqgyvff26h-perl5.30.3-Mojo-UserAgent-Cached-1.12.drv': 1 dependencies couldn't be built                                           builder for '/nix/store/5zs649ysb781zvmcl166qhris2amnfkn-perl5.32.0-Mojolicious-8.67.drv' failed with exit code 2; last 10 log lines:                                                         t/mojolicious/yaml_config_lite_app.t     (Wstat: 256 Tests: 3 Failed: 0)                                                                                                                      Non-zero exit status: 1                                                                                                                                                                     Parse errors: No plan found in TAP output                                                                                                                                                 t/test/mojo.t                            (Wstat: 65280 Tests: 1 Failed: 0)                                                                                                                    Non-zero exit status: 255                                                                                                                                                                   Parse errors: No plan found in TAP output
  Files=104, Tests=3173, 53 wallclock secs ( 1.04 usr  0.41 sys + 38.83 cusr  8.74 csys = 49.02 CPU)
  Result: FAIL
  Failed 40/104 test programs. 4/3173 subtests failed.
  make: *** [Makefile:1426: test_dynamic] Error 255
cannot build derivation '/nix/store/3c233w8faiji21wyaw8jx4k4cy9nwcjh-perl5.32.0-Mojo-UserAgent-Cached-1.12.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0avk5pdm7gbg6qkcdz6qpjn8xlbrz8nd-env.drv': 2 dependencies couldn't be built
```

**Comment by zakame** [comment]
Result of `nixpkgs-review pr 106255` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>perl530Packages.AlgorithmLCSS</li>
    <li>perl530Packages.MojoUserAgentCached</li>
    <li>perl532Packages.AlgorithmLCSS</li>
    <li>perl532Packages.MojoUserAgentCached</li>
  </ul>
</details>

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.MojoUserAgentCached

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 106255` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>perl530Packages.AlgorithmLCSS</li>
<li>perl530Packages.MojoUserAgentCached</li>
<li>perl532Packages.AlgorithmLCSS</li>
<li>perl532Packages.MojoUserAgentCached</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106255` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>perl530Packages.AlgorithmLCSS</li>
    <li>perl530Packages.MojoUserAgentCached</li>
    <li>perl532Packages.AlgorithmLCSS</li>
    <li>perl532Packages.MojoUserAgentCached</li>
  </ul>
</details>

**Pull request merged**
