### PR TITLE
ocamlPackages.lsp: 1.18.0 -> 1.19.0

### PR DESCRIPTION
**Pull request by smasher164**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by anmonteiro — CHANGES_REQUESTED** [review]
doesn't build on 5.1 / 4.14

**Comment by vbgl** [comment]
There is a better version of this change: https://github.com/nixos/nixpkgs/commit/f7a3ade7d35de8f24f53d2ef2090f9236864fd83.patch

However, this breaks `linol`…

**Comment by ulrikstrid** [comment]
`linol` is only used for `ligo` currently right? I'm not actively maintaining ligo anymore so either we should ask @EduardoRFS or someone on his team to step up as maintainer or it might be time to drop it as it's only getting more out of date.

**Comment by vbgl** [comment]
In the end the `linol` issue is trivial to sort out:  #344686.

**Comment by ulrikstrid** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/344686

**Comment by EduardoRFS** [comment]
I can step up as a maintainer, also linol will be dropped on a feature release. The team is 100% on Nix now.

**Comment by ulrikstrid** [comment]
@EduardoRFS you know where to find me if you want help adding yourself :)

**Pull request closed without merging**
