### PR TITLE
PyPy: 7.0.0

### PR DESCRIPTION
**Pull request by MostAwesomeDude**
###### Motivation for this change

We should have a robust PyPy story in place so that we can smoothly deprecate CPython 2 in concert with PSF.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by gebner** [comment]
> [...] smoothly deprecate CPython in concert with PSF.

Can you elaborate on this part?  I find it hard to believe that the PSF is deprecating CPython.  (Or is this about python 2?)

**Comment by MostAwesomeDude** [comment]
This is only about Python 2. Sorry about that; a missing character can make all the difference.

CPython 2.7 is going away next year upstream, and I think that we can be prepared with PyPy.

**Comment by Infinisil** [comment]
You also have https://github.com/NixOS/nixpkgs/pull/55182 open btw

**Comment by risicle** [comment]
Builds and works for me on non-nixos linux x86_64.

**Pull request closed without merging**
