### PR TITLE
workflows: Fix pkgs/by-name checks not running for non-committers

### PR DESCRIPTION
**Pull request by yu-re-ka**
## Description of changes

While reviewing #254368 I noticed I had to approve the workflow.
Copied the `permissions` definition from another workflow.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
It's likely that it isn't related to `permissions`, should be using `pull_request_target`.

https://github.com/NixOS/nixpkgs/blob/78058d810644f5ed276804ce7ea9e82d92bee293/.github/workflows/editorconfig.yml#L5-L7

Checkout would need to be updated as well.
https://github.com/NixOS/nixpkgs/blob/78058d810644f5ed276804ce7ea9e82d92bee293/.github/workflows/editorconfig.yml#L27-L30

**Comment by yu-re-ka** [comment]
@zowoq can you make the appropriate change?
I'm not 100% sure which parts are now needed, and I'm not an expert in GH Actions

**Comment by zowoq** [comment]
This should be all that is needed but would still need to verify that it works, it might make other assumptions about the env it runs in that could be different for pull_request_target.

```diff
diff --git a/.github/workflows/check-by-name.yml b/.github/workflows/check-by-name.yml
index 9622634fcffd..07e881b1f05d 100644
--- a/.github/workflows/check-by-name.yml
+++ b/.github/workflows/check-by-name.yml
@@ -4,7 +4,10 @@ name: Check pkgs/by-name
 
 # The pre-built tool is fetched from a channel,
 # making it work predictable on all PRs
-on: pull_request
+
+on:
+  # avoids approving first time contributors
+  pull_request_target
 
 # The tool doesn't need any permissions, it only outputs success or not based on the checkout
 permissions: {}
@@ -16,6 +19,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+        with:
+          # pull_request_target checks out the base branch by default
+          ref: refs/pull/${{ github.event.pull_request.number }}/merge
       - uses: cachix/install-nix-action@v22
       - name: Determining channel to use for dependencies
         run: |

```

**Comment by infinisil** [comment]
Thanks for the report/fix! I'm going to test this in a nixpkgs fork when I get the chance

**Comment by infinisil** [comment]
Merged to avoid amassing more workflows that need to be approved.

I now also went through all the ones that were waiting for approval and approved them. So this should be fully addressed now.

**Pull request merged**
