### PR TITLE
nixos/etcd: add package option

### PR DESCRIPTION
**Pull request by superherointj**
nixos/etcd: add package option

### CODE REVIEW

**Comment by zowoq** [comment]
Will this work with the api changes?

**Comment by winterqt** [comment]
> Will this work with the api changes?

What changes are you referring to?

**Comment by zowoq** [comment]
3.4 has a bunch of breaking changes which is why the default is still 3.3. 

Likely that the module won't work with any version except 3.3 without additional changes so there isn't any benefit in adding a package option.

**Comment by superherointj** [comment]
I have removed the reference to 3.5.

> so there isn't any benefit in adding a package option.

The benefit is just being able to override the package.
(Which is useful for many unforeseen cases, like patching etcd package.)

**Comment by zowoq** [comment]
> The benefit is being able to override the package.

If you need to do this why not override `pkgd.etcd`?

**Comment by superherointj** [comment]
> If you need to do this why not override `pkgd.etcd`?

It is not the same thing. I meant to say the package the module is using.

**Comment by zowoq** [comment]
That doesn't answer my question?

**Comment by superherointj** [comment]
> That doesn't answer my question?

I don't know.

Many other modules does this same way.

**Comment by zowoq** [comment]
Just because other modules have a package option doesn't mean it needs to be added here.

I don't see any benefit from adding it and it may actually be confusing for users at it implies that other versions could be used.

**Comment by superherointj** [comment]
@zowoq Sorry about the trouble.

**Pull request closed without merging**
