### PR TITLE
python312Packages.jupysql: 0.10.13 -> 0.10.14 

### PR DESCRIPTION
**Pull request by dotlambda**
Diff: https://github.com/ploomber/jupysql/compare/refs/tags/0.10.13...0.10.14

Changelog: https://github.com/ploomber/jupysql/blob/0.10.14/CHANGELOG.md

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 346509`

---
### `x86_64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.jupysql-plugin</li>
    <li>python311Packages.jupysql-plugin.dist</li>
    <li>python312Packages.jupysql-plugin</li>
    <li>python312Packages.jupysql-plugin.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.jupysql-plugin</li>
    <li>python311Packages.jupysql-plugin.dist</li>
    <li>python312Packages.jupysql-plugin</li>
    <li>python312Packages.jupysql-plugin.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.jupysql-plugin</li>
    <li>python311Packages.jupysql-plugin.dist</li>
    <li>python312Packages.jupysql-plugin</li>
    <li>python312Packages.jupysql-plugin.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.jupysql-plugin</li>
    <li>python311Packages.jupysql-plugin.dist</li>
    <li>python312Packages.jupysql-plugin</li>
    <li>python312Packages.jupysql-plugin.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
```
=========================== short test summary info ============================
FAILED src/tests/test_resultset.py::test_calling_legacy_plotting_functions_displays_warning[pie-.pie() is deprecated and will be removed in a future version. Use %sqlplot pie instea>
FAILED src/tests/test_resultset.py::test_calling_legacy_plotting_functions_displays_warning[bar-.bar() is deprecated and will be removed in a future version. Use %sqlplot bar instea>
FAILED src/tests/test_resultset.py::test_calling_legacy_plotting_functions_displays_warning[plot-.plot() is deprecated and will be removed in a future version. For more help, find u>
ERROR src/tests/test_resultset.py::test_resultset_getitem - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_dict - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_len - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_dicts - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_dataframe - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_csv - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_str - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_repr_html_when_feedback_is_2 - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_repr_html_with_reduced_feedback[0] - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_repr_html_with_reduced_feedback[1] - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_invalid_operation_error[head--1] - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_invalid_operation_error[tail-None] - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_invalid_operation_error[value_counts-None] - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_invalid_operation_error[not_df_function-None] - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
ERROR src/tests/test_resultset.py::test_resultset_config_autolimit_dict - sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog E...
= 3 failed, 640 passed, 1 deselected, 4 xfailed, 1 xpassed, 4 warnings, 15 errors in 19.55s =
```

```
>               self.__c.execute(statement, parameters)
E               sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog Error: Table with name df does not exist!
E               Did you mean "pg_depend"?
E               LINE 1: select * from df
E                                     ^
E               [SQL: select * from df]
E               (Background on this error at: https://sqlalche.me/e/20/f405)
```

**Comment by dotlambda** [comment]
Please don't review drafts unless you have something to add. I mostly opened this PR to bring the build failure to the maintainers' attention but will close it now since I'm not interested in fixing it.

**Comment by GaetanLepage** [comment]
Oh sorry for that.
I have received a review request so I went ahead and reviewed.

image

**Comment by dotlambda** [comment]
> Catalog Error: Table with name df does not exist!

There is an upstream issue about this: https://github.com/duckdb/duckdb/issues/13836

**Pull request closed without merging**
