### PR TITLE
openal-soft: 1.19.1 -> 1.21.1

### PR DESCRIPTION
**Pull request by McSinyx**
###### Motivation for this change

Updating the the OpenAL Soft version and information.  The site change is due to a domain pricing issue: kcat/alure#47

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126184` at 9c1cb88c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>attract-mode</li>
    <li>odpdown</li>
    <li>openrw</li>
    <li>termplay</li>
    <li>yaxg</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/efe698bf7a1bb55c8e2bb00a338b632f">fakenes</a></li>
    <li><a href="https://gist.github.com/d6ae6dc0d8212d80b326187d9c5bbea5">fluxus</a></li>
    <li><a href="https://gist.github.com/66b60528f5aaa0680901a62395b311f9">python38Packages.skytemple-ssb-debugger</a></li>
    <li><a href="https://gist.github.com/2306ca17d0528081061319a930c31ca6">tremulous</a></li>
  </ul>
</details>
<details>
  <summary>597 packages skipped due to time constraints:</summary>
  <ul>
    <li>EmptyEpsilon</li>
    <li>MIDIVisualizer</li>
    <li>_90secondportraits</li>
    <li>adapta-gtk-theme</li>
    <li>allegro5</li>
    <li>almanah</li>
    <li>alure2</li>
    <li>andyetitmoves</li>
    <li>ankisyncd</li>
    <li>apostrophe</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>59 packages built successfully:</summary>
  <ul>
    <li>allegro (allegro4)</li>
    <li>alure</li>
    <li>anki</li>
    <li>antsimulator</li>
    <li>brasero</li>
    <li>brasero-original</li>
    <li>bucklespring (bucklespring-x11)</li>
    <li>bucklespring-libinput</li>
    <li>dumb</li>
    <li>dwarf-fortress-packages.dwarf-fortress-original</li>
    <li>farstream</li>
    <li>freealut</li>
    <li>gmrender-resurrect</li>
    <li>gnome.gnome-sound-recorder</li>
    <li>gscrabble</li>
    <li>gst_all_1.gst-plugins-bad</li>
    <li>libsForQt5.libkdegames (libsForQt515.libkdegames ,plasma5Packages.libkdegames)</li>
    <li>libsForQt514.libkdegames</li>
    <li>lollypop</li>
    <li>mailnag</li>
    <li>minetest (minetestclient_5)</li>
    <li>mpv</li>
    <li>mpv-unwrapped</li>
    <li>mpvScripts.mpris</li>
    <li>openal (openalSoft)</li>
    <li>openarena</li>
    <li>openraPackages.mods.sp</li>
    <li>openxray</li>
    <li>pithos</li>
    <li>python38Packages.py-desmume</li>
    <li>python39Packages.py-desmume</li>
    <li>python39Packages.skytemple-ssb-debugger</li>
    <li>qt-video-wlr</li>
    <li>qutebrowser</li>
    <li>recapp</li>
    <li>sfml</li>
    <li>simplenes</li>
    <li>soldat-unstable</li>
    <li>toxic</li>
    <li>transcribe</li>
    <li>ue4demos.black_jack</li>
    <li>ue4demos.blueprint_examples_demo</li>
    <li>ue4demos.card_game</li>
    <li>ue4demos.effects_cave_demo</li>
    <li>ue4demos.elemental_demo</li>
    <li>ue4demos.landscape_mountains</li>
    <li>ue4demos.matinee_demo</li>
    <li>ue4demos.mobile_temple_demo</li>
    <li>ue4demos.realistic_rendering</li>
    <li>ue4demos.reflections_subway</li>
    <li>ue4demos.scifi_hallway_demo</li>
    <li>ue4demos.shooter_game</li>
    <li>ue4demos.strategy_game</li>
    <li>ue4demos.stylized_demo</li>
    <li>ue4demos.swing_ninja</li>
    <li>ue4demos.tappy_chicken</li>
    <li>ue4demos.vehicle_game</li>
    <li>unigine-valley</li>
    <li>unvanquished</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl2` is a deprecated license, please check if project uses `lgpl2Plus` or `lgpl2Only` and change `meta.license` accordingly.

Near pkgs/development/libraries/openal-soft/default.nix:45:5:
```
   |
45 |     license = licenses.lgpl2;
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by McSinyx** [comment]
There seems to be breaking API, l guess I'll need to investigate a little further.

**Comment by ilya-fedin** [comment]
Could this get a speed up? 1.19.1 lacks AL_SOFT_direct_channels_remix what means that e.g. tdesktop sound goes through 3D distortions.

**Comment by McSinyx** [comment]
Sorry I panicked out that time, it was a come back after over a year not using nix.

Looking at the build errors they all seem to be irrelevant so I think this is safe to merge.  BTW @ftrvxmtrx are you still talking the responsibility for this package?  I can step up if necessary.

**Comment by ilya-fedin** [comment]
Looks like someone else updated the package :thinking:

**Comment by McSinyx** [comment]
Nice!

**Pull request closed without merging**
