### PR TITLE
[backport 210848] tagparser: 11.5.0 -> 11.5.1

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Is there a particular reason for these backports?

We usually wait for the original commit to be merged before creating the backport so that it can have the correct "cherry picked from" commit id etc.

**Comment by matthiasbeyer** [comment]
> We usually wait for the original commit to be merged before creating the backport so that it can have the correct "cherry picked from" commit id etc.

I cherry-picked, so the "cherry picked from" is already correct.

**Comment by bjornfor** [comment]
If both PRs are made at the same time it's easy to break the cherry-pick ref if the master PR is rebased in the meantime. +1 for cherry-picking from master instead of a PR.

**Review by bjornfor — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
I don't feel responsible if someone else breaks my commit hashes, sorry.

**Comment by bjornfor** [comment]
You might accidentally break the ref yourself, if you need to fixup anything for whatever reason before merging. IMHO it's a foot gun.

**Comment by risicle** [comment]
It's perfectly valid for the committer to do a rebase-merge, in which case you don't know the final commit hash until that button is hit. It's not a matter of who's "responsible" for it, it's more that it has a habit of happening when we have parallel PRs, and we'd rather it didn't. We also try to avoid parallel PRs because it can lead to it being merged to the stable branch before master, another thing we don't want.

**Pull request merged**
