### PR TITLE
varnish: 7.0.2 -> 7.1.0

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
https://varnish-cache.org/releases/rel7.1.0.html#rel7-1-0

We could still keep 7.0 around, since it'll only be EOL 2022-09-15, but we can also make our lives easy switch now.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
As long as it's not one of those weird situations where 7.0 will EOL _after_ 7.1 and we regret bumping...

**Comment by ajs124** [comment]
[This](https://varnish-cache.org/releases/index.html) is the best source I've found for EOL dates, so far.

**Comment by risicle** [comment]
Merge conflict btw

**Comment by ajs124** [comment]
@risicle fixed the merge conflict

**Comment by risicle** [comment]
@ofborg test prometheus-exporters.varnish

**Review by risicle — APPROVED** [review]
Looks sensible to me. `nixpkgs-review` happy, nixos x86_64. Already broken on darwin. `nixosTests.prometheus-exporters.varnish` happy - would be good to have a proper nixos test though.

**Comment by risicle** [comment]
Of course we could always add `nixosTests.prometheus-exporters.varnish` to `passthru.tests`.

**Comment by ajs124** [comment]
On one hand, we could. On the other, I don't see any easy or clean way to parameterize it in a way where it would actually test the varnish package that it's called through instead of using the default package.

**Comment by risicle** [comment]
This is a common problem with almost all passthru'd `nixosTests`, and I've been advised to just go with it rather than trying to solve it with funny tricks.

FWIW I've found the most straightforward way of achieving it to be using `lib.fix`.

**Comment by ajs124** [comment]
I'm just afraid that it will give people wrong confidence. They build `varnish60.passthru.tests` and think they've built and tested `varnish60` but that's completely untrue.

If you think it's useful, I can still add it, but that's my concern.

**Comment by risicle** [comment]
I agree with you, I fear it could give people false confidence. But it's exactly what happens with e.g. postgis, unbound, openssh, nomad to name a few, so I learned to just stop worrying about it and hope someone solves it more generally someday :shrug: 

Either way, let's not let it hold this PR up.

**Pull request merged**
