### PR TITLE
armagetronad: update 0.4; fix possible problem in installCheckPhase

### PR DESCRIPTION
**Pull request by numinit**
## Description of changes

Fixing [ZHF issues](https://zh.fail/failed/by-maintainer/numinit.html): https://hydra.nixos.org/build/260923940/nixlog/4

Build stops on installCheckPhase on Hydra but succeeds locally(???). Attempting to fix it. "Works on my machine" isn't supposed to happen here...

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by numinit** [comment]
@ofborg build armagetronad armagetronad-dedicated armagetronad.passthru.tests

**Comment by numinit** [comment]
Should be ready. Rebased.

**Comment by numinit** [comment]
Rebased again against changes to NixOS tests.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 316823` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>armagetronad</li>
    <li>armagetronad-dedicated</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 316823` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>armagetronad</li>
    <li>armagetronad-dedicated</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
@ofborg build armagetronad armagetronad-dedicated

I have rebased this, let's see now

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 316823` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>armagetronad</li>
    <li>armagetronad-dedicated</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
In my case, it's this error.

```log
error: builder for '/nix/store/i5h58awgi0ns0bmpg5zfhzk3bk6vld2c-armagetronad-dedicated-0.2.9.2.3.drv' failed with exit code 2;
       last 25 log lines:
       > g++ -DHAVE_CONFIG_H -I. -I..   -iquote . -iquote ..  -I/nix/store/b23a6vc2nkq9v1vs1g003djakr78h8j3-libxml2-2.13.2-dev/include/libxml2   -iquote ./tools  -iquote ./render -O2 -std=c++11 -Wno-unused-but-set-variable -Wno-unused-private-field -Wno-unused-function -Wno-long-long -c -o render/librender_a-rRender.o `test -f 'render/rRender.cpp' || echo './'`render/rRender.cpp
       > network/nKrawallPrivate.cpp: In static member function 'static int nKrawall::FetchURL(const tString&, const char*, std::ostream&, int)':
       > network/nKrawallPrivate.cpp:461:19: error: 'xmlNanoHTTPOpen' was not declared in this scope
       >   461 |     void * ctxt = xmlNanoHTTPOpen( fullURL.str().c_str(), NULL);
       >       |                   ^~~~~~~~~~~~~~~
       > network/nKrawallPrivate.cpp:467:14: error: 'xmlNanoHTTPReturnCode' was not declared in this scope
       >   467 |     int rc = xmlNanoHTTPReturnCode(ctxt);
       >       |              ^~~~~~~~~~~~~~~~~~~~~
       > network/nKrawallPrivate.cpp:478:15: error: 'xmlNanoHTTPRead' was not declared in this scope
       >   478 |         len = xmlNanoHTTPRead( ctxt, &buf, max );
       >       |               ^~~~~~~~~~~~~~~
       > network/nKrawallPrivate.cpp:483:5: error: 'xmlNanoHTTPClose' was not declared in this scope
       >   483 |     xmlNanoHTTPClose(ctxt);
       >       |     ^~~~~~~~~~~~~~~~
```

**Comment by numinit** [comment]
Should be fixed.

**Review by JohnRTitor — APPROVED** [review]
Builds for me, will merge after eval passes.
image

**Comment by numinit** [comment]
Removed the auto backport label since I'll have to omit the libxml2 relevant commit for that to work.

**Comment by numinit** [comment]
aarch64 NixOS test [succeeded](https://logs.ofborg.org/?key=nixos/nixpkgs.316823&attempt_id=106b8e53-eeda-49f4-84c6-7e3a3da3e28f), x86_64 [timed out](https://logs.ofborg.org/?key=nixos/nixpkgs.316823&attempt_id=cd8fc655-6c0b-45fd-8cf7-fd2cdba76274). Increased the timeout for client setup.

**Pull request merged**
