### PR TITLE
crystal: refactor and add 0.35.1

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Motivation for this change

crystal is currently marked as broken, this is an attempt to fix it and bring it
up to date.

renabled tests by changing from `spec` to `spec_compiler` (only compiler tests)
which now pass:

```
Using compiled compiler at .build/crystal
.build/compiler_spec
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*..................................................................................................................................................................................................................................................................................................................................................................................................**.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*...................................................................................................................................................................................................................................................................................**.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*...............................................*..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Pending:
  Code gen: lib codegens lib var set and get
  Code gen: primitives codegens pointer of int
  Code gen: primitives sums two numbers out of an [] of Number
  Semantic: cast casts from union to incompatible union gives error
  Semantic: def overload restricts on generic type with free type arg
  Semantic: def overload restricts on generic type without type arg
  Semantic: instance var doesn't infer type to be nilable if using self.class in call in assign
  Semantic: pointer allows using pointer with subclass
  Semantic: primitives types pointer of int

Finished in 6:28 minutes
9102 examples, 0 failures, 0 errors, 9 pending
```

###### Things done

Changes:

- Removed tests `spec_stdlib` (kept `spec_compiler`)
- Add 0.35.1
- Slit shards versions to bring 0.11.1 and 0.12.0

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
It seems like nix/ofborg doesn't get the maintainers, tagging manually:

@manveru @david50407 @peterhoeg

**Comment by fabianhjr** [comment]
Supersedes #90038

**Comment by peterhoeg** [comment]
This is great! How about `shards` ref https://github.com/NixOS/nixpkgs/pull/89863?

**Comment by fabianhjr** [comment]
Hi @peterhoeg, sure, will take a look. Though, from that PR seems like there is interest on keeping multiple versions or should I just upgrade it to the latest one?

**Comment by peterhoeg** [comment]
We need multiple shards versions ref the 0.11 changelog:

> Add compatibility with Crystal 0.35. Drop compatibility with < 0.34

Hopefully crystal gets to v1.0 before 21.03 so we can start dropping the old versions.

**Comment by fabianhjr** [comment]
Hi @peterhoeg, split is done. I think we could also remove crystal-0.32 if scry builds and works on 0.33. (However from their commit log it seems it isn't compatible with 0.34 until next release)

I am currently building shards but since I don't have my previous builds of crystal (0.32-0.34) it will take a while. unu

**Comment by peterhoeg** [comment]
The GrandPlan(tm) was to keep the latest version of crystal that made it into a supported NixOS version around in unstable. That's 0.32 for 20.03 and 0.34 for 20.09. 20.03 will soon no longer be actively maintained and we can drop < 0.34

**Comment by fabianhjr** [comment]
Ah ok, will fixup the commits to keep previous versions, though I dont mind backporting this to 20.09 as a commit that keeps previous versions there.

**Comment by fabianhjr** [comment]
Everything fixuped to keep crystal-0.32.0 and shards-0.11.0.

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build crystal_0_34 shards_0_11

**Comment by peterhoeg** [comment]
Very nice work @fabianhauser 

Is there a particular reason for doing both shards 0.11 and 0.11.1?

**Comment by fabianhjr** [comment]
Not really, should I drop the 0.11 in favor of 0.11.1?

**Comment by peterhoeg** [comment]
Yes, please drop the `shards_0_11_1` attribute and have `shards_0_11` point at 0.11.1

It's just added maintenance otherwise.

**Comment by fabianhjr** [comment]
Ok pushed

**Comment by peterhoeg** [comment]
Thank you @fabianhjr !

**Pull request merged**
