### PR TITLE
python3Packages.sip: fix typo

### PR DESCRIPTION
**Pull request by zeuner**
## Description of changes

A typo broke the build of reverse dependencies. This PR fixes it. See also https://github.com/macports/macports-ports/commit/ec069438e74a52a53c9831ad2243846a0496b039

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dotlambda** [comment]
Should go to staging.

> A typo broke the build of reverse dependencies.

Do you have an example?

**Comment by zeuner** [comment]
> Do you have an example?

I encountered it when trying to build `pythonPackages.poppler-qt5`.

**Comment by zeuner** [comment]
> Should go to staging.

`staging` fails on the `pkgs/by-name` check due to a seemingly unrelated issue.

**Comment by zeuner** [comment]
I rebased it to an older `staging` commit since the latest `staging` contains `libplacebo_5` and `vulkan-volk` which do not honour the `pkgs/by-name` policy.

**Comment by infinisil** [comment]
See https://github.com/NixOS/nixpkgs/pull/282707 for why CI failed, it's an interesting edge case, could've been fixed by retriggered CI

**Review by nrdxp — APPROVED** [review]
I checked upstream and the tip has already been fixed so this should be fine until we update past the upstream fix.

**Comment by dotlambda** [comment]
@ofborg build python3.pkgs.sip

**Comment by dotlambda** [comment]
Actually should we merge it into staging-next since it fixes some builds?

**Comment by Stunkymonkey** [comment]
We should continue in #281180 which provides the newer version fixing this issue. Looking at the 6.8.1 code: https://www.riverbankcomputing.com/hg/sip/file/d6da922b80f7/sipbuild/generator/outputs/code.py

**Comment by zeuner** [comment]
> We should continue in #281180 which provides the newer version fixing this issue. Looking at the 6.8.1 code: https://www.riverbankcomputing.com/hg/sip/file/d6da922b80f7/sipbuild/generator/outputs/code.py

Should https://github.com/NixOS/nixpkgs/pull/282473/commits/219c17d5607c13ff50a701f84527280cc42754dc also go there?

**Comment by Stunkymonkey** [comment]
I not a big fan of df7ab7d1ddf6f4e151effea427fd99c9c7dcd186.

219c17d5607c13ff50a701f84527280cc42754dc LGTM, but not sure where we should track it.

**Comment by natsukium** [comment]
closing in favor of #281180

**Pull request closed without merging**
