### PR TITLE
protobuf: 3.4.0 -> {3.4.1, 3.5.1.1}

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Version update.
Have not tested all the deps, so the PR is against ```staging```

### CODE REVIEW

**Comment by orivej** [comment]
I wouldn't switch to Protobuf 3.5 (including 3.5.1.1) because it subtly corrupts protobuf field reflection with some uses: https://github.com/google/protobuf/issues/4293. The affected applications still build and run, but field reflection returns incorrect data about field extensions.

**Comment by Mic92** [comment]
@GrahamcOfBorg build mosh

**Comment by volth** [comment]
@grahamc '([full log](https://logs.nix.ci/?key=nixos/nixpkgs.35424&attempt_id=64182d2a-81d4-49ec-acab-388846f46616))' link leads to

**Comment by Mic92** [comment]
@volth works fine for me in firefox. Are you sure, you did not disable javascript?
It needs websockets to stream logs.

**Comment by Mic92** [comment]
macOS seems broken for different reason.

**Comment by volth** [comment]
The same with Firefox (no plugins at all, default settings):

**Comment by Mic92** [comment]
you should see more context in the firefox web inspector. Afaik it connects to `https://events.nix.gsc.io`

**Comment by volth** [comment]
It works now, although the rendered page is rather heavy, too many <div> tags

**Pull request merged**
