### PR TITLE
rav1e: Fix cross-compiling

### PR DESCRIPTION
**Pull request by zhaofengli**
###### Motivation for this change

Without this patch:

```
$ nix-build -E 'with (import ./. {}).pkgsCross.riscv64; rav1e'
/nix/store/ayrf1k443paf05kg721l393b2w8gcxb7-rav1e-riscv64-unknown-linux-gnu-0.4.1
$ file /nix/store/ayrf1k443paf05kg721l393b2w8gcxb7-rav1e-riscv64-unknown-linux-gnu-0.4.1/lib/librav1e.so.0.4.1
/nix/store/ayrf1k443paf05kg721l393b2w8gcxb7-rav1e-riscv64-unknown-linux-gnu-0.4.1/lib/librav1e.so.0.4.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
  - Tested the dynamic library with example programs in `libheif`
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zhaofengli** [comment]
Looks like I don't have permissions to do this. Could someone trigger the bot for me?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125000` at ae89722f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>78 packages marked as broken and skipped:</summary>
  <ul>
    <li>asymptote</li>
    <li>autotrace</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>deeptools</li>
    <li>devede</li>
    <li>dvd-slideshow</li>
    <li>gopro</li>
    <li>grass</li>
    <li>hydrus</li>
    <li>impressive</li>
    <li>invoice2data</li>
    <li>libvmi</li>
    <li>linuxPackages_hardkernel_4_14.dpdk</li>
    <li>linuxPackages_hardkernel_latest.dpdk</li>
    <li>linuxPackages_testing_bcachefs.dpdk</li>
    <li>natron</li>
    <li>odpdown</li>
    <li>opentsdb</li>
    <li>photoflow</li>
    <li>pig</li>
    <li>polymake</li>
    <li>processing</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.fipy</li>
    <li>python38Packages.foundationdb51</li>
    <li>python38Packages.foundationdb52</li>
    <li>python38Packages.foundationdb60</li>
    <li>python38Packages.foundationdb61</li>
    <li>python38Packages.ignite</li>
    <li>python38Packages.pygmt</li>
    <li>python38Packages.python-csxcad</li>
    <li>python38Packages.python-openems</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.tensorflowWithCuda</li>
    <li>python38Packages.textacy</li>
    <li>python39Packages.HTSeq</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.cnvkit</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.fipy</li>
    <li>python39Packages.foundationdb51</li>
    <li>python39Packages.foundationdb52</li>
    <li>python39Packages.foundationdb60</li>
    <li>python39Packages.foundationdb61</li>
    <li>python39Packages.ignite</li>
    <li>python39Packages.pygmt</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
    <li>python39Packages.streamz</li>
    <li>python39Packages.tensorflowWithCuda</li>
    <li>qemu_xen</li>
    <li>qemu_xen-light</li>
    <li>qemu_xen_4_10</li>
    <li>qemu_xen_4_10-light</li>
    <li>qlandkartegt</li>
    <li>qubes-core-vchan-xen</li>
    <li>scribus</li>
    <li>spark</li>
    <li>split2flac</li>
    <li>spring</li>
    <li>springLobby</li>
    <li>truvari</li>
    <li>vcs</li>
    <li>yosys-bluespec</li>
  </ul>
</details>
<details>
  <summary>8313 packages skipped due to time constraints:</summary>
  <ul>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>R</li>
    <li>abcl</li>
    <li>abiword</li>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>aerc</li>
    <li>afew</li>
    <li>agdaPackages.agda-categories</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>9 packages built successfully:</summary>
  <ul>
    <li>gimp (gimpPlugins.gimp)</li>
    <li>imagemagick</li>
    <li>imagemagick6</li>
    <li>imagemagickBig</li>
    <li>imv</li>
    <li>libheif</li>
    <li>libwmf</li>
    <li>rav1e</li>
    <li>vips</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/video/rav1e/default.nix:54:5:
```
   |
54 |     maintainers = [ ];
   |     ^
```
</li>
  </ul>
</details>

**Comment by zhaofengli** [comment]
Ok, finally back home. Here goes nothing...

**Comment by zhaofengli** [comment]
Ok, I messed up again :see_no_evil: I followed https://github.com/NixOS/ofborg/issues/463#issuecomment-617823601 but still the force push resulted in the notifications. My apologies.

**Comment by Ericson2314** [comment]
No worries, I find it's pretty tricky to get that right by hand. This looks good to me now.

**Pull request merged**
