### PR TITLE
fortify-headers: 1.1alpine1 -> 1.1alpine3

### PR DESCRIPTION
**Pull request by risicle**
## Description of changes

The relevant changes in this bump are the addition of some patches fixing behaviour with clang. I think we're still going to have to patch fortify-headers further to make it more easily disable-able for clang (if not just disable it entirely for clang) but this is a start.

Have built a lot of `pkgsMusl` packages on nixos x86_64 with this.

cc @NixOS/static 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On second thoughts this probably isn't urgent enough to go to `staging-next`.

**Comment by yu-re-ka** [comment]
Since it doesn't have many rebuilds, I think it should go into master.

**Review by yu-re-ka — APPROVED** [review]

**Comment by risicle** [comment]
Well, it's a full rebuild for musl users.

**Comment by yu-re-ka** [comment]
define "musl users". I have a device that's running full nixos with musl, but that can't be upgraded to current master because of too many rebuild failures being introduced in the last two staging cycles, some of which would be fixed by this.

**Comment by yu-re-ka** [comment]
> Would it be better if we merged https://github.com/NixOS/nixpkgs/pull/251942 to make this a completely non-urgent problem?

Either that or revert #219421 for now and then re-submit it together with other fixes?

**Comment by yu-re-ka** [comment]
which PR introduced the fortify-headers for musl libc then?

**Comment by risicle** [comment]
No wait, you're right - I've got my numbers mixed up.

**Comment by yu-re-ka** [comment]
Let's merge this into staging and #251942 into master, and then we're good for now and can figure out how to make it work with clang at some point

**Pull request merged**
