### PR TITLE
jetbrains: 2024.1 -> 2024.1.2

### PR DESCRIPTION
**Pull request by zlepper**
## Description of changes

Ran the `update_bin.py` script

```
jetbrains.clion: 2024.1 -> 2024.1.1
jetbrains.datagrip: 2024.1.1 -> 2024.1.2
jetbrains.dataspell: 2024.1 -> 2024.1.1
jetbrains.gateway: 2024.1 -> 2024.1.1
jetbrains.phpstorm: 2024.1 -> 2024.1.1
jetbrains.rider: 2024.1 -> 2024.1.1
jetbrains.ruby-mine: 2024.1 -> 2024.1.1
jetbrains.rust-rover: 2023.3 EAP -> 2024.1 EAP
jetbrains.webstorm: 2024.1 -> 2024.1.1
jetbrains.writerside: 2023.3 EAP -> 2024.1 EAP
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by superherointj** [comment]
Can you re-run the script and rebase? I did a re-run here and did not match properly, likely outdated by now.

**Comment by zlepper** [comment]
> Can you re-run the script and rebase? I did a re-run here and did not match properly, likely outdated by now.

Script has been rerun and git rebased :)

**Comment by superherointj** [comment]
zlepper, sorry about delay, was sleeping.
Just executed the script here, there are only 4 differences now.
What we do? You run again? And we get it synced?

The differences are related to 2024.1.1 -> 2024.1.2
So I think, it might be worth re-running this.
https://termbin.com/evxw

**Review by superherointj — APPROVED** [review]

**Comment by zlepper** [comment]
Seems those were released literally hours ago XD https://blog.jetbrains.com/webstorm/2024/04/webstorm-2024-1-2/ Will run the script again once I'm at a computer later today :)

**Comment by zlepper** [comment]
Alright, pushed, again :D And now we have the entire weekend before they will release another update (I hope) :D

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 306356` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.dataspell</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.rust-rover</li>
    <li>jetbrains.webstorm</li>
    <li>jetbrains.writerside</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]
LGTM. Update script is in sync for me.

**Pull request merged**
