### PR TITLE
turtle: 0.8 -> 0.9

### LINKED ISSUE #319958: The `turtle` pkg's nautilus integration does not work on NixOS inside a nix-shell
### Describe the bug
`turtle`'s main feature is to add additional functionality to the gnome file explorer, nautilus, via extra icons and context menus when using nautilus to navigate inside a git repository; but when running nautilus from within a `nix-shell` on NixOS with turtle installed, that functionality does not seam to be working.

### Steps To Reproduce
Steps to reproduce the behaviour:
1. Run `nix-shell -p turtle -p gnome.nautilus`
2. Run `nautilus -q` to kill any already running instances of nautilus.
3. Run `nautilus`
4. Navigate into a directory containing `.git`
5. Observe that no additional icons, information, or context actions have been added to nautilus, as shown in the below screenshot from the `turtle` gnome GitLab.

### Expected behaviour
When the `turtle` package is installed from either `nix-shell` or `environment.systemPackages` it's integration with nautilus functions.

Screenshot from the gnome GitLab showing nautilus with extra icons representing a file's git status:
Screenshot from the gnome GitLab showing nautilus with extra icons representing a file's git status

### Screenshots
A screenshot of nautilus shows a `.git` folder, but none of the icons added by `turtle` are present.
Screenshot from 2024-06-15 13-24-17

### Additional context
Looking at `pkgs/by-name/tu/turtle/package.nix` it does not appear that the `gnome.nautilus-python` package is listed as a dependency, but since `turtle`'s nautilus integration is written in python that package would be required for the integration to work. This may be the reason why the integration isn't working, but I'm not sure, as when I tried using a `nix-shell -p turtle -p gnome.nautilus -p gnome.nautilus-python` it also didn't work. It could also be that something else about my system could be stopping it from working, and if anyone wants extra details, I'll be happy to share.

It might also be that `turtle`'s `install.py` is trying to add the nautilus extension as if it was running on a mutable OS, and is trying to modify system files. Looking at the `install.py` there seams to be a few CLI options about installing to the user's home directory, which implies that by default it tries to install system-wide, which may be the problem. If this is the case, would what the `install.py` code copies into the system need to be named in the `package.nix` file or would a hole systemwide NixOS option in `configuration.nix` need to be set?

I'm new to using NixOS and if I'm doing anything wrong, please explain or point me to the relevant documentation, so I can learn.

The `turtle` package was added in pull request #313605

### Notify maintainers

@aleksanaa
@aleksana

In the `package.nix` the maintainer was listed as `aleksana` (without a second `a`) but that didn't look like the right GitHub user, so I'm pinging both. This may also be a problem to fix.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.05 (Uakari), 24.05.1409.cc54fb41d137`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/319958

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
@jtojnar the `symlinkJoin` method in `passthru` doesn't work (`NAUTILUS_PYTHON_DEBUG=misc ./result/bin/nautilus` no related outputs), but putting them in `environment.systemPackages` should work. I don't quite understand why the former doesn't work when both work the same way? Could you help me debug it?

**Comment by jtojnar** [comment]
If you just put `nautilus` into `symlinkJoin` it has no knowledge of that, the `realpath` of `nautilus` program will still be in the original store path, as will the `libdir` compiled into the program, that is actually used for finding extensions.

You would need to wrap it to set `NAUTILUS_4_EXTENSION_DIR` to find Nautilus extensions like `nautilus-python`, and  `XDG_DATA_DIRS` to find `nautilus-python` scripts.

I have a draft that does the former: https://github.com/NixOS/nixpkgs/pull/319535

**Comment by Aleksanaa** [comment]
Thanks!

**Comment by Aleksanaa** [comment]
Not adding passthru.nautilus-with-turtle, as this should be backported to 24.05, and we have `gnome.nautilus -> nautilus` not backported. And would be better to wait for https://github.com/NixOS/nixpkgs/pull/319535.

Tested with:

```nix
{
  symlinkJoin,
  nautilus,
  nautilus-python,
  turtle,
  makeBinaryWrapper,
}:

symlinkJoin {
  name = "nautilus-with-turtle-";
  paths = [
    nautilus
    nautilus-python
    turtle
  ];
  nativeBuildInputs = [ makeBinaryWrapper ];
  postBuild = ''
    wrapProgram $out/bin/nautilus \
      --prefix XDG_DATA_DIRS : $out/share \
      --prefix NAUTILUS_4_EXTENSION_DIR : $out/lib/nautilus/extensions-4 \
      --prefix PATH : $out/bin
  '';
  meta.mainProgram = "nautilus";
}
```

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 324976` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>turtle</li>
    <li>turtle.dist</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Pull request merged**
