### PR TITLE
modules/zabbix-agent: Added an option to specify UserParameters

### PR DESCRIPTION
**Pull request by Jauchi**
###### Motivation for this change
I needed to specify the same thing multiple times in the config file (UserParameter), so I added a functionality to do it.
Please note that I have never contributed to nixpkgs before, so things will probably break...
This function is not compatible with people putting "Include" in their settings. It will not break as long as you don't use  Include **and** use UserParameters. The description says this too.
This should not be major, as people using Include can just put their UserParameters there.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
Hi @Jauchi :wave: Thanks for choosing to contribute to nixpkgs!

Currently I would use the `zabbixAgent` module to write your configuration like this:
```nix
services.zabbixAgent.settings.UserParameter = [
  "zfs.zpool.health[*],zpool list -H -o health $1"
  "zfs.get.fsinfo[*],zfs get -o value -Hp $2 $1"
  ''zfs.get.compressratio[*],zfs get -o value -Hp compressratio $1 | sed "s/x//"''
];
```

This avoids any incompatibilities between options and allows you to merge configurations. You can specify `services.zabbixAgent.settings.UserParameter` multiple times and it will include all of your scripts. How does this look to you? Does it solve your problem?

**Comment by aanderse** [comment]
> Would it be possible to add something like this as an example for `services.zabbixAgent.settings`?

Definitely! Are you able/willing to write up a PR to add this?

**Comment by Jauchi** [comment]
> > Would it be possible to add something like this as an example for `services.zabbixAgent.settings`?
> 
> Definitely! Are you able/willing to write up a PR to add this?

Sure, but I'm a little short on time right now, so it may be a couple of days. Thank you very much for the quick help, I really appreciate it!

**Comment by aanderse** [comment]
No problem. Thank you!

**Pull request closed without merging**
