### PR TITLE
matrix-appservice-slack: 1.4.0 -> 1.6.1

### PR DESCRIPTION
**Pull request by kampka**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kampka** [comment]
@GrahamcOfBorg  build matrix-appservice-slack

**Comment by georgyo** [comment]
This was seems to have fallen though the cracks and never merged.

@kampka I tried updating this to 1.6.0, however I get the following error which I can not reproduce outside of `nix-build`

```
npm ERR! Maximum call stack size exceeded loadAllDepsIntoIdealTrK

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-10-12T11_34_10_088Z-debug.log

builder for '/nix/store/ppysc1ddp3gzk96k05md2w54bm9p6kx5-node_matrix-appservice-slack-1.6.0.drv' failed with exit code 1
error: build of '/nix/store/ppysc1ddp3gzk96k05md2w54bm9p6kx5-node_matrix-appservice-slack-1.6.0.drv' failed
```

If I try `nix-shell --pure default.nix -A matrix-appservice-slack` I get a completely different error when running `genericBuild`
```
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/@types%2fjson-schema failed: cache mode is 'only-if-cached' but no cached response available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/.npm/_logs/2020-10-12T11_36_08_165Z-debug.log
```

However if I run `npm install && npm build` it all works. I cannot figure out where and why the build process is failing.

**Comment by kampka** [comment]
@georgyo the thing with `node2nix` in the way that it is used here is, it does not pull in dependency version quite as specified in `package.json` and `package-lock.json` so using it to generate a working `node-packages.nix`, the stars and the npmjs repository and all the ancient gods have to agree that now is the time that it shall maybe work.
To make this more stable, the package would probably have to be rewritten, for which I currently lack the time, or node2nix would have to adjust / fix it's behavior in these cases.

**Comment by kampka** [comment]
Filed an issue for that: https://github.com/svanderburg/node2nix/issues/207

**Comment by kampka** [comment]
@GrahamcOfBorg build matrix-appservice-slack

**Comment by kampka** [comment]
@GrahamcOfBorg build matrix-appservice-slack

**Comment by SuperSandro2000** [comment]
@kampka

**Comment by kampka** [comment]
@SuperSandro2000 pong

**Comment by kampka** [comment]
Closing this as this package is now being removed for being unmaintained.

**Pull request closed without merging**
