### PR TITLE
Fixed two intra-page links to headers

### PR DESCRIPTION
**Pull request by Hodapp87**

### CODE REVIEW

**Comment by vcunat** [comment]
The current state browsed on http://nixos.org/nixpkgs/manual/#how-to-install-haskell-packages seems well-linked on those two places.

**Comment by peti** [comment]
Yeah, I also can't see any problem in the generated output.

**Comment by Hodapp87** [comment]
Oh, I was looking rather at https://github.com/NixOS/nixpkgs/blob/master/doc/haskell-users-guide.md#how-to-install-a-compiler and seeing that GitHub didn't interpret them properly.

**Comment by vcunat** [comment]
I see. It's unclear to me which of the markdown formats to choose. Perhaps still merge this to have better compatibility?

**Comment by peti** [comment]
The document uses Pandoc's extended Markdown, which Github doesn't handle in its entirety. The best place to read it is http://nixos.org/nixpkgs/manual/#how-to-install-haskell-packages, really.

**Pull request closed without merging**
