### PR TITLE
Backport of mupdf to address various CVEs

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

This is PR #68506 rebased on the release 19.09 branch. mupdf in 19.09 has various known vulnerabilities:

https://github.com/NixOS/nixpkgs/issues/70113

I checked the builds of the references derivations and ran the binaries. Since I do not know/use all of these programs, I could not test them extensively.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @vrthra @fpletz 

@teto

### CODE REVIEW

**Comment by flokli** [comment]
Hmm, can you cherry-pick backports with `-x` option?

**Comment by danieldk** [comment]
@flokli Should be fixed now.

**Comment by flokli** [comment]
@GrahamcOfBorg build mupdf zathura llpp k2pdfopt

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
