### PR TITLE
github-runner: switch to `buildDotnetModule`

### PR DESCRIPTION
**Pull request by veehaitch**
###### Description of changes

This PR continues what @IvarWithoutBones started in https://github.com/NixOS/nixpkgs/pull/191541:

- Switch to `buildDotnetModule`:
  * Deprecates the custom nuget script
  * Provides most `nativeBuildInputs` and `buildInputs` implicitly
  * Simplifies wrapping (though I ran into an issue tracked here #218449)
  * Builds without explicit `buildPhase` based on the given `projectFile`.
  * Out-of-the-box support for `disabledTests`
  * The (unwrapped) runner files are now located in `lib/github-runner/` instead of `lib/` directly. As a result, `externals` are now also located under `lib/` (as the directory is addressed relative to binaries).
  * Smaller closure (not self-contained anymore)
- Retrieve the actual commit hash instead of a fake SHA1
- Removes some tests from `disabledTests` which do not exist anymore
- Adds a basic `installCheckPhase`
- At least on Linux, wrapping does not add any `LD_LIBRARY_PATH` entries anymore. Darwin still adds `libicu` to `LD_LIBRARY_PATH`.
- In the NixOS module, use `Runner.Listener configure` directly to register the runner
- Adds a basic NixOS test

Supersedes #191541 
Fixes #169812

I tested the PR on NixOS with some of our workflows and everything seems to work as before. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Trundle** [comment]
Result of `nixpkgs-review pr 218455` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>github-runner</li>
  </ul>
</details>

The test also passed

**Comment by aanderse** [comment]
Awesome! Thank you both for this! Is anyone who knows about our `.NET` infrastructure able to review this? If not I'm still happy to merge this given that the work is a collaboration between yourself and @IvarWithoutBones (both people with high credibility in my books :+1:) as long as we can get at least one thumbs up from testing... (I may not have the time to test this soon).

**Review by newAM — APPROVED** [review]
Great improvements in packaging!

Builds and runs on x86_64-linux.

**Comment by veehaitch** [comment]
NB: We have been testing this PR for the past week and didn't run into any problems.

**Comment by domenkozar** [comment]
This broke using Nix, as it added LD_LIBRARY_PATH to `/var/lib/github-runner/xxx/.env`. Removing it and restarting the github-runner fixes it.

**Comment by aanderse** [comment]
> FYI: This broke using Nix, as it added LD_LIBRARY_PATH to `/var/lib/github-runner/xxx/.env`. Removing it and restarting the github-runner fixes it.

@domenkozar can you please elaborate and share details? One of the goals of this PR was to fix using `nix`... which it did. Hint: before this PR it was broken.

I am interested in hearing about how/why we had opposite results.

**Comment by domenkozar** [comment]
This was inside the `.env` file:

```
LANG=en_US.UTF-8
LD_LIBRARY_PATH=/nix/store/cgmpl823df6sjgc9qbb9wrw379x8yvwk-curl-7.86.0/lib:/nix/store/3xm08j9yrcj91saxq4s3ndl2gc2n717v-libkrb5-1.20/lib:/nix/store/wprxx5zkkk13hpj6k1v6qadjylh3vq9m-gcc-11.3.0-lib/lib:/nix/store/zaflwh2nwzj1f0wngd7hqm3nvlf3yhsx-zlib-1.2.13/lib:/nix/store/wkmc51s1nyyic7ym9c44k57wk8aqlpp9-icu4c-72.1/lib:/nix/store/8mag3ysxw4ln93jpdx7k2i4ci39pzlxf-lttng-ust-2.13.1/lib:/nix/store/zpwhl35d2dkj0p4bli5wp6sw1vfsyab5-openssl-3.0.7/lib
```

And Nix crashes:

```
/nix/store/iij5d6mjlcby5al6ifjcqj2fgy0lyg9m-nix-2.13.3/bin/nix version
/nix/store/iij5d6mjlcby5al6ifjcqj2fgy0lyg9m-nix-2.13.3/bin/nix: /nix/store/wprxx5zkkk13hpj6k1v6qadjylh3vq9m-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/iij5d6mjlcby5al6ifjcqj2fgy0lyg9m-nix-2.13.3/lib/libnixstore.so)
/nix/store/iij5d6mjlcby5al6ifjcqj2fgy0lyg9m-nix-2.13.3/bin/nix: /nix/store/wprxx5zkkk13hpj6k1v6qadjylh3vq9m-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/iij5d6mjlcby5al6ifjcqj2fgy0lyg9m-nix-2.13.3/lib/libnixutil.so)
/nix/store/iij5d6mjlcby5al6ifjcqj2fgy0lyg9m-nix-2.13.3/bin/nix: /nix/store/wprxx5zkkk13hpj6k1v6qadjylh3vq9m-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/xjbyll8g4xb2kjz728r3sa5ygnff4x39-aws-sdk-cpp-1.9.294/lib/libaws-cpp-sdk-transfer.so)
/nix/store/iij5d6mjlcby5al6ifjcqj2fgy0lyg9m-nix-2.13.3/bin/nix: /nix/store/wprxx5zkkk13hpj6k1v6qadjylh3vq9m-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/xjbyll8g4xb2kjz728r3sa5ygnff4x39-aws-sdk-cpp-1.9.294/lib/libaws-cpp-sdk-core.so)
```

**Comment by aanderse** [comment]
Thanks for the info @domenkozar.

**Comment by Pacman99** [comment]
I'm having a similar issue with this PR, filed a bug report here https://github.com/NixOS/nixpkgs/issues/227269

**Pull request merged**
