### PR TITLE
Kafka and c libraries for kafka and zookeeper

### PR DESCRIPTION
**Pull request by commandodev**

### CODE REVIEW

**Comment by copumpkin** [comment]
Did you forget to put the two libraries into a`ll-packages.nix`?

**Comment by boothead** [comment]
Looks like I messed up the commits. The entries onto all-packages.nix
landed with my other PR https://github.com/NixOS/nixpkgs/pull/6123.

Sorry about that!

On 3 February 2015 at 21:13, Daniel Peebles <notifications@github.com>
wrote:

> Did you forget to put the two libraries into all-packages.nix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/6121#issuecomment-72735863>.
>



-- 
Regards,
Ben Ford
ben.fordnz@gmail.com
+447540722690

**Comment by ragnard** [comment]
@boothead @copumpkin A bit late to this, but I believe the `kafka` package is duplicate of `apache-kafka`, also used by the nixos service.

**Comment by lethalman** [comment]
I've reverted only the commit that added kafka in 80d8d1fc276cd6a075b28e89f75f141bc6770b7f, as it already existed together with a nixos service.

**Comment by boothead** [comment]
Good catch, sorry about the noise!

**Pull request merged**
