### PR TITLE
Darwin GL Experiments

### PR DESCRIPTION
**Pull request by matthewbauer**
Trying to get some GL things to build with Darwin / macOS / XQuartz

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by abbradar** [comment]
Eval fails.

On `glxinfo` - maybe we want to put it into a separate output? The reason being `glxinfo` is very often used by various applications but other demo apps aren't that needed and eat up space.

**Comment by matthewbauer** [comment]
Yeah, alternatively move all of the demos to a "demos" output, as they are much less important.

**Comment by matthewbauer** [comment]
My main issue right now is the demos and glxinfo aren't actually working on macOS!

**Comment by matthewbauer** [comment]
Dropping the mesa-demos part for now.

**Pull request merged**
