### PR TITLE
python312Packages.accelerate: disable test_dynamo_extract_model

### PR DESCRIPTION
**Pull request by ConnorBaker**
## Description of changes

Disables another test which requires Dynamo support.

ZHF: #309482

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ConnorBaker** [comment]
Result of `nixpkgs-review pr 314709` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.argos-translate-files</li>
    <li>python312Packages.argos-translate-files.dist</li>
    <li>python312Packages.argostranslate</li>
    <li>python312Packages.argostranslate.dist</li>
    <li>python312Packages.translatehtml</li>
    <li>python312Packages.translatehtml.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python312Packages.accelerate</li>
    <li>python312Packages.accelerate.dist</li>
    <li>python312Packages.diffusers</li>
    <li>python312Packages.diffusers.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
    <li>python312Packages.manifest-ml</li>
    <li>python312Packages.manifest-ml.dist</li>
    <li>python312Packages.peft</li>
    <li>python312Packages.peft.dist</li>
    <li>python312Packages.stanza</li>
    <li>python312Packages.stanza.dist</li>
  </ul>
</details>

**Comment by ConnorBaker** [comment]
Result of `nixpkgs-review pr 314709` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.argos-translate-files</li>
    <li>python312Packages.argos-translate-files.dist</li>
    <li>python312Packages.argostranslate</li>
    <li>python312Packages.argostranslate.dist</li>
    <li>python312Packages.translatehtml</li>
    <li>python312Packages.translatehtml.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python312Packages.accelerate</li>
    <li>python312Packages.accelerate.dist</li>
    <li>python312Packages.diffusers</li>
    <li>python312Packages.diffusers.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
    <li>python312Packages.manifest-ml</li>
    <li>python312Packages.manifest-ml.dist</li>
    <li>python312Packages.peft</li>
    <li>python312Packages.peft.dist</li>
    <li>python312Packages.stanza</li>
    <li>python312Packages.stanza.dist</li>
  </ul>
</details>

**Comment by ConnorBaker** [comment]
No CUDA `aarch64-linux`.

```console
nix run .#nixpkgs-review -- pr 314709 \
  --system aarch64-linux \
  --no-shell \
  --build-graph nix \
  --print-result
```

Result of `nixpkgs-review pr 314709` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.argos-translate-files</li>
    <li>python312Packages.argos-translate-files.dist</li>
    <li>python312Packages.argostranslate</li>
    <li>python312Packages.argostranslate.dist</li>
    <li>python312Packages.translatehtml</li>
    <li>python312Packages.translatehtml.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python312Packages.accelerate</li>
    <li>python312Packages.accelerate.dist</li>
    <li>python312Packages.manifest-ml</li>
    <li>python312Packages.manifest-ml.dist</li>
    <li>python312Packages.peft</li>
    <li>python312Packages.peft.dist</li>
    <li>python312Packages.stanza</li>
    <li>python312Packages.stanza.dist</li>
  </ul>
</details>

**Comment by ConnorBaker** [comment]
Result of `nixpkgs-review pr 314709` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.argos-translate-files</li>
    <li>python312Packages.argos-translate-files.dist</li>
    <li>python312Packages.argostranslate</li>
    <li>python312Packages.argostranslate.dist</li>
    <li>python312Packages.translatehtml</li>
    <li>python312Packages.translatehtml.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python312Packages.accelerate</li>
    <li>python312Packages.accelerate.dist</li>
    <li>python312Packages.diffusers</li>
    <li>python312Packages.diffusers.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
    <li>python312Packages.manifest-ml</li>
    <li>python312Packages.manifest-ml.dist</li>
    <li>python312Packages.peft</li>
    <li>python312Packages.peft.dist</li>
    <li>python312Packages.stanza</li>
    <li>python312Packages.stanza.dist</li>
  </ul>
</details>

**Review by bcdarwin — APPROVED** [review]
LGTM, thanks.

**Comment by ConnorBaker** [comment]
Merging as ofborg has been stuck for 16h waiting to build it on `aarch64-darwin`, which I covered with `nixpkgs-review`.

**Pull request merged**
