### PR TITLE
haskellPackages: update hackage

### LINKED ISSUE #340712: Update request: haskellPackages.xmonad-contrib 0.18.0 → 0.18.1
- Package name: `haskellPackages.xmonad-contrib`
- Latest released version: `0.18.1`

- Current version on the unstable channel: `0.18.0`
- Current version on the stable/release channel: `0.18.0`

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@dschrempf @ivanbrennan @peti @slotThe 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by sternenseemann**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

More information about Haskell packages in nixpkgs can be found [in the nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#haskell).

---

This is the follow-up to #335932. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

No new version of stackage at this time (2024-09-03)!

### CODE REVIEW

**Comment by collinarnett** [comment]
One thing I noticed with one of the new packages `tiktoken` is that it requires `base64_1_0` instead of `base64`. Not sure how to contribute but I thought I would give a heads up while I'm testing using it before this pr gets merged.

**Comment by maralorn** [comment]
@collinarnett are you sure this is not fixable by using `doJailbreak`? (you can Ctrl+F this in the nixpkgs manual or in our configuration-common.nix file in nixpkgs.) The first release of tiktoken is 7 months after the release of base64, so I assume they just never tried to compile it with an earlier version.

**Comment by collinarnett** [comment]
I just tried it with `doJailbreak` and it breaks the tests.

```
[1/0/4 built, 0.0 MiB DL] building tiktoken-1.0.3direnv: ([/nix/store/1mrvvx2ygfyfz8sn3gg5f3qidvd9s8j1-direnv-2.34.0/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
error: builder for '/nix/store/mk0j2969fp6rsszzi4vfqxmqkbsqi9gx-tiktoken-1.0.3.drv' failed with exit code 1;
       last 25 log lines:
       > No pkg-config found
       > Using runghc version 9.6.5 found on system at:
       > /nix/store/hzdv2lb4sr83cbnx4c3fi6idpimvwab7-ghc-9.6.5/bin/runghc-9.6.5
       > Using strip version 2.41 found on system at:
       > /nix/store/md6hh4rrcrf99nssvcam3qaqs3skj086-gcc-wrapper-13.2.0/bin/strip
       > Using tar found on system at:
       > /nix/store/4m4vnjdy44s4sb8hlv4qsph492zz3rly-gnutar-1.35/bin/tar
       > No uhc found
       > Running phase: buildPhase
       > Preprocessing library for tiktoken-1.0.3..
       > Building library for tiktoken-1.0.3..
       > [1 of 2] Compiling Paths_tiktoken   ( dist/build/autogen/Paths_tiktoken.hs, dist/build/Paths_tiktoken.o, dist/build/Paths_tiktoken.dyn_o )
       > [2 of 2] Compiling Tiktoken         ( src/Tiktoken.hs, dist/build/Tiktoken.o, dist/build/Tiktoken.dyn_o )
       >
       > src/Tiktoken.hs:109:19: error: [GHC-76037]
       >     Not in scope: ‘Base64.Encoding.decodeBase64Untyped’
       >     NB: the module ‘Data.ByteString.Base64’ does not export ‘decodeBase64Untyped’.
       >     Suggested fix:
       >       Perhaps use one of these:
       >         ‘Base64.Encoding.decodeBase64’ (imported from Data.ByteString.Base64),
       >         ‘Base64.Encoding.decodeBase64Lenient’ (imported from Data.ByteString.Base64),
       >         ‘Base64.Encoding.encodeBase64’ (imported from Data.ByteString.Base64)
       >     |
       > 109 |     token <- case Base64.Encoding.decodeBase64Untyped base64Bytes of
       >     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       For full logs, run 'nix log /nix/store/mk0j2969fp6rsszzi4vfqxmqkbsqi9gx-tiktoken-1.0.3.drv'.
error: 1 dependencies of derivation '/nix/store/iild3js51yv77mp29rk2zmdrklai7akw-ghc-9.6.5-with-packages.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r21kjqdmf6cg91pcz07008zrlaab4jpl-ghc-shell-for-packages-0-env.drv' failed to build
```

In the repo's flake they explicitly override base64 to version 1.0 as well here. https://github.com/Gabriella439/tiktoken/blob/2e66d1e29acf66f08959f86080d53b07bccb5ae4/flake.nix#L18C1-L22C23

**Comment by maralorn** [comment]
Thank you. If you want you can open a PR which does this override in `configuration-common.nix` with a comment explaining that at least base64 1.0 is required, but LTS 22 contains an older version. Then you can drop tiktoken from a file called broken.yaml and run maintainers/scripts/haskell/regenerate-hackage-packages.sh.

**Comment by vcunat** [comment]
At this point, do you mind either waiting with Hydra builds for (probably) two days or merging `staging-next` into `haskell-updates`?

**Comment by sternenseemann** [comment]
> At this point, do you mind either waiting with Hydra builds for (probably) two days or merging `staging-next` into `haskell-updates`?

That's fine, feel free to cancel them any time. I checked the queue and at the time it seemed to be mostly blocked on a single platform, so figured extra builds may not matter. In any case, this iteration isn't time critical in the least bit.

**Comment by sternenseemann** [comment]
Two notable regressions I have noticed so far: pcg-random (aarch64-linux only) and dhall-docs

- https://hydra.nixos.org/build/272381297
- https://hydra.nixos.org/build/272365951

This seems to be related with the changed handling of ncurses in our GHC expression. This influences the terminfo package which has a changed package db entry now:

```diff
--- /nix/store/wsjvk8znfjimb6jc9m2mg50q1dyf4zi4-ghc-9.6.6/lib/ghc-9.6.6/lib/package.conf.d/terminfo-0.4.1.6.conf	1970-01-01 01:00:01.000000000 +0100
+++ /nix/store/0ac7ys577fvpihm342v5fpgzcqwkw41z-ghc-9.6.6/lib/ghc-9.6.6/lib/package.conf.d/terminfo-0.4.1.6.conf	1970-01-01 01:00:01.000000000 +0100
@@ -25,24 +25,15 @@
     System.Console.Terminfo.Keys
 
 import-dirs:          ${pkgroot}/../lib/aarch64-linux-ghc-9.6.6/terminfo-0.4.1.6
-library-dirs:
-    ${pkgroot}/../lib/aarch64-linux-ghc-9.6.6/terminfo-0.4.1.6
-    /nix/store/qmckz7yxdzs3ijms4g6ym25k9kjvvf8w-ncurses-6.4.20221231/lib
-
-dynamic-library-dirs:
-    ${pkgroot}/../lib/aarch64-linux-ghc-9.6.6
-    /nix/store/qmckz7yxdzs3ijms4g6ym25k9kjvvf8w-ncurses-6.4.20221231/lib
-
+library-dirs:         ${pkgroot}/../lib/aarch64-linux-ghc-9.6.6/terminfo-0.4.1.6
+dynamic-library-dirs: ${pkgroot}/../lib/aarch64-linux-ghc-9.6.6
 data-dir:
     ${pkgroot}/../share/aarch64-linux-ghc-9.6.6/terminfo-0.4.1.6
 
 hs-libraries:         HSterminfo-0.4.1.6
 extra-libraries:      tinfo
-include-dirs:
-    /nix/store/2jypnc3s7vqc92k20mlbdbq11phgxdid-ncurses-6.4.20221231-dev/include
-
 depends:              base-4.18.2.1
-haddock-interfaces: "${pkgroot}/../../../../fdycvh2hn15mpv3iy9434ahj5ry2rjp0-ghc-9.6.6-doc/share/doc/ghc/html/libraries/terminfo-0.4.1.6/terminfo.haddock"
+haddock-interfaces: "${pkgroot}/../../../../yl3xznbsb4yhyd5c0dgp2c9xlmx3gjdr-ghc-9.6.6-doc/share/doc/ghc/html/libraries/terminfo-0.4.1.6/terminfo.haddock"
 
 
-haddock-html: "${pkgroot}/../../../../fdycvh2hn15mpv3iy9434ahj5ry2rjp0-ghc-9.6.6-doc/share/doc/ghc/html/libraries/terminfo-0.4.1.6"
+haddock-html: "${pkgroot}/../../../../yl3xznbsb4yhyd5c0dgp2c9xlmx3gjdr-ghc-9.6.6-doc/share/doc/ghc/html/libraries/terminfo-0.4.1.6"
```

Notably, the ncurses' `/lib` and `/include` dirs are forgotten about. The challenge is going to be reintroducing that without breaking cross-compilation of GHC…

**Comment by sternenseemann** [comment]
The dhall etc. regressions are fixed by passing `--with-curses-*` again. I'll have to investigate if that's fine to do or causes other problems.

The pcg-random regression remains a mystery. `ExitFailure (-11)` may indicate a segmentation fault of some kind. I'll try bisecting.

**Comment by sternenseemann** [comment]
Bisect claims cd31b044130aa79baf368c5c3adb799cf5e3f00b is the first bad commit which is kind of bizarre.

**Comment by sternenseemann** [comment]
The symptom is indeed that `System.Random.PCG.Single.initFrozen 0` segfaults in GHCi (at least in the way cabal-doctest ends up invoking it).

**Comment by sternenseemann** [comment]
Even more bizarrely, this problem only seems to affect GHC 9.6.

**Comment by sternenseemann** [comment]
> Bisect claims [cd31b04](https://github.com/NixOS/nixpkgs/commit/cd31b044130aa79baf368c5c3adb799cf5e3f00b) is the first bad commit which is kind of bizarre.

This is beginning to make sense: The built GHCs now retain a reference to the binary GHC used for stage0 in the rpaths of the executables. Whether this is responsible for the segfault I'm not sure about yet. We should get rid of them either way.

**Comment by sternenseemann** [comment]
`pkgsCross.riscv64.haskell.compiler.ghc8107` has apparently regressed… that's what you get for not adding the job right away…

**Comment by sternenseemann** [comment]
GHC 8.10.7 on aarch64-linux has a similar issue to GHC 9.6 used to have: It retains a reference on the stage0 compiler.

**Comment by sternenseemann** [comment]
9.10.1 failures we see sometimes are due to: https://gitlab.haskell.org/ghc/ghc/-/issues/25153

**Pull request merged**
