### PR TITLE
nixos/gdm: disable the gdm services as it is redundant

### LINKED ISSUE #108672: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation
**Describe the bug**
I updated my system (unstable) channel and now `gdm` refuses to start:

**To Reproduce**
The important parts of my configuration (I hope this is enough to reproduce):

```nix
{ config, pkgs, ... }: {
  imports = [ ./hardware-configuration.nix ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  environment.systemPackages = with pkgs; [ libinput iio-sensor-proxy ];
  hardware.sensor.iio.enable = true;
  services.xserver.enable = true;
  services.xserver.libinput.enable = true;
  services.xserver.displayManager.gdm = {
    enable = true;
    wayland = true;
  };
  services.xserver.displayManager.autoLogin = {
    enable = true;
    user = "piegames";
  };
  services.xserver.desktopManager.gnome3.enable = true;
  services.xserver.desktopManager.gnome3.sessionPath =
    [ pkgs.gnome3.gedit pkgs.gnome3.mutter ];
  system.stateVersion = "20.03"; # Did you read the comment?
}
```

I was previously on nixpkgs commit `61525137fd1002f6f2a5eb0ea27d480713362cd5` (something from september 2020), and updated to latest unstable as of 2021-01-06 (cannot easily copy commit atm, maybe `b349d080d79d9d4e7ae3a88d199aa4161ace57f8`).

**Expected behavior**
Gdm starts just fine, just as it did before.

**Notify maintainers**
Gnome team: @hedning @jtojnar @worldofpeace @dasj19 

**Metadata**
- system: `"x86_64-linux"`
- host os: `Linux 5.4.86, NixOS, 21.03pre261529.d9dba88d08a, nixpkgs-unstable-21.03pre261714.44c443a7a60`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.10`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- gnome3.gdm
- gnome3.gnome-shell
- gnome3.mutter
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by Artturin**
and causes issues

###### Motivation for this change
Closes #108672

###### Things done

We can either 
```
    systemd.services.gdm.enable = false;
```
or remove gdm from the `systemd.packages` but i dont know if that will create more issues

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
@fakedrake @skogsbrus

**Comment by fakedrake** [comment]
I won't be able to test it for a few weeks but it looks lgtm.

**Review by doronbehar — APPROVED** [review]
I'm not one of those that experience the issue where gdm won't start at all, as some do in https://github.com/NixOS/nixpkgs/issues/108672, but I can testify that `systemctl status gdm.service` no longer outputs `gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation`. So I think this is good.

Well done! @Artturin .

**Comment by skogsbrus** [comment]
Super new to Nix / Nix OS, so not sure how to test the change. I couldn't find any relevant tips in [the manual](https://nixos.org/manual/nixpkgs/stable/#reviewing-contributions-module-updates) on how to review module changes. Would love to give it a try if I get some guidance! :)

**Comment by Artturin** [comment]
> Super new to Nix / Nix OS, so not sure how to test the change. I couldn't find any relevant tips in [the manual](https://nixos.org/manual/nixpkgs/stable/#reviewing-contributions-module-updates) on how to review module changes. Would love to give it a try if I get some guidance! :)

https://github.com/NixOS/nixpkgs/pull/128032#issuecomment-867929544
i can write a wiki page for reviewing changes later

**Comment by doronbehar** [comment]
> Super new to Nix / Nix OS, so not sure how to test the change. I couldn't find any relevant tips in [the manual](https://nixos.org/manual/nixpkgs/stable/#reviewing-contributions-module-updates) on how to review module changes. Would love to give it a try if I get some guidance! :)

@skogsbrus in this case it is super simple to test this change (I did so myself because the change here is so simple), just add to your `/etc/nixos/configuration.nix`:

```nix
systemd.services.gdm.enable = false;
```

And rebuild your system as usual with `nixos-rebuild`.

**Comment by Artturin** [comment]
> > Super new to Nix / Nix OS, so not sure how to test the change. I couldn't find any relevant tips in [the manual](https://nixos.org/manual/nixpkgs/stable/#reviewing-contributions-module-updates) on how to review module changes. Would love to give it a try if I get some guidance! :)
> 
> @skogsbrus in this case it is super simple to test this change (I did so myself because the change here is so simple), just add to your `/etc/nixos/configuration.nix`:
> 
> ```nix
> systemd.services.gdm.enable = false;
> ```
> 
> And rebuild your system as usual with `nixos-rebuild`.


Hah I forgot the easiest way

**Pull request merged**
