### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build pkgsCross.armv7l-hf-multiplatform.linux

**Comment by volth** [comment]
Please, include https://github.com/NixOS/nixpkgs/compare/staging...volth:patch-328 to fix https://github.com/NixOS/nixpkgs/pull/60169/checks?check_run_id=110135147

**Comment by volth** [comment]
And https://github.com/NixOS/nixpkgs/pull/60171

**Comment by matthewbauer** [comment]
@volth Cherry picked those. For future reference those usually these cross build things can go directly to master.

**Comment by FRidh** [comment]
@matthewbauer the wasm change broke the tarball job due to a failing test https://hydra.nixos.org/build/92604062

**Comment by volth** [comment]
@matthewbauer and https://github.com/NixOS/nixpkgs/pull/60238 please.
Or remove ```perlPackages.HTTPDaemon: 6.01 -> 6.04```, there is a regression

**Pull request merged**
