### PR TITLE
cups: 2.2.6 -> 2.2.10

### PR DESCRIPTION
**Pull request by dtzWill**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Still not sure why tooling ignores exit code? Anyway sorry about the noise :).

**Comment by rasendubi** [comment]
2.2.10 is released

**Comment by Mic92** [comment]
The errors for hub pull-requests, when editing a file are ignored here: https://github.com/github/hub/blob/f4252d55ecfa76aa4db50458faab4a269dada014/github/message_builder.go#L25

**Comment by dtzWill** [comment]
> The errors for hub pull-requests, when editing a file are ignored here: https://github.com/github/hub/blob/f4252d55ecfa76aa4db50458faab4a269dada014/github/message_builder.go#L25

<3 thanks

Also, will be updating for new release shortly (just some commit shuffling/picking)

**Comment by dtzWill** [comment]
Things like hplip have updates but that expression scares me :3.

**Pull request merged**
