### PR TITLE
nodejs: 6.6.0 -> 6.7.0

### PR DESCRIPTION
**Pull request by lo1tuma**
###### Things done
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

[Release Notes](https://nodejs.org/en/blog/release/v6.7.0/)

### CODE REVIEW

**Comment by lo1tuma** [comment]
Seems like travis failed because of a timeout.

**Comment by Mic92** [comment]
ping @gilligan something special I should test in addition to node, before merging this?

**Comment by gilligan** [comment]
@Mic92 - sorry, at a conference right now;) i would just make sure that it compiles on NixOS and the resulting node binary actually runs. I am fine merging then.

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
