### PR TITLE
libsoup_2_4: Rename from libsoup

### PR DESCRIPTION
**Pull request by jtojnar**
The 2.4 ABI branch has not been supported by upstream for a while now but people still keep accidentally adding it to new packages.

See #360897 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by maralorn — DISMISSED** [review]
This pr touches hackage-packages.nix

**Comment by jtojnar** [comment]
> This pr touches hackage-packages.nix

Not much we can do about that if we do not want to break eval without aliases. Well, we could place the alias to `all-packages.nix` instead, modify cabal2nix to use the new name, and then move it to `aliases.nix` but that sounds like to much bother.

**Comment by maralorn** [comment]
Well, we have to do something about it. I see two options: Either add overrides for these packages in configuration-nix.nix or in cabal2nix. I assume @sternenseemann has an opinion on what’s right here.

I mean in theory we don’t even know if the Haskell packages build with the newer libsoup.

**Comment by jtojnar** [comment]
It is not a new version, only the attribute name changed.

**Comment by sternenseemann** [comment]
We should probably do the same as we did with the attribute name rename of webkitgtk:

- Change cabal2nix to emit versioned attributes where the ABI version is statically known, but otherwise emit a dependency on a generic `libsoup` attribute (may it exist in nixpkgs or not). C.f. <https://github.com/NixOS/cabal2nix/pull/629>. 
- In the cases where no versioned attribute was generated, manually add overrides to `configuration-common.nix`: `pkg = super.pkg.override { libsoup = pkgs.…; }`. (I think with webkitgtk we didn't need to do this because all relevant packages use pkg-config which has the ABI version in the pc module name.)

**Comment by sternenseemann** [comment]
I've added the `cabal2nix-unstable` update to 2476dd6, so `hackage-packages.nix` should be reproducible using the generation script again.

**Comment by zowoq** [comment]
The `libsoup` -> `libsoup_2_4` rename breaks the `updateScript` which then breaks the `updateScript` fetcher for the `nixpkgs-update` bot.

```
$ nix-shell maintainers/scripts/update.nix --argstr path libsoup_2_4
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'nixpkgs-update-script'
         whose name attribute is located at /home/zowoq/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'shellHook' of derivation 'nixpkgs-update-script'
         at /home/zowoq/nixpkgs/maintainers/scripts/update.nix:261:3:
          260|   '';
          261|   shellHook = ''
             |   ^
          262|     unset shellHook # do not contaminate nested shells

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: Cannot find attribute ‘libsoup’.

```

> The 2.4 ABI branch has not been supported by upstream for a while now

Can we remove the `updateScript` from `libsoup_2_4`?

**Comment by bobby285271** [comment]
#366676

**Pull request merged**
