### PR TITLE
Cosmetic changes

### PR DESCRIPTION
**Pull request by jagajaga**

### CODE REVIEW

**Comment by spwhitt** [comment]
The logo looks a little large to me. You might consider embedding it as an HTML  tag, so you can set width and height to something smaller.

**Comment by jagajaga** [comment]
@spwhitt how to do it? :)

**Comment by spwhitt** [comment]
Here's a tweaked version of your commit as an example: https://github.com/spwhitt/nixpkgs/commit/ffd155de37a1b109d918b01512e09e0c0627af95

I picked that width at random, feel free to experiment.

**Comment by jagajaga** [comment]
@spwhitt like this one too :)

**Comment by spwhitt** [comment]
Though it also occurs to me that maybe a NixOS image is not the most appropriate for nixpkgs, which is also very useful on other systems.

**Comment by vcunat** [comment]
Heh, let's have a Nixpkgs logo &ndash; just replace the text and keep the flake ;-)

**Comment by jagajaga** [comment]
@vcunat maybe just `Nix`?

**Comment by domenkozar** [comment]
Wonderful. Now all we need is `CONTRIBUTING.md` :)

**Pull request merged**
