### PR TITLE
wireshark: 4.2.6 -> 4.4.2

### PR DESCRIPTION
**Pull request by pabloaul**
## Description of changes
- wireshark: 
  - 4.2.6 -> 4.4.2 
  - updated git patch offsets 
  - lua implicit 5.2 -> explicit 5.4
  - zlib -> zlib-ng
- pyshark: add https://github.com/KimiNewt/pyshark/pull/670 as a patch (thank you for finding this fpletz)
- credslayer: mark as broken due to failing tests on wireshark 4.4

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by teto** [comment]
running a nixpkgs-review .python3.12-pyshark-0.6 takes > 1 hour to build and it is still building. It seems stuck in pytestCheckPhase (according to nix-output-monitor). I haven't investigated but seems like some test is stuck

**Comment by pabloaul** [comment]
Had this issue aswell with the two stuck pytestCheckPhase. The processes for each were stuck sleeping, probably a race condition.
I am not sure if this is related to my changes though since the Github Actions went through fine

**Comment by bjornfor** [comment]
I get the same hang (for 8+ hours) for `nix-build -A python3Packages.pyshark` on the base commit (ed96506b5dcbb8d34ffe8ae0499d194ccfe9c71d) if I try to rebuild. However, on Hydra the build seems stable: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python312Packages.pyshark.x86_64-linux

**Comment by bjornfor** [comment]
> I get the same hang (for 8+ hours) for `nix-build -A python3Packages.pyshark` on the base commit ([ed96506](https://github.com/NixOS/nixpkgs/commit/ed96506b5dcbb8d34ffe8ae0499d194ccfe9c71d)) if I try to rebuild.

Nope, that's wrong. (It's too early in the morning.) I can build pyshark just fine on the base branch, so the hang looks like a regression in this PR.

**Review by bjornfor — DISMISSED** [review]
`nix-build -A python3Packages.pyshark` builds start to hang with this PR:

```
============================= test session starts ==============================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /build/source
collected 73 items / 1 deselected / 72 selected                                

../tests/capture/test_capture.py .....                                   [  6%]
[...waited hours without more output...]
```

If we can't fix it, I think we should at least turn that hang into a quick fail before merging this PR.

**Comment by pabloaul** [comment]
Okay, this must be patch related then... I'll take a closer look soon again at the changes from Wireshark

**Comment by pabloaul** [comment]
I was unable to track down the cause for the issue. If anyone more comfortable with the code and/or capture_sync.c could take a look, it would be much appreciated...

**Comment by fpletz** [comment]
Rebased, updated to new point release and picked a patch from pyshark master to fix the capture issue.

**Comment by pabloaul** [comment]
I think it would be fine to mark credslayer as broken.
pyshark seemingly still sort of works for the other projects that depend on it so I think we can leave it for now

**Review by fpletz — APPROVED** [review]

**Pull request merged**
