### PR TITLE
dhcp: 4.3.4 -> 4.3.6

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://kb.isc.org/article/AA-01518/82/DHCP-4.3.6-Release-Notes.html

Also removes need for a patch.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Works well so far, but should probably be carefully reviewed and tested before merged.

### CODE REVIEW

**Comment by dtzWill** [comment]
(this should probably go to staging first.. )

**Comment by dtzWill** [comment]
@GrahamcOfBorg build dhcp
@GrahamcOfBorg test networking ipv6 predictable-interface-names

**Review by fpletz — APPROVED** [review]

**Comment by fpletz** [comment]
On second thought, was the patch applied upstream or why don't we need that anymore?

**Comment by dtzWill** [comment]
Good question, I wish I had been more specific in my commit message back when I originally look at this... I didn't remember at first! :)

-----------

They moved from ifconfig to ip (from iproute2), rewriting the script quite a bit.

The patch fixed "flushing" the interface, the new script uses commands like:

```
            # alias IP may have changed => flush it
            ${ip} -4 addr flush dev ${interface} label ${interface}:0
```

instead of the problematic `ifconfig $interface inet 0 down` replaced by this patch.

**Comment by fpletz** [comment]
Oh, awesome, thanks! :+1:

**Comment by dtzWill** [comment]
@GrahamcOfBorg build dhcp
@GrahamcOfBorg test networking ipv6 predictable-interface-names

**Comment by dtzWill** [comment]
4.3.6-P1 is out: https://kb.isc.org/article/AA-01570/82/DHCP-4.3.6-P1-Release-Notes.html

Will bump this shortly...

**Pull request merged**
