### PR TITLE
Simplified totalmem calculation for zram.nix

### PR DESCRIPTION
**Pull request by CMCDragonkai**
Also the original one didn't even work on my computer.

### CODE REVIEW

**Comment by wizeman** [comment]
@CMCDragonkai: Could you remove the `procps` and `gnused` packages from the `PATH` in the script, since they are not needed anymore after your change?
Also, could you change your commit message to match the format specified in: http://hydra.nixos.org/job/nixpkgs/trunk/manual/latest/download-by-type/doc/manual#chap-submitting-changes

I assume you have tested this change, right?

**Comment by CMCDragonkai** [comment]
I've searched the entire repo, what is `procps`? And where is it defined? I've only tested the actual command itself, not the entire build. The original command didn't even work. can change the PR format soon.

**Comment by wizeman** [comment]
I was talking about this line, which is close to the lines you are modifying: https://github.com/MatrixAI/nixpkgs/blob/c97643fba6904319dfee4909183d69c73455be15/nixos/modules/config/zram.nix#L102

After your modifications, it doesn't seem like either `pkgs.procps` or `pkgs.gnused` is needed in the `PATH` anymore, so they should be removed (but you should probably keep `pkgs.gnugrep`).

**Comment by CMCDragonkai** [comment]
I saw the line, but what exactly is procps?

**Comment by wizeman** [comment]
@CMCDragonkai First result when searching in Google: http://procps.sourceforge.net/

Quoting:

`procps is the package that has a bunch of small useful utilities that give information about processes using the /proc filesystem. The package includes the programs ps, top, vmstat, w, kill, free, slabtop, and skill.`

In `all-packages.nix` you can find the `procps`, `procps-old`, `procps-ng` attributes (they point to different `procps` packages). You can find the derivations themselves in `pkgs/os-specific/linux/`, directories `procps` and `procps-ng`.

**Comment by CMCDragonkai** [comment]
Strange the github search didn't work for that. Thanks, will change the PR format tomorrow.

**Comment by CMCDragonkai** [comment]
@wizeman what about awk? Does that require a PATH import?

**Comment by CMCDragonkai** [comment]
Note that:

> Prior to kernel 3.15, each zram device contains it's own compression buffer, memory pools and other metadata as well as per-device locks. This can become a serious bottleneck for multi-core machines. To work around this problem, zram is capable of initializing multiple devices. For this reason, the recommended amount of devices for swap is 1 per cpu core for kernels prior to 3.15. 

This means at 3.15 or higher, one should be able to just:

```
echo $(nproc) > /sys/block/zram0/max_comp_streams
```

What do you think?

**Comment by CMCDragonkai** [comment]
Updated commit message.

**Comment by jgillich** [comment]
I think that instead of setting PATH, it should call the full path directly.
```
totalmem=$(${pkgs.gnugrep}/bin/grep 'MemTotal: ' /proc/meminfo | ${pkgs.gawk}/bin/awk '{print $2}')
```

**Comment by CMCDragonkai** [comment]
@jgillich Good point, I changed it according to your suggestion. Also I guess you answered my question regarding whether `awk` needed a path resolution. @wizeman can you review?

**Comment by wizeman** [comment]
Looks good to me. Just one more thing: could you squash the 3 commits together into 1 (e.g. using `git rebase -i`)?

You can leave the `zram: simplify totalmem calculation...` as the title for the commit.

Let me know when you do this, and I will merge it soon afterwards.
Thanks!

**Comment by CMCDragonkai** [comment]
@wizeman Done.

Please merge.

**Comment by fpletz** [comment]
Yes, this should be backported as it was indeed broken. There isn't a fixed backporting policy as far as I know. So I'll merge this and push a fix for the release-15.09 branch tomorrow if nobody objects.

**Pull request merged**
