### PR TITLE
nixos/gitlab: Improve support for GitLab Pages

### LINKED ISSUE #132295: gitlab-pages.service fails in test
`gitlab-pages.service` fails to start in the gitlab nixos test since 5606e90f8741b67c863647613aae31021642e1c4

```
gitlab # [   37.643367] gitlab-pages[1325]: time="2021-08-01T10:01:13Z" level=info msg="GitLab Pages Daemon" revision=HEAD version=dev
gitlab # [   37.659111] gitlab-pages[1325]: time="2021-08-01T10:01:13Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
gitlab # [   37.692905] gitlab-pages[1325]: time="2021-08-01T10:01:13Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
gitlab # [   37.724232] systemd[1]: gitlab-pages.service: Main process exited, code=exited, status=1/FAILURE
gitlab # [   37.755868] systemd[1]: gitlab-pages.service: Failed with result 'exit-code'.
gitlab # [   37.835846] systemd[1]: gitlab-pages.service: Scheduled restart job, restart counter is at 1.
gitlab # [   37.850066] systemd[1]: Stopped GitLab static pages daemon.
gitlab # [   37.868927] systemd[1]: Started GitLab static pages daemon.
gitlab # [   38.192279] gitlab-pages[1340]: time="2021-08-01T10:01:13Z" level=info msg="GitLab Pages Daemon" revision=HEAD version=dev
gitlab # [   38.224292] gitlab-pages[1340]: time="2021-08-01T10:01:13Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
gitlab # [   38.260198] gitlab-pages[1340]: time="2021-08-01T10:01:13Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
gitlab # [   38.291559] systemd[1]: gitlab-pages.service: Main process exited, code=exited, status=1/FAILURE
gitlab # [   38.337716] systemd[1]: gitlab-pages.service: Failed with result 'exit-code'.
gitlab # [   38.375489] systemd[1]: gitlab-pages.service: Scheduled restart job, restart counter is at 2.
gitlab # [   38.396191] systemd[1]: Stopped GitLab static pages daemon.
[...]
```

In previous versions of gitlab-pages the same message was printed as a warning.

CC @marsam @talyz

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
- Maintain `gitlab-pages` together with the rest of GitLab
- Update `gitlab-pages` to the latest version
- Add `gitlab-pages` to `update.py`
- Provide options under `services.gitlab.pages` and set defaults for important settings
- Generate the shared secret
- Reenable `gitlab-pages` in test

I haven't tested these changes outside of running the test. It would be nice if someone who actively uses Pages already could help with testing.

Fixes #132295 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by talyz** [comment]
Sorry, I didn't see your reply until just now :confused:

I see. I didn't know any secrets went into the config file. Yes, a patch would be greatly appreciated!

**Comment by onny** [comment]
Would be nice to get this fixed :) Do you mind rebase your PR on the recent changes?

**Comment by xanderio** [comment]
@talyz: If you currently don't have the time to rebase this, I would be up to do it, so we can get this merged :)

**Comment by xanderio** [comment]
I've rebased this PR at https://github.com/xanderio/nixpkgs/tree/gitlab-pages

Should I create a new PR from this rebase?

**Comment by xanderio** [comment]
Is there anything I can help with to get this merged?

ping @onny

**Comment by talyz** [comment]
I have some work to handle secrets that I still need to push. I'll get on that right away.

**Comment by talyz** [comment]
The updates have been pushed. Any help with testing would be appreciated!

**Comment by xanderio** [comment]
We're using these patch successfully for some time now in production.

**Pull request merged**
