### PR TITLE
pythonPackages.python-socketio_4: drop

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by graham33** [comment]
@dotlambda what was the motivation for dropping python-socketio 4 and python-engineio 3?  Note that the major version is tied to the protocol version, so if one wants to talk to a Socket.io 3.x or 4.x server, you have to use these versions and can't upgrade to python-socketio 5.x.  I can just put these in my NUR of course, but was maintaining them here in case others found them useful.

I'd also say procedurally it'd be good to tag the maintainer when dropping packages, just as an FYI.

**Comment by dotlambda** [comment]
> what was the motivation for dropping python-socketio 4 and python-engineio 3?

That versioned attributes aren't allowed within `pythonPackages` and there weren't being used anyway. You can always use a different version through `packageOverrides`.



> I'd also say procedurally it'd be good to tag the maintainer when dropping packages, just as an FYI.

Sorry, you're right.

**Comment by graham33** [comment]
Thanks @dotlambda - just so I understand, if I were to add a package that depends on these versions (I was considering doing this), would each user then be expected to add the required packageOverrides/overlays to their python environment?  Or would a package with this type of dependency just not be allowed in nixpkgs?  It is really annoying that the protocol and the libraries are versioned in this way...

**Comment by dotlambda** [comment]
If it's a Python package that is supposed to be used through `import foobar`, then using a non-standard version of a dependency is not allowed. For applications, you can override the dependencies' versions with `packageOverrides` though.

**Comment by graham33** [comment]
Ok thanks.  As I say, it's not exactly non-standard, in the sense that unfortunately upstream intend you to use different major versions of the module via the same import (see the table here: https://github.com/miguelgrinberg/python-socketio#readme).

In case anyone else needs these versions, I now have them back in my NUR: https://github.com/graham33/nur-packages

**Pull request merged**
