### PR TITLE
[20.09] python3Packages.humanize: fix missing dependency 

### PR DESCRIPTION
**Pull request by SuperSandro2000**
(cherry picked from commit b7f4d3d949b6a9f73f475fba3d839a3ea5b5708e)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by mweinelt — CHANGES_REQUESTED** [review]
Needs a motivation. Cleanups are not really worth backporting otherwise.

**Comment by SuperSandro2000** [comment]
> Needs a motivation. Cleanups are not really worth backporting otherwise.

The package does not work because setuptools is missing.

**Comment by mweinelt** [comment]
Then this is clearly not a cleanup.

**Comment by rmcgibbo** [comment]
This was one of my first commits to nixpkgs. I apologize if I used the wrong commit message.

**Review by rmcgibbo — APPROVED** [review]

**Pull request merged**
