### PR TITLE
gfortran/gcc: simplify & clean up on Darwin

### PR DESCRIPTION
**Pull request by copumpkin**
This should eliminate the branched logic for gfortran on Darwin, as well as preventing accidental inclusion of impure paths in gcc and gfortran builds.

Note that I don't think this will be a mass Linux rebuild, because I null out the `prePatch` on anything but a Darwin stdenv. It also won't mass-rebuild Darwin, so it should be pretty safe.

cc @adnelson 

P.S: I tested the new `gfortran` expression with `numpy` on Darwin and it seemed to be building fine...

###### Motivation for this change

The forked gfortran expression had broken on the latest LLVM 4 branch of the Darwin stdenv, so I noticed the fork and decided to kill it.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by adnelson — APPROVED** [review]
looks like a big win 👍

**Review by LnL7 — APPROVED** [review]

**Comment by copumpkin** [comment]
Just tested that there's no mass rebuild on NixOS, so I'm going to merge.

**Comment by vbgl** [comment]
Now `csdp` fails to build. This might be related to the changes in this PR.

```
clang -O3 -ansi -Wall -DNOSHORTS -DUSEGETTIME -I../include  csdp.o -L../lib -lsdp -llapack -lblas -lgfortran -lm -o csdp
clang-3.7: warning: argument unused during compilation: '-ansi'
ld: library not found for -lgfortran
```

**Comment by copumpkin** [comment]
Whoops, I'll take a look a bit later, thanks

**Pull request merged**
