### PR TITLE
lnd: 0.10.0 -> 0.10.3, enable same features as upstream

### PR DESCRIPTION
**Pull request by mmilata**
###### Motivation for this change

* 0.10.1 release: https://github.com/lightningnetwork/lnd/releases/tag/v0.10.1-beta
* was confused by missing `lncli` subcommands: https://github.com/lightningnetwork/lnd/blob/v0.10.1-beta/make/release_flags.mk#L36

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @jonasnick @cpunk2140

### CODE REVIEW

**Review by jonasnick — APPROVED** [review]
LGTM. Checked that the default tags are the same as in the release build and that this PR actually enables the tags in the build.

**Comment by nixbitcoin** [comment]
Can we bump this straight to `lnd 0.10.2` as only that version is currently compatible with `bitcoind 0.20` https://github.com/lightningnetwork/lnd/releases/tag/v0.10.2-beta.rc2 ?

**Comment by mmilata** [comment]
@nixbitcoin sure, can bump it to 0.10.2 when it's released, in a couple of days probably.

**Comment by nixbitcoin** [comment]
lnd v0.10.3-beta out now. Compatible with bitcoind 0.20.

**Comment by mmilata** [comment]
Bumped to 0.10.3.

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 8115b7552b873735e2d1d5717120465ad44512ee

Got same sha256 & vendorSha256
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEV3o0Un8+KoXoD+Fk3RH5rVMIs7oFAl8EXJAACgkQ3RH5rVMI
s7oEew//QE4+9orPkZ4pVghwhGKVfYZdD2vEfh0Au5gBD1fmkywkPeNUyAbggKrb
OHyEfdaTiTBrN1V0tyO7XXJ02CSBWqaTY6NWrHvQswRzcWXc8la8OlMPmO/wem81
2Xq+aqBQwdFz9x0hbrwJBFdw0z2UUJC/zf7wv3zuqyNtNA+v4qC1uI/dL3dc2f9H
2s9j62cy2Mi/IQViP0KcPCscRHRaLkjsyXhWxxu/j/FAAFScFRMalEh1M8dwQhgf
AKM9wMf35G0Fam1KazCo/58M3RzSTKAlMTdYyXnbcIC9aTU4OwQM+8KsXkvnfA+1
PlZ8d35KHiXHd4+/+eDGW/lFFDLSi9kyF8CvMRfWFp06pqkablkvW83is9Oe3mLA
2a0Q4rwj+Pcn2iUxmtG4TnEN43mVtpmxps9OMIKEIbpZRVIR3cS9XN6NmA2pqYe1
Dbw+ORkc4ZReUNjfMyKSnOQnNfWIzbIMNmEnYX9HonjiNhgpUQaGx84Tai1LePi3
2grFGNC0GXq9zT5yLyqEt7+59Hslga4DEBGuhm4CmSlabUpDZ4zg6FeP4RUw3pDO
o5t9+ewqQgmkE25lMRS8xUVSB1sK392TJKOFjLnbWV3/HN729b4sLJdYljmwSEFl
BF+BTgIKenqFAzJvrfqqNdH8/tB9lSIRhSNwelJ3hLv8h0GK45g=
=V0Yb
-----END PGP SIGNATURE-----
```

**Comment by nixbitcoin** [comment]
Tags are not showing up under `build_tags` with `lncli version`

**Comment by jonasnick** [comment]
LGTM.

Not a golang expert, but looking at lnd's Makefile, it seems that in order to make the tags show up in `lncli version` I think we have to add a `-ldflags=-X github.com/lightningnetwork/lnd/build.RawTags=...` build flag (and another one for `build.CommitHash` to fix `lnd -version`)

**Review by jonasnick — APPROVED** [review]
LGTM.

Not a golang expert, but looking at lnd's Makefile, it seems that in order to make the tags show up in lncli version I think we have to add a -ldflags=-X github.com/lightningnetwork/lnd/build.RawTags=... build flag (and another one for build.CommitHash to fix lnd -version)

**Comment by mmilata** [comment]
Good point. I've updated the PR to set `RawTags` and `GoVersion`. We can't reliably determine `Commit` and `CommitHash` so I think it's probably better to omit the so as not to cause confusion.

I mean `Commit` could be set to whatever `rev` we pass to `fetchFromGitHub` but would become inaccurate if `patches` is defined.

**Comment by nixbitcoin** [comment]
`build_tags` and `go_version` work now
```
{
    "lncli": {
        "commit": "",
        "commit_hash": "",
        "version": "0.10.3-beta",
        "app_major": 0,
        "app_minor": 10,
        "app_patch": 3,
        "app_pre_release": "beta",
        "build_tags": [
            "autopilotrpc",
            "signrpc",
            "walletrpc",
            "chainrpc",
            "invoicesrpc",
            "watchtowerrpc"
        ],
        "go_version": "go1.14.3"
    },
    "lnd": {
        "commit": "",
        "commit_hash": "",
        "version": "0.10.3-beta",
        "app_major": 0,
        "app_minor": 10,
        "app_patch": 3,
        "app_pre_release": "beta",
        "build_tags": [
            "autopilotrpc",
            "signrpc",
            "walletrpc",
            "chainrpc",
            "invoicesrpc",
            "watchtowerrpc"
        ],
        "go_version": "go1.14.3"
    }
}
```
Very strong.

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK f800711aaa7bd6a2df4197c7d88abf19b90e6212
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEV3o0Un8+KoXoD+Fk3RH5rVMIs7oFAl8IWQQACgkQ3RH5rVMI
s7r47w/8CdSQJ0hiiiRsUD4v7OOWsknP+hAyFjR9gYyelXWEuZ0bzU5ZhOSorkpY
+V4D9mPlbpWFr2XyPcq3UwowGWRSOlcyhGNHsPrS3yGoTXMLCpFmKUOfN4jlrIHd
an/A1MvmgQqNOO6Q4yWx8xgEBHCIWf3sg9rVrFX+KhHYjMRIF/myqho9SsRcVyi6
49mYYXgvApfAj+ASn2TFJdr9sDTFhJdOdsZbcNv8DqM8YA6Rq3SD3+n3jDNnZHAy
ErGMqBpwghOQv8FftDveQf/B+Rg7Sxrdou5Vnand6VFE07WbhkbE+h/79yKgvcXH
0bngu4e8nlgWrJZZ0kSYc28xwEulgllLA0jLk0tUn+cgHkvmQ1l+W8V7AD/fGB4v
DKz1M5vi5O9Lff7BwY9tGZ/WYTFUTdIoNbjM/T8zZOAWSAQ/V+YQ9EGaabRVly9L
emm43rEuULPi1AdlJ1G2xH6J3E9ZfNSgmYgiI60aZ78t+5thGtyOZAiMWuTUpuUV
Y80uhclo596B6Bqx5/FIzX3ICXyyum13zxFg8ExFOA4lIDZIvVlaEVvr2GrThifp
mQtC4s3tga5gLSJ4+nKQpYhrbj8UKg/a6hPMIYq9wnc8gLZwlAwrHbCyNYp6nSO3
fLDicu65HaCt5G4HmkvOIuAgXYL+0da2tvhcT28KOjzY7zZL5sg=
=g2CI
-----END PGP SIGNATURE-----
```

**Review by jonasnick — APPROVED** [review]
Cool! Can also confirm that it's possible to change the set of tags.

**Comment by jonasnick** [comment]
It should be noted perhaps that without this PR lnd is broken because the current version is incompatible with the bitcoind version in master (0.20).

**Pull request merged**
