### PR TITLE
haskell-modules/generic-builder.nix: use runCommand instead of phases

### PR DESCRIPTION
**Pull request by Stunkymonkey**
## Description of changes

part of #28910

what I tested: `nix-build . -A tests.haskell.shellFor`

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by maralorn** [comment]
Looks sensible to me.

Is there a reason to prefer stdenv.runCommand over pkgs.runCommand?

**Comment by sternenseemann** [comment]
stdenv.runCommand is better because it doesn't exist.

**Comment by mweinelt** [comment]
> stdenv.runCommand is better because it doesn't exist.

Try again.

**Comment by maralorn** [comment]
Well, we could just depend on `runCommand` directly instead of importing `pkgs`, right?

**Comment by Stunkymonkey** [comment]
sorry I intended to make a draft-PR, but instead submitted it right away.

**Comment by Stunkymonkey** [comment]
ping @maralorn ?

**Comment by maralorn** [comment]
LGTM, will need to check this out and try building a shell just to be sure.

**Comment by maralorn** [comment]
Is there a reason not to use runCommandNoCC?

**Comment by Stunkymonkey** [comment]
> Is there a reason not to use runCommandNoCC?

it never was `stdenvNoCC.mkDerivation` before, that is why I assumed to keep it this way... I am fine with both ways. Should I change it?

**Comment by maralorn** [comment]
No, you are right. This could be a breaking change to existing shells.

I tested it and I see nothing wrong with it.

**Pull request merged**
