### PR TITLE
update lua package set + several small fixes

### PR DESCRIPTION
**Pull request by teto**
## Description of changes

- bumped luarocks-nix that now uses nurl to generate nicer fetchers
- first stopped adding lua to propagatedinputs because of an issue I had when creating lua environements, but had to bring it back for the setupHook / envHook else lua programs were not getting wrapped. The utils.sh will be useful anyway post-release to record the relative paths in LUA_PATH
- BREAKING CHANGE in the format of the csv file. Replaced `src` column with `rockspec` - the URL to the actual rockspec - to simplify implementation and remove ambiguity. Before that, luarocks nix was downloading the repo and looking for rockspec files with a certain pattern. I suppose nixpkgs and one of my script is the the only consumer. It was not easy to use the lua updater out of tree before this release.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by teto** [comment]
the full nixpkgs review was too much so I've limited my testing to:
- built neovim and knot-resolver
- run lua-tests
- nixpkgs-review on vimPlugins and luaPackages
- build my config with it

Bottom line is the resty packages are broken (because they need the submodules I think) but:
- some of them are already broken
- they have no maintainer
- I am not sure yet how to decide how to tell `luarocks-nix` to generate the src with the submodules (short term a whitelist probably, later a smart mode for submodule autodetection in nurl ?).

The latter issues can be solved easily during ZHF. I would like to get this into staging-next first because it will unblock some fixes for neovim plugin dependencies, which I would like to have in the 24.05 release.

**Comment by teto** [comment]
I would like to get this in fast in staging-next to be able to fix a neovim issue with transitive dependencies and have a few days to see if breaks user configs before release. 
I've spent quite a bit of time testing this so I will self merge.

**Comment by vcunat** [comment]
`luaPackages.toml` doesn't look good:
https://hydra.nixos.org/build/258829548/nixlog/2/tail

**Comment by teto** [comment]
It escaped me. I dont think it matters that much ? it's a leaf package. I wanted to get the deep changes into staging first.
Then I can fix openresty and this one on master directly.

**Comment by vcunat** [comment]
Yes, it's probably worse that merging `master` into `staging-next` now gives a conflict in `pkgs/development/lua-modules/generated-packages.nix`, and I couldn't immediately see how to resolve it.

**Comment by vcunat** [comment]
(the conflict's been resolved somehow)

**Pull request merged**
