### PR TITLE
terraform: update providers

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
This updates all terraform providers, and simplifies the expression around it a bit.

The already-nullified `terraform-provider-azure-classic` was removed, `brightbox`, `huaweicloud`. `telefonicaopencloud` were added.

cc @jgeerds @zimbatm @peterhoeg @Mic92 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg eval

**Comment by Anton-Latukha** [comment]
@flokli 
Thank you =)

**Comment by LnL7** [comment]
@GrahamcOfBorg eval

**Comment by Mic92** [comment]
@GrahamcOfBorg build terraform_0_10-full terraform-full terragrunt terraform-provider-libvirt

**Pull request merged**
