### PR TITLE
wyvern: init at 1.4.1

### PR DESCRIPTION
**Pull request by 0x4A6F**
###### Motivation for this change

Add [wyvern](https://git.sr.ht/~nicohman/wyvern).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @0x4A6F

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build wyvern

**Comment by 0x4A6F** [comment]
@GrahamcOfBorg build wyvern

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 66641` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- wyvern
</details>

**Comment by tomberek** [comment]
```
hash mismatch in fixed-output derivation '/nix/store/lvkwxxp8nskrc63c19pg6kksk9rkgxf8-wyvern-1.4.0-vendor.tar.gz':
  wanted: sha256-ij6v3jXZtKKJYYRqzuCn4Cd+bqtTG0f2vSfOWsjyJi0=
  got:    sha256-rHkxLCbJgW2weJAUhLxzZRRkfYwPWJtRb5WWLr4tYUo=
```

**Comment by 0x4A6F** [comment]
Thanks to @nicohman there is now a functioning version released.

**Pull request merged**
