### PR TITLE
Prepare Coq derivation for Coq 8.17 build infrastructure.

### PR DESCRIPTION
**Pull request by Zimmi48**
###### Description of changes

Hopefully, this should make the Coq derivation work again in CI tests using Coq master. I have built the derivation locally, but I haven't yet tried a Coq Nix Toolbox build.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zimmi48** [comment]
As tested in https://github.com/coq-community/coq-nix-toolbox/pull/109, this seems to work fine.

cc @vbgl @CohenCyril

**Comment by Zimmi48** [comment]
So it turns out that I actually can split CoqIDE out. I will push a second commit doing this.

**Comment by Zimmi48** [comment]
BTW, cc @proux01 
We won't have the Coq Nix CI broken for three months this time.

**Comment by CohenCyril** [comment]
That's fantastic. Did you do a review of other deps (such as compcert and the like?)

**Comment by Zimmi48** [comment]
> That's fantastic. Did you do a review of other deps (such as compcert and the like?)

Not sure what you mean but I only ran the Coq Nix Toolbox on the one hand, and tried locally building pocklington (an example Coq package whose latest release is still compatible with Coq's master) on the other hand.

**Comment by CohenCyril** [comment]
I meant this `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`

**Comment by vbgl** [comment]
Yes, this PR only adds dead code…

**Comment by CohenCyril** [comment]
> Indeed, I didn't do it, but it should have no impact because this PR does not modify any (currently) exposed derivation (I mean exposed through an attribute).

Indeed sorry for the noise... I mixed it up with #180385

**Comment by Zimmi48** [comment]
> Yes, this PR only adds dead code…

Not completely dead 😁 it's reachable through the public API and it is actually used (which was the point for doing it now).

**Pull request merged**
