### PR TITLE
Revert "Revert "nixos/gitea: set service type to `notify`""

### PR DESCRIPTION
**Pull request by SuperSandro2000**
Reverts NixOS/nixpkgs#244843

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Wait until Forgejo maintainers split the Forgejo module.

**Comment by RaitoBezarius** [comment]
No, this is not the change we accepted to do, you didn't bother reading the discussion, so please do not engage further in that behavior.

**Comment by SuperSandro2000** [comment]
I don't see a reason here to wait on other people. They can take there time to do things properly and the workaround here is super simple.

**Comment by RaitoBezarius** [comment]
> I don't see a reason here to wait on other people. They can take there time to do things properly and the workaround here is super simple.

No, we do not need to pile up workarounds in a temporary situations, reverting to simple will not break Gitea.

**Comment by bendlas** [comment]
Hey Folks, Neither is Gitea dependent on being on notify, nor can't we override a quickfix later.

I'm sure it's sunny outside somewhere. Why not take a walk, touch grass and smell the flowers for half an hour?

**Pull request closed without merging**
