### PR TITLE
 dotnet: split sdk packages by platform 

### PR DESCRIPTION
**Pull request by corngood**
## Description of changes

The primary change here is to make `dotnet-sdk.packages` contain only the packages needed for the host/target systems.  This should help address #337030.  The other target packages are available in `dotnet-sdk.targetPackages.${rid}` should they be needed (e.g. for fetch-deps).

For VMR (source-built sdk/runtime), we can't currently cross-compile packages for the other RIDs, so we pass through the binary packages for the other RIDs.  Previously, the VMR `sdk.packages` only contained target packages for a single RID.  This means it should now be usable as a drop-in replacement for the same version of the binary SDK. 

There are some package fixes in here that give an idea of the sort of breaking changes this could cause.  Mostly it's just packages that were unnecessarily restoring for multiple RIDs.

Cc: @NixOS/dotnet 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
Result of `nixpkgs-review pr 343837` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>135 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>alttpr-opentracker</li>
    <li>am2rlauncher</li>
    <li>avalonia</li>
    <li>avalonia-ilspy</li>
    <li>azure-functions-core-tools</li>
    <li>beatsabermodmanager</li>
    <li>bicep</li>
    <li>blendfarm</li>
    <li>boogie</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>cavalier</li>
    <li>celeste64</li>
    <li>certdump</li>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>cyclonedx-cli</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>dependency-track</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-outdated</li>
    <li>dotnet-sdk</li>
    <li>dotnet-sdk_7</li>
    <li>dotnet-sdk_8</li>
    <li>dotnetCorePackages.dotnet_8.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_8.runtime</li>
    <li>dotnetCorePackages.dotnet_8.sdk</li>
    <li>dotnetCorePackages.dotnet_8.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_8.vmr</li>
    <li>dotnetCorePackages.dotnet_9.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_9.runtime</li>
    <li>dotnetCorePackages.dotnet_9.sdk</li>
    <li>dotnetCorePackages.dotnet_9.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_9.vmr</li>
    <li>dotnetCorePackages.sdk_6_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_3xx</li>
    <li>dotnetCorePackages.sdk_8_0_1xx</li>
    <li>dotnetCorePackages.sdk_8_0_3xx</li>
    <li>dotnetCorePackages.sdk_9_0</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>famistudio</li>
    <li>fantomas</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>garnet</li>
    <li>gh-gei</li>
    <li>git-credential-manager</li>
    <li>github-runner</li>
    <li>gitversion</li>
    <li>godot3-mono</li>
    <li>godot3-mono-debug-server</li>
    <li>godot3-mono-export-templates</li>
    <li>godot3-mono-headless</li>
    <li>godot3-mono-headless.dev</li>
    <li>godot3-mono-headless.man</li>
    <li>godot3-mono-server</li>
    <li>godot3-mono.dev</li>
    <li>godot3-mono.man</li>
    <li>ilspycmd</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>jetbrains.clion</li>
    <li>jetbrains.rider</li>
    <li>juniper</li>
    <li>kavita</li>
    <li>knossosnet</li>
    <li>kryptor</li>
    <li>libation</li>
    <li>lubelogger</li>
    <li>lumafly</li>
    <li>marksman</li>
    <li>mqttmultimeter</li>
    <li>msbuild</li>
    <li>naps2</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>networkminer</li>
    <li>nexusmods-app</li>
    <li>nexusmods-app-unfree</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>openutau</li>
    <li>osu-lazer</li>
    <li>pablodraw</li>
    <li>parabolic</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>ps3-disc-dumper</li>
    <li>pupdate</li>
    <li>python311Packages.asteroid-filterbanks</li>
    <li>python311Packages.asteroid-filterbanks.dist</li>
    <li>python311Packages.clr-loader</li>
    <li>python311Packages.clr-loader.dist</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.pythonnet</li>
    <li>python311Packages.pythonnet.dist</li>
    <li>python312Packages.asteroid-filterbanks</li>
    <li>python312Packages.asteroid-filterbanks.dist</li>
    <li>python312Packages.clr-loader</li>
    <li>python312Packages.clr-loader.dist</li>
    <li>python312Packages.pyannote-audio</li>
    <li>python312Packages.pyannote-audio.dist</li>
    <li>python312Packages.pythonnet</li>
    <li>python312Packages.pythonnet.dist</li>
    <li>recyclarr</li>
    <li>retrospy</li>
    <li>roslyn</li>
    <li>roslyn-ls</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>sonarr</li>
    <li>space-station-14-launcher</li>
    <li>tagger</li>
    <li>technitium-dns-server</li>
    <li>tone</li>
    <li>torrentstream</li>
    <li>vrcadvert</li>
    <li>wasabibackend</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
    <li>wiseunpacker</li>
    <li>xivlauncher</li>
  </ul>
</details>

**Comment by corngood** [comment]
Result of `nixpkgs-review` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>avalonia</li>
    <li>certdump</li>
    <li>pablodraw</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python312Packages.pyannote-audio</li>
    <li>python312Packages.pyannote-audio.dist</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
  </ul>
</details>
<details>
  <summary>78 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>avalonia-ilspy</li>
    <li>azure-functions-core-tools</li>
    <li>bicep</li>
    <li>blendfarm</li>
    <li>boogie</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>cyclonedx-cli</li>
    <li>dafny</li>
    <li>depotdownloader</li>
    <li>dotnet-outdated</li>
    <li>dotnet-sdk</li>
    <li>dotnet-sdk_7</li>
    <li>dotnet-sdk_8</li>
    <li>dotnetCorePackages.dotnet_8.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_8.runtime</li>
    <li>dotnetCorePackages.dotnet_8.sdk</li>
    <li>dotnetCorePackages.dotnet_8.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_8.vmr</li>
    <li>dotnetCorePackages.dotnet_9.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_9.runtime</li>
    <li>dotnetCorePackages.dotnet_9.sdk</li>
    <li>dotnetCorePackages.dotnet_9.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_9.vmr</li>
    <li>dotnetCorePackages.sdk_6_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_3xx</li>
    <li>dotnetCorePackages.sdk_8_0_1xx</li>
    <li>dotnetCorePackages.sdk_8_0_3xx</li>
    <li>dotnetCorePackages.sdk_9_0</li>
    <li>famistudio</li>
    <li>fantomas</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>garnet</li>
    <li>gh-gei</li>
    <li>git-credential-manager</li>
    <li>github-runner</li>
    <li>gitversion</li>
    <li>ilspycmd</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>juniper</li>
    <li>knossosnet</li>
    <li>kryptor</li>
    <li>libation</li>
    <li>lubelogger</li>
    <li>marksman</li>
    <li>msbuild</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>omnisharp-roslyn</li>
    <li>openutau</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>python311Packages.asteroid-filterbanks</li>
    <li>python311Packages.asteroid-filterbanks.dist</li>
    <li>python311Packages.clr-loader</li>
    <li>python311Packages.clr-loader.dist</li>
    <li>python311Packages.pythonnet</li>
    <li>python311Packages.pythonnet.dist</li>
    <li>python312Packages.asteroid-filterbanks</li>
    <li>python312Packages.asteroid-filterbanks.dist</li>
    <li>python312Packages.clr-loader</li>
    <li>python312Packages.clr-loader.dist</li>
    <li>python312Packages.pythonnet</li>
    <li>python312Packages.pythonnet.dist</li>
    <li>recyclarr</li>
    <li>roslyn</li>
    <li>roslyn-ls</li>
    <li>sonarr</li>
    <li>torrentstream</li>
    <li>vrcadvert</li>
    <li>wiseunpacker</li>
  </ul>
</details>

**Review by GGG-KILLER — APPROVED** [review]

**Review by konradmalik — APPROVED** [review]

**Review by konradmalik — APPROVED** [review]

**Comment by corngood** [comment]
Result of `nixpkgs-review pr 343837` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>135 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>alttpr-opentracker</li>
    <li>am2rlauncher</li>
    <li>avalonia</li>
    <li>avalonia-ilspy</li>
    <li>azure-functions-core-tools</li>
    <li>beatsabermodmanager</li>
    <li>bicep</li>
    <li>blendfarm</li>
    <li>boogie</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>cavalier</li>
    <li>celeste64</li>
    <li>certdump</li>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>cyclonedx-cli</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>dependency-track</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-outdated</li>
    <li>dotnet-sdk</li>
    <li>dotnet-sdk_7</li>
    <li>dotnet-sdk_8</li>
    <li>dotnetCorePackages.dotnet_8.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_8.runtime</li>
    <li>dotnetCorePackages.dotnet_8.sdk</li>
    <li>dotnetCorePackages.dotnet_8.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_8.vmr</li>
    <li>dotnetCorePackages.dotnet_9.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_9.runtime</li>
    <li>dotnetCorePackages.dotnet_9.sdk</li>
    <li>dotnetCorePackages.dotnet_9.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_9.vmr</li>
    <li>dotnetCorePackages.sdk_6_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_3xx</li>
    <li>dotnetCorePackages.sdk_8_0_1xx</li>
    <li>dotnetCorePackages.sdk_8_0_3xx</li>
    <li>dotnetCorePackages.sdk_9_0</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>famistudio</li>
    <li>fantomas</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>garnet</li>
    <li>gh-gei</li>
    <li>git-credential-manager</li>
    <li>github-runner</li>
    <li>gitversion</li>
    <li>godot3-mono</li>
    <li>godot3-mono-debug-server</li>
    <li>godot3-mono-export-templates</li>
    <li>godot3-mono-headless</li>
    <li>godot3-mono-headless.dev</li>
    <li>godot3-mono-headless.man</li>
    <li>godot3-mono-server</li>
    <li>godot3-mono.dev</li>
    <li>godot3-mono.man</li>
    <li>ilspycmd</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>jetbrains.clion</li>
    <li>jetbrains.rider</li>
    <li>juniper</li>
    <li>kavita</li>
    <li>knossosnet</li>
    <li>kryptor</li>
    <li>libation</li>
    <li>lubelogger</li>
    <li>lumafly</li>
    <li>marksman</li>
    <li>mqttmultimeter</li>
    <li>msbuild</li>
    <li>naps2</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>networkminer</li>
    <li>nexusmods-app</li>
    <li>nexusmods-app-unfree</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>openutau</li>
    <li>osu-lazer</li>
    <li>pablodraw</li>
    <li>parabolic</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>ps3-disc-dumper</li>
    <li>pupdate</li>
    <li>python311Packages.asteroid-filterbanks</li>
    <li>python311Packages.asteroid-filterbanks.dist</li>
    <li>python311Packages.clr-loader</li>
    <li>python311Packages.clr-loader.dist</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.pythonnet</li>
    <li>python311Packages.pythonnet.dist</li>
    <li>python312Packages.asteroid-filterbanks</li>
    <li>python312Packages.asteroid-filterbanks.dist</li>
    <li>python312Packages.clr-loader</li>
    <li>python312Packages.clr-loader.dist</li>
    <li>python312Packages.pyannote-audio</li>
    <li>python312Packages.pyannote-audio.dist</li>
    <li>python312Packages.pythonnet</li>
    <li>python312Packages.pythonnet.dist</li>
    <li>recyclarr</li>
    <li>retrospy</li>
    <li>roslyn</li>
    <li>roslyn-ls</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>sonarr</li>
    <li>space-station-14-launcher</li>
    <li>tagger</li>
    <li>technitium-dns-server</li>
    <li>tone</li>
    <li>torrentstream</li>
    <li>vrcadvert</li>
    <li>wasabibackend</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
    <li>wiseunpacker</li>
    <li>xivlauncher</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
I just tested ASF and it's plugin mechanism seems to still work like before.

**Pull request merged**
