### PR TITLE
waydroid: 1.4.2 -> 1.4.3; add update script, move to by-name, format, and other cleanup

### PR DESCRIPTION
**Pull request by adisbladis**
## Things done

Picking up https://github.com/NixOS/nixpkgs/pull/339882 which was closed by the original contributor.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adisbladis** [comment]
It's been a week with no review, so I'm going to merge this.
I guess you can see me as a reviewer since I didn't create the change :P

**Comment by CajuM** [comment]
> 1.4.3 doesn't work for me. I have to revert [waydroid/waydroid#1315](https://github.com/waydroid/waydroid/pull/1315). Does it work for you?

I had the same issue when I tried to update this package to 1.4.3 . It might be the lxc version we're using, some misplaced paths in /run on NixOS or the Waydroid devs did not properly write the lxc config file. Either way lxc won't bind-mount the wayland and pulse sockets. I tried to edit the lxc config file by hand and from what I recall there was an issue with relative paths?

**Comment by CajuM** [comment]
I think you should open an issue on https://github.com/waydroid/waydroid

**Comment by linsui** [comment]
Basically $XDG_RUNTIME_DIR works but /run/xdg doesn't work. I'll revert that commit for now so that waydroid in nixpkgs works.

**Pull request merged**
