### PR TITLE
bazel: 0.12.0 -> 0.13.0

### PR DESCRIPTION
**Pull request by uri-canva**
###### Motivation for this change

Update version.

Switch the existing bash hack with a patch that replaces all invocations of binaries assumed to be in the default bash path, /bin and /usr/bin with the absolute path to the binaries in the nix store.

Propagate `NIX_CFLAGS_COMPILE ` and `NIX_LDFLAGS` correctly to both the bootstrapping process and the bazel build definitions: both will clear the environment when invoking the cc and ld wrappers.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Duplicate of #40205

**Comment by uri-canva** [comment]
Oh cool, that wasn't there when I started working on this, let me rebase it.

**Comment by xeji** [comment]
Would be great if you and @rdnetto4 can merge your PRs into one.

**Comment by mboes** [comment]
What was wrong with the `customBash` hack? I fear your proposed new direction will be a lot harder to maintain by adding more work to upgrading Bazel to newer versions.

**Comment by uri-canva** [comment]
Other than that I'm not sure what's wrong with the `customBash` hack, it doesn't work when building `0.13.0` on NixOS, and I haven't looked into why and how to fix it because I needed a non-`customBash` approach anyway to make it work on darwin: Bazel uses `sandbox-exec` to execute actions on darwin, which disallows non-binaries used as interpreters in shebangs.

**Comment by uri-canva** [comment]
Not using the `customBash` hack is harder to maintain, but it's also using dependencies correctly: unrelated to the `customBash` see how the build is now forced to use the correct versions of `grep`, `sed`, etc, and the compiled binary references the correct paths for the tools it uses: this is hard to do with `PATH` manipulation because Bazel will drop environment variables to do its own sandboxing, and relies on certain tools existing in `/bin`, `/usr/bin`, or bash being able to find them without propagating `PATH`.

Note this also means the projects being built with Bazel after the hack is removed will have to configure the build correctly using `--action_env` and `use_default_shell_env=True`, as is being done for Bazel in the patch.

**Comment by mboes** [comment]
> It's true that the Bazel build does use sed and other tools, so there might be something I'm missing for customBash to be able to find them, maybe stdenv.shell already includes all tools available to nix derivations?

From what I can tell `sed`, `grep` and the like are only used in tests or other scripts not executed during build time of Bazel itself. I haven't tried running the tests, but for this reason, I'd be surprised if they work.

Now, Bazel might use `sed` from the user's `PATH` when building a user project, since `PATH` is not expunged. It might also use whatever `gcc` it finds on the path. Maybe not ideal, but that's a larger change to consider and not a blocker to upgrading to bazel-0.13.

> Builds with Bazel are already non-reproducible if you switch the installation method: Bazel installed with Nix will use binaries from the Nix store, including java and gcc, and Bazel installed from other package managers will use binaries installed in the system, whichever they might be.

Different kind of reproducibility. I guess I should have said "portability" instead. Ultimately, as a rule author, I don't want to have to write rules in one way when in Nixpkgs (which I can't detect reliably) and another elsewhere. As a developer, I don't want my users to have to pass extra flags on the command-line, or not, depending on their distribution. It's unclear to me whether that's still the case with your proposed changes. In any case, I submit that these are interesting changes but ought to be considered in a separate PR.

**Comment by uri-canva** [comment]
> I submit that these are interesting changes but ought to be considered in a separate PR.

Yeah absolutely, since there is a smaller change possible to upgrade the version that's what we should do first.

> Ultimately, as a rule author, I don't want to have to write rules in one way when in Nixpkgs (which I can't detect reliably) and another elsewhere.

I see, that makes sense. I was interested in using Nix under macOS, so it's a very different situation: if Bazel works exactly like installed with brew, as in refers to the shell path either as defined in the calling environment or as defined as bash default, and uses a lot of binaries from there, then it's very hard to achieve reproducible builds when using it.

---

Will close this PR and create a new one for darwin support once the upgrade has been merged on its own in #40205 or #40525.

**Pull request closed without merging**
