### PR TITLE
Revert "Revert "pythonPackages.nbxmpp: 4.0.0 → 4.0.1; gajim: 1.6.0 → 1.6.1""

### PR DESCRIPTION
**Pull request by vbgl**
Reverts NixOS/nixpkgs#211291

### CODE REVIEW

**Comment by vbgl** [comment]
Tested on nixos x86_64.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 211350` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>gajim</li>
    <li>python310Packages.nbxmpp</li>
    <li>python311Packages.nbxmpp</li>
  </ul>
</details>

**Comment by NickCao** [comment]
@ofborg build pythonPackages.nbxmpp gajim

**Comment by vbgl** [comment]
Thanks.

**Pull request merged**
