### PR TITLE
slstatus: update to unstable-2022-12-19

### PR DESCRIPTION
**Pull request by KAction**
Changes from unstable-2019-02-16 are mostly cleanup (comments, README,
compiler warnings).

maintainers: @oxzi

### CODE REVIEW

**Review by oxzi — APPROVED** [review]
Thanks for your PR. Works for me.

**Comment by KAction** [comment]
Ok to merge?

**Comment by KAction** [comment]
@happysalada Can you please merge this?

**Comment by happysalada** [comment]
Thanks !

**Pull request merged**
