### PR TITLE
sway: 1.1.1 -> 1.2-rc2

### PR DESCRIPTION
**Pull request by valebes**
###### Motivation for this change
Update 1.1.1 -> 1.2-rc2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by valebes** [comment]
Waiting for 93b9e73eea20ca4bc44491320cc822123f12cbd9

**Comment by alexarice** [comment]
I was under the impression that we were sticking to full releases for sway

**Comment by alexarice** [comment]
@primeos

**Comment by valebes** [comment]
Sorry, I've seen now.

**Comment by VlivesRaw** [comment]
Just a touch too early :D Sway 1.2 is released, maybe @valebes you can create a new PR?

**Comment by valebes** [comment]
@VlivesRaw After merge c1d74a12724dc040471bec25fd1a90997a18667f I'll take a look.

**Comment by primeos** [comment]
FYI: I've already created #67554 ;)

**Comment by valebes** [comment]
All right! :+1:

**Pull request closed without merging**
