### PR TITLE
crawl: add .desktop file and use high-res app icon

### PR DESCRIPTION
**Pull request by lightbulbjim**
###### Motivation for this change

The crawl source includes .desktop files but currently they are not
installed. This change installs them (with the executable path tweaked
for NixOS compatibility).

Also included in this change is a patch to use the included high-res app
icon instead of the default 32x32 icon. The default icon is very low res
and looks out of place beside other app icons.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lightbulbjim** [comment]
I've upstreamed the icon change but they only release every six months. Once the new version is released I'll remove the patch from nixpkgs, but in the meantime it would be nice to keep it.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Can you add the commit you upstreamed as a patch like?
```
patches = [
  (fetchpatch {
    url = "https://github.com/crawl/crawl/commit/2aa1166087e44e6585b26cedf1fe81b3f3ba547f.patch"
    sha256 = "0000000000000000000000000000000000000000000000000000";
  })
];
```

And remove it from the tree?

**Comment by lightbulbjim** [comment]
> Can you add the commit you upstreamed as a patch ... And remove it from the tree?

Good idea, it didn't even occur to me. Updated.

**Comment by worldofpeace** [comment]
Hash mismatch
```
 wanted: sha256:09ip3ppb81szn85l32zh3xiyp9kblcz8d0ngw83ilyr7p796m402
  got:    sha256:1jqrdv4wy18shg1fdabdb421232hg5micphkixcyzxd1lrmvadg0
```

Note that `fetchpatch` normalizes the generated patch, so if you for example retrieved the hash from
`nix-prefetch-url` it won't be correct.

**Comment by lightbulbjim** [comment]
> Note that `fetchpatch` normalizes the generated patch, so if you for example retrieved the hash from
> `nix-prefetch-url` it won't be correct.

I did use `nix-prefetch-url` to retrieve the hash.

The build succeeds for me with either `09ip3ppb81szn85l32zh3xiyp9kblcz8d0ngw83ilyr7p796m402` or `1jqrdv4wy18shg1fdabdb421232hg5micphkixcyzxd1lrmvadg0` set in `fetchpatch`. Not sure what's going on there. Other values do fail for me with a hash mismatch.

I guess I should use `1jqrdv4wy18shg1fdabdb421232hg5micphkixcyzxd1lrmvadg0`? Not sure why you're getting different results (or why both hashes work for me).

**Comment by lightbulbjim** [comment]
Finally got a chance to look at this. The tl;dr is that I updated the hash to `1jqrdv4wy18shg1fdabdb421232hg5micphkixcyzxd1lrmvadg0` and `nix-review` is now happy.

More context:

`nix-build` was happy with either hash. In fact, I've been building my system packages from a local branch with the "bad" hash for the past few days and it's been working fine. `nix-build` _does_ complain if I change the hash to some other value.

`nix-review`, on the other other hand, would only work with `1jqrdv4wy18shg1fdabdb421232hg5micphkixcyzxd1lrmvadg0`. Not sure what it's doing differently to `nix-build`; I'll have to look into that.

Compounding my testing was the fact that `nix-review wip` would fail to build the package every time with a "patch failed to apply" error. The only way I could get it to build was to commit my changes and use `nix-review rev`. Again, something I need to figure out as it took a while for me to realise that the error had nothing to do with the patch.

**Comment by worldofpeace** [comment]
For fixed-output derivations if the hash already matches a path in the store nix will skip the download and just use the existing path. Since you used `nix-prefetch-url` and used that hash I didn't get downloaded because the path already existed.

So changing the hash so that it no longer matches forces a rebuild, and then you get the mismatch because it wasn't correct.

I tend to do [Trust on first use](https://en.wikipedia.org/wiki/Trust_on_first_use) where you use a placeholder hash that for sure will be wrong
```
sha256 = "0000000000000000000000000000000000000000000000000000";
```

and then when the build fails with a hash mismatch you then substitute it with that hash
and assume it's correct.

I've done this locally and the hash used is correct
```
hash mismatch in fixed-output derivation '/nix/store/7spb1nsg7dj2bji2bgpai806vy4bmja4-2aa1166087e44e6585b26cedf1fe81b3f3ba547f.patch':
  wanted: sha256:0000000000000000000000000000000000000000000000000000
  got:    sha256:1jqrdv4wy18shg1fdabdb421232hg5micphkixcyzxd1lrmvadg0
```

##### more info at https://nixos.org/nixos/nix-pills/nix-store-paths.html

**Review by worldofpeace — APPROVED** [review]
Desktop item and icons look good.

**Comment by worldofpeace** [comment]
Thank you @lightbulbjim for fixing this.

If you have more questions about the hash issue, feel free to ask me.
There's also lots of people in #nixos (freenode) who'd also enjoy explaining this.

**Comment by lightbulbjim** [comment]
Thanks for merging and especially for the help. I appreciate it!

**Pull request merged**
