### PR TITLE
lowdown: 1.1.2 -> 1.2.0

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/kristapsdz/lowdown/releases/tag/VERSION_1_2_0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build nix lowdown

**Comment by trofi** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351454`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 184 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>attic-client</li>
    <li>attic-server</li>
    <li>bower2nix</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cached-nix-shell</li>
    <li>cachix (cachix.bin ,cachix.doc)</li>
    <li>certspotter</li>
    <li>clightning</li>
    <li>colmena</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>devenv</li>
    <li>disko</li>
    <li>dub-to-nix</li>
    <li>dydisnix</li>
    <li>fusionInventory</li>
    <li>harmonia</li>
    <li>hci</li>
    <li>hercules-ci-agent</li>
    <li>home-manager</li>
    <li>hydra</li>
    <li>libnixxml</li>
    <li>lix</li>
    <li>lix.debug</li>
    <li>lix.dev</li>
    <li>lix.devdoc</li>
    <li>lix.doc</li>
    <li>lix.man</li>
    <li>lixStatic</li>
    <li>lixStatic.dev</li>
    <li>lixVersions.lix_2_90</li>
    <li>lixVersions.lix_2_90.debug</li>
    <li>lixVersions.lix_2_90.dev</li>
    <li>lixVersions.lix_2_90.devdoc</li>
    <li>lixVersions.lix_2_90.doc</li>
    <li>lixVersions.lix_2_90.man</li>
    <li>lowdown (lowdown-unsandboxed)</li>
    <li>lowdown.dev (lowdown-unsandboxed.dev)</li>
    <li>lowdown.lib (lowdown-unsandboxed.lib)</li>
    <li>lowdown.man (lowdown-unsandboxed.man)</li>
    <li>lua51Packages.luarocks-nix</li>
    <li>lua52Packages.luarocks-nix</li>
    <li>lua53Packages.luarocks-nix</li>
    <li>lua54Packages.luarocks-nix</li>
    <li>luajitPackages.luarocks-nix</li>
    <li>luarocks-packages-updater</li>
    <li>luarocks-packages-updater.dist</li>
    <li>nil</li>
    <li>nim_lk</li>
    <li>niv (niv.bin ,niv.data)</li>
    <li>nix (nixVersions.latest)</li>
    <li>nix-binary-cache</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-du</li>
    <li>nix-eval-jobs</li>
    <li>nix-fast-build</li>
    <li>nix-fast-build.dist</li>
    <li>nix-index</li>
    <li>nix-init</li>
    <li>nix-inspect</li>
    <li>nix-pin</li>
    <li>nix-plugin-pijul</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-required-mounts</li>
    <li>nix-required-mounts.dist</li>
    <li>nix-serve</li>
    <li>nix-serve-ng</li>
    <li>nix-template</li>
    <li>nix-unit</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>nix-update.dist</li>
    <li>nix-visualize</li>
    <li>nix-visualize.dist</li>
    <li>nix-web</li>
    <li>nix.debug (nixVersions.latest.debug)</li>
    <li>nix.dev (nixVersions.latest.dev)</li>
    <li>nix.doc (nixVersions.latest.doc)</li>
    <li>nix.man (nixVersions.latest.man)</li>
    <li>nixStatic</li>
    <li>nixStatic.dev</li>
    <li>nixStatic.doc</li>
    <li>nixStatic.man</li>
    <li>nixVersions.git</li>
    <li>nixVersions.git.debug</li>
    <li>nixVersions.git.dev</li>
    <li>nixVersions.git.doc</li>
    <li>nixVersions.git.man</li>
    <li>nixVersions.minimum</li>
    <li>nixVersions.minimum.debug</li>
    <li>nixVersions.minimum.dev</li>
    <li>nixVersions.minimum.doc</li>
    <li>nixVersions.minimum.man</li>
    <li>nixVersions.nix_2_18</li>
    <li>nixVersions.nix_2_18.debug</li>
    <li>nixVersions.nix_2_18.dev</li>
    <li>nixVersions.nix_2_18.doc</li>
    <li>nixVersions.nix_2_18.man</li>
    <li>nixVersions.nix_2_19</li>
    <li>nixVersions.nix_2_19.debug</li>
    <li>nixVersions.nix_2_19.dev</li>
    <li>nixVersions.nix_2_19.doc</li>
    <li>nixVersions.nix_2_19.man</li>
    <li>nixVersions.nix_2_20</li>
    <li>nixVersions.nix_2_20.debug</li>
    <li>nixVersions.nix_2_20.dev</li>
    <li>nixVersions.nix_2_20.doc</li>
    <li>nixVersions.nix_2_20.man</li>
    <li>nixVersions.nix_2_21</li>
    <li>nixVersions.nix_2_21.debug</li>
    <li>nixVersions.nix_2_21.dev</li>
    <li>nixVersions.nix_2_21.doc</li>
    <li>nixVersions.nix_2_21.man</li>
    <li>nixVersions.nix_2_22</li>
    <li>nixVersions.nix_2_22.debug</li>
    <li>nixVersions.nix_2_22.dev</li>
    <li>nixVersions.nix_2_22.doc</li>
    <li>nixVersions.nix_2_22.man</li>
    <li>nixVersions.nix_2_23</li>
    <li>nixVersions.nix_2_23.debug</li>
    <li>nixVersions.nix_2_23.dev</li>
    <li>nixVersions.nix_2_23.doc</li>
    <li>nixVersions.nix_2_23.man</li>
    <li>nixci</li>
    <li>nixd</li>
    <li>nixos-anywhere</li>
    <li>nixos-generators</li>
    <li>nixos-install</li>
    <li>nixos-option</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixpkgs-hammering</li>
    <li>nixpkgs-manual</li>
    <li>nixpkgs-review</li>
    <li>nixpkgs-review.dist</li>
    <li>nixt</li>
    <li>nixt.dev</li>
    <li>nixtract</li>
    <li>node2nix</li>
    <li>npins</li>
    <li>nuget-to-nix</li>
    <li>nurl</li>
    <li>nvfetcher</li>
    <li>outline</li>
    <li>prefetch-yarn-deps</li>
    <li>python311Packages.nix-kernel</li>
    <li>python311Packages.nix-kernel.dist</li>
    <li>python311Packages.nixpkgs</li>
    <li>python311Packages.nixpkgs.dist</li>
    <li>python311Packages.pythonix</li>
    <li>python312Packages.nix-kernel</li>
    <li>python312Packages.nix-kernel.dist</li>
    <li>python312Packages.nixpkgs</li>
    <li>python312Packages.nixpkgs.dist</li>
    <li>python312Packages.pythonix</li>
    <li>sbomnix</li>
    <li>sbomnix.dist</li>
    <li>sonarr</li>
    <li>swiftPackages.swiftpm2nix</li>
    <li>terranix</li>
    <li>typescript-language-server</li>
    <li>update-nix-fetchgit</li>
    <li>update-python-libraries</li>
    <li>vimPluginsUpdater</li>
    <li>vulnix</li>
    <li>vulnix.dist</li>
    <li>vulnix.doc</li>
    <li>vulnix.man</li>
    <li>wp4nix</li>
    <li>yarn2nix</li>
    <li>zon2nix</li>
  </ul>
</details>

**Review by sternenseemann — APPROVED** [review]
looks good if darwin is okay

**Comment by afh** [comment]
Successfully built and tested on `aarch64-darwin`, not sure if my machine is able to finish nixpkgs-review before it melts…

**Review by afh — APPROVED** [review]
Thanks for this, @trofi, super helpful looking forward to seeing this merged 🙂

**Pull request merged**
