### PR TITLE
perl-packages: stdenv.lib -> lib

### PR DESCRIPTION
**Pull request by Profpatsch**
The library does not depend on stdenv, that `stdenv` exposes `lib` is
an artifact of the ancient origins of nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build perlPackages

**Review by siraben — APPROVED** [review]
LGTM. No more occurrences of `stdenv.lib`.

**Review by alyssais — APPROVED** [review]
LGTM assuming OfBorg finds it to be rebuild-0.

**Comment by Profpatsch** [comment]
Everything green, 0 rebuilds, except the darwin build, which is afaik still broken in ofborg.

**Comment by stigtsp** [comment]
Hi, some notes:
- `maintainers/scripts/nix-generate-from-cpan.pl` needs to be updated
- A bulk update of perlPackages is in staging-next https://github.com/NixOS/nixpkgs/pull/108423

**Pull request merged**
