### PR TITLE
staging-next 2022-04-23

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: [nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy](https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy)
- constitutents: [hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents](https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents)
- jobset: [hydra.nixos.org/jobset/nixpkgs/staging-next](https://hydra.nixos.org/jobset/nixpkgs/staging-next)
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/169172

### CODE REVIEW

**Comment by vcunat** [comment]
Somehow we now manage to iterate staging* faster.  Hydra is being idle now again.  That's nice.

**Comment by tpwrules** [comment]
I am able to cross-compile my bootstrap aarch64 installer again. Seems like the basic cross stuff is back in good shape. Thanks for the hard work!

**Review by ttuegel — APPROVED** [review]

**Comment by risicle** [comment]
:point_up: Fixing my own screwup

**Comment by Madouura** [comment]
Would like to see these merged into master.
- #166992
- #170121

**Comment by NickCao** [comment]
> Would like to see these merged into master as part of this.
> 
>     * [gcc: 11.2.0 -> 11.3.0 #170121](https://github.com/NixOS/nixpkgs/pull/170121)

We are too late for the party, just wait for the next staging-next cycle!

**Comment by vcunat** [comment]
Yes.  Actually, for the stuff built on Hydra as part of _this_ iteration, also the systemd rebuild is missing (77a189e066a839).

It was merged much later than expected, so I deferred it to the next one.  As I didn't want to juggle reverts, I pointed Hydra to a new branch before that merge (`staging-next-2022-04-23`).  I thought it would be very fast, but unfortunately Hydra's speed for aarch64-linux is a fraction of the usual, and moreover the whole farm was out for a day or two.

**Comment by vcunat** [comment]
To be clear, this was merged... basically.   That systemd change is missing in this iteration.

**Pull request closed without merging**
