### PR TITLE
{openlp,python3Packages.sqlalchemy-migrate,python3Packages.tempita}: drop

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

https://github.com/NixOS/nixpkgs/issues/326513

cc @jorsn

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mweinelt — APPROVED** [review]

**Comment by Sigmanificient** [comment]
- https://github.com/NixOS/nixpkgs/issues/290642

**Review by natsukium — APPROVED** [review]
Let's wait a week for a response.

**Review by anthonyroussel — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
There is an open PR for openlp https://github.com/NixOS/nixpkgs/pull/314882

**Comment by emilazy** [comment]
I’m sorry for missing that! I’ve dropped the commit to remove the maintainers entry as it’s clearly not appropriate; I just saw that @jorsn had not made any commits since 2020 and assumed there had been no work on it. I’ve also reworded the removal message.

I think that it be okay to merge this PR in the interim, with no prejudice against adding OpenLP back with the update PR. The package doesn’t build at all right now due to the insecure `qtwebkit` dependency and incompatibilities with Python 3.12 and SQLAlchemy 2, and as it seems like the maintainer doesn’t use the package and nobody else has stepped up to help with it, I’m unsure if there is enough interest to get the update over the finish line and sustainably maintain this package.

**Comment by jorsn** [comment]
@SuperSandro2000 thank you for pointing to my PR!
@emilazy Alright, I support that in principle, and thank you for not removing me as a maintainer :) However, in this PR, it is not entirely removed, but rather replaced by an error message stating it is removed. This sounds like a permanent thing, and I propose to add to the error message that a package for OpenLP-3 is being worked on – maybe even with the PR number (https://github.com/NixOS/nixpkgs/pull/314882).  I think we can get the update for openlp, because Cyber_Raven offered help with maintenance [in the forum](https://discourse.nixos.org/t/openlp-update-to-3-1-2-looking-for-reviewers-and-co-maintainers/46034). I was only too busy in the last two weeks to give starting instructions and update my PR.

**Comment by emilazy** [comment]
> thank you for not removing me as a maintainer :)

Sorry again about that! I checked the commit log and your most recent GitHub activity, but I should have searched the tracker too…

> However, in this PR, it is not entirely removed, but rather replaced by an error message stating it is removed. This sounds like a permanent thing, and I propose to add to the error message that a package for OpenLP-3 is being worked on – maybe even with the PR number (#314882). I think we can get the update for openlp, because Cyber_Raven offered help with maintenance [in the forum](https://discourse.nixos.org/t/openlp-update-to-3-1-2-looking-for-reviewers-and-co-maintainers/46034). I was only too busy in the last two weeks to give starting instructions and update my PR.

That sounds reasonable to me. I’ve pushed a change that hopefully sounds softer and links to the PR with a call for help; we can always adjust it later if necessary.

Do you know if upstream is planning on supporting Qt 6? FOSS support for Qt 5 is ending next year, so that might be a problem down the line.

**Comment by jorsn** [comment]
> Do you know if upstream is planning on supporting Qt 6? FOSS support for Qt 5 is ending next year, so that might be a problem down the line.

I found no information on this and asked in the forum: https://discuss.openlp.org/d/6878-qt6-support

**Pull request merged**
