### PR TITLE
bind: 9.12.4-P1 -> 9.14.2

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

9.12 is EOL as of May 2019.

9.14.2 release notes (which appear to extend those for 9.14.1):

https://ftp.isc.org/isc/bind9/9.14.2/RELEASE-NOTES-bind-9.14.2.html

Please check the security fixes and prioritize this as appropriate.

NixOS tests should be checked of course :).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg test bind
@GrahamcOfBorg test acme
@GrahamcOfBorg test nsd
@GrahamcOfBorg bind
@GrahamcOfBorg dnsperf
@GrahamcOfBorg nmapsi4
@GrahamcOfBorg sssd
@GrahamcOfBorg testssl
@GrahamcOfBorg twa

**Review by peti — APPROVED** [review]
:+1:

**Comment by vcunat** [comment]
This is in nixos-unstable now.  The darwin problem from this PR was trivial to fix in #62882, but [the test](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.bind.x86_64-linux) is broken, most likely due to this PR as well.  Any idea what's wrong?

**Comment by m1cr0man** [comment]
Encountered the issue of bind.service not starting today. Nothing helpful from systemd logs, as the command to generate the rndc.key is piped to /dev/null on stderr.

Removing that, I saw the following error:
```bash
# /nix/store/hjz9av8c209pm0nirbim1ylpjfpmdyjl-bind-9.14.2/sbin/rndc-confgen -r /dev/urandom -c /etc/bind/rndc.key -u named -a -A hmac
rndc-confgen: The -r option has been deprecated.
```

Removing the `-r` flag fixes the command, as the deprecation is hard. I will rebuild and test, and push a PR if it all goes well.

**Pull request merged**
