### PR TITLE
cairo: 1.16.0 -> 1.17.4

### PR DESCRIPTION
**Pull request by alyssais**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
This is technically an unstable release but I guess it makes sense to bump this since 1.16 is buggy. It would allow us to close https://github.com/NixOS/nixpkgs/pull/127120

Some interesting changes: most importantly, Meson port. But we can handle that later too.

- https://cairographics.org/news/cairo-1.17.4/
- https://cairographics.org/news/cairo-1.17.2/

**Comment by alyssais** [comment]
> This is technically an unstable release

Where's that documented?

**Comment by jtojnar** [comment]
On https://cairographics.org/news/, odd-minor versions are called snapshot.

**Comment by alyssais** [comment]
Wow, that is not obvious. :(

In that case I think it's probably better to just keep patching.

**Pull request closed without merging**
