### PR TITLE
nixos/drbd: fix syntax for etc config file and systemd service

### PR DESCRIPTION
**Pull request by jslight90**
###### Motivation for this change

Fix typo that causes DRBD module to raise an error when enabled.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — APPROVED** [review]
Do you use this module? I wonder how long this has been broken for... Any interest in writing a NixOS test?

**Comment by jslight90** [comment]
> Do you use this module? I wonder how long this has been broken for... Any interest in writing a NixOS test?

I just started trying to use it for an HA SAN.  There are some quirks to the pkg too.  Version 8 is not compatible with Linux kernel 5.x; I had to set `boot.kernelPackages = pkgs.linuxPackages_4_19`.  I tried to compile version 9 with nix, but it's going to take more work; the build stage looks for the kernel src directory, which isn't in the nix-store.

**Comment by jslight90** [comment]
It looks like there are more things broken with this than I first thought.  The systemd service is not configured correctly and calls the `ExecStop` command immediately after running the start script.

**Comment by aanderse** [comment]
I don't know if would be able find some time dig into this. My experience with `drbd` isn't that advanced, and isn't on NixOS at all. Are you considering digging deeper into this?

**Comment by jslight90** [comment]
The second commit I just made fixes the systemd service.  I might try to work on getting version 9 to compile (there are some nice new features), but I think this pull request works to fix version 8 for now.

**Comment by aanderse** [comment]
Thanks again for your work on this @jslight90. Unfortunately I still haven't found time to test this out... but really the module seems pretty broken so I don't think this PR has any possibility to make things worse :laughing: From simple inspection of the change everything makes sense, so I'll go ahead and merge this if you're good with that... yes?

**Comment by jslight90** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/119904.

**Pull request closed without merging**
