### PR TITLE
lib.meta.licensesSpdx: mapping from SPDX ID to compatible licenses

### PR DESCRIPTION
**Pull request by mibmo**
## Description of changes

Adds a mapping from SPDX IDs to the licenses defined in `lib.licenses`, available in `lib.licenses-spdx`.

I've needed this several times, so figured I'd add it to the lib. Do let me know if this is appropriate! :)

This is my first non-package contribution to Nix, so of course any and all feedback is welcome! :) (although hopefully there isn't much to say about such a simple change)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by infinisil** [comment]
Would the [recently-merged](https://github.com/NixOS/nixpkgs/pull/149990) [`getLicenseFromSpdxIdOr`](https://nixos.org/manual/nixpkgs/unstable/#function-library-lib.meta.getLicenseFromSpdxIdOr) by @ShamrockLee already work for you too?

**Comment by mibmo** [comment]
> Would the [recently-merged](https://github.com/NixOS/nixpkgs/pull/149990) [`getLicenseFromSpdxIdOr`](https://nixos.org/manual/nixpkgs/unstable/#function-library-lib.meta.getLicenseFromSpdxIdOr) by @ShamrockLee already work for you too?

Not sure how I missed that, but it's super useful! It'll work for the current PR I'm working on that needed this, so I'm perfectly fine with closing, although I do think it's useful to expose nonetheless :) But perhaps the `spdxLicenses` variable from the mentioned PR should just be exposed instead? It'd also make the getLicenseFromSpdxId{,Or} implementations trivial. I'd be happy to make such a PR. :)

**Comment by ShamrockLee** [comment]
If we could go back in time, I might prefer `lib.licenses-spdx` over the function.

@infinisil Is there an idiomatic approach in Nixpkgs when referencing an attribute set mapping?

**Comment by mibmo** [comment]
> If we could go back in time, I might prefer `lib.licenses-spdx` over the function.
> 
> @infinisil Is there an idiomatic approach in Nixpkgs when referencing an attribute set mapping?

Honestly I think they both have their uses. What do you think about changing this to something like `lib.meta.spdxLicenses` and basing the `getLicenseFromSpdx{,Or}` functions on it?

I doubt it really matters for a function like this (simple task; so few licenses; and afaik the thunk should be cached anyway).... but does the implementation matter much? I'm not sure which of the two implementations are more performant here — and regardless it seems like premature optimization, but nix isn't exactly known to be performant, so better safe than sorry?

```nix
# getLicenseFromSpdxIdOr
lib.mapAttrs
  (id: ls: assert lib.length ls == 1; builtins.head ls)
  # why the groupBy? when would there be duplicate licenses? (if this is a general concern, maybe it should be added as an assert to licenses itself?)
  (lib.groupBy
    (l: lib.toLower l.spdxId)
    (lib.filter (l: l ? spdxId)
      (lib.attrValues lib.licenses)))

# this PR
lib.attrsets.mapAttrs'
  (_key: license: {
    name = license.spdxId;
    value = license;
  })
  (lib.attrsets.filterAttrs (_key: license: license ? spdxId) lib.licenses)
```

Regardless, I'll rework this PR to what I mentioned, if anything just to experiment a bit! :)

**Comment by mibmo** [comment]
@ShamrockLee check out this version :) I think this is significantly better.

Not sure if it's worth exposing `licensesSpdxLowercase`, but ... probably not!

**Comment by infinisil** [comment]
> Why the groupBy? when would there be duplicate licenses? (if this is a general concern, maybe it should be added as an assert to licenses itself?)

Nice, that's a good idea!

**Comment by ShamrockLee** [comment]
> Not sure if it's worth exposing `licensesSpdxLowercase`, but ... probably not!

This reminds me that we deliberately eliminate case differences during SPDX ID matching in `getLicensesFromSpdxIdOr`.

A function like `getLicensesFromSpdxIdOr` seems to be a more flexible and elegant solution than the exposure of `spdxIdLowercase` or something like that.

**Comment by infinisil** [comment]
Tbh we shouldn't add symbols/functions when other functions already work, but in this case I do agree with both of you that just exposing the SPDX ID mapping would've been the better design from the start, so I think it's fine :)

I took the liberty to push some suggestions directly, I hope you don't mind! Let me know if they look good, let's merge :rocket:

**Comment by infinisil** [comment]
> A function like `getLicensesFromSpdxIdOr` seems to be a more flexible and elegant solution than the exposure of `spdxIdLowercase` or something like that.

Oh only just saw this now. I do wonder about that, because I'm now thinking that we could have a function like `lib.attrsets.{get,has}AttrCaseInsensitive`, which would be way more composable. It could even be efficient if the attribute set was the first argument.

**Comment by infinisil** [comment]
> > Why the groupBy? when would there be duplicate licenses? (if this is a general concern, maybe it should be added as an assert to licenses itself?)
> 
> Nice, that's a good idea!

More sidenotes: The list of licenses should ideally be automatically generated from the SPDX list directly somehow, and regularly updated, such that we don't even have to worry about that, and always have all the licenses available.

**Comment by mibmo** [comment]
> Oh only just saw this now. I do wonder about that, because I'm now thinking that we could have a function like `lib.attrsets.{get,has}AttrCaseInsensitive`, which would be way more composable. The attribute set would have to be the first argument to enable it to be efficient though.

I'm very much in favor of this, but wouldn't it almost be better to integrate it into Nix(CPP) itself?

> - Expose `lib.licensesSpdx`
oh, crap. Did I forgot to actually make it usable? .... either way, thanks for the cleanup! I don't know if there's anything left to do or discuss, other than perhaps for other people to review it, but I'll take the PR out of draft mode nonetheless. :)

**Comment by infinisil** [comment]
> I'm very much in favor of this, but wouldn't it almost be better to integrate it into Nix(CPP) itself? I'd venture to guess it fits the bill for a `builtin`.

I think in general we only need builtins if a non-builtin would be too inefficient, which I don't think is the case here :)



> oh, crap. Did I forgot to actually make it usable?

Nah, it was just only usable as `lib.meta.licensesSpdx` before, but it's standard practice to expose most `lib` functions under `lib.*` as well

**Pull request merged**
