### PR TITLE
plan9port: 2019-02-25 -> 2020-01-08

### PR DESCRIPTION
**Pull request by eraserhd**
###### Motivation for this change

Fixes and some minor new features.

Note this is the newest version that supports Darwin 10.12; the next
commit removes that support.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
  - [X] osxsnarf
  - [X] tmuxPlugins.plumb
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
  Lost the information, but something like 4000 bytes difference
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @AndersonTorres @bbarker @ftrvxmtrx @kovirobi

### CODE REVIEW

**Comment by bhipple** [comment]
Looks like it doesn't support aarch64 either; let's mark `meta.platforms` with linux and darwin only?

**Comment by eraserhd** [comment]
It is supposed to be portable -- for some definition of portable.  I removed aarch64-linux explicitly.

**Comment by KoviRobi** [comment]
If we use at least https://github.com/9fans/plan9port/commit/0237dec768a4ee36ae9e18ce8566d2c999d78410 then it might compile on aarch64? (https://github.com/9fans/plan9port/issues/363)

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 84920` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
<br>- plan9port
<br>- tmuxPlugins.plumb
</details>

**Pull request merged**
