### PR TITLE
Emacs `site-lisp` subdirectory support

### PR DESCRIPTION
**Pull request by the-kenny**
###### Motivation for this change

This pull request enhances our `site-lisp.el` which is loaded by Emacs on startup. In addition to adding a bit of documentation it now adds subdirectories of the `site-lisp` directory to `load-path`, allowing loading of libraries like `mu4e`.

@mekeor: Could you please try this branch and see if it works for you?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mekeor** [comment]
@the-kenny In this commit https://github.com/NixOS/nixpkgs/pull/33416/commits/68e02e74aadb79d3772d7747d1fcd31526006795 why did you remove `format`? What does that do?

**Comment by the-kenny** [comment]
@mekeor I accidentally added this empty and unused `let` binding in 6fc2c699a89bf04a6b2adf6f6f76912917057d9a. I can squash both commits or rewrite them without the `format` hunk if you want me to :)

**Comment by the-kenny** [comment]
@mekeor Just force-pushed rebased commits without the `format` thingy.

**Comment by the-kenny** [comment]
@GrahamcOfBorg build emacs mu

**Comment by matthewbauer** [comment]
@the-kenny Does this look ready to go? Hoping to get this in by 18.03...

**Comment by the-kenny** [comment]
@matthewbauer absolutely! :)

**Review by matthewbauer — APPROVED** [review]

**Pull request merged**
