### PR TITLE
cargo-limit: 0.0.5 -> 0.0.6, shellhub-agent: 0.5.1 -> 0.5.2 

### PR DESCRIPTION
**Pull request by otavio**
###### Motivation for this change

I've upgraded those two packages which I am the maintainer.

 - shellhub-agent
 - cargo-limit

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113847` at f2d739f6 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/d2e590879f1e9a028df458d70ede17c6">cargo-limit</a></li></li>
    <li><a href="https://gist.github.com/4eeac6fddf2738d9c7fa003eb6c8ac62">shellhub-agent</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>error: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-flags-array.md">no-flags-array</a>

`buildFlagsArray` is only intended to be used in Bash, not as a Nix attribute.

Near pkgs/applications/networking/shellhub-agent/default.nix:23:3:
```
   |
23 |   buildFlagsArray = [ "-ldflags=-s -w -X main.AgentVersion=v${version}" ];
   |   ^
```
</li>
  </ul>
</details>

**Comment by otavio** [comment]
I looked at the proposed suggestion to avoid using `buildFlagsArray` however, I did not find an alternative. Looking at similar packages, which also use Go `ldflags` build options, they do the same.

**Comment by rmcgibbo** [comment]
> I looked at the proposed suggestion to avoid using buildFlagsArray however, I did not find an alternative. Looking at similar packages, which also use Go ldflags build options, they do the same.

Yes, my understanding is also that there's not a good fix for this for golang yet, other than perhaps using `buildFlags` rather than `buildFlagsArray`. Sorry for the non-actionable noise with the bot.

**Comment by SuperSandro2000** [comment]
> > I looked at the proposed suggestion to avoid using buildFlagsArray however, I did not find an alternative. Looking at similar packages, which also use Go ldflags build options, they do the same.
> 
> Yes, my understanding is also that there's not a good fix for this for golang yet, other than perhaps using `buildFlags` rather than `buildFlagsArray`. Sorry for the non-actionable noise with the bot.

The test should be adapted to follow the exact examples here https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/go.section.md#buildflagsarray-and-buildflags-ex-gobuildflags-noarray

**Comment by otavio** [comment]
Is there anything pending before merging this?

**Pull request merged**
