### PR TITLE
asciiquarium: init at 1.1

### PR DESCRIPTION
**Pull request by utdemir**
###### Motivation for this change

It's a cool terminal animation. 

`asciiquarium` is a simple perl script which doesn't require anything to build, just putting `perl` and `Term::Animation` to the `PATH` looks enough.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
Awesome package! Here's some suggested changes:

```diff
diff --git a/pkgs/applications/misc/asciiquarium/default.nix b/pkgs/applications/misc/asciiquarium/default.nix
index 52af1ff0234..912f18890b5 100644
--- a/pkgs/applications/misc/asciiquarium/default.nix
+++ b/pkgs/applications/misc/asciiquarium/default.nix
@@ -5,19 +5,18 @@ in stdenv.mkDerivation {
   name = "asciiquarium-${version}";
   src = fetchurl {
     url = "https://robobunny.com/projects/asciiquarium/asciiquarium_${version}.tar.gz";
-    sha256 = "sha256:0qfkr5b7sxzi973nh0h84blz2crvmf28jkkgaj3mxrr56mhwc20v";
+    sha256 = "0qfkr5b7sxzi973nh0h84blz2crvmf28jkkgaj3mxrr56mhwc20v";
   };

-  buildInputs = [ makeWrapper ];
+  nativeBuildInputs = [ makeWrapper ];
+  buildInputs = [ perlPackages.perl ];

-  phases = "unpackPhase installPhase";
   installPhase = ''
     mkdir -p $out/bin
     cp asciiquarium $out/bin
     chmod +x $out/bin/asciiquarium
     wrapProgram $out/bin/asciiquarium \
-      --prefix PATH : ${perlPackages.perl}/bin/path \
-      --prefix PERL5LIB : ${perlPackages.makeFullPerlPath [ perlPackages.TermAnimation ] }
+      --set PERL5LIB ${perlPackages.makeFullPerlPath [ perlPackages.TermAnimation ] }
   '';

   meta = with stdenv.lib; {
```

Short explanations:
- "sha256:" isn't needed
- Because `makeWrapper` is called at build time, it should be in nativeBuildInputs (for cross compilation)
- In nixpkgs, we usually patch shebangs directly instead of setting PATH, and this even happens automatically if you use standard phases (by not setting `phases` explicitly) and add `perl` to `buildInputs`. The package wouldn't work without this because I had a perl in $PATH already. This fixes it.
- I `--set` `PERL5LIB` because there's no point in prefixing it

**Comment by utdemir** [comment]
@Infinisil Thank you very much for your suggestions and explanations, I really appreciate it! 

Especially the `patchShebangs` phase. That looks really useful.

**Comment by Infinisil** [comment]
Awesome, now just squash the commits into one and I can merge this

**Comment by utdemir** [comment]
Done, thanks!

**Pull request merged**
