### PR TITLE
unifi:Update download location

### PR DESCRIPTION
**Pull request by Baughn**
The old link's broken.

### CODE REVIEW

**Comment by wkennington** [comment]
Any reason? Does the old link no longer work?

**Comment by bjornfor** [comment]
Pleas update commit message: "<package>: <what>"

**Comment by Baughn** [comment]
Yes, the old link no longer works.

...Github doesn't seem to give me a way of changing the commit message.

**Comment by jagajaga** [comment]
You need to do 
```
git rebase -i HEAD~1
# do reword there
git push --force <your remote> <your branch>
```

**Comment by Baughn** [comment]
Well, I made the patch by using the edit button on github...

..I'll fix up the commit title once I've got a working dev environment again.

**Comment by Baughn** [comment]
Fix'd.

**Comment by cillianderoiste** [comment]
Thanks @Baughn, I'll cherry-pick it to 15.09.

**Comment by cillianderoiste** [comment]
I had to upgrade the version on 15.09 too because the old version is no longer available.

**Pull request merged**
