### PR TITLE
tcl: fix #243831

### LINKED ISSUE #243831: tcl: can't find tzdata
### Describe the bug

On current NixOs unstable:

```console
> nix run nixpkgs#eltclsh                                   

              eltclsh1.18 - Copyright (C) 2001-2020 LAAS-CNRS

eltclsh > set t [clock scan {2004-10-30 05:00:00} \
-format {%Y-%m-%d %H:%M:%S} \
-timezone :America/New_York]

time zone ":America/New_York" not found
```

### Steps To Reproduce

As above

### Expected behavior

Correct handling of timezone

### Additional context

Tcl can either use system tzdata from a list of directories, or install its own. Installation of  Tcl’s own tzdata is disabled in nixpkgs via commit 02bae3913260296447fe80ffb44276f48239e317, as NixOs installs its own tzdata.

However, `clock.tcl` [uses](https://core.tcl-lang.org/tcl/file?name=library/clock.tcl) a fixed list of paths to look for tzdata:

```tcl
    # Paths at which binary time zone data for the Olson libraries are known
    # to reside on various operating systems

    variable ZoneinfoPaths {}
    foreach path {
	/usr/share/zoneinfo
	/usr/share/lib/zoneinfo
	/usr/lib/zoneinfo
	/usr/local/etc/zoneinfo
    } {
	if { [file isdirectory $path] } {
	    lappend ZoneinfoPaths $path
	}
    }
```

This list, unsurprisingly, does not include `${pkgs.tzdata}/share/zoneinfo`. So on NixOs clock does not see any tzdata, and on non-NixOs it sees tzdata from outside the store, which may be a reproducibility issue.

### Notify maintainers

@siraben (I don’t see any maintainers listed, mentioning author of last version bump)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"                     
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.2, NixOS, 23.11 (Tapir), 23.11.20230713.e74e684`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos, nixos-hardware"`
 - channels(akho): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by akho**
###### Description of changes

Add a dependency on tzdata, use tzdata's zoneinfo in clock.tcl. Remove other paths clock.tcl may try to use for zoneinfo to avoid non-store dependency.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Closes #243831

### CODE REVIEW

**Comment by tjni** [comment]
Thank you for tackling this!

1. A personal opinion that this would be better as a patch file. The patch can have more surrounding context and in some cases can warn us if upstream changes their code in such a way that requires updating it.

2. How difficult would it be to write a test that can check the output from the repro?

**Comment by akho** [comment]
> Thank you for tackling this!
> 
>     1. A personal opinion that this would be better as a patch file. The patch can have more surrounding context and in some cases can warn us if upstream changes their code in such a way that requires updating it.

I thought about this a bit and looked at prior art (`rg zoneinfo pkgs/`). It seems that both approaches are present in Nixpkgs, and I found it easier to use `substituteInPlace` once, rather than having a patch with `@tzdata@` or smth and then a `substituteAll` on top.

I may be wrong though.

> 
>     2. How difficult would it be to write a test that can check the output from the repro?

I don’t have experience writing tests in Nixpkgs. Shouldn’t be hard though. Is there a helpful blog post I could read to learn?

**Comment by tjni** [comment]
> I found it easier to use substituteInPlace once, rather than having a patch with @tzdata@ or smth and then a substituteAll on top.

I agree it's easier and the patch is just my preference. If we add a test, then I don't mind keeping this as-is.

> Is there a helpful blog post I could read to learn?

There are some sections on testing in the nixpkgs documentation. I do not have a lot of experience myself, but I think inspiration can be taken from https://nixos.org/manual/nixpkgs/stable/#tester-testVersion.

**Comment by akho** [comment]
> There are some sections on testing in the nixpkgs documentation. I do not have a lot of experience myself, but I think inspiration can be taken from https://nixos.org/manual/nixpkgs/stable/#tester-testVersion.

That was interesting, but not exactly pertinent.

I’ve added a test via `installCheckPhase`. Interestingly, adding `make test` in `checkPhase` to run Tcl’s own test suite (which includes `clock.test`) does not help, as `make test` sees Tcl’s own tzdata regardless of configure flags. So we need to check the final, installed version.

**Comment by akho** [comment]
Changed the test to run in `passthru.tests`, instead of `installCheck`, as recommended in the Nixpkgs manual.

**Comment by asymmetric** [comment]
@ofborg build tcl

**Comment by tjni** [comment]
I apologize for not coming back to this sooner. The code and test looks good! I built it locally on my aarch64-darwin machine and also verified that the test with the old build and passes with the new build. I am sorry I don't have committer rights at the moment so I can't help you actually merge yet.

The last thing to do is to rebase this onto the staging branch, because the number of rebuilds are > 500. The instructions for that are [here](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging). I've messed it up before, so I always set the PR status to draft while I do it. This does mean that once it is merged, it could take a week or two before it reaches master (I'm sorry about that too).

**Review by tjni — APPROVED** [review]
LGTM (contingent on merging this into the staging branch)

**Comment by akho** [comment]
> I apologize for not coming back to this sooner.

No problem, thank you!

> The last thing to do is to rebase this onto the staging branch, because the number of rebuilds are > 500. The instructions for that are [here](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging). I've messed it up before, so I always set the PR status to draft while I do it. This does mean that once it is merged, it could take a week or two before it reaches master (I'm sorry about that too).

I did the steps in the instruction and can only hope I haven’t messed up too badly…

**Pull request merged**
