### PR TITLE
python310Packages.pysvn: 1.9.12 -> 1.9.18

### LINKED ISSUE #175227: `pythonImportsCheck` doesn't work with nonstandard `installPhase`
It relies on the `installPhase` doing
```sh
export PYTHONPATH="$out/@pythonSitePackages@:$PYTHONPATH"
```
I noticed this while trying to use `pythonImportsCheck` for `python3Packages.pysvn`.

cc @FRidh @jonringer @mweinelt

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by freezeboy — APPROVED** [review]
LGTM

**Review by SuperSandro2000 — COMMENTED** [review]
otherwise LGTM

**Comment by dotlambda** [comment]
Does openldap not break for anybody else?

**Comment by SuperSandro2000** [comment]
@ofborg build openldap

**Comment by dotlambda** [comment]
I still get
```
/nix/store/2b99rpx8zwdjjqkrvk7kqgn9mxhiidjy-binutils-2.38/bin/ld: cannot find slapd-common.o: No such file or directory
```
Weird.

**Comment by dotlambda** [comment]
> I still get
> 
> ```
> /nix/store/2b99rpx8zwdjjqkrvk7kqgn9mxhiidjy-binutils-2.38/bin/ld: cannot find slapd-common.o: No such file or directory
> ```
> 
> Weird.

Same happens on master. I guess I have to trust ofborg.

**Comment by SuperSandro2000** [comment]
openldap tests are failing on x86-64_linux

**Comment by dotlambda** [comment]
I moved the change concerning `pythonImportsCheck` to https://github.com/NixOS/nixpkgs/pull/201277.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 175235` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python310Packages.pysvn</li>
    <li>python39Packages.pysvn</li>
    <li>rabbitvcs</li>
  </ul>
</details>

**Pull request merged**
