### PR TITLE
wine64Packages: fix mainProgram

### PR DESCRIPTION
**Pull request by ShamrockLee**
###### Description of changes

This patch fixes the `meta.mainProgram` of packages in `wine64Packages` by adding `mainProgram` as an input parameter of `base.nix` default to `"wine"`, and specified as `"wine64"` for packages mentioned above.

This change should be backward compatible and cause no rebuilds.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Cc package maintainers: @avnik @raskin @bendlas @jmc-figueira

### CODE REVIEW

**Review by SFrijters — APPROVED** [review]
Looks sensible to me.
For `wineWow` do we still want the 32-bit `wine` to be default?

**Comment by ShamrockLee** [comment]
> For `wineWow` do we still want the 32-bit `wine` to be default?

I didn't use it often (after the messaging app LINE stopped working in Wine) I'm not sure about the use case, but defaulting to `wine64` sounds like a good idea.

BTW, we would need to document it in the release note (as a backward incompatibility) if the we change the mainProgram of a currently working package IMO.

**Review by SFrijters — APPROVED** [review]

**Comment by Ma27** [comment]
LGTM, please resolve the conflict though.

**Comment by ShamrockLee** [comment]
Rebased on top the master branch.

**Pull request merged**
