### PR TITLE
akkoma: 3.5.0 → 3.6.0

### PR DESCRIPTION
**Pull request by illdefined**
###### Description of changes

- New Akkoma release 3.6.0: <https://akkoma.dev/AkkomaGang/akkoma/src/tag/v3.6.0/CHANGELOG.md>,
- `pleroma-fe` renamed to `akkoma-fe`, new stable revison,
- new stable revision for `admin-fe`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
The hash doesn't match for me for https://akkoma.dev/AkkomaGang/akkoma/archive/v3.6.0.tar.gz ... I'm getting `sha256-Ovi2AnfkeCDlv3INomPxu8R1ARexOzZHC8dOLucrDaQ=`

**Comment by K900** [comment]
ofborg is getting the same hash too.

**Comment by K900** [comment]
Been running it for a few days (with the hash fixed), no issues here, let's merge.

**Comment by illdefined** [comment]
> The hash doesn't match for me for https://akkoma.dev/AkkomaGang/akkoma/archive/v3.6.0.tar.gz ... I'm getting `sha256-Ovi2AnfkeCDlv3INomPxu8R1ARexOzZHC8dOLucrDaQ=`

I changed the Git ref from a commit ID to a tag without considering that the hash would be different.

**Pull request merged**
