### PR TITLE
lirc: upgraded to 0.9.2a

### PR DESCRIPTION
**Pull request by bobvanderlinden**
An attempt to solve the problems mentioned in #6050. From ArchLinux repo I gathered that the patch wasn't needed anymore. In addition lirc now needs pkgconfig and x11. Python3 is used during the build phase.

I got everything compiled. Testing lirc gave a bit of trouble. I had the same trouble with lirc on the stable channel. I probably don't know how lirc works on a laptop (I only have it running on a non-nix raspberry pi).

### CODE REVIEW

**Comment by bobvanderlinden** [comment]
@victoredwardocallaghan @pSub could you give this a look? I have little knowledge of lirc on Nix.

**Comment by pSub** [comment]
The build fails for me with the following error:

```
./make_rel_symlink.py \
    //lirc-setup \
    //nix/store/rzmd5198i991vx75v6p3pw7352nzgj9r-lirc-0.9.2a/bin/lirc-setup
/nix/store/4dd49ybmqlaq2xw6cb4wxrgs51zhv19s-bash-4.3-p33/bin/bash: ./make_rel_symlink.py: /usr/bin/env: bad interpreter: No such file or directory
```

It should be easy to fix, but I remember from a previous attempt on updating lirc, that there was some problem with hardcoded paths.

@bobvanderlinden Do you have chroot builds enabled? I wonder why the build fails for me, but works for you.

**Comment by bobvanderlinden** [comment]
Hmm, ok. I wasn't aware that building with chroot enabled was bad. I build it on ArchLinux and on NixOS. On nixos I indeed had `nix.useChroot = true;` in my configuration.

Anyway, I've disabled chroot on my Nix machine and then it failed. I patched it by replacing `#!/usr/bin/env python3` with `${python3}/bin/python3`.

Maybe unrelated, but could you explain (or link) me why chroot must be disabled? I gathered it would make a separate chroot with only the buildInput in there, but apparently not?

**Comment by pSub** [comment]
Building with chroot enabled is good! I thought that you don't get the error, because you have chroots disabled. I have `nix.useChroot = true` and get this error… Weird…

**Comment by bobvanderlinden** [comment]
Yes, not sure what is going on. Not sure what's up with my setup, but it with the latest fix it should work with or without chroot. It works here either way. Travis seems to be failing on a different (unrelated?) packages. Could you give it a try?

**Comment by pSub** [comment]
Builds find for me. Thank you!

**Comment by bobvanderlinden** [comment]
Thanks!

**Pull request merged**
