### PR TITLE
neovim: revert change to extraMakeWrapperArgs

### PR DESCRIPTION
**Pull request by teto**
The changes in https://github.com/NixOS/nixpkgs/pull/101265 changed wrapNeovim to incite users to use a list instead of a string for extraMakeWrapperArgs. This reverts that since the change is not super useful (also I want the wrapper to be low-level so passing a string may actually make more sense) while breaking home-manager see https://github.com/nix-community/home-manager/issues/1577
@SenchoPens  does that fix your issue ?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by beardhatcode** [comment]
@teto, The same problem cropped up for me today. However this fixes it for me 
(nikpkgs @ db157224ef26d088b66d30b62a50f602ef526545 and home-manager @ [a98ec6e](https://github.com/nix-community/home-manager/commit/a98ec6ec158686387d66654ea96153ec06be33d7))

Thanks :+1:

**Review by LnL7 — APPROVED** [review]
I haven't been following the wrapper changes specifically, but this restores the current behaviour.

If you think the new approach should be encouraged the example is the manual should also be updated. Along with maybe some kind of warning when the fallback is used.

**Comment by teto** [comment]
sure. New wrapper is still a work in progress so I will wait for its interface to stabilize before updating these. Merging then and sorry for the annoyance.

**Comment by LnL7** [comment]
Alright, makes sense.

**Pull request merged**
