### PR TITLE
python311Packages.cloudscraper: 1.2.69 -> 1.2.71

### PR DESCRIPTION
**Pull request by fabaff**
Changelog: https://github.com/VeNoMouS/cloudscraper/releases/tag/1.2.71

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 230008` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>fanficfare</li>
    <li>fanficfare.dist</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>komikku</li>
    <li>maigret</li>
    <li>maigret.dist</li>
    <li>python310Packages.cloudscraper</li>
    <li>python310Packages.cloudscraper.dist</li>
    <li>python310Packages.garminconnect</li>
    <li>python310Packages.garminconnect.dist</li>
    <li>python311Packages.cloudscraper</li>
    <li>python311Packages.cloudscraper.dist</li>
    <li>python311Packages.garminconnect</li>
    <li>python311Packages.garminconnect.dist</li>
  </ul>
</details>

**Comment by NickCao** [comment]
The tag is yanked? Nothing at https://github.com/VeNoMouS/cloudscraper/tags

**Comment by kini** [comment]
It's still there on PyPI. It and the previous version, 1.2.70, both seem to be missing on github. :thinking: Maybe let's wait and see what's going on here.

**Comment by fabaff** [comment]
> The tag is yanked? Nothing at https://github.com/VeNoMouS/cloudscraper/tags

Looks more like that upstream is no longer tagging the source.

**Review by wegank — APPROVED** [review]

**Comment by kini** [comment]
> > The tag is yanked? Nothing at https://github.com/VeNoMouS/cloudscraper/tags
> 
> Looks more like that upstream is no longer tagging the source.

Well, presumably the changelog page you linked at the top of this pull request (https://github.com/VeNoMouS/cloudscraper/releases/tag/1.2.71) existed at the time the PR was made, but it doesn't exist now. Doesn't that indicate something was pulled?

**Comment by wegank** [comment]
I doubt the changelog page ever existed.

Anyway, https://github.com/VeNoMouS/cloudscraper/compare/1.2.69...cbb3c0e looks trivial, I don't think anything could be pulled.

**Comment by fabaff** [comment]
The changelog link in the PR description was added by `nix-update` and is based on the `changelog` entry. Now, upstream doesn't tag the source and this renders the link useless.

**Comment by kini** [comment]
Oh, I see :) Thanks for the explanation!

**Review by kini — APPROVED** [review]

**Pull request merged**
