### PR TITLE
Libbsd update Darwin patch

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change
This updates the Darwin patch for libbsd. The latest update broke it but I've reworked it so it applies there now.

### CODE REVIEW

**Review by LnL7 — APPROVED** [review]

**Comment by LnL7** [comment]
@GrahamcOfBorg build libtiger

**Comment by LnL7** [comment]
@GrahamcOfBorg build libbsd

**Comment by orivej** [comment]
The bot has approved the PR those meta does not evaluate: f80a55ca37a6130784587bebb8f55718a62f3e69

**Comment by LnL7** [comment]
That's is exactly one of the things I want to add to the bot, unless @grahamc beats me to it 😄

**Pull request merged**
