### PR TITLE
drop unmaintained phabricator package, service, and httpd subservice

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Stuck on a version from 2014, time for someone to either take this on or drop it.

If everyone agrees this should be dropped then I'll add release notes before we merge.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by thoughtpolice — APPROVED** [review]
This sounds good to me (while I didn't maintain these packages, I did maintain the Arcanist packages). In general we probably shouldn't be running/"endorsing" obsolete Phabricator versions at all.

**Review by danbst — APPROVED** [review]
agree. Maybe mention also in release notes?

I was using an approach based on @thoughtpolice scripts: https://gist.github.com/danbst/0580293476b963755e359e0aa7e9eac5

**Comment by FRidh** [comment]
Please add the release notes.

**Comment by aanderse** [comment]
> If everyone agrees this should be dropped then I'll add release notes before we merge.

I will assume everyone agrees this should be merged then. Will do. Thanks.

**Comment by aanderse** [comment]
@danbst Thanks for the link!

**Comment by aanderse** [comment]
Thanks all!

**Pull request merged**
