### PR TITLE
Fix kernel configuration merge

### LINKED ISSUE #71803: wrong merging  of kernel "optional" setting
**Describe the bug**

The `optional` character of a kernel configuration is set to true upon merging instead of false.

The fix is to update kernel_config.nix to:
```
  mergeFalseByDefault = locs: defs:
    if defs == [] then abort "This case should never happen."
    else if any (x: x.value == false) defs then false
    else true;
```
I need to update/check the tests too

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by teto**
###### Things done

Fix https://github.com/NixOS/nixpkgs/issues/71803

Was a bit tougher than expected because I misunderstood how mkMerge worked. I thought using submodule would create the missing fields in attribute sets but it doesn't. 
The fix made apparent that some configuration entries in common-config.nix are unused.
As it may depend on kernel version, I marked the entries optional. It felt less likely to break builds than plainly removing them (but removing them could be the correct thing to do). 

I improved the tests and made them more readable.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
should this target staging?

**Comment by teto** [comment]
done

**Comment by eadwu** [comment]
This doesn't seem to fix `INET_TCP_DIAG`? For me `INET_TCP_DIAG? m` is set which should be correct since it is now an option, but I'm still getting `warning: option not set correctly: INET_TCP_DIAG (wanted 'm', got 'y')` still.

**Comment by teto** [comment]
The warning for INET_TCP_DIAG already occurs on nixos-unstable. The way I see it, it should have triggered an error (and now would thanks to this PR, I changed the config to `INET_TCP_DIAG = option module;` to keep it working).
The config is `INET_TCP_DIAG = module;` fails because the kernel never asks for the setting and defaults to `yes` (probably because `INET_DIAG   = yes;`).
I've removed the entry in pkgs/os-specific/linux/kernel/common-config.nix due to your comment since it was not respected. If someone really wants INET_TCP_DIAG as a module, I can tweak it (cc @ivan from https://github.com/NixOS/nixpkgs/pull/69388 ).

**Comment by teto** [comment]
would like to merge this since it fixes a non-obvious bug CC @NeQuissimus

**Pull request merged**
