### PR TITLE
gnome3.gpaste: Add GPaste service

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
This makes GPaste finally work.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Do I need to run Gnome to test it?

**Comment by jtojnar** [comment]
@Mic92 I think the module should work even outside of GNOME, setting the `sessionPath` should only be necessary for the GNOME Shell extension.

**Comment by Mic92** [comment]
I suppose the gnome icon theme or something else is still missing:

```
systemctl status --user org.gnome.GPaste.Ui
● org.gnome.GPaste.Ui.service - GPaste user interface
   Loaded: loaded (/nix/store/z2xq8jmpjd13h6d8lkzhdrjc2vcrzgcj-gpaste-3.24.2/etc/systemd/user/org.gnome.GPaste.Ui.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2017-09-03 11:06:58 BST; 41s ago
 Main PID: 19451 (.gpaste-ui-wrap)
   CGroup: /user.slice/user-1000.slice/user@1000.service/org.gnome.GPaste.Ui.service
           └─19451 /nix/store/z2xq8jmpjd13h6d8lkzhdrjc2vcrzgcj-gpaste-3.24.2/libexec/gpaste/gpaste-ui --gapplication-service
Sep 03 11:06:58 turingmachine systemd[9834]: Starting GPaste user interface...
Sep 03 11:06:58 turingmachine systemd[9834]: Started GPaste user interface.
Sep 03 11:06:58 turingmachine .gpaste-ui-wrap[19451]: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not pr
Sep 03 11:06:58 turingmachine .gpaste-ui-wrap[19451]: Could not find the icon 'edit-paste'. The 'hicolor' theme
                                                      was not found either, perhaps you need to install it.
                                                      You can get a copy from:
                                                              http://icon-theme.freedesktop.org/releases
```

screen

**Comment by jtojnar** [comment]
@Mic92 That would be `adwaita-icon-theme`.

**Comment by Mic92** [comment]
also in 17.09 now.

**Pull request merged**
