### PR TITLE
mautrix-telegram: 0.6.1 -> 0.7.0

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

Updates `mautrix-telegram` to [0.7.0](https://github.com/tulir/mautrix-telegram/releases/tag/v0.7.0).
The dependency `mautrix-appservice` was updated to [0.4.0](https://github.com/tulir/mautrix-python/releases/tag/v0.4.0) and was renamed to `mautrix`.

:warning: The license of `python3Packages.mautrix` changed from MIT to [MPL2](https://github.com/tulir/mautrix-python/commit/7c6f05e5a18cc932ccfb2f2bbf38dcb054d8261d).

---

Final notes:

* I'd wait with merging until @pacien took a look at this (as this PR will require changes in their mautrix-telegram-module PR)
* I'm currently running this on my HS on NixOS 19.09 (you need to update `python3Packages.telethon` to 1.10.9 in your fork to make it work).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @nyanloutre @pacien

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
LGTM

failures not related to PR

```
[6 built (1 failed), 8 copied (5.6 MiB), 0.8 MiB DL]
error: build of '/nix/store/ly5qlnciv2ygnvxpkvyarwxwpda6xvwm-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/76603
1 package failed to build:
python38Packages.mautrix

2 package were built:
mautrix-telegram python37Packages.mautrix
```

**Comment by jonringer** [comment]
please address darwin issue, or limit platforms to only linux :)

**Comment by Ma27** [comment]
@jonringer fixed (explanation is in the body of the commit message :))

**Comment by jonringer** [comment]
LGTM

**Pull request merged**
