### PR TITLE
Merge Staging

### PR DESCRIPTION
**Pull request by domenkozar**
Current status: http://hydra.nixos.org/eval/1289636?compare=trunk-combined

Outstanding issues:
- [x] stdenvBootstrapTools fails on linux
- [x] libreoffice fails
- [ ] [cryptonite](http://hydra.nixos.org/build/39357184/nixlog/1/raw)
- [x] chromium test fails (and so the tested job)

### CODE REVIEW

**Comment by domenkozar** [comment]
@obadz any ideas about http://hydra.nixos.org/build/39357184/nixlog/1/raw

**Comment by globin** [comment]
@domenkozar it built locally earlier today AFAIR maybe fixed by now

**Comment by vcunat** [comment]
Bootstrap tools seem OK on Hydra, and acca6d2293 should fix at least some libreoffice errors.

**Comment by obadz** [comment]
cryptonite builds fine locally but doesn't seem to build on hydra.

**Comment by obadz** [comment]
Built after sufficient number of restarts. Might be made more reliable with #18118

**Comment by obadz** [comment]
`nix-build -A perlPackages.DBIxClass` has failing tests:

```
Test Summary Report
-------------------
t/prefetch/grouped.t                              (Wstat: 65280 Tests: 31 Failed: 1)
  Failed test:  28
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=319, Tests=41280, 130 wallclock secs ( 4.94 usr  0.52 sys + 112.74 cusr 15.30 csys = 133.50 CPU)
Result: FAIL
Failed 1/319 test programs. 1/41280 subtests failed.
make: *** [Makefile:1718: test_dynamic] Error 255
```

Blocks the building of `hydra`.

**Comment by domenkozar** [comment]
Known to upstream: https://rt.cpan.org/Public/Bug/Display.html?id=117271#txn-1662798

**Pull request merged**
