### PR TITLE
simulide: migrate to pkgs/by-name

### PR DESCRIPTION
**Pull request by TomaSajt**
This should not cause any rebuilds.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by TomaSajt** [comment]
I could move the optional parts directly into the place it's used, but it's a bit easier to review like this.
When I add the next versionNum I'll probably do it, but not now.

**Review by uninsane — APPROVED** [review]

**Comment by TomaSajt** [comment]
@reckenrode was just wondering if I was doing anything wrong with the `pkgs/by-name`-compatible multi-version support.
Tried to do it similarly to `apple-sdk`, but maybe there's something better than what I came up with.

**Review by BonusPlay — APPROVED** [review]

**Review by msanft — COMMENTED** [review]
IIRC, we didn't do move-only PRs at some point - but that might have changed. 

Additionally, if we move a package, I think it would be preferable to move it and then rename it in a separate commit to make git notice that it's a moved file only, thus keeping history.

**Comment by TomaSajt** [comment]
The thing is, this is a non-trivial move. This is why I only made changes that didn't cause any rebuilds, to ensure correctness.
I think we won't lose too much in the history, since there weren't a lot of updates

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Comment by reckenrode** [comment]
> @reckenrode was just wondering if I was doing anything wrong with the `pkgs/by-name`-compatible multi-version support. Tried to do it similarly to `apple-sdk`, but maybe there's something better than what I came up with.

Sorry, just saw this. The reorganized derivation seems fine. FWIW `apple-sdk` uses `callPackage` instead of `override` because of the way the latter interacts with overlays. If an overlay changes `apple-sdk`, then it also changes all overrides of `apple-sdk`, which may not be desirable.

**Pull request merged**
