### PR TITLE
nixos/qemu-vm: fix minor typo

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

The typo creates an empty directory `/0755` in initrd rootfs rather than create the Nix store directories with mode 0755

I guess setting the mode is not strictly necessary if it worked before this change, but I'll leave the `-m 0755` in just in case

cc: @ElvishJerricco (since we discussed this in Matrix in `#systemd-stage-1:nixos.org`)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
`0755` should be the default anyway, so this change should be practically a no-op aside from the missing `0755` directory; is that right?

**Comment by lilyinstarlight** [comment]
> `0755` should be the default anyway, so this change should be practically a no-op aside from the missing `0755` directory; is that right?

That is probably right, yeah. I mean it worked before so if you'd rather I removed it I'm fine with doing that too

**Comment by ElvishJerricco** [comment]
No it's probably best to have the explicit permissions there just for the style points. I just wanted to be sure I was sane for thinking this change should be a no-op.

**Comment by ElvishJerricco** [comment]
@ofborg test systemd-initrd-simple fsck

Just picking the simplest tests I can think of to prove this works here.

**Pull request merged**
