### PR TITLE
mailspring: init at 1.6.3

### PR DESCRIPTION
**Pull request by rummik**
###### Motivation for this change
I was checking out Mailspring, and happened to find out that there wasn't a Nix package for it.  So here's the result after some poking around.  It uses more or less the same configuration option that previously existed for Nylas to enable Gnome3's keyring, since libsecret requires a functioning password storage option

I'm not totally sure what else I should do since this is my first time contributing :sweat_smile: 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by aanderse** [comment]
You should collaborate with @tyrion who recently opened https://github.com/NixOS/nixpkgs/pull/69027.

**Comment by tyrion** [comment]
I get this error when trying to build it:
```
searching for dependencies of /nix/store/jbbzpxz0k7ibhj4hjya7kr91sihifws1-mailspring-1.6.3/share/mailspring/resources/app.asar.unpacked/libscram.so.2.0.25
  libcrypto.so.1.0.0 -> not found!
builder for '/nix/store/v0vp01ppvgkbw0zzciqg8gfc5ya965fg-mailspring-1.6.3.drv' failed with exit code 1
error: build of '/nix/store/v0vp01ppvgkbw0zzciqg8gfc5ya965fg-mailspring-1.6.3.drv' failed
```

**Comment by rummik** [comment]
@tyrion Yeah, looks like I somehow lost a dependency somewhere

**Comment by rummik** [comment]
@tyrion Seems the updated openssl versions didn't include `libcrypto.so.1.0.0`, so a symlink was needed.  It still requires gnome-keyring to function though, or some other keyring with libsecret support

**Comment by aanderse** [comment]
ping (triage)

**Comment by aanderse** [comment]
Seems like something went wrong with your last push. Can you please take a look and try again?

**Comment by tyrion** [comment]
I tried this pr and it seemed to work fine in the beginning, but then I realized I had problems with my non-google accounts. For some reason SMTP refuses to work. I tried with mailbox.org and posteo.de. The issue I was getting is similar to this one: https://github.com/Foundry376/Mailspring/issues/341

Switching back to my pr ( https://github.com/NixOS/nixpkgs/pull/69027 ) the issue seems to vanish.

**Comment by tklitschi** [comment]
#85492 working better. May wanna close this PR.

**Comment by drewrisinger** [comment]
Closed by #85492

**Pull request closed without merging**
