### PR TITLE
pythonPackages.pytest-sugar: 0.9.0 -> 0.9.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
@grahamc Something's wrong with @GrahamcOfBorg

**Comment by grahamc** [comment]
Master is broken :( Looking in to it. Thanks.

**Comment by grahamc** [comment]
(OfBorg is fine -- its just that someone broke master.)

**Comment by dotlambda** [comment]
I hope it wasn't one of my own commits :see_no_evil:

**Comment by grahamc** [comment]
nope, it is a memory issue I thought we'd hit one day ... and here we are :) 

 - https://github.com/NixOS/ofborg/commit/03a2d8427a83fdc893a965cc3b5c5a59b5c0509d
 - https://github.com/NixOS/ofborg/commit/70b55fba42ead4ac21a43c9c9f917ed9ecdd4641

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by dotlambda** [comment]
It works! :tada: Thank you!

**Comment by dotlambda** [comment]
The list of packages `nox-review` wants to compile:
```
python27Packages.zerobin python36Packages.zerobin python36Packages.pytest-sugar python36Packages.cheroot python27Packages.portend mnemosyne python36Packages.ws4py python27Packages.WSME tribler python27Packages.cherrypy flexget python36Packages.WSME python36Packages.bugseverywhere python27Packages.bugseverywhere python36Packages.cherrypy python27Packages.ws4py python27Packages.cheroot python27Packages.pytest-sugar python36Packages.portend
```
All but tribbler and flexget compile just fine after the update. The other two were also broken before.

**Pull request merged**
