### PR TITLE
Bump patchelf to 0.10

### PR DESCRIPTION
**Pull request by booxter**
This release contains three years of bug fixes and improvements.

### CODE REVIEW

**Comment by booxter** [comment]
I've validated that the package can be built; but I am not sure it's enough of testing for such a core package. If not, I seek guidance / help.

**Comment by domenkozar** [comment]
needs to target staging branch

**Comment by Infinisil** [comment]
`patchelfUnstable` needs to point to this version now, and patchelfUnstable seems to include a patch to make it work with musl, which should probably be tested. Also maybe the tests can be enabled, unstable has them enabled for non-darwin.

**Comment by booxter** [comment]
@Infinisil see, this is what I was afraid of. ;)

1. I will propose for staging, sorry I forgot that this package is special.
2. How would I test with musl? I have no idea what it is (yet). But it seems to me that the patch you refer to is only for tests (that are disabled in this package because they still fail).
3. Tests still fail the same way (except that the number of failing tests is 25 now, not 24; I will update the counter in the comment). I can share output with you if interested.

**Comment by booxter** [comment]
@Infinisil I also have, perhaps silly, questions on `patchelfUnstable`:

1. How do I install it with `nix-env`? `nix-env -f . -i patchelfUnstable` gives me:

```
error: selector 'patchelfUnstable' matches no derivations
```

2. Why do we need it at all if it's the exact same version? Should we drop it? (Perhaps I misunderstand the goal of having an "unstable" package in the tree; if so, do you have a link to documentation for me to chew on to understand it better?)

**Comment by Infinisil** [comment]
1. Well the package isn't special per-se, it's just that there's a *lot* of things that depend on `patchelf`. We put such changes on staging to reduce total amounts of rebuilds of those lots of things, so we can bunch such updates together.
2. One of the most basic libraries, one almost every package uses is libc. musl is an alternate implementation of it, focusing on it being very small, very useful for embedded stuff. You can build musl versions through `pkgsMusl`: `nix-build -A pkgsMusl.patchelf`
3. Output would be nice yeah, just to get a sense of why it's failing.



1. `nix-env -f. -iA patchelfUnstable`, but I usually just `nix-build -A patchelfUnstable` and then use `result/bin/..` to test things, then I don't need to install anything
2. We shouldn't drop it completely, because lots of things use `patchelfUnstable`, which would all fail if we removed it. In the future we might change `patchelfUnstable` to point to a new unstable version (without updating the normal `patchelf`).

One of the major things this PR needs is to figure out what other packages start failing to build with the newer version. For this I think it would be nice to add a hydra jobset. This might take a while to get merged :)

Ping @edolstra @domenkozar @dtzWill @Ericson2314 @jtojnar (people who are relevant for hydra jobs, and/or know a lot about staging stuff)

**Comment by booxter** [comment]
@Infinisil here is a pastebin with test failures: https://pastebin.com/9xGgW2h8 (I actually get the same errors when trying to build the `patchelfUnstable` package with no changes to the expression whatsoever).

**Comment by booxter** [comment]
Interestingly, when I build `pkgsMusl.patchelf` from regular 0.10 derivation (not unstable), I get only a single failure: https://pastebin.com/TG3Keexz which can be fixed with the following patch (adopted from unstable derivation):

```
diff --git a/pkgs/development/tools/misc/patchelf/default.nix b/pkgs/development/tools/misc/patchelf/default.nix
index 355d3979822..1c3df031f75 100644
--- a/pkgs/development/tools/misc/patchelf/default.nix
+++ b/pkgs/development/tools/misc/patchelf/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, fetchurl }:
+{ stdenv, fetchurl, autoreconfHook }:
 
 stdenv.mkDerivation rec {
   name = "patchelf-0.10";
@@ -8,9 +8,18 @@ stdenv.mkDerivation rec {
     sha256 = "1wzwvnlyf853hw9zgqq5522bvf8gqadk8icgqa41a5n7593csw7n";
   };
 
+  # Drop test that fails on musl (?)
+  postPatch = stdenv.lib.optionalString stdenv.hostPlatform.isMusl ''
+    substituteInPlace tests/Makefile.am \
+      --replace "set-rpath-library.sh" ""
+  '';
+
   setupHook = [ ./setup-hook.sh ];
 
-  doCheck = false; # fails 8 out of 24 tests, problems when loading libc.so.6
+  nativeBuildInputs = [ autoreconfHook ];
+  buildInputs = [ ];
+
+  doCheck = stdenv.hostPlatform.isMusl;
 
   meta = with stdenv.lib; {
     homepage = https://nixos.org/patchelf.html;
```

**Comment by booxter** [comment]
Gosh, what a mess I make with pull requests here.

**Comment by Infinisil** [comment]
(New PR is https://github.com/NixOS/nixpkgs/pull/58715)

**Pull request closed without merging**
