### PR TITLE
rocm: add update scripts

### PR DESCRIPTION
**Pull request by Flakebi**
###### Motivation for this change
Tested OpenCL with an example and it still works.

To update everything with the update scripts:
```shell
for f in rocm-smi rocm-cmake rocm-thunk rocm-runtime rocm-opencl-runtime rocm-device-libs rocm-comgr rocclr rocminfo llvmPackages_rocm.llvm hip; nix-shell maintainers/scripts/update.nix --argstr commit true --argstr package $f; end
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
Duplicate of #136445

**Comment by Flakebi** [comment]
Oh my, even hip is in there. Thanks for the heads up, I’ll rebase.

**Review by acowley — APPROVED** [review]
These update scripts look terrific! What a great addition.

**Review by lovesegfault — APPROVED** [review]
This rocks!

**Comment by SuperSandro2000** [comment]
Why do we even need this? Can't nix-update handle all of this?

**Comment by Flakebi** [comment]
I didn’t know nix-update before. Seems like it needs a regex (like `nix-update rocm-smi --version-regex 'rocm-(.*)'`), it can’t update llvm and for some reason it also cannot update hip (`Nix's builtins.parseDrvName could not parse the version from hip`).

Using the update.nix script for all packages looks more convenient to me.

**Pull request merged**
