### PR TITLE
Xorg: apply patch to fix X crashes

### PR DESCRIPTION
**Pull request by domenkozar**
I'm running this patch after I had a crash clicking a chromium tab.

/cc @the-kenny @rbvermaa

### CODE REVIEW

**Comment by edolstra** [comment]
Shouldn't this go to master first (and then cherry-pick to the release branch)?

**Comment by the-kenny** [comment]
I'm rebuilding my system on this patch as we're talking. I'll comment
here if I experience another crash.

Domen Kožar <notifications@github.com> writes:

> I'm running this patch after I had a crash clicking a chromium tab.
>
> /cc @the-kenny @rbvermaa 
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/NixOS/nixpkgs/pull/9658
>
> -- Commit Summary --
>
>   * Xorg: apply patch to fix X crashes
>
> -- File Changes --
>
>     A pkgs/servers/x11/xorg/fix_segfault.patch (63)
>     M pkgs/servers/x11/xorg/overrides.nix (3)
>
> -- Patch Links --
>
> https://github.com/NixOS/nixpkgs/pull/9658.patch
> https://github.com/NixOS/nixpkgs/pull/9658.diff
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/9658

--

**Comment by domenkozar** [comment]
@edolstra sure we can do that.

**Comment by vcunat** [comment]
This only changes `xorgserver` which should cause almost no rebuilds (just some drivers a VNC stuff IIRC).

**Comment by domenkozar** [comment]
Pushed to master and release-15.09

**Pull request closed without merging**
