### PR TITLE
nodejs: switch from 14.x to 16.x to keep up with the lts release

### PR DESCRIPTION
**Pull request by bobrik**
###### Motivation for this change

See: https://nodejs.org/en/about/releases/

It's also the only version that works properly on aarch64-darwin.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
It's been fixed for node2nix: https://github.com/svanderburg/node2nix/commit/e73c616408b753c386301e1d21ac634c959a4b6f

**Comment by happysalada** [comment]
We could do an unstable release of node2nix, but I feel it's better to keep what we have and change when node2nix makes a new release.

**Comment by bobrik** [comment]
https://github.com/NixOS/nixpkgs/issues/144627#issuecomment-975947953 mentions that the branch off happened already. Is it time to revisit this?

**Comment by happysalada** [comment]
btw, there is an update in progress of node2nix https://github.com/NixOS/nixpkgs/pull/146440/files
but yeah I think this can potentially be merged to staging. Whenever there is time to rebase and fix the conflict, I personally think this is mergeable, unless anyone sees an objection that I have missed.

**Comment by bobrik** [comment]
Rebased

**Comment by happysalada** [comment]
I just noticed, node16 fails to build on aarch64-darwin. @marsam is this normal or is this just a transitive failure ? (no worries if you don't know). Given that nixos supports darwin on tier1, we can't just merge this then ? (let me know if I'm wrong).

**Comment by bobrik** [comment]
@happysalada it builds just fine on master branch:

* https://hydra.nixos.org/eval/1725069?filter=nodejs&compare=1724929&full=#tabs-still-succeed

**Comment by happysalada** [comment]
@bobrik thanks for checking this out. Let's merge then.

**Comment by turboMaCk** [comment]
This PR cause this regression https://github.com/NixOS/nixpkgs/issues/152745 As far as I know we still lack support for nodejs 16 in node2nix which makes me wonder - What was tested before merge here? I have a feeling there might be more things broken at the moment.

**Comment by happysalada** [comment]
I thought the latest version of node2nix supports node 16 (version 1.10). There is a current PR to regenerate and test nodePackages https://github.com/NixOS/nixpkgs/pull/146440 (still WIP).
Since it was impossible to test all the packages, if I remember correctly nodePackages were tested. We indeed missed elmPackages indeed.
I personally use 
```
      nodePackages.prettier
      nodePackages.pnpm
      nodePackages.node2nix
      nodePackages.npm-check-updates
      nodePackages.svelte-language-server
      nodePackages.yarn
```
and those work like a charm.

**Comment by turboMaCk** [comment]
> We indeed missed elmPackages 

don't worry about that. It's intentionally designed in a way it doesn't block work on other parts of nixpkgs. I'm happy to take care of it. That's being said I think there might be other packages which rely on expressions produced by node2nix using `nodejs` argument which might need updating. It's not just nodePackages (which are btw independent of what is defined as nodejs in nixpkgs so I think they don't even use node 16 but I might be mistaken) - there can be applications using node2nix for packaging and using nodejs argument.

Anyway I think we can deal with all the potential issues if there are any.

**Comment by turboMaCk** [comment]
To clarify. I think that if intention of this PR was to update nodejs version things defined within `nodePackages` are using I don't think it accomplished that. This updated nodejs version for everything which uses `nodejs` attribute directly but I think `nodePackages` are using explicit attribute name which was updated in https://github.com/NixOS/nixpkgs/pull/149120 to version 14. Anyway take this with grain of salt - I did not check the code base this is just based on my memories of working with that part of nixpkgs about a year ago.

In order to update nodejs version for things that use node2nix we need to wait for support upstream. Current highest version node2nix supports is 14. However this should update nodejs for derivations that don't depend on node2nix (don't use npm dependecies, just node).

**Pull request merged**
