### PR TITLE
lua-language-server: 3.11.1 -> 3.12.0

### PR DESCRIPTION
**Pull request by gepbird**
Release: https://github.com/LuaLS/lua-language-server/releases/tag/3.12.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gepbird** [comment]
Fails to build on my review vm

<details><summary>Build log</summary>

```
lua-language-server> 测试[tclient]...
lua-language-server> test/tclient/tests/load-relative-library.lua:54: assertion failed!
lua-language-server> stack traceback:
lua-language-server>    [C]: in function 'assert'
lua-language-server>    test/tclient/tests/load-relative-library.lua:54: in upvalue 'callback'
lua-language-server>    script/lclient.lua:129: in function <script/lclient.lua:128>
lua-language-server> stack traceback:
lua-language-server>    script/lclient.lua:123: in function 'await.errorHandle'
lua-language-server>    script/await.lua:35: in function 'await.checkResult'
lua-language-server>    (...tail calls...)
lua-language-server>    script/lclient.lua:201: in local 'callback'
lua-language-server>    script/lclient.lua:232: in method 'update'
lua-language-server>    script/lclient.lua:143: in method 'start'
lua-language-server>    test/tclient/tests/load-relative-library.lua:13: in main chunk
lua-language-server>    [C]: in upvalue 'originRequire'
lua-language-server>    test.lua:42: in function 'require'
lua-language-server>    test/tclient/init.lua:11: in main chunk
lua-language-server>    [C]: in upvalue 'originRequire'
lua-language-server>    test.lua:42: in function 'require'
lua-language-server>    test.lua:48: in upvalue 'test'
lua-language-server>    test.lua:108: in local 'main'
lua-language-server>    test.lua:115: in main chunk
lua-language-server>    (bootstrap.lua):85: in main chunk
lua-language-server>    [C]: in ?
lua-language-server> bin/lua-language-server: script/lclient.lua:124: [19:47:46.386][error][#0:script/lclient.lua:123]: test/tclient/tests/load-relative-library.lua:54: assertion failed!
lua-language-server> stack traceback:
lua-language-server>    [C]: in function 'assert'
lua-language-server>    test/tclient/tests/load-relative-library.lua:54: in upvalue 'callback'
lua-language-server>    script/lclient.lua:129: in function <script/lclient.lua:128>
lua-language-server> stack traceback:
lua-language-server>    script/lclient.lua:123: in function 'await.errorHandle'
lua-language-server>    script/await.lua:35: in function 'await.checkResult'
lua-language-server>    (...tail calls...)
lua-language-server>    script/lclient.lua:201: in local 'callback'
lua-language-server>    script/lclient.lua:232: in method 'update'
lua-language-server>    script/lclient.lua:143: in method 'start'
lua-language-server>    test/tclient/tests/load-relative-library.lua:13: in main chunk
lua-language-server>    [C]: in upvalue 'originRequire'
lua-language-server>    test.lua:42: in function 'require'
lua-language-server>    test/tclient/init.lua:11: in main chunk
lua-language-server>    [C]: in upvalue 'originRequire'
lua-language-server>    test.lua:42: in function 'require'
lua-language-server>    test.lua:48: in upvalue 'test'
lua-language-server>    test.lua:108: in local 'main'
lua-language-server>    test.lua:115: in main chunk
lua-language-server>    (bootstrap.lua):85: in main chunk
lua-language-server>    [C]: in ?
lua-language-server> 
lua-language-server> stack traceback:
lua-language-server> 	[C]: in function 'error'
lua-language-server> 	script/lclient.lua:124: in function 'await.errorHandle'
lua-language-server> 	script/await.lua:35: in function 'await.checkResult'
lua-language-server> 	(...tail calls...)
lua-language-server> 	script/lclient.lua:201: in local 'callback'
lua-language-server> 	script/lclient.lua:232: in method 'update'
lua-language-server> 	script/lclient.lua:143: in method 'start'
lua-language-server> 	test/tclient/tests/load-relative-library.lua:13: in main chunk
lua-language-server> 	[C]: in upvalue 'originRequire'
lua-language-server> 	test.lua:42: in function 'require'
lua-language-server> 	test/tclient/init.lua:11: in main chunk
lua-language-server> 	[C]: in upvalue 'originRequire'
lua-language-server> 	test.lua:42: in function 'require'
lua-language-server> 	test.lua:48: in upvalue 'test'
lua-language-server> 	test.lua:108: in local 'main'
lua-language-server> 	test.lua:115: in main chunk
lua-language-server> 	(bootstrap.lua):85: in main chunk
lua-language-server> 	[C]: in ?
lua-language-server> FAILED: build/_/unit-test 
lua-language-server> bin/lua-language-server test.lua
lua-language-server> ninja: build stopped: subcommand failed.
```

</details>

### `x86_64-linux`
<details>
  <summary>:x: 8 packages failed to build:</summary>
  <ul>
    <li>lua-language-server</li>
    <li>lua51Packages.llscheck</li>
    <li>lua52Packages.llscheck</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>lunarvim</li>
    <li>vscode-extensions.sumneko.lua</li>
  </ul>
</details>

**Comment by gepbird** [comment]
After changing nothing to the previous environment it passes, looks like some tests are flaky.

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352961`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>lua-language-server</li>
    <li>lua51Packages.llscheck</li>
    <li>lua52Packages.llscheck</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>lunarvim</li>
    <li>vscode-extensions.sumneko.lua</li>
  </ul>
</details>

**Comment by gepbird** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352961`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>lua-language-server</li>
    <li>lua51Packages.llscheck</li>
    <li>lua52Packages.llscheck</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>lunarvim</li>
    <li>vscode-extensions.sumneko.lua</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]
LGTM, i think my emulated aarch64-linux just struggles in the check phase.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352961`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>lua-language-server</li>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>lunarvim</li>
    <li>vscode-extensions.sumneko.lua</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>lua-language-server</li>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>lunarvim</li>
    <li>vscode-extensions.sumneko.lua</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>lua-language-server</li>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>lunarvim</li>
    <li>vscode-extensions.sumneko.lua</li>
  </ul>
</details>

**Pull request merged**
