### PR TITLE
.github/workflows: re-add editorconfig

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
I'll wait for a bit until we see that "Wait for ofborg" isn't causing any problems.

**Comment by zowoq** [comment]
The "Wait for ofborg" actions don't seem to have caused any problems.

**Comment by timokau** [comment]
Would it be possible to only mark this check as a failure when it has passed before? I don't like that I have to make unrelated formatting changes whenever I'm touching some non-conforming file now.

**Comment by timokau** [comment]
To be clear I like the check itself, although I do agree with @FRidh that it should at least be announced on discourse.

**Comment by zowoq** [comment]
> Would it be possible to only mark this check as a failure when it has passed before? I don't like that I have to make unrelated formatting changes whenever I'm touching some non-conforming file now.

I'd imagine that it could be done somehow but I don't really see that it would be worth the effort. There are ~22000 files in the repo and ~800 errors in ~500 files. IIRC was about ~1400 errors a week ago.

**Comment by worldofpeace** [comment]
@zowoq Is there any reason why we didn't use nix in the check to use editorconfig-checker?

**Pull request merged**
