### PR TITLE
minicom: 2.8 -> 2.9

### PR DESCRIPTION
**Pull request by hzeller**
## Description of changes

https://salsa.debian.org/minicom-team/minicom/-/releases/2.9

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hzeller** [comment]
Ready to approve @peterhoeg ? (Looks like that will help bring it up in the queue of people that can merge)

**Comment by hzeller** [comment]
@peterhoeg - ready to merge ?

**Comment by peterhoeg** [comment]
I've been afk for a little while - thank you for your patience @hzeller .

We typically don't bring in top-level attrsets such as darwin, but instead pass through the required attributes directly from `all-packages.nix`. Here's an example for minidsp (I don't use this - it's just an example):

```nix
{
  minidsp = callPackage ../applications/audio/minidsp {
    inherit (darwin.apple_sdk.frameworks) AppKit IOKit;
  };
}
```

**Comment by hzeller** [comment]
Thanks for the suggestion @peterhoeg - I've move the Darwin-related import to the all-packages.nix now

**Pull request merged**
