### PR TITLE
quarto: allow overriding extra R and Python packages

### PR DESCRIPTION
**Pull request by minijackson**
###### Description of changes

Tested by running a `.qmd` file needing ggplot2 and a `.qmd` file needing numpy and matplotlib.

Pinging @MrTarantoga

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by MrTarantoga** [comment]
Result of `nixpkgs-review pr 211941` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by MrTarantoga** [comment]
Do you have an idea why the command `nixpkgs-review pr 211941` seems to need 8 GB of memory?

**Comment by MrTarantoga** [comment]
Also quarto is not longer a part of PATH with your submission.

**Comment by minijackson** [comment]
That's very weird, if not overridden, it shouldn't change anything, as it's only concatenating an empty array.

> Also quarto is not longer a part of PATH with your submission.

What do you mean by that?

**Comment by MrTarantoga** [comment]
I my case, I add the package to the local scope and quarto is able to have access to them. Why to you want to have an override option?

**Comment by MrTarantoga** [comment]
> That's very weird, if not overridden, it shouldn't change anything, as it's only concatenating an empty array.
> 
> > Also quarto is not longer a part of PATH with your submission.
> 
> What do you mean by that?

As I said: I'm not able to run quarto inside 'nixpkgs-review pr 211941'. It is not part of the path. Also your change need a huge amount of memory during the nixpkgs-review command. Also I do not see the needs for the change, because quarto is part of python and R, so it should be added like other packages in one scope.

**Comment by minijackson** [comment]
If I want to execute render the [first R example](https://quarto.org/docs/computations/r.html) from the documentation, I need to have the `ggplot2` package available to R, which is not available by default.

If I install in my environment an R package with `ggplot2` installed, quarto won't use that, since the `QUARTO_R` set in the wrapper takes priority. I think it is the same with Python

**Comment by MrTarantoga** [comment]
Thats how the command is processed:

```
➜  nixpkgs git:(master) ✗ nixpkgs-review pr 211941
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/211941/head:refs/nixpkgs-review/1
remote: Enumerating objects: 776, done.
remote: Counting objects: 100% (632/632), done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 776 (delta 507), reused 503 (delta 431), pack-reused 144
Empfange Objekte: 100% (776/776), 771.39 KiB | 5.76 MiB/s, fertig.
Löse Unterschiede auf: 100% (510/510), abgeschlossen mit 206 lokalen Objekten.
Von https://github.com/NixOS/nixpkgs
   25eeb4785c80..ad8d5cf731e7  master                -> refs/nixpkgs-review/0
   a3b7b770cec9..02641062d16b  refs/pull/211941/head -> refs/nixpkgs-review/1
$ git worktree add /home/goetz/.cache/nixpkgs-review/pr-211941/nixpkgs ad8d5cf731e7d0b2d0cca148fa01b805c4f5d3a3
Bereite Arbeitsverzeichnis vor (losgelöster HEAD ad8d5cf731e7)
Aktualisiere Dateien: 100% (33335/33335), fertig.
HEAD ist jetzt bei ad8d5cf731e7 nixos/manual: clarify mk{Enable,Package}Option MD usage
$ nix-env --option system x86_64-linux -f /home/goetz/.cache/nixpkgs-review/pr-211941/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
$ git merge --no-commit --no-ff 02641062d16b84b74c708fb99041b0421253759f
Automatischer Merge abgeschlossen; halte, wie gewünscht, vor dem Commit an
$ nix-env --option system x86_64-linux -f /home/goetz/.cache/nixpkgs-review/pr-211941/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation --meta
derivation 'systemd-252.4' has invalid meta attribute 'badPlatforms'
derivation 'systemd-minimal-252.4' has invalid meta attribute 'badPlatforms'
derivation 'systemd-stage-1-252.4' has invalid meta attribute 'badPlatforms'
derivation 'systemd-stage-1-network-252.4' has invalid meta attribute 'badPlatforms'
Nothing to be built.

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/211941

$ /nix/store/pfaw5zpqfang1w1ms61lw8q60sg7fzxy-nix-2.12.0/bin/nix-shell /home/goetz/.cache/nixpkgs-review/pr-211941/shell.nix
these 37 paths will be fetched (66.61 MiB download, 306.07 MiB unpacked):
  /nix/store/04c0b1rmi9r6k9sl69a4gw3mhp3b5q2n-zlib-1.2.13
  /nix/store/117vi3xd5nm0ai52clm4w6ni9bdzixnm-glibc-2.35-224-bin
  /nix/store/178vvank67pg2ckr5ic5gmdkm3ri72f3-binutils-2.39
  /nix/store/2dpp3axxcm5w276xb4hmqgxf5whw8nrm-gnumake-4.4
  /nix/store/38db4p333ibll7r1v151yc5f6ms1fr00-bash-interactive-5.2-p15
  /nix/store/49zl26cmymymzzh1xqahd6cp1g10l141-glibc-2.35-224-dev
  /nix/store/4cjf65g6bacv9f279j5mv04iapzjx6m6-gnused-4.9
  /nix/store/7197cs5xf76z9r33nkm3xhkk800n0nr1-attr-2.5.1
  /nix/store/7nplxyjihfwhaw0cmrxwlfrq4xkbbz83-patch-2.7.6
  /nix/store/7xs3mva2z3z4hf48mh6d5alcin52qbm9-binutils-wrapper-2.39
  /nix/store/86gmg0dan51jsm3p2n2fnac1s8mq94i7-bzip2-1.0.8
  /nix/store/917bxk94dsm12bid472x3jpn4p512p7y-gmp-with-cxx-stage4-6.2.1
  /nix/store/96xa21yfzb43447lhmc76zg2628kvak4-readline-8.2p1
  /nix/store/b73ppzd6pcq3a8znjqjs5ivfdcxgz0rb-diffutils-3.8
  /nix/store/bw3mxk76xp3i5m53g9i67fagnwbhyc1k-xz-5.4.0
  /nix/store/chilfhdcsnmwjl7igrw26j1lrc0zar35-stdenv-linux
  /nix/store/g4qrlj5kr7iwcr81jsm1p55vk0z9rh0z-gnutar-1.34
  /nix/store/hcy4vanjxs86cynwn98hcagqyj3ihns4-gzip-1.12
  /nix/store/hm4l5k50h19k9285rp2p47a1z5ryyk9x-ed-1.18
  /nix/store/hr2vffa1w2ylqksrhg72p26ys8z930lh-expand-response-params
  /nix/store/iiq295j1z4q1sxmdbrl2j8ma3l5ns4wr-gcc-wrapper-11.3.0
  /nix/store/lx2yaqgvxhcwj65w65q539c2rgxh2bb7-pcre-8.45
  /nix/store/mhq6vmzb6w1q5kicv91x9ywqb57fb2x2-patchelf-0.15.0
  /nix/store/mlvjrnjdjj7p2dnsayy848yk7djgd5xk-findutils-4.9.0
  /nix/store/p3zp8ymx8rzc3q25jskg4hzz0kr5lyi1-xz-5.4.0-bin
  /nix/store/phwcwazlcabg1v6wwrdv6gr5mh2r3ld8-bzip2-1.0.8-bin
  /nix/store/pj1hnyxhcsw1krmhnbb9rjvqssbzliw8-bash-5.2-p15
  /nix/store/qn0xz86az3rcqfpfrcxhjiyp8s169792-file-5.43
  /nix/store/qrqwd1ji31vmas9gax819j11w5ickgz1-gnugrep-3.7
  /nix/store/r1lybmy0jzjsfcmbg24h26aknbgpfvad-coreutils-9.1
  /nix/store/sq78g74zs4sj7n1j5709g9c2pmffx1y8-gcc-11.3.0-lib
  /nix/store/v94mvmxwak89z8y1ijv1nhzp4j3h9jxm-ncurses-6.3-p20220507
  /nix/store/xm9x9kylgy1fq8xdw3z7irkrg57zh1h4-acl-2.3.1
  /nix/store/ycw1sij5z1kjcxdclz7gqlnf9hdxchlb-gawk-5.2.1
  /nix/store/yzjgl0h6a3qh1mby405428f16xww37h0-glibc-2.35-224
  /nix/store/z1yw9cw97bcdfmxz5wk7j1bycw42r1mw-gcc-11.3.0
  /nix/store/zzwqcifb2hgm1qii6ixh86cjryzlf5zh-linux-headers-6.1
copying path '/nix/store/yzjgl0h6a3qh1mby405428f16xww37h0-glibc-2.35-224' from 'https://cache.nixos.org'...
copying path '/nix/store/zzwqcifb2hgm1qii6ixh86cjryzlf5zh-linux-headers-6.1' from 'https://cache.nixos.org'...
copying path '/nix/store/7197cs5xf76z9r33nkm3xhkk800n0nr1-attr-2.5.1' from 'https://cache.nixos.org'...
copying path '/nix/store/pj1hnyxhcsw1krmhnbb9rjvqssbzliw8-bash-5.2-p15' from 'https://cache.nixos.org'...
copying path '/nix/store/86gmg0dan51jsm3p2n2fnac1s8mq94i7-bzip2-1.0.8' from 'https://cache.nixos.org'...
copying path '/nix/store/hm4l5k50h19k9285rp2p47a1z5ryyk9x-ed-1.18' from 'https://cache.nixos.org'...
copying path '/nix/store/hr2vffa1w2ylqksrhg72p26ys8z930lh-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/ycw1sij5z1kjcxdclz7gqlnf9hdxchlb-gawk-5.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/sq78g74zs4sj7n1j5709g9c2pmffx1y8-gcc-11.3.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/117vi3xd5nm0ai52clm4w6ni9bdzixnm-glibc-2.35-224-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/2dpp3axxcm5w276xb4hmqgxf5whw8nrm-gnumake-4.4' from 'https://cache.nixos.org'...
copying path '/nix/store/xm9x9kylgy1fq8xdw3z7irkrg57zh1h4-acl-2.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/phwcwazlcabg1v6wwrdv6gr5mh2r3ld8-bzip2-1.0.8-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/4cjf65g6bacv9f279j5mv04iapzjx6m6-gnused-4.9' from 'https://cache.nixos.org'...
copying path '/nix/store/hcy4vanjxs86cynwn98hcagqyj3ihns4-gzip-1.12' from 'https://cache.nixos.org'...
copying path '/nix/store/v94mvmxwak89z8y1ijv1nhzp4j3h9jxm-ncurses-6.3-p20220507' from 'https://cache.nixos.org'...
copying path '/nix/store/7nplxyjihfwhaw0cmrxwlfrq4xkbbz83-patch-2.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/g4qrlj5kr7iwcr81jsm1p55vk0z9rh0z-gnutar-1.34' from 'https://cache.nixos.org'...
copying path '/nix/store/lx2yaqgvxhcwj65w65q539c2rgxh2bb7-pcre-8.45' from 'https://cache.nixos.org'...
copying path '/nix/store/49zl26cmymymzzh1xqahd6cp1g10l141-glibc-2.35-224-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/bw3mxk76xp3i5m53g9i67fagnwbhyc1k-xz-5.4.0' from 'https://cache.nixos.org'...
copying path '/nix/store/04c0b1rmi9r6k9sl69a4gw3mhp3b5q2n-zlib-1.2.13' from 'https://cache.nixos.org'...
copying path '/nix/store/qn0xz86az3rcqfpfrcxhjiyp8s169792-file-5.43' from 'https://cache.nixos.org'...
copying path '/nix/store/qrqwd1ji31vmas9gax819j11w5ickgz1-gnugrep-3.7' from 'https://cache.nixos.org'...
copying path '/nix/store/p3zp8ymx8rzc3q25jskg4hzz0kr5lyi1-xz-5.4.0-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/178vvank67pg2ckr5ic5gmdkm3ri72f3-binutils-2.39' from 'https://cache.nixos.org'...
copying path '/nix/store/917bxk94dsm12bid472x3jpn4p512p7y-gmp-with-cxx-stage4-6.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/mhq6vmzb6w1q5kicv91x9ywqb57fb2x2-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/96xa21yfzb43447lhmc76zg2628kvak4-readline-8.2p1' from 'https://cache.nixos.org'...
copying path '/nix/store/z1yw9cw97bcdfmxz5wk7j1bycw42r1mw-gcc-11.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/r1lybmy0jzjsfcmbg24h26aknbgpfvad-coreutils-9.1' from 'https://cache.nixos.org'...
copying path '/nix/store/38db4p333ibll7r1v151yc5f6ms1fr00-bash-interactive-5.2-p15' from 'https://cache.nixos.org'...
copying path '/nix/store/b73ppzd6pcq3a8znjqjs5ivfdcxgz0rb-diffutils-3.8' from 'https://cache.nixos.org'...
copying path '/nix/store/mlvjrnjdjj7p2dnsayy848yk7djgd5xk-findutils-4.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7xs3mva2z3z4hf48mh6d5alcin52qbm9-binutils-wrapper-2.39' from 'https://cache.nixos.org'...
copying path '/nix/store/iiq295j1z4q1sxmdbrl2j8ma3l5ns4wr-gcc-wrapper-11.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/chilfhdcsnmwjl7igrw26j1lrc0zar35-stdenv-linux' from 'https://cache.nixos.org'...

[nix-shell:~/.cache/nixpkgs-review/pr-211941]$ quarto check all
The program 'quarto' is not in your PATH. You can make it available in an
ephemeral shell by typing:
  nix-shell -p quarto

[nix-shell:~/.cache/nixpkgs-review/pr-211941]$ exit
exit
$ git worktree prune
➜  nixpkgs git:(master) ✗ nixpkgs-review pr 211941
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/211941/head:refs/nixpkgs-review/1
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 31 (delta 22), reused 6 (delta 2), pack-reused 0
Entpacke Objekte: 100% (31/31), 6.22 KiB | 132.00 KiB/s, fertig.
Von https://github.com/NixOS/nixpkgs
   ad8d5cf731e7..3f3524a4473d  master     -> refs/nixpkgs-review/0
$ git worktree add /home/goetz/.cache/nixpkgs-review/pr-211941-1/nixpkgs 3f3524a4473d9f0502a45d8bb10e59ef587e2230
Bereite Arbeitsverzeichnis vor (losgelöster HEAD 3f3524a4473d)
Aktualisiere Dateien: 100% (33336/33336), fertig.
HEAD ist jetzt bei 3f3524a4473d nixos/autosuspend: init at version 4.3.0
$ nix-env --option system x86_64-linux -f /home/goetz/.cache/nixpkgs-review/pr-211941-1/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
$ git merge --no-commit --no-ff 02641062d16b84b74c708fb99041b0421253759f
Automatischer Merge abgeschlossen; halte, wie gewünscht, vor dem Commit an
$ nix-env --option system x86_64-linux -f /home/goetz/.cache/nixpkgs-review/pr-211941-1/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation --meta
derivation 'systemd-252.4' has invalid meta attribute 'badPlatforms'
derivation 'systemd-minimal-252.4' has invalid meta attribute 'badPlatforms'
derivation 'systemd-stage-1-252.4' has invalid meta attribute 'badPlatforms'
derivation 'systemd-stage-1-network-252.4' has invalid meta attribute 'badPlatforms'
Nothing to be built.

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/211941

$ /nix/store/pfaw5zpqfang1w1ms61lw8q60sg7fzxy-nix-2.12.0/bin/nix-shell /home/goetz/.cache/nixpkgs-review/pr-211941-1/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-211941-1]$ quarto check all
The program 'quarto' is not in your PATH. You can make it available in an
ephemeral shell by typ
```

**Comment by minijackson** [comment]
nixpkgs-review reports:

> Nothing to be built.

This is because this PR doesn't modify the quarto package if the package is not overridden, which is why nixpkgs-review doesn't try to build quarto: the hash is the same as on master. This is also why quarto is not part of your environment.

**Comment by MrTarantoga** [comment]
> If I want to execute render the [first R example](https://quarto.org/docs/computations/r.html) from the documentation, I need to have the `ggplot2` package available to R, which is not available by default.
> 
> If I install in my environment an R package with `ggplot2` installed, quarto won't use that, since the `QUARTO_R` set in the wrapper takes priority. I think it is the same with Python

I see, that would it make less hacky to add additional packages. Well know I see the usage, thank you.

**Comment by MrTarantoga** [comment]
> nixpkgs-review reports:
> 
> > Nothing to be built.
> 
> This is because this PR doesn't modify the quarto package if the package is not overridden, which is why nixpkgs-review doesn't try to build quarto: the hash is the same as on master. This is also why quarto is not part of your environment.

So you mean, I have to install quarto first and then review the changes?

**Comment by MrTarantoga** [comment]
Yepp, that's it. Now it works, a bit strange behavior of the review function, but anyway i have it for the future.

Thank you, for the suggestion!

**Review by MrTarantoga — APPROVED** [review]

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 211941` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
