### PR TITLE
numpy, scipy: Fix some nativeBuildInputs

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

`checkInputs` were not touched for now.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by FRidh — APPROVED** [review]

**Comment by FRidh** [comment]
Could you also look at scipy

**Comment by Ericson2314** [comment]
Sure!

**Review by FRidh — COMMENTED** [review]
Actually, something else. This will break the concept of `checkInputs`. We should think of a long-term solution to that.

**Comment by FRidh** [comment]
I suppose those can always be added to nativeBuildInputs

**Comment by Ericson2314** [comment]
I left `pycheck` in `checkInputs` for now and just moved `gfortran`. But yes, longer term `checkInputs` doesn't scale :/. I recall there is an issue on this.

**Pull request merged**
