### PR TITLE
Kernels 2021-06-18

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Review by fabianhjr — APPROVED** [review]
Changes LGTM, going to build 5.12.12-hardened.

**Comment by TredwellGit** [comment]
5.12.12 breaks networking for me.

**Comment by TredwellGit** [comment]
Likely related to changed errno codes: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.12.12

**Comment by fabianhjr** [comment]
Hi @TredwellGit, about to reboot into the new version. I normally use ethernet but would want to try to replicate the issue you encountered. Could you describe a bit about how you are connected to networking? (Ethernet, WiFi onboard, card or dongle, use or not use VPN, etc)

**Comment by fabianhjr** [comment]
Rebooted onto 5.12.12-hardened, network seems fine on my setup with both onboard ethernet and wifi (802.11ac 5GHz) both with or without VPN (private resources)

Pings, tracepath and bandwidth as expected.

**Comment by TredwellGit** [comment]
Ethernet, NetworkManager, and systemd-resolved.

**Comment by fabianhjr** [comment]
I don't use resolved but ethernet an networkmanager are working ok. Can't reproduce a networking issue on 5.12.12-hardened. UnU

**Comment by TredwellGit** [comment]
```
avahi-daemon[2090]: netlink.c: recvmsg() failed: Invalid argument
NetworkManager[2086]: <error> [1624064978.5210] platform-linux: netlink: read: failed to retrieve incoming events: Invalid argument (-22)
systemd-resolved[2082]: Failed to synthesize system hostname PTR RR: Invalid argument
systemd-resolved[2082]: Failed to synthesize system hostname PTR RR: Device or resource busy
```

**Comment by ymatsiuk** [comment]
NM+iwd no issue on 5.12.12 (no Ethernet to test 🤷🏻 )

**Comment by TredwellGit** [comment]
https://github.com/torvalds/linux/commit/8478b361dfc567d5b9506749ccd24c225cf9b530 is the bad commit.

**Comment by TredwellGit** [comment]
https://github.com/torvalds/linux/commit/d2e381c4963663bca6f30c3b996fa4dbafe8fcb5

**Comment by TredwellGit** [comment]
@gregkh please backport https://github.com/torvalds/linux/commit/d2e381c4963663bca6f30c3b996fa4dbafe8fcb5 to stable.

**Comment by gregkh** [comment]
On Mon, Jun 21, 2021 at 09:19:14AM -0700, TredwellGit wrote:
> @gregkh please backport https://github.com/torvalds/linux/commit/d2e381c4963663bca6f30c3b996fa4dbafe8fcb5 to stable.

<formletter>

This is not the correct way to submit patches for inclusion in the
stable kernel tree.  Please read:
    https://www.kernel.org/doc/html/latest/process/stable-kernel-rules.html
for how to do this properly.

</formletter>

**Comment by fabianhjr** [comment]
@TredwellGit, what is the NixOS policy regarding patching  distro-kernel releases? Seems like a revert to a patch in 5.12.12 that has already been reverted in a more recent 5.13-rc is quite reasonable.

**Comment by TredwellGit** [comment]
I am going to patch it, but am busy. I was hoping that gregkh would just include it in 5.12.13 instead of requiring going through the LKML, though.

**Comment by TredwellGit** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Comment by TredwellGit** [comment]
@ofborg build linux_xanmod linux_5_4 linux-libre linux_latest-libre

**Comment by gregkh** [comment]
On Mon, Jun 21, 2021 at 10:23:41AM -0700, TredwellGit wrote:
> I am going to patch it, but am busy. I was hoping that gregkh would just include it in 5.12.13 instead of requiring going through the LKML, though.

Did you read the process for asking for a patch to be included in a
stable release?  It is not hard at all, just a single email...

Oh well...

**Review by ymatsiuk — APPROVED** [review]

**Review by Ma27 — APPROVED** [review]

**Comment by 06kellyjac** [comment]
To me it looks like [option 2](https://www.kernel.org/doc/html/latest/process/stable-kernel-rules.html#option-2) would have covered it

Email `stable@vger.kernel.org`
Put a sensible subject
Explain in the email which commit you need back-ported to which release and why.

---

I started writing up the email but since it's been merged with the patch added I guess there's no point. :shrug:

**Comment by Ma27** [comment]
Oh I thought @TredwellGit wanted to take care of this :sweat_smile: . But of course we should still take care of this, if I interpret the issue correctly, we aren't the only ones affected by this and I guess it's always preferable to have as few patches on top of Linux as possible.

**Comment by 06kellyjac** [comment]
When a back-port is applied will it replace the existing `mirror://kernel/linux/kernel/v5.x/linux-X.Y.Z.tar.xz` file and require we update our `sha256`s, or just result in a new minor release?

I'm guessing we want it back-ported to all 3 that the patch is applied to: `5.4`, `5.10`, and `5.12`?

**Pull request merged**
