### PR TITLE
elixir: set version to latest / elixir_1_14

### PR DESCRIPTION
**Pull request by superherointj**
elixir: set version to latest / elixir_1_14

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 211133` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>akkoma</li>
    <li>elixir</li>
    <li>elixir_1_13</li>
    <li>elixir_ls</li>
    <li>mix2nix</li>
    <li>plausible</li>
    <li>pleroma</li>
    <li>sonic-pi</li>
  </ul>
</details>

**Review by bclaud — APPROVED** [review]

**Review by PedroHLC — APPROVED** [review]

**Comment by superherointj** [comment]
@happysalada Would you mind reviewing this?

**Comment by happysalada** [comment]
This looks good thanks ! There was a compilation failure at some point, but it looks like its gone , nice !

**Comment by superherointj** [comment]
Thanks @happysalada!

**Pull request merged**
