### PR TITLE
neovide: fixup, remove skia from store

### PR DESCRIPTION
**Pull request by kirillrdy**
###### Description of changes

currently the way neovide is packaged, puts skia source code in store, which is about 561Mb,

I am trying to allow skia source to be GC'ed once neovide is built.

If anyone can explain to me why something like this, still doesnt allow skia_source_dir derivation from being GC'ed ?
```
   buildPhase = ''
    export SKIA_SOURCE_DIR=${skia_source_dir}
    cargo build --release
  '';
''
```

cc @ck3d 

also happy to hear how we can improve on implementation

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ck3d** [comment]
I had a look how skia is built. Skia adds the paths to its sources, which prevents Nix to remove the dependency.
Your solution works as expected. Putting skia source from nix store to the build directory removes the dependency to the store path.
I developed a second way to solve this issue, please have a look at https://github.com/NixOS/nixpkgs/pull/195123

**Comment by kirillrdy** [comment]
@ck3d thanks for you reply, you solution is obviously better, and I will look up more about `removeReferencesTo`

Could you elaborate on how did you find that skia was holding references to source path ? I have had similar issues with some of my derivations, would be handly to understand better how it works,

Thanks in advance,

**Comment by kirillrdy** [comment]
closing in favor of https://github.com/NixOS/nixpkgs/pull/195123

**Comment by kirillrdy** [comment]
@ck3d  I see, it references source code files paths in the binary itself, and `remove-reference-to` replaces them with eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee, so filenames in error messages still preserved

**Comment by ck3d** [comment]
I searched in the build folder in all build artifacts of neovide for the path to sources (/nix/store/...-source). I created a build folder with nix-shell but nix-build -K should also be okay.

**Pull request closed without merging**
