### PR TITLE
nixos/pump.io: remove

### PR DESCRIPTION
**Pull request by rvl**
It would be nice to merge this before the feature freeze if possible.

###### Motivation for this change

This would probably be better maintained in a separate repo as an external NixOS module which gets imported into user's configuration.

Upstream is releasing fairly regularly but I doubt we have many/any NixOS users of this (I stopped using it anyway).

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adisbladis** [comment]
Could you add a a segment in the release notes about this module being dropped?

cc release managers @vcunat @fpletz

**Comment by rvl** [comment]
OK release notes added and rebased onto current master.

**Review by vcunat — APPROVED** [review]
I also removed the UID.

**Comment by rvl** [comment]
Thanks!

**Pull request merged**
