### PR TITLE
Workflow security fixes

### PR DESCRIPTION
**Pull request by infinisil**
At NixCon we've had 13x1 and @basti564 report security problems with some Nixpkgs workflows, thank you! See the commit messages and contents for more details.

I explained these changes to @Mic92, so that he could immediately merge it.

We disabled the old compromised workflows, so that they wouldn't run anymore for all branches.

Ping @NixOS/security

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by LeSuisse** [comment]
Thanks for the ping and backports. Does the app credential has been rotated?

(And arghhhhhh GHA are minefield for anything non trivial :/ )

**Comment by infinisil** [comment]
@LeSuisse No need to, the private key couldn't be leaked, while the tokens generated from it are revoked after the workflow completes, and if something went wrong in 1 hour at the latest.

**Comment by infinisil** [comment]
And yeah GitHub Actions are a tricky beast, I'm very thankful to have been made aware of these problems!

**Comment by 13x1** [comment]
Hi there! Since this was a pretty big security issue, I thought I'd ask: Would this (and the accommodating talk at the last NixCon) be enough for a voucher for this NixCon for us? I can't use the voucher website since at the time I lost access to this GitHub account, but I think we have made a pretty big contribution (despite the unfortunate circumstances with GitHub) with this :) 

cc @infinisil

**Comment by LeSuisse** [comment]
I would suggest asking directly the Nixcon 2025 org team at nixcon@nixos.org

You are more likely to get an answer, I tend to ignore old PRs from my notifications (and I suppose I'm not the only one).

**Pull request merged**
