### PR TITLE
mysql_tzinfo_to_sql errors with tzdata 2013f and above

### PR DESCRIPTION
**Pull request by ip1981**

### CODE REVIEW

**Comment by ip1981** [comment]
```
[pashev@nixos:~/nixpkgs]$ /nix/store/l9wcg5md0c01jhfmk943ygf9b67gxli0-mysql-5.1.73/bin/mysql_tzinfo_to_sql /nix/store/m4fgmmsnl8wkmxzvas3kv71sa13v6mj4-tzdata-2014j/share/zoneinfo/ >/dev/null
Warning: Unable to load '/nix/store/m4fgmmsnl8wkmxzvas3kv71sa13v6mj4-tzdata-2014j/share/zoneinfo//iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/nix/store/m4fgmmsnl8wkmxzvas3kv71sa13v6mj4-tzdata-2014j/share/zoneinfo//posix/iso3166.tab' as time zone. Skipping it.
Warning: Skipping directory '/nix/store/m4fgmmsnl8wkmxzvas3kv71sa13v6mj4-tzdata-2014j/share/zoneinfo//posix/posix': to avoid infinite symlink recursion.
Warning: Unable to load '/nix/store/m4fgmmsnl8wkmxzvas3kv71sa13v6mj4-tzdata-2014j/share/zoneinfo//posix/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/nix/store/m4fgmmsnl8wkmxzvas3kv71sa13v6mj4-tzdata-2014j/share/zoneinfo//posix/zone1970.tab' as time zone. Skipping it.
Warning: Unable to load '/nix/store/m4fgmmsnl8wkmxzvas3kv71sa13v6mj4-tzdata-2014j/share/zoneinfo//zone.tab' as time zone. Skipping it.
Warning: Unable to load '/nix/store/m4fgmmsnl8wkmxzvas3kv71sa13v6mj4-tzdata-2014j/share/zoneinfo//zone1970.tab' as time zone. Skipping it.
```

**Comment by ip1981** [comment]
@shlevy ?

**Comment by ip1981** [comment]
@rickynils ?

**Comment by shlevy** [comment]
@ip1981 should this be applied to master too?

**Comment by joachifm** [comment]
Is this still relevant?

**Comment by ip1981** [comment]
Mariadb is fine. Can't tell on mysql.

**Pull request closed without merging**
