### PR TITLE
Fix clang OpenMP build of openblas and suitesparse

### PR DESCRIPTION
**Pull request by nh2**
See #79818.

Tested with:

```
NIX_PATH=nixpkgs=. nix-build --no-link --expr "with import <nixpkgs> {}; [ (suitesparse.override { stdenv = pkgs.clangStdenv; }) (openblas.override { stdenv = pkgs.clangStdenv; }) ]"
```

I tested on `linux-x86_64` only.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg build python310Packages.numpy

Fails for me on macos 10.15

**Comment by nh2** [comment]
> Fails for me on macos 10.15

@risicle What errors do you see?

On orborg I see only timeouts: https://github.com/NixOS/nixpkgs/pull/264194/checks?check_run_id=18165868284

I have no macOS so will need some feedback from macOS users.

**Comment by risicle** [comment]
Appears to work for me now.

**Comment by nh2** [comment]
@ofborg build python310Packages.numpy

**Comment by nh2** [comment]
Looks like it should still go to staging due to the mass rebuilds.

**Comment by nh2** [comment]
Rebased. Also fixed the `10.rebuild-linux: 101-500 ` on GCC (`suitesparse` `openmp` should have been conditional on `clang`).

**Comment by nh2** [comment]
The ofborg build is failing because LLVM itself is failing to build there (probably a `staging` issue?).

https://logs.ofborg.org/?key=nixos/nixpkgs.264194&attempt_id=2ac51d6d-0092-49a7-9b73-a134cb39998f

This change should be reasonably benign, so merging it now based on @risicle's feedback above where it worked on `master`.

**Pull request merged**
