### PR TITLE
mindustry: 141.2 -> 142

### PR DESCRIPTION
**Pull request by TheKostins**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fgaz** [comment]
Your maintainer entry should be added in alphabetical order

**Comment by fgaz** [comment]
Please squash the commits

**Comment by TheKostins** [comment]
Sorry for delay, squashed

**Review by fgaz — APPROVED** [review]
Thanks!

**Comment by chkno** [comment]
I'm not sure why the bot tried to backport this to 22.11?

* This doesn't need to be backported to release-22.11 because it already was: https://github.com/NixOS/nixpkgs/pull/220024
* If release-22.11 really needs a mindustry update, it would be https://github.com/NixOS/nixpkgs/pull/225703 142 -> 143.1 and then https://github.com/NixOS/nixpkgs/pull/233553 143.1 -> 144.3
    * But release-22.11 probably doesn't need a mindustry update because 22.11 is only supported [for another two weeks](https://nixos.org/manual/nixos/stable/release-notes.html#sec-release-22.11)
* release-23.05 is at 143.1 and master/unstable is at 144.3.  If any backports are needed, it would be https://github.com/NixOS/nixpkgs/pull/233553 143.1 -> 144.3 into release-23.05
* 144.3 is currently the latest upstream release.

**Comment by fgaz** [comment]
The same happened in https://github.com/NixOS/nixpkgs/pull/235817#issuecomment-1589767924

Maybe it's a bug in the bot: when labels are updated it runs again, cc @Janik-Haag

**Pull request merged**
