### PR TITLE
pyopenssl: 0.15.1 -> 16.0.0

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

certbot fails with this log:

```
======================================================================
ERROR: test_valid_true (certbot.tests.crypto_util_test.ValidPrivkeyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-certbot-0.6.0.drv-0/certbot-v0.6.0-src/certbot/tests/crypto_util_test.py", line 162, in test_valid_true
    self.assertTrue(self._call(RSA256_KEY))
  File "/tmp/nix-build-certbot-0.6.0.drv-0/certbot-v0.6.0-src/certbot/tests/crypto_util_test.py", line 159, in _call
    return valid_privkey(privkey)
  File "/tmp/nix-build-certbot-0.6.0.drv-0/certbot-v0.6.0-src/certbot/crypto_util.py", line 200, in valid_privkey
    OpenSSL.crypto.FILETYPE_PEM, privkey).check()
  File "/...-python2.7-pyopenssl-0.15.1/lib/python2.7/site-packages/OpenSSL/crypto.py", line 243, in check
    if _lib.EVP_PKEY_type(self._pkey.type) != _lib.EVP_PKEY_RSA:
AttributeError: '_cffi_backend.CDataGCP' object has no attribute 'type'
```

http://hydra.nixos.org/build/38387037/nixlog/3

This was fixed in pyca/pyopenssl#406 and pyca/pyopenssl@f8b29ba535b6748941e78eb6eaf504095d14bd12
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This will fix the error in certbot.

http://hydra.nixos.org/build/38387037/nixlog/3

### CODE REVIEW

**Comment by CorbinSimpsonAcquia** [comment]
This may also fix the `tahoelafs` package, which fails tests on Hydra due to PyOpenSSL errors.

**Comment by MostAwesomeDude** [comment]
This might fix `tahoelafs`, which is also broken right now. (The root cause, I believe, is a failure to keep PyOpenSSL and Cryptography in sync.)

**Comment by FRidh** [comment]
Quite some packages are effected by this update. As soon as the Hydra job for https://github.com/NixOS/nixpkgs/pull/17430 is finished I'll run one with this update.

**Comment by FRidh** [comment]
Hydra job is running https://headcounter.org/hydra/eval/329901

**Comment by FRidh** [comment]
- searx depends on pyopenssl==0.15.1, so we either need to keep that one, or test whether we can patch pyopenssl. https://headcounter.org/hydra/build/1225527
- service-identity fails as well. https://headcounter.org/hydra/build/1225537 . We might want to update it https://pypi.org/project/service_identity/

**Comment by FRidh** [comment]
Hydra is done. Its only the two packages I mentioned before that need to be fixed. When that is done this can be merged.

**Comment by matthewbauer** [comment]
Well, if those two packages aren't updatable, you can probably just apply this commit as patch:

pyca/pyopenssl@f8b29ba

**Comment by MostAwesomeDude** [comment]
Please do update service_identity. Its purpose, from their docs: "TL;DR: Use this package if you use pyOpenSSL and don’t want to be MITMed."

They dropped 2.6 and 3.3 support. Dunno if you need to flag that anywhere.

**Comment by matthewbauer** [comment]
This should be ready to merge now.

**Comment by FRidh** [comment]
Thanks for the updates!

**Pull request merged**
