### PR TITLE
lxqt: use qt5's mkDerivation

### PR DESCRIPTION
**Pull request by worldofpeace**
#### Motivation for this change
Wrap lxqt applications https://github.com/NixOS/nixpkgs/issues/65399 https://github.com/NixOS/nixpkgs/issues/65399#issuecomment-515706258

LXQT now starts in a vm for me, however there seems to be something up with the
theme and or icons.

#### Appearance before wrapQtAppsHook
Screenshot from 2019-07-27 17 30 32

#### Appearance after wrapQtAppsHook
Screenshot from 2019-07-27 17 32 12

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by romildo** [comment]
> LXQT now starts in a vm for me, however there seems to be something up with the
> theme and or icons.

Idem.

**Comment by worldofpeace** [comment]
cc @ttuegel any idea what's going wrong here?

Currently this is broken, and it's not a good shape for the release or users.

**Comment by ttuegel** [comment]
What theme package is used, and how is it installed?

**Comment by worldofpeace** [comment]
These packages appear to be installed as pre-requisites

```
pkgs.gvfs # virtual file systems support for PCManFM-QT
pkgs.libsForQt5.kwindowsystem # provides some QT5 plugins needed by lxqt-panel
pkgs.libsForQt5.libkscreen # provides plugins for screen management software
pkgs.libfm
pkgs.libfm-extra
pkgs.lxmenu-data
pkgs.menu-cache
pkgs.openbox # default window manager
pkgs.qt5.qtsvg # provides QT5 plugins for svg icons
```

and I'm assuming the theming package would be `lxqt-themes`.

**Comment by ttuegel** [comment]
I investigated this a little. It's unfortunately difficult to diagnose because applications seem to load their themes correctly, it's just the desktop that's the problem, and the desktop doesn't send logs to the system journal.

**Comment by ttuegel** [comment]
I think the default settings are just scrambled somehow. If I set the panel background color and the launcher icon, then everything seems to work OK; it looks like the defaults just aren't initialized correctly.

**Comment by worldofpeace** [comment]
> I think the default settings are just scrambled somehow. If I set the panel background color and the launcher icon, then everything seems to work OK; it looks like the defaults just aren't initialized correctly.

Ahh, I think I thought of the same thing. What operation does the application do to modify those things? If it's something environmental it can go in the session script, or maybe something is up the the `startlxqt` script in `lxqt-session`.

**Comment by ttuegel** [comment]
> What operation does the application do to modify those things? If it's something environmental it can go in the session script, or maybe something is up with the `startlxqt` script in `lxqt-session`.

My best guess (unvalidated, at the moment) is that there is a "default" configuration file that ships with LXQT. The changes to the Qt wrappers might have broken the resolution of that file's name. Without the default file, the panel's color is "uninitialized"; IIRC the uninitialized `QColor` is all zeros, i.e. black.

**Comment by worldofpeace** [comment]
So it does appear that the script for the environmental initialzation has an issue
```
if [ -z "$XDG_CONFIG_DIRS" ]; then
    export XDG_CONFIG_DIRS="/etc:/nix/store/hypj40wbcl8i9rl2b1915m4ny2yq28kg-lxqt-build-tools-0.6.0/etc/xdg:/var/empty/share"
else
    if ! contains "$XDG_CONFIG_DIRS" '/nix/store/hypj40wbcl8i9rl2b1915m4ny2yq28kg-lxqt-build-tools-0.6.0/etc/xdg'; then
        XDG_CONFIG_DIRS="$XDG_CONFIG_DIRS:/nix/store/hypj40wbcl8i9rl2b1915m4ny2yq28kg-lxqt-build-tools-0.6.0/etc/xdg"
    fi
fi
```

The nix store paths to `lxqt-build-tools` should be from within `lxqt-session`. Probably need to fix the cmake files.
As for where the it gets its settings, I'm pretty sure it's within `lxqt-session` and resolves it through the standard directories that could have gotten scrambled.

**Comment by worldofpeace** [comment]
So in the process of debugging this it appears I've fixed a separate issue https://github.com/NixOS/nixpkgs/pull/65482/commits/e34de045b65ac7b812d980df85204644baeb60c9 that doesn't produce the effects that I want :frowning: 

With the paths corrected in the script this still occurs.

I've tried actually disabling `wrapQtAppsHook` from exporting `XDG*` variables by commenting it out and I didn't eliminate the issue, so perhaps this isn't caused from the wrapping?

##### are there environment variables I can set to get debug messages?

**Comment by globin** [comment]
Can we merge this and fix up the theming in a new PR, it's rather annoying if one's terminal doesn't start...

**Comment by worldofpeace** [comment]
@globin That's fine, I'm mostly holding off because this is a pretty ugly regression for users of the desktop.

**Comment by globin** [comment]
Well it doesn't seem to work at all currently so this definitely should be an improvement already?

**Comment by worldofpeace** [comment]
No disagreement there @globin. I just need someone to review my new changes then.

**Comment by agaida** [comment]
> My best guess (unvalidated, at the moment) is that there is a "default" configuration file that ships with LXQT. The changes to the Qt wrappers might have broken the resolution of that file's name. Without the default file, the panel's color is "uninitialized"; IIRC the uninitialized `QColor` is all zeros, i.e. black.

@ttuegel - you are right

**Comment by scobiehague** [comment]
[quote]If I set the panel background color and the launcher icon, then everything seems to work OK; it looks like the defaults just aren't initialized correctly.[/quote]

It seems more is broken with the panel when I compare the appearance with screenshots of how themes should look. For instance, no border colour is applied to the panel, which can make it look off.

Also, many icons are missing from the generated start menus (even though they appear correctly in the taskbar), so it looks bad to the point of being unusuable for daily use. Are there any partially fixed versions around I can use?

**Comment by romildo** [comment]
I could not find a fix for this issue yet. As a workaround one can set the foreground and/or background colors in the lxqt panel properties.

**Comment by scobiehague** [comment]
> As a workaround one can set the foreground and/or background colors in the lxqt panel properties.

As there are other theme attributes LXQT applies to the panel, aside from colour, this is only a partial workaround. It isn't a massive deal, but [here](https://lensdump.com/i/lxqt-working.j9V97Z) is a screenshot of an LXQT theme I use on a laptop not switched over to NixOS yet. Notice the 3D border of the panel edge. [Here](https://lensdump.com/i/lxqt-broke.j9VJxc) is the same theme on NixOS. The panel is cutoff where the 3D border should appear, which is not as the theme author intended, and inconsistent with the widget theme by the same author.

Hopefully I will figure out a fix soon.

**Comment by lordcirth** [comment]
When I was looking at this a while ago, it seemed that the theme paths were getting rewritten to the lxqt package, rather than the themes package.

**Comment by worldofpeace** [comment]
@lordcirth I believe that was fixed in https://github.com/NixOS/nixpkgs/pull/65482/commits/e34de045b65ac7b812d980df85204644baeb60c9

**Comment by romildo** [comment]
> @lordcirth I believe that was fixed in [e34de04](https://github.com/NixOS/nixpkgs/commit/e34de045b65ac7b812d980df85204644baeb60c9)

It was not.

See https://github.com/NixOS/nixpkgs/pull/65482#issuecomment-523750315 onward.

**Comment by scobiehague** [comment]
Any themes installed by the package show in the preferences window to change themes, but do not get applied when selected. Themes installed in ~/.local/share/lxqt/themes also show, and also do not get applied when selected.

**Pull request merged**
