### PR TITLE
elmPackages: updates with node2nix 1.9.0

### PR DESCRIPTION
**Pull request by turboMaCk**
Periodical update of elm-packages. Fixes https://github.com/NixOS/nixpkgs/pull/110845 following upgrade of node2nix from https://github.com/NixOS/nixpkgs/pull/110813#pullrequestreview-575830796

Notable changes:

- elm-test no longer needs patch for elmi-to-json binary
- create-elm app no longer needs patch for elmi-to-json binary
- elm-review no longer needs patch for elmi-to-json binary
- remove `linux` platform constrain from `elm-json` since we now support at least a Darwin since https://github.com/NixOS/nixpkgs/pull/110598

tested:

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @svanderburg

### CODE REVIEW

**Comment by turboMaCk** [comment]
@GrahamcOfBorg build elmPackages

**Comment by turboMaCk** [comment]
@GrahamcOfBorg build elmPackages

**Comment by turboMaCk** [comment]
@GrahamcOfBorg build elmPackages

**Comment by turboMaCk** [comment]
cc @domenkozar & @svanderburg for review

**Comment by akoppela** [comment]
Thank you sirs!

**Pull request merged**
