### PR TITLE
haskell.compiler: stop reliance on LLVM 6 & 7; haskell.compiler.ghc884: remove at 8.8.4; llvmPackages_7: remove at 7.1.0

### PR DESCRIPTION
**Pull request by sternenseemann**
## Description of changes

cc @RaitoBezarius 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by RaitoBezarius — APPROVED** [review]
Looks good to me, thank you.

**Comment by sternenseemann** [comment]
cc @amjoseph-nixpkgs for GHC 8.6.5 changes

**Comment by sternenseemann** [comment]
Also I'd like someone to look over the alias stuff and suggest something for the release notes. Maybe it's easier to do the LLVM removals separately?

**Comment by maralorn** [comment]
LGTM. Just curious, why are we keeping LLVM 6?

**Comment by sternenseemann** [comment]
@ofborg build maude, root5

**Comment by sternenseemann** [comment]
Can someone test this for maude/root5 on darwin?

```nix
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 3ac47ca930d5..550200c6e8fa 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -17733,7 +17733,7 @@ with pkgs;
   ### End of CuboCore
 
   maude = callPackage ../development/interpreters/maude {
-    stdenv = if stdenv.cc.isClang then llvmPackages_7.stdenv else stdenv;
+    stdenv = if stdenv.cc.isClang then llvmPackages_6.stdenv else stdenv;
   };
 
   me_cleaner = callPackage ../tools/misc/me_cleaner { };
@@ -40003,7 +40003,7 @@ with pkgs;
 
   root5 = lowPrio (callPackage ../applications/science/misc/root/5.nix {
     inherit (darwin.apple_sdk.frameworks) Cocoa OpenGL;
-    stdenv = if stdenv.cc.isClang then llvmPackages_7.stdenv else stdenv;
+    stdenv = if stdenv.cc.isClang then llvmPackages_6.stdenv else stdenv;
   });
 
   rinetd = callPackage ../servers/rinetd { };
```

**Comment by veprbl** [comment]
No objection to root5 change from me.

**Comment by amjoseph-nixpkgs** [comment]
> cc @amjoseph-nixpkgs for GHC 8.6.5 changes

I have no objections.

The contraption using ancient (gentoo?) powerpc64le binaries to bootstrap ghc just isn't sustainable.

We need to invest in being able to cross-compile ghc (i.e. build a `build!=(host==target)` compiler).  Any other strategy for non-x86_64/aarch64 platforms isn't a good use of resources in the long run.

**Pull request merged**
