### PR TITLE
qutebrowser: shorten launch time marginally if an instance is already running

### PR DESCRIPTION
**Pull request by ldesgoui**
###### Motivation for this change

`qutebrowser` can be made considerably faster to launch if an instance is already running, this method is documented in one of the scripts provided by the package:
https://github.com/qutebrowser/qutebrowser/blob/master/scripts/open_url_in_instance.sh
Basically, socat is used to make an IPC call.

I've left it disabled by default because the behavior changes if an instance is already running, the initial call would block until the program is stopped, whereas a call to the IPC would exit immediately after having transmitted. This is, however, common to major browsers such as `chromium`.
The optimization is disabled if `qutebrowser` is called with flags.

`socat` adds ~700kb to the 6.7mb derivation

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ldesgoui** [comment]
I'm not pleased with how I measured, but I guess it's accurate enough:
without the optimization, a process takes ~1600ms to reach a page, and with it, it takes ~180ms

**Comment by ldesgoui** [comment]
@jagajaga Any thoughts on having it enabled by default ?

**Comment by xeji** [comment]
@GrahamcOfBorg build qutebrowser

**Comment by Infinisil** [comment]
Setting `withSocatTrick = true` currently requires rebuilding the whole qutebrowser derivation. I propose to make a wrapper derivation instead, which just takes the binary from the original derivation and wraps it into its own $out. Then a rebuild isn't needed when a user sets this flag to true.

**Comment by matthewbauer** [comment]
Would it be possible to just get qutebrowser to come with a flag to do this? This isn't really something I like having Nixpkgs deal with.

**Pull request closed without merging**
