### PR TITLE
wordnet: Fix darwin build

### PR DESCRIPTION
**Pull request by anka-213**
###### Motivation for this change

Building on darwin was failing with error:
```
14 warnings generated.
clang  -g -O2   -o wishwn  wishwn-tkAppInit.o wishwn-stubs.o -L../lib -lWN -L/nix/store/vmpwxmns16dhv0d1nhyaxjxwjwzazp52-tk-8.6.9/lib -ltk
ld: framework not found Cocoa
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```
This patch adds the missing dependency on darwin.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
@grahamcOfBorg build wordnet

**Comment by anka-213** [comment]
Btw, should I add myself as a maintainer, since there is none currently?

**Comment by vcunat** [comment]
Yes, I think so.

Borg doesn't have a darwin builder anymore and that doesn't seem like it will be fixed soon.

**Comment by rnhmjoj** [comment]
> Btw, should I add myself as a maintainer, since there is none currently?

If you care about this package yes, please go on and add yourself. There are lots of orphaned packages in Nixpkgs that needs some love.

ofBorg didn't manage to built this on darwin yet, must be stuck or very overloaded. I'll take your word it builds because I have no other means to test this.

**Comment by rnhmjoj** [comment]
> Borg doesn't have a darwin builder anymore and that doesn't seem like it will be fixed soon.

Ah, I didn't know that. That's sad.

**Comment by rnhmjoj** [comment]
So, should I go on and merge or are you adding yourself to the maintainers list?

**Comment by vcunat** [comment]
Well, `meta.maintainers` can be extended anytime later, let's not keep this rotting.

**Pull request merged**
