### PR TITLE
vimPlugins.vim-DetectSpellLang: init at 2020-01-13

### PR DESCRIPTION
**Pull request by GovanifY**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
I wonder if we should patch the plugin here to depend on aspell https://github.com/Konfekt/vim-DetectSpellLang/blob/master/plugin/detectspelllang.vim#L16

**Comment by GovanifY** [comment]
@symphorien This should now take care of that.

**Comment by GovanifY** [comment]
@symphorien Can you please review again this PR?

**Comment by symphorien** [comment]
Hmm actually the patch was a bad idea it generates an error:
```
Erreur détectée en traitant function detectspelllang#detectspelllang :
ligne   23 :
E15: Expression invalide : g:detectspelllang_langs./nix/store/l9rzczak0chmxc92p6fwg243ks6p3024-aspell-0.60.8/bin/aspell
```

because of https://github.com/Konfekt/vim-DetectSpellLang/blob/master/autoload/detectspelllang.vim#L24

so g:detectspelllang_program should stay "aspell".

Let's not patch the plugin at all and sorry for the wrong review.

**Comment by GovanifY** [comment]
@symphorien removed the patch, should be good now!

**Pull request merged**
