### PR TITLE
graalvm8-19.2.1 buildfix

### PR DESCRIPTION
**Pull request by hlolli**
###### Motivation for this change

Hydra build failures on linux https://hydra.nixos.org/build/118583841 and darwin https://hydra.nixos.org/build/118579881

###### Things done

* fix xcode build related bug on darwin
* print graalvm-native build log by default
* fix graal-nodejs runner shortcut

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ludovicc** [comment]
Failed to build on Darwin:

`nix-shell -p nixpkgs-review --run "nixpkgs-review pr 87958"`

[...]

```
$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /Users/lclaude/.cache/nixpkgs-review/pr-87958/build.nix
builder for '/nix/store/fmgshivpz9h1bp3hyymbs59sljw3j9b2-jvmci-19.3-b05.drv' failed with exit code 1; last 10 log lines:
    File "/nix/store/g03a391s1w7gxnffgyns3gw3w5y5yykw-mx-5.247.1/bin/internal_mx.py", line 6863, in prepare
      self.compiler.prepare_daemon(daemons, self.compileArgs)
    File "/nix/store/g03a391s1w7gxnffgyns3gw3w5y5yykw-mx-5.247.1/bin/internal_mx.py", line 7206, in prepare_daemon
      self.daemon = JavacDaemon(self.jdk, jvmArgs)
    File "/nix/store/g03a391s1w7gxnffgyns3gw3w5y5yykw-mx-5.247.1/bin/internal_mx.py", line 7319, in __init__
      CompilerDaemon.__init__(self, jdk, jvmArgs, 'com.oracle.mxtool.compilerserver.JavacDaemon', jdk.toolsjar, ['--force-javac'])
    File "/nix/store/g03a391s1w7gxnffgyns3gw3w5y5yykw-mx-5.247.1/bin/internal_mx.py", line 7255, in __init__
      raise RuntimeError('Error starting ' + self.name() + ': returncode=' + str(returncode) + '\n' + ''.join(pout))
  RuntimeError: Error starting javac-daemon: returncode=1

cannot build derivation '/nix/store/bkfyqmbp03fav9a43czppb9dz0k3qwrd-graal-19.2.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/cywkwgm3w89z90l7kgzlkanayg2siyyn-clj-kondo-2019.12.14.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7mlvcrfvbrgi51df2xq3ahid1w69hkps-env.drv': 2 dependencies couldn't be built
[1 built (1 failed), 196 copied (2312.8 MiB), 625.9 MiB DL]
error: build of '/nix/store/7mlvcrfvbrgi51df2xq3ahid1w69hkps-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/87958
2 packages failed to build:
clj-kondo graalvm8

[0.0 MiB DL]
error: build log of '/nix/store/cywkwgm3w89z90l7kgzlkanayg2siyyn-clj-kondo-2019.12.14.drv' is not available
[0.0 MiB DL]
error: build log of '/nix/store/bkfyqmbp03fav9a43czppb9dz0k3qwrd-graal-19.2.1.drv' is not available
$ nix-shell /Users/lclaude/.cache/nixpkgs-review/pr-87958/shell.nix
these paths will be fetched (1.46 MiB download, 7.85 MiB unpacked):
  /nix/store/02n29ivj4fcpyhj8wh1simy08lxg2pmr-bash-interactive-4.4-p23-dev
  /nix/store/bl9zgywn70jbm2wf9qmhhpswj3dvl2hn-bash-interactive-4.4-p23-doc
  /nix/store/i3bf9dywv5j6wbpw32j3v2i2k07dxsl4-bash-interactive-4.4-p23-info
  /nix/store/kpmw1b9sbh5hy67p0slvgfjrdiqbw6z7-bash-interactive-4.4-p23
  /nix/store/qf3g0lgkn57wd0n3fixfmq3g57xnjn3k-bash-interactive-4.4-p23-man
  /nix/store/zgkasmai95mm4ibdjj0iv5j8aigyikas-readline-7.0p5
copying path '/nix/store/bl9zgywn70jbm2wf9qmhhpswj3dvl2hn-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/i3bf9dywv5j6wbpw32j3v2i2k07dxsl4-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/qf3g0lgkn57wd0n3fixfmq3g57xnjn3k-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/zgkasmai95mm4ibdjj0iv5j8aigyikas-readline-7.0p5' from 'https://cache.nixos.org'...
copying path '/nix/store/kpmw1b9sbh5hy67p0slvgfjrdiqbw6z7-bash-interactive-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/02n29ivj4fcpyhj8wh1simy08lxg2pmr-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...

```

**Comment by Mic92** [comment]
@GrahamcOfBorg build graalvm8

**Comment by hlolli** [comment]
@ludovicc I'm curious to see what @grahamc does. This would be the jvmci which is failling for you, that's a relief imo. Why it's failing is hard to say, but I'm not sure this will work sandboxed on darwin, since it's using /Libraries/Java modules built into the macos system. I'm not a osx expert, but I have one and will test again soon.

**Comment by Mic92** [comment]
I think ofborg does build with sandbox on macOS.

**Comment by conferno** [comment]
> I think ofborg does build with sandbox on macOS

AFAIK, it does but the list of people who can trigger Darwin build is limited

**Comment by Mic92** [comment]
@conferno I am on the list but the builder does not process any builds at the moment.

**Comment by SuperSandro2000** [comment]
Due to the number of PRs nixpkgs gets every month we didn't review and merge this on in time before 20.03 hit EOL. If you think this PR is still relevant please rebase it on master or 20.09 and leave a comment.

**Pull request closed without merging**
