### PR TITLE
Remove more GraalVM references

### PR DESCRIPTION
**Pull request by jcf**
## Description of changes

Same issue as https://github.com/NixOS/nixpkgs/issues/269029 but with clojure-lsp, cljfmt, jet and zprint.

Based on feedback, the removal of references to the GraalVM derivation now takes place in the shared GraalVM builder.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jcf** [comment]
Is it worth adding tests to these packages? I see cljfmt has a version test that would be eesy to replicate.

**Comment by jcf** [comment]
I've added the tests based on my reading of the docs. I hope they're useful. Happy to remove if they're not.

**Comment by bennyandresen** [comment]
LGTM. (Only tested it on x86_64-linux however.)

**Review by ericdallo — APPROVED** [review]

**Comment by jcf** [comment]
Why did @ofborg request a review from @ericdallo after Eric had approved?

Anything more I can do to get this one merged, @thiagokokada? 🙏

**Review by thiagokokada — CHANGES_REQUESTED** [review]
I thought this was less widespread than this.

If this is affecting all binaries the best way to fix is to add it to the `buildGraalvmNativeImage` builder instead.

**Comment by jcf** [comment]
> I thought this was less widespread than this.
> 
> If this is affecting all binaries the best way to fix is to add it to the `buildGraalvmNativeImage` builder instead.

@thiagokokada I’ll see what I can later today. Watch this space!

**Comment by jcf** [comment]
@thiagokokada as requested, I've combined the reference-removal logic.

And I've built packages locally to verify that both references to GraalVM are removed and that any provided `postInstall` is combined correctly.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
