### PR TITLE
home-assistant: 0.86.4 -> 0.87.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
This breaks zoneminder as camera/switch/sensor.zoneminder has moved under the zoneminder component:

```
error: attribute 'camera.zoneminder' missing, at /home/peter/src/active/nixpkgs_unstable/pkgs/servers/home-assistant/default.nix:82:28
```

So ```parse-requirements.py``` changes from ```camera.zoneminder``` to ```zoneminder.camera``` although it should be ```camera.zoneminder```.

**Comment by dotlambda** [comment]
How does `camera.zoneminder` get into your `extraComponents`?

**Comment by dotlambda** [comment]
@peterhoeg Did you check again?

**Comment by peterhoeg** [comment]
I haven't tried, sorry.

**Comment by peterhoeg** [comment]
This is what is going on:

https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

**Comment by dotlambda** [comment]
I see. Maybe `parse-requirements.py` will have to be rewritten.
However, the only way I can think of how your error can occur is by *manually* adding `camera.zoneminder` to `extraComponents`.

**Comment by dotlambda** [comment]
@peterhoeg I found the cause of the error. Seems like it's the same as in https://github.com/NixOS/nixpkgs/issues/55958. Sorry for that.

**Comment by dotlambda** [comment]
@peterhoeg 753f58d has made it into the `nixos-18.09` channel. Could you upgrade your system and try this PR again?

**Comment by peterhoeg** [comment]
Now the re-organized components are fine, but ffmpeg and unifi are broken (might be their python packages that need updating). And of course 0.88 is out...

**Comment by dotlambda** [comment]
@netixx I think my last commit should make `mqtt.sensor` be picked up with your configuration.

@peterhoeg SO, would you be fine with merging this as is? I'd prefer to merge before tackling 0.88.

**Comment by dotlambda** [comment]
@peterhoeg I pushed two Python package updates that may fix ffmpeg and unifi. You're sure aiounifi, which isn't yet packaged, isn't needed for the unifi component to work at all? https://github.com/home-assistant/home-assistant/blob/0.87.1/requirements_all.txt#L136

**Comment by netixx** [comment]
It will be difficult for me to test this because my setup is a little bit complicated, but you'd just have to define `platform=mqtt` for a sensor to test it. 

By the way I had an import error for `aiounifi` using unify device_tracker platform, along with `pyunifi`- so I can sort of confirm both are needed!

**Comment by dotlambda** [comment]
> It will be difficult for me to test this because my setup is a little bit complicated, but you'd just have to define `platform=mqtt` for a sensor to test it.

I tested it with the configuration you provided in #55958 and can confirm that `mqtt.sensor` is picked up.

**Comment by peterhoeg** [comment]
#56508 for unifi/ffmpeg

**Comment by dotlambda** [comment]
I'll merge this within the next 12 hours if noone objects.

**Comment by dotlambda** [comment]
What do you think about backporting 971187e to 19.03?

**Pull request merged**
