### PR TITLE
remove mutt-kz: deprecated in favor of neomutt

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
How about https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L13959

**Comment by Mic92** [comment]
@peterhoeg  The reasoning of the pull request author refers to project headline, which states that mutt-kz as deprecated: https://github.com/karelzak/mutt-kz

**Comment by peterhoeg** [comment]
@Mic92 , absolutely, but the PR doesn't remove the reference from ```all-packages.nix``` which is what I wanted to point out.

**Comment by Mic92** [comment]
@peterhoeg ah ok, the link highlighted neomutt for me - and I did not even noticed mutt-kz one line above.

**Pull request closed without merging**
