### PR TITLE
Clean up / normalize java references and make icedtea the default jre / jdk

### PR DESCRIPTION
**Pull request by wkennington**

### CODE REVIEW

**Comment by wkennington** [comment]
Anyone using OSX able to build icedtea with the osx openjdk? Or is OSX stuck with openjdk at this point?

**Comment by edolstra** [comment]
What's the motivation for using icedtea instead of openjdk?

**Comment by 7c6f434c** [comment]
>What's the motivation for using icedtea instead of openjdk?

A random big package is more likely to work with icedtea than with
openjdk (for VUE and Apache Jena I tried using OpenJDK, failed, and had
to switch to IcedTea; are there examples of things broken by IcedTea?).
There are some quirks in openjdk like expecting user-writeable 
/etc/.java directory. It looks like icedtea in general is about taking
openjdk releases and fixing annoying problems...

**Comment by edolstra** [comment]
I don't have a /etc/.java and I've never had issues with that.

**Comment by 7c6f434c** [comment]
>I don't have a /etc/.java and I've never had issues with that.

Some version of VUE with some version of OpenJDK did require it; then it
stopped working but openjdk->icedtea change helped.

/jdk/src/solaris/classes/java/util/prefs/FileSystemPreferences.java
has references to /etc/.java/ and I was in a situtation where it 
actually lead to attempts to write to the /etc/.java/ directory.

**Comment by wkennington** [comment]
My motivation is somewhat similar. Iced tea provides a small set of patches
on top of a hand picked stable openjdk release. This gives some additional
functionality to bring openjdk more in line with oraclejdk. On top of this
it makes sense from an end user standpoint since it means they don't need a
copy of openjdk in their nix store when pulling from cache. Ideally we
would do away with openjdk entirely as many other distros already have. I
wonder if we could build iced tea with the openjdk bootstrap kit instead of
openjdk itself.

**Comment by wizeman** [comment]
I also use Icedtea as my default JDK /JRE. My motivation was due to security concerns, because at the time I created the Icedtea derivations it seemed that Icedtea was putting out releases with security fixes far more frequently than OpenJDK.

Although, now that I look into it again, it could simply have been that I've always been really confused about the OpenJDK release process, since I can't seem to figure out where to look for OpenJDK releases, release notes, or which version I should be using...

**Pull request closed without merging**
