### PR TITLE
Backport haskell backpack and profiling fixes

### PR DESCRIPTION
**Pull request by shlevy**
Jobset at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates-18.09

### CODE REVIEW

**Comment by shlevy** [comment]
@samueldr @vcunat Please advise on timing for merging this.

**Comment by samueldr** [comment]
I'm not familiar with mass rebuilds (if this is one), and the usual timings and such. Any tip?

**Comment by shlevy** [comment]
This is a mass-haskell rebuild. I created the relevant hydra jobset already and the cache is mostly populated.

There's been some discussion around this lately so it might have changed, but in the past we've just merged major rebuilds into staging (or, for haskell, haskell-updates), then when the relevant jobset stabilized and binaries uploaded anyone could just merge it into master or the relevant release branch. Since we're still in release prep mode I didn't want to just merge in churn unwarned, though.

**Comment by vcunat** [comment]
Ah, yes, timing seems good.  I've been falling behind updates.  There's this tarball problem blocking channels on both master and 18.09 anyway...

**Pull request merged**
