### PR TITLE
Pipewire 21.05 backport: 0.3.30 -> 0.3.33

### PR DESCRIPTION
**Pull request by domenkozar**
cc @Kranzes @jtojnar

### CODE REVIEW

**Comment by jansol** [comment]
Diff looks good at a glance. Also that's one epic reviewer list.

**Comment by Kranzes** [comment]
This backport seems to be missing the last commit i have made to 0.3.33 in unstable, which includes the updated json config files.

**Comment by domenkozar** [comment]
Thanks @Kranzes anzes :)

**Review by Kranzes — APPROVED** [review]
Looks good.

**Comment by domenkozar** [comment]
Works well for me :)

**Pull request merged**
