### PR TITLE
Damien/riot 1.6

### PR DESCRIPTION
**Pull request by DamienCassou**
###### Motivation for this change

New version of riot: 
- https://github.com/vector-im/riot-web/releases/tag/v1.6.0
- https://blog.riot.im/e2e-encryption-by-default-cross-signing-is-here/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Already done in bc6bad222e6d52491a2c4c8c95c598bf73e7949e, b9787479e2972110bce73f99a1a620f710ea4476

**Comment by DamienCassou** [comment]
Result of `nixpkgs-review pr 87135` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by DamienCassou** [comment]
@Ma27 I haven't seen any PR including these commits. Were they pushed directly to the master branch?

**Comment by Ma27** [comment]
Yes. Was a fairly trivial update of a leaf-package :)

**Pull request closed without merging**
