### PR TITLE
rust-analyzer: 2021-08-30 -> 2021-09-06

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ckiee — CHANGES_REQUESTED** [review]
I can reproduce the same hashes but the `update.sh` script was not ran so versions aren't bumped everywhere.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 137015` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>rust-analyzer</li>
    <li>rust-analyzer-unwrapped</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
  </ul>
</details>

**Comment by Mic92** [comment]
I run the update script, does this also mean I need to bump node packages?

**Comment by happysalada** [comment]
unfortunately yes.

**Review by ckiee — APPROVED** [review]
Diff matches `update.sh` diff now.

**Comment by Mic92** [comment]
I currently upgrade nodepackages as well.

**Comment by Mic92** [comment]
There you go.

**Comment by happysalada** [comment]
Thank you for this!

**Pull request merged**
