### PR TITLE
git-up: 1.4.2 -> 1.6.1

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
fixing @r-ryantm update failures.

bumped python2 to python3
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @peterhoeg

### CODE REVIEW

**Comment by peterhoeg** [comment]
Why not just change ```python2Packages``` to ```python3Packages```?

**Comment by peterhoeg** [comment]
@fridh, do you prefer the derivation to be specific about the python version (```python2Packages``` vs ```python3Packages```), or simply to take a ```pythonPackages``` and then have ```all-packages.nix``` override accordingly?

**Comment by mmahut** [comment]
@GrahamcOfBorg build git-up

**Review by ck3d — APPROVED** [review]
tested executable bin/git-up

**Comment by mmahut** [comment]
Please fix the merge conflict.

**Comment by jonringer** [comment]
@GrahamcOfBorg build git-up

rebased off master

**Review by Lassulus — APPROVED** [review]
tested with nix-review, run nix-up on nixpkgs which failed with `Failed to rebase upstream/release-18.09 onto 18.09` and then tested it on some other repos which worked ok.

**Pull request merged**
