### PR TITLE
nh_plus: init at 3.6.0-0

### PR DESCRIPTION
**Pull request by ToyVo**
there currently exists `programs.nh.package` that can be set to this. For nix-darwin to get similar options, nh_plus exists to support nix-darwin.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ToyVo** [comment]
@drupol you are marked as a maintainer for base nh, so I figure you are a good person to ping.

**Review by drupol — CHANGES_REQUESTED** [review]
Hello @viperML,

I am wondering if merging the changes from this fork in the original project wouldn't be a better idea than maintaining 2 similar software.

@ToyVo : The PR must have 2 commits. The first one must be: `maintainers: add Toyvo`, the second one must be the rest.

**Comment by viperML** [comment]
I would be happy to wait for @ToyVo pull request merging their darwin impl. I'm preparing for NH 4.0 release that removes the hard dependency on flakes.

**Comment by ToyVo** [comment]
I can work on another pr to bring in my changes but the reason why this was separate was because the changes were rejected once https://github.com/viperML/nh/issues/67 & https://github.com/viperML/nh/pull/97

**Comment by viperML** [comment]
You can base your changes from here: https://github.com/viperML/nh/compare/master...darwin

**Comment by drupol** [comment]
It's nice to see that you're finding a cleaner solution ! How about closing this issue and wait for proper support in `nh` then?

**Comment by ToyVo** [comment]
yeah, the nix-darwin support is merged into master and will be there for the 4.0 release

**Comment by Eveeifyeve** [comment]
> yeah, the nix-darwin support is merged into master and will be there for the 4.0 release

Make sure when 4.0 releases, archive  nh_plus and say darwin support has been implemented in nh.

**Pull request closed without merging**
