### PR TITLE
kdeApplications: kcalcore dependencies fix

### PR DESCRIPTION
**Pull request by nyanloutre**
###### Motivation for this change

kcalcore seems to be abandoned in favor of kcalendarcore

I still have errors compiling `kitinerary` but could not identify whout would cause that. As a consequence `kdepim-addons` is not building either.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by nyanloutre** [comment]
@grahamcofborg build kdeApplications.kitinerary

**Comment by worldofpeace** [comment]
@nyanloutre we updated poppler and it broke it, see https://github.com/KDE/kitinerary/commit/5e001bf0cc7651c4cbc2c43f4fc14e41bbfc71d6.
That patch doesn't apply though, but the conflict is just an include.
But even after this it doesn't build because other fixes need to be applied related to poppler.


Perhaps we can just override `src` to the latest released version.

**Comment by nyanloutre** [comment]
We can also update the KDE apps directly to 19.12: https://kde.org/announcements/releases/19.12/

**Comment by worldofpeace** [comment]
> We can also update the KDE apps directly to 19.12: https://kde.org/announcements/releases/19.12/

Sounds good, this fix isn't blocking staging next is it though?

**Comment by nyanloutre** [comment]
I don't think this fix should block staging next as the only packages failing to build are kitinerary and kdepim-addons which are not used in any other packages

**Comment by worldofpeace** [comment]
> I don't think this fix should block staging next as the only packages failing to build are kitinerary and kdepim-addons which are not used in any other packages

Ah ok. I thought there were failures in staging-next that broke the plasma5 test in deps chain.

**Pull request merged**
