### PR TITLE
tor-browser-bundle-bin: rewrite using fhs-user-env approach

### LINKED ISSUE #83096: Tor Browser: add-ons disabled on start
**Describe the bug**
In Tor Browser, all add-ons, including HTTPS Everywhere and NoScript are disabled when you start up the browser. 

**To Reproduce**
1. Ensure you have Tor Browser 9.0.6 (from 20.03 or unstable).
2. Right-click on the starting page. 
3. Observe that the "NoScript" option is missing.

**Expected behavior**
All add-ons should be enabled on startup.

**Additional context**
This appears to be a regression since 9.0.5 introduced in https://github.com/NixOS/nixpkgs/pull/82754

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.24-gnu, NixOS, 20.03beta591.99a3d7a86fc (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta695.b2935fbecea, u-20.09pre217526.9b3515eb95d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixos.tor-browser-bundle-bin
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by xaverdh**
###### Motivation for this change

Fix #83096

This amounts to a complete change of how we package the tor browser bundle. Instead of keeping it in the store, and fixing things after the fact, it creates an `fhs-user-env`, copies the upstream runtime into the local data path and runs it inside that environment.

This has some implications:
* Updating (after the initial setup) is done by the browser itself. This is an implementation details and could probably be changed with some effort, if that's desired. (Note to self: need to test if auto-update works)
* We have to somehow deal with people transitioning from the old wrapper.. currently the approach of this pr is to ~~nuke the old tor-browser data (except for the top level Downloads folder – if present)~~ error out if an old profile is detected and delegate migration to the user.  Suggestions on handling this more gracefully are appreciated here.
* I tried to keep some level of API compat between the old wrapper and the new interface, but whether this is desired is probably debatable.
* I started from scratch mostly (except for the prior art of @yurkobb [here](https://github.com/NixOS/nixpkgs/pull/102622)), which means that *some things* may not work (yet) as they used to. I count on *your feedback* to help fix this ;-)

Most importantly I would like to get some feedback from some of the current maintainers, if this approach seems sane. I also added myself as maintainer of this package, in case we agree that its the right way to proceed.

cc @offline @matejc @doublec @thoughtpolice @joachifm @hax404 @cap @KarlJoad

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yurkobb** [comment]
Hi and thanks for working on this!

I think maybe it would be safer to just issue an error and exit if there is a previous TBB in a users' $HOME rather than nuking it.

Although Tor Browser is very much about resetting to a clean state frequently, there are valid use cases for storing some long-term data in the profile, like bookmarks. Users with stored bookmarks might want to export them first.

**Comment by xaverdh** [comment]
> Hi and thanks for working on this!
> 
> I think maybe it would be safer to just issue an error and exit if there is a previous TBB in a users' $HOME rather than nuking it.
> 

^^ I implemented this approach, does seem safer.

One issue currently is that it crashes with something glib / gtk related when opening / saving a file.

**Comment by xaverdh** [comment]
Ok, the crashes were related to `XDG_DATA_DIRS` missing some stuff. Copied the relevant parts from the old wrapper and it works now.

**Comment by chkno** [comment]
This seems antithetical to reproducibility.  Before this change, the binary that runs is the one specified in configuration & verified by hash.  After this change, the binary that runs is whatever the auto-update server last sent, & will change from run to run.

This describes a `tor-browser-bundle-bin`*`-installer`*, not the `tor-browser-bundle-bin`.  If folks find value in having this, great, but please don't replace `tor-browser-bundle-bin` with it.

**Comment by yurkobb** [comment]
I support naming the this package differently, but I recommend keeping `tor-browser-bundle-bin` marked broken, since although its binary is reproducible, its behavior and state is not at all (mission-critical addons randomly disabled / crashing).

In general few distributions package Tor Browser itself; some package [torbrowser-launcher](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=torbrowser) instead, which does a similar job as this package - initially downloading tbb.

I would name this package `tor-browser-installer`.

**Comment by xaverdh** [comment]
Well this could also be extended to **not** use the built in auto-update mechanism and instead do updates in the start script if applicable. But if https://github.com/NixOS/nixpkgs/pull/103570 fixes the issue I will close this anyway. Might still be useful to pick up in the future tough, when mozilla decides to further "lock down" the browser, and remove the remaining methods of sideloading extensions.

**Comment by yurkobb** [comment]
Hm, what if we had both options available to the users? Can we have this package as well, perhaps under `tor-browser-bundle-bin-mutable` name?

I imagine there might be some people who would like to have a mutable Tor Browser installation (i.e. as close to the original Tor Browser). One use case is being able to update immediately via Tor Browser itself.

**Comment by xaverdh** [comment]
> Hm, what if we had both options available to the users? Can we have this package as well, perhaps under `tor-browser-bundle-bin-mutable` name?
> 
> I imagine there might be some people who would like to have a mutable Tor Browser installation (i.e. as close to the original Tor Browser). One use case is being able to update immediately via Tor Browser itself.

Agreed. With #103570 merged, I will close this pr and open a new one for a mutable variant of the tor browser bundle.
@yurkobb would you like to help maintain it, if it gets merged?

**Comment by yurkobb** [comment]
> > Hm, what if we had both options available to the users? Can we have this package as well, perhaps under `tor-browser-bundle-bin-mutable` name?
> > I imagine there might be some people who would like to have a mutable Tor Browser installation (i.e. as close to the original Tor Browser). One use case is being able to update immediately via Tor Browser itself.
> 
> Agreed. With #103570 merged, I will close this pr and open a new one for a mutable variant of the tor browser bundle.
> @yurkobb would you like to help maintain it, if it gets merged?

If I can be useful, yes, although my knowledge of the internals of firefox's profiles is near zero. But I can do simple updates I guess.

**Pull request closed without merging**
