### PR TITLE
caligula: init at 0.4.5

### PR DESCRIPTION
**Pull request by sodiboo**
## Description of changes

Caligula is a user-friendly, lightweight TUI for disk imaging.

https://github.com/ifd3f/caligula

While it works on my machine, which is an `x86_64-linux`, Caligula also supports macOS. I've copied the required frameworks from [the official flake](https://github.com/ifd3f/caligula/blob/edd8b153479302e8f7f613d9fc81169555a54299/nix/cross-helpers.nix#L53-L56), but it is important to note that **i do not own an `{x86_64,aarch64}-darwin` machine to test on**.

cc @ifd3f; you said on mastodon that you were interested in also maintaining the package? can you test that it works on macOS?

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ifd3f** [comment]
@sodiboo yes, I can add myself as a maintainer in separate PR.

I've tested and it builds and runs on x86_64-darwin and aarch64-darwin.

**Comment by sodiboo** [comment]
> it has that bug that prevents it from being used on disks in MacOS Sonoma

is that a bug upstream? or indirectly introduced by this package, specifically?

> Wonder if it's possible to mark those versions as broken for now?

That seems to be possible. From the manual:

> If a program ought to work on a certain platform, but doesn’t, the platform should be included in `meta.platforms`, but marked as broken with e.g. `meta.broken = !hostPlatform.isWindows`.

I didn't include `meta.platforms` because i didn't understand it (and my attempts at using it resulted in build failures), but i looked through some other packages now and found out how to actually use it lol. I can add the correct platforms and also mark it as broken on darwin

**Comment by sodiboo** [comment]
> is that a bug upstream? or indirectly introduced by this package, specifically?

actually i Looked At Your Issues™ and found it's https://github.com/ifd3f/caligula/issues/105, right?

**Comment by ifd3f** [comment]
> actually i Looked At Your Issues™ and found it's [ifd3f/caligula#105](https://github.com/ifd3f/caligula/issues/105), right?

Yes, that's the one.

**Review by hacker1024 — APPROVED** [review]

**Pull request merged**
