### PR TITLE
ffmpeg_7: 7.0.2 -> 7.1; xeve: 0.5.0 -> 0.5.1

### PR DESCRIPTION
**Pull request by emilazy**
I’ll look into upstreaming the tests fix some other time.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
@Atemu @jopejoe1 Any objections to just merging this? It looks like, in classic FFmpeg fashion, [they’ve broken at least one API](https://github.com/AirenSoft/OvenMediaEngine/pull/1626#issuecomment-2395079229), but I expect it to be less bad than 6 → 7 which has gone smoothly so far, and it’d be nice to ship 24.11 on the latest release.

**Review by Atemu — APPROVED** [review]
Diff LGTM.

The changelog looks small enough and odd API breakages like that one can only really be found by pushing this to unstable.

I'd like to see the patch upstreamed though.

**Comment by Atemu** [comment]
Result of `nixpkgs-review pr 346552 --checkout commit` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>ffmpeg_7-full</li>
    <li>ffmpeg_7-full.bin (ffmpeg_7-full.bin.bin ,ffmpeg_7-full.bin.data ,ffmpeg_7-full.bin.dev ,ffmpeg_7-full.bin.doc ,ffmpeg_7-full.bin.lib ,ffmpeg_7-full.bin.man)</li>
    <li>ffmpeg_7-full.data (ffmpeg_7-full.data.bin ,ffmpeg_7-full.data.data ,ffmpeg_7-full.data.dev ,ffmpeg_7-full.data.doc ,ffmpeg_7-full.data.lib ,ffmpeg_7-full.data.man)</li>
    <li>ffmpeg_7-full.dev (ffmpeg_7-full.dev.bin ,ffmpeg_7-full.dev.data ,ffmpeg_7-full.dev.dev ,ffmpeg_7-full.dev.doc ,ffmpeg_7-full.dev.lib ,ffmpeg_7-full.dev.man)</li>
    <li>ffmpeg_7-full.doc (ffmpeg_7-full.doc.bin ,ffmpeg_7-full.doc.data ,ffmpeg_7-full.doc.dev ,ffmpeg_7-full.doc.doc ,ffmpeg_7-full.doc.lib ,ffmpeg_7-full.doc.man)</li>
    <li>ffmpeg_7-full.lib (ffmpeg_7-full.lib.bin ,ffmpeg_7-full.lib.data ,ffmpeg_7-full.lib.dev ,ffmpeg_7-full.lib.doc ,ffmpeg_7-full.lib.lib ,ffmpeg_7-full.lib.man)</li>
    <li>ffmpeg_7-full.man (ffmpeg_7-full.man.bin ,ffmpeg_7-full.man.data ,ffmpeg_7-full.man.dev ,ffmpeg_7-full.man.doc ,ffmpeg_7-full.man.lib ,ffmpeg_7-full.man.man)</li>
  </ul>
</details>

**Comment by emilazy** [comment]
The FFmpeg site is down right now. I’ll put myself through finally learning `git send-email` when it comes back up.

**Comment by emilazy** [comment]
Patch sent upstream as https://patchwork.ffmpeg.org/project/ffmpeg/patch/20241006230501.51183-1-ffmpeg@emily.moe/.

**Pull request merged**
