### PR TITLE
Add Lykos153 to maintainer-list.nix

### PR DESCRIPTION
**Pull request by Lykos153**
svn path=/nixpkgs/branches/0.5-stable/; revision=993

###### Description of changes
Add Lykos153 to maintainer-list.nix

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
Are you planning on maintaining anything? People usually add themselves to the maintainers team for that reason.

**Review by Atemu — CHANGES_REQUESTED** [review]
Please use the template and read it carefully.

**Comment by Lykos153** [comment]
Yes I do. Should I include my entry in `maintainer-list.nix` in my first package submission?

Added the template back in, but I can't see how any of it applies.

**Comment by Atemu** [comment]
> Should I include my entry in `maintainer-list.nix` in my first package submission?

Yes, that's how it's usually done.

> Added the template back in, but I can't see how any of it applies.

Please read [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

**Comment by Lykos153** [comment]
I see, then I'll do it that way. Creating a separate PR just appeared a bit cleaner to me, but I'm sorry to have caused more annoyance than necessary.

FWIW I've read the template, CONTRIBUTING.md (twice, actually, precisely to find out wheater a separate PR would be more appropriate or not) and also the "Submitting changes" section of the nixpkgs manual.

**Comment by Atemu** [comment]
Please read the section pertaining commit messages again. It should be something along these lines: `maintainers: add Lykos153`.

**Pull request closed without merging**
