### PR TITLE
Do not verify SSL peer when fetching sources

### PR DESCRIPTION
**Pull request by kirelagin**
I would be greatful if as many people as possible could review this pull request as it potentially has security implications.

The idea is that we check the hashes of sources after fetching them, so there is no need to verify the SSL peer when making the connection. For example, `fetchurl` uses the `--insecure` option in order to make `curl` skip verification. Additionally, this way we get rid of the `pkgs.cacert` dependency in some places.

Fetchers that use `pkgs.cacert`:

* [x] `fetchgit` (tested)
* [ ] `fetchrepoproject` (can someone test the change please?)
* [ ] `docker/pull.{nix,sh}` (something crazy is going on there)
* [ ] `fetchbower` (haven’t looked yet)
* [ ] `fetchdarcs` (looks like there is no way to disable)
* [ ] `fetchgx` (haven’t looked yet)
* [ ] `fetchcargo` (haven’t looked yet)

Various other places, which I haven’t looked at yet:

~~~~
pkgs/applications/networking/browsers/chromium/update.nix:          if SSL_CERT_FILE="${cacert}/etc/ssl/certs/ca-bundle.crt" \
pkgs/applications/networking/remote/citrix-receiver/default.nix:    awk 'BEGIN {c=0;} /BEGIN CERT/{c++} { print > "cert." c ".pem"}' < ${cacert}/etc/ssl/certs/ca-bundle.crt
pkgs/build-support/rust/default.nix:    export SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt
pkgs/development/compilers/go/1.7.nix:  NIX_SSL_CERT_FILE = "${cacert}/etc/ssl/certs/ca-bundle.crt";
pkgs/development/compilers/go/1.8.nix:  NIX_SSL_CERT_FILE = "${cacert}/etc/ssl/certs/ca-bundle.crt";
pkgs/development/compilers/mono/generic.nix:    $out/bin/cert-sync ${cacert}/etc/ssl/certs/ca-bundle.crt
pkgs/development/compilers/openjdk/7.nix:      perl ${./generate-cacerts.pl} $jre/lib/openjdk/jre/bin/keytool ${cacert}/etc/ssl/certs/ca-bundle.crt
pkgs/development/compilers/openjdk/8.nix:      perl ${./generate-cacerts.pl} $jre/lib/openjdk/jre/bin/keytool ${cacert}/etc/ssl/certs/ca-bundle.crt
pkgs/development/compilers/rust/beta.nix:      export SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt
pkgs/development/compilers/rust/cargo.nix:      --set CARGO_HTTP_CAINFO "${cacert}/etc/ssl/certs/ca-bundle.crt" \
pkgs/development/compilers/rust/cargo.nix:      --set SSL_CERT_FILE "${cacert}/etc/ssl/certs/ca-bundle.crt" \
pkgs/development/compilers/rust/cargo.nix:    export SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt
pkgs/development/compilers/rust/nightly.nix:      export SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt
pkgs/development/haskell-modules/generic-stack-builder.nix:  GIT_SSL_CAINFO = "${cacert}/etc/ssl/certs/ca-bundle.crt";
pkgs/development/libraries/openssl/use-etc-ssl-certs-darwin.patch:+#  define X509_CERT_FILE          "/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt"
pkgs/development/libraries/qt-5/5.6/qtwebengine/default.nix:    sed -i -e 's,/cert.pem,/certs/ca-bundle.crt,' src/3rdparty/chromium/third_party/boringssl/src/crypto/x509/x509_def.c
pkgs/games/factorio/fetch.sh: --cacert $cacert/etc/ssl/certs/ca-bundle.crt \
pkgs/servers/xmpp/ejabberd/default.nix:    GIT_SSL_CAINFO = "${cacert}/etc/ssl/certs/ca-bundle.crt";
~~~~

I strongly suspect that some of those usages are either not needed or are plain wrong, given all that movement with `NIX_SSL_CERT_FILE` and attempts to make packages behave use trusted roots from the system as opposed to pulling `pkgs.cacert`.

### CODE REVIEW

**Comment by kirelagin** [comment]
More details on `fetchdarcs`. Darcs uses libcurl and there is no code in Darcs that would make it possible to configure libcurl to skip peer verification (this has to be done by calling `curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, FALSE)`). I also don’t think there is a way to influence the options of libcurl via environment, so it looks like, indeed, the only choice we have is to allow darcs to verify its peers.

**Comment by 7c6f434c** [comment]
I think we have a larger problem of expectation mismatch… It is sometimes very convenient to just bump the version in the expression and get the hash from the error message. But fetchurl doesn't verify SSL certificates, so this workflow is insecure…

**Comment by kirelagin** [comment]
@7c6f434c Yeah, you are right. This is a troubling issue indeed, although, honestly, I don’t think it is critical. Even if the original author of the expression gets MITMed, others will quickly figure this out.

But it would much better if there was a warning or even if the verification was automatically switched all somehow when updating expressions... Not sure how this would work. Do you wanna file a separate issue? :)

**Comment by 7c6f434c** [comment]
>@7c6f434c Yeah, you are right. This is a troubling issue indeed, although, honestly, I don’t think it is critical. Even if the original author of the expression gets MITMed, others will quickly figure this out.
>
>But it would much better if there was a warning or even if the verification was automatically switched all somehow when updating expressions... Not sure how this would work. Do you wanna file a separate issue? :)

Well, nix-prefetch-git is even more annoying to use than 
nix-prefetch-url so I decided to comment on the «not needed anyway» 
here, mostly so that this statement doesn't get to be written without
the fine print. If I had a _good_ solution I would probably have 
committed it already, also not sure what should happen…

**Comment by shlevy** [comment]
Strongly opposed to this. I'd rather not give any MITM insight into which specific github repos I'm downloading, thanks.

**Comment by kirelagin** [comment]
@shlevy Can you please submit a negative review so that it is clearly visible?

An opposite option would be to _modify `fetchurl`_ and all the other `fetch*` functions to make sure they are forcing TLS verification. The question then is which bundle of root certificates do we want to use when fetching? These have to be system-independent, otherwise this would be an impurity (admittedly a minor one). And we will have to make sure that path to the bundle does not get stored in the binaries. See also #8247.

**Review by shlevy — CHANGES_REQUESTED** [review]
Result integrity is not the only reason to use SSL. We shouldn't expose the specific packages our users download to a clever enough MITM

**Comment by vcunat** [comment]
It would be impurity in the sense of failure vs. success, not in the sense of getting a different output.

**Comment by volth** [comment]
Doesn't it just fall back to download from ```tarballs.nixos.org/${hash}``` in case of SSL error on the upstream's server ?

**Comment by vcunat** [comment]
IIRC nixos.org is tried *first*.

**Review by grahamc — CHANGES_REQUESTED** [review]
I disagree for several reasons:

1. Authenticity is just one feature of SSL, the privacy of our users is also paramount.
2.  Our update strategy is frequently TOFU, or"break the hash then use the fixed one," and I don't want to require a user upstream their packages in order for them to find out their upgrade was pwned.
3. cacert is a dependency of the fixed output derivation, which means if cacert changes all fixed outputs don't have to be updated.

I think the upsides here are very minimal, for potentially tragic downsides.

**Comment by FlorentBecker** [comment]
Should we just close this?

**Comment by fpletz** [comment]
I don't think that most project members and users will agree to this change.

**Pull request closed without merging**
