### PR TITLE
python312Packages.pprintpp: drop nose dependency

### PR DESCRIPTION
**Pull request by Sigmanificient**
## Description of changes

- #326513

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — COMMENTED** [review]
There’s a fork, https://github.com/joaonc/pprintpp2, that contains a port to pytest. It looks like upstream [was interested in merging its changes](https://github.com/wolever/pprintpp/pull/30), but it never happened. Maybe we should switch to that fork, or at least source the pytest patch from `9c65ae8e89ddb71d58153b1531dc969a5948d244`. I see that you have some tests seemingly working that are skipped in that patch, although I also wonder if the parameterized tests are actually getting run correctly in this version? https://github.com/wolever/parameterized/issues/167 suggests that the library they use might not work with current pytest versions.

I need to sleep soon so I’ll dig into this further another day unless you beat me to it.

**Comment by Sigmanificient** [comment]
I saw the fork, but wasn't sure about switching to it like this

**Comment by emilazy** [comment]
You can use `excludes` to skip those files, although I think that we should certainly source this from GitHub, as there are patches even beyond the last release (0.4.0, which this is behind).

I think switching to the fork and giving it a `0.4.0-unstable-YYYY-MM-DD` version is the best option, given that the upstream maintainer showed intent to merge its changes but then never got around to it; that’s approval enough for me. We could drop our existing patches and this new one, although it might be preferable to keep some of your changes if they allow running tests that are disabled in the fork.

**Comment by Sigmanificient** [comment]
Let's do that then!

**Review by emilazy — CHANGES_REQUESTED** [review]
The check inputs disappeared?

**Comment by Sigmanificient** [comment]
Seems like the forks has the same issue has me:  `2 passed, 3 deselected, 3 xfailed, 3 warnings in 0.24s`

**Comment by Sigmanificient** [comment]
> That seems okay? `xfailed` tests are meant to fail. Can you share the build log?

Woops I think the important part is this:
```
=============================== warnings summary ===============================
../../nix/store/xkdqvv523lvzaxkqy4rn1y60yflax19m-python3.11-nose-1.3.7/lib/python3.11/site-packages/nose/plugins/manager.py:418
  /nix/store/xkdqvv523lvzaxkqy4rn1y60yflax19m-python3.11-nose-1.3.7/lib/python3.11/site-packages/nose/plugins/manager.py:418: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

../../nix/store/xkdqvv523lvzaxkqy4rn1y60yflax19m-python3.11-nose-1.3.7/lib/python3.11/site-packages/nose/importer.py:12
  /nix/store/xkdqvv523lvzaxkqy4rn1y60yflax19m-python3.11-nose-1.3.7/lib/python3.11/site-packages/nose/importer.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
    from imp import find_module, load_module, acquire_lock, release_lock

test.py:81
  test.py:81: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_unicode will be ignored
    @parameterized([

test.py:92
  test.py:92: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_back_and_forth will be ignored
    @parameterized([

test.py:139
  test.py:139: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_expected_input will be ignored
    @parameterized([

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by emilazy** [comment]
That looks like you’re building the wrong version of the package. It’s still using nose and https://github.com/joaonc/pprintpp2/commit/9c65ae8e89ddb71d58153b1531dc969a5948d244 should have removed the use of the `parameterized` library.

**Comment by emilazy** [comment]
Can you put the testing stuff back? I don’t see any reason it shouldn’t work.

**Comment by Sigmanificient** [comment]
> Can you put the testing stuff back? I don’t see any reason it shouldn’t work.

I am not sure what you meant with this one

**Review by emilazy — APPROVED** [review]
Uh, sorry, I completely missed the `nativeCheckInputs = [ pytestCheckHook ]` line last time I looked at the diff since it moved lower down in the file…

Result of `nixpkgs-review pr 330705` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.ward</li>
    <li>python311Packages.ward.dist</li>
    <li>python312Packages.ward</li>
    <li>python312Packages.ward.dist</li>
  </ul>
</details>
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>opshin</li>
    <li>opshin.dist</li>
    <li>python311Packages.audio-metadata</li>
    <li>python311Packages.audio-metadata.dist</li>
    <li>python311Packages.pluthon</li>
    <li>python311Packages.pluthon.dist</li>
    <li>python311Packages.pprintpp</li>
    <li>python311Packages.pprintpp.dist</li>
    <li>python311Packages.pycardano</li>
    <li>python311Packages.pycardano.dist</li>
    <li>python311Packages.tbm-utils</li>
    <li>python311Packages.tbm-utils.dist</li>
    <li>python311Packages.uplc</li>
    <li>python311Packages.uplc.dist</li>
    <li>python312Packages.audio-metadata</li>
    <li>python312Packages.audio-metadata.dist</li>
    <li>python312Packages.pluthon</li>
    <li>python312Packages.pluthon.dist</li>
    <li>python312Packages.pprintpp</li>
    <li>python312Packages.pprintpp.dist</li>
    <li>python312Packages.pycardano</li>
    <li>python312Packages.pycardano.dist</li>
    <li>python312Packages.tbm-utils</li>
    <li>python312Packages.tbm-utils.dist</li>
    <li>python312Packages.uplc</li>
    <li>python312Packages.uplc.dist</li>
  </ul>
</details>

**Comment by Sigmanificient** [comment]
Was `ward` already broken?

**Comment by emilazy** [comment]
An awful lot of tests are still being skipped but that’s for the upstreams to work out.

**Comment by Sigmanificient** [comment]
> An awful lot of tests are still being skipped but that’s for the upstreams to work out.

Yeah :<

**Comment by emilazy** [comment]
> Was `ward` already broken?

Yes, hence “marked broken” (`broken = versionAtLeast rich.version "13.0.0";`). It seems to be another broken test framework, ironically.

**Pull request merged**
