### PR TITLE
tts: 0.0.13 -> 0.0.14

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

```
❯ ./result/bin/tts --text "To help with the large amounts of pull requests, we would appreciate your reviews of other pull requests, especially simple package updates. Just leave a comment describing what you have tested in the relevant package/service. Reviewing helps to reduce the average time-to-merge for everyone. Thanks a lot if you do\!"
 > tts_models/en/ljspeech/tacotron2-DDC is already downloaded.
 > vocoder_models/en/ljspeech/hifigan_v2 is already downloaded.
 > Using model: Tacotron2
 > Generator Model: hifigan_generator
Removing weight norm...
 > Text: To help with the large amounts of pull requests, we would appreciate your reviews of other pull requests, especially simple package updates. Just leave a comment describing what you have tested in the relevant package/service. Reviewing helps to reduce the average time-to-merge for everyone. Thanks a lot if you do!
 > Text splitted to sentences.
['To help with the large amounts of pull requests, we would appreciate your reviews of other pull requests, especially simple package updates.', 'Just leave a comment describing what you have tested in the relevant package/service.', 'Reviewing helps to reduce the average time-to-merge for everyone.', 'Thanks a lot if you do!']
 > Processing time: 9.217151880264282
 > Real-time factor: 0.4302393793181552
 > Saving output to tts_output.wav
```

https://shells.darmstadt.ccc.de/~hexa/tts-0.0.14.wav

No model changes. 
The test phase is quite a bit longer, but not unbearable: `🏁 tts-0.0.14 ⏲ 00:25:27`.

Due to licensing incompatibilities tts (MPL 2.0) doesn't rely on phonemizer (GPLv3) any more. That makes phonemizer/segments leaf packages that I don't intend to maintain anymore.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
undefined variable 'Mic92' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/ofborg-evaluator-1/pkgs/development/python-modules/coqpit/default.nix:35:44
```

**Comment by mweinelt** [comment]
Thanks, fixed. I blame @Mic92 for writing his maintainer handle in lowercase. :point_left: :smile:

**Comment by mweinelt** [comment]
aarch64 be like

> error: 1 dependencies of derivation '/nix/store/ya8wisnsw9cqsqp4hpaihgbsda05z4l2-python3.8-torchvision-0.9.0.drv' failed to build
> error: 2 dependencies of derivation '/nix/store/jr83dppv0gll3a297ap2gk6cd5f4cdgq-python3.8-tensorboardx-2.1.drv' failed to build

Can't be bothered about tensorflow failing on aarch64, sorry. :shrug:

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 123752` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.coqpit</li>
    <li>python39Packages.coqpit</li>
    <li>tests.trivial</li>
    <li>tts</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change looks good

Builds, works

Thanks for the update! :sparkles:

**Pull request merged**
