### PR TITLE
firefox{,-bin}: 102.0.1 -> 103.0; firefox-esr-102: 102.0.1esr -> 102.1.0esr; firefox-esr-91: 91.11.0esr -> 91.12.0esr; spidermonkey_91: 91.11.0 -> 91.12.0

### PR DESCRIPTION
**Pull request by mweinelt**
https://www.mozilla.org/en-US/firefox/103.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2022-28/

https://www.mozilla.org/en-US/firefox/102.1.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2022-30/

https://www.mozilla.org/en-US/firefox/91.12.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2022-29/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Test protocol
- YouTube
- WebGL
- Webcam, Microphone, Screensharing

On x86_64-linux with sway & pipewire
- [x] Firefox 103.0
- [ ] Firefox 102.1.0esr
- [ ] Firefox 91.12.0esr

**Comment by rhendric** [comment]
See also #179398!

**Review by squalus — APPROVED** [review]
Basic browsing tests pass on NixOS x86_64.

**Comment by mweinelt** [comment]
Release notes are up, added security advisories CVE identifiers to the individual commits. I think we are good to go!

**Comment by vcunat** [comment]
OK, no issues for me with `firefox` so far.

**Pull request merged**
