### PR TITLE
gns3-server: fix build, use buildPythonApplication

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
saw it was broken in another review

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
weird, its successful on nixos hydra: https://hydra.nixos.org/build/167021418

either way, disabling this test shouldn't hurt

**Comment by risicle** [comment]
On nixos x86_64, `moto` fails its tests:

```
           raise EndpointConnectionError(endpoint_url=request.url, error=e)
E           botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://sts.amazonaws.com/"

/nix/store/x9g2ip5f3wbbrjd4b4qlqm6nngq2x7pc-python3.9-botocore-1.23.35/lib/python3.9/site-packages/botocore/httpsession.py:414: EndpointConnectionError
```

```
=========================== short test summary info ============================
FAILED tests/test_stepfunctions/test_stepfunctions.py::test_state_machine_list_executions_with_filter
====== 1 failed, 3114 passed, 1 skipped, 35 warnings in 70.91s (0:01:10) =======
```

**Comment by risicle** [comment]
Ah, well it's happening for me on x86_64 now. Might be best to aim this at staging too.

**Comment by jonringer** [comment]
> Ah, well it's happening for me on x86_64 now. Might be best to aim this at staging too.

I think they're related issues, but not in a way that targeting staging makes sense. This is currently broken for all platforms, and at least it fixes a build on linux.

```
https://github.com/NixOS/nixpkgs/pull/159321

1 package built:
gns3-server
```

**Comment by starcraft66** [comment]
gns3-gui is also broken, probably for the same reason:

```
error: builder for '/nix/store/8kanp9n2m9lg61hyyrv2z3g0c6qyi0b2-python3.9-gns3-gui-2.2.29.drv' failed with exit code 1;
       last 10 log lines:
       > glibPreInstallPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./gns3_gui-2.2.29-py3-none-any.whl
       > Requirement already satisfied: setuptools in /nix/store/0xxs98jm9dpvybfgh7kghdq8ayvkp87m-python3.9-setuptools-57.2.0/lib/python3.9/site-packages (from gns3-gui==2.2.29) (57.2.0.post0)
       > Requirement already satisfied: psutil==5.8.0 in /nix/store/3la15bdsf7j3gdr74nc3zj2awdhfmhh0-python3.9-psutil-5.8.0/lib/python3.9/site-packages (from gns3-gui==2.2.29) (5.8.0)
       > Requirement already satisfied: distro==1.6.0 in /nix/store/b9wnll5nvn8cdp1vdmxa53cycbj7s38s-python3.9-distro-1.6.0/lib/python3.9/site-packages (from gns3-gui==2.2.29) (1.6.0)
       > ERROR: Could not find a version that satisfies the requirement jsonschema==3.2.0 (from gns3-gui) (from versions: none)
       > ERROR: No matching distribution found for jsonschema==3.2.0
       For full logs, run 'nix log /nix/store/8kanp9n2m9lg61hyyrv2z3g0c6qyi0b2-python3.9-gns3-gui-2.2.29.drv'.
error: 1 dependencies of derivation '/nix/store/j0ccvkvdwyvd2k630ir9l7qg3g877zw7-system-path.drv' failed to build
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 159321` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>gns3-gui</li>
    <li>gns3-server</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
