### PR TITLE
nixos/bcachefs: support unlock with clevis in systemd stage 1

### PR DESCRIPTION
**Pull request by mjm**
## Description of changes

Update the unlock script for bcachefs devices to attempt to use Clevis to unlock, as currently this only works in scripted stage 1.

I tested it on my Framework 13 by using PCR 7 and toggling whether SecureBoot was enabled. With it enabled, I wasn't prompted for my passphrase and booted to my display manager without input. With SecureBoot disabled, the unlock with Clevis failed and I was prompted for my passphrase.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ElvishJerricco — COMMENTED** [review]
Looks fine to me, though I haven't tested it in any way. Maybe we should add the `clevisBcachefs` test to `nixos/tests/installer-systemd-stage-1.nix`?

**Comment by JulienMalka** [comment]
I'll test this on my device during this week

**Comment by JulienMalka** [comment]
I tested the change on physical hardware, works for me.

**Review by ElvishJerricco — DISMISSED** [review]
@JulienMalka 

> Some of clevis tests are broken currently so I was not able to add the tests so far.

I think that's a blocker.

**Comment by ElvishJerricco** [comment]
Sounds like https://github.com/NixOS/nixpkgs/pull/300757 will fix the test. Let's add the test in this PR after that's merged.

**Review by JulienMalka — APPROVED** [review]
https://github.com/NixOS/nixpkgs/pull/300757 has landed, rebased on master and added the two tests.
Tested on local hardware for a week, tests are going through, LGTM.

**Pull request merged**
