### PR TITLE
ddcci-driver: patch to support linux 6.8

### PR DESCRIPTION
**Pull request by sweenu**
## Description of changes
Add patch until the fix is merged upstream (https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux/-/merge_requests/15).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sweenu** [comment]
Didn't have the opportunity to try the result, thanks for trying. Should we then simply mark it as broken for linux 6.8?

**Comment by ElvishJerricco** [comment]
@sweenu I just tested with 6.8 as well and got the same result. It "works" but it doesn't detect devices on its own, so you have to do the `new_device` hack. I wonder if the reason @Krutonium and @hughobrien seem to think it works might be because they're using the udev rule that does this `new_device` hack automatically? That was getting copy/pasted around on the NixOS Discourse and the ddcci-driver gitlab a lot.

But relying on users to have that workaround is not a *functioning* version of this driver. The only reason that udev rule was common is because of an as-of-yet-unresolved bug that doesn't affect everyone. This patch leaves it fundamentally broken for everyone, as far as I can tell. This needs to be fixed upstream. So in the meantime, yes, I think it's best to mark it broken on 6.8, and make sure it's obvious how to apply this patch in this PR so that anyone who still wants to can use the `new_device` hack.

**Comment by hughobrien** [comment]
@ElvishJerricco yes I did already have the `new_device` workaround in my config

```
      systemd.services.ddcci = {
        serviceConfig.Type = "oneshot";
        script = ''
          sleep 20
          echo 'ddcci 0x37' > /sys/bus/i2c/devices/i2c-15/new_device
        '';
      };   
```
It's not pretty

**Comment by Krutonium** [comment]
@ElvishJerricco I don't have that hack; I just installed the module and a Gnome addon and it just worked.

**Comment by ElvishJerricco** [comment]
@Krutonium If the Gnome addon you're using is based on `ddcutil` then you're not using `ddcci-driver` at all. `ddcutil` talks directly over the `i2c` device, not via the `ddcci` kernel module.

**Comment by sweenu** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/309948

**Pull request closed without merging**
