### PR TITLE
Libguestfs dependencies

### PR DESCRIPTION
**Pull request by avnik**
###### Motivation for this change

Remove unused dependencies, add dependencies which can be useful (./configure script looks for them to enable additional functionalities and other distros already have them).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
Needs a rebase.

**Comment by avnik** [comment]
Will rebase tomorrow (or more correct, replace commits with already rebased from my local-WIP branch)

**Comment by avnik** [comment]
@ajs124 rebase done

**Comment by euank** [comment]
The 'xen' portion of this PR ended up happening in #108882, which means this needs a rebase again; hopefully this can get reviewed/merged after that

**Comment by SuperSandro2000** [comment]
Closing due to inactivity from author.

**Pull request closed without merging**
