### PR TITLE
openorienteering-mapper: 0.9.0 -> 0.9.1

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change
[Changelog](https://github.com/OpenOrienteering/mapper/releases/tag/v0.9.1)

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
```sh
$ nix path-info -Sh /nix/store/9ggwghaaxisd3cjk4iniwrmjdkq1paxj-OpenOrienteering-Mapper-0.9.0
/nix/store/9ggwghaaxisd3cjk4iniwrmjdkq1paxj-OpenOrienteering-Mapper-0.9.0	 663.9M
$ nix path-info -Sh /nix/store/kdx140kwf9xx7hkzd1502sqk025y69if-OpenOrienteering-Mapper-0.9.1
/nix/store/kdx140kwf9xx7hkzd1502sqk025y69if-OpenOrienteering-Mapper-0.9.1	 664.4M
```
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @mpickering

### CODE REVIEW

**Comment by teto** [comment]
why ofborg didn't build on darwin ?

**Review by teto — APPROVED** [review]

**Comment by sikmir** [comment]
> why ofborg didn't build on darwin ?

What's up with darwin?

**Comment by c0bw3b** [comment]
Darwin builds on ofBorg builders are a different trust level.

@GrahamcOfBorg build openorienteering-mapper

**Review by c0bw3b — APPROVED** [review]
Result of `nix-review pr 75036` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package were build:</summary>

  - openorienteering-mapper
</details>

---

Builds and runs on NixOS

**Pull request merged**
