### PR TITLE
pkgs/rkt: bump to v1.1.0

### PR DESCRIPTION
**Pull request by steveej**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [ ] Built on platform(s): NixOS / OSX / Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### More

Fixes issue #<insert id>

cc @<maintainer>

---

_Please note, that points are not mandatory, but rather desired._

### CODE REVIEW

**Comment by ragnard** [comment]
LGTM

**Comment by kragniz** [comment]
:shipit:

**Comment by colemickens** [comment]
nit: commit should be named `rkt: 1.0.0 -> 1.1.0` based on [the manual](http://hydra.nixos.org/build/32530109/download/1/nixpkgs/manual.html#chap-submitting-changes).

Otherwise, LGTM.

**Comment by steveeJ** [comment]
@colemickens changed that. I left "pkgs/" intact to avoid ambiguity since rkt also has a module

**Comment by colemickens** [comment]
:+1:

**Pull request merged**
