### PR TITLE
imgbrd-wrapper: 7.3.2 -> 7.5.1

### PR DESCRIPTION
**Pull request by mkg20001**
###### Motivation for this change

ZHF: https://github.com/NixOS/nixpkgs/issues/144627

Note: the latest 7.6.2 failed to build and I didn't figure out how to fix it, but I just packaged 7.5.1 instead which is better than nothing :tm: 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mkg20001** [comment]
@NixOS/nixos-release-managers

**Review by evanjs — APPROVED** [review]
Not sure what's going on with #142372–just checked again and it _is_ still giving me a SEGFAULT.

I wonder if some combination of the two pull requests might help us get `7.6.2` working.

Anyway, `imgbrd-grabber 7.5.1` compiles and launches without issue.

**Comment by mkg20001** [comment]
Likely. We could merge this one and you can then rebase the 7.6.2 one?

**Review by risicle — APPROVED** [review]
Builds for me, nixos x86_64

**Pull request merged**
