### PR TITLE
dotnet-sdk_8: init at 8.0.100-preview.1.23115.2

### PR DESCRIPTION
**Pull request by JamieMagee**
###### Description of changes

Adds the first .NET 8.0 preview release
[Announcing .NET 8 Preview 1](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-1/).

.NET 8 will go GA in November 2023, and will be the new LTS release[^1]

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

[^1]: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#cadence

### CODE REVIEW

**Comment by JamieMagee** [comment]
Result of `nixpkgs-review pr 217624` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>dotnet-aspnetcore_8</li>
    <li>dotnet-runtime_8</li>
    <li>dotnet-sdk_8</li>
  </ul>
</details>

**Comment by raphaelr** [comment]
Commit message and PR name should start with "dotnet-sdk_8" instead of "dotnet-sdk_8.0" to make ofborg happy

@ofborg build dotnet-sdk_8 dotnet-sdk_8.tests

**Comment by JamieMagee** [comment]
Thanks for the tip! Looks like the evaluation was successful.

**Comment by prusnak** [comment]
@ofborg build dotnet-sdk_8 dotnet-sdk_8.tests

**Pull request merged**
