### PR TITLE
Update gleam, use v0.32.2

### PR DESCRIPTION
**Pull request by matt-savvy**
## Description of changes

[changelog](https://github.com/gleam-lang/gleam/blob/v0.32.0/CHANGELOG.md#v0320---2023-11-01)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Hey thanks a lot for this, this looks good to me, but per the contributing guidelines could you format the commit message differently ?

It should be
```
Gleam: 0.31.0 -> 0.32.0
https://github.com/gleam-lang/gleam/blob/v0.32.0/CHANGELOG.md
```

Otherwise the commit content looks good, thanks again !

**Comment by matt-savvy** [comment]
> Hey thanks a lot for this, this looks good to me, but per the contributing guidelines could you format the commit message differently ?
> 
> It should be
> 
> ```
> Gleam: 0.31.0 -> 0.32.0
> https://github.com/gleam-lang/gleam/blob/v0.32.0/CHANGELOG.md
> ```
> 
> Otherwise the commit content looks good, thanks again !

Sure, I've amended the commit and force-pushed: fa66ec62933

Let me know if that looks correct, thanks.

**Comment by matt-savvy** [comment]
https://nixpk.gs/pr-tracker.html?pr=265867

**Comment by tcoopman** [comment]
I'm not sure this is the correct place, but this build fails on M2: https://github.com/gleam-lang/gleam/issues/2397

**Comment by happysalada** [comment]
@tcoopman that is the right place.
The error says that there is a missing framework SystemConfiguration. If you search for this in nixpkgs, it should give you examples of how to add the dependency.
Basically you need to add it as a buildInput with lib.optional and stdenv.isdarwin.

I realise this might be a lot to digest and you might not have time for this. Im travelling until december, but happy to review any PRs until then.

**Comment by tcoopman** [comment]
@happysalada thanks, I quickly tried some stuff, but I couldn't get it to work. Don't have any time right now to explore more unfortunately, so I'll wait a bit...

**Comment by happysalada** [comment]
alright that should fix it https://github.com/NixOS/nixpkgs/pull/266669 let me know if you have time to test.

**Pull request merged**
