### PR TITLE
treewide: fix unstable Gentoo patch URLs

### PR DESCRIPTION
**Pull request by FliegendeWurst**
Without `?id=commitSha` these point to the main branch. One of the patches in this PR had in fact already disappeared! (I found the commit where it was added, so the URL works again)

I checked that all patches still resolve to the same contents.

## Things done

- Built on platform(s)
  - [x] x86_64-linux: 0 rebuilds... (it targets staging since one of these URLs was introduced in staging)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Thanks for this 💜

Due to the magic of FODs, I believe this can go to `master` (unless it depends on any `staging` changes).

**Comment by FliegendeWurst** [comment]
It depends on staging. See the mention in the commit above.

**Comment by emilazy** [comment]
Sorry for missing that!

**Comment by FliegendeWurst** [comment]
So I'm wondering.. would it make sense to have fetchpatch and co. in nixpkgs reject these URLs automatically?
There are a bunch more anti-patterns like fetching from a specific branch of a repository.
It would even be enough to catch these for the first run of the FOD.

**Comment by FliegendeWurst** [comment]
Perhaps it would be easiest to add that to https://github.com/NixOS/nixpkgs-vet first.

**Comment by emilazy** [comment]
It’d be nice, yeah. IIRC @alyssais wanted to make `fetchpatch` reject them but `nixpkgs-vet` would be nice since it could theoretically catch them in arbitrarily conditionals (albeit not dynamic assembly of URLs but hopefully reviewers can reject that!).

**Pull request merged**
