### PR TITLE
python311Packages.xsdata: 23.8 -> 24.1

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Changelog: https://github.com/tefra/xsdata/blob/v24.1/CHANGES.rst

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Ma27** [comment]
I don't really get why `ruff` is needed now and my mailserver now depends on a python linter/formatter (I've seen the code, I mean the reasoning), but 17M in a ~200M closure of Python code doesn't matter much, so that's not a hill I'd like to die on.

**Review by Ma27 — APPROVED** [review]

**Comment by dotlambda** [comment]
@Ma27 Your comment pointed me to a problem with this change:
https://github.com/tefra/xsdata/pull/892/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R51
Technically ruff is only an optional dependency installed with `xsdata[cli]`  Thus I should have added it to `passthru.optional-dependencies.cli`. It is however called using `subprocess.run()` rather than imported.
Ruff also does not have a public API: https://github.com/astral-sh/ruff/issues/659
So now the xsdata package is broken (because of a missing dependency) in case anyone uses its optional cli dependencies and the closure size is increased for no reason.

**Comment by Ma27** [comment]
> It is however called using subprocess.run() rather than imported.

So, I'm not sure if I'm missing something (I really need to sleep now), but isn't the subprocess call the reference that got patched in this PR?

**Comment by dotlambda** [comment]
> > It is however called using subprocess.run() rather than imported.
> 
> So, I'm not sure if I'm missing something (I really need to sleep now), but isn't the subprocess call the reference that got patched in this PR?

It's also listed in `pyproject.toml`.

**Comment by Ma27** [comment]
> It's also listed in pyproject.toml.

Ohh I see what you mean.
I guess removing ruff from there should be sufficient?

**Pull request merged**
