### PR TITLE
chrome-gnome-shell: Fix missing introspection data

### LINKED ISSUE #87740: chrome-gnome-shell: gobject `__main__+ChromeGNOMEShell' doesn't support property `application_id'
**Describe the bug**
I'm trying to use `chrome-gnome-shell` and I get this exception in the browser console:

```
stderr output from native app org.gnome.chrome_gnome_shell: /nix/store/xswsy4dys3ysgpn6ixwsn5179ai6irg6-python3.7-pygobject-3.34.0/lib/python3.7/site-packages/gi/types.py:220: Warning: g_param_spec_pool_lookup: assertion 'pool != NULL' failed
stderr output from native app org.gnome.chrome_gnome_shell:   _gi.type_register(cls, namespace.get('__gtype_name__'))
stderr output from native app org.gnome.chrome_gnome_shell: /nix/store/xswsy4dys3ysgpn6ixwsn5179ai6irg6-python3.7-pygobject-3.34.0/lib/python3.7/site-packages/gi/types.py:220: Warning: g_param_spec_pool_insert: assertion 'pool != NULL' failed
stderr output from native app org.gnome.chrome_gnome_shell:   _gi.type_register(cls, namespace.get('__gtype_name__'))
stderr output from native app org.gnome.chrome_gnome_shell: Traceback (most recent call last):
stderr output from native app org.gnome.chrome_gnome_shell:   File "/nix/store/1vz9z5p2bzi11fwsg5fzlg0hk8mlzbzl-chrome-gnome-shell-10.1/bin/.chrome-gnome-shell-wrapped", line 585, in <module>
stderr output from native app org.gnome.chrome_gnome_shell:     app = ChromeGNOMEShell(run_as_service)
stderr output from native app org.gnome.chrome_gnome_shell:   File "/nix/store/1vz9z5p2bzi11fwsg5fzlg0hk8mlzbzl-chrome-gnome-shell-10.1/bin/.chrome-gnome-shell-wrapped", line 63, in __init__
stderr output from native app org.gnome.chrome_gnome_shell:     else Gio.ApplicationFlags.IS_LAUNCHER | Gio.ApplicationFlags.HANDLES_OPEN
stderr output from native app org.gnome.chrome_gnome_shell: TypeError: gobject `__main__+ChromeGNOMEShell' doesn't support property `application_id'
```

I reported this upstream at https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/106 and the maintainer seems to think it is a NixOS bug.

**To Reproduce**
I am using `firefox-nightly-bin`, to which I have hackishly added the native-messaging manifest using `ln -sf (nix-build '<nixpkgs>' -A chrome-gnome-shell)/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json ~/.mozilla/native-messaging-hosts/`. When I go to `https://extensions.gnome.org/local/`, I see "An unexpected error occurred" in the webpage and the exception in the browser console.

**Expected behavior**
A successful webpage showing me the extensions I have installed.

**Additional context**
I can reproduce this stack trace by running the program at the command line.

**Notify maintainers**
@hedning @jtojnar @worldofpeace 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.30, NixOS, 20.03.1822.5adf2a6c116 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(ethan): `""`
 - channels(root): `"nixos-20.03.1822.5adf2a6c116"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - chrome-gnome-shell
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
It was crashing with:

    TypeError: gobject `__main__+ChromeGNOMEShell' doesn't support property `application_id'

– that is the constructor of parent class Gio.Application does not recognize the kwarg.

This is typically caused by missing pygobject overrides but I think ones for Gio are built-in into pygobject.

Even weirder, adding just `${gobject-introspection}/lib/girepository-1.0` seems to fix the issue so it might be missing the whole typelib.
But then why does not it fail when importing it?

    from gi.repository import GLib, Gio

For now, I am adding the Gio typelib which should been done from the start but more debugging should be done since weirdness like this can bring more bugs.

Fixes: https://github.com/NixOS/nixpkgs/issues/87740

cc @worldofpeace @glasserc

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wmertens** [comment]
I'm seeing this issue still - chrome-gnome-shell is still v10.1 and I'm seeing this error in the Chrome terminal output:

```
Mon Dec 06 19:57:51 😢  ERR 127 wmertens-nixos ~/Projects/Cap on master*
3078 $ /nix/store/05sszdlgbmx7xc0j5wl8b7ycp1496ipc-python3.9-pygobject-3.42.0/lib/python3.9/site-packages/gi/types.py:217: Warning: g_param_spec_pool_lookup: assertion 'pool != NULL' failed
  _gi.type_register(cls, namespace.get('__gtype_name__'))
/nix/store/05sszdlgbmx7xc0j5wl8b7ycp1496ipc-python3.9-pygobject-3.42.0/lib/python3.9/site-packages/gi/types.py:217: Warning: g_param_spec_pool_insert: assertion 'pool != NULL' failed
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/nix/store/i8qn9l78z22p55c753mfwsli7yl8l47j-chrome-gnome-shell-10.1/bin/.chrome-gnome-shell-wrapped", line 585, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/nix/store/i8qn9l78z22p55c753mfwsli7yl8l47j-chrome-gnome-shell-10.1/bin/.chrome-gnome-shell-wrapped", line 59, in __init__
    Gio.Application.__init__(
TypeError: gobject `__main__+ChromeGNOMEShell' doesn't support property `application_id'
```

**Comment by jtojnar** [comment]
@wmertens I cannot reproduce, works for me in both Firefox and Chromium. Could you please make sure you do not have `~/.config/google-chrome/NativeMessagingHosts/org.gnome.chrome_gnome_shell.json` pointing to the old version?

**Comment by wmertens** [comment]
@jtojnar thanks for following up, I dropped the ball here.

The file you mention had a different extension url so I replaced it but that didn't help, even after restarting chrome.

I also tried removing it, to no avail. Error remains the same.

**Comment by jtojnar** [comment]
@wmertens I am not concerned about the URL but the `path`.

**Comment by wmertens** [comment]
Ah - it was a regular file for me. What creates it?

**Comment by jtojnar** [comment]
Maybe you did and forgot about it?

**Comment by wmertens** [comment]
Hmm, unless it was part of instructions at some point, I didn't create it. It also doesn't get recreated, (but the native host still breaks).

I'll try removing the extension from Chrome and re-adding

**Comment by jtojnar** [comment]
I think we recommended creating the file in the past (though there were no official docs).

**Pull request merged**
