### PR TITLE
python312Packages.{polars,lancedb,pylance}: update and fix

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

- **python312Packages.pylance: 0.16.0 -> 0.17.0**
- **python312Packages.polars: 1.6.0 -> 1.7.1**
- **python312Packages.lancedb: 0.10.0 -> 0.13.0**

cc @natsukium

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by pbsds** [comment]
diff LGTM, conditioned that the darwin builds are not broken on the current pass

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages failed to build:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages failed to build:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.great-tables</li>
    <li>python311Packages.great-tables.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.great-tables</li>
    <li>python312Packages.great-tables.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
  </ul>
</details>

**Comment by pbsds** [comment]
all darwin failures are present on hydra, great-tables did not yet reach hydra, but the darwin CI in https://github.com/NixOS/nixpkgs/pull/341616 seems to have failed

**Comment by pbsds** [comment]
Do you have any more darwin fixes in progress or should we merge this?

**Review by pbsds — APPROVED** [review]

**Comment by GaetanLepage** [comment]
> all darwin failures are present on hydra, great-tables did not yet reach hydra, but the darwin CI in #341616 seems to have failed

Yes, it seems like `great-tables` has a failing test caused by a permission denied when writing to tmp.
I am still building the artifacts but it is painfully slow.
If hydra was able to build them, I would say that we should merge and eventually tackle the remaining issues afterwards.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341606` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.great-tables</li>
    <li>python311Packages.great-tables.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.great-tables</li>
    <li>python312Packages.great-tables.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
    <li>python312Packages.polars</li>
    <li>python312Packages.polars.dist</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Agreed, just tested polars on master and its broken for darwin, which in turn means pylance and lancedb are broken. So this PR at least improves the situation by one on darwin

**Pull request merged**
