### PR TITLE
nixos/wg-quick: use nftables if enabled

### PR DESCRIPTION
**Pull request by ncfavier**
Set `networking.firewall.package` to `nftables` if nftables is used, so that `wg-quick` can behave agnostically (it uses `nft` if present, otherwise falls back to `iptables`).

Tested with both iptables and nftables.

### CODE REVIEW

**Review by RaitoBezarius — APPROVED** [review]
LGTM.

**Comment by ncfavier** [comment]
I'm going to wait for https://github.com/NixOS/nixpkgs/pull/203011 since it overlaps this PR and looks promising.

**Comment by mkg20001** [comment]
@ncfavier the PR is merged now

**Comment by ncfavier** [comment]
I'm going to add a wg-quick-nftables test.

**Comment by ncfavier** [comment]
Hmm, it looks like iptables still works if nftables is enabled, so i can't get the test to fail on master. @duament any thoughts?

**Comment by duament** [comment]
> Hmm, it looks like iptables still works if nftables is enabled, so i can't get the test to fail on master. @duament any thoughts?

iptables-nft is expected to work with native nftables.

To disable iptables-nft, try blacklisting the `nft_compat` kernel module?

**Comment by duament** [comment]
And I think we should also replace iptables at https://github.com/NixOS/nixpkgs/blob/366683965efdd171880c6c4bb15ba19a60ed9966/pkgs/tools/networking/wireguard-tools/default.nix#L42

**Comment by ncfavier** [comment]
That worked, thanks.

@ofborg test wireguard

-------------------

> And I think we should replace iptables at
> 
> https://github.com/NixOS/nixpkgs/blob/366683965efdd171880c6c4bb15ba19a60ed9966/pkgs/tools/networking/wireguard-tools/default.nix#L42

`wg-quick`'s actual choice of firewall to use is based on whether `nft` is in PATH, so it is not influenced by the `iptables` there, so this is not strictly needed. There are a few things we could do though:

- move `iptables` to `--suffix` so that the version of iptables specified by `config.networking.firewall.package` takes precedence
- remove `iptables` altogether to signify that the package relies on an explicit choice of firewall backend in the environment

**Comment by ncfavier** [comment]
Went with the first one since the second one might break people's setups on non-NixOS.

**Pull request merged**
