### PR TITLE
beeper: init at 2.16.32

### PR DESCRIPTION
**Pull request by sumnerevans**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jyooru** [comment]
Result of `nixpkgs-review pr 145678` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>beeper</li>
  </ul>
</details>

**Comment by jyooru** [comment]
`./results/beeper/bin/beeper` launches fine.

**Comment by ryantm** [comment]
Doesn't build anymore:

```
$ NIXPKGS_ALLOW_UNFREE=1 nix build --impure .#beeper
error: hash mismatch in fixed-output derivation '/nix/store/da95805pdw8yz5hpv6ypzzx4ggi3xkcf-x64.drv':
         specified: sha256-YkvRsdiKgm9hlcepzuSiOi3B7yV0cgeCodmACKfZbAk=
            got:    sha256-6LILKK6YsmwVn0RAHbZqOfBs5GYHE1u/3CiCX/66u2o=
error: 1 dependencies of derivation '/nix/store/bzhbyq73sd2rphdp8mvxmspfzlf6cbp5-beeper-extracted.drv' failed to build
error: error: 1 dependencies of derivation '/nix/store/9crvqg7b1dzx069b5zqifyii3na0dg9c-beeper.drv' failed to build
```

**Comment by sumnerevans** [comment]
Unfortunately, we don't have a stable endpoint for downloading each version, so I'm going to close this.

**Comment by stites** [comment]
Just got off the waitlist and I can confirm that this derivation builds and gets me through this walkthrough with no errors!

The only modification was bumping the sha256 and version number:

```
appimageTools.wrapType2 rec {
  name = "beeper";
  version = "3.61.3";

  src = fetchurl {
    url = "https://download.beeper.com/linux/appimage/x64";
    sha256 = "085mdvp05qgwjnbchd641idlrzvchql4a2n84ld6sjgb39y09g7w";
  };
  ...
```

So excited for this @sumnerevans !!! If you have any say over deployment, maybe you could pitch a versioned download url (if you are planning on supporting multiple versions).

**Pull request closed without merging**
