### PR TITLE
root: 6.30.04 -> 6.30.06

### PR DESCRIPTION
**Pull request by guitargeek**
## Description of changes

Hello! My name is Jonas, and I am one of the core maintainers of ROOT.

I recently took an interest in nix, because I started to use NixOS on my laptop and I'm planning to deploy some ROOT-based products using nix.

Some improvement suggestions to the ROOT package in nix:

1. Don't define anything specific to Python 2, as Python 2 support is deprecated in ROOT 6.30 and will be removed from 6.32 (due to release in May) (https://github.com/root-project/root/pull/13948)
  2. Remove several other deprecated and ineffective build options
  3. Remove the explicit `-Droot7=ON`: this is the default, and since we are approaching ROOT 7 this option will never set to off by default anymore. No need to expliclity enable it in the derivation.
  4. Remove some explicit disabling of compiler warnings on clang. There is no need for that: we saw the warnings on our own CI and made sure to either fix or disable them.
  5. Remove the hack that disables the splash screen by default, as this has already been done in ROOT itself some time ago: https://github.com/root-project/root/pull/4187
  6. Finally, update to the latest 6.30.06 patch release.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by guitargeek** [comment]
@veprbl, I would appreciate your guidance!

**Comment by veprbl** [comment]
@GrahamcOfBorg build root root.tests

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 308122` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>hepmc3</li>
    <li>ns-3</li>
    <li>python311Packages.hepmc3</li>
    <li>python312Packages.hepmc3</li>
    <li>root</li>
    <li>root.debug</li>
    <li>xfitter</li>
    <li>yoda-with-root</li>
  </ul>
</details>

**Comment by veprbl** [comment]
Hello Jonas. And welcome to Nix! The PR looks good to me. Couple suggestions:
1. The commit message for a version bump should read as `attribute-name: prev-version -> new-version` (in this case, `root: 6.30.04 -> 6.30.06`)
2. Smaller distinct commits are preferred
3. Don't hesitate to add yourself to `root.meta.maintainers` https://ryantm.github.io/nixpkgs/stdenv/meta/#var-meta-maintainers

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 308122` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>hepmc3</li>
    <li>ns-3</li>
    <li>python311Packages.hepmc3</li>
    <li>python312Packages.hepmc3</li>
    <li>root</li>
    <li>xfitter</li>
    <li>yoda-with-root</li>
  </ul>
</details>

**Comment by guitargeek** [comment]
Thanks for your review @veprbl!

I have split up the PR in several smaller commits and added myself to `root.meta.maintainers`. I have kept the alphabetical order, let me know if this should be different.

**Review by veprbl — APPROVED** [review]

**Pull request merged**
