### PR TITLE
shunit2: 2019-08-10 (unstable) -> 2.1.8 and use resholvePackage

### PR DESCRIPTION
**Pull request by abathur**
###### Motivation for this change

Convert shunit2 to use `resholvePackage`.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by abathur** [comment]
@utdemir Curious what you think about this. 

I have PRs ready to convert a few Shell packages to use `resholvePackage`, but I'm a little unsure about the etiquette of converting packages other people maintain to use an API they may not be familiar with yet. 

I've noticed that you've used resholve in your dotfiles, so I'm hoping one of your packages is a good place to start.

**Comment by abathur** [comment]
I've reported the cause of the aarch64-darwin OfBorg failure separately in #154203.

**Review by utdemir — COMMENTED** [review]
Thanks for the change! It's impressive to me that `resholve` was able to check `shunit2`, as I always thought it's a shell script full of magic :).

I like the new result, as it made the derivation less dependent on rest of the system. I should've packed it alongside with `ncurses` and `grep` and stuff; but it's hard to grab all runtimr dependencies. I'm glad that `resholve` made those mistakes errors.

One drawback I see is that we are now depending on the "implementation details" of `shunit2`, which might make future maintenance harder. I added this derivation without reading a single line of `shunit2`'s source code, but obviously you had to read and understand it; and the future maintainers will need to do the same. 

I currently am not actively maintaining this package (I should remove myself as the maintainer these days), so I want to defer the decision to @cdepillabout .

**Comment by cdepillabout** [comment]
> I currently am not actively maintaining this package (I should remove myself as the maintainer these days)

I'm in the same boat.

@abathur How about removing me and @utdemir as maintainers, adding yourself, and then fixing up this derivation as you see fit?

**Comment by abathur** [comment]
> Thanks for the change! It's impressive to me that `resholve` was able to check `shunit2`, as I always thought it's a shell script full of magic :).
> 
> I like the new result, as it made the derivation less dependent on rest of the system. I should've packed it alongside with `ncurses` and `grep` and stuff; but it's hard to grab all runtimr dependencies. I'm glad that `resholve` made those mistakes errors.

Thanks--yes. They're easy to miss. resholve has turned up missing dependencies (even without counting coreutils) in nearly every shell package I've looked at converting so far.

> One drawback I see is that we are now depending on the "implementation details" of `shunit2`, which might make future maintenance harder. I added this derivation without reading a single line of `shunit2`'s source code, but obviously you had to read and understand it; and the future maintainers will need to do the same.

Yes, there is a trade off. For posterity, I didn't have to read anywhere near the full 1200+ line script. It's mostly just searching around and skimming a couple dozen lines to understand how the small number of identifiers that resholve complains about are used.

> I currently am not actively maintaining this package (I should remove myself as the maintainer these days), so I want to defer the decision to @cdepillabout .
> @abathur How about removing me and @utdemir as maintainers, adding yourself, and then fixing up this derivation as you see fit?

I can update the maintainers. I'd prefer to retain anyone who still has uses of shunit2 (I know @utdemir [has one](https://github.com/utdemir/h/blob/de3146517793f3710195cb26290fa7e865008c57/test.sh)! 😁), since you'll still be able to validate that future updates don't break your uses if I'm not able to respond for some reason. (My only personal dependency on shunit2 so far is a very, very trivial one in resholve's own "nix" demo.)

While searching, I noticed that @kayhide also has a few public uses of shunit2--perhaps they'd be open to me adding them, as well?

**Comment by abathur** [comment]
The aarch64-darwin blockage is worked around, so I'm opening for review. I took cdepillabout's place in the maintainer list but left utdemir, since he still has a public use of shunit2.

**Comment by happysalada** [comment]
I don't have additional comments. I'm just more impressed by resholve

**Pull request merged**
