### PR TITLE
Update language-puppet to 1.1.1 from hackage

### PR DESCRIPTION
**Pull request by PierreR**
This should fix `language-puppet` (which depends on hruby). I have managed to build it in a `nix-shell` with [this default.nix file](https://github.com/bartavelle/language-puppet/blob/master/default.nix) using the default ghc-7.10.x.

As a note the `puppetresources` package can be completely deleted (I know it is disabled anyway); it is deprecated and superseded by this package.

A little question : is there a tool that actually updates this automatically from hackage ?

Could you activate `language-puppet` in `cabal2nix` ?

### CODE REVIEW

**Comment by peti** [comment]
That update is part of 50ba03d. I'll merge to `master` once the test builds at http://hydra.cryp.to/jobset/nixpkgs/haskell-updates are done.

**Comment by PierreR** [comment]
I have seen the updated commit toward `language-puppet-1.1.1.2` but it does not appear yet at 

http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellngPackages.language-puppet.x86_64-linux

Is it just a matter of time or am I looking at the wrong place ?

Thx

**Comment by peti** [comment]
Automatic builds for the package had still been disabled because of earlier build failures. I've updated the package list to include it again; the new build should appear at the link you've used within 1 hour.

I also ran a local test build, and the new version compiled fine. Thank you for your efforts!

**Comment by PierreR** [comment]
Yep, it works !

What's the best strategy to use the  'binary cache' with haskellngpackages ? Add the channel `http://hydra.cryp.to/jobset/nixpkgs/haskell-updates/channel/latest` ?

Thanks for your help !

**Pull request closed without merging**
