### PR TITLE
python3Packages.sh: disable flaky tests

### LINKED ISSUE #199438: `python3Packages.sh` fails to build on Hydra (aarch64-darwin)
### Steps To Reproduce
1. build *python3Packages.sh*

### Build log
```
======================================================================
ERROR: test_piped_exception2 (test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-python3.10-sh-1.14.3.drv-0/sh-1.14.3/test.py", line 737, in test_piped_exception2
    self.assertRaises(ErrorReturnCode_2, fn)
  File "/nix/store/14sv2h3nag638062j87lg3ic4z8ipgis-python3-3.10.8/lib/python3.10/unittest/case.py", line 738, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/nix/store/14sv2h3nag638062j87lg3ic4z8ipgis-python3-3.10.8/lib/python3.10/unittest/case.py", line 201, in handle
    callable_obj(*args, **kwargs)
  File "/private/tmp/nix-build-python3.10-sh-1.14.3.drv-0/sh-1.14.3/test.py", line 735, in fn
    python(python(py.name, _piped=True), "-u", py2.name)
  File "/private/tmp/nix-build-python3.10-sh-1.14.3.drv-0/sh-1.14.3/sh.py", line 1524, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/private/tmp/nix-build-python3.10-sh-1.14.3.drv-0/sh-1.14.3/sh.py", line 788, in __init__
    self.wait()
  File "/private/tmp/nix-build-python3.10-sh-1.14.3.drv-0/sh-1.14.3/sh.py", line 852, in wait
    self.process._stdin_process.command.wait()
  File "/private/tmp/nix-build-python3.10-sh-1.14.3.drv-0/sh-1.14.3/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/private/tmp/nix-build-python3.10-sh-1.14.3.drv-0/sh-1.14.3/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_120: 

  RAN: /nix/store/14sv2h3nag638062j87lg3ic4z8ipgis-python3-3.10.8/bin/python3.10 /private/tmp/nix-build-python3.10-sh-1.14.3.drv-0/tmp3xh8eh1c

  STDOUT:


  STDERR:
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

### Additional context

amoffat/sh#541

### Notify maintainers

@siriobalmelli

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

Closes #199438.

Also, ZHF #199919

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siriobalmelli** [comment]
Result of `nixpkgs-review pr 199441` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by siriobalmelli** [comment]
LGTM

**Review by toonn — COMMENTED** [review]
Any reason [`disabledTests`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/aioimaplib/default.nix#L43) doesn't work?

**Comment by wegank** [comment]
@toonn The package uses unittest instead of pytest, so `disabledTests` won't work.

**Review by toonn — APPROVED** [review]
Looks OK to me. If `unittest` isn't compatible with `disabledTests` a patch seems like a good solution.

**Comment by mweinelt** [comment]
Pytest is compatible with unittest, so you can use `pytestCheckHook` instead with `pytestFlagsArray = [ "test.py" ];`. Then you can use `disabledTests` and purge the patch files.

**Comment by wegank** [comment]
@mweinelt Done. Although this will surely lead to massive rebuilds.

**Comment by mweinelt** [comment]
Then please rebase onto `staging-next` for this one time. I'll set this PR to draft to prevent accidental review requests.

**Comment by wegank** [comment]
@mweinelt Rebased.

**Pull request merged**
