### PR TITLE
tig: fix tig-completion's dependency on __git_complete

### PR DESCRIPTION
**Pull request by megheaiulian**
###### Motivation for this change
`tig` recently updated it's bash-completion making it depend on `__git-complete` from `git`. 
Becase `__git-complete` is not automatically sourced tig bash completion  fails.
Also this PR makes tig completion load on-demand.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by bjornfor — CHANGES_REQUESTED** [review]
Nit: please add PR info in commit message. It's valuable info!

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
Thanks!

**Comment by Ma27** [comment]
Ohh thanks a lot! Since this issue also exists on `release-20.03` I backported your patch as a438aed5a6ceda6beaa998af1c67a38f4b4c3156.

**Comment by smancill** [comment]
This PR didn't fix Zsh completion, which still complains with:

```
$ tig -- WARNING: this script is deprecated, please see git-completion.zsh
/nix/store/g92x5762p69g82fwx722gfqf15n4x0rr-tig-2.5.1/share/bash-completion/completions/tig:99: command not found: __git_complete
```

When using Zsh, `git-completion.bash` needs to be sourced by `tig-completion.zsh` with `GIT_SOURCING_ZSH_COMPLETION=y`.

A better patch would be not to source Git completion from `tig-completion.bash` when the shell is Zsh

``` diff
+ # fixes tig-completion __git-complete dependency
+ sed -i '1s;^;[[ -z $ZSH_VERSION ]] && source ${git}/share/bash-completion/completions/git\n;' contrib/tig-completion.bash
+
```

And substitute `git-completion.bash` also in `tig-completion.zsh` (which this PR missed), so it can be source properly from `tig-completion.zsh` instead of using the patched `source` command at the top of `tig-completion.bash`.

``` diff
     substituteInPlace contrib/tig-completion.zsh \
-      --replace 'e=$(dirname ''${funcsourcetrace[1]%:*})/tig-completion.bash' "e=$out/etc/bash_completion.d/tig-completion.bash"
+      --replace 'e=$(dirname ''${funcsourcetrace[1]%:*})/tig-completion.bash' "e=$out/share/bash-completion/completions/tig" \
+      --replace 'e=$(dirname ''${funcsourcetrace[1]%:*})/git-completion.bash' 'e=${git}/share/bash-completion/completions/git'
```

Not sure if the syntax is right (I just edited the files manually), but the point is clear I think. Both `tig-completion.bash` and `git-completion.bash` should be replaced in `tig-completion.zsh`.

I have no idea how to setup Nix to create and test the patch, that's why I am commenting here.

**Pull request merged**
