### PR TITLE
rss-glx: fix build

### PR DESCRIPTION
**Pull request by azahi**
###### Description of changes

Fix build https://hydra.nixos.org/build/178217710

ZHF: #172160

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by azahi** [comment]
Result of `nixpkgs-review pr 175287` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rss-glx</li>
  </ul>
</details>

**Comment by risicle** [comment]
On nixos x86_64:

```
builder for '/nix/store/qlygmh842pwwv6ix7pykgs2hxm0kj879-rss-glx-0.9.1.drv' failed with exit code 2; last 10 log lines:
  /nix/store/2b99rpx8zwdjjqkrvk7kqgn9mxhiidjy-binutils-2.38/bin/ld: /nix/store/8yphmqqn2wpp6aq3iid9i1bkx312lgqj-libheif-1.12.0/lib/libheif.so.1: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
  /nix/store/2b99rpx8zwdjjqkrvk7kqgn9mxhiidjy-binutils-2.38/bin/ld: /nix/store/8yphmqqn2wpp6aq3iid9i1bkx312lgqj-libheif-1.12.0/lib/libheif.so.1: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
  collect2: error: ld returned 1 exit status
  make[3]: *** [Makefile:578: drempels] Error 1
  make[3]: Leaving directory '/build/rss-glx_0.9.1/src'
  make[2]: *** [Makefile:1037: all-recursive] Error 1
  make[2]: Leaving directory '/build/rss-glx_0.9.1/src'
  make[1]: *** [Makefile:312: all-recursive] Error 1
  make[1]: Leaving directory '/build/rss-glx_0.9.1'
  make: *** [Makefile:241: all] Error 2
```

**Comment by azahi** [comment]
Well, that's weird. It builds fine for me.

**Comment by azahi** [comment]
Result of `nixpkgs-review pr 175287` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>rss-glx</li>
  </ul>
</details>

**Comment by azahi** [comment]
Wow, that's very strange. I'll look into this.

**Comment by azahi** [comment]
The issue was in:
``` diff
- rss-glx = callPackage ../misc/screensavers/rss-glx { stdenv = gcc10StdenvCompat; };
+ rss-glx = callPackage ../misc/screensavers/rss-glx { };
```

@risicle All should work now.

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 175287` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rss-glx</li>
  </ul>
</details>

**Pull request merged**
