### PR TITLE
k3s: 1.25.0+k3s1 -> 1.25.2+k3s1

### PR DESCRIPTION
**Pull request by superherointj**
k3s: 1.25.0+k3s1 -> 1.25.2+k3s1
* nixos/tests/k3s
  - fix tests
  - skip check-config in aarch64
  - add superherointj as maintainer
* (minor) convenience change to update script

### CODE REVIEW

**Review by bryanasdev000 — CHANGES_REQUESTED** [review]
Diff LGTM, but tests are failing.

Could you please take a look?

```
server # [  892.320393] k3s[5715]: time="2022-09-28T19:37:15Z" level=fatal msg="no-deploy flag is deprecated. Use --disable instead."
machine # [  892.345471] k3s[5801]: time="2022-09-28T19:37:15Z" level=fatal msg="no-deploy flag is deprecated. Use --disable instead."
```

https://logs.nix.ci/?key=nixos/nixpkgs.193376&attempt_id=e13cba6c-e4a0-4f81-90ac-0541ff5505fa

**Comment by bryanasdev000** [comment]
Note that based on:

https://github.com/k3s-io/k3s/compare/v1.25.0+k3s1...v1.25.2+k3s1
https://github.com/k3s-io/k3s/issues/1797
https://github.com/k3s-io/k3s/issues/1382

Tests may be borked *before* this update.

**Comment by superherointj** [comment]
@euank Thoughts?

**Comment by bryanasdev000** [comment]
Maybe something changed in test environment kernel?

Do you have a ARM64 access to run the `k3s check-config`?

**Comment by euank** [comment]
> Do you have a ARM64 access to run the k3s check-config?

Yup, it reproes for me by running `k3s check-config` on AWS's arm64 instances (like the `c6g` series).

----

In the v5.15 linux kernel tree, `make defconfig` on x86_64 gives me a `.config` with CGROUP_FREEZER, but doing it on arm I get a config without it.
I'm not sure why it's off by default for arm64, and looking at the git log, I don't see that it ever was on by default, so this doesn't seem like a recent upstream nor nixos kernel config change.

I think that the test might have been failing on arm64 ever since I uncommented that 'check-config' line in https://github.com/NixOS/nixpkgs/pull/182445, and that's what changed rather than something with the kernel or k3s.
I did only test that PR on x86_64, not arm.

To get another datapoint on that, I checked with k3s + linux from the `release-21.11` branch (k3s v1.22.3+k3s1, 5.10.126 kernel), and it also had the same `CONFIG_CGROUP_FREEZER` error in `check-config` on arm64.

I think it's probably easiest and best to skip the 'check-config' part of the test on arm64 for now, and then we can figure out if we should turn it on in the nixos kernel config, and come back to re-enable that bit of the test for arm64 too if it does make sense to turn it on.

------

Did we ever see `check-config` pass on arm64 in the past, or has it failed every time since that got uncommented?

Does skipping that bit on arm sound good to you as the right thing short term?

**Review by euank — APPROVED** [review]
Diff and test changes lgtm!

Thank you!

Per my comment above, I don't think the arm64 error is new, and I think it's something we should skip/ignore in the test on arm64 for now, until we can properly fix it.

I suspect we will want to come back and enable that kernel config option on arm64, but I think that should be handled separately from a version bump.

**Comment by superherointj** [comment]
@euank I have made the proposed changes. Let me know if you approve this so I can merge it.

**Comment by Artturin** [comment]
```
$ nix build ".#nixosTests.k3s.multi-node"
these 2 derivations will be built:
  /nix/store/8glp0r31z9lyrwwif3h6gn4945wnvsnm-nixos-test-driver-k3s-multi-node.drv
  /nix/store/mm39d39s8vh34p3bciw327z8qim0nkkx-vm-test-run-k3s-multi-node.drv
building '/nix/store/8glp0r31z9lyrwwif3h6gn4945wnvsnm-nixos-test-driver-k3s-multi-node.drv'...
nixos-test-driver-k3s-multi-node>      1        # This file contains type hints that can be prepended to Nix test scripts so they can be type
nixos-test-driver-k3s-multi-node>      2        # checked.
nixos-test-driver-k3s-multi-node>      3
nixos-test-driver-k3s-multi-node>      4        from test_driver.driver import Driver
nixos-test-driver-k3s-multi-node>      5        from test_driver.vlan import VLan
nixos-test-driver-k3s-multi-node>      6        from test_driver.machine import Machine
nixos-test-driver-k3s-multi-node>      7        from test_driver.logger import Logger
nixos-test-driver-k3s-multi-node>      8        from typing import Callable, Iterator, ContextManager, Optional, List, Dict, Any, Union
nixos-test-driver-k3s-multi-node>      9        from typing_extensions import Protocol
nixos-test-driver-k3s-multi-node>     10        from pathlib import Path
nixos-test-driver-k3s-multi-node>     11
nixos-test-driver-k3s-multi-node>     12
nixos-test-driver-k3s-multi-node>     13        class RetryProtocol(Protocol):
nixos-test-driver-k3s-multi-node>     14            def __call__(self, fn: Callable, timeout: int = 900) -> None:
nixos-test-driver-k3s-multi-node>     15                raise Exception("This is just type information for the Nix test driver")
nixos-test-driver-k3s-multi-node>     16
nixos-test-driver-k3s-multi-node>     17
nixos-test-driver-k3s-multi-node>     18        class PollingConditionProtocol(Protocol):
nixos-test-driver-k3s-multi-node>     19            def __call__(
nixos-test-driver-k3s-multi-node>     20                self,
nixos-test-driver-k3s-multi-node>     21                fun_: Optional[Callable] = None,
nixos-test-driver-k3s-multi-node>     22                *,
nixos-test-driver-k3s-multi-node>     23                seconds_interval: float = 2.0,
nixos-test-driver-k3s-multi-node>     24                description: Optional[str] = None,
nixos-test-driver-k3s-multi-node>     25            ) -> Union[Callable[[Callable], ContextManager], ContextManager]:
nixos-test-driver-k3s-multi-node>     26                raise Exception("This is just type information for the Nix test driver")
nixos-test-driver-k3s-multi-node>     27
nixos-test-driver-k3s-multi-node>     28
nixos-test-driver-k3s-multi-node>     29        start_all: Callable[[], None]
nixos-test-driver-k3s-multi-node>     30        subtest: Callable[[str], ContextManager[None]]
nixos-test-driver-k3s-multi-node>     31        retry: RetryProtocol
nixos-test-driver-k3s-multi-node>     32        test_script: Callable[[], None]
nixos-test-driver-k3s-multi-node>     33        machines: List[Machine]
nixos-test-driver-k3s-multi-node>     34        vlans: List[VLan]
nixos-test-driver-k3s-multi-node>     35        driver: Driver
nixos-test-driver-k3s-multi-node>     36        log: Logger
nixos-test-driver-k3s-multi-node>     37        create_machine: Callable[[Dict[str, Any]], Machine]
nixos-test-driver-k3s-multi-node>     38        run_tests: Callable[[], None]
nixos-test-driver-k3s-multi-node>     39        join_all: Callable[[], None]
nixos-test-driver-k3s-multi-node>     40        serial_stdout_off: Callable[[], None]
nixos-test-driver-k3s-multi-node>     41        serial_stdout_on: Callable[[], None]
nixos-test-driver-k3s-multi-node>     42        polling_condition: PollingConditionProtocol
nixos-test-driver-k3s-multi-node>     43        agent: Machine; server: Machine; server2: Machine;
nixos-test-driver-k3s-multi-node>     44        vlan1: VLan;
nixos-test-driver-k3s-multi-node>     45        machines = [server, server2, agent]
nixos-test-driver-k3s-multi-node>     46        for m in machines:
nixos-test-driver-k3s-multi-node>     47            m.start()
nixos-test-driver-k3s-multi-node>     48            m.wait_for_unit("k3s")
nixos-test-driver-k3s-multi-node>     49
nixos-test-driver-k3s-multi-node>     50        # wait for the agent to show up
nixos-test-driver-k3s-multi-node>     51        server.wait_until_succeeds("k3s kubectl get node agent")
nixos-test-driver-k3s-multi-node>     52
nixos-test-driver-k3s-multi-node>     53        for m in machines:
nixos-test-driver-k3s-multi-node>     54        m.succeed("k3s check-config")    m.succeed(
nixos-test-driver-k3s-multi-node>     55                "/nix/store/pdpha1p0vl1mn49xbyyfws75f1850ylq-stream-pause | k3s ctr image import -"
nixos-test-driver-k3s-multi-node>     56            )
nixos-test-driver-k3s-multi-node>     57
nixos-test-driver-k3s-multi-node>     58        server.succeed("k3s kubectl cluster-info")
nixos-test-driver-k3s-multi-node>     59        # Also wait for our service account to show up; it takes a sec
nixos-test-driver-k3s-multi-node>     60        server.wait_until_succeeds("k3s kubectl get serviceaccount default")
nixos-test-driver-k3s-multi-node>     61
nixos-test-driver-k3s-multi-node>     62        # Now create a pod on each node via a daemonset and verify they can talk to each other.
nixos-test-driver-k3s-multi-node>     63        server.succeed("k3s kubectl apply -f /nix/store/n9w4w1jrlda2xxp7b4jz3db7wpp93lnh-test.yml")
nixos-test-driver-k3s-multi-node>     64        server.wait_until_succeeds(f'[ "$(k3s kubectl get ds test -o json | jq .status.numberReady)" -eq {len(machines)} ]')
nixos-test-driver-k3s-multi-node>     65
nixos-test-driver-k3s-multi-node>     66        # Get pod IPs
nixos-test-driver-k3s-multi-node>     67        pods = server.succeed("k3s kubectl get po -o json | jq '.items[].metadata.name' -r").splitlines()
nixos-test-driver-k3s-multi-node>     68        pod_ips = [server.succeed(f"k3s kubectl get po {name} -o json | jq '.status.podIP' -cr").strip() for name in pods]
nixos-test-driver-k3s-multi-node>     69
nixos-test-driver-k3s-multi-node>     70        # Verify each server can ping each pod ip
nixos-test-driver-k3s-multi-node>     71        for pod_ip in pod_ips:
nixos-test-driver-k3s-multi-node>     72            server.succeed(f"ping -c 1 {pod_ip}")
nixos-test-driver-k3s-multi-node>     73            agent.succeed(f"ping -c 1 {pod_ip}")
nixos-test-driver-k3s-multi-node>     74
nixos-test-driver-k3s-multi-node>     75        # Verify the pods can talk to each other
nixos-test-driver-k3s-multi-node>     76        resp = server.wait_until_succeeds(f"k3s kubectl exec {pods[0]} -- socat TCP:{pod_ips[1]}:8000 -")
nixos-test-driver-k3s-multi-node>     77        assert resp.strip() == "server"
nixos-test-driver-k3s-multi-node>     78        resp = server.wait_until_succeeds(f"k3s kubectl exec {pods[1]} -- socat TCP:{pod_ips[0]}:8000 -")
nixos-test-driver-k3s-multi-node>     79        assert resp.strip() == "server"
nixos-test-driver-k3s-multi-node>     80
nixos-test-driver-k3s-multi-node>     81        # Cleanup
nixos-test-driver-k3s-multi-node>     82        server.succeed("k3s kubectl delete -f /nix/store/n9w4w1jrlda2xxp7b4jz3db7wpp93lnh-test.yml")
nixos-test-driver-k3s-multi-node>     83
nixos-test-driver-k3s-multi-node>     84        for m in machines:
nixos-test-driver-k3s-multi-node>     85            m.shutdown()
nixos-test-driver-k3s-multi-node> testScriptWithTypes:54: error: expected an indented block after 'for' statement
nixos-test-driver-k3s-multi-node> on line 53
nixos-test-driver-k3s-multi-node>     m.succeed("k3s check-config")    m.succeed(
nixos-test-driver-k3s-multi-node>      ^
nixos-test-driver-k3s-multi-node> Found 1 error in 1 file (errors prevented further checking)
error: builder for '/nix/store/8glp0r31z9lyrwwif3h6gn4945wnvsnm-nixos-test-driver-k3s-multi-node.drv' failed with exit code 2;
       last 10 log lines:
       >     81        # Cleanup
       >     82       server.succeed("k3s kubectl delete -f /nix/store/n9w4w1jrlda2xxp7b4jz3db7wpp93lnh-test.yml")
       >     83
       >     84    for m in machines:
       >     85          m.shutdown()
       > testScriptWithTypes:54: error: expected an indented block after 'for' statement
       > on line 53
       >     m.succeed("k3s check-config")    m.succeed(
       >      ^
       > Found 1 error in 1 file (errors prevented further checking)
       For full logs, run 'nix log /nix/store/8glp0r31z9lyrwwif3h6gn4945wnvsnm-nixos-test-driver-k3s-multi-node.drv'.
error: 1 dependencies of derivation '/nix/store/mm39d39s8vh34p3bciw327z8qim0nkkx-vm-test-run-k3s-multi-node.drv' failed to build
```

**Pull request merged**
