### PR TITLE
vimPlugins.tabnine-vim: init at 2021-01-14

### PR DESCRIPTION
**Pull request by VergeDX**
###### Motivation for this change

This is the Vim TabNine client, advanced AI based autocomplete for all programming languages. TabNine Indexes your entire project by reading your .gitignore or others, and determines which files to index.
-- quote from [vimawesome - tabnine-vim](https://vimawesome.com/plugin/tabnine-vim)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fortuneteller2k** [comment]
@ofborg eval

**Comment by cole-h** [comment]
@ofborg eval

(Sorry, ofborg's certs recently had an issue, meaning that it was unable to
react to PRs. This has been fixed, but all PRs filed in this period will need
ofborg to be manually kicked off.)

**Comment by SuperSandro2000** [comment]
@VergeDX please rebase

**Comment by VergeDX** [comment]
@SuperSandro2000 Changes performed.

**Comment by jonringer** [comment]
@VergeDX you could probably just remove the update commit

**Comment by VergeDX** [comment]
Well I followed the [doc/languages-frameworks/vim.section.md](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs) 
and run `./update.py --add "codota/tabnine-vim"` to add this plugin, the commit is auto.
I'll only add the `tabnine-vim` without update the others.

**Comment by VergeDX** [comment]
Well I followed the [doc/languages-frameworks/vim.section.md](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs) 
and run `./update.py --add "codota/tabnine-vim"` to add this plugin, the commit is auto.
I'll only add the `tabnine-vim` without update the others.

**Pull request merged**
