### PR TITLE
jenkins: fixed-output derivation to avoid rebuilds

### PR DESCRIPTION
**Pull request by jammerful**
see also #27754 (comment) for motivation.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] Linux
- [x] Tested via `nixos/tests/jenkins.nix`(had to raise the timeout)
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jammerful** [comment]
@Mic92 You did the same thing for my Gerrit package yesterday, this was the pattern I followed so doing the same for it.

**Comment by bjornfor** [comment]
This pattern adds a second hash that needs to be updated on version bumps. How much rebuilding is "saved"? Is it worth it?

**Comment by volth** [comment]
> This pattern adds a second hash that needs to be updated on version bumps.

It can be done with one hash, if ```buildCommand``` moved to ```postFetch``` of ```fetchurl```/```fetchzip``` (see examples in data/fonts directory).

> How much rebuilding is "saved"?

At least, there won't be separated versions for each platform.
Also, no rebuild on ```stdenv``` change (on those commits marked with ```mass-rebuid```).

**Comment by bjornfor** [comment]
> It can be done with one hash, if buildCommand moved to postFetch of fetchurl/fetchzip (see examples in data/fonts directory).

But that hash won't correspond to upstream source hash (right?). So it becomes more difficult to verify that the source we have is the exact same source upstream provides.

I think I'm -1 on this pattern. I think it's premature optimization. (At least in the form used in this PR.)

**Comment by volth** [comment]
Right.
So when there is a complex logic in ```buildCommand``` it is better to have both hashes to ease debugging. But when there is just picking one file from the archive, it should be ok. For example ```fetchzip``` and friends (without any tricks) use hash which does not correspond to the hash of the zip file, but the hash of the directory of unpacked files

**Pull request closed without merging**
