### PR TITLE
hikari: 2.0.4 -> 2.1.0

### PR DESCRIPTION
**Pull request by wjlroe**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wjlroe** [comment]
I have built and run this update locally (I'm running it now as I type this) and it works as well as the current version in the master branch

**Review by jpotier — APPROVED** [review]
Not tested, but someone else did. Change is minimal. LGTM

**Comment by jpotier** [comment]
Hikari 2.1.1 is out btw!

**Comment by wjlroe** [comment]
Closed in favour of updated PR #94266

**Pull request closed without merging**
