### PR TITLE
glusterfs service: Ensure dirs needed by `glusterfind` exist

### PR DESCRIPTION
**Pull request by nh2**
###### Motivation for this change

Without these dirs, `glusterfind` errors like this:

```
# glusterfind create test1 myvol
Failed to copy public key to /var/lib/glusterd/glusterfind/.keys: [Errno 2] No such file or directory: '/var/lib/glusterd/glusterfind/.keys/test1_myvol_secret.pem.pub'
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

FYI @bachp who's another user of this service.

---

I would also like to have this change in 17.09, please let me know if I need to open a separate PR for that.

### CODE REVIEW

**Comment by nh2** [comment]
Don't merge yet, I have at least 2 more fixes to `glusterfind` coming.

**Comment by nh2** [comment]
I've pusshed 3 more fixes. `glusterfind` `pre`, `post`, `list`, and `query` now work for me.

CC @bachp

**Comment by bachp** [comment]
I applied the patch to my setup and everything is working.
So from my point of view this is good to merge.

**Comment by joachifm** [comment]
@nh2 you can open a PR with cherry-picked commits against release-17.09 if you like. I can also do the cherry-picks directly if you prefer, but pushing the green button is less work for me :)

**Comment by nh2** [comment]
@joachifm Thanks! Cherry-pick PR at #29160.

**Pull request merged**
