### PR TITLE
jbig2dec: Fix cross-compilation

### PR DESCRIPTION
**Pull request by avnik**
## Description of changes

Fix cross-compilation issue -- `autogen.sh` call `./configure` without arguments.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Mindavi** [comment]
An alternative solution I've seen is this: `configureScript = "./autogen.sh";`.

**Comment by avnik** [comment]
@Mindavi from one side -- I like this suggestion,  but isn't it break stuff from here https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L1221 ?

**Comment by Mindavi** [comment]
Not sure what you mean, the libtool fixup seems unrelated? And the ./autogen.sh script passes all its arguments to ./configure, as far as I read. Ultimately both solutions are valid, but setting autogen as configure script seems to be done more often in the tree and is more easily discoverable.

**Comment by avnik** [comment]
@Mindavi I affraid, that following logic could break, because grep some stuff in $configureScript

```sh
    if [[ -f "$configureScript" ]]; then
        # Add --disable-dependency-tracking to speed up some builds.
        if [ -z "${dontAddDisableDepTrack:-}" ]; then
            if grep -q dependency-tracking "$configureScript"; then
                prependToVar configureFlags --disable-dependency-tracking
            fi
        fi

        # By default, disable static builds.
        if [ -z "${dontDisableStatic:-}" ]; then
            if grep -q enable-static "$configureScript"; then
                prependToVar configureFlags --disable-static
            fi
        fi

        if [ -z "${dontPatchShebangsInConfigure:-}" ]; then
            patchShebangs --build "$configureScript"
        fi
    fi
```

But I can change, to $configureScript if you like

**Comment by avnik** [comment]
Also, it probably should go for staging, due amount of rebuilds

**Comment by Mindavi** [comment]
> @Mindavi I affraid, that following logic could break, because grep some stuff in $configureScript
> 
> ```shell
>     if [[ -f "$configureScript" ]]; then
>         # Add --disable-dependency-tracking to speed up some builds.
>         if [ -z "${dontAddDisableDepTrack:-}" ]; then
>             if grep -q dependency-tracking "$configureScript"; then
>                 prependToVar configureFlags --disable-dependency-tracking
>             fi
>         fi
> 
>         # By default, disable static builds.
>         if [ -z "${dontDisableStatic:-}" ]; then
>             if grep -q enable-static "$configureScript"; then
>                 prependToVar configureFlags --disable-static
>             fi
>         fi
> 
>         if [ -z "${dontPatchShebangsInConfigure:-}" ]; then
>             patchShebangs --build "$configureScript"
>         fi
>     fi
> ```
> 
> But I can change, to $configureScript if you like

I see. Then just keep it as-is :)

**Review by Mindavi — CHANGES_REQUESTED** [review]
But indeed, needs to go to staging.

**Comment by avnik** [comment]
@Mindavi changed base branch to staging

**Pull request closed without merging**
