### PR TITLE
mu-editor: start at 1.1.0-alpha.2

### LINKED ISSUE #73975: Package request: mu editor
**Project description**
A small, simple editor for beginner Python programmers. Written in Python and Qt5.

**Metadata**

* homepage URL: https://codewith.mu/
* source URL: https://github.com/mu-editor/mu
* license: gpl3+
* platforms: linux, darwin

### PR DESCRIPTION
**Pull request by malbarbo**
###### Description of changes

The last version of mu is 1.1.1, but starting at 1.1.0-beta.1 it manages parts of the environment using virtualenv, pip and wheels, which is very hard to make work properly in nixos and even in other system (see https://github.com/mu-editor/mu/issues/1954). The last version I could make work was 1.1.0-alpha.2.

Fixes https://github.com/NixOS/nixpkgs/issues/73975.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by malbarbo** [comment]
The upstream are working on the issue, so I think in the future we can try to upgrade to a new version. Also, there are previous attempts to package the mu editor but none are completed. This package can serve some users willing to use mu editor in nixos ans be the base for future upgrades.

**Comment by rissson** [comment]
Previous work had been done in https://github.com/prologin/nixpkgs/commits/mu-editor
I'll review this when I have time.

**Comment by rissson** [comment]
Do you have a link to upstream issues or PRs that might address packaging problems encountered post 1.1.0-alpha.2 ?

**Comment by onny** [comment]
Please change PR title and commit names to format `program: init at X.X.X`

**Comment by AndersonTorres** [comment]
Closing as dead.

**Pull request closed without merging**
