### PR TITLE
zsh-completions: avoid collision with trashy

### PR DESCRIPTION
**Pull request by Vonfry**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Vonfry** [comment]
This pr may break completions for trash-cli.

**Comment by hurricanehrndz** [comment]
Don't think so since trash-cli includes its own completion as well, if anything this pr will fix another collision

**Comment by davidsierradz** [comment]
`zsh-completions` removed `_trash` completions, but there is not release yet. So we can accept this to resolve the issue right now, or wait until there is a new zsh-completions release: [Remove _trash* because trashcli support completion by Freed-Wu · Pull Request #895 · zsh-users/zsh-completions](https://github.com/zsh-users/zsh-completions/pull/895)

BTW, to fix collisions for all commands:

```diff
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
modified: pkgs/shells/zsh/zsh-completions/default.nix
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
@ pkgs/shells/zsh/zsh-completions/default.nix:20 @ stdenv.mkDerivation rec {

     # tmuxp install it so avoid collision
     rm $out/share/zsh/site-functions/_tmuxp
+
+    # trash-cli install it so avoid collision
+    # TODO: remove this after zsh-completions is updated (> 0.34.0)
+    rm $out/share/zsh/site-functions/_trash{,-empty,-list,-restore,-put}
   '';

   meta = {
```

**Comment by Artturin** [comment]
> `zsh-completions` removed `_trash` completions, but there is not release yet. So we can accept this to resolve the issue right now, or wait until there is a new zsh-completions release: [Remove _trash* because trashcli support completion by Freed-Wu · Pull Request #895 · zsh-users/zsh-completions](https://github.com/zsh-users/zsh-completions/pull/895)
> 
> BTW, to fix collisions for all commands:
> 
> ```diff
> --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> modified: pkgs/shells/zsh/zsh-completions/default.nix
> --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> @ pkgs/shells/zsh/zsh-completions/default.nix:20 @ stdenv.mkDerivation rec {
> 
>      # tmuxp install it so avoid collision
>      rm $out/share/zsh/site-functions/_tmuxp
> +
> +    # trash-cli install it so avoid collision
> +    # TODO: remove this after zsh-completions is updated (> 0.34.0)
> +    rm $out/share/zsh/site-functions/_trash{,-empty,-list,-restore,-put}
>    '';
> 
>    meta = {
> ```

@Vonfry please apply the diff

**Comment by Vonfry** [comment]
Let us wait for the new release of zsh-completions which will remove
_trash. Other fixes, such as the above patch, can be done locally
instead of this pr.

**Comment by Vonfry** [comment]
A new release is published. Let us make a pr to update.

**Pull request closed without merging**
