### PR TITLE
Switch default version of GNU Make to 4.x

### PR DESCRIPTION
**Pull request by peti**

### CODE REVIEW

**Comment by peti** [comment]
PR updated for GNU Make 4.1.

**Comment by bjornfor** [comment]
Commit message still says 4.0.

**Comment by peti** [comment]
Fixed, thanks!

**Comment by peti** [comment]
Test builds for this branch will run at http://hydra.nixos.org/jobset/nixpkgs/mass-rebuild-updates.

**Comment by peti** [comment]
The [Hydra builds](http://hydra.nixos.org/jobset/nixpkgs/mass-rebuild-updates) look fine, so I guess we can merge the switch to 4.x to `staging`. Now, is there anything left to do with regard to pretty-printed logs? I understand make 4.x doesn't provide the necessary markup any more?

**Comment by lethalman** [comment]
I usually read the tail of raw logs, or raw logs at all. I think we're all able to distinguish configure from build phase, so I think that's only prettiness for nobody. :+1: for ditching it.

**Comment by peti** [comment]
cd89c69 merged to `staging`.

**Comment by vcunat** [comment]
Maybe the corresponding jobset should stop building? http://hydra.nixos.org/jobset/nixpkgs/pr-4943

**Comment by peti** [comment]
I disabled it when I merged. I didn't bother cancelling the remaining 4000 builds from the queue, though. Maybe I should have? I thought that it's kind-of nice to have a complete build, just in case. I don't feel strongly about it, though.

**Comment by vcunat** [comment]
Ah, I see the queue probably only contains darwin jobs.

Earlier today I was just thinking of Hydra only having two slots for darwin jobs, so the queue will soon overflow with them, maybe even blocking further evaluations (I'm unsure what it does if it's this unbalanced).

**Comment by iElectric** [comment]
I've canceled the darwin jobs - they will get built as part of staging anyway

**Pull request closed without merging**
