### PR TITLE
portmod: 2.1.0 -> 2.4.2, bsatool2: init at 2.0.1

### LINKED ISSUE #197624: Portmod does not build mods for Fallout: New Vegas.
### Describe the bug
Portmod does not build mods for Fallout NV. It works correctly with OpenMW. 

### Steps To Reproduce
1. Try to install mod for Fallout NV.
2. Installation fails with this error:
`>>> Executing pkg_pretend for package assets-meshes/remastered-bodies-1.2
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmodlib/_wrapper.py", line 203, in main
    args.func(args)
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmodlib/_wrapper.py", line 67, in wrapper_pybuild
    pkg_func(pkg, "pkg_pretend")
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmodlib/_wrapper.py", line 55, in pkg_func
    return func()
  File "/tmp/portmod/tmpdb/common/bsa/bsa-0.4-r1.pybuild", line 25, in pkg_pretend
    if not shutil.which("bsatool2") and "linux" not in self.USE:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/_cli/main.py", line 468, in main
    args.func(args)
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/_cli/search.py", line 35, in search_main
    configure(selection)
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/merge.py", line 369, in configure
    _sandbox_execute_pybuild(
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/loader.py", line 363, in _sandbox_execute_pybuild
    result = _sandbox_execute(
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/loader.py", line 302, in _sandbox_execute
    raise SandboxedError(
portmod.loader.SandboxedError: /home/user/.local/share/portmod/repos/fallout-nv/assets-meshes/remastered-bodies/remastered-bodies-1.2.pybuild pretend failed!
ERROR: /home/user/.local/share/portmod/repos/fallout-nv/assets-meshes/remastered-bodies/remastered-bodies-1.2.pybuild pretend failed!`

### Notify maintainers
@marius851000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.70-xanmod1, NixOS, 22.11 (Raccoon), 22.11pre419369.301aada7a64`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager-22.05.tar.gz, nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### LINKED ISSUE #198109: Upgade request: portmod: 2.1.0 -> 2.4.2
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: portmod

current version: 2.1.0
desired version: 2.4.2

###### Notify maintainers
@marius851000

maintainers:

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by marius851000**
###### Description of changes

1. Update portmod from 2.1.0 to 2.4.2
2. Add bsatool2 as a binary. It should fix the problem of portmod not working with fallout: new vegas and other, more recent Bethesda games. Turns out this actually isn’t needed, but I’ll still keep it, as I already needed a tool like this in the past, and might need one again in the future.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I checked that it work well with Morrowind. I add two issues, related to updating:
1. The metadatas should be update (``portmod sync``)
2. With morrowind, I add to unmerge openmw-config and merge configtool (``portmod <prefix> merge -C openmw-config`` and ``portmod morrowind merge configtool``. But it seems that everything depends on configtool.)

Fix https://github.com/NixOS/nixpkgs/issues/198109 and should fix https://github.com/NixOS/nixpkgs/issues/197624 (untested for now)

### CODE REVIEW

**Comment by marius851000** [comment]
So, after some test, I found two issues:
1. New Vegas doesn’t work (that’s some issue with portmod, I think)
2. Mirrors does not work (it’s an API change in GitLab)

**Comment by marius851000** [comment]
Actually, the mirror issue is just a problem with portmod metadata repo.

**Comment by marius851000** [comment]
Turns out that a precompiled bsatool2 is fetched from portmod, and that it isn’t required. I’m a bit hesitant on keeping or removing it (knowing it could be usefull for some toying around in Skyrim. already had issue decompiled modern bsa in the past).

The other issues with fallout are all issues with the metadata repo. I’ll make a PR upstream of my change, but it won’t require change in NixPkgs, as it fetch it at runtime.

**Comment by marius851000** [comment]
Should be ready for review now.

**Review by LennyPenny — APPROVED** [review]
Just tried this as an overlay on 22.11 and it seems work fine :+1:

**Comment by LennyPenny** [comment]
@marius851000 if you could rebase this, merging is imminent

**Comment by Slime90** [comment]
@marius851000 Can this get pushed over the finish line?

**Comment by marius851000** [comment]
Oh, sorry, didn't looked at tyis for some time. I'll do once I'm done with my game jam and potentially r/place, so probably around the end of this month.

**Comment by marius851000** [comment]
Closed as a similar commit was made as 00ee658dfbcaac61a80a0b7ba1bb33d5b5caca44

**Pull request closed without merging**
