### PR TITLE
nixos/prowlarr: add a module similar to sonarr/radarr/lidarr

### PR DESCRIPTION
**Pull request by tboerger**
###### Description of changes

I have added more options to the prowlarr package which is pretty much similar to the other modules from the *rr universe.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by mweinelt — CHANGES_REQUESTED** [review]
We agreed when prowlarr was introduced that it doesn't have the same requirements as the other arr software wrt file permissions, becaues it is only access via its API, therefore `DynamicUser` was a concious decision and I'd like to hear a reason why it should be removed or I'll veto this change.

https://github.com/NixOS/nixpkgs/pull/136039#discussion_r722317458

**Comment by tboerger** [comment]
I have done that with the intention to be able to override the user and also the path where the state gets stored. By default it should not change much.

**Comment by mweinelt** [comment]
Can you use a bind mount instead? Systemd will do the right thing and wait for the bind mount before starting the service.

**Comment by tboerger** [comment]
I haven't tried bind mounts... But since this module is already running locally for me I think I will even keep that if it's not accepted upstream.

**Comment by tboerger** [comment]
Closing this in favor of my personal module

**Pull request closed without merging**
