### PR TITLE
Update php build configuration

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Changes in this PR:
- Drop support build php wint maraidb connector-c. Php not support version 3.1.
- Remove unused configure flags. The `configureFlags+` option is not applied during build.
- Add option `config.php.pear`
- Add option `config.php.ipv6`
- Build PHP with an external GD library
- Update `preConfigure` phase. Needed for a correct build from git-source.

cc @etu @aanderse 
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by aanderse** [comment]
@Izorkin sorry for delay.
@etu I haven't had a chance to look at this yet. Do you have any capacity over the next couple weeks to review this?

**Comment by Izorkin** [comment]
Updated and rebased.
cc @etu @aanderse @Mic92

**Review by Mic92 — APPROVED** [review]
That looks mostly fine to me. Have not tested yet.

**Comment by Izorkin** [comment]
Thanks!

**Pull request merged**
