### PR TITLE
tippecanoe: 1.35.0 -> 1.36.0

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change
[Changelog](https://github.com/mapbox/tippecanoe/blob/master/CHANGELOG.md)

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
WFM on macos 10.14. Wondering what the aarch64 failure is about though.

@ofborg build tippecanoe

**Comment by risicle** [comment]
Yup, seems to persist.

**Comment by sikmir** [comment]
I have no idea what is going wrong on aarch64... What is better way to proceed? Mark as not supported on aarch64?

**Comment by risicle** [comment]
Sad, but I guess it's the best thing to do. Might be worth opening a ticket upstream letting them know that their `coalesce-tract` test may have issues on non-x86.

It doesn't help that:

1. They appear to be doing bytewise comparisons of json output, which will obviously be unnecessarily sensitive to e.g. object key order.
2. We only have access to ofborg for aarch64, and can't inspect its filesystem after failure.

**Comment by sikmir** [comment]
> Sad, but I guess it's the best thing to do. Might be worth opening a ticket upstream letting them know that their `coalesce-tract` test may have issues on non-x86.

* marked as broken on aarch64
* upstream issue https://github.com/mapbox/tippecanoe/issues/881

**Comment by sikmir** [comment]
@risicle I've just tried to build tippecanoe on my aarch64 machine and it works just fine. Can we unbroke it on aarch64 and perhaps disable this test on aarch64 to not fail on CI?

**Comment by risicle** [comment]
Having worked a bit more with aarch64 packages now, there are quite a few which have slight disagreements in float precision with "expected" results that were presumably generated on x86. I think this is due to the existence of the x87 80bit extended precision mode.

Short answer: yes, but I would raise the issue upstream too if it isn't already.

**Comment by sikmir** [comment]
> Short answer: yes, but I would raise the issue upstream too if it isn't already.

Here is upstream issue: https://github.com/mapbox/tippecanoe/issues/881.

**Pull request merged**
