### PR TITLE
nixos/dhparams: Introduce a 'stateful' option

### PR DESCRIPTION
**Pull request by aszlig**
This option allows us to turn off stateful generation of Diffie-Hellman parameters, which in some way is still "stateful" as the generated DH params file is non-deterministic.

However what we can avoid with this is to have an increased surface for failures during system startup, because generation of the parameters is done during build-time.

Another advantage of this is that we no longer need to take care of cleaning up the files that are no longer used and in my humble opinion I would have preferred that #11505 (which puts the DH params in the Nix store) would have been merged instead of #22634 (which we have now).

Nevertheless, this now gives the user the choice to either get non-determinism in some store paths or an increased failure vector introduced during bootup.

Besides of the more obvious advantages pointed out, this also effects test runtime if more services are starting to use this (for example see #39507 and #39288), because generating DH params could take a long time depending on the bit size which adds up to test runtime.

If we generate the DH params in a separate derivation, subsequent test runs won't need to wait for DH params generation during bootup.

Apart from just adding the option I added a NixOS VM test to make sure I don't break the existing implementation plus I've cleaned up the module expression a bit.

Cc: @Ekleog

### CODE REVIEW

**Review by abbradar — APPROVED** [review]
NIce addition! Personally I don't like putting something non-deterministic into store but I do see advantages of that.

**Review by Ekleog — APPROVED** [review]
Great, thanks! Just a tiny question about bit size (not trying to ignite a flame war, if you think it's better with 4096 after reading my comment then please do so :))

**Comment by aszlig** [comment]
@Ekleog, @abbradar: I've added a new option `defaultBitSize`, which can be used to set a default for all the bit sizes in the defined parameters. In addition I updated the documentation a bit to give module developers a few hints about how to use the module in other modules and a release notes entry to make users aware of this.

**Comment by Ekleog** [comment]
LGTM, thanks! :+1:

**Review by Ekleog — APPROVED** [review]

**Pull request merged**
