### PR TITLE
cargo-depgraph: init at 1.2.2

### PR DESCRIPTION
**Pull request by figsoda**
###### Motivation for this change

Create dependency graphs for cargo projects using `cargo metadata` and graphviz

https://sr.ht/~jplatte/cargo-depgraph

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by legendofmiracles** [comment]
Running it in a rust repo prints what it seems to, but also these lines here:
```
crate from resolve not found in packages => dependencies, this should never happen!
crate from resolve not found in packages => dependencies, this should never happen!
crate from resolve not found in packages => dependencies, this should never happen!
crate from resolve not found in packages => dependencies, this should never happen!
crate from resolve not found in packages => dependencies, this should never happen!
```
At the top of the output, before the svg stuff

**Comment by figsoda** [comment]
I also had the same warnings, but the svg generated looked normal
I assumed it had nothing to do with packaging and ignored it

**Comment by figsoda** [comment]
@legendofmiracles If you are ok with it, I will merge this

**Review by legendofmiracles — APPROVED** [review]
The issue does indeed seem to be a general one, not related to nix: https://github.com/jplatte/cargo-depgraph/issues/10

**Comment by figsoda** [comment]
Didn't know this is also on github, checked sourcehut but couldn't figure out where issues are

**Pull request merged**
