### PR TITLE
vimPlugins.bufferize-vim: init

### PR DESCRIPTION
**Pull request by poscat0x04**
BTW do I need to run the update script?

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Kranzes — CHANGES_REQUESTED** [review]
That is not how you actually add a vim plugin on nixpkgs.
You can add bufferize by running this command:
`GITHUB_API_TOKEN=my_token ./pkgs/misc/vim-plugins/update.py --add "AndrewRadev/bufferize.vim" --proc 2` at the root of nixpkgs.
You will want to create a GitHub API token with at least `public_repo` access to avoid rate limiting when running the script.
The script also commits the changes so make sure you are on a clean branch.

**Comment by poscat0x04** [comment]
Oh ok, I thought those nix files were updated automatically.

**Comment by poscat0x04** [comment]
Well, I tried multiple times to update the plugins but they all errored out before finishing due to network issues.

**Comment by teto** [comment]
try again with `--proc 1` (it's the number of parallel jobs, the lower, the less likely you will hit issues )

**Comment by SuperSandro2000** [comment]
Closing due to inactivity

**Pull request closed without merging**
