### PR TITLE
audiobookshelf: 2.2.23 -> 2.3.3

### PR DESCRIPTION
**Pull request by jvanbruegge**
###### Description of changes

https://github.com/advplyr/audiobookshelf/releases/tag/v2.3.0
This release uses node-sqlite3, so python is needed to build it.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jvanbruegge** [comment]
cc @advplyr 
Only needed to add python as build-time dependency, so node-sqlite3 can build. Will update the version and mark as ready once it is released.

**Comment by jvanbruegge** [comment]
I've updated the PR to the latest patch release now

**Comment by wietsedv** [comment]
I'm assuming that the this PR is blocked by the `aarch64-darwin` test? Is there a known reason that this check is still in queue after more than 6 days? Also, if I'm not mistaken, the check will not do anything, since no `passthru.tests` is defined. The x86-variant and the linux variants have simply skipped.

Maybe this can be merged anyway regardless of the missing check.

**Comment by jvanbruegge** [comment]
@emilylange could this be merged? The package is not supported on darwin anyways

**Comment by emilylange** [comment]
> I'm assuming that the this PR is blocked by the `aarch64-darwin` test?

No, not necessarily. It probably just went under in the noise of all the other open PRs. Sorry for that.
In case this happens in the future again (which it probably will, because nixpkgs lol), I'd recommend posting the link in https://discourse.nixos.org/t/prs-ready-for-review/

A lot of committer (and non-commiters) watch that discourse topic and will get your attention that way.
And yes, this was originally intended as a hotfix... and is still with us in 2023...

> Is there a known reason that this check is still in queue after more than 6 days?

Yeah, ofborg (on aarch64-ofborg) is currently having issues and the person who has access to that infra and is the one who usually fixes such issue is on vacation rn.

Essentially a [Bus factor](https://en.wikipedia.org/wiki/Bus_factor) of one, I know, also not great.

---

Anyhow, thanks to both of you! :)
lgtm

**Comment by jvanbruegge** [comment]
Thanks!

**Pull request merged**
