### PR TITLE
lib: Fix #30902 on 18.03

### LINKED ISSUE #30902: Derivation platform checking compares against wrong machine
## Issue description

The logic in `pkgs/stdenv/generic/check-meta.nix` for checking the `meta.platforms` attribute currently compares `meta.platforms` against the `stdenv.system` attribute. In my cross-compilation environment `stdenv.system` is the double of my build platform, `x86_64-linux`.

It seems to me like this should rather be compared against `stdenv.hostPlatform.system`. Unfortunately, this attribute has slightly different semantics than `stdenv.system`. For instance, in the case of `armv7l-hf-multiplatform` it is `arm-linux` whereas the value expected by `uboot` is something like `armv7l-linux`. 

How much detail should `meta.system` capture?

Pinging @Ericson2314.

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

@vcunat this is a version of https://github.com/NixOS/nixpkgs/pull/34444 and all dependent and fix-up PRs for 18.03. I based that chain off the common ancestor of `release-18.03` and `master` so these are in fact the same commits (!), but we could of course do cherry-picks too per usual. 

There is 1 more commit needed to work around a uboot thing. That wasn't needed on `master` because @lopsided98 kindly including the proper solution in https://github.com/NixOS/nixpkgs/pull/36232 on staging, which was then recently merged back to master.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by ttuegel — APPROVED** [review]
Qt 5 parts look fine.

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/34645#issuecomment-378925954 this might be actually needed on 18.03 (as opposed to just nice) in order to disable some MUSL-only builds on hydra.

**Review by zimbatm — APPROVED** [review]
nice work!

**Comment by Ericson2314** [comment]
It's basically no rebuild and so easy to revert. So I'll just go off @zimbatm's review for now? It's my understanding that post-release things are a bit more relaxed; hope I'm not wrong about that.

**Pull request merged**
