### PR TITLE
Updating plan9port

### PR DESCRIPTION
**Pull request by bbarker**
###### Motivation for this change

To update plan9port (2+ years since last update on nixpkgs)

cc @ftrvxmtrx  @kovirobi 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bbarker** [comment]
@samueldr confirmed this was working on NixOS; the issue seems to be that it wouldn't build on Ubuntu for me, nor would the original version before this PR. However, the binaries seem to run without issue.

**Comment by KoviRobi** [comment]
Could you post the command that built those .o files with the wrong type (or perhaps the whole build log)? I wonder if it is something along the lines of those being build by plan9port's make command, which autodetects the compiler to be the Ubuntu one, which is perhaps compiling 32/64-bit binaries for your system, which uses a 64/32-bit Nix (wild guess here)

**Comment by bbarker** [comment]
@KoviRobi , here is my build log: https://gist.github.com/bbarker/a875119308731ca8d13cf59a132fc09e - still not sure what is causing the ELF issue as the only gcc in my container comes from Nix. But it looks like the issue with missing graphical binaries may be related to X11 includes.

**Comment by KoviRobi** [comment]
It builds for me too, without any problems (on NixOS), but I suspect the problem you might have is from
```
* Compiler version:
        gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) 
```
in your log (there is a shell file called `9c`, which might need to be patched) [unless Nix on other distributions uses the distribution's compiler]. Unsure why you have a problem with `X11/Xlib.h`, when the `default.nix` includes `libX11`. Also, if you are building fontsrv, you can probably just remove the fontsrv.patch

**Comment by bbarker** [comment]
@KoviRobi 

I got quite a bit further with the commit I pushed, but ultimate it still fails:

```
>>> cd /tmp/nix-build-plan9port-2018-09-20.drv-0/plan9port-a82a8b6/src/cmd/rio; mk all
9l -o o.rio client.o color.o cursor.o error.o event.o grab.o key.o main.o manage.o menu.o rio.o -L/nix/store/9xp35nsxrf959vnv2lf170xhfxn951b6-libXt-1.1.5-dev/include/lib/ -lXext -lX11
/usr/bin/x86_64-linux-gnu-ld: cannot find -lXext
/usr/bin/x86_64-linux-gnu-ld: cannot find -lX11
collect2: error: ld returned 1 exit status
mk: 9l -o o.rio ...  : exit status=exit(1)
mk: for i in ...  : exit status=exit(1)
mk: for i in ...  : exit status=exit(1)
```

What helped was adding more of the libs to `LOCAL.config`, but, seems like that isn't being used in the above link command.

As for gcc, I think that may just be a funny way it is reporting both gcc and OS together, since I have:

```
[nix-shell:acme]$ gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[nix-shell:acme]$ which gcc
/nix/store/iw94llkj05wgaz268mlzvgx8jkbi1ss0-gcc-wrapper-7.3.0/bin/gcc
```

Also, may have found another issue that may warrant opening a separate issue to track if you can confirm; I can't seem to get `ssam` to work at all; always get this error:

$ echo "foo" | 9 ssam 's/foo/bar/'
rc (/nix/store/7wq4afwhl5fd8ghfigv8qxsbd5widhpv-plan9port-2016-04-18/plan9/bin/rc): null list in concatenation

**Comment by Ekleog** [comment]
(triage) If I read correctly, this PR updates `plan9port`, works on as many platforms as the previous version of `plan9port` did, and fails with the same error as the previous `plan9port` did on other platforms. If so, maybe we can merge that and open an issue / another PR to solve the remaining issues? :)

@GrahamcOfBorg build plan9port

@bbarker If I read correctly, the change to the BUGGERED line in https://github.com/NixOS/nixpkgs/pull/47067/files#diff-9ed5354c1be372c549bf762e4b21f484 is now a no-op, and this patch could thus be simplified? :)

**Comment by bbarker** [comment]
@Ekleog This sounds like a good plan. I removed the fontsrv patch. I'll create a new issue summarizing what is here after merge; hopefully I'll get some time to continue working on it in the coming weeks. Feel free to squash and merge this one.

**Comment by samueldr** [comment]
@GrahamcOfBorg build plan9port

I want to see the CI output for darwin.

**Review by samueldr — APPROVED** [review]
@bbarker confirm that the squashed commit looks fine (especially with the commit message):

 * https://github.com/samueldr/nixpkgs/commit/7a86c6760a758e3305e668249bd8ddf88c457529

This is what I would merge. Everything I did locally worked fine. Both acme and sam started. 9term too, with rc. I don't know more about plan9 and plan9port to judge, but I think this is plenty.

**Comment by bbarker** [comment]
Thanks @samueldr , looks good and sounds good to me as well, though I'm certainly not a plan9 expert either. Once a build hits a channel I'll test the binaries (since I can't build them all yet).

**Pull request merged**
