### PR TITLE
mariadb: 10.3.17 -> 10.3.18

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Update package to verion 10.3.18
Changelog - https://mariadb.com/kb/en/library/mariadb-10318-changelog/
Fixed library location - https://github.com/NixOS/nixpkgs/pull/63355#issuecomment-521623538

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by disassembler** [comment]
@GrahamcOfBorg build mariadb.server mariadb.client

**Comment by disassembler** [comment]
running mysql nixos test locally as ofborg is broken

**Comment by Izorkin** [comment]
@disassembler local tests pass

**Comment by disassembler** [comment]
merged and added to release-19.09 branch

**Comment by vcunat** [comment]
According to Hydra, merging this PR broke build on darwin with:
```
CMake Error at cmake/plugin.cmake:284 (MESSAGE):
  Plugin AUTH_PAM cannot be built
Call Stack (most recent call first):
  CMakeLists.txt:416 (CONFIGURE_PLUGINS)
```
Issue: https://github.com/NixOS/nixpkgs/issues/69034

**Comment by vcunat** [comment]
BTW, the checks tab apparently showed this problem even before merging.  The breakage is blocking the channel.

**Comment by Izorkin** [comment]
@vcunat command `@GrahamcOfBorg build mariadb.server mariadb.client` did not work at that time.

**Comment by Izorkin** [comment]
Package `linux-pam` worked in Darwin?

**Comment by vcunat** [comment]
It doesn't depend on it
```
++ optional stdenv.isLinux linux-pam
```

**Pull request merged**
