### PR TITLE
nixos/stage-1: fix mount replacement in extra-utils

### LINKED ISSUE #243820: `extra-utils` is not allowed to refer to the following paths `util-linux-2.39-mount`
### Describe the bug

Trying to update a system to the latest `nixpkgs-unstable` "release" (`29bcead8405c`) results in the following error:

```
error: output '/nix/store/ibzgyvbn19ddwf40j49rsqxcyiy7bxzp-extra-utils' is not allowed to refer to the following paths:
         /nix/store/qhvwgvvm60s6df4samryixrrzblrlnha-util-linux-2.39-mount
error: 1 dependencies of derivation '/nix/store/8k5bsbpa3ndpji6r9wv70pab1gapaz0n-stage-1-init.sh.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hkwswshix57mzc34by49rk2ibxsa2jsb-initrd-linux-6.3.12.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yg32jyqpr85306rbqysvqrfyagjrppl6-nixos-system-tanker-23.11.20230715.29bcead.drv' failed to build
```

### Steps To Reproduce

I don't know how to easily reproduce this. At least for me, it seems to happen because the [ZFS module](https://github.com/NixOS/nixpkgs/blob/29bcead8405cfe4c00085843eb372cc43837bb9d/pkgs/os-specific/linux/zfs/generic.nix#L69) needs to adjusted. So:

Try to update a system that (at least) uses ZFS I guess ...

### Expected behavior

No build failure.

### Screenshots

N/A

### Additional context

It looks like this was caused by #236463.

I'm not sure if the ZFS module is the only place that needs to be adjusted after this PR has landed.

### Notify maintainers

@lheckemann (authored the PR mentioned above)
@ElvishJerricco (approved the PR mentioned above)
@jcumming @jonringer @globin @raitobezarius (ZFS maintainers)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.12, NixOS, 23.11 (Tapir), 23.11.20230715.46ed466`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/store/b6vnb230hgq98bbp7xpgszm7bk2m0bz5-source`
```

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Description of changes

Closes #243820

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by lheckemann — COMMENTED** [review]
Seems like a reasonable fix (EDIT: if this fixes it at all), though it would probably be better if copy_bin_and_libs were to chase symlinks. I'll open an alternative PR.

**Comment by SuperSandro2000** [comment]
I tested this on one machine which had the linked build failure and this fixed the deployment. Maybe we should merge this first and you're alternative better fix we do afterwards to unblock people.

**Comment by lheckemann** [comment]
Does https://github.com/NixOS/nixpkgs/pull/244177 also fix it?

**Review by magnetophon — APPROVED** [review]
works for me, thanks!

**Comment by magnetophon** [comment]
> Does #244177 also fix it?

Yes, it does, thanks!

**Comment by SuperSandro2000** [comment]
So we want to merge both or only one?

**Comment by magnetophon** [comment]
> So we want to merge both or only one?

Both are trying to fix the same issue and they work on their own.
Why would you want to merge both?

**Comment by SuperSandro2000** [comment]
> Why would you want to merge both?

If the symlink ever changes we would have the same problem again.

**Comment by lheckemann** [comment]
I think mine is the more correct solution, since it will work if any other tools that are needed by the initramfs become symlinks. Not sure the approach in this PR provides any value after that?

**Pull request merged**
