### PR TITLE
cocoapods: 1.6.2 -> 1.7.1

### PR DESCRIPTION
**Pull request by lilyball**
Also cocoapods-beta: 1.7.0.rc.2 -> 1.7.1.

###### Motivation for this change
https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.1

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jonringer** [comment]
I know cocoapods is usually targeted toward darwin, but I was able build and run pod on x86_64-linux

```
[16:35:49] jon@jon-workstation ~/projects/nixpkgs (cocoapods)
$ ./result/bin/pod --version
1.7.0
```

**Comment by lilyball** [comment]
Thanks for checking! I suspect you can't get much further than checking version though as even just installing Pods relies on Xcode (cocoapods loads Xcode's private frameworks to write out project files for some harebrained reason).

**Comment by jonringer** [comment]
Yea, i mean, it's just a ruby tool, so the tool itself makes sense it can run on linux. But just after that, it becomes very platform specific. Just thought it was funny.

**Comment by lilyball** [comment]
Updated to 1.7.1, which was just released today.

**Pull request merged**
