### PR TITLE
pythonPackages.pylibconfig: init at 0.2.4

### PR DESCRIPTION
**Pull request by lsix**

### CODE REVIEW

**Comment by FRidh** [comment]
Why are the tests disabled?

**Comment by lancelotsix** [comment]
The tests are not distributed in the archive:

```sh
$ curl https://pypi.python.org/packages/source/p/pylibconfig2/pylibconfig2-0.2.4.tar.gz | tar tz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5161  100  5161    0     0  25369      0 --:--:-- --:--:-- --:--:-- 25299
pylibconfig2-0.2.4/
pylibconfig2-0.2.4/PKG-INFO
pylibconfig2-0.2.4/pylibconfig2/
pylibconfig2-0.2.4/pylibconfig2/__init__.py
pylibconfig2-0.2.4/pylibconfig2/conf_types.py
pylibconfig2-0.2.4/pylibconfig2/parsing.py
pylibconfig2-0.2.4/pylibconfig2.egg-info/
pylibconfig2-0.2.4/pylibconfig2.egg-info/dependency_links.txt
pylibconfig2-0.2.4/pylibconfig2.egg-info/PKG-INFO
pylibconfig2-0.2.4/pylibconfig2.egg-info/SOURCES.txt
pylibconfig2-0.2.4/pylibconfig2.egg-info/top_level.txt
pylibconfig2-0.2.4/README.rst
pylibconfig2-0.2.4/setup.cfg
pylibconfig2-0.2.4/setup.py
```

The github repo do not seem to have proper tags for realeases. I could browse the history to find a proper point for this release and go with something like that:

```sh
$ curl https://codeload.github.com/heinzK1X/pylibconfig2/tar.gz/d1cad286ce1c54135117c809881fbef1f4d674d0 | tar tz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18324  100 18324    0     0  30655      0 --:--:-- --:--:-- --:--:-- 30642
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/.gitignore
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/.travis.yml
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/LICENSE
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/README.rst
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/pylibconfig2/
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/pylibconfig2/__init__.py
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/pylibconfig2/conf_types.py
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/pylibconfig2/parsing.py
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/pylibconfig2/test/
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/pylibconfig2/test/__init__.py
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/pylibconfig2/test/test.py
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/requirements.txt
pylibconfig2-d1cad286ce1c54135117c809881fbef1f4d674d0/setup.py
```

but I usually prefer to stay with the published archive.

**Comment by FRidh** [comment]
Yes, I agree on using the published archive. I suggest you include, e.g. in the commit message, why tests are disabled.

**Comment by lancelotsix** [comment]
Yes, I’ll amend the commit ASAP.

**Comment by lancelotsix** [comment]
Updates.

**Pull request merged**
