### PR TITLE
xxHash: add pkg-config file fix, clean up a bit

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

Add a patch to fix the pkg-config file generated by the new cmake-based build. Fixes tdesktop and friends. No nixpkgs-review because this is a lot, but tdesktop builds fine.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Ping @RasmusRendal @vcunat

**Review by RasmusRendal — APPROVED** [review]

**Review by Mindavi — APPROVED** [review]

**Review by ilya-fedin — APPROVED** [review]

**Comment by vcunat** [comment]
A very large rebuild :-(  but yes, it looks like a regression since nixpkgs master.

**Comment by Mindavi** [comment]
This was merged, but github didn't properly register.

**Comment by K900** [comment]
Indeed.

**Comment by vcunat** [comment]
Commit 20972d657edef0ca was merged but this PR shows commit dc8c268.  I'm not sure how this happened.

**Comment by K900** [comment]
Probably because of your Committed-by

**Pull request closed without merging**
