### PR TITLE
stdenv.darwin: bootstrap darwin using updated tools

### PR DESCRIPTION
**Pull request by ghost**
- unify the x64 and aarch64 unpack process
- use the tools from change https://github.com/NixOS/nixpkgs/pull/295557
- unpin libxml for python-minimal build as it crashes clang due to libxml version issues and `DYLD_LIBRARY_PATH`

testing:
- built stdenv for aarch64 and x64 with tools from hydra 

## [how to request a seed update](https://github.com/NixOS/nixpkgs/tree/master/maintainers/scripts/bootstrap-files#how-to-request-the-bootstrap-seed-update)
   1. get approval for PR
   2. request hydra build uploaded to tarballs.nixos.org

once tools are uploaded will switch to ready to review so the PR doesn't get merged prematurely.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by toonn — APPROVED** [review]
LGTM (didn't rerun a stdenv build though).

**Comment by a-n-n-a-l-e-e** [comment]
cc @lovesegfault for uploading new bootstrap-tools to tarballs.nixos.org

### aarch64-apple-darwin
```
$ sha256sum /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/*
63041266fcdb3a8db03829dc06c9e969ca3b660f755101c4950530798fdac454  /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/bootstrap-tools.tar.xz
77593ef6c27aa4a8272799f046427864b3359871de64a3f7fba6dd5e2b7f12d8  /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/unpack.nar.xz
```
Suggested commands to upload files to 'tarballs.nixos.org':
```
nix-store --realize /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools
aws s3 cp --recursive --acl public-read /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/ s3://nixpkgs-tarballs/stdenv/aarch64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e
aws s3 cp --recursive s3://nixpkgs-tarballs/stdenv/aarch64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e ./
sha256sum bootstrap-tools.tar.xz unpack.nar.xz
```

### x86_64-apple-darwin
```
$ sha256sum /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/*
5d44af17dea8350954b9b6daa8c2883bcb2f2f1633c1987d264b20032091cb3d  /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/bootstrap-tools.tar.xz
9d863677c42daffc1a7b2d9f775debd37b9ab4804d167a2d56f61c3f80d28dc4  /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/unpack.nar.xz
```
Suggested commands to upload files to 'tarballs.nixos.org':
```
nix-store --realize /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools
aws s3 cp --recursive --acl public-read /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/ s3://nixpkgs-tarballs/stdenv/x86_64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e
aws s3 cp --recursive s3://nixpkgs-tarballs/stdenv/x86_64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e ./
sha256sum bootstrap-tools.tar.xz unpack.nar.xz
sha256sum /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/*
```

**Comment by a-n-n-a-l-e-e** [comment]
ping @lovesegfault https://github.com/NixOS/nixpkgs/pull/295558#issuecomment-2016320691 for updating the tools into tarball.nixos.org

**Comment by a-n-n-a-l-e-e** [comment]
> @a-n-n-a-l-e-e I'm happy to help with uploading the tarballs, but I'd like to see an approval from @reckenrode and for this to be un-drafted before that :)

this is in draft mode so it doesn't get committed by accident, as noted in the PR comment to avoid incidents like  https://github.com/NixOS/nixpkgs/pull/255451

**Comment by reckenrode** [comment]
I’ll take a look at it this evening. It’d definitely be nice to update the bootstrap tools and simplify the stdenv bootstrap.

**Review by reckenrode — APPROVED** [review]
lgtm. I successfully built the stdenv on both aarch64-darwin and x86_64-darwin.

**Comment by lovesegfault** [comment]
Uploaded:
```console
$ nix-store --realize /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools
this path will be fetched (78.61 MiB download, 276.71 MiB unpacked):
  /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools
copying path '/nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools' from 'https://cache.nixos.org'...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools

$ sha256sum /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/*
63041266fcdb3a8db03829dc06c9e969ca3b660f755101c4950530798fdac454  /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/bootstrap-tools.tar.xz
77593ef6c27aa4a8272799f046427864b3359871de64a3f7fba6dd5e2b7f12d8  /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/unpack.nar.xz

$ aws s3 cp --recursive --acl public-read /nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/ s3://nixpkgs-tarballs/stdenv/aarch64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e
upload: ../../../../nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/unpack.nar.xz to s3://nixpkgs-tarballs/stdenv/aarch64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e/unpack.nar.xz
upload: ../../../../nix/store/sxc61dx6sng17lpp2rvv1q2apxj7bvq2-stdenv-bootstrap-tools/on-server/bootstrap-tools.tar.xz to s3://nixpkgs-tarballs/stdenv/aarch64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e/bootstrap-tools.tar.xz

$ aws s3 cp --recursive s3://nixpkgs-tarballs/stdenv/aarch64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e ./
download: s3://nixpkgs-tarballs/stdenv/aarch64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e/unpack.nar.xz to ./unpack.nar.xz
download: s3://nixpkgs-tarballs/stdenv/aarch64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e/bootstrap-tools.tar.xz to ./bootstrap-tools.tar.xz

$ sha256sum bootstrap-tools.tar.xz unpack.nar.xz
63041266fcdb3a8db03829dc06c9e969ca3b660f755101c4950530798fdac454  bootstrap-tools.tar.xz
77593ef6c27aa4a8272799f046427864b3359871de64a3f7fba6dd5e2b7f12d8  unpack.nar.xz

$ nix-store --realize /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools
this path will be fetched (90.25 MiB download, 298.00 MiB unpacked):
  /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools
copying path '/nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools' from 'https://cache.nixos.org'...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools

$ sha256sum /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/*
5d44af17dea8350954b9b6daa8c2883bcb2f2f1633c1987d264b20032091cb3d  /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/bootstrap-tools.tar.xz
9d863677c42daffc1a7b2d9f775debd37b9ab4804d167a2d56f61c3f80d28dc4  /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/unpack.nar.xz

$ aws s3 cp --recursive --acl public-read /nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/ s3://nixpkgs-tarballs/stdenv/x86_64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e
upload: ../../../../nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/unpack.nar.xz to s3://nixpkgs-tarballs/stdenv/x86_64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e/unpack.nar.xz
upload: ../../../../nix/store/z2gdi0ha3w9scbgl3jv6431hd52d4b3j-stdenv-bootstrap-tools/on-server/bootstrap-tools.tar.xz to s3://nixpkgs-tarballs/stdenv/x86_64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e/bootstrap-tools.tar.xz

$ aws s3 cp --recursive s3://nixpkgs-tarballs/stdenv/x86_64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e ./
download: s3://nixpkgs-tarballs/stdenv/x86_64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e/unpack.nar.xz to ./unpack.nar.xz
download: s3://nixpkgs-tarballs/stdenv/x86_64-apple-darwin/d03ae62edd9402b6ee0471cb1543e1e19585025e/bootstrap-tools.tar.xz to ./bootstrap-tools.tar.xz

$ sha256sum bootstrap-tools.tar.xz unpack.nar.xz
5d44af17dea8350954b9b6daa8c2883bcb2f2f1633c1987d264b20032091cb3d  bootstrap-tools.tar.xz
9d863677c42daffc1a7b2d9f775debd37b9ab4804d167a2d56f61c3f80d28dc4  unpack.nar.xz
```

**Comment by a-n-n-a-l-e-e** [comment]
thanks!

**Comment by a-n-n-a-l-e-e** [comment]
reverting due to xz vulnerability included in the tools.
 https://www.openwall.com/lists/oss-security/2024/03/29/4

**Pull request merged**
