### PR TITLE
ryujinx: 1.1.733 -> 1.1.819

### LINKED ISSUE #229755: Update request: ryujinx 1.1.733 → 1.1.747
- Package name: ryujinx
- Latest released version: 1.1.747

- Current version on the unstable channel: 1.1.743
- Current version on the stable/release channel: 1.1.327

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@IvarWithoutBones @06kellyjac 

-----

Note for maintainers: Please tag this issue in your PR.

Finally, for anyone who stumbles upon this issues, and wants an overlay to get them to 1.1.747 without waiting for the package to be updated:
```
(final: prev: {
  ryujinx = prev.ryujinx.overrideAttrs (old: let oldConfigureHook = (builtins.head (builtins.filter (p: p.name == "dotnet-configure-hook") old.nativeBuildInputs)); in rec {
    pname = "ryujinx";
    version = "1.1.747";
    src = prev.fetchFromGitHub {
      owner = "Ryujinx";
      repo = "Ryujinx";
      sha256 = "sha256-GGr/SbnzRRdB1CpTMu3KKbO1MBwzR2/gfTPx95lczSo=";
      rev = "${version}";
    };
    testProjectFile = "src/" + old.testProjectFile; # Source was moved inside of src/ subdirectory
    nugetDeps = prev.mkNugetDeps {
      name = "${pname}-${version}";
      nugetDeps = (args:
      (builtins.filter (p:
          p.name != "System.IdentityModel.Tokens.Jwt.6.29.0.nupkg"
          && p.name != "Microsoft.IdentityModel.JsonWebTokens.6.29.0.nupkg"
          && p.name != "Microsoft.IdentityModel.Tokens.6.29.0.nupkg"
          && p.name != "Microsoft.IdentityModel.Logging.6.29.0.nupkg"
          && p.name != "Microsoft.IdentityModel.Abstractions.6.29.0.nupkg"
        ) (import old.nugetDeps args))
      ++ [
          (args.fetchNuGet { pname = "Microsoft.IdentityModel.JsonWebTokens"; version = "6.30.0"; sha256 = "sha256-n1pPDnp30tEY90NfvVKUIKJik+2NJZLWZs1TSmQ7i/Q="; })
          (args.fetchNuGet { pname = "Microsoft.IdentityModel.Tokens"; version = "6.30.0"; sha256 = "sha256-H8LpCuW8gVV3H1jYBS/Hr6+vzbnw2y+iqFPO9HnVEqI="; })
          (args.fetchNuGet { pname = "Microsoft.IdentityModel.Logging"; version = "6.30.0"; sha256 = "sha256-xNiZDcuKaXSIBW6x8p3Qz2lyLHT2CKfhuRbEvUWKaI0="; })
          (args.fetchNuGet { pname = "Microsoft.IdentityModel.Abstractions"; version = "6.30.0"; sha256 = "sha256-x3AirIVNzwaMPL9Mc2pDfNYYFpMXYWcjnVLk3gm8cHY="; })
          (args.fetchNuGet { pname = "System.IdentityModel.Tokens.Jwt"; version = "6.30.0"; sha256 = "sha256-MiijECyyI8QagGCMgvfVjxJjYo6FP9VgCOwLPEQfa6U="; })
        ]
      );
    };
    dotnet-sdk = prev.dotnetCorePackages.sdk_7_0;
    sdkDeps = prev.lib.lists.flatten [ dotnet-sdk.packages ];
    sdkSource = prev.mkNugetSource {
      name = "dotnet-sdk-${dotnet-sdk.version}-source";
      deps = sdkDeps;
    };
    dependenciesSource = prev.mkNugetSource {
      name = "${pname}-${version}-dependencies-source";
      description = "A Nuget source with the dependencies for ${pname}-${version}";
      deps = [ nugetDeps ];
    };
    nuget-source = prev.symlinkJoin {
      name = "${pname}-${version}-nuget-source";
      paths = [ dependenciesSource sdkSource ];
    };
    nativeBuildInputs = (builtins.filter (p: p.name != "dotnet-configure-hook") old.nativeBuildInputs) ++ [
      (oldConfigureHook.overrideAttrs (old: {
        nugetSource = nuget-source;
      }))
    ];
  });
})
```

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Description of changes

Update ryujinx to 1.1.819

resolves #229755

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by mdarocha — APPROVED** [review]

**Comment by SuperSamus** [comment]
Tested myself, works.
(I tried with an updated version:
```
  version = "1.1.773"; # Based off of the official github actions builds: https://github.com/Ryujinx/Ryujinx/actions/workflows/release.yml

  src = fetchFromGitHub {
    owner = "Ryujinx";
    repo = "Ryujinx";
    rev = "40c17673f5a1a7c96f548dc4efaf05bba832a340";
    sha256 = "sha256-wT2j5oVCgcQFYIcsXphDqhCzp2sqOssa3rugrvLaR+0=";
  };
```
)

**Comment by mhuesch** [comment]
I just made an update for

ryujinx: 1.1.733 -> 1.1.787

given the crazy pace of updates Ryujinx lately (TOTK release) idk what the preferred update cadence would be. some of these "versions" might not be stable...

in any rate, leaving this patch in case it helps anyone. I can make a PR too, but maybe it'd be better to wait to update nixpkgs until Ryujinx has calmed down?

```
diff --git a/pkgs/applications/emulators/ryujinx/default.nix b/pkgs/applications/emulators/ryujinx/default.nix
index 61318b300b1..8627b9a5201 100644
--- a/pkgs/applications/emulators/ryujinx/default.nix
+++ b/pkgs/applications/emulators/ryujinx/default.nix
@@ -29,13 +29,13 @@
 
 buildDotnetModule rec {
   pname = "ryujinx";
-  version = "1.1.733"; # Based off of the official github actions builds: https://github.com/Ryujinx/Ryujinx/actions/workflows/release.yml
+  version = "1.1.787"; # Based off of the official github actions builds: https://github.com/Ryujinx/Ryujinx/actions/workflows/release.yml
 
   src = fetchFromGitHub {
     owner = "Ryujinx";
     repo = "Ryujinx";
-    rev = "9f12e50a546b15533778ed0d8290202af91c10a2";
-    sha256 = "1d1hg2sv0h56a56xnarcfp73df3rbw3iax85g258l6w2kxhkc42a";
+    rev = "e0544dd9c74e86cca6ee37c4d521d2d07f9ccdcc";
+    sha256 = "tKI9t9hTK7PQ28gXeS6V/dw94FA5eIVyNOnsKg6o9+Y=";
   };
 
   dotnet-sdk = dotnetCorePackages.sdk_7_0;
@@ -80,7 +80,7 @@ buildDotnetModule rec {
   ];
 
   projectFile = "Ryujinx.sln";
-  testProjectFile = "Ryujinx.Tests/Ryujinx.Tests.csproj";
+  testProjectFile = "src/Ryujinx.Tests/Ryujinx.Tests.csproj";
   doCheck = true;
 
   dotnetFlags = [
diff --git a/pkgs/applications/emulators/ryujinx/deps.nix b/pkgs/applications/emulators/ryujinx/deps.nix
index 2eff905dead..5aab354498d 100644
--- a/pkgs/applications/emulators/ryujinx/deps.nix
+++ b/pkgs/applications/emulators/ryujinx/deps.nix
@@ -50,10 +50,10 @@
   (fetchNuGet { pname = "Microsoft.CSharp"; version = "4.7.0"; sha256 = "0gd67zlw554j098kabg887b5a6pq9kzavpa3jjy5w53ccjzjfy8j"; })
   (fetchNuGet { pname = "Microsoft.DotNet.PlatformAbstractions"; version = "3.1.6"; sha256 = "0b9myd7gqbpaw9pkd2bx45jhik9mwj0f1ss57sk2cxmag2lkdws5"; })
   (fetchNuGet { pname = "Microsoft.Extensions.DependencyModel"; version = "6.0.0"; sha256 = "08c4fh1n8vsish1vh7h73mva34g0as4ph29s4lvps7kmjb4z64nl"; })
-  (fetchNuGet { pname = "Microsoft.IdentityModel.Abstractions"; version = "6.29.0"; sha256 = "06sdjg78764ycaq3bd32daacd9pjsvkihdzrw8d1cnmk3c42kvq3"; })
-  (fetchNuGet { pname = "Microsoft.IdentityModel.JsonWebTokens"; version = "6.29.0"; sha256 = "0iydfzz4vzzpx24q8mgvc3n289s00inc19x6a0w2v378mx4jkfl0"; })
-  (fetchNuGet { pname = "Microsoft.IdentityModel.Logging"; version = "6.29.0"; sha256 = "04vj5h638ljz2fylr2idgjbfq5lzbw79m5ixcj1ikl4ydl9jhp9p"; })
-  (fetchNuGet { pname = "Microsoft.IdentityModel.Tokens"; version = "6.29.0"; sha256 = "05crx7w79m3jxlbnfc2c8i63m5z6h28y04qv6sc84312rzi2yw8c"; })
+  (fetchNuGet { pname = "Microsoft.IdentityModel.Abstractions"; version = "6.30.1"; sha256 = "1jb7za7kc41zx4vafpmyj42vzqb407b34npb9g6f42sk7127hip1"; })
+  (fetchNuGet { pname = "Microsoft.IdentityModel.JsonWebTokens"; version = "6.30.1"; sha256 = "1c1hs0nrzlrpvdrpj01yr7cdknh19gdxrahndb5fmn8p4k1vljlv"; })
+  (fetchNuGet { pname = "Microsoft.IdentityModel.Logging"; version = "6.30.1"; sha256 = "02dkmh0qc2sfayvhzp8fgvn58b84yn8z4x3aijvjqahcwv14wfzs"; })
+  (fetchNuGet { pname = "Microsoft.IdentityModel.Tokens"; version = "6.30.1"; sha256 = "1283v1ynl7wp5llyswj2nd8l3pkj7yhcksy2slanid52iyqzzan1"; })
   (fetchNuGet { pname = "Microsoft.IO.RecyclableMemoryStream"; version = "2.3.2"; sha256 = "115bm7dljchr7c02hiv1r3l21r22wpml1j26fyn2amaflaihpq4l"; })
   (fetchNuGet { pname = "Microsoft.NET.Test.Sdk"; version = "17.5.0"; sha256 = "00gz2i8kx4mlq1ywj3imvf7wc6qzh0bsnynhw06z0mgyha1a21jy"; })
   (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "1.0.1"; sha256 = "01al6cfxp68dscl15z7rxfw9zvhm64dncsw09a1vmdkacsa2v6lr"; })
@@ -177,7 +177,7 @@
   (fetchNuGet { pname = "System.Globalization"; version = "4.3.0"; sha256 = "1cp68vv683n6ic2zqh2s1fn4c2sd87g5hpp6l4d4nj4536jz98ki"; })
   (fetchNuGet { pname = "System.Globalization.Calendars"; version = "4.0.1"; sha256 = "0bv0alrm2ck2zk3rz25lfyk9h42f3ywq77mx1syl6vvyncnpg4qh"; })
   (fetchNuGet { pname = "System.Globalization.Extensions"; version = "4.0.1"; sha256 = "0hjhdb5ri8z9l93bw04s7ynwrjrhx2n0p34sf33a9hl9phz69fyc"; })
-  (fetchNuGet { pname = "System.IdentityModel.Tokens.Jwt"; version = "6.29.0"; sha256 = "09bpj7gginq25fiyq3za5i8wm482qbnx6qhm4dxb95jrl3mmb126"; })
+  (fetchNuGet { pname = "System.IdentityModel.Tokens.Jwt"; version = "6.30.1"; sha256 = "1f4x5sw9wpkk485lchl0nzdzkcy83s9b119c7g187x0qvkcvdpc2"; })
   (fetchNuGet { pname = "System.IO"; version = "4.1.0"; sha256 = "1g0yb8p11vfd0kbkyzlfsbsp5z44lwsvyc0h3dpw6vqnbi035ajp"; })
   (fetchNuGet { pname = "System.IO"; version = "4.3.0"; sha256 = "05l9qdrzhm4s5dixmx68kxwif4l99ll5gqmh7rqgw554fx0agv5f"; })
   (fetchNuGet { pname = "System.IO.Compression"; version = "4.1.0"; sha256 = "0iym7s3jkl8n0vzm3jd6xqg9zjjjqni05x45dwxyjr2dy88hlgji"; })
```

**Comment by SuperSamus** [comment]
Not related to the PR, but I just noticed that the input `stdenvNoCC` isn't used for anything.

**Comment by SuperSamus** [comment]
Is this PR dead?

**Comment by mdarocha** [comment]
> Is this PR dead?

No, just didn't have the time to work on it. I'll update it and hopefully it'll be ready to merge

**Comment by baduhai** [comment]
Might as well run the update script again, and ask for another review.

**Comment by 06kellyjac** [comment]
Arguably an update PR isn't dead because it's still an update, just not the latest.

People are always welcome to submit fresh PRs & ryujinx should be trivial to update due to the update script - `nix-shell ./maintainers/scripts/update.nix --argstr package ryujinx`

---

There was an issue when running the script, I think my laptop went to sleep. If there are any issues with the update ofborg should pick them up

**Comment by SuperSamus** [comment]
The PR title should be updated.

**Comment by 06kellyjac** [comment]
done

**Pull request merged**
