### PR TITLE
lutris: 0.5.8.4 -> 0.5.9.1

### LINKED ISSUE #141645: lutris-unwrapped 0.5.8.3 is outdated
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: lutris-unwrapped

current version: 0.5.8.4
desired version: 0.5.9

###### Notify maintainers

maintainers: @Chiiruno 

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by wackbyte**
###### Motivation for this change

update the `lutris` packages and close #141645

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 141904` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
  </ul>
</details>

**Comment by wackbyte** [comment]
I'm currently looking into what's wrong. It's very confusing, but I think I'm making progress.

**Review by jmc-figueira — APPROVED** [review]

**Comment by wackbyte** [comment]
The patch has been upstreamed: lutris/lutris#3754

**Comment by Artturin** [comment]
Feel free to tag me in a pr which updates lutris once there's a release with that

**Pull request merged**
