### PR TITLE
wrapFirefox renames

### LINKED ISSUE #12065: Re-organise firefox
Firefox, at present, comes in five different packages:

* firefox
* firefox-wrapper
* firefox-bin
* firefox-esr
* firefox-esr-wrapper

The issue is that that firefox package is inevitably not what the user wants, causing issues when they try to enable plugins or configure pulseaudio.

I suggest reorganising Firefox into the following package attributes:

* firefox (current firefox-wrapper, with name "firefox")
* firefox-unwrapped (current firefox, with name "firefox-no-plugins")
* firefox-esr (current firefox-esr-wrapper, with name "firefox-esr")
* firefox-esr-unwrapped (current firefox-esr, with name "firefox-esr-no-plugins")
* firefox-bin

This would match better with what users expect, both through `nix-env -i` and `config.systemPackages`, but would also break backwards compatibility for people who currently have the wrapperless Firefox installed. What do people think?

### PR DESCRIPTION
**Pull request by vcunat**
Fixes #12065. It's a thing that seems to confuse people.

Reviews are welcome; see individual commit messages for details. /cc @NixOS/nixpkgs-committers as it's a UX issue potentially affecting many people.

After it's clearer this/which solution is taken, I'll write up a changelog entry and ensure other docs is in sync.

### CODE REVIEW

**Comment by abbradar** [comment]
Yay! Just a week ago I had yet another question from someone regarding this.

**Comment by vcunat** [comment]
After this PR, `nix-env -u` will upgrade unwrapped browsers to the wrapped versions, which is fine... but wrapped browsers will just remain silently without upgrade and installing will try to have *both* versions in the environment. I'm afraid we can't really improve this without changing the way `nix-env -u` works.

**Comment by vcunat** [comment]
I also corrected the wrapper references [in our wiki](https://nixos.org/wiki/Enable_Browser_Plugins).

**Comment by edolstra** [comment]
Not sure this was an improvement. The previous names (`firefox` and `firefox-with-plugins`) seem more accurate to me. The new `firefox` is a misnomer: it's actually `firefox` plus a bunch of stuff.

**Comment by ttuegel** [comment]
The new name is much more *discoverable*. Before, if a new user wanted Firefox, they actually needed `firefox-with-plugins` in almost every case and it wasn't clear to them why. Now, if they want Firefox, the just need `firefox`, no explanation needed. Only an experienced Nixpkgs user would want the un-wrapped Firefox, but we may they will know how to find it in either case.

**Comment by vcunat** [comment]
> The new firefox is a misnomer: it's actually firefox plus a bunch of stuff.

By default it's only some gstreamer stuff which is probably useful for html5 playback.

**Comment by vcunat** [comment]
BTW, I believe we still do need some general user-approachable framework for handling plugins.

**Comment by edolstra** [comment]
@ttuegel No, you only install `firefox-with-plugins` if you want plugins, so it's perfectly discoverable. 

If you actually need `firefox-with-plugins` for HTML5 playback, that's a bug, and we should fix that instead. (I.e., the `firefox` base package should depend on gstreamer, which in fact it already does.)

@vcunat I agree.

**Pull request merged**
