### PR TITLE
python3.pkgs.rpy2: 2.9.5 -> 3.2.2

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

There have been significant changes, therefore it doesn't make sense
anymore to maintain the python2 and python3 version in the same file.
We'll be able to drop the python2 version soon, some time after we have
switched sage to python3.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
I would to split out the changes into 2 commits:

```
python2Packages.rpy2: freeze at 2.9.5
python3Packages.rpy2: 2.9.5 -> 3.2.2
```

**Comment by timokau** [comment]
But python2 rpy2 was already frozen at 2.8.6. The only difference is that previously, both versions were maintained in the same file because 2.9.x (the py3 version) was similar enough.

**Review by jonringer — COMMENTED** [review]
this does seem to cause a regression with sage:

```
builder for '/nix/store/ss4rkx5p5aciz5nidlrzr088y00951br-sage-tests-8.9.drv' failed with exit code 1; last 10 log lines:
  sage -t --long /nix/store/62xwy4d6055qshylxl7n63idga66d96b-sage-src-8.9/src/sage/schemes/elliptic_curves/ell_rational_field.py
      [847 tests, 132.16 s]
  sage -t --long /nix/store/62xwy4d6055qshylxl7n63idga66d96b-sage-src-8.9/src/sage/rings/function_field/function_field.py
      [750 tests, 211.04 s]
  ----------------------------------------------------------------------
  sage -t --long /nix/store/62xwy4d6055qshylxl7n63idga66d96b-sage-src-8.9/src/sage/matrix/matrix_space.py  # 1 doctest failed
  ----------------------------------------------------------------------
  Total time for all tests: 652.0 seconds
      cpu time: 10508.3 seconds
      cumulative wall time: 13614.3 seconds
cannot build derivation '/nix/store/4i6b3xy9yh0frl6zakibjm83wxz7l2iz-sage-8.9.drv': 1 dependencies couldn't be built
```

**Review by Mic92 — APPROVED** [review]

**Comment by timokau** [comment]
@jonringer I cannot reproduce that. Neither on this branch, nor on master. This PR really shouldn't change anything for sage, since sage uses the py2 version which is still pinned on the same version.

The full log would be interesting. Is the failure reproducible for you?

**Comment by timokau** [comment]
You can run just that one test like this:

```
nix-build -E 'with (import ./. {}); sage.tests.override { files = [ "src/sage/matrix/matrix_space.py" ];}'
```

**Comment by jonringer** [comment]
I was also running a few other reviews, and it looks like it failed on a performance test. Could have been starved for cpu resources.

If you feel confident it will pass on hydra, then I'm fine with it

**Pull request merged**
