### PR TITLE
gpaste: 3.16.3 → 3.18.2

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by garbas** [comment]
isn't this downgrading package from 3.18.2 to 3.18.2?

**Comment by DamienCassou** [comment]
If you are talking about 3.18.3, it doesn't exist yet. What happened is that this nix file got copied from the 3.16 directory (where there is a gpaste 3.16.3) to the 3.18 directory without any change. Before my patch, it is just not possible to get gpaste on gnome 3.18.

**Comment by DamienCassou** [comment]
I'm merging because it works locally and the travis failure doesn't seem related.

**Comment by vcunat** [comment]
Hehe, the diff really is slightly confusing
```diff
-  version = "${gnome3.version}.3";
+  version = "${gnome3.version}.2";
```

hiding that `gnome3.version` has been changed somewhere in the meantime.

**Comment by DamienCassou** [comment]
@vcunat indeed

**Comment by garbas** [comment]
@DamienCassou +1

**Comment by lethalman** [comment]
Using gnome3.version was a bad choice. Now we use the src.nix for gnome software. Feel free to avoid using gnome3.version.

**Pull request merged**
