### PR TITLE
root: explicitly opt-out GPL-licensed libraries/plugins

### PR DESCRIPTION
**Pull request by ShamrockLee**
###### Motivation for this change

Due to the "infectious" nature of GPL license, the parts of code that makes use of GPL-licensed libraries in the ROOT source tree, e.g. MathMore, are deliberately seperated, and most of them are not included by default.

Two of those third-party libraries, are FFTW and GSL. The former is excluded in the Nix expression building ROOT, but the latter is still part of the `buildInputs`.

To prevent researchers from being forced to GPL their analysis scripts, this PR explicitly disable GSL from the cmakeFlags and remove it from buildInputs. GPL licensed plugin `MathMore` and its reverse dependency `RooFitMore` are explicitly opt-out as well.

https://root.cern/doc/master/group__MathMore.html

This PR also add openblas and lapack as build inputs to satisfy the requirement of TMVA. For the former, TMVA falls back to GSL CBLAS when OpenBLAS isn't presented, but the latter is recommended. The latter is used by TMVA SOFIE.

https://root-forum.cern.ch/t/tmva-sofie-undefined-reference-to-sgemm/47248

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
> To prevent researchers from being forced to GPL their analysis scripts

What is your use case here? Unless you plan to release your code under a license that is not GPL-compatible or not release your code at all, this should not affect you.

**Comment by mohe2015** [comment]
I don't have to domain specific knowledge and am not a lawyer either but I don't thing the GPL "infects" Scripts that run with a specific interpreter that is GPL licensed.

**Comment by veprbl** [comment]
@mohe2015 With ROOT you also can link to its libraries: either from your code or when running macros via ACLiC, which invokes the compiler.

**Comment by veprbl** [comment]
> I've heard that once you publish (?) your code which is linked to a GPL-licensed library, you must license all of it under the terms of GPL.

That's not correct.

You are always free to publish your code with a license as permissive as you like. However, if you distribute binaries that are linked to a piece of GPL code (see definition in the text of GPL for what that means), you must ensure that full source code would be possible to provide to the consumers under terms of GPL. Hence the license of the non-GPL components better be provided under "GPL-compatible" licenses.

**Comment by veprbl** [comment]
Even if my interpretation is wrong (IANL), disabling FFTW and MathMore by default seems a bit excessive, as those features are relatively useful and popular. One is expected to use `overrideAttrs` to tailor `root` to their specific needs.

**Comment by ShamrockLee** [comment]
> One is expected to use `overrideAttrs` to tailor `root` to their specific needs.

That makes sense. Simply remove GSL from the buildInputs shourd be a better choice. The reverse dependency left would only be the Python-GSL interface after `openblas` is available for TMVA.

By the way, FFTW has been disabled from the cmakeFlags before this PR for some reason. Should we drop the limitation?

**Comment by veprbl** [comment]
If FFTW is disabled, it's probably because nobody had suggested to enable it yet, so we don't need to do anything about it. Regarding the GSL, it seems like it's needed for MathMore, is that correct?

**Comment by ShamrockLee** [comment]
> Regarding the GSL, it seems like it's needed for MathMore, is that correct?

It turns out that MathMore is enabled (by default) once GSL is included, which is contrary to my previous understanding. Maybe I should leave it as is.

https://root.cern/doc/master/group__MathMore.html

Should I open anothe PR to add OpenBLAS and LAPACK, or simply change the title and PR message and do it here?

**Comment by veprbl** [comment]
> Should I open anothe PR to add OpenBLAS and LAPACK, or simply change the title and PR message and do it here?

Whichever you prefer

**Comment by veprbl** [comment]
I've noticed we don't enable TMVA explicitly. You might want to add that, if you use it.

**Comment by ShamrockLee** [comment]
@veprbl Thanks a lot for your help.

I'll close this PR to preserve the discussion and avoid confusion. I would open another PR for the TMVA part.

**Pull request closed without merging**
