### PR TITLE
appstream: 0.14.4 → 0.15.2

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

https://github.com/ximion/appstream/blob/v0.15.2/NEWS

- https://github.com/ximion/appstream/commit/fd5cdddeb6d0676e1d0024665c9037f8a63ad80a They provide installed tests now.
- https://github.com/ximion/appstream/commit/a8186ed96125f93b8963a8265ac42f56a837fb2b They use libxmlb instead of LMDB now.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin (using GitHub Actions)
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build appstream appstream.passthru.tests libsForQt5.appstream-qt libsForQt5.appstream-qt.passthru.tests
@ofborg build pantheon.appcenter gnome.gnome-software libsForQt5.discover

**Comment by bobby285271** [comment]
Is this package expect to work on darwin? With the introduction of `libxmlb`, I think this package will not evaluate on darwin anymore.

**Comment by jtojnar** [comment]
I do not see why libxmlb or this should not work on darwin, I just have not worked on the support since it is PITA.

**Comment by bobby285271** [comment]
I just ran a build for `libxmlb` with GitHub Actions (macos-latest), the build fails with:

```
ld: unknown option: --version-script
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

Full log: https://gist.github.com/bobby285271/233e2a9255ed6fea49d5b2b26e0f7ad1

Search result of `--version-script`: https://github.com/hughsie/libxmlb/blob/aa48a24e872dc47375952d7eb1dc6ff7430bc09d/src/meson.build#L41

@NixOS/darwin-maintainers Can someone offer a help to fix the build for `libxmlb` on darwin? I am sorry but I am really not sure how to deal with this. Thanks a lot!

**Comment by jtojnar** [comment]
That can be typically handled using

```meson
cc = meson.get_compiler('c')
vflag = cc.get_supported_link_arguments([vflag])
```

see e.g.:

https://github.com/GNOME/gcab/blob/14961b201e5daa34a250eddb06fe3fee011d6b20/libgcab/meson.build#L53

**Comment by jtojnar** [comment]
Maybe we have too old clang not supporting the C++14 attribute syntax?

**Comment by bobby285271** [comment]
With eye ball some more similar failure will happen e.g. https://github.com/ximion/appstream/blob/v0.15.2/qt/pool.h#L73

Maybe revert https://github.com/ximion/appstream/commit/41426d7bed38c93d146eacf4643c25c676675bc3 (and additionally patch qt/component.h) should work. Not tested.

---

It is midnight in UTC+8, going to sleep, will be back in 10 hours if my alarm clock works :zzz:

If you already find more failures for this package please leave a comment!

**Comment by bobby285271** [comment]
Looks like a simple revert won't work because https://github.com/ximion/appstream/commit/41426d7bed38c93d146eacf4643c25c676675bc3 is committed 7 minutes after https://github.com/ximion/appstream/commit/c14f306c9795d86881a92eded798b2396b2293f8 and I actually should look at the commit message :rofl: 

> The Qt version there is just too old and repeatedly causes issues -
> however, we can re-enable this once some way to deprecate enums that the
> old moc likes has been found.
> Or we can just wait a few months and test against the new LTS... (the
> cheaty way of doing things :-P)

I am sorry I know applying the patch conditionally is not good idea...

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/pull/161837/checks?check_run_id=5342175316

libsForQt5.appstream-qt seems to build on x86_64-darwin now.

---

https://github.com/NixOS/nixpkgs/pull/161837/checks?check_run_id=5342169568

What is this...?
> error: a 'x86_64-darwin' with features {} is required to build '/nix/store/krvyc5dva94ipkw60qjh87v7325cc1ni-fix-paths.patch.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test, recursive-nix}

**Comment by bobby285271** [comment]
@ofborg build libsForQt512.appstream-qt

**Comment by bobby285271** [comment]
@ofborg build tilix

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 161837` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>37 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnome.gnome-documents</li>
    <li>libsForQt512.bismuth</li>
    <li>libsForQt512.discover</li>
    <li>libsForQt512.kde-cli-tools</li>
    <li>libsForQt512.kdeplasma-addons</li>
    <li>libsForQt512.khotkeys</li>
    <li>libsForQt512.kinfocenter</li>
    <li>libsForQt512.kmenuedit</li>
    <li>libsForQt512.krohnkite</li>
    <li>libsForQt512.kwin-dynamic-workspaces</li>
    <li>libsForQt512.kwin-tiling</li>
    <li>libsForQt512.parachute</li>
    <li>libsForQt512.plasma-browser-integration</li>
    <li>libsForQt512.plasma-desktop</li>
    <li>libsForQt512.plasma-disks</li>
    <li>libsForQt512.plasma-phone-components</li>
    <li>libsForQt512.plasma-workspace</li>
    <li>libsForQt512.powerdevil</li>
    <li>libsForQt512.systemsettings</li>
    <li>libsForQt514.bismuth</li>
    <li>libsForQt514.discover</li>
    <li>libsForQt514.kde-cli-tools</li>
    <li>libsForQt514.kdeplasma-addons</li>
    <li>libsForQt514.khotkeys</li>
    <li>libsForQt514.kinfocenter</li>
    <li>libsForQt514.kmenuedit</li>
    <li>libsForQt514.krohnkite</li>
    <li>libsForQt514.kwin-dynamic-workspaces</li>
    <li>libsForQt514.kwin-tiling</li>
    <li>libsForQt514.parachute</li>
    <li>libsForQt514.plasma-browser-integration</li>
    <li>libsForQt514.plasma-desktop</li>
    <li>libsForQt514.plasma-disks</li>
    <li>libsForQt514.plasma-phone-components</li>
    <li>libsForQt514.plasma-workspace</li>
    <li>libsForQt514.powerdevil</li>
    <li>libsForQt514.systemsettings</li>
  </ul>
</details>
<details>
  <summary>65 packages built:</summary>
  <ul>
    <li>appstream</li>
    <li>bookworm</li>
    <li>bottles</li>
    <li>denemo</li>
    <li>evince (gnome.evince)</li>
    <li>fwupd</li>
    <li>gamemode</li>
    <li>giara</li>
    <li>glom</li>
    <li>gnome-feeds</li>
    <li>gnome-firmware-updater</li>
    <li>gnome.gnome-books</li>
    <li>gnome.gnome-software</li>
    <li>gnome.sushi</li>
    <li>gnonograms</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-mgba</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>libsForQt5.appstream-qt (libsForQt515.appstream-qt ,plasma5Packages.appstream-qt)</li>
    <li>libsForQt5.bismuth (libsForQt515.bismuth ,plasma5Packages.bismuth)</li>
    <li>libsForQt5.discover (libsForQt515.discover ,plasma5Packages.discover)</li>
    <li>libsForQt5.kde-cli-tools (libsForQt515.kde-cli-tools ,plasma5Packages.kde-cli-tools)</li>
    <li>libsForQt5.kdeplasma-addons (libsForQt515.kdeplasma-addons ,plasma5Packages.kdeplasma-addons)</li>
    <li>libsForQt5.khotkeys (libsForQt515.khotkeys ,plasma5Packages.khotkeys)</li>
    <li>libsForQt5.kinfocenter (libsForQt515.kinfocenter ,plasma5Packages.kinfocenter)</li>
    <li>libsForQt5.kmenuedit (libsForQt515.kmenuedit ,plasma5Packages.kmenuedit)</li>
    <li>libsForQt5.krohnkite (libsForQt515.krohnkite ,plasma5Packages.krohnkite)</li>
    <li>libsForQt5.kwin-dynamic-workspaces (libsForQt515.kwin-dynamic-workspaces ,plasma5Packages.kwin-dynamic-workspaces)</li>
    <li>libsForQt5.kwin-tiling (libsForQt515.kwin-tiling ,plasma5Packages.kwin-tiling)</li>
    <li>libsForQt5.parachute (libsForQt515.parachute ,plasma5Packages.parachute)</li>
    <li>libsForQt5.plasma-browser-integration (libsForQt515.plasma-browser-integration ,plasma5Packages.plasma-browser-integration)</li>
    <li>libsForQt5.plasma-desktop (libsForQt515.plasma-desktop ,plasma5Packages.plasma-desktop)</li>
    <li>libsForQt5.plasma-disks (libsForQt515.plasma-disks ,plasma5Packages.plasma-disks)</li>
    <li>libsForQt5.plasma-phone-components (libsForQt515.plasma-phone-components ,plasma5Packages.plasma-phone-components)</li>
    <li>libsForQt5.plasma-workspace (libsForQt515.plasma-workspace ,plasma5Packages.plasma-workspace)</li>
    <li>libsForQt5.powerdevil (libsForQt515.powerdevil ,plasma5Packages.powerdevil)</li>
    <li>libsForQt5.systemsettings (libsForQt515.systemsettings ,plasma5Packages.systemsettings)</li>
    <li>libsForQt512.appstream-qt</li>
    <li>libsForQt514.appstream-qt</li>
    <li>libxmlb</li>
    <li>lightly-qt</li>
    <li>metadata-cleaner</li>
    <li>meteo</li>
    <li>pantheon-tweaks</li>
    <li>pantheon.appcenter</li>
    <li>pantheon.elementary-calculator</li>
    <li>pantheon.elementary-camera</li>
    <li>pantheon.elementary-code</li>
    <li>pantheon.elementary-feedback</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-mail</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-photos</li>
    <li>pantheon.elementary-tasks</li>
    <li>pantheon.elementary-terminal</li>
    <li>pantheon.evince</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>pentobi</li>
    <li>setzer</li>
    <li>snippetpixie</li>
    <li>tilix</li>
    <li>wacomtablet</li>
  </ul>
</details>

**Review by jtojnar — APPROVED** [review]
Great job, LGTM.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 161837` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>appstream</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change looks good

Builds, works

Not fully tested

```
[nix-shell:~/.cache/nixpkgs-review/pr-161837-1]$ appstreamcli status
AppStream Status:
Version: 0.15.2

OS metadata sources:
 Software catalog data
 Group: os-catalog

 Data from locally installed software
 Group: local-metainfo

✘ No OS metadata found. This is unusual.
Other metadata sources:
 Group: flatpak-appcenter-x86_64
  /var/lib/flatpak/appstream/appcenter/x86_64/active
    • Collection XML:  2
  /var/lib/flatpak/appstream/appcenter/x86_64/active/icons
    • Iconsets:
        128x128
        64x64
        flatpak

Summary:
✔ We have information on 66 software components.
```

**Pull request merged**
