### PR TITLE
python3Packages.cramjam: 2.8.2 -> 2.8.3

### PR DESCRIPTION
**Pull request by RaghavSood**
## Description of changes

ZHF: https://github.com/NixOS/nixpkgs/issues/309482

https://github.com/milesgranger/cramjam/compare/v2.8.2...v2.8.3

cramjam 2.8.2 tests fail on aarch64-darwin

2.8.3 is a new upstream version, and seems to solve the failing tests too

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 311584` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages marked as broken and skipped:</summary>
  <ul>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>python311Packages.apache-beam</li>
    <li>python311Packages.apache-beam.dist</li>
    <li>python311Packages.bytewax</li>
    <li>python311Packages.bytewax.dist</li>
    <li>python311Packages.pins</li>
    <li>python311Packages.pins.dist</li>
    <li>python311Packages.streamz</li>
    <li>python311Packages.streamz.dist</li>
    <li>python312Packages.bytewax</li>
    <li>python312Packages.bytewax.dist</li>
    <li>python312Packages.pins</li>
    <li>python312Packages.pins.dist</li>
    <li>python312Packages.streamz</li>
    <li>python312Packages.streamz.dist</li>
  </ul>
</details>
<details>
  <summary>75 packages failed to build:</summary>
  <ul>
    <li>baserow</li>
    <li>baserow.dist</li>
    <li>paperless-ngx</li>
    <li>python312Packages.acquire</li>
    <li>python312Packages.acquire.dist</li>
    <li>python312Packages.celery</li>
    <li>python312Packages.celery-redbeat</li>
    <li>python312Packages.celery-redbeat.dist</li>
    <li>python312Packages.celery-singleton</li>
    <li>python312Packages.celery-singleton.dist</li>
    <li>python312Packages.celery.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.cohere</li>
    <li>python312Packages.cohere.dist</li>
    <li>python312Packages.confluent-kafka</li>
    <li>python312Packages.confluent-kafka.dist</li>
    <li>python312Packages.cramjam</li>
    <li>python312Packages.cramjam.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.dissect</li>
    <li>python312Packages.dissect-cobaltstrike</li>
    <li>python312Packages.dissect-cobaltstrike.dist</li>
    <li>python312Packages.dissect-target</li>
    <li>python312Packages.dissect-target.dist</li>
    <li>python312Packages.dissect.dist</li>
    <li>python312Packages.django-celery-beat</li>
    <li>python312Packages.django-celery-beat.dist</li>
    <li>python312Packages.django-celery-email</li>
    <li>python312Packages.django-celery-email.dist</li>
    <li>python312Packages.django-celery-results</li>
    <li>python312Packages.django-celery-results.dist</li>
    <li>python312Packages.django-google-analytics-app</li>
    <li>python312Packages.django-google-analytics-app.dist</li>
    <li>python312Packages.django-health-check</li>
    <li>python312Packages.django-health-check.dist</li>
    <li>python312Packages.django-raster</li>
    <li>python312Packages.django-raster.dist</li>
    <li>python312Packages.djmail</li>
    <li>python312Packages.djmail.dist</li>
    <li>python312Packages.dvc</li>
    <li>python312Packages.dvc-gdrive</li>
    <li>python312Packages.dvc-gdrive.dist</li>
    <li>python312Packages.dvc-hdfs</li>
    <li>python312Packages.dvc-hdfs.dist</li>
    <li>python312Packages.dvc-task</li>
    <li>python312Packages.dvc-task.dist</li>
    <li>python312Packages.dvc.dist</li>
    <li>python312Packages.dvclive</li>
    <li>python312Packages.dvclive.dist</li>
    <li>python312Packages.fastavro</li>
    <li>python312Packages.fastavro.dist</li>
    <li>python312Packages.fastparquet</li>
    <li>python312Packages.fastparquet.dist</li>
    <li>python312Packages.flow-record</li>
    <li>python312Packages.flow-record.dist</li>
    <li>python312Packages.flower</li>
    <li>python312Packages.flower.dist</li>
    <li>python312Packages.flowlogs-reader</li>
    <li>python312Packages.flowlogs-reader.dist</li>
    <li>python312Packages.intake-parquet</li>
    <li>python312Packages.intake-parquet.dist</li>
    <li>python312Packages.kombu</li>
    <li>python312Packages.kombu.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.nameko</li>
    <li>python312Packages.nameko.dist</li>
    <li>python312Packages.parquet</li>
    <li>python312Packages.parquet.dist</li>
    <li>python312Packages.python-snappy</li>
    <li>python312Packages.python-snappy.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
  </ul>
</details>
<details>
  <summary>100 packages built:</summary>
  <ul>
    <li>acquire (python311Packages.acquire)</li>
    <li>acquire.dist (python311Packages.acquire.dist)</li>
    <li>barman</li>
    <li>barman.dist</li>
    <li>dvc (python311Packages.dvc)</li>
    <li>dvc.dist (python311Packages.dvc.dist)</li>
    <li>python311Packages.celery</li>
    <li>python311Packages.celery-redbeat</li>
    <li>python311Packages.celery-redbeat.dist</li>
    <li>python311Packages.celery-singleton</li>
    <li>python311Packages.celery-singleton.dist</li>
    <li>python311Packages.celery.dist</li>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.cohere</li>
    <li>python311Packages.cohere.dist</li>
    <li>python311Packages.confluent-kafka</li>
    <li>python311Packages.confluent-kafka.dist</li>
    <li>python311Packages.cramjam</li>
    <li>python311Packages.cramjam.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.datashader</li>
    <li>python311Packages.datashader.dist</li>
    <li>python311Packages.dissect</li>
    <li>python311Packages.dissect-cobaltstrike</li>
    <li>python311Packages.dissect-cobaltstrike.dist</li>
    <li>python311Packages.dissect-target</li>
    <li>python311Packages.dissect-target.dist</li>
    <li>python311Packages.dissect.dist</li>
    <li>python311Packages.django-celery-beat</li>
    <li>python311Packages.django-celery-beat.dist</li>
    <li>python311Packages.django-celery-email</li>
    <li>python311Packages.django-celery-email.dist</li>
    <li>python311Packages.django-celery-results</li>
    <li>python311Packages.django-celery-results.dist</li>
    <li>python311Packages.django-google-analytics-app</li>
    <li>python311Packages.django-google-analytics-app.dist</li>
    <li>python311Packages.django-health-check</li>
    <li>python311Packages.django-health-check.dist</li>
    <li>python311Packages.django-raster</li>
    <li>python311Packages.django-raster.dist</li>
    <li>python311Packages.djmail</li>
    <li>python311Packages.djmail.dist</li>
    <li>python311Packages.dvc-gdrive</li>
    <li>python311Packages.dvc-gdrive.dist</li>
    <li>python311Packages.dvc-hdfs</li>
    <li>python311Packages.dvc-hdfs.dist</li>
    <li>python311Packages.dvc-task</li>
    <li>python311Packages.dvc-task.dist</li>
    <li>python311Packages.dvclive</li>
    <li>python311Packages.dvclive.dist</li>
    <li>python311Packages.fastavro</li>
    <li>python311Packages.fastavro.dist</li>
    <li>python311Packages.fastparquet</li>
    <li>python311Packages.fastparquet.dist</li>
    <li>python311Packages.flow-record</li>
    <li>python311Packages.flow-record.dist</li>
    <li>python311Packages.flower</li>
    <li>python311Packages.flower.dist</li>
    <li>python311Packages.flowlogs-reader</li>
    <li>python311Packages.flowlogs-reader.dist</li>
    <li>python311Packages.hdfs</li>
    <li>python311Packages.hdfs.dist</li>
    <li>python311Packages.intake</li>
    <li>python311Packages.intake-parquet</li>
    <li>python311Packages.intake-parquet.dist</li>
    <li>python311Packages.intake.dist</li>
    <li>python311Packages.kombu</li>
    <li>python311Packages.kombu.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.nameko</li>
    <li>python311Packages.nameko.dist</li>
    <li>python311Packages.parquet</li>
    <li>python311Packages.parquet.dist</li>
    <li>python311Packages.python-snappy</li>
    <li>python311Packages.python-snappy.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.buildsrht.dist</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.coresrht.dist</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.gitsrht.dist</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hgsrht.dist</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.hubsrht.dist</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.listssrht.dist</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.mansrht.dist</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.metasrht.dist</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.pastesrht.dist</li>
    <li>sourcehut.todosrht</li>
    <li>sourcehut.todosrht.dist</li>
  </ul>
</details>

**Comment by RaghavSood** [comment]
2.8.2 fails on python311 [hydra](https://hydra.nixos.org/build/258888472), but 2.8.3 breaks python312 instead - will check if it's possible to get both green

**Comment by RaghavSood** [comment]
Oddly enough, it does build python312Packages.cramjam when build standalone, but not when run through nixpkgs-review

```
raghavsood@r-mbp-a15> git checkout master                                                                                                                                                                                      ~/r/local/dev/github.com/RaghavSood/nixpkgs
Already on 'master'
Your branch is ahead of 'origin/master' by 586 commits.
  (use "git push" to publish your local commits)
raghavsood@r-mbp-a15> git switch cramjam/2.8.3                                                                                                                                                                                 ~/r/local/dev/github.com/RaghavSood/nixpkgs
Switched to branch 'cramjam/2.8.3'
Your branch is up to date with 'origin/cramjam/2.8.3'.
raghavsood@r-mbp-a15> nix-build -A python312Packages.cramjam                                                                                                                                                                   ~/r/local/dev/github.com/RaghavSood/nixpkgs
this derivation will be built:
  /nix/store/s2y9hl5bk5kfc715818342b3faqb8wxh-python3.12-cramjam-2.8.3.drv
building '/nix/store/s2y9hl5bk5kfc715818342b3faqb8wxh-python3.12-cramjam-2.8.3.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-build-hook
Using pypaBuildPhase
Sourcing python-runtime-deps-check-hook
Using pythonRuntimeDepsCheckHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing pytest-check-hook
Using pytestCheckPhase
Running phase: unpackPhase
unpacking source archive /nix/store/yzq95b87wq7rk22x2ipdsffcq3ypgrjw-source
source root is source
Executing cargoSetupPostUnpackHook
unpacking source archive /nix/store/8pn5wxv43ab00bqgn14sq9sj7drd6yzb-cargo-deps-vendor.tar.gz
Finished cargoSetupPostUnpackHook
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/rustfmt.toml
Running phase: patchPhase
Executing cargoSetupPostPatchHook
Validating consistency between /private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/source/Cargo.lock and /private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/cargo-deps-vendor.tar.gz/Cargo.lock
Finished cargoSetupPostPatchHook
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
no configure script, doing nothing
Running phase: buildPhase
Executing maturinBuildHook
/private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/source/cramjam-python /private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/source
++ env CC_AARCH64_APPLE_DARWIN=/nix/store/xzhppl1kydagd12hpymdr077in85015c-clang-wrapper-16.0.6/bin/cc CXX_AARCH64_APPLE_DARWIN=/nix/store/xzhppl1kydagd12hpymdr077in85015c-clang-wrapper-16.0.6/bin/c++ CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=/nix/store/xzhppl1kydagd12hpymdr077in85015c-clang-wrapper-16.0.6/bin/cc CC_AARCH64_APPLE_DARWIN=/nix/store/xzhppl1kydagd12hpymdr077in85015c-clang-wrapper-16.0.6/bin/cc CXX_AARCH64_APPLE_DARWIN=/nix/store/xzhppl1kydagd12hpymdr077in85015c-clang-wrapper-16.0.6/bin/c++ CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=/nix/store/xzhppl1kydagd12hpymdr077in85015c-clang-wrapper-16.0.6/bin/cc CARGO_BUILD_TARGET=aarch64-apple-darwin HOST_CC=/nix/store/xzhppl1kydagd12hpymdr077in85015c-clang-wrapper-16.0.6/bin/cc HOST_CXX=/nix/store/xzhppl1kydagd12hpymdr077in85015c-clang-wrapper-16.0.6/bin/c++ maturin build --jobs=8 --frozen --target aarch64-apple-darwin --manylinux off --strip --release
🔗 Found pyo3 bindings
🐍 Found CPython 3.12 at /nix/store/2r8fbgpabanb42zbdm4lngayc35wby8i-python3-3.12.3/bin/python3
   Compiling libc v0.2.153
   Compiling target-lexicon v0.12.14
   Compiling pkg-config v0.3.30
   Compiling once_cell v1.19.0
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.78
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   Compiling zstd-safe v7.0.0
   Compiling alloc-no-stdlib v2.0.4
   Compiling lock_api v0.4.11
   Compiling parking_lot_core v0.9.9
   Compiling crc32fast v1.4.0
   Compiling alloc-stdlib v0.2.2
   Compiling memoffset v0.9.0
   Compiling smallvec v1.13.1
   Compiling adler v1.0.2
   Compiling heck v0.4.1
   Compiling portable-atomic v1.6.0
   Compiling quote v1.0.35
   Compiling snap v1.1.1
   Compiling scopeguard v1.2.0
   Compiling syn v2.0.52
   Compiling miniz_oxide v0.7.2
   Compiling brotli-decompressor v2.5.1
   Compiling pyo3-build-config v0.20.3
   Compiling flate2 v1.0.28
   Compiling jobserver v0.1.28
   Compiling cc v1.0.90
   Compiling brotli v3.4.0
   Compiling parking_lot v0.12.1
   Compiling unindent v0.2.3
   Compiling indoc v2.0.4
   Compiling zstd-sys v2.0.9+zstd.1.5.5
   Compiling lz4-sys v1.9.4
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling libdeflate-sys v1.19.3
   Compiling lzma-sys v0.1.20
   Compiling pyo3-ffi v0.20.3
   Compiling pyo3 v0.20.3
   Compiling pyo3-macros-backend v0.20.3
   Compiling cramjam-python v2.8.3 (/private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/source/cramjam-python)
   Compiling pyo3-macros v0.20.3
   Compiling bzip2 v0.4.4
   Compiling libdeflater v1.19.3
   Compiling lz4 v1.24.0
   Compiling zstd v0.13.0
   Compiling xz2 v0.1.7
   Compiling libcramjam v0.3.0
    Finished release [optimized] target(s) in 43.37s
📦 Built wheel for CPython 3.12 to /private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/source/target/wheels/cramjam-2.8.3-cp312-cp312-macosx_11_0_arm64.whl
/private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/source
Finished maturinBuildHook
buildPhase completed in 44 seconds
Running phase: pythonRuntimeDepsCheckHook
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for cramjam-2.8.3-cp312-cp312-macosx_11_0_arm64.whl
Finished executing pythonRuntimeDepsCheck
Running phase: installPhase
Executing pypaInstallPhase
Successfully installed cramjam-2.8.3-cp312-cp312-macosx_11_0_arm64.whl
Finished executing pypaInstallPhase
Running phase: pythonOutputDistPhase
Executing pythonOutputDistPhase
Finished executing pythonOutputDistPhase
Running phase: fixupPhase
checking for references to /private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/ in /nix/store/6c93yimc1qpvnlpzqhbias4grd1fx0a9-python3.12-cramjam-2.8.3...
patching script interpreter paths in /nix/store/6c93yimc1qpvnlpzqhbias4grd1fx0a9-python3.12-cramjam-2.8.3
stripping (with command strip and flags -S) in  /nix/store/6c93yimc1qpvnlpzqhbias4grd1fx0a9-python3.12-cramjam-2.8.3/lib
checking for references to /private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/ in /nix/store/r4zbcdvkszd6lf8ylh8bskddib7wbcv2-python3.12-cramjam-2.8.3-dist...
patching script interpreter paths in /nix/store/r4zbcdvkszd6lf8ylh8bskddib7wbcv2-python3.12-cramjam-2.8.3-dist
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
Running phase: installCheckPhase
no Makefile or custom installCheckPhase, doing nothing
Running phase: pythonCatchConflictsPhase
Running phase: pythonRemoveBinBytecodePhase
Running phase: pythonImportsCheckPhase
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: cramjam
Running phase: pytestXdistHook
Running phase: pytestCheckPhase
Executing pytestCheckPhase
============================= test session starts ==============================
platform darwin -- Python 3.12.3, pytest-8.1.1, pluggy-1.4.0
rootdir: /private/tmp/nix-build-python3.12-cramjam-2.8.3.drv-0/source/cramjam-python
configfile: pyproject.toml
plugins: hypothesis-6.100.1, xdist-3.5.0
8 workers [645 items]  m
........................................................................ [ 11%]
........................................................................ [ 22%]
......................................................................... [ 33%]
........................................................................ [ 44%]
........................................................................ [ 55%]
........................................................................ [ 67%]
........................................................................ [ 78%]
........................................................................ [ 89%]
....................................................................     [100%]
============================= 645 passed in 8.34s ==============================
Finished executing pytestCheckPhase
Running phase: pytestcachePhase
Running phase: pytestRemoveBytecodePhase
/nix/store/6c93yimc1qpvnlpzqhbias4grd1fx0a9-python3.12-cramjam-2.8.3
```

**Comment by veprbl** [comment]
@GrahamcOfBorg build python311Packages.cramjam python312Packages.cramjam

**Comment by RaghavSood** [comment]
Well, I guess it's a local nixpkgs-review issue then

**Comment by mjm** [comment]
This is broken on Hydra for x86_64, and it fails to build on my builder (though not on my laptop for some reason).

**Comment by RaghavSood** [comment]
Yes, this appears to be flaky - it 311 and 312 fail intermittently, though not always at the same time.

**Comment by RaghavSood** [comment]
It appears to be failing intermittently across multiple architectures with the attached log.

It's always test_variants.py - I can't reproduce it even with the seeds in the logs, but I can get it to arbitrarily fail on my machine at times.

It's the same build failure I was seeing on 2.8.2 before I bumped it, but I mistakenly believed the bump was sufficient since it built locally and during the PR flow, and in a couple of subsequent hydra evaluations.

I'll remove the test for the moment until we know why it's flaky.
[Uploading cramjam_hydra.log…]()

**Comment by RaghavSood** [comment]
Disabled in #312445

**Pull request merged**
