### PR TITLE
nodejs_23: 23.1.0 -> 23.2.0

### PR DESCRIPTION
**Pull request by aduh95**
https://github.com/nodejs/node/releases/tag/v23.2.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Ma27 — CHANGES_REQUESTED** [review]
There's at least one obsolete patch:

```
nodejs> applying patch /nix/store/6dzrdls3was8cz3a5fk6qiyv0w5zzgr5-dcbc5fbe65b068a90c3d0970155d3a68774caa38.patch?full_index=1
nodejs> patching file lib/dgram.js
nodejs> patching file src/udp_wrap.cc
nodejs> patching file test/common/udp.js
nodejs> patching file test/parallel/test-child-process-dgram-reuseport.js
nodejs> Reversed (or previously applied) patch detected!  Assume -R? [n] 
nodejs> Apply anyway? [n] 
nodejs> Skipping patch.
nodejs> 1 out of 1 hunk ignored -- saving rejects to file test/parallel/test-child-process-dgram-reuseport.js.rej
nodejs> patching file test/parallel/test-cluster-dgram-reuseport.js
nodejs> Reversed (or previously applied) patch detected!  Assume -R? [n] 
nodejs> Apply anyway? [n] 
nodejs> Skipping patch.
nodejs> 1 out of 1 hunk ignored -- saving rejects to file test/parallel/test-cluster-dgram-reuseport.js.rej
nodejs> patching file test/parallel/test-dgram-reuseport.js
nodejs> Reversed (or previously applied) patch detected!  Assume -R? [n] 
nodejs> Apply anyway? [n] 
nodejs> Skipping patch.
nodejs> 1 out of 1 hunk ignored -- saving rejects to file test/parallel/test-dgram-reuseport.js.rej
```

**Comment by aduh95** [comment]
It's getting harder and harder to maintain Node.js with https://github.com/NixOS/nixpkgs/pull/344438 not landing

**Comment by Ma27** [comment]
> It's getting harder and harder to maintain Node.js with #344438 not landing

Merged. Change looked reasonable.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Merged.
Please note that the nodejs_23 on staging will require a fixup (i.e. the revert removed you added here) when master gets merged into staging (happens every few hours via some automation).

Would you mind filing a PR to resolve this as well?
Feel free to cc me to merge.

**Comment by aduh95** [comment]
> Please note that the nodejs_23 on staging will require a fixup (i.e. the revert removed you added here) when master gets merged into staging (happens every few hours via some automation).

There's going to be a git conflict to resolve, which IIUC will result in the bot giving up the merge and instead post a comment in `#105153`. I don't think I can do the git conflict resolution in a PR, can I?

**Comment by Ma27** [comment]
OK interesting I would've expected git to get done with that. Anyways, going to resolve now.

**Comment by Ma27** [comment]
Done: 85228bf93ed88b0e72add43285f7d0f8cdafb959
Nothing tbd from you here.

**Pull request merged**
