### PR TITLE
php: 7.2.22 -> 7.2.23, 7.3.9 -> 7.3.10

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
Changelog: https://www.php.net/ChangeLog-7.php#7.3.10
Changelog: https://www.php.net/ChangeLog-7.php#7.2.23

So far I've only made sure the hashes works, but I will build all the things on a more powerful system and check boxes below accordingly.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Ma27** [comment]
Diff seems fine, currently running `nix-review` locally.

**Comment by Ma27** [comment]
Btw nix-review runs into a timeout due to libcouchbase. This appears to be an issue with openssl 1.1.1, I'll check if upstream has some patches for this :)

**Comment by Izorkin** [comment]
On my home server php 7.2.23 (with libressl) is working fine.

**Comment by Ma27** [comment]
Yeah, the problem isn't related to php, but to libcouchbase (which is used by phpPackages.couchbase). I'd try to fix the libcouchbase issue tomorrow, but it's perfectly fine if someone merges this before :)

**Comment by Ma27** [comment]
Libcouchbase is fixed in #70455. I'll rerun nix-review with my patch, but I don't expect any further issues :)

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Thanks! Backported as 63b18e757620223b4f9ac1cd2f65fb9709d2aa2a, 6ae771e8d5319f45401e3afba90b5eafc2c48635.

**Comment by etu** [comment]
@Ma27 Thanks yourself for looking into libcouchbase :)

**Pull request merged**
