### PR TITLE
Mailman updates

### PR DESCRIPTION
**Pull request by alyssais**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
@OfBorg eval

**Comment by kirillrdy** [comment]
@alyssais should we add `nixosTests.mailman` to `passthru.tests` so that ofborg runs those automatically during reviews ?

**Comment by alyssais** [comment]
Good idea. https://github.com/NixOS/nixpkgs/pull/282040

**Review by kirillrdy — APPROVED** [review]

**Comment by kirillrdy** [comment]
Hmm I thought build passed before

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 281823` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>mailman</li>
    <li>mailman-hyperkitty</li>
    <li>mailman-hyperkitty.dist</li>
    <li>mailman-web</li>
    <li>mailman-web.dist</li>
    <li>mailman.dist</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
sorry posted x86 results by mistake 

Result of `nixpkgs-review pr 281823` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>mailman-web</li>
    <li>mailman-web.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>mailman</li>
    <li>mailman-hyperkitty</li>
    <li>mailman-hyperkitty.dist</li>
    <li>mailman.dist</li>
  </ul>
</details>

**Comment by alyssais** [comment]
mailman-web builds for me on aarch64-linux

**Comment by kirillrdy** [comment]
@alyssais its ok on my system `nix-build -A python3Packages.mocket --check --argstr system aarch64-linux` fails on master, probably because of binfmt, and log is very different to error on ofborg

whats strange is that now `nixosTests.mailman` fails on x86_64-linux :shrug:  ( builds locally for me )

**Comment by alyssais** [comment]
It's build on x86_64-linux on OfBorg now.  I think the dependencies are just flaky.

**Pull request merged**
