### PR TITLE
zen: init at 1.0.1-a.19, zen-specific: init at 1.0.1-a.19, maintainers: add kmdtaufik

### PR DESCRIPTION
**Pull request by kmdtaufik**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kmdtaufik** [comment]
@IogaMaster Can you review this code ? It's my first time contributing.

**Comment by getchoo** [comment]
From a quick look this seems good! However, it is a duplicate of https://github.com/NixOS/nixpkgs/pull/347222, where we're building the browser from source instead of using upstream's binaries

Also: welcome to Nixpkgs :)

**Comment by kmdtaufik** [comment]
> From a quick look this seems good! However, it is a duplicate of #347222, where we're building the browser from source instead of using upstream's binaries
> 
> Also: welcome to Nixpkgs :)

I don't have enough resources to build it from source, and it gives quite a lot errors. :cry:

**Review by Titaniumtown — CHANGES_REQUESTED** [review]
I don't think this binary approach should be taken over the build-from-source approach of #347222

**Comment by getchoo** [comment]
> I don't have enough resources to build it from source

Once it's merged, you won't need to as binaries will be built and cached by Hydra

I'd recommend continuing to use this in the meantime, but I'm not sure it's a good fit here with that PR nearing completion

**Comment by youwen5** [comment]
The other PR is done and just needs to be merged so Hydra can begin caching binaries. It also supports `aarch64-linux` which Zen does not provide binaries for.

**Comment by kmdtaufik** [comment]
> The other PR is done and just needs to be merged so Hydra can begin caching binaries. It also supports `aarch64-linux` which Zen does not provide binaries for.

It would be better to have it built from source, but while I was searching I couldn't find any PR for zen, so I built this and put it on PR :)

**Comment by getchoo** [comment]
> Off-topic : why is ofborg checking it for Darwin

It will always try to run for x86_64-linux, aarch64-linux, x86_64-darwin, and aarch64-darwin

**Review by IogaMaster — APPROVED** [review]
LGTM!

Welcome to nixpkgs and thanks for contributing! :smile:

**Comment by youwen5** [comment]
Thanks for the contribution, but I don't see any reason to merge this PR first when #347222 has been ready and is preferred (in nixpkgs). This PR would be better as a standalone zen-bin flake or something for people who want official upstream binaries.

**Comment by kmdtaufik** [comment]
> Thanks for the contribution, but I don't see any reason to merge this PR first when #347222 has been ready and is preferred (in nixpkgs). This PR would be better as a standalone zen-bin flake or something for people who want official upstream binaries. It would also be more useful to other people who want to run Zen now without building it from source due to resource constraints.

I'll change it to zen-bin and change the description next time. That way it'll be easier for the user.

**Comment by getchoo** [comment]
#347222 has been merged. You can check when it will land in your branch [here](https://nixpk.gs/pr-tracker.html?pr=347222)

Thanks again for contributing!

**Pull request closed without merging**
