### PR TITLE
gitea: 1.13.5 -> 1.13.6 + reformatting

### PR DESCRIPTION
**Pull request by schmittlauch**
###### Motivation for this change

- minor version bump incl. security fixes, see https://github.com/go-gitea/gitea/releases/tag/v1.13.6
- re-formatted derivation with `nixpkgs-fmt` for a consistent style

needs a backport to stable

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by schmittlauch** [comment]
The corresponding NixOS test is still building locally, but might take a while due to the need for building the whole kernel + C++ infra from scratch /0\

**Comment by schmittlauch** [comment]
forgot to mention: I ran `nixpkgs-fmt` on this, causing a lot of reformats. But as this is the defacto standard-formatter AFAIK, this needed to be done anyways at some point

**Comment by schmittlauch** [comment]
Huh, any idea why nixpkgs-review didn't give me these suggestions?

**Comment by Ma27** [comment]
@GrahamcOfBorg test gitea

> thus switch to the more compact fetchFromGithub helper

This doesn't seem to contain e.g. `node_modules`. Have you checked whether the UI is working fine with this change? (The test doesn't cover that IIRC).

> But as this is the defacto standard-formatter AFAIK, this needed to be done anyways at some point

However it's not mentioned anywhere in the contribution guidelines since we don't have a common coding standard.

I'm generally not a big fan of auto-formatters anymore since those make reviewing diffs (and also `git blame`) less useful IMHO. So if we change that, I'd prefer to have this in its own commit, then it's also immediately clear that you didn't have to touch e.g. the build script here and that it's only a purely cosmetic change :)

**Comment by Ma27** [comment]
> Huh, any idea why nixpkgs-review didn't give me these suggestions?

Those are part of https://github.com/jtojnar/nixpkgs-hammering IIRC.

**Comment by schmittlauch** [comment]
> > thus switch to the more compact fetchFromGithub helper
> 
> This doesn't seem to contain e.g. `node_modules`. Have you checked whether the UI is working fine with this change? (The test doesn't cover that IIRC).

Oh yeah, now that you mention it I remember such a thing.
No, I haven't checked that. I'm currently deploying my PR to my gitea instance, so let's wait and see.

Regarding nixpkgs-fmt it is up to you whether I split that into a separate commit or completely leave it out. But after done once, it might help keeping the diffs easier to review – until the next formatter comes up ;)

**Comment by schmittlauch** [comment]
Welp, @Ma27 was correct, just taking the repo breaks the webUI. Someone :tm: should probably add that as a test case.

Changed back to fetchurl-ing the release archive and added a comment for clarification.

**Comment by schmittlauch** [comment]
:heavy_check_mark: successfully deployed this to https://git.orlives.de/ *with* a working webUI this time

**Comment by schmittlauch** [comment]
side question: Why is `nixosTests` passed as a function argument? It is never (explicitly) used anywhere.

**Comment by rmcgibbo** [comment]
> Huh, any idea why nixpkgs-review didn't give me these suggestions?

The "suggestions" are part of my fork (running in the bot). They come from nixpkgs-hammering.

**Comment by Ma27** [comment]
> side question: Why is nixosTests passed as a function argument? It is never (explicitly) used anywhere.

You usually do `passthru.tests = { inherit (nixosTests) gitea; };` or sth. similar to associate a package with a VM test. This is helpful for e.g. ofborg or r-ryantm (IIRC) to also run the VM tests.

Not sure though why this isn't used here atm. Feel free to add this and check it with `nix-build -A gitea.tests`.

**Comment by SuperSandro2000** [comment]
> Huh, any idea why nixpkgs-review didn't give me these suggestions?

Because it is https://github.com/jtojnar/nixpkgs-hammering.

**Comment by Ma27** [comment]
Ported to stable as 528264e0c34c435f6b44e43b404e60d990cadb39, d00458c986b6834e09090e13c3c3a0ab356a5904.

**Pull request merged**
