### PR TITLE
rm .github/workflows/pending-*

### PR DESCRIPTION
**Pull request by veprbl**
These actions mess with CI status for no obvious reason. They make it
harder to tell a real eval failure from a pending build. The ofborg
builder for darwin is not working currently, so this marks many PRs
with a failed state.

cc @zowoq

### CODE REVIEW

**Comment by worldofpeace** [comment]
this is the actual issue here https://github.com/NixOS/nixpkgs/pull/96707

**Comment by zowoq** [comment]
> These actions mess with CI status for no obvious reason.

They are needed for the editorconfig check.

> They make it harder to tell a real eval failure from a pending build.

Will be fixed by https://github.com/NixOS/ofborg/pull/527.

> The ofborg builder for darwin is not working currently, so this marks many PRs with a failed state.

No it does not.

**Comment by veprbl** [comment]
> They are needed for the editorconfig check.

I would suggest removing it too. It affects a tiny fraction of pull requests, I would not be surprised if there is only a single digit number of people who actually consume this check. It makes no sense to me to keep it in the UI.

**Comment by zowoq** [comment]
>  It affects a tiny fraction of pull requests, I would not be surprised if there is only a single digit number of people who actually consume this check.

https://github.com/NixOS/nixpkgs/actions?query=workflow%3A%22Checking+EditorConfig%22+is%3Afailure

**Comment by zowoq** [comment]
Regardless of editorconfig we'll need the pending job if we want to work on https://github.com/NixOS/nixpkgs/issues/99722.

**Comment by veprbl** [comment]
@zowoq What are you trying to say? If I'm not mistaken, following your link I see that the check has some spurious fails for unrelated PR's.

**Comment by zowoq** [comment]
They aren't spurious.

**Comment by veprbl** [comment]
> They aren't spurious.

My bad. I see now.

**Comment by veprbl** [comment]
> > The ofborg builder for darwin is not working currently, so this marks many PRs with a failed state.
> 
> No it does not.

Here it happens on my PR: #100121
Here the status was not cleared for no reason (at the moment, the PR is not finished): #98634

**Comment by zowoq** [comment]
> > > The ofborg builder for darwin is not working currently, so this marks many PRs with a failed state.
> > 
> > 
> > No it does not.
> 
> Here it happens on my PR: #100121

It isn't related to darwin. `GrahamcOfBorg` was called manually before eval finished which caused a conflict between the completed jobs, I've seen this in a couple of PRs and I haven't bothered doing anything about because it won't be an issue once https://github.com/NixOS/ofborg/pull/527 and https://github.com/NixOS/nixpkgs/pull/96707 are merged.

> Here the status was not cleared for no reason (at the moment, the PR is not finished): #98634

Not sure exactly what happened with this one (being closed/reopened without pushing changes may have caused it go glitch) but it wouldn't have happened if we had https://github.com/NixOS/ofborg/pull/527 and https://github.com/NixOS/nixpkgs/pull/96707.

**Comment by gebner** [comment]
> > They are needed for the editorconfig check.
> 
> I would suggest removing it too. It affects a tiny fraction of pull requests, I would not be surprised if there is only a single digit number of people who actually consume this check. It makes no sense to me to keep it in the UI.

The editorconfig check is important.  Before it we had lots of trailing spaces.  And if you had an editorconfig-aware editor, then it would automatically strip them.  I've made several PRs with unrelated (accidental) whitespace changes in `all-packages.nix` for this reason.

Maybe the editorconfig check should be a different actions workflow though.

**Comment by FRidh** [comment]
Maybe the editorconfig check should first be announced on the mailing list (along with other CI plans), and at the least documented what is expected here from contributors. I'm pretty sure this has been said several times.

**Comment by doronbehar** [comment]
Speaking of EditorConfig, I'd like to suggest that it'll be more strict, also regarding spaces vs tabs ([example](https://github.com/NixOS/nixpkgs/pull/98093#discussion_r504656603)). Also :+1: on whoever that decided it should notify users when this check fails.

**Comment by SuperSandro2000** [comment]
CLosing this based on the discussions.

**Comment by zowoq** [comment]
Apologies, seems I forgot about this PR.
____
> Maybe the editorconfig check should first be announced on the mailing list ... I'm pretty sure this has been said several times.

Thought I'd already commented on this in another PR but if I did I can't find it.

As this is the fourth attempt at this check I was waiting until we didn't need the weird workarounds.
___
> I'd like to suggest that it'll be more strict, also regarding spaces vs tabs

Disallowing tabs was done in https://github.com/NixOS/nixpkgs/pull/101530. Indentation size is more disruptive, I'm still looking at ways to enable it.

> Also 👍 on whoever that decided it should notify users when this check fails.

Github, currently we aren't able to configure notifications. (IIRC users can disable them globally in their profile?)

**Pull request closed without merging**
