### PR TITLE
Move to explicit gtk2 and gtk3 choice

### PR DESCRIPTION
**Pull request by aske**
###### Motivation for this change

GTK3 is the recommended version of GTK library right now and GTK2 is in maintenance-mode. Usually an alias points to the latest version of a package, though there are some notable exceptions in the tree, such as GTK, Python and several others. This proposal is in the spirit of current work of moving to Python 3 by default (#18185).
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This is work in progress; many packages are still in the need of change. It would be good to have some feedback on whether we want this before moving further, also any help with fixing all references is much appreciated.

### CODE REVIEW

**Comment by FRidh** [comment]
Great, we should definitely do this. I do suggest that instead of changing each occurrence of `gtk` in the expression to `gtk2`,  that you use a let expression, `let gtk = gtk2`. But that's just my style preference.

**Comment by abbradar** [comment]
Several packages which I remember have both GTK2 and GTK3 support, that we can move to the new default:

* Firefox
* nvidia-x11

**Comment by vcunat** [comment]
**Firefox**: I'm not certain it's ready to be defaulted to GTK3. [There are dozens of open bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=627699) that "block" this upstream; it doesn't seem to be considered high-priority. I must say I have used it with GTK3 for months during the past year and I don't remember any serious problems, but the experience felt slightly worse.

IMHO these renamings aren't an important step, as the 2/3 choice should be explicit anyway. Switching the individual packages is what we should do, **if** there's a consensus that we should generally prefer gtk3 over gtk2 (which I assume).

**Comment by abbradar** [comment]
BTW @aske and I had an idea that maybe we want to remove `gtk` alias at all, like we have with Qt.

@vcunat It would be nice to have some list of packages supporting both GTKs that we should check. I can enlist DeaDBeeF but it's already GTK3 by default. Don't remember any others...

Also we indeed shouldn't switch Firefox if it's still immature -- thanks for the remark.

**Comment by vcunat** [comment]
Yes, better remove it than redirect, but those are just nitpicks. New code should reference `gtk3` in any case (or `gtk2` if really superior).

**Comment by vcunat** [comment]
**Xfce**: the latest stable doesn't support gtk3, at least most of it doesn't. The next major release, 4.14, is expected to add that as the main change, but there's no telling when the release might happen.

**Comment by aske** [comment]
Yeah, I've decided to remove aliases and move to explicit versioning; will rename PR and edit description to reflect it now.

Updated with explicitly specified uses of `gtk{2,3}`, `pygobject{2,3}`, `gtk-sharp-{2_0,3_0}`, `gtkmm{2,3}`, `gtkspell{2,3}`, `gnome{2,3}`, `libcanberra_gtk{2,3}` packages and removed top-level `gtk-sharp`, `gnome`, `gtk`, `gtkmm`, `libcanberra` which defaulted to gtk2-stuff.

It would be great to have the initial patch cherry-picked as soon as possible to prevent fast decay. I've also tried to keep as much hashes as possible. 

There are a number of packages which either do something strange (like using `libcanberra_gtk2` with `gtk3`, using both gtk versions at the same time, etc) or may (or, well, may not) benefit from moving to `gtk3`; those packages require a second look as I've chosen the most conservative option when there was a choice.

Here's a list (feel free to fill in checkboxes if you make changes): 

[ ] `gegl`
[ ] `gksu`
[ ] `gvfs`
[ ] `geary`
[ ] `pomodoro`
[ ] `kazam`
[ ] `keybinder`
[ ] `libgksu`
[ ] `libreoffice`
[ ] `nvidia-x11`
[ ] smth in `top-level/lua-packages.nix`
[ ] `lxappearance`
[ ] `mkcast`
[ ] `mysql-workbench`
[ ] `oneteam`
[ ] `planetaryannihilation`
[ ] `scilab`
[ ] `slurm`
[ ] `spice-gtk`
[ ] `tango-icon-theme`
[ ] `vivaldi`
[ ] `workrave`
[ ] `atom/env.nix`
[ ] `celestia`
[ ] `chromedriver`
[ ] `bluez5`
[ ] `java/classpath.nix`
[ ] `python-notify` (?)
[ ] `desmume`
[ ] `dia`
[ ] `pango` from haskell
[ ] `factor-lang`
[ ] `firefox-bin`
[ ] `gnome-shell`
[ ] `guake`
[ ] `guileGnome` in toplevel
[ ] `MonoAddins`
[ ] `node-webkit`
[ ] `tangogps`
[ ] `terminator`
[ ] `thrust`
[ ] `thunderbird-bin`
[ ] `totem`
[ ] `wicd`
[ ] `wine`

**Comment by abbradar** [comment]
We need to mark in changelog that `gnome` is not available now, I think.

**Comment by aske** [comment]
`gtkmathview` seems to be broken too. cc @roconnor

**Comment by aske** [comment]
After last changes `nox-review` says it's ok to go. :)

**Comment by abbradar** [comment]
I've cherry-picked your build fixes to master as they are unrelated to this PR.

Let's not keep this patch for long then -- I'm going to merge it in several days if there are no objections against it. tl;dr: the patch removes `gtk`, `gnome` and several other aliases and sets their versions explicitly for all packages (that's a lot of renaming, that's why we want it sooner), as we have for Qt. It doesn't try build more packages with GTK+3 yet. cc @edolstra

**Comment by aske** [comment]
Resolved new conflicts and checked `nox-review`; everything works now.

**Comment by vcunat** [comment]
OK from me for the tl;dr.

**Comment by abbradar** [comment]
@aske, would you please create a separate issue about moving to GTK3 by default and move your packages list there? Thanks!

**Comment by abbradar** [comment]
Apparently `nox-review` doesn't detect all failures: https://github.com/madjar/nox/issues/52. @peti, there are `gnome` mentions in `hackage-packages.nix`, can you fix Hackage4Nix to use `gnome2` instead?

**Pull request merged**
