### PR TITLE
nixos/opendkim: systemd sandbox

### PR DESCRIPTION
**Pull request by tnias**
###### Motivation for this change

Add systemd service sandbox features.

###### Things done

- [x] tested on a mailserver based on [simple-nixos-mailserver](https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/)

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc opendkim maintainer @abbradar

### CODE REVIEW

**Comment by symphorien** [comment]
CC @nlewo : this breaks simple nixos mailserver, because it uses PreStart to generate the key apparently.

relevant log:
```
server # 2020-08-08T21:37:56.922138+00:00 server systemd[1]: Starting OpenDKIM signing and verification daemon...
server # [   19.490661] systemd[1]: Starting OpenDKIM signing and verification daemon...
server # [   20.799512] opendkim-pre-start2020-08-08T21:37:58.233772+00:00 server opendkim-pre-start[866]: .opendkim-genkey-wrapped: openssl exited with status %d
server # [866]: .opendkim-genkey-wrapped: openssl exited with status %d
server # 2020-08-08T21:37:58.243123+00:00 server opendkim-pre-start[866]: 1
server # [   20.810270] opendkim-pre-start[866]: 1
server # 2020-08-08T21:37:58.256087+00:00 server systemd[1]: opendkim.service: Control process exited, code=exited, status=1/FAILURE
server # [   20.823766] systemd[1]: opendkim.service: Control process exited, code=exited, status=1/FAILURE
server # 2020-08-08T21:37:58.261531+00:00 server systemd[1]: opendkim.service: Failed with result 'exit-code'.
server # [   20.835354] systemd[1]: opendkim.service: Failed with result 'exit-code'.
server # 2020-08-08T21:37:58.272523+00:00 server systemd[1]: Failed to start OpenDKIM signing and verification daemon.
server # [   20.846334] systemd[1]: Failed to start OpenDKIM signing and verification daemon.
```

**Comment by nlewo** [comment]
@tnias I think we need to add a `ReadWritePaths = [cfg.keyPath]`. The current implementation is working because the default value of `keyPath` is `/var/lib/opendkim/keys` which is in the default systemd `stateDir`.
@symphorien If `cfg.keyPath` is a "readWrite" path, I think this should work for SNM.

**Comment by symphorien** [comment]
simple-nixos-mailserver tests now pass with this diff:
```diff
diff --git a/mail-server/opendkim.nix b/mail-server/opendkim.nix
index d381519..6fd0bef 100644
--- a/mail-server/opendkim.nix
+++ b/mail-server/opendkim.nix
@@ -56,6 +56,7 @@ in
       services.opendkim = {
         enable = true;
         selector = cfg.dkimSelector;
+        keyPath = cfg.dkimKeyDirectory;
         domains = "csl:${builtins.concatStringsSep "," cfg.domains}";
         configFile = pkgs.writeText "opendkim.conf" (''
           Canonicalization relaxed/simple
```

**Comment by symphorien** [comment]
I also ran simple-nixos-mailserver's tests with success on top of the merge of this PR and #93293 #93277 and #93305

**Comment by symphorien** [comment]
These PRs probably deserve (succinct) release notes.

**Comment by nlewo** [comment]
> These PRs probably deserve (succinct) release notes.

Yep, @tnias could you please add a sentence saying opendkim is now sanboxed in the section "Other Notable Changes" of the 20.09 release notes?

**Comment by tnias** [comment]
Yes, will add it.

**Comment by tnias** [comment]
@nlewo I rebased the patches against current master, as to not interfere with other releasenote changes.

**Comment by nlewo** [comment]
Thanks!

**Pull request merged**
