### PR TITLE
eternal-terminal: 4.1.2 -> 5.1.6.

### PR DESCRIPTION
**Pull request by qolii**
###### Motivation for this change
Standard update. Also remove an unneeded dependency, as highlighted in #45834.

This supersedes #45834.

I've tested this on a macOS->NixOS connection, and it seems to work just fine!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
@GrahamcOfBorg build eternal-terminal

**Comment by jtojnar** [comment]
While at it, could you add `ninja` to `nativeBuildInputs` and remove `enableParallelBuilding`? The former will make the build log slightly cleaner and possibly faster builds, the latter is already implied by `cmake`.

**Comment by qolii** [comment]
Done!

**Comment by jtojnar** [comment]
@GrahamcOfBorg build eternal-terminal

**Comment by qolii** [comment]
Thanks, @jtojnar!

**Pull request merged**
