### PR TITLE
nixos/systemd: don't require network-online.target for multi-user.taget v2

### PR DESCRIPTION
**Pull request by rnhmjoj**
This is another attempt at 62f30634 after the original change was reverted in 0d85bf0e because NetworkManager and other tests were broken.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested via:
  - [x] `nixosTests.networking.scripted`
  - [x] `nixosTests.networking.networkd`
  - [x] `nixosTests.networking.networkmanager`
  - [x] `nixosTests.connman` (fails, unrelated)
  - [x] `nixosTests.wpa_supplicant`
  - [x] `nixosTests.ipv6`
  - [x] `nixosTests.nat`
  - [x] `nixosTests.acme`
  - [x] `nixosTests.custom-ca`
  - [x] `nixosTests.bittorrent`
  - [x] `nixosTests.printing-service`
  - [x] `nixosTests.printing-socket`
  - [x] `nixosTests.printing-service-notcp`
  - [x] `nixosTests.printing-socket-notcp`
  - [x] `nixosTests.openssh`
  - [x] `nixosTests.libreswan`
  - [x] `nixosTests.libreswan-nat`
  - [x] `nixosTests.privoxy`
  - [x] `nixosTests.jool`
  - [x] `nixosTests.tayga`
  - [x] `nixosTests.magnetico`
  - [x] `nixosTests.dnsdist`
  - [x] `nixosTests.gnupg`
  - [x] `nixosTests.nginx`
  - [x] `nixosTests.caddy`
  - [x] `nixosTests.searx`
  - [x] `nixosTests.gitea`
  - [x] `nixosTests.nfs3` (fails, unrelated?)
  - [x] `nixosTests.nfs4`
  - [x] `nixosTests.samba`
  - [x] `nixosTests.fail2ban`
  - [x] `nixosTests.plasma5`
  - [x] `nixosTests.plasma6`
  - [x] `nixosTests.gnome`
  - [x] `nixosTests.gnome-xorg`

- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rnhmjoj** [comment]
I run quite a few tests with complex networking setup and I couldn't find any issue. The warnings abut `After=network-online.target` without the `Wants=` have been there for a year, so they must have worked.

I added a release note for 25.05. Is there anything I have to do?

**Review by rhendric — APPROVED** [review]

**Comment by flokli** [comment]
Let's get this in, it's been cooking for long enough. Thanks!

**Comment by Slabity** [comment]
This change appears to break NetworkManager on my system. It does not start automatically unless I manually add `systemd.targets.network-online.wantedBy = [ "multi-user.target" ];` back to my configuration. Otherwise I need to manually start the service before it comes up and connects to the network. Here's the relevant configuration:

```nix
networking.networkmanager ={
  enable = true;
  plugins = with pkgs; [
    networkmanager-openvpn
    networkmanager-openconnect
    networkmanager-vpnc
  ];
  unmanaged = [ "interface-name:ve-*" ];
};
```

And to be honest, I see zero difference in login speed between the two configurations.

Does something need to be changed with NetworkManager to get it working properly again?

**Comment by rnhmjoj** [comment]
Strange, `nixosTests.networking.networkmanager` was passing. Maybe the test script was doing something that would start the service.

Anyway, I don't know how NetworkManager is supposed to be started: for comparison dhcpcd wants network.target and is wanted by multi-user.target, while network-manager for some reason is wanted by network.target, but there's a NetworkManager-ensure-profiles service part of multi-user that pulls NetworkManager.service in...

**Comment by rnhmjoj** [comment]
@NixOS/freedesktop

**Comment by Slabity** [comment]
I think this should probably be reverted until things like #368262 and #368684 are fixed. It's affecting more stuff than expected (which is probably why it wasn't fully done in the past).

**Comment by rnhmjoj** [comment]
I'd rather not, otherwise people will never fix their stuff: the change was already postponed for one year.
We're just past the release, so this is best time for causing a little breakage.

**Comment by jtojnar** [comment]
Looking at the [upstream unit](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/83d99669f53557aeed2934d0687339ba8adf64d1/data/NetworkManager.service.in#L32) `NetworkManager.service` should itself be a dependency of `multi-user.target`.

Looks like you fixed that in https://github.com/NixOS/nixpkgs/pull/368791.

**Comment by vcunat** [comment]
- [ ] `nixosTests.kea`

**Comment by rnhmjoj** [comment]
@vcunat see https://github.com/NixOS/nixpkgs/pull/369601

**Pull request merged**
