### PR TITLE
nixos/utils: introduce genJqStructuredSecretsReplacementSnippet, deprecate genJqSecretsReplacementSnippet

### PR DESCRIPTION
**Pull request by jian-lin**
## Description of changes

genJqReplacementSnippet quotes the content of the secret file in the
output json file, which prevents structured secret, such as a list or
an object, from being used.

This patch is a breaking change for genJqSecretsReplacementSnippet'.
Since the function is somewhat internal, it should be fine.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [X] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jian-lin** [comment]
@ofborg test gitlab sing-box lemmy engelsystem artalk discourse

filebeat does not have a NixOS test.

netbird's NixOS test does not use secrets.

**Comment by Aleksanaa** [comment]
We usually add a new function in this case and guide users to use this function in the documentation. Changing the current behavior seems less ideal.

**Comment by jian-lin** [comment]
> We usually add a new function in this case and guide users to use this function in the documentation

Could you provide some precedents?

> Changing the current behavior seems less ideal.

Providing two slightly different functions is also not good.

To be clear, there is no **implicit** behavior change.  Out-of-tree usage of genJqSecretsReplacementSnippet will fail to eval **without damaging running systems**. With a post in https://discourse.nixos.org/t/breaking-changes-announcement-for-unstable/17574 , I consider the situation good enough.

The current somewhat mysterious error message "error: cannot coerce a function to a string" can be improved at the cost of worse interface of genJqSecretsReplacementSnippet:  we decrease the number of parameters by move some parameters into the newly added attribute set like this

```nix
genJqSecretsReplacementSnippet' = attr: { set, output, quote ? false }:
```

Then the error message becomes more clear

```console
error: function 'genJqSecretsReplacementSnippet'' called without required argument 'set'

       at /path/to/nixpkgs/nixos/lib/utils.nix:215:43:

          214|   # attr which identifies the secret to be changed.
          215|   genJqSecretsReplacementSnippet' = attr: { set, output, quote ? false }:
             |                                           ^
          216|     let
```

**Comment by Guanran928** [comment]
> Could you provide some precedents?

Maybe https://github.com/NixOS/nixpkgs/pull/287364

**Comment by jian-lin** [comment]
Switched to a non-breaking approach.  Please re-review.

**Comment by linyinfeng** [comment]
I think this is not an ideal solution since end users can not choose between string or JSON secrets.

A better user interface should allow users to choose whether the secret is JSON or string for every single secret. For example,

```nix
genJqSecretsReplacementSnippet {
  example = [
    {
      irrelevant = "not interesting";
    }
    {
      ignored = "ignored attr";
      relevant = {
        secretString1 = {
          _secret = "/path/to/secret";
        };
        secretString2 = {
          _secret = "/path/to/secret";
          quote = true; # or some other attribute name
        };
        secretJson = {
          _secret = "/path/to/secret";
          quote = false; # or some other attribute name
        };
      };
    }
  ];
} "/path/to/output.json"
```

And, another advantage of this user interface is that it keeps backward compatibility.

**Comment by Aleksanaa** [comment]
Perhaps we could use a shorter name for your new function, and keep the initially compatible behavior?

**Comment by linyinfeng** [comment]
> A better user interface should allow users to choose whether the secret is JSON or string for every single secret.

A demo: <https://github.com/NixOS/nixpkgs/compare/master...linyinfeng:nixpkgs:json-secrets>.

```nix
# demo.nix
let
  demoNixpkgs = fetchTarball "https://github.com/linyinfeng/nixpkgs/archive/refs/heads/json-secrets.zip";
  pkgs = import demoNixpkgs {};
  inherit (pkgs) lib;
  utils = import "${demoNixpkgs}/nixos/lib/utils.nix" {
    inherit lib pkgs;
    config = null;
  };
in
utils.genJqSecretsReplacementSnippet {
  example = [
    {
      irrelevant = "not interesting";
    }
    {
      ignored = "ignored attr";
      relevant = {
        secretString1 = {
          _secret = "/path/to/secret-quote-1";
        };
        secretString2 = {
          _secret = "/path/to/secret-quote-2";
          quote = true; # or some other attribute name
        };
        secretJson = {
          _secret = "/path/to/secret-json";
          quote = false; # or some other attribute name
        };
      };
    }
  ];
} "/path/to/output.json"
```

```console
$ nix eval --file ./demo.nix --impure --raw
if [[ -h '/path/to/output.json' ]]; then
  rm '/path/to/output.json'
fi

inherit_errexit_enabled=0
shopt -pq inherit_errexit && inherit_errexit_enabled=1
shopt -s inherit_errexit
secret1=$(<'/path/to/secret-json')
export secret1

secret2=$(<'/path/to/secret-quote-1')
export secret2

secret3=$(<'/path/to/secret-quote-2')
export secret3

/nix/store/axpqa3f5l63mc38h11x1gc5cykw8bn5i-jq-1.7.1-bin/bin/jq >'/path/to/output.json' '."example"[1]."relevant"."secretJson" = ($ENV.secret1 | fromjson) | ."example"[1]."relevant"."secretString1" = ($ENV.secret2) | ."example"[1]."relevant"."secretString2" = ($ENV.secret3)' <<'EOF'
{"example":[{"irrelevant":"not interesting"},{"ignored":"ignored attr","relevant":{"secretJson":{"_secret":"/path/to/secret-json","quote":false},"secretString1":{"_secret":"/path/to/secret-quote-1"},"secretString2":{"_secret":"/path/to/secret-quote-2","quote":true}}}]}
EOF
(( ! $inherit_errexit_enabled )) && shopt -u inherit_errexit
```

**Comment by jian-lin** [comment]
> I think this is not an ideal solution since end users can not choose between string or JSON secrets.

Even though I do not like the idea that users are able to choose between string and JSON secrets, especially with string as the default, I think it is the only backward compatible way.  

I also realize that my current implementation is actually a breaking change due to lack of a notification mechanism to tell users `genJqSecretsReplacementSnippet` is replaced with `genJqStructuredSecretsReplacementSnippet` and they should quote their secrets.

---

@linyinfeng Would you like to create a PR?

**Comment by linyinfeng** [comment]
> Even though I do not like the idea that users are able to choose between string and JSON secrets, especially with string as the default, I think it is the only backward compatible way.

I believe that string should be a reasonable default. 

1. Most of the time, a secret is a string. The old `genJqSecretsReplacementSnippet` already meets the needs of most users.

2. Converting some secrets to JSON string literals is hard since some strong secrets can contain special characters like `"` or `\`.

3. Since typical secrets are string, using plain text files makes the secret files format-orthogonal.

> @linyinfeng Would you like to create a PR?

I created <https://github.com/NixOS/nixpkgs/pull/325217>.

**Comment by jian-lin** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/325217

**Pull request closed without merging**
