### PR TITLE
coqPackages.vcfloat: init at 2.1.1

### LINKED ISSUE #257548: Package request: CoqPackages.vcfloat
**Project description**

VCFloat: A Unified Coq Framework for Verifying C Programs with Floating-Point Computations

**Metadata**

* homepage URL: https://verinum.org/ 
* source URL: https://github.com/VeriNum/vcfloat
* license: LGPL
* platforms: <uncertain limitations here>

### PR DESCRIPTION
**Pull request by quinn-dougherty**
**Sorry everyone about #257959 -- the pings really snuck up on me, I had no idea that was going to happen. It was also inconsiderate to have not gotten the commit squash/messaging stuff right initially.**

## Description of changes
Closes https://github.com/NixOS/nixpkgs/issues/257548

VCFloat: A Unified Coq Framework for Verifying C Programs with Floating-Point Computations

Metadata
- homepage URL: https://verinum.org/
- source URL: https://github.com/VeriNum/vcfloat
- license: LGPL3

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
(@wegank sry about keeping the word `version` in there-- I read it directly from `CONTRIBUTING.md`) 

@Zimmi48 @vbgl (I was told on Zulip that these are the people to tag)

**Comment by wegank** [comment]
@ofborg build coqPackages.vcfloat coqPackages.vcfloat.passthru.tests

**Comment by proux01** [comment]
@quinn-dougherty if you want, you can test this in the Coq Nix toolbox: https://github.com/coq-community/coq-nix-toolbox#testing-coqpackages-updates-in-nixpkgs

**Review by Zimmi48 — APPROVED** [review]
Hello,

Sorry for the long delay to review this PR!

I've opened https://github.com/coq-community/coq-nix-toolbox/pull/167 to test that there is no build issue and I'll merge CI passes there after.

**Pull request merged**
