### PR TITLE
nixos/{boinc,guix}: Use exec to start the payload binary of the service

### PR DESCRIPTION
**Pull request by lucasew**
## Description of changes
Right now both Guix and Boinc services have the following behaviour:

- Systemd start bash passing the start script
- Bash starts the payload process
- The payload process starts as bash children

The problem of this is that Bash is not being used anymore because it's blocked by the payload process and when it's unblocked bash will be closed anyway. Bash can turn into the payload process using the command exec. That's what I did.

The list is not exaustive, there may be more modules with this same issue but that's the modules I use that are having this issue.

Each occurence can help making the system use a few megabytes less of RAM.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 297526` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>

**Comment by Luflosi** [comment]
This is a definite improvement.
However I'm wondering why we don't just use systemd's `ExecStart` directly. What is the purpose of using a script if no shell features seem to be used? I'm confident this is at least true for boinc but didn't look at guix.

**Comment by lucasew** [comment]
> This is a definite improvement. However I'm wondering why we don't just use systemd's `ExecStart` directly. What is the purpose of using a script if no shell features seem to be used? I'm confident this is at least true for boinc but didn't look at guix.

I think it's because of that path option that sets up PATH for the service, and for services that take multiple lines. Basically convenience.

If it's just one command the overhead is basically zero if one uses this exec tip.

**Comment by lucasew** [comment]
> What do you mean by that? Which path option? And which of the two modules are you talking about? Both?

The path option: https://search.nixos.org/options?channel=unstable&show=systemd.user.services.%3Cname%3E.path&from=0&size=50&sort=relevance&type=packages&query=path

> Ok but two of the four scripts you changed only have one line, so let's use `ExecStart` for those. The other two are fine with me.

I was just following the pattern. Not sure if there is a RFC about this issue.

**Comment by Luflosi** [comment]
> The path option: https://search.nixos.org/options?channel=unstable&show=systemd.user.services.%3Cname%3E.path&from=0&size=50&sort=relevance&type=packages&query=path

I don't see that being used in any of the two services. What am I missing?

> I was just following the pattern. Not sure if there is a RFC about this issue.

I'm not aware of any RFC but the `systemd.services.<name>.script` option just creates a shell script with the provided commands, writes the file to the Nix store and then sets `ExecStart` to execute that script. In my personal opinion, all this extra stuff should not be used if it's possible to just use `ExecStart` directly. It also makes debugging easier when one wants to see what is being executed as one can just read the command directly in the unit file instead of having to follow another indirection to the shell script.

I see you've changed three of the four scripts to use `ExecStart` instead, even the script that spans multiple lines. I was sceptical, so I did some testing and this indeed works. [The documentation](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Command%20lines) also confirms this (see the example with `ExecStart=echo / >/dev/null & \; \` in the first line and `ls` in the second line). Is there anything stopping you from changing the last script as well? To be fair, this is just my personal preference but if you don't see any downsides as well, why not go for it?

I suggest you change the commit messages as they are not accurate anymore.

**Comment by lucasew** [comment]
> > The path option: https://search.nixos.org/options?channel=unstable&show=systemd.user.services.%3Cname%3E.path&from=0&size=50&sort=relevance&type=packages&query=path
> 
> I don't see that being used in any of the two services. What am I missing?
> 
> > I was just following the pattern. Not sure if there is a RFC about this issue.
> 
> I'm not aware of any RFC but the `systemd.services.<name>.script` option just creates a shell script with the provided commands, writes the file to the Nix store and then sets `ExecStart` to execute that script. In my personal opinion, all this extra stuff should not be used if it's possible to just use `ExecStart` directly. It also makes debugging easier when one wants to see what is being executed as one can just read the command directly in the unit file instead of having to follow another indirection to the shell script.
> 
> I see you've changed three of the four scripts to use `ExecStart` instead, even the script that spans multiple lines. I was sceptical, so I did some testing and this indeed works. [The documentation](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Command%20lines) also confirms this (see the example with `ExecStart=echo / >/dev/null & \; \` in the first line and `ls` in the second line). Is there anything stopping you from changing the last script as well? To be fair, this is just my personal preference but if you don't see any downsides as well, why not go for it?
> 
> I suggest you change the commit messages as they are not accurate anymore.

I'd would do as everyone is doing with the script option. I sent this just to avoid the necessity of having that bash intermediary process in the process tree that would vanish if there is a exec in the last line.

I think this ExecStart thing should be out of the scope of this PR and if you think it's actually important I think you should first gather feedback from more people using an RFC and then in the RFC process make a treewide change that solves this hipothetical issue in the whole nixpkgs at once.

**Review by Luflosi — APPROVED** [review]
LGTM.

**Review by FliegendeWurst — APPROVED** [review]

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
