### PR TITLE
fontforge: 20170730 -> 20190317

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://github.com/fontforge/fontforge/releases/tag/20190317

* add zmq (collab), woff2 (format), readline (cli)
* "just in case", keep determinism patching
* fontforge-fonttools: replace with override enabling tools
  Don't see any reason to not include by default,
  so this might make more sense as an alias instead.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build creep

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build tlwg ricty liberation-sans-narrow

**Comment by xeji** [comment]
@GrahamcOfBorg eval

**Comment by volth** [comment]
Updating ```fontforge``` might change ```sha256``` of some FODs in ```data/fonts``` (unlikely, but possible), and it won't be detected in our casual workflow because FODs are not going to rebuild.
Someone, who does not have ```cache.nixos.org``` in her list of binary caches eventually might get a strange hash mismatch.

So, the idea is to force Hydra (or ofborg?) to always rebuild FODs and ensure the output hash is still valid.

**Pull request merged**
