### PR TITLE
kmymoney: fix build

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
do you mind changing the commits to match:
```
python3Packages.weboob: 1.3 -> 1.5
kmymoney: 5.0.5 -> 5.0.7
```

**Comment by Mic92** [comment]
Done

**Comment by jonringer** [comment]
@GrahamcOfBorg build kmymoney

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS (1 broken on master)
diff LGTM
kmymoney launches fine

```
[4 built (1 failed), 149 copied (488.2 MiB), 86.3 MiB DL]
error: build of '/nix/store/wrywxdg732501qays5rbdq1lykybpahs-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/72221
1 package failed to build:
python27Packages.weboob

3 package were build:
kmymoney python37Packages.weboob python38Packages.weboob
```

**Pull request merged**
