### PR TITLE
normcap: 0.4.4 -> 0.5.2

### PR DESCRIPTION
**Pull request by markus1189**
## Description of changes

A pretty big bump version-wise: https://github.com/dynobo/normcap/releases

<s>I had to add the `substituteInPlace` which is pretty ugly to avoid this error:</s> (EDIT: fixed by adding pytest-cov as @christoph-heiss suggested)

```
error: builder for '/nix/store/6jj1izjxnndzdrqags3kfdiap7qbhzy0-normcap-0.5.2.drv' failed with exit code 4;
       last 10 log lines:         
       > > Warning:          Could not resolve keysym XF86ClearvuSonar
       > > Warning:          Could not resolve keysym XF86SidevuSonar
       > > Warning:          Could not resolve keysym XF86NavInfo                                                                                                                                                   
       > Errors from xkbcomp are not fatal to the X server                                                                                                                                                          
       > ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
       > __main__.py: error: unrecognized arguments: --cov --cov-report=xml --cov-report=html
       >   inifile: /build/source/pyproject.toml                                                                                                                                                                    
       >   rootdir: /build/source                                                                         
       > 
       > /nix/store/d4jf1cbbk494zwgbqz31pxgigpsbh6w2-stdenv-linux/setup: line 1553: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/6jj1izjxnndzdrqags3kfdiap7qbhzy0-normcap-0.5.2.drv'.
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by christoph-heiss** [comment]
> I had to add the `substituteInPlace` which is pretty ugly to avoid this error:

This can easily be fixed properly be adding `pytest-cov` to `nativeCheckInputs`:
```diff
diff --git a/pkgs/by-name/no/normcap/package.nix b/pkgs/by-name/no/normcap/package.nix
index 3b538329965d..27ff118ed9a7 100644
--- a/pkgs/by-name/no/normcap/package.nix
+++ b/pkgs/by-name/no/normcap/package.nix
@@ -52,13 +52,6 @@ ps.buildPythonApplication rec {
     ps.toml
   ];

-  postPatch = ''
-     substituteInPlace pyproject.toml \
-       --replace "\"--cov\"," "" \
-       --replace "\"--cov-report=xml\"," "" \
-       --replace "\"--cov-report=html\"," ""
-  '';
-
   preFixup = ''
     makeWrapperArgs+=(
       "''${qtWrapperArgs[@]}"
@@ -70,6 +63,7 @@ ps.buildPythonApplication rec {
   nativeCheckInputs = wrapperDeps ++ [
     ps.pytestCheckHook
     ps.pytest-qt
+    ps.pytest-cov
     ps.toml
   ] ++ lib.optionals stdenv.isLinux [
     ps.pytest-xvfb
```

**Comment by markus1189** [comment]
@christoph-heiss indeed, thanks!

**Review by christoph-heiss — APPROVED** [review]
Result of `nixpkgs-review pr 278448` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>normcap</li>
    <li>normcap.dist</li>
  </ul>
</details>

Did some smoketesting. Stumbled onto [this issue](https://github.com/dynobo/normcap/issues/375) under sway, but that's probably just a problem on my side, thus LGTM.

**Comment by pbsds** [comment]
Neat! 

Generally we strive to disable coverage testing when possible, seeing as it is a development hygiene check and not a correctness check in an of itself.

There is duplicate work in #275063, which is struggling with the same darwin check errors as this PR does. The push-and-wait-for-ofborg debugging loop has been slow, with low attention over the holidays.

**Comment by luzpaz** [comment]
Note 0.5.4 is latest release https://github.com/dynobo/normcap/blob/main/CHANGELOG#v054-2024-01-15

**Pull request closed without merging**
