### PR TITLE
docker: migrate to buildGoModule

### PR DESCRIPTION
**Pull request by Gerg-L**
## Description of changes
part of: https://github.com/NixOS/nixpkgs/issues/318069

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vdemeester** [comment]
Result of `nixpkgs-review pr 318922` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>devcontainer</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>airlift</li>
    <li>airlift.dist</li>
    <li>apptainer</li>
    <li>apptainer-overriden-nixos</li>
    <li>charliecloud</li>
    <li>docker (docker_24)</li>
    <li>docker-client</li>
    <li>docker-gc</li>
    <li>docker-sbom</li>
    <li>docker_25</li>
    <li>docker_26</li>
    <li>fn-cli</li>
    <li>nvidia-docker</li>
    <li>pipework</li>
    <li>python311Packages.jupyter-repo2docker</li>
    <li>python311Packages.jupyter-repo2docker.dist</li>
    <li>python312Packages.jupyter-repo2docker</li>
    <li>python312Packages.jupyter-repo2docker.dist</li>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>udocker</li>
    <li>udocker.dist</li>
  </ul>
</details>

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by msanft — APPROVED** [review]
LGTM. The `devcontainer` build seems to be broken, but is unrealted to this PR and also broken on main

**Comment by vdemeester** [comment]
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/axrcfrdihcc90v1sfkfv3s0f6sbkk5p1-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
yarn config v1.22.22
success Set "yarn-offline-mirror" to "/nix/store/7q311bg1n8v5zgbrkjxx336zycm38ff9-offline".
Done in 0.17s.
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[] 0/554[] 3/554[] 8/554[] 13/554[] 16/554[] 18/554[] 20/554[] 26/554[] 29/554[] 33/554[] 37/554[] 40/554[] 43/554[] 49/554[] 51/554[] 55/554[] 57/554[] 58/554[] 63/554[] 71/554[] 81/554[] 90/554[] 97/554[] 101/554[] 102/554[] 104/554[] >
[] 554/554[] 0/589[] 0/16489[] 510/16489[] 930/16489[] 1314/16489[] 1568/16489[] 1702/16489[] 1830/16489[] 1960/16489[] 2051/16489[] 2248/16489[] 2457/16489[] 2585/16489[] 2777/16489[] 3010/16489[] 3126/16489[] 3240/16489[] 3368/16489[] >

error /build/source/node_modules/esbuild: Command failed.
Exit code: 127
Command: node install.js
Arguments: 
Directory: /build/source/node_modules/esbuild
Output:
/bin/sh: node: not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This is the "weird" failure of `devcontainer`. I have no idea why it fails but it does not seem to be related *at al* to this update so I think it should be fine to merge. Even on `master`, `devcontainer` doesn't build (same error with `nix build .#devcontainer`).

**Review by SuperSandro2000 — COMMENTED** [review]
LGTM

**Comment by Gerg-L** [comment]
I'm assuming Sandro misclicked review instead of approve :D

**Comment by Gerg-L** [comment]
devcontainer was just missing nodejs in nativeBuildInputs, fixed it

**Comment by Gerg-L** [comment]
Result of `nixpkgs-review pr 318922` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>airlift</li>
    <li>airlift.dist</li>
    <li>apptainer</li>
    <li>apptainer-overriden-nixos</li>
    <li>charliecloud</li>
    <li>devcontainer</li>
    <li>docker</li>
    <li>docker-client</li>
    <li>docker-gc</li>
    <li>docker-sbom</li>
    <li>docker_25</li>
    <li>docker_26</li>
    <li>fn-cli</li>
    <li>nvidia-docker</li>
    <li>pipework</li>
    <li>python311Packages.jupyter-repo2docker</li>
    <li>python311Packages.jupyter-repo2docker.dist</li>
    <li>python312Packages.jupyter-repo2docker</li>
    <li>python312Packages.jupyter-repo2docker.dist</li>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>udocker</li>
    <li>udocker.dist</li>
  </ul>
</details>

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
