### PR TITLE
yubikey-personalization-gui: install man, desktop files and icons

### PR DESCRIPTION
**Pull request by offlinehacker**
###### Motivation for this change

Nices integration with desktop environments

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg eval

**Review by worldofpeace — CHANGES_REQUESTED** [review]
There are more files you could be installing.

See various other build expression in other distros
* https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/yubikey-personalization-gui#n36
* https://src.fedoraproject.org/rpms/yubikey-personalization-gui/blob/master/f/yubikey-personalization-gui.spec#_35

The pkgbuild looked most correct to me.

**Comment by offlinehacker** [comment]
I agree, but it's start. Do you want me to open issue for improvements?

**Comment by offlinehacker** [comment]
I will add PNG file still, as that one should really be copied

**Comment by worldofpeace** [comment]
> I agree, but it's start. Do you want me to open issue for improvements?

I thought we could just copy what archlinux was doing :smile: 
It looks very complete.

**Comment by offlinehacker** [comment]
will do 🙂

**Comment by offlinehacker** [comment]
Should be good now, thanks!

**Review by worldofpeace — APPROVED** [review]
Things tested.

1. icons converted correct, appear fine :heavy_check_mark: 
2. can view man page with `man` ✔️
3. can launch application from desktop file and has icons ✔️

**Pull request merged**
