### PR TITLE
effitask: init at 1.4.0

### PR DESCRIPTION
**Pull request by davidak**
###### Motivation for this change

it looks like a good todo.txt gui :)

Screenshot from 2020-04-05 01-16-21

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Emantor** [comment]
I get a hash-mismatch when trying to build:
```
$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/phoenix/.cache/nixpkgs-review/pr-84291/build.nix
hash mismatch in fixed-output derivation '/nix/store/vnb83xkhpmafcigva15javzw0f90j6nb-effitask-1.4.0-vendor.tar.gz':
  wanted: sha256:1crp43577k6ggywmdrphnfa8q353shj7746q07bv2vgbj84qqnqn
  got:    sha256:0dvmp23kny6rlv6c0mfyy3cmz1bi5wcm1mxps4z67lym5kxfd362
cannot build derivation '/nix/store/6qlm90gfg48b1nlkd9d0c0f2xpv1rxa3-effitask-1.4.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fyr7p1l5ch6mvyi9znnl266xga367il4-env.drv': 1 dependencies couldn't be built
[1 built (1 failed), 132 copied (1454.1 MiB), 395.2 MiB DL]
error: build of '/nix/store/fyr7p1l5ch6mvyi9znnl266xga367il4-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/84291
1 package failed to build:
effitask
```

**Comment by davidak** [comment]
@Emantor thanks for your effort to test this!

That is strange. The hash is correct when i build it using `nix-env -f ~/code/nixpkgs -i effitask`.

```
installing
hash mismatch in fixed-output derivation '/nix/store/5yvbxh2q627ppk5jvwfk7gpdjphpkv1y-effitask-1.4.0-vendor.tar.gz':
  wanted: sha256:0000000000000000000000000000000000000000000000000000
  got:    sha256:1crp43577k6ggywmdrphnfa8q353shj7746q07bv2vgbj84qqnqn
cannot build derivation '/nix/store/wyxm09hv0vcm0q5vw5yb7a3g7h7x7yrd-effitask-1.4.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/wyxm09hv0vcm0q5vw5yb7a3g7h7x7yrd-effitask-1.4.0.drv' failed
```

And don't get the error with `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 84291"`.

```
...
Automatic merge went well; stopped before committing as requested
$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/davidak/.cache/nixpkgs-review/pr-84291/build.nix
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
[2 built, 224 copied (1890.5 MiB), 485.3 MiB DL]
https://github.com/NixOS/nixpkgs/pull/84291
1 package built:
effitask
```

What could be the difference here?

**Comment by Emantor** [comment]
@davidak are you on stable or unstable? I'm running NixOS unstable.

**Comment by davidak** [comment]
@Emantor i'm on stable.

nixpkgs-review has the same version. 

```
$ nix run -f channel:nixos-19.09 nixpkgs-review
$ which nixpkgs-review
/nix/store/35vbwh8hmy935xhh6xd5x65c74iz597g-nixpkgs-review-2.2.0/bin/nixpkgs-review

$ nix run -f channel:nixos-unstable nixpkgs-review
$ which nixpkgs-review
/nix/store/9ywlmbslln9va0i2kmbj9gz1bdc40a44-nixpkgs-review-2.2.0/bin/nixpkgs-review
```

Maybe the Nix version?

```
$ nix --version
nix (Nix) 2.3.3
```

**Comment by Emantor** [comment]
I suspect there were some changes pertaining to cargo-vendor. Stable still contains `cargo-vendor` while master has dropped it for the builtin support in `cargo` version `1.37`.

**Comment by davidak** [comment]
@Emantor but the PR is branched from master, so it shouldn't make a difference? Or does nixpkgs-review build the changes of the PR on the current system channel?

**Comment by Emantor** [comment]
Indeed, cargo should be used from master too. Maybe @alyssais has an idea?  (pinging because she did some cargo sha fixups on master, found by a quick `git log --grep`)

**Comment by davidak** [comment]
I had access to a machine with nixos unstable and was able to reproduce the error. Updated it to work on master.

To run it properly, it has to be installed. in nix shell are assets not found. it also neede configured todo.txt-cli (see readme)

**Pull request merged**
