### PR TITLE
rambox: 1.5.0 -> 2.0.6 and remove deprecated CE

### LINKED ISSUE #161741: rambox-pro: 2.0.1
New release available at https://github.com/ramboxapp/download/releases

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: rambox-pro

current version: 1.5.0
desired version: 2.0.1

###### Notify maintainers

maintainers: @cawilliamson

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by vale981**
###### Description of changes

The same as #173896 by @Wabri, but updated for `2.0.6`.

> Since rambox community edition is no longer maintained and not work anymore, I remove it. Here the link to the deprecated repository: https://github.com/ramboxapp/community-edition

> I think this pr could close https://github.com/NixOS/nixpkgs/issues/161741 issue!

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
There seems to be some evaluation errors @ofborg :(

**Comment by vale981** [comment]
:( works locally, but I'll look into it

**Comment by Wabri** [comment]
@vale981 did you manage to find the error?

**Comment by vale981** [comment]
Sorry, I forgot about it. Will hopefully have time to look into it this week.

**Comment by NickCao** [comment]
superseded by https://github.com/NixOS/nixpkgs/pull/202175

**Pull request closed without merging**
