### PR TITLE
Revert google-fonts update to unstable, fixing Inconsolata

### PR DESCRIPTION
**Pull request by jb55**
###### Motivation for this change

An update to an unstable version of `google-fonts` broke the `Inconsolata` monospace font in programs that use xft such as urxvt. This PR reverts some recent `google-fonts` commits back to the stable version.

See:

https://github.com/googlefonts/Inconsolata/issues/42
https://discourse.nixos.org/t/how-to-fix-broken-inconsolata-font-in-urxvt-on-21-05/13437

cc @jakubgs  @06kellyjac @petabyteboy @tu-maurice

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130209` at 0ffd2b93 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>inconsolata</li>
    <li>ricty</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/data/fonts/inconsolata/default.nix:8:3:
```
  |
8 |   installPhase = ''
  |   ^
```
</li>
  </ul>
</details>

**Review by 06kellyjac — CHANGES_REQUESTED** [review]
I'm against this for 2 reasons

1. It's not just reverting the `src` but also reverting improvements like setting it to `stdenvNoCC` (which `inconsolata/default.nix` should use too)
2. The `inconsolata/default.nix` can just change it's own `src` to refer to an older working commit of `google/fonts` rather than reverting every other font in the google-fonts repo to **2019**

Edit: also calling the previous dated version stable is not true, `google/fonts` doesn't have any stable releases, every dated release of `google/fonts` is unstable. It's just someone changed the version text to make that clear

**Comment by jb55** [comment]
ah good point on just updating inconsolata/default.nix, will open a new PR

**Comment by 06kellyjac** [comment]
Thanks @jb55 :tada:

**Pull request closed without merging**
