### PR TITLE
coq: add desktop file for coqide

### PR DESCRIPTION
**Pull request by ncfavier**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
I tested that it works well.
I am unsure about the desktop name "CoqIDE Proof Assistant" since properly speaking CoqIDE is the IDE for the Coq Proof Assistant... but I guess this is fine like this.

**Comment by ncfavier** [comment]
Right, I kind of copied that blindly from other distros. I guess CoqIDE is better.

**Comment by ncfavier** [comment]
@vbgl could you merge this please?

**Comment by ncfavier** [comment]
Thanks!

**Pull request merged**
