### PR TITLE
rkt: 0.14.0 -> 0.15.0

### PR DESCRIPTION
**Pull request by kragniz**

### CODE REVIEW

**Comment by steveeJ** [comment]
I suggest to get #12131 in first and then rebase this PR.

**Comment by kragniz** [comment]
Sounds good, I'll rebase once that is merged.

**Comment by steveeJ** [comment]
@kragniz have you verified functionality of rkt with this build? rkt 0.15 introduced libacl as a new dependency which is not covered yet in the expressions

**Comment by kragniz** [comment]
Yes, I added `acl` as a new build input, and tested locally:

```
[kragniz@lambda-loli:~]$ rkt version
rkt version 0.15.0
appc version 0.7.4

[kragniz@lambda-loli:~]$ sudo rkt --insecure-options=image run docker://redis
rkt: using image from file /nix/store/40pkls3v31pn40rgkf440xl0qrxpv6v3-rkt-0.15.0/bin/stage1-coreos.aci
rkt: remote fetching from URL "docker://redis"
Downloading sha256:81cc5f26a6a: [==============================] 51.4 MB/51.4 MB
Downloading sha256:a3ed95caeb0: [==============================] 32 B/32 B
Downloading sha256:d43cb752619: [==============================] 2.04 KB/2.04 KB
Downloading sha256:861e96e7ae1: [==============================] 6.51 MB/6.51 MB
Downloading sha256:7fae3dcea8a: [==============================] 115 KB/115 KB 
Downloading sha256:b46c28ddbe0: [==============================] 808 KB/808 KB 
Downloading sha256:a3ed95caeb0: [==============================] 32 B/32 B
Downloading sha256:a3ed95caeb0: [==============================] 32 B/32 B
Downloading sha256:a3ed95caeb0: [==============================] 32 B/32 B
Downloading sha256:2d50fb4bcfa: [==============================] 2.99 MB/2.99 MB
Downloading sha256:c8fc9e7dfb8: [==============================] 98 B/98 B
Downloading sha256:a3ed95caeb0: [==============================] 32 B/32 B
Downloading sha256:a3ed95caeb0: [==============================] 32 B/32 B
Downloading sha256:a1a961e320b: [==============================] 196 B/196 B
Downloading sha256:a3ed95caeb0: [==============================] 32 B/32 B
Downloading sha256:a3ed95caeb0: [==============================] 32 B/32 B
Downloading sha256:a3ed95caeb0: [==============================] 32 B/32 B
run: group "rkt" not found, will use default gid when rendering images
Warning: error setting journal ACLs, you'll need root to read the pod journal: group "rkt" not foundWarning: libsystemd not found even though systemd is running. Cgroup limits set by the environment (e.g. a systemd service) won't be enforced.
rkt: warning: no volume specified for mount point "volume-data", implicitly creating an "empty" volume. This volume will be removed when the pod is garbage-collected.
Continuing with per-app isolators disabled: could not determine if we're running from a unit file: unable to open a handle to libsystemd
[730222.697576] entrypoint.sh[4]: 4:C 15 Jan 01:21:22.616 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
[730222.698165] entrypoint.sh[4]: 4:M 15 Jan 01:21:22.616 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
[730222.698371] entrypoint.sh[4]: 4:M 15 Jan 01:21:22.616 # Redis can't set maximum open files to 10032 because of OS error: Operation not permitted.
[730222.698560] entrypoint.sh[4]: 4:M 15 Jan 01:21:22.616 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
[730222.698779] entrypoint.sh[4]: _._
[730222.698959] entrypoint.sh[4]: _.-``__ ''-._
[730222.699163] entrypoint.sh[4]: _.-``    `.  `_.  ''-._           Redis 3.0.6 (00000000/0) 64 bit
[730222.699340] entrypoint.sh[4]: .-`` .-```.  ```\/    _.,_ ''-._
[730222.699514] entrypoint.sh[4]: (    '      ,       .-`  | `,    )     Running in standalone mode
[730222.699688] entrypoint.sh[4]: |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
[730222.699865] entrypoint.sh[4]: |    `-._   `._    /     _.-'    |     PID: 4
[730222.700045] entrypoint.sh[4]: `-._    `-._  `-./  _.-'    _.-'
[730222.700219] entrypoint.sh[4]: |`-._`-._    `-.__.-'    _.-'_.-'|
[730222.700392] entrypoint.sh[4]: |    `-._`-._        _.-'_.-'    |           http://redis.io
[730222.700572] entrypoint.sh[4]: `-._    `-._`-.__.-'_.-'    _.-'
[730222.700745] entrypoint.sh[4]: |`-._`-._    `-.__.-'    _.-'_.-'|
[730222.700915] entrypoint.sh[4]: |    `-._`-._        _.-'_.-'    |
[730222.701097] entrypoint.sh[4]: `-._    `-._`-.__.-'_.-'    _.-'
[730222.701269] entrypoint.sh[4]: `-._    `-.__.-'    _.-'
[730222.701445] entrypoint.sh[4]: `-._        _.-'
[730222.701617] entrypoint.sh[4]: `-.__.-'
[730222.701788] entrypoint.sh[4]: 4:M 15 Jan 01:21:22.617 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
[730222.701959] entrypoint.sh[4]: 4:M 15 Jan 01:21:22.617 # Server started, Redis version 3.0.6
[730222.702162] entrypoint.sh[4]: 4:M 15 Jan 01:21:22.617 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[730222.702339] entrypoint.sh[4]: 4:M 15 Jan 01:21:22.617 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
[730222.702520] entrypoint.sh[4]: 4:M 15 Jan 01:21:22.617 * The server is now ready to accept connections on port 6379
^]^]Container rkt-6ff34772-952b-473b-8853-ef307b813ef8 terminated by signal KILL.

**Comment by steveeJ** [comment]
@kragniz nice, thanks! Please rebase, then we should be good to merge.

**Comment by kragniz** [comment]
Rebased on top of master in last commit.

**Comment by globin** [comment]
I'm having errors that seem to originate from the interaction with systemd (https://gist.github.com/globin/69405b4d81f0c6a2f0fb#gistcomment-1671127)

**Comment by globin** [comment]
This fixes the libsystemd warning and cleans up a bit:
https://gist.github.com/globin/8df634f91e7b18558ade

**Comment by domenkozar** [comment]
@globin instead of relying on `LD_LIBRARY_PATH` it would be best to compile rkt with systemd.

**Comment by globin** [comment]
I didn't manage to do that, systemd is in the build inputs and the configure script has no further options for that.

**Comment by domenkozar** [comment]
It should be picked up during stage1 build, but I haven't looked if we even build it ourselves.

**Comment by steveeJ** [comment]
@domenkozar are you referring to building systemd within the rkt build? the rkt build system has a stage1 flavor named *src*, where it does exactly that. I've also noticed that rkt won't find the systemd libraries, effectively a failure in https://github.com/coreos/go-systemd/blob/7f0723f2757beb369312e795c56cb681a928d7c7/util/util.go#L89. I'm not sure what's the best solution. any suggestions to the rkt build system are welcome.

**Comment by domenkozar** [comment]
I take it Go doesn't have pkgconfig or similar tracking of dependencies? If it just loads systemd library at run time, then it has the same problem as Python and I see no better way than your approach.

**Pull request merged**
