### PR TITLE
python3Packages.{langchain,langchain-core,langchain-community,langchain-openai} update to latest 20241023

### PR DESCRIPTION
**Pull request by sarahec**
1. Updated via update script:
- python3Packages.langchain 0.3.1 -> 0.3.4 [diff](https://github.com/langchain-ai/langchain/compare/refs/tags/langchain==0.3.1...langchain==0.3.4)
- python3Packages.langchain-core 0.3.7->0.3.12 [diff](https://github.com/langchain-ai/langchain/compare/refs/tags/langchain-core==0.3.7...langchain-core==0.3.12)
- python3Packages.langchain-community 0.3.1->0.3.3 [diff](https://github.com/langchain-ai/langchain/compare/refs/tags/langchain-community==0.3.1...langchain-community==0.3.3)
- python3Packages.langchain-openai 0.2.1->0.2.3 [diff](https://github.com/langchain-ai/langchain/compare/refs/tags/langchain-openai==0.2.1...langchain-openai==0.2.3)
2. Relaxed boto3 dep in `langchain-aws`.
3. Disabled new langchain-core integration tests that aren't quite as cross-platform as expected.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sarahec** [comment]
Running into issues with building on Linux. Moving to draft for now.

**Comment by sarahec** [comment]
Result of `nixpkgs-review pr 350758` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
  </ul>
</details>
<details>
  <summary>62 packages built:</summary>
  <ul>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-ollama</li>
    <li>python311Packages.langchain-ollama.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langgraph.dist</li>
  </ul>
</details>

**Comment by sarahec** [comment]
Package build failures above are due to opentelemetry-python being stuck on protobuf 4.

**Review by dotlambda — CHANGES_REQUESTED** [review]
One commit per package.

**Comment by sarahec** [comment]
> One commit per package.

I had squashed this, do you want it parted out?

**Comment by dotlambda** [comment]
> > One commit per package.
> 
> I had squashed this, do you want it parted out?

Yes, you need one commit per package.

**Comment by sarahec** [comment]
> > > One commit per package.
> > 
> > 
> > I had squashed this, do you want it parted out?
> 
> Yes, you need one commit per package.

Thank you, Done. (also for #350773)

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 350758` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
  </ul>
</details>
<details>
  <summary>80 packages built:</summary>
  <ul>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.databricks-sdk</li>
    <li>python311Packages.databricks-sdk.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-ollama</li>
    <li>python311Packages.langchain-ollama.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python311Packages.mlflow</li>
    <li>python311Packages.mlflow.dist</li>
    <li>python311Packages.sagemaker</li>
    <li>python311Packages.sagemaker-mlflow</li>
    <li>python311Packages.sagemaker-mlflow.dist</li>
    <li>python311Packages.sagemaker.dist</li>
    <li>python312Packages.databricks-sdk</li>
    <li>python312Packages.databricks-sdk.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langgraph.dist</li>
    <li>python312Packages.mlflow</li>
    <li>python312Packages.mlflow.dist</li>
    <li>python312Packages.sagemaker</li>
    <li>python312Packages.sagemaker-mlflow</li>
    <li>python312Packages.sagemaker-mlflow.dist</li>
    <li>python312Packages.sagemaker.dist</li>
  </ul>
</details>

**Review by dotlambda — APPROVED** [review]

**Pull request merged**
