### PR TITLE
signal-cli: 0.12.2 -> 0.12.8

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**
## Description of changes

- changes: https://github.com/AsamK/signal-cli/compare/v0.12.2...v0.12.7
  - fixes e.g. https://github.com/AsamK/signal-cli/issues/1399, also an issue for package `scli`
- cc: @ivan

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yorickvP** [comment]
@ofborg build signal-cli

**Comment by raiford** [comment]
Is this ready?  Upstream is now at 0.12.8.

**Comment by KiaraGrouwstra** [comment]
@raiford i've updated to .8 now, but i never managed to successfully use this library before, so perhaps someone who knows how to use this would be in a better position to test it than me

**Comment by raiford** [comment]
Hey,  I think there might have been a mistake with your last push, it is still showing 0.12.7.

I did some manual tests and it looks like 0.12.7 is currently too old but I did manually test 0.12.8 and it works.

**Comment by KiaraGrouwstra** [comment]
@raiford thanks! i updated the PR now.

**Comment by raiford** [comment]
@KiaraGrouwstra Awesome thanks!  I just tested it via `nixpkgs-review` and it works for me

```
[nix-shell:~/.cache/nixpkgs-review/pr-275071-1]$ signal-cli --version
signal-cli 0.12.8

[nix-shell:~/.cache/nixpkgs-review/pr-275071-1]$ signal-cli listAccounts
Number: +XXXXXXXXXX

```

**Comment by KiaraGrouwstra** [comment]
@raiford thanks! lemme also tag maintainer @ivan then.

**Comment by yorickvP** [comment]
@ofborg build signal-cli

**Pull request merged**
