### PR TITLE
python3Packages.pybind11: 2.7.1 -> 2.8.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/pybind/pybind11/releases/tag/v2.8.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Have rebuilt a few hundred packages on macos 10.15 with this, only found pre-existing failures.

**Comment by r-burns** [comment]
Pinning pikepdf to pybind11 v2.7.x fixes downstream ocrmypdf. Would that be acceptable? It would be nice to not prevent the rest of nixpkgs from proceeding to v2.8.0 due to this issue.

**Comment by mweinelt** [comment]
We are not doing overrides within pythonPackages, only for pythonApplications, so I think reverting to 2.7.1 would be the correct move until we hit 21.11 unless someone finds the culprit.

**Comment by r-burns** [comment]
I get that for normal python packages, but pybind11 is a buildtime-only dep (and not really a package anyway, it's just headers). We could do `pybind11' = pybind11.overrideAtrrs (_: { src = ... })` inside of pikepdf and the rest of the python packages would be none the wiser.

**Comment by mweinelt** [comment]
Fixed on staging in 9f866231f89a40d56e06dfce810df4d91e67366e.

**Pull request merged**
