### PR TITLE
kde: add user feedback support

### PR DESCRIPTION
**Pull request by alois31**
###### Description of changes

KDE has a system for gaining user feedback, by means of opt-in telemetry and surveys. Introduce the kuserfeedback library that contains the technical implementation, and enable its use in relevant packages.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alois31** [comment]
So the panel not displaying to open windows seems to be something else (it does not happen if I take everything from this branch). Please let me now if I should back out plasma-workspace anyway to be on the safe side.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Please rebase

**Comment by K900** [comment]
Why these three specifically? I'd probably either enable it on all packages or none of them.

**Comment by alois31** [comment]
> Why these three specifically? I'd probably either enable it on all packages or none of them.

These are the ones I found that implement kuserfeedback telemetry. If further ones are found, these should be added too.

**Comment by K900** [comment]
Just looking at reverse dependencies in e.g. Arch, there's a lot more: https://archlinux.org/packages/extra/x86_64/kuserfeedback/

**Comment by alois31** [comment]
I checked in Arch, Debian and Fedora what applications are built with user feedback support and added them as well. drkonqi and labview are apparently not packaged in nixpkgs at all, so I skipped them.

**Comment by K900** [comment]
Might have been easier to just check the sources at this point... Anyway, I'll verify this works and merge, probably later tonight.

**Comment by K900** [comment]
And before anyone busts out the pitchforks: this is all 100% opt-in, and no data is collected without explicit user consent. In fact, you're not even prompted to contribute data unless you go into the application's settings menu and enable it.

**Pull request merged**
