### PR TITLE
Do not depend on pangox_compat

### LINKED ISSUE #75790: Newer version of pango seems to have broken a few packages
**Describe the bug**
Seems like some updates to pango broke a few packages

Among the broken ones:
 - ettercap (see #75789)
 - pangox-compat (which anydesk needs)
 - probably a few more

**To Reproduce**
1. Try to build ettercap or anydesk from master
2. It will fail to build with some pango-related errors

**Expected behavior**
It should work

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-24-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(maciej): `"nixpkgs-20.03pre204199.3140fa89c51"`
 - nixpkgs: `/home/maciej/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pango
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by jtojnar**
`pango` recently broke `pangox_compat` package but most packages do not actually need it – they were probably only adding it because `gtkglext` required it. We switched to master branch of gtkglext which fixes lot of issues and also no longer requires *pangox*.

|      package      | builds |   runs  |
|-------------------|--------|---------|
| `gnome2.gtkglext` | ✔️      | 🤷‍♀️️ |
| `pcb`             | ✔️      | ✔️       |
| `k3d`             |  ✔️      |   ✔️      |
| `lutris`          |   ⌛️     |         |
| `desmume`         | ✔️      | ✔️       |
| `anydesk`         | ❌      |         |
| `openmodelica`    |     ❌    |         |

`anydesk` seems to be an exception:

```
result/bin/anydesk: error while loading shared libraries: libpangox-1.0.so.0: cannot open shared object file: No such file or directory
```

but what can we expect from unfree software 😜️

`openmodelica` seems to fail for unrelated reasons:

```
checking LAPACK/BLAS flags... configure: error: dgesv (LAPACK) linking failed using -llapack -lblas
configure: error: ./configure failed for OMCompiler
builder for '/nix/store/2ivdliyd5f5r6xigz6j2z7id7bz9vsfw-openmodelica.drv' failed with exit code 1
```

Fixes: https://github.com/NixOS/nixpkgs/issues/75790

### CODE REVIEW

**Comment by worldofpeace** [comment]
Hmmph, :smile: as usual I wish nothing needed `pangox`.

**Review by worldofpeace — APPROVED** [review]
Looks great. I did not runtime test k3d, but everything else that was touched here.

**Comment by worldofpeace** [comment]
I think even trying to remove `libpangox-1.0.so.0` with patchelf on anydesk might break it?
I'm not sure if it actually depended on it, or if this was just from `gtkglext`.

**Review by jonringer — APPROVED** [review]
diff LGTM

```
[242 built (2 failed), 351 copied (3026.1 MiB), 673.8 MiB DL]
error: build of '/nix/store/203mf6w1mwgdvvdlp2cv1zksvcxn4wsk-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/75909
1 package are marked as broken and were skipped:
openmodelica

2 package failed to build:
anydesk gnash

8 package were built:
celestia desmume factor-lang gnome2.gtkglext k3d lutris lutris-free pcb
```

**Pull request merged**
