### PR TITLE
gnome3.evolution-data-server: Hardcode more GSettings schemas

### PR DESCRIPTION
**Pull request by jtojnar**
Geary crashes for me with

```
![???] 11:06:53 1.424732 GLib-GIO: Settings schema 'org.gnome.evolution-data-server.addressbook' is not installed
fish: “geary” terminated by signal SIGTRAP (Trace or breakpoint trap)
```

I used [Coccinelle](http://coccinelle.lip6.fr/) to create a base patch:

`spatch --sp-file hardcode-gsettings.cocci --dir src/ --in-place`

```cocci
@@
expression GSETTINGS_SCHEMA;
expression settings;
@@
- settings = g_settings_new (GSETTINGS_SCHEMA);
+ GSettingsSchemaSource *schema_source;
+ schema_source = g_settings_schema_source_new_from_directory ("@ESD_GSETTINGS_PATH@",  g_settings_schema_source_get_default (), TRUE, NULL);
+ GSettingsSchema *schema;
+ schema = g_settings_schema_source_lookup (schema_source, GSETTINGS_SCHEMA, FALSE);
+ settings = g_settings_new_full (schema, NULL, NULL);
+ g_settings_schema_source_unref (schema_source);
+ g_settings_schema_unref (schema);
```

and then manually fixed the conflict & gsettings-desktop-schemas path.

### CODE REVIEW

**Comment by worldofpeace** [comment]
> I used Coccinelle to create a base patch:

Ooh that's very useful. Is there something like this for python?

**Comment by jtojnar** [comment]
Seems to fix the Geary crashes I encountered.

**Comment by worldofpeace** [comment]
> Seems to fix the Geary crashes I encountered.

Should I do any manual checks on the patches being applied on the source code?

**Comment by jtojnar** [comment]
If you have any ideas what to check…

**Comment by worldofpeace** [comment]
> If you have any ideas what to check…

Bet the [tests](https://gitlab.gnome.org/GNOME/evolution-data-server/tree/master/tests) offer enough coverage to see nothing's gone awry.

**Pull request merged**
