### PR TITLE
python3Packages.thinc: 7.4.4 -> 7.4.5

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

python3Packages.thinc: 7.4.4 -> 7.4.5
    
Changelog:
    
https://github.com/explosion/thinc/releases/tag/v7.4.5
    
Also move cython from propagatedBuildInputs to buildInputs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by drewrisinger — CHANGES_REQUESTED** [review]
* [x] Diff LGTM
* [ ] Commits Should probably be squashed
* [x] Builds via ``nix-review`` on x86-64:

```
https://github.com/NixOS/nixpkgs/pull/106730
9 packages built:
python37Packages.spacy python37Packages.textacy python37Packages.thinc python38Packages.spacy python38Packages.textacy python38Packages.thinc python39Packages.spacy python39Packages.textacy python39Packages.thinc
```

**Comment by danieldk** [comment]
>     * [ ]  Commits Should probably be squashed

I don't think commits should be squashed. Having formatting changes and a version bump in the same commit makes diff-ing hard.

(Also, I have seen other PRs rejected because people do formatting changes and a version bump in one commit ;) .)

**Comment by drewrisinger** [comment]
ack @danieldk. I've had it both ways when submitting PRs, depending on the reviewer. I generally lean slightly towards squashing just b/c the mass amount of commits that ``nixpkgs`` already has (i.e. slowing down fresh clones), but no real preference.

**Comment by danieldk** [comment]
> ack @danieldk. I've had it both ways when submitting PRs, depending on the reviewer. I generally lean slightly towards squashing just b/c the mass amount of commits that `nixpkgs` already has (i.e. slowing down fresh clones), but no real preference.

Yeah, there doesn't seem to be general agreement on such things.

Thanks for the review!

**Comment by drewrisinger** [comment]
> Yeah, there doesn't seem to be general agreement on such things.

This suggests it might be worth adding a section to the ``CONTRIBUTING.md``.

**Pull request merged**
