### PR TITLE
[staging] coreutils: 8.32 -> 9.0

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

This might speed up `cp` and `mv` in nix builds (on certain file systems) since the tools use `copy_file_range` now.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) → I built the small channel on x86_64-linux
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
Release notes: https://lists.gnu.org/archive/html/coreutils-announce/2021-09/msg00000.html

**Comment by dasJ** [comment]
Marking this as ready since a lot of relevant builds are succeeding on the systems I have easy access to (x86_64-linux, aarch64-linux).

I'm still building the entire pkgs/top-level/release-small.nix for these systems but apart from unrelated eval errors, everything seems to be going well.
I will report back when the builds are done.

**Comment by r-burns** [comment]
Cherry-picked 97c7af3f4dab4fb715b65786e3be5ac1b507618e (this PR) back to 7c86d10590ccc5330fed0866fe937faf3e36f7a3 (master).

Encountered during x86_64-darwin stdenv bootstrap: `make[2]: *** No rule to make target '-lintl', needed by 'src/coreutils'.  Stop.`

**Comment by dasJ** [comment]
@r-burns Fixed. Currently building stdenv on x86_64-darwin

**Review by r-burns — APPROVED** [review]
Okay, one very long rebuild later, darwin stdenv is building.

Also tested on x86_64-linux: stdenv, pkgsMusl.coreutils, pkgsStatic.coreutils, pkgsCross.aarch64-multiplatform.coreutils. Problematic leaf packages will probably need to be addressed individually in staging-next.

**Comment by dasJ** [comment]
Still seems to fail on aarch64-linux while building coreutils in the checkPhase:
```
FAIL: tests/tail-2/assert
=========================

x
==> a <==
x

==> foo <==
FAIL tests/tail-2/assert.sh (exit status: 1)
```

**Comment by dasJ** [comment]
This is probably good to go now. I was able to build:
- The small channel on x86_64-linux
- stdenv for x86_64-darwin
- About half the small channel on aarch64 due to my limited computing resources on that platform. No builds failed, just most of them are still running. Succeeding are stdenv, gettext, and vim

**Comment by r-burns** [comment]
I noticed some Go packages were segfaulting in https://github.com/NixOS/nixpkgs/pull/141684, and the segfaults reproduce locally. I bisected the `jx` failure https://hydra.nixos.org/build/156019589 to this bump. Any ideas?

**Pull request merged**
