### PR TITLE
vivaldi: 3.7.2218.45-1 -> 3.8.2259.37-1

### PR DESCRIPTION
**Pull request by badmutex**
###### Motivation for this change
Vivaldi 3.8 is out. See https://vivaldi.com/new/

###### Things done
Version bump and add missing pre/post phase hooks for build and install phases.

Result is tested (this pr is submitted using the build result).

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cawilliamson** [comment]
Sadly this commit broke Widevine (meaning no HTML5 videos can be played in this version.)

Could someone please investigate?

**Comment by badmutex** [comment]
Oh no! Have you tried overriding the drv?  I call vivaldi as `vivaldi.override{proprietaryCodecs=true; enableWidevine=true;}` in my nixos config and verified by following https://help.vivaldi.com/desktop/media/widevinecdm-eme-drm-netflix-amazon-spotify/ .

What version of vivaldi are you upgrading from?

**Comment by cawilliamson** [comment]
> Oh no! Have you tried overriding the drv? I call vivaldi as `vivaldi.override{proprietaryCodecs=true; enableWidevine=true;}` in my nixos config and verified by following https://help.vivaldi.com/desktop/media/widevinecdm-eme-drm-netflix-amazon-spotify/ .
> 
> What version of vivaldi are you upgrading from?

My sincere apologies - after relogging the machine - all works fine.

Not entirely sure what happened but it's all working properly now! :)

**Comment by badmutex** [comment]
> Not entirely sure what happened but it's all working properly now! :)

Glad it's working!

**Pull request merged**
