### PR TITLE
pam_usb, nixos/pam-usb: drop

### LINKED ISSUE #33699: security.pam.usb seems to be broken on unstable
## Issue description

The usb pam module is broken (it requires udisks 1.0, which is not available on DBUS)

### Steps to reproduce

- Add `security.pam.usb.enable = true;` to configuration.nix;
- Rebuild the system;
- Try to run `# pamusb-conf --add-device=MyDev`
Get the following output:
```
Traceback (most recent call last):
  File "/nix/store/kn70lc5x66p0i407xd4i9cg3nn4368f5-pam_usb-0.5.0/bin/.pamusb-conf-wrapped", line 252, in <module>
    '/org/freedesktop/UDisks')
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files
```

- Add a line `services.dbus.packages = [ pkgs.udisks ];`
- Rebuild the system;
- Try to run `# pamusb-conf --add-device=MyDev`
Get the following output:
```
Traceback (most recent call last):
  File "/nix/store/kn70lc5x66p0i407xd4i9cg3nn4368f5-pam_usb-0.5.0/bin/.pamusb-conf-wrapped", line 252, in <module>
    '/org/freedesktop/UDisks')
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.UDisks': timed out

```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.10, NixOS, 18.03pre124015.f59a0f7f1a6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124015.f59a0f7f1a6"`
 - channels(balsoft): `"nixpkgs-18.03pre124015.f59a0f7f1a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

- My config (long & dirty): https://gist.github.com/balsoft/43b00a0de43ca602ef71ac71114bc642

### PR DESCRIPTION
**Pull request by RaitoBezarius**
## Description of changes

`security.pam.usb` is broken anyway and upstream has abandoned the software.
Fixes https://github.com/NixOS/nixpkgs/issues/33699.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by the-furry-hubofeverything** [comment]
There seem to be various forks, including this one https://github.com/mcdope/pam_usb

The maintainer seemed a bit busy however (https://github.com/mcdope/pam_usb/issues/208#issuecomment-1773513207), and the last commit was at Mar 21, so I guess it might not be worth it

**Comment by RaitoBezarius** [comment]
> There seem to be various forks, including this one [mcdope/pam_usb](https://github.com/mcdope/pam_usb)
> 
> The maintainer seemed a bit busy however ([mcdope/pam_usb#208 (comment)](https://github.com/mcdope/pam_usb/issues/208#issuecomment-1773513207)), and the last commit was at Mar 21, so I guess it might not be worth it

Not convinced how easy it is to port the current module to this, I will let anyone interested send a follow up PR after this drop.

**Comment by mcdope** [comment]
I think my fork is the most current one. However, it has several open issues and crappy code style in parts since I mainly do it for myself. Pretty certain there are multiple errors in memory handling too. 

That others also still use and enjoy it is more a sideeffect then intention :D But it works quite fine except in very exotic configurations. 

I would totally be up for helping with keeping it in. However, it would also be nice if somebody could find the time to help with the open issues. Also it should be made clear in the package description that this is kinda a experimental work-in-progress and MAY require hunting down issues together with me / maintainers.

My main problem is time: I got a 40h main job, a private business on the side, family, private projects like AmiFox (Chrome for Amiga computers) and then there is still the open source stuff :laughing:

**Comment by RaitoBezarius** [comment]
> I think my fork is the most current one. However, it has several open issues and crappy code style in parts since I mainly do it for myself. Pretty certain there are multiple errors in memory handling too.
> 
> That others also still use and enjoy it is more a sideeffect then intention :D But it works quite fine except in very exotic configurations.
> 
> I would totally be up for helping with keeping it in. However, it would also be nice if somebody could find the time to help with the open issues. Also it should be made clear in the package description that this is kinda a experimental work-in-progress and MAY require hunting down issues together with me / maintainers.
> 
> My main problem is time: I got a 40h main job, a private business on the side, family, private projects like AmiFox (Chrome for Amiga computers) and then there is still the open source stuff 😆

I think in that case, we should probably still drop it because it would still take you some time, if we get this re-introduced by a strongly motivated person, new things can happen (?).

**Comment by mcdope** [comment]
Whatever you prefer, just wanted to give my 2 cents :)

**Comment by RaitoBezarius** [comment]
> Whatever you prefer, just wanted to give my 2 cents :)

And thank you for chiming in, I appreciate it!

**Comment by mcdope** [comment]
Out of curiosity / maybe even for my issue tracker: what would you say needs to be done upstream (considering my fork as upstream) to keep this in / get it back in? Could you give me a summary or like that?

**Comment by RaitoBezarius** [comment]
> Out of curiosity / maybe even for my issue tracker: what would you say needs to be done upstream (considering my fork as upstream) to keep this in / get it back in? Could you give me a summary or like that?

The ideal would be a NixOS test, i.e. a QEMU VM test scenario with an emulation of the USB key and you or someone else taking the maintenance ship of this code, the module code and the package code in nixpkgs.

**Comment by mcdope** [comment]
> > Out of curiosity / maybe even for my issue tracker: what would you say needs to be done upstream (considering my fork as upstream) to keep this in / get it back in? Could you give me a summary or like that?
> 
> [...] i.e. a QEMU VM test scenario with an emulation of the USB key [...]

You mean like documented here -> https://nixos.wiki/wiki/NixOS_Testing_library I assume? That should easily be doable, since I already have test scripts incl. setting up a fake stick etc. 

I will add the qemu based test to my issues. 

However, I won't be able to take over maintenance of the package here myself. I'm sure if there is real interest for it some users will step up, like for Arch.

**Comment by RaitoBezarius** [comment]
> > > Out of curiosity / maybe even for my issue tracker: what would you say needs to be done upstream (considering my fork as upstream) to keep this in / get it back in? Could you give me a summary or like that?
> > 
> > 
> > [...] i.e. a QEMU VM test scenario with an emulation of the USB key [...]
> 
> You mean like documented here -> [nixos.wiki/wiki/NixOS_Testing_library](https://nixos.wiki/wiki/NixOS_Testing_library) I assume? That should easily be doable, since I already have test scripts incl. setting up a fake stick etc.

Correct, someone just have to send such a test in nixpkgs to revive this module.

> 
> I will add the qemu based test to my issues.
> 
> However, I won't be able to take over maintenance of the package here myself. I'm sure if there is real interest for it some users will step up, like for Arch.

Understandable, do you have people in mind or should I proceed with the drop for the upcoming release in the meantime?

**Comment by mcdope** [comment]
I would suggest to proceed with the drop for now. 

It will take me multiple weeks to provide that test, and I don't know any active pam_usb users using NixOS in my small collection of "ppl dedicated enough for XY". 

Let's be honest, pam_usb is filling a very small niche - could very well be nobody of the whole NixOS userbase is using it :D

**Comment by RaitoBezarius** [comment]
> I would suggest to proceed with the drop for now.
> 
> It will take me multiple weeks to provide that test, and I don't know any active pam_usb users using NixOS in my small collection of "ppl dedicated enough for XY".
> 
> Let's be honest, pam_usb is filling a very small niche - could very well be nobody of the whole NixOS userbase is using it :D

Gotcha, thank you for spending that much time clarifying things here, I really appreciate it!

**Pull request merged**
