### PR TITLE
llvm5: 5.0.1 -> 5.0.2

### PR DESCRIPTION
**Pull request by dtzWill**
Spectre-related fixes.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
@NixOS/darwin-maintainers okay to merge to staging for testing/rebuilds?

**Comment by LnL7** [comment]
Probably fine, but I'll start a build to check there are no obvious issues.

**Comment by matthewbauer** [comment]
Yeah this looks like a patch release and okay to merge quickly.

BTW Has anyone looked into moving to LLVM6.

**Comment by dtzWill** [comment]
Haha, you know I have! https://github.com/dtzWill/nixpkgs/tree/update/llvm-6-default (think created that shortly after LLVM6 was in-tree, so it's a bit old)

I forget if I found any problems, though.

It would save rebuilds to move to 6 directly instead of 5.0.2.  6.0.1 is due in a month or so, but usually point releases are easy: no breakage, just the rebuilds.

**Comment by dtzWill** [comment]
Rebased that branch onto staging here: https://github.com/dtzWill/nixpkgs/tree/update/llvm-6-default-rebased FWIW.

**Review by LnL7 — APPROVED** [review]

**Comment by vcunat** [comment]
Is there some description of what's changed?  Upstream has nothing on the web/announcement ML (yet?)

**Pull request merged**
