### PR TITLE
anup: fix build on darwin

### PR DESCRIPTION
**Pull request by r-burns**
###### Motivation for this change

ZHF 21.11 https://github.com/NixOS/nixpkgs/issues/144627

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 144685` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>anup</li>
  </ul>
</details>

**Comment by r-burns** [comment]
Hmm, care to post the log? It works on my machine (TM)

**Comment by siraben** [comment]
```
$ nix log /nix/store/5sphysf2vj5xc79cd64cdnsk0qb6sb0j-anup-0.4.0.drv | ix
http://ix.io/3E48
```

**Comment by r-burns** [comment]
Hmm, IDK then. I tried some rebuilds with `--check` and they are reliable for me.

**Comment by risicle** [comment]
@siraben do you have the sandbox enabled on this machine? This isn't the first rust package where you've received this mysterious SIGABRT that others can't replicate.

Builds and works for me, macos 10.15

**Comment by siraben** [comment]
@risicle I'm on macOS 12.0.1, perhaps that's causing the difference?

**Comment by r-burns** [comment]
Interesting, could be the reason. I'm also on 10.15 FWIW.

**Comment by risicle** [comment]
Yup, that sounds a likely culprit

**Review by thiagokokada — COMMENTED** [review]
Result of `nixpkgs-review pr 144685` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

No-op on `x86_64-linux`.

**Review by thiagokokada — APPROVED** [review]
Result of `nixpkgs-review pr 144685` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>anup</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Going to merge this since it works for at least some versions of macOS (before it didn't work in no one).

Patches to fix the build on macOS 12.0 can always be done in another PR.

Also, there is the https://discourse.nixos.org/t/nix-macos-monthly/12330 initiative, that once merged should also improve macOS situation (and maybe even fix this issue automatically?).

**Comment by thiagokokada** [comment]
> @risicle I'm on macOS 12.0.1, perhaps that's causing the difference?

BTW, probably also related: https://github.com/NixOS/nixpkgs/pull/126411

**Comment by flurie** [comment]
Just adding that this built successfully for me on macOS 12.0.1.

**Pull request merged**
