### PR TITLE
devpi-client: 2.7.0 -> 3.1.0rc1

### PR DESCRIPTION
**Pull request by makefu**
###### Motivation for this change

update devpi-client to the latest version.
With this commit i also bump the version of devpi-common from 3.0.1 -> 3.2.0rc1 and enable tests for the package.
Right now we cannot enable devpi-client tests because the devpi-server package is not yet packaged.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Apparently these `rc`s are quite stable and upstream is not going to release versions without `rc` soon.

**Comment by makefu** [comment]
@orivej i chose the rc because in the latest "stable" release the tests broke ...

**Comment by vcunat** [comment]
`meta` didn't evaluate this way; fixed in 623df97af5a.

**Comment by orivej** [comment]
@vcunat Thank you! I'm working on automating such basic sanity checks of the PRs that is lighter weight than `nox-review`.

**Comment by vcunat** [comment]
For a quick test I'm using
```
nix-env -f . -qaP --meta --json --drv-path --show-trace >/dev/null
```

It might be also nice to run something like
```
./maintainers/scripts/rebuild-amount.sh $(git merge-base HEAD master)
```

**Comment by makefu** [comment]
@vcunat how about having multiple build steps for all these things, like:
* sanity check (packages evaluate)
* meta check (meta evaluates)
* mass rebuild check (will build more than 100 packages)

When we see which test fails it would actually help the maintainers getting a quick overview about the state of the PR.

**Pull request merged**
