### PR TITLE
config.hardware.onlykey: update the udev rules for onlykey

### LINKED ISSUE #100513: Bad onlykey udev rule
The onlykey udev rule in `modules/hardware/onlykey.udev` is different from the one available on the onlykey documentation here
https://docs.crp.to/linux.html
The onlykey isn't recognized using the udev rules currently available on the nixpkgs tree.  

I don't know why the two rules are completely different... Maybe there are two different versions of the onlykey out there using different hardware?

Anyway, my workaround to get the onlykey working:
add the correct udev rule manually, by using the `services.udev.extraRules` option in your configuration.nix
https://nixos.org/manual/nixos/stable/options.html#opt-services.udev.extraRules

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

The udev rules were updated upstream without an explanation as you can see in [this comment][commit]. Assuming that they have changed the idVendor/idProduct, I've kept the old rules.

[commit]: trustcrypto/trustcrypto.github.io@0bcf928

fixes #100513

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @cawilliamson @yrashk

### CODE REVIEW

**Comment by toastal** [comment]
@kalbasit If my configuration contains `hardware.onlykey.enable = true` and it compiles, why would the udev rules not exist?

```console
$ rg "onlykey" /etc/nixos/configuration.nix                                                                      
67:  hardware.onlykey.enable = true;
280:    onlykey-cli
$ ls /etc/udev/rules.d/                                                                                          
00-path.rules                         77-mm-foxconn-port-types.rules            80-udisks2.rules
01-md-raid-creating.rules             77-mm-haier-port-types.rules              84-nm-drivers.rules
10-dm.rules                           77-mm-huawei-net-port-types.rules         85-nm-unmanaged.rules
11-dm-lvm.rules                       77-mm-longcheer-port-types.rules          85-regulatory.rules
13-dm-disk.rules                      77-mm-mtk-port-types.rules                85-tlp-rdw.rules
51-android.rules                      77-mm-nokia-port-types.rules              85-tlp.rules
60-steam-input.rules                  77-mm-pcmcia-device-blacklist.rules       90-alsa-restore.rules
60-steam-vr.rules                     77-mm-quectel-port-types.rules            90-libinput-fuzz-override.rules
63-md-raid-arrays.rules               77-mm-sierra.rules                        90-nm-thunderbolt.rules
64-md-raid-assembly.rules             77-mm-simtech-port-types.rules            90-pipewire-alsa.rules
69-bcache.rules                       77-mm-telit-port-types.rules              90-pulseaudio.rules
69-dm-lvm-metad.rules                 77-mm-tplink-port-types.rules             95-dm-notify.rules
69-md-clustered-confirm-device.rules  77-mm-ublox-port-types.rules              95-upower-csr.rules
77-mm-broadmobi-port-types.rules      77-mm-usb-device-blacklist.rules          95-upower-hidpp.rules
77-mm-cinterion-port-types.rules      77-mm-usb-serial-adapters-greylist.rules  95-upower-hid.rules
77-mm-dell-port-types.rules           77-mm-x22x-port-types.rules               95-upower-wup.rules
77-mm-dlink-port-types.rules          77-mm-zte-port-types.rules                98-ipv6-privacy-extensions.rules
77-mm-ericsson-mbm.rules              80-libinput-device-groups.rules           99-ipv6-privacy-extensions.rules
77-mm-fibocom-port-types.rules        80-mm-candidate.rules                     99-local.rules
$ rg "onlykey" /etc/udev/rules.d/ # empty
```

**Comment by kalbasit** [comment]
> @kalbasit If my configuration contains `hardware.onlykey.enable = true;` and it compiles, why would the udev rules not exist? (`lib.mkForce true` did not help either)
> 
> ```
> $ rg "onlykey" /etc/nixos/configuration.nix                                                                      
> 67:  hardware.onlykey.enable = true;
> 280:    onlykey-cli
> $ ls /etc/udev/rules.d/                                                                                          
> 00-path.rules                         77-mm-foxconn-port-types.rules            80-udisks2.rules
> 01-md-raid-creating.rules             77-mm-haier-port-types.rules              84-nm-drivers.rules
> 10-dm.rules                           77-mm-huawei-net-port-types.rules         85-nm-unmanaged.rules
> 11-dm-lvm.rules                       77-mm-longcheer-port-types.rules          85-regulatory.rules
> 13-dm-disk.rules                      77-mm-mtk-port-types.rules                85-tlp-rdw.rules
> 51-android.rules                      77-mm-nokia-port-types.rules              85-tlp.rules
> 60-steam-input.rules                  77-mm-pcmcia-device-blacklist.rules       90-alsa-restore.rules
> 60-steam-vr.rules                     77-mm-quectel-port-types.rules            90-libinput-fuzz-override.rules
> 63-md-raid-arrays.rules               77-mm-sierra.rules                        90-nm-thunderbolt.rules
> 64-md-raid-assembly.rules             77-mm-simtech-port-types.rules            90-pipewire-alsa.rules
> 69-bcache.rules                       77-mm-telit-port-types.rules              90-pulseaudio.rules
> 69-dm-lvm-metad.rules                 77-mm-tplink-port-types.rules             95-dm-notify.rules
> 69-md-clustered-confirm-device.rules  77-mm-ublox-port-types.rules              95-upower-csr.rules
> 77-mm-broadmobi-port-types.rules      77-mm-usb-device-blacklist.rules          95-upower-hidpp.rules
> 77-mm-cinterion-port-types.rules      77-mm-usb-serial-adapters-greylist.rules  95-upower-hid.rules
> 77-mm-dell-port-types.rules           77-mm-x22x-port-types.rules               95-upower-wup.rules
> 77-mm-dlink-port-types.rules          77-mm-zte-port-types.rules                98-ipv6-privacy-extensions.rules
> 77-mm-ericsson-mbm.rules              80-libinput-device-groups.rules           99-ipv6-privacy-extensions.rules
> 77-mm-fibocom-port-types.rules        80-mm-candidate.rules                     99-local.rules
> $ rg --ignore-case "OnlyKey" /etc/udev/rules.d/ #empty
> ```

Sorry for the delay in my reply. It works for me:

```
❯ grep 1d50 /etc/udev/rules.d/99-local.rules                                                                                            
ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", ENV{MTP_NO_PROBE}="1"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", MODE:="0666"
KERNEL=="ttyACM*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", MODE:="0666"
```

**Comment by kalbasit** [comment]
This works for me, I'll go ahead and merge it. It's broken without it anyways.

**Comment by toastal** [comment]
> This works for me, I'll go ahead and merge it. It's broken without it anyways.

I recently pulled and built from the main branch and this is now working for me. Thank you, @kalbasit!

**Pull request merged**
