### PR TITLE
zigbee2mqtt package & module

### PR DESCRIPTION
**Pull request by sweber83**
###### Motivation for this change
There was neither package nor module for zigbee2mqtt

###### Things done
Implemented nix package and NixOS module for https://www.zigbee2mqtt.io/

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sweber83** [comment]
I'm still looking forward to getting this merged.

**Comment by Lassulus** [comment]
cool,
new services are encouraged to have a test. I see that a full test would be somehow complicated for this. But maybe a simple curl/mqtt test to get the server version from the running daemon would be nice?

thanks for contributing though and sorry for the somewhat huge delay :)

**Comment by sweber83** [comment]
@Lassulus 
I'll look into writing a simple test
The problem is, i'm pretty sure zigbee2mqtt will not start if the zigbee usb device is not available.

**Comment by juaningan** [comment]
I'm interested in this, maybe I could help you @sweber83 ?

**Comment by sweber83** [comment]
@juaningan 
Thanks for reminding me about this pr.
Today I implemented a really simple test, which just tests if zigbee2mqtt fails with the correct error message.

I thought about writing a more thorough test, but did not find the time yet.
Qemu provides a way to set up an emulated serial device which connects to a character device on the host (usb-serial), this could be used to talk to zigbee2mqtt and emulate the missing zigbee usb device.
There is only a small bit of information regarding this capability of Qemu in the docs: https://www.qemu.org/docs/master/system/usb.html
But there is a small example to be found in the mail archive: https://www.redhat.com/archives/libvir-list/2013-January/msg00053.html

The largest hurdle to a thorough test is probably the part of implementing some kind of server, which connects to the character device and talks to zigbee2mqtt over the serial connection.
If you have an idea on to how implement such a thorough test, or just some pointers on improving my minimal test, any help is appreciated!

**Comment by mweinelt** [comment]
>  thought about writing a more thorough test, but did not find the time yet.
> Qemu provides a way to set up an emulated serial device which connects to a character device on the host (usb-serial), this could be used to talk to zigbee2mqtt and emulate the missing zigbee usb device.
> There is only a small bit of information regarding this capability of Qemu in the docs: https://www.qemu.org/docs/master/system/usb.html
> But there is a small example to be found in the mail archive: https://www.redhat.com/archives/libvir-list/2013-January/msg00053.html

Yikes. IMO such a complex test should not be a blocker for this pull request.

**Comment by sweber83** [comment]
@Lassulus 
I updated the PR today.
As you can see, I added a minimal test a few weeks back.
Since a more comprehensive test is pretty complicated to implement, I hope to get the PR merged as it is now.

**Pull request merged**
