### PR TITLE
budgiePlugins.budgie-media-player-applet: init at 1.0.0-unstable-2023-12-31

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

Sets `PYTHONPATH` in the wrapper for Python plugins and adds the `budgie-media-player-applet` plugin.

I am not sure if the way I'm exposing (the `passthru.requiredPythonModules` bit) and merging (the `lib.forEach plugins ...` bit) the Python dependencies is idiomatic enough, the rest of the code is taken from all the other `libpeas`-based apps but as far as I have seen no Python-based plugin is actually packaged for them yet.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FedericoSchonborn** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>budgie.budgie-desktop-with-plugins</li>
    <li>budgiePlugins.budgie-media-player-applet</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
Hmmm, I don't really involve in python ecosystem, it is unclear to me what might happen on *any python stuff* that runs on the desktop when setting `PYTHONPATH` in a desktop package (I feel like I might try `patchPythonScript` in the plugin packages if possible, but I really haven't checked how budgie python plugins work here) :thinking:

**Comment by FedericoSchonborn** [comment]
I was able to reduce it to just `pygobject3` in `PYTHONPATH`, if I do so in the applet itself it fails to import the library.

**Comment by bobby285271** [comment]
I now saw [how libpeas are done](https://github.com/BuddiesOfBudgie/budgie-desktop/blob/312ab1c49212ef84db2cf8b6f250f81ae743eca1/src/panel/plugin_manager.vala#L29) here. I wonder if we should patch libpeas here, previously we do these:

- https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/misc/nautilus-python/fix-paths.patch
- https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/cinnamon/nemo-extensions/nemo-python/python-path.patch

From what I saw in nautilus-python, it probably should be run before `pygobject_init`, but I did not test yet

https://github.com/GNOME/libpeas/blob/1.36/loaders/python/peas-plugin-loader-python.c#L252C3-L252C17

**Comment by FedericoSchonborn** [comment]
> I now saw [how libpeas are used](https://github.com/BuddiesOfBudgie/budgie-desktop/blob/312ab1c49212ef84db2cf8b6f250f81ae743eca1/src/panel/plugin_manager.vala#L29) here. I wonder if we should patch libpeas here, previously we do this:
> 
> [`master`/pkgs/desktops/gnome/misc/nautilus-python/fix-paths.patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/misc/nautilus-python/fix-paths.patch?rgh-link-date=2023-10-16T23%3A24%3A52Z)
> 
> From what I saw in nautilus-python, it probably should be run before `pygobject_init`, but I did not test yet
> 
> [GNOME/libpeas@`1.36`/loaders/python/peas-plugin-loader-python.c#L252C3-L252C17](https://github.com/GNOME/libpeas/blob/1.36/loaders/python/peas-plugin-loader-python.c?rgh-link-date=2023-10-16T23%3A24%3A52Z#L252C3-L252C17)

https://github.com/NixOS/nixpkgs/compare/master...FedericoSchonborn:nixpkgs:budgie-media-player-with-libpeas-fix-paths-patch

It works, I didn't test anything else apart from Pluma and Eye of MATE plugins though.

**Comment by FedericoSchonborn** [comment]
@bobby285271 @jtojnar 

Do I make a PR for the `libpeas` change? Should I base it on/wait for #247766?

**Comment by bobby285271** [comment]
Yeah the change should probably be applied to libpeas2 too (which is being packaged in https://github.com/NixOS/nixpkgs/pull/247766), still haven't got around to try the branch yet :upside_down_face:

**Comment by jtojnar** [comment]
> [master...FedericoSchonborn:nixpkgs:budgie-media-player-with-libpeas-fix-paths-patch](https://github.com/NixOS/nixpkgs/compare/master...FedericoSchonborn:nixpkgs:budgie-media-player-with-libpeas-fix-paths-patch)
> 
> It works, I didn't test anything else apart from Pluma and Eye of MATE plugins though.

That looks great at a glance. We definitely do not want to set `PYTHONPATH` in a wrapper in anything that can run other programs (which is basically anything).

The downside is that pygobject will be always pulled in, even when there are no Python plug-ins, like in GNOME Builder ≥ 45. But it is probably fine, when we are already pulling in libpython.

And it does not cover any other Python dependencies that the plug-ins might need. For that we will need to inject the directories to site directly in the plug-ins, similarly to how we do it in GNOME Shell extensions.

And we will probably need to do something similar with lgi to make it work with lua.

**Comment by FedericoSchonborn** [comment]
Almost forgot about this :grin:

@bobby285271

**Pull request merged**
