### PR TITLE
uclibc: Bump and clean

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

Well it does builds on `x86_64`, but nobody would use it there anyways.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dezgeg** [comment]
Um, will this now mean we will now start to expect a ton of per-package patches to fix compilation on uclibc? Why do we need both uclibc and musl anyway? And given that @edolstra previously explicitly requested an RFC for these sort of things (like the musl support athttps://github.com/NixOS/rfcs/pull/23) why is this now just going straight in?

**Comment by Ericson2314** [comment]
We *already* had it. It was just bitrotted, and so I cleaned it up because it was making other refactors harder, and I frankly I was tired at looking at the old code. If you are someone else want's to remove uclibc altogether, I have no problem with that.

> Um, will this now mean we will now start to expect a ton of per-package patches to fix compilation on uclibc?

What do you mean? Even if I did plan to actually support uclibc (not merely make it presentable for someone else to maintain or remove), the MUSL people (of which I am not one) have, in line with there promise, not dumped musl-only patches everywhere so I would hold myself to the same standard. Does the MUSL work not look that way to you?

**Comment by dezgeg** [comment]
If something has bitrotted to the point of not even building anymore, and nobody has noticed it, then the right thing is to remove it. Again, d0e25d815ce610c34581860abc1269408323ca1e almost 2 years ago dropped all of the mips builds because they had been already long broken then.

> What do you mean? Even if I did plan to actually support uclibc (not merely make it presentable for someone else to maintain or remove), the MUSL people (of which I am not one) have, in line with there promise, not dumped musl-only patches everywhere so I would hold myself to the same standard. Does the MUSL work not look that way to you?

As of current `master`, `git grep isMusl | wc -l` gives 104 hits. About 5 of those are the declarations / some common code. 31 of those lines directly match `.*patch.*` in various random packages. Most of the rest are lines like `++ stdenv.lib.optionals stdenv.hostPlatform.isMusl [` again in various random packages which sound like more patches as well. I don't expect most of those patches going away either due to dead upstreams and things like that. They really are a necessary evil to have the packages working at all on musl, and I expect similar patches to be needed with uclibc as well. So having another set of 100 patches in various packages needs quite strong justifications on why either of musl or glibc is not good enough but uclibc is really needed.

**Comment by Ericson2314** [comment]
> https://github.com/NixOS/nixpkgs/commit/d0e25d815ce610c34581860abc1269408323ca1e

That is great precedent. I especially wouldn't mind getting rid of xburstutils as importing nixpkgs from all-packages (which it does) is very bad.

>  I don't expect most of those patches going away either due to dead upstreams and things like that.

Actually through things like https://github.com/NixOS/nixpkgs/issues/37056 the hope is at least the patches could be unconditional.

And again, if you want to just remove uclibc, I have no problem with that. In fact, it's nice that since it was cleaned up before removal, if anyone wants (and can justify) adding it back, there's a good starting point to work from.

**Pull request merged**
