### PR TITLE
Dante improvements

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Continuation on https://www.theverge.com/2018/4/13/17233112/russia-telegram-ban-court-ruling

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @Shados

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]

**Comment by Shados** [comment]
@abbradar why remove `Restart = "always";`? In my experience using dante, it catches some corner cases with ephemeral failures, and systemd will still stop attempting restarts if too many occur in too short a timespan (5 in 10 seconds by default).

**Comment by peterhoeg** [comment]
Also, can we run with ```DynamicUser = true;``` and then avoid having it try to drop permissions on its own?

**Comment by abbradar** [comment]
@Shados Ah, so it really can abruptly stop? I should have asked before making the change -- can you give an example so that we put it into comments and someone won't try to change it again?


@peterhoeg Dante has some parts which run as privileged user, namely PAM authentication module.

**Comment by Shados** [comment]
@abbradar Sorry, I don't remember the specific issues I ran into, and I can't check my non-existent logs; because I'm using it as part of a micro-VPN service I run for a few mates, I have logging for it disabled unless I'm actively looking into some problem.

**Comment by abbradar** [comment]
@Shados Got that; I'll just make a generic comment then.

**Comment by abbradar** [comment]
@Shados Given that you have disabled logs for it `logoutput` by default would also create a problem, correct?

FWIW my instance doesn't log anything apart from "started up" and messages from PAM about successful authorizations.

**Comment by Shados** [comment]
@abbradar No, having `logoutput` on by default is fine, because (as you noted) dante won't log anything other than startup unless you explicitly define log levels for specific things in the configuration.

**Comment by abbradar** [comment]
Pushed an update to only restart on failure with a comment.

**Comment by abbradar** [comment]
Merging this in several days if no problems are found.

**Pull request merged**
