### PR TITLE
haskell.packages.ghc910 05/09 fixes of some packages

### PR DESCRIPTION
**Pull request by eldritch-cookie**
## Description of changes

this is me upstreaming the fixes i used on my flake, the changes are all in one commit but if neccessary i can split either per type of fix or per package.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by maralorn** [comment]
@eldritch-cookie Do you mind sharing which packages you primarily meant to fix this way?

tbh. maintaining all of these overrides is a bit of a hazzle because of the combination that:
1. the will quickly produce eval errors when new versions are released for any of the overriden packages and
2. when we have no hydra jobs for those overrides we won’t notice these eval errors.

The result would also be that you don’t provide much from this being upstream because when it breaks you and we will only notice once it reaches your deployment.

So I am not heavy set on a policy here, but I‘d generally say we shouldn’t accumulate brittle fixes for packages<->ghc combination for which we don’t have CI. Open for suggestions though.

**Comment by eldritch-cookie** [comment]
These fixes in specific are mainly hoogle dependencies + dependencies of my own latest project. I thought to contribute them as it could save someone some time.
I understand your concerns and yes unless we evaluate a subsection of the package set, eventually some fixes will become stale but i don't see how that is any worse than not accepting the fixes.
if that is not enough maybe we could build packages with alternative GHC versions only if the package has a maintainer on nixpkgs for that package.

**Comment by maralorn** [comment]
Yeah, makes sense.
So 1. we do actually build hoogle for all ghcs, so this is great. Can you maybe just enable the hoogle job like you enabled the hls job before?
2. sure let’s merge the rest as well, will probably not hurt anyone.

**Comment by eldritch-cookie** [comment]
> Can you maybe just enable the hoogle job like you enabled the hls job before? 

did i enable the hls job? my memory is pretty bad so i may have done that,but i do not remember how to do it

**Pull request merged**
