### PR TITLE
appimagekit: init at 20180727

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

@matthewbauer mentioned in https://github.com/matthewbauer/nix-bundle/blob/master/appimagetool.nix that he couldn't build it via nix, I thought I'd give it a try myself. Took quite some work, indeed.

###### Things done

- [X] It builds.
- But I have not tested that the runtime works outside of NixOS, it's likely to need some more patching.

But I feel it's better to contribute this now, as opposed to fermenting this patch in my local branch till I feel like continuing this.

### CODE REVIEW

**Comment by oxij** [comment]
@GrahamcOfBorg build appimagekit

**Comment by oxij** [comment]
OfBorg timeout on LLVM build, I did build it locally, so let's merge as is.

**Review by matthewbauer — APPROVED** [review]

**Comment by matthewbauer** [comment]
Thanks! I will definitely make use of this in nix-bundle.

**Comment by oxij** [comment]
@matthewbauer

TBH, after playing with nix-bundle (it's pretty awesome, thanks for making it) I think that it should be slurped into nixpkgs.

Like wouldn't it be awesome if one could just do `nix-build ./default.nix pkgsAppImage.emacs` (or whatever else) and distribute the result. With nix-bundle integrated into nixpkgs the answer to the general question of "What is the most simple way to turn my app into AppImage on any distro?" would be "Install nix, package your app for nixpkgs." That would work for cross-compilation too almost automagically, which is very hard to do with other tools I'm aware of. And it would also solve the problem of nix installer for non-NixOS not working on distros with different libcs (which was my motivation in making this; it's easy to forget that other things exist when using nix, but I was recently reminded that they do, and my first idea was to just install nix there, but it failed :( so I played with nix-bundle till I hacked something that worked good enough, the whole thing would've been much better if nix was distributed as a self-sufficient bundle).

**Comment by oxij** [comment]
> The main issue is how slow startup times are

I think it's good enough already. nix-bundle saved me a couple hours of the usual screwing around trying to properly compile things I need with all the options I want on an impure distro. I'd feel like I'm winning the cost/benefit thing even if it'd had taken a minute to start. (Unless I'd need to start it hundreds of times or something.)

But having an option of caching the unpacked bundle would be nice, I completely agree.

> We would have trouble putting the Nix installer in nix-bundle - the chroot will prevent it from working I think.

Assuming non-root pids can manipulate their own VFS namespace I'd expect we can just point /nix to the /nix in the parent's namespace.

> I think the more cross-platform alternative to nix-bundle for these use cases is just to link everything statically.

That would work for the nix use case, but I made this in the hope that I would eventually be able to make app binaries I could directly use on other distros. Like, I want to take my emacs together with config and packages to other people's machines sometimes to show them how awesome org-mode is.

"Here is the binary you can run in an Ubuntu VM, here's the .nix expression you can build if you don't want to run my binaries, take it, play with it" is much more convincing than "Here, let me show you how it works on my machine in my hands with piles of magic .el and scripts you're not gonna see."

> I actually provide a single executable Nix at https://matthewbauer.us/nix. I use it a lot in places where I don't have sudo. You can build it yourself with this pr: https://github.com/matthewbauer/nix-bundle/pull/35.

Yeah, I saw that. Wouldn't it be nice if nixos.org's nix would be like this too, right? (And screw the old UI :) )

**Pull request merged**
