### PR TITLE
sbcl: 2.2.9 -> 2.2.10

### PR DESCRIPTION
**Pull request by hraban**
Question: when do we prune older versions? Maybe some kind of time limit? The latest point release of every minor, and every point release of the latest minor?

###### Description of changes

Added SBCL 2.2.10

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by iblech** [comment]
When trying `nix-shell -I nixpkgs=https://github.com/hraban/nixpkgs/archive/sbcl-2.2.10.tar.gz -p sbcl`, I got the following error:

```
While evaluating the form starting at line 126, column 0
  of #P"/build/sbcl-2.2.10/contrib/sb-simd/../make-contrib.lisp":
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10010A0123}>:
  Couldn't execute "/bin/cat": No such file or directory

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10010A0123}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10050EA543}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10050EA543}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Couldn't execute ~S: ~A" {10050EA543}>)
3: (ERROR "Couldn't execute ~S: ~A" "/bin/cat" "No such file or directory")
4: (RUN-PROGRAM "/bin/cat" ("/build/sbcl-2.2.10/obj/from-self/contrib/sb-simd/module-setup.fasl" "/build
[...]
```

**Comment by hraban** [comment]
Interesting; same as borg. What arch are you? I assume Linux? On darwin x86-64 it seems to work without changes, both using your nix-shell invocation, or doing nix-build -A sbcl from my local checkout. I can run and use sbcl 2.2.10.

Since I also don't know what this means, I'll have to spin up a vm somewhere and investigate.

**Comment by hraban** [comment]
Apparently it's fixed in master: https://bugs.launchpad.net/sbcl/+bug/1995224

https://github.com/sbcl/sbcl/blob/master/contrib/make-contrib.lisp#L122

I'll add a patch entry for 2.2.10.

**Comment by hraban** [comment]
Apparently I don't understand how nix-prefetch-url works? Not sure what the hell is happening but it works now.

**Comment by hraban** [comment]
😭 I don't understand what the borg wants

**Comment by 7c6f434c** [comment]
@ofborg eval

**Comment by 7c6f434c** [comment]
I sort of understand, but it's not really related to this PR… let's see if it is fixed now

**Comment by 7c6f434c** [comment]
As of old versions, I remember leaving some in when things got broken, but if lispPackages build on Linux and mostly build on Darwin, I think we might clean out even all but the previous one (just out of caution as there are actually non-trivial changes requiring reaction so who knows).

**Comment by iblech** [comment]
Thanks! Indeed, I'm on Linux x86_64 and can confirm that sbcl builds now. There are warnings `patchelf: wrong ELF type` on which I cannot judge their importance. In any case, the `sbcl` binary starts up just fine.

**Comment by 7c6f434c** [comment]
@ofborg build lispPackages

**Comment by 7c6f434c** [comment]
Ah right, now I remember, we should keep some version that is compatible with StumpWM, I guess.

**Pull request merged**
