### PR TITLE
crystal: 0.35.1 -> 0.36.0

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Cc @NixOS/crystal-lang

**Review by davy-tw — APPROVED** [review]
LGTM

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110896` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>5 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>ameba: log was empty</li>
<li>crystal: log was empty</li>
<li>crystal2nix: log was empty</li>
<li>icr: log was empty</li>
<li>oq: log was empty</li>
  </ul>
</details>
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>(crystal_0_36): log was empty</li>
<li>lucky-cli: log was empty</li>
  </ul>
</details>

```
Semantic: instance var doesn't infer type to be nilable if using self.class in call in assign
Semantic: pointer allows using pointer with subclass
Semantic: primitives types pointer of int
Failures:
1) Crystal::Command::FormatCommand formats stdin (bug + show-backtrace)
Error running at_exit handler: Nil assertion failed
make: *** [Makefile:104: compiler_spec] Error 1
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110896` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>oq: log <a href="https://termbin.com/ucoa">https://termbin.com/ucoa</a></li>
  </ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>ameba: log <a href="https://termbin.com/bivnl">https://termbin.com/bivnl</a></li>
  </ul>
</details>
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>crystal (crystal_0_36)</li>
<li>crystal2nix</li>
<li>icr</li>
<li>lucky-cli</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

crystal:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern '{% if flag?(:gnu) %}"listen: "{% else %}"bind: "{% end %}' doesn't match anything in file 'spec/std/socket/tcp_server_spec.cr'
substituteStream(): WARNING: pattern '01 Jan 2020' doesn't match anything in file 'spec/std/http/cookie_spec.cr'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>

**Review by Br1ght0ne — APPROVED** [review]
LGTM

**Comment by fabianhjr** [comment]
Hi, this is a ping/bump to merge.

**Pull request merged**
