### PR TITLE
nixos/usbStorage: adapt upstream

### LINKED ISSUE #265013: `manage_start_stop` device attribute is now readonly
### Describe the bug
`hardware.usbStorage.manageStartStop` option, introduced in #185688 on new kernels (at least 6.5.9) results in errors logged in system log, such as:

```
Nov 02 13:46:53 khas (udev-worker)[2402350]: 0:0:0:0: /nix/store/8q4ca9415p9vglhgcjv7q5d1f88qvxri-udev-rules/99-local.rules:13 Failed to write ATTR{/sys/devices/pci0000:00/0000:00:08.1/0000:07:00.3/usb5/5-2/5-2:1.0/host0/target0:0:0/0:0:0:0/scsi_disk/0:0:0:0/manage_start_stop}, ignoring: Permission denied
```

This was introduced, in kernel, by https://github.com/torvalds/linux/commit/3cc2ffe5c16dc65dfac354bc5b5bc98d3b397567 which made the `manage_start_stop` attribute readonly and introduced two new ones instead: `manage_system_start_stop` and `manage_runtime_start_stop`. Not sure what would be the correct behavior now

### Steps To Reproduce
1. Use a recent kernel
2. Insert a usb storage device into system

### Expected behavior
No error message. Possibly one or both of the new attributes being set.

### Notify maintainers

CC: @bb2020 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231031.65fc4de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(ar): `"nixos"`
 - channels(root): `"agenix, bootspecsb, nixos"`
 - nixpkgs: `/nix/store/w457vs5vgbj0rhfrbq3bcb4ljcvpplj0-source`
```

### PR DESCRIPTION
**Pull request by bb2020**
## Description of changes
#265013

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bb2020** [comment]
Tested this today with an external drive.

```
~ grep -rn --include 'manage*start_stop' . /sys/devices/ 
/sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/host0/target0:0:0/0:0:0:0/scsi_disk/0:0:0:0/manage_system_start_stop:1:0
/sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/host0/target0:0:0/0:0:0:0/scsi_disk/0:0:0:0/manage_runtime_start_stop:1:0
/sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/host0/target0:0:0/0:0:0:0/scsi_disk/0:0:0:0/manage_start_stop:1:0
```

**Review by AndersonTorres — APPROVED** [review]

**Review by AndersonTorres — APPROVED** [review]

**Review by AndersonTorres — APPROVED** [review]

**Comment by bb2020** [comment]
Can we merge this?

**Comment by bb2020** [comment]
Can you merge this @AndersonTorres ?

**Comment by AndersonTorres** [comment]
No :(

**Comment by bb2020** [comment]
I set `manage_system_start_stop` to replicate the old behavior.
I presume el-cheapo USB devices won't be able to wake up after suspend if we set `manage_runtime_start_stop`.

It looks like they've made another change in https://github.com/torvalds/linux/commit/24eca2dce0f8d19db808c972b0281298d0bafe99.

**Pull request merged**
