### PR TITLE
nixos/availableKernelModules: add microsoft hid

### PR DESCRIPTION
**Pull request by sugar700**
This adds support for Microsoft USB keyboards at boot.

###### Motivation for this change

I'm using Microsoft Natural Ergonomic Keyboard 4000 (a wired USB keyboard) and without loading this module the kernel is unable to accept keyboard input during boot. `nixos-generate-config` doesn't load the right module (when seeing this keyboard it adds `usbhid` onto the module list), and from I can tell it's non-trivial to fix that.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by vikanezrimaya — APPROVED** [review]
Considering that we do seem to have these kinds of special cases on availableKernelModules already, I'd say this is not unreasonable.

LGTM.

**Comment by timokau** [comment]
I am not really sure what implications this has. @NeQuissimus as our "kernel guy", do you have an opinion on this PR?

**Comment by NeQuissimus** [comment]
Considering the Logitechs are in there already, we can probably add the MS one. But this should get out of control and eventually end up behind some switch :)

**Pull request merged**
