### PR TITLE
python.pkgs.pikepdf: 1.18.0 -> 2.2.0

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
pdfarranger works.
Where does the qpdf dependency come from ? It is not mentioned in the release notes.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105977` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>img2pdf (python38Packages.img2pdf)</li>
    <li>ocrmypdf</li>
    <li>pdfarranger</li>
    <li>python37Packages.img2pdf</li>
    <li>python37Packages.pikepdf</li>
    <li>python38Packages.pikepdf</li>
    <li>python39Packages.img2pdf</li>
    <li>python39Packages.pikepdf</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104377` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>directx-shader-compiler</li>
  </ul>
</details>


```
installing
mv: missing destination file operand after '/nix/store/f2hdrvqkfz5hcksc5xacs0y4r7nfd2zf-directx-shader-compiler-1.5.2010/lib/'
Try 'mv --help' for more information.
```

**Comment by doronbehar** [comment]
> pdfarranger works.
> Where does the qpdf dependency come from ? It is not mentioned in the release notes.

Somehow I got an error before that I can't reproduce anymore related to qpdf when I launched pdfarranger. I removed it now. Also the comment near the `sed` commands to pikepdf's `setup.py` now include a comment saying these should be removed when staging since wheel is updated in staging. Now when I think about it, perhaps I should push these updates to https://github.com/NixOS/nixpkgs/pull/105584 ?

**Comment by doronbehar** [comment]
Now I see that even pikepdf is updated there, properly without those `sed` commands. I'm updating pdfarranger there and closing this.

**Pull request closed without merging**
