### PR TITLE
crystal: fix darwin builds

### PR DESCRIPTION
**Pull request by manveru**
###### Motivation for this change

Darwin builds for Crystal are currently failing because of a test not passing anymore.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by disassembler — APPROVED** [review]

**Review by jonringer — APPROVED** [review]
diff LGTM

cc @SuperSandro2000  can you build `crystal_0_32` on darwin, may take a while

**Review by fabianhjr — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109137` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>17 packages failed to build and are new build failures:</summary>
  <ul>
<li>ameba: log was empty</li>
<li>crystal: log was empty</li>
<li>(crystal_0_35): log was empty</li>
<li>crystal2nix: log was empty</li>
<li>crystal_0_31: log <a href="https://termbin.com/d8y5">https://termbin.com/d8y5</a></li>
<li>crystal_0_32: log was empty</li>
<li>crystal_0_33: log was empty</li>
<li>crystal_0_34: log was empty</li>
<li>gitAndTools.thicket: log was empty</li>
<li>icr: log was empty</li>
<li>lucky-cli: log was empty</li>
<li>mint: log was empty</li>
<li>oq: log was empty</li>
<li>scry: log was empty</li>
<li>shards: log was empty</li>
<li>(shards_0_12): log was empty</li>
<li>shards_0_11: log was empty</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109137` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>17 packages failed to build and are new build failures:</summary>
  <ul>
<li>ameba: log was empty</li>
<li>crystal: log was empty</li>
<li>(crystal_0_35): log was empty</li>
<li>crystal2nix: log was empty</li>
<li>crystal_0_31: log <a href="https://termbin.com/sn0f7">https://termbin.com/sn0f7</a></li>
<li>crystal_0_32: log was empty</li>
<li>crystal_0_33: log was empty</li>
<li>crystal_0_34: log was empty</li>
<li>gitAndTools.thicket: log was empty</li>
<li>icr: log was empty</li>
<li>lucky-cli: log was empty</li>
<li>mint: log was empty</li>
<li>oq: log was empty</li>
<li>scry: log was empty</li>
<li>shards: log was empty</li>
<li>(shards_0_12): log was empty</li>
<li>shards_0_11: log was empty</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109137` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>17 packages failed to build and are new build failures:</summary>
  <ul>
<li>ameba: log was empty</li>
<li>crystal: log was empty</li>
<li>(crystal_0_35): log was empty</li>
<li>crystal2nix: log was empty</li>
<li>crystal_0_31: log <a href="https://termbin.com/hw3d">https://termbin.com/hw3d</a></li>
<li>crystal_0_32: log was empty</li>
<li>crystal_0_33: log was empty</li>
<li>crystal_0_34: log was empty</li>
<li>gitAndTools.thicket: log was empty</li>
<li>icr: log was empty</li>
<li>lucky-cli: log was empty</li>
<li>mint: log was empty</li>
<li>oq: log was empty</li>
<li>scry: log was empty</li>
<li>shards: log was empty</li>
<li>(shards_0_12): log was empty</li>
<li>shards_0_11: log was empty</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109137` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>16 packages failed to build and are new build failures:</summary>
  <ul>
<li>ameba: log was empty</li>
<li>crystal: log was empty</li>
<li>(crystal_0_35): log was empty</li>
<li>crystal2nix: log was empty</li>
<li>crystal_0_32: log <a href="https://termbin.com/yb6ay">https://termbin.com/yb6ay</a></li>
<li>crystal_0_33: log was empty</li>
<li>crystal_0_34: log was empty</li>
<li>icr: log was empty</li>
<li>lucky-cli: log was empty</li>
<li>mint: log was empty</li>
<li>oq: log was empty</li>
<li>scry: log <a href="https://termbin.com/9myu">https://termbin.com/9myu</a></li>
<li>shards: log was empty</li>
<li>(shards_0_12): log was empty</li>
<li>shards_0_11: log was empty</li>
<li>thicket: log was empty</li>
  </ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>crystal_0_31</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109137` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>icr: log <a href="https://termbin.com/0iz8">https://termbin.com/0iz8</a></li>
<li>mint: log <a href="https://termbin.com/i7qa">https://termbin.com/i7qa</a></li>
<li>oq: log <a href="https://termbin.com/2g0z">https://termbin.com/2g0z</a></li>
<li>scry: log <a href="https://termbin.com/byyi">https://termbin.com/byyi</a></li>
  </ul>
</details>
<details>
<summary>
11 packages built:
</summary>
<ul>
<li>ameba</li>
<li>crystal (crystal_0_35)</li>
<li>crystal2nix</li>
<li>crystal_0_31</li>
<li>crystal_0_32</li>
<li>crystal_0_33</li>
<li>crystal_0_34</li>
<li>lucky-cli</li>
<li>shards (shards_0_12)</li>
<li>shards_0_11</li>
<li>thicket</li>
</ul>
</details>

**Comment by manveru** [comment]
These packages need to be fixed independently. I don't think there's anything new about their failure...

**Comment by SuperSandro2000** [comment]
The following still does not build for darwin:

crystal_0_35: log was empty
crystal_0_32: log termbin.com/yb6ay
crystal_0_33: log was empty
crystal_0_34: log was empty

**Comment by siraben** [comment]
@manveru please fix the merge conflicts.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/131808

**Pull request closed without merging**
