### PR TITLE
nitrokey-app2: init at 2.1.2

### PR DESCRIPTION
**Pull request by mibmo**
## Description of changes

Adds nitrokey-app2, the newer nitrokey app that supports their new products.

## Things done

Adds 3 python3 packages; `pyqt5-stubs`, `qt-material` & `pynitrokey` that are used in the nitrokey-app2 package.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mibmo** [comment]
I'm currently stuck with a runtime error
```
Traceback (most recent call last):
  File "/nix/store/zw6rfm294xx3hmg9f7i4jm264ka6k4s0-nitrokey-app2-2.1.2/bin/.nitrokeyapp-wrapped", line 6, in <module>
    from nitrokeyapp.__main__ import main
  File "/nix/store/zw6rfm294xx3hmg9f7i4jm264ka6k4s0-nitrokey-app2-2.1.2/lib/python3.10/site-packages/nitrokeyapp/__main__.py", line 10, in <module>
    from nitrokeyapp.gui import GUI
  File "/nix/store/zw6rfm294xx3hmg9f7i4jm264ka6k4s0-nitrokey-app2-2.1.2/lib/python3.10/site-packages/nitrokeyapp/gui.py", line 19, in <module>
    from nitrokeyapp.about_dialog import AboutDialog
  File "/nix/store/zw6rfm294xx3hmg9f7i4jm264ka6k4s0-nitrokey-app2-2.1.2/lib/python3.10/site-packages/nitrokeyapp/about_dialog.py", line 7, in <module>
    from nitrokeyapp.ui.aboutdialog import Ui_AboutDialog
ModuleNotFoundError: No module named 'nitrokeyapp.ui.aboutdialog'
```

and to be honest I don't know even close to enough about Python to debug this. Help would be greatly appreciated. :)

**Comment by panicgh** [comment]
FYI #243049

**Comment by mibmo** [comment]
> I'm still waiting on any kind of action (that is, review or merge) on my PR but as I still use my Nitrokey 3 and intend to do so for the foreseeable future I'm still committed to keep the package (and PR as long as it takes) up to date.

Alright, well that's good to hear! :) I've added a suggestion but in general lgtm; from my perspective we can merge your PR.

> I'm not sure why you'd need pynitrokey to be packaged differently

I had it building using the packaged `pynitrokey` too so I've no idea why I was told to package it differently, but I suppose it's only a good thing if there's one less derivation to maintain. I don't think we have to go through the rigamarole of having both the application and package version.

**Comment by mibmo** [comment]
Closing in favour of #243049

**Pull request closed without merging**
