### PR TITLE
lib: introduce `forEach` = flip map

### PR DESCRIPTION
**Pull request by danbst**
lib: introduce `forEach` = flip map

The main purpose is to bring attention to `flip map`, which improves
code readablity. It is useful when ad-hoc anonymous function
grows two or more lines in `map` application:

```
    map (lcfg:
        let port = lcfg.port;
            portStr = if port != defaultPort then ":${toString port}" else "";
            scheme = if cfg.enableSSL then "https" else "http";
        in "${scheme}://cfg.hostName${portStr}"
    ) (getListen cfg);
```
Compare this to `foreach`-style:
```
    forEach (getListen cfg) (lcfg:
        let port = lcfg.port;
            portStr = if port != defaultPort then ":${toString port}" else "";
            scheme = if cfg.enableSSL then "https" else "http";
        in "${scheme}://cfg.hostName${portStr}"
    );
```
(the example was taken with modifications from apache-httpd module)

This is similar to Haskell's `for` (http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Traversable.html#v:for)

Extracted and simplified from a more radical approach in https://github.com/NixOS/nixpkgs/pull/57091.

### CODE REVIEW

**Comment by danbst** [comment]
I can add release doc if this is going to be merged.

**Comment by volth** [comment]
Going forward, the next step to improve Nix readability for functional programmers experienced in Haskell should be
```
    (getListen cfg) `foreach` (lcfg:
        let port = lcfg.port;
            portStr = if port != defaultPort then ":${toString port}" else "";
            scheme = if cfg.enableSSL then "https" else "http";
        in "${scheme}://cfg.hostName${portStr}"
    );
``` 

And for people with Scala background:
```
    (getListen cfg).foreach (lcfg:
        let port = lcfg.port;
            portStr = if port != defaultPort then ":${toString port}" else "";
            scheme = if cfg.enableSSL then "https" else "http";
        in "${scheme}://cfg.hostName${portStr}"
    );
```

**Comment by danbst** [comment]
@volth I agree with your sarcasm! But OTOH I'd want `flip map` instead of `map` here:

https://github.com/NixOS/nixpkgs/blob/f3282c8/nixos/modules/services/web-servers/nginx/default.nix#L656

We can try to amend documentation, to teach people about `flip map` idiom from start. But we still have lots of non-functional people around, who are not used to *reading* `flip`-ed code.

**Comment by Infinisil** [comment]
How about just naming this `for`?

**Comment by danbst** [comment]
@Infinisil I'd reserve `for` as a keyword for https://github.com/NixOS/nix/issues/2543

**Comment by aanderse** [comment]
@danbst & @volth consensus reached...?

**Comment by edolstra** [comment]
This should be `forEach` since we use camelCase naming for functions.

**Comment by danbst** [comment]
@aanderse @edolstra renamed.

Now `forEach` is called 10 times during
```
$ nix-instantiate ./nixos/ --arg configuration '{ boot.isContainer = true; }' -A system
```

**Comment by aanderse** [comment]
@edolstra from your comments I assume implicit approval at this point?

**Comment by danbst** [comment]
thanks @aanderse and @edolstra

**Pull request merged**
