### PR TITLE
nixos-option: don't break if `builtins.trace` is used in `<nixos-config>`

### LINKED ISSUE #67659: nixos-option fails if configuration has trace output
Repro script (run with `nix-shell -A success` or `-A fail`):
```nix
let
#pinning
  pkgs' = import <nixpkgs> {};
  pkgs = import (pkgs'.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "33b67761be99c21b151b9a3b8c5c8bd6398671a9";
    sha256 = "1i3yxywwivcj4ls7pyvy696m44g9xww7khx71vpm2igj4i9b7xq1";
    }) {};

#get command
  nixos-option = pkgs.substituteAll {
    name = "nixos-option.sh";
    isExecutable = true;
    src = <nixpkgs/nixos/modules/installer/tools/nixos-option.sh>;
    };

#repro
  configuration = fail: pkgs.writeText "configuration.nix" ''
    {pkgs, lib, ...}: let fail = ${if fail then "true" else "false"}; in {
      #the trace needs to come from somewhere that's not the examined attribute for some reason?
      imports = [ ({...}: if fail then (lib.traceVal {}) else {}) ]; 
      boot.loader.grub.devices = [ "nodev" ];
      fileSystems."/" = {};
      }
    '';
  test = fail: ''
    ${nixos-option} -I nixos-config=${configuration fail} boot.loader.grub.devices --verbose
    exit
    '';
in {
  fail = pkgs.mkShell {
    shellHook = test true;
    };
  success = pkgs.mkShell {
    shellHook = test false;
    };  
  }


```

The solution is probably to do something saner than merge all the output streams in `evalNix`?
The error seems to originate via the trace line getting substituted into the end of the header in `generateAccessors`, resulting in things like 
```bash
header='let
  nixos = import <nixpkgs/nixos> {};
  nixpkgs = import <nixpkgs> {};
in with nixpkgs.lib;

trace: { } let option = nixos.options."boot"."loader"."grub"."devices"; config = nixos.config."boot"."loader"."grub"."devices"; in
'
```

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

By default everything from `stderr` will be recorded in case of errors,
however this shouldn't break `nixos-option` if a simple trace call is
used that breaks the Nix expression returned by `nix-instantiate`.

Fixes #67659

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Infinisil** [comment]
Why is stderr redirected to stdout anyways?

**Comment by Ma27** [comment]
To provide a meaningful output if one of the evaluations fail (e.g. due to an evaluation error).

**Comment by Infinisil** [comment]
How about capturing stdout and stderr into separate variables instead of mixing them together? Something like https://stackoverflow.com/a/13806678/6605742

**Comment by deliciouslytyped** [comment]
Without having read any of the stuff here (which I admittedly should have) - it's probably not ergonomic to separate the streams for outputting to the user, because related lines should be located in their appropriate location.

So maybe display to the user should have merged output and the code should use separated streams for processing. This is starting to feel like "should not be written in bash" territory though?

**Comment by bjornfor** [comment]
FYI, this PR rewrites nixos-option from sh to C++: https://github.com/NixOS/nixpkgs/pull/68193.

**Comment by Ma27** [comment]
Yeah, seen it. But as this is a bigger change, I'm not sure if this will make it into the upcoming release and is this is mainly a bugfix, that should be good to go, right? :)

**Review by bjornfor — APPROVED** [review]

**Comment by Ma27** [comment]
@Infinisil any further objections? Otherwise I'd like to merge :)

**Comment by Infinisil** [comment]
Well I'm not a fan of this change because it just makes code uglier. I still think by separating stdout and stderr from the start this could be made a lot cleaner.

**Comment by deliciouslytyped** [comment]
Looks like it's handling special cases already, this "just" adds another one? *shrug*
Is it worth blocking a hotfix with "the whole thing needs a rewrite"? (or am I being too melodramatic?)

Effort should be transferred to the C++ issue for any significant work I think?

**Comment by lheckemann** [comment]
I'm in favour of cherry-picking this (as is, no major refactoring with changing stderr and such) to 19.09 so that the bug is fixed, but not putting it in master, given the wonderful rewrite that we should be able to merge soon :)

**Comment by Infinisil** [comment]
I guess. I'm just more fond of the notion of "leave code better than you saw it" than the opposite :)

**Comment by lheckemann** [comment]
Generally agree! But this is a case of "minimise effort for fixing almost-obsolete code" IMHO ;)

**Pull request closed without merging**
