### PR TITLE
cc-wrapper, clang-tools: move libcxx before cflags

### LINKED ISSUE #163052: Have IOSurface depend on Libsystem rathen than XPC
### Describe the bug
The IOSurface framework as defined by the apple-source-releases depends on XPC. This causes redefinition errors because other frameworks get these definitions from Libsystem. There was an attempt to fix it in PR #161561, but this causes [build problems due to Libsystem and libc++ being incompatible currently](https://github.com/NixOS/nixpkgs/pull/161561#issuecomment-1056063573), so it was reverted in PR #162681.

### Steps To Reproduce
The first problem:
1. Build something that depends on Libsystem and IOSurface, like `mac-notification-sys`.

The second problem:
1. Apply the patch having IOSurface depend on Libsystem rather than XPC.
2. Build something depending on IOSurface and libc++, like `xcbuild`.

### Expected behavior
The incompatibility between Libsystem and libc++ should be fixed so we can have IOSurface properly depend on Libsystem without causing problems.

### PR DESCRIPTION
**Pull request by tjni**
###### Description of changes

This fixes #163052, where the xcbuild build fails on Darwin after
libSystem is added as a dependency of IOSurface.

Even though cc-wrapper adds libc to NIX_CFLAGS_COMPILE using the
-idirafter flag, ensuring it comes after the C++ standard library,
and the clang-tools wrapper respects -idirafter when it parses
arguments, it appears that "-isystem libc" can make its way onto
NIX_CFLAGS_COMPILE too.

In honesty, I have not been able to figure out how NIX_CFLAGS_COMPILE
inherits "-isystem libSystem", or how it influences the xcbuild build
itself. However:

1. This change does appear to fix the xcbuild build.

2. If NIX_CFLAGS_COMPILE does have "-isystem libSystem" added to it
   somehow, it _should_ probably come after the C++ standard library.

###### Notes

1. I am not fully happy with my level of understanding of how this problem manifests, which also means I'm not certain that this is the right way to fix this issue. But I have reached a point where I can't do more without guidance. (For instance, the successful build of xcbuild took an hour and a half on my computer, because I changed cc-wrapper, and I can't learn by trial and error with that sort of build time.) I'd be happy to take advice though.

2. If this approach looks sound, I then both want to trigger more builds to check what effect this has (how?) and wary of doing so because it might use up a lot of build infrastructure. What should I do?

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
This looks safe to do if the C++ library used is libc++, as I notice in many of its headers that it can handle libc on the path, e.g, for `math.h`:

```
#include_next <math.h>

// redefines some macros from math.h as functions
```

I am not sure about other C++ standard libraries.

**Comment by tjni** [comment]
I'll need some time to set up an x86_64 Linux box to try to reproduce the build failure in libuv.

**Comment by tjni** [comment]
> I'll need some time to set up an x86_64 Linux box to try to reproduce the build failure in libuv.

I set one up and couldn't reproduce the libuv build (which is actually a test) failure. I triggered a couple new builds, and they went away, so it looks flaky. I think this is ready for review, unless the hanging Darwin tests could somehow be triggered to further verify this.

**Comment by tjni** [comment]
/cc @Mic92 @cmm 

This touches the clang wrapper as well, so please take a look if you've got some time. Thank you!

**Comment by tjni** [comment]
@Ericson2314 would you be able to either take a look or point me in a direction?

I'm currently looking for next steps, whether that is to revise the approach, do more testing, come back to this later (such as after the current release window), or something else. Thank you!

**Comment by Ericson2314** [comment]
This seems fine to me? The order dependence here is totally all accursed so I am not too wedded to the status quo.

**Comment by tjni** [comment]
Thank you for reviewing, @Ericson2314. @Luflosi @winterqt @midchildan do you want to take a look too?

I'd like to move this forward in some form to fix some longstanding compilation issues in some packages on OSX (such as cargo-watch and starship). If the approach seems worth a try, is the next step to rebase this onto staging? I'm committed to anything I can do to monitor and fix any breakages this might cause.

**Comment by winterqt** [comment]
> I am not fully happy with my level of understanding of how this problem manifests, which also means I'm not certain that this is the right way to fix this issue.

I'm in the same place, honestly. @toonn, could you take a look at this when you get a chance? :)

> If the approach seems worth a try, is the next step to rebase this onto staging?

Yes, please.

**Comment by tjni** [comment]
I am going to close this PR in favor of a new one that tracks `staging`. I tried to rebase it and it looks confused.

**Comment by tjni** [comment]
The replacement PR for this is #185569.

**Comment by winterqt** [comment]
For what it's worth @tjni, you can change the base branch for a PR without having to make a new one. Just so you know for the future :)

**Pull request closed without merging**
