### PR TITLE
[staging-20.09] perlPackages: bulk update

### PR DESCRIPTION
**Pull request by volth**
https://github.com/NixOS/nixpkgs/pull/97098 rebased to `staging-20.09`

### CODE REVIEW

**Comment by stigtsp** [comment]
LGTM

@NixOS/nixos-release-managers ok to merge into `staging-20.09`?

**Comment by jonringer** [comment]
my only concern is causing regressions in packages that have already been stabilized. One of the points of ZHF is to gradually stabilize the package set.

That being said, if you did want to fix any regressions that exist on the staging-20.09 branch, then I'm fine with merging this.

**Comment by stigtsp** [comment]
> my only concern is causing regressions in packages that have already been stabilized. One of the points of ZHF is to gradually stabilize the package set.
> 
> That being said, if you did want to fix any regressions that exist on the staging-20.09 branch, then I'm fine with merging this.

Sorry for the late response: This PR does fix issues with `Appperlbrew`, `AppSqitch`, `LaTeXML` introduced with perl-5.32.0, but is mainly version bumps and cleanups.

I'm happy to work on fixing any regressions that pop up if you're comfortable merging, or we can backports fixes for broken packages to 20.09 leaving out the version updates.

**Comment by worldofpeace** [comment]
@stigtsp @volth Please check hydra on nixpkgs/staging-20.09 for regressions.

**Pull request merged**
