### PR TITLE
dbeaver: 6.2.2 -> 6.2.3

### PR DESCRIPTION
**Pull request by jojosch**
###### Motivation for this change
https://dbeaver.io/2019/10/21/dbeaver-6-2-3/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
```
/nix/store/hlizapvmh2kp5d4h60qil1gpm0fcjr0n-dbeaver-ce-6.2.2	 1167844744
/nix/store/8rl1yhf2fw80vp5miizjx8grn1rvl5ya-dbeaver-ce-6.2.3	 1167811072
```
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by helinko** [comment]
Has the binary changed after this? I'm getting a has mismatch on nixos-unstable:

```
hash mismatch in fixed-output derivation '/nix/store/5fpygq6z6nlwn16icsdir50acbp2nx3d-dbeaver-ce-6.2.3-linux.gtk.x86_64.tar.gz':
  wanted: sha256:1v4sllzvaz4fj8s14ddzw11wczlghbdppv8fl5jg6xglg687sgaj
  got:    sha256:0kkfk7j5dqmwzal64qhk8m2qf6cw6xqgqx1s8v2kx0500lw9d39l
cannot build derivation '/nix/store/5yyzl2kb2s92c6b19ngphwkj3dfjm6b6-dbeaver-ce-6.2.3.drv': 1 dependencies couldn't be built

**Comment by jojosch** [comment]
hmm, the checksum has indeed changed. But only on the file hosted on https://dbeaver.io/files/6.2.3/ (the asset of the GitHub Release https://github.com/dbeaver/dbeaver/releases/tag/6.2.3 still matches the expected checksum).

```
~ nix-prefetch-url https://dbeaver.io/files/6.2.3/dbeaver-ce-6.2.3-linux.gtk.x86_64.tar.gz
[52.9 MiB DL]
path is '/nix/store/5fpygq6z6nlwn16icsdir50acbp2nx3d-dbeaver-ce-6.2.3-linux.gtk.x86_64.tar.gz'
0kkfk7j5dqmwzal64qhk8m2qf6cw6xqgqx1s8v2kx0500lw9d39l
~ nix-prefetch-url https://github.com/dbeaver/dbeaver/releases/download/6.2.3/dbeaver-ce-6.2.3-linux.gtk.x86_64.tar.gz
[52.9 MiB DL]
path is '/nix/store/rx6ibc9kai15mmmsv34djgrshgwpk518-dbeaver-ce-6.2.3-linux.gtk.x86_64.tar.gz'
1v4sllzvaz4fj8s14ddzw11wczlghbdppv8fl5jg6xglg687sgaj
```

When checking the expected checksum from https://dbeaver.io/files/6.2.3/checksum/ the "new" checksum seems to be the "correct" one ...
```
~ sha256sum *dbeaver*.tar.gz
348d963805a0803ec5463a74fc70379c19874545136262a8fabce256e4996e4e  dbeaver_io_dbeaver-ce-6.2.3-linux.gtk.x86_64.tar.gz
523d7d9079f475f364a10eed7bdb828f7ec643e0bf351234928e7cb53fa59aec  github_dbeaver-ce-6.2.3-linux.gtk.x86_64.tar.gz
~ cat dbeaver-ce-6.2.3-linux.gtk.x86_64.tar.gz.sha256
348d963805a0803ec5463a74fc70379c19874545136262a8fabce256e4996e4e
```

When comparing the contents of the two archives some of the bundled dependencies have been updated/changed.

**Comment by jonringer** [comment]
I would take the original release from github, if they really did need to patch something, then they should release another patch version.

**Comment by c0bw3b** [comment]
> When comparing the contents of the two archives some of the bundled dependencies have been updated/changed.

If their server got breached and someone was trying to spread a malicious piece of code embedded in legitimate software, it would look exactly like this. 😈

**Pull request merged**
