### PR TITLE
[gnome-46] fixup! glib: 2.78.4 → 2.80.0

### PR DESCRIPTION
**Pull request by bobby285271**
As an initial fixup.

From https://gitlab.gnome.org/Teams/Websites/release.gnome.org/-/issues/37#note_1965340:

> - GLib now includes libgirepository from gobject-introspection as a new library; the library has a new version so it can be installed in parallel with libgirepository from gobject-introspection until bindings like pygobject and gjs are ported to it
> - GLib generates its own introspection data, instead of deferring it to gobject-introspection. This change introduces a cyclic dependency between GLib and gobject-introspection that can be solved with a 2-phase build; for more information, see this topic on Discourse: https://discourse.gnome.org/t/dealing-with-glib-and-gobject-introspection-circular-dependency/18701
> - The introspection data is used to generate the API references for GLib using gi-docgen instead of gtk-doc, for faster build times, and publishing on docs.gtk.org: [GNOME/glib#3037 (closed)](https://gitlab.gnome.org/GNOME/glib/-/issues/3037)

Doing some early testing here...

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build glib
@ofborg build glib.passthru.tests
@ofborg build gtk3

**Comment by bobby285271** [comment]
@ofborg build pkgsCross.aarch64-multiplatform.glib
@ofborg build pkgsMusl.glib
@ofborg build pkgsStatic.glib

**Comment by bobby285271** [comment]
@ofborg build pkgsStatic.glib

**Comment by bobby285271** [comment]
@ofborg build glib.passthru.tests

**Comment by amaxine** [comment]
@bobby285271 I have no intention of doing another rebase after today until stable releases get tagged (and only if it's necessary, or as prep for merging). I'm happy to rebase your work here into the branch, or you can go ahead. I'm only probably going to push gstreamer later tonight, after I'm done rebuilding everything.

**Pull request closed without merging**
