### PR TITLE
flutter313/flutter316: Fix aarch64-darwin

### PR DESCRIPTION
**Pull request by dasJ**
## Description of changes

Should get rustdesk-flutter (#286129) closer to Darwin compatibility.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mkg20001 — APPROVED** [review]

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 286750` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 286750` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>flutter (flutter316 ,flutterPackages.stable ,flutterPackages.v3_16)</li>
    <li>flutter313 (flutterPackages.v3_13)</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 286750` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by siraben** [comment]
Nothing to be built?

```
> nix-review pr --post-result --no-shell 286750
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/286750/head:refs/nixpkgs-review/1
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 39 (delta 9), reused 16 (delta 8), pack-reused 15
Unpacking objects: 100% (39/39), 33.82 KiB | 1018.00 KiB/s, done.
From https://github.com/NixOS/nixpkgs
   a005075002c0..06de1cfb7824  master                -> refs/nixpkgs-review/0
 + a293fb72da29...e7a5feacab3a refs/pull/286750/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /Users/siraben/.cache/nixpkgs-review/pr-286750/nixpkgs 06de1cfb78243da0acd25c11c5153a56fc322cd3
Preparing worktree (detached HEAD 06de1cfb7824)
Updating files: 100% (39362/39362), done.
HEAD is now at 06de1cfb7824 Merge pull request #255185 from StarGate01/nrfconnect
$ git merge --no-commit --no-ff e7a5feacab3ae7f824513a5b55ba1990e005e882
Automatic merge went well; stopped before committing as requested
Nothing to be built.

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/286750

Posting result comment on https://github.com/NixOS/nixpkgs/pull/286750
$ git worktree remove -f /Users/siraben/.cache/nixpkgs-review/pr-286750/nixpkgs
```

**Comment by reckenrode** [comment]
aarch64-darwin needs to be added to `meta.platforms` in `flutter/flutter.nix`.

**Comment by reckenrode** [comment]
flutter-tools needs patching. It tries to run `/usr/bin/arch -arm64e xcrun`. Aside from being impure, nixpkgs does not build arm64e binaries, which results in the following error: `arch: posix_spawnp: xcrun: Bad CPU type in executable`.

The following patch adds an override to replace the impure `/usr/bin/arch` with the one from darwin.adv_cmds and changes `-arm64e` to `-arm64`. I’m not sure whether it’s necessary for `flutter-tools.nix`, but I did it there too just in case.

```patch
diff --git a/pkgs/development/compilers/flutter/artifacts/overrides/darwin.nix b/pkgs/development/compilers/flutter/artifacts/overrides/darwin.nix
new file mode 100644
index 000000000000..7899ec1bedb0
--- /dev/null
+++ b/pkgs/development/compilers/flutter/artifacts/overrides/darwin.nix
@@ -0,0 +1,17 @@
+{ darwin
+}:
+
+{ buildInputs ? [ ]
+, ...
+}:
+
+{
+  postPatch = ''
+    if [ "$pname" == "flutter-tools" ]; then
+      # Remove impure references to `arch` and use arm64 instead of arm64e.
+      substituteInPlace lib/src/ios/xcodeproj.dart \
+        --replace-fail /usr/bin/arch '${darwin.adv_cmds}/bin/arch' \
+        --replace-fail arm64e arm64
+    fi
+  '';
+}
diff --git a/pkgs/development/compilers/flutter/flutter-tools.nix b/pkgs/development/compilers/flutter/flutter-tools.nix
index 55fee5630c16..6f8d1b3c1a8f 100644
--- a/pkgs/development/compilers/flutter/flutter-tools.nix
+++ b/pkgs/development/compilers/flutter/flutter-tools.nix
@@ -1,4 +1,6 @@
-{ systemPlatform
+{ lib
+, stdenv
+, systemPlatform
 , buildDartApplication
 , git
 , which
@@ -7,6 +9,7 @@
 , flutterSrc
 , patches ? [ ]
 , pubspecLock
+, darwin
 }:
 
 buildDartApplication.override { inherit dart; } rec {
@@ -21,7 +24,15 @@ buildDartApplication.override { inherit dart; } rec {
   inherit patches;
   # The given patches are made for the entire SDK source tree.
   prePatch = ''pushd "$NIX_BUILD_TOP/source"'';
-  postPatch = ''popd'';
+  postPatch = ''
+    popd
+  ''
+  # Remove impure references to `arch` and use arm64 instead of arm64e.
+  + lib.optionalString stdenv.isDarwin ''
+    substituteInPlace lib/src/ios/xcodeproj.dart \
+      --replace-fail /usr/bin/arch '${darwin.adv_cmds}/bin/arch' \
+      --replace-fail arm64e arm64
+  '';
 
   # When the JIT snapshot is being built, the application needs to run.
   # It attempts to generate configuration files, and relies on a few external
```

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 286750` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>expidus.file-manager</li>
    <li>expidus.file-manager.debug</li>
    <li>expidus.file-manager.pubcache</li>
    <li>firmware-updater</li>
    <li>firmware-updater.debug</li>
    <li>firmware-updater.pubcache</li>
    <li>fluffychat</li>
    <li>fluffychat-web</li>
    <li>fluffychat-web.pubcache</li>
    <li>fluffychat.debug</li>
    <li>fluffychat.pubcache</li>
    <li>flutter (flutter316 ,flutterPackages.stable ,flutterPackages.v3_16)</li>
    <li>flutter313 (flutterPackages.v3_13)</li>
    <li>hover</li>
    <li>intiface-central</li>
    <li>intiface-central.debug</li>
    <li>intiface-central.pubcache</li>
    <li>localsend</li>
    <li>localsend.debug</li>
    <li>localsend.pubcache</li>
    <li>rustdesk-flutter</li>
    <li>rustdesk-flutter.debug</li>
    <li>rustdesk-flutter.pubcache</li>
    <li>yubioath-flutter</li>
    <li>yubioath-flutter.debug</li>
    <li>yubioath-flutter.pubcache</li>
  </ul>
</details>

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 286750` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>flutter (flutter316 ,flutterPackages.stable ,flutterPackages.v3_16)</li>
    <li>flutter313 (flutterPackages.v3_13)</li>
    <li>localsend</li>
  </ul>
</details>

**Review by 0x4A6F — APPROVED** [review]

**Pull request merged**
