### PR TITLE
Remove kvark from maintaining Mozilla packages

### PR DESCRIPTION
**Pull request by kvark**
I'm sorry for doing this - removing myself from maintaining the packages.
I'm no longer employed by Mozilla, which these packages are from. And I don't currently have a Nix system to test anything. So asking me to review these package updates isn't productive.

I'll be happy to also remove myself from the global maintainers list. I figured that once I start using Nix again, I'll probably want to maintain some packages again. So this PR keeps me in the list, unless you feel different.

cc @nbp @jimblandy

### CODE REVIEW

**Comment by Mindavi** [comment]
I'd say that it makes sense to remove yourself from the list for now. But either way is fine by me.

**Review by Mindavi — APPROVED** [review]

**Comment by Mindavi** [comment]
You're still a maintainer (in the list) for some packages, I guess

**Review by mweinelt — APPROVED** [review]
Thanks for your contributions, I've used moz-phab quite recently and was positively suprised that we have it!

Please also remove yourself from
> pkgs/development/python-modules/result/default.nix:43:21:

**Comment by kvark** [comment]
@mweinelt should be good now

**Pull request merged**
