### PR TITLE
vimPlugins: update, add nvim-lightline-lsp and lightline-lsp

### PR DESCRIPTION
**Pull request by ambroisie**
~~https://github.com/blackcauldron7/surround.nvim has been deleted, however a fork seems to have taken its place: https://github.com/ur4ltz/surround.nvim.~~

I hit a few issues with the `update.py` script, I hacked around on my local branch to resolve them, I can remove them or fix my hack-ish changes if wanted.

###### Motivation for this change

I wanted to try both plugins.

Traceback from the `./update.py --add <repo> call`:

```
Traceback (most recent call last):
  File "/home/ambroisie/git/other-projects/nixpkgs/pkgs/misc/vim-plugins/./update.py", line 93, in <module>
    main()
  File "/home/ambroisie/git/other-projects/nixpkgs/pkgs/misc/vim-plugins/./update.py", line 89, in main
    pluginupdate.update_plugins(editor, args)
  File "/home/ambroisie/git/other-projects/nixpkgs/maintainers/scripts/pluginupdate.py", line 664, in update_plugins
    plugin = fetch_plugin_from_pluginline(plugin_line)
  File "/home/ambroisie/git/other-projects/nixpkgs/maintainers/scripts/pluginupdate.py", line 458, in fetch_plugin_from_pluginline
    plugin, _ = prefetch_plugin(parse_plugin_line(plugin_line))
TypeError: parse_plugin_line() missing 1 required positional argument: 'line'
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ners** [comment]
The replacement of the surround-nvim plugin is already handled in #161371, without any changes to the Python. Please remove changes that are not relevant to the plugins you are adding, to avoid merge conflicts.

**Comment by ambroisie** [comment]
@ners I feel like the python changes are relevant, if only because one cannot use `./update.py --add <repo>` as *indicated in the documentation* as the way to add a plug-in.

Rebased to remove the `surround-nvim` changes. Should I remove the whole `vimPlugins: update` commit as a whole instead?

**Comment by ners** [comment]
> one cannot use `./update.py --add <repo>` as _indicated in the documentation_ as the way to add a plug-in.

Can you put an example of this in the motivation section of the PR?

**Comment by ambroisie** [comment]
> Can you put an example of this in the motivation section of the PR?

The errors encountered ?

**Comment by ambroisie** [comment]
@ners I added the traceback, and tested the plug-ins on NixOS x86_64

**Comment by ners** [comment]
LGTM

**Comment by teto** [comment]
thanks for fixing the script.

**Pull request merged**
