### PR TITLE
jsoncpp: update and drop old version

### PR DESCRIPTION
**Pull request by cpages**
In https://github.com/NixOS/nixpkgs/pull/16600 jsoncpp 1.6.5 was moved to jsoncpp_1_6_5 and 1.7.x was set as default, but no package was changed to keep using 1.6.5, so I guess it's safe to remove it.
@artuuge, @ttuegel any objections?

I also updated it to 1.8.0, all deps seem to build just fine.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ttuegel** [comment]
I have no objection to dropping jsoncpp-1.6.5, and as long as everything builds after the 1.7.0 -> 1.8.0 update, I have no objection there either.

**Comment by vbgl** [comment]
The updated `json_cpp` does not build on darwin. I had to add to the `preBuild` the following line to fix the build:

```
    export DYLD_LIBRARY_PATH="`pwd`/src/lib_json:$DYLD_LIBRARY_PATH"
```

**Comment by ttuegel** [comment]
@vbgl Do dependent packages build on Darwin with no additional changes?

**Comment by vbgl** [comment]
No, but I don’t think they ever did. `jsoncpp.meta.platforms` was restricted to `platforms.linux`.

**Comment by ttuegel** [comment]
OK, then I think this can be merged when Travis finishes!

**Comment by cpages** [comment]
Actually platforms was set to all before the 1.7 update. I picked a darwin specific hack from that version thinking it would be enough, but apparently it's not. I'll add that preBuild line before merging then.

**Comment by ttuegel** [comment]
I'm going to go ahead a merge this; the Travis failure is unrelated.

**Pull request merged**
