### PR TITLE
Bcc

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

documentation is installed wrong
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
@Mic92: Can you ask upstream to make a release, instead of nixpkgs having to contain bcc versions from "random" commits? I see they have some releases already, the latest is from february. So the concept of releases won't be unfamiliar to them :-)

**Comment by bjornfor** [comment]
Pushed to master (e2991cc70bc4c953570045ab29bde4734d7476ec, c58f6e62de1e3163489b4e2f29c6f2b0531ab47c).

**Comment by Mic92** [comment]
I would have used the release, but this package already started with a non-released version.
So I avoided to jump back in time. The version I updated too also had proper man pages, which was my main motivation.

**Comment by bjornfor** [comment]
@Mic92: Yes, your PR improved things, so I merged it :-)

But if you have time (and interest), please consider contacting upstream about creating a release. It's better for everyone when users "sync up" on released versions instead of being spread out on various more or less (un)stable snapshots of a development tree.

**Pull request closed without merging**
