### PR TITLE
fetchFromGitHub: also use git if deepClone or leaveDotGit is used

### LINKED ISSUE #107556: When specifying leaveDotGit within fetchFromGitHub, it fails with an error unless fetchSubmodules is also set.
**Describe the bug**
When attempting to `fetchFromGitHub` with the `leaveDotGit` option set, the fetcher within `/pkgs/build-support/fetchgithub/default.nix` will be [erroneously set to `fetchzip`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgithub/default.nix#L14) unless the option `fetchSubmodules` is also set.

**To Reproduce**
1. Run the following derivation (not picking on nix-script, it was just a handy, small example):
2. 
```
{ stdenv, haskellPackages, fetchFromGitHub }:

stdenv.mkDerivation {
  pname = "nix-script";
  version = "2020-03-23";

  src  = fetchFromGitHub {
    owner  = "bennofs";
    repo   = "nix-script";
    rev    = "7706b45429ff22c35bab575734feb2926bf8840b";
    sha256 = "0yiqljamcj9x8z801bwj7r30sskrwv4rm6sdf39j83jqql1fyq7y";
    leaveDotGit = true;
    # fetchSubmodules = true; # Uncomment for it to function
  };

  buildInputs  = [
    (haskellPackages.ghcWithPackages (hs: with hs; [ posix-escape ]))
  ];

  phases = [ "buildPhase" "installPhase" "fixupPhase" ];
  buildPhase = ''
    mkdir -p $out/bin
    ghc -O2 $src/nix-script.hs -o $out/bin/nix-script -odir . -hidir .
  '';
  installPhase = ''
    ln -s $out/bin/nix-script $out/bin/nix-scripti
  '';

  meta = with stdenv.lib; {
    description = "A shebang for running inside nix-shell";
    homepage    = "https://github.com/bennofs/nix-script";
    license     = licenses.bsd3;
    maintainers = with maintainers; [ bennofs rnhmjoj ];
    platforms   = haskellPackages.ghc.meta.platforms;
  };
}
```

**Expected behavior**
`leaveDotGit` should force `fetchgit` to be used as well.

**Notify maintainers**
@matthewbauer 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 20.09.2161.214e71a78a9 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2161.214e71a78a9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

leaveDotGit is only inherited if it is explicitly set, so fetchgit's default value leaveDotGit ? deepClone is respected. An alternative would be to set the default value in fetchFromGitHub as well, but we'd have to change the default value in both places if it ever was to change.

Fix #107556.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
I'm aware using fetchgit with deepClone or leaveDotGit is generally discouraged and I have a vague idea why (issues with reproducibility aigainst a changing upstream, right?), but I'm not 100% sure, so if someone could point me in the right direction I'd also add a note about that in the manual.

**Comment by Profpatsch** [comment]
@sternenseemann I feel like you need to ping some people in order for this to get merged.

**Comment by OmnipotentEntity** [comment]
Relevant bug report: #107556

**Review by Ekleog — APPROVED** [review]
LGTM! Not merging straight away as IMO this will need some more opinions, but I do believe it'd help.

**Comment by Ekleog** [comment]
Well, it's been two months since this PR was landed, and IRC was pinged a few times about it, so I'm going to assume that people who may have wanted to review this PR would at least have made a comment here to say “don't merge until I review” and merge :)

Thank you for the work put in there!

**Pull request merged**
