### PR TITLE
flutter: Remove Flutter 2

### PR DESCRIPTION
**Pull request by hacker1024**
###### Description of changes

No packages in Nixpkgs use Flutter 2 anymore. Maintaining such an old version of Flutter is difficult:

- It requires a unique patchset, as the files that need patching have changed significantly in recent versions
- The engine artifact set will not change, making it difficult to update artifact derivations for newer engines
- Testing must be performed for each Flutter version when changes to the Flutter derivations and build-support functions are made

On the flipside, there are not many Flutter API changes between version 2 and version 3. Most old apps should be able to be built with little modification.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by JulienMalka — APPROVED** [review]

**Comment by hacker1024** [comment]
Rebased on master.

**Review by algorithmiker — APPROVED** [review]

**Comment by hacker1024** [comment]
> someone should do a nixpkgs-review just to be sure, and then takeoff.

```
2 packages removed:
flutter (†2.10.5-unwrapped) flutter-wrapped-sdk-links (†)

Nothing to be built.
```

**Review by SuperSandro2000 — COMMENTED** [review]
we should add an entry to aliases.nix

**Comment by SuperSandro2000** [comment]
Aliases can also just be a throw telling people that the package was removed and that they need to migrate. It is always better than that the variable was not found. https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/aliases.nix

**Comment by Janik-Haag** [comment]
@hacker1024 can you add an alias that throws a error like Sandro suggested and rebase so we can merge this?

**Review by Janik-Haag — APPROVED** [review]

**Pull request merged**
