### PR TITLE
bitcoin: 0.21.0 -> 0.21.1

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- version update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jb55** [comment]
ACK a4cd25533dd14d63f0a486352c6f2c0b0fbfac37. hash gpg-verified.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121432` at a4cd2553 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>bitcoind</li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>bitcoin</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

util-linux is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/blockchains/bitcoin.nix:48:3:
```
   |
48 |   buildInputs = [ boost zlib zeromq miniupnpc libevent ]
   |   ^
```
</li>
  </ul>
</details>

**Comment by roconnor** [comment]
I have verified that the hash `caff23449220cf45753f312cefede53a9eac64000bb300797916526236b6a1e0` is signed by the known `Bitcoin Core binary release signing key` in https://bitcoincore.org/bin/bitcoin-core-0.21.1/SHA256SUMS.asc.

**Comment by jb55** [comment]
Tested-ACK. no issues building or running

**Pull request merged**
