### PR TITLE
python.pkgs.django cleanup

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Cleaning up old versions. Part of https://github.com/NixOS/nixpkgs/issues/25375.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
cc @lsix

**Comment by lsix** [comment]
Hi @FRidh 
deps
I did not go all the way through yet due to all the broken derivations. I think your approach of only using the same `django` everywhere to build everything is way cleaner, even if some derivations end up broken (because they expect a earlier version). Anyone who needs it should override the python packages set anyway.

I am currently running `nox-reivew` to see if some derivations should be marked as broken then it will be good for me.

**Comment by FRidh** [comment]
@lsix ideally those derivations that rely on Django should specify which Django version they need, either as a comment or in code. We could introduce a `djangoOlder` like we have with `pythonOlder` so that dependents could write e.g. `disabled = djangoOlder "1.10";`.

**Comment by lsix** [comment]
Introducing works:

```diff
diff --git a/pkgs/top-level/python-packages.nix b/pkgs/top-level/python-packages.nix
index d2fa2c38ca3..4aa1988e3a9 100644
--- a/pkgs/top-level/python-packages.nix
+++ b/pkgs/top-level/python-packages.nix
@@ -29,6 +29,9 @@ let
   isPyPy = python.executable == "pypy";
   isPy3k = strings.substring 0 1 python.pythonVersion == "3";
 
+  djangoOlder = versionOlder self.django.version;
+  djangoAtLeast = versionAtLeast self.django.version;
+
   callPackage = pkgs.newScope self;
 
   bootstrapped-pip = callPackage ../development/python-modules/bootstrapped-pip { };
@@ -68,7 +71,7 @@ let
 
 in {
 
-  inherit python bootstrapped-pip pythonAtLeast pythonOlder isPy26 isPy27 isPy33 isPy34 isPy35 isPy36 isPyPy isPy3k mkPythonDerivation buildPythonPackage buildPythonApplication;
+  inherit python bootstrapped-pip pythonAtLeast pythonOlder isPy26 isPy27 isPy33 isPy34 isPy35 isPy36 isPyPy isPy3k mkPythonDerivation buildPythonPackage buildPythonApplication djangoOlder djangoAtLeast;
   inherit fetchPypi callPackage;
   inherit sharedLibraryExtension;

```

but I am not sure this should make up to the entire `pythonPackage` set (most of the set do not care much about django).

Having

```nix
{buildPythonPackage,
 …
 , django, versionAtLeast
 …
}:
buildPythonPackage rec {
  …
  # disable for django-1.10 and later
  disabled = versionAtLeast django.version "1.10";
  …
}
```

could be just fine and readable (the error message presented to the interpreter should show it, the `disabled` uses assumes the cause is the version of the interpreter). I’ll try to go through it this noon or evening.

**Comment by lsix** [comment]
@FRidh  https://github.com/lsix/nixpkgs/commit/f6624782b7654aad0a618324a14abe3565428166 properly marks the broken derivations. If you are ok with it, you could cherry-pick it.

With it, I can run `nox-review wip --against 14413421824a4176bc8a2b29063104796eb0a638` properly.

**Comment by FRidh** [comment]
Instead of a `disabledReason` you could just throw in the expressions.

**Comment by lsix** [comment]
Here is an updated version: https://github.com/lsix/nixpkgs/commit/1f520bc1c5779bd42dbdb44318bb5946d53835ff

**Pull request merged**
