### PR TITLE
Herbstluftwm: 0.8.1 -> 0.8.2 + add test

### PR DESCRIPTION
**Pull request by ThibautMarty**
###### Motivation for this change

- update to last version
- change maintainership because previous maintainer did not respond for a long time and several mentions.
- add a simple NixOS test (based on i3wm.nix)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
@GrahamcOfBorg build herbstluftwm.passthru.tests

**Comment by Lassulus** [comment]
please rebase, the maintainers entry was already removed

**Comment by ThibautMarty** [comment]
done

**Comment by Lassulus** [comment]
running the test gives me this:
```
ensure we can open a new terminal
machine: sending monitor command: sendkey alt-ret
machine # [   65.547303] nscd[824]: 824 checking for monitored file `/etc/netgroup': No such file or directory
machine: Waiting for a window to appear
machine: must succeed: xwininfo -root -tree | sed 's/.*0x[0-9a-f]* \"\([^\"]*\)\".*/\1/; t; d'
(0.15 seconds)
machine: must succeed: xwininfo -root -tree | sed 's/.*0x[0-9a-f]* \"\([^\"]*\)\".*/\1/; t; d'
(0.11 seconds)
machine: must succeed: xwininfo -root -tree | sed 's/.*0x[0-9a-f]* \"\([^\"]*\)\".*/\1/; t; d'
(0.16 seconds)
machine: must succeed: xwininfo -root -tree | sed 's/.*0x[0-9a-f]* \"\([^\"]*\)\".*/\1/; t; d'
(0.13 seconds)
machine: must succeed: xwininfo -root -tree | sed 's/.*0x[0-9a-f]* \"\([^\"]*\)\".*/\1/; t; d'
(0.10 seconds)
machine # [   71.112872] xsession[1072]: /nix/store/by1dhhi4jrk3iva3rgrf007254m1lfbp-herbstluftwm-0.8.2/etc/xdg/herbstluftwm/autostart: line 168: /etc/xdg/herbstluftwm/panel.sh: No such file or directory
machine: must succeed: xwininfo -root -tree | sed 's/.*0x[0-9a-f]* \"\([^\"]*\)\".*/\1/; t; d'
(0.06 seconds)
```

**Comment by ThibautMarty** [comment]
The `panel.sh` script path is hardcoded in the provided `autostart` script.
For me, this is not a big deal as I suppose that anyone using such window manager will make her own configuration.
This should be fixed upstream, but I can make a patch for it, like:
```
patchPhase = ''
  substituteInPlace share/autostart --replace /etc $out/etc
'';
```
But even with this patch, the script will fail with this message: `This script requires the textwidth tool of the dzen2 project.` and I don't want to include such false dependencies in the package's closure.
They could be added to the test though:
```
environment.systemPackages = [ pkgs.dzen2 ];
```

Is this what you noticed or did I miss something else?

([I found a comment](https://github.com/herbstluftwm/herbstluftwm/commit/8c78994ae73c3371cb9598bced8735c8a1ebf14e) `#For guix` while digging the provided script, and that made me happy.)

**Review by bhipple — CHANGES_REQUESTED** [review]
Needs rebase

**Pull request closed without merging**
