### PR TITLE
matrix-synapse: 1.2.1 -> 1.3.0

### PR DESCRIPTION
**Pull request by mguentner**
###### Motivation for this change

https://github.com/matrix-org/synapse/releases/tag/v1.3.0

Performance improvements mostly. Added sd_notify due to https://github.com/matrix-org/synapse/issues/5732

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @pacien @Ekleog

### CODE REVIEW

**Comment by mguentner** [comment]
# Off-Topic

I created a channel for the coordination / discussion of the matrix subsystem.
Feel free to join! #matrix-nix:transformierende-gesellschaft.org :spider_web:

**Comment by peterhoeg** [comment]
How about changing the nixos module as well to make use of this?

**Comment by pacien** [comment]
@ofborg build nixosTests.matrix-synapse

**Review by pacien — APPROVED** [review]

**Comment by mguentner** [comment]
@peterhoeg 

You mean `Type=notify` in the systemd unit? Is there anything more to do?
I will be able to do in the next days!

**Comment by peterhoeg** [comment]
>   You mean Type=notify in the systemd unit?

Yep.

>   Is there anything more to do?

Don't think so.

**Comment by mguentner** [comment]
I changed the module as well.
Please keep in mind that `config.package` now needs to have `sd-notify` support.

**Comment by bachp** [comment]
Seems like [v1.3.1](https://github.com/matrix-org/synapse/releases/tag/v1.3.1) dropped the the sdnotify dependency again. Seems like they [implemented the functionality manually](https://github.com/matrix-org/synapse/pull/5871).

**Comment by mguentner** [comment]
I will update the branch asap.

**Comment by mguentner** [comment]
replaced by #66814

**Pull request closed without merging**
