### PR TITLE
vimPluginsUpdater: add missing nix-prefetch-git dependency

### PR DESCRIPTION
**Pull request by teto**
## Description of changes

Some fixes for new vimPluginsUpdater, noticed by @GaetanLepage in https://github.com/NixOS/nixpkgs/pull/259005 ty

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by figsoda — APPROVED** [review]

**Comment by GaetanLepage** [comment]
Oopsie
```
path is '/nix/store/zpwy83am2h86574zynp1fp9mz6cqs3nr-2b786703eef9f82ae7a56f3de4ee43e1e5efaaa5.tar.gz'
path is '/nix/store/23njg50yl12bwy26b57q0b9686pmj60q-95c5b25066efb34c75bce78698baa371fe0ee7c2.tar.gz'
path is '/nix/store/23njg50yl12bwy26b57q0b9686pmj60q-95c5b25066efb34c75bce78698baa371fe0ee7c2.tar.gz'
path is '/nix/store/r9rxy0z75s7w8f66w2315h7v3q96r4lm-f7b71f31d2ffa91715964b14b41ad4009d4d97f6.tar.gz'
path is '/nix/store/r9rxy0z75s7w8f66w2315h7v3q96r4lm-f7b71f31d2ffa91715964b14b41ad4009d4d97f6.tar.gz'
path is '/nix/store/wxgdaxq7x15rqkr4gz81g9k06hbmcqzi-b0c31bd73a6d1026765e659bd0a62c625ec057ad.tar.gz'
path is '/nix/store/wxgdaxq7x15rqkr4gz81g9k06hbmcqzi-b0c31bd73a6d1026765e659bd0a62c625ec057ad.tar.gz'
path is '/nix/store/9gcnfrxl44gjvdfsrjkgd3q1qln5rzmd-7fd86b7164442d3b5ec2c81b2694d040e716b5cf.tar.gz'
path is '/nix/store/9gcnfrxl44gjvdfsrjkgd3q1qln5rzmd-7fd86b7164442d3b5ec2c81b2694d040e716b5cf.tar.gz'
committing to nixpkgs "vimPlugins: update"
1344 plugins were checked
updated pkgs/applications/editors/vim/plugins/generated.nix
no changes in working tree to commit
updating nvim-treesitter grammars
Traceback (most recent call last):
  File "/nix/store/59hks209ql7adgw2hx6p2czr36nbyqiy-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 163, in <module>
    main()
  File "/nix/store/59hks209ql7adgw2hx6p2czr36nbyqiy-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 159, in main
    editor.run()
  File "/nix/store/59hks209ql7adgw2hx6p2czr36nbyqiy-vim-plugins-updater-0.1/lib/pluginupdate.py", line 560, in run
    getattr(self, command)(args)
  File "/nix/store/59hks209ql7adgw2hx6p2czr36nbyqiy-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 134, in update
    lockfile = os.path.join(args.nixpkgs.join(NIXPKGS_NVIMTREESITTER_FOLDER, "lockfile.json"))
TypeError: str.join() takes exactly one argument (2 given)
```

**Comment by teto** [comment]
sry forgot to put this as draft :'(

**Comment by GaetanLepage** [comment]
> sry forgot to put this as draft :'(

Would you know how it can be fixed ?
I am afraid that being unable to update the vim plugins is a bit annoying.
Can I help with that somehow ?

**Comment by teto** [comment]
I was planning to update the doc as requested https://github.com/NixOS/nixpkgs/issues/260227 but if you wanna coordinate with @jlesquembre to do it that could help, I will try to fix the updater within the next 24 hours in https://github.com/NixOS/nixpkgs/pull/260927

**Pull request merged**
