### PR TITLE
Update oraclejdk8 package to use patch 40 (latest)

### PR DESCRIPTION
**Pull request by mbbx6spp**

### CODE REVIEW

**Comment by lethalman** [comment]
The hashes were wrong before?

**Comment by mbbx6spp** [comment]
Sorry I should have explained. Yes that is correct, the current master oraclejdk8 Nix package is not using SHA256 hashes (you can check this by looking at the length of the SHA presently on master). This PR does. I have verified the change works locally on x86_64 linux. HTH. 

Current master SHA for x86_64:

```
$ echo "0nfm4xqd57s8dmkgd0jsrhys8dhfw0fx5d57mq70ramq9dl2jq66" | wc -c
      53
```

This PR's SHA for x86_64:

```
$ echo "c66029684bb8aa0c0eaea7b4d21de00e36a43dcc5a82f6666d489fd27027d559" | wc -c
      65
```

Thanks for checking.

**Comment by peti** [comment]
The old hashed were simply encoded in another system. Base-16 or base-32 or whatever; I can never remember which is which. It seems your PR just translates these hashes to hex.

**Comment by cocreature** [comment]
I haven't tested the x86 version but at least for the x64 one I needed to change the hashes when I tried it out a minute ago (I used the hash nix-prefetch-url gave me which is a short one so I'm not sure if this pr works).

**Comment by joachifm** [comment]
@peti is correct,

```
$ nix-hash --type sha256 --to-base16 0nfm4xqd57s8dmkgd0js
c66029684bb8aa0c0eaea7b4d21de00e36a43dcc5a82f6666d489fd27027d559
```

If the hashes are wrong, then this PR will not fix them.

**Comment by joachifm** [comment]
@peti is correct, you can use `nix-hash` to convert between base16 and base32 to confirm. If the hashes were wrong, this PR will not fix them.

**Comment by pSub** [comment]
Confirmed

```
% nix-hash --to-base32 a0f035c234eea71656ee989b8a569c901f7912ec969f1147771364b5aa5dcaad --type sha256                                            
1bfabnmbar0kfx3i37wnxh97j7whkib8m6wqxrb1d9zf6k13bw50

% nix-hash --to-base32 c66029684bb8aa0c0eaea7b4d21de00e36a43dcc5a82f6666d489fd27027d559 --type sha256                                            
0nfm4xqd57s8dmkgd0jsrhys8dhfw0fx5d57mq70ramq9dl2jq66
```

**Comment by mbbx6spp** [comment]
Thanks for clarifying and showing how to validate. I found the source of my confusion. I had been broken on the previous commit to the one on master now and didn't realize it had already been fixed so when I tested my change I thought I should submit. Cheers! :)

**Pull request closed without merging**
