### PR TITLE
python311Packages.resolvelib: 0.5.5 -> 1.0.1

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

Diff: https://github.com/sarugaku/resolvelib/compare/0.5.5...1.0.1

Changelog: https://github.com/sarugaku/resolvelib/blob/1.0.1/CHANGELOG.rst

The [concern](https://github.com/NixOS/nixpkgs/pull/133064) about resolvelib in ansible has already been resolved.
https://github.com/ansible/ansible/pull/80196

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 253239` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>48 packages built:</summary>
  <ul>
    <li>ansible (python310Packages.ansible-core)</li>
    <li>ansible-later</li>
    <li>ansible-later.dist</li>
    <li>ansible-lint</li>
    <li>ansible-lint.dist</li>
    <li>ansible.dist (python310Packages.ansible-core.dist)</li>
    <li>ansible_2_13</li>
    <li>ansible_2_13.dist</li>
    <li>ansible_2_14</li>
    <li>ansible_2_14.dist</li>
    <li>kargo</li>
    <li>kargo.dist</li>
    <li>molecule (python310Packages.molecule)</li>
    <li>molecule.dist (python310Packages.molecule.dist)</li>
    <li>pdm</li>
    <li>pdm.dist</li>
    <li>python310Packages.ansible-compat</li>
    <li>python310Packages.ansible-compat.dist</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.ansible-kernel.dist</li>
    <li>python310Packages.ansible-runner</li>
    <li>python310Packages.ansible-runner.dist</li>
    <li>python310Packages.ansible-vault-rw</li>
    <li>python310Packages.ansible-vault-rw.dist</li>
    <li>python310Packages.pytest-ansible</li>
    <li>python310Packages.pytest-ansible.dist</li>
    <li>python310Packages.pytest-testinfra</li>
    <li>python310Packages.pytest-testinfra.dist</li>
    <li>python310Packages.resolvelib</li>
    <li>python310Packages.resolvelib.dist</li>
    <li>python311Packages.ansible-compat</li>
    <li>python311Packages.ansible-compat.dist</li>
    <li>python311Packages.ansible-core</li>
    <li>python311Packages.ansible-core.dist</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-kernel.dist</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.ansible-runner.dist</li>
    <li>python311Packages.ansible-vault-rw</li>
    <li>python311Packages.ansible-vault-rw.dist</li>
    <li>python311Packages.molecule</li>
    <li>python311Packages.molecule.dist</li>
    <li>python311Packages.pytest-ansible</li>
    <li>python311Packages.pytest-ansible.dist</li>
    <li>python311Packages.pytest-testinfra</li>
    <li>python311Packages.pytest-testinfra.dist</li>
    <li>python311Packages.resolvelib</li>
    <li>python311Packages.resolvelib.dist</li>
  </ul>
</details>

**Comment by phaer** [comment]
@natsukium Are you still interested in this? 

Ansible_2_13 has already been dropped and Ansible_2_14 will be EOL in a month (https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) so we probably don't want to have that in 24.05 anyways.

So maybe we can finally get rid of this 3 year old resolvelib in nixpkgs? :)

**Comment by natsukium** [comment]
@phaer Thanks for letting me know. Let's drop `ansible_2_14` and update `resolvelib`.

**Comment by phaer** [comment]
I think this just needs a rebase but otherwise should be unblocked since https://github.com/NixOS/nixpkgs/pull/303372 hit master.

**Pull request merged**
