### PR TITLE
Stdenv shell instead of bin sh

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This targets #183.

Please review carefully, I did this without thinking too much. I also tried not to touch darwin stuff and only `.nix` files, as they are easy to patch.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Squashed. Feel free to suggest more.

**Comment by matthiasbeyer** [comment]
I guess this should be tagged as `mass-rebuild`.

**Comment by nbp** [comment]
It seems to me that many of these cases (`install`, `postInstall`, …) do not require such hand made modification.  the `patchShebangs` phase should already handle scripts which are using `#!/bin/sh`  and replace them by the version of sh which is available in the path, which is most likely to be the `stdenv.shell`.

On the other hand, I do agree that the `configure`, `preConfigure`, and `prePatch` phases are useful, unless you run `patchShebangs` there too.

Have a look at https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/patch-shebangs.sh

**Comment by nbp** [comment]
> It seems to me that many of these cases (install, postInstall, …) do not require such hand made modification. the patchShebangs phase should already handle scripts which are using #!/bin/sh and replace them by the version of sh which is available in the path, which is most likely to be the stdenv.shell.

Maybe, to make it explicit, we could just use `#!/patch-shebangs/sh`.

**Pull request closed without merging**
