### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
proper fix for python38 is found #108430. The commit was only reverted on staging-next, but staging will have python3.8.7

**Comment by TredwellGit** [comment]
Someone needs to revert https://github.com/NixOS/nixpkgs/commit/e1ed9b3b0851b95d3e82fb1085a121531c32a42a on staging.

**Comment by FRidh** [comment]
Gh action takes care of that.

**Comment by petabyteboy** [comment]
> Gh action takes care of that.

I think they mean revert the revert that was merged by GitHub actions. Because we _do_ want 3.8.7 in this iteration, no?

**Comment by TredwellGit** [comment]
That is what I mean.

**Comment by jonringer** [comment]
the bump was push to staging, not master, so staging-next wont get it.

But I'm also fine with not causing a stdenv rebuild.

**Comment by petabyteboy** [comment]
libsForQt5.qgpgme checks fail: https://termbin.com/6nb3

**Comment by petabyteboy** [comment]
374e3033d18897d753e5d5f1e5c5849489dcca12 is at fault

**Comment by FRidh** [comment]
Sigh...it really is time for rules on how to format lists and attribute sets.

**Comment by FRidh** [comment]
Building of Python wheels is broken on darwin, almost certainly due to 1a65c5df5f98 / https://github.com/NixOS/nixpkgs/pull/98915. Hopefully worked around with https://github.com/NixOS/nixpkgs/pull/108670.

**Comment by FRidh** [comment]
> libsForQt5.qgpgme checks fail: https://termbin.com/x0mm

is that because the update includes a bug, or because the tests in this package need fixing?

**Comment by FRidh** [comment]
~20.000 darwin builds to go. I will likely merge this tomorrow.

**Pull request merged**
