### PR TITLE
ocamlPackages.graphql_ppx: 1.0.1 → 1.2.0

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

Use ppxlib.

cc maintainers @Zimmi48 @jtcoolen 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zimmi48** [comment]
While testing with a project using the library, I got:

```
File "/nix/store/z00yjkrdp2mv12nkv0msblq1hxkp540f-ocaml4.10.2-graphql_ppx-1.2.0/lib/ocaml/4.10.2/site-lib/graphql_ppx/dune-package", line 9, characters 11-17:
9 |  (requires reason graphql_ppx.base ppxlib)
               ^^^^^^
Error: Library "reason" not found.
-> required by library "graphql_ppx" in
   /nix/store/z00yjkrdp2mv12nkv0msblq1hxkp540f-ocaml4.10.2-graphql_ppx-1.2.0/lib/ocaml/4.10.2/site-lib/graphql_ppx
```

This probably indicates that `reason` should be kept as part of the propagated dependencies.

**Comment by Zimmi48** [comment]
FTR, this ppx seems to be broken since 92a1b57bb14d48311df9c1b98a60cd4e0b8408dc. I get:

```
Error: No ppx driver were found.
Hint: Try upgrading or reinstalling ocaml-migrate-parsetree.
```

when trying to use it.

This error disappears after this upgrade but the ppx also seems to be ignored. I'll try to look deeper into it tomorrow.

**Comment by Zimmi48** [comment]
>This error disappears after this upgrade but the ppx also seems to be ignored.

It is not ignored. It's just that the API of the generated modules has changed. So my conclusion is that this PR fixes the problem introduced in 92a1b57bb14d48311df9c1b98a60cd4e0b8408dc. But I will need more time to adapt my project to the new API.

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
Approving modulo the move of `reason` out of the propagated build inputs (which should be reverted).

**Comment by vbgl** [comment]
Thank you Théo for your tests and comments. The non-propagation of `reason` and `ppxlib` has been done on purpose. Here is my reasoning.

If you build a library A using `graphql_ppx` (and the corresponding syntax additions), the (generated) code of this library will depend on the runtime (graphql_ppx.graphql_ppx_runtime); therefore the package of library A will have to propagate `graphql_ppx`.

However, when building a library B on top of library A but without using the syntax extensions from `graphql_ppx`, there is no need for `reason` nor `ppxlib`.

I believe that `reason` (and `ppxlib`) is not a real “transitive reverse-dependency” of `graphql_ppx`: only the direct users of `graphql_ppx` will need it (authors of A), not the users who come later in the dependency chain (authors of B).

Unless the authors of `graphql_ppx` split their libraries into smaller packages (in the dune/ocamlfind sense), the precise dependency graph cannot be precisely described in `nixpkgs`. So I had to make a choice (and I usually prefer to propagate less).

What do you think? (I may be wrong).

**Comment by Zimmi48** [comment]
>I usually prefer to propagate less

If that's your strategy, then the reasoning makes sense. But note that this strategy is going to feel more alien to opam users where there can only be "propagated build inputs".

This may also indicate the need for a finer grained notion of "propagated build input" in nixpkgs. One that would be propagated only to the packages using the library directly and not beyond...

**Comment by vbgl** [comment]
I’ve just amended the change to still propagate `reason`.

**Comment by vbgl** [comment]
Ping @Zimmi48. Is it better as it is now?

**Comment by Zimmi48** [comment]
@vbgl yes, thanks!

**Pull request merged**
