### PR TITLE
tandoor-recipes: fix build, 1.5.19 -> 1.5.25, add jvanbruegge as maintainer

### PR DESCRIPTION
**Pull request by jvanbruegge**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ipetkov** [comment]
Thanks for working on this! I can confirm that the frontend build is now fixed, but the main (python) package still fails to build

Tested with: `nim-build ./nixos/tests/tandoor-recipes.nix`

The following patch _does_ fix the python package for me though:

```diff
diff --git a/pkgs/applications/misc/tandoor-recipes/default.nix b/pkgs/applications/misc/tandoor-recipes/default.nix
index b6d99325f120..73bea7e03a3a 100644
--- a/pkgs/applications/misc/tandoor-recipes/default.nix
+++ b/pkgs/applications/misc/tandoor-recipes/default.nix
@@ -1,52 +1,15 @@
 { callPackage
 , nixosTests
-, python311
-, fetchFromGitHub
+, python3
 }:
 let
-  # python-ldap-3.4.4 does not work with python3(12)
-  python = python311.override {
-    self = python;
-    packageOverrides = self: super: {
-      validators = super.validators.overridePythonAttrs (_: rec {
-        version = "0.20.0";
-        src = fetchFromGitHub {
-          owner = "python-validators";
-          repo = "validators";
-          rev = version;
-          hash = "sha256-ZnLyTHlsrXthGnaPzlV2ga/UTm5SSEHLTwC/tobiPak=";
-        };
-        propagatedBuildInputs = [ super.decorator super.six ];
-      });
-
-      djangorestframework = super.djangorestframework.overridePythonAttrs (oldAttrs: rec {
-        version = "3.14.0";
-        src = oldAttrs.src.override {
-          rev = version;
-          hash = "sha256-Fnj0n3NS3SetOlwSmGkLE979vNJnYE6i6xwVBslpNz4=";
-        };
-        nativeCheckInputs = with super; [
-          pytest7CheckHook
-          pytest-django
-        ];
-      });
-
-      # python3.11-extruct-0.16.0 doesn't work with lxml-5.2.2
-      lxml = super.lxml.overridePythonAttrs (oldAttrs: rec {
-        version = "5.1.0";
-        src = oldAttrs.src.override {
-          rev = version;
-          hash = "sha256-eWLYzZWatYDmhuBTZynsdytlNFKKmtWQ1XIyzVD8sDY=";
-        };
-      });
-    };
-  };
+  python = python3;
 
   common = callPackage ./common.nix { };
 
   frontend = callPackage ./frontend.nix { };
 in
-python.pkgs.pythonPackages.buildPythonPackage rec {
+python.pkgs.pythonPackages.buildPythonPackage {
   pname = "tandoor-recipes";
 
   inherit (common) version src;
@@ -97,9 +60,10 @@ python.pkgs.pythonPackages.buildPythonPackage rec {
     psycopg2
     pyppeteer
     python-dotenv
-    pytube
+    pytubefix
     pyyaml
     recipe-scrapers
+    redis
     requests
     six
     uritemplate
```

**Comment by jvanbruegge** [comment]
Yes, fixed now.

**Review by ipetkov — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369173`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>tandoor-recipes</li>
  </ul>
</details>

**Comment by jvanbruegge** [comment]
I also deployed this now and it is working as expected

**Comment by ipetkov** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369173`

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>tandoor-recipes</li>
  </ul>
</details>

**Pull request merged**
