### PR TITLE
rust: 1.20.0 -> 1.21.0

### PR DESCRIPTION
**Pull request by yrashk**
###### Motivation for this change

Rust 1.21.0 has been released

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg rust.rustc

**Comment by LnL7** [comment]
I still have to test #31125 on linux, but we should probably merge those 2 at the same time.

**Comment by mguentner** [comment]
cc @Mic92

**Comment by Mic92** [comment]
Last time there was a problem with compiling firefox, is this resolved now?

**Comment by Mic92** [comment]
I currently try to build firefox with this pr.

**Comment by vcunat** [comment]
Firefox fails due to these:

> error: doc comment not used by rustdoc

**Review by LnL7 — APPROVED** [review]
For system: x86_64-darwin

```
cp: -r not specified; omitting directory 'target/release'
cp: -r not specified; omitting directory 'target/release/.fingerprint'
cp: -r not specified; omitting directory 'target/release/build'
cp: -r not specified; omitting directory 'target/release/deps'
cp: -r not specified; omitting directory 'target/release/examples'
cp: -r not specified; omitting directory 'target/release/incremental'
cp: -r not specified; omitting directory 'target/release/native'
post-installation fixup
stripping (with flags -S) in /nix/store/kdk4fyrccdny7a7iyw96ryhrnxplxc3q-cargo-0.22.0/bin
patching script interpreter paths in /nix/store/kdk4fyrccdny7a7iyw96ryhrnxplxc3q-cargo-0.22.0
```

**Comment by LnL7** [comment]
I tried backport some of the fixes from firefox 57 but it's getting kind of messy, perhaps we should start version rust like we do with other compilers?

**Comment by LnL7** [comment]
No, FF 57 is not released yet and the current version doesn't build with rust 1.21.

**Comment by Ma27** [comment]
the cyborg can talk😳

**Review by LnL7 — APPROVED** [review]
```
shrinking /nix/store/4q8x93zd34ivijg8v70pwkm5k2jsahvy-firefox-unwrapped-57.0/lib/firefox-57.0/libmozsandbox.so
shrinking /nix/store/4q8x93zd34ivijg8v70pwkm5k2jsahvy-firefox-unwrapped-57.0/lib/firefox-57.0/libmozavcodec.so
stripping (with flags -S) in /nix/store/4q8x93zd34ivijg8v70pwkm5k2jsahvy-firefox-unwrapped-57.0/lib  /nix/store/4q8x93zd34ivijg8v70pwkm5k2jsahvy-firefox-unwrapped-57.0/bin 
patching script interpreter paths in /nix/store/4q8x93zd34ivijg8v70pwkm5k2jsahvy-firefox-unwrapped-57.0
/nix/store/4q8x93zd34ivijg8v70pwkm5k2jsahvy-firefox-unwrapped-57.0/lib/firefox-57.0/run-mozilla.sh: interpreter directive changed from "/bin/sh" to "/nix/store/4ada72n7785wwazv42fhsnxjvilaa3aj-bash-4.4-p12/bin/sh"
checking for references to /tmp/nix-build-firefox-unwrapped-57.0.drv-0 in /nix/store/4q8x93zd34ivijg8v70pwkm5k2jsahvy-firefox-unwrapped-57.0...
running install tests
Mozilla Firefox 57.0
```

**Pull request merged**
