### PR TITLE
vimPlugins.nvim-dap-rr: init at 2024-07-10

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Add plugin [nvim-dap-rr](https://github.com/jonboh/nvim-dap-rr), an extension for [nvim-dap](https://github.com/mfussenegger/nvim-dap) to generate ready to go rr dap configurations.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 278871` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.nvim-dap-rr</li>
  </ul>
</details>

**Comment by teto** [comment]
looks like this depends at least on nvim-dap. Apparently it can work without telescope. And what about rr ? can it find it ok on nixos ?

**Comment by GaetanLepage** [comment]
> looks like this depends at least on nvim-dap. Apparently it can work without telescope. And what about rr ? can it find it ok on nixos ?

Yes indeed. I wonder how to properly add them. Is it right to put them in `dependencies` ?

**Comment by teto** [comment]
if you hardcode the path to "rr" then it works. If you add to propagatedBuildInputs, I am not sure what happens. We would need mechanisms to collect dependencies (eg. vim config, see https://github.com/NixOS/nixpkgs/issues/172538) that the neovim wrapper could inspect and build upon

**Comment by PerchunPak** [comment]
Since https://github.com/NixOS/nixpkgs/issues/172538 was closed, this can be resolved and merged, right?

@GaetanLepage

**Comment by GaetanLepage** [comment]
Looking at this again, I am not sure whether we should do anything extra.
Usually, we (in nixpkgs) don't bother providing the necessary dependencies for vim plugins.
Were you thinking of a specific "snippet" to include ?

**Comment by PerchunPak** [comment]
Yeah, after looking at this a bit more, there shouldn't be any extra work. `nvim-dap-python` is packaged very similarly to what is here now.

I will test this package a bit later.

**Review by PerchunPak — APPROVED** [review]
Found instructions where it is clear, that `nvim-dap-rr` doesn't use RR binary directly, so nothing we have to do.
https://github.com/rr-debugger/rr/wiki/Using-rr-in-an-IDE#setting-up-neovim

LGTM

**Pull request merged**
