### PR TITLE
font-manager: 0.7.3.1 -> 0.7.4.1

### PR DESCRIPTION
**Pull request by wedens**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Quiet weird to see travis here.

**Comment by worldofpeace** [comment]
@wedens Can you also switch to using the meson build system?

**Comment by Mic92** [comment]
@GrahamcOfBorg build font-manager

**Comment by worldofpeace** [comment]
> @worldofpeace I've never used meson before.
> 
> I've tried using meson, but I've got some errors/warnings:
> 
> ```
> lib/unicode/meson.build:23: WARNING: Passed invalid keyword argument "copy".
> WARNING: This will become a hard error in the future.
> lib/unicode/meson.build:23:0: ERROR:  Configure_file must have either "configuration" or "command".
> ```
> 
> ```
> WARNING: Unknown command line options: "auto_features"
> This will become a hard error in a future Meson release.
> ```

I couldn't reproduce. I've made these changes in https://github.com/NixOS/nixpkgs/pull/54272/commits/baa4b0ca57bcafce50930cf5e03a472b89f5f8de

**Comment by jtojnar** [comment]
That error looks like you were using old meson.

**Comment by wedens** [comment]
Seems like meson build introduced this problem when font-manager is installed with file-roller:
```
collision between `/nix/store/nds8x5h7i4v08618hyzi9pmk0knmsm23-font-manager-0.7.4.1/share/applications/mimeinfo.cache' and `/nix/store/vmrdln2j9pwkxmv4yw5b3xi0h8lfa1s3-file-roller-3.28.1/share/applications/mimeinfo.cache'
```

I suspect [this](https://github.com/FontManager/master/blob/master/meson_post_install.py) file is why it doesn't happen with `make`.

**Comment by worldofpeace** [comment]
> Seems like meson build introduced this problem when font-manager is installed with file-roller:
> 
> ```
> collision between `/nix/store/nds8x5h7i4v08618hyzi9pmk0knmsm23-font-manager-0.7.4.1/share/applications/mimeinfo.cache' and `/nix/store/vmrdln2j9pwkxmv4yw5b3xi0h8lfa1s3-file-roller-3.28.1/share/applications/mimeinfo.cache'
> ```
> I suspect [this](https://github.com/FontManager/master/blob/master/meson_post_install.py) file is why it doesn't happen with `make`.

Yeah I think that's a known issue. We probably need a setup hook to remove these `mimeinfo.cache`.

**Pull request merged**
