### PR TITLE
Clean up the inconsistent naming of themes

### PR DESCRIPTION
**Pull request by severen**
###### Motivation for this change

The directory names for themes were inconsistent. Some used the naming scheme `${theme}-gtk-theme`, whereas others just used the theme name.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X (N/A)
  - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by romildo** [comment]
I do not know if there are conventions regarding naming directories and packages. I try to name the package following the same name used by its authors. And it is common to save the Nix expression for a package in a file named `default.nix` in a directory named with the package name.

But I am still new to NixOS and there are many things regarding it that I do not know yet. Maybe more seasoned contributors have something to say about naming.

cc @vcunat

**Comment by vcunat** [comment]
Hmm, the case doesn't seem clear to me, even from text around http://nixos.org/nixpkgs/manual/#sec-organisation Note that in most other directories we tend to use the full name, and in particular numix and paper have multiple entries in the hierarchy (gtk theme, icons, etc.).

I suppose I'd leave the decision on maintainer(s) of these particular packages.

**Comment by romildo** [comment]
@SShrike @vcunat I am ok with this change. It has the advantage of keeping uniformity in the names of themes.

**Comment by taktoa** [comment]
I'm also okay with this change.

**Pull request merged**
