### PR TITLE
maintainers: Drop samueldr

### PR DESCRIPTION
**Pull request by samueldr**
I waited a long time, to wait and see how things would pan out.

It turns out obvious problems can't be dealt with, in an appropriate timing and manner.

Thanks to one individual, backed by a possee of previously banned individuals, and additional perma-banned individuals did it.

Thanks to all of you, I am quitting NixOS.

The continuous concern trolling, the continuous bigotted discussions, the continued hostile tone, the actions made despite the numerous times you were told to do better. The constant FUD. The constant waste of time. It's not a single event. It is a pattern.

I do not think that this situation can be salvaged anymore.

Systemic issue in the lack of governance enabled this. While some will put the fault entirely on the shoulders of the organization, I will say that they share the blame, but the bullying and pressure from the individuals ***who fully understand what they are doing*** is what did it.

Couple that with the structural inability for action by the moderation team being abused by those bad actors, and you have a recipe for alienating and burning-out the leftover important contributors.

Let it be written here that I have discussed with organization members and moderation team members about the continued behaviour of casting FUD on the community by this individual. This was done this individual's ban. It happened in what was (and still) tacitly agreed toe be a NixOS community place, the subreddit. Probably elsewhere too.

Nothing was done, no mention of re-considering the duration of the ban, and as far as I know, not even some discussion about how continuing the behaviour that was the reason for being banned is unwelcome.

What made me snap?

Not long after the ban being lifted, this individual continued with weird persecution plots and conspiracy theories casting doubts on the legitimacy of the moderation team's actions.

 - https://github.com/NixOS/rfcs/pull/175

And in the least self-aware way possible, continued this discourse of persecution and conspiracies, again casting FUD and divisiveness when asking for what, with a reasonable person, would have a formality.
See the original comment contents.

 - https://github.com/NixOS/nixpkgs-committers/issues/60#issuecomment-2179462978

This continued into the same behaviour that brought up the initial warnings and ban, on the unmoderated community-adjacent subreddit.

 - https://old.reddit.com/r/NixOS/comments/1djuxpx/drama_will_jonringers_commit_bit_be_restored/ https://archive.is/sCJJw
 
This continued onto the discourse into the same behaviour that brought up the initial warnings and ban.

 - https://discourse.nixos.org/t/should-jonringer-get-his-commit-bit-back/47267/46

The absolute insolence, consistently twisting the words I wrote to fit in his imagined narrative, took me over the edge. Then the moderator decision to *increase the time-out delay* to twelve hours, which at one hour was already causing the bad behaviour of mass-dumping information into single messages, meant there was no way for me to correct the facts and act in this manner without relitigating elsewhere gave me the time and energy to do it.

That's it.

The behaviour of this person. No political beliefs (I still don't know what they are). No employer (while I know and hate it, it is what it is). No plot form some shadow bagel trying to somehow do... Only jon knows what it would do... No take-over plot... Only the unacceptable behaviour, or character if you will, of that person.

Someone who from the start always had an equal opportunity to participate, regardless of his attributes. This person should have been accountable for his actions, but couldn't understand it.

This was not helped by their posse harrassing me personally, on top of all that.

In other words, the organization and community is not tooled to protect its valued members.

***So I am quitting with prejudice.***

Even though I helped build the NixOS project for over seven years, helped the community be the best it could in the IRC times, helped direct some of the community decisions.

I did not want to leave this community, because this is not only my home, but I built it with collaborators who cared. It seems like there is no one who cares left anymore. And I was pushed out against my best efforts.

Mostly thankless to the end.

— samueldr

<details><summary><h2>Things done</h2></summary>

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

</details>

https://discourse.nixos.org/t/maintainers-drop-samueldr-321436/47354

### CODE REVIEW

**Comment by vcunat** [comment]
Why do we need to immediately drop those packages?

**Comment by samueldr** [comment]
The maintainer did not do upkeep on them for a while. Most if not all were added early in Nixpkgs' lifetime for myself.

And some have unresponsive upstreams or have been removed/superseded.

**Comment by vcunat** [comment]
So by "unmaintained" you meant upstream.  In this context it really seemed to refer to yourself.

**Comment by RossComputerGuy** [comment]
What will happen with Mobile NixOS?

**Comment by samueldr** [comment]
> What will happen with Mobile NixOS?

https://discourse.nixos.org/t/maintainers-drop-samueldr-321436/47354#what-about-your-projects-2

**Comment by vcunat** [comment]
I think the discourse thread is better suited for such discussion (though Samuel doesn't seem to want any reactions).

Anyone has an idea what this GitHub warning is about?  I couldn't find anything.  (It's well hidden I guess?)
> The head ref may contain hidden characters: "ce\u00A0n'est\u00A0qu'un\u00A0au\u00A0revoir,\u00A0\u00E0\u00A0la\u00A0prochaine!"

**Comment by samueldr** [comment]
> So by "unmaintained" you meant upstream. In this context it really seemed to refer to yourself.

Sometimes both. I am picking up trash to try and lessen the load of "why is this even here?" in the future. I would have removed more, but that would have been a bad idea, since those are more important packages.

**Comment by samueldr** [comment]
> I think the discourse thread is better suited for such discussion (though Samuel doesn't seem to want any reactions).

Discourse thread for the stuff other than my maintainership yeah.


> Anyone has an idea what this GitHub warning is about? I couldn't find anything. (It's well hidden I guess?)
> 
> > The head ref may contain hidden characters: "ce\u00A0n'est\u00A0qu'un\u00A0au\u00A0revoir,\u00A0\u00E0\u00A0la\u00A0prochaine!"

Look at the origin branch name. I tried being fancy. GitHub tattled on me.

**Comment by samueldr** [comment]
Not waiting on Darwin for a maintainers removal.

image

**Comment by vcunat** [comment]
`uefi-firmware-parser` had a release upstream less than a year ago, but I don't know the package.

**Comment by samueldr** [comment]
I you (or anyone else) need it, feel free to package it!

**Pull request merged**
