### PR TITLE
minigalaxy: adds support for windows games

### PR DESCRIPTION
**Pull request by nickjanus**
###### Motivation for this change
Minigalaxy looks for wine in its path when user flips on support for windows games. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by legendofmiracles** [comment]
Not a fan of this, there are also plenty of games that are linux native and don't need wine to run.
Users shouldn't be forced to pull in over 600mb of dependencies for something they might not even need. 

If anything, this should be an optional flag to enable wrapping (should be a wrapper derivation to avoid rebuilding), to force the user to install wine in his environment, or a nixos module which makes either of those options more convenient.

**Comment by rapenne-s** [comment]
I'm not a huge fan either:

- it pulls a lot of extra dependencies
- I did some tests installing Windows games from GOG from minigalaxy. Lutris works a lot better to manage this.

# not usable
- banished: can't install
- final doom: run dosbox and nothing else happening
- anomaly defenders: can't install
- rollercoaster tycoon 2: fail to install
- return of the obra din: install and run but after the intro text the game stops responding
- return to castle wolfenstein: doesn't run
- unreal gold: can't install

# playable

- heroes 3 complete edition: it works
- shadowground survivor: it works
- torchlight: it works
- skyshine's bedlam: it works
- teleglitch: it works
- aquanox 2: it works

I didn't try AAA games because they are too long to install for me for testing purposes, but I suppose without a dxvk wine they are not playable either.

I'm not opposed to add Wine support though, but we have to keep in mind it will give a bad experience for most users.

**Review by rapenne-s — APPROVED** [review]
looks legit to me. Minigalaxy is able to use wine with the changes.

**Comment by nickjanus** [comment]
Thanks @legendofmiracles and @rapenne-s for reviewing! I should have some time this weekend to create a module and make the wine dependency optional, both of which seem like better ux. I do think it makes sense to have this enabled by default, if only to make installing the package less fiddly for those who want a "just works"(-ish) install, and because I've never associated "space-efficient" with nixos. 

I've used nixos for a bit, but I'm just switching over for gaming, so any suggestions on how to improve the wine experience here are welcome.

**Comment by legendofmiracles** [comment]
A module won't be needed for a simple `.override`, I was mostly just collecting thoughts with my first comment :p

I'm usually for just works, but wine is just on a different level with half a gigabyte of dependencies.
I'll leave it for @rapenne-s to decide whether it should be opt-in or opt-out

**Comment by rapenne-s** [comment]
I'd prefer opt-out strategy for a simpler user experience. When you are into installing commercial games, you don't care about 500 extra megabytes so this argument doesn't matter much IMO for minigalaxy.

**Comment by nickjanus** [comment]
@legendofmiracles it was a good learning exercise in any case, so I went ahead and added the module with wrapper. Hope that's alright!

**Comment by rapenne-s** [comment]
I don't have much experience with this, but I think the wrapper + module commits are a lot overhead for little benefit.

Wouldn't it be better to use something like in fossil package https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/fossil/default.nix#L14 with a conditional, and just add the wine to the bin path depending on the condition?

**Comment by nickjanus** [comment]
The benefit of the wrapper is that it's quicker to rebuild when changing the default vs a conditional in the unwrapped derivation. So instead of rebuilding the entire minigalaxy derivation, nixos just needs to create some symlinks. The module is more a matter of opinion on my part. As someone who has used nixos, but not bothered much with creating/understanding packages, I really like the module system for simple, stupid configuration of packages. It also helps that options are searchable via cli/nixos.org, unlike optional args for derivations, not counting nixpkgs checkouts :smile:. 

Is there a best practice here? I'm happy to remove the wrapper/module and just use an optional arg if you feel strongly.

**Comment by rapenne-s** [comment]
minigalaxy is really fast to rebuild because it's a few python files to bundle, I think we can afford rebuilding it entirely in case of change, a wrapper would just add more maintenance and complexity.

**Comment by rapenne-s** [comment]
@nickjanus hi, are you still willing to add support for windows games to minigalaxy?

**Review by infinisil — CHANGES_REQUESTED** [review]
I think the wrapper is fine, it doesn't matter much since the build is short, but it's a fairly common pattern in nixpkgs already.

Regarding the module, I think it's not needed, because the same thing can be achieved with just a

```nix
{
  systemPackages = [
    (pkgs.minigalaxy.override { withWine = false; })
  ];
}
```

I guess it's not as well documented then, but the `.override` pattern is fairly well-established.

@nickjanus Are you available to address this soon? Otherwise someone else could make these changes in a separate PR.

**Pull request closed without merging**
