### PR TITLE
kernelPatches: drop export_kernel_fpu_functions

### LINKED ISSUE #110956: kernelPatches.export_kernel_fpu_functions doesn't apply on 5.10.11
## Issue description

As of https://github.com/gregkh/linux/commit/f5ee8afc19711e1dd7bacae23712e224c1b22ba4, the patch doesn't apply anymore.

Do we still need it? How can one reproduce (and obvserve) the issue its supposed to fix?

cc @Mic92 @NeQuissimus

### PR DESCRIPTION
**Pull request by Atemu**
Hasn't been necessary since ZFS 0.8.3

###### Motivation for this change

Closes https://github.com/NixOS/nixpkgs/issues/110956

Ideally merge this right before a stable kernel bump to avoid unnecessary rebuilds.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Do we want to target staging with this?

**Comment by Mic92** [comment]
Maybe?

**Comment by NeQuissimus** [comment]
It should be OK to just remove this. There is a new batch of kernels coming anyways, let's merge this in.

**Comment by SuperSandro2000** [comment]
I basically can newer review kernel modules if I always need to build a few different kernels. :/

**Pull request merged**
