### PR TITLE
sd-image: FAT free /boot

### LINKED ISSUE #51924: Put kernel and initrd on ext4 in ARM images
## Issue description

As described in https://nixos.wiki/wiki/NixOS_on_ARM#Disable_use_of_.2Fboot_partition , it is not necessary to have the kernel on the FAT partition as u-boot can read from ext4.

@dezgeg said, "In retrospect, actually mounting the FAT partition at /boot was a bad idea... U-Boot can load the kernel+initrd+etc. just fine from the ext4 partition" - https://github.com/NixOS/nixpkgs/issues/22014#issuecomment-290152982

Note that we should keep the FAT partition, just reduce its usage. it is required for at least the raspberry pi: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/bootflow.md

So /boot/extlinux and /boot/nixos should be on ext4, /boot/*.{elf,bin,dat,txt} should stay in a FAT partition. Should we mount this fat partition at some point like `/boot/fat`?

@samueldr @dezgeg

### PR DESCRIPTION
**Pull request by samueldr**
#### A. Booting from ext4

*Fixes #51924*

This fixes one annoyance and allows recovering a bit of space.

The annoyance is that there is about 100MiB free for the generations on the
`/boot` partition in the current state of the SD images. This is not much when
playing around with kernels and this limit is often hit.

By using the FAT32 partition as a "firmware-only" partition for the Raspberry
Pi, we can reduce its size to a minimum required to hold the firmware-esque
bits required for boot. This allows us to cut ~100MiB of space.

#### B. Review "firmware" setup

By treating the FAT32 partition exactly as if it was a firmware bit, we can:

 1. Skip mounting it in the installed system.

This is not entirely *useful*, but this makes it easier to allow bigger firmwares
to be *fused* to the SD image as a user only has to remove the FAT32
partition to gain more space if needed (e.g. with some Rockchip firmwares).

> The initial PR also removed the 8MiB gap and assumed a user would
> remove the FAT32 partition before *fusing* a firmware to the SD image,
> but this is way too inconvenient compared to just dumping the data to
> the right location on the disk. 8MiB is not a significant enough size to
> warrant the headaches.

### Things done

- ☑️ Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - ☑️ NixOS
   - 🔲 other Linux distributions
- 🔲 Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- ☑️ Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- ☑️ Tested on hardware
- ☑️ Determined the impact on package closure size (by running ~~`nix path-info -S`~~ `nix path-info -s` before and after)
- 🔲 Assured whether relevant documentation is up to date
- ☑️ Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Here's the diff of the size of the image; the closure itself doesn't really change more.

```
[samueldr@aarch64:~/nixpkgs]$ nix path-info -s ./fat-free
/nix/store/pl1nvnm7g71j0hvbhjhd9xjxfy3ry7kg-nixos-sd-image-19.09pre130979.gfedcba-aarch64-linux.img      2007622888

[samueldr@aarch64:~/nixpkgs]$ nix path-info -s ./image--nixos-unstable
/nix/store/vlkb2zv9cyw95zhqpfz0cxxg1ibbr77j-nixos-sd-image-19.09pre130979.gfedcba-aarch64-linux.img      2081703144
```

All commits in the series should be independently good and able to build and boot. I verified boot at each step.

This was verified on:

 * Raspberry Pi 3B (the usual sd card boot, firmware from FAT32 partition as-built)
 * Pine A64-LTS (firmware from SPI nor flash, FAT32 partition still on)
 * Orange Pi Zero Plus 2 H5 (FAT32 partition deleted, no partition added, firmware fused as usual with dd)

---

**fusing**: I am using "fusing" as the term for the usual `sudo dd if=u-boot-sunxi-with-spl.bin of=/dev/sdX bs=1024 seek=8` for SoCs that read the firmware off the storage at a specific offset.

### CODE REVIEW

**Comment by samueldr** [comment]
I removed the only controversial change from the PR, it wasn't worth it in the end. Furthermore, the only advantage that it brought *still* is present by moving `/boot` off the FAT32 partition. It is possible to just remove the FAT32 partition to gain the couple MiB needed for the Rockchip blobby firmware that needs space up to 16MiB at the start of the disk.

**Comment by lheckemann** [comment]
[or non-blobby firmware](https://git.denx.de/?p=u-boot.git;a=blob;f=doc/README.rockchip;h=264f7e4994f9dcc81cac37d5632338946c1f0a05;hb=HEAD) :tada:

**Review by lheckemann — APPROVED** [review]
I haven't been able to test this yet, but it looks good :+1:

**Comment by samueldr** [comment]
Added `mkRemovedOptionModule` so users of the now removed options will get a warning, and builds that are most likely right.

**Comment by Thra11** [comment]
I wonder whether it would be possible (/ worthwhile) to remove the firmware partition from the generic sd-image but make it so that the raspberry pi derivation could override the necessary parts.

**Comment by samueldr** [comment]
@Thra11 it should be, though in the interest of ease of use, we end up putting that partition as "a" default firmware, which is for the most popular aarch64 platform.

We would still need to reserve the same amount of space in front of the system. So there would be no gain, other than removing a partition that isn't used by the system anymore.

**Pull request merged**
