### PR TITLE
Add monkeysphere package

### PR DESCRIPTION
**Pull request by kirchner**

### CODE REVIEW

**Comment by aforemny** [comment]
Thanks!

Merged in b80df37494407b0d5410365fe2446f573dd0d83a.

**Comment by jagajaga** [comment]
@aforemny Do you know about our `CONTRIBUTING.md`? This PR is out of guide.

**Comment by jagajaga** [comment]
@aforemny `description` of this pkg is out of rules too.

**Comment by jagajaga** [comment]
Fixed with https://github.com/NixOS/nixpkgs/commit/b6160fa7362ab62f7ad40477d63350827307e2d8
@aforemny please read http://hydra.nixos.org/job/nixpkgs/trunk/manual/latest/download-by-type/doc/manual#chap-submitting-changes.

**Comment by aforemny** [comment]
@jagajaga: My bad! Thank you for paying attention. :) I will pay attention to commit message format and meta attributes next time.

**Pull request closed without merging**
