### PR TITLE
i3: 4.9.1 -> 4.10.1

### PR DESCRIPTION
**Pull request by nmikhailov**

### CODE REVIEW

**Comment by nslqqq** [comment]
i3 now requires xephyr https://github.com/i3/i3/commit/2ddbc71e2bad4c287c28d4e8e4048db8fb801eb7

**Comment by domenkozar** [comment]
I thought that i3wm is trying to get rid of X dependencies?

**Comment by domenkozar** [comment]
@nslqqq apparently tests fail to build.

**Comment by nslqqq** [comment]
Yeah, probably xephyr crashes. I will look in to that as soon as I will
have some time.

**Comment by vcunat** [comment]
Needing git to build from a tarball is also strange.

**Comment by nslqqq** [comment]
@domenkozar @vcunat  
This should mostly be OK, though it requires #7316

**Pull request merged**
