### PR TITLE
pythonPackages.face_recognition: 1.2.1 -> 1.2.2

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

* Bumped `pythonPackages.face_recognition` to the latest version to get several important fixes (see the commit message for further reference)
* Reverted the latest `pythonPackages.dlib` bump as its build is currently broken

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
I think you should
1. raise an upstream issue about the dlib incompatibility
2. override the dlib version in the face_recognition expression instead of reverting the update

**Comment by Ma27** [comment]
@dotlambda that's not the problem. When running `nix-build -A pythonPackages.dlib` the build fails right now locally and on hydra: https://hydra.nixos.org/build/72222721

**Comment by dotlambda** [comment]
@Ma27 That's bad. Do you have an idea what could be causing the segfault? /cc @globin 

@GrahamcOfBorg build python2.pkgs.dlib python3.pkgs.dlib

**Comment by Ma27** [comment]
Don't have a spontaneous idea unfortunately. I can have a look at the diff of `dlib` between 19.9 and 19.10 though %)

**Comment by dotlambda** [comment]
I'm currently running `git bisect` and will keep you updated.

**Comment by Ma27** [comment]
awesome, thanks! I updated the description as it is indeed somehow misleading regarding *which* build was broken by the last `dlib` bump ;)

**Comment by dotlambda** [comment]
It seems like https://github.com/davisking/dlib/commit/14cbb804a9a69ba5ea928519f01c6c2875da2050 is causing this. However, I don't get a segfault but
```
  tools/python/test/test_svm_c_trainer.py ....../nix/store/6kz2vbh98s2r1pfshidkzhiy2s2qdw0a-stdenv-linux/setup: line 1223:  2914 Aborted                 /nix/store/azw9ys2m2fpfzf730xjcxja890gpyp58-python3-3.6.4/bin/python3.6m nix_run_setup test
```

**Comment by Ma27** [comment]
@dotlambda did you make any progress here or do you have any idea what could be causing this?

**Comment by dotlambda** [comment]
No progress, I don't have time right now. Would you mind opening an upstream issue about this? Maybe they can help out.
I'll merge this for now and hope we can eventually update to something like 19.11 which fixes this.

**Comment by Ma27** [comment]
@dotlambda I can have a closer look tonight and file a bug on upstream. Will keep you updated in case there's anything relevant for us %)

**Pull request merged**
