### PR TITLE
terraform-providers: update providers

### PR DESCRIPTION
**Pull request by zowoq**
###### Motivation for this change

Apart from a couple of problematic providers this updates everything using the terraform registry.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @zimbatm

### CODE REVIEW

**Comment by zowoq** [comment]
@ofborg build terraform-full

**Comment by zimbatm** [comment]
Result of `nixpkgs-review pr 153201` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>terraform-full</li>
  </ul>
</details>
<details>
  <summary>66 packages built:</summary>
  <ul>
    <li>terraform-providers.aci</li>
    <li>terraform-providers.auth0</li>
    <li>terraform-providers.avi</li>
    <li>terraform-providers.aviatrix</li>
    <li>terraform-providers.baiducloud</li>
    <li>terraform-providers.bigip</li>
    <li>terraform-providers.brightbox</li>
    <li>terraform-providers.checkpoint</li>
    <li>terraform-providers.ciscoasa</li>
    <li>terraform-providers.cloudscale</li>
    <li>terraform-providers.constellix</li>
    <li>terraform-providers.dme</li>
    <li>terraform-providers.dnsimple</li>
    <li>terraform-providers.docker</li>
    <li>terraform-providers.dome9</li>
    <li>terraform-providers.exoscale</li>
    <li>terraform-providers.flexibleengine</li>
    <li>terraform-providers.fortios</li>
    <li>terraform-providers.gridscale</li>
    <li>terraform-providers.heroku</li>
    <li>terraform-providers.huaweicloud</li>
    <li>terraform-providers.huaweicloudstack</li>
    <li>terraform-providers.icinga2</li>
    <li>terraform-providers.infoblox</li>
    <li>terraform-providers.ksyun</li>
    <li>terraform-providers.launchdarkly</li>
    <li>terraform-providers.linode</li>
    <li>terraform-providers.logicmonitor</li>
    <li>terraform-providers.mailgun</li>
    <li>terraform-providers.matchbox</li>
    <li>terraform-providers.mongodbatlas</li>
    <li>terraform-providers.ncloud</li>
    <li>terraform-providers.newrelic</li>
    <li>terraform-providers.ns1</li>
    <li>terraform-providers.nsxt</li>
    <li>terraform-providers.nutanix</li>
    <li>terraform-providers.okta</li>
    <li>terraform-providers.oktaasa</li>
    <li>terraform-providers.opc</li>
    <li>terraform-providers.opennebula</li>
    <li>terraform-providers.opentelekomcloud</li>
    <li>terraform-providers.opsgenie</li>
    <li>terraform-providers.pagerduty</li>
    <li>terraform-providers.panos</li>
    <li>terraform-providers.pass</li>
    <li>terraform-providers.powerdns</li>
    <li>terraform-providers.rundeck</li>
    <li>terraform-providers.scaleway</li>
    <li>terraform-providers.selectel</li>
    <li>terraform-providers.signalfx</li>
    <li>terraform-providers.skytap</li>
    <li>terraform-providers.spotinst</li>
    <li>terraform-providers.stackpath</li>
    <li>terraform-providers.statuscake</li>
    <li>terraform-providers.sumologic</li>
    <li>terraform-providers.tencentcloud</li>
    <li>terraform-providers.tfe</li>
    <li>terraform-providers.triton</li>
    <li>terraform-providers.turbot</li>
    <li>terraform-providers.ucloud</li>
    <li>terraform-providers.vcd</li>
    <li>terraform-providers.venafi</li>
    <li>terraform-providers.vra7</li>
    <li>terraform-providers.vultr</li>
    <li>terraform-providers.wavefront</li>
    <li>terraform-providers.yandex</li>
  </ul>
</details>

**Comment by zimbatm** [comment]
I'm not sure why `terraform-full` was skipped, but it builds fine here.

**Comment by zimbatm** [comment]
After this PR is merged, `["cloudstack", "segment", "vthunder"]` are the only providers that don't have a `provider-source-address`. I propose that those get removed so we can remove the old support.

**Review by zimbatm — APPROVED** [review]

**Comment by zowoq** [comment]
> After this PR is merged, `["cloudstack", "segment", "vthunder"]` are the only providers that don't have a `provider-source-address`. I propose that those get removed so we can remove the old support.

I've got a PR for those: https://github.com/NixOS/nixpkgs/pull/153206

**Pull request merged**
