### PR TITLE
haskellPackages.hasura: 2.0.7 -> 2.0.9

### PR DESCRIPTION
**Pull request by Lassulus**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@ofborg build hasura-graphql-engine hasura-cli

**Comment by cdepillabout** [comment]
Looks like this is at least building on Linux.

Thanks!

**Comment by datakurre** [comment]
@Lassulus Would you be able to help or instruct, how to upgrade hasura 2.0.9 to 2.0.10?

**Comment by Lassulus** [comment]
sure, just run `pkgs/development/misc/haskell/hasura/update.sh` from the top-level in nixpkgs. that should hopefully take care of that. just try to build it, if it fails with some reason. maybe some new dependencies need to be vendored, or some vendored need to be removed, that step is sadly trial and error, if it actually comes up.

**Comment by datakurre** [comment]
https://github.com/NixOS/nixpkgs/pull/148321

**Pull request merged**
