### PR TITLE
headphones: 0.6.0-beta.5 -> 0.6.0

### PR DESCRIPTION
**Pull request by rembo10**
###### Description of changes
Official v0.6.0 release with python 3. No major changes (was already on the python3 beta)
Tested working on nixos-unstable

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasj19 — COMMENTED** [review]
Build succeeded with nix-review however when i run the binary I encounter this:
```
headphones 
Cannot write to the data directory: /nix/store/lhq7lc8ndrl4wkwk2aisc01vnmfd7prc-headphones-0.6.0/opt/headphones. Exiting...
```
The app should not attempt to write in the nix store...

**Comment by rembo10** [comment]
Hm, so that's always been the case. The app attempts to store its data files in its own directory, unless --datadir is passed as a command line option (which is what happens with the nixos service).

Would it be better to wrap the program that will set the --datadir to /var/lib/headphones or something, unless that argument is passed in?

**Comment by dasj19** [comment]
If the data is user-app specific data then I would suggest a dot-folder inside the user's home folder as default. This way it would work also for nix users under other OS than NixOS.

**Comment by Artturin** [comment]
merging because rembo10 said its not a regression

**Pull request merged**
