### PR TITLE
go_1_19: 1.19.5 -> 1.19.6

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by mweinelt** [comment]
It would be very much appreciated, if you would discuss merging into a running staging cycle with us in #staging:nixos.org.

**Comment by mweinelt** [comment]
It could have easily been part of the original evaluation. Now we build one time with the old go version, one time with the new version, something that could've been prevented, if some communication made that clear.

**Comment by zowoq** [comment]
If you'd like prevention and communication, how about improving the notification for the start of the new cycle?

**Comment by qbit** [comment]
It sounds like the staging matrix room _is_ the place where those notifications happen, no?

**Comment by zowoq** [comment]
I'm suggesting something more prominent than what was posted there.

**Comment by zowoq** [comment]
> The Matrix room has been working pretty well for the months I've been involved in cycles. 

I wouldn't say that it worked well this time. Besides being rather unclear it seems like would have also needed to monitor multiple channels to have a complete understanding? I don't think I've missed any relevant comments here:

> looks like another staging-next cycle starting todayish

> Is -next going yet

> no
> it probably will be staging-next-22.11 first

> OK, so new staging-next

> Are we not doing 22.11 first?
> (I don't see any discussion about that, maybe I missed something in #dev.)

> 22.11 seems to be in progress. curl not fixed, rust not decided (?)

> Yeah, saw the #security-discuss discussion.

___


> What else would you prefer?

Clear, repeated warnings:

`new staging-next cycle will begin in 24 hours`

`new staging-next cycle will begin in 12 hours`

**Comment by vcunat** [comment]
But I don't have reliable predictions when to start a new cycle.  Hydra's load isn't so easy to predict, and also various important mass-rebuild fixes come in.

**Comment by zowoq** [comment]
> But I don't have reliable predictions when to start a new cycle. Hydra's load isn't so easy to predict

Treat the warning as a minimum notice period. Can always start it a bit later, just don't start it any earlier than the stated time.

**Comment by alyssais** [comment]
I'm not sure we want minimum notice periods, unless they're very short (much less than a day).  We decided to start these staging cycles in response to the git security issues, to get them out as quickly as possible.  Artificially delaying the cycles would mean delaying security updates.

Stuff should only **need** to to go into a particular staging cycle if it's a security fix or a fix for a regression.  We have a process for keeping track of security updates and making sure they get into the cycle if appropriate — it's the security triage matrix room.  It's kept very low traffic on purpose (we have a separate room for discussion), and the process from what I've seen has worked very well for security fixes that have been posted there.  We were not aware of these Go updates, because they were not posted there.  If they had been, we would have known to hold off on starting the cycle until they were merged.

**Comment by qbit** [comment]
It seems the problem is visibility in general then.

- Maybe maintainers need to up visibility by adding the `1.severity: security` tag for this kinda change? Would that increase visibility for the security triage room?
- Staging room could use some sort of brief heads up (maybe a room notice?) to make it more obvious when staging is about to start? I realize now that there was a comment stating it was started, but as a newcomer to the process (and room) - it didn't stand out to me (even when I was explicitly looking for it).

**Comment by zowoq** [comment]
> We were not aware of these Go updates, because they were not posted there. If they had been, we would have known to hold off on starting the cycle until they were merged.

Am I expected to pre-emptively post every new PR with security fixes that targets staging on the off chance someone decides to start a new staging-next cycle without mentioning it in #staging?

I would have just merged this myself if I'd been aware of the time frame.

> I'm not sure we want minimum notice periods, unless they're very short (much less than a day).

In this case it would likely have been avoided if I had had 7-8 hours notice, so 12 hours would work but longer would be better when it's possible.

**Comment by alyssais** [comment]
> Am I expected to pre-emptively post every new PR with security fixes that targets staging on the off chance someone decides to start a new staging-next cycle without mentioning it in #staging?

It's a good thing to do, yeah (for non-staging PRs too), because it means we can have an overview of all the security stuff going on.

**Comment by vcunat** [comment]
Well yes, that's what `staging` is for.  People "preemptively" make PRs and merge it there.  Including most of the security ones.

**Comment by zowoq** [comment]
> It's a good thing to do, yeah (for non-staging PRs too), because it means we can have an overview of all the security stuff going on.

Right, so this bottom-up communication, I still want better top-down communication.
___
> Well yes, that's what `staging` is for. People "preemptively" make PRs and merge them there. Including most of the security ones.

Sorry, I don't understand what you mean by this? I know how the staging cycle works, I was talking about having to pre-emptively post the PRs in #security?

**Pull request merged**
