### PR TITLE
Make autogen.man reproducible

### PR DESCRIPTION
**Pull request by basile-henry**
###### Motivation for this change

Working towards a reproducible iso_minimal (https://r13y.com/)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kisik21** [comment]
I feel like this is something that should be merged in staging, judging by how many packages need to be rebuilt.

**Comment by doronbehar** [comment]
Doesn't seem necessary to put this in 2 different commits. and yes it needs to target staging.

**Comment by NinjaTrappeur** [comment]
It seems like we were working on that concurently :) https://github.com/NixOS/nixpkgs/pull/103986

Note we have a IRC channel to sync the r13y effort, #nixos-r13y on freenode.

**Comment by zimbatm** [comment]
@basile-henry if you want to coordinate, we are a few people in the #nixos-r13y FreeNode channel.

https://github.com/NixOS/nixpkgs/pull/103986 was done concurrently to this

**Comment by basile-henry** [comment]
Ah, sorry about the duplicated efforts @NinjaTrappeur! :sweat_smile: I'll join the IRC channel to coordinate for future r13y work :+1:

**Comment by basile-henry** [comment]
Is there anything I need to do to get this PR over the line? :smile:

**Review by picnoir — APPROVED** [review]
LGTM

**Pull request merged**
