### PR TITLE
mercurial: 6.2.1 -> 6.2.2

### PR DESCRIPTION
**Pull request by techknowlogick**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by pacien — APPROVED** [review]
No new unexpected test failure.
Looking good to me :+1:

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 189379` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>devpi-client</li>
    <li>nbstripout</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>haskell-language-server</li>
    <li>haskellPackages.haskell-language-server</li>
    <li>haskellPackages.hls-alternate-number-format-plugin</li>
    <li>haskellPackages.hls-class-plugin</li>
    <li>haskellPackages.hls-module-name-plugin</li>
  </ul>
</details>
<details>
  <summary>54 packages built:</summary>
  <ul>
    <li>bumpver</li>
    <li>cabal2nix</li>
    <li>dep2nix</li>
    <li>dune-release</li>
    <li>git-cinnabar</li>
    <li>git-fast-export</li>
    <li>git-remote-hg</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>haskellPackages.ghcide</li>
    <li>haskellPackages.hls-brittany-plugin</li>
    <li>haskellPackages.hls-call-hierarchy-plugin</li>
    <li>haskellPackages.hls-change-type-signature-plugin</li>
    <li>haskellPackages.hls-eval-plugin</li>
    <li>haskellPackages.hls-explicit-imports-plugin</li>
    <li>haskellPackages.hls-floskell-plugin</li>
    <li>haskellPackages.hls-fourmolu-plugin</li>
    <li>haskellPackages.hls-haddock-comments-plugin</li>
    <li>haskellPackages.hls-hlint-plugin</li>
    <li>haskellPackages.hls-ormolu-plugin</li>
    <li>haskellPackages.hls-pragmas-plugin</li>
    <li>haskellPackages.hls-qualify-imported-names-plugin</li>
    <li>haskellPackages.hls-refine-imports-plugin</li>
    <li>haskellPackages.hls-rename-plugin</li>
    <li>haskellPackages.hls-retrie-plugin</li>
    <li>haskellPackages.hls-selection-range-plugin</li>
    <li>haskellPackages.hls-splice-plugin</li>
    <li>haskellPackages.hls-stylish-haskell-plugin</li>
    <li>haskellPackages.hls-tactics-plugin</li>
    <li>haskellPackages.hls-test-utils</li>
    <li>haskellPackages.retrie</li>
    <li>hound</li>
    <li>hydra_unstable</li>
    <li>mbed-cli</li>
    <li>mercurial (python310Packages.mercurial)</li>
    <li>mercurialFull</li>
    <li>mozphab</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>powerline (python310Packages.powerline)</li>
    <li>python310Packages.hg-evolve</li>
    <li>python310Packages.hg-git</li>
    <li>python310Packages.hglib</li>
    <li>python310Packages.python-hglib</li>
    <li>ydiff (python310Packages.ydiff)</li>
    <li>python39Packages.hg-evolve</li>
    <li>python39Packages.hg-git</li>
    <li>python39Packages.hglib</li>
    <li>python39Packages.mercurial</li>
    <li>python39Packages.powerline</li>
    <li>python39Packages.python-hglib</li>
    <li>python39Packages.ydiff</li>
    <li>sourcehut.hgsrht</li>
    <li>tortoisehg</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Can you take a look at the failing tests?

**Comment by pacien** [comment]
Quoting Sandro (2022-09-04 15:32:38)
> Can you take a look at the failing tests?

Failing tests:

- test-http-bad-server.t:
  - failing because of a formatting discrepencies between python versions
  - Upstream issue: https://bz.mercurial-scm.org/show_bug.cgi?id=6643

- test-hghave.t:
  - failing because of Python 3.12 deprecation messages
  - Upstream issue: https://bz.mercurial-scm.org/show_bug.cgi?id=6729

- test-patchbomb-tls.t:
  - failing because of Python 3.12 deprecation messages
  - Upstream issue: https://bz.mercurial-scm.org/show_bug.cgi?id=6727

Those concern only the tests (which are based on the console outputs).
They are not problematic otherwise.

We could temporarily disable those tests though.

**Review by pacien — APPROVED** [review]

**Pull request merged**
