### PR TITLE
antlr4: 4.7.1 -> 4.7.2

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
fixing updates @r-ryantm cannot.

patched mysqlWorkbench so it looked for the new version as well.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

```
$ nix path-info -Sh ./result
/nix/store/hh7mfax21dkp0cb6fr4hjc9cax558mlm-antlr-4.7.2  380.1M
$ nix path-info -Sh ./result
/nix/store/f1pwavzhbi3xlk1468syaykw8aqq2x5l-antlr-4.7.1  380.2M
```

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build antlr4 mysqlWorkbench python27Packages.antlr4-python2-runtime python27Packages.azure-cli-core python37Packages.antlr4-python3-runtime python37Packages.azure-cli-core

**Comment by jonringer** [comment]
@GrahamcOfBorg build antlr4 mysqlWorkbench python27Packages.antlr4-python2-runtime python27Packages.azure-cli-core python37Packages.antlr4-python3-runtime python37Packages.azure-cli-core

**Comment by mmahut** [comment]
@GrahamcOfBorg build antlr4 mysqlWorkbench python27Packages.antlr4-python2-runtime python27Packages.azure-cli-core python37Packages.antlr4-python3-runtime python37Packages.azure-cli-core

**Comment by disassembler** [comment]
building workbench locally as it's timing out because of build time it takes.

**Comment by mmahut** [comment]
@GrahamcOfBorg build antlr4 python27Packages.antlr4-python2-runtime python27Packages.azure-cli-core python37Packages.antlr4-python3-runtime python37Packages.azure-cli-core

**Comment by jonringer** [comment]
@GrahamcOfBorg build antlr4 python27Packages.antlr4-python2-runtime python27Packages.azure-cli-core python37Packages.antlr4-python3-runtime python37Packages.azure-cli-core

**Comment by jonringer** [comment]
bump :) @mmahut @marsam

**Comment by jonringer** [comment]
also, cc @FRidh as it includes two python packages

**Comment by marsam** [comment]
@jonringer thanks for working on this

**Pull request merged**
