### PR TITLE
perlPackages.NetAsyncHTTP: init at 0.47

### PR DESCRIPTION
**Pull request by zakame**
###### Motivation for this change

https://metacpan.org/pod/Net::Async::HTTP

This pure Perl module allows accessing HTTP using [IO::Async](https://search.nixos.org/packages?channel=unstable&show=perl532Packages.IOAsync&from=0&size=30&sort=relevance&query=IOAsync), along with accessing HTTPS (when [IO::Async::SSL](https://search.nixos.org/packages?channel=unstable&show=perl532Packages.IOAsyncSSL&from=0&size=30&sort=relevance&query=IOAsync) is available.)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102066` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>perl530Packages.NetAsyncHTTP</li>
    <li>perl532Packages.NetAsyncHTTP</li>
  </ul>
</details>

**Comment by zakame** [comment]
Thanks - so similar issue to https://github.com/NixOS/nixpkgs/pull/102071#issuecomment-718906248

I think I'll just disable network tests for here and on NetAsyncWebSocket entirely.

**Comment by stigtsp** [comment]
> I think I'll just disable network tests for here and on NetAsyncWebSocket entirely.

Is there a way to disable the network tests? It is rather nice to have at least some use_ok() tests to catch future breakage. :)

**Comment by zakame** [comment]
Maybe with some patching (e.g. `plan skip_all unless ...` on the test scripts needing network,) not sure how to do that here (yet) though :D

**Comment by stigtsp** [comment]
> Maybe with some patching (e.g. `plan skip_all unless ...` on the test scripts needing network,) not sure how to do that here (yet) though :D

You can remove files for tests that are failing in t/ for instance:

```
  preCheck = ''
    rm t/foo.t t/bar.t
  '';
```

**Comment by zakame** [comment]
Awesome, let me try that :muscle:

**Review by stigtsp — APPROVED** [review]
LGTM

Result of `nixpkgs-review pr 102066` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>perl530Packages.NetAsyncHTTP</li>
    <li>perl532Packages.NetAsyncHTTP</li>
  </ul>
</details>

**Comment by stigtsp** [comment]
@SuperSandro2000 Can you test on your Darwin?

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.NetAsyncHTTP perldevelPackages.NetAsyncHTTP

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102066` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>perl530Packages.NetAsyncHTTP</li>
    <li>perl532Packages.NetAsyncHTTP</li>
  </ul>
</details>

**Comment by zakame** [comment]
Thanks! :tada:

**Pull request merged**
