### PR TITLE
pipewire: wrap pipewire-pulse with pulseaudio

### PR DESCRIPTION
**Pull request by jonringer**
###### Description of changes

https://www.reddit.com/r/NixOS/comments/tj9vrj/fix_for_recent_pipewirepulse_breakage/

It attempts to call pactl

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
just realized this should go into staging, if it should go in at all

**Comment by virchau13** [comment]
Pulseaudio applications don't work without this change on my machine. `pipewire-pulse` outputs the following errors:

```
pipewire-pulse[1413]: execvp error 'pactl': No such file or directory
pipewire-pulse[1413]: failed to create context: No such file or directory
```

The second one seems to be the critical one, and it goes away after adding this to my configuration (which I think is essentially the same as the patch presented here):

```
systemd.user.services.pipewire-pulse.path = [ pkgs.pulseaudio ];
```

**Comment by jonringer** [comment]
Fix the build, also this is "only" a 9MB increase in closure size:

```
$ nix path-info -Sh ./result-pulse
/nix/store/z77lli69khq2zhyggndr36kn06idp7h0-pipewire-0.3.48-pulse	 514.3M
$ nix path-info -Sh ./result-pulse
/nix/store/9w6iv09bgdrhan4qpp9mlq2q87nr4cw4-pipewire-0.3.48-pulse	 523.3M
```

**Comment by collares** [comment]
@virchau13 Any chance this is fixed by #165231?

**Comment by virchau13** [comment]
> @virchau13 Any chance this is fixed by #165231? Audio is currently broken on NixOS unstable if you use GNOME and PulseAudio (i.e. if you didn't enable PipeWire explicitly).

I'm not at my computer right now, but I doubt it because:

- I don't use GNOME (or any DE),
- I explicitly enable PipeWire and disable PulseAudio,
- it still didn't work after I disabled Wireplumber and enabled pipewire-media-session.

I'll test it anyway though :P

**Comment by collares** [comment]
I agree there's no way the PR I mentioned can help. The reason I'm trying to find alternative explanations is that I also see a `pipewire-pulse[1982]: pw.conf: execvp error 'pactl': No such file or directory` message but not the "failed to create context" one, and PipeWire works fine here.

**Comment by collares** [comment]
The fact that your log message does not include the string `pw.conf` is a bit suspicious. Is there any chance Nix left a stale symlink in `~/.config/systemd/user` (as in #115492) and you're actually running an old version of PipeWire? The `pw.conf` topic logger was introduced in PipeWire 0.3.38 (https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/52bd80aaa45c8b72699e9d1faca640de8d7564b2), which is why I'm asking.

**Comment by virchau13** [comment]
Ooh, interesting...

```
<hexagon:~>% ls -la /etc/systemd/user/pipewire.service
lrwxrwxrwx 16 root root 93 Jan  1  1970 /etc/systemd/user/pipewire.service -> /nix/store/vyy4xwzbyvxfizwgp25fvkwdhjnq2apn-pipewire-0.3.48/lib/systemd/user/pipewire.service
<hexagon:~>% ls -la /etc/systemd/user/pipewire-pulse.service
lrwxrwxrwx 8 root root 105 Jan  1  1970 /etc/systemd/user/pipewire-pulse.service -> /nix/store/ma73z0g42alqvw3gvhcsqgwn5ig4d4a0-pipewire-0.3.48-pulse/lib/systemd/user/pipewire-pulse.service
<hexagon:~>% ls -la ~/.config/systemd/user/pipewire-pulse.service
lrwxrwxrwx 1 hexular users 105 Oct  4 16:19 /home/hexular/.config/systemd/user/pipewire-pulse.service -> /nix/store/vxlxcn9q5y5lascla1bpgrdd23lbi2x9-pipewire-0.3.36-pulse/lib/systemd/user/pipewire-pulse.service
<hexagon:~>% systemctl --user cat pipewire-pulse | head -n 1
# /home/hexular/.config/systemd/user/pipewire-pulse.service
```

So I do indeed have an old pipewire-pulse service in ~/.config/systemd/user that's being picked up.
However, if I delete the line `systemd.user.services.pipewire-pulse.path = [ pkgs.pulseaudio ];`, then rebuild, then the old pipewire-pulse version is still there, and the audio still breaks.

```
<hexagon:~>% systemctl --user daemon-reload
<hexagon:~>% systemctl --user cat pipewire-pulse | head -n 1
# /home/hexular/.config/systemd/user/pipewire-pulse.service
```

And the PipeWire service is always loaded from the new version of PipeWire regardless.

**Comment by collares** [comment]
Answering your edit: Because the config file (including the `{ path = "pactl"        args = "load-module module-always-sink" }` line) comes from the pipewire NixOS module, which is at the current version and is not affected by the stale symlink. Your `/etc` is not stale, but since you have both versions of pipewire-pulse in the Nix store (GCing should delete the old one), the symlinks are causing a version mismatch. This PR just works around this invalidation issue, it would probably work even if you replaced "pulseaudio" by any other package in `systemd.user.services.pipewire-pulse.path = [ pkgs.pulseaudio ];`.`

I'd delete `~/.config/systemd/user/pipewire-pulse.service` so Nix can recreate it.

**Comment by virchau13** [comment]
Yep that worked, thank you!

To anyone else who stumbles across this issue, delete the following files if present:

- `~/.config/systemd/user/pipewire-pulse.service`
- `~/.config/systemd/user/pipewire-pulse.socket`
- `~/.config/systemd/user/default.target.wants/pipewire-pulse.service`
- `~/.config/systemd/user/sockets.target.wants/pipewire-pulse.socket`

Still kind of strange these symlinks are getting created, though. I wonder what's behind that?

**Comment by collares** [comment]
That's a good question. Perhaps you ran `systemctl --user enable pipewire-pulse` manually at some point?

**Comment by virchau13** [comment]
Unfortunately, journalctl only shows my logs from 2021-12-01, so I have no idea. Although, should it not be the case that the entirety of ~/.config/systemd/user should be handled by home-manager / NixOS (i.e. it itself should be a symlink to a store path)?

**Comment by jansol** [comment]
Does this make the libpulseaudio dependency redundant?

**Comment by virchau13** [comment]
I mean, I guess so? IMO it's probably a good idea to add it anyway, since this behaviour may actually be important for some things, and since those who use pipewire-pulse also use at least 1 PulseAudio application it's very unlikely to add more disk usage.

**Comment by jansol** [comment]
I mean the library provided by the `libpulseaudio` package is already contained in the `pulseaudio` package, no? So there is no point in having it twice in pipewire. While you are right that the disk space question is likely negligible, it still does still ever so slightly add to the closure size. But more importantly it makes maintaining the pipewire package more confusing to have two almost-but-not-quite identical dependencies.

**Comment by jonringer** [comment]
> Does this make the libpulseaudio dependency redundant?

not necessarily. With the `withPulseAudio` switch, it might be the case that someone will build it without pulse support. However, the logic right now assumes that this will always be true

**Comment by jansol** [comment]
Then the logic should be fixed to account for that. It does not really make sense to build the pulseaudio compatibility layer without well, support for pulseaudio.

**Comment by flokli** [comment]
The first part of this comment is probably off-topic for this PR, but in case someone else runs into the same issue, here it goes.

---

I ran into random freezes in applications using pipewire-pulse - such as firefox stalling in all windows when opening a tab that tries to play/record sound. I also saw the

```
pipewire-pulse[1413]: execvp error 'pactl': No such file or directory
```

error here, and when disabling the socket (via `systemctl --user stop pipewire-pulse.socket`) it didn't freeze.  

I thought I was having the same issue. I gave this PR (cherry-picked into current master) a spin, it didn't improve things. I still had freezing windows.

In my case, in the end it could have been an unreachable bluetooth device. `pipewire.service` was logging lines like:

> pw.link: 0x5589c7760db0: one of the nodes is in error out:suspended in:error

I removed the device via `bluetoothctl`, restarted `wireplumber` and restarted `pipewire-pulse.socket`. The issue is gone!

---

As for this PR, I'm not sure this is the right way forward. We shouldn't hardcode some PATH into the binary. If we want to do something like this, we probably want to add a `systemd.user.services.pipewire-pulse.path = [ pkgs.pulseaudio ];` to `nixos/modules/services/desktops/pipewire/pipewire.nix`, rather than patching a random pulseaudio path into the pipewire application output.

**Comment by lilyinstarlight** [comment]
I just opened #173160 with the suggestion to just add `pkgs.pulseaudio` to the pipewire-pulse user unit path. If everyone agrees that should be the way forward, it can supersede this PR (but I'm not invested in any one solution, I just noticed no one had PR'd that yet and it would be nice to get something in)

**Comment by klemensn** [comment]
> I just opened #173160 with the suggestion to just add `pkgs.pulseaudio` to the pipewire-pulse user unit path. If everyone agrees that should be the way forward, it can supersede this PR (but I'm not invested in any one solution, I just noticed no one had PR'd that yet and it would be nice to get something in)

Wrappers should be avoided where possible, so adding pulseaudio to the systemd service PATH is the right thing to do.

**Review by klemensn — CHANGES_REQUESTED** [review]
Wrappers should be avoided where possible, so adding pulseaudio to the systemd service PATH is the right thing to do.

**Comment by flokli** [comment]
How does one add pipewire-pulse to the system? Can this be done by the module system under the hood?

**Comment by jansol** [comment]
@flokli  Pipewire-pulse is part of the pipewire package and is enabled in nixos by enabling pulse compatibility in the pipewire module.

**Comment by klemensn** [comment]
> @flokli Yep, open PR #173160 does this via the module system when `services.pipewire.pulse.enable = true`

Which I implicitly referred to given the context in this PR.

**Comment by jonringer** [comment]
I think #173160 solves this a better abstraction layer. going to close in favor of the other

**Pull request closed without merging**
