### PR TITLE
services.openssh: remove authorizedKeysCommand*

### PR DESCRIPTION
**Pull request by teto**
WIP PR to deal with openssh settings.

not needed now that they can be set via services.openssh.settings. If you only set services.openssh.AuthorizedKeysCommand without its AuthorizedKeysCommandUser counterpart (the user under which to run services.openssh.settings.AuthorizedKeysCommand), the sshd config validation will fail. The previous default was "nobody" so if you haven't deviated from it the migration path would be

services.openssh.settings.AuthorizedKeysCommandUser = "nobody" if not set else or services.openssh.settings.authorizedKeysCommandUser.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
@GrahamcOfBorg   test initrd-network-ssh

**Comment by teto** [comment]
I get `definition for option `services.openssh.settings.AuthorizedKeysFiles' is not of type `atom (null, bool, int, float or string)'` maybe I should revert that change after all, it's confusing to set a table instead of a string there too. 
Seems like `keyValue` accepts `listsAsDuplicateKeys = true;` as parameter. I'll see if I can create something that makes sense with it otherwise I'll revert the AuthorizedKeysFiles change

**Comment by teto** [comment]
I give up on ssh config. It is madness.

**Comment by aanderse** [comment]
@infinisil as the RFC42 champion do you have any advice for our situation?

the ssh file format will sometimes require that `key` of `type = listOf x` be transformed into `key x1 x2 x3 ...`, sometimes into `key x1,x2,x3,...`, and sometimes `key x1\nkey x2\nkey x3`... obviously this is problematic when we try to use a `settings` option for a file format like this

it almost feels as if adding a new overridable attribute called `toString` to `mkOption` would be useful... then we could do something like this:
```
key = mkOption {
  type = with types; listOf str;
  toString = x: concatStringsSep " " x; # vs `x: concatStringsSep "," x;` vs ... something something `listAsDuplicates = true`...? 🤔
};
```

at the same time that feels very overkill for a problem that _rarely_ occurs for us

i'm not expecting you to pull a rabbit out of your hat but i find it is usually worth pinging you on topics like this... so why not :smile:

any ideas? :heart:

**Comment by infinisil** [comment]
Thanks for the kind ping @aanderse! ❤️

This sounds like a case where it's appropriate to not rely on `pkgs.formats`, and instead write a custom, sshd-local format with the exact semantics needed.

I can imagine it looking a bit like this:

```
let
  # Any keys not specified here will be rendered on separate lines
  exceptionalKeyRenderKind = {
    SomeOption = "spaces";
    AnotherOption = "commas";
  };

  generate = ...;
in
...
```

It's of course a bit against the RFC42 spirit, because it makes the module more tied to upstream, but this seems unavoidable. I hope the list of keys that need such special rendering doesn't change often over time!

**Pull request closed without merging**
