### PR TITLE
Common lisp update

### PR DESCRIPTION
**Pull request by lukego**
###### Motivation for this change

Update the Common Lisp collection (`lispPackages`):

- Upgrade to the latest Quicklisp release 2021-08-07.
- Add assorted Quicklisp packages.
- Remove stale Quicklisp packages
- Add `mgl` and `mgl-mat` machine learning libraries that are outside Quicklisp.
- Fix shell script bug leading to environment space exhaustion.
- Update `shell.nix` and add instructions about doing so.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
>I pushed a fix to the syntax error on `mgl`. The failing `lispPackages` builds are now `iolib`, `dbus`, `nyxt`, and `mgl.` I'll troubleshoot when I have a chance and meanwhile the log is at https://gist.github.com/lukego/195feb701abe5996441119149f6cc01b.

Hmmm. OK, so `iolib` seems to have gained a new test that defaults to resolving a host on the public internet… https://github.com/sionescu/iolib

Sounds like we either need to drop those tests, or replace the address in the test (and compile and run the echo server)

**Comment by lukego** [comment]
So the failures we have now are `iolib`, `dbus`, and `nyxt`. Just at a glance it seems like `iolib` is the root cause and the others fail for depending on it.

**Comment by lukego** [comment]
Relatedly: There's a lot of activity around a new Lisp package management project called CLPM recently and I'm engaging with that crowd to see if there is room to collaborate. In particular I thought that if they are already generating extensive snapshots of Lisp package metadata then perhaps we could potentially import those as a convenient alternative to grovelling Quicklisp ourselves.

See https://gitlab.common-lisp.net/clpm/clpm/-/issues/47 for my braindump on that topic.

**Comment by lukego** [comment]
> What SBCL version is Quicklisp using now? Can we bump our default SBCL to 2.1.9? Currently we are still on 2.1.2, I think.

I hadn't noticed this. I'll try switching the default to 2.1.9 and if it works I'll push it on this branch too. Maybe it will help the `caveman` package to magically come back :)

**Comment by lukego** [comment]
> So, caveman is still broken in an unclear way with 2.1.9?

The specific error that I get on caveman is obscure but seems consistent with a package not being supported: https://gist.github.com/lukego/08efa6f9d2683d07187d3b95c9b94d7d.

I am not familiar with Caveman. On the one hand Quicklisp seems to list it as supported. On the other hand its [Github repo](https://github.com/fukamachi/caveman) seems to have been replaced with Caveman2 which Quicklisp treats as a separate package. So I don't know what to think about that and am inclined to drop it unless someone specifically needs it.

> I am now considering squash-merging

That would suit me fine. If you need any git-fu work from me though just let me know.

**Pull request merged**
