### PR TITLE
eclipses.plugins: add custom builder

### PR DESCRIPTION
**Pull request by rycee**
This builder simply adds two convenience functions called `installFeatureJar` and `installPluginJar`, respectively. These functions reduce the need of code duplication and makes `buildEclipsePlugin` correctly install plugin JAR that require unpacking.

### CODE REVIEW

**Comment by rycee** [comment]
@bjornfor, mind having a look at this?

**Comment by bjornfor** [comment]
I don't have very strong opinion, so if you want this merged, I can merge it. But you asked for review :-)

**Comment by rycee** [comment]
Good comments and exactly why I like to have a review :-)

I got the idea to use a custom builder from wanting to introduce the special install shell functions and otherwise have the build be a generic one. But for this simple case I think your solution is much cleaner so I switched to that one. I made the `installHelpers` variable "file local" since it is of fairly limited use outside `buildEclipsePlugin` and `buildEclipseUpdateSite`.

**Comment by bjornfor** [comment]
Ok :-)

But still the end result is about twice as many lines as before (ref. https://github.com/rycee/nixpkgs/commit/40eae632ea3377a9eeb959481ad867c840520aae). I'm not convinced :-)

But more importantly, you say in the commit message:

"These functions [...] makes `buildEclipsePlugin` correctly install
plugin JAR that require unpacking."

Is that the reason for the increase (bug fix)? Since I'm clearly not seeing what you're seeing, can you try fixing the bug first (in commit 1) and then reduce duplication (in commit 2)?

**Comment by bjornfor** [comment]
@rycee: What to do with this PR? Close or merge? (I still don't see the point, but I'm not that into the eclipse expressions as you are.)

**Comment by rycee** [comment]
Oops, I had completely forgotten about this! I'll close it since I don't have a need for this anymore but might revisit it in the future. Thanks!

**Pull request closed without merging**
