### PR TITLE
flashplayer: changed source origin

### PR DESCRIPTION
**Pull request by ericsagnes**
Please do not merge yet, this PR needs test and feedback.

Implementation of #11571 

This PR goal is to fix the flashplayer source not found error during `nixos-rebuild`.

Details:
Currently `flashplayer` is not cached in the binary cache, and the used `src` keeps only the newest version. 
If a `nixos-rebuild` is run after upstream has pushed a new version,  a source build of flashplayer is triggered and fails due to source not found, aborting the update.

I mainly changed the source origin and merged the code in `builder.sh` in the main derivation.
This should hopefully not introduce breaking changes and the derivation is building fine on my machine.
I don't have a 32 bit machine and am not familiar on how to test `flashplayer`, so feedback and testing is very appreciated.
Please also let me know if there are possible improvements.

cc maintainer @enolan

### CODE REVIEW

**Comment by enolan** [comment]
Sorry, I'm not using Nix anymore. Best of luck!

**Comment by ericsagnes** [comment]
@enolan No problems, would you like me to add a commit to remove you from the flashplayer maintainers?

**Comment by enolan** [comment]
I PR'd it already, thanks.

**Comment by ericsagnes** [comment]
duplicate of #11675

**Pull request closed without merging**
