### PR TITLE
pkgs/by-name: recommendations for multi-versioned packages

### PR DESCRIPTION
**Pull request by infinisil**
## Description of changes

Over the past weeks, we've seen one oversight with the new enforcement of `pkgs/by-name` for new packages.

This documents the problem and the recommendation for resolving it.

Here's some PRs that could've benefited from this:
- https://github.com/NixOS/nixpkgs/pull/291951#discussion_r1506857429
- https://github.com/NixOS/nixpkgs/pull/287918#issuecomment-1939243084
- https://github.com/NixOS/nixpkgs/pull/262276#issuecomment-1949922134
- https://github.com/NixOS/nixpkgs/pull/289690
- https://github.com/NixOS/nixpkgs/pull/285922#issuecomment-1925940231
- https://github.com/NixOS/nixpkgs/pull/285888#issuecomment-1924760282
- https://github.com/NixOS/nixpkgs/pull/285681#issuecomment-1922860408
- https://github.com/NixOS/nixpkgs/pull/291339

In the future, the error message should also link to this documentation

Ping @AndersonTorres @afh 

This work is sponsored by [Antithesis](https://antithesis.com/) :sparkles:

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by AndersonTorres — APPROVED** [review]

**Comment by AndersonTorres** [comment]
Not directly related, but a thing that concerns me is that `darwin. apple_xyz_sdk.callPackage` that hinders by-name adoption, e.g. for tinycc.

**Comment by infinisil** [comment]
@AndersonTorres Quick thoughts: I like how `pkgs/by-name` highlights such oddities and urges us to resolve them. While I think it's totally possible to fix that, I don't have an immediate answer.

This seems like an orthogonal problem though, could you open an issue for this?

**Comment by adamcstephens** [comment]
There are a lot of options in here, but it's not clear to me on first read which I'd want. Is there no way to loosen the checks somehow for packages that have yet to migrate?

**Review by afh — APPROVED** [review]
Thanks for writing this up, @infinisil. Very helpful!

Especially the list of example PRs where this popped up. I'd like to suggest to include #289690 in said list.

See below a minor blank space suggestion for consistency if this is relevant/important for project READMEs.

**Comment by infinisil** [comment]
@afh Thanks, done that!

**Pull request merged**
