### PR TITLE
Update pew to 0.1.14

### PR DESCRIPTION
**Pull request by berdario**

### CODE REVIEW

**Comment by lethalman** [comment]
I think the travis fail is genuine. Make sure you are using chroot builds.

**Comment by berdario** [comment]
Uhm, it seems this is incorrectly building pew with pypy2.4.

Basically: pew can work just fine with CPython2.6,2.7,pypy-python2.7,CPython3.3,CPython3.4,pypy-python3.2, but for everything except Python (either CPython or Pypy) under 3.4 (the pypy equivalent doesn't exist yet, but it should be only a matter of time), it needs some backported libraries. So I only packaged it for Pythons >=3.4.

**Comment by madjar** [comment]
@berdario I guess `disabled = !isPy34;` would do the trick.

**Comment by berdario** [comment]
> I think that the issue is that pypy doesn't have its python.majorVersion correctly set

This was incorrect: pypy had a `pythonVersion` attribute, and the correct approach for interpreter-agnostic code is to rely on that. That attribute though was missing from the other interpreters.

Now it should be fixed

**Comment by lethalman** [comment]
@iElectric let's merge this? Not sure if this travis error is related: `error: attribute ‘plone’ in selection path ‘python27Packages.plone.app.querystring-1.1.1’ not found`

**Comment by iElectric** [comment]
Why not just `disabled = isPy34;`

**Comment by berdario** [comment]
Because when pypy with py3.4 source compatibility will be packaged/released the expression won't make it available (my travisCI builds are already testing it successfully on Pypy3)

Also: as mentioned, `pythonVersion` ought to be available for every interpreter

And using `pythonAtLeast/pythonOlder` is just cleaner if all you want to do is just to specify a range of versions

**Pull request merged**
