### PR TITLE
caja-dropbox: fix python dependency

### LINKED ISSUE #62612: Caja dropbox does not build
## Issue description
caja-dropbox does not build and throws error:
```
error: pygtk-2.24.0 not supported for interpreter python3.7
```

### Steps to reproduce
run `nix-env -i caja-dropbox`

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.19.47, NixOS, 19.09pre181392.4ab1c14714f (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(alex): `""`
 - channels(root): `"nixos-19.09pre181392.4ab1c14714f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by alexarice**
###### Motivation for this change
Fixes #62612
This seems to fix the issue though I don't know much about python packaging so I don't know if what I have done is correct.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
@GrahamcOfBorg build mate.caja-dropbox

**Review by romildo — APPROVED** [review]
- [X] reviewed the diff and commit messages
- [X] made sure local build succeeded
- [X] run nix-review without any failures

**Comment by jtojnar** [comment]
Perhaps you might not want pygobject except for build (see https://github.com/NixOS/nixpkgs/pull/60752)

**Comment by alexarice** [comment]
> 
> 
> Perhaps you might not want pygobject except for build (see #60752)

So pygobject and gobject-introspection should be in native build inputs?

**Comment by jtojnar** [comment]
If the package is synchronized with `nautilus-dropbox` (`dropbox-cli` in Nixpkgs). I did not actually checked the fork did not diverge.

**Comment by alexarice** [comment]
I don't know much about the project, I just added things until it built. I know that pygobject and gobject-introspection are definitely needed during the build.

**Comment by alexarice** [comment]
The packages look virtually identical so I have the changed the dependencies to look like `nautilus-dropbox`

**Comment by alexarice** [comment]
@romildo @jtojnar is this ok now?

**Comment by jtojnar** [comment]
Hmm, the package actually does not obtain Dropbox from Nix. Either it needs to do so with a patch like `nautilus-dropbox` does, or it will require `pygobject` & `gtk` at runtime to download it.

**Comment by alexarice** [comment]
I'll include a patch

**Comment by alexarice** [comment]
Hopefully this is fixed now though I don't really know a good way to test if an input was correctly put as a nativeBuildInput or buildInput

**Comment by jtojnar** [comment]
You can add `strictDeps = true` to the derivation to enable the distinction.

**Comment by alexarice** [comment]
It all works with strictDeps on, should I include strictDeps in the derivation or is it unnecessary

**Comment by alexarice** [comment]
I have put in the `strictDeps = true` line as it everything appears to work correctly with it there

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
