### PR TITLE
unicorn: 2.0.0-rc7 -> 2.0.1

### PR DESCRIPTION
**Pull request by erdnaxe**
###### Description of changes

Based on https://github.com/NixOS/nixpkgs/pull/199191 but with a fix for Unicorn-Engine Python module.
Also fix darwin build using fix proposed by https://github.com/NixOS/nixpkgs/pull/199191#pullrequestreview-1167755288.
Fix aarch64-darwin build by introducing a patch.
Enable tests.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erdnaxe** [comment]
Result of `nixpkgs-review pr 199650` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.angrcli</li>
    <li>python39Packages.angrcli</li>
    <li>python39Packages.manticore</li>
    <li>unicorn-emu</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>adenum</li>
    <li>gef</li>
    <li>pwndbg</li>
    <li>pwntools (python310Packages.pwntools)</li>
    <li>python310Packages.angr</li>
    <li>python310Packages.angrop</li>
    <li>python310Packages.qiling</li>
    <li>python310Packages.unicorn</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.pwntools</li>
    <li>python39Packages.qiling</li>
    <li>python39Packages.unicorn</li>
    <li>unicorn</li>
  </ul>
</details>

**Comment by erdnaxe** [comment]
Upstream issue for aarch64-darwin: https://github.com/unicorn-engine/unicorn/issues/1730

**Comment by erdnaxe** [comment]
```
Test test_x86_nested_emu_start...                 Test interrupted by signal 10.
Test test_x86_nested_emu_stop...                  Test interrupted by signal 10.
Test test_x86_64_nested_emu_start_error...        Test interrupted by signal 10.
Test test_x86_nested_uc_emu_start_exits...        Test interrupted by signal 10.
```
There are 4 `test_x86` unit tests failing. All other tests are passing. Should we ignore testing on aarch64-darwin?

**Comment by risicle** [comment]
`nixpkgs-review` happy, aarch64-linux

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64. `pkgsStatic` and `pkgsCross.aarch64-multiplatform` variants build. Nice work.

**Pull request merged**
