### PR TITLE
python312Packages.dbus-python: 1.2.18 -> 1.3.2

### PR DESCRIPTION
**Pull request by mweinelt**
Migrates the build from autotools to meson-python.

- [x] .pc file does not yet land in the `dev` output
  - `lib/python3.11/site-packages/.dbus_python.mesonpy.libs/pkgconfig/dbus-python.pc`
  - How to configure that path in meson?
- [x] test `ffado`, it should be able to import `dbus.mainloop.pyqt5`

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pedorich-n** [comment]
Hi, @mweinelt ! Is there any chance you could get back to this? 

---

I have no idea what I'm doing, but I was able to find some info regarding your first question:
https://mesonbuild.com/Pkgconfig-module.html

> `install_dir` the directory to install to, defaults to the value of option `libdir` followed by `/pkgconfig`

Also, I found this: https://github.com/mesonbuild/meson-python/issues/240. It looks like `meson-python` can't install the `pc` file outside of `site-packages` if I'm reading it correctly 🤔 

I searched `nixpkgs` and found some derivations that patch `meson.build` files with a different `install_dir`, but none do that for `pc` files.

**Comment by mweinelt** [comment]
My backlog is quite large, so feel free to experiment with the existing changes. I don't know when I'll get back to them.

**Comment by SuperSandro2000** [comment]
> `install_dir` the directory to install to, defaults to the value of option `libdir` followed by `/pkgconfig`

install_dir is changed to fit into the wheel structure. When trying to override it with ``install_dir: get_option('libdir') / 'pkgconfig'`` it just fails with ``('\x1b[31m',)meson-python: error: Could not map installation path to an equivalent wheel directory: 'lib/pkgconfig/dbus-python.pc'``

**Comment by SuperSandro2000** [comment]
@ofborg build ffado

**Comment by pedorich-n** [comment]
Thanks for the fix, @SuperSandro2000 !

I actually spent a weekend back then trying to make this work, but failed. I thought I can make the meson do the correct lib placement "natively" and got stuck trying. 
Turns out it can't be done after all and a quick `mv` would've solved my issues. Oh well :smiley:

**Pull request merged**
