### PR TITLE
arduino: 1.6.0 -> 1.6.7

### PR DESCRIPTION
**Pull request by flosse**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [x] Built on platform: NixOS
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### More

cc @antono @robberer @bjornfor @dajero

### CODE REVIEW

**Comment by flosse** [comment]
Please don't merge, there is still an error if you wan't to compile a sketch:

```fork/exec /nix/store/ki0kap5g9rb7m85481900y23zph5ha9p-arduino/share/arduino/hardware/tools/avr/bin/avr-g++: no such file or directory```

**Comment by joachifm** [comment]
xref https://github.com/NixOS/nixpkgs/pull/6694

**Comment by aneeshusa** [comment]
Could you also please add a commit to update the meta.homepage attribute to use HTTPS? (i.e. https://www.arduino.cc/) Refs #13809.

**Comment by joachifm** [comment]
@flosse what is the status on this?

**Comment by flosse** [comment]
@joachifm I had not time to fix it.... using VirtualBox + Ubuntu just works ;-)

**Comment by joachifm** [comment]
@flosse fair enough. Can this be closed?

**Comment by joachifm** [comment]
Closing in favour of https://github.com/NixOS/nixpkgs/pull/17060

**Pull request closed without merging**
