### PR TITLE
python3Packages.ldaptor: 20.1.1 -> 21.2.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
Support for Python 3.9

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 114733` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.ldaptor</li>
    <li>python38Packages.ldaptor</li>
    <li>python39Packages.ldaptor</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package built (see https://github.com/NixOS/nixpkgs/pull/114733#issuecomment-787768596)
- [ ] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-114733/results/python38Packages.ldaptor/lib/python3.8/site-packages]$ python
Python 3.7.10 (default, Feb 16 2021, 02:11:57) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldaptor
>>> print(ldaptor.__version__)
21.2.0
```

Update looks good to me.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114733` at 819af33b run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/ceccb14a0773f9bfb3195806afa8baff">python37Packages.ldaptor</a></li></li>
    <li><a href="https://gist.github.com/5cf2b40a86eacc33164d2c0af78a1604">python38Packages.ldaptor</a></li></li>
    <li><a href="https://gist.github.com/51d3a553c7777f409d64687f431693b2">python39Packages.ldaptor</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/ldaptor/default.nix:34:3:
```
   |
34 |   meta = {
   |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `pythonAtLeast`.
Near pkgs/development/python-modules/ldaptor/default.nix:11:3:
```
   |
11 | , pythonAtLeast
   |   ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 114733` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.ldaptor</li>
<li>python38Packages.ldaptor</li>
<li>python39Packages.ldaptor</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
python37Packages.ldaptor:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/ldaptor/default.nix:33:3:

```
   |
33 |   meta = {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python38Packages.ldaptor:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/ldaptor/default.nix:33:3:

```
   |
33 |   meta = {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python39Packages.ldaptor:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/ldaptor/default.nix:33:3:

```
   |
33 |   meta = {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 114733` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.ldaptor</li>
<li>python38Packages.ldaptor</li>
<li>python39Packages.ldaptor</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
python37Packages.ldaptor:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/ldaptor/default.nix:33:3:

```
   |
33 |   meta = {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python38Packages.ldaptor:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/ldaptor/default.nix:33:3:

```
   |
33 |   meta = {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python39Packages.ldaptor:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/ldaptor/default.nix:33:3:

```
   |
33 |   meta = {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
</details>

**Pull request merged**
