### PR TITLE
pkgs/development/compilers: stdenv.lib -> lib

### PR DESCRIPTION
**Pull request by siraben**
###### Motivation for this change
Part of #108938

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
for verifying these changes don't cause regressions, do you mind doing:
```
TMPDIR=$(mktemp -d)
nix-instantiate --readonly-mode --eval --strict --show-trace --json ./maintainers/scripts/find-tarballs.nix --arg expr 'import ./maintainers/scripts/all-tarballs.nix' > $TMPDIR/tarballs.json
```

**Comment by jonringer** [comment]
We had a channel blocker due to a deeply nested lib. https://hydra.nixos.org/build/135415084/nixlog/106

it was fixed in https://github.com/NixOS/nixpkgs/commit/59863dc3d7d549e853d9cfe705fe0ea975284eaa

**Comment by siraben** [comment]
> for verifying these changes don't cause regressions, do you mind doing:
> 
> ```
> TMPDIR=$(mktemp -d)
> nix-instantiate --readonly-mode --eval --strict --show-trace --json ./maintainers/scripts/find-tarballs.nix --arg expr 'import ./maintainers/scripts/all-tarballs.nix' > $TMPDIR/tarballs.json
> ```

Thanks, I'm using this to find eval errors in my autofixing script now.

**Comment by siraben** [comment]
@jonringer please merge

**Comment by siraben** [comment]
@SuperSandro2000 rebuild 0

**Comment by jonringer** [comment]
sorry, I logged off for the day when you mentioned me :)

**Pull request merged**
