### PR TITLE
syslog-ng: make sure the service activates

### LINKED ISSUE #20153: systemd syslog-ng service fails to activate
I'm upgrading my systems from NixOS 16.03 to 16.09 and I'm trying to get syslog-ng working again. It's currently configured as:

```nix
{ syslog-ng.enable = true; }
```

The issue is that systemd is not noticing that syslog-ng has started:

```
Nov 04 12:47:08 mymachine systemd[1]: syslog-ng.service: Start operation timed out. Terminating.
Nov 04 12:47:08 mymachine systemd[1]: Failed to start syslog-ng daemon.
Nov 04 12:47:08 mymachine systemd[1]: syslog-ng.service: Unit entered failed state.
Nov 04 12:47:08 mymachine systemd[1]: syslog-ng.service: Failed with result 'timeout'.
Nov 04 12:47:08 mymachine systemd[1]: syslog-ng.service: Service hold-off time over, scheduling restart.
```

I do see that syslog-ng is running:

```
# ps -AH a | grep syslog
/nix/store/kag473gb3w8zaqw09qkgsjg2qn4ra5zc-syslog-ng-3.6.2/sbin/syslog-ng --foreground --module-path=/nix/store/kag473gb3w8zaqw09qkgsjg2qn4ra5zc-syslog-ng-3.6.2/lib/syslog-ng --cfgfile=/nix/store/8f9npiv1fyc487haxj0ff957ag7zqzld-syslog-ng.conf --control=/run/syslog-ng/syslog-ng.ctl --persist-file=/var/syslog-ng/syslog-ng.persist --pidfile=/run/syslog-ng/syslog-ng.pid
```

Note that the systemd syslog-ng service is [configured](https://github.com/NixOS/nixpkgs/blob/release-16.09/nixos/modules/services/logging/syslog-ng.nix#L87) with `Type = "notify";` This [means](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=) that syslog-ng should notify systemd when it has started up. My current hypotheses is that with the systemd upgrade to 231 something in the notification protocol has changed causing the syslog-ng notification to fail.

### PR DESCRIPTION
**Pull request by basvandijk**
Fixes #20153.

This is based on `release-16.09` because that's where I noticed the problem and where I tested this patch.

### CODE REVIEW

**Comment by fpletz** [comment]
The root cause of this is that syslog-ng doesn't find systemd anymore so it can notify system. From the configure output:

```
checking for libsystemd_daemon... no
```

**Comment by fpletz** [comment]
Our syslog-ng is fairly old: 3.6.2. Systemd changed to a monolithic libsystemd in 209 which was supported in syslog-ng in 3.7.1. The current syslog-ng is 3.8.1.

I'm preparing an upgrade which we probably should also port to 16.09.

cc maintainer @rickynils

**Comment by basvandijk** [comment]
@fpletz thanks for investigating! 

I'm looking forward to your syslog-ng upgrade in 16.09!

**Comment by basvandijk** [comment]
Hi @fpletz, did you do any work on the syslog-ng upgrade?

**Comment by fpletz** [comment]
@basvandijk Thanks for the reminder. Sorry, I forgot about this because I wanted to do more tests before pushing.

I've assigned myself to #20153 and will take care of it in the next few days.

**Comment by basvandijk** [comment]
@fpletz no problem, thanks and no rush!

**Pull request closed without merging**
