### PR TITLE
python: Add support for installing Python eggs

### PR DESCRIPTION
**Pull request by adisbladis**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @andir

### CODE REVIEW

**Comment by FRidh** [comment]
woah, egg's, that's prehistoric? Do we really need it? Code looks good, nothing wrong with that, it just feels strange adding support for something that's completely out.

**Comment by adisbladis** [comment]
@FRidh I added it for poetry2nix to automatically do the right thing when it encounters an egg. There are legit cases where an egg might be the only option.

**Review by FRidh — APPROVED** [review]
Good enough reason.

**Comment by FRidh** [comment]
Ah wait, the manual needs to include these. THere's a list of hooks.

**Comment by adisbladis** [comment]
I've added docs :)

**Pull request merged**
