### PR TITLE
gdm service module: make /run/gdm/.config/monitors.xml configurable

### PR DESCRIPTION
**Pull request by justinkb**
###### Description of changes

With this change, users can for example copy over their $HOME/.config/monitors.xml configuration, for example as created by gnome-control-center's display applet, so that their monitor setup, such as positions and scaling and refresh rates in the gdm screen are the same as when logged in.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — COMMENTED** [review]
This was previously proposed in https://github.com/NixOS/nixpkgs/pull/107850. Sorry, I still do not see a benefit over just using `systemd.tmpfiles.rules` directly.

**Comment by justinkb** [comment]
I will close the issue and use the functionality you suggested instead. I searched inside open issues for this issue... it didn't occur to me someone might have proposed it already but the issue being closed ;-)

**Comment by nodupe** [comment]
I wish this would have been merged, it would have made my life easier. :)

**Comment by pshirshov** [comment]
For me the benefits are obvious - one won't have to figure out what exactly needs to be written into the rules. There are many way less useful options in nixpkgs.

**Pull request closed without merging**
