### PR TITLE
batman-adv: 2023.1 -> 2023.2

### PR DESCRIPTION
**Pull request by philiptaron**
## Description of changes

Update batman-adv to 2023.2. From https://www.open-mesh.org/news/113:

      batman-adv

          support latest kernels (4.14 - 6.5)
          bugs squashed:
              avoid potential invalid memory access when processing ELP/OGM2 packets
              drop pending DAT worker when interface shuts down
              inform network stack about automatically adjusted MTUs
              keep user defined MTU limit when MTU is recalculated
              fix packet memory leak when sending OGM2 via inactive interfaces
              fix TT memory leak for roamed back clients

      alfred

          receive data with valid source on unix sock without active interface

      Happy routing,

      The B.A.T.M.A.N. team

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by philiptaron** [comment]
Hmmm, I meant for there to be one commit, not two. Evidently I don't know how to squash commits effectively yet.

**Comment by philiptaron** [comment]
@fpletz @mweinelt, you're the two maintainers. 💌

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 262984` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>alfred</li>
    <li>batctl</li>
    <li>linuxKernel.packages.linux_4_19.batman_adv</li>
    <li>linuxPackages_4_19_hardened.batman_adv (linuxKernel.packages.linux_4_19_hardened.batman_adv)</li>
    <li>linuxKernel.packages.linux_5_10.batman_adv</li>
    <li>linuxPackages_5_10_hardened.batman_adv (linuxKernel.packages.linux_5_10_hardened.batman_adv)</li>
    <li>linuxKernel.packages.linux_5_15.batman_adv</li>
    <li>linuxPackages_5_15_hardened.batman_adv (linuxKernel.packages.linux_5_15_hardened.batman_adv)</li>
    <li>linuxKernel.packages.linux_5_4.batman_adv</li>
    <li>linuxPackages_5_4_hardened.batman_adv (linuxKernel.packages.linux_5_4_hardened.batman_adv)</li>
    <li>linuxPackages.batman_adv (linuxKernel.packages.linux_6_1.batman_adv)</li>
    <li>linuxPackages_hardened.batman_adv (linuxPackages_6_1_hardened.batman_adv)</li>
    <li>linuxPackages_latest.batman_adv (linuxKernel.packages.linux_6_5.batman_adv)</li>
    <li>linuxPackages_6_5_hardened.batman_adv (linuxKernel.packages.linux_6_5_hardened.batman_adv)</li>
    <li>linuxPackages_latest-libre.batman_adv (linuxKernel.packages.linux_latest_libre.batman_adv)</li>
    <li>linuxPackages-libre.batman_adv (linuxKernel.packages.linux_libre.batman_adv)</li>
    <li>linuxPackages_lqx.batman_adv (linuxKernel.packages.linux_lqx.batman_adv)</li>
    <li>linuxPackages_testing_bcachefs.batman_adv (linuxKernel.packages.linux_testing_bcachefs.batman_adv)</li>
    <li>linuxPackages_xanmod.batman_adv (linuxKernel.packages.linux_xanmod.batman_adv)</li>
    <li>linuxPackages_xanmod_latest.batman_adv (linuxKernel.packages.linux_xanmod_latest.batman_adv ,linuxPackages_xanmod_stable.batman_adv)</li>
    <li>linuxPackages_zen.batman_adv (linuxKernel.packages.linux_zen.batman_adv)</li>
  </ul>
</details>

**Comment by philiptaron** [comment]
Thanks, @mweinelt !

**Pull request merged**
