### PR TITLE
mkPythonDerivation: obey a dontWrapPythonPrograms attribute

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
85a87f5155f66dbdfcdb9869f4bd4f2a10fe8e2c broke python packages not wanting *all* potential "programs" wrapped with `wrapPythonPrograms` but also not wanting to have to replace/disable the whole `fixupPhase`. Notably django.

I propose borrowing a leaf out of `mkDerivation`'s book and making `mkPythonDerivation` obey a `dontWrapPythonPrograms` flag.

This includes a followup commit adding the flag to django packages to fix them.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by risicle** [comment]
The two failures appear to be because of log limits exceeding again - it would be nice if some more people could do some local builds of this because I'm having trouble building current `python35Packages.django_hijack` with-or-without this patch and would like to to make sure it's a totally independent failure.

**Comment by FRidh** [comment]
@risicle note that, if you want to limit wrapping to only `$out/bin`, then that will soon be the case since I plan to push aa86d9fa7a93023f6c54f45631505375dc628b91.

**Comment by risicle** [comment]
Oh man. Perhaps this is best ignored then. It's a potentially useful feature, but adding a feature-with-no-users feels more like noise.

**Comment by FRidh** [comment]
I've pushed 45ac7700fa6aeedc088124aab863a43d476512b8 to master because I think it will come to use at some point.

**Comment by FRidh** [comment]
and also c10af9e744c91dff1ccc07a52a0b57d1e4d339f3 so we don't need the other commit anymore.

**Comment by risicle** [comment]
ok fair enough

**Pull request closed without merging**
