### PR TITLE
aws-iam-authenticator: 0.5.2 -> 0.5.3

### PR DESCRIPTION
**Pull request by stig**
###### Motivation for this change

Version bump. For reasons I'm not entirely clear about 0.5.2 does not work for me, but 0.5.3 does.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stig** [comment]
I've ticked `"Tested compilation of all pkgs that depend on this change using nix-shell -p nixpkgs-review --run "nixpkgs-review wip"` because there doesn't appear to be any dependent packages.

**Comment by srhb** [comment]
Thanks!

Looks to me like there's some inconsistent vendoring going on though, maybe upstream messed up their vendor dir/go.mod?

```
go: inconsistent vendoring in /build/source:
        github.com/aws/aws-sdk-go@v1.37.1: is explicitly required in go.mod, but vendor/modules.txt indicates github.com/aws/aws-sdk-go@v1.30.0

        To ignore the vendor directory, use -mod=readonly or -mod=mod.
        To sync the vendor directory, run:
                go mod vendor
error: builder for '/nix/store/nbvq1cmkw4qcxgrq0d9glzyizyia8g68-aws-iam-authenticator-0.5.3.drv' failed with exit code 1;
       last 10 log lines:
       > patching sources
       > configuring
       > building
       > Building subPackage ./cmd/aws-iam-authenticator
       > go: inconsistent vendoring in /build/source:
       >    github.com/aws/aws-sdk-go@v1.37.1: is explicitly required in go.mod, but vendor/modules.txt indicates github.com/aws/aws-sdk-go@v1.30.0
       >
       >       To ignore the vendor directory, use -mod=readonly or -mod=mod.
       >         To sync the vendor directory, run:
       >             go mod vendor
 ```

**Comment by stig** [comment]
Thanks for the review @srhb! 

This is my first time contributing to nixpkgs, and I don't know Go at all, so could do with some handholding. I tried adding `-mod=readonly` / `-mod=mod` to `buildFlagsArray`, but it didn't appear to do any good. Do you have a suggestion for how to proceed?

**Comment by srhb** [comment]
I'm happy to hand-hold -- and thanks for the bump! While we wait for clarification upstream, perhaps you could change the commit message according to the shortguide :)

https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

**Comment by srhb** [comment]
Happy to hand-hold later today! :)

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126335` at f65e459d run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/74394042f0ebeda8e6e06f57dba5ee4e">aws-iam-authenticator</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by srhb** [comment]
I think the easiest solution right now is to force go mod to revendor:

```
# Upstream has inconsistent vendoring, see <issue link>
deleteVendor = true;
vendorSha256 = "0000000000000000000000000000000000000000000000000000";
```

Then adjust vendorSha256 according to the build error.

**Comment by stig** [comment]
@srhb Wow, thank you - what a great first experience contributing to this project :-)

**Pull request merged**
