### PR TITLE
ldc: 1.11.0 -> 1.12.0

### PR DESCRIPTION
**Pull request by lionello**
###### Motivation for this change

Update to latest official release

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lionello** [comment]
@ThomasMader Need your comment on those commented lines, what's their purpose?

**Comment by ThomasMader** [comment]
First of all, thanks for your interest in D and ldc.

This entire optional String block removed the variadic.d test case in the dmd testsuite for the bootstrap version of ldc.
Maybe it's not needed anymore because something was fixed in ldc 0.17.6. You could try to reproduce the problem on your machine by switching back to 0.17.5 without removing the variadic.d testcase.
In case this doesn't make any problems anymore, this entire optional block can be removed.
The comment above was just to show the error message that occurred.

There are some "Can be removed" or "TODO" comments around which should be fixable now with this new version too. Please remove those fixes too as they were fixed upstream.

**Comment by ThomasMader** [comment]
I just realized that the testing/check phase is disabled for the bootstrap version at the moment.
I introduced it with https://github.com/NixOS/nixpkgs/commit/f4f488de21c971c1280fff11b8fe217fa8ad015e#diff-a9931c506e99f6acd6420fb8c119b55cR161
I did it because I figured that checking the bootstrapping version has not much of a value and is just prolonging the build time. It should be enough of a test If it builds ldc correctly and all tests are successful there.
I should have removed the code for it with that commit.

In that case you can just leave your patch as is or make the changes, I leave it up to you. If you don't want to make the cleanup I will do it afterwards.
Let me know when you are ready for merging, I will trigger a GrahamcOfBorg build for testing.

**Comment by xeji** [comment]
closing in favor of #52964

**Pull request closed without merging**
