### PR TITLE
pythonPackages.cgkit: init at 2.0.0

### PR DESCRIPTION
**Pull request by expipiplus1**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
@expipiplus1 cgkit is an old package that is not maintained anymore. Even so, it can still be useful. 
I'm fine with adding this as long as you maintain this package (thus add yourself as maintainer) and if a note is added in the source stating the package is no longer maintained and can be removed when it is broken.

**Comment by expipiplus1** [comment]
@FRidh I'm afraid that I'm not well versed in Python to act as a maintainer for a package; the only interest I have in this package is compiling someone else's code which depends on `cgkit`. If being able to program in Python isn't a requirement for maintainership then I could do it, although I fear that the only maintenance I'd be able to do would be to remove the package.

**Comment by FRidh** [comment]
@expipiplus1 considering you packaged this correctly it will be fine.

**Comment by expipiplus1** [comment]
Ok, that's done.

**Comment by FRidh** [comment]
@expipiplus1 you will have to add yourself to lib.maintainers. See https://github.com/NixOS/nixpkgs/blob/master/lib/maintainers.nix

**Comment by expipiplus1** [comment]
Ah, pushing new commits doesn't raise a notification.
Ping.

**Comment by FRidh** [comment]
Thanks

**Pull request merged**
