### PR TITLE
cimg,gmic,gmic-qt: 3.2.1 -> 3.2.2

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

I updated the three G'MIC packages (which required one upstream PR to fix gmic-qt) and made a few drive-by fixes

Changelog: https://discuss.pixls.us/t/on-the-road-to-3-3/34786 (notably includes a critical bug fix to enable mutexes for the command line tool when using parallel computing)

Drive-bys:
* Fix repo owner for cimg and gmic, since the repository was moved a while ago to GreycLab
* Remove unused args from packages
* Make gmic-qt use `stdenv.mkDerivation` instead of `qt5.mkDerivation` (see #180841, and this would also be a requirement to building with Qt6)

Upstream PR to fix CMakeLists: c-koi/gmic-qt#176

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

###### nixpkgs-review

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>cimg</li>
    <li>darktable</li>
    <li>gimp-with-plugins</li>
    <li>gimpPlugins.gmic</li>
    <li>gmic</li>
    <li>gmic-qt</li>
    <li>imgcat</li>
    <li>openroad</li>
    <li>phash</li>
    <li>photoprism</li>
  </ul>
</details>

### CODE REVIEW

**Comment by lilyinstarlight** [comment]
Also, given that both `gmic` and `gmic-qt` have no listed maintainers, should I just go ahead and add myself? I'm happy to adopt them (should I add myself to `cimg` too since the three are tightly coupled?)

**Comment by lilyinstarlight** [comment]
I made a small license fix and added myself as maintainer to all three. Let me know if this is problem

**Review by AndersonTorres — APPROVED** [review]

**Review by Zahrun — APPROVED** [review]
Built and tested ✓
Can we backport this to 22.11 since the update includes a critical bug fix?
Thank you!

**Comment by lilyinstarlight** [comment]
> Can we backport this to 22.11 since the update includes a critical bug fix?

Actually I just noticed 22.11 is still on G'MIC 3.1 (and so 3.1 -> 3.2 would be a bigger upgrade than 3.2.1 -> 3.2.2). I don't see any specific mentions of breaking or incompatible changes at <https://discuss.pixls.us/t/release-of-gmic-3-2/30567>, though, so I think it can still be a candidate for backporting

I'll make a manual backport shortly

**Comment by lilyinstarlight** [comment]
So this might not be backportable. `gmic-qt-krita` was removed upstream in 3.2.0 so this actually would be a breaking change against 22.11

Do you think you could just use `gmic` from nixos-unstable until 23.05 @Zahrun?

**Comment by Zahrun** [comment]
Sure, no problem, thank you!
Let's wait for 23.05. I guess if anyone faces the crash, they will find this related issues.
Fetching from unstable works well.

**Pull request merged**
