### PR TITLE
echidna: fix build on aarch64-darwin

### PR DESCRIPTION
**Pull request by alexfmpe**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hellwolf** [comment]
Hi,

Thanks for the update!

It seems it changed the indentation completely, was that intentional? I tried to run `nixfmt`, it seems accepting both versions (yours and the one before). If not necessary, I think we shouldn't create such a big formating change.

**Comment by alexfmpe** [comment]
> It seems it changed the indentation completely, was that intentional? I tried to run nixfmt, it seems accepting both versions (yours and the one before). If not necessary, I think we shouldn't create such a big formating change.

Well, I saw CI fail on nixfmt so ran the provided command which produced the second commit.
I don't have an opinion myself either way.

**Comment by hellwolf** [comment]
Oh, I see, I used `nixfmt-rfc-style` and ran it when I edited previous file.

Did you also use `nixfmt-rfc-style`, and how did you run it?

**Comment by alexfmpe** [comment]
I did `nix-shell --run "nixfmt"` on the root. This is the message I saw

https://github.com/NixOS/nixpkgs/blob/cb10e910778f8509236cb11603542cda425e27e1/.github/workflows/check-nix-format.yml#L83-L88

**Comment by hellwolf** [comment]
I can't reproduce it. When I run `nixfmt` to the old file, nothing changed. I am using latest nixpkgs-unstable `nixfmt-rfc-style`.

I am starting to suspect that the ci workflow is using a different version of `nixfmt`, as suggested by these comments:

```
        run: |
          # pin to a commit from nixpkgs-unstable to avoid e.g. building nixfmt
          # from staging
          # This should not be a URL, because it would allow PRs to run arbitrary code in CI!
          rev=$(jq -r .rev ci/pinned-nixpkgs.json)
          echo "url=https://github.com/NixOS/nixpkgs/archive/$rev.tar.gz" >> "$GITHUB_ENV"
```

Anyways, I won't hold this up for this thing. Let's just merge the fix!

**Review by hellwolf — APPROVED** [review]

**Comment by maralorn** [comment]
Thx

**Pull request merged**
