### PR TITLE
mp4v2: 4.1.3 -> 4.1.5

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
Thank you.

Indeed a couple of minor releases in several days.

There is a report with dependency compilation/use trouble:
https://github.com/TechSmith/mp4v2/issues/47,

So let us check a couple of those.

**Comment by Anton-Latukha** [comment]
@GrahamcOfBorg build mixxx

**Comment by Anton-Latukha** [comment]
Packages have trouble finding dev files, since you are at it - please, try to add split outputs to the package:
```
outputs = [ "bin" "dev" "out" "doc" ];
```
and see what sticks(populates).

At least from https://packages.debian.org/stretch/amd64/libmp4v2-dev/download it seems that `dev` output is there.

**Comment by Anton-Latukha** [comment]
Or we can merge as is, and I would attend further.

**Comment by marsam** [comment]
>try to add split outputs to the package:

Sure, I added `outputs = [ "out" "dev" "lib" ];` because `doc` doesn't seem to work

@GrahamcOfBorg build faac

**Comment by marsam** [comment]
@GrahamcOfBorg build mixxx

**Comment by Anton-Latukha** [comment]
Now we fixed the build error in `mixxx`, and so now it falls under unresolved dependencies - which is `mixxx` package config territory.

**Comment by Anton-Latukha** [comment]
I consider this good enough.

**Review by Anton-Latukha — APPROVED** [review]

**Comment by Anton-Latukha** [comment]
@GrahamcOfBorg build mp4v2

**Comment by marsam** [comment]
Looking at this again, it breaks cmus and mixxx. Closing this PR for now, sorry for the noise
I pushed the darwin fix in https://github.com/NixOS/nixpkgs/commit/b60acf29f14da4151101c839129116919b0e219c

**Comment by Anton-Latukha** [comment]
This was only a 25 days ago, feels like millennia.

With all this seems would wait for the 4.1.6.

I while ago rebased this fossil to the maintained fork, but most Linux distros would not. 
But again - this is a half-alive fork of a fossil package.

If most distros do not use the fork - we updating would probably hit a difference and would have a wall with compiling the dependent packages.

If bot would not update it - I check lesser packages I have like 2 times a year.

**Pull request closed without merging**
