### PR TITLE
systemd: pull OOMPolicy patches for sessions

### PR DESCRIPTION
**Pull request by pennae**
###### Description of changes

systemd 252 will kill an entire user session if a single process in it is oom-killed. this is obviously not great, and upstream has fixed this since.

fixes #210680

currently running these patches on our system (applied to `systemd.package` on top of its other patches) and they seem to work fine.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by flokli — CHANGES_REQUESTED** [review]
Please ping systemd-stable to backport https://github.com/systemd/systemd/pull/25385.

We usually don't backport non-NixOS-specific patches manually, but instead make sure they end up in systemd-stable.

**Comment by flokli** [comment]
Also, I tried reading through the upstream issue report (which unfortunately was very heated tone-wise :-/)

The way I understand this, this is only a problem for desktop environments that don't open different applications in different (sub-)scopes, and those that do should be fine?

On my system (Gnome), I do have separate scopes for each application, so from my understanding, slack eating my memory shouldnt cause firefox to be killed as well?

```shell
$ systemd-cgls
[...]
│   │ │ ├─app-gnome-firefox-485810.scope (#175290)
│   │ │ │ → user.xdg.inactive-since: 1746440862781
│   │ │ │ ├─485810 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─485903 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─485964 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─486000 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─486078 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─486081 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─486724 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─486752 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─486754 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─487269 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─487829 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─487951 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─488186 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ ├─488225 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ │ └─488289 /nix/store/qxmgaglpgcp3iapsnfzjfwc62pvaqkjh-firefox-108.0.1/>
│   │ │ ├─app-gnome-slack-1747613.scope (#114952)
│   │ │ │ → user.xdg.inactive-since: 1745490990564
│   │ │ │ ├─1747613 /nix/store/02g9q08rxlfs21hl6cxabp91wmrp60wv-slack-4.29.149/>
│   │ │ │ ├─1747644 /nix/store/02g9q08rxlfs21hl6cxabp91wmrp60wv-slack-4.29.149/>
│   │ │ │ ├─1747646 /nix/store/02g9q08rxlfs21hl6cxabp91wmrp60wv-slack-4.29.149/>
│   │ │ │ ├─1747654 /nix/store/02g9q08rxlfs21hl6cxabp91wmrp60wv-slack-4.29.149/>
│   │ │ │ ├─1747702 /nix/store/02g9q08rxlfs21hl6cxabp91wmrp60wv-slack-4.29.149/>
│   │ │ │ ├─1747720 /nix/store/02g9q08rxlfs21hl6cxabp91wmrp60wv-slack-4.29.149/>
│   │ │ │ ├─1747722 /nix/store/02g9q08rxlfs21hl6cxabp91wmrp60wv-slack-4.29.149/>
│   │ │ │ ├─1747764 /nix/store/02g9q08rxlfs21hl6cxabp91wmrp60wv-slack-4.29.149/>
│   │ │ │ └─1747856 /nix/store/02g9q08rxlfs21hl6cxabp91wmrp60wv-slack-4.29.149/>
```

**Comment by flokli** [comment]
Alright, thanks for clarifying. Maybe add this context to the backport request for systemd-stable.

Considering NixOS only has 252 on the unstable channel, and it's not a regression in the stable release, there's no immediate rush. I still think it's a good candidate for a upstream systemd-stable backport.

Too bad the original issue reporter [made no friends with upstream due to using bad language](https://github.com/systemd/systemd/issues/25376#issuecomment-1325435228), but I don't think this is a reason for simply not backporting to systemd-stable.

**Review by Mic92 — APPROVED** [review]
tested on my laptop

**Comment by flokli** [comment]
Upstream pulled the changes into [systemd-stable](https://github.com/systemd/systemd-stable), we now just need to wait for a new stable release tag, and then this PR can be updated to just use `v252.5`.

**Pull request closed without merging**
