### PR TITLE
bip: 0.8.9 -> 0.9.3

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

#269713

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by kirillrdy — APPROVED** [review]
Result of `nixpkgs-review pr 271248` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>bip</li>
    <li>bip.doc</li>
    <li>bip.man</li>
  </ul>
</details>

at least it runs

**Comment by Aleksanaa** [comment]
@kirillrdy are you testing its functionality? I've written a patch but don't know if it fully works.

```patch
diff --git a/src/connection.c b/src/connection.c
index 0a138eb..70d7d3a 100644
--- a/src/connection.c
+++ b/src/connection.c
@@ -1171,32 +1171,37 @@ static connection_t *connection_init(int anti_flood, int ssl, time_t timeout,
 static int ctx_set_dh(SSL_CTX *ctx)
 {
 	/* Return ephemeral DH parameters. */
-	DH *dh = NULL;
-	FILE *f;
+	EVP_PKEY* dh;
+	BIO *f;
 	long ret;
+	unsigned long error;
 
-	if ((f = fopen(conf_client_dh_file, "r")) == NULL) {
+	if ((f = BIO_new_file(conf_client_dh_file, "r")) == NULL) {
 		mylog(LOG_ERROR, "Unable to open DH parameters (%s): %s",
 		      conf_client_dh_file, strerror(errno));
 		return 0;
 	}
 
-	dh = PEM_read_DHparams(f, NULL, NULL, NULL);
-	fclose(f);
-
-	if (dh == NULL) {
-		mylog(LOG_ERROR, "Could not parse DH parameters from: %s",
-		      conf_client_dh_file);
-		return 0;
+	if (f) {
+		dh = EVP_PKEY_new();
+		if (!PEM_read_bio_Parameters(f, &dh)) {
+			BIO_free(f);
+			while ((error = ERR_get_error()))
+        mylog(LOG_ERROR, "SSL: %s", ERR_error_string(error, NULL));
+			mylog(LOG_ERROR, "Could not parse DH parameters from: %s",
+				  conf_client_dh_file);
+      return 0;
+		}
+		BIO_free(f);
 	}
 
 // SSL crap: passing argument 3 of ‘SSL_CTX_ctrl’ with different width due to
 // prototype
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wtraditional-conversion"
-	ret = SSL_CTX_set_tmp_dh(ctx, dh);
+	ret = SSL_CTX_set0_tmp_dh_pkey(ctx, dh);
 #pragma GCC diagnostic pop
-	DH_free(dh);
+	EVP_PKEY_free(dh);
 
 	if (ret != 1) {
 		mylog(LOG_ERROR, "Unable to set DH parameters: %s",

```

**Comment by kirillrdy** [comment]
> @kirillrdy are you testing its functionality? I've written a patch but don't know if it fully works.
> 
> ```diff
> diff --git a/src/connection.c b/src/connection.c
> index 0a138eb..70d7d3a 100644
> --- a/src/connection.c
> +++ b/src/connection.c
> @@ -1171,32 +1171,37 @@ static connection_t *connection_init(int anti_flood, int ssl, time_t timeout,
>  static int ctx_set_dh(SSL_CTX *ctx)
>  {
>  	/* Return ephemeral DH parameters. */
> -	DH *dh = NULL;
> -	FILE *f;
> +	EVP_PKEY* dh;
> +	BIO *f;
>  	long ret;
> +	unsigned long error;
>  
> -	if ((f = fopen(conf_client_dh_file, "r")) == NULL) {
> +	if ((f = BIO_new_file(conf_client_dh_file, "r")) == NULL) {
>  		mylog(LOG_ERROR, "Unable to open DH parameters (%s): %s",
>  		      conf_client_dh_file, strerror(errno));
>  		return 0;
>  	}
>  
> -	dh = PEM_read_DHparams(f, NULL, NULL, NULL);
> -	fclose(f);
> -
> -	if (dh == NULL) {
> -		mylog(LOG_ERROR, "Could not parse DH parameters from: %s",
> -		      conf_client_dh_file);
> -		return 0;
> +	if (f) {
> +		dh = EVP_PKEY_new();
> +		if (!PEM_read_bio_Parameters(f, &dh)) {
> +			BIO_free(f);
> +			while ((error = ERR_get_error()))
> +        mylog(LOG_ERROR, "SSL: %s", ERR_error_string(error, NULL));
> +			mylog(LOG_ERROR, "Could not parse DH parameters from: %s",
> +				  conf_client_dh_file);
> +      return 0;
> +		}
> +		BIO_free(f);
>  	}
>  
>  // SSL crap: passing argument 3 of ‘SSL_CTX_ctrl’ with different width due to
>  // prototype
>  #pragma GCC diagnostic push
>  #pragma GCC diagnostic ignored "-Wtraditional-conversion"
> -	ret = SSL_CTX_set_tmp_dh(ctx, dh);
> +	ret = SSL_CTX_set0_tmp_dh_pkey(ctx, dh);
>  #pragma GCC diagnostic pop
> -	DH_free(dh);
> +	EVP_PKEY_free(dh);
>  
>  	if (ret != 1) {
>  		mylog(LOG_ERROR, "Unable to set DH parameters: %s",
> ```

sorry, I know almost nothing of bip. All I know its builds and runs ( executes :-) 

my interest is in removing openssl 1.1, but happy to test/help is anyway I can

**Comment by Aleksanaa** [comment]
me too. I just saw it and thought of I may need it in future 😄
Skipping deprecation error should work for openssl 3.0 for now. I'll take some time to test it tomorrow.

**Comment by Aleksanaa** [comment]
Anyway we can get this merged I think. This patch is too out of scope, and I really don’t know much about OpenSSL.

**Comment by Aleksanaa** [comment]
Anyway we can get this merged I think. This patch is too out of scope, and I really don’t know much about OpenSSL.

**Pull request merged**
