### PR TITLE
backport: python27Packages.soco: 0.18.1 -> 0.19, remove broken

### PR DESCRIPTION
**Pull request by minijackson**
###### Motivation for this change

Fixes the default build of `beets` in NixOS 20.03

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Also quickly tested `beets` with my local library, and the compilation of beets also contained a quite significant amount of tests ^^

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg  python38Packages.soco  python37Packages.soco

**Comment by worldofpeace** [comment]
@minijackson You need to use `-x` in the cherry-pick, per the backport guide.

**Comment by minijackson** [comment]
I wanted to cherry-pick the automated PR, but it didn't remove the `broken` status. Should I split it into 2 separate commits ?

**Comment by Mic92** [comment]
@minijackson you can use `git commit --amend` to also remove the unbroken flag.

**Comment by minijackson** [comment]
Done !

**Pull request merged**
