### PR TITLE
argo: 2.2.1 -> 2.3.0

### PR DESCRIPTION
**Pull request by thundergolfer**
##### Motivation for this change

Make Argo's `2.3.0` available in Nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @groodt

### CODE REVIEW

**Comment by groodt** [comment]
@grahamcofborg build

**Comment by groodt** [comment]
@thundergolfer 
Can you change the title of the PR to: `argo: 2.2.1 -> 2.3.0`

Did you test this locally?

**Comment by Mic92** [comment]
I get an build error, when trying to build this: 
[argo.log](https://github.com/NixOS/nixpkgs/files/3639859/argo.log)

@GrahamcOfBorg build argo

**Comment by thundergolfer** [comment]
@Mic92 

Confirm that `cd $(git rev-parse --show-toplevel) && nix-build -A argo` is showing me the same error: 

```
go/src/github.com/argoproj/argo/workflow/artifacts/hdfs/util.go:21:26: cannot use krbClient (type *"gopkg.in/jcmturner/gokrb5.v5/client".Client) as type *"github.com/colinmarc/hdfs/vendor/gopkg.in/jcmturner/gokrb5.v5/client".Client in assignment
builder for '/nix/store/wfpzhnc91l4mdk4jxz37y743nqqhpbhk-argo-2.3.0.drv' failed with exit code 1
```

I'm not familiar with this codebase so will need to take a bit of time to look into it.

**Comment by thundergolfer** [comment]
The problem is still present in `2.4.0-rc1`.

**Comment by Mic92** [comment]
Just a wild speculation: Did you run go2nix against master of argo or against the released version? Might be an incompatible dependency version.

**Comment by thundergolfer** [comment]
@Mic92 No it ran `dep2nix`, and ran it on the correct branch. 

I've since discovered that bumping `colinmarc/hdfs` in the `Gopkg.toml` to the next commit, which no longer vendors deps, fixes the issue.

I'll stick up a PR on argoproj/argo for that, but don't know why this is happening.

**Comment by groodt** [comment]
argo 2.4.0 has been released and it fixes the build issue. nixpkgs bump here:
https://github.com/NixOS/nixpkgs/pull/70672

**Comment by thundergolfer** [comment]
Closing in favour of https://github.com/NixOS/nixpkgs/pull/70672

**Pull request closed without merging**
