### PR TITLE
pantheon.evince: init

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

Related change:

- https://github.com/elementary/evince/pull/21

Sorry for not noticing this before GNOME 41 packaging starts, maybe I should draft this for now?

FYI, we will have similar PR for file-roller soon, see:

- https://github.com/elementary/fileroller/issues/3

`pantheon.epiphany` has already been added in #130380, I will also test the compatibility for that later (update: LGTM)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
@davidak can you reproduce issue repeatedly? What happens when you try to apply the following patch:

```
git clone https://gitlab.gnome.org/GNOME/tracker.git
cd tracker/
git checkout 3.2.0
git apply <(curl -L https://gist.github.com/jtojnar/dfa8212436631ecfd63d2a8f716b7964/raw/45cfb2093c7b5f4fd1f545670e352d6f1e091eb7/tracker-test.patch)
```

```
diff --git a/pkgs/development/libraries/tracker/default.nix b/pkgs/development/libraries/tracker/default.nix
index 39ac21b7ad6..ae9b25d3579 100644
--- a/pkgs/development/libraries/tracker/default.nix
+++ b/pkgs/development/libraries/tracker/default.nix
@@ -32,12 +32,9 @@ stdenv.mkDerivation rec {
   pname = "tracker";
   version = "3.2.0";
 
-  outputs = [ "out" "dev" "devdoc" ];
+  outputs = [ "out" "dev" /*"devdoc"*/ ];
 
-  src = fetchurl {
-    url = "mirror://gnome/sources/${pname}/${lib.versions.majorMinor version}/${pname}-${version}.tar.xz";
-    sha256 = "sha256-8RelKHXUpNCceqmT+Mio0GRo1dz7FT642qUesThEUTo=";
-  };
+  src = /home/jtojnar/Projects/tracker;
 
   patches = [
     (substituteAll {
@@ -81,7 +78,7 @@ stdenv.mkDerivation rec {
   ];
 
   mesonFlags = [
-    "-Ddocs=true"
+    "-Ddocs=false"
   ];
 
   doCheck = true;
```

**Comment by jtojnar** [comment]
Opened an issue upstream: https://gitlab.gnome.org/GNOME/tracker/-/issues/332

**Comment by davidak** [comment]
Fix was merged.

@bobby285271 can you rebase?

**Comment by bobby285271** [comment]
Yeah the patch is for evince 40 and I just noticed that evince 41 is in master now.

It's 0:57 in UTC+8 and I will do this when I wake up :-)

**Review by jtojnar — COMMENTED** [review]
Mostly looks good, just few nits.

**Review by davidak — APPROVED** [review]
Change looks good

Builds, works

dark-mode is respected now

**Pull request merged**
