### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I assumed we'll want to recompile the CC wrapper (i.e. everything): https://github.com/NixOS/nixpkgs/commit/f3f7612a409e4ebbec634ab7f20e094f206d396a#r40248971

**Comment by FRidh** [comment]
Yes, I was waiting initially for it, but then read it wasn't done yet so decided to go ahead.

**Comment by vcunat** [comment]
Well, perhaps we'll still manage to add https://github.com/NixOS/nixpkgs/pull/92086 and #91746.

**Comment by FRidh** [comment]
@lovek323 gst-plugins-base is failing on staging-next. Could you have a look? https://hydra.nixos.org/build/123483856

**Comment by jtojnar** [comment]
That is the legacy gstreamer. Maybe this is a good time to mark it as broken as a first step in https://github.com/NixOS/nixpkgs/issues/39975

**Comment by FRidh** [comment]
It's a good way to motivate people to look into migrating if their application depends on it (transitively).

**Comment by vcunat** [comment]
Default `mono` [regressed](https://hydra.nixos.org/build/123524349), but I don't understand it.  It seems like some confusion in directory names:
```
...
AOT profiler data written to './../../class/lib/build-linux/csc.corlib.dll.aotprofile'
...
Cannot open assembly ',profile=./../../class/lib/build/csc.corlib.dll.aotprofile': No such file or directory.
```
/cc maintainers: @thoughtpolice @obadz @vrthra.

**Comment by jtojnar** [comment]
Right, looks like `qtModule` sets `setOutputFlags` to `false` by default:

https://github.com/NixOS/nixpkgs/blob/ffbbdf247a14808307ef558d71afca4ac364c795/pkgs/development/libraries/qt-5/qtModule.nix#L24

which we now respect. I guess we will need to revert https://github.com/NixOS/nixpkgs/commit/be1b22538a60e52987d238bb11f93043682b6e9a, or change it to use a separate `setCmakeOutputFlags` variable. I think the former makes more sense since CMake ignores unknown variables.

**Comment by vcunat** [comment]
In case you see more of these C syntax errors on lines `\#include`, they got triggered by the gnumake update.

**Comment by vcunat** [comment]
> Default `mono` [regressed](https://hydra.nixos.org/build/123524349) [...]

Now it builds since bb9f138f.

**Comment by vcunat** [comment]
Perhaps this ^^ multilib regression is insignificant enough to let it slide into the next staging-next iteration?  (unless you see a way how to fix it without rebuilding everything)

**Review by vcunat — APPROVED** [review]

**Comment by flokli** [comment]
@vcunat how's the status of this? Can we merge this and open another staging round?

Asking mostly because of https://github.com/NixOS/nixpkgs/pull/93128…

**Comment by vcunat** [comment]
This iteration had been merged in 377324ca.  I verified that `staging-next` still only contains merges from master in addition to master commits; I have no idea why GitHub hasn't closed this PR.

**Comment by vcunat** [comment]
Next iteration: #93465.

**Pull request closed without merging**
