### PR TITLE
glibc: 2.35-163 -> 2.35-218

### PR DESCRIPTION
**Pull request by trofi**
Among other things backport fix for gnu make-4.4 support:
  https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=2d7ed98add14f75041499ac189696c9bd3d757fe

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Potentially breaks a few timezone-related tests like `python310.twisted`:

```
twisted.trial.unittest.FailTest: '2006-06-29T23:00:00+0000' != '2006-06-30T00:00:00+0000'
- 2006-06-29T23:00:00+0000
?         ^^ ^^
+ 2006-06-30T00:00:00+0000
?         ^^ ^^
```

**Comment by trofi** [comment]
Abandoning in favour of less invasive https://github.com/NixOS/nixpkgs/pull/201936

**Comment by vcunat** [comment]
So, I've been unable to find any reference to the regression in `.twisted` tests.  It's triggered by glibc commit
https://sourceware.org/git/?p=glibc.git;a=commit;h=f6d4c1ac648c4ff8baad94500df0bb13108a4f79
(bisected, easy to revert atop latest 2.35-224)

Full failure log, for reference:
```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/nix/store/l2dwsswg8dd2ybqpxjy3a1iqsf5lj9d5-python3.10-twisted-22.10.0/lib/python3.10/site-packages/tw
isted/logger/test/test_format.py", line 251, in test_formatTimeDefault
    self.assertEqual(
  File "/nix/store/l2dwsswg8dd2ybqpxjy3a1iqsf5lj9d5-python3.10-twisted-22.10.0/lib/python3.10/site-packages/tw
isted/trial/_synctest.py", line 441, in assertEqual
    super().assertEqual(first, second, msg)
  File "/nix/store/xwz1n452s7913wj1338514lqzajmbgla-python3-3.10.8/lib/python3.10/unittest/case.py", line 845,
 in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/xwz1n452s7913wj1338514lqzajmbgla-python3-3.10.8/lib/python3.10/unittest/case.py", line 1226
, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: '2013-09-24T10:40:47+0000 [-#-] XYZZY\n' != '2013-09-24T11:40:47+0000 [-#-] XYZZY\n'
- 2013-09-24T10:40:47+0000 [-#-] XYZZY
?             ^
+ 2013-09-24T11:40:47+0000 [-#-] XYZZY
?             ^


twisted.logger.test.test_format.ClassicLogFormattingTests.test_formatTimeDefault
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/nix/store/l2dwsswg8dd2ybqpxjy3a1iqsf5lj9d5-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/logger/test/test_format.py", line 589, in test_eventAsTextTimestampOnly
    self.assertEqual(
  File "/nix/store/l2dwsswg8dd2ybqpxjy3a1iqsf5lj9d5-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/trial/_synctest.py", line 441, in assertEqual
    super().assertEqual(first, second, msg)
  File "/nix/store/xwz1n452s7913wj1338514lqzajmbgla-python3-3.10.8/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/xwz1n452s7913wj1338514lqzajmbgla-python3-3.10.8/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: '2013-09-24T10:40:47+0000 ABCD' != '2013-09-24T11:40:47+0000 ABCD'
- 2013-09-24T10:40:47+0000 ABCD
?             ^
+ 2013-09-24T11:40:47+0000 ABCD
?             ^


twisted.logger.test.test_format.EventAsTextTests.test_eventAsTextTimestampOnly
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/nix/store/l2dwsswg8dd2ybqpxjy3a1iqsf5lj9d5-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/logger/test/test_format.py", line 176, in test_formatTimeWithDefaultFormat
    testForTimeZone(
  File "/nix/store/l2dwsswg8dd2ybqpxjy3a1iqsf5lj9d5-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/logger/test/test_format.py", line 172, in testForTimeZone
    self.assertEqual(formatTime(localDST), expectedDST)
  File "/nix/store/l2dwsswg8dd2ybqpxjy3a1iqsf5lj9d5-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/trial/_synctest.py", line 441, in assertEqual
    super().assertEqual(first, second, msg)
  File "/nix/store/xwz1n452s7913wj1338514lqzajmbgla-python3-3.10.8/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/xwz1n452s7913wj1338514lqzajmbgla-python3-3.10.8/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: '2006-06-29T23:00:00+0000' != '2006-06-30T00:00:00+0000'
- 2006-06-29T23:00:00+0000
?         ^^ ^^
+ 2006-06-30T00:00:00+0000
?         ^^ ^^


twisted.logger.test.test_format.TimeFormattingTests.test_formatTimeWithDefaultFormat
-------------------------------------------------------------------------------
```
and the relevant source file:
 https://github.com/twisted/twisted/blob/twisted-22.10.0/src/twisted/logger/test/test_format.py

**Comment by vcunat** [comment]
https://github.com/NixOS/nixpkgs/pull/205133

**Comment by vcunat** [comment]
I forwarded the test issue upstream: https://github.com/twisted/twisted/issues/11786
I'd assume that soon we'll drop the revert and fix or skip these twisted tests instead.

**Pull request closed without merging**
