### PR TITLE
matrix-synapse: 1.85.1 -> 1.85.2

### PR DESCRIPTION
**Pull request by sumnerevans**
###### Description of changes

https://github.com/matrix-org/synapse/releases/tag/v1.85.2
Signed-off-by: Sumner Evans <me@sumnerevans.com>

###### Things done

Running on my server and it's working fine.

-----

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>matrix-synapse-plugins.matrix-synapse-ldap3</li>
    <li>matrix-synapse-plugins.matrix-synapse-ldap3.dist</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam.dist</li>
    <li>matrix-synapse-plugins.matrix-synapse-shared-secret-auth</li>
    <li>matrix-synapse-plugins.matrix-synapse-shared-secret-auth.dist</li>
    <li>matrix-synapse.dist</li>
  </ul>
</details>

-----

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@ofborg test matrix-synapse pantalaimon mjolnir appservice-irc

**Comment by mweinelt** [comment]
Tests are failing on aarch64-linux.

> FAILED (skips=83, errors=120, successes=2558)

**Review by Ma27 — APPROVED** [review]
This contains a bugfix for certain worker configurations, so I'd merge this now. Hydra seems to have built this fine and I can as well, so this is definitely a racy test. Perhaps they manage to fix the offending tests in the upcoming release, otherwise we should probably skip these as a workaround.

**Comment by mweinelt** [comment]
> Hydra seems to have built this fine 

Not on trunk-combined. Not on release-23.05.

https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.matrix-synapse.aarch64-linux
https://hydra.nixos.org/job/nixos/release-23.05/nixpkgs.matrix-synapse.aarch64-linux

**Comment by Ma27** [comment]
Ouch, thx for pointing that out. Taking a look tomorrow...

**Comment by Ma27** [comment]
-> https://github.com/NixOS/nixpkgs/pull/237379

I don't think the linked issue is related because it only applies to running single tests. However, for whatever reason on aarch64 we seem to have a notable timing issue, so I simply disabled parallelism there until upstream finds a fix.

**Pull request merged**
