### PR TITLE
qtscrcpy: switch to latest ffmpeg

### PR DESCRIPTION
**Pull request by Aleksanaa**
Per the request of https://github.com/NixOS/nixpkgs/pull/340257#issuecomment-2484225666. Tested and seems nothing broken.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — APPROVED** [review]
Thanks. I take it FFmpeg 7 fails? Do you have the error message?

**Comment by Aleksanaa** [comment]
> Thanks. I take it FFmpeg 7 fails? Do you have the error message?

No but the higher the upgrade, the more breaking changes there should be.

**Comment by emilazy** [comment]
We are trying to move away from these old FFmpeg versions entirely. Arch, for instance, ships FFmpeg 4 for compatibility with a few (mostly binary) packages, and FFmpeg 7, but no FFmpeg 6. Old versions should only be pinned where there is a compatibility issue and it is not possible to get a patch from upstream or another distro; please see the advice in `pkgs/development/libraries/ffmpeg/default.nix`. If it builds with just unversioned `ffmpeg`, that’s what it should use.

See also the prior work:

* https://github.com/NixOS/nixpkgs/pull/326618
* https://github.com/NixOS/nixpkgs/pull/336401

**Comment by emilazy** [comment]
This builds:

```patch
diff --git a/pkgs/by-name/qt/qtscrcpy/package.nix b/pkgs/by-name/qt/qtscrcpy/package.nix
index 88f13a04d0..88b6f36132 100644
--- a/pkgs/by-name/qt/qtscrcpy/package.nix
+++ b/pkgs/by-name/qt/qtscrcpy/package.nix
@@ -7,7 +7,7 @@
   libsForQt5,
   scrcpy,
   android-tools,
-  ffmpeg_4,
+  ffmpeg,
   makeDesktopItem,
   copyDesktopItems,
 }:
@@ -49,6 +49,8 @@
     substituteInPlace QtScrcpy/sndcpy/sndcpy.sh \
       --replace-fail 'ADB=./adb' "ADB=${lib.getExe' android-tools "adb"}" \
       --replace-fail 'SNDCPY_APK=sndcpy.apk' "SNDCPY_APK=$out/share/qtscrcpy/sndcpy.apk"
+    substituteInPlace QtScrcpy/QtScrcpyCore/src/device/decoder/decoder.cpp \
+      --replace-fail 'avcodec_close(m_codecCtx);' ""
   '';
 
   nativeBuildInputs = [
@@ -61,7 +63,7 @@
   buildInputs =
     [
       scrcpy
-      ffmpeg_4
+      ffmpeg
     ]
     ++ (with libsForQt5; [
       qtbase
```

The deprecated `avcodec_close` is unnecessary given the immediately following `avcodec_free_context` call. Since we’re already patching this a bunch it seems fine to me and better than pinning FFmpeg 6. Of course an actual `.patch` file would be better but that’s probably true of some of the existing `postPatch` already.

**Review by emilazy — APPROVED** [review]

**Pull request merged**
