### PR TITLE
modules/zabbix-agent: Improve examples

### PR DESCRIPTION
**Pull request by Jauchi**
###### Motivation for this change
Documentation for zabbix agent settings confused me, so I added better documentation to make sure it does not confuse anyone else.
For reference, this was discussed in #146291

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
@Jauchi please try rebase instead of merging master into your branch.

**Comment by Jauchi** [comment]
> @Jauchi please try rebase instead of merging master into your branch.
Sorry, I'm new to git...
The issue is the commits 8a21122 and 6647983, right?
That happened because I did `git pull` on my machine. So, instead of doing `git pull`, I should use `git rebase`?
I just found https://nixos.org/manual/nixpkgs/stable/#submitting-changes-making-patches but I made this change on my master branch (in the forked repo). Should I just start over with a new fork/pull request, or does that cause unnecessary work on your side?
I also don't see a way to remove commits from the pull request...

**Comment by aanderse** [comment]
@Jauchi don't worry about it :smile: You are correct that you should `git rebase` instead of `git pull`. If you're not having any luck, I value contribution over being an ace at `git`, so feel free to make a new PR if needed.

**Comment by Jauchi** [comment]
Yeah, okay, I think I broke something on my end. I think I'll have a look at how other people do this kind of stuff.
I will close this PR right here and I'll try to get it to work with two repos under my profile, since I might need a bit of practise first.
Thank you for being so helpful, I'll try to get everything to work before opening my 4th pull request.

**Pull request closed without merging**
