### PR TITLE
browsr: init at 1.10.7

### PR DESCRIPTION
**Pull request by figsoda**
###### Description of changes

https://github.com/juftin/browsr

also adds the following python libraries:
- https://github.com/sepandhaghighi/art
- https://github.com/darrenburns/rich-pixels
- https://github.com/fsspec/universal_pathlib

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
I tried running nixpkgs-review and start the binary but got

```
Traceback (most recent call last):
  File "/nix/store/0xgsx7pxsjg7agd934yiv431vpf1kx26-browsr-1.10.4/bin/.browsr-wrapped", line 6, in <module>
    from browsr.__main__ import browsr
  File "/nix/store/0xgsx7pxsjg7agd934yiv431vpf1kx26-browsr-1.10.4/lib/python3.10/site-packages/browsr/__init__.py", line 5, in <module>
    from .browsr import Browsr
  File "/nix/store/0xgsx7pxsjg7agd934yiv431vpf1kx26-browsr-1.10.4/lib/python3.10/site-packages/browsr/browsr.py", line 21, in <module>
    from rich_pixels import Pixels
  File "/nix/store/9fqz3bjjxrpy2braj0lm91dl2xqq6fmi-python3.11-rich-pixels-2.1.1/lib/python3.11/site-packages/rich_pixels/__init__.py", line 1, in <module>
    from rich_pixels._pixel import Pixels
  File "/nix/store/9fqz3bjjxrpy2braj0lm91dl2xqq6fmi-python3.11-rich-pixels-2.1.1/lib/python3.11/site-packages/rich_pixels/_pixel.py", line 6, in <module>
    from PIL import Image as PILImageModule
  File "/nix/store/6yaclnj56s92z1gm1mfrsdby2dw4p03c-python3.11-pillow-9.4.0/lib/python3.11/site-packages/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/nix/store/6yaclnj56s92z1gm1mfrsdby2dw4p03c-python3.11-pillow-9.4.0/lib/python3.11/site-packages/PIL/__init__.py)
```

**Comment by figsoda** [comment]
Having python 3.11 libraries in the environment might have messed with some stuff, I can reproduce the error in nixpkgs-review but running it locally works fine

**Review by drupol — COMMENTED** [review]
This LGTM, but since I'm not using Python I simply cannot carefully review it.

**Comment by teto** [comment]
tested the executable and it worked fine.

**Pull request merged**
