### PR TITLE
jujutsu: 0.14.0 -> 0.15.1

### PR DESCRIPTION
**Pull request by adamcstephens**
## Description of changes

Diff: https://github.com/martinvonz/jj/compare/v0.14.0...v0.15.1

Changelog: https://github.com/martinvonz/jj/blob/v0.15.1/CHANGELOG.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by thoughtpolice — CHANGES_REQUESTED** [review]
Please note that there will (unless something changes) be an 0.15.1 release very very shortly to fix a minor issue with the https://crates.io release. So let's hold off until then. Thanks for the quick update, though!

**Comment by shanesveller** [comment]
Is it accurate to say that this PR could come out of draft once https://nixpk.gs/pr-tracker.html?pr=289940 reflects that the change in #289940 has reached `master`?

**Comment by adamcstephens** [comment]
> Is it accurate to say that this PR could come out of draft once https://nixpk.gs/pr-tracker.html?pr=289940 reflects that the change in #289940 has reached `master`?

Indeed! I'll rebase once that hits master.

**Comment by thoughtpolice** [comment]
I believe that the rustc 1.76.0 bump has hit `master`, so you're free to rebase.

Also, please just go ahead and squash the two commits into one; no need for the intermediate `0.15.0` build. Thanks.

**Comment by adamcstephens** [comment]
Yeah, I rebased this already to get rust 1.76, but the new signing tests are failing. Even when providing the necessary dependencies, e.g. `openssh`, these still fail.

```
--- STDERR:              jj-lib::runner test_ssh_signing::ssh_signing_bad_allowed_signers ---
thread 'test_ssh_signing::ssh_signing_bad_allowed_signers' panicked at lib/tests/test_ssh_signing.rs:145:10:
called `Result::unwrap()` on an `Err` value: Backend(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
```

I can fix the test failures by turning off nextest and setting `checkFlags = [ "--skip=test_ssh_signing" ]`

I'm giving up trying to get this working with nextest. Through a combination of bash arrays, splitting and extra escaping, I can't seem to get the arguments to pass correctly through the nextest setup hook. Using `cargoTestArgs` (since these need to be before the `--` in the [nextest run](https://github.com/NixOS/nixpkgs/blob/9289a0678efadcd95fae82ea8c82318d3a86694a/pkgs/build-support/rust/hooks/cargo-nextest-hook.sh#L38) ) we need to set `-E 'not test(/test_ssh_signing/)'`

@thoughtpolice If you're fine with disabling nextest, I can finish this PR. If not, then you're welcome to commit to this PR (if a committer) or I can close this and let you replace it yourself.

**Comment by thoughtpolice** [comment]
Disabling `nextest` is fine.

**Review by thoughtpolice — APPROVED** [review]

**Pull request merged**
