### PR TITLE
c-blosc2: init at 2.13.2, python3Packages.blosc2: 2.3.2 -> 2.5.1

### PR DESCRIPTION
**Pull request by risicle**
## Description of changes

`c-blosc2` package largely copied from `c-blosc`, however `c-blosc2` is developed under a separate tree and has a different e.g. pkg-config name so probably warrants a separate package as it will likely diverge.

This allows us to switch `python3Packages.blosc2` to use this system `c-blosc2` instead of its own bundled version.

Also built `pkgsStatic`, `pkgsMusl`, `pkgsCross.aarch64-multiplatform`, `pkgsi686Linux` versions of c-blosc2.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
pkgs/by-name check is failing but I don't really want to separate this package from `c-blosc`.

**Comment by infinisil** [comment]
@risicle Yeah i wouldn't separate it in that way. Check out https://github.com/NixOS/nixpkgs/pull/285922#issuecomment-1925940231 for my recommendation

**Comment by risicle** [comment]
Hmm neither of those really feel appropriate here.

Have you considered the ghetto option of simply making the checker ignore any attrnames ending in a digit?

**Comment by infinisil** [comment]
> Hmm neither of those really feel appropriate here.

I'd expect this to work out just fine:

```nix
  inherit (callPackages ../development/libraries/c-biosc { })
    c-biosc c-biosc2;
```

Or is there a problem with this?

> Have you considered the ghetto option of simply making the checker ignore any attrnames ending in a digit?

I have considered it, but it feels like a hack, which I'm really not fond of!

It's actually really interesting to have this restriction, because it highlights the problem of multiple package versions and encourages exploration of better solutions.

Even the above recommendation already has the benefit of being explicit about multiple attributes coming from the same source, which is a step in the right direction for future improvements.

**Comment by risicle** [comment]
Ok I've gone with that approach, but FWIW it _also_ feels like a bit of a hack that doesn't serve much purpose but to placate the CI. And I'd much rather have a hacky CI than to fill nixpkgs with all these hacks that don't really add any value.

**Comment by Mindavi** [comment]
Sometimes adding a hack to CI is ok, but exempting packages with a number at the end is overly broad to me. So I think this is the right solution, for now. We can always reconsider later if we get tens or hundreds of packages like this.

**Review by Mindavi — APPROVED** [review]

**Pull request merged**
