### PR TITLE
sympy: enable ipython

### PR DESCRIPTION
**Pull request by ebzzry**

### CODE REVIEW

**Comment by ebzzry** [comment]
Even without `ipython` enabled, `python3.5-sympy` fails to build. However, `python2.7-sympy`, builds successfully.

**Comment by FRidh** [comment]
Python 3.5 is not yet supported by upstream.

I am disabling sympy for Python 3.5 in #10264

**Comment by ebzzry** [comment]
OK. Thanks.

**Comment by FRidh** [comment]
If that answers it, could you close the issue? Thanks.

**Pull request closed without merging**
