### PR TITLE
gnomeExtensions: auto-update

### PR DESCRIPTION
**Pull request by rhoriguchi**
###### Description of changes

Removing manual pinning of extension `dash-to-dock`. Makes updating easier and less likely to be forgotten. The stability issues should be resolved.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

List of open PRs: https://github.com/NixOS/nixpkgs/pulls
Reviewing guidelines: https://nixos.org/manual/nixpkgs/unstable/#chap-reviewing-contributions
-->

### CODE REVIEW

**Comment by rhoriguchi** [comment]
@piegamesde you asked about extensions being removed, here is an example:

```console
> nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"
...
1 package removed:
gnome-shell-extension-sur-clock (†4)
...
```

**Comment by piegamesde** [comment]
Great, thank you. Have you tried dash-to-dock out and can confirm that it still works? Also, might want to add yourself back as maintainer using an override (has been done in the past).

**Comment by rhoriguchi** [comment]
> Great, thank you. I always appreciate getting rid of manually packaged extensions.
> 
> Have you tried dash-to-dock out and can confirm that it still works? Also, might want to add yourself back as maintainer using an override (has been done in the past).

No haven't tried it, but assumed it works again, since if I remember correctly a while ago it was pinned to a certain commit. Also, I can add myself back as a maintainer, testing the extension is a bit cumbersome but I'll do it on the weekend. I'll mark the PR as draft till I've tested it.

**Comment by piegamesde** [comment]
Tested in VM and works

**Pull request merged**
