### PR TITLE
camlistore: 0.9 -> perkeep 20170505

### PR DESCRIPTION
**Pull request by yrashk**
camlistore has been renamed to perkeep

###### Motivation for this change

camlistore hasn't been updated in a long time

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build perkeep

**Comment by grahamc** [comment]
Bummer that Go is broken on aarch64...

**Comment by orivej** [comment]
> Bummer that Go is broken on aarch64...

@grahamcIt is not always broken: https://hydra.nixos.org/job/nixpkgs/trunk/go_1_8.aarch64-linux/all
I think the failures are mostly caused by haskell packages and may be mitigated by reducing jobs count (not build cores count) to 10 or fewer: https://github.com/NixOS/nixpkgs/pull/32271#issuecomment-351571748

**Comment by vcunat** [comment]
Go has flaky tests, on multiple platforms, I think.  It seems like they don't do well under high load.

**Comment by orivej** [comment]
Go tests are fairly stable on non aarch64 ([linux](https://hydra.nixos.org/job/nixpkgs/trunk/go_1_8.x86_64-linux/all), [darwin](https://hydra.nixos.org/job/nixpkgs/trunk/go_1_8.x86_64-darwin/all)), they fail either due to thread exhaustion (e.g. https://hydra.nixos.org/build/65201151) or due to being starved on CPU.

**Comment by grahamc** [comment]
FWIW the machine was doing nothing but compiling Go at the time of this
fairly. Before and after the build it had a load of 0.

**Comment by orivej** [comment]
@grahamc Could you post the complete log? It may be available with `nix log /nix/store/cx3p2q3vpw5n8y9w71piavvkmhqrii6c-go-1.8.5.drv`.

**Comment by grahamc** [comment]
You bet: https://clbin.com/9wfzg

**Comment by orivej** [comment]
As discussed on IRC, this error is caused by running Go tests on unionfs-fuse filesystem.

**Comment by vcunat** [comment]
@orivej: I'm not sure I understand... can you see an easy way to avoid these go failures on Hydra?  The repeated mass failures due to this are really annoying, as they're difficult to restart and they may hide other aarch64-linux problems easily.

**Pull request merged**
