### PR TITLE
.github/workflows/dispatch.yml: add slash-command-dispatch

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
PR isn't quite ready for review yet but we may as well start discussing the token, it would need to be from a committer with `public_repo, workflow, read:org` scopes.

Using a non-default token is required for:
- `dispatch.yml`: More reliable way of doing `/commands`, also allows us to drop some boilerplate and makes adding other commands simpler. (Would also cut down on GHA usage as the currently each command we add would run it's own CI job for a few seconds on every comment.)
- `rebase.yml`: Using the default github token to push changes doesn't trigger the PR actions (`wait for ofborg`, `editorconfig`, etc). Currently the rebase action works around it by closing the PR with a comment that says the PR should be reopened manually. A non-default token would also unblock rebasing on the same base branch (this has been requested by a few people) without needing additional workarounds.

The `GrahamcOfBorg` bot account is already a committer which would make things simpler. Alternatively I could make a bot account if someone would add it as a committer.

@domenkozar @grahamc

**Comment by zowoq** [comment]
ping @NixOS/security, re: token.

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/126192

**Comment by domenkozar** [comment]
@zowoq I plan to review this, but it's not a high priority for me.

**Comment by zowoq** [comment]
>  I plan to review this

I didn't ask for a review (at this stage), I just wanted a response about the token.

**Comment by Mic92** [comment]
> > I plan to review this
> 
> I didn't ask for a review (at this stage), I just wanted a response about the token.

Did you close the PR because you did not got feedback timely?

**Pull request closed without merging**
