### PR TITLE
gitlab-runner: 11.3.1 -> 11.4.0

### PR DESCRIPTION
**Pull request by bachp**
###### Motivation for this change

https://gitlab.com/gitlab-org/gitlab-runner/blob/8af42251eebf1922576b5f8179590138ef8a4e30/CHANGELOG.md

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build gitlab-runner

**Comment by xeji** [comment]
aarch64 failure looks like a builder-specific problem (lack of resources). Let's try again.
@GrahamcOfBorg build gitlab-runner

**Comment by xeji** [comment]
Same error on a different builder. @bachp have you encountered this aarch64 failure before?

**Comment by bachp** [comment]
@xeji I think there were already issues with the aarch64 build last update. 

However I was not able to reproduce them as they successfully build on my Raspberry Pi3. I even thought there were binaries available form cache.nixos.org (not 100% sure and can't check right now).

**Comment by xeji** [comment]
Yes, the current version builds on hydra for aarch64.  So let's assume this is an ofborg-only error and merge it anyway. Please check the aarch64 build in the next hydra evaluation.

**Pull request merged**
