### PR TITLE
pdf-tools: init at v0.70

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by DamienCassou** [comment]
/cc @oxij I can't build that locally:

```
mkdir -p 'pdf-tools-0.70'
cp lisp/*.el README server/epdfinfo 'pdf-tools-0.70'
echo '(define-package "pdf-tools" "0.70" "Support library for PDF documents." (quote ((emacs "24.3") (let-alist "1.0.1"))) :keywords (quote ("files" "multimedia")))' > 'pdf-tools-0.70/pdf-tools-pkg.el'
tar cf 'pdf-tools-0.70.tar' 'pdf-tools-0.70'

;;; pdf-tools

Single file epdfinfo does not match package name pdf-tools
note: keeping build directory ‘/tmp/nix-build-emacs-pdf-tools-v0.70.drv-2’
builder for ‘/nix/store/a9cczp4zl6d3b5iqd1lizc612k98kizq-emacs-pdf-tools-v0.70.drv’ failed with exit code 255
error: build of ‘/nix/store/a9cczp4zl6d3b5iqd1lizc612k98kizq-emacs-pdf-tools-v0.70.drv’ failed
```

**Comment by oxij** [comment]
`lisp` not `list`, also should've read the Makefile (default target does
a lot, too much, actually).

Apply this on top:

diff --git a/pkgs/top-level/emacs-packages.nix b/pkgs/top-level/emacs-packages.nix
index dc68f61..0c808f4 100644
--- a/pkgs/top-level/emacs-packages.nix
+++ b/pkgs/top-level/emacs-packages.nix
@@ -85,16 +85,16 @@ let self = _self // overrides;
 
   pdf-tools = melpaBuild rec {
     pname = "pdf-tools";
-    version = "v0.70";
+    version = "0.70";
     src = fetchFromGitHub {
       owner = "politza";
       repo = "pdf-tools";
-      rev = "${version}";
+      rev = "v${version}";
       sha256 = "19sy49r3ijh36m7hl4vspw5c4i8pnfqdn4ldm2sqchxigkw56ayl";
     };
     buildInputs = with external; [ autoconf automake libpng zlib poppler pkgconfig ];
-    preBuild = "make";
-    fileSpecs = [ "list/*.el" "server/epdfinfo" ];
+    preBuild = "make server/epdfinfo";
+    fileSpecs = [ "lisp/*.el" "server/epdfinfo" ];
     meta = {
       description = "Emacs support library for PDF files";
       license = gpl3;

**Comment by DamienCassou** [comment]
Thanks for your help. The error is now

```
installing
Parsing tar file...
Parsing tar file...done
Package `tablist-0.70' is unavailable
builder for ‘/nix/store/llmq1q6ngk9g2w859bqcwzggrvgcl9qz-emacs-pdf-tools-0.70.drv’ failed with exit code 255
error: build of ‘/nix/store/llmq1q6ngk9g2w859bqcwzggrvgcl9qz-emacs-pdf-tools-0.70.drv’ failed
The invocation of "nix-build -A emacs24PackagesNg.pdf-tools /home/travis/.nox/nixpkgs" failed
```

`tablist` is a `.el` file included in the tar. But I don't know why `tablist-0.70` is searched and not found.

**Comment by oxij** [comment]
That's because `tablist` is defined to be a separate package (see
`tablist.el` source). You'll have to define another derivation for it
and then depend on it (see e.g. `magit` for an example).

**Comment by DamienCassou** [comment]
This works really well. Thank you very much for your help.

**Pull request merged**
