### PR TITLE
qemu: enable debug info

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

I dropped autoPatchelfHook because it got confused with the debug objects, and I can't reproduce the pixman linker errors that caused it to be introduced in #106988 ("qemu: 5.1.0 -> 5.2.0").

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Drafted because I reproduced the autoPatchelfHook issue when testing with the QEMU rc.

**Comment by alyssais** [comment]
[`654d6b0453aa6eb19af0d75b0f087a97a5776da7`](https://git.qemu.org/?p=qemu.git;a=commitdiff;h=654d6b0453aa6eb19af0d75b0f087a97a5776da7) is the first bad commit

**Comment by alyssais** [comment]
In Nixpkgs we only have Meson 0.57.1, so that might explain why this isn't working.

**Comment by alyssais** [comment]
Yeah, that's because of the Meson version being too old, and QEMU using its internal version instead of our patched version.  I've opened https://github.com/NixOS/nixpkgs/pull/147210 to make sure this never happens by accident, and I'll make sure we have the right version of Meson before we upgrade QEMU.

So with that all sorted out, we can go ahead with this, and we won't be at risk of rpath regressions.  So this is ready for review.

**Comment by Artturin** [comment]
https://hydra.nixos.org/build/162289307
Probably caused by this pr

**Comment by vcunat** [comment]
This blocks the `nixos-unstable` channel now.

The 2G limit is only crossed on aarch64-linux.  Stats from the previous master build (successful):
```
$ nix path-info -s ./result ./result-ga ./result-debug
/nix/store/fjashkx22bw4zrl9phl91acw6jgn43i6-qemu-6.1.0           1068005248
/nix/store/9spayjr081j7jlvvdassypsv0a6dk3yw-qemu-6.1.0-ga            655960
/nix/store/cq8cj8jd3x96kyhy2gq9f6r7xrss4yf3-qemu-6.1.0-debug     1114494472
```
and the current build:
```
$ nix path-info -s ./result ./result-ga ./result-debug
/nix/store/fw893ccw8rnnfg066l2b91ypd63wx58v-qemu-6.1.0           1122797000
/nix/store/051rn39nhw9ayqh7sfx8yavysfmb113r-qemu-6.1.0-ga            776864
/nix/store/cq8cj8jd3x96kyhy2gq9f6r7xrss4yf3-qemu-6.1.0-debug     1114494472
```

**Comment by vcunat** [comment]
Well, x86_64-linux got to 96% of the limit, so that perhaps also isn't safe over long term.
```
$ nix path-info -s ./result*
/nix/store/45j5s96ivk8k4d61cayr0hla67s7bi7i-qemu-6.1.0-ga            762520
/nix/store/h6381cwzaw6fs9dzv9bgz0mgjnxk3vfx-qemu-6.1.0           1132452408
/nix/store/lyvqx84m4w02q3p2qxi3vh4c70dybi8a-qemu-6.1.0-debug      924265248
```

**Comment by vcunat** [comment]
Quick workaround: https://github.com/NixOS/nixpkgs/pull/152218

**Pull request merged**
