### PR TITLE
apacheKafka: 1.1.0 -> 2.0.0, various patch upgrades for other versions

### PR DESCRIPTION
**Pull request by mbode**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mbode** [comment]
I am not sure what the policy is on how many old versions should be kept, cf. discussion in #46659.

Also, it seems there are so far no mentions of Kafka version upgrades in the release notes, is that on purpose?

**Comment by NeQuissimus** [comment]
@GrahamcOfBorg test kafka

**Comment by mbode** [comment]
@NeQuissimus It seems you only pushed one of the commits to _master_

**Comment by NeQuissimus** [comment]
oO That's the weirdest thing! I just used the GitHub UI...

**Comment by mbode** [comment]
Oh sorry, I should've checked there first!

**Pull request merged**
