### PR TITLE
sublime-merge: Allow disabling libredirect

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
When using Sublime on systems with software linked against a different libc version, the programs executed as child processes tend to crash.

This is especially annoying when using SM on Ubuntu since git fails to start, preventing any interactive actions from succeeding.

Until https://github.com/NixOS/nixpkgs/issues/73077 is fixed, let’s add an option for disabling the feature for people who do not intend to edit files of different users.

cc @nh2

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124334` at 9ddccfdb run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>sublime-merge</li>
    <li>sublime-merge-dev</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/version-management/sublime-merge/common.nix:96:3:
```
   |
96 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by nh2** [comment]
@jtojnar Another idea: https://github.com/NixOS/nixpkgs/pull/124057#discussion_r638745295

**Review by zookatron — APPROVED** [review]
Looks good, this option makes sense to me given the conversation in the other thead. I tested out building the package with and without the option set and it behaves as expected, when the pkexec redirect is disabled Sublime merge is able to run Git commands without issue in an environment with the latest version of the Nixos code.

**Comment by anpryl** [comment]
@jtojnar any chances this will be merged?

**Comment by jtojnar** [comment]
I stopped using non-NixOS systems and no longer have time to move this forward. Maybe the best way forward would be trying to make Sublime team to fix it upstream: https://github.com/sublimehq/sublime_text/issues/3502. Maybe try asking about it on the [Discord](https://discord.com/invite/D43Pecu)?

**Pull request closed without merging**
