### PR TITLE
altserver-linux: cleanup and rename from alt-server / AltServer-Linux

### PR DESCRIPTION
**Pull request by amarshall**
## Description of changes

See individual commits for details. I’m pretty :man_shrugging: on `altserver-linux` vs. `alt-server-linux`.

## Things done

I have *only* tested that it execs and shows help.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
`altserver-linux` looks fine, as both AltStore and Homebrew use `altserver` without hyphen.

In the meantime, perhaps an alias is necessary?

**Comment by max-amb** [comment]
Looks good, thanks! I think we should go for plain altserver on second thought as this build is only for linux and for similarities with AltStore and homebrew.

**Review by max-amb — APPROVED** [review]

**Comment by max-amb** [comment]
There would be no point to packaging alt-server for macos, it runs natively there in the form of alt store.

**Comment by wegank** [comment]
> There would be no point to packaging alt-server for macos, it runs natively there in the form of alt store.

There is in fact an (official!) AltServer for macOS, not yet packaged in nixpkgs.

To be clear, AltServer is the application that installs AltStore on iOS devices.

**Comment by max-amb** [comment]
hm, so what do you propose we rename the package to to encompass all?

**Comment by wegank** [comment]
I'd prefer to keep it as it is, as having an `altserver` might confuse darwin users. Something like `altserver = if stdenv.isLinux then altserver-linux else ...` could of course be done if the one for macOS is packaged.

**Comment by max-amb** [comment]
Sounds good to me.

**Pull request merged**
