### PR TITLE
coreutils: fix tests failing on f2fs

### PR DESCRIPTION
**Pull request by voobscout**
###### Motivation for this change

```nixos-rebuild switch``` fails on F2FS based install.

```
============================================================================
Testsuite summary for GNU coreutils 8.29
============================================================================
# TOTAL: 603
# PASS:  464
# SKIP:  138
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./tests/test-suite.log
Please report to bug-coreutils@gnu.org
============================================================================
```
The culprit is "du threshold test" in ```tests/du/threshold.sh```

###### Things done

Removed failing test, as originally suggested by @edolstra in the comments:
https://github.com/NixOS/nixpkgs/blob/31712afa7b08a46c8e393a1b63c9fbae576762e6/pkgs/tools/misc/coreutils/default.nix#L26-L35
---

### CODE REVIEW

**Review by xeji — CHANGES_REQUESTED** [review]
The additional commits added above look like they don't belong here. Please check.

**Comment by voobscout** [comment]
What's up with all the commits I didn't add?

**Comment by xeji** [comment]
That can happen when a rebase is done incorrectly. I suggest you close this and open a new PR to clean it up.

**Comment by voobscout** [comment]
@xeji just to be clear, what's the correct way of rebasing?

After forking, I did
```bash
git clone git@github.com:voobscout/nixpkgs.git
cd nixpkgs
git remote add upstream https://github.com/NixOS/nixpkgs.git
git fetch upstream
git rebase upstream/master
```
Added my changes and committed. What went wrong?

**Comment by xeji** [comment]
By default, `git rebase` applies all commits since the common ancestor of both branches on top of (here) `upstream/master`. If the branches have diverged by more than your own changes, you end up with unwanted commits. To avoid that, use `git rebase --onto upstream/master start master` and specify the starting point of your changes (direct ancestor of your first own commit) in `start` . See the detailed explanation in `man git-rebase`. It is also recommended to use a separate branch for each pull request, not `master` from your fork.

**Comment by voobscout** [comment]
@xeji Many thanks! I'll redo this properly.

**Pull request closed without merging**
