### PR TITLE
nixos/krb5: allow lists in configuration

### LINKED ISSUE #89626: krb5.realms.<realm>.kdc should allow multiple hosts
**Describe the bug**
In the krb5 module (nixpkgs/nixos/modules/config/krb5) the `krb5.realms.<realm>.kdc` option should allow multiple hosts to be defined. Kerberos allows multiple entries for fault tolerance, however the module only allows a single host to be defined.

**Expected behavior**
The kdc option should be a list of strings, for example:

```
krb5.realms = {
  "CORP" = {
    admin_server = "dc01.corp.lan";
    kdc = [
      "dc01.corp.lan"
      "dc02.corp.lan"
    ];
  };
}
```

which should produce the following config:

```
[realms]
CORP = {
  admin_server = dc01.corp.lan
  kdc = dc01.corp.lan
  kdc = dc02.corp.lan
}
```

**Notify maintainers**

@eqyiel @Mic92 @pvgoran @volth 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.42, NixOS, 20.03.2015.e7752db2fb6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.03.2015.e7752db2fb6"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - krb5
```

### PR DESCRIPTION
**Pull request by heinic**
###### Motivation for this change
Fix #89626 

Kerberos allows multiple values for `kdc` to be specified, this should be possible by passing a list to `config.krb5.realms.<realm>.kdc`. In general, when specifying a list, it should  end up as multiple lines of `<attrName> = <list item>` in `krb5.conf`.

Although there has been code to accept lists, evaluating would lead to _attrs_ to be passed to `concatMapStringsSep` instead of a _list_ as the last parameter, causing the evaluation to fail. Because of this, removing it is not a breaking change.
https://github.com/NixOS/nixpkgs/blob/adc908a87371e9567950afb0ea55b929b870823c/nixos/modules/config/krb5/default.nix#L52-L53

###### Things done

Simplified indentation generation, allowing `mkRelation` to be more easily reused by `mkVal` (and vice versa). Added list handling to `mkRelation` and removed list handling from `mkVal`.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date  
  There is no documentation beside the examples, changing the relevant example would be an option.
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg test krb5

**Comment by heinic** [comment]
Updated the test like you suggested. I also changed the example for the nixos option, so it matches the updated test.

**Comment by heinic** [comment]
@ofborg test krb5

**Review by eqyiel — APPROVED** [review]

**Comment by eqyiel** [comment]
@heinic I don't have write access so someone else would have to merge this, but it looks good to me.

**Pull request merged**
