### PR TITLE
signal-desktop: 6.27.1 -> 6.29.1, signal-desktop-beta: 6.24.0-beta.1 -> 6.30.0-beta.2

### PR DESCRIPTION
**Pull request by Morantoine**
Also signal-desktop-beta: 6.24.0-beta.1 -> 6.30.0-beta.2

## Description of changes

Updated signal-desktop from 6.27.1 to 6.29.1, and signal-desktop-beta from 6.24.0-beta.1 to 6.30.0-beta.2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](thttps://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by YarekTyshchenko** [comment]
Tested on NixOS, works fine! Good job

**Comment by onny** [comment]
Since these are two different packages, maybe split up the commits for signal-desktop and signal-desktop-beta, thank you :+1:

**Comment by Morantoine** [comment]
> Since these are two different packages, maybe split up the commits for signal-desktop and signal-desktop-beta, thank you +1

Sure, done

**Review by JulienMalka — APPROVED** [review]
Both changes are working correctly on my NixOS laptop `x86_64-linux`, thanks

**Review by equirosa — APPROVED** [review]
LGTM

**Comment by teutat3s** [comment]
Thank you for working on this!
New version is out, could you update to use the newest version: [6.29.1](https://github.com/signalapp/Signal-Desktop/releases/tag/v6.29.1)?

**Comment by Morantoine** [comment]
> 

Sure, in a separate commit?

**Comment by Morantoine** [comment]
> > 


> Thank you for working on this! New version is out, could you update to use the newest version: [6.29.1](https://github.com/signalapp/Signal-Desktop/releases/tag/v6.29.1)?

Sure, in a separate PR?

**Comment by Morantoine** [comment]
> Thank you for working on this! New version is out, could you update to use the newest version: [6.29.1](https://github.com/signalapp/Signal-Desktop/releases/tag/v6.29.1)?

Updated the PR and the corresponding messages 👍🏻

**Review by teutat3s — APPROVED** [review]

**Comment by YarekTyshchenko** [comment]
Regular version seems to work alright, haven't tested the beta.
Given that it updates so often, maybe worth adding a script? Probably best left for another PR. This one LGTM!

**Comment by equirosa** [comment]
On August 26, 2023 3:09:34 PM CST, Yarek T ***@***.***> wrote:
>Regular version seems to work alright, haven't tested the beta.
>Given that it updates so often, maybe worth adding a script? Probably best left for another PR. This one LGTM!
>

That's probably a good call, I'll take a look at the ones we have for other packages and work on one for this

**Comment by thrifty-txt** [comment]
Would it be possible to split the work for an update script to a different PR if thats blocking this from being merged in? Many thanks!

**Comment by equirosa** [comment]
On August 31, 2023 7:44:47 PM CST, Ali Abdel-Qader ***@***.***> wrote:
>Would it be possible to split the work for an update script to a different PR if thats blocking this from being merged in? Many thanks!
>

Oh yeah! I thought that was the plan. I'll add the script in a different PR, this one can be merged :)

**Review by oddlama — APPROVED** [review]

**Comment by Morantoine** [comment]
Hey, just for info, any updates on when this will be merged or how it works?

**Comment by Kranzes** [comment]
@Morantoine Now :D

**Pull request merged**
