### PR TITLE
Electrum 2 8

### PR DESCRIPTION
**Pull request by joachifm**

### CODE REVIEW

**Comment by ehmry** [comment]
It can't open my wallet file, but other that, it works.
```
Traceback (most recent call last):
  File "/nix/store/bcqgm3iak715kqpz1hkz1p2g44hg1g93-electrum-2.8.0/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 157, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File "/nix/store/bcqgm3iak715kqpz1hkz1p2g44hg1g93-electrum-2.8.0/lib/python2.7/site-packages/electrum/daemon.py", line 220, in load_wallet
    wallet = Wallet(storage)
  File "/nix/store/bcqgm3iak715kqpz1hkz1p2g44hg1g93-electrum-2.8.0/lib/python2.7/site-packages/electrum/wallet.py", line 1751, in __new__
    wallet = WalletClass(storage)
  File "/nix/store/bcqgm3iak715kqpz1hkz1p2g44hg1g93-electrum-2.8.0/lib/python2.7/site-packages/electrum/wallet.py", line 1563, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/nix/store/bcqgm3iak715kqpz1hkz1p2g44hg1g93-electrum-2.8.0/lib/python2.7/site-packages/electrum/wallet.py", line 1408, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/nix/store/bcqgm3iak715kqpz1hkz1p2g44hg1g93-electrum-2.8.0/lib/python2.7/site-packages/electrum/wallet.py", line 105, in __init__
    self.load_addresses()
  File "/nix/store/bcqgm3iak715kqpz1hkz1p2g44hg1g93-electrum-2.8.0/lib/python2.7/site-packages/electrum/wallet.py", line 223, in load_addresses
    self.receiving_addresses = d.get('receiving', [])
AttributeError: 'list' object has no attribute 'get'
```

**Comment by joachifm** [comment]
@ehmry hm, I don't see anything in the changelog about incompatibilities with older wallets. Looks like a bug to me or at least a deficiency.

**Comment by joachifm** [comment]
Looks related: https://github.com/spesmilo/electrum/commit/0e49274eae9f497164ecc694729acdcf1188a43a. I'll wait until 2.8.1 hits the release archives.

**Comment by joachifm** [comment]
Hrm, maybe not. I'll wait anyway.

**Comment by joachifm** [comment]
@ehmry could you try again with 2.8.1? I don't have any old wallets handy, but I was at least able to open a freshly wallet created with 2.7.18.

**Comment by ehmry** [comment]
Excellent, no problems with 2.8.1, I say merge.

**Comment by joachifm** [comment]
@ehmry cool, thank you!

**Pull request merged**
