### PR TITLE
wire-desktop: linux 3.21.2936 -> 3.22.2937

### PR DESCRIPTION
**Pull request by toonn**
###### Motivation for this change

Version bump.
I also included a change to my maintainer email.

I expect a new release for macOS as well soon which I will add to this PR if it's not merged by then.

I usually backport these version bumps but have receive mixed messages about doing that. Please let me know if/when I can backport this.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115180` at dd4b13bc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/93aa7e570f17e16ddc2a8b127b0ef3d1">wire-desktop</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/networking/instant-messengers/wire-desktop/default.nix:100:5:
```
    |
100 |     installPhase = ''
    |     ^
```
</li>
  </ul>
</details>

**Comment by toonn** [comment]
I'm hesitant to add the runHook suggestions because those phases don't seem to be necessary in this case and more moving parts means more places to mess things up. This expression really just installs a .deb or .pkg, however, I will make the changes if reviewers say they're desirable.

**Comment by SuperSandro2000** [comment]
> I usually backport these version bumps but have receive mixed messages about doing that. Please let me know if/when I can backport this.

Sure, why not? As long as I don't need to do it and test it.

**Comment by SuperSandro2000** [comment]
> I'm hesitant to add the runHook suggestions because those phases don't seem to be necessary in this case and more moving parts means more places to mess things up. This expression really just installs a .deb or .pkg, however, I will make the changes if reviewers say they're desirable.

Please read https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md. So far I don't know any case where it broke something.

**Pull request merged**
