### PR TITLE
sourcehut: update-6

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
I'll look into fixing these on master:
```
https://github.com/NixOS/nixpkgs/pull/91324
22 packages failed to build:
cinnamon.cinnamon-common cinnamon.cinnamon-gsettings-overrides cinnamon.cinnamon-screensaver mirage-im python37Packages.cairosvg python37Packages.cssselect2 python37Packages.pygal python37Packages.qasm2image python37Packages.svglib python37Packages.tinycss2 python37Packages.weasyprint python37Packages.xml2rfc python38Packages.cairosvg python38Packages.cssselect2 python38Packages.pygal python38Packages.qasm2image python38Packages.svglib python38Packages.tinycss2 python38Packages.weasyprint xml2rfc sourcehut.gitsrht sourcehut.metasrht

11 packages built:
python37Packages.mistletoe python38Packages.mistletoe sourcehut.buildsrht sourcehut.dispatchsrht sourcehut.hgsrht sourcehut.hubsrht sourcehut.listssrht sourcehut.mansrht sourcehut.pastesrht sourcehut.python sourcehut.todosrht
```

**Comment by jonringer** [comment]
nevermind, a lot of these seem to build on master, do you mind investigating some of the breakages?

**Comment by eadwu** [comment]
Everything should build fine now. Cleaned up the commits as well. Will rebase when https://github.com/NixOS/nixpkgs/pull/97473 is merged.

**Comment by jonringer** [comment]
I merged it, please rebase :)

**Comment by eadwu** [comment]
Rebased.

**Review by jonringer — APPROVED** [review]
diff LGTM

```
https://github.com/NixOS/nixpkgs/pull/91324
33 packages built:
cinnamon.cinnamon-common cinnamon.cinnamon-gsettings-overrides cinnamon.cinnamon-screensaver mirage-im python37Packages.cairosvg python37Packages.cssselect2 python37Packages.mistletoe python37Packages.pygal python37Packages.qasm2image python37Packages.svglib python37Packages.tinycss2 python37Packages.weasyprint python37Packages.xml2rfc python38Packages.cairosvg python38Packages.cssselect2 python38Packages.mistletoe python38Packages.pygal python38Packages.qasm2image python38Packages.svglib python38Packages.tinycss2 python38Packages.weasyprint xml2rfc sourcehut.buildsrht sourcehut.dispatchsrht sourcehut.gitsrht sourcehut.hgsrht sourcehut.hubsrht sourcehut.listssrht sourcehut.mansrht sourcehut.metasrht sourcehut.pastesrht sourcehut.python sourcehut.todosrht
```

**Pull request merged**
