### PR TITLE
yuzu: 1475 -> 1495, yuzu-ea: 3702-> 3754

### PR DESCRIPTION
**Pull request by LostAttractor**
###### Description of changes

yuzu: 1475 -> 1495, yuzu-ea: 3702-> 3754

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PedroHLC** [comment]
Sadly, these versions require newer vulkan-header/loader. The tags before 06/July are okay.

**Comment by SuperSandro2000** [comment]
We can probably update those in another PR, too.

**Comment by SuperSandro2000** [comment]
@ofborg build yuzu-mainline yuzu-early-access

**Comment by leiserfg** [comment]
[EA-3737](https://github.com/pineappleEA/pineapple-src/releases/tag/EA-3737) was the last one before vulkan `1.3.256`

**Comment by PedroHLC** [comment]
Feel free to reuse any part of my code: https://github.com/chaotic-cx/nyx/blob/main/pkgs/yuzu-ea-git/default.nix

**Comment by leiserfg** [comment]
> Feel free to reuse any part of my code: https://github.com/chaotic-cx/nyx/blob/main/pkgs/yuzu-ea-git/default.nix

Will you upstream it?

**Comment by PedroHLC** [comment]
> > Feel free to reuse any part of my code: https://github.com/chaotic-cx/nyx/blob/main/pkgs/yuzu-ea-git/default.nix
> 
> Will you upstream it?

Not on my list of priorities, and the tzdata is a requirement to update, so feel free to do it.

**Comment by leiserfg** [comment]
I created #243780 to bump the vulkan version :crossed_fingers:

**Comment by leiserfg** [comment]
I think it's better to wait for the vulkan update and then rebase this branch when they get merged.

**Comment by PedroHLC** [comment]
In 3764, they changed the `VulkanMemoryAllocator` to depend on an unreleased commit `3d23bb07e375ecabad0ad2e53599861be77310e3`.

So the additions that this PR will have to cover is the upcoming Vulkan and Spirv bump, the tzdata pre-download, and (if you update to 3764) a new yet unreleased VulkanMemoryAllocator.

**Comment by leiserfg** [comment]
It's getting pretty hard to keep vulkan updated if they keep releasing components depending on other unreleased versions of other components.

**Pull request closed without merging**
