### PR TITLE
materia-theme: 20181115 -> 20181125

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update to version [20181125](https://github.com/nana-4/materia-theme/releases/tag/v20181125)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by c0bw3b** [comment]
Hello @romildo 
Do you think this could live under `pkgs/data/themes` instead of `misc/themes` ? And be declared in the `### DATA` section of all-packages.nix

I know ATM every others themes are under that top-level misc but it is too generic and it would be logical for themes to live next to icons and fonts and such.

**Comment by c0bw3b** [comment]
Indeed. Something like `gtk-engine-murrine` (which is mostly a library) should live under `pkgs/development/libraries/` then.  (or `pkgs/desktops/` but less ideal)

**Comment by romildo** [comment]
>Do you think this could live under pkgs/data/themes instead of misc/themes ? And be declared in the ### DATA section of all-packages.nix

Done.

**Review by c0bw3b — APPROVED** [review]
Thanks

**Pull request merged**
