### PR TITLE
deno: 1.1.0 -> 1.1.1

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS (x86)
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by danieldk — COMMENTED** [review]
Small cleanup suggestion for the derivation:

Maybe you could replace

```
  buildInputs = with stdenv.lib; [ ]
    ++ optionals stdenv.isDarwin [ Security CoreServices ];
```
by:
```
buildInputs = stdenv.lib.optionals stdenv.isDarwin [ Security CoreServices ];
```
(`optionals` will return an empty list when the conditional fails)

**Review by prusnak — APPROVED** [review]

**Comment by 06kellyjac** [comment]
Thanks for the suggestion @danieldk 

At the cost of 14 extra characters + a newline I personally prefer the appearance and clarity of the original.
Also it makes it very easy to add stuff if in the future all architectures buildInputs, or if there's another architecture that needs a set of specific buildInputs

**Comment by danieldk** [comment]
> At the cost of 14 extra characters + a newline I personally prefer the appearance and clarity of the original.

I kindly disagree. An additional glitch is that `stdenv.lib` is introduced to the lexical scope of `[]`. But at any rate, this is only a small nitpick :wink:.

**Review by danieldk — APPROVED** [review]
LGTM

Result of `nixpkgs-review pr 91126` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- deno
</details>

Also tested running `deno`.

**Comment by 06kellyjac** [comment]
Thanks for merging.

> An additional glitch is that `stdenv.lib` is introduced to the lexical scope of `[]`.

Interesting. I guess I'll change it going forward :sweat_smile: 
I'm pretty new to nix so I'd love to know the potential consequences of doing this. :slightly_smiling_face: 
I'm guessing adding `with` here `buildInputs = with stdenv; lib.optionals isDarwin [ Security CoreServices ];` run into the same issue?

**Pull request merged**
