### PR TITLE
cmake: 24.3 -> 25.1

### PR DESCRIPTION
**Pull request by Baitinq**
###### Description of changes

cmake: 24.3 -> 25.1

I removed the 002-application-services.diff as it failed to apply and compilation/behavior was successful (with very minimal testing) without it. Please let me know if this is not OK and the patch should be fixed :)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
It should target staging branch instead of master, because cmake is a dependecy of a huge amount of packages.

I remember that there is a complicated set of git commands that should be made in order to fix this - rebasing via github interface generates a truckload of trash and the bots go crazy. For now, just ignore it.

**Comment by Artturin** [comment]
> It should target staging branch instead of master, because cmake is a dependecy of a huge amount of packages.
> 
> I remember that there is a complicated set of git commands that should be made in order to fix this - rebasing via github interface generates a truckload of trash and the bots go crazy. For now, just ignore it.

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

**Comment by AndersonTorres** [comment]
>  Please let me know if this is not OK and the patch should be fixed :)

ofBorg complaining:

> [ 82%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmGlobalXCodeGenerator.cxx.o
> /tmp/nix-build-cmake-boot-3.25.1.drv-0/cmake-3.25.1/Source/cmGlobalXCodeGenerator.cxx:61:14: fatal error: 'ApplicationServices/ApplicationServices.h' file not found
> #    include <ApplicationServices/ApplicationServices.h>
>              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [Source/CMakeFiles/CMakeLib.dir/build.make:4696: Source/CMakeFiles/CMakeLib.dir/cmGlobalXCodeGenerator.cxx.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2115: Source/CMakeFiles/CMakeLib.dir/all] Error 2
> make: *** [Makefile:166: all] Error 2

**Review by AndersonTorres — CHANGES_REQUESTED** [review]
Regenerate and fixup the patch.

**Comment by AndersonTorres** [comment]
Given the complete failure to build it on Darwin, I will restart this.

https://github.com/NixOS/nixpkgs/pull/206799

**Pull request closed without merging**
