### PR TITLE
jetbrains: 2023.1.2 -> 2023.1.4

### PR DESCRIPTION
**Pull request by dritter**
jetbrains.clion: 2023.1.3 -> 2023.1.4
jetbrains.dataspell: 2023.1.2 -> 2023.1.3
jetbrains.gateway: 2023.1.2 -> 2023.1.3
jetbrains.goland: 2023.1.2 -> 2023.1.3
jetbrains.pycharm-community: 2023.1.2 -> 2023.1.3
jetbrains.pycharm-professional: 2023.1.2 -> 2023.1.3
jetbrains.rider: 2023.1.2 -> 2023.1.3
jetbrains.ruby-mine: 2023.1.2 -> 2023.1.3
jetbrains.webstorm: 2023.1.2 -> 2023.1.3

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dritter** [comment]
Result of `nixpkgs-review pr 239257` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.dataspell</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Comment by dritter** [comment]
Manually checked all Programs on `x86_64-linux`. All worked fine.

**Comment by dritter** [comment]
Result of `nixpkgs-review pr 239257` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.dataspell</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Comment by thomasfire** [comment]
Is there any information when this PR to be merged?

**Comment by pbek** [comment]
This might have interfered with #240521, see https://github.com/NixOS/nixpkgs/pull/240521#issuecomment-1627648790. Any ideas?

**Comment by dritter** [comment]
Hmm. Unfortunately not. My guess is that the plugins.json needs an update? My PR updated the IDEs mostly to the build number greater than `231.9161.40`, and the plugins.json seem to max at `231.9161.38`..

So I guess I need to update the plugins as well every time the IDEs are updated (and test with plugins)..

**Pull request merged**
