### PR TITLE
raul: 2017-07-23 -> 2019-12-09

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build raul

**Comment by markuskowa** [comment]
nix-review reveals that ingen that this breaks `ingen`:
```
builder for '/nix/store/02a84ixfb36wm7w0hyz1c0qcqapnjx26-ingen-unstable-2017-07-22.drv' failed with exit code 1; last 10 log lines:
  ['g++', '-I/build/ingen-cc4a4db', '-DNDEBUG', '-fshow-column', '-std=c++11', '-pthread', '-fPIC', '-I/build/ingen-cc4a4db/build', '-I/build/ingen-cc4a4db', '-I/nix/store/bgqcjx6wm42kjfdf9z7p38bpqcw7jsa8-glibmm-2.60.0-dev/include/glibmm-2.4', '-I/nix/store/kvxjm0d8ykl5j00y9h95b2z5f8skb4bz-glibmm-2.60.0/lib/glibmm-2.4/include', '-I/nix/store/n5czm0273cibw9gz3q6pnahahmbkkwlj-glib-2.60.3-dev/include', '-I/nix/store/n5czm0273cibw9gz3q6pnahahmbkkwlj-glib-2.60.3-dev/include/glib-2.0', '-I/nix/store/2y67xgagcx6bsinykrg8wc1jgw1gnfx2-glib-2.60.3/lib/glib-2.0/include', '-I/nix/store/jhbgsw23qbyb3f59ghckxc6i5mp0gx0i-libsigc++-2.10.1/include/sigc++-2.0', '-I/nix/store/jhbgsw23qbyb3f59ghckxc6i5mp0gx0i-libsigc++-2.10.1/lib/sigc++-2.0/include', '-I/nix/store/6f36bs1bw4628ay4861wqdi09x7cmviq-lv2-unstable-2017-07-08/include', '-I/nix/store/qa9243g07av0xhb2qz9829gbys8pssa3-lilv-0.24.4/include/lilv-0', '-I/nix/store/bwcsgwwjp3gzgch9zbylkbqddcrf76s5-serd-0.30.0/include/serd-0', '-I/nix/store/k57v8g23d9ynx0i3dp581ciwnw2kqlgl-sord-0.16.2/include/sord-0', '-I/nix/store/akj0wngm1h2mhqakmalcaqpnjvlz7kgv-sratom-0.6.2/include/sratom-0', '-I/nix/store/m7a9k5f8fs20rs7n7nzpd0fi8l9a6ans-raul-unstable-2019-03-17/include', '-I/build/ingen-cc4a4db/build', '-DHAVE_GCOV=1', '-DHAVE_BOOST_FORMAT_HPP=1', '-DHAVE_BOOST_INTRUSIVE_SLIST_HPP=1', '-DHAVE_BOOST_INTRUSIVE_PTR_HPP=1', '-DHAVE_BOOST_OPTIONAL_HPP=1', '-DINGEN_HAVE_THREAD_LOCAL=1', '-DHAVE_POSIX_MEMALIGN=1', '-DHAVE_ISATTY=1', '-DHAVE_VASPRINTF=1', '-DHAVE_LIBDL=1', '-DHAVE_SOCKET=1', '-DPYTHONDIR="/nix/store/spf7cq0wr8pk6f0vn4rw8b7i5xpmrbjh-ingen-unstable-2017-07-22/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/nix/store/spf7cq0wr8pk6f0vn4rw8b7i5xpmrbjh-ingen-unstable-2017-07-22/lib/python2.7/site-packages"', '-DINGEN_BUILD_LV2=1', '-DHAVE_JACK_METADATA=1', '-DHAVE_JACK_PORT_RENAME=1', '-DINGEN_JACK_SESSION=1', '-DINGEN_SHARED=1', '-DINGEN_VERSION="0.5.1"', '-DINGEN_BUILD_CLIENT=1', '-DINGEN_BUILD_GUI=1', '-DHAVE_JACK_MIDI=1', '-DINGEN_DATA_DIR="/nix/store/spf7cq0wr8pk6f0vn4rw8b7i5xpmrbjh-ingen-unstable-2017-07-22/share/ingen"', '-DINGEN_MODULE_DIR="/nix/store/spf7cq0wr8pk6f0vn4rw8b7i5xpmrbjh-ingen-unstable-2017-07-22/lib"', '-DINGEN_BUNDLE_DIR="/nix/store/spf7cq0wr8pk6f0vn4rw8b7i5xpmrbjh-ingen-unstable-2017-07-22/lib/lv2/ingen.lv2"', '-DHAVE_GLIBMM=1', '-DHAVE_LV2=1', '-DHAVE_LILV=1', '-DHAVE_RAUL=1', '-DHAVE_SERD=1', '-DHAVE_SORD=1', '-DHAVE_SRATOM=1', '../src/Log.cpp', '-c', '-o', '/build/ingen-cc4a4db/build/src/Log.cpp.1.o']
   -> task in 'libingen' failed (exit status 1): 
  	{task 140737336237008: cxx World.cpp -> World.cpp.1.o}

[...]
```

**Comment by aanderse** [comment]
@magnetophon are you able to look into the mentioned breakage?

**Comment by magnetophon** [comment]
ingen builds now: https://github.com/NixOS/nixpkgs/pull/78102

**Comment by teto** [comment]
```
[4 built, 1 copied (0.1 MiB), 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/65152
2 package built:
ingen raul
```

**Pull request merged**
