### PR TITLE
lib/recursiveUpdateUntil: fix code to match documentation

### PR DESCRIPTION
**Pull request by bluescreen303**
###### Motivation for this change

The function `recursiveUpdateUntil` did not produce the expected result for the exact example given in the documentation.

This fixes that and makes the function useable for any predicate that actually looks at the path argument. In current nixpkgs, there is only 1 location that touches this functionality:
https://github.com/NixOS/nixpkgs/blob/75601e10cb30d5220c09c5d0cf2c8ee55fc4b34a/nixos/maintainers/option-usages.nix#L128-L131

I'm not fully sure what that is all about, but since it's maintainer-only I do not expect issues will arise because of this fix, as they probably just assumed this function worked as advertised as well.

```
$ nix repl lib
Welcome to Nix version 2.0.2. Type :? for help.

Loading 'lib'...
Added 350 variables.

-- this is the exact example from the function's documentation:
nix-repl> recursiveUpdateUntil (path: l: r: path == ["foo"]) {
                   # first attribute set
                   foo.bar = 1;
                   foo.baz = 2;
                   bar = 3;
                 } {
                   #second attribute set
                   foo.bar = 1;
                   foo.quz = 2;
                   baz = 4;
                 }
{ bar = 3; baz = 4; foo = { bar = 1; baz = 2; quz = 2; }; }

-- although the documentation says:
{
    foo.bar = 1; # 'foo.*' from the second set
    foo.quz = 2; #
    bar = 3;     # 'bar' from the first set
    baz = 4;     # 'baz' from the second set
}
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
Ping @Profpatsch 

I'd rather have the documentation changed instead of the behaviour of the function. These functions might be widely used by other projects, which we can't know of whether it would break anything.

**Comment by Profpatsch** [comment]
tbh that wouldn’t have happened if the original author spared five minutes to put the example into the tests. :disappointed: 

I’m in favour of changing this function to match its documentation, because I don’t think we really need to be bug compatible in this case.

@bluescreen303 can you add a section to the release note file in `nixos/doc/manual/release-notes/rl-1809.xml`?
I’d like to see the example as a test in `lib/tests/misc.nix` as well.

**Comment by Infinisil** [comment]
Ping?

**Comment by Profpatsch** [comment]
@Infinisil added the test & release note, what do you say?

**Comment by Infinisil** [comment]
@GrahamcOfBorg eval

**Review by infinisil — APPROVED** [review]
@Profpatsch Looking good

**Pull request merged**
