### PR TITLE
spotify-tui: init at 0.5.0

### PR DESCRIPTION
**Pull request by jwijenbergh**
###### Motivation for this change
Spotify-tui is a spotify terminal client.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg spotify-tui

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Pushed a simple fix for darwin. Let's rebuild.... @GrahamcOfBorg build spotify-tui

**Comment by Ma27** [comment]
Built and tested on x86_64-linux and x86_64-darwin, so let's merge this now :+1:

**Comment by Ma27** [comment]
@jwijenbergh thanks!

**Pull request merged**
