### PR TITLE
Pijul: 0.8 -> 0.10

### PR DESCRIPTION
**Pull request by P-E-Meunier**
###### Motivation for this change

New release of Pijul, now using Carnix.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
Where can one find the Cargo.lock file used for this?

**Comment by yrashk** [comment]
@Infinisil it's in the tar.gz and https://nest.pijul.com/pijul_org/pijul

@P-E-Meunier looks like 0.10.1 is almost out of the door?

**Comment by P-E-Meunier** [comment]
It is. There was an important (yet quite subtle) bug introduced by the latest so-called "bugfixes", 0.10.1 fixes it.

**Comment by yrashk** [comment]
@P-E-Meunier really looking forward to having pijul 0.10.1 in nixpkgs! :heart_eyes:

**Comment by Infinisil** [comment]
@yrashk Which tar.gz? The download page only contains one for version 0.8.3. And https://nest.pijul.com/pijul_org/pijul gives me currently an internal server error, and last time I checked the Cargo.lock file there had a conflict.

**Comment by obadz** [comment]
Wow. That's a lot of nix code. Are we saying that carnix generated nix is the best way forward for nixpkgs?

**Comment by P-E-Meunier** [comment]
It also has its upsides, such as faster compilation, and factoring out common parts of Rust crates.

One issue is redundancy, as an important part of this code describes packages that are probably used by other crates.

Another option would be to generate Nix expressions for all of crates.io (each would be *much* smaller), include that in nixpkgs (like what is done for Haskell packages), and then have much smaller package descriptions.

**Comment by Mic92** [comment]
@P-E-Meunier we would then need multiple version of different crates for this to work, no? Have tried to generating this?

**Comment by Mic92** [comment]
In node.js we take this file here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/node-packages-v6.json
and generate this blob: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/node-packages-v6.nix

**Comment by P-E-Meunier** [comment]
@Mic92: Yes, a change of feature requires a recompilation, but my guess is that if a crate is included in nixkgs, then its dependencies will be compiled too, and might be included in a channel, which would make it much faster to compile Rust code on Nix than on any other platform (except during development, where incremental compilation by `rustc`, and the fact that Cargo needs to do less than Nix, make it faster).

I just pushed a patch to https://nest.pijul.com/pmeunier/carnix which splits the output into two parts, a common one describing the crates and their dependencies (without specific versions, sort of a relaxed `Cargo.toml`), and another (pretty small) one that sets the actual versions of everything (doing part of the job of a `Cargo.lock`).

This is not ready yet, because the generated code contains a giant attrset with all the crates used in the compilation, and they still reference each other.

**Comment by P-E-Meunier** [comment]
I've just opened #40587 to fix this, waiting for it to be accepted.

**Comment by xeji** [comment]
#40622 has an alternative approach without carnix, please have a look.

**Comment by P-E-Meunier** [comment]
@xeji: yes, this has been proposed before. Honestly, I think this PR:

- yields faster compile times.
- shares build products with other Rust software installed on the system.
- stress-tests Carnix, which will get NixOS an awesome Rust ecosystem in the future (we're not 100% there yet, but thanks to the various crates already using Carnix, Carnix itself has made huge progress).

**Comment by sheganinans** [comment]
I think that Carnix seems to be the right direction in the future but I'm not sure if such a huge default.nix file is the right way to go in the current moment.

If there was some way to factor out the shared nix expressions out into their own files and then have the Pijul default.nix file reference the default.nix files that it depends on, cleaning up the main Pijul default.nix, that would be the correct solution.

I am very excited about the future of Carnix and what it will accomplish for the nix/rust ecosystem, having all of crates.io automagically built by Carnix, similarly to how Nix currently packages Haskell libraries and binaries is absolutely "The Right Thing (tm)" but this PR seems to be a bit unwieldy for a rather simple version bump. 

Either way, I think that waiting for 0.10.1 would be the right thing to do as well, since it includes an important bugfix.

**Comment by sheganinans** [comment]
After looking at the generated nix expressions a bit more, it seems pretty straight forward to me.
Mostly I just want what is best for the community.
Pijul does seem like a good binary to stress test Carnix, if there isn't much opposition maybe we can give this a try.

So @P-E-Meunier  the low hanging fruit in instance is the duplication of crates that are shared across many other libraries. Maybe instead of using Cargo.toml files directly to generate these default.nix files, you have a set of nix files that has already been generated by scraping crates.io for all versions of all libraries. For example from your generated output you could have an arrayvec.nix file with every single version:

```nix
arrayvec_0_4_7_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "arrayvec";
    version = "0.4.7";
    authors = [ "bluss" ];
    sha256 = "0fzgv7z1x1qnyd7j32vdcadk4k9wfx897y06mr3bw1yi52iqf4z4";
    inherit dependencies buildDependencies features;
};
```

Then the Pijul default.nix file would then import arrayvec.nix and all the other dependencies, select the proper versions, put them into the right slots, and then the file should be much shorter and there would be no redundancies in the generated nix expressions.

**Comment by P-E-Meunier** [comment]
As I said in an earlier comment, the new Carnix (0.8) yields very small Nix expressions, and this might even improve in the future.

**Comment by sheganinans** [comment]
Glad to hear, if thats the case, Carnix sounds close to primetime! I think
we need more input for the community. Should we wait for Carnix 0.8 PR to
be accepted, then generate Pijul 0.10.1 with Carnix 0.8, then have that
pulled?

**Comment by yrashk** [comment]
From what I can tell, Pijul 0.10.1 has been on crates.io for quite some time. @P-E-Meunier any idea when/if it is going to be in downloads?

**Comment by sheganinans** [comment]
I've closed #40622 
Please merge this branch of Pijul 0.8 -> 0.10

**Comment by nanexcool** [comment]
This failed for me on MacOS:

```
Building pijul (src/main.rs)
....
error: linking with `/nix/store/1raxjnnz5fzjl216r6w9bffprqqxw3jr-clang-wrapper-5.0.2/bin/cc` failed: exit code: 1
...
 = note: ld: library not found for -lcrypto
          clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
          
error: aborting due to previous error
builder for '/nix/store/xxshgdn9s15bqsbzjcgp0c4r29frwzs8-rust_pijul-0.10.0.drv' failed with exit code 101
error: build of '/nix/store/xxshgdn9s15bqsbzjcgp0c4r29frwzs8-rust_pijul-0.10.0.drv' failed
```

**Comment by Mic92** [comment]
This was merged in https://github.com/NixOS/nixpkgs/pull/49331

**Pull request closed without merging**
