### PR TITLE
set-source-date-epoch-to-latest.sh: ignore generated files - episode 2

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Follow up https://github.com/NixOS/nixpkgs/pull/28227

On Darwin, file modification times (mtimes) have 1 second granularity and it happens that generated files (e.g. ```".sandbox.sb"```) have exactly the same mtime as ```..```

So, the mtime comparision shouldn't actually be ```-not -newer``` but ```-older```. not ```≤``` but ```<```.
Unfortunately, ```find``` has no such option.

Here I hacked ```(mtime - 1)``` on bash which is very ugly, it would be nice if someone has the idea how to code it more succintly, or replace ```find``` with somehing else (perl one-liner?)

cc @vcunat

### CODE REVIEW

**Comment by vcunat** [comment]
Uh, getting really ugly.  No immediate ideas.

**Comment by vcunat** [comment]
except that we most likely don't want to pull perl into stdenv.

**Comment by edolstra** [comment]
The comment above it mentions https://github.com/0-wiz-0/findnewest...

**Comment by volth** [comment]
Adding ```-older``` to ```find``` would be much smaller patch than own C-coded helper (which would also need own nix derivation).

**Comment by volth** [comment]
I submitted an issue there: https://savannah.gnu.org/bugs/index.php?52129

**Comment by edolstra** [comment]
Except that we can't count on `find` having that flag, especially not on macOS.

**Comment by vcunat** [comment]
`find ... -not -newer` is there on master, for over two weeks already, and I haven't noticed any problems on Hydra or heard any complaints about it.

**Comment by orivej** [comment]
This is fairly simple with awk:
```bash
find . -type f -printf '%T@ %p\n' |
  awk -v max=0 -v limit=$(date +%s -r "$NIX_BUILD_TOP/..") \
    '{ if (max < $1 && $1 < limit) max=$1 } END { print max }'
```

**Comment by copumpkin** [comment]
> Except that we can't count on find having that flag, especially not on macOS.

@edolstra why can't we? The Darwin stdenv uses all the same findutils/coreutils/GNU stuff as Linux.

**Comment by volth** [comment]
@vcunat There won't be visible problems unless the derivation is checked to be reproducible (by specifying ```outputHash``` or executing ```nix-build``` with ```--check```). Most of the derivation are not checked. The problems appear only when I started to introduce ```outputHash``` to derivations in ```data/fonts``` and only with those derivations.

**Comment by vcunat** [comment]
I meant problems about the flags for `find` not working on Darwin or some other system.

**Comment by copumpkin** [comment]
@vcunat sorry, only just noticed this, but the Darwin stdenv doesn't bootstrap itself impurely anymore. The BSD `find` tool isn't used or even visible (unless someone explicitly reaches out to `/usr/bin` and tries to find it with sandboxing turned off) at any stage of Nix-on-Darwin anymore

**Pull request closed without merging**
