### PR TITLE
vimPlugins.coc-rust-analyzer: init at 2020-04-24

### PR DESCRIPTION
**Pull request by samhug**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zimbatm** [comment]
```
builder for '/nix/store/z9w7xnfj8awx0i1hmv47p2pixkbfi52f-node_pulp-14.0.0.drv' failed with exit code 1; last 10 log lines:
  npm ERR! errno ENOENT
  npm ERR! purescript@0.12.5 postinstall: `install-purescript --purs-ver=0.12.5`
  npm ERR! spawn ENOENT
  npm ERR! 
  npm ERR! Failed at the purescript@0.12.5 postinstall script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /build/.npm/_logs/2020-04-26T11_57_39_988Z-debug.log
```

**Comment by samhug** [comment]
@zimbatm Thanks for taking a look at this. Sorry, I should've caught that failure earlier.

I'm not very familiar with nodePackages so I'm not sure how to resolve that failure.
I've dropped the commit containing my initial run of `node-packages/generate.sh` which bumped all the versions and instead only included the commit with the subsequent run that added `nodePackages.coc-rust-analyzer`.

This reduces the scope of the PR and nixpkgs-review passes now. I'm not sure what the policy or best-practice is regarding nodePackages additions and version bumps though.

**Comment by Mic92** [comment]
The package was broken before. Not a regression of this PR.

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 86044` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages built:</summary>
<br>- vimPlugins.coc-nvim
<br>- vimPlugins.coc-rust-analyzer
<br>- vimPlugins.denite-nvim
<br>- vimPlugins.iceberg-vim
<br>- vimPlugins.julia-vim
<br>- vimPlugins.neoformat
<br>- vimPlugins.neoterm
<br>- vimPlugins.nvim-lsp
<br>- vimPlugins.tagbar
<br>- vimPlugins.tender-vim
<br>- vimPlugins.vim
<br>- vimPlugins.vim-airline
<br>- vimPlugins.vim-fugitive
<br>- vimPlugins.vim-gitgutter
<br>- vimPlugins.vim-go
<br>- vimPlugins.vim-javacomplete2
<br>- vimPlugins.vim-snippets
<br>- vimPlugins.vim-subversive
<br>- vimPlugins.vim-tmux-navigator
<br>- vimPlugins.vimtex
<br>- vimPlugins.vista-vim
</details>

**Pull request merged**
