### PR TITLE
haskellPackages.shellFor: fix value of NIX_GHC_DOCDIR

### PR DESCRIPTION
**Pull request by KAction**
Before this commit it pointed to non-existent directory, now it points to GHC
user manual. What is more important, now $NIX_GHC_DOCDIR/../.. contains
documentation with all dependenices, one subdirectory for dependency.

Closes: #150666

Ping: @sterneseemann, @maralorn

### CODE REVIEW

**Comment by maralorn** [comment]
Thanks for the PR. That looks cool.

One thing though: I don‘t know what `lib.closePropagation` does. A short inquiry only resulted in the fact that it’s deprecated  … since at least 2009. (That’s what git blame on the function gives.) Do you think there is another solution?

**Comment by maralorn** [comment]
Oh, wait. That function was there before your PR, too.^^
So I wouldn‘t impose this issue on you.

Another thing: This doesn‘t need to target staging, I suggest haskell-updates instead. **Make sure to mark the PR as draft before changing merge base to prevent mass highlights from happening.**

**Comment by maralorn** [comment]
> What is more important, now $NIX_GHC_DOCDIR/../.. contains
> documentation with all dependenices, one subdirectory for dependency.

That’s nice. But is there any tooling that actually assumes this?

**Comment by KAction** [comment]
Rebased.

**Comment by sternenseemann** [comment]
I’ll try to have a look the day after tomorrow. I would like to compare build times before and also check again how ghc-paths handles this value (and how it’s used by its reverse dependencies). E. g. if you can get doc paths of individual packages using ghc-pkg I’d prefer to hide this feature behind a flag, but we’ll see.

**Comment by KAction** [comment]
Ping?

**Pull request closed without merging**
