### PR TITLE
[23.05] qt6: 6.5.1 -> 6.5.2

### PR DESCRIPTION
**Pull request by rnhmjoj**
## Description of changes

Backport of qt6 patch release

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 246756` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>
<details>
  <summary>211 packages built:</summary>
  <ul>
    <li>activitywatch</li>
    <li>adwaita-qt6</li>
    <li>adwaita-qt6.dev</li>
    <li>albert</li>
    <li>alice-tools-qt6</li>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>aw-qt</li>
    <li>aw-qt.dist</li>
    <li>bambootracker-qt6</li>
    <li>beamerpresenter (beamerpresenter-mupdf)</li>
    <li>beamerpresenter-poppler</li>
    <li>calcmysky</li>
    <li>calibre</li>
    <li>citra-canary</li>
    <li>citra-nightly</li>
    <li>copyq</li>
    <li>cudaPackages.nsight_compute</li>
    <li>cutemaze</li>
    <li>dolphin-emu</li>
    <li>duckstation</li>
    <li>fcitx5-chinese-addons</li>
    <li>fcitx5-configtool</li>
    <li>fcitx5-skk-qt</li>
    <li>fcitx5-unikey</li>
    <li>fcitx5-with-addons</li>
    <li>gpxsee-qt6</li>
    <li>gqrx</li>
    <li>gqrx-gr-audio</li>
    <li>gqrx-portaudio</li>
    <li>haka</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>in-formant</li>
    <li>jami</li>
    <li>kemai</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>kime</li>
    <li>ladybird</li>
    <li>libsForQt5.fcitx5-qt (plasma5Packages.fcitx5-qt)</li>
    <li>maestral-gui</li>
    <li>maestral-gui.dist</li>
    <li>mediaelch-qt6</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>mozillavpn</li>
    <li>nanovna-saver</li>
    <li>nanovna-saver.dist</li>
    <li>obs-studio</li>
    <li>obs-studio-plugins.advanced-scene-switcher</li>
    <li>obs-studio-plugins.droidcam-obs</li>
    <li>obs-studio-plugins.input-overlay</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-3d-effect</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>obs-studio-plugins.obs-command-source</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-livesplit-one</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-shaderfilter</li>
    <li>obs-studio-plugins.obs-source-clone</li>
    <li>obs-studio-plugins.obs-source-record</li>
    <li>obs-studio-plugins.obs-teleport</li>
    <li>obs-studio-plugins.obs-vaapi</li>
    <li>obs-studio-plugins.obs-vintage-filter</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.wlrobs</li>
    <li>olive-editor</li>
    <li>ostinato</li>
    <li>path-of-building</li>
    <li>pgmodeler</li>
    <li>pineapple-pictures</li>
    <li>pokefinder</li>
    <li>prismlauncher</li>
    <li>prismlauncher-unwrapped</li>
    <li>punes-qt6</li>
    <li>python310Packages.pyqt6</li>
    <li>python310Packages.pyqt6-charts</li>
    <li>python310Packages.pyqt6-charts.dist</li>
    <li>python310Packages.pyqt6-webengine</li>
    <li>python310Packages.pyqt6-webengine.dev</li>
    <li>python310Packages.pyqt6-webengine.dist</li>
    <li>python310Packages.pyqt6.dev</li>
    <li>python310Packages.pyqt6.dist</li>
    <li>python310Packages.pyside6</li>
    <li>python310Packages.shiboken6</li>
    <li>python311Packages.pyqt6</li>
    <li>python311Packages.pyqt6-charts</li>
    <li>python311Packages.pyqt6-charts.dist</li>
    <li>python311Packages.pyqt6-webengine</li>
    <li>python311Packages.pyqt6-webengine.dev</li>
    <li>python311Packages.pyqt6-webengine.dist</li>
    <li>python311Packages.pyqt6.dev</li>
    <li>python311Packages.pyqt6.dist</li>
    <li>python311Packages.pyside6</li>
    <li>python311Packages.shiboken6</li>
    <li>qalculate-qt</li>
    <li>qgnomeplatform-qt6</li>
    <li>qmmp</li>
    <li>qownnotes</li>
    <li>qt6.full (qt6Packages.full)</li>
    <li>qt6.qmake (qt6Packages.qmake)</li>
    <li>qt6.qt3d (qt6Packages.qt3d)</li>
    <li>qt6.qt3d.dev (qt6Packages.qt3d.dev)</li>
    <li>qt6.qt5compat (qt6Packages.qt5compat)</li>
    <li>qt6.qt5compat.dev (qt6Packages.qt5compat.dev)</li>
    <li>qt6.qtbase (qt6Packages.qtbase)</li>
    <li>qt6.qtbase.dev (qt6Packages.qtbase.dev)</li>
    <li>qt6.qtcharts (qt6Packages.qtcharts)</li>
    <li>qt6.qtcharts.dev (qt6Packages.qtcharts.dev)</li>
    <li>qt6.qtconnectivity (qt6Packages.qtconnectivity)</li>
    <li>qt6.qtconnectivity.dev (qt6Packages.qtconnectivity.dev)</li>
    <li>qt6.qtdatavis3d (qt6Packages.qtdatavis3d)</li>
    <li>qt6.qtdatavis3d.dev (qt6Packages.qtdatavis3d.dev)</li>
    <li>qt6.qtdeclarative (qt6Packages.qtdeclarative)</li>
    <li>qt6.qtdeclarative.dev (qt6Packages.qtdeclarative.dev)</li>
    <li>qt6.qtdoc (qt6Packages.qtdoc)</li>
    <li>qt6.qtgrpc (qt6Packages.qtgrpc)</li>
    <li>qt6.qtgrpc.dev (qt6Packages.qtgrpc.dev)</li>
    <li>qt6.qthttpserver (qt6Packages.qthttpserver)</li>
    <li>qt6.qthttpserver.dev (qt6Packages.qthttpserver.dev)</li>
    <li>qt6.qtimageformats (qt6Packages.qtimageformats)</li>
    <li>qt6.qtimageformats.dev (qt6Packages.qtimageformats.dev)</li>
    <li>qt6.qtlanguageserver (qt6Packages.qtlanguageserver)</li>
    <li>qt6.qtlanguageserver.dev (qt6Packages.qtlanguageserver.dev)</li>
    <li>qt6.qtlocation (qt6Packages.qtlocation)</li>
    <li>qt6.qtlocation.dev (qt6Packages.qtlocation.dev)</li>
    <li>qt6.qtlottie (qt6Packages.qtlottie)</li>
    <li>qt6.qtlottie.dev (qt6Packages.qtlottie.dev)</li>
    <li>qt6.qtmqtt (qt6Packages.qtmqtt)</li>
    <li>qt6.qtmqtt.dev (qt6Packages.qtmqtt.dev)</li>
    <li>qt6.qtmultimedia (qt6Packages.qtmultimedia)</li>
    <li>qt6.qtmultimedia.dev (qt6Packages.qtmultimedia.dev)</li>
    <li>qt6.qtnetworkauth (qt6Packages.qtnetworkauth)</li>
    <li>qt6.qtnetworkauth.dev (qt6Packages.qtnetworkauth.dev)</li>
    <li>qt6.qtpositioning (qt6Packages.qtpositioning)</li>
    <li>qt6.qtpositioning.dev (qt6Packages.qtpositioning.dev)</li>
    <li>qt6.qtquick3d (qt6Packages.qtquick3d)</li>
    <li>qt6.qtquick3d.dev (qt6Packages.qtquick3d.dev)</li>
    <li>qt6.qtquick3dphysics (qt6Packages.qtquick3dphysics)</li>
    <li>qt6.qtquick3dphysics.dev (qt6Packages.qtquick3dphysics.dev)</li>
    <li>qt6.qtquickeffectmaker (qt6Packages.qtquickeffectmaker)</li>
    <li>qt6.qtquickeffectmaker.dev (qt6Packages.qtquickeffectmaker.dev)</li>
    <li>qt6.qtquicktimeline (qt6Packages.qtquicktimeline)</li>
    <li>qt6.qtquicktimeline.dev (qt6Packages.qtquicktimeline.dev)</li>
    <li>qt6.qtremoteobjects (qt6Packages.qtremoteobjects)</li>
    <li>qt6.qtremoteobjects.dev (qt6Packages.qtremoteobjects.dev)</li>
    <li>qt6.qtscxml (qt6Packages.qtscxml)</li>
    <li>qt6.qtscxml.dev (qt6Packages.qtscxml.dev)</li>
    <li>qt6.qtsensors (qt6Packages.qtsensors)</li>
    <li>qt6.qtsensors.dev (qt6Packages.qtsensors.dev)</li>
    <li>qt6.qtserialbus (qt6Packages.qtserialbus)</li>
    <li>qt6.qtserialbus.dev (qt6Packages.qtserialbus.dev)</li>
    <li>qt6.qtserialport (qt6Packages.qtserialport)</li>
    <li>qt6.qtserialport.dev (qt6Packages.qtserialport.dev)</li>
    <li>qt6.qtshadertools (qt6Packages.qtshadertools)</li>
    <li>qt6.qtshadertools.dev (qt6Packages.qtshadertools.dev)</li>
    <li>qt6.qtspeech (qt6Packages.qtspeech)</li>
    <li>qt6.qtspeech.dev (qt6Packages.qtspeech.dev)</li>
    <li>qt6.qtsvg (qt6Packages.qtsvg)</li>
    <li>qt6.qtsvg.dev (qt6Packages.qtsvg.dev)</li>
    <li>qt6.qttools (qt6Packages.qttools)</li>
    <li>qt6.qttools.dev (qt6Packages.qttools.dev)</li>
    <li>qt6.qttranslations (qt6Packages.qttranslations)</li>
    <li>qt6.qttranslations.dev (qt6Packages.qttranslations.dev)</li>
    <li>qt6.qtvirtualkeyboard (qt6Packages.qtvirtualkeyboard)</li>
    <li>qt6.qtvirtualkeyboard.dev (qt6Packages.qtvirtualkeyboard.dev)</li>
    <li>qt6.qtwayland (qt6Packages.qtwayland)</li>
    <li>qt6.qtwayland.dev (qt6Packages.qtwayland.dev)</li>
    <li>qt6.qtwebchannel (qt6Packages.qtwebchannel)</li>
    <li>qt6.qtwebchannel.dev (qt6Packages.qtwebchannel.dev)</li>
    <li>qt6.qtwebengine (qt6Packages.qtwebengine)</li>
    <li>qt6.qtwebengine.dev (qt6Packages.qtwebengine.dev)</li>
    <li>qt6.qtwebsockets (qt6Packages.qtwebsockets)</li>
    <li>qt6.qtwebsockets.dev (qt6Packages.qtwebsockets.dev)</li>
    <li>qt6.qtwebview (qt6Packages.qtwebview)</li>
    <li>qt6.qtwebview.dev (qt6Packages.qtwebview.dev)</li>
    <li>qt6Packages.kcoreaddons</li>
    <li>qt6Packages.kcoreaddons.bin</li>
    <li>qt6Packages.kcoreaddons.dev</li>
    <li>qt6Packages.poppler</li>
    <li>qt6Packages.poppler.dev</li>
    <li>qt6Packages.qtkeychain</li>
    <li>qt6Packages.qtpbfimageplugin</li>
    <li>qt6Packages.quazip</li>
    <li>qt6Packages.quazip.dev</li>
    <li>qt6Packages.qxlsx</li>
    <li>qtcreator-qt6</li>
    <li>qtwirediff</li>
    <li>qucs-s</li>
    <li>qutebrowser-qt6</li>
    <li>qutebrowser-qt6.dist</li>
    <li>retext</li>
    <li>retext.dist</li>
    <li>stellarium</li>
    <li>syncplay</li>
    <li>telegram-desktop</li>
    <li>texworks</li>
    <li>wireshark (wireshark-qt)</li>
    <li>wireshark.dev (wireshark-qt.dev)</li>
    <li>yuzu-early-access</li>
    <li>yuzu-mainline</li>
    <li>zeal-qt6</li>
    <li>zint</li>
    <li>zint.dev</li>
  </ul>
</details>

**Comment by rnhmjoj** [comment]
Thank you for testing!

**Comment by eval-exec** [comment]
Hello, I failed to build `qtgrpc 6.5.2`, do you have any suggestions?
```bash
@nix { "action": "setPhase", "phase": "qtPreHook" }
qtPreHook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/qf242hz9q7z07kvl92l6vcrvs4y0lmy4-qtgrpc-everywhere-src-6.5.2.tar.xz
source root is qtgrpc-everywhere-src-6.5.2
setting SOURCE_DATE_EPOCH to timestamp 1688780772 of file qtgrpc-everywhere-src-6.5.2/.QT-ENTERPRISE-LICENSE-AGREEMENT
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
fixing cmake files...
cmake flags: -GNinja -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2/share/doc/QtGrpc -DCMAKE_INSTALL_INFODIR=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/79q70482qi8968805pavqf21svapfhaz-qtgrpc-6.5.2-dev/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/79q70482qi8968805pavqf21svapfhaz-qtgrpc-6.5.2-dev/include -DCMAKE_INSTALL_SBINDIR=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/strip -DCMAKE_RANLIB=/nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/ranlib -DCMAKE_AR=/nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/s7p5nqzyv238ny1ba7m1fk83r2b65cqp-qtgrpc-6.5.2  
-- The CXX compiler identification is GNU 12.3.0
-- The C compiler identification is GNU 12.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /nix/store/4psnynr2gp8piqsmpdpas58v5vf7r2dr-libGL-1.6.0/lib/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /nix/store/48ik6fm41v4sy5hxc6sisdbbqh8f321k-libxkbcommon-1.5.0/lib/libxkbcommon.so (Required is at least version "0.5.0") 
-- Found WrapVulkanHeaders: /nix/store/gf9wnl5dkdaz8hv51f8h505cs3pm9gws-vulkan-headers-1.3.254/include  
[0m
-- Configuration summary shown below. It has also been written to /build/qtgrpc-everywhere-src-6.5.2/build/config.summary[0m
[0m-- Configure with --log-level=STATUS or higher to increase CMake's message verbosity. The log level does not persist across reconfigurations.[0m
 
-- Configure summary:

Qt Protobuf tools:
  Qt Protobuf generator .................. yes
Qt GRPC:
  gRPC support ........................... yes
  Native gRPC support .................... yes
Qt GRPC tools:
  Qt GRPC generator ...................... yes
 
[0m[0m
-- Configuring done (9.3s)
-- Generating done (0.1s)
[33mCMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_POLICY_DEFAULT_CMP0025

[0m
-- Build files have been written to: /build/qtgrpc-everywhere-src-6.5.2/build
cmake: enabled parallel building
cmake: enabled parallel installing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j12
[1/63] Generating ../../mkspecs/modules/qt_lib_protobuf_private.pri
[2/63] Running syncqt.cpp for module: QtProtobuf
[3/63] Running syncqt.cpp for module: QtGrpc
[4/63] Generating ../../mkspecs/modules/qt_lib_grpc_private.pri
[5/63] Generating version linker script for target Protobuf
[6/63] Generating version linker script for target Grpc
[7/63] Automatic MOC for target Protobuf
[8/63] Generating prl file for target Protobuf
[9/63] Generating pc file for target Qt6::Protobuf
[10/63] Running AUTOMOC file extraction for target Protobuf
[11/63] Building CXX object src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/options.cpp.o
[12/63] Building CXX object src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/generatorbase.cpp.o
FAILED: src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/generatorbase.cpp.o 
/nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/g++ -DPROTOBUF_USE_DLLS -I/build/qtgrpc-everywhere-src-6.5.2/src/tools/qtprotoccommon -DNDEBUG -O2 -std=gnu++17 -fPIC -Wall -Wextra -MD -MT src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/generatorbase.cpp.o -MF src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/generatorbase.cpp.o.d -o src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/generatorbase.cpp.o -c /build/qtgrpc-everywhere-src-6.5.2/src/tools/qtprotoccommon/generatorbase.cpp
/build/qtgrpc-everywhere-src-6.5.2/src/tools/qtprotoccommon/generatorbase.cpp:8:10: fatal error: google/protobuf/stubs/logging.h: No such file or directory
    8 | #include <google/protobuf/stubs/logging.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[13/63] Running moc --collect-json for target Protobuf
[14/63] Building CXX object src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/qprotobufgenerator.cpp.o
FAILED: src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/qprotobufgenerator.cpp.o 
/nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/g++ -DPROTOBUF_USE_DLLS -DQT_DISABLE_DEPRECATED_UP_TO=0x050000 -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_LEAN_HEADERS=1 -DQT_NO_AS_CONST=1 -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_WARN_DEPRECATED_UP_TO=0x070000 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/build/qtgrpc-everywhere-src-6.5.2/src/tools/qtprotobufgen -I/build/qtgrpc-everywhere-src-6.5.2/build/src/tools/qtprotobufgen -I/build/qtgrpc-everywhere-src-6.5.2/src/tools/qtprotoccommon -isystem /nix/store/vdj63pdmwss2vvxliris26wnmr8ydyhi-qtbase-6.5.2/mkspecs/linux-g++ -DNDEBUG -O2 -std=c++17 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fno-exceptions -Wsuggest-override -MD -MT src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/qprotobufgenerator.cpp.o -MF src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/qprotobufgenerator.cpp.o.d -o src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/qprotobufgenerator.cpp.o -c /build/qtgrpc-everywhere-src-6.5.2/src/tools/qtprotobufgen/qprotobufgenerator.cpp
/build/qtgrpc-everywhere-src-6.5.2/src/tools/qtprotobufgen/qprotobufgenerator.cpp:20:10: fatal error: google/protobuf/stubs/logging.h: No such file or directory
   20 | #include <google/protobuf/stubs/logging.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[15/63] Building CXX object src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/main.cpp.o
[16/63] Building CXX object src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/utils.cpp.o
[17/63] Building CXX object src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/commontemplates.cpp.o
[18/63] Building CXX object src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/baseprinter.cpp.o
[19/63] Building CXX object src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/enumdefinitionprinter.cpp.o
[20/63] Building CXX object src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/enumdeclarationprinter.cpp.o
[21/63] Building CXX object src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/messagedefinitionprinter.cpp.o
[22/63] Building CXX object src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/generatorcommon.cpp.o
[23/63] Building CXX object src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/messagedeclarationprinter.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by NickCao** [comment]
> Hello @rnhmjoj , I failed to build `qtgrpc 6.5.2`, do you have any suggestions?

This could be due to the protobuf update in https://github.com/NixOS/nixpkgs/pull/244539

**Pull request merged**
