### PR TITLE
nixos/networkmanager: split modemmanager into a separate module

### PR DESCRIPTION
**Pull request by uninsane**
## Description of changes

this does not change any default behavior: it's just refactoring for easier development and use.

- separate modemmanager bits into `modemmanager.nix`.
- give the two modules their own `enable` option, with networkmanager enabling modemmanager by default.
  neither one of these is _dependent_ on the other -- they're just commonly used together. now our nixos modules reflect that.
- give each module its own `package` option.
  networkmanager and modemmanager somehow end up as inputs to a lot of other packages, so now we can iterate the service-specific parts without mass-rebuilding (for example, the possibility to run NetworkManager as its own user instead of root may require patching the actual package).
- introduce a `networking.networkmanager.enableDefaultPlugins` option, default true, to give an easier way to deploy without the plugins. several of the plugins are costly to build (requiring e.g. `webkitgtk` for captive portals) or don't even build for all platforms (especially cross-platform builds).
  
## Things done

- [x] deployed to a x86_64 ethernet-only box, an x86_64 ethernet + wifi box, an x86_64 wifi-only box, and an aarch64 wifi + cellular modem box.
- Built on platform(s)
  - [x] x86_64-linux  (and `pkgsCross.aarch64-multiplatform`)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Janik-Haag** [comment]
This is a reasonable change, but I quit nixpkgs, and thus won't be reviewing this.

**Comment by uninsane** [comment]
i've updated `meta.maintainers` to just be `lib.teams.freedesktop.members`. i'm willing to take on formal maintainership at least for modemmanager, or for networkmanager itself in a more limited role (i.e. testing) -- if the FDO team would want that.

**Review by Enzime — APPROVED** [review]
LGTM

**Review by misuzu — COMMENTED** [review]
Needs a release notes entry and nixfmt, LGTM otherwise

**Comment by jtojnar** [comment]
Sorry, forgot about this.

- Separate ModemManager module sounds reasonable – the NM module should never have gotten so big in the first place.
- The addition of Freedesktop maintainers are fine with me, though I will want to move the declarative NM config stuff out since I have no capacity to maintain that. But that can be done separately.
- `package` options should be acceptable in this case to reduce rebuilds, though not as critical as in the past now that NM is no longer a mass rebuild trigger through libproxy/webkitgtk.
- Still not sure about `enableDefaultPlugins` option design, might be better to split it into separate PR so that we can merge this one.

**Comment by uninsane** [comment]
> Needs a release notes entry and nixfmt, LGTM otherwise

done and done. nixos-manual-build CI is showing red, but i don't understand the error and the manual builds fine for me locally with the same command (`nix-build nixos/release.nix -A manual.x86_64-linux`).

>Still not sure about `enableDefaultPlugins` option design, might be better to split it into separate PR so that we can merge this one.

removed the `enableDefaultPlugins` patch for the time being. if someone else has interest in that part i'll let them [resurrect it](https://github.com/uninsane/nixpkgs/commit/266b26d5d6951a472526edd6cda651873be0e16c) (feel free to tag me on that), otherwise seems like it's probably not worth pushing for.

**Comment by misuzu** [comment]
> nixos-manual-build CI is showing red

Rerunning the action fixed the manual issue, but nixfmt check didn't pass

**Comment by uninsane** [comment]
formatted; CI shows green

**Review by misuzu — APPROVED** [review]

**Pull request merged**
