### PR TITLE
Fix/dictd python3 update

### PR DESCRIPTION
**Pull request by barryfm**
###### Description of changes
Updated dictdDBs.wiktionary: To update python2 -> python3

###### Things done

This effects the pkgs/servers/dict/wiktionary/ Files:

  - default.nix:  Change python2 -> python3 references
  - latest_version.py: Updates for python3, decodes('utf-8') no longer needed
  - wiktionary2dict.py: Updates for python3 and 'import codesc' no longer needed.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
       - [x] Created a `nixos-install test` of my computer using flakes and this nixpkgs.
       - [x]  Checked out some trials of the dict command using the locally build dictd server.

  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by barryfm** [comment]
I layered my changes on top of the dictdDBs.wordnet change by Lucias Hoffman

**Review by SuperSandro2000 — COMMENTED** [review]
lets squash the wordnet commits together if they are all about the same package.

**Comment by barryfm** [comment]
The wordnet patches were by @lucc and part of a different pull request.

**Comment by lucc** [comment]
I have been able to build the wordnet dictd package from my commits.  You can use and/or squash them as you wish.

**Comment by SuperSandro2000** [comment]
> The wordnet patches were by @lucc and part of a different pull request.

They still belong together and do one thing: convert the scripts to python3.

**Pull request merged**
