### PR TITLE
[staging-20.03] fontforge: 20190413 -> 20200314

### PR DESCRIPTION
**Pull request by davidak**
###### Motivation for this change

I noticed that the version in stable has vulnerabilities.

https://repology.org/project/fontforge/cves?version=20190413

Not sure why it was not backported.

https://github.com/NixOS/nixpkgs/issues/88291

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
I think this is a good idea, although I guess the generated fonts don't inherit the vulnerability. So it's only users of fontforge itself that are at risk, not users of the huge number of reverse dependencies of fontforge.

Could you target the `staging-20.03` branch? `fontforge` rebuilds a lot.

**Comment by davidak** [comment]
the staging channel is 6 days behind. so it seems i have to create the branch again...

**Comment by erictapen** [comment]
@davidak You could rebase: `git rebase -i origin/staging-20.03` and then delete all the lines with commits you don't want.

**Comment by davidak** [comment]
Ah, yes. That works.

**Review by erictapen — APPROVED** [review]
I just successfully built `fontforge-gtk` and I verified that `pkgs/development/libraries/libuninameslist/default.nix` and `pkgs/tools/misc/fontforge/default.nix` have the same content as in e9848d11ad038d4077948f14986496ccb14e11bc, so I think this backport is safe to go.

Also `fontforge` afaik only ever generates fontfiles for other derivations, so no concerns about breaking reverse dependencies from my side.

**Review by erictapen — APPROVED** [review]

**Pull request merged**
