### PR TITLE
Take maintainership for a few packages

### PR DESCRIPTION
**Pull request by matthiasbeyer**
#### Motivation for this change

Leon (@lschuermann) has informed me that he has too little time to take care of these, so I would like to take maintainership.
Some things are still maintained by Leon, though, as I do not feel confident in taking maintainership of these things (mainly services, esp. services I do not use myself).

Waiting for approval of @lschuermann

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
These patches should, if approved, probably be backported to nixos-20.03 and nixos-20.09.

**Comment by lschuermann** [comment]
Currently I'm at capacity and hence appreciate the effort @matthiasbeyer. In the future I'd be very interesting in continuing to maintain and further develop these and hence would create a PR to revert the change. Does this work for you @matthiasbeyer?

**Comment by SuperSandro2000** [comment]
If we don't replace but add the maintainer we don't need to revert in the future.

**Comment by matthiasbeyer** [comment]
Everything alright for me, thanks!

> If you don't replace but add the maintainer you don't need to revert in the future.

Yes, but I would like to give maintainership _back_ then, not just drop maintainership for me.
Like, I would take it temporarily but if Leon takes it back, give it back completely.

So this is exactly as intended.

**Review by jonringer — APPROVED** [review]

**Pull request merged**
