### PR TITLE
pythonpackages.thrift: 0.9.3 -> 0.10.0

### PR DESCRIPTION
**Pull request by pmiddend**
###### Motivation for this change

thrift-0.10.0 was released some time ago.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
Please change commit message part "increase version to 0.10.0" to "0.9.3 -> 0.10.0".

**Comment by Mic92** [comment]
We also need a separate version for `0.9` as this is needed for [pycassa](https://github.com/pycassa/pycassa/commit/33cbcc7ea62870f23b645fd26df64ec3e4d29f1f)

This package can be called `thrift_0_9` in `python-packages.nix`

**Comment by FRidh** [comment]
Let's not have multiple versions of one package inside `python-packages.nix`, because that will open the possibility again for collisions.

If our current packages break with the new version, then I think we should stick with the current version of `thrift`, unless its very outdated/broken/insecure.

**Comment by flokli** [comment]
@FRidh Does this mean this PR should be closed?

Currently, the situation is a bit of a mess, as there is (latest) `thrift` in top-level (with the python-bindings inside, too), and the (older) `thrift` in `python2Packages`, and it's not really obvious it is like that.

Maybe the python bindings should be split out of the `thrift` top-level package (and moved to `pythonPackages.thrift`), and the old thrift bindings hidden somewhere iside a let-expression or an override, if `thrift_0_9` in pythonPackages is not desired.

The issue in cassandra is tracked here: https://github.com/pycassa/pycassa/issues/245

**Comment by FRidh** [comment]
@flokli how is the `python-packages.nix` version supposed to work if it doesn't depend on all on the library in `all-packages.nix`?

**Comment by FRidh** [comment]
Closing because of inactivity.

**Pull request closed without merging**
