### PR TITLE
nixos/manual: clarify declarative packages section

### PR DESCRIPTION
**Pull request by aaronjanse**
###### Motivation for this change
The declarative package management gives a straightforward explaination of installing packages in NixOS, but assumes knowledge of Nix variables and knowledge of channels.

This leads to confusions such as #55556, where a user confused `nixos` and `pkgs` as almost interchangable.

This pull request elaborates on what the `pkgs` variable means (it's a reference to the root channel) and what the `nixos` prefix in a full package path means (it's the channel you are getting the package from).

This should allow a user to use the variable `pkgs` and the `nixos` prefix without needing an explaination of what they mean.

Although it doesn't explain what a channel is, it hopefully makes sense without knowing the full definition, and if a user is confused, they should have a clear question to ask (i.e. "what is a channel?").

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) 
on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danbst** [comment]
Hm, what about this instead? After this code example:
```
$ nix-env -qaP '*' --description
nixos.firefox   firefox-23.0   Mozilla Firefox - the browser, reloaded
...
```
place

> Note: the `nixos` prefix tells us that we want to get the package from the `nixos` channel and works only in CLI tools. In declarative configuration use `pkgs` prefix (variable).

A note about `pkgs` being a variable is fine, but it isn't root channel. It is root's `nixos` channel. Not sure how to communicate this better.

**Comment by aaronduino** [comment]
The HEAD commit formerly did not have the content it's description implied (rather it was just a revert commit iirc). I have force pushed [1] to make the commit match your suggestion @danbst 

[1] I assume that's acceptable because as far as I know, I'm the only one checking out this branch

**Review by danbst — APPROVED** [review]
Looks OK to me, I wish @AMDphreak have verified that this indeed clarifies section.

**Comment by AMDphreak** [comment]
Suggested modification: 

> Note: the nixos prefix tells us that we want to get the package from the nixos channel and works only in CLI tools. In declarative configuration use pkgs variable as a prefix, i.e. `pkgs.app_name_goes_here`.

So, the `pkgs` variable points to the `nixos` channel, but we can't access the `nixos` channel by name, because the user can only refer to variables passed into the scope of the Nix expression? Let me know if I read this right. I'm thinking the word "variable" is becoming a liability in this explanation, since people will likely think of the meaning of "variable" in the procedural way (stored value), rather than the functional way ("let" binding). There may need to be an introduction to the nomenclature of functional languages when the reader first encounters the concept of a name binding.

**Comment by danbst** [comment]
> Is the nixos channel owned by root? This would seem to imply that there is a nixos channel not owned by root. What's the story here?
It's possible to define `nixos` channel in user's channels. It can be used by `nixos-rebuild build`, but won't be used by `nixos-rebuild switch`, because you call usually `sudo nixos-rebuild switch`, thus root's channel is active.

as for variable thing: I really really wish we had documentation with ability to add comments in-place to each section. Like Google Docs annotations, or Mercurial book (which has comments to each paragraph).

> Let me know if I read this right: 
correct! 

> I'm thinking readers will interpret the word "variable" as the meaning of "variable" in the procedural programming paradigm (stored value), rather than the functional paradigm ("let" binding).
That depends on reader. I like to think about let-bindings as immutable variables, because you can reassign them whenever you want. But I also like your suggestion.

**Pull request merged**
