### PR TITLE
Downgrade llvmPackages_latest to 12 on Darwin

### PR DESCRIPTION
**Pull request by midchildan**
###### Motivation for this change

The recent upgrade of `llvmPackages_latest` to `llvmPackages_13` broke a number of packages that depend on it, due to `llmvPackages_13.libcxx` (and by extension, `llvmPackages_13.clang`) being marked as broken. This reverts those changes on Darwin. It should fix the builds of the following packages:

* clang-analyzer
* clang-tools
* lldb
* ccls

Relates to: #140783, #140783
ZHF: #144627

###### Things done

Since building from the staging branch triggered an overwhelming amount of local builds, I've tested on the `master` branched and rebased against `staging`.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg eval

**Comment by jonringer** [comment]
I would prefer to fix why they are broken, rather than just "rolling" back. However that's a lot more work.

**Comment by jonringer** [comment]
@ofborg eval

**Comment by midchildan** [comment]
For an actual fix, building `llvmPackages_13` with `llvmPackages_12.stdenv` seems to fix the [original problem](https://github.com/NixOS/nixpkgs/pull/133217#issuecomment-895742807) and makes the compile phase succeed, but then it fails when linking the dynamic binary. I haven't found a solution to this yet, and judging from the package definitions, neither [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb) nor [Macports](https://github.com/macports/macports-ports/blob/master/lang/llvm-13/Portfile) seem to suffer from this problem.



```
[ 97%] Linking CXX static library ../lib/libc++.a
/nix/store/hzkyp1z5amrp9b01hiim19p1wwyf1hjz-cctools-port-949.0.1/bin/ranlib: file: ../lib/libc++.a(functional.cpp.o) has no symbols
/nix/store/3sp84cykwfbyxyyzy5y8dxifgfhs1bx0-cctools-binutils-darwin-949.0.1/bin/ranlib: file: ../lib/libc++.a(functional.cpp.o) has no symbols
[ 98%] Linking CXX shared library ../lib/libc++.dylib
[ 98%] Built target cxx_static
ld: requested re-export symbol std::set_unexpected(void (*)()) is not from a dylib, but from CMakeFiles/cxx_shared.dir/exception.cpp.o
 file 'CMakeFiles/cxx_shared.dir/exception.cpp.o' for architecture x86_64
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/cxx_shared.dir/build.make:737: lib/libc++.1.0.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:471: src/CMakeFiles/cxx_shared.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by midchildan** [comment]
I've enabled `llvmPackages.llvm-manpages` in a572e7e249be8cdf144caa144f3861a4b48d4f50, since the lack of it seemed to be causing the ofborg failures.

**Comment by midchildan** [comment]
Closing in favor of #147289.

**Comment by midchildan** [comment]
Reopening because https://github.com/NixOS/nixpkgs/pull/147289#issuecomment-978180579.

**Comment by midchildan** [comment]
Re-closing because https://github.com/NixOS/nixpkgs/pull/147289 is now working.

**Pull request closed without merging**
