### PR TITLE
chefdk: 0.4.0 -> 0.10.0

### PR DESCRIPTION
**Pull request by whiteley**
I tried to update this in it's current configuration but also I'd like to point out that I don't feel the average user installing this will be receiving what they expect. The `chef-dk` gem is installed but the downloadable packages for `chefdk` include many other packages as well.

The packages are created using the Chef omnibus tool as defined here:
https://github.com/chef/omnibus-chef/blob/master/config/projects/chefdk.rb

I'd like to work on more fully supporting this need but I'm not sure if it would need to be packaging each individual dependency separately or what. If so, that creates the additional problem of how to define the meta package that would pull in all the tools.

I tested this by installing with `nix-build` and running `knife` for some basic tasks without issue.

### CODE REVIEW

**Comment by jagajaga** [comment]
Please create the same PR but to the master branch.

**Comment by whiteley** [comment]
My question was missed, could someone please suggest the best place for that discussion?

**Comment by rvlander** [comment]
I installed chefdk yesterday. It seems like berks in not available in the PATH. Any idea why?

**Comment by rvlander** [comment]
```bash
$> chef --version                     
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
/nix/store/0px3rvamwkj3mhnygz48pd7qh5hwxdbj-chefdk-0.10.0/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.2.5/lib/mixlib/shellout/unix.rb:338:in `exec': No such file or directory - berks (Errno::ENOENT)
...
```

**Comment by whiteley** [comment]
@rvlander yes absolutely, the problem is clearly described in my initial comment of this PR. The `chef-dk` rubygem is installed NOT the `chefdk` [package](https://downloads.chef.io/chef-dk/).

**Comment by rvlander** [comment]
@whiteley sorry I hadn't read your first comment. Personnally, I would expect all to be package in chefdk.

**Comment by rvlander** [comment]
@whiteley any decision made yet?

**Comment by whiteley** [comment]
@rvlander I was asking for direction from someone more involved with the project and have not received any. I won't be moving on this until that happens.

**Pull request merged**
