### PR TITLE
Remove libgsystem

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
`libgsystem` is deprecated. It is only required by `rpm-ostree`, updating will allow us to drop it.

Update, clean up dependencies, and add installed tests.

Tests currently fail see https://github.com/ostreedev/ostree/issues/1593 and https://github.com/ostreedev/ostree/issues/1592

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
If someone figures out how to fix the five failing tests please let me know.

**Comment by copumpkin** [comment]
Thanks! In principle it looks good but I don't use ostree anymore so can't really test it in any sort of realistic workflow. Happy to merge if it's ready though.

**Comment by jtojnar** [comment]
There is no hurry, we can probably wait for a patch for https://github.com/ostreedev/ostree/issues/1592.

**Comment by jtojnar** [comment]
@GrahamcOfBorg test ostree

**Pull request merged**
