### PR TITLE
coqPackages.contribs.zorn-lemmas: 8.6.0 -> 8.8.0

### PR DESCRIPTION
**Pull request by Zimmi48**
Update zorn-lemmas Coq package. This is untested for now.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Now tested with Coq 8.6 -> 8.9. However, the version number is fake because no version compatible with Coq 8.9 has been tagged yet. So maybe we should wait on this before merging.

BTW, I think the `contribs` attribute set should be reexported as part of `coqPackages` as I did when introducing the `janeStreet` attribute set in `ocamlPackages` (see https://github.com/NixOS/nixpkgs/pull/25658/files#diff-10ffb37397df96f7c25aff8aaecefd78R876). WDYT @vbgl? That being said, contribs that are kept up-to-date with recent Coq versions are slowly being moved to coq-community (which also includes packages that were not contribs previously) so maybe we should just split these packages out of the `contribs` attribute set one by one.

**Comment by vbgl** [comment]
@GrahamcOfBorg build coqPackages.contribs.zorn-lemmas

**Comment by vbgl** [comment]
@GrahamcOfBorg build coqPackages.contribs.zorns-lemma

@Zimmi48 There is a typo in the commit message ;-)

**Comment by vbgl** [comment]
Cherry-picked into master as b6a6f7ac989.

**Pull request closed without merging**
