### PR TITLE
fedora-coreos-config-transpiler: use upstream vendor

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ruuda** [comment]
I’m not really familiar with the Go ecosystem myself, I added the `vendorSha256` because @flokli recommended it [here](https://github.com/NixOS/nixpkgs/pull/91057#discussion_r442499270). What are the differences between having `vendorSha256 = null` vs `deleteVendor = true`?

**Comment by zowoq** [comment]
As upstream has a [`/vendor`](https://github.com/coreos/fcct/tree/v0.6.0/vendor) checked in to their repo `vendorSha256 = null` should be sufficient, `deleteVendor` isn't needed unless the deps are incomplete/broken.

**Review by danieldk — COMMENTED** [review]
LGTM

Result of `nixpkgs-review pr 93392` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- fedora-coreos-config-transpiler
</details>

Confirmed that the binary works.

**Comment by ruuda** [comment]
> As upstream has a /vendor checked in to their repo vendorSha256 = null should be sufficient, deleteVendor isn't needed unless the deps are incomplete/broken.

Ah, I see, thanks for the clarification!

**Pull request merged**
