### PR TITLE
Munin: Fix broken plugins

### LINKED ISSUE #23049: munin-node service: apc_nis plugin is enabled and throws errors
## Issue description
When I enable munin, the `apc_nis` plugin gets enabled automatically and is periodically throwing errors:
```
Error output from apc_nis:
Could not create socket: Connection refused
Service 'apc_nis' exited with status 111/0.
```
According to the plugin description, „apc_nis - Plugin to monitor APC UPS via the nis port of apcupsd“. I don't have any UPS running, though. Any idea why this plugin is enabled automatically, or how to disable it? Should I report that as an upstream bug?

### Steps to reproduce
`services.munin-node.enable = true;`

## Technical details

* System: NixOS 17.03pre101636.183eeb3 (Gorilla)
* Nix version:  nix-env (Nix) 1.11.6
* Nixpkgs version: 17.03pre101636.183eeb3

### PR DESCRIPTION
**Pull request by orbekk**
###### Motivation for this change

The munin-node service used wrapProgram to inject environment variables.
This doesn't work because munin plugins depend on argv[0], which is
overwritten when the executable is a script with a shebang line.

Instead, rely on environment variables passed to the systemd units. This
requires another minor patch to munin.

Also fixes https://github.com/NixOS/nixpkgs/issues/23049 by disabling the
apc_nis plugin.

###### Things done

The munin.nix test passes.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by domenkozar** [comment]
@jpierre03 @bjornfor

**Comment by bjornfor** [comment]
This reminds me that I tried to fix this myself, in https://github.com/bjornfor/nixpkgs/commits/munin-master. But while testing I found a regression that I couldn't solve/pinpoint, so I dropped it.

Looking at this PR, I see the same issue I was having. The list of enabled plugins change! Look in /etc/munin/plugins with/without this PR and see the difference.

```patch
$ diff -u before-pr after-pr
--- before-pr	2017-11-22 21:05:02.266009841 +0100
+++ after-pr	2017-11-22 21:05:02.267009844 +0100
@@ -7,10 +7,21 @@
 df
 df_abs
 df_inode
+diskstat_iops_sda
+diskstat_iops_sdb
+diskstat_iops_sdc
+diskstat_iops_sdd
+diskstat_latency_sda
+diskstat_latency_sdb
+diskstat_latency_sdc
+diskstat_latency_sdd
+diskstat_throughput_sda
+diskstat_throughput_sdb
+diskstat_throughput_sdc
+diskstat_throughput_sdd
 entropy
 forks
 fw_packets
-hddtemp_smartctl
 if_docker0
 if_enp3s0
 if_enp4s0
@@ -28,7 +39,6 @@
 interrupts
 irqstats
 load
-meminfo
 memory
 munin_stats
 munin_update
@@ -42,11 +52,11 @@
 nfsd4
 open_files
 open_inodes
-port_36113
-port_38357
-port_40641
-port_42059
+port_33867
+port_34535
+port_34809
 port_51413
+port_59903
 port_apcupsd
 port_domain
 port_git
```

BTW, I don't think we should remove "apc_nis" plugin. It's easier to disable it from user config than to bring it back if deleted by the NixOS module. (Also, I have APC UPS.)

**Comment by bjornfor** [comment]
I guess the only thing strange in that diff is that the hddtemp_smartctl and meminfo plugins no longer work after applying this PR.

**Comment by orbekk** [comment]
@bjornfor I found two issues. Both hddtemp_smartctl and meminfo work for me now. 

Some plugins should run as root, hddtemp and meminfo happen to be such plugins. Added plugin level configuration to solve this. Without the wrappers, munin uses user-level state directories. This was broken with the preserve_environment.patch, so I updated it.

Some plugins are still broken (e.g., the munin plugin), but as far as I can tell there are no more regressions on the two systems I tested.

**Comment by bjornfor** [comment]
@orbekk: Great! Can you squash that last commit so each commit in the PR represents a good state? And 
 explain in the commit message what was needed to get hddtemp_smartctl and meminfo to work.

**Comment by grahamc** [comment]
@GrahamcOfBorg test munin

**Comment by orbekk** [comment]
@bjornfor Done. I'd also like to make a few extra configuration variables for Munin, but I can send a follow-up request for that.

**Comment by bjornfor** [comment]
Applied to master with bd3e49a80ec70a9619d339a03a39ba3f580fba04 and 3 parents. Thanks!

I'll backport this to release-17.09 after a round of testing.

**Comment by bjornfor** [comment]
Backported to NixOS 17.09 with 340f3067722e649b09538de12e81fcd22f12cc52 and 3 parents.

**Comment by jpierre03** [comment]
thanks.

**Pull request closed without merging**
