### PR TITLE
window-manager service: add notion

### PR DESCRIPTION
**Pull request by tftio**
Add the notion window manager to the windowManager service definition.

### CODE REVIEW

**Comment by lethalman** [comment]
Looks fine, did you test it?

**Comment by jfb** [comment]
Yep, works fine.

**Comment by jfb** [comment]
I was able to add the following to my configuration:

```nix
  services.xserver.windowManager = {
    notion.enable = true;
    default = "notion";
  };
```

... and notion starts up as expected.

**Comment by lethalman** [comment]
Great thanks!

**Pull request merged**
