### PR TITLE
llvmPackages_git.llvm: run the tests on macOS

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

Port of c7231c0b6d8 ("llvmPackages_15.llvm: run the tests on macOS").

The sysctl native check input was taken from
6d0c87602fe ("llvmPackages_15.llvm: add in a missing check dep"), because it looks like it was supposed to be part of c7231c0b6d8 instead.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
I don't understand why is there ofborg-eval errors.

**Comment by alyssais** [comment]
> I don't understand why is there ofborg-eval errors.

```
The following tests FAILED:
         15 - mutex_is_actually_mutex_test (Failed)
Errors while running CTest
make: *** [Makefile:71: test] Error 8
error: builder for '/nix/store/3v5dx5yhjq0djccja8637swzbkh5w514-aws-c-common-0.8.9.drv' failed with exit code 2;
```

So probably not related.

@OfBorg eval

**Comment by alyssais** [comment]
@OfBorg build llvmPackages_git.llvm

**Comment by alyssais** [comment]
Would somebody mind checking this build on Darwin, since OfBorg can't?

**Pull request closed without merging**
