### PR TITLE
Altcoins: Add go-ubiq

### PR DESCRIPTION
**Pull request by ob7**
This adds go-ubiq, the ubiq clone of go-ethereum, to nixpkgs.

I started by copying go-ethereum.nix from altcoins directory, but could not get it to build using buildGoPackage, so I used the standard mkDerivation instead and was able to get it to build and run successfully.

### CODE REVIEW

**Comment by ob7** [comment]
How do I get this merged?

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build go-ubiq

**Review by matthewbauer — CHANGES_REQUESTED** [review]
see @GrahamcOfBorg log

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Pull request closed without merging**
