### PR TITLE
pcsx2: unstable-2020-11-13 -> unstable-2021-10-28

### PR DESCRIPTION
**Pull request by SuperSamus**
###### Things done

Bumped the version and tested a game.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GovanifY** [comment]
Hey, thanks for the PR! 
PCSX2 has changed quite a bit lately (eg it doesn't have plugins anymore and whatnot) so you might want to clean up a bit the cmake flags it uses! A bunch of them are now unnecessary or deprecated, such as GTK3_API, PLUGIN_DIR and PACKAGE_MODE. 

We might want to clean those up before merging a version bump.

**Comment by SuperSamus** [comment]
Done.
A few things though:

- Am I right or wrong in removing __GL_THREADED_OPTIMIZATIONS?
- I wanted to also remove DISABLE_ADVANCE_SIMD=TRUE, but without it Cmake complains that my CPU doesn't support SSE 4.1 `#error PCSX2 requires compiling for at least SSE 4.1` (when the Ryzen 4500U actually does).  The only recent thing I found about it is this: https://forums.pcsx2.net/Thread-PCSX2-on-21-04-Not-working-so-far

**Comment by GovanifY** [comment]
> Am I right or wrong in removing __GL_THREADED_OPTIMIZATIONS?

You are! See https://github.com/PCSX2/pcsx2/pull/4693


>     * I wanted to also remove DISABLE_ADVANCE_SIMD=TRUE, but without it Cmake complains that my CPU doesn't support SSE 4.1

You can add `-DARCH_FLAG="-march=native -msse4 -msse4.1"`, although this should be already set in the cmake, it might get overridden. PCSX2 requires at least SSE4.1 nowadays, so this won't make the packaging run on less machines than it could. A runtime toggle is also planned for AVX2 optimisations, but for now is a compile time build, which you can enable with `-mavx -mavx2 -mbmi -mbmi2`. Upstream will eventually move to a unique binary build system, so we shouldn't have to build it for avx, although in the meantime those optimisations will be disabled.

**Review by GovanifY — APPROVED** [review]
LGTM, all seems to install in the correct path; thanks for the scrub again!

**Review by r-burns — APPROVED** [review]
Result of `nixpkgs-review pr 143749` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pcsx2</li>
  </ul>
</details>

**Pull request merged**
