### PR TITLE
[Backport release-24.05] legcord: init at 1.0.1, armcord: remove, add throw with migration details

### PR DESCRIPTION
**Pull request by wrmilling**
## Things done

ArmCord was renamed to Legcord and re-versioned to 1.0.0 upstream, see the [release notes](https://github.com/Legcord/Legcord/releases/tag/v1.0.0) for details on this change. Updated to 1.0.1 while waiting on change reviews for this PR. 

Context and discussion can be found on the PR to unstable: https://github.com/NixOS/nixpkgs/pull/347971

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
```
       … while evaluating attribute 'buildPhase' of derivation 'legcord-1.0.0'

         at /home/emily/.cache/nixpkgs-review/pr-347988/nixpkgs/pkgs/by-name/le/legcord/package.nix:31:3:

           30|
           31|   buildPhase = ''
             |   ^
           32|     runHook preBuild

       error: attribute 'dist' missing

       at /home/emily/.cache/nixpkgs-review/pr-347988/nixpkgs/pkgs/by-name/le/legcord/package.nix:38:26:

           37|       --dir \
           38|       -c.electronDist="${electron_32.dist}" \
             |                          ^
           39|       -c.electronVersion="${electron_32.version}"
```

Not quite sure what’s going on there (source vs. binary package difference?).

**Comment by wrmilling** [comment]
> Not quite sure what’s going on there (source vs. binary package difference?).

I must have had something cached locally when I tested, thanks for the catch on this. Not knowing what else we will encounter between a source build on 24.05 vs on master, I am going to just revert to the deb-based packaging that we were doing with armcord/legcord already on 24.05 and let it be retired when 24.05 goes out of support.

**Comment by wrmilling** [comment]
@emilazy Apologies for the direct ping, could you take a second look and let me know if we need any more changes? Just want to close the loop on the armcord/legcord thing.

**Review by emilazy — APPROVED** [review]
No worries about the ping, I think I was waiting for ofborg and then forgot about it ^^;

LGTM, thank you for dealing with this.

**Pull request merged**
