### PR TITLE
blackmagic-desktop-video: refactor runpath resolution

### PR DESCRIPTION
**Pull request by Naxdy**
## Description of changes

Uses `placeholder` instead of `$ORIGIN` to determine an absolute (instead of relative) path to DesktopVideoHelper's libs. Functionally no different, but it's more in line with established nixpkgs conventions.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by hexchen — APPROVED** [review]
Looks good to me, but please do not merge this yet; I want to test it on hardware to make sure this doesn't subtly break somehow.

**Comment by Naxdy** [comment]
Semi-related: OBS needs

```nix
environment.sessionVariables = {
  LD_LIBRARY_PATH = [
    "${pkgs.blackmagic-desktop-video}/lib"
  ];
};
```

In order to be able to display the Blackmagic Capture source. Do you think it would make sense to add to the NixOS module, or could this have unforeseen side-effects in your opinion?

**Comment by hexchen** [comment]
I think that it's likely to have unwanted side-effects. My current solution is to manually override OBS to set decklinkSupport to true (see https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/obs-studio/default.nix#L51 for implementation details), but i agree that it might be nicer for something like that to be set automatically when you turn on the module.

**Review by getchoo — APPROVED** [review]

**Comment by Naxdy** [comment]
I see, makes sense. That's a bit unfortunate though, since it will prompt a full rebuild of OBS, though that's not necessary as long as it can find the library at runtime. Perhaps we can think about integrating it into `pkgs.wrapOBS` instead?

**Comment by hexchen** [comment]
Yeah, might be a more reasonable approach.

FTR: I marked this PR as "needs human intervention" cause I'd like to test that this works fine on hardware (though I am almost certain it will)

**Comment by SuperSandro2000** [comment]
That label is meant for the package upgrade bot when it created PRs which are not fully correct and need human attention before they can be merged.

**Comment by Naxdy** [comment]
@hexchen if you want, I can put it in draft to make sure no one merges it accidentally, until I get the all clear from you.

**Pull request merged**
