### PR TITLE
last: 1406 -> 1409

### PR DESCRIPTION
**Pull request by jbedo**
###### Description of changes

Bump last to lastest version.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by symphorien — CHANGES_REQUESTED** [review]
```
error: hash mismatch in fixed-output derivation '/nix/store/1ivcsray70ydcny2z0m892s7a6flhnhl-source.drv':
         specified: sha256-CaOoA/+pFtNeZTwH2vtO5ekdwA9JatbfdQBWXNm5WaI=
            got:    sha256-AFK0va1HonSWJdzJLdLraiu4LhUCJFgq6qajbbPmHuY=
```
did they force-push the tag?

**Comment by jbedo** [comment]
Wow they did. I had the old source in my store still, they updated a tag:

```
--- ./old/
+++ ./result/
│   --- ./old/src
├── +++ ./result/src
│ │   --- ./old/src/makefile
│ ├── +++ ./result/src/makefile
│ │ @@ -140,15 +140,15 @@
│ │  GeneticCodeData.hh: ../data/gc.prt
│ │     ../build/gc-inc.sh ../data/gc.prt > $@
│ │  
│ │  ScoreMatrixData.hh: ../data/*.mat
│ │     ../build/mat-inc.sh ../data/*.mat > $@
│ │  
│ │  VERSION1 = git describe --dirty
│ │ -VERSION2 = echo ' (HEAD -> main, tag: 1409) ' | sed -e 's/.*tag: *//' -e 's/[,) ].*//'
│ │ +VERSION2 = echo ' (tag: 1409) ' | sed -e 's/.*tag: *//' -e 's/[,) ].*//'
│ │  
│ │  VERSION = \"`test -e ../.git && $(VERSION1) || $(VERSION2)`\"
│ │  
│ │  version.hh: FORCE
│ │     echo $(VERSION) | cmp -s $@ - || echo $(VERSION) > $@
│ │  
│ │  FORCE:

```

**Comment by onny** [comment]
Result of `nixpkgs-review pr 188785` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>last</li>
    <li>tebreak</li>
  </ul>
</details>

**Comment by symphorien** [comment]
@jbedo you would mind opening an issue upstream to ask them politely to tag a point release or so instead of force pushing next time they are in this situation?

**Pull request merged**
