### PR TITLE
gnutls: 3.7.2 -> 3.7.3

### PR DESCRIPTION
**Pull request by vcunat**
###### Motivation for this change
Includes a low-severity security fix.
https://lists.gnupg.org/pipermail/gnutls-help/2022-January/004736.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
This is for `staging`, but for now I just wanted to get OfBorg builds without the baggage in `staging-next..staging`.

**Comment by vcunat** [comment]
Transparent KTLS support could be enabled since this version, but for me it caused trouble in the test-suite, so I abandoned it for now.

**Comment by vcunat** [comment]
@OfBorg build gnutls

**Comment by vcunat** [comment]
For `staging-21.11` I'd probably try to just pick a patch for the (low-severity) CVE.

**Comment by risicle** [comment]
Builds for me, macos 10.15 on `staging`.

**Comment by jonringer** [comment]
> For `staging-21.11` I'd probably try to just pick a patch for the (low-severity) CVE.

I don't see the harm in backporting a bugfix release

**Comment by vcunat** [comment]
It's certainly not a purely-bugfix release.  There's KTLS support added, crypto allowlisting (causing issues on Fedora together with their aggressive policies), etc.

**Comment by jonringer** [comment]
> It's certainly not a purely-bugfix release. There's KTLS support added, crypto allowlisting (causing issues on Fedora together with their aggressive policies), etc.

-_-. I know that gnutls existed before SemVer was established. But why call it a bug fix release, if there's new additions....

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 156588 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>4 packages built:</summary>  <ul>    <li>fwupd</li>    <li>kodi</li>    <li>libjcat</li>    <li>vlc</li>  </ul></details>

**Pull request merged**
