### PR TITLE
idrisPackages.heyting-algebra: remove because superseded

### PR DESCRIPTION
**Pull request by kmein**
The functionality provided by this package has been added to the Idris contrib library (module `Interfaces.Verified`).
Therefore identifiers cannot be disambiguated anymore.

###### Motivation for this change

@NixOS/backports #68361 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @brainrape

### CODE REVIEW

**Comment by Infinisil** [comment]
> The functionality provided by this package has been added to the Idris contrib library (module `Interfaces.Verified`).
> Therefore identifiers cannot be disambiguated anymore.

Can't we just remove the package then?

**Comment by kmein** [comment]
I wasn't sure about people depending on heyting-algebra and not knowing it has been superseded by the Idris libs.

**Comment by brainrape** [comment]
Shouldn't we remove the package then?

**Comment by brainrape** [comment]
If people depend on it, they will be using an older version of idris, so they might as well use an old nixpkgs version or copy this package to their project.

**Comment by brainrape** [comment]
It doesn't look like any packages in nixpkgs depend on this.

**Comment by brainrape** [comment]
My fondness of Heyting algebras notwithstanding, and given this is in Idris contrib, I think it's fine to remove the package completely - remove this file and the reference to it in `idris-modules/default.nix`. Or let me know if you don't have time, I'll do it.

**Comment by brainrape** [comment]
Thanks, looks good to merge. :+1:

**Pull request merged**
