### PR TITLE
deno: fix darwin build

### LINKED ISSUE #275375: Build failure: deno 1.39.0 on darwin
### Steps To Reproduce

1. build deno on darwin

aarch64: https://hydra.nixos.org/build/244340479
x68_64: https://hydra.nixos.org/build/244339583

### Build log

https://hydra.nixos.org/build/244339583/nixlog/1

### Notify maintainers

@06kellyjac 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.2.0, macOS 14.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/4fgs7yzsy2dqnjw8j42qlp9i1vgarzy0-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by 06kellyjac**
## Description of changes

Add missing framework for darwin

resolves: #275375

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 06kellyjac** [comment]
It might also need this `CoreGraphics` framework too.
If someone can try out this PR that'd be helpful

**Comment by 06kellyjac** [comment]
and actually if this builds we can probably remove the postPatch because a recent change here broke the substitute so it would mean it's not necessary anymore

https://github.com/denoland/deno/commit/393abed3873d83019feb5bcebb10a6929133862a

**Comment by 06kellyjac** [comment]
@xanderio

**Comment by xanderio** [comment]
Result of `nixpkgs-review pr 275377` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>deno</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.vim-pluto</li>
  </ul>
</details>

**Comment by xanderio** [comment]
@06kellyjac 

```
       > error: linking with `/nix/store/vwh2qqal1q101wv4jy40giavp73q0msd-clang-wrapper-16.0.6/bin/cc` failed: exit status: 1
       >   |
       >   = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/bin:/nix/store/30m4ghksg1dlnwfy3qybfixjwnrhgrh9-cargo-1.74.0/bin:/nix/store/6a8n27y9r10pnr653344yybxr4qpd7g9-cargo-auditable-0.6.1/bin:/nix/store/9m0szzwibi1rwp3wvn36r7w478i753ll-cmake-3.27.8/bin:/nix/store/yc7vkwp4fcz2kwwzmbd118garra589j1-ps-adv_cmds-119/bin:/nix/store/ysijl023j19h9ls25djxq43dm897v094-protobuf-24.4/bin:/nix/store/rp517rlw5kbxcwm382ap5lg0jvn4nakr-auditable-cargo-1.74.0/bin:/nix/store/30m4ghksg1dlnwfy3qybfixjwnrhgrh9-cargo-1.74.0/bin:/nix/store/i2q9ff0fpgr20zza6kr6nlpki6mn43if-rustc-wrapper-1.74.0/bin:/nix/store/vwh2qqal1q101wv4jy40giavp73q0msd-clang-wrapper-16.0.6/bin:/nix/store/3vzbr8yb4c233lhi1qz78b8kaaxrjqcj-clang-16.0.6/bin:/nix/store/pzajj7gw0nazs3vzp6jld53q8ird5izr-coreutils-9.4/bin:/nix/store/0i7w6qsij8akg6h39qn67w9ig5hirv1a-cctools-binutils-darwin-wrapper-16.0.6-973.0.1/bin:/nix/store/i4sfjfz08vmnrj84asl2j5imakga12za-cctools-binutils-darwin-16.0.6-973.0.1/bin:/nix/store/pzajj7gw0nazs3vzp6jld53q8ird5izr-coreutils-9.4/bin:/nix/store/6x5inimwy8rlvf678yy080zccbw71alb-findutils-4.9.0/bin:/nix/store/01bzxsyn8dqz9fsdhp9r6ya796g5ydmf-diffutils-3.10/bin:/nix/store/9z9k8dwhhiryr7z2pz70zca0vwa15yqc-gnused-4.9/bin:/nix/store/zsm4xd527427rnjfnvfhvsld2n57b822-gnugrep-3.11/bin:/nix/store/hhc2x65zvp89lh15grqk21r6dcvifggy-gawk-5.2.2/bin:/nix/store/gclclfhq9blxp32lv8kxm9iv5060rx5f-gnutar-1.35/bin:/nix/store/crpi4clk07gy760ydbb710f74dy8q6c9-gzip-1.13/bin:/nix/store/qay0pa86lb712162d6m5lyw62iczb71d-bzip2-1.0.8-bin/bin:/nix/store/zc9qsb0rzlw0ckhy7097frcwb4pkfx3d-gnumake-4.4.1/bin:/nix/store/6nxav88iiz0g8m598xy643f8hhdz5kkx-bash-5.2-p21/bin:/nix/store/kizmwlnj40d11ixbap74c0syaqxn05wc-patch-2.7.6/bin:/nix/store/xcy0fr1dangwh9r9isay6fqbg91g5b3h-xz-5.4.5-bin/bin:/nix/store/x1bzwj6pz7f3ajg5y36x07b1328jzx7r-file-5.45/bin" VSLANG="1033" ZERO_AR_DATE="1" "/nix/store/vwh2qqal1q101wv4jy40giavp73q0msd-clang-wrapper-16.0.6/bin/cc" "-Wl,-exported_symbols_list,/private/tmp/nix-build-deno-1.39.0.drv-0/rustcaLrw0q/list" "-arch" "arm64" "/private/tmp/nix-build-deno-1.39.0.drv-0/rustcaLrw0q/symbols.o" "/private/tmp/nix-build-deno-1.39.0.drv-0/source/target/aarch64-apple-darwin/release/deps/slug-fc0809b284e651e9.slug.a92eeefe0ccb5586-cgu.0.rcgu.o" "/private/tmp/nix-build-deno-1.39.0.drv-0/source/target/aarch64-apple-darwin/release/deps/slug-fc0809b284e651e9.kfthj897sv3xwa7.rcgu.o" "-L" "/private/tmp/nix-build-deno-1.39.0.drv-0/source/target/aarch64-apple-darwin/release/deps" "-L" "/private/tmp/nix-build-deno-1.39.0.drv-0/source/target/release/deps" "-L" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib" "/private/tmp/nix-build-deno-1.39.0.drv-0/source/target/aarch64-apple-darwin/release/deps/libdeunicode-1017d4e5790a63c6.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libstd-03c53b54a0b1f97d.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-32c6908016812ada.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libobject-d8028f9d6e099c46.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-b44bd6fb2b1b839e.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-c8dcf438cf6d13da.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libgimli-703d937e20906b80.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-b7ac46c30207e45c.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-4d8dae81211e4895.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-d204bf1a3582275b.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-e447863e017a3c6b.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide-ac4d1414355d5dc4.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libadler-6cc53510bafd9383.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libunwind-cc9a97bec3aa68fb.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-1b9937edf2e43f1a.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/liblibc-b935d087394ceac5.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/liballoc-d062ef7598770b49.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-e068a539d3cd8c41.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libcore-c654b0e49d6357d6.rlib" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-738eb43ff73087cd.rlib" "-lSystem" "-lc" "-lm" "-L" "/nix/store/y24qqyfbnnxza5841hd9hnda5icmzymq-rustc-1.74.0/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/private/tmp/nix-build-deno-1.39.0.drv-0/source/target/aarch64-apple-darwin/release/deps/libslug-fc0809b284e651e9.dylib" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs" "-fuse-ld=lld" "-weak_framework" "Metal" "-weak_framework" "MetalPerformanceShaders" "-weak_framework" "QuartzCore" "-weak_framework" "CoreGraphics"
       >   = note: clang-16: error: invalid linker name in argument '-fuse-ld=lld'
       >
       >
       > error: could not compile `slug` (lib) due to previous error
       > warning: build failed, waiting for other jobs to finish...
```

**Comment by 06kellyjac** [comment]
ok so lld was an issue. I've tried providing lld but if that doesn't work I guess I'll just fix the substitute that removes it
lmk if that works ok now @xanderio  :)
I don't have a macos vm at the moment

**Comment by 06kellyjac** [comment]
ok thanks. I'll just put the substitute back and let you know when that's pushed

**Comment by 06kellyjac** [comment]
pushed @xanderio

**Comment by nekowinston** [comment]
Result of `nixpkgs-review pr 275377` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>deno</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.vim-pluto</li>
  </ul>
</details>

**Comment by nekowinston** [comment]
I'm getting
```
substituteStream(): WARNING: pattern '"-C", "link-arg=-fuse-ld=lld"' doesn't match anything in file '.cargo/config.toml'
```

Since upstream introduced a newline:
https://github.com/denoland/deno/commit/393abed3873d83019feb5bcebb10a6929133862a

**Comment by aqrln** [comment]
Minimal patch that fixes the build:

```diff
diff --git a/pkgs/development/web/deno/default.nix b/pkgs/development/web/deno/default.nix
index 5ab831adb2d9..abd85b8059fe 100644
--- a/pkgs/development/web/deno/default.nix
+++ b/pkgs/development/web/deno/default.nix
@@ -27,7 +27,7 @@ rustPlatform.buildRustPackage rec {
   postPatch = ''
     # upstream uses lld on aarch64-darwin for faster builds
     # within nix lld looks for CoreFoundation rather than CoreFoundation.tbd and fails
-    substituteInPlace .cargo/config.toml --replace '"-C", "link-arg=-fuse-ld=lld"' ""
+    substituteInPlace .cargo/config.toml --replace '"link-arg=-fuse-ld=lld"' ""
   '';
 
   # uses zlib-ng but can't dynamically link yet
@@ -39,9 +39,10 @@ rustPlatform.buildRustPackage rec {
     protobuf
     installShellFiles
   ];
+
   buildInputs = lib.optionals stdenv.isDarwin (
     [ libiconv darwin.libobjc ] ++
-    (with darwin.apple_sdk.frameworks; [ Security CoreServices Metal Foundation QuartzCore ])
+    (with darwin.apple_sdk.frameworks; [ Security CoreServices Metal MetalPerformanceShaders Foundation QuartzCore ])
   );
 
   # work around "error: unknown warning group '-Wunused-but-set-parameter'"
```

**Comment by nekowinston** [comment]
@aqrln you have extra double quotes and `link-arg` instead of `link-args` in there, that won't work.
```
substituteInPlace .cargo/config.toml --replace "link-args=-fuse-ld=lld " ""
```
if you want to use `substituteInPlace`.

**Comment by 06kellyjac** [comment]
Oh I guess I didnt actually push. I did change the substitute to work but its not showing up on GH

**Comment by 06kellyjac** [comment]
actually pushed it now

**Comment by aqrln** [comment]
@nekowinston ah yeah you're right, I was under the impression that `nix build .#deno` succeeded but I was looking at the wrong terminal.

**Review by aqrln — APPROVED** [review]

**Comment by nekowinston** [comment]
Result of `nixpkgs-review pr 275377` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>deno</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.vim-pluto</li>
  </ul>
</details>

**Review by nekowinston — APPROVED** [review]

**Comment by aqrln** [comment]
Result of `nixpkgs-review pr 275377` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>deno</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.vim-pluto</li>
  </ul>
</details>

**Review by ryanccn — APPROVED** [review]

**Review by xanderio — APPROVED** [review]

**Comment by pbsds** [comment]
fixes https://hydra.nixos.org/build/244339583 https://hydra.nixos.org/build/244340479 https://hydra.nixos.org/build/244340144 https://hydra.nixos.org/build/244340026

Don't have a mac but LGTM, thanks!

**Pull request merged**
