### PR TITLE
nixos/networkd: add/adopt IPv6 options

### PR DESCRIPTION
**Pull request by veehaitch**
###### Description of changes

Adds a bunch of new options and deprecations, mostly related to Systemd 250 and IPv6.

The most significant change is the replacement of `DHCPv6PrefixDelegation` in favor of `DHCPPrefixDelegation`.

I've included the relevant systemd news entries in the commit messages.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
I have a bunch of hosts where I did set `networkConfig.IPv6Token` in my config.

Is there a way to alias these things, or add some migration notes in the release notes?

**Comment by veehaitch** [comment]
Thanks for the review! I'd much rather add a release note entry. In my opinion, Systemd renames and deprecates options to regularly to alias them.

Therefore, I'd suggest to add entries to the release notes for the renamed/deprecated options in this PR. Fine for you?

**Comment by flokli** [comment]
Yes, fine for me

**Comment by veehaitch** [comment]
@GrahamcOfBorg test systemd-networkd-ipv6-prefix-delegation

**Comment by veehaitch** [comment]
@flokli Done 🙂

**Review by flokli — APPROVED** [review]

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
