### PR TITLE
influxdb: 0.9.4 -> 0.13.0

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by kamilchm** [comment]
@zimbatm you can try to use `go2nix merge` from https://github.com/kamilchm/go2nix#for-nixers---packaging-go-applications to reuse Go dependencies from `go-modules/libs.json`.

**Comment by zimbatm** [comment]
@kamilchm like this ^?

**Comment by zimbatm** [comment]
I didn't reconcile any of the conflicting dependencies as I want to use the same versions that are approved by upstream. I can see how after a while the common go-modules list would only have references to past packages.

**Comment by kamilchm** [comment]
Well, you're right. I've created `libs.json` to have *backward compatible* set of `goPackages` with all of its pros and cons. But now the decision to reuse dependencies should be left to package maintainers.

**Comment by aristidb** [comment]
Ah, premature merging on my part. It fails to evaluate:

```
[aristid@cobalt:~/nixpkgs-dev]$ nix-build . -A pkgs.influxdb
error: opening file ‘/home/aristid/nixpkgs-dev/pkgs/development/development/go-modules/libs.json’: No such file or directory
(use ‘--show-trace’ to show detailed location information)
```

I suspect this is just a file that you forgot to git-add, @zimbatm ?

**Comment by aristidb** [comment]
I reverted the merge. Please resubmit once it works. :)

**Pull request merged**
