### PR TITLE
bcachefs: 2019-10-01

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
bcachefs (linux) commit seems to be broken.
```
fatal: reference is not a tree: 380885b0b8c38dc770c48602325de77171acc419
Unable to checkout 380885b0b8c38dc770c48602325de77171acc419 from https://evilpiepirate.org/git/bcachefs.git.
builder for '/nix/store/bhc7pfc4b08cscy241iyap6yfj30rgc1-bcachefs-380885b.drv' failed with exit code 1
cannot build derivation '/nix/store/f1bfl4ncywjh7wzk2b4ng2l3jxbblz1x-linux-5.2.2019.10.01.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pa50w8ida032lkz3154p7l9idffadc7g-nixos-system-machine-20.03.git.c18e6fb.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jyqid607yp72gjdd0iry307rqg66c8rk-nixos-vm.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/la7nbvy3iygs0yd22wq7887zh51znknm-nixos-test-driver-bcachefs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/p01ajjgh2292mf4yq5hpdajm6w3jsrgq-vm-test-run-bcachefs.drv': 1 dependencies couldn't be built
error: build of '/nix/store/p01ajjgh2292mf4yq5hpdajm6w3jsrgq-vm-test-run-bcachefs.drv' failed
```

**Comment by Chiiruno** [comment]
On a side note, thoughts on using https://github.com/koverstreet/bcachefs instead of the his website?
Seems to be a mirror made by him.
also cute avatar

**Comment by eadwu** [comment]
Looks like it got rebased, I suppose using the Github sources won't make a difference besides the time difference.

**Comment by eadwu** [comment]
Fixed hash.

**Review by ghost — APPROVED** [review]
Tested as usual, LGTM.

**Review by davidak — APPROVED** [review]
LGTM

not tested tho

**Pull request merged**
