### PR TITLE
python3Packages.envoy-reader: init at 0.19.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Python module to read from Enphase Envoy units

https://github.com/jesserizzo/envoy_reader

This is a Home Assistant depedency.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
Traceback (most recent call last):
  File "/nix/store/pp3aa69gq6g21h6zbmzvb5525ybdq1gf-python3.8-ha-ffmpeg-3.0.2/lib/python3.8/site-packages/haffmpeg/core.py", line 136, in open
    self._proc = await self._loop.run_in_executor(None, proc_func)
  File "/nix/store/71kh64r972bfm9n4jfzvjk2mrmg8zlvl-python3-3.8.9/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/71kh64r972bfm9n4jfzvjk2mrmg8zlvl-python3-3.8.9/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/71kh64r972bfm9n4jfzvjk2mrmg8zlvl-python3-3.8.9/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 123727` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.envoy-reader</li>
    <li>python39Packages.envoy-reader</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123727` at a766776d run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.envoy-reader</li>
    <li>python39Packages.envoy-reader</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by dotlambda** [comment]
> ```
> Traceback (most recent call last):
>   File "/nix/store/pp3aa69gq6g21h6zbmzvb5525ybdq1gf-python3.8-ha-ffmpeg-3.0.2/lib/python3.8/site-packages/haffmpeg/core.py", line 136, in open
>     self._proc = await self._loop.run_in_executor(None, proc_func)
>   File "/nix/store/71kh64r972bfm9n4jfzvjk2mrmg8zlvl-python3-3.8.9/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/nix/store/71kh64r972bfm9n4jfzvjk2mrmg8zlvl-python3-3.8.9/lib/python3.8/subprocess.py", line 858, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/nix/store/71kh64r972bfm9n4jfzvjk2mrmg8zlvl-python3-3.8.9/lib/python3.8/subprocess.py", line 1704, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
> ```

@mweinelt Did that happen in your deployment of Home Assistant? You should set https://www.home-assistant.io/integrations/ffmpeg#ffmpeg_bin.

**Comment by mweinelt** [comment]
> > ```
> > Traceback (most recent call last):
> >   File "/nix/store/pp3aa69gq6g21h6zbmzvb5525ybdq1gf-python3.8-ha-ffmpeg-3.0.2/lib/python3.8/site-packages/haffmpeg/core.py", line 136, in open
> >     self._proc = await self._loop.run_in_executor(None, proc_func)
> >   File "/nix/store/71kh64r972bfm9n4jfzvjk2mrmg8zlvl-python3-3.8.9/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> >     result = self.fn(*self.args, **self.kwargs)
> >   File "/nix/store/71kh64r972bfm9n4jfzvjk2mrmg8zlvl-python3-3.8.9/lib/python3.8/subprocess.py", line 858, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "/nix/store/71kh64r972bfm9n4jfzvjk2mrmg8zlvl-python3-3.8.9/lib/python3.8/subprocess.py", line 1704, in _execute_child
> >     raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
> > ```
> 
> @mweinelt Did that happen in your deployment of Home Assistant? You should set https://www.home-assistant.io/integrations/ffmpeg#ffmpeg_bin.


Pulled from ofBorg Liga.

**Comment by dotlambda** [comment]
It seems unrelated to this change, but I guess `ffmpeg` should be in `checkInputs` unless we wanna patch https://github.com/home-assistant/core/blob/922eec09098e0462b64bea91210a674512b8530a/homeassistant/components/ffmpeg/__init__.py#L42. That would increase the closure size though.

**Comment by lukegb** [comment]
@ofborg build python3Packages.envoy-reader

**Pull request merged**
