### PR TITLE
bundlerEnv: add wrapper

### PR DESCRIPTION
**Pull request by abbradar**
This adds a `.wrapper` attribute to the `bundlerEnv` derivation. Its main purpose is to enable easy packaging of simple Ruby scripts with Gemfiles. For example:

```
let env = bundlerEnv {
  name = "my-script-env";

  inherit ruby;
  gemfile = ./Gemfile;
  lockfile = ./Gemfile.lock;
  gemset = ./gemset.nix;
};

in stdenv.mkDerivation {
  name = "my-script";

  buildInputs = [ env.wrapper ];

  script = ./my-script.rb;

  buildCommand = ''
    mkdir -p $out/bin
    install -D -m755 $script $out/bin/my-script
    patchShebangs $out/bin/my-script
  '';
}
```

cc @cstrahan

### CODE REVIEW

**Comment by manveru** [comment]
That looks really nice, thanks man :smile:

**Comment by abbradar** [comment]
@domenkozar Added documentation. Thank you very much for pointing out documentation issues, it really needs more love from all of us!

**Comment by abbradar** [comment]
I'll merge this in a few days unless someone objects.

**Comment by domenkozar** [comment]
:+1:

**Comment by cstrahan** [comment]
Arg... I attempted to follow up on this the other day via email, but GitHub apparently didn't append my comment to this PR...

Anyway, I wanted to point out that I think the bin stubs already cover this - do they not? They set the `BUNDLE_GEMFILE`, `BUNDLE_PATH` and `GEM_PATH` variables here:

https://github.com/NixOS/nixpkgs/blob/b6c06e216bb3bface40eb8ea6576b25f9b2971dd/pkgs/development/interpreters/ruby/bundler-env/gen-bin-stubs.rb#L32-L36

Or am I missing what this PR is intend for?

**Comment by cstrahan** [comment]
Oh, never mind. I didn't give this a close enough read. You're wrapping the Ruby binaries (e.g. `ruby`/`gem`/etc), rather than the individual gems.

That seems appropriate, though I feel like `wrapper` could maybe use a better name.

:+1:

**Comment by abbradar** [comment]
I feel we can still decide on naming while it's hot -- your ideas?

**Comment by cstrahan** [comment]
I don't have any strong feelings, but ideas: rubyWrapper, rubyWrapped, wrappedRuby. I figure if we ever have anything else that should be wrapped, we'll probably want to differentiate in the name. Probably best to go ahead and indicate what's being wrapped. I'll defer to your judgement on naming, though.

**Comment by abbradar** [comment]
Renamed to `wrappedRuby` at https://github.com/NixOS/nixpkgs/commit/9b980baa9db36aebf1396cafaa4dfc385d7b7009 (pushed to `staging`, because I did this PR when your updates were still there).

**Pull request merged**
