### PR TITLE
exa: 0.10.1 -> unstable-2023-03-01

### PR DESCRIPTION
**Pull request by moni-dz**
###### Description of changes

same reason as last time:

> exa hasn't seen a release for 2 years

###### Things done

- Built on platform(s)
  - [] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fortuneteller2k** [comment]
Result of `nixpkgs-review pr 240490` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>exa</li>
    <li>exa.man</li>
  </ul>
</details>

**Comment by fortuneteller2k** [comment]
Result of `nixpkgs-review pr 240490` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>exa</li>
    <li>exa.man</li>
  </ul>
</details>

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]

**Comment by sersorrel** [comment]
There's at least one regression in unreleased exa versions: https://github.com/ogham/exa/issues/1198

What was new that merited the update in nixpkgs, ooi?

**Comment by SuperSandro2000** [comment]
exa didn't have a release for a longer time and cherry-picking multiple patches is cumbersome.
Maybe we should mark it broken/replace it with lsd?

**Comment by sersorrel** [comment]
lsd looks interesting, but given exa still basically works I think removing it would be disruptive for no real reason. (if it were a real drop-in replacement I could see the argument, but it looks like the default lsd colour scheme is unreadable in my terminal.)

**Pull request merged**
