### PR TITLE
mesa: Bring back feature detection based on enabled drivers

### PR DESCRIPTION
**Pull request by bkchr**
## Description of changes

The drivers of mesa can still be controlled by passing in a custom list to `galliumDrivers`. However, the current implementation expects that all the default drivers are always enabled. This leads to compilation issues when you pass in a custom list of drivers. This is fixed by bringing back the conditinal enabling of certain parts of the package based on the detected drivers.

CC @K900 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
I really don't want to maintain this. In fact, I'd rather even drop `galliumDrivers` entirely. What is your use case for this?

**Comment by bkchr** [comment]
It is used by `nixos-apple-silicon` here: https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/mesa-asahi-edge/default.nix

I mean I can change the package there to enable the `asahi` driver differently.

**Comment by K900** [comment]
Yeah this seems like what we do in Jovian for a similar package. Here's how I changed that: https://github.com/Jovian-Experiments/Jovian-NixOS/blob/development/pkgs/mesa-radv-jupiter/default.nix

**Comment by bkchr** [comment]
I see. IMO we should then make `galliumDrivers` to not be an input value to the package? Or we could also just add some `additionalGalliumDrivers`?

**Comment by K900** [comment]
Yes, I do want to remove it eventually.

**Pull request closed without merging**
