### PR TITLE
SDL2: 2.0.22 -> 2.24.0

### PR DESCRIPTION
**Pull request by PedroHLC**
###### Description of changes

- Foremost, they changed the versioning, the patch in the version was promoted to minor. `2.0.22 == 2.22.0`;

- Full changelog in https://github.com/libsdl-org/SDL/releases/tag/release-2.24.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSamus** [comment]
Closes #188794.

**Review by K900 — APPROVED** [review]
Diff LGTM, will test when I get some spare time around a faster computer.

**Review by Atemu — CHANGES_REQUESTED** [review]
Breaks the build of ffmpeg on aarch64-darwin:

```
ERROR: sdl2 requested but not found
```

**Comment by PedroHLC** [comment]
> Breaks the build of ffmpeg on aarch64-darwin:
> 
> ```
> ERROR: sdl2 requested but not found
> ```

Shouldn't break according to their changelog, could it be the building of pipewire's ffmpeg? If that's the case, we have an override in `top-level/all-packages.nix`, to `pipewire.ffmpeg.SDL2.pipewireSupport = false` to stop a cycle.

**Comment by Atemu** [comment]
No, it's the regular `ffmpeg` derivation. `SDL2` itself builds just fine.

**Comment by PedroHLC** [comment]
> No, it's the regular `ffmpeg` derivation. `SDL2` itself builds just fine.

Seems like my patch will need a little more tweaking to produce the same pkg-config as the previous version.

**Comment by vs49688** [comment]
Haven't tested it, but https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=e5163b1d34381a3319214a902ef1df923dd2eeba should fix the ffmpeg issue

**Comment by PedroHLC** [comment]
> Haven't tested it, but https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=e5163b1d34381a3319214a902ef1df923dd2eeba should fix the ffmpeg issue

Thanks, @vs49688, I was getting nuts thinking it was something wrong in the pkgconfig, didn't think of checking the version condition.

**Comment by PedroHLC** [comment]
Tested with `space-cadet-pinball` (builds and plays), `ffmpeg` (builds, alias of `ffmpeg_4`), and `ffmpeg_5` (builds).

**Review by Atemu — APPROVED** [review]
SDL and ffmpeg build on aarch64-darwin.

Don't know what I could run to test further.

**Review by thiagokokada — APPROVED** [review]

**Comment by thiagokokada** [comment]
@ofborg eval

**Comment by thiagokokada** [comment]
@PedroHLC Can you check the eval errors?

**Comment by superherointj** [comment]
@ofborg eval

**Review by superherointj — APPROVED** [review]
I have built SDL2 and +2000 downstream packages. Build did not finish because I ran out of disk space. But seemed good still.

**Pull request merged**
