### PR TITLE
KDE 5 packaging instructions

### PR DESCRIPTION
**Pull request by ttuegel**
### Problem

The instructions for adding and updating KDE 5 packages were significantly out-of-date. Consequently, there were mistakes in several package updates or additions.

### Solution

1. The instructions are made current.
2. The mistaken package updates and additions are corrected.

### Testing

~~I have verified, using `nox-review`, that these changes do not cause any rebuilds.~~

This change makes additional versions of `libktorrent` available, verified with `nox-review`.

Builds:
- [x] NixOS with sandboxing
- [x] macOS (Travis)
- [ ] Other Linux

### CODE REVIEW

**Comment by ttuegel** [comment]
Oops, just realized this is missing one more clean-up...

**Comment by ttuegel** [comment]
...and there we go!

I can't even follow my own instructions. 😺

**Comment by vandenoever** [comment]
Looks good. Glad that the KDE update process is becoming even smoother.

**Comment by ttuegel** [comment]
The Travis failure is spurious: it tries to build clang, which was updated in master. 🙄

**Pull request merged**
