### PR TITLE
GNOME: 44 → 45

### PR DESCRIPTION
**Pull request by vcunat**
Same as PR #247766, only targeting a different branch, as we (barely) missed the branch-off.

### CODE REVIEW

**Comment by fabianhjr** [comment]
Looking into

```
source root is source
patching sources
applying patch /nix/store/gpi9ahz1qbfirzwzrw9p5a4rni5kv40b-freon_at_UshakovVasilii_Github.yahoo.com.patch
patching file hddtempUtil.js
Hunk #1 succeeded at 10 (offset 3 lines).
Hunk #2 succeeded at 22 (offset 3 lines).
Hunk #3 FAILED at 35.
1 out of 3 hunks FAILED -- saving rejects to file hddtempUtil.js.rej
patching file liquidctlUtil.js
Hunk #1 succeeded at 7 with fuzz 1 (offset -1 lines).
patching file nvmecliUtil.js
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED -- saving rejects to file nvmecliUtil.js.rej
patching file sensorsUtil.js
Hunk #1 succeeded at 6 (offset -1 lines).
patching file smartctlUtil.js
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED -- saving rejects to file smartctlUtil.js.rej
error: builder for '/nix/store/hmlllr4vrqxf9j3xyrvmxrqavkl4srqy-gnome-shell-extension-freon-54.drv' failed with exit code 1;
       last 10 log lines:
       > patching file liquidctlUtil.js
       > Hunk #1 succeeded at 7 with fuzz 1 (offset -1 lines).
       > patching file nvmecliUtil.js
       > Hunk #1 FAILED at 3.
       > 1 out of 1 hunk FAILED -- saving rejects to file nvmecliUtil.js.rej
       > patching file sensorsUtil.js
       > Hunk #1 succeeded at 6 (offset -1 lines).
       > patching file smartctlUtil.js
       > Hunk #1 FAILED at 3.
       > 1 out of 1 hunk FAILED -- saving rejects to file smartctlUtil.js.rej
       For full logs, run 'nix log /nix/store/hmlllr4vrqxf9j3xyrvmxrqavkl4srqy-gnome-shell-extension-freon-54.drv'.
error: 1 dependencies of derivation '/nix/store/8cs62zfn5sqnnxk5kb4j9d8krlhhl5l3-gnome-shell-extension-freon-54-fish-completions.drv' failed to build
```

**Comment by PaulGrandperrin** [comment]
I just upgraded to Gnome45 which just arrived in the `nixos-23.11` branch and now my session doesn't open anymore.

I tried deleting my home directory and recreate a new one and now the session opens.

I compared the logs from the failed session and the clean and successful one and here is what I think makes the session fail:

```
Nov 23 15:43:38 nixos-xps systemd[2481]: Started Evolution address book service.
Nov 23 15:43:38 nixos-xps gsd-wacom[3754]: Cannot open display:
Nov 23 15:43:38 nixos-xps .org.gnome.Shel[3655]: Failed to open display
Nov 23 15:43:38 nixos-xps gsd-color[3714]: Cannot open display:
Nov 23 15:43:38 nixos-xps gsd-keyboard[3724]: Cannot open display:
Nov 23 15:43:38 nixos-xps .gnome-software[3727]: Failed to open display
Nov 23 15:43:38 nixos-xps gsd-media-keys[3728]: Cannot open display:
Nov 23 15:43:38 nixos-xps .evolution-alar[3755]: cannot open display: :0
Nov 23 15:43:38 nixos-xps gsd-power[3729]: Cannot open display:
Nov 23 15:43:38 nixos-xps polkitd[1281]: Unregistered Authentication Agent for unix-session:4 (system bus name :1.95, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.Wacom.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 15:43:38 nixos-xps gnome-session[3520]: gnome-session-binary[3520]: GnomeDesktop-WARNING: Failed to acquire idle monitor proxy: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Nov 23 15:43:38 nixos-xps gnome-session-binary[3520]: GnomeDesktop-WARNING: Failed to acquire idle monitor proxy: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Nov 23 15:43:38 nixos-xps dbus-daemon[3402]: [session uid=1000 pid=3402] Activated service 'org.gnome.Shell.Screencast' failed: Process org.gnome.Shell.Screencast exited with status 1
Nov 23 15:43:38 nixos-xps .gsd-usb-protec[3751]: Failed to get screen saver status: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Nov 23 15:43:38 nixos-xps gnome-session[3520]: gnome-session-binary[3520]: WARNING: Could not retrieve current screensaver active state: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Nov 23 15:43:38 nixos-xps gnome-session-binary[3520]: WARNING: Could not retrieve current screensaver active state: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.Shell@wayland.service: Main process exited, code=killed, status=9/KILL
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.Color.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.Keyboard.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.MediaKeys.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.Power.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.Wacom.service: Failed with result 'exit-code'.
Nov 23 15:43:38 nixos-xps systemd[2481]: Failed to start GNOME Wacom tablet support service.
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.Color.service: Failed with result 'exit-code'.
Nov 23 15:43:38 nixos-xps systemd[2481]: Failed to start GNOME color management service.
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.Keyboard.service: Failed with result 'exit-code'.
Nov 23 15:43:38 nixos-xps .gsd-usb-protec[3751]: Failed to fetch USBGuard parameters: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.usbguard1 was not provided by any .service files
Nov 23 15:43:38 nixos-xps systemd[2481]: Failed to start GNOME keyboard configuration service.
Nov 23 15:43:38 nixos-xps systemd[2481]: Reached target GNOME color management target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Reached target GNOME keyboard configuration target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Reached target GNOME Wacom tablet support target.
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.MediaKeys.service: Failed with result 'exit-code'.
Nov 23 15:43:38 nixos-xps systemd[2481]: Failed to start GNOME keyboard shortcuts service.
Nov 23 15:43:38 nixos-xps systemd[2481]: Reached target GNOME keyboard shortcuts target.
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.SettingsDaemon.Power.service: Failed with result 'exit-code'.
Nov 23 15:43:38 nixos-xps systemd[2481]: Failed to start GNOME power management service.
Nov 23 15:43:38 nixos-xps systemd[2481]: Reached target GNOME power management target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Reached target GNOME Session.
Nov 23 15:43:38 nixos-xps systemd[2481]: Reached target GNOME Wayland Session (session: gnome).
Nov 23 15:43:38 nixos-xps systemd[2481]: Reached target Current graphical user session.
Nov 23 15:43:38 nixos-xps systemd[2481]: GNOME Initial Setup was skipped because of an unmet condition check (ConditionPathExists=!/home/paulg/.config/gnome-initial-setup-done).
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.Shell@wayland.service: Failed with result 'signal'.
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.Shell@wayland.service: Triggering OnFailure= dependencies.
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.Shell@wayland.service: Consumed 1.218s CPU time.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME Wayland Session (session: gnome).
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target Current graphical user session.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME Session.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME Wayland Session.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME Session (session: gnome).
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME accessibility target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME color management target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME date & time target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME maintenance of expirable data target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME keyboard configuration target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME keyboard shortcuts target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME power management target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME printer notifications target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME RFKill support target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME FreeDesktop screensaver target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME file sharing target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME smartcard target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME sound sample caching target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME USB protection target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME Wacom tablet support target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped target GNOME XSettings target.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping Accessibility services bus...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping Virtual filesystem service - Apple File Conduit monitor...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping Virtual filesystem service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping Virtual filesystem service - GNOME Online Accounts monitor...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping Virtual filesystem service - digital camera monitor...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping Virtual filesystem service - Media Transfer Protocol monitor...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping Virtual filesystem service - disk device monitor...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME accessibility service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped GNOME color management service.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME date & time service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME maintenance of expirable data service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped GNOME keyboard configuration service.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped GNOME keyboard shortcuts service.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped GNOME power management service.
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME printer notifications service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME RFKill support service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME FreeDesktop screensaver service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME file sharing service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME smartcard service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME sound sample caching service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopping GNOME USB protection service...
Nov 23 15:43:38 nixos-xps systemd[2481]: Stopped GNOME Wacom tablet support service.
Nov 23 15:43:38 nixos-xps systemd[2481]: org.gnome.Shell-disable-extensions.service: multiple trigger source candidates for exit status propagation (org.gnome.Shell@wayland.service, org.gnome.Shell@x11.service), skipping.
```

I don't know what file or conf in my home dir is at fault but I'll investigate.

If someone has ideas about how I could do that, that woud be great.

**Comment by MatthewCash** [comment]
> I found the culprit: my dconf experimental settings, I don't know which one, I deleted both. `org/gnome/mutter/experimental-features = [ "scale-monitor-framebuffer" "rt-scheduler" ]`

My guess would be the `rt-scheduler` option because mutter now has a realtime KMS thread, so maybe the they conflict now 🤷.

**Comment by Emiller88** [comment]
I had the same issue, but it was the `"scale-monitor-framebuffer"` because that was the only experimental-feature I had enabled.

**Pull request merged**
