### PR TITLE
home-assistant: 2021.4.0 -> 2021.4.1

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/home-assistant/core/releases/tag/2021.4.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 118865` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>speedtest-cli (python38Packages.speedtest-cli)</li>
    <li>python39Packages.speedtest-cli</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 118865` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>speedtest-cli (python38Packages.speedtest-cli)</li>
    <li>python39Packages.speedtest-cli</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 118865` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>speedtest-cli (python38Packages.speedtest-cli)</li>
    <li>python39Packages.speedtest-cli</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Any particular log you can share about the build failure?

**Comment by Ma27** [comment]
Ported the speedtest-cli bump to 20.09 as it fixes a runtime error: 35d5d0d0676bac12b587580fa1d15c88efc879dc (commit message includes further details).

**Pull request merged**
