### PR TITLE
godot_4: add godot_4-mono

### LINKED ISSUE #255986: Godot 4 Mono Build
**Project description**

Free and Open Source 2D and 3D game engine (mono build)

**Metadata**

* homepage URL: https://godotengine.org/
* source URL: https://github.com/godotengine/godot
* license: mit
* platforms: i686-linux, aarch64-linux, x86_64-linux

### PR DESCRIPTION
**Pull request by corngood**
## Things done

Based on https://github.com/chaotic-cx/nyx/blob/main/pkgs/godot_4-mono/default.nix

Thanks @dr460nf1r3!

I dropped the runtime dependencies on: dotnet-runtime, msbuild, mono, but it's possible they are needed for something I wasn't able to test.

I did test: creating a new project, adding a C# script with a print, building and running the project.

Closes: https://github.com/NixOS/nixpkgs/issues/255986

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
```
2024-11-02T23:16:43.8830734Z pkgs/by-name/go/godot_4/deps.nix: not formatted
2024-11-02T23:16:43.9275980Z Some new/changed Nix files are not properly formatted
2024-11-02T23:16:43.9277415Z Please go to the Nixpkgs root directory, run `nix-shell`, then:
2024-11-02T23:16:43.9278442Z nixfmt 'pkgs/by-name/go/godot_4/deps.nix'
2024-11-02T23:16:43.9279506Z If you're having trouble, please ping @NixOS/nix-formatting
```

this is intentional for the generated file

**Comment by corngood** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353242`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 7 packages built:</summary>
  <ul>
    <li>godot_4</li>
    <li>godot_4-mono</li>
    <li>godot_4-mono.debug</li>
    <li>godot_4-mono.man</li>
    <li>godot_4.debug</li>
    <li>godot_4.man</li>
    <li>pixelorama</li>
  </ul>
</details>

**Review by dr460nf1r3 — APPROVED** [review]

**Comment by corngood** [comment]
Should we just default `withMono` to true on systems that have dotnet?

I'm not sure how valuable it is to maintain a non-mono package.

**Comment by GameDungeon** [comment]
Not super important, but it would be nice for it to have a debug flag, as a debug build of godot is required for profiling.

**Comment by corngood** [comment]
> Not super important, but it would be nice for it to have a debug flag, as a debug build of godot is required for profiling.

@GameDungeon can you elaborate on this?  Does this apply godot_4 (without mono) as well?

**Comment by GameDungeon** [comment]
Thinking on it more, yes it does, but I'm not sure if it actually is any useful with GDScript. The interpreted language probably makes the results pretty weird. External profilers require debug symbols for the output to make any sense, and external profilers are required to profile in mono. It has a built in profiler for GDScript. 

https://docs.godotengine.org/en/stable/contributing/development/debugging/using_cpp_profilers.html

**Comment by corngood** [comment]
@GameDungeon I don't see anything in there about profiling mono, and I'm not sure that having native debug info would even help with that.  It does sound like having debug info would be useful in general for profiling, but I think we should deal with that in another PR.  

Feel free to create an issue.  It would be especially useful if you can describe exactly how you want to go about profiling godot or something built with godot.

**Comment by GameDungeon** [comment]
I've profiled mono builds with the external profilers before. You are meant to use the built in profiler for GDScript, but that profiler does not work on mono. When you use the cpp profiler it needs symbols to display function names. I am fine with moving this to a separate issue though.

**Pull request merged**
