### PR TITLE
fetchgit: fetch submodules in parallel

### LINKED ISSUE #88982: fetchgit fetches submodules sequentially instead of in parallel
**Describe the bug**
`fetchgit` clones each submodule in sequence instead of in parallel, which is unnecessarily slow for repos that have a lot of submodules (such as `bat` which has 64 direct submodules).

At first I thought this was because git's `submodule.fetchJobs` setting defaults to `1`, but it turns out `fetchgit` doesn't even use that, it instead recursively clones the submodules by hand. @nbp it looks like you added this 10 years ago; is there any reason we can't just use `git submodule update --init --recursive` today?

I don't know why it doesn't just use git's built-in submodule handling, doing so would make fixing this trivial. Parallelizing the manual clone loop seems a lot more complicated (especially because of the problem of mixed output).

**To Reproduce**
1. Build `bat.src` from scratch. (Edit: `bat` was recently updated to not use submodules anymore. This can be reproduced using an older version)

**Expected behavior**
It should clone the repo in a reasonable amount of time.

**Notify maintainers**
Last few changes to `fetchgit/nix-prefetch-git` were @Mic92 and @bhipple

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(lily): `"nixpkgs-20.09pre226586.571212eb839"`
 - nixpkgs: `/Users/lily/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: fetchgit
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by domenkozar**
Fixes https://github.com/NixOS/nixpkgs/issues/88982

### CODE REVIEW

**Review by drupol — APPROVED** [review]
Nice one!

**Comment by NickCao** [comment]
How do we check that the resulting FODs are still the same?

**Comment by domenkozar** [comment]
I checked with `clickhouse.src` that has a couple of hundred submodules.

I just changed the hash to something different and made sure it conflicted to the previous one.

**Comment by NickCao** [comment]
Me now trying --rebuild with 543 srcs found with `rg fetchSubmodules`

**Comment by NickCao** [comment]
https://github.com/ryukau/LV2Plugins/ from `pkgs/applications/audio/uhhyou.lv2/default.nix` has gone away.

**Review by NickCao — APPROVED** [review]
Apparently there's some connectivity issue between my machine and github, but for the three dozen srcs I've built so far everything looks fine.

**Comment by lilyinstarlight** [comment]
It seems to be related to the use of `update = none` in the related submodules (https://github.com/gtk-rs/gtk-rs-core/blob/ed3457ebed5ef863ea40ad3d5f94eb0e87330b3a/.gitmodules#L4), which was ignored before but now followed by the `git submodule update` command

If this new behavior after this PR is considered "correct behavior", I'm fine with just updating the hashes gst-plugins-rs since it's unlikely many other packages are affected (if any)

It'll just make backports more annoying since this change isn't (and shouldn't be) on 23.05 and so the hahses will always differ for the same gst-plugins-rs version between `master` and `release-23.05`

**Comment by domenkozar** [comment]
I'd be inclined to say it's good that it does the right thing now.

**Comment by NickCao** [comment]
Can't we backport this to 23.05? It's not as much a breaking change as it seems. And we do have [fodwatch](https://tapesoftware.net/fodwatch/) monitoring FODs now.

**Comment by NickCao** [comment]
Or the worst case scenario would be us reverting this PR and making the new implementation an opt-in, which suffers the poor discoverability as fetchpatch2 does.

**Comment by lilyinstarlight** [comment]
> Can't we backport this to 23.05? It's not as much a breaking change as it seems. And we do have [fodwatch](https://tapesoftware.net/fodwatch/) monitoring FODs now.

It's still a possible breaking change at all for downstream users

> Or the worst case scenario would be us reverting this PR and making the new implementation an opt-in, which suffers the poor discoverability as fetchpatch2 does.

I think it's fine to leave as-is. The behavior is probably more correct now, so I don't think we should revert (especially if we revert to make it a poorly discoverable opt-in)

**Pull request merged**
