### PR TITLE
zfsUnstable: make it compatible again with 6.2.8 and potentially 6.3

### PR DESCRIPTION
**Pull request by RaitoBezarius**
###### Description of changes

This is an alternative proposal to #222942 where I use ZFS' maintainers patches to fix zfsUnstable on 6.2+.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Upstream issue: https://github.com/openzfs/zfs/issues/14658

**Comment by PedroHLC** [comment]
This one is better indeed. Thanks for researching the solution.

**Comment by RaitoBezarius** [comment]
I'm running with it on x86_64-linux with 6.2.8 kernel at the moment, just fine.

**Comment by RaitoBezarius** [comment]
Included latest "unified" patch from maintainer.

**Comment by Mic92** [comment]
@ofborg test zfsUnstable

**Comment by Mic92** [comment]
@ofborg test zfs

**Comment by toastal** [comment]
@RaitoBezarius I got an issue trying to load this. systemd Stage 1 says: `Invalid  ELF Header` (maybe the word "magic") was in there too along with `zfs modules are not loaded`. Is there anything else that would have changed?

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius I got an issue trying to load this. systemd Stage 1 says: `Invalid ELF Header` (maybe the word "magic") was in there too along with `zfs modules are not loaded`. Is there anything else that would have changed?
> 
> Reference: I have ZFS root with vfat boot partition that includes the decryption key for the encrypted pool for ZFS. An older commit with 6.1.x worked, but pulling more recently even the 6.1.x doesn't work. Rolling back so far has worked.

Ugh, I didn't reboot yet, I don't see reason for why this would happen though.

**Comment by RaitoBezarius** [comment]
> I gave it a go along with my version bump merge request for zfsUnstable. I backed out that bump and rebuilt before going to supper. When I return shortly, I'll check if for some mysterious reason that was the cause. -- toastal ไข่ดาว | https://toast.al PGP: 7944 74b7 d236 dab9 c9ef e7f9 5cce 6f14 66d4 7c9e

I am adding a NixOS test with sd-stage 1 for ZFS unstable.

**Comment by RaitoBezarius** [comment]
> > I gave it a go along with my version bump merge request for zfsUnstable. I backed out that bump and rebuilt before going to supper. When I return shortly, I'll check if for some mysterious reason that was the cause. -- toastal ไข่ดาว | https://toast.al PGP: 7944 74b7 d236 dab9 c9ef e7f9 5cce 6f14 66d4 7c9e
> 
> I am adding a NixOS test with sd-stage 1 for ZFS unstable.

It is passing on my side, pushed it.

**Review by toastal — APPROVED** [review]
This has built, it boots, and it fixes issue for me.

**Comment by RaitoBezarius** [comment]
I will update the PR with a proper fetchpatch and referencing the upstream PR in some minutes.

**Comment by RaitoBezarius** [comment]
(upstream merged it too.)

**Pull request merged**
