### PR TITLE
mdbook: 0.1.8 -> 0.3.1

### PR DESCRIPTION
**Pull request by tazjin**
###### Motivation for this change

Last update in nixpkgs was over a year ago and the project has progressed a lot in between. This moves the derivation to the latest tagged version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Havvy

### CODE REVIEW

**Review by srhb — CHANGES_REQUESTED** [review]
Looks like the license is (now?) mpl20, not asl20 or mit.

**Comment by tazjin** [comment]
@srhb You're right! It looks like the license has always been MPL 2.0, so I'm not sure where that came from originally. Updated it, but I can't resolve your comment because it's outside of the original diff and Github won't render it correctly.

**Review by srhb — APPROVED** [review]

**Comment by samueldr** [comment]
Is [this comment from the previous PR](https://github.com/NixOS/nixpkgs/pull/44494#issuecomment-410509330) still relevant? https://github.com/rust-docs/team/issues/23 is not resolved. I'm not even 100% sure I understand it, is it that it would break our rust builds since its documentation wouldn't build?

**Comment by tazjin** [comment]
@samueldr As far as I can tell, our Rust builds do not depend on `mdbook` (in fact nothing does, as per `rg -i 'mdbook'`). The Rust documentation that we do build as part of the standard platform is just what `rustdoc` creates, which is separate from the book(s).

Hence I don't think this comment is relevant for `nixpkgs`, but if a Nix user wants to contribute to upstream Rust books they will need to get an older version of the tool to build them.

**Pull request merged**
