### PR TITLE
llvm-general: Adds Darwin compatibilty

### PR DESCRIPTION
**Pull request by dalaing**
Fix for #14035

### CODE REVIEW

**Comment by acowley** [comment]
This looks good to me superficially. I can give it a try tomorrow. Thanks for this, @dalaing!

**Comment by acowley** [comment]
Looks good, builds, and tests pass for me!

**Comment by peti** [comment]
I would very much prefer to have those fixes applied to the package *upstream*. Would you mind submitting a PR to the libraries' authors instead, so that all users can benefit from these fixes?

**Comment by dalaing** [comment]
Upstream is working fine for me outside of Nix on OS X. As far as I can tell / unless I've gotten something horribly confused,  these changes are required to make llvm-general work on Nix.

**Comment by acowley** [comment]
An option to use `libc++` in the `cabal` file would make sense, but we’d still need to enable it on Darwin in `nixpkgs`.

**Comment by dalaing** [comment]
Is there anything I need to do to get this in?

**Comment by peti** [comment]
Does this problem still exist?

**Comment by dalaing** [comment]
My understanding is that there haven't been any changes around this in either llvm-general or in nixpkgs, so I'm pretty sure that it does.

I've since moved from using Nix on OS X to using NixOS in a VM, so I don't have a way of checking it anymore.

**Pull request merged**
