### PR TITLE
perlPackages.ImageExifTool: 12.00 -> 12.16

### PR DESCRIPTION
**Pull request by dywedir**
###### Motivation for this change

https://exiftool.org/history.html#v12.16

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stigtsp** [comment]
@ofborg build perlPackages.ImageExiftool

**Review by stigtsp — CHANGES_REQUESTED** [review]
Please rename commit message/pr to `perlPackages.ImageExifTool`

**Comment by stigtsp** [comment]
@ofborg build perlPackages.ImageExifTool

**Comment by dywedir** [comment]
Oh my!

**Comment by stigtsp** [comment]
@ofborg build perlPackages.ImageExifTool

**Review by stigtsp — APPROVED** [review]
LGTM

Result of `nixpkgs-review pr 111024` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>digikam</li>
    <li>exiftool (perl532Packages.ImageExifTool)</li>
    <li>fgallery</li>
    <li>gcstar</li>
    <li>hugin</li>
    <li>megapixels</li>
    <li>pdf-redact-tools</li>
    <li>perl530Packages.ImageExifTool</li>
    <li>rapid-photo-downloader</li>
    <li>shutter</li>
    <li>styx</li>
    <li>timelapse-deflicker</li>
  </ul>
</details>

**Pull request merged**
