### PR TITLE
Update fontconfig and freetype

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Update packages. Okay, truth be told: to get color emojis!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I'm not sure why don't we use `gperf` as a build input and instead resort to hacks. @vcunat?

### CODE REVIEW

**Comment by jtojnar** [comment]
See also https://github.com/NixOS/nixpkgs/pull/29704 and https://github.com/NixOS/nixpkgs/pull/33995

**Comment by abbradar** [comment]
@jtojnar Thanks, it seems I need to use search better.

**Comment by jtojnar** [comment]
We could also close the other PRs since they are inactive and outdated.

**Comment by abbradar** [comment]
At least `freetype` one is not actually outdated and the other one could be easily rebased -- I usually prefer "first one wins" in this case. Either way I'm now building Firefox to test #29704 -- let's see if the issue still stands.

**Comment by abbradar** [comment]
Reopening because I have fontconfig 2.15.6 here.

**Comment by abbradar** [comment]
@volth (Responding here as I'd like to pursue merging this one -- it has newer fontconfig) I'd like to get response from @vcunat on `gperf` first -- I feel I miss something otherwise it's strange we used hacks for such a long time.

**Comment by abbradar** [comment]
Ah, wait, @vcunat has already dropped this hack in his own PR.

We can proceed then I think -- I'll merge this in couple of days unless someone objects.

**Comment by vcunat** [comment]
The reason was general avoidance of unnecessary build-time closure bloat.  Very many packages depend on fontconfig (transitively), so every addition might be noticeable on mass rebuilds &ndash; e.g. everything having to wait on some more packages before fontconfig build starts, and everything having to rebuild if gperf is updated.

**Comment by abbradar** [comment]
@vcunat Ah, got it. It seems `gperf` is updated very rarely though -- the last update was in January 2017 and before that in February 2009. It also doesn't depend on anything so I'm inclined to just use it.

**Comment by volth** [comment]
I'd also remove ```useEncumberedCode``` option. If you want to retain it, it would need some care - on (not merged to master) ```2.7->2.8``` upgrade the patch became void, nothing depended on the option)

**Comment by abbradar** [comment]
@volth From reading https://www.freetype.org/patents.html and `ft_option.h` the patch for subpixel rendering is still applicable -- what am I missing?

We'd probably want to use those patches in Chromium too, yeah (but that's out of scope of this patchset).

**Comment by volth** [comment]
> @volth From reading https://www.freetype.org/patents.html and ft_option.h the patch for subpixel rendering is still applicable -- what am I missing?

For freetype 2.8 a reverse patch was required, when ```!useEncumberedCode```, not when ```useEncumberedCode```: https://github.com/NixOS/nixpkgs/pull/27725

**Comment by abbradar** [comment]
@volth Ah, I see. It's interesting they reverted their behaviour to the old one now. BTW, would you like me to take your (optional) patch for disabling hinting in too?

**Comment by abbradar** [comment]
On the second thought let's merge this now to get it into staging sooner -- we can add optional patches painlessly after that.

**Comment by volth** [comment]
> BTW, would you like me to take your (optional) patch for disabling hinting in too?

that's ```useSubpixelHinting``` in #27725

---
Now I just do
```
find . -type f -name ftoption.h \
  -exec sed -r -i 's/^#define TT_CONFIG_OPTION_SUBPIXEL_HINTING.*$//'   {} \; \
  -exec sed -r -i 's/^#define FT_CONFIG_OPTION_SUBPIXEL_RENDERING.*$//' {} \;
```

in ```freetype``` and ```chromium``` to be sure, that also overrides ```useEncumberedCode``` independent on the default. 
```kitty``` might require the patch too (https://github.com/kovidgoyal/kitty/issues/367) if you plan to bring the option to disable hinting to ```nixpkgs```

**Comment by volth** [comment]
```libreoffice``` includes ```freetype-2.8.1```:

https://github.com/NixOS/nixpkgs/blob/f6de73b/pkgs/applications/office/libreoffice/libreoffice-srcs.nix#L304-L305

should we bump version there ?

**Comment by 7c6f434c** [comment]
Bumping versions in this files will not ever lead to any desirable consequences (the makefile references exact tarball names, for example).

Switching to `--with-system-freetype` (maybe also for `fontconfig`) might be or not be a good idea, needs testing.

**Pull request merged**
