### PR TITLE
python310Packages.ha-ffmpeg: 3.0.2 -> 3.1.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 216859` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>home-assistant-component-tests.canary</li>
    <li>home-assistant-component-tests.ezviz</li>
    <li>home-assistant-component-tests.ffmpeg</li>
    <li>home-assistant-component-tests.homekit</li>
    <li>home-assistant-component-tests.logi_circle</li>
    <li>home-assistant-component-tests.nest</li>
    <li>home-assistant-component-tests.onvif</li>
    <li>home-assistant-component-tests.ring</li>
    <li>home-assistant-component-tests.skybell</li>
    <li>home-assistant-component-tests.tuya</li>
    <li>home-assistant-component-tests.xiaomi</li>
    <li>python310Packages.ha-ffmpeg</li>
    <li>python311Packages.ha-ffmpeg</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
A commit message should always reflect what is done in the commit, so I
wonder why `update meta` is also a complete reformatting.

And when you noticed, that you introduced a mistake in `meta.changelog`,
why didn't you amend the previous commit and instead went for third one?

**Comment by fabaff** [comment]
> A commit message should always reflect what is done in the commit, so I wonder why update meta is also a complete reformatting.

"Complete reformatting" is a bit of a stretch...could the commit message be better, sure.

> And when you noticed, that you introduced a mistake in meta.changelog, why didn't you amend the previous commit and instead went for a third one?

Because it saves time to do it that way. I added changelogs on a large scale after the past weeks and I really can't remember where I already added it and where not. Using GitHub to do it after a PR is created is simply the most efficient way for me to do it. It's inevitable that there are typos from time to time. 

> Also empty PR description, where at a minimum the changelog URL should be.

Adding `meta.changelog` was kind of the reason to prevent this in the future. We will then also have it for PRs created by r-ryantm.

**Comment by winterqt** [comment]
> "Complete reformatting" is a bit of a stretch...could the commit message be better, sure.

You also added `format = "setuptools"`, and changed `disabled` to `pythonOlder "3.7"`. All which should have been done in the bump.

**Pull request merged**
