### PR TITLE
chickenPackages: update eggs

### PR DESCRIPTION
**Pull request by nagy**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by konst-aa** [comment]
Looks good, how should we automate this?

**Review by konst-aa — APPROVED** [review]

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 244190` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>chickenPackages_5.chickenEggs.beaker</li>
    <li>chickenPackages_5.chickenEggs.ipfs</li>
    <li>chickenPackages_5.chickenEggs.lsp-server</li>
    <li>chickenPackages_5.chickenEggs.pandoc</li>
    <li>chickenPackages_5.chickenEggs.sq</li>
    <li>chickenPackages_5.chickenEggs.transmission</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>chickenPackages_5.chickenEggs.apropos</li>
    <li>chickenPackages_5.chickenEggs.bloom-filter</li>
    <li>chickenPackages_5.chickenEggs.breadline</li>
    <li>chickenPackages_5.chickenEggs.commands</li>
    <li>chickenPackages_5.chickenEggs.condition-utils</li>
    <li>chickenPackages_5.chickenEggs.edn</li>
    <li>chickenPackages_5.chickenEggs.edward</li>
    <li>chickenPackages_5.chickenEggs.gemini</li>
    <li>chickenPackages_5.chickenEggs.gemini-client</li>
    <li>chickenPackages_5.chickenEggs.json-rpc</li>
    <li>chickenPackages_5.chickenEggs.levenshtein</li>
    <li>chickenPackages_5.chickenEggs.lmdb</li>
    <li>chickenPackages_5.chickenEggs.monocypher</li>
    <li>chickenPackages_5.chickenEggs.posix-regex</li>
    <li>chickenPackages_5.chickenEggs.r7rs</li>
    <li>chickenPackages_5.chickenEggs.r7rs-tools</li>
    <li>chickenPackages_5.chickenEggs.redis</li>
    <li>chickenPackages_5.chickenEggs.remote-mailbox</li>
    <li>chickenPackages_5.chickenEggs.rlimit</li>
    <li>chickenPackages_5.chickenEggs.s9fes-char-graphics</li>
    <li>chickenPackages_5.chickenEggs.schematic</li>
    <li>chickenPackages_5.chickenEggs.srfi-105</li>
    <li>chickenPackages_5.chickenEggs.srfi-123</li>
    <li>chickenPackages_5.chickenEggs.srfi-135</li>
    <li>chickenPackages_5.chickenEggs.srfi-144</li>
    <li>chickenPackages_5.chickenEggs.srfi-180</li>
    <li>chickenPackages_5.chickenEggs.srfi-19</li>
    <li>chickenPackages_5.chickenEggs.srfi-207</li>
    <li>chickenPackages_5.chickenEggs.srfi-29</li>
    <li>chickenPackages_5.chickenEggs.toml</li>
    <li>chickenPackages_5.chickenEggs.uuid-lib</li>
  </ul>
</details>

**Comment by nagy** [comment]
> how should we automate this?

I think ultimately the implementation should be like this: https://github.com/NixOS/nixpkgs/blob/master/.github/workflows/update-terraform-providers.yml

But the changes in the ecosystem happen so infrequently, that I would suggest a minimal of a 3 month period between updates. And for such a low frequency, I dont know if automating this would be worth it. 

But even before automation we should have some tests in place. I am thinking about a NixOS test with some of the popular packages. Maybe starting a chicken http server and letting a chicken http client connect to it.
This is something that the automation could then run and mark the PR either as ready ( tests succeed ) or as draft ( tests fail).

Also I have some changes prepared with regard to cross compilation, that I want to get in first and some tests for that would be good as well.

**Comment by konst-aa** [comment]
> Maybe starting a chicken http server and letting a chicken http client connect to it.

I don't understand how starting a chicken http server will be used for testing. Is it just to test the `http-client` egg? 
> Also I have some changes prepared with regard to cross compilation, that I want to get in first and some tests for that would be good as well.  

Awesome!!

**Comment by nagy** [comment]
> I don't understand how starting a chicken http server will be used for testing. Is it just to test the http-client egg?

My intention was to test, that the ecosystem with its eggs in general is working. A few other ecosystems in nixpkgs have some like a "withPackages" wrapper. So for example Python has `python3.withPackages(ps: [ps.addict])` . With gives you a wrapped python, where this package can be imported.

Currently, we dont have that for chicken, so that we have to manually set the `CHICKEN_REPOSITORY_PATH` environment variable to point to the other packages. At least I have not found another way to be able to import the eggs. 

My plan is first to make such a wrapper available for chicken, which then could be used in the nixos test. This should make it easy to test the ecosystem. If chicken then is able to serve a website and retrieve it too, I would conclude, that the ecosystem in general is not broken.

**Comment by konst-aa** [comment]
Makes sense. `withPackages` would also be sweet as there'd be no need to use `makeWrapper` for compiled executables, right?

**Comment by nagy** [comment]
> as there'd be no need to use makeWrapper for compiled executables, right?

I have just published another cross compilation PR that gets rid of the current makeWrapper layer. But with the upcoming `withPackages` wrapper, I think we would still need to have at least one layer, as all the other ecosystems have that as well.

**Pull request merged**
