### PR TITLE
various: mark as broken or fix

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

This either marks as broken or fixes various packages which are failing in nixpkgs-review builds of #108741, which are also broken at HEAD.

* mxnet: fix build since GCC10 stdenv bump by reverting to GCC9 to avoid linker errors (fix)
* python3Packages.cliff: remove version constraint on PrettyTable, add which to checkInputs (fix)
* python3Packages.tensorflow-probability: broken by a tensorflow upgrade, non-trivial to update (mark as broken)
* python3Packages,optuna: broken by lapack/BLAS changes, as well as sklearn upgrade (mark as broken)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukegb** [comment]
@ofborg build mxnet python3Packages.cliff

cc maintainers of broken packages @costrouc @timokau

**Comment by SuperSandro2000** [comment]
I did a quick check to find a patch for mxnet but couldn't find one. Maybe I overlooked it.

**Comment by lukegb** [comment]
Yeah, there's #106866 as well which I think fixes the cliff build, although the cliff tests seemed to work for me (and on OfBorg); cc @IvarWithoutBones

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108977` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages marked as broken and skipped:
</summary>
<ul>
<li>python37Packages.optuna</li>
<li>python38Packages.optuna</li>
<li>python39Packages.cliff</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>python37Packages.cliff: log was empty</li>
  </ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>python38Packages.cliff</li>
</ul>
</details>

**Comment by timokau** [comment]
I agree that we should mark broken packages as broken. I haven't noticed that `tensorflow-probability` was broken since I haven't used it in a while. I probably will not use it in the near future either. Would you mind removing me from the maintainers list of that package as well?

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108977` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages marked as broken and skipped:
</summary>
<ul>
<li>python37Packages.optuna</li>
<li>python38Packages.optuna</li>
<li>python39Packages.cliff</li>
</ul>
</details>
<details>
<summary>
6 packages built:
</summary>
<ul>
<li>mxnet</li>
<li>python37Packages.cliff</li>
<li>python37Packages.mxnet</li>
<li>python38Packages.cliff</li>
<li>python38Packages.mxnet</li>
<li>python39Packages.mxnet</li>
</ul>
</details>

**Comment by lukegb** [comment]
> I agree that we should mark broken packages as broken. I haven't noticed that `tensorflow-probability` was broken since I haven't used it in a while. I probably will not use it in the near future either. Would you mind removing me from the maintainers list of that package as well?

No worries, done.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108977` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages marked as broken and skipped:
</summary>
<ul>
<li>python37Packages.optuna</li>
<li>python38Packages.optuna</li>
<li>python39Packages.cliff</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>python37Packages.cliff: log was empty</li>
  </ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>python38Packages.cliff</li>
</ul>
</details>

**Comment by lukegb** [comment]
Ah, you fixed cliff in #108925. I'll pull that change out of the stack.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108977` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>python37Packages.optuna</li>
<li>python38Packages.optuna</li>
</ul>
</details>
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>mxnet</li>
<li>python37Packages.mxnet</li>
<li>python38Packages.mxnet</li>
<li>python39Packages.mxnet</li>
</ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
