### PR TITLE
gittyup: fix file-open dialog under plasma6 and add maintainer pbek

### LINKED ISSUE #295814: Gittyup: "Open repository" not working in KDE Plasma 6
### Describe the bug

In [Gittyup](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/version-management/gittyup/default.nix) with KDE Plasma 6 you'll get an error `Unable to create KIO worker. Unknown protocol 'file'.` when trying to open a repository.

### Steps To Reproduce

1. Use plasma6 with `services.desktopManager.plasma6.enable = true;` (Wayland or X11 doesn't matter) in nixos-unstable
2. Press `Ctrl + O` in Gittyup to open a repository
3. See error dialog `Unable to create KIO worker. Unknown protocol 'file'.`

### Expected behavior

Directory picker allows choosing directory.

### Screenshots

image

### Logs

```
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.widgets.kdirmodel: protocol mismatch: "file" vs ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Select Folder" msgid_plural: "" msgctxt: "@title:window"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "New Folder..." msgid_plural: "" msgctxt: "@action:button"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "New Folder..." msgid_plural: "" msgctxt: "@action:inmenu"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Move to Trash" msgid_plural: "" msgctxt: "@action:inmenu"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Delete" msgid_plural: "" msgctxt: "@action:inmenu"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Show Hidden Folders" msgid_plural: "" msgctxt: "@option:check"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Properties" msgid_plural: "" msgctxt: "@action:inmenu"
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.core: "Unable to create KIO worker. Unknown protocol 'file'."
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
```

### Notify maintainers

No maintainers. 😅
@thiagokokada removed himself.
Maybe @zendo?

@K900, is this something you want to get involved in?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05.20240312.0ad13a6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/run/current-system/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by pbek**
## Description of changes

Fixes the file-open dialog under plasma6 and adds pbek as maintainer.

Fixes #295814

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
Actually, hold on, this might be a frameworkintegration thing. Can you see if it works in a non-Plasma session without this change?

**Comment by pbek** [comment]
Hm, good point. I haven't any non-plasma setup anywhere. 🙈

**Comment by pbek** [comment]
It is still working under plasma5 without kio tho...

**Comment by K900** [comment]
That's because Plasma 5 installs kio by default: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/services/x11/desktop-managers/plasma5.nix#L217

Anyway, this is definitely the wrong approach.

**Comment by pbek** [comment]
> Anyway, this is definitely the wrong approach.

Yes, I think so too.

**Pull request closed without merging**
