### PR TITLE
locustio: 0.7.2 -> 0.7.5

### PR DESCRIPTION
**Pull request by disassembler**
###### Motivation for this change
fixes build failures.

related to #28643

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by disassembler** [comment]
I tried upgrading gevent to 1.2.2 as default version and that just brought in a mess with nox review (lots of stuff already broken), so I added 1.2.2 instead of upgrading for now. This builds and and dependencies do as well.

**Comment by FRidh** [comment]
Sorry, same as in the previous PR, we don't keep multiple versions.

**Comment by disassembler** [comment]
Per @FRidh we don't keep multiple versions, so upgrading gevent to 1.2.2. There's lots of build failures with nox review, but a lot of those are broken already and in the list of packages to fix. Splitting out other changes to new PR's and moving locustio into it's own module.

**Comment by FRidh** [comment]
OK, this will need a bit more testing done. I'll keep this one for later.

**Comment by globin** [comment]
ping, this is broken on the release branch currently

**Comment by disassembler** [comment]
superseded by #31863 closing.

**Pull request closed without merging**
