### PR TITLE
ruby: only keep the latest tiny per major.minor

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [x] Built on platform(s): NixOS
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Tiny versions are just for bug-fixes and should be upgraded. I think that the
list has grown a bit too much organically and should be trimmed.

/cc @manveru @cstrahan

### CODE REVIEW

**Comment by globin** [comment]
:+1: if nothing depends on them

**Comment by zimbatm** [comment]
Cool. Still running nox-review

**Comment by zimbatm** [comment]
Everything is compiling fine. Package touched by the change: vagrant, platformio, steam, bundix and kodi-plugin-steam-launcher.

**Comment by globin** [comment]
Vagrant will probably break if it's not the correct patch version as it uses precompiled gems afair

**Comment by zimbatm** [comment]
vagrant is working fine here, at least `vagrant up` and `vagrant ssh` work correctly.

**Comment by globin** [comment]
:+1:

**Pull request merged**
