### PR TITLE
thanos: 0.31.0 -> 0.32.5

### PR DESCRIPTION
**Pull request by anthonyroussel**
## Description of changes

https://github.com/thanos-io/thanos/releases/tag/v0.32.0
https://github.com/thanos-io/thanos/releases/tag/v0.32.1
https://github.com/thanos-io/thanos/releases/tag/v0.32.2
https://github.com/thanos-io/thanos/releases/tag/v0.32.3
https://github.com/thanos-io/thanos/releases/tag/v0.32.4
https://github.com/thanos-io/thanos/releases/tag/v0.32.5

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jpds** [comment]
I've pushed up a commit on top of this branch for .5 if you'd like to cherry-pick that in: https://github.com/jpds/nixpkgs/commit/ddd780aef9196af6ef3e3072922e178dc7e37020

**Comment by anthonyroussel** [comment]
> I've pushed up a commit on top of this branch for .5 if you'd like to cherry-pick that in: [jpds@ddd780a](https://github.com/jpds/nixpkgs/commit/ddd780aef9196af6ef3e3072922e178dc7e37020)

@jpds Thanks! I've updated the pull-request for Thanos v0.32.5

**Comment by anthonyroussel** [comment]
@ofborg test thanos

**Comment by teutat3s** [comment]
Result of `nixpkgs-review pr 260089` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>thanos</li>
  </ul>
</details>

**Review by teutat3s — APPROVED** [review]

**Comment by teutat3s** [comment]
This fixes the build that's currently failing, so:
ZHF: #265948

**Comment by teutat3s** [comment]
https://github.com/ofborg build thanos thanos.tests

**Pull request merged**
