### PR TITLE
Haskell Packages: Use correct version of indexed-list-literals for vector-sized-1.0.0.0

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by peti** [comment]
@GrahamcOfBorg build haskellPackages.vector-sized_1_0_0_0

**Review by peti — CHANGES_REQUESTED** [review]
Please address the merge error.

**Comment by expipiplus1** [comment]
@peti, done, thanks.

**Comment by peti** [comment]
@GrahamcOfBorg build haskellPackages.vector-sized_1_0_0_0

**Review by peti — APPROVED** [review]

**Pull request merged**
