### PR TITLE
shadow: 4.11.1 -> 4.13

### PR DESCRIPTION
**Pull request by Izorkin**
###### Description of changes
Update shadow to version 4.13.
Removed patch shadow-4.1.3-dots-in-usernames. This change included in this PR - https://github.com/shadow-maint/shadow/pull/551
Added `dev` outputs.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
cc @SuperSandro2000 @matthewbauer @NeQuissimus @alyssais

**Review by NeQuissimus — APPROVED** [review]
LGTM

**Comment by Izorkin** [comment]
This PR checked in test virtual mashine.
The test seems to break here because of an error related to nix-build:
```
error (ignored): error: cannot unlink '/tmp/nix-build-strace-6.0.drv-0/strace-6.0': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-openssl-3.0.7.drv-3/openssl-3.0.7/test': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-libbfd-2.38.drv-0/binutils-2.38/bfd': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-bison-3.8.2.drv-0/bison-3.8.2/tests/testsuite.dir/427': Directory not empty
error: derivation '/nix/store/y836wp9pgazqks9nhph5n1gym2vdigy8-nix-info.drv' requires non-existent output 'out' from input derivation '/nix/store/d57jszk5hqgmrhicdx9y5p8107sivm3k-findutils-4.9.0.drv'
```

**Comment by Izorkin** [comment]
Test working:
```
nix-build nixos/tests/shadow.nix
...
shadow: sending monitor command: sendkey ret
shadow: waiting for monitor prompt
(finished: waiting for monitor prompt, in 0.00 seconds)
(finished: sending monitor command: sendkey ret, in 0.00 seconds)
(finished: sending keys ‘logout
‘, in 0.07 seconds)
(finished: subtest: check alternate password hashes, in 8.90 seconds)
(finished: run the VM test script, in 49.16 seconds)
test script finished in 49.21s
cleanup
kill machine (pid 6)
shadow # qemu-kvm: terminating on signal 15 from pid 4 (/nix/store/53kzz0r94qiah77ah20x239w5v06gvg3-python3-3.10.9/bin/python3.10)
(finished: cleanup, in 0.12 seconds)
kill vlan (pid 5)
/nix/store/0gyfrl7apjqjs0pbdxylihwvmg0nrgkw-vm-test-run-shadow

```

**Review by chkno — COMMENTED** [review]
LGTM

**Pull request merged**
