### PR TITLE
makeKernelHeaders: expose via passthru, support kernel 5.3 and newer

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

I want to provide newer kernel headers to a package that requires them.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @lostman

### CODE REVIEW

**Comment by FRidh** [comment]
I agree it would be good to make this function public, however, we should avoid adding more functions to the top-level; it's really intended only for packages and package sets.

**Comment by thefloweringash** [comment]
Is there a recommended place to put functions like these?

**Comment by FRidh** [comment]
Not really. You could add the function to its own `passthru`. You would then get `linuxHeaders.makeLinuxHeaders`.

**Comment by thefloweringash** [comment]
I think there may still be a reason to expose makeKernelHeaders when working with non-mainline features. However the features I wanted were merged around 5.0, so updating to 5.5 is sufficient. Going to close in favor of the update.

**Pull request closed without merging**
