### PR TITLE
python3Packages.tensorflow-bin: relax protobuf, tensorboard version constraints to fix build

### LINKED ISSUE #193616: `python39Packages.tensorflow` build failure on x86_64-linux as of `671fabc9`
## Issue description
Build of `python39Packages.tensorflow` failed on x86_64-linux as of 671fabc93b4d1a3b38499c7b20776477c91b2b15. This is currently breaking `python39Packages.tensorflow-bin`.

```
error: builder for '/nix/store/k89cix611qra1dasaxk75262d8pi7w51-python3.9-tensorflow-2.9.1.drv' failed with exit code 1;
       last 10 log lines:
       > installing
       > Executing pipInstallPhase
       > /build/dist /build
       > Processing ./tensorflow_cpu-2.9.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
       > Requirement already satisfied: astunparse>=1.6.0 in /nix/store/4l5zn60fm3x1fymgxxn0pji35sf06p1g-python3.9-astunparse-1.6.3/lib/python3.9/site-packages (from tensorflow-cpu==2.9.1) (1.6.3)
       > Requirement already satisfied: setuptools in /nix/store/fi05g7pi0haah5klvbp9qjsry31mpfd7-python3.9-setuptools-65.3.0/lib/python3.9/site-packages (from tensorflow-cpu==2.9.1) (65.3.0.post0)
       > Requirement already satisfied: termcolor>=1.1.0 in /nix/store/wjwp9pz0jxl2dx18vsk4dpk169mzpapp-python3.9-termcolor-2.0.1/lib/python3.9/site-packages (from tensorflow-cpu==2.9.1) (2.0.1)
       > ERROR: Could not find a version that satisfies the requirement tensorboard<2.10,>=2.9 (from tensorflow-cpu) (from versions: none)
       > ERROR: No matching distribution found for tensorboard<2.10,>=2.9
       > 
       For full logs, run 'nix log /nix/store/k89cix611qra1dasaxk75262d8pi7w51-python3.9-tensorflow-2.9.1.drv'.
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/3155463991)

python39Packages.tensorflow-bin maintainers cc: @jyp @abbradar @cdepillabout
python39Packages.tensorflow maintainers cc: @jyp @abbradar
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 671fabc93b4d1a3b38499c7b20776477c91b2b15
2. Run `nix-build -A python39Packages.tensorflow`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-1020-azure, Ubuntu, 20.04.5 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/store/sx8xlilbqymsa9341yxpivf57hi0az6r-source`
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/3155463991) that created this issue.
- Internal tags: -7116856311112812584 4075365868238245471

### PR DESCRIPTION
**Pull request by samuela**
###### Description of changes

Fix https://github.com/NixOS/nixpkgs/issues/193616.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by FRidh — COMMENTED** [review]
Note we have the pythonRelaxDepsHook for modifying wheel constraints.

**Comment by samuela** [comment]
> Note we have the pythonRelaxDepsHook for modifying wheel constraints.

I thought about that but wasn't sure whether it works with whl files as well. I'll give it a shot!

**Comment by samuela** [comment]
Does `pythonRelaxDepsHook` offer a way to remove dependencies altogether? For better or worse that is required in the tensorflow-bin derivation for the libclang, keras, and tensorlow-io-gcs-filesystem dependencies.

**Comment by samuela** [comment]
Just found that there is a `pythonRemoveDeps` option as well, but I'm not able to get either `pythonRelaxDeps` nor `pythonRemoveDeps` to work with `format = "wheel";`. Is this a supported pattern or should I file a bug report?

**Comment by samuela** [comment]
Conclusion from https://github.com/NixOS/nixpkgs/issues/198342 is that it's not possible to work around, but that a fix on the `pythonRelaxDepsHook` side of things should be straightforward.

That change will cause a massive set of rebuilds, so I'd like to keep it separate from this PR.

**Pull request merged**
