### PR TITLE
mxisd: 1.2.0 -> 1.4.3

### PR DESCRIPTION
**Pull request by mguentner**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @fpletz @hschaeidt :spider_web: 
I suggest to backport to 19.03

### CODE REVIEW

**Comment by aanderse** [comment]
@mguentner Sorry for the delay on this. Do you mind doing a git rebase? Please keep in mind that `PermissionsStartOnly` has been deprecated.

**Comment by mguentner** [comment]
@aanderse No worries. Thanks for taking a look.
mxisd 1.4.x seems stable enough. I will test it very soon.
I will might simply push to that branch and we can omit the 1.3.1.

**Comment by aanderse** [comment]
OK sounds good. I'll wait to hear back on a version update.

**Comment by mguentner** [comment]
@aanderse Ready :)

**Comment by aanderse** [comment]
@GrahamcOfBorg build mxisd
@GrahamcOfBorg test mxisd

**Comment by aanderse** [comment]
So it appears someone has removed `mxisd` from `nixos/tests/all-tests.nix` :disappointed: 
@mguentner bonus points if you push another commit on top of this to add `mxisd` (back?) to `all-tests.nix`

**Comment by mguentner** [comment]
@aanderse Pushed

**Comment by aanderse** [comment]
@mguentner thanks!
@GrahamcOfBorg test mxisd

**Comment by aanderse** [comment]
@mguentner can you briefly explain why the code in `preStart` is no longer required? It looks like you're moving from a mutable config file to immutable so are there any backward compatibility/upgrade issues to consider?

**Comment by mguentner** [comment]
@aanderse
At some point mxisd required the config to be named `application.yaml`. Pointing it to the `/nix/store` path produced by `writeText` did not work because of the filename like `hash-something-application.yaml`.

That's why I opted for simply copying the config to the work directory. I used `chmod 444` to prevent mutation.

So it was done because of the configuration requirements of mxisd < 1.3, not because it mutates the config file during runtime.
I don't expect / didn't run into any upgrade issues because of that.

If an existing config has something in `extraConfig` however, this might need to be adjusted as config format changed slightly. It's no longer some yaml-inspired format but standard-yaml.

More on that: https://github.com/kamax-matrix/mxisd/wiki/Upgrade-Notes#v130

**Comment by aanderse** [comment]
@mguentner you have been super helpful in my review of this change. Thank you!

**Pull request merged**
