### PR TITLE
sourcehut: fix #198478

### LINKED ISSUE #198478: sourcehut.buildsrht fails to build
### Steps To Reproduce
1. build *nix build github:NixOS/nixpkgs/nixos-unstable#sourcehut.buildsrht*

### Build log
```
error: builder for '/nix/store/3ls5r4wnz7fcq7jxhndd425jw8w7s8r7-python3.10-buildsrht-0.82.8.drv' failed with exit code 1;
       last 10 log lines:
       > Installing collected packages: buildsrht
       > Successfully installed buildsrht-0.82.8
       > /build/source
       > Finished executing pipInstallPhase
       > pythonOutputDistPhase
       > Executing pythonOutputDistPhase
       > Finished executing pythonOutputDistPhase
       > pythonOutputDistPhase
       > Executing pythonOutputDistPhase
       > mv: cannot stat 'dist': No such file or directory
```

### Additional context
Other sourcehut python pkgs fail in a similar manner

### Notify maintainers
@eadwu @tjni 

### Metadata
`nix flake metadata github:NixOS/nixpkgs/nixos-unstable`

```
Resolved URL:  github:NixOS/nixpkgs/nixos-unstable
Locked URL:    github:NixOS/nixpkgs/448a599c49978c2794401bfc3a2e1fba1a8663be
Description:   A collection of packages for the Nix package manager
Path:          /nix/store/hlqsxiwbmbgsp66xdlf5adlzz2y3xmh6-source
Revision:      448a599c49978c2794401bfc3a2e1fba1a8663be
Last modified: 2022-10-28 14:21:31
```

### PR DESCRIPTION
**Pull request by ju1m**
###### Description of changes

- [X] Fix #198478 by using `propagatedNativeBuildInputs` instead of manually propagating dependencies, which caused those build problems due to non-idempotent hooks being run twice.
Kudos to @winterqt for making sense of this bug in https://github.com/NixOS/nixpkgs/pull/198586

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ju1m** [comment]
meh, GitHub selected NixOS:sourcehut as base by default. what a mess.

**Comment by winterqt** [comment]
If you can't fix it, might be worth it just to make another PR.

**Comment by ju1m** [comment]
@winterqt, I was able to edit the merge base, now the PR is only adding 2 commits instead of 10000+ ^^
Hm, now there's another error popping up concerning `pagessrht` when merging againt latest master.

**Comment by ju1m** [comment]
Sorry everyone, I never, ever intended to notify all those reviewers. GitHub is too complex for me >_>

**Comment by dasJ** [comment]
Please open a new PR that does not ping unrelated people

**Pull request closed without merging**
