### PR TITLE
firefox-*-bin: updates

### PR DESCRIPTION
**Pull request by garbas**
* firefox-beta-bin: 51.0b8 -> 54.0b13

* firefox-devedition-bin: init at 54.0b14

Firefox DevEdition became a new product of Mozilla and is "repackaged"
Firefox Beta with its own release channel and six weeks release cycle as
other channels. It is no longer being built on nightly basis

* updated the update.nix script to facilitata firefox-devedition-bin

* disabling automatic updates by pointing to non existing channel

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
LGTM but I haven't tested it. I will do that later today if the PR is still open :)

**Comment by garbas** [comment]
I found the error which was already present before this update, but nevertheless i might ask here how fix it. If you open any ``Browser`` button where file selector shows up, then all channels of firefox-bin crash. I'm probably missing some dependency which is loaded dynamically, but I'm yet to learn how to detect this.

And for those who are looking for Firefox Nightly, look no further then github.commozilla/nixpkgs-mozilla :) and wow does nightly works faster.

**Comment by garbas** [comment]
hmm ... having a browser dialog works on nightly. i wonder what am i missing here.

**Comment by 7c6f434c** [comment]
Hm… Does `firefox-bin` set `gtk3` attribute on the unwrapped version? I think `wrapFirefox` sets `XDG_DATA_DIRS` needed by `gtk3` only when `browser.gtk3` attribute exists.

**Comment by garbas** [comment]
@7c6f434c tnx for the pointer. i just ``inherit gtk3`` in ``firefox-bin/default.nix`` (see last commit in this PR) and that fixed the problem. would this be ok solution?

**Comment by 7c6f434c** [comment]
Well, the main derivation adds it to `passthru`, but as it is a dependency already the difference is negligible.

**Pull request merged**
