### PR TITLE
calibre: add missing dependency, fixes #78642

### LINKED ISSUE #78642: Calibre 4.x requires PyQtWebEngine for ebook reader
**Describe the bug**
The ebook reader in Calibre 4.0 and above requires PyQtWebEngine for the ebook reader, as it will otherwise throw an ImportError.

**To Reproduce**
1. Install `calibre` from latest unstable `nixpkgs`.
2. Run calibre from terminal.
3. Attempt to open an ebook in the viewer (the quick start guide included should work fine for this example)
4. View the error in the terminal.

**Expected behavior**
The ebook reader to open properly.

**Additional context**
On my system, I have made an overlay which adds `python27.pyqtwebengine` to the `buildInputs` of `calibre`, and in the resulting derivation the ebook reader works perfectly fine. This seems just to be a missing dependency issue.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.97, NixOS, 19.09.1957.57c35c63004 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1957.57c35c63004, home-manager-19.09, nixos-unstable-20.03pre210078.90441b4b47f, nur"`
 - channels(malset): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ calibre ]
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by chamatht**
Fixes #78642
This commit adds pyqtwebengine.

###### Motivation for this change
Without pyqtwebengine, when you try to view an ebook, you get the following error 
```
Traceback (most recent call last):
  File "/nix/store/1zqhszwa961qf3nciz5wv854sfff18ph-calibre-4.8.0/bin/.calibre-parallel-wrapped", line 20, in <module>
    sys.exit(main())
  File "/nix/store/1zqhszwa961qf3nciz5wv854sfff18ph-calibre-4.8.0/lib/calibre/calibre/utils/ipc/worker.py", line 209, in main
    result = func(*args, **kwargs)
  File "/nix/store/1zqhszwa961qf3nciz5wv854sfff18ph-calibre-4.8.0/lib/calibre/calibre/gui_launch.py", line 80, in ebook_viewer
    from calibre.gui2.viewer.main import main
  File "/nix/store/1zqhszwa961qf3nciz5wv854sfff18ph-calibre-4.8.0/lib/calibre/calibre/gui2/viewer/main.py", line 12, in <module>
    from PyQt5.QtWebEngineCore import QWebEngineUrlScheme
ImportError: No module named QtWebEngineCore

```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)

- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Fixes https://github.com/NixOS/nixpkgs/issues/78642

**Review by pSub — APPROVED** [review]

**Comment by FRidh** [comment]
As written in #78642, we should not need webkit anymore so that change needs to be made.

**Comment by chamatht** [comment]
@FRidh made the change

**Review by veprbl — APPROVED** [review]
Works

**Pull request merged**
