### PR TITLE
Nextcloud: use php.ini for cron job as well

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
The cron jobs will sometimes fail because not enough memory is available. Enough memory _would_ be available if the php.ini for nextcloud's fpm pool were used, so use it.

###### Things done

- [x] Deployed a nextcloud using this and checked that the cronjob now succeeds where it used to fail
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lheckemann** [comment]
@ofborg test nextcloud

**Comment by aanderse** [comment]
This gets complicated because the new `phpIni` option could be misleading. `phpfpm` pools will also read from `php.buildEnv { extraConfig }` if provided.

Let's pull in a few more minds to make sure we get this done in the most understandable way possible by pulling in a few more minds to mull this over... @NixOS/php and @jtojnar.

**Comment by etu** [comment]
This could fail horribly if one used a customized PHP for the fpm pool and than that the cron job used the ini file with a non-customized PHP and pulled the ini-file from a customized one.

Better way would be to configure the PHP to contain all the settings and use the extended PHP package in both places.

**Comment by aanderse** [comment]
Actually reading through the code this already uses the custom `php` package which should include the proper `ini`. The issue may be here... https://github.com/mayflower/nixpkgs/blob/078cfc0926ffc5dcaa45b29cbbbb7451e0ff8a30/nixos/modules/services/web-apps/nextcloud.nix#L28

**Comment by lheckemann** [comment]
Hm, ok, I'm confused in that case. It was running out of memory with a limit significantly lower than our maxUploadSize. I'll convert this to a draft.

**Comment by Ma27** [comment]
@lheckemann did you have time to take another look at this? :)

**Comment by lheckemann** [comment]
We're getting the following, in spite of maxUploadSize being set to 16G:
```
systemd[1]: Starting nextcloud-cron.service...
php[43203]: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /rpool/nextcloud/store-apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/List.php on line 323
Nextcloud[43203]: {"reqId":"zZveIu4jbm36qnOZAWgB","level":3,"time":"2020-07-13T08:37:20+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at /rpool/nextcloud/store-apps/mail/ven>
php[43203]: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /rpool/nextcloud/store-apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/List.php on line 238
systemd[1]: nextcloud-cron.service: Main process exited, code=exited, status=255/EXCEPTION
```
So the memory limit does seem to be 128M instead of 16G, and the changes in this PR did fix that issue. What I don't understand at this point is why what @aanderse said doesn't seem to be the case:

>Actually reading through the code this already uses the custom php package which should include the proper ini.

Will investigate soon.

**Comment by Ma27** [comment]
@lheckemann is this happening on 20.03? On 20.03 the PHP package in use is `phpPackage = pkgs.php73;` while the new `php.buildEnv` API is used on `master` to configure the package used for `nextcloud-cron`.

**Comment by lheckemann** [comment]
That'll be it, thanks! :man_facepalming:

**Pull request closed without merging**
