### PR TITLE
maintainers: add lizelive

### PR DESCRIPTION
**Pull request by lizelive**
###### Description of changes

Split adding self to new pr.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Why you should learn how to contribute before contributing?

Are you serious?

**Comment by lizelive** [comment]
@AndersonTorres no why did you close the pr and why are you being rude.

I read the [guide](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) and see nothing against this.
At this point I'm really frustrated because this is trival change i have been trying to get in for 4 days.

@lilyinstarlight dm me on discord and says their is a policy that says two commits.

**Comment by necauqua** [comment]
'learn git' can be expanded into:
- Your initial rebase (somehow) touched 5000+ files, notifying all the maintainers of those files - it shouldn't have happened if the rebase was correct - you messed up something (significantly, it seems, oh well)
- When asked to split the commit into two it meant (and that's one of the ways of doing this in git):
    - soft-reset to parent commit
    - commit changes to maintainers and the starsector update in separate consecutive commits (following the naming convention that's used in nixpkgs)
    - force-push your branch to have those better commits in place of the one that was in that pull request
    
If the terms like "soft-reset" or "force-push" meant nothing to you - well, learn git, then come back, there's nothing wrong with that 🤷

---
imo AndersonTorres is not being rude;
wegank was passive-agressive, indeed

The "4 days" comment does not really mirror that you were being blocked just for not following the conventions or whatever, nixpkgs is _huge_ and thus is slow, even a perfect MR can take weeks to get merged in 🤷 

Well that's depending on how popular/maintained the package is, of course, and trust me, starsector is not one of these

Actually I think my fix for the starsector icon is still open

**Comment by AndersonTorres** [comment]
> @AndersonTorres no why did you close the pr and why are you being rude.

You started it with a "I don't wanna talk", and you are the one complaining about rudeness?

I needed to stalk your history in order to understood why.

> I read the guide and see nothing against this.

Each pull request is processed in parallel and independently by our CI machinery.

When you create two PRs that depends one of the other, the second PR will throw a syntax error and will remain in an unusable, blocked state until the merge of the blocking PR.

This is why PRs to merely add a new maintainer are almost inexistent - they almost will be a single commit from a larger PR.

And, **again**: you said "I don't wanna talk".
This is trollish behaviour, even accounting for your herculeous work on updating startsector.

> At this point I'm really frustrated because this is trival change i have been trying to get in for 4 days.

Too much code, too little maintainers.

And we are in the meantime of the arrival of a new release.

**Comment by AndersonTorres** [comment]
_Mental note: add a note to "very new contributors" to the contributing guide_

**Comment by lizelive** [comment]
@necauqua thank you for being nice and explaining

> If the terms like "soft-reset" or "force-push" meant nothing to you - well, learn git, then come back, there's nothing wrong with that shrug
they do. i prob rebased wrong then assumed that the notify everyone was a github issue because I don't work in large repo on github. use azure devop.

I always just think it's rude to close someone's pr.

**Comment by lizelive** [comment]
> _Mental note: add a note to "very new contributors" to the contributing guide_

I would love to see that!

**Comment by AndersonTorres** [comment]
I always just think it's rude to start a contribution with a "I don't wanna talk, la la la".

After all, "there is nothing in the guide about keeping PRs open".

Further, I always just think it's rude to a newbie imposing his own ethics over a group.

**Pull request closed without merging**
