### PR TITLE
haskellPackages.hexstring: unbreak

### PR DESCRIPTION
**Pull request by JulienMalka**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by cdepillabout — CHANGES_REQUESTED** [review]
Thanks for putting this PR together!

A couple things:

- Could you target the `haskell-updates` branch instead of `master`?  Make sure to read https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md before rebasing.
- We generally try not to carry around patches in Nixpkgs.  Is there some way you can fetch this change from upstream, ideally with `fetchpatch`?  You should be able to find a bunch of uses of `fetchpatch` in `configuration-common.nix`.
- Make sure not to commit any formatting changing (like in `configuration-common.nix`) since it makes the diff too hard to read.

**Comment by JulienMalka** [comment]
Thanks for your review :)

>     * Could you target the `haskell-updates` branch instead of `master`?  Make sure to read https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md before rebasing.

Done!

>     * We generally try not to carry around patches in Nixpkgs.  Is there some way you can fetch this change from upstream, ideally with `fetchpatch`?  You should be able to find a bunch of uses of `fetchpatch` in `configuration-common.nix`.

The patch is taken from here: https://github.com/solatis/haskell-hexstring/issues/3 
Upstream is irresponsive and there is no PR open. I also had to adapt it a little bit for it to apply cleanly. So I don't think we can do anything else that carry it in nixpkgs, tell me if you have another idea.


>     * Make sure not to commit any formatting changing (like in `configuration-common.nix`) since it makes the diff too hard to read.

Oopsie, fixed.

**Comment by cdepillabout** [comment]
@JulienMalka Thanks for the quick response.

> Upstream is irresponsive and there is no PR open. I also had to adapt it a little bit for it to apply cleanly. So I don't think we can do anything else that carry it in nixpkgs, tell me if you have another idea.

How about sending a PR to the upstream repo, and then just fetching that PR/commit with `fetchpatch`?  That would at least help other Haskellers (non-nix users) who encounter this same problem, and be a little better than carrying around the patch here in nixpkgs.

**Comment by JulienMalka** [comment]
> @JulienMalka Thanks for the quick response.
> 
> > Upstream is irresponsive and there is no PR open. I also had to adapt it a little bit for it to apply cleanly. So I don't think we can do anything else that carry it in nixpkgs, tell me if you have another idea.
> 
> How about sending a PR to the upstream repo, and then just fetching that PR/commit with `fetchpatch`? That would at least help other Haskellers (non-nix users) who encounter this same problem, and be a little better than carrying around the patch here in nixpkgs.

I can definitely try that :)

**Comment by JulienMalka** [comment]
@cdepillabout The patch does no apply on the upstream project... The source hosted on Cabal must be ever so slightly (I think whitespaces, because was not able to spot the difference ?) different than the one on Github.

**Pull request closed without merging**
