### PR TITLE
xfce: SVG icon support in xfce4-panel, fixes #18536

### LINKED ISSUE #18536: Some icons (SVG?) are not displayed in Xfce in 16.09beta172
## Issue description

I’ve tentatively updated my mother’s laptop—her DM is Xfce—to 16.09beta172 and some of the icons are gone:
- Chromium’s,
- battery applet,
- “Applications” menu in the corner of the display,
- LibreOffice.

Also, this might be of importance, `gtk-update-icon-cache` is gone from the `PATH`. It was there, previously.
### Steps to reproduce
1. Enable Xfce on 16.09beta172.
2. Install, e.g., Chromium → no icon shown in Xfce.
## Technical details
- System: 16.09beta172.e3bdf6b (Flounder)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: "16.09beta172.e3bdf6b"

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

Fixes #18536. /cc @davidak 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by davidak — APPROVED** [review]

**Comment by yegortimoshenko** [comment]
@davidak Have you tried to build it?

**Comment by davidak** [comment]
@yegortimoshenko yes, works fine. thank you!

**Review by vcunat — APPROVED** [review]
Sounds fine.

**Comment by orivej** [comment]
What application can be used for testing?

**Comment by davidak** [comment]
@orivej you can see this icon theme with Xfce https://github.com/NixOS/nixpkgs/pull/32745#issuecomment-352291952
Maybe there is another icon theme with SVG icons already packaged that you can use to test this.

**Pull request merged**
