### PR TITLE
environment.pathsToLink = [ "/share" ];

### PR DESCRIPTION
**Pull request by obadz**
It took me a few ours to figure out why mime file associations would no longer work and thumbnails in file managers wouldn't display after I got rid of GNOME.

Most desktops have added `/share` to `environment.pathsToLink` but that's not the default in system-path:

```
./e19.nix:    environment.pathsToLink = [ "/etc/enlightenment" "/etc/xdg" "/share/enlightenment" "/share/elementary" "/share/applications" "/share/locale" "/share/icons" "/share/themes" "/share/mime" "/share/desktop-directories" ];
./xfce.nix:    environment.pathsToLink = [ "/share/xfce4" "/share/themes" "/share/mime" "/share/desktop-directories" "/share/gtksourceview-2.0" ];
./gnome3.nix:    environment.pathsToLink = [ "/share" ];
./kde5.nix:    environment.pathsToLink = [ "/share" ];
./kde4.nix:    environment.pathsToLink = [ "/share" ];
```

`system-path.nix` had:

```
        "/share/doc"
        "/share/emacs"
        "/share/info"
        "/share/man"
        "/share/nano"
        "/share/org"
        "/share/terminfo"
        "/share/vim-plugins"
```

Wouldn't be a reasonable default to include `/share` there so that those of us who don't use desktops can use the mime stuff seamlessly? At the very least we should be adding `/share/mime` which is mentioned in `system-path.nix`:

``` nix
postBuild =
        ''
          if [ -x $out/bin/update-mime-database -a -w $out/share/mime/packages ]; then
              XDG_DATA_DIRS=$out/share $out/bin/update-mime-database -V $out/share/mime > /dev/null
          fi
```

### CODE REVIEW

**Comment by edolstra** [comment]
:-1: because this bloats the system profile. (`/share` can easily produce a few dozen megabytes of symlinks, which need to be regenerated on almost every configuration change.)

**Comment by lethalman** [comment]
Adding `share/mime` is fine in my opinion. But adding the whole `/share` is not a good idea. GNOME has `/share` because I hadn't time to shrink it yet.

**Comment by vcunat** [comment]
+1 for `share/{applications,mime}` and maybe some other particular locations. Those will be mostly present only when you install desktop apps, in which case you likely want those databases.

**Comment by edolstra** [comment]
Yeah, adding those is probably a good idea regardless of the desktop environment.

**Comment by obadz** [comment]
Ok I can resubmit with `share/{applications,mime, and maybe icons?}`. Not sure if `locale` is useful.

I'm not sure it will make that much of a difference vs including all `/share`.  Here are the directories with > 1Mb of symlinks on my system:

```
12.6 MiB [##########] /man                                                                                                                                                                  
12.6 MiB [######### ] /locale
 3.3 MiB [##        ] /mime
 1.6 MiB [#         ] /icons
```

**Comment by lethalman** [comment]
If we want to include icons, then I think it's better to enable applications,mime,icons only if xserver is enabled.

**Comment by vcunat** [comment]
It could depend on xserver being enabled, but if you don't have it, you likely won't install much stuff providing these paths. So far I can think of
```
# common desktop locations
"/share/mime" "/share/icons" "/share/themes"
# http://standards.freedesktop.org/menu-spec/1.1/
"/share/menus" "/share/applications" "/share/desktop-directories"
```

**Comment by lethalman** [comment]
@vcunat that's true!

**Comment by obadz** [comment]
Sorry closed by accident.

I tried @vcunat's paths, my `/share` went from 50Mb to 33Mb of symlinks, so essentially all the difference comes from `/locale`.

**Comment by obadz** [comment]
Let me know if you want me to resubmit with the paths in https://github.com/NixOS/nixpkgs/pull/9622#issuecomment-137403324

**Comment by obadz** [comment]
So hmm... should I resubmit with changes given the data sizes observed?

**Comment by lethalman** [comment]
You can update this one.

**Comment by obadz** [comment]
I mean, is it worth losing the generality of including `/share` given that the only sizeable subdirectory we're avoiding is `/locale`, coming in at 13Mb (on my system at least) ?

**Comment by oxij** [comment]
It'd be nice if we had

    environment.pathsToLink = [ "/share" ];
    environment.pathsNotToLink = [ "/share/locale" ];

wouldn't it?

**Comment by vcunat** [comment]
It isn't just locale. Most of data belongs into "/share" and there's no need to symlink it. I'll push the list above by hand soon to both master and 15.09 (unless someone does it first).

**Comment by obadz** [comment]
@vcunat, I updated the commit here if you want to merge that.

**Comment by vcunat** [comment]
Right, pushed your commit.

**Comment by obadz** [comment]
Great, thx

**Pull request closed without merging**
