### PR TITLE
[Backport release-22.05] zfs: 2.1.4 -> 2.1.5

### PR DESCRIPTION
**Pull request by Madouura**
(cherry picked from commit 8cfcee74b1678205aa82af92f2daeec293d50ced)

###### Description of changes
 #178632
Bot failed to automatically backport due to documentation.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
Hmmh, this would mean we update ZFS to 2.1.5 in 22.05 already.

Considering the stability of ZFS, I guess this is fine, but then we should have added the release notes to the 22.05 release notes, instead of 22.11?

**Comment by Madouura** [comment]
I'll go ahead and add the release notes to the PR then.
In a separate commit though, since I don't want to taint the cherry-pick.

**Comment by Madouura** [comment]
Also all tests except ``nixosTests.zfs`` pass.

**Comment by flokli** [comment]
Sorry, I wrote this confusingly.

If we backport this, we effectively make it appear in the 22.05 release - so the release notes on master should also reflect that, and not pretend it'll only ever end up in 22.11.

I propose sending a PR to master that moves it to the 22.05 release notes, and then cherry-pick both commits in this PR.

**Comment by PetarKirov** [comment]
@Madouura @flokli  any ideas why this breaking change [1] was not caught by Hydra? How can we prevent such problems to happen in the future?

[1]:  If `boot.kernelPackages` is set to `config.boot.zfs.package.latestCompatibleLinuxPackages`, the build fails with the error reported in #179551

**Pull request merged**
