### PR TITLE
libnma: 1.10.4 -> 1.10.6

### PR DESCRIPTION
**Pull request by dev-null-undefined**
libnma version bump
Removed gschema eap patch as the issue it addressed has been fixed in the new release. https://gitlab.gnome.org/GNOME/libnma/-/commit/6c49565725d6ae1ee85a306bed86667e9479242c

### CODE REVIEW

**Comment by bobby285271** [comment]
There is [no 1.10.7 right now](https://download.gnome.org/sources/libnma/1.10/), the development is [not even started](https://gitlab.gnome.org/GNOME/libnma/-/commit/71c6a75ffd16391969892d8eaa236bf7bcb9275a). Is it okay to go to 1.10.6, or do you wish to skip 1.10.6 because of some known issues?

**Comment by dev-null-undefined** [comment]
> Actually [1.10.7 sounds like a development release](https://gitlab.gnome.org/GNOME/libnma/-/commit/71c6a75ffd16391969892d8eaa236bf7bcb9275a). Is it okay to go to 1.10.6?
This PR was supposed to be just to cost less confusion once 1.10.7 is realesed since it will be the first release containing fix that will be addressing the same issue as the patch did, and i though that creating draft ready for just sha change could help if that happens.

In PR description there is the exact commit that is addressing this issue and unluckily the 1.10.6 does not contain it yet (26 minutes late). But someone else can surely upgrade to 1.10.6 before that and it should work just fine (with the patch).

**Comment by dev-null-undefined** [comment]
Now looking back at their release naming it's probably going to be 1.10.8 you are correct

**Comment by bobby285271** [comment]
> it will be the first release containing fix that will be addressing the same issue as the patch did

If you mean [this patch](https://gitlab.gnome.org/GNOME/libnma/-/commit/6c49565725d6ae1ee85a306bed86667e9479242c), It is part of 1.10.6, you can check which tag contains a specific commit in the GitLab web UI:



You can also [download the tarball](https://download.gnome.org/sources/libnma/1.10/libnma-1.10.6.tar.xz) and open `org.gnome.nm-applet.eap.gschema.xml.in` and check line 3 to see if the change is there.

**Comment by bobby285271** [comment]
Or do you mean you are still encountering the issue in #205687?

**Comment by dev-null-undefined** [comment]
> > it will be the first release containing fix that will be addressing the same issue as the patch did
> 
> If you mean [this patch](https://gitlab.gnome.org/GNOME/libnma/-/commit/6c49565725d6ae1ee85a306bed86667e9479242c), It is part of 1.10.6, you can check which tag contains a specific commit in the GitLab web UI:
> 
> 
> 
> You can also [download the tarball](https://download.gnome.org/sources/libnma/1.10/libnma-1.10.6.tar.xz) and open `org.gnome.nm-applet.eap.gschema.xml.in` and check line 3 to see if the change is there. 

You are correct I got confused by the other schema that still has the path and looks very similar.

**Comment by dev-null-undefined** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>40 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-control-center</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>firewalld-gui</li>
    <li>gnome-browser-connector</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-initial-setup</li>
    <li>gnome.gnome-session</li>
    <li>gnome.gnome-shell</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-tweaks</li>
    <li>networkmanager-fortisslvpn (gnome.networkmanager-fortisslvpn)</li>
    <li>networkmanager-iodine (gnome.networkmanager-iodine)</li>
    <li>networkmanager-l2tp (gnome.networkmanager-l2tp)</li>
    <li>networkmanager-openconnect (gnome.networkmanager-openconnect)</li>
    <li>networkmanager-openvpn (gnome.networkmanager-openvpn)</li>
    <li>networkmanager-vpnc (gnome.networkmanager-vpnc)</li>
    <li>gnome.nixos-gsettings-overrides</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>libnma</li>
    <li>libnma-gtk4</li>
    <li>mojave-gtk-theme</li>
    <li>networkmanager-sstp</li>
    <li>networkmanager_strongswan</li>
    <li>networkmanagerapplet</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.switchboard-plug-network</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>vimix-gtk-themes</li>
    <li>whitesur-gtk-theme</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
#214150 is containing this bump with an update for the update script.

**Comment by bobby285271** [comment]
Closing since https://github.com/NixOS/nixpkgs/pull/214150 is merged (I tested some basic functionality and the bump should be fine, if you are drafting this PR due to some regressions please say, thanks!)

**Pull request closed without merging**
