### PR TITLE
kstars,qolibri: migrate to Qt5.15

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

Also added some optional dependencies: libraw, qtkeychain, knotifyconfig and wcslib

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
Thanks for working on this @freezeboy . As I see it, there are different changes here mixed together.

1. Migration to QT5.15
2. Adding optional deps.
3. Using `mkDerivation` instead of adding `wrapQtAppsHook`.

I think all 3 changes should be separated to 3x2 commits (to each package).

**Comment by freezeboy** [comment]
Ok will do it

**Comment by freezeboy** [comment]
@doronbehar

**Comment by doronbehar** [comment]
Interestingly, the build fails on x86_64 but not on aarch64:

https://logs.nix.ci/?key=nixos/nixpkgs.104438&attempt_id=027ef031-9149-4d7a-a296-9cea53872fda

**Comment by doronbehar** [comment]
@freezeboy please squash the fixup commit. Also, after doing it, please request me for a review or cc me.

**Comment by freezeboy** [comment]
Cc @doronbehar if you can double check i didn't try to rebuild it after the rebase

Thank you

**Review by doronbehar — APPROVED** [review]

**Comment by doronbehar** [comment]
Result of `nixpkgs-review pr 104438` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>kstars</li>
    <li>qolibri</li>
  </ul>
</details>

**Pull request merged**
