### PR TITLE
nixos/plasma6: move out of x11

### PR DESCRIPTION
**Pull request by SuperSandro2000**
This release focuses on wayland, lets give that justice

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by rsniezek — COMMENTED** [review]
Could you add a sentence or two in the commit msg about how are you giving it a justice?

**Comment by SuperSandro2000** [comment]
> Could you add a sentence or two in the commit msg about how are you giving it a justice?

By moving the options from ``services.xserver.desktopManager.plasma6`` to ``services.desktopManager.plasma6``.

**Comment by nyabinary** [comment]
> > Could you add a sentence or two in the commit msg about how are you giving it a justice?
> 
> By moving the options from `services.xserver.desktopManager.plasma6` to `services.desktopManager.plasma6`.

TBH, I would be all for moving everything that supports Wayland out of the xservice/x11 directory, where would Wayland-only DE go, though? E.g. COSMIC?

**Comment by SuperSandro2000** [comment]
> TBH, I would be all for moving everything that supports Wayland out of the xservice/x11 directory, where would Wayland-only DE go, though? E.g. COSMIC?

Yes but let's start somewhere and then go from there to the other bits.

We just strip xserver from the options path. Then the options don't mention a specific display technology.

**Comment by pbek** [comment]
Will it still be possible to use Plasma6 with X11? The Nvidia Wayland Plasma6 support still was mostly broken in all my tests. Especially with old Nvidia graphic cards or with 4k dual screen (but I wasn't even able to make the latter work even with X11).

**Comment by K900** [comment]
Yes.

**Comment by pbek** [comment]
Awesome. I had 0 issues with AMD Radeon or Intel graphic cards. But Nvidia... phew... 😅 No suspend to RAM without garbled characters, no screen-lock without only getting a black screen afterward (the latter also under X11).

**Comment by michaelBelsanti** [comment]
It would be great to have this merged before the Cosmic module, so we can avoid having to move that one in the future

**Review by Shawn8901 — APPROVED** [review]
i use that pr since some days on my fork, i like the idea of moving the desktop managers out of the xserver config namespace, as the major ones are pushing to wayland (only) sessions, so it might be a good idea to unrelate it in our config as well

**Review by patka-123 — APPROVED** [review]

**Pull request merged**
