### PR TITLE
ntopng: fix missing static assets

### PR DESCRIPTION
**Pull request by samhug**
Instead of building the `dist` make target in the derivation (requires npm and all that), we're using the upstream pre-built static assets. Upstream refers to these using a sub-module so we need to fetch that.

Without this patch the web UI loads the html, but 404s on all CSS and JS assets because the `$out/share/ntopng/httpdocs/dist` directory is empty

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bjornfor — COMMENTED** [review]
Looks like the patch is missing some bits? And please capitalize first word in commit message body: "instead" -> "Instead".

**Comment by bjornfor** [comment]
Your PR message explains the situation better than the commit message. Copy it?

**Comment by samhug** [comment]
> Your PR message explains the situation better than the commit message. Copy it?

I've updated the commit message to match the PR


> Looks like the patch is missing some bits?

Unsure what the missing bits are unless this was referring to the commit message also. Fetching sub-modules and then updating the source hash to match was really the only change needed.

**Comment by bjornfor** [comment]
> I've updated the commit message to match the PR

Thanks!

> > Looks like the patch is missing some bits?
> 
> Unsure what the missing bits are unless this was referring to the commit message also. Fetching sub-modules and then updating the source hash to match was really the only change needed.

Ok, thanks for clearing that up. (Note to self: it's a bad idea to look at PRs on phone.)

**Review by bjornfor — APPROVED** [review]

**Comment by samhug** [comment]
Thanks for reviewing the PR!

**Pull request merged**
