### PR TITLE
boost17x: 1.77 -> 1.78

### PR DESCRIPTION
**Pull request by TheBenCollins**
###### Description of changes

Added the December 2021 release of Boost, 1.78.0. This PR not only adds a new package, `pkgs.boost178`, but also moves the indirect package `pkgs.boost17x` to point to the new library. This later change is more substantive as there are many other derivations that depend on this meta-package.

###### Things done

- Built on platform(s)
  - [ x ] x86_64-linux
I ran `nix-build -A pkgs.boost178 .` from the local clone of nixpkgs and got a proper result.

I was not able to run `nixpkgs-review` in a reasonable amount of time (was ongoing for many hours) so this check is left undone.

### CODE REVIEW

**Comment by ajs124** [comment]
Thanks for your contribution.
Some notes: This should go to staging, because it rebuilds >5k packages. Also, the commit messages don't follow CONTRIBUTING.md, I think.

For how to change the target branch to staging _without spamming a bunch of people_, maybe check #166472 or CONTRIBUTING.md, once it's merged.

**Comment by TheBenCollins** [comment]
@ajs124 I rebased onto staging as was requested. (I followed the directions in https://github.com/NixOS/nixpkgs/pull/166472). Let me know if there is anything else to work out.

**Comment by ajs124** [comment]
Thanks! The commit messages should follow the pattern [outlined here](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes). I know it's kind of pedantic, but it makes commit logs easier to read IMO.

**Comment by dotlambda** [comment]
superseded by #175694

**Pull request closed without merging**
