### PR TITLE
simp_le: 0.9.0 -> 0.14.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://github.com/zenhack/simp_le#0140

(intermediate versions are listed below)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Rudimentary testing only so far, and FWIW using acme 0.34.2, FWIW ( #61203 )

Should confirm NixOS test (and that the test uses this :P),
may confirm on live deployment but no timetable on that.

---

### CODE REVIEW

**Comment by gebner** [comment]
This fails on ofborg.  You should update acme as well.

**Comment by dtzWill** [comment]
I have, see the mentioned PR ( https://github.com/NixOS/nixpkgs/pull/61203 ).

I'll pull those in here as well for your testing convenience, will push it shortly after re-checking :).

**Comment by dtzWill** [comment]
Oh, if it's not clear "acme" is built from subdirectory of the certbot source.  Which might confuse things.  Anyway i'd like to see confirmation from borg the stack works as well so that plan is still on :+1:.

**Comment by dtzWill** [comment]
Oh, if it's not clear "acme" is built from subdirectory of the certbot source.  Which might confuse things.  Anyway i'd like to see confirmation from borg the stack works as well so that plan is still on :+1:.


@GrahamcOfBorg build simp_le
@GrahamcOfBorg test acme

**Comment by Lassulus** [comment]
whats the status on this one?

**Comment by dtzWill** [comment]
I think I was concerned about the NixOS test failure (`tests.acme`), but I haven't investigated at all.

**Comment by JakeStanger** [comment]
The current version of `simp_le` is now returning 403 errors from LetsEncrypt with `security.acme.certs` and `enableACME` (nginx), so updating this is a matter of urgency.

```json
{
  "type": "urn:acme:error:unauthorized",
  "detail": "Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.",
  "status": 403
}
```

**Comment by jahkeup** [comment]
To add to the sense of urgency @JakeStanger noted (for bumping to `0.15.0`) the ACMEv1 API is due to be shuttered at the end of the month (October 31, 2019) per their brownout schedule: https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/3

I bumped the dependency (both `certbot`/`acme` & `simp_le-client`) myself in an overlay in attempt to seamlessly support the move to the v2 API, but it seems the `security.acme` module implementation may need some changes to make the move possible - I *think* there's additional flags needed though I'm not familiar enough with the specific tool to say for certain.

**Comment by JakeStanger** [comment]
As a quick workaround for anybody who needs SSL and stumbles on this at the moment, you can use `certbot certonly` to generate a certificate and then move the fullchain and privkey into the acme folder.

**Comment by fpletz** [comment]
Closing in favour of #71291.

**Pull request closed without merging**
