### PR TITLE
Elm: fix "Map.! when compiling with --debug"

### PR DESCRIPTION
**Pull request by miniBill**
###### Motivation for this change
The elm compiler has a long standing bug that may prevent compiling in debugging mode. The extremely slow pace of release means that this bug is open since months and will be open for many more. While it seems like there will be a 0.19.1, we have no idea on the timeframe, so we apply a proposed patch in the meantime.
This patch is a fix for [#1851](https://github.com/elm/compiler/issues/1851).

###### Things done
- [X] Regenerated `versions.dat` using [`update.sh`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/elm/update.sh)
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
Thanks for the PR. I have no push access to Nixpkgs but I'd like to provide a first review to help committers.

Could you provide some more information about the bug you want to fix, e.g. an upstream ticket? Could you also list under "Things done", how you regenerated that `versions.dat` file? Is the change of `versions.dat` a requirement for fixing the bug or could it be left out to be applied later with a version bump of `elm`?

I noticed that neither of the two proposed patches are merged upstream yet. Personally I'd have a better feeling if they would be. Any chance that happens soon?

Also: @GrahamcOfBorg build elmPackages.elm

**Comment by miniBill** [comment]
> Thanks for the PR. I have no push access to Nixpkgs but I'd like to provide a first review to help committers.
Thank you very much =)
> 
> Could you provide some more information about the bug you want to fix, e.g. an upstream ticket? Could you also list under "Things done", how you regenerated that `versions.dat` file? Is the change of `versions.dat` a requirement for fixing the bug or could it be left out to be applied later with a version bump of `elm`?
Added the info to "Things done". I've used the provided script from this repo, to be completely honest I'm not sure whether updating it is required and what may happen if we don't update it (I fear heisenbugs).
> 
> I noticed that neither of the two proposed patches are merged upstream yet. Personally I'd have a better feeling if they would be. Any chance that happens soon?
I'd say that the patches will probably never be merged upstream, as the code was reworked [in a different way](https://github.com/elm/compiler/commit/af2ea2b5baf6e47dcccca4385f6a773a981c6df2), but there is [a fork](https://github.com/CurrySoftware/compiler) that has actually included this.
This is one of the most annoying bugs, as it's impossible to work around.
> 
> Also:
> @GrahamcOfBorg build elmPackages.elm

**Comment by miniBill** [comment]
@GrahamcOfBorg build elmPackages.elm

**Comment by domenkozar** [comment]
Closing as we're waiting on Elm 0.19.1 alpha https://github.com/elm/compiler/pull/1850#issuecomment-509327575

**Pull request closed without merging**
