### PR TITLE
update alsa lib, plugins and utils 

### PR DESCRIPTION
**Pull request by magnetophon**
###### Motivation for this change
WARNING: mass rebuild!

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
> WARNING: mass rebuild!

Could you rebase this on staging.

**Comment by magnetophon** [comment]
@FRidh how do I rebase on staging?

**Comment by FRidh** [comment]
I guess in this case its easiest to checkout staging, then cherry-pick your commits, and force push to this branch.

**Comment by FRidh** [comment]
otherwise something like `git rebase --onto upstream/staging upstream/master magnetophon/alsa`

**Comment by magnetophon** [comment]
@FRidh erm, not sure if I did that right...

**Comment by FRidh** [comment]
yep, it is good now.

**Pull request merged**
