### PR TITLE
Python packages updates

### PR DESCRIPTION
**Pull request by teh**
###### Motivation for this change

Fixes for zero hydra failures.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teh** [comment]
Apologies for the automatic "review requests" for everyone but @FRidh - forgot to rebase.

**Comment by globin** [comment]
Xarray patch seems to have the wrong hash and bokeh tests are failing

**Comment by teh** [comment]
@globin as just discussed IRL I can't reproduce either. Just did another `rebase/force-push`. Would you mind copy-pasting the error you are seeing?

**Comment by FRidh** [comment]
I've stopped using fetchpatch because of hash issues. What is actually the correct way to determine a hash for fetchpatch?

**Comment by teh** [comment]
@FRidh I can always download the patch but I was a bit nervous about licensing issues. I.e. what license applies to our code if we include code from other projects?

**Comment by FRidh** [comment]
@teh you can just use fetchurl

**Comment by vcunat** [comment]
> I've stopped using fetchpatch because of hash issues. What is actually the correct way to determine a hash for fetchpatch?

I don't think there's a way except to try running it with some incorrect hash.  (Not nice, yes.)  Dynamically generated patches like from github or cgit used to change in insignificant parts over time, and the normalization in `fetchpatch` helped that (that's why it was created).

**Comment by FRidh** [comment]
Its also in 17.09, see 407b8246bed950432ba21d3d5a468043dd830e6a

**Comment by copumpkin** [comment]
> I don't think there's a way except to try running it with some incorrect hash. (Not nice, yes.) 

To be fair, that's how I do almost all of my hashes for Nix, despite the availability of `nix-prefetch*`

**Pull request merged**
