### PR TITLE
rust: Fix for legacy fetch cargo

### PR DESCRIPTION
**Pull request by bhipple**
See inline comment and #79975 for details.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bhipple** [comment]
Building a package with a custom hook on the legacy fetcher, a "well behaved" package on the legacy fetcher, and a package on the new fetcher, respectively.

@GrahamcOfBorg build spotifyd ripgrep hexdino

**Comment by veprbl** [comment]
Actually, this could go to master.

**Comment by marsam** [comment]
@GrahamcOfBorg build nushell

**Review by Ma27 — APPROVED** [review]

**Comment by jonringer** [comment]
I would also be fine with targeting master

**Comment by bhipple** [comment]
Re-targeted the PR and rebased to master.

**Comment by bhipple** [comment]
@GrahamcOfBorg build ripgrep hexdino nushell

**Review by jonringer — APPROVED** [review]
LGTM

shouldn't affect most packages

**Comment by bhipple** [comment]
Yeah, I've searched through Hydra and sent pre-emptive upgrade PRs to fix the broken pkgs, so this is less urgent, but should still be merged regardless.  I currently have it targeting master but LMK if I should re-rebase it back to staging.

**Review by jonringer — APPROVED** [review]
diff LGTM

as far as i can tell, failures all fail on master
```
[276 built (34 failed), 521 copied (28991.8 MiB), 3074.0 MiB DL]
error: build of '/nix/store/hkksv82z4jib341jzzldjq87rypx5dra-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/80153
44 package failed to build:
icedtea_web amp b3sum bepasty bitwarden_rs-mysql btrfs-dedupe cargo-geiger ethabi firefox firefox-esr firefox-esr-68-unwrapped firefox-unwrapped firefox-wayland fluidasserts gitAndTools.git-dit gnvim heatseeker ion leftwm licensor mozplugger parinfer-rust parity python37Packages.aplpy python37Packages.arviz python37Packages.dask-jobqueue python37Packages.datashader python37Packages.intake python37Packages.optuna python37Packages.rl-coach python37Packages.streamz python37Packages.sunpy python38Packages.aplpy python38Packages.arviz python38Packages.dask-jobqueue python38Packages.datashader python38Packages.intake python38Packages.optuna python38Packages.rl-coach python38Packages.streamz sit slimerjs vector whitebox-tools

258 package built:
alacritty amber async bandwhich bat bitwarden_rs bitwarden_rs-postgresql boringtun bukubrow cargo-about cargo-asm cargo-audit cargo-bloat cargo-deb cargo-deps cargo-edit cargo-expand cargo-flamegraph cargo-fuzz cargo-generate cargo-graph cargo-inspect cargo-license cargo-make cargo-outdated cargo-raze cargo-release cargo-sweep cargo-udeps cargo-watch cargo-web cargo-xbuild chit click clog-cli cloudflare-wrangler cntr coloursum contrast crosvm diesel-cli diffr diskus du-dust dua dwm-status eidolon elan emplace eva evcxr exa fd ffsend findomain fractal fselect geckodriver gifski gir-rs git-backup git-series gitAndTools.delta gitAndTools.git-absorb gitAndTools.git-codeowners gitAndTools.git-gone gitAndTools.git-ignore gitAndTools.git-interactive-rebase-tool gleam gnirehtet gnome-podcasts gnvim-unwrapped zola hexyl httplz hydra-cli hyperfine i3status-rust intecture-agent intecture-auth intecture-cli ja2-stracciatella journaldriver just jwt-cli kak-lsp khal loc loop lorri lsd maturin mcfly mdbook mdcat miniserve mq-cli ncspot newsboat nix-index nixdoc nixpkgs-fmt nushell onefetch oxipng panopticon parallel-rust parity-beta pastel pax-rs pazi peek pijul powerline-rs procs prometheus-wireguard-exporter pueue python27Packages.bokeh python27Packages.colorcet python27Packages.holoviews python27Packages.hvplot python27Packages.nbsmoke python27Packages.panel python27Packages.robotframework-selenium2library python27Packages.robotframework-seleniumlibrary python27Packages.runway-python python27Packages.selenium python27Packages.splinter python37Packages.bokeh python37Packages.caffe python37Packages.colorcet python37Packages.dask python37Packages.dask-glm python37Packages.dask-image python37Packages.dask-ml python37Packages.dask-mpi python37Packages.dask-xgboost python37Packages.distributed python37Packages.glymur python37Packages.holoviews python37Packages.hvplot python37Packages.image-match python37Packages.imagecorruptions python37Packages.imgaug python37Packages.nbsmoke python37Packages.panel python37Packages.pims python37Packages.pyfftw python37Packages.robotframework-selenium2library python37Packages.robotframework-seleniumlibrary python37Packages.runway-python python37Packages.scikitimage python37Packages.selenium sequoia python37Packages.splinter python37Packages.stumpy python37Packages.stytra python38Packages.bokeh python38Packages.caffe python38Packages.colorcet python38Packages.dask python38Packages.dask-glm python38Packages.dask-image python38Packages.dask-ml python38Packages.dask-mpi python38Packages.dask-xgboost python38Packages.distributed python38Packages.glymur python38Packages.holoviews python38Packages.hvplot python38Packages.image-match python38Packages.imagecorruptions python38Packages.imgaug python38Packages.nbsmoke python38Packages.panel python38Packages.pims python38Packages.pyfftw python38Packages.robotframework-selenium2library python38Packages.robotframework-seleniumlibrary python38Packages.runway-python python38Packages.scikitimage python38Packages.selenium python38Packages.sequoia python38Packages.splinter python38Packages.stytra rage railcar rav1e rdedup rink ripasso-cursive ripgrep-all rnix-lsp routinator rq rsclock ruplacer rust-bindgen rust-cbindgen rustracer rustracerd rustup rx scaff sccache sd searx shadowenv shadowsocks-rust shell-hist shotgun silicon skim starship svd2rust svgbob svgcleaner synapse-bt system-syzygy taizen tdns-cli tealdeer tectonic tensorman termplay texlab thunderbird tiny todiff topgrade tox-node unpfs uq uutils-coreutils vdirsyncer vimPlugins.LanguageClient-neovim vimPlugins.YouCompleteMe vimPlugins.skim viu vivid void wasm-bindgen-cli wasm-gc wasm-pack wasmer wasmtime watchexec webmetro websocat wishbone-tool wmfocus xidlehook xprite-editor xsv xv ycmd ytop zcash
```

**Pull request merged**
