### PR TITLE
brogue: fix crash by stackprotector hardening

### PR DESCRIPTION
**Pull request by Profpatsch**
- [x] NixOS
- [ ] OS X
- [ ] Linux
- [x] Tested execution of all binary files (usually in `./result/bin/`)

### CODE REVIEW

**Comment by globin** [comment]
Could you add a comment to clarify that this causes a crash and is a potential security vulnerability and not an incompatibility with the flag?

**Comment by Profpatsch** [comment]
@globin done

**Comment by fpletz** [comment]
This package also needed fortify hardening disabled to run correctly. Backported to 16.09.

**Comment by svenkeidel** [comment]
I just tested your changes and it seams to work fine. I could not reproduce the crash though. Anyway, I am ok with this change.

**Pull request merged**
