### PR TITLE
qscintilla: revert bump to fix the build

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

This reverts the bump of `qscintilla` performed in #37330 as it actively breaks the qt5-darwin support added in 734323872a7271625e4948d9732f8ad0d59e9332.

Furthermore #37330 (namely 8ee6a03a3e75c6aaf4d7cf53bd6ffc6892d89950) **never** worked when building the `qt4` variant `nix-build -A qscintilla`.

The original bump broke the following packages transitively:

* *pkgs.tora*
* *pkgs.sqlitebrowser*
* *pkgs.sonic-pi*
* and many more...

As I don't have the required resources to actively test/maintain the darwin compatibility of `qscintilla` and the `qt4` variant **never** worked since the bump, I'd vote to revert the change for now and perform a bump with tested `qt4` and `darwin` derivations.

/cc @ryantm @mpickering @peterhoeg 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantm** [comment]
@Ma27 Added issue to blacklist this for nixpkgs-update

**Comment by Ma27** [comment]
(short side note, I'm currently running `nox-review` to reduce the risk of breakage, but that may take some time)

> Added issue to blacklist this for nixpkgs-update

This is definetely an appropriate measure to do for now I guess, however I think that the *core* issue behind the breakage we experience is a different one:

several packages in `nixpkgs` live in the "main" set (e.g. `nixos.foo`), but have specialized derivations in meta pages (e.g. `nixos.metapackage.foo`).

One example is `qscintilla` where the `qt5` derivation lives in `nixos.libsForQt5.qscintilla`, but the `qt4` derivation (which was obviously not tested) lives in `nixos.qscintilla`. Another specimen would be `dlib` with `nixos.dlib` and `nixos.pythonPackages.dlib` which use the same source. Unfortunately I don't know too much about how `nixpkgs-update` works ATM, but I guess that we'll have to enhance the testing logic a bit as this is definetely an avoidable issue :-)

**Comment by Ma27** [comment]
`nox-review` wasn't 100% successfully as it as it broke because of the `dmd` build which is currently broken on master (https://hydra.nixos.org/build/72698700)

**Comment by peterhoeg** [comment]
Instead of reverting, I would much rather that we keep a separate ```qscintilla-qt4``` around for 2.9 (several pyqt4 programs depend on qscintilla) and then keep the move to 2.10 around for qt5.

**Comment by lukeadams** [comment]
@Ma27 [There's a version bump (to 2.10.4) which fixes the qt4 variant](https://www.riverbankcomputing.com/news/qscintilla-2104)

**Comment by Ma27** [comment]
@peterhoeg I'd actually agree with you, *however* `libsForQt5.qscintilla` never worked with version 2.10: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.libsForQt5.qscintilla.x86_64-linux

The main reason for this is that in 3391006fd584fadb89fac191407c08a87d307f11 was added a darwin compliancy patch from the homebrew repository which fixes the XCode build of `qscintilla`.
`x86_64-linux` was broken as well as the patch was applied for *each* qt5 build (which I fixed in this PR as well).

As you can see on the `nox-review` output I posted above this will fix *several* packages on `master`. We should at least merge https://github.com/NixOS/nixpkgs/pull/39860/commits/be153f6323599a0128d384471c42e1f10d0a1f00 to fix the Linux builds and maybe even the revert (and let somebody try another bump in case he's able to test (and optionally rebase) the Darwin patch).

**Comment by peterhoeg** [comment]
Thanks for doing this - you are absolutely right.

**Pull request merged**
