### PR TITLE
haskell.packages: deal with evaluation fall out of most recent stackage update

### PR DESCRIPTION
**Pull request by sternenseemann**
random 1.2.0 has a new test suite with a lot of dependencies. Among
other packages it depends on doctest which depends on syb which depends
on tasty which depends on optparse-applicative which depends on
QuickCheck which depends on -- you guessed it -- random!

The cycle could be broken at any point of course, I've disabled the
tests on random here because it has seen the change that causes all
of this. However, we may also want to consider doing this for
optparse-applicative instead, since random seems like a more critical
package to run the tests for possibly? Not sure, looking for feedback.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
I feel like I had encountered these issues before. Can you tell how the loop got introduced?

**Comment by sternenseemann** [comment]
> I feel like I had encountered these issues before. Can you tell how the loop got introduced?

As outlined in the commit message:

random 1.2.0 tests -> doctest -> syb tests -> tasty -> optparse-applicative tests -> QuickCheck -> random 1.2.0

We actually had that in `cabal-install` where we already used random 1.2.0 (see 5110223f4ae72b15d2a4ffa14ea1f1594b8a2351) and we used the `dontCheck` approach as well there.

**Comment by cdepillabout** [comment]
Great, this looks like it gets everything evaluating again with `nix-env --query --available --out-path --file ./. --show-trace`.  Please feel free to merge this in.

**Comment by maralorn** [comment]
> > I feel like I had encountered these issues before. Can you tell how the loop got introduced?
> 
> As outlined in the commit message:
> 
> random 1.2.0 tests -> doctest -> syb tests -> tasty -> optparse-applicative tests -> QuickCheck -> random 1.2.0
> 
> We actually had that in `cabal-install` where we already used random 1.2.0 (see [5110223](https://github.com/NixOS/nixpkgs/commit/5110223f4ae72b15d2a4ffa14ea1f1594b8a2351)) and we used the `dontCheck` approach as well there.

What I meant is: Is this a new problem or did older random versions also have this loop and how did we solve this then? But it’s not that important …

**Comment by sternenseemann** [comment]
This is a new problem due to the update to random 1.2.0. Previously randoms test suite only depended on base.

**Pull request merged**
