### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by maralorn**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

---

This is the follow-up to #172982. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by cdepillabout** [comment]
It looks like `spago` is now broken.  It appears that there is a new version of one of its dependencies: `bower-json-1.1.0.0`.  `bower-json-1.1.0.0` only works with `>= aeson-2.0`.  But I believe `spago` only works with `< aeson-2.0`.  There are two ways I can see to fix this:

1. Generate `bower-json_1_0_0_1` (which works with `< aeson-2.0`) here in Nixpkgs and override `spago` to use it.
2. Send a PR to `spago` getting it compatible with `bower-json-1.1.0.0` (and `>= aeson-2.0`?) and then apply that patch here in Nixpkgs.

I'm not sure I'll have time to do either of these this week, but if someone is interested in looking at this, I'd happy to review a PR.

If no one takes a look at this over the next week or so, feel free to mark `spago` and `haskellPackages.spago` broken.

**Comment by maralorn** [comment]
@cdepillabout Ah, didn‘t see your message in time. But I just did 1.

**Comment by maralorn** [comment]
@roberth hercules-ci-agent has a build failure, which you probably understand better than I do: https://hydra.nixos.org/build/177779194/nixlog/1/tail

**Comment by cdepillabout** [comment]
@maralorn Oh great, thanks a lot!  That works for me.

**Comment by maralorn** [comment]
I have just triggered a set rebuild by merging #171685 and #172365.

See https://github.com/cdepillabout/nix-haskell-updates-status/tree/0097eb11d54c146a4976c9c476be3d732d656285 for the state of the branch before the rebuild.

**Comment by vcunat** [comment]
Is this meant for 22.05?  If not, I'd certainly cancel the builds now and postpone that after the current staging-next is merged in included in this.

**Comment by maralorn** [comment]
No, I was not planning to get this into 22.05. I guess I am fine with canceling this for a few days.

**Pull request merged**
