### PR TITLE
root: 6.24.06 -> 6.26.04

### PR DESCRIPTION
**Pull request by veprbl**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
cc @ShamrockLee @yipengsun

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 182037` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>hepmc3</li>
    <li>python310Packages.hepmc3</li>
    <li>python39Packages.hepmc3</li>
    <li>root</li>
    <li>xfitter</li>
    <li>yoda-with-root</li>
  </ul>
</details>

**Comment by yipengsun** [comment]
So we need to patch `llvm9` (which means re-compile it I guess) because this `PIE` flag is backported by ROOT developer?

Is this flag information only (mostly)? I'm just wondering if we want to jump to ROOT 6.26 in the future, we can just use the official `llvm9` w/o this patch to speed up compilation :-)

**Comment by yipengsun** [comment]
I'm looking at the original pull request for `llvm`: https://reviews.llvm.org/D80871

Not sure if the `llvm/tools/llvm-readobj/ELFDumper.cpp` should also be patched? Maybe `root` itself never uses this tool so the change is not carried over?

**Comment by veprbl** [comment]
> So we need to patch `llvm9` (which means re-compile it I guess) because this `PIE` flag is backported by ROOT developer?
> 
> Is this flag information only (mostly)? I'm just wondering if we want to jump to ROOT 6.26 (in the research group I belong to) in the future, we can just use the official `llvm9` w/o this patch to speed up compilation :-)

I'm not sure. It was originally suggested in #169579 and it does fix the compilation. You should be able to get the overridden version of `llvm_9` from cache.nixos.org same way as before once this is merged.

> I'm looking at the original pull request for `llvm`: https://reviews.llvm.org/D80871
> 
> Not sure if the `llvm/tools/llvm-readobj/ELFDumper.cpp` should also be patched? Maybe `root` itself never uses this tool so the change is not carried over?

Seems to be not needed. I assume that llvm-tools are not used by ROOT.

**Comment by yipengsun** [comment]
6 packages built:
hepmc3 python310Packages.hepmc3 python39Packages.hepmc3 root xfitter yoda-with-root

Build fine on Linux too.

**Comment by ShamrockLee** [comment]
Sorry for the delay in #169579 . I was busy working on something else.

The work involves fetching the patch from root-project/root and patch it to the official llvm source code, which requires manual specification of the destination file.

I'll try fetchPatch again this weekend. It would also be great if anyone is willing to help.

**Comment by veprbl** [comment]
@ShamrockLee If this works, you can rebase your change and focus it on just the path hardcoding.

**Pull request merged**
