### PR TITLE
lemmy: 0.18.2 -> 0.18.3

### LINKED ISSUE #246620: Update request: lemmy-{server,ui} 0.18.2 → 0.18.3
- Package name: lemmy-server and lemmy-ui
- Latest released version: 0.18.3

- Current version on the unstable channel: 0.18.2
- Current version on the stable/release channel: 0.17.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@happysalada @billewanick @adisbladis

https://github.com/LemmyNet/lemmy/releases/tag/0.18.3
https://github.com/LemmyNet/lemmy/blob/main/RELEASES.md

This release brings major performance optimizations and security improvements.

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by happysalada**
## Description of changes

update of lemmy to latest closes #246620

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
@adisbladis for testing.

**Review by billewanick — APPROVED** [review]

**Comment by billewanick** [comment]
Result of `nixpkgs-review pr 246940` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>lemmy-server</li>
    <li>lemmy-ui</li>
  </ul>
</details>

**Comment by billewanick** [comment]
Can't believe I didn't know about `nix-update -u lemmy-server`!

**Comment by arjan-s** [comment]
This is now running well on my personal server. Thanks!

**Comment by adisbladis** [comment]
> @adisbladis for testing.

I'm traveling right now so I can't test but changes LGTM.

**Pull request merged**
