### PR TITLE
esphome: 1.14.4 -> 1.14.5

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

> esphome: Fix ESP32 interrupt enable/disable switched (cherry-picked)

https://github.com/esphome/esphome/releases/tag/v1.14.5

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
@mweinelt Please test it with the commit I added.

**Comment by mweinelt** [comment]
Upgraded some of my esphome devices to 1.14.5. LGTM.

```
[16:11:50][D][api.connection:583]: Client 'Home Assistant 0.112.0 (172.23.42.122)' connected successfully!
[16:12:28][D][bme280.sensor:197]: Got temperature=26.0°C pressure=996.8hPa humidity=36.7%
[16:12:28][D][sensor:092]: '0ea3ab BME280 Temperature': Sending state 25.99000 °C with 1 decimals of accuracy
[16:12:28][D][sensor:092]: '0ea3ab BME280 Pressure': Sending state 996.77704 hPa with 1 decimals of accuracy
[16:12:28][D][sensor:092]: '0ea3ab BME280 Humidity': Sending state 36.69434 % with 1 decimals of accuracy
```

**Comment by mweinelt** [comment]
Oh, it seems to be missing click just now?!

```
Traceback (most recent call last):
  File "/nix/store/0y569sgcc10lhmd9b7fnzg0pxpbzdwfv-esphome-1.14.5/bin/.esphome-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/0y569sgcc10lhmd9b7fnzg0pxpbzdwfv-esphome-1.14.5/lib/python3.8/site-packages/esphome/__main__.py", line 566, in main
    return run_esphome(sys.argv)
  File "/nix/store/0y569sgcc10lhmd9b7fnzg0pxpbzdwfv-esphome-1.14.5/lib/python3.8/site-packages/esphome/__main__.py", line 535, in run_esphome
    return PRE_CONFIG_ACTIONS[args.command](args)
  File "/nix/store/0y569sgcc10lhmd9b7fnzg0pxpbzdwfv-esphome-1.14.5/lib/python3.8/site-packages/esphome/__main__.py", line 369, in command_update_all
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by mweinelt** [comment]
Upstream-Issue opened at https://github.com/esphome/issues/issues/1324.

**Comment by mweinelt** [comment]
Upstream added click to their requirements and I think we're good to go here.

**Pull request merged**
