### PR TITLE
nixos/ebusd: clean up module

### PR DESCRIPTION
**Pull request by h7x4**
## Description of changes

This PR only cleans up the code of the `ebusd` module, with the intention of not changing the outcome.

In general, I've cleaned up a bunch of descriptions, inlined a few single element lists, removed some extra space. The two big changes are the automatic generation of the `services.ebusd.logs` options, and the use of `cli.toGNUCommandLineShell` for constructing the string of arguments. The latter has also been moved from the top of the file, closer to the `ExecStart` where it is used.

I've tested that the code evalutates manually, but it would be nice if this had a basic test. Not sure how easy that would be to make though, considering it's a hardware related program.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by nathan-gs — APPROVED** [review]

**Comment by nathan-gs** [comment]
Looks good @h7x4, thanks for the improvements!

**Comment by nathan-gs** [comment]
@h7x4 a small improvement would be to add a `package` option

**Comment by h7x4** [comment]
@nathan-gs Done!

**Review by nathan-gs — APPROVED** [review]

**Comment by nathan-gs** [comment]
@globin @happysalada would you be willing to review & merge this one as well. Thx

**Comment by happysalada** [comment]
I merged the other one first, hopefully the merge conflict should be minimal. Please ping me when youve had a chance to rebase

**Comment by nathan-gs** [comment]
@h7x4 care to review the merge conflict and resubmit?

**Comment by bobrippling** [comment]
@nathan-gs @h7x4 I'm happy to sort the merge conflict to help this along, let me know

**Comment by nathan-gs** [comment]
> @nathan-gs @h7x4 I'm happy to sort the merge conflict to help this along, let me know

@bobrippling would be great!

**Comment by bobrippling** [comment]
> @bobrippling would be great!

Cool - done, pushed to `nixos-module-cleanup-ebusd` in [my fork](https://github.com/bobrippling/nixpkgs/), commit 7f6f6ffb93c0bad5e6248c08d4e801de7069a75f

You're welcome to fetch from there, or I can open a similar PR to this one

**Comment by nathan-gs** [comment]
@bobrippling let's create a new PR, we will close this one.

**Comment by bobrippling** [comment]
@nathan-gs thanks, done via #308500

**Comment by nathan-gs** [comment]
Closing, new PR in #308500

**Pull request closed without merging**
