### PR TITLE
matplotlib: 2.2.3 -> 3.0.0

### PR DESCRIPTION
**Pull request by smaret**
###### Motivation for this change

Update matplotlib to the latest upstream version (3.0.0). This version does not support Python 2. 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by smaret** [comment]
Should we keep the old version of `matplotlib` in `nixpkgs` for Python2 users?

**Comment by smaret** [comment]
CC'ing the package maintainer @lovek323

**Comment by FRidh** [comment]
Yes, we need to keep a version for Python 2.

**Comment by smaret** [comment]
@GrahamcOfBorg build python36Packages.matplotlib

**Comment by smaret** [comment]
@GrahamcOfBorg build python27Packages.matplotlib

**Comment by FRidh** [comment]
Thanks. I've pushed 880fae6a084a66dae6d92dd5fe4416bd4eed4978 to master.

**Pull request closed without merging**
