### PR TITLE
ell, iwd: update

### PR DESCRIPTION
**Pull request by bbigras**
###### Motivation for this change

- ell: 0.35 -> 0.36
- iwd: 1.10 -> 1.11

> ver 0.36:
>	Fix issue with strict netlink attribute validation.
>	Fix issue with DUID generation for DHCPv6.
>	Add support for Address Conflict Detection.
>	Add support for PKCS#12 algorithms handling.
>	Add support for PKCS#12 key derivation algorithm.
>	Add support for RC2 and ARC4 cipher suites.

https://git.kernel.org/pub/scm/libs/ell/ell.git/tree/ChangeLog?h=0.36

> ver 1.11:
>	Add support for ACD client for static configuration.
>	Add support for intelligent scan of all frequencies.

https://git.kernel.org/pub/scm/network/wireless/iwd.git/tree/ChangeLog?h=1.11

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bbigras** [comment]
Result of `nixpkgs-review pr 110275` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>ell</li>
    <li>iwd</li>
    <li>modem-manager-gui</li>
    <li>ofono</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110275` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>ell</li>
<li>iwd</li>
<li>modem-manager-gui</li>
<li>ofono</li>
</ul>
</details>

**Comment by bbigras** [comment]
Thanks!

**Pull request merged**
