### PR TITLE
nixos/proxmox-image: Disable O_DIRECT to fix assert when writing to tmpfs

### PR DESCRIPTION
**Pull request by mped-oticon**
VMA is Proxmox's virtual machine image format that wraps QEMU images, augmenting these with proxmox-specific configuration file. proxmox-image.nix uses the VMA tool to create vma image files. The VMA tool exists as a patchset ontop of QEMU.

VMA writes its output with open() and O_DIRECT flag. O_DIRECT does not work on Linux tmpfs [1]. Thus:
$ vma create ~/output.vma ...  # works, assuming home isn't tmpfs. $ vma create /dev/shm/output.vma ...  # fails since /dev/shm is tmpfs Failure results in assert(*errp == NULL).

O_DIRECT is a cache performance hint.
But it currently blocks our usage of nixos-generate -f proxmox from Non-NixOS hosts and Docker.

The patch here simply removes O_DIRECT:
vma-writer.c later performs memalign due to O_DIRECT, but this is safe to do with or without O_DIRECT.
Ideally, this should be fixed in upstream Proxmox: Perhaps by falling back to open without O_DIRECT.

Another attempt to fix this SIGABRT is [2], which writes the vma file directory to $out/ folder -- however that may still be tmpfs mounted which it is in our case.

[1] https://lore.kernel.org/lkml/45A29EC2.8020502@tmr.com/t/
[2] https://github.com/NixOS/nixpkgs/pull/224282

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Please open an issue upstream (QEMU or whatever) and ideally link it here, they should try O_DIRECT and if they have EINVAL, they should not go to O_DIRECT.
But the situation is suboptimal.

**Review by RaitoBezarius — APPROVED** [review]
LGTM other than this

**Comment by mped-oticon** [comment]
Thanks. Bug filed: https://bugzilla.proxmox.com/show_bug.cgi?id=4710

**Comment by RaitoBezarius** [comment]
Please add the link to the issue tracker as a comment above your inline patch and after this, we can merge.

**Comment by RaitoBezarius** [comment]
Final thing (sorry I didn't have much sleep those last days), can you reformat your commits (and the PR title) according to the CONTRIBUTING guide? `nixos/virtualisation/proxmox-image: disable O_DIRECT to fix assert errors` something along those lines with a proper comment message explaining the context.

**Comment by mped-oticon** [comment]
> (sorry I didn't have much sleep those last days), 

Me neither; newborn keeping me up.

> can you reformat your commits (and the PR title) 

`nixos/proxmox-image:` appears the be the default prefix headline according to git log.

Let me know if this is OK.

**Pull request merged**
