### PR TITLE
lima: 0.5.0 -> 0.6.0

### PR DESCRIPTION
**Pull request by voanhduy1512**
###### Motivation for this change

Update lima to 0.6.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
@voanhduy1512 Did you receive an invite to join the NixOS github org? You should have been sent one automatically after https://github.com/NixOS/nixpkgs/pull/128052 was merged.

**Comment by voanhduy1512** [comment]
I've just found out the email thanks to your reply but unfortunately the invitation was expired

**Comment by zowoq** [comment]
>  invitation was expired

@NixOS/security Could someone send another invite please?

**Comment by voanhduy1512** [comment]
@zowoq Just checking, am i expected to receive an invite email?

**Comment by zowoq** [comment]
> > invitation was expired
> 
> @NixOS/security Could someone send another invite please?

Ping @domenkozar @grahamc

**Comment by zowoq** [comment]
@zimbatm Can you send another invite to the org please?

**Comment by zimbatm** [comment]
@voanhduy1512 check your mails

**Comment by zowoq** [comment]
Thanks @zimbatm

**Comment by voanhduy1512** [comment]
Got it, thanks @zimbatm @zowoq

**Pull request merged**
