### PR TITLE
vimPlugins.nvim-treesitter: workaround for duplicate grammars

### PR DESCRIPTION
**Pull request by PerchunPak**
## Description of changes
See https://github.com/NixOS/nixpkgs/pull/339076#issuecomment-2329585080

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@BirdeeHub, could you please try rebuilding your system on this PR and see if the issue persists? I didn't test this.

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PerchunPak** [comment]
See also https://github.com/NixOS/nixpkgs/pull/319233#issuecomment-2308398048

Result of `nixpkgs-review pr 339589` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by BirdeeHub** [comment]
Im completely fine with this solution for this purpose for the reasons stated [in my most recent comment on the other thread](https://github.com/NixOS/nixpkgs/pull/339076#issuecomment-2329672560)

**Comment by BirdeeHub** [comment]
I forgot to mention, yes, I did rebuild agaisnt the branch ```workaround-339076```. It does work.

 It also still works with the norg overlay active.

**Review by stephen-huan — APPROVED** [review]

**Review by BirdeeHub — APPROVED** [review]

**Review by fpletz — APPROVED** [review]

**Comment by fpletz** [comment]
Not sure what to do with the other PR but let's get this in as this seems to restore the previous behavior.

**Comment by pinpox** [comment]
I started getting this error messages when starting neovim after the last update:
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:35: Error executing lua: ...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:36: BufReadPost
 Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ....10.1/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for lan
guage 'nix': uv_dlopen: no error
stack traceback:
        [C]: in function '_ts_add_language'
        ....10.1/share/nvim/runtime/lua/vim/treesitter/language.lua:112: in function 'add'
        ...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
        ...wrapped-0.10.1/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'
        ...wrapped-0.10.1/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
        ...wrapped-0.10.1/share/nvim/runtime/lua/vim/treesitter.lua:416: in function 'start'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
        ...es/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
        ...es/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...es/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...es/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
        [C]: in function 'nvim_cmd'
        ...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:36: in function <...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        ...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:35: in function <...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        ...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:36: in function <...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        ...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:35: in function <...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:35: in function <...-neovim-unwrapped-0.10.1/share/nvim/runtime/filetype.lua:10>
```

Could this be related?

**Comment by BirdeeHub** [comment]
doesnt look like it. Looks more like:

https://github.com/NixOS/nixpkgs/issues/332580#issuecomment-2325364470

Try not lazy loading treesitter

**Comment by BirdeeHub** [comment]
The issue fixed by this PR was a build time issue, and it simply denies duplicates. I would be very surprised if this error came from this PR.

**Comment by pinpox** [comment]
Thanks for clarifying. it was indeed an error with leftover files in ~/.config/share. Solved!

**Pull request merged**
