### PR TITLE
haste-client: Init at 0.2.3

### PR DESCRIPTION
**Pull request by SCOTT-HAMILTON**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/86041

###### Things done
Packaged haste-client at release 0.2.3. 
This seems a bit unmaintained and a few warnings are given at runtime but it still works and it is quite useful to share code on IRC.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by evils** [comment]
while the warnings are annoying
it works for me, thanks

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 96536` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>haste-client</li>
</ul>
</details>

**Comment by ajs124** [comment]
The tarball job on unstable-small is [broken right now](https://hydra.nixos.org/build/135345997) and a git bisect points me to this PR.

**Comment by puckipedia** [comment]
I believe the issue is the use of the `bundlerEnv` as a propagated build input, which no other package does. I believe it should be replaced with a `bundlerApp` usage, which seems to be what @SCOTT-HAMILTON intended, without silently breaking a piece of infrastructure way higher up.

**Comment by SCOTT-HAMILTON** [comment]
Fixing it, BTW haste servers seems to be dead right now.

**Comment by puckipedia** [comment]
Awesome, I'd suggest looking at https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/ruby.section.md#packaging-applications for the best way to solve it :p

**Comment by SuperSandro2000** [comment]
> Fixing it, BTW haste servers seems to be dead right now.

maybe I did not get rate limited but it is down. Interesting.

**Pull request merged**
