### PR TITLE
pythonPackages.can: 3.1.0 -> 3.3.1

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

Update Python package `can`. Python 2.7 doesn't seem to work anymore and the support is being dropped upstream anyway, so I dropped support here already. More info: https://github.com/hardbyte/python-can/issues/699

I also added a new dependency and switched from GitHub source to PyPI source now that tests were added to the PyPI tarball.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jluttine** [comment]
Oh, wait, I can make it work on Python 2 by upgrading `hypothesis` package. Just a sec, I'll make some changes and push them.

**Comment by jluttine** [comment]
So, I needed to upgrade `hypothesis` package to make Python 2 work. Another Python package `XlsxWriter` also required this updated version of `hypothesis` in order for its update to work, so I just added all these three updates to this same PR. I'm now running nox review..

**Comment by jluttine** [comment]
cc: `python-can` maintainer @sorki

**Comment by FRidh** [comment]
hypothesis goes to staging and needs to be tested in a separate job

**Review by FRidh — CHANGES_REQUESTED** [review]
let's not bump hypothesis in this PR if we can avoid it

**Comment by jluttine** [comment]
@FRidh I guess one solution is to disable the failing tests for Python 2 temporarily for these two packages, and add a comment that the disabling can be removed once hypothesis has been upgraded. Would that be a good solution?

**Comment by jluttine** [comment]
@FRidh I now removed the need to update `hypothesis` by disabling tests for `python-can` under Python 2.7 with hypothesis version 4.7.3. I ran nox-review and everything passed.

**Pull request merged**
