### PR TITLE
Support journal gatewayd

### PR DESCRIPTION
**Pull request by nlewo**
###### Motivation for this change

Since ae896e0, Systemd is no longer compiled with the http gateway because of an incompatibility between Systemd and libmicrohttpd. However, because of some updates, it is now building fine!

I also enable this feature is the systemd test to ensure the option `services.journald.enableHttpGateway` is working as excepted.

Note i also want to backport this patch to 20.09.

cc @flokli

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nlewo** [comment]
@GrahamcOfBorg test systemd

**Comment by ajs124** [comment]
This should probably be optional, since we're going that way with #101886. Assuming that gets merged, but I don't see why it wouldn't.

**Comment by nlewo** [comment]
@ajs124 Thanks for the link. 
I started to discuss about this feature in the PR #101885 . 
I would however prefer to let this PR open because it's not improvement but a bug fix (the NixOS option `services.journald.enableHttpGateway` is currently broken).

**Comment by nlewo** [comment]
Hm, it's actually hard to apply the revert on staging because of merge conflicts. So, I don't think it's relevant to keep this PR open.
I will submit one to fix the option on 20.09 and continue the discussion in #101886.

**Pull request closed without merging**
