### PR TITLE
deisctl: init at 1.10.0

### PR DESCRIPTION
**Pull request by jgeerds**
I need the deis client for work but unfortunately I've no experience in Go projects. Would someone be so nice and help me with it? Should I use `go2nix` or `GoDep`?

The build finishes without errors but the output doesn't contain the `deisctl` binary.

Here is the official documentation:
http://docs.deis.io/en/latest/installing_deis/install-deisctl/#building-from-source

CC: @lethalman

### CODE REVIEW

**Comment by lethalman** [comment]
`goPackages.deisctl.bin` then look into `result-bin`.

**Comment by geerds** [comment]
I'll try this in a few hours. Does it work for you?

**Comment by lethalman** [comment]
Yes.

**Comment by geerds** [comment]
Works for me as well. I've renamed the `client` binary to `deis`.

@lethalman Is it good enough for merging?

**Comment by lethalman** [comment]
@geerds you can merge :)

**Pull request merged**
