### PR TITLE
[21.05] linux_5_13: init at 5.13

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
partial backport of: #125082
backport of: #128502 #128567

(cherry picked from commit 367a53a82b0a3ffe6c1ea4261c22764129994669)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/128533

11 packages marked as broken and skipped:
linuxPackages_5_13.anbox linuxPackages_5_13.ixgbevf linuxPackages_5_13.lttng-modules linuxPackages_5_13.ndiswrapper linuxPackages_5_13.phc-intel linuxPackages_5_13.r8125 linuxPackages_5_13.rtl8723bs linuxPackages_5_13.sch_cake linuxPackages_5_13.tbs linuxPackages_5_13.zfs linuxPackages_5_13.zfsUnstable

13 packages failed to build:
linuxPackages_5_13.amdgpu-pro linuxPackages_5_13.evdi linuxPackages_5_13.mxu11x0 linuxPackages_5_13.nvidia_x11 linuxPackages_5_13.nvidia_x11_beta linuxPackages_5_13.nvidia_x11_legacy340 linuxPackages_5_13.nvidia_x11_legacy390 linuxPackages_5_13.nvidia_x11_vulkan_beta linuxPackages_5_13.openafs linuxPackages_5_13.openafs_1_9 linuxPackages_5_13.perf linuxPackages_5_13.tuxedo-keyboard linuxPackages_5_13.virtualboxGuestAdditions

61 packages built:
linuxPackages_5_13.acpi_call linuxPackages_5_13.akvcam linuxPackages_5_13.asus-wmi-sensors linuxPackages_5_13.batman_adv linuxPackages_5_13.bbswitch linuxPackages_5_13.bcc linuxPackages_5_13.bpftrace linuxPackages_5_13.broadcom_sta linuxPackages_5_13.can-isotp linuxPackages_5_13.chipsec linuxPackages_5_13.cpupower linuxPackages_5_13.cryptodev linuxPackages_5_13.ddcci-driver linuxPackages_5_13.digimend linuxPackages_5_13.dpdk linuxPackages_5_13.ena linuxPackages_5_13.facetimehd linuxPackages_5_13.fwts-efi-runtime linuxPackages_5_13.gcadapter-oc-kmod linuxPackages_5_13.hid-nintendo linuxPackages_5_13.hyperv-daemons linuxPackages_5_13.intel-speed-select linuxPackages_5_13.isgx linuxPackages_5_13.it87 linuxPackages_5_13.jool linuxPackages_5_13.kernel linuxPackages_5_13.mba6x_bl linuxPackages_5_13.mbp2018-bridge-drv linuxPackages_5_13.mwprocapture linuxPackages_5_13.netatop linuxPackages_5_13.nvidiabl linuxPackages_5_13.oci-seccomp-bpf-hook linuxPackages_5_13.openrazer linuxPackages_5_13.ply linuxPackages_5_13.r8168 linuxPackages_5_13.rtl8192eu linuxPackages_5_13.rtl8812au linuxPackages_5_13.rtl8814au linuxPackages_5_13.rtl8821au linuxPackages_5_13.rtl8821ce linuxPackages_5_13.rtl8821cu linuxPackages_5_13.rtl88x2bu linuxPackages_5_13.rtl88xxau-aircrack linuxPackages_5_13.rtlwifi_new linuxPackages_5_13.sysdig linuxPackages_5_13.system76 linuxPackages_5_13.system76-acpi linuxPackages_5_13.system76-io linuxPackages_5_13.systemtap linuxPackages_5_13.tmon linuxPackages_5_13.tp_smapi linuxPackages_5_13.turbostat linuxPackages_5_13.usbip linuxPackages_5_13.v4l2loopback linuxPackages_5_13.v86d linuxPackages_5_13.vendor-reset linuxPackages_5_13.vhba linuxPackages_5_13.virtualbox linuxPackages_5_13.x86_energy_perf_policy linuxPackages_5_13.xpadneo linuxPackages_5_13.zenpower
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128533` at 2b460dcd run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/f19bb1c023bf5dec31636223de6adaae">linuxPackages_5_13.anbox</a></li>
    <li><a href="https://gist.github.com/21c98146e5e14837865d1dbc794ca551">linuxPackages_5_13.evdi</a></li>
    <li><a href="https://gist.github.com/be7e1087c6f57ccbe1d410a202d5514a">linuxPackages_5_13.lttng-modules</a></li>
    <li><a href="https://gist.github.com/c8b4572f2cc9e423d42d4104e1be6090">linuxPackages_5_13.mwprocapture</a></li>
    <li><a href="https://gist.github.com/15938f6c31f861cb0c4be0def6272297">linuxPackages_5_13.mxu11x0</a></li>
    <li><a href="https://gist.github.com/757fec81cc0f9bf6246b14a8da4d11d3">linuxPackages_5_13.openafs</a> (linuxPackages_5_13.openafs_1_8)</li>
    <li><a href="https://gist.github.com/f39658e571c991c1915f8cf3ebb5d667">linuxPackages_5_13.openafs_1_9</a></li>
    <li><a href="https://gist.github.com/a02a74e5bc2d373e3c37c031ef79f755">linuxPackages_5_13.perf</a></li>
    <li><a href="https://gist.github.com/aeee0136bdcf196b0efc1c39bad692e0">linuxPackages_5_13.rtl8192eu</a></li>
    <li><a href="https://gist.github.com/70fd8725b5522c3ddf1b35e80f22a3f2">linuxPackages_5_13.rtl8723bs</a></li>
    <li><a href="https://gist.github.com/93997dc99bf2eca0ae34a9c834f7b6ae">linuxPackages_5_13.rtl8821ce</a></li>
    <li><a href="https://gist.github.com/6ac7bd4d2d8c300fc56fad9c8950299b">linuxPackages_5_13.sch_cake</a></li>
    <li><a href="https://gist.github.com/ba954af49859b4e1efbfeab6c2e69dc7">linuxPackages_5_13.tuxedo-keyboard</a></li>
  </ul>
</details>
<details>
  <summary>2 packages skipped due to time constraints:</summary>
  <ul>
    <li>linuxPackages_5_13.dpdk</li>
    <li>linuxPackages_5_13.zfsUnstable</li>
  </ul>
</details>
<details>
  <summary>36 packages built successfully:</summary>
  <ul>
    <li>linuxPackages_5_13.acpi_call</li>
    <li>linuxPackages_5_13.akvcam</li>
    <li>linuxPackages_5_13.batman_adv</li>
    <li>linuxPackages_5_13.bcc</li>
    <li>linuxPackages_5_13.can-isotp</li>
    <li>linuxPackages_5_13.cpupower</li>
    <li>linuxPackages_5_13.cryptodev</li>
    <li>linuxPackages_5_13.ddcci-driver</li>
    <li>linuxPackages_5_13.digimend</li>
    <li>linuxPackages_5_13.ena</li>
    <li>linuxPackages_5_13.fwts-efi-runtime</li>
    <li>linuxPackages_5_13.gcadapter-oc-kmod</li>
    <li>linuxPackages_5_13.hid-nintendo</li>
    <li>linuxPackages_5_13.hyperv-daemons</li>
    <li>linuxPackages_5_13.jool</li>
    <li>linux_5_13 (linuxPackages_5_13.kernel)</li>
    <li>linuxPackages_5_13.mba6x_bl</li>
    <li>linuxPackages_5_13.mbp2018-bridge-drv</li>
    <li>linuxPackages_5_13.netatop</li>
    <li>linuxPackages_5_13.oci-seccomp-bpf-hook</li>
    <li>linuxPackages_5_13.odp-dpdk</li>
    <li>linuxPackages_5_13.openrazer</li>
    <li>linuxPackages_5_13.r8125</li>
    <li>linuxPackages_5_13.r8168</li>
    <li>linuxPackages_5_13.rtl8812au</li>
    <li>linuxPackages_5_13.rtl8821cu</li>
    <li>linuxPackages_5_13.rtl88x2bu</li>
    <li>linuxPackages_5_13.rtw88 (linuxPackages_5_13.rtlwifi_new)</li>
    <li>linuxPackages_5_13.stdenv</li>
    <li>linuxPackages_5_13.systemtap</li>
    <li>linuxPackages_5_13.tmon</li>
    <li>linuxPackages_5_13.usbip</li>
    <li>linuxPackages_5_13.v4l2loopback</li>
    <li>linuxPackages_5_13.vhba</li>
    <li>linuxPackages_5_13.xpadneo</li>
    <li>linuxPackages_5_13.zfs (linuxPackages_5_13.zfsStable)</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by lheckemann** [comment]
Could you also cherry-pick https://github.com/NixOS/nixpkgs/pull/128785 (0c21d0fd7035d65e48d561a64d1ad1454c640aff) onto this? :)

**Review by lheckemann — APPROVED** [review]

**Comment by lheckemann** [comment]
Do we need to mark anything as broken or is this good to merge?

**Comment by jonringer** [comment]
> Do we need to mark anything as broken or is this good to merge?

I'm moving for the next few days, if we do, then I won't get around to it until next week.

I could see people getting angry that they were "broken" by bumping the latest. Maybe we should drop the `_latest` bump

**Comment by jonringer** [comment]
I have removed the `_latest`, bump. Stable users using `_latest` should probably expect it to not break their dependent modules when upgrade kernel version

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/128533

12 packages marked as broken and skipped:
linuxPackages_5_13.anbox linuxPackages_5_13.ixgbevf linuxPackages_5_13.lttng-modules linuxPackages_5_13.ndiswrapper linuxPackages_5_13.phc-intel linuxPackages_5_13.r8125 linuxPackages_5_13.rtl8723bs linuxPackages_5_13.sch_cake linuxPackages_5_13.tbs linuxPackages_5_13.zfs linuxPackages_5_13.zfsStable linuxPackages_5_13.zfsUnstable

13 packages failed to build:
linuxPackages_5_13.amdgpu-pro linuxPackages_5_13.evdi linuxPackages_5_13.mxu11x0 linuxPackages_5_13.nvidia_x11 linuxPackages_5_13.nvidia_x11_beta linuxPackages_5_13.nvidia_x11_legacy340 linuxPackages_5_13.nvidia_x11_legacy390 linuxPackages_5_13.nvidia_x11_vulkan_beta linuxPackages_5_13.openafs linuxPackages_5_13.openafs_1_9 linuxPackages_5_13.perf linuxPackages_5_13.tuxedo-keyboard linuxPackages_5_13.virtualboxGuestAdditions

64 packages built:
linuxPackages_5_13.acpi_call linuxPackages_5_13.akvcam linuxPackages_5_13.asus-wmi-sensors linuxPackages_5_13.batman_adv linuxPackages_5_13.bbswitch linuxPackages_5_13.bcc linuxPackages_5_13.bpftrace linuxPackages_5_13.broadcom_sta linuxPackages_5_13.can-isotp linuxPackages_5_13.chipsec linuxPackages_5_13.cpupower linuxPackages_5_13.cryptodev linuxPackages_5_13.ddcci-driver linuxPackages_5_13.digimend linuxPackages_5_13.dpdk linuxPackages_5_13.ena linuxPackages_5_13.facetimehd linuxPackages_5_13.fwts-efi-runtime linuxPackages_5_13.gcadapter-oc-kmod linuxPackages_5_13.hid-nintendo linuxPackages_5_13.hyperv-daemons linuxPackages_5_13.intel-speed-select linuxPackages_5_13.isgx linuxPackages_5_13.it87 linuxPackages_5_13.jool linux_5_13 linuxPackages_5_13.mba6x_bl linuxPackages_5_13.mbp2018-bridge-drv linuxPackages_5_13.mwprocapture linuxPackages_5_13.netatop linuxPackages_5_13.nvidiabl linuxPackages_5_13.oci-seccomp-bpf-hook linuxPackages_5_13.odp-dpdk linuxPackages_5_13.openrazer linuxPackages_5_13.pktgen linuxPackages_5_13.ply linuxPackages_5_13.r8168 linuxPackages_5_13.rtl8192eu linuxPackages_5_13.rtl8812au linuxPackages_5_13.rtl8814au linuxPackages_5_13.rtl8821au linuxPackages_5_13.rtl8821ce linuxPackages_5_13.rtl8821cu linuxPackages_5_13.rtl88x2bu linuxPackages_5_13.rtl88xxau-aircrack linuxPackages_5_13.rtw88 linuxPackages_5_13.stdenv linuxPackages_5_13.sysdig linuxPackages_5_13.system76 linuxPackages_5_13.system76-acpi linuxPackages_5_13.system76-io linuxPackages_5_13.systemtap linuxPackages_5_13.tmon linuxPackages_5_13.tp_smapi linuxPackages_5_13.turbostat linuxPackages_5_13.usbip linuxPackages_5_13.v4l2loopback linuxPackages_5_13.v86d linuxPackages_5_13.vendor-reset linuxPackages_5_13.vhba li
```
Appears to be the same as unstable

**Pull request merged**
