### PR TITLE
glibcLocales: support building on musl

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yu-re-ka** [comment]
@ofborg build pkgsMusl.glibcLocales

**Review by alyssais — CHANGES_REQUESTED** [review]
Breaks cross.

**Comment by yu-re-ka** [comment]
Please test again

**Comment by alyssais** [comment]
Gets further, but still broken:

```
aa_DJ.UTF-8...cannot create temporary file: /build/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/locale/locale-archive.yit4KF: No such file or directory
```

(Building `pkgsCross.aarch64-multiplatform.glibcLocales` from x86_64-linux.)

**Comment by yu-re-ka** [comment]
I think I figured it out now. Also confirmed with `pkgsCross.aarch64-multiplatform.glibcLocales`.

**Review by alyssais — CHANGES_REQUESTED** [review]
Otherwise LGTM.

**Pull request merged**
