### PR TITLE
dart-sass: 1.68.0 -> 1.69.0

### PR DESCRIPTION
**Pull request by lelgenio**
## Description of changes

Changelog: https://github.com/sass/dart-sass/blob/1.69.0/CHANGELOG.md
Diff: https://github.com/sass/dart-sass/compare/1.68.0...1.69.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ianmjones** [comment]
Result of `nixpkgs-review pr 259277` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>dart-sass</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>rstudio</li>
    <li>rstudioWrapper</li>
    <li>shopware-cli</li>
  </ul>
</details>

**Review by ianmjones — COMMENTED** [review]
sass itself built and ran fine, but for some reason RStudio did not (not sure why this is part of the dependency chain). :shrug: 

2023-10-07-17-48-57_3840x1981_scrot

**Comment by lelgenio** [comment]
@ianmjones The build failure is unrelated to this change, It's already failing on master.
Opened an issue at: https://github.com/NixOS/nixpkgs/issues/259651

**Review by ianmjones — APPROVED** [review]
@lelgenio said ...

> The [RStudio] build failure is unrelated to this change, It's already failing on master.

As such, seems to me that `dart-sass` is building and working fine. :+1:

**Pull request merged**
