### PR TITLE
python3Packages.pytest-cov: 2.11.1 -> 2.12.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 2.12.1

Change log:

- https://github.com/pytest-dev/pytest-cov/blob/master/CHANGELOG.rst#2121-2021-06-01
- https://github.com/pytest-dev/pytest-cov/blob/master/CHANGELOG.rst#2120-2021-05-14

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126013` at 34c4a438 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages marked as broken and skipped:</summary>
  <ul>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>hadoop</li>
    <li>hadoop_2_7</li>
    <li>hadoop_2_8</li>
    <li>hadoop_2_9</li>
    <li>impressive</li>
    <li>linuxPackages_hardkernel_4_14.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>odpdown</li>
    <li>opentsdb</li>
    <li>pig</li>
    <li>rainbowstream</li>
    <li>spark</li>
  </ul>
</details>
<details>
  <summary>106 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/eec800947411ef0f866c09380f3ef250">black</a> (python38Packages.black)</li>
    <li><a href="https://gist.github.com/3eafeb6b004c42a9abb75a7aef2a726c">bonfire</a></li>
    <li><a href="https://gist.github.com/5f448761f59e391a716ac488aa2c729d">liberation_ttf</a> (liberation_ttf_v2)</li>
    <li><a href="https://gist.github.com/305ce12606e6a25cf28b0752d7393191">mozlz4a</a></li>
    <li><a href="https://gist.github.com/2589e1b8fd9f249229840cd876f640ad">python38Packages.accuweather</a></li>
    <li><a href="https://gist.github.com/ef1bcf0cf692ffab138af48a5eda6f6e">python38Packages.advantage-air</a></li>
    <li><a href="https://gist.github.com/3205dfe94fdc1decba1d0b7e4214ee75">python38Packages.agent-py</a></li>
    <li><a href="https://gist.github.com/aad0a5224075da643bb188e044379267">python38Packages.aiobotocore</a></li>
    <li><a href="https://gist.github.com/1b6ef1470c9a26ed7fac93a95e1a53b0">python38Packages.aiohttp</a></li>
    <li><a href="https://gist.github.com/4ebbaf2f69323a269debc88bce61a21b">python38Packages.aiohttp-cors</a></li>
    <li><a href="https://gist.github.com/7714148a72ce934efd98a1c402d3d4b4">python38Packages.aiohttp-socks</a></li>
    <li><a href="https://gist.github.com/5988a4fc98dbc98f51545f3acb03b79a">python38Packages.aiohue</a></li>
    <li><a href="https://gist.github.com/6ee1dc2670015ad45c54fbd1773b9ba4">python38Packages.aioresponses</a></li>
    <li><a href="https://gist.github.com/a5ebda033ce83a427c8f69529d6a9532">python38Packages.aioshelly</a></li>
    <li><a href="https://gist.github.com/1a07ef8ca07a718bcae57273303811a1">python38Packages.aiounifi</a></li>
    <li><a href="https://gist.github.com/59f38e19150cafae87009f34ffae5966">python38Packages.ambiclimate</a></li>
    <li><a href="https://gist.github.com/d43f172ce90701abfdebab70f8acb7aa">python38Packages.aresponses</a></li>
    <li><a href="https://gist.github.com/e0d4ad878c3713ef6741a505c82851df">python38Packages.auroranoaa</a></li>
    <li><a href="https://gist.github.com/b1a1047425d110f0e0c502ffa09f4caa">python38Packages.azure-core</a></li>
    <li><a href="https://gist.github.com/34f82fd72d9238f93044ade7299ada67">python38Packages.azure-keyvault-secrets</a></li>
    <li><a href="https://gist.github.com/b33419c3c17c261a6d69d5937ba7bf44">python38Packages.azure-mgmt-common</a></li>
    <li><a href="https://gist.github.com/0326cbcaeded416c2f327c6e317c0a0c">python38Packages.azure-mgmt-core</a></li>
    <li><a href="https://gist.github.com/815f2c613f9cbb21605498f756160b86">python38Packages.azure-storage-blob</a></li>
    <li><a href="https://gist.github.com/df9e137a7e3a7035e9673e722446fdef">python38Packages.backports_functools_lru_cache</a></li>
    <li><a href="https://gist.github.com/495918b173eaa7f2630c1df25b448e99">python38Packages.booleanoperations</a></li>
    <li><a href="https://gist.github.com/ee7abfc5c0120814164dace74d58ae8c">python38Packages.brotlipy</a></li>
    <li><a href="https://gist.github.com/12cdaab63b5d65ef7a233a6be76930fc">python38Packages.browser-cookie3</a></li>
    <li><a href="https://gist.github.com/d28675c2ce2da644d0851bda8b8a32f6">python38Packages.construct</a></li>
    <li><a href="https://gist.github.com/07034651a10b5c5e276e872ab72c613d">python38Packages.coronavirus</a></li>
    <li><a href="https://gist.github.com/5970e58778f8db1c195267748a0e1ba9">python38Packages.dask</a></li>
    <li><a href="https://gist.github.com/73208c0280012209f41e968c83cf785d">python38Packages.defcon</a></li>
    <li><a href="https://gist.github.com/a04c139eff1923d0c62416192996127a">python38Packages.distributed</a></li>
    <li><a href="https://gist.github.com/96d37a5240ddb3bf2a72becc27fb02fa">python38Packages.fontmath</a></li>
    <li><a href="https://gist.github.com/6832a31299d13f2f1257f02ae5be54dd">python38Packages.fontparts</a></li>
    <li><a href="https://gist.github.com/55ae76efa9829c0ef462ebaa30c79e10">python38Packages.fontpens</a></li>
    <li><a href="https://gist.github.com/1dac038fec557dd8e162244526391af0">python38Packages.fonttools</a></li>
    <li><a href="https://gist.github.com/443941989fd83a1ff6df3b9da04c722e">python38Packages.fsspec</a></li>
    <li><a href="https://gist.github.com/6c65d6faabd8bfd45aca368b9a7bf4c3">python38Packages.hole</a></li>
    <li><a href="https://gist.github.com/1a7f6ed00b45b085299c42d3839f2092">python38Packages.httpbin</a></li>
    <li><a href="https://gist.github.com/abfb614a7856deede8697713e08c4179">python38Packages.irc</a></li>
    <li><a href="https://gist.github.com/86e1173241f2c8566ee06ade3dff6784">python38Packages.jaraco_collections</a></li>
    <li><a href="https://gist.github.com/0fbe5b8640a0a79c70c00fc426a8d1ea">python38Packages.jaraco_functools</a></li>
    <li><a href="https://gist.github.com/b0bda8c162f1ab9c8299ea24cb596c93">python38Packages.jaraco_logging</a></li>
    <li><a href="https://gist.github.com/396cf4b010b0211137c754d460ed1628">python38Packages.jaraco_text</a></li>
    <li><a href="https://gist.github.com/3f038a856735eb4a1cefad3ccd92c596">python38Packages.jsonrpc-websocket</a></li>
    <li><a href="https://gist.github.com/fabe128d926ed83700e455a028f5c771">python38Packages.kaitaistruct</a></li>
    <li><a href="https://gist.github.com/d8130c3cc9e25d740194f5d2d86b260e">python38Packages.lz4</a> (python38Packages.python-lz4)</li>
    <li><a href="https://gist.github.com/bb155904e8291a0f985ff16209dcb181">python38Packages.matrix-nio</a></li>
    <li><a href="https://gist.github.com/0a98b21ce488c4f61e1d238441b7d0a8">python38Packages.msrest</a></li>
    <li><a href="https://gist.github.com/64d478a172a893f00f90d5d8cbcd9710">python38Packages.msrestazure</a></li>
    <li><a href="https://gist.github.com/ff8f86b608575eba55efff45a994df2d">python38Packages.mutatormath</a></li>
    <li><a href="https://gist.github.com/923f91457e3b2b8e9745abd5777184e9">python38Packages.plexauth</a></li>
    <li><a href="https://gist.github.com/9b930c5b6c67e82523bf4a853308a5da">python38Packages.poolsense</a></li>
    <li><a href="https://gist.github.com/6a71fe8e2a18e6fc8a35ab0f04461da1">python38Packages.portend</a></li>
    <li><a href="https://gist.github.com/c26c5c896693c5b542ff28595577acbf">python38Packages.pyalmond</a></li>
    <li><a href="https://gist.github.com/f1d3c78002befb559ea9b1830eb8e993">python38Packages.pycfdns</a></li>
    <li><a href="https://gist.github.com/2f09e30f25d4547a89bce993a6f2bbc1">python38Packages.pyeverlights</a></li>
    <li><a href="https://gist.github.com/36d5aad336b8cd058b7c2c8bdcb76f14">python38Packages.pyfido</a></li>
    <li><a href="https://gist.github.com/01e080720ae26197032497255fff9638">python38Packages.pykmtronic</a></li>
    <li><a href="https://gist.github.com/6438bee85fed4fb950b89cdcd47b9630">python38Packages.pymazda</a></li>
    <li><a href="https://gist.github.com/7a602602e74d89649e81eb4b109b21e6">python38Packages.pyplaato</a></li>
    <li><a href="https://gist.github.com/f61696f4bd5234ecf30ae99cec7089d6">python38Packages.pyrisco</a></li>
    <li><a href="https://gist.github.com/7ca03fe0318caa4cba8b20cd93100a7e">python38Packages.pysqueezebox</a></li>
    <li><a href="https://gist.github.com/c4a14183cbd7febf54c0e86d6e60a996">python38Packages.pytest-aiohttp</a></li>
    <li><a href="https://gist.github.com/066196fb15c5506d47fee445921bab12">python38Packages.pytest-black</a></li>
    <li><a href="https://gist.github.com/0cac0d499049217af4292d3523d65042">python38Packages.pytest-httpbin</a></li>
    <li><a href="https://gist.github.com/5ad1bdced4b7f7742b7b4e5f24ef80b8">python38Packages.pytest-vcr</a></li>
    <li><a href="https://gist.github.com/7a34b44e2f4cd2ca3fd4c0bccb923de8">python38Packages.python-engineio</a></li>
    <li><a href="https://gist.github.com/31b6f037c07153cb68820df4c250d4a0">python38Packages.pyvolumio</a></li>
    <li><a href="https://gist.github.com/75633045d868ac1b3fe8405da6db1dd6">python38Packages.tempora</a></li>
    <li><a href="https://gist.github.com/df3b81fd2d4d86a197c2b733235d62a9">python38Packages.twinkly-client</a></li>
    <li><a href="https://gist.github.com/fbde0ad720f1a5031fd8d733cad1a940">python38Packages.vcrpy</a></li>
    <li><a href="https://gist.github.com/23c3ad339377ab3ba63d400f616fd0ee">python38Packages.wiffi</a></li>
    <li><a href="https://gist.github.com/302009abdb5391b25491e5b0a87e5dfc">python39Packages.aiohttp</a></li>
    <li><a href="https://gist.github.com/bbea09b60c0ef8134b1c5ec0637c3c15">python39Packages.aiohttp-cors</a></li>
    <li><a href="https://gist.github.com/000bfa6621e11aba16082921a1233138">python39Packages.aioresponses</a></li>
    <li><a href="https://gist.github.com/c6fa390db330896de952b31062280015">python39Packages.aresponses</a></li>
    <li><a href="https://gist.github.com/11f8ed951657a6123d4059c41e3a36a2">python39Packages.azure-core</a></li>
    <li><a href="https://gist.github.com/a0d57d7b5570d5e84180376d74a2e737">python39Packages.azure-storage-blob</a></li>
    <li><a href="https://gist.github.com/806da027c5585ce382cf79df47d90d5f">python39Packages.backports_functools_lru_cache</a></li>
    <li><a href="https://gist.github.com/fbafbe9664949ce9b20c650eeeb5cd2c">python39Packages.black</a></li>
    <li><a href="https://gist.github.com/a91014c01ea4a78d18abc53ff3dcedd5">python39Packages.brotlipy</a></li>
    <li><a href="https://gist.github.com/ef8372c4463acede17473eb01437e867">python39Packages.construct</a></li>
    <li><a href="https://gist.github.com/b793c284f3a4d6c0173d806d2db19c58">python39Packages.dask</a></li>
    <li><a href="https://gist.github.com/82e6151b8c6d525885387725b083ffb3">python39Packages.distributed</a></li>
    <li><a href="https://gist.github.com/8a89c4057ea27af6c7ffe31aabcc187c">python39Packages.easywatch</a></li>
    <li><a href="https://gist.github.com/ec8f9e2b03a755013fc1dea0d0ff9178">python39Packages.fsspec</a></li>
    <li><a href="https://gist.github.com/18285c2b39d6b693ba841d40ad15f1c2">python39Packages.httpbin</a></li>
    <li><a href="https://gist.github.com/3273afe761377cbba0f8c2ee46689e12">python39Packages.hupper</a></li>
    <li><a href="https://gist.github.com/9327e3ec86b094b511db9d2d4ec70198">python39Packages.jaraco_collections</a></li>
    <li><a href="https://gist.github.com/8d4f66e7b7c63782e44e9a5e4aa8353e">python39Packages.jaraco_functools</a></li>
    <li><a href="https://gist.github.com/efe3646cc6fd0ab57e4a6dcb853cfa33">python39Packages.jaraco_text</a></li>
    <li><a href="https://gist.github.com/1d9dcc3b7e573ef4147ffe2c5cbb85e9">python39Packages.kaitaistruct</a></li>
    <li><a href="https://gist.github.com/5e21cbabe771d153f3133d7d6880f397">python39Packages.lz4</a> (python39Packages.python-lz4)</li>
    <li><a href="https://gist.github.com/59a952aedee9d3cdd08f20ffb1097c71">python39Packages.msrest</a></li>
    <li><a href="https://gist.github.com/41a329888dd18af6e92cf3f3f4a5e2cf">python39Packages.portend</a></li>
    <li><a href="https://gist.github.com/f24dac1dcfa243b3bc23f1700eff5eca">python39Packages.pypugjs</a></li>
    <li><a href="https://gist.github.com/5c7b5b7e4b8414931b0835cb7fa7b5a3">python39Packages.pyramid</a></li>
    <li><a href="https://gist.github.com/9d72a3fb5f771c9e406810414990f77d">python39Packages.pyramid_mako</a></li>
    <li><a href="https://gist.github.com/af2809968e46730c2b30b65fe761ca2e">python39Packages.pytest-aiohttp</a></li>
    <li><a href="https://gist.github.com/5228b490ae74c39249809498886fe959">python39Packages.pytest-black</a></li>
    <li><a href="https://gist.github.com/75ed79aa82913d9fa3e4ba56ba0898ad">python39Packages.pytest-httpbin</a></li>
    <li><a href="https://gist.github.com/8d7848304b16d378fc1d83df4154a77e">python39Packages.pytest-vcr</a></li>
    <li><a href="https://gist.github.com/fb046c70f590bf87bbc7ebe186388c53">python39Packages.tempora</a></li>
    <li><a href="https://gist.github.com/4ac0b04217b71c91414062c68b6b8156">python39Packages.vcrpy</a></li>
    <li><a href="https://gist.github.com/68f445540b377a116f8bcbcbd8177165">python39Packages.watchdog</a></li>
  </ul>
</details>
<details>
  <summary>2321 packages skipped due to time constraints:</summary>
  <ul>
    <li>DisnixWebService</li>
    <li>R</li>
    <li>abcl</li>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>agda-pkg</li>
    <li>aiodnsbrute</li>
    <li>alerta-server</li>
    <li>alloy (alloy5)</li>
    <li>alloy4</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>258 packages built successfully:</summary>
  <ul>
    <li>photon</li>
    <li>python38Packages.PyGithub</li>
    <li>python38Packages.acme</li>
    <li>python38Packages.adal</li>
    <li>python38Packages.aiosmtpd</li>
    <li>python38Packages.alembic</li>
    <li>python38Packages.ansiwrap</li>
    <li>python38Packages.asgi-csrf</li>
    <li>python38Packages.atpublic</li>
    <li>python38Packages.autobahn</li>
    <li>python38Packages.bleak</li>
    <li>python38Packages.boto</li>
    <li>python38Packages.cairosvg</li>
    <li>python38Packages.cbor2</li>
    <li>python38Packages.clickclick</li>
    <li>python38Packages.cloudflare</li>
    <li>python38Packages.croniter</li>
    <li>python38Packages.cssselect2</li>
    <li>python38Packages.dbus-next</li>
    <li>python38Packages.desktop-notifier</li>
    <li>python38Packages.diskcache</li>
    <li>python38Packages.django-allauth</li>
    <li>python38Packages.dockerfile-parse</li>
    <li>python38Packages.easywatch</li>
    <li>python38Packages.factory_boy</li>
    <li>python38Packages.faker</li>
    <li>python38Packages.fasteners</li>
    <li>python38Packages.flask</li>
    <li>python38Packages.flask-babel</li>
    <li>python38Packages.flask-babelex</li>
    <li>python38Packages.flask-bootstrap</li>
    <li>python38Packages.flask-compress</li>
    <li>python38Packages.flask-cors</li>
    <li>python38Packages.flask-limiter</li>
    <li>python38Packages.flask-mongoengine</li>
    <li>python38Packages.flask-openid</li>
    <li>python38Packages.flask-paginate</li>
    <li>python38Packages.flask-restful</li>
    <li>python38Packages.flask-reverse-proxy-fix</li>
    <li>python38Packages.flask-sockets</li>
    <li>python38Packages.flask-sslify</li>
    <li>python38Packages.flask-versioned</li>
    <li>python38Packages.flask_assets</li>
    <li>python38Packages.flask_login</li>
    <li>python38Packages.flask_mail</li>
    <li>python38Packages.flask_script</li>
    <li>python38Packages.flask_sqlalchemy</li>
    <li>python38Packages.flask_testing</li>
    <li>python38Packages.flask_wtf</li>
    <li>python38Packages.flaskbabel</li>
    <li>python38Packages.flufl_bounce</li>
    <li>python38Packages.flufl_i18n</li>
    <li>python38Packages.gevent-websocket</li>
    <li>python38Packages.google-api-core</li>
    <li>python38Packages.google-api-python-client</li>
    <li>python38Packages.google-auth</li>
    <li>python38Packages.google-auth-httplib2</li>
    <li>python38Packages.google-auth-oauthlib</li>
    <li>python38Packages.google-cloud-core</li>
    <li>python38Packages.google-cloud-iam</li>
    <li>python38Packages.google-cloud-kms</li>
    <li>python38Packages.google-cloud-storage</li>
    <li>python38Packages.google-cloud-testutils</li>
    <li>python38Packages.google-resumable-media</li>
    <li>python38Packages.graphene</li>
    <li>python38Packages.graphviz</li>
    <li>python38Packages.gunicorn</li>
    <li>python38Packages.httplib2</li>
    <li>python38Packages.httpretty</li>
    <li>python38Packages.hupper</li>
    <li>python38Packages.ibm-cloud-sdk-core</li>
    <li>python38Packages.inquirer</li>
    <li>python38Packages.isort</li>
    <li>python38Packages.jeepney</li>
    <li>python38Packages.jira</li>
    <li>python38Packages.jsonlines</li>
    <li>python38Packages.keyring</li>
    <li>python38Packages.libagent</li>
    <li>python38Packages.mailmanclient</li>
    <li>python38Packages.maya</li>
    <li>python38Packages.minio</li>
    <li>python38Packages.msal</li>
    <li>python38Packages.msal-extensions</li>
    <li>python38Packages.multidict</li>
    <li>python38Packages.mwoauth</li>
    <li>python38Packages.natsort</li>
    <li>python38Packages.notify-py</li>
    <li>python38Packages.oauth2client</li>
    <li>python38Packages.oauthlib</li>
    <li>python38Packages.objgraph</li>
    <li>python38Packages.openapi-schema-validator</li>
    <li>python38Packages.openapi-spec-validator</li>
    <li>python38Packages.pendulum</li>
    <li>python38Packages.pkutils</li>
    <li>python38Packages.plaster</li>
    <li>python38Packages.plaster-pastedeploy</li>
    <li>python38Packages.poetry-core</li>
    <li>python38Packages.portalocker</li>
    <li>python38Packages.prance</li>
    <li>python38Packages.property-manager</li>
    <li>python38Packages.pyee</li>
    <li>python38Packages.pyjwt</li>
    <li>python38Packages.pylint</li>
    <li>python38Packages.pyocr</li>
    <li>python38Packages.pyppeteer</li>
    <li>python38Packages.pypugjs</li>
    <li>python38Packages.pyramid</li>
    <li>python38Packages.pyramid_mako</li>
    <li>python38Packages.pytestcov (python38Packages.pytest-cov)</li>
    <li>python38Packages.pytest-filter-subpackage</li>
    <li>python38Packages.pytest-flask</li>
    <li>python38Packages.pytest-isort</li>
    <li>python38Packages.pytest-localserver</li>
    <li>python38Packages.pytest-randomly</li>
    <li>python38Packages.pytest-server-fixtures</li>
    <li>python38Packages.pytest-shutil</li>
    <li>python38Packages.pytest-timeout</li>
    <li>python38Packages.pytest-trio</li>
    <li>python38Packages.pytest-virtualenv</li>
    <li>python38Packages.python-daemon</li>
    <li>python38Packages.python-jose</li>
    <li>python38Packages.python-jsonrpc-server</li>
    <li>python38Packages.python-multipart</li>
    <li>python38Packages.python-socks</li>
    <li>python38Packages.readchar</li>
    <li>python38Packages.requests_oauthlib</li>
    <li>python38Packages.rich</li>
    <li>python38Packages.secretstorage</li>
    <li>python38Packages.semver</li>
    <li>python38Packages.setuptoolsTrial</li>
    <li>python38Packages.smart-open</li>
    <li>python38Packages.snapshottest</li>
    <li>python38Packages.sortedcollections</li>
    <li>python38Packages.stups-cli-support</li>
    <li>python38Packages.stups-tokens</li>
    <li>python38Packages.tensorboard-plugin-profile</li>
    <li>python38Packages.textwrap3</li>
    <li>python38Packages.threadpoolctl</li>
    <li>python38Packages.tilequant</li>
    <li>python38Packages.tinycss2</li>
    <li>python38Packages.tld</li>
    <li>python38Packages.tox</li>
    <li>python38Packages.tqdm</li>
    <li>python38Packages.trio</li>
    <li>twine (python38Packages.twine)</li>
    <li>python38Packages.typesentry</li>
    <li>python38Packages.unpaddedbase64</li>
    <li>python38Packages.validators</li>
    <li>python38Packages.venusian</li>
    <li>python38Packages.virtualenv</li>
    <li>python38Packages.warrant</li>
    <li>python38Packages.watchdog</li>
    <li>python38Packages.werkzeug</li>
    <li>python38Packages.yarl</li>
    <li>python39Packages.PyGithub</li>
    <li>python39Packages.adal</li>
    <li>python39Packages.aiosmtpd</li>
    <li>python39Packages.alembic</li>
    <li>python39Packages.asgi-csrf</li>
    <li>python39Packages.atpublic</li>
    <li>python39Packages.autobahn</li>
    <li>python39Packages.cairosvg</li>
    <li>python39Packages.cbor2</li>
    <li>python39Packages.clickclick</li>
    <li>python39Packages.cssselect2</li>
    <li>python39Packages.dbus-next</li>
    <li>python39Packages.desktop-notifier</li>
    <li>python39Packages.factory_boy</li>
    <li>python39Packages.faker</li>
    <li>python39Packages.flask</li>
    <li>python39Packages.flask-babel</li>
    <li>python39Packages.flask-compress</li>
    <li>python39Packages.flask-cors</li>
    <li>python39Packages.flask-limiter</li>
    <li>python39Packages.flask-openid</li>
    <li>python39Packages.flask-restful</li>
    <li>python39Packages.flask-sockets</li>
    <li>python39Packages.flask-versioned</li>
    <li>python39Packages.flask_login</li>
    <li>python39Packages.flask_mail</li>
    <li>python39Packages.flask_script</li>
    <li>python39Packages.flask_sqlalchemy</li>
    <li>python39Packages.flask_testing</li>
    <li>python39Packages.flask_wtf</li>
    <li>python39Packages.flufl_bounce</li>
    <li>python39Packages.flufl_i18n</li>
    <li>python39Packages.gevent-websocket</li>
    <li>python39Packages.google-api-core</li>
    <li>python39Packages.google-api-python-client</li>
    <li>python39Packages.google-auth</li>
    <li>python39Packages.google-auth-httplib2</li>
    <li>python39Packages.google-auth-oauthlib</li>
    <li>python39Packages.graphene</li>
    <li>python39Packages.graphviz</li>
    <li>python39Packages.gunicorn</li>
    <li>python39Packages.httplib2</li>
    <li>python39Packages.httpretty</li>
    <li>python39Packages.isort</li>
    <li>python39Packages.jeepney</li>
    <li>python39Packages.jsonlines</li>
    <li>python39Packages.keyring</li>
    <li>python39Packages.libagent</li>
    <li>python39Packages.mailmanclient</li>
    <li>python39Packages.maya</li>
    <li>python39Packages.msal</li>
    <li>python39Packages.msal-extensions</li>
    <li>python39Packages.multidict</li>
    <li>python39Packages.mwoauth</li>
    <li>python39Packages.oauth2client</li>
    <li>python39Packages.oauthlib</li>
    <li>python39Packages.objgraph</li>
    <li>python39Packages.openapi-schema-validator</li>
    <li>python39Packages.openapi-spec-validator</li>
    <li>python39Packages.pendulum</li>
    <li>python39Packages.plaster</li>
    <li>python39Packages.plaster-pastedeploy</li>
    <li>python39Packages.poetry-core</li>
    <li>python39Packages.portalocker</li>
    <li>python39Packages.prance</li>
    <li>python39Packages.property-manager</li>
    <li>python39Packages.pyjwt</li>
    <li>python39Packages.pylint</li>
    <li>python39Packages.pytestcov (python39Packages.pytest-cov)</li>
    <li>python39Packages.pytest-filter-subpackage</li>
    <li>python39Packages.pytest-isort</li>
    <li>python39Packages.pytest-localserver</li>
    <li>python39Packages.pytest-randomly</li>
    <li>python39Packages.pytest-shutil</li>
    <li>python39Packages.pytest-timeout</li>
    <li>python39Packages.pytest-trio</li>
    <li>python39Packages.pytest-virtualenv</li>
    <li>python39Packages.python-daemon</li>
    <li>python39Packages.python-multipart</li>
    <li>python39Packages.readchar</li>
    <li>python39Packages.requests_oauthlib</li>
    <li>python39Packages.rich</li>
    <li>python39Packages.secretstorage</li>
    <li>python39Packages.semver</li>
    <li>python39Packages.setuptoolsTrial</li>
    <li>python39Packages.snapshottest</li>
    <li>python39Packages.sortedcollections</li>
    <li>python39Packages.stups-cli-support</li>
    <li>python39Packages.stups-tokens</li>
    <li>python39Packages.tensorboard-plugin-profile</li>
    <li>python39Packages.textwrap3</li>
    <li>python39Packages.threadpoolctl</li>
    <li>python39Packages.tilequant</li>
    <li>python39Packages.tinycss2</li>
    <li>python39Packages.tox</li>
    <li>python39Packages.tqdm</li>
    <li>python39Packages.trio</li>
    <li>python39Packages.twine</li>
    <li>python39Packages.typesentry</li>
    <li>python39Packages.validators</li>
    <li>python39Packages.venusian</li>
    <li>python39Packages.virtualenv</li>
    <li>python39Packages.werkzeug</li>
    <li>python39Packages.yarl</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/pytest-cov/default.nix:32:3:
```
   |
32 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by jonringer — APPROVED** [review]
should go into staging, but changes LGTM

**Comment by fabaff** [comment]
> should go into staging, but changes LGTM

That was the plan. GitHub action failed. I will do it manually.

**Pull request merged**
