### PR TITLE
diffoscope: enable bloat by default

### PR DESCRIPTION
**Pull request by gebner**
###### Motivation for this change

`nix run nixpkgs.diffoscope -c diffoscope` should start a full-featured diffoscope.  Using a lot of external tools is literally one of the tagline features of diffoscope: "unpack archives of many kinds and transform various binary formats into more human-readable form".

This PR therefore changes the top-level attribute `diffoscope` to include the whole kitchen sink.  A new `diffoscopeMinimal` attribute is added with the current feature set and smaller closure size.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grahamc** [comment]
If I remember correctly "with bloat" cannot be built on Hydra because part of its build chain creates an output with a significantly large sparse file. However, the NAR format doesn't know about sparse files and the output becomes too large and is rejected.

**Comment by gebner** [comment]
Ah, that's unfortunate.  Do you remember which package this was?

I'd really like hydra to build the full version because the python tests take quite some time to run.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121042` at b6d7559e run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>diffoscope</li>
    <li>diffoscopeMinimal</li>
  </ul>
</details>

**Comment by gebner** [comment]
Another alternative would be to reduce the number of tools disabled by `enableBloat = false`.  Upstream has a much less restrictive list of "huge" tools:
```python
# Set of tools considered "large" their installation size, or too niche in
# their target users.  To be easily excluded from installation if not
# specifically required.
# These are the names of the tools, not package names.
HUGE_TOOLS = {
    "ghc",
    "ocamlobjinfo",
    "llvm-bcanalyzer",
    "llvm-config",
    "llvm-dis",
    "ppudump",
    "javap",
    "ssconvert",
    "apktool",
    "apksigner",
    "pedump",
    "radare2",
    "dumpxsb",
}
```

**Comment by grahamc** [comment]
Since every dependency of diffoscope with bloat enabled was pre-built by hydra, I'm forced to conclude I am misremembering :) 

:+1:

**Pull request merged**
