### PR TITLE
[staging] busybox: 1.27.1 -> 1.27.2

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Update

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

@vcunat

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
Bootstrap tools seem OK.

**Comment by vcunat** [comment]
Note that this change causes almost no rebuilds, so it could go to master directly...

**Comment by dezgeg** [comment]
Shall we write it down?
````
diff --git a/pkgs/os-specific/linux/busybox/default.nix b/pkgs/os-specific/linux/busybox/default.nix
index bab8c5502d..56ca7283ef 100644
--- a/pkgs/os-specific/linux/busybox/default.nix
+++ b/pkgs/os-specific/linux/busybox/default.nix
@@ -29,6 +29,9 @@ in
 stdenv.mkDerivation rec {
   name = "busybox-1.27.1";
 
+  # Note to whoever is updating busybox: please verify that:
+  #   nix-build pkgs/stdenv/linux/make-bootstrap-tools.nix -A test
+  # still builds after the update.
   src = fetchurl {
     url = "http://busybox.net/downloads/${name}.tar.bz2";
     sha256 = "0dprylmcignrp29g41nkwr1b30v7i5x21lwymp3b93i1zd9sr468";
````

**Comment by NeQuissimus** [comment]
I am committing this straight to master, including the bootstrap test comment.

**Pull request closed without merging**
