### PR TITLE
hexchat: 2.12.4 -> 2.14.2

### PR DESCRIPTION
**Pull request by averelld**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @romildo

### CODE REVIEW

**Review by teto — APPROVED** [review]
tested with nix-review, worked fine.
I don't know enough about meson to comment the patchPhase though

**Review by ivan — APPROVED** [review]
Tested by connecting to my ZNC with a very large number of channels, I did not see any crashes or regressions

**Review by ivan — COMMENTED** [review]
Actually, I just noticed that 2.14.2 always dumps core when I close it:

```
# /run/current-system/sw/bin/hexchat -d $HOME/.config/hexchats/full
Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters

zsh: abort (core dumped)  /run/current-system/sw/bin/hexchat -d $HOME/.config/hexchats/full
```

Upstream bug is https://github.com/hexchat/hexchat/issues/2237 but maybe this is just something users have to live with until it's fixed upstream?

**Comment by teto** [comment]
noticed the same bug, I believe it's fine merging.

**Comment by averelld** [comment]
I've added the fedora patch.

**Review by ivan — APPROVED** [review]
Tested again, no core dump on exit any more; LGTM

**Comment by ivan** [comment]
@GrahamcOfBorg build hexchat

**Pull request merged**
