### PR TITLE
qt5.qtbase, qt6.qtbase: hardcode QT_QPA_PLATFORM_PLUGIN_PATH too avoid omitting

### PR DESCRIPTION
**Pull request by Et7f3**
###### Description of changes

When debugging #157862

I got:
```
Application path not initialized
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

From this [post](https://forum.qt.io/topic/133532/how-to-solve-could-not-load-the-qt-platform-plugin-cocoa-in-even-though-it-was-found) and
https://github.com/NixOS/nixpkgs/blob/f2f2a140ad9ac94ecaad1203e50bfab13f46e8e0/pkgs/applications/networking/p2p/tribler/default.nix#L89

the patch seems correct. I can't build this version but I can't build the non-patched version either. It is still present in binary cache so I guess my machine is at fault. I checked I see a `qguiapplication.o` so compilation did succeed. I also checked the patched file and the path it contains is similar to what is found for tribler. Since I can't build I can't test that the line showed become useless in tribler (so maybe it has cleanup to be done).

META: No one in code owner of qt6 ?

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
This is normally taken care of by wrapQtAppsHook, I'm not sure why that PR chooses to avoid it.

**Comment by Et7f3** [comment]
> This is normally taken care of by wrapQtAppsHook, I'm not sure why that PR chooses to avoid it.

in qgis the test are executed and fail with this issue from what I see it is a python that load the Qapplication. Does wrapQtAppsHook handle those ?

**Comment by K900** [comment]
wrapQtAppsHook basically just adds all the right environment variables and then runs the application. If it fails during tests, you will probably need to set the environment variables yourself.

**Comment by Et7f3** [comment]
I see only `QT_PLUGIN_PATH` in `wrapQtAppsHook` and `git grep` does show this variable is needed
```
git grep QT_QPA_PLATFORM_PLUGIN_PATH
pkgs/applications/graphics/pixinsight/default.nix:    "--set QT_QPA_PLATFORM_PLUGIN_PATH $out/opt/PixInsight/bin/lib/qt-plugins/platforms"
pkgs/applications/networking/p2p/tribler/default.nix:        --set QT_QPA_PLATFORM_PLUGIN_PATH ${qt5.qtbase.bin}/lib/qt-*/plugins/platforms \
pkgs/applications/networking/p2p/tribler/default.nix:    export QT_QPA_PLATFORM_PLUGIN_PATH=$(echo ${qt5.qtbase.bin}/lib/qt-*/plugins/platforms)
```

Is their a wrapQtLibraryHook ? If no then this PR fix this needed use case.

> If it fails during tests, you will probably need to set the environment variables yourself.

I have bought about this but it case another projet have qt in test it will fail and someone else will loose time in fixing the same issue. I opt to fix at the root cause so it will just works for others app/testsuite. We do already this for binary with patchelf so I think it will benefit us.

**Comment by K900** [comment]
This fix is not correct for other platforms, where platform plugins can be (and are) loaded from different derivations. wrapQtAppsHook sets QT_PLUGIN_PATH, which affects all plugins, not just QPA ones.

**Comment by Et7f3** [comment]
>  where platform plugins can be (and are) loaded from different derivations

Have you an exemple ?

**Comment by K900** [comment]
Linux, and possibly others as well. This will also hurt people that want to build their own platform plugins.

**Comment by Et7f3** [comment]
Ok I will set this variable in test then.

**Comment by Et7f3** [comment]
Now that I thought again what if instead of hard-coding it: I append a default value ?
I preserve original behavior `QT_QPA_PLATFORM_PLUGIN_PATH` affect the runtime and we forget we get the default platform style.

**Pull request closed without merging**
