### PR TITLE
mupdf-headless: init at 1.23.6

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
See https://github.com/NixOS/nixpkgs/pull/279687

cc @toonn who added `desktopToDarwinBundle` in https://github.com/NixOS/nixpkgs/commit/5c4f57cc5720ca7c4a500d6dc672208fe191564a

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
I didn't verify if that fixes all our concerns but code wise I didn't spot an issue.

**Review by veprbl — APPROVED** [review]

**Review by toonn — CHANGES_REQUESTED** [review]
Why remove `desktopToDarwinBundle`? Does the package come with an app bundle for macOS nowadays? The build input might not seem used but it brings in a setup-hook.

Making `desktopToDarwinBundle` depend on whether or not it's being built "headless" should be sufficient, no?

**Comment by dotlambda** [comment]
I wasn't quite sure whether to call it `mupdf-headless` or `mupdf_headless`. Any opinions?
Also, should I change the `pname` of the headless version?

**Review by toonn — COMMENTED** [review]
Apologies, misread the diff.

I think [this bullet point](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md?plain=1#L357) suggests hyphens are preferred.

**Review by toonn — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> I wasn't quite sure whether to call it `mupdf-headless` or `mupdf_headless`. Any opinions? 

``-`` is prefered especially in python land.

> Also, should I change the `pname` of the headless version?

Sure. Anything that breaks because of this was using pname wrong anyway.

**Comment by dotlambda** [comment]
> Sure, if you want to.

I'd prefer not to. The only reason for doing so would be to not mess with `nix-env -i`.

**Comment by SuperSandro2000** [comment]
nix-env is already confused of python3, so I don't think we necessarily need to pay special attention to it.

**Pull request merged**
