### PR TITLE
nixos/nix-containers: use SIGTERM to stop containers

### LINKED ISSUE #109695: "A stop job is running for container" on host shut down
**Describe the bug**

So, I seem to be seeing an issue that more or less exactly matches the description of #6212 on nixos today.

I have a number of containers hosting websites, and none of them are shut down gracefully when I shut the host down. I must wait for the 90-second systemd timeout, and see them forcibly shut down. The mysql database in one container doesn't seem to enjoy this.

If I shut down a container manually, via `nixos-container stop containerName`, it works flawlessly. But somehow this is not triggered when I shut down the host.

**To Reproduce**

There are details, but the meat and potatoes is that I have some containers defined in my `configuration.nix`, and then try to reboot my host with `reboot`.

**Additional context**

My containers reside on ZFS filesystems? That's all I can think of.

**Notify maintainers**

@adisbladis 
@zowoq 
@saschagrunert 

**Metadata**

```
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.19, NixOS, 21.03.git.b3616bd9640M (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/nixpkgs`
```

### PR DESCRIPTION
**Pull request by pennae**
###### Motivation for this change

fix #109695 (containers don't stop properly during system shutdown). supersedes #120636.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
This LGTM in general, but can we add a simply invocation of stopping a container to one of our VM tests, to keep testing this, and ensure it doesn't regress anymore?

**Comment by pennae** [comment]
sure! added tests for early/no-machined stop to containers-declarative.nix

**Comment by flokli** [comment]
Lovely! Thanks! Let's get some more eyes on this, but LGTM.

**Comment by arianvp** [comment]
Looks good to me. SIGRTMIN+3 handling is indeed something we want when we run systems inside the nspawn container.

**Review by arianvp — APPROVED** [review]

**Pull request merged**
