### PR TITLE
delly: 0.8.2 -> 0.8.5

### PR DESCRIPTION
**Pull request by jbedo**
###### Motivation for this change

New release of delly.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jbedo** [comment]
@scalavision

**Comment by scalavision** [comment]
Thank you @jbedo !

This looks good to me :-)

I don't have merge privileges, but at least I will test it out this afternoon.

**Review by scalavision — APPROVED** [review]

**Comment by scalavision** [comment]
I run through a whole genome bam file, it resulted in 30k+ lines. I will benchmark against gold standard tomorrow, I think however, that this can be merged already.

**Review by scalavision — CHANGES_REQUESTED** [review]
Seems the license has changed from gpl3 to bsd2, @jbedo , could you update this as well?

https://github.com/dellytools/delly/commit/06f0b0cf6f1301ec23b67fe36107541d7ce5ccdf#diff-04c6e90faac2675aa89e2176d2eec7d8R12

**Comment by jbedo** [comment]
Oops, completely missed the license change!

**Review by scalavision — CHANGES_REQUESTED** [review]
Hm... I think it is actually BSD3 isn't it, not mit? If you can change to bsd3 it would be nice :-)

**Comment by jbedo** [comment]
> Hm... I think it is actually BSD3 isn't it, not mit? If you can change to bsd3 it would be nice :-)

Not sure how I got that wrong, I meant to write bsd3.

**Review by scalavision — APPROVED** [review]
Nice! Thanks :-)

**Comment by scalavision** [comment]
@ryantm could you have a look at this one? As far as I can tell everything is ok. I have also tested running the tool locally.

**Comment by ryantm** [comment]
Result of `nixpkgs-review pr 99128` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- delly
</details>

**Pull request merged**
