### PR TITLE
desed: 1.2.1-unstable-2024-09-06 -> 1.2.2

### PR DESCRIPTION
**Pull request by a-kenji**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by vinylen — APPROVED** [review]
Thanks for this! I'm not familiar with nix-update-script but looks interesting!

**Comment by a-kenji** [comment]
The documentation for `nix-update-script` is [here](https://github.com/NixOS/nixpkgs/tree/master/pkgs#automatic-package-updates).

Basically it allows for automatic package bumps.

Since you are the maintainer and the package is under `pkgs/by-name/` you are able to then [request a merge](https://github.com/NixOS/nixpkgs/blob/746cf3d0e76c1bc57d4be5e1397b07fabad54bf6/CONTRIBUTING.md#how-to-merge-pull-requests-yourself) from the `nixpkgs-merge-bot`.

**Review by vinylen — APPROVED** [review]

**Comment by vinylen** [comment]
@NixOS/nixpkgs-merge-bot merge

**Comment by a-kenji** [comment]
@vinylen, 
Apologies maybe I was unclear :).

Once ryantm opens a pr triggered by the `nix-update` script you are then able as a package maintainer to request merge by the merge bot.

But you already found the right command, so for the next time you are ready now :+1: .

**Comment by vinylen** [comment]
Ah i see that makes sense. Thank you for your patience 😅

**Comment by vcunat** [comment]
Still pretty bad on Hydra, never close to success so far:
https://hydra.nixos.org/job/nixpkgs/trunk/desed.x86_64-linux/all

**Comment by vcunat** [comment]
You know, ofBorg showed the same error, too (at a glance).

**Comment by a-kenji** [comment]
Ah, thank you for the notification @vcunat!
I think I know how the error happened.
#351866 should address the issue.

**Pull request merged**
