### PR TITLE
pari: 2.11.4 -> 2.13.1, update sage test expectations

### PR DESCRIPTION
**Pull request by collares**
###### Motivation for this change

Fixes #102699 without breaking Sage. We will wait until the Sage patch is upstreamed, though (see https://github.com/NixOS/nixpkgs/pull/122592#pullrequestreview-657112637).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg eval

**Comment by collares** [comment]
@timokau This the upstream ticket now has a `positive_review`. There are many options: wait for the next Sage beta, wait for the 21.05 branch to be cut, and so on. Let me know what you prefer :)

**Review by timokau — APPROVED** [review]
I think [positive review](https://trac.sagemath.org/ticket/30801#comment:141) and no new feedback for 7 days is good enough to get this into 20.05. Luckily we won't have to compromise between sage stability and a recent pari. I assume the "draft" status is only because the PR was dependent on the upstream ticket, so I'll ignore it.

The changes themselves look good. Thank you for staying on this.

**Comment by collares** [comment]
@timokau Thank you for caring deeply about Sage stability, and thank you for the review!

**Pull request merged**
