### PR TITLE
GNOME updates 2023-06-09 (staging)

### PR DESCRIPTION
**Pull request by bobby285271**
###### Description of changes

After 3 (?) release, at-spi2-core finally re-depends on systemd with meson flags we used...

###### Things done

- [x] Check what other distros are patching.
- [x] Briefly tested with system.replaceRuntimeDependencies.
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg test lightdm
@ofborg build glib gtk3 at-spi2-core

**Review by jtojnar — APPROVED** [review]
> After 3 (?) release, at-spi2-core finally re-depends on systemd with meson flags we used...

If I am reading the diff correctly, the changes are only relevant when explicit path for dbus-broker is not set.

The only problematic part was  the regression in 2.48.1, which broke it when built with support for both broker & daemon on broker-only systems (originally reported by Arch people in `#gnome-hackers` channel). And the subsequent breakage resulting from an attempted fix.

---

Other changes look good.

**Comment by bobby285271** [comment]
:man_shrugging: 2.48.2 actually does not build because we are under the case of `get_option('dbus_broker') != 'default'` and `get_option('default_bus') == 'dbus-daemon'`, so `dependency('libsystemd')` is not decalared

```
[129/292] Linking target bus/at-spi-bus-launcher
FAILED: bus/at-spi-bus-launcher 
gcc  -o bus/at-spi-bus-launcher bus/at-spi-bus-launcher.p/at-spi-bus-launcher.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /nix/store/wdqklc0xcyjz1v77fvnzydn6dphyaf20-glib-2.76.2/lib/libgio-2.0.so /nix/store/wdqklc0xcyjz1v77fvnzydn6dphyaf20-glib-2.76.2/lib/libgobject-2.0.so /nix/store/wdqklc0xcyjz1v77fvnzydn6dphyaf20-glib-2.76.2/lib/libglib-2.0.so /nix/store/5kkhv0vh2daa9fqrv2s9i3zmwhg7g1h7-libX11-1.8.4/lib/libX11.so /nix/store/ks4dlb95gmlziv3jgn8hfq7ay0gazprw-libXtst-1.2.3/lib/libXtst.so /nix/store/5hdjhhhpnzsvhincscy7j35r5gscsfpl-libXi-1.8/lib/libXi.so -Wl,--end-group
/nix/store/shw0b6wv2xdvyj71b1fj147i83awrqfz-binutils-2.40/bin/ld: bus/at-spi-bus-launcher.p/at-spi-bus-launcher.c.o: in function `ensure_a11y_bus.isra.0':
at-spi-bus-launcher.c:(.text+0xf43): undefined reference to `sd_pid_get_user_unit'
collect2: error: ld returned 1 exit status
```

**Comment by jtojnar** [comment]
Yeah, that is what I was referring to with “the subsequent breakage resulting from an attempted fix”.

**Pull request merged**
