### PR TITLE
opentofu: patch plugins to use opentofu plugin registry

### LINKED ISSUE #283015: opentofu: plugins not found due to missing registry override
### Describe the bug

`opentofu.withPlugins` still fails to override `registry.terraform.io` to `registry.opentofu.org`.
as a result of this, it will fail to find used plugins, searching in a nix store path containing `registry.terraform.io` rather than `registry.opentofu.org`.

### Steps To Reproduce
1. use `opentofu.withPlugins`
2. use a plugin in a `.tf`, e.g.:

    ```tf
    terraform {
      required_providers {
        nomad = {
          source = "hashicorp/nomad"
        }
      }
    }
    
    provider "nomad" {
      address = "http://127.0.0.1:4646"
    }
    ```

3. run `tofu init`
4. find error not unlike:

    ```
    │ Error: Failed to query available provider packages
    │ 
    │ Could not retrieve the list of available versions for provider hashicorp/nomad: provider registry.opentofu.org/hashicorp/nomad was not found in any of
    │ the search locations
    │ 
    │   - /nix/store/gaybr4b1wqlkfyppd0bnb0qwszki3az5-opentofu-1.6.0-rc1/libexec/terraform-providers
    ```

### Expected behavior
plugins work using opentofu as well

### Screenshots
-

### Additional context

- note this technically applies to both `withPlugins` as well as its derivatives like `full` and `passthru`.
- while a workaround might be [patching this](https://github.com/NixOS/nixpkgs/compare/master...KiaraGrouwstra:nixpkgs:opentofu-plugins-from-tofu-registry) to straight-up override the plugin domains, it would be nice to get a proper solution here i.e. that would not break the plugins for terraform.

### Notify maintainers

@gmemstr
@nickcao
@zowoq

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0-zen2, NixOS, 24.05 (Uakari), 24.05.20240114.dd5621d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(kiara): `"home-manager"`
 - channels(root): `""`
 - nixpkgs: `/nix/store/sl31dgnpwinzvzhh7ak2rx3h6w7kbb30-source`
```

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**
Patch `opentofu`'s plugins so as to use its own registry, rather than Terraform's, as per @yajo's comment at https://github.com/NixOS/nixpkgs/issues/283015#issuecomment-2009610478.

closes #283015.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — APPROVED** [review]
thank you for this change @KiaraGrouwstra! sorry for the delay on review as it resulted in a merge conflict, but i will be happy to merge once resolved

**Comment by KiaraGrouwstra** [comment]
@aanderse thanks! i rebased it now ✌️

**Comment by KiaraGrouwstra** [comment]
@mjm hm, i'm not sure how to proceed to fix that - pinging maintainers @nickcao @zowoq as well.

**Comment by mjm** [comment]
I think I've got a fix, will open a PR.

**Comment by zowoq** [comment]
This broke the passthru.test.

**Comment by KiaraGrouwstra** [comment]
@zowoq how might i run that to reproduce?

**Comment by zowoq** [comment]
`nix-build -A opentofu.tests.opentofu_plugins_test`

https://logs.ofborg.org/?key=nixos/nixpkgs.358522&attempt_id=c5800818-2dba-43f2-8519-47fd392397e5

**Comment by aanderse** [comment]
sorry for the mistake @zowoq, thanks for pointing it out... and thanks for fixing @KiaraGrouwstra!

**Pull request merged**
