### PR TITLE
swig: 3.0.7 -> 3.0.10

### PR DESCRIPTION
**Pull request by leenaars**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rasendubi** [comment]
@leenaars, the Travis has failed with segfault during build of swig. Could you take a look?

**Comment by globin** [comment]
Travis passed now

**Comment by bjornfor** [comment]
It breaks nixos-rebuild on 64-bit systems:

```
$ sudo nixos-rebuild -I nixpkgs=. test
...
error: Package ‘swig-3.0.10’ in ‘/home/bfo/proj/code/forks/nixpkgs/pkgs/development/tools/misc/swig/3.x.nix:27’ is not supported on ‘x86_64-linux’, refusing to evaluate.
```

**Comment by bjornfor** [comment]
Fixed: d5c27859b45a1a6743e2b901b9d40b48e6f810ec.

**Pull request merged**
