### PR TITLE
radare2: 5.7.2 -> 5.7.8

### PR DESCRIPTION
**Pull request by azahi**
###### Description of changes

This also fixes and issue with `lib_r` version not being properly exported (required for Iaito).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by azahi** [comment]
I'm also planning to switch the build system to Meson (as recommended by upstream) in a separate PR in the near future.

**Comment by azahi** [comment]
Looks like linking is [failing](https://logs.nix.ci/?key=nixos/nixpkgs.200595&attempt_id=ed931d37-b3c7-4b66-8a93-eeefa53685aa) on Darwin and it seems like it was failing already. I can mark it as broken or maybe someone with an access to MacOS could find a fix to that.

**Review by anthonyroussel — APPROVED** [review]
Result of `nixpkgs-review pr 200595` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
5 packages built:
</summary>
<ul>
<li>diffoscope</li>
<li>iaito</li>
<li>python310Packages.r2pipe</li>
<li>python39Packages.r2pipe</li>
<li>radare2</li>
</ul>
</details>

**Review by trofi — APPROVED** [review]

**Comment by Mic92** [comment]
Some years ago I switched it from meson to make because this would fix the cross compilation, but maybe this is no longer an issue

**Comment by Mic92** [comment]
I switched to meson which fixed the macOS build.

**Comment by Mic92** [comment]
@ofborg build radare2

**Review by Mic92 — APPROVED** [review]

**Pull request merged**
