### PR TITLE
[20.09] undervolt: expose power limits as Nixopts

### PR DESCRIPTION
**Pull request by Atemu**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/95011#issuecomment-719503542

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by bennyandresen — APPROVED** [review]
LGTM.
And this change is already in master.

/status needs_merger

**Comment by Atemu** [comment]
> And this change is already in master.

What do you mean by that?

**Comment by bennyandresen** [comment]
> > And this change is already in master.
> 
> What do you mean by that?

I reviewed this before I realized it was a backport and it looked good to me.
Then saw that it's already in nixos-unstable (=master) and already received discussion before.

Conclusion: I'm good with this change and would merge it.

**Comment by Atemu** [comment]
Oh sorry, I confused this PR with my other one you reviewed haha. \^\^

**Comment by timokau** [comment]
> I reviewed this before I realized it was a backport and it looked good to me.

It is a convention (I'm not sure if its documented anywhere, but I do it and I have seen others do it too) to prefix backport PR titles with the release they are targeting. That helps to avoid that confusion.

**Review by timokau — APPROVED** [review]
Thanks! I don't see any reason against this backport, and our release managers are probably overworked. So let's just get this in :)

**Pull request merged**
