### PR TITLE
coq-elpi: 1.10.1 -> 1.10.2

### PR DESCRIPTION
**Pull request by gares**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gares** [comment]
@GrahamcOfBorg build coqPackages_8_13.coq-elpi coqPackages_8_13.hierarchy-builder

**Comment by gares** [comment]
@GrahamcOfBorg build coqPackages_8_13.coq-elpi coqPackages_8_13.hierarchy-builder

**Comment by gares** [comment]
We may need to update HB at the same time

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 126587` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>coqPackages.hierarchy-builder</li>
    <li>coqPackages.mathcomp-analysis</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>coqPackages.coq-elpi</li>
  </ul>
</details>

**Comment by siraben** [comment]
```
$ nix log /nix/store/mz5w8hsy72cx78wwl6vjm8h9k5q5b0q2-coq8.13-hierarchy-builder-1.1.0.drv | ix
http://ix.io/3uLY
```

**Comment by gares** [comment]
We need to synchronise @CohenCyril

**Comment by siraben** [comment]
Note that on master I have updated hierarchy-builder to 1.1.0, so this needs rebasing.

**Comment by CohenCyril** [comment]
@GrahamcOfBorg build coqPackages_8_13.coq-elpi coqPackages_8_13.hierarchy-builder

**Pull request closed without merging**
