### PR TITLE
box86: init at 0.2.6

### PR DESCRIPTION
**Pull request by gador**
###### Description of changes

Init of Box86, analog to #173987

Testing doesn't work for me, since I don't have 32bit (ARM) hardware. 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
  - [ ] i686-linux
  - [ ] armv7l-linux <-- Needs testing
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 174113` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>box86</li>
  </ul>
</details>

**Comment by misuzu** [comment]
It kinda works:
```bash
$ file /nix/store/nd9cygzqn4vr5jr2sznajz698i5r13mi-box86-0.2.6/bin/box86
/nix/store/nd9cygzqn4vr5jr2sznajz698i5r13mi-box86-0.2.6/bin/box86: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /nix/store/f3kxgygcywqzxfkh7azpm4nfcy0aldyl-glibc-2.34-210/lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, not stripped
$ /nix/store/nd9cygzqn4vr5jr2sznajz698i5r13mi-box86-0.2.6/bin/box86 $(nix-build '<nixpkgs>' -A pkgs.coreutils --system i686-linux --no-out-link)/bin/echo test
Box86 with Dynarec v0.2.6 nogit built on Jan  1 1980 00:00:00
Error: PltResolver: Symbol __prctl_time64(ver 2: __prctl_time64@GLIBC_2.34) not found, cannot apply R_386_JMP_SLOT 0x821ea50 (0x804d036) in /nix/store/436zxq4ics2mmxfh4iswj2lf6bpjabxr-coreutils-9.0/bin/echo
```

**Comment by davidak** [comment]
@misuzu thanks. can you also test the other tools that worked here: https://github.com/ptitSeb/box64/issues/311

or even try a game from this list https://box86.org/app/

that issue might be expected

**Comment by misuzu** [comment]
`hello` doesn't work 🤔
```bash
$ /nix/store/nd9cygzqn4vr5jr2sznajz698i5r13mi-box86-0.2.6/bin/box86 $(nix-build '<nixpkgs>' -A pkgs.hello --system i686-linux --no-out-link)/bin/hello
Box86 with Dynarec v0.2.6 nogit built on Jan  1 1980 00:00:00
$ /nix/store/nd9cygzqn4vr5jr2sznajz698i5r13mi-box86-0.2.6/bin/box86 $(nix-build '<nixpkgs>' -A pkgs.coreutils --system i686-linux --no-out-link)/bin/uptime
Box86 with Dynarec v0.2.6 nogit built on Jan  1 1980 00:00:00
Error: PltResolver: Symbol __prctl_time64(ver 2: __prctl_time64@GLIBC_2.34) not found, cannot apply R_386_JMP_SLOT 0x821ea50 (0x804d036) in /nix/store/436zxq4ics2mmxfh4iswj2lf6bpjabxr-coreutils-9.0/bin/uptime
$ /nix/store/nd9cygzqn4vr5jr2sznajz698i5r13mi-box86-0.2.6/bin/box86 $(nix-build '<nixpkgs>' -A pkgs.coreutils --system i686-linux --no-out-link)/bin/who
Box86 with Dynarec v0.2.6 nogit built on Jan  1 1980 00:00:00
Error: PltResolver: Symbol __prctl_time64(ver 2: __prctl_time64@GLIBC_2.34) not found, cannot apply R_386_JMP_SLOT 0x821ea50 (0x804d036) in /nix/store/436zxq4ics2mmxfh4iswj2lf6bpjabxr-coreutils-9.0/bin/who
$ /nix/store/nd9cygzqn4vr5jr2sznajz698i5r13mi-box86-0.2.6/bin/box86 $(nix-build '<nixpkgs>' -A pkgs.coreutils --system i686-linux --no-out-link)/bin/mktemp
Box86 with Dynarec v0.2.6 nogit built on Jan  1 1980 00:00:00
Error: PltResolver: Symbol __prctl_time64(ver 2: __prctl_time64@GLIBC_2.34) not found, cannot apply R_386_JMP_SLOT 0x821ea50 (0x804d036) in /nix/store/436zxq4ics2mmxfh4iswj2lf6bpjabxr-coreutils-9.0/bin/mktemp
$ /nix/store/nd9cygzqn4vr5jr2sznajz698i5r13mi-box86-0.2.6/bin/box86 $(nix-build '<nixpkgs>' -A pkgs.coreutils --system i686-linux --no-out-link)/bin/uname -a
Box86 with Dynarec v0.2.6 nogit built on Jan  1 1980 00:00:00
Error: PltResolver: Symbol __prctl_time64(ver 2: __prctl_time64@GLIBC_2.34) not found, cannot apply R_386_JMP_SLOT 0x821ea50 (0x804d036) in /nix/store/436zxq4ics2mmxfh4iswj2lf6bpjabxr-coreutils-9.0/bin/uname
$ /nix/store/nd9cygzqn4vr5jr2sznajz698i5r13mi-box86-0.2.6/bin/box86 $(nix-build '<nixpkgs>' -A pkgs.coreutils --system i686-linux --no-out-link)/bin/whoami
Box86 with Dynarec v0.2.6 nogit built on Jan  1 1980 00:00:00
Error: PltResolver: Symbol __prctl_time64(ver 2: __prctl_time64@GLIBC_2.34) not found, cannot apply R_386_JMP_SLOT 0x821ea50 (0x804d036) in /nix/store/436zxq4ics2mmxfh4iswj2lf6bpjabxr-coreutils-9.0/bin/whoami
```

**Comment by davidak** [comment]
That might be still all expected. It is not intended to run CLI programs, but games.

**Comment by misuzu** [comment]
Unfortunately I don't have graphics on my arm machine to test games.

**Comment by onny** [comment]
@ofborg build box86

**Comment by arbv** [comment]
Are there any chances for this to be merged?

**Comment by davidak** [comment]
@arbv i think the status was that the package needs more testing.

Could you test if it works for your use-case?

**Comment by arbv** [comment]
@davidak I do not have a non-headless board for this purpose right now. I intended to get one at some point and am checking if NixOS has everything I need in the repos and stumbled upon this.

**Comment by arbv** [comment]
@misuzu  As as side note I believe that box86 needs to use 32-bit libraries (ARMv7) even when it runs on a 64-bit host (Aarch64). (As it enables running 32-bit x86 programs). That is, I think that one needs to add a 32-bit version of nixpkkgs on a 64-bit system and install the package from there.

**Comment by misuzu** [comment]
> That is, I think that one needs to add a 32-bit version of nixpkkgs on a 64-bit system and install the package from there.

That's exactly how it was tested, look closer to the used commands.

jfyi armv7l is not really supported right now

**Comment by Yeshey** [comment]
Hey, I'm not super proficient in nixOS, and I'm still wrapping my head around box86 and box64, but I'm interested in seeing this work

I only have a `aarch64-linux` server and a `x86_64` PC, not a `armv7l-linux` machine.   
I only managed to build this for my `x86_64` PC by changing `stdenv` to `gccMultiStdenv`, otherwise I'd get this error:
```nix
CMake Error at /nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/nix/store/9bv7dcvmfcjnmg5mnqwqlq2wxfn8d7yi-gcc-wrapper-13.2.0/bin/gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/build/source/build/CMakeFiles/CMakeScratch/TryCompile-pLy4Zu'
    
    Run Build Command(s): /nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -E env VERBOSE=1 /nix/store/cdzpn0rdq810aknww3w9fy3wmw9ixr66-gnumake-4.4.1/bin/make -f Makefile cmTC_a699d/fast
    /nix/store/cdzpn0rdq810aknww3w9fy3wmw9ixr66-gnumake-4.4.1/bin/make  -f CMakeFiles/cmTC_a699d.dir/build.make CMakeFiles/cmTC_a699d.dir/build
    make[1]: Entering directory '/build/source/build/CMakeFiles/CMakeScratch/TryCompile-pLy4Zu'
    Building C object CMakeFiles/cmTC_a699d.dir/testCCompiler.c.o
    /nix/store/9bv7dcvmfcjnmg5mnqwqlq2wxfn8d7yi-gcc-wrapper-13.2.0/bin/gcc   "-m32"  -o CMakeFiles/cmTC_a699d.dir/testCCompiler.c.o -c /build/source/build/CMakeFiles/CMakeScratch/TryCompile-pLy4Zu/testCCompiler.c
    Linking C executable cmTC_a699d
    /nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a699d.dir/link.txt --verbose=1
    /nix/store/9bv7dcvmfcjnmg5mnqwqlq2wxfn8d7yi-gcc-wrapper-13.2.0/bin/gcc "-m32"  CMakeFiles/cmTC_a699d.dir/testCCompiler.c.o -o cmTC_a699d
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/14c6s4xzhy14i2b05s00rjns2j93gzz4-gcc-13.2.0/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/libgcc.a when searching for -lgcc
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/14c6s4xzhy14i2b05s00rjns2j93gzz4-gcc-13.2.0/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/libgcc.a when searching for -lgcc
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: cannot find -lgcc: No such file or directory
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: cannot find libgcc_s.so.1: No such file or directory
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/14c6s4xzhy14i2b05s00rjns2j93gzz4-gcc-13.2.0/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/libgcc.a when searching for -lgcc
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: skipping incompatible /nix/store/14c6s4xzhy14i2b05s00rjns2j93gzz4-gcc-13.2.0/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/libgcc.a when searching for -lgcc
    /nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin/ld: cannot find -lgcc: No such file or directory
    collect2: error: ld returned 1 exit status
    make[1]: *** [CMakeFiles/cmTC_a699d.dir/build.make:99: cmTC_a699d] Error 1
    make[1]: Leaving directory '/build/source/build/CMakeFiles/CMakeScratch/TryCompile-pLy4Zu'
    make: *** [Makefile:127: cmTC_a699d/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:92 (project)


-- Configuring incomplete, errors occurred!
```

As far as I understand it should only prove useful in arm, for it to compile in my `aarch64-linux` I had to use:
```nix
let
  crossPkgs = pkgsCross.armv7l-hf-multiplatform;
in
crossPkgs.stdenv.mkDerivation rec {
[...]
  cmakeFlags = [
    "-DNOGIT=1"
    "-DARM_DYNAREC=ON"
  ];
[...]
```

and it compiled, I'm worried this might be the wrong approach as the discussion seems to imply I'd need a `armv7l-linux` machine or emulation, maybe it's grabbing some pre-built stuff from one of my [substituters](https://github.com/Yeshey/nixOS-Config/blob/main/modules/nixos/mySystem/default.nix)? But it is able to run all the programs @davidak could run with box84 [here](https://github.com/ptitSeb/box64/issues/311), and fail a lot of the same ones:
```sh
# in x86 PC
> nix build -f "<nixpkgs>" --argstr system "i686-linux" coreutils
> ll
total 1
lrwxrwxrwx 1 root root 57 jun  4 03:52 result -> /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5
> nix copy --to ssh://root@10.0.10.238 /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5

# in aarch64 server
# what works
[yeshey@nixos-skyloft:~]$ box86 /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5/bin/echo test
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Error initializing native libgmp.so.10 (last dlerror is libgmp.so.10: cannot open shared object file: No such file or directory)
test

[yeshey@nixos-skyloft:~]$ box86 /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5/bin/uname -a
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Error initializing native libgmp.so.10 (last dlerror is libgmp.so.10: cannot open shared object file: No such file or directory)
Linux nixos-skyloft 6.6.32 #1-NixOS SMP Sat May 25 14:22:56 UTC 2024 i686 GNU/Linux

[yeshey@nixos-skyloft:~]$ uname -a
Linux nixos-skyloft 6.6.32 #1-NixOS SMP Sat May 25 14:22:56 UTC 2024 aarch64 GNU/Linux

[yeshey@nixos-skyloft:~]$ box86 /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5/bin/whoami
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Error initializing native libgmp.so.10 (last dlerror is libgmp.so.10: cannot open shared object file: No such file or directory)
yeshey

# what doesnt work

[yeshey@nixos-skyloft:~]$ box86 /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5/bin/uptime
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Error initializing native libgmp.so.10 (last dlerror is libgmp.so.10: cannot open shared object file: No such file or directory)
Error: PltResolver: Symbol utmpxname(ver 4: utmpxname@GLIBC_2.1) not found, cannot apply R_386_JMP_SLOT 0x81c6c54 (0x804db26) in /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5/bin/coreutils

[yeshey@nixos-skyloft:~]$ box86 /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5/bin/who
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Error initializing native libgmp.so.10 (last dlerror is libgmp.so.10: cannot open shared object file: No such file or directory)
Error: PltResolver: Symbol utmpxname(ver 4: utmpxname@GLIBC_2.1) not found, cannot apply R_386_JMP_SLOT 0x81c6c54 (0x804db26) in /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5/bin/coreutils

[yeshey@nixos-skyloft:~]$ box86 /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5/bin/mktemp
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Error initializing native libgmp.so.10 (last dlerror is libgmp.so.10: cannot open shared object file: No such file or directory)
Error: PltResolver: Symbol __mempcpy_chk(ver 7: __mempcpy_chk@GLIBC_2.3.4) not found, cannot apply R_386_JMP_SLOT 0x81c69f4 (0x804d1a6) in /nix/store/dm0wz420s9n1nbp3731y9iqya0zswyy8-coreutils-9.5/bin/coreutils
```

I also tried to run `vectoroids` but couldn't
```nix
> nix build -f "<nixpkgs>" --argstr system "i686-linux" vectoroids
> ll
total 1
lrwxrwxrwx 1 root root 60 jun  4 04:16 result -> /nix/store/v6d358nsnd16xf9hshvmq2pgn4frayyv-vectoroids-1.1.0
> nix copy --to ssh://root@143.47.53.175 /nix/store/v6d358nsnd16xf9hshvmq2pgn4frayyv-vectoroids-1.1.0
```
in the server, connecting with freerdp to get a Graphical Interface:
image


I'm also changed to using version 0.3.6 of box86 for my tests.
I'll be trying to see if I need to make a chroot or some other way to get it to work, they have a list of libraries wrapped or not [here](https://box86.org/2022/02/box86-box64-are-easy-to-use/), and will report back if I find out anything.

**Comment by Yeshey** [comment]
with @OPNA2608's [comment](https://github.com/NixOS/nixpkgs/pull/173987#issuecomment-1134330893) in the box64 merge request I tried to run `vectoroids` with box86:
```bash
# Fetch target game
nix build -f "<nixpkgs>" --argstr system "i686-linux" vectoroids
mv result vectoroids

# Fetch & expose native libraries for game
for lib in SDL SDL_image SDL_mixer; do
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}${LD_LIBRARY_PATH:+:}$(nix-build "<nixpkgs>" --no-out-link -A $lib)/lib"
done

box86 ./vectoroids/bin/vectoroids
```

but no luck
```bash
zsh ❯ box86 ./vectoroids/bin/vectoroids                                                                                             02:20:39
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Error initializing native libSDL-1.2.so.0 (last dlerror is libSDL-1.2.so.0: wrong ELF class: ELFCLASS64)
Error initializing native libSDL_mixer-1.2.so.0 (last dlerror is libSDL_mixer-1.2.so.0: wrong ELF class: ELFCLASS64)
Error initializing native libSDL_image-1.2.so.0 (last dlerror is libSDL_image-1.2.so.0: wrong ELF class: ELFCLASS64)
Error initializing native libX11.so.6 (last dlerror is libX11.so.6: cannot open shared object file: No such file or directory)
Error initializing native libXext.so.6 (last dlerror is libXext.so.6: cannot open shared object file: No such file or directory)
Error initializing native libXrandr.so.2 (last dlerror is libXrandr.so.2: cannot open shared object file: No such file or directory)
Error initializing native libXrender.so.1 (last dlerror is libXrender.so.1: cannot open shared object file: No such file or directory)
Error initializing native libxcb.so.1 (last dlerror is libxcb.so.1: cannot open shared object file: No such file or directory)
Error initializing native libXau.so.6 (last dlerror is libXau.so.6: cannot open shared object file: No such file or directory)
Error initializing native libXdmcp.so.6 (last dlerror is libXdmcp.so.6: cannot open shared object file: No such file or directory)
Error initializing native libpulse-simple.so.0 (last dlerror is libpulse-simple.so.0: cannot open shared object file: No such file or directory)
Error initializing native libpulse.so.0 (last dlerror is libpulse.so.0: cannot open shared object file: No such file or directory)
Error initializing native libvorbisfile.so.3 (last dlerror is libvorbisfile.so.3: cannot open shared object file: No such file or directory)
Error initializing native libvorbis.so.0 (last dlerror is libvorbis.so.0: cannot open shared object file: No such file or directory)
Error initializing native libogg.so.0 (last dlerror is libogg.so.0: cannot open shared object file: No such file or directory)
Error initializing native libsmpeg-0.4.so.0 (last dlerror is libsmpeg-0.4.so.0: cannot open shared object file: No such file or directory)
Error initializing native libasound.so.2 (last dlerror is libasound.so.2: cannot open shared object file: No such file or directory)
Error initializing native libdbus-1.so.3 (last dlerror is libdbus-1.so.3: cannot open shared object file: No such file or directory)
Error initializing native libsndfile.so.1 (last dlerror is libsndfile.so.1: cannot open shared object file: No such file or directory)
Error initializing native libmpg123.so.0 (last dlerror is libmpg123.so.0: cannot open shared object file: No such file or directory)
Error initializing native libcap.so.2 (last dlerror is libcap.so.2: cannot open shared object file: No such file or directory)
Error initializing native libglib-2.0.so.0 (last dlerror is libglib-2.0.so.0: cannot open shared object file: No such file or directory)
Error initializing native libgthread-2.0.so.0 (last dlerror is libgthread-2.0.so.0: cannot open shared object file: No such file or directory)
Error initializing native libpng16.so.16 (last dlerror is libpng16.so.16: cannot open shared object file: No such file or directory)
Error initializing native libjpeg.so.62 (last dlerror is libjpeg.so.8: cannot open shared object file: No such file or directory)
Error initializing native libz.so.1 (last dlerror is libz.so.1: cannot open shared object file: No such file or directory)
Error: PltResolver: Symbol __isoc23_strtoul(ver 3: __isoc23_strtoul@GLIBC_2.38) not found, cannot apply R_386_JMP_SLOT 0x60f2e008 (0x60f0b056) in /nix/store/9jj6c8b2ppib69pmx9pf51br2jplra0p-libxcb-1.17.0/lib/libxcb.so.1
```

if I build vectoroids for 64 bit
```bash
nix build -f "<nixpkgs>" --argstr system "x86_64-linux" vectoroids
```

and try to run with box86, it fails and launches with box64 instead:
```bash
❯ box86 ./vectoroids/bin/vectoroids
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Error: reading elf header of /nix/store/4s01xi2pxh6iqpdkrls96bx26zinfd2q-vectoroids-1.1.0/bin/vectoroids, trying to launch using box64 instead
[...]
```

**Comment by Yeshey** [comment]
setting the libraries with 
```bash
for lib in SDL SDL_image SDL_mixer; do
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}${LD_LIBRARY_PATH:+:}$(nix-build "<nixpkgs>" --no-out-link -A $lib)/lib"
done
```
seems to influence it, as it starts complaining about `wrong ELF class: ELFCLASS64`.

```bash
> BOX86_LOG=1 box86 $(nix-build '<nixpkgs>' -A pkgs.vectoroids --system i686-linux --no-out-link)/bin/vectoroids                                                                  05:22:10
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA AES PMULL PageSize:4096 Running on Neoverse-N1 with 4 Cores
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 105 Env var
Looking for /nix/store/v6d358nsnd16xf9hshvmq2pgn4frayyv-vectoroids-1.1.0/bin/vectoroids
Rename process to "vectoroids"
Error initializing native libSDL-1.2.so.0 (last dlerror is libSDL-1.2.so.0: cannot open shared object file: No such file or directory)
Using emulated /nix/store/larw11ibzfichszy5qq59g3x3lpbq7s1-SDL-1.2.15/lib/libSDL-1.2.so.0
Using native(wrapped) libpthread.so.0
Error initializing native libSDL_mixer-1.2.so.0 (last dlerror is libSDL_mixer-1.2.so.0: cannot open shared object file: No such file or directory)
Using emulated /nix/store/82dbpsa8r68z5zq5nq2c41x73j55l5ln-SDL_mixer-1.2.12/lib/libSDL_mixer-1.2.so.0
Error initializing native libSDL_image-1.2.so.0 (last dlerror is libSDL_image-1.2.so.0: cannot open shared object file: No such file or directory)
Using emulated /nix/store/78x0hzdk604nqnc51zzd8y1xx648xks7-SDL_image-1.2.12/lib/libSDL_image-1.2.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
[...]

> for lib in SDL SDL_image SDL_mixer; do                            
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}${LD_LIBRARY_PATH:+:}$(nix-build "<nixpkgs>" --no-out-link -A $lib)/lib"                               
done

> BOX86_LOG=1 box86 $(nix-build '<nixpkgs>' -A pkgs.vectoroids --system i686-linux --no-out-link)/bin/vectoroids                                                                                    05:23:23
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA AES PMULL PageSize:4096 Running on Neoverse-N1 with 4 Cores
Box86 with Dynarec v0.3.6 nogit built on Jan  1 1980 00:00:00
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 106 Env var
Looking for /nix/store/v6d358nsnd16xf9hshvmq2pgn4frayyv-vectoroids-1.1.0/bin/vectoroids
Rename process to "vectoroids"
Error initializing native libSDL-1.2.so.0 (last dlerror is libSDL-1.2.so.0: wrong ELF class: ELFCLASS64)
Using emulated /nix/store/larw11ibzfichszy5qq59g3x3lpbq7s1-SDL-1.2.15/lib/libSDL-1.2.so.0
Using native(wrapped) libpthread.so.0
Error initializing native libSDL_mixer-1.2.so.0 (last dlerror is libSDL_mixer-1.2.so.0: wrong ELF class: ELFCLASS64)
Using emulated /nix/store/82dbpsa8r68z5zq5nq2c41x73j55l5ln-SDL_mixer-1.2.12/lib/libSDL_mixer-1.2.so.0
Error initializing native libSDL_image-1.2.so.0 (last dlerror is libSDL_image-1.2.so.0: wrong ELF class: ELFCLASS64)
Using emulated /nix/store/78x0hzdk604nqnc51zzd8y1xx648xks7-SDL_image-1.2.12/lib/libSDL_image-1.2.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
[...]
```

this [should work without chroot](https://github.com/ptitSeb/box64/issues/311#issuecomment-1134207580), so  we just need to get the 32 bit arm libraries and point at them
This doesn't seem to work tho:
```bash
 for lib in SDL SDL_image SDL_mixer; do                                                                                                                                         
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}${LD_LIBRARY_PATH:+:}$(nix-build "<nixpkgs>" --argstr system "i686-linux" --no-out-link -A $lib)/lib"
done
```
Maybe [`BOX86_LD_LIBRARY_PATH`](https://ptitseb.github.io/box86/USAGE.html) should be used as well, but couldn't get it to do anything yet

**Comment by Yeshey** [comment]
> > `nix-build "<nixpkgs>" --argstr system "i686-linux" --no-out-link -A $lib`
> 
> You would need to use some 32-bit ARM system there, assuming you're building on a 64-bit ARM device. I.e. `armv7l-linux`.

yeah, [you're right](https://github.com/ptitSeb/box86#:~:text=You%20NEED%20a%2032%2Dbit%20subsystem%20to%20run%20and%20build%20Box86.%20Box86%20is%20useless%20on%2064%2Dbit%20only%20systems), copy that, thanks! But for what I see it can be used inside a 32bit chroot, and is even needed to run something like steam. I'm looking into creating a 32bit chroot now, perhaps with `nixos-container`. Trying to follow [this guide](https://github.com/Raezroth/Linux-ARM-Gaming-Chroot/blob/master/Docs/create-chroot.md) rn. Trying to understand what `dpkg --add-architecture armhf` does, and what the nixOS alternative would be for now
   
Something I also want to look into is using `systemd-binfmt` to make it automatically run the executables, ideally for me I would make a module that could change qemu emulation to box86/box64 emulation. I think [this](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/binfmt.nix) should be the relevant code that I'd have to look at in that case

Tangent aside, if this works and were to be merged, I'm also oblivious as to what would be the cross platform alternative to what I'm using rn to build `box86` in my `aarch64`
```nix
let
  crossPkgs = pkgsCross.armv7l-hf-multiplatform;
in
crossPkgs.stdenv.mkDerivation rec {
[...]
```

**Comment by Yeshey** [comment]
Finally got box86 to run vectoroids. So, box86 needs to be built with 32bit libraries and it uses 32bit arm libraries (or `armv7l-linux`) to run 32 bit x86 binaries (or `i686-linux`).

My x86 PC, with (`x86_64-linux`) can run 32 bit x86 code (`i686-linux`). My 64bit arm machine (or `aarch64-linux` machine), can also run 32bit arm code (`armv7l-linux`):
```bash
zsh ❯ zcat /proc/config.gz | grep CONFIG_COMPAT                                                     15:40:36

CONFIG_COMPAT=y
CONFIG_COMPAT_ALIGNMENT_FIXUPS=y
CONFIG_COMPAT_OLD_SIGACTION=y
CONFIG_COMPAT_32BIT_TIME=y
CONFIG_COMPAT_BINFMT_ELF=y
# CONFIG_COMPAT_BRK is not set
CONFIG_COMPAT_NETLINK_MESSAGES=y
```
Most aarch64 platforms can run 32bit code, but not all of them can.

It's because box86 needs a 32bit toolkit to be built that I had to use pkgsCross to build it in aarch64, and it will only run vectoroids for `i686-linux` platform, I got it to run like this:
```bash
# in my `x86_64-linux` PC:
> nix-build "<nixpkgs>" --argstr system "i686-linux" -A vectoroids # creates results folder 
> ll
lrwxrwxrwx - root  9 jun 14:36  result -> /nix/store/v6d358nsnd16xf9hshvmq2pgn4frayyv-vectoroids-1.1.0
> nix copy --to ssh://root@10.0.10.238 /nix/store/v6d358nsnd16xf9hshvmq2pgn4frayyv-vectoroids-1.1.0 # send the `i686-linux` vectoroids package to the aarch64 server

# in my `aarch64-linux` server
export LD_LIBRARY_PATH="$(for lib in SDL SDL_image SDL_mixer; do nix-build '<nixpkgs>' -A pkgsCross.armv7l-hf-multiplatform.${lib} --no-out-link; done | xargs -I {} echo -n {}/lib: | sed 's/:$//')"
BOX86_LOG=1 box86 /nix/store/v6d358nsnd16xf9hshvmq2pgn4frayyv-vectoroids-1.1.0/bin/vectoroids
```

image

**Pull request closed without merging**
