### PR TITLE
python310Packages.python-fsutil: Unmark broken on Darwin

### PR DESCRIPTION
**Pull request by tjni**
At least on my aarch64 Darwin machine, python-fsutil builds fine.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by viraptor** [comment]
Result of `nixpkgs-review pr 186338` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Review by viraptor — APPROVED** [review]
Builds, tests and imports on darwin intel too.

**Comment by risicle** [comment]
`nixpkgs-review` reveals no new failures on macos 10.15 & nixos x86_64

**Review by risicle — APPROVED** [review]

**Comment by risicle** [comment]
Might be worth seeing if it works on 22.05 too and doing the same there if so.

**Comment by tjni** [comment]
Good idea. My machine is building right now, so I cannot test at the moment. When I can, I will test this against the `release-22.05` branch. If it works, do I need special permissions to add the backport label?

**Comment by risicle** [comment]
Yup, you need to be a committer, but I can do it if you yell.

**Comment by tjni** [comment]
@risicle I built this locally against `release-22.05` and it succeeds on aarch64-darwin.

**Pull request merged**
