### PR TITLE
firefox 70

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

Firefox 70 is about to be released / has been released. 

This bump depends on a bump of nss, sqlite & rust-cbindgen.

I made a separate PR to drop the abuse of `RUSTC_BOOSTRAP=1` that has been merged into master already. Since this work depends on it I've included it here as well.

cc @vcunat @FRidh because they usually handle the staging workflow.

I targeted `staging-next` on purpose since this is likely to have a few Firefox security fixes (again). The reasoning for staging should be obvious. We have a pretty large rebuild due to `sqlite` and `nss` being touched.

I did build firefox on this branch and it looked fine for a while. I've not yet done intensive tests of the other things that will be rebuild in this branch. Usually the impact isn't that bad.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by volth** [comment]
BTW, shouldn't we de-cloudflare Firefox 70?
It has DNS-over-HTTP(s) enabled and set to cloudflare DNS servers without any fallback.
On NixOS we could set them to `config.networking.nameservers` or something less vendor locky

**Comment by andir** [comment]
> BTW, shouldn't we de-cloudflare Firefox 70?
> It has DNS-over-HTTP(s) enabled and set to cloudflare DNS servers without any fallback.
> On NixOS we could set them to `config.networking.nameservers` or something less vendor locky

I am absolutely in favor of that. I'd like to see an approach where we supply an enterprise policy that disables is.

**Comment by flokli** [comment]
Seems the other solutions documented [here](https://support.mozilla.org/en-US/kb/configuring-networks-disable-dns-over-https) (probing for a canary domain, `security.enterprise_roots.enabled`) don't really apply, so enterprice policies might be the way to configure this.

According to their docs, this could be accomplished by adding a `policies.json` file into a `distribution` folder below the "installation directory". I didn't `strace` yet where our firefox looks for it.

The appropriate policy would be `DNSOverHTTPS`, and an example json is documented here: https://github.com/mozilla/policy-templates/blob/master/README.md#dnsoverhttps

This also allows pointing to another DoH server, if sb. wanted to do that.

If we do this, we probably want to point firefox to look for that in the wrapper, so policies can be redefined without having to recompile `firefox-unwrapped`

**Comment by FRidh** [comment]
Changing to staging because its not uncommon to get regressions due to sqlite. 
(Note, however, that staging will anyway move to staging-next now so it won't matter...)

**Comment by vcunat** [comment]
> .mil-domains won't be resolved from Russia and Iran

For now, Firefox should only default to Cloudflare in "North America", besides displaying some opt-out dialogue, and the default resolver can prevent this anytime by blocking [a canary domain](https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet).  _At least that's what I remember from discussions in relevant IETF places; I haven't investigated details of the defaults._

I'm certainly not a fan of Mozilla choosing this weird combination of defaults, and we could disable that in nixpkgs somehow (perhaps later).  But in any case, the "war" is primarily about the masses who have no idea about DNS, and I don't think in _our_ case the default applies to that many people.

**Comment by volth** [comment]
BTW, even the IP addresses of Firefox's DoH server `mozilla.cloudflare-dns.com` are in Russian blacklist (
source https://ntc.party/t/esni-encrypted-sni/68/2),

**Pull request merged**
