### PR TITLE
buildLinux: Fix result derivation overriding with `passthru` via `stdenv.mkDerivation` instead of `lib.extendDerivation`

### LINKED ISSUE #111504: overrideAttrs on kernel derivation loses passthru values
**Describe the bug**

There is an oddity with how the kernel derivations react when `overrideAttrs` is used with them. Some `passthru` values are lost, namely `features` and `commonStructuredConfig`.

In turn, this makes customizing them harder than expected. These values are used in the NixOS modules.

**To Reproduce**

Using `overrideAttrs`, the `passthru` value given to the function does not hold all values found on the derivation's own passthru.

Details:

 - https://gist.github.com/samueldr/5cb327043a2f451edb5b38175eb07c73

``` nix
let
  kernel = pkgs.linux_latest;
  overriddenKernel = kernel.overrideAttrs({ passthru ? {}, ... }: {
    passthru = passthru // {
      world = "y'all";
    };
  });
in
  /* ok   */ assert kernel ? features;
  /* ok   */ assert kernel ? commonStructuredConfig;
  /* fail */ assert overriddenKernel ? features;
  /* fail */ assert overriddenKernel ? commonStructuredConfig;
```

**Expected behavior**

Values in `passthru` on the derivation should all be present in the `overrideAttrs` call.

**Workaround**

``` nix
let
  kernel = pkgs.linux_latest;
  overriddenKernel = kernel.overrideAttrs({ passthru ? {}, ... }: {
    passthru = kernel.passthru // { # <- use the derivation rather than the param
      world = "y'all";
    };
  });
in
```

**Additional context**

 - https://gist.github.com/samueldr/5cb327043a2f451edb5b38175eb07c73

And where I suspect this is coming from:

 - https://github.com/NixOS/nixpkgs/blob/21a2aebf314c385ac44c09492c76c31f846ae3e3/pkgs/os-specific/linux/kernel/generic.nix#L179-L187

This is can be observed against 891f607d5301d6730cb1f9dcf3618bcb1ab7f10e, and is an evaluation issue. No builds happened.

The linked gist contains a full reproduction.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by ShamrockLee**
## Description of changes

The `buildLinux` build helper currently relies on `lib.extendDerivation` to attach passthru attributes to each outputs. As `lib.extendDerivation` doesn't handle overriders correctly (#288148), the passthru arguments will be lost when overriding the kernel packages.

This PR fixes this issues by overriding the derivation returned by `manual-config.nix` with `<pkg>.overrideAttrs`, and update `passthru` to pass the attributes.

Aside from fixing the attribute-lost-after-overriding issue, this changes also enable the `passthru` attributes overriding with `<pkg>.overrideAttrs` and allow `passthru.tests` test cases to reference `finalAttrs.passthru.tests`.

This PR would conflict with #287659, but such conflict is trivial to resolve, and I'll do the rebase once any one of them gets merged.

Fixes: #111504
Previous attempt: #149455

## Things done

- Built on platform(s)
  - [X] x86_64-linux (no known rebuilds)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ShamrockLee** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by ShamrockLee** [comment]
@ofborg build linux linux.tests

**Review by infinisil — APPROVED** [review]
Tested this and it seems to be working well, nice job! And it's much nicer than by previous attempt :smile: 

For future reference, an example of what works now is testing kernel overrides like this:
```nix
(linuxPackages.kernel.overrideAttrs (old: {
  # Some changes
})).tests
```

**Comment by ShamrockLee** [comment]
Thank you @infinisil for testing and merging!

The fix utilize `finalAttrs.finalPackage` provided by #119942, which makes things much easier than the previous take.

**Pull request merged**
