### PR TITLE
ghost: init at 0.11.9

### PR DESCRIPTION
**Pull request by b123400**
###### Motivation for this change
Add [Ghost](https://ghost.org), the blogging platform to nixpkgs.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wit"` (New package, no dependent)
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

- I am new to here, not sure if I have structured the package in a good way🙏
- Description and long description are copied from Ghost's package.json and website, maybe there are some better descriptions that I didn't realise.

### CODE REVIEW

**Comment by joachifm** [comment]
The main problem here is the huge amount of stuff that'd need to be checked into the repository. Now, that's a failing of the tooling as far as I can tell, but even if it can't be helped it's still way too much, IMO.

**Comment by Mic92** [comment]
It would create a little bit less, if it was added to `./pkgs/development/node-packages/node-packages.json` instead.

**Comment by b123400** [comment]
OK, let me try to add it via node-packages.json. I thought it is ok because I saw [pump.io](https://github.com/NixOS/nixpkgs/tree/master/pkgs/servers/web-apps/pump.io) is doing something similar.

By the way, I think adding the module alone is not enough to make it usable. The ghost package only comes with the core part, it does not include any theme and the admin panel. To make it work, I have to run `grunt init` at the package level, what is the best practice of doing that? A new nix derivation that points to the generated node module, with a `buildPhase`?

**Comment by b123400** [comment]
Updated to use node-packages.json

**Comment by Mic92** [comment]
This project seems to use bower to download assets. We have this tool for that: https://github.com/rvl/bower2nix

**Comment by b123400** [comment]
Hello, sorry for the late follow up, have been busy for a while... After some trial and error, I think using `node-packages.json` might not be very suitable and decided to revert to the original approach. The reasons are:

- The existing build system of `ghost` is impure, for example it depends on codes from [other](https://github.com/TryGhost/Casper) [repositories](https://github.com/TryGhost/Ghost-Admin) has to be pulled as a submodule without tagging. To workaround this, patch of the build script is needed, which makes it more difficult to maintain.
- node2nix (which `node-packages.json` is depending on) is not enough to setup dependencies, the npm package "knex" looks for optional dependencies such as `mysql` and `pq` in runtime, and users are expected to install them manually. That does not work in the nix workflow because the dependency graph is generated.
- A pre-build zip file already exists, why not just use it, for its simplicity?
- I agree that this PR is big and hard to read every line, but using `node-packages.json` or `bower2nix` would also create a big diff, they won't make things better. If it helps, I can write a readme on how is the file generated.

**Comment by joachifm** [comment]
I still think 11K lines for a single package is way too much.

The repo is a commons, so there has to be a reasonable payoff for each line added. This proposal falls short of that by far. Consider that 20 package expressions of this size would add more lines than is required to describe the entire open source Haskell ecosystem (thousands of packages).

**Comment by b123400** [comment]
Right, this is big, but is there any way to make it smaller? If I use `node-packages.json`, I would need extra packages (devDependencies) to build it, which probably makes the diff even bigger.

**Comment by nbp** [comment]
If you cannot add it into Nixpkgs yet, maybe you can provide an overlay for it, such that others can follow this overlays updates, and potentially contribute back.

**Comment by disassembler** [comment]
I agree with @nbp. Please provide this in an overlay. I'm closing this out because of the concerns raised earlier.

**Pull request closed without merging**
