### PR TITLE
perl522: update darwin patch

### PR DESCRIPTION
**Pull request by sjourdois**

### CODE REVIEW

**Comment by copumpkin** [comment]
@domenkozar that's only a mass-rebuild on darwin, right?

**Comment by domenkozar** [comment]
yup

**Comment by domenkozar** [comment]
@pikajude feel free to cherry-pick this into staging

**Comment by zimbatm** [comment]
This was superseded by b8b8084682bf0b0ba3a0dbc86772ec54b82a41fb

**Pull request closed without merging**
