### PR TITLE
transmission: pin to openssl_1_1

### PR DESCRIPTION
**Pull request by pborzenkov**
###### Description of changes

The PR pins `openssl` in transmission to `openssl_1_1` as otherwise `transmission` segfaults almost immediately after start (upon trying to establish an encrypted connection).
1
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by collares** [comment]
@ofborg eval

**Review by collares — APPROVED** [review]
Can confirm this currently is a problem:

```
Thread 5 ".transmission-g" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdf7fe640 (LWP 75576)]
0x00007ffff69f4ce1 in EVP_CIPHER_CTX_set_key_length () from /nix/store/5nh3xmnx2lybwzl3p328q7b9rfh1ssyb-openssl-3.0.5/lib/libcrypto.so.3
(gdb) bt
#0  0x00007ffff69f4ce1 in EVP_CIPHER_CTX_set_key_length () from /nix/store/5nh3xmnx2lybwzl3p328q7b9rfh1ssyb-openssl-3.0.5/lib/libcrypto.so.3
#1  0x000000000047c1d4 in tr_rc4_set_key ()
#2  0x0000000000499561 in tr_cryptoEncryptInit ()
#3  0x000000000049a089 in canRead ()
#4  0x00000000004811bb in canReadWrapper ()
#5  0x00000000004a680f in UTP_ProcessIncoming(UTPSocket*, unsigned char const*, unsigned long, bool) ()
#6  0x00000000004a7510 in UTP_IsIncomingUTP ()
#7  0x0000000000465fab in tr_utpPacket ()
#8  0x0000000000465715 in event_callback ()
#9  0x00007ffff6f1b3c8 in event_process_active_single_queue () from /nix/store/c3a3v3ja9rv0byvmqvirzlyp6pch4dkn-libevent-2.1.12/lib/libevent-2.1.so.7
#10 0x00007ffff6f1bb17 in event_base_loop () from /nix/store/c3a3v3ja9rv0byvmqvirzlyp6pch4dkn-libevent-2.1.12/lib/libevent-2.1.so.7
#11 0x00000000004642e8 in libeventThreadFunc ()
#12 0x000000000044e308 in ThreadFunc ()
#13 0x00007ffff6488e86 in start_thread (arg=<optimized out>) at pthread_create.c:442
#14 0x00007ffff650fc60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

Pinning OpenSSL to version 1.1 fixes the crash as expected.

**Comment by McSinyx** [comment]
Is this a Transmission or OpenSSL bug?

**Comment by collares** [comment]
Neither, it is an interaction bug. RC4 is opt-in in OpenSSL 3.0 but Transmission assumes it is enabled by default.

**Review by LunNova — APPROVED** [review]

**Comment by LunNova** [comment]
Confirmed this workaround works on my machine.

**Review by vcunat — APPROVED** [review]
Thanks.

**Comment by vcunat** [comment]
The fix is a year old, and it seems rather unclear to me when the release might happen, at a quick glance :-/

**Pull request merged**
