### PR TITLE
Update quicklisp packages

### PR DESCRIPTION
**Pull request by SquircleSpace**
###### Motivation for this change
The lispPackages are a bit out of date.  Let's update them!

Also, quicklisp-to-nix fails to identify some dependencies (due to a bug in quicklisp).  This branch tries to work around that bug.

###### Things done

Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Nice workaround, I expected something worse would be needed. But I think `iolib/syscalls` gets listed but doesn't build because it needs `split-sequence` and thiis doesn't get detected for some reason (probably some transitivity catch, together with the entire question of `iolib` being a single tarball with many systems). Any ideas about further cheap workarounds? (Just adding an override seems to work).

**Comment by bradleyjensen** [comment]
I’m still iterating on this. I’ve figured out how to run the test builds the CI system does, so my next attempt should build before I push it.

I don’t think it’s possible to catch all dependencies automatically. Some quicklisp packages are pretty funky. I think I’ve maximized the number of automatically detectable dependencies. Now I’m trying to eliminate unnecessary overrides.

I notice that several quicklisp releases have multiple nix packages currently. I’d like to have one package per release and then, ideally, create aliases to that package for convenience. That way, there’s only one copy of each release in the nix store. Does that sound reasonable?

**Comment by 7c6f434c** [comment]
>I’m still iterating on this. I’ve figured out how to run the test builds the CI system does, so my next attempt should build before I push it.

Spoiler: `nix-build --no-out-link '<nixpkgs> -A lispPackages'` is good enough more often than not.

>I don’t think it’s possible to catch all dependencies automatically. Some quicklisp packages are pretty funky. I think I’ve maximized the number of automatically detectable dependencies. Now I’m trying to eliminate unnecessary overrides.

Well, booting a fresh image, loading Quicklisp and requiring a system does load some set of systems, so there could be a way to measure this dependency stuff. Just not sure how exactly to do this. Maybe spawning multiple fresh lisp images is needed, after all.

I have a suspicion that you current approach could be amplified by taking transitive closure (or recursive dependencies, or deps-of-deps-of-deps — whatever you prefer to call this, it's the same and it is sometimes annoying)

>I notice that several quicklisp releases have multiple nix packages currently. I’d like to have one package per release and then, ideally, create aliases to that package for convenience. That way, there’s only one copy of each release in the nix store. Does that sound reasonable?

Not sure: this can introduce circular dependencies, for example. For example, `cl-ppcre` and `cl-unicode`.

Thanks for your efforts!

**Comment by bradleyjensen** [comment]
Just giving a status update. I’m still working on this. I’m now trying to build packages in isolation and tracking which packages quicklisp installs (like 7c6f434c recommended), but some packages aren’t building. It looks like quicklisp’s handler-case that catches missing dependencies isn’t being respected. Still trying to figure it out.

**Comment by 7c6f434c** [comment]
Isn't the problem about non-Lisp dependencies? Maybe I should delay trying to think of a brute-force work-around for a bit, because it will probably be just too crazy.

**Comment by bradleyjensen** [comment]
In this instance, I don’t think so. I’m running in a nix-shell that has all the non-lisp dependencies available. I was able to run the original ql-to-nix in this shell without issue. I’m going to try a few more avenues of investigation, and if I can’t figure it out I’ll probably reach out for help.

**Comment by 7c6f434c** [comment]
Well, there is also an option of doing some overrides here and there and reporting bugs upstream (unless reported by someone else for other reaons, which does seem to happen with these dependency problems)

**Comment by 7c6f434c** [comment]
Hm, OK, change of plan. I think this is an improvement as-is, so I merge it and then override things manually and then apply the stuff I wanted to apply after this is merged.

Switching from ASDF dependencies to transitive ASDF dependencies seems to be a good idea, but can be done post-merge

`pgloader` seems to be already broken before merge, so this doesn't need to hold back the PR.

**Comment by bradleyjensen** [comment]
Alrighty. I think I’m getting very close to having reliable automatic dependency determination. I’ll open a new PR when I have it working.

**Pull request merged**
