### PR TITLE
clang: fix crosscompilation for 16.x

### PR DESCRIPTION
**Pull request by avnik**
###### Description of changes

Fix cross-compilation issue for clang 16.x (port existing fix from 15.x branch)

Closing #238432 
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] x86_64-linux.pkgsCross.aarch64-multiplatform
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
@ofborg build pkgsCross.aarch64-multiplatform.clang16

**Comment by avnik** [comment]
@ofborg https://github.com/ofborg build pkgsCross.aarch64-multiplatform.clang_16

**Comment by avnik** [comment]
fix ofborg mention, to match proper attribute

**Comment by rrbutani** [comment]
Ah, thanks; looks like we forgot to apply #226551 to `llvmPackages_16`.

Would you mind copying the [`stdenv.buildPlatform.canExecute` change](https://github.com/NixOS/nixpkgs/pull/226551/files#diff-aaa35d68512c62164bdfc12f65685eae233d764c393a88b9f438bae1fb596b05L39) from that PR as well? (It looks like we're not running into the `maybe-uninitialized` warning with LLVM 16 so we can leave that bit out)

**Comment by avnik** [comment]
@rrbutani  you about this snippet?
```
    env = lib.optionalAttrs (stdenv.buildPlatform != stdenv.hostPlatform) {
      # The following warning is triggered with (at least) gcc >=
      # 12, but appears to occur only for cross compiles.
      NIX_CFLAGS_COMPILE = "-Wno-maybe-uninitialized";
    };
```
In my setup it not failed, but I can add this fragment, if you feel it important.

**Comment by avnik** [comment]
Can confirm, that all rebuild successfully exactly on this commit:
```
 nix build ".#pkgsCross.aarch64-multiplatform.clang_16" -L --cores 24
 ```

**Review by rrbutani — APPROVED** [review]

**Comment by avnik** [comment]
@rrbutani  all done

**Review by rrbutani — APPROVED** [review]

**Comment by avnik** [comment]
@rrbutani Should I also PR this for stable branch?

**Comment by Artturin** [comment]
members can add labels

**Comment by sternenseemann** [comment]
Seems like `pkgsStatic.llvmPackages_15.clang-unwrapped` is still broken with trouble executing `clang-tblgen`. Seems it also doesn't work for 15, will need some investigation. It definitely used to work for `llvmPackages_11`.

**Pull request merged**
