### PR TITLE
lbry: 0.52.2 -> 0.52.4

### PR DESCRIPTION
**Pull request by MarekPasnikowski**
###### Motivation for this change

New upstream release.

[ LBRY GitHub Releases ]( https://github.com/lbryio/lbry-desktop/releases )

### CODE REVIEW

**Review by enderger — APPROVED** [review]

**Comment by Obikawa** [comment]
Is there a reason why this PR is not merged yet?

**Comment by enderger** [comment]
Not that I know of, I can’t merge PRs.

**Comment by Obikawa** [comment]
Thanks. Now I know that my assumption of `reviewer = write access` was wrong. I will exercise more patience.

**Comment by enderger** [comment]
I’ve requested review from someone with write permission.

**Comment by SuperSandro2000** [comment]
Merged. Yes, reviewers don't necessarily can merge things.

**Pull request merged**
