### PR TITLE
teleport_13: init at 13.3.8

### PR DESCRIPTION
**Pull request by justinas**
###### Description of changes

New major version.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Tchekda** [comment]
Teleport v14 went public this week. It would be great to have it too. 
I would love to help but I have no clue how this package is compiled

**Review by Tchekda — APPROVED** [review]
LGTM

**Comment by Tchekda** [comment]
> > Teleport v14 went public this week. It would be great to have it too. I would love to help but I have no clue how this package is compiled
> 
> Will add v14 as well once I get the chance.

Would be awesome. 

If you need maintainer review, maybe add the same maintainer that merged your previous teleport PR: arianvp ?

**Comment by TimoHocker** [comment]
Would be great to get this merged soon. All my nixos servers are now unreachable from teleport after upgrading my main server.

**Comment by justinas** [comment]
Sorry, forgot to close this one. This has already been obsoleted by https://github.com/NixOS/nixpkgs/pull/258943 . Teleport 13 & 14 are in nixos-unstable now.

**Pull request closed without merging**
