### PR TITLE
jekyll-favicon: init at 1.1.0

### LINKED ISSUE #198542: jekyll-favicon
**Project description**
>  Favicon generator and tag for Jekyll.

**Metadata**

* [homepage](https://afaundez.github.io/jekyll-favicon)
* [source](https://github.com/afaundez/jekyll-favicon)
* license: MIT
* platforms: Any

### PR DESCRIPTION
**Pull request by l0b0**
###### Description of changes

Closes #198542

> **Project description**
> >  Favicon generator and tag for Jekyll.
> 
> **Metadata**
> 
> * [homepage](https://afaundez.github.io/jekyll-favicon)
> * [source](https://github.com/afaundez/jekyll-favicon)
> * license: MIT
> * platforms: Any

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
I didn't notice this PR was targeting `staging`

**Comment by l0b0** [comment]
> I didn't notice this PR was targeting `staging`

Is that a problem? I thought new changes generally should target staging.

**Comment by marsam** [comment]
>Is that a problem? I thought new changes generally should target staging.

It's not a problem, sorry I didn't expand correctly.
I just thought this PR could have target `master` directly, since it's just a small number of rebuilds.
https://github.com/NixOS/rfcs/blob/master/rfcs/0026-staging-workflow.md

**Comment by l0b0** [comment]
@marsam Thank you for the explanation. Contributing to nixpkgs is *technically* the least painful experience I've had, but it's hard to learn about all the norms surrounding introducing changes.

**Pull request merged**
