### PR TITLE
pkgconfig: 0.29 -> 0.29.1

### PR DESCRIPTION
**Pull request by ndowens**
###### Motivation for this change
Update

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ndowens** [comment]
Have not tested with nox-review

**Comment by joachifm** [comment]
I expect it'd take a while to complete :) Changelog is here: https://lists.freedesktop.org/archives/pkg-config/2016-March/001043.html, doesn't look too scary.

**Comment by ndowens** [comment]
Nah, i get emails on some things that gets updated through fedora's release monitoring

**Comment by joachifm** [comment]
Should go via staging in any case, I think.

**Comment by globin** [comment]
Please rebase your commit on staging

**Comment by edolstra** [comment]
This PR contains 86 unrelated commits...

**Comment by vcunat** [comment]
That's just due to the switch of target branch (some commits from `staging..master`).

**Pull request closed without merging**
