### PR TITLE
dependabot: automatically update github actions

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by Mic92** [comment]
cc @zowoq 

same as in https://github.com/NixOS/nix/pull/3757

**Review by zowoq — APPROVED** [review]
👍

**Comment by lopsided98** [comment]
Unfortunately, it seems that this runs on forks as well. It appears that if the master branch of your fork contains this commit, your fork starts getting dependabot PRs, and I can't find a way to turn it off.

**Comment by lopsided98** [comment]
The documentation claims that it has to be manually enabled: https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-version-updates-on-forks

I'm certain I never manually enabled it, but it seems to be enabled anyway and there doesn't seem to be any way to disable it.

**Comment by zowoq** [comment]
@Mic92 We may want to disable this until we can restrict it to this repo so it isn't spamming forks.

cc @Ma27

**Comment by zowoq** [comment]
Upstream has an open issue about this: https://github.com/dependabot/dependabot-core/issues/2198

Dependabot is disabled by default for forks ... but sometimes it starts sending PRs anyway.

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/95055

**Pull request merged**
