### PR TITLE
dvc: remove setuptools_scm_git_archive pin, mark broken

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by anthonyroussel** [comment]
Result of `nixpkgs-review pr 185127` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>dvc</li>
    <li>dvc-with-remotes</li>
  </ul>
</details>

**Comment by anthonyroussel** [comment]
@SuperSandro2000 Hello!

FYI, I just saw that when I run `dvc init` on my x86_64-linux laptop, I have the following output:

```output
Traceback (most recent call last):
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/lib/python3.10/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/lib/python3.10/site-packages/dvc/cli/command.py", line 36, in do_run
    return self.run()
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/lib/python3.10/site-packages/dvc/commands/init.py", line 42, in run
    from dvc.repo import Repo
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/lib/python3.10/site-packages/dvc/repo/__init__.py", line 13, in <module>
    from dvc.ignore import DvcIgnoreFilter
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/lib/python3.10/site-packages/dvc/ignore.py", line 11, in <module>
    from dvc.fs import AnyFSPath, FileSystem, Schemes, localfs
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/lib/python3.10/site-packages/dvc/fs/__init__.py", line 33, in <module>
    from dvc_objects.fs.implementations.gdrive import GDriveAuthError  # noqa: F401
ImportError: cannot import name 'GDriveAuthError' from 'dvc_objects.fs.implementations.gdrive' (/nix/store/kzspjpsfk7cxbbaadzbnfc2rfd3il9cx-python3.10-dvc-objects-0.1.5/lib/python3.10/site-packages/dvc_objects/fs/implementations/gdrive.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/bin/.dvc-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/lib/python3.10/site-packages/dvc/cli/__init__.py", line 202, in main
    ret = _log_exceptions(exc) or 255
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/lib/python3.10/site-packages/dvc/cli/__init__.py", line 69, in _log_exceptions
    from dvc.fs import AuthError, ConfigError, RemoteMissingDepsError
  File "/nix/store/bhkgqn7flwd1y5zyssny0lsyixmpgwfm-dvc-2.12.0/lib/python3.10/site-packages/dvc/fs/__init__.py", line 33, in <module>
    from dvc_objects.fs.implementations.gdrive import GDriveAuthError  # noqa: F401
ImportError: cannot import name 'GDriveAuthError' from 'dvc_objects.fs.implementations.gdrive' (/nix/store/kzspjpsfk7cxbbaadzbnfc2rfd3il9cx-python3.10-dvc-objects-0.1.5/lib/python3.10/site-packages/dvc_objects/fs/implementations/gdrive.py)
```

**Comment by SuperSandro2000** [comment]
I am going to mark it broken since it is obviously not working right now. The update requires a new package which I don't want to package right now since I am not even using the package.

**Comment by anthonyroussel** [comment]
> I am going to mark it broken since it is obviously not working right now. The update requires a new package which I don't want to package right now since I am not even using the package. If someone wants to fix it feel tree to do that.

@SuperSandro2000 Hello!

No problem, I use `dvc` regularly so I will try to fix that issue and upgrade `dvc` in the next few days :)

**Comment by anthonyroussel** [comment]
PR to upgrade dvc to v2.17.0: https://github.com/NixOS/nixpkgs/pull/185703

**Pull request merged**
