### PR TITLE
gitlab: 12.5.5 -> 12.6.2

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
Update GitLab to the latest version.

Gitaly is problematic in this release for two reasons:
1. The version used in the `gitlab` repo is not tagged and as a result its commit id is used instead (reported [here](https://gitlab.com/gitlab-org/gitlab/issues/194206))
2. A new permission check on hook files checks for write permission when only read and execute are needed (reported [here](https://gitlab.com/gitlab-org/gitaly/issues/2305))

###### Things done

Tried a few things manually in a VM:
- Clone, commit and push to a repo
- Remove and add ssh keys, making sure the executable path referenced in `authorized_keys` is correct

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @flokli @globin @roblabla @fpletz @krav @petabyteboy

### CODE REVIEW

**Comment by talyz** [comment]
@GrahamcOfBorg test gitlab

**Comment by talyz** [comment]
Updated to latest security update.

@GrahamcOfBorg test gitlab

**Comment by flokli** [comment]
Updated to the latest security update.

**Comment by talyz** [comment]
The issues are reported; I've updated the description with links.

**Comment by flokli** [comment]
Merged - especially considering the security fixes, let's not delay this any further.

**Comment by flokli** [comment]
backported to 19.09 in dbc79093be0, 9fc0570071a, 18469aca5a6, 7ce433cf062, c93501dc786, fd7ce831d4b, 7201d239204.

**Pull request merged**
