### PR TITLE
pythonPackages.sagemaker: add pandas for analytical feature

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113978` at d39ff410 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/c9800ad4aee11dacd17cb451d8684ddb">python37Packages.sagemaker</a></li></li>
    <li><a href="https://gist.github.com/76fa7f7f7705712959d27e455d2824fd">python38Packages.sagemaker</a></li></li>
    <li><a href="https://gist.github.com/19c967b1ad25991394f07b4d83e0e7d1">python39Packages.sagemaker</a></li></li>
  </ul>
</details>

**Comment by FRidh** [comment]
Does it need to be present during build-time?

**Review by NeQuissimus — APPROVED** [review]

**Comment by NeQuissimus** [comment]
@FRidh The binary that is being wrapped needs it and some of the imports.

@SuperSandro2000 Maybe we can add this to ensure the binary works

```
  postFixup = ''
    [ "$($out/bin/sagemaker-upgrade-v2 --help 2>&1 | grep -cim1 'pandas failed to import')" -eq "0" ]
  '';
```
And add `"sagemaker.lineage.visualizer"` to `pythonImportsCheck`

**Review by NeQuissimus — APPROVED** [review]

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 113978` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.sagemaker</li>
    <li>python38Packages.sagemaker</li>
    <li>python39Packages.sagemaker</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change LGTM

Builds, tests successful

**Pull request merged**
