### PR TITLE
rtmidi: add PulseAudio support

### PR DESCRIPTION
**Pull request by Moredread**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @magnetophon

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Can you change platforms to `unix` and use `with stdenv.lib;`?

**Comment by Moredread** [comment]
> Can you change platforms to `unix` and use `with stdenv.lib;`?

rtmidi should work on Darwin and compiles on the 19.03 branch atm just fine, e.g. https://hydra.nixos.org/build/98258688

It also doesn't look like we need to check the platform when adding to buildInputs, as `alsaLib` is linux only and rtaudio builds on Hydra. Or am I'm missing something?

I've refactored usage of `std.lib`  though.

**Comment by worldofpeace** [comment]
> rtmidi should work on Darwin and compiles on the 19.03 branch atm just fine, e.g. https://hydra.nixos.org/build/98258688
>
> It also doesn't look like we need to check the platform when adding to buildInputs, as alsaLib is linux only and rtaudio builds on Hydra. Or am I'm missing something?

Not sure where I meant those things, `platforms.unix` is identical to `platforms; linux ++ darwin;`

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build rtmidi

**Comment by Moredread** [comment]
@worldofpeace oh sorry, didn't know that unix means both. I've changed it.

**Comment by worldofpeace** [comment]
It seems the latest commit doesn't add pulseaudio to buildInputs. And technically this doesn't support darwin properly, but that's for another PR perhaps.

**Pull request merged**
