### PR TITLE
Enable kernel configuration option FANOTIFY

### PR DESCRIPTION
**Pull request by nckx**
Makes fatrace work out of the box without having to compile a whole custom kernel.

### CODE REVIEW

**Comment by devhell** [comment]
Would the MSR part also solve the powertop loading issues I've been seeing with various laptops?

**Comment by edolstra** [comment]
Note that MSR was already built as a module so we could also add it to `boot.kernelModules`.

**Comment by devhell** [comment]
Ah, it seems CONFIG_X86_MSR is required for my issue as well. Nevermind then, sorry.

**Comment by nckx** [comment]
Yes, it actually solves a few annoyances here and there. Often in tools beginning with *power-*.

> Note that MSR was already built as a module so we could also add it to boot.kernelModules.

Argh, you're right. `modprobe msr`, not `modprobe x86_msr` :neutral_face:

I've updated the PR.

**Pull request merged**
