### PR TITLE
python3Packages.tensorflow: switched to Nix-provided protobuf.

### LINKED ISSUE #150765: pyarrow and tensorflow results segfault when used together
### Describe the bug
When both tensorflow and pyarrow are imported in a python script (in this order) any serialization attempt in pyarrow results `Segmentation fault`.
This happens in the unstable nix channel.

### Steps To Reproduce
Create shell.nix:
```
{ pkgs ? import <nixos-unstable> {} }:

pkgs.mkShell {
  buildInputs = with pkgs.python3Packages; [
    tensorflow
    pyarrow
  ];
}
```
(`nixos-unstable` points to the `https://nixos.org/channels/nixos-unstable` channel)

Create example.py:
```
import tensorflow
import pyarrow.flight as fl

command = fl.FlightDescriptor.for_command(b"{}")
command.serialize()
```

Run the example in nix-shell: `python3 example.py`.

### Expected behavior
Script exits without segfault with 0 exit status.

### Additional context
It seems that the root cause of the problem is the different version of protobuf library used. Pyarrow uses the system's protobuf library (3.19), while tensorflow uses a bundled protobuf library (3.9).

This seems to be confirmed by gdb:
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffd5df6613 in google::protobuf::Message::MergeFrom(google::protobuf::Message const&) () from /nix/store/yi1wv7l1p49h8gf1lapb1gi199r94k8s-protobuf-3.19.0/lib/libprotobuf.so.30
#2  0x00007fffd9e638d0 in google::protobuf::MessageLite::AppendPartialToString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const ()
   from /nix/store/rn3gphncqpi605rs3i6jzvnmvfclz4vj-python3.9-tensorflow-2.7.0/lib/python3.9/site-packages/tensorflow/python/../libtensorflow_framework.so.2
[...]
```
(see that `#2` frame uses `google::protobuf::MessageLite::AppendPartialToString` from tensorflow)

If pyarrow is imported first, the problem disappears. I think that in this case the correct symbol (from pyarrow) is loaded first.

In tensorflow the using of the bundled protobuf was introduced when it was updated to 2.4.0 in the commit 69d1e62b36bf1b65754acfd3a6f343b6b919dd25.
The flight feature flag (which is necessary to run the example) was added to `arrow-cpp` in the commit ac4188fe579f0c1f2121848771a372cc13200c8c.

### Notify maintainers
@ndl

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[zsolt@skylake:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.21, NixOS, 21.05.4470.3b422991781 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(zsolt): `""`
 - channels(root): `"nixos-21.05.4481.c5f1ee98224, nixos-unstable-22.05pre338278.b0bf5f888d3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by ndl**
###### Motivation for this change

This prevents conflicts with other Python packages that also use protobuf, see e.g. #150765.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Fixes: #150765

### CODE REVIEW

**Comment by ndl** [comment]
@veprbl FYI, I don't have access to Darwin system and the hash should have changed => I had to put `fakeSha256` for now, will try to extract the right value from the ofborg's build logs for Darwin (but if you try building it on Darwin - please LMK what hash will you get).

**Comment by veprbl** [comment]
@GrahamcOfBorg build python3Packages.tensorflow

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 150887` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>python3Packages.tensorflow</li>
  </ul>
</details>

**Review by veprbl — APPROVED** [review]
Very cool!

**Pull request merged**
