### PR TITLE
kdeFrameworks: 5.62 -> 5.64; kdeApplications: 19.08.2 -> 19.08.3

### PR DESCRIPTION
**Pull request by nyanloutre**
###### Motivation for this change
Update KDE Framework and applications
#71232 was already updating the framework but is blocked by the new Plasma update.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by nyanloutre** [comment]
ran nixosTests.plasma5 successfully

**Comment by nyanloutre** [comment]
@grahamcofborg test plasma5

**Review by ttuegel — APPROVED** [review]
Thanks! :+1:

**Comment by FRidh** [comment]
Could you have a look at the failing akonadi build on staging-next?
https://hydra.nixos.org/build/108066998
If you know of a fix, please open a PR to staging-next

**Comment by nyanloutre** [comment]
Opened #75533

**Pull request merged**
