### PR TITLE
pythonPackages.gateone: needs tornado_4

### PR DESCRIPTION
**Pull request by manveru**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
commit msg should be `pythonPackages.gateone: needs tornado_4`

**Comment by manveru** [comment]
@worldofpeace updated

**Comment by FRidh** [comment]
Python modules are not allowed to rely on a different version of a package in order to prevent multiple versions in an environment.

**Comment by worldofpeace** [comment]
> Python modules are not allowed to rely on a different version of a package in order to prevent multiple versions in an environment.

Please elaborate on what change is needed?
The need for some packages to depend on `tornado_4` or `tornado` is unavoidable.

**Comment by manveru** [comment]
This is actually an executable... Not sure who'd use gateone as a library.

**Comment by worldofpeace** [comment]
> This is actually an executable... Not sure who'd use gateone as a library.

In that case, this should be moved out of `python-modules` and should use `buildPythonApplication` instead of `buildPythonPackage`.

**Comment by FRidh** [comment]
I think this derivation predates the splitting between libraries and applications.

**Comment by manveru** [comment]
Well, I'd appreciate it if someone could do that then, I'm not familiar enough with Python.

**Comment by worldofpeace** [comment]
> Well, I'd appreciate it if someone could do that then, I'm not familiar enough with Python.

I can do this for you, I'll push the required changes in a bit.

**Comment by manveru** [comment]
Thanks :)

**Review by tomberek — APPROVED** [review]
Still functions, thanks for the cleanup @manveru

**Comment by worldofpeace** [comment]
@tomberek With the NixOS service?

**Comment by tomberek** [comment]
@worldofpeace : Non-NixOS worked fine when just running the package. Ran into issues with the service on NixOS:

1) The pidDir is not created.
2) After that was resolved, the service error-ed with the following:
```
systemd[1]: Starting GateOne web-based terminal...
systemd[1]: Started GateOne web-based terminal.
gateone[15438]: Traceback (most recent call last):
gateone[15438]:   File "/nix/store/mi80nhj95lpxzh92wr7imzvwwfkcch5q-python2.7-gateone-1.2-0d57c3/bin/.gateone-wrapped", line 8, in <module>
gateone[15438]:     from gateone.core.server import main
gateone[15438]:   File "/nix/store/mi80nhj95lpxzh92wr7imzvwwfkcch5q-python2.7-gateone-1.2-0d57c3/lib/python2.7/site-packages/gateone/core/server.py", line 402, in <module>
gateone[15438]:     from gateone.auth.authorization import require, authenticated, policies
gateone[15438]:   File "/nix/store/mi80nhj95lpxzh92wr7imzvwwfkcch5q-python2.7-gateone-1.2-0d57c3/lib/python2.7/site-packages/gateone/auth/authorization.py", line 38, in <module>
gateone[15438]:     @memoize
gateone[15438]:   File "/nix/store/mi80nhj95lpxzh92wr7imzvwwfkcch5q-python2.7-gateone-1.2-0d57c3/lib/python2.7/site-packages/gateone/core/utils.py", line 290, in __init__
gateone[15438]:     MEMO = AutoExpireDict(timeout=timeout, interval="30s")
gateone[15438]:   File "/nix/store/mi80nhj95lpxzh92wr7imzvwwfkcch5q-python2.7-gateone-1.2-0d57c3/lib/python2.7/site-packages/gateone/core/utils.py", line 161, in __init__
gateone[15438]:     self.interval = kwargs.pop('interval')
gateone[15438]:   File "/nix/store/mi80nhj95lpxzh92wr7imzvwwfkcch5q-python2.7-gateone-1.2-0d57c3/lib/python2.7/site-packages/gateone/core/utils.py", line 211, in interval
gateone[15438]:     self._timeout_checker, value, io_loop=self.io_loop)
gateone[15438]: TypeError: __init__() got an unexpected keyword argument 'io_loop'
gateone[15438]: Exception AttributeError: "'AutoExpireDict' object has no attribute '_key_watcher'" in <bound method AutoExpireDict.__del__ of {}> ignored
systemd[1]: gateone.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: gateone.service: Failed with result 'exit-code'.
```

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by manveru** [comment]
Since this seems to be outdated, and I'm not planning on using this package. I'll close it.

**Comment by tomberek** [comment]
Should we mark as broken?

**Pull request closed without merging**
