### PR TITLE
linux-kernel: enable BPF_LSM

### PR DESCRIPTION
**Pull request by akshatagarwl**
Enables instrumentation of the security hooks with BPF programs for
implementing dynamic MAC and Audit Policies.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
since this change causes over 500 rebuilds, do you mind targeting the staging branch

```
# finding the common merge base will avoid pinging all CODEOWNERs
common=$(git merge-base origin/master origin/staging)
git rebase --onto=$common HEAD~1 # or however many commits you want to pull
git push .. ... --force
```
then change the base branch in the github PR from `master` -> `staging`

See https://nixos.org/nixpkgs/manual/#submitting-changes-staging-branch for more details on staging branch

**Comment by jonringer** [comment]
What's the supporting use case for this? Seems like unlikely that a mainstream user would need to use this.

**Comment by humancalico** [comment]
>  `finding the common merge base will avoid pinging all CODEOWNERs`

Sorry, I didn't look at this before

> What's the supporting use case for this? Seems like unlikely that a mainstream user would need to use this.

@jonringer I've added some more details in the commit message. Can you check that out?

**Comment by Artturin** [comment]
arch sets this https://github.com/archlinux/svntogit-packages/blob/9fb55235d5b8642b4893c92ee943d06360ce1f45/trunk/config#L123

**Comment by Mic92** [comment]
> What's the supporting use case for this? Seems like unlikely that a mainstream user would need to use this.

I can see how this could be used for container security policies - but I have not seen any mainstream container runtimes using it yet (I guess because it's still quite fresh?). Since we don't enable any LSM in NixOS by default this probably does not have any effects for mainstream user (except slightly higher disk space for the kernel module) and then it seems to be only used in lsm when enabled during boot.

**Comment by humancalico** [comment]
> I can see how this could be used for container security policies - but I have not seen any mainstream container runtimes using it yet (I guess because it's still quite fresh?)

You're right. It's still very new and there have been some research projects that use this (eg https://github.com/willfindlay/bpfcontain-rs/) but no mainstream container runtimes use it yet.

**Review by Mic92 — APPROVED** [review]
I am fine with having this.
@dasJ @ajs124 Thoughts?

**Comment by dasJ** [comment]
Don't see an issue, even with LSM users like us. This shouldn't affect anything that already exists imo

**Review by jonringer — APPROVED** [review]
I don't have a strong opinion

**Pull request merged**
