### PR TITLE
julia_111{,-bin}: init at 1.11.0

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thomasjm** [comment]
Thanks for doing this! I think some of these commits should be consolidated? If this isn't ready to go yet, just let me know when you'd like a review.

**Comment by NickCao** [comment]
> Thanks for doing this! I think some of these commits should be consolidated? If this isn't ready to go yet, just let me know when you'd like a review.

It's ready for review, we can squash the commits afterwards.

**Review by 7c6f434c — APPROVED** [review]
Diff looks reasonable to me

**Comment by NickCao** [comment]
Rebased and squashed commits.

**Comment by NickCao** [comment]
@thomasjm Would you please test julia 1.11 against julia.withPackage?

**Comment by thomasjm** [comment]
Yes, trying to build the new Julia now.

**Comment by thomasjm** [comment]
Hmm, there's a problem with the package resolution code in `julia-modules/package-closure.nix`. This often happens with new Julia versions; we'll have to tweak it.

BTW, if we're dropping Julia 1.6 here then we can also remove the `resolveCode1_6` in that file.

**Comment by thomasjm** [comment]
I've made the necessary tweaks here: https://github.com/codedownio/nixpkgs/tree/julia_111. Please feel free to cherry-pick, or I can make a follow-up PR if you like.

Out of the top 1000 Julia packages, I'm seeing 13 failures with Julia 1.11, a 98.7% success rate.

**Comment by NickCao** [comment]
> Please feel free to cherry-pick

Done, reworded the commit messages a bit if you don't mind.

**Comment by thomasjm** [comment]
Thanks! Also totally fine to squash or combine them of course. (Like maybe joining the julia_16 one with your commit to remove julia_16 if desired)

**Review by thomasjm — APPROVED** [review]
LGTM

**Pull request merged**
