### PR TITLE
cryptsetup: 2.5.0 -> 2.6.0

### PR DESCRIPTION
**Pull request by mattmelling**
###### Description of changes

Update to 2.6.0, add self as maintainer

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by yu-re-ka — CHANGES_REQUESTED** [review]
The `doCheck = !stdenv.hostPlatform.isMusl` should be changed to `doCheck = true` since the bug issue with the tests under musl has been fixed in this release

**Comment by yu-re-ka** [comment]
This should go to the staging branch, follow the instructions in [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging) to find the common merge base.

**Comment by mattmelling** [comment]
Thanks, will reopen against staging.

**Comment by yu-re-ka** [comment]
For reference: 

```
[yuka@yuyu:~/proj/nixpkgs]$ git rev-parse HEAD
1abdf48ab4ee6a4cf7044fbc501ff5221af9c359
[yuka@yuyu:~/proj/nixpkgs]$ git diff
diff --git a/pkgs/os-specific/linux/cryptsetup/default.nix b/pkgs/os-specific/linux/cryptsetup/default.nix
index 6811e60eba5..d0bf31f3bb7 100644
--- a/pkgs/os-specific/linux/cryptsetup/default.nix
+++ b/pkgs/os-specific/linux/cryptsetup/default.nix
@@ -53,10 +53,7 @@ stdenv.mkDerivation rec {
   nativeBuildInputs = [ pkg-config ] ++ lib.optionals rebuildMan [ asciidoctor ];
   buildInputs = [ lvm2 json_c openssl libuuid popt ];
 
-  # The test [7] header backup in compat-test fails with a mysterious
-  # "out of memory" error, even though tons of memory is available.
-  # Issue filed upstream: https://gitlab.com/cryptsetup/cryptsetup/-/issues/763
-  doCheck = !stdenv.hostPlatform.isMusl;
+  doCheck = true;
 
   passthru = {
     tests = {

[yuka@yuyu:~/proj/nixpkgs]$ nix-build -A pkgsMusl.cryptsetup
/nix/store/ly1y04vawlkrfpf107ahy7rb3apq0hns-cryptsetup-2.6.0-bin

[yuka@yuyu:~/proj/nixpkgs]$

**Pull request closed without merging**
