### PR TITLE
nixos/git: init

### PR DESCRIPTION
**Pull request by figsoda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by IvarWithoutBones** [comment]
home-manager has a [git module](https://github.com/nix-community/home-manager/blob/master/modules/programs/git.nix), which has a ton of options. Could these maybe be ported over?

**Comment by figsoda** [comment]
i personally prefer not porting these options since they can already be done easily with the current implementation

**Comment by IvarWithoutBones** [comment]
Fair enough👍

**Review by nrdxp — APPROVED** [review]
Actually, from my perspective, it's actually better to use the INI generator since it allows specifying any valid Git config values directly in Nix without having to tediously define each one by hand. I guess the only downside is that invalid values would be allowed, but this seems like an acceptable trade-off since `git` will just silently ignore these. 

Good work, I've been wanting this for a while now :+1:

**Pull request merged**
