### PR TITLE
cataclysm-dda{,-git}: build on Darwin

### PR DESCRIPTION
**Pull request by mnacamura**
###### Motivation for this change

Let's play Cataclysm DDA on Darwin!

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mnacamura** [comment]
@GrahamcOfBorg  build cataclysm-dda cataclysm-dda-git

**Comment by mnacamura** [comment]
After `nix-env -f '<nixpkgs>' -iA cataclysm-dda`, `~/.nix-profile/Applications/Cataclysm.app` appears but `~/Applications/Cataclysm.app` does not. Why?

**Comment by LnL7** [comment]
nix-env only manages ~/.nix-profile

**Comment by LnL7** [comment]
@GrahamcOfBorg build cataclysm-dda cataclysm-dda-git

**Comment by mnacamura** [comment]
I misunderstood. `~/Applications` is supervised by nix-darwin, not by nixpkgs.

**Comment by 7c6f434c** [comment]
As the owner of the corresponding borg builder: 

```

g++ -DRELEASE -DSDLTILES -DTILES -DLOCALIZE -DPREFIX="/nix/store/k0l8whysfv1wrmiknch9h0f6j9fzkakj-cataclysm-dda-0.C" -DUSE_HOME_DIR -Os -Wall -Wextra    --std=c++11 -MMD -D_REENTRANT -I/nix/store/6jffcc1ybxm7iyv2fy4i7fwc5b417qw5-SDL2-2.0.7-dev/include/SDL2 -I/nix/store/d3ng8s7pv77x7l6dbzvrmcglgvfqkipw-SDL2_mixer-2.0.2/include/SDL2 -DSDL_SOUND   -I/nix/store/5j5r4gazddc2kycyiv6a3xghid59dkjq-lua-5.2.3/include -DLUA -c src/computer.cpp -o obj/tiles/computer.o
g++  -o cataclysm-tiles -DRELEASE -DSDLTILES -DTILES -DLOCALIZE -DPREFIX="/nix/store/k0l8whysfv1wrmiknch9h0f6j9fzkakj-cataclysm-dda-0.C" -DUSE_HOME_DIR \
          obj/tiles/player_activity.o obj/tiles/ranged.o obj/tiles/item_action.o obj/tiles/damage.o obj/tiles/output.o obj/tiles/rng.o obj/tiles/iuse_software.o obj/tiles/mission.o obj/tiles/inventory.o obj/tiles/iuse_actor.o obj/tiles/veh_interact.o obj/tiles/activity_item_handling.o obj/tiles/text_snippets.o obj/tiles/monster.o obj/tiles/ammo.o obj/tiles/savegame_legacy.o obj/tiles/armor_layers.o obj/tiles/requirements.o obj/tiles/sdltiles.o obj/tiles/init.o obj/tiles/basecamp.o obj/tiles/monmove.o obj/tiles/name.o obj/tiles/game.o obj/tiles/artifact.o obj/tiles/event.o obj/tiles/scenario.o obj/tiles/cata_tiles.o obj/tiles/dependency_tree.o obj/tiles/iuse.o obj/tiles/mapgenformat.o obj/tiles/mondeath.o obj/tiles/computer.o obj/tiles/iexamine.o obj/tiles/editmap.o obj/tiles/catalua.o obj/tiles/monattack.o obj/tiles/mapgen.o obj/tiles/posix_time.o obj/tiles/faction.o obj/tiles/ui.o obj/tiles/weather_data.o obj/tiles/tileray.o obj/tiles/version.o obj/tiles/gamemode.o obj/tiles/mission_start.o obj/tiles/options.o obj/tiles/mondefense.o obj/tiles/messages.o obj/tiles/action.o obj/tiles/addiction.o obj/tiles/bionics.o obj/tiles/line.o obj/tiles/input.o obj/tiles/color.o obj/tiles/mission_end.o obj/tiles/mutation_data.o obj/tiles/wincurse.o obj/tiles/main_menu.o obj/tiles/animation_tiles.o obj/tiles/mod_manager_ui.o obj/tiles/mission_fail.o obj/tiles/mtypedef.o obj/tiles/overmap.o obj/tiles/martialarts.o obj/tiles/field.o obj/tiles/creature.o obj/tiles/animation_curses.o obj/tiles/itypedef.o obj/tiles/filesystem.o obj/tiles/item.o obj/tiles/mapsharing.o obj/tiles/map.o obj/tiles/veh_typedef.o obj/tiles/worldfactory.o obj/tiles/bodypart.o obj/tiles/auto_pickup.o obj/tiles/main.o obj/tiles/clzones.o obj/tiles/skill.o obj/tiles/effect.o obj/tiles/savegame.o obj/tiles/npctalk.o obj/tiles/inventory_ui.o obj/tiles/npcmove.o obj/tiles/pickup.o obj/tiles/weather_gen.o obj/tiles/cursesport.o obj/tiles/monstergenerator.o obj/tiles/simplexnoise.o obj/tiles/item_factory.o obj/tiles/construction.o obj/tiles/item_group.o obj/tiles/creature_tracker.o obj/tiles/translations.o obj/tiles/path_info.o obj/tiles/disease.o obj/tiles/iuse_software_sokoban.o obj/tiles/live_view.o obj/tiles/tutorial.o obj/tiles/catacharset.o obj/tiles/profession.o obj/tiles/defense.o obj/tiles/mapbuffer.o obj/tiles/weather.o obj/tiles/wish.o obj/tiles/iuse_software_snake.o obj/tiles/savegame_json.o obj/tiles/overmapbuffer.o obj/tiles/crafting.o obj/tiles/active_item_cache.o obj/tiles/player.o obj/tiles/start_location.o obj/tiles/mapdata.o obj/tiles/nonplayer.o obj/tiles/npc.o obj/tiles/char_validity_check.o obj/tiles/mutation.o obj/tiles/trapdef.o obj/tiles/sounds.o obj/tiles/speech.o obj/tiles/help.o obj/tiles/material.o obj/tiles/melee.o obj/tiles/mongroupdef.o obj/tiles/mapgen_functions.o obj/tiles/advanced_inv.o obj/tiles/mod_manager.o obj/tiles/character.o obj/tiles/missiondef.o obj/tiles/mission_place.o obj/tiles/newcharacter.o obj/tiles/calendar.o obj/tiles/vehicle.o obj/tiles/debug.o obj/tiles/activity_handlers.o obj/tiles/json.o obj/tiles/iuse_software_kitten.o obj/tiles/trapfunc.o obj/tiles/lightmap.o -s -L/nix/store/pan0vwrvh40ciqfyjzrdjl9bxwbgc3jw-SDL2-2.0.7/lib -L/nix/store/d3ng8s7pv77x7l6dbzvrmcglgvfqkipw-SDL2_mixer-2.0.2/lib -lSDL2_mixer -Wl,-rpath,/nix/store/pan0vwrvh40ciqfyjzrdjl9bxwbgc3jw-SDL2-2.0.7/lib -Wl,--enable-new-dtags -lSDL2 -lvorbisfile -lvorbis -logg   -L/nix/store/5j5r4gazddc2kycyiv6a3xghid59dkjq-lua-5.2.3/lib -llua -lm -lSDL2 -lSDL2_ttf -lSDL2_image
/nix/store/4zaswd1lyncz1jmjkfd3hjz33vakpwx7-stdenv/setup: line 100: png2icns: command not found

```

**Comment by mnacamura** [comment]
Thank you for the information.
That should be fixed by cf8cd83.

**Comment by mnacamura** [comment]
@GrahamcOfBorg build cataclysm-dda cataclysm-dda-git

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build cataclysm-dda cataclysm-dda-git

**Comment by 7c6f434c** [comment]
@mnacamura erm… any ideas what happenned to the darwin build?

**Comment by LnL7** [comment]
My machine is building a bunch of stuff right now, it’s probably unrelated to the changes.

**Pull request merged**
