### PR TITLE
matrix-synapse: remove setuptools_rust from runtime dependencies

### PR DESCRIPTION
**Pull request by NickCao**
###### Description of changes
fixes https://github.com/NixOS/nixpkgs/pull/196686#issuecomment-1286471490

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
@ofborg eval

**Comment by Ma27** [comment]
@ofborg eval

Let's retry without the internal-error label.

**Comment by Ma27** [comment]
also cc @cole-h.

**Comment by cole-h** [comment]
@ofborg eval

Let's see how many times GitHub can send us invalid responses.

**Comment by cole-h** [comment]
OK, I have no idea what's going on...

@NickCao Could I ask you to close this PR and open a brand new one and see if that works? I don't currently have the bandwidth to debug why GitHub is being obnoxious at the moment. :bow:

**Comment by NickCao** [comment]
Guess I somehow breaks github, constantly getting 500 now on https://github.com/NixOS/nixpkgs/compare/master...NickCao:nixpkgs:synapse?expand=1

**Comment by Ma27** [comment]
Perhaps GitHub just doesn't want us to have this change :upside_down_face: 
(Considering that #198189 is now open, they've lost though :p)

**Comment by cole-h** [comment]
Truly weird issue. Thanks for the ping, @Ma27, and for making a new PR, @NickCao; sorry for creating more work for you :bow:

**Comment by SuperSandro2000** [comment]
> Let's retry without the internal-error label.

That shouldn't have an effect.

**Pull request closed without merging**
