### PR TITLE
wpsoffice: cleanup and i686 version

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
fails to build because of an not allowed reference to the build directory. @ttuegel might have more insights how to fix this.

```
...
installing                                                                                                                                                                                    
post-installation fixup                                                                                                                                                                       
stripping (with flags -S) in /nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672/bin                                                                                            
patching script interpreter paths in /nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672                                                                                        
/nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672/opt/kingsoft/wps-office/wpp: interpreter directive changed from "/bin/bash" to "/nix/store/wb34dgkpmnssjkq7yj4qbjqxpnapq0lw-bash-4.4-p12/bin/bash"                                                                                                                                                                         
/nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672/opt/kingsoft/wps-office/install_fonts: interpreter directive changed from "/bin/bash" to "/nix/store/wb34dgkpmnssjkq7yj4qbjqxpnapq0lw-bash-4.4-p12/bin/bash"                                                                                                                                                               
/nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672/opt/kingsoft/wps-office/wps: interpreter directive changed from "/bin/bash" to "/nix/store/wb34dgkpmnssjkq7yj4qbjqxpnapq0lw-bash-4.4-p12/bin/bash"                                                                                                                                                                         
head: write error: Broken pipe                                                                                                                                                                
/nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672/opt/kingsoft/wps-office/et: interpreter directive changed from "/bin/bash" to "/nix/store/wb34dgkpmnssjkq7yj4qbjqxpnapq0lw-bash-4.4-p12/bin/bash"                                                                                                                                                                          
/nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672/bin/wpp: interpreter directive changed from "/bin/bash" to "/nix/store/wb34dgkpmnssjkq7yj4qbjqxpnapq0lw-bash-4.4-p12/bin/bash"                                                                                                                                                                                             
/nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672/bin/et: interpreter directive changed from "/bin/bash" to "/nix/store/wb34dgkpmnssjkq7yj4qbjqxpnapq0lw-bash-4.4-p12/bin/bash"
/nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672/bin/wps: interpreter directive changed from "/bin/bash" to "/nix/store/wb34dgkpmnssjkq7yj4qbjqxpnapq0lw-bash-4.4-p12/bin/bash"                                                                                                                                                                                             
checking for references to /build in /nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672...                                                                                     
RPATH of binary /nix/store/06pkl9cb8wf2qr61lsbgpg5aqpkax7fn-wpsoffice-10.1.0.5672/opt/kingsoft/wps-office/office6/libphonon.so.4.4.0 contains a forbidden reference to /build                 
                                                                                                                                                                                              
builder for ‘/nix/store/48likrg03x7794c5wkn6lmqvqngab99w-wpsoffice-10.1.0.5672.drv’ failed with exit code 1                                                                                   
error: build of ‘/nix/store/48likrg03x7794c5wkn6lmqvqngab99w-wpsoffice-10.1.0.5672.drv’ failed    
```

**Comment by ttuegel** [comment]
You need to remove the build directory before the call to `patchelf`.

**Comment by gnidorah** [comment]
@Mic92 @ttuegel Just this? Thanks

**Comment by Mic92** [comment]
Thanks!

**Comment by gnidorah** [comment]
@Mic92 Thank you!

**Comment by JamieMagee** [comment]
Result of `nixpkgs-review pr 26343` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
