### PR TITLE
wine{Unstable,Staging}: 5.20 -> 5.21 / wineStable: 5.0.2 -> 5.0.3 / airwave: mark as broken

### PR DESCRIPTION
**Pull request by pstn**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SFrijters — APPROVED** [review]
Built staging and used it to run my usual Wine applications, and it all LGTM.

**Comment by SFrijters** [comment]
FYI, wineStable 5.0.3 was released today as well, maybe that could also go into this update.

**Comment by pstn** [comment]
Yes, that sounds reasonable testing right now, will update here when my CPU is done :sleeping:

**Comment by pstn** [comment]
Alright, had a successful build, pushed again for nix-review.

**Comment by pstn** [comment]
Also had to upgrade vst-sdk since I couldn't find the old sources any more in their dl page.

**Comment by pstn** [comment]
Alright, that PR-Review took a while but everything built and as far as I can see executes correctly.

**Comment by ikervagyok** [comment]
Can we include this update as well? would reduce the rebuilds needed, if it lands together. https://github.com/NixOS/nixpkgs/pull/102142

**Comment by SFrijters** [comment]
Issue while running nixpkgs-review on my end (still ongoing):

```
error: --- Error --- nix-daemon
builder for '/nix/store/h0gk3a0bq9piz2hz28rbd3pnkdwc3rm9-airwave-1.3.3.drv' failed with exit code 1; last 10 log lines:
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- VSTSDK_PATH is set to /nix/store/65l493prjwzxvnj6dwyjh3jx1bbz4khi-vst-sdk_3.7.0_build-116_2020-07-31/VST2_SDK
  CMake Error at CMakeLists.txt:65 (message):
    VST SDK is not found.  You should set the VSTSDK_PATH variable to the
    directory, where your copy of the VST SDK is located.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/build/source/build/CMakeFiles/CMakeOutput.log".
```

That's after downloading the SDK zip file by hand and adding it to the store as suggested by the `requireFile` builder. The nix store path exists and contains `public.sdk`, is that expected?

**Comment by pstn** [comment]
@ikervagyok Can do, but this is going to be hard on my CPU...

@SFrijters Yes, having that issue aswell. Working on a fix.

**Comment by SFrijters** [comment]
The rest is fine for me btw:
```
1 package failed to build:
airwave

19 package built:
lutris lutris-free lutris-unwrapped pipelight playonlinux protontricks wine wineStaging wineMinimal wineStable winePackages.fonts winePackages.staging wineUnstable wineWowPackages.base wineWowPackages.full wineWowPackages.minimal wineWowPackages.staging wineWowPackages.unstable winetricks
```

**Review by avnik — APPROVED** [review]
unstable+staging match my own update (but you submit earlier) -- and it works well.
But I haven't idea about vst stuff

**Comment by ikervagyok** [comment]
@pstn you dont have to include it, but these kind of auxiliary updates often fall short for a long time. I'll try with the next wine-release if it's too much for your cpu/patience.

**Comment by SFrijters** [comment]
@pstn Unfortunately I don't have airwave on my system usually, so I don't have the old SDK sources in my store.
But maybe this helps: if I look at https://github.com/psycha0s/airwave the README consistently mentions VST3 instead of VST2, so maybe the fix is to set
```
- cmakeFlags = [ "-DVSTSDK_PATH=${vst-sdk}/VST2_SDK" ];
+ cmakeFlags = [ "-DVSTSDK_PATH=${vst-sdk}/VST3_SDK" ];
```
in airwave?

**Comment by pstn** [comment]
Already tried that to no avail.
I had a closer look at airwave and it seems like it's looking for the files [aeffect.h aeffectx.h](https://github.com/psycha0s/airwave/blob/e44976c37dde1fa3d3293772c74ea91851ba6dd7/CMakeLists.txt#L61) and can't find them because they aren't in the archive any more. Since that project seems to be on life support anyway, I propose to not upgrade vst-sdk and mark airwave as broken since it can't be built any more if you don't happen to have the right files.

**Comment by SFrijters** [comment]
I agree with not updating the sdk / marking airwave as broken.

But weirdly, the previous version used in nixpkgs seems to available still at https://www.steinberg.net/sdk_downloads/vstsdk366_27_06_2016_build_61.zip . So we could also *revert* back to that and put a comment. But it seems like a losing battle.

**Comment by pstn** [comment]
If I was working with airwave I rather had a warning because of a broken package with time to fix than something happening suddenly. If people already have that vstsdk version in their store, they can still build airwave and might have time to supply a proper fix themselves upstream.

**Review by SFrijters — APPROVED** [review]
Did a nixpkgs-review on the latest again and got 
```
1 package marked as broken and skipped:
airwave

19 package built:
lutris lutris-free lutris-unwrapped pipelight playonlinux protontricks wine wineStaging wineMinimal wineStable winePackages.fonts winePackages.staging wineUnstable wineWowPackages.base wineWowPackages.full wineWowPackages.minimal wineWowPackages.staging wineWowPackages.unstable winetricks
```

so LGTM.

**Comment by avnik** [comment]
Would be nice to have it merged, becasue 5.22 is on the go (and it need patching of cert-path.patch, @dasJ I will need your advice here)

**Comment by dasJ** [comment]
```patch
diff --git a/dlls/crypt32/rootstore.c b/dlls/crypt32/rootstore.c
index f795181..fb4926a 100644
--- a/dlls/crypt32/rootstore.c
+++ b/dlls/crypt32/rootstore.c
@@ -18,6 +18,7 @@
 #include "config.h"
 #include <stdarg.h>
 #include <stdio.h>
+#include <stdlib.h> /* getenv */
 #include <sys/types.h>
 #ifdef HAVE_SYS_STAT_H
 #include <sys/stat.h>
@@ -916,6 +917,11 @@ static void read_trusted_roots_from_known_locations(HCERTSTORE store)

         for (i = 0; !ret && i < ARRAY_SIZE(CRYPT_knownLocations); i++)
             ret = import_certs_from_path(CRYPT_knownLocations[i], from, TRUE);
+
+        char *nix_cert_file = getenv("NIX_SSL_CERT_FILE");
+        if (nix_cert_file != NULL)
+            ret = import_certs_from_path(nix_cert_file, from, TRUE);
+
         check_and_store_certs(from, store);
     }
     CertCloseStore(from, 0);
```

**Comment by dasJ** [comment]
Huh? Doesn't the patch apply?

**Comment by pstn** [comment]
I don' think this pr should be applied any more. Why merge an out of support version. Let's just merge 5.22 directly instead. I'll have a look.

**Comment by pstn** [comment]
@dasJ It seems like that file [changed a lot](https://source.winehq.org/git/wine.git/blobdiff/5b62f89baa82daecd430897de0bb5cab32c5fc5e..bedfb9cae224a369efa4588332a5518dbee57035:/dlls/crypt32/rootstore.c) since the 5.21.

**Comment by avnik** [comment]
@pstn I mean add one more commit with 5.22 on top of this, or merge it and do 5.22 separately due rootcert issue.
I like to see all versions in history.

@dasJ they split reading root certs between rootcert.c and `dlls/crypt32/unixlib.c`

PS btw, I thinking about side repo, with auto updating all wines by hashes on their site (and by pushing to wine-staging probably) -- what you think about it?

**Comment by pstn** [comment]
Sounds like a flake that I would use and contribute to if possible. It seems like especially wine-unstable/staging moves to fast nowadays for nixpkgs to keep up without a commiter with a strong interest in it.

**Comment by avnik** [comment]
@pstn exactly. And also be easier to update/propagate staging to nixpkgs.  Is pretty safe to update automatically (after 1day grace period maybe, if it broken  in siderepo -- someone can jus "vetoing" merging, marking is as brownbag)

**Comment by avnik** [comment]
I made new branch with commits from there, and new 5.22 and updated cert-root.patch, now building. Will do new PR as soon as it builds (it take ~3 hours)

**Comment by SFrijters** [comment]
Superseded by #104719

**Pull request closed without merging**
