### PR TITLE
python312Packages.paramiko: update dependencies

### PR DESCRIPTION
**Pull request by dotlambda**
`python3Packages.django-storages` is currently broken due to this:
```
_____________________ ERROR collecting tests/test_sftp.py ______________________
ImportError while importing test module '/build/source/tests/test_sftp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_sftp.py:8: in <module>
    import paramiko
/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/__init__.py:22: in <module>
    from paramiko.transport import (
/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/transport.py:99: in <module>
    from paramiko.ed25519key import Ed25519Key
/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/ed25519key.py:22: in <module>
    import nacl.signing
E   ModuleNotFoundError: No module named 'nacl'
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
This was fixed with https://github.com/NixOS/nixpkgs/pull/345326/commits/50d865aa192645e10064173422b394a12aecdfea during the last Python mass update.

**Comment by vcunat** [comment]
BTW, `master..staging-next` is empty right now.

**Comment by Scrumplex** [comment]
Looks like this issue has made it to nixos-unstable: https://hydra.nixos.org/build/274787269 https://hydra.nixos.org/build/274837261

**Comment by vcunat** [comment]
Nothing to do about this anymore, I believe.  The almost-same fixes are in `staging-next` now.

**Pull request closed without merging**
