### PR TITLE
python312Packages.fabric: add pynacl as dependency

### PR DESCRIPTION
**Pull request by getchoo**
Fixes the build failure that appeared in https://hydra.nixos.org/build/274289142

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by getchoo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 350059`

---
### `aarch64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>azure-cli</li>
    <li>azure-cli.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>Fabric (python312Packages.fabric)</li>
    <li>linien-gui</li>
    <li>linien-gui.dist</li>
    <li>python311Packages.fabric</li>
    <li>python311Packages.linien-client</li>
    <li>python311Packages.linien-client.dist</li>
    <li>python312Packages.linien-client</li>
    <li>python312Packages.linien-client.dist</li>
  </ul>
</details>

---

<details>
  <summary>`azure-cli` fails with the following. Doesn't seem to be caused by this PR</summary>

```
error: builder for '/nix/store/i6h7pjv2a6smaal3ppja1jnzcg1451ya-python3.12-azure-cli-core-2.64.0.drv' failed with exit code 2;
       last 10 log lines:
       >
       > azure/cli/core/tests/test_help_loaders.py:13
       >   /build/azure-cli-2.64.0-src/src/azure-cli-core/azure/cli/core/tests/test_help_loaders.py:13: PytestCollectionWarning: cannot collect test class 'TestCommandLoader' because it has a __init__ constructor (from: azure/cli/core/tests/test_help_loaders.py)
       >     class TestCommandLoader(AzCommandsLoader):
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > ERROR azure/cli/core/tests/test_keys.py
       > !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
       > ================== 2 deselected, 2 warnings, 1 error in 1.98s ==================
       For full logs, run 'nix log /nix/store/i6h7pjv2a6smaal3ppja1jnzcg1451ya-python3.12-azure-cli-core-2.64.0.drv'.
error: 1 dependencies of derivation '/nix/store/2hkyc8vg4dyfnkvawjllyiw1sksm57lm-python3.12-azure-cli-2.64.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ga7pkkj44lx3miljxcmpd9rgg40vgz3z-review-shell.drv' failed to build
```
</details>

**Review by DerDennisOP — APPROVED** [review]
lgtm

**Comment by katexochen** [comment]
Build failure is in paramiko, see https://github.com/NixOS/nixpkgs/issues/348995. Fix is already in staging-next.

**Comment by getchoo** [comment]
Ah, thanks!

**Pull request closed without merging**
