### PR TITLE
pkgs: add linux_{zen,lxq} to top-level

### LINKED ISSUE #228044: Top-level kernels missing
### Describe the bug

Some kernels (`pkgs.linuxKernel.kernels.linux_{zen,lqx,…}`) don't exist at the top-level (as `pkgs.linux_zen`, `pkgs.linux_lqx`, …) while others do (`pkgs.linux_latest`, `pkgs.linux_xanmod`, …).
Their corresponding packages (`pkgs.linuxPackages_{zen,lqx,…}`) are present though.

### Steps To Reproduce

1. `nix repl`
2. `:l <nixpkgs>`
3. `linux_` and press tab
4. `linuxPackages_` and press tab

### Notify maintainers

@PedroHLC

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.9-zen1, NixOS, 23.05 (Stoat), 23.05.20230408.6f95dd4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/nix/store/pmyn8x8ilqpbg73c6d3qn8k39djn224c-source`
```

### PR DESCRIPTION
**Pull request by m-bdf**
###### Description of changes

Add `linux_zen` and `linux_lqx` to top-level pkgs for consistency with the other kernel variants.

Closes #228044. @PedroHLC

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by PedroHLC — APPROVED** [review]
Nothing really to review here, so, LGTM.

**Comment by NickCao** [comment]
I have vague memory that we are no longer adding these aliases, cc @fabianhjr for opinions.

**Comment by fabianhjr** [comment]
I don't have much context but yeah I think the idea was to move to `linuxPackages` / `linuxKernel.packages`.



```
> rg "linuxPackages.*\.kernel" pkgs/top-level/
pkgs/top-level/all-packages.nix
26724:    base = linuxPackages.kernel;
26737:  linux = linuxPackages.kernel;
26740:  linux_latest = linuxPackages_latest.kernel;
26752:  linux-rt = linuxPackages-rt.kernel;
26753:  linux-rt_latest = linuxPackages-rt_latest.kernel;
26757:  linux_hardened = linuxPackages_hardened.kernel;
26759:  linux_4_14_hardened = linuxPackages_4_14_hardened.kernel;
26761:  linux_4_19_hardened = linuxPackages_4_19_hardened.kernel;
26773:  linux_hardkernel_latest = linuxPackages_hardkernel_latest.kernel;
26777:  linux-libre = linuxPackages-libre.kernel;
26779:  linux_latest-libre = linuxPackages_latest-libre.kernel;
```

Recent kernels are missing and I think *_latest should be removed if that is the direction nixpkgs is going.

**Comment by m-bdf** [comment]
But if we search for `lnuxKernel.kernels` then all the recent ones are here:

```cmd
> rg "linuxKernel\.kernels" pkgs/top-level/
pkgs/top-level/aliases.nix
899:  linux-rt_5_10 = linuxKernel.kernels.linux_rt_5_10;
900:  linux-rt_5_15 = linuxKernel.kernels.linux_rt_5_15;
901:  linux-rt_5_4 = linuxKernel.kernels.linux_rt_5_4;
902:  linux-rt_6_1 = linuxKernel.kernels.linux_rt_6_1;
925:  linux_4_14 = linuxKernel.kernels.linux_4_14;
926:  linux_4_19 = linuxKernel.kernels.linux_4_19;
927:  linux_4_9 = linuxKernel.kernels.linux_4_9;
928:  linux_5_10 = linuxKernel.kernels.linux_5_10;
929:  linux_5_15 = linuxKernel.kernels.linux_5_15;
930:  linux_5_18 = linuxKernel.kernels.linux_5_18;
931:  linux_5_19 = linuxKernel.kernels.linux_5_19;
932:  linux_5_4 = linuxKernel.kernels.linux_5_4;
933:  linux_6_0 = linuxKernel.kernels.linux_6_0;
934:  linux_6_1 = linuxKernel.kernels.linux_6_1;
935:  linux_6_2 = linuxKernel.kernels.linux_6_2;
939:  linux_rpi0 = linuxKernel.kernels.linux_rpi1;
940:  linux_rpi02w = linuxKernel.kernels.linux_rpi3;
941:  linux_rpi1 = linuxKernel.kernels.linux_rpi1;
942:  linux_rpi2 = linuxKernel.kernels.linux_rpi2;
943:  linux_rpi3 = linuxKernel.kernels.linux_rpi3;
944:  linux_rpi4 = linuxKernel.kernels.linux_rpi4;

pkgs/top-level/all-packages.nix
26705:  linux_testing = linuxKernel.kernels.linux_testing;
26708:  linux_testing_bcachefs = linuxKernel.kernels.linux_testing_bcachefs;
26724:  linux_5_4_hardened = linuxKernel.kernels.linux_5_4_hardened;
26726:  linux_5_10_hardened = linuxKernel.kernels.linux_5_10_hardened;
26728:  linux_5_15_hardened = linuxKernel.kernels.linux_5_15_hardened;
26730:  linux_6_1_hardened = linuxKernel.kernels.linux_6_1_hardened;
26748:  linux_xanmod = linuxKernel.kernels.linux_xanmod;
26750:  linux_xanmod_stable = linuxKernel.kernels.linux_xanmod_stable;
26752:  linux_xanmod_latest = linuxKernel.kernels.linux_xanmod_latest;
```

**Comment by fabianhjr** [comment]
Oh then I am wrong, they should be moved to aliases and use the same pattern then.

**Pull request closed without merging**
