### PR TITLE
f3: 6.0-2016.11.16-unstable -> 7.0

### PR DESCRIPTION
**Pull request by jfrankenau**
###### Motivation for this change

Update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
cc @makefu @elitak

### CODE REVIEW

**Comment by makefu** [comment]
@GrahamcOfBorg build f3

**Comment by makefu** [comment]
@jfrankenau seems like the new f3 release is down again.

**Comment by jfrankenau** [comment]
Sorry, had a typo in there. It should work now.

**Comment by makefu** [comment]
@GrahamcOfBorg build f3

**Review by makefu — APPROVED** [review]
lgtm

**Comment by makefu** [comment]
anything blocking this pr?

**Pull request merged**
