### PR TITLE
ffmpeg 2.8: init at 2.8.1

### PR DESCRIPTION
**Pull request by devhell**
Built and run locally.

This commit adds a `ffmpeg 2.8` branch with the init version being
`2.8.1`. `ffmpeg` points to `ffmpeg 2.8`.

The changelog can be found here:
https://github.com/FFmpeg/FFmpeg/blob/master/Changelog

### CODE REVIEW

**Comment by andrewrk** [comment]
I'm confused how this pull request is even possible. These changes already are merged into master:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/ffmpeg/2.8.nix
https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L6259

**Comment by peti** [comment]
Is it possible that those addition were committed in `staging` originally and got into `master` by way of a merge just yesterday?

**Comment by devhell** [comment]
Weird. Feel free to close this if it has already been done before. @peti might be right, but when I did this PR there was no 2.8 in master. Either way, no biggie.

**Comment by vcunat** [comment]
We do have this in master, and auto-merging produces a bad state with repeated definition in all-packages.nix.

**Pull request closed without merging**
