### PR TITLE
notmuch: add missing "patchShebangs configure"

### PR DESCRIPTION
**Pull request by flokli**
This is on master as well, and fixes last failing notmuch test
"Ignore files and directories specified in new.ignore (regexp)"

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dezgeg** [comment]
Huh. What version of Nix this happens with?

**Comment by xeji** [comment]
Weird thing is, I could not reproduce the `notmuch` hydra failure locally on the `staging-18.03` branch. Builds fine on my machine with or without this patch...

**Comment by flokli** [comment]
I was able to reproduce locally with a checkout of df29e697fde09363f7a2fbf6016986cd983f77b1, and a
```
nix-build -A notmuch -I nixpkgs=/path/to/checkout .
```

`Nix 2.0.1` here.

**Comment by xeji** [comment]
I just did exactly the same and it succeded:
```
Notmuch test suite complete.
All 960 tests behaved as expected (4 expected failures).
```
Only difference is that I have `nix (Nix) 2.0`.

**Comment by flokli** [comment]
d97416198a035ed983e8195bca0493f6eee3f8ae (which seems to be this PR) speaks about `/bin/sh` impurity.

**Comment by xeji** [comment]
whatever, the patch shouldn't hurt and is consistent with master, so let's get this merged and see.

**Comment by bfortz** [comment]
I don't know if it will help with the transient test failure (I was not able to reproduce it), but I suggest bumping notmuch to 0.26.1 at the same time. Builds ok for me against staging-18.03. See PR #39487

**Pull request merged**
