### PR TITLE
fix logseq unable to run by pinning electron version

### PR DESCRIPTION
**Pull request by polarmutex**
###### Motivation for this change
in the current master logseq is unable to run

###### Things done
pinned the electron version so logseq runs

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bascht** [comment]
Is there anything that's blocking this MR? I manually verified that @polarmutex's fix works even with the latest logseq 0.4.1 release:

```shell
$ nix-env -f ~/Code/nixos/nixpkgs -iA logseq
installing 'logseq-0.4.1'
these derivations will be built:
  /nix/store/c3idv53crw19w27lifw0zaj2cjyyw5ip-logseq-0.4.1.AppImage.drv
  /nix/store/ffwnz36880jwrl0sq9zqvgm065z31zwi-appimage-exec.sh.drv
  /nix/store/ysp01isi0dkx98ajqm6741nlli53r720-logseq-0.4.1-extracted.drv
  /nix/store/q0w2hl48jvbj2ybrrkr12plgdm28ci3z-logseq-0.4.1.drv
these paths will be fetched (52.79 MiB download, 235.78 MiB unpacked):
  /nix/store/0csfz8a602mis8i7q7929z7dc28sgr3z-curl-7.76.1-man
  /nix/store/0kgvmx19fvwcwp83pd40qa9lbcfih862-libarchive-3.5.1-lib
  /nix/store/165chj0krlfdkh8c4fq0p72ip9d4z9r0-nghttp2-1.43.0-bin
  /nix/store/1syid5jdx07cwkjbwqwh12akcfdsagn2-nghttp2-1.43.0-dev
  /nix/store/26ky9b8xsk0xhcvh2a8waxmm6mm4qpyr-mirrors-list
  /nix/store/2j78271w0pinbmiwrlj2sr949mn1rix0-c-ares-1.17.2
  /nix/store/2qmkkrkk2d1jvin6iy8yvfh7iaawyqwm-gcc-wrapper-10.3.0
  /nix/store/49fgqipzvqg06cm05gw43z6khxjj6fhp-curl-7.76.1-bin
  /nix/store/4cnyjnpswvlvld2icvfhdp35xn1w61af-gnused-4.8
  /nix/store/4kihg81a0l0v38nf1nyihglj0pm8bca7-libarchive-3.5.1
  /nix/store/5kry9k64l4siw7f3qp4a5zyrdgjf85mi-gnumake-4.3
  /nix/store/6i4kv5p4vkbxzxb1dcnri342qlhpj8n2-libkrb5-1.18
  /nix/store/78nfwnbp5bj885li37ny52znnr8z0dx4-openssl-1.1.1l-bin
  /nix/store/86mlz0g8a5hfpfw6my18d9n00dlgjamk-libssh2-1.9.0-dev
  /nix/store/8grgkzdvrjjafgnwy5714naibiamaa70-hook
  /nix/store/9jsp95c5r4pl1pdqzy9z405wj39czpwa-stdenv-linux
  /nix/store/9pcmv5xl3zj7l91pdnj98gwkjbhvj7c4-openssl-1.1.1l
  /nix/store/b07551pc54i6zyzcq08p51610b7ifxmh-stdenv-linux
  /nix/store/b5glibvns7bakx3wq6bbbbr2fzapzrnf-hook
  /nix/store/c9pzg5rcy2vkv1j1g9r2zg2k39ykq5wh-libssh2-1.9.0
  /nix/store/dp2xc2mvfy4gwbkz8g1qq71q12c3nhwy-linux-headers-5.12
  /nix/store/fmyn0jdp41d2wg4pnapjlqwxxvsp3k2x-ed-1.17
  /nix/store/gcwds7i87a6cpc5lx8bwn6xzbzfw2kp4-patchelf-0.13
  /nix/store/hgz45qisazmj43zcvgjqwhskjhqy7ml7-nghttp2-1.43.0
  /nix/store/hq164navrcpj1w31r544n6qjdq4by92h-findutils-4.8.0
  /nix/store/i2gkwnhr3vpd28cjljp13ifrh4n3p4im-libev-4.33
  /nix/store/j7s08fw8cx71kvxzyhkz7sqqm804s6bl-gcc-10.3.0
  /nix/store/jrq4ad6y482vci7xpq8g5wwb8igjxjkr-curl-7.76.1
  /nix/store/k593zfw4pp8qjh4r7ci4c36323hssff3-curl-7.76.1-dev
  /nix/store/kmqs0wll31ylwbqkpmlgbjrn6ny3myik-binutils-2.35.1
  /nix/store/nlwr2haphv30zkcr66lyhnchilywxw4v-gawk-5.1.0
  /nix/store/np1948gz80ycm5wgmc6q2r5di48zy5yd-pv-1.6.20
  /nix/store/q68q448r514ak3vhf2m44ax6vhmxamjx-glibc-2.33-49-dev
  /nix/store/qs9ai71mpr7dsm1ili447x1nql3ga18q-patch-2.7.6
  /nix/store/r760mzynwbl0x5vw1rsms2m7xsjss86n-nghttp2-1.43.0-lib
  /nix/store/rk0fr6xd87r4xv7fhp71lm4y9dmmz3y2-libkrb5-1.18-dev
  /nix/store/vbr0mp09qiq72jllhrzp92dcj989w9ba-lzo-2.10
  /nix/store/x24di5gndsi4plj1snp1wk4dzf2k9sp2-openssl-1.1.1l-dev
  /nix/store/xqchqx3l1230cc1g2vvchhm4l17ji2kv-zlib-1.2.11-dev
  /nix/store/xsrvdr2ir43zrj5ip8fhh9n30mrrgd10-squashfs-4.5
  /nix/store/y56fwb7pp4h2m017w80jmmcd4wsm2iff-diffutils-3.7
  /nix/store/zpfa1fc00k5r7zfknkigapxxn4kgiirc-binutils-wrapper-2.35.1
  /nix/store/zva08p0hb6dc4invg3dsa1z62r6xrbpv-expand-response-params
copying path '/nix/store/b5glibvns7bakx3wq6bbbbr2fzapzrnf-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/y56fwb7pp4h2m017w80jmmcd4wsm2iff-diffutils-3.7' from 'https://cache.nixos.org'...
copying path '/nix/store/fmyn0jdp41d2wg4pnapjlqwxxvsp3k2x-ed-1.17' from 'https://cache.nixos.org'...
copying path '/nix/store/zva08p0hb6dc4invg3dsa1z62r6xrbpv-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/hq164navrcpj1w31r544n6qjdq4by92h-findutils-4.8.0' from 'https://cache.nixos.org'...
copying path '/nix/store/nlwr2haphv30zkcr66lyhnchilywxw4v-gawk-5.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/5kry9k64l4siw7f3qp4a5zyrdgjf85mi-gnumake-4.3' from 'https://cache.nixos.org'...
copying path '/nix/store/4cnyjnpswvlvld2icvfhdp35xn1w61af-gnused-4.8' from 'https://cache.nixos.org'...
copying path '/nix/store/dp2xc2mvfy4gwbkz8g1qq71q12c3nhwy-linux-headers-5.12' from 'https://cache.nixos.org'...
copying path '/nix/store/26ky9b8xsk0xhcvh2a8waxmm6mm4qpyr-mirrors-list' from 'https://cache.nixos.org'...
copying path '/nix/store/gcwds7i87a6cpc5lx8bwn6xzbzfw2kp4-patchelf-0.13' from 'https://cache.nixos.org'...
copying path '/nix/store/0csfz8a602mis8i7q7929z7dc28sgr3z-curl-7.76.1-man' from 'https://cache.nixos.org'...
copying path '/nix/store/kmqs0wll31ylwbqkpmlgbjrn6ny3myik-binutils-2.35.1' from 'https://cache.nixos.org'...
copying path '/nix/store/hgz45qisazmj43zcvgjqwhskjhqy7ml7-nghttp2-1.43.0' from 'https://cache.nixos.org'...
copying path '/nix/store/6i4kv5p4vkbxzxb1dcnri342qlhpj8n2-libkrb5-1.18' from 'https://cache.nixos.org'...
copying path '/nix/store/r760mzynwbl0x5vw1rsms2m7xsjss86n-nghttp2-1.43.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/2j78271w0pinbmiwrlj2sr949mn1rix0-c-ares-1.17.2' from 'https://cache.nixos.org'...
copying path '/nix/store/8grgkzdvrjjafgnwy5714naibiamaa70-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/0kgvmx19fvwcwp83pd40qa9lbcfih862-libarchive-3.5.1-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/i2gkwnhr3vpd28cjljp13ifrh4n3p4im-libev-4.33' from 'https://cache.nixos.org'...
copying path '/nix/store/vbr0mp09qiq72jllhrzp92dcj989w9ba-lzo-2.10' from 'https://cache.nixos.org'...
copying path '/nix/store/9pcmv5xl3zj7l91pdnj98gwkjbhvj7c4-openssl-1.1.1l' from 'https://cache.nixos.org'...
copying path '/nix/store/qs9ai71mpr7dsm1ili447x1nql3ga18q-patch-2.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/np1948gz80ycm5wgmc6q2r5di48zy5yd-pv-1.6.20' from 'https://cache.nixos.org'...
copying path '/nix/store/xqchqx3l1230cc1g2vvchhm4l17ji2kv-zlib-1.2.11-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/xsrvdr2ir43zrj5ip8fhh9n30mrrgd10-squashfs-4.5' from 'https://cache.nixos.org'...
copying path '/nix/store/4kihg81a0l0v38nf1nyihglj0pm8bca7-libarchive-3.5.1' from 'https://cache.nixos.org'...
copying path '/nix/store/b07551pc54i6zyzcq08p51610b7ifxmh-stdenv-linux' from 'https://cache.nixos.org'...
copying path '/nix/store/rk0fr6xd87r4xv7fhp71lm4y9dmmz3y2-libkrb5-1.18-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/c9pzg5rcy2vkv1j1g9r2zg2k39ykq5wh-libssh2-1.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/165chj0krlfdkh8c4fq0p72ip9d4z9r0-nghttp2-1.43.0-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/78nfwnbp5bj885li37ny52znnr8z0dx4-openssl-1.1.1l-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/q68q448r514ak3vhf2m44ax6vhmxamjx-glibc-2.33-49-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/jrq4ad6y482vci7xpq8g5wwb8igjxjkr-curl-7.76.1' from 'https://cache.nixos.org'...
copying path '/nix/store/86mlz0g8a5hfpfw6my18d9n00dlgjamk-libssh2-1.9.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/x24di5gndsi4plj1snp1wk4dzf2k9sp2-openssl-1.1.1l-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/1syid5jdx07cwkjbwqwh12akcfdsagn2-nghttp2-1.43.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/49fgqipzvqg06cm05gw43z6khxjj6fhp-curl-7.76.1-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/j7s08fw8cx71kvxzyhkz7sqqm804s6bl-gcc-10.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/k593zfw4pp8qjh4r7ci4c36323hssff3-curl-7.76.1-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/zpfa1fc00k5r7zfknkigapxxn4kgiirc-binutils-wrapper-2.35.1' from 'https://cache.nixos.org'...
building '/nix/store/ffwnz36880jwrl0sq9zqvgm065z31zwi-appimage-exec.sh.drv'...
building '/nix/store/c3idv53crw19w27lifw0zaj2cjyyw5ip-logseq-0.4.1.AppImage.drv'...

trying https://github.com/logseq/logseq/releases/download/0.4.1/logseq-linux-x64-0.4.1.AppImage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   639  100   639    0     0   2985      0 --:--:-- --:--:-- --:--:--  2985
copying path '/nix/store/2qmkkrkk2d1jvin6iy8yvfh7iaawyqwm-gcc-wrapper-10.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/9jsp95c5r4pl1pdqzy9z405wj39czpwa-stdenv-linux' from 'https://cache.nixos.org'...
100  116M  100  116M    0     0  29.6M      0  0:00:03  0:00:03 --:--:-- 35.1M
building '/nix/store/ysp01isi0dkx98ajqm6741nlli53r720-logseq-0.4.1-extracted.drv'...
Uncompress ahjy8savj6bk1v0zh9wh44gawqkf6lr6-logseq-0.4.1.AppImage of type 02 @ offset 188392

ahjy8savj6bk1v0zh9wh44gawqkf6lr6-logseq-0.4.1.AppImage is now installed in /nix/store/xcqnc8bjl5w4f4gjqj8b5dcaji8hi8mj-logseq-0.4.1-extracted
building '/nix/store/q0w2hl48jvbj2ybrrkr12plgdm28ci3z-logseq-0.4.1.drv'...
patching sources
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-http-push
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-imap-send
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-daemon
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-lfs
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-http-fetch
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-remote-http
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-shell
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-sh-i18n--envsubst
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-http-backend
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/bin/git
shrinking /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/better-sqlite3/build/Release/better_sqlite3.node
strip is /nix/store/kmqs0wll31ylwbqkpmlgbjrn6ny3myik-binutils-2.35.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/bin
patching script interpreter paths in /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-quiltimport: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-merge-octopus: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-merge-one-file: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-filter-branch: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-mergetool: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-request-pull: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-merge-resolve: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-instaweb: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-submodule: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-web--browse: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-difftool--helper: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/libexec/git-core/git-bisect: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/pre-rebase.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/update.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/pre-commit.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/pre-receive.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/pre-applypatch.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/pre-push.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/prepare-commit-msg.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/pre-merge-commit.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/post-update.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/applypatch-msg.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/dugite/git/share/git-core/templates/hooks/commit-msg.sample: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/open/xdg-open: interpreter directive changed from "#!/bin/sh" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/sh"
/nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1/share/logseq/resources/app/node_modules/better-sqlite3/deps/download.sh: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/1flh34xxg9q3fpc88xyp2qynxpkfg8py-bash-4.4-p23/bin/bash"
checking for references to /build/ in /nix/store/xkffcmy574hyhb1nvbanj1146vw0d0f5-logseq-0.4.1...


patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
building '/nix/store/k1ajwlgjvzzk72jbfsfrrvnfm7zi28n2-user-environment.drv'...
created 11501 symlinks in user environment

$ logseq
Gtk-Message: 09:03:13.442: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:03:13.442: Failed to load module "pk-gtk-module"
09:03:13.480 › Logseq App(0.4.1) Starting... 
```

(App launches & window pops up like it is supposed to)

**Comment by esclear** [comment]
This would supersede #137576 .

**Comment by bascht** [comment]
@polarmutex do you want to take over or should I open a new PR that bumps to 0.4.1 and cherry-picks your fix for the electron issue?

**Comment by SuperSandro2000** [comment]
If an update fixes the issue, please update the package instead. Also please override the input instead of changing the variable in the file itself.

**Comment by polarmutex** [comment]
@bascht  I will  also add the update to 0.4.2 since it was released today

**Comment by fufexan** [comment]
What's stopping this from getting merged?

**Comment by SuperSandro2000** [comment]
> this works on my system, can someone explain what i need to change? (still kinda new to nixos) I have specified the electron to v13 in the file changes, is there another way to do this?

I don't think anything else.

**Pull request merged**
