### PR TITLE
diffutils: disable tests on riscv64

### LINKED ISSUE #300550: Build failure: diffutils-3.10-riscv64-linux on qemu
### Steps To Reproduce

1. build diffutils-3.10-riscv64-linux

### Build log

[diffutils-log.txt](https://github.com/NixOS/nixpkgs/files/14817596/diffutils-log.txt)

### Additional context

i had suspended the system halfway through the build, and suspected that might have caused an issue, so i ran the build again and got the same result

### Notify maintainers

@dasJ 
@alyssais 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
hive@sol ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240226.13aff9b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.3`
 - nixpkgs: `/nix/store/1gpgihsi21bni03hy6i5ccw9lfrhnbqi-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by theotheroracle**
## Description of changes

disable tests in diffutils on risc64
fixes #300550

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
as per https://github.com/NixOS/nixpkgs/issues/300550#issuecomment-2032136788 this is only on qemu

**Comment by fgaz** [comment]
> as per [#300550 (comment)](https://github.com/NixOS/nixpkgs/issues/300550#issuecomment-2032136788) this is only on qemu

I think we should include a comment about this, so we don't accidentally revert

**Comment by alyssais** [comment]
I'm not sure we should be disabling tests for problems that only exist in emulators?

**Comment by fgaz** [comment]
My guess is that for now emulation is still the main way non-cross RISC-V packages are built, so I think this change makes sense. It should definitely be reverted at some point, and (#300621 as well)

**Comment by skeuchel** [comment]
Is that a problem with system or user mode emulation?

**Comment by theotheroracle** [comment]
I would suspect both, but I've been running the builds as not root

**Pull request merged**
