### PR TITLE
curl: Set cabundle in configure. Closes #3382

### LINKED ISSUE #3382: Provide more assistance for users to find SSL certificates (the "unable to get local issuer certificate" problem)
This caused me a big headache yesterday. A solution (for git) is to install cacert and then run GIT_SSL_CAINFO=$HOME/.nix-profile/etc/ca-bundle.crt, but when running outside nixos that environment variable isn't set and there's no warning/indication that you'd need to set anything. 

Basically this means curl/git are broken out of the box.

A nice thing would be to print "Curl has installed but no SSL certificates are currently available, which means all SSL operations will fail. To add SSL certificates, install the cacert package, then set CURL_CA_BUNDLE=$HOME/.nix-profile/etc/ca-bundle.crt in your environment", in bright red, when curl is installed, and a similar message for git.

It would also be nice if the packages just shipped with a certificate list.

### PR DESCRIPTION
**Pull request by lucabrunox**

### CODE REVIEW

**Comment by vcunat** [comment]
I gather our ``pkgs.curl`` should not use this option by default (and use the env variable instead). Are there some other reasons to keep the option?

**Comment by edolstra** [comment]
Don't think so. Certificates are really runtime configuration data to be taken from /etc. If we want a static fallback certificate bundle at all, it should be done in OpenSSL, not curl (so that all OpenSSL-based applications benefit).

**Comment by jagajaga** [comment]
So what's the status of this PR?

**Comment by vcunat** [comment]
If #3382 is still an issue, it seems a different solution should be found than hardcoding the CA bundle *by default* (having the option is certainly fine with me). The bundle is just data that don't need to cause rebuilds, and it's also used by other packages than just curl.

**Pull request closed without merging**
