### PR TITLE
gmime3: 3.2.7 -> 3.2.11

### PR DESCRIPTION
**Pull request by vcunat**
The active repo is elsewhere now; reading linked from:
https://gitlab.gnome.org/GNOME/gmime/-/issues/10

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
The reason I looked at this is that the package started to fail its check phase on aarch64-darwin consistently.  Unfortunately, in the past few days the aarch64-darwin OfBorg won't really work :-/  Still, other platforms build, so I don't expect regression either way.

**Comment by vcunat** [comment]
> 22 packages built:
aerc afew alot astroid balsa gmime3 gnome.geary i3status-rust lbdb lieer meli mu muchsync neomutt notmuch notmuch-addrlookup python310Packages.notifymuch python310Packages.notmuch python310Packages.notmuch2 python39Packages.notifymuch python39Packages.notmuch python39Packages.notmuch2

**Comment by risicle** [comment]
`gmime3` builds for me with this, darwin-aarch64, macos 12.3

**Comment by vcunat** [comment]
Actually, I see that the test did succeed even on the same-hash derivation after a few attempts: https://hydra.nixos.org/log/qnli0fylc6rlaz9y00n3d4yj78sqqz5y-gmime-3.2.7.drv

**Comment by vcunat** [comment]
For reference, before it was like
```
Testing GnuPG crypto context: failed (4 errors, 0 warnings)
Testing PGP/MIME implementation: failed (6 errors, 0 warnings)
Results: 11 tests passed; 2 tests failed.
Failed tests: 
 test-pgp
 test-pgpmime
```

**Comment by risicle** [comment]
`nixpkgs-review` reveals no new failures, macos 10.15 & nixos x86_64

**Pull request merged**
