### PR TITLE
nixbox: init at unstable-2019-04-20

### PR DESCRIPTION
**Pull request by LinArcX**
###### Motivation for this change
I need a central app to manage all nixos operations in one place. So with nixbox i can manage Derivations, Generations(delete them, list them, ..), manage channels, fix nix store, ... in single application without worry to memorize their commands. 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by tomberek — APPROVED** [review]
Builds, runs and functions on Ubuntu

**Comment by timokau** [comment]
Since you apparently maintain that package, would you mind making a release first?

**Comment by timokau** [comment]
Also writing something in the motivation section here would be nice, since it adds a new package.

**Comment by c0bw3b** [comment]
@LinArcX > I left a small PR on your tool: https://github.com/LinArcX/nixbox/pull/1

And +1 on making a proper tagged release of it before inclusion in nixpkgs.

**Review by ryantm — CHANGES_REQUESTED** [review]
Please make a tagged release

**Comment by wamserma** [comment]
@LinArcX Are you willing to update this PR?
I see you made [the release](https://github.com/LinArcX/nixbox/releases/tag/0.1.0) quite a while ago, but never came back to this PR.

**Comment by LinArcX** [comment]
@wamserma hi. Actually I don't have nixos anymore.

But I think this pr is OK. Since I added a releas for it.

**Comment by wamserma** [comment]
@LinArcX Are you willing to actively maintain this? Then please update the PR to use the release tag, otherwise please close it.

**Comment by LinArcX** [comment]
I don't have nuxpkgs right now. I close it. If anyone interest open new pr.

**Pull request closed without merging**
