### PR TITLE
texlive: fix build broken by poppler update

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Vendored patch, or even patching texlive at all vs. patching poppler
(see mailing list thread and linked issues, arguably poppler bug)
might make this not the best, but it's what I have right now :).

So this is a bit of an issue reporting the breakage :).

The patch included has been working well for me, FWIW.

Check breakage vs fixing with: `texlive.bin.core` for example.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build texlive.bin.core

**Comment by jonringer** [comment]
since a lot of these are flat out broken, I'm tempted to merge into master immediately

**Comment by jonringer** [comment]
I got the error:
```
/nix/store/jg8wgwfrj7xr5n85xg6hp5ww6ishjhdc-poppler-min-0.84.0-dev/include/poppler/poppler-config.h:142:10: fatal error: cstdio: No such file or directory
  142 | #include <cstdio> // __MINGW_PRINTF_FORMAT is defined in the mingw stdio.h
```
which seems odd to me, as this is a stdlib c++ header. But I'm not familiar with the poppler build chain. Looks fairly complex.

**Comment by vcunat** [comment]
I tried to poke upstream: https://gitlab.freedesktop.org/poppler/poppler/commit/1c1d9a70013125f67518f398a2b5abf37ec43cdd#note_400730

**Pull request merged**
