### PR TITLE
tuir: use the maintained fork and update 1.29.0 -> 1.31.0

### PR DESCRIPTION
**Pull request by brokenpip3**
## Description of changes

The latest commit of original forked from rtv tuir is more than 4 years ago: https://gitlab.com/ajak/tuir. Also that version currently does not allow to login and comment/post in reddit and have some navigation bug.
Recently arise a actively supported fork from [Chocimier](https://github.com/Chocimie): https://gitlab.com/Chocimier/tuir that is also listed here: https://gist.github.com/michael-lazar/8c31b9f637c3b9d7fbdcbb0eebcf2b0a
I reviewed the latest [changes](https://gitlab.com/Chocimier/tuir/-/compare/master...master?from_project_id=12748921) from upstream and tested it with a derivation, everything is working again.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Please split the commit, do not add yourself as a maintainer in the same commit as the version bump please!

**Comment by brokenpip3** [comment]
hei @matthiasbeyer, thanks! will do it

**Review by matthiasbeyer — APPROVED** [review]
Thanks.

I don't know what the policy on changing the repo we fetch the sources from is, so I'll wait with merging until someone with knowledge about the policy comes along, but I approve the changes itself!

**Comment by matthiasbeyer** [comment]
Ah, sorry. The commit message on the maintainer commit should be `tuir: Add brokenpip3 as maintainer`

**Comment by brokenpip3** [comment]
> Ah, sorry. The commit message on the maintainer commit should be `tuir: Add brokenpip3 as maintainer`

sorry about that! fixed :)

**Comment by brokenpip3** [comment]
it seems that the ofborg tests on aarch64 are stuck since 6 days, not sure what I can do to unlock them

**Review by smancill — APPROVED** [review]
LGTM

**Pull request merged**
