### PR TITLE
perlPackages.Mouse: 2.3.0 -> 2.4.5 to fix build issues

### PR DESCRIPTION
**Pull request by grahamc**
###### Things done:
- [X] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by joachifm** [comment]
This is already in ca6ac920ed0eb2bb0f4284c118c8c416742d5810

**Comment by grahamc** [comment]
oh, right on :) thanks you. How do we ensure those commits get back to master? and: how can I run those i3 tests locally?

**Comment by joachifm** [comment]
I suppose I can just cherry-pick that change. There's a bit of a flurry to get these fixes into the release branch as quickly as possible, so oversights may occur, no big deal.

Tests can be run really easily via `nix-build`, as in `nix-build nixos/tests/i3wm.nix`. Alternatively, `nix-build nixos/release.nix -A tests.i3wm` should work as well.

**Comment by grahamc** [comment]
Ah, I missed setting the `nixos/release.nix` part. I guess I just want to make sure improvements to the release get back in to master, because they are good contributions.

**Comment by joachifm** [comment]
Yes, I also think fixes should go into either master or staging (if applicable) before release just for that reason

**Comment by joachifm** [comment]
Annoyingly, the test works on master, so I think I'll have to pick into staging to maintain a sensible commit history ... The situation is a bit messy atm, it's not always easy to see what the best course of action is.

**Pull request closed without merging**
