### PR TITLE
merge master into staging

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

I want to push the rest of `libcardiacarrest` switch (see #35374), but it's a mass-rebuild, so I need this.

~~I'm sure I screwed up some of the `src` hashes, because some packages switched `src` sources. Currently building the new `stdenv` to check it.~~

- [X] Conflicted `src` build.

### CODE REVIEW

**Comment by oxij** [comment]
Btw, @grahamc, is it possible to make ofborg test mergability with staging too?

**Comment by oxij** [comment]
@GrahamcOfBorg build systemd epoxy gtk3 python3Packages.asgiref python3Packages.daphne

**Comment by oxij** [comment]
Requesting review of the resolved conflicts from @shlevy @xeji @lsix @FRidh.

**Comment by oxij** [comment]
LGTM. No longer WIP.

**Comment by xeji** [comment]
`pkgs/development/libraries/epoxy/default.nix` LGTM.

**Comment by FRidh** [comment]
Thanks. Paths with conflicts:
```
        both modified:   pkgs/development/libraries/epoxy/default.nix
        both modified:   pkgs/development/libraries/gtk+/3.x.nix
        both modified:   pkgs/development/python-modules/asgiref/default.nix
        both modified:   pkgs/development/python-modules/daphne/default.nix
        both modified:   pkgs/os-specific/linux/systemd/default.nix
```
The Python modules look fine. 

@shlevy @aszlig can you check the merge of systemd?

**Comment by aszlig** [comment]
@FRidh: :+1: - Diffed against a rebase and the contents of `systemd/default.nix` match with the contents of the merge commit.

**Comment by shlevy** [comment]
Will merge at the sooner of @lsix's positive review or a day.

**Comment by lsix** [comment]
Hi all, sorry for the delay.

I have checked and tested the parts I am involved with. Everything is fine for me.

@shlevy you can merge when you like.

**Pull request merged**
