### PR TITLE
Remove system config kernel parameter

### LINKED ISSUE #60184: Delete systemConfig kernel parameter?
While working on booting my Chromebook, @grahamc, @cleverca22, @samueldr, @lheckemann and me noticed that lot of scripts (for example the bit that generates GRUB `menuentry`s) set the kernel parameter `systemConfig=${config.system.build.toplevel}` but nothing appears to use it.

We should find out what it was good for, when the last use case was removed, whether it's still desired and thus whether we should remove it everywhere. 

Uses in nixpkgs commit 05a53ecd827c5910e34171e7681c56913b29add1:

```
% git grep systemConfig
nixos/modules/installer/cd-dvd/system-tarball-fuloong2f.nix:      init=/boot/init systemConfig=/boot/init ${toString config.boot.kernelParams}
nixos/modules/installer/cd-dvd/system-tarball-pc.nix:      append ip=dhcp nfsroot=/home/pcroot systemConfig=${config.system.build.toplevel} init=${config.system.build.toplevel}/init rw
nixos/modules/installer/cd-dvd/system-tarball-pc.nix:      append initrd=initrd ip=dhcp nfsroot=/home/pcroot systemConfig=${config.system.build.toplevel} init=${config.system.build.toplevel}/init rw
nixos/modules/misc/crashdump.nix:        --command-line="systemConfig=$(readlink -f /run/current-system) init=$(readlink -f /run/current-system/init) irqpoll maxcpus=1 reset_devices ${kernelParams}"
nixos/modules/profiles/docker-container.nix:    ln -fs $systemConfig/init /init
nixos/modules/system/activation/activation-script.nix:            systemConfig=@out@
nixos/modules/system/activation/activation-script.nix:            # The readlink is there to ensure that when $systemConfig = /system
nixos/modules/system/activation/activation-script.nix:            ln -sfn "$(readlink -f "$systemConfig")" /run/current-system
nixos/modules/system/activation/top-level.nix:      substituteInPlace $out/init --subst-var-by systemConfig $out
nixos/modules/system/boot/loader/generic-extlinux-compatible/extlinux-conf-builder.sh:    echo "  APPEND systemConfig=$path init=$path/init $extraParams"
nixos/modules/system/boot/loader/grub/install-grub.pl:        "systemConfig=" . Cwd::abs_path($path) . " " .
nixos/modules/system/boot/loader/init-script/init-script-builder.sh:      echo "export systemConfig=$(readlink -f $path)"
nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py:    kernel_params = "systemConfig=%s init=%s/init " % (generation_dir, generation_dir)
nixos/modules/system/boot/stage-2-init.sh:systemConfig=@systemConfig@
nixos/modules/system/boot/stage-2-init.sh:echo "booting system configuration $systemConfig" > /dev/kmsg
nixos/modules/system/boot/stage-2-init.sh:$systemConfig/activate
nixos/modules/system/boot/stage-2-init.sh:ln -sfn "$systemConfig" /run/booted-system
nixos/modules/virtualisation/lxc.nix:    systemConfig =
nixos/modules/virtualisation/lxc.nix:    environment.etc."lxc/lxc.conf".text = cfg.systemConfig;
```

### PR DESCRIPTION
**Pull request by xaverdh**
###### Motivation for this change
Picking up https://github.com/NixOS/nixpkgs/pull/60256.
closes https://github.com/NixOS/nixpkgs/issues/60184

###### Things done

I ran the boot tests (`nix-build -A nixosTests.boot`) locally.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xaverdh** [comment]
The EditorConfig failure is likely unrelated?

**Comment by SuperSandro2000** [comment]
> The EditorConfig failure is likely unrelated?

but you can fix it anyway, right?

**Comment by xaverdh** [comment]
> > The EditorConfig failure is likely unrelated?
> 
> Can you fix it anyway, please?

I pushed the whitespace normalization as a separate commit (shout if you want it squashed instead).

**Comment by xaverdh** [comment]
cc @samueldr @nh2 @flokli

**Comment by Ma27** [comment]
Don't you think that unindenting the generated bash code will make it harder to read the resulting script (which can become necessary when e.g. debugging a system)?

**Comment by xaverdh** [comment]
> Don't you think that unindenting the generated bash code will make it harder to read the resulting script (which can become necessary when e.g. debugging a system)?

ah right, I trusted the editorconfig plugin to do the right thing when normalizing. Feel free to revert the relevant commit (0e8d7f9b3dabef47226a63654d4bba08aa438972) for now, its not the important part of this pr.

**Comment by Ma27** [comment]
@SuperSandro2000 what do you think of this? I'd actually prefer a revert.

That said, I'd like to emphasize that I'm not a big fan of - especially that huge - cosmetic changes during regular development since this makes reviews even harder. I mean I'm well-aware of the possibility of per-commit reviews, but why throwing away the "Files changed"-feature? This can be easily done in its own PR.

**Comment by flokli** [comment]
This is merged with a merge commit (not a squash-merge), which retains original individual commits in here, so an individual review is possible by looking at the git log, or looking at individual commits from the web interface.

The only thing that's a bit messy here is the "Files changed" tab, in its default view. However, you can also tell GitHub to hide whitespace changes:

github-whitespace

I don't really see what a (partial) revert would help here. The code changes and whitespace changes are in different commits, putting it into separate PRs wouldn't change anything here.

**Comment by Ma27** [comment]
And what about the unindented (and IMHO harder to read) bash script generated by `install-grub.pl`?

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 what do you think of this? I'd actually prefer a revert.

I just wanted to have those tabs replaced with spaces not a full whitespace normalization.

**Comment by xaverdh** [comment]
pr is [here](https://github.com/NixOS/nixpkgs/pull/113887)

**Pull request merged**
