### PR TITLE
coreboot-utils: fix cross-compilation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build pkgsCross.aarch64-multiplatform.coreboot-utils

**Comment by felixsinger** [comment]
Awesome. Will try that out. Thanks :)

**Comment by amjoseph-nixpkgs** [comment]
@felixsinger do you have any objections to this?

**Comment by amjoseph-nixpkgs** [comment]
@ofborg eval

**Pull request merged**
