### PR TITLE
libreoffice-fresh: 7.0.3.1 -> 7.0.4.2

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@ofborg build libreoffice-fresh

**Comment by 7c6f434c** [comment]
That unexpected failure looks transient, but I want to be sure…

**Comment by TredwellGit** [comment]
I don't just check the things done boxes without actually doing them.

**Comment by 7c6f434c** [comment]
>I don't just check the things done boxes without actually doing them.

Sorry if it looked like distrust which it is not, it is just that there are problems that still appear after the submitter have built succesfully.

The problem is that the fixed-output derivations can sometimes succeed to build if you have something with that hash and name but obtained from a different URL, and sometimes there's upstream changing tarballs or moving the download server or something. In all such cases a local nix-build will still succeed for you. I surely believe you have properly done everything you report as succesful; I just want to get a confirmation that none of the unfortunately-not-that-weird cases that are very much more annoying to check locally than via a rebuild elsewhere has happenned and gone unnoticed.

**Review by mohe2015 — APPROVED** [review]
Tested but didn't do anything complicated.

**Pull request merged**
