### PR TITLE
mindustry: 126.2 → 140.4

### PR DESCRIPTION
**Pull request by chkno**
###### Description of changes
This is the big update, releasing the last 1.5 years of development out of beta, with the new planet Erekir: https://store.steampowered.com/news/app/1127400/view/3415444546227810671

Also, get back to using the latest Java and gradle versions (as enabled and required by https://github.com/Anuken/Mindustry/issues/5114 )

Also, eliminate more (maybe the last of?) uses of binaries-not-built-here.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

This is follow-up from https://github.com/NixOS/nixpkgs/pull/198323

FYI:
Mindustry maintainer @fgaz
Other folks that have done mindustry version bumps @maxhbr @Mindavi

### CODE REVIEW

**Review by fgaz — APPROVED** [review]
Great work, thank you! What about adding yourself to meta.maintainers?

**Review by pyrox0 — APPROVED** [review]
LGTM!

**Comment by Mindavi** [comment]
Great that you managed to get this all building! Didn't test (yet), but the diff looks good on a first look.

**Comment by twitchyliquid64** [comment]
I was able to build this and test it successfully on an online server! Unfortunately the audio didnt work.

Debugging with:

```diff
diff --git a/pkgs/games/mindustry/default.nix b/pkgs/games/mindustry/default.nix
index 51d8577caa7..5bad0196007 100644
--- a/pkgs/games/mindustry/default.nix
+++ b/pkgs/games/mindustry/default.nix
@@ -159,6 +161,7 @@ stdenv.mkDerivation rec {
     sed -ie "/curl.*glew/{;s#curl -o #cp ${glewSource} #;s# -L http.*\.zip##;}" Arc/backends/backend-sdl/build.gradle
     sed -ie "/curl.*sdlmingw/{;s#curl -o #cp ${SDLmingwSource} #;s# -L http.*\.tar.gz##;}" Arc/backends/backend-sdl/build.gradle

+    sed -ie "s#-DWITH_MINIAUDIO#-DWITH_MINIAUDIO -DMA_DEBUG_OUTPUT#g" Arc/arc-core/build.gradle

     pushd Mindustry
   '' + optionalString enableClient ''

[xxx@xxx:~/projects/nixpkgs]$
```

We get the following output:

```
[I] [Core] Initialized SDL v2.24.0
DEBUG: Failed to initialize WASAPI backend.
DEBUG: Failed to initialize DirectSound backend.
DEBUG: Failed to initialize WinMM backend.
DEBUG: Failed to initialize Core Audio backend.
DEBUG: Failed to initialize sndio backend.
DEBUG: Failed to initialize audio(4) backend.
DEBUG: Failed to initialize OSS backend.
DEBUG: Attempting to initialize PulseAudio backend...
DEBUG: Loading library: libpulse.so
INFO: Failed to load library: libpulse.so
DEBUG: Loading library: libpulse.so.0
INFO: Failed to load library: libpulse.so.0
DEBUG: Failed to initialize PulseAudio backend.
DEBUG: Attempting to initialize ALSA backend...
DEBUG: Loading library: libasound.so.2
INFO: Failed to load library: libasound.so.2
DEBUG: Loading library: libasound.so
INFO: Failed to load library: libasound.so
DEBUG: [ALSA] Failed to open shared object.
DEBUG: Failed to initialize ALSA backend.
DEBUG: Attempting to initialize JACK backend...
DEBUG: Loading library: libjack.so
INFO: Failed to load library: libjack.so
DEBUG: Loading library: libjack.so.0
INFO: Failed to load library: libjack.so.0
DEBUG: Failed to initialize JACK backend.
DEBUG: Failed to initialize AAudio backend.
DEBUG: Failed to initialize OpenSL|ES backend.
DEBUG: Failed to initialize Web Audio backend.
DEBUG: Failed to initialize Custom backend.
DEBUG: Failed to initialize Null backend.
[E] Failed to initialize audio, disabling sound: arc.util.ArcRuntimeException: Other error
	at arc.audio.Soloud.init(Native Method)
	at arc.audio.Audio.initialize(Audio.java:41)
	at arc.audio.Audio.<init>(Audio.java:30)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:42)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```

Which suggests it cannot find the right libraries.

**Comment by fgaz** [comment]
It worked for me, but I use pipewire with pulse, jack, and alsa enabled. What audio server do you use @twitchyliquid64? Pulseaudio I suppose?

**Comment by fgaz** [comment]
@twitchyliquid64 what happens if add something like [this](https://github.com/NixOS/nixpkgs/blob/f0609d6c0571e7e4e7169a1a2030319950262bf9/pkgs/games/shattered-pixel-dungeon/default.nix#L71) to `installPhase`?

**Comment by Mindavi** [comment]
I am seeing the exact same issue:

```
[I] [Core] Initialized SDL v2.24.2
[E] Failed to initialize audio, disabling sound: arc.util.ArcRuntimeException: Other error
        at arc.audio.Soloud.init(Native Method)
        at arc.audio.Audio.initialize(Audio.java:41)
        at arc.audio.Audio.<init>(Audio.java:30)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:42)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

[I] [GL] Version: OpenGL 4.6.0 / Intel / Mesa Intel(R) HD Graphics 530 (SKL GT2)
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 17.0.4
[I] [RAM] Available: 7.8 GB
[I] [Mindustry] Version: 140.3
[I] Total time to load: 3373ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 26 community servers.
```

I'll see if adding pulseaudio works for me.

**Comment by chkno** [comment]
Thank you for the feedback, @fgaz, @theHedgehog0, @Mindavi, and @twitchyliquid64!  I've updated this PR:

* Sound is fixed
* 140.4 was released, so go for that instead of 140.3
* Added myself to maintainers

**Comment by fgaz** [comment]
@GrahamcOfBorg build mindustry-server

**Review by fgaz — APPROVED** [review]
Looks good, let's merge. Just in time for the branch-off too!

**Comment by twitchyliquid64** [comment]
I can confirm sounds works for me with this PR!

**Pull request merged**
