### PR TITLE
stripe-cli: 1.8.4 -> 1.8.8

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Description of changes

Bumps `stripe-cli` to `1.8.8`

also:

Added ldflags
  -s -w makes the binary 2MB smaller
  -X ... adds the version details (without a v prefix like the official release, see screenshot)
image
Added the tests
Added shell completions
Added changelog and longDescription
Added myself as a maintainer

cc: @RaghavSood

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 167586` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stripe-cli</li>
  </ul>
</details>

**Comment by techknowlogick** [comment]
Result of `nixpkgs-review pr 167586` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>stripe-cli</li>
  </ul>
</details>

**Comment by techknowlogick** [comment]
Test fail with:
```
=== RUN   TestLookUpLatestVersion
    plugin_test.go:19:
                Error Trace:    plugin_test.go:19
                Error:          Not equal:
                                expected: "2.0.1"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -2.0.1
                                +
                Test:           TestLookUpLatestVersion
--- FAIL: TestLookUpLatestVersion (0.00s)
```

**Comment by 06kellyjac** [comment]
Interesting. Ill have a play with this tomorrow and either fix it or turn off tests for darwin

**Comment by 06kellyjac** [comment]
Ok tests now pass on my aarch64 linux box and I raised an issue upstream

image

**Comment by techknowlogick** [comment]
Result of `nixpkgs-review pr 167586` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stripe-cli</li>
  </ul>
</details>

**Review by techknowlogick — APPROVED** [review]

**Comment by 06kellyjac** [comment]
rebased since #167087 was merged

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 167586` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stripe-cli</li>
  </ul>
</details>

**Comment by 06kellyjac** [comment]
@ofborg eval

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 167586` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stripe-cli</li>
  </ul>
</details>

**Pull request merged**
