### PR TITLE
unicorn: fix build on riscv

### PR DESCRIPTION
**Pull request by patryk4815**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
See https://github.com/NixOS/nixpkgs/pull/274827, gcc13 in staging fixes this issue once and for all.

**Comment by patryk4815** [comment]
@NickCao I known this PR. But it don't help with this package. On gcc13 it still fails.

**Comment by NickCao** [comment]
> @NickCao I know this PR. But it don't help with this package. On gcc13 it still fails (tested on master with gcc13Stdenv.mkDerivation)

Indeed, I'm able to reproduce the build failure. Thanks for the fix.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 275084` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>adenum</li>
    <li>gef</li>
    <li>pwndbg</li>
    <li>pwntools (python311Packages.pwntools)</li>
    <li>pwntools.dist (python311Packages.pwntools.dist)</li>
    <li>python310Packages.pwntools</li>
    <li>python310Packages.pwntools.dist</li>
    <li>python310Packages.qiling</li>
    <li>python310Packages.qiling.dist</li>
    <li>python310Packages.unicorn</li>
    <li>python310Packages.unicorn.dist</li>
    <li>python311Packages.angr</li>
    <li>python311Packages.angr.dist</li>
    <li>python311Packages.angrcli</li>
    <li>python311Packages.angrcli.dist</li>
    <li>python311Packages.angrop</li>
    <li>python311Packages.angrop.dist</li>
    <li>python311Packages.qiling</li>
    <li>python311Packages.qiling.dist</li>
    <li>python311Packages.unicorn</li>
    <li>python311Packages.unicorn.dist</li>
    <li>unicorn</li>
  </ul>
</details>

Tested building `pkgsCross.riscv64.unicorn` with both `gcc12Stdenv` and `gcc13Stdenv`.

**Comment by wtdcode** [comment]
How does this get reproduced? I'm happy to backport it.

**Comment by NickCao** [comment]
> How does this get reproduced? I'm happy to backport it.

I was using cross compilation (building `.#pkgsCross.riscv64.unicorn`), in short the proper fix would be to add `-latomic` to linker flag in upstream cmake files whenever the host platform requires it.

**Comment by patryk4815** [comment]
I added comment there: https://github.com/unicorn-engine/unicorn/issues/1840#issuecomment-1869035939 ;)

**Pull request merged**
