### PR TITLE
prosody: add cloud_notify_encrypted module

### PR DESCRIPTION
**Pull request by martinetd**
###### Motivation for this change

I've been pointed out in https://github.com/tigase/siskin-im/issues/177 that this module exists: https://modules.prosody.im/mod_cloud_notify_encrypted
regardless of my success with the actual issue linked I think the module would be useful in general.

I'm not sure what to do with new modules, should I add it with default enable=false for a while first?

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by martinetd** [comment]
marking as draft as I don't have time to look at test failures right now.
I'd like to finish getting siskin to work first, after another look there are other cloud modules that might be useful (although I don't know if required); it might make sense to regroup them in a "siskin" suboption as they appear specific from what I can see (protocols not made into XEP yet)... but I still haven't gotten it to work yet, and it looks like prosody's fault (it's not sending jingles in push messages) -- I'll be asking the prosody list for help.

**Comment by NickCao** [comment]
superseded by later updates.

**Comment by martinetd** [comment]
> superseded by later updates.

No, it's not. The cloud_modify_encrypted has not been added (as an option or not) and I keep rebasing this patch everytime I update my system, thinking I should finish this someday, and forgetting again immediately.

Anyway, I'll reopen when I've had time to look at why tests failed with that... :|

**Comment by martinetd** [comment]
grmbl github won't let me re-open this after rebase...
I've opened #213320 as draft to re-run tests and have a new look.

**Pull request closed without merging**
