### PR TITLE
nixos/emby : use the dataDir option

### PR DESCRIPTION
**Pull request by Vskilet**
###### Motivation for this change
Before this contribution, dataDir was not use by emby when you launch 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
@Vskilet 
Looks good. Though there's the conflict because of bb06b5b442c132a4cd3db41ab615cd49e5ee21b7

**Comment by worldofpeace** [comment]
cc @timokau @xeji

**Review by timokau — CHANGES_REQUESTED** [review]
Please rebase.

**Comment by Vskilet** [comment]
Mmmmh ... I think that not I would like to do

**Pull request closed without merging**
