### PR TITLE
Pharo VM (64b) for Pharo 7 and Pharo 8 images

### PR DESCRIPTION
**Pull request by rydnr**
###### Motivation for this change

Current Pharo package (specifically, spur64) contains a Smalltalk VM that doesn't work correctly with Pharo 7 and Pharo 8 images. It shows a blank screen. Also, some recent Pharo distributions (such as GToolkit https://github.com/feenkcom/gtoolkit) require libmoz2d to be installed.

This PR includes the work from @lukego for spur64. For 32b there's still some work to be done, so it's left as is.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rydnr** [comment]
I'm not sure how to fix the checks above.

**Comment by lukego** [comment]
Great work!

**Comment by alyssais** [comment]
Please rebase this on nixpkgs master.

**Comment by maxkrieger** [comment]
Any updates on this?

**Comment by rydnr** [comment]
I created another PR: #66387

**Pull request closed without merging**
