### PR TITLE
dwarf-fortress: 0.47.02 -> 0.47.04

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
lots of bug fixes

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
cc @shazow

**Comment by doom3wasagoodgame** [comment]
LGTM :+1:

**Review by shazow — APPROVED** [review]
Haven't had a chance to try it yet but the diff looks good.

**Review by ghost — APPROVED** [review]

**Comment by jonringer** [comment]
```
[4 built]
https://github.com/NixOS/nixpkgs/pull/82431
5 package built:
dwarf-fortress dwarf-fortress-packages.dwarf-fortress-full dwarf-fortress-packages.dwarf-fortress-original dwarf-therapist dwarf-fortress-packages.dwarf-therapist-original
```

**Pull request merged**
