### PR TITLE
xpra: 0.14.19 -> 0.15.3

### PR DESCRIPTION
**Pull request by akaWolf**
Update xpra from 0.14.19 to 0.15.3
Also preferably, if someone, who already used xpra test new version.

### CODE REVIEW

**Comment by ts468** [comment]
@akaWolf Thanks a lot!

**Comment by domenkozar** [comment]
Gtk3 version is broken, anyone cares about it?

**Comment by ts468** [comment]
On 03/09/2016 03:57 PM, Domen Kožar wrote:
> Gtk3 version is broken, anyone cares about it?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/9185#issuecomment-194333064
>
Thanks! Xpra 0.16 is released by now. I might have a look if that helps.

**Comment by ts468** [comment]
@domenkozar: #13810 should fix it.

**Pull request merged**
