### PR TITLE
flashrom: Add support for Segger J-Link devices

### PR DESCRIPTION
**Pull request by felixsinger**
###### Motivation for this change
Rework the flashrom package so that all compiler options of flashrom can be used and add the build option `jlinkSupport` which allows using Segger J-Link devices. See the commit messages for more information.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by felixsinger** [comment]
Depends on #140901

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]

**Comment by felixsinger** [comment]
Oops, I just noticed that I added gcc9Stdenv to the patch which adds J-Link support. Fixed now.

**Comment by felixsinger** [comment]
What is left here? I would like to get this merged.

**Review by c0d3z3r0 — CHANGES_REQUESTED** [review]

**Review by c0d3z3r0 — APPROVED** [review]

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 140902` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flashrom</li>
  </ul>
</details>

**Comment by felixsinger** [comment]
@Lassulus Thanks a lot!

**Pull request merged**
