### PR TITLE
[WIP] apache pulsar 2.4.0 pkg

### PR DESCRIPTION
**Pull request by aahmed-se**

### CODE REVIEW

**Comment by Zhen-hao** [comment]
@aahmed-se do you plan to submit a pull request?
I will be happy to contribute :)

**Comment by aahmed-se** [comment]
@Zhen-hao not currently you can go ahead and give it a shot.

**Comment by Zhen-hao** [comment]
cool. we will try to upgrade to 2.5.0 and merge

**Comment by aahmed-se** [comment]
closing this as this is superseded by this pr
https://github.com/NixOS/nixpkgs/pull/91837

**Pull request closed without merging**
