### PR TITLE
Add packages for a number of fonts.

### PR DESCRIPTION
**Pull request by rycee**
These are some packages for some nice fonts I like. Some of these also add fontconfig configs to establish aliases with popular Microsoft fonts but I am uncertain what is the best way to install those. I've manually added

``` xml
<include ignore_missing="yes">~/.nix-profile/etc/fonts/conf.d</include>
```

to my `fonts.conf` file but some more smooth solution should hopefully be possible.

The added fonts are
- Caladea,
- Carlito,
- Comfortaa,
- Comic Relief,
- Fantasque Sans Mono,
- Lobster Two,
- Pecita,
- Quattrocento, and
- Quattrocento Sans.

Also added is a set "fonts" giving, for example, Pecita the attribute path "fonts.pecita". Again, I am not certain if this would be considered best practice or I instead should put them in the "global path".

### CODE REVIEW

**Comment by vcunat** [comment]
- The ``fonts`` attribute: up to now we were putting almost everything directly into the top level, including all fonts AFAIK. I would either have *all* fonts under the attribute or none. Also, I think we would need ``recurseIntoAttrs`` for the fonts to be usable by nix-env.

- Installable ``fonts.conf`` files: this use case hasn't occurred to me. /cc @ttuegel, @lethalman. At first blush, I think we should add this to the default font config (to cover both nix-env and systemPackages):
 ```
<include ignore_missing="yes">~/.nix-profile/etc/fonts/conf.d</include>
<include ignore_missing="yes">/run/current-system/sw/etc/fonts/conf.d</include>
 ```
 Which reminds me that there's special ``fonts.fonts`` not covered by either... I don't know right now what's best.

**Comment by rycee** [comment]
Agreed about having either all fonts under the fonts attribute or none. For this I have no preference one way or another, I mainly liked having fonts somewhat more easily discoverable.

An additional complication about the fonts config is that you may or may not want to have a particular configuration enabled. For example, if you already have the Microsoft core fonts installed then you may not want to have "Comic Relief" install itself as an alias for "Comic Sans". The way, for example, Debian solves this is to have the font package install its configuration file into `/etc/fonts/conf.avail/` and symlink to it from `/etc/fonts/conf.d/`. If you then don't want a particular configuration enabled you remove the corresponding symlink from `/etc/fonts/conf.d/`.

**Comment by rycee** [comment]
I have now force-pushed an updated commit which no longer contains a `fonts` set. Instead the derivations are placed as attributes directly in all-packages.nix (together with existing fonts packages). I still am uncertain about the fontconfig configs, though. Would it be sufficient for now to have a boolean argument to the expression that enables/disables installation of the aliases? That is, something like `comic-relief.override { enableAlias = false; }` would not install the "Comic Sans MS" alias.

**Comment by vcunat** [comment]
Idea: what about naming each fontconfig file by the font-family name that it overrides. Those file collisions would then be resolved by standard priorities that users can set. (We would need to add some files of those names to the original fonts as well, e.g. valid empty font configs.)

**Comment by rycee** [comment]
@vcunat: That sounds really quite clever. I can give that a try. Haven't played around with priorities yet so I'm happy to get the practice :-)

**Comment by rycee** [comment]
I've force-pushed commits with the priority thing implemented. I've tried it out a bit and I think it works very well.

**Comment by vcunat** [comment]
It's probably fine. I'm sorry I took so long to get back.

**Comment by rycee** [comment]
That's ok. Thanks a lot for your input, I'm quite pleased with how it turned out.

**Pull request merged**
