### PR TITLE
thunderbird, thunderbird-bin: 68.1.1 -> 68.2.2 [Critical security fixes]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Critical security fixes
- Other updates

https://www.thunderbird.net/en-US/thunderbird/68.2.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2019-35/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Fuuzetsu, @nbp, @edolstra

### CODE REVIEW

**Comment by taku0** [comment]
Updated to 68.2.1.
cc @Fuuzetsu, @nbp, @edolstra

**Comment by taku0** [comment]
Updated to 68.2.2.
cc @Fuuzetsu, @nbp, @edolstra, @vcunat
Please review this.  Critical security fixes have been not merged for 2 weeks.

**Comment by andir** [comment]
The compilation fails on master. Probably due to some rustc version changes. On my 19.09 backport branch it works fine.

@taku0 Any idea if they already have a patch for newer rustc?

**Comment by taku0** [comment]
> @taku0 Any idea if they already have a patch for newer rustc?

I have no idea. FYI, `firefox` also suffers from the issue.
https://github.com/NixOS/nixpkgs/issues/73023

**Comment by andir** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1585223 seems to be relevant

**Comment by andir** [comment]
As it looks this time around Mozilla tries to dicatate older versions of rustc..
Here is another bugzilla entry on the same topic https://bugzilla.mozilla.org/show_bug.cgi?id=1585099

**Comment by andir** [comment]
@taku0 seems like you want to pick https://hg.mozilla.org/releases/mozilla-esr68/rev/f0020f517832 as patch on top of this

**Comment by taku0** [comment]
@andir 
The patch is already applied to 68.2.2, and I have removed it from `thunderbird/default.nix`.

**Comment by taku0** [comment]
Possible options:

- Wait for an upstream patch.
- Change `rustc` and related packages to have multiple `rustc` packages in nixpkgs.
- Write a patch ourselves.

**Comment by taku0** [comment]
Or just reverting `rustc`?

**Comment by taku0** [comment]
I'll try to have multiple `rustc` packages in nixpkgs.

**Comment by taku0** [comment]
I have confirmed that the error is same as `firefox` (#73023):

```
error[E0204]: the trait `Copy` may not be implemented for this type
  --> /build/objdir/x86_64-unknown-linux-gnu/release/build/style-f0201ccbb62104fd/out/gecko/structs.rs:23:297444
```

**Comment by taku0** [comment]
Made PR #73039 for rustc.  When #73039 is merged, I will rebase on it.

**Comment by taku0** [comment]
Built and ran `thunderbird` successfully with #73039.

**Comment by vcunat** [comment]
For 19.09 this seemed clear and worked for me well, so I pushed there already.

**Comment by taku0** [comment]
#73039 is merged.  Rebased on the master. Now it's ready to merge.

**Pull request merged**
