### PR TITLE
mitmproxy: 4.0.4 -> 5.1.1

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Version bump. I intended to port this to 20.03 but the `cryptography` update is problematic.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using
- [x] Tested execution of all binary files (mitmproxy works)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @orivej

### CODE REVIEW

**Comment by primeos** [comment]
Quick heads up that the `cryptography` update is already in staging: #84192

**Comment by rnhmjoj** [comment]
Ah, thank you. Should I move this to staging?

**Comment by primeos** [comment]
@rnhmjoj I think that would be a good/easy solution for this case (alternatively wait until #84442 is merged - but that might take a few days).

**Comment by rnhmjoj** [comment]
@primeos Ok, done!

**Comment by vcunat** [comment]
That iteration of `staging-next` is in master now.

**Comment by rnhmjoj** [comment]
Moved back to master. I tested mitmproxy again and it still works.

**Pull request merged**
