### PR TITLE
perl: 5.24.4 -> 5.28.0

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

```Perl 5.24``` [is deprecated upstream](https://www.cpan.org/src/README.html) so it might be gone in ```nixpkgs-18.09```

I have been using ```Perl 5.28``` as default NixOS Perl for about a month.

This PR includes https://github.com/NixOS/nixpkgs/pull/42659 as the first commit

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Let's build  a random package to check
@GrahamcOfBorg build perl522Packages.DBDSQLite perl524Packages.DBDSQLite perl526Packages.DBDSQLite perl528Packages.DBDSQLite

**Comment by volth** [comment]
@xeji: better talk to ofborg in https://github.com/NixOS/nixpkgs/pull/42659 because this PR rebuilds stdenv and likely any task will time out

**Comment by xeji** [comment]
oops, missed that. While we wait for the timeouts: would you prefer to have #42659 merged first and see what happens on hydra, or merge this right away?

**Comment by volth** [comment]
> would you prefer to have #42659 merged first and see what happens on hydra, or merge this right away?

My plan was https://github.com/NixOS/nixpkgs/issues/27610#issuecomment-403291770 but now we have little time until 18.09 split, ...

**Comment by xeji** [comment]
> My plan was #27610 (comment) but now we have little time until 18.09 split, ...

My quick one-package test in #42659 looked ok, and this LGTM.
So let's merge this and close #42659.

**Pull request merged**
