### PR TITLE
Rust updates

### PR DESCRIPTION
**Pull request by jgillich**
Currently fails to build cargo:

```
 Downloading regex v0.1.58 (registry file:///nix/store/xj4i6hmks3wv5mdnanncrn8kwwjzip0z-rustRegistry-2016-03-20-a8f5a24)
unable to get packages from source

Caused by:
  failed to parse manifest at `/nix/store/gqidn6a0k6sz7psxi0imnwfkhjij9lf3-cargo-2016-03-20-fetch/registry/src/-ce71226a1be9ab73/regex-0.1.58/Cargo.toml`

Caused by:
  expected a value of type `string` for the key `lib.name`
builder for ‘/nix/store/am9p1970s3a45hpq7f56nkcik22bzfj1-cargo-2016-03-20-fetch.drv’ failed with exit code 101
cannot build derivation ‘/nix/store/fx7lrj7kvbmypysx6i4cdrm7yrslzwrn-cargo-2016-03-20.drv’: 1 dependencies couldn't be built
```

Maybe someone knows what's going on here?

### CODE REVIEW

**Comment by jgillich** [comment]
Builds fine now, maybe just some temporary issue on crates.io. Can someone restart Travis and/or test locally?

**Comment by jgillich** [comment]
Turns out I also had to update cargo-snapshot, now this is blocked by https://github.com/alexcrichton/git2-rs/issues/119

**Comment by jgillich** [comment]
Turns out I also had to update cargo-snapshot, now this is blocked by https://github.com/alexcrichton/git2-rs/issues/119

**Comment by jgillich** [comment]
This should be it, finally. These build times are insane.

**Comment by jgillich** [comment]
ping @abbradar all done and working for me.

**Comment by abbradar** [comment]
Thanks! This will take a while to build...

**Comment by abbradar** [comment]
I got different hash for `exa`: `01ak7n7qkzs8jip8vhifmqhfm1xgjhr1qs532kblrw28gndp2pyi`

**Comment by jgillich** [comment]
The reason I updated exa was that Travis complained about a hash mismatch. So now it changed again? Hmm, not sure what to do about that..

**Comment by abbradar** [comment]
Well, I don't know of any stability issues with `fetchFromGitHub`. Let's run this separately (if possible, on several machines) and compare hashes.

**Comment by abbradar** [comment]
I ran `nix-build --check -A exa.src` several times -- hashes are consistent for me.

**Comment by jgillich** [comment]
On a DO vps:
```
output path ‘/nix/store/w7xm9dwjjn3y2fglr0dsiajaxmix3n0i-exa-2016-03-22-fetch’ has r:sha256 hash ‘18anwh235kzziq6z7md8f3rl2xl4l9d4ivsqw9grkb7yivd5j0jk’ when ‘1rg4gxx8m2q47m3mzlw3g4a6351dj513k9m740r0qh63p4v8yncc’ was expected
```
Which is actually the same as on Travis.

:confused:

**Comment by jgillich** [comment]
Changed the deps hash and managed to build it successfully - without touching src.

**Comment by abbradar** [comment]
Argh, now I think we have a problem -- I got yet another different hash `1rg4gxx8m2q47m3mzlw3g4a6351dj513k9m740r0qh63p4v8yncc`. We might need to check `fetchcargo` for determinism D: You haven't updated `exa`'s revision right now, haven't you?

**Comment by jgillich** [comment]
Nope, revision is still the same.

**Comment by abbradar** [comment]
Oh well. Let's merge this and open a bug! I can only hope that it's my connection or something.

**Pull request merged**
