### PR TITLE
phosh: 0.11.0 -> 0.12.0, phoc: 0.7.0 -> 0.7.1

### PR DESCRIPTION
**Pull request by zhaofengli**
###### Motivation for this change

See changelogs for [Phosh](https://source.puri.sm/Librem5/phosh/-/tags/v0.12.0) and [Phoc](https://source.puri.sm/Librem5/phoc/-/tags/v0.7.1).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128852` at 8cf86dbf run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>phoc</li>
    <li>phosh</li>
  </ul>
</details>

**Comment by tomfitzhenry** [comment]
The changelog for phosh 0.12.0 mentions that the following patches in other packages are needed:
* "glib: gdbusobjectmanagerclient: Call GetManagedObjects async. Otherwise gnome-calls and phosh will block on each other on startup blocking the whole UI."
* "wlroots (>= 0.12.0):  Layer shell restrictions. See #422. Otherwise phosh will fail to start."

Might be worth skipping 0.12.0?

**Comment by zhaofengli** [comment]
For the second one, we already use a patched version of wlroots 0.12.0. Not sure about the first one, but it might be an issue if people are already using the Calls app.

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM, hit me up when this should be merged

**Comment by tomfitzhenry** [comment]
> Not sure about the first one, but it might be an issue if people are already using the Calls app.

I use the Calls app, but I expect that's rare, and I think breakages are acceptable for now. I'm happy to maintain a local patch to keep using 0.11 for the sake of Calls.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 128852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>phoc</li>
    <li>phosh</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
The patch is in GTK 3.24.30.

**Pull request merged**
