### PR TITLE
tahoelafs: 1.10.0 -> 1.10.2

### LINKED ISSUE #9586: Tahoe-LAFS package is outdated
Currently, the [Tahoe-LAFS package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/p2p/tahoe-lafs/default.nix) is at 1.10.0, whereas the latest version is 1.10.2 (even though the download page still says 1.10.1).

cc @peti

### PR DESCRIPTION
**Pull request by ArdaXi**
This resolves #9586

Had to bump quite a fair number of packages, I don't think it broke much but I'm not entirely sure how to check other than open the PR and wait for the test.

There's a comment about bumping twisted causing carbon to break, but carbon seems to run fine with this.

### CODE REVIEW

**Comment by domenkozar** [comment]
Twisted is quite problematic, we have numerous attempts at bumping it but it breaks quite some packages.

**Comment by ArdaXi** [comment]
I asked on IRC and was told to simply try it. Otherwise, perhaps I should make it a multiversion?

**Comment by ArdaXi** [comment]
I asked on IRC and was told to simply try it. Otherwise, perhaps I should make it a multiversion?

**Comment by ArdaXi** [comment]
It seems like #1785 is the reason Twisted was downgraded from this version, I know at least a newer version of carbon actually likes 13.2.0, will have a look at graphite and whisper.

**Comment by domenkozar** [comment]
@ArdaXi sounds good

**Comment by ArdaXi** [comment]
Bumped carbon up to 0.9.15 now as well.

**Comment by nathan7** [comment]
@domenkozar Are there any current blockers for this?

**Comment by nathan7** [comment]
The service_identity package here appears to be identical to service-identity (they refer to the same PyPI package)

**Comment by garbas** [comment]
refractored expression a bit and merged it. tnx!

**Pull request closed without merging**
