### PR TITLE
haskell-hoodle: update to version 0.4

### PR DESCRIPTION
**Pull request by wavewave**
hoodle v0.4. hoodle is a pen note-taking program written in haskell.
- updated: `hoodle` `hoodle-builder` `hoodle-core` `hoodle-parser` `hoodle-render` `hoodle-types` `xournal-parser` `xournal-types`
- added: `hoodle-publish`

### CODE REVIEW

**Comment by peti** [comment]
Do you realize that we already have `hoodle 0.4` in `haskell-ng.packages.ghc784.hoodle`?

**Comment by wavewave** [comment]
oh. I didn't. that's great and thank you for letting me know!

**Comment by Fuuzetsu** [comment]
Shall we close the PR then?

**Comment by wavewave** [comment]
I am closing it.

**Comment by peti** [comment]
@wavewave, we're getting build errors in `hoodle-extra-0.1`:

    Preprocessing executable 'idfilepathdb' for hoodle-extra-0.1...

    exe/idfilepathdb.hs:35:18:
        Could not find module ‘DiffDB’
        Use -v to see a list of the files searched for.

**Comment by wavewave** [comment]
hoodle-extra needed to be upgraded. I haven't updated it with the new version of hoodle (in fact, many of its features got included in main hoodle) Thanks for the report!

**Pull request closed without merging**
