### PR TITLE
packagekit: add 'enableNixBackend' as an option 

### PR DESCRIPTION
**Pull request by ikervagyok**
###### Motivation for this change packagekit: add 'enableNixBackend' as an option 
packagekit doesn't compile on my computers because of a broken nix-backend.
i am not good at fixing cpp, so i cant really analyse the source. 

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
can you post the build error? maybe somebody has a good idea how to fix it.

**Comment by matthewbauer** [comment]
Looks like c94454a45a7410f9fdd84896c693c1c4df5e10f1 broke it.

**Comment by bendlas** [comment]
@ikervagyok this could be done by passing a `--disable-nix` configureFlag to the packagekit build. It wouldn't make much sense though, to have the nix build of packagekit not support the nix backend ;-)

@matthewbauer do you have time to fix packagekit for the newest nix and put those patches into our build until they have been released into packagekit itself?

**Comment by bendlas** [comment]
@Mic92 here is the build error: http://hastebin.com/tiyomifipe.log

**Comment by ikervagyok** [comment]
@bendlas: It was temporary, to fix my update/install issues and it raised the right amount of attention. Of course I'd love to see a correct fix asap, but I can't provide one. ;)

@matthewbauer: I was amazed when I  saw packagekit has support for nix. Keep it up!

**Pull request merged**
