### PR TITLE
miller: 5.10.3 -> 6.2.0

### LINKED ISSUE #163851: miller: needs update to 6.1.0
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: miller

current version: 5.10.3
desired version: 6.1.0

miller is now written in Go; there's still a configure script and a makefile, but I don't know if it's now more complicated to package because of fetching dependencies in a reproducible way or whatever.

###### Notify maintainers

maintainers: @mstarzyk

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by mstarzyk**
###### Description of changes
Fixes #163851.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
Thanks!

Fixes #163851 .
(above text might need to be in the PR description or commit message to auto-close, but that's fine :), at least want to link the two)

**Comment by mstarzyk** [comment]
I haven't checked my email for a while. Thanks for letting me know about #163851.
Updated the PR description.

**Comment by mstarzyk** [comment]
Version [6.2.0](https://github.com/johnkerl/miller/releases/tag/v6.2.0) was released in the meantime, so I updated this PR.

**Comment by rissson** [comment]
Could you squash your commits? Otherwise, LGTM.

**Comment by mstarzyk** [comment]
Squashed, thanks.

**Review by rissson — APPROVED** [review]

**Pull request merged**
