### PR TITLE
.github/workflows/update-terraform-providers.yml: re-enable 

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by zimbatm — APPROVED** [review]

**Comment by Mic92** [comment]
dry-run; https://github.com/NixOS/nixpkgs/actions/runs/3203347859

**Comment by Mic92** [comment]
```
Traceback (most recent call last):
  File "/nix/store/w67169jnq7c64x2kbk5xibqh9figky4k-update.py", line 244, in <module>
    main(args.max_workers, args.keep_going, args.commit, args.packages)
  File "/nix/store/w67169jnq7c64x2kbk5xibqh9figky4k-update.py", line 220, in main
    confirm = input('Press Enter key to continue...')
EOFError: EOF when reading a line
Press Enter key to continue...
Error: Process completed with exit code 1.
```

**Comment by zowoq** [comment]
oops, not sure how I missed that.

**Comment by zowoq** [comment]
Looks like there isn't a nice way of avoiding the prompt.

https://github.com/ryantm/nixpkgs-update/blob/ec0092589a8cf9ac040a1420696c93d0a2bb063f/src/Nix.hs#L355
```
    TP.setStdin (TP.byteStringInput "\n") $
    proc "timeout" [T.unpack timeout, "nix-shell", "maintainers/scripts/update.nix", "--argstr", "package", T.unpack attrPath ]
```

https://github.com/NixOS/nixpkgs/pull/194907

**Comment by zowoq** [comment]
now it's working: https://github.com/NixOS/nixpkgs/pull/194984

**Pull request merged**
