### PR TITLE
neochat: 1.0.1 -> 1.1.1

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Bumps libquotient as part of this. Also tested with quaternion, which is also working.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build quaternion

**Comment by peterhoeg** [comment]
Fixed #112542

**Comment by peterhoeg** [comment]
Cc @crazazy

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114193` at a254d117 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/15f2feb6c577e5f9f66578dd5538a39d">neochat</a></li></li>
    <li><a href="https://gist.github.com/5df7ab11933ce61d98b05173b1bc0c5c">quaternion</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `qtbase`.
Near pkgs/applications/networking/instant-messengers/neochat/default.nix:6:3:
```
  |
6 | , qtbase
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `qttools`.
Near pkgs/applications/networking/instant-messengers/neochat/default.nix:7:3:
```
  |
7 | , qttools
  |   ^
```
</li>
  </ul>
</details>

**Review by mjlbach — APPROVED** [review]
LGTM

**Review by mjlbach — APPROVED** [review]

**Pull request merged**
