### PR TITLE
foundationdb: add fdb 6.1 with cmake build

### PR DESCRIPTION
**Pull request by thoughtpolice**
###### Motivation for this change

FoundationDB 6.1 is going to ship somewhat soon(-ish) and has a new CMake build system. While it would have been possible to keep wobbling on with the old one (a strange beast), CMake has a number of advantages and the overall result for the 6.1+ builds is looking much cleaner in the future with minimal patching, no old boost, or GCC 4.9, etc.

Some notes:

  - Allow usage of `clang` and `libcxx` as the stdenv if `useClang = true`. This significantly shrinks (~45%) the resulting closure size because all foundationdb binaries are statically linked to their source code (effectively duplicating large amounts of the codebase in each binary). Enabled by default, tentatively.
    - LTO doesn't quite work right in some configurations, but should hopefully offer even further significant increases (~75%!) if we can figure it out.
    - LTO + LLD in `libcxxStdenv` needs investigation, it dramatically seems to reduce memory requirements but something weird happens and `libtls` doesn't get its `RPATH` appropriately set(????)
  - We only need *one* patch this time, which will hopefully be resolved upstream eventually. For us, this patch is completely positive and only fixes a build failure with libcxx. See the discussion in https://github.com/apple/foundationdb/pull/1533 for a path forwards.
  - The new build has a wonky layout in the install phase due to its strange `fdb_install` custom command, so unfortunately we still need a mostly custom install phase. I want to try and fix this so normal `ninja install` or whatever works (maybe I'm missing something) but it'll take more coordination upstream.
  - Tentatively using `gcc8Stdenv` for now as well, since it gives some binary size improvements. This can probably go away if we move to GCC 9.1 or something in `stdenv` (soon, hopefully!)
  - We now ship the tests that are run in the `.out` output. These are tiny compared to the binaries so it's not a big deal, but the improvement is that we can now run self-tests against any closures we build. (My intention is to eventually automate this and use it in some of the FoundationDB NixOS tests.)
    - Unfortunately, there's no way to get the enabled test list from CMake easily. :( I'd like to fix this upstream so we don't need `test-lists.txt`.

This is a draft and a WIP, but the core shape looks OK I guess. This expression is also very viable and suitable for development on FDB itself using `nix-shell '<nixpkgs>' -A foundationdb61 --pure`, etc.

###### Still TODO

- [x] Re-distribute the `fdb-java.jar` file again (should be easy, it gets built anyway).
- [x] Re-implement `.pythonsrc` so the Python bindings still work.
- [ ] I don't understand the `libtls` weirdness going on in the build system, it should just detect it from `buildInputs` I think...
- [x] ~Find a way to get rid of `test-lists.txt`~
  - This will probably take some work upstream, see [some forum discussion](https://forums.foundationdb.org/t/show-the-fdb-forums-prototyping-simulation-runs-on-kubernetes/1357/2). For now, this is alright I guess...
- [ ] Think about getting rid of older FoundationDB versions? Bonus points: we can finally get rid of `stdenv49` since nothing else needs it, and all the other old stuff! (The on-disk formats are still compatible, too!)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thoughtpolice** [comment]
@GrahamcOfBorg build foundationdb61 python3Packages.foundationdb61

**Comment by thoughtpolice** [comment]
Let's go ahead and merge this. The `libtls` shenanigans and old version support can be figured out a little later, plus some improvements to the `foundationdb` module will come soon hopefully...

**Comment by TimothyKlim** [comment]
@thoughtpolice Hi! Is there any chance that 6.1.8 (official release) will be released here soon? Thanks!

**Comment by thoughtpolice** [comment]
@TimothyKlim 2a56ea3593aa0702a61313572c2211ef947f4d1f

**Pull request merged**
