### PR TITLE
powerpipe: init at 0.2.0

### LINKED ISSUE #307970: Package request: powerpipe
**powerpipe**

Dynamically query your cloud, code, logs & more with SQL

This project is related to the already packaged steampipe project.

steampipe will be split up in 3 projects:

- steampipe
- powerpipe
- flowpipe

This issue tracks integrating powerpipe

**Metadata**

* platforms:  linux, darwin,
*  arch: amd64, arm64

```
  meta = {
    changelog = "https://github.com/turbot/powerpipe/blob/v${version}/CHANGELOG.md";
    description = "Dynamically query your cloud, code, logs & more with SQL";
    homepage = "https://powerpipe.io/";
    license = lib.licenses.agpl3Only;
    mainProgram = "powerpipe";
    maintainers = with lib.maintainers; [ weitzj ];
  };
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by weitzj**
This relates to the already packaged project: steampipe

## Description of changes

Fixes: https://github.com/NixOS/nixpkgs/issues/307970

Add new powerpipe.io package

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by weitzj** [comment]
@hardselius , @anthonyroussel  maybe you are interested in looking into this PR

**Comment by weitzj** [comment]
Hi @kashw2 . I  hope the new commits are better now.

**Comment by weitzj** [comment]
Build output from `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`


```
~/g/s/g/w/nixpkgs (fix/307970-add-powerpipe|✔) $ nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"  14:28:55
these 22 paths will be fetched (5.66 MiB download, 25.30 MiB unpacked):
  /nix/store/abnpppvp92svnb2sd9slqxl3l55knf1r-aws-c-auth-0.7.10
  /nix/store/c6r6dj48whdb8lvm1nvrigvd1nwwqf6d-aws-c-cal-0.6.9
  /nix/store/39zhpzmzwh15nv8f49zrvpvv3p28vx7d-aws-c-common-0.9.10
  /nix/store/sffijznrs0fzlgvfk175pn1lhkcizvjh-aws-c-compression-0.2.17
  /nix/store/rx751pf04m2hwg3zj8nnsq6ch6c34wgh-aws-c-event-stream-0.3.2
  /nix/store/lh85d9crjahnw5mm8qz0vsnmw9c3wmyk-aws-c-http-0.7.14
  /nix/store/yz49xlfsfpknmy0s2cq4hhchjmfvhs9y-aws-c-io-0.13.36
  /nix/store/a02h7cv3sa8pl8x1731b0k30c55klkpz-aws-c-mqtt-0.9.10
  /nix/store/vf0r2n1rij0s49893f1dd6fv548ix2v5-aws-c-s3-0.4.0
  /nix/store/y2w1smfydsmk1hwwksh38q8ki99b9dmf-aws-c-sdkutils-0.1.12
  /nix/store/pbf3ldj9swm1fnr13d6j9c024r3bhjww-aws-checksums-0.1.17
  /nix/store/w2b69ipfb6asgwpcf0mva4dykf33119n-aws-crt-cpp-0.24.7
  /nix/store/qbg99yh97w8dpkwqywq3fvv3d18rkm7v-aws-sdk-cpp-1.11.207
  /nix/store/4i41z0i5yfh83faaz4lj1jsh9nsdhxsj-boehm-gc-8.2.2
  /nix/store/j759rp0iz86id7g88gy5kmxb6mk7rhfy-busybox-static-aarch64-unknown-linux-musl-1.36.1
  /nix/store/gjg089iv44r3s9mkxvn7angdf906px0x-editline-1.17.1
  /nix/store/q3w39di4s1cr88lzjdad20gnmxkq8l03-libarchive-3.7.2-lib
  /nix/store/zkx66vk2g9mqkx44p02khpagzi6f9yvq-lowdown-1.1.0-lib
  /nix/store/3h4hxi8q9gr5zyhzfix3jxzhkzqn774q-nix-2.18.1
  /nix/store/7rxy4r52qbmxmd20cnrvx996z019a798-nix-2.18.1-man
  /nix/store/bv0qmvwdl8gb71i7vxifv1cp4pj7b77y-nixpkgs-review-2.10.3
  /nix/store/13v9v8190f4v14qcjd7z5ghcwpznj5i7-s2n-tls-1.4.1
copying path '/nix/store/j759rp0iz86id7g88gy5kmxb6mk7rhfy-busybox-static-aarch64-unknown-linux-musl-1.36.1' from 'https://cache.nixos.org'...
copying path '/nix/store/7rxy4r52qbmxmd20cnrvx996z019a798-nix-2.18.1-man' from 'https://cache.nixos.org'...
copying path '/nix/store/4i41z0i5yfh83faaz4lj1jsh9nsdhxsj-boehm-gc-8.2.2' from 'https://cache.nixos.org'...
copying path '/nix/store/gjg089iv44r3s9mkxvn7angdf906px0x-editline-1.17.1' from 'https://cache.nixos.org'...
copying path '/nix/store/39zhpzmzwh15nv8f49zrvpvv3p28vx7d-aws-c-common-0.9.10' from 'https://cache.nixos.org'...
copying path '/nix/store/13v9v8190f4v14qcjd7z5ghcwpznj5i7-s2n-tls-1.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/zkx66vk2g9mqkx44p02khpagzi6f9yvq-lowdown-1.1.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/q3w39di4s1cr88lzjdad20gnmxkq8l03-libarchive-3.7.2-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/c6r6dj48whdb8lvm1nvrigvd1nwwqf6d-aws-c-cal-0.6.9' from 'https://cache.nixos.org'...
copying path '/nix/store/sffijznrs0fzlgvfk175pn1lhkcizvjh-aws-c-compression-0.2.17' from 'https://cache.nixos.org'...
copying path '/nix/store/pbf3ldj9swm1fnr13d6j9c024r3bhjww-aws-checksums-0.1.17' from 'https://cache.nixos.org'...
copying path '/nix/store/y2w1smfydsmk1hwwksh38q8ki99b9dmf-aws-c-sdkutils-0.1.12' from 'https://cache.nixos.org'...
copying path '/nix/store/yz49xlfsfpknmy0s2cq4hhchjmfvhs9y-aws-c-io-0.13.36' from 'https://cache.nixos.org'...
copying path '/nix/store/rx751pf04m2hwg3zj8nnsq6ch6c34wgh-aws-c-event-stream-0.3.2' from 'https://cache.nixos.org'...
copying path '/nix/store/lh85d9crjahnw5mm8qz0vsnmw9c3wmyk-aws-c-http-0.7.14' from 'https://cache.nixos.org'...
copying path '/nix/store/abnpppvp92svnb2sd9slqxl3l55knf1r-aws-c-auth-0.7.10' from 'https://cache.nixos.org'...
copying path '/nix/store/a02h7cv3sa8pl8x1731b0k30c55klkpz-aws-c-mqtt-0.9.10' from 'https://cache.nixos.org'...
copying path '/nix/store/vf0r2n1rij0s49893f1dd6fv548ix2v5-aws-c-s3-0.4.0' from 'https://cache.nixos.org'...
copying path '/nix/store/w2b69ipfb6asgwpcf0mva4dykf33119n-aws-crt-cpp-0.24.7' from 'https://cache.nixos.org'...
copying path '/nix/store/qbg99yh97w8dpkwqywq3fvv3d18rkm7v-aws-sdk-cpp-1.11.207' from 'https://cache.nixos.org'...
copying path '/nix/store/3h4hxi8q9gr5zyhzfix3jxzhkzqn774q-nix-2.18.1' from 'https://cache.nixos.org'...
copying path '/nix/store/bv0qmvwdl8gb71i7vxifv1cp4pj7b77y-nixpkgs-review-2.10.3' from 'https://cache.nixos.org'...
no oauth token found for github.com
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
remote: Enumerating objects: 1619, done.
remote: Counting objects: 100% (1270/1270), done.
remote: Compressing objects: 100% (327/327), done.
remote: Total 1619 (delta 1031), reused 1118 (delta 927), pack-reused 349
Receiving objects: 100% (1619/1619), 1.63 MiB | 7.08 MiB/s, done.
Resolving deltas: 100% (1090/1090), completed with 309 local objects.
From https://github.com/NixOS/nixpkgs
 * [new branch]                master     -> refs/nixpkgs-review/0
$ git worktree add /home/weitz/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/nixpkgs 705bad7ed6014a9957cb43e426e310f581ca1100
Preparing worktree (detached HEAD 705bad7ed601)
Updating files: 100% (41258/41258), done.
HEAD is now at 705bad7ed601 Merge pull request #307483 from r-ryantm/auto-update/libgedit-gtksourceview
$ nix-env --extra-experimental-features no-url-literals --option system aarch64-linux -f <nixpkgs> --nix-path nixpkgs=/home/weitz/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/nixpkgs nixpkgs-overlays=/run/user/1000/tmppflmzafw -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
$ git merge --no-commit --no-ff 03c29612128b73f55928f48abcc97b8185d14e7b
Auto-merging maintainers/maintainer-list.nix
Automatic merge went well; stopped before committing as requested
$ nix-env --extra-experimental-features no-url-literals --option system aarch64-linux -f <nixpkgs> --nix-path nixpkgs=/home/weitz/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/nixpkgs nixpkgs-overlays=/run/user/1000/tmppflmzafw -qaP --xml --out-path --show-trace --no-allow-import-from-derivation --meta
1 package added:
powerpipe (init at 0.2.0)

$ nix build --nix-path nixpkgs=/home/weitz/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/nixpkgs nixpkgs-overlays=/run/user/1000/tmppflmzafw --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed -f /home/weitz/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/build.nix
1 package built:
powerpipe

$ /nix/store/3h4hxi8q9gr5zyhzfix3jxzhkzqn774q-nix-2.18.1/bin/nix-shell /home/weitz/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/shell.nix --nix-path nixpkgs=/home/weitz/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/nixpkgs nixpkgs-overlays=/run/user/1000/tmppflmzafw
Info: Your devbox environment may be out of date. Please run 

eval "$(devbox global shellenv --recompute)"

Sourcing pypa-build-hook
[nix-shell:~/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b]$ ls
build.nix  logs  nixpkgs  report.json  report.md  results  shell.nix

[nix-shell:~/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b]$ cd results/powerpipe/bin
[nix-shell:~/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/results/powerpipe/bin]$ ls
powerpipe

[nix-shell:~/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/results/powerpipe/bin]$ ./powerpipe 
Powerpipe: Dashboards for DevOps.
	
Visualize cloud configurations. Assess security posture against a
massive library of benchmarks. Build custom dashboards with code.
	
Common commands:
	
  # Install a mod from the hub - https://hub.powerpipe.io
  powerpipe mod init
  powerpipe mod install github.com/turbot/powerpipe-mod-aws-compliance

  # View dashboards at http://localhost:9033
  powerpipe server

  # List and run benchmarks in the terminal
  powerpipe benchmark list
  powerpipe benchmark run aws_compliance.benchmark.cis_v140
	
Documentation available at https://powerpipe.io/docs

Usage:
  powerpipe [--version] [--help] COMMAND [args] [flags]
  powerpipe [command]

Available Commands:
  benchmark   List, view, and run Powerpipe benchmarks
  control     List, view, and run Powerpipe controls
  dashboard   List, view, and run Powerpipe dashboards in batch mode
  help        Help about any command
  login       Login to Turbot Pipes
  mod         Powerpipe mod management
  query       List, view, and run Powerpipe queries
  server      Start Powerpipe dashboard server
  variable    Manage Powerpipe variables in the current mod and its direct dependents

Flags:
      --config-path string    Colon separated list of paths to search for workspace files, in order of decreasing precedence
  -h, --help                  help for powerpipe
      --install-dir string    Path to the installation directory (default "/home/weitz/.powerpipe")
      --mod-location string   Path to the workspace working directory (default "/home/weitz/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/results/powerpipe/bin")
  -v, --version               version for powerpipe
      --workspace string      Sets the Powerpipe workspace profile (default "default")

Use "powerpipe [command] --help" for more information about a command.

[nix-shell:~/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/results/powerpipe/bin]$ ldd ./powerpipe 
$	not a dynamic executable

[nix-shell:~/.cache/nixpkgs-review/rev-03c29612128b73f55928f48abcc97b8185d14e7b/results/powerpipe/bin]$ 
```

**Review by anthonyroussel — COMMENTED** [review]
Result of `nixpkgs-review pr 307971` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>powerpipe</li>
  </ul>
</details>

**Comment by weitzj** [comment]
Thank you @anthonyroussel

**Review by anthonyroussel — APPROVED** [review]
Welcome and congratulations for your first contribution to Nixpkgs!

**Review by winterqt — DISMISSED** [review]
Please update the message of the first commit to align with the commit message guidelines as well.

(Additionally, please squash the third and second commits while you're at it. 🙂)

**Comment by weitzj** [comment]
> Please update the message of the first commit to align with the commit message guidelines as well.
> 
> (Additionally, please squash the third and second commits while you're at it. 🙂)

Thank you @winterqt . I have updated the commit messages, squashed the second/third commit and rebased everything against the current `master`

**Review by anthonyroussel — APPROVED** [review]

**Comment by weitzj** [comment]
@winterqt  would you be so kind and review this PR again?

**Comment by weitzj** [comment]
@wegank  or @anthonyroussel  can somebody overrule the pending review? Or what is the project policy?

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 307971` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>powerpipe</li>
  </ul>
</details>

**Comment by weitzj** [comment]
Thank you

**Comment by weitzj** [comment]
@wegank  could you please add the `backport release-23.11` label? I think since I am a new maintainer in this MR, I cannot add the label myself, yet?

**Pull request merged**
