### PR TITLE
remind: use gitUpdater

### PR DESCRIPTION
**Pull request by afh**
* Use `nix-update-script` for automated updates using [r-ryantm](https://github.com/r-ryantm)

How would the current maintainers feel about me also becoming a maintainer for this package?
This would allow me to merge updates through r-ryantm created update PRs.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by afh** [comment]
Just learned from a link to [this comment](https://github.com/NixOS/nixpkgs/pull/349060#issuecomment-2418107015) that r-ryantm may be able to update this package with only the `src` changes from this PR.

Do any of the current maintainers have more insight into this?

**Comment by 7c6f434c** [comment]
I am not sure about the exact update logic

**Comment by 7c6f434c** [comment]
(OK with adding you as a maintainer)

**Review by 7c6f434c — APPROVED** [review]

**Comment by afh** [comment]
Thanks for the feedback everyone, and thanks for the invitation to become a maintainer of remind, which I'll gladly accept.

Let's see if we can get this merged before the next version of remind comes out :) I'm already seeing two beta having been published recently.

**Comment by afh** [comment]
Thanks for merging this, @7c6f434c, much appreciated 💯  I'm looking forward to seeing bot update PRs for this package 😃🤞

**Pull request merged**
