### PR TITLE
discord: use buildFHSUserEnv to avoid crashing

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
got tired of it crashing

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xfix** [comment]
This probably should be using `buildFHSUserEnvBubblewrap`.

**Comment by JJJollyjim** [comment]
@jonringer are you sure this solves the root cause, and not a second crash? The error message is "Cannot upload crash dump: cannot exec /usr/bin/wget"!

The crash I am aware of is #96063, which would be resolved by #93453

**Comment by JJJollyjim** [comment]
(the only place in the binary wget is referenced is in code that looks like it corresponds to this part of CEF: https://chromium.googlesource.com/chromium/src/+/470748ce474f8fce7a566eb570021273c88d04c0/components/crash/app/breakpad_linux.cc)

**Comment by jonringer** [comment]
@JJJollyjim yes, but allowing for the initial `/usr/bin/wget` to succeed makes the failure with libappindicator irrelevant.

**Comment by jonringer** [comment]
> probably should be using `buildFHSUserEnvBubblewrap` (see #55973).

done

**Comment by JJJollyjim** [comment]
@jonringer sorry, I'm still not sure I understand. My conception of what's happening:
* Discord is segfaulting in libappindicator, thus crashing
* As part of crashing, it tries to phone home with wget, and fails

It's going to crash either way right?

**Comment by jonringer** [comment]
@JJJollyjim  you're absolutely right, please look at https://github.com/NixOS/nixpkgs/pull/96296

**Pull request closed without merging**
