### PR TITLE
webkitgtk: fix build on aarch64-darwin

### PR DESCRIPTION
**Pull request by emilytrau**
###### Motivation for this change

Fixes webkitgtk build on Apple Silicon. Depends on #132270 #132271 #132272 . This PR won't get it fully building as it also requires aften, but #131666 depends on this PR.

Related issue: #131791

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
This breaks build on x86_64-darwin
https://logs.nix.ci/?key=nixos/nixpkgs.132273&attempt_id=6f7fc38c-146a-4d8e-9e57-3abff2655b71

**Comment by happysalada** [comment]
I'm trying to build this to give you more information as to where the failure can be exactly.
I'll update when the build finishes.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 132273` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>19 packages marked as broken and skipped:</summary>
  <ul>
    <li>almanah</li>
    <li>balsa</li>
    <li>gnome-recipes</li>
    <li>gnome.nautilus-python</li>
    <li>kicad-unstable-small</li>
    <li>mate.atril</li>
    <li>mate.mate-user-guide</li>
    <li>newsflash</li>
    <li>nyxt</li>
    <li>onboard</li>
    <li>python38Packages.wxPython_4_1</li>
    <li>python39Packages.wxPython_4_1</li>
    <li>quodlibet</li>
    <li>quodlibet-full</li>
    <li>quodlibet-without-gst-plugins</li>
    <li>quodlibet-xine</li>
    <li>quodlibet-xine-full</li>
    <li>skytemple</li>
    <li>vuze</li>
  </ul>
</details>
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>font-manager</li>
    <li>webkitgtk (gnome.webkitgtk)</li>
    <li>gnvim</li>
    <li>gnvim-unwrapped</li>
    <li>haskellPackages.gi-javascriptcore</li>
    <li>haskellPackages.gi-webkit2</li>
    <li>haskellPackages.gi-webkit2webextension</li>
    <li>luakit</li>
    <li>pdfpc</li>
    <li>rednotebook</li>
    <li>setzer</li>
    <li>surf</li>
  </ul>
</details>

**Comment by happysalada** [comment]
This seems to be the culprit
```
[861/4574] Linking CXX shared library lib/libjavascriptcoregtk-4.0.18.18.7.dylib^M[862/4574] Linking CXX
FAILED: Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/__/jsc.cpp.o
```

**Comment by angustrau** [comment]
Thanks for running a build for me @happysalada! I pulled out an old intel Mac and was able to do some more diagnoses. First to get past the linking error, I added `"-DUSE_LD_GOLD=OFF"` to cmakeFlags. That revealed that `darwin.usr-include` isn't the same as `darwin.apple_sdk.sdk` on x86-64, and is missing the `proc_pid_rusage` definition we are looking for. To explain the discrepency I dug into `usr-include`, which turns out pulls it's headers from `stdenv`. The purpose of the [original snippet](https://github.com/NixOS/nixpkgs/blob/a66d9f9b000f7ddf07d0a5ed1d729a1f36c179c6/pkgs/development/libraries/webkitgtk/default.nix#L180) that required the sdk was because this method didn't exist in `stdenv`! It seems that this workaround is no longer required in the `stdenv` shipped on aarch64. To test my hypothesis, I commented out the snippet on my aarch64 machine and was still able to build webkit. It seems like the actual solution might be to only build in this workaround on x86-64.

**Comment by happysalada** [comment]
So you want to leave the original code from the snippet and add a `!stdenv.Aarch64` ?
I'm happy to test when you get to it.

**Comment by happysalada** [comment]
Just found by accident a related PR
https://github.com/NixOS/nixpkgs/pull/126101
There might be stuff that you find interesting in there.

**Review by veprbl — APPROVED** [review]

**Comment by angustrau** [comment]
I'm happy to get this merged. Thanks @veprbl @thefloweringash @happysalada for all your help in tracking this one down!

**Comment by happysalada** [comment]
Thank you for the PR!

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 132273` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
