### PR TITLE
pythonPackages.afew: 3f1e5e9 -> 9744c18

### PR DESCRIPTION
**Pull request by datakurre**
Fixes issue with move mail and isync.

### CODE REVIEW

**Comment by fpletz** [comment]
I think it makes more sense to use a package name with git and timestamp here to fix upgrading with `nix-env`, like `afew-git-2015-01-30` because there doesn't seem to be any releases.

**Comment by datakurre** [comment]
@fpletz That certainly makes sense. Thanks. Better now?

**Comment by fpletz** [comment]
Thanks! Only one more thing: Please squash your commits and we're good to go!

**Comment by fpletz** [comment]
:beers:

**Pull request merged**
