### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents (soon)

Previous staging-next: #124095

### CODE REVIEW

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/1680187.html

zstd-1.5.0 on aarch64-darwin blocks ~25k jobs. :1st_place_medal:

**Comment by vcunat** [comment]
It looks good after that today's zstd merge: https://hydra.nixos.org/eval/1680489?filter=zstd

**Comment by r-burns** [comment]
Looks like gcc-unwrapped.x86_64-darwin ran out of disk space https://hydra.nixos.org/build/145529201

<details>

```
finding garbage collector roots...
deleting garbage...
deleting unused links...
waiting for the big garbage collector lock...
finding garbage collector roots...
deleting garbage...
deleting unused links...
waiting for the big garbage collector lock...
finding garbage collector roots...
deleting garbage...
deleting unused links...
waiting for the big garbage collector lock...
../../gcc-10.3.0/gcc/config/i386/sync.md:3388:1: fatal error: error writing to /private/tmp/nix-build-gcc-10.3.0.drv-0/ccjTDdpi.s: No space left on device
compilation terminated.
make[3]: *** [Makefile:1117: insn-emit.o] Error 1
make[3]: Leaving directory '/private/tmp/nix-build-gcc-10.3.0.drv-0/build/gcc'
make[2]: *** [Makefile:4848: all-stage3-gcc] Error 2
make[2]: Leaving directory '/private/tmp/nix-build-gcc-10.3.0.drv-0/build'
make[1]: *** [Makefile:21574: stage3-bubble] Error 2
make[1]: Leaving directory '/private/tmp/nix-build-gcc-10.3.0.drv-0/build'
make: *** [Makefile:21638: bootstrap] Error 2
finding garbage collector roots...
deleting garbage...
deleting unused links...
builder for '/nix/store/b1zipkwshrdij0w92sqdr9k3kjpzidkn-gcc-10.3.0.drv' failed with exit code 2
```
</details>

I assume it simply needs a restart, because it builds for me locally

**Comment by jonringer** [comment]
restarted it

**Comment by vcunat** [comment]
> restarted it

Unfortunately Hydra doesn't have a way of restarting everything that was failed by a particular build.  You can just restart one-by-one or everything.  Well, thanks to periodic ZHF, restarting everything shouldn't be that costly.  So I did that now; there was a different transient issue on aarch64-linux, too.

**Comment by vcunat** [comment]
With `environment.noXlibs = true;` the `gtk3` build gets broken with
```
  Run-time dependency cairo-xlib found: NO (tried pkgconfig)
  
  meson.build:521:97: ERROR: Dependency "cairo-xlib" not found, tried pkgconfig
```
That is a (future) channel blocker, via the `simple` test using `imports = [ ../modules/profiles/minimal.nix ];`

**Comment by vcunat** [comment]
For reference, that blocker was now fixed by PR #128473.

**Comment by vcunat** [comment]
[trezor build broke](https://hydra.nixos.org/build/146138747);  /cc @mmahut, @prusnak

**Comment by prusnak** [comment]
> [trezor build broke](https://hydra.nixos.org/build/146138747); /cc @mmahut, @prusnak

Fix in https://github.com/NixOS/nixpkgs/pull/128531

**Comment by Izorkin** [comment]
After this update on my home server, building of the qtwebengine-5.15.3 package begins. How do I know who is using this package?

**Comment by jonringer** [comment]
@Izorkin that build finished 2 days ago https://hydra.nixos.org/eval/1682247?filter=qtwebengine&compare=1682152&full=#tabs-still-succeed . Most likely your derivation deviates from master.

**Comment by Izorkin** [comment]
Found error, fixed in this PR - 74281b9faa2f5cf64f43573b04e7a30fdf559a80

**Pull request merged**
