### PR TITLE
mailman: drop

### LINKED ISSUE #158424: python3.pkgs.mailman is not a Python module
`python3.pkgs.mailman` is not a Python module and `python310.pkgs.mailman` actually uses Python 3.9!???
It can also not be added to `python3Packages` with the correct Python version cause it overrides sqlalchemy.
Thus mailman and the packages depending on it need to be removed from `python-packages.nix`.
cc @mweinelt @jonringer

### PR DESCRIPTION
**Pull request by dotlambda**
https://github.com/NixOS/nixpkgs/issues/158424 still hasn't been resolved, causing me to waste half an hour thinking about why mailman is broken after updating postfix in #170034. This was pointed out to the maintainers a long time ago but they don't care.

###### Description of changes
closes https://github.com/NixOS/nixpkgs/issues/158424

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
* It's not that we don't care, I started working on it and got quite far, but got sick in the meantime and decided to pause everything work-related.
* You reported the original issue, so you seem to be aware of mailman's current issues. Why did you even bother when updating postfix, then?
* It would be greatly appreciated if you could keep your bad mood to yourself in the future, thanks ;-)

Anyways, I have a working draft, that requires some more extensive testing first. I'll try to file a PR in the upcoming week, so no need to drop it now.

**Comment by Ma27** [comment]
Care to elaborate why it should remain open?

**Comment by dotlambda** [comment]
> * It's not that we don't care, I started working on it and got quite far, but got sick in the meantime and decided to pause everything work-related.

You're not the only one. @lheckemann [promised](https://github.com/NixOS/nixpkgs/pull/159892#issuecomment-1038825878) to fix this two months ago but didn't.

> * You reported the original issue, so you seem to be aware of mailman's current issues. Why did you even bother when updating postfix, then?

I forgot about it. Must be my bad memory ;-)

> * It would be greatly appreciated if you could keep your bad mood to yourself in the future, thanks ;-)

It would be greatly appreciated if you helped reduce Python maintainers' workload by actually following their requests.

> Care to elaborate why it should remain open?

Because it is still the only PR solving this problem. I honestly don't see why I shouldn't merge it.

**Comment by ajs124** [comment]
Even assuming the premise of this PR is correct, the implementation isn't:
- it does not add a `throw` alias
- It does not remove the module
- The package still builds
- The maintainers still respond, they just seem to have been busy with other stuff for a while

**Comment by dotlambda** [comment]
> * The package still builds

It doesn't. Try `nix-build -A python310.pkgs.mailman`.

**Comment by lheckemann** [comment]
FWIW, @ma27 took over the work from me. I think it's quite rude to accuse us of not caring just because we aren't able to provide a fix for a complex issue quickly. Sometimes other things happen in our lives.

**Comment by ajs124** [comment]
> > * The package still builds
> 
> It doesn't. Try `nix-build -A python310.pkgs.mailman`.

Try `nix-build -A mailman`. I get that this is an issue, but this isn't a solution for a lot of reasons. This is a waste of time.

**Pull request closed without merging**
