### PR TITLE
Python: buildPyPIPackage and buildPyPIApplication

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@Mic92 prefer this instead?

**Comment by Mic92** [comment]
Yes! Less burden on humans. It also make it easier to migrate, because we just have to grep for the old function.

**Comment by FRidh** [comment]
Indeed. Also, because we could now start using `pname` and `version` that also makes it easier to eventually require that as input to `buildPythonPackage` itself.

**Comment by Mic92** [comment]
In future we can also hopefully make it use of Pipfile: https://github.com/pypa/pipfile

**Comment by FRidh** [comment]
That is very interesting and we should get involved in that. Thanks for the link!

**Comment by FRidh** [comment]
I suppose we should develop an update script that modifies the code in-place instead.

**Pull request closed without merging**
