### PR TITLE
lsof: 4.87 -> 4.88

### PR DESCRIPTION
**Pull request by k0ral**
Cc maintainers: @mornfall 

Successfully built locally.

### CODE REVIEW

**Comment by garbas** [comment]
there is a problem with downloading from url ... i get 

``Got a 530 ftp-server response when 220 was expected``

**Comment by domenkozar** [comment]
Hmm, "it works for me". Maybe we can use a http link for the download url?

**Comment by garbas** [comment]
Quoting Domen Kožar (2015-06-11 14:53:46)
> Hmm, "it works for me". Maybe we can use a http link for the download url?
> 

i tried it manuall (in browser) and prompts for user/pass.
i've changed url to some mirror one (used in linux from scratch manual)


--
Rok Garbas - http://www.garbas.si

**Comment by k0ral** [comment]
The official website advertises some mirrors, including an [HTTP one][1].

[1]: http://www.mirrorservice.org/sites/lsof.itap.purdue.edu/pub/tools/unix/lsof/

**Comment by garbas** [comment]
i've must have missed it, darn.

**Pull request merged**
