### PR TITLE
python3Packages.deform: remove nose dependency

### PR DESCRIPTION
**Pull request by lavafroth**
## Description of changes
Addresses #326513.

- Dependency `nose` was removed from `deform` in version 2.0.15 (2020-12-10).
- Set `pyproject = true` and `build-system` to setuptools.
- Use the `hash` attribute for sha256.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
The URL in the comment beside the `license` is a 404. Going by [their `LICENSE.txt`](https://github.com/Pylons/deform/blob/fdc43d59de7d11b0e3ba1b92835b780cfe181719/LICENSE.txt), we can see that the correct expression is `license = [ lib.licenses.bsd3 lib.licenses.cc-by-30 ]`. Could you correct that (and remove the `with lib` while you’re at it)?

There’s also some optional testing dependencies listed in [`setup.py`](https://github.com/Pylons/deform/blob/fdc43d59de7d11b0e3ba1b92835b780cfe181719/setup.py) that might be worth including, although perhaps a Selenium dependency would be a bit much.

**Comment by lavafroth** [comment]
I've corrected the licenses and removed the `with lib` in the `meta` attribute. About the extra dependencies, the functional tests are run using the [`run-selenium-tests.bash`](https://github.com/Pylons/deform/blob/fdc43d59de7d11b0e3ba1b92835b780cfe181719/run-selenium-tests.bash) file which spins up a server. Let me know if we'd want to include those tests and dependencies as well.

**Comment by emilazy** [comment]
Result of `nixpkgs-review pr 328917` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.deform</li>
    <li>python311Packages.deform.dist</li>
    <li>python312Packages.deform</li>
    <li>python312Packages.deform.dist</li>
  </ul>
</details>

**Review by emilazy — APPROVED** [review]
Looks good to me; probably not worth running those heavy integration tests.

Let’s try out that merge button…

**Pull request merged**
