### PR TITLE
phosh: 0.14.1 -> 0.15.0, phoc: 0.11.0 -> 0.12.0

### PR DESCRIPTION
**Pull request by zhaofengli**
###### Motivation for this change

See upstream changelogs for [Phosh](https://gitlab.gnome.org/World/Phosh/phosh/-/tags/v0.15.0) and [Phoc](https://gitlab.gnome.org/World/Phosh/phoc/-/tags/v0.12.0). Most notably, the lock screen now has a button to summon the on-screen keyboard so that arbitrary passwords can be entered.

Also note the required/recommended patches on other packages ([Phosh](https://gitlab.gnome.org/World/Phosh/phosh/-/tags/v0.15.0#required-patchesversions-off-other-projects), [Phoc](https://gitlab.gnome.org/World/Phosh/phoc/-/tags/v0.12.0)). A [new patch](https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/1074) for g-s-c has been added to the list for the "Add VPN" dialog (not included).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg eval

**Comment by tomfitzhenry** [comment]
I am running this PR on my Pinephone and it LGTM.

**Comment by jtojnar** [comment]
Possibly problematic changes:

* [run: Drop gnome session setup.](https://gitlab.gnome.org/World/Phosh/phosh/-/commit/b466034a5eed79be981e6fd6924d8f9db83bab50) Most of the time people want phosh+phoc so the session just causes trouble. We can drop it and people can needing a session can just fire it up.
* [run: Always start unlocked.](https://gitlab.gnome.org/World/Phosh/phosh/-/commit/be3ce5c529067aa50ec2dbda9c9b78f1cc6abb3b) Running nested is the main use case and one usually wants an unlocked shell there so run unlocked by default. If people want to run locked they can pass '-L'.

**Comment by zhaofengli** [comment]
@jtojnar

> Possibly problematic changes:
> 
>     * [run: Drop gnome session setup.](https://gitlab.gnome.org/World/Phosh/phosh/-/commit/b466034a5eed79be981e6fd6924d8f9db83bab50) Most of the time people want phosh+phoc so the session just causes trouble. We can drop it and people can needing a session can just fire it up.
> 
>     * [run: Always start unlocked.](https://gitlab.gnome.org/World/Phosh/phosh/-/commit/be3ce5c529067aa50ec2dbda9c9b78f1cc6abb3b) Running nested is the main use case and one usually wants an unlocked shell there so run unlocked by default. If people want to run locked they can pass '-L'.

I believe both of those changes only have to do with the development launcher. The launcher script we use is [`data/phosh.in`](https://gitlab.gnome.org/World/Phosh/phosh/-/blob/016036f67aa2a0b6b375495b8ab21369dbd77288/data/phosh.in#L51) which starts both phoc and phosh with a regular gnome-session. For the record, with this update phosh does start locked with other gnome-session components launched correctly.

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
