### PR TITLE
Update gnupg21 package to gpg-2.1.2

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This updates the gnupg21 package to gpg-2.1.2.

Unfortunately when building it, gcc gets rebuild on my machine (why the hell?), so I'd prefer someone telling me either how to build it without building the world or someone else testing it (_nice smile_).

I did this because the actually used version (2.1.1) is a development version which shouldn't be used...

### CODE REVIEW

**Comment by spwhitt** [comment]
To avoid rebuilding, you should work off of the unstable channel rather than master. So:

  1. Run nixos-version
  2. Checkout the hash printed above
  3. git cherry-pick your commit
  4. Test

I also have a branch at my repository which is automatically updated to track the unstable channel if you want to use that: https://github.com/spwhitt/nixpkgs/tree/channel-unstable

**Comment by matthiasbeyer** [comment]
@spwhitt: Thanks a lot, that will help! Really good to know!

**Comment by wkennington** [comment]
How do you figure 2.1.1 is a Dev release? Nowhere does it say that.
http://lists.gnupg.org/pipermail/gnupg-announce/2014q4/000360.html

**Comment by matthiasbeyer** [comment]
running `gpg2 --list-keys <some key>` for example prints a warning that the version is a dev version and shouldn't be used for production keys.

**Comment by matthiasbeyer** [comment]
Anyways, thanks for merging!

**Pull request merged**
