### PR TITLE
nodePackages.graphite-cli: 1.0.9 → 1.1.2

### LINKED ISSUE #281024: Update request: graphite-cli 1.0.9 → 1.1.1
- Package name: Grahpite-cli
- Latest released version: 1.1.1

- Current version on the unstable channel: 1.0.9
- Current version on the stable/release channel: 1.0.9

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

This package has no maintainer because it is a NPM package. #229475 might be related?
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by aikooo7**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Closes #281024

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by aikooo7** [comment]
Reason for force-push: I commited using the version 1.0.14 (latest stable) but issue asked for 1.1.1 (beta)

**Review by aikooo7 — COMMENTED** [review]
As requested, this pr uses the version 1.1.1 (beta) as upsite of 1.0.14 (latest stable), please let me know if this is a issue

**Comment by dotlambda** [comment]
> As requested, this pr uses the version 1.1.1 (beta) as upsite of 1.0.14 (latest stable), please let me know if this is a issue

According to https://www.npmjs.com/package/@withgraphite/graphite-cli?activeTab=versions, at least 1.1.2 is marked stable.

**Comment by aikooo7** [comment]
> > As requested, this pr uses the version 1.1.1 (beta) as upsite of 1.0.14 (latest stable), please let me know if this is a issue
> 
> According to https://www.npmjs.com/package/@withgraphite/graphite-cli?activeTab=versions, at least 1.1.2 is marked stable.

At the time of the pr it was the most recent, it was updated 7 hours ago, I will update this pr when I have time

**Comment by aikooo7** [comment]
@dotlambda Sorry for the ping but any status on this?

**Pull request closed without merging**
