### PR TITLE
Revert "burp: 2.1.32 -> 2.2.4"

### PR DESCRIPTION
**Pull request by ryantm**
Reverts NixOS/nixpkgs#47093

### CODE REVIEW

**Comment by ryantm** [comment]
@GrahamcOfBorg build burp

**Comment by xeji** [comment]
Wasn't this already reverted in #47115 a few hours ago?

**Comment by ryantm** [comment]
Hmm, yep, sorry. Does reverting twice cause any issue?

**Comment by ryantm** [comment]
Oh, I see, my commit is completely empty, so it's probably fine.

**Comment by xeji** [comment]
No, I checked, the merge commit for this  is a noop.

**Pull request merged**
