### PR TITLE
Use ncg for x86 ghc cross compilation

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This is an alternative to #59865 after some feedback from @angerman:

#59865 (comment)

Basically, we shouldn't be using llvm for x86 ghc because it has some bugs, and we can just use the ncg flavor in these cases.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peti** [comment]
What  is the motivation for this change?

**Comment by matthewbauer** [comment]
This is an alternative to https://github.com/NixOS/nixpkgs/pull/59865 after some feedback from @angerman: 

https://github.com/NixOS/nixpkgs/pull/59865#issuecomment-484828943

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
@peti @angerman says GHC + LLVM for x86 has subtle bugs relating to register assignment.

**Comment by angerman** [comment]
Ref: https://gitlab.haskell.org/ghc/ghc/issues/14251

**Comment by Ericson2314** [comment]
Given that this is a ofborg 0 rebuild (this is off the the critical path of things deemed most important), I'm just going to merge.

**Comment by matthewbauer** [comment]
Looks to be working:

https://hydra.nixos.org/build/93598437

!!!

**Comment by nh2** [comment]
Just linking up some issues:

Originally requested on https://github.com/NixOS/nixpkgs/issues/61262

**Pull request merged**
