### PR TITLE
borgmatic: add darwin support

### PR DESCRIPTION
**Pull request by c4710n**
###### Description of changes

This PR add darwin support for borgmatic.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by tjni — COMMENTED** [review]
LGTM minor some minor comments.

Can you also add:
```
__darwinAllowLocalNetworking = true;
```
to the derivation so that the tests pass when the Darwin sandbox is enabled?

**Review by imlonghao — APPROVED** [review]
LGTM, but I don't have a Darwin environment, so I can't test it besides x86_64-linux

As for platforms, borgmatic is written in Python so I believe it should work in all platform

**Comment by c4710n** [comment]
@tjni @imlonghao Thanks for the comments.

I have updated the code based on your comments.

**Review by tjni — APPROVED** [review]

**Review by imlonghao — APPROVED** [review]

**Comment by c4710n** [comment]
The test on x86_64-darwin failed due to [e2fsprogs](https://github.com/NixOS/nixpkgs/pull/243510/checks?check_run_id=15062728449) which is not supported on darwin.

Can anybody give some tips? I will dig the problem, and try to fix it.

**Comment by tjni** [comment]
Can you rebase against master to trigger the ofborg build again? The staging-next branch was just merged and it might fix the issue.

**Pull request merged**
