### PR TITLE
texlive: 2019 (wip)

### LINKED ISSUE #60890: request: texlive 2019! \o/
Hi folks!

Another year, another texlive release! Let's help Nix'ers typeset with all the latest and greatest!

Someone want to get the process started? And is our mirroring situation okay, or are we increasingly imposing on some generous soul?

I'll poke at this if I can, but unlikely to have time in coming weeks. Can definitely help test though! :)

------

Misc info:

https://tug.org/texlive/doc/texlive-en/texlive-en.html#news (link won't work when 2020 is out, probably)

FWIW we have this note: 
https://github.com/NixOS/nixpkgs/blob/b6d0bdf5136031b49d174e638e7d0bdc8c5e5a12/pkgs/tools/typesetting/tex/texlive/bin.nix#L201

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Another year, another update!

This uses snapshot hosted on wdtz.org,
which may not be up to the task long-term.

Not sure how hard folks hit our TL mirrors...

Commit history is messy, showing path taken so far.
(Will clean up if/when reach something ready to merge)

Help testing and suggestions for cleanup appreciated!

For example, dvisvgm was having troubles I ultimately resolved
by setting `LDFLAGS` but likely has a better solution.

Fixes #60890.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Status?

**Comment by dtzWill** [comment]
Seems to work well for my needs? And I'm not confident about the hosting situation, but mostly I have no idea what to expect from NixOS'ers tex usage ^_^.

And apparently this latest conflict which I'll address tomorrow / next push, time for bed for me O:).

**Comment by sondr3** [comment]
Minor ping, this would be great to have in 19.09 😄

**Comment by flokli** [comment]
@dtzWill what's missing from https://www.tug.org/historic/ , that needs to be hosted at wdtz.org? It seems like the 2019 texlive sources are there, too…

**Comment by dtzWill** [comment]
> @dtzWill what's missing from https://www.tug.org/historic/ , that needs to be hosted at wdtz.org? It seems like the 2019 texlive sources are there, too…

The ctan sources-- aka everything in texlive that's not the core binaries :(.  Nothing new on this front, just we need to play another round of "host the tarballs" for 2019 :).

**Comment by dtzWill** [comment]
Closing in favor of #71419! \o/

If there's anything useful here not over there, LMK O:).

**Comment by veprbl** [comment]
> The ctan sources-- aka everything in texlive that's not the core binaries :(

Actually, the "-texmf" tarball contains exactly those packages from CTAN. And, in theory, it should be possible to build our texlive using that 2.6 GB tarball. The problem is that we would have to duplicate their build system. This is not impossible to do, and, in fact, guix did this [1] (mere 7k lines of handwritten Guile code). They overcome the problem of a big tarball by fetching from svn [2], but this probably would not work for us since we are looking to provide 3.5k individual packages unless we are going to break compatibility. Right now, I don't see any shortcuts on this path.

[1] https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/tex.scm?h=bf7b08c4fe7d14c25a83bde99f19eca1119d88ff
[2] https://git.savannah.gnu.org/cgit/guix.git/tree/guix/build-system/texlive.scm?h=bf7b08c4fe7d14c25a83bde99f19eca1119d88ff#n66

**Pull request closed without merging**
