### PR TITLE
openblas: fix cross-compilation

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
I think we need ```"FC=${stdenv.cc.targetPrefix}gfortran"```  to get the cross gfortran.

**Comment by FRidh** [comment]
Thanks. I'll have a look at it. Some other mentions of `FC` https://github.com/xianyi/OpenBLAS/issues/862 http://iprc.soest.hawaii.edu/users/xfu/tool/INSTALL.html

**Comment by FRidh** [comment]
Got a bit further, but encountered now https://github.com/xianyi/OpenBLAS/issues/1958.

**Comment by FRidh** [comment]
```
/nix/store/k2gsj607cl4dcmgi60n17vcsmh17gqar-aarch64-unknown-linux-gnu-binutils-2.30/bin/aarch64-unknown-linux-gnu-ld: ../libopenblasp-r0.3.4.a(saxpy.o): Relocations in generic ELF (EM: 62)
/nix/store/k2gsj607cl4dcmgi60n17vcsmh17gqar-aarch64-unknown-linux-gnu-binutils-2.30/bin/aarch64-unknown-linux-gnu-ld: ../libopenblasp-r0.3.4.a(saxpy.o): Relocations in generic ELF (EM: 62)
../libopenblasp-r0.3.4.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:134: sblat1] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/source/test'
make: *** [Makefile:124: tests] Error 2
```

**Comment by FRidh** [comment]
Working now.

**Comment by FRidh** [comment]
@GrahamcOfBorg build openblas openblasCompat pkgsCross.aarch64-multiplatform.openblas

**Comment by matthewbauer** [comment]
Note: this broke openblas on darwin. Should be fixed by https://github.com/NixOS/nixpkgs/commit/cfc43138cb2d906b9b24563a4487949efb106532.

**Pull request merged**
