### PR TITLE
vimPlugins.lean-nvim: add dependencies

### PR DESCRIPTION
**Pull request by Smaug123**
###### Motivation for this change
Per https://github.com/Julian/lean.nvim/blob/1adf2c8fd323ea1758d1b3a5f78be6dd44592a6b/README.rst, the lean.nvim plugin has these two dependencies. I omitted any optional dependencies and the Lean language server from this addition.

###### Things done

When I added these packages manually to my home-manager setup, Vim fired up successfully and showed me the plugin's infoview pane; I haven't installed the Lean 3 language server so I couldn't get as far as testing whether anything *actually* works, but the language server is strictly speaking optional so I didn't go any further.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Smaug123** [comment]
The PR which introduced lean-nvim is https://github.com/NixOS/nixpkgs/pull/143923 . @RaitoBezarius any views on this?

**Comment by RaitoBezarius** [comment]
@Smaug123 Good point! I listed them explicitly myself because I am not sure, it's the good semantic to put them as hidden dependencies.

**Comment by Smaug123** [comment]
I guess the point is that the plugin won't work at all without those dependencies, whereas it will work without the Lean language server so there's a better argument for leaving that one out.

**Comment by RaitoBezarius** [comment]
Then, it makes sense to me!

Le mer. 3 nov. 2021 à 00:06, Patrick Stevens ***@***.***> a
écrit :

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 144282 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>spacevim</li>    <li>vimPlugins.lean-nvim</li>  </ul></details>

**Pull request merged**
