### PR TITLE
freecad: switch back to isolated config with env vars turned on

### LINKED ISSUE #266246: FreeCAD CLI is broken
After https://github.com/NixOS/nixpkgs/pull/263599, the standard FreeCAD command-line interface as described in https://wiki.freecad.org/Start_up_and_Configuration and also by `FreeCAD --help` is broken. This is what happens when I try to use `--module-path` option:

```
$ FreeCAD --module-path /nix/store/mdvqjz4l2p55j2crq6gz4yz7p7y7h2f4-freecad-render-2023.02.06
unknown option --module-path
usage: /nix/store/5zn1mcv2f7dxzy0carv32v8ddkxnp2yx-freecad-0.21.1/bin/FreeCAD [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
Program received signal SIGSEGV, Segmentation fault.
#0  /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6(+0x3da70) [0x7f5dfc255a70]
#1  /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6(+0x15f15d) [0x7f5dfc37715d]
#2  /nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/libpython3.11.so.1.0(+0x1183a3) [0x7f5dfe5183a3]
#3  /nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/libpython3.11.so.1.0(Py_EncodeLocale+0x5a) [0x7f5dfe535cba]
#4  /nix/store/5zn1mcv2f7dxzy0carv32v8ddkxnp2yx-freecad-0.21.1/bin/FreeCAD() [0x407a1d]
#5  /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6(+0x27fce) [0x7f5dfc23ffce]
#6  /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6(__libc_start_main+0x89) [0x7f5dfc240089]
#7  /nix/store/5zn1mcv2f7dxzy0carv32v8ddkxnp2yx-freecad-0.21.1/bin/FreeCAD() [0x408e05]
```

As a workaround, a working build of freecad 0.21.1 can be fetched from this pinned commit (flake input):
```
    nixpkgs-unstable-freecad.url = "nixpkgs/f99e5f03cc0aa231ab5950a15ed02afec45ed51a";
```

### PR DESCRIPTION
**Pull request by lilyinstarlight**
## Description of changes

Fixes some environmental issues with FreeCAD, such as the Python interpreter erroneously parsing `argv` in #266246

Fixes #266246

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by valff** [comment]
I tested it and it works! Thanks @lilyinstarlight

**Comment by andir** [comment]
Looks good to me. Could we somehow come up with a test case for this so we don't break it again?

**Comment by lilyinstarlight** [comment]
> Could we somehow come up with a test case for this so we don't break it again?

It looks like `FreeCAD -c </dev/null` could be used as a simple test. It does the segfault thing and exits with code 1 on master but exits with code 0 on this PR

So I'll see if I can add it as a `installCheckPhase` here

**Comment by AndersonTorres** [comment]
> So I'll see if I can add it as a installCheckPhase here

Usually I prefer a passsthru smoke-test, like in Spigot package.

**Comment by Janik-Haag** [comment]
> Usually I prefer a passsthru smoke-test, like in Spigot package.

Is there a actual technical reason or is this a personal opinion of yours?
`installCheckPhase` is intended for exactly this kind of thing and splitting it out into a extra derivation like in the spigot seems like it is adding unnecessary overhead

**Comment by Janik-Haag** [comment]
Result of `nixpkgs-review pr 266498` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>freecad</li>
  </ul>
</details>

**Comment by AndersonTorres** [comment]
> Is there a actual technical reason or is this a personal opinion of yours? 

This is not a test suite from FreeCAD maintainers (like, say [Zig does with its test directory](https://github.com/ziglang/zig/tree/master/test)). It is just a smoke test we are doing for our own benefit.

So, it looks reasonable to me to treat it as a `passthru.tests`.
It is a test from Nixpkgs team to Nixpkgs team, so it is reasonable to separate it from the rest of building logic.

Indeed, a very similar test is so typical it was encoded as a `passthru.tests`; namely, `testers.testVersion`.

Also, separating such tests from the main building logic avoids recompilation when the test suite needs to be updated. It is a bit frustrating to recompile the otherwise same code just because `-v` is now `--version`.

These are the _technical reasons_. However I will not impose them.

**Review by Janik-Haag — APPROVED** [review]

**Comment by lilyinstarlight** [comment]
> Usually I prefer a passsthru smoke-test, like in Spigot package.

I was under the impression `installCheckPhase` was preferred for simple does-it-execute tests like this (independent of stuff like `testVersion` which gets annoying when upstream doesn't update the version number in their source), but it seems that guidance was rejected in #119731 (despite reviewers having since urged me to do otherwise to get PRs merged...)

I'll change it to a `runCommand` in `passthru.tests` to match the current guidance in the Nixpkgs manual, thanks @AndersonTorres!

**Comment by lilyinstarlight** [comment]
Done! I've now also made the test check that `PYTHONPATH` works in general, in addition to making sure argument parsing doesn't fail in the same way as before this change

**Review by bjornfor — APPROVED** [review]

**Comment by AndersonTorres** [comment]
Wow, a 3-year-old recommendation!

**Review by AndersonTorres — APPROVED** [review]

**Comment by bjornfor** [comment]
Thanks!

**Pull request merged**
