### PR TITLE
drawpile: fix build

### PR DESCRIPTION
**Pull request by fgaz**
###### Motivation for this change

ZHF: #97479

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fgaz** [comment]
Hm. Apparently my tree was too old

**Comment by worldofpeace** [comment]
@fgaz It would be helpful to link to the failing job

**Comment by worldofpeace** [comment]
Yep, I'm seeing the failure
```
/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: cannot find -lsecret-1
collect2: error: ld returned 1 exit status
make[2]: *** [src/desktop/CMakeFiles/drawpile.dir/build.make:1585: bin/drawpile-2.1.17] Error 1
make[1]: *** [CMakeFiles/Makefile2:513: src/desktop/CMakeFiles/drawpile.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------- nix-build
error: --- Error --- nix-daemon
builder for '/nix/store/lhp8rsv75n0kkhkw0wlsmz1cns1qbqq4-drawpile-2.1.17.drv' failed with exit code 2; last 10 log lines:
  [ 99%] Building CXX object src/desktop/CMakeFiles/drawpile.dir/bundled/QtColorWidgets/color_names.cpp.o
  [ 99%] Building CXX object src/desktop/CMakeFiles/drawpile.dir/qrc_color_widgets.cpp.o
  [ 99%] Building CXX object src/desktop/CMakeFiles/drawpile.dir/qrc_cursors.cpp.o
  [100%] Building CXX object src/desktop/CMakeFiles/drawpile.dir/qrc_builtin.cpp.o
  [100%] Linking CXX executable ../../bin/drawpile
  /nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1/bin/ld: cannot find -lsecret-1
  collect2: error: ld returned 1 exit status
  make[2]: *** [src/desktop/CMakeFiles/drawpile.dir/build.make:1585: bin/drawpile-2.1.17] Error 1
  make[1]: *** [CMakeFiles/Makefile2:513: src/desktop/CMakeFiles/drawpile.dir/all] Error 2
```

tbh this should fail a lot earlier with CMake. Perhaps a bug could be filed?

**Review by worldofpeace — APPROVED** [review]

**Comment by fgaz** [comment]
I'll report it upstream

**Pull request merged**
