### PR TITLE
gitea: 1.17.4 -> 1.18.0

### PR DESCRIPTION
**Pull request by Ma27**
###### Description of changes
ChangeLog: https://github.com/go-gitea/gitea/releases/tag/v1.18.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by techknowlogick — CHANGES_REQUESTED** [review]
Just FYI, we are having issues with CI at the moment (some flakiness). So this tar.gz may need to be rebuild as part of the CI restart.

**Comment by Ma27** [comment]
Marking as draft. Having problems with avatars not found after deploying anyways, still investigating.

**Comment by Izorkin** [comment]
> Marking as draft. Having problems with avatars not found after deploying anyways, still investigating.

I updated without errors. There are no problems with avatars.
Correct hash - `sha256-X0KvIB2JvSoh2MR9FcwKObQzod2GxhKeGqIKU5CKTEM=`

Options `LFS_CONTENT_PATH` deprecated:
```
...s/setting/setting.go:613:deprecatedSetting() [E] Deprecated fallback `[server]` `LFS_CONTENT_PATH` present. Use `[lfs]` `PATH` instead. This fallback will be removed in v1.19.0
```

and:
```
...s/setting/setting.go:731:loadFromConf() [W] unix PROTOCOL value is deprecated, please use http+unix
```

Patch:
```diff
diff --git a/nixos/modules/services/misc/gitea.nix b/nixos/modules/services/misc/gitea.nix
index ac598108a01..c59c7064c4c 100644
--- a/nixos/modules/services/misc/gitea.nix
+++ b/nixos/modules/services/misc/gitea.nix
@@ -395,7 +395,7 @@ in
           ROOT_URL = cfg.rootUrl;
         }
         (mkIf cfg.enableUnixSocket {
-          PROTOCOL = "unix";
+          PROTOCOL = "http+unix";
           HTTP_ADDR = "/run/gitea/gitea.sock";
         })
         (mkIf (!cfg.enableUnixSocket) {
@@ -404,7 +404,6 @@ in
         })
         (mkIf cfg.lfs.enable {
           LFS_START_SERVER = true;
-          LFS_CONTENT_PATH = cfg.lfs.contentDir;
         })

       ];
@@ -426,6 +425,10 @@ in
       oauth2 = {
         JWT_SECRET = "#oauth2jwtsecret#";
       };
+
+      lfs = mkIf (cfg.lfs.enable) {
+        PATH = cfg.lfs.contentDir;
+      };
     };

     services.postgresql = optionalAttrs (usePostgresql && cfg.database.createDatabase) {

```

**Comment by SuperSandro2000** [comment]
fails to build on darwin:

```
/nix/store/za0pnll14dv61b124n6xxnjapd150lcr-go-1.19.4/share/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
Undefined symbols for architecture x86_64:
  "_pam_start_confdir", referenced from:
      __cgo_897673d6bfaf_Cfunc_pam_start_confdir in 000032.o
      _check_pam_start_confdir in 000033.o
     (maybe you meant: _check_pam_start_confdir, __cgo_897673d6bfaf_Cfunc_check_pam_start_confdir , __cgo_897673d6bfaf_Cfunc_pam_start_confdir )
ld: symbol(s) not found for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
error: builder for '/nix/store/zqr2xx5a66km81m8av714sm45gy3ym0g-gitea-1.18.0.drv' failed with exit code 1;
```

I would try to use sdk 11 otherwise just mark it broken.

**Pull request merged**
