### PR TITLE
python310Packages.pywlroots: 0.15.18 -> 0.15.19

### PR DESCRIPTION
**Pull request by arjan-s**
###### Description of changes
https://github.com/flacjacket/pywlroots/releases

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by chvp — APPROVED** [review]
I got a 404 when trying to update this package earlier, but it seems to have resolved itself. Works for me (`qtile` still runs as expected).

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 182852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>python310Packages.pywlroots</li>
    <li>python39Packages.pywlroots</li>
    <li>qtile</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 182852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>python310Packages.pywlroots</li>
    <li>python39Packages.pywlroots</li>
    <li>qtile</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 182852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>python310Packages.pywlroots</li>
    <li>python39Packages.pywlroots</li>
    <li>qtile</li>
  </ul>
</details>

**Comment by superherointj** [comment]
> I got a 404 when trying to update this package earlier, but it seems to have resolved itself. Works for me (`qtile` still runs as expected).

Can you test again?

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 182852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>python310Packages.pywlroots</li>
    <li>python39Packages.pywlroots</li>
    <li>qtile</li>
  </ul>
</details>

**Review by chvp — CHANGES_REQUESTED** [review]
Ah, it doesn't work with `nixpkgs-review` because it needs #182845. My mistake on not testing separately (I just did an apply of https://github.com/NixOS/nixpkgs/pull/182852.patch).

**Comment by arjan-s** [comment]
Sorry, my mistake for not mentioning https://github.com/NixOS/nixpkgs/pull/182845 is required. I've tested this PR with that change already applied.

**Comment by superherointj** [comment]
Merged #182845 . Please, rebase.

**Comment by superherointj** [comment]
@arjan-s Can you squash commits?

**Comment by superherointj** [comment]
@arjan-s Can you squash commits? (I mean, I asked for a rebase, you did a merge. Now there is 2 commits. I suggest you drop the merge, and do a rebase. So there is only a single commit.)

**Comment by arjan-s** [comment]
Yes, apologies! I tried the rebase from my phone last night, but Github website only did a merge. So I planned to fix it this morning. Thanks for picking it up!

**Pull request merged**
