### PR TITLE
fetchFromGitiles: init

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

This has the same motivation as fetchFromGitHub/fetchFromGitLab --
it's cheaper to download a tarball of a single revision than it is to
download a whole history.

I could have gone with domain/group/repo, like fetchFromGitLab, but it
would have made implementation more difficult, and this syntax means
it's a drop-in replacement for fetchgit, so I decided it wasn't worth
it.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by 7c6f434c** [comment]
What can be rev? Literal commit ID or a tag name?

**Comment by jonringer** [comment]
rev can be anything that git understands. so a commitish, tag, or ref. https://git-scm.com/docs/git-rev-parse#_specifying_revisions

**Comment by 7c6f434c** [comment]
Then was «refs/tags/version» replacement to «version» necessary when switching to Gitiles?

**Comment by alyssais** [comment]
I think what you’re talking about is actually a change from `fetchgit` to `fetchFromGitHub` I did as cleanup while introducing `fetchFromGitiles` in the same file. I dropped the `refs/tags/` prefix for consistency with the rest of Nixpkgs, where `refs/tags/` is used rarely.

**Comment by jonringer** [comment]
unless a repo is doing something like using branches and tags with the same names, but different commits, then it wont matter.

**Comment by 7c6f434c** [comment]
I am just an annoying literalist: `fetchFromGitiles` says it accepts arguments similar to `fetchgit`, and the latter says it prefers full `refs/tags/` form so I wonder whether Gitiles fully supports the full form.

**Comment by jonringer** [comment]
not familiar with gitiles, :man_shrugging:

**Comment by alyssais** [comment]
> I am just an annoying literalist: `fetchFromGitiles` says it accepts
> arguments similar to `fetchgit`, and the latter says it prefers full
> `refs/tags/` form so I wonder whether Gitiles fully supports the full
> form.

It does support it, but I still don't want to use it here, because
whatever fetchgit says, refs/tags/ is not the norm in NixOS.  Either
there should be a treewide change to refs/tags/, or the documentation
should be changed, and both of those things are out of scope for this
PR.

The documentation shouldn't say something different to what actual
practice is.

**Comment by 7c6f434c** [comment]
>> I am just an annoying literalist: `fetchFromGitiles` says it accepts
>> arguments similar to `fetchgit`, and the latter says it prefers full
>> `refs/tags/` form so I wonder whether Gitiles fully supports the full
>> form.
>
>It does support it, but I still don't want to use it here, because

Ah that's fine, I agree about scope, I was just checking that the level
of consistency doesn't go down when inheriting the full-reference 
support promise (not all web frontends like slash-separated arguments).

**Comment by alyssais** [comment]
Cool :)

Otherwise happy with the PR?

**Pull request merged**
