### PR TITLE
Update putty derivation

### PR DESCRIPTION
**Pull request by ardumont**
- Use source code tarball instead of svn.
- Add meta information on package.

### CODE REVIEW

**Comment by ardumont** [comment]
screenshot_2015-03-17_14-51-11

**Comment by ardumont** [comment]
Rebased to latest code.
Building is running locally to ensure everything is still ok.

**Comment by ardumont** [comment]
Here we go:

```sh
# tony at lenovo in ~/repo/perso/nixpkgs on git:update-putty-derivation o [16:20:20]
$ nix-build -A putty
these derivations will be built:
/nix/store/71zjyy5lfbd8mnpxcv2z90qn3ykxs46m-putty-0.64.drv
building path (s) ‘/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64’
unpacking sources
unpacking source archive /nix/store/jmnnxrw3yknx6mvka9ycxbxi4pfc3ixp-putty-0.64.tar.gz
source root is putty-0.64
patching sources
...
glibPreFixupPhase
post-installation fixup
patching ELF executables and libraries in /nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64
/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/bin/puttytel
/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/bin/puttygen
/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/bin/putty
/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/bin/pterm
/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/bin/psftp
/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/bin/pscp
/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/bin/plink
gzipping man pages in /nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64
stripping (with flags -S) in /nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/lib  /nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/bin
strip:/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64/lib/gdk-pixbuf-loaders-2.0/putty-0.64/loaders.cache: File format not recognized
patching script interpreter paths in /nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64
/nix/store/1ckx7qv4vgrysqvyib07izk8s1wabvsf-putty-0.64
```
A small screenshot:
screenshot_2015-03-17_16-25-08

**Comment by lethalman** [comment]
Built locally, thanks.

**Comment by vcunat** [comment]
A nitpick: when building from a tarball, autotools typically aren't needed.

**Comment by ardumont** [comment]
> A nitpick: when building from a tarball, autotools typically aren't needed.

`There is no nitpick, there is only the Knowledge` :D
I did not know that otherwise I would have removed it.
Thanks for sharing.

**Comment by vcunat** [comment]
Actually, *if* the code needs to change configure.ac as it does, it will need autotools to regenerate stuff from it :-) I just don't know why the changes were there etc. (and whether you/someone want to spend more time with this expression).

**Pull request merged**
