### PR TITLE
treewide: remove AndersonTorres from maintainers

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by winterqt** [comment]
Is this OK to merge? I see you've force pushed a few times.

**Comment by fpletz** [comment]
@AndersonTorres What's going on here? Also referring to #360012. Are you dropping maintainership for some packages or are you actually leaving? Could you please do it in a single PR?

**Comment by winterqt** [comment]
(There is also a difference between "treewide" and e.g. "various." Treewide implies that you're doing it for every package, so seeing two treewides PRs a day apart is a bit weird. It's fine if you're dropping for only some packages, but some further specificity would be appreciated. Thanks!)

**Comment by AndersonTorres** [comment]
> @AndersonTorres What's going on here? Also referring to https://github.com/NixOS/nixpkgs/pull/360012. Are you dropping maintainership for some packages or are you actually leaving?

I am just dropping maintainership, because

1. I have less free time for now, because I changed shifts in my work and for an indefinite amount of time I am no longer working at home.

2. Because of the above, I am physically and mentally tired. I will take a 30-day vacation from my paid work, and in tandem I will do the same in the open source volunteering.

3. Following the above, in this new year I will take less responsibilities and keep a narrower focus. Because of this I am relinquishing maintenance of some packages right now.

> Could you please do it in a single PR?

This will be the last one.
Indeed [that bug on curl that plagues git](https://github.com/curl/curl/issues/15496) is slowing me down.

> Treewide implies that you're doing it for every package

I have a semantic disagreement here: I think "treewide" is any change that reaches many locations at the source tree, not necessarily all of them.
But I am not interested to bike-shed on terminology. "Various" is a better name, anyway.

> some further specificity would be appreciated

For now I am relinquishing some packages that I am no longer using and others that don't need me caring for them.

**Comment by winterqt** [comment]
Thank you for the clarification, no worries. I'm going to let this sit for 24h in case you think of any more you'd like to drop.

**Pull request merged**
