### PR TITLE
xvfb-run: use a minimal xserver build

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

This should get us in the range of 500 rebuilds for Mesa, which is easily mergeable into master. Hype.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Tested gjs and libadwaita as primary consumers of xvfb in tests.

**Comment by vcunat** [comment]
But now was quite a fitting time to merge such a change to `staging-next`, given the state of rebuilding in there.

**Comment by Luflosi** [comment]
This broke the aaaaxy test in `nixos/tests/aaaaxy.nix`. The game needs GLX.
What is the alternative? How can I make the test work again?

**Comment by K900** [comment]
Use a real X server, just like other graphical applications do for their tests.

**Comment by Luflosi** [comment]
Can you point me to an example please?

**Comment by K900** [comment]
e.g. https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/plasma5.nix

**Pull request merged**
