### PR TITLE
xen: 4.5.1 -> 4.5.2

### PR DESCRIPTION
**Pull request by mixis**
Excerpt from upstream release notes:
This release also contains the security fixes for XSA-137, XSA-138, XSA-141 to XSA-153.
XSA-139 and XSA-140 only apply to QEMU Upstream and are fixed from versions 2.3.1 and 2.4.0 of QEMU.
The qemu portion of XSA-135 has also been applied to qemu-traditional.

### CODE REVIEW

**Comment by mixis** [comment]
Please note: xen 4.5.0 is still vulnerable and used for "xen_xenServer". @ts468 likely knows better what to do about that.

**Comment by mixis** [comment]
It looks like travis failed for unrelated reasons. The build completes locally and works for me as dom0 and domU.

**Comment by ts468** [comment]
@mixis Thank you very much for your efforts, and sorry for the late response. The changes look fine to me, but I can't test them at the moment. If you're telling me that NixOS still evaluates correctly then I would just merge them immediately as they are. But if you're unsure, then please let me know! Again, many thanks for your work!

**Comment by mixis** [comment]
@ts468 based on yesterdays master, nixos still works. In absence of a type checker I'm never sure if such slight changes in scoping don't break unexpected places. The other changes are trivial version updates, which makes me wonder if nix or its ecosystem already support automating updates for projects that sign their releases.

**Comment by ts468** [comment]
@mixis Thanks for the confirmation, and again for your efforts! I was more or less just asking if the default nixos configuration still evaluates after the change, and apparently that seems to be the case. Unfortunately, there is no automated update mechanism for packages in NixOS so far.

**Pull request merged**
