### PR TITLE
i3lock: Make sure that man pages get installed

### PR DESCRIPTION
**Pull request by malyn**

### CODE REVIEW

**Comment by lethalman** [comment]
cc @garbas, looks fine to me. Thanks.

**Comment by garbas** [comment]
shouldn't that folder be `$out/share/man/man1`?

**Comment by garbas** [comment]
ah no ... `$out/man/man1` also works

**Comment by edolstra** [comment]
`$out/man` is automatically moved to `$out/share/man`, but it's cleaner to use `$out/share/man` in the first place.

**Pull request merged**
