### PR TITLE
androidStudioPackages.{stable, beta, canary}: update to latest releases

### PR DESCRIPTION
**Pull request by msfjarvis**
## Description of changes

- [androidStudioPackages.stable: 2023.2.1.24 -> 2023.2.1.25](https://androidstudio.googleblog.com/2024/04/android-studio-iguana-202321-patch-2.html)
- [androidStudioPackages.beta: 2023.2.1.15 -> 2023.2.1.27](https://androidstudio.googleblog.com/2024/04/android-studio-jellyfish-202331-rc-2.html)
- [androidStudioPackages.canary: 2024.1.1.1 -> 2024.1.1.2](https://androidstudio.googleblog.com/2024/04/android-studio-koala-202411-canary-4.html)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
cant run emulator ... let me investigate, it could be just my machine

**Comment by kirillrdy** [comment]
emulator is indeed broken, but I think it's not tied to version of android studio but to version of SDK

maybe @msfjarvis can comment, if emulator works for you

no need to block this PR, while I instigate further

**Comment by msfjarvis** [comment]
> emulator is indeed broken, but I think it's not tied to version of android studio but to version of SDK
> 
> maybe @msfjarvis can comment, if emulator works for you
> 

Just checked, emulator's definitely broken. I don't think this PR specifically broke it, since I also got a report yesterday from another person that it was broken for them too on nixpkgs-unstable. I think this PR can be merged and I'll look into the emulator separately.

**Comment by kirillrdy** [comment]
@msfjarvis let me know if you need a hand

**Pull request merged**
