### PR TITLE
orca-slicer: 2.0.0 -> 2.1.1

### LINKED ISSUE #321679: Update request: orca-slicer 2.0.0 → 2.1.1
- Package name: orca-slicer
- Latest released version: 2.1.1

- Current version on the unstable channel: 2.0.0
- Current version on the stable/release channel: 2.0.0

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
@zhaofengli @ovlach @pinpox 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by oddlama**
## Description of changes

Updates orca-slicer to the newest version and fixes the black-screen bug due to webkit compositing.
Closes https://github.com/NixOS/nixpkgs/issues/321679

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by etrigan63** [comment]
This needs to be backported to 24.05 as it crashes after launch.

**Comment by oddlama** [comment]
> This needs to be backported to 24.05 as it crashes after launch.

It also crashes on the 24.11 version built by hydra. While it was working fine before, some dependencies were upgraded and are seemingly related to the issue. Not sure how to debug this, since it starts correctly when invoked with gdb.

If I had to guess, I would assume that a backported dependency causes the crash for you and this backport will probably not fix it.

**Comment by pinpox** [comment]
It started crashing for me too, on nixos-unstable. Was working fine before, I can even start it but about 10 seconds into using it it crashes with only `Segmentation Fault` printed to the terminal. @oddlama how did you try to debug with gdb?

**Comment by oddlama** [comment]
When I try to start it with gdb, it prints `Failed to get GBM device` a hundred times and exits without crashing. When I try to start it normally it crashes. And for some reason the coredump doesn't have a lot of information about the true cause:

```
#0  0x0000000000000000 in ??? ()
#1  0x00007fe93d7b461c in ??? () at /nix/store/gyl7pz5wh7bqh3v8icva2b0790gbxj54-nvidia-x11-555.58.02-6.8.12/lib/libnvidia-tls.so.555.58.02
#2  0x00007ffdd8303730 in ??? ()
#3  0x0000000000000000 in ??? ()
```

Maybe the stack was corrupted.

**Comment by k3d3** [comment]
> It started crashing for me too, on nixos-unstable. Was working fine before, I can even start it but about 10 seconds into using it it crashes with only `Segmentation Fault` printed to the terminal. @oddlama how did you try to debug with gdb?
> 
> EDIT:
> 
> So I guess something to do with webkitgtk2?

Yep, webkit2 is broken, and the cause is the device tab. My workaround is to set the Device UI value in the printer settings to 127.0.0.1:

image

If you can't access that dialog because it crashes too quickly, it can be set in the `~/.config/OrcaSlicer/user/default/machine/(printer name)` directly:

image

Obviously this isn't a solution to the problem, but hopefully it's a helpful workaround.

**Comment by oddlama** [comment]
@k3d3 You must be running into a different issue, since this crash also happens when you start from scratch (no config directory).

**Comment by oddlama** [comment]
When I diff the two derivations I have (one from when this was merged which works and one from today which crashes), we can see the following changes:

```
<<< /nix/store/1v6wdnvcsvizl66afqd96bzfjfhgh8qp-orca-slicer-2.1.1/bin/orca-slicer
>>> /nix/store/g1mwq39waf0y7fhbgfln5gzhqm2mb1ab-orca-slicer-2.1.1/bin/orca-slicer
Version changes:
[D.]  #01  SDL2              2.30.4 -> 2.30.3
[D.]  #02  audit             4.0 -> 3.1.2
[D.]  #03  bubblewrap        0.9.0 -> 0.8.0
[D.]  #04  cryptsetup        2.7.3 -> 2.7.1
[D.]  #05  flite             2.2-lib -> 2.2
[D.]  #06  fribidi           1.0.14 -> 1.0.13
[D*]  #07  glib              2.80.3 -> 2.80.2
[D.]  #08  hwdata            0.383 -> 0.382
[D.]  #09  icu4c             74.2 -> 73.2
[D.]  #10  libapparmor       4.0.1 -> 3.1.7
[D.]  #11  libass            0.17.2 -> 0.17.1
[D.]  #12  libbpf            1.4.3 -> 1.4.2
[D.]  #13  libcamera         0.3.0 -> 0.2.0
[D.]  #14  libdrm            2.4.121 -> 2.4.120
[D.]  #15  libopenmpt        0.7.8 -> 0.7.7
[D.]  #16  libvpx            1.14.1 -> 1.14.0
[D.]  #17  libxslt           1.1.41 -> 1.1.39
[D.]  #18  lz4               1.9.4-lib -> 1.9.4
[D*]  #19  mesa              24.1.2, 24.1.2-osmesa -> 24.1.1, 24.1.1-osmesa
[D.]  #20  nettle            3.10 -> 3.9.1
[D.]  #21  nuspell           5.1.6-lib -> 5.1.4-lib
[D*]  #22  openssl           3.0.14 -> 3.0.13
[D.]  #23  pcre2             10.44 -> 10.43
[D.]  #24  pipewire          1.2.0 -> 1.0.7
[D.]  #25  python3           3.12.4 -> 3.11.9
[D.]  #26  xkeyboard-config  2.42 -> 2.41
[D.]  #27  xz                5.6.2, 5.6.2-bin -> 5.4.6, 5.4.6-bin
Added packages:
[A.]  #1  libGL  1.7.0, 1.7.0-dev
Closure size: 352 -> 354 (354 paths added, 352 paths removed, delta +2, disk usage -6.0MiB).
```

One of those dependencies must be the cause or strongly related.

**Pull request merged**
