### PR TITLE
go_1_22: 1.22.1 -> 1.22.2

### PR DESCRIPTION
**Pull request by zowoq**
Changelog: https://go.dev/doc/devel/release#go1.22

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mfrw — APPROVED** [review]
Built locally on Linux x86_64:

```bash
./result/bin/go version
go version go1.22.2 linux/amd64
```

**Comment by jrick** [comment]
was it intentional that this was merged directly to staging instead of master?

**Comment by zowoq** [comment]
> was it intentional that this was merged directly to staging instead of master?

Yes.

**Comment by jimmidyson** [comment]
I'm a nix newbie and wondering about the process this goes through until it reaches `nixpkgs-unstable`? Is that documented somewhere?

When can I expect to be able to use this version?

**Comment by jrick** [comment]
> I'm a nix newbie and wondering about the process this goes through until it reaches `nixpkgs-unstable`? Is that documented somewhere?
> 
> When can I expect to be able to use this version?

This confused me for a while searching online to figure out how the branching worked, but I think this is the best explanation: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging.  I saw merges from master -> staging and figured everything is meant to hit master first.  I didn't realize staging also would be eventually merged back into master.

**Comment by zowoq** [comment]
> When can I expect to be able to use this version?

A new staging-next should start in a day or so. https://nixpk.gs/pr-tracker.html?pr=301373 is probably the easiest was to track progress.

**Pull request merged**
