### PR TITLE
[18.03] firefox updates (59.0 -> 59.0.1, firefox-esr: 52.7.1esr -> 52.7.2esr)

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

Backport of #37208 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by andir** [comment]
Updated the commit messages to reflect the actual changes.

**Comment by vcunat** [comment]
59 won't build this way:
```
configure: error: you don't have NSS installed or your version is too old
```

**Comment by andir** [comment]
I was still waiting for my build machine to finish the tasks.. I'll get
that upgraded as well.

On 18 Mar 2018 16:22, "Vladimír Čunát" <notifications@github.com> wrote:

59 won't build this way:

configure: error: you don't have NSS installed or your version is too old

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NixOS/nixpkgs/pull/37309#issuecomment-374007709>, or mute
the thread

**Comment by vcunat** [comment]
BTW, do you have WIP on backporting these to 17.09 as well?

**Comment by andir** [comment]
Yes, there is a PR for that: https://github.com/NixOS/nixpkgs/pull/37313

**Comment by vcunat** [comment]
This will probably be good after picking 5a019829eb40, but I haven't finished the build yet.

**Comment by andir** [comment]
I picked that on this branch. Running a build again. Finally back at a proper computer so feedback should be quicker now...

**Comment by vcunat** [comment]
It didn't compile for me (two attempts).  It fails to compile `gkrust`, but I can't see any helpful information immediately.

**Comment by andir** [comment]
59.0.1 did compile fine for me. The issue seems to be with some paxctl call:

```
WARNING: Found 21 duplicated files taking 243077 bytes (uncompressed)
# Package mozharness
/build/mozilla-release-3db9e3d52b17563efca181ccbb50deb8660c59ae/obj-x86_64-pc-linux-gnu/_virtualenv/bin/python -m mozbuild.action.test_archive  mozharness /build/mozilla-release-3db9e3d52b17563efca181ccbb50deb8660c59ae/obj-x86_64-pc
-linux-gnu/dist/mozharness.zip
Wrote 546 files in 2469259 bytes to mozharness.zip in 0.21s
Packing stylo binding files...
cd '../../dist/rust_bindings/style' && \
        zip -r5D '/build/mozilla-release-3db9e3d52b17563efca181ccbb50deb8660c59ae/obj-x86_64-pc-linux-gnu/dist/firefox-59.0.1.en-US.linux-x86_64.stylo-bindings.zip' .
  adding: atom_macro.rs (deflated 93%)
  adding: pseudo_element_definition.rs (deflated 91%)
  adding: bindings.rs (deflated 88%)
  adding: structs.rs (deflated 89%)
../../config/nsinstall -D /nix/store/azqq6pdx03k65qn6fjzyza6cb5iv3ygi-firefox-unwrapped-59.0.1/lib/firefox
(cd ../../dist/firefox && /nix/store/2p00w952ljb1172nsf3jm7nsjgsw5qpw-gnutar-1.30/bin/tar --exclude=precomplete --exclude=.mkdir.done -chf - .) | \
  (cd /nix/store/azqq6pdx03k65qn6fjzyza6cb5iv3ygi-firefox-unwrapped-59.0.1/lib/firefox && tar -xf -)
../../config/nsinstall -D /nix/store/azqq6pdx03k65qn6fjzyza6cb5iv3ygi-firefox-unwrapped-59.0.1/bin
rm -f -f /nix/store/azqq6pdx03k65qn6fjzyza6cb5iv3ygi-firefox-unwrapped-59.0.1/bin/firefox
ln -s /nix/store/azqq6pdx03k65qn6fjzyza6cb5iv3ygi-firefox-unwrapped-59.0.1/lib/firefox/firefox /nix/store/azqq6pdx03k65qn6fjzyza6cb5iv3ygi-firefox-unwrapped-59.0.1/bin
make[1]: Leaving directory '/build/mozilla-release-3db9e3d52b17563efca181ccbb50deb8660c59ae/obj-x86_64-pc-linux-gnu/browser/installer'
PaX control v0.9
Copyright 2004,2005,2006,2007,2009,2010,2011,2012,2014 PaX Team <pageexec@freemail.hu>

usage: paxctl <options> <files>

options:
        -p: disable PAGEEXEC            -P: enable PAGEEXEC
        -e: disable EMUTRAMP            -E: enable EMUTRAMP
        -m: disable MPROTECT            -M: enable MPROTECT
        -r: disable RANDMMAP            -R: enable RANDMMAP
        -x: disable RANDEXEC            -X: enable RANDEXEC
        -s: disable SEGMEXEC            -S: enable SEGMEXEC

        -v: view flags                  -z: restore default flags
        -q: suppress error messages     -Q: report flags in short format
        -c: convert PT_GNU_STACK into PT_PAX_FLAGS (see manpage!)
        -C: create PT_PAX_FLAGS (see manpage!)
builder for '/nix/store/qb5q6sh95r4v04nimirhcajsh9vxh8hv-firefox-unwrapped-59.0.1.drv' failed with exit code 1
cannot build derivation '/nix/store/57f69iidv3s7xlgc2b4a5q3cbxvkw8gg-firefox-59.0.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/57f69iidv3s7xlgc2b4a5q3cbxvkw8gg-firefox-59.0.1.drv' failed
```

I'll try to investigate further.

**Comment by andir** [comment]
I added the required pax changes to the firefox `58.0.2 -> 59.0.1` commit. I am compiling it right now. fingers crossed.

**Comment by andir** [comment]
For the record: On ARM we also need to add this patch https://hg.mozilla.org/releases/mozilla-esr52/rev/5cd5586a2f48 to fix the libvorbis/tremor issue.

I'll include that in this PR.

**Comment by andir** [comment]
Builds fine for me. @vcunat any objections against merging?

**Comment by vcunat** [comment]
None.  I was unable to build some dependency that still suffers from a `/bin/sh` impurity problem.

**Comment by andir** [comment]
Rebuild succeeded for me.

**Pull request merged**
