### PR TITLE
LightDM: Set default user session when possible.

### PR DESCRIPTION
**Pull request by ElvishJerricco**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
@wkennington You might be a good reviewer for this PR? This file doesn't seem to have a code owner, but I think you have the most contributions to it.

**Comment by obadz** [comment]
Could you explain what behavior you expected prior to this patch and how it changed afterward?

I made some changes a while back so that lighdm remembers each users's sessions (cf94cdb59bf). Doesn't that fill the need of what you're trying to do?

**Comment by ElvishJerricco** [comment]
@obadz This is purely useful for the session it defaults to on first ever login. I was very surprised to find myself in the wrong session despite having `default`s set, and it took me a bit to realize what I needed to do. Now, whenever you configure a new system, it will default to the right session out of the gate.

**Comment by obadz** [comment]
Ok, cool. Thanks.

**Pull request merged**
