### PR TITLE
freshBootstrapTools: rename from stdenvBootstrapTools

### PR DESCRIPTION
**Pull request by trofi**
`stdenvBootstrapTools` was defined in both `nixpkgs` and `releases`
jobsets. This makes hydra view a bit confusing:

    $ git grep -F 'stdenvBootstrapTools =' | cat
    pkgs/top-level/all-packages.nix:  stdenvBootstrapTools = if stdenv.hostPlatform.isDarwin then
    pkgs/top-level/release.nix:      stdenvBootstrapTools = with lib;

The change renames jobset to be distinct. At least it improves grep
experience.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
> The change renames jobset to be distinct.

If name collisions cause `hydra.nixos.org` to silently delete jobs we really ought to have CI prevent (or at least warn on) merges that would create collisions.  Otherwise this will happen again...

**Comment by trofi** [comment]
Looking at https://hydra.nixos.org/jobset/nixpkgs/trunk#tabs-configuration `trunk` configuration I suspect it's a nix expression level collision where both `release.nix` and `all-packages.nix` define the same attribute name and it somehow gets merged incorrectly.

**Comment by trofi** [comment]
@ofborg eval

**Comment by trofi** [comment]
After the change we can see both present in top level:

```
$ nix repl -f pkgs/top-level/release.nix
Welcome to Nix 2.10.3. Type :? for help.

Loading installable ''...
Added 16795 variables.
nix-repl> stdenvBootstrapTools
{ aarch64-linux = { ... }; i686-linux = { ... }; x86_64-darwin = { ... }; x86_64-linux = { ... }; }

nix-repl> freshBootstrapTools
{ }
```

Not sure why `freshBootstrapTools` is empty. Possible another bug.

**Comment by trofi** [comment]
Looks like plain rename does not work anymore and fails eval. I wonder if 5643714dea562f0161529ab23058562afeff46d0 somehow relies on new meaning of stdenvBootstrapTools. I don't see how exacly how they are related. Maybe @alyssais knows?

I suspect things were broken for a while. Before this change:

```
# command from pkgs/os-specific/linux/busybox/default.nix:# nix build -f pkgs/top-level/release.nix stdenvBootstrapTools.x86_64-linux.dist
$ nix build -f pkgs/top-level/release.nix stdenvBootstrapTools.x86_64-linux.dist
error: attribute 'x86_64-linux' in selection path 'stdenvBootstrapTools.x86_64-linux.dist' not found
```

After the change:

```
$ nix build -f pkgs/top-level/release.nix stdenvBootstrapTools.x86_64-linux.dist
error: anonymous function at /home/slyfox/dev/git/nixpkgs-master/pkgs/stdenv/linux/make-bootstrap-tools.nix:1:1 called with unexpected argument 'localSystem'

       at /home/slyfox/dev/git/nixpkgs-master/pkgs/top-level/release.nix:169:16:

          168|             inherit
          169|               (import ../stdenv/linux/make-bootstrap-tools.nix {
             |                ^
          170|                 localSystem = { inherit system; };
```

**Comment by trofi** [comment]
I suspect we need to adapt below to avoid removed `localSystem` parameter:
```nix
      stdenvBootstrapTools = with lib;
        genAttrs systemsWithAnySupport
          (system: {
            inherit
              (import ../stdenv/linux/make-bootstrap-tools.nix {
                localSystem = { inherit system; };
              })
              dist test;
          })
```

**Comment by trofi** [comment]
> Looks like plain rename does not work anymore and fails eval. I wonder if [5643714](https://github.com/NixOS/nixpkgs/commit/5643714dea562f0161529ab23058562afeff46d0) somehow relies on new meaning of stdenvBootstrapTools. I don't see how exacly how they are related. Maybe @alyssais knows?

Added a rollback CL to this PR (don't know how to fix it forward). Rollback restores `nix build -f pkgs/top-level/release.nix stdenvBootstrapTools.x86_64-linux.dist` evaluation for me. WDYT?

**Comment by amjoseph-nixpkgs** [comment]
I have a stupid question: are the configuration files for the Hydra instance running on `hydra.nixos.org` posted somewhere (minus signing keys, of course) where I can view them?

I think I've run into this problem before.

Hydra itself is open-source and you can get a copy off of github, but the details of how it is configured for the particular instance used to build nixpkgs/nixos weren't something I was able to find.  That seemed like a natural "start here" point for debugging things like this.

**Comment by trofi** [comment]
[caveat: I never created hydra jobsets] I think the job definition is clicked on hydra UI directly: you pick a repository, branch, expression and possibly a set of platforms to run on. https://hydra.nixos.org/jobset/nixpkgs/trunk#tabs-configuration

**Comment by amjoseph-nixpkgs** [comment]
> you pick a repository, branch, expression and possibly a set of platforms to run on

Yes, but where is the list of repository/branch/expressions that are run automatically?  In other words, from your link:

```
Nix expression: 	pkgs/top-level/release.nix in input nixpkgs
```

Where did `pkgs/top-level/release.nix` come from?

Similarly, on [this page](https://hydra.nixos.org/jobset/nixpkgs/cross-trunk#tabs-configuration), where did `pkgs/top-level/release-cross.nix` come from?

There must be a list of "entry points into nixpkgs" somewhere in the Hydra configuration.  I've never been able to find that.

**Comment by amjoseph-nixpkgs** [comment]
@trofi, I think you edited my comment instead of replying to it...

**Comment by trofi** [comment]
> @trofi, I think you edited my comment instead of replying to it...

Gah! My apologies! I hope I did not butcher it while restoring it. No idea why I cleackied `edit` instead of Reply. Trying again as a reply:

> Yes, but where is the list of repository/branch/expressions that are run automatically? In other words, from your link: Where did pkgs/top-level/release.nix come from?
> > Nix expression: 	pkgs/top-level/release.nix in input nixpkgs

I think people typed it in using web UI. I would guess administrator privileges give you that. json API exposes it as well: https://github.com/NixOS/hydra/blob/master/hydra-api.yaml#L148

**Comment by trofi** [comment]
> I suspect that if the root cause of the problem in this PR is some kind of name-collision, it would be in whatever merges these entry points together.

I think all of merging happens right within `pkgs/top-level/release.nix` expression. It's a `let jobs = { stdenvBootstrapTools =  ... } // (mapTestOn ((packagePlatforms pkgs) // { ... } in jobs` expression.

I guess `(mapTestOn ((packagePlatforms pkgs)` is what overrides initially locally defined `stdenvBootstrapTools`.

**Comment by amjoseph-nixpkgs** [comment]
Personally I don't care what the package is called.  I didn't pick the name.

I also think the bug here isn't the package name, it's the fact that name collisions cause jobs to be dropped silently.  Simply renaming the package is a band-aid; this will happen again somewhere else.  The way [it got this name](https://github.com/NixOS/nixpkgs/pull/168650#issuecomment-1107361774) in the first place is out of a desire to have the same name for jobs in both `release` and `release-cross`.

**Comment by trofi** [comment]
> Personally I don't care what the package is called.
> 
> But I think the bug here isn't the package name, it's the fact that name collisions cause jobs to be dropped silently. Simply renaming the package is a band-aid; this will happen again somewhere else. The way [it got this name](https://github.com/NixOS/nixpkgs/pull/168650#issuecomment-1107361774) in the first place is out of a desire to have the same name for jobs in both `release` and `release-cross`.

Is your suggestion to not rename the package and make it work? Or have an eval to fail loudly? (that would still require a rename).

Failing loudly should be easier by slightly changing the way attrs are merged. Say, some equivalent of

```
nix-repl> let as = { a = 1; }; in as // { a = 2; }
{ a = 2; }

nix-repl> let as = { a = 1; }; bs = { a = 2; }; in { inherit (as) a; inherit (bs) a; }
error: attribute 'a' already defined at (string):1:56

       at «string»:1:72:

            1| let as = { a = 1; }; bs = { a = 2; }; in { inherit (as) a; inherit (bs) a; }
             |      
```

**Comment by amjoseph-nixpkgs** [comment]
> Is your suggestion to not rename the package and make it work? Or have an eval to fail loudly? (that would still require a rename).

Having it fail loudly and then changing the name to unfail it sounds great.

I'm still astonished that Hydra doesn't send notifications of any kind [and people seem to be okay with that](https://github.com/NixOS/nixpkgs/pull/168650#issuecomment-1188269844).  That is pretty demotivating.

**Comment by trofi** [comment]
> > Is your suggestion to not rename the package and make it work? Or have an eval to fail loudly? (that would still require a rename).
> 
> Having it fail loudly and then changing the name to unfail it sounds great.

Added a `pkgs/top-level/release.nix: disallow symbol clash between 'pkgs' and local jobs` change. When applied on `master` it fails as:

```
$ nix repl ./release.nix
error: jobs: Unexpected attribute collision between 'jobs' and 'pkgs': stdenvBootstrapTools
```

> I'm still astonished that Hydra doesn't send notifications of any kind [and people seem to be okay with that](https://github.com/NixOS/nixpkgs/pull/168650#issuecomment-1188269844). That is pretty demotivating.

That's probably worth discussing with infrastrusture team. Maybe in https://github.com/NixOS/nixos-org-configurations/issues/51? I personally would prefer an RSS feed for package state changes I care about. I don't trust email delivery.

**Comment by trofi** [comment]
`pkgs/top-level/release.nix: disallow symbol clash between 'pkgs' and local jobs` is easier to review in "ignore whitespace" mode:

```diff
--- a/pkgs/top-level/release.nix
+++ b/pkgs/top-level/release.nix
@@ -31,6 +31,7 @@ let
   ] (arch: builtins.elem "${arch}-darwin" systemsWithAnySupport);

   jobs =
+    let nonPackageJobs =
       { tarball = import ./make-tarball.nix { inherit pkgs nixpkgs officialRelease supportedSystems; };

         metrics = import ./metrics.nix { inherit pkgs nixpkgs; };
@@ -193,7 +194,19 @@ let
               };
             };

-    } // (mapTestOn ((packagePlatforms pkgs) // {
+       };
+    # Do not allow attribute collision between jobs inserted in
+    # 'nonPackageAttrs' and jobs pulled in from 'pkgs'.
+    # Conflicts usually cause silent job drops like in
+    #   https://github.com/NixOS/nixpkgs/pull/182058
+    nonPackageAttrs = lib.attrNames nonPackageJobs;
+    packageAttrs = lib.attrNames pkgs;
+    attributeCollisions = lib.intersectLists nonPackageAttrs packageAttrs;
+    in assert lib.assertMsg
+              (attributeCollisions == [])
+              "jobs: Unexpected attribute collision between 'jobs' and 'pkgs': ${lib.concatStringsSep " " attributeCollisions}";
+
+    nonPackageJobs // (mapTestOn ((packagePlatforms pkgs) // {
       haskell.compiler = packagePlatforms pkgs.haskell.compiler;
       haskellPackages = packagePlatforms pkgs.haskellPackages;
       idrisPackages = packagePlatforms pkgs.idrisPackages;
```

**Review by ghost — COMMENTED** [review]
We really shouldn't revert commit 5643714dea562f0161529ab23058562afeff46d0 by @alyssais -- it was made for a good reason.

Please drop the revert (9c8e3847993b61000085f64259423dad1ca9549e) and cherry-pick e76b10c3acd2f7347b9131c175d54045063e026e instead.

Otherwise LGTM.

**Comment by amjoseph-nixpkgs** [comment]
> I personally would prefer an RSS feed for package state changes I care about.

That would be fine too.

> I don't trust email delivery.

Might be something to discuss with your email provider.

**Comment by trofi** [comment]
I think this PR gets only more bloated code-wise. I'm declaring the defeat. I hope the failure mode is clear enough for others to fix it properly.

**Comment by amjoseph-nixpkgs** [comment]
> only more bloated code-wise

Whenever I re-indent code I haven't touched, git always makes me regret it...

**Pull request closed without merging**
