### PR TITLE
opera: 68.0.3618.63 -> 71.0.3770.271

### PR DESCRIPTION
**Pull request by srid**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by srid** [comment]
@r-ryantm

**Comment by srid** [comment]
Before this gets merged, I should note that right-click is broken on the new version. Right clicking anywhere on the web pages simply doesn't do anything. 

I run GNOME Wayland, for what it's worth. 

For this reason, I went back to version 68.

**Comment by ryantm** [comment]
@srid FYI @r-ryantm is an updater bot, so it can't really review PRs.

**Comment by srid** [comment]
The beta version (72) doesn't have this issue. Perhaps we should add a `opera-beta` package.

**Comment by SuperSandro2000** [comment]
@srid Is this still the latest version of opera?

**Comment by srid** [comment]
opera-stable_72.0.3815.400_amd64.deb is the latest.

**Pull request closed without merging**
