### PR TITLE
python3Packages.mcstatus: 6.1.0 -> 6.1.2

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 6.1.2

https://github.com/Dinnerbone/mcstatus/releases/tag/v6.1.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 128187` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.mcstatus</li>
    <li>python39Packages.mcstatus</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@fabaff merge conflict.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 128187` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.mcstatus</li>
    <li>python39Packages.mcstatus</li>
  </ul>
</details>

**Comment by siraben** [comment]
Build failure on linux

<details>

```
Successfully installed homeassistant-2021.6.6
/tmp/nix-build-homeassistant-2021.6.6.drv-0/source
Finished executing pipInstallPhase
@nix { "action": "setPhase", "phase": "fixupPhase" }
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/qbbllv468xipcrg67i85csln4p2fd8pb-homeassistant-2021.6.6
patching script interpreter paths in /nix/store/qbbllv468xipcrg67i85csln4p2fd8pb-homeassistant-2021.6.6
checking for references to /tmp/nix-build-homeassistant-2021.6.6.drv-0/ in /nix/store/qbbllv468xipcrg67i85csln4p2fd8pb-homeassistant-2021.6.6...
Rewriting #!/nix/store/2nhfiak8a30vw67mxksc2kdb69np2jcw-python3-3.8.9/bin/python3.8 to #!/nix/store/2nhfiak8a30vw67mxksc2kdb69np2jcw-python3-3.8.9
wrapping `/nix/store/qbbllv468xipcrg67i85csln4p2fd8pb-homeassistant-2021.6.6/bin/hass'...
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
@nix { "action": "setPhase", "phase": "installCheckPhase" }
running install tests
no Makefile or custom installCheckPhase, doing nothing
@nix { "action": "setPhase", "phase": "pythonCatchConflictsPhase" }
pythonCatchConflictsPhase
@nix { "action": "setPhase", "phase": "pythonRemoveBinBytecodePhase" }
pythonRemoveBinBytecodePhase
@nix { "action": "setPhase", "phase": "pythonImportsCheckPhase" }
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
@nix { "action": "setPhase", "phase": "pytestCheckPhase" }
pytestCheckPhase
Executing pytestCheckPhase
mkdir: cannot create directory ‘/build/media’: No such file or directory
```

</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 128187` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>home-assistant</li>
<li>python38Packages.mcstatus</li>
<li>python39Packages.mcstatus</li>
</ul>
</details>

**Pull request merged**
