### PR TITLE
ccemux: 1.1.1 -> unstable-2023-07-08

### PR DESCRIPTION
**Pull request by viluon**
I am new to this. The change is trivial, but I'm not familiar with the testing & approval process. The assigned version string may be against best practices. Apologies for any extra work incurred.

###### Description of changes

Updating to CC:Tweaked 1.106.1. There haven't been new releases of CCEmuX in over 4 years, but the underlying version of CC:Tweaked keeps changing. [Full changelog](https://github.com/CCEmuX/CCEmuX/compare/v1.1.1...989cfe52a0458b991e0a7d87edec81d3fef472ac).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GiggleSquid** [comment]
Result of `nixpkgs-review pr 243451` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ccemux</li>
  </ul>
</details>

**Review by GiggleSquid — CHANGES_REQUESTED** [review]
Overall, good job. Just a few nitpicky details.
Make sure you squash commits into a single ccemux: 1.1.1 -> unstable-2023-07-08

**Comment by viluon** [comment]
Thank you @GiggleSquid for the beginner-friendly review. I've integrated your suggestions and switched to `hash = "sha256-..."` for the desktop icon while I was at it.

**Comment by GiggleSquid** [comment]
I forgot to mention, you're also welcome to add yourself as a maintainer if you wish. The current maintainer may be inactive. You'll get notifications about PRs for the pkgs you maintain and will be considered an authority on the pkg itself.
If you do, you'll also need to add yourself to the maintainers/maintainer-list.nix and add a separate commit in the PR See: [maintainers](https://nixos.org/manual/nixpkgs/stable/#var-meta-maintainers)

Totally up to you though!

Changes look good, I'll approve after you become a maintainer or say you don't want to. Otherwise I'll just have to approve twice

**Comment by viluon** [comment]
Alright, is it okay if the maintainers commit also includes the change in the package's list of maintainers?

**Comment by GiggleSquid** [comment]
The maintainers commit should only include changes to the maintainer-list.
Sorry, should have mentioned that!

The meta maintainers in the pkg should be in the version change commit

**Comment by viluon** [comment]
No worries, rebased.

**Review by GiggleSquid — APPROVED** [review]
Looks good to me!

**Comment by viluon** [comment]
@GiggleSquid are there any blockers to merging this?

**Comment by GiggleSquid** [comment]
> are there any blockers to merging this?

Not afaik.

It takes someone with merge powers, and the ratio of mergers to PRs is extremely low. It can take anywhere from instantly to never to be merged.
Often having more reviews  *can* help.

There is a pr-review-request channel on the "Nix/NixOS (Unofficial)" discord. You're welcome to post in there to see if you can drum up more attention

**Review by drupol — APPROVED** [review]
:100: ! Nice, nothing to say here, congrats!

**Pull request merged**
