### PR TITLE
treewide: ensure pre/post phase hooks are strings

### PR DESCRIPTION
**Pull request by smancill**
###### Motivation for this change

Some derivations use `lib.optional` or `lib.optionals` when setting pre/post phase hooks. Ensure the proper `lib.optionalString` is used.

###### Things done

I fixed a similar issue a couple of weeks ago when working on `libcanberra`, and I though that a treewide fix would be useful.

I don't have the computer power to rebuild all modified derivations, but visual inspection of the patch looks fine.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Review by jonringer — APPROVED** [review]
diff LGTM

**Comment by r-burns** [comment]
I think there is an eval failure in staging which would be fixed by https://github.com/NixOS/nixpkgs/pull/134594

**Comment by vcunat** [comment]
@OfBorg eval

**Comment by SuperSandro2000** [comment]
This can target master, right?

**Comment by smancill** [comment]
> This can target master, right?

I can rebase master if you want. I though that it should target staging due to the big number of modified derivations.

**Comment by SuperSandro2000** [comment]
> I can rebase master if you want. I though that it should target staging due to the big number of modified derivations.

We still only rebuild under 10 packages which means we can target master.

**Comment by smancill** [comment]
> > I can rebase master if you want. I though that it should target staging due to the big number of modified derivations.
> 
> We still only rebuild under 10 packages which means we can target master.

I rebased on top of master and pushed, but I cannot change the base branch in this PR now to master.

**Comment by roberth** [comment]
(I did not intend to remove the zowoq review request, but the github ui enforces a 15 reviewer limit iirc)

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 134578` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>tests.vim.test_vim_with_vim_nix</li>
<li>vimPlugins.vim-xdebug</li>
</ul>
</details>

**Comment by r-burns** [comment]
Btw, in the future you can rebase onto `git merge-base master staging` and force push before switching the base branch, to avoid any extra commits showing up

**Comment by smancill** [comment]
> Btw, in the future you can rebase onto `git merge-base master staging` and force push before switching the base branch, to avoid any extra commits showing up

No, my problem was how to change the base branch here in the UI from `staging` to `master`, since I couldn't find it.

The title of the PR needs to be edited and then the option to the base branch is available, which is not very intuitive.

**Pull request merged**
