### PR TITLE
Experimental (preview) Pharo packaging

### PR DESCRIPTION
**Pull request by lukego**
This is an experimental new packaging of [Pharo](http://pharo.org/) for nixpkgs. I am concerned that this may be a dead-end due to the [xkcd 927](https://xkcd.com/927/) problem. There are too many ways to distribute and install Pharo applications and I may simply be making that worse. However, I would not like this work to be lost and so I share it here now.

This branch provides a few packages:

- `pharo-vm` is a wrapper for starting a suitable virtual machine. These days there are at least three mutually incompatible variants of the VM and each application will work in exactly one of them. The wrapper hides this complexity from the user and chooses the right one automatically. (This is based on a script shared on an upstream pharo mailing list.)
- Several applications (images): `pharo-5.0`, `pharo-6.0`, `moose-6.1`, etc. These are binaries from the internet and provided for convenient & so that they are tested for compatibility with the VMs.
- Behind the scenes, three virtual machines. One (cog) is built from an old source release and the others (spur and spur64) are built from very recent code using different build options (32-bit vs 64-bit.)

Compared with the existing pharo support in nixpkgs this should be more compatible (updated VMs) and provides more images (additional to the "launcher" image that frankly does not seem to work that well or be very actively maintained.) This branch also features a rewritten virtual machine build derivation in `build-vm.nix` because the latest VMs have a different build procedure to the one that was packaged before.

Just now I am considering whether to drop branch entirely, or upstream the virtual machine part, or upstream the whole shebang. See [squeak vm-dev mailing list](http://lists.squeakfoundation.org/pipermail/vm-dev/2017-April/024854.html) post for the thought process.

Feedback on the overall direction from nixpkgs point of view would be welcome if anybody else is specifically interested in Pharo.

### CODE REVIEW

**Comment by lukego** [comment]
Closing because this PR was only to share a work in progress. Likely to follow up with a new solution in the near future after Pharo 6.0 has shipped and upstream have more bandwidth find discussing the best solution.

**Comment by DamienCassou** [comment]
I think your work is important, so please keep going. I'm using neither Pharo nor Nix anymore, but I would appreciate a good packaging if I had to use them again.

> additional to the "launcher" image that frankly does not seem to work that well or be very actively maintained

I've indeed stopped maintaining it. Even though some people still use and [maintain it](http://smalltalkhub.com/#!/~Pharo/PharoLauncher/commits), I agree with you I can't say that's very active maintenance.

**Comment by lukego** [comment]
Thanks for the encouragement, @DamienCassou :).

I will come back to this in a month or so after the Pharo 6.0 release when people upstream will have more bandwidth to discuss packaging.

I also need to better understand the Pharo Launcher (didn't realize that you wrote that, btw) and what the intended vm*image compatibility matrix is supposed to be.

**Comment by lukego** [comment]
@DamienCassou btw, the SmalltalkHub link shows no activity when I open it in Chrome on OSX ([screenshot](http://imgur.com/a/T7fHV)). Could be some browser/website issue misleading me to think the project is not active when it actually is. I'll be careful to get in touch with the right people via the mailing list.

**Pull request closed without merging**
