### PR TITLE
gnomeExtensions.gsconnect: 54 -> 55

### PR DESCRIPTION
**Pull request by LostAttractor**
###### Description of changes
gnomeExtensions.gsconnect: 54 -> 55

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by piegamesde** [comment]
I know it's not related to this change, but can you please move the `postPatch` phase up to after the `patch` phase in a second commit?

Apart from that change looks good, please confirm on which GNOME version(s) you tested it.

**Comment by LostAttractor** [comment]
I am tested on Gnome 44 at both staging-next & master (since https://github.com/NixOS/nixpkgs/pull/224806 has been merged).

**Comment by LostAttractor** [comment]
@piegamesde I don't understand why you expect me to do this.
The current script in the `postPatch` phase is also patching the script/code that needs to be used in `buildPhase` and `testPhase`, why do you expect me to move it after the `patchPhase`

**Comment by mweinelt** [comment]
The request was about the position of `postPatch` in the `default.nix`. It should come after the `patches` array, not just before `postFixup`.

**Comment by mweinelt** [comment]
Ah, well. In python we prefer it in execution order. Should probably be standardized outside of this PR. :laughing:

**Pull request merged**
