### PR TITLE
nixos/modules/security/rngd: Disable by default

### PR DESCRIPTION
**Pull request by nicoonoclaste**
###### Motivation for this change

`rngd` seems to be the root cause for slow boot issues, and its functionality is
redundant since kernel v3.17 (2014), which introduced a `krngd` task (in kernel
space) that takes care of pulling in data from hardware RNGs:

> commit be4000bc4644d027c519b6361f5ae3bbfc52c347
> Author: Torsten Duwe <duwe@lst.de>
> Date:   Sat Jun 14 23:46:03 2014 -0400
>
>     hwrng: create filler thread
>
>     This can be viewed as the in-kernel equivalent of hwrngd;
>     like FUSE it is a good thing to have a mechanism in user land,
>     but for some reasons (simplicity, secrecy, integrity, speed)
>     it may be better to have it in kernel space.
>
>     This patch creates a thread once a hwrng registers, and uses
>     the previously established add_hwgenerator_randomness() to feed
>     its data to the input pool as long as needed. A derating factor
>     is used to bias the entropy estimation and to disable this
>     mechanism entirely when set to zero.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nbraud** [comment]
> Hmm, why did you remove the udev rules?

I removed the udev rules because they were all for hardware that's already handled by the kernel directly.

**Comment by shlevy** [comment]
@nbraud Perhaps we should remove rngd altogether, but this is the only hardware that rngd helps for anyway. If someone explicitly enables it presumably they want it for their devices?

**Review by NeQuissimus — APPROVED** [review]

**Comment by nbraud** [comment]
> @nbraud Perhaps we should remove rngd altogether, but this is the only hardware that rngd helps for anyway.

Removing the `rngd` module would make sense at this stage, yes.  It's a fair bit more work (as default configuration, documentation, and other modules need to be updated) and I'm unsure how to deal with it breaking backwards compat (removing the options under `security.rngd` might cause people's config to fail to evaluate).

It's possible some people might want `rngd` (the program) to deal with hardware RNGs that the kernel doesn't detect as such (I have a couple such devices, that provide a random stream over (emulated) USB-serial) but it doesn't seem to be a configuration that the module supports anyway (so there would be no loss of functionality)

> If someone explicitly enables it presumably they want it for their devices?

Presumably, but (as mentioned above) there doesn't seem to be a way, in the module, to point `rngd` at a custom device.

**Comment by vcunat** [comment]
> removing the options under `security.rngd` might cause people's config to fail to evaluate

`mkRemovedOptionModule` IIRC

**Comment by worldofpeace** [comment]
I'm now strongly confused as to why https://github.com/NixOS/nixpkgs/commit/1ac86e14c746140a7fa9a6e81a3471739655366b is needed then. I would prefer to remove this entirely. Just judging from the evidence presented here that krngd in kernel space should be handing this.

**Comment by worldofpeace** [comment]
backported fc5f50a94940ce071293aa3cd8b6dcbb685c4181 26c98e742f22c657ac7e31aacc67c8640b62c27d to release-20.09

**Comment by nbraud** [comment]
Thanks @worldofpeace, and sorry for going silent: I've been pretty sick the last month+, and the workstation I installed NixOS on decided to just die.  (I'm currently RMAing the motherboard.  >_>')

**Pull request merged**
