### PR TITLE
amdgpu-pro: 17.10 -> 17.40

### PR DESCRIPTION
**Pull request by corngood**
###### Motivation for this change

Building off #29698 and #31644.

DKMS module compiles and loads.  I'm having trouble getting xorg to start on my R9 290, due to what looks like DC related modesetting errors.

If anyone else can test it, that would be appreciated.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bkchr** [comment]
@corngood I think you missed to push the new patches.

**Comment by corngood** [comment]
@bkchr Looks like the patches are there, but I had the wrong kernel derivation.  Should be fixed now.

**Comment by corngood** [comment]
@bkchr  Actually, you're right, it's still broken.  Sorry about that.  I'll have to fix it when I get home.

**Comment by corngood** [comment]
@bkchr  should be fixed now

Keep in mind that this alters boot.kernelPackages, so if you have kernel overrides, you'll need to make sure to set `KALLSYMS_ALL y`, and it's unlikely to work with anything other than 4.9.  Unfortunately this also means a local kernel rebuild.

**Comment by Mounium** [comment]
On an R9 380 it results in a black screen. Logging in with ssh tells me that the video card indeed uses amdgpu, but I can't really find anything in journalctl why wouldn't there be anything to display, the same for me as with other versions of amdgpu-pro on nixos. 
Here is the diff of amdgpu and amdgpu-pro (on different kernel) `journalctl -b -p 4 -o cat`:  https://gist.github.com/Mounium/7b270f4939ec4b83010b97f16363bd38

**Comment by corngood** [comment]
I added the `xreallocarray` hack I described here: https://github.com/NixOS/nixpkgs/issues/33619#issuecomment-356991967

I now have a working xserver.

Tested software:
- [x] xorgserver
- [x] OpenGL (glxgears)
- [ ] Vulkan
- [ ] OpenCL
- [ ] VDPAU
- [ ] OpenGL 32bit
- [ ] Vulkan 32bit
- [ ] OpenCL 32bit
- [ ] VDPAU 32bit

Hardware:
- [x] R9 290
- [ ] More GPUS

I need to go to bed, but if anyone can try it and give test results for the stuff above, that would be great.

**Comment by corngood** [comment]
I got all the major bits tested except OpenCL.  I tried `clinfo` from `amdappsdk`, but it just crashed.

Any suggestions for testing CL with something in nixpkgs?

I also removed WIP because this is at least working, unlike what's there, although I wouldn't mind confirmation on some other GPUs.

**Comment by AndrewMorsillo** [comment]
This does not work for me on an rx480. Same issue as before, sddm starts but kde immediately crashes back to the login manager.

**Comment by corngood** [comment]
@AndrewMorsillo I don't think it's exactly the same problem, because before my last change the xorg driver wouldn't even load.  If you have a desktop manager, you must have an xorg driver.  It sounds like it's crashing when it first uses GL.  Could you share your `uname -a`, `modinfo amdgpu`, and any logs that provide info about the crash?

**Comment by AndrewMorsillo** [comment]
@corngood sorry it took so long for me to get back to you. Version 17.10 builds fine on unstable for me but I still have the issue where I can log in with sddm but then get booted right back to it (plasma fails to start).

uname -a
`Linux nixos 4.9.78 #1-NixOS SMP Tue Jan 23 18:57:10 UTC 2018 x86_64 GNU/Linux`

Here is output from modinfo amdgpu
https://pastebin.com/8eyg77x7

Here is some output from journalctl -r. 
https://pastebin.com/YF3BvZvS

**Comment by corngood** [comment]
@AndrewMorsillo Sorry I'm a bit confused.  Have you actually tested this PR (17.40)?  Your logs show 17.10.  Could you post logs from 17.40?

**Comment by Mounium** [comment]
Unfortunately it doesn't run for me either (xorg doesn't load up), here are the relevant logs:
```
Linux 4.9.79 #1-NixOS SMP Wed Jan 31 11:55:57 UTC 2018
86_64 GNU/Linux
```

modinfo:
https://gist.github.com/Mounium/f832bb3e0e9a63ba499a0fb82d5dc5c5

relevant journalctl log:
https://gist.github.com/Mounium/19a124b4f42c820f5c04474e0bc0e4d0

**Comment by AndrewMorsillo** [comment]
@corngood I tried both 17.10 and 17.40 with the same results and as far as I can tell the same log output.

**Comment by corngood** [comment]
@AndrewMorsillo 

```
Jan 30 17:03:31 nixos sddm-greeter[1023]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
```

This kind of stuff is very strange.  Could you maybe try using slim instead of sddm?

**Comment by corngood** [comment]
@Mounium I don't see anything helpful in your log.  I guess you don't even get to your display manager?

**Comment by Mounium** [comment]
Even the boot screen, ttys won't load up with these drivers on NixOS, unfortunately I couldn't even get any useful logs out of it.

**Comment by edwtjo** [comment]
This PR solves my crashing xorg problems at c10288c171fcec37821c28b96437e933e41033d8 the card is a R9 M370X

**Comment by corngood** [comment]
@edwtjo I assume you have working xorg, opengl, etc?

@vcunat  I think we should put this in.  It's definitely less broken than 17.10.

**Comment by edwtjo** [comment]
@corngood yes and I think this should be merged.

**Pull request merged**
