### PR TITLE
[staging-20.09] openblas: 0.3.10 -> 0.3.12

### PR DESCRIPTION
**Pull request by nomeata**
this backports the following commits from `master` to 20.09:

* f52263ced09 treewide: Start to break up static overlay
* d1d536cc07f openblas: 0.3.10 -> 0.3.12
* f715602febc Revert "openblas: 0.3.10 -> 0.3.12"
* 840c20169e9 Merge pull request #101715 from r-ryantm/auto-update/openblas
* e1a59dddd08 openblas: 0.3.10 -> 0.3.12
* 4e291519102 Revert "Merge pull request #101780 from glittershark/bump-openblas"
* 3b4cd4f4dac openblas: 0.3.10 -> 0.3.12
* 692d219a931 Merge staging-next into staging
* 7902256cfd1 openblas: enable multiple outputs
* 92d7b38e89a openblas: enable on ppc64le

The motivation is to unbreak building `python36Packages.scipy` (see
issue 92458)

### CODE REVIEW

**Comment by nomeata** [comment]
(Targeting staging as per advice by @TredwellGit in https://github.com/NixOS/nixpkgs/issues/92458#issuecomment-756308950)

**Comment by nomeata** [comment]
@ofborg build python36Packages.scipy

**Comment by jonringer** [comment]
just saw this, generally we do a cherry-pick, so theres a 1-to-1 correlation between commits in master, to commits in 20.09.

Also, the branches seem to have divereged to the point that it might be worthwhile to just bump the package on 20.09 instead of cherry-picking

**Comment by nomeata** [comment]
Given that on master there are commits and reversion etc, it seemed cleaner to me to just get the state of the package from master (`git checkout master -- …`). I just listed the contributing commits for reference,  so unless I misunderstand what you are saying, I am just doing what you describe in

>  it might be worthwhile to just bump the package on 20.09 instead of cherry-picking

am I?

**Comment by twhitehead** [comment]
Ran into this on our HPC cluster. Would be great if it could get pulled. :smile:

**Comment by r-burns** [comment]
Well, I think what we would want to do for this backport, is only update the version and hash (and remove the upstreamed patch). The static/shared and split-outputs changes, while beneficial, could potentially cause breakage in package dependees.

**Comment by twhitehead** [comment]
Sounds reasonable to me. @nomeata, let me know if you are too busy to modify you pull request, and I can submit an alternative one that just bumps the version and drops the obsolete patch.

**Comment by jonringer** [comment]
Yea, this is kind of an exceptional case, where it was reverted several times. I guess squashing is fine. However, this is only bumping to `0.3.12` not `0.3.13` currently

**Comment by twhitehead** [comment]
Right. It is just the subject that is wrong. The bump only needs to be to 0.3.12, as per the actual patch and the referenced commits, to fix the scipy issue.

**Comment by nomeata** [comment]
Oh, embarrassing. Fixed the title.

Is there more for me to do? I have withdrawn my toes, so if someone else does a proper fix before me and closes this one, they would not be stepped on.

**Comment by twhitehead** [comment]
@r-burns suggested just bumping the version and hash to make the changes as minimal  as possible, which seems reasonable to me (not that my opinion matters).

What is you thoughts on this @jonringer? Is this good as is now, or are you thinking it would be best to just bump the version and change the hash?

**Comment by jonringer** [comment]
@GrahamcOfBorg build python3Packages.numpy

**Review by jonringer — APPROVED** [review]
I think it's find for now, I would like for it to be updated to 0.3.13 though, as 0.3.12 has a threading issue with high core count cpus https://github.com/xianyi/OpenBLAS/issues/2993#issuecomment-730374018

**Comment by twhitehead** [comment]
Are you wanting 01378600776 squashed into this as well, or a separate pull request for it?

**Comment by jonringer** [comment]
It would be my preference to have it squashed, as it allows me to review the package without failure

**Comment by nomeata** [comment]
> It would be my preference to have it included and squashed, as it allows me to review the package without failure.

Done

**Comment by roberth** [comment]
Is this ready for a merge?

**Comment by twhitehead** [comment]
> Is this ready for a merge?

I believe so. @nometa has addressed everything that @jonringer has brought up.

**Comment by roberth** [comment]
Thanks! Merging into `staging-20.09` https://github.com/NixOS/nixpkgs/pull/112373

**Pull request merged**
