### PR TITLE
doc/tauri: use tauri 2.0 dependencies & new darwin SDK pattern in example

### PR DESCRIPTION
**Pull request by getchoo**
Part of https://github.com/NixOS/nixpkgs/issues/354146

Follow up to https://github.com/NixOS/nixpkgs/pull/346277

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Eveeifyeve — COMMENTED** [review]
Just need to test this pr before I can say it's a good to go.

**Comment by pluiedev** [comment]
I think libsoup is still required, but with libsoup_3 instead of libsoup

**Comment by pluiedev** [comment]
And BTW, should also mention that libayatana-appindicator or libappindicator is required on Linux if the app has the `tray_icon` feature enabled (see https://github.com/tauri-apps/tauri/blob/f884bae75b3ad8f8debfd29bb05ac9cbc9748c89/crates/tauri-cli/src/interface/rust.rs#L1242-L1267)

**Comment by getchoo** [comment]
> I think libsoup is still required, but with libsoup_3 instead of libsoup

webkitgtk_4_1 already [uses it](https://github.com/NixOS/nixpkgs/blob/ecd6e1eed151a8d1a9c81ed0572ec294c6e20397/pkgs/top-level/all-packages.nix#L11192) and [propagates it](https://github.com/NixOS/nixpkgs/blob/ecd6e1eed151a8d1a9c81ed0572ec294c6e20397/pkgs/development/libraries/webkitgtk/default.nix#L202)

> And BTW, should also mention that libayatana-appindicator or libappindicator is required on Linux if the app has the tray-icon feature enabled (see https://github.com/tauri-apps/tauri/blob/f884bae75b3ad8f8debfd29bb05ac9cbc9748c89/crates/tauri-cli/src/interface/rust.rs#L1242-L1267)

This would be better in a separate PR (and was actually missing from the v1 documentation as well). We should also try to avoid LD_LIBRARY_PATH hacks and opt instead of forcing linking through linker args/patching -- as done [here](https://github.com/NixOS/nixpkgs/blob/9d9c9b1bfdf8700ac538f32177189d2496779ae2/pkgs/by-name/cl/clash-verge-rev/unwrapped.nix#L32-L33) for example

**Pull request merged**
