### PR TITLE
zsh-navigation-tools: 1.4 -> 2.0.7, install all files

### PR DESCRIPTION
**Pull request by psprint**
Basic update, all files are installed (this allows to comfortably run ZNT with *plugin.zsh file) and version bump

### CODE REVIEW

**Comment by makefu** [comment]
Not sure what the `official` maintainers think but your commit messages do not seem to follow the contributing guidelines ( https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md ) . Keep in mind that your commits will become part of the shared history of nixpkgs :)

Besides that, the commit looks good, waiting for it to arrive at unstable :+1:

**Comment by psprint** [comment]
@makefu: Thanks I have updated the commit messages

**Comment by zimbatm** [comment]
Thanks !

**Comment by psprint** [comment]
Thanks for the merge!

**Pull request merged**
