### PR TITLE
chromium: delete no longer needed patchset

### PR DESCRIPTION
**Pull request by Ekleog**
If I read this error message correctly, this patchset is no longer
needed:

trace: WARNING: chromium: stable version 66.0.3359.117 is newer than a patchset bounded at 66. You can safely delete it.

Building before and after this change on my (non-aarch64) machine doesn't change the hash, so I can't do much for testing except wait for ofborg's build.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Ofborg will timeout for sure for chromium.

**Comment by Ekleog** [comment]
Cc @chaoflow @bendlas

**Comment by Ekleog** [comment]
Well, I'm not sure it will, as it's supposed to not rebuild anything, it should get it from binary cache :)

**Comment by Ekleog** [comment]
Sounds like the patch was actually still required. Closing in favor of https://github.com/NixOS/nixpkgs/pull/39633.

**Pull request closed without merging**
