### PR TITLE
zsh-fzf-tab: 1.0 -> 1.1.1

### PR DESCRIPTION
**Pull request by Vonfry**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Vonfry** [comment]
The darwin one will build failed because the default filesystem is case-insensitive APFS and there are both src and Src in source dir in the new release building process. It should be reported to upstream or patch in nixpkgs specially. If someone would like to do it, PR is welcome.

**Comment by dbaynard** [comment]
Aloxaf/fzf-tab#421 builds on Darwin — you may use this, until the bug is fixed.

```nix
src = fetchFromGitHub {
  owner = "dbaynard";
  repo = "fzf-tab";
  rev = "f53850a5088f65c9492600b4485fe5f463e90f59";
  hash = "sha256-AWoP/ZaaZd9OsYWZqr7gFnzBfv4Bz2xguP3RJ9hE83s=";
};
```

However I would like to delete my fork when the PR is closed/merged, so perhaps best to wait?

**Comment by dbaynard** [comment]
@scoiatael is there away to have nix pick the `src` as is and convert the `Src` to `src~nix~case~hack~1`?

**Comment by scoiatael** [comment]
> @scoiatael is there away to have nix pick the `src` as is and convert the `Src` to `src~nix~case~hack~1`?

if I read https://github.com/NixOS/nix/commit/276a40b31f631c188d6dcbdf603a738e1380ff74#diff-c304dc8febdd19002dc22cb044b0319a34775d5cba32522ade0ad38cfd89bf60R246-R256 correctly it's not likely - looks like it's based on file order in the archive. But I don't know nix enough to say that there are no better language constructs to deal with it.

But the change I propose should work for all cases - on case sensitive filesystems `src*` should expand to `src` and on macOS it will expand to `src~nix~case~hack~1`. @Vonfry do you need me to submit a patch to configure script?

**Comment by Vonfry** [comment]
> But the change I propose should work for all cases - on case sensitive filesystems src* should expand to src and on macOS it will expand to src~nix~case~hack~1. 

I have recommited it in this pr.

**Comment by Vonfry** [comment]
The upstream release a new version to fix the darwin building. Therefore, this pr is updated as well.

**Pull request merged**
