### PR TITLE
samtools: 1.5.0 -> 1.6.0

### PR DESCRIPTION
**Pull request by mimame**
###### Motivation for this change

htslib, samtools and bcftools
- Update to the last versions
- Prograte htslib to samtools and bcftools
- Enable enableParallelBuilding
- Do tests

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Using binaries from PATH is the reasonable thing to do for upstream projects, so I don't think that we should patch in absolute paths. Just add the necessary programs to `nativeBuildInputs`.

**Comment by mimadrid** [comment]
Thanks a lot @orivej. I didn't do that because I didn't know which was better buildInputs vs nativeBuildInputs. I will update the commits as soon as possible

**Comment by mimadrid** [comment]
@orivej Fixed. Don't hesitate to ask for more changes

**Comment by orivej** [comment]
Why didn't you add `perl` too?

**Comment by mimadrid** [comment]
@orivej, thanks a lot for your support and help
I hope to have done all right this time. I've also prograte htslib to samtools and bcftools.

**Comment by orivej** [comment]
Please review my changes.

samtools and bcftools install some python and perl scripts. We do not even depend on python, and I have not checked that perl scripts have all the necessary dependencies to run. This can be left as is until someone needs them.

**Comment by mimadrid** [comment]
That's perfect but I think that htslib has to be propagated to samtools and bcftools for using bgzip and tabix

**Comment by orivej** [comment]
Do you mean that users of samtools and bcftools also need bgzip and tabix in their PATH?

**Comment by mimadrid** [comment]
I think so because in other distros the htslib dependency is visible from PATH by default.
Which is your opinion?

**Comment by orivej** [comment]
Other distros have no other way. From a quick glance it does not seem that samtools need htslib binaries. (Even if they did, the proper solution is a program wrapper that adds htslib to the PATH of the wrapped program, not a propagation of htslib.)

**Pull request merged**
