### PR TITLE
udev service: generate hwdb database from all udev packages

### PR DESCRIPTION
**Pull request by abbradar**
With this a proper hwdb database should be generated from `services.udev.packages`. Because many `hwdb` files are contained in `udev` package itself, it was added to `services.udev.packages` (why wasn't it there, anyway?). Also we now don't dynamically regenerate `hwdb.bin` in activatiion script, which is a Good Thing IMO.

### CODE REVIEW

**Comment by edolstra** [comment]
Why is that a good thing? This makes the system closure bigger.

Also, there  is no `udev` package anymore, it's just an alias for systemd. And we were definitely using systemd's hwdb files.

**Comment by abbradar** [comment]
First, we have several packages with their own `hwdb` files, namely `libmtp`, and `sane-backends` (the latter doesn't generate them now but I have a PR underway). `hwdb` can also be used for nice things, for example (my usecase) https://wiki.archlinux.org/index.php/Map_scancodes_to_keycodes#Example_for_custom_hwdb . We don't have any way of adding `hwdb` files at this time.

Second, right now we are essentially emulating what Nix should do (check if dependencies changed and if they did, rebuild something) inside an activation script which feels inelegant. Also, this makes `/etc` more immutable (I like the idea of fully immutable `/etc` sometime in the future). I referred to those tho points as a Good Thing.

I can't understand closure size argument -- if it doesn't reside in `/nix/store`, it will be generated by an activation script and reside in `/etc` taking the same space, unless I'm misunderstanding something (I also don't take symlinks, metadata stored by Nix etc. into account).

`udev` is an alias defined in the module -- I used it for brevity.

**Comment by abbradar** [comment]
Name changed because we indeed do have a proper hwdb database now, it's just composed only of entries from `systemd` package.

**Comment by edolstra** [comment]
Increases in closure size affect how long it takes to deploy a machine via NixOps, etc. Also, when cached data is stored in /var/cache, we store only one version at a time; by contrast, keeping it in the Nix store might cause us to store many different versions (in the worst case, one for each generation of the system profile).

In the case of hwdb.bin, the size of ~6 MB is not a huge problem, but not entirely trivial either.

As an aside (regarding the immutable /etc): we used to keep hwdb.bin in /var, but for some reason that's no longer the case, even though the systemd Nix expression still has `makeFlags = "hwdb_bin=/var/lib/udev/hwdb.bin"`.

**Comment by abbradar** [comment]
Ah, I see now. Indeed, there is some value in generating cache files on demand then, but I can't see how to do this easily in this case (we now can have multiple dependencies), while also switching to new hwdb on a NixOS switch without a reboot or a manual regeneration.

A quick question: we may want to drop this make flag, but this would be a mass rebuild. I have just pushed (mass-rebuildy) `fontconfig` updates to staging and Hydra has not yet evaluated them -- maybe quickly throw the patch on a departing train?

**Comment by abbradar** [comment]
I've added a patch to drop our hwdb location changes -- I haven't known about them, and without removing them the patchset is not fully correct. Notice that this makes it a mass rebuild!

**Comment by abbradar** [comment]
Ah, I've looked into `systemd` source, and it looks like they don't have any make flags anymore, simply having [a constant](https://github.com/NixOS/systemd/blob/nixos-v228/src/hwdb/hwdb.c#L44). I've changed the patch to only leave a comment "please remove this sometime later", so this is not a mass rebuild anymore.

**Comment by abbradar** [comment]
@edolstra ping, what do you think? tl;dr: I don't see a simple way to do this in activation script because not only `systemd` can be a dependency -- it can be done but would be too complex in my opinion for too little gain. Also doing this in Nix should update hwdb database without a reboot, so if we resolve #12790 it would be reloaded automatically on switch, which sounds very nice to have.

**Comment by puffnfresh** [comment]
@abbradar this is awesome. Up until now I've used a preFixup override for systemd to have a custom rule that I needed. Thank you!

**Pull request merged**
