### PR TITLE
wezterm: make it build with clang 19

### PR DESCRIPTION
**Pull request by ofalvai**
zlib patch: the upstream patch doesn't apply to this old vendored version of zlib.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@ofborg build wezterm

**Comment by SuperSandro2000** [comment]
No idea why darwin is failing

```
warning: non-local `impl` definition, `impl` blocks should be written at the same level as their item
  --> mux/src/renderable.rs:23:86
   |
23 |     Debug, Clone, Copy, PartialEq, Eq, Default, Deserialize, Serialize, FromDynamic, ToDynamic,
   |                                                                                      ^--------
   |                                                                                      |
   |                                                                                      `ToDynamic` is not local
   |                                                                                      move the `impl` block outside of this constant `_IMPL_PLACEDYNAMIC_FOR_RenderableDimensions`
24 | )]
25 | pub struct RenderableDimensions {
   |            -------------------- `RenderableDimensions` is not local
   |
   = note: the derive macro `ToDynamic` defines the non-local `impl`, and may need to be changed
   = note: the derive macro `ToDynamic` may come from an old version of the `wezterm_dynamic_derive` crate, try updating your dependency with `cargo update -p wezterm_dynamic_derive`
   = note: an `impl` is never scoped, even when it is nested inside an item, as it may impact type checking outside of that item, which can be the case if neither the trait or the self type are at the same nesting level as the `impl`
   = note: items in an anonymous const item (`const _: () = { ... }`) are treated as in the same scope as the anonymous const's declaration for the purpose of this lint
   = note: this warning originates in the derive macro `ToDynamic` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by ofalvai** [comment]
@SuperSandro2000 those are warnings only, the real failure is the last line of the ofBorg log:

```
error: building of '/nix/store/6y2kr2qcrjmknk7hz0sy2gmaplmgvhjk-wezterm-20240203-110809-5046fc22.drv^out' from .drv file timed out after 3600 seconds
```

Let me run a nixpkgs-review on all platforms as proof

**Comment by ofalvai** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366840`

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>wezterm</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>wezterm</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>wezterm</li>
  </ul>
</details>

**Comment by vcunat** [comment]
I confirm aarch64-darwin and x86_64-linux builds.

**Pull request merged**
