### PR TITLE
yabai: init at 2.4.3

### PR DESCRIPTION
**Pull request by cmacrae**
###### Motivation for this change
These changes add me as a maintainer and introduce a package for yabai, for Darwin systems.  
I've been maintaining my own package for quite some time, so figured it was time to finally share it.  

This PR supersedes #73260 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by LnL7 — CHANGES_REQUESTED** [review]
Looks like you forgot to expos this ini all-packages.nix.

**Comment by cmacrae** [comment]
Whoops! I did, thanks @LnL7 👍🏻 I’ll add it shortly

**Comment by LnL7** [comment]
@GrahamcOfBorg build yabai

**Comment by LnL7** [comment]
Seems like it doesn't build on 10.12, is that expected?

**Comment by cmacrae** [comment]
> Seems like it doesn't build on 10.12, is that expected?

Yep, it's not supported on 10.12, I believe.  Is there any measures we can take in the package to express this? :)

**Comment by cmacrae** [comment]
The Makefile outlines the following build flag for clang: `-mmacosx-version-min=10.13 `

**Comment by LnL7** [comment]
Just double checking.

We don't differentiate os versions, that would mean we'd have to build everything separately for each supported version. For most things we ensure builds don't use symbols that are not available on all supported versions, but frameworks are impure which means this can happen.

**Review by LnL7 — APPROVED** [review]

**Comment by cmacrae** [comment]
Yeah of course,  that makes sense 👍   
Thanks for the review and merge 🙏 Much appreciated

**Pull request merged**
