### PR TITLE
kernel-config: enable vanilla PaX ports

### PR DESCRIPTION
**Pull request by joachifm**
Might be nice to know about for people who want a little bit of PaX but are too timid for the real deal :) Tested by building configfile.

### CODE REVIEW

**Comment by spacekitteh** [comment]
Are these flags enabled in the hardened kernel too?

**Comment by joachifm** [comment]
If this ends up being accepted, I'll have to take it into account for the grsec kernel; I have not looked into what happens when both HARDENED_USERCOPY and PAX_USERCOPY are enabled at the same time (which they are now).

**Review by fpletz — APPROVED** [review]

**Comment by joachifm** [comment]
Hm, I wonder if anybody would seriously entertain enabling these? Though grsecurity upstream are generally not too enthused about the ports of their stuff, I *think* these make sense as stand-alone mitigations, at least conceptually (I can't speak to potential shortcomings in the ports).

**Comment by joachifm** [comment]
If not I'll close this in a little while.

**Comment by spacekitteh** [comment]
I don't understand the cause for concern?

**Comment by joachifm** [comment]
@spacekitteh there may be concerns over performance

**Comment by joachifm** [comment]
Some background on usercopy: https://lwn.net/Articles/695991/. The author of the port claims no measurable performance impact, but I'm unaware of any comprehensive benchmarking.

**Comment by joachifm** [comment]
I've just gone ahead and added a hardened kernel config instead ...

**Pull request closed without merging**
