### PR TITLE
circt: 1.83.0 -> 1.84.0

### PR DESCRIPTION
**Pull request by sequencer**
- **circt: 1.83 -> 1.84**
- **circt: add sequencer to maintainers**

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by smancill — DISMISSED** [review]
You need to add yourself to the maintainers list, in a separate commit.

See https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md

**Comment by sequencer** [comment]
Thanks~

**Comment by pineapplehunter** [comment]
Result of `nixpkgs-review pr 338312` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>circt</li>
    <li>circt.dev</li>
    <li>circt.lib</li>
  </ul>
</details>

**Review by pineapplehunter — APPROVED** [review]

**Comment by sequencer** [comment]
result of `nixpkgs-review pr 338312` (build on aarch64)
```
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/338312/head:refs/nixpkgs-review/1
remote: Enumerating objects: 2132, done.
remote: Counting objects: 100% (1028/1028), done.
remote: Compressing objects: 100% (395/395), done.
Receiving objects: 100% (691/691), 211.05 KiB | 783.00 KiB/s, done.
remote: Total 691 (delta 475), reused 442 (delta 253), pack-reused 0 (from 0)
Resolving deltas: 100% (475/475), completed with 143 local objects.
From https://github.com/NixOS/nixpkgs
 * [new branch]                master                -> refs/nixpkgs-review/0
 * [new ref]                   refs/pull/338312/head -> refs/nixpkgs-review/1
$ git worktree add /home/sequencer/.cache/nixpkgs-review/pr-338312/nixpkgs b956c2f42a5d0c9fbbfd8b2a9cf3bb5f0a6fcf41
Preparing worktree (detached HEAD b956c2f42a5d)
Updating files: 100% (42976/42976), done.
HEAD is now at b956c2f42a5d ocamlPackages.lockfree: 0.4.0 → 0.5.0
$ git merge --no-commit --no-ff 21baffd4052beea8fc8b78415b24cac5528ac94e
Auto-merging maintainers/maintainer-list.nix
Automatic merge went well; stopped before committing as requested
┏━ Dependency Graph:
┃ ✔ review-shell
┣━━━ Builds
┗━ ∑ ⏵ 0 │ ✔ 1 │ ⏸ 0 │ Finished at 20:16:49 after 0s

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/338312

3 packages built:
circt circt.dev circt.lib

$ /etc/profiles/per-user/sequencer/bin/nom-shell --argstr system aarch64-linux --argstr nixpkgs-path /home/sequencer/.cache/nixpkgs-review/pr-338312/nixpkgs --argstr nixpkgs-config-path /tmp/tmp39xsx_dn.nix --argstr attrs-path /home/sequencer/.cache/nixpkgs-review/pr-338312/attrs.nix --nix-path 'nixpkgs=/home/sequencer/.cache/nixpkgs-review/pr-338312/nixpkgs nixpkgs-overlays=/tmp/tmp2gias7bm' /nix/store/31zva50bkbk1cihpzd66jy7aahm6521z-nixpkgs-review-2.10.5/lib/python3.12/site-packages/nixpkgs_review/nix/review-shell.nix
```

**Review by NickCao — APPROVED** [review]

**Pull request merged**
