### PR TITLE
Merge staging-next into staging

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/runs/2326588858?check_suite_focus=true

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is normally done by someone with push access. Can't really review it if the merge conflict resolving has errors.

**Comment by vcunat** [comment]
I'm not sure about some of the conflicts, say `fetchpypi` vs. `fetchFromGitHub` (a few cases), but none of them seems important.

**Comment by jonringer** [comment]
Pretty sure this is done after a `staging-next` cycle is merged into master, it's then merged into staging, and then the next `staging-next` cycle begins

correct me if I'm wrong cc @FRidh

**Comment by lukegb** [comment]
Ordinarily the bot would do it, but there are merge conflicts, so it's been broken for [a few days](https://github.com/NixOS/nixpkgs/pull/105153#issuecomment-818025241)

**Comment by SuperSandro2000** [comment]
> Pretty sure this is done after a `staging-next` cycle is merged into master, it's then merged into staging, and then the next `staging-next` cycle begins
> 
> correct me if I'm wrong cc FRidh

Master gets merged every 6 hours into staging-next and that every 6 hours into staging. See https://github.com/NixOS/nixpkgs/blob/master/.github/workflows/merge-staging.yml#L24

**Comment by SuperSandro2000** [comment]
> I'm not sure about some of the conflicts, say `fetchpypi` vs. `fetchFromGitHub` (a few cases), but none of them seems important.

They are important because pypi often has no tests.

**Comment by vcunat** [comment]
This PR chose `fetchFromGitHub` in all/both the conflicts, if I look right.

**Pull request merged**
