### PR TITLE
local-ai: 2.11.0 -> 2.12.3

### PR DESCRIPTION
**Pull request by ck3d**
## Description of changes

- update local-ai to latest version
- activated tts and stablediffusion per default
- added llama test

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by teto** [comment]
Result of `nixpkgs-review pr 302907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>local-ai</li>
  </ul>
</details>

**Comment by teto** [comment]
when enabling cuda, I get 
```
       > -- Detecting CXX compile features - done
       > -- Could NOT find Git (missing: GIT_EXECUTABLE)
       > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
       > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
       > -- Found Threads: TRUE
       > CMake Warning at CMakeLists.txt:297 (message):
       >   WHISPER_CUBLAS is deprecated and will be removed in the future.
       >
       >   Use WHISPER_CUDA instead
       >
       > 

```
in the logs.

**Comment by teto** [comment]
In my fork of nixpkgs (nixos-unstable + some patches from staging/master), whisper-cpp doesn't build with 
```

      cp ${whisper-cpp}/lib/static/lib*.a sources/whisper.cpp

**Comment by teto** [comment]
sry dunno how but somehow firefox focused "close" as I was editing a message :/

**Comment by ck3d** [comment]
I had to rebase to latest master, since cuda-modules has been update and broke cuda support. See PR description for additional information about my latested changes.

**Comment by teto** [comment]
Result of `nixpkgs-review pr 302907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>local-ai</li>
  </ul>
</details>

**Comment by teto** [comment]
I've built the cuda version and made it work with success ! 

I get this warning when building the tests.
```
$ nix-build -A local-ai.tests                           
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
```

**Comment by teto** [comment]
`nix-build -A local-ai.tests` (with cuda on) shows: 
```
machine # [  283.724375] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr whisper_backend_init: using CUDA backend
machine # [  283.736613] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr ggml_cuda_init: failed to initialize CUDA: CUDA driver is a stub library
machine # [  283.746635] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr ggml_backend_cuda_init: error: invalid device 0
machine # [  283.749849] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr whisper_backend_init: ggml_backend_cuda_init() failed
machine # [  283.751778] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr whisper_model_load:      CPU total size =    31.57 MB
machine # 100 47725    0     0  100 47725      0   9106  0:00:05  0:00:05 --:--:--  9116[  284.617496] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr whisper_model_load: model size    =   31.57 MB
machine # [  284.621479] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr whisper_backend_init: using CUDA backend
machine # [  284.623934] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr ggml_backend_cuda_init: error: invalid device 0
machine # [  284.626259] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr whisper_backend_init: ggml_backend_cuda_init() failed
machine # [  284.627860] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr whisper_init_state: kv self size  =    8.26 MB
machine # [  284.630816] local-ai[584]: 9:37AM DBG GRPC(ggml-tiny.en-q5_1.bin-127.0.0.1:42411): stderr whisper_init_state: kv cross size =    9.22 MB
```
then seems to be stuck:
```
m model=whisper-en --output transcription.json, in 474.79 seconds)
machine: must succeed: /nix/store/fnpqqn7v8f6nqywxvngv4sp7k590m0x0-jq-1.7.1-bin/bin/jq --exit-status 'debug | .segments | first.text == "Hello, how are you?"' transcription.json
machine # ["DEBUG:",{"segments":[{"id":0,"start":0,"end":1200000000,"text":"Hello, how are you?","tokens":[50363,18435,11,703,389,345,30,50423]}],"text":"Hello, how are you?"}]
(finished: must succeed: /nix/store/fnpqqn7v8f6nqywxvngv4sp7k590m0x0-jq-1.7.1-bin/bin/jq --exit-status 'debug | .segments | first.text == "Hello, how are you?"' transcription.json, in 0.29 seconds)
(finished: run the VM test script, in 755.28 seconds)
test script finished in 755.56s
cleanup
kill machine (pid 9)
qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/bin/python3.11)
(finished: cleanup, in 0.02 seconds)
kill vlan (pid 7)
```

Not blocking for me so feel free to merge.

**Review by teto — APPROVED** [review]

**Comment by ck3d** [comment]
Thanks for review. Some test can not be executed with cublas os clblas. I will make the test conditional with the next PR.

**Pull request merged**
