### PR TITLE
HOTFIX: Do not allow GRUB re-installs at the moment!

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by ts468** [comment]
@wkennington @lethalman @edolstra
What do you think?  At the moment there seems to be an issue with GRUB not finding a boot menu after calling grub-install.

**Comment by wkennington** [comment]
Are you using the code in master? What does your /boot look like.

**Comment by ts468** [comment]
I think grub configuration is split over two directories:
/boot/grub/grub.cfg
/boot/boot/grub/...

**Comment by wkennington** [comment]
That should be fixed in master, try deleting /boot/boot and forcing a
reinstall.

**Comment by edolstra** [comment]
Eh, what is this for? If there is a bug, shouldn't we fix it instead?

**Comment by wkennington** [comment]
The bug should be fixed but you have to force a reinstall of grub, maybe we
need a parameter in the update file to be able to force updates when we
have fixes like this?

**Comment by edolstra** [comment]
Maybe we should revert the recent changes to the GRUB menu builder? They seem to have made it significantly more complex, and this is the one critical part of NixOS - if we mess up here, users can't roll back to previous configurations.

**Comment by wkennington** [comment]
I would prefer not to revert as it should be in working order if you did not get caught installing between d4fc2b4d99122ba6592835aa84f659b22aeea433 and cb343e7be6445a643a22992871a76e4911af2c49

The problem in this case seems to be that c38a9b607fada946bedefcd45f1ec836583a0e1d forced a rebuild prior to cb343e7be6445a643a22992871a76e4911af2c49 which caused broken installations. I've done some testing on my own fat32 systems which shows everything is now in working order. I'm trying to get confirmation from ts486 and roconner.

I'm also working on a test case for fat32 /boot's to make sure we don't see the regression in the future.

**Comment by ts468** [comment]
My system could boot with GRUB successfully. I've deleted /boot/boot---as it shouldn't be there?---and /boot/grub/state to trigger a reinstall of GRUB.

@wkennington thanks for the quick fix! @edolstra sorry for the noise.

**Comment by wkennington** [comment]
Correct, I think we can say this is resolved.

**Comment by roconnor** [comment]
Building in master worked for me.

**Pull request closed without merging**
