### PR TITLE
python3.pkgs.pygls: 0.13.0 -> 1.0.0

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
Result of `nixpkgs-review pr 204457` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>cmake-language-server</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python39Packages.jedi-language-server</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>ycmd</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python310Packages.lsprotocol</li>
    <li>python310Packages.nox</li>
    <li>python310Packages.pygls</li>
    <li>python39Packages.lsprotocol</li>
    <li>python39Packages.nox</li>
    <li>python39Packages.pygls</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
Some dependents fail to build with this update ^, better wait for them to accommodate for pygls' breaking changes.. Converting to draft.

**Comment by RTUnreal** [comment]
is there an update on this PR?
jedi-language-server upstream has been updated, which many of the build failures rely on. (cmake-language-server seems to use pygls, so I am not sure how the state there is, and vimPlugins.YouCompleteMe seems to be deprecated)

**Comment by benjaminor** [comment]
cmake-language-server-0.1.6 still uses pygls-0.13.0 (they have updated it on master https://github.com/regen100/cmake-language-server/commit/a28d3803ad6b1b78978d39a842a1e66b7c2c6720) which means if you update pygls to 1.0.0 it breaks.

Otherwise if you don't update pygls to 1.0.0 jedi-language-server (and with it vs-code.extensions.ms-python.python) remains broken. I see three options:
1. Downgrade jedi-language-server to 0.39.0. 
2. Wait until cmake-language-server cuts a new release and then merge this PR.
3. Add a custom pygls-0.13.0 to cmake-language-server in nixpkgs inside this PR. Once they cut a new release you could remove this hack.

Option 1 and 2 are not exclusive. Regarding option 3) I don't know if it is considered good style in nixpkgs to add a custom python dependency.

**Comment by B4dM4n** [comment]
There is another option:

4. Update `cmake-language-server` to `master`. This makes it compatible with the new pygls version and also python-3.11.

This is what I did in my attempt to complete this PR and fix all `nixpkgs-review` failures: [master...B4dM4n:nixpkgs:pygls-update](https://github.com/NixOS/nixpkgs/compare/master...B4dM4n:nixpkgs:pygls-update)

I could't try the `cmake-language-server` yet, but all tests are passing.

I did test the `vscode-extensions.ms-python.python` extension with the update and it's working fine.

Until a new `cmake-language-server` release is made, I think we should prefer either option 3 or 4, to move forward and keep the latest python updates.

**Comment by doronbehar** [comment]
Option 4 sounds best to me. I'm sorry but I don't have time to work on this myself. You are free to open a PR yourself and ask to close this one.

**Comment by doronbehar** [comment]
Obselete.

**Pull request closed without merging**
