### PR TITLE
ctranslate2: 3.20.0 -> 3.21.0

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/OpenNMT/CTranslate2/blob/v3.21.0/CHANGELOG.md

## Description of changes

```
/nix/store/jwfc9vv8kryfs9bz4jzwn8f15qrhk2v5-python3.11-libretranslate-1.3.11
/nix/store/vlzs5ggapb8hkirlg11y5rlnjvmy72ls-wyoming-faster-whisper-1.0.2
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 266731` at dcfd1e86 run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages marked as broken and skipped:</summary>
  <ul>
    <li>libretranslate</li>
    <li>python310Packages.argos-translate-files</li>
    <li>python310Packages.argostranslate</li>
    <li>python310Packages.ctranslate2</li>
    <li>python310Packages.faster-whisper</li>
    <li>python310Packages.libretranslate</li>
    <li>python310Packages.translatehtml</li>
    <li>python311Packages.argos-translate-files</li>
    <li>python311Packages.argostranslate</li>
    <li>python311Packages.ctranslate2</li>
    <li>python311Packages.faster-whisper</li>
    <li>python311Packages.libretranslate</li>
    <li>python311Packages.translatehtml</li>
    <li>whisper-ctranslate2</li>
    <li>wyoming-faster-whisper</li>
  </ul>
</details>

**Review by misuzu — APPROVED** [review]
Tested by running libretranslate. jaxlib is broken on master

**Comment by mweinelt** [comment]
> jaxlib is broken on master

Bisected to https://github.com/NixOS/nixpkgs/pull/265041

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 266731` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>29 packages built:</summary>
  <ul>
    <li>ctranslate2</li>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>python310Packages.argos-translate-files</li>
    <li>python310Packages.argos-translate-files.dist</li>
    <li>python310Packages.argostranslate</li>
    <li>python310Packages.argostranslate.dist</li>
    <li>python310Packages.ctranslate2</li>
    <li>python310Packages.ctranslate2.dist</li>
    <li>python310Packages.faster-whisper</li>
    <li>python310Packages.faster-whisper.dist</li>
    <li>python310Packages.libretranslate</li>
    <li>python310Packages.libretranslate.dist</li>
    <li>python310Packages.translatehtml</li>
    <li>python310Packages.translatehtml.dist</li>
    <li>python311Packages.argos-translate-files</li>
    <li>python311Packages.argos-translate-files.dist</li>
    <li>python311Packages.argostranslate</li>
    <li>python311Packages.argostranslate.dist</li>
    <li>python311Packages.ctranslate2</li>
    <li>python311Packages.ctranslate2.dist</li>
    <li>python311Packages.faster-whisper</li>
    <li>python311Packages.faster-whisper.dist</li>
    <li>python311Packages.translatehtml</li>
    <li>python311Packages.translatehtml.dist</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
    <li>wyoming-faster-whisper</li>
    <li>wyoming-faster-whisper.dist</li>
  </ul>
</details>

**Pull request merged**
