### PR TITLE
matrix-appservice-irc: init at 0.3.1

### PR DESCRIPTION
**Pull request by Ralith**
###### Motivation for this change

Provides IRC bridging for the [Matrix](https://matrix.org/) chat network.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Is it really necessary to check in more than 10000 lines for a single package?

**Comment by Ralith** [comment]
I have very poor understanding of the npm packaging infrastructure, but this is certainly not the only package that includes a npm2nix generated file. I've experimented some but haven't been able to work out a way to get it to work with the default top-level one. If there's a better way, I'd love to hear about it.

**Comment by joachifm** [comment]
If nodejs stuff requires 10,000+ lines *per* package we seriously need to reconsider how things are done on that front.

**Comment by Ralith** [comment]
It looks like the NPM/nodejs infrastructure is being reworked in #16886 although recent activity is limited. Should this be blocked by it?

**Comment by joachifm** [comment]
> Should this be blocked by it?

As far as I'm concerned, yes. I'm not checking in 10,000+ lines of code for a single package. Somebody else might do it, however, my opinion is by no means authoritative.

**Comment by fpletz** [comment]
No progress for over a year. We will not merge this in the current form but feel free to reopen if things have improved.

**Pull request closed without merging**
