### PR TITLE
tartube: replace youtube-dl with yt-dlp

### LINKED ISSUE #328418: Build failure: tartube
### Steps To Reproduce

1. build tartube

### Build log
<details>

```console
linus@yoga:~/home/ > nix build nixpkgs#tartube
error:
       … while evaluating the attribute 'drvPath'

         at /nix/store/iqxdbcjlg9wx8gdc8bdhy9nsd5imcbjp-source/lib/customisation.nix:365:7:

          364|     in commonAttrs // {
          365|       drvPath = assert condition; drv.drvPath;
             |       ^
          366|       outPath = assert condition; drv.outPath;

       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘python3.12-youtube-dl-2021.12.17’ in /nix/store/iqxdbcjlg9wx8gdc8bdhy9nsd5imcbjp-source/pkgs/tools/misc/youtube-dl/default.nix:84 is marked as insecure, refusing to evaluate.


       Known issues:
        - youtube-dl is unmaintained, migrate to yt-dlp, if possible

       You can install it anyway by allowing this package, using the
       following methods:

       a) To temporarily allow all insecure packages, you can use an environment
          variable for a single invocation of the nix tools:

            $ export NIXPKGS_ALLOW_INSECURE=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) for `nixos-rebuild` you can add ‘python3.12-youtube-dl-2021.12.17’ to
          `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
          like so:

            {
              nixpkgs.config.permittedInsecurePackages = [
                "python3.12-youtube-dl-2021.12.17"
              ];
            }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          ‘python3.12-youtube-dl-2021.12.17’ to `permittedInsecurePackages` in
          ~/.config/nixpkgs/config.nix, like so:

            {
              permittedInsecurePackages = [
                "python3.12-youtube-dl-2021.12.17"
              ];
            }
```
</details>

### Additional context

`tartube` and `tartube-yt-dlp` both depend on `youtube-dl` (because they use the same derivation), causing them to fail to build, as this package is now marked as insecure (see #325371).

### Notify maintainers

@mkg20001 @luc65r 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
linus@yoga:~/home/ > nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.39, NixOS, 24.11 (Vicuna), 24.11.20240714.693bc46`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/iqxdbcjlg9wx8gdc8bdhy9nsd5imcbjp-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by libewa**
fixes NixOS#328418

## Description of changes

Replace `youtube-dl` with `yt-dlp`, to remove a security vulnerability error.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by eclairevoyant — COMMENTED** [review]
We should then move `tartube-yt-dlp` to `aliases.nix` as it's now redundant. In any case its override must be changed as this breaks it.

**Comment by kirillrdy** [comment]
@libewa greetings !

as per @eclairevoyant comment, there is an attribute `tartube-yt-dlp` in all-packages.nix that now breaks because of this change.

please migrate `tartube-yt-dlp` to pkgs/top-level/aliases.nix

**Comment by averyanalex** [comment]
```shell
nix run github:nixos/nixpkgs/pull/328432/head#tartube
```

```
error: Package ‘python3.12-youtube-dl-2021.12.17’ in /nix/store/d14assbszmy2m136pbxvfqn92mz6azp5-source/pkgs/tools/misc/youtube-dl/default.nix:84 is marked as insecure, refusing to evaluate.```

In fact it doesn't fix #328418, because doesn't really removes youtube-dl from deps.

**Comment by libewa** [comment]
`tartube-yt-dlp` works now (it didn't work for me last time i updated), so this is unneccessary (maybe someone can add a warning to `tartube` to use `tartube-yt-dlp` instead, or add an alias)

**Pull request closed without merging**
