### PR TITLE
sbcl: 1.5.0 -> 1.5.1, tested on nixos x86_64

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ryantm** [comment]
@GrahamcOfBorg build sbcl

**Comment by ryantm** [comment]
Darwin is passing on Hydra, so someone should investigate the possible Darwin regression.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build maxima lispPackages.iolib lispPackages.stumpwm

**Comment by 7c6f434c** [comment]
The failure might be related to the fact that our bootstrap SBCL is older both than the Linux bootstrap and than the latest available upstream binary.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build maxima lispPackages.iolib lispPackages.stumpwm

**Comment by 7c6f434c** [comment]
I wonder if we should drop `sb-concurrency` on `aarch64`…

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build maxima lispPackages.iolib lispPackages.stumpwm

**Pull request merged**
