### PR TITLE
Create binutils 2.38 holdback set of releases

### PR DESCRIPTION
**Pull request by trofi**
###### Description of changes

`binutils-2.39` will be a disruptive release: https://github.com/NixOS/nixpkgs/pull/185297.
It changes disassembly API and broke `perf` for all old linux releases. We will need to hold
back old release until all dependencies are ported to 2.39.

This change introduces held back release of `libbfd` and `libopcodes`. It's a copy of current
`binutils` release.

The plan is to pin all to-be-broken packages to this 2.38 release.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Example use case is `bpftools`:

build failure:

```
error: builder for '/nix/store/vgxg4zvgcifm80q1zmiamwkkb45fjf4m-bpftools-5.19.2.drv' failed with exit code 2;
       last 10 log lines:
       >       |             ^~~~~~~~~~~~~~~~~~~~~
       > jit_disasm.c:105:17: error: too few arguments to function 'init_disassemble_info'
       >   105 |                 init_disassemble_info(&info, stdout,
       >       |                 ^~~~~~~~~~~~~~~~~~~~~
```

Example fix:

```diff
--- a/pkgs/os-specific/linux/bpftools/default.nix
+++ b/pkgs/os-specific/linux/bpftools/default.nix
@@ -1,5 +1,5 @@
 { lib, stdenv
-, libopcodes, libbfd, elfutils, readline
+, libopcodes_2_38, libbfd_2_38, elfutils, readline
 , linuxPackages_latest, zlib
 , python3, bison, flex
 }:
@@ -9,7 +9,7 @@ stdenv.mkDerivation {
   inherit (linuxPackages_latest.kernel) version src;

   nativeBuildInputs = [ python3 bison flex ];
-  buildInputs = [ libopcodes libbfd elfutils zlib readline ];
+  buildInputs = [ libopcodes_2_38 libbfd_2_38 elfutils zlib readline ];

   preConfigure = ''
     patchShebangs scripts/bpf_doc.py
```

**Comment by trofi** [comment]
Needs headers fixes

**Comment by trofi** [comment]
Tested this change on `binutils-2.39` branch by pinning `linuxPackages.perf` and `bpftools` to old binutils libraries. Both built successfully.

Ready for review.

**Review by lovesegfault — APPROVED** [review]
LGTM, thanks for all the work trofi

**Pull request merged**
