### PR TITLE
pythonPackages.pyqt5: upgrade and solve qml issue

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

This PR upgrades `.pyqt5` and `.pyqtwebengine` and fixes their build. During build-time many Qt modules were not detected and thus not included in the build. Apparently they also need to be added to `nativeBuildInputs`. I suppose this is because of qmake?

Anyway, both packages work fine when using with `python3.withPackages`. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
Qutebrowser now runs without the error. However, there is a regression in PyQt5.sip for Python 2 it seems.

**Comment by FRidh** [comment]
I can imagine we can have collisions with sip as well because for each variant we create `sipconfig.py` at the same location.

**Comment by FRidh** [comment]
qgis does not build yet, but I leave that for someone else (or at least another day).

**Comment by FRidh** [comment]
@grahamcofborg build picard qutebrowser anki python3Packages.spyder

**Comment by petabyteboy** [comment]
Great news that this is finally figured out :tada: 
I built and ran qutebrowser successfully, so that's good
I am wondering if adding the target dependencies to nativeBuildInputs really is the right thing, it detected qml just fine before, so what broke it?

**Comment by FRidh** [comment]
> I am wondering if adding the target dependencies to nativeBuildInputs really is the right thing, it detected qml just fine before, so what broke it?

Yes, I don't like it either. Maybe `strictDeps = true;`? I have not checked it.

**Pull request merged**
