### PR TITLE
steam/steam-fhs: add gnome2.pango

### LINKED ISSUE #157614: [Steam] Dota fails to launch after Jan 31 update
### Describe the bug
When launching dota from steam, it errors out with an error about `libpangoft`.

Dota was working yesterday. It broke today (Jan 31) after an update. I believe the update switched the game to use the soldier runtime (which runs the game inside a container). Before, I believe dota was running uncontainerized.

I filed a bug report on the dota tracker: https://github.com/ValveSoftware/Dota-2/issues/2018

### Steps To Reproduce
1. Launch steam
2. Launch dota

### Expected behavior
The game to launch.

### Screenshots
screenshot

### Additional context
Steam installed through `programs.steam.enable = true;`.

### Notify maintainers
@jagajaga @jonringer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix > nix-info -m
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:9:

            1| (import <nixpkgs> {}).stdenv.hostPlatform.system
             |         ^
 - system: `0`
 - host os: `Linux 5.10.93, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `""`
 - channels(owner): `""`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:1:

            1| <nixpkgs>
             | ^
 - nixpkgs: `0`
```

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes #157614

Fix dota, which needs libpangoft2-1.0.so
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@tgharib can you test with:
```
NIX_PATH=nixpkgs=https://github.com/jonringer/nixpkgs/archive/refs/heads/fix-dota.tar.gz nix-shell -p steam --run steam
```

**Comment by tgharib** [comment]
@jonringer Now I get a different error:

image

**Comment by jonringer** [comment]
Might be related to https://github.com/NixOS/nixpkgs/pull/130984

**Comment by gardspirito** [comment]
Doesn't seem to work for me... Also, I don't know how FHS works, but isn't `gnome.pango2` supposed to be placed in `multiPkgs` and not in `targetPkgs`?

Anyway, now it seems to fail with missing `librendersystemgl.so`:
```
Setting breakpad minidump AppID = 373300
 failed to dlopen "/data/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemgl.so" error=libudev.so.0: cannot open shared object file: No such file or directory
 failed to dlopen "librendersystemgl.so" error=libudev.so.0: cannot open shared object file: No such file or directory
```

**Comment by jonringer** [comment]
> Doesn't seem to work for me... Also, I don't know how FHS works, but isn't `gnome.pango2` supposed to be placed in `multiPkgs` and not in `targetPkgs`?
> 
> Anyway, now it seems to fail with missing `librendersystemgl.so`:
> 
> ```
> Setting breakpad minidump AppID = 373300
>  failed to dlopen "/data/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemgl.so" error=libudev.so.0: cannot open shared object file: No such file or directory
>  failed to dlopen "librendersystemgl.so" error=libudev.so.0: cannot open shared object file: No such file or directory
> ```

Multipkgs is if you want it built for both 32bit and 64bit version. But it's also annoying in that now you need to build the 32bit version. For most games this shouldn't be an issue

**Comment by gardspirito** [comment]
Sorry for my stupidity, but why is `pango` placed in `targetPkgs` and not in `multiPkgs`?

**Comment by gardspirito** [comment]
> Might be related to #130984

Applying #130984 patch alone does not resolve the issue. `libudev` is still missing.

**Comment by jonringer** [comment]
from the discussion in https://github.com/ValveSoftware/Dota-2/issues/2018#issuecomment-1028371648, this doesn't seem to be the right path.

**Pull request closed without merging**
