### PR TITLE
python3Packages.matrix-nio: permit insecure Olm during check phase

### PR DESCRIPTION
**Pull request by AndrewKvalheim**
## Description of changes

Olm has a [known vulnerability](https://github.com/NixOS/nixpkgs/pull/334638) but is only an [optional dependency](https://github.com/matrix-nio/matrix-nio/blob/0.24.0/pyproject.toml#L37) of nio, so in theory nio should by default be unaffected. nio’s tests, however, cover its full suite of extra features, so Olm is still evaluated as a dependency of the check phase. Since the check phase doesn’t process user data or access the network this vulnerability isn’t relevant and can be ignored, allowing nio to evaluate and ultimately be run without Olm.

I’m not confident in this implementation. Is there a tidier way to do it? Should the permission be narrowed to specifically this vulnerability? I haven’t found any precedent for this and wonder if something like a `checkPhasePermittedInsecurePackages` would be warranted.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `git cherry-pick NixOS/#336651 && nixpkgs-review rev HEAD`.
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Ah, sorry for dropping the ball on this. I agree that we should solve this. We should also backport the fix to 24.05 before I merge https://github.com/NixOS/nixpkgs/pull/335189.

We could also just do one of these:

* Re‐enumerate the optional dependencies again with the override for `olm`, since there aren’t that many.
* Define `e2eDeps = python-olm': [ atomicwrites … python-olm' … ]` and use it appropriately for both values.
* Skip all of this and don’t make Hydra build libolm again and just disable the libolm‐requiring tests since after all that’s not exactly a “first‐class” supported code path now.

I think I’d prefer any one of them, since they’re simpler than the construction here.

**Comment by emilazy** [comment]
Can we handle https://github.com/NixOS/nixpkgs/issues/336052 here too since it’s the exact same issue?

**Comment by emilazy** [comment]
Also I think instead of `olm = lib.findFirst (p: p.pname == "olm") null pythonPackage.buildInputs` it should be fine to just say `pkgs.olm`? I guess that would make overlaying `python-olm` with `python-olm.override { olm = …; }` weird, but if we’re worried about that case we should just add, say, `passthru = { inherit olm; }` to `python-olm`.

Anyway I lean toward just disabling the checks.

**Comment by AndrewKvalheim** [comment]
Thanks, how’s that for a simpler implementation? Please also feel free to just edit yourself if that’s easier.

**Comment by SuperSandro2000** [comment]
Can we please stop such hick and just ignore the effected tests?

**Comment by AndrewKvalheim** [comment]
[Yes](https://github.com/NixOS/nixpkgs/pull/336901).

**Pull request closed without merging**
