### PR TITLE
add tonelib-{jam,zoom}

### PR DESCRIPTION
**Pull request by dan4ik605743**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dan4ik605743** [comment]
Excellent

**Comment by dan4ik605743** [comment]
And the question. When can I install these packages? Now they are in nix search. And install not found.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 127919` at 2262b3fd run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>tonelib-jam</li>
    <li>tonelib-zoom</li>
  </ul>
</details>

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Please follow the contributing guide when creating and naming your commits.

**Comment by dan4ik605743** [comment]
Okay, I'm sorry.

**Comment by dan4ik605743** [comment]
Why don't you push, my packages. What can I fix?

**Comment by dan4ik605743** [comment]
@SuperSandro2000 ?

**Comment by SuperSandro2000** [comment]
> And the question. When can I install these packages? Now they are in nix search. And install not found.

You need to wait for the channel to advance but you need to install them beforehand to make sure they work.

> Why don't you push, my packages??

Because your commits do not follow the contributing guide.

**Comment by dan4ik605743** [comment]
@SuperSandro2000 Well, as they will be available in the channel, I will definitely install them. It turns out that I can delete my changes and re-run, good. Then the question is, can you push 2 packages at once with one commit?

tonelib- {jam, zoom}: new nixpkgs

Is it okay?

**Comment by SuperSandro2000** [comment]
> Then the question is, can you push 2 packages at once with one commit?

You shouldn't but you can do one commit for each package in this PR. It is not a problem if a PR includes multiple commits.

**Comment by dan4ik605743** [comment]
Ok, I'll make 2 commits for 2 packages. In one PR. package1: new nixpkg
package2: new nixpkg

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Ok, I'll make 2 commits for 2 packages. In one PR. package1: new nixpkg
> package2: new nixpkg

No.

tonelib-jam: init at 4.6.6
tonelib-zoom: init at 4.3.1

**Comment by dan4ik605743** [comment]
> > @SuperSandro2000 Ok, I'll make 2 commits for 2 packages. In one PR. package1: new nixpkg
> > package2: new nixpkg
> 
> No.
> 
> tonelib-jam: init at 4.6.6
> tonelib-zoom: init at 4.3.1

OK thank you very much. I'll know

**Comment by dan4ik605743** [comment]
I'll fix everything.

**Pull request closed without merging**
