### PR TITLE
redmine: 5.1.2 -> 5.1.3

### PR DESCRIPTION
**Pull request by felixsinger**
## Description of changes

Updates Rails as well, which fixes two CVEs. See https://rubyonrails.org/2024/6/4/Rails-Versions-6-1-7-8-7-0-8-4-and-7-1-3-4-have-been-released.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by felixsinger** [comment]
@GrahamcOfBorg test redmine

**Comment by felixsinger** [comment]
@GrahamcOfBorg test redmine

**Comment by felixsinger** [comment]
@GrahamcOfBorg test redmine

**Comment by felixsinger** [comment]
Can anyone help out with this issue?

```
machine # [   13.244171] redmine-pre-start[994]: /nix/store/82da2n2gnjra98a9h0mwml6lba943yzk-bundler-2.5.11/lib/ruby/gems/3.1.0/gems/bundler-2.5.11/lib/bundler/definition.rb:594:in `materialize': Could not find nokogiri-1.15.6-x86_64-linux, sqlite3-1.6.9-x86_64-linux, ffi-1.17.0-x86_64-linux-gnu in locally installed gems (Bundler::GemNotFound)
```

**Comment by felixsinger** [comment]
@GrahamcOfBorg test redmine

**Comment by aanderse** [comment]
hey @felixsinger :wave:

sorry i didn't mean to ignore you - i have been swamped with various things and then got sick for a few days
are you making any progress?

**Comment by felixsinger** [comment]
> hey @felixsinger 👋
> 
> sorry i didn't mean to ignore you - i have been swamped with various things and then got sick for a few days are you making any progress?

Yo!

No worries. Yeah, it seems I've got it just working. A couple platforms need to be removed. See the update.sh. :)

I'm planning to add more information to the commit message once the CI finished verifying.

By the way, since this is includes a security fix, should this PR have the "1. severity: security" label? I'm not very familiar with the labels.

**Comment by aanderse** [comment]
awesome

yes, security label is always helpful, and i see you already marked for backport :heavy_check_mark:

looking good, thanks

is any additional detail needed in the commit message?

**Comment by felixsinger** [comment]
> is any additional detail needed in the commit message?

Hmm... It's actually not needed. I'm just picky about my own commit messages :)

Anyway, if you think this is ready then let's get it in as soon as the CI is ready.

**Comment by felixsinger** [comment]
Look like most important tests passed. Darwin is still pending, but I think we can submit the patch.

**Pull request merged**
