### PR TITLE
lib/types: dont warn loaOf for home-manager namespace

### PR DESCRIPTION
**Pull request by worldofpeace**
This option namespace is not a part of NixOS
so we shouldn't provide this warning for it.

###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/77501 https://github.com/NixOS/nixpkgs/pull/77501#discussion_r365531223.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
I understand but I don't quite agree on this. Sure, home-manager is not a NixOS project, so it should be their responsibility to handle this. However it's a popular application among NixOS users and, I say, for the sake of UX we should provide clearer errors (especially if home-manager can't implement this, or can it?).

**Comment by jtojnar** [comment]
They can create their own `loaOf` fork something like this:

```nix
elemType: types.loaOf elemType // {
  merge = /* copy of our merge with attrNames replaced */;
}
```

However, I wonder if we should expose the merge function parametrizable by the `attrNames`, so that they could just do:


```nix
elemType: let
  origType = types.loaOf elemType;
in origType // {
  merge = origType._mergeWithAttrNames [
    /* home-manager attrNames */
  ];
}
```

**Comment by worldofpeace** [comment]
> I understand but I don't quite agree on this. Sure, home-manager is not a NixOS project, so it should be their responsibility to handle this. However it's a popular application among NixOS users and, I say, for the sake of UX we should provide clearer errors (especially if home-manager can't implement this, or can it?).

We should, as @jtojnar suggests, allow home-manager to utilize NixOS `lib`. it's reasonable to allow it to be extensible for other module systems that exist outside NixOS. It just shouldn't be specific to one single project.

**Comment by jtojnar** [comment]
Do not have time to test it right now but the following might be sufficient:

```patch
--- a/lib/types.nix
+++ b/lib/types.nix
@@ -327,7 +327,37 @@ rec {
     };
 
     # List or attribute set of ...
-    loaOf = elemType:
+    loaOf = rec {
+      __functor = elemType: _mergeWithNameAttrs elemType __nameAttrs;
+      _anyString = placeholder "name";
+      __nameAttrs = [
+        { path = [ "environment" "etc" ];
+          name = "target";
+        }
+        { path = [ "containers" _anyString "bindMounts" ];
+          name = "mountPoint";
+        }
+        { path = [ "programs" "ssh" "knownHosts" ];
+          # hostNames is actually a list so we would need to handle it only when singleton
+          name = "hostNames";
+        }
+        { path = [ "fileSystems" ];
+          name = "mountPoint";
+        }
+        { path = [ "boot" "specialFileSystems" ];
+          name = "mountPoint";
+        }
+        { path = [ "services" "znapzend" "zetup" ];
+          name = "dataset";
+        }
+        { path = [ "services" "znapzend" "zetup" _anyString "destinations" ];
+          name = "label";
+        }
+        { path = [ "services" "geoclue2" "appConfig" ];
+          name = "desktopID";
+        }
+      ];
+      _mergeWithNameAttrs = elemType: nameAttrs:
       let
         convertAllLists = loc: defs:
           let
@@ -340,48 +370,8 @@ rec {
             let
               padWidth = stringLength (toString (length def.value));
               unnamed = i: unnamedPrefix + fixedWidthNumber padWidth i;
-              anyString = placeholder "name";
-              nameAttrs = [
-                { path = [ "environment" "etc" ];
-                  name = "target";
-                }
-                { path = [ "containers" anyString "bindMounts" ];
-                  name = "mountPoint";
-                }
-                { path = [ "programs" "ssh" "knownHosts" ];
-                  # hostNames is actually a list so we would need to handle it only when singleton
-                  name = "hostNames";
-                }
-                { path = [ "fileSystems" ];
-                  name = "mountPoint";
-                }
-                { path = [ "boot" "specialFileSystems" ];
-                  name = "mountPoint";
-                }
-                { path = [ "services" "znapzend" "zetup" ];
-                  name = "dataset";
-                }
-                { path = [ "services" "znapzend" "zetup" anyString "destinations" ];
-                  name = "label";
-                }
-                { path = [ "services" "geoclue2" "appConfig" ];
-                  name = "desktopID";
-                }
-                { path = [ "home-manager" "users" anyString "programs" "ssh" "matchBlocks" ];
-                  name = "host"; # https://github.com/rycee/home-manager/blob/e8dbc3561373b68d12decb3c0d7c1ba245f138f7/modules/programs/ssh.nix#L265
-                }
-                { path = [ "home-manager" "users" anyString "home" "file" ];
-                  name = "target"; # https://github.com/rycee/home-manager/blob/0e9b7aab3c6c27bf020402e0e2ef20b65c040552/modules/files.nix#L33
-                }
-                { path = [ "home-manager" "users" anyString "xdg" "configFile" ];
-                  name = "target"; # https://github.com/rycee/home-manager/blob/54de0e1d79a1370e57a8f23bef89f99f9b92ab67/modules/misc/xdg.nix#L41
-                }
-                { path = [ "home-manager" "users" anyString "xdg" "dataFile" ];
-                  name = "target"; # https://github.com/rycee/home-manager/blob/54de0e1d79a1370e57a8f23bef89f99f9b92ab67/modules/misc/xdg.nix#L58
-                }
-              ];
               matched = let
-                equals = a: b: b == anyString || a == b;
+                equals = a: b: b == _anyString || a == b;
                 fallback = { name = "name"; };
               in findFirst ({ path, ... }: all (v: v == true) (zipListsWith equals loc path)) fallback nameAttrs;
               nameAttr = matched.name;

```

**Comment by misuzu** [comment]
There is already a fix for this in home-manager: https://github.com/rycee/home-manager/pull/984

**Comment by jtojnar** [comment]
@misuzu that only fixes the warning producing definitions inside home-manager modules. If user sets any of those options in their `home.nix` to list, they will still see the warning.

@rycee will need to decide which of these variants they want:
* improving the warning using `_mergeWithAttrNames` exposed from `lib.types.loaOf` as described above
* improving the warning by overriding the whole merge method
* ignoring the warning imprecision, letting users figure it out for themselves

**Comment by rycee** [comment]
All internal use of the list form of `home.file` should be removed from HM now. I'm not particularly concerned about the warning imprecision and instead rely on people carefully reading the release notes. I'll reconsider if I get many support requests 🙂

For the SSH hosts option I will have to ponder a bit. Most likely I'll try to figure out some nice way to introduce a `dagOf` option type since that is semantically the best for the option and it could possibly be made to be compatible with values of the attribute set type.

**Review by jtojnar — APPROVED** [review]

**Comment by jtojnar** [comment]
Well, `dagOf` could still be sub-type of `attrsOf`:

```nix
{
  a = { arrows = [ "b" "c" "d" "e" ]; };
  b = { arrows = [ "c" ]; };
  c = { arrows = [ "d" "e" ]; };
  d = { arrows = [ "e" ]; };
  e = { arrows = [ ]; };
}
```

[DAG](https://commons.wikimedia.org/wiki/File:Tred-G.svg)

**Pull request merged**
