### PR TITLE
19.09: Nodejs backport

### PR DESCRIPTION
**Pull request by wmertens**
###### Motivation for this change

Update NodeJS versions to upstream stable, cherrypicking the commits from master

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wmertens** [comment]
@grahamcofborg build nodejs-10_x nodejs-12_x

**Comment by wmertens** [comment]
@FRidh thoughts on merging this? Looks like the build is too large for ofborg…

**Comment by Ma27** [comment]
Had those tabs open for a while now, will take care of this :)

**Comment by marsam** [comment]
I think nodejs-10_x can safely backported, however nodejs-12_x needs https://github.com/NixOS/nixpkgs/pull/68748 and probably needs to go to `staging-19.09`

**Comment by wmertens** [comment]
@marsam I added that patch and changed the base

**Review by Ma27 — APPROVED** [review]
Tested the changes locally :+1:

**Pull request merged**
