### PR TITLE
A (rough but working) way to restart systemd to activate config changes.

### PR DESCRIPTION
**Pull request by ctheune**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ctheune** [comment]
SystemD is not restarted and thus changed configuration is not applied upon
changes to configuration like this:

  systemd.extraConfig = ''
    RuntimeWatchdogSec=60
  '';

This commit implements a very simple and rough way of doing so. I'm open to
improvements, like: should we pay attention to more config files like the
journal? Should we refactor this in a way that predicts the reload instead of
looking at the result of the activation?

Unfortunately my Perl fu is very limited, so I'm open to suggestions but might
not be able to implement them ...

**Comment by ctheune** [comment]
Thanks, @GrahamcOfBorg ... anything I can do to move this forward?

**Comment by ctheune** [comment]
Well, it's been in place over here for a while. I guess I can even figure out a test (although I'm a bit short on time currently) if needed. We could monitor more files, etc. However, that change in itself seems fine so you could maybe even just merge that ... more improvements are always possible ...

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by ctheune** [comment]
Sorry, this got lost in the flood of my open ends. I might be able to convince @dpausp to pick this up ... :)

**Comment by wmertens** [comment]
I like it, it's simple and straightforward. However, as long as we don't have a CAS store, it will restart systemd even if the file contents are the same. 

@ctheune, does it restart a lot, and does it ever cause trouble?

**Comment by ctheune** [comment]
Hah, that's an old one. I just checked and we didn't use this patch in production as I wanted to get the upstream discussion done first, so I can't tell whether this causes continuous superfluous restarts. However, daemon-reexec isn't something that usually is a problem and this really only depends on how often you run activate on your system. We even usually run daemon-reexec gratuitously if systemd chokes on itself ... ;)

**Comment by wmertens** [comment]
Ok, in that case I'm A-OK with merging this. Could you perhaps rebase or at least resolve the conflicts?

**Comment by ctheune** [comment]
I can try a rebase, will take a while. Was on holiday the last weeks and just came back.

**Comment by ctheune** [comment]
@dpausp Is this something we want to follow up on? Do we still maintian this in our overlay/fork?

**Comment by wmertens** [comment]
this is still a problem...

**Comment by dasJ** [comment]
I did an alternative implementation in #149342

**Comment by flokli** [comment]
Let's close this in favor of #149342.

**Pull request closed without merging**
