### PR TITLE
fusuma: enable "essential" plugins

### PR DESCRIPTION
**Pull request by ebardie**
[This commit changes the gem files, but no changes to `default.nix`.]

A lot of useful Fusuma functionality is split out in to plugins, which means that this functionality isn't currently available on NixOS.

This pull request enable specifically the following plugins:

  * [fusuma-plugin-appmatcher](https://github.com/iberianpig/fusuma-plugin-appmatcher)
  * [fusuma-plugin-keypress](https://github.com/iberianpig/fusuma-plugin-keypress)
  * [fusuma-plugin-sendkey](https://github.com/iberianpig/fusuma-plugin-sendkey)
  * [fusuma-plugin-tap](https://github.com/iberianpig/fusuma-plugin-tap)
  * [fusuma-plugin-wmctrl](https://github.com/iberianpig/fusuma-plugin-wmctrl)

I've not enabled the other plugins available on rubygems for the following reasons:

  * [fusuma-plugin-remap](https://github.com/iberianpig/fusuma-plugin-remap) : seems niche functionality and requires [udev configuration](https://github.com/iberianpig/fusuma-plugin-remap#set-up-udev-rules) to create a virtual input device.

  * [fusuma-plugin-thumbsense](https://github.com/iberianpig/fusuma-plugin-thumbsense) : again, niche (?) and pulls in remap (see above).

  * [fusuma-plugin-touchscreen](https://github.com/Phaengris/fusuma-plugin-touchscreen) : I've no way of testing.  Note: enabling didn't appear to cause any problems.

Ideally all of the plugin implemented functionality would be made available as separate pkgs, but that would require patching Fusuma to search outside of the Gem directory, which would require more than my pretty much zero Ruby knowledge.

Enabling this subset of plugins for what appears to be widely useful functionality seems a good option.

## Description of changes

See the various plugin links above.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ebardie** [comment]
I can't add suggested reviewers to the PR, even after reverting to Draft status.

Adding the maintainers from `default.nix` here: @jfrankenau @nicknovitski @Br1ght0ne

**Comment by Br1ght0ne** [comment]
Result of `nixpkgs-review pr 250149` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Review by Br1ght0ne — APPROVED** [review]

**Review by nicknovitski — APPROVED** [review]

**Comment by Br1ght0ne** [comment]
`fusuma` was recently bumped to `3.1.0` in https://github.com/NixOS/nixpkgs/pull/253277, so this PR needs to be updated to use/test these plugins with `3.1.0`.

**Comment by ebardie** [comment]
Thanks @Br1ght0ne 

Any ideas on how to get this PR progressed?

**Review by nicknovitski — APPROVED** [review]

**Comment by ebardie** [comment]
@wegank Given that you merged a recent Fusuma PR, would you be able to review/merge this one too please?  Thanks.

**Pull request merged**
