### PR TITLE
cmake: 3.25.3 -> 3.26.2

### PR DESCRIPTION
**Pull request by hesiod**
###### Description of changes

Update CMake to 3.26.2:
* https://discourse.cmake.org/t/cmake-3-26-2-available-for-download/7796
* https://cmake.org/cmake/help/latest/release/3.26.html

Building `cmakeMinimal` on top of Nixpkgs master was successful.

I'm also adding myself to the maintainer list in this PR.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hesiod** [comment]
@ofborg build cmakeMinimal
(Building `cmake` fails on Darwin due to timeout while building LLVM, but `cmakeMinimal` should work)

**Comment by AndersonTorres** [comment]
Why did you call the Discourse channel?

**Comment by AndersonTorres** [comment]
There are not too much people out there that have suitable machines to test Darwin builds.
This is the main reason people are cautious to commit this PR, I suppose.

Also this tool generates a lot of potential rebuilds, and not everyone has powerful machines to test such rebuilds. (Indeed I believe no one truly has.)

If you are using Discourse to call people, at least add this context (especially the "we need Darwin testers" part), or else this link will only add noise.

**Comment by hesiod** [comment]
Thanks for the explanation! I didn't want to add lengthy explanations to the Discourse post since people seldom add such comments to their posts there, and I didn't want to add noise to the thread. If explanations/comments in posts are appreciated I'll be happy to add them in the future.

> There are not too much people out there that have suitable machines to test Darwin builds. This is the main reason people are cautious to commit this PR, I suppose.

I didn't see this as a major blocker to this particular PR as this has occurred in the past (as mentioned in your comment here: https://github.com/NixOS/nixpkgs/pull/206799#issuecomment-1364585359) and it will occur in the future again since nothing about CMake updates changes the LLVM timeout. If the LLVM timeout is reason to delay CMake updates for some time, I think the situation should be improved in the future.
If it would help, maybe I can look into somehow circumventing the timeout and allowing to build at least `cmakeMinimal` on Darwin, e.g. by somehow using another LLVM version. I didn't look into this any further previously as I'm assuming that smaller PRs to staging are preferred over larger PRs.

> Also this tool generates a lot of potential rebuilds, and not everyone has powerful machines to test such rebuilds. (Indeed I believe no one truly has.)

I mean, that's why staging exists, right?

**Comment by hesiod** [comment]
Converted to draft while I update to `3.26.3` and try to improve the Darwin situation

**Comment by hesiod** [comment]
@ofborg build cmakeMinimalGcc

**Comment by AndersonTorres** [comment]
The PR you linked as example was merged after two annoying and slow months. You are comparing this to a single week...

Transitions to patch versions (semver semantics) are less traumatic, on the other hand.

**Comment by mweinelt** [comment]
The latest onnxruntime package requires cmake>=3.26 to configure, so I would appreciate if this could go forward.

**Comment by AndersonTorres** [comment]
Wow! I thougth it was done already!

**Comment by mweinelt** [comment]
For one there is an experimental commit on top right now, not sure what to make of that. And then we have 3.26.4 already upstream!

**Comment by AndersonTorres** [comment]
I will open a new PR myself.

**Comment by cbourjau** [comment]
@mweinelt It appears that `onnxruntime` can be build with older versions of `cmake`, too. I updated #226734 accordingly.

**Pull request closed without merging**
