### PR TITLE
darwin: fixed gnulib in libpipeline and man-db

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

Partial fixes for #15849
These changes fix gnulib for both libpipeline and man-db, however there is still an issue with the `man-db` package:

```
Undefined symbols for architecture x86_64:
  "_database", referenced from:
      _gripe_corrupt_data in libmandb_la-db_lookup.o
      _gripe_replace_key in libmandb_la-db_lookup.o
      _split_content in libmandb_la-db_lookup.o
      _dblookup in libmandb_la-db_lookup.o
      _dblookup_pattern in libmandb_la-db_lookup.o
      _dbver_rd in libmandb_la-db_ver.o
      _dbver_wr in libmandb_la-db_ver.o
      ...
```
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] OS X
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by copumpkin** [comment]
Are the two .patch files identical? Perhaps they could live in the gnulib folder? Otherwise this seems good.

**Comment by LnL7** [comment]
@copumpkin looks like the missing _database symbol is only is only used in `libdb/db_lookup.c` and `libdb/db_ver.c` for debugging purposes.
I guess it might be ok just to replace those with an empty string.

**Comment by vcunat** [comment]
Ping? The issue https://github.com/NixOS/nixpkgs/issues/15849 is marked as *blocker*...

**Comment by LnL7** [comment]
The man package works because it was switched back to `man-old` on darwin. I have not looked at this further, but like I do have a possible fix like I said before.

**Comment by Ekleog** [comment]
(triage) @LnL7 Is this still relevant? I feel like it should be closed due to old age, but without any kind of certainty.

**Comment by LnL7** [comment]
Yeah, this is pretty old. I should try it again.

**Pull request closed without merging**
