### PR TITLE
xTB ecosystem: build with meson, fix (cross) compilation

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
Checked generated pkg-config files, and building static libraries.

**Review by sheepforce — COMMENTED** [review]
Thank you very much, I've also already thought myself about switching everything over to meson, as the cmake builds cause a lot of problems in other packages, e.g. 

  * https://github.com/grimme-lab/xtb/issues/981
  * https://github.com/pprcht/gfnff/issues/1
  * https://github.com/pprcht/gfn0/issues/1
  * https://github.com/grimme-lab/CPCM-X/issues/31
  * https://github.com/grimme-lab/numsa/issues/11

So all the stuff in the xTB ecosystem, the main reason why I've added these packages.  If we switch over to Meson we should probably have all packages migrated at once. Thus, in this ecosystem, the remaining packages would be

  * mctc-lib
  * multicharge
  * mstore

(and some more, that haven't yet made it to nixpkgs but only to NixOS-QChem). Could you change those remaining three over to meson+ninja, too? :innocent:

**Comment by NickCao** [comment]
And another one, dftd4.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 299273` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>dftd4</li>
    <li>dftd4.dev</li>
    <li>mctc-lib</li>
    <li>mctc-lib.dev</li>
    <li>mstore</li>
    <li>mstore.dev</li>
    <li>multicharge</li>
    <li>multicharge.dev</li>
    <li>python311Packages.pyscf</li>
    <li>python311Packages.pyscf.dist</li>
    <li>python311Packages.simple-dftd3</li>
    <li>python311Packages.simple-dftd3.dist</li>
    <li>python311Packages.tblite</li>
    <li>python312Packages.pyscf</li>
    <li>python312Packages.pyscf.dist</li>
    <li>python312Packages.simple-dftd3</li>
    <li>python312Packages.simple-dftd3.dist</li>
    <li>python312Packages.tblite</li>
    <li>simple-dftd3</li>
    <li>simple-dftd3.dev</li>
    <li>tblite</li>
    <li>tblite.dev</li>
    <li>test-drive</li>
    <li>toml-f</li>
    <li>toml-f.dev</li>
  </ul>
</details>

**Review by sheepforce — APPROVED** [review]
Thank you very much, LGTM :sheep: :blush:

**Pull request merged**
