### PR TITLE
perldevel: 5.30.0 -> 5.31.2

### PR DESCRIPTION
**Pull request by volth**
update `perldevel`

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build perldevel
@GrahamcOfBorg build pkgsCross.aarch64-multiplatform.perldevel

**Comment by volth** [comment]
for `pkgsCross.aarch64-multiplatform.perldevel` the build of cross-`gcc` failed, which seems to be a recent regression (I am on ~2weeks old `master` and cross-compilation works there)

**Comment by volth** [comment]
@GrahamcOfBorg build perldevel
@GrahamcOfBorg build pkgsCross.armv7l-hf-multiplatform.perldevel

**Comment by volth** [comment]
cc @aanderse

**Comment by volth** [comment]
The error is only in `pkgsCross.aarch64-multiplatform.perldevel on aarch64-linux ` which is nonsense, because it is actually not a cross compilation. It is failed earlier than `perl` is built

**Comment by aanderse** [comment]
Thanks for the explanation. Final question: should we not rename `perl530` to `perl531`?

**Comment by volth** [comment]
No, even numbers are releases, uneven are development versions.
the current state is https://www.cpan.org/src/README.html

**Comment by aanderse** [comment]
Right. I might recall one of the developers at work who is into `perl` at work explaining that to me in the past. Thanks again! I really appreciate your working keeping `perl` a first class citizen in nixpkgs!

**Pull request merged**
