### PR TITLE
nrpl: init at 20150521

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Basic REPL for nim.

Cc: @ehmry

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
After building:

```
./result/bin/nrpl
> hi
/bin/sh: nim: command not found
> Error: unhandled exception: EOF reached [IOError]
```

**Comment by peterhoeg** [comment]
It works here:

```
> hi
Hint: nrpltmp [Processing]
nrpltmp.nim(1, 1) Error: undeclared identifier: 'hi'
> ^CSIGINT: Interrupted by Ctrl-C.
```

Very odd indeed. I'll take a look tomorrow.

**Comment by grahamc** [comment]
It is very likely because nrpl is using the PATH to find nim, which I don't have.

**Comment by peterhoeg** [comment]
@grahamc, do you mind giving this version a go? And happy new year!

**Pull request merged**
