### PR TITLE
svgcleaner: init at unstable-2021-08-30

### PR DESCRIPTION
**Pull request by yuuyins**
###### Description of changes

Re-add [svgcleaner](https://github.com/RazrFalcon/svgcleaner). It was removed at
- https://github.com/NixOS/nixpkgs/pull/146452, 
- https://github.com/NixOS/nixpkgs/commit/42d32516400c1d821d275a5460900bbaef3d3bf1

According to https://nixos.org/manual/nixpkgs/stable/#submitting-changes-deprecating-packages

>There is currently no policy when to remove a package.
>
>Before removing a package, one should try to find a new maintainer or fix smaller issues first. 

svgcleaner works very well despite not being developed anymore. I can be the maintainer.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ehmry** [comment]
Please consider adding some buggy features so this doesn't happen again.

**Comment by yuuyins** [comment]
> Please consider adding some buggy features so this doesn't happen again.

@ehmry sorry i don't understand. What exactly you mean by "adding some buggy features", and how this leads to "this doesn't happen again"?

**Comment by yuuyins** [comment]
thank you for merging btw!

**Comment by yuuyins** [comment]
well i see guess i will need to fork it and add some bugs for the sake of keeping it on nixpkgs just in case 😂

**Pull request merged**
