### PR TITLE
zig_0_10: fix macOS build

### LINKED ISSUE #214545: ncdu fails to build on darwin
nixpkgs a13e71c8e6e95c2c8d53302a13b92727caf3ab16

```
error: builder for '/nix/store/2rbv1ig09fr15iqxm3jzsmq785ycj89k-ncdu-2.2.2.drv' failed with exit code 2;
       last 10 log lines:
       >
       > /private/tmp/nix-build-ncdu-2.2.2.drv-0/ncdu-2.2.2/src/ncurses_refs.c:1:1: error: unable to build C object: clang exited with code 1
       > /private/tmp/nix-build-ncdu-2.2.2.drv-0/ncdu-2.2.2/src/model.zig:39:37: error: expected '{', found '('
       >     pub const Packed = packed struct(u64) {
       >                                     ^
       > ncdu...The following command exited with error code 1:
       > /nix/store/vfz2c7lgk9bb6ysadrd7wpz8qf3kln3a-zig-0.9.1/bin/zig build-exe /private/tmp/nix-build-ncdu-2.2.2.drv-0/ncdu-2.2.2/src/main.zig /private/tmp/nix-build-ncdu-2.2.2.drv-0/ncdu-2.2.2/src/ncurses_refs.c -lc -lncursesw -OReleaseSafe --cache-dir /private/tmp/nix-build-ncdu-2.2.2.drv-0/ncdu-2.2.2/zig-cache --global-cache-dir /private/tmp/nix-build-ncdu-2.2.2.drv-0/ncdu-2.2.2/Cache/zig --name ncdu -target native-native -mcpu x86_64 --enable-cache
       > error: the following build command failed with exit code 1:
       > /private/tmp/nix-build-ncdu-2.2.2.drv-0/ncdu-2.2.2/zig-cache/o/474d0dfff458481b99da3016f54c952e/build /nix/store/vfz2c7lgk9bb6ysadrd7wpz8qf3kln3a-zig-0.9.1/bin/zig /private/tmp/nix-build-ncdu-2.2.2.drv-0/ncdu-2.2.2 /private/tmp/nix-build-ncdu-2.2.2.drv-0/ncdu-2.2.2/zig-cache Cache/zig -Drelease-safe -Dcpu=baseline
       > make: *** [Makefile:15: release] Error 1
       For full logs, run 'nix log /nix/store/2rbv1ig09fr15iqxm3jzsmq785ycj89k-ncdu-2.2.2.drv'.
error: 1 dependencies of derivation '/nix/store/xi33vkwmibfh9ckpd986m9nwzvrab1k1-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/a72yyrdq1mxynl5sm8sxm3qsh7h1sy8q-darwin-system-23.05.20230204.a13e71c+darwin4.87b9d09.drv' failed to build
```

### PR DESCRIPTION
**Pull request by kubkon**
Relevant upstream issue: ziglang/zig#14559

The patch is a backport of fixes that landed in zig-master and can be removed with zig-0.11 release.

Additionally, make sure we link statically against LLVM to avoid unpleasant runtime surprises originating from mixing static and dynamic LLVM libraries.

Finally, unbreak Zig 0.10.1 on macOS.

cc @winterqt

---

Closes #214545.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
@ofborg build ncdu

**Comment by zowoq** [comment]
Can make 0.10 the default on darwin as well.

```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index a0d1e76e1c3..62a5de4e4df 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -24198,8 +24198,7 @@ with pkgs;
   zig_0_10 = darwin.apple_sdk_11_0.callPackage ../development/compilers/zig/0.10.nix {
     llvmPackages = llvmPackages_15;
   };
-  # Zig 0.10.1 is broken on Darwin, so use 0.9.1 on Darwin instead.
-  zig = if stdenv.isDarwin then zig_0_9 else zig_0_10;
+  zig = zig_0_10;
 
   zimlib = callPackage ../development/libraries/zimlib { };
 

```

**Comment by kubkon** [comment]
> Can make 0.10 the default on darwin as well.
> 
> ```diff
> diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
> index a0d1e76e1c3..62a5de4e4df 100644
> --- a/pkgs/top-level/all-packages.nix
> +++ b/pkgs/top-level/all-packages.nix
> @@ -24198,8 +24198,7 @@ with pkgs;
>    zig_0_10 = darwin.apple_sdk_11_0.callPackage ../development/compilers/zig/0.10.nix {
>      llvmPackages = llvmPackages_15;
>    };
> -  # Zig 0.10.1 is broken on Darwin, so use 0.9.1 on Darwin instead.
> -  zig = if stdenv.isDarwin then zig_0_9 else zig_0_10;
> +  zig = zig_0_10;
>  
>    zimlib = callPackage ../development/libraries/zimlib { };
>  
> ```

Done!

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 221153` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>cargo-lambda</li>
    <li>cargo-zigbuild</li>
    <li>clipbuzz</li>
    <li>ncdu</li>
    <li>zig</li>
    <li>zls</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zig_0_9</li>
  </ul>
</details>

**Comment by wegank** [comment]
@ofborg eval

**Pull request merged**
