### PR TITLE
nixos/tests/initrd-network-ssh: fix with real initrd secrets implementation

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Fixes the `initrd-network-ssh` test, which was broken by the use of a real initrd secrets implementation. This was fixed by enabling the bootloader in the VM, which also exposed a few other bugs along the way.

The `-serial pty` QEMU option specified in the boot disk image builder prevented errors from being shown, and `-nographics` is redundant.

For the secret to be accessible to the VM disk builder, it needed to be added to the store, which broke some assumptions in the initrd-ssh module. I removed some hacks there that do not seem to be necessary, though I may be missing some problem with this.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @emilazy @CRTified

### CODE REVIEW

**Comment by lopsided98** [comment]
@ofborg test initrd-network-ssh

**Comment by CRTified** [comment]
Thank you for taking care of this :)
Would it make sense to change the [type of hostKeys](https://github.com/NixOS/nixpkgs/blob/920f5320797c03cd131c28a3ab6036fff287d4b3/nixos/modules/system/boot/initrd-ssh.nix#L44) to `types.str` then, as `boot.initrd.secrets` expects strings in the end?

**Comment by lopsided98** [comment]
It looks like `virtualisation.useBootLoader` is broken on aarch64 and it looks pretty involved to make it work.

**Comment by Mic92** [comment]
@GrahamcOfBorg test initrd-network-ssh

**Comment by Ma27** [comment]
ping @emilazy could you please take a look? :) 
Also, we should probably document this behavior.

**Comment by emilazy** [comment]
Unfortunately I no longer remember what the `builtins.unsafeDiscardStringContext` was needed for; I worry a little about breaking working configs but it's probably fine to remove. I think it would be nice to still make `hostKeys = [ ./ssh_host_ed25519_key ]` work (although it's arguably a footgun), but if it doesn't then the [type of the option](https://github.com/NixOS/nixpkgs/blob/06fc2a6f95c5b49c54cc3cc342183ff279d8ac5b/nixos/modules/system/boot/initrd-ssh.nix#L44) should probably be updated.

**Comment by Ma27** [comment]
> I worry a little about breaking working configs 

@emilazy now that I think of it, I fully agree that this is quite important to keep in mind! For instance, I'm now using `hostKeys = [ /run/keys/sshkey ]` rather than `["/run/keys/sshkey"]` to make sure that the file from the key directory of nixops gets copied to `/etc/ssh/sshkey` and AFAICS this patch would leak my hostkey into the nix-store when deploying it with my current config.

**Comment by emilazy** [comment]
If your bootloader has initrd secrets support it's generally preferable to use the quoted paths; non-quoted paths will always be copied to the Nix store, whereas quoted paths are processed by the initrd secrets generator during `nixos-rebuild`. i haven't used NixOps so unfortunately i'm not sure how it affects this calculus. initrd secrets are flaky in a bunch of ways, e.g. #85000 (unfortunately pretty much amounts to "implement proper initrd secrets support for every bootloader", I think), #85563.

**Comment by Ma27** [comment]
No they don't, unless you do e.g. `"${./.}"` or am I misunderstanding you? As long as they get converted back to a string (e.g. with `toString` or in this case `baseNameOf`) no copy happens.

**Comment by lopsided98** [comment]
Yes, there are a lot of edge cases here. I think I have fixed it now.

In the test, the bootloader is installed in a VM (using `runInLinuxVM`), therefore the key must be in the store, making it difficult to test some of the more realistic cases. `"${./ssh_host_ed25519_key}"` results in a string (ie. `isString == true`) with a context that references the store path and needs to be removed. Therefore, I moved the `unsafeDiscardStringContext` call to cover both branches of `initrdKeyPath`. This allows the test to work and shouldn't break anyone's config.

**Comment by emilazy** [comment]
This PR probably wants to revert or at least adjust #102530.

**Pull request closed without merging**
