### PR TITLE
ghc: fix build for cross-ghc (target  aarch64-android) for 8.10.7

### LINKED ISSUE #179244: ghc: build for cross ghc (target aarch64-android) fails
### Steps To Reproduce
```
nix-shell -p pkgsCross.aarch64-android-prebuilt.haskell.packages.ghc8107.ghc
```
### Build log
```
error: attribute 'targetPrefix' missing

       at /nix/store/djjif9r889r2mgcqj0jmri74kmj1hifm-nixos-22.05/nixos/pkgs/development/compilers/ghc/8.10.7.nix:245:46:

          244|     export READELF="${targetCC.bintools.bintools}/bin/${targetCC.bintools.targetPrefix}readelf"
          245|     export STRIP="${bintoolsFor.strip}/bin/${bintoolsFor.strip.targetPrefix}strip"
             |                                              ^
          246|   '' + lib.optionalString (stdenv.targetPlatform.linker == "cctools") ''
(use '--show-trace' to show detailed location information)
```

### Additional context
I try to use this for reflex platform to build an android app with ghc.

### Notify maintainers

[https://github.com/chrbauer/nixpkgs/tree/fix-build-ghc-8-10-7]

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.05 (Quokka), 22.05.1191.ccf8bdf7262`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05"`
 - channels(fridolin): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by chrbauer**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chrbauer** [comment]
There is no bintoolsFor.strip.targetPrefix for target Aarch64 (see decl of bintoolsFor)

**Comment by chrbauer** [comment]
The problem is on 22.05, but 21.11 was ok

**Comment by cdepillabout** [comment]
A couple things:

- Could you rebase this on the `haskell-updates` branch?  We generally ask that all haskell-related fixes go to that branch instead of `master`.
- Could you explain what this is fixing?  How can I confirm that this fix does the right thing, and there was actually a bug previously?

**Review by sternenseemann — CHANGES_REQUESTED** [review]
This is the incorrect fix if there's anything to fix at all.

What do you mean by aarch64? -linux? -darwin? from what I can tell it evaluates correctly on both platforms and also for the cross codepath.

**Comment by chrbauer** [comment]
Ok, let us first decide, whether we need this patch for ghc 8.10.7 and whether my patch is the correct approach or not. I understand that you say it is incorrect, but i think i could work. A better solution would be of course nicer, but I'm not sure what this solution would be. (Most likely to fix bintools to make the bintoolsFor redundant, but I don't know what effort this would be.)

My setup is quite difficult. But I managed to find a simple way to demonstrate the problem in NixOS 22.05:

```sh
nix-shell -p pkgsCross.aarch64-android-prebuilt.haskell.packages.ghc8107.ghc
```
This results in the following error:

```
error: attribute 'targetPrefix' missing

       at /nix/store/djjif9r889r2mgcqj0jmri74kmj1hifm-nixos-22.05/nixos/pkgs/development/compilers/ghc/8.10.7.nix:245:46:

          244|     export READELF="${targetCC.bintools.bintools}/bin/${targetCC.bintools.targetPrefix}readelf"
          245|     export STRIP="${bintoolsFor.strip}/bin/${bintoolsFor.strip.targetPrefix}strip"
             |                                              ^
          246|   '' + lib.optionalString (stdenv.targetPlatform.linker == "cctools") ''
(use '--show-trace' to show detailed location information)
```

Please advice how we should continue. If we agree on a solution I can rebase the patch and check the other compilers, ...

**Comment by sternenseemann** [comment]
The correct fix is to make the `pkgsCross.aarch64-android-prebuilt.stdenv.cc.bintools.bintools` have the proper `passthru` attributes:

```diff
diff --git a/pkgs/development/androidndk-pkgs/androidndk-pkgs.nix b/pkgs/development/androidndk-pkgs/androidndk-pkgs.nix
index 04dfbcbedf0..736e088454e 100644
--- a/pkgs/development/androidndk-pkgs/androidndk-pkgs.nix
+++ b/pkgs/development/androidndk-pkgs/androidndk-pkgs.nix
@@ -56,9 +56,12 @@ rec {
   binaries = runCommand "ndk-toolchain-binutils" {
     pname = "ndk-toolchain-binutils";
     inherit (androidndk) version;
-    isClang = true; # clang based cc, but bintools ld
     nativeBuildInputs = [ makeWrapper ];
     propagatedBuildInputs = [ androidndk ];
+    passthru = {
+      targetPrefix = prefix;
+      isClang = true; # clang based cc, but bintools ld
+    };
   } ''
     mkdir -p $out/bin
```

**Comment by chrbauer** [comment]
[https://github.com/NixOS/nixpkgs/issues/179244](Issue created)

**Comment by cdepillabout** [comment]
@chrbauer Sorry for the back and forth rebasing, but you can probably go back to basing this on `master` since it doesn't have anything Haskell-specific anymore.

I'll wait for @sternenseemann to approve before merging though.

**Comment by chrbauer** [comment]
no problem with rebasing. I'm glad, that sternenseemann provided the solution.

**Pull request merged**
