### PR TITLE
update julia to 0.4.2

### PR DESCRIPTION
**Pull request by rened**

### CODE REVIEW

**Comment by ttuegel** [comment]
Travis failure *seems* spurious, but I'll double-check locally.

**Comment by ttuegel** [comment]
Could you please update the commit message to conform to our format for updates? It should be `julia: 0.4.0 -> 0.4.2`.

**Comment by rened** [comment]
@ttuegel thanks for looking at this! renamed.

**Comment by ttuegel** [comment]
Merged, thanks!

**Pull request merged**
