### PR TITLE
bottles: 2022.1.14-trento-4 -> 2022.2.14-trento

### PR DESCRIPTION
**Pull request by psydvl**
###### Motivation for this change
`bottles` updated from 2021.12.28-treviso to 2022.2.14-trento
~`bottles` updated from 2021.12.28-treviso to 2022.1.28-trento-4~
~`bottles` updated from 2021.12.28-treviso to 2022.1.14-trento-4~
~`bottles` updated from 2021.12.28-treviso to 2022.1.14-trento-2~

Add me as maintainer for this package

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by asbachb** [comment]
@psydvl I can confirm this is running. But maybe you could add some more information in your commit why you changed the stuff beside the version upgrade.

**Comment by asbachb** [comment]
I played around a little bit more. With the new version I'm unable to launch "Epic Game Store". First there's a message about missing graphics drivers. After I launched it with the old bottles I got into the application, but it seems to crash and screen stays black.

**Comment by psydvl** [comment]
> I played around a little bit more. With the new version I'm unable to launch "Epic Game Store". First there's a message about missing graphics drivers. After I launched it with the old bottles I got into the application, but it seems to crash and screen stays black.

Works fine for me
Can you provide more information?

<details>
<summary>There are bottle configuration file to share</summary>

image

</details>

<details>
<summary>Option to write terminal output to file</summary>

```console
bottles 2>&1 | tee file.log
```
or if launched from nixpkgs git
``` console
NIXPKGS_GIT=$PWD
nix-shell -I nixpkgs=$NIXPKGS_GIT -p bottles --run bottles 2>&1 | tee file.log
```

</details>

Screenshots will be fine to add too

**Comment by psydvl** [comment]
> @psydvl I can confirm this is running. But maybe you could add some more information in your commit why you changed the stuff beside the version upgrade.

`wineWowPackages` deleted, because it's not necessary dependency and by default bottles use `caffe` wine runner

`libunwind` added to steam-run because program default wine runner (`caffe-6.23`) require it and I think this is a better way to add it
More information about my investigation about it here https://github.com/bottlesdevs/Bottles/issues/922

Should I add this information somehow to `default.nix`?

**Comment by asbachb** [comment]
I guess it would be sufficient to add it in the commit message.

I can check the logs later on. But could not find anything suspicious on my previous run. Maybe it's some kind of my setup (wayland - sway, Ryzen). Created a new empty custom bottle and installed via the installer.

**Comment by psydvl** [comment]
Force pushed to add line(13) with comment and update commit message

**Review by asbachb — APPROVED** [review]
I'm able to build and run. Got some problems with Epic Game Store but I don't think it's caused by this PR.

**Comment by asbachb** [comment]
@psydvl Maybe you can add marvin to get this merged: https://github.com/timokau/marvin-mk2

**Comment by asbachb** [comment]
I'm unable to create an empty gaming bottle:

1) Moved `~/.local/share/bottles`
2) Created a new gaming bottle names "Epic Game Store"

UI:
```
Generating bottle configuration
The WINE config is being updated…
WINE config updated!
Setting Windows version…
Apply CMD default settings…
Optimizing environment…
Applying environment: Gaming…
Installing DXVK…
Installing dependency: Microsoft d3dx9 DLLs from DirectX 9 redistributable…
There was an error creating the bottle.
```

Console:
```
/home/asbachb/.local/share/bottles/temp/directx_Jun2010_redist/Apr2005_d3dx9_25_x86.cab: WARNING; possible 5960 extra bytes at end of file.
(18:01:00) ERROR Error while running async job: <bound method Manager.create_bottle of <bottles.backend.manager.Manager object at 0x7f982c273d60>>
Exception: [Errno 2] No such file or directory: '/home/asbachb/.local/share/bottles/temp/win32/d3dx9_25.dll'
  File "/nix/store/bqiyp83maijdr34hv6mcsvx06d23w05p-bottles-2021.12.28-treviso/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)
  File "/nix/store/bqiyp83maijdr34hv6mcsvx06d23w05p-bottles-2021.12.28-treviso/share/bottles/bottles/backend/manager.py", line 1143, in create_bottle
    self.dependency_manager.install(config, [dep, _dep])
  File "/nix/store/bqiyp83maijdr34hv6mcsvx06d23w05p-bottles-2021.12.28-treviso/share/bottles/bottles/backend/dependency.py", line 164, in install
    res = self.__perform_steps(config, step)
  File "/nix/store/bqiyp83maijdr34hv6mcsvx06d23w05p-bottles-2021.12.28-treviso/share/bottles/bottles/backend/dependency.py", line 257, in __perform_steps
    if not self.__step_get_from_cab(config=config, step=step):
  File "/nix/store/bqiyp83maijdr34hv6mcsvx06d23w05p-bottles-2021.12.28-treviso/share/bottles/bottles/backend/dependency.py", line 522, in __step_get_from_cab
    shutil.copy(
  File "/nix/store/i6vabb4div9iy6lsl642d86k1q8riasn-python3-3.9.9/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/i6vabb4div9iy6lsl642d86k1q8riasn-python3-3.9.9/lib/python3.9/shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
```

**Comment by asbachb** [comment]
I wonder if it would be beneficial to migrate that package to `https://nixos.org/manual/nixpkgs/stable/#sec-fhs-environments`.

**Comment by psydvl** [comment]
@asbachb it seems you launching old version 
According to log "bottles-2021.12.28-treviso"

**Comment by asbachb** [comment]
@psydvl You're right. Redone the test:

1) `rm -r ~/.local/share/bottles`
2) Created an empty gaming bottle

Which worked without problems.

**Review by asbachb — APPROVED** [review]

**Review by asbachb — APPROVED** [review]
Now Epic Game Store is working again. Lgtm!

**Review by asbachb — APPROVED** [review]
LGTM.

**Review by asbachb — APPROVED** [review]
Was able to launch and start epic game store.

**Review by asbachb — APPROVED** [review]
Launches, rund epic game store, run rocket league, ps4 controller works via bluetooth.

**Pull request merged**
