### PR TITLE
filebot: 5.1.4 -> 5.1.5

### PR DESCRIPTION
**Pull request by felschr**
## Description of changes

Supersedes #336827

Updates filebot to 5.1.5, migrates it to `pkgs/by-name` & reformats the file with `nixfmt-rfc-style`.

Changelog: https://www.filebot.net/forums/viewtopic.php?t=13578

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Atemu — APPROVED** [review]
Otherwise diff LGTM and I trust that you did basic QA.

**Comment by felschr** [comment]
According to [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases) backwards-compatible changes are allowed to be backported and among the specific examples it lists:

> - ✔️ Package version updates
>   -  ✔️ Patch versions with fixes
>   -  ✔️ Minor versions with new functionality, but no breaking changes

**Comment by Atemu** [comment]
They are indeed permitted but the question is whether it makes sense to do so.

For unstable, the mantra is to get all packages to the newest stable upstream releases on a best-effort basis with no regard for timing other than inter-compatibility. 

In stable release however, you generally keep everything as is and only backport important fixes or updates that must be made available to stable users or else they will have a really bad time (i.e. security, critical bugfixes). This is realised through an explicit branch-off.

My question is whether you want to backport this because it fixes an important bug that users would definitely want to see fixed quickly (i.e. a critical bug) or whether it's merely for the sake of keeping stable up to date with the newest small fixes and features. The latter contradicts the goal of the stable release; IMV it's supposed to be the unchanged initial state released in May with the minimal set of updates that are necessary.

**Comment by felschr** [comment]
@Atemu thank you for clarifying.
My only reason for backporting this PR was to include the new features & improvements and there are no security fixes mentioned in the changelog. Therefore I'm good with **not** backporting it.

I'll keep this in mind for future PRs.

**Pull request merged**
