### PR TITLE
nixos/networking-interfaces: add preferTempAddress option

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Most operating systems implement IPv6 privacy extensions and are using temporary address for outbound connections by default. NixOS should do the same.

###### Things done

- [x] Tested via tests/networking.nix (doesn't break anything)
- [x] Test if temporary addresses are actually being used
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg test networking.networkd.privacy

**Comment by vcunat** [comment]
The `ipv6` test [is broken on master](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.ipv6.x86_64-linux) and reverting this merge fixes it for me locally.

**Comment by rnhmjoj** [comment]
Ah, I didn't notice there were more networking tests outside networking.nix.

**Comment by rnhmjoj** [comment]
It looks like it checks if there is exactly one address, now there are 2 at least. It's pretty trivial to fix.

**Comment by vcunat** [comment]
Thanks for the very fast fix (< 1h).

**Pull request merged**
