### PR TITLE
pxz: use upstream's Makefile

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Description of changes

Cleanup that I've had sitting around for ages.

Instead of using custom build and install phases, just use upstream's.

At the same time, get rid of a build date in the binary.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Wait, this doesn't actually work. Super strange.

**Comment by dtzWill** [comment]
Great! After looking at upstream's Makefile, your second iteration looks good.

The version test is failing, presently, though.  For two reasons, I think:

1) Baked-in version doesn't match our `version` attribute.  This was previously injected into the build, looks like we still can by adding `"VERSION=${version}"` to `makeFlags` (just checked).

2) Apparently (?) the `--version` output drops the information about PXZ when piped to something?  With (1) change, normal output:
```
$ ./result/bin/pxz --version
Parallel PXZ 4.999.9beta+git (build 19700101)
xz (XZ Utils) 5.2.5
liblzma 5.2.5
```

Piped to `less` (or try grep'ing `pxz --version|grep PXZ` haha), the first line is missing:

```
$ ./result/bin/pxz --version |& cat
xz (XZ Utils) 5.2.5
liblzma 5.2.5
```

**Comment by dtzWill** [comment]
Not sure we want to go this route, but because I'm curious, here's a simple fix for the output being lost in these scenarios (`--help`, `--version`, to pipe): 9496c94ebf08ba592b101726e69b386b39d921bc .

**Comment by ajs124** [comment]
This is sort of out-of scope for this PR, but what's the use of pxz, nowadays? xz has had support for parallel compression for years.

**Comment by peterhoeg** [comment]
> This is sort of out-of scope for this PR, but what's the use of pxz, nowadays? xz has had support for parallel compression for years.

I have a few scripts that are using it. I didn't know that xz supported parallel ops, so at least in my case it would be a matter of changing those scripts.

**Pull request merged**
