### PR TITLE
ums: init at 5.3.1

### PR DESCRIPTION
**Pull request by thall**

### CODE REVIEW

**Comment by ip1981** [comment]
Could we teach the bot to ignore maintaners.nix? :-)

**Comment by civodul** [comment]
Igor Pashev <notifications@github.com> skribis:

> Could we teach the bot to ignore maintaners.nix? :-)

And to ignore me specifically?  :-)

Is it based on the list of people who changed a specific file?

Ludo’.

**Comment by spwhitt** [comment]
@ip1981 @civodul Configuration format is here: https://github.com/facebook/mention-bot/blob/master/CONFIG.md We put that in a file called `.mention-bot` in the repo root.

So yes we can ignore users, but it looks like ignoring files is not yet implemented.

**Comment by spwhitt** [comment]
@thall Thanks for the contribution, but I believe if it's possible to build UMS from [source](https://github.com/UniversalMediaServer/UniversalMediaServer/) rather than downloading a release, that's generally preferred.

**Comment by garbas** [comment]
@thall tnx!
@spwhitt i've merged this PR even if it builds from prepackaged tarball. other distros are also building it this way (eg. Arch -> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ums) and if we look at the recommended way how to build it from source you will see there is some netbeans ide clicking required (https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/How-to-Build-UMS-%28Advanced%29). while it would be preferred to have it build from source, it would make little sense to raise the bar even higher then other distros.

**Comment by spwhitt** [comment]
@garbas Fair enough, I wasn't aware of the extra hoop jumping involved.

**Pull request closed without merging**
