### PR TITLE
rmlint: 1.0.8 -> 2.0.0

### PR DESCRIPTION
**Pull request by k0ral**

### CODE REVIEW

**Comment by lethalman** [comment]
Use the tarball please.

**Comment by k0ral** [comment]
Tarball doesn't include [this fix](https://github.com/sahib/rmlint/pull/102), hence the use of a specific revision.
Sure I could use the tarball and patch it from nix, but I felt like patching upstream was cleaner.

**Comment by lethalman** [comment]
I don't think it's cleaner to see a revision instead of a version in a derivation name. I'd rather use a tarball + patch.

**Comment by k0ral** [comment]
I thought the deviration name was whatever I chose to write in the `name` attribute, regardless of the way I fetch the source code.
Anyway, I've updated the pull request to use a tarball + patch.

**Pull request merged**
