### PR TITLE
linuxPackages.tuxedo-keyboard: 3.0.5 -> 3.0.7

### PR DESCRIPTION
**Pull request by moni-dz**
###### Motivation for this change
Linux 5.13 support

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fortuneteller2k** [comment]
@ofborg build linuxPackages_5_13.tuxedo-keyboard

**Comment by SuperSandro2000** [comment]
@ofborg eval
@ofborg build linuxPackages_5_13.tuxedo-keyboard

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Review by felixsinger — APPROVED** [review]
Tested on InfinityBook S 14 v5, works.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 128787 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>4 packages marked as broken and skipped:</summary>  <ul>    <li>linuxPackages-libre.tuxedo-keyboard</li>    <li>linuxPackages_hardkernel_4_14.tuxedo-keyboard</li>    <li>linuxPackages_hardkernel_latest.tuxedo-keyboard</li>    <li>linuxPackages_latest-libre.tuxedo-keyboard</li>  </ul></details><details>  <summary>12 packages built:</summary>  <ul>    <li>linuxPackages.tuxedo-keyboard (linuxPackages_5_10.tuxedo-keyboard)</li>    <li>linuxPackages_4_14.tuxedo-keyboard</li>    <li>linuxPackages_4_19.tuxedo-keyboard</li>    <li>linuxPackages_5_12.tuxedo-keyboard</li>    <li>linuxPackages_5_13.tuxedo-keyboard (linuxPackages_latest.tuxedo-keyboard)</li>    <li>linuxPackages_5_4.tuxedo-keyboard</li>    <li>linuxPackages_hardened.tuxedo-keyboard</li>    <li>linuxPackages_latest_hardened.tuxedo-keyboard</li>    <li>linuxPackages_lqx.tuxedo-keyboard</li>    <li>linuxPackages_testing_bcachefs.tuxedo-keyboard</li>    <li>linuxPackages_xanmod.tuxedo-keyboard</li>    <li>linuxPackages_zen.tuxedo-keyboard</li>  </ul></details>

**Review by blanky0230 — COMMENTED** [review]
Nice, Thanks! :)

**Pull request merged**
