### PR TITLE
apptainer, singularity: fix wrapper PATH prefix

### PR DESCRIPTION
**Pull request by ShamrockLee**
###### Description of changes

This patch fixes a bug in the prefixed PATH of the wrapper introduced in f6e7fccfa6b22fb8928fd1c3cf8401f7fef17e11 .

The prefixing `PATH` should be specified as (in Bash)

```bash
"${defaultPathInputs// /\/bin:}${defaultPathInputs:+/bin}"
```

I forgot to add `${defaultPathInputs:+/bin}`, causing the trailing `/bin` to be missing, hence this PR.

This PR also specify the `nvidia-container-cli path` configuration option for Sylabs's SingularityCE.

This fixes (partially) #230851
Cc: @misumisumi

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ShamrockLee** [comment]
Let's wait until the branch-off.

**Comment by ShamrockLee** [comment]
@jbedo Are you available for a look?

**Comment by ShamrockLee** [comment]
Thank you.

BTW, as a simple fix, it would also be helpful to backport it to the stable branch.

**Review by jbedo — APPROVED** [review]
LGTM and tested ok as far as possible without an nvidia card.

**Pull request merged**
