### PR TITLE
azure-cli: 2.56.0 -> 2.58.0

### PR DESCRIPTION
**Pull request by jfchevrette**
## Description of changes

My naive attempt at updating azure-cli to 2.58.0

The list of package overrides was done semi-manually with a script which fetched the necessary details based on https://github.com/Azure/azure-cli/blob/azure-cli-2.58.0/src/azure-cli/requirements.py3.Linux.txt. The list was then checked to only include packages for which the version from `python311Packages` in nixpkgs-unstable was different

Not sure if there was a better way to do this. Let me know if I missed a tool or something, I'm always keen to learn!

Upstream changelog: https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#march-05-2024

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jfchevrette** [comment]
Result of `nixpkgs-review pr 297495` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>azure-cli</li>
    <li>azure-cli.dist</li>
  </ul>
</details>

**Comment by jonringer** [comment]
>Not sure if there was a better way to do this. Let me know if I missed a tool or something, I'm always keen to learn!

Unfortunately, upstream doesn't make this super easy to translate for Nix. Alternative would be to move it out of nixpkgs into NUR, using something like poetry2nix which would be less of a maintenance burden, but less useful for mainstream consumption.

**Review by jonringer — APPROVED** [review]
```
Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/297495

2 packages built:
azure-cli azure-cli.dist
```
Got usage, diff looks fine to me

**Comment by jonringer** [comment]
Just waiting on CI to finish

**Comment by jonringer** [comment]
aarch64-darwin seems to be far behind. merging.

**Pull request merged**
