### PR TITLE
pythonPackages.gssapi: fix tests, 1.6.2 -> 1.6.9

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
ZHF: #97479

The failing tests seem to be causing trouble upstream too (https://github.com/pythongssapi/python-gssapi/issues/220), so I skipped them (which itself wasn't particularly simple thanks to `nosetests`).

Also bumped to latest version, mostly to get python 3.8 working. Though this does have the effect of dropping python 2.7 support :shrug:

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
should also remove shouldbe from the dependencies, or else that failure will propagate to gssapi:

```
builder for '/nix/store/pv86mnsxhjr3mz3kanlffl3dwdyg3z0m-python3.8-shouldbe-0.1.2.drv' failed with exit code 1; last 10 log lines:
      from should_be import core
    File "/build/shouldbe-0.1.2/should_be/core.py", line 264, in <module>
      class ObjectMixin(BaseMixin):
    File "/build/shouldbe-0.1.2/should_be/core.py", line 334, in ObjectMixin
      alias_method('should_be_true', should_be_truthy)
    File "/build/shouldbe-0.1.2/should_be/core.py", line 169, in alias_method
      new_code = buildCode(oc, name=new_name)
    File "/build/shouldbe-0.1.2/should_be/core.py", line 136, in buildCode
      resc = CodeType(argcount or baseCode.co_argcount,
  TypeError: an integer is required (got type bytes)
cannot build derivation '/nix/store/aj7nhajw0pzq6lmm7jqrskqs7awy23vq-python3.8-gssapi-1.6.9.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jgas3kylvs2pghwqqwbv8q6q1jd86wrx-python3.8-asyncssh-2.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2r0ckwfa46zi8q0ig30mp22yf9hwg136-env.drv': 2 dependencies couldn't be built
[3 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/2r0ckwfa46zi8q0ig30mp22yf9hwg136-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/97873
2 packages failed to build:
python38Packages.asyncssh python38Packages.gssapi

2 packages built:
python37Packages.asyncssh python37Packages.gssapi
```

**Comment by jonringer** [comment]
also related: https://github.com/pythongssapi/python-gssapi/issues/215

**Comment by risicle** [comment]
Well ok, suppose that just means I've got to disable the tests for python 3.8 then. At least there's `pythonImportsCheck`.

On that note, it would be pretty useful to be able to introspect into packages to see if they're "disabled", allowing us to switch on that condition rather than replicate the logic of "`shouldbe` doesn't work on python 3.8" here.

**Comment by jonringer** [comment]
> Well ok, suppose that just means I've got to disable the tests for python 3.8 then

Yea, that seems fine



> On that note, it would be pretty useful to be able to introspect into packages to see if they're "disabled", allowing us to switch on that condition rather than replicate the logic of "`shouldbe` doesn't work on python 3.8" here.

The problem is that "disabling" a package just correlates to throwing an error. And this is kind of an "exceptional" problem, as most upstreams aren't completely dead.

It's unfortunate that upstream invested so much in an upstream library.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 97873 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages failed to build:</summary>  <ul>    <li>python38Packages.asyncssh</li>    <li>python38Packages.gssapi</li>  </ul></details><details>  <summary>2 packages built:</summary>  <ul>    <li>python37Packages.asyncssh</li>    <li>python37Packages.gssapi</li>  </ul></details>

**Comment by jonringer** [comment]
not sure why report was wrong:
```
https://github.com/NixOS/nixpkgs/pull/97873
4 packages built:
python37Packages.asyncssh python37Packages.gssapi python38Packages.asyncssh python38Packages.gssapi
```

**Pull request merged**
