### PR TITLE
mongodb-3_4, mongodb-3_6: drop

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

#203814 seems to be stalled, so let's try again.

The original PR drops boost160 while keeping boost159. I think it would be better to drop them both after #207373.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by gador** [comment]
Just for anyone dropping by:

This harsh update from version 3.4 to 6.0 breaks `unifi` which uses `pkgs.mongodb` by default. 
For the next time, can we please update more gradually? I know, mongodb 3.4 is EOL for quite some time now, but other services and packages depend on it and should have more gradually move to the new version to allow the updates to not break the database.

For others who noticed the database getting corrupted:

```
nix-shell -p mongodb-3_4 mongodb-tools
mongod --dbpath /var/lib/unifi/data/db  --logpath /var/log/unifi/repair.log --repair
mongod --dbpath /var/lib/unifi/data/db  --logpath /var/log/unifi/repair.log --journal --fork
mongodump --out=/root/mongodump
pkill mongod
exit
nix-shell -p mongodb-4_2 mongodb-tools
# remove old data dir and recreate it
mv /var/lib/unifi/data/db /var/lib/unifi/data/db_bak
mkdir /var/lib/unifi/data/db
mongod --dbpath /var/lib/unifi/data/db  --logpath /var/log/unifi/repair.log --journal --fork
mongorestore /root/mongodump
pkill mongod
nix-shell -p mongodb-5_0 mongodb-tools
(rinse and repeat)
nix-shell -p mongodb-6_0 mongodb-tools
(rinse and repeat)
```
I'm not sure whether thes gradual procedure is necessary, but at least it works.

**Comment by Artturin** [comment]
This needs a release note and upgrade instructions if needed

**Comment by gador** [comment]
What would be the best way to tackle this?
I just tested this in a VM with an older commit (677ed08a50931e38382dbef01cba08a8f7eac8f6) with the older `mongodb` and a more recent commit with the newer `mongodb-4_2`. 
Unfortunately even the update from `3_4` to `4_2` breaks the database. Should we add a check for `stateVersion` and a warning to first backup the database?

I just feel a release note isn't enough, since every user who updates to `23.05` will break their unifi installation.

**Comment by wegank** [comment]
Perhaps by specifying in the release note that MongoDB upgrades must be done (and progressively, following the official instruction `3.4 -> 3.6 -> 4.0 -> 4.2 (-> 4.4)`) in 22.11 before upgrading to 23.05?

**Comment by wegank** [comment]
@riotbib @winterqt Could you please take a look at including the instructions in the release notes?

**Comment by riotbib** [comment]
> @riotbib @winterqt Could you please take a look at including the instructions in the release notes?

Sure, @wegank. Added to my TODOs. Thanks for the reminder!

**Comment by Ralith** [comment]
This bit me today, after reading the release notes and seeing no mention of breaking changes :(

**Pull request merged**
