### PR TITLE
notesnook: 2.6.1 -> 3.0.6

### PR DESCRIPTION
**Pull request by cig0**
## Description of changes

- Application update: https://github.com/streetwriters/notesnook/releases/tag/v3.0.6
- Package update: (Darwin) fix installation

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by cig0** [comment]
New PR as requested by https://github.com/NixOS/nixpkgs/pull/312066#issuecomment-2131404981

**Comment by j0lol** [comment]
Issue on darwin aarch64: 
```
error: builder for '/nix/store/9wjmrz9nfmnjn4k9lhcvpxsiwwkfyaam-notesnook-3.0.6.drv' failed with exit code 1;
       last 4 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/afwks9bv2y2fik98a62bb68j8jbhv3bs-notesnook_mac_arm64.dmg
       > error: only HFS file systems are supported.
       > do not know how to unpack source archive /nix/store/afwks9bv2y2fik98a62bb68j8jbhv3bs-notesnook_mac_arm64.dmg
       For full logs, run 'nix log /nix/store/9wjmrz9nfmnjn4k9lhcvpxsiwwkfyaam-notesnook-3.0.6.drv'.
```

**Comment by j0lol** [comment]
Looks like theyre just releasing app.zips now, ill switch it to that

**Comment by j0lol** [comment]
huh im not sure what the best way to deal with a .zip is

**Comment by cig0** [comment]
> huh im not sure what the best way to deal with a .zip is

Is there any reason for that switch? `v.3.0.6` has `.dmg` packages available.

**Comment by cig0** [comment]
Hey @j0lol let me know if you need a hand; I can help you maintain this package!

**Comment by j0lol** [comment]
I would love help maintaining! @cig0 

> Is there any reason for that switch? v.3.0.6 has .dmg packages available.

I'm not sure why, but nix fails to extract the dmg... I'll look into it :) I would like to resolve issues with macos builds but I think the priority is just to get linux builds merged.

**Comment by j0lol** [comment]
Found the issue: notesnook seems to distribute APFS images, but undmg only supports HFS

https://discourse.nixos.org/t/help-with-error-only-hfs-file-systems-are-supported-on-ventura/25873/11

**Comment by j0lol** [comment]
Somewhat embarrassingly, im not sure macos builds ever worked? it puts a .app in $out/Applications/Notesnook.app but doesn't seem to do anything with it. Odd!

**Comment by j0lol** [comment]
```
➜ nix run nixpkgs#sequelpro

error: unable to execute '/nix/store/gvckm7x4dz4hy6rnqv70dwkz38dyj5zg-sequel-pro-1.1.2/bin/sequel-pro': No such file or directory

➜  gvckm7x4dz4hy6rnqv70dwkz38dyj5zg-sequel-pro-1.1.2 tree -L 2
.
└── Applications
    └── Sequel Pro.app
```

This is standard behavior! Welp.

**Review by j0lol — CHANGES_REQUESTED** [review]
MacOS build needs to be modified like so to use `_7zz` over `undmg`:
```nix
  darwin = stdenv.mkDerivation {
    inherit pname version src meta;

    nativeBuildInputs = [ _7zz ];

    sourceRoot = "Notesnook.app";

    # 7zz did not unpack in setup hook for some reason, done manually here
    unpackPhase = ''
      7zz x $src
    '';
    
    installPhase = ''
      mkdir -p $out/Applications/Notesnook.app
      cp -R . $out/Applications/Notesnook.app
    '';
  };
```

Other than that, seems ready for merge.

**Review by j0lol — APPROVED** [review]
Looks great!

**Comment by jrunestone** [comment]
Hey thanks guys for putting this together!

**Comment by Gerg-L** [comment]
Result of `nixpkgs-review pr 314730` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>notesnook</li>
  </ul>
</details>

**Review by Gerg-L — APPROVED** [review]

**Comment by cig0** [comment]
> Hey thanks guys for putting this together!

@j0lol did the heavy lifting and deserves the credit :raised_hands: It's been a month since I switched to NixOS, and I have so much to learn lol. Embrace the :snowflake:!

**Comment by cig0** [comment]
@j0lol Would it be okay for you to add the `backport release-24.05 ` label so folks on that channel can enjoy having their favorite app updated?

**Comment by pbsds** [comment]
this is a major version bump. which typically is not elegible for backport

**Pull request merged**
