### PR TITLE
ati-drivers: update to Catalyst 15.7 and fix building with recent kernels

### LINKED ISSUE #2912: ati_unfree fails to compile with newer kernel versions
I was given a tip by vcunat to upgrade the kernel to see if my GPU requires a newer kernel version (AMD has done a lot of adding to the linux kernel lately). But I received the same error when I tried upgrading to linuxPackages_3_14 and linuxPackages_latest:

/tmp/nix-build-ati-drivers-13.12-3.14.6.drv-0/common/lib/modules/fglrx/build_mod/2.6.x/kcl_acpi.c: In function 'KCL_ACPI_GetHandles':
/tmp/nix-build-ati-drivers-13.12-3.14.6.drv-0/common/lib/modules/fglrx/build_mod/2.6.x/kcl_acpi.c:796:59: error: 'struct acpi_dev_node' has no member named 'handle'
         pInfo->video_handle = pInfo->pcidev->dev.acpi_node.handle;

Can someone reproduce this? Suggested fix?

### PR DESCRIPTION
**Pull request by dfoxfranke**
Fixes #2912.

### CODE REVIEW

**Comment by geerds** [comment]
I'll test these changes this evening

**Comment by dfoxfranke** [comment]
Looks like my fix for 3.18 broke 3.14. I'm working on adding a conditional compilation to fix this...

**Comment by dfoxfranke** [comment]
Just to clarify in case someone is waiting on me: commit d7443ffb892be6c61eb71a20ae19e2da23f29dc8 fixes the problem mentioned in my previous comment, and to the best of my knowledge this should be ready to merge. I've been running it on my system for the past week.

**Comment by vcunat** [comment]
I re-tested it's building at least, on both 64-bit and 32-bit, kernels 3.14, 3.18, 4.1.

**Comment by matthiasbeyer** [comment]
I cannot rebuild my system with kernel 4.2 and ati drivers.

Maybe I post another issue for this.

**Pull request merged**
