### PR TITLE
python3Packages.hyperscan: init at 0.6.0

### PR DESCRIPTION
**Pull request by mbalatsko**
## Description of changes

- added package with Python bindings of `hyperscan`
- `hyperscan`: build  on `x86_64-darwin`
- `hyperscan`: build `chimera`
- `secretscanner `: restricted platforms to `x86_64-linux`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
@avnik just making sure the changes are okay with you.

**Comment by mbalatsko** [comment]
Result of `nixpkgs-review pr 258283` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>hyperscan</li>
    <li>noseyparker</li>
    <li>python310Packages.hyperscan</li>
    <li>python311Packages.hyperscan</li>
    <li>rspamd</li>
    <li>secretscanner</li>
    <li>suricata</li>
  </ul>
</details>

**Comment by happysalada** [comment]
This looks good to me, happy to wait a bit for other people to have a look at it too.

**Comment by mbalatsko** [comment]
Made some minor fixes and managed to add hyperscan build on x86_64-darwin! Will post `nixpkgs-review` result on both platforms shortly

**Comment by mbalatsko** [comment]
Result of `nixpkgs-review pr 258283` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>hyperscan</li>
    <li>noseyparker</li>
    <li>python310Packages.hyperscan</li>
    <li>python311Packages.hyperscan</li>
    <li>rspamd</li>
    <li>secretscanner</li>
    <li>suricata</li>
  </ul>
</details>

**Comment by mbalatsko** [comment]
Result of `nixpkgs-review pr 258283` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>secretscanner</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>hyperscan</li>
    <li>hyperscan.dev</li>
    <li>python310Packages.hyperscan</li>
    <li>python310Packages.hyperscan.dist</li>
    <li>python311Packages.hyperscan</li>
    <li>python311Packages.hyperscan.dist</li>
  </ul>
</details>

**Comment by mbalatsko** [comment]
> 1 package failed to build:
> * secretscanner

I have restricted platforms to `x86_64-linux` as it depends on hyperscan and earlier was built only on `x86_64-linux`. Are you ok with that @fabaff ?

**Comment by mbalatsko** [comment]
Result of `nixpkgs-review pr 258283` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>hyperscan</li>
    <li>hyperscan.dev</li>
    <li>python310Packages.hyperscan</li>
    <li>python310Packages.hyperscan.dist</li>
    <li>python311Packages.hyperscan</li>
    <li>python311Packages.hyperscan.dist</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]

**Pull request merged**
