### PR TITLE
Added support for TPM to OVMF

### PR DESCRIPTION
**Pull request by witchof0x20**
###### Motivation for this change
Windows 11 requires TPM2 support. This patch adds TPM2 support to OVMF.

Related to #141224 

###### Things done
* Added `tpmSupport` flag to `OVMF`
* Added the corresponding build flags for TPM support

Based on this gentoo patch:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=7ece9892529e7690a1c763a4ab7f33046bc069ae

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
Just minor comestic changes.

**Review by thiagokokada — APPROVED** [review]
`nixpkgs-review` didn't trigger any rebuilds, but rebuilding it manually worked fine. Tested the result `OVMF_CODE.fd` file on my Windows 10 VM, and while I didn't tested the TPM part itself, it is still reporting that it is Secure Boot enabled (I did a `OVMF.override { secureBoot = true; tpmSupport = true; }`), so it seems fine.

BTW, right now there is no way to use this package unless you manually create an overlay, but this will generate a local build. I think it would be nice to expose this to `all-packages` so we could have a hydra cache of this artifact. To avoid breaking changes, I would propose:

```
  OVMF = callPackage ../applications/virtualization/OVMF { };
  OVMF-CSM = OVMF.override { csmSupport = true; };
  OVMF-secureBoot = OVMF.override { secureBoot = true; };
  OVMF-secureBootTpm = OVMF.override { secureBoot = true; tpmSupport = true; };
```

WDYT @witchof0x20 ?

Anyway, tested and approved.

**Comment by witchof0x20** [comment]
> `nixpkgs-review` didn't trigger any rebuilds, but rebuilding it manually worked fine. Tested the result `OVMF_CODE.fd` file on my Windows 10 VM, and while I didn't tested the TPM part itself, it is still reporting that it is Secure Boot enabled (I did a `OVMF.override { secureBoot = true; tpmSupport = true; }`), so it seems fine.
> 
> BTW, right now there is no way to use this package unless you manually create an overlay, but this will generate a local build. I think it would be nice to expose this to `all-packages` so we could have a hydra cache of this artifact. To avoid breaking changes, I would propose:
> 
> ```
>   OVMF = callPackage ../applications/virtualization/OVMF { };
>   OVMF-CSM = OVMF.override { csmSupport = true; };
>   OVMF-secureBoot = OVMF.override { secureBoot = true; };
>   OVMF-secureBootTpm = OVMF.override { secureBoot = true; tpmSupport = true; };
> ```
> 
> WDYT @witchof0x20 ?
> 
> Anyway, tested and approved.

Sounds good to me! I went ahead and added that change

**Comment by witchof0x20** [comment]
ah crap broke my branch 1 sec

**Review by thiagokokada — APPROVED** [review]

**Review by thiagokokada — APPROVED** [review]

**Review by thiagokokada — APPROVED** [review]
Result of `nixpkgs-review pr 141236` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>OVMFFull</li>
  </ul>
</details>

**Pull request merged**
