### PR TITLE
nixos/grub: implements GRUB_SAVEDEFAULT feature

### PR DESCRIPTION
**Pull request by SrTobi**
Original issue: #108206

This will make grub remember the configuration that was booted and
select it as default menu entry the next time.

I'm not sure how to test this exactly.
I tried it on my NixOS system and it worked.
But I was using grub2.
I also implemented this for grub1, but I have no idea if it works.
I followed this documentation: https://www.gnu.org/software/grub/manual/legacy/savedefault.html

###### Motivation for this change

This is a well known feature `grub-mkconfig` offers and which is currently not (or not easily) achievable within a `configuration.nix`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
For now I suggest to just ignore this in GRUB Legacy.

**Comment by AndersonTorres** [comment]
Try a virtual machine from scratch.

**Comment by SrTobi** [comment]
Ok, I tried it with a virtual machine and it works. Also tried it with grub legacy there, and even though I couldn't get grub legacy to  boot (because nixos-rebuild would fail with multiple errors) the `menu.lst` that was created looked exactly as in the documentation.

**Comment by AndersonTorres** [comment]
@SrTobi did you try legacy grub before that modification?

**Comment by SrTobi** [comment]
@AndersonTorres yeah, had nothing to do with the savedefault changes. I used the standard config generated by `nixos-generate-config`:

image


When running rebuild I get various issues depending on the previous state of the installation.

1. When having previously used grub2, I get:
image

2. When deleting `/boot` and running rebuild I get:
image


Partitions:
image

**Comment by Vinetos** [comment]
Any news ?

**Comment by SrTobi** [comment]
@Mic92 @samueldr can you have a look? What is to do here?

**Comment by corngood** [comment]
I've been using this for a while without any problems.  Thanks!

**Comment by SrTobi** [comment]
@corngood what do you mean you have been using it? do you have a custom nixpkg version? or how?

**Comment by corngood** [comment]
Yeah, I maintain a fork of `master` with some things merged into it, this is one of them.

**Comment by SrTobi** [comment]
ah ok, thx. was a little confused :D

**Review by AndersonTorres — APPROVED** [review]
LGTM. LGTBorg.

**Comment by SrTobi** [comment]
@Mic92, @samueldr could you pls have a look as well... this is sitting for over half a year

**Pull request merged**
