### PR TITLE
[WIP] Nix Java/Maven environment

### PR DESCRIPTION
**Pull request by NeQuissimus**
**DO NOT MERGE**

I am looking for feedback here before I continue.
My laptop is for RMA, so I figured I use the time to gather feedback.

This is intended to provide a full Java/Maven environment for NixOS.
Maven is a giant mess of circular dependencies and odd behaviour :)

What I am doing is basically the following:
Build my dependencies and their transitive dependencies all from source.
Every time I hit a circular dependency (which happens more often than I would like), bootstrap in a binary version of said dependency.

Maven very much depends on an actual Maven repository. In order to keep it from running to Maven Central or any other third-parts repository, I create a Maven mirror pointing to the nix-store.
Maven will then attempts to find all artifacts there rather than the Internet.
This, however, means that I need to do some copying of artifacts into an `.m2` structure, as Maven seems to dislike symlinks.

In `all-packages.nix` I have defined namespaces for Maven plugins and Java packages/libraries, so that the default namespace is not cluttered up with things most users will not want to see. (Similar to other language-specific environments we have)

Note that this is very much a work-in-progress and is far from done.
For example, I want to remove the `poms.xml` file and place the expressions somewhere more sensible, probably into separate files, grouping only different versions of the same POM into a single file.
My ultimate goal is to build Maven itself as well as Gradle (another build tool) from source, including all their (transitive) dependencies.
So far I am still working on the first library, Apache Commons I/O.

I have not squashed git commits so far, so that a little bit of context can be provided by the messages.

I welcome any and all feedback, this is turning into much more work than I had anticipated and I would not want to go down this very long path and spend so much time and then end up having created an awful solution nobody wants :)
Don't be afraid to trash this.

Thanks, guys!

### CODE REVIEW

**Comment by copumpkin** [comment]
Very exciting, but I haven't had a chance to actually review what you've done! 

Just want to cc @shlevy who's worked in the space and made https://github.com/NixOS/mvn2nix-maven-plugin. Also @charleso who's been interested in the past.

I'll try to review it myself in the next couple of days, thanks.

**Comment by shlevy** [comment]
In addition to mvn2nix, check out https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/build-maven.nix.

**Comment by shlevy** [comment]
(I do building of .m2 in the store in that expr)

**Comment by puffnfresh** [comment]
Just did a quick review, looks like a good approach, even though it has a lot of copying :+1:

**Comment by NeQuissimus** [comment]
@shlevy Maybe I do not understand correctly. Does build-maven handle dependency JARs?
Effectively, this builds using maven and places the resulting JAR in the nix-store, correct? Maybe I am missing something.
I did not know about writeText, I will definitely be stealing that :)

**Comment by shlevy** [comment]
@NeQuissimus You use mvn2nix-maven-plugin to generate a dependency specification, which build-maven uses to fetch all dependencies and build a full .m2 repo in the store (symlinks have worked fine for me, I'm not sure what issue you've had) and then build the jar into the store. But you can also just use the repo-building function if you want to. Currently it fetches binaries for the dependencies, but it could in principle do builds transitively.

**Comment by NeQuissimus** [comment]
Ah, ok, the disconnect was that I did not realize the two worked hand-in-hand.
I will look this through once I have my laptop back :)
Thanks already.

**Comment by copumpkin** [comment]
> as Maven seems to dislike symlinks.

Any idea why that is? Sounds like it'll make building temporary package environments a bit of a pain.

**Comment by shlevy** [comment]
As I said above, sum links have worked for me just fine

**Comment by NeQuissimus** [comment]
I will try this again, maybe my errors were caused by something else.
I should have my laptop back some time this week and will take a look then.

**Comment by bendlas** [comment]
@NeQuissimus Interesting, I'm working on tooling to build leiningen projects with nix. I'll be sure to take some time out to review your take on mvn in depth. One question from reading your description: If you're going for bootstrapping, is it necessary to do binary bootstrapping in case of circular deps? Couldn't you maybe put the source-path of the dependency onto the compile - class-path of the target?

**Comment by shlevy** [comment]
@bendlas FYI, I've used `mvn2nix-maven-plugin` to build lein projects in the past (via `lein pom`)

**Comment by NeQuissimus** [comment]
@bendlas For plain builds, I would say yes.
But Maven will search its repository for binaries, I am pretty sure I would have to alter pom files to make sources available.

Note that due to my limited time right now, I have not been able to clean things up at all. I wanted to get `commonsIo` with all dependencies going first. That should give me/us all the plugins and libs Maven needs to get going. Once that is done, building other libraries should be much easier.
I did want to refactor some things before kicking off another review. There are some things I don't like right now.

**Comment by bendlas** [comment]
@shlevy yep, your program at https://github.com/NixOS/mvn2nix-maven-plugin/blob/6606b3b04def33d6f7944ac68dffa7ea80c998d2/src/main/java/org/nixos/mvn2nix/Mvn2NixMojo.java#L253 was also a great source of inspiration, thank you! I'm making a java runner for modules described through nix, with classloader, security-manager and thread-pool separation, to run multiple java programs within one vm: https://github.com/webnf/dwn
Now, first I adapted my existing tooling with a leiningen plugin https://github.com/webnf/lein-nix, but thinking about this again, it would actually make a lot of sense to generate the class paths through `mvn2nix`.

@NeQuissimus impressive, did you write all the dependencies out by hand? I like the Idea of bootstrapping maven. Even if pulling in another set of binary deps makes me sad, at least it should come in handy for anybody hacking on maven. Still, if (most of) the derivations could be generated through `mvn2nix` or similar, that would be a massive boon in my view.

**Comment by NeQuissimus** [comment]
I did look at `mvn2nix`. The issue with building everything from source in the Java/Maven space is that there is a massive number of cyclic dependencies just to even get Maven going.
I suspect (although this is purely an educated guess) that at some point ancient versions of Maven plugins were built using Ant. I say this because essentially every Maven plugin has a dependency chain that eventually ends in a cycle. The only good explanation I can come up with is that these very old dependencies forming the cycle were built using Ant once upon a time and to avoid Ant, things have been modified to depend on binary files.

To be fair, I was expecting all of this to be much less work that it has turned out to be. However, once all the Maven plugins have been completed, building libraries should be trivial.

**Comment by shlevy** [comment]
Yeah, mvn2nix doesn't even try to build deps from source by default, and in many cases there are deps which are binary only. I'm honestly not sure what is gained by doing deps from source, really, in the java world.

**Comment by NeQuissimus** [comment]
I am mostly doing it because it seems to be "the NixOS way" :)

**Comment by Mathnerd314** [comment]
https://wiki.gentoo.org/wiki/Project:Java/Why_build_from_source has a list of advantages.

Other languages have moved their packages to a separate file (go-packages, python-packages, etc.), partly so that they can be built with different compiler versions; should this also happen for Java? ``javaPackages`` and ``mavenPlugins`` are attribute sets so it would not be hard.

**Comment by copumpkin** [comment]
@NeQuissimus what happened?

**Pull request closed without merging**
