### PR TITLE
jamomacore: remove as unmaintained

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

This library is broken since years, upstream has no activity since 2015 for this library
I found one application using it which looks unmaintained also, so removed it too

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Can you rebase this branch on master to fix the eval error?

**Review by RaghavSood — APPROVED** [review]

**Review by prusnak — CHANGES_REQUESTED** [review]
https://github.com/ossia/i-score redirects to https://github.com/ossia/score which is **totally alive** (last commit is 11 hours ago).

I suggest renaming `i-score` to `ossia-score` and updating it to latest version (which does not seem to require jamomacore).

Then we can drop the `jamomacore`.

**Comment by freezeboy** [comment]
I am ok to add this software, but:

1) as the previous was broken since ages, I suppose nobody use it currently
2) I am not sure what their "release" suffix a19 means, but from other tags I guess alpha, and the fetch phase doesn't work:

```
From https://github.com/ArashPartow/exprtk
 * [new branch]      master     -> origin/master
fatal: reference is not a tree: d312ba91419c9cb12c8279fd3a19096d39dfcb5e
Unable to checkout d312ba91419c9cb12c8279fd3a19096d39dfcb5e from https://github.com/ArashPartow/exprtk.
```

**Comment by prusnak** [comment]
> I am not sure what their "release" suffix a19 means, but from other tags I guess alpha, and the fetch phase doesn't work:

In that case I think it's best to wait for the 3.0.0 stable

**Comment by SuperSandro2000** [comment]
@freezeboy please resolve the merge conflict.

**Comment by freezeboy** [comment]
Rebased, i also gave another try to build ossia-score to follow @prusnak's idea but still no success apparently they don't provide all the files in the source tgz.

**Pull request merged**
