### PR TITLE
nixos/drone-server: init

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change

#70519

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/73971)

### CODE REVIEW

**Comment by davidak** [comment]
@filalex77 do you want to continue this? i would love to run drone natively on nixos. but in docker is also fine i guess

**Comment by Mic92** [comment]
I also have drone-exec-runner packaged, so it works without docker: https://github.com/Mic92/dotfiles/blob/master/nixos/eve/modules/drone.nix

**Comment by hexop** [comment]
> I also have drone-exec-runner packaged, so it works without docker: https://github.com/Mic92/dotfiles/blob/master/nixos/eve/modules/drone.nix

I'm interested in packaging it for nixpkgs, as my first real contribution.
I can't see a license on your repo, can I use your module as a base for a PR?

**Comment by Mic92** [comment]
> > I also have drone-exec-runner packaged, so it works without docker: [https://github.com/Mic92/dotfiles/blob/master/nixos/eve/modules/drone.nix](https://github.com/Mic92/dotfiles/blob/master/nixos/eve/modules/drone.nix?rgh-link-date=2021-02-15T16%3A20%3A30Z)
> 
> I'm interested in packaging it for nixpkgs, as my first real contribution.
> I can't see a license on your repo, can I use your module as a base for a PR?

There you go: https://github.com/Mic92/dotfiles/blob/master/LICENSE.md

**Comment by hexop** [comment]
> > > I also have drone-exec-runner packaged, so it works without docker: [https://github.com/Mic92/dotfiles/blob/master/nixos/eve/modules/drone.nix](https://github.com/Mic92/dotfiles/blob/master/nixos/eve/modules/drone.nix?rgh-link-date=2021-02-15T16%3A20%3A30Z)
> > 
> > 
> > I'm interested in packaging it for nixpkgs, as my first real contribution.
> > I can't see a license on your repo, can I use your module as a base for a PR?
> 
> There you go: https://github.com/Mic92/dotfiles/blob/master/LICENSE.md

Thanks, I'll start hacking on it ASAP

**Comment by pinpox** [comment]
I'm getting this error on every build, using the drone-exec-runner package linked above:
```
+ git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /tmp/drone-3wNQW6gz5vVqH4j9/drone/src/.git/
+ git remote add origin https://github.com/pinpox/test-drone-ci.git
+ git fetch  origin +refs/heads/main:
fatal: unable to access 'https://github.com/pinpox/test-drone-ci.git/': Could not resolve host: github.com
```

I found a few related issues, e.g. https://github.com/drone-plugins/drone-git/issues/67#issuecomment-378268813 But the fixes all reference docker settings. Do you need any specific network settings for it to work? Not sure where or to what I should set `DRONE_RUNNER_NETWORKS=` or `DRONE_NETWORK` here

**Comment by pinpox** [comment]
I found the cause for the error above. I had to add a few packages to get it to resolve DNS
```nix
   path = [
      pkgs.git
      pkgs.gnutar
      pkgs.bash
      pkgs.nixUnstable
      pkgs.gzip
      pkgs.bind
      pkgs.dnsutils
      pkgs.openssh
    ];
  ```

Drone doesn't seem to be able to run nix commands though:
```nix
+ nix shell 'nixpkgs#hello' -c hello
error: --- Error --- nix
cannot open connection to remote store 'daemon': error: --- SysError --- nix
reading from file: Connection reset by peer
```

**Comment by Mic92** [comment]
I am pretty sure git does not use dnsutils/bind for resolving hostnames. I have the nscd socket bind mounted into the chroot. However this is completly off-topic since this module does not configure any runner.

**Comment by Mic92** [comment]
Related to this `drone-runner-exec` pr: https://github.com/NixOS/nixpkgs/pull/115003

**Comment by davidak** [comment]
FYI: Drone is not fully open source anymore. There is a community fork of the last open version. https://woodpecker-ci.org/
We use it at https://codeberg.org/ and it works well. So i suggest to package that instead.

**Comment by davidak** [comment]
>Drone still is fully open source, the licence just prohibits using certain parts for enterprise

That violates [freedom 0 of FSFs Free Software definition](https://www.gnu.org/philosophy/free-sw.html#four-freedoms) and is therefore not open source! It is source-available.

You are right that woodpecker does not support all features (yet) that newer drone versions have.

**Pull request closed without merging**
