### PR TITLE
securefs: 0.11.1 -> 0.13.0

### PR DESCRIPTION
**Pull request by aaftre**
###### Description of changes

Updated package version in pkgs/tools/filesystems/securefs/default.nix to version 0.13.0, removed dependency on back ported patch add-macfuse-support.patch.

version 0.12.0+ added support for Apple M1.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by viraptor** [comment]
Result of `nixpkgs-review pr 186312` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>securefs</li>
  </ul>
</details>

**Comment by viraptor** [comment]
darwin intel build fails with:
```
/tmp/nix-build-securefs-0.13.0.drv-0/source/sources/unix.cpp:150:20: error: no member named 'futimens' in the global namespace
        int rc = ::futimens(m_fd, ts);
                 ~~^
/tmp/nix-build-securefs-0.13.0.drv-0/source/sources/unix.cpp:405:16: error: no member named 'utimensat' in the global namespace
    int rc = ::utimensat(m_dir_fd, path.c_str(), ts, AT_SYMLINK_NOFOLLOW);
             ~~^
2 errors generated.
make[2]: *** [CMakeFiles/securefs-static.dir/build.make:370: CMakeFiles/securefs-static.dir/sources/unix.cpp.o] Error 1
```

Also the PR name should be `securefs: 0.11.1 -> 0.13.0` according to https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md

**Comment by viraptor** [comment]
The compilation can be fixed by using:
```
darwin.apple_sdk_11_0.callPackage pkgs/tools/filesystems/securefs { }
```
in all-packages.nix. But the app still doesn't start then because of:
```
dyld[18747]: Library not loaded: /usr/local/lib/libfuse.2.dylib
  Referenced from: /nix/store/39lzarsp58z2xyl9kyp8blgq70pklhli-securefs-0.13.0/bin/securefs
  Reason: tried: '/usr/local/lib/libfuse.2.dylib' (no such file), '/usr/lib/libfuse.2.dylib' (no such file)
[1]    18747 abort      ./result/bin/securefs --help
```
It needs some rpath / install_name rewriting.

**Comment by wegank** [comment]
> The compilation can be fixed by using:
> 
> ```
> darwin.apple_sdk_11_0.callPackage pkgs/tools/filesystems/securefs { }
> ```
> 
> in all-packages.nix. But the app still doesn't start then because of:
> 
> ```
> dyld[18747]: Library not loaded: /usr/local/lib/libfuse.2.dylib
>   Referenced from: /nix/store/39lzarsp58z2xyl9kyp8blgq70pklhli-securefs-0.13.0/bin/securefs
>   Reason: tried: '/usr/local/lib/libfuse.2.dylib' (no such file), '/usr/lib/libfuse.2.dylib' (no such file)
> [1]    18747 abort      ./result/bin/securefs --help
> ```
> 
> It needs some rpath / install_name rewriting.

That's expected, see https://github.com/NixOS/nixpkgs/blob/master/doc/builders/packages/fuse.section.md#fuse-sec-fuse.

**Comment by wegank** [comment]
Superseded by #227032.

**Pull request closed without merging**
