### PR TITLE
Moving llvm 3.5.0 to llvm 3.5.2

### PR DESCRIPTION
**Pull request by spacekitteh**
Moving 3.5.0 to 3.5.2. I fixed Polly, by the way. And I commented out dragonegg, because it's screwed for 3.4 and 3.5.

### CODE REVIEW

**Comment by spacekitteh** [comment]
(the build failed due to out of memory on the CI box)

**Comment by spacekitteh** [comment]
Fixed polly!

**Comment by spacekitteh** [comment]
again, the build failure is due to an OOM error on the build box :)

**Comment by spacekitteh** [comment]
Dragonegg fails to compile with gcc 4.9. This is a bug in dragonegg itself. Trying to figure out how to get it to compile with gcc5 (or if that doesn't work, 4.8)

**Comment by spacekitteh** [comment]
Couldn't figure out a fix so I commented it out. It should be fixed in 3.6 anyway.

**Comment by spacekitteh** [comment]
All build failures are pre-existing failures, by the way

**Comment by MP2E** [comment]
Merged as of 2e416464419f9462b2f55375ce8b9199b843f136

Note that DragonEgg is not building at the moment, but it's a bug upstream. Since this is a relatively low profile project, I opted to let it break, for the moment.

**Pull request closed without merging**
