### PR TITLE
qt59: 5.9.3 -> 5.9.7

### PR DESCRIPTION
**Pull request by FlorianFranzen**
###### Motivation for this change

Updates Qt 5.9.3 to 5.9.7

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build qt59.full
@GrahamcOfBorg build qt59.qmake
@GrahamcOfBorg build qt59.qtbase
@GrahamcOfBorg build qt59.qtcharts
@GrahamcOfBorg build qt59.qtconnectivity
@GrahamcOfBorg build qt59.qtdeclarative
@GrahamcOfBorg build qt59.qtdoc
@GrahamcOfBorg build qt59.qtgraphicaleffects
@GrahamcOfBorg build qt59.qtimageformats
@GrahamcOfBorg build qt59.qtlocation
@GrahamcOfBorg build qt59.qtmacextras
@GrahamcOfBorg build qt59.qtmultimedia
@GrahamcOfBorg build qt59.qtquickcontrols
@GrahamcOfBorg build qt59.qtquickcontrols2
@GrahamcOfBorg build qt59.qtscript
@GrahamcOfBorg build qt59.qtsensors
@GrahamcOfBorg build qt59.qtserialport
@GrahamcOfBorg build qt59.qtsvg
@GrahamcOfBorg build qt59.qttools
@GrahamcOfBorg build qt59.qttranslations
@GrahamcOfBorg build qt59.qtvirtualkeyboard
@GrahamcOfBorg build qt59.qtwayland
@GrahamcOfBorg build qt59.qtwebchannel
@GrahamcOfBorg build qt59.qtwebengine
@GrahamcOfBorg build qt59.qtwebkit
@GrahamcOfBorg build qt59.qtwebsockets
@GrahamcOfBorg build qt59.qtx11extras
@GrahamcOfBorg build qt59.qtxmlpatterns

**Comment by veprbl** [comment]
@GrahamcOfBorg build qt59.full
@GrahamcOfBorg build qt59.qmake
@GrahamcOfBorg build qt59.qtbase
@GrahamcOfBorg build qt59.qtcharts
@GrahamcOfBorg build qt59.qtconnectivity
@GrahamcOfBorg build qt59.qtdeclarative
@GrahamcOfBorg build qt59.qtdoc
@GrahamcOfBorg build qt59.qtgraphicaleffects
@GrahamcOfBorg build qt59.qtimageformats
@GrahamcOfBorg build qt59.qtlocation
@GrahamcOfBorg build qt59.qtmacextras
@GrahamcOfBorg build qt59.qtmultimedia
@GrahamcOfBorg build qt59.qtquickcontrols
@GrahamcOfBorg build qt59.qtquickcontrols2
@GrahamcOfBorg build qt59.qtscript
@GrahamcOfBorg build qt59.qtsensors
@GrahamcOfBorg build qt59.qtserialport
@GrahamcOfBorg build qt59.qtsvg
@GrahamcOfBorg build qt59.qttools
@GrahamcOfBorg build qt59.qttranslations
@GrahamcOfBorg build qt59.qtvirtualkeyboard
@GrahamcOfBorg build qt59.qtwayland
@GrahamcOfBorg build qt59.qtwebchannel
@GrahamcOfBorg build qt59.qtwebengine
@GrahamcOfBorg build qt59.qtwebkit
@GrahamcOfBorg build qt59.qtwebsockets
@GrahamcOfBorg build qt59.qtx11extras
@GrahamcOfBorg build qt59.qtxmlpatterns

**Comment by FlorianFranzen** [comment]
@veprbl Thanks, good catch. It seems to build on Darwin now as well. Looks like a few build workers reset though.

**Comment by veprbl** [comment]
I ran nix-review on linux, the only failure is csound-qt, but it's not due to this PR: https://hydra.nixos.org/job/nixpkgs/trunk/csound-qt.x86_64-linux/all?page=1

**Comment by veprbl** [comment]
Ok, let's merge. I will take a look again once hydra updates the cache.

**Comment by veprbl** [comment]
One build failure so far complains about the hash of a tarball:
https://hydra.nixos.org/build/88060633
This is fine when I do it locally and it was fine when ofborg built it. Will wait to see if it goes away.

**Comment by veprbl** [comment]
In light of #54986 this needs to be backported

**Pull request merged**
