### PR TITLE
nginxModules: update and add nginx modules

### PR DESCRIPTION
**Pull request by Izorkin**
Update nginx modules:
- http_proxy_connect_module to 16.04.2019
- dav to 3.0.0
- lua to 0.10.14
- upstream-check to 12.08.2018
- upstream-tarantool to 2.7.1
- subsFilter to 13.04.2016

Added nginx modules:
- live 18.11.2018
- mpeg-ts 0.1.1
- coolkit 0.2
- slowfs-cache 1.10
- limit-speed 21.05.2014
- sorted-querystring 0.3
- video-thumbextractor 0.9.0
- naxsi 0.56

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Izorkin** [comment]
@GrahamcOfBorg build nginxMainline
@GrahamcOfBorg test nginx

**Comment by Izorkin** [comment]
cc @Mic92

**Comment by c0bw3b** [comment]
@Izorkin it looks like `nginxModules.dav` update broke the build of `tengine`
See: https://hydra.nixos.org/build/93598570 (first failing build on x86_64)

**Comment by Izorkin** [comment]
@c0bw3b thanks. Update - https://github.com/NixOS/nixpkgs/pull/61907

**Pull request merged**
