### PR TITLE
treewide: Default openssl version to 3.0

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

Newer version and kTLS finally.

I'll be adding a changelog entry when this is close to being merged because I don't want to resolve conflicts every 2 days ;)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
To activate kTLS support in openssl, need to add this changes:
```
diff --git a/pkgs/development/libraries/openssl/default.nix b/pkgs/development/libraries/openssl/default.nix
index ca2e240dd869f..b8cd042cb3012 100644
--- a/pkgs/development/libraries/openssl/default.nix
+++ b/pkgs/development/libraries/openssl/default.nix
@@ -108,6 +108,7 @@ let
       "-DUSE_CRYPTODEV_DIGESTS"
     ] ++ lib.optional enableSSL2 "enable-ssl2"
       ++ lib.optional enableSSL3 "enable-ssl3"
+      ++ lib.optional (versionAtLeast version "3.0.0") "enable-ktls"
       ++ lib.optional (versionAtLeast version "1.1.0" && stdenv.hostPlatform.isAarch64) "no-afalgeng"
       # OpenSSL needs a specific `no-shared` configure flag.
       # See https://wiki.openssl.org/index.php/Compilation_and_Installation#Configure_Options
```
Added on this PR - #147027

**Comment by vcunat** [comment]
Jobset: https://hydra.nixos.org/jobset/nixpkgs/pr-150093

**Comment by vcunat** [comment]
I now switched the jobset to `x86_64-linux`, as `aarch64-linux` has been very busy this week.

**Comment by ajs124** [comment]
Thanks for letting me know. I might need both though, eventually. I saw at least one failure (https://hydra.nixos.org/build/178674654/nixlog/1) recently in that jobset that I could only reproduce myself on aarch64-linux, but that succeeded on x86_64-linux.

**Comment by vcunat** [comment]
OK, tell me when you think it's a good moment to add more platforms.

**Comment by ajs124** [comment]
> OK, tell me when you think it's a good moment to add more platforms.

I think we can go ahead and enable this for darwin as well. Probably for both x86_64 and aarch64. On Linux as well.

IMO this is mostly ready, although this is my first tree-wide change of this magnitude, so maybe I'm missing something.

**Comment by vcunat** [comment]
I added `*-darwin` now.

**Review by stigtsp — APPROVED** [review]
perlPackages changes LGTM

**Review by sternenseemann — APPROVED** [review]
Haskell changes are okay!

**Review by mweinelt — APPROVED** [review]
Python changes look reasonable. Thank you!

**Comment by SuperSandro2000** [comment]
This broke eval for node 18 

```
error: anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/ofborg-evaluator-5/pkgs/development/web/nodejs/v18.nix:1:1 called with unexpected argument 'openssl'
```

**Pull request merged**
