### PR TITLE
[20.03] mariadb: backport updates

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Backport updates to 20.03

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
cc @flokli

**Comment by Izorkin** [comment]
@GrahamcOfBorg build mariadb.client
@GrahamcOfBorg build mariadb.server
@GrahamcOfBorg test mysql

**Comment by flokli** [comment]
@Izorkin the PR was targeted against another branch, and now needs a rebase. I'm doing that now.

**Comment by flokli** [comment]
Did that now, also had to manually add the

> (cherry picked from commit …)

line usually created from the `git cherry-pick` `-x` parameter.

Pleas remember to always to backport cherrypicks with this parameter.

**Comment by Izorkin** [comment]
> Pleas remember to always to backport cherrypicks with this parameter.

Sorry, i will try not to forget.

**Review by aanderse — APPROVED** [review]

**Pull request merged**
