### PR TITLE
nix-software-center: init at 0.1.2

### PR DESCRIPTION
**Pull request by sund3RRR**
## Description of changes
[Nix-software-center](https://github.com/vlinkz/nix-software-center) is a graphical app store for Nix built with [libadwaita](https://gitlab.gnome.org/GNOME/libadwaita), [GTK4](https://www.gtk.org/), and [Relm4](https://relm4.org/). Heavily inspired by [GNOME Software](https://gitlab.gnome.org/GNOME/gnome-software).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Gerg-L** [comment]
Multiple IFD's this is packaged completely incorrectly

**Comment by Gerg-L** [comment]
> Multiple IFD's this is packaged completely incorrectly

Alright, it's mostly fixed now

**Comment by Nyabinary** [comment]
@vlinkz Would be nice to upstream it tbh

**Comment by Zahrun** [comment]
@vlinkz I really like your projects and I think they can become really good and appreciated, and make NixOS more accessible and enjoyable to use graphically. I was wondering what can boost the development, would it be monetary donations, more developers joining, or something else? What would be the best way to support you?

**Comment by vlinkz** [comment]
> @vlinkz Would be nice to upstream it tbh

> @vlinkz I really like your projects and I think they can become really good and appreciated, and make NixOS more accessible and enjoyable to use graphically. I was wondering what can boost the development, would it be monetary donations, more developers joining, or something else? What would be the best way to support you?

I think really I just need to spend more time finishing it and making sure it's stable. On the topic of boosting development, if more developers were interested in finishing it up, that would likely make things go faster. Monetarily I'm doing fine, so that's not needed. Just have my time spread pretty thin through projects and life.

**Pull request closed without merging**
