### PR TITLE
saxon-he: 9.9.0.1 -> 11.5

### PR DESCRIPTION
**Pull request by avi-jois**
Update the default version of saxon-he to 11.5.
Create a new saxon_9-he package for compatibility.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 219753` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>saxon-he</li>
    <li>saxon_9-he</li>
  </ul>
</details>

**Review by pbsds — APPROVED** [review]

**Review by rvl — APPROVED** [review]
##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines - not the latest release anymore
- [x] package build on x86_64-linux - yes
- [x] executables tested on x86_64-linux - tested bin/saxon-he (`net.sf.saxon.Transform`) and also `net.sf.saxon.Query`.
- [x] all depending packages build - N/A
- [x] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed - N/A
- [x] patches that are remotely available are fetched rather than vendored - N/A

##### Possible improvements

Would it be possible to update again to [Saxon-HE 11.6](https://github.com/Saxonica/Saxon-HE/releases/tag/SaxonHE11-6)?

##### Comments

Thanks

**Comment by emilytrau** [comment]
Result of `nixpkgs-review pr 219753` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>saxon-he</li>
    <li>saxon_9-he</li>
  </ul>
</details>

**Review by emilytrau — APPROVED** [review]
Apologies for the delay. Thank you for your contribution!

**Pull request merged**
