### PR TITLE
dockerTools: Add fakechroot to fakeRootCommands

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

Make installation scripts work unmodified in `fakeRootCommands`, by making programs behave like the image root is `/`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
@ofborg test docker-tools

**Comment by roberth** [comment]
cc @vroad as contributor of the `fakeroot` change.

**Comment by utdemir** [comment]
@roberth It does look like a minimal change to me, but unfortunately I do not know much about chroot or fakeroot, so I think someone else (maybe @vroad) would be a better reviewer.

**Comment by vroad** [comment]
@roberth @utdemir Unfortunately I don't know much about fakeroot or fakechroot either, I tried fakeroot for the first time in my previous PR just because it was exactly what I have been looking for solving my issue (file owner issue).

**Comment by roberth** [comment]
Fair enough. I've disabled it by default, so the change is entirely opt-in. I'll merge it so we can gain some experience over time.

**Pull request merged**
