### PR TITLE
(attempt to debug libarchive tests on ofborg)

### PR DESCRIPTION
**Pull request by risicle**
(please ignore)

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg build libarchive

**Comment by risicle** [comment]
@ofborg build libarchive

(this may be faster)

**Comment by risicle** [comment]
@ofborg build libarchive

maybe not

**Comment by risicle** [comment]
@ofborg build libarchive

**Comment by risicle** [comment]
@uri-canva did you get the failure on your own machine or just ofborg?

**Comment by uri-canva** [comment]
I got a failure on my `x86_64-darwin` laptop.

**Comment by uri-canva** [comment]
If it helps:

 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixpkgs"`
 - channels(uri): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by risicle** [comment]
Are you able to reproduce it and get the contents of that `bsdcpio_test.<timestamp>` file?

**Comment by uri-canva** [comment]
I can try, how do I do that? I assume there's some flags I pass to keep the temporary files around?

**Comment by uri-canva** [comment]
Testing on `cbdf1f436c9ed50fa12e6473892fc7f07f80fafd`, running `nix-build -A curl` like before in the meantime, I had garbage collected so I need to build everything again, I'll be back later, give me as precise instructions as you can please, I'm not super familiar with how to debug these kinds of failures.

**Comment by risicle** [comment]
`nix-build -K` will keep the temporary file around.

**Comment by uri-canva** [comment]
```
test_option_a

cpio/test/test_option_a.c:150: st.st_atime != files[3].atime_sec
   Description: Copying file with -a should not have changed atime.
      st.st_atime=1651446884 (0x626f1464, 014233612144)
      files[3].atime_sec=1 (0x1, 01)
cpio/test/test_option_a.c:159: st.st_atime != files[4].atime_sec
   Description: Archiving file with -a should not have changed atime.
      st.st_atime=1651446884 (0x626f1464, 014233612144)
      files[4].atime_sec=1 (0x1, 01)
```

**Comment by uri-canva** [comment]
```
> ls -lR /private/tmp/nix-build-libarchive-3.6.1.drv-0/bsdcpio_test.2022-05-01T23.14.25-000/test_option_a/
total 96
-rw-r--r--  1 _nixbld1  nixbld    8  2 May 09:14 archive-a.err
-rw-r--r--  1 _nixbld1  nixbld  512  2 May 09:14 archive-a.out
-rw-r--r--  1 _nixbld1  nixbld    8  2 May 09:14 archive-no-a.err
-rw-r--r--  1 _nixbld1  nixbld  512  2 May 09:14 archive-no-a.out
drwxr-xr-x  3 _nixbld1  nixbld   96  2 May 09:14 copy-a/
-rw-r--r--  1 _nixbld1  nixbld    8  2 May 09:14 copy-a.err
-rw-r--r--  1 _nixbld1  nixbld    0  2 May 09:14 copy-a.out
drwxr-xr-x  3 _nixbld1  nixbld   96  2 May 09:14 copy-no-a/
-rw-r--r--  1 _nixbld1  nixbld    8  2 May 09:14 copy-no-a.err
-rw-r--r--  1 _nixbld1  nixbld    0  2 May 09:14 copy-no-a.out
-rw-r--r--  1 _nixbld1  nixbld    1  1 Jan  1970 f0
-rw-r--r--  1 _nixbld1  nixbld    1  1 Jan  1970 f1
-rw-r--r--  1 _nixbld1  nixbld    1  1 Jan  1970 f2
-rw-r--r--  1 _nixbld1  nixbld    1  1 Jan  1970 f3
-rw-r--r--  1 _nixbld1  nixbld    1  1 Jan  1970 f4
-rw-r--r--  1 _nixbld1  nixbld    1  1 Jan  1970 f5

/private/tmp/nix-build-libarchive-3.6.1.drv-0/bsdcpio_test.2022-05-01T23.14.25-000/test_option_a//copy-a:
total 8
-rw-r--r--  1 _nixbld1  nixbld  1  2 May 09:14 f3

/private/tmp/nix-build-libarchive-3.6.1.drv-0/bsdcpio_test.2022-05-01T23.14.25-000/test_option_a//copy-no-a:
total 8
-rw-r--r--  1 _nixbld1  nixbld  1  2 May 09:14 f1
```

**Comment by risicle** [comment]
Interesting, because @lovek323's failure is actually in `test_option_t` https://github.com/NixOS/nixpkgs/pull/170654#issuecomment-1113919277

**Comment by uri-canva** [comment]
Interesting, no, that one passes for me:
```
PASS: bsdcat_test
FAIL: bsdcpio_test
PASS: bsdtar_test
PASS: libarchive_test
========================================
   libarchive 3.6.1: ./test-suite.log
========================================

# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: bsdcpio_test
==================


If tests fail or crash, details will be in:
   /private/tmp/nix-build-libarchive-3.6.1.drv-0/bsdcpio_test.2022-05-01T23.14.25-000

Reference files will be read from: /private/tmp/nix-build-libarchive-3.6.1.drv-0/source/cpio/test
Running tests on: "/private/tmp/nix-build-libarchive-3.6.1.drv-0/source/bsdcpio"
Exercising: bsdcpio 3.6.1 - libarchive 3.6.1 zlib/1.2.12 liblzma/5.2.5 bz2lib/1.0.6 libzstd/1.5.2

  0: test_0                                                          ok
  1: test_basic                                                      ok
  2: test_cmdline                                                    ok
  3: test_extract_cpio_Z                                             ok
  4: test_extract_cpio_bz2                                           ok
  5: test_extract_cpio_grz                                           ok (S)
  6: test_extract_cpio_gz                                            ok
  7: test_extract_cpio_lrz                                           ok (S)
  8: test_extract_cpio_lz                                            ok
  9: test_extract_cpio_lz4                                           ok (S)
 10: test_extract_cpio_lzma                                          ok
 11: test_extract_cpio_lzo                                           ok (S)
 12: test_extract_cpio_xz                                            ok
 13: test_extract_cpio_zstd                                          ok
 14: test_format_newc                                                ok
 15: test_gcpio_compat                                               ok
 16: test_missing_file                                               ok
 17: test_option_0                                                   ok
 18: test_option_B_upper                                             ok
 19: test_option_C_upper                                             ok
 20: test_option_J_upper                                             ok
 21: test_option_L_upper                                             ok
 22: test_option_Z_upper                                             ok
 23: test_option_a                                                   FAIL
 24: test_option_b64encode                                           ok
 25: test_option_c                                                   ok
 26: test_option_d                                                   ok
 27: test_option_f                                                   ok
 28: test_option_grzip                                               ok (S)
 29: test_option_help                                                ok
 30: test_option_l                                                   ok
 31: test_option_lrzip                                               ok (S)
 32: test_option_lz4                                                 ok (S)
 33: test_option_lzma                                                ok
 34: test_option_lzop                                                ok (S)
 35: test_option_m                                                   ok
 36: test_option_passphrase                                          ok
 37: test_option_t                                                   ok
 38: test_option_u                                                   ok
 39: test_option_uuencode                                            ok
 40: test_option_version                                             ok
 41: test_option_xz                                                  ok
 42: test_option_y                                                   ok
 43: test_option_z                                                   ok
 44: test_option_zstd                                                ok
 45: test_owner_parse                                                ok
 46: test_passthrough_dotdot                                         ok
 47: test_passthrough_reverse                                        ok

Totals:
  Tests run:               48
  Tests failed:             1
  Assertions checked:   16365
  Assertions failed:        2
  Skips reported:           8

Failing tests:
  23: test_option_a (2 failures)

Details for failing tests: /private/tmp/nix-build-libarchive-3.6.1.drv-0/bsdcpio_test.2022-05-01T23.14.25-000

FAIL bsdcpio_test (exit status: 1)

============================================================================
Testsuite summary for libarchive 3.6.1
============================================================================
# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to libarchive-discuss@googlegroups.com
============================================================================
```

**Comment by lovek323** [comment]
I'm happy to help out here, see if I get a different failure. Should I run a build on this PR?

**Comment by risicle** [comment]
It occurs to me that these are likely both file-access-time related failures, and are probably quite vulnerable to systems which e.g. have anti-virus or other background services which scan newly-created files, thus altering their `atime`. Should probably just disable them on darwin.

**Comment by uri-canva** [comment]
Tested it on a laptop that doesn't have such processes and can confirm it builds correctly.

**Pull request closed without merging**
