### PR TITLE
git-cola: update dependencies and make it work in darwin

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Description of changes

- `pyinotify` was removed a long time ago: https://github.com/git-cola/git-cola/pull/510
- `sip_4` does not seem to be needed, at least there is no mention at docs and the program seems to works fine without it
- `send2trash` added since it is an optional feature: https://github.com/git-cola/git-cola#optional-features

The removal of `pyinotify` also makes this build and works in darwin, so removing the `meta.platforms` (will inherit from `buildPythonApplication` instead).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
CC @wegank.

**Review by wegank — APPROVED** [review]

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 218818` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>git-cola</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Added tests so we can ensure this package will not be broken in the future.

CC @wegank.

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 218818` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>git-cola</li>
  </ul>
</details>

**Review by bobvanderlinden — APPROVED** [review]
Thanks for the PR! Quite a few improvements over what was already there. Darwin support is bonus for me :+1:

Tested this locally on NixOS x86_64 and git-cola works fine :+1:

**Pull request merged**
