### PR TITLE
Update python-dateutil 2.6.1 -> 2.7.3

### PR DESCRIPTION
**Pull request by pacien**
###### Motivation for this change
Various bugfixes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Please rebase this PR on the `staging` branch since it causes >22k rebuild.

**Comment by FRidh** [comment]
Bumps of this package typically cause quite some breakage, so don't merge. This needs more investigation.

**Comment by pacien** [comment]
The PR has been rebased.

Version 2.7.x ([changelog](https://github.com/dateutil/dateutil/blob/2.7.3/NEWS#L97)) most notably drops support for Python 2.6 and 3.2, whereas versions 2.7 and 3.6 are used in NixOS. Other changes mostly consist of bug fixes, feature addition and a few deprecation. I hope this doesn't break other packages.

As a side note, updating this library would enable the resolution of some issues in other packages like [this one](https://github.com/Kozea/Radicale/issues/646).

**Comment by pacien** [comment]
Seems like this breaks a test in the `vobject` package.

**Comment by FRidh** [comment]
I've included the changes in https://github.com/NixOS/nixpkgs/pull/41894.

**Pull request closed without merging**
