### PR TITLE
Emacs packages

### PR DESCRIPTION
**Pull request by ttuegel**
- Update `elpaPackages`
- Add `melpaStablePackages` and `melpaPackages` to `emacsPackagesNg`. Adds about 1500 packages.

Relevant issue: #11503 
Interested parties: @oxij @gridaphobe

Not for merging yet, I want to see what Travis says.

### CODE REVIEW

**Comment by gridaphobe** [comment]
Very exciting! Can we add the script that generates the json files to `maintainers/scripts` too?

**Comment by ttuegel** [comment]
The scripts are provided in my [emacs2nix](https://github.com/ttuegel/emacs2nix) repository. I'm unsure of the best way to bundle them into Nixpkgs because you really need a clone of that repository to build them.

**Comment by ttuegel** [comment]
I expect many of these packages will be broken due to problems upstream. I will mark them broken for Hydra once we make that determination.

**Comment by ttuegel** [comment]
Travis appears to confirm my suspicion re: breakage, i.e. it looks like upstream problems to me. I think it's ready to throw at Hydra!

**Comment by jgeerds** [comment]
Thank you very much for your work @ttuegel !

**Comment by gridaphobe** [comment]
@ttuegel the error that travis reports (https://travis-ci.org/NixOS/nixpkgs/builds/97048155#L7803) does not look like an upstream issue to me, it looks like one of the derivations contains the wrong hash for the git commit.

**Comment by ttuegel** [comment]
@gridaphobe I suspect that somebody upstream did `git push -f`, but I will double-check before I commit anything.

**Comment by gridaphobe** [comment]
I wondered about that, but this appears to be checking out a specific commit rather than a tag, so `git push -f` ought to have invalidated the commit itself.

**Comment by ttuegel** [comment]
Hm, you're right, I didn't think that through enough. It turns out that `fetchgit` uses `fetchSubmodules = true` by default, but `melpa2nix` wasn't generating the hashes with that option to `nix-prefetch-git`. I will have to regenerate those packages.

**Comment by oxij** [comment]
Yay, awesome! Thank you!

Nitpicks:

* Descriptive commit messages and some comments (at least in the headers
  of files so that people would get the idea what they're looking at)
  there would be nice to have.

* `pkgs/applications/editors/emacs-modes/*.nix` files beg to be
  rewritten into special cases of a single generic thing.

* With `pkgs: with pkgs;` in their headers it's hard to tell what do
  they actually depend on, isn't it just `lib`?

And the main questions:

* How does one to override `emacs` with this?
* You override package sets with each other, but wouldn't it make sense
  to allow the access to all the sets?

I mean, it seems to me that we should move `elpaPackages`,
`melpaStablePackages` and `melpaPackages` into a kind of
`emacsPackagesNgGen` so that they get their `emacs` from it, e.g.:

  # this is modelled after Haskell's GHC versions a little
  emacsPackageSetsGen =  emacs: {
    inherit emacs; # ! I think it should just go here, instead of being an argument for everything else
    
    nix = callPackage ./emacs-packages.nix { ... };
    elpa = { ... };
    melpa-stable = { ... };
    melpa = { ... };
  };

  emacsPackageSets = emacsPackageSetsGen emacs;

  # All this does is generate a single (preferably, consistent) package
  # set. It can be inlined and beta-reduced into the next definition,
  # but maybe it has it's own uses. Probably not.
  emacsPackagesNgGen = sets: ... all the default override business goes here ...;

  emacsPackagesNg = emacsPackagesNgGen emacsPackageSets;

  emacsWithPackagesGen = eset: ... something something eset something ... ;

  # The main thing
  emacsWithPackages = emacsWithPackagesGen emacsPackagesNg;

which has a nice side effect that you can get different `emacs` configs
(e.g. "all-stable", "all-unstable") with a single expression using
`emacsWithPackages` by overriding that `eset` thing. E.g. we can
actually provide some with nixpkgs:

  # The same comment applies
  emacsPackagesUnstableNgGen = sets: ... all the override business goes here, but in reverse order ...;

  emacsPackagesUnstableNg = emacsPackagesUnstableNgGen emacsPackageSets;

  emacsWithUnstablePackages = emacsWithPackagesGen emacsPackagesUnstableNg;

and overriding `emacs` globally would be as easy as overriding either
`emacs` derivation or `emacsPackageSets`.

Also, maybe we should rename `*Gen` into `*Fun`, since that seems to be
much more frequent convention now.

**Comment by ttuegel** [comment]
> How does one to override `emacs` with this?

`emacsPackagesNg.override { emacs = ...; }`

> You override package sets with each other, but wouldn't it make sense to allow the access to all the sets?

I'm not sure about this; Emacs won't allow multiple versions of a package in the same environment, i.e. we need to have a single, coherent set of dependencies for all Emacs packages (per Emacs version, anyway).

> I mean, it seems to me that we should move `elpaPackages`, `melpaStablePackages` and `melpaPackages` into a kind of `emacsPackagesNgGen` so that they get their `emacs` from it

This statement confuses me; the reason I merged all the sets into one was so they would have a single, coherent set of dependencies, including `emacs`.

**Comment by ttuegel** [comment]
> Also, maybe we should rename `*Gen` into `*Fun`, since that seems to be much more frequent convention now.

I forgot to mention, because `emacsPackagesNgGen` uses `makeScope` now, there's no reason for it to be a function of `emacs`. We can just have `emacsPackagesNg` as a plain set because overriding `emacs` overrides that dependency for all packages.

**Comment by ttuegel** [comment]
OK, the Travis build is failing now due to the log running too long, i.e. it really is spurious.

**Comment by oxij** [comment]
Thomas Tuegel <notifications@github.com> writes:

>> How does one to override `emacs` with this?
>
> `emacsPackagesNg.override { emacs = ...; }`

Well, yes, but then, fix me if I'm wrong here, suppose I want a package
from unstable MELPA in my `emacsWithPackages`. I'll need to override
`emacsWithPackages`, `emacsPackagesNg`, and `melpaPackages` together to
get my

  emacsWithPackages (with emacsPackagesNg; with melpaPackages; [
    ...
    the_package
    ...
  ])

Won't I? (like in #10811) This is not going to be pretty. Where as with
my code above overriding one `emacsPackageSets` thing would do.

(It's also just struck me that one can put `emacsWithPackages` into
`emacsPackageSetsGen` thing, so that one could have other permutations
of package versions by supplying a single function that generates a
scope of packages from { nix, elpa, melpa, melpa-stable } attrset).

>> You override package sets with each other, but wouldn't it make sense to allow the access to all the sets?
>
> I'm not sure about this; Emacs won't allow multiple versions of a package in the same environment, i.e. we need to have a single, coherent set of dependencies for all Emacs packages (per Emacs version, anyway).

1) `emacsPackagesNgGen` idea in my code above addresses this, I think.
2) You can't guarantee that the user won't add one manually into the
   environment there anyway, so it should be user's responsibility.

>> I mean, it seems to me that we should move `elpaPackages`, `melpaStablePackages` and `melpaPackages` into a kind of `emacsPackagesNgGen` so that they get their `emacs` from it
>
> This statement confuses me; the reason I merged all the sets into one was so they would have a single, coherent set of dependencies, including `emacs`.

I mean, like in `emacsPackageSetsGen` in my code above.

In one sentence my concern is this: I don't like that `elpaPackages`,
`melpaPackages`, and `melpaStablePackages` are top-level attributes, as
you'll have to override all of them together which means that having two
different `emacsWithPackages` with one nixpkgs config would be painful
(and in the previous message and in this message above I proposed a
simple way to fix this).

**Comment by ttuegel** [comment]
> Well, yes, but then, fix me if I'm wrong here, suppose I want a package from unstable MELPA in my `emacsWithPackages`. I'll need to override `emacsWithPackages`, `emacsPackagesNg`, and `melpaPackages` together

Like you suggested, it would be convenient to have `emacsWithPackages` be in the set `emacsPackageNg`, so let's assume I've already done that.

All you need to do to override a package is:
```
emacsPackagesNg.override (self: {
  # Suppose the stable version of foo from ELPA is used by default
  foo = self.melpaPackages.foo;
  # By default, the "most stable" version of a package is chosen, 
  # but the original packages remain in `self.elpaPackages`, 
  # `self.melpaStablePackages`, and `self.melpaPackages`.
})
```
This would override that package everywhere that it's used as a dependency (so if `emacsWithPackages` is included in the set, that's overridden, too).

I think there is some confusion about what the top-level `melpaPackages` is. It's not something that you *can* override. It's just a function that inserts the MELPA packages into another package set. The consistency of dependencies is ensured by the fix-point trick.

> You can't guarantee that the user won't add one manually into the environment there anyway, so it should be user's responsibility.

No, the filesystem guarantees the user can't do that: the files will collide and they'll only get one version. It may not be the version that they want, but that's what they'll get. It should be on us to ensure (at least) that a pure `emacsWithPackages` environment is completely consistent.

> In one sentence my concern is this: I don't like that `elpaPackages`, `melpaPackages`, and `melpaStablePackages` are top-level attributes, as you'll have to override all of them together which means that having two different `emacsWithPackages` with one nixpkgs config would be painful (and in the previous message and in this message above I proposed a simple way to fix this).

What I'm getting from this is:
1. It's confusing that `elpaPackages` etc. are top-level attributes, since the user should never refer to them, and
1. Along with the previously proposed changes to `emacsWithPackages` (i.e. making it "know" its own package set), I should move it into `emacsPackagesNg`.

Should I remove `elpaPackages` etc. or rename them to `elpaPackagesFun`?

**Comment by ttuegel** [comment]
In that last commit, I modified how the package set is constructed slightly to make it clearer where all the packages are coming from and how the fix-point trick works.

**Comment by oxij** [comment]
> All you need to do to override a package is:
> ...

So, am I right to assume that after all those changes (including the
ones cited below)

  let
    em = emacsPackagesNg.override (self: {
      emacs = self.emacs.override { withX = false; }
      foo = self.melpaPackages.foo;
    });
  in em.emacsWithPackages (p: with p; [ foo ]);

will generate a derivation with a single `emacs` with `withX` option set
to `false` and `foo` package from unstable MELPA compiled with that
`emacs`?

> No, the filesystem guarantees the user can't do that: the files will collide and they'll only get one version. It may not be the version that they want, but that's what they'll get. It should be on us to ensure (at least) that a pure `emacsWithPackages` environment is completely consistent.

I agree on the latter point, but the former still holds, because at
least `melpaBuild` generates paths like
`share/emacs/site-lisp/elpa/anzu-0.52` which would not collide for
different versions.

> I think there is some confusion about what the top-level `melpaPackages` is. It's not something that you *can* override. It's just a function that inserts the MELPA packages into another package set. The consistency of dependencies is ensured by the fix-point trick.

Ah, okay.

> What I'm getting from this is:
>
> 1. It's confusing that `elpaPackages` etc. are top-level attributes, since the user should never refer to them, and

Yes!

> 1. Along with the previously proposed changes to `emacsWithPackages` (i.e. making it "know" its own package set), I should move it into `emacsPackagesNg`.

Yes.

> Should I remove `elpaPackages` etc. or rename them to `elpaPackagesFun`?

Unless there's an argument against it, I would prefer them to be
completely hidden into `emacsPackagesNg` so as not to confuse users (and
hydra). AFAICS, the majority of top-level `*Gen` and `*Fun` things in
`all-packages.nix` are to be used by users.

**Comment by ttuegel** [comment]
Your example is not quite right, it should be
```
let em = emacsPackagesNg.override (super: self: { 
      emacs = super.emacs.override { withX = false; };
      foo = self.melpaPackages.foo;
    });
in em.emacsWithPackages (p: with p; [ foo ])
```
The main difference is that the argument to `override` takes two arguments: `super` is the package set *before* overriding and `self` is the package set *after* the overrides are applied. The `emacs` attribute comes from `super.emacs.override` because `self.emacs.override` would recurse infinitely. This expression would do exactly what you described, though.

> the former still holds, because at least `melpaBuild` generates paths like `share/emacs/site-lisp/elpa/anzu-0.52` which would not collide for different versions.

That's right, I didn't think about that.

> Unless there's an argument against it, I would prefer them to be completely hidden into `emacsPackagesNg` so as not to confuse users (and hydra).

They won't bother Hydra because they are just functions, but I agree they should not be exposed.

**Comment by ttuegel** [comment]
I have added release notes and documentation for my changes. I have not documented the Emacs infrastructure in the manual yet because that is still in flux, but the parts I have added in this PR are documented in the source tree.

**Comment by ttuegel** [comment]
Rebased to fix some merge conflicts with the release notes. This is just waiting for final feedback.

**Comment by jgeerds** [comment]
I hope that I can test your changes tomorrow. I'm very excited

**Comment by oxij** [comment]
> Your example is not quite right, it should be
> ```
> let em = emacsPackagesNg.override (super: self: { 
>       emacs = super.emacs.override { withX = false; };
>       foo = self.melpaPackages.foo;
>     });
> in em.emacsWithPackages (p: with p; [ foo ])
> ```
> ...

I just modified your code above, but the super-way is even better. Will
test tomorrow, I hope.

**Comment by oxij** [comment]
Some problems I found till now:

1) Generated things require a lot more stuff to build. Why?

   Can be seen by introspecting the output of (in zsh syntax):

   $ diff -Nua <(nix-store -qR $(nix-store -q --deriver `nix-build -A emacsPackagesNg.anzu`) ) \
               <(nix-store -qR $(nix-store -q --deriver `nix-build -A emacsPackagesNg.melpaPackages.anzu`) )

   most of those seem to derive from Mozilla's nss:

   $ nix-store -q --requisites /nix/store/*-nss-cacert-3.21.drv

2) Generated things do `fetchgit` where `fetchFromGitHub` is
   possible, which is considerably slower.

3) There seem to be some confusion with `fetchgit`, e.g.:

   $ nix-build -A emacsPackagesNg.melpaPackages.helm
   these derivations will be built:
     /nix/store/y8mgyk0wnhpnkd4n45bkcxrp6w30ax48-helm-97e8ffa.drv
     /nix/store/506xl9ddr92kx6pqbhrwc16g8zihnnzj-emacs-helm-core-1.9.0.drv
     /nix/store/f8hkxsz9175nwxspmj024m1dpb5i6rkk-emacs-helm-1.9.0.drv
   building path(s) ‘/nix/store/di46ixjqf8pa61c4in3d15zxxkb6yns5-helm-97e8ffa’
   exporting git://github.com/emacs-helm/helm.git (rev 97e8ffaed3c5959e9c16e7a0e45cc0702218b2cc) into /nix/store/di46ixjqf8pa61c4in3d15zxxkb6yns5-helm-97e8ffa
   Initialized empty Git repository in /nix/store/di46ixjqf8pa61c4in3d15zxxkb6yns5-helm-97e8ffa/.git/
   fatal: Invalid refspec '+refs/tags/v1.9.0^{}'

   it then continues the fetch, but this error seems suspicious.

**Comment by ttuegel** [comment]
> most of those seem to derive from Mozilla's nss

I think it may actually be due to the inclusion of git, which seems to need Perl stuff and certificates; I think the latter is where we get nss.

> Generated things do `fetchgit` where `fetchFromGitHub` is possible, which is considerably slower.

In the past, I've had a lot of trouble hashing things for `fetchFromGitHub` because there is no `nix-prefetch-from-github`. I will look into this again, because it seems to hurt us in two places (download speed and closure size).

**Comment by ttuegel** [comment]
For the benefit of future readers, I find that
```
diff -Nua <(nix-store -qR $(nix-instantiate -A emacsPackagesNg.anzu) | sort) <(nix-store -qR $(nix-instantiate -A emacsPackagesNg.melpaPackages.anzu) | sort)
```
gives a better picture of the difference between `buildInputs`.

**Comment by ttuegel** [comment]
OK, I have removed as many of the uses of `fetchgit` as I can. I think the only way forward with this now is to expose it to wider testing.

**Comment by domenkozar** [comment]
Quite a lot of emacs packages are failing http://hydra.nixos.org/eval/1234291?full=1

**Comment by ttuegel** [comment]
Yes, I just pushed a fix for some typos; that should fix many of the failures. There are a few failures due to upstream problems; those will need to be tracked down by hand. The rest are from outdated dependencies; for that, we need to remove our hand-written Emacs packages. We've been discussing this at #11503.

**Comment by domenkozar** [comment]
Thanks!

**Pull request merged**
