### PR TITLE
Jenkins enhancement

### PR DESCRIPTION
**Pull request by aborsu**
Added jenkins http bind port option and prefix option. Creating options instead of relying on extra arguments allows to use these options in jenkins-job-builder (Using a prefix meant it stopped working.)
Also we could use this to create a reverse proxy service for apache, nginx, and (name any proxy capable server you want).

### CODE REVIEW

**Comment by bjornfor** [comment]
Good idea!

**Comment by bjornfor** [comment]
Would it be less confusing if ```host``` was renamed to ```listenAddress```? (It's not like host can be _any_ host, just an address on the local machine.)

**Comment by garbas** [comment]
@bjornfor sorry i've already merged before seeing you comment. 

do we use listenAddress in other modules? ``host`` was good enough name for me.
you still want to change it?

**Comment by bjornfor** [comment]
_I_ would like to change the name. But I'd like to hear other peoples thoughts.

I guess the more important / immediate issue is what happens when curl tries to connect to 0.0.0.0? (That won't work, would it?)

**Comment by bjornfor** [comment]
@garbas: Yes, we have some use of listenAddress in other modules:

```
$ git grep -l "listenAddress" nixos/modules
nixos/modules/services/amqp/rabbitmq.nix
nixos/modules/services/databases/4store-endpoint.nix
nixos/modules/services/databases/virtuoso.nix
nixos/modules/services/monitoring/bosun.nix
nixos/modules/services/networking/git-daemon.nix
nixos/modules/services/networking/notbit.nix
nixos/modules/services/networking/privoxy.nix
nixos/modules/services/networking/ssh/sshd.nix
nixos/modules/services/printing/cupsd.nix
nixos/modules/services/security/hologram.nix
```

There are many more ```host``` options than ```listenAddress``` in nixos, but I think host is mostly used for "the address a client should connect to". (I didn't manually check all options.)

**Comment by aborsu** [comment]
Ok, as we are on the subject of naming, i created the prefix option as it's the name used by jenkins but most apache submodules actually use urlPrefix. Should we change that as well?
Also should I change the names in my code or should I make another pull request since some if it is merged?

**Comment by aborsu** [comment]
@bjornfor I didn't have any problems with a curl to 0.0.0.0
I'm not a network expert but using the broadcast adress means it might be sent out to the network. I'm not sure.

**Comment by aborsu** [comment]
I was browsing around, I saw [this](https://github.com/NixOS/nixpkgs/blob/release-15.09/nixos/modules/services/misc/gitlab.nix#L129).
It might solve both the host variable name question and the 0.0.0.0 issue.

**Comment by bjornfor** [comment]
urlPrefix and prefix sound like same semantics. host and listenAddress do not (IMHO).

I'm no network expert either. Surprised that curl 0.0.0.0 worked :-)

I'll rename host to listenAddress when I get back to my computer, if no objections.

**Comment by garbas** [comment]
will you also rename other occurrences of ``host``? :)

what i care most is consistency. if we choose the name ``listenAddress`` then lets fix it across all modules. if we chose ``host`` then lets change to that. but not having both.

**Comment by bjornfor** [comment]
Ok. I'll try to make a PR for the existing uses, because they require option renaming and I might make mistakes. This one I think is OK to change in place.

**Comment by bjornfor** [comment]
Changed in c6b251f5d549f8d3dd877d0b086ae4f876bc5a2b. (And fixed a typo in b2d0886b37bc7a927c98a15430b3be3cbc4f81f7.)

Hm, there are several modules (and the programs they represent) that use "host" as a listening address. I mean, some modules define "host" and then pass it to the program like "bind_address = ${cfg.host}", but other programs use "host" themself in the CLI or configuration file. I'm not sure how strict we should be in converting "host" to "listenAddress" now :-/

**Comment by bjornfor** [comment]
I do like standard interfaces though (i.e. listenAddress for everything that is used for bind/listen) :-D

**Pull request closed without merging**
