### PR TITLE
Revert "vimPlugins.nvim-treesitter: collate grammars"

### LINKED ISSUE #341442: nvim-treesitter not linking grammars
### Describe the bug

I noticed that nvim wasn't loading any of my treesitter plugins. I decided to check the plugin directory.

```
$ nix build 'nixpkgs#vimPlugins.nvim-treesitter.withAllGrammars' --no-link --print-out-paths
/nix/store/8iwi6pzi9690yl1l0dv3r497hml7zylf-vimplugin-nvim-treesitter-2024-08-04

$ nix path-info --recursive /nix/store/8iwi6pzi9690yl1l0dv3r497hml7zylf-vimplugin-nvim-treesitter-2024-08-04
/nix/store/cjnmdi9chk0fhjy8p8dq8inxqr4p3vk7-libunistring-1.2
/nix/store/04hj9k1gyv26b9gdmcmw3l3bbi124xxi-libidn2-2.3.7
/nix/store/3ilxy06yvz70vg6ld86kyjr6qb248vd6-gcc-13.3.0-libgcc
/nix/store/mrsnnz2nmnb4mrma1bfv6inmy2k3k3k8-xgcc-13.3.0-libgcc
/nix/store/wlffq5p6mxxgfap10sav3ij936jzqm59-glibc-2.39-52
/nix/store/zx9zgvy2nsxcmpn0fzx277m5lk352cdf-gcc-13.3.0-lib
/nix/store/cxz2iaaaipqbf2slznyaazx81d27imlh-gmp-with-cxx-6.3.0
/nix/store/p610ybx1pp15lnxxdggm3nmaq31whnvi-attr-2.5.2
/nix/store/gda8zjgw0s8zzg5ijza7p12zf5c4b0b0-acl-2.3.2
/nix/store/vb8mdklw65p9wikp97ybmnyay0xzipx3-coreutils-9.5
/nix/store/vpvy79k1qq02p1vyqjk6nb89gwhxqvyb-bash-5.2p32
/nix/store/8iwi6pzi9690yl1l0dv3r497hml7zylf-vimplugin-nvim-treesitter-2024-08-04
```

hm. something is very wrong here. it isn't pulling in any grammars. let's investigate:

https://github.com/NixOS/nixpkgs/blob/7a33145986fa450a1e202728ad485755c28558e9/pkgs/applications/editors/vim/plugins/nvim-treesitter/overrides.nix#L43-L45

ok, so it's looking for a file at `parser/${name}.so`. what does the grammar derivation look like?

```
$ nix build 'nixpkgs#vimPlugins.nvim-treesitter.withAllGrammars' --no-link --print-out-paths
/nix/store/8iwi6pzi9690yl1l0dv3r497hml7zylf-vimplugin-nvim-treesitter-2024-08-04

$ eza -lT /nix/store/9g0g0gbgn4n7w4mlrlzp0r7yjwd1wn3f-nix-grammar-0.0.0+rev=68d3b79
dr-xr-xr-x    - root 31 Dec  1969 /nix/store/9g0g0gbgn4n7w4mlrlzp0r7yjwd1wn3f-nix-grammar-0.0.0+rev=68d3b79
.r-xr-xr-x 106k root 31 Dec  1969 ├── parser
dr-xr-xr-x    - root 31 Dec  1969 └── queries
.r--r--r-- 2.7k root 31 Dec  1969    ├── highlights.scm
.r--r--r-- 1.4k root 31 Dec  1969    ├── injections.scm
.r--r--r-- 1.2k root 31 Dec  1969    └── locals.scm

$ file /nix/store/9g0g0gbgn4n7w4mlrlzp0r7yjwd1wn3f-nix-grammar-0.0.0+rev=68d3b79/parser
/nix/store/9g0g0gbgn4n7w4mlrlzp0r7yjwd1wn3f-nix-grammar-0.0.0+rev=68d3b79/parser: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

So the parser is ending up at `$out/parser` instead of `$out/parser/${language}.so`. What does the grammar derivation's source look like?

https://github.com/NixOS/nixpkgs/blob/7a33145986fa450a1e202728ad485755c28558e9/pkgs/development/tools/parsing/tree-sitter/grammar.nix#L7

Checking `git blame`, this code has been in place for years.

Checking `git blame` for `nvim-treesitter`, I find https://github.com/NixOS/nixpkgs/commit/54f33c58c45e4677699162dbd864adfd363377e1. It was merged three weeks ago.

I see that https://github.com/NixOS/nixpkgs/pull/341079 is open. I couldn't find any information on this problem with GitHub search...

Could that PR be merged quicker please? My editor setup is broken now :(

### Notify maintainers

@stephen-huan 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7, NixOS, 24.11 (Vicuna), 24.11.20240831.5154507`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.0pre20240807_cfe66dbe`
 - nixpkgs: `/nix/store/fa03w7hljdlqzqxlh68cmhhp8yr8msk7-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by PerchunPak**
## Description of changes

This reverts PR #319233. It caused a lot of weird regressions and a lot of headaches for me. Even a 20% improvement isn't worth it. Also see https://github.com/NixOS/nixpkgs/pull/319233#issuecomment-2339271761

In addition, I added a workaround for #332580 as it is also a very annoying regression that will reappear after merging this (minimal reproduction example: https://github.com/NixOS/nixpkgs/issues/332580#issuecomment-2308526316)

Fixes #341442

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

CC @figsoda, @BirdeeHub
@MangoIV, could you try this with koka? Treesitter didn't detect its grammar for some reason for me

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PerchunPak** [comment]
Result of `nixpkgs-review pr 341079` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.nvim-treesitter-parsers.nix</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

Result of `nixpkgs-review pr 341079` run on (emulated) aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.nvim-treesitter-parsers.nix</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by BirdeeHub** [comment]
This is a straight up revert, yes? Im ok with that. It does cause weird things when multiple things add grammars.

**Comment by BirdeeHub** [comment]
Result of `nixpkgs-review pr 341079` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.nvim-treesitter-parsers.nix</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by stephen-huan** [comment]
Apologies again and thanks for handling this @PerchunPak!

For posterity, what do https://github.com/NixOS/nixpkgs/issues/332580 and https://github.com/NixOS/nixpkgs/pull/321550 have to do with https://github.com/NixOS/nixpkgs/pull/319233?

**Review by stephen-huan — APPROVED** [review]

**Comment by PerchunPak** [comment]
> For posterity, what do https://github.com/NixOS/nixpkgs/issues/332580 and https://github.com/NixOS/nixpkgs/pull/321550 have to do with https://github.com/NixOS/nixpkgs/pull/319233?

#319233 accidentally reverted #321550 and #321550 introduced a very annoying regression described in #332580. On every key press in nix file, there was an error emitted

**Comment by PerchunPak** [comment]
> This is a straight up revert, yes?

Yes, it is

> It does cause weird things when multiple things add grammars because now you have 2 bundled grammar balls with the same name instead of just 1

Treesitter should prefer the first grammar it finds, as stated in `:help treesitter`, and looks like this behavior was fine for everyone
> Parsers are searched for as `parser/{lang}.*` in any 'runtimepath' directory.
> If multiple parsers for the same language are found, the first one is used.
> (NOTE: This typically implies the priority "user config > plugins > bundled".)

---

> Id like to see a fix get pushed to the nix grammar eventually for that.

That's for upstream to work on, I don't know anything about writing queries for treesitter
https://github.com/nix-community/tree-sitter-nix/issues/84

**Comment by BirdeeHub** [comment]
LGTM then!

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Pull request merged**
