### PR TITLE
taskwarrior3: 3.1.0 -> 3.2.0

### PR DESCRIPTION
**Pull request by TimShilov**
Bumped taskwarrior version to 3.2.0.
Changelog: https://github.com/GothenburgBitFactory/taskwarrior/releases/tag/v3.2.0
Among other things it also fixes the annoying database locking issue (https://github.com/GothenburgBitFactory/taskwarrior/issues/3676).

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by TimShilov** [comment]
I have tried testing the build but for some reason I'm getting the following error:
```
$ nix build --file /nix/store/0nmjnwymxxvvq1lccjfdlar4v3qnhdph-nixpkgs-review-2.12.0/lib/python3.12/site-packages/nixpkgs_review/nix/review-shell.nix --nix-path 'nixpkgs=/Users/tim/.cache/nixpkgs-review/pr-356198-2/nixpkgs nixpkgs-overlays=/tmp/tmp0piq6p39' --extra-experimental-features 'nix-command no-url-literals' --no-link --keep-going --no-allow-import-from-derivation --argstr local-system aarch64-darwin --argstr nixpkgs-path /Users/tim/.cache/nixpkgs-review/pr-356198-2/nixpkgs --argstr nixpkgs-config-path /tmp/tmpu78p3jjn.nix --argstr attrs-path /Users/tim/.cache/nixpkgs-review/pr-356198-2/attrs.nix
error: builder for '/nix/store/0z9bs8wmia3wi81a7256dsfag1s8vxc5-taskwarrior-3.2.0.drv' failed with exit code 2;
       last 25 log lines:
       >    Compiling google-cloud-storage v0.15.0
       >    Compiling ureq v2.10.1
       >    Compiling strum_macros v0.25.3
       >    Compiling chrono v0.4.38
       > error: download of config.json failed
       >
       > Caused by:
       >   failed to download from `https://index.crates.io/config.json`
       >
       > Caused by:
       >   [6] Could not resolve hostname (Could not resolve host: index.crates.io)
       > make[2]: *** [src/taskchampion-cpp/CMakeFiles/cxxbridge_v1.0.128.dir/build.make:74: corrosion/cxxbridge_v1.0.128/bin/cxxbridge] Error 101
       > make[1]: *** [CMakeFiles/Makefile2:617: src/taskchampion-cpp/CMakeFiles/cxxbridge_v1.0.128.dir/all] Error 2
       > make[1]: *** Waiting for unfinished jobs....
       >    Compiling taskchampion-lib v0.1.0 (/tmp/nix-build-taskwarrior-3.2.0.drv-0/source/src/taskchampion-cpp)
       >    Compiling uuid v1.11.0
       >    Compiling cxxbridge-macro v1.0.128
       >    Compiling byteorder v1.5.0
       >    Compiling strum v0.25.0
       >    Compiling rusqlite v0.29.0
       >    Compiling taskchampion v0.9.0
       >     Finished `release` profile [optimized] target(s) in 46.06s
       > Copying byproducts `libtaskchampion_lib.a` to /tmp/nix-build-taskwarrior-3.2.0.drv-0/source/build/src/taskchampion-cpp
       > [ 13%] Built target _cargo-build_taskchampion_lib
       > make: *** [Makefile:166: all] Error 2
       For full logs, run 'nix log /nix/store/0z9bs8wmia3wi81a7256dsfag1s8vxc5-taskwarrior-3.2.0.drv'.
error: 1 dependencies of derivation '/nix/store/h0w9bw34dzkidsfl6f12a9byna5l6ib6-review-shell.drv' failed to build
```

Not sure what's going on there. Maybe a network issue on my side, I will dig it a bit later.

**Comment by doronbehar** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356198`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>taskwarrior3</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>vimPlugins.taskwarrior3</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
Seems like an issue with upstream's rust dependencies...

**Comment by doronbehar** [comment]
In Nixpkgs we don't merge master into PR branches, but rather we rebase, in order to keep the PR's commits list as clean as possible.

As for the build error, I verified it is still an issue myself now, and opened:

- https://github.com/GothenburgBitFactory/taskwarrior/issues/3705

In the meantime, this is marked as a draft, so no one will merge it by mistake.

**Comment by doronbehar** [comment]
Closing in favor of : 

- https://github.com/NixOS/nixpkgs/pull/359893

(Now not a draft).

**Pull request closed without merging**
