### PR TITLE
[DRAFT] python310Packages.afdko: 3.9.0 -> 3.9.1

### PR DESCRIPTION
**Pull request by onny**
###### Description of changes

update package

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
@sternenseemann Trying to update your python package, unfortunately the libxml2 not found error reoccurs 

```
  -- Found LibXml2: /nix/store/c8p91c6fm67f4ldza6d811wfj61far9f-libxml2-2.9.14/lib/libxml2.so (found version "2.9.14")
  -- Could not locate LibXml2 or system is Linux, will install externally & statically link
  CMake Error at /nix/store/grd724gvgblkvklrmbdyqm5jp8phyb7r-cmake-3.23.2/share/cmake-3.23/Modules/ExternalProject.cmake:2540 (message):
    error: could not find git for clone of external.libxml2
  Call Stack (most recent call first):
    /nix/store/grd724gvgblkvklrmbdyqm5jp8phyb7r-cmake-3.23.2/share/cmake-3.23/Modules/ExternalProject.cmake:3640 (_ep_add_download_command)
    cmake/ExternalLibXML2.cmake:23 (ExternalProject_Add)
    CMakeLists.txt:50 (include)


  -- Configuring incomplete, errors occurred!
```

**Comment by sternenseemann** [comment]
Yes, this is because of the following problem: https://github.com/adobe-type-tools/afdko/pull/1527#issuecomment-1172872618

I've thus opted for upgrading to 3.9.0 and waiting for 3.9.2 or 3.10.0 (whatever comes first)…

**Comment by trofi** [comment]
Should we revert 246216e599eefe157169d2deaec801206fd735d8 meanwhile? `staging` (and `staging-next`) is still broken by `3.9.1` update: https://github.com/NixOS/nixpkgs/pull/191333#issuecomment-1251937657 /cc @mweinelt

**Comment by sternenseemann** [comment]
Yes.

**Comment by trofi** [comment]
Proposed the revert as https://github.com/NixOS/nixpkgs/pull/192768

**Pull request closed without merging**
