### PR TITLE
python312Packages.mdtraj: fix runtime error and support python3.12

### LINKED ISSUE #308847: python3Packages.mdtraj: import fails with ModuleNotFoundError
### Describe the bug
Attempting to import `mdtraj` results in the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/973kyr6nvhd51p20i9xnzqpsrvry7fwn-python3-3.11.9-env/lib/python3.11/site-packages/mdtraj/__init__.py", line 57, in <module>
    from .geometry import *
  File "/nix/store/973kyr6nvhd51p20i9xnzqpsrvry7fwn-python3-3.11.9-env/lib/python3.11/site-packages/mdtraj/geometry/__init__.py", line 53, in <module>
    from .order import *
  File "/nix/store/973kyr6nvhd51p20i9xnzqpsrvry7fwn-python3-3.11.9-env/lib/python3.11/site-packages/mdtraj/geometry/order.py", line 25, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

### Steps To Reproduce
Run the following:
```
nix shell --refresh --impure --expr 'let nixpkgs = builtins.getFlake "github:nixos/nixpkgs/nixpkgs-unstable"; pkgs = nixpkgs.legacyPackages.x86_64-linux; in (pkgs.python311.withPackages (ps: [ ps.mdtraj ]))' --command python -c "import mdtraj"
```

### Expected behavior
Importing `mdtraj` should succeed.

### Additional context
`setuptools` might need to be a runtime dependency. (See [this](https://github.com/Nix-QChem/NixOS-QChem/blob/62f3b8018c2696ac447d8805a5b281b50eea7e85/pkgs/lib/mdtraj/default.nix#L35) alternate derivation which does not have this problem.)

### Notify maintainers

@natsukium 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.87, NixOS, 23.11 (Tapir), 23.11.20240428.12430e4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

closes #308847

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by getchoo** [comment]
Result of `nixpkgs-review pr 309076` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.mdtraj</li>
    <li>python311Packages.mdtraj.dist</li>
    <li>python312Packages.mdtraj</li>
    <li>python312Packages.mdtraj.dist</li>
  </ul>
</details>

**Review by getchoo — APPROVED** [review]

**Review by markuskowa — COMMENTED** [review]
Thanks for fixing the package.
It seems that everything works fine on aarch64, but `python312Packages.mdtraj` fails on x86_64.

**Comment by markuskowa** [comment]
The SSE detection fails with python-3.12. However, the SSE intrinsics are not turned off properly in this case.
The following patch rectifies the problem.

```
diff --git a/basesetup.py b/basesetup.py
index 54dd009e..9ff6ed76 100644
--- a/basesetup.py
+++ b/basesetup.py
@@ -32,6 +32,7 @@ class CompilerDetection(object):
 
     def __init__(self, disable_openmp):
         self.disable_openmp = disable_openmp
+        self.disable_intrinsics = True
         self._is_initialized = False
 
     def initialize(self):
@@ -76,7 +77,7 @@ class CompilerDetection(object):
         if os.environ.get('MDTRAJ_BUILD_DISABLE_INTRINSICS') == "1":
             self.disable_intrinsics = True
             print("Env var MDTRAJ_BUILD_DISABLE_INTRINSICS set")
-        else:
+        elif (self.sse2_enabled or self.neon_enabled):
             self.disable_intrinsics = False
 

```

**Comment by natsukium** [comment]
Yes, I have a problem with SIMD. For some reason, only Python 3.12 cannot detect it.
But I'm able to build on Debian without any problems.

Is it correct that this patch is meant to allow the build to pass without SIMD, and not to enable it?
I think it would be better to accept this patch now, merge this PR, and postpone the SIMD issue.

**Comment by markuskowa** [comment]
> Yes, I have a problem with SIMD. For some reason, only Python 3.12 cannot detect it. But I'm able to build on Debian without any problems.
> 
> Is it correct that this patch is meant to allow the build to pass without SIMD, and not to enable it? I think it would be better to accept this patch now, merge this PR, and postpone the SIMD issue.
> 
> ```
> mdtraj> Attempting to autodetect OpenMP support... Did not detect OpenMP support
> mdtraj> Attempting to autodetect SSE2   support... Did not detect SSE2 support
> mdtraj> Attempting to autodetect SSE3   support... Did not detect SSE3 support
> mdtraj> Attempting to autodetect SSE4.1 support... Did not detect SSE4.1 support
> mdtraj> Attempting to autodetect NEON   support... Did not detect NEON support
> ```

Yes, this patch allows the build to pass without SSE. This is also an upstream bug since the sse intrinsics do not get deactivated if the compiler SSE detection fails.
I agree, that we can fix the actual SSE detection issue later. You can add the patch to the PR to unbreak the python 3.12 build.

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 309076` at 34399938 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python311Packages.mdtraj</li>
    <li>python312Packages.mdtraj</li>
  </ul>
</details>

**Review by markuskowa — APPROVED** [review]
Thanks for opening the upstream PR!

**Comment by natsukium** [comment]
Thanks for your support!

**Pull request merged**
