### PR TITLE
mercurial: 6.4.5 -> 6.5

### PR DESCRIPTION
**Pull request by pacien**
Changelog: https://wiki.mercurial-scm.org/Release6.5

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Review by drupol — CHANGES_REQUESTED** [review]
Oh crap, I just validated it too quickly and noticed that tests are not passing anymore.

**Comment by pacien** [comment]
Quoting Pol Dellaiera (2023-07-12 05:38:30)
> @drupol requested changes on this pull request.
> Oh crap, I just validated it too quickly and noticed that tests are not passing anymore.

From the ofborg results, it fails on:
- build dependencies for darwin,
- test dependencies (gnupg) for the passthru.tests on x86_64.linux.

However the test suite passes fine on aarch64-linux,
so I think the mercurial package itself is fine.

**Comment by drupol** [comment]
So everything normal here?

**Comment by pacien** [comment]
Quoting Pol Dellaiera (2023-07-12 12:58:18)
> So everything normal here?

Yes, all seems good here.

**Pull request merged**
