### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
are you going to merge master into this? ~7 conflicts need to be resolved.

I would do it, but don't want to step on your toes. Also, I need to leave for work :(

**Comment by jonringer** [comment]
resolved merge conflicts, the conflicted packages seem to be building fine locally

**Comment by jtojnar** [comment]
Sorry about creating this mess, I was cherry-picking the compatible changes from #72074 and the did not notice changes in dependent files from master. `NIX_*` are in fact environment variables so they need to be strings, not arrays (and it is going to be enforced by #72074) – only because of these unnoticed conflicts the eval failed.

I have reverted your fixes and merged staging where proper fixes were introduced:

* `hspell`: 49e485925632fd1a75b29cc4334f69e8fc09464a
* `libreoffice`: 2093fa784a02b45628ed360d66cab75e5022eb96
* `virtualbox`’s `iasl`: 21280e418da32bb309be0ce5b97afac8efdbad1c

I have decided to restart the cycle by merging staging here because it also includes lot of build fixes to issues I introduced yesterday, even if they do not impact evaluation.

**Comment by jonringer** [comment]
sounds good to me, just tryingto get ofborg to eval it

**Comment by FRidh** [comment]
Hydra is stuck evaluating staging-next
https://hydra.nixos.org/jobset/nixpkgs/staging-next

**Comment by jonringer** [comment]
hurray! I can finally work on stabilizing a bunch of stuff on master :)

**Pull request merged**
