### PR TITLE
More GNOME updates

### PR DESCRIPTION
**Pull request by jtojnar**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zhaofengli** [comment]
Just a note that vte is a blocker for bumping kgx, which now requires vte >= 0.65.

**Comment by jtojnar** [comment]
Would the compiler matter if the library only exposes C ABI?

**Comment by vcunat** [comment]
I'd hope that would be OK, if the ELFs don't e.g. end up depending on libstdc++ (as reported by `ldd ./result/lib/*.so`).

**Comment by jkarlson** [comment]
Are these things that are supposed to happen for nixos-21.11?

**Pull request merged**
