### PR TITLE
gnu-cobol: move to pkgs/by-name, rename to gnucobol, nixfmt, add NIST test suite

### PR DESCRIPTION
**Pull request by techknowlogick**
## Description of changes

Include changes from https://github.com/NixOS/nixpkgs/pull/325294

All the credit for this PR goes to @kiike

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for the suggestion, @lovesegfault. I split up some changes in that PR into separate commits, so instead of cherry-picking, I adjusted the author field of the new commits. I hope this is a suitable approach, as I very much want to ensure that appropriate credit due is accounted for.

**Comment by kiike** [comment]
```

gnucobol> make[3]: Leaving directory '/build/gnucobol-3.2/tests/cobol85'
gnucobol> make[2]: Leaving directory '/build/gnucobol-3.2/tests/cobol85'
gnucobol> make[1]: Leaving directory '/build/gnucobol-3.2/tests'
gnucobol>        IDENTIFICATION DIVISION.
gnucobol>        PROGRAM-ID. HELLO.
gnucobol>
gnucobol>        PROCEDURE DIVISION.
gnucobol>        DISPLAY "Hello, COBOL!".
gnucobol>        STOP RUN.
gnucobol> Hello, COBOL!
gnucobol> installCheckPhase completed in 8 minutes 26 seconds
┏━ Dependency Graph:
┃    ┌─ ↓ ✔ luaotfload-3.28
┃    ├─ ↓ ✔ luatex-69182
┃    ├─ ↓ ✔ texlive-scripts-70585
┃    │           ┌─ ↓ ✔ perl-5.38.2-env
┃    │        ┌─ ↓ ✔ texlive.infra-69740-tlpdb-70616
┃    │     ┌─ ↓ ✔ texlive-2023-env-texmfdist
┃    │  ┌─ ↓ ✔ texlive-2023-env-texmfroot
┃    ├─ ↓ ✔ fonts.conf
┃ ┌─ ↓ ✔ texlive-2023-env
┃ ├─ ✔ newcob.val.tar.gz ⏱ 4s
┃ ✔ gnucobol-3.2 ⏱ 9m0s
┣━━━ Builds          │ Downloads         │ Host
┃        │ ✔ 2 │     │     │       │     │ localhost
┃        │     │     │     │ ↓ 164 │     │ https://cache.nixos.org
┗━ ∑ ⏵ 0 │ ✔ 2 │ ⏸ 0 │ ↓ 0 │ ↓ 164 │ ⏸ 0 │ Finished at 20:43:42 after 9m19s
```

Building fine on x86_64-linux. Thanks for re-submitting the changes!

**Comment by kiike** [comment]
```
gnucobol> make[1]: Leaving directory '/build/gnucobol-3.2/tests'
gnucobol>        IDENTIFICATION DIVISION.
gnucobol>        PROGRAM-ID. HELLO.
gnucobol>
gnucobol>        PROCEDURE DIVISION.
gnucobol>        DISPLAY "Hello, COBOL!".
gnucobol>        STOP RUN.
gnucobol> Hello, COBOL!
gnucobol> installCheckPhase completed in 20 minutes 58 seconds
┏━ Dependency Graph:
┃ ┌─ ↓ ✔ libtool-2.4.7
┃ ├─ ↓ ✔ stdenv-linux
┃ │  ┌─ ↓ ✔ luaotfload-3.28
┃ │  ├─ ↓ ✔ luatex-69182
┃ │  │        ┌─ ↓ ✔ gcc-wrapper-13.3.0
┃ │  │     ┌─ ↓ ✔ perl-5.38.2-env
┃ │  │  ┌─ ↓ ✔ texlive.infra-69740-tlpdb-70616
┃ │  ├─ ↓ ✔ texlive-scripts-70585
┃ ├─ ↓ ✔ texlive-2023-env
┃ ├─ ✔ newcob.val.tar.gz ⏱ 4s
┃ ✔ gnucobol-3.2 ⏱ 21m54s
┣━━━ Builds          │ Downloads         │ Host
┃        │ ✔ 2 │     │     │       │     │ localhost
┃        │     │     │     │ ↓ 260 │     │ https://cache.nixos.org
┗━ ∑ ⏵ 0 │ ✔ 2 │ ⏸ 0 │ ↓ 0 │ ↓ 260 │ ⏸ 0 │ Finished at 19:42:20 after 22m19s

[kiike@builder-arm-1:~/nixpkgs]$ nix-info
system: "aarch64-linux", multi-user?: yes, version: nix-env (Nix) 2.18.2, nixpkgs: /nix/store/7a56nns2g9wnic8d2yd1np1wj5y8z9y9-source
```

All green on aarch64-linux too!

**Comment by lovesegfault** [comment]
Thanks folks!

**Pull request merged**
