### PR TITLE
shortwave: 3.2.0 -> 4.0.1, move to by-name

### PR DESCRIPTION
**Pull request by zendo**
Changelog:
https://gitlab.gnome.org/World/Shortwave/-/blob/main/data/de.haeckerfelix.Shortwave.metainfo.xml.in.in?ref_type=heads#L78

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
```
(shortwave:117290): Gtk-WARNING **: 12:58:25.730: Could not load image '___object_18___ 
                    ': Error opening file /home/aleksana/.cache/nixpkgs-review/pr-352786/___object_18___ 
                    : No such file or directory
 ERROR mdns_sd::service_daemon > Failed to send SearchStarted(_googlecast._tcp.local.)(repeating:true): sending on a closed channel
```

<details>
<summary>screenshots</summary>

image
image

</details>

**Comment by Aleksanaa** [comment]
Will take a look later

**Comment by zendo** [comment]
It refused to connect when VPN enabled.

**Review by Aleksanaa — APPROVED** [review]

**Comment by lavenderdotpet** [comment]
image
```[lavender@WorkStation:~]$ shortwave 

(shortwave:13728): Adwaita-WARNING **: 14:26:15.401: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(shortwave:13728): Gtk-WARNING **: 14:26:15.442: Could not load image '___object_18___ 
                    ': Error opening file /home/lavender/___object_18___ 
                    : No such file or directory
Gdk-Message: 14:26:15.977: Error 71 (Protocol error) dispatching to Wayland display.
```

**Comment by lavenderdotpet** [comment]
> ```
> (shortwave:117290): Gtk-WARNING **: 12:58:25.730: Could not load image '___object_18___ 
>                     ': Error opening file /home/aleksana/.cache/nixpkgs-review/pr-352786/___object_18___ 
>                     : No such file or directory
>  ERROR mdns_sd::service_daemon > Failed to send SearchStarted(_googlecast._tcp.local.)(repeating:true): sending on a closed channel
> ```
> 
> screenshots

this issue is still happening why was this merged with out fixing

**Pull request merged**
