### PR TITLE
texstudio: fix QT5

### PR DESCRIPTION
**Pull request by nek0**
###### Motivation for this change

texstudio refused to start due to following error:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
```

Fix applied as described in [NixOS wiki](https://nixos.wiki/wiki/Qt#qt5).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Chaddai

### CODE REVIEW

**Review by bjornfor — CHANGES_REQUESTED** [review]
Please prefix commit subject with package name.

**Comment by nek0** [comment]
Like this?

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
> Like this?

Yes. Thanks!

**Comment by bb010g** [comment]
Could this be pulled into `release-19.09`?

**Comment by bjornfor** [comment]
Backported with b926503738cc5b19f3ee66f8a5745c41318a82ff and parent.

**Pull request merged**
