### PR TITLE
pydot_ng: init at 1.0.0

### PR DESCRIPTION
**Pull request by bcdarwin**

### CODE REVIEW

**Comment by FRidh** [comment]
Tests seem to require `pytest`. Please make sure the tests are run.

**Comment by bcdarwin** [comment]
Fixed.

I needed to create an empty directory to get the tests to run (could also have patched to disable the test), but apparently preCheck wasn't being run so I included it in the checkPhase ... any ideas?

**Comment by FRidh** [comment]
Could you add yourself as maintainer?

**Comment by bcdarwin** [comment]
Done.

**Pull request merged**
