### PR TITLE
WIP: build-support.dockerTools: fix `buildTools` not inheriting configs from `fromImage`

### PR DESCRIPTION
**Pull request by eyJhb**
###### Motivation for this change
Having a simple base image in Nix, and then extending upon that would not inherit basic things such as `PATH`, `CMD`, etc.
which made it harder to make a multitude of images.

This tries to fix that! Keep in mind there is one bug and one "maybe fix".

- BUG: If a env is set as `KEY` in a env file, it will be set as `KEY=`, which may or may not be good?
- MAYBE FIX: from my testing, it seems like the image we should look at in `manifest.json` should be the LAST one and not the first one, so all `[0]` is replaced with `[-1]` where it makes sense.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
The spec doesn't specify an ordering for the [manifest list](https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list). Instead, it seems like we need to pick the right image based on its platform:

> The manifest list is the “fat manifest” which points to specific image manifests for one or more platforms.

We'll need some test cases for this functionality in `nixosTests.docker-tools`.

@GrahamcOfBorg test docker-tools

**Comment by eyJhb** [comment]
I have looked at that, however that is not how the manifest looks in general for Docker, if you just unpack a image. I might be doing it wrong, however what we read etc. looks like this 

```json
[
    {
        "Config": "75b0df7cb496aa9a65ae208f3eb08fe6f97415c44509461be2761ff819d121bc.json",
        "RepoTags": [
            "img1:latest"
        ],
        "Layers": [
            "bab8c82687797da6af15c9045d34c44a7b5330eb49a34f982f7836db6d82eac4/layer.tar"
        ]
    }
]
```

And yes, 100% needs some tests added to it.

**Comment by eyJhb** [comment]
> The spec doesn't specify an ordering for the [manifest list](https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list). Instead, it seems like we need to pick the right image based on its platform:
> 
> > The manifest list is the “fat manifest” which points to specific image manifests for one or more platforms.
> 
> We'll need some test cases for this functionality in `nixosTests.docker-tools`.
> 
> @GrahamcOfBorg test docker-tools

The image follows this specification https://github.com/moby/moby/blob/master/image/spec/v1.2.md, whereas the other is the OCI image spec (as far as I can see)...

**Comment by eyJhb** [comment]
Closing till I have something better, if anything.

**Pull request closed without merging**
