### PR TITLE
pinentry_mac: use xcbuild

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This switches pinentry_mac over to xcbuild.

Sadly, pinentry_mac does not work out of the box. I've had to make a few changes for it to compile:

- Update .xib to newer Xcode
- Remove passphrase formatter (see issue Microsoft/winobjc#2501)
- Update to 10.10 MacOS SDK (we don't support older SDKs like Xcode does)
- Disable ARC features (seems to be related to 10.10 SDK)
- Removed .pch (see issue facebook/xcbuild#244)

This PR adds a couple of new packages too:

- [plist-cpp](https://github.com/microsoft/plist-cpp)
- [nsplist](https://github.com/microsoft/nsplist)
- [xib2nib](https://github.com/matthewbauer/xib2nib) (based off of [WinObjC](https://github.com/microsoft/WinObjC))

Each of these packages needs some changes to get working from MSVSC to NixPkgs, so I'm going to try to work to get those changes include so we have legitimate versioning.

I'll try to clean this PR up in the coming, but right now it works as is.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by copumpkin** [comment]
Whoa, you figured out where to get a pure `ibtool`-equivalent??

**Comment by matthewbauer** [comment]
@copumpkin Microsoft has tool inside of WinObjC called xib2nib. I've moved it to a separate repo and got it running on *nix systems. Then I made a bash wrapper that fakes ibtool options and passes them to xib2nib. That means there are some parts of ibtool that it doesn't actually implement. In addition xib2nib has spotty support for some nib files especially older ones (like in pinentry_mac). So after some modifications pinentry_mac is able to work with it.

**Review by copumpkin — APPROVED** [review]
Awesome. Anyway, I'm fine with merging this but if you want to do more work to it first, that's also fine.

**Comment by matthewbauer** [comment]
Ok even though it builds correctly, something weird is going on with the .nib file.

**Comment by matthewbauer** [comment]
Looks good to me if no one has anything to fix.

Some notes on xib2nib:

- it only supports "CocoaTouch" layouts and storyboards not "Cocoa"
- we can get it working eventually, but there isn't much documentation on it.

**Comment by copumpkin** [comment]
How does it work for pinentry if it only supports cocoatouch?

**Comment by matthewbauer** [comment]
@copumpkin So, I'm cheating now and just compiling them in Xcode and checking them into the pienntry_mac tree. I want to keep xib2nib in here though because eventually it should be useful.

**Comment by copumpkin** [comment]
Oh, I see. That works for now I guess 😄 so the xib2nib tool isn't actually used here?

**Comment by copumpkin** [comment]
Also, is converting xib files to nib files the only thing builds generally need to do? I've done a lot of reverse engineering and we could probably revive https://github.com/davidquesada/ibtool without much effort.

**Comment by matthewbauer** [comment]
I'd say that converting xib to nib is the main thing. Storyboards may also be includes and they're basically just a wrapper around a bunch of .xib's.

You're going to have the same problem with ibtool though where it just works with CocoaTouch. I've been looking at the format of .nib's and it's not very well documented. They look like they're just binary plists encoded as nskeyedarchive.

**Comment by copumpkin** [comment]
What's the main difference between CocoaTouch and Cocoa for this? Is it just that there's a bigger RE community around iOS?

**Comment by matthewbauer** [comment]
Probably because iOS is more locked down and stuff so you can use some other layout tools like in gtk or qt. Also Cocoa has a lot more features that need to be included to work while CocoaTouch has relatively less elements. Even for CocoaTouch I don't think it works with 100% of layouts.

**Comment by copumpkin** [comment]
I just took a peek at the "source" for `ibtool` and there really isn't that much of it... 😄 and it doesn't seem to link to external libraries or pull in external files (as far as I've been able to tell yet)

Anyway, this seems fine and promising. I'll look into `ibtool` a bit more later. Feel free to drop by IRC, too!

**Comment by copumpkin** [comment]
Aha, `ibtoold` is what contains the meat of the logic

**Comment by copumpkin** [comment]
Aha, `InterfaceBuilderKit.framework` is yuuuge! This is going to be interesting 😄

**Comment by copumpkin** [comment]
Merging this since my random banter has no bearing on any of this stuff.

**Comment by copumpkin** [comment]
@matthewbauer have you looked at gorm at all, from GNUstep? It looks like it understands nibs and xibs, but it might not understand the cocoa stuff

**Comment by matthewbauer** [comment]
@copumpkin

I don't think gorm supports the .xib format. Apple just added it in Xcode 5 to support version control that didn't like changes to binary files. You're right that it's probably not too complicated and somebody with some RE skills like yourself or others could probably get it working but looking at xib2nib source, it's definitely not going to be too easy.

I don't know if you've got any connections at Apple but maybe if we beg we can get them to open source ibtool? It definitely doesn't have a lot of applications for the average user but it certainly would make this whole thing easier. I suspect, however, that it would be impossible to open source ibtool without open sourcing the whole Cocoa framework and interface builder which is understandably closed source.

Also: do you know what's going on with Hydra? pinentry_mac isn't building for some reason but I can't get any logs on it. They're all in some non-text format. Maybe gzip?

https://lists.gnu.org/archive/html/gnustep-dev/2013-08/msg00078.html
http://wiki.gnustep.org/index.php/XIB

**Pull request merged**
