### PR TITLE
vimPlugins: bump

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 204853` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.editorconfig-vim</li>
    <li>vimPlugins.flake8-vim</li>
    <li>vimPlugins.python-mode</li>
    <li>vimPlugins.tabnine-vim</li>
  </ul>
</details>
<details>
  <summary>106 packages built:</summary>
  <ul>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.calendar-vim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-conjure</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.codi-vim</li>
    <li>vimPlugins.command-t</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.dracula-nvim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.gentoo-syntax</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.hotpot-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.legendary-nvim</li>
    <li>vimPlugins.lsp-inlayhints-nvim</li>
    <li>vimPlugins.lsp-overloads-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.nginx-vim</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.purescript-vim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.registers-nvim</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.ssr-nvim</li>
    <li>vimPlugins.tcomment_vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-dap-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.treesj</li>
    <li>vimPlugins.urlview-nvim</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-dadbod</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-obsession</li>
    <li>vimPlugins.vim-sensible</li>
    <li>vimPlugins.vim-tmux-navigator</li>
    <li>vimPlugins.vim-xkbswitch</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.vimwiki</li>
    <li>vimPlugins.zk-nvim</li>
  </ul>
</details>

**Comment by figsoda** [comment]
also nvim-treesitter grammars are not updated for some reason

**Comment by SuperSandro2000** [comment]
The script is broken and unreliable.

**Comment by figsoda** [comment]
Did the script crash for you by any chance? I can't seem to reproduce either of the issues

**Review by figsoda — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> Did the script crash for you by any chance? I can't seem to reproduce either of the issues

Yeah, I think so because the python git library is broken for newer git versions and fails to commit.

**Comment by SuperSandro2000** [comment]
Just squashed and added a cleanup commit.

I just rerun in without any failures and still got some bogus diff:

```diff
diff --git a/pkgs/applications/editors/vim/plugins/generated.nix b/pkgs/applications/editors/vim/plugins/generated.nix
index 6188496a80b..ffca484b876 100644
--- a/pkgs/applications/editors/vim/plugins/generated.nix
+++ b/pkgs/applications/editors/vim/plugins/generated.nix
@@ -442,7 +442,7 @@
       owner = "ycm-core";
       repo = "YouCompleteMe";
       rev = "2d1de481a94a3be428c87ab0404c38e58b386813";
-      sha256 = "0g780ykjiya6clc3yi8ky4lxhyj2ayc629wn5i2iq8siwm4ab07v";
+      sha256 = "1wlv028y4xnxaz458w2nrv8hqykpwshfbpkyjarqlbirlqhfpw6v";
       fetchSubmodules = true;
     };
     meta.homepage = "https://github.com/ycm-core/YouCompleteMe/";
@@ -2678,7 +2678,7 @@
       owner = "editorconfig";
       repo = "editorconfig-vim";
       rev = "30ddc057f71287c3ac2beca876e7ae6d5abe26a0";
-      sha256 = "1pscf8a3fd79gzqm91gb22pmd44ijahyim9f8vq94c99silyvrjh";
+      sha256 = "1fdpvkgfgw41drszdj9gwz368kmb78d4h6qqq03ihlgqscpw4dvi";
       fetchSubmodules = true;
     };
     meta.homepage = "https://github.com/editorconfig/editorconfig-vim/";
@@ -2884,7 +2884,7 @@
       owner = "andviro";
       repo = "flake8-vim";
       rev = "5bc93f7f26ceb18ccbe116830eaf8ff2baa63994";
-      sha256 = "142pgasl0b64a0zxmspdsi636axrgvdx6rh3hwjrb1zlsck19y1a";
+      sha256 = "1s7rb2ygky1jjjqpwhzp5lsf7js1g0yhnbf6x5lfwygz6646xpy3";
       fetchSubmodules = true;
     };
     meta.homepage = "https://github.com/andviro/flake8-vim/";
@@ -6419,12 +6419,12 @@
 
   orgmode = buildVimPluginFrom2Nix {
     pname = "orgmode";
-    version = "2022-11-30";
+    version = "2022-12-07";
     src = fetchFromGitHub {
       owner = "nvim-orgmode";
       repo = "orgmode";
-      rev = "fc9bb0f5823d01e4008e4b86663772d4148aa9ce";
-      sha256 = "1vb0x89qr2kk5ma8syw4l56c6j2b7y2advyjykdli8psn6i7gsyf";
+      rev = "d3980a5cda71266579ef773168d7750e04911877";
+      sha256 = "1wlmzsj70x891bcxkdcwgx7hiljhgcl73w2i9vadk4n51hxc57h7";
     };
     meta.homepage = "https://github.com/nvim-orgmode/orgmode/";
   };
@@ -6689,7 +6689,7 @@
       owner = "python-mode";
       repo = "python-mode";
       rev = "149ccf7c5be0753f5e9872c023ab2eeec3442105";
-      sha256 = "1l577vb781fqsnin44r5ny0zd5mac9yxbg65fyxcr0x9x7iw97x2";
+      sha256 = "01qxrd3a49vyy5gkczlgipwcjhx97hsb6z8qia9sjdhxys1kvmb3";
       fetchSubmodules = true;
     };
     meta.homepage = "https://github.com/python-mode/python-mode/";
@@ -7605,7 +7605,7 @@
       owner = "codota";
       repo = "tabnine-vim";
       rev = "35f1661297b4bf8b12324c8d29442b36a5ef64d2";
-      sha256 = "1snrjrd0ri5d3kkdv81gvbsv6nccjxqh6zpwkzbz9nh7nhb7dmy2";
+      sha256 = "09l3yqdq3gkrfj8xyzmym260rvq1xl2sh02mfy8la9k1pg6524k8";
       fetchSubmodules = true;
     };
     meta.homepage = "https://github.com/codota/tabnine-vim/";
@@ -11926,12 +11926,12 @@
 
   vim-sandwich = buildVimPluginFrom2Nix {
     pname = "vim-sandwich";
-    version = "2022-07-22";
+    version = "2022-12-07";
     src = fetchFromGitHub {
       owner = "machakann";
       repo = "vim-sandwich";
-      rev = "74898e6f5c5ea37e17163f00bf4981049f785eed";
-      sha256 = "09zx0081bmprvf1zv3wxjnl0j4viks9w3yysbwgg1qqi38fls5rg";
+      rev = "c5a2cc438ce6ea2005c556dc833732aa53cae21a";
+      sha256 = "1b1rim7q398dnwdaqakcycvyvw04rw32k10ij7w7mqpbn9hklpm5";
     };
     meta.homepage = "https://github.com/machakann/vim-sandwich/";
   };
@@ -12863,12 +12863,12 @@
 
   vim-which-key = buildVimPluginFrom2Nix {
     pname = "vim-which-key";
-    version = "2022-10-30";
+    version = "2022-12-07";
     src = fetchFromGitHub {
       owner = "liuchengxu";
       repo = "vim-which-key";
-      rev = "398adc5bf2918ee84e78bd974a9f9d64ddfc0801";
-      sha256 = "18kjcw8jdidihfscir5kihz22mvlwkbab1w5m8hc2w9qjljcza50";
+      rev = "c0eb7a63e80ed0dc2c91eb8c879b7396a795f775";
+      sha256 = "14v47fjp1klnacbbn2ly9ya0xs4dv2bsf9pg391zfcpp9rzf6mrl";
     };
     meta.homepage = "https://github.com/liuchengxu/vim-which-key/";
   };
```

**Review by figsoda — APPROVED** [review]
They all seem to use `fetchSubmodules`, the hash mismatch is probably introduced by `fetchgit`

Are you on macos? I'm not sure what other sanitation we can do since `leaveDotGit` is true

anyways, changes lgtm, we can worry about the hash mismatches later

**Comment by SuperSandro2000** [comment]
> Are you on macos?

Nope

**Pull request merged**
