### PR TITLE
nixos/zapret: init

### PR DESCRIPTION
**Pull request by Nishimara**
## Description of changes

Added zapret service. Systemd service is from [upstream](https://github.com/bol-van/zapret/blob/9fcd8f830ebde2491719a5c698e22d1d5210e0fb/init.d/systemd/zapret.service), not sure if i need to change it, except hardening

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ASHGOLDOFFICIAL** [comment]
Options like that should be created:

**Comment by ASHGOLDOFFICIAL** [comment]
Options like that should be created:
```nix
    # a better name needed
    ipsetHostsUser = {
      exclude = mkOption {
        type = types.lines;
        default = ''
          10.0.0.0/8
          172.16.0.0/12
          192.168.0.0/16
          169.254.0.0/16
          fc00::/7
          fe80::/10
        '';
        description = "Contents of ipset/zapret-hosts-user-exclude.txt.";
      };
      
      include = mkOption {
        type = types.lines;
        default = "";
        example = "nonexistent.domain";
        description = "Contents of ipset/zapret-hosts-user.txt.";
      };
  
      ipban = mkOption {
        type = types.lines;
        default = "";
        example = "nonexistent.domain";
        description = "Contents of ipset/zapret-hosts-user-ipban.txt.";
      };
    };
```

Then values of these options should be written somewhere. Is there a way (for example, by changing an environment variable) to tell zapret to look for these files in different directory (somewhere in `/etc`, for example). Maybe we can ask bol-van to create such functionality?

Maybe add arguments with default values like `hostsUserExclude ? "notadomen.domain"` to package definition, and then during `configurePhase` or some other phase write these arguments' values to needed files. But in that case module can't be used (I think).

**Comment by Nishimara** [comment]
I don't think that we can do something with files, that meant to be changed except config. We can put this in package options, but that will be nasty
```nix
package = pkgs.zapret.override {
  zapret-hosts-user = ''
    site1
    site2
    ...
  '';
};
```
We can change files in package source so it will look in /etc/zapret rather than in $ZAPRET_BASE/ipset, but that too much changes. I will create an issue in zapret.

For now you can use even nastier method
```nix
package = pkgs.zapret.overrideAttrs (prev: {
  installPhase = ''
    ${prev.installPhase}
    
    cat << EOF > $out/usr/share/zapret/ipset/needed-file
      needed-configuration
    EOF
  '';
});
```

**Comment by ASHGOLDOFFICIAL** [comment]
I think every way to implement it now would be nasty. The only clean way is for bol-van to allow changing these files' location. I'm not an expert but I think configuration files should be separate from program's files.

**Comment by voronind-com** [comment]
I've created an alternative PR here https://github.com/NixOS/nixpkgs/pull/347805

**Comment by Nishimara** [comment]
Closing due to better implementation at #347805

**Pull request closed without merging**
