### PR TITLE
evtest-qt: use qt5's mkDerivation

### PR DESCRIPTION
**Pull request by alexarice**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by alexarice** [comment]
#65399

**Comment by alexarice** [comment]
@peterhoeg @ttuegel  as you both seem to know what's going on with qt apps.

Do either of you know why I can't get this to run with sudo? I get the following error,
```
sudo result/bin/evtest-qt                   ~/nixpkgs-review
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, minimal, offscreen, vnc, xcb.

[1]    23611 abort      sudo result/bin/evtest-qt
```

Adding wrapQtAppsHook does not seem to work. The program works fine when not ran through root

**Comment by peterhoeg** [comment]
I have no issues with sudo and this PR.

**Comment by alexarice** [comment]
> 
> 
> Do you use wayland @alexarice?

yes, I thought this could be the problem, can root not connect to wayland?

**Comment by alexarice** [comment]
> 
> 
> > > Do you use wayland @alexarice?
> > 
> > 
> > yes, I thought this could be the problem, can root not connect to wayland?
> 
> Indeed, I believe that is the cause of your issue.

I've only ever used this to check controller input, and I can see that without root. Is it something that is fixable/ worth trying to fix?

**Comment by alexarice** [comment]
fair enough, the fix in this pr still needs to go through as the program doesn't run at all without it

**Review by worldofpeace — APPROVED** [review]
LGTM, I verified the binary was wrapped and executed it without a runtime error.

**Comment by alexarice** [comment]
Thanks for the quick merge

**Pull request merged**
