### PR TITLE
buildLinux: allow changing the pname

### PR DESCRIPTION
**Pull request by Atemu**
## Description of changes

Linux kernel drvs were all just "linux-x.y.z". This allows variants to
distinguish themselves in package names (i.e. "linux-libre").

Repology uses pname for matching
https://github.com/repology/repology-rules/issues/445. This should fix our
kernel variants not showing up on Repology.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Atemu** [comment]
I'll either merge this right after the next kernels update or retarget to staging.

**Review by teto — APPROVED** [review]
absolutely nitpicking but pname tends to come before "version" in packages. My OCD would prefer to see the pname before version but feel free to ignore ^^

I love the idea, especially if it makes repology more truthful

**Comment by Atemu** [comment]
I did actually consider putting pname before version but the reason I didn't is that pname isn't really important while the version has important implications within the Linux kernel drv.

**Review by moni-dz — APPROVED** [review]

**Review by vifino — APPROVED** [review]

**Comment by Atemu** [comment]
Actually, many of these are bumped separately; staging would be better.

**Comment by Ma27** [comment]
> Actually, many of these are bumped separately; staging would be better.

Fwiw kernel updates are usually merged into master and that's fine. Most of the rebuilds are the out-of-tree kernel modules anyways.

**Comment by Atemu** [comment]
Kernel updates usually contain important security and bug fixes while this one is purely cosmetic. Every kernel change is also + a couple dozen MiB in every user's /boot/ which is usually quite space restricted.

**Review by Ma27 — APPROVED** [review]
I think `master` would be fine, but I don't really mind anyways.

LGTM, thanks!

**Pull request merged**
