### PR TITLE
waybar: 0.9.0 -> 0.9.1, fix build

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

ZHF: #80379
https://hydra.nixos.org/build/113067187

-----

Also supersedes #78458 as `date` is needed to build waybar-0.9.1.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
Following https://github.com/NixOS/nixpkgs/pull/78458#issuecomment-578585795, I'd prefer to name it `howard-hinnant-date`, as this seems to be the Repology meta name of the package?

Also could you, as you are already editing the package, add `meta.homepage` to Waybar?

Thanks for the fix and the upstream PRs!

**Comment by Synthetica9** [comment]
> Following #78458 (comment), I'd prefer to name it howard-hinnant-date, as this seems to be the Repology meta name of the package?

I agree, `date` seems to general for a package so specific

**Comment by Ma27** [comment]
@erictapen fixed :)

**Comment by eonpatapon** [comment]
When building with pulseaudio support it fails:

```
../src/modules/network.cpp:68:3: error: 'assert' was not declared in this scope
   68 |   assert(starts_with(read, category));
      |   ^~~~~~
../src/modules/network.cpp:6:1: note: 'assert' is defined in header '<cassert>'; did you forget to '#include <cassert>'?
    5 | #include "util/format.hpp"
  +++ |+#include <cassert>
    6 |
[51/74] Compiling C++ object 'waybar@exe/src_modules_pulseaudio.cpp.o'.'.
```

It works when backporting this patch: https://github.com/Alexays/Waybar/commit/129713fe1b8986fb4722b8e439b16508f063b3e7:

```diff
diff --git a/pkgs/applications/misc/waybar/default.nix b/pkgs/applications/misc/waybar/default.nix
index 69d6ff84268..d302b3c58c2 100644
--- a/pkgs/applications/misc/waybar/default.nix
+++ b/pkgs/applications/misc/waybar/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, fetchFromGitHub, meson, pkgconfig, ninja, wrapGAppsHook
+{ stdenv, fetchFromGitHub, fetchpatch, meson, pkgconfig, ninja, wrapGAppsHook
 , wayland, wlroots, gtkmm3, libinput, libsigcxx, jsoncpp, fmt, scdoc, spdlog, gtk-layer-shell
 , howard-hinnant-date, cmake
 , traySupport  ? true,  libdbusmenu-gtk3
@@ -46,6 +46,13 @@
       "-Dsystemd=disabled"
     ];

+    patches = [
+      (fetchpatch {
+        url = "https://github.com/Alexays/Waybar/commit/129713fe1b8986fb4722b8e439b16508f063b3e7.patch";
+        sha256 = "1zphcyh0097c5m2s6p93i674q5im4zm8bp0hqb607afsk6vi2qd8";
+      })
+    ];
+
     meta = with stdenv.lib; {
       description = "Highly customizable Wayland bar for Sway and Wlroots based compositors";
       license = licenses.mit;
```

**Comment by Ma27** [comment]
What did you do to invoke the command? When running `nix-build -E 'with import ./. {}; waybar.override { pulseSupport = true; }'`, it results in the following derivation:

```
/nix/store/4a7ss18bwgn6biiggvmybx25cb9dfwzk-waybar-0.9.1
```

**Comment by erictapen** [comment]
@eonpatapon Also the commit you mentioned is already present in 0.9.1.

**Comment by eonpatapon** [comment]
I'm sorry I had some override in my overlay that I forgot about :(

The build works fine

**Comment by Ma27** [comment]
Backported as 2fadc21e707dc65df2fd75c71a6d1e8d8aa091a5, 590c89b9fd115b6e6aab4a2d08c01286d198bbae.

**Pull request merged**
