### PR TITLE
nixos/mediawiki: fix nginx rewrites and pin php to 8.1

### PR DESCRIPTION
**Pull request by Mic92**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
API now works for me:  

```
$ curl  "https://nixos-wiki.thalheim.io/w/rest.php/v1/search/page?q=vim&limit=1"
{"pages":[{"id":17,"key":"Vim","title":"Vim","excerpt":"  environment.systemPackages = with pkgs; [ <span class='searchmatch'>vim</span> ];\n  environment.systemPackages = with pkgs; [ <span class='searchmatch'>vim</span>_configurable ];\n","matched_title":null,"description":null,"thumbnail":null}]}
```

I now have to apply some patches to mediawiki, but I am unsure why this only happens to us (I would expect that other people also should see these errors): https://github.com/Mic92/nixos-wiki-infra/tree/45d4ffe847d5bc39b58d758d4b8cedd32bb49791/modules/nixos-wiki

**Comment by Mic92** [comment]
@ofborg test mediawiki

**Comment by McSinyx** [comment]
Assets and API are working for me, although I override the config instead of using your branch.

> this only happens to us (I would expect that other people also should see these errors)

Where these errors are supposed to show up, and are they related to the PHP version pinning?

**Comment by Mic92** [comment]
> Assets and API are working for me, although I override the config instead of using your branch.
> 
> > this only happens to us (I would expect that other people also should see these errors)
> 
> Where these errors are supposed to show up, and are they related to the PHP version pinning?

No, they happend on both php versions: https://github.com/Mic92/nixos-wiki-infra/tree/main/modules/nixos-wiki

**Pull request merged**
