### PR TITLE
ast-grep: 0.28.1 -> 0.30.0

### LINKED ISSUE #355770: Update request: `ast-grep` 0.28.1 → 0.30.0
## Package Information

- Package name: `ast-grep`
- Latest released version: [0.30.0](https://crates.io/crates/ast-grep/0.30.0)
- Current version on the unstable channel: [0.28.1](https://search.nixos.org/packages?channel=unstable&show=ast-grep&from=0&size=1&sort=relevance&type=packages&query=ast-grep)
- Current version on the stable/release channel: [0.22.3](https://search.nixos.org/packages?channel=24.05&show=ast-grep&from=0&size=1&sort=relevance&type=packages&query=ast-grep)

## Checklist

- [x] Checked the [nixpkgs issues](https://github.com/NixOS/nixpkgs/issues)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

 * @cafkafk
 * @Lord-Valen
 * @montchr

For some reason, @r-ryantm [seems to have stopped](https://nixpkgs-update-logs.nix-community.org/ast-grep/) after [0.28.0 that worked well](https://nixpkgs-update-logs.nix-community.org/ast-grep/2024-10-06.log). 0.28.1 was manually updated by @cafkafk, probably as a result.

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by cafkafk**
## Things done
Release notes: https://github.com/ast-grep/ast-grep/releases/tag/0.30.0

Closes: #355770

Signed-off-by: Christina Sørensen <christina@cafkafk.com>

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PaulDance** [comment]
Thanks for the super quick response! Just out of curiosity, will this mean the auto-update bot will start running and therefore opening PRs again for this package?

**Comment by PaulDance** [comment]
> it might have just been slow

That seems unlikely to me: the [logs](https://nixpkgs-update-logs.nix-community.org/ast-grep/) show it ran with a rather consistent pace, most of the time every 7~15 days, while the latest run was ~40 days ago with multiple updates since. Could it be that your manual update disabled it somehow for the package? Or some change in the bot itself?

**Comment by cafkafk** [comment]
May be the case that no one else updated it on repology for instance, it *should* be fixable with a passthru update script... I'll do that in a separate PR tomorrow, should mean it gets picked up

**Comment by PaulDance** [comment]
> May be the case that no one else updated it on repology for instance

There are multiple instances of the latest version there, though: <https://repology.org/project/ast-grep/versions>.

> it should be fixable with a passthru update script... I'll do that in a separate PR tomorrow, should mean it gets picked up

Cool, thanks!

**Comment by PaulDance** [comment]
Is there anything blocking this being merged? I'm not too familiar with the review process here, as it seems optional.

**Comment by PaulDance** [comment]
Super cool, many thanks!

**Pull request merged**
