### PR TITLE
[WIP] buildRustPackage: enable strictDeps

### PR DESCRIPTION
**Pull request by Mic92**
This will improve cross-compiling support by forcing
users to specify buildInputs/nativeBuildInputs correctly.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
cc @Ericson2314

**Comment by Mic92** [comment]
Let me have a look what this change breaks.

**Comment by lovesegfault** [comment]
@Mic92 Any updates on this?

**Comment by Mic92** [comment]
I was finished my buildGoPackage/buildGoModule prs first. This one is next on the list, but take a bit longer, as it rebuilds more packages.

**Comment by lovesegfault** [comment]
Got it, I am testing this on my server as well.

**Comment by lovesegfault** [comment]
Alright, here's my results:
```
62 package marked as broken and skipped:
AgdaSheaves TotalParserCombinators agdaBase autotrace bitvector categories epsxe fast-neural-doodle gimpPlugins.exposureBlend gimpPlugins.focusblur gimpPlugins.texturize gitAndTools.git-dit gtk-sharp-3_0 hhvm hyper-haskell idutils intec
ture-cli invoice2data k9copy loadcaffe mapmap mikutter monodevelop natron neural-style notify-sharp openmodelica photoflow polkadot pretty python37Packages.blaze python37Packages.odo python38Packages.arviz python38Packages.blaze python3
8Packages.odo python38Packages.optuna python38Packages.rl-coach rabbitvcs sit synfigstudio torch torch-hdf5 transcribe vimPlugins.youcompleteme vimiv xfce.xfce4-dict-plugin xfce.xfce4-eyes-plugin xfce.xfce4-fsguard-plugin xfce.xfce4-gen
mon-plugin xfce.xfce4-mailwatch-plugin xfce.xfce4-mpc-plugin xfce.xfce4-notes-plugin xfce.xfce4-timer-plugin xfce.xfce4-vala-panel-appmenu-plugin xfce.xfce4_dict_plugin xfce.xfce4_eyes_plugin xfce.xfce4_fsguard_plugin xfce.xfce4_genmon_
plugin xfce.xfce4_mailwatch_plugin xfce.xfce4_mpc_plugin xfce.xfce4_notes_plugin xfce.xfce4_timer_plugin

60 package failed to build:
AgdaStdlib agdaIowaStdlib amp cargo-download cargo-update cedille citrix_workspace citrix_workspace_19_10_0 citrix_workspace_19_6_0 citrix_workspace_19_8_0 contrast fluidasserts fluxus fractal geeqie gencfsm gnome-builder gnome-podcasts
 httplz hydra-cli ib-controller jucipp jwm khal luxcorerender mopidy-mopify mopidy-musicbox-webclient mopidy-soundcloud mopidy-spotify-tunigo mopidy-youtube nasc navit newsboat nix-du obs-ndi panopticon parallel-rust parinfer-rust ping
python37Packages.arviz python37Packages.dask-jobqueue python37Packages.datashader python37Packages.intake python37Packages.rl-coach sequoia python37Packages.streamz python37Packages.stumpy python37Packages.sunpy python38Packages.dask-jo
bqueue python38Packages.datashader python38Packages.intake python38Packages.sequoia python38Packages.streamz rink ripasso-cursive stm32cubemx tensorman uutils-coreutils vdirsyncer vector
```

**Comment by Mic92** [comment]
Interesting. I had a lot more failures on my machine. Your list looks easier to process to begin with.

**Comment by lovesegfault** [comment]
@Mic92 A lot of the rebuilds this triggers have spurious failures, I got to that list after re-running `nixpkgs-review` some 10 times :D

**Comment by Mic92** [comment]
These are all packages fixed that did fail with strict deps on. There are some packages broken that were already broken before.

**Comment by Mic92** [comment]
@GrahamcOfBorg build hydra-cli

**Comment by Mic92** [comment]
I will master into staging together with the buildRustPackage patch that enable strict deps.

**Comment by Mic92** [comment]
strict deps are enabled in e8323a0bf9d677af7f2705f14c6ee145ed8c2cb7

**Pull request merged**
