### PR TITLE
burpsuite: ease src override 

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

Following the discussion [on discourse](https://discourse.nixos.org/t/overriding-a-package-version-without-building-the-old-version/10696), I updated the software and refactored the derivation to ease future overrides for it

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107717` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>burpsuite</li>
  </ul>
</details>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

**Comment by freezeboy** [comment]
Added the hooks

**Comment by SuperSandro2000** [comment]
Why is ofborg not deting a rebuild?

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107717` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>burpsuite</li>
  </ul>
</details>

**Comment by buckley310** [comment]
I have a (now obsolete) PR that includes a fix for the "integrated browser" feature https://github.com/NixOS/nixpkgs/pull/100677
It's a few lines in the launch script, might be worth stealing if you like it.

**Comment by freezeboy** [comment]
Just stole it ;) can you tell me if it works on your side ?

**Comment by buckley310** [comment]
Looks good to me.

**Comment by buckley310** [comment]
Looks like another burp update got merged. https://github.com/NixOS/nixpkgs/pull/109549   
It does not include all the changes from this PR though. Maybe just rebase and change the title :shrug:

**Comment by SuperSandro2000** [comment]
@freezeboy please resolve the merge conflict

**Comment by freezeboy** [comment]
All done

**Comment by buckley310** [comment]
Looks good. Works for me on nixos-unstable, and it makes the "Open Browser" feature work.

**Pull request merged**
