### PR TITLE
gcc11: 11.4.0 -> 11.5.0

### PR DESCRIPTION
**Pull request by trofi**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 328380` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>64 packages marked as broken and skipped:</summary>
  <ul>
    <li>cudaPackages_11.cudnn_7_4</li>
    <li>cudaPackages_11.cudnn_7_4.dev</li>
    <li>cudaPackages_11.cudnn_7_4.lib</li>
    <li>cudaPackages_11.cudnn_7_4.static</li>
    <li>cudaPackages_11.cudnn_7_6</li>
    <li>cudaPackages_11.cudnn_7_6.dev</li>
    <li>cudaPackages_11.cudnn_7_6.lib</li>
    <li>cudaPackages_11.cudnn_7_6.static</li>
    <li>cudaPackages_11.cudnn_8_0</li>
    <li>cudaPackages_11.cudnn_8_0.dev</li>
    <li>cudaPackages_11.cudnn_8_0.lib</li>
    <li>cudaPackages_11.cudnn_8_0.static</li>
    <li>cudaPackages_11.cudnn_8_1</li>
    <li>cudaPackages_11.cudnn_8_1.dev</li>
    <li>cudaPackages_11.cudnn_8_1.lib</li>
    <li>cudaPackages_11.cudnn_8_1.static</li>
    <li>cudaPackages_11.cudnn_8_2</li>
    <li>cudaPackages_11.cudnn_8_2.dev</li>
    <li>cudaPackages_11.cudnn_8_2.lib</li>
    <li>cudaPackages_11.cudnn_8_2.static</li>
    <li>cudaPackages_11.cudnn_8_3</li>
    <li>cudaPackages_11.cudnn_8_3.dev</li>
    <li>cudaPackages_11.cudnn_8_3.lib</li>
    <li>cudaPackages_11.cudnn_8_3.static</li>
    <li>cudaPackages_11.cudnn_8_4</li>
    <li>cudaPackages_11.cudnn_8_4.dev</li>
    <li>cudaPackages_11.cudnn_8_4.lib</li>
    <li>cudaPackages_11.cudnn_8_4.static</li>
    <li>cudaPackages_11.cudnn_8_5</li>
    <li>cudaPackages_11.cudnn_8_5.dev</li>
    <li>cudaPackages_11.cudnn_8_5.lib</li>
    <li>cudaPackages_11.cudnn_8_5.static</li>
    <li>cudaPackages_11.nccl-tests</li>
    <li>cudaPackages_11.nvidia_driver</li>
    <li>cudaPackages_11.nvidia_driver.bin</li>
    <li>cudaPackages_11.nvidia_driver.lib</li>
    <li>cudaPackages_11.tensorrt_8_0</li>
    <li>cudaPackages_11.tensorrt_8_0.bin</li>
    <li>cudaPackages_11.tensorrt_8_0.dev</li>
    <li>cudaPackages_11.tensorrt_8_0.lib</li>
    <li>cudaPackages_11.tensorrt_8_0.python</li>
    <li>cudaPackages_11.tensorrt_8_0.sample</li>
    <li>cudaPackages_11.tensorrt_8_0.static</li>
    <li>cudaPackages_11.tensorrt_8_2</li>
    <li>cudaPackages_11.tensorrt_8_2.bin</li>
    <li>cudaPackages_11.tensorrt_8_2.dev</li>
    <li>cudaPackages_11.tensorrt_8_2.lib</li>
    <li>cudaPackages_11.tensorrt_8_2.python</li>
    <li>cudaPackages_11.tensorrt_8_2.sample</li>
    <li>cudaPackages_11.tensorrt_8_2.static</li>
    <li>cudaPackages_11.tensorrt_8_4</li>
    <li>cudaPackages_11.tensorrt_8_4.bin</li>
    <li>cudaPackages_11.tensorrt_8_4.dev</li>
    <li>cudaPackages_11.tensorrt_8_4.lib</li>
    <li>cudaPackages_11.tensorrt_8_4.python</li>
    <li>cudaPackages_11.tensorrt_8_4.sample</li>
    <li>cudaPackages_11.tensorrt_8_4.static</li>
    <li>cudaPackages_11.tensorrt_8_5</li>
    <li>cudaPackages_11.tensorrt_8_5.bin</li>
    <li>cudaPackages_11.tensorrt_8_5.dev</li>
    <li>cudaPackages_11.tensorrt_8_5.lib</li>
    <li>cudaPackages_11.tensorrt_8_5.python</li>
    <li>cudaPackages_11.tensorrt_8_5.sample</li>
    <li>cudaPackages_11.tensorrt_8_5.static</li>
  </ul>
</details>
<details>
  <summary>19 packages failed to build:</summary>
  <ul>
    <li>cudaPackages_11.nsight_systems</li>
    <li>cudaPackages_11.nsight_systems.bin</li>
    <li>cudaPackages_11.tensorrt (cudaPackages_11.tensorrt_8_6)</li>
    <li>cudaPackages_11.tensorrt.bin (cudaPackages_11.tensorrt_8_6.bin)</li>
    <li>cudaPackages_11.tensorrt.dev (cudaPackages_11.tensorrt_8_6.dev)</li>
    <li>cudaPackages_11.tensorrt.lib (cudaPackages_11.tensorrt_8_6.lib)</li>
    <li>cudaPackages_11.tensorrt.python (cudaPackages_11.tensorrt_8_6.python)</li>
    <li>cudaPackages_11.tensorrt.sample (cudaPackages_11.tensorrt_8_6.sample)</li>
    <li>cudaPackages_11.tensorrt.static (cudaPackages_11.tensorrt_8_6.static)</li>
    <li>dcgm</li>
    <li>gnat11</li>
    <li>gnat11.info</li>
    <li>gnat11.man</li>
    <li>manaplus</li>
    <li>prometheus-dcgm-exporter</li>
    <li>python311Packages.tensorrt</li>
    <li>python311Packages.tensorrt.dist</li>
    <li>python312Packages.tensorrt</li>
    <li>python312Packages.tensorrt.dist</li>
  </ul>
</details>
<details>
  <summary>167 packages built:</summary>
  <ul>
    <li>chow-tape-model</li>
    <li>cudaPackages_11.backendStdenv</li>
    <li>cudaPackages_11.cuda_cccl</li>
    <li>cudaPackages_11.cuda_cccl.dev</li>
    <li>cudaPackages_11.cuda_cudart</li>
    <li>cudaPackages_11.cuda_cudart.dev</li>
    <li>cudaPackages_11.cuda_cudart.lib</li>
    <li>cudaPackages_11.cuda_cudart.static</li>
    <li>cudaPackages_11.cuda_cudart.stubs</li>
    <li>cudaPackages_11.cuda_cuobjdump</li>
    <li>cudaPackages_11.cuda_cuobjdump.bin</li>
    <li>cudaPackages_11.cuda_cupti</li>
    <li>cudaPackages_11.cuda_cupti.dev</li>
    <li>cudaPackages_11.cuda_cupti.lib</li>
    <li>cudaPackages_11.cuda_cupti.sample</li>
    <li>cudaPackages_11.cuda_cupti.static</li>
    <li>cudaPackages_11.cuda_cuxxfilt</li>
    <li>cudaPackages_11.cuda_cuxxfilt.bin</li>
    <li>cudaPackages_11.cuda_cuxxfilt.dev</li>
    <li>cudaPackages_11.cuda_cuxxfilt.static</li>
    <li>cudaPackages_11.cuda_demo_suite</li>
    <li>cudaPackages_11.cuda_documentation</li>
    <li>cudaPackages_11.cuda_gdb</li>
    <li>cudaPackages_11.cuda_gdb.bin</li>
    <li>cudaPackages_11.cuda_memcheck</li>
    <li>cudaPackages_11.cuda_memcheck.bin</li>
    <li>cudaPackages_11.cuda_nsight</li>
    <li>cudaPackages_11.cuda_nsight.bin</li>
    <li>cudaPackages_11.cuda_nvcc</li>
    <li>cudaPackages_11.cuda_nvcc.static</li>
    <li>cudaPackages_11.cuda_nvdisasm</li>
    <li>cudaPackages_11.cuda_nvdisasm.bin</li>
    <li>cudaPackages_11.cuda_nvml_dev</li>
    <li>cudaPackages_11.cuda_nvml_dev.dev</li>
    <li>cudaPackages_11.cuda_nvml_dev.lib</li>
    <li>cudaPackages_11.cuda_nvprof</li>
    <li>cudaPackages_11.cuda_nvprof.bin</li>
    <li>cudaPackages_11.cuda_nvprof.lib</li>
    <li>cudaPackages_11.cuda_nvprune</li>
    <li>cudaPackages_11.cuda_nvprune.bin</li>
    <li>cudaPackages_11.cuda_nvrtc</li>
    <li>cudaPackages_11.cuda_nvrtc.dev</li>
    <li>cudaPackages_11.cuda_nvrtc.lib</li>
    <li>cudaPackages_11.cuda_nvrtc.static</li>
    <li>cudaPackages_11.cuda_nvtx</li>
    <li>cudaPackages_11.cuda_nvtx.dev</li>
    <li>cudaPackages_11.cuda_nvtx.lib</li>
    <li>cudaPackages_11.cuda_nvvp</li>
    <li>cudaPackages_11.cuda_nvvp.bin</li>
    <li>cudaPackages_11.cuda_profiler_api</li>
    <li>cudaPackages_11.cuda_profiler_api.dev</li>
    <li>cudaPackages_11.cuda_sanitizer_api</li>
    <li>cudaPackages_11.cuda_sanitizer_api.bin</li>
    <li>cudaPackages_11.cudatoolkit</li>
    <li>cudaPackages_11.cudatoolkit-legacy-runfile</li>
    <li>cudaPackages_11.cudatoolkit-legacy-runfile.doc</li>
    <li>cudaPackages_11.cudatoolkit-legacy-runfile.lib</li>
    <li>cudaPackages_11.cudnn (cudaPackages_11.cudnn_8_9)</li>
    <li>cudaPackages_11.cudnn.dev (cudaPackages_11.cudnn_8_9.dev)</li>
    <li>cudaPackages_11.cudnn.lib (cudaPackages_11.cudnn_8_9.lib)</li>
    <li>cudaPackages_11.cudnn.static (cudaPackages_11.cudnn_8_9.static)</li>
    <li>cudaPackages_11.cudnn_8_6</li>
    <li>cudaPackages_11.cudnn_8_6.dev</li>
    <li>cudaPackages_11.cudnn_8_6.lib</li>
    <li>cudaPackages_11.cudnn_8_6.static</li>
    <li>cudaPackages_11.cudnn_8_7</li>
    <li>cudaPackages_11.cudnn_8_7.dev</li>
    <li>cudaPackages_11.cudnn_8_7.lib</li>
    <li>cudaPackages_11.cudnn_8_7.static</li>
    <li>cudaPackages_11.cudnn_8_8</li>
    <li>cudaPackages_11.cudnn_8_8.dev</li>
    <li>cudaPackages_11.cudnn_8_8.lib</li>
    <li>cudaPackages_11.cudnn_8_8.static</li>
    <li>cudaPackages_11.cutensor</li>
    <li>cudaPackages_11.cutensor.dev</li>
    <li>cudaPackages_11.cutensor.lib</li>
    <li>cudaPackages_11.cutensor.static</li>
    <li>cudaPackages_11.cutensor_1_3</li>
    <li>cudaPackages_11.cutensor_1_3.dev</li>
    <li>cudaPackages_11.cutensor_1_3.lib</li>
    <li>cudaPackages_11.cutensor_1_3.static</li>
    <li>cudaPackages_11.cutensor_1_4</li>
    <li>cudaPackages_11.cutensor_1_4.dev</li>
    <li>cudaPackages_11.cutensor_1_4.lib</li>
    <li>cudaPackages_11.cutensor_1_4.static</li>
    <li>cudaPackages_11.cutensor_1_5</li>
    <li>cudaPackages_11.cutensor_1_5.dev</li>
    <li>cudaPackages_11.cutensor_1_5.lib</li>
    <li>cudaPackages_11.cutensor_1_5.static</li>
    <li>cudaPackages_11.cutensor_1_6</li>
    <li>cudaPackages_11.cutensor_1_6.dev</li>
    <li>cudaPackages_11.cutensor_1_6.lib</li>
    <li>cudaPackages_11.cutensor_1_6.static</li>
    <li>cudaPackages_11.cutensor_1_7</li>
    <li>cudaPackages_11.cutensor_1_7.dev</li>
    <li>cudaPackages_11.cutensor_1_7.lib</li>
    <li>cudaPackages_11.cutensor_1_7.static</li>
    <li>cudaPackages_11.fabricmanager</li>
    <li>cudaPackages_11.fabricmanager.bin</li>
    <li>cudaPackages_11.fabricmanager.dev</li>
    <li>cudaPackages_11.fabricmanager.lib</li>
    <li>cudaPackages_11.libcublas</li>
    <li>cudaPackages_11.libcublas.dev</li>
    <li>cudaPackages_11.libcublas.lib</li>
    <li>cudaPackages_11.libcublas.static</li>
    <li>cudaPackages_11.libcufft</li>
    <li>cudaPackages_11.libcufft.dev</li>
    <li>cudaPackages_11.libcufft.lib</li>
    <li>cudaPackages_11.libcufft.static</li>
    <li>cudaPackages_11.libcufile</li>
    <li>cudaPackages_11.libcufile.dev</li>
    <li>cudaPackages_11.libcufile.lib</li>
    <li>cudaPackages_11.libcufile.sample</li>
    <li>cudaPackages_11.libcufile.static</li>
    <li>cudaPackages_11.libcurand</li>
    <li>cudaPackages_11.libcurand.dev</li>
    <li>cudaPackages_11.libcurand.lib</li>
    <li>cudaPackages_11.libcurand.static</li>
    <li>cudaPackages_11.libcusolver</li>
    <li>cudaPackages_11.libcusolver.dev</li>
    <li>cudaPackages_11.libcusolver.lib</li>
    <li>cudaPackages_11.libcusolver.static</li>
    <li>cudaPackages_11.libcusparse</li>
    <li>cudaPackages_11.libcusparse.dev</li>
    <li>cudaPackages_11.libcusparse.lib</li>
    <li>cudaPackages_11.libcusparse.static</li>
    <li>cudaPackages_11.libnpp</li>
    <li>cudaPackages_11.libnpp.dev</li>
    <li>cudaPackages_11.libnpp.lib</li>
    <li>cudaPackages_11.libnpp.static</li>
    <li>cudaPackages_11.libnvidia_nscq</li>
    <li>cudaPackages_11.libnvidia_nscq.lib</li>
    <li>cudaPackages_11.libnvjpeg</li>
    <li>cudaPackages_11.libnvjpeg.dev</li>
    <li>cudaPackages_11.libnvjpeg.lib</li>
    <li>cudaPackages_11.libnvjpeg.static</li>
    <li>cudaPackages_11.nccl</li>
    <li>cudaPackages_11.nccl.dev</li>
    <li>cudaPackages_11.nsight_compute</li>
    <li>cudaPackages_11.nsight_compute.bin</li>
    <li>cudaPackages_11.nvidia_fs</li>
    <li>cudaPackages_11.saxpy</li>
    <li>cudaPackages_11.setupCudaHook</li>
    <li>dmd</li>
    <li>driversi686Linux.amdvlk</li>
    <li>gcc11</li>
    <li>gcc11.info</li>
    <li>gcc11.man</li>
    <li>gcc11Stdenv</li>
    <li>gdc</li>
    <li>gdc.info</li>
    <li>gdc.man</li>
    <li>gfortran11</li>
    <li>gfortran11.info</li>
    <li>gfortran11.man</li>
    <li>python311Packages.cupy</li>
    <li>python311Packages.cupy.dist</li>
    <li>python311Packages.tensorflowWithCuda</li>
    <li>python311Packages.tensorflowWithCuda.dist</li>
    <li>python312Packages.cupy</li>
    <li>python312Packages.cupy.dist</li>
    <li>sgx-psw</li>
    <li>sgx-sdk</li>
    <li>sgx-ssl</li>
    <li>titanion</li>
    <li>torus-trooper</li>
    <li>tumiki-fighters</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 328380` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>86 packages marked as broken and skipped:</summary>
  <ul>
    <li>cudaPackages_11.cuda-samples</li>
    <li>cudaPackages_11.cudnn_7_4</li>
    <li>cudaPackages_11.cudnn_7_4.dev</li>
    <li>cudaPackages_11.cudnn_7_4.lib</li>
    <li>cudaPackages_11.cudnn_7_4.static</li>
    <li>cudaPackages_11.cudnn_7_6</li>
    <li>cudaPackages_11.cudnn_7_6.dev</li>
    <li>cudaPackages_11.cudnn_7_6.lib</li>
    <li>cudaPackages_11.cudnn_7_6.static</li>
    <li>cudaPackages_11.cudnn_8_0</li>
    <li>cudaPackages_11.cudnn_8_0.dev</li>
    <li>cudaPackages_11.cudnn_8_0.lib</li>
    <li>cudaPackages_11.cudnn_8_0.static</li>
    <li>cudaPackages_11.cudnn_8_1</li>
    <li>cudaPackages_11.cudnn_8_1.dev</li>
    <li>cudaPackages_11.cudnn_8_1.lib</li>
    <li>cudaPackages_11.cudnn_8_1.static</li>
    <li>cudaPackages_11.cudnn_8_2</li>
    <li>cudaPackages_11.cudnn_8_2.dev</li>
    <li>cudaPackages_11.cudnn_8_2.lib</li>
    <li>cudaPackages_11.cudnn_8_2.static</li>
    <li>cudaPackages_11.cudnn_8_3</li>
    <li>cudaPackages_11.cudnn_8_3.dev</li>
    <li>cudaPackages_11.cudnn_8_3.lib</li>
    <li>cudaPackages_11.cudnn_8_3.static</li>
    <li>cudaPackages_11.cudnn_8_4</li>
    <li>cudaPackages_11.cudnn_8_4.dev</li>
    <li>cudaPackages_11.cudnn_8_4.lib</li>
    <li>cudaPackages_11.cudnn_8_4.static</li>
    <li>cudaPackages_11.cudnn_8_5</li>
    <li>cudaPackages_11.cudnn_8_5.dev</li>
    <li>cudaPackages_11.cudnn_8_5.lib</li>
    <li>cudaPackages_11.cudnn_8_5.static</li>
    <li>cudaPackages_11.nccl-tests</li>
    <li>cudaPackages_11.nvidia_driver</li>
    <li>cudaPackages_11.nvidia_driver.bin</li>
    <li>cudaPackages_11.nvidia_driver.lib</li>
    <li>cudaPackages_11.tensorrt</li>
    <li>cudaPackages_11.tensorrt.bin</li>
    <li>cudaPackages_11.tensorrt.dev</li>
    <li>cudaPackages_11.tensorrt.lib</li>
    <li>cudaPackages_11.tensorrt.python</li>
    <li>cudaPackages_11.tensorrt.sample</li>
    <li>cudaPackages_11.tensorrt.static</li>
    <li>cudaPackages_11.tensorrt_8_0</li>
    <li>cudaPackages_11.tensorrt_8_0.bin</li>
    <li>cudaPackages_11.tensorrt_8_0.dev</li>
    <li>cudaPackages_11.tensorrt_8_0.lib</li>
    <li>cudaPackages_11.tensorrt_8_0.python</li>
    <li>cudaPackages_11.tensorrt_8_0.sample</li>
    <li>cudaPackages_11.tensorrt_8_0.static</li>
    <li>cudaPackages_11.tensorrt_8_2</li>
    <li>cudaPackages_11.tensorrt_8_2.bin</li>
    <li>cudaPackages_11.tensorrt_8_2.dev</li>
    <li>cudaPackages_11.tensorrt_8_2.lib</li>
    <li>cudaPackages_11.tensorrt_8_2.python</li>
    <li>cudaPackages_11.tensorrt_8_2.sample</li>
    <li>cudaPackages_11.tensorrt_8_2.static</li>
    <li>cudaPackages_11.tensorrt_8_4</li>
    <li>cudaPackages_11.tensorrt_8_4.bin</li>
    <li>cudaPackages_11.tensorrt_8_4.dev</li>
    <li>cudaPackages_11.tensorrt_8_4.lib</li>
    <li>cudaPackages_11.tensorrt_8_4.python</li>
    <li>cudaPackages_11.tensorrt_8_4.sample</li>
    <li>cudaPackages_11.tensorrt_8_4.static</li>
    <li>cudaPackages_11.tensorrt_8_5</li>
    <li>cudaPackages_11.tensorrt_8_5.bin</li>
    <li>cudaPackages_11.tensorrt_8_5.dev</li>
    <li>cudaPackages_11.tensorrt_8_5.lib</li>
    <li>cudaPackages_11.tensorrt_8_5.python</li>
    <li>cudaPackages_11.tensorrt_8_5.sample</li>
    <li>cudaPackages_11.tensorrt_8_5.static</li>
    <li>cudaPackages_11.tensorrt_8_6</li>
    <li>cudaPackages_11.tensorrt_8_6.bin</li>
    <li>cudaPackages_11.tensorrt_8_6.dev</li>
    <li>cudaPackages_11.tensorrt_8_6.lib</li>
    <li>cudaPackages_11.tensorrt_8_6.python</li>
    <li>cudaPackages_11.tensorrt_8_6.sample</li>
    <li>cudaPackages_11.tensorrt_8_6.static</li>
    <li>python311Packages.tensorrt</li>
    <li>python311Packages.tensorrt.dist</li>
    <li>python312Packages.tensorrt</li>
    <li>python312Packages.tensorrt.dist</li>
    <li>tests.cuda.cudaPackages_11.cuda-samples</li>
    <li>tests.cuda.cudaPackages_11_6.cuda-samples</li>
    <li>tests.cuda.cudaPackages_11_8.cuda-samples</li>
  </ul>
</details>
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>cudaPackages_11.nsight_systems</li>
    <li>cudaPackages_11.nsight_systems.bin</li>
    <li>dcgm</li>
    <li>gnat11</li>
    <li>gnat11.info</li>
    <li>gnat11.man</li>
    <li>manaplus</li>
    <li>prometheus-dcgm-exporter</li>
    <li>tests.cc-wrapper.supported</li>
  </ul>
</details>
<details>
  <summary>173 packages built:</summary>
  <ul>
    <li>chow-tape-model</li>
    <li>cudaPackages_11.backendStdenv</li>
    <li>cudaPackages_11.cuda_cccl</li>
    <li>cudaPackages_11.cuda_cccl.dev</li>
    <li>cudaPackages_11.cuda_cudart</li>
    <li>cudaPackages_11.cuda_cudart.dev</li>
    <li>cudaPackages_11.cuda_cudart.lib</li>
    <li>cudaPackages_11.cuda_cudart.static</li>
    <li>cudaPackages_11.cuda_cudart.stubs</li>
    <li>cudaPackages_11.cuda_cuobjdump</li>
    <li>cudaPackages_11.cuda_cuobjdump.bin</li>
    <li>cudaPackages_11.cuda_cupti</li>
    <li>cudaPackages_11.cuda_cupti.dev</li>
    <li>cudaPackages_11.cuda_cupti.lib</li>
    <li>cudaPackages_11.cuda_cupti.sample</li>
    <li>cudaPackages_11.cuda_cupti.static</li>
    <li>cudaPackages_11.cuda_cuxxfilt</li>
    <li>cudaPackages_11.cuda_cuxxfilt.bin</li>
    <li>cudaPackages_11.cuda_cuxxfilt.dev</li>
    <li>cudaPackages_11.cuda_cuxxfilt.static</li>
    <li>cudaPackages_11.cuda_demo_suite</li>
    <li>cudaPackages_11.cuda_documentation</li>
    <li>cudaPackages_11.cuda_gdb</li>
    <li>cudaPackages_11.cuda_gdb.bin</li>
    <li>cudaPackages_11.cuda_memcheck</li>
    <li>cudaPackages_11.cuda_memcheck.bin</li>
    <li>cudaPackages_11.cuda_nsight</li>
    <li>cudaPackages_11.cuda_nsight.bin</li>
    <li>cudaPackages_11.cuda_nvcc</li>
    <li>cudaPackages_11.cuda_nvcc.static</li>
    <li>cudaPackages_11.cuda_nvdisasm</li>
    <li>cudaPackages_11.cuda_nvdisasm.bin</li>
    <li>cudaPackages_11.cuda_nvml_dev</li>
    <li>cudaPackages_11.cuda_nvml_dev.dev</li>
    <li>cudaPackages_11.cuda_nvml_dev.lib</li>
    <li>cudaPackages_11.cuda_nvprof</li>
    <li>cudaPackages_11.cuda_nvprof.bin</li>
    <li>cudaPackages_11.cuda_nvprof.lib</li>
    <li>cudaPackages_11.cuda_nvprune</li>
    <li>cudaPackages_11.cuda_nvprune.bin</li>
    <li>cudaPackages_11.cuda_nvrtc</li>
    <li>cudaPackages_11.cuda_nvrtc.dev</li>
    <li>cudaPackages_11.cuda_nvrtc.lib</li>
    <li>cudaPackages_11.cuda_nvrtc.static</li>
    <li>cudaPackages_11.cuda_nvtx</li>
    <li>cudaPackages_11.cuda_nvtx.dev</li>
    <li>cudaPackages_11.cuda_nvtx.lib</li>
    <li>cudaPackages_11.cuda_nvvp</li>
    <li>cudaPackages_11.cuda_nvvp.bin</li>
    <li>cudaPackages_11.cuda_profiler_api</li>
    <li>cudaPackages_11.cuda_profiler_api.dev</li>
    <li>cudaPackages_11.cuda_sanitizer_api</li>
    <li>cudaPackages_11.cuda_sanitizer_api.bin</li>
    <li>cudatoolkit_11 (cudaPackages_11.cudatoolkit)</li>
    <li>cudaPackages_11.cudatoolkit-legacy-runfile</li>
    <li>cudaPackages_11.cudatoolkit-legacy-runfile.doc</li>
    <li>cudaPackages_11.cudatoolkit-legacy-runfile.lib</li>
    <li>cudaPackages_11.cudnn</li>
    <li>cudaPackages_11.cudnn.dev</li>
    <li>cudaPackages_11.cudnn.lib</li>
    <li>cudaPackages_11.cudnn.static</li>
    <li>cudaPackages_11.cudnn_8_6</li>
    <li>cudaPackages_11.cudnn_8_6.dev</li>
    <li>cudaPackages_11.cudnn_8_6.lib</li>
    <li>cudaPackages_11.cudnn_8_6.static</li>
    <li>cudaPackages_11.cudnn_8_7</li>
    <li>cudaPackages_11.cudnn_8_7.dev</li>
    <li>cudaPackages_11.cudnn_8_7.lib</li>
    <li>cudaPackages_11.cudnn_8_7.static</li>
    <li>cudaPackages_11.cudnn_8_8</li>
    <li>cudaPackages_11.cudnn_8_8.dev</li>
    <li>cudaPackages_11.cudnn_8_8.lib</li>
    <li>cudaPackages_11.cudnn_8_8.static</li>
    <li>cudaPackages_11.cudnn_8_9</li>
    <li>cudaPackages_11.cudnn_8_9.dev</li>
    <li>cudaPackages_11.cudnn_8_9.lib</li>
    <li>cudaPackages_11.cudnn_8_9.static</li>
    <li>cudaPackages_11.cutensor (cudaPackages_11.cutensor_2_0)</li>
    <li>cudaPackages_11.cutensor.dev (cudaPackages_11.cutensor_2_0.dev)</li>
    <li>cudaPackages_11.cutensor.lib (cudaPackages_11.cutensor_2_0.lib)</li>
    <li>cudaPackages_11.cutensor.static (cudaPackages_11.cutensor_2_0.static)</li>
    <li>cudaPackages_11.cutensor_1_3</li>
    <li>cudaPackages_11.cutensor_1_3.dev</li>
    <li>cudaPackages_11.cutensor_1_3.lib</li>
    <li>cudaPackages_11.cutensor_1_3.static</li>
    <li>cudaPackages_11.cutensor_1_4</li>
    <li>cudaPackages_11.cutensor_1_4.dev</li>
    <li>cudaPackages_11.cutensor_1_4.lib</li>
    <li>cudaPackages_11.cutensor_1_4.static</li>
    <li>cudaPackages_11.cutensor_1_5</li>
    <li>cudaPackages_11.cutensor_1_5.dev</li>
    <li>cudaPackages_11.cutensor_1_5.lib</li>
    <li>cudaPackages_11.cutensor_1_5.static</li>
    <li>cudaPackages_11.cutensor_1_6</li>
    <li>cudaPackages_11.cutensor_1_6.dev</li>
    <li>cudaPackages_11.cutensor_1_6.lib</li>
    <li>cudaPackages_11.cutensor_1_6.static</li>
    <li>cudaPackages_11.cutensor_1_7</li>
    <li>cudaPackages_11.cutensor_1_7.dev</li>
    <li>cudaPackages_11.cutensor_1_7.lib</li>
    <li>cudaPackages_11.cutensor_1_7.static</li>
    <li>cudaPackages_11.fabricmanager</li>
    <li>cudaPackages_11.fabricmanager.bin</li>
    <li>cudaPackages_11.fabricmanager.dev</li>
    <li>cudaPackages_11.fabricmanager.lib</li>
    <li>cudaPackages_11.libcublas</li>
    <li>cudaPackages_11.libcublas.dev</li>
    <li>cudaPackages_11.libcublas.lib</li>
    <li>cudaPackages_11.libcublas.static</li>
    <li>cudaPackages_11.libcufft</li>
    <li>cudaPackages_11.libcufft.dev</li>
    <li>cudaPackages_11.libcufft.lib</li>
    <li>cudaPackages_11.libcufft.static</li>
    <li>cudaPackages_11.libcufile</li>
    <li>cudaPackages_11.libcufile.dev</li>
    <li>cudaPackages_11.libcufile.lib</li>
    <li>cudaPackages_11.libcufile.sample</li>
    <li>cudaPackages_11.libcufile.static</li>
    <li>cudaPackages_11.libcurand</li>
    <li>cudaPackages_11.libcurand.dev</li>
    <li>cudaPackages_11.libcurand.lib</li>
    <li>cudaPackages_11.libcurand.static</li>
    <li>cudaPackages_11.libcusolver</li>
    <li>cudaPackages_11.libcusolver.dev</li>
    <li>cudaPackages_11.libcusolver.lib</li>
    <li>cudaPackages_11.libcusolver.static</li>
    <li>cudaPackages_11.libcusparse</li>
    <li>cudaPackages_11.libcusparse.dev</li>
    <li>cudaPackages_11.libcusparse.lib</li>
    <li>cudaPackages_11.libcusparse.static</li>
    <li>cudaPackages_11.libnpp</li>
    <li>cudaPackages_11.libnpp.dev</li>
    <li>cudaPackages_11.libnpp.lib</li>
    <li>cudaPackages_11.libnpp.static</li>
    <li>cudaPackages_11.libnvidia_nscq</li>
    <li>cudaPackages_11.libnvidia_nscq.lib</li>
    <li>cudaPackages_11.libnvjpeg</li>
    <li>cudaPackages_11.libnvjpeg.dev</li>
    <li>cudaPackages_11.libnvjpeg.lib</li>
    <li>cudaPackages_11.libnvjpeg.static</li>
    <li>cudaPackages_11.nccl</li>
    <li>cudaPackages_11.nccl.dev</li>
    <li>cudaPackages_11.nsight_compute</li>
    <li>cudaPackages_11.nsight_compute.bin</li>
    <li>cudaPackages_11.nvidia_fs</li>
    <li>cudaPackages_11.saxpy (tests.cuda.cudaPackages_11.saxpy ,tests.cuda.cudaPackages_11_8.saxpy)</li>
    <li>cudaPackages_11.setupCudaHook</li>
    <li>dmd</li>
    <li>driversi686Linux.amdvlk</li>
    <li>gcc11</li>
    <li>gcc11.info</li>
    <li>gcc11.man</li>
    <li>gcc11Stdenv</li>
    <li>gdc (gdc11)</li>
    <li>gdc.info (gdc11.info)</li>
    <li>gdc.man (gdc11.man)</li>
    <li>gfortran11</li>
    <li>gfortran11.info</li>
    <li>gfortran11.man</li>
    <li>python311Packages.cupy</li>
    <li>python311Packages.cupy.dist</li>
    <li>python311Packages.tensorflowWithCuda</li>
    <li>python311Packages.tensorflowWithCuda.dist</li>
    <li>python312Packages.cupy</li>
    <li>python312Packages.cupy.dist</li>
    <li>sgx-psw</li>
    <li>sgx-sdk</li>
    <li>sgx-ssl</li>
    <li>tests.cuda.cudaPackages_11_6.saxpy</li>
    <li>tests.cuda.cudaPackages_11_7.saxpy</li>
    <li>titanion</li>
    <li>torus-trooper</li>
    <li>tumiki-fighters</li>
  </ul>
</details>

**Comment by gen740** [comment]
It appears that the `pkgs.gcc11` for arrch-darwin is broken by this PR.
The darwin test seems to be failing.

**Comment by trofi** [comment]
Thanks for the report! Can you check if the following PR fixed darwin:
- https://github.com/NixOS/nixpkgs/pull/335554

**Pull request merged**
