### PR TITLE
meshlab: 1.3.3 -> 2016.12

### PR DESCRIPTION
**Pull request by chpatrick**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
Hm, I don't think we should package unreleased software. That's effectively bypassing upstream QA.

**Comment by chpatrick** [comment]
I don't think there was much upstream QA to speak of until they added Travis in March - the latest 2016.12 release doesn't build for example without some workarounds. I think it would be best to use a version that builds out of the box and has a year's worth of fixes.

**Comment by bjornfor** [comment]
Then they might need a little push to tag a release, IMHO.

**Comment by nh2** [comment]
Related:

* #26680 (the Qt-related issues in there seem to be gone in @chpatrick's PR here, not sure if because of newer meshlab or newer NixOS base)
* https://github.com/cnr-isti-vclab/meshlab/issues/247

**Comment by chpatrick** [comment]
I've changed this to build 2016.12 for now.

**Comment by chpatrick** [comment]
@bjornfor Is it OK to merge now?

**Comment by bjornfor** [comment]
Yes. Applied to master (38e2228a3540af86e88858ca465cb07c40f102f6). Thanks!

**Pull request closed without merging**
