### PR TITLE
blightmud: darwin support

### LINKED ISSUE #321605: blightmud: support aarch64-darwin
### Steps To Reproduce

1. build blightmud on arm64-darwin (unsupported system)

### Build log

command: `export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1; nix-shell -p blightmud`

full log: https://gist.github.com/erratic-pattern/90d8f97ab083f5caa575cb98d8002b5e

### Notify maintainers
@cpu 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
adam@Adams-MacBook-Pro:~/Code/nix-config/ > nix-shell -p nix-info --run "nix-info -m"
these 12 paths will be fetched (2.16 MiB download, 21.38 MiB unpacked):
  /nix/store/gykz8wrap5y81fav0yvh7m8d81d7i6y0-DarwinTools-1
  /nix/store/5ll62p1j9pxzvgwsimpbjfy3jwq3cva3-adv_cmds-119-locale
  /nix/store/8rxm4jzw1dddm53rpc2zdqgafadn7d5n-bash-interactive-5.2-p21
  /nix/store/jih6ds079f3gxw49bb0wvw11lm85fspz-ed-1.19
  /nix/store/x1bzwj6pz7f3ajg5y36x07b1328jzx7r-file-5.45
  /nix/store/hhc2x65zvp89lh15grqk21r6dcvifggy-gawk-5.2.2
  /nix/store/h9ywc3fm6k1l7vsc8yxiac8ks559r51g-gnu-config-2023-09-19
  /nix/store/zc9qsb0rzlw0ckhy7097frcwb4pkfx3d-gnumake-4.4.1
  /nix/store/v18l548l4cdp190f37z9670srdxl08b8-nix-info
  /nix/store/kizmwlnj40d11ixbap74c0syaqxn05wc-patch-2.7.6
  /nix/store/sf52i9wcklk5i5f2w15p0kng8dq3qqwx-stdenv-darwin
  /nix/store/gh04z99llkk2f2a6763rbv28s20gkb8w-update-autotools-gnu-config-scripts-hook
copying path '/nix/store/gykz8wrap5y81fav0yvh7m8d81d7i6y0-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/5ll62p1j9pxzvgwsimpbjfy3jwq3cva3-adv_cmds-119-locale' from 'https://cache.nixos.org'...
copying path '/nix/store/zc9qsb0rzlw0ckhy7097frcwb4pkfx3d-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/8rxm4jzw1dddm53rpc2zdqgafadn7d5n-bash-interactive-5.2-p21' from 'https://cache.nixos.org'...
copying path '/nix/store/x1bzwj6pz7f3ajg5y36x07b1328jzx7r-file-5.45' from 'https://cache.nixos.org'...
copying path '/nix/store/h9ywc3fm6k1l7vsc8yxiac8ks559r51g-gnu-config-2023-09-19' from 'https://cache.nixos.org'...
copying path '/nix/store/hhc2x65zvp89lh15grqk21r6dcvifggy-gawk-5.2.2' from 'https://cache.nixos.org'...
copying path '/nix/store/jih6ds079f3gxw49bb0wvw11lm85fspz-ed-1.19' from 'https://cache.nixos.org'...
copying path '/nix/store/v18l548l4cdp190f37z9670srdxl08b8-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/gh04z99llkk2f2a6763rbv28s20gkb8w-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/kizmwlnj40d11ixbap74c0syaqxn05wc-patch-2.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/sf52i9wcklk5i5f2w15p0kng8dq3qqwx-stdenv-darwin' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by matteo-pacini**
## Description of changes

Fixes #321605.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by cpu — APPROVED** [review]
The diff looks reasonable to me (though I lack a darwin system to test with), thank you.

**Comment by DontEatOreo** [comment]
Result of `nixpkgs-review pr 321727` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>blightmud-tts</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>blightmud</li>
  </ul>
</details>

**Comment by DontEatOreo** [comment]
Error log from `nixpkgs-review`:

```console
failures:

---- net::tls::test_tls::test_tls_init_verify_err stdout ----
thread 'net::tls::test_tls::test_tls_init_verify_err' panicked at src/net/tls.rs:186:48:
cannot listen on port: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- net::tls::test_tls::test_tls_init_no_verify stdout ----
thread 'net::tls::test_tls::test_tls_init_no_verify' panicked at src/net/tls.rs:186:48:
cannot listen on port: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }

---- net::tls::test_tls::test_tls_init_verify stdout ----
thread 'net::tls::test_tls::test_tls_init_verify' panicked at src/net/tls.rs:186:48:
cannot listen on port: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }


failures:
    net::tls::test_tls::test_tls_init_no_verify
    net::tls::test_tls::test_tls_init_verify
    net::tls::test_tls::test_tls_init_verify_err

test result: FAILED. 167 passed; 3 failed; 0 ignored; 0 measured; 10 filtered out; finished in 0.59s

error: test failed, to rerun pass `--lib`
```

**Comment by matteo-pacini** [comment]
@DontEatOreo I've disabled those tests, as they seems to be network related.

@cpu I didn't notice earlier the second variant - `blightmud-tts`. Now it compiles fine too, because of the two added Darwin frameworks, AVFoundation and AppKit.

**Comment by DontEatOreo** [comment]
Result of `nixpkgs-review pr 321727` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>blightmud</li>
    <li>blightmud-tts</li>
  </ul>
</details>

**Review by 4evy — APPROVED** [review]

**Pull request merged**
