### PR TITLE
vimPlugins.Nvim-R: init at 2023-11-16

### PR DESCRIPTION
**Pull request by magnouvean**
## Description of changes
Added Nvim-R plugin for neovim. This is quite a popular neovim plugin (almost 900 github stars!) for interacting with R, and I was a little surprised it wasn't packaged already, so I figured I'd do it. I havent been able to test all that much, but I think it should be fine (or else I am happy to fix further). The repo is here: https://github.com/jalvesaq/Nvim-R

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
> I havent been able to test all that much
 
 considering your change is a one-liner I guess not. I dont see why we should undergo the maintainance that comes with a new package if you weren't motivated enough to test it. 
 
 TIP: `nix run nixpkgs#vimPluginsUpdater -- update` to actually generate the nix derivation that you can build and test

**Comment by magnouvean** [comment]
Right, sorry about that. I think I misunderstood how the process worked, but I found some documentation so I think I got it now. I have run the above as requested and I can at least confirm it builds fine. Still haven't really figured out how to install this into neovim though based on a local nixpkgs, so I havent been able to test the functionality (though I don't think the plugin should require any external dependencies which I guess is the biggest problem?). I might try a little more in the weekend though and confirm that everything works as it should.

**Comment by teto** [comment]
the nix code was generated so you should now be able to refer to the plugin as `vimPlugins.Nvim-R`. How do you configure your neovim ? home-manager, nixos-module or just plain neovim ?

**Comment by magnouvean** [comment]
I am using home-manager, but I just didn't find a way to get the vimPlugins.Nvim-R from my fork into it, but I seemed to have found a way by creating my own neovim override package based on example from https://nixos.org/manual/nixpkgs/stable/#vim, so that's good anyway :).

I managed to test this and the functionality looks good as far as I can tell. I was able to create a repl and send lines to it, and everything I would expect the plugin to do (though I of course haven't managed to test everything, just the basics). I also didn't manage to test the completion stuff as nixpkgs missed some dependencies, but this is just extra functionality for the package and not the core of it (most people probably use lsp that completion anyway).

The only thing I saw was that it prompted for installation of `nvimcom`, which I just accepted and everything worked fine, but this is perhaps not true to the nix-philosophy as it installed some R package in the home directory I think. `nvimcom` as far as I understand it is some R library which is needed for proper usage of this plugin, however this is not packaged for nix. If it was packaged though I'm not sure if this should be a required dependency anyway as then we would need also to bring in R as a dependency, which imo isn't really needed (I for example want to have R installed via direnvs), but maybe there are different views about this :)

**Pull request closed without merging**
