### PR TITLE
Bump jetbrains 2024.2.1

### PR DESCRIPTION
**Pull request by jeantil**
## Description of changes

Bump jetbrains 2024.2.1 

I am quite new to nixos and not sure how to apply these changes on my nixos setup to test them locally, I read through the contributing guidelines, through the pkgs readme file and did not really find a command I could run without having the PR opened. 

my nixos is installed as a flake, intellij is installed through homemanager. 
I simply ran the [update script](https://github.com/NixOS/nixpkgs/blob/b956c2f42a5d0c9fbbfd8b2a9cf3bb5f0a6fcf41/pkgs/applications/editors/jetbrains/bin/update_bin.py) provided in the jetbrains package which did all the work really

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jeantil** [comment]
I figured out how to test this change locally and it works ! 
image

**Comment by drupol** [comment]
Hello,

Thanks for your first PR however, I think it can be closed, it has been made in https://github.com/NixOS/nixpkgs/pull/338323

However, I notice that you have updated more things. Maybe you can rebase your PR?

**Comment by jeantil** [comment]
Damn, I did search for a similar PR and somehow missed it, sorry about this. 
The update script seems to update all of jetbrains products based on the latest release but I only tested idea-ultimate as that's the one I use.

**Comment by jeantil** [comment]
I tried rebasing and I'm not confident in the changes so I'll just close this.

**Pull request closed without merging**
