### PR TITLE
xbanish: init at 1.4

### PR DESCRIPTION
**Pull request by choochootrain**
###### Things done
- [X] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [X] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [X] Added appropriate emoji to commit message
- [X] First nixpkgs contribution

---

### CODE REVIEW

**Comment by cillianderoiste** [comment]
That looks good @choochootrain, I just wonder, why use this revision rather than the v1.4 release from a few months earlier?

**Comment by choochootrain** [comment]
no reason other than i didn't bother to look at releases heh - i'll update

**Comment by choochootrain** [comment]
this builds but i now i'm seeing this when i try to add it to my env for manual testing:

```
$ nix-env -f . -iA xbanish
installing ‘xbanish-1.4’
building path(s) ‘/nix/store/xbhbc00h05pwb8b7a0805iyr78z0hwsh-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 87.
error creating link ‘/nix/store/xbhbc00h05pwb8b7a0805iyr78z0hwsh-user-environment/bin’: File exists at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 87.
builder for ‘/nix/store/dmfpwy5sw5ad4f3vkprdkjglsam4c1dk-user-environment.drv’ failed with exit code 17
error: build of ‘/nix/store/dmfpwy5sw5ad4f3vkprdkjglsam4c1dk-user-environment.drv’ failed
```

i think i broke something while juggling the commit between 16.03 and master improperly. have you seen this before?

**Comment by zimbatm** [comment]
It works for me but the man page doesn't install properly. You would have to change the recipe like this:
```diff
--- a/pkgs/tools/X11/xbanish/default.nix
+++ b/pkgs/tools/X11/xbanish/default.nix
@@ -19,6 +19,10 @@ stdenv.mkDerivation rec {
     makeFlagsArray+=("PREFIX=$out")
   '';
 
+  preInstall = ''
+    mkdir -p $out/man/man1
+  '';
+
   meta = {
     description = "Hides mouse pointer while not in use";
     longDescription = ''

```

**Comment by choochootrain** [comment]
whoops @zimbatm that also explains the error i was seeing. binary and man page are in the correct place now.

**Comment by zimbatm** [comment]
Thanks !

**Pull request merged**
