### PR TITLE
Add libgccjit

### PR DESCRIPTION
**Pull request by matthewbauer**
libgccjit is a special "language" frontend of gcc which can compile programs. It can be embedded and used as a library, similar to llvm.

This can be used to build gccemacs. For instance:

```
{ pkgs ? import <nixpkgs> {} }:
(pkgs.emacs.override { stdenv = pkgs.gcc9Stdenv; srcRepo = true; }).overrideAttrs (o: {
    src = pkgs.fetchgit {
      url = "https://git.savannah.gnu.org/git/emacs.git";
      rev = "766f4b96ee148adf8f4bbbf5fa4f1c47555d46de";
      sha256 = "sha256-3SJ431AsdurrDESo8HLElGhUzl0eyADIlit/PNV2FR4=";
    };
    LIBRARY_PATH = "${pkgs.lib.getLib pkgs.stdenv.cc.libc}/lib";
    patches = [];
    buildInputs = o.buildInputs or [] ++ [ pkgs.libgccjit ];
    makeFlags = o.makeFlags or [] ++ ["NATIVE_FAST_BOOT=1"];
    configureFlags = o.configureFlags or [] ++ ["--with-nativecomp"];
  })
```

which can be built with `nix-build`.

### CODE REVIEW

**Review by bhipple — APPROVED** [review]
This is fantastic!  I've managed to compile a `gccemacs` locally now, starting to play with it a bit.  

Why do we need this line, though?  It'd be nice if we could remove that bit, but doing so results in a broken jitter, similar to what I was seeing in my earlier efforts.  

```nix
LIBRARY_PATH = "${lib.getLib stdenv.cc.libc}/lib";
```

**Comment by matthewbauer** [comment]
> Why do we need this line, though? It'd be nice if we could remove that bit, but doing so results in a broken jitter, similar to what I was seeing in my earlier efforts.
> 
> ```nix
> LIBRARY_PATH = "${lib.getLib stdenv.cc.libc}/lib";
> ```

libgccjit needs to know where libc & other runtime libs are. Normally we do this by inserting the flags through cc-wrapper's gcc. But libgccjit doesn't invoke gcc at all, so we need another way to do this. We could get rid of it if we could somehow wrap the library and setting that environment variable, but that's not quite possible in the same way we can do in a binary. This is basically the same situation as libclang is in: see https://github.com/NixOS/nixpkgs/issues/43366.

**Comment by bhipple** [comment]
I now have a working `gccemacs` that I've used to stress test `libgccjit` and all appears to be well so far!

Since this is a no-op cleanup on regular stdenv and just adds the new pkg, I think this is ready to be merged, but I'll defer to @FRidh and/or @jonringer if there's a good time to start Hydra churning away rebuilding-the-world on `staging` again.

Resolves #75288

**Comment by collares** [comment]
Is there any reason libgccjit was pinned to gcc9, or was it just the current version at the time?

**Pull request merged**
