### PR TITLE
buildFHSUserEnvBubblewrap: mount vulkan ICDs

### LINKED ISSUE #134556: steam/proton: missing icd files for nvidia
### Describe the bug
The vulkan icd files for nvidia are missing in steam and causes Black Ops III to not be able to launch properly

### Steps To Reproduce
1. run `steam-run ls /usr/share/vulkan/icd.d/`

on my machine I get:

```console
[babbaj@nixos:~]$ steam-run ls /usr/share/vulkan/icd.d/
intel_icd.i686.json    lvp_icd.i686.json    radeon_icd.i686.json
intel_icd.x86_64.json  lvp_icd.x86_64.json  radeon_icd.x86_64.json
```

### Expected behavior
`nvidia_icd32.json` and `nvidia_icd.json` should be present

### Additional context
Running nvidia driver 470.57.02 on a gtx 970, running the nixos-unstable branch and I do not have an intel or amd gpu
@starcraft66 has a similar but working setup with a 1080 ti

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.57, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre309163.23485f23ff8, home-manager-21.05, master, nixos-stable-20.09, nixos-unstable-21.11pre309163.23485f23ff8"`
 - channels(babbaj): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - steam
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Another alternative solution to #130984, just mount the system ICDs (if they exist) at the default location. If there aren't any, then it will revert to the existing Mesa drivers brought in by steamfhs

This should inherit the behavior of the system, and avoid trying to load ICDs which may or may not exist.

overlaps with: #126435
may solve: #126428

closes: #134556

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 135024` at 6a168562 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>57 packages skipped due to time constraints:</summary>
  <ul>
    <li>Sylk</li>
    <li>altair</li>
    <li>android-studio (androidStudioPackages.stable)</li>
    <li>androidStudioPackages.beta</li>
    <li>androidStudioPackages.canary</li>
    <li>androidStudioPackages.dev</li>
    <li>anki-bin</li>
    <li>anytype</li>
    <li>apple-music-electron</li>
    <li>betterdiscord-installer</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>kodiPackages.steam-launcher</li>
    <li>protontricks</li>
    <li>steam</li>
    <li>steam-run</li>
    <li>steam-run-native</li>
    <li>steam-tui</li>
    <li>steamcmd</li>
  </ul>
</details>

**Comment by critbase** [comment]
Oh cool, this looks like it might be a cleaner solution than my PR. I'll try and test this later.

Also, would the 32 bit files (under /run/opengl-driver-32) need to be mounted this way as well?

**Comment by jonringer** [comment]
> Oh cool, this looks like it might be a cleaner solution than my PR. I'll try and test this later.
> 
> Also, would the 32 bit files (under /run/opengl-driver-32) need to be mounted this way as well?

Currently no, The unfortunate reality is that the file is named the same `nvidia_icd.json`, so one will overwrite the other... We could start installing the drivers with the arch suffixed, similar to mesa which has `radeon_icd.x86_64.json`

**Comment by bendlas** [comment]
Field report: with this patch applied (in particular https://github.com/NixOS/nixpkgs/pull/135024/commits/98014f032c0e12593f60a2636e5fc99cbadd94ba), Satisfactory doesn't start any more.

It pops up an error Dialog: `Cannot find a compatible Vulkan driver (ICD).`

That's with `Proton-6.16-GE-1`

**Comment by jonringer** [comment]
> Field report: with this patch applied (in particular [98014f0](https://github.com/NixOS/nixpkgs/commit/98014f032c0e12593f60a2636e5fc99cbadd94ba)), Satisfactory doesn't start any more.
> 
> It pops up an error Dialog: `Cannot find a compatible Vulkan driver (ICD).`
> 
> That's with `Proton-6.16-GE-1`

Are you running an AMD, NVIDIA, or Intel GPU?

**Comment by bendlas** [comment]
> Are you running an AMD, NVIDIA, or Intel GPU?

Nvidia legacy 470: https://github.com/bendlas/nixos-config/blob/6f6d1c7e0ab1cf6f242d3be2afd5165b96c98803/nitox.nix#L108

```
$ uname -a
Linux nitox 5.10.80 #1-NixOS SMP Thu Nov 18 13:04:33 UTC 2021 x86_64 GNU/Linux

$ glxinfo
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
...
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 670/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 470.86
OpenGL core profile shading language version string: 4.60 NVIDIA
...
```

**Comment by Flakebi** [comment]
I’m not familiar with the steam sandboxes, but does Vulkan work on your host system? I.e.
Does `vulkaninfo` (from `vulkan-tools`) show your nvidia GPU?
And I assume there is an nvidia icd json in `/run/opengl-driver/share/vulkan/icd.d/` that references some nvidia .so library in `/nix/store`?

**Comment by jonringer** [comment]
> And I assume there is an nvidia icd json in `/run/opengl-driver/share/vulkan/icd.d/` that references some nvidia .so library in `/nix/store`?

Correct

```
$ cat /run/opengl-driver/share/vulkan/icd.d/nvidia_icd.json
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "/nix/store/spvqmp94b0i8wvbc3jr8bfj5lsr8i5yr-nvidia-x11-495.44-5.4.160/lib/libGLX_nvidia.so.0",
        "api_version" : "1.2.186"
    }
}
```

**Comment by jonringer** [comment]
seems this is already the case:

```
[nix-shell:/home/jon/projects/nixpkgs]$ steam-run bash
(nix-shell) [14:32:55] jon@jon-desktop /home/jon/projects/nixpkgs (master)
$ cat /run/opengl-driver/share/vulkan/icd.d/nvidia_icd.json
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "/nix/store/spvqmp94b0i8wvbc3jr8bfj5lsr8i5yr-nvidia-x11-495.44-5.4.160/lib/libGLX_nvidia.so.0",
        "api_version" : "1.2.186"
    }
}
```

**Comment by smcv** [comment]
> The unfortunate reality is that the file is named the same nvidia_icd.json, so one will overwrite the other... We could start installing the drivers with the arch suffixed, similar to mesa which has radeon_icd.x86_64.json

For reference, in case this change gets resurrected as a result of https://github.com/ValveSoftware/Dota-2/issues/2018, there are basically three ways to do multilib/multiarch Vulkan drivers:

1. Have a JSON manifest per architecture with different names and optionally different content, like Mesa; or
2. Arrange for the content to be literally identical, and only have one JSON manifest shared between architectures:
    a. reference the actual library by its SONAME only, like `libGLX_nvidia.so.0`, and then arrange for it to be findable via `LD_LIBRARY_PATH` or `ld.so.cache`, like the NVIDIA proprietary driver on e.g. Debian; or
    b. reference the actual library with special tokens that are expanded by `ld.so`, like `/usr/${LIB}/libGLX_nvidia.so.0`; or
3. Use multiple directories, and set `VK_ICD_FILENAMES` or `XDG_DATA_DIRS` to force the search path

I agree that the way Mesa does it (option 1) is likely to be easiest for an OS distributor.

Option 2a might not be an option on NixOS in general, but for the FHS-like container that is used to run Steam, it could probably be made to work.

Option 2b might not work on NixOS, it depends how you configure glibc. It would only work if `${LIB}` has different expansions for x86_64 and i386 loaders.

**Comment by jonringer** [comment]
As a follow up, our `buildFHSUserEnvBubblewrap`  (which steam uses) now uses `XDG_DATA_DIRS` to pass the share directory provided by NixOS's graphics installation path. This should no longer be an issue

**Pull request closed without merging**
