### PR TITLE
pythonPackages.faker: 8.8.2 -> 9.3.1

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Motivation for this change

Update Mirage-IM dependencies (although the new version works OK without them).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
faker needs to go into python-unstable, cc @mweinelt

**Comment by r-burns** [comment]
Yes, the python-unstable branch I believe. Based on previous matrix-nio bumps, that package causes under 10 rebuilds so you can split up this PR and send matrix-nio directly to master if you'd like to get it in faster.

**Comment by mweinelt** [comment]
Sorry, no. Needs to go into staging, python-unstable was merged two days ago.

**Comment by AndersonTorres** [comment]
What about this 11 commits?

**Comment by r-burns** [comment]
These extra commits are from master, looks like you based your PR on the very tip of master. Since these commits haven't been auto-merged into staging yet they show up here when you change the base branch.

The solution is to rebase /just your/ commits onto `$(git merge-base upstream/master upstream/staging)` and then force push before changing the base branch

**Comment by AndersonTorres** [comment]
Can I just cherry-pick this modification in staging?

**Comment by r-burns** [comment]
Yeah that works too now. The merge-base dance is just if you want to avoid the codeowners spam in the future

**Pull request merged**
