### PR TITLE
scaleway-cli: 1.14 -> 1.17

### PR DESCRIPTION
**Pull request by brrrocking**
###### Motivation for this change
Package update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build scaleway-cli

**Comment by Mic92** [comment]
Is a backport to 18.09 required here?

**Comment by brocking** [comment]
Backport is not required as the unstable channel will be sufficient, but it might be useful anyway. I actually updated the package as the previous version was non functional for me (on macOS), although there didn't appear to be any issues listed in the [scaleway-cli](https://github.com/scaleway/scaleway-cli) project. However the project recommends to make use of the latest version and it consists of various updates anyway.

**Comment by Mic92** [comment]
backport: 9fa6a261fb2

**Comment by brocking** [comment]
Thanks!

**Pull request merged**
