### PR TITLE
bazel-watcher: 0.14.0 -> 0.16.2

### PR DESCRIPTION
**Pull request by uri-canva**
###### Description of changes

Update `bazel-watcher`, and fix it on darwin. `bazel-watcher` specifies a bazel version now: https://github.com/bazelbuild/bazel-watcher/blob/v0.16.2/.bazelversion so it's not useful as a downstream test for bazel 3 and 4, so removed it from there.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by uri-canva** [comment]
@ofborg build bazel_3.tests bazel_4.tests bazel_5.tests

**Comment by bobby285271** [comment]
@ofborg eval

**Comment by adisbladis** [comment]
@ofborg eval

**Comment by uri-canva** [comment]
Hash mismatch, will have to figure out what is non-hermetic this time:
```
error: hash mismatch in fixed-output derivation '/nix/store/3z2z3w6zp7wq3lyd9nddmjl97rgfaplk-bazel-watcher-0.16.2-deps.tar.gz.drv':
         specified: sha256-LW5LJMS94D28SXDQB5ZHZ8RDHe3y6g+AN/4irJF3mOc=
            got:    sha256-RX9jZIfqm98Dnv4CSgfyP31fjdlgHRsldml1+/jExPI=
```

**Comment by onny** [comment]
Please rebase. Unfortunately it looks like it already got updated on master

**Pull request closed without merging**
