### PR TITLE
fd: 7.2.0 -> 7.3.0

### PR DESCRIPTION
**Pull request by dywedir**
[changelog](https://github.com/sharkdp/fd/releases/tag/v7.3.0)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by worldofpeace — APPROVED** [review]
Builds and works fine on NixOS.

Don't know what's up with the darwin build.

**Comment by thoughtpolice** [comment]
@GrahamcOfBorg build fd

**Comment by thoughtpolice** [comment]
The error makes me think we were just being haunted by ghosts earlier. But the ghosts may be gone now, so let's see!

```
installing
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to sync
Caused by:
  failed to load pkg lockfile
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  [16/-1] unexpected return value from ssl handshake -9808
```

**Comment by xeji** [comment]
looks like rustc build succeeded on Hydra in the meantime, so let's try again
@GrahamcOfBorg build fd

**Comment by xeji** [comment]
Now the timeouts are gone but it's the same Darwin error again: 

```
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  [16/-1] unexpected return value from ssl handshake -9808
```

**Comment by xeji** [comment]
Since this doesn't look like an issue specific to `fd` I suggest we merge it anyway. Darwin can be fixed later.

**Review by marsam — APPROVED** [review]

**Comment by marsam** [comment]
FWIW I can build it on darwin https://gist.github.com/10a2319157de357940732fe1c30972f5

**Comment by worldofpeace** [comment]
Thanks again for the darwin testing @marsam :smile:

**Pull request merged**
