### PR TITLE
dwarf-fortress: refactor

### LINKED ISSUE #106838: Old cp argument breaks dwarf fortress
Dwarf Fortress installs successfully, but it fails on launch. The "--no-preserve" argument of cp in [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/dwarf-fortress/wrapper/dwarf-fortress-init.in#L23) appears to be out of date.

```
me@computer ~ [1]> dwarf-fortress
Using /home/me/.local/share/df_linux as Dwarf Fortress overlay directory.
If you do any changes in it, don't forget to clean it when updating the game version!
We try to detect changes based on data directories being symbolic links -- keep this in mind.

cp: unrecognized option --no-preserve=all
BusyBox v1.31.1 () multi-call binary.

Usage: cp [OPTIONS] SOURCE... DEST

Copy SOURCE(s) to DEST
	-a	Same as -dpR
	-R,-r	Recurse
	-d,-P	Preserve symlinks (default if -R)
	-L	Follow all symlinks
	-H	Follow symlinks on command line
	-p	Preserve file attributes if possible
	-f	Overwrite
	-i	Prompt before overwrite
	-l,-s	Create (sym)links
	-T	Treat DEST as a normal file
	-u	Copy only newer files
```

Could someone familiar with the expected behavior of the script take a look? @abbradar, @matthewbauer, @cole-h

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
Makes the code more readable and Closes #106838

###### Things done
removed the usage of `pkgs.`, ran nixpkgs-fmt on .nix files, fixed #106838

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>dwarf-fortress (dwarf_fortress)</li>
    <li>dwarf-fortress-packages.dwarf-fortress-full</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_43_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_09</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_10</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_11</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_12</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_01</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_02</li>
    <li>dwarf-fortress-packages.dwarf-therapist</li>
  </ul>
</details>

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
can be tested with
```
{ config, pkgs, ...}:

{
  nixpkgs.overlays = let
    # Replace with the rev of the latest commit
    aRev = "b1ada8bd70a3cc0f7fdeea4003eac540946a7069";
    pkgsArtturin = builtins.fetchTarball {
      url = "https://github.com/Artturin/nixpkgs/archive/${aRev}.tar.gz";
    };
    artturinOverlay = self: super: {
      artturin = super.callPackage pkgsArtturin { config = super.config; };
    };
  in [
    artturinOverlay
  ];

  home.packages = with pkgs; [
    artturin.dwarf-fortress-packages.dwarf-fortress-full
  ];
}
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128584` at b1ada8bd run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built successfully:</summary>
  <ul>
    <li>dwarf-fortress (dwarf-fortress-packages.dwarf-fortress ,dwarf-fortress-packages.dwarf-fortress_0_47_04)</li>
    <li>dwarf-fortress-packages.dwarf-fortress-full</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_43_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_09</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_10</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_11</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_12</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_01</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_02</li>
    <li>dwarf-therapist (dwarf-fortress-packages.dwarf-therapist)</li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/games/dwarf-fortress/wrapper/default.nix:118:3:
```
    |
118 |   buildCommand = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/games/dwarf-fortress/wrapper/default.nix:118:3:
```
    |
118 |   buildCommand = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/games/dwarf-fortress/dwarf-therapist/wrapper.nix:31:3:
```
   |
31 |   buildCommand = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/games/dwarf-fortress/dwarf-therapist/wrapper.nix:31:3:
```
   |
31 |   buildCommand = ''
   |   ^
```
</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

thanks!

```
https://github.com/NixOS/nixpkgs/pull/128584

11 packages built:
dwarf-fortress dwarf-fortress-packages.dwarf-fortress-full dwarf-fortress-packages.dwarf-fortress_0_43_05 dwarf-fortress-packages.dwarf-fortress_0_44_05 dwarf-fortress-packages.dwarf-fortress_0_44_09 dwarf-fortress-packages.dwarf-fortress_0_44_10 dwarf-fortress-packages.dwarf-fortress_0_44_11 dwarf-fortress-packages.dwarf-fortress_0_44_12 dwarf-fortress-packages.dwarf-fortress_0_47_01 dwarf-fortress-packages.dwarf-fortress_0_47_02 dwarf-therapist
```

**Comment by numinit** [comment]
Thanks for doing this!

**Pull request merged**
