### PR TITLE
firefox-bin: 41.0.2 -> 42.0

### PR DESCRIPTION
**Pull request by taku0**
- Various security fixes 
- Private Browsing with Tracking Protection
- Control Center that contains site security and privacy controls https://wiki.mozilla.org/QA/Control_Center
- Indicator added to tabs that play audio with one-click muting
- WebRTC improvements
- Login Manager improvements

https://www.mozilla.org/en-US/firefox/42.0/releasenotes/

Unfortunately, Mozilla now provides only SHA512SUMS but not SHA1SUMS, and Nix does not support SHA-512 hash yet, so that I have to download all archives (8.4 GiB) to calculate those SHA-256 hashes when updating the `sources.nix`.

### CODE REVIEW

**Comment by falsifian** [comment]
It looks like @wkennington just beat you to it (588a950df976cbd5a0795c0ceabc49ae0986bbd7 is on master). It is not cherry-picked to the release branches yet though.

**Comment by falsifian** [comment]
Cherry-pick to release-15.09 is #10838; not yet tested. Didn't bother with release-14.12 since the patch didn't apply cleanly and I personally run release-15.09.

**Comment by taku0** [comment]
@falsifian That `firefox` package is a source package, building a Firefox on local machine. This `firefox-bin` is a binary package, downloads and patchelf the binary distribution of Firefox built by Mozilla.

**Comment by falsifian** [comment]
Whoops, reopened.

**Pull request closed without merging**
