### PR TITLE
[staging-next] fix lutris, attempt wine fix

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
trying to fix some packages before they land in master

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
I was able to launch StarCraft2 through lutris

**Comment by jonringer** [comment]
Seems I'm just unable to build it, but hydra can build it find

**Comment by jonringer** [comment]
I may split some of this into different PRs

**Comment by SFrijters** [comment]
To avoid possible duplicate work, note that #103233 is also being worked on.

**Comment by jonringer** [comment]
thanks

**Pull request closed without merging**
