### PR TITLE
pango: make x11 optional, disabled on darwin

### PR DESCRIPTION
**Pull request by jacereda**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by 7c6f434c — APPROVED** [review]

**Comment by 7c6f434c** [comment]
Not completely sure if not having X11 support is a good macOS default — and in any case this changes dependency order, which implies a rebuild even on Linux, so it should be retargeted to `staging`

**Comment by jtojnar** [comment]
We are updating pango in https://github.com/NixOS/nixpkgs/pull/57027, is this change compatible?

**Comment by 7c6f434c** [comment]
Substantially yes, but automatic merge will produce a conflict (both add some conditional build inputs, both change the argument list).

**Comment by FRidh** [comment]
please rebase

**Comment by jacereda** [comment]
Sorry for the mess, I rebased accidentally on top of master.
Had to change cairo as well to avoid an indirect dependency on xorg.

**Review by 7c6f434c — APPROVED** [review]

**Comment by 7c6f434c** [comment]
Hm, I wonder if the hash problem on aarch64 is transient or a real hash mismatch

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/58560#issuecomment-483973509

**Review by matthewbauer — APPROVED** [review]

**Comment by FRidh** [comment]
tested locally

**Comment by glittershark** [comment]
This breaks building Cairo for me on MacOS with the following message:
```
In file included from cairo-xlib-display.c:40:
In file included from ./cairo-xlib-private.h:40:
./cairo-xlib-xrender-private.h:39:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
1 error generated.
make[3]: *** [Makefile:2358: cairo-xlib-display.lo] Error 1
make[3]: Leaving directory '/private/var/folders/tp/9fpldz0s6j93ln6_dd6pwhsm0000gn/T/nix-build-cairo-1.16.0.drv-0/cairo-1.16.0/src'
make[2]: *** [Makefile:1955: all] Error 2
make[2]: Leaving directory '/private/var/folders/tp/9fpldz0s6j93ln6_dd6pwhsm0000gn/T/nix-build-cairo-1.16.0.drv-0/cairo-1.16.0/src'
make[1]: *** [Makefile:910: all-recursive] Error 1
make[1]: Leaving directory '/private/var/folders/tp/9fpldz0s6j93ln6_dd6pwhsm0000gn/T/nix-build-cairo-1.16.0.drv-0/cairo-1.16.0'
make: *** [Makefile:761: all] Error 2
```

**Pull request merged**
