### PR TITLE
rustc: 1.39 -> 1.40

### PR DESCRIPTION
**Pull request by edolstra**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Mic92** [comment]
Merge conflict due to documentation update.

**Comment by Mic92** [comment]
I am about to build fd on aarch64-linux and x86_64-linux.
We also need a macOS build. @alyssais @grahamc or @LnL7 could either of you run:

```
$ nix-review pr -p fd 76100
```

Our firefox/thunderbird build is still based on the old rustc version.

**Comment by Mic92** [comment]
`fd` on aarch64 builds!

**Review by LnL7 — APPROVED** [review]
Darwin build also looks good.

**Comment by Mic92** [comment]
`fd` on x86_64 builds!

**Review by Mic92 — APPROVED** [review]

**Comment by Mic92** [comment]
pushed to staging: Journal of Environmental Science and Engineering B 2 (2014) 586-601

**Comment by nmattia** [comment]
@edolstra @Mic92 why delete 1.39? I thought we started tracking multiple versions: https://github.com/NixOS/nixpkgs/pull/73039

**Comment by nmattia** [comment]
or rather, why keep 1.38?

**Comment by edolstra** [comment]
We only keep old versions if there a specific need. 1.38 is (was?) needed for Firefox.

**Pull request closed without merging**
