### PR TITLE
nixos/prometheus: add checkConfig

### PR DESCRIPTION
**Pull request by thefloweringash**
Workaround for https://github.com/prometheus/prometheus/issues/5222

###### Motivation for this change

As is, it's not possible to use options like `password_file` that refer to locations outside of the sandbox.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by tomfitzhenry — COMMENTED** [review]
I can see the rationale for this change. My concern is that adding an option is a maintenance burden. Is there precedent for having options to disable validation?

**Comment by thefloweringash** [comment]
I didn't see much with a quick grep. I only really found `nix.checkConfig`, which is a nicer name for the same thing. The other alternative that comes to mind is to _always_ ignore errors in the config, or skip checking completely. This would make the module slightly worse and less safe for current users, but one day can be improved again when (if?) upstream produces the appropriate tools

**Comment by tomfitzhenry** [comment]
> I only really found nix.checkConfig, which is a nicer name for the same thing.

I agree it's nicer. If we do choose to add a new option (which I'm still unsure of), perhaps it'd be better phrased as:

```
checkConfig = mkOption {
    type = types.bool;
    default = true;
    description = ...
}
```

I think this is easier to read, since it's shorter and phrased positively.

If we did that, I don't think we should call promtool if checkConfig = false, since:
* it isn't reasonable to expect users to check the promtool output and manually filter the errors they know are okay.
* this makes our Nix config unnecessarily complex, for little gain.

Users who want promtool checking, but have to disable it because it doesn't quite work for them should continue to work with upstream on resolving prometheus/prometheus#5222 .

**Review by tomfitzhenry — APPROVED** [review]
LGTM.

Pro: Disabling validation is a necessary evil at times. The "password file is not visible at CI time" is such an example. I get the impression there's a missing abstraction with NixOS for user-configurable validation, but for the moment an all-or-nothing approach is fine.

Con: It's another option, and thus a maintenance burden.

**Comment by alyssais** [comment]
LGTM, but we should evaluate whether to remove the option is https://github.com/prometheus/prometheus/pull/6488 is accepted.

**Pull request merged**
