### PR TITLE
git: 2.35.3 -> 2.36.0

### PR DESCRIPTION
**Pull request by techknowlogick**
###### Description of changes

https://github.blog/2022-04-18-highlights-from-git-2-36/

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
This will certainly have to target staging

**Comment by techknowlogick** [comment]
> This will certainly have to target staging

@lovesegfault rebased onto staging :)

**Review by mweinelt — APPROVED** [review]
Tested `gitMinimal` and `gitFull` on both aarch64-linux and x86_64-linux.

**Comment by vcunat** [comment]
It won't build on aarch64-darwin: https://hydra.nixos.org/build/174700755

Maybe a simple addition of a dependency will suffice; say could someone from @NixOS/darwin-maintainers have a look?

**Comment by winterqt** [comment]
I'd make a patch but I can't right now -- but the fix is to add the CoreServices framework as a dependency. See how we handle adding it in callPackage; if nobody else makes a patch I'll do it when I can.

**Comment by vcunat** [comment]
I had guessed so, but I don't have a means to verify.

**Comment by reckenrode** [comment]
@winterqt @vcunat I created #170291 with the fix (add CoreServices framework). I didn’t add it to `callPackage` because I didn’t want to risk breaking anything since git is used in quite a few places with different git packages.

**Comment by vcunat** [comment]
And tests... I suppose well have to disable one, at least on aarch64-darwin?  (the other three built OK)
https://hydra.nixos.org/build/174778232

**Comment by vcunat** [comment]
For reference, done in 9b6415840

**Pull request merged**
