### PR TITLE
Factorio: 0.13.8 -> 0.13.13, mod support

### PR DESCRIPTION
**Pull request by elitak**
###### Motivation for this change

Adding mod support for Factorio is especially helpful for the headless server, where there is no native mod manager.

Until I work out a way to fetch the mods list using their API, transform it into derivations, and host the derivations as a channel usable by nixos-channel, this feature will only be useful to expert users. I think using channels is the most appropriate / idiomatic approach? Please advise if you can think of a better way.

 I'm omitting from this PR the small sample of mods that I translated into derivations by hand.

I didn't like adding the top-level function `factorio-mkModDirDrv` to `all-packages.nix`, but I couldn't see any better solution to sharing the function between nixpkgs and nixos. Is there a cleaner way?
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mpscholten** [comment]
Very cool :) Would be useful to have some documentation on how to use this (otherwise people always need to take a look at the nixpkgs source). Maybe a blog post or an entry to the nixpkgs manual.

> Until I work out a way to fetch the mods list using their API, transform it into derivations, and host the derivations as a channel usable by nixos-channel, this feature will only be useful to expert users. 

👍

**Comment by elitak** [comment]
I didn't really think there would be much of an audience for this, but in case there is, I'll try to make using this changeset a little less abstruse. To that end, I've added the sample mods I mentioned I omitted as a third commit. It's temporary and hardly complete, but can serve as a template for adding one's own mod list.

The final piece is what you would put in configuration.nix, for the headless server:

     services.factorio = {
        enable = true;
        saveName = "bobs";
        autosave-interval = 60;
        mods = with pkgs.factorio-mods; [
          bobassembly
          bobconfig
          bobelectronics
          bobenemies
          bobgreenhouse
          bobinserters
          boblibrary
          boblogistics
          bobmining
          bobmodules
          bobores
          bobplates
          bobpower
          bobrevamp
          bobtech
          bobtechsave
          bobwarfare
        ];
      };

You can also put something similar in `.nixpkgs/config.nix`, then `nix-build -A factorio`:

    pkgs: {
      packageOverrides = pkgs: {
          factorio = pkgs.factorio.override {
            username = "yourlogin"; password = "yourpwd";
            mods = with pkgs.factorio-mods.override { }; [
              bobassembly
              bobconfig
              bobelectronics
              bobenemies
              bobgreenhouse
              bobinserters
              boblibrary
              boblogistics
              bobmining
              bobmodules
              bobores
              bobplates
              bobpower
              bobrevamp
              bobtech
              bobtechsave
              bobwarfare
            ];
          };
      }
    }

Now, you can connect using `./result/bin/factorio` to the server running the same mods list, without the need to fiddle with the buggy and cumbersome mod manager.

That should be all the info necessary to use this. I hesitate to make a blog post anywhere, as again, this is temporary, mostly because maintaining the mods derivations in this repository is untenable. In the final version, the declarations will be almost identical, the only difference will be to use channels, like:

    mods = with (import <factorio-mods>); [

Then, users can run `nixos-channel --add https://probably-my-host-providing-daily-scraped-updates.com/factorio-mods factorio-mods; nixos-channel --update` to update all the mods they use in a coherent way.

**Comment by mpscholten** [comment]
Thanks for the example code :) Always good to have some examples.

Very excited about the factorio-mods channel. Good job so far 👍

**Comment by joachifm** [comment]
So this is ready to go?

**Comment by elitak** [comment]
Yes. I will add more features in a later PR.

**Pull request merged**
