### PR TITLE
anki: 24.06.3 -> 24.11

### PR DESCRIPTION
**Pull request by cything**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Defelo — APPROVED** [review]
tested on x86_64-linux

**Comment by cything** [comment]
That's weird cause it passes on my computer which is x86_64-linux too.
```
test deckconfig::update::test::should_increase_remaining_learning_steps_if_unpassed_learning_step_added ... ok
test dbcheck::test::tags ... ok
test deckconfig::update::test::should_increase_remaining_relearning_steps_if_unpassed_relearning_step_added ... ok
test deckconfig::update::test::should_keep_at_least_one_remaining_learning_step ... ok
test dbcheck::test::note_fields ... ok
test dbcheck::test::note_card_link ... ok
```
I also enabled the tests that were disabled for being flaky like you said and those pass too.

**Comment by martinetd** [comment]
I could get deckconfig::update::test::should_keep_at_least_one_remaining_relearning_step to fail on my laptop by just running it in a loop (after ~1-2k tries; about 2 mins)

```
$ cargo test -vv should_keep_at_least_one_remaining_relearning_step
...
grab the very long line that actually ran something
$ i=0; while BUILDHASH='' CARGO=/home/asmadeus/.rustup/toolchains/1.82.0-x86_64-unknown-linux-gnu/bin/cargo CARGO_MANIFEST_DIR=/home/shared/anki/rslib CARGO_PKG_AUTHORS='Ankitects Pty Ltd and contributors <https://help.ankiweb.net>' CARGO_PKG_DESCRIPTION='Anki'\''s Rust library code' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=AGPL-3.0-or-later CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=anki CARGO_PKG_README=README.md CARGO_PKG_REPOSITORY='' CARGO_PKG_RUST_VERSION=1.80 CARGO_PKG_VERSION=0.0.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=0 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' DESCRIPTORS_BIN=/home/shared/anki/out/rslib/proto/descriptors.bin LD_LIBRARY_PATH='/home/shared/anki/target/debug/build/blake3-9cf1804407af6b48/out:/home/shared/anki/target/debug/build/libsqlite3-sys-521a7856f28c3ca9/out:/home/shared/anki/target/debug/build/ring-1f5a96420d9a73dd/out:/home/shared/anki/target/debug/build/ring-de37fd4f38f3f6b1/out:/home/shared/anki/target/debug/build/zstd-sys-ceda26dcbb83d3fc/out:/home/shared/anki/target/debug/deps:/home/shared/anki/target/debug:/home/asmadeus/.rustup/toolchains/1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/asmadeus/.rustup/toolchains/1.82.0-x86_64-unknown-linux-gnu/lib:/opt/wayland/lib64' MACOSX_DEPLOYMENT_TARGET=10.13.4 OUT_DIR=/home/shared/anki/target/debug/build/anki-913348601b716ed8/out PROTOC=/home/shared/anki/out/extracted/protoc/bin/protoc PYO3_NO_PYTHON=1 STRINGS_PY=/home/shared/anki/out/pylib/anki/_fluent.py STRINGS_TS=/home/shared/anki/out/ts/lib/generated/ftl.ts /home/shared/anki/target/debug/deps/anki-cb2bb8435ea2d543 should_keep_at_least_one_remaining_relearning_step; do i=$((i+1)); done; echo $i
....

---- deckconfig::update::test::should_keep_at_least_one_remaining_relearning_step stdout ----
thread 'deckconfig::update::test::should_keep_at_least_one_remaining_relearning_step' panicked at rslib/src/scheduler/answering/mod.rs:557:61:
called `Result::unwrap()` on an `Err` value: InvalidInput { source: InvalidInputError { message: "bug: card modified without updating queue: id:1733554619996 card:1733554620 entry:1733554619", source: None, backtrace: None } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    deckconfig::update::test::should_keep_at_least_one_remaining_relearning_step

1759
```

If you have time reporting it like I did in https://github.com/ankitects/anki/issues/3353 and just skipping it here is probably the way to go.

**Comment by cything** [comment]
Thanks! I was able to reproduce it exactly like it did. First, it failed after 1.6k tries and during some high CPU usage, it failed after 400 tires. I also created an issue upstream: https://github.com/ankitects/anki/issues/3619

**Review by martinetd — APPROVED** [review]
Thank you!

**Review by donovanglover — APPROVED** [review]
LGTM. Grats on your first contribution to nixpkgs!

**Comment by cything** [comment]
Thank you so much!!

**Review by dotlambda — COMMENTED** [review]
Please use `fetchCargoVendor` so we don't have to vendor the lock file.

**Comment by donovanglover** [comment]
Forgot about that but agree. For anyone that has time, feel free to make a PR updating anki to use the new [`fetchCargoVendor`](https://github.com/NixOS/nixpkgs/pull/349360)

**Pull request merged**
