### PR TITLE
openjpeg: disable more tests

### PR DESCRIPTION
**Pull request by FliegendeWurst**
These were missed in #355345, I guess.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by paparodeo** [comment]
see also https://github.com/NixOS/nixpkgs/pull/358443

**Comment by FliegendeWurst** [comment]
That includes more tests, so I'm closing this PR

**Comment by paparodeo** [comment]
they are the same tests -- I just sorted the tests first. disabled ones are: https://github.com/NixOS/nixpkgs/pull/358443/commits/8dc067b88f1010a012a7fca01d54307fe5831ca9

**Comment by paparodeo** [comment]
did you see these tests fail or is this from the report in https://github.com/NixOS/nixpkgs/pull/354107#issuecomment-2495449910?

**Comment by FliegendeWurst** [comment]
> did you see these tests fail or is this from the report in https://github.com/NixOS/nixpkgs/pull/354107#issuecomment-2495449910?

I saw them fail on x86_64-linux

**Comment by paparodeo** [comment]
thanks. I built on x64 linux with gcc13 and gcc14 without the exclusions. hope there are not more flakey ones.

**Pull request closed without merging**
