### PR TITLE
Darwin fixes

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

These are some more fixes for Darwin stuff. All of the touched files should build on Darwin and hopefully they don't break anything on Linux.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
Running nox-review...

**Comment by globin** [comment]
```
error: cannot link ‘/nix/store/.links/1666wf33g20gqagij48gmh2wk7vxq07kp0a0avqf13hyjfyii7wx’ to ‘/nix/store/cqi1732zfxcvbqnn0dr9kghhs33w01jr-fontforge-20160404-src/osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/PkgInfo’: Operation not permitted
```

**Comment by matthewbauer** [comment]
I've never had that type of issue before... Perhaps nix-collect-garbage could resolve it?

**Comment by knedlsepp** [comment]
I'm currently working on python3.5-jupyter and I'm having problems building fontforge. Are [your changes](https://github.com/NixOS/nixpkgs/pull/18063/commits/dc8d8e9efac3a202fbc2bb552c985a4fdcfdfb00) already working? Even with your patch I'm getting:
```
configure: error: Package requirements (pango >= 1.10 pangoxft) were not met:

No package 'pango' found
No package 'pangoxft' found
```
However if I add `pango` to buildInputs unconditionally, I get
```
error: infinite recursion encountered, at undefined position
```

**Comment by veprbl** [comment]
@knedlsepp 
#18278

**Comment by knedlsepp** [comment]
@veprbl: Thx for pointing it out!

**Comment by matthewbauer** [comment]
Yeah I can remove that one once it is merged.

**Comment by LnL7** [comment]
Was this tested on nixos/linux?

**Comment by matthewbauer** [comment]
@LnL7 I don't have a Linux machine to run this on. I doubt anything would break from this though. They are all pretty small changes.

**Comment by Mic92** [comment]
@matthewbauer this would probably get faster merged, if you split up your commits across pull requests. Otherwise one maintainer would have to test all packages in one flush.

**Comment by LnL7** [comment]
I agree. These are not all just trivial fixes, like adding frameworks.

**Pull request closed without merging**
