### PR TITLE
gnupg agent module: Added extra and browser sockets to GnuPG agent, and added dirmngr, also made SSH support false by default due to programs.ssh.startAgent defaulting to true

### PR DESCRIPTION
**Pull request by CMCDragonkai**
I cloned gnupgs source code to lookup how they are doing systemd integration and ported it to the new gnupg.nix program module.

I had a variation of this already running on my desktop nixos.

@fpletz I changed ssh support to default to false because the ssh start agent defaults to true, I think it would be a better UX if enabling GPG agent doesn't automatically require ssh support and thus result in a nixos rebuild error. Happy to change it back though if you really want it that way.

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
@fpletz Ping

**Review by fpletz — APPROVED** [review]
Thanks for the reminder and these additions. LGTM! :+1: 

My reasoning behind the ssh support was that if you enable the gpg-agent, you might not want to run two separate agents for gpg and ssh. So if an user enables the gpg-agent, it would get the informed by the error that there is a choice between ssh-agent and gpg-agent as an ssh agent (which is not obviously exposed in the module system).

But defaulting to false is also fine by me. I wonder, though, if we should disable ssh-agent by default too.

**Comment by CMCDragonkai** [comment]
Its probably better had ssh agent been disabled by default too. But now we
try to be backwards compatible.

Thanks for accepting!

On 15 Jun 2017 23:14, "Franz Pletz" <notifications@github.com> wrote:

*@fpletz* approved this pull request.

Thanks for the reminder and these additions. LGTM! 👍

My reasoning behind the ssh support was that if you enable the gpg-agent,
you might not want to run two separate agents for gpg and ssh. So if an
user enables the gpg-agent, it would get the informed by the error that
there is a choice between ssh-agent and gpg-agent as an ssh agent (which is
not obviously exposed in the module system).

But defaulting to false is also fine by me. I wonder, though, if we should
disable ssh-agent by default too.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NixOS/nixpkgs/pull/26295#pullrequestreview-44293002>,
or mute the thread

**Comment by fpletz** [comment]
I've created a PR to change the ssh-agent default: #26605

**Comment by fpletz** [comment]
Thanks!

**Pull request merged**
