### PR TITLE
Scala-native does not support sbt 1.X yet

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by volth** [comment]
```src``` to be fixed as well. It has sha256 of sbt-1.0.1

**Comment by MasseGuillaume** [comment]
Indeed, updated.

**Comment by volth** [comment]
I cannot test it right now (no laptop here, only mobile phone), but it looks like whole ```src``` should be overwriten, because ```sha256``` is inside ```src```

**Comment by Mic92** [comment]
mhm. I think this update was a no-op then.

**Pull request merged**
