### PR TITLE
php: default package php56 -> php70

### PR DESCRIPTION
**Pull request by grahamc**
PHP7 is becoming the default in Ubuntu 16.04, and many devs are already moving to php7 as their baseline dependency. Is there a good argument to defaulting to 5.6?

Please backport to 16.03.
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by globin** [comment]
Ack for unstable, too late for 16.03

**Comment by grahamc** [comment]
Well okay :) I'm going to fix the build failures. I little bit disappointed we can't brag about php7 default, but OK.

**Comment by grahamc** [comment]
This is definitely a WIP due to the Xapian breakage here: https://github.com/NixOS/nixpkgs/issues/13899

**Comment by grahamc** [comment]
- [ ] xapianBindings are not allowed to be distributed with PHP support due to PHP / GPL license conflicts.

**Comment by fpletz** [comment]
There are also some packages like owncloud in the apache-httpd module that will probably still require php5.

**Comment by joachifm** [comment]
Both `xapianBindings` and `sup` are broken on master already, not sure if this PR is the best place for those.

**Comment by grahamc** [comment]
I'll split those out now in to a separate PR, as that can be backported (right?) to 16.03 to fix them there.

**Comment by grahamc** [comment]
## PHP7 Work / Verify List

 - [ ] OwnCloud - https://owncloud.org/blog/php-7-is-here-and-owncloud-is-ready/

**Comment by joachifm** [comment]
Yeah, I think we should backport them. At any rate, do not consider those blockers for this change, which seems too sensible to be hampered by that incredibly annoying breakage.

**Pull request closed without merging**
