### PR TITLE
spdlog: 1.8.2 -> 1.8.5

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117987` at 10b3ed18 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lizardfs</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/438e90aa9ffd12c8dbdf115e80914529">python38Packages.qiskit-aer</a></li>
    <li><a href="https://gist.github.com/2138d5c560cef5f818e02888884f738f">python38Packages.qiskit-ignis</a></li>
    <li><a href="https://gist.github.com/944f617fbca5e715e1ade092c9ebb1b7">python39Packages.qiskit</a></li>
    <li><a href="https://gist.github.com/64ac27ff1ca1300fe9b8f89c3253763e">python39Packages.qiskit-aer</a></li>
    <li><a href="https://gist.github.com/9a5f7f0f848cbbcc0b7908b77afcb1f3">python39Packages.qiskit-aqua</a></li>
    <li><a href="https://gist.github.com/dd6fcec6873f0228b847a36b54fcc7c4">python39Packages.qiskit-ibmq-provider</a></li>
    <li><a href="https://gist.github.com/fd09b1e714ad66f89a804ae1bc38b21c">python39Packages.qiskit-ignis</a></li>
  </ul>
</details>
<details>
  <summary>19 packages skipped due to time constraints:</summary>
  <ul>
    <li>bear</li>
    <li>far2l</li>
    <li>hal-hardware-analyzer</li>
    <li>kodi (kodiPackages.kodi)</li>
    <li>kodi-gbm</li>
    <li>kodi-wayland</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>gerbera</li>
    <li>mtxclient</li>
    <li>spdlog (spdlog_1)</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by doronbehar** [comment]
Result of `nixpkgs-review pr 117987` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lizardfs</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>bear</li>
    <li>far2l</li>
    <li>gerbera</li>
    <li>hal-hardware-analyzer</li>
    <li>mtxclient</li>
    <li>nheko</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.qiskit-aer</li>
    <li>python38Packages.qiskit-aqua</li>
    <li>python38Packages.qiskit-ibmq-provider</li>
    <li>python38Packages.qiskit-ignis</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-aqua</li>
    <li>python39Packages.qiskit-ibmq-provider</li>
    <li>python39Packages.qiskit-ignis</li>
    <li>spdlog (spdlog_1)</li>
    <li>waybar</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
I built all reverse deps besides kodi deps. Don't know why some of them failed in previous nixpkgs-review run.

**Comment by doronbehar** [comment]
Other then that I see no breaking changes in the release notes.

**Pull request merged**
