### PR TITLE
tor-browser-bundle-bin: fix (noscript) extension startup

### PR DESCRIPTION
**Pull request by xaverdh**
#### Motivation for this change

Fix the `noscript` part of https://github.com/NixOS/nixpkgs/issues/83096

###### Things done

Tested locally; this seems to fix the issue.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xaverdh** [comment]
This should fix the issue with `noscript`. Since its the only `addon` which got "lost" when firefox stopped sideloading from the isntallation directory, it probably won't do anything for other addons. So might not fix the linked issue fully.

**Comment by xaverdh** [comment]
(pushed a change, to also unmark as broken)

**Comment by joachifm** [comment]
Has this been verified to not introduce impurities in the profile dir? If not, please ensure that the profile does not capture any Nix store paths in a way that may allow them to become stale.

**Comment by xaverdh** [comment]
> Has this been verified to not introduce impurities in the profile dir? If not, please ensure that the profile does not capture any Nix store paths in a way that may allow them to become stale.

The only store paths I can see captured are from `onboarding@mozilla.org`, in the startup cache and such (so likely unrelated to this).

**Comment by yurkobb** [comment]
Thank you, NoScript is back for me at least for the initial start up after `rm -fR ~/.local/share/tor-browser`.

**Comment by yurkobb** [comment]
If I comment out [this line](https://github.com/NixOS/nixpkgs/blob/7e619b521a22a1c729cca67e234ecaf698043bfa/pkgs/applications/networking/browsers/tor-browser-bundle-bin/default.nix#L290) though, NoScript seems to persist across restarts:

```
rm -f "\$HOME/TorBrowser/Data/Browser/profile.default"/{addonStartup.json.lz4,compatibility.ini,extensions.ini,extensions.json}
```

And HTTPS Everywhere is also listed in `about:addons`.

**Comment by xaverdh** [comment]
> Thank you, NoScript is back for me at least for the initial start up after `rm -fR ~/.local/share/tor-browser`.
> 
> EDIT: after a restart, NoScript is gone again :(

By gone, you mean gone from the UI or gone from `about:addons` ?
(for me its just not visible in the UI, but still there and working after restart)

**Comment by xaverdh** [comment]
> If I comment out [this line](https://github.com/NixOS/nixpkgs/blob/7e619b521a22a1c729cca67e234ecaf698043bfa/pkgs/applications/networking/browsers/tor-browser-bundle-bin/default.nix#L290) though, NoScript seems to persist across restarts:
> 
> ```
> rm -f "\$HOME/TorBrowser/Data/Browser/profile.default"/{addonStartup.json.lz4,compatibility.ini,extensions.ini,extensions.json}
> ```
> 
> And HTTPS Everywhere is also listed in `about:addons`.

Unfortunately that *will* capture store paths, if I read the comment there correctly.

**Comment by yurkobb** [comment]
> > Thank you, NoScript is back for me at least for the initial start up after `rm -fR ~/.local/share/tor-browser`.
> > EDIT: after a restart, NoScript is gone again :(
> 
> By gone, you mean gone from the UI or gone from `about:addons` ?
> (for me its just not visible in the UI, but still there and working after restart)

In my second test just now of your PR, NoScript persisted after a restart and didn't disappear from the UI; in my previous test, JS was enabled in the Safest mode and NoScript was missing from the UI (I didn't check about:addons). Looks like it's the same behavior I had with the 9.x versions where addons disappeared unpredictably on restarts - sometimes they persisted, sometimes not.

**Comment by xaverdh** [comment]
> In my second test just now of your PR, NoScript persisted after a restart and didn't disappear from the UI; in my previous test, JS was enabled in the Safest mode and NoScript was missing from the UI (I didn't check about:addons). Looks like it's the same behavior I had with the 9.x versions where addons disappeared unpredictably on restarts - sometimes they persisted, sometimes not.

Thats sad :-(
On my system at least I reliably have noscript up and working across restarts (when building from this pr). At least up to now.
But its doesn't show in the UI, no matter what I do.. maybe the upstream tor browser doesn't show it in the UI either? not sure..

**Comment by yurkobb** [comment]
I think I'll try to use it for a while; anyway, this is better than the original 10.x without NoScript at all. I'm not sure the state of things in 9.x are safe to call "unbroken", who knows what other weird bugs are hidden in there if the UI of the addon disappears.

**Comment by xaverdh** [comment]
Ok, I can now reproduce your issue. NoScript doesn't function from time to time..

**Comment by xaverdh** [comment]
Ok, I went down a different route now, trying to force installation of NoScript via enterprise policies.

**Comment by yurkobb** [comment]
Thank you for investing time into this... I'm too unfamiliar with the architecture of the profile to understand what is going on. I was thinking though - is there a possibility of an altogether different way of using TBB at all, perhaps by using [buildFHSUserEnv](https://nixos.org/manual/nixpkgs/stable/#sec-fhs-environments) and run the unmodified TBB from torproject.org? This way it would self-manage its installation wherever we install it, per-user. What do you think?

**Comment by xaverdh** [comment]
Actually I had the same thought.
Especially since the issue here appears to **not just** be installation of the extension as I initially thought (even with enforcing it through policies `NoScript` appears broken after restarts).
I will look into using `FHSUserEnv` (or the more modern bubblewrap variant) eventually, but if someone wants to beat me to it, feel free to do so ;-)

**Comment by yurkobb** [comment]
I just got the original TBB running in `nix-shell` via a `FHSUserEnv` using this expression (I just copied the dependencies from the `tor-browser-bundle-bin` package, not sure if all of them are strictly required in this case); I will try running it for a while to see how it behaves.

```nix
{ pkgs ? import <nixpkgs> {} }:

(pkgs.buildFHSUserEnv {
  name = "tbb-env";
  targetPkgs = pkgs: (with pkgs;
    [ udev
      zlib
      alsaLib
      curl
      gnutar
      gtk3
      atk
      cairo
      dbus
      dbus-glib
      fontconfig
      freetype
      gdk-pixbuf
      glib
      gtk3
      xorg.libxcb
      xorg.libX11
      xorg.libXext
      xorg.libXrender
      xorg.libXt
      pango
      libpulseaudio
      apulse
      # Media support (implies audio support)
      ffmpeg_3

      gmp

      python27
    ]);
  runScript = "bash";
}).env
```

**Comment by xaverdh** [comment]
Thanks! Here we go: https://github.com/NixOS/nixpkgs/pull/103156

**Pull request closed without merging**
