### PR TITLE
spicetify-cli: init at 1.1.0

### LINKED ISSUE #96419: Packaging Request: spicetify-cli
** spicetify-cli

Allows users to change css, javascript used by the proprietary spotify client

**Metadata**

* Project page:  https://github.com/khanhas/spicetify-cli
* License: gpl3
* Platforms: linux & darwin

spicetify-cli works by making changes to software distributed in the spotify client (css/javascipt).  I'm imaging support for this program in nixpkgs would look somewhat like spicetify-cli's [flatpak](https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-flatpak) support where users would have to tell spicetify-cli where the spotify client files are located. Course this would break as spotify is updated, but that might be a good first step.

Happy to take a swing at this. Is there an existing package that does something similar?

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
was testing my `nix-template` tool, decided to try and package a go package

closes: #96419

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aaronjanse** [comment]
Nice! I think spicetify-cli modifies some files in `/nix/store/*spotify*/`, so users will need a little glue to get this working. Thank you @jonringer!

**Comment by jonringer** [comment]
> Nice! I think spicetify-cli modifies some files in `/nix/store/*spotify*/`, so users will need a little glue to get this working. Thank you @jonringer!

ah, that will probably be upstreamed

**Comment by glittershark** [comment]
When actually running this it looks for `jsHelper` inside of the bin directory - I think we need:
```nix
    postInstall = ''
      cp -r ${src}/jsHelper $out/bin/jsHelper
    '';
```

**Comment by jonringer** [comment]
I don't use spotify anymore...

**Comment by il-mich** [comment]
Are there any updates on this package?

**Comment by aaronjanse** [comment]
I've manually gotten this to modify Spotify, so I plan to package that process next. But I don't have time to do so until at least Thursday, possibly not until next Tuesday. Of course, if someone else is willing to package it, feel free to do so; no need to wait for me

**Comment by aaronjanse** [comment]
I've got a working derivation. Next I'll clean it up for submission to Nixpkgs

https://gist.github.com/aaronjanse/1783a6197d28e0aeda0d9f402175daf6

**Review by aaronjanse — APPROVED** [review]
Thank you @jonringer! This looks great, and I was able to successfully use it to patch Spotify.

Would it be appropriate to submit a Spotify theme wrapper using spicetify-cli [1] to nixpkgs, or should I publish it as a 3rd-party flake?

[1] https://github.com/jonringer/nixpkgs/compare/add-spicetify-cli...aaronjanse:aj-add-spotify-spiced

**Comment by jonringer** [comment]
@aaronjanse I would probably expose themes as something similar to:

```
spotify.theme.spiced
```

implementation being something like:
```
let
  spotify = mkDerivation {
    ...
    passthru = {
       theme = {
         spice = spotify.overide { spotify-unwrapped = spotify-spiced; }
       };
    };
in spotify
```

**Comment by kalbasit** [comment]
Is this PR still in progress? @jonringer can you convert it to Draft if it requires further changes?

**Comment by aaronjanse** [comment]
I think this PR is complete. The discussion above is planning for creating another PR that uses the package added here

**Comment by jonringer** [comment]
I'm going to say that it's working as intended.

Additional improvements can be done in a later PR

**Pull request merged**
