### PR TITLE
pythonPackages: rename dns -> dnspython

### LINKED ISSUE #32404: Rename Python package dns to dnspython
`dnspython` Python package is named `dns` in nixpkgs. Should be renamed to `dnspython` because that is the name of the package in PyPI. Keep the old name available for backwards compatibility until 18.09. Raise deprecation warning if using `dns` instead of `dnspython`.

I would have done this but I couldn't find information on how to do this kind of deprecation.

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Fix #32404

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks!

**Comment by jluttine** [comment]
Here is at least one remaining reference to `dns`: https://github.com/NixOS/nixpkgs/blob/3674d7aa41f457f86a3726af6e83fa81b75e4b43/pkgs/development/python-modules/salmon/default.nix#L1

**Comment by rnhmjoj** [comment]
@jluttine I searched `python-packages.nix` and `pkgs/development/python-modules`.
I also certainly missed all the python applications that depends on it but I can't figure how to look for "dns" in nixpkgs, it's too common.

**Comment by jluttine** [comment]
@rnhmjoj Ok! Would running `nox-review` help to detect those that are affected by this change?

**Comment by rnhmjoj** [comment]
Uhm, sound like a good idea. Remove the alias and see what fails. I'll try it.

**Pull request merged**
