### PR TITLE
vault: 0.11.5 -> 1.0.0

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

HackerNews-driven package upgrade

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by thoughtpolice** [comment]
Ofborg is choking on `aarch64-linux`, though I can't immediately find any recent `aarch64-build` on Hydra. Is this a regression? Maybe we should just restrict vault to x86/Linux, for now?

**Comment by zimbatm** [comment]
@GrahamcOfBorg build vault

**Comment by zimbatm** [comment]
looks like upgrading gox was enough to fix the aarch64 build, but now we have a lot of rebuilds

**Comment by LnL7** [comment]
@GrahamcOfBorg test vault

**Review by LnL7 — APPROVED** [review]

**Comment by zimbatm** [comment]
only 2k builds, I guess it's ok to go into master

**Pull request merged**
