### PR TITLE
perlPackages.Dotenv: init at 0.002

### PR DESCRIPTION
**Pull request by aanderse**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by stigtsp — APPROVED** [review]
Looks good to me

**Comment by aanderse** [comment]
@GrahamcOfBorg build perlPackages.Dotenv perldevelPackages.Dotenv

**Comment by aanderse** [comment]
No! Curse you `perl 5.32`!

**Comment by stigtsp** [comment]
> No! Curse you `perl 5.32`!

`Pod::Parser` was removed from perl 5.32, causing `Pod::Coverage` to fail.

**Comment by aanderse** [comment]
@stigtsp I manage systems for `perl` developers and maintain infrastructure, but don`t (generally) write much/any myself. Any hints on where to go from here?

**Comment by stigtsp** [comment]
> @stigtsp I manage systems for `perl` developers and maintain infrastructure, but don`t (generally) write much/any myself. Any hints on where to go from here?

Adding PodParser as a propagatedBuildInput for PodCoverage seems like the way to go.

When we bump the default perl to 5.32, Pod::Parser will dissappear from it's Module::CoreList. And misc checks in nix-generate-from-cpan (and likely cpan2nix) will start including it as a dependency for new and updated packages.

**Comment by aanderse** [comment]
@stigtsp thanks for the explanation. Is that a PR you would be willing to file? If I had to fill out the "motivation" section on that PR I would have to say "Because @stigtsp said so, and it kinda makes sense to me..." :smile:

**Comment by stigtsp** [comment]
> @stigtsp thanks for the explanation. Is that a PR you would be willing to file?

No prob - I'll have a look to see if there are other modules that need to be updated due to this change in 5.32.

**Comment by stigtsp** [comment]
The `Pod::Parser` issue is mentioned in the perl 5.32.0 bump https://github.com/NixOS/nixpkgs/pull/93036

**Comment by aanderse** [comment]
@GrahamcOfBorg build perlPackages.Dotenv perldevelPackages.Dotenv

**Comment by stigtsp** [comment]
>[..] build perlPackages.Dotenv perldevelPackages.Dotenv

Should mention that the PRs are against staging, and not merged yet. :)

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.Dotenv perldevelPackages.Dotenv

**Comment by stigtsp** [comment]
@aanderse As #93187 has made it's way to master, this now builds. :)

**Comment by aanderse** [comment]
@GrahamcOfBorg build perlPackages.Dotenv perldevelPackages.Dotenv

**Pull request merged**
