### PR TITLE
vimPluginsUpdater: fix treesitter updates

### PR DESCRIPTION
**Pull request by teto**
## Description of changes

WIP 
- vimPluginsUpdater: fix treesitter updates"

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
@GaetanLepage Could you try this version please ? I have had an issue the first time I ran it but then it disappeared, I am not sure if the nix eval realizes the store path :s   
```
nix eval --extra-experimental-features nix-command --impure --json --expr '(import <localpkgs> { }).vimPlugins.nvim-treesitter.src' --nix-path localpkgs=/home/teto/nixpkgs
```

**Comment by GaetanLepage** [comment]
It returns me this:
`"/nix/store/fx980df3w03js4ad1y8c3i9rci5j9gxz-source"`

**Comment by GaetanLepage** [comment]
However, the path in question does not exist in my store...

**Comment by figsoda** [comment]
you might need to use `nix build` with either `--json` or `--print-out-paths`, in addition you can probably use `-f` to save some boilerplate

**Comment by GaetanLepage** [comment]
> you might need to use `nix build` with either `--json` or `--print-out-paths`, in addition you can probably use `-f` to save some boilerplate

```
nixpkgs on  master [$] 
❯ nix build --extra-experimental-features nix-command --impure --json --expr '(import <localpkgs> { }).vimPlugins.nvim-treesitter.src' --nix-path localpkgs=/home/gaetan/perso/nix/nixpkgs
[{"drvPath":"/nix/store/xnk8lsp42zr08i74lmn113yjbsk3q3kv-source.drv","outputs":{"out":"/nix/store/fx980df3w03js4ad1y8c3i9rci5j9gxz-source"}}]

nixpkgs on  master [$] 
❯ ls -l /nix/store/fx980df3w03js4ad1y8c3i9rci5j9gxz-source                                                  
Permissions Size User Group Date Modified Name
dr-xr-xr-x     - root root   1 Jan  1970  assets/
dr-xr-xr-x     - root root   1 Jan  1970  autoload/
dr-xr-xr-x     - root root   1 Jan  1970  contrib/
.r--r--r--   13k root root   1 Jan  1970  CONTRIBUTING.md
dr-xr-xr-x     - root root   1 Jan  1970  doc/
.r--r--r--   11k root root   1 Jan  1970  LICENSE
.r--r--r--   17k root root   1 Jan  1970  lockfile.json
dr-xr-xr-x     - root root   1 Jan  1970  lua/
.r--r--r--   206 root root   1 Jan  1970  Makefile
dr-xr-xr-x     - root root   1 Jan  1970  parser/
dr-xr-xr-x     - root root   1 Jan  1970  parser-info/
dr-xr-xr-x     - root root   1 Jan  1970  plugin/
dr-xr-xr-x     - root root   1 Jan  1970  queries/
.r--r--r--   43k root root   1 Jan  1970  README.md
dr-xr-xr-x     - root root   1 Jan  1970  scripts/
dr-xr-xr-x     - root root   1 Jan  1970  tests/
```

**Comment by teto** [comment]
@GaetanLepage should be good now.

**Comment by GaetanLepage** [comment]
```
path is '/nix/store/9gcnfrxl44gjvdfsrjkgd3q1qln5rzmd-7fd86b7164442d3b5ec2c81b2694d040e716b5cf.tar.gz'
committing to nixpkgs "vimPlugins: update"
path is '/nix/store/rsnxxzavk1xpjcm0zwilzfz1by0sjh24-53e1637a864cb7e8f21af107b8073bc8b24acd11.tar.gz'
1345 plugins were checked
updated pkgs/applications/editors/vim/plugins/generated.nix
committing to nixpkgs "vimPlugins: resolve github repository redirects"
updating nvim-treesitter grammars
Traceback (most recent call last):
  File "/nix/store/ffiqqhi7r079agd3mmpwbmwc9ivswa4i-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 170, in <module>
    main()
  File "/nix/store/ffiqqhi7r079agd3mmpwbmwc9ivswa4i-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 166, in main
    editor.run()
  File "/nix/store/ffiqqhi7r079agd3mmpwbmwc9ivswa4i-vim-plugins-updater-0.1/lib/pluginupdate.py", line 559, in run
    getattr(self, command)(args)
  File "/nix/store/ffiqqhi7r079agd3mmpwbmwc9ivswa4i-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 142, in update
    generated = treesitter.update_grammars(nvim_treesitter_dir)
  File "/nix/store/ffiqqhi7r079agd3mmpwbmwc9ivswa4i-vim-plugins-updater-0.1/lib/treesitter.py", line 77, in update_grammars
    with open(lockfile_path) as lockfile_fd:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/gk88yizs5720sgbgzszyp0vz3dyg3rn8-source\n/lockfile.json'
```
Almost !

**Comment by teto** [comment]
@GaetanLepage we are both victims here, can I victimize you (have you try)  once more ?

**Comment by GaetanLepage** [comment]
Thanks for the fix @teto. It now works.

A few observations:
- The new version of the script seems more obscure and slower than the old version. When I look at the output, I fear that it is doing things twice. For instance `1345 plugins were checked` appears twice.
- Secondly, the plugins update commit as expected, but the nvim-treesitter grammars update the file without committing like it was the case before.

**Comment by teto** [comment]
> The new version of the script seems more obscure and slower than the old version. When I look at the output, I fear that it is doing things twice. For instance 1345 plugins were checked appears twice.

Looking at the code it might appear twice when there are redirects (it runs updates twice). I think this predates the refactor, the cache system is kinda broken, rerunning the script should be instant but instead it rechecks everything, I would prefer to rely on nix caching via nix prefetch like it's done for nvim-treesitter plugins. But that's for someone else or at least not me before 23.11

> Secondly, the plugins update commit as expected, but the nvim-treesitter grammars update the file without committing like it was the case before.

What if you pass --nixpkgs as an argument ? this commits only if detects being in a nixpkgs checkout and the changes might have broken that. But the behaviour when not in a nixpkgs checkout is not well defined, I think it should just skip the treesitter part with a warning probably

**Comment by GaetanLepage** [comment]
All right !
I guess we can merge this ASAP then.
Thank you once again @teto for this fix !

**Comment by teto** [comment]
I'll look into restoring the  autocommit for treesitter if no one beats me to it (feel free). My priority is https://github.com/NixOS/nixpkgs/pull/258819 and it's quite tough

**Pull request merged**
