### PR TITLE
renderdoc: 1.1 -> 1.2

### PR DESCRIPTION
**Pull request by Ralith**
###### Motivation for this change
Routine update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build renderdoc

**Comment by worldofpeace** [comment]
Looking at the [Release Notes](https://github.com/baldurk/renderdoc/releases/tag/v1.2) i think at least the python extensions need testing.

**Comment by Ralith** [comment]
That would be welcome, but should it block the update?

**Comment by worldofpeace** [comment]
IMHO updates should be quality assured if deemed necessary.

**Pull request merged**
