### PR TITLE
pythonPackages.xml2rfc: 2.18.0 -> 2.27.1 (and dependency updates)

### PR DESCRIPTION
**Pull request by JohnAZoidberg**
###### Motivation for this change
Fixes build for `pythonPackages.{xml2rfc,cairocffi,cairosvg}`.
Mark `qiskit` as broken as it requires significant effor to upgrade and fix.

###### Things done

`xml2rfc` successfully converts an XML to a RFC `.txt`

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JohnAZoidberg** [comment]
`nix-review pr 68802` is successful now and xml2rfc works.

Thanks for checking the commit message, that's fixed, too.

**Comment by elohmeier** [comment]
That cairocffi update will help a lot with #68361! Thanks :-)

**Comment by JohnAZoidberg** [comment]
Everything okay? @pandaman @vcunat @yrashk
It'd be really useful to have in 19.09 as it makes lots of packages build again.

Sadly a few of the packages don't have maintainers :( But the tests all run through fine, so that's good.

**Comment by globin** [comment]
This PR has conflicts

**Comment by JohnAZoidberg** [comment]
An update to `pythonPackages.cairocffi` was already merged in #69256.
Needed to update `pythonPackages.weasyprint` now.

`xml2rfc` command still works.

**Review by elohmeier — APPROVED** [review]

**Comment by globin** [comment]
Pushed to master with an additional fix

**Comment by JohnAZoidberg** [comment]
@globin Can you please explain your fix?
```diff
-  # ignore failing test cases
+  # excluded test needs the Ahem font
   checkPhase = ''
     runHook preCheck
-    pytest -k 'not test_table_vertical_align and not test_text_overflow_ellipsis and not test_text_overflow_clip'
+    pytest -k 'not test_font_stretch'
     runHook postCheck
   '';

```

Are the other tests succeeding for you?
On my machine `test_font_stretch` doesn't fail, but the others do.

**Comment by globin** [comment]
After that patch everything worked for me

**Comment by JohnAZoidberg** [comment]
Are you building this derivation?

```
> nix-instantiate -A python3Packages.weasyprint
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/d06ki3nzbmmwlbrzdk6hpsdvvv6h91zk-python3.7-weasyprint-50.drv
```

**Comment by vcunat** [comment]
The derivation you mention [builds on Hydra](https://hydra.nixos.org/build/102138362#tabs-details) and also when I retry it locally.

**Comment by vcunat** [comment]
19.09 seems the same for me ATM. (I don't know if Robin fixed it or it was OK already.)

**Comment by JohnAZoidberg** [comment]
Works for me too, now. Must've messed up something before.

**Pull request closed without merging**
