### PR TITLE
fluffychat: 1.12.1 -> 1.13.0

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
build fails with
```
fluffychat> [        ] /nix/store/fm1xq4f3g48k1mmwl6qg9jc3ipgfsk1x-binutils-2.40/bin/ld: warning: libgbm.so.1, needed by /build/source/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/../third_party/libwebrtc/lib/linux-x64/libwebrtc.so, not found (try using -rpath or -rpath-link)
fluffychat> [        ] /nix/store/fm1xq4f3g48k1mmwl6qg9jc3ipgfsk1x-binutils-2.40/bin/ld: warning: libdrm.so.2, needed by /build/source/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/../third_party/libwebrtc/lib/linux-x64/libwebrtc.so, not found (try using -rpath or -rpath-link)
```

**Comment by NickCao** [comment]
> Say if you need help.

Surely could use some.

Adding ld flags as such can make it build, but still cannot run with broken rpaths.
```diff
-- a/pkgs/applications/networking/instant-messengers/fluffychat/default.nix
+++ b/pkgs/applications/networking/instant-messengers/fluffychat/default.nix
@@ -1,6 +1,8 @@
 { lib
 , fetchFromGitHub
 , imagemagick
+, mesa
+, libdrm
 , flutter
 , makeDesktopItem
 , gnome
@@ -47,6 +49,8 @@ flutter.buildFlutterApplication rec {
       --subst-var out
   '';

+  env.NIX_LDFLAGS = "--as-needed -rpath ${lib.makeLibraryPath [ mesa libdrm ]}";
+
   meta = with lib; {
     description = "Chat with your friends (matrix client)";
     homepage = "https://fluffychat.im/";
```

**Comment by NickCao** [comment]
> Might be worth trying something like `preBuild="export CXXFLAGS="$CXXFLAGS -L${mesa.lib} -lgbm -L${libdrm.lib} -ldrm"`
> 
> what is the error you get when running?

```
$ /nix/store/cxfqjwshlcqnq74qn01w99lyg4la9cv1-fluffychat-1.13.0/bin/fluffychat
/nix/store/cxfqjwshlcqnq74qn01w99lyg4la9cv1-fluffychat-1.13.0/bin/fluffychat: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
$ export LD_LIBRARY_PATH=/nix/store/afajk9q9cvsxcgw22vl9vh53h3bdgcpl-mesa-23.1.4/lib:/nix/store/qx2y7chays0azsb9zfk2qx7z3hjzmvhl-libdrm-2.4.115/lib
$ /nix/store/cxfqjwshlcqnq74qn01w99lyg4la9cv1-fluffychat-1.13.0/bin/fluffychat
#
# Fatal error in: ../../media/engine/adm_helpers.cc, line 39
# last system error: 0
# Check failed: 0 == adm->Init() (0 vs. -1)
# Failed to initialize the ADM.fish: Job 1, '/nix/store/cxfqjwshlcqnq74qn01w…' terminated by signal SIGABRT (Abort)
```

**Comment by NickCao** [comment]
The `Failed to initialize the ADM` could be related to my use of pipewire, not sure though.

**Comment by NickCao** [comment]
> You need to strace it to see what library it tries to open. But as far as memory serves, it needs pulseaudio in the library path?

Wow it does the trick, setting `LD_LIBRARY_PATH` to `lib.makeLibraryPath [ mesa libdrm pulseaudio ]` makes it work.

**Comment by NickCao** [comment]
ping @gilice for another review.

**Review by algorithmiker — APPROVED** [review]
changes look reasonable

**Pull request merged**
