### PR TITLE
appimage-run: add libthai

### LINKED ISSUE #264509: appimage-run unable to find library
### Describe the bug
I'm unable to run [lrcget](https://github.com/tranxuanthang/lrcget/releases/tag/0.2.1) with NixOS intended way, with `appimage-run`
I was able to run it with `$LD_LIBRARY_PATH` but loading not `libthai` as I guess it should but from steam-run's libs.

### Steps To Reproduce
1. Download appimage
2. Try to run it with appimage-run
3. set `LD_LIBRARY_PATH` to steam-run's libs (I've found one with `fd libthai /nix/store `)

### Expected behavior
Able to `appimage-run ./lrcget_0.2.1_amd64.AppImage`

### Screenshots
```
Downloads ➤ appimage-run ./lrcget_0.2.1_amd64.AppImage
lrcget_0.2.1_amd64.AppImage installed in /home/casual/.cache/appimage-run/81d13ad0c4c1c358a939bad4ab318fab443461ccd02f9e1061329c8d8a58ceb9
lrcget: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

Downloads ➤ nix-shell -p libthai
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/wc0w5s93apa8izklkh2dmmzg497x96ds-libthai-0.1.29-dev
copying path '/nix/store/wc0w5s93apa8izklkh2dmmzg497x96ds-libthai-0.1.29-dev' from 'https://cache.nixos.org'...

[nix-shell:~/Downloads]$ appimage-run ./lrcget_0.2.1_amd64.AppImage
lrcget_0.2.1_amd64.AppImage installed in /home/casual/.cache/appimage-run/81d13ad0c4c1c358a939bad4ab318fab443461ccd02f9e1061329c8d8a58ceb9
lrcget: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

[nix-shell:~/Downloads]$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/nix/store/7irqfyfwpab9gm9z5hgvg9xjn2ph0mh1-libthai-0.1.29/lib appimage-run ./lrcget_0.2.1_amd64.AppImage           
lrcget_0.2.1_amd64.AppImage installed in /home/casual/.cache/appimage-run/81d13ad0c4c1c358a939bad4ab318fab443461ccd02f9e1061329c8d8a58ceb9
lrcget: error while loading shared libraries: libthai.so.0: wrong ELF class: ELFCLASS32

[nix-shell:~/Downloads]$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/nix/store/7qmljwan3x9k6mdfyx79h5z27fjy7cg1-steam-run-usr-target/lib/ appimage-run ./lrcget_0.2.1_amd64.AppImage
lrcget_0.2.1_amd64.AppImage installed in /home/casual/.cache/appimage-run/81d13ad0c4c1c358a939bad4ab318fab443461ccd02f9e1061329c8d8a58ceb9
Could not determine the accessibility bus address
Database file path: /home/casual/.local/share/net.lrclib.lrcget/db.sqlite3
*App runs normally*
...
```

### Additional context
I guess it may be related to errors in lrcget itself but before making issue at their repo I want to consult with you as there is no similar issues at their repo.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.8-zen1, NixOS, 23.11 (Tapir), 23.11.20231026.63678e9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-23.05, nixpkgs"`
 - channels(casual): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

### PR DESCRIPTION
**Pull request by SuperSamus**
## Description of changes

It is on the list: https://github.com/AppImageCommunity/pkg2appimage/blame/3076946d2cc4f4909d7927f9477e3178d5c04d02/excludelist#L123
Closes #264509.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by haruki7049** [comment]
I cloned [SuperSamus/nixpkgs](https://github.com/SuperSamus/nixpkgs) and ran `git checkout appimage-libthai`

next, I ran below commands:
```bash
nix-build -E 'with import <nixpkgs> {}; callPackage ./package.nix {}'
./result/bin/immersed-vr
```
then I got this error: 
```
Immersed: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory
```

my environment is:
```md
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.928.50aa30a13c4a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Review by haruki7049 — CHANGES_REQUESTED** [review]
I cloned [SuperSamus/nixpkgs](https://github.com/SuperSamus/nixpkgs) and ran `git checkout appimage-libthai`

next, I ran below commands:
```bash
nix-build -E 'with import <nixpkgs> {}; callPackage ./package.nix {}'
./result/bin/immersed-vr
```
then I got this error: 
```
Immersed: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory
```

my environment is:
```md
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.928.50aa30a13c4a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

what can I do?

**Comment by SuperSamus** [comment]
>```
>nix-build -E 'with import <nixpkgs> {}; callPackage ./package.nix {}'
>```

`with import <nixpkgs>` means that you are using main version of nixpkgs (instead of the local one) that doesn't have libthai in appimage-run. But with `./package.nix` you are using the local version of immersed-vr, which also doesn't have libthai.

You are supposed to do `nix-build -A immersed-vr` from the root of your nixpkgs.
Alternatively:
```
nix-build -E 'with import <nixpkgs> {}; pkgs.immersed-vr' -I nixpkgs=path/to/your/nixpkgs
```

**Comment by haruki7049** [comment]
OK. I'll try that. Thank you!!

**Review by haruki7049 — APPROVED** [review]
I've confirmed that this works fine!! LGTM!!

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
