### PR TITLE
hyperscan: 5.1.0 -> 5.1.1

### PR DESCRIPTION
**Pull request by dtzWill**
* provide misc utils needed by build

###### Motivation for this change

https://github.com/intel/hyperscan/releases/tag/v5.1.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by tomberek — CHANGES_REQUESTED** [review]
Reverse dependency rspamd failed to build:
```
builder for '/nix/store/bxhx78ybg92zycgb2am7wnfn05bcanvj-rspamd-1.9.0.drv' failed with exit code 2; last 10 log lines:
   #include "hs.h"
            ^~~~~~
  compilation terminated.
  make[2]: *** [src/CMakeFiles/rspamd-server.dir/build.make:618: src/CMakeFiles/rspamd-server.dir/libutil/map_helpers.c.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  make[1]: *** [CMakeFiles/Makefile2:1541: src/CMakeFiles/rspamd-server.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 62%] Linking C shared library libTH.so
  [ 62%] Built target TH
  make: *** [Makefile:130: all] Error 2

```

**Comment by c0bw3b** [comment]
Well not sure where `nm` should come from on Darwin so I'm going to restrict this to Linux platforms, as is rspamd already.

**Review by tomberek — APPROVED** [review]
Builds and runs now. Including rspamd.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build rspamd

**Pull request merged**
