### PR TITLE
Fix desktop tests

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
https://hydra.nixos.org/build/100471962
https://hydra.nixos.org/build/100471851
https://hydra.nixos.org/build/100472011

A lot of these tests, though strangely not all, were failing at the
```
$machine->succeed("getfacl /dev/snd/timer | grep -q alice");
```

step which seems to also be done in the login test.

The same issue popped up there so I duplicated the fix https://github.com/NixOS/nixpkgs/commit/f59b4cb8d545d3bb1bd954f9e3267cb7ebec3557.
In general all these tests could be nicer.

I also took the liberty to bump the `memorySize` for the xfce tests https://github.com/NixOS/nixpkgs/commit/5b42b1f40158f6ee6277bab8bb59c5360d2153e0 https://github.com/NixOS/nixpkgs/commit/9f43d809b32c7f0ee3ce13ff3a3454ab7e2e9d18 to what all the other desktop tests have.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
cc @andir as you authored https://github.com/NixOS/nixpkgs/commit/f59b4cb8d545d3bb1bd954f9e3267cb7ebec3557 and systemd bump.

**Comment by andir** [comment]
I do wonder if we shouldn't default sound to enabled when a DE is activated.

**Comment by worldofpeace** [comment]
Just realized that certain DE's enable pulseaudio which in turn enables sound. Probably why in certain cases it wasn't failing.

> I do wonder if we shouldn't default sound to enabled when a DE is activated.

It's only like that for certain modules with pulseaudio.

**Comment by worldofpeace** [comment]
I've opted to just enable pulseaudio in those particular tests.

**Comment by worldofpeace** [comment]
backported in b0e36731a8b7cd110ae20e3a65321c354c3ea688...c6332a7fbfd01673ed552a9e291e87d6f621427a

**Pull request merged**
