### PR TITLE
Python packages fixes

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by gebner** [comment]
@FRidh Can you revert the shippai update 0bca28c89078ddc25aca0c1f8c50d3bafdd36412?  This breaks vdirsyncer.

**Comment by FRidh** [comment]
@gebner done f26e5b5

**Comment by FRidh** [comment]
python-jose/moto/botocore is quite a pain to solve

**Comment by FRidh** [comment]
Might have to revert the botocore/boto3 bumps, and let awscli "vendor" different versions.

**Comment by dotlambda** [comment]
A propos `pytest-fixture-config`, should we just set `doCheck = false`?

**Comment by dotlambda** [comment]
Rebasing onto latest `staging-next` so the fixes in master are taken into consideration.

**Comment by dotlambda** [comment]
@FRidh Do you have the rights to restart a Hydra job? Pyparted builds fine for me.

**Comment by FRidh** [comment]
@dotlambda no I cannot

**Comment by vcunat** [comment]
Apparently that error happens in Hydra's cloud instances and not elsewhere: https://hydra.nixos.org/build/80376351#tabs-buildsteps  (for me it always succeeds locally, too)

**Comment by vcunat** [comment]
Waiting for something before merging to `staging-next`?

**Pull request merged**
