### PR TITLE
Update strings.nix

### PR DESCRIPTION
**Pull request by rick68**
fix a mistake of lib.strings.addContextFrom

### CODE REVIEW

**Comment by vcunat** [comment]
No, I'm fairly certain it's intentional, and after this PR it surely wouldn't make any sense. *String contexts* are a rather tricky thing, as they certainly aren't common in other languages and we probably don't document them https://github.com/NixOS/nix/issues/280. However, one almost never needs to know about them, especially after https://github.com/NixOS/nixpkgs/pull/2883.

**Comment by rick68** [comment]
This is my test code:
``` nix
#! /usr/bin/env nix-instantiate --eval

with import <nixpkgs> {};

let
  f = lib.strings.addContextFrom;
  a = "foo";
  b = "bar";
  result = f a b;
in
  builtins.toJSON result
```
Result:
``` shell
"\"bar\""
```
I expect that the result is `"\"foobar\""`, but it's not.

**Comment by vcunat** [comment]
> I expect that the result is "\"foobar\"", but it's not.

I'm very certain that function isn't meant to do concatenation. It was created more as a refactoring in  #2883. Context is roughly about whether a string "depends" on a path from nix store (e.g. contains a path from it).

**Comment by vcunat** [comment]
Specifically: regular strings have an empty context, and context isn't "visible" in the string.

**Pull request closed without merging**
