### PR TITLE
 firefox, firefox-bin: 80.0.1 -> 81.0,  firefox-esr: 78.2.0esr -> 78.3.0esr [High security fixes]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- High security fixes
- Other changes and fixes.

https://www.mozilla.org/en-US/firefox/81.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2020-42/

https://www.mozilla.org/en-US/firefox/78.3.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2020-43/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Note

Firefox 81 requires `MACH_USE_SYSTEM_PYTHON` or `virtualenv` in HOME.

### CODE REVIEW

**Review by kevincox — APPROVED** [review]

**Review by ajs124 — APPROVED** [review]

**Comment by mohe2015** [comment]
Shouldn't this be merged ASAP if these are high security fixes?

**Comment by kevincox** [comment]
Since @taku0 has permissions I was letting him merge in case there is anything that remains to be done.

**Comment by taku0** [comment]
I don't have privilege to merge. I'm a `nixpkgs-maintainers` member but not `nixpkgs-committers`. I don't see a merge button on this page.

**Comment by kevincox** [comment]
My mistake! I'll need to check up on what the different groups mean.

**Comment by vcunat** [comment]
The "Member" badge is unfortunately a bit confusing in this way.  IIRC it was a known downside when creating the -maintainers team.

**Pull request merged**
