### PR TITLE
dwm-status: init at 0.4.0

### PR DESCRIPTION
**Pull request by Gerschtli**
###### Motivation for this change

Inits my own `dwm-status` package at version 0.4.0.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantm** [comment]
It looks like there is already another project by this name packaged by AUR and crates.io https://repology.org/metapackage/rust-dwm-status/versions https://github.com/pierrechevalier83/rust-dwm-status. Can you comment on why yours has the same name, how it differs, and if you are planning to publish it to crates.io too?

**Comment by Gerschtli** [comment]
Thats not correct. The package you mentioned has the name `rust-dwm-status`, mine is simply called `dwm-status` and it is already published at crates.io: https://crates.io/crates/dwm-status

The difference to `rust-dwm-status` is, that my package is more efficient because it listens for dbus signals or file changes and it is more configurable, so that you can use different ordering of elements in the status bar. I'm planning to add more configuration options if I have the time or anyone shows interest in my package.

**Comment by ryantm** [comment]
@GrahamcOfBorg build dwm-status

**Comment by Gerschtli** [comment]
@ryantm Do you have an idea how to fix the error on darwin?

**Comment by Gerschtli** [comment]
You are right, I don't expect this package to be run on Darwin, fixed it

**Comment by Gerschtli** [comment]
And the aarch64 build failure is caused by the usual timeout with rust packages..

**Comment by xeji** [comment]
@GrahamcOfBorg  build dwm-status

**Comment by andir** [comment]
Have you considered declaring the runtime dependency "xsetroot" in the package? It probably only works (on NixOS) because the xserver module puts that binary in the system path. If you are running dwm-status on any non-nixos system that is using nix that will probably fail (unless it is in the PATH by accident).

**Comment by Gerschtli** [comment]
That sounds reasonable, `xorg.xsetroot` and optionally `alsaUtils` should be included as runtime dependencies. I will open another PR to add these.

Thank you!

**Pull request merged**
