### PR TITLE
rustc: wrap llvmPackages when using LLVM with callPackage

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Description of changes

CC @trofi

Use `callPackage` with `pkgsLLVM.rustc.llvmPackages` so it fixes eval with Firefox, Betterbird, etc.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
How did you test the eval? Maybe I'm doing it wrong. It fails for me as:

```
$ nix eval github:NixOS/nixpkgs/pull/330754/head#pkgsLLVM.betterbird-unwrapped
error:
       … while calling a functor (an attribute set with a '__functor' attribute)
         at /nix/store/7fzm97kg6m5nh0623wx1b5h45n6g05g0-source/lib/customisation.nix:264:13:
          263|     in if missingArgs == {}
          264|        then makeOverridable f allArgs
             |             ^
          265|        # This needs to be an abort so it can't be caught with `builtins.tryEval`,

       … while evaluating a branch condition
         at /nix/store/7fzm97kg6m5nh0623wx1b5h45n6g05g0-source/lib/customisation.nix:148:7:
          147|     in
          148|       if isAttrs result then
             |       ^
          149|         result // {

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'stdenv' missing
       at /nix/store/7fzm97kg6m5nh0623wx1b5h45n6g05g0-source/pkgs/applications/networking/browsers/firefox/common.nix:177:28:
          176|   # LTO requires LLVM bintools including ld.lld and llvm-ar.
          177|   buildStdenv = overrideCC llvmPackages.stdenv (llvmPackages.stdenv.cc.override {
             |                            ^
          178|     bintools = if ltoSupport then buildPackages.rustc.llvmPackages.bintools else stdenv.cc.bintools;

$ nix eval github:NixOS/nixpkgs/pull/330754/merge#pkgsLLVM.betterbird-unwrapped
error:
       … while calling a functor (an attribute set with a '__functor' attribute)
         at /nix/store/7fzm97kg6m5nh0623wx1b5h45n6g05g0-source/lib/customisation.nix:264:13:
          263|     in if missingArgs == {}
          264|        then makeOverridable f allArgs
             |             ^
          265|        # This needs to be an abort so it can't be caught with `builtins.tryEval`,

       … while evaluating a branch condition
         at /nix/store/7fzm97kg6m5nh0623wx1b5h45n6g05g0-source/lib/customisation.nix:148:7:
          147|     in
          148|       if isAttrs result then
             |       ^
          149|         result // {

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'stdenv' missing
       at /nix/store/7fzm97kg6m5nh0623wx1b5h45n6g05g0-source/pkgs/applications/networking/browsers/firefox/common.nix:177:28:
          176|   # LTO requires LLVM bintools including ld.lld and llvm-ar.
          177|   buildStdenv = overrideCC llvmPackages.stdenv (llvmPackages.stdenv.cc.override {
             |                            ^
          178|     bintools = if ltoSupport then buildPackages.rustc.llvmPackages.bintools else stdenv.cc.bintools;
```

Moving formatting changes to a separate commit might get it a bit easier to review what the PR changes WRT evaluation.

**Comment by RossComputerGuy** [comment]
> How did you test the eval?

`nix repl`. I just looked at my repl history and it seemed I wrongfully assumed the fix worked fully because I am used to the Nixpkgs LLVM WS flake automatically using `pkgsLLVM` with `legacyPackages`. I can finish up this fix easily.

**Comment by RossComputerGuy** [comment]
Ok, it works now.

**Comment by trofi** [comment]
The `pkgsLLVM.betterbird-unwrapped` eval succeeds now. Thank you!

**Comment by RossComputerGuy** [comment]
Only the manual rebuilds on x86_64-linux for some reason but it looks like this is ready and we probably should get it in before #332153, I'll merge if there's no objections.

**Pull request merged**
