### PR TITLE
Systemd package rewrite

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Artturin** [comment]
This shouldn't have gone to master

**Comment by Artturin** [comment]
Or did you rework it in to a 0 rebuild but ofborg didn't notice? I checked locally and the hashes didn't change?

**Comment by Artturin** [comment]
There's a diff in systemdMinimal

```
+ /nix/store/7pxp8bgm6g7lbrksklsr8i39b1a4z7kx-systemd-minimal-libs-254.3.drv:{dev}
      • The environments do not match:
          mesonFlags=''
          -Dversion-tag=254.3 -Dtime-epoch=1690536449 -Dmode=release -Ddbuspolicydir=/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9/share/dbus-1/system.d -Ddbussessionservicedir=/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9/share/dbus-1/services -Ddbussystemservicedir=/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9/share/dbus-1/system-services -Dpam=false -Dpamconfdir=/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9/etc/pam.d -Drootprefix=/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9 -Dpkgconfiglibdir=/02qcpld1y6xhs5gz9bchpxaw0xdhmsp5dv88lh25r2ss44kh8dxz/lib/pkgconfig -Dpkgconfigdatadir=/02qcpld1y6xhs5gz9bchpxaw0xdhmsp5dv88lh25r2ss44kh8dxz/share/pkgconfig -Dloadkeys-path=/nix/store/h61z387009jczng21m881kr10lys2f2w-kbd-2.6.3/bin/loadkeys -Dsetfont-path=/nix/store/h61z387009jczng21m881kr10lys2f2w-kbd-2.6.3/bin/setfont -Dtty-gid=3 -Ddebug-shell=/nix/store/x88ivkf7rmrhd5x3cvyv5vh3zqqdnhsk-bash-interactive-5.2-p15/bin/bash -Dglib=false -Dtests=false -Dacl=false -Danalyze=false -Daudit=false -Dgcrypt=false -Dimportd=false -Dlz4=false -Dhomed=false -Dlogind=false -Dlocaled=false -Dhostnamed=false -Dmachined=false -Dnetworkd=false -Doomd=false -Dpolkit=false -Dlibcryptsetup=false -Dportabled=false -Dhwdb=false -Dremote=false -Dtimedated=false -Dtimesyncd=false -Duserdb=false -Dcoredump=false -Dfirstboot=false -Dresolve=false -Dsplit-usr=false -Dlibcurl=false -Dlibidn=false -Dlibidn2=false -Dfirstboot=false -Dsysusers=false -Drepart=false -Dsysupdate=false -Dquotacheck=false -Dldconfig=false -Dsmack=true -Db_pie=true -Dinstall-sysconfdir=false -Dsbat-distro=nixos -Dsbat-distro-summary=NixOS -Dsbat-distro-url=https://nixos.org/ -Dsbat-distro-pkgname=systemd-minimal-libs -Dsbat-distro-version=254.3 -Dsystem-uid-max=999 -Dsystem-gid-max=999 -Dsysvinit-path= -Dsysvrcnd-path= -Dsulogin-path=/nix/store/05dii7y9kgxz85yv31kgpc0dmwgnmyvp-util-linux-minimal-2.39.2-login/bin/sulogin -Dnologin-path=/nix/store/05dii7y9kgxz85yv31kgpc0dmwgnmyvp-util-linux-minimal-2.39.2-login/bin/nologin -Dmount-path=/nix/store/904n4i7lf2q4y3n4q8rnhdwlgx0vlic3-util-linux-minimal-2.39.2-mount/bin/mount -Dumount-path=/nix/store/904n4i7lf2q4y3n4q8rnhdwlgx0vlic3-util-linux-minimal-2.39.2-mount/bin/umount -Dcreate-log-dirs=false -Ddefault-hierarchy=unified -Dman=true -Defi=false -Dbootloader=false -Dukify=false -Dbashcompletiondir=no -Dzshcompletiondir=no -Dnss-myhostname=false -Dnss-mymachines=false -Dnss-resolve=false -Dnss-systemd=false -Dbpf-framework=false -Dtpm2=false -Dutmp=true -Dgshadow=true -Didn=true -Dkmod=true -Dkmod-path=/nix/store/djaryncvgyybm8qrzznhxby2wsbdvh8l-kmod-31/bin/kmod
```

**Comment by Artturin** [comment]
eab0837b6803f776a5eb055ffcc9c8041807036a caused them

https://github.com/NixOS/nixpkgs/pull/270024

**Comment by RaitoBezarius** [comment]
Also, pardon me but why did you bypass the systemd team @AndersonTorres ? This is a critical package, this is inacceptable.

**Comment by AndersonTorres** [comment]
> Also, pardon me but why did you bypass the systemd team @AndersonTorres ? This is a critical package, this is inacceptable.

I believed in my local build and in the ofBorg statuses, sorry.

**Comment by RaitoBezarius** [comment]
> > Also, pardon me but why did you bypass the systemd team @AndersonTorres ? This is a critical package, this is inacceptable.
> 
> I believed in my local build and in the ofBorg statuses, sorry.

Even if you believed in your local builds and in the ofBorg statuses, how can we expect this change to be acceptable from the systemd maintainer community in nixpkgs?

**Comment by arianvp** [comment]
Please re-open a new PR targeting staging and tag @NixOS/systemd for review.

**Comment by AndersonTorres** [comment]
> how can we expect this change to be acceptable from the systemd maintainer community in nixpkgs?

The current code is not good.

**Comment by Kloenk** [comment]
> The current code is not good.

Interesting description of change. please also add somewhat motivation to the next pr. I was waiting with even really looking at the code for a at least one sentence why description.

**Comment by arianvp** [comment]
> The current code is not good.

I think we all agree the packaging is a bit of a mess so I am happy you're improving it.  It's not a good excuse to bypass review though. It's actually better to get review in that case so we all know what changed and what the impact for is for maintenance. :).

Review would also have caught the accidental merge to `master` (Systemd changes must always go to `staging`)

So yeh. Feel free to re-open this PR.

**Comment by nikstur** [comment]
Also v255 changes many of the meson options to features so we would have needed to change much of this PR yet again. IMHO there is no reason to switch to the lib.meson* functions before v255

**Comment by AndersonTorres** [comment]
> Interesting description of change.

1. This thread is already dead, I am not interested on defending my egregious error of ignoring the review;
2. I will have plenty of room to discuss the ugliness of this code in a next iteration;
3. The next iteration will wait a little more, [since new code was committed](https://github.com/NixOS/nixpkgs/pull/262952);
4. New systemd will be released soon, so I will wait a little bit more (above the a little more above).

**Pull request merged**
