### PR TITLE
ocamlPackages.{ipaddr,macaddr}: 3.1.0 → 5.0.0 and update all affected packages (tuntap, conduit, cohttp, …)

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

<https://github.com/mirage/ocaml-ipaddr/releases/tag/v5.0.0> etc.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build jackline ocamlPackages.eliom ocamlPackages.cohttp-lwt-unix ocamlPackages.irmin-unix ocamlPackages.mirage-runtime ocamlPackages.tuntap ocamlPackages.opium

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build jackline ocamlPackages.eliom ocamlPackages.cohttp-lwt-unix ocamlPackages.irmin-unix ocamlPackages.mirage-runtime ocamlPackages.tuntap ocamlPackages.opium

**Comment by sternenseemann** [comment]
`cohttp-lwt-unix` now requires dune 2 to build, unfortunately now every package which (indirectly?!) depends on that package willl also require dune 2. I tried to fix every instance of that, lmk if I missed one.

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build jackline ocamlPackages.eliom ocamlPackages.cohttp-lwt-unix ocamlPackages.irmin-unix ocamlPackages.mirage-runtime ocamlPackages.tuntap ocamlPackages.opium ocamlPackages.ocsigen-start ocamlPackages.curly

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build jackline ocamlPackages.eliom ocamlPackages.cohttp-lwt-unix ocamlPackages.irmin-unix ocamlPackages.mirage-runtime ocamlPackages.tuntap ocamlPackages.opium ocamlPackages.ocsigen-start ocamlPackages.curly

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocaml-ng.ocamlPackages_4_07.cohttp-lwt

**Comment by vbgl** [comment]
The update of `mirage-runtime` has been merged into `master` as 324c353ee3dff7f0d6050bc0043bad5cf74b20b3

**Comment by sternenseemann** [comment]
A bit puzzled by the build error in `cohttp-lwt`. Is there a difference between 4.07 lwt and 4.08 and later lwt?

**Comment by vbgl** [comment]
In `nixpkgs` OCaml 4.07 and 4.08 have identical versions of lwt. However, they have different versions of `ppx_sexp_conv`.

**Comment by sternenseemann** [comment]
Best fix is probably to add a check for the version of `ppx_sexp_conv` then? `cohttp-lwt` depends on `ppx_sexp_conv` >= 0.13.0, but the latter doesn't build on OCaml 4.07.

**Comment by vbgl** [comment]
Why not. Or just raise the `minimumOCamlVersion` attribute of `cohttp-lwt`.

**Comment by sternenseemann** [comment]
Added a check for the version of `ppx_sexp_conv` in 8e368f787ee94861617aa2e562446257403be4da.

**Pull request merged**
