### PR TITLE
 nixos/geoclue2: restructure module made by worldofpeace

### PR DESCRIPTION
**Pull request by leotaku**
###### Motivation for this change

Changes to pull request #45306, motivations discussed there.

Restructured the module to use the `generators.toINI` function.
I hope this fits what @michaelpj had in mind, please give me some feedback.

Also, if I understand everything correctly, the still-active review by @Infinisil has already been addressed in the initial pr.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by leotaku** [comment]
Also, I would appreciate if somebody could help me with finding a fix for the following problem:
When the service configuration is changed, the `/etc/geoclue/geoclue.conf` file gets changed, but the geoclue service does not restart. (because nixos does not know that this service depends on the file)

**Comment by worldofpeace** [comment]
> Also, I would appreciate if somebody could help me with finding a fix for the following problem:
> When the service configuration is changed, the `/etc/geoclue/geoclue.conf` file gets changed, but the geoclue service does not restart. (because nixos does not know that this service depends on the file)

maybe
```
systemd.services.geoclue.restartTriggers = [ "/etc/geoclue/geoclue.conf" ];
```

Though I don't know how geoclue handles changes to the config file, and just maybe reloads as expected?

**Comment by leotaku** [comment]
> Though I don't know how geoclue handles changes to the config file, and just maybe reloads as expected?

It does not. I have implemented your suggestion into the module.

**Review by michaelpj — APPROVED** [review]
LGTM!

**Review by worldofpeace — CHANGES_REQUESTED** [review]
We're missing configuration that's upstream default, see what was removed in this commit https://github.com/NixOS/nixpkgs/pull/45306/commits/807f3f3b888e87cc6219ced46db94c2972286c28.

**Comment by leotaku** [comment]
@worldofpeace I hope that was what you meant? I hope so, otherwise @ me and I will revert and change what is needed.

**Comment by worldofpeace** [comment]
That's what I meant @leotaku, but we also need
```nix
services.geoclue2.appConfig."io.elementary.desktop.agent-geoclue2" = {
  isAllowed = true;
  isSystem = true;
};
```

in the `pantheon.nix` module.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
see above comment

**Comment by worldofpeace** [comment]
Fixed up the commit msg's there and added myself as a coauthor.

Going to test this with GNOME3 and Pantheon and then I think we should be good to merge :+1:

**Comment by leotaku** [comment]
Great!

Off-topic but is there some explanation on how working on other contributors pull requests/co-authoring works? I don't really know how to use these features which was why I created a separate pull request in the first place.

**Comment by worldofpeace** [comment]
> Off-topic but is there some explanation on how working on other contributors pull requests/co-authoring works? I don't really know how to use these features which was why I created a separate pull request in the first place.

For making a multi author commit this should probably explain that https://help.github.com/en/articles/creating-a-commit-with-multiple-authors.

Usually though what you can do is open a pr against my fork trying to merge your fixes into my branch.
Or I maybe could have added you as a temporary collaborator to my fork. Though that depends if you know the person still cares about x change.

Either way I'm happy to see this continued :+1:

**Review by worldofpeace — APPROVED** [review]
Tested that GeoClue functionality in gnome-weather, gnome-maps, and gnome-calendar are unaffected by this change.

**Pull request merged**
