### PR TITLE
linuxHeaders: 5.12 -> 5.14

### PR DESCRIPTION
**Pull request by trofi**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Fixed `libsanitizer` build on `gcc` and `compiler-rt` packages.

### CODE REVIEW

**Comment by veprbl** [comment]
Why skip gcc 4.8?

**Comment by trofi** [comment]
> Why skip gcc 4.8?

4.8 did not require patching (`nix build -f . gcc48` worked as is). Looking at the `libsanitizer` directory in `gcc-4.9` `ioctl` interceptors are not there yet.

I guess it was added at gcc-4.9+ times. Maybe in https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=ef1b3fda32c08e9bd6977b96e1e619aae3e3726a

**Comment by Mic92** [comment]
I reverted https://github.com/NixOS/nixpkgs/pull/138465 in this PR.

**Comment by vcunat** [comment]
This approach to reverting won't work (I believe), as normal 3-way merge will auto-resolve it the "wrong" way.  I... suppose it's off-topic to explain in depth why.  A simple rebase (to some commit past PR #138465) would auto-resolve it the "right" way ™️

**Comment by trofi** [comment]
I rebased this PR against current `staging`. I hope it's intended result.

I assume something is controversial here (missing one-off world rebuild? i don't know how to trigger it).

Should I move gcc/llvm fixes to a separate PR if it helps them get merged faster? I'm afraid I'm about to send more patches against `llvm` and `gcc` to support gcc-11 and that would conflict in `patches = ` area.

**Comment by vcunat** [comment]
Patches to (the default) gcc would cause a mass rebuild and need to go through `staging` anyway.  I don't think this PR is controversial, really.

**Review by vcunat — APPROVED** [review]
Looks good enough for `staging`.  I built some packages locally.

**Pull request merged**
