### PR TITLE
teamviewer: 15.26.4 -> 15.29.4

### PR DESCRIPTION
**Pull request by nazarewk**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`), see http://github.com/nazarewk-iac/nix-configs/commit/70aff45f
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by nazarewk** [comment]
note i've tested it through https://github.com/nazarewk-iac/nix-configs/commit/70aff45f90f7f8cfd02e79cdf91d9012298dc73f

**Comment by nazarewk** [comment]
I'm figuring out following errors:
```
May 09 13:25:44 nazarewk-krul teamviewerd[2914621]: sh: line 1: su: command not found
May 09 13:25:44 nazarewk-krul teamviewerd[2914620]: qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
May 09 13:25:44 nazarewk-krul teamviewerd[2914620]: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. 
```

**Comment by cole-h** [comment]
@ofborg eval

**Comment by nazarewk** [comment]
looks like above errors are not related to the update, don't really know where is the `su` error thrown or how to fix it

**Comment by SuperSandro2000** [comment]
> looks like above errors are not related to the update, don't really know where is the `su` error thrown or how to fix it

Yeah, you can ignore the ofborg error. Just restart it after it failed and the other stuff is handled by other people.

**Pull request merged**
