### PR TITLE
mcpelauncher: init at 0.9.0

### LINKED ISSUE #231875: Package request: mcpelauncher
**Project description**

An unofficial launcher for Minecraft Bedrock Edition

**Metadata**

* homepage URL: [https://mcpelauncher.readthedocs.io](https://mcpelauncher.readthedocs.io)
* source URL: [https://github.com/minecraft-linux/mcpelauncher-manifest](https://github.com/minecraft-linux/mcpelauncher-manifest)
* license: GPL 3.0
* platforms: Linux and Darwin

### PR DESCRIPTION
**Pull request by Aleksanaa**
###### Description of changes

Resolves https://github.com/NixOS/nixpkgs/issues/231875

Things still have to do:

- [ ] Build and test on darwin.
- [ ] ~~Add mcpelauncher-msa for xbox login support.~~
- [ ] Add qt6 build.
- [ ] Add optional glfw support.
- [ ] Add a mcpelauncher-full `symlinkJoin` wrapper.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Aleksanaa** [comment]
@VergeDX could you try to compile client with `-DBUILD_WEBVIEW=OFF` and login into xbox account with msa-ui-qt? Cmake says the webview is used for login into xbox.

**Comment by Aleksanaa** [comment]
Okay, it seems that msa is deprecated. https://github.com/minecraft-linux/msa-manifest/issues/3#issuecomment-1165362299

**Comment by Aleksanaa** [comment]
The problem: I've added a patch
```patch
diff --git a/ext/glfw.cmake b/ext/glfw.cmake
index 5487f32..feeb89f 100644
--- a/ext/glfw.cmake
+++ b/ext/glfw.cmake
@@ -1,18 +1,2 @@
-include(FetchContent)
-
-set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
-set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
-set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
-set(GLFW_INSTALL OFF CACHE BOOL "" FORCE)
-
-FetchContent_Declare(
-        glfw3_ext
-        URL "https://github.com/minecraft-linux/glfw/archive/fce9121962bc0a21c39e2d6f8e08bad30c566c72.zip"
-)
-
-FetchContent_GetProperties(glfw3_ext)
-if(NOT glfw3_ext_POPULATED)
-  FetchContent_Populate(glfw3_ext)
-  add_subdirectory(${glfw3_ext_SOURCE_DIR} ${glfw3_ext_BINARY_DIR})
-endif()
-add_library(glfw3 ALIAS glfw)
\ No newline at end of file
+add_library(glfw3 INTERFACE IMPORTED)
+#add_library(glfw3 ALIAS glfw)
```

And `glfw` to `buildInputs` (also `qt5.qttools` for some reasons), so it should be linked together (definition in https://github.com/minecraft-linux/game-window/blob/51da20b8ad2cf946c5428e8564f9fc2e9ae2ca4b/CMakeLists.txt#L20). However, ld throws a lot of `undefined reference to` that I've checked carefully in `/nix/store/<pkgs.glfw>/include/GLFW`. They are there. I don't know if it's because I don't understand cmake or something.

**Comment by Henry-Hiles** [comment]
Have you had any progress since then? Is this functional?

**Comment by Aleksanaa** [comment]
Okay let's go ahead

**Comment by Aleksanaa** [comment]
Outdated

**Pull request closed without merging**
