### PR TITLE
setuid-wrappers: Update wrapper dir atomically.

### LINKED ISSUE #18124: setuid-wrapper activationScript is not atomic
It's currently possible to cancel `nixos-rebuild` between deletion of previous setuid wrappers and population of new ones. And yes, I've been able to lock myself out of machine (almost, if I didn't have root ssh key).

Current implementation: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/setuid-wrappers.nix#L118-L120

Proposed implementation (see at the bottom of blog post): https://axialcorps.com/2013/07/03/atomically-replacing-files-and-directories/

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #18124.

### CODE REVIEW

**Comment by shlevy** [comment]
@domenkozar please test

**Comment by edolstra** [comment]
Sorry, didn't see "please test" before hitting merge...

**Comment by domenkozar** [comment]
I'm still getting:

 `dummy> mv: cannot move '/var/setuid-wrappers' to '/var/setuid-wrappers-old': Device or resource busy`.

**Comment by shlevy** [comment]
Hmm, even with /var/setuid-wrappers-old not existing already?

**Comment by shlevy** [comment]
(this may mean that this change has to be activated with nixos-rebuild boot)

**Comment by domenkozar** [comment]
Without:

```
[root@dummy:~]# ls /var/setuid*
setuid-wrappers.2DF8dF0aTv  setuid-wrappers.Pt01NyPpjG  setuid-wrappers.vaeo8U1fcw
```

**Comment by shlevy** [comment]
What the hell, where did those temp names come from?

**Comment by domenkozar** [comment]
I activated new configuration three times, this is what was left behind from the error probably.

**Pull request merged**
