### PR TITLE
mpv: build with ffmpeg-full

### PR DESCRIPTION
**Pull request by K900**
This enables support for smb (and possibly other protocols) that mpv advertises native support for, which kio takes it up on.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jopejoe1** [comment]
We are at the moment trying to remove the dependens of ffmpeg-full, the features that mpv needs should be added to the regular ffmpeg variant. Unless there is a compeling reason that feature should not be in the regular version.

For more info please see #271863

cc @Atemu

**Comment by K900** [comment]
The primary feature that's missing is Samba support. I'm not sure if enabling it in ffmpeg(-not-full) will work because Samba is GPLv3 poison.

**Comment by jopejoe1** [comment]
Currently all ffmpeg variants that we have are build with GPLv3 enabled.

**Comment by K900** [comment]
Should I change this to enabling Samba on ffmpeg-not-full then?

**Comment by jopejoe1** [comment]
Should check by how much the closure size increases by enabling samba and if that is not to large, enable it for the small variant of ffmpeg

**Comment by K900** [comment]
```
❯ nix store diff-closures ./before ./after                                                           ffmpeg: +9.8 KiB
jansson: ∅ → 2.14, +112.7 KiB
ldb: ∅ → 2.8.0, +852.1 KiB
libarchive: ∅ → 3.7.2, +883.6 KiB
libbsd-unstable: ∅ → 2023-04-29, +100.0 KiB
libmd: ∅ → 1.1.0, +125.7 KiB
liburing: ∅ → 2.5, +154.8 KiB
libxcrypt: +230.2 KiB
popt: ∅ → 1.19, +186.9 KiB
python3: +118413.4 KiB
python3.11-dnspython: ∅ → 2.4.2, +3581.2 KiB
python3.11-markdown: ∅ → 3.5.1, +1065.0 KiB
samba: ∅ → 4.19.4, +77907.0 KiB
talloc: ∅ → 2.4.2, +325.4 KiB
tdb: ∅ → 1.4.10, +276.9 KiB
tevent: ∅ → 0.16.0, +243.6 KiB
```

oof

**Comment by Atemu** [comment]
Python3 isn't too bad because that'll be in the closure of most users anyways.

I don't know about samba though. Would it be in a typical desktop closure? (i.e. GNOME ISO). If so, that'd probably be fine.

**Comment by Atemu** [comment]
As for this PR's goal: MPV has a wrapper anyways right? Would it not be possible to build in a mechanism to supply your desired ffmpeg there? If someone needed smb support in MPV for some odd reason, they'd be able to just select ffmpeg-full themselves.

**Comment by K900** [comment]
For Plasma, yes. For GNOME, can't really say.

**Comment by K900** [comment]
> As for this PR's goal: MPV has a wrapper anyways right? Would it not be possible to build in a mechanism to supply your desired ffmpeg there? If someone needed smb support in MPV for some odd reason, they'd be able to just select ffmpeg-full themselves.

No, it uses ffmpeg as a library. We could have an mpvFull though.

**Comment by Atemu** [comment]
As a user of MPV myself, I really wouldn't want mpv to depend on ffmpeg-full by default.

As a maintainer of ffmpeg, I'm wary of closure size increases for niche features. I checked [Arch's ffmpeg](https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/blob/main/PKGBUILD?ref_type=heads) and it also doesn't include samba support. Given its niche, I don't think it's reasonable to have in the small variant.

I'd rather see this solution or adding smb support in default ffmpeg as last resorts if other (more appropriate) solutions aren't workable:

1. Would it be possible to achieve this using overrides instead?
2. It's a little hacky but the wrapper could also (ab)use LD_LIBRARY_PATH to inject a custom version of ffmpeg into MPV.
3. mpvFull sounds like an okay compromise but I'd rather have 1. or 2.

**Comment by K900** [comment]
That way, kio will run the file through a FUSE filesystem instead of passing a direct smb:// URL to mpv, which will be slower, but hopefully not by much?

**Pull request closed without merging**
