### PR TITLE
gdb: 10.2 -> 11.1

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

See https://sourceware.org/pipermail/gdb/2021-September/049719.html for
release information.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 137628` at d0af9fbc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>38 packages marked as broken and skipped:</summary>
  <ul>
    <li>adoptopenjdk-hotspot-bin-13</li>
    <li>adoptopenjdk-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-hotspot-bin-13</li>
    <li>adoptopenjdk-jre-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-openj9-bin-13</li>
    <li>adoptopenjdk-jre-openj9-bin-14</li>
    <li>adoptopenjdk-openj9-bin-13</li>
    <li>adoptopenjdk-openj9-bin-14</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>electron_3</li>
    <li>electron_4</li>
    <li>electron_5</li>
    <li>epsxe</li>
    <li>googleearth-pro</li>
    <li>hadoop</li>
    <li>hadoop_2_7</li>
    <li>hadoop_2_8</li>
    <li>hadoop_2_9</li>
    <li>impressive</li>
    <li>invoice2data</li>
    <li>jboss</li>
    <li>keyfinder</li>
    <li>linuxKernel.packages.hardkernel_4_14.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>obinskit</li>
    <li>odpdown</li>
    <li>opentsdb</li>
    <li>pcsxr</li>
    <li>pdfdiff</li>
    <li>pig</li>
    <li>spark</li>
    <li>termplay</li>
    <li>twinkle</li>
    <li>unicap</li>
    <li>unifi-video</li>
    <li>vdrPlugins.xineliboutput</li>
    <li>xpdf</li>
  </ul>
</details>
<details>
  <summary>4780 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>DisnixWebService</li>
    <li>Literate</li>
    <li>MIDIVisualizer</li>
    <li>OSCAR</li>
    <li>R</li>
    <li>Sylk</li>
    <li>_1password-gui</li>
    <li>abcl</li>
    <li>abiword</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>29 packages built successfully:</summary>
  <ul>
    <li>adoptopenjdk-bin (adoptopenjdk-hotspot-bin-11 ,openjdk11-bootstrap)</li>
    <li>openjdk16-bootstrap (adoptopenjdk-hotspot-bin-15)</li>
    <li>openjdk8-bootstrap (adoptopenjdk-hotspot-bin-8)</li>
    <li>gdb</li>
    <li>gtk3 (gnome.gtk ,gtk3-x11)</li>
    <li>libsoup (gnome.libsoup)</li>
    <li>tracker (gnome.tracker)</li>
    <li>gssdp</li>
    <li>gupnp</li>
    <li>gupnp-igd</li>
    <li>libnice</li>
    <li>libpsl</li>
    <li>openconnect (openconnect_gnutls)</li>
    <li>php80Extensions.calendar</li>
    <li>php80Extensions.exif</li>
    <li>php80Extensions.ftp</li>
    <li>php80Extensions.gd</li>
    <li>php80Extensions.gettext</li>
    <li>php80Extensions.ldap</li>
    <li>php80Extensions.pcntl</li>
    <li>php80Extensions.pdo</li>
    <li>php80Extensions.pdo_odbc</li>
    <li>php80Extensions.pdo_sqlite</li>
    <li>php80Extensions.readline</li>
    <li>php80Extensions.session</li>
    <li>php80Extensions.tokenizer</li>
    <li>php80Extensions.xmlwriter</li>
    <li>stoken</li>
    <li>valgrind</li>
  </ul>
</details>

**Comment by risicle** [comment]
@ofborg build python3.tests.cpython-gdb

**Comment by risicle** [comment]
Builds & runs on macos 10.15

**Comment by NickHu** [comment]
Confirmed working on x86_64-linux

Also fixes https://github.com/rust-lang/rust/issues/85267

**Pull request merged**
