### PR TITLE
zed-editor: 0.146.5 -> 0.147.2

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/zed-industries/zed/releases/tag/v0.147.2

cc @jansol @niklaskorz 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 333027` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 333027` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 333027` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 333027` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
```
error[E0277]: the trait bound `str: std::default::Default` is not satisfied
  --> crates/gpui/src/shared_string.rs:14:28
   |
14 |         Self(ArcCow::Owned(Arc::default()))
   |                            ^^^ the trait `std::default::Default` is not implemented for `str`, which is required by `std::sync::Arc<_, _>: std::default::Default`
   |
   = help: the following other types implement trait `std::default::Default`:
             &mut str
             &str
   = note: required for `std::sync::Arc<str>` to implement `std::default::Default`
```

**Comment by niklaskorz** [comment]
> ```
> error[E0277]: the trait bound `str: std::default::Default` is not satisfied
>   --> crates/gpui/src/shared_string.rs:14:28
>    |
> 14 |         Self(ArcCow::Owned(Arc::default()))
>    |                            ^^^ the trait `std::default::Default` is not implemented for `str`, which is required by `std::sync::Arc<_, _>: std::default::Default`
>    |
>    = help: the following other types implement trait `std::default::Default`:
>              &mut str
>              &str
>    = note: required for `std::sync::Arc<str>` to implement `std::default::Default`
> ```

That means the minimum Rust version for Zed is now 1.80, which luckily was already merged to staging-next

**Comment by GaetanLepage** [comment]
> That means the minimum Rust version for Zed is now 1.80, which luckily was already merged to staging-next

Makes sense, thanks !
Sometimes the error message is clearer though.

**Comment by linuxmobile** [comment]
waiting this <3

**Comment by domenkozar** [comment]
It makes sense to make a PR against staging-next :)

**Comment by GaetanLepage** [comment]
> It makes sense to make a PR against staging-next :)

Done :)

**Comment by GaetanLepage** [comment]
It builds fine on both `x86_64-linux` and `aarch64-linux`.

**Pull request merged**
