### PR TITLE
sequoia: unbreak on darwin

### PR DESCRIPTION
**Pull request by puzzlewolf**
###### Motivation for this change
This is an attempt to unbreak `sequoia` on darwin. I don't own a Mac, so I'm trying to get ofBorg to do the work :)

`sequoia` has been marked broken on Darwin since #73104 (version 0.11.0). I'd like to check if the build still fails and try to fix it, if it does.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by puzzlewolf** [comment]
Hmm, there is no build attempt for darwin. Is there a way to make this work, or am I trying something I shouldn't?

**Comment by puzzlewolf** [comment]
Remove "[WIP]" from title to make ofBorg build the package, from the readme:

> If the title of a PR begins with WIP:, contains [WIP] anywhere, or has the 2.status: work-in-progress label, its packages are not built automatically. Note: Marking a PR as a draft does not prevent automatic builds.

I guess I'm not allowed to, but let's try:
@ofBorg build sequoia

**Comment by puzzlewolf** [comment]
@doronbehar I see you are a trusted user for ofBorg. Could you please trigger a build on darwin?

**Comment by doronbehar** [comment]
> @doronbehar I see you are a trusted user for ofBorg. Could you please trigger a build on darwin?

I appreciate your enthusiasm regarding this package and your motivation to make it build on Darwin, but TBH I don't see much point in this effort, as long as you are not a Darwin user yourself. Let somebody else put on the effort. For completeness, I'd keep this PR open as a draft and perhaps open /or search if an issue's already open for Sequoia's Darwin support so it will be a bit noticable if someone will seek that in the future.

To answer your question, the answer is NO. Building this package is already expensive and I'm not willing to make ofborg test it while it's not tested at all on a human's machine.

**Comment by puzzlewolf** [comment]
Hm, ok. That makes sense. Thanks for explaining :)

**Comment by puzzlewolf** [comment]
Closing, since #101753 sequoia is no longer marked as broken :)

**Pull request closed without merging**
