### PR TITLE
lemmy: make update.sh more robust

### LINKED ISSUE #237717: Lemmy 0.17.4 is out and update.sh is malfunctioning
### Describe the bug

Lemmy update.sh produces:

```
❯  cat pin.json
{
  "version": "0.17.4",
  "serverSha256": "sha256-lF5/Y8VAM0NGJDKcfvKQWRg4zQ2gCvNhVQLNmuUjdg8=",
  "serverCargoSha256": "      . 205052 exec nix-build -A lemmy-server",
  "uiSha256": "sha256-g72EQOYHtBZ3vCu8aSmoPILuOJ8yiC4W7nDOtmFqK0o=",
  "uiYarnDepsSha256": "      . 205057 exec nix-build -A lemmy-ui"
}
```
Please see the entries: serverCargoSha256 and uiYarnDepsSha256

### Steps To Reproduce
1. cd to .../nixpkgs/pkgs/servers/web-apps/lemmy
2. run ./update.sh and it does succeed (exits with 0)

### Expected behavior
To fill pin.json with hash values.

### Notify maintainers

@happysalada @billewanick 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.11 (Tapir), 23.11.20230609.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/matejc/workarea/nixpkgs`
```

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

fixes #237717
@matejc can you test when you have a moment ?
in order to test, you can just switch the lemmy version manually to 0.17.3 and run the script.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
@adisbladis you mentioned the update script was broken, did you run into another issue ?

**Comment by matejc** [comment]
The fix is just changing the need in which dir people run the script from.

May I suggest to run this:
```
nix-build -A lemmy-server -A lemmy-ui --dry-run
```
at the beginning of the script and if by any reason it fails have a nice error message for the user, something in the lines of:
```
Error: Please check from which directory you ran the script from, it needs to be run from ./nixpkgs/blabla/ directory. 
```

**Comment by matejc** [comment]
@happysalada and like @adisbladis mentioned somewhere, I also had a different hash values than the accepted PR for Lemmy 0.17.4 that is now merged in master.

**Comment by happysalada** [comment]
@matejc you were right about fetch modules. It's weird, this must be a recent change, I've used this update script several times.

I would rather keep the ability to run the script from anywhere if you don't mind.

Let me know if there is anything else.

**Comment by matejc** [comment]
@happysalada it works perfectly, lets get it merged!
previously I misunderstood `$directory` variable, so there is no need to use `nix-build ... --dry-run`

**Comment by billewanick** [comment]
Wanted to note that I also tested the updated update script and it works great. From any directory.
Thanks for this @happysalada !!

**Comment by happysalada** [comment]
Thank you !

**Pull request merged**
