### PR TITLE
Update metadata to reflect uncompyle6 and xdis relicensing to GPL (v3 and v2 respectively)

### PR DESCRIPTION
**Pull request by charles-dyfis-net**
###### Motivation for this change

Significant bugfixes to uncompyle6 between 2.8 and 3.2; able to correctly handle a wider range of bytecode.

xdis and spark_parser are part of the dependency chain; analysis via nox appears to indicate that they aren't used elsewhere.

Note that upstream moved to GPLv3 for uncompyle6 and GPLv2 for xdis within this span of releases.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]
Rebase onto staging-next because there are changes in these expressions there.

**Comment by charles-dyfis-net** [comment]
@FRidh, done -- we now only update the license metadata (since the versions were updated without those fixes in the interim), and are based on staging-next. Is a separate PR for master needed?

**Comment by charles-dyfis-net** [comment]
I'm a bit surprised re: the rebuild-stdenv flag -- this is literally nothing but a metadata change. Perhaps the rebase onto staging-next is at fault?

**Comment by samueldr** [comment]
@GrahamcOfBorg eval

Could it be that you pushed and *then* changed the target branch? In any case, let's re-eval with ofborg, more of a curiosity than a necessity.

**Pull request merged**
