### PR TITLE
opencl-clhpp: 2.0.15 -> 2024.05.08

### LINKED ISSUE #276448: Update request: opencl-clhpp 2.0.15 → 2023.12.14
Auto-updates for this package seem to fail due to changes to opencl-headers that introduce cmake https://r.ryantm.com/log/opencl-clhpp/2023-12-17.log. Seems to me like https://github.com/NixOS/nixpkgs/pull/254870 should fix this issue and no manual intervention will be needed, but I'm not entirely sure. At the moment this package is very outdated and misses bugfixes https://github.com/KhronosGroup/OpenCL-CLHPP/pull/175 without which software using this library fails to build with certain compiler flags. I'm not sure who to tag here since the package has no maintainers. @lelgenio, this issue seems relevant.

- Package name: opencl-clhpp
- Latest released version: 2023.12.14

- Current version on the unstable channel: 2.0.15
- Current version on the stable/release channel: 2.0.15

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@FRidh @lelgenio

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by xokdvium**
## Description of changes

Rebased https://github.com/NixOS/nixpkgs/pull/277072 and applied a patch to arrayfire, which fails to build with new opencl-clhpp.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by xokdvium** [comment]
@ofborg build arrayfire

**Review by chessai — APPROVED** [review]

**Comment by xokdvium** [comment]
I guess arrayfire isn't built due to freeimage being marked insecure, so ofborg won't build it.

**Comment by xokdvium** [comment]
Result of `nixpkgs-review pr 335392` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>arrayfire</li>
    <li>forge</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>clfft</li>
    <li>clpeak</li>
    <li>mandelbulber</li>
    <li>opencl-clhpp</li>
    <li>sanjuuni</li>
    <li>virtualgl</li>
    <li>virtualglLib</li>
  </ul>
</details>

**Comment by smancill** [comment]
Result of `nixpkgs-review pr 335392` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>opencl-clhpp</li>
  </ul>
</details>

**Comment by smancill** [comment]
Closes #276448

**Comment by smancill** [comment]
This should be ok to merge, right? LGTM, but I was waiting for another opinion.

**Comment by xokdvium** [comment]
I don't see why not. Arrayfire is already insecure, but it does build with the patch applied. Fixing it should be easier in the future.

**Pull request merged**
