### PR TITLE
inetutils: set priority lower than util-linux

### PR DESCRIPTION
**Pull request by bryango**
**Warning:** although seemingly innocuous (trivial `nixpkgs-review`), this might be a breaking change for some people, but should reduce the confusion for most others.

The `inetutils` package provides the `telnet` command, along with some lesser known binaries such as `logger`.

However, `util-linux` also provides `logger` with a `meta.priority = 6`, while inetutils has a default priority of 5 (so inetutils wins; note that smaller `meta.priority` wins). If inetutils is installed, the `logger` binary from `inetutils` would shadow the one from `util-linux`, which is unexpected for most users.

In this PR, we demote inetutils such that the `logger` binary from `util-linux` (instead of `inetutils`) is now preferred. This has been the default for many linux distributions, including in:

- Arch: `logger` from inetutils is simply disabled:
	- https://gitlab.archlinux.org/archlinux/packaging/packages/inetutils/-/blob/24578966983e0ec3e62eb6574594b440c3180893/PKGBUILD#L71
- Debian:
	- `logger` from inetutils is not installed by default: https://packages.debian.org/en/bookworm/inetutils-tools
	- ... while the `logger` from util-linux is essential: https://packages.debian.org/en/bookworm/util-linux

If anyone would like to keep the old behavior, i.e. prioritize `inetutils`, they can simply set a _lower_ `meta.priority` for `inetutils`, or use e.g. `lib.setPrio 5 inetutils`. This is documented with doc comments around this change. Note that the default `meta.priority` is defined in [`buildEnv`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/buildenv/default.nix) and is currently 5.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by bjornfor — APPROVED** [review]

**Comment by h7x4** [comment]
Would it make sense to add a note about this in the release notes?

**Review by h7x4 — APPROVED** [review]

**Comment by h7x4** [comment]
@ofborg eval

**Comment by bryango** [comment]
It seems that `ofborg-eval-lib-tests` is [failing](https://gist.github.com/GrahamcOfBorg/bc5d07772fef68f2b4ad44bf6d26d723) for unrelated reasons:
```console
       … while evaluating the attribute 'args' of the derivation 'bootstrap-stage0-glibc-bootstrapFiles'

       at /ofborg/checkout/2/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/ofborg-evaluator-2/pkgs/stdenv/generic/make-derivation.nix:352:7:

          351|     // (optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          352|       name =
             |       ^
          353|         let

       error: opening lock file '/nix/var/nix/temproots/2782631': No space left on device
```
I will try to ping ofborg again later.

**Comment by h7x4** [comment]
Seems like the new ofborg run went fine

**Pull request merged**
