### PR TITLE
pkgs.boogie: 2.4.1 -> 2.15.7

### PR DESCRIPTION
**Pull request by jwiegley**
###### Description of changes

Builds newer than 2.4.1 require `buildDotnetModule` instead of `buildDotnetPackage`.

This update is needed since Boogie 2.4.1 really only supports Z3 4.8.4, due to changes in the optimization flags, so in order to use a more modern Z3, we have to move Boogie forward.

See ChangeLog here: https://github.com/boogie-org/boogie/releases

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by layus** [comment]
I introduced Boogie for Dafny. Currently trying to update it to see if this new version is usable. I cannot really test Boogie without that.

**Review by layus — CHANGES_REQUESTED** [review]
This definitely breaks Dafny, and I have spent too much time trying to fix it. Please mark Dafny as broken and let's call it a day.

**Comment by jwiegley** [comment]
@layus How about we keep Boogie 2.4.1 under the attribute `Boogie_2_4` and have dafny depend on that, while users who install `pkgs.boogie` will get 2.15? I really don't want to break dafny.

**Review by layus — APPROVED** [review]
Thank you for the changes.

It's a bit sad that we have to keep an old Boogie for an old Dafny, 
But Dafny build system uses custom msbuild commands to call gradle (no less!) somewhere.

**Comment by layus** [comment]
I wonder who uses Boogie. There is not usage in nixpkgs.

**Pull request merged**
