### PR TITLE
Set dontCheck on haskellPackages.monomer

### PR DESCRIPTION
**Pull request by chreekat**
Note: monomer is currently marked as transitively unbuildable, but NixOS/cabal2nix#516 will fix that. Once it does, this patch will make monomer buildable, itself. 

###### Motivation for this change

monomer's test suite requires a DISPLAY, like a number of other packages that currently can't be tested in the Nix sandbox.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
A couple of things:

* Can you rebase on `haskell-updates` and retarget your PR (best using `git rebase -i $(git merge-base origin/master origin/haskell-updates)` whilst deleting all unrelated commits)? I've just now updated `cabal2nix-unstable` on there and regenerated the package set, so your changes should be applied.
* Make sure that your commit messages match the [Contributing guideline](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

**Comment by chreekat** [comment]
Actually, I'll go ahead and unmark packages as broken so we can see if all my changes actually work. One sec

**Comment by chreekat** [comment]
Ok, hopefully that all works

**Comment by sternenseemann** [comment]
Cherry picked as a198f752583 and 568e022497d. Will land with #135453.

**Pull request closed without merging**
