### PR TITLE
Linux kernel updates 2023-08-30

### PR DESCRIPTION
**Pull request by Ma27**
## Description of changes

Update all to the latest version available.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by K900 — APPROVED** [review]
Diff LGTM, weird how there's no 6.5.1, didn't run-test.

**Comment by Ma27** [comment]
> didn't run-test.

for the record, currently on it, until then this is a draft :)

**Comment by fabianhjr** [comment]
Seems like 6.5.1 hasn't been fully published yet @K900

image

**Comment by fabianhjr** [comment]
Seems like 6.5.1 is scheduled for Saturday Sept 02, 2023

https://lore.kernel.org/stable/20230831110830.817738361@linuxfoundation.org/T/#t

**Review by fabianhjr — APPROVED** [review]
Diff LGTM, evals

**Comment by Ma27** [comment]
Removed the bump of linux-rt to 5.10.192, this fails the same way as 5.10.192 used to: https://github.com/NixOS/nixpkgs/pull/251929#issuecomment-1699817670

5.10.193 seems to have fixed this, at least I can't reproduce this anymore. For linux-rt we should just wait until 5.10.193 or later is available with rt patches.

**Pull request merged**
