### PR TITLE
nixos/navidrome: fix settings type

### LINKED ISSUE #312749: nixos/navidrome: error: attribute 'Port' missing
### Describe the bug
Evaluation failure when setting `services.navidrome.settings.*` and `services.navidrome.openfirewall = true`.
Moreover setting any `services.navidrome.settings.*` will "remove" the default values for `services.navidrome.settings.Address` and `services.navidrome.settings.Port`

### Steps To Reproduce
1. Build your system with these options:
```nix
  services.navidrome = {
    enable = true;
    openFirewall = true;
    settings = {
      BaseUrl = "/navidrome";
    };
  };
```

2. Observe the failure:
```
       error: attribute 'Port' missing

       at /nix/store/0aavdx9m5ms1cj5pb1dx0brbrbigy8ij-source/nixos/modules/services/audio/navidrome.nix:135:69:

          134|
          135|       networking.firewall.allowedTCPPorts = mkIf cfg.openFirewall [ cfg.settings.Port ];
             |                                                                     ^
          136|     };
```

### Expected behavior
System builds, firewall is opened for the default 4533 port.

### Additional context
This bug happens because the [default value is defined for settings as a whole](https://github.com/nixos/nixpkgs/blob/4a6b83b05df1a8bd7d99095ec4b4d271f2956b64/nixos/modules/services/audio/navidrome.nix#L24-L27) rather than for each individual setting.

### Notify maintainers
@nu-nu-ko 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05.20240517.4a6b83b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.11.1115.5de0b32be6e8"`
 - nixpkgs: `/nix/store/0aavdx9m5ms1cj5pb1dx0brbrbigy8ij-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

Fixes #312749. This fixes merging user-set values with default values.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by fsnkty — APPROVED** [review]
seems a better fix than what I had suggested I was going to do.
thank you! :heart:
(assuming you've tested this of course) sorry I'm unable to atm.

**Comment by eclairevoyant** [comment]
I tested this on a config which has the following:

```nix
  services.navidrome = {
    enable = true;
    openFirewall = true;

    settings = {
      Address = "0.0.0.0";
      MusicFolder = "/run/navidrome/media/music";
    };
  };
```

and verified that the correct port is in fact preserved, while the user-set settings are merged in:

```
$ nix eval .#nixosConfigurations.$(hostname).config.services.navidrome.settings
{ Address = "0.0.0.0"; MusicFolder = "/run/navidrome/media/music"; Port = 4533; }
```

**Review by gepbird — APPROVED** [review]
Thank you both for your quick response, ideas and work! I have also tested it and the code LGTM.

A tiny nit: 18e089be7feb381d5fb7defb1648706d64c5c7c4 contains a formatting change that should be in a74fd69291a5c3b82a363ff5a1625ba6b0ff9935.

**Comment by mweinelt** [comment]
This breaks the nixos test, because settings is now required but unset by default.

**Pull request merged**
