### PR TITLE
spdx-license-list-data: 3.15 -> 3.16

### PR DESCRIPTION
**Pull request by oxzi**
###### Motivation for this change
Version bump.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxzi** [comment]
Result of `nixpkgs-review pr 159182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>esphome</li>
    <li>platformio</li>
    <li>spdx-license-list-data</li>
  </ul>
</details>

**Comment by c0bw3b** [comment]
It's unrelated to the version bump but shouldn't this also install `exceptions.json`?
After all it's part of the SPDX definitions.

**Comment by oxzi** [comment]
> It's unrelated to the version bump but shouldn't this also install `exceptions.json`? After all it's part of the SPDX definitions.

Honestly, I simply don't know. I guess it's for historical reasons, as it was always™ this way (c5d06b022b22d0e542ce2ffd0fe092317758fb03).

This package also exists in [other repositories](https://repology.org/project/spdx-license-list-data/versions) with other contents.
For example, [Alpine](https://git.alpinelinux.org/aports/tree/community/spdx-licenses/APKBUILD) creates a package for each file format. [Void Linux](https://github.com/void-linux/void-packages/blob/master/srcpkgs/spdx-licenses-list/template) creates packages for _some_ file formats. [Debian](https://github.com/Debian/spdx-licenses), however, only ships the txt file versions.

Thus, I pushed another commit to this PR to include _all_ formats without breaking compatibility. @c0bw3b, would you please take another look?

**Comment by oxzi** [comment]
Result of `nixpkgs-review pr 159182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>esphome</li>
    <li>platformio</li>
    <li>spdx-license-list-data</li>
  </ul>
</details>

**Comment by c0bw3b** [comment]
Yes shipping all formats in one package would be _really_ complete but it gets quite big!
`nix path-info` tells me ~177MB.
We probably don't want to pull that on every `platformio` install.

Nix has a really elegant solution for this : multi-outputs derivations.
With one output for each format, `platformio` would only need to have `spdx-license-list-data.json` in its build inputs and ignore the rest.

I'm trying to write such a derivation on my end, but it's not working yet.

**Comment by oxzi** [comment]
Closed in favor of #161958.

**Pull request closed without merging**
