### PR TITLE
gnome-icon-theme: fix cross

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

This package is just an icon set, so all the dependencies are going to be build deps.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Lets do this to ensure there's no deps

```diff
diff --git a/pkgs/data/icons/gnome-icon-theme/default.nix b/pkgs/data/icons/gnome-icon-theme/default.nix
index 239cf052ca9..664b0a0c512 100644
--- a/pkgs/data/icons/gnome-icon-theme/default.nix
+++ b/pkgs/data/icons/gnome-icon-theme/default.nix
@@ -23,6 +23,9 @@ stdenv.mkDerivation rec {
     rm -r "$out/share/locale"
   '';
 
+  # just a icon theme so the output shouldn't depend on anything
+  allowedReferences = [ ];
+
   meta = with lib; {
     description = "Collection of icons for the GNOME 2 desktop";
     homepage = "https://download.gnome.org/sources/gnome-icon-theme/";
```

**Comment by romildo** [comment]
> This package is just an icon set, so all the dependencies are going to be build deps.

> Lets do this to ensure there's no deps

The Icon Standard says that themes may inherit from other themes as a way to extend them. When parent themes are not installed, the look may not be as expected, and some (inherited) icons may be missed. It is natural that an icon package depends on its parent icon packages. This is assured in many icon packages in nixpkgs.

**Comment by alyssais** [comment]
Thanks for the info.

> It is natural that an icon theme package depends on its parent icon theme packages.

Correct be if I'm wrong, but this particular icon theme doesn't have a parent, does it?  What we're doing here is saying that this icon theme has no dependencies, not that no other icon themes are allowed to depend on this one.

**Comment by romildo** [comment]
> Correct me if I'm wrong, but this particular icon theme doesn't have a parent, does it? What we're doing here is saying that this icon theme has no dependencies, not that no other icon themes are allowed to depend on this one.

I just wanted to say that rhe absence of dependences is not because it is an icon theme. The way it has been said in the comments may wrongly suggest that this is the reason.

**Comment by alyssais** [comment]
> I just wanted to say that rhe absence of dependences is not because it is an icon theme. The way it has been said in the comments may wrongly suggest that this is the reason.

Ah, I understand now. Thanks. I've removed the comment.

**Review by romildo — APPROVED** [review]

**Pull request merged**
