### PR TITLE
ghcjsHEAD: don’t just copy & replace, reuse same code

### PR DESCRIPTION
**Pull request by Profpatsch**
The HEAD file was just copied over and a few hashes replaced.
Most of these hashes were already function arguments anyway, so no reason to not
abstract over that.

`ghcjsHEAD` builds, it needs a rebuild because the `ghcjs-prim` build input is set to `null` instead of missing (my guess).

cc @TravisWhitaker @ryantrinkle

### CODE REVIEW

**Comment by Profpatsch** [comment]
Update: The stage1Packages had to be changed as well, added a commit for that.

**Comment by TravisWhitaker** [comment]
This is way better! Thanks! I tend to have the affordance to treat nix files like config files and forget that things like this are possible...

Perhaps the shims should be an argument as well?

**Comment by Profpatsch** [comment]
> Perhaps the shims should be an argument as well?

They are! https://github.com/NixOS/nixpkgs/pull/20493/files#diff-f13bf85e6c9e824c1ccdfb265469c2c5R59

You can basically think of nix as a very powerful DSL, with better abstraction possibilities than most general purpose langs.

**Comment by Profpatsch** [comment]
I will merge it now, since it shouldn’t change anything. Should something break feel free to do a rollback.

**Pull request merged**
