### PR TITLE
python3Packages.elgato: init at 2.1.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Python client for Elgato Key Lights

https://github.com/frenck/python-elgato

This is a Home Assistant dependency.

- Target Home Assistant release: current

ToDo:

- [ ] Update `component-packages` 
- [ ] Enable tests in Home Assistant

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126047` at 7360c3ed run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.elgato</li>
    <li>python39Packages.elgato</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Please update this PR.

**Comment by frenck** [comment]
As the author of this package, I would request not to repack my code in this case.

Thank you for hindering the authors wishes.

**Comment by lukegb** [comment]
Locked for now. Please see https://github.com/NixOS/nixpkgs/issues/126677#issuecomment-860071285.

**Comment by frenck** [comment]
As the author of the upstream package, I do not agree with this package being added.

While licensing wise I cannot stop you at this point, I think the way it is used and packaged in this project harms the user experience and thus the upstream project.

Thank you for considering.

**Comment by jagajaga** [comment]
@frenck I don't want to sound rude, but sorry, then you need to change your license. Is this truly an open source or a proprietary software indeed? There is nothing bad in adding this package to nix collection. On the contrary, it only gives it popularization, and most importantly, helps other people. People who use this package in Nix/NixOS would not disturb you in any manner related to the packaging in our system.

**Review by jagajaga — APPROVED** [review]

**Comment by lukegb** [comment]
> @frenck I don't want to sound rude, but sorry, then you need to change your license. Is this truly an open source or a proprietary software indeed? There is nothing bad in adding this package to nix collection. On the contrary, it only gives it popularization, and most importantly, helps other people. People who use this package in Nix/NixOS would not disturb you in any manner related to the packaging in our system.

We've had discussions about this - in a few other issues, for other HA dependencies authored by frenck; authors of software are free to express their wishes above and beyond what the license they've chosen actually requires, and as part of the OSS ecosystem it's our responsibility to listen to and consider those requests. We should remain respectful of these requests and the human beings behind them, even if we ultimately choose not to abide by them.

For better or for worse, in NixOS "we've" decided to continue to try to package this software: in NixOS, we provide a different user experience for HA than upstream provides as a result of our declarative-configuration philosophy, and as a result as responsible members of the OSS ecosystem we need to do our part in trying to reduce the support load on upstream - we expect that users of NixOS who use the HA packaging we provide will be aware of these implications (because, well, they're users of NixOS: they're probably used to things being a little different), and that there are clear escape hatches if they choose to run HA in an upstream-supportable way (using `virtualisation.oci-containers` to run the provided Docker container, for instance, or manually packing a venv in a way that `pip` will work).

The HA ecosystem is large, and the team can't possibly understand and make everything work every weird configuration that users throw at them, so I harbour no ill will towards them for wanting to reduce the scope of configurations that they're willing to support, and am extremely grateful for all the work they, and other OSS maintainers, put into providing this software for everyone to use for free.

**Comment by SuperSandro2000** [comment]
> As the author of the upstream package, I do not agree with this package being added.
> 
> While licensing wise I cannot stop you at this point, I think the way it is used and packaged in this project harms the user experience and thus the upstream project.
> 
> Thank you for considering.

We know this. Please stop posting this under new packages or updates here. Thank you.

**Comment by frenck** [comment]
> Please stop posting this under new packages or updates here. Thank you.

Thanks, I'm aware you know this, someone looking into the history might not.
Therefore I think it is important I distance myself from it.

Thanks 👍 

../Frenck

**Pull request merged**
