### PR TITLE
haskell/with-packages-wrapper.nix: install "doc" outputs

### LINKED ISSUE #76837: NIX_GHC_DOCDIR not set properly
**Describe the bug**
When creating a Haskell development environment like this:
```
# shell.nix
{ pkgs ? import <nixpkgs> { } }:

let
  all-hies = import (fetchTarball "https://github.com/infinisil/all-hies/tarball/master") {};
  hie = all-hies.selection { selector = p: { inherit (p) ghc865; }; };

in
  pkgs.haskellPackages.shellFor {
    buildInputs = with pkgs; [
      hie
      cabal-install
    ];

    packages = (hp: with hp; [ gloss ]);
    withHoogle = true;
  }
```

with `withHoogle = true`, the doc is generated in `${ghcEnv}/share/doc/hoogle/html`, however the `NIX_GHC_DOCDIR` is set to `${ghcEnv}/share/doc/ghc/html`.
The former does not even exist (no such file or directory error on `ls $NIX_GHC_DOCDIR`).

See this line:

https://github.com/NixOS/nixpkgs/blob/ff882242ea70502696b551c7c9bfb933a250c60f/pkgs/development/haskell-modules/make-package-set.nix#L322

Note that I have seen https://github.com/NixOS/nixpkgs/issues/20730 and think that it is a different issue.

This issue prevents from using HIE in a nix-shell. See https://discourse.nixos.org/t/cant-make-hie-work-on-vs-code-with-nix/5277/

**To Reproduce**
Use previous `shell.nix`
```
nix-shell --run "ls $NIX_GHC_DOCDIR"
nix-shell --run "whateverfolderghcisin/share/doc/hoogle"
```

**Expected behavior**
`nix-shell --run "ls $NIX_GHC_DOCDIR"` should point to `${ghcEnv}/share/doc/hoogle/html`

**Metadata**
```
% nix run nixpkgs.nix-info -c nix-info -m                                                                                                                                                                                                  ~
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.91, NixOS, 19.09.1686.69ed29f5f41 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(arsleust): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by matthewbauer**
We were previously just installing the "out" output which broke when
we recently changed to generating multiple outputs.

Fixes #76837

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by cdepillabout** [comment]
@matthewbauer Could you show me how to test that this actually fixes the problem with hoogle?

My idea was to run a command like the following on the current `master`:

```console
$ nix-build -E 'with import ./. {}; haskellPackages.ghcWithPackages (p: [p.conduit])'
/nix/store/48grjcgskic4iij38sgdfx4f4q7r0hlr-ghc-8.6.5-with-packages
```

This works, as expected.  In the `/nix/store/48grjcgskic4iij38sgdfx4f4q7r0hlr-ghc-8.6.5-with-packages` directory, there is no `share/doc` directory (as expected?).

I then checked out this PR and tried to run the same command, but I got an error:

```console
$ hub checkout https://github.com/NixOS/nixpkgs/pull/76842
$ nix-build -E 'with import ./. {}; haskellPackages.ghcWithPackages (p: [p.conduit])'
these derivations will be built:
  /nix/store/chk26hff7nhhzjyjj5fk80xm3rw3v597-ghc-8.6.3-with-packages.drv
building '/nix/store/chk26hff7nhhzjyjj5fk80xm3rw3v597-ghc-8.6.3-with-packages.drv'...
created 131 symlinks in user environment
rm: cannot remove '/nix/store/0s4vjgsz437aqmpyxxr5zqdcdcdih57j-ghc-8.6.3-with-packages/bin/ghc': Permission denied
builder for '/nix/store/chk26hff7nhhzjyjj5fk80xm3rw3v597-ghc-8.6.3-with-packages.drv' failed with exit code 1
error: build of '/nix/store/chk26hff7nhhzjyjj5fk80xm3rw3v597-ghc-8.6.3-with-packages.drv' failed
```

I don't understand two things:

1. Why is this trying to use ghc-8.6.3 (and not the latest version of ghc, 8.6.5)?  Is this PR branched off of an old version of nixpkgs?  Could you rebase it on top of the current master?
2. It is probably bad that this is failing, right?

**Comment by matthewbauer** [comment]
> 1. Why is this trying to use ghc-8.6.3 (and not the latest version of ghc, 8.6.5)?  Is this PR branched off of an old version of nixpkgs?  Could you rebase it on top of the current master?

Yeah this was based off of `git merge-base origin/release-19.03 origin/release-19.09` so that it can be merged into master, release-19.09 and release-19.03. It definitely can be rebased, but ideally this fix would be merged into all three branches.

> 2. It is probably bad that this is failing, right?

Yeah this is definitely an oversight. It looks like it is a result in moving from symlinkJoin to buildEnv.

**Comment by cdepillabout** [comment]
@matthewbauer 

> Yeah this was based off of git merge-base origin/release-19.03 origin/release-19.09 so that it can be merged into master, release-19.09 and release-19.03.

Oh, I see.  That's really smart! I'm happy with this as-is, then.  No need to rebase.

> It looks like it is a result in moving from symlinkJoin to buildEnv.

I've tested your fix in 93aabab and this appears to be working for me.

```console
$ nix-build -E 'with import ./. {}; haskellPackages.ghcWithPackages (p: with p; [aeson conduit lens servant-server])'
...
/nix/store/c36g05zmrflibzy5w6wji2zc0nmry3sf-ghc-8.6.3-with-packages
$ ls /nix/store/c36g05zmrflibzy5w6wji2zc0nmry3sf-ghc-8.6.3-with-packages/share/doc/
adjunctions-4.4
aeson-1.4.2.0
ansi-terminal-0.8.2
...
```

**Review by cdepillabout — APPROVED** [review]

**Comment by matthewbauer** [comment]
Also it's usually worth trying the GitHub merge commit to test PRs. I think nix-review does this for you, but you can also use something like & test merge_commit_sha directly:

```
nix-build -E "(import (builtins.fetchTarball \"https://github.com/NixOS/nixpkgs/archive/$(curl https://api.github.com/repos/NixOS/nixpkgs/pulls/76842 | jq -r .merge_commit_sha).tar.gz\") {}).haskellPackages.ghcWithPackages (p: [p.conduit])"
```

**Pull request merged**
