### PR TITLE
python3Packages.yarl: 1.0.0 -> 1.1.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by rasendubi — APPROVED** [review]
Looks good. Would you like to become the maintainer of the package?

**Comment by dotlambda** [comment]
I could do that, even though I have never used the package. I just need the newer version for #33675.

**Comment by adisbladis** [comment]
@GrahamcOfBorg eval

**Comment by adisbladis** [comment]
@dotlambda I fixed your eval issue (`maintainers` was not scoped). Thanks!

**Pull request merged**
