### PR TITLE
roon-server: 1.8-850 -> 1.8-880

### LINKED ISSUE #152104: roon-server: 1.8-850 -> 1.8-880
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: roon-server

current version: 1.8-850
desired version: 1.8-880

###### Notify maintainers

maintainers: @reanimus @lovesegfault @Steell @volth

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change

Closes: #152104

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
@anttisoikkeli This PR needs to be tested, I'm currently away from home and cannot test this in my Roon server.

**Comment by Steell** [comment]
Tested and confirmed operating as expected on my NixOS machine.

**Comment by anttisoikkeli** [comment]
@Steell did you actually test to connect to it? Mine is running as well, but my Roon Remote fails to connect to it.

Tested on Android (Note 10 Plus) and iPad (2019 model) and both have latest version of Roon Remote. Android gives Connecting/Connection failed -loop and iPad can't even find it. Systemctl tells me that it's running on 1.8-880. Nothing has changed in the system lately.

I'm 98% certain that this relates to the new version of roon-server somehow. I'm guessing that adding libtasn1 isn't enough after all and some missing library is now failing silently or then the new version needs some new open ports.

Ping @lovesegfault as well.

Sorry for reacting this late, but I haven't been able to play with this before now.

**Comment by lovesegfault** [comment]
It's going to take me a hot minute to be able to test or debug this.

My Roon server is in storage and I'm in another continent for another few weeks, and then I need to find a house before I can reassemble everything.

My recommendation is that we either revert this for now or that someone debug the issue without my help.

**Comment by anttisoikkeli** [comment]
I can try to debug this as well. Personally at least, I'm not in a hurry.

Note that reverting is not really an option. New versions of Roon Remotes (that get updated automatically in mobile devices) are not backwards compatible with the old roon-server and those can't be downgraded. We would have a broken system anyway, even if we reverted all the changes. That's why I created the issue in the first place.

I would say that let's just accept that it's broken and debug/fix this when we have time. Reverting creates just extra work without any benefits.

**Comment by anttisoikkeli** [comment]
It's firewall! `sudo systemctl stop firewall` and Roon Remote can connect.

**Comment by lovesegfault** [comment]
> It's firewall! `sudo systemctl stop firewall` and Roon Remote can connect.

Ah, interesting :)

Can you try stealing my firewall rules and seeing if it fixes it?

https://github.com/lovesegfault/nix-config/blob/09602aa096cac83ab92aa770889c925bd44836be/hosts/bohr/default.nix#L63

**Comment by anttisoikkeli** [comment]
Those are already identical to: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/audio/roon-server.nix

There is something else. I also tried to allow all TCP and UDP ports with this and no success:
```nix
    networking.firewall.allowedTCPPortRanges = [ { from = 0; to = 65353; } ];
    networking.firewall.allowedUDPPortRanges = [ { from = 0; to = 65353; } ];
```

**Comment by anttisoikkeli** [comment]
Found it, this fixes the problem:
```
sudo iptables -I INPUT 1 -p tcp --dport 9330:9339 -j ACCEPT
```
Source: https://community.roonlabs.com/t/connection-failed-and-chromecast-issues-roon-using-new-additional-network-ports-since-880/181528

Now I just need to find out why the lines from my previous comment didn't fix anything, but that's not related to this ticket :)

**Pull request merged**
