### PR TITLE
cargo,clippy,rustc,rustfmt: 1.77.2 -> 1.78.0 

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

I guess we want to hold this until breaking changes are allowed again, since we have packages using nightly features that have been renamed.

Built:

- [x] fd on aarch64-linux
- [x] fd on x86_64-linux
- [x] fd on x86_64-darwin
- [x] firefox on aarch64-linux
- [x] firefox on x86_64-linux
- [x] firefox-esr on aarch64-linux
- [x] firefox-esr on x86_64-linux
- [x] thunderbird on aarch64-linux
- [x] thunderbird on x86_64-linux
- [x] betterbird on aarch64-linux
- [x] librewolf on aarch64-linux
- [x] floorp on aarch64-linux
- [x] nixosTests.kernel-rust on aarch64-linux
- [x] nixosTests.kernel-rust on x86_64-linux

I haven't fixed thunderbirdPackages.thunderbird-102, but it's been marked insecure since September, and I think we should just remove it: #308820.

**Could somebody please check fd on x86_64-darwin?**

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by zowoq** [comment]
> Could somebody please check fd on x86_64-darwin?

Built.

**Comment by centromere** [comment]
Is this ready to go?

**Comment by alyssais** [comment]
Yes from my PoV, but since we're between staging cycles anyway, I was holding off on merging in case anybody wanted to review.

**Comment by vcunat** [comment]
I'm not 100% sure how git auto-resolved `pkgs/top-level/linux-kernels.nix` and perhaps some other changes in there, but given that's a basically leaf-package issue, I didn't wait/try.

**Comment by alyssais** [comment]
*sigh* the update seems to have broken cross compilation of Rust programs.  Bisecting…

**Comment by vcunat** [comment]
- [ ] `rustc` won't build on aarch64-darwin now:
  ```
  cargo:warning=error: unknown target CPU 'apple-a13'
  cargo:warning=note: valid target CPU values are: mvp, bleeding-edge, generic
  ```
  [on Hydra](https://hydra.nixos.org/build/261783693) and I can reproduce the same locally.

**Comment by alyssais** [comment]
Fix for cross compilation: https://github.com/NixOS/nixpkgs/pull/317179

**Comment by alyssais** [comment]
Potential fix for aarch64-darwin: https://github.com/NixOS/nixpkgs/pull/317273

**Pull request merged**
