### PR TITLE
[WIP] neovim: 0.2.1 -> 0.2.2

### PR DESCRIPTION
**Pull request by ghost**
##### TODO

* nixos/tests, see https://github.com/NixOS/nixpkgs/pull/32509/files#diff-60a46e09bd8194cb429be3b0c6f0b4d0R129

* `:CheckHealth` from neovim, ruby error:
```
  - INFO: Ruby: ruby 2.4.0p0 (2016-12-24) [x86_64-linux]
  - INFO: Host: /nix/store/12l4jz2i1qw3hipzs6f016a1d0apm7fv-neovim-0.2.2/bin/nvim-ruby
  - ERROR: Command error (job=12): /nix/store/12l4jz2i1qw3hipzs6f016a1d0apm7fv-neovim-0.2.2/bin/nvim-ruby --version
    Output: /nix/store/6z17cwrivy793q28q7sc0c4rh4349d0k-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find msgpack-1.1.0 in any of the sources (Bundler::GemNotFound)	from /nix/store/6z17cwrivy793q28q7sc0c4rh4349d0k-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'	from /nix/store/6z17cwrivy793q28q7sc0c4rh4349d0k-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'	from /nix/store/6z17cwrivy793q28q7sc0c4rh4349d0k-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'	from /nix/store/6z17cwrivy793q28q7sc0c4rh4349d0k-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'	from /nix/store/6z17cwrivy793q28q7sc0c4rh4349d0k-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'	from /nix/store/6z17cwrivy793q28q7sc0c4rh4349d0k-bundler-1.14.6/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:102:in `setup'	from /nix/store/12l4jz2i1qw3hipzs6f016a1d0apm7fv-neovim-0.2.2/bin/nvim-ruby:16:in `<main>'
  - ERROR: Failed to run: /nix/store/12l4jz2i1qw3hipzs6f016a1d0apm7fv-neovim-0.2.2/bin/nvim-ruby --version
    - ADVICE:
      - Report this issue with the output of: 
      - /nix/store/12l4jz2i1qw3hipzs6f016a1d0apm7fv-neovim-0.2.2/bin/nvim-ruby --version
```

###### Motivation for this change

Especially important, because v0.2.1 contains broken netrw parts, which is fixed in v0.2.2 (https://github.com/neovim/neovim/pull/7557). 

And of course the new version contains in general bug fixes and new features (-> [Release Notes](https://github.com/neovim/neovim/commit/6d2c30daf3b29b84b15b547ef956e165f5e9685d))

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
I am preparing a neovim wrapper (to prevent useless rebuilds) and while doing so I noticed the withPython3 instead of withRuby here: 
https://github.com/toogley/nixpkgs/blob/f7f940cf7156994d30bdb97582dd48bd1a9dffc8/pkgs/applications/editors/neovim/default.nix#L146
Could you fix it too as well please ?

**Comment by teto** [comment]
Is it still WIP ? I've kinda finished my wrapper so I wonder if I should wait for your PR first.

**Comment by toogley** [comment]
@teto Yep, its still WIP and i'm not sure when i have time to work on that again.

**Comment by mnacamura** [comment]
I succeeded in building on macOS and passing `:CheckHealth` by adding the following changes to this PR:
```diff
diff --git a/pkgs/applications/editors/neovim/ruby_provider/Gemfile.lock b/pkgs/applications/editors/neovim/ruby_provider/Gemfile.lock
index 61df9ed7932..07426ace850 100644
--- a/pkgs/applications/editors/neovim/ruby_provider/Gemfile.lock
+++ b/pkgs/applications/editors/neovim/ruby_provider/Gemfile.lock
@@ -1,9 +1,9 @@
 GEM
   remote: https://rubygems.org/
   specs:
-    msgpack (1.1.0)
+    msgpack (1.2.0)
     multi_json (1.12.2)
-    neovim (0.6.1)
+    neovim (0.6.2)
       msgpack (~> 1.0)
       multi_json (~> 1.0)
```

**Comment by teto** [comment]
Could you rebase please ? you might need to edit pkgs/applications/editors/neovim/wrapper.nix

**Comment by jlesquembre** [comment]
I think we can close this PR since #34113 is already merged

**Pull request closed without merging**
