### PR TITLE
electron: 1.7.5 -> 1.8.1

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

 - [x] version bump
 - [x] added "i686-linux" "armv7l-linux" "aarch64-linux" (binaries compiled by upstream)

### CODE REVIEW

**Comment by orivej** [comment]
This may be causing blank white screen in `rambox` with this error in the console:
```
[5268:1216/203518.057807:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1. 
```
https://github.com/NixOS/nixpkgs/pull/32741#issuecomment-352203170

**Comment by yegortimoshenko** [comment]
v1.8.1 is pre-release version (beta), the latest stable version is v1.7.9: https://github.com/electron/electron/releases/tag/v1.8.1

**Comment by Mic92** [comment]
@yegortimoshenko I guess you can do a new pull request in that case to downgrade to `1.7.9`.

**Comment by volth** [comment]
It might worth trying 1.8.2, perhaps that bug is fixed.

1.7.9 does not have arm64 version, so the downgrating would result either in abandoning ```aarch64-linux``` support or in maintaining both 1.7.x and 1.8.x version (and explicitly passing ```electron_1_7``` to the ```rambox``` derivation)

**Comment by Mic92** [comment]
That would be also a solution.

**Comment by gnidorah** [comment]
Or maybe just that? https://github.com/NixOS/nixpkgs/pull/32765

**Comment by yegortimoshenko** [comment]
This problem is unlikely to be specific to Rambox.

**Comment by gnidorah** [comment]
@yegortimoshenko We need complains of users of other Electron programs :D
Then for a while 1.8.1 will move to `electron_1_8`, and 1.7.x will go back to `electron`

**Pull request merged**
