### PR TITLE
glib: 2.78.1 -> 2.78.3

### PR DESCRIPTION
**Pull request by trofi**
Changes:
- https://gitlab.gnome.org/GNOME/glib/-/releases/2.78.3
- https://gitlab.gnome.org/GNOME/glib/-/releases/2.78.2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by amaxine** [comment]
Tests fail locally for me
```
115/341 glib:glib+core+no-valgrind+pkg-config / glib-2.0-pkg-config                     FAIL             0.10s   exit status 1
>>> MALLOC_CHECK_=2 G_ENABLE_DIAGNOSTIC=1 G_DEBUG=gc-friendly PKG_CONFIG_PATH=/build/glib-2.78.3/build/meson-private MALLOC_PERTURB_=29 /nix/store/q1c2flcykgr4wwg5a6h450hxbk4ch589-bash-5.2-p15/bin/bash -xe -c 'pkg-config --validate glib-2.0
test "$(pkg-config --modversion glib-2.0)" = "2.78.3"
test "$(pkg-config --variable=prefix glib-2.0)" = "/nix/store/kc7kcg1kflyj5pb3mvmhwh4jklp6ri9b-glib-2.78.3"
test "$(pkg-config --variable=datadir glib-2.0)" = "/nix/store/kc7kcg1kflyj5pb3mvmhwh4jklp6ri9b-glib-2.78.3/share"
test "$(pkg-config --variable=gobject_query glib-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/gobject-query"
test "$(pkg-config --variable=glib_mkenums glib-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/glib-mkenums"
test "$(pkg-config --variable=glib_valgrind_suppressions glib-2.0)" = "/nix/store/kc7kcg1kflyj5pb3mvmhwh4jklp6ri9b-glib-2.78.3/share/glib-2.0/valgrind/glib.supp"'

285/341 glib:gio+no-valgrind+pkg-config / gio-2.0-pkg-config                            FAIL             0.10s   exit status 1
>>> MALLOC_CHECK_=2 MALLOC_PERTURB_=91 G_ENABLE_DIAGNOSTIC=1 G_DEBUG=gc-friendly PKG_CONFIG_PATH=/build/glib-2.78.3/build/meson-private /nix/store/q1c2flcykgr4wwg5a6h450hxbk4ch589-bash-5.2-p15/bin/bash -xe -c 'pkg-config --validate gio-2.0
test "$(pkg-config --modversion gio-2.0)" = "2.78.3"
test "$(pkg-config --variable=prefix gio-2.0)" = "/nix/store/kc7kcg1kflyj5pb3mvmhwh4jklp6ri9b-glib-2.78.3"
test "$(pkg-config --variable=datadir gio-2.0)" = "/nix/store/kc7kcg1kflyj5pb3mvmhwh4jklp6ri9b-glib-2.78.3/share"
test "$(pkg-config --variable=schemasdir gio-2.0)" = "/nix/store/kc7kcg1kflyj5pb3mvmhwh4jklp6ri9b-glib-2.78.3/share/glib-2.0/schemas"
test "$(pkg-config --variable=giomoduledir gio-2.0)" = "/nix/store/kc7kcg1kflyj5pb3mvmhwh4jklp6ri9b-glib-2.78.3/lib/gio/modules"
test "$(pkg-config --variable=gio gio-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/gio"
test "$(pkg-config --variable=glib_compile_resources gio-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/glib-compile-resources"
test "$(pkg-config --variable=gdbus gio-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/gdbus"
test "$(pkg-config --variable=gdbus_codegen gio-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/gdbus-codegen"
test "$(pkg-config --variable=gresource gio-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/gresource"
test "$(pkg-config --variable=gsettings gio-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/gsettings"
test "$(pkg-config --variable=gio_querymodules gio-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/gio-querymodules"
test "$(pkg-config --variable=glib_compile_schemas gio-2.0)" = "/nix/store/sbi7w21zdzsmb0hsd09fdl2lfimv1y8v-glib-2.78.3-bin/bin/glib-compile-schemas"'
```

**Comment by trofi** [comment]
Builds fine here on `x86_64-linux`:

```
$ nix build github:NixOS/nixpkgs/pull/273187/head#glib; realpath result*
/nix/store/hc11bdg8q1vcixdjkd7a6841sqg1s05n-glib-2.78.3-bin

$ nix build github:NixOS/nixpkgs/pull/273187/merge#glib; realpath result*
/nix/store/8fc7nidf5jaz8dsnays13fsvz7zsixgl-glib-2.78.3-bin
```

Might be a non-determinism of tests. I'll try a few rebuilds locally to trigger the failure. I wonder if `2.78.1` fails for you on some reruns.

**Comment by jtojnar** [comment]
It is `glib.tests` that fails.

**Comment by trofi** [comment]
Oh, thank you! `glib.tests.withChecks` fails for me as well. Switching to draft for now.

**Comment by jtojnar** [comment]
Looks like it is not a regression.

**Comment by jtojnar** [comment]
Fixed in #273161

**Pull request closed without merging**
