### PR TITLE
firefox-unwrapped: Apply patch for mozbz#1803016

### LINKED ISSUE #226539: Firefox 112.0+ crashes on Wayland with scaling
### Describe the bug
Recurring but sudden crashes.

### Steps To Reproduce
Using it over multiple hours / days (without reboot) on unstable

### Expected behavior
No crashes or within reproducible actions 

### Screenshots
---

### Additional context
https://crash-stats.mozilla.org/report/index/d38cdbf0-bd3a-450f-9840-522800230416
https://crash-stats.mozilla.org/report/index/404af7aa-94ac-449d-8ec8-adff10230416
https://crash-stats.mozilla.org/report/index/be5b9392-9784-425f-886e-b8c730230414
https://crash-stats.mozilla.org/report/index/817396ba-c909-4873-b746-632d30230414

(four examples in the past three days)

### Notify maintainers

@lovesegfault
@hexa

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.11, NixOS, 23.05 (Stoat), 23.05.20230416.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/gs6fkh869l6nj9dws2dd8w217iq60337-source`
```

### PR DESCRIPTION
**Pull request by mweinelt**
Resolves crashes on wayland, when the either component of the window size wouldn't be divisible by the desktop scaling.

Unfortunately marked wontfix for Firefox 112, so we apply this patch instead.

https://bugzilla.mozilla.org/show_bug.cgi?id=1803016

Closes: #226539 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I find it slightly confusing that you drop a different patch in the same commit without mentioning anything.

**Comment by mweinelt** [comment]
I can split this up. The reason I dropped it is that it doesn't get applied to any version we have at this point.

**Comment by vcunat** [comment]
I saw the reason, after thinking and looking for a while.  Perhaps it's enough to just mention it in the commit message.

**Comment by mweinelt** [comment]
Split in two commits and scoped to the affected package attribute.

**Comment by Kiskae** [comment]
Does it make sense to also backport https://hg.mozilla.org/integration/autoland/rev/ddba22b4de24 to cover other crashes caused by the wayland client log handler?

Like this patch it also is fixed in firefox 113

**Comment by vcunat** [comment]
Either way, I see no reason to wait with this one.

**Comment by vcunat** [comment]
So far it looks uncertain whether Mozilla will backport this one to 112 themselves.

**Comment by vcunat** [comment]
Perhaps it will get to 112:
https://bugzilla.mozilla.org/show_bug.cgi?id=1826583#c38

**Comment by vcunat** [comment]
Included in the next patch (112.0.2).

**Pull request merged**
