### PR TITLE
deeptools,tebreak,python3Packages.cnvkit,python3Packages.HTSeq: Fix test

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change

#100814

```
writing manifest file 'deepTools.egg-info/SOURCES.txt'
running build_ext
Matplotlib created a temporary config/cache directory at /build/matplotlib-qzbkbnui because the default path (/homeless-shelter/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Finished executing setuptoolsCheckPhase
pytestcachePhase
copying 1 paths...
copying path '/nix/store/n60jc9dap8acc3f28j154779am5rpsnd-deepTools-3.5.0'
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>deeptools</li>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
    <li>tebreak</li>
  </ul>
</details>

**Comment by Mic92** [comment]
The PR is merged now.

**Comment by unode** [comment]
@SuperSandro2000 instead of disabling tests altogether, can we disable only the failing ones?

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 instead of disabling tests altogether, can we disable only the failing ones?

If I did no mistake they all have zero tests indicated by ``Ran 0 tests in 0.000s``.

**Comment by FRidh** [comment]
> If I did no mistake they all have zero tests indicated by Ran 0 tests in 0.000s.

That depends on how the tests should be run. `buildPythonPackage` has a default runner, but the default is often not sufficient. Check the source / sdist for tests.

**Comment by SuperSandro2000** [comment]
> That depends on how the tests should be run. `buildPythonPackage` has a default runner, but the default is often not sufficient. Check the source / sdist for tests.

The pypi tar balls often don't contain tests. I switch to the GitHub ones.

We should really pay more attention to this in the future when updating/adding packages.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>deeptools</li>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
    <li>tebreak</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>deeptools</li>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
    <li>tebreak</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>kmymoney</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>deeptools</li>
    <li>gnucash</li>
    <li>lasso</li>
    <li>matrix-synapse</li>
    <li>python37Packages.pysaml2</li>
    <li>python38Packages.pysaml2</li>
    <li>tebreak</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>kmymoney</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>aqbanking</li>
    <li>deeptools</li>
    <li>gnucash</li>
    <li>lasso</li>
    <li>matrix-synapse</li>
    <li>python37Packages.pysaml2</li>
    <li>python38Packages.pysaml2</li>
    <li>tebreak</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>kmymoney</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python38Packages.HTSeq</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>aqbanking</li>
    <li>deeptools</li>
    <li>gnucash</li>
    <li>lasso</li>
    <li>matrix-synapse</li>
    <li>python37Packages.pysaml2</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.pysaml2</li>
    <li>tebreak</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python37Packages.pysaml2</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>oathToolkit</li>
    <li>pass-otp</li>
    <li>passExtensions.pass-otp</li>
    <li>python38Packages.pysaml2</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>deeptools</li>
    <li>krunner-pass</li>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
    <li>tebreak</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python37Packages.pysaml2</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>oathToolkit</li>
    <li>passExtensions.pass-otp</li>
    <li>python38Packages.pysaml2</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>kmymoney</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>deeptools</li>
    <li>gnucash</li>
    <li>lasso</li>
    <li>matrix-synapse</li>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python37Packages.pysaml2</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.pysaml2</li>
    <li>tebreak</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>deeptools</li>
    <li>krunner-pass</li>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
    <li>tebreak</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python37Packages.pysaml2</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>oathToolkit</li>
    <li>passExtensions.pass-otp</li>
    <li>python38Packages.pysaml2</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>oathToolkit</li>
    <li>pass-otp</li>
    <li>passExtensions.pass-otp</li>
    <li>python37Packages.pysaml2</li>
    <li>python38Packages.pysaml2</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>kmymoney</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>aqbanking</li>
    <li>deeptools</li>
    <li>gnucash</li>
    <li>lasso</li>
    <li>matrix-synapse</li>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python37Packages.pysaml2</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.pysaml2</li>
    <li>tebreak</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by unode** [comment]
1 package failed to build:
* kmymoney
```
builder for '/nix/store/3dmc2ghin4lciidqpx1835j8s0b549as-kdiagram-2.6.0.drv' failed with exit code 2; last 10 log lines:
                   from /nix/store/gnbsmzcp9n66vssz1sfv2yw26fd9xkb5-qtbase-5.15.0-dev/include/QtWidgets/qabstractscrollarea.h:44,
                   from /nix/store/gnbsmzcp9n66vssz1sfv2yw26fd9xkb5-qtbase-5.15.0-dev/include/QtWidgets/qabstractitemview.h:44,
                   from /nix/store/gnbsmzcp9n66vssz1sfv2yw26fd9xkb5-qtbase-5.15.0-dev/include/QtWidgets/QAbstractItemView:1,
                   from /build/kdiagram-2.6.0/src/KGantt/kganttlegend.h:23,
                   from /build/kdiagram-2.6.0/src/KGantt/kganttlegend.cpp:20:
  /nix/store/gnbsmzcp9n66vssz1sfv2yw26fd9xkb5-qtbase-5.15.0-dev/include/QtGui/qfontmetrics.h:106:9: note: declared here
    106 |     int width(const QString &, int len = -1) const;
        |         ^~~~~
  make[1]: *** [CMakeFiles/Makefile2:1943: src/KGantt/CMakeFiles/KGantt.dir/all] Error 2
  make: *** [Makefile:149: all] Error 2
builder for '/nix/store/845mhhmpx3nljs0q8hqh29v0ywvng8sv-qtwebkit-5.212.0-alpha4.drv' failed with exit code 2; last 10 log lines:
  [ 67%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/UserAgentStyleSheetsData.cpp.o
  [ 67%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/PlugInsResourcesData.cpp.o
  [ 67%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/CSSGrammar.cpp.o
  /build/source/build/DerivedSources/WebCore/CSSGrammar.cpp:160:10: fatal error: CSSGrammar.hpp: No such file or directory
    160 | #include "CSSGrammar.hpp"
        |          ^~~~~~~~~~~~~~~~
  compilation terminated.
  make[2]: *** [Source/WebCore/CMakeFiles/WebCore.dir/build.make:28188: Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/CSSGrammar.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:1629: Source/WebCore/CMakeFiles/WebCore.dir/all] Error 2
  make: *** [Makefile:182: all] Error 2
```

13 packages built:
* deeptools
* gnucash
* lasso
* matrix-synapse
* python27Packages.HTSeq
* python37Packages.HTSeq
* python37Packages.cnvkit
* python37Packages.pysaml2
* python38Packages.HTSeq
* python38Packages.cnvkit
* python38Packages.pysaml2
* tebreak
* xmlsec

The build failure seems unrelated to this pull request so LGTM on `x86_64-linux`

**Comment by unode** [comment]
Result of `nixpkgs-review pr 102140` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- kmymoney
</details>
<details>
  <summary>13 packages built:</summary>
<br>- deeptools
<br>- gnucash
<br>- lasso
<br>- matrix-synapse
<br>- python27Packages.HTSeq
<br>- python37Packages.HTSeq
<br>- python37Packages.cnvkit
<br>- python37Packages.pysaml2
<br>- python38Packages.HTSeq
<br>- python38Packages.cnvkit
<br>- python38Packages.pysaml2
<br>- tebreak
<br>- xmlsec
</details>

**Review by jonringer — APPROVED** [review]
diff LGTM

```
https://github.com/NixOS/nixpkgs/pull/102140
1 package marked as broken and skipped:
kmymoney

13 packages built:
deeptools gnucash lasso matrix-synapse python27Packages.HTSeq python37Packages.HTSeq python37Packages.cnvkit python37Packages.pysaml2 python38Packages.HTSeq python38Packages.cnvkit python38Packages.pysaml2 tebreak xmlsec
```

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>aqbanking</li>
    <li>deeptools</li>
    <li>gnucash</li>
    <li>kmymoney</li>
    <li>lasso</li>
    <li>matrix-synapse</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python37Packages.pysaml2</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.pysaml2</li>
    <li>tebreak</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102140` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>deeptools</li>
    <li>krunner-pass</li>
    <li>python27Packages.HTSeq</li>
    <li>python37Packages.HTSeq</li>
    <li>python37Packages.cnvkit</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.cnvkit</li>
    <li>tebreak</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>oathToolkit</li>
    <li>passExtensions.pass-otp</li>
    <li>python37Packages.pysaml2</li>
    <li>python38Packages.pysaml2</li>
    <li>xmlsec</li>
  </ul>
</details>

**Pull request merged**
