### PR TITLE
mercurial: 3.4.2 -> 3.5.1

### PR DESCRIPTION
**Pull request by k0ral**
Successfully built locally.

Cc maintainer: @edolstra

### CODE REVIEW

**Comment by garbas** [comment]
also 3.5.1 is out. @johbo could you help with this?

**Comment by k0ral** [comment]
Updated to 3.5.1 .

**Comment by johbo** [comment]
Sorry, got a bit busy in the last days, cool that we have a recent mercurial now :-)

**Comment by garbas** [comment]
@johbo np, i just thought you would be interested into mercurial stuff and to have as much as possible upstream. could you check if mercurial stuff is ok in both branches "master" and "release-15.09"?

**Pull request closed without merging**
