### PR TITLE
folly: 2023.02.27.00 -> 2024.01.22.00, bump rest of ecosystem to 2024.01.22.00

### PR DESCRIPTION
**Pull request by risicle**
## Description of changes

A replacement for #282958 that won't get overwritten every week.

`passthru.tests` WFM on macos 12 x86_64 & nixos x86_64. Some more packages could do with having their tests enabled but this has cascaded out of control enough.

Hope all the `apple_sdk_11_0` switching doesn't cause problems, but it seems necessary for all folly-based libs.

cc @wegank 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
Result of `nixpkgs-review` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>buck</li>
    <li>python311Packages.pywatchman</li>
    <li>python311Packages.pywatchman.dist</li>
    <li>python312Packages.pywatchman</li>
    <li>python312Packages.pywatchman.dist</li>
    <li>rs-git-fsmonitor</li>
    <li>watchman</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>edencommon</li>
    <li>fb303</li>
    <li>fbthrift</li>
    <li>fizz</li>
    <li>folly</li>
    <li>folly.dev</li>
    <li>mvfst</li>
    <li>wangle</li>
  </ul>
</details>

**Comment by wegank** [comment]
@ofborg build watchman

**Comment by risicle** [comment]
Oh I thought I did - wonder where that commit went...

**Comment by risicle** [comment]
Yup, pushed it to the wrong branch :facepalm:. Fixed now.

**Comment by wegank** [comment]
Result of `nixpkgs-review` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>buck</li>
    <li>edencommon</li>
    <li>fb303</li>
    <li>fbthrift</li>
    <li>fizz</li>
    <li>folly</li>
    <li>folly.dev</li>
    <li>mvfst</li>
    <li>python311Packages.pywatchman</li>
    <li>python311Packages.pywatchman.dist</li>
    <li>python312Packages.pywatchman</li>
    <li>python312Packages.pywatchman.dist</li>
    <li>rs-git-fsmonitor</li>
    <li>wangle</li>
    <li>watchman</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Comment by risicle** [comment]
Oh I probably need to make `mvfst` a by-name package (:roll_eyes:) before I merge or I will get nagged to death.

**Comment by risicle** [comment]
@infinisil so what am I supposed to do if my new by-name package just needs a custom `callPackage` (in this case `darwin.apple_sdk_11_0`) - the CI test doesn't seem to account for that.

**Comment by infinisil** [comment]
See https://github.com/NixOS/nixpkgs/blob/4ec0020e841be6f186b712fd90e4cad5c40712e1/pkgs/by-name/README.md#limitations

CI won't complain about new packages in the category hierarchy if it doesn't use `callPackage`.

But if you can make it work with the standard `pkgs.callPackage` and move it to `pkgs/by-name`, that would be great :)

**Comment by risicle** [comment]
Ah that explains why it wasn't complaining before...

**Pull request merged**
