### PR TITLE
python3Packages.dulwich: 0.20.32 -> 0.20.35, python3Packages.scmrepo: 0.0.8 -> 0.0.13

### PR DESCRIPTION
**Pull request by fabaff**
###### Description of changes
Update to latest upstream releases

Related #157998

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Does this really need to be for staging?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 165821` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.optuna</li>
  </ul>
</details>
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>dvc</li>
    <li>dvc-with-remotes</li>
    <li>hydra-unstable</li>
    <li>python310Packages.osc-lib</li>
    <li>python310Packages.python-heatclient</li>
    <li>python310Packages.python-ironicclient</li>
    <li>python310Packages.python-manilaclient</li>
    <li>python310Packages.python-openstackclient</li>
    <li>python39Packages.oslo-concurrency</li>
    <li>python39Packages.subunit2sql</li>
    <li>python39Packages.tempest</li>
  </ul>
</details>
<details>
  <summary>68 packages built:</summary>
  <ul>
    <li>breezy (python39Packages.breezy)</li>
    <li>cabal2nix</li>
    <li>dep2nix</li>
    <li>devpi-client</li>
    <li>errbot</li>
    <li>flatpak-builder</li>
    <li>klaus (python39Packages.klaus)</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>openstackclient (python39Packages.python-openstackclient)</li>
    <li>python310Packages.breezy</li>
    <li>python310Packages.check-manifest</li>
    <li>python310Packages.cliff</li>
    <li>python310Packages.dulwich</li>
    <li>python310Packages.hacking</li>
    <li>python310Packages.hg-git</li>
    <li>python310Packages.keystoneauth1</li>
    <li>python310Packages.klaus</li>
    <li>python310Packages.openstackdocstheme</li>
    <li>python310Packages.openstacksdk</li>
    <li>python310Packages.oslo-concurrency</li>
    <li>python310Packages.oslo-config</li>
    <li>python310Packages.oslo-context</li>
    <li>python310Packages.oslo-db</li>
    <li>python310Packages.oslo-i18n</li>
    <li>python310Packages.oslo-log</li>
    <li>python310Packages.oslo-serialization</li>
    <li>python310Packages.oslo-utils</li>
    <li>python310Packages.python-cinderclient</li>
    <li>python310Packages.python-glanceclient</li>
    <li>python310Packages.python-keystoneclient</li>
    <li>python310Packages.python-novaclient</li>
    <li>python310Packages.python-swiftclient</li>
    <li>python310Packages.scmrepo</li>
    <li>python310Packages.stestr</li>
    <li>python310Packages.subunit2sql</li>
    <li>python310Packages.tempest</li>
    <li>python39Packages.check-manifest</li>
    <li>python39Packages.cliff</li>
    <li>python39Packages.dulwich</li>
    <li>python39Packages.hacking</li>
    <li>python39Packages.hg-git</li>
    <li>python39Packages.keystoneauth1</li>
    <li>python39Packages.openstackdocstheme</li>
    <li>python39Packages.openstacksdk</li>
    <li>python39Packages.osc-lib</li>
    <li>python39Packages.oslo-config</li>
    <li>python39Packages.oslo-context</li>
    <li>python39Packages.oslo-db</li>
    <li>python39Packages.oslo-i18n</li>
    <li>python39Packages.oslo-log</li>
    <li>python39Packages.oslo-serialization</li>
    <li>python39Packages.oslo-utils</li>
    <li>python39Packages.python-cinderclient</li>
    <li>python39Packages.python-glanceclient</li>
    <li>python39Packages.python-heatclient</li>
    <li>python39Packages.python-ironicclient</li>
    <li>python39Packages.python-keystoneclient</li>
    <li>python39Packages.python-manilaclient</li>
    <li>python39Packages.python-novaclient</li>
    <li>swiftclient (python39Packages.python-swiftclient)</li>
    <li>python39Packages.scmrepo</li>
    <li>python39Packages.stestr</li>
    <li>rabbitvcs</li>
    <li>reno</li>
    <li>vcstool</li>
    <li>xandikos</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> Does this really need to be for staging?

No, it can go to `master`. `gpgme` for Python 3.10 is available.

**Review by risicle — APPROVED** [review]
`nixpkgs-review` reveals no new failures, macos 10.15 & nixos x86_64

**Pull request merged**
