### PR TITLE
helio-workstation: 2.2 -> 3.1

### PR DESCRIPTION
**Pull request by suhr**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by magnetophon** [comment]
It builds and runs, but everywhere I'd expect text, there is empty space.
Therefore I haven't been able to find the preferences menu, and have not been able to configure it to use jack.

Does it work for you, @suhr?

**Comment by magnetophon** [comment]
After `rm -r .config/Helio`, I can see text, and configure it to use jack.
A jack port shows up, but I haven't been able to produce sound yet.
Probably PEBCAC though.

**Comment by suhr** [comment]
Make sure you run qjackctl before running Helio. Also, if you tried to use Helio without working jack, you will have to reset Helio configuration again.

**Comment by magnetophon** [comment]
Thanks.  I had jack running already.

I have sound now, the missing step seemed to be to scan my plugins folder and assign an instrument to the track.
I had previously assigned the built-in piano, but that didn't work.

In any case the package seems to be working just fine, thanks!

**Review by magnetophon — APPROVED** [review]

**Pull request merged**
