### PR TITLE
python3Packages.rokuecp: init at 0.8.1

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

Needs a maintainer. cc @Church-

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM except that maintainer

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 120284` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.rokuecp</li>
    <li>python39Packages.rokuecp</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package built (see https://github.com/NixOS/nixpkgs/pull/120284#issuecomment-825457777)
- [x] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-120284/results/python38Packages.rokuecp/lib/python3.8/site-packages]$ python
Python 3.8.8 (default, Feb 19 2021, 11:04:50) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from rokuecp import Roku
>>> async def main():
...     async with Roku("192.168.1.100") as roku:
...             print(roku)
... 
>>> loop = asyncio.get_event_loop()
>>> loop.run_until_complete(main())
<rokuecp.rokuecp.Roku object at 0x7f7c3534f610>
[...]                       
```

Change looks good to me. Issue was already mentioned (maintainer).

**Comment by mweinelt** [comment]
The fun fact will be, that ultimately the home-assistant maintainers will keep this up to date with home-assistant requirements, given that we don't like test failures much.

**Comment by SuperSandro2000** [comment]
I forgot to add a maintainer...

**Comment by mweinelt** [comment]
@Church- It would be great if you could step up and maintain this package, given that I am not a roku user and therefore cannot test it.

**Pull request merged**
