### PR TITLE
boogie: 2.15.7 -> 3.0.4, move out of `dotnet-packages.nix`

### PR DESCRIPTION
**Pull request by mdarocha**
## Description of changes

Update boogie to the newest version.
Also moved it out of `dotnet-packages.nix` into the `by-name` folder - this helps with https://github.com/NixOS/nixpkgs/issues/234775.
Alias was added for backwards compatibility.

An install test was added to verify boogie can find the z3 binary it depends on.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mdarocha** [comment]
Result of `nixpkgs-review pr 255378` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>boogie</li>
  </ul>
</details>

**Comment by yorickvP** [comment]
I'm not sure that the aliases merge like this, I'll test it later

**Comment by yorickvP** [comment]
@ofborg build dotnetPackages.boogie

**Comment by mdarocha** [comment]
> I'm not sure that the aliases merge like this, I'll test it later

```
       error: Alias dotnetPackages is still in all-packages.nix
```

Looks like you're right

**Comment by mdarocha** [comment]
@yorickvP I've managed to define the alias in a different way, so that compatibility is preserved. Guess we can move it to `aliases.nix` when `dotnet-packages.nix` is removed.

**Comment by mdarocha** [comment]
@ofborg build dotnetPackages.Boogie

**Review by doronbehar — APPROVED** [review]

**Comment by doronbehar** [comment]
Looks good to me, haven't tested anything, but I trust OP have tested this.

**Pull request merged**
