### PR TITLE
redmine: 3.4.8 -> 4.0.1

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Include Redmine 4.x series in NixOS, while maintaining the 3.4.x series. The 4.x series is very new and not necessarily something people will want to be upgrading to immediately. The 3.4.x series is still maintained upstream and receiving security patches. With this commit existing Redmine users can choose to upgrade to the 4.x series at their convenience, after they have been able to test in house to make sure compatibility with all of their plugins and settings.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg build redmine_4

**Comment by aanderse** [comment]
@GrahamcOfBorg test redmine

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg test redmine

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build nixosTests.redmine

**Comment by 7c6f434c** [comment]
@aanderse are you an extra-known-user for ofborg?

**Comment by aanderse** [comment]
> @aanderse are you an extra-known-user for ofborg?

https://github.com/NixOS/ofborg/blob/c17ef84004073cea718f21c1605e2242d7b3e4c0/config.extra-known-users.json#L2
Yes.

**Comment by aanderse** [comment]
> @GrahamcOfBorg test redmine

Notice the test says success but clicking more details doesn't show anything meaningful (to me).

https://github.com/NixOS/nixpkgs/pull/55234/checks?check_run_id=58937573

**Comment by 7c6f434c** [comment]
That's true and that is why I tried to run the test via `nixosTests`

**Comment by 7c6f434c** [comment]
O-o-o-K, Aarch64 seems to succeed with tests…

**Comment by aanderse** [comment]
Thanks!

**Pull request merged**
