### PR TITLE
xfsprogs: removed unneeded make configure invocation and build inputs

### PR DESCRIPTION
**Pull request by NickCao**
build log says `make: 'configure' is up to date.`, meaning that the invocation is a nop

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Review by trofi — APPROVED** [review]

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 233765` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnome.gnome-todo</li>
    <li>gnome2.gvfs</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>libvmi</li>
    <li>mailnagWithPlugins</li>
    <li>mailnagWithPlugins.dist</li>
    <li>qemu_xen</li>
    <li>qemu_xen.debug</li>
    <li>qemu_xen.ga</li>
    <li>qemu_xen_4_15</li>
    <li>qemu_xen_4_15.debug</li>
    <li>qemu_xen_4_15.ga</li>
    <li>qubes-core-vchan-xen</li>
    <li>xen</li>
    <li>xen-slim</li>
    <li>xenPackages.xen-slim</li>
    <li>xenPackages.xen-vanilla</li>
    <li>xenPackages.xen_4_15-slim</li>
    <li>xenPackages.xen_4_15-vanilla</li>
    <li>xen_4_15</li>
    <li>xen_4_15-slim</li>
    <li>xmonad_log_applet</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>redpanda-server</li>
  </ul>
</details>
<details>
  <summary>206 packages built:</summary>
  <ul>
    <li>CuboCore.coreaction</li>
    <li>CuboCore.corearchiver</li>
    <li>CuboCore.corefm</li>
    <li>CuboCore.coregarage</li>
    <li>CuboCore.corehunt</li>
    <li>CuboCore.coreimage</li>
    <li>CuboCore.coreinfo</li>
    <li>CuboCore.corekeyboard</li>
    <li>CuboCore.corepad</li>
    <li>CuboCore.corepaint</li>
    <li>CuboCore.corepdf</li>
    <li>CuboCore.corepins</li>
    <li>CuboCore.corerenamer</li>
    <li>CuboCore.coreshot</li>
    <li>CuboCore.corestats</li>
    <li>CuboCore.corestuff</li>
    <li>CuboCore.coreterminal</li>
    <li>CuboCore.coretime</li>
    <li>CuboCore.coretoppings</li>
    <li>CuboCore.coreuniverse</li>
    <li>CuboCore.libcsys</li>
    <li>adapta-gtk-theme</li>
    <li>almanah</li>
    <li>apptainer</li>
    <li>apptainer-overriden-nixos</li>
    <li>apx</li>
    <li>bubblemail</li>
    <li>bubblemail.dist</li>
    <li>budgie.budgie-control-center</li>
    <li>budgie.budgie-control-center.debug</li>
    <li>calls</li>
    <li>calls.devdoc</li>
    <li>cantata</li>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev (ceph-dev.dev)</li>
    <li>ceph.doc (ceph-dev.doc)</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man (ceph-dev.man)</li>
    <li>charliecloud</li>
    <li>chatty</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-control-center</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.nemo</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-python</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>cinnamon.nemo.dev</li>
    <li>clementine</li>
    <li>deepin.dde-control-center</li>
    <li>deepin.dde-daemon</li>
    <li>deepin.dde-device-formatter</li>
    <li>deepin.dde-dock</li>
    <li>deepin.dde-dock.dev</li>
    <li>deepin.dde-file-manager</li>
    <li>deepin.dde-gsettings-schemas</li>
    <li>deepin.dde-network-core</li>
    <li>deepin.dde-session-ui</li>
    <li>deepin.deepin-album</li>
    <li>deepin.deepin-compressor</li>
    <li>deepin.deepin-image-viewer</li>
    <li>deepin.deepin-music</li>
    <li>deepin.deepin-screen-recorder</li>
    <li>deepin.deepin-system-monitor</li>
    <li>deepin.udisks2-qt5</li>
    <li>deepin.util-dfm</li>
    <li>docker (docker_20_10)</li>
    <li>docker-gc</li>
    <li>docker.man (docker_20_10.man)</li>
    <li>elementary-planner</li>
    <li>endeavour</li>
    <li>enlightenment.enlightenment</li>
    <li>eos-installer</li>
    <li>evolution</li>
    <li>evolution-data-server (gnome.evolution-data-server)</li>
    <li>evolution-data-server-gtk4</li>
    <li>evolution-data-server-gtk4.dev</li>
    <li>evolution-data-server.dev (gnome.evolution-data-server.dev)</li>
    <li>evolution-ews</li>
    <li>evolutionWithPlugins</li>
    <li>exaile</li>
    <li>fn-cli</li>
    <li>folks</li>
    <li>folks.dev</li>
    <li>folks.devdoc</li>
    <li>gfbgraph</li>
    <li>gfbgraph.dev</li>
    <li>gfbgraph.devdoc</li>
    <li>glusterfs</li>
    <li>gnome-browser-connector</li>
    <li>gnome-multi-writer</li>
    <li>gnome-online-accounts</li>
    <li>gnome-online-accounts.debug</li>
    <li>gnome-online-accounts.dev</li>
    <li>gnome-online-accounts.devdoc</li>
    <li>gnome-online-accounts.man</li>
    <li>gnome-photos</li>
    <li>gnome-photos.installedTests</li>
    <li>gnome-recipes</li>
    <li>gnome.cheese</li>
    <li>gnome.cheese.devdoc</li>
    <li>gnome.cheese.man</li>
    <li>gnome.geary</li>
    <li>gnome.gnome-applets</li>
    <li>gnome.gnome-calendar</li>
    <li>gnome.gnome-contacts</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-control-center.debug</li>
    <li>gnome.gnome-disk-utility</li>
    <li>gnome.gnome-flashback</li>
    <li>gnome.gnome-initial-setup</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gnome-notes</li>
    <li>gnome.gnome-online-miners</li>
    <li>gnome.gnome-panel</li>
    <li>gnome.gnome-panel.dev</li>
    <li>gnome.gnome-panel.man</li>
    <li>gnome.gnome-session</li>
    <li>gnome.gnome-session.debug</li>
    <li>gnome.gnome-session.sessions</li>
    <li>gnome.gnome-shell</li>
    <li>gnome.gnome-shell.debug</li>
    <li>gnome.gnome-shell.devdoc</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-tweaks</li>
    <li>gnome.gvfs</li>
    <li>gnome.gvfs.debug</li>
    <li>gnome.nixos-gsettings-overrides</li>
    <li>gnome.totem</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.gsconnect.installedTests</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>grilo-plugins</li>
    <li>gvfs</li>
    <li>gvfs.debug</li>
    <li>libgdata</li>
    <li>libgdata.dev</li>
    <li>libgdata.installedTests</li>
    <li>libxfs (libxfs.bin ,libxfs.dev ,libxfs.doc ,xfsprogs.dev)</li>
    <li>libzapojit</li>
    <li>libzapojit.dev</li>
    <li>mate.mate-utils</li>
    <li>mojave-gtk-theme</li>
    <li>monitor</li>
    <li>nfs-ganesha</li>
    <li>nvidia-docker</li>
    <li>pantheon.elementary-calendar</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-mail</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.elementary-tasks</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-plug-onlineaccounts</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>partition-manager</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>pipework</li>
    <li>psensor</li>
    <li>python310Packages.jupyter-repo2docker</li>
    <li>python310Packages.jupyter-repo2docker.dist</li>
    <li>python311Packages.jupyter-repo2docker</li>
    <li>python311Packages.jupyter-repo2docker.dist</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>rabbitvcs</li>
    <li>rabbitvcs.cli</li>
    <li>rabbitvcs.dist</li>
    <li>rapid-photo-downloader</li>
    <li>rapid-photo-downloader.dist</li>
    <li>sambaFull (samba4Full)</li>
    <li>sambaFull.dev (samba4Full.dev)</li>
    <li>sambaFull.man (samba4Full.man)</li>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>spaceFM</li>
    <li>stratisd</li>
    <li>stratisd.initrd</li>
    <li>udiskie</li>
    <li>udiskie.dist</li>
    <li>udisks (udisks2)</li>
    <li>udisks.dev (udisks2.dev)</li>
    <li>udisks.devdoc (udisks2.devdoc)</li>
    <li>udisks.man (udisks2.man)</li>
    <li>udocker</li>
    <li>udocker.dist</li>
    <li>usbimager</li>
    <li>usermount</li>
    <li>valent</li>
    <li>ventoy-full</li>
    <li>vifm-full</li>
    <li>vimix-gtk-themes</li>
    <li>whitesur-gtk-theme</li>
    <li>wipefreespace</li>
    <li>xfsdump</li>
    <li>xfsprogs</li>
    <li>xfsprogs.bin</li>
    <li>xfsprogs.doc</li>
    <li>xfstests</li>
  </ul>
</details>

**Comment by alberand** [comment]
@NickCao why libtool was removed? With this version I'm getting:
```shell
error: builder for '/nix/store/m82hdrqbr9pd8hn4p9dpm81rwnp2fwv4-xfsprogs-git.drv' failed with exit code 2;
       last 10 log lines:
       > updateAutotoolsGnuConfigScriptsPhase
       > configuring
       > patching script interpreter paths in ./install-sh
       > find: './install-sh': No such file or directory
       > no configure script, doing nothing
       > building
       > build flags: -j12 SHELL=/nix/store/a7f7xfp9wyghf44yv6l6fv9dfw492hd3-bash-5.2-p15/bin/bash
       > libtoolize -c -i -f
       > /nix/store/a7f7xfp9wyghf44yv6l6fv9dfw492hd3-bash-5.2-p15/bin/bash: line 1: libtoolize: command not found
       > make: *** [Makefile:111: configure] Error 127
```

**Comment by trofi** [comment]
`git` suggests you are not using `xfsprogs` derivation as is. Could it be you are using `git` checkout of `xfsprogs` and need a few extra depends to generate build system files that are normally present in release tarball?

**Comment by alberand** [comment]
Yes, I have version and src overwritten. I have my patched branch pinned. I will check if updating xfsprogs solves it.

28 Jul 2023 16:24:44 Sergei Trofimovich ***@***.***>:

**Comment by trofi** [comment]
In that case you might need to pull `libtool` and other dev-only depends (autoconf? automake? autoreconf hook?) explicitly as well. Those are usually done via `xfsprogs.overrideAttrs(oa: { nativeBuildInputs = oa.nativeBuildInputs ++ [ libtool ... ]; }` (just like `src`).

**Comment by alberand** [comment]
> In that case you might need to pull `libtool` and other dev-only depends (autoconf? automake? autoreconf hook?) explicitly as well. Those are usually done via `xfsprogs.overrideAttrs(oa: { nativeBuildInputs = oa.nativeBuildInputs ++ [ libtool ... ]; }` (just like `src`).

Thank you! Yes, the `nativeBuildInputs` and `preConfigure` (with `make configure`) solved the problem. But why is this needed? Why the nixpkg version doesn't need that dependencies? Not clear for me how overwriting `src` and `version` in derivation breaks it.

**Comment by NickCao** [comment]
Release tarballs are not raw sources, instead they are preprocessed by autoconf/libtool... to generate the configure scripts. You may compare the content of the release tarballs and the git checkout to see the difference.

**Comment by alberand** [comment]
> Release tarballs are not raw sources, instead they are preprocessed by autoconf/libtool... to generate the configure scripts. 

Thanks! Sorry to bother, but one more question, is there a way to invoke this preprocessing, so I don't need to modify dependencies and preConfigure? Or if you can point me to documentation/sources where it's happening would also help.

> You may compare the content of the release tarballs and the git checkout to see the difference.

Yes, it differs, I see, thanks! For anyone else wondering on how to get tarball of Nix package: `nix-build "<nixpkgs>" -A xfsprogs.src`

**Comment by NickCao** [comment]
Just run `make configure` in the source tree should work (very likely that upstream also produce the release tarballs this way). Another option is adding `autoreconfHook` to `nativeBuildInputs`, it handles everything for you.

**Pull request merged**
