### PR TITLE
lpod-python: init -> 1.1.5

### PR DESCRIPTION
**Pull request by leenaars**

### CODE REVIEW

**Comment by FRidh** [comment]
Judging from the Travis build log this package doesn't seem to be compatible with Python 3.x. Could you fix this? Aside from that this looks good.

**Comment by leenaars** [comment]
Indeed, I think some work was done once on adding Python 3 support, but I don't think it was finished.

**Comment by FRidh** [comment]
Could you rebase and squash your commits. Then it's ready to be merged.

**Comment by FRidh** [comment]
@leenaars I think something has gone with the rebasing

**Comment by leenaars** [comment]
@FRidh Eeks. Yes, it did. Okay now...

**Comment by FRidh** [comment]
thanks

**Pull request merged**
