### PR TITLE
sequoia: fix build by migrating off legacy fetchCargo implementation

### PR DESCRIPTION
**Pull request by bhipple**
Currently broken; see #79975 for details. Would also be fixed by #80153
eventually, but since we want to upgrade either way we might as well do so now.

https://hydra.nixos.org/job/nixpkgs/trunk/sequoia.x86_64-linux

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bhipple** [comment]
@grahamcofborg build

**Comment by bhipple** [comment]
Interesting.  This built and passed all of test cases for me locally (using NixOS with sandboxing), and built for ofBorg, but appears to have just failed on Hydra . . . any ideas?  

https://hydra.nixos.org/build/112870138

**Comment by doronbehar** [comment]
It's the same old https://github.com/NixOS/nixpkgs/issues/70646 .

**Comment by bhipple** [comment]
Ah, so I'm guessing it'll build eventually?  This package did take a looooooooong time to compile and run its test cases on my laptop -- long enough that I went and spun up a 48 core build box on AWS instead :)

**Pull request merged**
