### PR TITLE
Simpler pure nixpkgs

### PR DESCRIPTION
**Pull request by zimbatm**
###### Description of changes

Make it easier to use the pure version of nixpkgs by allowing the `system` argument. I'm happy that localSystem and crossSystem exist, but the common case for me is to pass the relevant system.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Ericson2314 — CHANGES_REQUESTED** [review]
I don't want the dinner entry point to be cluttered up with redundant ways of passing the same information. This makes the pure case more complicated, not simpler.

**Comment by lovesegfault** [comment]
Maybe we should rename those inputs to `hostPlatform` and `targetPlatform`, if anything?

**Comment by zimbatm** [comment]
Ok, let me quickly unroll a few thoughts and see where we agree.

1. Having the same function signature for the pure and impure functions is a nice property. It makes it easier to swap one for the other.
2. Now the impure entrypoint is purely about injecting impure variables, no mixed concern.
3. Calling nixpkgs with `{ inherit system; }` is the common case. Typing `{ localSystem = { inherit system; }; }` is more complicated. That's what I meant by simplifying, making it easier for the user by optimizing for the common case.
4. The reality is that flakes will be around for a while now, and they solidify the position of the system tuple (sorry).

I just really care about the usability of the user in that scenario.

Another variation might be to allow `localSystem` and `crossSystem` to also take strings. And then either deprecate the `system` entirely, or clarify that system is `localSystem` and deprecate the latter.

**Comment by Shawn8901** [comment]
I am have not opinion on the PR, but that system is meant to be legacy is at least on my opinion quite clearly stated out on the impure entrypoint comments.
https://github.com/NixOS/nixpkgs/blob/6337682f24aa554b0f7738a3a3f5ca6e2dfc1d34/pkgs/top-level/impure.nix#L14

**Comment by zimbatm** [comment]
If I am not mistaken, that was @Ericson2314's idea; he did a ton of work on the cross-compilation and his idea was that we would move to more advanced system declarations and deprecate the old `system` attribute. The problem is that most people don't use cross-compilation so all of this is just making their usage more complicated. Ideally, we can find a middle ground that works well for both cases.

**Comment by Ericson2314** [comment]
Yes it was my idea. Cross or no cross, the system string is very rough and doesn't capture enough information to characterize the system.

**Comment by zimbatm** [comment]
The problem is that they are not going away. We have `builtins.currentSystem` and flakes, and they are conveniently short. So it's better to embrace and extend.

**Comment by zimbatm** [comment]
it's time to close some old PRs

**Pull request closed without merging**
