### PR TITLE
transmission: 3.0.0 -> 4.0.2

### PR DESCRIPTION
**Pull request by stephenmw**
This removes unneeded patches and adds a build time dependency on python.

###### Description of changes

https://github.com/transmission/transmission/releases/tag/4.0.2

The most important change I noticed is that local peer discovery (lpd) is now enabled by default. This isn't documented in the release notes.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GabrielDougherty** [comment]
Partway through a nixpkgs-review currently. I got these errors so far:

```
error: builder for '/nix/store/hf081ch03dig47sabjchqswz9jpljc4f-transmission-4.0.2.drv' failed with exit code 1;
       last 10 log lines:
       > -- Checking for modules 'gtkmm-3.0>=3.24.0;glibmm-2.4>=2.60.0;giomm-2.4>=2.26.0'
       > --   No package 'gtkmm-3.0' found
       > --   No package 'glibmm-2.4' found
       > --   No package 'giomm-2.4' found
       > CMake Error at CMakeLists.txt:304 (message):
       >   GTK is required but wasn't found
       >
       >
       > -- Configuring incomplete, errors occurred!
       > See also "/build/source/build/CMakeFiles/CMakeOutput.log".
       For full logs, run 'nix log /nix/store/hf081ch03dig47sabjchqswz9jpljc4f-transmission-4.0.2.drv'.
error: builder for '/nix/store/5inv8qk99vfgrn9hkkmrardkckk0p77b-torrential-2.0.1.drv' failed with exit code 1;
       last 10 log lines:
       >                  from src/com.github.davidmhewitt.torrential.p/Dialogs/FileSelectDialog.c:32:
       > /nix/store/iwn3lazhagb72wyrdnjbzqf9n847p5xm-transmission-4.0.2/include/transmission/tr-macros.h:8:10: fatal error: array: No such file or directory
       >     8 | #include <array>
       >       |          ^~~~~~~
       > compilation terminated.
       > [21/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_MultiInfoBar.c.o
       > [22/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_Application.c.o
       > [23/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_PreferencesWindow.c.o
       > [24/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_TorrentListBox.c.o
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/5inv8qk99vfgrn9hkkmrardkckk0p77b-torrential-2.0.1.drv'.
```

I'm on  x86_64-linux Pop!_OS

**Comment by wegank** [comment]
Duplicate of #215316 and #221582...?

**Comment by GabrielDougherty** [comment]
Result of `nixpkgs-review pr 222051` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>fragments</li>
    <li>torrential</li>
    <li>transmission-gtk</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>libtransmission</li>
    <li>transmission</li>
    <li>transmission-qt</li>
  </ul>
</details>

**Comment by stephenmw** [comment]
Since this is a duplicate, I will close out this pull request.

**Pull request closed without merging**
