### PR TITLE
palemoon-bin: init at 32.0.0

### PR DESCRIPTION
**Pull request by OPNA2608**
###### Description of changes

Due to https://github.com/NixOS/nixpkgs/pull/201859, we won't be able to provide Nix-built binary downloads of Pale Moon past NixOS 22.11:
```
↪ nix-build . --no-out-link -A palemoon
error: Package ‘python-2.7.18.6’ in <pwd>/pkgs/development/interpreters/python/cpython/2.7/default.nix:330 is marked as insecure, refusing to evaluate.
```

[The Debian maintainer is in a similar boat](https://forum.palemoon.org/viewtopic.php?f=3&t=11466&start=760#p236112). We'll have to make do with the prebuilt binaries for now.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
That dreadful day has come...

**Review by AndersonTorres — APPROVED** [review]

**Comment by winterqt** [comment]
Is Pale Moon even maintained? I'm not sure how I feel about shipping packages in-tree that we can't even build because their build system (by association) is EOL...

Maybe a flake would be best?

**Comment by OPNA2608** [comment]
> Is Pale Moon even maintained?

Latest release is from 2023-01-24 & added "full coverage of the ECMAScript 2016-2020 JavaScript specifications, with the exception of BigInt primitives". There's just no-one on the team with the time & Python(2,3) experience to migrate the build system: https://github.com/NixOS/nixpkgs/pull/204336#issuecomment-1336252606

**Comment by AndersonTorres** [comment]
And they are (correctly, I should say) afraid of another deprecation in the future, given that the less than optimal handling of Python migration.

**Pull request merged**
