### PR TITLE
plasma-integration: Fix font style name bug with Qt >= 5.8

### PR DESCRIPTION
**Pull request by ttuegel**
### Motivation

Qt 5.8 corrects a bug in font style name handling. Unfortunately, KDE relies on that bug. As a result, some font styles (bold, italic, etc.) will be unavailable for UI fonts. This is a patch from upstream and a configuration file update.

### Testing

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ttuegel** [comment]
@GrahamcOfBorg test plasma5

**Comment by grahamc** [comment]
@ttuegel do you know if this is a bug in ofborg, or nixos, or the kde test?

**Comment by ttuegel** [comment]
@grahamc The test passes locally on `x86_64-linux`. I presume it is an ofborg problem, but I don't have positive evidence of that.

**Comment by pbogdan** [comment]
I think it may have been fixed in https://github.com/NixOS/nixpkgs/commit/2a09b4275c353bde6ee72d126cd0e99834dcf66e?

**Comment by grahamc** [comment]
I think you're right. Let's try this again:

@GrahamcOfBorg test plasma5

**Comment by grahamc** [comment]
This seems to be the core of the issue:

```
trying https://phabricator.kde.org/file/data/nr6lcghxw2xejj7pftfh/PHID-FILE-dexapcoktxshi5dtwhk7/D9070.diff
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download D9070.diff from any mirror
builder for ‘/nix/store/9kz4hdn0mhh045bcqplfaggfn3y9b2gj-D9070.diff.drv’ failed with exit code 1
```

**Comment by ttuegel** [comment]
It seems like Phabricator might randomly generate patch URLs, so let's try downloading it from the interface instead.

**Comment by grahamc** [comment]
@ttuegel ^ was this auto-building helpful, or annoying?

**Comment by ttuegel** [comment]
Helpful, since I was just going to request the build again anyway. 😄 

I can't figure out why the hash is failing now, but that's an unrelated issue.

**Comment by ttuegel** [comment]
Let's try checking the patch in to Nixpkgs, since I can't get a stable link upstream. 🙄

**Comment by ttuegel** [comment]
@GrahamcOfBorg test plasma5

**Comment by ttuegel** [comment]
@grahamc 
The test fails on `aarch64` due to a problem with OCR; the root of the problem seems to be:
```
machine: waiting for (?^:Alice Foobar) to appear on the screen
machine: performing optical character recognition
machine: sending monitor command: screendump /build/ocrin.ppm
sh: command: not found
```
and later:
```
convert: unable to open image `/build/ocrin.ppm': No such file or directory @ error/blob.c/OpenBlob/2735.
convert: no images defined `tiff:-' @ error/convert.c/ConvertImageCommand/3258.
```
Is there a known issue with OCR on `aarch64`?

**Comment by grahamc** [comment]
cc @dezgeg 

For now I'd not worry too much about the aarch64 failure.

**Pull request merged**
