### PR TITLE
nixVersions.nix_2_13: init at 2.13.1

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
cc 

@adisbladis @Mic92 `nix-eval-jobs`
@lf- `nix-doc`

**Comment by lf-** [comment]
Thank you for pinging me. I'll have a look.

**Comment by lf-** [comment]
I have updated nix-doc so it will build with nix 2.13, as well as adding integration tests.

The update PR is here: https://github.com/NixOS/nixpkgs/pull/211310

Let's get the nix-doc update PR merged before updating Nix so people using the plugin won't have any issues :)

**Comment by zowoq** [comment]
@ofborg build nix-doc

**Comment by zowoq** [comment]
@lf- Looks like `nix-doc` is broken again with 2.13.1.

**Comment by lf-** [comment]
damn! I'll fix it in the next couple days.

**Comment by lf-** [comment]
@zowoq it looks like nix reverted one of the API changes in 2.13.1. I've fixed nix-doc upstream to support that as well, nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/211499

**Comment by Mic92** [comment]
I did an rc1 release for nix-eval-jobs but there is still a double-free bug that I need to fix.

**Comment by zowoq** [comment]
> I did an rc1 release for nix-eval-jobs but there is still a double-free bug that I need to fix.

@Mic92 Are you fine with merging this pinning `nix-eval-jobs` or do you want to wait?

**Comment by vcunat** [comment]
She update of default nix broke the tarball job and is thus blocking channels:
https://hydra.nixos.org/log/wlx6pqyzczhpzl4ips8f9gim3l3kwzqw-nixpkgs-tarball-23.05pre445417.ad161ee67ce.drv

(So far I don't get what exactly got broken there.)

**Comment by Artturin** [comment]
> She update of default nix broke the tarball job and is thus blocking channels: [hydra.nixos.org/log/wlx6pqyzczhpzl4ips8f9gim3l3kwzqw-nixpkgs-tarball-23.05pre445417.ad161ee67ce.drv](https://hydra.nixos.org/log/wlx6pqyzczhpzl4ips8f9gim3l3kwzqw-nixpkgs-tarball-23.05pre445417.ad161ee67ce.drv)
> 
> (So far I don't get what exactly got broken there.)

maybe related to https://github.com/NixOS/nix/pull/6204

**Comment by zowoq** [comment]
Should we revert https://github.com/NixOS/nixpkgs/commit/956bc25a803ac00394f2a6d98b7a901ab3065dcf and https://github.com/NixOS/nixpkgs/commit/37a44ff3a0415ab84fe52e9c78ad4bafd227737b for now? (no need to revert the other two)

**Comment by roberth** [comment]
@zowoq sgtm

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/212010

@roberth Thanks for debugging and follow up on the nix side.

**Comment by Mic92** [comment]
@zowoq for my release process of nix-eval-jobs it would be nice if I could have 2.13 before it is made the default. Than I can make a release of nix-eval-jobs with the new version.

**Comment by zowoq** [comment]
nix 2.13.1 is in master, we just reverted making it the default.

nix-eval-jobs is still pinned to 2.12, didn't revert as I wasn't sure if it or nix would get fixed first.

**Comment by zowoq** [comment]
nix 2.13.2: https://github.com/NixOS/nixpkgs/pull/212769

**Pull request merged**
