### PR TITLE
treewide: stdenv.lib -> lib

### PR DESCRIPTION
**Pull request by siraben**
###### Motivation for this change
Part of #108938.

I wasn't doing sed with `/g`, so here's the fix. Proof:

```
$ rg 'stdenv\.lib' pkgs/applications | wc -l
0
$ rg 'stdenv\.lib' pkgs/desktops | wc -l
0
$ rg 'stdenv\.lib' pkgs/data | wc -l
0
$ rg 'stdenv\.lib' pkgs/desktops | wc -l
0
$ rg 'stdenv\.lib' pkgs/games | wc -l
0
$ rg 'stdenv\.lib' pkgs/misc | wc -l
0
$ rg 'stdenv\.lib' pkgs/shells | wc -l
0
$ rg 'stdenv\.lib' pkgs/tools | wc -l
0
$ rg 'stdenv\.lib' pkgs/top-level | wc -l
0
```

I have not performed the change to pkgs/development which has over 30K occurrences of stdenv.lib
```
$ rg 'stdenv\.lib' pkgs/development | wc -l
30598
```

### CODE REVIEW

**Comment by siraben** [comment]
`pkgs/os-specific` is annoying to debug... may move it to a different PR to get things going here.

**Comment by jonringer** [comment]
a lot of the os-specific packages probably have a lot more "legacy" nix code in them. I think chunking this work into more but smaller PR's would be wise

**Comment by cole-h** [comment]
Found a few more evaluation errors with `nix shell -f. hydra-unstable -c hydra-eval-jobs -I . pkgs/top-level/release.nix`, fixed in e2b82bcbf3fcc0afe5b7e4d8a766e6f623f42ddb.

**Comment by cole-h** [comment]
Found a few more. 085ae5e48582632d68d97be9dc3acd4db56676fb

`hydra-eval-jobs` + `outpaths.nix` are a match made in heaven (for this kind of stuff).

**Comment by SuperSandro2000** [comment]
Maybe we should overthink how we currently do this. Causing 500+ rebuilds and a few eval errors is not that ideal.

**Comment by siraben** [comment]
@SuperSandro2000 The mass rebuild is because of whitespace changes in the phases, again.

**Comment by siraben** [comment]
Rebased on master again because of my other treewide PR. If looks good, I will squash the two commits.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
There are under 100 rebuilds. I think that could have gone straight to master.

**Comment by Mic92** [comment]
Right. I missed that the mass-rebuild was removed.

**Comment by siraben** [comment]
Reverted back to badf512,

**Comment by archseer** [comment]
This breaks in certain places where lib wasn't imported:

```
error: --- UndefinedVarError ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ nix
at: (3:8) in file: /nix/store/qh1497vqx38yl6qcpdgf83jd45i96ahi-source/pkgs/applications/editors/kakoune/plugins/kak-fzf.nix

     2|
     3| assert lib.asserts.assertOneOf "fzf" fzf.pname [ "fzf" "skim" ];
      |        ^
```

https://github.com/NixOS/nixpkgs/blob/3bdf95ceb5660273a01ed2e5be2676487f7e820e/pkgs/applications/editors/kakoune/plugins/kak-fzf.nix#L1-L3

**Comment by jonringer** [comment]
@archseer although unfortunate, these changes are hard to review due to the massive scope, I'll create a PR to fix the affected packages

**Comment by SuperSandro2000** [comment]
Those plugins are not evaluated by ofborg so this could happen with every treewide PR. I suggest to add them to evaluation do we noticed such regressions.

**Pull request merged**
