### PR TITLE
neovide: add missing cctools.libtool dependency

### PR DESCRIPTION
**Pull request by tjni**
This targets staging-next, because the fix does not work on master (some header files are not found). staging-next should be merged around Nov 12 according to https://github.com/NixOS/nixpkgs/issues/339153.

Fixes https://github.com/NixOS/nixpkgs/issues/354889.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — APPROVED** [review]
Thanks!

Do you know if the `xcbuild` dependency is required? We no longer need it for `xcrun`, only `xcodebuild`.

**Comment by tjni** [comment]
@emilazy It works without xcodebuild, cool!

**Comment by ck3d** [comment]
The time between PR and merge is less than one day! How can I as maintainer do the review?

**Comment by emilazy** [comment]
This is a simple Zero Hydra Failures fix to address a regression caused by changes in the Darwin build environment, which I’m one of the maintainers of. I felt confident that the fix is correct and updates the package to not be broken by the new Darwin build environment. If you have concerns about this PR, I’m sorry and let me know if there is anything I can do – note though that maintainership is not ownership and that it’s normal for packages across the tree to get updated quickly to fix issues caused by changes to the standard build environment.

**Comment by emilazy** [comment]
Ugh, but you’re right that this broke eval on Linux and I should have caught that – I didn’t see as I wasn’t pinged on the subsequent issue. I will send a PR to fix it now.

**Comment by tjni** [comment]
Sorry guys, I forgot to scope the dependency to Darwin.

**Comment by futile** [comment]
How come this wasn't caught by CI? Wasn't CI green for this PR? It shouldn't have been if `x86_64-linux` failed to build, no?

**Comment by emilazy** [comment]
ofborg is very slow these days, and for Darwin it’s basically unusable, so I’m used to manually testing builds for Darwin‐related PRs rather than waiting for it – but of course that meant that Linux didn’t get checked, which is my fault. (Hopefully [whatever form the ofborg redesign takes](https://discourse.nixos.org/t/infrastructure-announcement-the-future-of-ofborg-your-help-needed/56025) will help address these issues so that we can rely on ofborg results for all platforms.)

Since this was on the `staging-next` branch where we buffer up fixes for changes that cause mass rebuilds and monitor the results, there is a natural buffer between any commit being merged and it hitting the `master` branch, and we tend to move on fixes for regressions more quickly. This PR followed the common pattern of fixes for the new Darwin scheme; I’ve reviewed and merged a bunch of these as we work to fix the regressions before the release, and didn’t give this one any more thought than others. However, in this case the new regression being introduced slipped through the cracks and `staging-next` was merged into `master` a few days later.

All of that is on me and not an excuse for my sloppiness here, and I’m sorry that the issue hit the channels. The channel should bump with the fix in the next couple days.

**Comment by futile** [comment]
Awesome, thanks for the super clear answer! No problem, thank you for your work on fixing neovide for aarch64-darwin, and your work on nixpkgs in general! :)

**Pull request merged**
