### PR TITLE
pulseaudio: 12.2 -> 13.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/13.0/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/pull/68313

Though we might have to go with this one if the issues with darwin can't be resolved timely.

**Comment by dtzWill** [comment]
Oops missed that, and yeah I ducked the move to meson O:).  Didn't try so your call-- I can help test if you want to pursue that instead :).

**Comment by worldofpeace** [comment]
Thanks, hopefully the bug report gets good attention
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/734

**Comment by bjornfor** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/pull/68313.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build pulseaudio libpulseaudio pulseaudioFull qtwebengine

**Comment by worldofpeace** [comment]
I doesn't seem pulseaudio is supporting darwin very well these days.

Merging as https://github.com/NixOS/nixpkgs/pull/68313 will break darwin builds.

**Pull request merged**
