### PR TITLE
Tcl: 8.5.15 -> 8.6.4

### PR DESCRIPTION
**Pull request by AndersonTorres**

### CODE REVIEW

**Comment by wkennington** [comment]
Already in staging. You are also missing the tk bump which needs to be in
lockstep.

**Comment by imz** [comment]
@wkennington

Is it correct that [the revision in staging](https://github.com/NixOS/nixpkgs/blob/staging/pkgs/development/interpreters/tcl/default.nix#L25) has ` libdir = "lib/tcl8.5";` whereas the new version is 8.6.

This suggested patch had `libdir` being changed, too.

**Comment by vcunat** [comment]
It should hopefully be OK in current staging https://github.com/NixOS/nixpkgs/commit/8286f6c#commitcomment-10909142.

**Comment by imz** [comment]
@vcunat Hmm, so I somehow missed a commit of March 27, when I was looking at staging... and my link above (<https://github.com/NixOS/nixpkgs/blob/staging/pkgs/development/interpreters/tcl/default.nix#L25>) stopped to work.

**Comment by vcunat** [comment]
It stopped because the file no longer exists on staging :-) For the status see https://github.com/NixOS/nixpkgs/blob/staging/pkgs/development/interpreters/tcl/

**Pull request closed without merging**
