### PR TITLE
nixos/bcache: install udev rules outside initrd too

### LINKED ISSUE #26281: Bcache udev rules not installed outside initrd
`bcache-tools` installs udev rules into the initrd but not into the main system. As a result, symlinks to bcache devices from `/dev/disk/by-uuid` and `/dev/disk/by-label` are missing.

Adding `bcache-tools` to `services.udev.packages` doesn't quite suffice as a workaround because of a hardcoded reference to `/bin/sh`. Instead I had to copy the contents of `69-bcache.rules` into `services.udev.extraRules` and replace `/bin/sh` with `${pkgs.stdenv.shell}`.

cc @bjornfor

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change
Should fix https://github.com/NixOS/nixpkgs/issues/26281 ("Bcache udev rules not installed outside initrd").

(Apparently I cannot verify that these rules are working by generating symlinks to bcache devices in /dev/disk/by-*, because on my system I run LVM on top of bcache.)

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
I rebuilt and rebooted my system with this. No harm done.

**Review by abbradar — APPROVED** [review]
Seems all good to me!

I still wonder _why_ do we need to replace `/bin/sh` -- shouldn't it work given that `/bin/sh` is installed and I don't think udev isolates itself in a chroot/mount namespace? Still, less sources of impurity is anyway better.

**Comment by bjornfor** [comment]
Good question. Maybe @dfoxfranke can answer, because it seems that was tested:

```
@dfoxfranke wrote:
Adding bcache-tools to services.udev.packages doesn't quite suffice as a workaround
because of a hardcoded reference to /bin/sh. Instead I had to copy the contents of
69-bcache.rules into services.udev.extraRules and replace /bin/sh with ${pkgs.stdenv.shell}.```

**Comment by dfoxfranke** [comment]
@bjornfor See https://github.com/bjornfor/nixpkgs/commit/2230f640a6869a2f9d9b877b2bf5693821d36379#commitcomment-22384001

**Comment by abbradar** [comment]
Argh, I definitely need more sleep - I have read this and acknowledged in my head but still asked the question again. Thanks!

**Comment by bjornfor** [comment]
Looking at 775f381a9e34abf502ad438ebce7258c5bae9643 it is clear the /bin/sh substitute rule was added for bcache. I think I'll close this PR and open a new one from my old branch: https://github.com/NixOS/nixpkgs/compare/master...bjornfor:bcache-udev-rules

And if the changes in the above branch does create a regression, it will be at build time (AFAICT), not runtime (when booting).

**Comment by bjornfor** [comment]
Closing in favor of the new PR: https://github.com/NixOS/nixpkgs/pull/26354.

**Pull request closed without merging**
