### PR TITLE
node-gyp: init at 10.2.0

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
see #229475 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by doronbehar — APPROVED** [review]
Thanks for working on this :). Changes look good to me, but I'd wait for more reviewers to respond... A nixpkgs-review report would be nice too.

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 334377` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>code-server</li>
    <li>openvscode-server</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>balena-cli</li>
    <li>cdxgen</li>
    <li>n8n</li>
    <li>node-gyp</li>
    <li>nodehun</li>
    <li>vscode-js-debug</li>
  </ul>
</details>

**Review by gepbird — APPROVED** [review]
`code-server` fails on master too, no new failures :rocket: 

Tested the update script, changes LGTM!

**Review by thomasjm — APPROVED** [review]
Thanks for working on this. The `nodehun` package works, so I'm happy as far as the packages I maintain.

I wish this didn't require adding 5,000 lines of `package-lock.json` though. One of the main motivations mentioned in #229475 is to avoid having a centralized update script that takes 4 hours to run. But breaking that up into *separate* packages that have their own update scripts and a large increase in lockfile data doesn't necessarily seem like an improvement. I see the `node-gyp` repo doesn't provide a lockfile but it would be nice if there were some other way to do this. Approving though because I have no idea what that way would be :)

**Comment by doronbehar** [comment]
> I wish this didn't require adding 5,000 lines of `package-lock.json` though.

I too feel the same. I was wondering, do we have a clue why upstream won't track such a file in their repository? That's the best I found:

[nodejs/node-gyp@`020e2bd` (#1573)](https://github.com/nodejs/node-gyp/pull/1573/commits/020e2bdb6836b57462cccac6083a67f074019658)

**Pull request merged**
