### PR TITLE
Revive multiple outputs for Haskell packages.

### PR DESCRIPTION
**Pull request by nc6**
Incorporates fix to ghcWithPackages from domenkozar.

### CODE REVIEW

**Comment by vcunat** [comment]
@peti: through your `https://github.com/peti/nixpkgs haskell-updates` -> https://hydra.nixos.org/jobset/nixpkgs/haskell-updates or you want it some other way?

**Comment by peti** [comment]
Test builds are running at https://hydra.nixos.org/jobset/nixpkgs/pr-32112.

**Comment by domenkozar** [comment]
41 failing looks pretty good :D

**Comment by domenkozar** [comment]
@peti I went through all of failures and they are not related to this PR. What else is missing to merge this?

**Comment by peti** [comment]
It would be great if someone could test whether functions like `ghcWithPackages` and `ghcWithHoogle` actually work properly in that branch.

**Comment by nc6** [comment]
@peti 
```
[nc@varda:~/nixpkgs.hask-split-out]$  nix-shell -p "haskellPackages.ghcWithPackages (ps: [ps.turtle])" -I .

[nix-shell:~/nixpkgs.hask-split-out]$ ghci 
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/nc/.ghc/ghci.conf
λ> import Turtle
(0.08 secs, 0 bytes)
```

**Comment by peti** [comment]
Has anyone tested ghcWithHoogle?

**Comment by nc6** [comment]
```
[nc@varda:~/nixpkgs.hask-split-out]$  nix-shell -p "haskellPackages.ghcWithHoogle (ps: [ps.turtle])" -I .

[nix-shell:~/nixpkgs.hask-split-out]$ hoogle "MonadIO io => Shell a -> FoldM IO a r -> io r"
Turtle.Shell foldIO :: MonadIO io => Shell a -> FoldM IO a r -> io r
Turtle.Bytes shellStrictWithErr :: MonadIO io => Text -> Shell ByteString -> io (ExitCode, ByteString, ByteString)
Turtle.Bytes procStrict :: MonadIO io => Text -> [Text] -> Shell ByteString -> io (ExitCode, ByteString)
Turtle.Bytes procStrictWithErr :: MonadIO io => Text -> [Text] -> Shell ByteString -> io (ExitCode, ByteString, ByteString)
CoreMonad liftIO2 :: MonadIO m => (a -> b -> IO c) -> a -> b -> m c
MonadUtils liftIO2 :: MonadIO m => (a -> b -> IO c) -> a -> b -> m c
CoreMonad liftIO3 :: MonadIO m => (a -> b -> c -> IO d) -> a -> b -> c -> m d
MonadUtils liftIO3 :: MonadIO m => (a -> b -> c -> IO d) -> a -> b -> c -> m d
Data.StateVar ($~) :: (HasUpdate t a b, MonadIO m) => t -> (a -> b) -> m ()
Data.StateVar ($~!) :: (HasUpdate t a b, MonadIO m) => t -> (a -> b) -> m ()
-- plus more results not shown, pass --count=20 to see more
```

**Comment by nc6** [comment]
@peti See above!

**Comment by orivej** [comment]
Could not this mass rebuild have gone via staging? I had to revert it in my local checkout just to deploy hydra without building ghc myself.

**Comment by vcunat** [comment]
I think it had its Hydra job, but staging got merged to master in the meantime...

**Comment by orivej** [comment]
Oh, well, it happens…

**Comment by vcunat** [comment]
Problem: output cycle in `happy` on Darwin: https://hydra.nixos.org/build/65352540 (killing ~1.3k builds)

**Comment by vcunat** [comment]
There are apparently also a few linux regressions due to this PR: https://hydra.nixos.org/eval/1415828?filter=linux&compare=1415796&full=#tabs-now-fail

**Comment by LnL7** [comment]
The cycles between out and bin are caused by https://github.com/NixOS/nixpkgs/pull/25537

**Comment by peti** [comment]
`ghcWithPackages` appears to be broken again: https://github.com/NixOS/nixpkgs/issues/32332. I cannot even reproduce the example reported as success in https://github.com/NixOS/nixpkgs/pull/32112#issuecomment-348807773.

**Comment by domenkozar** [comment]
@peti I will fix this today.

**Comment by peti** [comment]
I thought it was fixed already? I'm a little disappointed, to be honest. This is the second time this PR has completely broken the Haskell infrastructure and it seems pretty obvious that no-one has ever used this code before. This does *not* inspire confidence.

**Comment by peti** [comment]
> It's unfair to expect things are working when there is no indication what is intended to work.

I beg your pardon? The expectation that `ghcWithPackages` can successfully create a working development environment was clearly communicated in https://github.com/NixOS/nixpkgs/pull/32112#issuecomment-348756927, was it not?

**Comment by domenkozar** [comment]
@peti did you read the comment next to yours thaylt shows that?

**Comment by peti** [comment]
I am sorry, but I don't follow. Which comment are you referring to? And what exactly does that comment show?

**Comment by nc6** [comment]
@peti This was tested before the PR was opened. I can replicate your example quite happily on my branch:

```
[nc@varda:~/nixpkgs.hask-split-out]$ nix-shell -p "haskellPackages.ghcWithPackages (ps: [ps.conduit])" -I .

[nix-shell:~/nixpkgs.hask-split-out]$ ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/nc/.ghc/ghci.conf
λ> import Data.Conduit
(0.02 secs, 0 bytes)
```

That it's broken on master is annoying, but it's not due to this being untested.

**Comment by peti** [comment]
@nc6, are you sure that you're actually building the branch you intend to build? I.e. does the `-I .` flag really achieve what it's intended to? It looks to me like you mean to use `-I nixpkgs=$PWD`, but obviously I cannot know for sure. All I can say is that this very example fails when I run it on my machine,

**Comment by globin** [comment]
Can confirm this works on master:
```
$ git show           
commit 9f90700b564f35caa4ca28aa8d56cfffd4d1ae6f (HEAD -> up, upstream/master)
Merge: fd7953d95f4 62e6f2eb1dc
Author: Jörg Thalheim <Mic92@users.noreply.github.com>
Date:   Tue Dec 5 10:47:55 2017 +0000

    Merge pull request #32336 from Mic92/vim-codefmt
    
    vim-codefmt: init at 2017-03-04

 $ NIX_PATH=nixpkgs=. nix-shell -p "haskellPackages.ghcWithPackages (ps: [ps.conduit])"             

[nix-shell:~/dev/nixpkgs-upstream]$ ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude> import Data.Conduit
Prelude Data.Conduit> 
```

**Comment by peti** [comment]
@globin, can you please try a revision prior to my revert, i.e. e5e32822df935484f9baff019f692a0c6812f1c4?

**Comment by vcunat** [comment]
Right, `-I .` won't work as expected, at least unless you add a symlink `nixpkgs -> .`

**Comment by globin** [comment]
Ah sry didn't notice your revert, fails with:
```
There are problems in package conduit-1.2.12.1:
  dependency "exceptions-0.8.3-ADEDRATtUrMK1JW4zMQ9U" doesn't exist
  dependency "lifted-base-0.2.3.11-Ei0JSPdt7KOCD2HIA5jFqV" doesn't exist
  dependency "mmorph-1.0.9-5bASEvmIkr5CpdAYXwPsn0" doesn't exist
  dependency "monad-control-1.0.2.2-1Ci8dYJ8Tb7E3HTcTqOb8l" doesn't exist
  dependency "mtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6" doesn't exist
  dependency "primitive-0.6.2.0-4578caNkWQ54Gt1mxLF2Yh" doesn't exist
  dependency "resourcet-1.1.9-L2BUQrxWZMwDiwhcuyPuNi" doesn't exist
  dependency "transformers-base-0.4.4-GKSs0LKukAL8ymq2naFmrH" doesn't exist
  dependency "transformers-compat-0.5.1.4-IuFogs8HAVUJBWVNMhtssu" doesn't exist

The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.
conduit-1.2.12.1
builder for '/nix/store/vc9453svk0na3w237x6zvbsia0qph9j0-ghc-8.0.2-with-packages.drv' failed with exit code 1
```

**Comment by nc6** [comment]
Oh, darn. Yeah, if I try with `-I nixpkgs=$PWD`, I see the same :-(

**Comment by domenkozar** [comment]
@nc6 I'll give this another try

**Comment by domenkozar** [comment]
I have found the issue, `symlinkJoin` doesn't handle multiple outputs at all. This is a bit deeper rabbit hole than I thought, will give it a few more days.

**Comment by domenkozar** [comment]
Fixed! Only darwin left: https://github.com/NixOS/nixpkgs/issues/32082#issuecomment-350541007

**Pull request merged**
