### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

~With cross-compilation of Python extension modules.~

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
I think the sysconfigdata changes are breaking python37Packages.bootstrapped-pip - hydra log:
```
  File "/nix/store/i8sy0wp598x46ny7jp26ga45sn0nrmf9-python3-3.7.9/lib/python3.7/sysconfig.py", line 422, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'
```

**Comment by FRidh** [comment]
Sigh. This was the issue spidermonkey_78 had before my fix. That got fixed by using a symlink, and now this one complains with a symlink. OK, next patch, a copy instead.

**Comment by FRidh** [comment]
Reverted the Python cross commit again in 0a12b8a5e9f31ab1f56f55df93af24b46dd0b30f.

**Comment by FRidh** [comment]
Python namespace hook is causing trouble @jonringer 
```
Enforcing PEP420 namespace: azure.keyvault
/nix/store/szhb6132xmkq3q3bn9zv0fynmcfykjml-findutils-4.7.0/bin/find: ‘/nix/store/0v1llc4mv94qsvixjfasiavkk63hk5zk-python3.7-azure-keyvault-certificates-4.2.1/lib/python3.7/site-packages/azure/__pycache__/’: No such file or directory
rm: missing operand
```

**Comment by jonringer** [comment]
Ah, I originally, had a `if [ -d "$pycachePath"]; then` in there, guess I forgot to add is back when changing the find call

**Comment by jonringer** [comment]
fixed:
```
$ nix-build -E 'with import ./. { config = {}; overlays = []; }; python3.withPackages (ps: with ps; [ jaraco_functools jaraco_collections])'
these derivations will be built:
  /nix/store/f86c3fslhirg7l5wfpxszhmm5crcg86y-python3-3.8.6-env.drv
building '/nix/store/f86c3fslhirg7l5wfpxszhmm5crcg86y-python3-3.8.6-env.drv'...
created 234 symlinks in user environment
/nix/store/vpivpif8aapvr5fmaivi8m1akaam7brj-python3-3.8.6-env
[13:49:35] jon@nixos ~/projects/nixpkgs (staging-next)
$ nix-build -A azure-cli
/nix/store/qm8fsm79x5cycqs702gjch2w20r9fzik-python3.7-azure-cli-2.14.2
```
building ceph now, but it should work... takes while since ceph have ~2000 build dependencies
```
$ nix-store -q --requisites $(nix-instantiate -A ceph) | grep drv | wc -l
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
1987
```

**Pull request merged**
