### PR TITLE
lib/types: Fix coercedTo check

### PR DESCRIPTION
**Pull request by infinisil**
Without this change

```nix
(coercedTo str toInt int).check "foo"
```

would evaluate to true, even though

```nix
(coercedTo str toInt int).merge {} [{ value = "foo"; }]
```

will throw an error because "foo" can't be coerced to an int.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
So this adds both the check that `coerceFunc` succeeds, along with the `finalType` check on its result.

**Comment by Infinisil** [comment]
Ping @rycee and @Profpatsch

**Comment by Profpatsch** [comment]
Can you add a succeeding/failing test pair to `lib/tests/modules.sh`?

**Comment by Infinisil** [comment]
@Profpatsch I added some tests. One thing I'm not sure about is whether this assert: https://github.com/NixOS/nixpkgs/blob/db5f8fa096af618b39c06f5c37a4031a3eaae59e/lib/types.nix#L430 is still needed, because now the check gets performed in `check` already, so it shouldn't even get to that point with an invalid type.

**Comment by Infinisil** [comment]
@Profpatsch Pretty sure that's not possible because the value to check occurs in the function argument to those two attributes, and the attributes can in theory be used separately anyways.

A question: I changed the name of `coercedTo` types slightly in the latest commit:
```nix
types.coercedTo str toInt int # "int or string convertible to it"
```

because it makes more sense instead of `"int or string"`. What do you think of this naming? Maybe `"int or string convertible to one"` would be better or even `"int or string convertible to int"`, which would get out of control with bigger type names.

**Comment by Profpatsch** [comment]
I like the improved documentation.
But I’d really like @nbp to give his opinion on the doubling of the coerce function. We don’t use `coercedTo` a lot in nixpkgs, so maybe the overhead is not bad enough for it to be a blocker.

**Review by nbp — APPROVED** [review]
Sorry for the delay.

* I prefer the new wording as it explicit the manipulated type. (maybe preferred?)
* Thanks for adding tests
* I do not think the overhead would be a big deal at the moment, and if it is, then this can probably be separated in multiple options.

[blind-review](https://github.com/zombie/blind-reviews "Review performed in blind mode")

**Comment by Profpatsch** [comment]
Nice, thanks! I will merge then.

**Pull request merged**
