### PR TITLE
ondsel: init at 2024.2.2

### PR DESCRIPTION
**Pull request by ein-shved**
## Description of changes

[Ondsel](https://ondsel.com/) is commercial fork of general purpose Open Source
    3D CAD/MCAD/CAx/CAE/PLM modeler FreeCAD

This is fork of patch #292995

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ein-shved** [comment]
Steel in progress. Need to install plugins and not sure about maintainers list...

**Comment by Naxdy** [comment]
With the stable release of FreeCAD 1.0 imminent, I'm wondering if it's even worthwhile to package Ondsel ES separately, given that all they really do is package some addons on top of vanilla FreeCAD, as they are very involved in upstreaming their own changes back to FreeCAD. :thinking:

**Comment by ein-shved** [comment]
> If you just install these addons via the built-in addon manager

Addons managers is not Nix-way, I will see for a way to install addons via nix configuration and maybe switch to module implementation instead of building modified FreeCad from scratch. Thank you!

**Comment by ein-shved** [comment]
I opened another WIP PR #347776 which introduces customization of freecad. @Naxdy, FYI.

**Comment by maxammann** [comment]
> given that all they really do is package some addons on top of vanilla FreeCAD, as they are very involved in upstreaming their own changes back to FreeCAD. 🤔

Which addons do you refer to specifically?

**Comment by ein-shved** [comment]
Closing this because of [goodbye](https://ondsel.com/blog/goodbye/)

**Pull request closed without merging**
