### PR TITLE
[Backport release-24.05] zfs: 2.2.5 -> 2.2.6

### PR DESCRIPTION
**Pull request by amarshall**
## Description of changes

I’m on the fence about backporting the changes to `latestCompatibleLinuxPackages`—it does make backporting and maintenance a lot easier. It should also ease backports for Kernel updates and removals as it decouples the ZFS drv from them somewhat. My hesitation is simply that it is a more “substantial” change.

Leaving this draft for a bit for discussion re above and also to let 2.2.6 sit on unstable for a bit before backporting.

## Things done

```
$ nix-instantiate --eval -A zfs_2_1.passthru.latestCompatibleLinuxPackages.kernel.name
"linux-6.6.50"

$ nix-instantiate --eval -A zfs_2_2.passthru.latestCompatibleLinuxPackages.kernel.name
"linux-6.10.9"

$ nix-instantiate --eval -A zfs_unstable.passthru.latestCompatibleLinuxPackages.kernel.name
"linux-6.10.9"
```

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by adamcstephens — APPROVED** [review]

**Comment by adamcstephens** [comment]
I’m comfortable moving forward whenever you are.

**Comment by tomgray** [comment]
I built `release-24.05` from commit `c5672ec7cbac38685781356e7c24595028c810b2` and I received a libre kernel. This is unexpected? Presumably most users would want a non-libre kernel so that they can load binary firmwares for wifi cards, motherboard chipset, etc.

Repro:

```
-bash-3.2$ git checkout c5672ec7cbac38685781356e7c24595028c810b2
Note: switching to 'c5672ec7cbac38685781356e7c24595028c810b2'.

<snip>

HEAD is now at c5672ec7cbac [Backport release-24.05] double-conversion: Allow static linking (#341273)
-bash-3.2$ nix repl
Welcome to Nix 2.18.2. Type :? for help.

nix-repl> :lf .
Added 17 variables.

nix-repl> legacyPackages.x86_64-linux.zfs.latestCompatibleLinuxPackages.kernel.version
"6.10.9"

nix-repl> legacyPackages.x86_64-linux.zfs.latestCompatibleLinuxPackages.kernel.isLibre
true
```

**Comment by tomgray** [comment]
> Additionally, I would generally recommend against using latestCompatibleLinuxPackages at all—your Kernel can (and will) go backwards at times.

This is good advice; recent wifi chipsets seem to be quite dependent on having a newer kernel version, and the recent downgrade to 6.6 on `nixos-24.05` for ZFS resulting from the deprecation of 6.8 and 6.9 broke my wifi card until I replaced my use of `latestCompatibleLinuxPackages`.

**Comment by Atemu** [comment]
`latestCompatibleLinuxPackages` needs to go but in the mean time we must unbreak stable: https://github.com/NixOS/nixpkgs/issues/341867

I'm going to revert the commit.

**Comment by Atemu** [comment]
You prefaced this with being on the fence about but next time, please don't backport such changes. They're bound to run into issues like this and it's better to just eat the minor maintenance overhead for the next few months (isn't that like 2 PRs max anyways?).

We really should not break stable like this.

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/pull/342495

**Pull request merged**
