### PR TITLE
[staging] rustPlatform.cargoCheckHook: respect cargoCheckType

### PR DESCRIPTION
**Pull request by figsoda**
###### Motivation for this change

`checkType` and `cargoCheckType` are not respected in `rustPlatform.buildRustPackage`

nym should be the only package that is effected since `cargoCheckType` defaults to `cargoBuildType` and it is the only package that sets `checkType`

There could be a drawback where `cargoCheckHook` is used outside of `buildRustPackage` and `cargoBuildType` is set to `"debug"` and `cargroCheckType` isn't, but this niche use case doesn't currently exist in nixpkgs afaik, quick github search didn't give me any usage either

Related: #115008, #114455

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
@ofborg build rustc cargo nym

**Comment by SuperSandro2000** [comment]
This probably needs a documentation update.

**Comment by figsoda** [comment]
this is a bug fix and the current documentation is correct, i don't think it is significant enough (the fact that only one package is using the feature) to have a documentation update

**Comment by figsoda** [comment]
not sure what is calling the darwin build to fail

**Comment by SuperSandro2000** [comment]
darwin is broken on staging. Nothing to worry about for you.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
