### PR TITLE
python3.pkgs.scipy: Set HOME to a writeable directory

### PR DESCRIPTION
**Pull request by doronbehar**
May fix darwin build.

## Description of changes

See comment at https://github.com/NixOS/nixpkgs/pull/239969#issuecomment-1656989346

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
@ofborg build python3.pkgs.scipy

**Comment by doronbehar** [comment]
@ofborg build python3.pkgs.scipy

**Comment by mweinelt** [comment]
Not sure why you think the first commit is required. The second one should target staging-next, where the issues currently appears.

**Comment by mweinelt** [comment]
```
xsimd-x86_64-darwin> building '/nix/store/x812djr6gwaz3ylpqzv7c8vlhlfifvxp-xsimd-11.1.0.drv'
xsimd-x86_64-darwin> unpacking sources
xsimd-x86_64-darwin> unpacking source archive /nix/store/zzh955ls6ycs8rwj3w50dq8k3vyjc8g0-source
xsimd-x86_64-darwin> source root is source
xsimd-x86_64-darwin> patching sources
xsimd-x86_64-darwin> substituteStream(): WARNING: pattern '${prefix}/@CMAKE_INSTALL_LIBDIR@' doesn't match anything in file 'xsimd.pc.in'
xsimd-x86_64-darwin> configuring
xsimd-x86_64-darwin> fixing cmake files...
xsimd-x86_64-darwin> cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LOCALEDIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/share/doc/xsimd -DCMAKE_INSTALL_INFODIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/include -DCMAKE_INSTALL_SBINDIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/wnj5203979qy5i69zr9jznc6mncybpap-cctools-binutils-darwin-11.1.0-973.0.1/bin/strip -DCMAKE_RANLIB=/nix/store/21apr3mbmghnkd6zy2axxli2s36js3n8-clang-wrapper-11.1.0/bin/ranlib -DCMAKE_AR=/nix/store/21apr3mbmghnkd6zy2axxli2s36js3n8-clang-wrapper-11.1.0/bin/ar -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/nix/store/9yq562snidbjpgd4j3gnx1ikps4asm96-xsimd-11.1.0 -DBUILD_TESTS=ON 
xsimd-x86_64-darwin> -- The C compiler identification is Clang 11.1.0
xsimd-x86_64-darwin> -- The CXX compiler identification is Clang 11.1.0
xsimd-x86_64-darwin> -- Detecting C compiler ABI info
xsimd-x86_64-darwin> -- Detecting C compiler ABI info - done
xsimd-x86_64-darwin> -- Check for working C compiler: /nix/store/21apr3mbmghnkd6zy2axxli2s36js3n8-clang-wrapper-11.1.0/bin/clang - skipped
xsimd-x86_64-darwin> -- Detecting C compile features
xsimd-x86_64-darwin> -- Detecting C compile features - done
xsimd-x86_64-darwin> -- Detecting CXX compiler ABI info
xsimd-x86_64-darwin> -- Detecting CXX compiler ABI info - done
xsimd-x86_64-darwin> -- Check for working CXX compiler: /nix/store/21apr3mbmghnkd6zy2axxli2s36js3n8-clang-wrapper-11.1.0/bin/clang++ - skipped
xsimd-x86_64-darwin> -- Detecting CXX compile features
xsimd-x86_64-darwin> -- Detecting CXX compile features - done
xsimd-x86_64-darwin> -- xsimd v11.0.1
xsimd-x86_64-darwin> -- Tests build type is Release
xsimd-x86_64-darwin> -- Performing Test HAS_CPP11_FLAG
xsimd-x86_64-darwin> -- Performing Test HAS_CPP11_FLAG - Success
xsimd-x86_64-darwin> CMake Error at test/CMakeLists.txt:187 (message):
xsimd-x86_64-darwin>   
xsimd-x86_64-darwin> 
xsimd-x86_64-darwin>       Cannot find required doctest component.
xsimd-x86_64-darwin>       Please either set CMAKE_PREFIX_PATH to the location of doctestConfig.cmake,
xsimd-x86_64-darwin>       or set DOWNLOAD_DOCTEST=ON
xsimd-x86_64-darwin> 
xsimd-x86_64-darwin> 
xsimd-x86_64-darwin> -- Configuring incomplete, errors occurred!
error: build of '/nix/store/x812djr6gwaz3ylpqzv7c8vlhlfifvxp-xsimd-11.1.0.drv' on 'ssh-ng://hexa@darwin-build-box.winter.cafe' failed: builder for '/nix/store/x812djr6gwaz3ylpqzv7c8vlhlfifvxp-xsimd-11.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > -- Performing Test HAS_CPP11_FLAG - Success
       > CMake Error at test/CMakeLists.txt:187 (message):
       >
       >
       >       Cannot find required doctest component.
       >       Please either set CMAKE_PREFIX_PATH to the location of doctestConfig.cmake,
       >       or set DOWNLOAD_DOCTEST=ON
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/x812djr6gwaz3ylpqzv7c8vlhlfifvxp-xsimd-11.1.0.drv'.
error: builder for '/nix/store/x812djr6gwaz3ylpqzv7c8vlhlfifvxp-xsimd-11.1.0.drv' failed with exit code 1

**Comment by doronbehar** [comment]
> Not sure why you think the first commit is required.

Because of [this build log](https://hydra.nixos.org/log/7bip658158274pr1flx7aq24q9m8hr76-python3.10-scipy-1.11.1.drv) (already linked in https://github.com/NixOS/nixpkgs/pull/239969#issuecomment-1657132110)) from [this build](https://hydra.nixos.org/build/229863854), from [this evaluation](https://hydra.nixos.org/eval/1797964?filter=scipy&compare=1797817&full=#tabs-now-fail).

**Comment by vcunat** [comment]
The second commit does not suffice to fix the build for me.  Either way, we need fixes for scipy on `staging-next` branch already.

**Comment by doronbehar** [comment]
> The second commit does not suffice to fix the build for me. Either way, we need fixes for scipy on `staging-next` branch already. EDIT: it's also easier to test based on there, as binaries are available.

Yes I know, thanks for the help. I guess I'll close this now, as all of the efforts are in https://github.com/NixOS/nixpkgs/pull/246200 .

**Pull request closed without merging**
