### PR TITLE
picard: pkgs/by-name migration

### PR DESCRIPTION
**Pull request by superherointj**
picard:
- pkgs/by-name migration
- nixfmt format
- order arguments by alphabetical order

CC @doronbehar

### CODE REVIEW

**Comment by Sigmanificient** [comment]
Hi, Is there any reason to reorder the argument to follow alphabetical order? It seems a bit weird to me, as I believe the previous order makes more sense (the elements follow the order they are used in the derivation)

**Comment by superherointj** [comment]
> Hi, Is there any reason to reorder the argument to follow alphabetical order? It seems a bit weird to me, as I believe the previous order makes more sense (the elements follow the order they are used in the derivation)

Alphabetical order is objective.
Alphabetical order can be easily integrated to `nixfmt` but some other arbitrary logic won't be possible.
Some other order is (more) subjective and there is disagreement on it.
We have to agree on something. It is easier to agree on alphabetical order than on some other subjective order. And everyone already knows alphabetical order. No indoctrination is necessary. Everyone easily gets it right and from the start.

**Comment by superherointj** [comment]
> It seems a bit weird to me, as I believe the previous order makes more sense (the elements follow the order they are used in the derivation)

That order seems weird to me. See the problem? That isn't order. Also, the order won't matter. We only need to not have duplicated arguments in the attrs. And for avoiding that, alphabetical order is best. Any argument in the attrs can be overriden, so there isn't an order to that.

The exception to this, would be phases order, which has hooks being executed in sequence, which causes errors to show up in sequence.

I can remove the alphabetical re-ordering if you wish.

**Comment by Sigmanificient** [comment]
No, I'm just curious about it, as this is the first time I encounter this. Is there any discourse post applying this?

You are right that it would be easier to apply as an automated rule of `nixfmt`, although I am not a particularly fan of the idea that it should be forced.

One of the main point that makes me appreciate the previous ordering, is that it keep things that are related into groups, unlike the alphabetical one. (For instance, a python package with many dependencies should seen them as one "block" of argument which is itself alphabetically sort, rather than being scattered around.

**Comment by superherointj** [comment]
> although I am not a particularly fan of the idea that it should be forced.

That's precisely the win of `nixfmt`, to avoid unnecessary arguments. It should be forced, the matter is just what. I find alphabetical order the most objective order you can find for the arguments. Some other logical is hard to convey to people. I'd rather not have to debate/explain these things. I can tell my 5yo son alphabetical order and he gets it right, see? Try to explain to him the logic you wanted to use? I'm sure it's harder... And also, not really best. (Even though it might make sense for you, even though it doesn't make that much sense for me.)

> One of the main point that makes me appreciate the previous ordering, is that it keep things that are related into groups, unlike the alphabetical one. (For instance, a python package with many dependencies would seen them as one "block" of argument which is itself alphabetically sort, rather than being scattered around).

That's subjective. I don't see the order you see, the attrs is flat, any argument can be overridden.

> In any case, I believe the final say should be to the package maintainer (unless this becomes official)

I have removed the proposed solution. Though I think that's the most optimal solution we can have.

**Review by doronbehar — COMMENTED** [review]
TBH I too slightly dislike the new formatting, and I avoid it as much as possible, but the truth is that I don't have a choice as the RFC process dictated that this formatting is the consensus :cry: . Unless you are willing to become a maintainer, I tend to disapprove this change, sorry.

**Comment by superherointj** [comment]
> TBH I too slightly dislike the new formatting, and I avoid it as much as possible, but the truth is that I don't have a choice as the RFC process dictated that this formatting is the consensus 😢 . Unless you are willing to become a maintainer, I tend to disapprove this change, sorry.

I have already dropped the change.

**Comment by superherointj** [comment]
Do you want to stall the `nixfmt` format?

**Comment by doronbehar** [comment]
> I have already dropped the change.

Which change?

**Comment by superherointj** [comment]
> > I have already dropped the change.
> 
> Which change?

Alphabetical ordering of arguments.

**Comment by doronbehar** [comment]
> Do you want to stall the `nixfmt` format?

I want to avoid it for some packages I maintain, because I'm hopeful that the format and the implementation may change in the future. Other dissatisfaction are mentioned here: https://discourse.nixos.org/t/satisfaction-survey-from-the-new-rfc-166-formatting/49758

**Comment by doronbehar** [comment]
> > > I have already dropped the change.
> > 
> > 
> > Which change?
> 
> Alphabetical ordering of arguments.

I noticed that, but I thought you wanted to become a maintainer for this package. This can be done with / without a migration to nixfmt and pkgs/by-name.

**Comment by superherointj** [comment]
Since the proposed changes were not appreciated, I have already closed the PR. The issue is settled.
I did not mean to become a maintainer. I was going to review the PR, which I did (and merged).

**Comment by doronbehar** [comment]
So what did you mean by "Permission to come aboard!"?

**Comment by superherointj** [comment]
> So what did you mean by "Permission to come aboard!"?

From Star Trek, Captain Picard would say: `Granted/Denied`
But yes, the meaning you took from it could be valid too. I just didn't have that in mind exactly.
I only went on to review the PR because of the name. ;-)

**Comment by doronbehar** [comment]
Haha there is no way I could have figured that meaning spontaneously :) In general I'd avoid using jokes based on cultural knowledge in a diverse space such as Nixpkgs.

**Pull request closed without merging**
