### PR TITLE
Update gambit and gerbil from upstream

### PR DESCRIPTION
**Pull request by fare**
###### Motivation for this change

New upstream releases.
A few packaging improvements (download less for gambit, statically link gambit path into gerbil).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fare** [comment]
(Weird that github sorts the commits by inception date and not by order in the history, which is different due to rebases)

**Comment by fare** [comment]
@thoughtpolice @7c6f434c

**Comment by grahamc** [comment]
Weird that only fare is listed as a maintainer in https://gist.github.com/GrahamcOfBorg/5eca118b37e498583e34a08c76c7be59 ... hmm...

**Review by 7c6f434c — APPROVED** [review]

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build gerbil gambit gerbil-unstable gambit-unstable

@grahamc nothing too strange: the gerbil file (where there is a single maintainer) got changed, the gambit package definition didn't really — only the source-tarball definition files did. This is probably similar enough to `all-packages.nix` situation for ofborg not to mention me.

**Pull request merged**
