### PR TITLE
mqttx: init at 1.9.8

### LINKED ISSUE #242396: Package request: MQTTx
**Project description**
A powerful, all-in-one MQTT 5.0 client toolbox for desktop, CLI and WebSocket, it makes developing and testing MQTT applications faster and easier.

**Metadata**

* homepage URL: https://mqttx.app/
* source URL: https://github.com/emqx/MQTTX
* license: mit, bsd, gpl2+ , Apache License 2
* platforms: unix, linux, darwin

### PR DESCRIPTION
**Pull request by gaelreyrol**
###### Description of changes

This PR adds the package MQTTX as an AppImage: https://github.com/emqx/MQTTX

Closes https://github.com/NixOS/nixpkgs/issues/242396

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by onemoresuza — CHANGES_REQUESTED** [review]
There's a new naming convention for packages, which can be found [here](https://github.com/NixOS/nixpkgs/blob/cd3c88ad04b4fc98112dee77aa6eb356aa8419a5/pkgs/by-name/README.md).

Could you move the `default.nix` to the correspondingly `package.nix` location? Doing that, there's no need for the `all-packages.nix` addition, so you can remove it.

**Comment by gaelreyrol** [comment]
@onemoresuza Done!

**Comment by onemoresuza** [comment]
Result of `nixpkgs-review pr 243622` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mqttx</li>
  </ul>
</details>

**Review by onemoresuza — APPROVED** [review]

**Review by onemoresuza — APPROVED** [review]

**Comment by mausch** [comment]
Works great on x86_64-linux , thanks!
hash for the aarch64 source is different though https://github.com/NixOS/nixpkgs/pull/243622/checks?check_run_id=19461475158
so please either fix that or disable aarch64-linux, hopefully someone will merge after that.

**Comment by gaelreyrol** [comment]
> Works great on x86_64-linux , thanks! hash for the aarch64 source is different though https://github.com/NixOS/nixpkgs/pull/243622/checks?check_run_id=19461475158 so please either fix that or disable aarch64-linux, hopefully someone will merge after that.

Done!

**Review by pbsds — APPROVED** [review]
Result of `nixpkgs-review pr 243622` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mqttx</li>
  </ul>
</details>


- [x] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package builds on x86_64-linux
- [x] executables tested on x86_64-linux
- [x] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [x] `meta.platforms` is set
- [x] `meta.maintainers` is set
- [x] build time only dependencies are declared in `nativeBuildInputs`
- [x] source is fetched using the appropriate function
- [x] the list of `phases` is not overridden
- [x] when a phase (like `installPhase`) is overridden it starts with `runHook preInstall` and ends with `runHook postInstall`.
- [x] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [x] patches that are remotely available are fetched rather than vendored

Runs fine and LGTM

**Pull request merged**
