### PR TITLE
nordic: complement buildInputs

### PR DESCRIPTION
**Pull request by Cryolitia**
## Description of changes

Complement buildInputs, which are essential for nordic, otherwise fault on sddm: 

- plasma-framework

- qtgraphicaleffects

- plasma-workspace

- breeze-icons

image

CC maintainer: @romildo

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Cryolitia** [comment]
1 package built:
nordic

Result of `nixpkgs-review pr 261742` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nordic</li>
  </ul>
</details>

**Comment by romildo** [comment]
It is a lot of new dependencies just for sddm. I suggest to make the installation of sddm optional. What do you think, @Cryolitia ?

**Comment by romildo** [comment]
> It is a lot of new dependencies just for sddm. I suggest to make the installation of sddm optional. What do you think, @Cryolitia ?

We can consider this idea later. Merging as-is for now.

**Review by romildo — APPROVED** [review]

**Comment by Cryolitia** [comment]
> It is a lot of new dependencies just for sddm. I suggest to make the installation of sddm optional. What do you think, @Cryolitia ?

Thanks for your time firstly. 

I absolutely support it. I have noticed that you had done a lot of work after this PR. Is it already solved?

I noticed that you used `propagatedUserEnvPkgs` instead of `buildInputs` in https://github.com/NixOS/nixpkgs/pull/262552/files#diff-cbca472085afa11e13fe20c7ecd21fd62798afa6f1e11a44f34636150b0a9fc4R85 . But I have trouble to understand and could found little description about `propagatedUserEnvPkgs`, could you please explain it to me if you have time, I would appriciate it with honor.

**Comment by romildo** [comment]
> I absolutely support it. I have noticed that you had done a lot of work after this PR. Is it already solved?

Yes, it is solved. But I am going to make another PR for a separate output for the sddm theme.

> I noticed that you used `propagatedUserEnvPkgs` instead of `buildInputs` in https://github.com/NixOS/nixpkgs/pull/262552/files#diff-cbca472085afa11e13fe20c7ecd21fd62798afa6f1e11a44f34636150b0a9fc4R85 . But I have trouble to understand and could found little description about `propagatedUserEnvPkgs`, could you please explain it to me if you have time, I would appriciate it with honor.

In fact it is not well documented. I think because there is an attempt to deprecate it. See https://github.com/NixOS/nixpkgs/issues/43049.

It includes the listed packages in the environment. For binaries it is usually better to build wrappers that indicates where the dependencies can be found. But for other cases, like themes, that does not work.

Later on if I find a good explanation I tell you.

**Comment by romildo** [comment]
@Cryolitia maybe you want to review https://github.com/NixOS/nixpkgs/pull/263855.

**Pull request merged**
