### PR TITLE
rust: bump registry and racerd

### LINKED ISSUE #17942: racerd fails on unstable
## Issue description

`racerd` fails to compile on unstable.

### Steps to reproduce

`nixos-rebuild build` on 16.09.git.52a875f (Flounder)

## Technical details

* System: 16.09.git.52a875f (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre88945.5120af0"

---

trace:

```
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/m88cskz21fcjlk93h2z3wppqa15csp2f-racerd-0.1.1.drv
  /nix/store/gp3vhwlb5f9jswvjr9fmdmgr2h354rsr-vimplugin-youcompleteme-2016-07-23.drv
  /nix/store/rmhfy6h58wmmkxrxbl3ad5m8f5gjfgx8-vimrc.drv
  /nix/store/jn0xcwifj4rg922vaap73hkznx83aihs-vim.drv
  /nix/store/vmiqwkqg7grvhm4z1m7zs837ywzyrh18-neovim-0.1.4-configured.drv
  /nix/store/cwmvdpfy5zzmsf51wapcvv538x3zwq18-system-path.drv
  /nix/store/f64nl2v750dhv5vmpsf46hw6pr2mfqbb-dbus-conf.drv
  /nix/store/cs3qj1cnf4myx4dz1xqhmxpsd27fk5jc-unit-dbus.service.drv
  /nix/store/d3fwxcvvyvcr9al71dfirhx4wi13sn90-unit-polkit.service.drv
  /nix/store/i04sj89zkqmly59hc3ih4c434b7wr8bx-system-units.drv
  /nix/store/jvmvbqicbbnnidv7rl97pk87hvjpa5qd-etc.drv
  /nix/store/klj1sdidc71j062mn6igmbijrmv30gb6-nixos-system-yuu-16.09pre88945.5120af0.drv
building path(s) ‘/nix/store/hmdwmd69imi89xmp0yq6bfrag93jlzkl-racerd-0.1.1’
unpacking sources
unpacking source archive /nix/store/d48wmmblw7xh7kilgazd8lf8kc6fzj75-racerd-dcbb788
source root is racerd-dcbb788
Using cargo deps from /nix/store/0xs0yf0fl11das189fkafsw7gc8yaxqk-racerd-0.1.1-fetch
Using indexHash '-ba82b75dd6681d6f'
Using rust registry from /nix/store/kqq2zab0k1kq8pmbi5nf0wnkg1qldnj8-rustRegistry-2016-08-10-fe018be
warning: custom registry support via the `registry.index` configuration is being removed, this functionality will not work in the future
warning: TOML file found which contains invalid syntax and will soon not parse
at `/tmp/nix-build-racerd-0.1.1.drv-0/deps/registry/src/-ba82b75dd6681d6f/url-0.5.9/Cargo.toml`.

The TOML spec requires newlines after table definitions (e.g. `[a] b = 1` is
invalid), but this file has a table header which does not have a newline after
it. A newline needs to be added and this warning will soon become a hard error
in the future.
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/tmp/nix-build-racerd-0.1.1.drv-0/deps/registry/src/-ba82b75dd6681d6f/iron-0.3.0/Cargo.toml`

To learn more, run the command again with --verbose.
builder for ‘/nix/store/m88cskz21fcjlk93h2z3wppqa15csp2f-racerd-0.1.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/gp3vhwlb5f9jswvjr9fmdmgr2h354rsr-vimplugin-youcompleteme-2016-07-23.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/rmhfy6h58wmmkxrxbl3ad5m8f5gjfgx8-vimrc.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/vmiqwkqg7grvhm4z1m7zs837ywzyrh18-neovim-0.1.4-configured.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/jn0xcwifj4rg922vaap73hkznx83aihs-vim.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/cwmvdpfy5zzmsf51wapcvv538x3zwq18-system-path.drv’: 2 dependencies couldn't be built
cannot build derivation ‘/nix/store/f64nl2v750dhv5vmpsf46hw6pr2mfqbb-dbus-conf.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/d3fwxcvvyvcr9al71dfirhx4wi13sn90-unit-polkit.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/cs3qj1cnf4myx4dz1xqhmxpsd27fk5jc-unit-dbus.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/i04sj89zkqmly59hc3ih4c434b7wr8bx-system-units.drv’: 2 dependencies couldn't be built
cannot build derivation ‘/nix/store/jvmvbqicbbnnidv7rl97pk87hvjpa5qd-etc.drv’: 2 dependencies couldn't be built
cannot build derivation ‘/nix/store/klj1sdidc71j062mn6igmbijrmv30gb6-nixos-system-yuu-16.09pre88945.5120af0.drv’: 2 dependencies couldn't be built
error: build of ‘/nix/store/klj1sdidc71j062mn6igmbijrmv30gb6-nixos-system-yuu-16.09pre88945.5120af0.drv’ failed
```

### PR DESCRIPTION
**Pull request by steveej**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Should fix #17942.

### CODE REVIEW

**Comment by the-kenny** [comment]
@steveeJ I had to fix `exa`s `sha256` too. Trying now and will merge this (with the fix) in a few minutes.

**Comment by the-kenny** [comment]
@steveeJ Sorry, `exa` still fails, even with a fixed hash. Seems like it's impure. Could you remove that commit from this PR? I think we should fix this in a separate PR.

**Comment by globin** [comment]
Regarding exa, their Cargo.toml contains the following which probably causes the impurity:
```
[dependencies.zoneinfo_compiled]
git = "https://github.com/rust-datetime/zoneinfo-compiled.git"
```

**Comment by the-kenny** [comment]
Likely. We should open an upstream issue for this and/or fix this via "magic paths" mentioned in 17670

**Comment by the-kenny** [comment]
I'm merging this anyway as it's a separate issue and racerd/registry are worth updating.

**Pull request merged**
