### PR TITLE
lightspark: ffmpeg_3 -> ffmpeg

### PR DESCRIPTION
**Pull request by jchv**
###### Motivation for this change
#120705

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124330` at e80b1ae9 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>lightspark</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

llvm is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/misc/lightspark/default.nix:23:3:
```
   |
23 |   buildInputs = [
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/misc/lightspark/default.nix:31:5:
```
   |
31 |     license = licenses.lgpl3;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/patch-phase.md">patch-phase</a>

`patchPhase` should not be overridden, use `postPatch` instead.

Near pkgs/misc/lightspark/default.nix:17:3:
```
   |
17 |   patchPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
@jchv Would you mind making the changes suggested by @r-rmcgibbo?

**Comment by jchv** [comment]
@dotlambda 
> @jchv Would you mind making the changes suggested by @r-rmcgibbo?

Not at all! I wasn't sure if it should be done in a separate PR or not.

Quick question, do you know if there's a way to silence the LLVM issue? Lightspark uses LLVM to do JITing, not anything at compile time (that I am aware of.)

**Comment by dotlambda** [comment]
> Quick question, do you know if there's a way to silence the LLVM issue? Lightspark uses LLVM to do JITing, not anything at compile time (that I am aware of.)

I don't think so. Just ignore it.

**Comment by jchv** [comment]
> > Quick question, do you know if there's a way to silence the LLVM issue? Lightspark uses LLVM to do JITing, not anything at compile time (that I am aware of.)
> 
> I don't think so. Just ignore it.

Done, thanks.

**Comment by dotlambda** [comment]
@jchv Will you make a PR for the backport?

**Pull request merged**
