### PR TITLE
home-assistant: 0.118.4 -> 0.118.5

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

New upstream release.

https://github.com/home-assistant/core/releases/tag/0.118.5

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by delroth — APPROVED** [review]
LGTM for pyatmo.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105981` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python39Packages.pyatmo</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python37Packages.pyatmo</li>
    <li>python38Packages.pyatmo</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105981` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python39Packages.pyatmo</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.pyatmo</li>
    <li>python38Packages.pyatmo</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
https://github.com/testing-cabal/fixtures/issues/44

**Pull request merged**
