### PR TITLE
tauon: 7.8.0 -> 7.8.1

### PR DESCRIPTION
**Pull request by huantianad**
## Description of changes
Main change is adding pipewire support.

### To discuss:
 Perhaps we should make discord RPC support not optional, or at least on by default, so users don't have to recompile the C libraries if they want to enable it, and so we match upstream's defaults.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nagisa** [comment]
Is there any way I can help to drive this forward? Tauon currently does not build at all due to `./compile-phazor.sh: cannot execute: required file not found` which this seems like it may fix.

**Comment by jansol** [comment]
Build fixes can be sent to master right away as a separate PR from the other changes. I'd argue that the jxl fix and unused dependencies can be bundled with those as well.

The pipewire backend should wait until there is an upstream release tag. I don't have strong feelings one way or the other regarding discord rpc, but changing that should probably wait for the next release too.

**Comment by huantianad** [comment]
Makes sense, I can definitely split up this PR!

**Comment by jansol** [comment]
[7.8.1](https://github.com/Taiko2k/Tauon/releases/tag/v7.8.1) is now out as a proper release tag that contains the pipewire changes.

**Comment by jansol** [comment]
Personally I don't care for it but I'm not opposed to it either (it's still disabled by default in tauon's settings IIRC)

**Comment by huantianad** [comment]
Yeah makes sense, it is still disabled by default in settings, and I'd say the main benefit of disabling it in the derivation is just a smaller closure size.

**Comment by jansol** [comment]
Does it really make a meaningful difference to closure size? If it doesn't then might as well have it in the build by default.

**Comment by huantianad** [comment]
Yeah I don't think it does, let's turn it on by default then.

**Review by jansol — APPROVED** [review]
Builds, runs & makes funny noises

**Comment by jansol** [comment]
[7.8.2 is out to fix some regression in 7.8.1](https://github.com/Taiko2k/Tauon/releases/tag/v7.8.2)

**Review by jansol — APPROVED** [review]

**Pull request merged**
