### PR TITLE
roc-toolkit: 0.1.5 -> 0.2.1

### PR DESCRIPTION
**Pull request by bgamari**
###### Description of changes

Update `roc-toolkit`, as requested by #208352. This required a patch to workaround https://github.com/roc-streaming/roc-toolkit/issues/503.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bgamari** [comment]
Unfortunately it appears that `pipewire` does not compile with these changes.

Cc @ribosomerocker

**Comment by bgamari** [comment]
Marking as draft due to `pipewire` incompatibility.

**Comment by bgamari** [comment]
It appears that we will be unable to merge this until the next release of `pipewire` (which will presumably include https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1474) is available.

**Comment by ribosomerocker** [comment]
Nice! Thank you very much for your PR. We could merge this PR when the new release comes out, but we could also cherry pick the patch then apply this (an idea someone had on the pipewire matrix room), but I'm not quite sure which solution would be the better one. For me this isn't quite as much of an emergency but it doesn't seem like a new release will happen any time soon.

**Comment by bgamari** [comment]
The patch does seem a tad large to backport. As far as I can tell, `pipewire` releases pretty [regularly](https://gitlab.freedesktop.org/pipewire/pipewire/-/tags) so I think it would be fine just to wait.

**Comment by K900** [comment]
Pipewire 0.3.64 is out, I'll pick this into that branch.

**Comment by ribosomerocker** [comment]
Alright, so that was merged (but into stage-next? I don't really know what that does), maybe now it should work?

**Comment by K900** [comment]
Yes, it should be in unstable by now.

**Pull request closed without merging**
