### PR TITLE
pythonPackages.pytest: 3.0.7 -> 3.1.3

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

This causes so much rebuild I created this PR for staging.

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks @lsix. Not sure whether we can go to pytest 3.1. Last time I tried it I ran into a lot of failing packages because it changed behavior (https://github.com/pytest-dev/pytest/issues/2430).

**Comment by lsix** [comment]
I can build and pass the test suite for `SQLAlchemy` with pytest 3.1.3. Do you have another problematic package you can think of so I can see if it is still problematic (I cannot run nox-review since it triggers too much rebuild for my computer)?

Should this be pushed to `python-wip` to have a clearer view of what gets broken?

**Comment by Mic92** [comment]
Was this issue fixed in pytest `3.2`?

**Comment by lsix** [comment]
As far as I can see, there is no 3.2 release (yet). The issue @FRidh refered to have been fixed in 3.1.1 or so I think.

**Comment by FRidh** [comment]
An open relevant issue is https://github.com/pytest-dev/pytest-xdist/issues/163.

**Comment by FRidh** [comment]
A couple of days ago 3.2.1 was released. Hopefully we start building Python packages again soon (https://github.com/NixOS/nixpkgs/pull/28244) so we can more easily check whether we can do a pytest bump.

**Comment by FRidh** [comment]
Closing because 3.2 is currently the default pytest in Nixpkgs.

**Pull request closed without merging**
