### PR TITLE
kubernetes: 1.12.3 -> 1.13.1

### PR DESCRIPTION
**Pull request by nicknovitski**
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"` (Nox errored out :p)
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
cc @johanot

**Comment by johanot** [comment]
Thanks. Will do some testing later today.

**Comment by johanot** [comment]
Using v1.13 with the nixos/kubernetes module doesn't work, which I kind of expected. I will look into the details of the required module changes soon.

**Comment by srhb** [comment]
OK, let's hold off on merging this till the module is compatible then. :)

**Comment by johanot** [comment]
Sure. And... Let's get 1.13.1, since it got released just now! :)

**Comment by nicknovitski** [comment]
@johant Would it be more helpful to you if I updated this pr to 1.13.1 and kept it open, or just closed it?

**Comment by johanot** [comment]
Turns out the module itself is fine, but the test cases were failing due to an unsupported alpha feature: `BoundServiceAccountTokenVolume`. I can accept that the module doesn't yet support this feature, but I think we should disable alpha features in the tests (see #52365). And then; let's progress with this PR :)  ... @nicknovitski Yes, I think you should update this PR to 1.13.1 and keep it open.

**Comment by nicknovitski** [comment]
@johanot Updated to 1.13.1.

**Comment by johanot** [comment]
@GrahamcOfBorg build kubernetes

**Review by johanot — APPROVED** [review]
LGTM. RBAC and DNS test cases run clean locally when rebased with master.

**Pull request merged**
