### PR TITLE
xmlbird: fix build with python 3.8 

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
ZHF: #97479

Also fix a similar bug in `birdfont` (`xmlbird`'s only reverse-dependency) which would cause build to fail on debian-based non-nixos systems.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
interesting... wonder if there's a way to fix this more broadly for nixos

However, this would also mean that users which are non-nixos linux would also see their distribution as "nix". But I'm not sure if that's a terrible thing, as nix essentially act as a guest OS

**Comment by risicle** [comment]
It had crossed my mind to consider how we could sandbox `uname`. Or if not sandbox, best-effort spoof it. An `LD_PRELOAD` hack would _work_ but I can't imagine how we'd ensure it's applied universally.

Or simply patch our `glibc`'s `uname` implementation to listen out for a `NIX_SPOOF_UNAME` environment variable we set in build-mode.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 98298 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>birdfont</li>    <li>xmlbird</li>  </ul></details>

**Comment by jonringer** [comment]
I think this is a pretty uncommon scenario. Just patching it like this should be fine.

**Pull request merged**
