### PR TITLE
gnutar: 1.29 -> 1.30

### PR DESCRIPTION
**Pull request by copumpkin**
Unclear when to merge this to staging, because @orivej wants to make sure something else happens first.

Also, I personally would love to get this into 17.09 (https://github.com/NixOS/nixpkgs/pull/32824) but if others think it's not worthwhile, I'll live. @fpletz @globin 

###### Motivation for this change

Gnutar just got a new release that includes a CVE patch that we were applying manually before, and also it fixes the `--numeric-owner` flag to get us deterministic cross-platform behavior.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Announcement: http://lists.gnu.org/archive/html/info-gnu/2017-12/msg00011.html

**Review by vcunat — APPROVED** [review]

**Comment by copumpkin** [comment]
Thanks @vcunat!

**Comment by vcunat** [comment]
I think this regression is related: https://hydra.nixos.org/build/66305655 but ATM I can't at all understand what's happening there.

**Comment by vcunat** [comment]
Oh, I see, it was during a build, not during fetch or something.  Fixed now.

**Comment by copumpkin** [comment]
@vcunat thanks!

**Pull request merged**
