### PR TITLE
stdenv: fix backward multiple outputs conditional

### PR DESCRIPTION
**Pull request by alyssais**
This is supposed to shareDocName to a fallback value if it can't be
determined from looking at the configure script.  But the conditional
checked whether shareDocName was set, rather than if it wasn't.  This
meant that if shareDocName had been detected from a configure script,
it would be immediately overridden by the package name, and if it
couldn't be detected, shareDocName would remain unset.

This resulted in QEMU installing files like $out/share/doc/index.html,
which should of course have been in $out/share/doc/qemu/index.html.

An interesting side effect of this is that, since
9f8751528cd89d343258dd718afa56f8590917bb when this code was added, the
detected package name has never actually been used for installing
documentation, because it would always be overridden.  So this patch
will actually enable that for the first time, four years later.

_We should probably consider, seeing as we’ve been getting by without it for four years, do we want the configure detection at all? I think we probably do, but it’s worth thinking about._

### CODE REVIEW

**Comment by vcunat** [comment]
Oh, fixing this might be affecting many packages and thus break some things due to the move... but I suppose we do want it anyway.

**Comment by jtojnar** [comment]
Should close: https://github.com/NixOS/nixpkgs/issues/90486 and maybe also https://github.com/NixOS/nixpkgs/issues/82304

**Comment by Ericson2314** [comment]
Wow! Yeah let's give this a shot.

**Comment by alyssais** [comment]
I’ve done some additional work now to also fix this for CMake, which implemented its own version of this. One thing I’d like to understand before this is merged is the purpose of a714284, which I’ve essentially reverted here to allow the CMake setup hook to use the same variable as stdenv to disable the output options.

I’m also a bit unsure whether my choice not to set the CMake options for single-output derivations is the right one. This does match what we’ve always done in stdenv, but CMake has set them unconditionally for a long time. So feedback on that would be appreciated.

Finally, I did a search through the codebase for packages that manually did something to share/doc, and fixed any packages I found that looked like they would be affected by this change, hence the last three commits.

**Comment by vcunat** [comment]
I believe some of the passed flags were unrecognized and failing the build.  Perhaps newer cmake fixed that in the meantime.  _At that time it was even happening in some rarer cases where configure scripts were generated upstream by too old autotools, but the question here is about cmake anyway._

**Comment by alyssais** [comment]
Do you remember any packages that were affected at the time that we
could test?

**Comment by vcunat** [comment]
Eh, my bad, the `setOutputFlags` part disables putting flags like `--bindir=/foo/bar` into `configureFlags`... that wouldn't work in cmake anyway, would it?

**Comment by jtojnar** [comment]
> I’ve done some additional work now to also fix this for CMake, which implemented its own version of this. One thing I’d like to understand before this is merged is the purpose of [a714284](https://github.com/NixOS/nixpkgs/commit/a714284d8b7d2dac3ed2c76670f290fe332da00c), which I’ve essentially reverted here to allow the CMake setup hook to use the same variable as stdenv to disable the output options. Perhaps @ttuegel or @vcunat can shed some light on that?

Yeah, I do not understand that either. The `setOutputFlags` only disables setting `configureFlags` and `installFlags` (even [then](https://github.com/NixOS/nixpkgs/blob/a714284d8b7d2dac3ed2c76670f290fe332da00c/pkgs/build-support/setup-hooks/multiple-outputs.sh#L47-L63)). CMake does not use `configureFlags` so the only reason they could be disabling it is to avoid setting `installFlags`. But CMake generates regular `Makefile`s and `make` should not give a darn if `pkgconfigdir`, `m4datadir` or `aclocaldir` is set.

> I’m also a bit unsure whether my choice not to set the CMake options for single-output derivations is the right one. This does match what we’ve always done in stdenv, but CMake has set them unconditionally for a long time. So feedback on that would be appreciated.

I do not see why that would be a problem other than masking broken packages that expect the paths are relative. But some people might consider it a benefit: https://github.com/NixOS/nixpkgs/pull/52859#issuecomment-450256748

> Finally, I did a search through the codebase for packages that manually did something to share/doc, and fixed any packages I found that looked like they would be affected by this change, hence the last three commits.

:+1:

**Comment by alyssais** [comment]
Jan Tojnar <notifications@github.com> writes:

>> I’ve done some additional work now to also fix this for CMake, which
>> implemented its own version of this. One thing I’d like to understand
>> before this is merged is the purpose of
>> [a714284](https://github.com/NixOS/nixpkgs/commit/a714284d8b7d2dac3ed2c76670f290fe332da00c),
>> which I’ve essentially reverted here to allow the CMake setup hook to
>> use the same variable as stdenv to disable the output
>> options. Perhaps @ttuegel or @vcunat can shed some light on that?
>
> Yeah, I do not understand that either. The `setOutputFlags` only
> disables setting `configureFlags` and `installFlags` (even
> [then](https://github.com/NixOS/nixpkgs/blob/a714284d8b7d2dac3ed2c76670f290fe332da00c/pkgs/build-support/setup-hooks/multiple-outputs.sh#L47-L63)). CMake
> does not use `configureFlags` so the only reason they could be
> disabling it is to avoid setting `installFlags`. But CMake generates
> regular `Makefile`s and `make` should not give a darn if
> `pkgconfigdir`, `m4datadir` or `aclocaldir` is set.

Yeah, that's what I was thinking.

>> I’m also a bit unsure whether my choice not to set the CMake options
>> for single-output derivations is the right one. This does match what
>> we’ve always done in stdenv, but CMake has set them unconditionally
>> for a long time. So feedback on that would be appreciated.
>
> I do not see why that would be a problem other than masking broken
> packages that expect the paths are relative. But some people might
> consider it a benefit:
> https://github.com/NixOS/nixpkgs/pull/52859#issuecomment-450256748

Cool, so you think the way I've done it is fine?

It is a shame about libdir still having to be set.  I could not set that
too, and rely on the hook that moves lib64 to lib, but then there'd be
an extra symlink and packages that do things to lib in installPhase
would break, so I decided that was probably best always being set for
CMake.

**Comment by jtojnar** [comment]
> Cool, so you think the way I've done it is fine?

I have a minor preference for keeping it always there because I like it when things break early and less variability is better for predictability but I understand Matthew’s sentiment. Especially when the breakage is not always loud and might be only discovered at runtime or during build of dependent packages. I will defer to you.

> It is a shame about libdir still having to be set. I could not set that too, and rely on the hook that moves lib64 to lib, but then there'd be an extra symlink and packages that do things to lib in installPhase would break, so I decided that was probably best always being set for CMake.

Yeah, I agree that it is always best to let the project know upfront rather than change paths behind its backs. If you wish, you can pass it just `lib` as a relative path when not building multiple outputs. But personally, I would not bother.

**Comment by alyssais** [comment]
Okay, let’s try it out. I wouldn’t be surprised if there are unforeseen consequences that warrant a revert and a refinement to the approach, but I don’t think we’re going to be able to identify those up front.

**Pull request merged**
