### PR TITLE
mpvScripts: Make more of occivink's scripts available

### PR DESCRIPTION
**Pull request by olmokramer**
## Description of changes

Some mpv scripts from [occivink's mpv-scripts](https://github.com/occivink/mpv-scripts) collection were already available from `pkgs.mpvScripts`. This change makes the `crop` and `encode` scripts also available.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by donovanglover** [comment]
Result of `nixpkgs-review pr 330944` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>mpvScripts.crop</li>
    <li>mpvScripts.encode</li>
    <li>nixpkgs-manual</li>
  </ul>
</details>

**Comment by donovanglover** [comment]
Changes LGTM but I think there should be a separate commit for each script added.

- `mpvScripts.crop: init at 0-unstable-2024-01-11`
- `mpvScripts.encode: init at 0-unstable-2024-01-11`

That way we know when these scripts were added to nixpkgs and at what version.

**Comment by olmokramer** [comment]
Thank you for the feedback @donovanglover, I agree that separate commits per script would be better. I've applied your suggested changes now!

**Review by donovanglover — APPROVED** [review]
Changes look good thanks. Note that we're trying to get rid of periods in `meta.description` (see https://github.com/NixOS/nixpkgs/pull/317959 for prior effort).

Don't want to bother you with this since I think it should be handled automatically by tooling and the `blacklistExtensions` description was misleading, so I'll merge this now and the descriptions can be fixed later. Thanks for contributing!

**Comment by olmokramer** [comment]
Ah so much happening in nixpkgs that it's easy to lose track of it all... I'll keep that in mind for future contributions.

**Pull request merged**
