### PR TITLE
[20.09] Staging

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

Gather and deliver staging changes.

###### Things done

  - [x] [base:staging](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+base%3Astaging-20.09)
  - [x] [base:release](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+base%3Arelease-20.09) (if mass-rebuild)
  - [x] [base: wrong branch](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+base%3Anixos-20.09)
  - [x] let it build on hydra

https://hydra.nixos.org/jobset/nixpkgs/staging-20.09

### CODE REVIEW

**Comment by jonringer** [comment]
we really need a staging/staging-next workflow

**Comment by roberth** [comment]
@nomeata openmolcas [fails](https://hydra.nixos.org/build/136649617/nixlog/1). This seems to be caused by the openblas update. Could you have a look?

**Comment by nomeata** [comment]
Yuck, I basically just backported what’s on `master`, without knowing a lot about the packages. Maybe @jonringer is better suited to investigate.

**Comment by roberth** [comment]
@markuskowa as the maintainer of openmolcas, do you think it's ok to update it for release 20.09? It currently fails on `staging-20.09` because of an `openblas` minor update.

**Comment by markuskowa** [comment]
@roberth The breakage is not because of a minor `openblas` update but rather due to the fact that `openblas` now splits its outputs into `out` and `dev` (CC @jonringer, 7902256cfd1aeec4867e9f3f2fe30b05f6c151b1). Is that really a change that should be ported back to stable?
In any case commit 8b02ff6b8eeb4896276c8777003736598a78d30d fixes the handling of `openblas` split outputs for `openmolcas`. If you cherry-pick that commit it should work again.

**Comment by jonringer** [comment]
> Is that really a change that should be ported back to stable?

Probably not, but reverting the package several times with small changes in between doesn't make for backporting the package easy.

personally, I think fixing the failing builds will be less effort. However, out-of-tree code might break, so it might be best to prune the multiple outputs.

**Comment by jonringer** [comment]
The original PR sat for several days after applying my changes, I just haven't had as much time or will to review the ever-growing nix backlog

Selection_050

**Comment by markuskowa** [comment]
> personally, I think fixing the failing builds will be less effort. However, out-of-tree code might break, so it might be best to prune the multiple outputs.

I suggest to leave out 7902256cfd1aeec4867e9f3f2fe30b05f6c151b1 from the back port. That seems to be the best compromise with the lowest risk of unintended breakage (crossing my fingers that the `openblas` update itself works just fine ;) ).

**Comment by roberth** [comment]
pytorch is now failing on wendy and ike with

```
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: torch
/nix/store/ncs78c8ip7h8ckbj2a6i5iq3xkxsj9jn-python-imports-check-hook.sh/nix-support/setup-hook: line 9: 44826 Illegal instruction     (core dumped) /nix/store/33abxyajzdaggfbcrxzzpslc4582r84l-python3-3.7.9/bin/python3.7 -c 'import os; import importlib; list(map(lambda mod: importlib.import_module(mod), os.environ["pythonImportsCheck"].split()))'
```

This might be caused by the openblas update, because it is a library of highly optimized procedures which may cause a bug like this. On the other hand, it can be triggered by unreproducible builds like

> Using -march=native enables all instruction subsets supported by the local machine (hence the result might not run on different machines)

which could happen anywhere.

Unless someone has any better ideas we'll have to revert the openblas update.

**Comment by jonringer** [comment]
could also be a hydra issue
```
[11:22:13] jon@nixos ~/projects/nixpkgs (staging-20.09)
$ nix-build -A python37Packages.pytorch
/nix/store/s1ahjp7iri00785wgz228yf8ggdp5vfi-python3.7-pytorch-1.6.0
```

**Comment by roberth** [comment]
@jonringer You probably have a cpu that supports the offending instruction, whereas build machines wendy and ike don't.

**Comment by jonringer** [comment]
Yea, but we specify a very low target
```
$ nix eval -f . openblas.makeFlags
[ "BINARY=64" "CC=cc" "CROSS=0" "DYNAMIC_ARCH=1" "FC=gfortran" "HOSTCC=cc" "INTERFACE64=1" "NO_AVX512=1" "NO_BINARY_MODE=" "NO_SHARED=0" "NO_STATIC=1" "NUM_THREADS=64" "PREFIX=/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9" "TARGET=ATHLON" "USE_OPENMP=1" ]
```
if specialized isa extensions are being snuck in, then sure we can revert. I just can't review this PR then

**Comment by jonringer** [comment]
weird that unstable doesn't have this issue https://hydra.nixos.org/eval/1648178?filter=python37Packages.pytorch&compare=1647998&full=

**Comment by roberth** [comment]
That wasn't built on an old server but on packet.net, so that success may have been lucky.
I guess I'll restart them for now, but this is going to be a drain if not fixed in the long term.

@FRidh have you seen this before?

**Comment by roberth** [comment]
I hope these references keep working, unlike hydra's previous log links which are forgotten.

https://nix-cache.s3.amazonaws.com/log/3p6ghxdfyslkwbgi89w9cv8aybc5kp8i-python3.7-pytorch-1.6.0.drv
https://nix-cache.s3.amazonaws.com/log/ii77x3k4x2ypvw8b6yfivwzdfx2fprbg-python3.8-pytorch-1.6.0.drv

I'll keep a copy of them if they break and anyone wants to fix it.

**Comment by worldofpeace** [comment]
> we really need a staging/staging-next workflow

U mean that we should duplicate the workflow that we have on master? I think staging-next on master only became needed because there's so much development and rebuilds that we need to batch them. But on release branches it's mainly security updates, and ideally we'd have the quickest route to deliver those.

**Comment by roberth** [comment]
Regarding workflow, I just jumped in with creating staging PRs, because `staging-20.09` sat around, seemingly unattended for most of January. The volume here seems to be quite low, which is ok because most fixes aren't mass rebuilds anyway.
I can keep that up for another while, but perhaps we can reuse automation from unstable's staging process?

**Pull request merged**
