### PR TITLE
nixos/postfix: allow dollar parameters in lists

### LINKED ISSUE #30521: postfix: $variables inconsistently available in config values
## Issue description

If I use a Postfix `$variable` in a configuration value that takes a string (for example, `services.postfix.origin = "$mydomain";`), it is passed through to Postfix verbatim.

If I use one in a configuration value that takes a list (for example, `services.postfix.destination = [ "mail" "mail.$mydomain" ];`), the dollar sign is escaped, so `postconf -n` shows `mydestination = mail mail.$$mydomain`.

The problem code is in [postfix.nix](/NixOS/nixpkgs/blob/release-17.09/nixos/modules/services/mail/postfix.nix#L29), where `mkList` calls `escape` but `mkVal` does not in the terminal else clause.

I *think* the preferred solution would be to remove `escape` from `mkList` as well, so that we can use `$variables` consistently in Postfix configuration (most Postfix documentation and internet help in general assumes these are available); if the original author of this module had a reason for wanting to always dollar-escape configuration values, then I guess extraConfig is an acceptable way to use `$variables` if we really want them, but it does add some warnings when you redefine things like mydestination.

## Technical details

* System: NixOS 17.09.1716.68ef4b14bc (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 17.09.1716.68ef4b14bc
* Sandboxing enabled: no

### PR DESCRIPTION
**Pull request by rhendric**
###### Motivation for this change

Fixes #30521.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
This may need an entry in the release notes for NixOS 18.03 (backward incompatibility).

**Comment by rhendric** [comment]
Okay, added release note.

Is @qknight the right maintainer to nudge?

**Comment by qknight** [comment]
@uwap could you have a look at this please?

**Comment by uwap** [comment]
Looks alright to me!

**Comment by qknight** [comment]
@bjornfor shall we also integrate it into 17.09?

**Comment by bjornfor** [comment]
@qknight: Won't that break some users configs? Can it be considered a bugfix? I don't know :-)

**Comment by rhendric** [comment]
I would vote for calling this a bugfix, since the inconsistency I described in #30521 is pretty clearly buggy IMO. Looking at the list of supported options, I don't actually think there are any list-of-string options that could reasonably want a literal dollar sign in them—networks and domain names can't contain them—so unless I'm missing something, someone would have to be doing some weird stuff if this broke their config.

**Comment by bjornfor** [comment]
Undo the 18.03 release note then then, and pick both commits to release-17.09?

**Comment by tylerjl** [comment]
+1 to get this into a bugfix earlier than 18.03, as it currently stands, this just straight-up breaks postfix for most configurations. I'm just a user but wanted to mention that this caused postfix to simply break upon upgrading to 17.09 (note that the service starts normally but parses incorrect destinations, so the failure is hard to catch operationally).

**Comment by qknight** [comment]
so any wish what we should do?

**Pull request merged**
