### PR TITLE
monado: upstream missing tooling

### PR DESCRIPTION
**Pull request by Pandapip1**
## Description of changes

My understanding is that tooling that is required for development should be placed in `nativeBuildInputs`, even if it doesn't impact the build.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Scrumplex** [comment]
Hmm. Not quite sure about this. Where have you read about this? :O

**Comment by Pandapip1** [comment]
> Hmm. Not quite sure about this. Where have you read about this? :O

I couldn't find much documentation for 'packages that are required for development but not for building' at all. In `shell.nix`, the only place that really makes makes sense to them it in is `nativeBuildInputs`. The proposed monado `shell.nix` file piggybacks off of `nixpkgs` for the `buildInputs` and `nativeBuildInputs`, since the maintainers are considering adding the `shell.nix` file but don't want to have to maintain it.

Is there a better place to put this?

**Comment by Scrumplex** [comment]
I think this would fit in `passthru` but I am not sure if there is prior precedent to this.

I personally prefer to maintain my own out-of-tree flake for development purposes, if an upstream project is unwilling to include it in the repository.

**Comment by Pandapip1** [comment]
> I think this would fit in passthru but I am not sure if there is prior precedent to this.

Can you link me to the docs?

**Comment by Pandapip1** [comment]
Any updates here?

**Comment by Pandapip1** [comment]
CC @Scrumplex @expipiplus1 @prusnak; this is blocking an upstream MR

**Comment by prusnak** [comment]
> CC @Scrumplex @expipiplus1 @prusnak; this is blocking an upstream MR

How come? Link to MR?

**Comment by Pandapip1** [comment]
> How come? Link to MR?

https://gitlab.freedesktop.org/monado/monado/-/merge_requests/2152

**Comment by prusnak** [comment]
> > How come? Link to MR?
> 
> 
> 
> https://gitlab.freedesktop.org/monado/monado/-/merge_requests/2152

This is just non-sense. Even upstream maintainers in the MR are confused.

I don't think we should add anything that is not directly required for building the package.

**Comment by Pandapip1** [comment]
Actually, on reflection, several of these definitely should be in `nativeBuildInputs`

**Comment by Scrumplex** [comment]
> Actually, on reflection, several of these definitely should be in `nativeBuildInputs`

We only add things to `nativeBuildInputs` that are strictly required to build Monado. As it is right now, adding these dependencies doesn't really affect the build from what I can tell?

**Comment by Pandapip1** [comment]
> We only add things to nativeBuildInputs that are strictly required to build Monado. As it is right now, adding these dependencies doesn't really affect the build from what I can tell?

Yea. Just reverted that commit.

**Comment by prusnak** [comment]
I am closing this. I don't think this makes any sense at all.

**Pull request closed without merging**
