### PR TITLE
sratom: 0.6.0 -> 0.6.2

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
duplicate of #44695 but with an extra dependency?

**Comment by magnetophon** [comment]
It checks for it in the config.
Feel free to close.

**Comment by xeji** [comment]
#44695 was merged to staging (the number of rebuilds is high but not extremely high, so it could go either way).  So if you like to add the dependency, it should go to staging as well, so please rebase this.

**Comment by magnetophon** [comment]
The extra dependency was not put there with much thought.
Sorry for the noise.

**Pull request closed without merging**
