### PR TITLE
cachix: Fix building on hydra and reenable

### LINKED ISSUE #104475: Evaluation error on master related to Cachix
**Describe the bug**
https://github.com/NixOS/nixpkgs/pull/104450
https://gist.github.com/GrahamcOfBorg/47751d3bec1f953492c2df736e58ae2c

**To Reproduce**
```
warning: ignoring the user-specified setting 'restrict-eval', because it is a restricted setting and you are not a trusted user
trace: `mkStrict' is obsolete; use `mkOverride 0' instead.
trace: `lib.nixpkgsVersion` is deprecated, use `lib.version` instead!
trace: warning: lib.readPathsFromFile is deprecated, use a list instead
trace: Warning: `showVal` is deprecated and will be removed in the next release, please use `traceSeqN`
trace: lib.zip is deprecated, use lib.zipAttrsWith instead
error: while evaluating the attribute 'constituents' of the derivation 'nixpkgs-21.03pre999999.82040d6' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-3/pkgs/build-support/trivial-builders.nix:7:7:
while evaluating the attribute 'cachix.x86_64-linux' at undefined position:
attribute 'x86_64-linux' missing, at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-3/pkgs/top-level/release.nix:108:15
```

**Notify maintainers**

@domenkozar 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by maralorn**
###### Motivation for this change

We want to fix #104475 and keep cachix working.

@domenkozar is that okay for you (for now) or did you have something different in mind?

\cc @FRidh 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
@turboMaCk You said in https://github.com/NixOS/nixpkgs/pull/103740#issuecomment-731416898, that `haskell.packages.ghc883.cachix` builds for you. Though are you sure about that? On current master this fails with a failure to build `repline 0.4.0.0` for me.

I might be confusing something there …
Will look into it further.

**Comment by turboMaCk** [comment]
To clarify during tomorrow (during the stream) I just tried to pull `haskell-updates` branch locally and run `nix-build`. I no longer had the result though because I garbage collected it :/

Anyway I tried to pull this PR and test the build. It also no longer works for me. There is a failure in configure phase for `repline-0.4.0.0..` - missing dependency for `haskeline ==0.8.*`.

Feel free to ping me if you need a help with this. I'm `turbo_MaCk#7903` on Discord and `turbo_MaCk` on IRC.

**Comment by turboMaCk** [comment]
Also be aware that @domenkozar is working on 8.10 support in this branch https://github.com/cachix/cachix/pull/331 I think his preferred approach is fix it in upstream right away rather than risking doing more work by both patching & then fixing the upstream.

**Comment by maralorn** [comment]
I have this PR working locally and will push it after a bit of clean-up in a few minutes.

**Comment by maralorn** [comment]
I think having a few `servant-` packages without a broken flag is a bearable problem. I will merge master into haskell-updates, when this is merged and we'll continue curating the package set there.

@domenkozar This built for me locally. I suggest you press merge, if you want.

**Comment by turboMaCk** [comment]
:+1: one for switching to patch for ghc 8.10. I was also able to build this locally.

**Comment by domenkozar** [comment]
@maralorn I really appreciate your effort and help getting this fixed <3

**Pull request merged**
