### PR TITLE
dub: 1.30.0 -> 1.33.0

### PR DESCRIPTION
**Pull request by jtbx**
## Description of changes

https://github.com/dlang/dub/releases/tag/v1.33.0

One of the newer tests, `use-c-sources`, fails, so I added it to the list of already failing tests.

Added myself to meta.maintainers also.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
This would break the build of the "Literate" package:

```
dub --root=lit/tangle build
    Starting Performing "debug" build using ldc2 for x86_64.
Error /homeless-shelter: Permission denied
make: *** [Makefile:11: bin/tangle] Error 2
```

Want to fix up that package to set HOME?  (Or maybe there's a better solution?)

**Comment by jtbx** [comment]
Yeah I'd say it's the best solution, other packages do it too.

**Comment by jtbx** [comment]
Literate builds fine for me, probably because it shouldn't have to access HOME anyway since dub doesn't have download any dependencies (which are cached in HOME/.dub)

**Comment by alyssais** [comment]
On top of this PR?

**Comment by jtbx** [comment]
Oops, no. I'll push a fix.

**Comment by alyssais** [comment]
One small thing: can you swap the order of commits?  That means there's never a state where Literate doesn't build, which is nice for bisectability.

**Pull request merged**
