### PR TITLE
[21.11] python3Packages.tensorflow: patch for compatibility with h5py 3.0.0+

### LINKED ISSUE #124599: tensorflow 2.4 depends on h5py 2.10 but is packaged with h5py 3.2
**Describe the bug**
h5py 3 is incompatible with tensorflow 2.4 (see [here](https://github.com/tensorflow/tensorflow/issues/44467)).

**To Reproduce**
1. Load model
2. Run script
3. Encounter error

```
# Error when loading model
model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**Expected behavior**
It's supposed to be packaged with h5py 2.10 to avoid the bug.

**Notify maintainers**

@jyp @abbradar

### LINKED ISSUE #147321: Keras HDF5 model loading is broken
### Describe the bug
Keras crashes trying to load HDF5 format models

### Steps To Reproduce
```
$ nix-shell -p 'python3.withPackages (p: with p; [ tensorflow_2 Keras ])' --run python3
Python 3.8.11 (default, Jun 28 2021, 10:57:31) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras.models import Sequential, load_model
>>> m = Sequential()
>>> m.build((1,))
>>> m.save("test.h5")
>>> load_model("test.h5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/55rirzxfv37rsz5c13dh88hnj0apzhva-python3-3.8.11-env/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/nix/store/55rirzxfv37rsz5c13dh88hnj0apzhva-python3-3.8.11-env/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 182, in load_model_from_hdf5
    model_config = json_utils.decode(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
>>> 
```

### Expected behavior
I expect models to load without crashing.

### Additional context
This is a known Keras bug due to an incompatibility with h5py >= 3.0.0. Solutions I have tried that worked include building both Keras and Tensorflow with h5py 2.10.0 (which must itself be built with the old HDF5 1.10), and patching Tensorflow as noted here: https://github.com/tensorflow/tensorflow/issues/44467#issuecomment-720042186 . Allegedly updating Tensorflow past 2.4 also works.

IMHO it would be best to update both Tensorflow and Keras to 2.7.0 and backport the updates to at least 21.11.

### Notify maintainers

cc @veprbl

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-90-generic, Ubuntu, 20.04.2 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(tpwatson): `"nixpkgs-21.05.4349.09650059d7f"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

Fixes #147321
Fixes #124599

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
cc @tpwrules

**Comment by tpwrules** [comment]
I tested on x86_64-linux and it works great. Thank you!

**Comment by veprbl** [comment]
Great!

**Comment by sekunho** [comment]
Thank you!

**Pull request merged**
