### PR TITLE
rustc: 1.62.1 -> 1.63.0

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

`fd` builds on x86_64-linux; waiting for Firefox and Thunderbird.

**Could an x86_64-darwin user please build `fd`?**

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Firefox and Thunderbird build on x86_64-linux.

**Comment by zowoq** [comment]
Built `fd` on `x86_64-darwin`.

**Comment by trofi** [comment]
`evcxr` fails tests in `staging` after 59dd915c110fad911067c18aaffb53ac75b99015 `rustc: 1.62.1 -> 1.63.0` as:

```
$ nix build -f. evcxr -L
...
evcxr> failures:
evcxr> ---- abort_and_restart stdout ----
evcxr> thread 'abort_and_restart' panicked at 'assertion failed: `(left == right)`
evcxr>   left: `"Child process terminated with status: signal: 6 (SIGABRT) (core dumped)"`,
evcxr>  right: `"Child process terminated with status: signal: 6"`', evcxr/tests/integration_tests.rs:576:17
evcxr> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
evcxr> failures:
evcxr>     abort_and_restart
evcxr> test result: FAILED. 36 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 50.62s
```

**Comment by Mic92** [comment]
I would try to bump to the latest version of evcxr: https://github.com/google/evcxr/releases/tag/v0.13.0

**Comment by trofi** [comment]
Oh, good call! https://github.com/google/evcxr/commit/a7e7580acaee82693ddcb9affcb37f9f6bd72bd6 looks like a fix. Proposed  https://github.com/NixOS/nixpkgs/pull/186442 update to `0.13.0` which fixes all test faiiures for me.

**Pull request merged**
