### PR TITLE
Add name parameter to developPackage

### PR DESCRIPTION
**Pull request by mightybyte**
###### Motivation for this change

Without this change, developPackage does not work for projects where the directory has a different name than the `.cabal` file.  You also can't do `root = builtins.filterSource...` because `builtins.baseNameOf` doesn't work on filterSource's return value.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mightybyte** [comment]
Pinging @shlevy

**Review by shlevy — APPROVED** [review]

**Review by basvandijk — CHANGES_REQUESTED** [review]
Nice improvement. The [documentation](https://github.com/NixOS/nixpkgs/blob/d36c55a530e31955ef9657dab745faf9f315eae8/pkgs/development/haskell-modules/make-package-set.nix#L203:L204) still mentions that the directory and cabal file should have the same name. Could you update it?

**Comment by mightybyte** [comment]
@basvandijk Ahh, good catch.  I've pushed an update.

**Comment by ryantm** [comment]
Thanks!

**Pull request merged**
