### PR TITLE
Cleanup of dead packages after Gna.org closure

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change

Gna.org forge has been closed for a while now. See [archived announce](https://web.archive.org/web/20170505010209/https://mail.gna.org/public/project/2016-11/msg00001.html).
I've updated packages that move elsewhere in the last few months, now comes the time to remove the ones that disappeared along with the forge.

* `blackshades-elite` cc @viric 
* `smbldap-tools` legacy, Samba3-only
* `remember` is now a mode of base emacs so was irrelevant as an external plugin anyway
* `poker-eval` cc @Zert and its Haskell bindings
* `bins` no homepage / no source repo / no maintainers
* `pdfshuffler` ~~was just marked broken and not removed since its SF.net repo may still be alive~~  @Mic92  removed too

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
Oh I missed that `poker-eval` was referenced in Haskell packages...

@ryantm @basvandijk can you remove `haskellPackages.poker-eval` properly? I have no clue about Haskell packaging, I just know that `hackage-packages.nix` is auto-generated and that I should not mess with it manually :cat2:

**Comment by Mic92** [comment]
pdfshuffler can be also removed.

**Comment by Mic92** [comment]
There is an active fork of it, if somebody is interested in packaging it: https://github.com/jeromerobert/pdfarranger

**Comment by peti** [comment]
@c0bw3b, we package every package on Hackage. So we won't release `power-eval` even if it no longer builds. What should be done is to replace the reference to `pkgs.poker-eval` in `pkgs/development/haskell-modules/hackage-packages.nix` by `null` to avoid evaluation errors.

**Comment by c0bw3b** [comment]
Okay, thanks for the explanation.
It would mean change it to:
```nix
  "poker-eval" = callPackage
    ({ mkDerivation, array, base, mtl, poker-eval, random, vector }:
     mkDerivation {
       pname = "poker-eval";
       version = "0.3.1";
       sha256 = "0v1is9jnpw1ij3b7h9figkjqk58dzc44v6vpdmxfmb80w0myihrv";
       libraryHaskellDepends = [ array base mtl random vector ];
       librarySystemDepends = [ poker-eval ];
       description = "Binding to libpoker-eval";
       license = stdenv.lib.licenses.publicDomain;
     }) {poker-eval=null;}
```
( instead of `inherit (pkgs) poker-eval;` on the last line )


But am I allowed to edit that manually in `hackage-packages.nix`?

**Comment by peti** [comment]
> But am I allowed to edit that manually in `hackage-packages.nix`?

Yes. At some point in the future, `hackage2nix` will re-generate the file,  but it will generate the exact same code that you've cited above.

**Comment by c0bw3b** [comment]
Thank you @peti 
I will complete this PR later today

**Pull request merged**
