### PR TITLE
libtom{crypt,math}: update to 1.18.0 and 1.0.1 resp.

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change
Version bump
And homepage refresh (see #30636)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
nox-review pr is successful 
```shell
Result in /tmp/nox-review-adf20lef
total 8
lrwxrwxrwx 1 demo users 62  7 nov.  23:29 result -> /nix/store/asnjz6hf6xd0qylns346w53d8m4kwhpp-libtomcrypt-1.18.0
lrwxrwxrwx 1 demo users 60  7 nov.  23:29 result-2 -> /nix/store/94rgzbyzrcq9im843hxkyds6nn59kyr8-libtommath-1.0.1
lrwxrwxrwx 1 demo users 58  7 nov.  23:29 result-3 -> /nix/store/f2mvk3jpgwhk8zs42zvbvc3wxw6bda18-convertlit-1.8
```

**Comment by c0bw3b** [comment]
Needs a little fixing for Darwin apparently

**Comment by c0bw3b** [comment]
Fixed `libtommath` build on Darwin and kept `libtomcrypt` linux-only

The nixos-manual job of Travis jobset fails because of:
```shell
Package ‘oraclejre-8u151’ in /home/travis/build/NixOS/nixpkgs/pkgs/development/compilers/oraclejdk/jdk-linux-base.nix:80 has an unfree license (‘unfree’), refusing to evaluate.
```
Probably not related to my commits

**Comment by grahamc** [comment]
@GrahamcOfBorg libtommath libtomcrypt

**Comment by c0bw3b** [comment]
Rebased on master after  #31528 and all Travis jobs are ok now

**Pull request merged**
