### PR TITLE
[21.05] zfs: Linux 5.14 compatibility

### PR DESCRIPTION
**Pull request by hmenke**
###### Motivation for this change

There were two recent ZFS releases with Linux 5.14 compatibility fixes.
https://github.com/openzfs/zfs/releases/tag/zfs-2.0.6
https://github.com/openzfs/zfs/releases/tag/zfs-2.1.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hmenke** [comment]
Result of `nixpkgs-review pr 138828` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>linuxPackages-libre.zfs</li>
    <li>linuxPackages-libre.zfsUnstable</li>
    <li>linuxPackages_latest-libre.zfs</li>
    <li>linuxPackages_latest-libre.zfsUnstable</li>
  </ul>
</details>
<details>
  <summary>69 packages built:</summary>
  <ul>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome.gnome-boxes</li>
    <li>libceph</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvmi</li>
    <li>linuxPackages.zfs</li>
    <li>linuxPackages.zfsUnstable</li>
    <li>linuxPackages_4_14.zfs</li>
    <li>linuxPackages_4_14.zfsUnstable</li>
    <li>linuxPackages_4_19.zfs</li>
    <li>linuxPackages_4_19.zfsUnstable</li>
    <li>linuxPackages_4_4.zfs</li>
    <li>linuxPackages_4_4.zfsUnstable</li>
    <li>linuxPackages_4_9.zfs</li>
    <li>linuxPackages_4_9.zfsUnstable</li>
    <li>linuxPackages_5_13.zfs</li>
    <li>linuxPackages_5_13.zfsUnstable</li>
    <li>linuxPackages_5_14.zfs</li>
    <li>linuxPackages_5_14.zfsUnstable</li>
    <li>linuxPackages_5_4.zfs</li>
    <li>linuxPackages_5_4.zfsUnstable</li>
    <li>linuxPackages_hardened.zfs (linuxPackages_latest_hardened.zfs)</li>
    <li>linuxPackages_hardened.zfsUnstable (linuxPackages_latest_hardened.zfsUnstable)</li>
    <li>linuxPackages_lqx.zfs</li>
    <li>linuxPackages_lqx.zfsUnstable</li>
    <li>linuxPackages_testing_bcachefs.zfs</li>
    <li>linuxPackages_testing_bcachefs.zfsUnstable</li>
    <li>linuxPackages_xanmod.zfs</li>
    <li>linuxPackages_xanmod.zfsUnstable</li>
    <li>linuxPackages_zen.zfs</li>
    <li>linuxPackages_zen.zfsUnstable</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixopsUnstable</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>partition-manager</li>
    <li>perl530Packages.SysVirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>python38Packages.guestfs</li>
    <li>python38Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>qemu_full</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_2_6.ruby-libvirt</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>samba4Full</li>
    <li>sanoid</li>
    <li>terraform-full</li>
    <li>terraform-provider-libvirt (terraform-providers.libvirt)</li>
    <li>vagrant</li>
    <li>virtmanager (virt-manager)</li>
    <li>virtmanager-qt (virt-manager-qt)</li>
    <li>virt-top</li>
    <li>virtviewer (virt-viewer)</li>
    <li>virtlyst</li>
    <li>zfs</li>
    <li>zfsUnstable</li>
    <li>zfstools</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 138828` at 6c840afd run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages marked as broken and skipped:</summary>
  <ul>
    <li>libvirt_5_9_0</li>
    <li>libvmi</li>
    <li>linuxPackages_hardkernel_4_14.zfs</li>
    <li>linuxPackages_hardkernel_4_14.zfsStable</li>
    <li>linuxPackages_hardkernel_4_14.zfsUnstable</li>
    <li>linuxPackages_hardkernel_latest.zfs</li>
    <li>linuxPackages_hardkernel_latest.zfsStable</li>
    <li>linuxPackages_hardkernel_latest.zfsUnstable</li>
    <li>linuxPackages_testing_bcachefs.zfs</li>
    <li>linuxPackages_testing_bcachefs.zfsStable</li>
    <li>linuxPackages_testing_bcachefs.zfsUnstable</li>
  </ul>
</details>
<details>
  <summary>45 packages skipped due to time constraints:</summary>
  <ul>
    <li>bareos</li>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>haskellPackages.libvirt-hs</li>
    <li>libceph</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>18 packages built successfully:</summary>
  <ul>
    <li>haskellPackages.libzfs</li>
    <li>linuxPackages_4_14.zfs (linuxPackages_4_14.zfsStable)</li>
    <li>linuxPackages_4_14.zfsUnstable</li>
    <li>linuxPackages_4_19.zfs (linuxPackages_4_19.zfsStable)</li>
    <li>linuxPackages_5_13.zfs (linuxPackages_5_13.zfsStable)</li>
    <li>linuxPackages_5_14.zfs (linuxPackages_5_14.zfsStable ,linuxPackages_latest.zfs ,linuxPackages_latest.zfsStable)</li>
    <li>linuxPackages_5_4.zfs (linuxPackages_5_4.zfsStable)</li>
    <li>linuxPackages_5_4.zfsUnstable</li>
    <li>linuxPackages_hardened.zfs (linuxPackages_hardened.zfsStable ,linuxPackages_latest_hardened.zfs ,linuxPackages_latest_hardened.zfsStable)</li>
    <li>linuxPackages_hardened.zfsUnstable (linuxPackages_latest_hardened.zfsUnstable)</li>
    <li>linuxPackages_lqx.zfs (linuxPackages_lqx.zfsStable)</li>
    <li>linuxPackages_lqx.zfsUnstable</li>
    <li>linuxPackages_zen.zfs (linuxPackages_zen.zfsStable)</li>
    <li>linuxPackages_zen.zfsUnstable</li>
    <li>sanoid</li>
    <li>zfs (zfsStable)</li>
    <li>zfsUnstable</li>
    <li>zfstools</li>
  </ul>
</details>

**Review by Mic92 — APPROVED** [review]
Not tested but agree that we should have this backport.

**Comment by Mic92** [comment]
@ofborg test zfs

**Pull request merged**
