### PR TITLE
darwin.stdenv: use CoreFoundation instead of CF

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

This patch switches the CoreFoundation on x86_64-darwin from the open source swift-corelibs-foundation (CF) to the system CoreFoundation. The changes were tested by building the stdenv and Nix, which depends on aws-sdk-cpp.

This change was motivated by failures building packages for the current staging-next cycle https://github.com/NixOS/nixpkgs/pull/263535 due to an apparent incompatibility with the rpath-based approach to choosing CF or CoreFoundation and macOS 14. This error often manifests as a crash with an Illegal Instruction.

For example, building aws-sdk-cpp for building Nix will fail this way.

https://hydra.nixos.org/build/239459417/nixlog/1

    Application Specific Information:
    CF objects must have a non-zero isa

    Error Formulating Crash Report:
    PC register does not match crashing frame (0x0 vs 0x7FF8094DD640)

    Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
    0   CoreFoundation                	    0x7ff8094dd640 CF_IS_OBJC.cold.1 + 14
    1   CoreFoundation                	    0x7ff8094501d0 CF_IS_OBJC + 60
    2   CoreFoundation                	    0x7ff8093155e8 CFRelease + 40
    3   ???                           	       0x10c7a2c61 s_aws_secure_transport_ctx_destroy + 65
    4   ???                           	       0x10c87ba32 aws_ref_count_release + 34
    5   ???                           	       0x10c7b7adb aws_tls_connection_options_clean_up + 27
    6   ???                           	       0x10c596db4 Aws::Crt::Io::TlsConnectionOptions::~TlsConnectionOptions() + 20
    7   ???                           	       0x10c2d249c Aws::CleanupCrt() + 92
    8   ???                           	       0x10c2d1ff0 Aws::ShutdownAPI(Aws::SDKOptions const&) + 64
    9   ???                           	       0x102d9bc6f main + 335
    10  dyld                          	       0x202f333a6 start + 1942

According to a [post][1] on the Apple developer forums, hardening was added to CoreFoundation, and this particular message occurs when you attempt to release an object it does not recognize as a valid CF object. (Thank you to @lilyinstarlight for finding this post).

When I switched aws-sdk-cpp to link against CoreFoundation instead of CF, the error went away. Somehow both libraries were being used. To prevent dependent packages from linking the wrong CoreFoundation, it would need to be added as a propagated build input.

Note that there are other issues related to mixing CF and CoreFoundation frameworks. https://github.com/NixOS/nixpkgs/pull/264503 fixes an issue with abseil-cpp where it propagates CF, causing issues when using a different SDK version. Mixing versions can also cause crashes with Python when a shared object is loaded that is linked to the “wrong” CoreFoundation.

`NIX_COREFOUNDATION_RPATH` is supposed to make sure the right CoreFoundation is being used, but it does not appear to be enough on macOS 14 (presumably due to the hardening). While it is possible to propagate CoreFoundation manually, the cleaner solution is to make it the default. CF remains available as `darwin.swift-corelibs-foundation`.

[1]: https://developer.apple.com/forums/thread/739355

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by reckenrode** [comment]
@toonn

**Comment by vcunat** [comment]
you suggest to rebuild darwin stdenv in `staging-next`?

**Comment by reckenrode** [comment]
> you suggest to rebuild darwin stdenv in `staging-next`?

Yes. This is the CoreFoundation change I’ve been discussing in the staging channel on Matrix. @K900 suggested I should probably submit it now if I don’t expect more stdenv rebuilds.

**Comment by vcunat** [comment]
`staging-next..staging` currently does change stdenv.outPath on x86_64-darwin, on a quick check.

**Comment by K900** [comment]
AFAICT we have 3k regressions on Darwin which can't really be fixed without this, so we basically have to eat the rebuild count.

**Comment by reckenrode** [comment]
I’m going to retarget this to staging. While I think it’s an improvement for the maintainability and reliability of Darwin, I’m not seeing where those 3k failures are due to this issue, and not having to rebuild the stdenv is highly preferable right now.

**Comment by reckenrode** [comment]
I’m flipping this back out of draft. python3Packages.tokenizers is another example that crashes (along with aws-sdk-cpp and arrow-cpp). The common thread is they all use the AWS SDK and link against both CF and CoreFoundation. While it is possible to fix all the aws-* packages to link CoreFoundation, my concern is that would be kicking the can down the road. In this particular case, only the packages that link other frameworks are linking CoreFoundation. When those are mixed with others that don’t, that’s when things break.

**Comment by reckenrode** [comment]
Converting to draft while I figure why retargeting to staging-next is causing an infinite recursion.

**Comment by reckenrode** [comment]
Marking this ready. It actually evals. I’m just bad at git. Apparently `git rebase FETCH_HEAD~3..FETCH_HEAD` is not the same as `git rebase FETCH_HEAD~3 FETCH_HEAD~2 FETCH_HEAD~1 FETCH_HEAD`.

**Comment by reckenrode** [comment]
Merging to unblock the Darwin staging-next eval.

**Pull request merged**
