### PR TITLE
psmisc: 23.5 -> 23.6

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://gitlab.com/psmisc/psmisc/-/blob/v23.6/ChangeLog?ref_type=tags#L1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 248592` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>heroic</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>lutris-unwrapped.dist</li>
    <li>rng-tools</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>epsonscan2</li>
    <li>hylafaxplus</li>
    <li>ipmiview</li>
    <li>killall (unixtools.killall)</li>
    <li>psmisc</li>
    <li>smart-wallpaper</li>
    <li>timeshift</li>
    <li>tmpwatch</li>
    <li>x2goserver</li>
    <li>xfstests</li>
    <li>zoneminder</li>
  </ul>
</details>

**Comment by trofi** [comment]
The rebuild small enough for `master`. Repointed there.

> 6 packages failed to build:

Can you post a build log for one of them? Say, `rng-tools`? Somehow it builds for me as is on `x86_64-linux`:

```
$ nix build --no-link github:NixOS/nixpkgs/pull/248592/merge#rng-tools
<ok>
```

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 248592` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>epsonscan2</li>
    <li>heroic</li>
    <li>hylafaxplus</li>
    <li>ipmiview</li>
    <li>killall (unixtools.killall)</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>lutris-unwrapped.dist</li>
    <li>psmisc</li>
    <li>rng-tools</li>
    <li>smart-wallpaper</li>
    <li>timeshift</li>
    <li>tmpwatch</li>
    <li>x2goserver</li>
    <li>xfstests</li>
    <li>zoneminder</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
I get:

```
...
checking for C compiler default output file name... a.out                                                                                                                                                                                      
...skipping...                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                               
.. contents:: :depth: 2                                                                                                                                                                                                                        
                                                                                                                                                                                                                                               
FAIL: rngtestjitter.sh                                                                                                                                                                                                                         
======================                                                                                                                                                                                                                         
                                                                                                                                                                                                                                               
Disabling 0: Hardware RNG Device (hwrng)                                                                                                                                                                                                       
Disabling 2: Intel RDRAND Instruction RNG (rdrand)                                                                                                                                                                                             
Disabling 1: TPM RNG Device (tpm)                                                                                                                                                                                                              
Initializing available sources                                                                                                                                                                                                                 
[jitter]: JITTER timeout set to 10 sec                                                                                                                                                                                                         
[jitter]: Initializing AES buffer                                                                                                                                                                                                              
[jitter]: Enabling JITTER rng support                                                                                                                                                                                                          
[jitter]: Initialized                                                                                                                                                                                                                          
[pkcs11]: No pkcs11 slots available                                                                                                                                                                                                            
[pkcs11]: Initialization Failed                                                                                                                                                                                                                
[rtlsdr]: Initialization Failed                                                                                                                                                                                                                
unable to adjust write_wakeup_threshold: Permission denied                                                                                                                                                                                     
rngtest: bits received from input: 2000064                                                                                                                                                                                                     
rngtest: bits sent to output: 1980000                                                                                                                                                                                                          
rngtest: FIPS 140-2 successes: 99                                                                                                                                                                                                              
rngtest: FIPS 140-2 failures: 1                                                                                                                                                                                                                
rngtest: FIPS 140-2(2001-10-10) Monobit: 0                                                                                                                                                                                                     
rngtest: FIPS 140-2(2001-10-10) Poker: 0                                                                                                                                                                                                       
rngtest: FIPS 140-2(2001-10-10) Runs: 1                                                                                                                                                                                                        
rngtest: FIPS 140-2(2001-10-10) Long run: 0                                                                                                                                                                                                    
rngtest: FIPS 140-2(2001-10-10) Continuous run: 0                                                                                                                                                                                              
rngtest: input channel speed: (min=4.500; avg=23.000; max=19073.486)Mibits/s                                                                                                                                                                   
rngtest: FIPS tests speed: (min=41.736; avg=131.179; max=149.012)Mibits/s                                                                                                                                                                      
rngtest: output channel speed: (min=2.661; avg=9.757; max=18.626)Gibits/s                                                                                                                                                                      
rngtest: Program run time: 6905012 microseconds                                                                                                                                                                                                
killing                                                                                                                                                                                                                                        
FAIL rngtestjitter.sh (exit status: 1)                                                                                                                                                                                                         
                                                                                                                                                                                                                                               
============================================================================                                                                                                                                                                   
Testsuite summary for rng-tools 6.16                                                                                                                                                                                                           
============================================================================                                                                                                                                                                   
# TOTAL: 3                                                                                                                                                                                                                                     
# PASS:  2                                                                                                                                                                                                                                     
# SKIP:  0                                                                                                                                                                                                                                     
# XFAIL: 0                                                                                                                                                                                                                                     
# FAIL:  1                                                                                                                                                                                                                                     
# XPASS: 0                                                                                                                                                                                                                                     
# ERROR: 0                                                                                                                                                                                                                                     
============================================================================                                                                                                                                                                   
See tests/test-suite.log                                                                                                                                                                                                                       
Please report to Neil Horman <nhorman@tuxdriver.com>                                                                                                                                                                                           
============================================================================ 
```

**Comment by matthiasbeyer** [comment]
The command you posted prints `0` for me as well.

**Comment by trofi** [comment]
I wonder what differs on your system from mine. Here are my systems where it works:

```
$ nix --version; uname -a
nix (Nix) 2.17.0
Linux nz 6.4.8 #1-NixOS SMP PREEMPT_DYNAMIC Thu Aug  3 08:26:15 UTC 2023 x86_64 GNU/Linux
```

```
$ nix --version; uname -a
nix (Nix) 2.14.1
Linux sk 6.2.7 #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 17 07:58:04 UTC 2023 x86_64 GNU/Linux
```

**Comment by matthiasbeyer** [comment]
I am running

```
nix (Nix) 2.13.5                                                                                                                                               
Linux moon 5.15.125 #1-NixOS SMP Tue Aug 8 17:58:35 UTC 2023 x86_64 GNU/Linux
```

**Comment by trofi** [comment]
Works on `5.15.126` for me as well:

```
$ uname -r
5.15.126

$ nix build github:NixOS/nixpkgs/e6e55010858023a048cf36b4dd422a483878a581#rng-tools && nix build github:NixOS/nixpkgs/e6e55010858023a048cf36b4dd422a483878a581#rng-tools --rebuild; echo $?
0

$ nix build --no-link github:NixOS/nixpkgs/pull/248592/merge#rng-tools; echo $?
0
```

Might be CPU-specific? Mine supports `rdrand`.

```
$ LANG=C lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  32
  On-line CPU(s) list:   0-15
  Off-line CPU(s) list:  16-31
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 9 5950X 16-Core Processor
    CPU family:          25
    Model:               33
    Thread(s) per core:  1
    Core(s) per socket:  16
    Socket(s):           1
    Stepping:            0
    Frequency boost:     enabled
    CPU(s) scaling MHz:  84%
    CPU max MHz:         5083.3979
    CPU min MHz:         0.0000
    BogoMIPS:            6787.35
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpu
                         id extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dn
                         owprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms i
                         nvpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lb
                         rv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succo
                         r smca fsrm
Virtualization features:
  Virtualization:        AMD-V
Caches (sum of all):
  L1d:                   512 KiB (16 instances)
  L1i:                   512 KiB (16 instances)
  L2:                    8 MiB (16 instances)
  L3:                    64 MiB (2 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-15
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
  Spectre v2:            Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by matthiasbeyer** [comment]
On `LANG=C lscpu | grep rdrand` I get output... so I assume that it supports it as well... :shrug:

**Comment by trofi** [comment]
Looking at `FAIL: rngtestjitter.sh` I wonder if this test is performance-sensitive. Could it be that something interferes with the test on your machine? If you happen to run tests in a VM, or there are other RNG-heavy tasks.

**Comment by trofi** [comment]
There is the actual test: https://github.com/nhorman/rng-tools/blob/master/tests/rngtestjitter.sh#L15

It does disable most of hardware-accelerating bits and uses AES directly. The test timeout is 30s. You can try to run that command directly and see how it behaves from run to run on your system.

**Comment by trofi** [comment]
Another possible avenue is change of `killall` behaviour around https://github.com/nhorman/rng-tools/blob/master/tests/rngtestjitter.sh#L6

`psmisc` added a `kill()` fallback in case `pidfd_send_signal()` returns `ENOSYS`:  https://gitlab.com/psmisc/psmisc/-/commit/6892e321e7042e3df60a5501a1c59d076e8a856f

Could it be that you are running some kind of sandbox (like docker) and it filters `pidfd_send_signal()` with some other error errorcode like `EPERM`?

**Comment by trofi** [comment]
No, I think `psmisc` is a distraction. `killall` only kills `rngd`, but not `rngtest` (which should return actual status).

`rngtest` returns `1` error code when `rngtest` detects a problem in random quality:

> rngtest: FIPS 140-2 successes: 99                                                                                                                                                                                                              
> rngtest: FIPS 140-2 failures: 1     
> FAIL rngtestjitter.sh (exit status: 1)                                                                                                                                                                                                         

```
EXIT STATUS
       ...
       1 if no errors happen, but at least one block fails the FIPS tests.
       ...
```

**Comment by matthiasbeyer** [comment]
So I am running the build on a VPS, which might be the problem here. What you'd have me do?

**Comment by trofi** [comment]
Good question. I would focus on the following question:

rule out `psmisc` and get more confidence it's the problem of the build environment

For that I suggest running 10 rebuilds at `psmisc` patch and before `psmisc` patch:

At:

```
$ nix build --no-link github:NixOS/nixpkgs/pull/248592/merge#rng-tools; for i in `seq 1 10`; do nix build --no-link github:NixOS/nixpkgs/pull/248592/merge#rng-tools --rebuild; done
```

Before:

```
$ nix build --no-link github:NixOS/nixpkgs/e6e55010858023a048cf36b4dd422a483878a581#rng-tools; for i in `seq 1 10`; do  nix build --no-link github:NixOS/nixpkgs/e6e55010858023a048cf36b4dd422a483878a581#rng-tools --rebuild; done
```

In both cases can you cont and report how many times the build failed?

**Comment by trofi** [comment]
If you run `nixpkgs-review` against this PR again, does it fail?

**Comment by matthiasbeyer** [comment]
Yes, see https://github.com/NixOS/nixpkgs/pull/248592#issuecomment-1676037026

**Comment by trofi** [comment]
Yes, I suggest running it again.

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 248592` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>epsonscan2</li>
    <li>heroic</li>
    <li>hylafaxplus</li>
    <li>ipmiview</li>
    <li>killall (unixtools.killall)</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>lutris-unwrapped.dist</li>
    <li>psmisc</li>
    <li>rng-tools</li>
    <li>smart-wallpaper</li>
    <li>timeshift</li>
    <li>tmpwatch</li>
    <li>x2goserver</li>
    <li>xfstests</li>
    <li>zoneminder</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
Hm, weird.

**Comment by trofi** [comment]
I suspect these packages are not very tolerant to overloaded systems. Which might be a problem with these packages. But there is a fine line between small unrelated system load and overload to a point when test just start timing out. You might need to explore individual failures locally to say for sure.

**Pull request merged**
