### PR TITLE
cc-wrapper: fix regression for the C compiler wrapper

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

#111970 caused a regression: C compiler is now passed a path to the C++ standard library includes
Fixes: #118195
Fixes: #119866
Fixes the original issue behind #111970 (cc @ttuegel)
cc @abbradar as author of the original nostdlib logic 87607af7a1bf35682f8ad206307ed46e8ead260a

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]
I like the look of this, including the `cpp` -> `cxx`.

**Comment by domenkozar** [comment]
cc @jonringer this is needed for fixing a bunch of macOS packages.

**Review by jonringer — APPROVED** [review]
Diff LGTM

(hopefully) not a breaking change :)

**Comment by lugray** [comment]
Can this be added to nixpkgs-unstable? https://github.com/NixOS/nixpkgs/commit/54c7a0f42287f63c2db8086a8ad46ac981364378, which this fixes, exists on nixpkgs-unstable.

**Comment by veprbl** [comment]
@lugray This is on its course towards that: staging -> staging-next -> master -> nixpkgs-unstable

**Comment by lugray** [comment]
Ah, okay. Thanks for explaining the process.

**Comment by ldeck** [comment]
Is this related to https://github.com/NixOS/nix/issues/4621?

**Comment by veprbl** [comment]
@ldeck, no, it's not.

**Pull request merged**
