### PR TITLE
gspeech: init at 0.9.2

### PR DESCRIPTION
**Pull request by mothsART**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jpotier** [comment]
chore: You may want to redo your `--amend`, as your second commit is actually named `--amend` :)

**Comment by mothsART** [comment]
> chore: You may want to redo your `--amend`, as your second commit is actually named `--amend` :)

correct, done.

**Comment by jpotier** [comment]
Trying to build locally (with sandboxing, on NixOS) fails with the following error:
```sh
$ git clone https://github.com/mothsART/nixpkgs
$ git checkout feature/new-package-gspeech
$ nix build -I nixpkgs=./ nixpkgs.gspeech
builder for '/nix/store/z90zqbzd3b7g5hapbc5956rv4bh5rrdg-gSpeech-0.9.0.drv' failed with exit code 1; last 10 log lines:
  writing entry points to gspeech.egg-info/entry_points.txt
  writing top-level names to gspeech.egg-info/top_level.txt
  package init file 'speech/workers/__init__.py' not found (or not a regular file)
  package init file 'speech/workers/fr_FR/__init__.py' not found (or not a regular file)
  reading manifest file 'gspeech.egg-info/SOURCES.txt'
  writing manifest file 'gspeech.egg-info/SOURCES.txt'
  running build_ext
  /build/source/speech/widgets/save.py:5: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
    from gi.repository import Gtk
  error: [Errno 13] Permission denied: '/homeless-shelter'
[1 built (1 failed), 174 copied (803.4 MiB), 178.9 MiB DL]
error: build of '/nix/store/z90zqbzd3b7g5hapbc5956rv4bh5rrdg-gSpeech-0.9.0.drv' failed
```

I see ofborg has the exact same problem [trying to build gspeech](https://github.com/NixOS/nixpkgs/pull/86641/checks?check_run_id=646318879). Unfortunately, I'm not too familiar with building python packages in nix, so my helping is limited.

**Comment by mothsART** [comment]
> Trying to build locally (with sandboxing, on NixOS) fails with the following error:
> 
> ```shell
> $ git clone https://github.com/mothsART/nixpkgs
> $ git checkout feature/new-package-gspeech
> $ nix build -I nixpkgs=./ nixpkgs.gspeech
> builder for '/nix/store/z90zqbzd3b7g5hapbc5956rv4bh5rrdg-gSpeech-0.9.0.drv' failed with exit code 1; last 10 log lines:
>   writing entry points to gspeech.egg-info/entry_points.txt
>   writing top-level names to gspeech.egg-info/top_level.txt
>   package init file 'speech/workers/__init__.py' not found (or not a regular file)
>   package init file 'speech/workers/fr_FR/__init__.py' not found (or not a regular file)
>   reading manifest file 'gspeech.egg-info/SOURCES.txt'
>   writing manifest file 'gspeech.egg-info/SOURCES.txt'
>   running build_ext
>   /build/source/speech/widgets/save.py:5: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>     from gi.repository import Gtk
>   error: [Errno 13] Permission denied: '/homeless-shelter'
> [1 built (1 failed), 174 copied (803.4 MiB), 178.9 MiB DL]
> error: build of '/nix/store/z90zqbzd3b7g5hapbc5956rv4bh5rrdg-gSpeech-0.9.0.drv' failed
> ```
> 
> I see ofborg has the exact same problem [trying to build gspeech](https://github.com/NixOS/nixpkgs/pull/86641/checks?check_run_id=646318879). Unfortunately, I'm not too familiar with building python packages in nix, so my helping is limited.
> 
> This error: `error: [Errno 13] Permission denied: '/homeless-shelter'` usually happens when a program tries to write to the `$HOME` directory during the build (`$HOME` is set to `/homeless-shelter` which does not exist, on purpose), which is forbidden.

Found : I edited my project, pass to version 0.9.1 and updated my sha256 hash.

**Comment by jpotier** [comment]
Confirmed, I can now build the project on NixOS with sandboxing enabled. Still I cannot run it, is there some runtime dependencies I should have to test this?

**Comment by jpotier** [comment]
The other binary seems to run fine though:

```sh
$ ./result/bin/gspeech-cli
gSpeech version 0.9.0
Usage : gSpeech-cli -i "[text to read]" ( or -f [txt file] ) -o [.wav filename] ... -l [optional lang]

Common flags:
-h   --help                   show usage information
-v   --version                show version information
-i   --input-text             text to read
-f   --input-file             file to read (supported only plain txt
-o   --output-file            name of the audio output file (wav type)
-l   --lang                   language

possible languages:
de-DE
en-GB
en-US
es-ES
fr-FR
it-IT
```

**Review by jpotier — APPROVED** [review]
LGTM, builds in sandbox, produces valid binaries

**Comment by mothsART** [comment]
> Confirmed, I can now build the project on NixOS with sandboxing enabled. ~Still I cannot run it,~ Binary runs, but fails. Is there some runtime dependencies I should have to test this?
> 
> ```shell
> $ ./result/bin/gspeech
> Traceback (most recent call last):
>   File "/nix/store/2521np3363z8vzk8358lb3mcpsb1pxka-gSpeech-0.9.1/bin/..gspeech-wrapped-wrapped", line 9, in <module>
>     sys.exit(main())
>   File "/nix/store/2521np3363z8vzk8358lb3mcpsb1pxka-gSpeech-0.9.1/lib/python3.7/site-packages/speech/main.py", line 249, in main
>     pid.kill_if_already_exist(conf.app_name, conf.pid)
>   File "/nix/store/2521np3363z8vzk8358lb3mcpsb1pxka-gSpeech-0.9.1/lib/python3.7/site-packages/speech/pid.py", line 23, in kill_if_already_exist
>     with open(pid_path, 'w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/eeva/.cache/gSpeech/gspeech.pid'
> ```

**Comment by mothsART** [comment]
> The other binary seems to run fine though:
> 
> ```shell
> $ ./result/bin/gspeech-cli
> gSpeech version 0.9.0
> Usage : gSpeech-cli -i "[text to read]" ( or -f [txt file] ) -o [.wav filename] ... -l [optional lang]
> 
> Common flags:
> -h   --help                   show usage information
> -v   --version                show version information
> -i   --input-text             text to read
> -f   --input-file             file to read (supported only plain txt
> -o   --output-file            name of the audio output file (wav type)
> -l   --lang                   language
> 
> possible languages:
> de-DE
> en-GB
> en-US
> es-ES
> fr-FR
> it-IT
> ```



> Confirmed, I can now build the project on NixOS with sandboxing enabled. ~Still I cannot run it,~ Binary runs, but fails. Is there some runtime dependencies I should have to test this?
> 
> ```shell
> $ ./result/bin/gspeech
> Traceback (most recent call last):
>   File "/nix/store/2521np3363z8vzk8358lb3mcpsb1pxka-gSpeech-0.9.1/bin/..gspeech-wrapped-wrapped", line 9, in <module>
>     sys.exit(main())
>   File "/nix/store/2521np3363z8vzk8358lb3mcpsb1pxka-gSpeech-0.9.1/lib/python3.7/site-packages/speech/main.py", line 249, in main
>     pid.kill_if_already_exist(conf.app_name, conf.pid)
>   File "/nix/store/2521np3363z8vzk8358lb3mcpsb1pxka-gSpeech-0.9.1/lib/python3.7/site-packages/speech/pid.py", line 23, in kill_if_already_exist
>     with open(pid_path, 'w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/eeva/.cache/gSpeech/gspeech.pid'
> ```

An other application bug (on first launch) ; correction on 0.9.2 version.
Seems fine now.

**Comment by Lassulus** [comment]
running `gspeech-cli -i "hello world"` gives me:
```
sh: pico2wave: command not found
```

**Comment by jpotier** [comment]
This works fine: `nix run nixpkgs.picotts -c ./result/bin/gspeech-cli -i "hello world"`. @mothsART you know better how this package should be used: do you think it should be a self contained unit, or just the frontend?

**Comment by NinjaTrappeur** [comment]
You can use `wrapProgram` to create a wrapper in charge of appending the runtime dependencies in the binary $PATH.

For instance: https://github.com/NixOS/nixpkgs/blob/b67bc34d4e3de1e89b8bb7cd6e375ba44f1ae8ca/pkgs/applications/networking/mailreaders/aerc/default.nix#L41

-----------------------

This package is the fork of a fork of a fork. Is there a particular reason not to upstream your changes? Did you try to at least open a PR?

**Comment by mothsART** [comment]
thanks to all: i use "wrapProgram" now and gspeech is working like a charm.

@NinjaTrappeur : this package is a fork of a fork, i'm aware of it.
Firstable, i've evolved gSpeech because I participate to a french Linux distribution (educative), who's naming Primtux : https://primtux.fr/

Last at least one year, the creator of Gspeech redirect to the fork : https://github.com/tuxmouraille/gSpeech/issues/4#issuecomment-454307959

I've pushed 2 PR to lusum repo, merged by him after a long time but reworked behind without PEP8, an ugly monolitic code...

My goal was to refactor for bring unit and fonctionnal test with CI, flake8 compatibility, add some algorithms and dictionnary to perform tts quality (french tts first), upgrade to python3 and gtk3, adapt for better debian and nix packaging etc.

Doing all of this in upstream would have taken me a lot longer and a lot of uncertainty.
If the project would have been more dynamic, I would probably have acted differently.

**Comment by Lassulus** [comment]
hmm, running `gspeech` does nothing for me. I need to kill it with ctrl+c. What is it supposed to do?

**Comment by mothsART** [comment]
@Lassulus : gspeech launch an application indicator like this https://wiki.primtux.fr/lib/exe/detail.php/wiki:gspeech.png?id=gspeech

**Comment by Lassulus** [comment]
ah, I didn't have a tray, tested it now with stalonetray, everything works fine

**Pull request merged**
