### PR TITLE
pict-rs: 0.3.3 -> 0.4.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adisbladis** [comment]
A package update is easy but the schema migration makes me a bit uncertain how to best approach this.
https://git.asonix.dog/asonix/pict-rs.git#user-content-0-3-to-0-4-migration-guide

cc @asonix

**Comment by asonix** [comment]
The pict-rs module needs to be updated as well since environment variables have changed. Theoretically you could leave the same nix config options and derive the new settings to make upgrades "just work"

**Comment by asonix** [comment]
Specifically,
```nix
    systemd.services.pict-rs = {
      environment = {
        PICTRS__PATH = cfg.dataDir;
        PICTRS__ADDR = "${cfg.address}:${toString cfg.port}";
      };
```
could change to
```nix
    systemd.services.pict-rs = {
      environment = {
        PICTRS__OLD_DB__PATH = cfg.dataDir;
        PICTRS__REPO__PATH = "${cfg.dataDir}/sled-repo";
        PICTRS__STORE__PATH = "${cfg.dataDir}/files";
        PICTRS__SERVER_ADDR = "${cfg.address}:${toString cfg.port}";
      };
```
This would prevent disruption for users on upgrade, but doesn't expose pict-rs full configuration. I think expanding the scope of configuration for pict-rs on nixos is probably best reserved for a different PR

**Comment by adisbladis** [comment]
I've opened https://github.com/NixOS/nixpkgs/pull/243373 instead which tackles the NixOS module too.

**Comment by Mic92** [comment]
Closed in favor of https://github.com/NixOS/nixpkgs/pull/243373

**Pull request closed without merging**
