### PR TITLE
crystal: 0.31 -> 0.34

### PR DESCRIPTION
**Pull request by manveru**
###### Motivation for this change

* Deprecate Crystal versions: 0.27, 0.29, 0.30
* Add Crystal versions: 0.33, 0.34
* Rely only on a single binary Crystal to build the others.
* Update shards to work with 0.34, this might break it for the older ones though.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Sweet, just what I was waiting for!

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build crystal_0_32 crystal_0_33 crystal_0_34

**Comment by peterhoeg** [comment]
Upstream only tests with the 2 latest released versions of llvm, ref https://github.com/crystal-lang/crystal/issues/8725#issuecomment-582592330

We should probably bump llvm in this case (I know that I previously advocated just using our default version) and put a note in there. Any thoughts?

**Comment by manveru** [comment]
@peterhoeg agreed, I saw build issues on darwin using older LLVM as well.

**Comment by peterhoeg** [comment]
This is great. I'll get the New-And-Improved(tm) builder fixed after this and push `lucky-cli`.

**Pull request merged**
