### PR TITLE
taskell: 1.7.3 -> 1.9.3

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by Br1ght0ne — APPROVED** [review]
diff LGTM
executable works

```
[3 built, 78 copied (244.0 MiB), 16.9 MiB DL]
https://github.com/NixOS/nixpkgs/pull/77315
1 package built:
taskell
```

**Comment by dtzWill** [comment]
LGTM! Matches what I put together and have been using, too. :)

**Comment by dtzWill** [comment]
Bummer re:darwin failure (fails to build haskell `tz`, see builder logs), as taskell previously was building successfully: https://hydra.nixos.org/build/109464110 .  Don't know how important this is to Darwin folks but seemed worth mentioning, at least :).

**Review by doronbehar — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
How about merging this PR?

**Comment by filalex77** [comment]
@GrahamcOfBorg build taskell

**Comment by alyssais** [comment]
Should either be fixed or marked as broken on or incompatible with Darwin and aarch64.

**Comment by matthiasbeyer** [comment]
> Should either be fixed or marked as broken on or incompatible with Darwin and aarch64.

How to do that?

**Comment by doronbehar** [comment]
`platforms = [ "x86_64-linux" ];`

**Review by Br1ght0ne — APPROVED** [review]
diff LGTM
```
[3 built, 266 copied (3297.4 MiB), 222.5 MiB DL]
https://github.com/NixOS/nixpkgs/pull/77315
1 package built:
taskell

$ nix-shell /home/brightone/.cache/nixpkgs-review/pr-77315/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-77315]$ taskell test
Create /home/brightone/.cache/nixpkgs-review/pr-77315/test? (Y/n):

**Comment by matthiasbeyer** [comment]
Please merge this.

**Comment by matthiasbeyer** [comment]
Please merge this.

**Pull request merged**
