### PR TITLE
cornelis: init at 2024-04-08

### PR DESCRIPTION
**Pull request by phijor**
## Description of changes

This PR adds a package containing the binary of [Cornelis](https://github.com/isovector/cornelis), which provides editor-integration for Agda in Neovim.

This is a Haskell package, but it is not available on hackage. It therefore includes an update-script to generate the derivation with `cabal2nix`.

The upstream repository includes a Neovim plugin which should be packaged in a future PR.  I personally do not configure Neovim through Nix, so any help with that would be appreciated.

_Edit:_ I packaged a first iteration of the vim plugin.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by phijor** [comment]
@malob, I have seen your contributions to the upstream Nix flake. Would you have the capacity to co-maintain the package here?

**Comment by phijor** [comment]
Result of `nixpkgs-review pr 304335` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cornelis</li>
  </ul>
</details>

**Comment by phijor** [comment]
I've been reading some other PRs adding Haskell packages and have learned that `non-hackage-packages.nix` is a thing. I'll try to add the package there instead.

cc @sternenseemann is there documentation on how to add non-hackage packages?

**Comment by malob** [comment]
I think your derivation can be a lot simpler. This worked for me:
```nix
{ haskellPackages, fetchFromGitHub }:

let
  pname = "cornelis";
  src = fetchFromGitHub {
    owner = "isovector";
    repo = pname;
    rev = "9d3347e7d8589a28bcdd283001367d60bacf6b05";
    hash = "sha256-KaAhKeESwOQ0R0vxeAO/CDPiPimiemoARyr0uIVTQ4w=";
  };
in

haskellPackages.callCabal2nix pname src {}
```

**Comment by malob** [comment]
If you're going to add `cornelis` to `nixpkgs` probably also worth adding the Vim plugin. Something like the following should do it in `pkgs/applications/editors/vim/plugins/overrides.nix`:
```nix
{ lib
[...]
, cornelis
[...]
,
}: self: super:
{
  [...]
  cornelis = buildVimPlugin {
    inherit (cornelis) pname version src;
    dependencies = with super; [ nvim-hs-vim vim-textobj-user ];
  };
  [...]
}
```

**Comment by malob** [comment]
Oh yeah, sure, you can list me as a co-maintainer.

**Comment by phijor** [comment]
> I think your derivation can be a lot simpler. This worked for me:

I think your code performs an _Import From Derivation_, which is [disallowed in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#import-from-derivation). So running `cabal2nix` and committing the generated file is probably the way to go.

> If you're going to add `cornelis` to `nixpkgs` probably also worth adding the Vim plugin. Something like the following should do it in `pkgs/applications/editors/vim/plugins/overrides.nix`:

Ahhh, that's a great suggestion, thank you. I believe in this case we should set `g:cornelis_use_global_binary = 1` and point the plugin to the right binary. Let me figure out how to do that.

> Oh yeah, sure, you can list me as a co-maintainer.

I'll do that!

**Comment by phijor** [comment]
Cornelis is now on [Hackage](https://hackage.haskell.org/package/cornelis). I guess we could wait for the next update to the Haskell package set here and then drop the custom packaging.

**Comment by malob** [comment]
I think waiting for `haskellPackages` update is probably the right call.

**Comment by phijor** [comment]
#307204 includes the package from hackage. Once that’s been merged into master, I’ll rebase and remove the custom packaging.

**Comment by phijor** [comment]
I rebased this on `master` after #307204 got merged. Of course the version of `cornelis` imported from Hackage is broken; 8be493adf288df9878a9c0396ccb0b317003e318 attempts to work around the problem (which has been reported at isovector/cornelis#150).

465ae2d5992534eeac1d90cda289271ab81c97b8 still includes some custom packaging for the top-level package: it sets some `meta` data and minimizes derivation size.

**Review by ncfavier — APPROVED** [review]
Looks good

**Pull request merged**
