### PR TITLE
ollama: 0.3.5 -> 0.3.8

### PR DESCRIPTION
**Pull request by drupol**
Diff: https://github.com/ollama/ollama/compare/v0.3.5...v0.3.8

Changelog: https://github.com/ollama/ollama/releases/tag/v0.3.8

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by abysssol — CHANGES_REQUESTED** [review]
Doesn't build.

The errors look the same as #331585, so it's probably the same problem, though I'm not sure. I don't know what the fix is, or if there is one.

**Comment by tomberek** [comment]
Failure seems to be in the check phase due to not having a GPU to load the relevant models. Not sure how this was handled in the past.

**Comment by mastoca** [comment]
From my attempts, it seems the unit test TestHomogeneousGPUs (in server/sched_test.go) for the ollama-server is failing somehow since 0.3.6 though nothing appears to have changed for the test. The only odd thing I see is the `return` (https://github.com/ollama/ollama/blob/4c4fe3f87fe1858b35bd0d41e093a0039ec4cee4/server/sched_test.go#L689) doesn't have a `nil` but again that's been like that for a while.

**Comment by mastoca** [comment]
I was able to successfuly build **0.3.9** ROCm & CUDA. I can verify cuda which runs/works for me.

Someone else has to test ROCm as I don't have that GPU.

**Pull request closed without merging**
