### PR TITLE
re2: 2024-06-01 -> 2024-07-02

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/google/re2/compare/2024-06-01...2024-07-02

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by azahi** [comment]
Do you think we can remove chromium from passthru tests? ofborg always fails to build it anyway, and forcing ofborg to compile something as big as it is just stealing CPU time that can be used for building stuff that can be verified.

**Comment by trofi** [comment]
FWIW I built `re2.tests` locally successfully on `x86_64-linux`.

It feels like `ofborg` has troubles building anything that touches close-to-stdenv `staging` in general (or when `staging` already has `stdenv` rebuild merged).

`chromium` was added to `tests` in https://github.com/NixOS/nixpkgs/commit/12c1a063bcf4bac7d6b0a629ace59500cb9d52a4 . Maybe @risicle has some thoughts on it's fate.

**Comment by risicle** [comment]
ofborg is generally never going to successfully build anything on the staging branch anyway.

**Comment by risicle** [comment]
I'd be fine if `chromium` were commented out so it could at least serve as a prompt to a human.

But then we run into `haskellPackages.re2`, which presumably requires a ghc build.

It might be worth stopping ofborg from attempting any `passthru.tests` builds on staging at all. Or perhaps having a hard block on specific packages like `chromium`.

**Review by azahi — APPROVED** [review]

**Pull request merged**
