### PR TITLE
wire-desktop: linux 3.12.2916 -> 3.15.2922, mac 3.12.3490 -> 3.15.3621

### PR DESCRIPTION
**Pull request by toonn**
###### Motivation for this change
Bump both mac and linux version of "wire-desktop".
This PR would supersede #82236, which lacked the mac version bump and used an unofficial version number.

Should we switch to SRI hashes?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by arianvp** [comment]
LGTM. We can close the previous PR.

**Comment by turboMaCk** [comment]
Looks good! closing old PR.

**Comment by toonn** [comment]
They made another linux release so this PR has two bumps for linux now. Half expecting another macOS release as well.

**Comment by turboMaCk** [comment]
well that means that now we're in same situation with my original Linux update PR where we decided to wait for update for both platforms.

**Comment by Kiwi** [comment]
for what little it matters now i did test the linux version on nixos briefly and minimally last night and didn't notice anything bad.

**Comment by arianvp** [comment]
The MacOS release will probably be up tomorrow.  Sorry these things do not always perfectly align; because signing and release process differs per platform

**Comment by arianvp** [comment]
MacOS release is now out.

I'll evaluate if I can maybe make a bot that triggers a PR to nixpkgs when our internal CI systems trigger; this means these kind of updates will be less manual in the future.

**Comment by toonn** [comment]
Can't find it on github yet.

Not that these bumps are usually trivial to automate indeed but the current bump for macOS required changing the source URL. Just something to keep in mind.

**Review by flokli — APPROVED** [review]

**Comment by flokli** [comment]
backported to 20.03 in 7730ed9da4d cf77a5fdc18 97d3d1ec7fc

**Pull request merged**
