### PR TITLE
riot-desktop: use yarn2nix-moretea

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

Now that we have yarn2nix-moretea in the tree, we can use that instead of the vendored version that was introduced when yarn2nix was removed previously.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by petabyteboy** [comment]
cc @pacien @worldofpeace

**Comment by pacien** [comment]
Would using `yarn.lock` directly and letting `yarn2nix` generate `yarn.nix` automatically be allowed in nixpkgs? I'm not sure whether it would have an impact on the evaluation time, but it would simplify the maintenance of this package.

**Comment by petabyteboy** [comment]
> Would using `yarn.lock` directly and letting `yarn2nix` generate `yarn.nix` automatically be allowed in nixpkgs? I'm not sure whether it would have an impact on the evaluation time, but it would simplify the maintenance of this package.

It's not possible with Hydra (yet).

**Comment by pacien** [comment]
Ok, I added an update script as well in https://github.com/NixOS/nixpkgs/pull/67528.

**Comment by petabyteboy** [comment]
closing in favor of  #67528

**Pull request closed without merging**
