### PR TITLE
azure-cli: 2.15.1 -> 2.16.0

### PR DESCRIPTION
**Pull request by anhdle14**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

One thing I am not sure about is whether patching `cryptography` to `3.3.1` is the correct way or not. But for pyOpenSSL to compile, `cryptography` must be at least `3.2`. Source here: [CHANGELOG](https://github.com/pyca/pyopenssl/blob/master/CHANGELOG.rst)

### CODE REVIEW

**Comment by jonringer** [comment]
Please follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) and [manual#submitting-changes-making-patches ](https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches) and squash the fix-up commits.

 `git rebase -i` is a powerful command which achieves this, I created a small video demonstrating it's use [here](https://www.youtube.com/watch?v=OR8Q-4PLalc). A more indepth text tutorial can be found [here](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

**Comment by anhdle14** [comment]
@jonringer Thank you for the very informative video, I did what was requested.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 106773 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>azure-cli</li>  </ul></details>

**Comment by jonringer** [comment]
congrats @anhdle14 on your first nixpkgs contribution. Thanks! :)

**Pull request merged**
