### PR TITLE
justbuild: 1.2.1 -> 1.2.2

### PR DESCRIPTION
**Pull request by clkamp**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Ma27 — CHANGES_REQUESTED** [review]
Hash mismatch for me:

```
source> unpacking source archive /build/v1.2.2.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/h9m8ghs2snqx7m39cl14c4lzzzq8h16q-source.drv':
         specified: sha256-R7+R4CYVBpj5fzbjvwMxy0kXJehN7mCQdpWEgW4qCvY=
            got:    sha256-2gW/GCGc1+0znJ1UqoJJ/rTAOciSZGuEymTWgYyrOTk=
```

Perhaps the tag was force-pushed?

**Comment by aehlig** [comment]
> Perhaps the tag was force-pushed?

No, the tag was not modified; it still points to https://github.com/just-buildsystem/justbuild/commit/e1ee04684c34ae30ac3c91b6753e99a81a9dc51c as it always has.

Moreover, the source archive ...
```
/tmp>rm v1.2.2.tar.gz 
/tmp>curl -L --output v1.2.2.tar.gz https://github.com/just-buildsystem/justbuild/archive/refs/tags/v1.2.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  731k    0  731k    0     0   854k      0 --:--:-- --:--:-- --:--:--  854k
/tmp>sha256sum v1.2.2.tar.gz 
6a9c8c9793e9f1ad9f57ac81856c8263929a41a7346d01a4a57df2bb1b33db4e  v1.2.2.tar.gz
/tmp>
```
... still has the same checksum as witnessed by [other](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=justbuild&id=48d34966bd35ffef3d4fc5e09e7ae8b1050d13d4#n15) [distros](https://github.com/void-linux/void-packages/blob/9bffb355062302cd17ca4cc297681d3b6b5c300a/srcpkgs/justbuild/template#L16) shortly after the release.

**Comment by aehlig** [comment]
> @clkamp Maybe the hash was wrong in the first place?

It was wrong, and I can also explain where the wrong hash came from. Readding the `postFetch` ...
```
diff --git a/pkgs/by-name/ju/justbuild/package.nix b/pkgs/by-name/ju/justbuild/package.nix
index 60bd485e601b..b258439e2037 100644
--- a/pkgs/by-name/ju/justbuild/package.nix
+++ b/pkgs/by-name/ju/justbuild/package.nix
@@ -33,6 +33,9 @@ stdenv.mkDerivation rec {
     owner = "just-buildsystem";
     repo = "justbuild";
     rev = "v${version}";
+    postFetch = ''
+      rm -rf $out/test/end-to-end/targets $out/test/end-to-end/TARGETS
+    '';
     sha256 = "sha256-R7+R4CYVBpj5fzbjvwMxy0kXJehN7mCQdpWEgW4qCvY=";
   };
```
... also fixes the build. I guess, @clkamp you _first_ updated the upstream reference and hash, and only _afterwards_ removed the `postFetch` that is no longer needed thanks to https://github.com/just-buildsystem/justbuild/commit/302c994ba3342a3227178ab9e86704bfdff29ffc

Now that we understand where die difference in the hashes came from (and that nothing suspicious is going on), I suggest to simply update the hash to the reported one, i.e., `sha256-2gW/GCGc1+0znJ1UqoJJ/rTAOciSZGuEymTWgYyrOTk=`. @clkamp @Ma27 what do you think?

**Comment by aehlig** [comment]
> @clkamp Maybe the hash was wrong in the first place?

It was wrong, and I can also explain where the wrong hash came from. Readding the `postFetch` ...
```
diff --git a/pkgs/by-name/ju/justbuild/package.nix b/pkgs/by-name/ju/justbuild/package.nix
index 60bd485e601b..b258439e2037 100644
--- a/pkgs/by-name/ju/justbuild/package.nix
+++ b/pkgs/by-name/ju/justbuild/package.nix
@@ -33,6 +33,9 @@ stdenv.mkDerivation rec {
     owner = "just-buildsystem";
     repo = "justbuild";
     rev = "v${version}";
+    postFetch = ''
+      rm -rf $out/test/end-to-end/targets $out/test/end-to-end/TARGETS
+    '';
     sha256 = "sha256-R7+R4CYVBpj5fzbjvwMxy0kXJehN7mCQdpWEgW4qCvY=";
   };
```
... also fixes the build. I guess, @clkamp you _first_ updated the upstream reference and hash, and only _afterwards_ removed the `postFetch` that is no longer needed thanks to https://github.com/just-buildsystem/justbuild/commit/302c994ba3342a3227178ab9e86704bfdff29ffc

Now that we understand where die difference in the hashes came from (and that nothing suspicious is going on), I suggest to simply update the hash to the reported one, i.e., `sha256-2gW/GCGc1+0znJ1UqoJJ/rTAOciSZGuEymTWgYyrOTk=`. @clkamp @Ma27 what do you think?

**Comment by aehlig** [comment]
Nevertheless, I could reconstruct the very same error that @Ma27 reported (with the same obtained hash).
```
trying https://github.com/just-buildsystem/justbuild/archive/v1.2.2.tar.gz
copying path '/nix/store/h8d2j0prdf7pnpgyrgkxrrbfwnmxbq6y-binutils-wrapper-2.40' from 'https://cache.nixos.org'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  731k    0  731k    0     0   579k      0 --:--:--  0:00:01 --:--:-- 2532k
unpacking source archive /build/v1.2.2.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/h9m8ghs2snqx7m39cl14c4lzzzq8h16q-source.drv':
         specified: sha256-R7+R4CYVBpj5fzbjvwMxy0kXJehN7mCQdpWEgW4qCvY=
            got:    sha256-2gW/GCGc1+0znJ1UqoJJ/rTAOciSZGuEymTWgYyrOTk=
error: 1 dependencies of derivation '/nix/store/2ybvmq2dn7df5zrdq0cksv532ip2mlh8-justbuild-1.2.2.drv' failed to build
```

Following the fetch, `curl -Lv --output /tmp/v1.2.2.tar.gz https://github.com/just-buildsystem/justbuild/archive/v1.2.2.tar.gz` shows a redirect to `https://codeload.github.com/just-buildsystem/justbuild/tar.gz/refs/tags/v1.2.2` and there the file is served with `content-disposition: attachment; filename=justbuild-1.2.2.tar.gz`. This content disposition is new, as far as I remember; however, I don't see how this should influence the resulting hash. Nevertheless, when I manually change the hash to the reported one, I can successfully build and get a working `just` binary. @clkamp Maybe the hash was wrong in the first place?

**Comment by clkamp** [comment]
Thanks for catching this, what @aehlig pointed out was exactly what happened. Sorry for the noise.

**Comment by clkamp** [comment]
Superseded by #278751

**Pull request closed without merging**
