### PR TITLE
pcl: 1.8.1 -> 1.9.1

### LINKED ISSUE #51573: Updated to pcl 1.9.1
## Issue description

[pcl](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/pcl/default.nix) is in need of an update.

https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.9.1

### PR DESCRIPTION
**Pull request by luzpaz**
https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.9.1  
Closes #51573

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build pcl

**Review by xeji — CHANGES_REQUESTED** [review]
fix hash mismatch

**Comment by luzpaz** [comment]
> fix hash mismatch

Please fix this, not able to at this time.

**Comment by cpages** [comment]
Fixed in master, thanks

**Pull request closed without merging**
