### PR TITLE
gex: 0.6.3. -> 0.6.4

### PR DESCRIPTION
**Pull request by evanrichter**
## Description of changes

[upstream release notes
](https://github.com/Piturnah/gex/releases/tag/v0.6.4)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by evanrichter** [comment]
Result of `nixpkgs-review pr 267275` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gex</li>
  </ul>
</details>

**Comment by evanrichter** [comment]
failed build on (aarch64-)darwin, need to add some frameworks, starting with Security

**Comment by evanrichter** [comment]
ok darwin build just needed Security:

1 package built:
gex

Result of `nixpkgs-review pr 267275` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gex</li>
  </ul>
</details>

**Comment by evanrichter** [comment]
ready for review @Azd325 and @Piturnah :)

**Review by Azd325 — APPROVED** [review]

**Comment by Azd325** [comment]
@evanrichter Btw do we need still `libgit2_1_6` in the `builtinputs`. It seems that we use the `libgit` from cargo with an higher version.

**Comment by evanrichter** [comment]
> @evanrichter Btw do we need still `libgit2_1_6` in the `builtinputs`. It seems that we use the `libgit` from cargo with an higher version.

hm, it does build and run without this input. But I think this means that libgit2-sys has decided to use it's own copy of libgit2 sources. I updated the derivation to force libgit2-sys to use the system (nixpkgs) copy of libgit2 using an environment variable. I verified that the build.rs script fails now when libgit2 is not provided.

also libgit2_1_6 is now a too old version, so I bumped it to libgit2 (1.7.1 currently)

**Comment by evanrichter** [comment]
`nixpkgs-review pr 267275` re-confirmed on aarch64-darwin and x86_64-linux

**Review by Azd325 — APPROVED** [review]

**Review by Piturnah — APPROVED** [review]

**Comment by evanrichter** [comment]
just in the nick of time!! 😆

image

**Pull request merged**
