### PR TITLE
nixos/nsd: symlink conf file to /etc/nsd

### PR DESCRIPTION
**Pull request by picnoir**
###### Motivation for this change

```
We remove the configFile build flag override in the NixOS module.

Instead of embedding the conf file link to the binaries, we symlink it
to /etc/nsd/nsd.nix, the hardcoded config file location for the
various CLI nsd utilities.

This config file build option override is triggerring a nsd rebuild
for each configuration change. This prevent us to use the nixos cache
in many cases.
```

@hrdinka, I see you wrote that particular part. I know it was a long time ago, but I feel like I might be missing some context and do something stupid here. Would you happen to remember what led you to add this override?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hrdinka** [comment]
@NinjaTrappeur Yea, this needs a change. The reason for this is that all nsd binaries installed on the system (like `nsd-control`) need access to the config file to work. Back than I did not want to further clutter `/etc` but today this might be the better solution: Either symlink the config file to `/etc/nsd/nsd.conf` (better compatibilty) or maybe symlink it to nsd’s `stateDir` (like other services do it; better for NixOS users and worse for others) and use this path for the config file in the derivation. I am in favor of symlinking it to `/etc`. Just let me know if you are going to do the change or if I should do it.

**Comment by NinjaTrappeur** [comment]
Aha! I did not think about `nsd-control`.

Ok, sounds good. We're already symlinking the zones files to `/etc/nsd/` anyways.

>  Just let me know if you are going to do the change or if I should do it.

I won't be available until tonight (CEST time). If you can do it earlier, be my guest, I'll be happy to review it. If you go ahead, it'll probably a good idea to cherry-pick 9501883 at the same time.

I'm using NSD on my router, needless to say the current un-cached situation is a bit annoying to me, I'd like to fix that pretty quick!

**Comment by NinjaTrappeur** [comment]
Just updated the PR. We're now creating a symlink to `/etc/nsd/nsd.conf`.

**Comment by hrdinka** [comment]
Great, thanks a lot for your changes! One last request since you are already on it. The default config file path is wrong in the derivation. It’s missing the leading `/`, please be so kind and add it :smiley::

https://github.com/NixOS/nixpkgs/pull/91514/files#diff-a172753a317033e33503641d094d3636R14

**Comment by NinjaTrappeur** [comment]
Aha, indeed. Good catch.

Updated.

**Comment by hrdinka** [comment]
Thanks for all the changes :+1:

**Pull request merged**
