### PR TITLE
[RFC] types.listOf: actually validate the contents

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

This is a footgun. Remove the footgun. I solemnly swear to do my best to deal with the inevitable fallout.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
This will probably break things. Things that are broken by this probably deserve it.

**Comment by Deep-Six** [comment]
@K900  thanks for resolving this! It was driving me mad!

**Comment by K900** [comment]
For context, @Deep-Six was hitting a completely inscrutable error after doing `environment.systemPackages = [ pkgs.rust ]`, with `pkgs.rust` being a random attribute set of assorted Rust stuffs and _not_ a package.

**Comment by K900** [comment]
The comment saying check-meta should be enabled "soon" is from 2017... Right now I've enabled it just to see more things fail (or not?), but maybe it should stay that way?

CC @copumpkin who wrote the original comment all those years ago.

**Comment by K900** [comment]
OK, so it turns out the validation _does_ work correctly here, the problem is with `toPretty` specifically exploding when passed `pkgs.rust` for ... whatever reason?

**Comment by roberth** [comment]
`toPretty` probably fails miserably on data structures that involve repetition and recursive references. Maybe that's what happened?

In error messages, we shouldn't enter more than two layers of attrsets and/or lists, to avoid infinite recursions and to avoid some unnecessarily large messages.

**Comment by K900** [comment]
Yes, that is what happened. I've submitted a fix (ish) for toPretty in #168327

**Pull request closed without merging**
