### PR TITLE
nixos/{sudo,-rs}: revert sudo-rs, make own module

### PR DESCRIPTION
**Pull request by mkg20001**
## Description of changes

This reverts the module changes that were added by the addition of sudo-rs from the sudo module.

This also adds a new sudo-rs module that contains those changes, available as security.sudo-rs, alongside modified tests and adjusted release notes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bendlas — CHANGES_REQUESTED** [review]
I think this direction is a lot more productive than the "quick! merge it before it bitrots" approach that we saw in https://github.com/NixOS/nixpkgs/pull/253876, good.

However, I'm wondering what happened to the manual changes: Comparing https://github.com/NixOS/nixpkgs/pull/256472/files#diff-3aa4af7420bc171f80cd8160cba96b688adbb702eb283f20e86cc4d2d81df42a with this, it looks like this PR may still have the (now wrong) updates to the nixos manual. But it's hard to tell because we're mixing revert and replacement here.

So I'm wondering if it wouldn't make more sense to rebase this on https://github.com/NixOS/nixpkgs/pull/256472, if only to get a cleaner diff for review. But at the very least, this PR should probably also update the nixos manual.

**Review by RaitoBezarius — DISMISSED** [review]
Ensure all commit messages have a body and please insert a PR body to explain a summary of your changes.

**Review by RaitoBezarius — CHANGES_REQUESTED** [review]
Ensure all commit messages have a body and please insert a PR body to explain a summary of your changes.

**Comment by mkg20001** [comment]
@ofborg test sudo sudo-rs

**Comment by mkg20001** [comment]
Given that this sudo-rs module contains both sudo and sudo-rs support, would it make sense to name it sudo-experimental or sudo-exp for short and use that as a sort of testing ground for sudo-related changes? This might also prove useful in the future, for example to try alternatives to SETENV (which is arround to allow user-profile binaries to be ran via sudo)

**Comment by RaitoBezarius** [comment]
> Given that this sudo-rs module contains both sudo and sudo-rs support, would it make sense to name it sudo-experimental or sudo-exp for short and use that as a sort of testing ground for sudo-related changes? This might also prove useful in the future, for example to try alternatives to SETENV (which is arround to allow user-profile binaries to be ran via sudo)

No, I think it should be named `sudo-rs` as it is clearly the module for the Rust reimplementation of sudo.

If we want a `sudo-experimental`, the changes should be done in an experimental branch on the sudo module IMHO. Because they will be anyway sent to the sudo maintainer at some point so…

**Review by RaitoBezarius — CHANGES_REQUESTED** [review]
Please be precise about commit SHA1 and original commit title when you mention revert of something.

The goal is to provide useful information for anyone checking stuff and not having to search for the right commit, especially when the revert is not a standard `git revert` of an atomic commit.

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 256491` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 tests built:</summary>
  <ul>
    <li>nixosTests.sudo</li>
    <li>nixosTests.sudo-rs</li>
  </ul>
</details>

**Review by RaitoBezarius — APPROVED** [review]

**Comment by mkg20001** [comment]
can i merge this now?

**Comment by RaitoBezarius** [comment]
No, please wait for additional feedback, I have asked in the dev room.

**Review by delroth — APPROVED** [review]
Approving the changes to the `sudo` module, no opinion on `sudo-rs` and I have not fully reviewed that (new) module code.

**Review by bendlas — APPROVED** [review]
Manual update was addressed

**Comment by RaitoBezarius** [comment]
@nbraud If you can stamp the `sudo-rs` part, it would be nice, I would prefer to avoid us merging something you do not agree with.

**Comment by Artturin** [comment]
Either of the PRs have to be merged ASAP https://github.com/NixOS/nixpkgs/issues/256713

**Comment by bendlas** [comment]
For the record, I'm still in favor of outright reverting the original change as per https://github.com/NixOS/nixpkgs/pull/256472, and rebasing this so that we have enough time to build consensus around this change.

But since consensus already seems to be forming around this PR, I'm also fine with merging this.

Whatever we do, we'll need to act fast, when the regressions are already starting. So I suggest we merge this with or without @nbraud's approval, @mkg20001 @RaitoBezarius 

I'll wait for activity on this PR for a couple of hours, otherwise, I'll commit the outright revert from https://github.com/NixOS/nixpkgs/pull/256472 in the evening in a few hours, since that seems a little more low-risk.

**Comment by RaitoBezarius** [comment]
@mkg20001 It is really unfortunate that you merged this again when I explicitly wrote that we need to wait approval from @nbraud as they are mentioned as maintainers, and I am not sure they agreed on this.

**Comment by RaitoBezarius** [comment]
It has been brought to me that this PR caused issues again because it prevents evaluation of NixOS systems.

See https://buildkite.com/tvl/depot/builds/26764#018acc79-bb62-4dc3-856f-9cad3f64ec9b — I don't know yet what is the root cause as I am busy.

**Comment by delroth** [comment]
> It has been brought to me that this PR caused issues again because it prevents evaluation of NixOS systems.

From correlating the line numbers, I think the evaluation you linked is from a nixpkgs version before this was merged. Could you double check?

**Comment by RaitoBezarius** [comment]
Right, they are at e35dcc04a3853da485a396bdd332217d0ac9054f I think, which is 2 commits before the fix. My bad, I think it's indeed related *before* this was merged.

@flokli is checking.

**Comment by RaitoBezarius** [comment]
Apologies my brain farted, this commit fixed it.

**Comment by bendlas** [comment]
> @mkg20001 It is really unfortunate that you merged this again when I explicitly wrote that we need to wait approval from @nbraud as they are mentioned as maintainers, and I am not sure they agreed on this.

I agree. The more I'm looking at this, the more I regret not just straight having pushed the button on @RaitoBezarius' revert and having this PR rebased, and instead giving @mkg20001 the option to cave to the pressure in a way that again disrespects both a reviewer's as well as a contributor's time and commitment :disappointed:

Looking back at the original PRs, I also regret directing a lot of my talking-to at you, @nbraud, when you clearly made good efforts at letting yourself be directed, and relying on face-value communication. As just a contributor you're not expected to be aware of all the nuances of coordination within the NixOS org (like the module being maintained by the pkg maintainers). If a NixOS member, in this case @mkg20001, helps you with your PR outside of their area of responsibility, it falls upon them to ensure the necessary consensus is built before pushing anything. So, @nbraud, I'd like to offer my apology for (what I assume to be) your initial contribution experience with NixOS. And I hope you'll consider contributing again in the future.

**Pull request merged**
