### PR TITLE
chromium: 85.0.4183.121 -> 86.0.4240.75

### PR DESCRIPTION
**Pull request by primeos**
###### Testing status

| platform | attribute | status | tester |
| --- | --- | --- | --- |
| x86_64 | chromium | :heavy_check_mark: | @danielfullmer |
| x86_64 | nixosTests.chromium | :heavy_check_mark: | @danielfullmer  |
| x86_64 | google-chrome | | @primeos |
| aarch64 | chromium | | @thefloweringash |

@thefloweringash this one should be especially interesting to test on AArch64 due to the switch to LLVM 11 (no final release yet, currently at RC 6). Hope this won't cause any issues...

Note to self: I'll likely have to change the implementation of `enableVaapi` in the wrapper IIRC (Linux should now have a feature flag to enable it instead of disabling it - which is very nice). Not sure if I can take care of that before merging this PR due to the lack of build resources (help is welcome if someone is interested).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danielfullmer** [comment]
Briefly tested `chromium` and `nixosTests.chromium` working on `x86_64-linux`.

**Comment by TredwellGit** [comment]
Tested `chromium` on x86_64 NixOS.

I got system FFmpeg 4, libjpeg, and zlib working with this. Will submit pull request after this one is merged.

**Comment by primeos** [comment]
Ok, so according to CI AArch64 should likely be fine.
I forgot to test Chrome but both M86 and M87 from the beta and dev channels where fine a few weeks ago.

M86 has (AFAIK unintentionally) enabled VA-API by default and I'll open another PR to disable it by default as before.

@TredwellGit thanks again for the ANGLE patch and for your testing :)

**Comment by thefloweringash** [comment]
Sorry I'm a bit late. Built `chromium` and `nixos/tests/chromium.nix -A stable` on `aarch64-linux`.

**Pull request merged**
