### PR TITLE
qtwebengine: fix build for darwin

### LINKED ISSUE #76715: qtbase is broken on macOS again
Full log:

https://gist.github.com/dhess/eccf0b973e7f632935a16b14c606fe45

Error message:

```
Done running configuration tests.

Configure summary:

Qt WebEngine:
  Embedded build ......................... no
  Full debug information ................. no
  Pepper Plugins ......................... yes
  Printing and PDF ....................... yes
  Proprietary Codecs ..................... yes
  Spellchecker ........................... yes
  Native Spellchecker .................... no
  WebRTC ................................. yes
  Use System Ninja ....................... yes
  Geolocation ............................ yes
  WebChannel support ..................... yes
  Use v8 snapshot ........................ yes
  Kerberos Authentication ................ no
  Support qpa-xcb ........................ no
  Use ALSA ............................... no
  Use PulseAudio ......................... no
  Clang version .......................... clang version 7.1.0 (tags/RELEASE_710/final)
  macOS minimum deployment target ........ 10.12
  Optional system libraries used:
    re2 .................................. no
    icu .................................. no
    libwebp, libwebpmux and libwebpdemux . yes
    opus ................................. yes
    ffmpeg ............................... no
    libvpx ............................... no
    snappy ............................... no
    glib ................................. no
    zlib ................................. yes
    minizip .............................. no
    libevent ............................. yes
    jsoncpp .............................. no
    protobuf ............................. no
    libxml2 and libxslt .................. no
    lcms2 ................................ no
    png .................................. no
    JPEG ................................. yes
    harfbuzz ............................. yes
    freetype ............................. no

Qt is now configured for building. Just run 'make'.
Once everything is built, you must run 'make install'.
Qt will be installed into '/nix/store/8vrf5yxh1lbfcnnjiqxyigl91m46p9fg-qtbase-5.12.6'.

Prior to reconfiguration, make sure you remove any leftovers from
the previous build.

Project ERROR:
Could not resolve SDK product version for 'macosx'.

builder for '/nix/store/9d41zz8sscxpx16k34q6nw3fynwmmqnl-qtwebengine-5.12.6.drv' failed with exit code 3
```

That's the result I get from my macOS remote builder. 

When I run the build on my desktop Mac, it builds fine and uses the impure SDK from my Catalina install (10.15.1):

```
Done running configuration tests.

Configure summary:

Qt WebEngine:
  Embedded build ......................... no
  Full debug information ................. no
  Pepper Plugins ......................... yes
  Printing and PDF ....................... yes
  Proprietary Codecs ..................... yes
  Spellchecker ........................... yes
  Native Spellchecker .................... no
  WebRTC ................................. yes
  Use System Ninja ....................... yes
  Geolocation ............................ yes
  WebChannel support ..................... yes
  Use v8 snapshot ........................ yes
  Kerberos Authentication ................ no
  Support qpa-xcb ........................ no
  Use ALSA ............................... no
  Use PulseAudio ......................... no
  Clang version .......................... clang version 7.1.0 (tags/RELEASE_710/final)
  macOS SDK version ...................... 10.15.1
  macOS minimum deployment target ........ 10.12
  Optional system libraries used:
    re2 .................................. no
    icu .................................. no
    libwebp, libwebpmux and libwebpdemux . yes
    opus ................................. yes
    ffmpeg ............................... no
    libvpx ............................... no
    snappy ............................... no
    glib ................................. no
    zlib ................................. yes
    minizip .............................. no
    libevent ............................. yes
    jsoncpp .............................. no
    protobuf ............................. no
    libxml2 and libxslt .................. no
    lcms2 ................................ no
    png .................................. no
    JPEG ................................. yes
    harfbuzz ............................. yes
    freetype ............................. no

Qt is now configured for building. Just run 'make'.
Once everything is built, you must run 'make install'.
Qt will be installed into '/nix/store/8vrf5yxh1lbfcnnjiqxyigl91m46p9fg-qtbase-5.12.6'.

Prior to reconfiguration, make sure you remove any leftovers from
the previous build.
```

However, the local build displays this warning repeatedly:

```
/nix/store/np30qrnfzyxvqablwl6nj42m7f41bpdw-qtbase-5.12.6-dev/mkspecs/features/mac/default_post.prf:5: 'xcodeSDKInfo' is not a recognized replace function.
```

I assume this is related to the `qtbase` macOS patches and hopefully gives some clue as to why it's broken.

### LINKED ISSUE #86949: QT Webengine fails to compile on MacOS
### Bug Description

The `qtwebengine` component of the `qt5Full` derivation fails to compile on MacOS.
But in two ways, and I can't tell what causes one or the other to trigger.

#### 1st Way
```
/nix/store/4p3bds5cknzwg72np1rzyn3jq0962z84-bash-4.4-p23/bin/bash:
  ../../../../../../../nix/store/1ngwf6wvh9hf1vz3h2h5znqi90fa86q1-clang-wrapper-7.1.0/bin/clang++:
  No such file or directory
```
On command: https://gist.github.com/jakubgs/7e2dceb9f3a9d454cec2d9affd662107

#### 2nd Way
```
/bin/sh: ../../../../../../../nix/store/1ngwf6wvh9hf1vz3h2h5znqi90fa86q1-clang-wrapper-7.1.0/bin/clang:
  /nix/store/4p3bds5cknzwg72np1rzyn3jq0962z84-bash-4.4-p23/bin/bash:
  bad interpreter: No such file or directory
```
On command: https://gist.github.com/jakubgs/e6d02a8277cabd283c36457d59055b86

### Steps to Reproduce

1. Use the `unstable` channel
2. Run `nix-env -iA nixpkgs.qt5Full`
3. See compilation failure

### Expected behavior
Compiles.

### Notify maintainers
@matthewbauer 

### Metadata
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(jenkins): `"nixpkgs-20.09pre221814.10100a97c89"`
 - nixpkgs: `/Users/jenkins/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by eqyiel**
###### Motivation for this change

I want to use software on macOS that depends on this, like Anki.

Resolves https://github.com/NixOS/nixpkgs/issues/76715
Resolves https://github.com/NixOS/nixpkgs/issues/86949

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JJJollyjim** [comment]
Testing now (the build takes a while :)

**Review by veprbl — APPROVED** [review]
nixpkgs-review on x86_64-darwin
```
15 package marked as broken and skipped:
ankisyncd deepin.qt5integration deepin.qt5platform-plugins melonDS nmon pysolfc qsynth qt-mobility qt-video-wlr qt3 qt4 qt5ct qtads quvi quvi_scripts

20 package failed to build:
anki mellowplayer merkaartor mnemosyne nmapsi4 plex-media-player python-qt python27Packages.pyside2 python27Packages.pyside2-tools python37Packages.pyside2 python37Packages.pyside2-tools python38Packages.pyside2 python38Packages.pyside2-tools qsyncthingtray qt5.full qt514.full qt514.qtwebengine qt514.qtwebview qutebrowser sl1-to-photon

7 package built:
ghostwriter python27Packages.pyqtwebengine python37Packages.pyqtwebengine python38Packages.pyqtwebengine qt5.qtwebengine qt5.qtwebview webmacs
```

**Comment by eqyiel** [comment]
@veprbl sorry, I must have used the wrong `nixpkgs` checkout at that time because when I double checked, it builds fine. #96130

**Comment by sikmir** [comment]
Build failed for me with:
```
$ nix-build -A qt5.qtwebengine
...
Using Xcode version , but at least version 8.3.3 is required to build Qt WebEngine.
QtWebEngine will not be built.
...
```
But I have Xcode 10.1:
```
$ xcodebuild -version
Xcode 10.1
Build version 10B61
```
What is going wrong?

**Pull request merged**
