### PR TITLE
nixos/httpd: remove unnecessary sendmail configuration

### PR DESCRIPTION
**Pull request by sugar700**
PHP now uses system-sendmail without special configuration (see https://github.com/NixOS/nixpkgs/pull/95898).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — APPROVED** [review]

**Comment by aanderse** [comment]
Looks like https://github.com/NixOS/nixpkgs/blob/730751e73136c372b8e64617a6e49dc9752640a0/nixos/modules/services/web-servers/phpfpm/default.nix#L30 can be cleaned up a bit too. @xfix - are you interested in tackling that?

**Comment by aanderse** [comment]
ping @NixOS/php

**Comment by aanderse** [comment]
@GrahamcOfBorg test php.fpm php.httpd

**Review by etu — APPROVED** [review]

**Comment by aanderse** [comment]
Thanks @xfix!

**Pull request merged**
