### PR TITLE
lm_sensors: add fancontrol module

### PR DESCRIPTION
**Pull request by zopieux**
###### Motivation for this change

lm_sensors package provides a `fancontrol` script that regularly checks temperature sensors and adapts fan speeds according to a config file. This PR adds a `fancontrol` module to enable that feature.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions (Arch)
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by delroth — COMMENTED** [review]
Isn't this a duplicate of https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/fancontrol.nix ?

**Comment by Zopieux** [comment]
Hah, indeed, fun timing. Do you still want to cherry-pick the test or is this too trivial?

**Comment by Evils-Devils** [comment]
aside from mine being in config.hardware and linking to pwmconfig's man page (as suggested in #69398), and explicitly mentioning the need for config in the mkEnableOption (the process of setting up fancontrol is too much yak shaving to not have that in there IMO)
yours looks more polished (i was considering writing a test for this to learn about them xD)
i'm also not sure the default value for config couldn't be `buildins.readFile /etc/fancontrol` since that's where pwmconfig defaults to... (though i agree it shouldn't do that in nixos)

**Comment by Evils-Devils** [comment]
i merged our work [here](https://github.com/Evils-Devils/nixpkgs/commit/5829a0ad9f5b65562d01c38c8fb594208b2df250).

defaulting to null will result in an explicit failure if no config is given
(it'd be nice if it did the same for an empty string...)
enable will now show as "whether to enable software fan control"
systemd will now say "Started software fan control."

i'm not sure about the `after = ["lm_sensors.service" ];` line, there is no such module
i'd also love a way to make the man pages available to the user since we're referring to them...

**Comment by Zopieux** [comment]
@Evils-Devils Thanks for merging in my work! Do you intend to submit the updated version soonish, so I can close that PR?

**Comment by Evils-Devils** [comment]
@Zopieux i'll do so if you want that
though i was thinking you could `git reset --hard` your branch to mine if you like the changes

**Comment by Zopieux** [comment]
Thanks!

**Pull request closed without merging**
