### PR TITLE
abseil-cpp_202401: init at 20240116.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Add the [latest version of abseil-cpp](https://github.com/abseil/abseil-cpp/releases/tag/20240116.0).

cc @andersk 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 283956` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>abseil-cpp_202401</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 283956` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>abseil-cpp_202401</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 283956` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>abseil-cpp_202401</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 283956` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>abseil-cpp_202401</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> I assume it isn't compatible with the most recent version we already have and we cannot just update that like in the past?

I wanted to do this in two steps:
- Just add the package
- set [`abseil-cpp = abseil-cpp_202401` in `all-packages.nix`](https://github.com/NixOS/nixpkgs/blob/e78f177a8a7a79d6c7e1fcfe509901e87658ec63/pkgs/top-level/all-packages.nix#L20454) (targetting `staging`)

**Comment by SuperSandro2000** [comment]
Hmm, if you can't test this locally because of the low cache hits on staging, you could do a rebase to the merge base of master and staging, which could be cached a lot better.

**Comment by GaetanLepage** [comment]
@SuperSandro2000 cache misses is not a problem for me as I have the hardware to build the big tree anyway.
This PR now targets `staging`.

**Comment by jonringer** [comment]
If you wanted to expedite this, you could cherry-pick 2dd67a80d8bc7a2881ec1e81faa33dac22357312 to master...

**Comment by GaetanLepage** [comment]
> If you wanted to expedite this, you could cherry-pick [2dd67a8](https://github.com/NixOS/nixpkgs/commit/2dd67a80d8bc7a2881ec1e81faa33dac22357312) to a PR against master...

This is exactly what I had done until 10 minutes ago haha !
I thought that @SuperSandro2000 was suggesting to directly target `staging`.

@jonringer what about adding `abseil-cpp_202401` in `master` right now and creating a separate PR targeting `staging` to do `abseil-cpp = abseil-cpp_202401` ?

**Comment by GaetanLepage** [comment]
@jonringer done, it is now targetting `master` again and only adds `abseil-cpp_202401`.
Will do the change of version in another PR targetting `staging`.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 283956` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>abseil-cpp_202401</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
The CI encourages to init this as a `pkgs/by-name` package.
What do you think ? It is not like the random "new package" that one would add. It has to follow the same structure as the previous releases.
Should I move it to `pkgs/by-name` ?

**Comment by vcunat** [comment]
I don't think that's needed in this PR.  Maybe move all of them at some point.

I'm not 100% sure about putting @andersk into `.meta.maintainers` of this new version unless they say OK.

**Comment by GaetanLepage** [comment]
> I don't think that's needed in this PR. Maybe move all of them at some point.

Ok, I'll do a follow-up PR.



> I'm not 100% sure about putting @andersk into `.meta.maintainers` of this new version unless they say OK.

I have set myself as the only maintainer.

**Comment by infinisil** [comment]
CI _can_ be ignored for that specific check, especially now that I'm still ironing out some bugs. However it would be better if CI was fully green, so doing such refactorings before adding new versions of packages.

**Pull request merged**
