### PR TITLE
WIP: Emacs Packages

### PR DESCRIPTION
**Pull request by ttuegel**
This is a WIP/preview of my (second) attempt at automatically generating our Emacs packages. This contains all of ELPA and MELPA unstable. This time, the packages are built from stable sources, so we won't have the problem of mysteriously disappearing packages!

Brave Emacs users: please test your favorite packages and report here if I've broken them! My branch is based on the latest `nixos-unstable` channel, so testing should require minimal rebuilding.

TODO:
- Stable MELPA packages
- Maintainer scripts to automatically regenerate versions and hashes

### CODE REVIEW

**Comment by jagajaga** [comment]
:+1:

**Comment by bendlas** [comment]
Great, looking forward to get this into `nixpkgs`. Currently merges fine with https://github.com/NixOS/nixpkgs/pull/7892 too. There are a couple of issues I noticed:

## yasnippet
```
output path ‘/nix/store/4m8pcf3s6a4krr5q76q7hgnqbb94gvv3-yasnippet-197db9f’ should have r:sha256 hash ‘1hsdf8fg1agbb8x19wygniv3s0lvli4gdh0zq122pxib6snnhlbd’, instead has ‘08xnjispslszv837fkqxhsj9sga276q7m2bmgn8rinjakk4q8ia7’
```
Hope this is not yet another case of silent package update.

## ido-completing-read+
The `+` prevents `with pkgs.emacsPackages; [ ido-completing-read+ ]`. `with pkgs.emacsPackages; [ "ido-completing-read+" ]` doesn't work either. No fault in the PR, but maybe a mangled name could be additionally provided, for convenience.

## marmalade
I'm using a couple of marmalade packages. Probably not within the scope of this PR, but mentioning for completeness
- `clojurescript-mode`
- `cljdoc`
- `hippie-expand-haskell`
- `slime-js`

**Comment by ttuegel** [comment]
> Hope this is not yet another case of silent package update.

No, this is yet another problem with the HTTP client library I'm using. The lesson is, "shell out to curl". :)

> The + prevents with pkgs.emacsPackages; [ ido-completing-read+ ]. with pkgs.emacsPackages; [ "ido-completing-read+" ] doesn't work either. No fault in the PR, but maybe a mangled name could be additionally provided, for convenience.

I already mangle package names with `@` in them (`@` -> `at`). I forgot some of the package names have `+`; I'll just add the same sort of mangling rule.

> I'm using a couple of marmalade packages. Probably not within the scope of this PR, but mentioning for completeness

Unfortunately, I can't track Marmalade. In order to have reproducible builds, I need the package repository to either keep old versions or point to the upstream source. ELPA does the former and MELPA does the latter. Marmalade does neither; packagers just upload tarballs ad-hoc, so there will never be a way for me to package Marmalade. (At least, not without falling prey to the silent update problem again.) This PR doesn't interfere with installing Marmalade packages through Emacs as usual, though. I also kept all the packages from Nixpkgs that weren't in MELPA, but in the long-term I think we should pressure maintainers to get their packages on MELPA (lower maintenance cost for us).

**Comment by oxij** [comment]
@ttuegel I don't oppose the idea, but this is too radical yet.

* a2fa94289c90ff81e77dfd943f51057d74c7803a is absolutely okay.
* 14c350791775d0cbf605fa73cf09e1936ee8f586 does too much at once. It will conflict with every single change to `emacs-packages.nix` in master. It is hard to write a nice structured list of problems for a unstructed blob, but I will try.

Here it goes.

* Even if it does not remove any package, did you try to build and run all of those that migrated? Currently even (kinda old) `emacsPackages` is not a subset of (kinda new) `emacsPackagesNg` (and vice versa) because when we did that I felt like I lacked expertise to use (that is, test) even half of `emacsPackages`. And people will get angry when their favorite package disappears or breaks.
* Builders like `melpaPackage` and `elpaPackage` should live in their own files in `bulid-support`. They are big enough for this.
* `defaultOverrides` part is ugly. I think we should strive for a design similar to `python-packages.nix` and `python-packages-generated.nix` or even `haskellPackagesNg` with it's per-compiler config (because it would be nice to support various Emacs versions and XEmacs).
* The following pattern is ugly and useless:

~~~~
  ghc-mod =
     let drv = { mkDerivation, ghc-mod, stdenv }:
        mkDerivation rec { ... };
     in callPackage drv { ... };
~~~~

Why generate a function and then use `callPackage` when you can reference all the dependencies directly with self/super trick?
* Preferably, one should generalize `melpaBuild` with that awesome `build-package-from-recipe` thing. There's basically one word difference between the files, why copy-paste?
* Is there a good reason why is that huge json is split into `packages` and `recipes` inside? This will make things complicated on updates, because every packages update in that json will be split into two patch hunks and commits will get unreadable.
* Why do you have that huge json with recipes and then `melpaPackage` does `fetchurl` for a recipe again? That is, what is the point of `fetchurl`ing recipes (which will generate files in nix store) when the size of a typical recipe is not much different from the size of its hash?
* Maybe I'm outdated, but the last time I tried `nyan-mode` actually needed that patch to work correctly on NixOS.
* Are you sure you want to be a maintainer of all the MELPA in nixpkgs?

Constructively, i.e. "what I would do with this if I were the author of this and were to ignore the whole XEmacs problem for now":

* Leave a2fa94289c90ff81e77dfd943f51057d74c7803a as is.
* Split 14c350791775d0cbf605fa73cf09e1936ee8f586 into pieces:
    * Generalize `melpaBuild` with the recipe thingy leaving the change to `melpa2nix.el` as is.
    * Make `melpaPackage` and `elpaPackage` live in their own file(s) in `build-support/emacs`.
    * Generate a huge json with the package description and recipe combined in a single json node.
    * let autoMELPAPackages = map thru that json applying `melpaPackage` or whatnot, generating that huge attrset of packages. Preferably without any `fetchurl`ing there.
    * Tie the recursive knot between `emacs-packages.nix` (making the hand-written part take priority) making that change as small as possible (i.e. why change the indent of the whole file when one needs to add a couple of new functions there).
    * Remove the hand-written duplicates I'm able to test from `emacs-packages.nix`.
    * Move hand-written stuff from the old `emacsPackages` to `emacs-packages.nix` without changing anything. Remove the hand-written duplicates I'm able to test from `emacs-packages.nix` again.
    * Only then rename `emacsPackagesNg` to `emacsPackages`.

Note that duplicates should actually be duplicates, version number difference may make a lot of difference.

**Comment by oxij** [comment]
And a minor thing. The commit message of a2fa94289c90ff81e77dfd943f51057d74c7803a says "melpaBuild", but changes "generic" builder.

**Comment by ttuegel** [comment]
> I don't oppose the idea, but this is too radical yet.

Yes, that's the point. I expect to get push-back from the contributors who don't like anything to change. :)

> It will conflict with every single change to emacs-packages.nix in master.

Yesterday I rebased it forward from the beginning of April. There were few conflicts.

> defaultOverrides part is ugly. I think we should strive for a design similar to python-packages.nix and python-packages-generated.nix or even haskellPackagesNg with it's per-compiler config (because it would be nice to support various Emacs versions and XEmacs).

I'm not sure what the exact complaint is here, but it sounds like you would prefer the list of extra packages be in a separate file, is that right?

> The following pattern is ugly and useless:
> 
>   ghc-mod =
>      let drv = { mkDerivation, ghc-mod, stdenv }:
>         mkDerivation rec { ... };
>      in callPackage drv { ... };
> 
> Why generate a function and then use callPackage when you can reference all the dependencies directly with self/super trick?

It's not useless; it is necessary to enable per-package overrides properly. In fact, this is exactly what haskell-ng does.

> Preferably, one should generalize melpaBuild with that awesome build-package-from-recipe thing. There's basically one word difference between the files, why copy-paste?

The former basically takes the recipe parameters on the command-line, while the latter passes in a path to the recipe file. They are quite similar, but not trivially so; in particular, the functions don't even take the same arguments.

> Why do you have that huge json with recipes and then melpaPackage does fetchurl for a recipe again? That is, what is the point of fetchurling recipes (which will generate files in nix store) when the size of a typical recipe is not much different from the size of its hash?

The JSON doesn't contain the recipe, just enough information to download the source. The recipes are not amenable to translating into JSON because they have an irregular structure. For actually building the packages, it's best to give the S-Exp directly to Emacs. But you're right, they are short enough it's probably best just to include the S-Exp in a string.

> Note that duplicates should actually be duplicates, version number difference may make a lot of difference.

It is very troubling to me that you would say this. The only purpose to generating package expressions automatically is so they can be regularly updated with minimal effort. If keeping the same versions is important now, it will always be important in the future; then, we should not upgrade packages frequently or automatically. If, on the other hand, upgrading versions is desirable in the future, there is no reason not to do it now.

NixOS PRs are never merged after an objection has been raised, so I will close this to clear the queue.

**Comment by ttuegel** [comment]
Sorry, it was just pointed out to me that it looks like I'm abandoning this. That's not the case! I wanted to get feedback from users. Now it's clear that there are non-trivial changes to make before merging this. I just don't want too many people to start using this patch when I know that what eventually gets merged will be different!

**Comment by oxij** [comment]
>> It will conflict with every single change to emacs-packages.nix in master.

> Yesterday I rebased it forward from the beginning of April. There were few conflicts.

A happy coincidence :)

The other problem with huge blobs is that if it happens to produce a problem then there's no way for people with write access to quickly fix it except to revert the whole blob.

>> defaultOverrides part is ugly. I think we should strive for a design similar to python-packages.nix and python-packages-generated.nix or even haskellPackagesNg with it's per-compiler config (because it would be nice to support various Emacs versions and XEmacs).

> I'm not sure what the exact complaint is here, but it sounds like you would prefer the list of extra packages be in a separate file, is that right?

Yes and no. I would prefer `emacs-packages.nix` to be hand-written part that `import`s the generated part in a way very similar to `python-packages.nix`.

>> The following pattern is ugly and useless:

> It's not useless; it is necessary to enable per-package overrides properly. In fact, this is exactly what haskell-ng does.

Hmm. I still think it kinda is, if one applies overrides before instantiating `callPackage`.

>>  Preferably, one should generalize melpaBuild with that awesome build-package-from-recipe thing. There's basically one word difference between the files, why copy-paste?

> The former basically takes the recipe parameters on the command-line, while the latter passes in a path to the recipe file. They are quite similar, but not trivially so; in particular, the functions don't even take the same arguments.

Ah, okay.

>> Note that duplicates should actually be duplicates, version number difference may make a lot of difference.

> It is very troubling to me that you would say this. The only purpose to generating package expressions automatically is so they can be regularly updated with minimal effort. If keeping the same versions is important now, it will always be important in the future; then, we should not upgrade packages frequently or automatically. If, on the other hand, upgrading versions is desirable in the future, there is no reason not to do it now.

The problem with elisp is that it's very easy to get a package that will appear work, except it actually wouldn't. E.g. I once managed to break `org-mode` in a nontrivial way by loading parts of it from a local repo and some other parts from `emacsPackages`. It would work, but it felt like if something otherworldly creeped into it in places.

With this I have a fear that an atomic move from the current stuff to generated MELPA (or even just a plain simple hand written `melpaBuild` in place of an ad-hoc builder) may break something in a nontrivial way.
Making that transition it in one big blobby go will likely to mean
* hurdles with bisecting problems,
* as a consequence => pains for users and blobby reverts.

I would be very unhappy if my new NixOS from master built pretty okay, but then in two days I would find out that `org-mode` or `proof-general` is creeping with ghosts. Especially on a laptop, especially in the middle of a work day.

Yet I'm not saying we should not do this. I'm saying we should check the new stuff to work first before dropping something someone is likely to actually use.

**Comment by oxij** [comment]
Note that most of my concerns can be summarized as "split that blob into pieces" since the core `recipe` part of it is pretty awesome (so awesome, in fact, that I got kinda exited about this).

I see no problem leaving this PR open.

**Comment by ttuegel** [comment]
> Hmm. I still think it kinda is, if one applies overrides before instantiating callPackage.

I think we're talking about different things. You're talking about overriding one package in the collection so the other packages in the collection see the overridden version. I'm talking about overriding one package in an isolated way--for example, upgrading one of its dependencies without upgrading that dependency for the in the rest of the collection. The most important feature is the ability to override `mkDerivation`; that lets us inject arbitrary modifications into the generated packages: patches, extra phase hooks, etc.

**Comment by oxij** [comment]
>> Hmm. I still think it kinda is, if one applies overrides before instantiating callPackage.

> I think we're talking about different things. You're talking about overriding one package in the collection so the other packages in the collection see the overridden version. I'm talking about overriding one package in an isolated way--for example, upgrading one of its dependencies without upgrading that dependency for the in the rest of the collection. The most important feature is the ability to override `mkDerivation`; that lets us inject arbitrary modifications into the generated packages: patches, extra phase hooks, etc.

Ah, okay. Then I only suggest doing this change for the currently existing packages as a separate commit.

**Comment by gridaphobe** [comment]
Sorry I'm late to the party here, I didn't even see this PR.

I share @oxij's concern about bulk updates breaking packages in subtle ways, but I think the benefits of making all of MELPA available vastly outweigh the concern. There's always going to be cases where upgrading one package breaks another, but for that scenario we have the ability to override said package to an earlier version by specifying a different commit/hash pair.

I'd also really like to see the script that generates the json blobs added, so I can help keep the package set up to date.

**Pull request closed without merging**
