### PR TITLE
nixos/tests/mtp: init

### PR DESCRIPTION
**Pull request by MatthewCroughan**
###### Motivation for this change

Adds a fully fledged NixOS VM integration test which uses jmtpfs and gvfs to test the functionality of MTP inside of NixOS. It uses USB device emulation in QEMU to create MTP device(s) which can be tested against.

This was motivated by https://github.com/NixOS/nixpkgs/issues/145824, since MTP broke and my friend was unable to interact with his Android Phone in NixOS, seemingly due to the libmtp 1.1.19 upgrade.

This NixOS test proves that upgrading to libmtp 1.1.19 is not the cause of the regression, as the test will fail on 7b06961 (the commit that introduced 1.1.19), and also fail on 946ea034cdd7d948119486f1f7726b4c8a937a88 (the commit prior to the upgrade to 1.1.19)

I have prepared three branches so that viewers of this PR can test for themselves:

##### Running this test on `nixos-21.05` (working)
`nix build github:matthewcroughan/nixpkgs/basedOn21.05#nixosTests.mtp -L`
##### Before the update to libmtp-1.1.19 (broken)
`nix build github:matthewcroughan/nixpkgs/before-libmtp-1.1.19#nixosTests.mtp -L`
##### After the update to libmtp-1.1.19 (broken)
`nix build github:matthewcroughan/nixpkgs/after-libmtp-1.1.19#nixosTests.mtp -L`

Co-authored-by: nixinator <33lockdown33@protonmail.com>

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Approach & implementation seem reasonable, however the test is currently failing for me (on your branch):

```
client # qemu-system-x86_64: usb-mtp: file monitoring init failed: File monitoring not available on this platform
client # 10+0 records in
client # 10+0 records out
client # 10485760 bytes (10 MB, 10 MiB) copied, 0.181539 s, 57.8 MB/s
client # ls: cannot access '/run/user/0/gvfs/*/testFile10M': No such file or directory
client: output:
cleanup
kill machine (pid 6)
client # qemu-system-x86_64: terminating on signal 15 from pid 4 (/nix/store/8dxxjbiyxwkvh53q5kh6nydla2anacgi-python3-3.9.6/bin/python3)
(0.01 seconds)
Traceback (most recent call last):
  File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 1334, in <module>
    driver.run_tests()
  File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 1210, in run_tests
    self.test_script()
  File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 1206, in test_script
    exec(self.tests, symbols, None)
  File "<string>", line 4, in <module>
  File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 640, in succeed
    raise Exception(
Exception: command `/nix/store/822ngckji6dyy597fy10b7wxvv8yysc3-gvfsTest.sh >&2` failed (exit code 2)
error: build of '/nix/store/nqwag7rjm8r3mn6smzfa7gs22p1fk54w-vm-test-run-mtp.drv' on 'ssh-ng://builder-ng' failed: error: builder for '/nix/store/nqwag7rjm8r3mn6smzfa7gs22p1fk54w-vm-test-run-mtp.drv' failed with exit code 1
error: builder for '/nix/store/nqwag7rjm8r3mn6smzfa7gs22p1fk54w-vm-test-run-mtp.drv' failed with exit code 1
```

@ofborg test mtp

**Comment by MatthewCroughan** [comment]
> Approach & implementation seem reasonable, however the test is currently failing for me (on your branch):
> 
> ```
> client # qemu-system-x86_64: usb-mtp: file monitoring init failed: File monitoring not available on this platform
> client # 10+0 records in
> client # 10+0 records out
> client # 10485760 bytes (10 MB, 10 MiB) copied, 0.181539 s, 57.8 MB/s
> client # ls: cannot access '/run/user/0/gvfs/*/testFile10M': No such file or directory
> client: output:
> cleanup
> kill machine (pid 6)
> client # qemu-system-x86_64: terminating on signal 15 from pid 4 (/nix/store/8dxxjbiyxwkvh53q5kh6nydla2anacgi-python3-3.9.6/bin/python3)
> (0.01 seconds)
> Traceback (most recent call last):
>   File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 1334, in <module>
>     driver.run_tests()
>   File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 1210, in run_tests
>     self.test_script()
>   File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 1206, in test_script
>     exec(self.tests, symbols, None)
>   File "<string>", line 4, in <module>
>   File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 640, in succeed
>     raise Exception(
> Exception: command `/nix/store/822ngckji6dyy597fy10b7wxvv8yysc3-gvfsTest.sh >&2` failed (exit code 2)
> error: build of '/nix/store/nqwag7rjm8r3mn6smzfa7gs22p1fk54w-vm-test-run-mtp.drv' on 'ssh-ng://builder-ng' failed: error: builder for '/nix/store/nqwag7rjm8r3mn6smzfa7gs22p1fk54w-vm-test-run-mtp.drv' failed with exit code 1
> error: builder for '/nix/store/nqwag7rjm8r3mn6smzfa7gs22p1fk54w-vm-test-run-mtp.drv' failed with exit code 1
> ```
> 
> @ofborg test mtp

Yes, it fails because MTP functionality is broken in NixOS thanks to some regression, which is why I made this test. The breakage is expected. It will not break if you cherry-pick this commit into nixos-21.05.

**Comment by Ma27** [comment]
Whoops sorry, I Interpreted it to be fixed already and this was only to avoid similar situations in the future :)

**Comment by MatthewCroughan** [comment]
> Whoops sorry, I Interpreted it to be fixed already and this was only to avoid similar situations in the future :)

Yeah, sadly it's not clear what caused the MTP regression in NixOS. Someone could use this test to run [`nix-bisect`](https://github.com/timokau/nix-bisect)` and prove what caused the regression. But I don't know much about how to use `nix-bisect` and spent enough time making this test already. Perhaps on the weekend!

**Comment by SuperSandro2000** [comment]
Not my area of expertise

**Comment by oxalica** [comment]
The test seems incorrect. After checking and bisecting, I found `qemu: 6.0.0 -> 6.1.0` 988da51d9c49a1d43fe28a5f92394f5dbc16eede failing the test, while the commit before this one passed the test. I don't think it's the cause of the MTP issue, just the issue of test set.

N.B. This QEMU commit is broken, you need to prepend `makeWrapper` to `nativeBuildInputs` of `qemu` to make it build, and then you'll get the same test failure: `ls: cannot access '/run/user/0/gvfs/*/testFile10M': No such file or directory`.

**Comment by MatthewCroughan** [comment]
Maybe if we force the version of QEMU to be consistent throughout these tests (Staying at version 6.0.0) it will be a better test. Since the test itself is relying on hardware behavior which has changed between QEMU 6.0.0 and QEMU 6.1.0.

```diff
❯ git diff v6.0.0 v6.1.0 -- hw/usb/dev-mtp.c
diff --git a/hw/usb/dev-mtp.c b/hw/usb/dev-mtp.c
index bbb8274344..c1d1694fd0 100644
--- a/hw/usb/dev-mtp.c
+++ b/hw/usb/dev-mtp.c
@@ -772,12 +772,9 @@ static void usb_mtp_add_str(MTPData *data, const char *str)
 
 static void usb_mtp_add_time(MTPData *data, time_t time)
 {
-    char buf[16];
-    struct tm tm;
-
-    gmtime_r(&time, &tm);
-    strftime(buf, sizeof(buf), "%Y%m%dT%H%M%S", &tm);
-    usb_mtp_add_str(data, buf);
+    g_autoptr(GDateTime) then = g_date_time_new_from_unix_utc(time);
+    g_autofree char *thenstr = g_date_time_format(then, "%Y%m%dT%H%M%S");
+    usb_mtp_add_str(data, thenstr);
 }
 
 /* ----------------------------------------------------------------------- */
@@ -907,7 +904,8 @@ static MTPData *usb_mtp_get_object_handles(MTPState *s, MTPControl *c,
                                            MTPObject *o)
 {
     MTPData *d = usb_mtp_data_alloc(c);
-    uint32_t i = 0, handles[o->nchildren];
+    uint32_t i = 0;
+    g_autofree uint32_t *handles = g_new(uint32_t, o->nchildren);
     MTPObject *iter;
 
     trace_usb_mtp_op_get_object_handles(s->dev.addr, o->handle, o->path);
```

**Comment by MatthewCroughan** [comment]
@oxalica It looks as if one cannot ask for a different version of QEMU to be used for their test. So if there is an issue with QEMU that causes a test to fail, that cannot be fixed by simply locking the QEMU version within a test. At least, I cannot find any existing examples of doing this, so we may have to write some new code, or maybe QEMU should have versions in Nixpkgs like `qemu_6_1` and `qemu_6_0`.

**Comment by MatthewCroughan** [comment]
Actually, I just read https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/testing-python.nix and it has an attribute inside called `pythonTestDriver.qemu_pkg`, which I'm interesting in overriding with my own.

**Comment by oxalica** [comment]
> Maybe if we force the version of QEMU to be consistent throughout these tests (Staying at version 6.0.0) it will be a better test. Since the test itself is relying on hardware behavior which has changed between QEMU 6.0.0 and QEMU 6.1.0.

So what version of QEMU *SHOULD* be used for this test? If 6.0.0 should be used, it's unable to be merged since it will never work on master (6.1.0). If 6.1.0 should be used, why it fails after bumping to 6.1.0?
Remind that 6.0.0 PASSED the test, 6.1.0 FAILED the test. If gvfs break somewhere else, it must be after QEMU bumping. Thus this test cannot test it out.

**Comment by MatthewCroughan** [comment]
@oxalica It seems that the behavior of QEMU changed with 6.1.0 in a way that breaks the test, so we need to use 6.0.0, that is correct.

**Comment by MatthewCroughan** [comment]
> We should at least fix the test to pass the commit of bumping QEMU

It is not the job of the test to be aware of what commit it is on, as far as I understand it. That's your job as the bisector to fix, then mark as `git bisect good` or `git bisect bad`, the test just cannot be automated between the commit ranges you're using with this problem in the middle, but as the human you simply fix the commit yourself and mark it.

**Comment by oxalica** [comment]
> It is not the job of the test to be aware of what commit it is on, as far as I understand it. That's your job as the bisector to fix, then mark as `git bisect good` or `git bisect bad`, the test just cannot be automated between the commit ranges you're using with this problem in the middle, but as the human you simply fix the commit yourself and mark it.

My point is that, even if we fixed `gvfs`, this test would still fail, because we have QEMU 6.1.0 in master. So this PR could not being merged anyway.

**Comment by MatthewCroughan** [comment]
@oxalica That is only true if we cannot find a way within the testing framework to override the version of QEMU being used, which I believe should be possible, I'm looking into it.

**Comment by MatthewCroughan** [comment]
@oxalica thanks to the help of @juliosueiras I've managed to use QEMU 6.0.0 by modifying how the test is called in `all-tests.nix`, is it possible you could try bisecting again?

**Comment by juliosueiras** [comment]
though I am pretty sure referring to another commit of nixpkgs is not allow?

**Comment by MatthewCroughan** [comment]
> though I am pretty sure referring to another commit of nixpkgs is not allow?

It's IFD, which Hydra would not permit. An overrideAttrs would be better, and allowed on Hydra. This is my understanding after having spoken to @adisbladis on Matrix.

**Comment by oxalica** [comment]
> @oxalica thanks to the help of @juliosueiras I've managed to use QEMU 6.0.0 by modifying how the test is called in `all-tests.nix`, is it possible you could try bisecting again?

Hmmm, then the test simply passed on latest `nixos-unstable` (81cef6b70fb5d5cdba5a0fef3f714c2dadaf0d6d). But I still cannot get MTP work on KDE. Does it mean it's actually not the issue of gvfs, but somewhere else?

**Comment by MatthewCroughan** [comment]
@oxalica KDE does not use GVFS, it uses `kiod5` which would be another unit to add to this test. Can you check if MTP via GVFS works in Gnome on the latest unstable?

**Comment by andrevmatos** [comment]
I applied the change in #152289 to my system, but mtp is still broken under KDE.

**Comment by onny** [comment]
Trying to run the test but seems to fail, is this expected? Error message is `gio: gphoto2://[usb:001,002]/: volume doesn’t implement mount`

```
$ git checkout add-mtp-test
$ nix-build nixos/tests/mtp.nix
[...]
(finished: waiting for unit multi-user.target, in 15.85 seconds)
client # [   15.060221] dhcpcd[851]: eth0: adding route to fec0::/64
client # [   15.062143] dhcpcd[851]: eth0: adding default route via fe80::2
client: waiting for unit dbus.service
client # [   15.071683] dhcpcd[602]: forked to background, child pid 851
client # [   15.183914] login[788]: pam_unix(login:session): session opened for user root(uid=0) by LOGIN(uid=0)
client # [   15.301979] systemd-udevd[588]: vtcon1: Process '/nix/store/aqwqh3drn9bf6qrs70wiyrxaawh1wcnz-systemd-249.5/lib/systemd/systemd-vconsole-setup' failed with exit code 1.
client # [   15.309635] systemd-udevd[589]: vtcon0: Process '/nix/store/aqwqh3drn9bf6qrs70wiyrxaawh1wcnz-systemd-249.5/lib/systemd/systemd-vconsole-setup' failed with exit code 1.
client # [   15.329139] systemd-logind[640]: New session 1 of user root.
(finished: waiting for unit dbus.service, in 0.28 seconds)
client: must succeed: /nix/store/nvypzic9qkh8jnc7lln5ycvhgxnq7b82-gvfsTest.sh >&2
client # [   15.349808] systemd[1]: Created slice Slice /user/0.
client # [   15.380325] systemd[1]: Starting User Runtime Directory /run/user/0...
client # [   15.480431] systemd[1]: Finished User Runtime Directory /run/user/0.
client # [   15.494112] systemd[1]: Starting User Manager for UID 0...
client # [   15.529943] systemd[882]: pam_unix(systemd-user:session): session opened for user root(uid=0) by (uid=0)
client # gio: gphoto2://[usb:001,002]/: volume doesn’t implement mount
client: output: 
cleanup
kill machine (pid 8)
client # qemu-system-x86_64: terminating on signal 15 from pid 6 (/nix/store/k0z9n599k02hab8qjjp3ljw065iwjcvg-python3-3.9.6/bin/python3.9)
(finished: cleanup, in 0.07 seconds)
Traceback (most recent call last):
  File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/bin/.nixos-test-driver-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/__init__.py", line 86, in main
    driver.run_tests()
  File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/driver.py", line 115, in run_tests
    self.test_script()
  File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/driver.py", line 111, in test_script
    exec(self.tests, symbols, None)
  File "<string>", line 4, in <module>
  File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/machine.py", line 554, in succeed
    raise Exception(
Exception: command `/nix/store/nvypzic9qkh8jnc7lln5ycvhgxnq7b82-gvfsTest.sh >&2` failed (exit code 2)
kill vlan (pid 7)
error: builder for '/nix/store/68zpn4ykvnnm0hqjyfvsk0wh4szymagf-vm-test-run-mtp.drv' failed with exit code 1;
       last 10 log lines:
       >     driver.run_tests()
       >   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/driver.py", line 115, in run_tests
       >     self.test_script()
       >   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/driver.py", line 111, in test_script
       >     exec(self.tests, symbols, None)
       >   File "<string>", line 4, in <module>
       >   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/machine.py", line 554, in succeed
       >     raise Exception(
       > Exception: command `/nix/store/nvypzic9qkh8jnc7lln5ycvhgxnq7b82-gvfsTest.sh >&2` failed (exit code 2)
       > kill vlan (pid 7)
       For full logs, run 'nix log /nix/store/68zpn4ykvnnm0hqjyfvsk0wh4szymagf-vm-test-run-mtp.drv'.
```

**Comment by MatthewCroughan** [comment]
> Trying to run the test but seems to fail, is this expected? Error message is `gio: gphoto2://[usb:001,002]/: volume doesn’t implement mount`
> 
> ```
> $ git checkout add-mtp-test
> $ nix-build nixos/tests/mtp.nix
> [...]
> (finished: waiting for unit multi-user.target, in 15.85 seconds)
> client # [   15.060221] dhcpcd[851]: eth0: adding route to fec0::/64
> client # [   15.062143] dhcpcd[851]: eth0: adding default route via fe80::2
> client: waiting for unit dbus.service
> client # [   15.071683] dhcpcd[602]: forked to background, child pid 851
> client # [   15.183914] login[788]: pam_unix(login:session): session opened for user root(uid=0) by LOGIN(uid=0)
> client # [   15.301979] systemd-udevd[588]: vtcon1: Process '/nix/store/aqwqh3drn9bf6qrs70wiyrxaawh1wcnz-systemd-249.5/lib/systemd/systemd-vconsole-setup' failed with exit code 1.
> client # [   15.309635] systemd-udevd[589]: vtcon0: Process '/nix/store/aqwqh3drn9bf6qrs70wiyrxaawh1wcnz-systemd-249.5/lib/systemd/systemd-vconsole-setup' failed with exit code 1.
> client # [   15.329139] systemd-logind[640]: New session 1 of user root.
> (finished: waiting for unit dbus.service, in 0.28 seconds)
> client: must succeed: /nix/store/nvypzic9qkh8jnc7lln5ycvhgxnq7b82-gvfsTest.sh >&2
> client # [   15.349808] systemd[1]: Created slice Slice /user/0.
> client # [   15.380325] systemd[1]: Starting User Runtime Directory /run/user/0...
> client # [   15.480431] systemd[1]: Finished User Runtime Directory /run/user/0.
> client # [   15.494112] systemd[1]: Starting User Manager for UID 0...
> client # [   15.529943] systemd[882]: pam_unix(systemd-user:session): session opened for user root(uid=0) by (uid=0)
> client # gio: gphoto2://[usb:001,002]/: volume doesn’t implement mount
> client: output: 
> cleanup
> kill machine (pid 8)
> client # qemu-system-x86_64: terminating on signal 15 from pid 6 (/nix/store/k0z9n599k02hab8qjjp3ljw065iwjcvg-python3-3.9.6/bin/python3.9)
> (finished: cleanup, in 0.07 seconds)
> Traceback (most recent call last):
>   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/bin/.nixos-test-driver-wrapped", line 9, in <module>
>     sys.exit(main())
>   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/__init__.py", line 86, in main
>     driver.run_tests()
>   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/driver.py", line 115, in run_tests
>     self.test_script()
>   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/driver.py", line 111, in test_script
>     exec(self.tests, symbols, None)
>   File "<string>", line 4, in <module>
>   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/machine.py", line 554, in succeed
>     raise Exception(
> Exception: command `/nix/store/nvypzic9qkh8jnc7lln5ycvhgxnq7b82-gvfsTest.sh >&2` failed (exit code 2)
> kill vlan (pid 7)
> error: builder for '/nix/store/68zpn4ykvnnm0hqjyfvsk0wh4szymagf-vm-test-run-mtp.drv' failed with exit code 1;
>        last 10 log lines:
>        >     driver.run_tests()
>        >   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/driver.py", line 115, in run_tests
>        >     self.test_script()
>        >   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/driver.py", line 111, in test_script
>        >     exec(self.tests, symbols, None)
>        >   File "<string>", line 4, in <module>
>        >   File "/nix/store/ldzp01cfbjvx560ffc7gvkss41yqrk9p-nixos-test-driver-1.0/lib/python3.9/site-packages/test_driver/machine.py", line 554, in succeed
>        >     raise Exception(
>        > Exception: command `/nix/store/nvypzic9qkh8jnc7lln5ycvhgxnq7b82-gvfsTest.sh >&2` failed (exit code 2)
>        > kill vlan (pid 7)
>        For full logs, run 'nix log /nix/store/68zpn4ykvnnm0hqjyfvsk0wh4szymagf-vm-test-run-mtp.drv'.
> ```

Please run this instead. I'm not sure if your branch is really up to date.

`nix build github:matthewcroughan/nixpkgs/473a571a8c99fb45d2e4ab41823a66287ff26161#nixosTests.mtp`

This will ensure you're using the same test as me. For me, the test passes.

**Comment by onny** [comment]
> Please run this instead. I'm not sure if your branch is really up to date.
> 
> `nix build github:matthewcroughan/nixpkgs/473a571a8c99fb45d2e4ab41823a66287ff26161#nixosTests.mtp`
> 
> This will ensure you're using the same test as me. For me, the test passes.

Yep this works for me :)

**Pull request merged**
