### PR TITLE
xdg-desktop-portal-gtk: remove gnome-settings-daemon

### PR DESCRIPTION
**Pull request by colemickens**
###### Description of changes

I do not, do not want networkmanager in my system, or the things it pulls in.

Testing in progress, but it builds.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — CHANGES_REQUESTED** [review]
There are still two runtime dependencies:

https://github.com/flatpak/xdg-desktop-portal-gtk/blob/a1558c0096cdaf5d2fbc8ac81c536e818e14b2da/src/settings.c#L273-L277

**Comment by colemickens** [comment]
Does it make sense to have a build flag for those too? Presumably Sway users aren't getting much benefit from the Settings portal anyway.

**Comment by colemickens** [comment]
It seems like the Settings portal is already disabled with the existing package parameter. I've updated this PR to keep `gnome.gnome-settings-daemon` whenever `buildPortalsInGnome` is true.

This feels maybe like what was originally intended?

**Comment by jtojnar** [comment]
`buildPortalsInGnome` will be `true` when `xdg-desktop-portal-gnome` is not installed, which should be the case on Sway. So making it conditional on that will not help you.

And the xsettings schema controls various settings like font-family in GTK apps on X11. Though I am not sure if it will be set by synchronized by anything – on GNOME this is handled by gnome-settings-daemon.

Also please keep the comment.

**Comment by colemickens** [comment]
I seem to not understand this enough. I'll have to revisit this another time or maybe file an upstream bug. I am a bit frustrated that because I want a file picker, I have to build openconnect......

**Comment by jtojnar** [comment]
From upstream point of view all the schemas are optional so there should be no issue there.

**Comment by colemickens** [comment]
Thanks for the comments and review @jtojnar. I'm going to close this in favor of an Issue as a reminder/followup: #229702

**Pull request closed without merging**
