### PR TITLE
pythonPackages.pbr: 1.8.1 -> 2.0.0

### PR DESCRIPTION
**Pull request by nlewo**

### CODE REVIEW

**Comment by LnL7** [comment]
We have a bunch of packages like `stevedore` that are currently not compatible with this version.

**Comment by FRidh** [comment]
@LnL7  `stevedore` needs a version bump.

**Comment by FRidh** [comment]
@nlewo in the future please fill out the template (and run nox-review)

**Comment by LnL7** [comment]
Yeah, working on it.

**Comment by nlewo** [comment]
@FRidh sorry about the template, I tryied to use hub to push the review but it removed the template.
Ok for `nox-review`.

**Comment by volth** [comment]
Just curious: why not ```3.0.0``` ?

**Comment by FRidh** [comment]
They're moving fast with the new versions. When this PR was made that version wasn't released yet. Open a PR I would say.

**Comment by volth** [comment]
I would better undo this, or create ```pbr``` and ```pbr2``` (akin to ```requests``` and ```requests2``` because there are many dependencies on old ```pbr```). The disaster was done not by introducing ```pbr2``` but by removing the old ```pbr```)

**Comment by FRidh** [comment]
No, this is going to stay. Having multiple packages is an absolute last resort, and with a package like pbr that is going to cause a lot of problems because it is used a lot. From the Hydra build I ran it seems we nowadays have about the same amount of failures as before.

**Pull request merged**
