### PR TITLE
[20.09] boot.initrd.luks: add reusePassphrases support for YubiKey 2FA

### PR DESCRIPTION
**Pull request by ctem**
The 20.09 backport will be done after the [master PR](https://github.com/NixOS/nixpkgs/pull/107402).

###### Motivation for this change

`boot.initrd.luks.reusePassphrases = true;` is not respected when used with YubiKey-based 2FA.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ctem** [comment]
Hi! This is my first Nixpkgs PR. I chose `nixos-20.09` as the base branch for the PR because my `fix/luksroot` branch is based on `3a02dc9edb2` to correspond with my NixOS version, `20.09.2181.3a02dc9edb2 (Nightingale)`. Perhaps I should have rebased my branch on `master` instead?

**Comment by nh2** [comment]
> Perhaps I should have rebased my branch on `master` instead?

@ctem That is correct. The common approach is to

* make a PR against `master`, merge it (it then becomes `nixos-unstable` after merge and Hydra CI), and then
* if a backport to stable is desired, make a PR against `release-20.09` (which then becomes `nixos-20.09` after merge Hydra CI) using `git cherry-pick -x` to create a `cherry picked from commit ...` line referencing the `master` commit.

Having a 20.09 PR open is also useful for easy testability. The best steps you should take are:

1. Make a PR against `master`
2. Make this PR a `Draft PR`, and explain in the issue description that the 20.09 backport will be done after the master PR
3. When the `master` PR is merged, replace the commit in this PR by one done with `git cherry-pick -x`, remove the `Draft` bit from the PR, and retarget this PR against `release-20.09` instead of `nixos-20.09`.

**Comment by ctem** [comment]
@nh2 Thank you for your kind instruction! Steps 1-2 are complete; now awaiting the `master` PR to be merged.

**Comment by nh2** [comment]
Linking `master` PR: #107402

**Comment by cole-h** [comment]
(FYI: when this is circled back to, this PR needs to be based against the release-20.09 branch, not nixos-20.09.)

**Comment by ctem** [comment]
Master PR #107402 has been merged, so I’ve updated and reopened this backport PR.

**Comment by ctem** [comment]
@symphorien Yes, that sounds reasonable. I’ll leave this open in the meantime.

**Comment by mweinelt** [comment]
Unfortunately NixOS 20.09 has reached its end-of-life status on 2021-07-01, one
month after the release of NixOS 21.05.

Since we do not accept any changes to its branches anymore, I'm closing this pull
request.

**Pull request closed without merging**
