### PR TITLE
vapoursynth: wrap vspipe

### PR DESCRIPTION
**Pull request by tadeokondrak**
###### Motivation for this change

See #58859 (`vspipe` included with VapourSynth doesn't work), but less complex and hopefully merged faster.

Apparently you don't even need to make it a python module for it to be usable, as `nix-shell -p python3 vapoursynth` seems to work fine. (I *think* it didn't when I made the first PR, but I may be wrong)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by rnhmjoj — APPROVED** [review]
Finally vspipe works, thank you!

**Comment by teto** [comment]
could you rebase/fix conflict and test please

**Comment by tadeokondrak** [comment]
@teto done

**Comment by teto** [comment]
Is the `vapoursynth.withPlugins` function still in question ? seems like the approach https://github.com/NixOS/nixpkgs/issues/64158 would be better in the long run. I guess it depends on how many plugins are available etc.
I am ok to merge this meanwhile, just wondering .

**Comment by tadeokondrak** [comment]
Yes, I definitely plan to work more on this, see https://github.com/tadeokondrak/vs-overlay for my current progress on packaging plugins themselves, which I eventually would like to upstream (most) of into nixpkgs and add a withPlugins function.

**Comment by teto** [comment]
rnhmjoj on irc tested and liked it.

**Pull request merged**
