### PR TITLE
Glob093 doesnt exist

### PR DESCRIPTION
**Pull request by chessai**
###### Motivation for this change
```bash
  ~/nixpkgs $ nix repl default.nix
  ~/nixpkgs $ nix repl default.nix 
   Welcome to Nix version 2.0.4. Type :? for help.

   Loading 'default.nix'...
   Added 9532 variables.

   nix-repl> haskell.packages.ghc861.Glob 
   error: attribute 'Glob_0_9_3' missing, at 
  /home/user/nixpkgs/pkgs/development/haskell-modules/configuration-ghc-8.6.x.nix:52:10
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
Just remove the line completely, `Glob = super.Glob` is the same as not having it at all. And make sure for this to only be a single commit

**Review by peti — CHANGES_REQUESTED** [review]
Don't edit `hackage-packages.nix`. Please see the comment in the very first line.

**Comment by Infinisil** [comment]
@peti I think the user was just a bit git confused, the only commit they intend to contribute is the "fix Glob not existing" one, which seems okay to do

**Comment by c0bw3b** [comment]
Solved in 95ae25600e7d614aad8be044124007617c5f0390

**Pull request closed without merging**
