### PR TITLE
phpExtensions.dom: fix build

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change
ZHF #122042

cc @stephank @NixOS/php @NixOS/release-engineers 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124193` at 53951c0c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>hhvm</li>
    <li>libsForQt512.kcachegrind</li>
    <li>libsForQt514.kcachegrind</li>
    <li>php73Extensions.pcs</li>
    <li>php73Packages.phpmd</li>
    <li>php74Extensions.pcs</li>
    <li>php80Extensions.pcs</li>
  </ul>
</details>
<details>
  <summary>6 packages skipped due to time constraints:</summary>
  <ul>
    <li>bookstack</li>
    <li>libsForQt5.kcachegrind (libsForQt515.kcachegrind ,plasma5Packages.kcachegrind)</li>
    <li>php73Extensions.couchbase</li>
    <li>pulseeffects-legacy</li>
    <li>pulseeffects-pw</li>
    <li>unit</li>
  </ul>
</details>
<details>
  <summary>246 packages built successfully:</summary>
  <ul>
    <li>adminer</li>
    <li>php (apacheHttpdPackages.php ,php74)</li>
    <li>arcanist</li>
    <li>drush</li>
    <li>engelsystem</li>
    <li>icingaweb2</li>
    <li>lsp-plugins</li>
    <li>matomo</li>
    <li>matomo-beta</li>
    <li>nagios</li>
    <li>nextcloud-news-updater</li>
    <li>phoronix-test-suite</li>
    <li>php73</li>
    <li>php73Extensions.bcmath</li>
    <li>php73Extensions.bz2</li>
    <li>php73Extensions.calendar</li>
    <li>php73Extensions.ctype</li>
    <li>php73Extensions.curl</li>
    <li>php73Extensions.dba</li>
    <li>php73Extensions.dom</li>
    <li>php73Extensions.enchant</li>
    <li>php73Extensions.event</li>
    <li>php73Extensions.exif</li>
    <li>php73Extensions.fileinfo</li>
    <li>php73Extensions.filter</li>
    <li>php73Extensions.ftp</li>
    <li>php73Extensions.gd</li>
    <li>php73Extensions.gettext</li>
    <li>php73Extensions.gmp</li>
    <li>php73Extensions.hash</li>
    <li>php73Extensions.iconv</li>
    <li>php73Extensions.imap</li>
    <li>php73Extensions.intl</li>
    <li>php73Extensions.json</li>
    <li>php73Extensions.ldap</li>
    <li>php73Extensions.mailparse</li>
    <li>php73Extensions.mbstring</li>
    <li>php73Extensions.memcached</li>
    <li>php73Extensions.mysqli</li>
    <li>php73Extensions.mysqlnd</li>
    <li>php73Extensions.opcache</li>
    <li>php73Extensions.openssl</li>
    <li>php73Extensions.pcntl</li>
    <li>php73Extensions.pdo</li>
    <li>php73Extensions.pdo_dblib</li>
    <li>php73Extensions.pdo_mysql</li>
    <li>php73Extensions.pdo_oci</li>
    <li>php73Extensions.pdo_odbc</li>
    <li>php73Extensions.pdo_pgsql</li>
    <li>php73Extensions.pdo_sqlite</li>
    <li>php73Extensions.pdo_sqlsrv</li>
    <li>php73Extensions.pgsql</li>
    <li>php73Extensions.posix</li>
    <li>php73Extensions.pspell</li>
    <li>php73Extensions.readline</li>
    <li>php73Extensions.redis</li>
    <li>php73Extensions.session</li>
    <li>php73Extensions.shmop</li>
    <li>php73Extensions.simplexml</li>
    <li>php73Extensions.snmp</li>
    <li>php73Extensions.soap</li>
    <li>php73Extensions.sockets</li>
    <li>php73Extensions.sodium</li>
    <li>php73Extensions.sqlite3</li>
    <li>php73Extensions.swoole</li>
    <li>php73Extensions.sysvmsg</li>
    <li>php73Extensions.sysvsem</li>
    <li>php73Extensions.sysvshm</li>
    <li>php73Extensions.tidy</li>
    <li>php73Extensions.tokenizer</li>
    <li>php73Extensions.wddx</li>
    <li>php73Extensions.xml</li>
    <li>php73Extensions.xmlreader</li>
    <li>php73Extensions.xmlrpc</li>
    <li>php73Extensions.xmlwriter</li>
    <li>php73Extensions.xsl</li>
    <li>php73Extensions.zend_test</li>
    <li>php73Extensions.zip</li>
    <li>php73Extensions.zlib</li>
    <li>php73Packages.box</li>
    <li>php73Packages.composer</li>
    <li>php73Packages.composer1</li>
    <li>php73Packages.deployer</li>
    <li>php73Packages.php-cs-fixer</li>
    <li>php73Packages.php-parallel-lint</li>
    <li>php73Packages.phpcbf</li>
    <li>php73Packages.phpcs</li>
    <li>php73Packages.phpstan</li>
    <li>php73Packages.psalm</li>
    <li>php73Packages.psysh</li>
    <li>php74Extensions.bcmath</li>
    <li>php74Extensions.bz2</li>
    <li>php74Extensions.calendar</li>
    <li>php74Extensions.couchbase</li>
    <li>php74Extensions.ctype</li>
    <li>php74Extensions.curl</li>
    <li>php74Extensions.dba</li>
    <li>php74Extensions.dom</li>
    <li>php74Extensions.enchant</li>
    <li>php74Extensions.event</li>
    <li>php74Extensions.exif</li>
    <li>php74Extensions.ffi</li>
    <li>php74Extensions.fileinfo</li>
    <li>php74Extensions.filter</li>
    <li>php74Extensions.ftp</li>
    <li>php74Extensions.gd</li>
    <li>php74Extensions.gettext</li>
    <li>php74Extensions.gmp</li>
    <li>php74Extensions.iconv</li>
    <li>php74Extensions.imap</li>
    <li>php74Extensions.intl</li>
    <li>php74Extensions.json</li>
    <li>php74Extensions.ldap</li>
    <li>php74Extensions.mailparse</li>
    <li>php74Extensions.mbstring</li>
    <li>php74Extensions.memcached</li>
    <li>php74Extensions.mysqli</li>
    <li>php74Extensions.mysqlnd</li>
    <li>php74Extensions.opcache</li>
    <li>php74Extensions.openssl</li>
    <li>php74Extensions.pcntl</li>
    <li>php74Extensions.pdo</li>
    <li>php74Extensions.pdo_dblib</li>
    <li>php74Extensions.pdo_mysql</li>
    <li>php74Extensions.pdo_oci</li>
    <li>php74Extensions.pdo_odbc</li>
    <li>php74Extensions.pdo_pgsql</li>
    <li>php74Extensions.pdo_sqlite</li>
    <li>php74Extensions.pdo_sqlsrv</li>
    <li>php74Extensions.pgsql</li>
    <li>php74Extensions.posix</li>
    <li>php74Extensions.pspell</li>
    <li>php74Extensions.readline</li>
    <li>php74Extensions.redis</li>
    <li>php74Extensions.session</li>
    <li>php74Extensions.shmop</li>
    <li>php74Extensions.simplexml</li>
    <li>php74Extensions.snmp</li>
    <li>php74Extensions.soap</li>
    <li>php74Extensions.sockets</li>
    <li>php74Extensions.sodium</li>
    <li>php74Extensions.sqlite3</li>
    <li>php74Extensions.sysvmsg</li>
    <li>php74Extensions.sysvsem</li>
    <li>php74Extensions.sysvshm</li>
    <li>php74Extensions.tidy</li>
    <li>php74Extensions.tokenizer</li>
    <li>php74Extensions.xml</li>
    <li>php74Extensions.xmlreader</li>
    <li>php74Extensions.xmlrpc</li>
    <li>php74Extensions.xmlwriter</li>
    <li>php74Extensions.xsl</li>
    <li>php74Extensions.zend_test</li>
    <li>php74Extensions.zip</li>
    <li>php74Extensions.zlib</li>
    <li>php74Packages.box</li>
    <li>php74Packages.composer</li>
    <li>php74Packages.composer1</li>
    <li>php74Packages.deployer</li>
    <li>php74Packages.php-cs-fixer</li>
    <li>php74Packages.php-parallel-lint</li>
    <li>php74Packages.phpcbf</li>
    <li>php74Packages.phpcs</li>
    <li>php74Packages.phpmd</li>
    <li>php74Packages.phpstan</li>
    <li>php74Packages.psalm</li>
    <li>php74Packages.psysh</li>
    <li>php80</li>
    <li>php80Extensions.bcmath</li>
    <li>php80Extensions.bz2</li>
    <li>php80Extensions.calendar</li>
    <li>php80Extensions.ctype</li>
    <li>php80Extensions.curl</li>
    <li>php80Extensions.dba</li>
    <li>php80Extensions.dom</li>
    <li>php80Extensions.enchant</li>
    <li>php80Extensions.event</li>
    <li>php80Extensions.exif</li>
    <li>php80Extensions.ffi</li>
    <li>php80Extensions.fileinfo</li>
    <li>php80Extensions.filter</li>
    <li>php80Extensions.ftp</li>
    <li>php80Extensions.gd</li>
    <li>php80Extensions.gettext</li>
    <li>php80Extensions.gmp</li>
    <li>php80Extensions.iconv</li>
    <li>php80Extensions.imap</li>
    <li>php80Extensions.intl</li>
    <li>php80Extensions.ldap</li>
    <li>php80Extensions.mailparse</li>
    <li>php80Extensions.mbstring</li>
    <li>php80Extensions.memcached</li>
    <li>php80Extensions.mysqli</li>
    <li>php80Extensions.mysqlnd</li>
    <li>php80Extensions.opcache</li>
    <li>php80Extensions.openssl</li>
    <li>php80Extensions.pcntl</li>
    <li>php80Extensions.pdo</li>
    <li>php80Extensions.pdo_dblib</li>
    <li>php80Extensions.pdo_mysql</li>
    <li>php80Extensions.pdo_oci</li>
    <li>php80Extensions.pdo_odbc</li>
    <li>php80Extensions.pdo_pgsql</li>
    <li>php80Extensions.pdo_sqlite</li>
    <li>php80Extensions.pdo_sqlsrv</li>
    <li>php80Extensions.pgsql</li>
    <li>php80Extensions.posix</li>
    <li>php80Extensions.pspell</li>
    <li>php80Extensions.readline</li>
    <li>php80Extensions.redis</li>
    <li>php80Extensions.session</li>
    <li>php80Extensions.shmop</li>
    <li>php80Extensions.simplexml</li>
    <li>php80Extensions.snmp</li>
    <li>php80Extensions.soap</li>
    <li>php80Extensions.sockets</li>
    <li>php80Extensions.sodium</li>
    <li>php80Extensions.sqlite3</li>
    <li>php80Extensions.sysvmsg</li>
    <li>php80Extensions.sysvsem</li>
    <li>php80Extensions.sysvshm</li>
    <li>php80Extensions.tidy</li>
    <li>php80Extensions.tokenizer</li>
    <li>php80Extensions.xml</li>
    <li>php80Extensions.xmlreader</li>
    <li>php80Extensions.xmlwriter</li>
    <li>php80Extensions.xsl</li>
    <li>php80Extensions.zend_test</li>
    <li>php80Extensions.zip</li>
    <li>php80Extensions.zlib</li>
    <li>php80Packages.box</li>
    <li>php80Packages.composer</li>
    <li>php80Packages.composer1</li>
    <li>php80Packages.deployer</li>
    <li>php80Packages.php-cs-fixer</li>
    <li>php80Packages.php-parallel-lint</li>
    <li>php80Packages.phpcbf</li>
    <li>php80Packages.phpcs</li>
    <li>php80Packages.phpmd</li>
    <li>php80Packages.phpstan</li>
    <li>php80Packages.psalm</li>
    <li>php80Packages.psysh</li>
    <li>qcachegrind</li>
    <li>rss-bridge-cli</li>
    <li>wp-cli</li>
    <li>yle-dl</li>
  </ul>
</details>
<details>
  <summary>7 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/top-level/php-packages.nix:327:11:
```
    |
327 |           (fetchpatch {
    |           ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/top-level/php-packages.nix:240:7:
```
    |
240 |       installPhase = ''
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/top-level/php-packages.nix:430:11:
```
    |
430 |           (pkgs.writeText "zend_file_cache_config.patch" ''
    |           ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/top-level/php-packages.nix:103:7:
```
    |
103 |       meta.maintainers = lib.teams.php.members;
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/top-level/php-packages.nix:122:7:
```
    |
122 |       meta.maintainers = lib.teams.php.members;
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/top-level/php-packages.nix:359:11:
```
    |
359 |           (fetchpatch {
    |           ^
```
</li>
    <li>warning: unused-argument

Unused argument: `fetchgit`.
Near pkgs/top-level/php-packages.nix:1:22:
```
  |
1 | { stdenv, lib, pkgs, fetchgit, phpPackage, autoconf, pkg-config, re2c
  |                      ^
```
</li>
  </ul>
</details>

**Comment by stephank** [comment]
Thanks for looking into this. I’m a little worried the URL is unstable, because it’s a commit on my fork. If upstream does not merge it as-is, I may break it in the future.

I noticed it is only upstream `master` that results in incompatible patches. Once upstream fixes it in 7.4 or 8.0, those commits should apply cleanly to either version.

**Comment by Ma27** [comment]
That shouldn't be a problem as it points to the source revision itself and since it's part of a PR (and uses github.com/php-src/php) the URL should be (relatively) stable.

**Comment by risicle** [comment]
`nixpkgs-review` happy for me, macos 10.15 & nixos x86_64

**Pull request merged**
