### PR TITLE
nano-wallet: 20.0 -> 21.3

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

Update Nano (cryptocurrency) wallet.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 116780` at d131e019 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/92f5e62a4b75db99406f22a092101938">nano-wallet</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/applications/blockchains/nano-wallet/default.nix:35:3:
```
   |
35 |   buildPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`checkPhase` should probably contain `runHook preCheck` and `runHook postCheck`.

Near pkgs/applications/blockchains/nano-wallet/default.nix:39:3:
```
   |
39 |   checkPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@jluttine can you mark it broken for aarch64?

**Comment by jluttine** [comment]
@SuperSandro2000 But didn't it build fine on aarch64?

> Result of `nixpkgs-review pr 116780` at [d131e01](https://github.com/NixOS/nixpkgs/commit/d131e01943d179122abae714d47a5f1725d3bd49) run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package built successfully:
> 
>     * [nano-wallet](https://gist.github.com/92f5e62a4b75db99406f22a092101938)

Or what don't I understand?

**Comment by SuperSandro2000** [comment]
> Or what don't I understand?

Yeah, if you look at ofborg it failed.

**Comment by jluttine** [comment]
@SuperSandro2000 Do you mean this: https://github.com/NixOS/nixpkgs/pull/116780/checks?check_run_id=2146441484

It just seems to timeout. It really takes a long time to build nano-wallet. On my machines about 30-40min I guess. So, I suppose, it might timeout because of 3600s limit. Not sure, but that's how it looks to me. Can't see any real failure, just a timeout.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Do you mean this: [#116780 (checks)](https://github.com/NixOS/nixpkgs/pull/116780/checks?check_run_id=2146441484)
> 
> It just seems to timeout. It really takes a long time to build nano-wallet. On my machines about 30-40min I guess. So, I suppose, it might timeout because of 3600s limit. Not sure, but that's how it looks to me. Can't see any real failure, just a timeout.

oh yeah... lets wait what hydra will say about it.

**Pull request merged**
