### PR TITLE
kubo: 0.17.0 -> 0.18.1

### PR DESCRIPTION
**Pull request by Luflosi**
###### Description of changes
https://github.com/ipfs/kubo/releases/tag/v0.18.0
https://github.com/ipfs/kubo/releases/tag/v0.18.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Luflosi** [comment]
#209304 needs to be merged before this PR.

**Comment by lourkeur** [comment]
I noticed that `meta.description` is a bit wrong now that Kubo has been renamed. Kubo is "An IPFS implementation in Go" (Github tagline) not "A global, versioned, peer-to-peer filesystem".

**Comment by Luflosi** [comment]
I updated the description.

**Comment by Luflosi** [comment]
Rebased.

Since #209304 was merged, this PR is now ready.

**Review by fabianhjr — APPROVED** [review]
Build, ran, works, NixOS x86_64

**Comment by K900** [comment]
Uhh why me? ^^"

**Comment by fabianhjr** [comment]
Someone to merge if the review so far is enough :'v

(Need a nixpkgs/committer)

**Comment by fabianhjr** [comment]
TY @K900 :3

**Comment by Luflosi** [comment]
Thanks!

**Pull request merged**
