### PR TITLE
warmux: 11.04.1 -> unstable-2017-10-20

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change

Gna.org forge is closed but someone was kind enough to clone the repo on GitHub and even
add some fixes on top of it.

/cc @7c6f434c 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Commit log seems OK; dunno if it is a good idea to check that inital import corresponds to a version we know from Gna…

**Review by 7c6f434c — APPROVED** [review]

**Comment by c0bw3b** [comment]
Hard to check it though; the last known source we have in cache is a release tarball and the first commit of the GH repo is a clone of the former gna.org forge taken some time after the 11.04.1 release. :/

**Comment by 7c6f434c** [comment]
A continuation, not really a clone, though… A continuous history from 11.04 would be nice but oh well, not much we can do.

**Comment by timokau** [comment]
Couldn't we just check out 11.04 on the clone and diff the source with the last-known release tarball?

**Comment by 7c6f434c** [comment]
It starts with a single-commit import of an old head.

**Pull request merged**
