### PR TITLE
Revert "chirp: 20161018 -> 20170311"

### PR DESCRIPTION
**Pull request by ndowens**
Reverts NixOS/nixpkgs#24094

### CODE REVIEW

**Comment by fpletz** [comment]
Why? What are you doing?!

**Comment by ndowens** [comment]
I left a comment # in a push

**Comment by fpletz** [comment]
What?

**Comment by ndowens** [comment]
I left a commented line I planned to remove if it wasn't needed

**Comment by fpletz** [comment]
So why revert the commit and push it again? Do you know how to use git?

**Comment by the-kenny** [comment]
Also, is there any reason for the immediately-merged PRs? You can just push your commits directly to master and prevent a lot of noise (in the commits as well as in other contributor's emails)

**Pull request merged**
