### PR TITLE
wordpress: packages for plugins and themes

### PR DESCRIPTION
**Pull request by onny**
###### Motivation for this change

I packaged some Wordpress themes and plugins in the subset ``wordpressPackages.plugins`` and ``wordpressPackages.themes``. These packages can be used in a Wordpress installation like this:

```
services.wordpress = {
  webserver = "caddy";
  sites."blog.${config.networking.domain}" = {
    plugins = with wordpressPackages.plugins; [
      anti-spam-bee
      code-syntax-block
      lightbox-with-photoswipe
      wp-gdpr-compliance
    ];
    themes = [ wordpressPackages.themes.geist ];
  };
};
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
#96910

**Comment by onny** [comment]
> #96910

Oh I wasn't aware of [wp4nix](https://git.helsinki.tools/helsinki-systems/wp4nix). Is this something we could get merged into nixpkgs? Would be cool to have Wordpress packages in there too.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124383` at 1758c907 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/2e97fa358239fc839efa022f0bf53ca4">wordpressPlugins.webp-converter-for-media</a></li>
  </ul>
</details>
<details>
  <summary>14 packages built successfully:</summary>
  <ul>
    <li>wordpressPlugins.anti-spam-bee</li>
    <li>wordpressPlugins.async-javascript</li>
    <li>wordpressPlugins.breeze</li>
    <li>wordpressPlugins.co-authors-plus</li>
    <li>wordpressPlugins.code-syntax-block</li>
    <li>wordpressPlugins.disable-xml-rpc</li>
    <li>wordpressPlugins.jetpack</li>
    <li>wordpressPlugins.lightbox-with-photoswipe</li>
    <li>wordpressPlugins.opengraph</li>
    <li>wordpressPlugins.simple-login-captcha</li>
    <li>wordpressPlugins.wp-gdpr-compliance</li>
    <li>wordpressPlugins.wp-statistics</li>
    <li>wordpressPlugins.wp-user-avatar</li>
    <li>wordpressThemes.geist</li>
  </ul>
</details>
<details>
  <summary>29 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:127:5:
```
    |
127 |     buildInputs = [ pkgs.unzip ];
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/web-apps/wordpress/plugins.nix:25:14:
```
   |
25 |       inherit pluginName unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:83:5:
```
   |
83 |     buildInputs = [ pkgs.unzip pkgs.php ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/servers/web-apps/wordpress/themes.nix:27:7:
```
   |
27 |       installPhase = "mkdir -p $out; cp -R * $out/";
   |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:25:14:
```
   |
25 |       inherit pluginName unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:105:5:
```
    |
105 |     buildInputs = [ pkgs.unzip ];
    |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `path`.
Near pkgs/servers/web-apps/wordpress/themes.nix:19:5:
```
   |
19 |     path ? lib.getName themeName,
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/web-apps/wordpress/plugins.nix:25:14:
```
   |
25 |       inherit pluginName unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:182:5:
```
    |
182 |     buildInputs = [ pkgs.unzip ];
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:138:5:
```
    |
138 |     buildInputs = [ pkgs.unzip ];
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/web-apps/wordpress/themes.nix:25:14:
```
   |
25 |       inherit themeName unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:61:5:
```
   |
61 |     buildInputs = [ pkgs.unzip ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:94:5:
```
   |
94 |     buildInputs = [ pkgs.unzip ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/servers/web-apps/wordpress/themes.nix:25:14:
```
   |
25 |       inherit themeName unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:171:5:
```
    |
171 |     buildInputs = [ pkgs.unzip ];
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:149:5:
```
    |
149 |     buildInputs = [ pkgs.unzip ];
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:25:14:
```
   |
25 |       inherit pluginName unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: unused-argument

Unused argument: `src`.
Near pkgs/servers/web-apps/wordpress/themes.nix:12:5:
```
   |
12 |     src,
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:40:5:
```
   |
40 |     buildInputs = [ pkgs.unzip ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:160:5:
```
    |
160 |     buildInputs = [ pkgs.unzip ];
    |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `src`.
Near pkgs/servers/web-apps/wordpress/plugins.nix:12:5:
```
   |
12 |     src,
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:27:7:
```
   |
27 |       installPhase = "mkdir -p $out; cp -R * $out/";
   |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/servers/web-apps/wordpress/themes.nix:25:14:
```
   |
25 |       inherit themeName unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:72:5:
```
   |
72 |     buildInputs = [ pkgs.unzip ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:50:5:
```
   |
50 |     buildInputs = [ pkgs.unzip ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/plugins.nix:116:5:
```
    |
116 |     buildInputs = [ pkgs.unzip ];
    |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `path`.
Near pkgs/servers/web-apps/wordpress/plugins.nix:19:5:
```
   |
19 |     path ? lib.getName pluginName,
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

unzip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/wordpress/themes.nix:40:5:
```
   |
40 |     buildInputs = [ pkgs.unzip ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/web-apps/wordpress/themes.nix:25:14:
```
   |
25 |       inherit themeName unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by onny** [comment]
I changed the package attributes according to wp4nix:
```
nix-shell -p wordpressPackages.plugins.jetpack
```
and for themes:
```
nix-shell -p wordpressPackages.themes.geist
```
Most of the plugins and themes have version tags so that the zip download url is fixed to a specific version.

@ajs124 @mohe2015 The pull request mentioned above looks interesting. It addresses several issues and contains breaking changes, so it's a bigger thing and maybe not so easy to merge? In how far does it relate to packaging of plugins and themes?

**Comment by ajs124** [comment]
> Most of the plugins and themes have version tags so that the zip download url is fixed to a specific version.

People republish these versions by pushing to the same subversion tag regularly.

**Comment by mohe2015** [comment]
@onny
> Most of the plugins and themes have version tags so that the zip download url is fixed to a specific version.

This was actually a problem we faced because the plugins can update their contents without updating the version. This is one reason ajs124 wrote the script that downloads them from svn.

> ajs124 mohe2015 The pull request mentioned above looks interesting. It addresses several issues and contains breaking changes, so it's a bigger thing and maybe not so easy to merge?

I'm currently waiting for https://github.com/NixOS/nixpkgs/pull/84446 to get merged and would probably try again to get it merged then.
The first three commits are easy improvements and should be fairly easy to get merged.
Changing the default database name makes it easier to create multiple wordpress services but is a breaking change (well stateVersion).
Changing the prefix of the apache service name is not required but may be benefical. Unfortunately this would break with the nginx PR so maybe I should think about it now.
Removing the version from the theme folder name is probably the most important change as otherwise wordpress is almost unusable if a theme doesn't store the settings in a way this doesn't break. But this is also a breaking change which is unfortunate.
Allowing a mutable wp-content directory is mostly convenience for testing new plugins and themes or using plugins that don't work with the non-writable approach but then you loose most benefits of the module anyways.
I also added some documentation for changing the hostname but this is also terribly supported by wordpress itself so it's only a documentation change but I would still avoid it if possible.

As ajs124 just said plugin and theme versions are not immutable. Also it's way easier to just use an automatic tool to package and update these.

> In how far does it relate to packaging of plugins and themes?

The main change is the change of the directory names for plugins and themes. Other than that I would strongly recommend to use something like wp4nix (possibly with flakes) and not packaging manually at all.

**Pull request closed without merging**
