### PR TITLE
taskell: 1.4.2 -> 1.4.3

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

Followup for #60363

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions (centos)
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@dtzWill and @BenBals here we go.

**Comment by BenBals** [comment]
Thanks for the mention.

##### Reviewed points

- [ ] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on Linux nixos-beb 4.19.37 #1-NixOS SMP Sat Apr 27 07:36:41 UTC 2019 x86_64 GNU/Linux
- [x] executables tested on Linux nixos-beb 4.19.37 #1-NixOS SMP Sat Apr 27 07:36:41 UTC 2019 x86_64 GNU/Linux
- [ ] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [ ] `meta.platforms` is set
- [x] `meta.maintainers` is set
- [ ] build time only dependencies are declared in `nativeBuildInputs`
- [x] source is fetched using the appropriate function
- [ ] phases are respected
- [ ] patches that are remotely available are fetched with `fetchpatch`

##### Possible improvements

##### Comments
Is meta.maintainers unset or am I just missing it?

**Comment by matthiasbeyer** [comment]
Hmh all meta info is missing. Will fix this ... Maybe tomorrow tho

**Comment by marsam** [comment]
I fixed a minor issue in the last commit, I hope you don't mind
Thanks!

**Pull request merged**
