### PR TITLE
Collection of core package updates with breaking changes

### PR DESCRIPTION
**Pull request by wkennington**
This is a collection of changes which should be merged before the first 16.xx release of nixos. The most problematic and annoying change is gcc5 which sets the c and c++ standard to c11 and c++11 by default up from 89. Almost every core package has been patched / updated to make this change work but I'm sure there are still lots of fringe things that I haven't been able to test and therefore can't validate as working. Getting a hydra build for these changes would be incredibly helpful / insightful.

### CODE REVIEW

**Comment by wkennington** [comment]
cc @vcunat @edolstra

**Comment by vcunat** [comment]
> gcc5 which sets the c and c++ standard to c11 and c++11 by default up from 89

I wonder if it's easier to override this in stdenv so that the default standard remains as before. It might take some time before upstream adapts to this behavior.

**Comment by wkennington** [comment]
Yeah maybe we do that, but unfortunately an override like that might break
things which expect 99 or 11. Can we make the override conditional, only if
a std flag isn't passed?

**Comment by vcunat** [comment]
I don't see a problem in passing ``--std=foo`` twice. My `gcc` isn't complaining, so I assume the last one holds, as usual.

**Comment by edolstra** [comment]
Please don't merge such major change in the future without more review / consensus. For example, you didn't address how we're going to handle the GCC ABI change, and I see you also reintroduced OpenSSH 7 without explaining how we're going to deal with the key type deprecations (401782cb678d2e28c0f7f2d40c6421624f410148). These things should also really be done in separate PRs (e.g. we already have a PR for GCC 5 - https://github.com/NixOS/nixpkgs/pull/7807).

I've reverted this (741bf840dad05cd1728481045466811ae8ae8281).

**Pull request merged**
