### PR TITLE
vala updates

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
See News in commit msg's.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Myybe we should merge the Vala part of https://github.com/NixOS/nixpkgs/pull/60198 first.

**Comment by worldofpeace** [comment]
I'd like to pick https://github.com/NixOS/nixpkgs/pull/60198/commits/393ca4cf70081b09168083cb7acc5b9548835582 here and then it can be dropped from that pr if that sounds reasonable?

**Review by jtojnar — APPROVED** [review]

**Comment by jtojnar** [comment]
Other than that 0.42 commit message links to 0.40 news

**Comment by worldofpeace** [comment]
Fixed the commit msg. Self merging :smile:

**Comment by dtzWill** [comment]
AFAICT vala 0.44.3 on current staging doesn't build, because the graphviz patch fails to apply :(.

**Comment by worldofpeace** [comment]
Fix incoming shortly :+1:

**Comment by worldofpeace** [comment]
patch for vala 0.44.3 fixed in 3b481dfdf9e258b0354885c971a7d2edffd39292

it was rejected because https://gitlab.gnome.org/GNOME/vala/commit/911973341ff70d6b6b00ce612d99e0aaf699106d

**Comment by dtzWill** [comment]
On Fri, 03 May 2019 12:31:33 -0700, worldofpeace <notifications@github.com> wrote:
> patch for vala 0.44.3 fixed in 3b481dfdf9e258b0354885c971a7d2edffd39292
> 
> it was rejected because https://gitlab.gnome.org/GNOME/vala/commit/911973341ff70d6b6b00ce612d99e0aaf699106d

Ah, that'd do it.  Thanks for the quick turnaround! \o/

**Pull request merged**
