### PR TITLE
wl-screenrec: 0.1.3 -> 0.1.4-unstable-2024-07-28

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

Includes support for FFmpeg 7. We can’t use the release tag because of a Cargo build issue; see <https://github.com/russelltg/wl-screenrec/issues/77>. Hopefully there’ll be a new release tag soon.

Diff: <https://github.com/russelltg/wl-screenrec/compare/v0.1.3...b817accf1d4f2373cb6f466f760de35e5b8626bd>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by colemickens** [comment]
For some reason, when I applied this and tried to build:

```
╰🡒  nix build .#wl-screenrec
warning: Git tree '/home/cole/code/nixpkgs' is dirty
warning: 'https://cache.flakehub.com' does not appear to be a binary cache
error: hash mismatch in fixed-output derivation '/nix/store/m27m32kwvdldbj7zb201wknz8r2kigj8-wl-screenrec-0.1.4-unstable-2024-07-28-vendor.tar.gz.drv':
         specified: sha256-dspknmYRb3BakKxGuJe05q1mSFRjTUfCXxSQJTDYtJQ=
            got:    sha256-AYirjrnk8SGTXk5IjzCep2AQJYPbgHAOOf47MUDYj4k=
error: 1 dependencies of derivation '/nix/store/4sg27hl2mb6j9p279wvd3s5d6g17hxnc-wl-screenrec-0.1.4-unstable-2024-07-28.drv' failed to build
```

**Comment by emilazy** [comment]
Uh, oops. I suspect I forgot to update the Cargo hash at some point when juggling versions, because I get the same hash if I clear it out. Try now?

**Review by colemickens — APPROVED** [review]
I didn't test it locally, but it builds and runs on my server enough to print help text.

**Comment by colemickens** [comment]
@ofborg test

**Comment by colemickens** [comment]
@ofborg evall

**Comment by colemickens** [comment]
@ofborg eval

**Comment by emilazy** [comment]
It’s just really slow these days. No rush, though – I didn’t actually test this out locally either, I’m just here to remove `ffmpeg_4` dependencies :)

**Comment by colemickens** [comment]
lol ofborg, I already approved! Looks like it's just waiting on darwin, I'm going to merge it.

**Comment by emilazy** [comment]
Thanks!

**Pull request merged**
