### PR TITLE
nixosTests.keepassxc: Add regression test for #163482

### PR DESCRIPTION
**Pull request by turion**
###### Description of changes

Tries to add a regression test for #163482 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
@underscore-j I tried to capture your instructions to reproduce the bug, but the test succeeds. See the changed test. You can run it with:

```
$ nix-build . -A nixosTests.keepassxc.driverInteractive
$ ./result/bin/nixos-test-driver --interactive
```

**Comment by underscore-j** [comment]
If you add `qt5.enable = true;` so the settings are actually effective, it does indeed crash.

**Comment by underscore-j** [comment]
(btw, it suffices to click on 'open existing database' to provoke a crash, in case you want the test to not take as long)

**Comment by turion** [comment]
@underscore-j Thanks, with your help I was able to make a regression test, reproduce the bug and fix it.

**Comment by turion** [comment]
@ofborg test keepassxc

**Comment by turion** [comment]
CC @jonafato

**Comment by turion** [comment]
Regression test works on my machine now, and the issue is fixed. @underscore-j can you test?

**Comment by joba00002** [comment]
issue is fixed for me when building from your branch.

**Comment by turion** [comment]
@ofborg test keepassxc

**Comment by underscore-j** [comment]
> Regression test works on my machine now, and the issue is fixed. @underscore-j can you test?

Yes, everything now works as expected. Thanks!

**Pull request merged**
