### PR TITLE
haskellPackages.llvm-ffi: dynamically pick LLVM version

### PR DESCRIPTION
**Pull request by sternenseemann**
## Description of changes

The question is if this will be guaranteed going forward, @thielema?

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thielema** [comment]
Automatically binding to the most recent LLVM version is tough. LLVM moves quickly and breaks things from time to time. E.g. LLVM-17 removes a lot of old stuff, but its replacements are not available before LLVM-13. That's why I have not released an LLVM-17 compatible llvm-ffi to Hackagae. That is, I cannot promise that the latest `llvm-ffi` at Hackage always supports the current LLVM major version in Nix. I'd prefer to bump the used LLVM version manually. Sometimes it may need an additional Cabal flag to set in `llvm-ffi`.

**Comment by sternenseemann** [comment]
We are not binding it to the most recent LLVM version. We are simply dispatching to the LLVM version matching the major version of llvm-ffi. I. e. the update to LLVM 17 will only happen when you release llvm-ffi `== 17.*`.

**Comment by thielema** [comment]
On Thu, 4 Jan 2024, sternenseemann wrote:

> We are not binding it to the most recent LLVM version. We are simply 
> dispatching to the LLVM version matching the major version of llvm-ffi. 
> I. e. the update to LLVM 17 will only happen when you release llvm-ffi 
> == 17.*.

I see. I would still prefer to select LLVM version manually, because 
chances are good that I can always select the preferred Nix LLVM version 
using a Cabal flag.

**Comment by sternenseemann** [comment]
Is it completely irrelevant which LLVM version is picked?

**Comment by thielema** [comment]
On Fri, 5 Jan 2024, sternenseemann wrote:

> Is it completely irrelevant which LLVM version is picked?

Every llvm-ffi release supports a range of LLVM versions. llvm-ffi only 
exposes a subset of LLVM's C interface, namely the one needed by the 
higher level interface llvm-tf. E.g. llvm-ffi-16.0 supports LLVM-4 to 
LLVM-16, whereas llvm-ffi-17.0 will only support LLVM-13 to LLVM-17. You 
may choose the used LLVM version via a Cabal flag like llvm1300.

**Pull request closed without merging**
