### PR TITLE
devilutionx: 1.4.1 -> 1.5.0

### PR DESCRIPTION
**Pull request by aanderse**
###### Things done

todo:
- test
- package `simpleini` because _appears_ that `devilutionx` will support a system provided `simpleini` now

---

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by karolchmist** [comment]
Hey @aanderse ! Thank you for the PR. 

Unfortunately it crashes when I start going through the menu. 

So first the intro videos play. Then after a first `Enter` in the main menu the sounds disappears, and after a second `Enter` it completely freezes. 

I can reproduce it on two different PCs, under i3 + xfce4, on both shareware and full GOG version of Diablo.

There is no error message, and nothing interesting if run with `--verbose` flag.

Can you reproduce it as well?

**Comment by aanderse** [comment]
I get this repeated many times followed by a crash:

```
ERROR: Missing font kerning: fonts\24-00.bin
ERROR: Error
Failed to open file:
fonts\grayui.trn

Couldn't open /nix/store/szmaj1vv8snmlqzks30c1mn0ph1q31wa-devilutionx-1.5.0/bin/assets/fonts/grayui.trn
ERROR: Error
Failed to open file:
ui_art\diablo.pal
```

I thought the `mpq` we build contains these resources... :thinking:

**Comment by icodeforyou-dot-net** [comment]
@karolchmist @aanderse any updates on this PR? I was thinking about open an issue on this today...

**Comment by aanderse** [comment]
Unfortunately I won't be able to return to this PR for at least another few weeks so please feel free to open an issue.

**Comment by karolchmist** [comment]
@icodeforyou-dot-net yes it would be great! 

I tried to figure it out, but I've failed since I have zero C++ skills :disappointed:

**Comment by icodeforyou-dot-net** [comment]
Yeah I might create an issue today or tomorrow. I want this mission critical piece of software up and running again on the newest release to run it over Zerotier.

**Comment by TheBrainScrambler** [comment]
I've been trying to run it too, but had freezes too. However it looks like the freeze happens after a certain amount of time, and not when trying to enter some menu. If I span `Enter` when running the game I can get to the menu to load a singleplayer game, and then it freezes.

> I get this repeated many times followed by a crash:
> 
> ```
> ERROR: Missing font kerning: fonts\24-00.bin
> ERROR: Error
> Failed to open file:
> fonts\grayui.trn
> 
> Couldn't open /nix/store/szmaj1vv8snmlqzks30c1mn0ph1q31wa-devilutionx-1.5.0/bin/assets/fonts/grayui.trn
> ERROR: Error
> Failed to open file:
> ui_art\diablo.pal
> ```
> 
> I thought the `mpq` we build contains these resources... 🤔

https://github.com/diasurgical/devilutionX/blob/master/docs/installing.md

fonts.mpq is a file provided by upstream, and is only required for certain translations. So if you don't have it it's normal to get errors related to fonts.

I've tried to compare the logs from running `devilutionx --verbose` on 1.4.1 and 1.5.0, but they are the same, with just the order of some lines beings changed and differents directories in the nix store being referred, which is normal. So nothing in the logs, and it looks like this is a nix issue ... I'm clueless

**Comment by karolchmist** [comment]
So [devilutionx 1.5.1](https://github.com/diasurgical/devilutionX/releases/tag/1.5.1) was released last week, and I tried it on this branch. The progress is, now it crashes before the main menu, with an error message :tada: 

```
VERBOSE: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
ERROR: Missing file: fonts\24-00.pcx
ERROR: Error loading font: fonts\24-00.clx
[1]    50663 segmentation fault (core dumped)  /nix/store/m19m8adj3sv9sm7r2ca89znjxknwhis8-devilutionx-1.5.1/bin/devilutionx
```

**Comment by undyamon** [comment]
So, I tried to test the build locally with 1.5.1 (basically updating the version and the `rev` and `hash` fields of all custom dependencies). Once in the menu, the game freezes on the second press of a button (so I can go down twice, or up twice or inside a menu entry, etc) but no error or report is displayed.

I don't know if this helps but the appimage version of the game, run with `appimage-run`, works and does not freeze.

**Comment by aanderse** [comment]
oof... if someone gets motivated we should consider asking upstream for some help

any takers?

**Pull request closed without merging**
