### PR TITLE
python3Packages.{textfsm,hijri-converrter,token-bucket}: update

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
https://github.com/google/textfsm/releases/tag/v1.1.2
https://github.com/falconry/token-bucket/releases/tag/0.3.0
https://github.com/dralshehri/hijri-converter/releases/tag/v2.1.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
`pinnwand` fails with

```
  ERROR: Could not find a version that satisfies the requirement token-bucket<0.3.0,>=0.2.0 (from pinnwand)
  ERROR: No matching distribution found for token-bucket<0.3.0,>=0.2.0
```

**Comment by mweinelt** [comment]
Thanks, fixed in https://github.com/NixOS/nixpkgs/pull/128904/commits/bcd5b09634ff12cb426661c125b44984e27ef576.

**Comment by risicle** [comment]
On macos 10.15, looks like `python39Packages.token-bucket` is a little flaky, failing on `test_conforming_ratio` occasionally

```
>       assert target_ratio < actual_ratio < ratio_max
E       assert 0.698 < 0.62
```

**Review by risicle — APPROVED** [review]
Otherwise, no new test failures, macos 10.15, nixos x86_64

**Pull request merged**
