### PR TITLE
maintainers: add khushraj

### PR DESCRIPTION
**Pull request by khrj**
Superseeds https://github.com/NixOS/nixpkgs/pull/128765 @mweinelt 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Is there anything in particular you'd like to maintain? Usually maintainer objects are created when you start maintaining some package.

**Comment by KhushrajRathod** [comment]
@mweinelt yes, I'm creating a nix package for https://github.com/dprint/dprint, I'm still figuring it out but I should be done in an hour or so

**Comment by Artturin** [comment]
This should be included as a commit in that pr

**Comment by KhushrajRathod** [comment]
Ah I see, thanks

**Comment by KhushrajRathod** [comment]
https://github.com/NixOS/nixpkgs/pull/128784

**Pull request closed without merging**
