### PR TITLE
steam: fix steamrt trying to use a missing setup.sh

### PR DESCRIPTION
**Pull request by puffnfresh**
I was getting the following error after a Steam update:

    internal error: /steamrt/setup.sh is missing, this runtime is invalid or corrupted

The script is used to put things on PATH but it doesn't seem we need to do that.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by benley — APPROVED** [review]
I ran into the same issue and this fixed it for me, thank you

**Comment by baracoder** [comment]
Is it required to backport for 19.03?

**Comment by benley** [comment]
> Is it required to backport for 19.03?

I think so, yes.  Totally forgot that the system where I encountered it was running 19.03.

**Comment by matthew-piziak** [comment]
Is this part of `https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz`?  I'm not sure if I'm reading this right: http://howoldis.herokuapp.com/

In any case I am still getting this error on that channel.

**Comment by benley** [comment]
It looks like it hasn't made its way into nixos-unstable yet, but it does show up in the nixos-unstable-small channel if you want to try that one.  Personally I just cherry-picked the commit onto a local checkout of nixos-unstable (from https://github.com/NixOS/nixpkgs-channels)

**Comment by matthew-piziak** [comment]
Oh interesting. I think I know how to do that. If I fork `nixpkgs-channels` then I can make my own tarball to pull. Thank you @benley!

**Comment by benley** [comment]
Also technically you don't need to make a tarball if you just want to use it locally.  You can do something like `nixos-rebuild -I nixpkgs=~/path/to/nixpkgs-channels` and it will build using your working copy on disk.

**Comment by matthew-piziak** [comment]
For the record `nixpkgs-unstable-small` works perfectly. Thanks!

And yeah, that's true but I'd rather have something hosted than I can share between machines; and something in my `configuration.nix`, since I like things specified in a version-controlled file, rather than ephemerally in a command line argument. Nevertheless thank you for the suggestion!

**Pull request merged**
