### PR TITLE
grafana-mimir: add initial module

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

initial module for grafana mimir
tested with the following config

```
  services.mimir = {
    enable = true;
    configuration = {
      multitenancy_enabled = false;

      blocks_storage = {
        backend = "filesystem";
        bucket_store = {
          sync_dir = "/var/lib/mimir/tsdb-sync";
        };
        filesystem = {
          dir = "/var/lib/mimir/data/tsdb";
        };
        tsdb = {
          dir = "/var/lib/mimir/tsdb";
        };
      };

      compactor = {
        data_dir = "/var/lib/mimir/compactor";
        sharding_ring = {
          instance_addr = "127.0.0.1";
          kvstore = {
            store = "memberlist";
          };
        };
      };

      distributor = {
        ring = {
          instance_addr = "127.0.0.1";
          kvstore = {
            store = "memberlist";
          };
        };
      };


      ingester = {
        ring = {
          instance_addr = "127.0.0.1";
          kvstore = {
            store = "memberlist";
          };
          replication_factor = 1;
        };
      };

      ruler = {
        rule_path = "/var/lib/mimir/data-ruler";
        ring = {
          instance_addr = "127.0.0.1";
        };
      };

      ruler_storage = {
        backend = "local";
        local = {
          directory = "/var/lib/mimir/rules";
        };
      };

      server = {
        http_listen_port = 9009;
        log_level = "warn";
        # loki is listening on 9095 by default
        grpc_listen_port = 9096;
      };

      store_gateway = {
        sharding_ring = {
          replication_factor = 1;
          instance_addr = "127.0.0.1";
        };
      };
      
      activity_tracker = {
        filepath = "/var/lib/mimir/metrics-activity.log";
      };
      
      memberlist = {
        bind_addr = ["127.0.0.1"];
      };
    };
  };
```

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
@bryanhonof you might be interested

**Comment by bryanhonof** [comment]
That looks a lot like what I was writing already :).  Although I also added the following to the config attribute.
```nix
{
    systemd.tmpfiles.rules = [
      "d ${cfg.dataDir}/rules 0755 ${cfg.user} ${cfg.group}"
      "d ${cfg.dataDir}/tsdb-sync 0755 ${cfg.user} ${cfg.group}"
    ];
}
```
Otherwise mimir would complain about it not finding those directories. Maybe we can get the directories that have to be created from the `configuration` attribute?

---
Maybe we could brainstorm together about how are we going to handle mimir in its [microserverices mode](https://grafana.com/docs/mimir/latest/operators-guide/architecture/deployment-modes/#microservices-mode). Since, with this module, it's currently only capable of being deployed in its [monolith mode](https://grafana.com/docs/mimir/latest/operators-guide/architecture/deployment-modes/#monolithic-mode). My initial idea was the following.

Have a list of strings that indicate what components will be enabled e.g.
```nix
{
    services.mimir = {
        enable = true;
        components = [ "ingester" "distributor" ];
    };
}
```

And then based from that list deploy multiple systemd services representing one component. But perhaps it isn't a good idea to define multiple systemd services per NixOS module.

Or we can enable components depending on whats in the `configuration` attribute. E.g. if  `configuration.compactor` exists, we know the compactor has to be enabled.

Or we could just ignore the micro services mode altogether :). If we implement it however, we'd also have to take a look at the [Loki NixOS module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/monitoring/loki.nix). As both [architectures are quite similar](https://grafana.com/docs/loki/latest/fundamentals/architecture/components/).

**Comment by happysalada** [comment]
going to merge for now, but happy to take feedback anytime.

**Comment by bryanhonof** [comment]
@happysalada Oh, no harm done at all! Just did a brain dump here :). If you're interested in discussing the idea further, you could message me on matrix `@bjth:matrix.org`.

**Comment by happysalada** [comment]
Here is some thoughts regarding what you mentioned.

- I was thinking of running with `DynamicUser` so as not to require a specific user and group to run mimir. Security wise it seems better.
- regarding the tmpfile. Using `StateDirectory` means systemd will create the folder for us. If the user wants to use another dataDir, I think it makes sense to expect the user to create that folder himself.

regarding the microservices it's an interesting idea. I don't think there is any problem with having several systemd services per module. I have to say though, that I don't think I'll have the capacity to implement that. I'm happy to review and test though!

One more improvement that is both for this and the loki module is to add options to the configuration. So that it's discoverable. I have been lazy with both modules, I'm always thinking about waiting until the config is stable. Would be happy to support by testing such an effort as well. (I use these in their most basic form and I'm really not that knowledgeable about both).

**Pull request merged**
