### PR TITLE
monero: 0.13.0.3 -> 0.13.0.4

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
version bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg build monero-gui

**Comment by fuwa0529** [comment]
Thanks @rnhmjoj, I forgot that the gui depends on the cli. Should I drop this PR until the gui can build?

**Comment by rnhmjoj** [comment]
I think the failures are unrelated. I will disable the support for darwin and aarch64 since they have been failing for a while. You could update monero-gui if you want.

**Comment by fuwa0529** [comment]
I'm currently running the cli only, so at least I can test the daemon and wallet. I might get the gui to compile but probably not much test at all since I won't be using it. But thanks for the update.

**Review by rnhmjoj — APPROVED** [review]
I tested it too and everything seems to work. I will update the GUI once this is merged.

**Pull request merged**
