### PR TITLE
jellyfin{,-web}: 10.10.1 → 10.10.2 → 10.10.3

### LINKED ISSUE #356716: Update request: jellyfin{,-web} 10.10.1 → 10.10.2
## Package Information

- Package name: jellyfin/jellyfin-web
- Latest released version: 10.10.2
- Current version on the unstable channel: 10.10.1
- Current version on the stable/release channel: 10.9.11

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@nyanloutre @minijackson @purcell @jojosch 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by vikanezrimaya**
Resolves #356716. Requires .NET SDK update, therefore depends on aa319c6f1e150efc6c21326979d40088c28564a1 (part of #355753, now merged)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by minijackson** [comment]
Looks good, thanks. [Jellyfin 10.10.3](https://github.com/jellyfin/jellyfin/releases/tag/v10.10.3) was released recently, could you update your PR?

**Review by minijackson — APPROVED** [review]
Looks good, thanks!

Tested by building the `smoke-test`, and running the smoke-test interactively for a few minutes.

---

Result of `nixpkgs-review pr 356897` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
  </ul>
</details>

**Comment by minijackson** [comment]
> should I squash, or leave two commits sequentially updating the version?

@vikanezrimaya I think either is fine, you can leave it as is.

**Review by phanirithvij — APPROVED** [review]
```console
$ nix build github:nixos/nixpkgs/refs/pull/356897/merge#nixosTests.jellyfin --no-link --print-out-paths
/nix/store/45aq482brkaaxamjs519c1bq4kk64ac6-vm-test-run-jellyfin
```

**Pull request merged**
