### PR TITLE
treewide: use boolToString function

### PR DESCRIPTION
**Pull request by fpletz**
###### Motivation for this change

Lots of modules define a function to convert bools to `"true"` or `"false"`, so there should be a function in the library for doing exactly that. Using `toString` on a bool returns `"1"` or `""` instead.

### CODE REVIEW

**Review by copumpkin — APPROVED** [review]
Lovely, thanks

**Review by Mic92 — APPROVED** [review]

**Review by globin — APPROVED** [review]

**Comment by copumpkin** [comment]
Okay with three approvals I'm just going to merge 😄

**Comment by vcunat** [comment]
I really wonder how you managed to create `babelToString` :-D

**Comment by copumpkin** [comment]
@vcunat lol I missed that, and no idea. @fpletz I'm curious, any ideas how that appeared? 😄

**Comment by fpletz** [comment]
Ah, sorry, I've been messing with https://www.irif.fr/~jch/software/babel/ a lot lately. :smile:

**Pull request merged**
