### PR TITLE
jitsi-meet: 1.0.4628 -> 1.0.4938

### PR DESCRIPTION
**Pull request by pkern**
###### Motivation for this change

Jitsi has gotten more functionality visible in the UI in the most recent version over the one that is currently in nixpkgs, there is also a [variety of fixes](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - [x] jitsi-meet test
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
  - [x] Tested the new version on my jitsi-meet server
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by lukegb — APPROVED** [review]
LGTM, giving maintainers right of first refusal.

**Comment by petabyteboy** [comment]
I would prefer if we could update all the components to their latest releases, in case some of the changes depend on each other.

**Comment by pkern** [comment]
They don't seem to update in lockstep, however. So what's "latest" then? Latest `jitsi-meet_<number>` tag? Do we need to stick to a release?

Looking at an actual set of tagged stable releases according to GitHub (i.e. what shows as "latest release") I see 2.0.5765 with jitsi-meet 1.0.4900 (instead of .4938), jitsi-videobridge 2.1-478-gc6da57bd and jicofo 1.0-740. Presumably that'd be all to update?

**Comment by mmilata** [comment]
That seems to correspond to [changelog entries](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md) and [stable .debs](https://download.jitsi.org/stable/). I guess everything else is just "nightly build"?

**Comment by pkern** [comment]
That set of packages together fails both the nixos test and a manual test.

**Comment by pkern** [comment]
I guess that's https://community.jitsi.org/t/jvb-not-connecting/91157/2 - which exceeds my familiarity with Jitsi.

**Comment by pkern** [comment]
nixos test hangs at `journalctl -b -u jicofo -o cat | grep -q 'connected .JID: focus@auth.server'` and on my real server I get this:

```
Apr 25 18:37:54 hallow prosody[13145]: focus.jitsi.kern.pm:component: Component not connected, bouncing error for: <iq from='oqz91punnu4uib_b@jitsi.kern.pm/5XwWiAVf' type='set' to='focus.jitsi.kern.pm' id='7f403d62-3d23-45f9-91f6-b70df7cba5c0:sendIQ'>
```

**Comment by lukegb** [comment]
> nixos test hangs at `journalctl -b -u jicofo -o cat | grep -q 'connected .JID: focus@auth.server'` and on my real server I get this:
> 
> ```
> Apr 25 18:37:54 hallow prosody[13145]: focus.jitsi.kern.pm:component: Component not connected, bouncing error for: <iq from='oqz91punnu4uib_b@jitsi.kern.pm/5XwWiAVf' type='set' to='focus.jitsi.kern.pm' id='7f403d62-3d23-45f9-91f6-b70df7cba5c0:sendIQ'>
> ```

In terms of the NixOS test, it looks like some of the log messages we look for seem to have changed (https://github.com/jitsi/jicofo/blob/stable/jitsi-meet_5390/src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java#L266 --> https://github.com/jitsi/jicofo/blob/stable/jitsi-meet_5765/src/main/java/org/jitsi/impl/protocol/xmpp/XmppProviderImpl.java#L205)

Interestingly in the test connection.getUser() == null... hrm.

**Comment by timhae** [comment]
I tested the package set from the pull review on my server, everything looks good and works as intended. I switched to this PR because I had issues with screensharing in the 20.09 and unstable version of jitsi-meet

**Comment by petabyteboy** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/127236

**Pull request closed without merging**
