### PR TITLE
svxlink: init at 19.09.1

### PR DESCRIPTION
**Pull request by zaninime**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zaninime** [comment]
@rnhmjoj could you have a look on this one too? Thanks. It's pretty trivial.

**Comment by rnhmjoj** [comment]
I can confirm it builds and everything in `/bin` runs.
Qtel is properly wrapped but so are all other tools. Is this necessary? I think that only Qtel is a Qt application. In that case you should disable the hook and manually wrap `Qtel`. See for example [arx-liberatis](https://github.com/NixOS/nixpkgs/blob/7becdb2363ab72847866adbce564b1577de2097a/pkgs/games/arx-libertatis/default.nix#L41) package if you don't know how.

Also I noticed is this error when running `bin/svxlink`

    TclVoiceMail: *** ERROR: The spool directory (/nix/store/p0csgl15hlgamcwqw3cinqbjafhm4wnq-svxlink-19.09.1/var/spool/svxlink/voice_mail) is not writable by the current user or does not exist.

I'm not sure whether it can be ignored (because I haven't configured it) or the software needs some patching to change this path.

**Comment by zaninime** [comment]
@rnhmjoj Thanks a lot for your review. I missed both things actually. Now I fixed it so it's only wrapping `qtel` and not the rest. The spool dir error can be ignored as that is taken from the default configuration file, so it's possible to configure it (and to configure the location of the config file) at runtime.

**Review by rnhmjoj — APPROVED** [review]
Ok, it looks all right to me, now.

**Pull request merged**
