### PR TITLE
elasticsearch: 1.7.2 -> 2.1.0

### PR DESCRIPTION
**Pull request by ghost**
Tested the build and the module.
Did not get it to work with the security manager.

### CODE REVIEW

**Comment by lethalman** [comment]
Elasticsearch 2.x is backwards-incompatible with 1.x. It must not be replaced like that.

**Comment by markWot** [comment]
@lethalman, ok. Should I put them into a different package and module (elasticsearch2)?

**Comment by lethalman** [comment]
@markWot it can be a different .nix in the same folder, and attribute `elasticsearch2`.

**Comment by markWot** [comment]
@lethalman ok thank you very much. I will update it later.

**Pull request closed without merging**
