### PR TITLE
python3Packages.discordpy: 1.2.4 -> 1.2.5, enable, add import checks

### LINKED ISSUE #77457: Discordpy package broken
**Describe the bug**
I'm unable to build discordpy because the build is flagged as broken. Here is what I get:
```
error: Package ‘python3.7-discord.py-0.16.12’ in /nix/store/549qgbwb5af81xis8dy72krdw44p5w01-nixos-19.09.1776.b926503738c/nixos/pkgs/development/python-modules/discordpy/default.nix:35 is marked as broken, refusing to evaluate.
```

**To Reproduce**
1. Install discordpy

**Expected behavior**
It should be built.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - discordpy # https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/python-modules/discordpy
```

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes: #77457

they are better about updating their dependencies

cc @Th0rgal
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Th0rgal** [comment]
Hello, thank you for the PR! I tried to install it but it didn't work though. :(
I cloned your file discordpy.nix into my .config/nixpkgs folder (home-manager) and I tried to build it that way:
```
let
  my-python-packages = python-packages: with python-packages; [
    aiohttp
    pywal
    pygame
    pillow
    requests
    (pkgs.callPackage ./discordpy.nix)
  ];
  python-with-my-packages = python3.withPackages my-python-packages;
```
I've got the other packages but not discordpy: I'm not able to use import discord.
Did I do something wrong?
Here is my entire configuration: https://github.com/Th0rgal/zeus-nix-home

Thank you!

**Comment by jonringer** [comment]
not really sure about the setup, but importing works:

```
[2 built (1 failed), 2 copied (0.8 MiB), 0.2 MiB DL]
error: build of '/nix/store/r1zpj6mi1g5ybalnrh30kmfrmiagbdmb-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/77465
1 package failed to build:
python38Packages.discordpy

1 package built:
python37Packages.discordpy

[0.0 MiB DL]
error: build log of '/nix/store/mvql2m09sii1fiyk1mn9c0ljvw7bxvwf-python3.8-discord.py-1.2.5.drv' is not available
$ nix-shell /home/jon/.cache/nixpkgs-review/pr-77465/shell.nix

[nix-shell:/home/jon/.cache/nixpkgs-review/pr-77465]$ python
Python 3.7.6 (default, Dec 18 2019, 19:23:55)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import discord
>>>
```

**Comment by jonringer** [comment]
failures are from python38Packages.aiohttp
```
[2 built (1 failed), 2 copied (0.8 MiB), 0.2 MiB DL]
error: build of '/nix/store/r1zpj6mi1g5ybalnrh30kmfrmiagbdmb-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/77465
1 package failed to build:
python38Packages.discordpy

1 package built:
python37Packages.discordpy
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build python37Packages.discordpy

**Pull request merged**
