### PR TITLE
drop thunderbird{,-bin} 68

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
I personally don't use Thunderbird much, but I'd rather not have an EOL version in nixpkgs, if there aren't any really good reasons to keep it around.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
I see no reason to keep these.

**Comment by taku0** [comment]
@mweinelt @xfix
Did you succeed to migrate to OpenPGP?

**Comment by vcunat** [comment]
I did, though I don't use it very often.

**Review by taku0 — APPROVED** [review]
LGTM.

**Comment by teto** [comment]
seems like we have a consensus :)

**Comment by xfix** [comment]
> @mweinelt @xfix
> Did you succeed to migrate to OpenPGP?

Yeah.

**Comment by mweinelt** [comment]
Not using Thunderbird anymore, neomutt all the way.

**Pull request merged**
