### PR TITLE
libbpf: 0.6.0 -> 0.6.1

### PR DESCRIPTION
**Pull request by saschagrunert**
###### Motivation for this change

- Update to the latest release
- Format file with nigpkgs-fmt

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by saschagrunert** [comment]
cc @thoughtpolice @vcunat @martinetd

**Review by martinetd — COMMENTED** [review]
looks good to me in itself.
That's more a miss on my part, but let's get bpftrace/bcc tested on libbpf updates too: could you please add

```
  passthru.tests = {
    bpf = nixosTests.bpf;
  };
```
as well?

**Comment by saschagrunert** [comment]
> looks good to me in itself. That's more a miss on my part, but let's get bpftrace/bcc tested on libbpf updates too: could you please add
> 
> ```
>   passthru.tests = {
>     bpf = nixosTests.bpf;
>   };
> ```
> 
> as well?

Yes sure, added the passthru.

**Comment by martinetd** [comment]
> Yes sure, added the passthru.

Thanks!
It looks like it didn't test it though, perhaps we need to add nixosTests to the file's inputs? I'm not sure why it didn't throw an error instead of not doing anything so not sure if it's required, but I don't have other ideas why it wouldn't run.

**Review by vcunat — APPROVED** [review]
The version change just adds two small fixes: https://github.com/libbpf/libbpf/releases/tag/v0.6.1

**Comment by zowoq** [comment]
> It looks like it didn't test it though, perhaps we need to add nixosTests to the file's inputs?

https://github.com/NixOS/nixpkgs/pull/152156

**Comment by vcunat** [comment]
Uh, I missed the comment and the evaluation error?

**Comment by zowoq** [comment]
`ofborg` [doesn't evaluate `passthru`](https://github.com/NixOS/ofborg/issues/524) but IIRC it would have errored on hydra.

**Pull request merged**
