### PR TITLE
minimal-bootstrap.kaem-minimal: remove kaem-minimal as unused

### PR DESCRIPTION
**Pull request by emilytrau**
###### Description of changes

Remove `minimal-bootstrap.kaem-minimal` package as it is no longer needed in the bootstrap chain. Thanks @Ericson2314 for catching!

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilytrau** [comment]
Continues #227914

**Comment by asymmetric** [comment]
@emilytrau will you be linking all related PRs to #227914 like you did above? Asking cause I'd like to follow along.

**Comment by Ericson2314** [comment]
Oh while it is needed, I don't mind keeping it. My questioning it on IRC was not supposed to imply I didn't want it!

My hope is long term to have a "commuting" bootstrap, where there are many ways to get to the same result. (This works best with CA derivations, were we can literally assert that store paths the same.) So for that, who knows, maybe `kaem-minimal` would be useful?

Your call: if you still think we should get rid of it (and I suppose we rather have redundancies not in `hex0`), we can merge it.

**Comment by Ericson2314** [comment]
(Come to think of it, a tool to take a derivation graph, topo sort it, and splat out a kaem minimal file would be a neat trick!)

**Pull request closed without merging**
