### PR TITLE
nheko: 0.4.0 -> 0.4.1

### PR DESCRIPTION
**Pull request by Ekleog**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
let's see if this builds on darwin
@GrahamcOfBorg  build nheko

**Comment by xeji** [comment]
Did this build on Darwin before? (Can't find Darwin version on Hydra).
Anyway, please try to fix the Darwin build or restrict to `platforms.linux`.

**Comment by Ekleog** [comment]
It had never been built on darwin before AFAIK (at least not by ofborg, and I never received notification by hydra on darwin builds).

I've just tried to push a fix, hopefully that should make things build. Could you re-trigger a build? :)

**Comment by xeji** [comment]
@GrahamcOfBorg build nheko

**Comment by xeji** [comment]
Thanks. Looks promising but I have no idea how to fix the new error. Unless you want to give it another try, I'd say we merge it as is and let whoever wants to use this on Darwin fix it.

**Comment by Ekleog** [comment]
Let's see if this does it, hopefully it will just work now :)

**Comment by xeji** [comment]
@GrahamcOfBorg build nheko

**Comment by xeji** [comment]
Thank you!

**Pull request merged**
