### PR TITLE
openafs_1_8: 1.8.5 -> 1.8.6

### PR DESCRIPTION
**Pull request by andersk**
###### Motivation for this change

Now that `linux_latest` is 5.6, OpenAFS fails to build without these changes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
  - Succeeded: `linuxPackages-libre.openafs_1_8 linuxPackages.openafs_1_8 linuxPackages_4_14.openafs_1_8 linuxPackages_4_19.openafs_1_8 linuxPackages_4_4.openafs_1_8 linuxPackages_4_9.openafs_1_8 linuxPackages_5_5.openafs_1_8 linuxPackages_5_6.openafs_1_8 linuxPackages_latest-libre.openafs_1_8 linuxPackages_latest_xen_dom0.openafs_1_8 linuxPackages_xen_dom0.openafs_1_8 openafs_1_8`.

    Failed: `linuxPackages_hardened.openafs_1_8 linuxPackages_latest_hardened.openafs_1_8 linuxPackages_latest_xen_dom0_hardened.openafs_1_8 linuxPackages_testing_bcachefs.openafs_1_8 linuxPackages_testing_hardened.openafs_1_8 linuxPackages_xen_dom0_hardened.openafs_1_8`.

    (The incompatibility with the hardened variant is [not a regression](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.linuxPackages_hardened.openafs_1_8.x86_64-linux).)
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Cc @maggesi @spacefrogg

### CODE REVIEW

**Review by spacefrogg — CHANGES_REQUESTED** [review]
I would like to defer this until the 1.8.6 release or at least split it off such that 1.8.5 is used on compatible kernels and 1.8.6pre* is used only on 5.6 kernels. When deployed, AFS is usually a central piece of infrastructure and pre-releases had issues in the past. So, I wouldn't like to surprise anyone with a breaking minor release update.

**Comment by Mic92** [comment]
Does 1.8.6pre2 works with 1.8.5 userland? Than we can make the module depending on the kernel version.

**Comment by Mic92** [comment]
I made a PR that only cherry-pick the 5.6er fixes into openafs: https://github.com/NixOS/nixpkgs/pull/88552

**Comment by spacefrogg** [comment]
> Does 1.8.6pre2 works with 1.8.5 userland? Than we can make the module depending on the kernel version.

It _usually_ works out. It is, though, neither supported nor recommended by upstream. Given the significance of a working AFS, my comment above still applies. I would suggest marking it broken on 5.6 kernels until 1.8.6 is released. It would only disturb client updates and no pure server setups.

I know this is an nuisance and it is successfully haunting distribution maintainers since the first release of OpenAFS. Let's hope for kafs...

**Comment by Mic92** [comment]
Can we close this and wait for the next proper release of openafs?

**Comment by andersk** [comment]
1.8.6 is released now; updated.

**Comment by Mic92** [comment]
We might want to backport this to 20.03 because linux 5.7 is also present there.

**Comment by andersk** [comment]
Opened #91867 for the backport.

**Pull request merged**
