### PR TITLE
got: 0.77 -> 0.78

### PR DESCRIPTION
**Pull request by afh**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by wahjava — APPROVED** [review]

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 199469` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>got</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Comment by bobby285271** [comment]
The x86_64-darwin build is [already failing on hydra](https://hydra.nixos.org/job/nixpkgs/trunk/got.x86_64-darwin).

**Comment by afh** [comment]
Thanks for reporting @bobby285271 :pray:

There is [a comment by @abathur](https://github.com/NixOS/nixpkgs/issues/154203#issuecomment-1013933110) on issue #154203 stating that:

> it seems like the SDK version is biting us again a bit on making this jump. […] seeing missing symbol failures for open_memstream (on x86_64-darwin, at least) from https://github.com/tpoechtrager/cctools-port/commit/86cf74fd50016550703435302c33c17474759666

For what it's worth: I'm able to reproduce the build issue locally myself, but do not know how to address it.

**Comment by afh** [comment]
ℹ️ #207993 should fix the x86_64-darwin build issues.

**Pull request merged**
