### PR TITLE
xanmod-kernels: update

### PR DESCRIPTION
**Pull request by Atemu**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Shawn8901** [comment]
Likely there is a typo on the lts commit, as the version is 6.1.16 not 6.1.17

**Comment by Atemu** [comment]
Good catch, thanks!

**Comment by Atemu** [comment]
Btw @Shawn8901, [I see you use xanmod](https://github.com/Shawn8901/nix-configuration/blob/bc5ace9f941592d3684e62e1fd506a5676537f0d/machines/pointalpha/hardware.nix#L26) and I've seen you comment on PRs a few times. If you want to add yourself as a maintainer, go right ahead!

**Comment by Shawn8901** [comment]
> Btw @Shawn8901, [I see you use xanmod](https://github.com/Shawn8901/nix-configuration/blob/bc5ace9f941592d3684e62e1fd506a5676537f0d/machines/pointalpha/hardware.nix#L26) and I've seen you comment on PRs a few times. If you want to add yourself as a maintainer, go right ahead!

i`ve cherry-picked the update to my custom nixpkgs branch and can give feedback if the lts bump  does work on my machine setup after that build has finished. Tho i am building that on x86-64-v3 my rebuilds take quite a while as i have a lot of stuff to rebuild. :slightly_smiling_face:

**Review by Shawn8901 — APPROVED** [review]
lts variant works fine so far for me as i can tell.

**Comment by Atemu** [comment]
@wegank this doesn't need to go through staging. The rebuilds are just kernel modules.

**Pull request merged**
