### PR TITLE
nixos/amdgpu: remove

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/111551#issuecomment-802082766

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
I think this is fine :)

**Comment by sternenseemann** [comment]
Probably there was some reason to introducing this module in <https://github.com/NixOS/nixpkgs/commit/b4821ece01818a4702b332e9bc54b093c50d5d7a> which I don't know. Maybe there is some valid reason for this existing and we can resolve the issue some other way?

Seems to me that removing this module at least *potentially* could break Xorg for some users after upgrading to 21.05.

**Comment by TredwellGit** [comment]
There are some GPUs that support radeon and amdgpu so the module was added to make sure that radeon is not used. I don't know if this is still necessary for these GPUs to prefer amdgpu. I assume that if the radeon driver is loaded first that they will still operate. https://wiki.archlinux.org/index.php/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support

This module does break X for radeon users right now. Maybe users of these SI/CIK cards should write a module.

I have tested that this pull request works with modern amdgpu cards.

**Comment by vcunat** [comment]
Oh, I introduced it?  I have no idea why, after those years (damn the missing explanation), but the motivation you suggest sounds likely.

**Comment by vcunat** [comment]
What do you think about the condition instead?
```nix
config.services.xserver.videoDrivers == [ "amdgpu" ]
```
That's assuming there are devices that can be handled by both kernel drivers and radeon may get preferred.

**Comment by kanashimia** [comment]
Using amdgpu driver on a SI/CIK card requires setting those kernel parameters:
```nix
boot.kernelParams = [ 
  # For SI - Southern Islands (GCN 1) cards.
  "radeon.si_support=0" "amdgpu.si_support=1"
  # For CIK - Sea Islands (GCN 2) cards.
  "radeon.cik_support=0" "amdgpu.cik_support=1"
];
```
So even when radeon is not available - amdgpu won't be used without manually enabling support for such cards, hence why blacklisting radeon module only does harm.

And disabling SI/CIK support for radeon driver should fix issues with it being used, when both drivers are enabled.

Maybe we can add some module that sets those options by demand?

**Comment by TredwellGit** [comment]
So can someone merge this? Seems important for 21.05.

**Comment by vcunat** [comment]
I agree it's important.  I was unsure what exact approach to use, but waiting seems worse than any of them.  We can switch later if the situation becomes clearer.

**Pull request merged**
