### PR TITLE
Build MELPA package sets without null packages

### PR DESCRIPTION
**Pull request by afrepues**
###### Motivation for this change

The current algorithm creates attributes with null values for packages
with no source in a variant of MELPA. Though will satify dependencies
they produce no files, and though a build that transitively depends on
one them will be successful, Emacs won't find them and any code
depending on them won't work.

The solution with minimal code change would have been filtering the
list of results from melpaDerivation by comparing the value against
null, but that leads to an infinite recursion.

This commit also moves legacy renames from the shared to the unstable
set, as the corresponding null value elements won't exist in the
stable set anymore.

The test used for the problem was:

>  $ nix-build --show-trace ./default.nix -A emacs26Packages.melpaStablePackages.findr
>  error: expression does not evaluate to a derivation (or a set or list of those)

The expected output, obtained with this commit is:

>  $ nix-build --show-trace ./default.nix -A emacs26Packages.melpaStablePackages.findr
>  error: attribute 'findr' in selection path 'emacs26Packages.melpaStablePackages.findr' not found

###### Merging into other branches

This can be cleanly merged into [release-20.03](/NixOS/nixpkgs/tree/release-20.03), merging into an older branch will need to be done by cherry picking.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by afrepues** [comment]
@grahamcofborg build emacs26Packages.melpaStablePackages.findr

**Comment by afrepues** [comment]
@adisbladis do you have time to review this?

**Comment by afrepues** [comment]
@adisbladis this affects 20.03 as well, and this branch can be cleanly merged into `release-20.03`. Is it possible to do this directly or is a separate MR necessary?

**Comment by adisbladis** [comment]
@afrepues Could you cherry-pick this on top of 20.03 and send a separate PR? (Use `git cherr-pick -x`).

**Comment by afrepues** [comment]
@adisbladis backport to 20.03 in !86213

**Pull request merged**
