### PR TITLE
nixos/plasma5: add ark as a file archiver

### PR DESCRIPTION
**Pull request by nachoslover813260**
Since the default plasma desktop already got dolphin-plugins adding ark for archiving would make plasma desktop more complete as well

### CODE REVIEW

**Comment by SuperSamus** [comment]
On one hand, it is not listed in the recommended packages to install by default: https://community.kde.org/Distributions/Packaging_Recommendations
On the other hand, stuff like Elisa or Okular are preinstalled, so... I don't know.
Also, `@SuperSandro2000` doesn't like Ark: https://github.com/NixOS/nixpkgs/pull/175738#discussion_r889040370.

**Comment by peterhoeg** [comment]
If we are aiming to have a desktop environment that does most things that most people will need out of the box, then I'm all for including ark as part of the default set.

Sure, some people don't like it, but being on the "path of least surprise" should trump one person's personal preference.

We essentially have these options:

1. leave it out and have people add it manually. This could be handled by having a wiki page or similar that describes "things you probably want to add in after enabling KDE".
2. add it in by default. Some will not use it and others will actively dislike it. And so what? We are not trying to optimize for the smallest possible installation size when talking desktops. Those who don't like it can simply not use it.
3. add it to the optional packages list which means people who really want to can simply remove it through the "excludedPackages" option.
   
   
I'm very much in favour of option 3 though. It will do what most people expect and still allow those die-hards to exclude it.

**Comment by peterhoeg** [comment]
@nachoslover813260, what's your take on adding it to optionalPackages?

**Comment by rski** [comment]
I fully agree on making it optional, in fact I'd personally like to disable dolphin too, so I submitted a PR for that: https://github.com/NixOS/nixpkgs/pull/218994

From what I can tell, making things optional costs next to nothing, while adding to the non-optional package list makes the plasma module less flexible

**Review by rski — CHANGES_REQUESTED** [review]
note that commit messages are prefixed by the package or module being changed, so this PR needs and the commit attached to it need to be

nixos/plasma5: add ark as a file archiver

**Comment by peterhoeg** [comment]
Super, thanks all!

**Pull request merged**
