### PR TITLE
SDL2_net: move headers to "dev" output

### PR DESCRIPTION
**Pull request by trofi**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Cherry-picked to master for testing, only failure this causes for me is `dosbox-staging`.

```
FAILED: src/dos/libdos.a.p/program_serial.cpp.o 
g++ -Isrc/dos/libdos.a.p -Isrc/dos -I../src/dos -I../include -I. -I.. -Isrc/libs/ghc -I../src/libs/ghc -Isrc/libs/loguru -I../src/libs/loguru -I/nix/store/58cdrn1birpig59wqygva9cmsnxh7wwa-SDL2-2.26.4-dev/include -I/nix/store/58cdrn1birpig59wqygva9cmsnxh7wwa-SDL2-2.26.4-dev/include/SDL2 -I/nix/store/y8ab9wi9sldj6y7md833xkbppgimrs>
In file included from ../src/dos/../hardware/serialport/softmodem.h:30,
                 from ../src/dos/program_serial.cpp:27:
../src/dos/../hardware/serialport/misc_util.h:59:10: fatal error: SDL_net.h: No such file or directory
   59 | #include <SDL_net.h>
      |          ^~~~~~~~~~~
```

**Comment by trofi** [comment]
Good catch! Let's see if it's just a matter of missing `meson` dependency in `dosbox-staging`. Looking.

**Comment by trofi** [comment]
Proposed `dosbox-staging` fix against `master` as https://github.com/NixOS/nixpkgs/pull/226491

**Comment by Artturin** [comment]
```
diff --git a/pkgs/applications/emulators/dosbox-staging/default.nix b/pkgs/applications/emulators/dosbox-staging/default.nix
index 62331bd6219..bd1d864b2ff 100644
--- a/pkgs/applications/emulators/dosbox-staging/default.nix
+++ b/pkgs/applications/emulators/dosbox-staging/default.nix
@@ -70,8 +70,8 @@ stdenv.mkDerivation (self: {
   ];
 
   env.NIX_CFLAGS_COMPILE = toString [
-    "-I${SDL2_image}/include/SDL2"
-    "-I${SDL2_net}/include/SDL2"
+    "-I${lib.getDev SDL2_image}/include/SDL2"
+    "-I${lib.getDev SDL2_net}/include/SDL2"
   ];
 
   desktopItems = [
```

**Pull request merged**
