### PR TITLE
python311Packages.dvc-data: 0.36.2 -> 0.38.1

### PR DESCRIPTION
**Pull request by superherointj**
* python311Packages.dvc-data: 0.36.2 -> 0.38.1
* python311Packages.dvc-objects: 0.19.0 -> 0.19.3
* python311Packages.sqltrie: 0.0.27 -> 0.0.28

fixes #215100

### CODE REVIEW

**Comment by NickCao** [comment]
@ofborg build dvc

**Comment by NickCao** [comment]
See https://github.com/NixOS/nixpkgs/pull/213038

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 214755` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>dvc</li>
    <li>dvc-with-remotes</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python310Packages.dvc-data</li>
    <li>python310Packages.dvc-objects</li>
    <li>python310Packages.sqltrie</li>
    <li>python311Packages.dvc-data</li>
    <li>python311Packages.dvc-objects</li>
    <li>python311Packages.sqltrie</li>
  </ul>
</details>

**Comment by NickCao** [comment]
Includes: https://github.com/NixOS/nixpkgs/pull/215100

**Comment by superherointj** [comment]
> Includes: #215100

Will review.

**Comment by NickCao** [comment]
dvc-objects: https://github.com/iterative/dvc-objects/compare/0.19.0...0.19.3

**Comment by NickCao** [comment]
dvc-data: https://github.com/iterative/dvc-data/compare/0.36.2...0.38.1

**Comment by superherointj** [comment]
> dvc-objects: [iterative/dvc-objects@0.19.0...0.19.3](https://github.com/iterative/dvc-objects/compare/0.19.0...0.19.3)
> dvc-data: [iterative/dvc-data@0.36.2...0.38.1](https://github.com/iterative/dvc-data/compare/0.36.2...0.38.1)

What do you mean?

**Comment by NickCao** [comment]
Reviewed changes in dvc-objects and dvc-data, nothing packaging related.

**Review by NickCao — APPROVED** [review]

**Pull request merged**
