### PR TITLE
perl538Packages.CSSDOM: fix build

### PR DESCRIPTION
**Pull request by tu-maurice**
## Description of changes

CSSDOM's test failed due to the deprecated use of a package seperator. There's a patch upstream, but it hasn't been merged yet. The corresponding ticket has been idle since August.

See https://rt.cpan.org/Public/Bug/Display.html?id=146661

This adds the patch directly to nixpkgs, because the perl bug tracker seems to refuse automated downloads.

ZHF: #265948

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stigtsp** [comment]
Thx, waiting for staging-next to be merged as it contains 64f82333aae1657df4bb232320ed71f92816b9d1 affecting this package

**Comment by tu-maurice** [comment]
Your commit fixes this already at the expense of removing a test. Mine uses an upstream patch and keeps the test. The question is do we care for having the test.

**Comment by stigtsp** [comment]
I prefer your solution of patching the test to be honest, feel free to update the PR to also remove my change.

**Review by stigtsp — APPROVED** [review]
LGTM (waiting for eval)

**Pull request merged**
