### PR TITLE
erlang: 25.3.2.12 -> 25.3.2.13; erlang_27: 27.0 -> 27.0.1

### PR DESCRIPTION
**Pull request by chiroptical**
## Description of changes

- https://erlangforums.com/t/patch-package-otp-25-3-2-13-released/3816
- https://erlangforums.com/t/patch-package-otp-27-0-1-released/3824

The 27.0.1 release also allows us to simplify the ex_doc set thanks to

- https://github.com/erlang/otp/pull/8596

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
This PR broke erlang 27. Why was it merged without any checks actually passing? x86_64-linux ran, but it failed.

```
/nix/store/m101dg80ngyjdb02g6jwy80sr7kzj26g-bash-5.2p26/bin/bash: line 1: /nix/store/2wgna59d979j3r3hwx0vjv4mi06dw1d0-ex_doc-0.34.1/bin/.ex_doc-wrapped: cannot execute: required file not found
```

**Comment by happysalada** [comment]
That is my bad ! I misread ofborg.
Do you want to make a revert ?

**Comment by happysalada** [comment]
@chiroptical eould you mind making a PR to revert the erlang 27 change ?

**Comment by chiroptical** [comment]
> @chiroptical eould you mind making a PR to revert the erlang 27 change ?

https://github.com/NixOS/nixpkgs/pull/327631 (sorry missed the comments on this)

**Comment by chiroptical** [comment]
Ohh https://github.com/NixOS/nixpkgs/runs/27351492397 didn't pass.

**Comment by chiroptical** [comment]
I can reproduce this on Linux, but I can't reproduce it building OTP 27.0.1 directly...

**Pull request merged**
