### PR TITLE
Revert "stdenv: label the ephemeral coreutils-stage4 package"

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

https://github.com/NixOS/nixpkgs/pull/169378#discussion_r912407295

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

This reverts commit 23ea8b35dacd9152c9e0e21577d5afe3e39b6255.

### CODE REVIEW

**Comment by vcunat** [comment]
This doesn't look urgent to me, so why target `staging-next`?

**Comment by amjoseph-nixpkgs** [comment]
> This doesn't look urgent to me, so why target `staging-next`?

To prevent the commit-being-reverted from making it to `master`.

If there is no risk of that happening I can change the base branch back to `staging`.

**Comment by amjoseph-nixpkgs** [comment]
> To prevent the commit-being-reverted from making it to `master`.

To clarify: if the commit-being-reverted and the revert are merged to master in separate "batches", it will not break eval or any builds.

But it will two rebuild-everything's for people working at `master`, and perhaps cause some minor confusion when the `pname` of `coreutils` briefly changes to `coreutils-stage4`.  Both of these are entirely my fault.

If neither of those is serious enough for a merge into `staging-next`, just say so and I'll change the base branch.  I don't have a good feel for what the threshhold is for targeting `staging-next`, although I guessed it might be lower in this case since the commit is a revert of something that hasn't yet reached `master`.  I may have guessed wrong there.

**Comment by vcunat** [comment]
Rebuilds: as for the build farm, the thing is that it already has rebuilt coreutils and very many packages depending on it; for users, basically every staging iteration has a stdenv rebuild anyway.

**Comment by vcunat** [comment]
So yes, the two choices are `staging-next` ASAP or &ndash; as I suggested &ndash; deferring to the next staging-next iteration (e.g. merging to `staging`, no need to hurry with that), which would mean that master and channels would contain the in-between state for some time.

**Comment by amjoseph-nixpkgs** [comment]
Thank you for explaining!  I have switched the base branch.

**Comment by Mindavi** [comment]
No worries, it happens :)

**Comment by amjoseph-nixpkgs** [comment]
In case anybody is wondering, here is the full story on what happened here.

While working through the stdenv bootstrapping process in order to make the powerpc64le bootstrap finish, I discovered that there were five packages which were getting built twice (once during the bootstrap phases and then again as part of all-packages.nix):

  gmp mpfr mpc isl coreutils

It was extremely frustrating to always have *two* of each of these in the output of `nix-tree` and `nix-store -q --requisites`!  I was constantly getting mixed up about which "gmp" was the special bootstrap-gmp and which was the "real" gmp.  So I wrote two commits:

```
02630180fad510ee877fa51112b7c7b230ef2f13 stdenv: add -stageX markers to gmp, mpfr, libmpc, and isl
23ea8b35dacd9152c9e0e21577d5afe3e39b6255 stdenv: label the ephemeral coreutils-stage4 package
```

This was extremely helpful to me and got rid of all the confusion.  I included these commits in PR #169378 so others could benefit from the reduced confusion as well.

The double-rebuilding of `gmp`, `mpfr`, `libmpc`, and `isl` is due to the deliberate design of stdenv.  The `*-stageX` versions are compiled statically, in order to prevent `stdenv.cc` from having references to `bootstrap-files`.

**The double-rebuilding of `coreutils`, however, was *not* caused by stdenv.  It was not even caused by anything in nixpkgs.  It was caused by one of my own site-specific overlays.**   I did not realize this.  So I was "fixing" a problem caused by a commit that only I was using! The "fix" worked great for me -- one of my `coreutils` builds had `pname="coreutils-stage4"`, and the other one had `pname="coreutils"`.

Unfortunately for everybody else who didn't have my site-specific problem in the first place, the "fix" simply renamed their one-and-only copy of `coreutils` to `coreutils-stage4`.

The site-specific overlay I have that was causing a double-build of `coreutils` was a `(self: super: ...)` function where the `...` body of the function incorrectly used `super` rather than `self`.

**Comment by amjoseph-nixpkgs** [comment]
> Just here to mention that the home-manager CI tests are currently broken because of the extra `-stage4` (but it looks like this will fix it).

At what commit?  Both the PR which introduced the bug and the PR which fixed it were merged to `master` in the same commit, 2543ab976c892bbdc5afe5bc05fbdbdce264803d.  You should never have seen the unfixed code.

**Comment by amjoseph-nixpkgs** [comment]
> The commit you're pointing to only has the fix, so the breakage was merged earlier: [2543ab9#diff-bf918d7f48f6a34a4a1acb33373dee717cff2c3f5503a7ca41d90e5f289faf1e](https://github.com/NixOS/nixpkgs/commit/2543ab976c892bbdc5afe5bc05fbdbdce264803d#diff-bf918d7f48f6a34a4a1acb33373dee717cff2c3f5503a7ca41d90e5f289faf1e)

The fix (1b94ad9) is in 2543ab9:

```
git merge-base --is-ancestor 1b94ad9 2543ab9 && echo yes
```

**Comment by amjoseph-nixpkgs** [comment]
> The current nixos-unstable, as I said. [e4d49de](https://github.com/NixOS/nixpkgs/commit/e4d49de45a3b5dbcb881656b4e3986e666141ea9)

Yes, you are totally right.  Thank you for being so patient with me.

Merge b39924fc776 brought the bug (23ea8b3) but not the fix (1b94ad9) from staging(-next) to master.

My more serious mistake [was thinking](https://github.com/NixOS/nixpkgs/pull/179961#issuecomment-1173020777) that changing the pname of a package would tend not to break automated things.  I assumed they were mainly for `nix-env`/`nix profile`.  But now I see from the CI failure you linked that home-manager has some neat mechanism for referencing store paths by `pname`, independent of their output address:

```
ExecReload=/nix/store/00000000000000000000000000000000-coreutils-stage4/bin/kill
```

Totally fascinating.  But how do you deal with the situation where the user has two different versions of `coreutils` installed?  That's why I assumed that `pname`s were basically just comments -- because they aren't unique within the store.  When they aren't, `nix-env` forces you to reference them by the store-path of the deriving derivation.

I'll be more careful with `pname`s in the future now that I know they aren't just comment fields for human use.

I apologize for the breakage I caused here.

**Pull request merged**
