### PR TITLE
babashka: 0.0.71 -> 0.0.78

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
https://github.com/NixOS/nixpkgs/pull/83776

**Comment by AndersonTorres** [comment]
@bhougland18 
@bandresen
@DerGuteMoritz 
@mmilata

**Review by bennyandresen — COMMENTED** [review]
LGTM.

Also to your question: To build clojure tools from source we would have to chase a ton of clojure/java dependencies down and package them up for nix first or accept that the package can't be built in sandbox mode.
Using the prepared uberjar is the pragmatic choice.

**Comment by AndersonTorres** [comment]
Maybe some day when he have something like "javaStdenv"...

**Comment by jlesquembre** [comment]
Thanks for working on this!

**Pull request merged**
