### PR TITLE
spatialite-tools: add missing libz dependency

### LINKED ISSUE #332723: Build failure: spatialite_tools
### Steps To Reproduce

1. `nix run nixpkgs/master#spatialite_tools`

### Build log
https://gist.github.com/wildwestrom/0bdb6e0894eadd7ff90abe98a552034c

### Notify maintainers

@dotlambda 
@sikmir 
@afh

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.9, NixOS, 24.05 (Uakari), 24.05.20240309.3030f18`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nix-ld, nixos"`
 - nixpkgs: `/nix/store/nra828scc8qs92b9pxra5csqzffb6hpl-source`


~ took 2s
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by afh**
fixes #332723

## Description of changes

Add `libz` to `buildInputs` as the build was failing with ` ld: library not found for -lz`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by afh** [comment]
Result of `nixpkgs-review pr 332727` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>spatialite_tools</li>
  </ul>
</details>

**Comment by wildwestrom** [comment]
I was the one who originally submitted #332723. Everything seems to be working now on my machine (x86_64, NixOS).

```console
❯ nix run nixpkgs/ba5fe710df27a0e4b2533b5d0d63c5b70feab7d6#spatialite_tools
undefined CMD


usage: spatitalite_tool CMD ARGLIST
==============================================================
CMD has to be one of the followings:
------------------------------------
-h or --help                      print this help message
-v or --version                   print version infos
-i or --import                    import [CSV/TXT, DBF or SHP]
-e or --export-shp                exporting some shapefile

supported ARGs are:
-------------------
-dbf or --dbf-path pathname       the full DBF path
-shp or --shapefile pathname      the shapefile path [NO SUFFIX]
-d or --db-path pathname          the SpatiaLite db path
-t or --table table_name          the db geotable
-g or --geometry-column col_name  the Geometry column
-c or --charset charset_name      a charset name
-s or --srid SRID                 the SRID
--type         [POINT | LINESTRING | POLYGON | MULTIPOINT]

optional ARGs for SHP import are:
---------------------------------
-2 or --coerce-2d                  coerce to 2D geoms [x,y]
-k or --compressed                 apply geometry compression

examples:
---------
spatialite_tool -i -dbf abc.dbf -d db.sqlite -t tbl -c CP1252
spatialite_tool -i -shp abc -d db.sqlite -t tbl -c CP1252 [-s 4326] [-g geom]
spatialite_tool -i -shp abc -d db.sqlite -t tbl -c CP1252 [-s 4326] [-2] [-k]
spatialite_tool -e -shp abc -d db.sqlite -t tbl -g geom -c CP1252 [--type POINT]
```

Trying to do a review however failed.
```console
❯ nix run nixpkgs#nixpkgs-review -- pr 332727
no oauth token found for github.com
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/332727/head:refs/nixpkgs-review/1
$ git worktree add /home/main/.cache/nixpkgs-review/pr-332727-2/nixpkgs 2a13929e1f191b3690dd2f2db13098b04adb9043
Preparing worktree (detached HEAD 2a13929e1f19)
Updating files: 100% (42701/42701), done.
HEAD is now at 2a13929e1f19 postgresqlPackages.timescaledb_toolkit: fix on macos (#332353)
$ git merge --no-commit --no-ff ba5fe710df27a0e4b2533b5d0d63c5b70feab7d6
fatal: refusing to merge unrelated histories
https://github.com/NixOS/nixpkgs/pull/332727 failed to build: Failed to merge ba5fe710df27a0e4b2533b5d0d63c5b70feab7d6 into /home/main/.cache/nixpkgs-review/pr-332727-2/nixpkgs. git merge failed with exit code 128
$ git worktree remove -f /home/main/.cache/nixpkgs-review/pr-332727-2/nixpkgs`
```

**Comment by afh** [comment]
At first glance it seems that the nixpkgs-review failures you reported, @wildwestrom, could stem from an issue specific to your local setup. Are you able to nixpkgs-review other PRs successfully?

**Comment by wildwestrom** [comment]
After running another review, my setup started working (inexplicably).

```console
❯ nix run nixpkgs#nixpkgs-review -- pr 332727
no oauth token found for github.com
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/332727/head:refs/nixpkgs-review/1
From https://github.com/NixOS/nixpkgs
 + d6de18216fda...ba5fe710df27 refs/pull/332727/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /home/main/.cache/nixpkgs-review/pr-332727-3/nixpkgs e16e4d74c55c7780781487cee2325ffc6120e6a7
Preparing worktree (detached HEAD e16e4d74c55c)
Updating files: 100% (42701/42701), done.
HEAD is now at e16e4d74c55c Merge pull request #332199 from illdefined/vapoursynth-new
$ git merge --no-commit --no-ff ba5fe710df27a0e4b2533b5d0d63c5b70feab7d6
Automatic merge went well; stopped before committing as requested
$ nix build --nix-path nixpkgs=/home/main/.cache/nixpkgs-review/pr-332727-3/nixpkgs nixpkgs-overlays=/tmp/tmpiiju9cof --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed -f /home/main/.cache/nixpkgs-review/pr-332727-3/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/332727

1 package built:
spatialite_tools

$ /nix/store/6r0bm8shswm9v08kzvq24ib48mx3kxmn-nix-2.18.1/bin/nix-shell /home/main/.cache/nixpkgs-review/pr-332727-3/shell.nix --nix-path nixpkgs=/home/main/.cache/nixpkgs-review/pr-332727-3/nixpkgs nixpkgs-overlays=/tmp/tmpiiju9cof

[nix-shell:~/.cache/nixpkgs-review/pr-332727-3]$ spa
spa-acp-tool              spatialite_dxf            spatialite_tool
spa-inspect               spatialite_gml            spatialite_xml2utf8
spa-json-dump             spatialite_network        spatialite_xml_collapse
spa-monitor               spatialite_osm_filter     spatialite_xml_load
spa-resample              spatialite_osm_map        spatialite_xml_print
spatialite                spatialite_osm_net        spatialite_xml_validator
spatialite_convert        spatialite_osm_overpass   spawn_console
spatialite_dem            spatialite_osm_raw        spawn_login

[nix-shell:~/.cache/nixpkgs-review/pr-332727-3]$ spatialite
SpatiaLite version ..: 5.1.0	Supported Extensions:
	- 'VirtualShape'	[direct Shapefile access]
	- 'VirtualDbf'		[direct DBF access]
	- 'VirtualText'		[direct CSV/TXT access]
	- 'VirtualGeoJSON'		[direct GeoJSON access]
	- 'VirtualXL'		[direct XLS access]
	- 'VirtualNetwork'	[Dijkstra shortest path - obsolete]
	- 'RTree'		[Spatial Index - R*Tree]
	- 'MbrCache'		[Spatial Index - MBR cache]
	- 'VirtualFDO'		[FDO-OGR interoperability]
	- 'VirtualBBox'		[BoundingBox tables]
	- 'VirtualSpatialIndex'	[R*Tree metahandler]
	- 'VirtualElementary'	[ElemGeoms metahandler]
	- 'VirtualRouting'	[Dijkstra shortest path - advanced]
	- 'VirtualKNN2'	[K-Nearest Neighbors metahandler]
	- 'VirtualGPKG'	[OGC GeoPackage interoperability]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'SpatiaLite'		[Spatial SQL - OGC]
PROJ version ........: Rel. 9.4.1, June 1st, 2024
GEOS version ........: 3.12.2-CAPI-1.18.2
RTTOPO version ......: 1.1.0
TARGET CPU ..........: x86_64-unknown-linux-gnu
the SPATIAL_REF_SYS table already contains some row(s)
SQLite version ......: 3.46.0
Enter ".help" for instructions
SQLite version 3.46.0 2024-05-23 13:25:27
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
spatialite>
```

**Comment by afh** [comment]
Thanks for double-checking, @wildwestrom, much appreciated.

**Comment by wildwestrom** [comment]
No problem. I also think additional review is unnecessary. No functionality should have changed so I just needed to confirm was that the package compiles properly.

**Review by wildwestrom — APPROVED** [review]
LGTM. The functionality shouldn't have changed at all, just fixed the build.

**Comment by wildwestrom** [comment]
I don't really know how things work around here, when should this get into nixos unstable?

**Comment by afh** [comment]
Thanks for the approval, @wildwestrom, much appreciated 👍

I've now labeled this PR as approved and mentioned it over on discourse, this usually helps folks with commit rights to this repo to pick up PRs to merged.
I'd expect this to be merged in the next few days, at the latest within a fortnight.

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 332727` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>spatialite_tools</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
spatialite_tools:
<details>

warning: EvalError
Cannot evaluate attribute ‘spatialite_tools’ in ‘/nix/store/sf46hr0ryyyqnjypbhj49b214bc3sqjp-nixpkgs’.
</details>
</details>

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 332727` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>spatialite_tools</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
spatialite_tools:
<details>

warning: EvalError
Cannot evaluate attribute ‘spatialite_tools’ in ‘/nix/store/47h8kbqc30cj3yb575rwhv2j5n9a884d-nixpkgs’.
</details>
</details>

**Review by gador — APPROVED** [review]

**Pull request merged**
