### PR TITLE
 nixos/woodpecker-server: change type of environmentFile to list of paths 

### PR DESCRIPTION
**Pull request by Janik-Haag**
Makes the module more consistent with it's agent module. 
 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ambroisie — APPROVED** [review]

**Comment by ambroisie** [comment]
I think we could migrate users away from a single string through `coercedTo str (f: [ f ]) list` (+ a warning if the option isn't of `list` type): this would preserve backwards compatibility.

**Comment by Janik-Haag** [comment]
feel free to just push to the pr ^^

**Comment by ambroisie** [comment]
I don't have commit bits, I can't push on somebody else's PR.

**Comment by Janik-Haag** [comment]
> Allowing edits by maintainers
>
> > If checked, users with write access to NixOS/nixpkgs can add new commits to your woodpecker branch. 

hm yeah this reads like it only allows edits if you have commit rights.

I'm not quite sure where you want me to add that:
> coercedTo str (f: [ f ]) list

in the apply module option?

**Comment by ambroisie** [comment]
> I'm not quite sure where you want me to add that:
> 
> > coercedTo str (f: [ f ]) list
> 
> in the apply module option?

It's a type: see [the documentation](https://nixos.org/manual/nixos/unstable/#sec-option-types-composed).

**Comment by Janik-Haag** [comment]
Tested and implemented your suggestion except for the warning part since I'm not quite sure on how to write the assertion for it. Btw thank you for teaching me about `coercedTo`

**Comment by ambroisie** [comment]
Sorry I forgot about the example last time, this should be fine otherwise.

**Comment by Janik-Haag** [comment]
Ah fuck I messed up sorry, I read except for example and thought you meant a example for assertions, sorry. gonna open another pr.

**Pull request merged**
