### PR TITLE
racket: 6.10.1 -> 6.11

### PR DESCRIPTION
**Pull request by oxzi**
###### Motivation for this change
Updates the racket-package to the latest version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by disassembler** [comment]
Builds, runs, no dependencies. Merging! Thanks for the update.

**Comment by bendlas** [comment]
Racket build is failing for me. Any ideas?
@disassembler 
```
libtool: compile:  gcc -g -O2 -Wall -I./.. -I../../../racket/gc2/../include -I../../../racket/gc2/../../rktio -I../../rktio -pthread -DUSE_SENORA_GC -DMZ_USES_SHARED_LIB -c xsrc/numarith.c  -fPIC -DPIC -o .libs/numarith.o
env XFORM_USE_PRECOMP=xsrc/precomp.h ../racketcgc  -cqu ../../../racket/gc2/xform.rkt --setup . --depends --cpp "gcc -E -I./.. -I../../../racket/gc2/../include -I../../../racket/gc2/../../rktio -I../../rktio -pthread   -DUSE_SENORA_GC   -DMZ_USES_SHARED_LIB "  --keep-lines -o xsrc/number.c ../../../racket/gc2/../src/number.c
Error [GCING] 1958 in ../../../racket/gc2/../src/number.c: Function double_is_integer declared __xform_nongcing__, but includes a function call at __isinff128.
Error [GCING] 4050 in ../../../racket/gc2/../src/number.c: Function double_fits_fixnum declared __xform_nongcing__, but includes a function call at __isinff128.
xform: Errors converting
  context...:
   /tmp/nix-build-racket-6.11.drv-0/racket-6.11/src/build/racket/gc2/xform-collects/compiler/private...:8:2: xform
   /tmp/nix-build-racket-6.11.drv-0/racket-6.11/src/build/racket/gc2/xform-collects/xform/xform-mod.rkt: [running body]
   /tmp/nix-build-racket-6.11.drv-0/racket-6.11/src/racket/gc2/xform.rkt: [running body]
make[4]: *** [Makefile:268: xsrc/number.c] Error 1
make[4]: Leaving directory '/tmp/nix-build-racket-6.11.drv-0/racket-6.11/src/build/racket/gc2'
make[3]: *** [Makefile:176: all] Error 2
make[3]: Leaving directory '/tmp/nix-build-racket-6.11.drv-0/racket-6.11/src/build/racket/gc2'
make[2]: *** [Makefile:104: 3m] Error 2
make[2]: Leaving directory '/tmp/nix-build-racket-6.11.drv-0/racket-6.11/src/build/racket'
make[1]: *** [Makefile:58: 3m] Error 2
make[1]: Leaving directory '/tmp/nix-build-racket-6.11.drv-0/racket-6.11/src/build'
make: *** [Makefile:51: all] Error 2
builder for ‘/nix/store/jg5qlq1rr8rds0821yzw7w5bi7xn69a6-racket-6.11.drv’ failed with exit code 2
```

**Comment by geistesk** [comment]
This is interesting.
The build also fails for me on the current master-branch. However, switching back to my `racket-6.11`-branch, which is one commit ahead of 25515ce9280dcb90cffc3fbd15e4ab2ac8ec0e38, works fine. There must be a change in one of the depending packages.
Funfact: Compiling the old nix expression for 6.10.1 on the current master-branch fails with the exact same error. So someone has pushed something with breaks racket without `nox-review`ing it first.

The issue has some similarities with racket/racket#1638.

**Comment by gebner** [comment]
We've already had a similar issue before, see #13733 and upstream https://github.com/racket/racket/issues/1222.

**Comment by gebner** [comment]
I managed to build the git version of racket by patching `xform.rkt`:
```
diff --git a/racket/collects/compiler/private/xform.rkt b/racket/collects/compiler/private/xform.rkt
index f2c0f53360..ca77b74d9a 100644
--- a/racket/collects/compiler/private/xform.rkt
+++ b/racket/collects/compiler/private/xform.rkt
@@ -905,6 +905,7 @@
                strlen cos cosl sin sinl exp expl pow powl log logl sqrt sqrtl atan2 atan2l frexp
                isnan isinf fpclass signbit _signbit _fpclass __fpclassify __fpclassifyf __fpclassifyl
               _isnan __isfinited __isnanl __isnan __signbit __signbitf __signbitd __signbitl
+               __isinff128
                __isinff __isinfl isnanf isinff __isinfd __isnanf __isnand __isinf
                __inline_isnanl __inline_isnan __inline_signbit __inline_signbitf __inline_signbitd __inline_signbitl
                __builtin_popcount __builtin_clz __builtin_isnan __builtin_isinf __builtin_signbit
```

**Comment by gebner** [comment]
So for now I've fixed the build by switching to gcc7.

**Pull request merged**
