### PR TITLE
 pythonPackages.weboob: add pyqt5 as native input

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Address @dotlambda feedback for #57555 after merge
- https://github.com/NixOS/nixpkgs/pull/57555#issuecomment-472638302
- https://github.com/NixOS/nixpkgs/pull/57555#issuecomment-472641284

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
Port to stable so since the last change fixed build, and this makes things nicer.

**Comment by dotlambda** [comment]
I changed it a tiny bit by using `old.src.override`.

**Comment by dotlambda** [comment]
cherry picked in 497b0237a5accdbb75c719c087ea9a18f34b6849 and 9fa2a21ba46d0d46a5666d7a19735479e87cd0df

**Comment by worldofpeace** [comment]
> I changed it a tiny bit by using `old.src.override`.

Nice, more people should do it like that :+1:

**Pull request merged**
