### PR TITLE
podman-desktop: 0.12.0 -> 1.0.1

### LINKED ISSUE #224301: Update request: podman-desktop 0.12.0 → 0.13.0
- Package name: podman-desktop
- Latest released version: 0.12.0

- Current version on the unstable channel: 0.12.0
- Current version on the stable/release channel: N/A

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@panda2134 bad timing with this one, new version right after you got the package merged.

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by NickCao**
Diff: https://github.com/containers/podman-desktop/compare/v0.12.0...1.0.1

Changelog: https://github.com/containers/podman-desktop/releases/tag/v1.0.1

###### Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/224301

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by panda2134** [comment]
This doesn't build on darwin-x86_64:

```
src/extension.ts → dist...
created dist in 1.1s

> podman-desktop@0.13.0 build:extensions:kind
> cd ./extensions/kind && npm run build


> kind@0.0.1 build
> tsc && node ./scripts/build.js


> podman-desktop@0.13.0 build:extensions:registries
> cd ./extensions/registries && npm run build


> registries@0.0.1 build
> rollup --bundleConfigAsCjs --config rollup.config.js --compact --environment BUILD:production  && node ./scripts/build.js


src/extension.ts → dist...
created dist in 888ms
✨  Done in 88.31s.
yarn run v1.22.19
$ /private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/.bin/electron-builder --dir --config .electron-builder.config.cjs -c.electronDist=/nix/store/6n027zxcxkcbhxm5cskqfn5vjapvlhvq-ele>
  • electron-builder  version=23.6.0 os=22.3.0
  • loaded configuration  file=/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/.electron-builder.config.cjs
  • description is missed in the package.json  appPackageFile=/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/package.json
  • author is missed in the package.json  appPackageFile=/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=x64 electron=23.1.1 appOutDir=dist/mac
  • copying Electron  source=/nix/store/6n027zxcxkcbhxm5cskqfn5vjapvlhvq-electron-23.1.1/lib/electron/Electron.app destination=/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/dist/mac/Electron>
  ⨯ corrupted Electron dist  failedTask=build stackTrace=Error: corrupted Electron dist
    at Object.createMacApp (/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/app-builder-lib/src/electron/electronMac.ts:90:11)
    at beforeCopyExtraFiles (/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:86:5)
    at MacPackager.doPack (/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/app-builder-lib/src/platformPackager.ts:285:7)
    at MacPackager.pack (/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/app-builder-lib/src/macPackager.ts:192:7)
    at Packager.doBuild (/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/private/tmp/nix-build-podman-desktop-0.13.0.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by panda2134** [comment]
We might have to [patch this](https://github.com/electron-userland/electron-builder/blob/ac9c33ce0ffec43ec6cb71053b2177a5b872cb48/packages/app-builder-lib/src/electron/electronMac.ts#L90) in electron-builder, because it doesn't work well with nix.

**Comment by NickCao** [comment]
I do not have access to darwin machines, would you like to take this over and have a try?

**Comment by panda2134** [comment]
> I do not have access to darwin machines, would you like to take this over and have a try?

I'm working on this.

**Comment by panda2134** [comment]
`app-builder-bin` failed to read plist files. This seems to be related to Gatekeeper on macOS Ventura. Any clues on confirming this? (since I didn't find any log items related to Gatekeeper in `system.log`)

**Comment by panda2134** [comment]
It is too hard to package the new version under macOS due to changes with electron-builder. I will investigate into this when I have time.

**Comment by NickCao** [comment]
No longer interested in this.

**Pull request closed without merging**
