### PR TITLE
  p2pvc: new package

### PR DESCRIPTION
**Pull request by hmuehlhans**
Added myself to maintainers

### CODE REVIEW

**Comment by jagajaga** [comment]
Whyh did you close

**Comment by hmuehlhans** [comment]
just saw travis ci error and i thought it was from my package but it wasn't

**Comment by jagajaga** [comment]
But if it was about your pkg, then you had to fix pkg, rebase and force push? Don't create PRs for the same pkg if you can fix and repush :)

**Comment by hmuehlhans** [comment]
all right I will remember that thanks :)

**Comment by lethalman** [comment]
Built locally, thanks. Nitpick: don't put a dot at the end of the description. I fixed that for you in another commit.

**Comment by hmuehlhans** [comment]
thank you very much lethalman

**Pull request merged**
