### PR TITLE
inconsolata: 2.001 -> 3.001

### PR DESCRIPTION
**Pull request by appsforartists**
## Description of changes

- Added discretionary coding ligatures in Inconsolata and exposes them by default as Ligconsolata.
- Extended charset to GF Latin Plus, GF Latin Pro
- Improved outline quality

https://github.com/google/fonts/blob/main/ofl/inconsolata/FONTLOG.txt

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by appsforartists** [comment]
@7c6f434c @mikoim I updated the tag and the location in the repo.  I can see all the `ttf`s in `ls $( nix build -A inconsolata)/share/truetype/inconsolata`, but I'm only seeing the 2 old files in `fc-list`.  Can you please help?

**Comment by 7c6f434c** [comment]
The changes look fine… when you run `fc-list`, which version of the `fonts.conf` is in use?

**Comment by appsforartists** [comment]
I don't see a store for them:

```shell
$ fc-list | grep nconsolata
/run/current-system/sw/share/fonts/truetype/inconsolata/Inconsolata-Regular.ttf: Inconsolata:style=Regular
/run/current-system/sw/share/fonts/truetype/inconsolata/Inconsolata-Bold.ttf: Inconsolata:style=Bold
```

But I do see the fonts in that same folder:
```shell
$ ls -la /run/current-system/sw/share/fonts/truetype/inconsolata/
total 8776
dr-xr-xr-x 1 root root   5350 1969-12-31 16:00 .
dr-xr-xr-x 1 root root     22 1969-12-31 16:00 ..
-r--r--r-- 1 root root 108216 1969-12-31 16:00 Inconsolata-Black.ttf
-r--r--r-- 1 root root 107220 1969-12-31 16:00 Inconsolata-Bold.ttf
-r--r--r-- 1 root root 105520 1969-12-31 16:00 Inconsolata-Condensed.ttf
-r--r--r-- 1 root root 107368 1969-12-31 16:00 Inconsolata-CondensedBlack.ttf
-r--r--r-- 1 root root 106948 1969-12-31 16:00 Inconsolata-CondensedBold.ttf
-r--r--r-- 1 root root 106896 1969-12-31 16:00 Inconsolata-CondensedExtraBold.ttf
-r--r--r-- 1 root root 105484 1969-12-31 16:00 Inconsolata-CondensedExtraLight.ttf
-r--r--r-- 1 root root 105872 1969-12-31 16:00 Inconsolata-CondensedLight.ttf
-r--r--r-- 1 root root 106972 1969-12-31 16:00 Inconsolata-CondensedMedium.ttf
-r--r--r-- 1 root root 105580 1969-12-31 16:00 Inconsolata-CondensedRegular.ttf
-r--r--r-- 1 root root 106884 1969-12-31 16:00 Inconsolata-CondensedSemiBold.ttf
-r--r--r-- 1 root root 106552 1969-12-31 16:00 Inconsolata-Expanded.ttf
-r--r--r-- 1 root root 109872 1969-12-31 16:00 Inconsolata-ExpandedBlack.ttf
-r--r--r-- 1 root root 108168 1969-12-31 16:00 Inconsolata-ExpandedBold.ttf
-r--r--r-- 1 root root 109956 1969-12-31 16:00 Inconsolata-ExpandedExtraBold.ttf
-r--r--r-- 1 root root 107880 1969-12-31 16:00 Inconsolata-ExpandedExtraLight.ttf
-r--r--r-- 1 root root 107696 1969-12-31 16:00 Inconsolata-ExpandedLight.ttf
-r--r--r-- 1 root root 108292 1969-12-31 16:00 Inconsolata-ExpandedMedium.ttf
-r--r--r-- 1 root root 106612 1969-12-31 16:00 Inconsolata-ExpandedRegular.ttf
-r--r--r-- 1 root root 108204 1969-12-31 16:00 Inconsolata-ExpandedSemiBold.ttf
-r--r--r-- 1 root root 107272 1969-12-31 16:00 Inconsolata-ExtraBold.ttf
-r--r--r-- 1 root root 105408 1969-12-31 16:00 Inconsolata-ExtraCondensed.ttf
-r--r--r-- 1 root root 107020 1969-12-31 16:00 Inconsolata-ExtraCondensedBlack.ttf
-r--r--r-- 1 root root 106964 1969-12-31 16:00 Inconsolata-ExtraCondensedBold.ttf
-r--r--r-- 1 root root 106740 1969-12-31 16:00 Inconsolata-ExtraCondensedExtraBold.ttf
-r--r--r-- 1 root root 104956 1969-12-31 16:00 Inconsolata-ExtraCondensedExtraLight.ttf
-r--r--r-- 1 root root 105436 1969-12-31 16:00 Inconsolata-ExtraCondensedLight.ttf
-r--r--r-- 1 root root 106180 1969-12-31 16:00 Inconsolata-ExtraCondensedMedium.ttf
-r--r--r-- 1 root root 105468 1969-12-31 16:00 Inconsolata-ExtraCondensedRegular.ttf
-r--r--r-- 1 root root 107228 1969-12-31 16:00 Inconsolata-ExtraCondensedSemiBold.ttf
-r--r--r-- 1 root root 107836 1969-12-31 16:00 Inconsolata-ExtraExpanded.ttf
-r--r--r-- 1 root root 111232 1969-12-31 16:00 Inconsolata-ExtraExpandedBlack.ttf
-r--r--r-- 1 root root 110348 1969-12-31 16:00 Inconsolata-ExtraExpandedBold.ttf
-r--r--r-- 1 root root 110752 1969-12-31 16:00 Inconsolata-ExtraExpandedExtraBold.ttf
-r--r--r-- 1 root root 108764 1969-12-31 16:00 Inconsolata-ExtraExpandedExtraLight.ttf
-r--r--r-- 1 root root 109164 1969-12-31 16:00 Inconsolata-ExtraExpandedLight.ttf
-r--r--r-- 1 root root 109424 1969-12-31 16:00 Inconsolata-ExtraExpandedMedium.ttf
-r--r--r-- 1 root root 107896 1969-12-31 16:00 Inconsolata-ExtraExpandedRegular.ttf
-r--r--r-- 1 root root 109516 1969-12-31 16:00 Inconsolata-ExtraExpandedSemiBold.ttf
-r--r--r-- 1 root root 105732 1969-12-31 16:00 Inconsolata-ExtraLight.ttf
-r--r--r-- 1 root root 105612 1969-12-31 16:00 Inconsolata-Light.ttf
-r--r--r-- 1 root root 106752 1969-12-31 16:00 Inconsolata-Medium.ttf
-r--r--r-- 1 root root 105628 1969-12-31 16:00 Inconsolata-Regular.ttf
-r--r--r-- 1 root root 106836 1969-12-31 16:00 Inconsolata-SemiBold.ttf
-r--r--r-- 1 root root 105792 1969-12-31 16:00 Inconsolata-SemiCondensed.ttf
-r--r--r-- 1 root root 109008 1969-12-31 16:00 Inconsolata-SemiCondensedBlack.ttf
-r--r--r-- 1 root root 107176 1969-12-31 16:00 Inconsolata-SemiCondensedBold.ttf
-r--r--r-- 1 root root 107660 1969-12-31 16:00 Inconsolata-SemiCondensedExtraBold.ttf
-r--r--r-- 1 root root 106216 1969-12-31 16:00 Inconsolata-SemiCondensedExtraLight.ttf
-r--r--r-- 1 root root 106452 1969-12-31 16:00 Inconsolata-SemiCondensedLight.ttf
-r--r--r-- 1 root root 107324 1969-12-31 16:00 Inconsolata-SemiCondensedMedium.ttf
-r--r--r-- 1 root root 105852 1969-12-31 16:00 Inconsolata-SemiCondensedRegular.ttf
-r--r--r-- 1 root root 106732 1969-12-31 16:00 Inconsolata-SemiCondensedSemiBold.ttf
-r--r--r-- 1 root root 106228 1969-12-31 16:00 Inconsolata-SemiExpanded.ttf
-r--r--r-- 1 root root 109792 1969-12-31 16:00 Inconsolata-SemiExpandedBlack.ttf
-r--r--r-- 1 root root 108012 1969-12-31 16:00 Inconsolata-SemiExpandedBold.ttf
-r--r--r-- 1 root root 108584 1969-12-31 16:00 Inconsolata-SemiExpandedExtraBold.ttf
-r--r--r-- 1 root root 107636 1969-12-31 16:00 Inconsolata-SemiExpandedExtraLight.ttf
-r--r--r-- 1 root root 106344 1969-12-31 16:00 Inconsolata-SemiExpandedLight.ttf
-r--r--r-- 1 root root 107516 1969-12-31 16:00 Inconsolata-SemiExpandedMedium.ttf
-r--r--r-- 1 root root 106288 1969-12-31 16:00 Inconsolata-SemiExpandedRegular.ttf
-r--r--r-- 1 root root 108116 1969-12-31 16:00 Inconsolata-SemiExpandedSemiBold.ttf
-r--r--r-- 1 root root 105064 1969-12-31 16:00 Inconsolata-UltraCondensed.ttf
-r--r--r-- 1 root root 107048 1969-12-31 16:00 Inconsolata-UltraCondensedBlack.ttf
-r--r--r-- 1 root root 106308 1969-12-31 16:00 Inconsolata-UltraCondensedBold.ttf
-r--r--r-- 1 root root 106632 1969-12-31 16:00 Inconsolata-UltraCondensedExtraBold.ttf
-r--r--r-- 1 root root 105040 1969-12-31 16:00 Inconsolata-UltraCondensedExtraLight.ttf
-r--r--r-- 1 root root 105136 1969-12-31 16:00 Inconsolata-UltraCondensedLight.ttf
-r--r--r-- 1 root root 106236 1969-12-31 16:00 Inconsolata-UltraCondensedMedium.ttf
-r--r--r-- 1 root root 105124 1969-12-31 16:00 Inconsolata-UltraCondensedRegular.ttf
-r--r--r-- 1 root root 106260 1969-12-31 16:00 Inconsolata-UltraCondensedSemiBold.ttf
-r--r--r-- 1 root root 109516 1969-12-31 16:00 Inconsolata-UltraExpanded.ttf
-r--r--r-- 1 root root 111876 1969-12-31 16:00 Inconsolata-UltraExpandedBlack.ttf
-r--r--r-- 1 root root 111816 1969-12-31 16:00 Inconsolata-UltraExpandedBold.ttf
-r--r--r-- 1 root root 111860 1969-12-31 16:00 Inconsolata-UltraExpandedExtraBold.ttf
-r--r--r-- 1 root root 110040 1969-12-31 16:00 Inconsolata-UltraExpandedExtraLight.ttf
-r--r--r-- 1 root root 110512 1969-12-31 16:00 Inconsolata-UltraExpandedLight.ttf
-r--r--r-- 1 root root 110728 1969-12-31 16:00 Inconsolata-UltraExpandedMedium.ttf
-r--r--r-- 1 root root 109576 1969-12-31 16:00 Inconsolata-UltraExpandedRegular.ttf
-r--r--r-- 1 root root 111508 1969-12-31 16:00 Inconsolata-UltraExpandedSemiBold.ttf
-r--r--r-- 1 root root 107160 1969-12-31 16:00 Ligconsolata-Bold.ttf
-r--r--r-- 1 root root 105636 1969-12-31 16:00 Ligconsolata-Regular.ttf
```

**Comment by 7c6f434c** [comment]
`fc-cache -r` maybe?

**Comment by appsforartists** [comment]
Thanks.  That worked.

**Comment by appsforartists** [comment]
I don't think this needs a release note.  Ready for review.

**Pull request merged**
