### PR TITLE
mimalloc: 2.0.0 -> 2.0.2

### PR DESCRIPTION
**Pull request by mikroskeem**
###### Motivation for this change

General update; Fix macOS support

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mikroskeem** [comment]
Note for future: mimalloc seems to keep two major versions maintained at the same time (at the time of writing). This derivation should've been broken off to `mimalloc_2` when 2.x.x was released, instead of doing 1.x.x -> 2.x.x imo. #116319

Doing this right now is quite late perhaps?

However when new major version is released and upstream keeps two or more major versions updated, then this should be kept in mind.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 128579` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mimalloc</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 128579` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mimalloc</li>
  </ul>
</details>

**Comment by siraben** [comment]
@mikroskeem I think keeping it as is is fine for now. If packages require such a distinction (or break), then it might be good to revisit this.

**Pull request merged**
