### PR TITLE
swaynotificationcenter: 0.9.0 -> 0.10.0

### LINKED ISSUE #377: [Bug] trouble launching bash script
**Please read through the README and the Man pages before submitting**
**Please also make sure that there isn't any prior issue describing this bug**

**Describe the bug**

I am trying to achieve https://github.com/ErikReider/SwayNotificationCenter/issues/323, i.e. copying the content of the notification on click. For some reason it didn't work so I tried to debug the env via:
```
  "scripts": {
    "example-action-script": {
      "exec": "bash -c '/usr/bin/env > /home/teto/swaync-test.txt'",
	  "run-on": "action"
    }
  },
```
but this triggers:
```
Jan 29 08:25:27 jedha swaync[231086]: >: -c: line 1: unexpected EOF while looking for matching `''
```
while I can copy the command in shell just fine. Could it be some parsing issue ?

**Expected behavior**

**Please provide logs if you're experiencing notification errors / bugs**

Attach Gists for swaync logs by running `G_MESSAGES_DEBUG=all swaync` and (if applicable) application logs.
```
Jan 29 10:57:36 jedha systemd[3470]: Starting Swaync notification daemon...
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_fast: "/org/gnome/desktop/peripherals/mouse/" (establishing: 0, active: 0)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_fast: "/org/gnome/desktop/sound/" (establishing: 0, active: 0)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_fast: "/org/gnome/desktop/privacy/" (establishing: 0, active: 0)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_fast: "/org/gnome/desktop/wm/preferences/" (establishing: 0, active: 0)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_fast: "/org/gnome/desktop/a11y/" (establishing: 0, active: 0)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_fast: "/org/gnome/desktop/a11y/interface/" (establishing: 0, active: 0)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_established: "/org/gnome/desktop/interface/" (establishing: 1)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_established: "/org/gnome/desktop/peripherals/mouse/" (establishing: 1)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_established: "/org/gnome/desktop/sound/" (establishing: 1)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_established: "/org/gnome/desktop/privacy/" (establishing: 1)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_established: "/org/gnome/desktop/wm/preferences/" (establishing: 1)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_established: "/org/gnome/desktop/a11y/" (establishing: 1)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_established: "/org/gnome/desktop/a11y/interface/" (establishing: 1)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: Compositor prefers decoration mode 'server'
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: unsetenv() is not thread-safe and should not be used after threads are created
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_fast: "/org/erikreider/swaync/" (establishing: 0, active: 0)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: watch_established: "/org/erikreider/swaync/" (establishing: 1)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: configModel.vala:334: {
                                                 "positionX" : "right",
                                                 "positionY" : "top",
                                                 "layer" : "top",
                                                 "layer-shell" : true,
                                                 "cssPriority" : "application",
                                                 "timeout" : 10,
                                                 "timeout-low" : 5,
                                                 "timeout-critical" : 6,
                                                 "transition-time" : 200,
                                                 "keyboard-shortcuts" : true,
                                                 "image-visibility" : "when-available",
                                                 "notification-window-width" : 500,
                                                 "hide-on-clear" : false,
                                                 "hide-on-action" : true,
                                                 "control-center-positionX" : "none",
                                                 "control-center-positionY" : "none",
                                                 "control-center-margin-top" : 0,
                                                 "control-center-margin-bottom" : 0,
                                                 "control-center-margin-left" : 0,
                                                 "control-center-margin-right" : 0,
                                                 "control-center-layer" : "top",
                                                 "categories-settings" : {  },
                                                 "notification-visibility" : {  },
                                                 "scripts" : {
                                                   "example-action-script" : {
                                                     "exec" : "bash -c '/usr/bin/env > /home/teto/swaync-test.txt'",
                                                     "run-on" : "action"
                                                   }
                                                 },
                                                 "script-fail-notify" : true,
                                                 "fit-to-screen" : true,
                                                 "control-center-height" : 600,
                                                 "control-center-width" : 500,
                                                 "notification-2fa-action" : true,
                                                 "notification-inline-replies" : false,
                                                 "notification-icon-size" : 64,
                                                 "notification-body-image-height" : 100,
                                                 "notification-body-image-width" : 200,
                                                 "widgets" : [
                                                   "buttons-grid",
                                                   "menubar#label",
                                                   "backlight",
                                                   "mpris",
                                                   "volume",
                                                   "inhibitors",
                                                   "title",
                                                   "dnd",
                                                   "notifications"
                                                 ],
                                                 "widget-config" : {
                                                   "buttons-grid" : {
                                                     "actions" : [
                                                       {
                                                         "label" : "直",
                                                         "command" : "~/.config/rofi/rofi-wifi-menu.sh"
                                                       },
                                                       {
                                                         "label" : "<U+F5AE>",
                                                         "command" : "~/.config/rofi/rofi-bluetooth"
                                                       },
                                                       {
                                                         "label" : "<U+F011>",
                                                         "command" : "notify-send -m 'toto'",
                                                         "type" : "toggle"
                                                       },
                                                       {
                                                         "label" : "<U+F011>",
                                                         "command" : "wlogout"
                                                       }
                                                     ]
                                                   },
                                                   "volume" : {
                                                     "label" : "<U+F028>"
                                                   },
                                                   "menubar#label" : {
                                                     "menu#power-buttons" : {
                                                       "label" : "<U+F011>",
                                                       "position" : "right",
                                                       "actions" : [
                                                         {
                                                           "label" : "<U+F021> Reboot",
                                                           "command" : "systemctl reboot"
                                                         },
                                                         {
                                                           "label" : "<U+F023> Lock",
                                                           "command" : "swaylock -f --image ~/.config/wallpapers/snow_woods.jpg"
                                                         },
                                                         {
                                                           "label" : "<U+F08B> Logout",
                                                           "command" : "swaymsg exit"
                                                         },
                                                         {
                                                           "label" : "<U+F011> Shut down",
                                                           "command" : "systemctl poweroff"
                                                         }
                                                       ]
                                                     },
                                                     "menu#powermode-buttons" : {
                                                       "label" : "<U+F829>",
                                                       "position" : "left",
                                                       "actions" : [
                                                         {
                                                           "label" : "Performance",
                                                           "command" : "powerprofilesctl set performance"
                                                         },
                                                         {
                                                           "label" : "Balanced",
                                                           "command" : "powerprofilesctl set balanced"
                                                         },
                                                         {
                                                           "label" : "Power-saver",
                                                           "command" : "powerprofilesctl set power-saver"
                                                         }
                                                       ]
                                                     },
                                                     "buttons#topbar-buttons" : {
                                                       "position" : "left",
                                                       "actions" : [
                                                         {
                                                           "label" : "<U+F5FF>",
                                                           "command" : "grim"
                                                         }
                                                       ]
                                                     }
                                                   },
                                                   "backlight" : {
                                                     "label" : "<U+F5DD>",
                                                     "device" : "intel_backlight",
                                                     "min" : 10
                                                   },
                                                   "inhibitors" : {
                                                     "text" : "Inhibitors",
                                                     "button-text" : "Clear All Notifs",
                                                     "clear-all-button" : true
                                                   },
                                                   "title" : {
                                                     "text" : "Notifications TITLE",
                                                     "clear-all-button" : true,
                                                     "button-text" : "Clear All (or not)"
                                                   },
                                                   "dnd" : {
                                                     "text" : "Do Not Disturb"
                                                   },
                                                   "label" : {
                                                     "max-lines" : 5,
                                                     "text" : "Label Text"
                                                   },
                                                   "mpris" : {
                                                     "image-size" : 96,
                                                     "image-radius" : 12
                                                   }
                                                 }
                                               }
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: factory.vala:42: Loading widget: buttons-grid
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: menubar#label: Config doesn't have key: animation-duration!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: menubar#label: Config doesn't have key: animation-type!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: menubar.vala:176: No animation-type for menu-object given using default
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: menubar#label: Config doesn't have key: animation-duration!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: menubar#label: Config doesn't have key: animation-type!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: menubar.vala:176: No animation-type for menu-object given using default
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: menubar#label: Config doesn't have key: label!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: menubar.vala:167: No label for menu-object given using default
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: menubar#label: Config doesn't have key: animation-duration!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: menubar#label: Config doesn't have key: animation-type!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: menubar.vala:176: No animation-type for menu-object given using default
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: factory.vala:42: Loading widget: menubar
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: backlight: Config doesn't have key: subsystem!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: backlightUtil.vala:41: Could not find device /sys/class/backlight/intel_backlight/brightness
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: factory.vala:42: Loading widget: backlight
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: factory.vala:42: Loading widget: mpris
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: volume: Config doesn't have key: show-per-app!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: volume: Config doesn't have key: empty-list-label!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: volume: Config doesn't have key: expand-button-label!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: volume: Config doesn't have key: collapse-button-label!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: volume: Config doesn't have key: icon-size!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: volume: Config doesn't have key: animation-duration!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: baseWidget.vala:47: volume: Config doesn't have key: animation-type!
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: factory.vala:42: Loading widget: volume
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: factory.vala:42: Loading widget: inhibitors
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: factory.vala:42: Loading widget: title
Jan 29 10:57:36 jedha .swaync-wrapped[734696]: factory.vala:42: Loading widget: dnd
Jan 29 10:57:36 jedha systemd[3470]: Started Swaync notification daemon.
Jan 29 10:58:05 jedha .swaync-wrapped[734696]: notiDaemon.vala:171: Notification: 
                                               category:                 (null)
                                               image_data:                 false
                                               expire_timeout:                 -1
                                               replaces_id:                 0
                                               desktop_entry:                 (null)
                                               body:                         
                                               app_icon:                 
                                               action_icons:                 false
                                               time:                         1706522285
                                               hints:                 
                                                       sender-pid: int64 735084
                                                       urgency: byte 0x01
                                               applied_id:                 1
                                               image_path:                 (null)
                                               inline-reply:                 (null)
                                               app_name:                 notify-send
                                               summary:                 toto
                                               icon_data:                 false
                                               resident:                 false
                                               default_action:                 (null)
                                               actions:                 
                                               urgency:                 Normal
Jan 29 10:58:07 jedha swaync[735125]: >: -c: line 1: unexpected EOF while looking for matching `''
```
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora 37]: nixos
 - Version [e.g. 0.7]
 ```
➜ swaync --version                          
swaync 0.9.0
```
**Additional context**

### PR DESCRIPTION
**Pull request by teto**
## Description of changes

the new version fixes https://github.com/ErikReider/SwayNotificationCenter/issues/377

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 290627` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>swaynotificationcenter</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]
Tested launching `swaync` and sending a notification to it, worked flawlessly.

As usual:
```console
╰─λ ./results/swaynotificationcenter/bin/swaync-client --version
swaync 0.10.0
```

**Comment by leon-erd** [comment]
Version 0.10.0 introduced these three new dependencies: gvfs, granite, sassc (see https://github.com/ErikReider/SwayNotificationCenter/releases/tag/v0.10.0).
According to https://github.com/ErikReider/SwayNotificationCenter/blob/main/build-scripts/PKGBUILD gvfs and granite are runtime dependencies and sassc is a buildtime dependency (if I understand it correctly).
So gvfs and granite should be added to the `buildInputs` while sassc should be added to `nativeBuildInputs` right?
Also https://github.com/NixOS/nixpkgs/commit/b86adcb62880609cf06e14aa210460943eb34e9c introduced the line `substituteInPlace src/functions.vala --replace /usr/local/etc $out/etc` in `postPatch` which is also not needed anymore. Tell me if I'm wrong :grin:

**Comment by leon-erd** [comment]
Also I guess this should be tagged so it can be closed once this is merged :)
https://github.com/NixOS/nixpkgs/issues/290451

**Review by olivatooo — APPROVED** [review]

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 290627` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>swaynotificationcenter</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]

**Comment by leon-erd** [comment]
@teto I mean the release notes explicitly list these as new dependencies. Just have a look at the two links I sent you. Building works fine without gvfs but I guess some features will not work if granite and gvfs are not available as runtime dependencies. But I have asked upstream what they are needed for :)

**Comment by teto** [comment]
if there is an issue with gvfs let's fix it in another PR. This got 2 approvals, let's merge.

**Pull request merged**
