### PR TITLE
calibre: add missing fonttools dependency

### PR DESCRIPTION
**Pull request by 71zenith**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
Can you explain why? Was there some buildtime or runtime error we're fixing here?

**Comment by 71zenith** [comment]
My bad i probably should have left a comment in the first place.
This fixes a runtime error when im trying to change the font in an epub, calibre cannot locate the font even though its in the system. It does not explicitly say that fonttools is missing (or I have failed to notice if it says)
I looked into the arch package and it listed fonttools as the dependency.

**Comment by 71zenith** [comment]
Relevant: 
https://archlinux.org/packages/extra/x86_64/calibre/
https://github.com/kovidgoyal/calibre/blob/master/setup/arch-ci.sh

**Comment by eclairevoyant** [comment]
Please provide the full steps to reproduce the error, then we can verify if this PR actually fixes the issue.

**Comment by 71zenith** [comment]
Steps
1. Download the [sample-epub](https://github.com/IDPF/epub3-samples/releases/download/20230704/accessible_epub_3.epub)
2. Open file in calibre. Right-click on the file and Click on "Edit Book"
3. Go to tools from the top menu and click "Manage Fonts"
4. Try to "Install font" and add any font file [e.g.](https://github.com/openmaptiles/fonts/raw/master/noto-sans/NotoSans-Regular.ttf). It will result with error such as
```
ERROR: Unhandled exception: <b>FileNotFoundError</b>:[Errno 2] No such file or directory: '/home/zen/.config/calibre/fonts/Poppins-Regular.ttf'
```
5. Now try the above with fonttools as a listed python dependency

**Review by eclairevoyant — COMMENTED** [review]
Thanks for the steps.
It does clear the error, but it doesn't seem to add the font. I'm unsure what to check next as there's no error/stacktrace

**Comment by 71zenith** [comment]
You will need to "Change Selected font" and enter the font you have installed previously. Without fonttools, it would straight up fail stating it "It does not exist". 
With fonttools, you will be able to change the font given that you have gone through "install fonts" previously. Rest, if you want to see the font in action, you can try to remove all the other font and only keeping the one you installed.

**Review by wfdewith — CHANGES_REQUESTED** [review]
@71zenith This PR needs to be rebased on master for the new `by-name` file structure. Also, in #338867 (created shortly after this PR), `fonttools` was added to the check dependencies, but that should be removed in this PR as well (after rebasing), since it is a full runtime dependency.

See my commit here that I made before I realized that there was already a PR for this issue: https://github.com/NixOS/nixpkgs/commit/419b631de5728f002c76cdd55611de08b582eeb3.

**Comment by wfdewith** [comment]
Made obsolete by #366152

**Pull request closed without merging**
