### PR TITLE
kakounePlugins.quickscope-kak: init at 1.0.0

### PR DESCRIPTION
**Pull request by eraserhd**
###### Motivation for this change

New Kakoune plugin

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eraserhd** [comment]
@AndersonTorres can you merge this one?

**Comment by AndersonTorres** [comment]
I am running the tests.

**Comment by AndersonTorres** [comment]
No outputs?

Result of `nixpkgs-review pr 106548` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by eraserhd** [comment]
@AndersonTorres I'm not sure how `nixpkgs-review` works, but maybe it's not catching this because it needs to be configured as a Kakoune plugin.  I'm using my fork of nixpkgs with this in my config: https://github.com/eraserhd/dotfiles/blob/develop/kakoune/default.nix#L21

I know I can't build from master without commenting out quicksope-kak, and I'm definitely using it regularly...

`nix-build . -A kakounePlugins.quickscope-kak` also works for me.

```
jfelice@C02CW0J5ML87 nixpkgs (dogfood)
$ nix-build . -A kakounePlugins.quickscope-kak
/nix/store/d220k3fnbf0iwwdawc55980mkdy2zs81-quickscope-kak-1.0.0

jfelice@C02CW0J5ML87 nixpkgs (dogfood)
$ find -L result
result
result/share
result/share/kak
result/share/kak/autoload
result/share/kak/autoload/plugins
result/share/kak/autoload/plugins/quickscope.lua
result/share/kak/autoload/plugins/quickscope.kak
result/share/kak/autoload/plugins/quickscope.asciidoc

```

**Comment by AndersonTorres** [comment]
So it is OK to me.

**Pull request merged**
