### PR TITLE
[WIP] sage: use proper overlays

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

Sage has lots of dependencies and integrates tightly with them. Some of them have to be (temporarily) pinned at older versions. Currently that is done by simply using `<pkg>.override`. But since there are so many dependencies, they are likely to depend on each other. That makes it necessary to "wire them up" using lots of `inherit`'s (as seen in #43679).

Since `packageOverrides` was deprecated, I'm unsure how to solve this. Here I use the variant mentioned in the manual, but not used anywhere in nixpkgs (yet). That re-imports nixpkgs however:

```
sagepkgs = import nixpkgs.path {
    overlays = [ ... ];
}
```

Is this a terrible idea? Will this lead to even more memory consumption? Will this ignore all previous user-defined overlays? Is there a better way?

@grahamc @matthewbauer @7c6f434c @FRidh 

Other than the change from simple `.override` to overlays nothing has changed. So there is no need to review the details here (although you're of course free to do so).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
`packageOverrides` is to override the package set from outside of it. Overlays are considered the superior solution and it is thus replacing it.

In this case, what is needed is a new scope. All the sub package sets use this as well, see e.g. Qt5:
```
libsForQt59 = lib.makeScope qt59.newScope mkLibsForQt5;
```

**Comment by timokau** [comment]
> Re-importing nixpkgs is very ugly, and all the user overlays will be lost inside of the reimport, not to mention system and configuration settings.

Yeah that's what I feared. I wish it was as easy as it is with the python package set.

> In this case, what is needed is a new scope.

Can you help me with that? Unfortunately it seems like that isn't documented anywhere. I would need a scope that has all of the regular nixpkgs, but with some overrides. All the scopes I'm aware of only have new packages, not the rest of nixpkgs.

> In order to make it possible to modify some of the Sage-specific overrides

That's probably overkill. At best there shouldn't be any sage specific overrides at all, whenever possible I try to backport compatibility patches instead.

**Comment by FRidh** [comment]
@timokau see https://github.com/FRidh/nixpkgs/commit/c6a649a424b1379d9c5f7c757797abb309dcf585

The `withDoc` part will need to be fixed though.

**Comment by FRidh** [comment]
Might as well finish it right away as well:
https://github.com/NixOS/nixpkgs/commit/c6e27de8352e856890561ad5b259de670d0921f0

Please test.

**Comment by timokau** [comment]
Thanks! Thats a lot to read through, I'll do that and test it tomorrow.

**Comment by timokau** [comment]
Unfortunately that does break the build:

```
Error compiling Cython file:
------------------------------------------------------------
...
from sage.libs.gmp.mpz cimport *
from sage.libs.flint.fmpz_poly cimport *
from sage.libs.flint.nmod_poly cimport *
from sage.libs.flint.ulong_extras cimport *

from cypari2.paridecl cimport (GEN, cgetg, t_POL, set_gel, gel, stoi, lg,
^
------------------------------------------------------------

sage/schemes/elliptic_curves/descent_two_isogeny.pyx:33:0: 'cypari2/paridecl/hyperellratpoints.pxd' not found
```

I'll figure out the details when I have more time.

Regarding the changes in general:

```
lib.fix' (lib.extends overrides (lib.extends packages (self: pkgs // {callPackage = pkgs.newScope self;})))
```

What does that do? I know what `lib.fix` is supposed to do, but I don't know about the rest.

```
sagePackages = callPackage ../applications/science/math/sage { };
```

Will this show up in search results?

**Comment by FRidh** [comment]
> Unfortunately that does break the build:

I think there is something not OK with the `callPackage` here, or we have to explicitly pass in things with `self`.

```
lib.fix' (lib.extends overrides (lib.extends packages (self: pkgs // {callPackage = pkgs.newScope self;})))
```

Create a new package set that extends `pkgs` with a `callPackage` that looks into the current `self` when passing arguments to function calls:
```
self: pkgs // {callPackage = pkgs.newScope self;}
```
Take our "overlay" of modifications and extend our new package set with it:
```
lib.extends packages (self: pkgs // {callPackage = pkgs.newScope self;})
```
Extend once more with `overrides` "overlay" and then fix the final set:
```
lib.fix' (lib.extends overrides (lib.extends packages (self: pkgs // {callPackage = pkgs.newScope self;})))
```

**Comment by FRidh** [comment]
> Will this show up in search results?

No, we don't recurse into that attribute set so it won't show up in say `nix-env -q` or `nix search`. But, you can access the attributes.

**Comment by FRidh** [comment]
The issue is that `cypari2` doesn't use our version of `pari`. So, something is not yet correct with this new method.

**Comment by FRidh** [comment]
[This](https://github.com/FRidh/nixpkgs/commit/5aa92b6c94b002b602299f55f48ad0e2f6b390ae) should do the trick, although I'm not sure whether that can go in as I expect it to take up some memory.

**Comment by timokau** [comment]
Also if `fix -> fix'` isn't acceptable, can't we use the same mechanism overlays use to make it possible to do deep overrides from within nixpkgs? Its not a unique sage problem, sage just needs it at a bigger scale than most packages. `pythonPackages` offers it, why not `nixpkgs`?

**Comment by FRidh** [comment]
> Should those overlaps in namespaces be considered an issue and fixed? They lead to pretty subtle bugs...

They're annoying, but package names eventually will overlap. That's one reason why we use namespaces.

> Are there reasons for this? Wouldn't it be nicer to treat python pkgs and "regular" pkgs as uniformly as possible?

Python libraries belong in the Python package set. That way we're also preventing possible naming collisions.

> Also if `fix -> fix'` isn't acceptable, can't we use the same mechanism overlays use to make it possible to do deep overrides from within nixpkgs? Its not a unique sage problem, sage just needs it at a bigger scale than most packages. `pythonPackages` offers it, why not `nixpkgs`?

We are using the same mechanism: the package set we've defined here is exactly the same. The issue is that we need to re-evaluate the main package set. In order to do that, we need to access it, and there's two ways: the method you originally proposed, and attaching it to the evaluated package set as `__unfix__` with `fix'`.

**Comment by timokau** [comment]
> > Should those overlaps in namespaces be considered an issue and fixed? They lead to pretty subtle bugs...
> 
> They're annoying, but package names eventually will overlap. That's one reason why we use namespaces.

That's true. Maybe the python (and similar) infrastructure's `callPackage` should refuse to pick a package if there are multiple options and force the user to specify one explicitly. No idea if that's technically feasible though.

> > Are there reasons for this? Wouldn't it be nicer to treat python pkgs and "regular" pkgs as uniformly as possible?
> 
> Python libraries belong in the Python package set. That way we're also preventing possible naming collisions.

But the name collision still happened this way. Probably I'm just idealizing in my thinking that implementation language should be an implementation detail :)

> > Also if `fix -> fix'` isn't acceptable, can't we use the same mechanism overlays use to make it possible to do deep overrides from within nixpkgs? Its not a unique sage problem, sage just needs it at a bigger scale than most packages. `pythonPackages` offers it, why not `nixpkgs`?
> 
> We are using the same mechanism: the package set we've defined here is exactly the same. The issue is that we need to re-evaluate the main package set. In order to do that, we need to access it, and there's two ways: the method you originally proposed, and attaching it to the evaluated package set as `__unfix__` with `fix'`.

That makes sense, I didn't consider that the original proposal just "fixed" this issue by re-importing.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by timokau** [comment]
Still blocked on something like https://github.com/NixOS/nixpkgs/pull/44196.

**Comment by adamcstephens** [comment]
@collares It would be great to put some effort into this if you'd like to keep it open. It hasn't been touched in five years, was marked draft *four* years ago, has merge conflicts, and the PR linked above as a dependency was never accepted. Just keeping it open in its current state provides zero value.

**Comment by collares** [comment]
Fine by me in this particular instance, since I can reopen it if I find time in the future to work on this refactoring.

That being said, I don't think it's useful in general to close still-relevant issues/draft PRs even if they're "old", since the main thing this accomplishes is discarding progress/experience other people have gathered in the past, which future people may use in solving the problem. I hope the CADT model doesn't become Nixpkgs standard policy.

**Comment by adamcstephens** [comment]
The PR content is maintained just as well in the closed state on github. Nothing is lost. WIP and Draft indicate someone is actively working on this issue, but that's clearly not the case, so I argue Closed is a much better indicator of the state of this PR. Future people will still be able to see it just the same. Though at this point this PR seems much closer to never being done than getting merged. 

I'm not sure what the CADT model is, so I can't comment on that.

**Comment by collares** [comment]
That's fair. The discoverability aspect for closed PRs is a problem, so I filed issue #340754 as a compromise.

**Comment by adamcstephens** [comment]
An issue is a great idea. To be clear, I fully encourage someone to work on this if it's a real problem. As Anderson said when closing the other PR, it likely benefits to be done from scratch anyway.

 > The discoverability aspect for closed PRs is a problem

Out of curiosity, why do you find this the case? How is a draft more discoverable?

**Pull request closed without merging**
