### PR TITLE
nushellPlugins: fixes

### PR DESCRIPTION
**Pull request by aidalgol**
## Description of changes
* Fix the check phase of each plugin package.
* Fix incorrect `meta.homepage` URLs.
* Inherit `src` *and* `version` from `nushell`.
* Add `passthru.updateScript`.
* Code style housekeeping.
* Add myself to the maintainers list for each plugin package.

## Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Hey, thanks a lot for coming around !

The problem with inheriting source and version is that when nushell gets updated, then the update script thinks the plugins are up to date and doesnt run.

I had it like that originally but ended up leaving the version hard coded.

Did you find a way around that ?

**Comment by aidalgol** [comment]
> The problem with inheriting source and version is that when nushell gets updated, then the update script thinks the plugins are up to date and doesnt run.
> 
> I had it like that originally but ended up leaving the version hard coded.
> 
> Did you find a way around that ?

Ack!  No, I wasn't even aware of that issue.  I'm converting this PR to a draft while I work out a fix for that.

**Comment by aidalgol** [comment]
That was easier than I expected.  Just passing `--version=skip` to `nix-update-script` makes it check the hash regardless of the value of `version`.

**Comment by happysalada** [comment]
Could we just add a comment of why the version skip is there, its not immediately obvious to someone looking at the code.

**Comment by aidalgol** [comment]
> Could we just add a comment of why the version skip is there, its not immediately obvious to someone looking at the code.

Done.

**Comment by happysalada** [comment]
> > Could we just add a comment of why the version skip is there, its not immediately obvious to someone looking at the code.
> 
> Done.

@aidalgol did you maybe forget to push ?

**Comment by aidalgol** [comment]
> @aidalgol did you maybe forget to push ?

I forgot to actually stage the changes. :facepalm:

**Comment by happysalada** [comment]
Ok this looks good

The last puzzle is why ofborg isnt building any of these plugins. I havent figured out, if you ever do, feel free to make a PR

**Pull request merged**
