### PR TITLE
haskellPackages.spy: fix for new fsnotify version

### PR DESCRIPTION
**Pull request by Profpatsch**
- Built on platform(s)
  - [x] NixOS

Temporary fix, until it is merged upstream.

### CODE REVIEW

**Comment by peti** [comment]
Can we download that patch instead of checking it into Nixpkgs?

**Comment by Profpatsch** [comment]
Right, sounds like a good idea.

**Comment by Profpatsch** [comment]
@peti Nope, sorry, it’s a different patch upstream.

**Comment by peti** [comment]
Should we not distribute *upstream's* patch then?

**Comment by Profpatsch** [comment]
Well, they haven’t released a new version. I have of course done the patch against the latest version first, and then created the PR to match the current upstream master (for easy integration).

**Comment by peti** [comment]
The patch against their `master` does not apply to our current version?

**Comment by Profpatsch** [comment]
No, sadly not.

**Pull request merged**
