### PR TITLE
telegram-desktop: 4.8.4 -> 4.11.1

### PR DESCRIPTION
**Pull request by NickCao**
###### Description of changes
Depends on the release of glibmm 2.78 due to https://github.com/telegramdesktop/tdesktop/commit/f817df9d7fb107d9196d94f22c9ca6250b902c16

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PedroHLC** [comment]
Hello random nixpkgs user, if you came here after your telegram-desktop started randomly crash, two notes for you:

1. The current version is 4.9.9, we're 16 releases late;
2. In-repo version now SIGABRT when receiving those new sponsored toasts `Data::SponsoredMessages` on channels.

I won't report (2) to upstream because of (1)...

**Comment by SuperSandro2000** [comment]
> Depends on the release of glibmm 2.78 due to [telegramdesktop/tdesktop@f817df9](https://github.com/telegramdesktop/tdesktop/commit/f817df9d7fb107d9196d94f22c9ca6250b902c16)

As a stop gap measure we can't just revert the linked commit?

**Comment by NickCao** [comment]
> As a stop gap measure we can't just revert the linked commit?

The blast radius is wider than the single commit, also covers various submodules and subsequent changes.

**Comment by PedroHLC** [comment]
Just adding that I tested pinning these glib versions to telegram, and it worked perfectly from this tags to the latest commit in each of the four involved repos. I just needed to prefix ${glib.out}/lib to LD_LIBRARY_PATH in telegram's wrapper.

**Comment by RuRo** [comment]
So what's the current status of this PR? What are we blocked on?

The corresponding #256606 PR for updating `glibmm` was closed 3 weeks ago without merging (due to an accidental rebase, supposedly), but no new PR was created.

The version bump for `glibmm` should be fairly simple. Is there some breakage that prevents us from updating it?

**Comment by NickCao** [comment]
> The version bump for `glibmm` should be fairly simple. Is there some breakage that prevents us from updating it?

Maybe the gnome/gtk maintainers knows the situation better than me, but I think we would be updating it together with the gnome 45 update.

**Comment by leiserfg** [comment]
Is there someone around with a flake pointing to an updated telegram to use it meanwhile?

**Comment by PedroHLC** [comment]
Chaotic-Nyx has it directly from the master branch, daily bumped. Been using since my previous comment, and basically if it builds, then it works.

**Comment by NickCao** [comment]
@ofborg build telegram-desktop

**Comment by NickCao** [comment]
> @ofborg build telegram-desktop

Well it did not work, mixing multiple versions of glib is a bad idea.

**Comment by PedroHLC** [comment]
> Well it did not work, mixing multiple versions of glib is a bad idea.

The most significant difference from this and the first one I got working was that I was also pinning glib in `tg-owt`, and I had this (in telegram):

```
postFixup = ''
  qtWrapperArgs+=(
    --prefix LD_LIBRARY_PATH : "${glib_git.out}/lib"
  )
''
```

**Comment by NickCao** [comment]
I'm thinking of building glibmm 2.78 atop glib 2.76.

**Comment by NickCao** [comment]
> I'm thinking of building glibmm 2.78 atop glib 2.76.

I works even better than anticipated

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 244598` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>glom</li>
    <li>glom.dev</li>
    <li>glom.devdoc</li>
    <li>glom.doc</li>
    <li>glom.lib</li>
    <li>mm-common</li>
    <li>telegram-desktop</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]
image

**Comment by NickCao** [comment]
The `mm-common` fix could use some rework, otherwise this is good to go.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 244598` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>glom</li>
    <li>glom.dev</li>
    <li>glom.devdoc</li>
    <li>glom.doc</li>
    <li>glom.lib</li>
    <li>mm-common</li>
    <li>telegram-desktop</li>
  </ul>
</details>

**Pull request merged**
