### PR TITLE
kernel: enable EFI initrd loader

### PR DESCRIPTION
**Pull request by ethorsoe**
Initrd loader is not enabled by default in some aarch64 kernels,
which makes systemd-boot booted kernels fail by default, add this
everywhere, since this is a sane default even when it's already in
some kernel defaults.

###### Motivation for this change
make system-boot work on some aarch64 kernels

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by delroth** [comment]
I +1'd this pull request a while ago, but to be more explicit about my support for this PR: this is absolutely **required** for NixOS to boot on ARMv8 UEFI platforms with kernels > 5.12 in its default configuration (systemd-boot). Currently the default configuration leads to an unbootable system.

I've been using a variant of this PR for months on my system and can confirm it works and has no noticeable harmful effect: https://github.com/delroth/infra.delroth.net/commit/2f67f445f7b2f29a2a46757dc24b1181c936acce

Can someone please merge this PR? @samueldr

**Comment by samueldr** [comment]
I'm wondering why the default value changed for us.

```
[samuel@ednakrabapple:~]$ zcat /proc/config.gz | grep EFI_GENERIC_STUB_INITRD_CMDLINE_LOADER
CONFIG_EFI_GENERIC_STUB_INITRD_CMDLINE_LOADER=y

[samuel@ednakrabapple:~]$ uname -a
Linux ednakrabapple 5.10.68 #1-NixOS SMP Wed Sep 22 10:28:07 UTC 2021 aarch64 GNU/Linux
```

There are [no recent changes to the Kconfig](https://github.com/torvalds/linux/commits/master/drivers/firmware/efi/Kconfig).

Tracking down why this value changed is desirable as it might be hiding some more subtle undesirable change.

**Comment by delroth** [comment]
https://github.com/torvalds/linux/commit/6edcf9dc2e1aff3aa1f5a69ee420fb30dd0e968a is the upstream change

**Review by samueldr — APPROVED** [review]

**Comment by samueldr** [comment]
I guess it's as simple as no one using `systemd-boot` updated and rebooted to the latest kernel since a 5.10. I assume `grub` is not affected here, but I'm not sure.

**Comment by delroth** [comment]
Because few people use UEFI ARMv8 systems with NixOS, and among those people the knowledge of this magic kernel config option has been passed down as a valuable secret :-)

This isn't a "gray area" thing, our (default) systemd-boot boot path literally relies on this option, and it's only working on X86 because the kernel developer inexplicably made the default for this option dependent on the architecture (probably to not break backwards compatibility, and who cares about ARMv8 UEFI systems...).

**Comment by samueldr** [comment]
Yeah, it's not a gray area, I was merely confused as to why it took *so long* until users hit the issue. I verified that indeed since 5.11 it *is* disabled in our config.

**Pull request merged**
