### PR TITLE
python3Packages.{mocket,samsunsgtvws,segments,csvw}: update

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

- https://github.com/xchwarze/samsung-tv-ws-api/releases/tag/v1.6.0
- https://github.com/cldf/csvw/blob/fbeb899e2af7d10221fe1230d56aba6e33fcda12/CHANGES#L14-L17
- https://github.com/mindflayer/python-mocket/releases/tag/3.9.36
  https://github.com/mindflayer/python-mocket/releases/tag/3.9.37
  https://github.com/mindflayer/python-mocket/releases/tag/3.9.38
  https://github.com/mindflayer/python-mocket/releases/tag/3.9.39
- https://github.com/cldf/segments/blob/master/CHANGES.md#220---2021-01-11

###### Things done

- [x ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 109515` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.geoip2</li>
    <li>python39Packages.sopel</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>tts</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>python37Packages.clldutils</li>
    <li>python37Packages.csvw</li>
    <li>python37Packages.geoip2</li>
    <li>python37Packages.mocket</li>
    <li>python37Packages.phonemizer</li>
    <li>python37Packages.samsungtvws</li>
    <li>python37Packages.segments</li>
    <li>python37Packages.sopel</li>
    <li>python38Packages.clldutils</li>
    <li>python38Packages.csvw</li>
    <li>python38Packages.geoip2</li>
    <li>python38Packages.mocket</li>
    <li>python38Packages.phonemizer</li>
    <li>python38Packages.samsungtvws</li>
    <li>python38Packages.segments</li>
    <li>python38Packages.sopel</li>
    <li>python39Packages.clldutils</li>
    <li>python39Packages.csvw</li>
    <li>python39Packages.mocket</li>
    <li>python39Packages.phonemizer</li>
    <li>python39Packages.samsungtvws</li>
    <li>python39Packages.segments</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Trying to get the mocket tests running, bear with me.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 109515` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.geoip2</li>
    <li>python39Packages.sopel</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>python37Packages.clldutils</li>
    <li>python37Packages.csvw</li>
    <li>python37Packages.geoip2</li>
    <li>python37Packages.mocket</li>
    <li>python37Packages.phonemizer</li>
    <li>python37Packages.samsungtvws</li>
    <li>python37Packages.segments</li>
    <li>python37Packages.sopel</li>
    <li>python38Packages.clldutils</li>
    <li>python38Packages.csvw</li>
    <li>python38Packages.geoip2</li>
    <li>python38Packages.mocket</li>
    <li>python38Packages.phonemizer</li>
    <li>python38Packages.samsungtvws</li>
    <li>python38Packages.segments</li>
    <li>python38Packages.sopel</li>
    <li>python39Packages.clldutils</li>
    <li>python39Packages.csvw</li>
    <li>python39Packages.mocket</li>
    <li>python39Packages.phonemizer</li>
    <li>python39Packages.samsungtvws</li>
    <li>python39Packages.segments</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109515` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.geoip2</li>
<li>python39Packages.sopel</li>
</ul>
</details>
<details>
<summary>
22 packages built:
</summary>
<ul>
<li>python37Packages.clldutils</li>
<li>python37Packages.csvw</li>
<li>python37Packages.geoip2</li>
<li>python37Packages.mocket</li>
<li>python37Packages.phonemizer</li>
<li>python37Packages.samsungtvws</li>
<li>python37Packages.segments</li>
<li>python37Packages.sopel</li>
<li>python38Packages.clldutils</li>
<li>python38Packages.csvw</li>
<li>python38Packages.geoip2</li>
<li>python38Packages.mocket</li>
<li>python38Packages.phonemizer</li>
<li>python38Packages.samsungtvws</li>
<li>python38Packages.segments</li>
<li>python38Packages.sopel</li>
<li>python39Packages.clldutils</li>
<li>python39Packages.csvw</li>
<li>python39Packages.mocket</li>
<li>python39Packages.phonemizer</li>
<li>python39Packages.samsungtvws</li>
<li>python39Packages.segments</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.mocket:
<details>

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'setup_requires=["pipenv"]' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python37Packages.samsungtvws:
<details>

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'websocket-client==' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python38Packages.mocket:
<details>

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'setup_requires=["pipenv"]' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python38Packages.samsungtvws:
<details>

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'websocket-client==' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python39Packages.mocket:
<details>

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'setup_requires=["pipenv"]' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python39Packages.samsungtvws:
<details>

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'websocket-client==' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109515` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.geoip2</li>
<li>python39Packages.sopel</li>
</ul>
</details>
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.geoip2: log was empty</li>
<li>python37Packages.mocket: log <a href="https://termbin.com/u8imo">https://termbin.com/u8imo</a></li>
<li>python37Packages.sopel: log was empty</li>
  </ul>
</details>
<details>
<summary>
19 packages built:
</summary>
<ul>
<li>python37Packages.clldutils</li>
<li>python37Packages.csvw</li>
<li>python37Packages.phonemizer</li>
<li>python37Packages.samsungtvws</li>
<li>python37Packages.segments</li>
<li>python38Packages.clldutils</li>
<li>python38Packages.csvw</li>
<li>python38Packages.geoip2</li>
<li>python38Packages.mocket</li>
<li>python38Packages.phonemizer</li>
<li>python38Packages.samsungtvws</li>
<li>python38Packages.segments</li>
<li>python38Packages.sopel</li>
<li>python39Packages.clldutils</li>
<li>python39Packages.csvw</li>
<li>python39Packages.mocket</li>
<li>python39Packages.phonemizer</li>
<li>python39Packages.samsungtvws</li>
<li>python39Packages.segments</li>
</ul>
</details>

**Comment by mweinelt** [comment]
> class unittest.IsolatedAsyncioTestCase(methodName='runTest')
>
>    This class provides an API similar to TestCase and also accepts coroutines as test functions.
>
>    New in version 3.8.

Aha, fixed by ignoring `tests38` on pythonOlder 3.8.

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/109515

2 packages marked as broken and skipped:
python39Packages.geoip2 python39Packages.sopel

1 package failed to build:
tts

22 packages built:
python37Packages.clldutils python37Packages.csvw python37Packages.geoip2 python37Packages.mocket python37Packages.phonemizer python37Packages.samsungtvws python37Packages.segments python37Packages.sopel python38Packages.clldutils python38Packages.csvw python38Packages.geoip2 python38Packages.mocket python38Packages.phonemizer python38Packages.samsungtvws python38Packages.segments python38Packages.sopel python39Packages.clldutils python39Packages.csvw python39Packages.mocket python39Packages.phonemizer python39Packages.samsungtvws python39Packages.segments
```

**Pull request merged**
