### PR TITLE
python3Packages.requests: 2.25.1 -> 2.26.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 2.26.0

Change log: https://github.com/psf/requests/blob/master/HISTORY.md#2260-2021-07-13

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130224` at e3fb183c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>27 packages marked as broken and skipped:</summary>
  <ul>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>gnuradio3_7</li>
    <li>gnuradio3_7Packages.ais</li>
    <li>gnuradio3_7Packages.gnuradio</li>
    <li>gnuradio3_7Packages.gsm</li>
    <li>gnuradio3_7Packages.limesdr</li>
    <li>gnuradio3_7Packages.nacl</li>
    <li>gnuradio3_7Packages.osmosdr</li>
    <li>gnuradio3_7Packages.rds</li>
    <li>googleearth-pro</li>
    <li>grass</li>
    <li>hadoop</li>
    <li>hadoop_2_7</li>
    <li>hadoop_2_8</li>
    <li>hadoop_2_9</li>
    <li>impressive</li>
    <li>linuxPackages_hardkernel_4_14.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>natron</li>
    <li>ocropus</li>
    <li>odpdown</li>
    <li>opentsdb</li>
    <li>pig</li>
    <li>rainbowstream</li>
    <li>spark</li>
    <li>unifi-video</li>
  </ul>
</details>
<details>
  <summary>10177 packages skipped due to time constraints:</summary>
  <ul>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>R</li>
    <li>_389-ds-base</li>
    <li>abcl</li>
    <li>acd-cli</li>
    <li>acousticbrainz-client</li>
    <li>adafruit-ampy</li>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>python39Packages.charset-normalizer</li>
    <li>python39Packages.requests</li>
    <li>sphinx (python39Packages.sphinx)</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/python-modules/requests/default.nix:25:15:
```
   |
25 |   patches = [ ./0001-Prefer-NixOS-Nix-default-CA-bundles-over-certifi.patch ];
   |               ^
```
</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
> Requests now supports Brotli compression, if either the brotli or brotlicffi package is installed. (#5783)

**Comment by fabaff** [comment]
`brotlicffi` (#131896) will be needed for `httpx` update as well.

**Comment by SuperSandro2000** [comment]
I think we want to target staging here.

**Comment by fabaff** [comment]
> I think we want to target staging here.

It's for staging. At least that's what I see.

**Review by SuperSandro2000 — APPROVED** [review]
Is home-assistant sufficient enough to check for build failures?
What do you think @mweinelt @jonringer @fabaff ?

**Comment by mweinelt** [comment]
No.

**Pull request merged**
