### PR TITLE
chromium: prevent automatic Widevine DRM download

### LINKED ISSUE #115275: Chromium uses Widevine despite having BSD-3 license
**Describe the bug**
Nix installs a version of Chromium with Widevine on NixOS, despite not being enabled and goes through unfree license checks.

**To Reproduce**
1. Add `pkgs.chromium` to `environment.systemPackages`
2. Rebuild system configuration
3. Check `chrome://components` in Chromium

**Expected behavior**
- Widevine is not installed if not explicitly enabled.
or
- Chromium trips nonfree license checks and forces user to allow unfree packages.

**Screenshots**
image
image

**Notify maintainers**
@primeos
@thefloweringash
@bendlas

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.18, NixOS, 20.09.3368.16fc9eb7364 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(patrycja): `""`
 - channels(root): `"nixos-20.09.3368.16fc9eb7364, unstable-21.05pre272691.04ac9dcd311"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by emilylange**
## Description of changes

Previously, chromium automatically downloaded Widevine via its component updater when encountering DRM protected content for the first time or when manually opening chrome://components.

This commit disables that and also prevents previously downloaded Widevine blobs (usually in ~/.config/chromium/WidevineCdm/) from being loaded and executed.

Widevine now only works using
~~~
chromium.override { enableWideVine = true; }
~~~
making Widevine truly opt-in, as it's supposed to be. Using that override also sets meta.license to unfree, making the end user aware that Widevine is in fact unfree.

See #115275 for further details.

Closes #115275.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`) **both non-Widevine and Widevine variants**
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilylange** [comment]
Result of `nixpkgs-review pr 310209` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>archivebox</li>
    <li>archivebox.dist</li>
    <li>itch</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>redisinsight</li>
  </ul>
</details>
<details>
  <summary>89 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>antares</li>
    <li>aws-azure-login</li>
    <li>bilibili</li>
    <li>bitwarden-desktop</li>
    <li>bitwarden-directory-connector</li>
    <li>blockbench</li>
    <li>breitbandmessung</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>chromium</li>
    <li>chromium.sandbox</li>
    <li>deltachat-desktop</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron (electron_29)</li>
    <li>electron_27</li>
    <li>electron_28</li>
    <li>electron_30</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>fast-cli</li>
    <li>fcast-receiver</li>
    <li>feishin</li>
    <li>freetube</li>
    <li>grafana-kiosk</li>
    <li>headset</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>jitsi-meet-electron</li>
    <li>koodo-reader</li>
    <li>kuro</li>
    <li>logseq</li>
    <li>lx-music-desktop</li>
    <li>mattermost-desktop</li>
    <li>mermaid-cli</li>
    <li>mermaid-filter</li>
    <li>micropad</li>
    <li>morgen</li>
    <li>nix-tour</li>
    <li>obsidian</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>passky-desktop</li>
    <li>percollate</li>
    <li>playwright-test</li>
    <li>pocket-casts</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>protonmail-desktop</li>
    <li>puppeteer-cli</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python311Packages.pytest-playwright</li>
    <li>python311Packages.pytest-playwright.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.pytest-playwright</li>
    <li>python312Packages.pytest-playwright.dist</li>
    <li>r2modman</li>
    <li>revolt-desktop</li>
    <li>sharedown</li>
    <li>single-file-cli</li>
    <li>sitespeed-io</li>
    <li>siyuan</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>teams-for-linux</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>thedesk</li>
    <li>threema-desktop</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>ungoogled-chromium</li>
    <li>ungoogled-chromium.sandbox</li>
    <li>vesktop</li>
    <li>vhs</li>
    <li>vieb</li>
    <li>wayback</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
    <li>webtorrent_desktop</li>
    <li>whalebird</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

~~~shell
# git describe --abbrev=40
24.05-pre-72131-gd5c611fcf504321442bd91b19b3dea7e20f468e7
# nix-build nixos/tests/chromium.nix -A stable -A ungoogled
/nix/store/h1q6hnvsjfqfzd7vhjk8dlng5i2difbv-vm-test-run-chromium-stable
/nix/store/inlc3b5asmi4lm4mr3y0mar818289wpv-vm-test-run-chromium-ungoogled
~~~

**Review by networkException — APPROVED** [review]

**Comment by emilylange** [comment]
I also manually tested `chromium`, `ungoogled-chromium` (both with and without Widevine) and `element-desktop` on wayland.

**Comment by emilylange** [comment]
No, @SuperSandro2000, enabling DRM does not require you to compile chromium from source.

It's a wrapper.

A lot of effort went into ensuring you would not have to recompile chromium from source.

**Comment by SuperSandro2000** [comment]
I think I know why I thought that. At https://github.com/emilylange/nixpkgs/blob/e4f185cfaf2c6ba59d3d4d3de42f79f4b1cea978/pkgs/applications/networking/browsers/chromium/default.nix#L153-L164 the runCommand package is named like the source and I almost immediately aborted when I saw that. Sorry 😅

**Pull request merged**
