### PR TITLE
stdenv: run checks late

### PR DESCRIPTION
**Pull request by baloo**
###### Motivation for this change

According to #140179 #139292 running tests can make a derivation non-deterministic.

This is an idea to run tests *after* installation and ensuring this way tests can't affects outputs.
Should tests fail, the build would be discarded altogether.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by baloo** [comment]
Question: Is the output actually needed? Wouldn't a failed test just cancel the build?

**Comment by r-burns** [comment]
* This will definitely break packages which have made implicit assumpations about the ordering of phases.
* It is unintuitive IMO for installCheckPhase to happen before checkPhase 
* If this is python-specific, modifying global stdenv seems like too big a hammer

I would prefer something like https://github.com/NixOS/nixpkgs/issues/26400

**Comment by baloo** [comment]
>     * This will definitely break packages which have made implicit assumptions about the ordering of phases.
I successfully built all dependencies to `python39Packages.pytest-xdist` which were causing problems. (157 packages built without issue).
> 
>     * It is unintuitive IMO for installCheckPhase to happen before checkPhase
True
> 
>     * If this is python-specific, modifying global stdenv seems like too big a hammer
This is not python specifc
>

**Comment by baloo** [comment]
I never wrote an RFC before but I can look into that.

**Pull request closed without merging**
