### PR TITLE
Expose prometheus generic builder.

### PR DESCRIPTION
**Pull request by jbgi**
###### Motivation for this change
 So that people can easily try newer prometheus versions in overlays:
```nix
 self: super: {
   prometheus_2 = (super.callPackage <nixpkgs/pkgs/servers/monitoring/prometheus> {}).generic {
     version = "2.8.1";
     sha256 = "0x8w0qdh4lcf19nmdlhvgzpy08c2a932d3k49cjwhi5npcsf858n";
     doCheck = false;
   };
 }
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by basvandijk** [comment]
Maybe rename `generic` to `buildPrometheus` to give it a less generic name.

**Comment by basvandijk** [comment]
BTW I just tested the `prometheus2` test on `prometheus-2.8.1` and that finishes successfully. Will push a PR soon.

**Comment by basvandijk** [comment]
See: https://github.com/NixOS/nixpkgs/pull/59182. I'll merge that as soon as the checks complete.

**Comment by basvandijk** [comment]
I just pushed the rename myself. Will merge after the checks complete.

**Comment by jbgi** [comment]
@basvandijk thanks, for some reason the checks did not pass on my machine when I tried to build 2.8.1, which was the original reason for this PR...

**Pull request merged**
