### PR TITLE
steam-fhsenv: don't unshare pid

### LINKED ISSUE #104412: Steam-run: can't use MIT shared memory
**Describe the bug**
It seems to be impossible to use shared memory inside steam-run environment. I'd expect to be able to allow some programs to use MIT shared memory.

**To Reproduce**
1. Download Natron (it uses shared memory) [here](https://github.com/NatronGitHub/Natron/releases/download/v2.3.15/Natron-2.3.15-Linux-64-no-installer.tar.xz)
2. Unpack and go to the created directory
3. Install steam-run
4. Run `steam-run ./Natron`

You should get an error:
```
 steam-run ./Natron
Natron Version 2.3.15
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  1 (X_ShmAttach)
  Serial number of failed request:  270
  Current serial number in output stream:  271
```
**Workaround**
I can force QT not to use MITSHM using:
```
QT_X11_NO_MITSHM=1 steam-run ./Natron
```
but it may be less efficient since it just disable shared memory.

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change

closes: #104412

Some applications such as Natron need access to MIT-SHM or other
shared memory mechanisms. Unsharing the pid namespace
breaks the ability for application to reference shared memory.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tobiasBora** [comment]
To make it work with `steam-run`, we also need to put the `unshareXXX` code into the `buildFhsUserEnv` created in the `passthru.run = buildFHSUserEnv`. Also, does it make sense to copy all the unshare stuff, like `unshare{User,Ipc,Pid,Net,Uts,CGroup}`?

**Comment by jonringer** [comment]
> To make it work with `steam-run`, we also need to put the `unshareXXX` code into the `buildFhsUserEnv`

done

**Comment by tobiasBora** [comment]
Thanks a lot, I can confirm it works. By the way, if you have any idea on how to make bubblewrap run packages that require fuse internally, I would be very happy to hear about it. This is used for example by some AppImages like LittleWeeb (and since `appimage-run` segfault on that image, I would have love to see if steam-run could get anything better). But anyway, I guess it's a different topic, this PR can be merged independently. Thanks again.

**Comment by jonringer** [comment]
My assumption is that using a new user space is breaking file IO, but would need to run an `strace` to know for sure

```
    --unshare-user               Create new user namespace (may be automatically implied if not setuid)
    --unshare-user-try           Create new user namespace if possible else continue by skipping it
    --unshare-ipc                Create new ipc namespace
    --unshare-pid                Create new pid namespace
    --unshare-net                Create new network namespace
    --unshare-uts                Create new uts namespace
    --unshare-cgroup             Create new cgroup namespace
```

**Comment by jonringer** [comment]
anyway, was able to launch steam and csgo with changes

**Pull request merged**
