### PR TITLE
[20.09] keepassxc: 2.6.2 -> 2.6.3

### PR DESCRIPTION
**Pull request by claudiiii**
###### Motivation for this change

(cherry picked from commit ef0419f06b816c21910718c4aec90bab30facb63)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by claudiiii** [comment]
Result of `nixpkgs-review pr 110921` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>keepassxc (keepassx2-http)</li>
  </ul>
</details>

**Comment by turion** [comment]
PR builds. `bin/keepassxc` executes correctly.

**Review by turion — APPROVED** [review]
LGTM

**Comment by turion** [comment]
Nothing has changed, right?

**Comment by claudiiii** [comment]
Yea I just did the initial cherry pick with the wrong name.

**Comment by taku0** [comment]
It fails on macOS Big Sur 11.1.

```
$ nix-build -I nixpkgs=. -A pkgs.keepassxc
these derivations will be built:
  /nix/store/gky538jmj5qkqhbivfayc056259nfm3s-keepassxc-2.6.3.drv
building '/nix/store/gky538jmj5qkqhbivfayc056259nfm3s-keepassxc-2.6.3.drv'...
unpacking sources
unpacking source archive /nix/store/j5vxc9n39dxcmsn2zvnrahmalfyyxjvw-source
source root is source
patching sources
applying patch /nix/store/jydw05w7r67l8ixpgri3yg85rr8f4nxj-darwin.patch
patching file CMakeLists.txt
Hunk #1 succeeded at 360 with fuzz 2 (offset 53 lines).
Hunk #2 succeeded at 424 (offset 54 lines).
patching file src/CMakeLists.txt
Hunk #1 succeeded at 407 (offset 56 lines).
patching file src/autotype/mac/CMakeLists.txt
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DCMAKE_INSTALL_LOCALEDIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/share/doc/KeePassXC -DCMAKE_INSTALL_INFODIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/include -DCMAKE_INSTALL_SBINDIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/33ansvs5lpcz1vg1x7p37maqn1cxhivl-cctools-binutils-darwin-927.0.2/bin/strip -DCMAKE_RANLIB=/nix/store/33ansvs5lpcz1vg1x7p37maqn1cxhivl-cctools-binutils-darwin-927.0.2/bin/ranlib -DCMAKE_AR=/nix/store/33ansvs5lpcz1vg1x7p37maqn1cxhivl-cctools-binutils-darwin-927.0.2/bin/ar -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/nix/store/mch8941017gll7hcr4ykjzixknj716mc-keepassxc-2.6.3 -DKEEPASSXC_BUILD_TYPE=Release -DWITH_GUI_TESTS=ON -DWITH_XC_AUTOTYPE=ON -DWITH_XC_UPDATECHECK=OFF -DWITH_XC_YUBIKEY=ON -DWITH_XC_BROWSER=ON -DWITH_XC_KEESHARE=ON -DWITH_XC_KEESHARE_SECURE=ON -DWITH_XC_TOUCHID=ON -DWITH_XC_SSHAGENT=ON 
-- The C compiler identification is Clang 7.1.0
-- The CXX compiler identification is Clang 7.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /nix/store/3mrwg8hplg82w3c4q2c2whkjq4wfly25-clang-wrapper-7.1.0/bin/clang
-- Check for working C compiler: /nix/store/3mrwg8hplg82w3c4q2c2whkjq4wfly25-clang-wrapper-7.1.0/bin/clang - broken
CMake Error at /nix/store/bjs3kjc9zkl5vgipdgi9d8w2d5brcrjq-cmake-3.18.2/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/nix/store/3mrwg8hplg82w3c4q2c2whkjq4wfly25-clang-wrapper-7.1.0/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /private/var/folders/8z/69zjg6ns4s7crhymsmhp8tp80000gn/T/nix-build-keepassxc-2.6.3.drv-3/source/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/nix/store/i36sdgn6450hja6rzinimvrsjf5c3m7m-gnumake-4.3/bin/make cmTC_90a6f/fast && /nix/store/i36sdgn6450hja6rzinimvrsjf5c3m7m-gnumake-4.3/bin/make  -f CMakeFiles/cmTC_90a6f.dir/build.make CMakeFiles/cmTC_90a6f.dir/build
    make[1]: Entering directory '/private/var/folders/8z/69zjg6ns4s7crhymsmhp8tp80000gn/T/nix-build-keepassxc-2.6.3.drv-3/source/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_90a6f.dir/testCCompiler.c.o
    /nix/store/3mrwg8hplg82w3c4q2c2whkjq4wfly25-clang-wrapper-7.1.0/bin/clang   -arch x86_64 -o CMakeFiles/cmTC_90a6f.dir/testCCompiler.c.o -c /private/var/folders/8z/69zjg6ns4s7crhymsmhp8tp80000gn/T/nix-build-keepassxc-2.6.3.drv-3/source/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_90a6f
    /nix/store/bjs3kjc9zkl5vgipdgi9d8w2d5brcrjq-cmake-3.18.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_90a6f.dir/link.txt --verbose=1
    /nix/store/3mrwg8hplg82w3c4q2c2whkjq4wfly25-clang-wrapper-7.1.0/bin/clang  -arch x86_64 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_90a6f.dir/testCCompiler.c.o -o cmTC_90a6f 
    ld: file not found: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [CMakeFiles/cmTC_90a6f.dir/build.make:106: cmTC_90a6f] Error 1
    make[1]: Leaving directory '/private/var/folders/8z/69zjg6ns4s7crhymsmhp8tp80000gn/T/nix-build-keepassxc-2.6.3.drv-3/source/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:140: cmTC_90a6f/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)


-- Configuring incomplete, errors occurred!
See also "/private/var/folders/8z/69zjg6ns4s7crhymsmhp8tp80000gn/T/nix-build-keepassxc-2.6.3.drv-3/source/build/CMakeFiles/CMakeOutput.log".
See also "/private/var/folders/8z/69zjg6ns4s7crhymsmhp8tp80000gn/T/nix-build-keepassxc-2.6.3.drv-3/source/build/CMakeFiles/CMakeError.log".
builder for '/nix/store/gky538jmj5qkqhbivfayc056259nfm3s-keepassxc-2.6.3.drv' failed with exit code 1
error: build of '/nix/store/gky538jmj5qkqhbivfayc056259nfm3s-keepassxc-2.6.3.drv' failed
```

**Comment by turion** [comment]
Die the previous version work on macos?

**Comment by claudiiii** [comment]
It also fails to build on Catalina when using sandboxed build (it builds fine without the sandbox), with a "Segmentation fault 11" like described in #97194, but that seems to be a general problem with Qt on macOS (https://github.com/NixOS/nixpkgs/search?q=lrelease&type=issues, and look at the build results for macOS).

**Comment by taku0** [comment]
2.6.2 fails with the same error.

Linux version works fine.

**Comment by turion** [comment]
> 2.6.2 fails with the same error.

Then this should be reported as a separate issue. Thanks for pointing out!

**Pull request merged**
