### PR TITLE
[wip] Remove binary blobs

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This removes some packages that are hopefully completely unnecessary now that a source-based alternative exists for them.

Here are the names effected:

- firefox-bin
- thunderbird-bin
- tensorflow (now uses tensorflow/src.nix)

To make the transition from these easier, I think it would be good to provide some alternatives. I have added a nur-packages repo that contains the old expressions: https://github.com/matthewbauer/nur-packages

There could be a good reason for keeping these around but my understanding is that we can now use the official branding in the source-based firefox & thunderbird.

### CODE REVIEW

**Comment by grahamc** [comment]
:-1: sometimes the binary versions are the only way to get certain features, and the betas are much nicer through bins.

**Comment by matthewbauer** [comment]
Hmmm... Maybe this is a good chance to make the source-based versions better? Besides branding, there should be no reason we cannot build binaries just as good as Mozilla's on Nix infrastructure. Binary blobs are just never going to be as portable a Nix derivation.

**Comment by grahamc** [comment]
Practically speaking, I can't imagine we'll want to be building all the variations of the beta / nightly releases of each of these packages on Hydra, and nobody will want to be building them locally (looking at many hours of builds). I think these bins are reasonable. I think they are valuable.

**Comment by adisbladis** [comment]
The maintenance burden to maintain `devedition` and `beta` firefox is currently a few minutes every few days or so.
Building these firefox release channels would be a multi hour endeavour every few _days_ for these packages. I would not be able to maintain these packages any more if that was the case.

It's also worth noting that the `-bin` variants can possibly get security updates very fast while the source derivation occasionally has problems.

I don't know about the rest of the packages in this PR but at the very least firefox and thunderbird bins should remain.

**Comment by 7c6f434c** [comment]
Also, practically speaking, from time to time updating Firefox source build is a longer process than a binary release just because `nss` is a large-rebuild dependency.

**Comment by FRidh** [comment]
The binary tensorflow was re-added because of difficulties building from source. There are good reasons to sometimes use binaries, as mentioned already by others, so I am against this change.

**Comment by matthewbauer** [comment]
Ok closing for now. This discussion is probably best for me to bring up in an RFC.

**Pull request closed without merging**
