### PR TITLE
spyder: mark as broken

### PR DESCRIPTION
**Pull request by eduardosm**
###### Motivation for this change

watchdog version is incorrect and textdistance is missing

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
The motivation field is there to explain your reasoning behind this change, please use it.

**Comment by eduardosm** [comment]
> The motivation field is there to explain your reasoning behind this change, please use it.

Done

**Comment by gebner** [comment]
So spyder has been updated twice with a missing dependency that we don't even have in nixpkgs yet (the textdistance dependency was introduced in 4.2.1)?  These mass-updates are getting a bit out of hand..

Could you package textdistance instead of marking spyder broken?

**Comment by eduardosm** [comment]
https://github.com/NixOS/nixpkgs/pull/120884

**Pull request closed without merging**
