### PR TITLE
mesa: default to 23.0.1

### PR DESCRIPTION
**Pull request by K900**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I'm not so sure about the libgbm output splitting actually, but I thought it better discuss here: https://github.com/NixOS/nixpkgs/pull/219534#issuecomment-1484087897

**Review by vcunat — APPROVED** [review]
This switch is rater inconsequential, as it doesn't affect the runtime libGL* or drivers.

**Comment by vcunat** [comment]
The automatic `rm` line would be easier to maintain than a patch, as we'll now need to support multiple versions simultaneously.  But not a big deal.

**Comment by K900** [comment]
The patch applies to both and I'm hoping to get the Mesa people to backport it to oldstable as well.

**Comment by K900** [comment]
The patch applies to both and I'm hoping to get the Mesa people to backport it to oldstable as well.

**Comment by K900** [comment]
The patch applies to both and I'm hoping to get the Mesa people to backport it to oldstable as well.

**Comment by vcunat** [comment]
(github was now slow etc. for me as well)

Them backporting it only makes it harder for us, because it seems unlikely that everything is released synchronously.

**Comment by vcunat** [comment]
I see nothing preventing this:

> Rebuilding the world with an overlay that sets `mesa = final.mesa_23;` *does* result in a working desktop

**Comment by vcunat** [comment]
Until now we've missed that mesa 23 won't build on darwin:
https://hydra.nixos.org/job/nixpkgs/trunk/mesa_23_0_1.x86_64-darwin
https://hydra.nixos.org/job/nixpkgs/trunk/mesa_23_0_1.aarch64-darwin

**Comment by K900** [comment]
Hold on why is it even building DRI

**Comment by K900** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21859 ugh.

**Comment by vcunat** [comment]
Uh, so I don't know... perhaps default darwin to `mesa_22` for now as we keep it anyway?

**Comment by K900** [comment]
I agree.

**Pull request merged**
