### PR TITLE
[staging-next] ocaml fixes due to findlib changes

### PR DESCRIPTION
**Pull request by r-burns**
https://github.com/NixOS/nixpkgs/pull/133008/commits/a3ab43d3a45338f845a0f8a12ed34e84c8b79dae moved a required setup step to a preConfigure hook, which wasn't getting triggered by some packages.

###### Motivation for this change

Fixes e.g. jackline and virt-top on staging-next https://github.com/NixOS/nixpkgs/pull/135477

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Change looks good, I couldn't find the relevant hydra failures though. Perhaps you tested on local ? (it looks as if there are just a bunch of pending jobs right now)

@symphorien might be interested in this.

**Comment by r-burns** [comment]
Yeah there's a lot still queued up but many failures are already visible: https://hydra.nixos.org/eval/1702118?full=1&compare=1700369#tabs-now-fail

E.g. https://hydra.nixos.org/build/151271341 (jackline), https://hydra.nixos.org/build/150650387 (virt-top)

**Comment by r-burns** [comment]
Result of `nixpkgs-review pr 136821` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>ocamlPackages.ocaml_extlib-1-7-7</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>google-drive-ocamlfuse</li>
    <li>libbap</li>
    <li>ocamlPackages.bap</li>
    <li>python38Packages.bap</li>
    <li>python39Packages.bap</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>beluga</li>
    <li>haxe</li>
    <li>haxePackages.hxcpp</li>
    <li>haxePackages.hxcs</li>
    <li>haxePackages.hxjava</li>
    <li>haxePackages.hxnodejs_4</li>
    <li>haxe_4_0</li>
    <li>haxe_4_1</li>
    <li>jackline</li>
    <li>ocamlPackages.caqti-driver-mariadb</li>
    <li>ocamlPackages.cudf</li>
    <li>ocamlPackages.dose3</li>
    <li>ocamlPackages.javalib</li>
    <li>ocamlPackages.mariadb</li>
    <li>ocamlPackages.mccs</li>
    <li>ocamlPackages.ocaml-sat-solvers</li>
    <li>ocamlPackages.ocaml_extlib</li>
    <li>ocamlPackages.ocaml_oasis</li>
    <li>ocamlPackages.pgsolver</li>
    <li>ocamlPackages.sawja</li>
    <li>ocamlPackages.tcslib</li>
    <li>virt-top</li>
  </ul>
</details>

**Comment by r-burns** [comment]
Perhaps a more correct solution is to have findlib add createOcamlDestDir to postHooks, instead of preConfigureHooks? Causes many more rebuilds though, so not sure if it's appropriate for a staging-next fix.

**Comment by r-burns** [comment]
Result of `nixpkgs-review pr 136821` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>ocamlPackages.ocaml_extlib-1-7-7</li>
  </ul>
</details>
<details>
  <summary>56 packages built:</summary>
  <ul>
    <li>beluga</li>
    <li>google-drive-ocamlfuse</li>
    <li>haxe</li>
    <li>haxePackages.hxcpp</li>
    <li>haxePackages.hxcs</li>
    <li>haxePackages.hxjava</li>
    <li>haxePackages.hxnodejs_4</li>
    <li>haxe_4_0</li>
    <li>haxe_4_1</li>
    <li>jackline</li>
    <li>libbap</li>
    <li>liquidsoap</li>
    <li>ocamlPackages.async_smtp</li>
    <li>ocamlPackages.bap</li>
    <li>ocamlPackages.camomile</li>
    <li>ocamlPackages.caqti-driver-mariadb</li>
    <li>ocamlPackages.charInfo_width</li>
    <li>ocamlPackages.cryptokit</li>
    <li>ocamlPackages.cudf</li>
    <li>ocamlPackages.dose3</li>
    <li>ocamlPackages.eliom</li>
    <li>ocamlPackages.email_message</li>
    <li>ocamlPackages.gapi_ocaml</li>
    <li>ocamlPackages.gettext-camomile</li>
    <li>ocamlPackages.graphql_ppx</li>
    <li>ocamlPackages.javalib</li>
    <li>ocamlPackages.jwto</li>
    <li>ocamlPackages.lambdaTerm</li>
    <li>ocamlPackages.mariadb</li>
    <li>ocamlPackages.mccs</li>
    <li>ocamlPackages.ocaml-sat-solvers</li>
    <li>ocamlPackages.ocaml_extlib</li>
    <li>ocamlPackages.ocaml_oasis</li>
    <li>ocamlPackages.ocsigen-start</li>
    <li>ocamlPackages.ocsigen-toolkit</li>
    <li>ocamlPackages.ocsigen_server</li>
    <li>ocamlPackages.pgsolver</li>
    <li>ocamlPackages.reason</li>
    <li>ocamlPackages.reason-native.console</li>
    <li>ocamlPackages.reason-native.dir</li>
    <li>ocamlPackages.reason-native.file-context-printer</li>
    <li>ocamlPackages.reason-native.fp</li>
    <li>ocamlPackages.reason-native.pastel</li>
    <li>ocamlPackages.reason-native.pastel-console</li>
    <li>ocamlPackages.reason-native.qcheck-rely</li>
    <li>ocamlPackages.reason-native.refmterr</li>
    <li>ocamlPackages.reason-native.rely</li>
    <li>ocamlPackages.reason-native.rely-junit-reporter</li>
    <li>ocamlPackages.sawja</li>
    <li>ocamlPackages.tcslib</li>
    <li>ocamlPackages.utop</li>
    <li>ocamlPackages.zed</li>
    <li>opa</li>
    <li>python38Packages.bap</li>
    <li>python39Packages.bap</li>
    <li>virt-top</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Thank you for this!

**Pull request merged**
