### PR TITLE
duplicacy: 2.3.0 -> 2.7.2

### PR DESCRIPTION
**Pull request by Dyazz**
###### Motivation for this change

This update brings a lot of news back-ends. You can now use OneDrive as a storage back-end.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 107767` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>duplicacy</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Looks good to me.

```bash
[nix-shell:~/.cache/nixpkgs-review/pr-107767/results/duplicacy/bin]$ ./duplicacy 
NAME:
   duplicacy - A new generation cloud backup tool based on lock-free deduplication

USAGE:
   duplicacy [global options] command [command options] [arguments...]
   
VERSION:
   2.7.2 (unofficial)
   
COMMANDS:
   init         Initialize the storage if necessary and the current directory as the repository
   backup       Save a snapshot of the repository to the storage
[...]
```

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107767` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>duplicacy</li>
  </ul>
</details>

**Comment by jonringer** [comment]
@Dyazz thanks for making your first nixpkgs PR :)

**Review by jonringer — COMMENTED** [review]
kind of small, but
To comply with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) please have the commit message name be of the format
```
<pkg-name>: <subject-line>
```
for more examples, please look at https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

in your case, the commit message should be:
```
duplicacy: 2.3.0 -> 2.7.2
```

missing `:`, and should be lower case

otherwise, LGTM

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107767` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>duplicacy</li>
  </ul>
</details>

**Comment by Dyazz** [comment]
> 
> 
> kind of small, but
> To comply with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) please have the commit message name be of the format
> 
> ```
> <pkg-name>: <subject-line>
> ```
> 
> for more examples, please look at https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes
> 
> in your case, the commit message should be:
> 
> ```
> duplicacy: 2.3.0 -> 2.7.2
> ```
> 
> missing `:`, and should be lower case
> 
> otherwise, LGTM

My bad. I reformatted the commit message.

Thanks for the reviews !

**Comment by jonringer** [comment]
> My bad. I reformatted the commit message.
> 
> Thanks for the reviews !

The title was changed, but the commit is the same. Need to do:
```
git commit --amend
# edit subject line
# save
git push ... ... --force
```

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 107767` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>duplicacy</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
