### PR TITLE
chromedriver: add support for aarch64-darwin

### PR DESCRIPTION
**Pull request by kalekseev**
###### Motivation for this change

Provide binary for Apple Silicon

###### Things done

Haven't tested `update.py` script but change is straightforward.
That change can be incorporated into the next chrome version bump, to make sure that everything works as expected.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
Evaluation seems to fail?

**Comment by kalekseev** [comment]
@domenkozar where do you see the failure? All GitHub actions passed including aarch64-darwin

**Comment by primeos** [comment]
There was already a PR for this: https://github.com/NixOS/nixpkgs/pull/128979. @kalekseev did you try running chromedriver ("Tested basic functionality of all binary files (usually in ./result/bin/)" isn't checked). Apparently it might just segfault: https://github.com/NixOS/nixpkgs/pull/128979#issuecomment-1003599950.

(I just now noticed this change during a Chromium update since I wasn't pinged here.)

**Comment by kalekseev** [comment]
@primeos it works with my project's testsuite, it's a standalone binary on macos that nix downloads from release page so I'm not sure how that can segfault (the only idea is a mismatch between chromedriver and chrome version)

**Pull request merged**
