### PR TITLE
Trytond dependencies updates

### PR DESCRIPTION
**Pull request by johbo**
###### Motivation for this change

While working on the integration of trytond I have found that some packages need to be updated. I've grouped the updates into this PR.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by johbo** [comment]
This seems to cause quite a few rebuilds, I guess it's best to re-create against staging.

**Comment by johbo** [comment]
uh, seems the base branch can be changed, guess it's just a rebase then :D

**Comment by FRidh** [comment]
yes, rebase it  yourself to staging. Afterwards, I'll change the merge target here and then its good.

**Comment by johbo** [comment]
I'll try a nox run on my box, but I guess that will run a while :D

**Comment by 7c6f434c** [comment]
Now that's a large `nox-review` run (tried running it, still running, no guarantees that I will finish running it and not give up…)

**Comment by FRidh** [comment]
@7c6f434c I think we can just go ahead and merge. We can always revert.

**Review by FRidh — APPROVED** [review]

**Comment by 7c6f434c** [comment]
@FRidh this being _Python_ packages (and I am not their maintainer), I would just defer to your judgement if you merged yourself.

**Pull request merged**
