### PR TITLE
[DRAFT] nocodb: init at 0.84.1

### LINKED ISSUE #153512: [Packaging request] NocoDB
**Project description**
[NocoDB](https://nocodb.com/) is an [Airtable](https://www.airtable.com/) alternative, similar to [Baserow](https://baserow.io/). A web application for displaying and managing database information.

**Metadata**

* homepage URL: https://nocodb.com
* source URL: https://github.com/nocodb/nocodb
* license: agpl3
* platforms: unix, linux, darwin

### PR DESCRIPTION
**Pull request by onny**
###### Motivation for this change
Packages nocodb web app and fixes https://github.com/NixOS/nixpkgs/issues/153512 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Not sure yet on how to run the backend and frontend servers. Backend server should be present at:
```
/nix/store/[...]-nocodb-0.84.1/lib/node_modules/nocodb/packages/nocodb
```
According to `package.json` the `run` command will execute:
```
ts-node src/example/docker
```
Where `src/example/docker.ts` is a typescript file. Should we run it with `ts-node`?

**Comment by onny** [comment]
> Not sure yet on how to run the backend and frontend servers. Backend server should be present at:
> 
> ```
> /nix/store/[...]-nocodb-0.84.1/lib/node_modules/nocodb/packages/nocodb
> ```
> 
> According to `package.json` the `run` command will execute:
> 
> ```
> ts-node src/example/docker
> ```
> 
> Where `src/example/docker.ts` is a typescript file. Should we run it with `ts-node`?

Is anyone familiar with this? @SuperSandro2000 @happysalada @aanderse

**Comment by happysalada** [comment]
It seems they run ts-node in dev mode to have automatic refresh.

their dockerfile however references a main.js
https://github.com/nocodb/nocodb/blob/master/packages/nocodb/Dockerfile#L28
Since main.js is not included in the repo, there is a possibility it's built by the project. If after building the project it's still not there, then I would try using `node` with `docker/index.js` which seem to do the same as the docker.ts file.

**Comment by onny** [comment]
I'm able to compile and run it in ArchLinux:

```
pacman -S ts-node
git clone https://github.com/nocodb/nocodb
cd nocodb
# run backend
cd packages/nocodb
npm install
ts-node src/example/docker --log-error --project tsconfig.json
```

The daemon is listening on :8080

**Comment by SuperSandro2000** [comment]
I think this could also be part of nodePackages.

**Comment by onny** [comment]
> I think this could also be part of nodePackages.

I tried it, added  `nocodb` to `node-packages.json` file. After successfull build, there is no binary in `./result/bin`. Not exactly sure if its a possible way to build this package?

**Comment by happysalada** [comment]
if I remember correctly it's not ad simple as that.
nocodb had many subpackages (in the repo).
a brief check on the npm package doesn't mention a binary https://www.npmjs.com/package/nocodb
We will have to check further how this can be used.

**Comment by l5r** [comment]
I managed to package it for myself by writing a [small wrapper application](https://github.com/l5r/nixcfg/tree/master/pkgs/nocodb)

**Comment by onny** [comment]
> I managed to package it for myself by writing a [small wrapper application](https://github.com/l5r/nixcfg/tree/master/pkgs/nocodb)

Thats cool :) Are you planning to open a pull request for this?

**Comment by DamienCassou** [comment]
Does anyone still care about this? The PR has conflicts and must be rebased.

**Comment by jlbribeiro** [comment]
> I managed to package it for myself by writing a [small wrapper application](https://github.com/l5r/nixcfg/tree/master/pkgs/nocodb)

To add to this conversation (and to keep this PR alive), @l5r's wrapper app is distributed as [nocodb/nocodb-seed](https://github.com/nocodb/nocodb-seed) and _briefly_ mentioned in [NocoDB's README](https://github.com/nocodb/nocodb#node-application). Not sure how up-to-date `nocodb/nocodb-seed` is kept in relation to `nocodb`, so it might be worth just packaging the "seed" app along the package definition (like @l5r did) since it would provide greater control over the versioning.
But like @SuperSandro2000 mentioned, `nocodb` should probably be in `nodePackages` as well; separate _quests_ for now, though.

**Comment by SuperSandro2000** [comment]
It should be an extra package using buildNpmPackage if possible. Generating nodePackages is a terrible task because it is so big, takes forever and has no caching or parallism.

**Comment by lucasew** [comment]
> Is this still underway?

Seems like it's not. Closing. Things changed a lot in this time tho.

**Comment by sinanmohd** [comment]
https://github.com/NixOS/nixpkgs/pull/378544

**Pull request closed without merging**
