### PR TITLE
seq66: fix build against `gcc-13`

### PR DESCRIPTION
**Pull request by trofi**
Without the chnage build fails on `master` as:

    In file included from os/daemonize.cpp:64:
    ../include/os/daemonize.hpp:58:8: error: 'uint32_t' does not name a type
       58 | extern uint32_t daemonize
          |        ^~~~~~~~
    ../include/os/daemonize.hpp:36:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
       35 | #include "seq66_platform_macros.h"      /* for detecting 32-bit builds      */
      +++ |+#include <cstdint>

As upstream changes are quite invasive for backport I am only injecting missing headers.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
builds but segfaults when trying to run:
```console
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

[1]    723867 IOT instruction (core dumped)  ./result/bin/qseq66
```

**Comment by trofi** [comment]
Great catch! I think it's a side-effect of a missing plugin path. As a result `qt` fails to find any rendering backends. Attempted to fix as `seq66: enable Qt wrapper to fix plugin loading`. This allows starting GUI for me.

**Review by ghost — COMMENTED** [review]
the qt-wrapper is an improvement but it fails to find a sound device -- pulse audio would work -- but there is no plugin located under `/nix/store/bzjr9mcffxbvhi4h2r43canrr83mi876-alsa-lib-1.2.9`
```console
[No 'rc' file, will create qseq66.rc / ctrl / midi]
[No 'usr' file, will create /home/anna/.config/seq66/qseq66.usr]
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
? JACK server not running?
? JACK server not running?
[? rtmidi_info: no system support for specified API]
ALSA lib conf.c:4005:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/nix/store/bzjr9mcffxbvhi4h2r43canrr83mi876-alsa-lib-1.2.9/lib/alsa-lib/libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
? error opening ALSA sequencer client
terminate called after throwing an instance of 'seq66::rterror'
  what():  no rtmidi API support found
[1]    888823 IOT instruction (core dumped)  result/bin/qseq66
```

**Comment by trofi** [comment]
Seems to run successfully against `pipewire` for me:

```
nix run github:NixOS/nixpkgs/pull/280768/head#seq66
[Reading rc configuration /home/slyfox/.config/seq66/qseq66.rc]
[Reading MIDI control file /home/slyfox/.config/seq66/qseq66.ctrl]
[32 loop-control lines]
[32 mute-group-control lines]
[50 automation-control lines]
[Reading mute group file /home/slyfox/.config/seq66/qseq66.mutes]
[Filter-by-channel off]
[Reading user configuration /home/slyfox/.config/seq66/qseq66.usr]
[Non-I/O port 'PipeWire-System']
[Non-I/O port 'PipeWire-RT-Event']
[Initialized, running without JACK sync]
3 rtmidi ports created:
Input ports (2):
  [0] 0:1 system:announce (system)
  [1] 14:0 Midi Through:Midi Through Port-0
Output ports (1):
  [0] 14:0 Midi Through:Midi Through Port-0
```

**Review by ghost — APPROVED** [review]
may not work for me but still seems like this change is a big improvement -- builds and can run.

**Pull request merged**
