### PR TITLE
staging-next 2021-10-15

### PR DESCRIPTION
**Pull request by mweinelt**
Another staging-next iteration. Documentation here: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-staging-next-branch

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

*Per the [release schedule](https://discourse.nixos.org/t/lets-have-a-great-21-11-release-cycle/15262/3?u=hexa) we are now restricted to non-breaking changes to release critical packages.*

### CODE REVIEW

**Comment by lourkeur** [comment]
pybind11 in 86b096d6efd1cf5897163abc5e0378b4bab3b76e seems to break `python3Packages.blspy` and others

<details><summary>error message</summary>

```
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: blspy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/p3c7js1a70c3v28vhbcnq1fvffmxwx6f-python3-3.9.7/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /nix/store/drrypsf90628kpkghkz8aj4vav07jw7j-python3.9-blspy-1.0.6/lib/python3.9/site-packages/blspy.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3bls9GTElement4SIZEE
 ```

**Comment by happysalada** [comment]
I'm having a weird error building rust executables on darwin-x86_64
```
/nix/store/9bfrvss4b2jmpffh00m2drwd0z3j5zfm-cargo-1.55.0/bin/cargo: line 5: /nix/store/9bfrvss4b2jmpffh00m2drwd0z3j5zfm-cargo-1.55.0/bin/.cargo-wrapped: cannot execute binary file: Exec format error
/nix/store/9bfrvss4b2jmpffh00m2drwd0z3j5zfm-cargo-1.55.0/bin/cargo: line 5: /nix/store/9bfrvss4b2jmpffh00m2drwd0z3j5zfm-cargo-1.55.0/bin/.cargo-wrapped: Undefined error: 0
```
this can be replicated by building alacritty for example.
I really have no idea where this could be coming from.

**Comment by happysalada** [comment]
commit https://github.com/NixOS/nixpkgs/pull/141684/commits/77e346f6eda9811cbd33ce0ff9fcce6b47364fea appears to be working fine
(some earlier commits had unrelated problems).
Latest commit is definitely not working.
Testing adf4e67

**Comment by jonringer** [comment]
They should be easy enough to fix

librsvg
```
ld: framework not found Foundation
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

jedi has a test failure around import differences between platforms, which we probably don't care about

**Comment by jonringer** [comment]
librsvg might be a bit more involved, foundation is already getting passed. ` CCLD` doesn't seem to be aware of the Foundation framework.

**Comment by happysalada** [comment]
I've tested a PR upgrading coreutils to 9 for darwin.

**Comment by vcunat** [comment]
I believe that all the larger regressions have been fixed.  https://hydra.nixos.org/eval/1718058?compare=1718001

**Comment by vcunat** [comment]
Next iteration: https://github.com/NixOS/nixpkgs/pull/144730

**Pull request merged**
