### PR TITLE
minio, minio-client: 2019-10-12 -> 2019-12-17

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
`minio`: https://github.com/minio/minio/releases/tag/RELEASE.2019-12-17T23-16-33Z
`minio-client`: https://github.com/minio/mc/releases/tag/RELEASE.2019-12-17T23-26-28Z

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @edolstra @bachp

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/75879)

### CODE REVIEW

**Comment by filalex77** [comment]
@GrahamcOfBorg build minio-client

**Comment by filalex77** [comment]
Need some help on `subPackages` for `minio-client` :)

**Comment by bachp** [comment]
@filalex77 what exactly is it you need help with?

**Comment by dR3b** [comment]
What's the status here? Thanks!

**Comment by bachp** [comment]
@filalex77 I created https://github.com/NixOS/nixpkgs/pull/82138 to bring minio and minio client to the latest version.

**Comment by marsam** [comment]
addressed by #82138

**Pull request closed without merging**
