### PR TITLE
gtk4: 4.8.2 → 4.8.3

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

https://gitlab.gnome.org/GNOME/gtk/-/compare/4.8.2...4.8.3

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build libshumate

**Comment by bobby285271** [comment]
Ught, hydra says that some `libshumate` tests are failing, probably introduced here: https://hydra.nixos.org/build/202846003

I wonder if we should do something like `GTK_A11Y=none` to its checkPhase.

**Comment by jtojnar** [comment]
Ugh. Yeah, that will be probably needed. Like we had to do `NO_AT_BRIDGE=1` for some GTK 3 programs.

**Comment by jtojnar** [comment]
Opened #207546

**Comment by trofi** [comment]
Bisect claims `gtksourceview5` started failing it's tests as https://hydra.nixos.org/log/5ayrdz8hlng38kfrqx7xpjy4q6lkmm74-gtksourceview-5.6.1.drv after 0b714816fdc46eb9621d632ea573b841ee4d0ec8 `gtk4: 4.8.2 → 4.8.3`:

```
Summary of Failures:

16/26 test-buffer               FAIL            0.12s   killed by signal 5 SIGTRAP
19/26 test-printcompositor      FAIL            0.08s   killed by signal 5 SIGTRAP
20/26 test-space-drawer         FAIL            0.07s   killed by signal 5 SIGTRAP
21/26 test-view                 FAIL            0.07s   killed by signal 5 SIGTRAP
22/26 test-vim-input            FAIL            0.07s   killed by signal 5 SIGTRAP
25/26 test-vim-state            FAIL            0.13s   killed by signal 5 SIGTRAP
```

**Comment by jtojnar** [comment]
That is also resolved by https://github.com/NixOS/nixpkgs/pull/207546

**Pull request merged**
