### PR TITLE
kde5: fix extra-cmake-modules hooks

### PR DESCRIPTION
**Pull request by ttuegel**
The hooks are broken for a few packages.

### CODE REVIEW

**Comment by ttuegel** [comment]
Evaluation succeeds on Travis; the failure seems to be spurious.

**Comment by obadz** [comment]
Have you seen these? http://hydra.nixos.org/eval/1285499#tabs-now-fail

**Comment by ttuegel** [comment]
@obadz No, because Hydra stopped mailing again. :unamused:

Actually, all those build locally with a few subsequent fixes that I pushed yesterday. They should be picked up by the next evaluation.

**Comment by obadz** [comment]
Ok thanks!

Yes hydra was down for a while :-(

```
2016-07-30 01:09:28 obadz niksnut, ikwildrpepper: http://hydra.nixos.org/ is down
2016-07-30 15:45:18 obadz niksnut, ikwildrpepper: http://hydra.nixos.org/ still down
2016-07-31 13:47:00 obadz niksnut, ikwildrpepper: http://hydra.nixos.org/ still down
2016-07-31 15:08:32 obadz horray, hydra is back up!
```

(Times are BST)

**Pull request merged**
