### PR TITLE
chromium: Update upstream versions

### PR DESCRIPTION
**Pull request by bradediger**
`chromium-binary-plugins` is broken on master because the upstream versions went away. 

Building and testing locally right now... will check off testing tasks below when complete.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by NeQuissimus** [comment]
@bradediger Could you be so kind to take care of google-chrome as well? That would fix #17480

**Comment by bradediger** [comment]
@NeQuissimus Are you sure it isn't covered by this one? Looks like `google-chrome` [depends on `chromium.upstream-info`](https://github.com/NixOS/nixpkgs/blob/ef46388c487cc58cd064ba2298a4ea9c7076c28a/pkgs/applications/networking/browsers/google-chrome/default.nix#L35), which I updated here.

**Comment by bradediger** [comment]
> Cannot write: No space left on device

Sorry travis-ci :unamused:

**Comment by NeQuissimus** [comment]
@bradediger Oh, my bad. That is very much possible.

**Comment by domenkozar** [comment]
cc @aszlig

**Comment by NeQuissimus** [comment]
It would seem that @benley did this in #17500

**Pull request closed without merging**
