### PR TITLE
 pythonPackages.lz4: remove in favor of pythonPackages.python-lz4

### PR DESCRIPTION
**Pull request by veprbl**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review pr 51603"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @costrouc

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build mozlz4a python27Packages.buildbot python27Packages.joblib python27Packages.uproot python37Packages.uproot

**Comment by FRidh** [comment]
Why?

**Comment by veprbl** [comment]
@FRidh Because right now `lz4` is just an outdated version of `python-lz4`.

**Comment by FRidh** [comment]
Care to document that in the commit message(s).

**Comment by veprbl** [comment]
@FRidh done!

**Comment by veprbl** [comment]
@GrahamcOfBorg build python2Packages.python-lz4 python3Packages.python-lz4

**Comment by veprbl** [comment]
pythonPackages.lz4 was bumped to 2.1.2 in 57aa856d25fa63239a55e4523cdb89f8f76ad012 and 775fa99aa432892eebf5e24ccc3d5fa815adaa90. We still need to get rid of the duplicates.

**Pull request merged**
