### PR TITLE
ghidra: add support for aarch64-darwin

### PR DESCRIPTION
**Pull request by greedy**
###### Description of changes

Adds aarch64-darwin as a supported platform.

This also changes the method used to change Java's notion of the user home directory. Instead of redirecting /etc/passwd to a generated file, the JAVA_TOOL_OPTIONS environment variable is used to provide a value for the user.home system property. The redirect method did not seem to be effective on my Monterey (12.6) system and the new approach is IMO simpler anyway.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by greedy** [comment]
A backport to 22.05 would be nice

**Comment by risicle** [comment]
This looks sensible to me, and builds happily on macos 10.15 & nixos x86_64. Would have to be quite certain there were no regressions from this to bring it to 22.05.

**Comment by greedy** [comment]
I would think this change doesn't have any changes in the build products so I could try this patch on top of the release branch and check for differences. It turns out that there are a few non-reproducibility issues in the build related to timestamps and ordering of items in the zip and jar files and the listings of files by license. Still, by using `unzip -lqv`, which includes the CRC32 for each file, using `sed -e 's/[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9] [0-9][0-9]:[0-9][0-9]/00-00-0000 00:00/' to clear the impure timestamps, and `sort -k8` to sort the listings by filename, nearly all the class files were the same. I believe the exceptions were generated code (e.g. from antlr grammars) that may have had timestamps or non-deterministic ordering of members.

I'd like to submit a further fix to try and improve the reproducibility of the build, probably as a separate PR. Are there any guides, tools, and/or advice for making JAR and ZIP files with good reproducibility?

**Comment by risicle** [comment]
The "unexpected changes" often come from the more obscure platforms which we haven't managed to test. But this has an explicitly restricted set of platforms anyway, so that probably reduces that problem.

**Review by risicle — APPROVED** [review]

**Pull request merged**
