### PR TITLE
errbot: 5.2.0 -> 6.1.1

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
fixing @r-ryantm  updates

Also:
- enabled tests

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @fpletz  @globin 

```
nix-review pr 67781
...
[1 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/67781
1 package were build:
errbot
```
```
$ nix path-info -Sh ./result
/nix/store/j4w4z2pg2m50wzbmfqfc94lvqsmw1lwd-errbot-6.1.1         140.4M
$ nix path-info -Sh ./result
/nix/store/ijqcs0bygkpqipf1wgsfkspd0d256w02-errbot-5.2.0         132.5M
```

### CODE REVIEW

**Comment by jonringer** [comment]
noticed that installing the `pyside` extra included the qt4 closure... removed it to save 600MB

**Comment by mmahut** [comment]
Do you mind resolving the conflict please?

**Comment by mmahut** [comment]
@GrahamcOfBorg build errbot

**Comment by fpletz** [comment]
Rebased onto current master and fixed the conflict.

**Pull request merged**
