### PR TITLE
Auto format and resize with systemd

### LINKED ISSUE #165256: autoResize and autoFormat should use mount options x-systemd.makefs and x-systemd.growfs instead of custom units
Systemd includes code in `systemd-fstab-generator` that will format and resize file systems automatically. There's no need for our custom units.

### PR DESCRIPTION
**Pull request by ElvishJerricco**
###### Description of changes

Closes #165256

This removes a few bespoke chunks of code with questionable value, in favor of implementations straight out of systemd. The supported features are *slightly* different, but I think most common use cases are covered.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by flokli — APPROVED** [review]

**Comment by arianvp** [comment]
Dropping `f2fs` seems an unfortunate breaking change as it's a popular file system format for phones (e.g. Mobile NixOS probably uses it). Apart from that LGTM but lets maybe bump the Mobile NixOS people?

**Comment by flokli** [comment]
It shouldn't be too hard to add support for this to systemd upstream.

**Comment by ElvishJerricco** [comment]
@flokli Can f2fs be resized online? The reason `systemd-growfs` works on the FSes it does is because it knows their ioctls for resizing a live file system while it's mounted. It's ordered *after* its mount unit for this reason.

And @arianvp FWIW this only really affects stage 1 FSes, since stage 2 doesn't have *any* resizing support before this PR. That's also why this PR removes resizing from stage 1 in its entirety; it resizes live, mounted file systems in stage 2 instead.

**Comment by ElvishJerricco** [comment]
> let's maybe bump the Mobile NixOS people

Oh and IIUC mobile NixOS has its own initrd, so changes to the regular NixOS one shouldn't matter?

**Review by nikstur — APPROVED** [review]
Looks good, gaining resizing of btrfs and xfs seems to be fair trade off over losing f2fs

**Comment by flokli** [comment]
This needs another rebase due to release note changes.

**Comment by ElvishJerricco** [comment]
@flokli Done.

**Review by nikstur — APPROVED** [review]

**Comment by ElvishJerricco** [comment]
Oh, i was just about to update this PR to use `mkRemovedOptionModule`, which I should have done in the first place. I'll open a new PR I suppose.

**Comment by ElvishJerricco** [comment]
@arianvp Are you sure this is something we should backport? It is technically a couple of breaking changes.

**Pull request merged**
