### PR TITLE
lib/systems/inspect.nix: add isAarch

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I find it nice that the proposed name differs from earlier `.isArm`  https://github.com/NixOS/nixpkgs/pull/79291

**Comment by SuperSandro2000** [comment]
I didn't check that but the functionally is also different. isArm was just an alias ``isArm = isAarch32;``

**Comment by vcunat** [comment]
Yes, that's why I thought it's good that the names differ.  For the unlikely case that someone still had code using `isArm`.

**Comment by SuperSandro2000** [comment]
So can we merge it? You didn't approve so I am unsure if I can self merge.

**Comment by vcunat** [comment]
I can't see any issue with it, but overall I haven't much dealt with platform-specific stuff.  I'd probably wait for feedback for more than several hours.

**Comment by eitau** [comment]
Can we backport it? I wanted to use [recent home-assistant version](https://nixos.wiki/wiki/Home_Assistant#Running_a_recent_version_using_an_overlay) on my 22.05 server but, you know, the `attribute 'isAarch' missing` is there.

**Comment by vcunat** [comment]
I don't see a problem with that, so let me open it at least.

**Pull request merged**
