### PR TITLE
nixos/networkd: Add routes from interfaces to [Route] section of .network file

### PR DESCRIPTION
**Pull request by duairc**
###### Motivation for this change

Similarly to my motivation for #93598, I want to improve consistency between when `networking.useNetworkd` is `true` and when it's `false`. In particular I want to be able to write a NixOS module that can abstract out a non-trivial networking setup but still be agnostic to whether the system uses networkd or not.

Currently any routes that are set in `networking.interfaces.<interface>.routes` are completely ignored when using networkd. This commit instead adds them to the `systemd.network.networks.<network>.routes` option of the corresponding networkd network.

One thing that's tricky is that there isn't a trivial mapping between the options in `networking.interfaces.<interface>.routes`, which allows you to specify `interface`, `via` and `options` (the latter is passed more or less directly to the `ip route` command) and `systemd.network`'s `[Route]` options. I've not attempted to do this in a complete way, but I do look at some of the `options` attributes and try to do the most sensible thing with them. I chose the particular options I did simply because they were useful to me. The "proper" way to do this would probably be to move them to be top level options of `networking.interfaces.<interface>.routes` rather than untyped strings in the `options` attrset..

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by duairc** [comment]
I didn't mean to close this. I messed up a force-push and GitHub closed it on my behalf. I've fixed that but I can't seem to reopen it.

**Comment by erictapen** [comment]
I'm using this for over a year now on my systems and would like to have it merged.

**Comment by andir** [comment]
Do we have VM tests that exercise this code? If so I am in favor of merging.

**Comment by Luflosi** [comment]
I improved upon this PR in #144590.

**Pull request closed without merging**
