### PR TITLE
nixos default channel: use http instead of https

### PR DESCRIPTION
**Pull request by vcunat**
AFAIK https doesn't work in nixos-rebuild --upgrade. I just stumbled into it on a clean install, and I think that I heard before users complaining about errors like this.

Any comments?

### CODE REVIEW

**Comment by ballo** [comment]
I just attempted a fresh install on OS X and got this error. Why is this ticket closed?

**Comment by vcunat** [comment]
- This PR is against release 14.04 which is long unsupported.
- You probably need to provide more specific info to get to the root of the issue.

**Comment by ballo** [comment]
OK, specifically I ran (as instructed):

curl https://nixos.org/nix/install | sh

aaaaand, that's it.

**Comment by kirelagin** [comment]
@ballo OK, given the information you provided, looks like something is not working.

**Comment by vcunat** [comment]
The script runs `curl -L https://nixos.org/releases/nix/nix-1.10/nix-1.10-x86_64-darwin.tar.bz2` (on darwin), and that works for me ATM (on linux).

**Comment by ballo** [comment]
This is Yosemite, BTW

**Comment by cstrahan** [comment]
I just installed Nix on my new Mac and I'm also still getting this. This is on El Capitan.

**Comment by ballo** [comment]
Oh good, it isn't just Yosemite. Hopefully this can be fixed for both

**Comment by Treeant34** [comment]
Tried installing Nix twice on OS X 10.10.5 (VMWare Fusion 8 guest) using the shell command (curl https://nixos.org/nix/install | sh) and keep getting the same error (unable to check ‘https://nixos.org/channels/nixpkgs-unstable’).

https://github.com/NixOS/nix/issues/728

I wanted to try this package manager on OS X, as I really see this as the package management model for the future, but I am stumped at the moment (being a Nix Newb). There isn't a pile of info out there for OS X installation regarding Nix. Is it possible to execute multiple commands in terminal to get Nix installed on Yosemite (since the script install doesn't want to work) and if so, what are they?

Help?

Thx

**Comment by chrislambda** [comment]
Same problem here, running OS X Yosemite 10.10.5.  I just ran the command:

curl https://nixos.org/nix/install | sh

and got

/nix/store/<stuff>/nix-1.10/bin/nix-channel: unable to check ‘https://nixos.org/channels/nixpkgs-unstable’

**Comment by ivan-krukov** [comment]
Seeing the same issue on a fresh El Capitan installation.
After seeing the error the first time, I have changed the `$url` on line `30` to `http`, and the installation completed (apparently) successfully.

```bash
curl https://nixos.org/nix/install -O
sed -i '' 's/http/https/g' install
sh ./install
```

**Pull request closed without merging**
