### PR TITLE
go: 1.18rc -> 1.18

### PR DESCRIPTION
**Pull request by elliot-u410**
###### Description of changes

Update go_1_18 from 1.18rc1 to 1.18.

Update default version of go from 1.17 -> 1.18.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by noch3** [comment]
I may not have named the first commit message correctly.

**Comment by noch3** [comment]
`go_2-dev` is likely obsolete now. Removing that is backward breaking and should be a separate MR.

**Comment by zowoq** [comment]
I've dropped the 1.17 -> 1.18 commit, it requires other changes and testing.

**Comment by noch3** [comment]
Is it just the two failed packages or are there other things needed?

**Comment by zowoq** [comment]
> `go_2-dev` is likely obsolete now.

No, `go_2` is not obsolete.

**Comment by zowoq** [comment]
> Is it just the two failed packages or are there other things needed?

The 1.17 -> 1.18 was incomplete as it was, it didn't change `buildGo{Module,Package}`. It will cause many rebuilds and likely lots of breakage that needs to be fixed or pinned. See https://github.com/NixOS/nixpkgs/pull/113230 as an example.

**Comment by noch3** [comment]
Awesome. Thank you.

**Pull request merged**
