### PR TITLE
nixos/unifi: add deprecation warning for openPorts

### PR DESCRIPTION
**Pull request by pennae**
###### Motivation for this change

#149889 

cc @lunik1 @erictapen 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lunik1** [comment]
I think it's a little clear to explicitly say `false` will be the new default, something like

> The current services.unifi.openPorts = true default is deprecated and will change to false in 22.11. Set it explicitly to silence this warning.

LGTM otherwise.

**Comment by aanderse** [comment]
Should we take this opportunity to rename the option to the standard `openFirewall` while we're at it?

**Comment by pennae** [comment]
changed the name as well now. shouldn't hurt, it having been enabled by default all along anyway.

**Review by erictapen — COMMENTED** [review]
If we already change the name of the option, why not just add openFirewall as a new option, deprecate the openPorts option and add some assertion that openPorts and openFirewall must be consistent? The assertion could then provide context for the change in default behaviour, e.g. `You probably didn't set this explicitly, but the default changed.`.

This way we don't have to force new users to explicitly set openFirewall = false.

**Comment by pennae** [comment]
that's also an option, but aliasing the option and warning if it's not set to anything explicitly seems like it'd make a smoother transition. existing configs would continue to work without changes for a while and just warn that openPorts has been renamed and openFirewall isn't explicitly set true. having two options that must be consistent would require people to set *two* options for the transitional period, and when (if? what's the removal period for renamed options?) we remove openPorts their config would break again.

if that's not an important consideration for you then we're just as fine to remove openPorts outright in favor of openFirewall with a changed default.

**Review by bachp — APPROVED** [review]

**Comment by erictapen** [comment]
There appeared merge conflicts in the release notes. Could you fix these? I think after that it is fine to merge.

**Comment by pennae** [comment]
updated again :+1: the release notes can be a bit annoying sometimes :sweat_smile:

**Review by erictapen — APPROVED** [review]
Thanks!

**Pull request merged**
