### PR TITLE
nodePackages.tailwindcss: init at 3.0.1

### LINKED ISSUE #149333: Packaging request: tailwindcss cli
**Project description**

Tailwindcss is a utility-first CSS framework. The team has recently built a cli to facilitate the compilation process.

**Metadata**

* homepage URL: https://tailwindcss.com/docs/installation#using-tailwind-cli
* source URL: https://github.com/tailwindlabs/tailwindcss
* license: mit
* platforms: it is an npm package, so unix, linux, darwin

Here is also the link to the npm package containing the executable of the cli: https://www.npmjs.com/package/tailwindcss

It does not seem complicated to build in Nix but I have just never done that before so it feels a little overwhelming to me. Would appreciate a hand.

### PR DESCRIPTION
**Pull request by jyooru**
###### Motivation for this change

Closes #149333

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jyooru** [comment]
Running `pkgs/development/node-packages/generate.sh` seems to have also updated all the other node packages. I'm running nixpkgs-review on this PR now and I'm already seeing some failures due to the updates. Is there a way to add tailwindcss without updating all the other packages?

**Comment by jyooru** [comment]
Result of `nixpkgs-review pr 149839` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>hyperspace-cli</li>
    <li>teleprompter</li>
    <li>timedoctor</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
  </ul>
</details>
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bat-extras.prettybat</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>deltachat-desktop</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>gtop</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>lumo</li>
    <li>parity-ui</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>shepherd</li>
    <li>slack</li>
    <li>sloc</li>
    <li>teams</li>
    <li>teck-programmer</li>
    <li>thelounge</li>
    <li>vimPlugins.coc-diagnostic</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>whalebird</li>
    <li>yaml-language-server</li>
    <li>zerobin</li>
    <li>zx</li>
  </ul>
</details>

**Comment by jyooru** [comment]
> * python38Packages.batchspawner

All good, I was trying to figure out if that fail was an issue of this PR!

**Comment by jyooru** [comment]
Result of `nixpkgs-review pr 149839` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>32 packages built:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>deltachat-desktop</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>joplin</li>
    <li>lumo</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
  </ul>
</details>

**Comment by lobre** [comment]
There has just been an update from Tailwind to a major version today (v3.0.0). Maybe it is worth directly integrating it to avoid having to upgrade later?

https://www.npmjs.com/package/tailwindcss

**Pull request merged**
