### PR TITLE
[19.09] chromium: 78.0.3904.108 -> 79.0.3945.79

### PR DESCRIPTION
**Pull request by ivan**
###### Motivation for this change

Backport #75516

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Untested (I am on master), please test.

###### Notify maintainers

cc @bendlas @thefloweringash

### CODE REVIEW

**Comment by ivan** [comment]
I am building chromium `chromiumBeta chromiumDev google-chrome google-chrome-beta google-chrome-dev` on taalo, it should be done in 3-4 hours.

**Comment by ivan** [comment]
All builds succeeded, but I did not run the outputs.

**Comment by thefloweringash** [comment]
Our expression for Chromium doesn't currently build on aarch64, so don't let aarch64 get in the way of merging this.

**Comment by mebubo** [comment]
@nh2 @grahamc could you merge this please?

Brings fixes to multiple CVEs to 19.09.

This pull request is a cherry-pick of 4 out of 6 commits from #75516, in master since a month ago.

Thanks!

**Pull request merged**
