### PR TITLE
nodePackages: netlify-cli init at 2.59.1

### PR DESCRIPTION
**Pull request by matthuszagh**
###### Motivation for this change
Adds the [netlify-cli](https://github.com/netlify/cli) tool. Used generate.sh to create the nix build expressions, so this also updates other packages.

###### Things done
Added netlify-cli to node-packages-v10.json and then ran `./generate.sh`.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthuszagh** [comment]
I've updated this to fix merge conflicts.

**Comment by utdemir** [comment]
I tested this on NixOS and deployed a website with it without any problems.

I think it might also make sense to add an entry to the top-level package set too.

**Comment by prusnak** [comment]
Please rework your PR. It now has a merge conflict after PR https://github.com/NixOS/nixpkgs/pull/89184 has been merged

**Comment by matthuszagh** [comment]
@prusnak I've updated this to use the new scheme. Added it to `node-packages.json` and used `generate.sh`. It builds on `nodePackages` and `nodePackages_latest`.

@utdemir in regard to adding a top-level package, this is the only node package I've contributed, so I'll defer to someone who's more familiar with nixpkgs and node packages.

**Comment by utdemir** [comment]
I do not know who to ping, but it'd be good to have this package in nixpkgs. It looks like it gets a merge conflict on `node-package.nix` while waiting for a merge, so maybe someone with a commit right should do the rebase too.

**Comment by matthuszagh** [comment]
@calbrecht I'm not sure if you're the right person to ping for a review here. Please excuse me if not. If you would be willing to provide a review, let me know and I'll fix the merge conflicts before you review (node-packages.nix is changed frequently so it doesn't make sense for me to try to keep this up-to-date before it's reviewed). Thanks!

**Comment by matthuszagh** [comment]
I've gone ahead and resolved the conflicts.

**Comment by calbrecht** [comment]
@matthuszagh, lgtm 👌 Thanks.
Have no merge rights, too :)

**Comment by matthuszagh** [comment]
@globin, would you be willing to review this PR? If so, let me know and I'll resolve the merge conflicts. Thanks!

**Comment by mrkkrp** [comment]
It would be nice to merge this.

**Comment by matthuszagh** [comment]
@mrkkrp agreed. Unfortunately, I'm not sure who the right person to contact for that is. If you do know, mind notifying them? When someone with merge rights agrees to review this, I'll go ahead and resolve the merge conflicts.

**Comment by matthuszagh** [comment]
@Infinisil would you be willing to review this PR? I noticed you merged `pyright`, but if you're not the right person for this would you happen to know who is? If you are willing, let me know and I'll fix the merge conflicts first. Thanks!

**Comment by Infinisil** [comment]
Looks good to me, I can merge it if you re-update the node packages. Feel free to ping me when done :)

**Comment by matthuszagh** [comment]
Thanks so much @Infinisil! I've fixed the merge conflicts. One remaining question: should I add a top-level package for this, or just leave it as is?

**Comment by Infinisil** [comment]
Since this is not really a node package but only happens to be written with node, it would make sense to add a top-level package.

**Comment by matthuszagh** [comment]
@Infinisil done.

**Pull request merged**
