### PR TITLE
home-assistant: 0.100.3 -> 0.103.2

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Mic92** [comment]
cc @peterhoeg

**Comment by colemickens** [comment]
I've cherry-picked and tested these changes. Works for me. Thanks!

**Comment by jonringer** [comment]
related:
#75898
#74360
#74126
#70258
#70021

**Comment by Mic92** [comment]
@GrahamcOfBorg test home-assistant

**Comment by Scriptkiddi** [comment]
also related #75876

**Comment by Mic92** [comment]
Tests do not all work since there is a problem the authentication (I assume there is no user set up). However given that the package in master is broken anyway, this PR is still an improvement.

**Comment by makefu** [comment]
great stuff, thanks!

**Comment by colemickens** [comment]
Thanks for the work here. And a heads up, the new beta is back to building. I'll keep an eye and send a PR if someone doesn't beat me when they tag it as stable.

**Pull request merged**
