### PR TITLE
 xorg.libXTrap: init at 1.0.1 (Fix build of xorg.xtrap)

### PR DESCRIPTION
**Pull request by JohnAZoidberg**
###### Motivation for this change
`xorg.xtrap` wouldn't build because the library was missing.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
This is a generated file, so we shouldn't edit it manually.
So I'm wondering why this script doesn't generate it.

**Comment by JohnAZoidberg** [comment]
I only edited tarballs.list. Is that generated, too?

**Comment by worldofpeace** [comment]
Ah, I didn't see you touching the `tarballs.list` and thought it was a manual addition only to `pkgs/servers/x11/xorg/default.nix `.

This should be good then :+1:

**Review by worldofpeace — APPROVED** [review]
I can build `xorg.xtrap`. Per directory `.gitignore` should be fine too.

**Pull request merged**
