### PR TITLE
Kernels 2021-06-10

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Review by fabianhjr — APPROVED** [review]
LGTM

EDIT: Checked out the branch and building 5.9.10

EDIT2: Build complete, rebooting

EDIT3: Booted to 5.12.10-hardened

**Review by ymatsiuk — APPROVED** [review]

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
@domenkozar perhaps this is a bug in the backport bot action: After merging this PR, a backport PR was successfully created. Then different labels changed and GHA tries to create another backport PR.

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/126825

**Pull request merged**
