### PR TITLE
[WIP] X11 updates and refactor

### PR DESCRIPTION
**Pull request by ikervagyok**
###### Motivation for this change
wanted to update xorg-server, found some mistakes and going on to fix them.

@dtzWill: have seen your updates in the PR-queue, do you have more? otherwise i start upgrading and adding packages i find and conactenate the `*.list`-files into a sorted `tarballs.list`

also i'm no perl expert, but i'm looking into a way to add `xorgproto` instead of all of `*-proto` and make it work (without the infinite recursion i encountered before). any prior art is appreciated ;)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ikervagyok** [comment]
these should be all package updates from january 2016 until now which got announced over `xorg-announce`, except for:
- packages already covered by @dtzWill
    - `libdrm` https://github.com/NixOS/nixpkgs/pull/48217
    - `libSM` https://github.com/NixOS/nixpkgs/pull/48174
    - `libx11` https://github.com/NixOS/nixpkgs/pull/48115
- the `*proto` packages, which need to be built implicitly from common upstream package `xorg-proto`
    - `*proto` (removal)
    - `xorg-proto` (init at 2018.4)
    - `xorg-server` (1.19.6 -> 1.20.2)

**Comment by dtzWill** [comment]
Wow, wonderful! Sorry for not responding earlier.  I've been updating things in a somewhat adhoc manner, going through xorg-announce is great, thanks for tackling this! I think you've got everything I've been sitting on-- partially driven by my own needs and partially to test updates before sending upstream I've been maintaining [this 'nixos-dtz' branch](https://github.com/dtzWill/nixpkgs/tree/nixos-dtz).  Updates are all over the place but one thing useful to xorg updates are the various xorgproto fixups I've made on top of the previous effort to update to 1.20.1.

... which I just bumped to 1.20.2 :).

They might not be neatly gathered, but perhaps it's a useful resource that might help with some busywork.  If it's a pain to extract but you think they're useful I can rebase them out for easier review, just LMK.  Sorry this isn't really meant for anyone --even myself-- to use long-term but just how I've been staying on partially on top of things :).

Or maybe you have it all under control, which is good too ^_^.

Actually I might just merge this PR into my branch to help test your updates....

**Comment by ikervagyok** [comment]
@dtzWill i'll look into your `xorg-proto` stuff this weekend, until then maybe i'll learn some perl to rewrite parts of `generate-expr-from-tarballs.pl`:

1. add some special handling for `*-proto` and replace their sources and dependencies with the ones defined in `xorg-proto` (for that particular package)
2. maybe parallelize the `generate-expr-from-tarballs.pl` - it's a real pain to go through one package at a time or to cheat and use `git add -p`-magic to do (mass) updates

**Comment by ikervagyok** [comment]
@dtzWill i wont have time until probably the second week in november - if you want to go ahead and do something with this, feel free to do it

**Comment by ikervagyok** [comment]
@dtzWill the next few days i've got a bit of time now for these kind of refactors. is there any update i should know before trying again and waisting a lot of time doing redundant work?

**Comment by ikervagyok** [comment]
should be good to go, but not yet tested as my computer still compiles.

**Comment by FRidh** [comment]
This should target, and thus be rebased on, staging.

**Comment by MP2E** [comment]
Just tried to rebuild based off of this branch, and most things seem to work, but unfortunately libXp is not building on my desktop. It states that printproto can't be found despite xorgproto being passed in as a buildInput to libXp. Not sure what's going on here, but here's the log in case it helps

```
MP2E:~$ nix-env -f ~/nixpkgs -iA motif                                                                                                                                                                                                                                                                                       ~
installing 'motif-2.3.6'
these derivations will be built:
  /nix/store/gl5rdvp2bhxxyi6kni4lair570k8pm31-libXp-1.0.3.drv
  /nix/store/rhla4k1415dcpdksn47ccwjksfrvm55q-motif-2.3.6.drv
building '/nix/store/gl5rdvp2bhxxyi6kni4lair570k8pm31-libXp-1.0.3.drv'...
unpacking sources
unpacking source archive /nix/store/ia3vjdfys8f1prc21fdlvyq9ibqmq8d9-libXp-1.0.3.tar.bz2
source root is libXp-1.0.3
setting SOURCE_DATE_EPOCH to timestamp 1424556336 of file libXp-1.0.3/config.h.in
patching sources
configuring
fixing libtool script ./ltmain.sh
configure flags: --disable-static --disable-dependency-tracking --prefix=/nix/store/4h8nigwfzc8k3xbbjrgzki05ykqz466i-libXp-1.0.3 --bindir=/nix/store/4h8nigwfzc8k3xbbjrgzki05ykqz466i-libXp-1.0.3/bin --sbindir=/nix/store/4h8nigwfzc8k3xbbjrgzki05ykqz466i-libXp-1.0.3/sbin --includedir=/nix/store/mpq2qm5mwjz5cgm3lxhiwrf5s37xi5qi-libXp-1.0.3-dev/include --oldincludedir=/nix/store/mpq2qm5mwjz5cgm3lxhiwrf5s37xi5qi-libXp-1.0.3-dev/include --mandir=/nix/store/4h8nigwfzc8k3xbbjrgzki05ykqz466i-libXp-1.0.3/share/man --infodir=/nix/store/4h8nigwfzc8k3xbbjrgzki05ykqz466i-libXp-1.0.3/share/info --docdir=/nix/store/4h8nigwfzc8k3xbbjrgzki05ykqz466i-libXp-1.0.3/share/doc/libXp --libdir=/nix/store/4h8nigwfzc8k3xbbjrgzki05ykqz466i-libXp-1.0.3/lib --libexecdir=/nix/store/4h8nigwfzc8k3xbbjrgzki05ykqz466i-libXp-1.0.3/libexec --localedir=/nix/store/4h8nigwfzc8k3xbbjrgzki05ykqz466i-libXp-1.0.3/share/locale
checking for a BSD-compatible install... /nix/store/0q4i5ll9gxs6giq7kqkniww934j9j8dk-coreutils-8.30/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/0q4i5ll9gxs6giq7kqkniww934j9j8dk-coreutils-8.30/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... none
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /nix/store/zzzq8a9af192wfsi7lvf0mndpc8ykp4q-gnugrep-3.1/bin/grep
checking for egrep... /nix/store/zzzq8a9af192wfsi7lvf0mndpc8ykp4q-gnugrep-3.1/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether __clang__ is declared... no
checking whether __INTEL_COMPILER is declared... no
checking whether __SUNPRO_C is declared... no
checking for pkg-config... /nix/store/5830g1sp16dl5r2xmgj5pxjd6p0r3csk-pkg-config-0.29.2/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a sed that does not truncate output... /nix/store/4q0b6gz1yvb4bdzfcbyicz3vmlq05nxa-gnused-4.5/bin/sed
checking if gcc supports -Werror=unknown-warning-option... no
checking if gcc supports -Werror=unused-command-line-argument... no
checking if gcc supports -Wall... yes
checking if gcc supports -Wpointer-arith... yes
checking if gcc supports -Wmissing-declarations... yes
checking if gcc supports -Wformat=2... yes
checking if gcc supports -Wstrict-prototypes... yes
checking if gcc supports -Wmissing-prototypes... yes
checking if gcc supports -Wnested-externs... yes
checking if gcc supports -Wbad-function-cast... yes
checking if gcc supports -Wold-style-definition... yes
checking if gcc supports -Wdeclaration-after-statement... yes
checking if gcc supports -Wunused... yes
checking if gcc supports -Wuninitialized... yes
checking if gcc supports -Wshadow... yes
checking if gcc supports -Wmissing-noreturn... yes
checking if gcc supports -Wmissing-format-attribute... yes
checking if gcc supports -Wredundant-decls... yes
checking if gcc supports -Wlogical-op... yes
checking if gcc supports -Werror=implicit... yes
checking if gcc supports -Werror=nonnull... yes
checking if gcc supports -Werror=init-self... yes
checking if gcc supports -Werror=main... yes
checking if gcc supports -Werror=missing-braces... yes
checking if gcc supports -Werror=sequence-point... yes
checking if gcc supports -Werror=return-type... yes
checking if gcc supports -Werror=trigraphs... yes
checking if gcc supports -Werror=array-bounds... yes
checking if gcc supports -Werror=write-strings... yes
checking if gcc supports -Werror=address... yes
checking if gcc supports -Werror=int-to-pointer-cast... yes
checking if gcc supports -Werror=pointer-to-int-cast... yes
checking if gcc supports -pedantic... yes
checking if gcc supports -Werror... yes
checking if gcc supports -Werror=attributes... yes
Package xorg-macros was not found in the pkg-config search path.
Perhaps you should add the directory containing `xorg-macros.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xorg-macros' found
checking whether make supports nested variables... (cached) yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /nix/store/4q0b6gz1yvb4bdzfcbyicz3vmlq05nxa-gnused-4.5/bin/sed
checking for fgrep... /nix/store/zzzq8a9af192wfsi7lvf0mndpc8ykp4q-gnugrep-3.1/bin/grep -F
checking for ld used by gcc... ld
checking if the linker (ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... nm
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse nm output from gcc object... ok
checking for sysroot... no
./configure: line 12833: /usr/bin/file: No such file or directory
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for XPRINT... no
configure: error: Package requirements (x11 >= 1.6 xext xextproto xau printproto) were not met:

No package 'printproto' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XPRINT_CFLAGS
and XPRINT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
builder for '/nix/store/gl5rdvp2bhxxyi6kni4lair570k8pm31-libXp-1.0.3.drv' failed with exit code 1
cannot build derivation '/nix/store/rhla4k1415dcpdksn47ccwjksfrvm55q-motif-2.3.6.drv': 1 dependencies couldn't be built
error: build of '/nix/store/rhla4k1415dcpdksn47ccwjksfrvm55q-motif-2.3.6.drv' failed
```

**Comment by ikervagyok** [comment]
@FRidh at this point it would be cleaner, to restart from current staging - wdyt? any suggestions, what i should take into account when redoing all this?

@MP2E any other breakages?

**Comment by worldofpeace** [comment]
> at this point it would be cleaner, to restart from current staging - wdyt? any suggestions, what i should take into account when redoing all this?

They just meant to change the base branch to staging. These changes should be delivered there for sure since it's going to rebuild **lots** of things and it would halt dev on master.

**Comment by ikervagyok** [comment]
@MP2E amdgpu was the primary motivation for me - and then i realized that there were a lot of missing updates ;)

@worldofpeace i tried that, but found that it's an ugly patch like the rebase onto master a few days ago - i'd rather have these commits in a nice and tidy state in case we need to revert some. i'll do it tomorrow ;)

**Pull request closed without merging**
