### PR TITLE
[Backport release-22.11] GNOME updates

### PR DESCRIPTION
**Pull request by hmenke**
###### Description of changes

Backport of https://github.com/NixOS/nixpkgs/pull/214150 which fixes some GTK bugs

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hmenke** [comment]
Result of `nixpkgs-review pr 215722` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>aqemu</li>
    <li>elementary-planner</li>
    <li>mailnagWithPlugins</li>
    <li>pantheon.elementary-tasks</li>
    <li>xmonad_log_applet</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>ocamlPackages.ocaml-freestanding</li>
  </ul>
</details>
<details>
  <summary>229 packages built:</summary>
  <ul>
    <li>almanah</li>
    <li>alpine-make-vm-image</li>
    <li>apostrophe</li>
    <li>appvm</li>
    <li>blackbox-terminal</li>
    <li>bottles</li>
    <li>bubblemail</li>
    <li>caerbannog</li>
    <li>calls</li>
    <li>cambalache</li>
    <li>chatty</li>
    <li>cinnamon.nemo</li>
    <li>clementine</li>
    <li>cloud-init</li>
    <li>cloud-utils</li>
    <li>cobang</li>
    <li>colima</li>
    <li>cot (python310Packages.cot)</li>
    <li>cozy</li>
    <li>cpupower-gui</li>
    <li>denemo</li>
    <li>diffoscope</li>
    <li>dropbox-cli</li>
    <li>eiciel</li>
    <li>empathy</li>
    <li>endeavour</li>
    <li>epiphany</li>
    <li>evince</li>
    <li>evolution</li>
    <li>evolution-data-server</li>
    <li>evolution-data-server-gtk4</li>
    <li>evolution-ews</li>
    <li>evolutionWithPlugins</li>
    <li>folks</li>
    <li>fondo</li>
    <li>geany-with-vte</li>
    <li>geeqie</li>
    <li>germinal</li>
    <li>gfbgraph</li>
    <li>glom</li>
    <li>gnome-builder</li>
    <li>gnome-connections</li>
    <li>gnome-console</li>
    <li>gnome-feeds</li>
    <li>gnome-online-accounts</li>
    <li>gnome-photos</li>
    <li>gnome-podcasts</li>
    <li>gnome-recipes</li>
    <li>gnome-usage</li>
    <li>gnome.cheese</li>
    <li>gnome.dconf-editor</li>
    <li>gnome.eog</li>
    <li>gnome.file-roller</li>
    <li>gnome.geary</li>
    <li>gnome.gnome-applets</li>
    <li>gnome.gnome-boxes</li>
    <li>gnome.gnome-calendar</li>
    <li>gnome.gnome-color-manager</li>
    <li>gnome.gnome-contacts</li>
    <li>gnome.gnome-disk-utility</li>
    <li>gnome.gnome-flashback</li>
    <li>gnome.gnome-maps</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gnome-notes</li>
    <li>gnome.gnome-online-miners</li>
    <li>gnome.gnome-panel</li>
    <li>gnome.gnome-screenshot</li>
    <li>gnome.gnome-system-monitor</li>
    <li>gnome.gvfs</li>
    <li>libchamplain (gnome.libchamplain)</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.rygel</li>
    <li>gnome.seahorse</li>
    <li>gnome.simple-scan</li>
    <li>gnome.sushi</li>
    <li>gnome.totem</li>
    <li>gnome.vinagre</li>
    <li>gnome.yelp</li>
    <li>gnomeExtensions.ddterm</li>
    <li>gnomeExtensions.drop-down-terminal</li>
    <li>gnonograms</li>
    <li>gpx-viewer</li>
    <li>grilo-plugins</li>
    <li>gthumb</li>
    <li>gtkd</li>
    <li>gtkterm</li>
    <li>gtranslator</li>
    <li>guake</li>
    <li>guestfs-tools</li>
    <li>gupnp-tools</li>
    <li>gupnp_1_6</li>
    <li>gvfs</li>
    <li>kermit-terminal</li>
    <li>libchamplain_libsoup3</li>
    <li>libgdata</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libhandy</li>
    <li>libzapojit</li>
    <li>lifeograph</li>
    <li>lima</li>
    <li>linuxKernel.packages.linux_4_14.virtualbox</li>
    <li>linuxKernel.packages.linux_4_14_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_4_19.virtualbox</li>
    <li>linuxKernel.packages.linux_4_19_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_5_10.virtualbox</li>
    <li>linuxKernel.packages.linux_5_10_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_5_15.virtualbox</li>
    <li>linuxKernel.packages.linux_hardened.virtualbox (linuxKernel.packages.linux_5_15_hardened.virtualbox)</li>
    <li>linuxKernel.packages.linux_5_4.virtualbox</li>
    <li>linuxKernel.packages.linux_6_1.virtualbox</li>
    <li>linuxKernel.packages.linux_6_1_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_latest_libre.virtualbox</li>
    <li>linuxKernel.packages.linux_libre.virtualbox</li>
    <li>linuxKernel.packages.linux_lqx.virtualbox</li>
    <li>linuxKernel.packages.linux_xanmod.virtualbox</li>
    <li>linuxKernel.packages.linux_xanmod_latest.virtualbox (linuxKernel.packages.linux_xanmod_stable.virtualbox)</li>
    <li>linuxKernel.packages.linux_zen.virtualbox</li>
    <li>lollypop</li>
    <li>lxterminal</li>
    <li>markets</li>
    <li>mate.mate-terminal</li>
    <li>mate.mate-user-guide</li>
    <li>minder</li>
    <li>mlterm</li>
    <li>monitor</li>
    <li>nautilus-open-any-terminal</li>
    <li>nemiver</li>
    <li>numberstation</li>
    <li>o</li>
    <li>onboard</li>
    <li>open-watcom-bin</li>
    <li>open-watcom-bin-unwrapped</li>
    <li>out-of-tree</li>
    <li>pantheon-tweaks</li>
    <li>pantheon.appcenter</li>
    <li>pantheon.elementary-calendar</li>
    <li>pantheon.elementary-camera</li>
    <li>pantheon.elementary-capnet-assist</li>
    <li>pantheon.elementary-code</li>
    <li>pantheon.elementary-feedback</li>
    <li>pantheon.elementary-files</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-mail</li>
    <li>pantheon.elementary-notifications</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-photos</li>
    <li>pantheon.elementary-screenshot</li>
    <li>pantheon.elementary-shortcut-overlay</li>
    <li>pantheon.elementary-terminal</li>
    <li>pantheon.elementary-videos</li>
    <li>pantheon.epiphany</li>
    <li>pantheon.file-roller-contract</li>
    <li>pantheon.switchboard</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-plug-applications</li>
    <li>pantheon.switchboard-plug-bluetooth</li>
    <li>pantheon.switchboard-plug-datetime</li>
    <li>pantheon.switchboard-plug-display</li>
    <li>pantheon.switchboard-plug-keyboard</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-notifications</li>
    <li>pantheon.switchboard-plug-onlineaccounts</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-printers</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-plug-sharing</li>
    <li>pantheon.switchboard-plug-sound</li>
    <li>pantheon.switchboard-plug-wacom</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.xdg-desktop-portal-pantheon</li>
    <li>paperwork</li>
    <li>portfolio-filemanager</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.openpaperwork-gtk</li>
    <li>python310Packages.paperwork-backend</li>
    <li>python310Packages.paperwork-shell</li>
    <li>python39Packages.cot</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.openpaperwork-gtk</li>
    <li>python39Packages.paperwork-backend</li>
    <li>python39Packages.paperwork-shell</li>
    <li>qemu</li>
    <li>qemu-utils</li>
    <li>qemu_full</li>
    <li>qemu_kvm</li>
    <li>qtemu</li>
    <li>quickemu</li>
    <li>rabbitvcs</li>
    <li>remmina</li>
    <li>roxterm</li>
    <li>sakura</li>
    <li>shotwell</li>
    <li>solo5</li>
    <li>spot</li>
    <li>stupidterm</li>
    <li>swaynotificationcenter</li>
    <li>swaysettings</li>
    <li>taxi</li>
    <li>terminator</li>
    <li>termite (termite-unwrapped)</li>
    <li>termonad</li>
    <li>thiefmd</li>
    <li>tilda</li>
    <li>tilix</li>
    <li>timeshift</li>
    <li>timeshift-minimal</li>
    <li>timeshift-unwrapped</li>
    <li>tootle</li>
    <li>tracker-miners</li>
    <li>tym</li>
    <li>vagrant</li>
    <li>vala-language-server</li>
    <li>virt-manager</li>
    <li>virt-viewer</li>
    <li>virtualbox</li>
    <li>virtualboxHardened</li>
    <li>virtualboxHeadless</li>
    <li>virtualboxWithExtpack</li>
    <li>vte</li>
    <li>vte-gtk4</li>
    <li>wike</li>
    <li>xfce.xfce4-terminal</li>
    <li>zpool-auto-expand-partitions</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
gnome-builder 43.5 has some [regression](https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/1980), I personally prefer 43.4 or [43.6](https://github.com/NixOS/nixpkgs/pull/215052).

**Comment by hmenke** [comment]
@bobby285271 Okay, dropped.

**Comment by bobby285271** [comment]
> @ofborg test gnome

Looks like 22.11 is missing #206291

```
Cannot nix-instantiate `nixosTests.gnome' because:
error: Function called without required argument "makeHardcodeGsettingsPatch" at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/ofborg-evaluator-3/pkgs/tools/networking/networkmanager/libnma/default.nix:27
```

**Comment by bobby285271** [comment]
The diff should be fine, rebuilt my laptop with the branch.



Please fixup the commits when you think this is ready. You can test this branch [with the steps here](https://discourse.nixos.org/t/help-testing-gnome-pantheon-cinnamon-co-needed/21935).

**Comment by Lyndeno** [comment]
Gnome console was updated to 43 in the referenced PR but not backported. Is it something that can be backported?

**Comment by hmenke** [comment]
@Lyndeno According to the GNOME maintainer, no. https://view.matrix.org/room/!XQQVyIbcAcHFvzmcTl:nixos.org/$VDjfSI3FDbz7S0LdGQos_P3sCKmEOSbRs5or5QM8VMg

**Pull request merged**
