### PR TITLE
Various VSCode / VSCodium extension themes

### PR DESCRIPTION
**Pull request by D3vil0p3r**
## Description of changes

vscode-extensions.carrie999.cyberpunk-2020: init at 0.1.4
vscode-extensions.dhedgecock.radical-vscode: init at 3.3.1
vscode-extensions.nur.just-black: init at 3.1.1
vscode-extensions.silofy.hackthebox: init at 0.2.9
vscode-extensions.thorerik.hacker-theme: init at 3.0.1

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Janik-Haag** [comment]
I don't use vscode and am thus quite unfamiliar with the packaging. so I won't review this.

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 280941` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>vscode-extensions.carrie999.cyberpunk-2020</li>
    <li>vscode-extensions.dhedgecock.radical-vscode</li>
    <li>vscode-extensions.nur.just-black</li>
    <li>vscode-extensions.silofy.hackthebox</li>
    <li>vscode-extensions.thorerik.hacker-theme</li>
  </ul>
</details>

**Comment by h7x4** [comment]
I've gone through and verified all the licenses against upstream.

Could you add yourself as maintainer for the packages?

**Comment by D3vil0p3r** [comment]
> I've gone through and verified all the licenses against upstream.
> 
> Could you add yourself as maintainer for the packages?

@h7x4 done.

**Comment by D3vil0p3r** [comment]
@h7x4 fixed.

**Comment by h7x4** [comment]
Would you mind moving the maintainership changes to each respective commit? Right now, they are all bundled within 1b4f26bc4e0af3c5b4475cca8f0ff67a14bcc1ac

**Comment by D3vil0p3r** [comment]
> Would you mind moving the maintainership changes to each respective commit? Right now, they are all bundled

What if I close this PR and I open a new one? It should be easier for me instead of removing all commits and recreating all of them.

**Comment by drupol** [comment]
> Would you mind moving the maintainership changes to each respective commit? Right now, they are all bundled within [1b4f26b](https://github.com/NixOS/nixpkgs/commit/1b4f26bc4e0af3c5b4475cca8f0ff67a14bcc1ac)

Which maintainership changes? All the extensions that @D3vil0p3r is trying to introduce are new, nothing else is being modified.

**Comment by drupol** [comment]
> > Would you mind moving the maintainership changes to each respective commit? Right now, they are all bundled
> 
> What if I close this PR and I open a new one? It should be easier for me instead of removing all commits and recreating all of them.

There's no need to create a new PR, just do `git rebase -i 1b4f26bc4e0af3c5b4475cca8f0ff67a14bcc1ac^ --mixed`, redo your commits properly, and then once its done, just do `git push -f patch-8`

**Comment by h7x4** [comment]
> Which maintainership changes? All the extensions that @D3vil0p3r is trying to introduce are new, nothing else is being modified.

Sorry, the wording is a bit inaccurate. I meant the parts of the diff containing `maintainers = with maintainers; [ d3vil0per ]`

**Comment by drupol** [comment]
> > Which maintainership changes? All the extensions that @D3vil0p3r is trying to introduce are new, nothing else is being modified.
> 
> Sorry, the wording is a bit inaccurate. I meant the parts of the diff containing `maintainers = with maintainers; [ d3vil0per ]`

I still don't get it. That means that this PR is supposed to contain 10 commits? 5 for adding the 5 new extensions, and 5 for changing the maintainership ?!

**Comment by lucasew** [comment]
> > Would you mind moving the maintainership changes to each respective commit? Right now, they are all bundled
> 
> What if I close this PR and I open a new one? It should be easier for me instead of removing all commits and recreating all of them.

`git reset --soft` to the initial commit then `git add --interactive` to stage hunks in the file for each commit.

**Comment by drupol** [comment]
> `git reset --soft` to the initial commit then `git add --interactive` to stage hunks in the file for each commit.

That's precisely what I explained in https://github.com/NixOS/nixpkgs/pull/280941#issuecomment-1901090432

**Comment by D3vil0p3r** [comment]
> > > Which maintainership changes? All the extensions that @D3vil0p3r is trying to introduce are new, nothing else is being modified.
> > 
> > 
> > Sorry, the wording is a bit inaccurate. I meant the parts of the diff containing `maintainers = with maintainers; [ d3vil0per ]`
> 
> I still don't get it. That means that this PR is supposed to contain 10 commits? 5 for adding the 5 new extensions, and 5 for changing the maintainership ?!

No. In practice before @h7x4 suggestions, I didn't insert `maintainers` attribute. So he suggested to add them for each one of the VSCode theme code and these new changes should be "put" each one with the related vscode theme commit. At the end we will have 5 commits.

**Comment by drupol** [comment]
OK I got it.

So, to summarize, one commit should be atomic and contain only 1 extension insertion, including the maintainership attribute. And you need to do that 5 times since you're adding 5 new extensions.

**Comment by D3vil0p3r** [comment]
> OK I got it.
> 
> So, to summarize, one commit should be atomic and contain only 1 extension insertion, including the maintainership attribute. And you need to do that 5 times since you're adding 5 new extensions.

Exactly

**Comment by h7x4** [comment]
I think the easiest way I know of to do this is to create five new commits, one for each maintainer line, and then do `git rebase -i HEAD~10`, where you move each maintainer line commit as a `fixup` below the commit they belong to.

**Comment by drupol** [comment]
> I think the easiest way I know of to do this is to create five new commits, one for each maintainer line, and then do `git rebase -i HEAD~10`, where you move each maintainer line commit as a `fixup` below the commit they belong to. But there might be better ways of doing it.
> 
> I don't think it warrants a new PR though, but it's probably not that big of a deal.

Indeed, even better.

**Comment by D3vil0p3r** [comment]
Since I already squashed the further 5 commits related to the `maintainers` attribute, what I did is the following:
```
git rebase -i HEAD~5

Change "pick" to "edit" for each one of the 5 commits
Edit one by one default.nix and append the missing maintainers attribute to the related vscode theme
git commit --all --amend --no-edit
git rebase --continue (to edit the code for the next commit I tagged from "pick" to "edit")
```
I found this method very easy to use. Now commits should be fixed.

**Review by drupol — APPROVED** [review]

**Review by h7x4 — APPROVED** [review]

**Pull request merged**
