### PR TITLE
emacs: Add feature flags

### PR DESCRIPTION
**Pull request by KAction**

### CODE REVIEW

**Review by jtbx — APPROVED** [review]

**Comment by adisbladis** [comment]
Could you add the `--with-foo` compiler flags explicitly?

**Comment by KAction** [comment]
> Could you add the `--with-foo` compiler flags explicitly?

Sure, but that will be staging change then.

**Review by AndersonTorres — CHANGES_REQUESTED** [review]
Being pedantic, change the title to the less generic 

```
emacs: add withDbus and withSelinux flags
```

**Comment by AndersonTorres** [comment]
> Stdenv depenends on emacs?!

Maybe staging is buggy again.

**Comment by KAction** [comment]
> Being pedantic, change the title to the less generic
> 
> ```
> emacs: add withDbus and withSelinux flags
> ```

Done

**Review by AndersonTorres — APPROVED** [review]

**Comment by AndersonTorres** [comment]
P.S.: can this PR be merged right before mine, that adds mailutils? Merging things is hard, merging thing on staging is a bit harder.

https://github.com/NixOS/nixpkgs/pull/291209

**Comment by fabianhjr** [comment]
Hi @AndersonTorres, currently only focusing on merging already reviewed PRs; hopefully will be able to review + merge 291209 during the week.

**Pull request merged**
