### PR TITLE
Draft: discourse 3.1.0 backport to nixos-23.05 

### PR DESCRIPTION
**Pull request by pdg137**
I'm trying to apply https://github.com/NixOS/nixpkgs/pull/250735 or https://github.com/NixOS/nixpkgs/pull/257294 to nixos-23.05 and keep running into this "Failed to open TCP connection to github.com:443" error when I run the tests:

```
_64-linux/3.2.0/sass-embedded-1.64.1/gem_make.out
current directory: /nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/ext/sass
/nix/store/vh5zmcaji4pihr08sqb6z4zznshl2l3g-ruby-3.2.2/bin/ruby -rrubygems /nix/store/kd8ar4rzh880afhfc1zqd82g4iqxc9jd-ruby3.2.2-rake-13.0.6/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=/nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/extensions/x86_64-linux/3.2.0/sass-embedded-1.64.1 RUBYLIBDIR\=/nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/extensions/x86_64-linux/3.2.0/sass-embedded-1.64.1
gem install --force --install-dir /nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/ext/sass/ruby --no-document --ignore-dependencies --platform x86_64-linux-gnu --version 1.64.1 sass-embedded
fetch https://github.com/sass/dart-sass/releases/download/1.64.1/dart-sass-1.64.1-linux-x64.tar.gz
rake aborted!
SocketError: Failed to open TCP connection to github.com:443 (getaddrinfo: Temporary failure in name resolution)
/nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/ext/sass/Rakefile:176:in `public_send'
/nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/ext/sass/Rakefile:176:in `fetch'
/nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/ext/sass/Rakefile:27:in `rescue in block in <top (required)>'
/nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/ext/sass/Rakefile:21:in `block in <top (required)>'
/nix/store/kd8ar4rzh880afhfc1zqd82g4iqxc9jd-ruby3.2.2-rake-13.0.6/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<main>'

Caused by:

/nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/ext/sass/Rakefile:207:in `gem_install'
/nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/ext/sass/Rakefile:23:in `block in <top (required)>'
/nix/store/kd8ar4rzh880afhfc1zqd82g4iqxc9jd-ruby3.2.2-rake-13.0.6/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<main>'
Tasks: TOP => default => install => cli.rb => dart-sass
(See full trace by running task with --trace)
rm -rf /nix/store/am8avzjcmcd871rzmz5z44f86vvnn9c1-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/ext/sass/ruby

rake failed, exit code 1
```

I think that's related to removing the sass-embedded patch in https://github.com/NixOS/nixpkgs/pull/250735/commits/8e8a6ed409ea6333e7f408de89377fc98e930c96. But I don't understand it or know what to do to get it to work.  @TheNeikos @MTRNord do you have any suggestions?

### CODE REVIEW

**Comment by TheNeikos** [comment]
I think https://github.com/NixOS/nixpkgs/pull/240000 also needs to be applied?

**Comment by pdg137** [comment]
Thanks @TheNeikos, I applied those commits and I think that gets me further.

However now the tests freeze on the "building discourse-assets-3.1.0" step like this:
```
$ nix build -v -f. nixosTests.discourse
...
building '/nix/store/yny7adpfvnhv9j5a5f7cfap7qasvx6g0-discourse-assets-3.1.0.drv'...
[1/252/277 built, 260 copied (960.5/961.9 MiB), 259.5 MiB DL] building discourse-assets-3.1.0 (buildPhase):     from /nix/store/x2v29wk5sdpsrn0vcna09rq30v0kijsz-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/lib/sass/embedded/dispatcher.rb:18:in `block in initialize'
```

Is this another obvious problem, or is there a way to get more debugging output from these commands?

**Comment by TheNeikos** [comment]
> Thanks @TheNeikos, I applied those commits and I think that gets me further.
> 
> However now the tests freeze on the "building discourse-assets-3.1.0" step like this:
> 
> ```
> $ nix build -v -f. nixosTests.discourse
> ...
> building '/nix/store/yny7adpfvnhv9j5a5f7cfap7qasvx6g0-discourse-assets-3.1.0.drv'...
> [1/252/277 built, 260 copied (960.5/961.9 MiB), 259.5 MiB DL] building discourse-assets-3.1.0 (buildPhase):     from /nix/store/x2v29wk5sdpsrn0vcna09rq30v0kijsz-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/lib/sass/embedded/dispatcher.rb:18:in `block in initialize'
> ```
> 
> Is this another obvious problem, or is there a way to get more debugging output from these commands?

You could try running with -L, that should output the log as it’s coming in. And otherwise, you’d have to read what the code does at the position it reports…

**Comment by pdg137** [comment]
The -L gives more info, still not sure what it means:

```
$ nix build -L -v -f. nixosTests.discourse
...
discourse-assets> app/assets/javascripts/node_modules/js-yaml/bin/js-yaml.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/8w46c2hf7hclc5p3adyi85bm67gpikqf-nodejs-18.17.1/bin/node"
discourse-assets> Waiting for Redis and PostgreSQL to be ready..
discourse-assets> psql: error: connection to server on socket "/build/.s.PGSQL.5432" failed: No such file or directory
discourse-assets>       Is the server running locally and accepting connections on that socket?
discourse-assets> 2023-10-22 18:07:42.194 UTC [634] LOG:  starting PostgreSQL 14.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 12.2.0, 64-bit
discourse-assets> 2023-10-22 18:07:42.195 UTC [634] LOG:  listening on IPv4 address "127.0.0.1", port 5432
discourse-assets> 2023-10-22 18:07:42.200 UTC [634] LOG:  listening on Unix socket "/build/.s.PGSQL.5432"
discourse-assets> 2023-10-22 18:07:42.205 UTC [638] LOG:  database system was shut down at 2023-10-22 18:07:42 UTC
discourse-assets> 2023-10-22 18:07:42.210 UTC [634] LOG:  database system is ready to accept connections
discourse-assets> CREATE ROLE
discourse-assets> CREATE DATABASE
discourse-assets> CREATE EXTENSION
discourse-assets> CREATE EXTENSION
discourse-assets> fatal: not a git repository (or any of the parent directories): .git
discourse-assets> > Seeding theme and color schemes
discourse-assets> #<Thread:0x00007fffea44b000 /nix/store/x2v29wk5sdpsrn0vcna09rq30v0kijsz-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/lib/sass/embedded/dispatcher.rb:17 run> terminated with exception (report_on_exception is true):
discourse-assets> /nix/store/x2v29wk5sdpsrn0vcna09rq30v0kijsz-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/lib/sass/embedded/dispatcher.rb:79:in `receive_proto': undefined method `receive_proto' for nil:NilClass (NoMethodError)
discourse-assets>           @mutex.synchronize { @observers[id] }.receive_proto(proto)
discourse-assets>                                                ^^^^^^^^^^^^^^
discourse-assets>       from /nix/store/x2v29wk5sdpsrn0vcna09rq30v0kijsz-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/lib/sass/embedded/dispatcher.rb:19:in `block (2 levels) in initialize'
discourse-assets>       from /nix/store/x2v29wk5sdpsrn0vcna09rq30v0kijsz-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/lib/sass/embedded/dispatcher.rb:18:in `loop'
discourse-assets>       from /nix/store/x2v29wk5sdpsrn0vcna09rq30v0kijsz-ruby3.2.2-sass-embedded-1.64.1/lib/ruby/gems/3.2.0/gems/sass-embedded-1.64.1/lib/sass/embedded/dispatcher.rb:18:in `block in initialize'
[1/0/25 built] building discourse-assets-3.1.0 (buildPhase)
```

**Comment by pdg137** [comment]
I'm giving up on this for now but will leave this up in case anyone else wants to try to pick it up from here.

**Comment by wegank** [comment]
Closing since NixOS 23.05 is EOL.

**Pull request closed without merging**
