### PR TITLE
rPackages: sparklyr environment variables

### PR DESCRIPTION
**Pull request by nviets**
This PR sets the default SPARK_HOME and JAVA_HOME for R's sparklyr package using a patch for .onload. Preset value take precedence. SPARK_HOME points to python3Packages.pyspark rather than pkgs.spark because the former is actively maintained.

Is there a way to automatically infer and set the python version in this line?
```
${pkgs.python3Packages.pyspark}/lib/python3.10/site-packages/pyspark
```

@alexvorobiev

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin

### CODE REVIEW

**Comment by jbedo** [comment]
Yes, you can get the prefix from the python interpreter:
```
${pkgs.python3Packages.pyspark}/lib/${pkgs.python3Packages.python.libPrefix}/site-packages/pyspark
```

**Comment by nviets** [comment]
Thanks @jbedo. Done.

**Comment by nviets** [comment]
Result of `nixpkgs-review pr 219439` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Review by jbedo — CHANGES_REQUESTED** [review]
Otherwise LGTM, tested fine on my x86_64-linux machine.

**Pull request merged**
