### PR TITLE
RFC: treewide: use stdenv's {configure,c?make}Flags instead of hooks

### PR DESCRIPTION
**Pull request by stv0g**
## Description of changes

There is a large inconsistency on how configure, make and cmake flags are set when they need to refer to environment variables such as `$out`.

The stdenv shorthands like `configureFlags` are not directly substituting environment variables. Hence usage of `$` must be escaped to `$$` or `${}`. During this refactor a couple of instances have been found where this escaping was not done. This commit also fixes them.

I stumbled over this while working on #299626

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by stv0g** [comment]
This is my first larger PR to nixpkgs. Is this the correct approach?

There are also likely more instances where the flags have been set wrong?
Maybe we can use some Nix-magix to query for instances where `$out` has been used without proper escaping?

**Comment by tpwrules** [comment]
I think `$$out` should generally instead be `${placeholder "out"}`.

**Comment by wegank** [comment]
I also found `$(out)` (and the bulletproof `${placeholder "out"}`) more often than `$$out`.

**Comment by stv0g** [comment]
Thanks :)

> I also found $(out)

Isnt this only valid in `makeFlags` as make expands them internally?

I am wondering which case would be considered best practice here?

**Comment by stv0g** [comment]
I gave this another iteration and harmonized all usages of $$out, $(out) in `configureFlags` with the `placeholder` function.

I also moved all adjustments of `configureFlags` made in `preConfigure` to the top-level `configureFlags` attribute itself.

Grepping through nixpkgs with `\$\((out|bin|dev|lib|doc)\)` also reveals around 1400 instances where we use Make-style variable substitution mostly in `{make,build,install}Flags`.

I would like to get some more opinions, on whether we also like to harmonize these cases with `placeholder`. I am all for it. I would just like to some more feedback consensus before making the changes..

**Pull request closed without merging**
