### PR TITLE
gnome3.20: update all to latest

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change

I noticed some packages in the 3.20 series were actually 3.18 versions (gnome-bluetooth, gnome-screenshot). I ran the maintainer script to regenerate and update all 3.20 packages.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Letting Travis do some build-testing. Don't merge yet.

### CODE REVIEW

**Comment by bjornfor** [comment]
Cc @lethalman

**Comment by DamienCassou** [comment]
@bjornfor thanks. Could you please rebase on top of master? 2 recent merged PRs already updated many packages: #17056 and #17030. Moreover, please try to build the updated packages. I know I refrained from upgrading a package which required an updated dependency and other packages were incompatible with this update.

**Comment by bjornfor** [comment]
@DamienCassou: Yes, I'll rebase. I forgot about that other PR (I thought it was already merged).

**Comment by bjornfor** [comment]
After rebasing there was only one minor version bump and a lot of churn. I guess the last changes to src.nix files have been done by hand, although there is a maintainer script that generates those files (it creates minor differences).

My motivation for this PR was mostly getting the two 3.18 packages up to 3.20 (which the above PRs did). So closing this one.

**Comment by DamienCassou** [comment]
Bjørn Forsman <notifications@github.com> writes:

> After rebasing there was only one minor version bump and a lot of churn. I guess the last changes to src.nix files have been done by hand, although there is a maintainer script that generates those files (it creates minor differences).

yes, I updated the nix files manually. That was probably a bad idea but
this will be fixed automatically when we launch the update script again.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by bjornfor** [comment]
@DamienCassou: FYI, there were manual changes in the files *before* rebasing on top of your changes too.

**Pull request closed without merging**
