### PR TITLE
fcitx5: bump packages to fix positioning issue on wayland

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change
Bump fcitx5 packages. Also fix the issue that input method window is displayed on wrong position far from input place, on wayland.
Tested to work fine with `fcitx5-rime` in Qt programs on plasma-wayland (#100057).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 116748` at edd4d885 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/74dd050ab67a13036aedf9c420c1b6b9">fcitx5</a></li></li>
    <li><a href="https://gist.github.com/3c753c946c471a252205b7c7421a8e92">fcitx5-chinese-addons</a></li></li>
    <li><a href="https://gist.github.com/26a82572be4d2e0ed4b41711cc30b2d5">fcitx5-configtool</a></li></li>
    <li><a href="https://gist.github.com/d0d375fadc38c0c3104c98be1aa132ef">fcitx5-gtk</a></li></li>
    <li><a href="https://gist.github.com/5f9a4941cbfa7e5b61547ff94d7c0fc0">fcitx5-lua</a></li></li>
    <li><a href="https://gist.github.com/2be9d0a283c64c966cbbaf9a0e40b1f1">fcitx5-mozc</a></li></li>
    <li><a href="https://gist.github.com/5275000bdca3fd4f33af1a4491860357">fcitx5-rime</a></li></li>
    <li><a href="https://gist.github.com/105f4d18f15fd58857c9c4d96a77faaa">fcitx5-table-extra</a></li></li>
    <li><a href="https://gist.github.com/1d5e75b7411c423557969d748c00e4b3">fcitx5-table-other</a></li></li>
    <li>fcitx5-with-addons</li>
    <li><a href="https://gist.github.com/522816784dde75298922281a72d5fee0">libime</a></li></li>
    <li><a href="https://gist.github.com/a3df05558cc6113e31718af2f9e79b9f">libsForQt5.fcitx5-qt</a></li> (libsForQt515.fcitx5-qt ,plasma5Packages.fcitx5-qt)</li>
    <li><a href="https://gist.github.com/bf3f066033bdd241ba3a0f01edb7f83c">libsForQt512.fcitx5-qt</a></li></li>
    <li><a href="https://gist.github.com/adeaa2d575650e361d38791e1cf677e2">libsForQt514.fcitx5-qt</a></li></li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 116748` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
14 packages built:
</summary>
<ul>
<li>fcitx5</li>
<li>fcitx5-chinese-addons</li>
<li>fcitx5-configtool</li>
<li>fcitx5-gtk</li>
<li>fcitx5-lua</li>
<li>fcitx5-mozc</li>
<li>fcitx5-rime</li>
<li>fcitx5-table-extra</li>
<li>fcitx5-table-other</li>
<li>fcitx5-with-addons</li>
<li>libime</li>
<li>libsForQt5.fcitx5-qt (libsForQt515.fcitx5-qt ,plasma5Packages.fcitx5-qt)</li>
<li>libsForQt512.fcitx5-qt</li>
<li>libsForQt514.fcitx5-qt</li>
</ul>
</details>

**Comment by poscat0x04** [comment]
https://github.com/NixOS/nixpkgs/pull/115386 dupe?

**Comment by oxalica** [comment]
Close as duplicated

**Pull request closed without merging**
