### PR TITLE
cpan2nix updates

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

update perlPackages

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build hydra

**Comment by volth** [comment]
@GrahamcOfBorg build perlPackages.Mojolicious

**Comment by volth** [comment]
@GrahamcOfBorg build perlPackages.LWPProtocolHttps

**Comment by volth** [comment]
@GrahamcOfBorg build hydra

**Comment by volth** [comment]
@GrahamcOfBorg build perlPackages.CatalystRuntime

**Comment by volth** [comment]
@GrahamcOfBorg build perlPackages.CatalystRuntime

**Comment by volth** [comment]
@GrahamcOfBorg build hydra

**Comment by Mic92** [comment]
@volth ready to roll?

**Comment by volth** [comment]
> @volth ready to roll?

#Mic92 It is still building locally.
I think it is ok to merge if you are in hurry.
If the rebuild  reveals broken derivations, I'll create a fix PR for them later today

**Comment by Mic92** [comment]
@volth no rush, if you still want to test.

**Comment by volth** [comment]
built successfully on ```x86_64-linux```, lets' merge

**Pull request merged**
