### PR TITLE
redmine: 4.2.9 -> 4.2.10

### PR DESCRIPTION
**Pull request by felixsinger**
###### Description of changes

The update contains fixes for security issues.

Changelog: https://www.redmine.org/projects/redmine/wiki/Changelog_4_2#4210-2023-03-05

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by obadz — APPROVED** [review]

**Comment by Atemu** [comment]
It builds fine on aarch64-linux and the changelog only mentions minor changes.

How can I test this?

**Comment by felixsinger** [comment]
> It builds fine on aarch64-linux and the changelog only mentions minor changes.

From the changelog:

```
[Security]
* Defect #38063: Avoid double-render error with ApplicationController#find_optional_project
* Defect #38070: Role#permission_tracker? and related does not consider whether the base permission is (still) set
* Defect #38133: Update Nokogiri to fix several security issues
* Defect #38297: Insufficient permission checks when adding attachments to issues
```

> How can I test this?

`service.redmine.enable = true` and configure database settings. There are also tests which set up a Redmine host and test basic functionality.

**Review by Atemu — APPROVED** [review]
Result of `nixpkgs-review pr 220326` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>redmine</li>
  </ul>
</details>

**Comment by Atemu** [comment]
Please run the tests next time and tick the relevant box, that makes things easier.

**Comment by felixsinger** [comment]
Ah, yes forgot to tick the box. Thanks!

**Pull request merged**
