### PR TITLE
ncdu_2: 2.2.1 -> 2.2.2

### PR DESCRIPTION
**Pull request by rodrgz**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by AndersonTorres — COMMENTED** [review]
ncdu_2? Do we package ncdu_1?

**Comment by rodrgz** [comment]
> ncdu_2? Do we package ncdu_1?

yes.

ncdu is an alias for ncdu_2: 
https://github.com/NixOS/nixpkgs/blob/fcc4a1cbfb62874d2d79745781dfeb4227bfd3b8/pkgs/top-level/aliases.nix#L1010

ncdu_1 exists:
https://github.com/NixOS/nixpkgs/blob/216fbe09999764469066b1ccf05dcff45cf078e7/pkgs/tools/misc/ncdu/1.nix#L5

**Comment by AndersonTorres** [comment]
Is there any reason for this? It is a bit strange...

**Comment by rodrgz** [comment]
> Is there any reason for this? It is a bit strange...

ncdu_1 is the C version that is still being maintained. More info: https://dev.yorhel.nl/ncdu

**Comment by zowoq** [comment]
> ncdu is an alias for ncdu_2:

`ncdu_2` is an alias for `ncdu`.

CI didn't build this, the commit should have been `ncdu: 2.2.1 -> 2.2.2`,

**Pull request merged**
