### PR TITLE
netdata: 1.46.1 -> 1.47.0

### PR DESCRIPTION
**Pull request by rhoriguchi**
## Description of changes

- Netdata adds `lm_sensors` as soft dependency netdata/netdata#18067
- `logs-management` was remove netdata/netdata#18186

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rhoriguchi** [comment]
Hi, any ideas why this does not build @pedorich-n @RaitoBezarius

**Comment by pedorich-n** [comment]
Thank you for the PR! I've been meaning to have a look at this, but haven't had a chance yet.

I don't fully understand why it's failing, but I think I managed to "narrow it down" to go modules. When I add the following to the `cmakeFlags` the build succeeds.
```nix
(lib.cmakeBool "ENABLE_PLUGIN_GO" false)
```

I don't know if it's normal for Go builds in Nix, but I see a lot of `connection refused` for Go modules in the logs. Is it possible that `Cmake` doesn't use the pre-built Go modules and tries to download them during the build and that's why it fails?

Examples of such logs:
```
cmd/godplugin/main.go:22:2: github.com/jessevdk/go-flags@v1.6.1: Get "https://proxy.golang.org/github.com/jessevdk/go-flags/@v/v1.6.1.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:34113->[::1]:53: read: connection refused
logger/handler.go:10:2: github.com/lmittmann/tint@v1.0.5: Get "https://proxy.golang.org/github.com/lmittmann/tint/@v/v1.0.5.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:53330->[::1]:53: read: connection refused
logger/default.go:9:2: github.com/mattn/go-isatty@v0.0.20: Get "https://proxy.golang.org/github.com/mattn/go-isatty/@v/v0.0.20.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:52453->[::1]:53: read: connection refused
plugin/go.d/agent/confgroup/config.go:14:2: github.com/ilyam8/hashstructure@v1.1.0: Get "https://proxy.golang.org/github.com/ilyam8/hashstructure/@v/v1.1.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:46704->[::1]:53: read: connection refused
...
```

**Comment by RaitoBezarius** [comment]
Apologies I moved away from netdata, so I don't really maintain it anymore.

**Comment by rhoriguchi** [comment]
What I could deduce is that the go closure has the required modules. I think the issue is that it's not using it as intended.

```console
> nix-build -A netdata.netdata-go-modules 
Finished at 19:24:03 after 0s
/nix/store/xiapjp91jwhv5kr776pqwsnn0fhpqsw7-netdata-go-plugins-1.47.0-go-modules

> find /nix/store/xiapjp91jwhv5kr776pqwsnn0fhpqsw7-netdata-go-plugins-1.47.0-go-modules -name 'go-flags'
/nix/store/xiapjp91jwhv5kr776pqwsnn0fhpqsw7-netdata-go-plugins-1.47.0-go-modules/github.com/jessevdk/go-flags
```

**Comment by Izorkin** [comment]
Error build with enable log management:
```
rror: builder for '/nix/store/sn2qkrkn89d8s1vsq38jimyjjcs66gbs-netdata-1.47.0.drv' failed with exit code 1;
       last 10 log lines:
       > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/registry-hello.html
       > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/switch.html
       > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/ilove.html
       > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/old/index.html
       > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/static/img/netdata-logomark.svg
       > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/css/morris-0.5.1.css
       > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/css/c3-0.4.18.min.css
       > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/.well-known/dnt/cookies
       > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/v0/index.html
       > mv: cannot stat '/nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/libexec/netdata/plugins.d/logs-management.plugin': No such file or directory
       For full logs, run 'nix log /nix/store/sn2qkrkn89d8s1vsq38jimyjjcs66gbs-netdata-1.47.0.drv'.

```

**Comment by rhoriguchi** [comment]
> Error build with enable log management:
> 
> ```
> rror: builder for '/nix/store/sn2qkrkn89d8s1vsq38jimyjjcs66gbs-netdata-1.47.0.drv' failed with exit code 1;
>        last 10 log lines:
>        > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/registry-hello.html
>        > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/switch.html
>        > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/ilove.html
>        > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/old/index.html
>        > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/static/img/netdata-logomark.svg
>        > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/css/morris-0.5.1.css
>        > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/css/c3-0.4.18.min.css
>        > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/.well-known/dnt/cookies
>        > -- Installing: /nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/share/netdata/web/v0/index.html
>        > mv: cannot stat '/nix/store/q37kqdfsyi5wxdc5nq0860wn376fqdb9-netdata-1.47.0/libexec/netdata/plugins.d/logs-management.plugin': No such file or directory
>        For full logs, run 'nix log /nix/store/sn2qkrkn89d8s1vsq38jimyjjcs66gbs-netdata-1.47.0.drv'.
> ```

I've missed that it was removed netdata/netdata#18186

**Review by Izorkin — APPROVED** [review]

**Comment by pedorich-n** [comment]
`changefinder` was also dropped: https://github.com/netdata/netdata/pull/18370
I believe it was added only because of netdata, and used only here: https://github.com/NixOS/nixpkgs/blob/3736dd89d4c831157739051315be405e87ed9249/nixos/modules/services/monitoring/netdata.nix#L221
But I don't know what is the process of removing something from nixpkgs. Probably it's better to do in a separate PR.

**Review by pedorich-n — APPROVED** [review]

**Pull request merged**
