### PR TITLE
python3Packages.crytic-compile: 0.1.9 -> 0.1.12

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.1.12.

Change log: https://github.com/crytic/crytic-compile/releases/tag/0.1.12

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 108851` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python37Packages.crytic-compile</li>
    <li>python37Packages.slither-analyzer</li>
    <li>python38Packages.crytic-compile</li>
    <li>slither-analyzer (python38Packages.slither-analyzer)</li>
    <li>python39Packages.crytic-compile</li>
    <li>python39Packages.slither-analyzer</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

failling builds require this version, they just need to be updated
```
https://github.com/NixOS/nixpkgs/pull/108851

3 packages failed to build:
python37Packages.slither-analyzer slither-analyzer python39Packages.slither-analyzer

3 packages built:
python37Packages.crytic-compile python38Packages.crytic-compile python39Packages.crytic-compile
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108851` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.slither-analyzer: log was empty</li>
<li>slither-analyzer: log was empty</li>
<li>(python38Packages.slither-analyzer): log was empty</li>
<li>python39Packages.slither-analyzer: log was empty</li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.crytic-compile</li>
<li>python38Packages.crytic-compile</li>
<li>python39Packages.crytic-compile</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108851` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.slither-analyzer: log <a href="https://termbin.com/v6rw">https://termbin.com/v6rw</a></li>
<li>slither-analyzer: log <a href="https://termbin.com/oihha">https://termbin.com/oihha</a></li>
<li>(python38Packages.slither-analyzer): log was empty</li>
<li>python39Packages.slither-analyzer: log <a href="https://termbin.com/od9s">https://termbin.com/od9s</a></li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.crytic-compile</li>
<li>python38Packages.crytic-compile</li>
<li>python39Packages.crytic-compile</li>
</ul>
</details>

**Pull request merged**
