### PR TITLE
mypy: 0.812 → 0.910

### PR DESCRIPTION
**Pull request by nicoonoclaste**
- types-toml: Init at 0.1.5
- mypy: 0.812 → 0.910

###### Motivation for this change

- types-toml: Init at 0.1.5
  type annotations for `toml`, a new dependency of `mypy`.

- mypy: 0.812 → 0.910
  New versions of `mypy` include significant changes:
  - Switch to [modular `typeshed`](https://mypy-lang.blogspot.com/2021/05/the-upcoming-switch-to-modular-typeshed.html)
  - [`TypeGuard`](https://www.python.org/dev/peps/pep-0647/) support
  - Configuration via `pyproject.toml`

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] ~~Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))~~ N/A
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

###### Issues

@lnl7 @martingms I am having issues getting this to build, as `mypy` apparently
doesn't find the type hints for the `toml` module, even though it should be in
`$PYTHONPATH`.  Any hint (^^') how to proceed?

### CODE REVIEW

**Comment by mweinelt** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/130173

**Comment by nbraud** [comment]
@mweinelt Thanks, not sure how I missed that.

@veehaitch, would you like shared maintainership of `types-toml` and `types-typed-ast`, if/when I figure out what's broken here?

**Comment by veehaitch** [comment]
> @veehaitch, would you like shared maintainership of `types-toml` and `types-typed-ast`, if/when I figure out what's broken here?

Very much, yes!

**Comment by takeda** [comment]
I see that here and in https://github.com/NixOS/nixpkgs/pull/130173 it looks like change is completed and appears the checks have passed, but PR is still listed as a draft? Is there some kind of issue that prevents this or https://github.com/NixOS/nixpkgs/pull/130173 to be merged?

**Comment by takeda** [comment]
Just noticed the comment that repo maintainers can update a draft to a PR, @lovesegfault or @jonringer I saw that you merged prior updates to this package. Can you please look at this or https://github.com/NixOS/nixpkgs/pull/130173 and merge it? Recent changes to mypy don't allow to automatically bump version anymore.

**Comment by mweinelt** [comment]
I think this can well stay a draft until the issues the author noticed themselves are resolved.

**Comment by wamserma** [comment]
Closes https://github.com/NixOS/nixpkgs/issues/139319

**Comment by nbraud** [comment]
> I see that here and in #130173 it looks like change is completed and appears the checks have passed, but PR is still listed as a draft? Is there some kind of issue that prevents this or #130173 to be merged?

As @mweinelt noted, there's a couple of remaining issues which are why I left this as draft for now.
I've been delving in `mypy` annotation-finding code to try and debug this, but no success so far.

**Comment by superherointj** [comment]
@nbraud Opened a new PR. Hope you don't mind. Check if issues are resolved. I've integrated @jnetod additions. Feel free to add yourself as maintainer (in a new PR).

**Comment by SuperSandro2000** [comment]
Closing in favor of #140627

**Pull request closed without merging**
