### PR TITLE
appium: init at 2.4.1

### PR DESCRIPTION
**Pull request by NyCodeGHG**
## Description of changes

https://appium.io

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eyJhb** [comment]
Awesome work! I'll hopefully have time to check this out tomorrow! :)

**Comment by NyCodeGHG** [comment]
thanks! this still needs some work on buildNpmPackage for missing lockfile fields

**Comment by eyJhb** [comment]
> thanks! this still needs some work on buildNpmPackage for missing lockfile fields

I was just sitting around, trying to get it to compile using nix on my own system, and I wanted to use yarn2nix. Have you considered if that could be a option for this? A `yarn.lock` can be generated by just doing `yarn install` or whatever. 

But I didn't get further, because then I stumbled upon this. But maybe it could be a option, if you're dealing with pesky workspace/npm/whatever errors. 

I really admire your patience for packaging this :p

**Comment by eyJhb** [comment]
Made a branch of it here https://github.com/eyJhb/nixpkgs/tree/appium :) @NyCodeGHG not enough time to complete it?

**Comment by NyCodeGHG** [comment]
@eyJhb I deleted the wrong branch while cleaning stuff up, but until there is a way of getting around the npm lockfile bug, I don't see this getting packaged soon :(

**Comment by eyJhb** [comment]
Wouldn't it be fine to just vendor it for now? :)

**Comment by eyJhb** [comment]
@NyCodeGHG can you explain what you did in the lockfile, to create the patch?

**Comment by eyJhb** [comment]
@NyCodeGHG sorry for the ping once more, but I don't think that the lockfile should stop this. We vendor other lockfiles as well. Even then, could you tell me what you did to convert the lockfile to something we understand?

**Comment by NyCodeGHG** [comment]
@eyJhb sorry, i forgot to reply.
We do vendor other lockfiles, but that should really be the last resort.
To get a "clean" lockfile, you need to checkout the repo, delete every node_modules folder and package-lock.json files and run npm install.

**Pull request closed without merging**
