### PR TITLE
kabeljau: Disable on Darwin

### LINKED ISSUE #343346: Build failure: kabeljau (on Darwin)
### Steps To Reproduce

1. build `kabeljau` on Darwin

### Build log

```
Running phase: installPhase
+ test -f /nix/store/z9655l0m7bxz5g37xl01yv70lf2md1dl-kabeljau-1.2.0/bin/kabeljau
+ test -f /nix/store/z9655l0m7bxz5g37xl01yv70lf2md1dl-kabeljau-1.2.0/share/applications/kabeljau.desktop
+ for icon_width in 32 64 128
+ test -f /nix/store/z9655l0m7bxz5g37xl01yv70lf2md1dl-kabeljau-1.2.0/share/icons/hicolor/32x32/apps/kabeljau.png
+ for icon_width in 32 64 128
+ test -f /nix/store/z9655l0m7bxz5g37xl01yv70lf2md1dl-kabeljau-1.2.0/share/icons/hicolor/64x64/apps/kabeljau.png
+ for icon_width in 32 64 128
+ test -f /nix/store/z9655l0m7bxz5g37xl01yv70lf2md1dl-kabeljau-1.2.0/share/icons/hicolor/128x128/apps/kabeljau.png
+ mkdir -p ./build
+ rm -rf ./build
+ install -Dm700 kabeljau.sh ./build/bin/kabeljau
+ install -Dm600 kabeljau.desktop -t ./build/usr/share/applications
+ mkdir -p ./build/usr/share/icons/hicolor
+ for icon_width in 32 64 128
+ mkdir -p ./build/usr/share/icons/hicolor/32x32/apps
+ inkscape -o ./build/usr/share/icons/hicolor/32x32/apps/kabeljau.png -C -w 32 -h 32 --export-png-color-mode=RGBA_8 icons/hicolor/32x32/kabeljau.svg

** (process:91057): WARNING **: 20:22:59.393: Unable to create profile directory (Read-only file system) (30)
** Message: 20:22:59.679: Cannot create profile directory /homeless-shelter/.config/inkscape.
** Message: 20:22:59.679: Inkscape will run with default settings, and new settings will not be saved. 
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories

** (org.inkscape.Inkscape:91057): WARNING **: 20:22:59.770: Could not create directory '/homeless-shelter/.config/inkscape'

** (org.inkscape.Inkscape:91057): WARNING **: 20:22:59.770: Could not create extension error log file '/homeless-shelter/.config/inkscape/extension-errors.log'

(org.inkscape.Inkscape:91057): Gtk-CRITICAL **: 20:22:59.793: Unable to create user data directory '/homeless-shelter/.local/share' for storing the recently used files list: Read-only file system
2024-09-20 20:22:59.851 .inkscape-wrapped[91057:2519730] +[NSXPCSharedListener endpointForReply:withListenerName:replyErrorCode:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
/private/tmp/nix-build-kabeljau-1.2.0.drv-0/just-wdz7Um/build: line 21: 91057 Trace/BPT trap: 5       inkscape -o ./build/usr/share/icons/hicolor/$icon_width"x"$icon_width/apps/kabeljau.png -C -w $icon_width -h $icon_width --export-png-color-mode=RGBA_8 icons/hicolor/32x32/kabeljau.svg
error: Recipe `build` failed with exit code 133
error: builder for '/nix/store/m1c00pjvxdky1mzpy9h6ik943jpl4q5a-kabeljau-1.2.0.drv' failed with exit code 133;
       last 10 log lines:
       > Fontconfig error: No writable cache directories
       >
       > ** (org.inkscape.Inkscape:91057): WARNING **: 20:22:59.770: Could not create directory '/homeless-shelter/.config/inkscape'
       >
       > ** (org.inkscape.Inkscape:91057): WARNING **: 20:22:59.770: Could not create extension error log file '/homeless-shelter/.config/inkscape/extension-errors.log'
       >
       > (org.inkscape.Inkscape:91057): Gtk-CRITICAL **: 20:22:59.793: Unable to create user data directory '/homeless-shelter/.local/share' for storing the recently used files list: Read-only file system
       > 2024-09-20 20:22:59.851 .inkscape-wrapped[91057:2519730] +[NSXPCSharedListener endpointForReply:withListenerName:replyErrorCode:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
       > /private/tmp/nix-build-kabeljau-1.2.0.drv-0/just-wdz7Um/build: line 21: 91057 Trace/BPT trap: 5       inkscape -o ./build/usr/share/icons/hicolor/$icon_width"x"$icon_width/apps/kabeljau.png -C -w $icon_width -h $icon_width --export-png-color-mode=RGBA_8 icons/hicolor/32x32/kabeljau.svg
       > error: Recipe `build` failed with exit code 133
```

### Additional context

Calls Inkscape which tries to create working files in the sandbox.

### Notify maintainers

@auroraanna 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by sarahec**
## Description of changes

Disables on Darwin due to calling Inkscape during the install phase. Inkscape then tries to crete files in the sandbox.

Fixes #343346

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by viraptor** [comment]
It looks like it's trying to write to home. Have you tried to set HOME for just the Inkscape command to make it write to a temporary directory?

**Comment by viraptor** [comment]
Also the man page https://inkscape.org/doc/inkscape-man.html says:
> The default location of the profile directory can be overridden with the INKSCAPE_PROFILE_DIR environment variable.

**Comment by sarahec** [comment]
> It looks like it's trying to write to home. Have you tried to set HOME for just the Inkscape command to make it write to a temporary directory?

Setting `HOME=$TMPDIR` in the install script right before calling Inkscape doesn't help. Same BPT 5 trap, same troubles with Fontconfig.

**Comment by sarahec** [comment]
FYI, this package crashes `nixpkgs-review`.

**Comment by viraptor** [comment]
I can rebuild locally just fine with both `sandbox=true` and `sandbox=false`. This package isn't really broken as such... something weird is happening in the environment.

**Comment by sarahec** [comment]
> I can rebuild locally just fine with both `sandbox=true` and `sandbox=false`. This package isn't really broken as such... something weird is happening in the environment.

Darwin x86 or aarch64? I'm having the failures using nix-build -A kabeljau. (And it definitely crashes `nixpkgs-review`).

**Comment by viraptor** [comment]
Aarch64, run through nix-build on 14.6. Just waiting for the nix-review run now.

**Comment by sarahec** [comment]
I'll be mightily puzzled if it works for you but not for me.

**Comment by viraptor** [comment]
Works with nix-review with sandbox on as well:
(this is for a local noop change, not this PR)
Result of `nixpkgs-review` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>kabeljau</li>
  </ul>
</details>

**Comment by sarahec** [comment]
Can you install it from cache? (Is it building in Hydra?)

**Comment by sarahec** [comment]
@ofBorg build kabeljau

**Comment by sarahec** [comment]
Closing per @viraptor

**Comment by sarahec** [comment]
P.S. @viraptor if you have some special way to set up the development environment on Darwin I'd love to know. (I'm using the official nix installer + nix-Darwin installed as a flake. Working in a stock standard checkout of nixpkgs)

**Comment by viraptor** [comment]
Just the standard installation carried over since version 22 at least. MacOS is a black box full of surprises sometimes 🤷

**Comment by sarahec** [comment]
I get the same error you would see on Hydra:

```sh
+ inkscape -o ./build/usr/share/icons/hicolor/32x32/apps/kabeljau.png -C -w 32 -h 32 --export-png-color-mode=RGBA_8 icons/hicolor/32x32/kabeljau.svg

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Critical error: required built-in appearance SystemAppearance not found'
*** First throw call stack:
```

I'm curious what setting you have that allows the builder access to the UI.

**Pull request closed without merging**
