### PR TITLE
kati: init at 2dde61

### PR DESCRIPTION
**Pull request by Gabriella439**
###### Motivation for this change

We're trying to write a `make2nix` utility at Awake Networks, but due to the complexity of
Make's semantics we'd like to reuse the `kati` project to transform `Makefile`s to the simpler
`ninja` file format which we can then more easily translate to Nix derivations

The first step in this is adding `kati` to `nixpkgs`, which is what this change does

NOTE: This does not build on `master` most likely due to changes introduced in 6b999f3c42607342231b6fe119fcf0f934f40fd8 which break the following chain of derivations:

```
  /nix/store/4dsy1vkny9938yqg5k5c3lg357v2dzha-python2.7-hypothesis-3.11.0.drv
  /nix/store/qp1dwblvm3wn4xq3x59rcz9ncaphhm2b-python2.7-cryptography1.8.1.drv
  /nix/store/dg59z5r33nrlm3622nan403zb7qj3zfn-python2.7-paramiko-2.1.1.drv
  /nix/store/4fz077qbsw2b6xvp7csmdyhbxikpj2bm-bazaar-2.7.0.drv
  /nix/store/c7p5sbpan0qa45n9x8gsnkqh9k32q969-go-1.8.3.drv
  /nix/store/jqf40zx08bkbz0zrsz8vx1v6f0masiy8-govers-20150109-3b5f175.drv
  /nix/store/m05bhn2c0bx4pwgl944a4njz58jrvkw6-kati-unstable-2017-05-23.drv
```

... but this does build on a fairly recent commit (4cbd5e4141422b835a86bb1b5e2d004a3c9a3a3e) so once the Python-related breakage is fixed this build should succeed again

cc: @taktoa (who is also using this to write a `haskell2nix` utility for incremental Haskell builds
by taking advantage of GHC's `Makefile` output)

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by taktoa** [comment]
I don't think `go` is needed, as `kati` was rewritten in C++. As I understand it, all the `.go` files in the repo are just historical artifacts, not actually relevant code.

**Comment by FRidh** [comment]
@Gabriel439 hypothesis should build again with https://github.com/NixOS/nixpkgs/commit/b27a2667db0b2b2b2546f1c2d5bdcc78e13132d3.

**Comment by Gabriel439** [comment]
@taktoa: The `ckati` binary built by the C++ build doesn't support generating `ninja` files from `Makefile`s like the `kati` executable does.  In fact, as far as I can tell it isn't complete yet because it doesn't take any options and just serves as a very basic `make` replacement

@FRidh: Thanks!  That fixed it

**Comment by taktoa** [comment]
use `ckati --ninja Makefile`.

**Comment by Gabriel439** [comment]
I think this is ready now.  This now uses the C++ build and I verified that I could generate `.ninja` files from `Makefile`s using the `ckati` executable

**Comment by fpletz** [comment]
Squashed. Thanks!

**Comment by anka-213** [comment]
@Gabriel439 Did you get anywhere with the make2nix project?

**Comment by Gabriel439** [comment]
@anka-213: We did not pursue that in the end, mainly due to being blocked on the absence of support for recursive Nix at the time

**Pull request merged**
