### PR TITLE
gnome.mutter: 43.3 -> 43.4

### PR DESCRIPTION
**Pull request by jian-lin**
This release fixes some focus regressions[1], but introduces two
new[2] ones[3].

I think the issues it fixes is much more annoying than thoes it
introduces, hence this PR.

[1]: https://gitlab.gnome.org/GNOME/mutter/-/issues/2626
[2]: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2878#note_1685873
[3]: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2878#note_1696253

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bobby285271 — DISMISSED** [review]
Yeah I am aware of this [a month ago](https://github.com/NixOS/nixpkgs/pull/217068#discussion_r1112439161) and I am ~~utACKing~~ ACKing this as long as jtojnar is okay to resolve merge conflicts for [GNOME 44 PR](//github.com/NixOS/nixpkgs/pull/218143). Though [43.4](https://gitlab.gnome.org/GNOME/mutter/-/compare/43.3...43.4) should actually address this as well so you don't need to fetch so many patches. 


(I will leave the merge decision to jtojnar)

**Comment by jtojnar** [comment]
Ugh, https://gitlab.gnome.org/GNOME/mutter/-/issues/2690 sounds especially
annoying. But given that it will be there in 44, I guess we will have to
suffer through it either way.

I am fine with resolving conflicts. If the patch is part of an oldstable
release, bumping that would be preferred.

**Comment by jian-lin** [comment]
- mutter is bumped to 43.4
- I have tested it locally
- CI is passed

**Comment by Alizter** [comment]
Result of `nixpkgs-review pr 223106` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>gnomeExtensions.easyScreenCast</li>
  </ul>
</details>
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>gnome-browser-connector</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-control-center.debug</li>
    <li>gnome.gnome-session</li>
    <li>gnome.gnome-session.debug</li>
    <li>gnome.gnome-session.sessions</li>
    <li>gnome.gnome-shell</li>
    <li>gnome.gnome-shell.debug</li>
    <li>gnome.gnome-shell.devdoc</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-tweaks</li>
    <li>gnome.gpaste</li>
    <li>gnome.mutter</li>
    <li>gnome.mutter.debug</li>
    <li>gnome.mutter.dev</li>
    <li>gnome.mutter.devdoc</li>
    <li>gnome.mutter.man</li>
    <li>gnome.nixos-gsettings-overrides</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.gsconnect.installedTests</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>mojave-gtk-theme</li>
    <li>pantheon.elementary-session-settings</li>
    <li>phoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>vimix-gtk-themes</li>
    <li>whitesur-gtk-theme</li>
  </ul>
</details>

**Comment by jian-lin** [comment]
I do not think this PR makes gnomeExtensions.easyScreenCast fail to build.  Anyway, I fixed that in https://github.com/NixOS/nixpkgs/pull/223225.

**Comment by jtojnar** [comment]
Changes look okay: https://gitlab.gnome.org/GNOME/mutter/-/compare/43.3...43.4

Might be nice to add GNOME Shell bump as well.

**Comment by jian-lin** [comment]
The gnome-shell bump is added.  I have been using it and there is no issue no far.  Not sure what the failed CI tasks, `ofborg-eval` and `ofborg-eval-check-meta`, mean.

**Comment by jtojnar** [comment]
@ofborg eval

**Comment by jian-lin** [comment]
ping :)

**Comment by bobby285271** [comment]
Ah since this is some focus change, I imagine the eval is giving something like `(false, 'TypeError: global.display.focus_window is null')` if the test is failing?

**Comment by bobby285271** [comment]
> (Though we probably need to re-read the changes and figure out why this happens first...)

It sounds like the MR does cause other regressions https://gitlab.gnome.org/GNOME/mutter/-/issues/2690 :upside_down_face:

**Comment by jian-lin** [comment]
https://gitlab.gnome.org/GNOME/mutter/-/issues/2690 has been mentioned multiple times in this PR.  It happens when you open multiple windows of the same program.  I do not think it makes our nixos tests fail. (if that is why you mention it)

What about downgrade to 43.2?  In that case, there will not be any focus regressions until Gnome 44 lands.

**Comment by bobby285271** [comment]
>  I do not think it makes our nixos tests fail. (if that is why you mention it)

Hmmm, it sounds like the problematic commit are both https://gitlab.gnome.org/GNOME/mutter/-/commit/3ac82a58c51a5c8db6b49e89a1232f99c79644cc (by excluding this commit from e4d942f8aa725a7e561f13a2e4f51cb7a4acfbae the test pass for me).

**Pull request closed without merging**
