### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by vcunat** [comment]
@NixOS/darwin-maintainers: there's been a mass failure for about a week (I think) &ndash; `swift-corefoundation` [doesn't build](https://hydra.nixos.org/build/98372621) (repeatedly), can some of you have a look?

**Comment by LnL7** [comment]
Unfortunately I can't seem to reproduce that locally. (both on 10.12 and 10.14)

```
[175/180] CompileC: String.subproj/CFRegularExpression.c
[176/180] CompileC: String.subproj/CFRunArray.c
[177/180] CompileC: URL.subproj/CFURL.c
[178/180] CompileC: String.subproj/CFString.c
[179/180] CompileC: Base.subproj/CFKnownLocations.c
[180/180] Link: Build/CoreFoundation/libCoreFoundation.dylib
ld: warning: directory not found for option '-L../bootstrap/x86_64-apple-darwin/usr/lib'
ld: warning: undefined base symbol '__TMC15SwiftFoundation19_NSCFConstantString' for alias '___CFConstantStringClassReference'
installing
post-installation fixup
strip is /nix/store/68cs638458sifx94qila1xwpbmw88yrq-cctools-binutils-darwin/bin/strip
patching script interpreter paths in /nix/store/0y4lhd3n4dq1v4771p703jcxrbwcg4i1-swift-corefoundation
warning: rewriting hashes in '/nix/store/lpgv4agfpz7p08pnvp63n20k7ffhhznq-swift-corefoundation'; cross fingers
/nix/store/lpgv4agfpz7p08pnvp63n20k7ffhhznq-swift-corefoundation
```

**Comment by grahamc** [comment]
I just managed to run the build on 10.13.6 which is what hydra runs.

**Comment by vcunat** [comment]
And it succeeded?

> Running pass 'Interprocedural Sparse Conditional Constant Propagation' on module 'Base.subproj/CFRuntime.c'.

Perhaps it's possible to work around it by tweaking optimization parameters for this package/file.

**Comment by FRidh** [comment]
@NixOS/darwin-maintainers are there any ideas how to proceed?

**Comment by FRidh** [comment]
opened a separate issue for darwin issue https://github.com/NixOS/nixpkgs/issues/66811

**Comment by grahamc** [comment]
We were able to reproduce it when running it in a loop... but only sometimes. Ugh.

**Pull request merged**
