### PR TITLE
soapysdr+plugins: init at 0.6.1

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
This the first step to integrate the soapysdr driver, which provides a unified SDR driver library.
Includes the following components:
- soapysdr library
- SDR plugins for: airspy, hackrf, bladerf, uhd, limesdr
- Remote plugin
- Integration with welle-io

See also: https://github.com/NixOS/nixpkgs/pull/37020
@roosemberth Does this implementation work for you?

Thanks to @ck3d for some valuable feedback on integrating the plugin system

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build soapysdr-with-plugins soapysdr soapyuhd soapybladerf soapyairspy welle-io soapyremote soapyhackrf limesuite

**Comment by Mic92** [comment]
It is weird that this error does not come up on x86_64.

**Comment by markuskowa** [comment]
I guess this line causes the error on aarch64:
`/build/source/src/backend/viterbi_spiral.c:23:10: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>`
According to hydra `welle-io` never built successfully on aarch64. I'll just remove the architecture from the meta tags.

**Comment by roosemberth** [comment]
Sidenote: this works for me, closing #37020 in favor of this one.

**Comment by markuskowa** [comment]
@Mic92 I would be good to go. Do we need any other refinements?

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
