### PR TITLE
haskell.compiler.ghc9{6,8}: work around output cycles on aarch64-darwin

### PR DESCRIPTION
**Pull request by mpscholten**
## Description of changes

Fix for https://github.com/NixOS/nixpkgs/pull/255037#issuecomment-1741767225

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
Let's see if ofborg is able to build this for us to test:

@ofborg build haskell.packages.ghc963.ormolu

**Comment by mpscholten** [comment]
@cdepillabout looks like it failed because `ghc963` is missing on this branch. Can you trigger a build on `ghc962`?

**Comment by cdepillabout** [comment]
@mpscholten It appears that `haskell.packages.ghc963.ormolu` succeeded on x86_64-linux and -darwin, which indicates that 9.6.3 is available.

It appears to be timing out for aarch64 (which is likely expected, given that ofborg will timeout with long builds, and ghc is a long build).

Also, in the future, I think you should be able to run ofborg yourself, just by giving a similar `@ofborg build ...` in a comment if you want to play around with it!

**Comment by mpscholten** [comment]
It seems like `ormolu` is not failing anymore on the M1 runner. The build has now run [into a different issue](https://gitlab.haskell.org/ghc/ghc/-/issues/24041) which is unrelated to this change.

**Comment by cdepillabout** [comment]
> It seems like `ormolu` is not failing anymore on the M1 runner. The build has now run [into a different issue](https://gitlab.haskell.org/ghc/ghc/-/issues/24041) which is unrelated to this change.

Hey, sorry I hadn't gotten back to you.

Is this PR still stuck on waiting for https://gitlab.haskell.org/ghc/ghc/-/issues/24041 to be fixed?

**Comment by mpscholten** [comment]
Yes, looks like a fix was merged for GHC 9.8.x but no backport for 9.6.x yet

**Comment by cdepillabout** [comment]
@mpscholten Do you mind if I convert this to a draft since we are still waiting on upstream for a fix for 9.6?

(If I've misunderstood, and this shouldn't be put into a draft, feel free to switch it back to non-draft.)

**Comment by mpscholten** [comment]
As far as I understand the fix here is actually independent of that GHC issue. So even when GHC has merged that fix, I think this issue here will still happen unless the PR is merged

**Comment by mpscholten** [comment]
Yes correct.

This PR here specifically fixes the issue of https://github.com/NixOS/nixpkgs/issues/140774 for GHC 9.6 This was also applied for GHC 9.4 via https://github.com/NixOS/nixpkgs/issues/220647

**Review by sternenseemann — APPROVED** [review]

**Comment by maralorn** [comment]
Nice!

**Pull request merged**
