### PR TITLE
assorted gnome updates

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
See commit msg's for links to News

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
We should probably add `gdk-pixbuf` to `clutter-gst` dependencies.

**Comment by worldofpeace** [comment]
> We should probably add `gdk-pixbuf` to `clutter-gst` dependencies.

Yep, since it's explicit now.

**Comment by hedning** [comment]
Fixed the gnome-desktop bubblewrap patch.

**Review by jtojnar — APPROVED** [review]

**Comment by worldofpeace** [comment]
Thanks @hedning

**Comment by hedning** [comment]
So the thumbnailing script refuse to run due `/var/cache/fontconfig` not being present. A simple, but ad-hoc fix is telling gnome-desktop to use `PKG_CONFIG_FONTCONFIG_CACHEDIR = "/etc/fonts";`.

I guess a more robust fix is only mounting the fontconfig cache if it actually exists.

**Pull request merged**
