### PR TITLE
slurm: 17.11.9-2 -> 18.08.0-1

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
Update `slurm` and adapt nixos module.

###### Things done

- Update slurm
- Update pySlurm to 20180811
- Add option `clusterName` to module.
 slurm 18.08 requires `ClusterName` to be set.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg test slurm

**Comment by xeji** [comment]
@GrahamcOfBorg build python27Packages.pyslurm python36Packages.pyslurm

**Comment by xeji** [comment]
Looks like `pyslurm` needs to be updated as well.

**Comment by markuskowa** [comment]
`pySlurm` seems to be very particular about the slurm version. Looks like this update has to wait then until `pySlurm` is updated.

**Comment by xeji** [comment]
Yes, unfortunately `pyslurm` upstream only supports `slurm` 17.11.9

**Comment by veprbl** [comment]
I think that ```pyslurm``` pretending to not support new ```slurm``` versions is often for no reason. Looking at commits [1] I see no real ABI changes, but bumps of max version every time with no real change to the code. I wonder if we could just drop this check.

[1] https://github.com/PySlurm/pyslurm/commits/master

**Comment by markuskowa** [comment]
@veprbl I agree. The choice in `pyslurm` looks a bit random. However, when I remove the version check, I get an error. It seems not be compatible. Bumping the `pyslurm` version to latest git revision, does also not work.

```
warning: pyslurm/pyslurm.pyx:59:4: 'id_t' redeclared
warning: pyslurm/pyslurm.pyx:62:10: 'PRIO_PROCESS' redeclared
warning: pyslurm/pyslurm.pyx:67:4: 'const_char_ptr' redeclared
warning: pyslurm/pyslurm.pyx:68:4: 'const_char_pptr' redeclared
warning: pyslurm/pyslurm.pyx:71:13: 'ALPS_CRAY_SYSTEM' redeclared
warning: pyslurm/slurm.pxd:15:4: 'size_t' redeclared
warning: pyslurm/slurm.pxd:241:8: 'WAIT_POWER_NOT_AVAIL' redeclared
warning: pyslurm/slurm.pxd:242:8: 'WAIT_POWER_RESERVED' redeclared
warning: pyslurm/slurm.pxd:1752:4: 'dynamic_plugin_data_t' redeclared
warning: pyslurm/slurm.pxd:1754:4: 'bitstr_t' redeclared
warning: pyslurm/slurm.pxd:2416:4: 'slurmdb_assoc_rec_t' redeclared
warning: pyslurm/slurm.pxd:2433:4: 'slurmdb_cluster_rec_t' redeclared
error: command 'gcc' failed with exit status 1
```

**Comment by xeji** [comment]
I suggest opening an upstream issue to support latest slurm.

**Comment by markuskowa** [comment]
https://github.com/PySlurm/pyslurm/issues/126

**Comment by giovtorres** [comment]
Hi, I help to maintain PySlurm.  The versioning could certainly be improved.  The version checks are sanity checks to make sure that PySlurm is compiled against the right version of Slurm.  This was necessary a few years back when there would be changes to `slurm.h` in the middle of branch, say the .5 micro version, and newer versions of PySlurm would then break for micro versions .1 thru .4.  Over the last 2 major/minor versions, however, I've noticed the API has stabilized quite a bit and this has become unnecessary, but that's not to say it can't happen again.

Switching between major or minor versions almost always requires updates to PySlurm that match the changes to the slurm headers and any code in the API that is wrapped or referenced by PySlurm.

I updated the test container to 18.08.0 over the weekend and I've started to update PySlurm for 18.08.0-1.

**Comment by markuskowa** [comment]
@giovtorres Thanks!

**Comment by xeji** [comment]
There's still a merge conflict

**Comment by markuskowa** [comment]
@GrahamcOfBorg build python37Packages.pyslurm

**Comment by xeji** [comment]
don't have python37 yet :smile:
@GrahamcOfBorg build python36Packages.pyslurm

**Comment by markuskowa** [comment]
We actually do: /nix/store/q38ddqq7nz82lv6z0arl5wdk9s3w3j96-python3-3.7.0 
though it's not the default yet

**Comment by xeji** [comment]
Is this ready to merge? (If you like to work on python37 support, that should probably be a separate PR)

**Comment by markuskowa** [comment]
Yes, I would say it is ready. Python 3.7 seems to be very experimental as
of now. I couldn't even find hydra builds.

**Pull request merged**
