### PR TITLE
Allow spaces in variables set through makeWrapperArgs

### PR DESCRIPTION
**Pull request by mbakke**
### The issue

If a user tries to set a variable containing spaces with `makeWrapperArgs`, it will be broken up on said spaces by `wrapPythonPrograms` into separate `wrapProgram` arguments, resulting in a broken wrapper script.

E.g. if you do `makeWrapperArgs = ["--set LD_PRELOAD 'lib1 lib2'"]`, the resulting wrapper line will look as such: `export LD_PRELOAD='lib1`, which obviously isn't what we want.
### The fix

Bash supports declaring an array from a string while preserving quoted elements with the following syntax: `declare -a arrName="($varWithQuotedStrings)"`. I've modified `wrapPythonPrograms` to use that rather than naively looping through `makeWrapperArgs` (which is passed from Nix as a single string and has to be broken up one way or another).

I also had to add quotes around the exported variables from `wrapProgram` to cater for this new functionality. Otherwise the above example would end up as `export LD_PRELOAD=lib1 lib2` which naturally also breaks the parser.
### The merge

This triggers a rather hefty rebuild as everything that uses `makeWrapper` is affected. The `makeWrapper` change will cause breakage if there are cases where it's already quoted, and there is a chance that the new `wrapPythonPrograms` behaviour might break some uses. It may be wise to merge the `make-wrapper.sh` fix first to reduce noise.

### CODE REVIEW

**Comment by joachifm** [comment]
Looks to me like this ought to go via staging

**Comment by domenkozar** [comment]
Hmm, will this work on darwin?

**Comment by mbakke** [comment]
Staging sounds sensible. I assume Darwin is fine as bash arrays are used gratuitously elsewhere. It's easy enough to test, just add the above `makeWrapperArgs` example to any Python package with few dependencies (I've used `getmail` and `volatility`).

**Comment by benley** [comment]
I think this should be OK on darwin - even if things are explicitly using /bin/sh, that is bash 3.2.57 on MacOS and ought to be new enough to support these features.

**Comment by mbakke** [comment]
So how do we proceed with this? Is anyone able to test the fix on Darwin?

**Comment by vcunat** [comment]
Hmm, staged but it breaks some setup code for nixos tests: https://github.com/NixOS/nixpkgs/blob/staging/nixos/lib/testing.nix#L116 I couldn't find a quick solution, but I'll try to get to it later, unless someone else fixes it before that.

**Comment by mbakke** [comment]
It looks like just removing the double quotes should work. How do I test this locally?

**Comment by vcunat** [comment]
Rebasing *against master* is rather unhelpful, as the previous version of this PR was merged already to the staging branch (which won't be merged to master until these problems are fixed).

**Comment by vcunat** [comment]
I was testing by building one of the NixOS tests:
```
$ cd /path/to/nixpkgs/work/tree
$ nix-build nixos/release-combined.nix -A nixos.tests.installer.simple.x86_64-linux -Q
```

**Comment by mbakke** [comment]
Yes of course, just wanted a newer base to cherry-pick any fixes on, although it obviously doesn't matter. Building cec03a8e now, will look into the results tomorrow.

**Comment by vcunat** [comment]
@mbakke: If you use state a few commits later, e.g. current staging, you will get many binaries from the cache.

**Comment by mbakke** [comment]
Thanks for the tip. One obvious problem is that some exported variables contain bashisms. Currently building https://github.com/mbakke/nixpkgs/commit/a3cc2baf4d372c1790e997728e586c7b57abfebb, but I think you can include that right away.

**Comment by mbakke** [comment]
@vcunat Running the tests now on a remote VM without nested VMX, so it's fairly slow. But so far so good. I had to remove double quotes from the test wrapper as expected, and did a cursory grep across the tree for the same problem.

Will check on it later today. See https://github.com/mbakke/nixpkgs/commits/staging for the fixes.

**Comment by mbakke** [comment]
Hmm, the test has failed twice now at:

    machine# error: unable to download ‘http://curl.haxx.se/download/curl-7.47.1.tar.bz2’: Couldn't resolve host name (6)

I doubt it's related. At least the tests are running now; I think it's good to go for Hydra. Stupid of me to use single quotes on the wrapper to begin with, should have known better..

**Pull request closed without merging**
