### PR TITLE
nixos: doc: implement #12542

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

NixOS `documentation` subtree was born out of 2/3s of #12542, this implements the leftover 1/3. This patchset consists of option renames, code movements, a bit of cleanup, and one new assert.

In short, nothing substantial.

This simply makes the `configuration.nix(5)` manual cleaner and the `services.nixosManual` service is now actually a service, not an amalgamation of different things.

###### Known issues

`services.nixosManual.showManual` should be renamed to `services.nixosManual.enable`, but since `services.nixosManual.enable` meant a completely different thing before and there's no `configVersion`-thing yet I left it as is.

###### Things done

- [X] It builds.

Don't merge sooner than 2018-09-09 23:59 UTC.

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
I just skimmed this quickly, but I do like it.

**Review by samueldr — COMMENTED** [review]
Overall looks fine, just a nit pick with the phrasing. :+1: Thanks for the work!

**Comment by oxij** [comment]
Status: this conflicts with merged #46510 and I have questions about that change there, so this is now stalled.

**Comment by oxij** [comment]
Fixed nitpicks. Fixed conflicts and rebased.

**Review by samueldr — APPROVED** [review]

**Comment by Izorkin** [comment]
Error update NixOS

```
sudo nixos-rebuild switch --upgrade
unpacking channels...
building Nix...
building the system configuration...
error: attribute 'manual' missing, at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/services/misc/nixos-manual.nix:57:39
```
with --show-trace
```
unpacking channels...
building Nix...
building the system configuration...
error: while evaluating the attribute 'installBootLoader' of the derivation 'nixos-system-NixOS-Local-19.03pre153447.2da6f215d31' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/pkgs/stdenv/generic/make-derivation.nix:177:11:
while evaluating the attribute 'text' of the derivation 'install-grub.sh' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/pkgs/stdenv/generic/make-derivation.nix:177:11:
while evaluating 'flip' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/trivial.nix:74:16, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/boot/loader/grub/grub.nix:591:12:
while evaluating 'concatMapStrings' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/strings.nix:27:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/trivial.nix:74:19:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/boot/loader/grub/grub.nix:591:53, called from undefined position:
while evaluating the attribute 'text' of the derivation 'grub-config.xml' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/pkgs/stdenv/generic/make-derivation.nix:177:11:
while evaluating the attribute 'extraEntries' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:336:9:
while evaluating the option `boot.loader.grub.extraEntries':
while evaluating the attribute 'isDefined' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:374:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:348:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:416:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:349:62:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:232:58:
while evaluating the attribute 'config.extraEntries' at /etc/nixos/services/rescue-boot.nix:44:3:
while evaluating the attribute 'config.system.build.toplevel' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/system/activation/top-level.nix:272:5:
while evaluating 'foldr' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/lists.nix:36:20, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/system/activation/top-level.nix:136:12:
while evaluating 'fold'' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/lists.nix:39:15, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/lists.nix:43:8:
while evaluating 'showWarnings' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/system/activation/top-level.nix:100:18, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/system/activation/top-level.nix:107:16:
while evaluating 'foldr' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/lists.nix:36:20, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/system/activation/top-level.nix:100:23:
while evaluating 'fold'' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/lists.nix:39:15, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/lists.nix:43:8:
while evaluating the attribute 'warnings' at undefined position:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:336:9:
while evaluating the option `warnings':
while evaluating the attribute 'isDefined' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:374:5:
while evaluating the attribute 'values' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:348:28, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:416:25, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:349:62:
while evaluating the attribute 'value' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:232:58:
while evaluating the attribute 'config.warnings' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/system/boot/systemd.nix:707:5:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/attrsets.nix:225:10, called from undefined position:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/system/boot/systemd.nix:707:51, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/attrsets.nix:225:16:
while evaluating 'optional' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/lists.nix:199:20, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/system/boot/systemd.nix:708:7:
while evaluating the attribute 'serviceConfig.Type' at undefined position:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:336:9:
while evaluating the option `systemd.services.nixos-manual.serviceConfig':
while evaluating the attribute 'mergedValue' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:369:5:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:369:32, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:369:19:
while evaluating 'merge' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/types.nix:276:20, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:372:8:
while evaluating 'filterAttrs' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/attrsets.nix:115:23, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/types.nix:277:35:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/attrsets.nix:116:29, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/attrsets.nix:116:18:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/types.nix:277:51, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/attrsets.nix:116:62:
while evaluating the attribute 'ExecStart' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/attrsets.nix:335:7:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/types.nix:277:86, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/attrsets.nix:335:15:
while evaluating the attribute 'optionalValue' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:376:5:
while evaluating the attribute 'values' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:348:28, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:416:25, called from /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/modules.nix:349:62:
while evaluating the attribute 'value' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/lib/types.nix:282:55:
while evaluating the attribute 'ExecStart' at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/services/misc/nixos-manual.nix:57:9:
while evaluating the attribute 'system.build.manual.manualHTMLIndex' at undefined position:
attribute 'manual' missing, at /nix/store/0hfq6hrgyv5r8zz6lflxwhglgzgws2sb-nixos-19.03pre153447.2da6f215d31/nixos/nixos/modules/services/misc/nixos-manual.nix:57:39
```

**Comment by oxij** [comment]
Please show the output of `grep nixosManual configuration.nix` (and/or all equivalent files).

It looks like you have `services.nixosManual.enable` disabled but `services.nixosManual.showManual` enabled and the new `assert` gets computed too late for some reason.

**Comment by Izorkin** [comment]
Not found nixosManual  in /etc/nixos/*

**Comment by oxij** [comment]
Indeed, I reproduced your error it with a minimal config with the above combination of options, so evaluation order is indeed buggy, fixed in #47293.

Now the question is what sets this combination of variables in your config. Do you include any profiles?

(In principle, I can "fix" this by simply disabling `showManual` if manual is not being generated, but that combination of options is semantically incorrect.)

**Comment by Izorkin** [comment]
This config causes an error

causes an error

```
{ pkgs, ... }:
let
  netboot = import (pkgs.path + "/nixos/lib/eval-config.nix") {
      modules = [
        (pkgs.path + "/nixos/modules/installer/netboot/netboot-minimal.nix")
        module
      ];
    };
    module = {
      boot.supportedFilesystems = [ "zfs" ];
      boot.loader.grub.extraConfig = "
        serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1
        terminal_input console
        terminal_output console
      ";
      boot.kernelParams = [ "console=ttyS0,115200n8" ];
      boot.kernelPackages = pkgs.linuxPackages_4_18;
      boot.zfs.enableUnstable = true;
      services.openssh = {
        enable = true;
        ports = [ 22 ];
        passwordAuthentication = false;
        allowSFTP = true;
        forwardX11 = false;
        startWhenNeeded = true;
      };
    };
in {
  boot.loader.grub.extraEntries = ''
    menuentry "NixOS - Rescue boot" {
      linux ($drive1)/rescue-kernel init=${netboot.config.system.build.toplevel}/init ${toString netboot.config.boot.kernelParams}
      initrd ($drive1)/rescue-initrd
    }
  '';
  boot.loader.grub.extraFiles = {
    "rescue-kernel" = "${netboot.config.system.build.kernel}/bzImage";
    "rescue-initrd" = "${netboot.config.system.build.netbootRamdisk}/initrd";
  };
}

```

**Pull request merged**
