### PR TITLE
WIP: nixos: update system.stateVersion disclaimer

### PR DESCRIPTION
**Pull request by ilikeavocadoes**
##### Motivation for this change
A year ago I asked on discourse if I should ever want to change my system.stateVersion (https://discourse.nixos.org/t/when-should-i-change-system-stateversion/1433). I got my answer, but I thought the comment on the default configuration.nix is a bit misleading. It's meant to tell the user that the user doesn't need to change this value ever, but instead left me to wonder if it should regularly be changed.

Many new users seem to have this exact confusion. By a quick search I found at least 4 threads on discourse where someone asks the same question. I also periodically get hearts on discourse to my last message in the thread, where I state that I understand now that I should never change system.stateVersion. The thread also has more than 1 200 views, which is way more than a simple question should get. I think this is an indication that many users search for an answer to this same question.

I propose that the message to be reworded, but am unsure about the best wording. My current change is just an example, which I intend to replace with a better text. Any ideas about a better message?

### CODE REVIEW

**Comment by ryantm** [comment]
Here's another official place that documents stateVersion: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/version.nix#L54

**Comment by earksiinni** [comment]
I created https://github.com/NixOS/nixpkgs/issues/88948 not knowing that this PR already existed.

I think that this PR moves in the right direction, but I would make two suggestions:

1. The updated comment doesn't explain _why_ `stateVersion` should never need to change. OTOH, that setting's description does it quite well: https://github.com/NixOS/nixpkgs/blob/147aded7df024288a387e1dde290f79f964e41bf/nixos/modules/misc/version.nix#L56-L73 Why don't we simply use this description as the comment? IMHO, the description should first be updated to make it a little more beginner-friendly as it assumes a high level of knowledge about NixOS' internal structure (e.g., "You should only bump this option, if you are sure that you can or have migrated all state on your system which is affected by this option").
2. We should get rid of the "`Did you read the comment?`" parenthetical. At best, it has a bad doc smell--if you have to tell the reader to reread the previous section, there's a more fundamental problem. At worst, it has a somewhat passive-aggressive tone and could even be interpreted as condescending toward the reader.

**Comment by maralorn** [comment]
I it is worth noting that the comment in the configuration.nix has been changed in january 2020:

https://github.com/NixOS/nixpkgs/pull/77279

**Comment by maralorn** [comment]
I will close this, since it is about changing an out-dated version. Please feel free to open again or a new PR if you want to improve on the status quo.

**Pull request closed without merging**
