### PR TITLE
4 new audio derivations

### PR DESCRIPTION
**Pull request by joelmo**

### CODE REVIEW

**Comment by joelmo** [comment]
Tested in 16.03pre68782.54e430a (Emu).

Airwave doesn't work as expected in ardour. But in qtractor it's ok.

**Comment by edolstra** [comment]
Sorry, but I don't think we should be packaging proprietary Windows packages (which `vstsdk` and `asiosdk` appear to be, though they lack a description). (Precedent: https://github.com/NixOS/nixpkgs/pull/7597)

Also, the use of `requireFile` makes it impossible to install this automatically.

**Comment by joelmo** [comment]
Airwave needs vstsdk, and wineasio needs asiosdk. It won't be possible to install these automatically but it will be easier. vstsdk and asiosdk is proprietary but airwave and vstsdk is not. Each of these  needs one header file from the sdk.

If not vstsdk, asiosdk is in, can I add airwave and wineasio anyway?

There is another derivation using requireFile (nixos.oraclejdk) the same way I did here.

**Comment by joelmo** [comment]
Would it be ok to add a nixpkgs-restricted repository and add this link in nixpkgs: https://github.com/NixOS/nixpkgs/commit/17981e0c2c5c837330934cac90f723a4d03fe20a

This repo could also have another name, contrib, users or anything.

That way I can add sdks there and wineasio, airwave in nixpkgs?

**Comment by vcunat** [comment]
@edolstra: ping.

**Comment by joachifm** [comment]
Maybe create a new issue for nixpkgs-restricted, unless one already exists, and close this?

**Pull request closed without merging**
