### PR TITLE
papermc: 1.16.5r771 -> 1.17.1r97

### PR DESCRIPTION
**Pull request by neonfuz**
###### Motivation for this change
Version bump. Important especially because it's past a major version boundary. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by neonfuz** [comment]
This can be backported, I've heard there's a backport bot but I have no idea how to use it?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129870` at b18a3d05 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>papermc</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/games/papermc/default.nix:24:3:
```
   |
24 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/games/papermc/default.nix:18:3:
```
   |
18 |   buildPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by aaronjanse** [comment]
> This can be backported, I've heard there's a backport bot but I have no idea how to use it?

I haven't had a chance to try this locally, but assuming the PR works, I also think it should be backported.

**Comment by SuperSandro2000** [comment]
> This can be backported, I've heard there's a backport bot but I have no idea how to use it?

Just add the label to the PR:

**Pull request merged**
