### PR TITLE
Init CKAN: The Comprehensive Kerbal Archive Network

### PR DESCRIPTION
**Pull request by Baughn**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

At this version, it automatically discovers the Steam version of KSP. Works great!

### CODE REVIEW

**Comment by Baughn** [comment]
The mono commit was actually merged once before. I guess Github is showing it because it's a cherry-pick.

**Comment by obadz** [comment]
Ok thanks.

Looks nice. Want to add yourself as `maintainer` in `meta` and maybe also add a `platforms` tag?

**Comment by Baughn** [comment]
I added a maintainer tag, but platforms-wise, it really should run on any platform that Mono will run on. "All platforms" is accurate.

**Comment by joachifm** [comment]
Please use `platforms.all`; my interpretation of the docs is that no `platforms` implies "no platform"

**Comment by obadz** [comment]
Is this error benign?

```
Gtk not found (missing LD_LIBRARY_PATH to libgtk-x11-2.0.so.0?), using built-in colorscheme
```

**Comment by Baughn** [comment]
@joachifm That doesn't match my experience. It's installing fine. Still, I added it.

@obadz It means that the user theme won't be applied, but I'm not sure how to fix it without setting LD_LIBRARY_PATH, which I've previously been discouraged from. The program works anyway.

**Comment by joachifm** [comment]
@Baughn sure, but it won't be built by hydra.

**Comment by lokegustafsson** [comment]
4 years later, this package does not work for me - presumably due to being extremely outdated. Could someone with more experience than me with nix packaging update this? Maintainer mention: @Baughn

**Pull request merged**
