### PR TITLE
pianotrans: Use torch-bin on darwin

### PR DESCRIPTION
**Pull request by azuwis**
###### Description of changes

torch on darwin is very slow, switch to torch-bin make it 10 times faster.

Before this commit:

```
$ ./result/bin/pianotrans ~/src/pianotrans/test/cut_liszt.opus
Queue: /Users/azuwis/src/pianotrans/test/cut_liszt.opus
--------------------------------------------------------------------------------
Checkpoint path: /nix/store/x5s23cxikav9j6b7qjc8h8dj3939awsr-python3.10-piano-transcription-inference-0.0.5/share/checkpoint.pth
Using cpu for inference.
Using CPU.
--------------------------------------------------------------------------------
Transcribe: /Users/azuwis/src/pianotrans/test/cut_liszt.opus
Segment 0 / 3
Segment 1 / 3
Segment 2 / 3
Segment 3 / 3
Write out to /Users/azuwis/src/pianotrans/test/cut_liszt.opus.mid
Transcribe time: 86.738 s
--------------------------------------------------------------------------------
Queue finished.
--------------------------------------------------------------------------------
```

After this commit:
```
$ ./result/bin/pianotrans ~/src/pianotrans/test/cut_liszt.opus
Queue: /Users/azuwis/src/pianotrans/test/cut_liszt.opus
--------------------------------------------------------------------------------
Checkpoint path: /nix/store/zcfbs3p3j27rg73rs1pfqn75n1icmiyd-python3.10-piano-transcription-inference-0.0.5/share/checkpoint.pth
Using cpu for inference.
Using CPU.
--------------------------------------------------------------------------------
Transcribe: /Users/azuwis/src/pianotrans/test/cut_liszt.opus
Segment 0 / 3
Segment 1 / 3
Segment 2 / 3
Segment 3 / 3
Write out to /Users/azuwis/src/pianotrans/test/cut_liszt.opus.mid
Transcribe time: 8.796 s
--------------------------------------------------------------------------------
Queue finished.
--------------------------------------------------------------------------------
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I am not sure if this should be done on a higher level.

**Comment by mweinelt** [comment]
Wow, that difference is striking. Is it only reproducible on darwin?

**Comment by SomeoneSerge** [comment]
This looks astonishingly wrong.
This was also to be expected since we use many untested build flags and don't run benchmarks.

Quick Linux numbers for reference (they're dirty as I'm running something else in parallel, but they're consistent):

<details>

```console
❯ nix-shell -p pianotrans --command "pianotrans cut_liszt.opus"
Queue: cut_liszt.opus
--------------------------------------------------------------------------------
Checkpoint path: /nix/store/3airwlwxa3k06kaqh4nprjc9bpbzdzn1-python3.10-piano-transcription-inference-0.0.5/share/checkpoint.pth
Using cpu for inference.
Using CPU.
--------------------------------------------------------------------------------
Transcribe: cut_liszt.opus
Segment 0 / 3
Segment 1 / 3
Segment 2 / 3
Segment 3 / 3
Write out to cut_liszt.opus.mid
Transcribe time: 46.365 s
--------------------------------------------------------------------------------
Queue finished.
--------------------------------------------------------------------------------
~/Unsorted via 🐍 v3.10.9 took 2m30s
❯ nix-shell -p '(pianotrans.override { python3 = python3.override { packageOverrides = self: super: { torch = super.torch-bin; }; }; })'  --command "pianotrans cut_liszt.opus"
Queue: cut_liszt.opus
--------------------------------------------------------------------------------
Checkpoint path: /nix/store/j5rph7qic2cvd8xs5fgd65wb4xi4lryl-python3.10-piano-transcription-inference-0.0.5/share/checkpoint.pth
Using cuda for inference.
GPU number: 1
--------------------------------------------------------------------------------
Transcribe: cut_liszt.opus
Segment 0 / 3
Segment 1 / 3
Segment 2 / 3
Segment 3 / 3
Write out to cut_liszt.opus.mid
Transcribe time: 2.998 s
--------------------------------------------------------------------------------
Queue finished.
--------------------------------------------------------------------------------
~/Unsorted via 🐍 v3.10.9 took 34s
❯ LD_PRELOAD=/nix/store/l0d6c6wa5sk4wx70x77k3d5clmny7sw6-cuda_cudart-11.7.60/lib/stubs/libcuda.so nix-shell -p '(pianotrans.override { python3 = python3.override { packageOverrides = self: super: { torch = super.torch-bin; }; }; })'  --command "pianotrans cut_liszt.opus"
Queue: cut_liszt.opus
/nix/store/bzdidgqd016h9ygqp44xvi2w10wx1dr4-python3.10-torch-1.13.1/lib/python3.10/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 34: CUDA driver is a stub library (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
--------------------------------------------------------------------------------
Checkpoint path: /nix/store/j5rph7qic2cvd8xs5fgd65wb4xi4lryl-python3.10-piano-transcription-inference-0.0.5/share/checkpoint.pth
Using cpu for inference.
Using CPU.
--------------------------------------------------------------------------------
Transcribe: cut_liszt.opus
Segment 0 / 3
Segment 1 / 3
Segment 2 / 3
Segment 3 / 3
Write out to cut_liszt.opus.mid
Transcribe time: 34.648 s
--------------------------------------------------------------------------------
Queue finished.
--------------------------------------------------------------------------------
~/Unsorted via 🐍 v3.10.9 took 1m2s
```

</details>

**Comment by mweinelt** [comment]
Quite a bit less significant on my i7-1255U.

```
/tmp/pianotrans/test master ❯ nix-shell -p pianotrans --command "pianotrans cut_liszt.opus"         21:30:51
Queue: cut_liszt.opus
--------------------------------------------------------------------------------
Checkpoint path: /nix/store/n6h3r96m44qks0a3p265h5jh7vjq6l4z-python3.10-piano-transcription-inference-0.0.5/share/checkpoint.pth
Using cpu for inference.
Using CPU.
--------------------------------------------------------------------------------
Transcribe: cut_liszt.opus
Segment 0 / 3
Segment 1 / 3
Segment 2 / 3
Segment 3 / 3
Write out to cut_liszt.opus.mid
Transcribe time: 14.178 s
--------------------------------------------------------------------------------
Queue finished.
--------------------------------------------------------------------------------
```

```
/tmp/pianotrans/test master ?1 ❯ nix-shell -p '(pianotrans.override { python3 = python3.override { packageOverrides = self: super: { torch = super.torch-bin; }; }; })'  --command "pianotrans cut_liszt.opus"
Queue: cut_liszt.opus
--------------------------------------------------------------------------------
Checkpoint path: /nix/store/id2dy9vy90ydrnkgass468ipkf9i46cd-python3.10-piano-transcription-inference-0.0.5/share/checkpoint.pth
Using cpu for inference.
Using CPU.
--------------------------------------------------------------------------------
Transcribe: cut_liszt.opus
Segment 0 / 3
Segment 1 / 3
Segment 2 / 3
Segment 3 / 3
Write out to cut_liszt.opus.mid
Transcribe time: 14.027 s
--------------------------------------------------------------------------------
Queue finished.
--------------------------------------------------------------------------------

**Comment by mweinelt** [comment]
> I am not sure if this should be done on a higher level.

I'm not sure what you're saying here.

**Comment by SomeoneSerge** [comment]
@azuwis are you running an intel machine?

**Comment by SomeoneSerge** [comment]
Simply rebuilding with MKL cuts it down 5sec

<details>

```
❯ nix-shell ~/Sources/nixpkgs/torch-mkl.nix --command "pianotrans cut_liszt.opus"
Queue: cut_liszt.opus
--------------------------------------------------------------------------------
Checkpoint path: /nix/store/4m5cma4gm6f8n9g217l03p9w26hfvm2h-python3.10-piano-transcription-inference-0.0.5/share/checkpoint.pth
Using cpu for inference.
Using CPU.
--------------------------------------------------------------------------------
Transcribe: cut_liszt.opus
Segment 0 / 3
Segment 1 / 3
Segment 2 / 3
Segment 3 / 3
Write out to cut_liszt.opus.mid
Transcribe time: 5.859 s
--------------------------------------------------------------------------------
Queue finished.
--------------------------------------------------------------------------------
❯ cat ~/Sources/nixpkgs/torch-mkl.nix
with (import ./. {
  config.allowUnfree = true;
}
);

let
  torch = python3Packages.torch.override
    {
      blas = blas.override {
        blasProvider = mkl;
      };
      # lapack = lapack.override {
      #   lapackProvider = mkl;
      # };
    };
in
mkShell {
  packages = [
    (pianotrans.override { python3 = python3.override { packageOverrides = self: super: { inherit torch; }; }; })
  ];
}
```

</details>

**Comment by azuwis** [comment]
I've just run a test on a old x86_64-linux machine (i5-4250U) without nvidia card, torch and torch-bin show consistent similar results (49.641s vs 48.227s).

On aarch64-darwin, the different is significant (86.738s vs 8.796s).

Can someone run the test on x86_64-darwin?

**Comment by SomeoneSerge** [comment]
@azuwis the third test (with LD_PRELOAD) disables cuda

**Comment by azuwis** [comment]
I've tried this:

``` diff
--- a/pkgs/development/python-modules/torch/default.nix
+++ b/pkgs/development/python-modules/torch/default.nix
@@ -9,7 +9,7 @@
 
   # Build inputs
   numactl,
-  CoreServices, libobjc,
+  Accelerate, CoreServices, libobjc,
 
   # Propagated build inputs
   numpy, pyyaml, cffi, click, typing-extensions,
@@ -275,7 +275,7 @@ in buildPythonPackage rec {
     ++ lib.optionals rocmSupport [ openmp ]
     ++ lib.optionals (cudaSupport || rocmSupport) [ magma ]
     ++ lib.optionals stdenv.isLinux [ numactl ]
-    ++ lib.optionals stdenv.isDarwin [ CoreServices libobjc ];
+    ++ lib.optionals stdenv.isDarwin [ Accelerate CoreServices libobjc ];
 
   propagatedBuildInputs = [
     cffi
diff --git a/pkgs/top-level/python-packages.nix b/pkgs/top-level/python-packages.nix
index b85deafeb47..359d53c0586 100644
--- a/pkgs/top-level/python-packages.nix
+++ b/pkgs/top-level/python-packages.nix
@@ -11611,7 +11611,7 @@ self: super: with self; {
 
   torch = callPackage ../development/python-modules/torch {
     cudaSupport = pkgs.config.cudaSupport or false;
-    inherit (pkgs.darwin.apple_sdk.frameworks) CoreServices;
+    inherit (pkgs.darwin.apple_sdk.frameworks) Accelerate CoreServices;
     inherit (pkgs.darwin) libobjc;
     inherit (pkgs.llvmPackages_rocm) openmp;
   };
```

and got log:

```
Found a library with BLAS API (accelerate). Full path: (/nix/store/ayzalr4m1455j5pi9jlh7jfsng0ixibl-apple-framework-Accelerate-11.0.0/Library/Frameworks/Accelerate.framework)
```

Before/after is 87.902s/75.178s, a bit better, but still very slow.

**Comment by SomeoneSerge** [comment]
Well, I guess we keep looking. Can you also `gist` the full `nix log ...`?

For what it's worth, here's how I do the comparison, since I don't know better.
I strip the dates from the upstream to match formatting, like so: https://gist.github.com/SomeoneSerge/5f3b78a5a10abadd54c9cff7bbd4890e
Then I use nvim's diffsplit:

```console
❯ unzip 5f3b78a5a10abadd54c9cff7bbd4890e-f2d146ce3977933be3ecef280ef0b6a1015d52dd.zip
❯ nvim -O 5f3b78a5a10abadd54c9cff7bbd4890e-f2d146ce3977933be3ecef280ef0b6a1015d52dd/*
:diffthis
C-w l
:diffthis
```

**Comment by azuwis** [comment]
I think https://github.com/NixOS/nixpkgs/pull/220017 fixes the problem, with the patch I got:

```
Queue: /Users/azuwis/src/pianotrans/test/cut_liszt.opus
--------------------------------------------------------------------------------
Checkpoint path: /nix/store/c4l57n8cql9pa5ngaf6kal428wsi4qdq-python3.10-piano-transcription-inference-0.0.5/share/checkpoint.pth
Using cpu for inference.
Using CPU.
--------------------------------------------------------------------------------
Transcribe: /Users/azuwis/src/pianotrans/test/cut_liszt.opus
Segment 0 / 3
Segment 1 / 3
Segment 2 / 3
Segment 3 / 3
Write out to /Users/azuwis/src/pianotrans/test/cut_liszt.opus.mid
Transcribe time: 9.012 s
--------------------------------------------------------------------------------
Queue finished.
--------------------------------------------------------------------------------
```

**Comment by SuperSandro2000** [comment]
> I'm not sure what you're saying here.

We should fix this generally for torch.

**Comment by azuwis** [comment]
Close by #220017

**Pull request closed without merging**
