### PR TITLE
Emacs packages update: 2019-08-09

### PR DESCRIPTION
**Pull request by rasendubi**
###### Motivation for this change
Update elpa-packages, melpa-packages, melpa-stable-packages.

Checked with nix-instantiate. Also, works fine with my Emacs setup.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Previous update: https://github.com/NixOS/nixpkgs/pull/62784

cc @rycee (you seem to be interested in Emacs packages updates :slightly_smiling_face: )

### CODE REVIEW

**Comment by adisbladis** [comment]
@rasendubi Thanks for your PR!

We have recently changed the machinery for generating melpa-packages (see https://github.com/NixOS/nixpkgs/pull/59189).
Please use the new `update-melpa` script to update Melpa.

**Review by jonringer — COMMENTED** [review]
`+169,534 −88`
..... oh boy

**Comment by rasendubi** [comment]
Oh, I missed that. I have removed melpa packages from the PR, so it only updates elpa now.

**Comment by adisbladis** [comment]
Thanks!

**Pull request merged**
