### PR TITLE
searx: 0.18.0 -> 1.0.0

### PR DESCRIPTION
**Pull request by Lassulus**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

sadly I had to disable the tests because they wanted to do

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119529` at 7053c71d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>searx</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/servers/web-apps/searx/default.nix:1:63:
```
  |
1 | { lib, nixosTests, python3, python3Packages, fetchFromGitHub, fetchpatch }:
  |                                                               ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Please remove fetchpatch from inputs.

**Review by risicle — APPROVED** [review]
Builds, macos 10.14 & nixos tests pass, x86_64.

If you really wanted to get _some_ assurance back without the `checkPhase` you could add a `pythonImportsCheck`. I realize this is more an application than a module, but the `toPythonModule` implies that it is used as a module in at least some capacity.

**Comment by rnhmjoj** [comment]
I'm trying to find out why the NixOS test is failing but looks unrelated to the PR.
Anyway, if the tests really need networking now, just delete the lines no point in keeping them as comments.

**Review by dasj19 — APPROVED** [review]
Works on my server. Good job. Approved.

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg test searx

**Review by rnhmjoj — APPROVED** [review]

**Pull request merged**
