### PR TITLE
nodejs: 0.12.7 -> 4.1.0

### PR DESCRIPTION
**Pull request by utdemir**
A big version jump after io.js merge.

`dontDisableStatic` flag is added since the `./configure` script didn't
recognize `--disable-static` flag added by default.

New dependencies are also introduced, coming from io.js.

I tested this using a fairly large nodejs project, and the basic functionality was working; probably some packages are broken but most of them will work, I hope.

cc @cillianderoiste @Havvy

### CODE REVIEW

**Comment by utdemir** [comment]
I think the Travis error isn't relevant to this commit.

**Comment by domenkozar** [comment]
Shall we remove all `io.js` references?

**Comment by utdemir** [comment]
I thought about that, but I can't found a definitive answer about the future of the io.js project. Its website is up without any notice about the merge, but the code repository is redirected to nodejs's.

Perhaps we should alias `io.js` to `nodejs` temporarily?

**Comment by wmertens** [comment]
Perhaps it would be wise to put this on a separate attribute for now?

**Comment by utdemir** [comment]
@wmartens It's not as big as it sounds, the numbering may very well be `0.13.0`. I'm pretty sure there won't be any catastrophic failures.

**Comment by Havvy** [comment]
io.js and node.js merged. Node.js 4.0.0 is really io.js 3.2.x with changes from Node.js wrapped into it. In effect, io.js swallowed node.js up, and donned its name. Seeing that the people working on io.js were the same people working on node.js before the split, it's more like io.js was a continuation of node.js as Joyent became an impediment for development. As such, Node 0.10.x feels really outdated.

@domenkozar There's no reason to keep the io.js package, given that the way I was updating it was to follow the latest version and not keep older versions. (I haven't been updating it recently because of a minor bit of apathy, but meh.) If this was io.js 4.1.0, it'd be replacing the current io.js version.

Re: Broken packages - Given different versions of V8 used, many npm packages that uses binary parts will not compile. Though as those packages update to `nan` 2+, that's being fixed. But that's a problem in every distribution, not real NixOS specific. Really, NixOS helps this because for the packages that aren't updated yet (or never will update), we can have them specifically rely on Node 0.10.0. But I'm not sure if any of those packages are currently in our registry.

**Comment by utdemir** [comment]
I went ahead and removed io.js after @Havvy 's comment.

How about this?

**Comment by wmertens** [comment]
Ok, I follow the reasoning etc, and the PR looks good so :+1:.

I would just like this change to be documented in the release notes so people will know to recompile their modules.
(incidentally, npm2nix solves this problem by making nodejs part of the dependency of the modules)

**Comment by matthiasbeyer** [comment]
Can you please update the commit message of the package update commit? It lacks the dash for the arrow. Sorry for bothering you, but that's important for scripting, you know?

**Comment by utdemir** [comment]
@matthiasbeyer, Oh, I should have been more careful, fixed, thanks.

**Comment by wmertens** [comment]
@utdemir can you rebase? Then I'll pull.

**Comment by utdemir** [comment]
@wmertens Rebased, thanks

**Comment by wmertens** [comment]
Nothing better than merging a PR on a Friday evening ;)

**Comment by offlinehacker** [comment]
Does it work on Darwin?

**Comment by utdemir** [comment]
@offlinehacker I didn't tried this on Darwin, trying now.

**Comment by utdemir** [comment]
@offlinehacker Hmm. It can't apply `no-xcode.patch` properly.

```
applying patch /nix/store/w9f0cqmzjgpdcyfqaihzf80bdwn7x4xg-no-xcode.patch
patching file tools/gyp/pylib/gyp/xcode_emulation.py
Hunk #1 succeeded at 446 (offset 144 lines).
Hunk #2 succeeded at 579 (offset 152 lines).
Hunk #3 succeeded at 835 with fuzz 2 (offset 153 lines).
Hunk #4 succeeded at 1043 (offset 169 lines).
Hunk #5 FAILED at 1033.
1 out of 5 hunks FAILED -- saving rejects to file tools/gyp/pylib/gyp/xcode_emulation.py.rej
builder for ‘/nix/store/6q1crv6yd4i5bdq8adlg38jh7xyn08yv-nodejs-4.1.0.drv’ failed with exit code 1
error: build of ‘/nix/store/6q1crv6yd4i5bdq8adlg38jh7xyn08yv-nodejs-4.1.0.drv’ failed
/nix/var/nix/profiles/default/bin/nix-shell: failed to build all dependencies
```

With nixpkgs `6070cd0`.

**Pull request merged**
