### PR TITLE
libredirect: fix on darwin

### LINKED ISSUE #141811: libredirect is failed to build on MacOS (unstable channel)
### Describe the bug
`libredirect` is failed to build

### Steps To Reproduce

1. Install Nix packager on MacOS
2. `nix-shell -p libredirect`

### Expected behavior
Build without errors.

### Screenshots

```
% nix-shell -p libredirect
these derivations will be built:
  /nix/store/cjpqz1r3z04lh16f6mfms47p7w93f2in-libredirect-0.drv
building '/nix/store/cjpqz1r3z04lh16f6mfms47p7w93f2in-libredirect-0.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
libredirect.c:90:27: warning: second argument to 'va_arg' is of promotable type 'mode_t' (aka 'unsigned short'); this va_arg has undefined behavior because arguments will be promoted to 'int' [-Wvarargs]
        mode = va_arg(ap, mode_t);
                          ^~~~~~
/nix/store/gsf62i0m9a3lbvnlvci9nlranvx7ncrw-clang-wrapper-7.1.0/resource-root/include/stdarg.h:35:50: note: expanded from macro 'va_arg'
#define va_arg(ap, type)    __builtin_va_arg(ap, type)
                                                 ^~~~
libredirect.c:104:27: warning: second argument to 'va_arg' is of promotable type 'mode_t' (aka 'unsigned short'); this va_arg has undefined behavior because arguments will be promoted to 'int' [-Wvarargs]
        mode = va_arg(ap, mode_t);
                          ^~~~~~
/nix/store/gsf62i0m9a3lbvnlvci9nlranvx7ncrw-clang-wrapper-7.1.0/resource-root/include/stdarg.h:35:50: note: expanded from macro 'va_arg'
#define va_arg(ap, type)    __builtin_va_arg(ap, type)
                                                 ^~~~
libredirect.c:118:27: warning: second argument to 'va_arg' is of promotable type 'mode_t' (aka 'unsigned short'); this va_arg has undefined behavior because arguments will be promoted to 'int' [-Wvarargs]
        mode = va_arg(ap, mode_t);
                          ^~~~~~
/nix/store/gsf62i0m9a3lbvnlvci9nlranvx7ncrw-clang-wrapper-7.1.0/resource-root/include/stdarg.h:35:50: note: expanded from macro 'va_arg'
#define va_arg(ap, type)    __builtin_va_arg(ap, type)
                                                 ^~~~
3 warnings generated.
installing
install: creating directory '/nix/store/vnn9n7qz6r6wk5rmkqzlmmv6kzy9yl46-libredirect-0'
install: creating directory '/nix/store/vnn9n7qz6r6wk5rmkqzlmmv6kzy9yl46-libredirect-0/lib'
'libredirect.dylib' -> '/nix/store/vnn9n7qz6r6wk5rmkqzlmmv6kzy9yl46-libredirect-0/lib/libredirect.dylib'
post-installation fixup
patching script interpreter paths in /nix/store/vnn9n7qz6r6wk5rmkqzlmmv6kzy9yl46-libredirect-0
patching script interpreter paths in /nix/store/4z4i62b2yq642kfl48zvxdwami3kzadj-libredirect-0-hook
running install tests
Assertion failed: (testfp != NULL), function main, file test.c, line 51.
Assertion failed: (system(SUBTEST) == 0), function test_subprocess, file test.c, line 41.
/nix/store/nanwchp2iifac622hl6ad22bnpkqk2ip-stdenv-darwin/setup: line 1355: 66325 Abort trap: 6           NIX_REDIRECTS="/foo/bar/test=/nix/store/yf7fdgv8lad2xwxh579lk607sy09kzph-coreutils-8.32/bin/true" ./test
builder for '/nix/store/cjpqz1r3z04lh16f6mfms47p7w93f2in-libredirect-0.drv' failed with exit code 134
error: build of '/nix/store/cjpqz1r3z04lh16f6mfms47p7w93f2in-libredirect-0.drv' failed
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
% nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/b1ikfhh5p0fhgmdysi2bmr5bvbcx640s-nix-info
  /nix/store/fkkkf1lbcb186la1zh6f522krcn9vpn8-DarwinTools-1
copying path '/nix/store/fkkkf1lbcb186la1zh6f522krcn9vpn8-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/b1ikfhh5p0fhgmdysi2bmr5bvbcx640s-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(Admin): `"nixpkgs-21.11pre320922.ee084c02040"`
 - nixpkgs: `/Users/Admin/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by stephank**
###### Motivation for this change

ZHF: #144627
@NixOS/nixos-release-managers

Fixes: #141811

Also fixes an issue that may be new on macOS 11 or 12 where `DYLD_FORCE_FLAT_NAMESPACE` was removed. In this case, *all* tests failed, not just `test_subprocess`.

I'm not sure if there is away to make the macros prettier, using maybe some magic syntax I don't know of. 🙂

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
I think the macros are fine (or at least I've seen much uglier macros), and I haven't found any new failures on macos 10.15 & nixos x86_64.

I had to look up why the `DYLD_INSERT_LIBRARIES` thing was necessary at all, so it could probably do with a comment or something.

**Comment by siraben** [comment]
I ran `git bisect` on `libredirect` on darwin, below is the results. First bad commit is 5ca02655057bb568f09b3aed4acee44e3f805291

<details>

```
$ git bisect log
git bisect start
# bad: [b836d1d6676b6a9ebffabf7435bd3adc13995c6a] Merge pull request #144464 from r-ryantm/auto-update/minio
git bisect bad b836d1d6676b6a9ebffabf7435bd3adc13995c6a
# good: [4a57860df4b0a69fecdf2b0469d4a98f31d8d5ca] Merge pull request #136090 from jakubgs/more-syncthing-options
git bisect good 4a57860df4b0a69fecdf2b0469d4a98f31d8d5ca
# bad: [1645417960138185b7f5db5619a901fceb07f703] Merge pull request #139871 from fabaff/bump-urllib3
git bisect bad 1645417960138185b7f5db5619a901fceb07f703
# skip: [6f3ee459deac73b6d509b6e74a0fb0df78612d57] git: disable flaky test 6421-merge-partial-clone
git bisect skip 6f3ee459deac73b6d509b6e74a0fb0df78612d57
# good: [cfb993f75586757293e884b8403c1ea7ca507dd3] inferno: 0.10.6 -> 0.10.7
git bisect good cfb993f75586757293e884b8403c1ea7ca507dd3
# bad: [4d5f14d5f3123cb4346ee70ebd06c2068f5c16d8] python3Packages.claripy: 9.0.9792 -> 9.0.9947
git bisect bad 4d5f14d5f3123cb4346ee70ebd06c2068f5c16d8
# bad: [3a7e5f6c25155e09f7fe4b9ccb13dde339007377] ipxe: allow to pass options with values
git bisect bad 3a7e5f6c25155e09f7fe4b9ccb13dde339007377
# bad: [4e89f2a6091d2422f20804c603b05395d5f218c2] Merge #137106: knot-dns: 3.1.1 -> 3.1.2
git bisect bad 4e89f2a6091d2422f20804c603b05395d5f218c2
# bad: [ebd5774d272fc52a7ca0da667014f8fec90f6cd8] Duplicated shell-command-plus - manual fixup
git bisect bad ebd5774d272fc52a7ca0da667014f8fec90f6cd8
# bad: [4a4294d74be2c6fdc2041275762a8a1dc7216a0b] vim-plugins.direnv.vim: fix directory for substitution
git bisect bad 4a4294d74be2c6fdc2041275762a8a1dc7216a0b
# good: [717cbf8e7dcd14d97125cc1176d43c5dabc5c933] python38Packages.eventlet: 0.31.1 -> 0.32.0
git bisect good 717cbf8e7dcd14d97125cc1176d43c5dabc5c933
# bad: [1871c113f1d44f8e8922586b333e11d174bd19ca] Merge pull request #124157 from nh2/libredirect-children
git bisect bad 1871c113f1d44f8e8922586b333e11d174bd19ca
# good: [0ecfdfcc60e8dfbfb1df2044aeb8968317d76a05] Merge pull request #136599 from lugray/update_shadowenv
git bisect good 0ecfdfcc60e8dfbfb1df2044aeb8968317d76a05
# good: [0197de93b6cac9b88a71d969aa4802c2a24a47d2] Merge pull request #136671 from primeos/intel-media-driver
git bisect good 0197de93b6cac9b88a71d969aa4802c2a24a47d2
# good: [e0f90f86e9e73668efd7c71fe473db4c318d6798] procs: add changelog to meta
git bisect good e0f90f86e9e73668efd7c71fe473db4c318d6798
# good: [90982af6a14f75b148f98ac6cc09c569b14c0b61] rust-analyzer: 2021-08-23 -> 2021-08-30
git bisect good 90982af6a14f75b148f98ac6cc09c569b14c0b61
# bad: [0afbd6c86a29160386e5386332b65ba707a25340] libredirect: Enable debug symbols
git bisect bad 0afbd6c86a29160386e5386332b65ba707a25340
# bad: [5ca02655057bb568f09b3aed4acee44e3f805291] libredirect: Add missing phase hooks
git bisect bad 5ca02655057bb568f09b3aed4acee44e3f805291
# first bad commit: [5ca02655057bb568f09b3aed4acee44e3f805291] libredirect: Add missing phase hooks
```
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 144653` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python38Packages.oslo-concurrency</li>
    <li>python38Packages.oslo-log</li>
    <li>python38Packages.python-manilaclient</li>
    <li>python38Packages.subunit2sql</li>
    <li>python38Packages.swift</li>
    <li>python38Packages.tempest</li>
    <li>python39Packages.oslo-concurrency</li>
    <li>python39Packages.oslo-log</li>
    <li>python39Packages.python-manilaclient</li>
    <li>python39Packages.subunit2sql</li>
    <li>python39Packages.swift</li>
    <li>python39Packages.tempest</li>
  </ul>
</details>
<details>
  <summary>29 packages built:</summary>
  <ul>
    <li>libredirect</li>
    <li>openstackclient (python39Packages.python-openstackclient)</li>
    <li>python38Packages.keystoneauth1</li>
    <li>python38Packages.openstacksdk</li>
    <li>python38Packages.osc-lib</li>
    <li>python38Packages.oslo-db</li>
    <li>python38Packages.oslo-serialization</li>
    <li>python38Packages.oslo-utils</li>
    <li>python38Packages.python-cinderclient</li>
    <li>python38Packages.python-glanceclient</li>
    <li>python38Packages.python-heatclient</li>
    <li>python38Packages.python-ironicclient</li>
    <li>python38Packages.python-keystoneclient</li>
    <li>python38Packages.python-novaclient</li>
    <li>python38Packages.python-openstackclient</li>
    <li>python38Packages.python-swiftclient</li>
    <li>python39Packages.keystoneauth1</li>
    <li>python39Packages.openstacksdk</li>
    <li>python39Packages.osc-lib</li>
    <li>python39Packages.oslo-db</li>
    <li>python39Packages.oslo-serialization</li>
    <li>python39Packages.oslo-utils</li>
    <li>python39Packages.python-cinderclient</li>
    <li>python39Packages.python-glanceclient</li>
    <li>python39Packages.python-heatclient</li>
    <li>python39Packages.python-ironicclient</li>
    <li>python39Packages.python-keystoneclient</li>
    <li>python39Packages.python-novaclient</li>
    <li>swiftclient (python39Packages.python-swiftclient)</li>
  </ul>
</details>

**Comment by stephank** [comment]
> I ran `git bisect` on `libredirect` on darwin, below is the results. First bad commit is [5ca0265](https://github.com/NixOS/nixpkgs/commit/5ca02655057bb568f09b3aed4acee44e3f805291)

@siraben The commit before this also fails with me, but was cached. Were you testing with `nix-build --check`?

Both fixes in this PR are for issues caused by newer macOS versions. I expect the cached build was produced on an older macOS builder.

> 12 packages failed to build:

I think this is fine? Guessing these are new failures in packages now unblocked.

> I had to look up why the DYLD_INSERT_LIBRARIES thing was necessary at all, so it could probably do with a comment or something.

@risicle Added a comment and rebased the PR. 👍

**Comment by misuzu** [comment]
With `sandbox = false`

Result of `nixpkgs-review pr 144653` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>openstackclient (python39Packages.python-openstackclient)</li>
    <li>python38Packages.oslo-concurrency</li>
    <li>python38Packages.oslo-log</li>
    <li>python38Packages.python-manilaclient</li>
    <li>python38Packages.subunit2sql</li>
    <li>python38Packages.swift</li>
    <li>python38Packages.tempest</li>
    <li>python39Packages.osc-lib</li>
    <li>python39Packages.oslo-concurrency</li>
    <li>python39Packages.oslo-log</li>
    <li>python39Packages.python-heatclient</li>
    <li>python39Packages.python-ironicclient</li>
    <li>python39Packages.python-manilaclient</li>
    <li>python39Packages.subunit2sql</li>
    <li>python39Packages.swift</li>
    <li>python39Packages.tempest</li>
  </ul>
</details>
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>libredirect</li>
    <li>python38Packages.keystoneauth1</li>
    <li>python38Packages.openstacksdk</li>
    <li>python38Packages.osc-lib</li>
    <li>python38Packages.oslo-db</li>
    <li>python38Packages.oslo-serialization</li>
    <li>python38Packages.oslo-utils</li>
    <li>python38Packages.python-cinderclient</li>
    <li>python38Packages.python-glanceclient</li>
    <li>python38Packages.python-heatclient</li>
    <li>python38Packages.python-ironicclient</li>
    <li>python38Packages.python-keystoneclient</li>
    <li>python38Packages.python-novaclient</li>
    <li>python38Packages.python-openstackclient</li>
    <li>python38Packages.python-swiftclient</li>
    <li>python39Packages.keystoneauth1</li>
    <li>python39Packages.openstacksdk</li>
    <li>python39Packages.oslo-db</li>
    <li>python39Packages.oslo-serialization</li>
    <li>python39Packages.oslo-utils</li>
    <li>python39Packages.python-cinderclient</li>
    <li>python39Packages.python-glanceclient</li>
    <li>python39Packages.python-keystoneclient</li>
    <li>python39Packages.python-novaclient</li>
    <li>swiftclient (python39Packages.python-swiftclient)</li>
  </ul>
</details>

**Comment by stephank** [comment]
I think those failing packages are also out of scope here? I tried a few builds, and found some test failures that don't seem related to libredirect, but correct me if I'm wrong.

**Comment by risicle** [comment]
Sorry I should have been more clear, I meant the injection of the extra `DYLD_INSERT_LIBRARIES` in `rewriteSystemCall` being because of the darwin "security" feature.

**Comment by stephank** [comment]
Oh duh, that makes a lot more sense. Fixed again and rebased. 😅

**Review by risicle — APPROVED** [review]

**Pull request merged**
