### PR TITLE
openconnect_pa: remove from nixpkgs

### PR DESCRIPTION
**Pull request by kini**
According to the README on [the website][1], this fork of OpenConnect
is deprecated because the Palo Alto Networks VPN functionality has
been upstreamed into OpenConnect 8.0 and higher.

[1]: https://github.com/dlenski/openconnect

###### Motivation for this change

As mentioned in the commit message, `openconnect_pa` is now deprecated because it's been upstreamed into `openconnect`.

Pinging @chessai, who introduced this package in #50513.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by chessai — APPROVED** [review]

**Comment by chessai** [comment]
Removal is the correct course of action. You are correct

**Comment by kini** [comment]
Thanks. I don't have the permissions necessary to merge this PR, so I'm just waiting for a committer to see it.

**Comment by ajs124** [comment]
There seems to be a merge conflict now, but if you resolve that, I can merge it.

**Comment by kini** [comment]
Thanks for the offer. Unfortunately, it looks like the merge conflict is because PR #123123 duplicates this. That PR got merged in a week while this PR has been sitting around for more than half a year. Just the luck of the draw I guess :roll_eyes:

**Pull request closed without merging**
