### PR TITLE
cargo-generate: 0.21.1 -> 0.21.3

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

[Required to build with Rust 1.80.](https://github.com/rust-lang/rust/issues/127343)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
Backport?

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 333488` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>cargo-generate</li>
  </ul>
</details>

**Comment by turboMaCk** [comment]
It seems the failure here is simple dependecy issue:

```
error: builder for '/nix/store/jr9x8fvwfhxlcpl6jfcnsk146hqk2f2h-cargo-generate-0.21.3.drv' failed with exit code 101;
       last 10 log lines:
       >   HINT: you may need to install a package such as libgit2, libgit2-dev or libgit2-devel.
       >
       >
       >   --- stderr
       >   thread 'main' panicked at /build/cargo-generate-0.21.3-vendor.tar.gz/libgit2-sys/build.rs:39:13:
       >   The environment variable `LIBGIT2_NO_VENDOR` has been set but no compatible system libgit2 could be found.
       >   The build is now aborting. To disable, unset the variable or use `LIBGIT2_NO_VENDOR=0`.
       >
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/jr9x8fvwfhxlcpl6jfcnsk146hqk2f2h-cargo-generate-0.21.3.drv'.
error: 1 dependencies of derivation '/nix/store/jr1l10p1a55gbnwgbp5jyz87mwmcq7zy-review-shell.drv' failed to build
```

Do you want me to resolve this?

**Comment by turboMaCk** [comment]
The problem seems to be with version of libgit2.

pkg-configs is looking for:

```
libgit2 libgit2 >= 1.8.1 libgit2 < 1.9.0
```

but PKG_CONFIG_PATH (nix-store version) is

```
/nix/store/bi07nywzpydih5v50jldxmc4pihan9fb-libgit2-1.7.2-dev/lib/pkgconfig
```

So we're required to update libgit2 `1.7.2` -> `1.8.1`.

**Comment by turboMaCk** [comment]
I already have branch with the necessary update ready. I can confirm it fixes build failure with cargo-generate too.

Now I'm making sure all downstream packages which depend on libgit2 are compiling. Once I have results I will issue the PR.

**Comment by turboMaCk** [comment]
Some relevant discussion can be found in https://github.com/NixOS/nixpkgs/pull/333660

to make this go smoother, we're introducing new attribute for newer version of libgit2. That way rust updates won't be coupled with unrelated update causing a lot of rebuilds that has to go through staging. libgit2 version was the only blocker for this update as you can see in the linked PR.

**Review by matthiasbeyer — APPROVED** [review]

**Comment by alyssais** [comment]
@turboMaCk we can just merge this into staging-next and not have to worry, right?  (Same with #333495)

**Review by turboMaCk — APPROVED** [review]
@alyssais I see that staging-next already has bump of the libgit2. So lets merge there. I will close the other PR after this one is merged.

**Pull request merged**
