### PR TITLE
Kernels 2021-12-01

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabianhjr — APPROVED** [review]
Been on 5.15.5 for a day.

**Comment by lorenz** [comment]
I recommend skipping 5.15.5 because of https://lore.kernel.org/all/CAGnHSEmkTyq_QqP9S6TemsHOKxj2Gzq3R7X6+PxbQs_R-iBB7Q@mail.gmail.com/T/. The fix will be in 5.15.6.

**Review by fabianhjr — APPROVED** [review]
Diff LGTM
Built and booted into 5.15.6

```
> cat /proc/version
Linux version 5.15.6 (nixbld@localhost) (gcc (GCC) 10.3.0, GNU ld (GNU Binutils) 2.35.2) #1-NixOS SMP Wed Dec 1 08:04:57 UTC 2021
```

**Review by ivan — APPROVED** [review]
5.10.83-hardened1 is working for me on x86_64 NixOS 21.11

**Review by NeQuissimus — APPROVED** [review]

**Comment by TredwellGit** [comment]
Please go ahead and merge this if you have the time.

**Pull request merged**
