### PR TITLE
go-task: 3.38.0 -> 3.39.2

### PR DESCRIPTION
**Pull request by trim21**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by infinisil** [comment]
Please ignore the codeowner check failure, see https://github.com/NixOS/nixpkgs/pull/336261#issuecomment-2400822729 for context

**Comment by trim21** [comment]
is there a document how hash and vendorHash are calculated? Looks like it's not `base64(sha256())` of content of `refs/tags/v${version}.tar.gz` or`go.mod`

**Comment by SuperSandro2000** [comment]
Just run go mod update on the package.

> is there a document how hash and vendorHash are calculated? Looks like it's not base64(sha256()) of content of refs/tags/v${version}.tar.gz or go.mod

It is the nix hashed output of go mod vendor in a directory.

**Comment by trim21** [comment]
> Just run go mod update on the package.
> 
> >

do you mean `go mod vendor` ?

**Comment by trim21** [comment]
sorry, I close this PR by accident

**Comment by SuperSandro2000** [comment]
> > Just run go mod update on the package.
> > >
> 
> do you mean `go mod vendor` ?

I meant nix-update https://github.com/Mic92/nix-update but probably got distracted while writting

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by trim21** [comment]
> > > Just run go mod update on the package.
> > > >
> > 
> > 
> > do you mean `go mod vendor` ?
> 
> I meant nix-update https://github.com/Mic92/nix-update but probably got distracted while writting

It's actually just `go mod vendor` and `nix hash path ./vendor`

**Comment by Ramblurr** [comment]
```

error: builder for '/nix/store/ax5di1cill14lmvbaksdldhvxbp7l8y7-go-task-3.39.2-go-modules.drv' failed with exit code 1;
       last 10 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/w611p6wgzs5x0zvs68w6yzxzlv6kkdnq-source
       > source root is source
       > Running phase: patchPhase
       > applying patch /nix/store/y5jgbbdi3jwpaidyq3yf9cn8spf0507q-fix-ldflags-version.patch
       > patching file internal/version/version.go
       > Reversed (or previously applied) patch detected!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 1 out of 1 hunk ignored -- saving rejects to file internal/version/version.go.rej
       For full logs, run 'nix log /nix/store/ax5di1cill14lmvbaksdldhvxbp7l8y7-go-task-3.39.2-go-modules.drv'.
```

Just bumped nixos unstable in my flake, and I am getting this build error.

**Pull request merged**
