### PR TITLE
nix-index: Add mainProgram

### PR DESCRIPTION
**Pull request by Pandapip1**
## Description of changes

Adds `mainProgram` to `nix-index`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
`nix-locate` seems like it might be more appropriate choice? Though really you need both.

**Comment by eclairevoyant** [comment]
Yeah I definitely don't agree with this PR, nix-locate is really the "main program" of this package, and as mentioned, you'd need `nix-index` to generate the DB (or use `nix-index-database` for a pregenerated DB).
I'd rather say we don't set it at all for this package.

**Comment by Pandapip1** [comment]
> `nix-locate` seems like it might be the more appropriate choice? Though really you need both.

Huh, I thought that was a separate package.

**Comment by eclairevoyant** [comment]
> I thought that was a separate package.

```
$ ls $(nix build nixpkgs#nix-index --print-out-paths --no-link)/bin
nix-channel-index  nix-index  nix-locate
```

**Comment by Pandapip1** [comment]
Yea, no, I checked and nix-locate is in there. It's just weird that two independent (i.e. one isn't a dependency of another) are packaged together.

**Comment by emilazy** [comment]
They’re not independent. The purpose of `nix-index` is to create a database for `nix-locate` to query.

**Comment by Pandapip1** [comment]
> The purpose of `nix-index` is to create a database for `nix-locate` to query.

I recognize this, but there are prebuilt nix indexes (which would remove the need to install `nix-index`), and there are also programs that depend on having a nix index but don't need nix-locate (such as `comma`).

**Pull request closed without merging**
