### PR TITLE
NAnt

### PR DESCRIPTION
**Pull request by zohl**
This patch adds NAnt, a builder for dotnet projects.

There is two-step building process:
1) build NAnt with make (nant-bootstrapped)
2) build NAnt with NAnt

While the first step is ok, the second one throws errors.

One of the problem, `gmcs not found`, can be fixed by symlinking `mcs`. There is another way (e.g. see library Hyena), but this will require to patch every project which uses `gmcs`.

Another one is where I stumped. NAnt failed with message:
`
[resgen] Cannot open assembly '/nix/store/...-mono-4.0.4.1/lib/mono/2.0/resgen.exe': No such file or directory.
`
As far as I understand it can be fixed by providing MONO_GAC_PREFIX. But, indeed, there is no such file.
I compiled NAnt in a clean debian with no problem. There is `mono-complete` package that provides this executable image. Could it be a missing file in nix's `mono` package?

Seeking for advice, as I' not familiar with dotnet things.

### CODE REVIEW

**Comment by abbradar** [comment]
Have you tried compiling it with `mono = mono-complete`? I think this is just `mono` with additional stuff added.

**Comment by zohl** [comment]
The problem is that `mono-complete` is a debian package :smile:

**Comment by abbradar** [comment]
Second guess: you specify `mono-2.0` as `nant` target in `buildPhase`. Why not `mono-4.5`?

**Comment by zohl** [comment]
It can be built against `mono-2.0`, `mono-3.5` and `mono-4.0`, but each of them throws the same error. The other framework's versions do not supported.

I would sed all the files to substitute for example `4.0` to `4.5`, but it looks like some binary files are also specify their supported versions.
And of course I already tried a "dirty" solution with symlinking `mono/*/resgen.exe` to `4.5/resgen.exe`. That didn't succeed too.

**Comment by zohl** [comment]
It turned out that the latest version supports `mono-4.5`. Moreover, this version of nant also can be built against `mono-2.0` without problems.

**Comment by abbradar** [comment]
Another round of nitpicks! Sorry for not going through all the package more closely first time.

**Comment by zohl** [comment]
Done, fixed everything according to your comments.

**Comment by abbradar** [comment]
Thanks! This doesn't feel like a mass rebuild to me -- let's merge this to `master`.

**Pull request merged**
