### PR TITLE
python3Packages.afdko: 3.9.3 -> 3.9.7

### PR DESCRIPTION
**Pull request by h7x4**
## Description of changes

Depends on https://github.com/NixOS/nixpkgs/pull/249201

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
> Depends on #249201

Then I'd suggest making both changes part of the same PR.

**Comment by h7x4** [comment]
How does one go about doing that? Should I create my own PR, or ask the owner of the other PR to add it to theirs?

**Comment by sternenseemann** [comment]
You are the author of the other PR?

**Comment by sternenseemann** [comment]
Ah, I thought it was the fonttools PR. I think we probably want to have all three updates in a single-ish PR anyways.

**Comment by pbsds** [comment]
https://github.com/NixOS/nixpkgs/pull/249201 is merged as of #251878. Current status: https://nixpk.gs/pr-tracker.html?pr=251878

**Comment by sternenseemann** [comment]
We can just target staging-next with this, the rebuild seems reasonably small.

**Comment by h7x4** [comment]
@sternenseemann, I changed target to staging-next

**Comment by NickCao** [comment]
Superseded by https://github.com/NixOS/nixpkgs/commit/fae629edac597cd3261445e0b2e97a33335e6a4c

**Pull request closed without merging**
