### PR TITLE
Xfce 4.20

### PR DESCRIPTION
**Pull request by bobby285271**
This updates Xfce to 4.20, [released on Dec 15th](https://xfce.org/about/news/?post=1734220800).

- Wayland session is still [experimental](https://wiki.xfce.org/releng/wayland_roadmap) and requires opt-in using `enableWaylandSession` option.
- Overriding Wayland compositor is possible using `waylandSessionCompositor` option, but you might need to take care [`xfce4-session`](https://gitlab.xfce.org/xfce/xfce4-session/-/merge_requests/49), [`dbus-update-activation-environment`](https://github.com/labwc/labwc/blob/eaf11face68ee1f1bcc7ce1498304ca8c108c8ba/src/config/session.c#L234) and [`systemctl --user import-environment`](https://github.com/labwc/labwc/blob/eaf11face68ee1f1bcc7ce1498304ca8c108c8ba/src/config/session.c#L239) on startup.
- For new Xfce installations, default panel layout has [changed](https://gitlab.xfce.org/xfce/xfce4-panel/-/merge_requests/158/diffs) to not include external panel plugins by default. You can still add them yourself using the "Panel Preferences" dialog.

### Todos

- [x] [Fix plugin "(null)" could not be loaded issue](https://gitlab.xfce.org/xfce/xfce4-panel/-/merge_requests/155).
- [x] [Fix xfce-wayland + lightdm setup](https://gitlab.xfce.org/xfce/xfce4-session/-/merge_requests/68).
- Make sure everything matches [what the wayland roadmap says](https://wiki.xfce.org/releng/wayland_roadmap).
  - [x] xfce4-pulseaudio-plugin libxfce4windowing support.
  - [x] xfce4-docklike-plugin libxfce4windowing support.
- [x] Wait for Budgie desktop fixes for libxfce4windowing.
- [x] Wait for the actual release.
- [x] Write release notes.

### CODE REVIEW

**Comment by bobby285271** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353048`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>xmonad_log_applet_xfce</li>
  </ul>
</details>
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 124 packages built:</summary>
  <ul>
    <li>budgie-analogue-clock-applet</li>
    <li>budgie-control-center</li>
    <li>budgie-control-center.debug</li>
    <li>budgie-desktop</li>
    <li>budgie-desktop-with-plugins</li>
    <li>budgie-desktop.dev</li>
    <li>budgie-desktop.man</li>
    <li>budgie-gsettings-overrides</li>
    <li>budgie-user-indicator-redux</li>
    <li>caffeine-ng</li>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
    <li>greybird</li>
    <li>lightdm-gtk-greeter</li>
    <li>pragha</li>
    <li>xfce.catfish</li>
    <li>xfce.catfish.dist</li>
    <li>xfce.exo</li>
    <li>xfce.exo.dev</li>
    <li>xfce.garcon</li>
    <li>xfce.garcon.dev</li>
    <li>xfce.gigolo</li>
    <li>xfce.gigolo.dev</li>
    <li>xfce.libxfce4ui</li>
    <li>xfce.libxfce4ui.dev</li>
    <li>xfce.libxfce4util</li>
    <li>xfce.libxfce4util.dev</li>
    <li>xfce.libxfce4windowing</li>
    <li>xfce.libxfce4windowing.dev</li>
    <li>xfce.mousepad</li>
    <li>xfce.mousepad.dev</li>
    <li>xfce.orage</li>
    <li>xfce.orage.dev</li>
    <li>xfce.parole</li>
    <li>xfce.parole.dev</li>
    <li>xfce.ristretto</li>
    <li>xfce.ristretto.dev</li>
    <li>xfce.thunar</li>
    <li>xfce.thunar-archive-plugin</li>
    <li>xfce.thunar-archive-plugin.dev</li>
    <li>xfce.thunar-dropbox-plugin</li>
    <li>xfce.thunar-media-tags-plugin</li>
    <li>xfce.thunar-media-tags-plugin.dev</li>
    <li>xfce.thunar-volman</li>
    <li>xfce.thunar-volman.dev</li>
    <li>xfce.thunar.dev</li>
    <li>xfce.tumbler</li>
    <li>xfce.tumbler.dev</li>
    <li>xfce.xfburn</li>
    <li>xfce.xfburn.dev</li>
    <li>xfce.xfce4-appfinder</li>
    <li>xfce.xfce4-appfinder.dev</li>
    <li>xfce.xfce4-battery-plugin</li>
    <li>xfce.xfce4-battery-plugin.dev</li>
    <li>xfce.xfce4-clipman-plugin</li>
    <li>xfce.xfce4-clipman-plugin.dev</li>
    <li>xfce.xfce4-cpufreq-plugin</li>
    <li>xfce.xfce4-cpufreq-plugin.dev</li>
    <li>xfce.xfce4-cpugraph-plugin</li>
    <li>xfce.xfce4-cpugraph-plugin.dev</li>
    <li>xfce.xfce4-datetime-plugin</li>
    <li>xfce.xfce4-datetime-plugin.dev</li>
    <li>xfce.xfce4-dev-tools</li>
    <li>xfce.xfce4-dict</li>
    <li>xfce.xfce4-dict.dev</li>
    <li>xfce.xfce4-dockbarx-plugin</li>
    <li>xfce.xfce4-docklike-plugin</li>
    <li>xfce.xfce4-docklike-plugin.dev</li>
    <li>xfce.xfce4-eyes-plugin</li>
    <li>xfce.xfce4-fsguard-plugin</li>
    <li>xfce.xfce4-genmon-plugin</li>
    <li>xfce.xfce4-i3-workspaces-plugin</li>
    <li>xfce.xfce4-mailwatch-plugin</li>
    <li>xfce.xfce4-mpc-plugin</li>
    <li>xfce.xfce4-netload-plugin</li>
    <li>xfce.xfce4-netload-plugin.dev</li>
    <li>xfce.xfce4-notes-plugin</li>
    <li>xfce.xfce4-notes-plugin.dev</li>
    <li>xfce.xfce4-notifyd</li>
    <li>xfce.xfce4-notifyd.dev</li>
    <li>xfce.xfce4-panel</li>
    <li>xfce.xfce4-panel-profiles</li>
    <li>xfce.xfce4-panel.dev</li>
    <li>xfce.xfce4-power-manager</li>
    <li>xfce.xfce4-power-manager.dev</li>
    <li>xfce.xfce4-pulseaudio-plugin</li>
    <li>xfce.xfce4-pulseaudio-plugin.dev</li>
    <li>xfce.xfce4-screensaver</li>
    <li>xfce.xfce4-screensaver.dev</li>
    <li>xfce.xfce4-screenshooter</li>
    <li>xfce.xfce4-screenshooter.dev</li>
    <li>xfce.xfce4-sensors-plugin</li>
    <li>xfce.xfce4-session</li>
    <li>xfce.xfce4-session.dev</li>
    <li>xfce.xfce4-settings</li>
    <li>xfce.xfce4-settings.dev</li>
    <li>xfce.xfce4-systemload-plugin</li>
    <li>xfce.xfce4-taskmanager</li>
    <li>xfce.xfce4-taskmanager.dev</li>
    <li>xfce.xfce4-terminal</li>
    <li>xfce.xfce4-terminal.dev</li>
    <li>xfce.xfce4-time-out-plugin</li>
    <li>xfce.xfce4-time-out-plugin.dev</li>
    <li>xfce.xfce4-timer-plugin</li>
    <li>xfce.xfce4-verve-plugin</li>
    <li>xfce.xfce4-verve-plugin.dev</li>
    <li>xfce.xfce4-volumed-pulse</li>
    <li>xfce.xfce4-volumed-pulse.dev</li>
    <li>xfce.xfce4-weather-plugin</li>
    <li>xfce.xfce4-whiskermenu-plugin</li>
    <li>xfce.xfce4-whiskermenu-plugin.dev</li>
    <li>xfce.xfce4-windowck-plugin</li>
    <li>xfce.xfce4-xkb-plugin</li>
    <li>xfce.xfce4-xkb-plugin.dev</li>
    <li>xfce.xfconf</li>
    <li>xfce.xfconf.dev</li>
    <li>xfce.xfdashboard</li>
    <li>xfce.xfdashboard.dev</li>
    <li>xfce.xfdesktop</li>
    <li>xfce.xfdesktop.dev</li>
    <li>xfce.xfmpc</li>
    <li>xfce.xfmpc.dev</li>
    <li>xfce.xfwm4</li>
    <li>xfce.xfwm4.dev</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
@ofborg test xfce xfce-wayland budgie

* If you wish to test this PR, feel free to do.
* If you already tested pre2, the only non-trivial change since pre2 is [xfdesktop 4.19.7 -> 4.20.0](https://gitlab.xfce.org/xfce/xfdesktop/-/compare/xfdesktop-4.19.7...xfdesktop-4.20.0).

**Comment by Yarny0** [comment]
#### Review per https://github.com/NixOS/nixpkgs/tree/3566ab7246670a43abd2ffa913cc62dad9cdf7d5/pkgs#package-updates

##### Reviewed points

- [ ] package name fits guidelines
- [ ] package version fits guidelines
- [x] package builds on *x86-64*
- [x] executables tested on *x86-64*
- [ ] all depending packages build
- [ ] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [ ] patches that are remotely available are fetched rather than vendored

More:

- [x] desktop looks good
- [x] thunar looks good
- [x] xfce terminal looks good
- [x] panel plugins `applicationsmenu`, `launcher`, `pager`, `xfce4-verve-plugin`, `tasklist`, `systray`, `xfce4-clipman-plugin`, `pulseaudio`, `xkb`, `cpugraph`, `systemload`, `datetime`, `actions` look alright and are able to perform their basic actions

##### Comments

*   Everything tested after rebasing the branch onto [recent `nixos-unstable`](https://github.com/NixOS/nixpkgs/commit/3566ab7246670a43abd2ffa913cc62dad9cdf7d5).

*   It seems that the workspace background settings got broken with this update: When selecting a wallpaper file and leaving the checkbox "Apply to all workspaces" ticked, the change is only applied to the first workspace, the other workspaces still sport the default image with the Xfce mouse.  Deselecting the checkbox is needed to change the wallpaper of other workspaces.

    I found https://gitlab.xfce.org/xfce/xfdesktop/-/issues/294 and https://gitlab.xfce.org/xfce/xfdesktop/-/merge_requests/126 ; they might be related to the problem, but I haven't had enough time to investigate further.

*   In any case, that bug should not be a blocker.  I haven't found any further issues, let alone any serious bugs.  I approve and recommend merging the pull request at hand.

*   @bobby285271 , thank you for preparing this! As an Xfce user, I really appreciate your work!

**Review by romildo — APPROVED** [review]
Changes look good to me, and the system works well for me.

**Comment by bobby285271** [comment]
Thanks all for testing!

> It seems that the workspace background settings got broken...

I cannot produce the issue yet, but yeah https://gitlab.xfce.org/xfce/xfdesktop/-/issues/294 provides good idea on how to debug this, i.e. monitor xfconf changes with `xfconf-query -c xfce4-desktop -mv` and probably figure out whether there is a `single_workspace` that is `false` for you.

**Pull request merged**
