### PR TITLE
[21.05] element-{web,desktop}: 1.8.4 -> 1.8.5

### PR DESCRIPTION
**Pull request by sumnerevans**
###### Motivation for this change

(cherry picked from commit 04732d7c56c72a5cbb12355df5701d06b971cece)

See https://github.com/NixOS/nixpkgs/pull/137869

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sumnerevans** [comment]
Really sorry for the ping everyone.

**Comment by Ma27** [comment]
@ofborg eval

**Review by jonringer — COMMENTED** [review]
looks like were are missing a commit which enables darwin support:

```
nonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/ofborg-evaluator-1/pkgs/applications/networking/instant-messengers/element/element-desktop.nix:1:1 called without required argument 'Security', at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/ofborg-evaluator-1/lib/customisation.nix:69:16
```

**Comment by Ma27** [comment]
Ah yes, it doesn't even evaluate when doing a `nix-build`. Pushed a fix.

**Comment by sumnerevans** [comment]
Thanks for fixing this. Was traveling so I didn't have time to look into it.

**Pull request merged**
