### PR TITLE
fetchFromGitHub: fix meta

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Useful for packages which are just the fetcher. (e.g. cabin, fonts)

related:
- https://github.com/repology/repology-updater/pull/1225
- https://github.com/NixOS/nixpkgs/pull/158548#issuecomment-1033877175

Also, to reduce noise in: https://repology.org/log/10558694

before:
```
$ nix eval .#cabin.meta
{ homepage = "https://github.com/impallari/Cabin"; }
```

after:
```
nix-repl> cabin.meta
{ description = "A humanist sans with 4 weights and true italics"; homepage = "http://www.impallari.com/cabin"; license = { ... }; longDescription = "The Cabin font family is a humanist sans with 4 weights and true italics,\ninspired by Edward Johnston’s and Eric Gill’s typefaces, with a touch of\nmodernism. Cabin incorporates modern proportions, optical adjustments, and\nsome elements of the geometric sans. It remains true to its roots, but has\nits own personality.\n\nThe weight distribution is almost monotone, although top and bottom curves\nare slightly thin. Counters of the b, g, p and q are rounded and optically\nadjusted. The curved stem endings have a 10 degree angle. E and F have\nshorter center arms. M is splashed.\n"; maintainers = [ ... ]; platforms = [ ... ]; position = "/home/jon/projects/nixpkgs/pkgs/data/fonts/cabin/default.nix:19"; }
```

tangentially related: #158850

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
Weird, this was 0 rebuilds on aarch64-darwin:

```
$ nix-env --option system aarch64-darwin -f /Users/jon/.cache/nixpkgs-review/pr-158844/nixpkgs -qaP --xml --out-path --show-trace --meta
Nothing to be built.

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/158844

$ nix-shell /Users/jon/.cache/nixpkgs-review/pr-158844/shell.nix
```

**Comment by jonringer** [comment]
cc @siraben , how also tries to clean up repology errors

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 158844` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by siraben** [comment]
That's strange. What are the rebuilds on `x86_64-darwin`?

**Review by grahamc — APPROVED** [review]
Looks good to me.

**Pull request merged**
