### PR TITLE
pkgs/uwsgi: fix compiling and linking the php plugin in uwsgi

### LINKED ISSUE #97352: uwsgi with php plugin doesn't compile
**Describe the bug**
when enabling the php plugin in the uwsgi package the compile of the plugin fails.

**To Reproduce**
1. `nix-build -E 'with import <nixpkgs> {}; uwsgi.override { plugins=[ "php" ]; }'`

**Screenshots**
```
*** uWSGI is ready, launch it with ./uwsgi ***
using profile: buildconf/nixos.ini
detected include path: ['/nix/store/vb1fh8zqdcs7n3hvn8awlrpdfnic6zjg-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include', '/nix/store/vb1fh8zqdcs7n3hvn8awlrpdfnic6zjg-gcc-9.3.0/include', '/nix/store/vb1fh8zqdcs7n3hvn8awlrpdfnic6zjg-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include-fixed', '/nix/store/vbs3xx1b5i5bzf1sjkz2lkmz7b8cy92y-glibc-2.30-dev/include']
*** uWSGI building and linking plugin plugins/php ***
/bin/sh: php-config: not found
/bin/sh: php-config: not found
/bin/sh: php-config: not found
/bin/sh: php-config: not found
[gcc] /nix/store/yjg3pdnwgynl1sz9rkc5gyjcgjamgfi9-uwsgi-2.0.18/lib/uwsgi/php_plugin.so
In file included from plugins/php/php_plugin.c:1:
plugins/php/common.h:1:10: fatal error: php.h: No such file or directory
    1 | #include "php.h"
      |          ^~~~~~~
compilation terminated.
In file included from plugins/php/session.c:1:
plugins/php/common.h:1:10: fatal error: php.h: No such file or directory
    1 | #include "php.h"
      |          ^~~~~~~
compilation terminated.
*** unable to build php plugin ***
```

**Additional context**

The uwsgi build system tries to invoke `php-config` to get the include paths for the compile, but php-config is not in the path (it's in the php.dev package). This can be fixed by setting the `UWSGICONFIG_PHPDIR = "${php-embed.unwrapped.dev}";` environment variable. uwsgi then finds `php.h`, but fails on `#include "ext/session/php_session.h"` which is in `extensions.session.dev`, and under a different path in the store.

https://github.com/unbit/uwsgi/blob/master/plugins/php/common.h
https://github.com/unbit/uwsgi/blob/master/plugins/php/uwsgiplugin.py

I'll try to find a better solution next.

**Notify maintainers**
@abbradar @schneefux @globin

**Metadata**
Maintainer information:
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.7-arch1-1, Alpine Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixpkgs-20.09pre228453.dcb64ea42e6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by gdamjan**
###### Motivation for this change

fixes #97352 - it enables the use of the php plugin of uwsgi.

###### Things done

I tested in a nixos docker container, on ArchLinux host:

```sh
$ docker run -ti --rm -v ~/src/nixpkgs:/nixpkgs nixos/nix:latest
# nix-build -E 'with import <nixpkgs> {}; uwsgi.override { plugins=[ "php" ]; }' # fails as specified in the bug 97352

# NIX_PATH=nixpkgs=/nixpkgs nix-build -E 'with import <nixpkgs> {}; uwsgi.override { plugins=[ "php" ]; }' # works
```

###### Explanation of the changes

The root of the problem is that uwsgi has a bit of a different build system, and it would expect to find the `php-config` binary in order to set it's compiler and linker flags. There was an additional problem that the uwsgi-php plugin needs to also link with the `session.so` php extension - which on NixOS is a separate package¹.

The first problem was solved by adding all the required `buildInputs` to the uwsgi package so that it can find all the needed header files, libraries and to have php-config in its PATH.

I also had to patch uwsgi to **not** look for `php_session.h` with a path like this `#include "ext/session/php_session.h"`, since on NixOS it's just in `…php-session-7.4.8-dev/include`.

Third, I had to patch the uwsgi build system for the php plugin to explicitly add the `session.so` library and its rpath to `LDFLAGS`. In the nix expression that's exported as the UWSGICONFIG_PHP_LDFLAGS environment variable. It's important that these flags are not used for the main uwsgi binary, but just for the php-plugin shared object.

¹ not sure why the session extension is separated on NixOS, it's builtin in libphp.so on both Debian/Ubuntu and ArchLinux - something to be discussed by the PHP team i guess.

ps.
this is my first involvement with the NixOS project, so I'm open to any criticism and suggestions.

### CODE REVIEW

**Comment by gdamjan** [comment]
updated after the borked PR #97536

**Comment by azazel75** [comment]
@rnhmjoj Do you know if this fil be merged with 20.09 as well? I find  it always difficult to understand that

**Comment by rnhmjoj** [comment]
The backport process to stable branches (20.09 now) is manual and the policy is to only backport security or bug fixes.
This PR is technically fixing PHP supports, but it's really adding a new feature and does non-trivial changes to uwsgi: I don't think it's a good idea to backport it.

If you need it, you could pick the uwsgi package from the unstable channel while staying on 20.09. I can't find a guide or example right know, if you're interested I can explain it to you.

**Comment by azazel75** [comment]
> The backport process to stable branches (20.09 now) is manual and
    > the policy is to only backport security or bug fixes.  This PR is
    > technically fixing PHP supports, but it's really adding a new
    > feature and does non-trivial changes to uwsgi: I don't think it's
    > a good idea to backport it.

A new feature? It just fixes something that worked like a charm in 20.03 and
is broken in 20.09, it doesn't add any new functionality. It isn't a
new, incompatible, release of uwsgi. If you don't need the PHP module
nothing will change for you.

    > If you need it, you could pick the uwsgi package from the unstable
    > channel while staying on 20.09. I can't find a guide or example right
    > know, if you're interested I can explain it to you.

There's no need, thanks. I just wanted me to save the hassle of using PHP
and other plugins from unstable.

-- 
Alberto Berti  -  Information Technology Consultant
PGP: 9377 A68C C5B5 B534 36BD  F20B E3B5 C559 99D6 7CF9

            "gutta cavat lapidem"

**Comment by rnhmjoj** [comment]
> A new feature? It just fixes something that worked like a charm in 20.03 and
is broken in 20.09, it doesn't add any new functionality. It isn't a
new, incompatible, release of uwsgi. If you don't need the PHP module
nothing will change for you.

You're right, I wasn't aware the php was there before this PR...
It should be backported, then. I'll open a PR for this soon.

**Comment by gdamjan** [comment]
I can make a PR against release-20.09 too (I believe I already have a branch).

I personally do believe this needs to be fixed in 20.09, since it's the difference between completely not working and fixed :)

**Comment by gdamjan** [comment]
> I can make a PR against release-20.09 too (I believe I already have a branch).

https://github.com/NixOS/nixpkgs/pull/107792

**Pull request merged**
