### PR TITLE
ghc: support Apple Silicon on head/9.2.1

### PR DESCRIPTION
**Pull request by domenkozar**
Untested.

According to https://www.haskell.org/ghc/blog/20210309-apple-m1-story.html, we're waiting on GHC 9.0.2 release.

### CODE REVIEW

**Comment by sternenseemann** [comment]
I'd like to keep the GHC 8.10.2 bindist until

* We know that GHC 8.10.7 is finally a *good* release and we have a bindist for that version
* We have debugged and fixed `pkgsMusl.ghc` and made sure it also bootstraps fine on musl with `ghc8105Binary` / `ghc8107Binary` (which we can't really do atm), I think we owe this to @nh2 who has poured significant time and effort into `ghc8102Binary` to make sure it works in a variety of scenarios

Also of course not upgrading the binary GHC would make merging this PR much more of a no-brainer as no set rebuild would be required for any platform other than `aarch64-darwin`.

**Comment by domenkozar** [comment]
That sounds good, I don't think we're in particular hurry to merge this PR so let's make sure all those things check first.

**Comment by domenkozar** [comment]
`pkgsMusl.ghc` builds fine on this branch!

**Comment by sternenseemann** [comment]
I think this has all been done independently now; Current master *should* have 9.2.1 with `aarch64-darwin` support, testing would be appreciated cc @prusnak @domenkozar

**Comment by prusnak** [comment]
Unfortunately it does not work for me (master b31c4628c244ef11b74d82edfd87b580a18b0f0b)

```
$ nix-shell -p haskell.compiler.ghc921
> ghc --version
Killed: 9
```

**Comment by sternenseemann** [comment]
Can you check `log(1)` for what's going on? Maybe we need to copy over some codesigning hacks.

**Comment by prusnak** [comment]
> Can you check `log(1)` for what's going on? Maybe we need to copy over some codesigning hacks.

I know what is going on. Lots of fixes that have been done for `ghc/8.10.7.nix` have not been applied for `ghc/9.2.1.nix`. Sent a PR here with the hotfix here (and couple of other smaller changes): https://github.com/NixOS/nixpkgs/pull/145128

Currently, the situation with `pkgs/development/compilers/ghc/*.nix` is a little bit messy, because there is lots of copy-pasta going on and it would be very nice if things were abstracted into one common.nix file, but I guess noone has time to do this properly.

**Comment by sternenseemann** [comment]
> Currently, the situation with `pkgs/development/compilers/ghc/*.nix` is a little bit messy, because there is lots of copy-pasta going on and it would be very nice if things were abstracted into one common.nix file, but I guess noone has time to do this properly.

See #123599. Big problem is that some stuff is (quite) different, e. g. integer-simple vs. ghc-bignum. Overall it's probably a matter of lacking time and motivation.

**Comment by domenkozar** [comment]
Thanks y'all :)

**Pull request closed without merging**
