### PR TITLE
Jetbrains updates

### PR DESCRIPTION
**Pull request by averelld**
###### Motivation for this change

Various updates via script. Only idea has been tested.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by andir** [comment]
Thank your for taking care of this :+1:.

It is probably a bit picky but usually a commit should use the proper attribute names of an expression. In your case the commits are missing the prefix `jetbrains.`. 

Besides that they all are valid and install just fine.

**Review by andir — CHANGES_REQUESTED** [review]
Please add the `jetbrains.` prefix to the commit messages.

**Review by edwtjo — APPROVED** [review]
LGTM, Thanks!

**Comment by Mic92** [comment]
Same problem as in my [pull request](https://github.com/NixOS/nixpkgs/pull/37328):
webstorm does not start:

```
$ webstorm
Start Failed: Internal error. Please report to http://jb.gg/ide/critical-startup-errors
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.intellij.ide.Bootstrap.main(Bootstrap.java:39)
        at com.intellij.idea.Main.main(Main.java:78)
Caused by: java.lang.UnsatisfiedLinkError: /nix/store/v39g3hkkkvzv620xgs3dwikjzm6mg0wg-webstorm-2017.3.5/webstorm-2017.3.5/jre64/lib/amd64/libawt_xawt.so: libXext.so.6: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at java.awt.Toolkit$3.run(Toolkit.java:1636)
        at java.awt.Toolkit$3.run(Toolkit.java:1634)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
        at java.awt.Cursor.<clinit>(Cursor.java:195)
        at javax.swing.text.html.HTMLEditorKit.<clinit>(HTMLEditorKit.java:623)
        at com.intellij.util.ui.UIUtil.<clinit>(UIUtil.java:102)
        at com.intellij.ide.plugins.PluginManager.start(PluginManager.java:78)
        ... 6 more
Also, an UI exception occurred on attempt to show above message:
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at java.awt.Component.<clinit>(Component.java:594)
        at com.intellij.idea.Main.showMessage(Main.java:172)
        at com.intellij.idea.Main.showMessage(Main.java:148)
        at com.intellij.idea.Main.main(Main.java:81)
```

Why are you merging pull requests that do not even pass a simple test if the program starts?

**Comment by Mic92** [comment]
webstorm was fixed in b9b08f8a093e8981121697fbdf61bfd714acd6cb

**Pull request merged**
