### PR TITLE
ffmpeg: make version part of the interface

### PR DESCRIPTION
**Pull request by Atemu**
## Description of changes
This allows overriders to declare a different ABI. Doing so via overrideAttrs
would not affect the flags in the arguments; effectively retaining the
overridden package's ABI.
See https://github.com/NixOS/nixpkgs/issues/280645 for an instance of that.

By overriding the arguments using

    ffmpeg.override { version = "..."; ... }

the ABI will now be overridden as expected.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

cc @anund

### CODE REVIEW

**Comment by anund** [comment]
Should this reference also be `version`? I don't currently understand how finalAttrs works in this context.
https://github.com/NixOS/nixpkgs/blob/a5ff0757c8aa0b4be88c866d87ee9824dc9a5239/pkgs/development/libraries/ffmpeg/generic.nix#L343-L347

**Review by arthsmn — APPROVED** [review]

**Comment by Atemu** [comment]
I'd almost prefer for it not to be but, really, you should be overriding src anyways if you're overriding the version. The hash won't match anyways.

I guess we could also make hash and src an explicit part of the interface; making it fetch ffmpeg versions from the upstream repo.

**Comment by jopejoe1** [comment]
I think version and src should be part of the interface and hash should be removed from it.

**Comment by Atemu** [comment]
Why?

Having the hash in there has the nice property that one could make the ffmpeg drv build any upstream version by specifying version and hash as an override argument.

**Comment by Atemu** [comment]
(I've overhauled this in a local tree that I'm still having some issues with, drafting for now.)

**Comment by jopejoe1** [comment]
> Why?

I think that having an src part of the interface would make it redundant as with src you could specify any srource and not just versions avaivable upstream.

**Comment by Atemu** [comment]
You could still specify any source if `src` was part of the interface; you'd just override it.

**Pull request closed without merging**
