### PR TITLE
ubuntu-sans{,-mono}: rename from ubuntu_font_family, 0.83 -> 1.004

### PR DESCRIPTION
**Pull request by jopejoe1**
## Description of changes

- ubuntu_font_family got renamed to ubuntu-sans
- got split into mono and regular
- is now a variable font

Development now happens at:

https://github.com/canonical/Ubuntu-Sans-fonts
https://github.com/canonical/Ubuntu-Sans-Mono-fonts

@NixOS/enlightenment, cinnamon team (@bobby285271, @mkg20001) does this break anything for your desktops, as you used the old version of the font, also do you need the mono version too?

@antono do you still want to be the maintainer of ubuntu fonts?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by romildo** [comment]
I do not think ubuntu fonts are really needed for the Enlightenment DE. I did not find any reference to them in the source code. After removing them from the enlightenment module, the DE seems to still work without issues.

I suspect they were added just to provide some set of fonts for the DE, and that they can be removed from the default list of fonts.

**Comment by jopejoe1** [comment]
Removed them from enlightenment, also added a fontconfig alias for cinnamon, which should resolve the issue. If you could please @bobby285271 test that.

**Comment by bobby285271** [comment]
@ofborg test cinnamon

**Comment by bobby285271** [comment]
It looks like nixosTests.cinnamon does not build yet, it sounds like this not how other fontconfig configurations are built. https://github.com/NixOS/nixpkgs/blob/46d3bc293531c209a771802770e7d066686d92c3/nixos/modules/config/fonts/fontconfig.nix#L176

(It looks like ubuntu did ship [both versions](https://packages.ubuntu.com/noble/fonts-ubuntu-classic), I am happy to be listed as maintainer of the old one...)

**Comment by jopejoe1** [comment]
Added ubuntu-classic fonts and made you the maintainer

**Review by drupol — APPROVED** [review]

**Review by drupol — CHANGES_REQUESTED** [review]
LGTM, almost.

Can you pass the new files you're introducing through `nixfmt-rfc-style` ?

**Comment by jopejoe1** [comment]
formatted with rfc-style-formatter

**Review by drupol — APPROVED** [review]
Thank you!

**Pull request merged**
