### PR TITLE
nixos/jupiter: add a kernel jsFile option

### PR DESCRIPTION
**Pull request by jraygauthier**
###### Motivation for this change

Required in order to get haskell syntax highlighting when using ihaskell as a jupyter kernel.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Relates to https://github.com/gibiansky/IHaskell/issues/920 and https://github.com/gibiansky/IHaskell/pull/1027

### CODE REVIEW

**Comment by jraygauthier** [comment]
@aborsu / @sveitser: Does this seems fine to any of you?

**Comment by sveitser** [comment]
I have never used this functionality of jupyter. Happy to test it if you can provide an example.

**Comment by jraygauthier** [comment]
@sveitser Here's the config I use:

```nix
  services.jupyter.enable = true;
  services.jupyter.password = "'sha1:1b961dc713fb:88483270a63e57d18d43cf337e629539de1436ba'";
  services.jupyter.kernels = {
    python3 = let
      env = (pkgs.python3.withPackages (pythonPackages: with pythonPackages; [
        ipykernel
        pandas
        scikitlearn
      ]));
    in {
      displayName = "Python 3 for machine learning";
      argv = [
        "${env.interpreter}"
        "-m"
        "ipykernel_launcher"
        "-f"
        "{connection_file}"
      ];
      language = "python";
      logo32 = env + "/${env.sitePackages}/ipykernel/resources/logo-32x32.png";
      logo64 = env + "/${env.sitePackages}/ipykernel/resources/logo-64x64.png";
    };

    haskell = let
      callPackage = lib.callPackageWith pkgs;
      ihaskell = ./ihaskell-with-pkgs-unstable {};
      ihaskellEnv = ihaskell.ihaskellEnv;
      ihaskellWrapperSh = ihaskell.ihaskellWrapperSh;

    in {
      displayName = "Haskell";
      argv = [
        "${ihaskellWrapperSh}/bin/ihaskell-wrapper"
        "kernel"
        "--ghclib"
        "${ihaskellEnv}/lib/ghc-${ihaskellEnv.version}"
        # "--debug"
        "+RTS"
        "-M3g"
        "-N2"
        "-RTS"
        "{connection_file}"

      ];
      jsFile = ihaskell.ihaskellJsFile;
      logo64 = ihaskell.ihaskellLogo64;
      language = "haskell";
    };
  };
```

with `./ihaskell-with-pkgs-unstable` defined as:

```nix
{ lib }:
  let
    ihaskellNixpkgsCfg = {
      # allowBroken = true;

      packageOverrides = super: let self = super.pkgs; in
        let
            # See pkgs/development/haskell-modules/lib.nix for available helpers.
            overrideCabal = super.haskell.lib.overrideCabal;
            unmarkBroken = drv: super.haskell.lib.overrideCabal drv (drv: { broken = false; });
            doJailbreak = super.haskell.lib.doJailbreak;
            overrideSrc = super.haskell.lib.overrideSrc;
            addSetupDepend = super.haskell.lib.addSetupDepend;
        in rec
      {
        haskell = super.haskell // {
          packageOverrides = self: super: rec {
            /*
            haskell-src-meta = super.haskell-src-meta.overrideScope (self: super: { haskell-src-exts = self.haskell-src-exts_1_21_0; });
            ihaskell-charts = doJailbreak (unmarkBroken super.ihaskell-charts);
            Chart = overrideCabal super.Chart (drv: {
              broken = false;
              jailbreak = true;
              # preConfigure = ''
              #   sed -i ihaskell-charts -E \
              #     -e 's#(lens[^<]+)< *4.17#\1<4.50#g'
              # '';
            });
            */
            static-canvas = doJailbreak (unmarkBroken super.static-canvas);

            Chart = self.callHackageDirect {
              pkg = "Chart";
              ver = "1.9.1";
              sha256 = "0aiq9r78yhma1xzhwl2xlzwqb2c59k6a4jjvdpninwm6lngac3s7";
            } {};
            Chart-cairo = self.callHackageDirect {
              pkg = "Chart-cairo";
              ver = "1.9.1";
              sha256 = "0ambbkxbndjqxr0c4pysn87b3z0f8zpgvldj4qjbyazadna9k807";
            } {};
          };
        };
      };
    };
    # ihaskellNixpkgs = pkgs;

    ihaskellNixpkgsSrc = builtins.fetchTarball {
      url = "https://github.com/NixOS/nixpkgs-channels/archive/2df17ecf1b748379a349f763f376bad173bff83b.tar.gz";
      sha256 = "10s6p0i3g4jkmdgfh3zb73baapks6gwcfl2p9hc3j490ly2wa0kv";
    };
    ihaskellNixpkgs = import "${ihaskellNixpkgsSrc}" { config = ihaskellNixpkgsCfg; };

    ihaskellCleanSource = name: type: let
      baseName = baseNameOf (toString name);
    in lib.cleanSourceFilter name type && !(
      (type == "directory" && (builtins.elem baseName [ ".stack-work" "dist"])) ||
      builtins.any (lib.flip lib.hasSuffix baseName) [ ".hi" ".ipynb" ".sock" ".yaml" ".yml" ]
    );
    ihaskellSourceFilter = src: name: type: let
      relPath = lib.removePrefix (toString src + "/") (toString name);
    in ihaskellCleanSource name type && !( builtins.any (lib.flip lib.hasPrefix relPath) [
      "notebooks" "demo" "docker" "image"
    ]);


    ihaskellRepoLocal = builtins.filterSource (ihaskellSourceFilter ../../IHaskell) ../../IHaskell;
    ihaskellRepoRemote = builtins.fetchTarball {
      url = "https://github.com/jraygauthier/IHaskell/archive/534c0ac45544d7a79c07027678a04eb4b40f2bc3.tar.gz";
      sha256 = "07x0y7w2iscs9607shrxsx9iyjgjg2pcq8fdzrx43iipn4376q9a";
    };

    # ihaskellRepo = ihaskellRepoLocal;
    ihaskellRepo = ihaskellRepoRemote;

    ihaskellSystemPackages = pkgs: [
    ];

    ihaskellPackages = hps: with hps; [
      ihaskell-blaze
      ihaskell-diagrams
      ihaskell-charts

      # [ihaskell-display: IHaskell display instances for basic types
      # ](http://hackage.haskell.org/package/ihaskell-display)
      # > Deprecated. in favor of ihaskell
      # ihaskell-display

      # Error: HList
      # ihaskell-aeson
      # Error: HList
      # ihaskell-rlangqq
      ihaskell-gnuplot
      ihaskell-graphviz
      ihaskell-hatex
      ihaskell-juicypixels
      ihaskell-magic
      # Error: No instance for (Control.Monad.Fail.MonadFail Axis)
      # ihaskell-plot
      ihaskell-static-canvas
      /*
      # Compiles but takes a lot of time to do so.
      # Also:
      # [ihaskell-widgets runs with no error, however, displays no widget ·
      # Issue #870 · gibiansky/IHaskell](https://github.com/gibiansky/IHaskell/issues/870)
      ihaskell-widgets
      */
    ];

    ihaskellRelease86 = (import "${ihaskellRepo}/release-8.6.nix" {
      nixpkgs = ihaskellNixpkgs;
      packages = ihaskellPackages;
      systemPackages = ihaskellSystemPackages;
    });
  in
ihaskellRelease86
```

**Comment by jraygauthier** [comment]
There is ihaskell's `*.js` file: https://github.com/gibiansky/IHaskell/blob/master/html/kernel.js

**Comment by jraygauthier** [comment]
For the curious, here's the PR that added passthrough for ihaskell release https://github.com/gibiansky/IHaskell/pull/1027

**Comment by teto** [comment]
Thanks for your work ! Will look into it this week end probably.
Btw, I've recently tried https://github.com/tweag/jupyterWith and was really impressed how well it worked.

**Comment by jraygauthier** [comment]
@teto Nice, thanks for the ref. I wasn't aware of this jupyterWith project. This is pretty impressive.

**Comment by jraygauthier** [comment]
@teto: Just rebased on latest. Still interested in testing this?

**Comment by teto** [comment]
It's a bit hard to test and the jupyterWith project seemed so much better than nixpkgs implementation that I kinda lost interest (had developed some local jupyter improvements as well). I hope they merged theirs. Eventually I can merge this as is if it passes the tests. Low-risk PR.

**Comment by jraygauthier** [comment]
Alright.

Should be building fine now:

```bash
$ nix-shell -p nix-review --run "nix-review rev HEAD"
$ git fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0
$ git worktree add /home/rgauthier/.cache/nix-review/rev-c4ad72bcb8e822bd7fe5aa978f6d35b3b9dae587/nixpkgs a4083fb4551ce6dda68ac684a2ca951d2fa3ab72
Preparing worktree (detached HEAD a4083fb4551)
HEAD is now at a4083fb4551 Merge pull request #67236 from Chiiruno/dev/general
$ nix-env -f /home/rgauthier/.cache/nix-review/rev-c4ad72bcb8e822bd7fe5aa978f6d35b3b9dae587/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit c4ad72bcb8e822bd7fe5aa978f6d35b3b9dae587
Automatic merge went well; stopped before committing as requested
$ nix-env -f /home/rgauthier/.cache/nix-review/rev-c4ad72bcb8e822bd7fe5aa978f6d35b3b9dae587/nixpkgs -qaP --xml --out-path --show-trace --meta
$ nix build --no-link --keep-going --max-jobs 4 --option build-use-sandbox true -f /home/rgauthier/.cache/nix-review/rev-c4ad72bcb8e822bd7fe5aa978f6d35b3b9dae587/build.nix
[8 built, 676 copied (3620.9 MiB), 823.9 MiB DL]
3 package were build:
jupyter sage sageWithDoc
```

**Comment by Profpatsch** [comment]
cc @MMesch maybe we can add that to jupiterWith? Or even push jupiterWith to nixpkgs?

**Comment by jraygauthier** [comment]
Using jupiterWith myself nowadays.

**Pull request closed without merging**
