### PR TITLE
playwright-test: init at 1.31.1

### LINKED ISSUE #217693: Package request: playwright test
**Project description**

The request is not necessarily to package this for nixpkgs but if anyone has already done it so that I can steal the derivation. I think the probability is high considering the recent hype around playwright (there was also a post on this yesterday  https://discourse.nixos.org/t/running-playwright-tests/25655/2).

I am trying to help a coworker run "playwright test" but I dont know much about playwright or node. The executable brought by `nix shell nixpkgs#playwright` doesn't provide it and it's a python one. 
Seems like the "true" playwright is in typescript https://github.com/microsoft/playwright and the test command is provided by a submodule @playwright/test . At some point I managed to make it work with node2nix on that last repo but it might have been a fluke since once I started calling the derivation from a flake, it tried to reach out to the network.

**Metadata**

* homepage URL:  https://github.com/microsoft/playwright
* source URL:  https://github.com/microsoft/playwright
* license: apache 2
* platforms: unix, linux, darwin

### PR DESCRIPTION
**Pull request by teto**
Adds "playwright test" command.

###### Description of changes

Raw dump of a package working in an out of tree project, still needs some polish
Fixes  https://github.com/NixOS/nixpkgs/issues/217693 

I've tried buildNpmPackage but doesn't seem ready yet to handle this kind of package.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pbek** [comment]
I built the PR and run the resulting binary in a (unfortunately private) repository with Playwright tests written in Javascript:

```bash
/nix/store/8ck7islaxlgffm584kf91rq05ygigima-_at_playwright_slash_test-1.31.1/bin/playwright test
```

gave me errors like

```
Error: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

   at mono/mono.spec.js:7

   5 |     await page.goto('https://url.domain');
   6 |     await expect(page).toHaveURL(/auth\/realms/);
>  7 |     await page.locator('#username').fill(process.env.STUDENT_USERNAME ?? '');
     | ^
   8 |     await page.locator('#password').fill(process.env.STUDENT_PASSWORD ?? '');
   9 |     await page.locator('button[type="submit"]').click()
  10 |     await expect(page).toHaveURL(/mono/);

    at TestTypeImpl._currentSuite (/home/user/dev/e2e-tests-ng/node_modules/@playwright/test/lib/common/testType.js:70:13)
    at TestTypeImpl._createTest (/home/user/dev/e2e-tests-ng/node_modules/@playwright/test/lib/common/testType.js:76:24)
    at /home/user/dev/e2e-tests-ng/node_modules/@playwright/test/lib/common/transform.js:226:12
    at Object.<anonymous> (/home/user/dev/e2e-tests-ng/tests/mono/mono.spec.js:7:1)
```

**Comment by teto** [comment]
> You have two different versions of @playwright/test. 

Ha I have seen that error at some point. I was told that javascript has a peculiar singleton system based on path that even symlinks could throw off. This package is a port of a package we use internally with success and that shouldn't suffer from the problem. 
Why is it that the path is a local one ? /home/user/dev/e2e-tests-ng/node_modules/@playwright/test/lib/common/testType.js:76:24
it should come from the nix store

So maybe it's a plawyright error. Have you tried clearning up NODE_PATH in case it does load an alternative playwright ?

**Comment by pbek** [comment]
My NODE_PATH is `NODE_PATH=/nix/store/njh6p007ymbmcgas5l7sqqxfmm394zx1-nodejs-18.15.0/lib/node_modules`.
Setting it to an empty string didn't help. 🤔 

Only when I was manually removing `node_modules/@playwright/` (note that it will installed again by `npm install`) I managed to use the test **successfully in Chromium!**

But not in Firefox, there I got:

    browserType.launch: Executable doesn't exist at /nix/store/dkpc25ivrhx19d5v9px74qnsafn65hlr-playwright-browsers-chromium/firefox-1378/firefox/firefox

I don't know where it gets the path from, `/nix/store/dkpc25ivrhx19d5v9px74qnsafn65hlr-playwright-browsers-chromium` is the path for the chromium browser. **Any chance to make it work in firefox too?**

My shell.nix is:

```nix
{ pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    buildInputs = [
      pkgs.nodejs-18_x
      pkgs.playwright
    ];

    PLAYWRIGHT_BROWSERS_PATH="${pkgs.playwright-driver.browsers}";
  }
```

And **is there a chance to make it work inside VS-Code with the Playwright extension** (where you are supposed to do the actual development of the tests)?

**Comment by aszenz** [comment]
> And is there a chance to make it work inside VS-Code with the Playwright extension (where you are supposed to do the actual development of the tests)?

Add this to your vscode settings

```json
"playwright.env": {
    "PLAYWRIGHT_BROWSERS_PATH": "/nix/store/mlyamflq8icq0lwfircr03aiba0dbzg3-chromium-playwright",
    "PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS": 1
  },
```
Unfortunately u have to hard code the nix store path, maybe there's a way to read it from env var in vscode

**Comment by pbek** [comment]
Hm, I tried to do that, but vs-code doesn't even seem to detect my JS tests any more. It wants to show python tests. 😅

**Comment by teto** [comment]
awesome, maybe we can integrate your repository as part of the testsuite ?

Seems like it works for the only supported browser aka chrome:
```
Running 3 tests using 3 workers
  1) [webkit] › example.spec.js:4:1 › has title ────────────────────────────────────────────────────

    browserType.launch: Executable doesn't exist at /nix/store/fpibn255xp5iazcdnghbf06qgbacrqv3-playwright-browsers-chromium/webkit-1792/pw_run.sh
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

  2) [firefox] › example.spec.js:4:1 › has title ───────────────────────────────────────────────────

    browserType.launch: Executable doesn't exist at /nix/store/fpibn255xp5iazcdnghbf06qgbacrqv3-playwright-browsers-chromium/firefox-1378/firefox/firefox
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

  2 failed
    [firefox] › example.spec.js:4:1 › has title ────────────────────────────────────────────────────
    [webkit] › example.spec.js:4:1 › has title ─────────────────────────────────────────────────────
  1 passed (6.0s)

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.
  
  ```
  I am tempted to merge as is and discuss the test afterwards. There might even be a native testsuite that could be run

**Comment by pbek** [comment]
> awesome, maybe we can integrate your repository as part of the testsuite ?

fine with me! 🚀

**Comment by teto** [comment]
Let's go !

**Comment by pbek** [comment]
@teto, do you maybe know why there is no `--ui` parameter, as in `playwright test --ui`? (see https://playwright.dev/docs/test-cli)

**Comment by teto** [comment]
nope sry no idea, documentation is not clear to me either.

**Comment by samhh** [comment]
@pbek That was added in [1.32.0](https://github.com/microsoft/playwright/releases/tag/v1.32.0).

**Comment by pbek** [comment]
Ah, I see, thank you :)
So we'll need to wait for @toto. 😅

**Comment by samhh** [comment]
@teto We're also keen on a newer version at work. What would be the process of updating? Do we need to think about the driver/browsers as well?

**Comment by toto** [comment]
I think you mean @teto not @toto ;)

**Comment by teto** [comment]
I am sure you could sell @toto for a shitton of money, if only to https://en.wikipedia.org/wiki/Toto_Ltd. 

@samhh Absolutely, the playwright-driver version must match the package version ! we could add a warning to check that 
the playwright python package has this script to update the driver that I might have broken ?! 
https://github.com/teto/nixpkgs/blob/3beded5aa4b3e20e510b2eea292c3f49fbe44341/pkgs/development/python-modules/playwright/update.sh#L24
I dont know if nix-update can replace that script (probably not) but I guess the last lines should be moved to pkgs/development/web/playwright/

I have spent my plawyright FOSS credits but I am happy to review PRs if you wanna update the package. 


pkgs/development/web/playwright-test/wrapped.nix was written manually but depends on the driver version. Updating the driver and running `pkgs/development/web/playwright-test $ node2nix -i package.json` (from memory)  should work

**Comment by pbek** [comment]
> I think you mean @teto not @toto ;)

I'm so sorry! 😆

**Comment by kalekseev** [comment]
@samhh pr with latest playwright version https://github.com/NixOS/nixpkgs/pull/235914

**Pull request merged**
