### PR TITLE
make-wrapper: add `--no-assert` to skip assertExecutable()

### PR DESCRIPTION
**Pull request by steveej**
###### Motivation for this change
This allows to disable the assertion introduced in #24944.
The assertion prevents from wrapping a file that is not accessible in the sandbox, which is too restrictive for development environments, e.g. when wrapping a script that is somewhere in $HOME.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
- I'm not sure the name is ideal as it doesn't make it very clear what the flag changes
- There is no way of wrapping a program with `--add-flags --no-assert` without also triggering the no-assert behaviour

Other than that, LGTM.

**Comment by steveeJ** [comment]
> I'm not sure the name is ideal as it doesn't make it very clear what the flag changes

Suggestions welcome ;-)

> There is no way of wrapping a program with --add-flags --no-assert without also triggering the no-assert behaviour

This is solvable but I'm not sure if it's worth the complexity. You'd have to postpone the `assertExecution()` call until all arguments have been evaluated.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by steveeJ** [comment]
@mmahut I used a fork for a while and then project which needed it got abandoned. If you care for this feature I'll rebase it and we can continue the discussions.

**Comment by Ekleog** [comment]
Seeing as there's AFAIU no currently known need for this change, let's close this and people can still find it back in the PR logs if they need it too :)

**Pull request closed without merging**
