### PR TITLE
nixos/swap: fix creation on BTRFS and refactor assertions

### LINKED ISSUE #156829: `swapDevices` doesn't create a proper swapfile on btrfs
### Describe the bug

When using `swapDevices` to create and activate a swapfile on btrfs, it fails with messages like this:

```
A dependency job for swap.target failed. See 'journalctl -xe' for details.
warning: the following units failed: swapfile.swap

× swapfile.swap - /swapfile
     Loaded: loaded (/etc/fstab; generated)
     Active: failed (Result: exit-code) since Wed 2022-01-26 18:15:02 CST; 23ms ago
       What: /swapfile
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
         IP: 0B in, 0B out
        CPU: 2ms

Jan 26 18:15:02 toy systemd[1]: Activating swap /swapfile...
Jan 26 18:15:02 toy swapon[125673]: swapon: /swapfile: swapon failed: Invalid argument
Jan 26 18:15:02 toy systemd[1]: swapfile.swap: Swap process exited, code=exited, status=255/EXCEPTION
Jan 26 18:15:02 toy systemd[1]: swapfile.swap: Failed with result 'exit-code'.
Jan 26 18:15:02 toy systemd[1]: Failed to activate swap /swapfile.
warning: error(s) occurred while switching to the new configuration
```

The kernel says:

```
Jan 26 18:15:02 toy kernel: BTRFS warning (device nvme0n1p2): swapfile must not be copy-on-write
```

I am not very familiar with Nix, but after reading the corresponding [swap.nix](https://github.com/NixOS/nixpkgs/blob/17c61e97723ef2b10b60fd497b0e4eebe3b8655c/nixos/modules/config/swap.nix) and [btrfs manual](https://btrfs.readthedocs.io/en/latest/Swapfile.html), it seems that creating a swapfile on btrfs requires disabling copy-on-write for that file (via `chattr +C swapfile`) as well. However, `swap.nix` doesn't do it currently.

BTW, manually creating the swapfile and letting NixOS activating it works fine for me.

### Steps To Reproduce

1. Add `swapDevices = [{ device = "/swapfile"; size = 1024; }];` to `hardware-configuration.nix` (`/` is supposed to be mounted as btrfs).
2. Run `sudo nixos-rebuild switch`.

### Expected behavior

Swapfile is created and activated without any issue.

### Additional context

There is a workaround on NixOS Discourse: <https://discourse.nixos.org/t/how-do-i-set-up-a-swap-file/8323/7>.

### Notify maintainers

@Artturin

### Metadata

- system: `"x86_64-linux"`
- host os: `Linux 5.15.11-zen1, NixOS, 22.05 (Quokka)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.5.1`
- channels(root): `"nixos-22.05pre348581.c07b471b52b, home-manager"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by oxalica**
###### Description of changes

Fixes #156829

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zendo** [comment]
```
.rw------- 8.6G root 30 Nov 08:23 /swapfile

Filename				Type		Size		Used		Priority
/swapfile                               file		8388604		0		-2
```
Works on my machine, Thank you.

**Comment by Artturin** [comment]
@ofborg build nixosTests.swap-file-btrfs

**Comment by Artturin** [comment]
@ofborg build nixosTests.swap-partition

**Comment by RaitoBezarius** [comment]
It seems like it's in a good shape, anything left over before merging? Maybe having a backward compat release note in 23.05 ?

**Comment by oxalica** [comment]
@RaitoBezarius
> It seems like it's in a good shape, anything left over before merging? Maybe having a backward compat release note in 23.05 ?

The related code would only be trigger when the swapfile size is different than the size specified in config.
- If user uses BTRFS, the service fails on master, but succeeds after this PR.
- If user uses non-COW filesystems like EXT4, the service succeeds on master, and still succeeds after this PR, just with an extra `chattr`, whose result is ignored.

I consider this a fix rather than a breaking change.

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius
> 
> > It seems like it's in a good shape, anything left over before merging? Maybe having a backward compat release note in 23.05 ?
> 
> The related code would only be triggered when the swapfile size is different than the size specified in the config.
> 
> * If user uses BTRFS, the service fails on master, but succeeds after this PR.
> * If user uses non-COW filesystems like EXT4, the service succeeds on master, and still succeeds after this PR, just with an extra `chattr`, whose result is ignored.
> 
> I consider this a fix rather than a breaking change.

You convinced me!

**Comment by RaitoBezarius** [comment]
@Artturin are you okay with merging this?

**Comment by oxalica** [comment]
Rebased and added maintainers for the new test.

**Comment by Artturin** [comment]
gives me `swapon: /swapfile: skipping - it appears to have holes.` on zfs but it's not a regression

**Comment by NickCao** [comment]
@ofborg test swap-file-btrfs

**Review by NickCao — APPROVED** [review]
A note for users: you may have to delete the swapfile to trigger a recreation.

**Comment by oxalica** [comment]
> gives me `swapon: /swapfile: skipping - it appears to have holes.` on zfs but it's not a regression

AFAIK, ZFS doesn't support swapfile, but swap volume could be used instead. https://wiki.archlinux.org/title/ZFS#Swap_volume

**Pull request merged**
