### PR TITLE
Add solid-server to the list of node packages

### PR DESCRIPTION
**Pull request by sauyon**
###### Motivation for this change

Adding solid-server node package

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I'm pretty sure this package should also include systemd units and configuration for the solid server, but I was unsure about where to put those files.

EDIT: I also didn't commit commit the `node-packages-v*.nix` files because they contained a lot of unrelated changes.

### CODE REVIEW

**Comment by Mic92** [comment]
Please also add at least `node-packages-v6.nix`. Otherwise the package will be not available for install. You can later add a module to `nixos/` to care of the configuration/systemd service part.

**Comment by sauyon** [comment]
Should I revert everything that wasn't the solid package or leave it?

**Comment by Mic92** [comment]
No just keep it.

**Comment by sauyon** [comment]
Should I manually squash the commits or will you when you merge?

**Comment by globin** [comment]
This is a merge conflict

**Comment by FRidh** [comment]
Closing because of inactivity.

**Pull request closed without merging**
