### PR TITLE
cemu: 2.0-32 -> 2.0-36

### PR DESCRIPTION
**Pull request by lasers**
###### Description of changes
Bump version.

Speaking of versions, it has been `Cemu 2.0 (experimental)` for a long time...  I change this to `Cemu 2.0-33`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by baduhai — COMMENTED** [review]
~~LGTM~~ Actually, I just checked upstream and that is also experimental. So this should only be changed once upstream stops considering 2.0-XX experimental. I'll accept the version bump, though.

**Comment by lasers** [comment]
>upstream stops considering 2.0-XX experimental

I think upstream provide the users with `2.0-XX (experimental)` . Compiling  from source always give us  `2.0 (experimental)`. Went through several cemu iterations with `2.0 (experimental)` without seeing release numbers... at least without a bit more of digging. Any objection to doing this as `2.0-XX (experimental)` this time?

Initially, I think `2.0-33` is sufficient though because we don't have non-experimental `cemu` packaged nor do I think users will want to use non-experimental `cemu`. If/when stable releases start coming, they might be `Cemu 2.1`, `Cemu 2.2` or such.

**Comment by lasers** [comment]
I go ahead with `2.0-XX (experimental)` making this `2.0-34 (experimental)` instead of `2.0 (experimental)`. Cheers.

**Review by baduhai — APPROVED** [review]
LGTM

**Review by baduhai — APPROVED** [review]
LGTM

**Pull request merged**
