### PR TITLE
Tortoisehg 3.7.1 and icon_path fix

### LINKED ISSUE #13507: missing icons in tortoisehg toolbar
## Basic info

To make sure that we are on the same page:

* Kernel: (run `uname -a`)
Linux pav 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.10

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.03pre76763.be0abb3"

and the app itself is:

/nix/store/gxy7aws40mycs4d1zawxfwbbs5a3430q-tortoisehg-3.6/bin/tortoisehg

## Describe your issue here
Goto Revision and many other icons are missing and fall back to text.

### Expected result
A toolbar full of icons

### Actual result
A toolbar with icons for reload, stop, and home, followed by text buttons for Goto Revision, Filter Toolbar, etc.

secreenshot:

thg-missing-icons

### Steps to reproduce
1. `nix-env -i tortoisehg`
2. `tortoisehg`

### PR DESCRIPTION
**Pull request by dckc**
###### Things done:
- [x] Tested via `nix.useChroot`.
- [ ] Built on platform(s):
  - linux
- [x] Tested compilation of all pkgs that depend on this change.
  - `nix-store --query --referrers $(which tortoisehg)` shows nothing but user-environments.
- [x] Tested execution of binary products.
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### Extra

Fixes #13507

cc @k0ral

### CODE REVIEW

**Comment by dckc** [comment]
+cc @danbst

I just realized who the maintainer of this package is.

**Comment by danbst** [comment]
Nice. Have you tried to set `--root` to `$out`? This might be better, because we get get rid of `substituteInPlace` entirely

**Comment by dckc** [comment]
No, I haven't tried `--root`. I tried `--prefix`, only to realize it's an install-time thing, but the `/usr/share` value seems to be needed a build time. I wonder if that applies to `--root`. I guess I'll find out.

**Comment by FRidh** [comment]
While you're at it, could you replace `pyPackages` with `pythonPackages`.
`pkgs.pyqt4` should not be in `pythonPath` but in propagatedBuildInputs`, and neither should `qscintilla` and `iniparse` be . Only `mercurial` should probably stay there.

Also, please do not pass the whole `pkgs` but instead only the specific packages you need, like in this case `mercurial`.

**Comment by dckc** [comment]
I tried `installFlags = ["--root" "$out"]` but it doesn't work. It looks like `--root` is an install-time thing just like `--prefix` but the `sharedir` needs to be known **at build time**.

When I take `qscintilla` out of `pythonPath` I get `ImportError: No module named Qsci`.

I don't understand how to not pass the whole `pkgs` when it's used in the default expression `pythonPackages ? pkgs.python27Packages`. I tried taking it out of the argument list but I kept getting `undefined variable ‘pkgs’`.

**Comment by FRidh** [comment]
`buildPythonPackage` and  `buildPythonApplication` use `--prefix=$out`.
I opened a PR https://github.com/dckc/nixpkgs/pull/1

**Comment by FRidh** [comment]
@dckc rebasing:
- first pull the commit we made into your local branch with `git pull tortoisehg-3.7.1`
- next, squash the commits. `git rebase -i HEAD~4`. You can use `fixup` for the last 3 or 4 commits.
- and force-push back to this branch: `git push -f origin tortoisehg-3.7.1`

**Comment by FRidh** [comment]
if it doesn't work out, let me know.

**Comment by FRidh** [comment]
@dckc any progress?

**Comment by dckc** [comment]
I'm struggling to find motivation. Learning about nix has been interesting, and I would like to contribute a proper fix, but what I have works for me and I'm hitting obstacles at every turn. For example:

```
~/src/nixpkgs$ git pull tortoisehg-3.7.1
fatal: 'tortoisehg-3.7.1' does not appear to be a git repository
```

We're doing a migration from hg to git at work and it's really got me down.

Another demotivator is that hg was updated to 3.7.1 without checking this package that depends on it. (d4193c82c13e190b516ccaa9930544d4cdeaa98c)

@danbst, are you perhaps willing to clean up this PR?

**Comment by FRidh** [comment]
Yea I can imagine it takes quite some effort to get used to git. It's especially annoying if you have something that already works.
Anyway, I should have included the remote address there. I thought it would work like this.
So what I meant is that you have to pull the changes we made to your branch into your local branch.
Likely your remote is `origin`, so `git pull origin tortoisehg-3.7.1` should do the trick. 

This looks to be finished aside from the rebasing. I could just do the rebasing and push it and then we're done.

**Comment by joachifm** [comment]
@FRidh if this is ready for inclusion, perhaps you could rebase & merge it, considering the lack of response from the OP or is that considered poor form?

**Comment by FRidh** [comment]
Rebased and pushed in a4ce0e233b086845324f6b4d38ce3a408612a8d7.
Thanks @dckc

**Pull request closed without merging**
