### PR TITLE
manual.configuration.userManagement: mkpasswd

### PR DESCRIPTION
**Pull request by SRGOM**
Added clarification about mkpasswd in User Management section of the manual

### CODE REVIEW

**Comment by teto** [comment]
Thanks for the clarification, I would advise `nix run` (transient) rather than `nix-env` (permanent).

**Comment by SRGOM** [comment]
Sorry I don't know how to use `nix run`. I addressed your comment in another way but if you're not happy, please let me know and I will find out how `nix run` is used

**Comment by ck3d** [comment]
The equivalant command for nix run is following:
```
nix run nixpkgs.mkpasswd -c mkpasswd -m sha-512
```

**Comment by SRGOM** [comment]
Done. Using `nix run` now

**Pull request closed without merging**
