### PR TITLE
nogroup fixes after #133166

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

cc #133166 #138027

cc @ajs124 @zhaofengli @dschrempf 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zhaofengli** [comment]
Ah, by "dynamically allocated user id" in #138027 I thought you were going to use systemd's `DynamicUser`. This is fine for me as well, as long as there's an easy way for me to fix the UID/GID to deterministic values.

**Comment by symphorien** [comment]
Beyond this PR I'm curious about your use case of fixed UIDs, since rfc52 deprecates them: https://github.com/NixOS/rfcs/blob/master/rfcs/0052-dynamic-ids.md

**Comment by zhaofengli** [comment]
My root filesystem (including /etc/passwd) is [wiped on each boot](https://grahamc.com/blog/erase-your-darlings), and NixOS's dynamic UID/GID assignment isn't deterministic. The `DynamicUser` option in systemd is better in this regard because it automatically sets the ownership of the service's `StateDirectory` (/var/lib/name), `CacheDirectory` (/var/cache/name), and a few other related paths before the it's started. The problem is that it's not easy to point those directories outside of the mandated paths (you can only change the `name` part of `/var/lib/name`) - Symlinks do not work, and bind mounts require more setup and do not interact well with mounts made later in the boot process.

**Comment by dschrempf** [comment]
I just tried this with openntp in a virtual machine, and it worked. I can't say anything about the other services! Thanks!

**Review by yu-re-ka — APPROVED** [review]
Unbreaks the unifi module for me. Thanks!

**Pull request merged**
