### PR TITLE
coqPackages.{serapi: 8.17.0+0.17 -> 8.18.0+0.18, coq-lsp: 0.1.7+8.17 -> 0.1.8+8.18}

### PR DESCRIPTION
**Pull request by Alizter**
## Description of changes

Update serapi and coq-lsp.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build coqPackages_8_18.coq-lsp

**Comment by ejgallego** [comment]
Thank you so much @Alizter and @vbgl !

By the way @Alizter , maybe we should update the Nix entry in coq-lsp 's README ?

**Comment by Alizter** [comment]
@ejgallego Sure, the readme only mentions the flake in the repo AFAIK. You can just mention that `coq-lsp` is available from nixpkgs.

**Comment by ejgallego** [comment]
@Alizter we still have a link to the Nix package repos pull request for 8.16, should we remove it, or it is something expected for Nix users?

Maybe it is more customary to link to the coq-lsp recipe file?

**Comment by Alizter** [comment]
Let's continue this discussion in the repo so as to not disturb others.

**Pull request merged**
