### PR TITLE
[WIP] gnuradio: 3.7.14.3 -> 3.8.0.0

### PR DESCRIPTION
**Pull request by tomberek**
###### Motivation for this change
Update gnuradio to latest. This is a tech preview and update to python3, so I suspect we'll need to have both 3.7 and 3.8 in Nixpkgs for a bit.

###### Things done
Many changes to dependencies due to python2 -> python3 transition. Graphics libraries have changed. There is a hack in there about dist-packages, I'm working with upstream to fix that (https://github.com/gnuradio/gnuradio/pull/2019).

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tomberek** [comment]
Can a known user run ofborg please? I have not built on OS X.

**Comment by tomberek** [comment]
@fpletz @bjornfor can you give this a test?

**Comment by bjornfor** [comment]
Sorry, I have no time to test. And I'm not actively using gnuradio either, so not sure how to test beyond starting the GUI.

Is tech preview like a release candidate? Or beta release? If so I'd prefer not to add v3.8 to nixpkgs before upstream makes a (real) release.

**Comment by tomberek** [comment]
It's a release candidate for their push from python2 to python3. I want to give people a chance to test. And due to the large number of breaking changes I expect to have to support both 3.7.X and 3.8 for a little while.

**Comment by bjornfor** [comment]
Perhaps make this new version lowPrio then, until it gets a stable release?

**Comment by tomberek** [comment]
Sure, i don't have tagging/labeling rights.

**Comment by bjornfor** [comment]
No, I meant to apply the ```lowPrio``` function. grep in nixpkgs and you'll see it.

**Comment by tomberek** [comment]
done

**Comment by doronbehar** [comment]
I too think this should wait until 3.8 is not beta/release candidate/tech preview. I've made some tests in the past with programs that depend on Gnuradio and they didn't even succesfully compile with this version.

**Comment by doronbehar** [comment]
Update: GNURadio 3.8 was officially release today: https://www.gnuradio.org/news/2019-08-10-gnu-radio-v3-8-0-0-release/

@tomberek would you like to try again to push this? I consider taking over this myself..

**Comment by tomberek** [comment]
Here's a new push with a version bump to 3.8.0.0. Still doesn't work right due to some Qt issues. Anyone familiar with Qt packaging and dependencies?

Current symptoms, i can build and start `gnuradio-companion`, build a flow graph. Trying to bring in a Qt widget or output causes a seg fault.
```

(..gnuradio-companion-wrapped-wrapped:707): Gtk-WARNING **: 23:15:59.822: Could not find the icon 'gnuradio-grc'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
<<< Welcome to GNU Radio Companion 3.8.0.0 >>>

Block paths:
        /nix/store/lgj3w4c5bgqxksbpxr5ckngdapl7g7mb-gnuradio-3.8.0.0/share/gnuradio/grc/blocks
Warning: restarting the docstring loader (crashed while loading 'qtgui_bercurve_sink')
Warning: restarting the docstring loader (crashed while loading 'qtgui_const_sink_x')
Warning: restarting the docstring loader (crashed while loading 'qtgui_edit_box_msg')
Warning: restarting the docstring loader (crashed while loading 'qtgui_freq_sink_x')
Warning: restarting the docstring loader (crashed while loading 'qtgui_histogram_sink_x')
Warning: docstring loader crashed too often
Segmentation fault (core dumped)
```

**Comment by doronbehar** [comment]
Have you tried using `wrapQtAppsHook`? It's not a documented hook but you can try to find other Python QT derivations that use it and maybe figure out something with it.

**Comment by tomberek** [comment]
Yes I tried that, but I must have been using it incorrectly, or there is something else about Qt that I don’t understand.

**Comment by SuperSandro2000** [comment]
@tomberek are you going to work on this or can we close it?

**Comment by tomberek** [comment]
@SuperSandro2000 https://github.com/NixOS/nixpkgs/pull/99685 is much farther along, closing in favor of that PR.

**Pull request closed without merging**
