### PR TITLE
git-town: 7.3.0 → 7.4.0 

### PR DESCRIPTION
**Pull request by blaggacao**
- [x] `git-own --help` suceeded

### CODE REVIEW

**Comment by blaggacao** [comment]
Result of `nixpkgs-review pr 96944` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- git-town
</details>

**Comment by blaggacao** [comment]
Result of `nixpkgs-review pr 96944` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- git-town
</details>

**Review by danieldk — APPROVED** [review]
LGTM

Result of `nixpkgs-review pr 96944` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>git-town</li>
  </ul>
</details>

Tested binary: :heavy_check_mark: 

Please keep and fill in the *Things done* template. Removing these makes reviewing harder.

**Comment by blaggacao** [comment]
@danieldk thanks for merging! ok will do. I thought it's ckearer this way, since most are redundand with nix-review post and the manual check (which I confirmed), but for the sake of structure, it might still be valuable. :+1:

**Comment by blaggacao** [comment]
@danieldk

Tested binary: ✔️

Did you do that manually in the report or is it a new version of nixpkgs-review?

**Pull request merged**
