### PR TITLE
curaLulzbot: Move from Python 3.8 back to 3.6 to avoid showstopper bugs

### PR DESCRIPTION
**Pull request by charles-dyfis-net**
See https://gitlab.com/lulzbot3d/cura-le/cura-lulzbot/-/issues/72

###### Motivation for this change

cura-lulzbot does not work at all in NixSO 20.09, as `cura_app.py` refers to `platform.linux_distribution()`, which was deprecated in Python 3.6 and removed as of (or possibly before?) 3.8.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
It should be enough to just drop the line `linux_distro_name = platform.linux_distribution()[0].lower()` in `cura_app.py`. It does not seem that the assigned variable `linux_distro_name` is used anywhere.

**Comment by charles-dyfis-net** [comment]
> It should be enough to just drop the line `linux_distro_name = platform.linux_distribution()[0].lower()` in `cura_app.py`. It does not seem that the assigned variable `linux_distro_name` is used anywhere.

True. However, I'm very hesitant to try to ship against a Python version upstream has (clearly) never tested.

**Comment by charles-dyfis-net** [comment]
> It should be enough to just drop the line `linux_distro_name = platform.linux_distribution()[0].lower()` in `cura_app.py`. It does not seem that the assigned variable `linux_distro_name` is used anywhere.

@prusnak -- FWIW, I've gotten a report (from @leenaars) that merely patching out that variable results in an executable that starts up successfully, but doesn't correctly operate past that point.

**Comment by charles-dyfis-net** [comment]
One place where I'd appreciate feedback is on whether it's acceptable to have the change making numpy for Python 3.6 available (vs being in a gap between Python 3.4-and-older using numpy 1.16, and Python 3.8-and-newer using Numpy 1.20) inside the same commitish as the rest of the work, or whether it should be split either into its own commit, or into a completely separate PR.

**Comment by charles-dyfis-net** [comment]
> One place where I'd appreciate feedback is on whether it's acceptable to have the change making numpy for Python 3.6 available (vs being in a gap between Python 3.4-and-older using numpy 1.16, and Python 3.8-and-newer using Numpy 1.20) inside the same commitish as the rest of the work, or whether it should be split either into its own commit, or into a completely separate PR.

@jonringer, are you the right person to ask on the above? (I see your name on the `if pythonOlder` line being changed).

**Comment by charles-dyfis-net** [comment]
> One place where I'd appreciate feedback is on whether it's acceptable to have the change making numpy for Python 3.6 available (vs being in a gap between Python 3.4-and-older using numpy 1.16, and Python 3.8-and-newer using Numpy 1.20) inside the same commitish as the rest of the work, or whether it should be split either into its own commit, or into a completely separate PR.

@FRidh, it looks like you're involved in numpy derivation maintenance -- are you the right person to ask on the above?

**Comment by FRidh** [comment]
The 3.6 package set is not tested at all and can break at anytime. As more packages remove support for 3.6 it gets even harder to keep it working, an effort you would have to put in yourself. 3.6 is considered EOL end of this year.

**Comment by charles-dyfis-net** [comment]
> The 3.6 package set is not tested at all and can break at anytime. As more packages remove support for 3.6 it gets even harder to keep it working, an effort you would have to put in yourself. 3.6 is considered EOL end of this year.

Through EOY seems like a timeline on which I'm reasonably able to make that commitment. If Lulzbot hasn't managed to put out a new release of their Cura fork by the time the newest Python interpreter they support goes EOL, that would seem like an excellent time to call Cura-LE dead.

**Comment by FRidh** [comment]
Sure, its up to you, just be aware we don't have any CI anymore for that package set. I'd strongly recommend working with upstream at migrating to a newer Python version.

**Comment by charles-dyfis-net** [comment]
> Sure, its up to you, just be aware we don't have any CI anymore for that package set. I'd strongly recommend working with upstream at migrating to a newer Python version.
> 
> Note also Python 3.6 will be removed for NixOS 21.11.

:+1:; I've pinged their customer support to get an official statement on upstream maintenance plans.

(It turns out they _have_ pushed out a minor revision, but it's only updating the frontend and not the Python libraries behind it, which are where much is the breakage is).

**Comment by charles-dyfis-net** [comment]
Upstream indicated that the failure to tag a new `curaBinaryData` release with updated firmware was in error; revising the version-bump part of this PR to include the previously-missing components (which will enable support for the new 1.75mm toolhead).

**Pull request closed without merging**
