### PR TITLE
jre8: minimize minimal build and add more GUI dependencies to the regular one

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

We have several issues (https://github.com/NixOS/nixpkgs/issues/17876, https://github.com/NixOS/nixpkgs/issues/12472) which arise because Java is not linked to all supported libraries. I propose to add requested and several other libraries to Java's closure, and instead make `minimal` minimal-er. The idea is that `jre8_headless` doesn't support sound, printing and GUI and is used for console and server applications. `jre8`, on the other hand, supports all kinds of GUI-related activities, and is also linked to GTK, CUPS and several GNOME libraries. This makes it much nicer to work with, especially on HighDPI displays -- GTK-2 Java backend is the only one which is DPI-aware.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by abbradar** [comment]
I also propose prefix'ing several Java options to `java` by default to enable GTK backend by default -- this way it still can be overridden but gives much nicer user experience. I haven't done this yet though -- I'm interested in feedback on this idea first.

**Comment by joelmo** [comment]
I don't understand why prefixing gives better user experience here. Do you want that to have better control if you set `pkgs.minimal = true`?

**Comment by abbradar** [comment]
With several Java options prefixed applications would use GTK and native font settings (specifically anti-aliasing) by default, so applications would look native and use system DPI. This changes only default style to GTK -- application would still be able to override it if needs to. I'm not sure about font settings however, but I think using system defaults is better anyway.

**Comment by abbradar** [comment]
Oh, and see https://wiki.archlinux.org/index.php/java#Tips_and_tricks for the options themselves.

**Comment by joelmo** [comment]
I agree that applications should use system settings where possible. Btw now that gtk support is enabled am not sure that the infinality patch is needed if font rendering is provided by gtk. The infinality patch I believe make java use system defaults for font rendering, I don't know how to check if the DPI match.
I don't know what is best but the options you linked too can also be set by a wrapper.

**Comment by abbradar** [comment]
On October 2, 2016 9:13:00 PM GMT+03:00, Joel Moberg <notifications@github.com> wrote:
>I agree that applications should use system settings where possible.
>Btw now that gtk support is enabled am not sure that the infinality
>patch is needed if font rendering is provided by gtk.

Infinality would still be useful in case application wants to have some other style besides GTK or perhaps its own widgets. 

> The infinality patch I believe make java use system defaults for font rendering,

Nice! It shouldn't hurt to set this in wrapper anyway I'd say in case Infinality support is disabled (we have a flag after all). 

> I
>don't know how to check if the DPI match.

As far as I know GTK is the only DPI-aware backend, Infinality doesn't help with that. 

>I don't know what is best but the options you linked too can also be
>set by a wrapper.

That's precisely my idea. I don't want to add anything extra besides those that set GTK as a default style and enable system font settings. 
-- 
Nikolay.

**Comment by abbradar** [comment]
Okay, I've rewritten a more in-depth description of what I've changed. Also I went another way -- I now patch Java to use GTK automatically when it's available (not only if desktop is GNOME). This should be a cleaner way -- it avoids wrappers and possible options clashes.

I copy the description of the first patch here for more visibility:

This makes several adjustments around what is linked into JRE.

* system giflib, libjpeg, zlib are now used unconditionally;
* libstdc++ is linked dynamically.

For full version:

* GTK+ and GNOME libraries are linked;
* Extra X11 libraries are linked;
* CUPS is linked;
* libmagic (file) is linked.

For minimal version:

* All X11 support is removed;
* Sound support is removed.
* Fonts and their support are not linked.

jre8_headless is added as a minimal build.

Overall this adds support for all things GUI into the default Java build and
removes them from the minimal build.

**Comment by abbradar** [comment]
cc maintainer @edwtjo

**Comment by abbradar** [comment]
This has not generated negative opinions so far and seems a non-breaking change with closure size increase the only possible problem. I'll merge this in several days unless anybody objects.

**Comment by deepfire** [comment]
@abbradar, I'm on nixpkgs master, and I still can't use -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel  with neither openjdk nor oraclejre, as it doesn't find  GTKLookAndFeel.

How do I diagnose this?

**Comment by rycee** [comment]
@abbradar Are you still working on this? It would be great to have these improvements in NixOS 17.03.

**Comment by abbradar** [comment]
@rycee I thought that this was merged long ago.

@deepfire Sorry, seems that your message in pile of others D: I know that I'm very late but is this still relevant?

**Comment by rycee** [comment]
@abbradar Sorry! I was going through some old PRs and got confused, thought this was still open. I checked, the GTK+ look and feel work for me :-)

**Pull request merged**
