### PR TITLE
pv: 1.8.5 -> 1.8.9

### PR DESCRIPTION
**Pull request by TheRealKeto**
## Description of changes

Update `pv` to its latest released version, 1.8.9. The project license changed to GPL-3+.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]
Diff looks good, running nixpkgs-review now.

This might take a while, given the rebuilds...

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 306463` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>radicle-upstream</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>badlion-client</li>
    <li>lunatask</li>
  </ul>
</details>
<details>
  <summary>114 packages built:</summary>
  <ul>
    <li>Sylk</li>
    <li>altair</li>
    <li>alvr</li>
    <li>anytype</li>
    <li>appimage-run</li>
    <li>arduino-ide</li>
    <li>bazecor</li>
    <li>beekeeper-studio</li>
    <li>beeper</li>
    <li>betterdiscord-installer</li>
    <li>bloomrpc</li>
    <li>bootstrap-studio</li>
    <li>buttercup-desktop</li>
    <li>caido</li>
    <li>caprine-bin</li>
    <li>chrysalis</li>
    <li>cider</li>
    <li>codux</li>
    <li>cozy-drive</li>
    <li>crypto-org-wallet</li>
    <li>davinci-resolve</li>
    <li>davinci-resolve-studio</li>
    <li>deskreen</li>
    <li>devdocs-desktop</li>
    <li>electron-mail</li>
    <li>electronplayer</li>
    <li>firefly-desktop</li>
    <li>flexoptix-app</li>
    <li>fluent-reader</li>
    <li>framesh</li>
    <li>freetube</li>
    <li>hamsket</li>
    <li>hifile</li>
    <li>hoppscotch</li>
    <li>immersed-vr</li>
    <li>irccloud</li>
    <li>jan</li>
    <li>jbrowse</li>
    <li>jetbrains-toolbox</li>
    <li>joplin-desktop</li>
    <li>kchat</li>
    <li>keet</li>
    <li>kmeet</li>
    <li>lbry</li>
    <li>ldtk</li>
    <li>ledger-live-desktop</li>
    <li>lens</li>
    <li>listen1</li>
    <li>lmstudio</li>
    <li>logseq</li>
    <li>losslesscut-bin</li>
    <li>lunar-client</li>
    <li>marktext</li>
    <li>mathpix-snipping-tool</li>
    <li>mendeley</li>
    <li>miru</li>
    <li>mobilecoin-wallet</li>
    <li>mockoon</li>
    <li>molotov</li>
    <li>motrix</li>
    <li>mqttx</li>
    <li>museeks</li>
    <li>mycrypto</li>
    <li>neo4j-desktop</li>
    <li>nosql-workbench</li>
    <li>notable</li>
    <li>notesnook</li>
    <li>notion-app-enhanced</li>
    <li>nuclear</li>
    <li>openlens</li>
    <li>osu-lazer-bin</li>
    <li>p3x-onenote</li>
    <li>parsify</li>
    <li>pcloud</li>
    <li>plexamp</li>
    <li>polypane</li>
    <li>protonup-qt</li>
    <li>pureref</li>
    <li>pv</li>
    <li>rambox</li>
    <li>raven-reader</li>
    <li>remnote</li>
    <li>requestly</li>
    <li>revolt-desktop</li>
    <li>ripcord</li>
    <li>rshim-user-space</li>
    <li>saleae-logic-2</li>
    <li>sanoid</li>
    <li>session-desktop</li>
    <li>simplex-chat-desktop</li>
    <li>sonixd</li>
    <li>soulseekqt</li>
    <li>spacedrive</li>
    <li>ssb-patchwork</li>
    <li>station</li>
    <li>steam-rom-manager</li>
    <li>super-productivity</li>
    <li>timeular</li>
    <li>todoist-electron</li>
    <li>trezor-suite</li>
    <li>tusk</li>
    <li>tutanota-desktop</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>upscayl</li>
    <li>via</li>
    <li>vial</li>
    <li>wal_e</li>
    <li>wal_e.dist</li>
    <li>wootility</li>
    <li>xlights</li>
    <li>zecwallet-lite</li>
    <li>zettlr</li>
    <li>zulip</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
Lunatask maintainer @henkery - do you want to investigate here?
badlion-client has no maintainer, so I'd merge this if @henkery doesn't mind.

**Comment by henkery** [comment]
For now I agree to merge, will try to resolve failing build of lunatask after rebuild

**Comment by Scrumplex** [comment]
The `badlion-client` failure is a mismatched source hash, so it's totally unrelated here

**Comment by matthiasbeyer** [comment]
Okay, as @henkery approved, lets merge this earlier than I said :laughing:

**Pull request merged**
