### PR TITLE
heroic: fix cursor issues

### PR DESCRIPTION
**Pull request by Steinhagen**
Fix the Xorg mouse issues initialy found with Lutris in: https://github.com/NixOS/nixpkgs/pull/348533

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by aidalgol — APPROVED** [review]
I don't think I have any way of testing this, but adding these Xorg packages to the FHS environment seems perfectly sensible to me.

**Comment by Atemu** [comment]
For testing, please simply point your Nixpkgs at this branch. If you use NIX_PATH then use `-I nixpkgs=https://github.com/Steinhagen/nixpkgs/archive/refs/heads/heroic-xorg-mouse-fix.zip` and flakes users can use the flake url `github:Steinhagen/nixpkgs/heroic-xorg-mouse-fix`.

**Comment by Steinhagen** [comment]
If you are using flakes, another way to test this would be:

============================== flake.nix ===============================
```
{
  ......................................................................
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    heroicfix.url = "github:Steinhagen/nixpkgs/heroic-xorg-mouse-fix";
  ......................................................................
  };
  outputs =
    {
      self,
      ...
    }@inputs:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages."x86_64-linux";
      pkgs-heroicfix = import inputs.heroicfix {
        inherit system;
        config.allowUnfree = true;
      };
    in
    {
      nixosConfigurations = {
        test-machine = nixpkgs.lib.nixosSystem {
          specialArgs = {
            inherit
              system
              inputs
              pkgs-heroicfix
              ;
          ..............................................................
          };
          modules = [
            ./configuration.nix
  ......................................................................
```

=========================== configuration.nix ==========================
```
{
  pkgs,
  pkgs-heroicfix,
  ...
}:
{
  ......................................................................
  users.users = {
    demouser = {
      ..................................................................
      packages =
        (with pkgs; [
          ..............................................................
        ])
        ++ (with pkgs-heroicfix; [
          (heroic.override {
            extraPkgs = pkgs-heroicfix: [
              wineWowPackages.staging
              winetricks
              wineWowPackages.waylandFull
            ];
          })
        ]);
    };
  };
}
```

**Comment by Atemu** [comment]
Yup, please test with that and report back.

**Comment by KennethHoff** [comment]
I realized I was on a relatively old unstable branch so it takes a little while to rebuild. First gonna test if my PC works on the newest unstable and then I can test out @Steinhagen's branch.

Tangent, but how do I set the `download-buffer-size` setting? My Google-fu is unusually bad at this; I literally get 3 results on Google and even ChatGPT is failing me. It says something about `nix.conf` but I want to set it in my `configuration.nix` instead :sweat_smile:

**Comment by KennethHoff** [comment]
After like an hour of compiling Firefox for some reason I was able to verify that `nixos-unstable` w/ Heroic still does not work, but this PR w/ Heroic _does_ work! (I checked Lutris too just for fun, and it still worked)

**Review by KennethHoff — APPROVED** [review]

**Comment by Atemu** [comment]
Great, thanks :)

**Pull request merged**
