### PR TITLE
skim: init at 1.4.28

### PR DESCRIPTION
**Pull request by yurrriq**
###### Motivation for this change

[Skim](http://skim-app.sourceforge.net) is a great PDF reader for macOS, so why not have a Nix package for it?

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rasendubi** [comment]
It is better to build the package from source rather than download pre-built binary.

**Comment by yurrriq** [comment]
@rasendubi: Ok, I've always downloaded binaries, but I'll give it a go.

**Comment by yurrriq** [comment]
Well, I've been at it a long time and can't seem to figure out. There aren't really any good examples of building non-Apple Xcode projects either :/

If y'all wanna close this because it's a binary, go ahead, but I'm going to keep using it locally :)

**Comment by yurrriq** [comment]
I've rebased this and upgraded to 1.4.28. I have no intentions of building from source any time soon. Feel free to merge or close.

**Pull request closed without merging**
