### PR TITLE
superlu: 5.2.1 -> 7.0.0; openmolcas: unpin Boost

### PR DESCRIPTION
**Pull request by emilazy**
Includes fixes for GCC 14. Also addresses non‐free code already removed by Debian. If there’s demand for this functionality it could be re‐added under a flag.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by markuskowa — APPROVED** [review]
openmolcas LGTM. I am just a bit confused here: how is openmolcas connected to superlu?

cc @sheepforce

**Comment by sheepforce** [comment]
> how is openmolcas connected to superlu?

I think it doesn't:
```bash
$ nix why-depends nixpkgs/master#openmolcas nixpkgs/master#superlu
this path will be fetched (0.20 MiB download, 0.63 MiB unpacked):
  /nix/store/df9zjr9xbip7qsbs4icy6wlmb5nsjwiv-superlu-5.2.1
'flake:nixpkgs/master#openmolcas' does not depend on 'flake:nixpkgs/master#superlu'
```

Otherwise unpinning boost in OpenMolcas is certainly a good idea :)

**Comment by emilazy** [comment]
It’s a build‐time dependency, so I had to fix `superlu` to check whether `openmolcas` could be unpinned:

```
yuyuko:~/Developer/nixpkgs  (empty) (no description set)
❭ nix why-depends --derivation .#legacyPackages.x86_64-linux.{openmolcas,superlu}
/nix/store/ljkz2ic7z8xca2db2380pb5q7vl558bm-openmolcas-24.10.drv
└───/nix/store/57ya1bmb77z5fmd9dd54p98llxman2yy-armadillo-14.0.3.drv
    └───/nix/store/q4vf39pii368h9cliylbslvsfxi2b048-superlu-7.0.0.drv
```

Whether that’s sensible or not, I don’t know – I confess that I’m doing a tree‐wide clean‐up and couldn’t accurately describe exactly what this software does :)

**Comment by paparodeo** [comment]
for whatever reason after the update to superlu darwin is segfaulting running tests. not linking to accelerate and using the bias package fixes -- https://github.com/NixOS/nixpkgs/pull/367110

**Pull request merged**
