### PR TITLE
himalaya: 0.5.8 → 0.5.9

### PR DESCRIPTION
**Pull request by toastal**
Version bump, but also included the comment suggested for the build
flags as suggested on the last merge request. It would seem that
‘official’ description for the project has changed as well.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by toastal** [comment]
@yanganto hasn't responded to the last several merge request for version bumps, should another person be added as a maintainer as well?

https://github.com/NixOS/nixpkgs/pull/136872
https://github.com/NixOS/nixpkgs/pull/142867
https://github.com/NixOS/nixpkgs/pull/159138
https://github.com/NixOS/nixpkgs/pull/162465

**Comment by yanganto** [comment]
Yes, If @toastal can help to become one of the maintainers will be appreciated.  I will take time on this.  Thanks for reminding me.

**Comment by toastal** [comment]
@yanganto I don't know if I'm the *most* qualified, but I can help. It takes a surprising amount of time to do this stuff for sure.

**Comment by yanganto** [comment]
@toastal I do not have the power to decide this, and I think you can be a maintainer for this because you have the will and there will be a way, eventually you will learn everything you need to know by keeping this package updated.

Because of the VPN version matching issue, I lock my OS in an older version these days and have not to keep updating my system these days, so I seldom watch on the packages I packed before being updated or not.  And I really appreciate that you keep updating this package.  Once I can update my system, I can with you and keep things updated and learn. :)

**Review by yanganto — APPROVED** [review]
`nixpkgs-review pr 163954` without error on NixOS

**Pull request merged**
