### PR TITLE
zfs: 0.6.5.2 -> 0.6.5.3

### PR DESCRIPTION
**Pull request by dasjoe**
Bugfix release, see https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.3 for changelog

### CODE REVIEW

**Comment by domenkozar** [comment]
@wkennington

**Comment by dasjoe** [comment]
Please cherry-pick this into 15.09, too.

@wkennington: how should point releases like this be handled?
ZoL's @behlendorf said @nedbass is ZoL's stable release maintainer, who
is tagging point releases "to stabilize things".
Those releases move independent from `master`, I think we should handle
them like kernel point releases and include them in the current stable.

-- 
Regards,
Hajo Möller

**Comment by wkennington** [comment]
Sounds good to me.

**Comment by behlendorf** [comment]
Yes, you'll probably want to track the -release branch which is maintained @nedbass.  It will get updated for critical bug fixes and support for the latest kernels.  As always we'll keep the master is good shape but it will get the larger more disruptive changes first so there's more potential something will be overlooked.

**Comment by dasjoe** [comment]
I'll close this, as @wkennington pushed a similar commit a few days ago.

However, I would still like this point release to make it into `release-15.09`.

**Pull request closed without merging**
