### PR TITLE
Update some mate packages patch version

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update some mate packages patch version:

mate.mate-user-guide: 1.22.2 -> [1.22.3](https://github.com/mate-desktop/mate-user-guide/releases/tag/v1.22.3)
mate.mate-system-monitor: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-system-monitor/releases/tag/v1.22.2)
mate.mate-settings-daemon: 1.22.0 -> [1.22.1](https://github.com/mate-desktop/mate-settings-daemon/releases/tag/v1.22.1)
mate.mate-session-manager: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-session-manager/releases/tag/v1.22.2)
mate.mate-screensaver: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-screensaver/releases/tag/v1.22.2)
mate.mate-power-manager: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-power-manager/releases/tag/v1.22.2)
mate.mate-panel: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-panel/releases/tag/v1.22.2)
mate.mate-notification-daemon: 1.22.0 -> [1.22.1](https://github.com/mate-desktop/mate-notification-daemon/releases/tag/v1.22.1)
mate.mate-menus: 1.22.0 -> [1.22.1](https://github.com/mate-desktop/mate-menus/releases/tag/v1.22.1)
mate.mate-media: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-media/releases/tag/v1.22.2)
mate.mate-indicator-applet: 1.22.0 -> [1.22.1](https://github.com/mate-desktop/mate-indicator-applet/releases/tag/v1.22.1)
mate.mate-icon-theme: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-icon-theme/releases/tag/v1.22.2)
mate.mate-desktop: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-desktop/releases/tag/v1.22.2)
mate.mate-control-center: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-control-center/releases/tag/v1.22.2)
mate.mate-calc: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-calc/releases/tag/v1.22.2)
mate.mate-applets: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/mate-applets/releases/tag/v1.22.2)
mate.marco: 1.22.2 -> [1.22.3](https://github.com/mate-desktop/marco/releases/tag/v1.22.3)
mate.libmateweather: 1.22.0 -> [1.22.1](https://github.com/mate-desktop/libmateweather/releases/tag/v1.22.1)
mate.eom: 1.22.1 -> [1.22.2](https://github.com/mate-desktop/eom/releases/tag/v1.22.2)
mate.caja-extensions: 1.22.0 -> [1.22.1](https://github.com/mate-desktop/caja-extensions/releases/tag/v1.22.1)

Tested on a VM.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by chpatrick — APPROVED** [review]

**Comment by worldofpeace** [comment]
I can test this in a VM today @romildo and review the patch releases.

**Comment by romildo** [comment]
@GrahamcOfBorg build mate.caja-extensions mate.eom mate.libmateweather mate.marco mate.mate-applets mate.mate-calc mate.mate-control-center mate.mate-desktop mate.mate-icon-theme mate.mate-indicator-applet mate.mate-media mate.mate-menus mate.mate-notification-daemon mate.mate-panel mate.mate-power-manager mate.mate-screensaver mate.mate-session-manager mate.mate-settings-daemon mate.mate-system-monitor mate.mate-user-guide

**Comment by worldofpeace** [comment]
Seeing these errors in the journal
```
Unable to contact datetime settings daemon: Error calling StartServiceByName for org.mate.SettingsDaemon.DateTimeMechanism: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ServiceNotFound: Bus name not found in system service directory
```

Other than this, everything seems fine when testing in a VM.

**Review by worldofpeace — APPROVED** [review]
See above.

**Pull request merged**
