### PR TITLE
Adds Haskell generic builder argument modifier

### LINKED ISSUE #104349: Haskell builds do not always build/source test dependencies
**Describe the bug**
The Haskell build framework does not appear to appropriately source Haskell packages in the `nix-shell` environment when `doCheck = false` for the entire Haskell package set _except_ a single packages (in this case, the package being developed.

See [this repository](https://github.com/jkachmar/haskell-nix-repro) for a reproduction; specific areas of interest are as follows:
- [the `mkDerivation` override disabling tests](https://github.com/jkachmar/haskell-nix-repro/blob/trunk/default.nix#L27-L33)
- [the overlay that re-enables tests for the package-under-test](https://github.com/jkachmar/haskell-nix-repro/blob/trunk/default.nix#L45-L47)

**To Reproduce**
1. Clone [this repository](https://github.com/jkachmar/haskell-nix-repro)
2. Invoke `nix-shell`
3. Observe the following:
    -  `hspec` is neither built by Nix, nor included in the packages displayed by the `shellHook` call to `ghc-pkg list`
    - calling `cabal test` from within the shell will attempt to download dependencies from Hackage
4. Additionally, one can apply the following patch and observe the following:
    - `hspec` _is_ built by Nix however it is still _not_ displayed by the `shellHook` call to `ghc-pkg list`
    - calling `cabal test` still attempts to download the package from Hackage, even though we observed that it was compiled by Nix

<details>
<summary>patch</summary>
<p>

```patch
diff --git a/shell.nix b/shell.nix
index 31d485e..eaf8bf4 100644
--- a/shell.nix
+++ b/shell.nix
@@ -1,11 +1,10 @@
 let
-  inherit (import ./default.nix {}) haskellPkgs;
+  inherit (import ./default.nix {}) haskellPkgs pkgs;
 in
 
-haskellPkgs.shellFor {
-  packages = p: [ p.repro ];
-  nativeBuildInputs = [ haskellPkgs.cabal-install ];
-  shellHook = ''
-    ghc-pkg list
-  '';
+pkgs.mkShell {
+  buildInputs = [
+    (haskellPkgs.ghcWithPackages (p: [p.repro]))
+    pkgs.cabal-install
+  ];
 }
```

</p>
</details>  

**Expected behavior**
Nix's Haskell build framework should support the following behavior:
- disabling all tests in a package set _while also_ selectively enabling tests for a subset of packages as desired
- appropriately sourcing the transitive dependency tree of all enabled components in a Haskell project within the `nix-shell` environment's GHC `pkgdb`

**Notify maintainers**

ping @cdepillabout, as we spoke about this on Slack.

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20201102_550e11f`
 - channels(jkachmar): `"darwin"`
 - channels(root): `"nixpkgs-21.03pre246624.cfed29bfcb2"`
 - nixpkgs: `/nix/store/s18y38xsw017icfnskgasfxy437ms267-13jxji98gdq08mzcxsk9gvm70cd5fkzr-darwin-stable-src`
```

NOTE: My personal Nix configuration is fairly involved; at the time of writing I've tested this with:
- [this nixpkgs-20.09 checkout](https://github.com/jkachmar/dotnix/blob/f289e402b23e4b1b43d681e47bfa5d575b7a6297/nix/sources.json#L2-L13)
- [this nixpkgs-unstable checkout](https://github.com/jkachmar/dotnix/blob/f289e402b23e4b1b43d681e47bfa5d575b7a6297/nix/sources.json#L62-L73)

### PR DESCRIPTION
**Pull request by jkachmar**
###### Motivation for this change

Closes #104349, or rather at least provides a means for users to override settings for Haskell builders that can result in issues like the one described in #104349.

TODO:
- [x] add documentation
- [x] add examples

A quick example, lifted from @cdepillabout's original fork that provided this solution, would be:

```nix
{
  # ... elided
  haskellPkgs = pkgs.haskell.packages.ghc884.override (hpArgs: {
    overrides = pkgs.lib.composeExtensions (hpArgs.overrides or (_: _: { })) (
      _hfinal: hprev: {
        mkDerivation = args: hprev.mkDerivation ({
          doCheck = false;
          doBenchmark = false;
          doHoogle = true;
          doHaddock = true;
          enableLibraryProfiling = true;
          enableExecutableProfiling = false;
        } // args);
      }
    );
  });
}
``` 

The above snippet provide a Haskell package set that does **not** run tests or benchmarks for any of the declared dependencies, but which can be used as follows:
```nix
# ... elided
haskellPkgs.shellFor {
  packages = p: [ p.foo ];
  genericBuilderArgsModifier = args: args // { doCheck = true; doBenchmark = true; };
}
```

...which would enable tests and benchmarks for the package `foo` being developed, and would result in their dependencies being compiled into the shell environment accordingly.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jkachmar** [comment]
Ping @cdepillabout and @expipiplus1, since we discussed this in the issue thread.

I've added documentation, but I'm worried it might be a bit verbose. If it is, any thoughts on how the example might be reduced in scope a bit?

If not, I think this should be good to merge; I've tested it with a fork of `nixpkgs` on my work codebase and it all seems to be working as expected.

**Comment by cdepillabout** [comment]
Sorry for taking a while to review this.

I think the documentation is really easy to understand, so I am going to go ahead and merge this in!  Thanks for taking the time to put this together!

It would be nice to have a test for this (since the problem it solves is somewhat non-trivial), but given that it would implicitly require IFD, we can't really have it run on Hydra.

**Comment by jkachmar** [comment]
Not a problem, thanks for getting this merged in!

Just as a final point of follow-up, what's the procedure for making sure this gets backported to the `release-20.09` branch (if that's possible)?

**Comment by cdepillabout** [comment]
> Just as a final point of follow-up, what's the procedure for making sure this gets backported to the release-20.09 branch (if that's possible)?

Oh yeah, sorry I had forgot that you originally wanted this on 20.09.  There is no real formal process.  Could you `git cherry-pick -x` this commit against the `release-20.09` branch and open a PR?

**Pull request merged**
