### PR TITLE
mist: remove

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change
Mist is now deprecated and not maintained anymore since about two years ago.
See [README of the repository](https://github.com/ethereum/mist#mist-browser-deprecated).

Note that the package in master is also broken (segfault when starting on linux-x86_64).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drewrisinger** [comment]
Diff mostly LGTM, except the alias is a little too long. I'd follow something closer to https://github.com/NixOS/nixpkgs/blob/8c95378ef9b4b5e7ba52c73aa8554d53cd635327/pkgs/top-level/aliases.nix#L580

If you want, you could still include the migration guide, though people could also find that on their own. I might also move the ``mist`` section up to somewhere in the file where it makes a little more sense than directly at the end. maybe somewhere alphabetically.

**Comment by oxalica** [comment]
Simplified. Now I just put the link to README of the repository, which contains these links.

r? @jonringer

**Comment by bhipple** [comment]
Always happy to see garbage being picked up!

**Comment by jonringer** [comment]
I guess i didn't hit `submit review`, but yea, looks good

**Pull request merged**
