### PR TITLE
[21.05] php: php upgrades

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
Backport of #125513, #125656, #125628

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125621` at fb4f4add run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>pulseeffects-legacy</li>
    <li>pulseeffects-pw</li>
  </ul>
</details>
<details>
  <summary>3 packages skipped due to time constraints:</summary>
  <ul>
    <li>libsForQt512.kcachegrind</li>
    <li>libsForQt514.kcachegrind</li>
    <li>unit</li>
  </ul>
</details>
<details>
  <summary>17 packages built successfully:</summary>
  <ul>
    <li>adminer</li>
    <li>php (apacheHttpdPackages.php ,php74)</li>
    <li>arcanist</li>
    <li>bookstack</li>
    <li>engelsystem</li>
    <li>icingaweb2</li>
    <li>libsForQt5.kcachegrind (libsForQt515.kcachegrind ,plasma5Packages.kcachegrind)</li>
    <li>lsp-plugins</li>
    <li>matomo</li>
    <li>matomo-beta</li>
    <li>nagios</li>
    <li>nextcloud-news-updater</li>
    <li>phoronix-test-suite</li>
    <li>php80</li>
    <li>qcachegrind</li>
    <li>wp-cli</li>
    <li>yle-dl</li>
  </ul>
</details>

**Comment by risicle** [comment]
Does composer follow semver? Are there any breaking changes with 2.0 -> 2.1?

**Comment by etu** [comment]
@risicle In general composer are very strong proponents of semver in their entire messaging of how people should version composer packages, so I kinda assume that they do the same in their own releases.

Here's the changelog: https://github.com/composer/composer/releases/tag/2.1.0

Should be fine imo.

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15, nixos x86_64

**Pull request merged**
