### PR TITLE
1password: fix sha256 hash

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jb55** [comment]
uhh since this is a password manager, was there any investigation as to why the hash was changed?

**Comment by grahamc** [comment]
@xeji did you test this change prior to merging? I'm surprised nobody called ofborg.

**Comment by xeji** [comment]
@grahamc it's unfree. I built it locally before merging.

**Comment by xeji** [comment]
@grahamc it would be great if ofborg allowed building unfree packages so we could check all architectures before merging. Shouldn't be a license issue if the result doesn't leave the builder's local nix store.

**Comment by jb55** [comment]
I've verified the new hashes, the binaries are signed with the op signing key: https://keybase.io/1password

Please confirm that this has been done before merging, for future hash changes!

Thanks :)

**Comment by xeji** [comment]
@jb55 checking code signatures manually before merging would be a pain since each tarball needs to be unpacked first. It makes more sense to check the signature automatically during build. 
I give that a try in  #42580.

**Pull request merged**
