### PR TITLE
linuxHeaders: 6.4 -> 6.5

### PR DESCRIPTION
**Pull request by trofi**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Will need at least `strace` fix:

```
io_uring.c: In function 'print_io_sqring_offsets':
io_uring.c:48:16: error: 'const struct io_sqring_offsets' has no member named 'resv2'; did you mean 'resv1'?
   48 |         if (p->resv2) {
      |                ^~~~~
      |                resv1
```

**Comment by trofi** [comment]
Asked `strace` if it's reasonable to cut a new upstream release: https://github.com/strace/strace/issues/266

Otherwise we will need to backport or snapshot.

**Comment by trofi** [comment]
`strace` update PR: https://github.com/NixOS/nixpkgs/pull/252919

**Comment by trofi** [comment]
Rebased past `strace` update. Should be ready.

**Comment by trofi** [comment]
Built successfully all direct reverse dependencies: `apparmor-bin-utils apparmor-parser apparmor-utils audacity audit autofs5 ceph ceph-dev dbus-broker duperemove envoy gfxtablet glibcInfo glibcLocales glibcLocalesUtf8 glibc_memusage input-utils jujuutils klibc libapparmor libceph librseq linuxHeaders linuxptp multipath-tools musl mythtv nbd oprofile sc-controller steamcontroller stratovirt systemd systemdMinimal systemdStage1 systemdStage1Network tenacity trafficserver uclibc uclibc-ng udev`

**Comment by marsam** [comment]
@GrahamcOfBorg eval

**Review by marsam — APPROVED** [review]

**Comment by chvp** [comment]
How would I go about fixing the following build failure? https://hydra.nixos.org/build/236408998/nixlog/1

I already created an upstream issue: https://github.com/wangyu-/udp2raw/issues/492

**Comment by trofi** [comment]
The failure says that flexible arrays are attempted to be used in the middle of the struct:

```
/nix/store/y8wfrgk7br5rfz4221lfb9v8w3n0cnyd-glibc-2.37-8-dev/include/linux/if_packet.h:24:17: error: flexible array member 'sockaddr_ll::<unnamed union>::<unnamed struct>::sll_addr_flex' not at end of 'struct packet_info_t'
   24 |                 __DECLARE_FLEX_ARRAY(unsigned char, sll_addr_flex);
      |                 ^~~~~~~~~~~~~~~~~~~~
```

Which seems to be true for `packet_info_t` in `udp2raw`: https://github.com/wangyu-/udp2raw/blob/bc8bd8c2f8434e790defaa69890c9c2c8c1fadd2/network.h#L229

The twist is that it's conditional code:

```
...
#ifdef UDP2RAW_LINUX
    sockaddr_ll addr_ll;
#endif

    i32_t data_len;
```

There are 2 `socladdr_ll` definitions:

`glibc` one (non-flexible):

```
struct sockaddr_ll
  {
    unsigned short int sll_family;
    unsigned short int sll_protocol;
    int sll_ifindex;
    unsigned short int sll_hatype;
    unsigned char sll_pkttype;
    unsigned char sll_halen;
    unsigned char sll_addr[8];
  };
```

and `linuxHeaders` one (flexible):

```
struct sockaddr_ll {
        unsigned short  sll_family;
        __be16          sll_protocol;
        int             sll_ifindex;
        unsigned short  sll_hatype;
        unsigned char   sll_pkttype;
        unsigned char   sll_halen;
        union {
                unsigned char   sll_addr[8];
                /* Actual length is in sll_halen. */
                __DECLARE_FLEX_ARRAY(unsigned char, sll_addr_flex);
        };
};
```

Flexible field added in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/?id=a0ade8404c3bc2bf2631cb0f20d372eed22d9d96

I think the intent of the chance was not to change struct from fixed-size to flexible size. Might be considered a kernel bug?  @q2ven WDYT?

**Comment by q2ven** [comment]
Thanks for reporting!

The commit added a union-ed flex array just for working around fortified memcpy() check.  It does not intend to introduce any regression.

Actually my initial attempt did not touch the struct and fixed the problematic code itself, but a maintainer suggested the current way which causes an error for struct having sockaddr_ll in the middle.
https://lore.kernel.org/netdev/20230720004410.87588-3-kuniyu@amazon.com/

I’ll fix it at the kernel side.

Thank you again!

**Comment by trofi** [comment]
Sounds good. Thank you!

Meanwhile we'll try to revert the change downstream just for `linux-headers` until it's fixed as https://github.com/NixOS/nixpkgs/pull/258761

**Pull request merged**
