### PR TITLE
stalwart-mail: 0.9.0 -> 0.9.1

### PR DESCRIPTION
**Pull request by onny**
## Description of changes

Changelog https://github.com/stalwartlabs/mail-server/releases/tag/v0.9.1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by oddlama — APPROVED** [review]
looks good

**Comment by esclear** [comment]
I noticed that the build for 0.9.0 failed in the test stage: https://hydra.nixos.org/build/268871650 
Do out think this PR fixes this as well?

**Comment by happysalada** [comment]
Ofborg fails with an unrelated error on this run.

**Comment by happysalada** [comment]
@ofborg build

**Comment by philipwilk** [comment]
> I noticed that the build for 0.9.0 failed in the test stage: https://hydra.nixos.org/build/268871650 Do you think this PR fixes this as well?

On 0.9.0 compiling fails at the mail-server step.
[hercules' try](https://hercules-ci.com/accounts/github/philipwilk/derivations/%2Fnix%2Fstore%2Fcaq5pfsnzdjdix3ivczn6j7q5c41jpak-stalwart-mail-0.9.0.drv/log?via-job=98f29d2a-4da3-4757-b63f-27d32b404ed3)

**Comment by esclear** [comment]
`Hmm,` I've tied it multiple times on multiple machines now.
It failed every time.

```
   Compiling jemallocator v0.5.4
   Compiling console v0.15.8
   Compiling rtoolbox v0.0.2
   Compiling is-terminal v0.4.12
   Compiling encode_unicode v1.0.0
   Compiling number_prefix v0.4.0
   Compiling base64 v0.13.1
   Compiling indicatif v0.17.8
   Compiling jmap-client v0.3.2
   Compiling prettytable-rs v0.10.0
   Compiling rpassword v7.3.1
   Compiling clap v4.5.13
   Compiling managesieve v0.9.0 (/build/source/crates/managesieve)
   Compiling pop3 v0.9.0 (/build/source/crates/pop3)
   Compiling human-size v0.4.3
   Compiling tests v0.1.0 (/build/source/tests)
   Compiling stalwart-cli v0.9.0 (/build/source/crates/cli)
   Compiling mail-server v0.9.0 (/build/source/crates/main)
thread 'main' panicked at cargo-auditable/src/rustc_wrapper.rs:101:39:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `mail-server` (bin "stalwart-mail")
error: builder for '/nix/store/caq5pfsnzdjdix3ivczn6j7q5c41jpak-stalwart-mail-0.9.0
.drv' failed with exit code 101
error: 1 dependencies of derivation '/nix/store/c8vjmnhpww3gllf7cjys8vxv8ysj2qq9-ma
n-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6i07r8awbyz32cx19jgpmhcrmkp3xvpd-st
alwart-mail-0.9.0_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l3p6k59nir374ik56c4d63zp5raxrjfw-sy
stem-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y6gxnmcxr3gizxy7ivkgg8j29g56dl8l-un
it-stalwart-mail.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f1dlvam0wqv0v1ck0ip7sasmqrijzhan-ni
xos-system-charon-24.05.3803.c306d09c1dc6.drv' failed to build
```

**Comment by philipwilk** [comment]
yeah that looks like the same place as mine on my multiple hercules builds

**Comment by esclear** [comment]
Interestingly, building from within the nixpkgs repo worked for me with the usual `nix-build -A stalwart-mail` invocation on main.
I only see the error shown above when doing a nixos-rebuild. 🤔

**Comment by onny** [comment]
Result of `nixpkgs-review pr 333507` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 test built:</summary>
  <ul>
    <li>nixosTests.stalwart-mail</li>
  </ul>
</details>

**Comment by onny** [comment]
Result of `nixpkgs-review pr 333507` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 test built:</summary>
  <ul>
    <li>nixosTests.stalwart-mail</li>
  </ul>
</details>

**Comment by onny** [comment]
@philipwilk @esclear could you please try the new version?

**Comment by esclear** [comment]
I haven't had the opportunity to try it yet.

Is there a reason behind deactivating these tests, specifically, @onny?

From when I looked into the build and test problems, they were caused by the system being short on RAM.
Looking at the latest build for 0.9.0, it appears that a lot more tests failed: https://hydra.nixos.org/build/269088992/log

**Comment by onny** [comment]
With the new versions, these two new tests were failing.

@ofborg build stalwart-mail

**Comment by esclear** [comment]
Okay, so these also failed locally for you?

**Comment by esclear** [comment]
Stalwart is, unfortunately, still failing a number of tests on hydra, even with the new changes: https://hydra.nixos.org/build/269871892/nixlog/1

re build times: They seem very long to me as well, on my servers it takes ~2h to build (and at least 14 GiB of RAM) to build stalwart-mail.

As mentioned before, the problem is especially apparent, since stallwart-(cli|main) seems to be built twice (once for testing), even though I fail to see why.

**Comment by philipwilk** [comment]
I just upgraded my build server and successfully built it, but it still took a WHILE. Internet upload upgrade is pending until next week but if you want to pull it because you're getting build failures for it you can get it from ``https://cache.fogbox.uk`` and the signing key is ``cache.fogbox.uk:lwlsX4TZdJXQzfqTWRMf/I8xTlR/i+B5RTkD2BQhzdA=``. [build log](https://hercules-ci.com/accounts/github/philipwilk/derivations/%2Fnix%2Fstore%2F03520czpvfmamkpcr26j5wbjpnjmbpyq-stalwart-mail-0.9.1.drv?via-job=bbac7266-f5f4-46f7-9dd4-91db6b32f69c)

**Pull request merged**
