### PR TITLE
idrisPackages: Fix linking to gmp library and cc

### LINKED ISSUE #54579: idris package missing gmp.h, can't compile hello world.
## Issue description

Trying to compile fails with 

```
~/projects/idrissandbox 2m 6s
❯ idris -o main Main.idr
In file included from /nix/store/4sbvpzm6lvjr9cz8cmghjhb35i60irhj-idris-1.3.1-data/share/ghc-8.6.3/x86_64-linux-ghc-8.6.3/idris-1.3.1/rts/idris_rts.h:522:0,
                 from /tmp/idris5886-0.c:2:
/nix/store/4sbvpzm6lvjr9cz8cmghjhb35i60irhj-idris-1.3.1-data/share/ghc-8.6.3/x86_64-linux-ghc-8.6.3/idris-1.3.1/rts/idris_gmp.h:5:10: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
          ^~~~~~~
compilation terminated.
FAILURE: "/nix/store/isg8rxaxkijl9x3hr2gzsf8pqfnqxg3k-gcc-wrapper-7.4.0/bin/gcc" ["-fwrapv","-fno-strict-overflow","-std=c99","-pipe","-fdata-sections","-ffunction-sections","-D_POSIX_C_SOURCE=200809L","-DHAS_PTHREAD","-DIDRIS_ENABLE_STATS","-I.","-Wl,-gc-sections","/tmp/idris5886-0.c","-L/nix/store/4sbvpzm6lvjr9cz8cmghjhb35i60irhj-idris-1.3.1-data/share/ghc-8.6.3/x86_64-linux-ghc-8.6.3/idris-1.3.1/rts","-lidris_rts","-lgmp","-DIDRIS_GMP","-lpthread","-I/nix/store/4sbvpzm6lvjr9cz8cmghjhb35i60irhj-idris-1.3.1-data/share/ghc-8.6.3/x86_64-linux-ghc-8.6.3/idris-1.3.1/rts","-lm","-I.","-I/nix/store/mma2ff9v5c7s50r9md8xxfw9qv58bfh3-idris-1.3.1/libs/prelude","-I/nix/store/mma2ff9v5c7s50r9md8xxfw9qv58bfh3-idris-1.3.1/libs/base","-I.","-I/nix/store/wsm1zzcrhlc0scs4hfsrv05ba1932d75-idris-1.3.1/libs/prelude","-I/nix/store/wsm1zzcrhlc0scs4hfsrv05ba1932d75-idris-1.3.1/libs/base","-o","main"]

```

### Steps to reproduce
Install `idris` (not `idrisPackages.idris`)
Create Main.idr with 

```
module Main

main : IO ()
main = putStrLn "Hello, World"
```
run `idris -o main Main.idr`

observe error

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.3, NixOS, 19.03pre167225.1b3affcbaa8 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.03pre167225.1b3affcbaa8"`
 - channels(aria): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by infinisil**
Fixes https://github.com/NixOS/nixpkgs/issues/54579 and probably https://github.com/NixOS/nixpkgs/issues/52796

Ping @ar1a @marsam @shmish111 @mpickering 

This has been broken since 5d18129ce8af9a69312818ea0a5a0029a04a2255,
which updated idris from 1.3.0 to 1.3.1, which included
https://github.com/idris-lang/Idris-dev/pull/4472 as the cause of the
error. I'm still not entirely sure why this broke it though.

This way should be rather future proof, it uses NIX_CFLAGS to pass
gpm link flags to our CC wrapper directly. The
`NIX_CC_WRAPPER_${stdenv.cc.infixSalt}_TARGET_HOST` part I'm pretty sure
is needed for the CC wrapper to know that those CFLAGS are meant for the
cc running on the HOST.

The second commit just switches to stdenv's cc.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg build idrisPackages.contrib

**Comment by Infinisil** [comment]
Okay well that's weird. I tried building `idrisPackages.contrib` locally on my mac, which failed with an error that some Idris typeclass wasn't known (`DecEq` specifically). I am running a very outdated macOS and nix version though, so not sure. @GrahamcOfBorg seems to not have had any problems. Let's try a couple more libraries

@GrahamcOfBorg build idrisPackages.effects idrisPackages.glfw idrisPackages.html idrisPackages.http idrisPackages.idrisscript idrisPackages.pipes idrisPackages.webgl idrisPackages.yaml

And also some of the currently failing ones on Darwin:

@GrahamcOfBorg build idrisPackages.bi idrisPackages.config idrisPackages.electron idrisPackages.eternal idrisPackages.ipkgparser idrisPackages.mhd

**Comment by Infinisil** [comment]
State of builds:
- On x86_64, everything builds
- On aarch, there's lots of timeouts, but no failures
- For the usually succeeding effects, glfw, ... packages, on darwin the `contrib` dependency now failed, even though it succeeded when I told it to build it earlier.. It failed with the same error I encountered regarding `DecEq`, maybe an impurity? This is the check with idrisPackages.contrib failing as a dependency: https://github.com/NixOS/nixpkgs/pull/58319/checks?check_run_id=87664056, and this is the one where it failed standalone: https://github.com/NixOS/nixpkgs/pull/58319/checks?check_run_id=87621971. I doubt that the different master version at these different times would've had an influence. @grahamc Can you perhaps check what versions of macOS these two builds used?
- For the usually failing bi, config, ..., on darwin only two of them failed, soo success?

**Comment by Infinisil** [comment]
@GrahamcOfBorg build idrisPackages.contrib

**Comment by Infinisil** [comment]
@GrahamcOfBorg build idrisPackages.contrib

**Comment by ar1a** [comment]
This closes #54579

**Comment by Infinisil** [comment]
@GrahamcOfBorg build idrisPackages.contrib

**Comment by Infinisil** [comment]
Doesn't solve the darwin issue.. I have no idea what's up with that tbh. Maybe something during the compilation of Prelude failed, making DecEq unavailable, dunno

I think I'll just merge this for now, idris currently is in an almost unusable state, so anything is an improvement.

**Comment by Infinisil** [comment]
Not sure what to do about this right now. There's clearly a regression here, on my mac idrisPackages.contrib doesn't build anymore, but no idea where it comes from.

**Comment by ar1a** [comment]
you may get some insight from #idris or perhaps create an issue

**Comment by Infinisil** [comment]
I'll just merge this now, idris is almost unusable without this

**Comment by Infinisil** [comment]
Seems to build just fine on macOS Mojave, but not on High Sierra. So this problem should automatically disappear as hydra and people update their version

**Comment by rycee** [comment]
Been playing around with Idris and notice that this issue seem to affect 19.03, would any mind if I backport this? Seems to work well for me.

**Comment by Infinisil** [comment]
@rycee Sounds good

**Comment by rycee** [comment]
Cool, done 🙂

**Pull request merged**
