### PR TITLE
Make numpy and scipy depend on openblas

### PR DESCRIPTION
**Pull request by adnelson**
This configures numpy and scipy to use the openblas framework for their linear algebra operations, which seems preferable since it reduces the number and complexity of dependencies (a single library for BLAS and LAPACK). In addition openblas seems to be a lighter-weight dependency (in terms of build time, not sure about size) than ATLAS. In addition, on OSX, the numpy setup.py (and presumably scipy) will impurely check for the existence of the `Accelerate` framework, and if found, will pass it as an argument to `clang`, which will fail. It will not do this if there's a `site.cfg` telling it where to find `openblas`. This keeps things pure, and also makes it cross-platform.

### CODE REVIEW

**Comment by adnelson** [comment]
@domenkozar @spwhitt @ttuegel

**Comment by domenkozar** [comment]
We already had that once and had to revert. I'll look into the reasons why.

**Comment by spwhitt** [comment]
History of numpy and openblas is here https://github.com/NixOS/nixpkgs/pull/6381 and here https://github.com/NixOS/nixpkgs/issues/6772.

**Comment by adnelson** [comment]
Hmm, well that's unfortunate. I'm curious whether this is fixed with numpy 1.9.2. I'm building it right now and we'll see.

**Comment by adnelson** [comment]
Ugh, OK well I'm getting a segfault in the numpy tests when building with openblas. Yikes. Googling around I don't see anyone else getting this issue but I might investigate further... I guess for now sticking with atlas is the best.

I suppose one thing that I could do is attempt to write a custom test function so that we can confirm that it works, as currently numpy has `doCheck = false`.

**Comment by adnelson** [comment]
For the record, here's the output I'm getting with openblas:

```
>>> import numpy
>>> numpy.test('full', verbose=10)
Running unit tests for numpy
NumPy version 1.9.2
NumPy is installed in /nix/store/mp2y8m2sdr4fvrl850wsq1kxlf87bk53-python2.7-numpy-1.9.2/lib/python2.7/site-packages/numpy
Python version 2.7.10 (default, Jan 01 1970, 00:00:01) [GCC 4.2.1 Compatible Clang 3.6.0 (tags/RELEASE_360/final)]
nose version 1.3.4
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.config: INFO: Excluding tests matching ['f2py_ext', 'f2py_f90_ext', 'gen_ext', 'pyrex_ext', 'swig_ext']
test_complex (test_abc.ABC) ... ok
test_floats (test_abc.ABC) ... ok
test_int (test_abc.ABC) ... ok
test_uint (test_abc.ABC) ... ok
test_api.test_array_array ... ok
test_api.test_fastCopyAndTranspose ... ok
test_api.test_array_astype ... ok
test_api.test_copyto_fromscalar ... ok
test_api.test_copyto ... ok
test_api.test_copyto_permut ... ok
test_api.test_copy_order ... ok
test_api.test_contiguous_flags ... ok
test_api.test_broadcast_arrays ... ok
Basic test of array2string. ... ok
Test custom format function for each element in array. ... ok
This should only apply to 0-D arrays. See #1218. ... ok
test_arrayprint.TestArrayRepr.test_nan_inf ... ok
test_str (test_arrayprint.TestComplexArray) ... ok
test_arrayprint.TestPrintOptions.test_basic ... ok
test_arrayprint.TestPrintOptions.test_formatter ... ok
test_arrayprint.TestPrintOptions.test_formatter_reset ... ok
test_arrayprint.test_unicode_object_array ... ok
Ticket 844. ... ok
test_blasdot.test_blasdot_used ... ok
test_blasdot.test_dot_2args ... [1]    22018 segmentation fault  result/bin/np_test
```

**Comment by adnelson** [comment]
Closing this in favor of #8045

**Comment by ttuegel** [comment]
Segfault is due to OpenBLAS using `INTERFACE64=1`, which is incompatible with reference BLAS and LAPACK. A fix is on the way (later today, probably).

**Pull request closed without merging**
