### PR TITLE
resholve: 0.6.9 -> 0.8.0 + API reorganization

### PR DESCRIPTION
**Pull request by abathur**
@happysalada This one's a little chunky (but less complex than it looks; a lot of the churn is just renames). Do you have bandwidth/interest this time around?

###### Description of changes

- Update resholve to 0.8.0
    - [0.7.0](https://github.com/abathur/resholve/blob/master/CHANGELOG.md#v070-april-8-2022) fixes a few issues and improves resholve's ability to handle packages that invoke intra-package executables.
    - [0.8.0](https://github.com/abathur/resholve/blob/master/CHANGELOG.md#v080-april-8-2022) reorganizes resholve's Nix api (folding it into resholve's passthru, renaming functions).
- Update binlore, a dependency for resholve's Nix API, to 0.2.0 ([changelog](https://github.com/abathur/binlore/blob/main/CHANGELOG.md#v020-april-7-2022))
- Track upstream changes to resholve's Nix API; add aliases and a release note noting the renames. (There's a more verbose description of the reorganization in https://github.com/abathur/resholve/commit/bb29c2402e55353ec04f7fa45d338f93b56ea5fa)
- Change `pkgs/` uses of `resholvePackage` to `resholve.mkDerivation`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

###### nixpkgs-review:
Result of `nixpkgs-review` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>bash-preexec</li>
    <li>bashup-events32</li>
    <li>bashup-events44</li>
    <li>bats</li>
    <li>pdf2odt</li>
    <li>resholve</li>
    <li>shunit2</li>
    <li>yadm</li>
  </ul>
</details>

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>arch-install-scripts</li>
    <li>bash-preexec</li>
    <li>bashup-events32</li>
    <li>bashup-events44</li>
    <li>bats</li>
    <li>dgoss</li>
    <li>pdf2odt</li>
    <li>resholve</li>
    <li>shunit2</li>
    <li>yadm</li>
  </ul>
</details>

### CODE REVIEW

**Comment by abathur** [comment]
I queried on matrix about the ofborg eval error; I guess trace is not OK for this purpose. I'll update these to use throw and force-push when I get back home.

**Comment by happysalada** [comment]
I read all and couldn't find anything to improve. I only have trivial feedback (there is one sentence that is a little ambiguous in the release, but I don't think it matters).

Thank you for your work on this!

I'm not using a lot of nix at the moment, but these are on my list of stuff to take out for a spin next!

**Comment by abathur** [comment]
@grahamc @cole-h @clkamp @toonn @kwbauson @ninlives @utdemir I think you all have some uses of resholve; just a heads-up that when this PR is available in nixpkgs you'll need some renames:
  - `resholvePackage` -> `resholve.mkDerivation`
  - `resholveScript` -> `resholve.writeScript`
  - `resholveScriptBin` -> `resholve.writeScriptBin`

**Comment by abathur** [comment]
@tejing noticed your new public uses of resholveScript and resholveScriptBin today; just wanted to make sure this rename doesn't surprise you later :)

See post above for replacements.

**Pull request merged**
