### PR TITLE
tmux: fix tmux sha256 hash

### PR DESCRIPTION
**Pull request by ookhoi**
###### Motivation for this change
fix:
```
unpacking source archive /build/2.8.tar.gz
fixed-output derivation produced path '/nix/store/5ffizfra8bqflflbi985d6y427ndq8a9-source' with sha256 hash '1fy87wvxn7r7jzqapvjisc1iizic3kxqk2lv83giqmw1y4g3s7rl' instead of the expected hash '0n8sjddy00xgh1rvvw968hh72pyslg1gahmzajfc4b3xax87drpi'
repairing outputs of '/nix/store/9h7m55sxcn1ah8fxynkfzk0gxhv31yl6-synctex-missing-header.patch.drv'...
cannot build derivation '/nix/store/inbx3y8s5ni778smbbzszhwpx5jq44jk-tmux-2.8.drv': 1 dependencies couldn't be built
repairing outputs of '/nix/store/0g3ab8b617jcl0qw7xympfnwz2a29rlv-token_store-0.1.2.tar.gz.drv'...
repairing outputs of '/nix/store/yq9kh0w74chi9w8rz97ff9wsd6iy82g9-sysfsutils-2.1.0.tar.gz.drv'...
repairing outputs of '/nix/store/gli61d3b5hykmzii2xsmav2wsj31kr71-system-generators.drv'...
cannot build derivation '/nix/store/3g0iz00kxpb46p96akiagzy5c5851d74-system-path.drv': 1 dependencies couldn't be built
repairing outputs of '/nix/store/d1f7gjdm5axz0ai1ia4f6jg0w9prn9pb-tcl8.6.6-src.tar.gz.drv'...
repairing outputs of '/nix/store/4qgyaa4c2qm599xylak4ms7704ml5ja0-thin-provisioning-tools-0.7.6.drv'...
cannot build derivation '/nix/store/s21w2jrs9p5wl2xijz494c5skzr40rxk-nixos-system-p70-19.03pre157041.64553463956.drv': 1 dependencies couldn't be built
error: build of '/nix/store/s21w2jrs9p5wl2xijz494c5skzr40rxk-nixos-system-p70-19.03pre157041.64553463956.drv' failed
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by andir** [comment]
@grahamcofborg build tmux

**Comment by andir** [comment]
@ookhoi can you adjust the commit message to fit the format described in CONTRIBUTING.MD ?

I am a bit inclined to say we should switch to the got revision instead of tags.. They seem to not honor the concept of release tags.. Or github changed something there...

**Comment by vcunat** [comment]
Uh, did they move tags again?  a6dc11e81e2cf26c  That seems a bad practice.  For this expression we could use hashes instead of tag names to specify the revision to download, but that would be relatively ugly.

**Comment by LnL7** [comment]
I don't get any hash mismatches, both on linux and darwin.

```
$ nix-build -A tmux.src --check
checking outputs of '/nix/store/4glcwlmsrgwjr4lnjvaz9xmgmqc5ajgc-source.drv'...

trying https://github.com/tmux/tmux/archive/2.8.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   114    0   114    0     0    217      0 --:--:-- --:--:-- --:--:--   217
100  622k    0  622k    0     0   364k      0 --:--:--  0:00:01 --:--:-- 1420k
unpacking source archive /build/2.8.tar.gz
/nix/store/ajlv30w3yzqsjsb6rrwrr8v478fgjf30-source
```

**Comment by ookhoi** [comment]
> @ookhoi can you adjust the commit message to fit the format described in CONTRIBUTING.MD ?

Of course, is it correct now?

> I am a bit inclined to say we should switch to the got revision instead of tags..

I'm affraid I do not understand but I suspect it will make the tmux fetch more robust. What should I change for that?

**Comment by ookhoi** [comment]
> I don't get any hash mismatches, both on linux and darwin.

I'm on https://nixos.org/channels/nixos-unstable-small (not sure if that matters)

**Comment by c0bw3b** [comment]
There was a [change 11d ago](https://github.com/tmux/tmux/commits/2.8) because configure.ac was still mentioning "2.8-rc"
Bad practice but hopefully this should not happen too often...

**Comment by vcunat** [comment]
`--check` succeeds for me both before this PR and after it, so something is wrong, perhaps with `--check`?

**Comment by vcunat** [comment]
Here, logs of checking the same fetching derivation, different results within a couple minutes.

```
checking outputs of '/nix/store/4glcwlmsrgwjr4lnjvaz9xmgmqc5ajgc-source.drv'...

trying https://github.com/tmux/tmux/archive/2.8.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   114    0   114    0     0    223      0 --:--:-- --:--:-- --:--:--   223
100  622k    0  622k    0     0   216k      0 --:--:--  0:00:02 --:--:--  312k
unpacking source archive /build/2.8.tar.gz
/nix/store/ajlv30w3yzqsjsb6rrwrr8v478fgjf30-source
```

vs.

```
checking outputs of '/nix/store/4glcwlmsrgwjr4lnjvaz9xmgmqc5ajgc-source.drv'...

trying https://github.com/tmux/tmux/archive/2.8.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   114    0   114    0     0    205      0 --:--:-- --:--:-- --:--:--   204
100  622k    0  622k    0     0   332k      0 --:--:--  0:00:01 --:--:--  855k
unpacking source archive /build/2.8.tar.gz
fixed-output derivation produced path '/nix/store/5ffizfra8bqflflbi985d6y427ndq8a9-source' with sha256 hash '1fy87wvxn7r7jzqapvjisc1iizic3kxqk2lv83giqmw1y4g3s7rl' instead of the expected hash '0n8sjddy00xgh1rvvw968hh72pyslg1gahmzajfc4b3xax87drpi'
error: build of '/nix/store/4glcwlmsrgwjr4lnjvaz9xmgmqc5ajgc-source.drv' failed
```

**Comment by xeji** [comment]
Strange that we seem to get different results. On my local linux machine the new hash looks correct:

```
$ nix-prefetch-url https://github.com/tmux/tmux/archive/2.8.tar.gz --unpack
unpacking...
path is '/nix/store/vffvjc24xxvjywpqmcsns7lfin7wr68q-2.8.tar.gz'
1fy87wvxn7r7jzqapvjisc1iizic3kxqk2lv83giqmw1y4g3s7rl
```

**Comment by xeji** [comment]
@ookhoi since upstream seems to have moved the tag, let's pin this to the corresponding upstream git commit instead of the version tag to ensure it's stable:

```
-    rev = version;
+    rev = "01918cb0170e07288d3aec624516e6470bf5b7fc";
```

**Comment by ookhoi** [comment]
> @ookhoi since upstream seems to have moved the tag, let's pin this to the corresponding upstream git commit instead of the version tag to ensure it's stable:
> 
> ```
> -    rev = version;
> +    rev = "01918cb0170e07288d3aec624516e6470bf5b7fc";
> ```

Sorry for the delay @xeji 
I've replaced `version` with `"01918cb0170e07288d3aec624516e6470bf5b7fc"` and am currently building.

**Comment by ookhoi** [comment]
I'm running `tmux 2.8` now

**Comment by xeji** [comment]
@GrahamcOfBorg build tmux

**Pull request merged**
