### PR TITLE
update etcher version - will update to electron v25

### PR DESCRIPTION
**Pull request by andar1an**
## Description of changes

https://github.com/balena-io/etcher/commit/f38bca290fe26121bed58d1131265e1aa350ddb5 (patch: upgrade to electron 25, 2023-08-30)
https://github.com/balena-io/etcher/commit/fb8ed5b529e22bc9e766bfe99c2b6955ed695b58 (patch: refactor scanner, loader and flasher out of gui + upgrade to electron 25, 2023-08-30)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

:+1:  - Security related update
cc @wegank

### CODE REVIEW

**Comment by stephenandary** [comment]
This is my first pull request for a pkg update, please let me know if I did something wrong, or did not do something I was supposed to do.

**Comment by wegank** [comment]
There is an unresolved problem upstream (balena-io/etcher#4138) that blocks all previous update attempts at #261626 and #263729. Have you actually tested flashing an image onto a USB stick using your build?

**Comment by stephenandary** [comment]
No, I will look up how to build locally to test.

**Comment by stephenandary** [comment]
Do you happen to know of any blog or easily digestible content related to building and testing packages for nikpgs? 

I found this in the docs <https://github.com/jtojnar/nixpkgs-hammering>, there is a lot to read though, and something more concise would be helpful if you know of anything.

**Comment by wegank** [comment]
For contributions to nixpkgs, you can find some instructions in [pkgs/README.md](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#quick-start-to-adding-a-package). Specifically, for building etcher, you'll need to run this from the root of the nixpkgs source tree:

```bash
$ NIXPKGS_ALLOW_INSECURE=1 nix-build -A etcher
```

`NIXPKGS_ALLOW_INSECURE=1` is something that will be prompted when running `nix-build -A etcher`, since both Electron 19 and 25 are marked as insecure in nixpkgs.

**Comment by stephenandary** [comment]
> For contributions to nixpkgs, you can find some instructions in [pkgs/README.md](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#quick-start-to-adding-a-package). Specifically, for building etcher, you'll need to run this from the root of the nixpkgs source tree:
> 
> ```shell
> $ NIXPKGS_ALLOW_INSECURE=1 nix-build -A etcher
> ```
> 
> `NIXPKGS_ALLOW_INSECURE=1` is something that will be prompted when running `nix-build -A etcher`, since both Electron 19 and 25 are marked as insecure in nixpkgs.

Oh no, I was hoping going to 25 would remove that security prompt. Thank you for this, I am doing now.

**Comment by stephenandary** [comment]
It builds, I will test package now with `sudo nixos-rebuild switch -I nixpkgs=/path/to/local/nixpkgs` and see what happens.

**Comment by stephenandary** [comment]
Seemed to flash for me, and validated.  I did receive a partition table warning, but I imagine that is because of the image I had on this USB already.
image

**Comment by stephenandary** [comment]
Seems when I comment out the permittedInsecurePackages config, that it is still referencing electron-19.1.9 when the subsequent error occurs. 

I ran this command: `sudo nixos-rebuild switch -I nixpkgs=/home/stephen/Repos/github/nixpkgs --flake /home/stephen/Repos/gitlab/flakes/machines#tor-dev-01`

**Comment by wegank** [comment]
> Update: I think I need to update the electron dependency version somehow in the PR. Local path works in flake, but still reverences v19.1.9. Looking into now, but I don't see how the dependency version is determined yet in etcher default.nix. I do see electron passed in as input though, so will trace.

For doing this, you also have to change `electron_19` to `electron_25` somewhere in the `pkgs/top-level/all-packages.nix`.

But what's interesting is that you've discovered that Electron 1.18.13 works with Electron 19. I'll check whether this is the case on my machine, and if it is, we can definitely do the upgrade.

**Comment by stephenandary** [comment]
> > Update: I think I need to update the electron dependency version somehow in the PR. Local path works in flake, but still reverences v19.1.9. Looking into now, but I don't see how the dependency version is determined yet in etcher default.nix. I do see electron passed in as input though, so will trace.
> 
> For doing this, you also have to change `electron_19` to `electron_25` somewhere in the `pkgs/top-level/all-packages.nix`.
> 
> But what's interesting is that you've discovered that Electron 1.18.13 works with Electron 19. I'll check whether this is the case on my machine, and if it is, we can definitely do the upgrade.

I need to learn about all-packages.nix now, but was hoping this upgrade would move etcher to electron 25 also.

**Comment by wegank** [comment]
> But what's interesting is that you've discovered that Electron 1.18.13 works with Electron 19. I'll check whether this is the case on my machine, and if it is, we can definitely do the upgrade.

This is not the case on my machine, unfortunately... Does Etcher report itself as 1.18.13 when clicked on the settings button?

**Comment by stephenandary** [comment]
> > But what's interesting is that you've discovered that Electron 1.18.13 works with Electron 19. I'll check whether this is the case on my machine, and if it is, we can definitely do the upgrade.
> 
> This is not the case on my machine, unfortunately... Does Etcher report itself as 1.18.13 when clicked on the settings button?

No, 1.18.2. I will restart machine and see if that changes anything.

**Comment by stephenandary** [comment]
Builds have been taking a long time since clearing garbage and restarting. I am going to put a pin in this for today.

**Comment by stephenandary** [comment]
I won't have time to finish this so closing.

**Pull request closed without merging**
