### PR TITLE
lite: init at 1.03

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
https://github.com/rxi/lite/releases/tag/v1.03

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by utdemir** [comment]
I got an error running it on NixOS:

```
❯ git rev-parse --short HEAD
65e441dc63c
❯ $(nix-build -A lite --builders "")/bin/lite
Error: [string "local core..."]:7: module 'core' not found:
	no field package.preload['core']
	no file '/nix/store/2w58n6psn9ax6qiyin18ix9xljdnlg11-lite-1.03/bin/data/core/init.lua'
	no file '/nix/store/2w58n6psn9ax6qiyin18ix9xljdnlg11-lite-1.03/bin/data/core.lua'
	no file '/usr/local/share/lua/5.2/core.lua'
	no file '/usr/local/share/lua/5.2/core/init.lua'
	no file '/usr/local/lib/lua/5.2/core.lua'
	no file '/usr/local/lib/lua/5.2/core/init.lua'
	no file './core.lua'
	no file '/usr/local/lib/lua/5.2/core.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './core.so'
stack traceback:
	[C]: in function 'require'
	[string "local core..."]:7: in function <[string "local core..."]:2>
	[C]: in function 'xpcall'
	[string "local core..."]:2: in main chunk
```

**Comment by HugoReeves** [comment]
Possibly a duplicate of #87434 
As it was the first PR and seems to have slightly more feedback, you may want to ask the author of #87434 to add you as one of the maintainers on their PR.

**Comment by prusnak** [comment]
The bug above is fixed in my PR https://github.com/NixOS/nixpkgs/pull/87434

@filalex77 I'll add you as a maintainer in my PR and we can close this PR, agreed?

**Comment by filalex77** [comment]
@prusnak Yeah, sure!

**Comment by prusnak** [comment]
OK, added.

Closing. Superseded by https://github.com/NixOS/nixpkgs/pull/87434

**Pull request closed without merging**
