### PR TITLE
trivial: fetchurl more securely

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change
Obvious.

###### Things done

- [X] Makes no changes to actual derivations.

### CODE REVIEW

**Comment by grahamc** [comment]
Nice.

**Comment by oxij** [comment]
I hate to assault you at random places, but can you also merge

- #34778 (trivial)
- #33898 (discussed before, all issues fixed)
- #29440 (the not-cherry-picked patches are mostly trivial, I run on top of this for months)
- #27688 (its awesome, I have patches that depend on this and run on top if it for months)

**Comment by oxij** [comment]
I hate to assault you at random places, but can you please also merge

- #34778 (trivial)
- #33898 (discussed before, all issues fixed)
- #29440 (the not-cherry-picked patches are mostly trivial, I run on top of this for months)
- #27688 (its awesome, I have patches that depend on this and run on top if it for months)

**Comment by grahamc** [comment]
I don't feel comfortable merging the last one, but I sent mail to the mailing list about it. Thanks for the pings, glad to get these merged :)

**Comment by oxij** [comment]
> I don't feel comfortable merging the last one, but I sent mail to the mailing list about it. Thanks for the pings, glad to get these merged :)

Fair enough. Huge thanks!

**Pull request merged**
