### PR TITLE
meson: 0.61.2 -> 0.63.0

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
https://mesonbuild.com/Release-notes-for-0-62-0.html
https://mesonbuild.com/Release-notes-for-0-63-0.html

built `dav1d`, `qemu`, `systemd` and `mesa` for testing on `x86_64-linux`.
also a subset of them cross to `aarch64-linux` and native on `aarch64-linux`

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
`mesa` and `qemu` don't build with this, because `wayland-protocols` fail with a bunch of messages like this:
```
[82/277] Compiling C++ object tests/test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.p/meson-generated_.._test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.cc.o
FAILED: tests/test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.p/meson-generated_.._test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.cc.o 
g++ -Itests/test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.p -Itests -I../tests -I/nix/store/26irg7wnjyfh7w1dd3mbd2qp6jcvbmy5-wayland-1.20.0-dev/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -O0 -Wall -Werror -MD -MQ tests/test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.p/meson-generated_.._test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.cc.o -MF tests/test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.p/meson-generated_.._test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.cc.o.d -o tests/test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.p/meson-generated_.._test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.cc.o -c tests/test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.cc
In file included from /nix/store/x35d72904sc58is4j4lsgzh3jkbidig4-glibc-2.34-210-dev/include/bits/libc-header-start.h:33,
                 from /nix/store/x35d72904sc58is4j4lsgzh3jkbidig4-glibc-2.34-210-dev/include/stdint.h:26,
                 from /nix/store/zs6hnk47hcrrcrd885d66xmhlvp05jxm-gcc-11.3.0/lib/gcc/x86_64-unknown-linux-gnu/11.3.0/include/stdint.h:9,
                 from /build/wayland-protocols-1.25/build/tests/idle-inhibit-unstable-v1-client.h:6,
                 from tests/test-build-cxx-unstable_idle_inhibit_idle_inhibit_unstable_v1_xml.cc:1:
/nix/store/x35d72904sc58is4j4lsgzh3jkbidig4-glibc-2.34-210-dev/include/features.h:412:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  412 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1plus: all warnings being treated as errors

**Comment by ajs124** [comment]
Seems to come from https://github.com/mesonbuild/meson/pull/9287, se we can fix it by setting hardeningDisable, but that doesn't seem great, especially since it's only needed for the tests. Ideas?

**Comment by alyssais** [comment]
We should set `mesonBuildType` to `debugoptimized` or `release` for wayland-protocols, I think.

And probably reconsider our default of "plain", because I don't think it's a good idea to be building all our packages that use Meson with `-O0` by default.

([Upstream docs](https://mesonbuild.com/Builtin-options.html#core-options))

**Comment by jtojnar** [comment]
See also https://github.com/NixOS/nixpkgs/pull/171069.

**Comment by jtojnar** [comment]
> And probably reconsider our default of "plain", because I don't think it's a good idea to be building all our packages that use Meson with `-O0` by default.

Huh? Should not `-O2` be on, when we have hardening enabled by default?

https://github.com/NixOS/nixpkgs/blob/3567e122f4d5bd1f2ef157e76e827077e037f78b/pkgs/stdenv/generic/make-derivation.nix#L173-L187
https://github.com/NixOS/nixpkgs/blob/3567e122f4d5bd1f2ef157e76e827077e037f78b/pkgs/build-support/cc-wrapper/add-hardening.sh#L41

**Comment by ajs124** [comment]
This can probably be closed in in favor of #171069 then?

**Pull request closed without merging**
