### PR TITLE
r-modules: regenerate CRAN packages

### PR DESCRIPTION
**Pull request by michelk**
cc @peti

### CODE REVIEW

**Comment by peti** [comment]
@michelk, the updated version generates various evaluation errors: http://hydra.cryp.to/jobset/nixpkgs/r-updates#tabs-errors.

**Comment by michelk** [comment]
I ran `nix-build test-evaluation.nix --dry-run` after upgrading. No errors popped up.

**Comment by peti** [comment]
Yes, unfortunately that script does not catch all errors. :disappointed: Some issues pop only once you actually try to build all those packages, like `hydra.cryp.to` does. Anyway, those issues are real. Do you think you'll have a chance to look into them?

**Comment by michelk** [comment]
I'll try to look at it this afternoon.

**Comment by michelk** [comment]
See #12181.

Do you have a convenient method to update this list?

**Comment by peti** [comment]
I don't have a convenient solution for this problem either, unfortunately. :disappointed:

**Pull request merged**
