### PR TITLE
python311Packages.django-countries: 7.5.1 -> 7.6.1

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/SmileyChris/django-countries/blob/v7.6.1/CHANGES.rst

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mweinelt** [comment]
Bisecting the pretalx test failure.

**Comment by SuperSandro2000** [comment]
The error is:
```
pretalx # [   15.395075] systemd[1]: Starting pretalx web service...
pretalx # [   15.398618] systemd[1]: Started pretalx asynchronous job runner.
pretalx # [   15.730421] pretalx-web-pre-start[971]: Traceback (most recent call last):
pretalx # [   15.732886] pretalx-web-pre-start[971]:   File "/nix/store/fh5xid09q779f8rngr7rr2x9fxciq7py-python3-3.11.8-env/bin/pretalx-manage", line 6, in <module>
pretalx # [   15.734078] pretalx-web-pre-start[971]:     os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pretalx.settings")
pretalx # [   15.734918] pretalx-web-pre-start[971]:     ^^
pretalx # [   15.735388] pretalx-web-pre-start[971]: NameError: name 'os' is not defined
pretalx # [   15.743353] systemd[1]: pretalx-web.service: Control process exited, code=exited, status=1/FAILURE
```

and someone one of our hooks ate `import os`

```
 ➜ cat /nix/store/m03p5n5wf82xdwcjgynjljdbiaf4l4gi-python3-3.11.8-env/bin/pretalx-manage
#!/nix/store/m03p5n5wf82xdwcjgynjljdbiaf4l4gi-python3-3.11.8-env/bin/python3.11
import sys;import site;import functools;sys.argv[0] = '/nix/store/1np1h3vx4nbli4d00kbfc342yy2c3jqc-pretalx-2024.1.0/bin/pretalx-manage';functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/1np1h3vx4nbli4d00kbfc342yy2c3jqc-pretalx-2024.1.0/lib/python3.11/site-packages','/nix/store/kd3qkj6j3vfrwmdqg0qss5m6pl2j0h96-python3.11-beautifulsoup4-4.12.3/lib/python3.11/site-packages','/nix/store/712l49an61zhd6bb8aks9ydkj423zc84-python3.11-chardet-5.2.0/lib/python3.11/site-packages','/nix/store/f1bavyxqhv96a8rv2gh980s9s3d65y5l-python3.11-soupsieve-2.5/lib/python3.11/site-packages','/nix/store/3kghw9mw6bpvxbb4p0y28rqnwjlhyjk5-python3.11-bleach-6.1.0/lib/python3.11/site-packages','/nix/store/5008f6jqxbs9ygxphndi4d8f694l2av7-python3.11-html5lib-1.1/lib/python3.11/site-packages','/nix/store/9z56ljqk4ahpx4fj01d82yr0dra6kyvl-python3.11-six-1.16.0/lib/python3.11/site-packages','/nix/store/2w2v00sn8z0ixp9j3fh7imzvk0bf0v8z-python3.11-webencodings-0.5.1/lib/python3.11/site-packages','/nix/store/vy23p29z57xd9r7lmpdqhdbqv8rkvw7n-python3.11-packaging-24.0/lib/python3.11/site-packages','/nix/store/4718wmk03wr3554kmf09vy80vkdjvq56-python3.11-setuptools-69.1.1/lib/python3.11/site-packages','/nix/store/2kz7z5ni83dn0sain03r7il6r2z5dy2z-python3.11-celery-5.3.6/lib/python3.11/site-packages','/nix/store/j96l98s6wvw8byf5abpy4w10flgb1prq-python3.11-billiard-4.2.0/lib/python3.11/site-packages','/nix/store/fslvacr1jmwrlhmf5dnc4avgfg4zvz92-python3.11-click-8.1.7/lib/python3.11/site-packages','/nix/store/sszh0zsdzmmfcj4mvgxp2z2ax3pgwj8x-python3.11-click-didyoumean-0.3.0/lib/python3.11/site-packages','/nix/store/wavv1fmh3a7v1ycgbngycvlycfj8q5z0-python3.11-click-plugins-1.1.1/lib/python3.11/site-packages','/nix/store/kmypm0vyq63bvwwhsp0b576r90v2mhk6-python3.11-click-repl-0.3.0/lib/python3.11/site-packages','/nix/store/sv3fwj87naw4waw5w31mffs5lj86snz1-python3.11-prompt-toolkit-3.0.43/lib/python3.11/site-packages','/nix/store/7nr6ahqcdg1h7m5zcsig1bgxnw3mcl38-python3.11-wcwidth-0.2.13/lib/python3.11/site-packages','/nix/store/1vvcyj17hqwph2vlzfkxc95ky4jq4xmx-python3.11-kombu-5.3.5/lib/python3.11/site-packages','/nix/store/3lp46bmhlpi0kdc69bz76g3v08ccqy4m-python3.11-amqp-5.2.0/lib/python3.11/site-packages','/nix/store/i7a2r9lx792rfqbrgzwq4jy6inadzcma-python3.11-vine-5.1.0/lib/python3.11/site-packages','/nix/store/bvihsbc449fdw7h57bn84vwxmpp2is7f-python3.11-python-dateutil-2.9.0.post0/lib/python3.11/site-packages','/nix/store/2h4i0p0g6p4ql3nmpnkckgdqp9py4ymz-python3.11-tzdata-2024.1/lib/python3.11/site-packages','/nix/store/nfb94i8p6xv6sq3pwaxqdqyjiymamdg1-python3.11-css-inline-0.13.0/lib/python3.11/site-packages','/nix/store/0y1yf773xdb4l2g14f99m3y0sibl563g-python3.11-csscompressor-0.9.5/lib/python3.11/site-packages','/nix/store/jl21cc2n39nyhabpg15dnlr6dka9cjc7-python3.11-cssutils-2.10.2/lib/python3.11/site-packages','/nix/store/75in5rd5s1bilsw4rw7nlh4d561qnqq3-python3.11-defusedcsv-2.0.0/lib/python3.11/site-packages','/nix/store/i71cwkxisxm88y52n5j1wywjpcy7m247-python3.11-django-4.2.11/lib/python3.11/site-packages','/nix/store/r9hb3p85j8cwkyys3la2nji974vpl08y-python3.11-asgiref-3.7.2/lib/python3.11/site-packages','/nix/store/h6pyqc5m90y7lysa3myl3lqrqifkwmmy-python3.11-typing-extensions-4.10.0/lib/python3.11/site-packages','/nix/store/lj85f9ly8lqsigswar4i4644lkywy5ki-python3.11-sqlparse-0.4.4/lib/python3.11/site-packages','/nix/store/4npzif729g7z34s7zqamy4a184mw9qkq-python3.11-django-bootstrap4-3.0.0/lib/python3.11/site-packages','/nix/store/dhvislqhqmk44ij4pa2w36wmp4qqplx5-python3.11-django-compressor-4.4/lib/python3.11/site-packages','/nix/store/rw12rnqdaj57bf8w8qghvj1lknyxnbrf-python3.11-calmjs-3.4.4/lib/python3.11/site-packages','/nix/store/4sk6vm87ccjp8mfjx11zjkdnfc99lma0-python3.11-calmjs-parse-1.3.1/lib/python3.11/site-packages','/nix/store/h5vrdizl12f3cgs59a5fsqzhi1pbkacn-python3.11-ply-3.11/lib/python3.11/site-packages','/nix/store/r1q8cdbr0hhrfk286r74jbzhkdjnarf5-python3.11-calmjs-types-1.0.1/lib/python3.11/site-packages','/nix/store/haqr9x49fba5bwpasj555fyxbnx4h6fq-python3.11-django-appconf-1.0.5/lib/python3.11/site-packages','/nix/store/y6bfrc0p3yllqw6c28mnzr5cdmdbqvh0-python3.11-jinja2-3.1.3/lib/python3.11/site-packages','/nix/store/m0awn8yi9vf8k3925af2m72r8rfn4c0w-python3.11-markupsafe-2.1.5/lib/python3.11/site-packages','/nix/store/1llyk8z1w4mlj9afcb04sv36gq37w23d-python3.11-rcssmin-1.1.2/lib/python3.11/site-packages','/nix/store/v86rr60dr5pb9nplx1crzvl0wwdya3pv-python3.11-rjsmin-1.2.2/lib/python3.11/site-packages','/nix/store/69s0025hhglahnlixkgqvvxm71d7kkll-python3.11-django-context-decorator-1.6.1/lib/python3.11/site-packages','/nix/store/kk2phy1vjx346m5q2i086knzh2w9ifbz-python3.11-django-countries-7.5.1/lib/python3.11/site-packages','/nix/store/szfi90zabpcgk15f8glpfj2n51r6j2kf-python3.11-django-csp-3.8/lib/python3.11/site-packages','/nix/store/xlk56vrxqxcx8cbs4rn0g16wd7dx70hp-python3.11-django-filter-23.5/lib/python3.11/site-packages','/nix/store/glnp6prihw0s8zinv05qrfsips018g11-python3.11-django-formset-js-improved-0.5.0.3/lib/python3.11/site-packages','/nix/store/w5wg1pdjvwq028x0p5msb3f4snps9k04-python3.11-django-jquery-js-3.1.1/lib/python3.11/site-packages','/nix/store/glq9c1zwkmv5pd9za6vxw7fwrjjxskv5-python3.11-django-formtools-2.5.1/lib/python3.11/site-packages','/nix/store/7azb08rq11pysxxpam4sxazw9n0g5p3s-python3.11-django-hierarkey-1.1.0/lib/python3.11/site-packages','/nix/store/7mxbb5cd289spz5vzspi3mg19jianwk9-python3.11-django-i18nfield-1.9.4/lib/python3.11/site-packages','/nix/store/dik7kvr4klqlhqbnjb9ilj27pvcs0v9k-python3.11-django-libsass-0.9/lib/python3.11/site-packages','/nix/store/jmpywgnlkgjjlg6xrgig9qk1007msm8p-python3.11-libsass-0.23.0/lib/python3.11/site-packages','/nix/store/4zp391ph4aifx5g1s6cwg82p02im516z-python3.11-django-scopes-2.0.0/lib/python3.11/site-packages','/nix/store/2ljdhfd5i2rs8i8r0gg2calazw73jf94-python3.11-djangorestframework-3.14.0/lib/python3.11/site-packages','/nix/store/cssc8bgd3bgg50zcsakzzbxb1cfp6f7q-python3.11-pytz-2024.1/lib/python3.11/site-packages','/nix/store/xjh7wxjr2c5n7i3ka8c47xnaj2m25hnw-python3.11-markdown-3.5.2/lib/python3.11/site-packages','/nix/store/v3j6m43i5anja1vhr04ad7bnrwql66x3-python3.11-pillow-10.2.0/lib/python3.11/site-packages','/nix/store/f9w5ax1v3jjzzd9cnl1jbr4hxddzq7hv-python3.11-olefile-0.47/lib/python3.11/site-packages','/nix/store/wvnzwxz9vnlqz1rzvjgkb4w7n04h6x5w-python3.11-defusedxml-0.7.1/lib/python3.11/site-packages','/nix/store/v7vpsd7q8f7rzfid5dfj1b04hsl7h08n-python3.11-publicsuffixlist-0.10.0.20240328/lib/python3.11/site-packages','/nix/store/sgg4w36r4d7s74pgz15ickpk0lby482p-python3.11-qrcode-7.4.2/lib/python3.11/site-packages','/nix/store/qsr8yf44w7l6imr0snma5r7vnhgca4ci-python3.11-pypng-0.0.21/lib/python3.11/site-packages','/nix/store/qdm6mky7ffqfgbla0ck5r7bx4sf51jvb-python3.11-reportlab-4.1.0/lib/python3.11/site-packages','/nix/store/lwz9pmmfsj76vgwbcf6k0k2h1wp4ma4h-python3.11-requests-2.31.0/lib/python3.11/site-packages','/nix/store/z80yc5pjvp5zb9qk00wlfqi3i7bb0arf-python3.11-brotlicffi-1.1.0.0/lib/python3.11/site-packages','/nix/store/faax7x0w8v0l6x491fxr4n67ig9ay0ks-python3.11-cffi-1.16.0/lib/python3.11/site-packages','/nix/store/wh9jgyzk1fs8nifdchwzpa5mhdp3w0jj-python3.11-pycparser-2.21/lib/python3.11/site-packages','/nix/store/6n2xvcf6q91spf4yh8blkplbxlrrppas-python3.11-certifi-2023.11.17/lib/python3.11/site-packages','/nix/store/p399rwfcx5f484mi8mqpix5w99dywgya-python3.11-charset-normalizer-3.3.2/lib/python3.11/site-packages','/nix/store/2hkwndic1dilzx804j9s7g1gbv534aqs-python3.11-idna-3.6/lib/python3.11/site-packages','/nix/store/ap9lk8ikrypqnbwi738ygi31clqyvir6-python3.11-urllib3-2.2.1/lib/python3.11/site-packages','/nix/store/6kblk8h0pilj1adlp9biml5hzyb95s90-python3.11-rules-3.3.0/lib/python3.11/site-packages','/nix/store/c2fnr7frcw3g97wf0r8nhd5pm9c95frp-python3.11-urlman-2.0.1/lib/python3.11/site-packages','/nix/store/1467hjg9szswvz41ack52aza3hgfhqp4-python3.11-vobject-0.9.6.1/lib/python3.11/site-packages','/nix/store/gnfry4jaqh7hx4lmnr0qcbdzszl0kx0s-python3.11-whitenoise-6.6.0/lib/python3.11/site-packages','/nix/store/ac43p7wd61sxp3faidjfj7xjwwvmd5zs-python3.11-brotli-1.1.0/lib/python3.11/site-packages','/nix/store/nkg20lcsbz5jygv7ckl4jja327wyzzy3-python3.11-zxcvbn-4.4.28/lib/python3.11/site-packages','/nix/store/iac1b3wmr7z46r8491qymq1xapy09lym-python3.11-lxml-5.1.0/lib/python3.11/site-packages'], site._init_pathinfo());
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pretalx.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
```

**Comment by SuperSandro2000** [comment]
seems like #297628 is not working

**Comment by SuperSandro2000** [comment]
Untested revert in #302385

**Comment by mweinelt** [comment]
Ultimately not a blocker for this PR.

**Pull request merged**
