### PR TITLE
webcord{,-vencord}: move to pkgs/by-name, format with nixfmt, fixes for update scripts

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

webcord: move to pkgs/by-name, format with nixfmt, set electron version via update script
webcord-vencord: move to pkgs/by-name, format with nixfmt, disable nixpkgs-update, fix meta

The intent is to make version bumps as hands-off as possible.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by huantianad — COMMENTED** [review]
Oh I didn't know that we're using the new formatter in nixpkgs now, nor that we can include a package in `all-packages.nix` even if it's stored in by-name.

Main thing I wonder is if the bot that makes PRs off of update scripts will get messed up if the new electron version isn't in nixpkgs? I assume it'd just fail to build but still make the PR though.

**Comment by eclairevoyant** [comment]
r-ryantm checks to see if it builds in the first place. So if the new electron version isn't present, it just won't make the PR (which is fine, IMO, since it will catch it as soon as the new electron is added)

**Comment by Gerg-L** [comment]
webcord-vencord should be moved too

**Review by Gerg-L — APPROVED** [review]
Assuming the update script works properly looks good

**Comment by eclairevoyant** [comment]
> Assuming the update script works properly

Seems to.

<details>
<summary>Update log</summary>

```
$ nix-shell maintainers/scripts/update.nix --argstr package webcord

Going to be running update for following packages:
 - webcord-4.8.0

Press Enter key to continue...

Running update for:
 - webcord-4.8.0: UPDATING ...
 - webcord-4.8.0: DONE.

Packages updated!

$ git diff
diff --git a/pkgs/by-name/we/webcord/package.nix b/pkgs/by-name/we/webcord/package.nix
index d38fd3570215..f3fb33f5dcc4 100644
--- a/pkgs/by-name/we/webcord/package.nix
+++ b/pkgs/by-name/we/webcord/package.nix
@@ -11,16 +11,16 @@

 buildNpmPackage rec {
   pname = "webcord";
-  version = "4.8.0";
+  version = "4.9.1";

   src = fetchFromGitHub {
     owner = "SpacingBat3";
     repo = "WebCord";
     rev = "refs/tags/v${version}";
-    hash = "sha256-x9Ejb8yxgQhlEfUUfoqbgSffNNtOoFeAyb3OISR+Jz4=";
+    hash = "sha256-sYTMfqZokwJ3CFtArkUckCpQlnyJ1BVpewU92sNaKC8=";
   };

-  npmDepsHash = "sha256-7H4I4vKygMgsPh+OvZZGhpkoQQu1a51yUTwEPJSBM18=";
+  npmDepsHash = "sha256-LxOqpUVl2hXZrfTQfMz1+fVGRuNwG6dX03fGQVYmqq0=";

   nativeBuildInputs = [
     copyDesktopItems
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 4b9377590668..21785b51cc8c 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -35573,7 +35573,7 @@ with pkgs;

   webcamoid = libsForQt5.callPackage ../applications/video/webcamoid { };

-  webcord = callPackage ../by-name/we/webcord/package.nix { electron = electron_29; };
+  webcord = callPackage ../by-name/we/webcord/package.nix { electron = electron_30; };

   webex = callPackage ../applications/networking/instant-messengers/webex { };
```
</details>

**Review by NotAShelf — APPROVED** [review]
looks good

**Review by huantianad — APPROVED** [review]

**Pull request merged**
