### PR TITLE
magic-wormhole-rs: Add alias `wormhole-rs`

### PR DESCRIPTION
**Pull request by piegamesde**
###### Description of changes

Follow-up on [#174626](https://github.com/NixOS/nixpkgs/pull/174626#issuecomment-1140334400)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
aliases.nix is a deprecation list. The added alias should be converted to a throw in the next release and in the one after that be removed. To make things better discoverable please use description/longDescription.

**Comment by piegamesde** [comment]
At the top of the file there is a comment:

```nix
# Add 'preserve, reason: reason why' after the date if the alias should not be removed.
# Try to keep them to a minimum.
# valid examples of what to preserve:
#   distro aliases such as:
#     debian-package-name -> nixos-package-name
```

Am I misunderstanding something? It even lists pretty much my exact use case as example

**Comment by mweinelt** [comment]
We do have persistent aliases and it's fine to create one, when, like in this case, the package and the binary name differ and wormhole-rs is more the more likely name for someone to look for.

**Review by mweinelt — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Does the script ignore aliases which have longer commits?

**Comment by mweinelt** [comment]
```
remove-old-aliases.py
68:            or "preserve, reason:" in line.lower()
```

**Pull request merged**
