### PR TITLE
Rework stage.nix's extraPkgs

### PR DESCRIPTION
**Pull request by matthewbauer**
I have renamed the overlay to “otherPackageSets” because I think that
is more descriptive.

pkgsLocal has been removed because there were concerns that it would
be confusing. None of the other names seemed very useful so I think it
is best to avoid it altogether. pkgsCross is still included,
hopefully, that will not have as much confusion.

pkgsMusl is now available for building Musl packages. It will give you
packages bulit with the Musl libc.

Also added more documentation.

/cc @dezgeg @Ericson2314 @dtzWill

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]
I like just let-binding `force*` to deprecate then by before, but that's just a quible. Looks good!

**Comment by dtzWill** [comment]
\o/ \o/ \o/

**Comment by grahamc** [comment]
Any chance you could:

1. add back the forceSystem function
2. add a builtins.trace log which says it is deprecated, and how to upgrade
3. a changelog entry with the same contents?

This broke a bunch of my stuff, and the only way to figure out how and why was to `git log -S forceSystem`.

**Comment by matthewbauer** [comment]
Yeah that would be a good idea.

**Comment by grahamc** [comment]
Thank you a lot!

**Comment by matthewbauer** [comment]
I think there is a pretty critical issue in forceSystem where the .drv is different for each host system. We can probably try to fix it but it could get a little complicated with trying to avoid that bug. Are you just using forceSystem for i686? Maybe we can just point it to pkgsi686Linux.

**Pull request merged**
