### PR TITLE
Integrate wine-staging into 32/64/wow build arch

### PR DESCRIPTION
**Pull request by bendlas**
also update wine and winetricks

### CODE REVIEW

**Comment by bendlas** [comment]
this fixes https://github.com/NixOS/nixpkgs/issues/7798
cc @abbradar

**Comment by abbradar** [comment]
Very nice, thanks! Squash with the first commit and let's merge this -- I'll just need to make a test build.

**Comment by bendlas** [comment]
squashed and force-pushed

**Comment by abbradar** [comment]
Just finished building ^_^. Thanks for your work!

**Pull request merged**
