### PR TITLE
noisetorch: 0.5.2-beta -> 0.8.2

### PR DESCRIPTION
**Pull request by reedrw**
###### Motivation for this change
noisetorch has added a more complete command line implementation, which is useful for running the software as a systemd service among other things.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by PanAeon — APPROVED** [review]

**Comment by PanAeon** [comment]
@reedrw do you thing it is worth while to add this as a systemd service in nixos?

**Comment by reedrw** [comment]
I think it would be pretty cool if I could have something like
```nix
{
  services.noisetorch = {
    enable = true;
    device = "alsa_output.<whatever>";
  };
}
```
In my configuration.nix. But I don't really know a lot about writing NixOS modules to do it myself (nor am I really that worried about it not being there).

**Comment by PanAeon** [comment]
yeah, maybe I'll add a ticket for this, after all it's a little bit of convenience. Adding a user service is not a problem, but I think I'll have to create a Virtualbox VM in order to test it...

**Comment by reedrw** [comment]
I forgot about this until my NUR bot update of it failed. The config.go patch is no longer necessary as the updater is no longer compiled by default.

**Comment by reedrw** [comment]
And naturally a new release comes out minutes after I update this PR

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 97530` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>noisetorch</li>
  </ul>
</details>

**Pull request merged**
