### PR TITLE
portmidi: 217 -> 234

### PR DESCRIPTION
**Pull request by emilytrau**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 133485` at e9597a06 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>impressive</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/897644f97a3533abf1f0f6e47905ce50">purePackages.midi</a></li>
    <li><a href="https://gist.github.com/10e8ede7175a474a1a6aa7b705f436c6">python38Packages.rl-coach</a></li>
    <li><a href="https://gist.github.com/14bf1ffe02b5384a2b94527aed72689b">python39Packages.rl-coach</a></li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>musescore</li>
  </ul>
</details>
<details>
  <summary>21 packages built successfully:</summary>
  <ul>
    <li>_20kly</li>
    <li>cantoolz</li>
    <li>denemo</li>
    <li>endgame-singularity</li>
    <li>frescobaldi</li>
    <li>gnome.aisleriot</li>
    <li>lenmus</li>
    <li>mixxx</li>
    <li>orca-c</li>
    <li>portmidi</li>
    <li>pysolfc</li>
    <li>python38Packages.mido</li>
    <li>python38Packages.pygame</li>
    <li>python38Packages.pygame-gui</li>
    <li>python38Packages.pytmx</li>
    <li>python39Packages.mido</li>
    <li>python39Packages.pygame</li>
    <li>python39Packages.pygame-gui</li>
    <li>python39Packages.pytmx</li>
    <li>video2midi</li>
    <li>xjadeo</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/8f0737fwyva2a9p9nfg7zzg6nxl3gsfl-portmidi-234.drv' failed with exit code 1; last 10 log lines:
  patching file CMakeLists.txt
  patching file pm_common/CMakeLists.txt
  patching file pm_dylib/CMakeLists.txt
  patching file pm_java/CMakeLists.txt
  applying patch /nix/store/vw57rc6il3gnszrmb9j2gapkl5f3jg8c-remove-darwin-variables.diff
  patching file CMakeLists.txt
  patching file pm_common/CMakeLists.txt
  Hunk #1 FAILED at 22.
  1 out of 2 hunks FAILED -- saving rejects to file pm_common/CMakeLists.txt.rej
  patching file pm_dylib/CMakeLists.txt
```

**Comment by risicle** [comment]
On NixOS x86_64:

```
builder for '/nix/store/zs65kddxy08l67nkdkcy01h30xvfysnw-cantoolz-3.7.0.drv' failed with exit code 1; last 10 log lines:
      File "/build/source/cantoolz/modules/io/hw_TCP2CAN.py", line 80, in handle
        self.selfx.set_error_text('TCPClient: recv response error:' + str(e))
    AttributeError: 'CustomTCPClient' object has no attribute 'selfx'

      warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

  -- Docs: https://docs.pytest.org/en/stable/warnings.html
  =========================== short test summary info ============================
  FAILED tests/modules/test_hw_tcp2can.py::TestTCP2CAN::test_server - Assertion...
  ====== 1 failed, 26 passed, 1 deselected, 3 warnings in 159.70s (0:02:39) ======
```

...wonder if this is a flaky test.

**Comment by risicle** [comment]
(Fixed on macos now except pre-existing failure `orca-c`)

**Comment by angustrau** [comment]
`cantoolz` builds ok for me on NixOS x86_64, but I seem to be getting a different derivation.

```
❯ nix-build . -A cantoolz
/nix/store/ncqza9wyxklbp8y8b00z4jkn5yli72vb-cantoolz-3.7.0
```

**Comment by risicle** [comment]
WFM now - I think there may have been a temporary breakage in `master` that `nixpkgs-review` was merging with.

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64

**Pull request merged**
