### PR TITLE
openscad-unstable: init at 2024-01-22

### PR DESCRIPTION
**Pull request by pca006132**
## Description of changes

Add openscad-unstable package, which provides new experimental features on top of the old openscad package.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

This is only tested on NixOS with wayland. Would be nice if someone can help me test on other environments, e.g. darwin.

Notify maintainers: @bjornfor @7c6f434c @gebner. Btw should I add maintainers for the stable openscad package to this openscad-unstable? The build system is completely changed.

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pca006132** [comment]
In principle there is no unfree dependencies, but `cuda_cccl` license is set to CUDA EULA instead of Apache 2.0. Should I build thrust/cccl from source and remove the `cuda_cccl` dependency?

**Comment by 7c6f434c** [comment]
The expression looks OK.

If you want, you could add me as a maintainer, to have ofborg nag me about merging the updates… can't speak for the others (but presumably sooner or later this build system will happen to be in the stable version)

I think binaries from CUDA distribution might indeed be under CUDA EULA even if the source is better licensed? It would be unfortunate have only OpenSCAD version that touches unfree binary distributions or is limited in the GPUs it agrees to use. I guess it is not pressing until this is the stable version, but well, eventually…

**Comment by pca006132** [comment]
Sure, will add you to the maintainer list.

It is not using the GPU for computation, the cccl/thrust dependency is just a parallel implementation of c++ algorithms (slightly more than the c++17 parallel algorithms). In fact, I can do a fetchFromGitHub to fetch the source repo of thrust, licensed under Apache 2.0, and avoid the cuda cccl dependency. Just not sure if this is desirable.

**Comment by 7c6f434c** [comment]
In general if building from source is not too hard, it is considered preferred in Nixpkgs. And under the current policy the main Hydra doesn't touch the CUDA binary downloads, which would be another point in favour of a source build.

So yes, I will be grateful if you try!

**Comment by pca006132** [comment]
@7c6f434c done!

**Comment by 7c6f434c** [comment]
Minor nitpick: we drop leading `v` in versions. 

Maybe a free build of cccl would be worth having as a standalone library?

Morbid curiousity: any idea how much RAM gcc build tried to take (if you noticed)?

**Comment by pca006132** [comment]
> Minor nitpick: we drop leading `v` in versions.

Sure, will fix.

> Maybe a free build of cccl would be worth having as a standalone library?

I can try.

> Morbid curiousity: any idea how much RAM gcc build tried to take (if you noticed)?

My machine has 20 threads, it uses more than 30GB of RAM and was start using swap. With clang, it uses less than 20GB of RAM.

**Comment by pca006132** [comment]
@7c6f434c The problem with cccl is that it depends on nvcc, so unless you strip away many of the features as we do with openscad (manifold uses thrust tbb/cpp backend only), we cannot build it without depending on the (unfree) cuda toolkit. I think I will just leave cccl here and wait for #224292.

**Pull request merged**
