### PR TITLE
nixos/lib: Use SingleLineStr in systemd unit description option 

### PR DESCRIPTION
**Pull request by D4ndellion**
###### Motivation for this change
Would stop things like #157019 needing to happen.

There's probably more places we can swap out str with `singleLineStr` considering it is so new.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — APPROVED** [review]
Makes sense to me.

**Comment by roberth** [comment]
I'd prefer a solution where newlines are escaped properly throughout. I guess it doesn't matter much for `description`, but for other options it may. See `man systemd.syntax` for `"\n"`. `\` as line continuation markers also exists but is cosmetic.

**Review by bachp — APPROVED** [review]

**Comment by jonringer** [comment]
hold on... let me run a bunch of nixosTests

**Comment by jonringer** [comment]
more specifically, going to instantiate: https://github.com/jonringer/nix-test-staging-next/blob/main/test-staging.nix

**Review by jonringer — APPROVED** [review]
Was able to instantiate some 90 nixosTests

LGTM

**Pull request merged**
