### PR TITLE
tiny-cuda-nn: quote strings; use strictDeps; format with alejandra

### LINKED ISSUE #238617: tiny-cuda-nn: Build fails due to unquoted environment variable export
Originally spotted by @nviets (thank you!).

### Steps To Reproduce

Steps to reproduce the behavior (assuming `allowUnfree` and `cudaSupport` are both `true`):

`nix build .#tiny-cuda-nn`

### Build log

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/v6q53k8zlkm2ccd8dlms65fwm65xzp0k-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
/nix/store/j0xzghjmynydvw37zihdbw598j0iwly9-stdenv-linux/setup: line 127: 61: command not found
/nix/store/j0xzghjmynydvw37zihdbw598j0iwly9-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
```

### Additional context

The `TCNN_CUDA_ARCHITECTURES` environment variable contains semicolons and must be quoted, otherwise bash will interpret the semicolons as command separators.

https://github.com/NixOS/nixpkgs/blob/6764cc2a0909396c435ee4c915c72c7db1be6bae/pkgs/development/libraries/science/math/tiny-cuda-nn/default.nix#L83-L85

### PR DESCRIPTION
**Pull request by ConnorBaker**
###### Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/238617.

- Quoted strings inside of shell script portions of the derivation to avoid breakages
- Switched to `strictDeps = true`, which caught an issue where `cuda_cudart` is both a build-time and runtime dependency
- Formatted the file with Alejandra (which I forgot to do when I committed, apparently)

Test with this flake:

<details>

```nix
{
  inputs = {
    nixGL = {
      inputs.nixpkgs.follows = "nixpkgs";
      url = "github:guibou/nixGL";
    };
    nixpkgs.url = "github:NixOS/nixpkgs/refs/pull/238619/head";
  };

  nixConfig = {
    # Add my own cache and the CUDA maintainer's cache
    extra-substituters = [
      "https://cantcache.me"
      "https://cuda-maintainers.cachix.org"
    ];
    extra-trusted-substituters = [
      "https://cantcache.me"
      "https://cuda-maintainers.cachix.org"
    ];
    extra-trusted-public-keys = [
      "cantcache.me:Y+FHAKfx7S0pBkBMKpNMQtGKpILAfhmqUSnr5oNwNMs="
      "cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E="
    ];
  };

  outputs = inputs: let
    system = "x86_64-linux";

    pkgs = import inputs.nixpkgs {
      inherit system;
      config = {
        allowUnfree = true;
        cudaSupport = true;
        cudaForwardCompat = true;
      };
    };

    nixGL = import inputs.nixGL {
      inherit pkgs;
      enableIntelX86Extensions = true;
      enable32bits = false;
      nvidiaVersion = "535.54.03";
      nvidiaHash = "sha256-RUdk9X6hueGRZqNw94vhDnHwYmQ4+xl/cm3DyvBbQII=";
    };

    test-tiny-cuda-nn = with pkgs;
      writeShellApplication {
        name = "test-tiny-cuda-nn";
        runtimeInputs = [
          nixGL.nixGLNvidia
          (python3.withPackages (ps:
            with ps; [
              tiny-cuda-nn
              torch
              tqdm
            ]))
        ];
        text =
          # If the script was run with --nixgl, then we need to wrap the
          # python interpreter with nixGL.
          ''
            PYTHON_CMDS=("python3")
            if [[ "$*" =~ "--nixgl" ]]; then
              echo "Running with nixGL..."
              PYTHON_CMDS=("${nixGL.nixGLNvidia.name}" "''${PYTHON_CMDS[@]}")
            fi
          ''
          # Set the SCRIPTS_DIR variable to the path of the scripts directory
          + ''
            SCRIPTS_DIR="${python3Packages.tiny-cuda-nn.src}/scripts"
          ''
          # Test torch bindings
          + ''
            echo "Testing the torch bindings..."
            # Yes, there is a typo in the filename.
            /usr/bin/env time -v \
              "''${PYTHON_CMDS[@]}" "$SCRIPTS_DIR/test_toch_bindings.py"
            echo "Done."
          ''
          # Test training
          + ''
            echo "Training a toy SDF model with eikonal term..."
            /usr/bin/env time -v \
              "''${PYTHON_CMDS[@]}" "$SCRIPTS_DIR/test_grid_bwdbwd.py"
            echo "Done."
          ''
          # Stress test
          + ''
            echo "Stress-testing the GPU memory arena of tiny-cuda-nn with randomly sized allocations..."
            /usr/bin/env time -v \
              "''${PYTHON_CMDS[@]}" "$SCRIPTS_DIR/test_random_input.py"
            echo "Done."
          '';
      };
  in {
    legacyPackages.${system} = pkgs;
    apps.${system} = {
      test-tiny-cuda-nn = {
        program = pkgs.lib.getExe test-tiny-cuda-nn;
        type = "app";
      };
    };
    formatter.${system} = pkgs.alejandra;
  };
}
```

</details>

To run on NixOS:

```bash
nix run .#test-tiny-cuda-nn -L
```

To run on non-NixOS:

```bash
nix run .#test-tiny-cuda-nn -L -- --nixgl
```

Note: I *strongly* recommend setting `cudaCapabilities` in the flake to whatever you intend to run the tests on. For such a tiny package, it take quite a while to compile!

Run `Nixpkgs-review`:

```bash
nixpkgs-review pr 238619 \
  --extra-nixpkgs-config '{ allowUnfree = true; cudaSupport = true; }' \
  --no-shell \
  --print-result
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ConnorBaker** [comment]
Result of `nixpkgs-review pr 238619 --extra-nixpkgs-config '{ allowUnfree = true; cudaSupport = true; }'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.tiny-cuda-nn</li>
    <li>tiny-cuda-nn</li>
  </ul>
</details>

**Review by samuela — COMMENTED** [review]
there's a large diff here for what are ultimately formatting changes... just want to confirm that's intentional?

**Comment by ConnorBaker** [comment]
> there's a large diff here for what are ultimately formatting changes... just want to confirm that's intentional?

That's correct -- I've really got to look into `pre-commit` or something to ensure consistent formatting before I push.

**Review by samuela — APPROVED** [review]

**Comment by samuela** [comment]
Thanks @ConnorBaker !

**Comment by SomeoneSerge** [comment]
Makes me think that I maybe want alejandra the other way around: an ultimate compromising formatter that preserves whatever style was already chosen in the document, nixpkgs-fmt or alejandra, but makes it consistent

**Pull request merged**
