### PR TITLE
xgboost: 1.5.2 -> 1.7.2

### PR DESCRIPTION
**Pull request by bcdarwin**
###### Description of changes

Update xgboost and unbreak xgboost Python packages; supersedes #184147.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Would be good if it's possible patch the python tests and maybe disable those which are failing.
If it's impossible to get them working then it's fine for me to disable it.

**Comment by nviets** [comment]
1.6.2 has already been released. Could we update before merging?

**Comment by bcdarwin** [comment]
> 1.6.2 has already been released. Could we update before merging?

@nviets - bumped to 1.6.2.

**Comment by trivialfis** [comment]
Hi @bcdarwin , thank you for working on this. Indeed, the requirement of downloading data is problematic for nix environment. But can we at least run the `test_basic.py`, which should finish in no time. In the meanwhile, I will try to make XGBoost rely less on fetched data for tests, or at least isolate them whenever appropriate.

**Comment by nviets** [comment]
@bcdarwin - could you update to 1.7.2?

**Comment by bcdarwin** [comment]
> @bcdarwin - could you update to 1.7.2?

@nviets - done.

**Review by nviets — APPROVED** [review]

**Comment by nviets** [comment]
@Mindavi - could you please merge?

**Pull request merged**
