### PR TITLE
[20.09] Tailscale updates

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

Magic DNS.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by danderson — APPROVED** [review]
Works for me, if backporting this much is acceptable. 1.4.4 is a good upgrade from 1.0, doesn't break anything that used to work, strictly adds more shinies.

**Comment by grahamc** [comment]
I just tagged the RMs for 20.09 to see what they think :).

**Comment by jonringer** [comment]
I've only glanced over the changelogs, but doesn't seem to mention any breaking changes. So I'm okay with updating it

**Comment by danderson** [comment]
Tailscale employee here. Can confirm, no breaking changes from 1.0 to 1.4, only new features.

**Pull request merged**
