### PR TITLE
home-assistant: v0.103.1 -> 0.104.3

### PR DESCRIPTION
**Pull request by colemickens**
###### Motivation for this change

Upgrade `home-assistant` from 0.103.1 -> 0.104.3.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
This is ready for review. Please also take a look at : https://github.com/NixOS/nixpkgs/pull/78009

**Comment by colemickens** [comment]
cc: @Mic92

**Comment by Mic92** [comment]
Works fine in general. It only breaks icloud support, which I added in https://github.com/NixOS/nixpkgs/pull/78109

**Comment by colemickens** [comment]
Now with 0.0.1 more umph - updated to latest release - `0.104.3`.

**Comment by colemickens** [comment]
@Mic92 Additionally, this no longer breaks your recently added iCloud support - I've updated, rebased, and regenerated.

**Comment by Mic92** [comment]
@colemickens Ok. I cannot confirm that for me. I no longer see home-assistant icloud logins in the log after this update. I have not digged deeper into it. The rest seems to work. Maybe we could merge it anyway.

**Pull request merged**
