### PR TITLE
protobuf: 3.5.1.1 -> 3.6.1, grpc: 1.10.1 -> 1.15.0

### PR DESCRIPTION
**Pull request by tarigo**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tarigo** [comment]
> This change affects many packages. How did you test it?

Please elaborate your concern. This library is backward compatible across versions. So, how did I test what? Backward compatibility?

**Comment by xeji** [comment]
See the checklist above. Since you did not check anything it is not clear to me what you did. 
In particular, did you build the package and other packages that depend on it?  On which platforms?

**Comment by tarigo** [comment]
I'm sorry that this change is not clear for you, @xeji.  Maybe, it would be better to include somebody, how is more aware about this topic... Let's say  @orivej or @volth.

**Comment by tarigo** [comment]
Just a side note:  
running `nox-review` for this PR with resources I have (harware&time) is not possible because:
1). It takes ages and ages to recompile all dependencies on my laptop.

**Comment by tarigo** [comment]
Just a side note:  
running `nox-review` for this PR with resources I have (harware&time) is not possible because:
1). It takes ages and ages to recompile all dependencies on my laptop.

**Comment by tarigo** [comment]
Just a side note:  
running `nox-review` for this PR with resources I have (harware&time) is not possible because:
1). It takes ages and ages to recompile all dependencies on my laptop.
2). Some of dependencies are broken for other reasons (not this particular change). For example chromium build failed trying to apply patch.
3). `nox-review -k`  does not work due to bug in review script.

Probably we can come up with some reasonable amount of dependencies to build and test or some test for `nixpkgs/pkgs/test`, sufficient enough, to verify further updates of protobuf library.  I would be glad to help.

**Comment by orivej** [comment]
I'd like to add protobuf 3.6.1 first (in #47307), and then switch the default protobuf from 3.4 to 3.6 (as done in this PR) and the default python protobuf from 3.5 to 3.6 (as done in #45709).

> Probably we can come up with some reasonable amount of dependencies to build and test

It seems reasonable to rebuild only those packages that run `protoc` or use `protoc`-generated files from their dependencies, but they are not known in advance.

You don't have to rebuild everything to propose a PR, only to indicate the amount of testing that has been done.

> This library is backward compatible across versions.

Protobuf introduces breaking changes in every minor release: we do have to check every package that depends on it. For example, while testing this update I noticed that `pokerth` fails to build and needs to be restricted to `protobuf3_4`, and `protobufc` fails to build and needs to be updated to 1.3.1. A lot more might have to be done to switch the default to 3.6.

**Comment by tarigo** [comment]
Ok, understood. Actually, my main motivation was to get the fresh version gRPC. I made PR #47348 for that.

**Pull request closed without merging**
