### PR TITLE
ffmpeg: add ilbc options

### PR DESCRIPTION
**Pull request by jopejoe1**
## Description of changes

Support for en-/de-coding support for ilbc.

Can be tested with:

```bash
ffmpeg -i input.opus -c:a libilbc -ar 8000 -ac 1  out.lbc
ffmpeg -i out.lbc out.opus
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Do you have a use case for this that makes it worth packaging the library for? It seems like one of the many codecs that is basically obsoleted by more modern speech codecs and I’d assume that there aren’t many files in this format lying around (but maybe an application might want to process it with FFmpeg as a library?).

**Comment by Atemu** [comment]
I think one of the main use-cases for obsolete codec support is being able to decode it (and e.g. encoding them in modern formats).

I once needed to decode some old obsolete format used in some old game before and remember it being a PITA; needing to compile an extraction and decoding tool long before I was comfortable doing that.

I don't know this format but anyone who has files in this format now or in the future will want this patch to have landed.

This one doesn't look very complex or large, so I welcome its addition.

**Comment by emilazy** [comment]
Right; old files is a great use case. In this case though the codec was very much intended for real‐time streaming use, so I’m not sure how many files there will actually be lying around outside of test suites. Not trying to block this though.

**Comment by jopejoe1** [comment]
The codec is also still included in Chrom{e,ium} and Safari's WebRTC stack.

Im also of the opinion that we should make our full version as complete as we can.

**Comment by Atemu** [comment]
So this is interesting, for some reason the pre-patch ffmpeg is able to decode the file I produced?

**Review by Atemu — APPROVED** [review]
I think it's best to just have this.

**Pull request merged**
