### PR TITLE
llama-cpp: add support for Vulkan backend

### PR DESCRIPTION
**Pull request by mschwaig**
## Description of changes

This adds support for the newly added Vulkan backend for llama-cpp, implemented in the same way as https://github.com/ggerganov/llama.cpp/pull/5173.

The one thing that is tricky about this is the `vulkanSupport` flag that I added to the function  arguments alongside the existing arguments `cudaSupport`, `rocmSupoort`, `openclSupport`, `blasSupport` and `metalSupport`, which raises two questions for me.

#### Does using `vulkanSupport` directly work for all users?

I am not sure if we would expect people to set `cudaSupport` or `rocmSupport` at the same time as `vulkanSupport` and if the result would/should be sane if it's passed to `llama-cpp` like that or if the package should do some prioritization and compile with the faster vendor-specific API only when it is set alongside of Vulkan. The upstream flake has separate outputs for each backend.

#### Will using `vulkanSupport` directly still make sense if even more backends are added?

A number of other backends have been added to the upstream at the same time with the one from this PR (see https://github.com/ggerganov/llama.cpp/discussions/5138).
There is a second Vulkan backend that goes through Kompute and the authors of those two Vulkan backends want to merge them eventually. There is also a SYCL backend for Intel GPUs.
If we would add support for those backends as well I am not sure how users should access those in a way that is idiomatic for nixpkgs:
 * Kompute also targets Vulkan,
 * one of the Vulkan backends will go away again if the two are actually merged, and
 * would there be a `useSYCL`flag?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by philiptaron** [comment]
I'd wait to land this until https://github.com/ggerganov/llama.cpp/pull/5311 lands, so that there aren't the awkward darwin checks.

More broadly speaking, Vulkan support is aiming to be the new "default" llama.cpp backend, superseding the opencl backend. (At least, that's what I understand from @0cc4m's PRs and comments.) If that comes to be, I expect the OpenCL backend to diminish and get relegated to a non-default state, and the Vulkan backend be promoted to default.

That moment hasn't arrived, but I'm looking forward to when it does. `llama.cpp`'s defaults should give users the fastest local AI possible, and the results from Vulkan are better than those from OpenCL.

**Comment by mschwaig** [comment]
> I'd wait to land this until [ggerganov/llama.cpp#5311](https://github.com/ggerganov/llama.cpp/pull/5311) lands, so that there aren't the awkward darwin checks.

I don´t mind either way.

The one thing that's not properly marked as broken right now are Darwin builds on ARM with `.override =  { useVulkan = true; } `.

Darwin on Intel is marked as broken in any case, but someone could also check if that actually starts working after Mac support is merged upstream and we make `vulkanSupport=true` the default in that case already.

I will not do either of those things myself since I don´t have any Macs at home.

**Comment by happysalada** [comment]
Im integrating upstream flake changes in https://github.com/NixOS/nixpkgs/pull/289513
Would you mind if we went for my PR ?

**Comment by mschwaig** [comment]
> Im integrating upstream flake changes in #289513 Would you mind if we went for my PR ?

In general I don't mind, but I have some concerns about the current state of your PR which I will mention in a comment there.

**Review by philiptaron — CHANGES_REQUESTED** [review]
I agree that pursuing https://github.com/NixOS/nixpkgs/pull/289513 is the better path.

**Comment by mschwaig** [comment]
Ok, I will close this then.

**Pull request closed without merging**
