### PR TITLE
zeromq: enable curve support

### LINKED ISSUE #337508: `zeromq` package is missing optional features provided by other distributions
### Describe the bug

The `zeromq` package providing `libzmq` is missing several features that other distributions enable by default.

Some examples:
- Upstream Debian Packaging: https://github.com/zeromq/libzmq/blob/1f4dd54f94009cb57bb68bfc856edc1c0bd3df06/packaging/debian/rules#L46
- Arch Linux Packaging: https://gitlab.archlinux.org/archlinux/packaging/packages/zeromq/-/blob/main/PKGBUILD?ref_type=heads#L53-67
- Fedora Packaging: https://src.fedoraproject.org/rpms/zeromq/blob/rawhide/f/zeromq.spec#_70

Features like `ENABLE_CURVE` and `WITH_LIBSODIUM` should probably be enabled by default. I was expecting curve support from the package and even saw `libsodium` in the package's inputs, yet I ran into an `ENOTSUP` on `zmq_curve_keypair`.
- See the unused `libsodium` input: https://github.com/NixOS/nixpkgs/blob/31fb372aa93926f3e05401c7474cc560e197c765/pkgs/development/libraries/zeromq/4.x.nix#L7
- See the ENOTSUP error here: https://libzmq.readthedocs.io/en/latest/zmq_curve_keypair.html

### Expected behavior

An we should probably provide build options similar to the upstream RHEL packaging. See https://github.com/zeromq/libzmq/blob/1f4dd54f94009cb57bb68bfc856edc1c0bd3df06/packaging/redhat/zeromq.spec#L184-L193

Most should probably be enabled by default.

### Notify maintainers

@fpletz 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by smancill**
## Description of changes

- Modernize the derivation.
- Create and install man pages (not done when using CMake)
- Enable Curve support

Closes #337508

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by fpletz — COMMENTED** [review]
Looks good, we should target staging though.

**Comment by smancill** [comment]
> Looks good, we should target staging though.

Done. I wasn't sure how many packages would be dependents.

**Comment by risicle** [comment]
The combination of this having the tests disabled and no `passthru.tests` makes this hard to review.

**Comment by risicle** [comment]
Built `pyzmq`, `zmqpp`, `cppzmq`, `azmq`, `czmq`, `ffmpeg.override { withZmq = true; }` on macos 12 x86_64 successfully.

(the world's trying to tell you something when you've got that many wrapper libraries)

**Comment by smancill** [comment]
> The combination of this having the tests disabled and no `passthru.tests` makes this hard to review.

Could you point what should be done with `passthru.tests`. That's the part I am not yet much aware of nixpkgs. Then I can added it now in this PR.

**Comment by risicle** [comment]
e.g.

```
  passthru.tests = {
    inherit
      azmq
      cppzmq
      czmq
      zmqpp
    ;
    ffmpeg = ffmpeg.override { withZmq = true; };
    pyzmq = python3.pkgs.pyzmq;
  };
```

And when adding the necessary arguments to the top of the file I tend to comment them `# for passthru.tests` to make it clear there isn't some weird recursive dependency stuff going on.

**Review by risicle — APPROVED** [review]

**Comment by alyssais** [comment]
This added pyzmq to passthru.tests, but was then merged with that test failing??

**Comment by alyssais** [comment]
https://github.com/NixOS/nixpkgs/pull/341813

**Comment by risicle** [comment]
Ofborg can generally not be trusted on staging anyway - I think I tested this cherry-picked to staging-next (failed to mention though) and it worked.

**Comment by alyssais** [comment]
WDYM?  Sometimes OfBorg times out or fails to build a dependency, but that's not what happened here — it failed to build the exact package being tested, for reasons that are clearly an OOM or similar transient failure.

**Comment by risicle** [comment]
Right, but even so, transient unrelated breakage is an expected thing on staging, and that doesn't make it any less valid to add `pyzmq` as a passthru test. And I had high confidence any breakage _was_ unrelated as I had tested a cherry-picked version of this branch. I don't see any issue in what's happened here.

**Comment by alyssais** [comment]
> And I had high confidence any breakage _was_ unrelated as I had tested a cherry-picked version of this branch.

Right, that's fair enough if so.  I wonder if the problem just didn't happen on macOS.

**Pull request merged**
