### PR TITLE
nixos/auto-cpufreq: Add configuration support.

### PR DESCRIPTION
**Pull request by nicoonoclaste**
###### Description of changes

Added `services.auto-cpufreq.settings` option.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
- [ ] Tested, as applicable:
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Module updates) Added a release notes entry if the change is significant
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nbraud** [comment]
Presumably, this doesn't need a release note entry, since there is no functional difference for existing users:
an empty `/etc/auto-cpufreq.conf` is created, when `services.auto-cpufreq.settings` is unset/default, but that doesn't change the behavior of `auto-cpufreq`.

**Comment by nbraud** [comment]
@Technical27, is this OK by you?

**Comment by nbraud** [comment]
PS: I tried first to make the modules' options model the `auto-cpufreq.conf` ones, but I couldn't get `formats.ini` to work with that.

**Comment by mkg20001** [comment]
> an empty /etc/auto-cpufreq.conf is created, when services.auto-cpufreq.settings is unset/default, but that doesn't change the behavior of auto-cpufreq.

you can add mkIf (cfg.settings != {})

You're using /etc, meaning you can specify the --config option in ExecStart.

The unit file from the derivation is used, but you should be able to override it and use that instead of restartTrigger (since a changed execstart would restart automatically). 

(The empty execstart tells systemd to toss the existing values since it's multi-value)

```patch
diff --git a/nixos/modules/services/hardware/auto-cpufreq.nix b/nixos/modules/services/hardware/auto-cpufreq.nix
index 5a8b7c8e43c5..a32404fbcdcc 100644
--- a/nixos/modules/services/hardware/auto-cpufreq.nix
+++ b/nixos/modules/services/hardware/auto-cpufreq.nix
@@ -27,15 +27,19 @@ in {
 
   config = mkIf cfg.enable {
     environment.systemPackages = [ pkgs.auto-cpufreq ];
-    environment.etc.${cfgFilename}.source = cfgFile;
 
     systemd = {
       packages = [ pkgs.auto-cpufreq ];
       services.auto-cpufreq = {
         # Workaround for https://github.com/NixOS/nixpkgs/issues/81138
         wantedBy = [ "multi-user.target" ];
-        restartTriggers = [ cfgFile ];
         path = with pkgs; [ bash coreutils ];
+        serviceConfig = {
+          ExecStart = [
+            ""
+            "${pkgs.auto-cpufreq}/bin/auto-cpufreq --config ${cfgFile}"
+          ];
+        };
       };
     };
   };
```

**Comment by nbraud** [comment]
> > an empty /etc/auto-cpufreq.conf is created, when services.auto-cpufreq.settings is unset/default, but that doesn't change the behavior of auto-cpufreq.
> 
> you can add mkIf (cfg.settings != {})
> 
> You're using /etc, but instead you can specify the --config option in ExecStart.

I'm aware, it just seemed unnecessary but I can do it anyhow.  :)
BRB

**Comment by nbraud** [comment]
Done!

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/228721

**Pull request merged**
