### PR TITLE
python3Packages.mysql-connector: 8.0.23 -> 8.0.24 and remove myself as maintainer

### PR DESCRIPTION
**Pull request by primeos**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119937` at 8c4c6f92 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.mysql-connector</li>
    <li>python39Packages.mysql-connector</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/mysql-connector/default.nix:32:5:
```
   |
32 |     maintainers = with lib.maintainers; [ ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/mysql-connector/default.nix:24:0:
```
   |
24 |     description = "A MySQL driver";
   | ^
```
</li>
  </ul>
</details>

**Comment by primeos** [comment]
@SuperSandro2000 btw I'd really prefer if you didn't squash such PRs. IMO updates and maintainer changes are independent and apart from that the commit message subject is too long when squashed (and the one extra sentence from the second commit got lost).

**Comment by SuperSandro2000** [comment]
Did I squash it? GitHub trolled me again by remembering that I squashed some other PR and transferred that to here.

**Comment by primeos** [comment]
Ah, yeah, it can be quite a bit annoying that GH remembers the last choice for merging instead of a default.

**Pull request merged**
