### PR TITLE
ocamlPackages.{lwt,ocplib-endian}: fix for OCaml >= 5

### LINKED ISSUE #227024: Build failure: ocaml-ng.ocamlPackages_5_0.mdx
### Steps To Reproduce

```sh-session
$ nix-build -A ocaml-ng.ocamlPackages_5_0.mdx
```

### Build log

Important parts:

```sh-session
...
398 | (rule
399 |  (target prelude.actual)
400 |  (deps (package mdx) (source_tree prelude))
401 |  (action
402 |   (with-stdout-to %{target}
403 |    (chdir prelude
404 |     (run ocaml-mdx test --output - --prelude-str "#require \"lwt\"" --prelude-str "toto:let x = \"42\"" test-case.md)))))
(cd _build/default/test/bin/mdx-test/expect/prelude && ../../../../../../install/default/bin/ocaml-mdx test --output - --prelude-str '#require "lwt"' --prelude-str 'toto:let x = "42"' test-case.md) > _build/defaul>
Got an error while evaluating:
---
#require "lwt"
---
No such package: bigarray - required by `lwt.unix'
Done: 92% (822/886, 64 left) (jobs: 16)^M                                       ^MDone: 93% (842/897, 55 left, 1 failed) (jobs: 16)^M                                                 ^MDone: 93% (842/897, 55 left, >
(cd _build/default && /nix/store/q951w69v8kbdrw6shdpibnl594yfr0by-diffutils-3.9/bin/diff -u test/bin/mdx-test/expect/lwt/test-case.md test/bin/mdx-test/expect/lwt.actual)
--- test/bin/mdx-test/expect/lwt/test-case.md   2023-04-19 08:32:48.313302890 +0000
+++ test/bin/mdx-test/expect/lwt.actual 2023-04-19 08:32:48.654289502 +0000
@@ -2,6 +2,7 @@
 
 \```ocaml
 # #require "lwt";;
+No such package: bigarray - required by `lwt.unix'
 # let x = Lwt.return 3;;
 val x : int Lwt.t = <abstr>
 \```
@@ -10,7 +11,9 @@
 
 \```ocaml
 # Lwt.return 4;;
-- : int = 4
+Line 1, characters 1-13:
+Error: Unbound module Lwt_main
 # Lwt_list.map_p Lwt.return [1;2;3];;
-- : int list = [1; 2; 3]
+Line 1, characters 1-34:
+Error: Unbound module Lwt_main
 \```
Done: 96% (889/919, 30 left, 1 failed) (jobs: 16)^M                                                 ^MDone: 97% (915/937, 22 left, 2 failed) (jobs: 10)^M                                                 ^MDone: 98%>
Testing `Mdx'.
This run has ID `07TRW5AD'.

  [OK]          Block           0   Header.infer_from_file: "".
...
  [OK]          Util            2   String.english_conjonction: three.
...skipping...
 # Lwt_list.map_p Lwt.return [1;2;3];;
-- : int list = [1; 2; 3]
+Line 1, characters 1-34:
+Error: Unbound module Lwt_main
 \```
Done: 96% (889/919, 30 left, 1 failed) (jobs: 16)^M                                                 ^MDone: 97% (915/937, 22 left, 2 failed) (jobs: 10)^M                                                 ^MDone: 98%>
Testing `Mdx'.
This run has ID `07TRW5AD'.

  [OK]          Block           0   Header.infer_from_file: "".
```

### Additional context

Is there a missing `propogatedBuildInput` or something like this? I’m not quite sure. `nix-build -A ocaml-ng.ocamlPackages_4_14.mdx` succeeds. It stops some downstream packages from building. Along with, is there a use for like `dos2unix` to remove these `^M`s?

### Notify maintainers

@romildo 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.24, NixOS, 23.05 (Stoat), 23.05.20230417.f00994e`
 (command hung after *shrug*)
```

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

Closes #227024.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
Why do you restrict the patches to OCaml ≥ 5.0? This PR changes the derivation hashes even when the patch is not applied and causes rebuild…

Also, the commit message (and the title of this PR) is rather misleading.

**Comment by wegank** [comment]
> Why do you restrict the patches to OCaml ≥ 5.0?

Because `bigarray` is no more standalone since OCaml 5.0.

> This PR changes the derivation hashes even when the patch is not applied and causes rebuild…

That could be fixed by `postPatch = if cond then ... else null`, but do we really want to do that?

> Also, the commit message (and the title of this PR) is rather misleading.

Both `ocaml-ng.ocamlPackages_5_0.lwt` and `ocaml-ng.ocamlPackages_5_0.ocplib-endian` are perfectly buildable without this PR. What would you suggest as an alternative of the commit message?

**Comment by vbgl** [comment]
Thanks for the clarification.

These libraries build, but are unusable; I’d rather read something like: “ocamlPackages.lwt: fix for OCaml ≥ 5”.

**Comment by wegank** [comment]
@ofborg build ocaml-ng.ocamlPackages_5_0.mdx

**Review by vbgl — APPROVED** [review]
Awesome!

**Comment by toastal** [comment]
Man, if this comes true I’ll be so happy! I’ve been wanting to get into OCaml now that multicore is on the feature list and apps are slowing starting to convert/be compatible. I opened the `uring` with the hopes of getting to `eio`.

**Comment by ulrikstrid** [comment]
@toastal in the meantime you can use the OCaml overlays over at https://github.com/ocaml-nix/nix-overlays

**Comment by Alizter** [comment]
Result of `nixpkgs-review pr 227050` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>acgtk</li>
    <li>coccinelle</li>
    <li>comby</li>
    <li>cvehound</li>
    <li>cvehound.dist</li>
    <li>dune-release</li>
    <li>flitter</li>
    <li>flow</li>
    <li>google-drive-ocamlfuse</li>
    <li>jackline</li>
    <li>libbap</li>
    <li>ligo</li>
    <li>liquidsoap</li>
    <li>python310Packages.bap</li>
    <li>python310Packages.bap.dist</li>
    <li>python311Packages.bap</li>
    <li>python311Packages.bap.dist</li>
    <li>reason</li>
    <li>sail-riscv-rv32</li>
    <li>sail-riscv-rv64</li>
    <li>soupault</li>
    <li>stog</li>
    <li>wayland-proxy-virtwl</li>
  </ul>
</details>

**Review by Alizter — APPROVED** [review]

**Pull request merged**
