### PR TITLE
hors: init at 0.8.2

### PR DESCRIPTION
**Pull request by figsoda**
###### Motivation for this change

hors  allows you to get instant coding answers via the command line

https://github.com/windsoilder/hors

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
@ofborg build hors

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 138766` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>hors</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [x] `meta.maintainers` is set
- [x] package builds (see https://github.com/NixOS/nixpkgs/pull/138766#issuecomment-923658720)
- [ ] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-138766-1]$ ./results/hors/bin/hors python yaml -n 2 -a
Search stackoverflow link failed with 'DuckDuckGo' search engine, you can try another engine through `-e` argument, or specify `$HORS_ENGINE` env variable to another value
...ew/pr-138766-1]$ ./results/hors/bin/hors -e google csv python -n 2 -a

- Answer from https://stackoverflow.com/questions/67943578/python-and-api-output-to-csv
[...]
```

Looks good to me.

**Comment by figsoda** [comment]
didnt build on darwin i will mae another pr to fix it

**Pull request merged**
