### PR TITLE
Mesa updates! 10.2.9 -> 10.4.4

### PR DESCRIPTION
**Pull request by eduarrrd**
OK, this probably requires some testing. Works for me so far though.

@vcunat Please review. Some stuff you added I had to remove and I could never figured out why it was there in the first place. I hope you can help me verify I didn't just break ALL THE THINGS ;-).

### CODE REVIEW

**Comment by eduarrrd** [comment]
Travis timed out as usual ...

**Comment by eduarrrd** [comment]
@vcunat The argument being made in the mesa commit is that egl drivers are mesa exclusive and should be used anywhere else if I'm reading it right. What's the point of taking them out?

BTW, it seems like a large part of the problem came from mesa expecting to be told about LLVM being built without (C++) RTTI through `llvm-config --cxxflags` by it containing `--fno-rtti` which was NOT the case.

**Comment by vcunat** [comment]
The drivers are split into another output because of heavy dependencies (mainly LLVM). They aren't needed for most stuff linking against libGL, which is the main use for mesa during builds. Therefore, the drivers even aren't present in $(libdir).

Moreover, we separate the driver choice to NixOS, so we use the impure ``/run/opengl-driver*`` links.

**Comment by eduarrrd** [comment]
Maybe this is my lack of understanding speaking but when I run `find /nix/store/*mesa-noglu-10.2.9* -name '*egl*'` none of the results are in `-drivers/`. Same from the other prespective:
`libEGL.so -> /nix/store/m1pbnsg9iw0jhb4z0smjsmqvjds3kzlr-mesa-noglu-10.2.9/lib/libEGL.so` in `/run/opengl-driver/`.

What am I supposed to see?

**Comment by vcunat** [comment]
Ah, I'm sorry, it got moved to the main output. Still, the main point is that e.g. my main system is using a different libEGL (provided by nvidia). Therefore the EGL search patch shouldn't be hardcoded under $(libdir) but under ${driverLink}.

**Comment by eduarrrd** [comment]
Just so I'm getting this right, the point is for mesa to find EGL libraries/drivers under `${driverLink}` while the location of mesa's EGL stuff does not need to be modified?

**Comment by eduarrrd** [comment]
So if I'm reading the mesa code right, the constant is used only once, in `src/egl/main/egldriver.c`, within `_eglGetSearchPath()`. It is a constant additional path added to the basename of `EGL_DRIVER` and `EGL_DRIVERS_PATH` environment variables. Shouldn't we be using those instead of making unsupported changes to the build system? Also, scons sets the initial path to `""` (empty string) instead of of .`$(libdir)/egl`.

**Comment by vcunat** [comment]
I agree that patching the file is a good and easy solution.

**Comment by vcunat** [comment]
Now I'm running this and some other mass-rebuild changes; it seems good. I expect to polish it and push to staging tomorrow.

**Comment by vcunat** [comment]
Is there an upstream bug open for those check errors? (So that I get some notification when we might try checks again.)

**Comment by vcunat** [comment]
I squashed the mesa updates, including a .5 bump (only tested it builds); and leaving the authorship with you, as it was mostly your work.

It's in staging now, included with some other mass-rebuild changes. My whole system built and runs fine (including KDE4, some Xfce and GNOME3 components), so I expect no further larger problems. I tested nouveau and nvidia to cover both mesa and non-mesa drivers.

**Comment by iElectric** [comment]
Thank you

**Comment by eduarrrd** [comment]
Thanks @vcunat for fixing this up!

As for the check, I couldn't find the thread :-/. The problem it comes down is that all tests pass but `src/glsl/tests/lower_jumps/create_test_cases.py` pass. The type of error seemed to be tool related from what I remember. I'll keep watch on this and see how to fix it once I find some time.

**Comment by vcunat** [comment]
I've found through years of nixpkgs work that it doesn't pay off investing much energy into fixing package tests. In most cases I get no reasonable reaction from upstream (I don't count pointless requests for reproducing against latest master as reasonable). Mesa's probably above average in this, but still...

**Pull request closed without merging**
