### PR TITLE
python3Packages.sip: 6.8.0 -> 6.8.1

### LINKED ISSUE #281100: Build failure: qgis build is failing during sip-build
### Steps To Reproduce

1. with latest master do `nix-build -A qgis`

### Build log

```
pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
Querying qmake about your Qt installation...
These bindings will be built: gui.
Generating the gui bindings...
Generating the _gui .api file...
Generating the _gui .pyi file...
sip-build: An internal error occurred...
Traceback (most recent call last):
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/bin/.sip-build-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/tools/build.py", line 37, in main
    handle_exception(e)
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/exceptions.py", line 83, in handle_exception
    raise e
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/tools/build.py", line 34, in main
    project.build()
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/project.py", line 245, in build
    self.builder.build()
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/builder.py", line 46, in build
    self._generate_bindings()
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/builder.py", line 273, in _generate_bindings
    buildable = bindings.generate()
                ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/bindings.py", line 220, in generate
    output_code(spec, self, project, buildable)
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 60, in output_code
    _module_code(spec, bindings, project, py_debug, buildable)
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 512, in _module_code
    _virtual_handler(sf, spec, handler)
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 4530, in _virtual_handler
    sipres_value = _call_default_ctor(spec, ctor)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 4254, in _call_default_ctor
    class_type = fmt_argument_as_cpp_type(spec, arg.definition)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kaf0lwx9czgl3xcl3bxicl3apx8gzvj0-python3.11-sip-6.8.0/lib/python3.11/site-packages/sipbuild/generator/outputs/formatters/argument.py", line 46, in fmt_argument_as_cpp_type
    original_typedef = arg.original_typedef
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WrappedClass' object has no attribute 'original_typedef'
ninja: build stopped: subcommand failed
```

### Additional context

Hydra job: https://hydra.nixos.org/build/246593929

### Notify maintainers

Notify @NixOS/geospatial 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by imincik**
## Description of changes

Patch update of SIP fixing multiple regressions introduced in v6.8.0 and causing many build failures (for example https://github.com/NixOS/nixpkgs/issues/281100)

See: https://riverbankcomputing.com/news/SIP_v6.8.1_Released
and https://www.riverbankcomputing.com/hg/sip/file/tip/NEWS

fixes #281100
closes https://github.com/NixOS/nixpkgs/pull/282473

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please add a ``Closes #281100`` to the PR body.

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by imincik** [comment]
@mweinelt , should this PR go to `python-updates` or `staging` branch instead of `master` ?

**Comment by dotlambda** [comment]
Why not update to 6.8.2?

**Comment by imincik** [comment]
> Why not update to 6.8.2?

6.8.2 release is not yet announced in [news](https://riverbankcomputing.com/news). I am not sure whether it is released or not.

**Comment by kirillrdy** [comment]
> @mweinelt , should this PR go to `python-updates` or `staging` branch instead of `master` ?

3109 packages updated:

If there is no currently active python-updates branch, then this should go to staging

**Comment by dotlambda** [comment]
> > Why not update to 6.8.2?
> 
> 6.8.2 release is not yet announced in [news](https://riverbankcomputing.com/news). I am not sure whether it is released or not.

https://www.riverbankcomputing.com/hg/sip/file/tip/NEWS lists it as released on December 31.

**Comment by imincik** [comment]
> Why not update to 6.8.2?

@dotlambda , version 6.8.2 is not on PyPi (which is the source repo for this package).

**Comment by imincik** [comment]
@vcunat , would you please include this PR in https://github.com/NixOS/nixpkgs/pull/281828 . Thanks .

**Review by Stunkymonkey — APPROVED** [review]

**Review by dotlambda — APPROVED** [review]

**Comment by dotlambda** [comment]
Why does aarch64-darwin fail with

> error: attribute 'tests' in selection path 'python311Packages.sip.passthru.tests' not found

?

**Comment by kirillrdy** [comment]
> Why does aarch64-darwin fail with
> 
> > error: attribute 'tests' in selection path 'python311Packages.sip.passthru.tests' not found
> 
> ?

see if pythonPackages.poppler-qt5 builds on aarch64-darwin even with this change, maybe try ofborg ?

**Comment by dotlambda** [comment]
> see if pythonPackages.poppler-qt5 builds on aarch64-darwin even with this change, maybe try ofborg ?

That shouldn't change whether the attribute 'tests' exists. Anyway:
@ofborg build python3Packages.poppler-qt5

**Comment by kirillrdy** [comment]
> > see if pythonPackages.poppler-qt5 builds on aarch64-darwin even with this change, maybe try ofborg ?
> 
> That shouldn't change whether the attribute 'tests' exists. Anyway: @ofborg build python3Packages.poppler-qt5

I've seen that error before, when one of tests dependencies was not supported on that platform, I assumed it's normal

**Comment by imincik** [comment]
Thanks for moving this forward !

**Pull request merged**
