### PR TITLE
portaudio: build with JACK on linux

### PR DESCRIPTION
**Pull request by starcraft66**
###### Motivation for this change

Applications relying on PortAudio such as Mixxx cannot use the JACK audio backend.

I tested this on my system and Mixxx now correctly detects JACK. This caused a fairly long rebuild on my computer due to webkitgtk, libreoffice and Chromium among others depending on PortAudio. I expect this change to trigger a mass rebuild so I will target it against staging.

Fixes https://github.com/NixOS/nixpkgs/issues/157529

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by poelzi** [comment]
LGTM. fixes for me the problem of missing jack output

**Review by poelzi — APPROVED** [review]

**Comment by poelzi** [comment]
@Mic92 can you merge please :)

**Comment by visceralchokehold** [comment]
Hello, seems this might not get merged, so could you teach me how to add this to my NixOS system?

**Comment by starcraft66** [comment]
@visceralchokehold Example from my config, you can add that snippet to your packages: https://github.com/starcraft66/os-config/blob/master/flake.nix#L54-L57

**Comment by starcraft66** [comment]
Looks like this rotted enough to get a merge conflict, just committed a resolution via the web interface. It should still build...

**Comment by prusnak** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/215284 

We can build portaudio with jack on darwin too.

**Pull request closed without merging**
