### PR TITLE
vimPlugins.peskcolor-vim: remove

### LINKED ISSUE #336856: 404 Error using `vimPluginsUpdater` due to `andsild/peskcolor.vim`
### Describe the bug
When trying to use the vimPluginsUpdater to update `generated.nix`, a 404 error occurs when fetching plugins.
This error occurs from attempting to fetch from the link [https://github.com/andsild/peskcolor.vim](https://github.com/andsild/peskcolor.vim), which no longer appears to exist on GitHub.

### Steps To Reproduce
1. nix-shell -p vimPluginsUpdater --run vim-plugins-updater

### Expected behavior
Expected `generated.nix` to be updated without error.

### Additional context

Full trace:
```
nix-shell -p vimPluginsUpdater --run vim-plugins-updater
path is '/nix/store/15mcxy6nsyalafifmhg1h20jm6i2h914-06bb771690bc9df0763d14769b779062d8f12bc5.tar.gz'
Prefetching
HTTP Error 404: Not Found, Retrying in 3 seconds...
HTTP Error 404: Not Found, Retrying in 6 seconds...
HTTP Error 404: Not Found, Retrying in 12 seconds...
1482 plugins were checked, 1 plugin(s) could not be downloaded:

PluginDesc(repo=Repo(peskcolor.vim, https://github.com/andsild/peskcolor.vim/), branch='', alias=''): HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/nix/store/w83lg4nh2kh6bvb2gc12yqndmrw0i1ix-vim-plugins-updater-0.1/lib/pluginupdate.py", line 724, in prefetch
    plugin, redirect = prefetch_plugin(pluginDesc, cache)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/w83lg4nh2kh6bvb2gc12yqndmrw0i1ix-vim-plugins-updater-0.1/lib/pluginupdate.py", line 597, in prefetch_plugin
    commit, date = repo.latest_commit()
                   ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/w83lg4nh2kh6bvb2gc12yqndmrw0i1ix-vim-plugins-updater-0.1/lib/pluginupdate.py", line 76, in f_retry
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/nix/store/w83lg4nh2kh6bvb2gc12yqndmrw0i1ix-vim-plugins-updater-0.1/lib/pluginupdate.py", line 193, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/imd120fan53pgy6qi6kra0q15v5kn6dn-nix-info
copying path '/nix/store/imd120fan53pgy6qi6kra0q15v5kn6dn-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.153.1-microsoft-standard-WSL2, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by PerchunPak**
## Description of changes

Author just deleted the repository (yesterday it existed), and 404 breaks the update script. This PR removes `peskcolor-vim` from auto-updater in the same way as it was done before (ref 6289ae751a92e2c61a782bb65576a95c5afd9a1c).

Fixes #336856

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@GaetanLepage

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PerchunPak** [comment]
Result of `nixpkgs-review pr 336589` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by PerchunPak** [comment]
Also ran the updater and didn't find any other 404s

**Comment by GaetanLepage** [comment]
Has the repo moved ?
If so, we should point to the new host in `vim-plugin-names`.
Otherwise, we should consider remove it...

**Comment by PerchunPak** [comment]
If repo moves, GitHub does a redirect and it gets automatically handled by the update script. This looks like someone's personal color scheme, so no users (hopefully) will depend on it.

By grepping `git log pkgs/applications/editors/vim/plugins`, it looks like only two plugins were moved to `overrides.nix` this way (bc791d55e06190169a023ebb9620f0c5a7790a48, 559dbaaaa5e18c83a9f26ded374e9c05d253ded8) and 2 more plugins were just dropped (1ee0d7545655, d87bfc99ceb9). I would rather drop this plugin completely, so doing that.

**Review by GaetanLepage — APPROVED** [review]
LGTM thanks !

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 336589` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by PerchunPak** [comment]
Fixes #336856

**Comment by PerchunPak** [comment]
@teto, if GaetanLepage already approved this, can we merge?

**Pull request merged**
