### PR TITLE
Fix incorrect mktemp usage in `nix-prefetch-git` which breaks fetching LFS repositories

### PR DESCRIPTION
**Pull request by tcbravo**
###### Motivation for this change

The affected part of `nix-prefetch-git` runs when fetching a repository with `fetchgit` and passing `fetchLFS = true`. Specifically, there is an invocation of `mktemp` which seems to be incorrect - it fails on my systems with the following error, inside or outside of a build environment:

`mktemp: failed to create directory via template ‘nix-prefetch-git-tmp-home-XXXXXXXXXX/tmp.XXXXXXXXXX’: No such file or directory`

With the change in this PR, the `mktemp` command runs in isolation and fetching repositories with LFS works again. I think this should probably be backported to 21.11 since the combination of `-d` and `-p` (introduced in #134122) is incorrect usage to the best of my knowledge.

###### Things done

Removed the `-p` flag passed to an invocation of `mktemp` in `nix-prefetch-git`.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
gimme a nudge when @bjornfor does not react in a couple days

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
I was sure I had tested it (https://github.com/NixOS/nixpkgs/pull/134122#pullrequestreview-735511568) :cry: . But now I see the error:

```
$ mktemp -d -p nix-prefetch-git-tmp-home-XXXXXXXXXX
mktemp: failed to create directory via template ‘nix-prefetch-git-tmp-home-XXXXXXXXXX/tmp.XXXXXXXXXX’: No such file or directory
```

Note that this creates the directory in $PWD, not in $TMPDIR (unlike the other mktemp calls in that script). So a follow-up or amend could be to use the same `mktemp` style as the rest of the file to not pollute $PWD (although the directory should be cleaned up after).

**Comment by tcbravo** [comment]
Agreed, I amended the change to respect $TMPDIR.

**Comment by bjornfor** [comment]
Thanks!

**Pull request merged**
