### PR TITLE
pythonPackages.pyproj1: Added support for version 1.9.6

### PR DESCRIPTION
**Pull request by Rakesh4G**
###### Motivation for this change
Structure for pyproj is very different from pyproj version 2 onwards, Some applications (e. g. Mapproxy) are still using old structure from pyrpoj (1.9.6). So with latest nixpkgs they doesn't work.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
@CMCDragonkai @jonringer

### CODE REVIEW

**Review by jonringer — CHANGES_REQUESTED** [review]
we cannot have different versions of the same package within the same package set, if it needs to be overriden, then please override it for the application. Look at aws-sam-cli for an example

**Comment by Rakesh4G** [comment]
> we cannot have different versions of the same package within the same package set, if it needs to be overriden, then please override it for the application. Look at aws-sam-cli for an example

OK, @jonringer

**Comment by CMCDragonkai** [comment]
@jonringer There are other packages where "v1s" were left over due to incompatibility with lots of other packages.

**Comment by jonringer** [comment]
In the python-modules package set, this creates an issue. Because if you're in an environment where packageA needs pyproj1 ,and packageB needs pyproj2, then PYTHONPATH will have both packages on it. However, when it goes to do `import pyproj`, it will only resolve to one of the packages. This will break either packageA or packageB in a subtle way

**Comment by jonringer** [comment]
> @jonringer There are other packages where "v1s" were left over due to incompatibility with lots of other packages.

If there are such packages, this was an oversight.

**Comment by Rakesh4G** [comment]
> we cannot have different versions of the same package within the same package set, if it needs to be overriden, then please override it for the application. Look at aws-sam-cli for an example
Hi @jonringer 
I have updated mapproxy to override pyproj locally.
https://github.com/NixOS/nixpkgs/pull/68628

**Comment by jonringer** [comment]
Ah, that is much  more acceptable, as it won't create an in-coherent package set

**Comment by FRidh** [comment]
#68628 is merged, so closing this.

**Pull request closed without merging**
