### PR TITLE
vim-plugins: rewrite updater

### PR DESCRIPTION
**Pull request by Mic92**
A new python script has been added to replace the aged viml-based
updater. The new updater has the following advantages:

- use rss feeds to check for updates quicker
- parallel downloads & better caching
- uses proper override mechanism instead of text substitution
- update generated files in-place instead of having to insert updated plugins manually

Automatically adding plugin `dependencies` based on plugin metadata has been
not re-implemented in this updater.
This mechanism has been mostly been used by Mark Weber's plugins, which seem to
no longer receive regular updates.
This could be implemented in future as required.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
nix-review is happy with the new version.

**Comment by LnL7** [comment]
I had a feeling about this when seeing https://github.com/NixOS/nixpkgs/commit/182f1fc2c8f046f97e0c9f5626e9647b66f24ef7. 😃

**Comment by Mic92** [comment]
It is much more fun to add vim plugins now.

**Comment by Mic92** [comment]
Now with documentation! I will backport the first commit, where I extended the vim plugin documentation.

**Comment by rvolosatovs** [comment]
How can the `update.py` script itself be accessed? Is it in the repository?
`git ls-tree 484e180 pkgs/misc/vim-plugins -r | rg 'update.py'` returns 0 results.
Am I missing something?

**Pull request merged**
