### PR TITLE
haskellPackages: improve LLVM handling for GHC

### PR DESCRIPTION
**Pull request by sternenseemann**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/Mw5WLnzsP7fC4Zky) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

---

This is the follow-up to #146621. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

I'll focus on working on GHC in this iteration and maybe even skip bumping hackage. The things I'm looking into are:

* [x] Use latest supported LLVM version for every GHC
* [x] Simplify how `llvmPackages` is reexposed in the package set
* [x] Fix `pkgsCross.*.buildPackages.ghc` (is not a cross-compiler counter-intuitively)
* [x] Unify NCG-detection mechanism for `withPackages` and GHC derivations
* [x] Investigate if we can avoid propagating LLVM in the GHC derivations and instead add it to the wrapper
* [ ] #146770 

Fixes to existing packages / unbreaking packages are always welcome of course!

### CODE REVIEW

**Review by prusnak — COMMENTED** [review]
untested, but changes look good

**Comment by sternenseemann** [comment]
Sadly upgrading LLVM to 12 for GHC 8.10.7 doesn't solve some instances of LLVM's `opt` failing during compilation for `aarch64-darwin` that were reported on Matrix. This seems to be happening when compiling `haskellPackages.happy_1_19_12` which is required for ghcjs.

**Comment by zowoq** [comment]
Sorry for asking here but matrix won't let me in...

What's the best way of making sure that `haskellPackages.ShellCheck` always points to the latest version? IIRC there used to be a hack somewhere in the haskell tooling that did this but `0.8.0` has been out for three weeks and `ShellCheck` is still at 0.7.2?

**Comment by sternenseemann** [comment]
@zowoq Seems like we [used to delete the version constraint on `ShellCheck`](https://github.com/NixOS/nixpkgs/commit/f3f84855e8fa9b190a14f49c5c6db9e816e72c10#diff-761c52eee41fac26653a0540d5ce647485105ab241ecdd5aeda45bfb5c6311c1R38) coming from stackage. This was deleted in a later cleanup trimming down the sed expression.

Not having the latest version of something due to stackage is an annoyance with most packages that are “user facing”, so shellcheck, pandoc, xmonad etc. This should get better when we switch to stackage nightly again, but is an inherent flaw of our packaging approach.

Since we do have the latest version of every package available, there should be nothing stopping us from using them for the top level packages (except for XMonad which is a bit tricky) with a bit of manual effort.

**Comment by sternenseemann** [comment]
Seems like everything worked out. Aside from some flaky test suites, there is only one regression, namely `haskellPackages.risc386` on `aarch64-linux` which fails due to a crash (bug) in LLVM. This seems to be due to our upgrade to LLVM 12, not our changes to GHC's packaging which is great.

Some stuff I have in mind is still pending which I'll tackle some other time:

* `ghcWithPackages`/`ghcWithHoogle` refactors (#146770)
* Set absolute paths in the binary GHCs' `settings` files as well (this is not urgent since our binary GHCs just need to be good enough to build the proper GHCs, but still nicer overall; since it's easy enough to test, it's just a matter of slipping in a set rebuild at some point (maybe even via staging?))
* Have an absolute path for `touch` in `settings` (this is not supported by upstream at the moment, maybe we should try to get a patch in?)

Some of the changes here will be backported as #147404, but mostly the LLVM upgrades. 17b8b5a4dc5a49d83d508cb66c6ac2f0bb9fa39b would be very cool to backport, but I'd like to see if there are any downstream issues first. Backporting after release has the issue that this is a *subtle* breaking change since LLVM would no longer be in `PATH` in derivations that use a GHC with LLVM, but not sure if anyone relies on this behavior.

**Comment by zowoq** [comment]
> Seems like we [used to delete the version constraint on `ShellCheck`](https://github.com/NixOS/nixpkgs/commit/f3f84855e8fa9b190a14f49c5c6db9e816e72c10#diff-761c52eee41fac26653a0540d5ce647485105ab241ecdd5aeda45bfb5c6311c1R38) coming from stackage.

Knew it used to be around somewhere, thanks for finding it.

> Since we do have the latest version of every package available, there should be nothing stopping us from using them for the top level packages (except for XMonad which is a bit tricky) with a bit of manual effort.

`ShellCheck` does have a top level package that installs `justStaticExecutables haskellPackages.ShellCheck` and docs/manpage.

PR: https://github.com/NixOS/nixpkgs/pull/147780

**Pull request merged**
