### PR TITLE
Update Haskell package set to LTS 15.8 (plus other fixes)

### PR DESCRIPTION
**Pull request by peti**
This PR is test-built by Hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. I'll fix up the remaining errors and merge it on Friday, 2020-04-17 [20:00 CET](http://www.thetimezoneconverter.com/?t=20:00&tz=Berlin). You can watch this live on Twitch at https://www.twitch.tv/peti343. In addition to the chat features offered by Twitch, there is also a voice conference at https://discord.gg/YTEa3XR that viewers can use to chat with me and with each other.

## TODO

- [x] Confirm that https://github.com/NixOS/nixpkgs/pull/85446 has fixed `ghcWithPackages` for ghc-8.10.x.
- [x] Investigate why `ghc-lib-parser-ex-8.8.5.8` seems to [fail to compile for Niklas](https://buildkite.com/nh2/static-haskell-nix/builds/358#97768331-aaff-4e46-af14-502b2754c144).
- [ ] Split-out a minimal `nix` docker image: https://github.com/NixOS/docker/pull/13
- [ ] Run `krank` on our override files and collect a TODO list of possibly outdated items.
- [x] Update `all-cabal-hashes` reference.
- [x] Merge r-updates, too, if there's time: https://github.com/NixOS/nixpkgs/pull/81307
- [x] Merge https://github.com/NixOS/nixpkgs/pull/84980 *after* we've merged to `master` to get it in for the next session.

### CODE REVIEW

**Comment by nh2** [comment]
One thing I'd like us to look into:

My [CI failure](https://buildkite.com/nh2/static-haskell-nix/builds/358#97768331-aaff-4e46-af14-502b2754c144) against `master` says:

```
Configuring ghc-lib-parser-ex-8.8.5.8...
Setup: Encountered missing dependencies:
ghc-lib-parser -any

builder for '/nix/store/4bhjr2nz9i2lyffp6ivqwxf7dxakx4ch-ghc-lib-parser-ex-8.8.5.8.drv' failed with exit code 1
```

And indeed, `hackage-packages.nix` doesn't list in `"ghc-lib-parser-ex"` a dependency on `ghc-lib-parser`, even though the cabal file of that version [lists the dependency](https://hackage.haskell.org/package/ghc-lib-parser-ex-8.8.5.8).

**Comment by cdepillabout** [comment]
@nh2 It looks like that dependency is behind a flag, which is maybe why cabal2nix isn't picking it up.

https://hackage.haskell.org/package/ghc-lib-parser-ex-8.8.5.8/ghc-lib-parser-ex.cabal

**Comment by nh2** [comment]
> It looks like that dependency is behind a flag, which is maybe why cabal2nix isn't picking it up.

@cdepillabout Thanks! And it looks like the logic is changing again: https://github.com/shayne-fletcher/ghc-lib-parser-ex/pull/42

**Comment by guibou** [comment]
`krank` author here. I'm really happy that you are trying `krank` to track outdated overrides. Please, let me know (here or in [krank](https://github.com/guibou/krank/issues) issue tracker) if there is any improvement I can do.

**Comment by nh2** [comment]
@guibou I hadn't known about `krank` until now, that sounds really useful also for my own projects (and especially ugprades of NixOS!).

No specific requests yet, but I noticed one thing: Given that `krank` is a Haskell program, could you add it to Stackage? That would significantly increase the chances that it itself will not break in nixpkgs (reducing maintenance effort over here), and will also make it much easier to get it to build e.g. in [static-haskell-nix](https://github.com/nh2/static-haskell-nix).

**Comment by peti** [comment]
Next week we'll merge https://github.com/NixOS/nixpkgs/pull/85926.

**Pull request merged**
