### PR TITLE
nixos/mautrix-facebook: add new required config option

### PR DESCRIPTION
**Pull request by kevincox**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
There's not been a bump since April -- why is this suddenly needed?

**Comment by kevincox** [comment]
I haven't looked into it too far yet. I suspect that a mautrix bump caused this issue.

**Comment by kevincox** [comment]
Mautrix was updated 2 weeks ago: https://github.com/NixOS/nixpkgs/commit/3abbce5848bd3da6b626b4b4635612cd339c5026

**Comment by winterqt** [comment]
I force-pushed to fix the commit message, but looking at it now, this shouldn't be required.

Mautrix defaults to `standard`, see https://github.com/mautrix/python/blob/690f4702cbdf1145646a6deebd21946a6338854c/mautrix/bridge/user.py#L131.

What error do you get when this option isn't set?

**Comment by kevincox** [comment]
I got an explicit error that this open is required and not set. Away from the exact log right now but it was very clear.

**Comment by winterqt** [comment]
Ah, here we go: https://github.com/mautrix/python/commit/bc7a01c77ca302e10b3e875f6175b59827cb4ab6.

I assume the error was `Invalid value for homeserver.software in config`?

**Comment by kevincox** [comment]
Something like that. I don't remember if it was invalid or missing but I can check tomorrow.

**Review by winterqt — APPROVED** [review]
Sent out a call for maintainers of Mautrix Python based software to check if they're affected by this.

**Comment by kevincox** [comment]
You did have the right error message. For reference the entire log message with metadata is below (with system-specific information removed).

```json
{
  "CODE_FILE": "/nix/store/hifpjkhq21haj87kmpjd94gk064wgcxx-python3.10-mautrix-0.18.4/lib/python3.10/site-packages/mautrix/bridge/bridge.py",
  "CODE_FUNC": "prepare",
  "CODE_LINE": "126",
  "LOGGER": "mau.init",
  "MESSAGE": "mau.init: Invalid value for homeserver.software in config",
  "PRIORITY": "2",
  "PROCESS_NAME": "MainProcess",
  "SYSLOG_IDENTIFIER": "mautrix-facebook",
  "THREAD_NAME": "MainThread",
  "_COMM": "python",
  "_EXE": "/nix/store/fkcl1wzq3106qqgl84bhgk1lp56q6bzg-python3-3.10.7/bin/python3.10",
  "_SYSTEMD_CGROUP": "/system.slice/mautrix-facebook.service",
  "_SYSTEMD_SLICE": "system.slice",
  "_SYSTEMD_UNIT": "mautrix-facebook.service",
  "_TRANSPORT": "journal",
}
```

**Pull request merged**
