### PR TITLE
bundler: 1.16.3 -> 1.16.6

### PR DESCRIPTION
**Pull request by alyssais**
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by zimbatm** [comment]
thanks! It looks like 1.16.6 is already out, do you mind bumping the PR?
https://github.com/bundler/bundler/blob/1-16-stable/CHANGELOG.md

**Comment by alyssais** [comment]
Wow they're moving quickly! Will do

**Comment by alyssais** [comment]
Done :)

**Comment by zimbatm** [comment]
@GrahamcOfBorg build bundler

**Comment by zimbatm** [comment]
Thanks @alyssais 

You have been doing good ruby contributions over time. If you want ofborg to auto-build your PR, make a PR to the ofborg repo like https://github.com/NixOS/ofborg/pull/252 and I will +1 you.

**Comment by zimbatm** [comment]
If you're interested, make sure to read the [README](https://github.com/NixOS/ofborg/#readme) to understand how it works first

**Comment by ryantm** [comment]
@zimbatm @alyssais It looks like this got merged as just upgrading bundler to `1.16.4`

**Comment by alyssais** [comment]
https://github.com/NixOS/nixpkgs/pull/50416

**Pull request merged**
