### PR TITLE
qt57: darwin compatibility

### PR DESCRIPTION
**Pull request by periklis**
Port of the qt56 compatibility patch 7a9400d by @acowley

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
Reverted in https://github.com/NixOS/nixpkgs/commit/a2eae3bc4433e8d3f3c3690532bf99fdfbd8b3a1. Let me know if you want me to test a new version of the changes.

http://hydra.nixos.org/eval/1340739

**Comment by periklis** [comment]
The Link to hydra isn't working for me.

**Comment by LnL7** [comment]
The linux builds for `qt57.qtbase` broke, https://gist.github.com/LnL7/c22b667a75c79e236e39445204bc75f0

**Comment by periklis** [comment]
Thx for the log

**Pull request merged**
