### PR TITLE
maude: 3.3.1 -> 3.4

### PR DESCRIPTION
**Pull request by timKraeuter**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by peti — APPROVED** [review]

**Comment by donovanglover** [comment]
Result of `nixpkgs-review pr 331988` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>tamarin-prover</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>maude</li>
  </ul>
</details>

Seems to be caused by https://github.com/tamarin-prover/tamarin-prover/blob/7b79a738b75c6fc8825614c23e3dc43381d3a203/src/Main/Console.hs#L176

**Comment by timKraeuter** [comment]
> Result of `nixpkgs-review pr 331988` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:
> 1 package built:
> 
> Seems to be caused by https://github.com/tamarin-prover/tamarin-prover/blob/7b79a738b75c6fc8825614c23e3dc43381d3a203/src/Main/Console.hs#L176

Thanks for the information. I created a [pull request to update Maude](https://github.com/tamarin-prover/tamarin-prover/pull/670) in the tamarin-prover.

**Review by drupol — DISMISSED** [review]
Looks like tests are broken.

**Comment by timKraeuter** [comment]
Once my pull request to tamarin-prover is merged and the package is updated, it should work.

**Comment by drupol** [comment]
Mark it as draft then please, so we don't spend time on this yet.

**Comment by timKraeuter** [comment]
My pull request to tamarin-prover was merged. They aim for a release in mid-September, which would include my fix.
I will wait with this pull request until a new release of the prover, which then becomes compatible with the new Maude version.

**Comment by vbgl** [comment]
Tamarin 1.10 is out. See #352371.

**Comment by timKraeuter** [comment]
Looks good. When that is merged we can move forward with this pull-request.

**Comment by timKraeuter** [comment]
Tamarin 1.10 is merged so the tests should not fail anymore.

**Comment by vbgl** [comment]
@GrahamcOfBorg maude tamarin-prover

**Pull request merged**
