### PR TITLE
fluentd: add cloudwatchlogs plugin

### PR DESCRIPTION
**Pull request by DzmitrySudnik**
And whatever got autoupgraded by running
`bundle lock --update && bundix`

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @nicknovitski

### CODE REVIEW

**Comment by risicle** [comment]
`nix-review` builds for me macos 10.13, all binaries can give me `--help`.

**Comment by DzmitrySudnik** [comment]
Hi @alyssais and @zimbatm , could you please review this?
Thank you

**Comment by alyssais** [comment]
Seems a bit weird to me that plugins are all bundled into this one package, and since I don’t know anything about the package, I don’t know what criteria we should be using to decide whether to include a plug-in or not.

I’d like to hear from @nicknovitski, the maintainer of the package.

**Comment by zimbatm** [comment]
ruby bundler doesn't have a good way to load plugins

**Pull request merged**
