### PR TITLE
SAGA, SAGA LTS release, dependencies and QGIS SAGA plugin

### PR DESCRIPTION
**Pull request by mpickering**
###### Motivation for this change

I wanted to use SAGA plugins with QGIS. In order to do so I had to make SAGA and its dependencies build on darwin. I also had to package an older SAGA release as QGIS requires this specific version. In the end I copied the derivation rather than overriding as it was not too complicated and easier to understand this way. 

Attributes to check: `saga_2_3_2` and `saga`. 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@grahamcofborg build saga saga_2_3_2

**Comment by mpickering** [comment]
I don't understand why the build is reported as failed. It looks like it completes.

**Comment by xeji** [comment]
Check the full log, there are some errors during the process.

**Comment by mpickering** [comment]
@GrahamcOfBorg build saga_2_3_2

**Comment by mpickering** [comment]
Everything builds here now.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build saga saga_2_3_2

**Comment by 7c6f434c** [comment]
I have read the code (including the referenced external patch — I noticed one).

It seems to me that the code is reasonable. Aarch64 has never been built on Hydra anyway. Maybe mark as broken-if-aarch64?

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build qgis

**Comment by 7c6f434c** [comment]
@mpickering Hydra makes me wonder if the Darwin failure of `qgis` is a regression.

**Comment by mpickering** [comment]
@7c6f434c Seems to be #48065

I think this patch should be merged even though it doesn't build currently. If it is not merged now then I will have to post on the mailing list again in three months for someone to review it.

**Comment by 7c6f434c** [comment]
Ah, OK, then it is not a regression related to this PR.

Yes, it breaks nothing on Linux and looks reasonable, and it does indeed seem that you are the most .qualified person to keep track of Darwin+GIS, so let your next attempt start from a better position…

@michelk what is your opinion about adding @mpickering as a co-maintainer for `saga`?

**Comment by michelk** [comment]
yes @7c6f434c,  please add @mpickering as co-maintainer.

**Pull request merged**
