### PR TITLE
nixos-rebuild: use --pipe instead of --pty in systemd-run

### LINKED ISSUE #262686: nixos-rebuild with --target-host hangs in github action environment
### Describe the bug
I've set up a github action to deploy nixos on remote hosts with command
```
nix run nixpkgs#nixos-rebuild -- --flake .#"$host" --target-host deploy@"$host".rvf6.com --use-remote-sudo switch
```

But after #258571, it stops working.

The failed job https://github.com/duament/flakes/actions/runs/6598694622/job/17926924711 shows it hangs for about 2 hours and exit abnormally. On the target host I found `nixos-rebuild-switch-to-configuration.service` exited successfully but the `systemd-run` process hangs.

I can also reproduce it locally with `systemd-run --user --same-dir nix run nixpkgs#nixos-rebuild -- --flake .#az --target-host deploy@az.rvf6.com --use-remote-sudo switch`.

Might be related to tty.

### Steps To Reproduce
1. Run nixos-rebuild --target-host either in github action environment or locally with systemd-run

### Expected behavior
Exit successfully

### Screenshots
```
❯ systemctl status nixos-rebuild-switch-to-configuration.service session-16.scope
○ nixos-rebuild-switch-to-configuration.service - /nix/store/hy54mnahnssgf95wfk890gr6kgamnizq-nixos-system-az-23.11.20231021.fcb40e7/bin/switch-to-configuration switch
     Loaded: loaded (/run/systemd/transient/nixos-rebuild-switch-to-configuration.service; transient)
  Transient: yes
     Active: inactive (dead) since Sun 2023-10-22 14:45:28 HKT; 26min ago
   Duration: 4.190s
    Process: 5365 ExecStart=/nix/store/hy54mnahnssgf95wfk890gr6kgamnizq-nixos-system-az-23.11.20231021.fcb40e7/bin/switch-to-configuration switch (code=exited, status=0/SUCCESS)
   Main PID: 5365 (code=exited, status=0/SUCCESS)
         IP: 0B in, 0B out
         IO: 0B read, 0B written
        CPU: 1.147s

Oct 22 14:45:25 az nixos[5365]: switching to system configuration /nix/store/hy54mnahnssgf95wfk890gr6kgamnizq-nixos-system-az-23.11.20231021.fcb40e7
Oct 22 14:45:26 az su[5616]: Successful su for deploy by root
Oct 22 14:45:26 az su[5616]: pam_unix(su:session): session opened for user deploy(uid=993) by (uid=0)
Oct 22 14:45:26 az su[5616]: pam_unix(su:session): session closed for user deploy
Oct 22 14:45:26 az su[5623]: Successful su for rvfg by root
Oct 22 14:45:26 az su[5623]: pam_unix(su:session): session opened for user rvfg(uid=1000) by (uid=0)
Oct 22 14:45:27 az su[5623]: pam_unix(su:session): session closed for user rvfg
Oct 22 14:45:28 az nixos[5365]: finished switching to system configuration /nix/store/hy54mnahnssgf95wfk890gr6kgamnizq-nixos-system-az-23.11.20231021.fcb40e7
Oct 22 14:45:28 az systemd[1]: nixos-rebuild-switch-to-configuration.service: Deactivated successfully.
Oct 22 14:45:28 az systemd[1]: nixos-rebuild-switch-to-configuration.service: Consumed 1.147s CPU time, no IO, no IP traffic.

● session-16.scope - Session 16 of User deploy
     Loaded: loaded (/run/systemd/transient/session-16.scope; transient)
  Transient: yes
     Active: active (running) since Sun 2023-10-22 14:45:22 HKT; 26min ago
         IP: 0B in, 0B out
         IO: 228.0K read, 3.8M written
      Tasks: 5
     Memory: 704.0K
        CPU: 378ms
     CGroup: /user.slice/user-993.slice/session-16.scope
             ├─5305 "sshd: deploy [priv]"
             ├─5319 "sshd: deploy@notty"
             ├─5355 fish -c "sudo --preserve-env=NIXOS_INSTALL_BOOTLOADER -- systemd-run -E LOCALE_ARCHIVE --collect --no-ask-password --pty --quiet --same-dir --service-type=exec --unit=nixos-re>
             ├─5363 sudo --preserve-env=NIXOS_INSTALL_BOOTLOADER -- systemd-run -E LOCALE_ARCHIVE --collect --no-ask-password --pty --quiet --same-dir --service-type=exec --unit=nixos-rebuild-swi>
             └─5364 systemd-run -E LOCALE_ARCHIVE --collect --no-ask-password --pty --quiet --same-dir --service-type=exec --unit=nixos-rebuild-switch-to-configuration --wait /nix/store/hy54mnahn>

Oct 22 14:45:22 az systemd[1]: Started Session 16 of User deploy.
Oct 22 14:45:23 az sudo[5340]:   deploy : PWD=/var/empty ; USER=root ; COMMAND=/run/current-system/sw/bin/nix-env -p /nix/var/nix/profiles/system --set /nix/store/hy54mnahnssgf95wfk890gr6kgamnizq>
Oct 22 14:45:23 az sudo[5340]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=993)
Oct 22 14:45:23 az sudo[5340]: pam_unix(sudo:session): session closed for user root
Oct 22 14:45:24 az sudo[5351]:   deploy : PWD=/var/empty ; USER=root ; COMMAND=/run/current-system/sw/bin/systemd-run -E LOCALE_ARCHIVE --collect --no-ask-password --pty --quiet --same-dir --serv>
Oct 22 14:45:24 az sudo[5351]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=993)
Oct 22 14:45:24 az sudo[5351]: pam_unix(sudo:session): session closed for user root
Oct 22 14:45:24 az sudo[5363]:   deploy : PWD=/var/empty ; USER=root ; COMMAND=/run/current-system/sw/bin/systemd-run -E LOCALE_ARCHIVE --collect --no-ask-password --pty --quiet --same-dir --serv>
Oct 22 14:45:24 az sudo[5363]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=993)
```

### Notify maintainers

@thiagokokada 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.11 (Tapir), 23.11.20231021.fcb40e7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/store/xvwsw3qcgzw1xs4i9yypl9qipq08maig-source`
```

### PR DESCRIPTION
**Pull request by duament**
## Description of changes

Last attempt #262985 by @thiagokokada

~In https://github.com/NixOS/nixpkgs/issues/262686#issuecomment-1778309890, I noticed `nixos-rebuild` changed some tty settings, including `echo`. That could certainly cause the wierd error:~
```
ValueError: invalid literal for int() with base 10: 'echo ${PIPESTATUS[0]}'
```

~So I tried to add `stty -echo` to restore the echo setting and it worked.~

Edit: It has been fixed in systemd 255.

Fix #262686

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
The main issue that I see is that this is essentially an issue with `--pipe`, and will probably affect any test that uses `nixos-rebuild`.

**Comment by thiagokokada** [comment]
> > The main issue that I see is that this is essentially an issue with `--pipe`, and will probably affect any test that uses `nixos-rebuild`.
> 
> I think we have 2 ways to fix this:
> 1. Find the root cause that changes tty settings and fix it
> 2. Add the `stty -echo` command in the `nixos-rebuild` script or the test driver

I think we need to find the root cause. Adding a workaround to the test suite is bad because it can mask issues.

**Comment by duament** [comment]
It's a systemd bug. Opened an issue at https://github.com/systemd/systemd/issues/29714.

**Comment by duament** [comment]
Since systemd 255 has been in the master branch, it's now safe to remove the stty workaround.

@thiagokokada please review

**Review by thiagokokada — APPROVED** [review]

**Comment by thiagokokada** [comment]
CC @roberth.

**Comment by roberth** [comment]
CC @Enzime

**Comment by Enzime** [comment]
Probably a good idea to rebase this PR and run the NixOS tests

**Comment by duament** [comment]
> Probably a good idea to rebase this PR and run the NixOS tests

@Enzime I rebased it a couple of hours ago. And it passed all 4 nixos-rebuild tests.

**Comment by johnnywalker** [comment]
I've been using this change for while now with EC2 AMIs, and `nixos-rebuild` no longer hangs when executing `systemd`.

**Pull request merged**
