### PR TITLE
zulu{13-20}: init; zulu11: 11.62.17 -> 11.66.15; zulu8: 8.68.0.19 -> 8.72.0.17

### LINKED ISSUE #28977: Support for Zulu on AArch64
## Issue description
Now that NixOS supports AArch64 (IE on the Raspberry Pi 3) I'd like to use Zulu. However, the existing derivation only supports x86 based systems. 

### Steps to reproduce
`nix-env -i zulu` on a AArch64 bit system. 

## Technical details

I've managed to make the package install by changing and hardcoding some values in the existing derivation (https://github.com/NixOS/nixpkgs/blob/740d76371e6c1c76bae4801fc5b736a796c1ebbe/pkgs/development/compilers/zulu/default.nix#L80) however I'm not proficient enough in the Nix language to build a solution for all existing platforms. 

Zulu supports Arm 32bit with hard and soft float as well as aarch64 (see https://www.azul.com/downloads/zulu-embedded/) however I'm not sure how to change the existing derivation to detect the arch properly.

### PR DESCRIPTION
**Pull request by pokon548**
## Description of changes
This brings [zulu](https://www.azul.com/downloads/#zulu) 13, 15, 17, 19 and 20 to NixOS.
Older zulu{8,11} are also upgraded to latest version.
May also resolve #28977 as I add ```aarch64-linux``` to platforms too.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 250144` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>davmail</li>
    <li>zulu</li>
    <li>zulu11</li>
    <li>zulu13</li>
    <li>zulu15</li>
    <li>zulu17</li>
    <li>zulu19</li>
    <li>zulu8</li>
  </ul>
</details>

**Comment by edude03** [comment]
hmm, for what it's worth, I kicked the tires on this on a m2 MacBook and got

```
nix run 'github:pokon548/nixpkgs?ref=add-zulu#zulu'
error: hash mismatch in fixed-output derivation '/nix/store/9gg47izq16yw039jxyrl9d299rws7qsy-zulu20.32.11-ca-jdk20.0.2-macosx_aarch64.tar.gz.drv':
         specified: sha256-lJ5FabM1uQnqZgwtFfcRt/mHMz+4UwnvlifcdOmlbJs=
            got:    sha256-15uNZ6uMfSASV3QU2q2oA/jBk2PCHOfSjn1GY7/7qIY=
error: 1 dependencies of derivation '/nix/store/g1v4rplkgf6wn8ikf81wm522qqn50g61-zulu-20.32.11.drv' failed to build
```

```
❯ nix run 'github:pokon548/nixpkgs?ref=add-zulu#zulu19'
Usage: java [options] <mainclass> [args...] 
```

So zulu20 isn't working, 19 is, and I didn't try the rest

**Comment by edude03** [comment]
Actually, I tried the nixpkgs-review tool on this PR (never seen or used it before) and got the following: 

```
 nix run github:mic92/nixpkgs-review -- pr https://github.com/NixOS/nixpkgs/pull/250144
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/250144/head:refs/nixpkgs-review/1
remote: Enumerating objects: 2814, done.
remote: Counting objects: 100% (1970/1970), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 2814 (delta 1891), reused 1935 (delta 1883), pack-reused 844
Receiving objects: 100% (2814/2814), 3.06 MiB | 6.95 MiB/s, done.
Resolving deltas: 100% (2083/2083), completed with 926 local objects.
From https://github.com/NixOS/nixpkgs
   1a78023696b..b414f942e03  master     -> refs/nixpkgs-review/0
$ git worktree add /Users/edude03/.cache/nixpkgs-review/pr-250144-4/nixpkgs b414f942e0379771422fd6e203a558ab7151eac5
Preparing worktree (detached HEAD b414f942e03)
Updating files: 100% (37176/37176), done.
HEAD is now at b414f942e03 doc: link, instead of just mentioning, Nix manual (#255126)
$ git merge --no-commit --no-ff 843430e78e23096817de24abef22ef00cc4bd41a
Auto-merging pkgs/top-level/all-packages.nix
Automatic merge went well; stopped before committing as requested
$ nix build --nix-path nixpkgs=/Users/edude03/.cache/nixpkgs-review/pr-250144-4/nixpkgs nixpkgs-overlays=/tmp/tmpoc30r6mw --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation -f /Users/edude03/.cache/nixpkgs-review/pr-250144-4/build.nix
error: hash mismatch in fixed-output derivation '/nix/store/wx60pv3lmq8599wr0b0nw5917b7g2ryq-zulu11.66.15-ca-jdk11.0.20-macosx_aarch64.tar.gz.drv':
         specified: sha256-5bgcvYUiuCSibBCj9ZkN/2LBGtUcIlsmFAs7eloMv14=
            got:    sha256-djK8Kfikt9SSuT87x1p7YWMIlNuF0TZFYDWrKiTTiIU=
error: 1 dependencies of derivation '/nix/store/ixangxshm7bhghhq1qfrpxq5qkhgn16g-zulu-11.66.15.drv' failed to build
error: hash mismatch in fixed-output derivation '/nix/store/1bm10d9y4k05bvad0yz3z881nsvk9cn4-zulu20.32.11-ca-jdk20.0.2-macosx_aarch64.tar.gz.drv':
         specified: sha256-lJ5FabM1uQnqZgwtFfcRt/mHMz+4UwnvlifcdOmlbJs=
            got:    sha256-15uNZ6uMfSASV3QU2q2oA/jBk2PCHOfSjn1GY7/7qIY=
error: 1 dependencies of derivation '/nix/store/qs97346xsyxfw8craw87xpdsj4kgmsm8-zulu-20.32.11.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mgh6ph4vlglgz70syblqjv963k9s7yj8-davmail-6.1.0.drv' failed to build
error: 3 dependencies of derivation '/nix/store/gry6sg26nf6lr26r6pi8ykgg7i3lcv4r-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/250144

1 package marked as broken and skipped:
zulu17

3 packages failed to build:
davmail zulu zulu11

3 packages built:
zulu13 zulu15 zulu19

error: build log of '/nix/store/mgh6ph4vlglgz70syblqjv963k9s7yj8-davmail-6.1.0.drv^*' is not available
error: build log of '/nix/store/bms1snz2xq001am82rrp0r5dfw8i8dzs-davmail-6.1.0' is not available
error: build log of '/nix/store/qs97346xsyxfw8craw87xpdsj4kgmsm8-zulu-20.32.11.drv^*' is not available
error: build log of '/nix/store/9aj79rn6s894q8p80607ah064jkcd64p-zulu-20.32.11' is not available
error: build log of '/nix/store/ixangxshm7bhghhq1qfrpxq5qkhgn16g-zulu-11.66.15.drv^*' is not available
error: build log of '/nix/store/mdd9fr4wwpn788xhl218kghjj21wwzxj-zulu-11.66.15' is not available
error: cannot find flake 'flake:None' in the flake registries
$ /nix/store/gqf7zhkx1n6sijax727ycrm57ikrv3pc-nix-2.15.1/bin/nix-shell /Users/edude03/.cache/nixpkgs-review/pr-250144-4/shell.nix --nix-path nixpkgs=/Users/edude03/.cache/nixpkgs-review/pr-250144-4/nixpkgs nixpkgs-overlays=/tmp/tmpoc30r6mw
these 2 paths will be fetched (1.10 MiB download, 8.28 MiB unpacked):
  /nix/store/gqxzpx1x6c7hhjcvk2w44d1dd40nlhwk-bash-interactive-5.2-p15
  /nix/store/rba3cfa3aybqwmm044315rqjmddz5szx-readline-8.2p1
copying path '/nix/store/rba3cfa3aybqwmm044315rqjmddz5szx-readline-8.2p1' from 'https://cache.nixos.org'...
copying path '/nix/store/gqxzpx1x6c7hhjcvk2w44d1dd40nlhwk-bash-interactive-5.2-p15' from 'https://cache.nixos.org'....
```

**Comment by wegank** [comment]
Have unsolvable merge conflicts and is partially closed by #259825.

I'm not sure adding the EOL versions of Zulu is a good idea, but do it in a follow-up PR if you wish.

**Pull request closed without merging**
