### PR TITLE
liberasurecode: ignore strict prototypes on clang; fix darwin

### PR DESCRIPTION
**Pull request by ghost**
can not file an issue at https://github.com/openstack/liberasurecode
clang fails because global functions do not include the header which has the function prototypes, and some of the function prototypes which take no arguments are not written to clangs liking. nonetheless, ignore the warning for clang.

ZHF: #265948
https://hydra.nixos.org/build/241932295

Result of `nixpkgs-review` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>liberasurecode</li>
    <li>liberasurecode.dev</li>
    <li>liberasurecode.doc</li>
    <li>python310Packages.pyeclib</li>
    <li>python310Packages.pyeclib.dist</li>
    <li>python310Packages.swift</li>
    <li>python310Packages.swift.dist</li>
    <li>python311Packages.pyeclib</li>
    <li>python311Packages.pyeclib.dist</li>
    <li>python311Packages.swift</li>
    <li>python311Packages.swift.dist</li>
  </ul>
</details>

<hr>

no changes for x64 linux
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by a-n-n-a-l-e-e** [comment]
@ofborg eval

**Comment by a-n-n-a-l-e-e** [comment]
cc maintainers: @SuperSandro2000 (team openstack)

**Review by emilytrau — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> can not file an issue at [openstack/liberasurecode](https://github.com/openstack/liberasurecode)

This is just a mirror, you need to go through their gerrit.

Also instead of chasing warnings, we should just disable werror.

Please test #271335

**Comment by a-n-n-a-l-e-e** [comment]
> 
> Also instead of chasing warnings, we should just disable werror.

i agree, code should be written with warnings as errors and distributed with warnings as warnings -- however, in reviews committers have asked to leave warnings as errors and just disable specific warnings, so i have to oblige.

**Pull request merged**
