### PR TITLE
Cjdns module enhancments

### PR DESCRIPTION
**Pull request by joachifm**
###### Motivation for this change

Assorted cleanup and refactoring.
###### Things done

Ran the VM test for cjdns.

### CODE REVIEW

**Comment by groxxda** [comment]
What do we need bash for? 
The change from `if cfg != ""` to `if cfg != []` might overwrite the config for someone who explicitly set `cfg = ""`..
We could guard this case with an `assert cfg != ""` somewhere, but I'm not sure if it's needed.

**Comment by joachifm** [comment]
> What do we need bash for? 

?

> The change from if cfg != "" to if cfg != [] might overwrite the config for someone who explicitly set cfg = ""..

I assume you're referring to `confFile`? If so, `confFile = ""` should be a type error.

**Comment by groxxda** [comment]
> > What do we need bash for?
> ?
Maybe it's too late for me but I don't see the reason to write a bash script, that echoes stuff to a file and import the resulting file?

**Comment by joachifm** [comment]
I don't think there's a way to call an external program at Nix eval time, so we have to do it via a derivation.

**Comment by groxxda** [comment]
Okay, definitely too late for me :sleeping: . I'm still trying to figure out where `x.key` and `x.host` come from in 
```
           "echo $(${pkgs.cjdns}/bin/publictoip6 ${x.key}) ${x.host}")
```

**Comment by joachifm** [comment]
I'll grant that the new version packs quite a bit of stuff into a single operation :) It can be made somewhat clearer by floating parts of it out, I'll consider that if people find the new version too dense.

**Comment by ehmry** [comment]
One thing that needs to be done is support for user+password auth rather than just password auth. I can do this in the next day or so.

**Comment by tohl** [comment]
Does it fix /etc/hosts generation?  This did not work correctly last
time I tried, e.g. the same host was added several time instead of many
hosts added once each.

Would it also be possible to allow more module instances?

**Comment by joachifm** [comment]
> Does it fix /etc/hosts generation? This did not work correctly last time I tried, e.g. the same host was added several time instead of many hosts added once each.

The keys in the input attrset are unique by construction and we traverse it only once, so I'm fairly confident the output will contain at most one entry per peer. Please test if you can. I failed to realize there was an actual bug in the original.

**Pull request merged**
