### PR TITLE
eddie: init at 2.24.4

### LINKED ISSUE #73233: Packaging requests: eddie-ui
**Project description**
eddie-ui is the official client for AirVPN
It's written in C# with .Net/Mono framework and supports multiple architectures: x64, x86, armv7i
for reference, there's an arch pkgbuild here (there might be an easier way in nix): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=eddie-ui 

**Metadata**

* homepage URL: https://airvpn.org/
* source URL: https://github.com/AirVPN/Eddie
* license: gpl3+
* platforms: multiplatform

### PR DESCRIPTION
**Pull request by paveloom**
## Description of changes

https://eddie.website

Closes https://github.com/NixOS/nixpkgs/issues/73233.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by h4rldev** [comment]
+1

**Review by FliegendeWurst — APPROVED** [review]

**Comment by paveloom** [comment]
The `msbuild` package currently uses `dotnetCorePackages.sdk_6_0` that has been recently marked as insecure.

**Comment by FliegendeWurst** [comment]
Tracking issue for .NET 6/7: #326335

**Review by FliegendeWurst — COMMENTED** [review]
Package LGTM. ~~But I'd prefer to see the msbuild situation resolved (as in, a WIP PR for updating msbuild) before merging. No point in having this package if the build tool will be removed soon-ish.~~

**Comment by yuannan** [comment]
I'm having to add dot net runtime 6 to the EOL list in order to install this. Is this due to eddie?

The only difference in getting this error or not is from `eddie`. I've tried it with my flake.nix as well as nix-shell.

**Comment by FliegendeWurst** [comment]
Yes, it depends on msbuild, which depends on .NET 6, which is marked insecure.

**Pull request merged**
