### PR TITLE
python3Packages.certifi: 2020.12.5 -> 2021.05.30

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 2021.05.30

Enable tests.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
This needs to target staging. We should probably also backport it.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125632` at b53d3d26 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>84 packages marked as broken and skipped:</summary>
  <ul>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>deeptools</li>
    <li>gnuradio3_7</li>
    <li>gnuradio3_7Packages.ais</li>
    <li>gnuradio3_7Packages.gnuradio</li>
    <li>gnuradio3_7Packages.gsm</li>
    <li>gnuradio3_7Packages.limesdr</li>
    <li>gnuradio3_7Packages.nacl</li>
    <li>gnuradio3_7Packages.osmosdr</li>
    <li>gnuradio3_7Packages.rds</li>
    <li>grass</li>
    <li>impressive</li>
    <li>libvmi</li>
    <li>linuxPackages_hardkernel_4_14.dpdk</li>
    <li>linuxPackages_hardkernel_latest.dpdk</li>
    <li>linuxPackages_testing_bcachefs.dpdk</li>
    <li>natron</li>
    <li>ocropus</li>
    <li>odpdown</li>
    <li>opentsdb</li>
    <li>pig</li>
    <li>polymake</li>
    <li>processing</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.fipy</li>
    <li>python38Packages.foundationdb51</li>
    <li>python38Packages.foundationdb52</li>
    <li>python38Packages.foundationdb60</li>
    <li>python38Packages.foundationdb61</li>
    <li>python38Packages.ignite</li>
    <li>python38Packages.pygmt</li>
    <li>python38Packages.pymystem3</li>
    <li>python38Packages.python-csxcad</li>
    <li>python38Packages.python-openems</li>
    <li>python38Packages.pytorchWithCuda</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.tensorflowWithCuda</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
    <li>python39Packages.HTSeq</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.cnvkit</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.fipy</li>
    <li>python39Packages.foundationdb51</li>
    <li>python39Packages.foundationdb52</li>
    <li>python39Packages.foundationdb60</li>
    <li>python39Packages.foundationdb61</li>
    <li>python39Packages.ignite</li>
    <li>python39Packages.pygmt</li>
    <li>python39Packages.pymystem3</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
    <li>python39Packages.pytorchWithCuda</li>
    <li>python39Packages.streamz</li>
    <li>python39Packages.tensorflowWithCuda</li>
    <li>python39Packages.thinc</li>
    <li>qemu_xen</li>
    <li>qemu_xen-light</li>
    <li>qemu_xen_4_10</li>
    <li>qemu_xen_4_10-light</li>
    <li>qlandkartegt</li>
    <li>qubes-core-vchan-xen</li>
    <li>rainbowstream</li>
    <li>spark</li>
    <li>spring</li>
    <li>springLobby</li>
    <li>truvari</li>
    <li>yosys-bluespec</li>
  </ul>
</details>
<details>
  <summary>9729 packages skipped due to time constraints:</summary>
  <ul>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>R</li>
    <li>abcl</li>
    <li>acd-cli</li>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>aerc</li>
    <li>afew</li>
    <li>agda-pkg</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>13 packages built successfully:</summary>
  <ul>
    <li>python38Packages.certifi</li>
    <li>python38Packages.factory_boy</li>
    <li>python38Packages.flask</li>
    <li>python38Packages.flask_sqlalchemy</li>
    <li>python38Packages.requests</li>
    <li>python38Packages.responses</li>
    <li>sphinx (python38Packages.sphinx)</li>
    <li>python38Packages.werkzeug</li>
    <li>python39Packages.certifi</li>
    <li>python39Packages.flask</li>
    <li>python39Packages.requests</li>
    <li>python39Packages.sphinx</li>
    <li>python39Packages.werkzeug</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by lukegb** [comment]
@ofborg build python3Packages.certifi

**Comment by lukegb** [comment]
OK, I'm bored of watching aarch64-linux compile stdenv, :shipit:

**Pull request merged**
