### PR TITLE
python312: 3.12.5 -> 3.12.6; python311: 3.11.9 -> 3.11.10

### PR DESCRIPTION
**Pull request by mweinelt**
https://docs.python.org/release/3.12.6/whatsnew/changelog.html
https://docs.python.org/release/3.11.10/whatsnew/changelog.html

Closes: #340246

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by natsukium — APPROVED** [review]
tested on all four major platforms

**Comment by trofi** [comment]
Bisect claims that 9550eb8922a4ff28fcdc14b32bd28553d050dd8c `python312: 3.12.5 -> 3.12.6` broke `python3Packages.poetry-core` in `staging` as:

```
$ nix build --no-link github:NixOS/nixpkgs/staging#python3Packages.poetry-core -L
...
python3.12-poetry-core> tests/version/test_requirements.py ...........................F.         [100%]
python3.12-poetry-core> =================================== FAILURES ===================================
python3.12-poetry-core> _____________ test_invalid_requirement[name @ file:.-invalid URL] ______________
python3.12-poetry-core> string = 'name @ file:.', exception = 'invalid URL'
python3.12-poetry-core>     @pytest.mark.parametrize(
python3.12-poetry-core>         ["string", "exception"],
python3.12-poetry-core>         [
python3.12-poetry-core>             ("foo!", "Unexpected character at column 4\n\nfoo!\n   ^\n"),
python3.12-poetry-core>             ("foo (>=bar)", 'invalid version constraint ">=bar"'),
python3.12-poetry-core>             ("name @ file:.", "invalid URL"),
python3.12-poetry-core>             ("name @ file:/.", "invalid URL"),
python3.12-poetry-core>         ],
python3.12-poetry-core>     )
python3.12-poetry-core>     def test_invalid_requirement(string: str, exception: str) -> None:
python3.12-poetry-core> >       with pytest.raises(
python3.12-poetry-core>             InvalidRequirement,
python3.12-poetry-core>             match=re.escape(f"The requirement is invalid: {exception}"),
python3.12-poetry-core>         ):
python3.12-poetry-core> E       Failed: DID NOT RAISE <class 'poetry.core.version.requirements.InvalidRequirement'>
python3.12-poetry-core> tests/version/test_requirements.py:130: Failed
python3.12-poetry-core> =========================== short test summary info ============================
python3.12-poetry-core> FAILED tests/version/test_requirements.py::test_invalid_requirement[name @ file:.-invalid URL] - Failed: DID NOT RAISE <class 'poetry.core.version.requirements.InvalidRequi...
python3.12-poetry-core> ========== 1 failed, 2035 passed, 3 skipped, 11 deselected in 14.51s ===========
```

**Comment by mweinelt** [comment]
Reported upstream in https://github.com/python-poetry/poetry/issues/9678

**Comment by alyssais** [comment]
https://github.com/NixOS/nixpkgs/pull/341584

**Comment by alyssais** [comment]
Also twisted: https://github.com/twisted/twisted/pull/12314

**Comment by alyssais** [comment]
executing: https://github.com/alexmojaki/executing/issues/85

**Comment by alyssais** [comment]
Fix for twisted: https://github.com/NixOS/nixpkgs/pull/342331

**Comment by alyssais** [comment]
Fix for executing: https://github.com/NixOS/nixpkgs/pull/342333

**Comment by SuperSandro2000** [comment]
Thanks for the fixes!

**Pull request merged**
