### PR TITLE
R,rPackages: R 4.2.1 -> 4.2.2

### PR DESCRIPTION
**Pull request by jbedo**
###### Description of changes

Bump R and related packages to latest release.  Nixpkgs-review output:

```
1 package marked as broken and skipped:
ocamlPackages.ocaml-r

3 packages failed to build:
python310Packages.cnvkit sage sageWithDoc

18 packages built:
R diffoscope postgresql11Packages.plr postgresql12Packages.plr postgresql13Packages.plr postgresql14Packages.plr postgresql15Packages.plr python310Packages.rpy2 python39Packages.cnvkit python39Packages.rpy2 quarto rWrapper rstudio rstudio-server rstudioServerWrapper rstudioWrapper spark spark_3_1
```

The two failing builds are scikit-learn tests and sage tests. Scikit-learn has intolerable error for the lasso test:

```
_____________________________ test_graphical_lasso _____________________________
[gw3] linux -- Python 3.10.8 /nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/bin/python3.10
random_state = RandomState(MT19937) at 0x7FFFB771AF40

    def test_graphical_lasso(random_state=0):
        # Sample data from a sparse multivariate normal
        dim = 20
        n_samples = 100
        random_state = check_random_state(random_state)
        prec = make_sparse_spd_matrix(dim, alpha=0.95, random_state=random_state)
        cov = linalg.inv(prec)
        X = random_state.multivariate_normal(np.zeros(dim), cov, size=n_samples)
        emp_cov = empirical_covariance(X)
    
        for alpha in (0.0, 0.1, 0.25):
            covs = dict()
            icovs = dict()
            for method in ("cd", "lars"):
                cov_, icov_, costs = graphical_lasso(
                    emp_cov, return_costs=True, alpha=alpha, mode=method
                )
                covs[method] = cov_
                icovs[method] = icov_
                costs, dual_gap = np.array(costs).T
                # Check that the costs always decrease (doesn't hold if alpha == 0)
                if not alpha == 0:
                    assert_array_less(np.diff(costs), 0)
            # Check that the 2 approaches give similar results
>           assert_array_almost_equal(covs["cd"], covs["lars"], decimal=4)
E           AssertionError: 
E           Arrays are not almost equal to 4 decimals
E           
E           Mismatched elements: 2 / 400 (0.5%)
E           Max absolute difference: 0.0003378
E           Max relative difference: 0.1012732
E            x: array([[ 8.6952e-01,  2.2943e-02, -2.5220e-02,  1.2521e-02,  6.7809e-01,
E                   -1.3608e-02, -1.6757e-02,  1.3787e-01, -2.4110e-02,  5.2935e-02,
E                   -1.1025e-01,  2.3021e-02,  4.3972e-03,  1.1677e-03,  9.9450e-02,...
E            y: array([[ 8.6952e-01,  2.2943e-02, -2.5185e-02,  1.2546e-02,  6.7809e-01,
E                   -1.3580e-02, -1.6755e-02,  1.3787e-01, -2.4106e-02,  5.2943e-02,
E                   -1.1024e-01,  2.3016e-02,  4.3968e-03,  1.1677e-03,  9.9451e-02,...

```

The failing sage-test seems to be:

```
sage -t --long --random-seed=195837145062785932380370109676744555818 /nix/store/y5ckjzc159mkrm2cwbi278binldj2k5b-sage-src-9.7/src/sage/schemes/toric/sheaf/klyachko.py
**********************************************************************
File "/nix/store/y5ckjzc159mkrm2cwbi278binldj2k5b-sage-src-9.7/src/sage/schemes/toric/sheaf/klyachko.py", line 29, in sage.schemes.toric.sheaf.klyachko
Failed example:
    V.cohomology(dim=True, weight=(0,0,0,0))    # long time
Expected:
    (0, 0, 3, 0, 0)
Got:
    (0, 0, 0, 0, 0)
**********************************************************************
1 item had failures:
   1 of  13 in sage.schemes.toric.sheaf.klyachko
    [151 tests, 1 failure, 29.93 s]
```

Hydra link:

https://hydra.nixos.org/jobset/nixpkgs/r-updates

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by collares** [comment]
Sage test failure is a known random/intermittent issue. Feel free to ignore it. Thanks for testing it!

**Review by bcdarwin — COMMENTED** [review]
Lots of new failures on aarch64-linux, but they mostly seem to be related to `grpc` failing to build.

It looks like the cnvkit issue on Darwin is the only outstanding thing here?

**Comment by bcdarwin** [comment]
@GrahamcOfBorg build python310Packages.cnvkit

**Comment by bcdarwin** [comment]
@jbedo -- I don't know what platform you ran nixpkgs-review on but it now looks like python310Packages.cnvkit is building fine in Linux and has a broken dependency on Darwin, in which case this should be ready to merge?

**Review by bcdarwin — APPROVED** [review]

**Review by collares — APPROVED** [review]

**Pull request merged**
