### PR TITLE
nixosTests.k3s.{single-node,multi-node}: enable check-config for aarch64

### PR DESCRIPTION
**Pull request by superherointj**
nixosTests.k3s.{single-node,multi-node}: enable check-config for aarch64

CC @NixOS/k3s

### CODE REVIEW

**Comment by Mic92** [comment]
I assume you ran the test on aarch64?

**Comment by Mic92** [comment]
@ofborg test nixosTests.k3s.single-node

**Comment by Mic92** [comment]
@ofborg test nixosTests.k3s.multi-node

**Comment by superherointj** [comment]
> I assume you ran the test on aarch64?

I did run on Raspberry Pi, I'm waiting CI to re-run here.

**Comment by Mic92** [comment]
@ofborg test k3s.single-node

**Comment by Mic92** [comment]
@ofborg test k3s.multi-node

**Comment by euank** [comment]
LGTM if ofborg is happy!

The last ofborg run there failed with:

>        error: 'k3s_1_24' has been removed from nixpkgs as it has reached end of life

@ofborg test k3s.single-node.k3s_1_28 k3s.single-node.k3s_1_29 k3s.single-node.k3s_1_30 k3s.single-node.k3s_1_31 k3s.multi-node.k3s_1_28 k3s.multi-node.k3s_1_29 k3s.multi-node.k3s_1_30 k3s.multi-node.k3s_1_31

Hopefully there's a clean way we can make trying to run all the k3s version tests at once skip those error attributes, but that seems like a separate issue from this PR!

**Comment by euank** [comment]
Looks like it got past check-config on aarch64 just fine, nice!

It's failing with a different error:

```
agent # [ 1193.513817] k3s[793]: E0923 09:28:49.589402     793 kuberuntime_manager.go:1272] "Unhandled Error" err="container &Container{Name:test,Image:test.local/pause:local,Command:[socat TCP4-LISTEN:8000,fork EXEC:echo server],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{memory: {{20971520 0} {<nil>} 20Mi BinarySI},},Requests:ResourceList{memory: {{20971520 0} {<nil>} 20Mi BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-api-access-6bnql,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Never,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod test-nnnqf_default(eb0c063a-fd84-47d0-8cbf-f369882083fc): CreateContainerConfigError: services have not yet been read at least once, cannot construct envvars"
```

I think that means this PR's correct, and there's another issue or flake in there.
Let's see if it reproduces just running one of them..

@ofborg test k3s.single-node.k3s_1_28

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 343296` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by euank** [comment]
.. Okay, learned my lesson, I'll run em all as separate commands instead of one long command and make sure that passes. That one looked happy though, so I'm optimistic!

@ofborg test k3s.single-node.k3s_1_29
@ofborg test k3s.single-node.k3s_1_30
@ofborg test k3s.single-node.k3s_1_31
@ofborg test k3s.multi-node.k3s_1_28
@ofborg test k3s.multi-node.k3s_1_29
@ofborg test k3s.multi-node.k3s_1_30
@ofborg test k3s.multi-node.k3s_1_31

**Comment by euank** [comment]
Looks like for aarch64 linux we got passes for most of them, and then that "services have not yet been read at least once" error for multi-node.k3s_1_29 and multi-node.k3s_1_28.

Looks good to me!

**Review by euank — APPROVED** [review]

**Pull request merged**
