### PR TITLE
add packages: qutebrowser + dependency pypeg2

### PR DESCRIPTION
**Pull request by novahahn**

### CODE REVIEW

**Comment by jagajaga** [comment]
Thank you! But please solve conflicts and rebase against current master.

**Comment by kirelagin** [comment]
@ehahn Thanks for the expression! Are you actually using qutebrowser?
I altered your expression to get qutebrowser from git and when I run it, it segfaults after a few seconds. The same commit (The-Compiler/qutebrowser@5d490a4e22d544ff4daf13969ccf2780facdc34f) works fine on Gentoo.

**Comment by kirelagin** [comment]
Hm, that’s probably due to older PyQt. There are reports of qutebrowser crashing with PyQt < 5.4.2.

**Comment by ehahn** [comment]
On most websites it works fine for me, some crash it consistently. I'll look into this later today.

**Pull request merged**
