### PR TITLE
kubernetes: 1.13.5 -> 1.14.0

### PR DESCRIPTION
**Pull request by arianvp**
###### Motivation for this change
A new release was done.
 
I opened against `staging` because this requires `1.12.1` of golang

I have not yet ran the  nixos tests, as I am still rebuilding `kubernetes`
There might be some stuff that fails, 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by arianvp** [comment]
building the docs failed with the following cryptic error message:

```
!!! Error in ./hack/update-generated-docs.sh:36
  Error in ./hack/update-generated-docs.sh:36. 'make -C "${KUBE_ROOT}" WHAT="${BINS[*]}"' exited with status 2
Call stack:
  1: ./hack/update-generated-docs.sh:36 main(...)
Exiting with status 1

```

**Comment by arianvp** [comment]
Fixed the build.

**Comment by arianvp** [comment]
I have not yet been able to run the NixOS tests, because many of the dependencies it depends on are in `staging` and don't have a cached version yet. I don't have the compute power to compute `gnupg` and `openldap` from scratch.

**Comment by arianvp** [comment]
@GrahamcOfBorg test kubernetes.dns kubernetes.rbac

**Comment by flokli** [comment]
@GrahamcOfBorg test kubernetes.dns kubernetes.rbac

**Comment by arianvp** [comment]
I'm not sure why the aarch64 build failed. But we are also skipping tests in aarch64 . Note sure if that's on purpose

**Comment by arianvp** [comment]
Man pages don't seem to get generated.

**Comment by FRidh** [comment]
> I have not yet been able to run the NixOS tests

That's fine, we can see the results as soon as this is in `staging-next`.

**Comment by arianvp** [comment]
@GrahamcOfBorg build kubernetes

**Comment by arianvp** [comment]
The build suceeds now on `aarch64` as well and all tests pass.  I think this is ready for merge.

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
