### PR TITLE
qt59.qtwebkit: fix build on Darwin

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

Broken by #49768.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
Huh, I already fixed this.

**Comment by LnL7** [comment]
https://github.com/NixOS/nixpkgs/pull/49845

**Comment by alyssais** [comment]
… huh.

Maybe I wasn't up to date when it was broken for me, and then since I changed it in a different place, git just combined the two when I updated.

**Comment by alyssais** [comment]
Oh, bet I know what it is! My fix would have propagated the cf-private dependency (bad), and that would have fixed qtwebkit, which is what I use qtbase for.

So what actually needs to happen is qtwebkit needs to depend on cf-private as well. I'll change the PR to do that.

**Comment by LnL7** [comment]
Ah, I might have missed that. I tried to fix everything that's important to get master back in an ok state but looking into swift-corelibs is probably the proper solution.

**Comment by alyssais** [comment]
@LnL7 I just build this locally, and now it fails because it can't find `CFURLCreateFromFSRef`. It built fine with my previous commit. Any ideas?

**Comment by LnL7** [comment]
@GrahamcOfBorg build qt5.qtwebkit

**Comment by alyssais** [comment]
Oh, it'll need to be qt59.qtwebkit – it's the only Darwin-compatible version right now. See #48700.

**Comment by LnL7** [comment]
@GrahamcOfBorg build qt59.qtwebkit

**Comment by LnL7** [comment]
@alyssais Does this latest commit work for you? I had a successful build.

**Comment by alyssais** [comment]
Yep, this works for me.

**Comment by timokau** [comment]
Not sure if this is related, but qtwebkit currently fails for darwin: https://github.com/NixOS/nixpkgs/pull/52613/checks?check_run_id=43642188

**Comment by timokau** [comment]
Looks like that is already https://github.com/NixOS/nixpkgs/pull/51846

**Comment by veprbl** [comment]
@timokau 
The `name` attribute for our qtwebkit is a bit confusing. So `qt59.qtwebkit` does seem to build [1], but `qt511.qtwebkit` is used by pyqt5 and it is broken [2]. I expect that it will become harder and harder to maintain working `qtwebkit` in the future. The #51846 is a step towards phasing out QtWebKit from the python applications.

[1] https://hydra.nixos.org/job/nixpkgs/trunk/qt59.qtwebkit.x86_64-darwin
[2] https://hydra.nixos.org/job/nixpkgs/trunk/qt511.qtwebkit.x86_64-darwin

**Pull request merged**
