### PR TITLE
plex: 1.22.0.4163-d8c4875dd ->  1.22.1.4275-48e10484b

### PR DESCRIPTION
**Pull request by MayNiklas**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117569` at fbd50b91 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>plex</li>
    <li>plexRaw</li>
  </ul>
</details>

**Comment by MayNiklas** [comment]
Plex just released version 1.22.1.4271-b86a5e175.
If wished, I could easily add a commit with the new version to my pull request (maybe even force pushing?).

The checksums would be:
arm64: 0li26p4lqg1nigbkjap9p4khw8slhqc3ah5lpbb11arkvpcdwnzw
amd64: 1hvmh33fkhp5zmyrr9iwgs1qhgdsg834cnmmnjch1q4g6qmwl6zq

**Comment by MayNiklas** [comment]
Plex just released version 1.22.1.4275-48e10484b.
The checksums would be:
arm64: 08x5ay0nvsdc2n584bw0vdqxh33wn0mlwyqciwgvwq873jn39j3z
amd64: 1h5pkd7fzqlbvqv25cdppglw651yc3026hnyim5vy1s1s182paws

**Comment by badmutex** [comment]
@MayNiklas Plex does have a very fast release cycle 😅 

I would add and squash commits then update the PR title.

**Comment by MayNiklas** [comment]
@badmutex I just committed the newest version to my fork so it's included within this PR & changed the PR title.

Will you be able to squash it when merging? Or should I force push it over the first commit?

**Comment by badmutex** [comment]
@MayNiklas I don't actually have privileges to merge.
@SuperSandro2000 would you be able to take over that?

**Review by LnL7 — APPROVED** [review]

**Pull request merged**
