### PR TITLE
ch341eeprom: init at 0-unstable-2021-01-05

### PR DESCRIPTION
**Pull request by xokdvium**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by xokdvium** [comment]
Tested with compatible hardware and 24c08 eeprom. Write/read/erase function as expected

**Review by ghost — COMMENTED** [review]
looks good. verified maintainer info matches.
why are you disabling optimizations?
you can use `makeFlags` rather than patching the Makefile.

<details><summary>suggested changes</summary>

```diff
diff --git a/pkgs/by-name/ch/ch341eeprom/package.nix b/pkgs/by-name/ch/ch341eeprom/package.nix
index e5e1328aa32a..dd73169b9dac 100644
--- a/pkgs/by-name/ch/ch341eeprom/package.nix
+++ b/pkgs/by-name/ch/ch341eeprom/package.nix
@@ -17,13 +17,11 @@ stdenv.mkDerivation {
 
   buildInputs = [ libusb1 ];
 
-  dontConfigure = true;
-
-  postPatch = ''
-    substituteInPlace Makefile \
-      --replace-fail "CC = clang" "CC = ${stdenv.cc.targetPrefix}cc" \
-      --replace-fail "CFLAGS = -Wall -O2" "CFLAGS ?="
-  '';
+  makeFlags = [
+    "CC=${stdenv.cc.targetPrefix}cc"
+    # why is optimization disabled?
+    "CFLAGS="
+  ];
 
   installPhase = ''
     runHook preInstall

```
</details>

**Comment by xokdvium** [comment]
> why are you disabling optimizations?

This is by mistake. Removed `CFLAGS` patch. 
Switched to using `makeFlags` as suggested.

**Review by ghost — APPROVED** [review]
Looks good. ` dontConfigure = true;` isn't required as there is nothing to configure the step will get skipped anyway.

**Comment by xokdvium** [comment]
> dontConfigure = true; isn't required as there is nothing to configure the step will get skipped anyway.

Huh, fair enough. Though there are packages (e.g. `smallwm`) without autoconf that still set `dontConfigure = true`.

**Comment by a-n-n-a-l-e-e** [comment]
> Huh, fair enough. Though there are packages (e.g. `smallwm`) without autoconf that still set `dontConfigure = true`.

it is unnecessary there too.

**Comment by a-n-n-a-l-e-e** [comment]
i missed the license. it should be `gpl3Plus` not `gpl3` as there is the `or later` section at the end of the file.

**Pull request merged**
