### PR TITLE
systemd: remove unused null checks

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by flokli** [comment]
These are not unused, but help people composing their own (more minimal) systemd to not accidentally pass some dependencies as null where they're really required, no?

**Comment by SuperSandro2000** [comment]
If people want to disable features they can use the with* flags. All packages must exist because there is no ``? null`` and overwriting some packages to null is not supported and you are on your own.

**Comment by flokli** [comment]
> overwriting some packages to null is not supported and you are on your own.

Is this written down somewhere, like in a nixpkgs style guide? I see a ton of things in `all-packages.nix` setting packages to `null`, even entirely being configured by checking what's null (`rsyslog`).

**Comment by SuperSandro2000** [comment]
> Is this written down somewhere, like in a nixpkgs style guide?

I don't know maybe somewhere. It is in the process of being removed for a longer time since it can easily be missused by simple having a typo and if packages are removed/renamed it will never be noticed. It is only actually required for bootstrapping and some other special cases not for having optional features. 



> I see a ton of things in `all-packages.nix` setting packages to `null`, even entirely being configured by checking what's null (`rsyslog`).

There are actually not to many left https://search.nix.gsc.io/?q=%3D%20null&i=nope&files=pkgs%2Ftop-level%2Fall-packages.nix&excludeFiles=&repos=

and packages like rsyslog should be switched to boolean style inputs like systemd is already doing for all options.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Pull request merged**
