### PR TITLE
Update Heroic Games Launcher and dependencies

### PR DESCRIPTION
**Pull request by aidalgol**
## Description of changes
Update Heroic to 2.9.1, and its dependencies gogdl and legendary (@equirosa) to their latest stable versions.  Also added Nile for Heroic's Amazon Games support.

This version upstream moved to a non-free Electron fork for DRM support to go along with the new support for web applications.  This has been patched out to allow us to continue using mainline Electron from nixpkgs.

If anyone wants to take on packaging the [ECS fork](https://github.com/castlabs/electron-releases), then we can add an option to build the heroic package with and without DRM support (e.g. `heroic` and `heroic-unfree`).

## Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by equirosa** [comment]
Result of `nixpkgs-review pr 246288` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>gogdl</li>
    <li>gogdl.dist</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>legendary-gl</li>
    <li>legendary-gl.dist</li>
    <li>rare</li>
    <li>rare.dist</li>
  </ul>
</details>

**Review by equirosa — APPROVED** [review]
LGTM

**Review by Henry-Hiles — APPROVED** [review]
LGTM, looking forward to the update.

**Comment by K900** [comment]
Been running this for a bit with [a somewhat hacky patch to make Steam shortcuts work](https://gitlab.com/K900/nix/-/blob/master/hacks/heroic/non-steam-shortcuts.diff) and [a very hacky patch to disable Discord RPC](https://gitlab.com/K900/nix/-/blob/master/hacks/heroic/kill-discord-rpc.diff) (because it creates messy directories in $HOME for complicated reasons). I think we should definitely include the shortcuts patch and then this should be good to merge.

**Comment by aidalgol** [comment]
@K900 For the Discord RPC patch, why is just disabling the setting in Heroic insufficient?

For the Steam shortcuts patch, what is the problem that fixes?  I'm not familiar with that functionality, so I'm not sure what's going on there.

**Comment by K900** [comment]
The Steam shortcuts patch makes the Steam shortcuts point at the `heroic` wrapper as the executable instead of the Electron binary, which is 1) in the store and may disappear and 2) the wrong thing to run anyway.

The Discord RPC patch is an ugly workaround for xdg-mime freaking out when launched in steam-session. I'm not entirely sure why disabling it in Heroic doesn't seem to make it not trigger.

**Comment by K900** [comment]
(I'm not proposing to merge the Discord patch, btw, I just think the shortcuts one is good)

**Comment by aidalgol** [comment]
Patch to fix Steam shortcuts from @K900 applied.

**Comment by equirosa** [comment]
Result of `nixpkgs-review pr 246288` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>gogdl</li>
    <li>gogdl.dist</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>legendary-gl</li>
    <li>legendary-gl.dist</li>
    <li>nile</li>
    <li>nile.dist</li>
    <li>rare</li>
    <li>rare.dist</li>
  </ul>
</details>

**Review by equirosa — APPROVED** [review]

**Comment by Henry-Hiles** [comment]
> [](https://github.com/Mic92/nixpkgs-review)
> 10 packages
Wait why is rare being built? Isnt that just an alternative to heroic?

**Comment by K900** [comment]
Because `legendary`, which both `rare` and `heroic` depend on, also got updated.

**Pull request merged**
