### PR TITLE
impressive: 0.10.3 -> 0.10.5

### PR DESCRIPTION
**Pull request by k0ral**

### CODE REVIEW

**Comment by pSub** [comment]
Does impressive work for you? With the current version I get the following error
```
OSError: ('GL: cannot open shared object file: No such file or directory', 'GL', None)
```

**Comment by k0ral** [comment]
It doesn't work either, with a similar error:

    Oops! Cannot load necessary modules: ('Unable to load OpenGL library', 'libGL.so: cannot open shared object file: No such file or directory', 'libGL.so', 'libGL.so')

I figured it was due to my running a non-NixOS system, but it seems I was wrong.

**Comment by lethalman** [comment]
On non-nixos you should set up `/run/opengl-driver` properly.

**Comment by vcunat** [comment]
I assume you're non-nixos and missing the opengl-driver link(s), which is independent of this package/update. This seems to work fine for me.

**Pull request closed without merging**
