### PR TITLE
haskellPackages: fix `lsp_2_1_0_0` and `hls-plugin-api` on `haskell-updates`

### PR DESCRIPTION
**Pull request by peterbecich**
## Description of changes

https://github.com/NixOS/nixpkgs/issues/250091

Fix `hls-plugin-api` and `lsp_2_1_0_0`

Tested with
```
nix build .#haskellPackages.hls-plugin-api

nix build .#haskellPackages.lsp_2_1_0_0
```

Possibly also fixes `ghcide`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
Looks like you've edited a generated file.
I think it should be possible to generate this change by adding to `extra-packages` in `pkgs/development/haskell-modules/configuration-hackage2nix/main.yaml`.
Otherwise, you'd need to add overrides in one of the `configuration-*.nix` files.

**Comment by sternenseemann** [comment]
`lsp_2_1_0_0` is done in https://github.com/NixOS/nixpkgs/pull/249708/commits/dba9d4e33a2dd73d052aee9f71f494b086d43647; HLS is a bit more involved (fixing hls-plugin-api alone is not enough), I started work on it and will consult with the HLS nixpkgs maintainer @maralorn when he gets back.

**Comment by peterbecich** [comment]
@roberth , thanks.

After editing `configuration-hackage2nix/main.yaml`, `.../broken.yaml`, etc., what do I run to regenerate `hackage-packages.nix` from that?

**Comment by maralorn** [comment]
maintainers/scripts/haskell/regenerate-hackage-packages.sh

**Pull request closed without merging**
