### PR TITLE
Update Vagrant: 1.8.1 -> 1.8.4

### PR DESCRIPTION
**Pull request by langston-barrett**
###### Motivation for this change

update
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)

```
code/nixpkgs % ./result/bin/vagrant --version
Vagrant 1.8.3
```
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by siddharthist** [comment]
SHA256 checksums were lifted from [releases.hashicorp.com](https://releases.hashicorp.com/vagrant/1.8.3/vagrant_1.8.3_SHA256SUMS).

**Comment by aneeshusa** [comment]
Version 1.8.4 is available, can you please update to that since it's the current/latest version?

**Comment by siddharthist** [comment]
@aneeshusa I actually had trouble building that one, so I just went for this one instead :) maybe we can merge this and get that one in another PR? 

Sorry, I'm a bit of a newbie to Nix and I don't want to take on something I can't handle yet.

**Comment by grahamc** [comment]
I tested this PR and it works, but I think the fix for 1.8.4 is pretty simple. Perhaps you could do it?

1: I looked at the build output and saw:

```
post-installation fixup
chmod: cannot access '/nix/store/ywiw6qzdlnw8zryk1il8fhb9ya4fs4fv-vagrant-1.8.4/opt/vagrant/embedded/gems/gems/bundler-1.12.0/lib/bundler/templates/Executable': No such file or directory
```

that means it is in our build script: 

 - https://github.com/siddharthist/nixpkgs/blob/9b3c75f73d0b41a14b27f4951088e498bd8cba5e/pkgs/development/tools/vagrant/default.nix#L100
- https://github.com/siddharthist/nixpkgs/blob/9b3c75f73d0b41a14b27f4951088e498bd8cba5e/pkgs/development/tools/vagrant/default.nix#L105

2: I looked at the diff for the project: https://github.com/mitchellh/vagrant/compare/018cbc6550d8df061d69ebd12a43333594908e98...bedaeee and saw they specifically locked down bundler to 1.12.5

So, I think all you need to do is fix those two lines in our expression. Would you mind?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/16944#-:-KMp9452VJH_N71C00f9:-577673902)*

**Comment by siddharthist** [comment]
@grahamc You're exactly right :) thanks for the help! It's done.
```
code/nixpkgs > ./result/bin/vagrant --version         
Vagrant 1.8.4
```

**Comment by grahamc** [comment]
Built & tested the new commit. Looks good to merge, maybe even backport to 16.03

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/16944#-:-KMpWTEmWfqRh2_mWqvR:-1247178551)*

**Pull request merged**
