### PR TITLE
nextcloud: 20.0.12 -> 20.0.13, 21.0.4 -> 21.0.5, 22.1.1 -> 22.2.0

### PR DESCRIPTION
**Pull request by yayayayaka**
###### Motivation for this change
https://nextcloud.com/blog/fresh-updates-here-22-2-0-21-0-5-and-20-0-13/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux (all three ^^)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Thanks! Will take a look tomorrow! :)

**Review by bachp — APPROVED** [review]
22.2.0 tested and working

**Comment by Ma27** [comment]
The tests are failiny locally though. Going to look into this.

**Comment by Ma27** [comment]
The problem is that nextcloud isn't compatible with mariadb 10.6. There's a workaround though. I'll apply it (with an eval-warning for users) and push it to that branch. After that, the change should be good to go.

**Review by Ma27 — APPROVED** [review]
Works OK for me now, but I could use some more reviews here for my MySQL fix.

cc @aanderse @nlewo @bachp

**Comment by bachp** [comment]
@Ma27 I'm using postgres tough so I haven't tested them, but the look OK to me.

**Pull request merged**
