### PR TITLE
Update Haskell package set to LTS 16.1 (plus other fixes)

### PR DESCRIPTION
**Pull request by peti**
This PR is test-built by Hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. I'll fix up the remaining errors and merge it on Friday, 2020-06-12 [20:00 +02:00](http://www.thetimezoneconverter.com/?t=20:00&tz=Berlin). You can watch this live on Twitch at https://www.twitch.tv/peti343. In addition to the chat features offered by Twitch, there is also a voice conference at https://discord.gg/YTEa3XR that viewers can use to chat with me and with each other.

### CODE REVIEW

**Comment by peti** [comment]
We can't merge today, unfortunately, because there are too many build errors left to fix. `cabal-install` and `stack` seem to be broken and Hydra is in no shape to help us figure out why these builds fail since it has a backlog of 100,000 builds in the queue already. I'll either merge this PR off-stream in the next couple of days or we'll try again next Friday, depending on how complicated the missing fixes are.

**Comment by dbaynard** [comment]
I'm trying to build stack as part of ZuriHac

**Comment by dbaynard** [comment]
> I'm trying to build stack (as part of ZuriHac).

The `x509-validation` test suite hangs and the `tls` test suite fails. Should I disable them, or dig further?

I'm checking cabal-install, now, too.

**Comment by peti** [comment]
Next week, we'll merge https://github.com/NixOS/nixpkgs/pull/91474.

**Pull request merged**
