### PR TITLE
nix-melt: bump deps harder to fix rust 1.80 build

### PR DESCRIPTION
**Pull request by bryango**
## Description of changes

This one is a follow-up of #334556 as that actually didn't work... Sorry for the miss.

It turns out that in this case a simple `cargo update time` is not enough to fix the build; one also needs to ~~increment the semver spec in `Cargo.toml`, or~~ do a `cargo update time --recursive`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
> one also needs to increment the semver spec in `Cargo.toml`.

Do you understand why?  To me this seems to contradict the [Cargo documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio)

**Comment by bryango** [comment]
> > one also needs to increment the semver spec in `Cargo.toml`.
> 
> Do you understand why? To me this seems to contradict the [Cargo documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio)

I was also confused, but then I took a closer look at the documentation, and it does say that:

> An update is allowed if the new version number does not modify **the left-most non-zero number** in the major, minor, patch grouping.

This feels like bad design to me :rofl: In particular, we have:

https://github.com/NixOS/nixpkgs/blob/0766e419f46b793a1e952d6a50bfa9a40bf7a353/pkgs/tools/nix/nix-melt/0001-fix-build-for-rust-1.80.patch#L193-L205

Namely the `time` crate version before the update is, inconveniently, `0.3.20`, so a `cargo update` will only bring it up to `0.3.2*`, never to `>=0.3.35`.

**Comment by alyssais** [comment]
Surely that means the leftmost number is "20", and they'd have said "digit" if they truly meant for it to work that way?

**Comment by bryango** [comment]
> Surely that means the leftmost number is "20", and they'd have said "digit" if they truly meant for it to work that way?

Indeed, then I don't know what's happening... Now I am confused again haha...

**Comment by bryango** [comment]
I went down a rabbit hole and did some cargo archeology and I think I understand why: `cargo update` is executed "conservatively" since https://github.com/rust-lang/cargo/issues/613, https://github.com/rust-lang/cargo/pull/614. Basically, `cargo update time` will try its best to not bump the dependencies of `time`. This restricts the amount that `time` itself can be updated. In order to get the really latest version, one has to add a `--recursive` flag (which used to be called `--aggressive`):
```
cargo update time --recursive
```
Only by doing this can we ensure that `time` is updated to the latest semver compatible version. In our case, I can reproduce that:
- without `--recursive`, `time` only gets updated to `0.3.26`
- with `--recursive`, `time` gets updated to the latest `0.3.36` with a couple of other dependencies updated

**Comment by bryango** [comment]
@alyssais Shall this be merged as-is? `cargo update time --recursive` has roughly the same effects (see the [diff here](https://github.com/bryango/nix-melt/compare/bryango:nix-melt:cargo-update-recursive..cargo-update-explicit)). I actually prefer the explicit version bump in `Cargo.toml` since explicit is better than implicit :smile:

**Comment by alyssais** [comment]
Thanks for figuring it out!

I would prefer the `cargo update time --recursive`, because the version in the Cargo.toml is (at least theoretically) the minimum version required to build the crate.  0.3.35 is not the minimum version required to build the crate, as long as you have a compatible compiler.  This is also in the context of a patch file, where it's right next to an updated time dependency anyway, so it's still plenty explicit.

**Review by alyssais — APPROVED** [review]

**Comment by bryango** [comment]
Just updated `cargoHash`, waiting for ofborg!

**Review by cafkafk — APPROVED** [review]
LGTM, ty

**Review by xokdvium — APPROVED** [review]
Result of `nixpkgs-review pr 335060` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nix-melt</li>
  </ul>
</details>

**Pull request merged**
