### PR TITLE
Deadbeef 0.7.2 → 1.8.0

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
http://deadbeef.sourceforge.net/posts/deadbeef_1.8.0_is_out.html

Added native opus support

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
At the moment wildmidi plug-in is broken:

```
dlopen error: /nix/store/ad41yrj56xm27mzhzlkgmxks1z2g3y7s-deadbeef-with-plugins-1.8.0/lib/deadbeef/wildmidi.so: undefined symbol: X
trying /nix/store/ad41yrj56xm27mzhzlkgmxks1z2g3y7s-deadbeef-with-plugins-1.8.0/lib/deadbeef/wildmidi.fallback.so...
plugin wildmidi.so not found or failed to load

```

**Comment by bobvanderlinden** [comment]
This also failed in the previous version, but it never showed a dialog box for this:

```
dlopen error: /nix/store/nxp9nlqs9d0x79yx3s08n87z61jxdgsx-deadbeef-0.7.2/lib/deadbeef/wildmidi.so: undefined symbol: X
trying /nix/store/nxp9nlqs9d0x79yx3s08n87z61jxdgsx-deadbeef-0.7.2/lib/deadbeef/wildmidi.fallback.so...
plugin not found or failed to load
```

**Comment by jtojnar** [comment]
Replacing our wildmidi.so with wildmidi.so from [upstream](https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.0/deadbeef-static_1.8.0-1_x86_64.tar.bz2/download) fixed it.

So did the one built using the following command in `nix-shell -A deadbeef`:

```shell
unpackPhase
cd source
cd plugins/wildmidi
gcc -shared -Iinclude -DWILDMIDI_VERSION=\"0.2.2\" -DWILDMIDILIB_VERSION=\"0.2.2\" -DTIMIDITY_CFG=\"/etc/timidity.conf\" -fPIC wildmidiplug.c src/wildmidi_lib.c include/wildmidi_lib.h -o wildmidi.so -lm
```

If we build deadbeef with debugging info using `nix-build -E 'with import <nixpkgs> {}; enableDebugging deadbeef'` where the symbol comes from:

```ShellSession
$ nm -A -D -l result/lib/deadbeef/wildmidi.so
result/lib/deadbeef/wildmidi.so:0000000000018080 B X	/build/source/plugins/wildmidi/src/wildmidi_lib.c:399
```

Apparently, it is from this global variable:

https://github.com/DeaDBeeF-Player/deadbeef/blob/7ac83fb204fc3c8a35486ef8f9550cd98cec674e/plugins/wildmidi/src/wildmidi_lib.c#L399

But its name is `b`, not `X`.

I tried `hardeningDisable = ["all"];` but that did not help. What else could be renaming the symbol?

**Comment by bobvanderlinden** [comment]
The `installPhase` seemed to be messing things up. Using `dontPatchELF = true;` resolves the issue for me. With that the warning did not show up. Not sure what consequences this has for the other elf-files.

**Comment by bobvanderlinden** [comment]
Confirmed to be working with the patch. :+1: Thank you!

**Comment by jtojnar** [comment]
I can reproduce it with `nix run -f . patchelfUnstable -c patchelf --shrink-rpath wildmidi.so`. Will open an issue with patchelf.

**Pull request merged**
