### PR TITLE
python3Packages.python-engineio: build on macOS

### PR DESCRIPTION
**Pull request by misuzu**
###### Motivation for this change
It builds just fine on macOS.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by misuzu** [comment]
Also tested building `appdaemon` on macOS, only one test is failing with `OSError: AF_UNIX path too long`, but that's because of very long path to `tmp` directory, for example:
`path = '/private/var/folders/y1/9_wlrg890x1g723s7mgn73wr0000gn/T/nix-build-python3.7-aiohttp-3.6.2.drv-0/tmp1a3nap4t/tmp.sock'`.

**Comment by Mic92** [comment]
> Also tested building `appdaemon` on macOS, only one test is failing with `OSError: AF_UNIX path too long`, but that's because of [very long path to `tmp` directory](https://github.com/broadinstitute/cromwell/issues/3647), for example:
> `path = '/private/var/folders/y1/9_wlrg890x1g723s7mgn73wr0000gn/T/nix-build-python3.7-aiohttp-3.6.2.drv-0/tmp1a3nap4t/tmp.sock'`. Not sure why it's using different version of `aiohttp`.
> 
> Building `python37Packages.aiohttp` with `--check` is also failing on my machine, so this is probably local issue.

Can you either disable or fix new dependencies that are now failing because of enabling this?

**Comment by misuzu** [comment]
@GrahamcOfBorg build appdaemon

**Comment by misuzu** [comment]
> Can you either disable or fix new dependencies that are now failing because of enabling this?

`appdaemon` is building on multi-user nix.

**Comment by misuzu** [comment]
`gdbgui` build should be working too.

@GrahamcOfBorg build gdbgui

**Comment by Mic92** [comment]
Is your list complete?

@GrahamcOfBorg build gdbgui appdaemon

**Comment by misuzu** [comment]
> Is your list complete?

According to grep - it is :D

**Comment by Mic92** [comment]
@misuzu nix-review is often the better tool to test all rebuilds.

**Pull request merged**
