### PR TITLE
rimshot: init at 1.0 (unversioned)

### PR DESCRIPTION
**Pull request by leenaars**
Music game to create any kind of drumbeats

### CODE REVIEW

**Comment by leenaars** [comment]
The CI failure seems unrelated to the commit - it works on multiple systems for me.

**Comment by joachifm** [comment]
The desktop item and meta information appears to refer to orthorobot, is that intentional? Looks ok to me, otherwise.

**Comment by leenaars** [comment]
Hi @joachifm, not intentional. Is fixed.

**Comment by joachifm** [comment]
Please add a version.

**Comment by joachifm** [comment]
Could you update the commit subject? Otherwise this looks good to go.

**Comment by leenaars** [comment]
@joachimf: like so?

**Comment by joachifm** [comment]
No: change the subject of the commit itself (via `git commit --amend`) and force-push it. The desired format is `rimshot: init at 1.0`. I realize that this is nitpicky, but it's the policy ...

**Comment by leenaars** [comment]
@joachifm: done and apologies for the delay.

**Comment by joachifm** [comment]
No need to apologize. Thanks!

**Pull request merged**
