### PR TITLE
git: darwin: disable hanging test completion

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

hydra hasn't caught up with the latest package versions. Upon doing a review, trying to build git 2.33 on my x86_64-darwin machine, the test `t9902-completion` hangs forever. I tried to rebuild 4 times, just to be sure, but it seems that test is faulty.
 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by happysalada** [comment]
Ok, I have two failures coming from 2 different tests
```
    #===(   18623;1208  8/?  224/?  2/? )= =fatal: Not a valid object name refs/tags/signed-empty
    #===(   22665;1651  9/?  1/?  0/?  0/? )= =/private/tmp/nix-build-git-2.33.0.drv-2/git-2.33.0/t/../contrib/completion/git-completion.bash: line 405: compgen: command not found
```

The second error might be because the resolution of the shell is `/sh` instead of `/bash` not sure.

even after disabling those tests though, I still have the build hang for no discernible reason. I have to say I'm a littlle puzzled by this one. I've added in the commit disabling the 2 failures.

**Comment by happysalada** [comment]
When it hangs, the nix-daemon stays stuck on it. Even if I cancel the build and try to build again, it is stuck at waiting for `lock on ...`. I have to restart the machine completely.

**Comment by r-burns** [comment]
Hmm, I was able to build git on master. Is this flaky for you, or is it system-specific? Either way the change seems reasonable.

> Does the completion work in an interactive shell? If not this needs fixing, if it is just the test I think this should be fine.

Agreed, but if hunting down the underlying cause is too time consuming I'd be okay with merging this as an incremental improvement. Better to have a semi-functional git with broken completions than be unable to build it at all.

**Comment by happysalada** [comment]
I agree it's better to merge an incremental improvement. The build still hangs after disabling those tests.
I'm giving it one last try by enabling verbose logs, just to see if something else comes up. If nothing else comes up, I'll just merge this.

**Comment by happysalada** [comment]
ok, the build hanged with -vvv, so just merging this for now until I figure out how to debug further.

**Pull request merged**
