### PR TITLE
libdvdread: 5.0.3 -> 6.0.0

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update generated by https://github.com/ryantm/nix-update tools. These checks were done:

- built on NixOS
- Warning: no binary found that responded to help or version flags. (This warning appears even if the package isn't expected to have binaries.)
- found 6.0.0 with grep in /nix/store/dr0ps08716fhniggawzg9f9s7d74r8v7-libdvdread-6.0.0
- directory tree listing: https://gist.github.com/63bc02c878936a5428bbd234fd6c26c8

cc @wmertens for review

### CODE REVIEW

**Comment by wmertens** [comment]
Thanks!

This changes the API surface a little (https://code.videolan.org/videolan/libdvdread/blob/master/NEWS) and so it might cause dependent programs to fail to build. 

I'll figure out how to get ofBorg to test that…

**Comment by wmertens** [comment]
@grahamcofborg build transcode gstreamer

**Comment by wmertens** [comment]
Hmm, @ryantm would it be possible to merge this PR with #37661? They are a unit and I prefer it when a PR can stand on its own.

So just add the change from one to the other and close the one PR

**Comment by wmertens** [comment]
Ah I now see I'm talking to lots of bots :) I'll do the combining.

**Comment by ryantm** [comment]
Well, I do see your messages, but I appreciate you taking care of it, because I'm trying to make the overall updater better. I saw your [issue about combining PRs ](https://github.com/ryantm/nix-update/issues/29) too .

**Comment by wmertens** [comment]
Well, this is quite a large set of indirect changes.

@grahamc can I ask ofborg to build all the dependents? Or should I just merge and hope for the best :)

(so I would ask `build alarm-clock-applet anki audio-recorder banshee baresip beets bombono bomi brasero brasero-original byzanz cantata clementine cutegram devede dvd-slideshow dvdauthor dvdbackup dvdstyler empathy eolie epiphany frostwire gajim gmtk gnome-mpv gnome3.cheese gnome3.empathy gnome3.epiphany gnome3.gnome-contacts gnome3.gnome-control-center gnome3.gnome-disk-utility gnome3.gnome_control_center gnome3.gpaste gnome3.rhythmbox gnome3.totem gnome_mplayer gradio gst-plugins-bad gst-plugins-ugly gst_all_1.gst-plugins-ugly handbrake k3b k9copy kdeApplications.k3b kdeApplications.kdenlive kdenlive kmplayer kodiPlugins.steam-launcher libdvdnav libdvdread libsForQt5.phonon-backend-gstreamer libsForQt5.phonon-backend-vlc libsForQt5.vlc libsForQt510.phonon-backend-gstreamer libsForQt510.phonon-backend-vlc libsForQt510.vlc linux-steam-integration lsdvd lxdvdrip megaglest minitube mkcast mopidy-iris mopidy-local-images mopidy-local-sqlite mopidy-mopify mopidy-musicbox-webclient mopidy-soundcloud mopidy-spotify-tunigo mopidy-youtube mpc-qt mplayer mpv obs-studio ogmtools phonon-backend-gstreamer phonon-backend-vlc pipelight pithos pitivi python27Packages.kaa-metadata python27Packages.mpv python36Packages.mpv qstopmotion quodlibet quodlibet-full qutebrowser radiotray-ng rhythmbox sayonara sound-juicer steam steam-run steam-run-native tomahawk transcode transcribe translate-shell tribler vlc vlc_npapi vlc_qt5 vobcopy wineStaging xbmcPlugins.steam-launcher xfce.parole xfce4-12.parole`)

**Comment by grahamc** [comment]
It very likely can't build all of that within the time limit. I'd recommend picking a few and running just those :)

**Comment by wmertens** [comment]
@GrahamcOfBorg build handbrake dvdbackup gnome_mplayer

**Pull request merged**
