### PR TITLE
[22.11] jetbrains-jdk: add JCEF support

### PR DESCRIPTION
**Pull request by l0b0**
###### Description of changes

Backport of #196738, with [@GenericNerdyUsername's patch](https://github.com/NixOS/nixpkgs/pull/196738#issuecomment-1383271759). Anyone know how to wire this into IDEA to test it properly on 22.11?

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by l0b0** [comment]
@niknetniko This would be really useful to have.

**Comment by niknetniko** [comment]
> @niknetniko This would be really useful to have.

I'm not entirely sure why I was pinged here, as I had no part in creating the original patch, and I am not a maintainer for Intellij, just a user. Perhaps you'll have better luck in finding reviewers/someone who can merge by posting in https://discourse.nixos.org/t/prs-ready-for-review/3032?

Anyway, I tried reviewing locally: Goland could not be built, but I am unsure if this was the case already or not (I don't use 22.11 myself). The last log lines were:


```
/nix/store/zp8vq02cd40x1r1c7r69hizpb7m8rlzz-goland-2022.2.4/goland/plugins/remote-dev-server/bin/launcher.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/96ky1zdkpq871h2d>
/nix/store/zp8vq02cd40x1r1c7r69hizpb7m8rlzz-goland-2022.2.4/goland/bin/remote-dev-server.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/96ky1zdkpq871h2dlk198fz0zvklr1dr->
...
/nix/store/zp8vq02cd40x1r1c7r69hizpb7m8rlzz-goland-2022.2.4/goland/bin/format.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/96ky1zdkpq871h2dlk198fz0zvklr1dr-bash-5.1-p1>
/nix/store/zp8vq02cd40x1r1c7r69hizpb7m8rlzz-goland-2022.2.4/goland/bin/inspect.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/96ky1zdkpq871h2dlk198fz0zvklr1dr-bash-5.1-p>
checking for references to /build/ in /nix/store/zp8vq02cd40x1r1c7r69hizpb7m8rlzz-goland-2022.2.4...
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
patchelf: getting info about '/nix/store/zp8vq02cd40x1r1c7r69hizpb7m8rlzz-goland-2022.2.4/goland/plugins/go-plugin/lib/dlv/linux/dlv': No such file or directory
```

**Comment by l0b0** [comment]
> I'm not entirely sure why I was pinged here, as I had no part in creating the original patch, and I am not a maintainer for Intellij, just a user.

I pinged you because you were the reviewer of the original PR.

> Perhaps you'll have better luck in finding reviewers/someone who can merge by posting in https://discourse.nixos.org/t/prs-ready-for-review/3032?

Thanks for the tip! Posted there.

**Comment by l0b0** [comment]
This is redundant, as 23.05 is out and has this change.

**Pull request closed without merging**
