### PR TITLE
home-assistant: fix zha in home-assistant

### PR DESCRIPTION
**Pull request by mvnetbiz**
###### Motivation for this change
I would like to move my home-assistant onto NixOS
Basing off of #88715

###### Things done
Updated versions, fixed dependencies, and enabled the tests.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mvnetbiz** [comment]
Zigpy has settled on the pypi project "zigpy" so no renaming is needed.
https://github.com/zigpy/zigpy/pull/363
https://github.com/zigpy/zigpy/issues/351

**Comment by mvnetbiz** [comment]
I ran this basic home-assistant configuration in a VM, with the "Nortek GoControl HUSBZB-1" USB adapter, configured the ZHA integration sucessfully.
```nix
{
  users.users.root.initialPassword = "homeroot";
  users.users.hass.extraGroups = [ "dialout" ];
  networking.firewall.enable = false;

  services.home-assistant = {
    enable = true;
    config = {
      homeassistant = {
        name = "NixOS";
        time_zone = "America/New_York";
      };
      frontend = { };
      http = {
        server_host = "0.0.0.0";
        server_port = 8123;
      };
      history = { };
      logbook = { };
      map = { };
      sensor = [
        {
          platform = "yr";
          name = "Weather";
        }
      ];
      tts = [ { platform = "google_translate"; } ];
      zha = {
        database_path = "/var/lib/hass/zigbee.db";
        enable_quirks = false;
      };
      logger = {
        default = "info";
        logs = {
          "homeassistant.core" = "debug";
          "homeassistant.components.zha" = "debug";
          "bellows.zigbee.application" = "debug";
          "bellows.ezsp" = "debug";
          "zigpy" = "debug";
          "zigpy_cc" = "debug";
          "zigpy_deconz.zigbee.application" = "debug";
          "zigpy_deconz.api" = "debug";
          "zigpy_xbee.zigbee.application" = "debug";
          "zigpy_xbee.api" = "debug";
          "zigpy_zigate" = "debug";
          "zhaquirks" = "debug";
        };
      };
    };
  };
}
```

**Comment by mvnetbiz** [comment]
Is this okay to squash into 1 commit, or does this need cleanup?

**Review by etu — APPROVED** [review]
My ZHA modules seems to load fine now, I don't have things hooked up to my ZHA network since... it was... broken. But at least the module loads which is great :-)

**Comment by etu** [comment]
And now I have it set up with my ZigBee devices as well, it works! Thanks :)

**Pull request merged**
