### PR TITLE
dmd: 2.083.1 -> 2.084.0, dub: 1.12.1 -> 1.13.0, dtools: 2.083.1 -> 2.084.0, Literate: 2018-12-23 -> 2019-01-08

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

Version updates

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ThomasMader** [comment]
@GrahamcOfBorg build dmd

**Comment by veprbl** [comment]
@GrahamcOfBorg build dmd

**Comment by ThomasMader** [comment]
@zyedidia Literate has compile errors with dmd 2.084.0 could you please fix them?

**Comment by zyedidia** [comment]
Should be fixed now. Let me know if there are more problems.

**Comment by ThomasMader** [comment]
@zyedidia Thank you for the quick fix. No problems anymore.

@veprbl I updated the Literate package and also dub and dtools as they are connected to dmd. Everything should be good now.

@GrahamcOfBorg build dub dtools Literate

**Comment by veprbl** [comment]
@GrahamcOfBorg build dub dtools Literate

**Review by veprbl — APPROVED** [review]

**Pull request merged**
