### PR TITLE
maintainers: remove one year inactive maintainer kiwi

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

fyi @Kiwi (I don't expect an answer though)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
> * all of them, but only when you accidentally notice

this one. I just checked bitwarden-desktop regarding an electron update and noticed that the existing updates where all done by one of the maintainers and then I checked the profile and didn't notice any activity in 2024 or 2023, so.. I guess that person is inactive for long enough to be removed.

> Also how do you define inactivity?

If you don't have any github activity in over a year, you are definitely inactive.

**Comment by eclairevoyant** [comment]
> Is there an official written process somewhere

no, at most there's an in-progress rfc

**Comment by SuperSandro2000** [comment]
> it's a sensitive issue as the one year threshold and what consists in "activity" are debatable.

> or he could have moved to another forge, contributed to github private repositories and chose to hide those and so on.

True but nixpkgs activity cannot be and there is not much value in keeping inactive maintainers as that just gives a false hope that packages are maintainted and PRs for a package get reviewed. See the last 10+ bitwarden-desktop updates and the truly the maintainers are two other people.

> I hope you also emailed him as github pings could be filtered.

Isn't that just another argument to remove inactive and unresponsive accounts?

> Another question is how long do we wait for an answer before a merge?

Personally I don't think we need to wait that long.

**Comment by sternenseemann** [comment]
IMO it doesn't make sense to do this without an established policy. Also, having a stale maintainer entry is strictly more useful than having none at all.

**Comment by eclairevoyant** [comment]
> [committers] would generally (I think) want to wait for review from a maintainer if there is one

Realistically there is no onboarding for committers, and even most _contributors_ are aware that maintainers aren't necessarily active despite being listed, so I wouldn't generalise along these lines for committers.

But I agree that it'd cause confusion for _end users_. Maintainership should simply be an accurate reflection of the state of care for the package, not some kind of exclusive ownership - former maintainers are welcome to contribute without being maintainer, or come back as maintainer, should they choose so in the future.

Besides, maintainership is fluid, so as long as maintainers are notified in such removal PRs after extended inactivity, and don't respond for (say) a week after the tag, I don't see a major issue personally.

> Certainly though having a formal process would be best.

which is pending the rfc

**Comment by SuperSandro2000** [comment]
Since we have done similar things in the past already, I don't see the necessity of waiting for the RFC which will just delay the unavoidable.

**Comment by 7c6f434c** [comment]
Speaking of documented formal procedures:

https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md#how-to-lose-maintainer-status

**Comment by doronbehar** [comment]
> Speaking of documented formal procedures:
> 
> [`master`/maintainers/README.md#how-to-lose-maintainer-status](https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md?rgh-link-date=2024-06-14T13%3A48%3A01Z#how-to-lose-maintainer-status)

Linking the PR that added that text for reference (from `git blame`):

https://github.com/NixOS/nixpkgs/pull/250344

**Pull request merged**
