### PR TITLE
matrix-synapse-unwrapped: 1.108.0 -> 1.109.0

### PR DESCRIPTION
**Pull request by sumnerevans**
## Description of changes

https://github.com/element-hq/synapse/releases/tag/v1.109.0

Signed-off-by: Sumner Evans <sumner.evans@automattic.com>

## Things done

Running on my server and working fine.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by teutat3s — APPROVED** [review]

**Review by superherointj — APPROVED** [review]

**Comment by superherointj** [comment]
> for us this update broke nheko, schildichat, fluffychat, element-web (partially), and synapse itself (partially).

What do you think should be done?

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 320824` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>matrix-synapse-plugins.matrix-synapse-ldap3</li>
    <li>matrix-synapse-plugins.matrix-synapse-ldap3.dist</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam.dist</li>
    <li>matrix-synapse-plugins.matrix-synapse-s3-storage-provider</li>
    <li>matrix-synapse-plugins.matrix-synapse-s3-storage-provider.dist</li>
    <li>matrix-synapse-plugins.matrix-synapse-shared-secret-auth</li>
    <li>matrix-synapse-plugins.matrix-synapse-shared-secret-auth.dist</li>
    <li>matrix-synapse-unwrapped</li>
    <li>matrix-synapse-unwrapped.dist</li>
  </ul>
</details>

**Comment by superherointj** [comment]
> for us this update broke nheko, schildichat, fluffychat, element-web (partially), and synapse itself (partially).

Is testing missing? `nixpkgs-review` didn't show any breakage.

**Comment by NickCao** [comment]
> for us this update broke nheko, schildichat, fluffychat, element-web (partially), and synapse itself (partially).

Would you elaborate?

**Comment by Ma27** [comment]
> nixpkgs-review didn't show any breakage

Of course not, it's not the build that's breaking, synapse isn't even in the closure of the clients :upside_down_face: 

I upgraded last weekend and had the same issue, incidentally it resolved itself within minutes. I'm using synapse, but with a heavy worker setup.

The most important symptom was having a lot of `synapse.handlers.sync: [GET-38885] Timed out waiting for worker to catch up. Returning empty response` in the logs and clients being unable to receive messages.

We should probably stop rushing merges. I didn't have the time & energy to investigate on my regular systme updates, but if we give people (myself included) more time to actually test this, we may catch things like that before they hit stable.
That said, I don't know how fast the merge was this time, but synapse occasionally publishes a .1 resolving ugly regressions after the .0 release.

**Comment by NickCao** [comment]
Adding a data point: not seeing issue with my monolith deployment, could be a worker only thing (which is not covered by nixos tests?)

**Comment by superherointj** [comment]
> > nixpkgs-review didn't show any breakage
> 
> Of course not, it's not the build that's breaking, synapse isn't even in the closure of the clients 🙃

A test is missing then.

> We should probably stop rushing merges. I didn't have the time & energy to investigate on my regular systme updates, but if we give people (myself included) more time to actually test this, we may catch things like that before they hit stable. That said, I don't know how fast the merge was this time, but synapse occasionally publishes a .1 resolving ugly regressions after the .0 release.

No worry. I won't be merging much forward. Dealing with regressions is such a pain.

**Comment by Ma27** [comment]
> Adding a data point: not seeing issue with my monolith deployment, could be a worker only thing (which is not covered by nixos tests?)

I'm pretty sure that this is the case, I wouldn't expect a bump to be merged if the default way of deploying it is also busted.
That said, the nixos tests are just smoke tests (including the worker tests). I have this on my todo list, but time :shrug: 

> A test is missing then.

While I agree that the testing situation is sparse here I must ask, what do you expect? Synapse is a big piece of software and testing for all possible features? There's a reason why it makes sense to give maintainers and/or power-users the opportunity to run updates for a few days to see if they catch something.

I surely hope you don't merge any random package just because the button went green though.

**Comment by superherointj** [comment]
> I surely hope you don't merge any random package just because the button went green though.

Indeed.

**Comment by sumnerevans** [comment]
I have workers and always verify that my homeserver is working either before submitting the PR or before setting it to "ready for review". It appears that people are reporting the issue in upstream Synapse (https://github.com/element-hq/synapse/issues/17274) but there does not appear to be a resolution yet.

**Comment by sumnerevans** [comment]
It appears that Synapse v1.110.0 might fix the problem: https://github.com/element-hq/synapse/blob/release-v1.110/CHANGES.md#bugfixes

**Pull request merged**
