### PR TITLE
python3Packages.google_api_core: 0.15.0 -> 1.16.0

### PR DESCRIPTION
**Pull request by ruuda**
###### Motivation for this change

A new version is available upstream.

`google-api-core` version 1.16.0 requires at least Python 3.5, there is no point in keeping a Python 3.2 check around here.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`) (there are none)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

CC @vanschelven

### CODE REVIEW

**Comment by ruuda** [comment]
I also have a commit to update `python3Packages.google_cloud_core`, which depends on this PR. Should I open a separte PR for it, or add it to this PR?

**Comment by jonringer** [comment]
you can add it to this commit

unfortunately the python google packages are pretty broken (at least on python2) ATM, creating a lot of noise when reviewing

**Comment by ruuda** [comment]
> unfortunately the python google packages are pretty broken (at least on python2) ATM, creating a lot of noise when reviewing

Yeah, the reason I opened these is because I need the `google_cloud_storage` package, which is broken on Python 3.7. My first try was to update its dependencies to the latest versions. That did not help, but I thought, I’d open PRs for the bumps anyway.

#77813 and #77819 are related. Should I maybe put them in this pull request too? That would also cause less rebuilds, right?

**Comment by jonringer** [comment]
sounds reasonable.

Still, the google sdk namespace is a hot mess right now :(

**Review by jonringer — COMMENTED** [review]
please squash the first two commits

**Comment by ruuda** [comment]
> please squash the first two commits

Done.

**Review by jonringer — COMMENTED** [review]
would still be nice to fix the google namespace, it's horribly broken:
```
[120 built (32 failed), 240 copied (808.6 MiB), 204.2 MiB DL]
error: build of '/nix/store/5kc34hp8iv6gp52qlnp0bhqrfwv12mq3-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/77814
35 package failed to build:
blink dvc-with-remotes fluidasserts python27Packages.google-auth-oauthlib python27Packages.kubernetes python37Packages.cirq python37Packages.google_cloud_automl python37Packages.google_cloud_bigquery python37Packages.google_cloud_bigtable python37Packages.google_cloud_container python37Packages.google_cloud_datastore python37Packages.google_cloud_dns python37Packages.google_cloud_error_reporting python37Packages.google_cloud_logging python37Packages.google_cloud_resource_manager python37Packages.google_cloud_runtimeconfig python37Packages.google_cloud_spanner python37Packages.google_cloud_storage python37Packages.google_cloud_translate python37Packages.rl-coach python38Packages.cirq python38Packages.google_cloud_automl python38Packages.google_cloud_bigquery python38Packages.google_cloud_bigtable python38Packages.google_cloud_container python38Packages.google_cloud_datastore python38Packages.google_cloud_dns python38Packages.google_cloud_error_reporting python38Packages.google_cloud_logging python38Packages.google_cloud_resource_manager python38Packages.google_cloud_runtimeconfig python38Packages.google_cloud_spanner python38Packages.google_cloud_storage python38Packages.google_cloud_translate python38Packages.rl-coach

83 package built:
beancount deja-dup duplicity duply fava gcalcli gdrivefs gmailieer kmymoney python27Packages.google-auth-httplib2 python27Packages.google_api_python_client python27Packages.google_auth python27Packages.google_cloud_testutils python27Packages.googleapis_common_protos python27Packages.grpc_google_iam_v1 python27Packages.pydrive python27Packages.weboob python37Packages.goobook python37Packages.google-auth-httplib2 python37Packages.google-auth-oauthlib python37Packages.google_api_core python37Packages.google_api_python_client python37Packages.google_auth python37Packages.google_cloud_asset python37Packages.google_cloud_bigquery_datatransfer python37Packages.google_cloud_core python37Packages.google_cloud_dataproc python37Packages.google_cloud_dlp python37Packages.google_cloud_firestore python37Packages.google_cloud_iot python37Packages.google_cloud_kms python37Packages.google_cloud_language python37Packages.google_cloud_monitoring python37Packages.google_cloud_pubsub python37Packages.google_cloud_redis python37Packages.google_cloud_securitycenter python37Packages.google_cloud_speech python37Packages.google_cloud_tasks python37Packages.google_cloud_testutils python37Packages.google_cloud_texttospeech python37Packages.google_cloud_trace python37Packages.google_cloud_videointelligence python37Packages.google_cloud_vision python37Packages.google_cloud_websecurityscanner python37Packages.googleapis_common_protos python37Packages.grpc_google_iam_v1 python37Packages.kubernetes python37Packages.pydrive python37Packages.weboob python38Packages.beancount python38Packages.goobook python38Packages.google-auth-httplib2 python38Packages.google-auth-oauthlib python38Packages.google_api_core python38Packages.google_api_python_client python38Packages.google_auth python38Packages.google_cloud_asset python38Packages.google_cloud_bigquery_datatransfer python38Packages.google_cloud_core python38Packages.google_cloud_dataproc python38Packages.google_cloud_dlp python38Packages.google_cloud_firestore python38Packages.google_cloud_iot python38Packages.google_cloud_kms python38Packages.google_cloud_language python38Packages.google_cloud_monitoring python38Packages.google_cloud_pubsub python38Packages.google_cloud_redis python38Packages.google_cloud_securitycenter python38Packages.google_cloud_speech python38Packages.google_cloud_tasks python38Packages.google_cloud_testutils python38Packages.google_cloud_texttospeech python38Packages.google_cloud_trace python38Packages.google_cloud_videointelligence python38Packages.google_cloud_vision python38Packages.google_cloud_websecurityscanner python38Packages.googleapis_common_protos python38Packages.grpc_google_iam_v1 python38Packages.kubernetes python38Packages.pydrive python38Packages.weboob s3ql
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build python3Packages.google_api_core
@GrahamcOfBorg build python3Packages.google_auth
@GrahamcOfBorg build python3Packages.google_cloud_core
@GrahamcOfBorg build python3Packages.googleapis_common_protos

**Pull request merged**
