### PR TITLE
openvscode-server: 1.85.1 -> 1.87.1

### PR DESCRIPTION
**Pull request by ck3d**
## Description of changes

update to latest version

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Rucadi** [comment]
This is not compiling, a:

nix run nixpkgs#openvscode-server

returns the error:

```
rucadi@Rucadi:~$ nix run nixpkgs#openvscode-server
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
error: builder for '/nix/store/sza40yyfjsvr0gnjdp92alrm11sqwmxx-openvscode-server-1.87.1.drv' failed with exit code 1;
       last 25 log lines:
       > npm ERR! ../node_modules/node-addon-api/napi-inl.h:3805:41:   required from 'static void Napi::InstanceWrap<T>::AttachPropData(napi_env, napi_value, const napi_property_descriptor*) [with T = node_kerberos::KerberosServer; napi_env = napi_env__*; napi_value = napi_value__*]'
       > npm ERR! ../node_modules/node-addon-api/napi-inl.h:4211:24:   required from 'static Napi::Function Napi::ObjectWrap<T>::DefineClass(Napi::Env, const char*, size_t, const napi_property_descriptor*, void*) [with T = node_kerberos::KerberosServer; size_t = long unsigned int]'
       > npm ERR! ../node_modules/node-addon-api/napi-inl.h:4224:21:   required from 'static Napi::Function Napi::ObjectWrap<T>::DefineClass(Napi::Env, const char*, const std::initializer_list<Napi::ClassPropertyDescriptor<T> >&, void*) [with T = node_kerberos::KerberosServer]'
       > npm ERR! ../src/kerberos.cc:95:20:   required from here
       > npm ERR! ../node_modules/node-addon-api/napi-inl.h:64:47: error: invalid conversion from 'napi_finalize' {aka 'void (*)(napi_env__*, void*, void*)'} to 'node_api_nogc_finalize' {aka 'void (*)(const napi_env__*, void*, void*)'} [-fpermissive]
       > npm ERR!    64 |   status = napi_add_finalizer(env, obj, data, finalizer, hint, nullptr);
       > npm ERR!       |                                               ^~~~~~~~~
       > npm ERR!       |                                               |
       > npm ERR!       |                                               napi_finalize {aka void (*)(napi_env__*, void*, void*)}
       > npm ERR! /nix/store/z5kba7kzgam364xkaxqzdhxjadh2mbqp-nodejs-18.20.0/include/node/js_native_api.h:516:43: note:   initializing argument 4 of 'napi_status napi_add_finalizer(napi_env, napi_value, void*, node_api_nogc_finalize, void*, napi_ref__**)'
       > npm ERR!   516 |                    node_api_nogc_finalize finalize_cb,
       > npm ERR!       |                    ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
       > npm ERR! make: *** [kerberos.target.mk:110: Release/obj.target/kerberos/src/kerberos.o] Error 1
       > npm ERR! gyp ERR! build error
       > npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
       > npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/nix/store/z5kba7kzgam364xkaxqzdhxjadh2mbqp-nodejs-18.20.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
       > npm ERR! gyp ERR! System Linux 5.15.146.1-microsoft-standard-WSL2
       > npm ERR! gyp ERR! command "/nix/store/z5kba7kzgam364xkaxqzdhxjadh2mbqp-nodejs-18.20.0/bin/node" "/nix/store/z5kba7kzgam364xkaxqzdhxjadh2mbqp-nodejs-18.20.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       > npm ERR! gyp ERR! cwd /build/source/remote/node_modules/kerberos
       > npm ERR! gyp ERR! node -v v18.20.0
       > npm ERR! gyp ERR! node-gyp -v v10.0.1
       > npm ERR! gyp ERR! not ok
       >
       > npm ERR! A complete log of this run can be found in: /build/source/.npm/_logs/2024-03-28T17_06_36_821Z-debug-0.log
       >
       For full logs, run 'nix-store -l /nix/store/sza40yyfjsvr0gnjdp92alrm11sqwmxx-openvscode-server-1.87.1.drv'.
```

**Comment by drupol** [comment]
The build was passing, which architecture are you using?

**Comment by Rucadi** [comment]
I'm using x86-64, could replicate in two different machines, both running ubuntu.

**Comment by drupol** [comment]
Got the same issue too :(

**Comment by Rucadi** [comment]
Commit b5e930a583294d194f3ba807283552b25f8a2888 seems to be the issue.

**Comment by drupol** [comment]
Maybe it's a bug in openvscode ?

**Comment by Rucadi** [comment]
> Maybe it's a bug in openvscode ?

It seems like it's a bug with ffi-napi, already being tracked here: https://github.com/nodejs/node/issues/52240

Probably could make sense to revert the PR https://github.com/NixOS/nixpkgs/pull/299328 ?

Probably this is not the only package affected.

**Comment by drupol** [comment]
@marsam Are you OK reverting it ?

**Comment by marsam** [comment]
>Are you OK reverting it ?

Yes, it's fine to revert it. Sorry about that!

**Pull request merged**
