### PR TITLE
garage: unbreak on aarch64-darwin

### PR DESCRIPTION
**Pull request by wegank**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 208722` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by RaitoBezarius** [comment]
@Artturin did you test it on aarch64-darwin? I didn't approve it.
I wanted to test it more thoroughly because we had tests not passing on the nix-community remote builder. :/

**Comment by Artturin** [comment]
I didnt but the ofborg build passed

**Comment by RaitoBezarius** [comment]
> I didnt but the ofborg build passed

The ofborg passed too on the previous PR but we could not reproduce it on the remote builder too, so I just hope this is a "environment problem" on the remote builder anyway

**Comment by Artturin** [comment]
for reference these are the failures

```
running 22 tests
test k2v::simple::test_simple ... FAILED
test k2v::batch::test_batch ... FAILED
test k2v::errorcodes::test_error_codes ... FAILED
test admin::test_admin_bucket_perms ... FAILED
test k2v::item::test_item_return_format ... FAILED
test k2v::poll::test_poll ... FAILED
test bucket::test_bucket_all ... FAILED
test k2v::item::test_items_and_indices ... FAILED
test s3::list::test_listmultipart ... FAILED
test s3::list::test_listobjectsv1 ... FAILED
test s3::list::test_listobjectsv2 ... FAILED
test s3::multipart::test_uploadlistpart ... FAILED
test s3::multipart::test_uploadpartcopy ... FAILED
test s3::objects::test_deleteobject ... FAILED
test s3::objects::test_getobject ... FAILED
test s3::objects::test_putobject ... FAILED
test s3::simple::test_simple ... FAILED
test s3::streaming_signature::test_create_bucket_streaming ... FAILED
test s3::streaming_signature::test_put_website_streaming ... FAILED
test s3::streaming_signature::test_putobject_streaming ... FAILED
test s3::website::test_website_s3_api ... FAILED
test s3::website::test_website ... FAILED

failures:

---- k2v::simple::test_simple stdout ----
thread 'k2v::simple::test_simple' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- k2v::batch::test_batch stdout ----
thread 'k2v::batch::test_batch' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- k2v::errorcodes::test_error_codes stdout ----
thread 'k2v::errorcodes::test_error_codes' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- admin::test_admin_bucket_perms stdout ----
thread 'admin::test_admin_bucket_perms' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- k2v::item::test_item_return_format stdout ----
thread 'k2v::item::test_item_return_format' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- k2v::poll::test_poll stdout ----
thread 'k2v::poll::test_poll' panicked at 'Command exited with code 1: Could not assign garage node layout', src/garage/tests/common/ext/process.rs:46:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- bucket::test_bucket_all stdout ----
thread 'bucket::test_bucket_all' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- k2v::item::test_items_and_indices stdout ----
thread 'k2v::item::test_items_and_indices' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::list::test_listmultipart stdout ----
thread 's3::list::test_listmultipart' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::list::test_listobjectsv1 stdout ----
thread 's3::list::test_listobjectsv1' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::list::test_listobjectsv2 stdout ----
thread 's3::list::test_listobjectsv2' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::multipart::test_uploadlistpart stdout ----
thread 's3::multipart::test_uploadlistpart' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::multipart::test_uploadpartcopy stdout ----
thread 's3::multipart::test_uploadpartcopy' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::objects::test_deleteobject stdout ----
thread 's3::objects::test_deleteobject' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::objects::test_getobject stdout ----
thread 's3::objects::test_getobject' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::objects::test_putobject stdout ----
thread 's3::objects::test_putobject' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::simple::test_simple stdout ----
thread 's3::simple::test_simple' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::streaming_signature::test_create_bucket_streaming stdout ----
thread 's3::streaming_signature::test_create_bucket_streaming' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::streaming_signature::test_put_website_streaming stdout ----
thread 's3::streaming_signature::test_put_website_streaming' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::streaming_signature::test_putobject_streaming stdout ----
thread 's3::streaming_signature::test_putobject_streaming' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::website::test_website_s3_api stdout ----
thread 's3::website::test_website_s3_api' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19

---- s3::website::test_website stdout ----
thread 's3::website::test_website' panicked at 'Once instance has previously been poisoned', src/garage/tests/common/garage.rs:215:19


failures:
    admin::test_admin_bucket_perms
    bucket::test_bucket_all
    k2v::batch::test_batch
    k2v::errorcodes::test_error_codes
    k2v::item::test_item_return_format
    k2v::item::test_items_and_indices
    k2v::poll::test_poll
    k2v::simple::test_simple
    s3::list::test_listmultipart
    s3::list::test_listobjectsv1
    s3::list::test_listobjectsv2
    s3::multipart::test_uploadlistpart
    s3::multipart::test_uploadpartcopy
    s3::objects::test_deleteobject
    s3::objects::test_getobject
    s3::objects::test_putobject
    s3::simple::test_simple
    s3::streaming_signature::test_create_bucket_streaming
    s3::streaming_signature::test_put_website_streaming
    s3::streaming_signature::test_putobject_streaming
    s3::website::test_website
    s3::website::test_website_s3_api

test result: FAILED. 0 passed; 22 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.07s
```

looks like they're due to a impurity or something

**Pull request merged**
