### PR TITLE
linuxPackages: remove kernelHeaders

### PR DESCRIPTION
**Pull request by joachifm**
EDIT: see commit messages for details

### CODE REVIEW

**Comment by joachifm** [comment]
Ah, of course something DID use that attribute: klibc

**Comment by joachifm** [comment]
Pushed a more compatible variant

**Comment by joachifm** [comment]
As far as I can tell, klibc is the only package affected by this change.

**Comment by dezgeg** [comment]
Well, the API does change in the sense that new kernel versions can add new stuff. Say, if I right now wanted to use say, `PTRACE_O_SUSPEND_SECCOMP` (taken from https://lwn.net/Articles/656731/) in my program I'd need `linuxPackages_4_4.kernelHeaders` (or newer) in `buildInputs` to use it.

However, that does have the drawback that if the 4.4 kernel in nixpkgs gets stable/security updates, my program would need to be recompiled for no good reason... so really only suitable for lazy people and/or out-of-nixpkgs packages, I'd guess. The "proper" way would be add a `linuxHeaders_4_4` (note: a top-level attribute, not inside `linuxPackages`) alongside the one we currently have (seems to be `linuxHeaders_3_18`).

**Comment by joachifm** [comment]
When I say patching I don't mean updating the kernel, I'm aware that could change the API.

According to https://www.kernel.org/doc/Documentation/kbuild/headers_install.txt they are always backwards compatible, so it should be okay to always just use the newest header package.

**Comment by dezgeg** [comment]
> so it should be okay just use the newest header package.
Well, yes. But the latest `linuxHeaders` package we currently have is `linuxHeaders_3_18`, so there is some value in using e.g. `linuxPackages_4_4.kernelHeaders`.

**Comment by joachifm** [comment]
Oh, I very much agree with that

**Comment by joachifm** [comment]
Linus on API headers: http://lkml.iu.edu/hypermail/linux/kernel/0007.3/0587.html The way I read this, for API headers you always want the ones that were used for libc, which I think strengthens the argument for removing `linuxPackages.kernelHeaders`.

**Comment by joachifm** [comment]
I have now updated klibc to use linuxHeaders and moved it out of linuxPackages. The reasoning for each step has been consolidated in the commit messages.

**Comment by joachifm** [comment]
I've successfully built all affected packages locally, so given the lack of objections, I'm merging this.

**Pull request merged**
