### PR TITLE
Remove all dots at end of descriptions

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done:
- [ ] Tested via `nix.useChroot`.
- [ ] Built on platform(s): .
- [ ] Tested compilation of all pkgs that depend on this change.
- [ ] Tested execution of binary products.
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Is this something that we want to do ? It might make it harder for some of the long-running branches to rebase. Although they usually touch the code and not the descriptions.

Specially crafted for @JagaJaga

```
find -name "*.nix" -exec sed -e 's|\(description.*\)\.";|\1";|g' -i {} \;
```

### CODE REVIEW

**Comment by jagajaga** [comment]
Descriptions of modules must stay with dots. Only pkgs!

**Comment by grahamc** [comment]
Nice!

```diff
18:55:29.676 550d549
18:55:29.677 < aws_shell: Description ends with a period
18:55:29.677 574d572
18:55:29.677 < backblaze-b2: Description ends with a period
18:55:29.677 681d678
18:55:29.677 < bitmeter: Description ends with a period
18:55:29.678 907d903
18:55:29.678 < certificate-transparency: Description ends with a period
18:55:29.678 949d944
18:55:29.678 < chirp: Description ends with a period
18:55:29.678 1135d1129
18:55:29.679 < compass: Description ends with a period
18:55:29.679 1189d1182
18:55:29.679 < coreclr: Description ends with a period
18:55:29.679 1395d1387
18:55:29.679 < dcadec: Description ends with a period
18:55:29.679 1450d1441
18:55:29.680 < devilspie2: Description ends with a period
18:55:29.680 1531d1521
18:55:29.680 < direwolf: Description ends with a period
18:55:29.680 1731d1720
18:55:29.680 < dotnetPackages.MathNetNumerics: Description ends with a period
18:55:29.681 1794d1782
18:55:29.681 < driftnet: Description ends with a period
18:55:29.681 2003d1990
18:55:29.681 < elmPackages.elm-compiler: Description ends with a period
18:55:29.681 2067d2053
18:55:29.682 < entr: Description ends with a period
18:55:29.682 2489d2474
18:55:29.682 < gawp: Description ends with a period
18:55:29.682 2670d2654
18:55:29.682 < git-radar: Description ends with a period
18:55:29.682 3690d3673
18:55:29.683 < homesick: Description ends with a period
18:55:29.683 3716d3698
18:55:29.683 < htmlcxx: Description ends with a period
18:55:29.683 3774d3755
18:55:29.684 < i3blocks: Description ends with a period
18:55:29.684 3871d3851
18:55:29.684 < imgur-screenshot: Description ends with a period
18:55:29.684 4070d4049
18:55:29.684 < jenkins-job-builder: Description ends with a period
18:55:29.684 4132d4110
18:55:29.684 < jp2a: Description ends with a period
18:55:29.684 5603d5580
18:55:29.684 < lgogdownloader: Description ends with a period
18:55:29.684 6487d6463
18:55:29.684 < linuxPackages.rtl8812au: Description ends with a period
18:55:29.684 6541d6516
18:55:29.684 < linuxPackages_3_10.rtl8812au: Description ends with a period
18:55:29.684 6596d6570
18:55:29.684 < linuxPackages_3_12.rtl8812au: Description ends with a period
18:55:29.685 6652d6625
18:55:29.685 < linuxPackages_3_14.rtl8812au: Description ends with a period
18:55:29.685 6707d6679
18:55:29.685 < linuxPackages_3_18.rtl8812au: Description ends with a period
18:55:29.685 6763d6734
18:55:29.685 < linuxPackages_4_1.rtl8812au: Description ends with a period
18:55:29.685 6820d6790
18:55:29.685 < linuxPackages_4_3.rtl8812au: Description ends with a period
18:55:29.685 6876d6845
18:55:29.685 < linuxPackages_chromiumos_3_14.rtl8812au: Description ends with a period
18:55:29.685 6931d6899
18:55:29.685 < linuxPackages_chromiumos_3_18.rtl8812au: Description ends with a period
18:55:29.685 6985d6952
18:55:29.685 < linuxPackages_chromiumos_latest.rtl8812au: Description ends with a period
18:55:29.685 7048d7014
18:55:29.685 < linuxPackages_latest_xen_dom0.rtl8812au: Description ends with a period
18:55:29.686 7105d7070
18:55:29.686 < linuxPackages_testing.rtl8812au: Description ends with a period
18:55:29.686 7316d7280
18:55:29.686 < logstash: Description ends with a period
18:55:29.686 7379d7342
18:55:29.686 < longview: Description ends with a period
18:55:29.686 7391d7353
18:55:29.686 < lp_solve: Description ends with a period
18:55:29.686 8017d7978
18:55:29.686 < multimon-ng: Description ends with a period
18:55:29.686 8402d8362
18:55:29.686 < ocamlPackages.bitstring: Description ends with a period
18:55:29.686 8536d8495
18:55:29.686 < ocamlPackages.piqi: Description ends with a period
18:55:29.686 8539d8497
18:55:29.686 < ocamlPackages.piqi-ocaml: Description ends with a period
18:55:29.686 8569d8526
18:55:29.687 < ocamlPackages.uuidm: Description ends with a period
18:55:29.687 8626d8582
18:55:29.687 < omniorb: Description ends with a period
18:55:29.687 8864d8819
18:55:29.687 < pamtester: Description ends with a period
18:55:29.687 10331d10285
18:55:29.687 < perlPackages.LogLogLite: Description ends with a period
18:55:29.687 11905d11858
18:55:29.687 < picolisp: Description ends with a period
18:55:29.687 11943d11895
18:55:29.687 < pioneer: Description ends with a period
18:55:29.687 12036d11987
18:55:29.687 < popfile: Description ends with a period
18:55:29.687 12286d12236
18:55:29.687 < python27Packages.FormEncode: Description ends with a period
18:55:29.687 12300d12249
18:55:29.688 < python27Packages.SPARQLWrapper: Description ends with a period
18:55:29.688 12451d12399
18:55:29.688 < python27Packages.cmd2: Description ends with a period
18:55:29.688 12546d12493
18:55:29.688 < python27Packages.django_pipeline: Description ends with a period
18:55:29.688 12548d12494
18:55:29.688 < python27Packages.django_pipeline_1_3: Description ends with a period
18:55:29.688 12643d12588
18:55:29.688 < python27Packages.gcutil: Description ends with a period
18:55:29.688 12660d12604
18:55:29.688 < python27Packages.ghp-import: Description ends with a period
18:55:29.688 12685d12628
18:55:29.688 < python27Packages.gpsoauth: Description ends with a period
18:55:29.688 12737d12679
18:55:29.688 < python27Packages.inginious: Description ends with a period
18:55:29.688 12783d12724
18:55:29.689 < python27Packages.keepalive: Description ends with a period
18:55:29.689 12819d12759
18:55:29.689 < python27Packages.linecache2: Description ends with a period
18:55:29.689 13063d13002
18:55:29.689 < python27Packages.pkginfo: Description ends with a period
18:55:29.689 13091d13029
18:55:29.689 < python27Packages.ptest: Description ends with a period
18:55:29.689 13122d13059
18:55:29.689 < python27Packages.pycontracts: Description ends with a period
18:55:29.689 13137d13073
18:55:29.689 < python27Packages.pyelasticsearch: Description ends with a period
18:55:29.689 13184d13119
18:55:29.689 < python27Packages.pypolicyd-spf: Description ends with a period
18:55:29.689 13411d13345
18:55:29.689 < python27Packages.shortuuid: Description ends with a period
18:55:29.689 13475d13408
18:55:29.689 < python27Packages.svgwrite: Description ends with a period
18:55:29.690 13538d13470
18:55:29.690 < python27Packages.traceback2: Description ends with a period
18:55:29.690 13742d13673
18:55:29.690 < python35Packages.FormEncode: Description ends with a period
18:55:29.690 13754d13684
18:55:29.690 < python35Packages.SPARQLWrapper: Description ends with a period
18:55:29.690 13857d13786
18:55:29.690 < python35Packages.cmd2: Description ends with a period
18:55:29.690 13991d13919
18:55:29.690 < python35Packages.ghp-import: Description ends with a period
18:55:29.690 14007d13934
18:55:29.690 < python35Packages.gpsoauth: Description ends with a period
18:55:29.690 14073d13999
18:55:29.690 < python35Packages.keepalive: Description ends with a period
18:55:29.690 14088d14013
18:55:29.690 < python35Packages.linecache2: Description ends with a period
18:55:29.691 14232d14156
18:55:29.691 < python35Packages.pkginfo: Description ends with a period
18:55:29.691 14252d14175
18:55:29.691 < python35Packages.ptest: Description ends with a period
18:55:29.691 14273d14195
18:55:29.691 < python35Packages.pycontracts: Description ends with a period
18:55:29.691 14284d14205
18:55:29.691 < python35Packages.pyelasticsearch: Description ends with a period
18:55:29.691 14486d14406
18:55:29.691 < python35Packages.shortuuid: Description ends with a period
18:55:29.691 14523d14442
18:55:29.691 < python35Packages.svgwrite: Description ends with a period
18:55:29.691 14553d14471
18:55:29.691 < python35Packages.traceback2: Description ends with a period
18:55:29.691 15049d14966
18:55:29.691 < rebar3: Description ends with a period
18:55:29.692 15054d14970
18:55:29.692 < rebar3-open: Description ends with a period
18:55:29.692 16487d16402
18:55:29.692 < ums: Description ends with a period
18:55:29.692 16610d16524
18:55:29.692 < vanilla-dmz: Description ends with a period
18:55:29.692 17410d17323
18:55:29.692 < wolfssl: Description ends with a period
18:55:29.692 17617d17529
18:55:29.692 < xfce.xfce4_whiskermenu_plugin: Description ends with a period
18:55:29.692 18488d18399
18:55:29.692 < zandronum-server: Description ends with a period
18:55:29.692 18919c18830
18:55:29.692 < Number of bad descriptions: 312
18:55:29.692 ---
18:55:29.692 > Number of bad descriptions: 232
```

**Comment by zimbatm** [comment]
@jagajaga fixed

**Comment by zimbatm** [comment]
@grahamc what kind of tool do you use to generate this output ?

**Pull request merged**
