### PR TITLE
postman: 9.31.0 -> 10.12.0

### PR DESCRIPTION
**Pull request by GabrielDougherty**
###### Description of changes

Update Postman from 9.31.0 to 10.12.0 . Release notes are here: https://www.postman.com/release-notes/postman-app/

Also added support for aarch64 linux.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GabrielDougherty** [comment]
cc @johnrichardrinehart

**Comment by GabrielDougherty** [comment]
Result of `nixpkgs-review pr 222113` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>postman</li>
  </ul>
</details>

**Comment by johnrichardrinehart** [comment]
@GabrielDougherty Sorry for the late response. Thanks for doing this work!

**Comment by GabrielDougherty** [comment]
@johnrichardrinehart Any time

**Comment by chasecaleb** [comment]
@GabrielDougherty @SuperSandro2000 This broke postman for me -- any thoughts on what's going on?

Here's what happens on nixos-unstable (current commit at time of testing is 4bb072f0a8b267613c127684e099a70e1f6ff106)
```
caleb@work-vmware> NIXPKGS_ALLOW_UNFREE=1 nix run --impure 'github:nixos/nixpkgs/nixos-unstable#postman'                             
[113845:0328/144259.027576:FATAL:fork_and_spawn.cc(196)] posix_spawn: No such file or directory (2)
```

Reverting to 9.31.0 works, which I tested by doing `NIXPKGS_ALLOW_UNFREE=1 nix run --impure 'github:nixos/nixpkgs/8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8#postman'`. I found the commit from https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=postman ... it's from 3/11.

**Comment by GabrielDougherty** [comment]
@chasecaleb can you run it with strace to see which file it is failing to open?

**Comment by johnrichardrinehart** [comment]
> @GabrielDougherty @SuperSandro2000 This broke postman for me -- any thoughts on what's going on?
> 
> Here's what happens on nixos-unstable (current commit at time of testing is [4bb072f](https://github.com/NixOS/nixpkgs/commit/4bb072f0a8b267613c127684e099a70e1f6ff106))
> 
> ```
> caleb@work-vmware> NIXPKGS_ALLOW_UNFREE=1 nix run --impure 'github:nixos/nixpkgs/nixos-unstable#postman'                             
> [113845:0328/144259.027576:FATAL:fork_and_spawn.cc(196)] posix_spawn: No such file or directory (2)
> ```
> 
> Reverting to 9.31.0 works, which I tested by doing `NIXPKGS_ALLOW_UNFREE=1 nix run --impure 'github:nixos/nixpkgs/8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8#postman'`. I found the commit from https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=postman ... it's from 3/11.

What's your arch?

**Comment by johnrichardrinehart** [comment]
I see. `postman` as a part of its initialization starts `chrome_crashpad_launcher` which didn't have `patchelf` applied to it so the linker was pointing to
```bash
$ NIXPKGS_ALLOW_UNFREE=1 nix build --impure .#postman && file ./result/share/postman/chrome_crashpad_handler 
./result/share/postman/chrome_crashpad_handler: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=10673ac1910d11465f65e039f32033ac9871289d, not stripped
```

I pushed #223988 to fix this:
```bash

**Comment by johnrichardrinehart** [comment]
@chasecaleb Please give `NIXPKGS_ALLOW_UNFREE=1 nix run --impure github:johnrichardrinehart/nixpkgs/johnrichardrinehart/fix-postman-linker#postman && file ./result/share/postman/chrome_crashpad_handler` a try.

**Comment by chasecaleb** [comment]
Sorry for taking a couple days to get back to this, but looks like you've got it under control. Nice job!

> @chasecaleb Please give
> 
> ```shell
> NIXPKGS_ALLOW_UNFREE=1 nix run --impure github:johnrichardrinehart/nixpkgs/johnrichardrinehart/fix-postman-linker#postman
> ```
> 
> a try.

@johnrichardrinehart verified - that works for me :100:

**Comment by johnrichardrinehart** [comment]
> Sorry for taking a couple days to get back to this, but looks like you've got it under control. Nice job!
> 
> > @chasecaleb Please give
> > 
> > ```shell
> > NIXPKGS_ALLOW_UNFREE=1 nix run --impure github:johnrichardrinehart/nixpkgs/johnrichardrinehart/fix-postman-linker#postman
> > ```
> > 
> > a try.
> 
> @johnrichardrinehart verified - that works for me :100:

Haha, all good. I only put up this work less than a day ago. Thanks for confirming it fixes!

**Pull request merged**
