### PR TITLE
python3Packages.llama-cpp-python: init at 0.2.18

### LINKED ISSUE #242792: Package request: llama-cpp-python
## **Project description**

Simple Python bindings for @ggerganov's llama.cpp library. This package provides:

-   Low-level access to C API via ctypes interface.
-   High-level Python API for text completion
    -   OpenAI-like API
    -   LangChain compatibility

## **Metadata**

* homepage URL: https://llama-cpp-python.readthedocs.io
* source URL: https://github.com/abetlen/llama-cpp-python
* license: mit
* platforms: unix, linux, darwin, ...

## Related:

<https://github.com/NixOS/nixpkgs/issues/224921>

### PR DESCRIPTION
**Pull request by elohmeier**
## Description of changes

Added the llama-cpp-python package containing the Python bindings for llama.cpp. Required shared libraries and models have been exposed in llama-cpp.
Fixes #242792.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7omb** [comment]
I just found this PR when I was about to [create one](https://github.com/NixOS/nixpkgs/commit/daf66ce0dd7c4c1963f257d1b3b0b3de7522bb28). Because they differ in some aspects, I still want to mention it here to facilitate discussion.

This PR uses the existing llama-cpp package which has the advantage that cuda, rocm etc. should work. The (current) drawback is that it does not use the [vendored llama.cpp version](https://github.com/abetlen/llama-cpp-python/tree/f3b844ed0a139fc5799d6e515e9d1d063c311f97/vendor) and requires patches.

**Comment by elohmeier** [comment]
There is an issue with the shared library change in llama-cpp causing problems when using it with ollama, I'll investigate that issue.

**Comment by mausch** [comment]
Thanks for starting this PR @elohmeier !

Currently this is missing a few dependencies to get  https://github.com/abetlen/llama-cpp-python#openai-compatible-web-server to run: uvicorn, fastapi, starlette, and pydantic 2.x ( https://github.com/NixOS/nixpkgs/pull/244564 ).

**Comment by 414owen** [comment]
@elohmeier are you still seeing an issue here? llama-cpp-python has moved on a bit, and the patches no longer apply.

**Comment by elohmeier** [comment]
Unfortunately I have no use for that package right now. Maybe someone else can pick this up.

**Comment by kirillrdy** [comment]
i have a working version for latest llama-cpp-python, with CUDA support, but using vendored llama, if people are interested can create PR

**Comment by hoh** [comment]
It's been almost a year since this PR was open and `llama-cpp` is now well in `nixpkgs`. 

Would it now make sense to add this library to `nixpkgs` ?

@kirillrdy , can you share this version you mentioned ?

**Comment by kirillrdy** [comment]
@hoh https://github.com/NixOS/nixpkgs/pull/349657

**Comment by hoh** [comment]
> @hoh #349657

Nice 🤩, thank you!
I'll test it on Monday.

**Pull request closed without merging**
