### PR TITLE
godot: 3.4.4 -> 3.5

### PR DESCRIPTION
**Pull request by leiserfg**
###### Description of changes

https://github.com/godotengine/godot/blob/3.5/CHANGELOG.md#35---2022-08-05

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by viraptor** [comment]
Result of `nixpkgs-review pr 186692` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lorien</li>
  </ul>
</details>

**Review by Lerrrtaste — APPROVED** [review]
Works for me

**Comment by kilianar** [comment]
This seems to be a duplicate of #185916

**Comment by leiserfg** [comment]
> This seems to be a duplicate of #185916

You are right, I didn't see it, but in any case, the patch in that PR  has the mistake of keeping comments that should be removed (related to the `--libs` flag). One of the two can be closed but please some one merge the other one.

**Review by MatthewCroughan — APPROVED** [review]

**Comment by MatthewCroughan** [comment]
Sound doesn't seem to work, specifically with this PR.

```
Godot Engine v3.5.stable.custom_build - https://godotengine.org/
OpenGL ES 3.0 Renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
Async. shader compilation: OFF
ALSA lib pcm.c:2655:(snd_pcm_open_conf) Either /nix/store/mdgpj79x2j8hmdlzpiby6g9dw631h7r4-alsa-plugins-1.2.7.1/lib/alsa-lib/libasound_module_pcm_pulse.so cannot be opened or _snd_pcm_pulse_open was not defined inside
ERROR: Condition "status < 0" is true. Returned: ERR_CANT_OPEN
   at: init_device (drivers/alsa/audio_driver_alsa.cpp:89)
WARNING: All audio drivers failed, falling back to the dummy driver.
     at: initialize (servers/audio_server.cpp:222)
```

**Comment by leiserfg** [comment]
> Condition "status < 0" is true. Returned: ERR_CANT_OPEN
Are you using nixos or nix in another system? In non-nixos systems I have faced similar issues with other programs, try building godot with pulseaudio enabled and see if that fixes it.

**Comment by MatthewCroughan** [comment]
@leiserfg this is on a NixOS system. The entire NixOS configuration can be found here. https://github.com/goatchurchprime/nixcfg

NixOS 22.05's Godot, as well as NixOS Unstable's `godot` package both work fine. The error only occurs with this PR.

**Comment by leiserfg** [comment]
> @leiserfg this is on a NixOS system. The entire NixOS configuration can be found here. https://github.com/goatchurchprime/nixcfg
> 
> NixOS 22.05's Godot, as well as NixOS Unstable's `godot` package both work fine. The error only occurs with this PR.

Very rare, I don't think it's the packaging, as I (and neither the other PR) didn't add any alsa related change, also the audio works fine for me so I can't debug it. Enabling the pulseaudio should fix it (no idea why it's not the default but I don't think I should change it ).

**Comment by MatthewCroughan** [comment]
@leiserfg the patch has changed the way it handles alsa. So there are alsa changes in this PR that could have caused this, even if subtle.

**Comment by leiserfg** [comment]
> the patch has changed the way it handles alsa

The only change is the line number of where the alsa lib is injected, check the same file in master https://github.com/NixOS/nixpkgs/blob/da87f771027c5fe2db7d93d4e56197849236dc5a/pkgs/development/tools/godot/pkg_config_additions.patch#L21

**Comment by MatthewCroughan** [comment]
@leiserfg Compiling with `pulseaudio = true` doesn't seem to change the error or runtime behavior. Something about this PR, or Godot 3.5 has broken audio.

**Comment by MatthewCroughan** [comment]
```
nix-repl> y = import <nixpkgs> {}                        

nix-repl> x = import (builtins.getFlake "github:leiserfg/nixpkgs/update-godot") {}         

nix-repl> x.alsa-lib.version
"1.2.6.1"

nix-repl> y.alsa-lib.version                                                       
"1.2.7.2"
```

This may explain some of the behavior. Your PR is based on alsa 1.2.6.1, whereas my system is based on alsa 1.2.7.2. 

`alsa-lib` in Nixpkgs was updated recently via 
- https://github.com/NixOS/nixpkgs/commit/a1edc2fe67a6efd0c4fd0febb8008091daa5c2ef
- https://github.com/NixOS/nixpkgs/commit/020ca659d7fd00f117c6aa308d1aaa276480f1f8

**Comment by MatthewCroughan** [comment]
@leiserfg 
Following on from my previous comment, I got sound working by the following expression
```
nix-repl> y = import <nixpkgs> {}                        

nix-repl> x = import (builtins.getFlake "github:leiserfg/nixpkgs/update-godot") {}

nix-repl> y.callPackage x.godot.override {}
«derivation /nix/store/2g1c34gi8l3f273miz7g7ky5k9ar8prz-godot-3.5.drv»

nix-repl> :b y.callPackage x.godot.override {}

This derivation produced the following outputs:
  dev -> /nix/store/g3am6wcys22wkg345i0sn2ia36564gys-godot-3.5-dev
  man -> /nix/store/q19j81wpsy6hm5w1i50aaaii2ispwxvs-godot-3.5-man
  out -> /nix/store/k5fz4phfkf3ljpl7an1j7is7csnbbgbm-godot-3.5
```

This means I built a Godot based on your PR's derivation, except replacing all of its input arguments with values coming from my own system, where alsa-lib is at the correct version, etc.

This solved the problem, and the resulting Godot binary works fine and has working audio.

**Comment by MatthewCroughan** [comment]
If we look closer at the error that was thrown by Godot, it would imply that it looks for `alsa-plugins` from the environment, which is an impurity that needs to be fixed.

```
ALSA lib pcm.c:2655:(snd_pcm_open_conf) Either /nix/store/mdgpj79x2j8hmdlzpiby6g9dw631h7r4-alsa-plugins-1.2.7.1/lib/alsa-lib/libasound_module_pcm_pulse.so cannot be opened or _snd_pcm_pulse_open was not defined inside
```

Since your PR is based on alsa-plugins 1.2.6, yet this error was thrown on my system, it implies that Godot found it based on the environment. Tricky.

**Comment by leiserfg** [comment]
> ```
> nix-repl> y = import <nixpkgs> {}                        
> 
> nix-repl> x = import (builtins.getFlake "github:leiserfg/nixpkgs/update-godot") {}         
> 
> nix-repl> x.alsa-lib.version
> "1.2.6.1"
> 
> nix-repl> y.alsa-lib.version                                                       
> "1.2.7.2"
> ```
> 
> This may explain some of the behavior. Your PR is based on alsa 1.2.6.1, whereas my system is based on alsa 1.2.7.2.
> 
> `alsa-lib` in Nixpkgs was updated recently via
> 
>     * [a1edc2f](https://github.com/NixOS/nixpkgs/commit/a1edc2fe67a6efd0c4fd0febb8008091daa5c2ef)
> 
>     * [020ca65](https://github.com/NixOS/nixpkgs/commit/020ca659d7fd00f117c6aa308d1aaa276480f1f8)

If that works then It should be fine if I just rebase the PR on top of a more recent commit of master.

**Comment by MatthewCroughan** [comment]
@leiserfg

> If that works then It should be fine if I just rebase the PR on top of a more recent commit of master.

That is only a temporary fix. Like I explain above, Godot has an impurity since it is able to discover **new alsa versions** on the system dynamically, even though it was compiled with 1.2.6, it still found `alsa-plugins` 1.2.7 at runtime. It then looked for a function name, and it did not exist. That is the real problem.

**Comment by leiserfg** [comment]
I faced a similar issue before with another program and this fixed it, maybe that also works for godot, can you try doing it by hand? (I can't because godot works for me) 
https://github.com/NixOS/nixpkgs/pull/168004

**Comment by MatthewCroughan** [comment]
@leiserfg that does indeed look like the fix we need. Although, in theory, this problem exists for every program that uses `alsa-lib`, right? It's a shame we can't fix this generically for every program using `alsa-lib`. I'll give your PR a PR.

**Comment by MatthewCroughan** [comment]
@leiserfg I've made the following PR to your PR here, please merge it, and then we can see about getting this PR merged and kill two birds with one stone :) 

https://github.com/leiserfg/nixpkgs/pull/1

**Pull request merged**
