### PR TITLE
libspectre: 0.2.7 -> 0.2.12

### PR DESCRIPTION
**Pull request by panicgh**
## Description of changes

https://gitlab.freedesktop.org/libspectre/libspectre/-/blob/0.2.12/NEWS

Bump from the old 0.2.7 (2012) release to 0.2.12 (2023).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

----

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>61 packages built:</summary>
  <ul>
    <li>cantor</li>
    <li>cinnamon.xreader</li>
    <li>deco</li>
    <li>deepin.deepin-reader</li>
    <li>denemo</li>
    <li>enlightenment.econnman</li>
    <li>enlightenment.ecrire</li>
    <li>enlightenment.efl</li>
    <li>enlightenment.enlightenment</li>
    <li>enlightenment.ephoto</li>
    <li>enlightenment.evisum</li>
    <li>enlightenment.rage</li>
    <li>enlightenment.terminology</li>
    <li>evince</li>
    <li>evince.dev</li>
    <li>evince.devdoc</li>
    <li>farge</li>
    <li>feh</li>
    <li>feh.doc</li>
    <li>feh.man</li>
    <li>fontpreview</li>
    <li>glom</li>
    <li>glom.dev</li>
    <li>glom.devdoc</li>
    <li>glom.doc</li>
    <li>glom.lib</li>
    <li>gnome.sushi</li>
    <li>hqplayer-desktop</li>
    <li>hqplayer-desktop.doc</li>
    <li>imlib2Full</li>
    <li>imlib2Full.bin</li>
    <li>imlib2Full.dev</li>
    <li>kile</li>
    <li>labplot</li>
    <li>libsForQt5.okular</li>
    <li>libspectre</li>
    <li>manga-cli</li>
    <li>mate.atril</li>
    <li>multilockscreen</li>
    <li>nsxiv</li>
    <li>nsxiv.doc</li>
    <li>nsxiv.man</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>pqiv</li>
    <li>python310Packages.pythonefl</li>
    <li>python310Packages.pythonefl.dist</li>
    <li>python310Packages.pywal</li>
    <li>python310Packages.pywal.dist</li>
    <li>python311Packages.pythonefl</li>
    <li>python311Packages.pythonefl.dist</li>
    <li>pywal (python311Packages.pywal)</li>
    <li>pywal.dist (python311Packages.pywal.dist)</li>
    <li>qiv</li>
    <li>qpdfview</li>
    <li>stylish</li>
    <li>sxiv</li>
    <li>vimPlugins.openscad-nvim</li>
    <li>wpgtk</li>
    <li>wpgtk.dist</li>
    <li>zathura</li>
  </ul>
</details>

### CODE REVIEW

**Comment by risicle** [comment]
`nixpkgs-review` happy, nixos x86_64

**Comment by onemoresuza** [comment]
# Reviewed points

Result of `nixpkgs-review pr 268549` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>calligra</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>manga-cli</li>
  </ul>
</details>
<details>
  <summary>60 packages built:</summary>
  <ul>
    <li>cantor (libsForQt5.cantor ,plasma5Packages.cantor)</li>
    <li>cinnamon.xreader</li>
    <li>deco</li>
    <li>deepin.deepin-reader</li>
    <li>denemo</li>
    <li>enlightenment.econnman</li>
    <li>enlightenment.ecrire</li>
    <li>enlightenment.efl</li>
    <li>enlightenment.enlightenment</li>
    <li>enlightenment.ephoto</li>
    <li>enlightenment.evisum</li>
    <li>enlightenment.rage</li>
    <li>enlightenment.terminology</li>
    <li>evince (gnome.evince)</li>
    <li>evince.dev (gnome.evince.dev)</li>
    <li>evince.devdoc (gnome.evince.devdoc)</li>
    <li>farge</li>
    <li>feh</li>
    <li>feh.doc</li>
    <li>feh.man</li>
    <li>fontpreview</li>
    <li>glom</li>
    <li>glom.dev</li>
    <li>glom.devdoc</li>
    <li>glom.doc</li>
    <li>glom.lib</li>
    <li>gnome.sushi</li>
    <li>hqplayer-desktop</li>
    <li>hqplayer-desktop.doc</li>
    <li>imlib2Full</li>
    <li>imlib2Full.bin</li>
    <li>imlib2Full.dev</li>
    <li>kile</li>
    <li>labplot</li>
    <li>libsForQt5.okular (plasma5Packages.okular)</li>
    <li>libspectre</li>
    <li>mate.atril</li>
    <li>multilockscreen</li>
    <li>nsxiv</li>
    <li>nsxiv.doc</li>
    <li>nsxiv.man</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>pqiv</li>
    <li>python310Packages.pythonefl</li>
    <li>python310Packages.pythonefl.dist</li>
    <li>python310Packages.pywal</li>
    <li>python310Packages.pywal.dist</li>
    <li>python311Packages.pythonefl</li>
    <li>python311Packages.pythonefl.dist</li>
    <li>pywal (python311Packages.pywal)</li>
    <li>pywal.dist (python311Packages.pywal.dist)</li>
    <li>qiv</li>
    <li>qpdfview</li>
    <li>stylish</li>
    <li>sxiv</li>
    <li>vimPlugins.openscad-nvim</li>
    <li>wpgtk</li>
    <li>wpgtk.dist</li>
    <li>zathura</li>
  </ul>
</details>

- [X] package name fits guidelines
- [X] package version fits guidelines
- [X] package builds on x86_64-linux
- [X] executables tested on x86_64-linux
- [ ] all depending packages build
    - The `manga-cli` package failed to build
- [X] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [X] patches that are remotely available are fetched rather than vendored

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by panicgh** [comment]
I could not reproduce the manga-cli build failure.

Result of `nixpkgs-review pr 268549` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>calligra</li>
  </ul>
</details>
<details>
  <summary>61 packages built:</summary>
  <ul>
    <li>cantor (libsForQt5.cantor ,plasma5Packages.cantor)</li>
    <li>cinnamon.xreader</li>
    <li>deco</li>
    <li>deepin.deepin-reader</li>
    <li>denemo</li>
    <li>enlightenment.econnman</li>
    <li>enlightenment.ecrire</li>
    <li>enlightenment.efl</li>
    <li>enlightenment.enlightenment</li>
    <li>enlightenment.ephoto</li>
    <li>enlightenment.evisum</li>
    <li>enlightenment.rage</li>
    <li>enlightenment.terminology</li>
    <li>evince (gnome.evince)</li>
    <li>evince.dev (gnome.evince.dev)</li>
    <li>evince.devdoc (gnome.evince.devdoc)</li>
    <li>farge</li>
    <li>feh</li>
    <li>feh.doc</li>
    <li>feh.man</li>
    <li>fontpreview</li>
    <li>glom</li>
    <li>glom.dev</li>
    <li>glom.devdoc</li>
    <li>glom.doc</li>
    <li>glom.lib</li>
    <li>gnome.sushi</li>
    <li>hqplayer-desktop</li>
    <li>hqplayer-desktop.doc</li>
    <li>imlib2Full</li>
    <li>imlib2Full.bin</li>
    <li>imlib2Full.dev</li>
    <li>kile</li>
    <li>labplot</li>
    <li>libsForQt5.okular (plasma5Packages.okular)</li>
    <li>libspectre</li>
    <li>manga-cli</li>
    <li>mate.atril</li>
    <li>multilockscreen</li>
    <li>nsxiv</li>
    <li>nsxiv.doc</li>
    <li>nsxiv.man</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>pqiv</li>
    <li>python310Packages.pythonefl</li>
    <li>python310Packages.pythonefl.dist</li>
    <li>python310Packages.pywal</li>
    <li>python310Packages.pywal.dist</li>
    <li>python311Packages.pythonefl</li>
    <li>python311Packages.pythonefl.dist</li>
    <li>pywal (python311Packages.pywal)</li>
    <li>pywal.dist (python311Packages.pywal.dist)</li>
    <li>qiv</li>
    <li>qpdfview</li>
    <li>stylish</li>
    <li>sxiv</li>
    <li>vimPlugins.openscad-nvim</li>
    <li>wpgtk</li>
    <li>wpgtk.dist</li>
    <li>zathura</li>
  </ul>
</details>

**Comment by onemoresuza** [comment]
I've fetched the PR locally and managed to build `manga-cli`. Still don't know
what caused the build failure, but it seems to be unrelated with the PR.

**Review by onemoresuza — APPROVED** [review]

**Pull request merged**
