### PR TITLE
franz: 5.3.3 -> 5.4.1

### PR DESCRIPTION
**Pull request by davidtwco**
###### Motivation for this change
[v5.4.0](https://github.com/meetfranz/franz/releases/tag/v5.4.0) of Franz was released.

I've included a second commit which adds myself as an additional maintainer to this package, as I've submitted a handful of PRs to update this package: #68976, #68899, #68256, #65258 and #62586.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @gnidorah

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Tested with `nix-review pr 71862`

**Comment by gnidorah** [comment]
@davidtwco Could you please also remove me from maintainers? I see this software went on commercial rails with serious limitations in free plan. I dont care it anymore

**Comment by davidtwco** [comment]
> 
> 
> @davidtwco Could you please also remove me from maintainers? I see this software went on commercial rails with serious limitations in free plan. I dont care it anymore

I've updated the PR to do this.

**Comment by gnidorah** [comment]
@davidtwco Thank you!

**Comment by davidtwco** [comment]
Added a commit to upgrade to [Franz 5.4.1](https://github.com/meetfranz/franz/releases/tag/v5.4.1) which has since been released.

**Review by Lassulus — APPROVED** [review]
tested with nix-review

**Pull request merged**
