### PR TITLE
emby: 3.2.60.0 -> 3.2.70.0

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were performed:

- built on NixOS
- found 3.2.70.0 with grep in /nix/store/rrf5cqpbsmq42mwy2zsgab7r7pn44zim-emby-3.2.70.0

### CODE REVIEW

**Comment by ryantm** [comment]
@GrahamcOfBorg build emby

**Comment by mogorman** [comment]
@ryantm this automatic updating of packages is awesome, did you or can you provide some more info about how you have this scripted and if others can help do this to keep all packages in nixos up to date

**Comment by jtojnar** [comment]
@mogorman https://github.com/ryantm/nix-update

**Comment by mogorman** [comment]
very cool thanks @jtojnar for the link

**Comment by ryantm** [comment]
@mogorman I added instructions in the README.md of https://github.com/ryantm/nix-update please open an issue there, if you have trouble!

**Pull request merged**
