### PR TITLE
buildSkawarePackage: pass through extra args

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

This allows things like hooks other than postInstall to be passed
through to mkDerivation, which is very useful when customising or
debugging a package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @pmahoney

### CODE REVIEW

**Comment by Profpatsch** [comment]
Not a fan.

**Comment by alyssais** [comment]
> Not a fan.

Revert if you want.

What do you propose instead?

**Comment by Profpatsch** [comment]
> What do you propose instead?

Thinking about it, maybe it’s the best way

**Comment by alyssais** [comment]
>> What do you propose instead?
>
> Thinking about it, maybe it’s the best way

https://github.com/NixOS/rfcs/pull/58 proposes adding syntax that would
make this a lot nicer.

**Comment by Profpatsch** [comment]
I think I’m gonna revert this, because if you are debugging you can just add the extra argument to `buildSkawarePackage` proper or use `overrideDerivation` to add it after the fact. 

e.g. `outputs` wasn’t added and `meta` has strange semantics now.

**Comment by Profpatsch** [comment]
reverted as part of https://github.com/NixOS/nixpkgs/pull/83162

**Pull request merged**
