### PR TITLE
kubernetes: only build on linux 

### PR DESCRIPTION
**Pull request by zowoq**
###### Motivation for this change

Avoid building the entire kubernetes package on non-linux platforms (also for `kubectl` only linux users).

This could be simplified after we get rid of the addon manager but for now this is seems the easier approach.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Makes sense, LGTM

**Comment by zowoq** [comment]
I've updated this so `pkgs.kubernetes` has a symlink from `pkgs.kubectl` instead of building its own `kubectl`.

**Comment by zowoq** [comment]
@ofborg test kubernetes

**Comment by zowoq** [comment]
@ofborg test kubernetes

**Comment by zowoq** [comment]
For some reason I can't see hydra at the moment so I can't be sure but it is highly unlikely it was caused by this, probably just a flaky build that needs to be restarted, I'll check hydra again in a few hours.

**Comment by anmonteiro** [comment]
Appreciate it. I have no idea where to look in Hydra. Would be lovely if you could share the URL you're looking at.

**Comment by zowoq** [comment]
I usually watch the kubernetes nixos tests at https://hydra.nixos.org/jobset/nixos/trunk-combined/jobs-tab?filter=kubernetes, that should show any build failures as well. Currently it times out for me, not sure if its a problem on my end or not.

**Comment by anmonteiro** [comment]
Also times out for me.

**Comment by zowoq** [comment]
Hydra seems to be offline for maintenance, hopefully should be back up soon.

I rebuilt the derivation and tests without any issues so I'd say it is just a flaky build.

**Comment by anmonteiro** [comment]
Looks like your link is up and Kube has indeed failed to build in the last 3 consecutive runs. Not sure if flakey

**Comment by zowoq** [comment]
It failed once and hasn't been attempted again.

https://hydra.nixos.org/build/168106547

@jonringer @vcunat Could you restart it please?

**Comment by vcunat** [comment]
Restarted.

For hydra.nixos.org privileges I'd probably ask at https://matrix.to/#/#infra:nixos.org

**Comment by anmonteiro** [comment]
It doesn't seem like the build has completed successfully.

**Comment by vcunat** [comment]
I do see it succeeding: https://hydra.nixos.org/build/168106547

**Comment by anmonteiro** [comment]
I'm not very well-versed in Hydra, but looking at this dashboard still shows a failure: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.kubernetes.x86_64-linux

**Comment by vcunat** [comment]
Yes, that's just how Hydra works.  Now I also restarted it, and it should soon get cached from the previously linked build.  (same hash)

**Comment by anmonteiro** [comment]
Thanks for your help!

**Pull request merged**
