### PR TITLE
discord: 0.0.12 -> 0.0.13

### PR DESCRIPTION
**Pull request by ldesgoui**
###### Motivation for this change
Discord still prevents you from using outdated versions

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ldesgoui** [comment]
We probably want backports for this, should I try my hand? 20.03 and 20.09?

**Review by ghost — APPROVED** [review]
Tested, nixpkgs-review checks out.
LGTM.

**Comment by Chiiruno** [comment]
cc @Mic92 for merge

**Comment by SuperSandro2000** [comment]
> We probably want backports for this, should I try my hand? 20.03 and 20.09?

20.03 is EOL.

**Comment by Xe** [comment]
Please add `libdrm` and `mesa` to the libPath or this will fail on launch.

**Comment by ldesgoui** [comment]
> Please add `libdrm` and `mesa` to the libPath or this will fail on launch.

It runs fine for me, what issue are you experiencing?

**Comment by Xe** [comment]
```$ /nix/store/i9v8ym6dkrv71a1zc0v629x9kbdyxg1s-discord-canary-0.0.116/bin/DiscordCanary
/nix/store/i9v8ym6dkrv71a1zc0v629x9kbdyxg1s-discord-canary-0.0.116/bin/DiscordCanary: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```

**Comment by Chiiruno** [comment]
That seems to be a canary issue, and not pursuant to this PR.

-------- Original Message --------

**Comment by ldesgoui** [comment]
> That seems to be a canary issue, and not pursuant to this PR.

`mesa` and `libdrm` definitely become part of the closure in this PR so it kind of is


> ```
> /nix/store/i9v8ym6dkrv71a1zc0v629x9kbdyxg1s-discord-canary-0.0.116/bin/DiscordCanary: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
> ```

Thanks, I'm really not sure why that would be the case, `autoPatchelfHook` properly picks up both `mesa` and `libdrm` and adds it to the RPATH of `opt/Discord/.Discord-wrapped`, which should absolutely make the closure pick it up as well, that's the case for me locally anyways:

**Comment by leo60228** [comment]
For what it's worth, I had the libgbm issue when using the latest `discord/default.nix` with an outdated `discord/base.nix`.

**Review by jonringer — APPROVED** [review]
diff LGTM
gui launches fine

```
1 package built:
discord
```

**Pull request merged**
