### PR TITLE
libdigidoc, libdigidocpp, qdigidoc updates

### PR DESCRIPTION
**Pull request by lukateras**
Alternative to https://github.com/NixOS/nixpkgs/pull/42321. cc @jagajaga @Mic92

### CODE REVIEW

**Comment by Mic92** [comment]
Looks good, compilation error should be fixed though.

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build qdigidoc

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build qdigidoc

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build qdigidoc

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build qdigidoc

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build qdigidoc

**Pull request merged**
