### PR TITLE
ghc, haskell infra: #40642 direct to master

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

#40642 but not to staging so @peti can merge it to `haskell-updates` and then master. [Be sure to merge not rebase or the commits won't be shared with staging.]

@peti I removed the staging merge, and then this merges with master cleanly.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
So I'm seeing build failures w/ghc on master-- has this been confirmed to work (x86_64, non-cross, Linux)?

If so I'll go debug why I'm seeing failures, but wanted to check things are expected to work before starting that adventure xD.

**Comment by dtzWill** [comment]
I posted this on IRC, but for anyone following here:

I've confirmed the failure on another machine :(.  LMK if anyone's *not* seeing it...?

Full log (warning, 16M): https://gist.github.com/dtzWill/e17a89191bb9d5be25ddd5339b99e822
Last 1000 lines (`tail -n1000`): https://gist.github.com/dtzWill/b17d74f7ce81197be86540a529407ba9

**Comment by Ericson2314** [comment]
I built some GHC on mac for sure. Building more now.

**Comment by dtzWill** [comment]
No worries, I have plenty of rebuilds before this become my blocking point xD.  GL sorting it out, thanks for taking a look!

**Comment by peti** [comment]
ghc is broken on `master`: https://hydra.nixos.org/build/74555446

I'll revert this change.

**Pull request merged**
