### PR TITLE
libvirt: Shrink closure by disabling zfs by default

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

I don't think the zfs integration (i.e. direct zvol support) is widely used.

`nix path-info -S` reports `509285216` → `362482320`

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Maybe this should be put into the changelog to not cause any surprises.

**Comment by gebner** [comment]
> I don't think the zfs integration (i.e. direct zvol support) is widely used.

That's not a reason to disable a feature.

Presumably the extra dependencies (like zfs) only make a difference for the libvirtd daemon.  What we should probably have is two packages, `libvirt` (with minimal dependencies), and `libvirtFull` (with all dependencies).  Most packages should depend on `libvirt` (because they only use the library to communicate with the daemon).  The `libvirtd` module should then default to the `libvirtFull` package for the daemon, and this package should be configurable.

If you don't want zfs, you could just set `virtualisation.libvirtd.package = pkgs.libvirt`.

**Comment by lheckemann** [comment]
We use this feature at mayflower, and I also use it for my personal stuff. I'd definitely appreciate it it remained enabled by default (though it wouldn't kill me if it didn't ;) )

That said, this could (and should!) probably be a runtime thing: meson only [seems to use](https://gitlab.com/libvirt/libvirt/-/blob/master/meson.build#L1980-2000) the `zfs` and `zpool` executables, which should generally be obtained from the booted system and _not_ a "hard-coded" version, so that the tools match the kernel module version. This would simultaneously eliminate the path dependency, reducing the closure size, and make it more reliable by matching zfs's expectations more closely.

**Comment by dasJ** [comment]
@lheckemann Is relying on /run a good idea? I doubt this will work on non-NixOS systems

**Comment by lheckemann** [comment]
Indeed it won't. Maybe a nixos-specific patch to try /run/booted-system and fall back to PATH would make sense. I don't currently have the capacity to implement that though.

**Pull request closed without merging**
