### PR TITLE
libimobiledevice updates

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Obscene package versions mostly :)

This should give function to devices with newer IOS versions.

Also #40952 is partially finished (no longer outdated) but they still are without a maintainer.

Testing with new devices would be nice and always kind reviewers :+1:

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build usbmuxd libusbmuxd libimobiledevice ifuse gtkpod

**Review by infinisil — APPROVED** [review]
Yup, still works just fine

**Comment by Infinisil** [comment]
ifuse also works with my iPhone 6 Plus

**Comment by worldofpeace** [comment]
@Infinisil Did you device have like IOS > 11.x?

**Comment by Infinisil** [comment]
@worldofpeace Nah, only 10.3.3 (I don't want to update because it's already very sluggish, the update probably just makes it worse).

If we can't find somebody with 11.x in a few days I say let's just merge it.

**Comment by worldofpeace** [comment]
@Infinisil I tested it with 11.x and it works :+1:

**Review by infinisil — APPROVED** [review]
Nice!

**Pull request merged**
