### PR TITLE
rustfmt: 0.4 -> 0.6

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

Package outdated
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

WIP

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Can someone tell me what happened? :curly_loop:

**Comment by grahamc** [comment]
Yeah, for this build you changed the version built but the sha256 of all its dependencies wasn't updated. The error indicates this:

```
output path ‘/nix/store/s8h9dvj6nx84b79rlcaagd21y5arhdfd-rustfmt-0.6-fetch’ has r:sha256 hash ‘13rrhgzxxx5gwpwvyxw03m5xng9c1xyaycmqpi123ma3ps5822jf’ when ‘1lbcpvp7xhyl96w7jfd18w6py60nwllr93jna5j33zvnip61cpf5’ was expected
```

`1lbcpvp7xhyl96w7jfd18w6py60nwllr93jna5j33zvnip61cpf5` being the out of date dependency sha. When you fix that, add a comment tagging me and I'll merge this ASAP.

**Comment by matthiasbeyer** [comment]
@grahamc Updated, should work now. Please wait for travis, though.

**Comment by grahamc** [comment]
I mean, I can wait if you really want me to. I've built and tested this PR locally though and know it to be good.

**Comment by matthiasbeyer** [comment]
> I've built and tested this PR locally though and know it to be good.

Awesome! Then, I do not care.

**Pull request merged**
