### PR TITLE
maven: 3.9.8 -> 3.9.9

### PR DESCRIPTION
**Pull request by bjornfor**
## Things done

Update to latest 3.x version.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by uncenter** [comment]
Duplicate of #348802, but the diff is the same so whatever 😁 

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 348864`

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>protege</li>
  </ul>
</details>
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>certificate-ripper</li>
    <li>digital</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 9 packages built:</summary>
  <ul>
    <li>bytecode-viewer</li>
    <li>gol</li>
    <li>h2</li>
    <li>h2.doc</li>
    <li>jugglinglab</li>
    <li>kotlin-language-server</li>
    <li>mariadb-connector-java</li>
    <li>quark-goldleaf</li>
    <li>tabula-java</li>
  </ul>
</details>

**Comment by bjornfor** [comment]
Result of `nixpkgs-review pr 348864` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>microsoft-identity-broker</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>apgdiff</li>
    <li>bytecode-viewer</li>
    <li>certificate-ripper</li>
    <li>commafeed</li>
    <li>cryptomator</li>
    <li>dependency-track</li>
    <li>digital</li>
    <li>exificient</li>
    <li>forge-mtg</li>
    <li>gephi</li>
    <li>global-platform-pro</li>
    <li>gol</li>
    <li>h2</li>
    <li>h2.doc</li>
    <li>java-language-server</li>
    <li>jd-cli</li>
    <li>jetbrains.idea-community (jetbrains.idea-community-src)</li>
    <li>jetbrains.idea-community-bin</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.pycharm-community (jetbrains.pycharm-community-src)</li>
    <li>jnr-posix</li>
    <li>joularjx</li>
    <li>jugglinglab</li>
    <li>kotlin-interactive-shell</li>
    <li>kotlin-language-server</li>
    <li>ktfmt</li>
    <li>lemminx</li>
    <li>mariadb-connector-java</li>
    <li>maven (maven3)</li>
    <li>ns-usbloader</li>
    <li>openrefine</li>
    <li>protege</li>
    <li>quark-goldleaf</li>
    <li>runelite</li>
    <li>s3proxy</li>
    <li>scenebuilder</li>
    <li>schemaspy</li>
    <li>slipstream</li>
    <li>sonarlint-ls</li>
    <li>tabula-java</li>
    <li>tika</li>
    <li>vatprism</li>
    <li>verapdf</li>
  </ul>
</details>

**Comment by bjornfor** [comment]
> Duplicate of #348802, but the diff is the same so whatever 😁

It was a race condition :-) I searched github, didn't find a matching PR and started on my own.

> ## `nixpkgs-review` result

I don't have access to aarch64-darwin, but perhaps those failures happen already on the base branch?

**Comment by bjornfor** [comment]
> Result of `nixpkgs-review pr 348864` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:
> 
>     * microsoft-identity-broker

It's a hash mismatch of a .deb file which also happen on the base branch:

```
$ NIXPKGS_ALLOW_UNFREE=1 nix-build -A microsoft-identity-broker
these 2 derivations will be built:
  /nix/store/wz10p968qgwnax383ahyalsb7iwqmi0q-microsoft-identity-broker_2.0.1_amd64.deb.drv
  /nix/store/adyap53k7xm8l266sfrvnd57yf95yjf5-microsoft-identity-broker-2.0.1.drv
this path will be fetched (0.24 MiB download, 0.27 MiB unpacked):
  /nix/store/sxlv9s1q909h9fskwbi8rrld2zf6r7g5-jnr-posix-3.1.18
copying path '/nix/store/sxlv9s1q909h9fskwbi8rrld2zf6r7g5-jnr-posix-3.1.18' from 'https://cache.nixos.org'...
building '/nix/store/wz10p968qgwnax383ahyalsb7iwqmi0q-microsoft-identity-broker_2.0.1_amd64.deb.drv'...

trying https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/microsoft-identity-broker/microsoft-identity-broker_2.0.1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80.4M  100 80.4M    0     0  43.0M      0  0:00:01  0:00:01 --:--:-- 43.0M
error: hash mismatch in fixed-output derivation '/nix/store/wz10p968qgwnax383ahyalsb7iwqmi0q-microsoft-identity-broker_2.0.1_amd64.deb.drv':
         specified: sha256-O9zbImSWMrRsaOozj5PsCRvQ3UsaJzLfoTohmLZvLkM=
            got:    sha256-I4Q6ucT6ps8/QGiQTNbMXcKxq6UMcuwJ0Prcqvov56M=
error: 1 dependencies of derivation '/nix/store/adyap53k7xm8l266sfrvnd57yf95yjf5-microsoft-identity-broker-2.0.1.drv' failed to build
```

**Pull request merged**
