### PR TITLE
Brave: enable Darwin build

### PR DESCRIPTION
**Pull request by pniedzwiedzinski**
###### Motivation for this change
I used Brave a lot on my linux machine, but as I switched to Mac I could not get it from Nixpkgs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please fix the merge conflict and squash the commits together.

**Comment by siraben** [comment]
@pniedzwiedzinski poke, it'd be nice to have more graphical applications from Nixpkgs build on macOS.

**Comment by stellarhoof** [comment]
Not stale

**Comment by SuperSandro2000** [comment]
> Not stale

It is stale because the merge conflict did not get resolve in over 3 months now.

**Review by Janik-Haag — COMMENTED** [review]
@pniedzwiedzinski are you still interested in getting this merged? I will close this in a few weeks if you aren't.

**Pull request closed without merging**
