### PR TITLE
mu: 1.8.14 -> 1.10.3

### PR DESCRIPTION
**Pull request by chvp**
###### Description of changes

https://github.com/djcb/mu/releases/tag/v1.10.0  
https://github.com/djcb/mu/releases/tag/v1.10.1  
https://github.com/djcb/mu/releases/tag/v1.10.2  
https://github.com/djcb/mu/releases/tag/v1.10.3  

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Alizter** [comment]
Result of `nixpkgs-review pr 223229` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>lbdb</li>
    <li>mu</li>
  </ul>
</details>

**Comment by peterhoeg** [comment]
Unless there's a particular strong reason to do this right away, I'd like to hold off a little as we need to wait for some of the tooling around it to catch up with the changes. The last round of function renaming broke quite a few people's setups.

**Comment by chvp** [comment]
No other reason than to be up-to-date.

**Comment by jian-lin** [comment]
I noticed that the VERSION of info manual is not corrected.

```
File: mu4e.info,  Node: Top,  Next: Introduction,  Up: (dir)

mu4e manual for version {No value for `VERSION'}
************************************************

   Welcome to mu4e!

   mu4e (mu-for-emacs) is an e-mail client for GNU Emacs version 26.3 or
newer, built on top of the mu(1) e-mail search engine.  mu4e is
optimized for quickly processing large amounts of e-mail.

```

**Comment by chvp** [comment]
> I noticed that the VERSION of info manual is not correct.

Fixed this in my latest commit. In https://github.com/NixOS/nixpkgs/commit/0e1a1748f4ad the texinfo version was set to texinfo 4 to (apparently) fix the build, but this was never removed as time went on.

**Comment by peterhoeg** [comment]
mu4e doesn't play nice with `evil-collection` which breaks things for me with this change (PR here: https://github.com/emacs-evil/evil-collection/pull/720)

I'm very much in favour of waiting until that's fixed.

**Comment by chvp** [comment]
Sure, that's fine by me. I have been using this for 2 weeks with evil-collection with the following modifications (if anyone else wants to test it out):
```elisp
(defun mu4e--main-action-str (title cmd) "")
(defalias 'mu4e~view-quit-buffer 'mu4e-view-quit)
(remove-hook 'mu4e-main-mode-hook 'evil-collection-mu4e-update-main-view)
```

**Comment by jian-lin** [comment]
> mu4e doesn't play nice with evil-collection which breaks things for me with this change (PR here: https://github.com/emacs-evil/evil-collection/pull/720)

I do not use evil, but it looks they have fixed it in another PR https://github.com/emacs-evil/evil-collection/pull/729.

Could we merge this now?

**Pull request merged**
