### PR TITLE
fprintd: 1.92.0 -> 1.94.1

### LINKED ISSUE #153240: fprintd 1.92.0 fails to build on latest unstable
### Describe the bug

Package fprintd doesn't build with the latest unstable (currently on commit https://github.com/NixOS/nixpkgs/commit/5b091d4fbe3b7b7493c3b46fe0842e4b30ea24b3).

### Steps To Reproduce

With the following configuration, using ThinkPad X1 Carbon 7th gen:

```nix
security = {
  pam = {
    services = {
      login.fprintAuth = true;
      swaylock-effects.fprintAuth = true;
      sudo.fprintAuth = true;
      system-local-login.fprintAuth = true;
      su.fprintAuth = true;
    };
  };
};

services.fprintd.enable = true;
```

After a `nix flake update` to the latest unstable, the compilation gives an error:

```
error: builder for '/nix/store/8gz3dz8h1yais5vk129xm0wnpln6n0wy-fprintd-1.92.0.drv' failed with exit code 1;
       last 10 log lines:
       > Expected Fail:      0
       > Fail:               0
       > Unexpected Pass:    0
       > Skipped:            0
       > Timeout:            11
       >
       > Full log written to /build/source/build/meson-logs/testlog.txt
       > FAILED: meson-test
       > /nix/store/cm0di021fzm7kay4q262p23j8bnp5f8z-meson-0.57.1/bin/meson test --no-rebuild --print-errorlogs
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/8gz3dz8h1yais5vk129xm0wnpln6n0wy-fprintd-1.92.0.drv'.
error: 1 dependencies of derivation '/nix/store/pg6gk20xxh6hm5pa1a64i46gaq43iq6x-chfn.pam.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9xxjcr38fiywsmp6ak1b4m6ilcqfdq8y-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j07ga9k17agqvlw0gvy9yr7zx80jan2r-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/34yadjxgqpwglaxhqmnnf9rjcbh9n6g6-nixos-system-purrpurr-22.05.20211230.5b091d4.drv' failed to build
```

### Notify maintainers

@abbradar @grahamc

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.10, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-21.11pre294109.fbfb79400a0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/153240.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Didn't test it on a physical scanner yet, will try soon.

### CODE REVIEW

**Comment by abbradar** [comment]
Apparently my current laptop needs additional unpackaged drivers for fprintd to work, which I don't have time to work on. @pimeys can you try this and report if it works?

**Comment by pimeys** [comment]
@abbradar yes! Right after I finish my work and get back to my laptop.

**Comment by pimeys** [comment]
Set my flake to take `fprintd` and `libfprint` from your fork. Compiles successfully, and after a reboot I can login with my fingerprint, and I can also `sudo ls` which asks my fingerprint, and after giving it it runs `ls` successfully.

Seems to work. Thank you.

**Comment by abbradar** [comment]
Thanks for the testing!

**Comment by hacker1024** [comment]
`fprintd-tod` is still on 1.90, and failing to build.

**Pull request merged**
