### PR TITLE
php.extensions.mysqlnd: Fix compression support

### LINKED ISSUE #89226: phpExtensions.mysqlnd: compression not supported
After PR #83896 phpExtensions.mysqlnd not supported compression.
Checked with `phpinfo();`
```
Compression - not supported
```
@etu

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
`HAVE_ZLIB` has to be defined in `mysqlnd.h` for compression support to be turned on, but the `configure` script doesn't actually define it even when `zlib` is available.

Fixes #89226.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Possibly related to https://github.com/php/php-src/commit/ee4295b4ce421003c2e1d2af98066826deb23319

**Comment by Izorkin** [comment]
I disabled the `zlib` extension, now in `mysqlnd` `Compression supported` does not change to `Compression - not supported`
I think there should be a dynamic check of the zlib extension.

**Comment by talyz** [comment]
@jtojnar Yes, that seems relevant - it just didn't go all the way, likely because it's not needed when building the extension as a part of PHP...

@Izorkin Well, the `mysqlnd` extension doesn't use the `zlib` extension, but links to `zlib` on its own, so that's expected behavior.

**Comment by jtojnar** [comment]
@talyz Not sure what you mean, `PKG_CHECK_MODULES` should set `HAVE_ZLIB` variable.

**Comment by talyz** [comment]
@jtojnar Oh, maybe it should. That's not how they set it in the `zlib` module (they use `AC_DEFINE(HAVE_ZLIB,1,[ ])` there), so I figured that's what they would have done here too; or just remove `HAVE_ZLIB`, since it's explicitly checked for anyway :)

**Comment by jtojnar** [comment]
Yeah, that seems to work: https://github.com/php/php-src/pull/5655


```patch
diff --git a/pkgs/top-level/php-packages.nix b/pkgs/top-level/php-packages.nix
index 82c68c2127d..63243266702 100644
--- a/pkgs/top-level/php-packages.nix
+++ b/pkgs/top-level/php-packages.nix
@@ -1,4 +1,4 @@
-{ stdenv, lib, pkgs, fetchgit, php, autoconf, pkgconfig, re2c
+{ stdenv, lib, pkgs, fetchgit, fetchpatch, php, autoconf, pkgconfig, re2c
 , gettext, bzip2, curl, libxml2, openssl, gmp, icu, oniguruma, libsodium
 , html-tidy, libzip, zlib, pcre, pcre2, libxslt, aspell, openldap, cyrus_sasl
 , uwimap, pam, libiconv, enchant1, libXpm, gd, libwebp, libjpeg, libpng
@@ -983,14 +983,14 @@ in
         # The configure script doesn't correctly add library link
         # flags, so we add them to the variable used by the Makefile
         # when linking.
-        MYSQLND_SHARED_LIBADD = "-lssl -lcrypto -lz";
+        MYSQLND_SHARED_LIBADD = "-lssl -lcrypto";
         # The configure script builds a config.h which is never
         # included. Let's include it in the main header file
         # included by all .c-files.
         patches = [
           (pkgs.writeText "mysqlnd_config.patch" ''
-            --- a/mysqlnd.h
-            +++ b/mysqlnd.h
+            --- a/ext/mysqlnd/mysqlnd.h
+            +++ b/ext/mysqlnd/mysqlnd.h
             @@ -1,3 +1,6 @@
             +#ifdef HAVE_CONFIG_H
             +#include "config.h"
@@ -999,7 +999,20 @@ in
                +----------------------------------------------------------------------+
                | Copyright (c) The PHP Group                                          |
           '')
+        ] ++ lib.optionals (!lib.versionOlder php.version "7.4") [
+          # Fix compression support
+          # https://github.com/php/php-src/pull/5655
+          (fetchpatch {
+            url = "https://github.com/php/php-src/commit/fd852e5896c506a501642b8cd6c5620bfa0cbd36.patch";
+            sha256 = "xhmEAzulTmcfXSIYIFHWHnq3s4zw4nKhwXJgRNMQ3Rk=";
+          })
         ];
+
+        # mkExtension sets sourceRoot to the extension directory
+        # so we need this in order to avoid fiddling with patches.
+        prePatch = ''pushd ../..'';
+        postPatch = ''popd'';
+
         postPhpize = lib.optionalString (lib.versionOlder php.version "7.4") ''
           substituteInPlace configure --replace '$OPENSSL_LIBDIR' '${openssl}/lib' \
                                       --replace '$OPENSSL_INCDIR' '${openssl.dev}/include'
```

```ShellSession
$ nix shell -f . 'php' -L -c php -r 'phpinfo();' | grep Compression
Compression => supported
```

**Comment by talyz** [comment]
@jtojnar I changed the patching behavior, so that `mkExtension` always patches from the PHP source root, like you did in your patch. I kept my patch, though, since it works for all versions of PHP, not only 7.4. I also feel like removing `HAVE_ZLIB` might be the way to go for upstream as well, since it's probably just a leftover from before php/php-src@ee4295b - if you specify that you want compression support enabled, the extension won't build without `zlib`, since the `PKG_CHECK_MODULES` check will fail...

**Review by jtojnar — APPROVED** [review]

**Comment by Izorkin** [comment]
Found in build log:
```
checking whether to enable mysqlnd... yes, shared
checking whether to disable compressed protocol support in mysqlnd... yes
```
By default, compression is disabled?

**Comment by Izorkin** [comment]
Checking with `configureFlags = [ "--disable-mysqlnd-compression-support" ];`
```
checking whether to enable mysqlnd... yes, shared
checking whether to disable compressed protocol support in mysqlnd... no
```
Default enable compression support.

**Review by Izorkin — APPROVED** [review]

**Comment by jtojnar** [comment]
> I kept my patch, though, since it works for all versions of PHP, not only 7.4. I also feel like removing `HAVE_ZLIB` might be the way to go for upstream as well

Upstream agrees, could you try to PR your patch then?

**Comment by talyz** [comment]
@Izorkin Yeah, I was confused by that too. Seems like it's just the configure output that's being flipped, though.

@jtojnar Done! :) php/php-src#5658

**Pull request merged**
