### PR TITLE
mangohud: use vendored vulkan-headers to fix build

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

This isn't great but what can you do.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Result of `nixpkgs-review pr 225985` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>heroic</li>
    <li>mangohud</li>
    <li>mangohud.doc</li>
    <li>mangohud.man</li>
  </ul>
</details>

**Review by kira-bruneau — APPROVED** [review]
Thanks @K900!! I can only see this being a problem if there's portability issues between different headers - but I assume the vulkan ABI is stable.

We can't guarantee what loader is used by the app anyway, so MangoHud already has to assume its stable (also thanks noticing we don't actually need `vulkan-loader` as a dependency!)

**Comment by kira-bruneau** [comment]
It also looks like there was an upstream commit to disable using the system vulkan headers, so looks like this is the right approach: https://github.com/flightlessmango/MangoHud/commit/bc282cf300ed5b6831177cf3e6753bc20f48e942

**Comment by Krutonium** [comment]
Even pulling in `mangohud` from Master it continues to be broken. https://gitea.krutonium.ca/Krutonium/NixOS/src/commit/c8170692e850b4a1dad72705cfdfcdb003a1f7f8/user/krutonium-hm-extras/packages.nix#L173-L177

```
error: builder for '/nix/store/v3hjcx3zkk0jafyrdrz4wl0yhziilahf-mangohud-0.6.8.drv' failed with exit code 1;
       last 10 log lines:
       >  2004 | extern "C" VK_LAYER_EXPORT VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL overlay_GetDeviceProcAddr(VkDevice dev,
       >       |            ^~~~~~~~~~~~~~~
       > ../src/vulkan.cpp:2018:12: error: 'VK_LAYER_EXPORT' does not name a type
       >  2018 | extern "C" VK_LAYER_EXPORT VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL overlay_GetInstanceProcAddr(VkInstance instance,
       >       |            ^~~~~~~~~~~~~~~
       > ../src/vulkan.cpp:1987:14: warning: 'void* find_ptr(const char*)' defined but not used [-Wunused-function]
       >  1987 | static void *find_ptr(const char *name)
       >       |              ^~~~~~~~
       > [33/66] Compiling C++ object src/libMangoHud.so.p/file_utils.cpp.o
       > ninja: build stopped: subcommand failed.
```

**Comment by kira-bruneau** [comment]
@Krutonium It seems to be building for me from your flake:

```
nix build --rebuild --print-out-paths --inputs-from git+https://gitea.krutonium.ca/Krutonium/NixOS.git nixpkgs-master#mangohud
/nix/store/97iii8iicfsgaa8hcdvx8fdvpls7k9mv-mangohud-0.6.8-man
/nix/store/szharnvp56vmmqqj2h79p47547263bxp-mangohud-0.6.8
```

It's also building on hydra now: https://hydra.nixos.org/job/nixpkgs/trunk/mangohud.x86_64-linux/all

**Comment by Krutonium** [comment]
:\ It's still not building for me, with that same error. 

image

I did this because I was curious (I tried disabling Mangohud) why it was still trying and now I am quite confused as to why fontconfig is pulling in MangoHud o.O

**Comment by Krutonium** [comment]
Welp, 8 hours later, now it works. I don't even. Nothing on my end has changed.

**Pull request merged**
