### PR TITLE
neovim-remote: disable tests

### PR DESCRIPTION
**Pull request by tssm**
###### Description of changes
The only enabled test started to fail with write errors. Setting `HOME=$TMPDIR` works, but then it fails the same way than the disabled ones
###### Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
with master c3fafea4edcfed02a37f5f9dfa36c871d1b00e8d , it builds ok for me (linux), what's the error ?

**Comment by tssm** [comment]
Huh, maybe it's a macOS only issue:

```
----------------------------- Captured stdout call -----------------------------
[!] Can't connect to: pytest_socket_20a44d4e-a32d-4e56-b024-9432907def1d

    The server (nvim) and client (nvr) have to use the same address.

    Server:

        Specify the server address when starting nvim:

        $ nvim --listen pytest_socket_20a44d4e-a32d-4e56-b024-9432907def1d

        Use `:echo v:servername` to verify the address.

        Alternatively, run nvr without arguments. It defaults to
        starting a new nvim process with the server name set to
        "/tmp/nvimsocket".

        Security: When using an Unix domain socket, that socket should
        have proper permissions so that it is only accessible by your
        user.

    Client:

        Expose $NVIM_LISTEN_ADDRESS (obsolete in nvim but still
        supported by nvr) to the environment before using nvr or use
        its --servername option. If neither is given, nvr assumes
        "/tmp/nvimsocket".

        $ NVIM_LISTEN_ADDRESS=pytest_socket_20a44d4e-a32d-4e56-b024-9432907def1d nvr file1 file2
        $ nvr --servername pytest_socket_20a44d4e-a32d-4e56-b024-9432907def1d file1 file2
        $ nvr --servername 127.0.0.1:6789 file1 file2

    Use -s to suppress this message.

----------------------------- Captured stderr call -----------------------------
Error detected while processing function <SNR>14_LoadRemotePlugins[5]..<SNR>14_GetManifest[1]..<SNR>14_GetManifestPath:
line   10:
E739: Cannot create directory /homeless-shelter: read-only file system
```

When `HOME` is set to `TMPDIR` the last part is not shown, but it still with `Can't connect to: pytest_socket_20a44d4e-a32d-4e56-b024-9432907def1d` (as the already disabled tests do)

**Comment by Mindavi** [comment]
Maybe change to doCheck = !stdenv.isDarwin instead.

**Comment by tssm** [comment]
Done 👍

**Pull request merged**
