### PR TITLE
python3Packages.numpy: 1.20.3 -> 1.21.1

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/numpy/numpy/releases/tag/v1.21.1
https://github.com/numpy/numpy/releases/tag/v1.21.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by veprbl** [comment]
@GrahamcOfBorg build python38Packages.numpy python39Packages.numpy

**Comment by SuperSandro2000** [comment]
> @GrahamcOfBorg build python38Packages.numpy python39Packages.numpy

I build them and they build successful.

**Comment by risicle** [comment]
Failure on macos 10.15:

**Comment by risicle** [comment]
Some brief investigation suggests it was added in clang 8. I wonder if https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/distutils/checks/extra_avx512dq_mask.c is not doing its job properly.

**Comment by risicle** [comment]
Sure enough if we replace the line https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/src/common/simd/avx512/conversion.h#L109 with an `#error ...` declaration it fails there, so it looks like `NPY_HAVE_AVX512BW_MASK` is being set true for clang7 even though it definitely shouldn't be.

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 132754` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python38Packages.numpy</li>
    <li>python39Packages.numpy</li>
  </ul>
</details>

**Comment by risicle** [comment]
@veprbl nice! Is this something we want to conditionally set for clang only though?

**Comment by veprbl** [comment]
> @veprbl nice! Is this something we want to conditionally set for clang only though? (p.s. fixes it for me, macos 10.15)

I had that thought, but it doesn't seem to be worth it to run into issues like this.

**Pull request merged**
