### PR TITLE
python38Packages.clifford: fix broken hash

### PR DESCRIPTION
**Pull request by rmcgibbo**
###### Motivation for this change
It looks like I accidentally messed this hash up.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rmcgibbo** [comment]
/marvin opt-in
/status needs_reviewer

This should be a simple merge. The hash is just wrong, because of a mistake on my end in a previous PR.

**Review by cole-h — APPROVED** [review]

**Review by cole-h — CHANGES_REQUESTED** [review]
(I didn't notice that the builds failed until after I approved... Oops.)

Though this is covered in #108799, I feel that it's better to get this in sooner rather than later.

That said, could you also add the stuff from [`cc6bd03` (#108799)](https://github.com/NixOS/nixpkgs/pull/108799/commits/cc6bd032fcc544247494ec0941194f98c1a04f38) that fixes the tests and credits @SuperSandro2000 (by adding `Co-authored-by: Sandro Jäckel <sandro.jaeckel@gmail.com>`)?

**Comment by SuperSandro2000** [comment]
> Though this is covered in #108799, I feel that it's better to get this in sooner rather than later.

Those PRs are just collections of things I noticed over several days because I am to lazy to create a PR for each of those.

> That said, could you also add the stuff from [`cc6bd03` (#108799)](https://github.com/NixOS/nixpkgs/pull/108799/commits/cc6bd032fcc544247494ec0941194f98c1a04f38) that fixes the tests and credits @SuperSandro2000 (by adding `Co-authored-by: Sandro Jäckel <sandro.jaeckel@gmail.com>`)?

Not necessary if you cherry-pick them but this can also wait until the PR gets merged.

**Comment by rmcgibbo** [comment]
Okay, I added your improvements to disabledTests, Sandro, and force-pushed.

**Review by cole-h — APPROVED** [review]
Diff LGTM.

---

Result of `nixpkgs-review pr 108083` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.clifford</li>
    <li>python38Packages.clifford</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@rmcgibbo please solve the merge conflict.

**Comment by rmcgibbo** [comment]
You already fixed the issue by merging #108799, so closing.

**Pull request closed without merging**
