### PR TITLE
abseil-cpp: 20240116.2 -> 20240722.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/abseil/abseil-cpp/releases/tag/20240722.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
@ofborg build abseil-cpp

**Comment by GaetanLepage** [comment]
I succesfully built `abseil-pp` on all 4 architectures.

**Comment by SuperSandro2000** [comment]
@ofborg build telegram-desktop ycmd libreoffice protobuf

**Comment by philiptaron** [comment]
The pattern of `abseil-cpp` pinning and lack of pinning makes no sense to me. 🙂 

I spent a lot of CPU cycles and disk space building stuff. I don't think I found anything that doesn't build due to this patch, but it's staging: there's a lot of noise.

**Comment by SuperSandro2000** [comment]
> The pattern of `abseil-cpp` pinning and lack of pinning makes no sense to me. 🙂

It is basically: if things break because they do major changes we pin an older version.

**Comment by mweinelt** [comment]
I think this broke onnxruntime, but downgrading it to 202401 does not fix it and gtest does not consume abseil-cpp, so I'm not sure where to apply a fix.

```
onnxruntime> In file included from /nix/store/b98gmgf0hv1fmwk6sff5q316mpd8h169-source/googletest/include/gtest/gtest-assertion-result.h:46,
onnxruntime>                  from /nix/store/b98gmgf0hv1fmwk6sff5q316mpd8h169-source/googletest/include/gtest/gtest.h:64,
onnxruntime>                  from /build/source/onnxruntime/test/util/file_util.cc:3:
onnxruntime> /nix/store/b98gmgf0hv1fmwk6sff5q316mpd8h169-source/googletest/include/gtest/gtest-message.h:62:10: fatal error: absl/strings/internal/has_absl_stringify.h: No such file or directory
onnxruntime>    62 | #include "absl/strings/internal/has_absl_stringify.h"
onnxruntime>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
onnxruntime> compilation terminated.
onnxruntime> make[2]: *** [CMakeFiles/onnxruntime_test_utils.dir/build.make:104: CMakeFiles/onnxruntime_test_utils.dir/build/source/onnxruntime/test/util/file_util.cc.o] Error 1
onnxruntime> make[2]: *** Waiting for unfinished jobs....

**Comment by SuperSandro2000** [comment]
> gtest does not consume abseil-cpp

It does optionally https://github.com/google/googletest/blob/main/googletest/include/gtest/gtest-message.h#L59-L62

**Comment by mweinelt** [comment]
Not in our package, so?

**Comment by SuperSandro2000** [comment]
We are using both the compiled variant and the source and since we build onnxruntime I think it is configuring gtest with abseil https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/onnxruntime/default.nix#L184-L187

I can't test this right now though...

**Comment by mweinelt** [comment]
But rolling back abseil to 202401 in onnxruntime doesn't fix the build.

**Pull request merged**
