### PR TITLE
AWS C/C++ library bumps

### PR DESCRIPTION
**Pull request by r-burns**
Bumping aws-c-* collection, s2n-tls, and aws-crt-cpp to the latest versions.

###### Motivation for this change

These packages are all highly interdependent, and breaking changes in one can require updates in lockstep, so it makes sense to bundle these bumps into a single PR.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
I can't finish a nixpkgs-review because of https://github.com/NixOS/nixpkgs/issues/160289 but this seems to be working well. The only failures I noticed are already broken python packages.

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 160281` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.discover</li>
    <li>libsForQt514.discover</li>
    <li>nixui</li>
    <li>ovftool</li>
  </ul>
</details>
<details>
  <summary>3 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>nix-doc</li>
    <li>nix-plugins</li>
    <li>python310Packages.tokenizers</li>
    <li>python310Packages.transformers</li>
    <li>streamlit</li>
  </ul>
</details>
<details>
  <summary>121 packages built:</summary>
  <ul>
    <li>arrow-cpp</li>
    <li>aws-c-auth</li>
    <li>aws-c-cal</li>
    <li>aws-c-common</li>
    <li>aws-c-compression</li>
    <li>aws-c-event-stream</li>
    <li>aws-c-http</li>
    <li>aws-c-io</li>
    <li>aws-c-mqtt</li>
    <li>aws-c-s3</li>
    <li>aws-c-sdkutils</li>
    <li>aws-checksums</li>
    <li>aws-crt-cpp</li>
    <li>aws-sdk-cpp</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cached-nix-shell</li>
    <li>cachix</li>
    <li>comma</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>dydisnix</li>
    <li>fusionInventory</li>
    <li>gnome.gnome-packagekit</li>
    <li>gnome.gnome-software</li>
    <li>simple-scan (gnome.simple-scan)</li>
    <li>go2nix</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>haskellPackages.hercules-ci-cli</li>
    <li>haskellPackages.hercules-ci-cnix-expr</li>
    <li>haskellPackages.hercules-ci-cnix-store</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.nvfetcher</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hci</li>
    <li>hercules-ci-agent</li>
    <li>home-manager</li>
    <li>hubstaff</li>
    <li>hydra-unstable</li>
    <li>libnixxml</li>
    <li>libsForQt5.discover (libsForQt515.discover ,plasma5Packages.discover)</li>
    <li>libsForQt5.packagekit-qt (libsForQt515.packagekit-qt ,plasma5Packages.packagekit-qt)</li>
    <li>libsForQt512.packagekit-qt</li>
    <li>libsForQt514.packagekit-qt</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>nix (nixVersions.nix_2_6 ,nixVersions.stable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-du</li>
    <li>nix-eval-jobs</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-simple-deploy</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixVersions.nix_2_3</li>
    <li>nixVersions.nix_2_4</li>
    <li>nixVersions.nix_2_5</li>
    <li>nixVersions.unstable</li>
    <li>nixos-generators</li>
    <li>nixos-option</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>nvfetcher</li>
    <li>packagekit</li>
    <li>pantheon.appcenter</li>
    <li>pantheon.elementary-onboarding</li>
    <li>parquet-tools</li>
    <li>prefetch-yarn-deps</li>
    <li>python310Packages.datafusion</li>
    <li>python310Packages.datasets</li>
    <li>python310Packages.google-cloud-bigquery</li>
    <li>python310Packages.ibis-framework</li>
    <li>python310Packages.nix-kernel</li>
    <li>python310Packages.nixpkgs</li>
    <li>python310Packages.pyarrow</li>
    <li>python310Packages.pythonix</li>
    <li>python310Packages.snowflake-connector-python</li>
    <li>python310Packages.snowflake-sqlalchemy</li>
    <li>python39Packages.apache-beam</li>
    <li>python39Packages.datafusion</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.google-cloud-bigquery</li>
    <li>python39Packages.ibis-framework</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.intake-parquet</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pyarrow</li>
    <li>python39Packages.pythonix</li>
    <li>python39Packages.snowflake-connector-python</li>
    <li>python39Packages.snowflake-sqlalchemy</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.tensorflow-datasets</li>
    <li>python39Packages.tokenizers</li>
    <li>python39Packages.transformers</li>
    <li>rnix-lsp</li>
    <li>s2n-tls</li>
    <li>system-config-printer</li>
    <li>terranix</li>
    <li>tests.trivial-builders.references</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
    <li>yarn2nix</li>
  </ul>
</details>

**Comment by r-burns** [comment]
Nice, thanks for the proper review. This has been up for a while and seems to be good to go so I'll plan to merge in 24 hours if no further reviews

**Comment by vcunat** [comment]
I see aws-c-common breaking on x86_64-darwin: https://hydra.nixos.org/job/nixpkgs/trunk/aws-c-common.x86_64-darwin

That's a blocker for the `nixpkgs-unstable` channel.

**Comment by Artturin** [comment]
Looks like it worked 20 days ago https://github.com/NixOS/nixpkgs/runs/5224243299

**Comment by vcunat** [comment]
The message is suspicious. The file exists (in cache.nixos.org): `/nix/store/hnsbw22x8djbq0p70m2llq4qb3gbwmmi-ncurses-6.3/lib/libncursesw.6.dylib`

**Comment by vcunat** [comment]
It succeeded on Hydra, after some more issues with the farm.  So I'll assume that this PR wasn't at fault.

**Pull request merged**
