### PR TITLE
openjdk11: add src.zip for IDEs

### PR DESCRIPTION
**Pull request by svalaskevicius**
#### Motivation for this change

IDEs use the provided src.zip to navigate the java codebase.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by svalaskevicius** [comment]
the resulting jdk is bigger... by 64M but more usable now for development... it was part of jdk8 but not for 11

**Comment by gebner** [comment]
It's already there in the `lib/openjdk/lib` directory:
```
-r--r--r-- 2 root root 62M Jan  1  1970 /nix/store/0g6r8xlf5fshi23f64mrzabx3s042xaz-openjdk-11.0.8+10/lib/openjdk/lib/src.zip
```

We could add an extra symlink (without size increase).  But I believe you can also set intellij to use `../lib/openjdk` as java home.

**Comment by svalaskevicius** [comment]
Hi, I'm not using Intellij :) plus it's nice when things are in places where the tools look for them (in this case I'm using scala metals) 

A symlink could work too, I didnt see it in another directory.. although I need to check again to be sure..

**Comment by svalaskevicius** [comment]
@gebner I've updated to use a symlink, thanks :)

**Comment by gebner** [comment]
Does metals work out-of-the-box now?

Could you also add the symlink to openjdk14, please?

**Comment by svalaskevicius** [comment]
@gebner  yes, it does seem to work fine :) 

also added to openjdk14, but unable to test if metals works with it as it is limited to java 11 atm. I did check the symlink though and it was resolving.

**Pull request merged**
