### PR TITLE
nixos/xserver: refactor/fix xml tags for keyboard layout overrides

### PR DESCRIPTION
**Pull request by dasj19**
###### Motivation for this change

With the current XML tags there is an issue when building with a custom keyboard.
As described here: https://github.com/NixOS/nixpkgs/pull/47764#issuecomment-521997293 the description of the new keyboard layout will be missing in the built file: xkeyboard-config-2.27/share/X11/xkb/rules/evdev.lst

@rnhmjoj explains that this broke when xkb dropped intltool ... https://github.com/NixOS/nixpkgs/pull/47764#issuecomment-523237183

###### Things done

I built with `https://github.com/NixOS/nixpkgs/pull/47764#issuecomment-523237183` and checked the output in xkeyboard-config-2.27/share/X11/xkb/rules/evdev.lst

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @rnhmjoj

### CODE REVIEW

**Review by rnhmjoj — APPROVED** [review]
Thank you.

**Comment by worldofpeace** [comment]
Looks good, @dasj19 can you make commit msg the title of your PR? (and with a summary in the body)

**Comment by dasj19** [comment]
@worldofpeace I just did that with `git commit --amend` ... hope I did not mess anything up, this is my first contribution to this project.

**Comment by rnhmjoj** [comment]
@dasj19: in general you should use `git rebase -i`: it can squash commits into a single one, rearrange or change the commit title.

**Comment by dasj19** [comment]
closed as https://github.com/NixOS/nixpkgs/pull/68310 was merged, and it contained the same changes I was proposing here

**Pull request closed without merging**
