### PR TITLE
Upgrade md5 and sha1 to sha256 across Python

### PR DESCRIPTION
**Pull request by grahamc**
###### Things done:

(the following are in progress)
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [ ] Built on platform(s): NixOS / OSX / Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grahamc** [comment]
99% sure this should be tagged as mass rebuild.

**Comment by domenkozar** [comment]
@grahamc did you test all this?

**Comment by grahamc** [comment]
Absolutely not!

:smile: 

 The way I did the update was downloaded the package, asserted the md5sum matched the existing sum, and then calculated the sha256 to replace it.

I'm running `nox-review pr 13845` to make sure they build, and I'm assuming that'll be done sometime next week... ;)

This package upgrade: https://github.com/grahamc/nixpkgs/commit/53d31634ed5a4f949f661f3999333f6a1ea5ca71 is only used by https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python-packages.nix#L23750-L23775, which hasn't been updated since 2014.

**Comment by domenkozar** [comment]
Merging , @grahamc do report if that nox-review finishes so we catch any errors.

**Pull request merged**
