### PR TITLE
Adds Coq contribs

### PR DESCRIPTION
**Pull request by vbgl**
About 160 Coq libraries.

### CODE REVIEW

**Comment by vcunat** [comment]
- The hashes don't match (anymore). Is there a more stable way of downloading them?
- I don't see why you add new packages that are marked as broken.

**Comment by vbgl** [comment]
Thanks for your review.

Changing hashes: I filed a bug upstream but don’t expect much from it; I’m trying to use `fetchzip` since it’s just about timestamps, but it’s not completely satisfying yet (see #5851).

Broken packages: the file `all.nix` includes everything from [this webpage](http://www.lix.polytechnique.fr/coq/pylons/coq/pylons/contribs/list/v8.4). Some of the listed packages are actually broken, or I don’t know how to build them. You are right: it might be better not to include them in the first place.

**Comment by vcunat** [comment]
@vbgl: as a work-around, you can do it without ``nix-prefetch-zip``: just put in ``fetchzip`` with any valid hashes (incorrect ones), and then try to build. It will tell you the correct hashes when the build fails.

**Comment by vcunat** [comment]
Unless there's the same problem in ``fetchzip`` itself.

**Comment by vbgl** [comment]
Hashes should be correct and reliable now, thanks to `fetchzip`.

**Comment by vcunat** [comment]
Pushed. Travis failed on one package, but I can't reproduce that. Perhaps it was some hidden timeout (it just says "killed").

**Pull request closed without merging**
