### PR TITLE
[backport] spectral: 2018-09-24 -> 2019-03-03

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
I think after the qt 5.12 update the program stopped working due to the qml path problem.
This update fixes the issue so it should be backported.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change (none)
- [x] Tested execution of all binary files
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by timokau — APPROVED** [review]
Can only improve things since the package currently doesn't work at all. Thank you!

**Review by timokau — CHANGES_REQUESTED** [review]
Missed the darwin failure. This [is apparently already the case on master](https://hydra.nixos.org/job/nixpkgs/trunk/spectral.x86_64-darwin), so it should be sufficient to restrict the `platforms` to linux.

**Comment by rnhmjoj** [comment]
@timokau Done.

**Review by timokau — APPROVED** [review]

**Comment by timokau** [comment]
Sorry for the delay, missed the notification email.

**Comment by rnhmjoj** [comment]
No problem, thank you.

**Pull request merged**
