### PR TITLE
quickwit: 0.8.0 -> 0.8.1, default config file

### PR DESCRIPTION
**Pull request by nh2**
* [x] Based on #300659, merge that first
* https://github.com/quickwit-oss/quickwit/releases/tag/v0.8.1
* Also fix:
  * #289000

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nh2** [comment]
Building this still fails on my 128 GB RAM machine with:

```
thread 'actors::indexer::tests::test_indexer_triggers_commit_on_timeout' panicked at quickwit-indexing/src/actors/indexer.rs:1039:9:
assertion `left == right` failed
  left: MemoryLimit
 right: Timeout
```

See: https://github.com/NixOS/nixpkgs/issues/289000#issuecomment-2029514548

**Comment by happysalada** [comment]
I observed the same failure when building 0.8.0
Let's skip this test if that's ok with you.

**Comment by nh2** [comment]
> Let's skip this test if that's ok with you.

Fine by me, I don't know yet how to disable specific Rust tests though. Feel free to push into my PR here in case you know it!

**Comment by happysalada** [comment]
I'm not close to a keyboard for long enough to push a commit, but here is an example.
```
  checkFlags = [
    # tries to make a network access
    "--skip=sinks::loki::tests::healthcheck_grafana_cloud"
```
so it shoulb be something like `--skip='actors::indexer::tests::test_indexer_triggers_commit_on_timeout`

I should have time this weekend, I'm just posting this in case you have time before.

**Comment by tcheronneau** [comment]
Hey guys I've been trying to build quickwit with the UI (and finally managed to do it). 
I've also added the recommended build-features. Maybe it would worth to add that with this PR ?

**Comment by happysalada** [comment]
That would indeed be appreciated. Would you he okay with pushing to the branch ?

**Comment by nh2** [comment]
I already left some comments on your PR #307808

**Comment by nh2** [comment]
> Hey guys I've been trying to build quickwit with the UI (and finally managed to do it).
> I've also added the recommended build-features

@tcheronneau Where are those changes, do you have a branch? Feel free to push them into this PR as additional commits for me to review, if you have permission to do that. Otherwise, let me know and I'll pull them.

**Comment by tcheronneau** [comment]
> > Hey guys I've been trying to build quickwit with the UI (and finally managed to do it).
> > I've also added the recommended build-features
> 
> @tcheronneau Where are those changes, do you have a branch? Feel free to push them into this PR as additional commits for me to review, if you have permission to do that. Otherwise, let me know and I'll pull them.

@nh2 I don't really know how to come in your PR (not used to github). 
But you can find the change there : https://github.com/NixOS/nixpkgs/commit/be916fcec5c99b9f6c7208f3434c7e70d003eec3.

**Comment by tcheronneau** [comment]
I've prepared a PR but I cannot push to your repo. 
In the end the build features does not work for now. 
I'll try to debug I got a dev from quickwit I could maybe contact to help. 
For now the working package with UI is there : https://gist.github.com/tcheronneau/8c0417705e8acc28e37289255dbb6b45

**Comment by jpds** [comment]
Sorry folks - I didn't see this one when I pushed up #317152.

**Comment by wegank** [comment]
Done in #317152.

**Pull request closed without merging**
