### PR TITLE
Guile setup hook, use compiled files

### PR DESCRIPTION
**Pull request by KoviRobi**
Often packages install the compiled files to
`$(libdir)/guile/$(GUILE_EFFECTIVE_VERSION)/ccache` (e.g. see
guile-opengl). This path is not explicitly given in the info page, but
is used in a couple of places, and is also part of `%load-compiled-path`
variable in guile (for `"${guile}/lib/guile/2.2/ccache`).

Similarly, the site-ccache is also part of `%load-compiled-path` in
guile.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by KoviRobi** [comment]
Something to investigate is why does everything in GUILE_LOAD_COMPILED_PATH there twice

**Comment by SuperSandro2000** [comment]
Can you target staging and rebase the PR?

**Comment by andir** [comment]
I rebased this onto staging and fixed the commit message to be in line with our contribution guidelines.

**Comment by KoviRobi** [comment]
Thanks @andir (I didn't realise others could force-push to my branch, I presume because it's forked from NixOS/nixpkgs and it's a pull request).

For what it's worth, the duplicate paths are a problem elsewhere so this pull request doesn't create any new problems. E.g.
```
[[ rmk35@pc-nixos-a... /pkgs/unstable ]]|$ nix-shell -p pyrex

[nix-shell:~/programming/nix/pkgs/unstable]$ echo $PYTHONPATH | tr : \\n
/nix/store/vlijrzyfhzl7s08296fjy42cn0kj50pw-python2.7-pyrex-0.9.5.1.1/lib/python2.7/site-packages
/nix/store/vfd4wghhzz4afzxgwynsnbj9xzpkib4z-python-2.7.18/lib/python2.7/site-packages
/nix/store/vlijrzyfhzl7s08296fjy42cn0kj50pw-python2.7-pyrex-0.9.5.1.1/lib/python2.7/site-packages
/nix/store/vfd4wghhzz4afzxgwynsnbj9xzpkib4z-python-2.7.18/lib/python2.7/site-packages
```
I don't know why this is but I suspect it's because of dependency graph walking and shared dependencies.

**Comment by andir** [comment]
Sounds good enough for now. This is already an improvement. When we find a "better" way of doing that we can do it.

**Pull request merged**
