### PR TITLE
python310Packages.ua-parser: 0.10.0 -> 0.15.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 179491` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>5 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>pgadmin4: log was empty</li>
<li>python310Packages.ua-parser: log was empty</li>
<li>python310Packages.user-agents: log was empty</li>
<li>python39Packages.ua-parser: log was empty</li>
<li>python39Packages.user-agents: log was empty</li>
  </ul>
</details>

**Comment by gador** [comment]
This updates breaks the packages mentioned before.
Error log:
```
nix-build -A python3Packages.ua-parser
these 2 derivations will be built:
  /nix/store/wj1r2izkm5ycvaz642v4nyag90cbzg0f-source.drv
  /nix/store/0sldhdlhx2nvwbxnk23w7ydpdvjq67s8-python3.10-ua-parser-0.15.0.drv
resolved derivation: '/nix/store/wj1r2izkm5ycvaz642v4nyag90cbzg0f-source.drv' -> '/nix/store/y8vnvnhbabrpg7kzqfx3wzhkml30v9ic-source.drv'...
building '/nix/store/y8vnvnhbabrpg7kzqfx3wzhkml30v9ic-source.drv'...
exporting https://github.com/ua-parser/uap-python.git (rev 0.15.0) into /nix/store/g0hhpbznsrz16zayqwj77frnlq51h29m-source
Initialized empty Git repository in /nix/store/g0hhpbznsrz16zayqwj77frnlq51h29m-source/.git/
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 19 (delta 1), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), 13.58 KiB | 4.52 MiB/s, done.
From https://github.com/ua-parser/uap-python
 * tag               0.15.0     -> FETCH_HEAD
Switched to a new branch 'fetchgit'
Submodule 'uap-core' (https://github.com/ua-parser/uap-core) registered for path 'uap-core'
Initialized empty Git repository in /nix/store/g0hhpbznsrz16zayqwj77frnlq51h29m-source/uap-core/.git/
fatal: invalid refspec '+refs/tags/v0.15.0^{}'
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 30 (delta 2), reused 15 (delta 0), pack-reused 0
Unpacking objects: 100% (30/30), 820.35 KiB | 4.63 MiB/s, done.
From https://github.com/ua-parser/uap-core
 * branch            bbd43aed9a623486191a33c3af9e463e89c85f7a -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...
error: hash mismatch in fixed-output derivation '/nix/store/y8vnvnhbabrpg7kzqfx3wzhkml30v9ic-source.drv':
         specified: sha256-CwwVaToy5se5dZ4m1EHn8qgvprK82/Sgpos4lHedIUc=
            got:    sha256-TtOj1ZL8+4T95AgF9ErvI+0W35WQ23snFhCyCbuRjxM=
error: 1 dependencies of derivation '/nix/store/0sldhdlhx2nvwbxnk23w7ydpdvjq67s8-python3.10-ua-parser-0.15.0.drv' failed to build
```

**Comment by dotlambda** [comment]
How was ofborg able to build this if the hash was wrong?

**Comment by gador** [comment]
I don't know, but `ofborg` didn't remove the `.git` directory according to the [logs](https://logs.nix.ci/?key=nixos/nixpkgs.179491&attempt_id=961bf783-2c09-4eab-b526-5b0b397ac42d)

**Pull request merged**
