### PR TITLE
perlPackages.Catmandu:init at 1.2002 [WIP]

### PR DESCRIPTION
**Pull request by pasqui23**
###### Motivation for this change

Still not ready,as after installing it 
```
$  catmandu                                        
Can't locate Catmandu.pm in @INC (you may need to install the Catmandu module) (@INC contains: /nix/store/xnr1miqcjqsvqb6n23zavrvnnyax49bi-perl-5.28.2/lib/perl5/site_perl/5.28.2/x86_64-linux-thread-multi /nix/store/xnr1miqcjqsvqb6n23zavrvnnyax49bi-perl-5.28.2/lib/perl5/site_perl/5.28.2 /nix/store/xnr1miqcjqsvqb6n23zavrvnnyax49bi-perl-5.28.2/lib/perl5/5.28.2/x86_64-linux-thread-multi /nix/store/xnr1miqcjqsvqb6n23zavrvnnyax49bi-perl-5.28.2/lib/perl5/5.28.2) at ~/.nix-profile/bin/catmandu line 3.
BEGIN failed--compilation aborted at ~/.nix-profile/bin/catmandu line 3.
```
###### Things done

- [X ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
This regex
https://github.com/NixOS/nixpkgs/blob/120398ab4b098e815b926dc7270de3bd99f63fd7/pkgs/development/perl-modules/generic/builder.sh#L20

does not match ```#!perl``` file of ```bin/catmandu``` file
related https://github.com/NixOS/nixpkgs/pull/32717
cc @gebner

**Comment by volth** [comment]
Here is ```perlPackages.Catmandu:init at 1.2002``` made by a script out of cpan metadata
https://github.com/NixOS/nixpkgs/compare/staging...volth:cpan2nix-2019-07-02?expand=1

It depends on https://github.com/NixOS/nixpkgs/pull/64157 fix too

**Comment by pasqui23** [comment]
So what,we close this pr and open your diff?

**Comment by volth** [comment]
I have not tested my diff well (only tested that `bin/catmandu` starts).
At first glance this PR has more deps, which `cpan2nix` did not include.

**Comment by volth** [comment]
May be ```my diff + manual fixes (if they are needed)```, so they could survive future version updates made by bots

**Comment by pasqui23** [comment]
@Volth ok how do i take your fixes and develop them in my fork of nixpkgs?My git-fu is very weak

**Comment by volth** [comment]
it is already merged, can be closed

**Pull request closed without merging**
