### PR TITLE
remove PKG_CONFIG_PATH from profileRelativeEnvVars

### PR DESCRIPTION
**Pull request by bennofs**

### CODE REVIEW

**Comment by bjornfor** [comment]
Hm, I actually prefer to have it there. It allows using NixOS as a somewhat "normal" distro, if one wants to.

**Comment by edolstra** [comment]
We also don't set variables like `LIBRARY_PATH` or `C_INCLUDE_PATH`, which would be necessary if you want NixOS to behave like a "normal" distro wrt software development.

**Comment by lethalman** [comment]
:+1: let's remove this please...

**Comment by bjornfor** [comment]
@edolstra: I'm not familiar with LIBRARY_PATH and C_INCLUDE_PATH. AFAIK, pkg-config returns all flags that are needed.

I can of course add PKG_CONFIG_PATH in my configuration.nix.

Btw, should we remove PERL5LIB also then?

**Comment by bjornfor** [comment]
What problems does PKG_CONFIG_PATH cause? What is the motivation to remove it?

**Comment by bjornfor** [comment]
(Some more thoughts. Correct me if I'm wrong.)

If we remove PKG_CONFIG_PATH, we're basically saying "this is not a package you should install in your profile". Why would we do that? Is it because pkg-config is a "developer tool", as opposed to "end user application"? Where to draw the line between the two? (I don't think there is a definite line...)

And if we are going to dictate what kind of packages users install to their profiles, we better do it in a user friendly style. Like having a mechanism for _actually_ preventing packages from being installed in a profile; there could be an assert of some sort with a friendly message. Without such a mechanism, we'd be providing a very user un-friendly system; "wait... so I'm allowed to install this, but the developers have _intentinally_ broken it when installed this way?".

**Comment by lethalman** [comment]
@bjornfor libraries or dev stuff were never supposed to be in your profile. Pretty sure a lot of libs you put in your profile just don't work. So it's already like this, removing PKG_CONFIG_PATH defines even better that libs shouldn't be installed in the profile.

And this PR does not prevent you from setting that PKG_CONFIG_PATH variable manually again.

**Comment by bjornfor** [comment]
Well, I think it is up to _each user_ to decide what should be in his/her profile. In my opinion, NixOS should make programs just work, if possible, in any configuration/profile. Especially not intentionally cripple some programs because it can be considered "bad style" to use them this or that way. If we are to dictate, do it user friendly, with an assert + message.

Btw, most problems I've come across with broken libraries are due to broken pkg-config files. Otherwise it works fine, in my experience. Of course, I don't build complex stuff in such environments... (And I really do appreciate what nix has to offer in environment isolation etc. It's just different tools for different tasks.)

Here is a use case.
From time to time, I work a lot with Buildroot and Linux source trees. For this I need pkg-config and some other deps. Now, I can define a shell.nix file and enter the development environment every time I'm going to do some work. But what if that is _all I do_ on that machine for weeks? Entering nix-shell suddenly becomes a pointless chore. I'd save a lot of time by putting all deps into my profile and be done with it. (If something requires a clean environment, there is always ```nix-shell --pure``` or ```nix-build```.)

Sure, I can put PKG_CONFIG_PATH back on my system. But I do care about defaults and useability. And like I said above, intentionally breaking a tool is a terrible way to say it's "discouraged".

**Comment by ttuegel** [comment]
:+1:

**Comment by bjornfor** [comment]
No activity since august last year. Closing. (I'm just doing this to clean up, if you feel strongly about this issue, re-open.)

**Comment by vcunat** [comment]
I've got no strong opinion on this one, but IMO putting dev deps into `systemPackages` or installing via `nix-env` shouldn't be encouraged. It's not something we really support.

**Pull request closed without merging**
