### PR TITLE
transmission: patch to load legacy openssl provider

### PR DESCRIPTION
**Pull request by seirl**
###### Description of changes

This prevents a segfault in EVP_CIPHER_CTX_set_key_length() when adding a new torrent.

See background information here:
https://github.com/transmission/transmission/issues/4716

Testing plan: My system package would segfault in the EVP_CIPHER_CTX_set_key_length() function. I applied this patch, rebuilt the package and now it's no longer crashing.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Dettorer** [comment]
Result of `nixpkgs-review pr 216953` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>fragments</li>
    <li>libtransmission</li>
    <li>torrential</li>
    <li>transmission</li>
    <li>transmission-gtk</li>
    <li>transmission-qt</li>
  </ul>
</details>

**Comment by Dettorer** [comment]
Looks good.

I ran `nix shell '.#transmission' '.#transmission-qt' --command transmission-qt` both on master and on this PR's branch. I confirm adding a torrent file with master's version segfaults while doesn't anymore with this PR. I tried a few times back and forth between the two branches to make sure the apparent fix wasn't because of some kind of state saved by transmission.

**Comment by vcunat** [comment]
I don't expect this is needed, as we pass `openssl_legacy` to `transmission`.  And both should be superseded by already open upgrade https://github.com/NixOS/nixpkgs/pull/215316

**Comment by delroth** [comment]
Probably the cause for https://hydra.nixos.org/build/209741494 broken since last staging merge?

**Comment by ajs124** [comment]
I'm >90% sure this shouldn't be needed since #209341

**Comment by seirl** [comment]
Hmm, but I do get a crash on the latest nixpkgs unstable.

**Comment by ajs124** [comment]
> on the latest nixpkgs unstable

Hm. Can you verify if #209341 was included in that?

Because transmission has been working fine for me. Then again, I'm (basically) on the nixos-22.11-small branch.

In any case, there's a discussion to be had if this PR the preferred solution over what we currently have, but leaving what I added in #209341 and adding this PR does seem redundant.

**Comment by delroth** [comment]
Could it be that `transmission-qt` specifically still ends up picking up a non-legacy openssl via the Qt dependency?

**Comment by ajs124** [comment]
@delroth that does sound quite likely, yes. Packages propagating `openssl` or `curl` (which propagates `openssl`) often lead to all kinds of _interesting_ problems.

**Comment by delroth** [comment]
Sounds like a good reason to maybe revert https://github.com/NixOS/nixpkgs/pull/209341 then until we switch to transmission 4.0? WDYT?

**Comment by ajs124** [comment]
Sounds reasonable enough. You can push the revert to this branch.

**Comment by seirl** [comment]
Done!

**Comment by ajs124** [comment]
don't just revert that, also add your patch.

the debian patch is flawed and leads to a sizeable memory leak see #207047

**Comment by seirl** [comment]
@ajs124 Ah, gotcha. I split it into one revert + one commit that changes the patch URL to the gentoo downstream patch instead of the debian one. Please take another look?

**Comment by ajs124** [comment]
Diff LGTM, haven't tested anything though.

As @vcunat mentioned, there's also #215316. However, maybe we should still go ahead with this PR, if we're going to keep transmission 3 around, as suggested in https://github.com/NixOS/nixpkgs/pull/215316#issuecomment-1435690066.

But I'll leave those decisions to the maintainers of this package.

**Pull request merged**
