### PR TITLE
Improve SDL setup hook

### PR DESCRIPTION
**Pull request by sergv**
## Summary

SDL setup hook does more work that required by putting more entries into SDL_LIB_PATH than needed. This contributes to bloated environment that leads to https://github.com/NixOS/nixpkgs/issues/41340.

## Details

Before f7fdc997bf0748a49dea2e0e5451a21da02ee4c1 the SDL setup hook looked like this (literally it was a bit different but logically `SDL_LIB_PATH` was modified only when `SDL_PATH` was too) :

```bash
addSDLPath () {
  if [ -e "$1/include/SDL" ]; then
    export SDL_PATH="${SDL_PATH-}${SDL_PATH:+ }$1/include/SDL"
    export SDL_LIB_PATH="${SDL_LIB_PATH-}${SDL_LIB_PATH:+ }-L$1/lib"
  fi
}
```

The last commit (https://github.com/NixOS/nixpkgs/pull/72812/commits/f7fdc997bf0748a49dea2e0e5451a21da02ee4c1) in the relevant PR https://github.com/NixOS/nixpkgs/pull/72812 changed the logic to:

```bash
addSDLPath () {
  if [ -e "$1/include/SDL" ]; then
    export SDL_PATH="${SDL_PATH-}${SDL_PATH:+ }$1/include/SDL"
  fi
  if [ -e "$1/lib" ]; then
    export SDL_LIB_PATH="${SDL_LIB_PATH-}${SDL_LIB_PATH:+ }-L$1/lib"
  fi
}
```

I was unable to find any justification for this change and the commit message looks suspicious: `Merge commit 'afa48f16f265fd3e88073bca7929e1e103bd3dc3' into bash-no-undef-vars`. The mentioned commit afa48f16f265fd3e88073bca7929e1e103bd3dc3 is not related to SDL so it seems like merge ought to have left SDL as is.

The way hook looks now, any package that has `/lib` gets added to `SDL_LIB_PATH` which is only used for SDL purposes within nixpkgs as far as I can tell. It seems that only SDL-related things should go there, like `SDL_image`, `SDL_mixer`, etc - basically the packages that have corresponding `/include/SDL`. Putting everything in there the way it works now is likely redundant.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by FliegendeWurst — CHANGES_REQUESTED** [review]
LGTM :+1:

Since this fix causes a lot of rebuilds, please rebase the PR onto staging ([howto](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging)).

**Comment by sergv** [comment]
Thanks for the review! I've rebased onto staging and changed merge target to staging as well.

**Review by FliegendeWurst — COMMENTED** [review]
Per https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions the first line of the commit message should be: "SDL: put only SDL-related paths in SDL_LIB_PATH" (or similar).
It's very good that you included some context in the commit description!

**Comment by sergv** [comment]
Renamed the commit and rebased on staging once more.

**Review by FliegendeWurst — APPROVED** [review]

**Review by Ericson2314 — APPROVED** [review]
Looks good to me!

I think that was just a sloppy merge "huh, conditioning -L on include path? that looks like I made a mistake."

Good sleuthing, and thanks for catching my mistake.

**Comment by Artturin** [comment]
Probably won't work with split outputs though

**Comment by Ericson2314** [comment]
Oh huh good catch

**Comment by sergv** [comment]
Good point about packages with split dev, I didn't give them a thought before. However I'm probably missing something yet it seems they won't cause a problem: the SDL's setup hook initializes `SDL_PATH` and `SDL_LIB_PATH` variables which within nixpkgs are only consumed by the SDL itself (only mentioned in SDL's `find-headers.patch`).

As far as I understood from mentions of the environment variables the hook is intended to make packages like `SDL_image`, `SDL_mixer`, `SDL_ttf` or `SDL_gfx` found by the SDL. None of these packages have split dev. Only SDL itself uses split dev but it doesn't need to add itself to the environment variables sine it's the consumer of those variables.

**Comment by Artturin** [comment]
Add a comment that it's doesn't work with split dev

**Comment by sergv** [comment]
I've added a note about split dev in the setup hook.

**Comment by Artturin** [comment]
Why was this merged when it includes extra commits?

**Comment by Artturin** [comment]
image

@sergv Seems you rebased incorrectly and dropped your changes and github thought the pr was already merged :/ Can you make a new pr reconstructed from `git reflog`, I'll merge it.

Here's how you can rebase without dropping commits BTW https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

**Comment by sergv** [comment]
@Artturin looks like I may have accidentally removed branch in my repo, but I'm not fully sure. I've created new PR at https://github.com/NixOS/nixpkgs/pull/296015.

**Pull request merged**
