### PR TITLE
dht: 0.25 -> 0.27

### PR DESCRIPTION
**Pull request by bheesham**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bheesham** [comment]
Output from `nixpkgs-review`:

```
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
$ git worktree add /home/bheesham/.cache/nixpkgs-review/rev-40ea49cc96ed9f5b2dc0f1c91d697ead8538e034/nixpkgs 063272c0d839f614d574af5d97338f185a430876
Preparing worktree (detached HEAD 063272c0d83)
Updating files: 100% (33623/33623), done.
HEAD is now at 063272c0d83 terraform-providers.tencentcloud: 1.79.9 → 1.79.10
$ nix-env --option system x86_64-linux -f /home/bheesham/.cache/nixpkgs-review/rev-40ea49cc96ed9f5b2dc0f1c91d697ead8538e034/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
$ git merge --no-commit --no-ff 40ea49cc96ed9f5b2dc0f1c91d697ead8538e034
Automatic merge went well; stopped before committing as requested
$ nix-env --option system x86_64-linux -f /home/bheesham/.cache/nixpkgs-review/rev-40ea49cc96ed9f5b2dc0f1c91d697ead8538e034/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation --meta
7 packages updated:
dht (0.25 → 0.27) fragments torrential transmission transmission transmission transmission

$ nix --experimental-features nix-command build --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed -f /home/bheesham/.cache/nixpkgs-review/rev-40ea49cc96ed9f5b2dc0f1c91d697ead8538e034/build.nix
7 packages built:
dht fragments libtransmission torrential transmission transmission-gtk transmission-qt

$ /nix/store/nnznavnhyli08264apz6lanbjza48si1-nix-2.13.2/bin/nix-shell /home/bheesham/.cache/nixpkgs-review/rev-40ea49cc96ed9f5b2dc0f1c91d697ead8538e034/shell.nix
```

**Comment by ajs124** [comment]
I did basically the same change in #215316, but that's sort of stuck, so IMO we can just get this PR here in and I'll rebase mine.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 216591` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>dht</li>
    <li>fragments</li>
    <li>libtransmission</li>
    <li>torrential</li>
    <li>transmission</li>
    <li>transmission-gtk</li>
    <li>transmission-qt</li>
  </ul>
</details>

**Review by NickCao — APPROVED** [review]
Tested downloading Arch Linux iso with transmission-gtk.

**Comment by bheesham** [comment]
:tada: Thank you!

**Pull request merged**
