### PR TITLE
audacity: 3.3.3 -> 3.4.0

### PR DESCRIPTION
**Pull request by rski**
Added two libraries that cmake requested

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rski** [comment]
getting some fun errors, not sure what to do about them. It started once and got something about opus and ioctl, on exit it sigaborts every time:
```
Thread 1 "..audacity-wrap" received signal SIGABRT, Aborted.
0x00007ffff51c4d7c in __pthread_kill_implementation ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
(gdb) bt
#0  0x00007ffff51c4d7c in __pthread_kill_implementation ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#1  0x00007ffff51759c6 in raise ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#2  0x00007ffff515e8fa in abort ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#3  0x00007ffff515f767 in __libc_message.cold ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#4  0x00007ffff51cea45 in malloc_printerr ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#5  0x00007ffff51d097c in _int_free_merge_chunk ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#6  0x00007ffff51d0c79 in _int_free ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#7  0x00007ffff51d3323 in free ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#8  0x00000000008bee03 in AudacityFileConfig::~AudacityFileConfig() ()
#9  0x00000000008bee29 in AudacityFileConfig::~AudacityFileConfig() ()
#10 0x00000000008bd8c1 in std::shared_ptr<wxConfigBase>::~shared_ptr() ()
#11 0x00007ffff5177fa5 in __run_exit_handlers ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#12 0x00007ffff51780de in exit ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#13 0x00007ffff515ffd5 in __libc_start_call_main ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#14 0x00007ffff5160089 in __libc_start_main_impl ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#15 0x000000000088fc45 in _start ()
```
and now it's also failing on startup with:
```
An unrecoverable error has occurred during startup
```
and the same backtrace :shrug:

**Comment by rski** [comment]
now the old audacity is also throwing the config error. fun

**Comment by giomf** [comment]
Result of `nixpkgs-review pr 265222` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>audacity</li>
  </ul>
</details>

It builds without problems. But I got the same errors as you:

> Unable to load the "mod-opus" module.
Error: Inappropriate ioctl for device

I only got these error once. After a restart they disappeared.

**Comment by rski** [comment]
full exit bt:
```
Thread 1 "..audacity-wrap" received signal SIGABRT, Aborted.
0x00007ffff51c4d7c in __pthread_kill_implementation ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
(gdb) bt
#0  0x00007ffff51c4d7c in __pthread_kill_implementation ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#1  0x00007ffff51759c6 in raise ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#2  0x00007ffff515e8fa in abort ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#3  0x00007ffff515f767 in __libc_message.cold ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#4  0x00007ffff51cea45 in malloc_printerr ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#5  0x00007ffff51d097c in _int_free_merge_chunk ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#6  0x00007ffff51d0c79 in _int_free ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#7  0x00007ffff51d3323 in free ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#8  0x00000000009348cf in std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string (this=0x14fa980, __in_chrg=<optimized out>)
    at /nix/store/0b9bsznqs6pdg42dxcwvrlmarjn2p6a1-gcc-12.3.0/include/c++/12.3.0/bits/basic_string.h:802
#9  wxString::~wxString (this=0x14fa980, __in_chrg=<optimized out>)
    at /nix/store/dpb22dp3k7w8p9yph0k3gwmxcc1y2gxh-wxwidgets-3.2.3/include/wx-3.2/wx/string.h:301
#10 0x0000000000954113 in AudacityFileConfig::~AudacityFileConfig (this=0x14fa720, 
    __in_chrg=<optimized out>) at /build/source/src/AudacityFileConfig.cpp:80
#11 0x0000000000954127 in AudacityFileConfig::~AudacityFileConfig (this=0x14fa720, 
    __in_chrg=<optimized out>) at /build/source/src/AudacityFileConfig.cpp:80
#12 0x0000000000953eaa in std::default_delete<AudacityFileConfig>::operator() (__ptr=<optimized out>, 
    this=<optimized out>)
    at /nix/store/0b9bsznqs6pdg42dxcwvrlmarjn2p6a1-gcc-12.3.0/include/c++/12.3.0/bits/unique_ptr.h:95
#13 std::_Sp_counted_deleter<AudacityFileConfig*, std::default_delete<AudacityFileConfig>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=<optimized out>)
    at /nix/store/0b9bsznqs6pdg42dxcwvrlmarjn2p6a1-gcc-12.3.0/include/c++/12.3.0/bits/shared_ptr_base.h:527
#14 0x0000000000928733 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x15a8030)
    at /nix/store/0b9bsznqs6pdg42dxcwvrlmarjn2p6a1-gcc-12.3.0/include/c++/12.3.0/bits/shared_ptr_base.h:346
#15 0x0000000000952262 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (
    this=<optimized out>, __in_chrg=<optimized out>)
    at /nix/store/0b9bsznqs6pdg42dxcwvrlmarjn2p6a1-gcc-12.3.0/include/c++/12.3.0/bits/shared_ptr_base.h:1071
#16 std::__shared_ptr<wxConfigBase, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>, 
    __in_chrg=<optimized out>)
    at /nix/store/0b9bsznqs6pdg42dxcwvrlmarjn2p6a1-gcc-12.3.0/include/c++/12.3.0/bits/shared_ptr_base.h:1524
#17 std::shared_ptr<wxConfigBase>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /nix/store/0b9bsznqs6pdg42dxcwvrlmarjn2p6a1-gcc-12.3.0/include/c++/12.3.0/bits/shared_ptr.h:175
#18 0x00007ffff5177fa5 in __run_exit_handlers ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#19 0x00007ffff51780de in exit ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#20 0x00007ffff515ffd5 in __libc_start_call_main ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#21 0x00007ffff5160089 in __libc_start_main_impl ()
   from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#22 0x0000000000927b05 in _start ()
(gdb) 
```

**Comment by rski** [comment]
feels related to https://github.com/audacity/audacity/pull/5004

**Comment by wegank** [comment]
Also fails on aarch64-linux (audacity/audacity#5476).

**Pull request closed without merging**
