### PR TITLE
cmatrix: init at 1.2a

### PR DESCRIPTION
**Pull request by AndersonTorres**
cmatrix is a ncurses-based "screensaver".

### CODE REVIEW

**Comment by jagajaga** [comment]
What about this line? https://travis-ci.org/NixOS/nixpkgs/builds/73276423#L487

**Comment by AndersonTorres** [comment]
Hum, strange. Here I don't see any suspect call to a FHS dir. I will dig into it now

**Comment by jagajaga** [comment]
@AndersonTorres do use use chroot builds?

**Comment by AndersonTorres** [comment]
As far as I know, yes - I use that line on configuration.nix:

`nix.useChroot=true;`

**Comment by jagajaga** [comment]
Built locally, thanks.

**Pull request merged**
