### PR TITLE
armcord: 3.1.6 -> 3.1.7

### PR DESCRIPTION
**Pull request by westlyroots**
###### Description of changes

Updating to latest release: https://github.com/ArmCord/ArmCord/releases/tag/v3.1.7

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by red-star-fighter** [comment]
new to submitting, I can't get nixos-review to work- it keeps crashing in my VM without giving a proper output. :(
theoretically, nothing should break - it's a small update.

**Comment by Zaedus** [comment]
I tried to build from your branch and there was a hash mismatch error. 
```
error: hash mismatch in fixed-output derivation '/nix/store/21klxx1dmvkklq5ppl7n8wvs03mjyair-ArmCord_3.1.7_amd64.deb.drv':
         specified: sha256-WmPR+c36HKvpsV7T3VQ4scUX5SswqqwofXsJD1Aza+w=
            got:    sha256-c0ejSivQbxpPUQ6P0YUya3q1EJ1yF4RFGur11BMwz3o=
error: 1 dependencies of derivation '/nix/store/zy14bb518r310z5mqj6cfdrlja1y41cn-armcord-3.1.7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hqnh88ds413khl7q4r1qmkpisfj1zvl4-review-shell.drv' failed to build
```
Could you confirm by running `nix-build <insert nixpkgs dir here> -A armcord`?
If armcord is already installed you can add the `--check` option to the above command to force rebuilding.

**Comment by red-star-fighter** [comment]
> I tried to build from your branch and there was a hash mismatch error.
> 
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/21klxx1dmvkklq5ppl7n8wvs03mjyair-ArmCord_3.1.7_amd64.deb.drv':
>          specified: sha256-WmPR+c36HKvpsV7T3VQ4scUX5SswqqwofXsJD1Aza+w=
>             got:    sha256-c0ejSivQbxpPUQ6P0YUya3q1EJ1yF4RFGur11BMwz3o=
> error: 1 dependencies of derivation '/nix/store/zy14bb518r310z5mqj6cfdrlja1y41cn-armcord-3.1.7.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/hqnh88ds413khl7q4r1qmkpisfj1zvl4-review-shell.drv' failed to build
> ```
> 
> Could you confirm by running `nix-build <insert nixpkgs dir here> -A armcord`? If armcord is already installed you can add the `--check` option to the above command to force rebuilding.

I messed up and calculated the hashes incorrectly. After fixing it, it built fine and launched properly.

**Review by huantianad — CHANGES_REQUESTED** [review]
Works fine for me on x86_64, but please squash your commits and rename it to `armcord: 3.1.6 -> 3.1.7` (the same as your PR's name).

**Comment by wrmilling** [comment]
@red-star-fighter If you can complete the change mentioned by @huantianad, I can throw my approval on there as well.

**Comment by wiryfuture** [comment]
Don't mean for this come off as rude, but is this PR still happening? I want to backport 3.1.7 to 22.11 but don't want to backport 3.1.6 when 3.1.7 is basically available.

**Review by wrmilling — APPROVED** [review]
Commits still need cleanup, otherwise fine.

**Comment by huantianad** [comment]
The original author doesn't seem to be active right now, is there a proper way to "take control" of the PR and squash the commits? Otherwise we could open/switch to another PR.

**Comment by K900** [comment]
Superseded by #227937.

**Pull request closed without merging**
