### PR TITLE
libuv: 1.9.0 -> 1.9.1, nodejs-4.3.1 -> 4.4.4, nodejs-5.11.0 -> 5.11.1

### PR DESCRIPTION
**Pull request by groxxda**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

nodejs 6.2.0 upstream already uses the new libuv
Since the three node packages all depend on libuv and thus will be rebuilt, I figured it may be a good time to bump them aswell.

Tested execution of the respective binaries of all node versions and neovim.

Packages that fail to build for me: airfield (marked broken), groovebasin (needs pinning to node_0.10, I'll open a separate PR), ripple-rest (development frozen probably also needs older node) - I think all of these are unrelated to my changes.

### CODE REVIEW

**Comment by groxxda** [comment]
CC nodejs maintainers: @cillianderoiste @gilligan

**Comment by gilligan** [comment]
I'm on my mobile right now- will check it out tomorrow. Looks like build failed on travis.

**Comment by groxxda** [comment]
Build fails on travis due to timeout: 
>The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by gilligan** [comment]
Considering that @groxxda tested the build locally and we can't change the fact that travis will time out this LGTM.

Just need someone to merge - Perhaps @zimbatm or @svanderburg or @joachifm ?

**Comment by zimbatm** [comment]
there :)

**Pull request merged**
