### PR TITLE
Ibus: binding fixes

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Build gi overrides & stop building Python 2 bindings installed to Python 3 directory.

cc @laMudri 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by lukateras — APPROVED** [review]

**Comment by jtojnar** [comment]
It does not seem to be enough to fix https://github.com/NixOS/nixpkgs/pull/61978

**Comment by laMudri** [comment]
> It does not seem to be enough to fix #61978

In testing that, have you also added `wrapGAppsHook` to ibus-table?

**Comment by jtojnar** [comment]
Not sure, will double check once I get home.

**Comment by jtojnar** [comment]
```ShellSession
$ echo 'with import <nixpkgs> { };
mkShell {
  buildInputs = [
    gobject-introspection
    ibus
    (python3.withPackages (p: [p.pygobject3 ibus]))
    wrapGAppsHook
  ];
}
' > ibus-typelib.nix
$ nix-shell ibus-typelib.nix --run python3
Python 3.7.3 (default, Mar 25 2019, 20:59:09)
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import IBus
__main__:1: PyGIWarning: IBus was imported without specifying a version first. Use gi.require_version('IBus', '1.0') before import to ensure that the right version gets loaded.
>>> IBus.LookupTable(page_size=10, cursor_pos=0, cursor_visible=True, round=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: gobject `IBusLookupTable' doesn't support property `page_size'
```

**Comment by jtojnar** [comment]
Looking at the tests, it should definitely work:

https://github.com/ibus/ibus/blob/7cef5bf572596361bc502e8fa917569676a80372/bindings/pygobject/test-override-ibus.py#L108-L109

**Comment by jtojnar** [comment]
Hmm, looks like the issue is somewhere else, the overrides from `ibus` are not even added to the env:

```ShellSession
$ ls -l $(nix-build -E 'with import <nixpkgs> {}; (python3.withPackages (p: [p.pygobject3 ibus]))')/lib/python3.7/site-packages
total 44
…
lrwxrwxrwx 1 root root 101 Jan  1  1970 gi -> /nix/store/7shmlh3agdy31hhh0da2bhk9zzzpg7gp-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi
…
```

**Comment by jtojnar** [comment]
Now I feel stupid. We actually need to use `(p.toPythonModule ibus)`.

**Pull request merged**
