### PR TITLE
[18.09] nixos/emby: use the dataDir option

### PR DESCRIPTION
**Pull request by Vskilet**
###### Motivation for this change
 In #48043 @joachifm suggest to add the pull request to the release. I added other commits to assure compatibility.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by worldofpeace — APPROVED** [review]

**Comment by worldofpeace** [comment]
cc @xeji

**Comment by worldofpeace** [comment]
@Vskilet btw it's nice to be able to tell if this is a backport by having the pr title include `[18.09]`.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build emby

**Comment by Vskilet** [comment]
Ok @fpletz thanks to give feedbacks 😄
But should I cherry-picking with x now ?

**Comment by worldofpeace** [comment]
I don't see any reason to hold this off. 
cc @fpletz @xeji @Mic92

**Comment by c0bw3b** [comment]
Do we want/need to backport the version bump also?
Or was the goal to backport just the last 2 commits ("use the dataDir option" and "delete programData hardcode in pkg") ?

Naive question really, I did not follow previous work

**Comment by worldofpeace** [comment]
> Do we want/need to backport the version bump also?
> Or was the goal to backport just the last 2 commits ("use the dataDir option" and "delete programData hardcode in pkg") ?
> 
> Naive question really, I did not follow previous work

Yes and yes.

I've tested in a vm with the 18.09 release and switching to this version hasn't caused any problems.
There was this [issue](https://github.com/MediaBrowser/Emby/issues/3438) but it was worked around with https://github.com/NixOS/nixpkgs/pull/48150/commits/cfd6ace6bfcff94a0be8cabb37d719039384c81b. The upstream fix will be in the next release.

`dataDir` fix is also pertinent because its use was non-functional.

**Comment by xeji** [comment]
@GrahamcOfBorg build emby

**Pull request merged**
