### PR TITLE
nixos/httpd: drop tomcat-connector httpd subservice

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Drop support for `httpd.extraSubservices`.

This subservice is pretty simple and hard codes more than it should. I would suggest that those wishing to use `mod_jk` can probably just configure it themselves.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@fpletz If you don't mind I'd like to get your approval (or not) on this PR.

**Comment by samueldr** [comment]
Seems like this broke eval (nixos:trunk-combined)

```
[...]

error: getting status of '/nix/store/2gzyvv5bbapcs0y63swz9l359l42529r-source/nixos/modules/services/web-servers/apache-httpd/tomcat-connector.nix': No such file or directory
(use '--show-trace' to show detailed location information)
```

**Comment by grahamc** [comment]
...annoying... on it.

**Comment by grahamc** [comment]
Hrm?

```
$ grep -ri tomcat-connector.nix
```

**Comment by grahamc** [comment]
```
else import (toString "${toString ./.}/${if svc ? serviceType then svc.serviceType else svc.serviceName}.nix");
```

Good grief!

**Comment by aanderse** [comment]
Sorry team... thanks for taking care of that.

**Pull request merged**
