### PR TITLE
Upgrade the nightly rust on 15.09

### PR DESCRIPTION
**Pull request by grahamc**
- patch prsec for updated tests
- remove the cc / linker patch
###### Things done:
- [X] Tested via `nix.useChroot`.
- [X] Built on platform(s): x86-64.
- [ ] Tested compilation of all pkgs that depend on this change.
- [X] Tested execution of binary products.
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grahamc** [comment]
One thing I'm not sure about is the nix linter says it has a bad name, and has no version. What is an appropriate version and name here?

**Comment by wizeman** [comment]
A few comments:
1. Updates should generally be done on the `master` branch, and if necessary, the commits should later be backported to the `release-15.09`. This means you should rebase your patch on `master`.
2. The attribute `shortVersion` should be set to the date of the `srcRev` commit, so that people know when Rust was last updated.
3. The commit message should also follow the guidelines from `CONTRIBUTING.md`, specifically, it should be named something like `rustcMaster: 2015-08-09 -> 2016-02-xx`
4. Why did you remove the patch that makes `rustc` call the `cc`/`ar` commands with their full path?
It's generally a good idea to do the latter because otherwise, it will pick up whatever is in the path (assuming there even is something in the path), which may or may not be the right `cc`/`ar` command (e.g., if using Nix in a different distro, it will likely pick up the distro's compiler/archiver, which may not even be installed, rather than Nix's).

**Comment by grahamc** [comment]
OK. Thank you for the comments and review, here is my to-do which I'll address ASAP:

 - [ ] re: master, then rebasing to 15.09: OK we can do that. There are several updates then which could have been backported. Since they had not, I thought it was going to be maintained separately for 15.09. I'll resubmit a PR based on master.
 - [ ] re: shortVersion: Makes sense, can-do.
 - [ ] re: commit message: I think I knew this and did it correctly, but a squash later down the road ruined the message. Will fix.
 - [ ] re: cc / ar patches: I wasn't entirely sure it was necessary anymore, and may have misunderstood a different diff I had seen in another tree. I'll restore this (and update the patch, since it no longer applies. May also be fixed by the master rebase.)

**Comment by grahamc** [comment]
@wizeman so the master revision has removed the cc / ar patch as well. That is why I removed it. I've ticked that as completed, but haven't restored it -- simply started off master this time. We could talk about that if it should be restored...

Anywho. I'm about to push an updated branch, which will require a new PR.

**Pull request closed without merging**
