### PR TITLE
elixir_1_12: init

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

elixir 1.12 release

@NixOS/beam I would like to propose something else.
- Keep 4 elixir versions by default (which corresponds to about 2 years). Meaning that after this is merged, we would drop 1.7. If you feel this is too conservative, let me know, I personally don't use anything else than the latest.
- Wait 3 months before making the latest release the default one. I think in 3 months, all the bugs should have appeared.

@minijackson @cw789 @ydlr @Ma27  you might be interested in this

I'll leave this one day open in case anybody is interested.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cw789** [comment]
**Elixir versions within Nixpkgs**
I'm unsure about your proposal. It probably would be better to stick to the Elixir Compatibility and Deprecation policy:
→ [hexdocs.pm/elixir/compatibility-and-deprecations.html](https://hexdocs.pm/elixir/compatibility-and-deprecations.html)

I mean I could get to the point where I still want to upgrade NixOS for security reasons but do not touch my excellent running Elixir application. But I personally would probably update my application anyway - as it always gave no trouble.

If we change it, we should also update the comment:
https://github.com/NixOS/nixpkgs/blob/c03bb4d8126bd36b0a7bdd4454f3687068ab0492/pkgs/development/beam-modules/default.nix#L72-L73

**Default Elixir version within Nixpkgs**
Regarding this I have a different point of view. I would always make the latest version the default one immediately.
As I'm in the opinion that things that might break should anyway always only pin a fixed version.

Things that are allowed to break and use the default version (the latest),
would know in this case 3 months earlier that something will break.

But I know in the world of Nixpkgs this probably makes more trouble to the maintainers
as it would improve the world faster...

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123774` at 4f4c6508 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>elixir_1_12</li>
    <li>tests.trivial</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/interpreters/elixir/generic-builder.nix:19:5:
```
   |
19 |     name = "${baseName}-${version}";
   |     ^
```

Near pkgs/development/interpreters/elixir/generic-builder.nix:21:12:
```
   |
21 |     inherit src version;
   |            ^
```
</li>
  </ul>
</details>

**Comment by minijackson** [comment]
I agree with @cw789 on keeping versions officially supported upstream. I think nixpkgs user are going to expect all stable versions to be packaged and maintained.

On the default version, I would use the latest version, and keep it at the same version for the duration of the NixOS release (i.e. the release track would not change on 20.09, 21.05, etc.), but changes on nixos-unstable, and notify breaking changes on the release notes.

If users are worried of breaking changes, they can still pin the Elixir release track, which we could recommend in the manual.

But breaking changes will happen nonetheless, I think the best we can do is being predictable, by following upstream.

**Comment by happysalada** [comment]
Thanks a lot for both of your feedback. I was not aware of the elixir deprecation schedule, let's stick to that for sure!

I also like the idea of switching the main one to the latest version.

I've defaulted to 1.12.

I'm open to adding something for the next release (21.11), I have to say I don't know where to add it though.

@cw789 I'm not sure what you meant by updating the comment?

**Comment by cw789** [comment]
> I'm not sure what you meant by updating the comment?

I just meant if we'll have a different schedule for removing old versions we should replace the mentioned comment accordingly.

But otherwise everything totally fine.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 123774` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>elixir (elixir_1_12)</li>
    <li>elixir_ls</li>
  </ul>
</details>

**Comment by minijackson** [comment]
At the risk of seeming nitpicky, I think 18 hours is not a lot of time to wait for a change in major version, I could have easily missed that window. But that's just my personal opinion ^^

**Comment by yurrriq** [comment]
let's be sure to document this too, even if if it's just a link to the Elixir deprecation schedule in https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/beam.section.md

**Review by jonringer — APPROVED** [review]
diff lgtm, I'll wait for others.

**Comment by happysalada** [comment]
@minijackson I have no problem with waiting longer, my experience is that if people don't respond within a day, they are busy. I'm happy to wait until next monday.

@yurrriq added docs about the elixir deprecation schedule.

**Comment by happysalada** [comment]
Btw in case people are interested in trying elixir 1.12 in their app. For phoenix apps, I just discovered that there is a need for `libstdc++`, if it can save time to others.
https://github.com/phoenixframework/phoenix/pull/4334

**Pull request merged**
