### PR TITLE
Update argyllcms

### PR DESCRIPTION
**Pull request by samuelrivas**
Update to the latest published version. For some reason I needed to fix jam too as it doesn't compile for me locally

### CODE REVIEW

**Comment by samuelrivas** [comment]
It seems it failed to download, though it works for me...

**Comment by jagajaga** [comment]
I can't download it from my machine too.

**Comment by samuelrivas** [comment]
It seems the author pulled it after he published the newer 1.8.2 version.

I have contacted him to check if there is any archive of old versions, otherwise I guess we'll need some kind of mirror

**Comment by samuelrivas** [comment]
Two problems.

First, the author has limited storage in the server, so he is not willing to keep all versions around and keeps only a subset of them. I could check with 1.8.2 and see if it still builds, but 1.8.1 is gone forever. Anyway, to be safe we would need to host the version that we depend on in some kind of mirror. Is there anything I could use or should I set up my own?

Second, the server rejects curl with 406 now. Apparently there is nothing the author could do to fix that (it is externally hosted), but it means that nix will not be able to pull the source, even if it is there. That could be solved by a separate mirror too.

Another issue is that the author doesn't seem to be very keen on the idea of packaging, so he is not terribly enthusiastic about helping out. He is being very reasonable in the conversation, though, but given all this issues I am thinking of just dropping this PR, I can build locally anyway.

**Comment by jagajaga** [comment]
Nowadays we have no mechanism to deal with that problem :(
I think you can improve this PR for the current version of pkg and maintain it in future?

Curl error --- no ideas how to deal with it.

Leave this PR open for a better time. But don't remove `argyllcms-1.8.1`. I think we will need it in the nearest future.

**Comment by cillianderoiste** [comment]
It looks like it's blocking curl by user agent, adding the following to fetchurl should work:

    curlOpts = "--user-agent ''";

e.g. `curl --user-agent "" http://www.argyllcms.com/Argyll_V1.8.2_src.zip` works, but without overriding the user agent I get a 406.

**Comment by samuelrivas** [comment]
Ah, I didn't know about `curlOpts` that should fix the downloading issue.

What about not having guarantees of the sources not to be removed? I think nixos hosts the sources in hydra once the package builds, right? If that is the case that should also be fine(ish).

I'll try and see if 1.8.2 still builds cleanly and bump the PR if that is the case then.

**Comment by samuelrivas** [comment]
1.8.2 build correctly on my computer after making curl look like mozilla.

**Pull request merged**
