### PR TITLE
bluez also install gatttool

### PR DESCRIPTION
**Pull request by husnoo**
###### Motivation for this change
bluez does not install gatttool by default, although it does build it. 

https://bugzilla.redhat.com/show_bug.cgi?id=1141909

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [yes] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Do we also need `mpris-proxy`? Please reword your commit to `bluez: also install gatttool`

**Comment by bjornfor** [comment]
Seems you have pushed something else to this branch now (simavr).

**Comment by husnoo** [comment]
Hi, i got the impression that git would stick the pull request to the commits at the time of the request, and further work would not be included? I have the branch so I can do my own stuff with nixpkgs... I didn't realise it would add it to this ticket.

**Comment by 7c6f434c** [comment]
GitHub allows you to update the branch with a Pull Request and this updates the Pull Request. GitLab allows the same with their Merge Requests, by the way.

The choice is not on the level of Git, it is determined by the Web UI software anyway.

**Comment by Mic92** [comment]
deprecated by https://github.com/NixOS/nixpkgs/pull/23540

**Pull request closed without merging**
