### PR TITLE
nheko: use qt5's mkDerivation

### PR DESCRIPTION
**Pull request by rawkode**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
cc https://github.com/NixOS/nixpkgs/issues/65399

**Review by worldofpeace — CHANGES_REQUESTED** [review]
This isn't packaged properly according to the qt documentation in nixpkgs
> https://hydra.nixos.org/build/96804884/download/1/nixpkgs/manual.html#sec-language-qt
> Import mkDerivation and Qt (such as qtbase modules directly. Do not import Qt package sets; the Qt versions of dependencies may not be coherent, causing build and runtime failures. 

It imports the qt package set `qt5` and doesn't reference  `qtbase` etc. directly.

Can you fix this @rawcode?

**Comment by rawkode** [comment]
Sorry, missed this @worldofpeace; it's @rawkode with a K :smile: 

Updated as requested

**Comment by worldofpeace** [comment]
> Sorry, missed this @worldofpeace; it's @rawkode with a K :smile:

:rofl: GitHub suggestions do go awry sometimes.

**Review by worldofpeace — APPROVED** [review]
I can launch the executable from the `result` symlink, and I checked that it was wrapped.

Thanks for fixing this @rawkode :sparkles:

**Pull request merged**
