### PR TITLE
rsync: fix regression with _FORTIFY_SOURCE=2

### PR DESCRIPTION
**Pull request by Mic92**
## Description of changes

See https://github.com/WayneD/rsync/issues/511 for details.                        
Not using fetchpatch, because I didn't found a raw link for opensuse's repository.

This had been accidentally merged into master, that's why have reverts...
see https://github.com/NixOS/nixpkgs/pull/265846

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
Will this be backported?

**Comment by Mic92** [comment]
It's already in 23.11.

**Comment by matthiasbeyer** [comment]
Thanks!
So I only have to find out how to redeploy my system without being able to rsync the config to it :laughing:

**Comment by Mic92** [comment]
nix-store -r /nix/store/fjvrv5pw5qr2kz13s7aakl4r94khrkj7-rsync-3.2.7/

**Comment by matthiasbeyer** [comment]
:thinking: what does that do? The manpage does not explain it...

**Pull request merged**
