### PR TITLE
wrapQtAppsHook: use `patchelf --print-interpreter` instead of `isELFExec`

### LINKED ISSUE #68404: wrapQtAppsHook fails to wrap PIEs
**Describe the bug**
Unfortunately, as I just discovered, some executables are built as PIEs (e.g. keepassxc) and these won't be wrapped after this change: https://github.com/nixos/nixpkgs/commit/88146a095f5040b5beb9612c63604493aefa9fd2. PIEs are technically isELFDyn, not isELFExec. Without wrapping, the programs won't start.

Ref. https://github.com/NixOS/nixpkgs/issues/65399.

**To Reproduce**
```
$ nix-build -A keepassxc && ./result/bin/keepassxc
[...]
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
[...]
Aborted (core dumped)
```

**Expected behavior**
PIEs would be wrapped too, and keepassxc would not abort startup.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.71, NixOS, 19.09.git.1a1a7ed (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.03.173426.541d9cce8af"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change
Wrap all executables, even PIEs. Without this change, programs like keepassxc do not start anymore since recent Qt wrapper changes.

Fixes https://github.com/NixOS/nixpkgs/issues/68404.
References https://github.com/NixOS/nixpkgs/issues/65399.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
Am I correct that scripts won't be covered then? I proposed to patch those as well in https://github.com/NixOS/nixpkgs/pull/65372.

**Comment by bjornfor** [comment]
> Am I correct that scripts won't be patched then? I proposed to patch those as well in #65372.

Right, it doesn't wrap scripts, only ELFs. I didn't know about that PR before.

For me, this PR only fixes a regression introduced when the wrapQtAppsHook switched from using isELF to isELFExec, since at that time it stopped wrapping keepassc (and other PIEs).

**Comment by lheckemann** [comment]
so... yes, it does need a backport?

**Comment by worldofpeace** [comment]
Yes @lheckemann, though in my opinion I would have waited for @ttuegel approval of the change...
See https://github.com/NixOS/nixpkgs/pull/68513#issuecomment-530824550

**Comment by bjornfor** [comment]
Backported to relese-19.09: f62222edf895a4b6d11c954775e46ef6f251c468, 29cb637ee080f133e9a422e4706118f61c85848e.

**Comment by ttuegel** [comment]
LGTM :+1: Thanks!

**Comment by matthewbauer** [comment]
Does this mean we should remove isELFExec and isELFDyn? It looks to me like they are not accurate enough to be useful.

**Pull request merged**
