### PR TITLE
WIP: pythonPackages.gunicorn: 19.1.0 -> 19.4.5

### PR DESCRIPTION
**Pull request by desiderius**
Tested with Python 2.7, Python 3.4 & Python 3.5

### CODE REVIEW

**Comment by FRidh** [comment]
Do all dependents still work?

**Comment by FRidh** [comment]
Mock is required as well as a specific version of pytestcov.

Please make sure you've tested the commits before opening a PR, or else mark it as WIP.

**Comment by desiderius** [comment]
Dependencies to be checked:

 - [ ] test aiohttp
 - [ ] review docker_registry (obsolete ?)
 - [ ] test pecan (gunicorn is not listed in requirements.txt)
 - [ ] review syncserver (19.1.1 is listed in requirements.txt)

**Comment by FRidh** [comment]
Please reopen when it is in a state that it can be merged.

**Pull request closed without merging**
