### PR TITLE
python310Packages.paste: disable failing test on Python 3.11

### PR DESCRIPTION
**Pull request by fabaff**
###### Description of changes
Fix build (https://hydra.nixos.org/build/209309492)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 217499` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>gnomecast</li>
    <li>python310Packages.paste</li>
    <li>python310Packages.pastescript</li>
    <li>python310Packages.sqlobject</li>
    <li>python311Packages.paste</li>
    <li>python311Packages.pastescript</li>
    <li>python311Packages.sqlobject</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> My feelings these days is that anybody still using Paste should stop.

Can we remove it?
It seems to be an optional dependency of sqlobject.
Though gnomecast and pastedeploy look like tougher cases.
cc @SuperSandro2000 @emilytrau

**Comment by SuperSandro2000** [comment]
If it is unused sure but if gnomecast is requiring it we can't really.

**Comment by dotlambda** [comment]
> If it is unused sure but if gnomecast is requiring it we can't really.

It doesn't look like gnomecast has a maintainer these days, so maybe it could also be removed.
But I was more interested in your opinion on pastedeploy.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 217499` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>devpi-client</li>
    <li>python310Packages.cypherpunkpay</li>
    <li>python310Packages.pyramid_hawkauth</li>
    <li>python311Packages.buildbot</li>
    <li>python311Packages.buildbot-full</li>
    <li>python311Packages.buildbot-ui</li>
    <li>python311Packages.cypherpunkpay</li>
    <li>python311Packages.pyramid_hawkauth</li>
    <li>python311Packages.splinter</li>
    <li>python311Packages.zope-testbrowser</li>
  </ul>
</details>
<details>
  <summary>64 packages built:</summary>
  <ul>
    <li>ankisyncd</li>
    <li>buildbot (python310Packages.buildbot)</li>
    <li>buildbot-full (python310Packages.buildbot-full)</li>
    <li>buildbot-ui (python310Packages.buildbot-ui)</li>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>devpi-server</li>
    <li>errbot</li>
    <li>gnomecast</li>
    <li>libceph</li>
    <li>pypiserver (python310Packages.pypiserver)</li>
    <li>python310Packages.aiohttp-apispec</li>
    <li>python310Packages.cornice</li>
    <li>python310Packages.deform</li>
    <li>python310Packages.nplusone</li>
    <li>python310Packages.paste</li>
    <li>python310Packages.pastedeploy</li>
    <li>python310Packages.pastescript</li>
    <li>python310Packages.pecan</li>
    <li>python310Packages.plaster-pastedeploy</li>
    <li>python310Packages.pypugjs</li>
    <li>python310Packages.pyramid</li>
    <li>python310Packages.pyramid_chameleon</li>
    <li>python310Packages.pyramid_exclog</li>
    <li>python310Packages.pyramid_jinja2</li>
    <li>python310Packages.pyramid_mako</li>
    <li>python310Packages.pyramid_multiauth</li>
    <li>python310Packages.splinter</li>
    <li>python310Packages.sqlobject</li>
    <li>python310Packages.swift</li>
    <li>python310Packages.webargs</li>
    <li>python310Packages.webdav4</li>
    <li>python310Packages.webtest</li>
    <li>python310Packages.webtest-aiohttp</li>
    <li>python310Packages.wsgidav</li>
    <li>python310Packages.zope-testbrowser</li>
    <li>python311Packages.aiohttp-apispec</li>
    <li>python311Packages.cornice</li>
    <li>python311Packages.deform</li>
    <li>python311Packages.nplusone</li>
    <li>python311Packages.paste</li>
    <li>python311Packages.pastedeploy</li>
    <li>python311Packages.pastescript</li>
    <li>python311Packages.pecan</li>
    <li>python311Packages.plaster-pastedeploy</li>
    <li>python311Packages.pypiserver</li>
    <li>python311Packages.pypugjs</li>
    <li>python311Packages.pyramid</li>
    <li>python311Packages.pyramid_chameleon</li>
    <li>python311Packages.pyramid_exclog</li>
    <li>python311Packages.pyramid_jinja2</li>
    <li>python311Packages.pyramid_mako</li>
    <li>python311Packages.pyramid_multiauth</li>
    <li>python311Packages.sqlobject</li>
    <li>python311Packages.swift</li>
    <li>python311Packages.webargs</li>
    <li>python311Packages.webdav4</li>
    <li>python311Packages.webtest</li>
    <li>python311Packages.webtest-aiohttp</li>
    <li>python311Packages.wsgidav</li>
    <li>qemu_full</li>
    <li>samba4Full</li>
    <li>tribler</li>
  </ul>
</details>

**Comment by fabaff** [comment]
- Fix for `devpi-client` (#218194) is available
- `pyramid_hawkauth` will removed

**Comment by SuperSandro2000** [comment]
> It doesn't look like gnomecast has a maintainer these days, so maybe it could also be removed.
> But I was more interested in your opinion on pastedeploy.

I didn't properly dive into this, if you think removing it is reasonable or have some upstream link to support this, sure.

**Pull request merged**
