### PR TITLE
authy: remove

### LINKED ISSUE #300252: Build failure: Authy
### Steps To Reproduce

1. build *Authy*, stable or unstable channel

### Build log

```console
building '/nix/store/j7v7md0cp58li621jd36qk0f1xnkhzw2-H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_21.snap.drv'...

trying https://api.snapcraft.io/api/v1/snaps/download/H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_21.snap
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   205    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_21.snap from any mirror
error: builder for '/nix/store/j7v7md0cp58li621jd36qk0f1xnkhzw2-H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_21.snap.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/kvlivs4myj4pwbifpl2qbmsx8l2brlym-authy-2.4.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lymka0ll326k2ndisknyyh1hp8iagknd-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/24q0x4gr5ikypwjs20h6099ilpc74l6x-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/adwwkvxi38hriz3pnqa6wgknxxkh51f5-nixos-system-nixos-23.11.5742.219951b495fc.drv' failed to build

```

### Additional context

No additional context, seems like the package of one of the dependencies was taken off snap for some reason

### Notify maintainers
Could not run `nix eval` for some reason...

### Metadata
```console
[stefanidze@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.5541.56528ee42526`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by iAmMrinal0**
desktop apps reached end of life on March 19, 2024 https://web.archive.org/web/20240314234911/https://help.twilio.com/articles/19753631228315

Closes #300252 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by marcusramberg — APPROVED** [review]
lgtm

**Review by Sigmanificient — APPROVED** [review]

**Comment by Aleksanaa** [comment]
Please also remove this:

```
./pkgs/test/config.nix:              tempAllow pkgs.authy "2.1.0" [ "electron-9.4.4" ];
```

**Review by Aleksanaa — COMMENTED** [review]
Please also remove this:

```
./pkgs/test/config.nix:              tempAllow pkgs.authy "2.1.0" [ "electron-9.4.4" ];
```

**Comment by iAmMrinal0** [comment]
> Please also remove this:
> 
> ```
> ./pkgs/test/config.nix:              tempAllow pkgs.authy "2.1.0" [ "electron-9.4.4" ];
> ```

looks like there was only this package in the file. I've removed the file itself and its respective reference. Thanks for catching it.

**Comment by Aleksanaa** [comment]
> looks like there was only this package in the file. I've removed the file itself and its respective reference. Thanks for catching it.

Maybe we should choose another example for this? CC @roberth

**Comment by roberth** [comment]
Thanks for the ping @Aleksanaa. I'm updating the test in
- https://github.com/NixOS/nixpkgs/pull/306498

Please rebase when that's merged.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by roberth** [comment]
You can rebase now.

**Comment by roberth** [comment]
Thanks!

**Pull request merged**
