### PR TITLE
toybox: 0.8.3 -> 0.8.4

### PR DESCRIPTION
**Pull request by kampka**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kampka** [comment]
@ofBorg build toybox

**Comment by SuperSandro2000** [comment]
Fails to build on darwin with:

```
building
build flags: SHELL=/nix/store/k89nm2jva0qmvd970f84wq2iq1iwm9bs-bash-4.4-p23/bin/bash PREFIX=\$\(out\)/bin
scripts/make.sh
Generate headers from toys/*/*.c...
generated/newtoys.h Library probe...........
Make generated/config.h from .config.
generated/flags.h generated/globals.h generated/tags.h generated/help.h
Compile toybox...............lib/portability.c:474:10: warning: unused variable 'offset' [-Wunused-variable]
  int i, offset;
         ^
1 warning generated.
.............................................toys/posix/cp.c:329:30: error: implicit declaration of function 'utimensat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      if (fdout == AT_FDCWD) utimensat(cfd, catch, times, AT_SYMLINK_NOFOLLOW);
                             ^
toys/posix/cp.c:329:30: note: did you mean 'utimes'?
/nix/store/i09q4si3r6ad3iblrdjxfmvl8bks6amg-Libsystem-osx-10.12.6/include/sys/time.h:202:5: note: 'utimes' declared here
int     utimes(const char *, const struct timeval *);
        ^
toys/posix/cp.c:330:12: error: implicit declaration of function 'futimens' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      else futimens(fdout, times);
           ^
toys/posix/cp.c:330:12: note: did you mean 'futimes'?
/nix/store/i09q4si3r6ad3iblrdjxfmvl8bks6amg-Libsystem-osx-10.12.6/include/sys/time.h:190:5: note: 'futimes' declared here
int     futimes(int, const struct timeval *);
        ^
2 errors generated.
toys/posix/cpio.c:215:15: error: implicit declaration of function 'utimensat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        err = utimensat(AT_FDCWD, name, times, AT_SYMLINK_NOFOLLOW);
              ^
toys/posix/cpio.c:215:15: note: did you mean 'utimes'?
/nix/store/i09q4si3r6ad3iblrdjxfmvl8bks6amg-Libsystem-osx-10.12.6/include/sys/time.h:202:5: note: 'utimes' declared here
int     utimes(const char *, const struct timeval *);
        ^
1 error generated.
..make: *** [Makefile:17: toybox] Error 1
```

**Comment by kampka** [comment]
@SuperSandro2000 sorry, I cannot debug Darwin issues, but looking at the toybox code, the errors in question have been present in the codebase for up to six years now.

Maybe someone from @NixOS/darwin-maintainers can take a look at this?

**Comment by r-burns** [comment]
futimes/utimensat require the 10.13 SDK. Should probably not block this update since the SDK update is long pending and this has been broken for a while :/ https://github.com/NixOS/nixpkgs/issues/101229

**Comment by SuperSandro2000** [comment]
> futimes/utimensat require the 10.13 SDK. Should probably not block this update since the SDK update is long pending and this has been broken for a while :/ https://github.com/NixOS/nixpkgs/issues/101229

I should start to work on that again.

**Comment by kampka** [comment]
@SuperSandro2000 @r-burns so, any of you guys feel like approving this? :)
It looks like @hhm0 has not been active in the Nix* community for some time now ...

**Review by r-burns — APPROVED** [review]
Just stopped by to give my 2¢ but I suppose I can give a review too :)

Result of `nixpkgs-review pr 104037` [1](https://github.com/Mic92/nixpkgs-review) on x86_64 (non-NixOS) linux
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>toybox</li>
  </ul>
</details>

Basic toys (echo, cat, printf, sleep, arch, ps) pass sanity checks

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 sorry, I cannot debug Darwin issues, but looking at the toybox code, the errors in question have been present in the codebase for up to six years now.
> 
> Maybe someone from @NixOS/darwin-maintainers can take a look at this?

Can you please mark it as broken on darwin? Then I merge it.

```
broken = stdenv.isDarwin;
```

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104037` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>toybox</li>
  </ul>
</details>

**Comment by kampka** [comment]
> Can you please mark it as broken on darwin? Then I merge it.
> 
> ```nix
> broken = stdenv.isDarwin;
> ```

done

**Comment by kampka** [comment]
@SuperSandro2000 
> Can you please mark it as broken on darwin? Then I merge it.

How about it? :)

**Pull request merged**
