### PR TITLE
python311Packages.repoze-{lru,sphinx-autointerface,who}: rename from repoze_{lru,sphinx_autointerface,who}

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

part of https://github.com/NixOS/nixpkgs/issues/245383

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 266822` at b832f0a3 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/1be84243620a6de8696327ac3674748e">python310Packages.opensfm</a></li>
    <li><a href="https://gist.github.com/natsukium/18241bfbe7b2ffe13f5ad09f6b98b647">python311Packages.opensfm</a></li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li><a href="https://gist.github.com/natsukium/a286d3f648d81a63e89b1bcc23c18b04">samba4Full</a></li>
    <li><a href="https://gist.github.com/natsukium/99ebb64f143a8575674169f9a975a841">samba4Full.dev</a></li>
    <li><a href="https://gist.github.com/natsukium/851b2e586c906b9d23a34c22b79cd68d">samba4Full.man</a></li>
  </ul>
</details>
<details>
  <summary>48 packages built successfully:</summary>
  <ul>
    <li>buildbot</li>
    <li>buildbot-full</li>
    <li>buildbot-ui</li>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev</li>
    <li>ceph.doc</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man</li>
    <li>devpi-client</li>
    <li>devpi-server</li>
    <li>python310Packages.aiohttp-apispec</li>
    <li>python310Packages.cornice</li>
    <li>python310Packages.cypherpunkpay</li>
    <li>python310Packages.deform</li>
    <li>python310Packages.pypugjs</li>
    <li>python310Packages.pyramid</li>
    <li>python310Packages.pyramid-chameleon</li>
    <li>python310Packages.pyramid-exclog</li>
    <li>python310Packages.pyramid-jinja2</li>
    <li>python310Packages.pyramid-mako</li>
    <li>python310Packages.pyramid-multiauth</li>
    <li>python310Packages.repoze-lru</li>
    <li>python310Packages.repoze-sphinx-autointerface</li>
    <li>python310Packages.repoze-who</li>
    <li>python310Packages.routes</li>
    <li>python310Packages.slack-bolt</li>
    <li>python310Packages.webargs</li>
    <li>python310Packages.webhelpers</li>
    <li>python311Packages.aiohttp-apispec</li>
    <li>python311Packages.cornice</li>
    <li>python311Packages.cypherpunkpay</li>
    <li>python311Packages.deform</li>
    <li>python311Packages.pypugjs</li>
    <li>python311Packages.pyramid</li>
    <li>python311Packages.pyramid-chameleon</li>
    <li>python311Packages.pyramid-exclog</li>
    <li>python311Packages.pyramid-jinja2</li>
    <li>python311Packages.pyramid-mako</li>
    <li>python311Packages.pyramid-multiauth</li>
    <li>python311Packages.repoze-lru</li>
    <li>python311Packages.repoze-sphinx-autointerface</li>
    <li>python311Packages.repoze-who</li>
    <li>python311Packages.routes</li>
    <li>python311Packages.slack-bolt</li>
    <li>python311Packages.webargs</li>
    <li>python311Packages.webhelpers</li>
  </ul>
</details>

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 266822` at dd12b6e7 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/bcac28528e36e5480b824060032f3140">python310Packages.opensfm</a></li>
    <li><a href="https://gist.github.com/natsukium/dc382b10d3563c209338a2c070240dcb">python311Packages.opensfm</a></li>
  </ul>
</details>
<details>
  <summary>54 packages built successfully:</summary>
  <ul>
    <li>buildbot</li>
    <li>buildbot-full</li>
    <li>buildbot-ui</li>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev</li>
    <li>ceph.doc</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man</li>
    <li>devpi-client</li>
    <li>devpi-server</li>
    <li>python310Packages.aiohttp-apispec</li>
    <li>python310Packages.cornice</li>
    <li>python310Packages.cypherpunkpay</li>
    <li>python310Packages.deform</li>
    <li>python310Packages.pypugjs</li>
    <li>python310Packages.pyramid</li>
    <li>python310Packages.pyramid-chameleon</li>
    <li>python310Packages.pyramid-exclog</li>
    <li>python310Packages.pyramid-jinja2</li>
    <li>python310Packages.pyramid-mako</li>
    <li>python310Packages.pyramid-multiauth</li>
    <li>python310Packages.repoze-lru</li>
    <li>python310Packages.repoze-sphinx-autointerface</li>
    <li>python310Packages.repoze-who</li>
    <li>python310Packages.routes</li>
    <li>python310Packages.slack-bolt</li>
    <li>python310Packages.webargs</li>
    <li>python310Packages.webhelpers</li>
    <li>python311Packages.aiohttp-apispec</li>
    <li>python311Packages.cornice</li>
    <li>python311Packages.cypherpunkpay</li>
    <li>python311Packages.deform</li>
    <li>python311Packages.pypugjs</li>
    <li>python311Packages.pyramid</li>
    <li>python311Packages.pyramid-chameleon</li>
    <li>python311Packages.pyramid-exclog</li>
    <li>python311Packages.pyramid-jinja2</li>
    <li>python311Packages.pyramid-mako</li>
    <li>python311Packages.pyramid-multiauth</li>
    <li>python311Packages.repoze-lru</li>
    <li>python311Packages.repoze-sphinx-autointerface</li>
    <li>python311Packages.repoze-who</li>
    <li>python311Packages.routes</li>
    <li>python311Packages.slack-bolt</li>
    <li>python311Packages.webargs</li>
    <li>python311Packages.webhelpers</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>samba4Full</li>
    <li>samba4Full.dev</li>
    <li>samba4Full.man</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by natsukium** [comment]
I fixed the commit messages.
`pytho3Packages` -> `python3Packages`

**Review by SuperSandro2000 — APPROVED** [review]
@ofborg eval

**Comment by natsukium** [comment]
@ofborg eval

**Pull request merged**
