### PR TITLE
stdenv: fix unbound NIX_LOG_FD in `nix develop`

### PR DESCRIPTION
**Pull request by tie**
## Description of changes

When running `nix develop` for a package, Nix records the stdenv environment with NIX_LOG_FD set. That is, when the actual development shell runs, it uses the functions that attempt to log to NIX_LOG_FD, but this variable is not actually set.

As a workaround, check whether NIX_LOG_FD is set at runtime.

Example (before this change):
```console
$ nix develop --file . hello
$ echo "${NIX_LOG_FD-unset}"
unset
$ runPhase unpackPhase
bash: "$NIX_LOG_FD": Bad file descriptor
Running phase: unpackPhase
unpacking source archive /nix/store/pa10z4ngm0g83kx9mssrqzz30s84vq7k-hello-2.12.1.tar.gz
bash: "$NIX_LOG_FD": Bad file descriptor
source root is hello-2.12.1
bash: "$NIX_LOG_FD": Bad file descriptor
setting SOURCE_DATE_EPOCH to timestamp 1653865426 of file hello-2.12.1/ChangeLog
```

After this change:
```console
$ nix develop --file . hello
$ runPhase unpackPhase
Running phase: unpackPhase
unpacking source archive /nix/store/pa10z4ngm0g83kx9mssrqzz30s84vq7k-hello-2.12.1.tar.gz
source root is hello-2.12.1
setting SOURCE_DATE_EPOCH to timestamp 1653865426 of file hello-2.12.1/ChangeLog
```

Notice that `bash: "$NIX_LOG_FD": Bad file descriptor` lines are gone.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
Same issue here, but the origin seems to be different.

```
❯ rm -rf .venv && direnv reload
direnv: loading ~/Code/work/python-project/.envrc
direnv: using flake
direnv: nix-direnv: Renewed cache
Executing venvHook
Creating new venv environment in path: './.venv'
/home/pol/.config/direnv/lib/hm-nix-direnv.sh:1792: "$NIX_LOG_FD": Bad file descriptor
Installing dependencies from lock file

Package operations: 71 installs, 0 updates, 0 removals

  - Installing typing-extensions (4.12.2): Pending...
  - Installing typing-extensions (4.12.2)
  - Installing annotated-types (0.7.0)
  ...
```

**Comment by tie** [comment]
>```
>direnv: using flake
>```

@drupol, IIRC nix-direnv (ab)uses `nix develop`, so probably the same underlying issue…

**Review by philiptaron — APPROVED** [review]
Yep.

**Comment by trofi** [comment]
Is it a side-effect of https://github.com/NixOS/nix/issues/8987 by chance?

**Comment by tie** [comment]
>Is it a side-effect of https://github.com/NixOS/nix/issues/8987 by chance?

@trofi, yes, these functions were recorded in a separate derivation where `NIX_LOG_FD` was set. I’m OK with this Nix behavior, but we should probably document that stdenv’s setup.sh and hooks shouldn’t have significant side effects when _sourced_.

**Pull request merged**
