### PR TITLE
signal-desktop: bumps for 19.03

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
signal-desktop on 19.03 complains about the version being expired, and asking to upgrade, so let's do that!

We should probably always backport signal-desktop version bumps to the stable release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by schmittlauch** [comment]
I just ran `nix-review` on this and can confirm it's working fine.

**Comment by primeos** [comment]
@flokli thanks for the backport :)

> We should probably always backport signal-desktop version bumps to the stable release.

Yes, that was a bit unfortunate... :o Normally I backport a bunch of updates ~30 days before the version on the stable channel expires (can e.g. be extracted from `libexec/resources/app.asar` -> `{"buildExpiration":1563316653000}` -> `date --date="@1563316653"` -> Wed Jul 17 00:37:33 CEST 2019). But it seems like I forgot to add a reminder to my calendar after the last backport (probably because there was no backport for 19.03 yet).

Backporting every update individually would unfortunately significantly increase my workload as I don't use a stable channel and have to use VMs for testing (I'm not sure if there was ever a problem, but I don't want to risk it and skip testing). If someone has time for it that would be great, if not I would continue as before and give my best to not miss any backports (could probably add a periodic reminder after that branch-offs as well to add a new reminder for the stable channel).

**Comment by flokli** [comment]
@primeos no worries. Thanks for maintaining :-)

I wasn't aware signal-desktop clients have an expiration date. Maybe we should add this in a comment in the derivation somewhere.

I added a nixos vm test in https://github.com/NixOS/nixpkgs/pull/61916, that does OCR on the "Link your phone to Signal Desktop" message

Assuming you already tested basic functionality on unstable and the vm test on 19.03 passed, I'd consider it highly unlikely this will break in other major ways. But whatever workflow works for you best :-)

**Comment by primeos** [comment]
> I wasn't aware signal-desktop clients have an expiration date. Maybe we should add this in a comment in the derivation somewhere.

Good idea. I'll have a look at this for the next update (maybe I could automate it and use it for reminders as well).

> I added a nixos vm test in #61916, that does OCR on the "Link your phone to Signal Desktop" message

Thanks :)

> Assuming you already tested basic functionality on unstable and the vm test on 19.03 passed, I'd consider it highly unlikely this will break in other major ways. But whatever workflow works for you best :-)

I also think that it's safe to assume that the backport works, if it doesn't crash during the launch due to incompatible dependencies or other problems.

**Comment by flokli** [comment]
I backported to signal test to 19.03 too, so checking should be pretty simple :-)

**Pull request merged**
