### PR TITLE
youtube-dl: 2019.10.16 -> 2019.10.22

### PR DESCRIPTION
**Pull request by xrelkd**
###### Motivation for this change

Update `youtube-dl` to the latest release.
- https://github.com/ytdl-org/youtube-dl/releases/tag/2019.10.22

**NOTE**: Updates to `youtube-dl` should be backported, thanks!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @bluescreen303 @phreedom @AndersonTorres @fuuzetsu @fpletz @enzime

### CODE REVIEW

**Comment by mweinelt** [comment]
> NOTE: Updates to youtube-dl should be backported, thanks!

It would certainly be preferable to have a dedicated pull request for the backport as it should be properly tested as well.

**Comment by mweinelt** [comment]
Running youtube-dl from the build results of nix-review leaves me with this error.

```
[nix-shell:~/.cache/nix-review/pr-71602-2]$ youtube-dl 
Traceback (most recent call last):
  File "/nix/store/mnr7ix39r93m1bw75dkzz0naa72chz0v-python3.7-youtube-dl-2019.10.22/bin/.youtube-dl-wrapped", line 7, in <module>
    from youtube_dl import main
  File "/nix/store/v8xb6ldqq128yafpv2m6j8xdx2dmpq5v-python3.8-youtube-dl-2019.10.22/lib/python3.8/site-packages/youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "/nix/store/v8xb6ldqq128yafpv2m6j8xdx2dmpq5v-python3.8-youtube-dl-2019.10.22/lib/python3.8/site-packages/youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "/nix/store/v8xb6ldqq128yafpv2m6j8xdx2dmpq5v-python3.8-youtube-dl-2019.10.22/lib/python3.8/site-packages/youtube_dl/downloader/__init__.py", line 5, in <module>
    from .hls import HlsFD
  File "/nix/store/v8xb6ldqq128yafpv2m6j8xdx2dmpq5v-python3.8-youtube-dl-2019.10.22/lib/python3.8/site-packages/youtube_dl/downloader/hls.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "/nix/store/knl6l75h1agddyixkjvnkmp89fkniq4g-python3.8-pycryptodome-3.7.3/lib/python3.8/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/nix/store/knl6l75h1agddyixkjvnkmp89fkniq4g-python3.8-pycryptodome-3.7.3/lib/python3.8/site-packages/Crypto/Cipher/_mode_ecb.py", line 47, in <module>
    """
  File "/nix/store/knl6l75h1agddyixkjvnkmp89fkniq4g-python3.8-pycryptodome-3.7.3/lib/python3.8/site-packages/Crypto/Util/_raw_api.py", line 299, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-37m-x86_64-linux-gnu.so': /nix/store/knl6l75h1agddyixkjvnkmp89fkniq4g-python3.8-pycryptodome-3.7.3/lib/python3.8/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.abi3.so': /nix/store/knl6l75h1agddyixkjvnkmp89fkniq4g-python3.8-pycryptodome-3.7.3/lib/python3.8/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.so': /nix/store/knl6l75h1agddyixkjvnkmp89fkniq4g-python3.8-pycryptodome-3.7.3/lib/python3.8/site-packages/Crypto/Util/../Cipher/_raw_ecb.so: cannot open shared object file: No such file or directory
```

**Review by fpletz — APPROVED** [review]
I'm not sure what nix-review is doing there but doing `$(nix-build -A youtubeDL)/bin/youtube-dl` does work for me and downloading YouTube videos seems to work.

**Comment by xrelkd** [comment]
@worldofpeace Could you review this PR? I think it is ready to be merged. Thank you!

**Comment by worldofpeace** [comment]
Notice to reviewers: I don't think you can properly test python applications in nix-review because the nix shell environment it creates will mix python versions breaking the program at runtime.

**Comment by worldofpeace** [comment]
backported in 85c2914ff3d0ed6c822a137d2942dc2af1f2d876.
Also had to do the previous bump a36b4f0ce5b609adaa3ce45eef1b76937cdbd57e.

**Pull request merged**
