### PR TITLE
keybase: 1.0.22 -> 1.0.27

### PR DESCRIPTION
**Pull request by edef1c**
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by edef1c** [comment]
This is probably worth backporting because old versions of the Keybase CLI are entirely unusable now.

**Comment by fpletz** [comment]
This version of keybase fails on 17.03. Does it need a newer version of go?

```
# github.com/keybase/client/go/protocol/keybase1
go/src/github.com/keybase/client/go/protocol/keybase1/extras.go:1403: undefined: sort.Slice
go/src/github.com/keybase/client/go/protocol/keybase1/extras.go:1404: undefined: sort.Slice
go/src/github.com/keybase/client/go/protocol/keybase1/extras.go:1413: undefined: sort.Slice
go/src/github.com/keybase/client/go/protocol/keybase1/extras.go:1420: undefined: sort.Slice
builder for ‘/nix/store/k1avallx2xkh1db67bbajxanrvz23ijz-keybase-1.0.27.drv’ failed with exit code 1
```

**Comment by edef1c** [comment]
@fpletz Yes, `sort.Slice` was added in Go 1.8. I could write a patch to cover for that, though?

**Comment by fpletz** [comment]
That would be cool! I've pushed the release-17.03 branch with the cherry-picks for the updates: https://github.com/mayflower/nixpkgs/tree/keybase-17.03

You can make a PR with a fix on top of that branch against `release-17.03`.

**Pull request merged**
