### PR TITLE
Eliom42

### PR DESCRIPTION
**Pull request by FlorentBecker**
Update ocaml web framework ocsigen to the latest released versions.

### CODE REVIEW

**Comment by FlorentBecker** [comment]
The build failure noticed by travis should be fixed now by https://github.com/NixOS/nixpkgs/commit/4a69e5ae856e727ac9282f08f565e4466f3cc029

**Comment by vbgl** [comment]
It seems that `cohttp` needs to be updated as well (at least to version 0.19.0, according to the release notes).

**Comment by FlorentBecker** [comment]
Which release notes? cohttp is not a dependency of eliom or ocsigen, at least as they are packaged now.

**Comment by vbgl** [comment]
The release notes of [cohttp](https://github.com/mirage/ocaml-cohttp/releases). Updating `lwt` breaks the `cohttp` that is now packaged in `nixpkgs`.

**Comment by FlorentBecker** [comment]
I see, thanks.

**Pull request merged**
