### PR TITLE
frandom: Remove

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
#28643

### CODE REVIEW

**Comment by fpletz** [comment]
> frandom is based on the RC4 encryption algorithm, which is considered secure, and is used by several applications, including SSL.

:hankey: We should rather remove this module. The Linux random generator has improved greatly in 4.x.

**Comment by NeQuissimus** [comment]
@fpletz Done, grep is not finding any references to frandom anymore, so I think I removed everything.

**Comment by fpletz** [comment]
cc @bluescreen303

**Comment by fpletz** [comment]
Thanks!

**Pull request merged**
