### PR TITLE
vimPlugins.coc-flutter: init

### PR DESCRIPTION
**Pull request by workflow**
###### Motivation for this change

Init the [coc-flutter](https://github.com/iamcco/coc-flutter) vim plugin

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
You missed updating vim-plugins and probably some overwrite to integrate the node package.

**Comment by workflow** [comment]
Getting the following when running `./update.py`:

```
920 plugins were checked, 1 plugin(s) could not be downloaded:

lingua-franca.vim: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/farlion/code/nix/nixpkgs/maintainers/scripts/pluginupdate.py", line 471, in prefetch
    plugin, redirect = prefetch_plugin(pluginDesc, cache)
  File "/home/farlion/code/nix/nixpkgs/maintainers/scripts/pluginupdate.py", line 326, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "/home/farlion/code/nix/nixpkgs/maintainers/scripts/pluginupdate.py", line 70, in f_retry
    return f(*args, **kwargs)
  File "/home/farlion/code/nix/nixpkgs/maintainers/scripts/pluginupdate.py", line 124, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
  File "/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

As for overwrites, it seems to be working fine on NixOS without any.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Getting the following when running `./update.py`:

Please check if the branch and repo path are correct.

**Comment by workflow** [comment]
@SuperSandro2000 @midchildan @jonringer This is rebased and should now be good to go

**Comment by SuperSandro2000** [comment]
Please don't reformat the entire file and change `,` around. It only blows up your diff and makes it harder for reviewers to find the actual changes.

**Comment by workflow** [comment]
@SuperSandro2000 thanks for catching, auto-format. Fixing and rebasing.
Would be helpful to have a nix formatter catch this in CI :)

**Pull request merged**
