### PR TITLE
redpanda: 22.3.5 -> 22.3.11

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

package update

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Why the hash is only updated for x86_64-darwin?

**Comment by happysalada** [comment]
I was thinking of using the ci as a cheat to tell me the hash for the other platform. That clearly failed as the ci skipped the build.

**Comment by happysalada** [comment]
ok, I've just done the hash update manually.

**Comment by happysalada** [comment]
closes #213672

**Review by wegank — APPROVED** [review]
Tested on aarch64-darwin.

**Comment by c4milo** [comment]
I can help test on Darwin arm64. I'm a nix newbie, though, I would appreciate some directions

**Comment by happysalada** [comment]
you can check here, what is the latest commit on unstable
https://status.nixos.org/
It should take another couple of days I think. (depending on how many packages the build farm has in the queue).

also, I forgot to mention, but this package only includes rpk, and not redpanda unfortunately. I never got to packaging redpanda, which is a more arduous task.

**Comment by c4milo** [comment]
Awesome, @happysalada thank you!. I'm a staff engineer with Redpanda, please shoot me a message over at camilo@redpanda.com. We would love to send you Redpanda swag, if you want of course!

**Comment by happysalada** [comment]
Amazing to see someone from redpanda interested in Nix!
One day if I see the redpanda team at a conference, I'll definitely ask from some swag! In the meanwhile, I'll refrain from sending physical things across the world (Climate change and stuff).
If you ever need help merging a PR related to redpanda, feel free to ping me.
Amazing product that you guys have! (A couple of people have asked for the full redpanda binary, but that is definitely above my C++ compilation level, happy to review anything related to it of course).

**Comment by emaxerrno** [comment]
dropping by to say thank you @happysalada .

**Comment by happysalada** [comment]
From the man himself ! Much appreciated ! Best of luck with the amazing product !

**Pull request merged**
