### PR TITLE
src.meta.changelog

### PR DESCRIPTION
**Pull request by zimbatm**
## Description of changes

I'm playing with some ideas inspired by #338301.

What if meta attributes were derived from the source?

In particular, the `meta.changelog` is a computed value, so having it in the code isn't very valuable as it's not directly accessible.

This also fixed the issue that when `src` gets overridden, the `meta.changelog` is out of sync.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
I like the idea in principle, but I think we still need to track some information in the package definition, because not all projects use GitHub releases (an in‐repo changelog is usually more useful when available, in fact).

**Comment by zimbatm** [comment]
What would be the downside of having false-negative changelog URLs? Package can still override `meta.changelog` with its definition.

Or alternatively, if the stdenv patch is dropped, packages could opt-in with:
```
meta = {
  inherit (src.meta) changelog;
}
```

**Comment by emilazy** [comment]
I think exposing broken changelog URLs to users would be kind of bad, but I like the idea of `inherit (src.meta) changelog;`.

**Comment by zimbatm** [comment]
After mulling on this more, even `inherit (src.meta) changelog` seems too implicit. How would the user know it points to the release unless they read the code?

Maybe a better direction would be a lib that builds common URLs, and maybe used like this:
```
meta = {
  changelog = lib.urls.github.repo_release src;
};
```

Not a priority so I'm closing this for now

**Comment by zimbatm** [comment]
For the spelunkers, see also #35075

**Pull request closed without merging**
