### PR TITLE
python312Packages.pyside2: use python.pkgs.distutils

### PR DESCRIPTION
**Pull request by dotlambda**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @Pleune

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Pleune** [comment]
What have you done to test this? It seems like an improvement, but I think I tried essentially the same and it did not work. I believe it was because setuptools does not actually create the fake distutils module until it has itself been imported, so I needed to figure out a way to first import setuptools for each file. But maybe my understanding was confused...

But if this is now working without the absurd replacing, that would be great.

I will test this with with my app on Monday.

**Comment by Pleune** [comment]
Relevant:  https://github.com/NixOS/nixpkgs/pull/327976#discussion_r1767894143

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 342948` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>natron</li>
    <li>python312Packages.pyside2-tools</li>
  </ul>
</details>
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>freecad</li>
    <li>freecad-wayland</li>
    <li>napari (python312Packages.napari)</li>
    <li>napari.dist (python312Packages.napari.dist)</li>
    <li>patray</li>
    <li>patray.dist</li>
    <li>python311Packages.magicgui</li>
    <li>python311Packages.magicgui.dist</li>
    <li>python311Packages.napari</li>
    <li>python311Packages.napari-npe2</li>
    <li>python311Packages.napari-npe2.dist</li>
    <li>python311Packages.napari.dist</li>
    <li>python311Packages.pyside2</li>
    <li>python311Packages.pyside2-tools</li>
    <li>python312Packages.magicgui</li>
    <li>python312Packages.magicgui.dist</li>
    <li>python312Packages.napari-npe2</li>
    <li>python312Packages.napari-npe2.dist</li>
    <li>python312Packages.pyside2</li>
    <li>python312Packages.shiboken2</li>
    <li>renderdoc</li>
    <li>sl1-to-photon</li>
    <li>sl1-to-photon.dist</li>
  </ul>
</details>

**Comment by Pleune** [comment]
I tested this in my use case and it is working perfectly the same 👍

**Pull request merged**
