### PR TITLE
nodePackages: update to latest

### LINKED ISSUE #248366: Update request: pnpm 8.5.1 → 8.6.x
- Package name: `nodePackages_latest.pnpm` or `nodePackages.pnpm`
- Latest released version: 8.6.12
- Current version on the unstable channel: 8.6.11
- Current version on the stable/release channel: 8.5.1
- [x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@happysalada 
@dotlambda 

Personal note: Having both `nodePackages_latest.pnpm` or `nodePackages.pnpm` doesn't make any sense in either of the branches, if they're both pointing to the same version (both are 8.5.1 in release and 8.6.11 in unstable branch).

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by happysalada**
## Description of changes

update node-packages to latest.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
closes https://github.com/NixOS/nixpkgs/issues/248366

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 248402` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>emacsPackages.lsp-bridge</li>
  </ul>
</details>
<details>
  <summary>45 packages built:</summary>
  <ul>
    <li>bat-extras.prettybat</li>
    <li>commitlint</li>
    <li>concurrently</li>
    <li>create-cycle-app</li>
    <li>emanote</li>
    <li>emanote.data</li>
    <li>graphite-cli</li>
    <li>haskellPackages.emanote</li>
    <li>haskellPackages.emanote.data</li>
    <li>haskellPackages.emanote.doc</li>
    <li>haskellPackages.tailwind</li>
    <li>haskellPackages.tailwind.doc</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>lighthouse</li>
    <li>lv_img_conv</li>
    <li>mastodon-bot</li>
    <li>node2nix</li>
    <li>nodehun</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>wasm-text-gen</li>
    <li>wrangler</li>
    <li>yaml-language-server</li>
  </ul>
</details>

**Review by tjni — APPROVED** [review]
LGTM. I think the single failure in nixpkgs-review is due to my Mac being in sandbox mode. Something was hanging so I killed the process.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 248402` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>code-server</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>teleprompter</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>67 packages built:</summary>
  <ul>
    <li>bat-extras.prettybat</li>
    <li>breitbandmessung</li>
    <li>commitlint</li>
    <li>concurrently</li>
    <li>create-cycle-app</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>emanote</li>
    <li>emanote.data</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>graphite-cli</li>
    <li>haskellPackages.emanote</li>
    <li>haskellPackages.emanote.data</li>
    <li>haskellPackages.emanote.doc</li>
    <li>haskellPackages.tailwind</li>
    <li>haskellPackages.tailwind.doc</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>lighthouse</li>
    <li>lv_img_conv</li>
    <li>mastodon-bot</li>
    <li>morgen</li>
    <li>node2nix</li>
    <li>nodehun</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>pulsar</li>
    <li>pyright</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>redoc-cli</li>
    <li>slack</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>vscode-fhs</li>
    <li>vscode-langservers-extracted</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wasm-text-gen</li>
    <li>wrangler</li>
    <li>yaml-language-server</li>
  </ul>
</details>

**Pull request merged**
