### PR TITLE
tracker-miners: 3.5.3 -> 3.5.4

### PR DESCRIPTION
**Pull request by the-furry-hubofeverything**
## Description of changes

https://gitlab.gnome.org/GNOME/tracker-miners/-/compare/3.5.3...3.5.4

Includes improvements to the seccomp jail, and fixes for spurious SIGSYS positives, including the one encountered on my system https://github.com/the-furry-hubofeverything/hubble-systems/issues/14

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by the-furry-hubofeverything** [comment]
It's running on my laptop, and I'm currently doing `nixpkgs-review`...

**Comment by the-furry-hubofeverything** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>dropbox-cli</li>
    <li>dropbox-cli.nautilusExtension</li>
    <li>eiciel</li>
    <li>eiciel.nautilusExtension</li>
    <li>gnome-photos</li>
    <li>gnome-photos.installedTests</li>
    <li>gnome.file-roller</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-control-center.debug</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.nautilus-python.dev</li>
    <li>gnome.nautilus-python.devdoc</li>
    <li>gnome.nautilus-python.doc</li>
    <li>gnome.nautilus.dev</li>
    <li>gnome.nautilus.devdoc</li>
    <li>gnomeExtensions.gtk4-desktop-icons-ng-ding</li>
    <li>nautilus-open-any-terminal</li>
    <li>nautilus-open-any-terminal.dist</li>
    <li>pantheon.file-roller-contract</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>tracker-miners</li>
  </ul>
</details>

**Review by IogaMaster — APPROVED** [review]

**Review by rvl — APPROVED** [review]
I have tested this PR and with v3.5.4 the fs miner seems to work as well as it did before.

**Comment by jtojnar** [comment]
Bumped in
https://github.com/NixOS/nixpkgs/commit/e4271d0b7290dcd8707023194426eb4933e4b97a

**Pull request closed without merging**
