### PR TITLE
restool: 20.12 → 2.4

### PR DESCRIPTION
**Pull request by danc86**
###### Description of changes

Updates restool to ~LSDK 21.08, which appears to be the latest release if I understand their versioning scheme.~ the latest upstream commit.

There's unfortunately no upstream changelog, just the git history:
https://source.codeaurora.org/external/qoriq/qoriq-components/restool/log/?h=LSDK-21.08
But it appears to be just new commands and options, and some fixes.

~In this PR I also included a backport of an unreleased commit which is needed to use restool with the latest fsl_dpaa2_switch kernel driver. Let me know if you'd prefer not to include that and I can take it out.~

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danc86** [comment]
Result of `nixpkgs-review pr 182203` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>restool</li>
  </ul>
</details>

**Comment by delroth** [comment]
One thing that's been on my TODO list for this package is changing to the "more official" versioning scheme for restool. In this case, it would be v2.3 according to what's in the Makefile for the tag you're fetching. WDYT? I'm also fine with doing that in a followup PR.

This would align us with the versioning convention used by Fedora and SUSE, the other two distros packaging restool at this point. Note also that Fedora is packaging a v2.4 from a random git commit, we could pick up the same version (abd2f5b).

I'm slightly -1 on vendoring a patch here, I think this might be better as an override in your personal nixos config, but could be convinced otherwise. If we go for v2.4 it might be that this isn't needed at all anymore too...

**Comment by delroth** [comment]
(https://repology.org/project/restool/versions other distros with restool)

**Comment by danc86** [comment]
Hmm yeah I was a bit unsure about that. Upstream seems to have made a bit of a mess here. It doesn't help that they don't publish release notes, or releases. They seem to have stopped updated the `master` branch, the most recent tag on there follows the (old?) `LSDK-YY.MM` convention. Instead they seem to be developing on the `integration` branch, it's the most recently modified branch.

The arbitrary commit that Fedora has packaged is actually the tip of that branch, one commit after this one:

```
commit 7be71e7d0d0bce3c317c82308247ac901b8aa436
Author: Ioana Ciornei <ioana.ciornei@nxp.com>
Date:   Tue Oct 26 14:46:58 2021 +0300

    restool: increment version to v2.4

    Increment the restool version.
```

so it seems pretty reasonable to take that as a 2.4 "release". It seems to be as close to an actual release as NXP is going to bother with.

**Comment by danc86** [comment]
Amended the PR to use the same commit as Fedora and call it version 2.4.

**Review by delroth — APPROVED** [review]
Finally had time to do some testing on my Honeycomb, LGTM. Thank you!

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 182203` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>restool</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 182203` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>restool</li>
  </ul>
</details>

**Comment by arachnist** [comment]
I just had to go back to version 20.12 (didn't reboot in a long while…), because 2.4 broke `ls-listni` and `ls-addni` on my honeycomb. The commands from 2.4 just return:
```shell
[nix-shell:~]# ls-listni
MC error: Unsupported operation (status 0xb)
MC error: Unsupported operation (status 0xb)
dprc.1/dpni.4 (interface: eth4)
MC error: Unsupported operation (status 0xb)
MC error: Unsupported operation (status 0xb)
dprc.1/dpni.3 (interface: eth3)
MC error: Unsupported operation (status 0xb)
MC error: Unsupported operation (status 0xb)
dprc.1/dpni.2 (interface: eth2)
MC error: Unsupported operation (status 0xb)
MC error: Unsupported operation (status 0xb)
dprc.1/dpni.1 (interface: eth1)
MC error: Unsupported operation (status 0xb)
MC error: Unsupported operation (status 0xb)
dprc.1/dpni.0 (interface: eth0)
```

**Comment by delroth** [comment]
That's because your MC firmware is too old, and unfortunately it doesn't look like restool maintains backwards compatibility...

**Pull request merged**
