### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by flokli** [comment]
@FRidh can we sneak in #66725 here as well? It's another big rebuild, and was just an hour too late ;-)

**Comment by vcunat** [comment]
`qt5.qtbase` on darwin: https://github.com/NixOS/nixpkgs/pull/66266#issuecomment-523131781

**Comment by vcunat** [comment]
Relatively a lot of remaining [build regressions since master](https://hydra.nixos.org/eval/1538653?compare=1538611#tabs-now-fail) are due to some python packages.  Otherwise the qtbase problem (above) still holds, and several Qt apps won't build (probably easy, details in the same thread).

**Comment by flokli** [comment]
@vcunat can you cherry pick #66725 in here? That's another stdenv rebuild, which should make the `wrapQtAppsHook` a bit smarter, and should probably be done before branching off 19.09.

**Comment by vcunat** [comment]
Rebuild-wise, the current commit is almost all finished.  It might be better to merge to master and reiterate, though the currently remaining number of build regressions worries me a little.

**Pull request merged**
