### PR TITLE
[20.09] gomplate: init at 3.8.0

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
Backport of #99402

Yes, this is me trying to sneak a new package into the soon-to-be-stable branch post freeze, but in my defence, it's a leaf package and shouldn't affect anything else.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by davidak — CHANGES_REQUESTED** [review]
##### Reviewed points

- [X] package path fits guidelines
- [X] package name fits guidelines
- [X] package version fits guidelines
- [X] package build on x86_64
- [X] executables tested on x86_64
- [X] `meta.description` is set and fits guidelines
- [X] `meta.license` fits upstream license
- [ ] `meta.platforms` is set
- [X] `meta.maintainers` is set
- [ ] build time only dependencies are declared in `nativeBuildInputs`
- [X] source is fetched using the appropriate function
- [X] phases are respected
- [ ] patches that are remotely available are fetched with `fetchpatch`

##### Possible improvements

Can you add  `meta.platforms`? Or does it come from `buildGoModule`?

##### Comments

Except that, looks good :sparkles:

**Comment by risicle** [comment]
I _would_ have if asked on `master`, but this is just a backport and it doesn't seem worth diverging the branches for...

**Comment by davidak** [comment]
yes, it has to be added on master first. maybe in another pr

**Review by davidak — APPROVED** [review]

**Comment by aanderse** [comment]
I don't think you need to declare `platforms` for `go` packages because it inherits... maybe? Someone should verify that.

@risicle it's perfectly acceptable to backport leaf packages like this during a release. There isn't any impact, like you said.

**Pull request merged**
