### PR TITLE
qt6.qtbase: patch for loading libXcursor

### LINKED ISSUE #181176: Telegram on Wayland doesnt use system cursor theme.
### Describe the bug
On Wayland (with QT_QPA_PLATFORM=wayland), Telegram doesn't use the system cursor theme.

### Steps To Reproduce
1. Open Wayland with QT_QPA_PLATFORM=wayland set
2. notice how the cursor doesn't use the system's cursor theme and instead uses a simple, small black cursor theme

### Expected behavior
Telegram on wayland should use the system's cursor theme.

### Screenshots
Screenshot from 2022-07-11 20-22-13
Screenshot from 2022-07-11 20-22-46
Here it's on wayland
Screenshot from 2022-07-11 20-23-43
Screenshot from 2022-07-11 20-23-46
Here it's on Xwayland.

### Additional context
Also just noticed that it only renders like half the cursor or 75% of the cursor, but screenshots seem to make the cursor render correctly. 

### Notify maintainers
@oxalica 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.10-zen1, NixOS, 22.11 (Raccoon), 22.11pre390948.5f43d8b088d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by NickCao**
###### Description of changes
Fixes https://github.com/NixOS/nixpkgs/issues/181176 on xorg, (maybe also on wayland, I cannot reproduce this)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by leiserfg** [comment]
Thankfully you found how to inject it, I tried a few hours ago with `LD_LIBRARY_PATH` but that didn't work.

**Comment by Hentioe** [comment]
Tested that this patch works, hope to merge it soon

**Review by niknetniko — APPROVED** [review]
Works for me

**Comment by leiserfg** [comment]
What is required in order to get this merged? Is there a way to help?

**Review by ttuegel — APPROVED** [review]

**Pull request merged**
