### PR TITLE
ran gnome-exntensions's update-extensions.py script after gnome-shell44 update

### PR DESCRIPTION
**Pull request by NoelGisler**
###### Description of changes

exactly as the title says.
after the update of gnome43 -> gnome44 i saw a lot of my extensions that are updated were not yet updated in the NixOS repo, so i ran the update script.
probably updated a lot of extensions.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by piegamesde** [comment]
"probably updated a lot of extensions" 11 according to the diff, to be precise :)

LGTM

**Comment by Neon-44** [comment]
Oh hey, 1 line = 1 extension. That's convenient. Almost like it was done intentionally  🤔.

So that's why the file is so cramped. Makes a lot of sense now lol.

**Comment by piegamesde** [comment]
Oh, I almost forgot: please rename the commit to `gnomeExtensions: auto-update`

**Comment by Neon-44** [comment]
done.

am also going to update the script to print a message " please name commit message: 'gnomeExtensions: auto-update' " or similar at the end, so future updaters know what to commit.

**Comment by piegamesde** [comment]
The correct place to document this would be in the folder's README.

**Comment by Neon-44** [comment]
alright, I'll open a new PR if i ever get around to it.

this one looks good so far?

**Pull request merged**
