### PR TITLE
radare2-cutter: 1.1 -> 1.2

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

cc @dtzWill 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build radare2-cutter

**Comment by dtzWill** [comment]
https://github.com/NixOS/nixpkgs/pull/33198#issuecomment-366558419 :(

What I remember of the details:

* desktop file is broken-- submitted issue and upstream fixed it (trivial capitalization problem)
* top bar is too small / cuts off text within

IIRC it also died on some inputs that worked previously, but I can't find them currently.

Upstream seems to have fixed both of these, but also requires using a newer radare2.

Tried git version ~2 weeks ago, here's that branch: https://github.com/dtzWill/nixpkgs/tree/feature/r2-cutter-1.2-git .

Will update to latest git shortly and see how that goes...

**Comment by Mic92** [comment]
@dtzWill should I revert this update?

**Comment by dtzWill** [comment]
I suppose so, yes, but I'm happy leaving it as-is as well.  It's not the /most/ broken :).  Thanks!

**Comment by Mic92** [comment]
@dtzWill see c16936c2a2fb9020cfa37462905b4238b1fd5a72

**Pull request merged**
