### PR TITLE
vim: add lspkind-nvim, auto-session, compe-tabnine; fix minimap-vim duplicate tag

### PR DESCRIPTION
**Pull request by onsails**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 111954` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.airline (vimPlugins.vim-airline)</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.denite (vimPlugins.denite-nvim)</li>
    <li>vimPlugins.deoplete-vim-lsp</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.galaxyline-nvim</li>
    <li>vimPlugins.git-messenger-vim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lspkind-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.nvim-compe</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.sql-nvim</li>
    <li>vimPlugins.tcomment_vim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.vim-erlang-tags</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-lsc</li>
    <li>vimPlugins.vim-ruby</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 111954` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.denite (vimPlugins.denite-nvim)</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-lsp</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.deoplete-vim-lsp</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.galaxyline-nvim</li>
    <li>vimPlugins.lspkind-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.nvim-compe</li>
    <li>vimPlugins.nvim-lightbulb</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.oceanic-next</li>
    <li>vimPlugins.unite (vimPlugins.unite-vim)</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-pencil</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Comment by jonringer** [comment]
not related to your changes, but
```
https://github.com/NixOS/nixpkgs/pull/111954

1 package failed to build:
vimPlugins.minimap-vim

48 packages built:
spacevim vimPlugins.YouCompleteMe vimPlugins.ale vimPlugins.aniseed vimPlugins.auto-session vimPlugins.chadtree vimPlugins.coc-explorer vimPlugins.compe-tabnine vimPlugins.conjure vimPlugins.defx-nvim vimPlugins.denite vimPlugins.deoplete-fish vimPlugins.deoplete-khard vimPlugins.deoplete-lsp vimPlugins.deoplete-nvim vimPlugins.deoplete-vim-lsp vimPlugins.fern-vim vimPlugins.galaxyline-nvim vimPlugins.gentoo-syntax vimPlugins.ghcid vimPlugins.gitgutter vimPlugins.gitsigns-nvim vimPlugins.lsp-status-nvim vimPlugins.lspkind-nvim vimPlugins.lspsaga-nvim vimPlugins.lualine-nvim vimPlugins.neoformat vimPlugins.nvim-compe vimPlugins.nvim-dap vimPlugins.nvim-lightbulb vimPlugins.nvim-lspconfig vimPlugins.nvim-lsputils vimPlugins.nvim-treesitter vimPlugins.nvim-ts-rainbow vimPlugins.oceanic-next vimPlugins.popfix vimPlugins.telescope-nvim vimPlugins.unite vimPlugins.vim-clap vimPlugins.vim-floaterm vimPlugins.vim-pencil vimPlugins.vim-plug vimPlugins.vim-smoothie vimPlugins.vim-snippets vimPlugins.vimspector vimPlugins.vimtex vimPlugins.vista-vim vimPlugins.zephyr-nvim
```

**Comment by onsails** [comment]
> not related to your changes, but
> 
> ```
> https://github.com/NixOS/nixpkgs/pull/111954
> 
> 1 package failed to build:
> vimPlugins.minimap-vim
> 
> 48 packages built:
> spacevim vimPlugins.YouCompleteMe vimPlugins.ale vimPlugins.aniseed vimPlugins.auto-session vimPlugins.chadtree vimPlugins.coc-explorer vimPlugins.compe-tabnine vimPlugins.conjure vimPlugins.defx-nvim vimPlugins.denite vimPlugins.deoplete-fish vimPlugins.deoplete-khard vimPlugins.deoplete-lsp vimPlugins.deoplete-nvim vimPlugins.deoplete-vim-lsp vimPlugins.fern-vim vimPlugins.galaxyline-nvim vimPlugins.gentoo-syntax vimPlugins.ghcid vimPlugins.gitgutter vimPlugins.gitsigns-nvim vimPlugins.lsp-status-nvim vimPlugins.lspkind-nvim vimPlugins.lspsaga-nvim vimPlugins.lualine-nvim vimPlugins.neoformat vimPlugins.nvim-compe vimPlugins.nvim-dap vimPlugins.nvim-lightbulb vimPlugins.nvim-lspconfig vimPlugins.nvim-lsputils vimPlugins.nvim-treesitter vimPlugins.nvim-ts-rainbow vimPlugins.oceanic-next vimPlugins.popfix vimPlugins.telescope-nvim vimPlugins.unite vimPlugins.vim-clap vimPlugins.vim-floaterm vimPlugins.vim-pencil vimPlugins.vim-plug vimPlugins.vim-smoothie vimPlugins.vim-snippets vimPlugins.vimspector vimPlugins.vimtex vimPlugins.vista-vim vimPlugins.zephyr-nvim
> ```

I've just commited fix to upstream and its patch here

**Comment by jonringer** [comment]
yep, noticed it changed as I hit submit.

I would prefer to give upstream some time to merge, then do another updated. want to avoid a another PR where the patch has to be removed.

**Comment by onsails** [comment]
upstream pr merged, I've re-submitted update.

**Comment by onsails** [comment]
Result of `nixpkgs-review pr 111954` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>55 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aniseed</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.compe-tabnine</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.denite (vimPlugins.denite-nvim)</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-lsp</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.deoplete-vim-lsp</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.galaxyline-nvim</li>
    <li>vimPlugins.gentoo-syntax</li>
    <li>vimPlugins.ghcid</li>
    <li>vimPlugins.gitgutter (vimPlugins.vim-gitgutter)</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.lsp-status-nvim</li>
    <li>vimPlugins.lspkind-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.nvim-compe</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-lightbulb</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-lsputils</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.oceanic-next</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.popfix</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.unite (vimPlugins.unite-vim)</li>
    <li>vimPlugins.vim-LanguageTool</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-oscyank</li>
    <li>vimPlugins.vim-pencil</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-smoothie</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.vista-vim</li>
    <li>vimPlugins.zephyr-nvim</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 111954 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package failed to build:</summary>  <ul>    <li>vimPlugins.minimap-vim</li>  </ul></details><details>  <summary>48 packages built:</summary>  <ul>    <li>spacevim</li>    <li>vimPlugins.YouCompleteMe</li>    <li>vimPlugins.ale</li>    <li>vimPlugins.aniseed</li>    <li>vimPlugins.auto-session</li>    <li>vimPlugins.chadtree</li>    <li>vimPlugins.coc-explorer</li>    <li>vimPlugins.compe-tabnine</li>    <li>vimPlugins.conjure</li>    <li>vimPlugins.defx-nvim</li>    <li>vimPlugins.denite (vimPlugins.denite-nvim)</li>    <li>vimPlugins.deoplete-fish</li>    <li>vimPlugins.deoplete-khard</li>    <li>vimPlugins.deoplete-lsp</li>    <li>vimPlugins.deoplete-nvim</li>    <li>vimPlugins.deoplete-vim-lsp</li>    <li>vimPlugins.fern-vim</li>    <li>vimPlugins.galaxyline-nvim</li>    <li>vimPlugins.gentoo-syntax</li>    <li>vimPlugins.ghcid</li>    <li>vimPlugins.gitgutter (vimPlugins.vim-gitgutter)</li>    <li>vimPlugins.gitsigns-nvim</li>    <li>vimPlugins.lsp-status-nvim</li>    <li>vimPlugins.lspkind-nvim</li>    <li>vimPlugins.lspsaga-nvim</li>    <li>vimPlugins.lualine-nvim</li>    <li>vimPlugins.neoformat</li>    <li>vimPlugins.nvim-compe</li>    <li>vimPlugins.nvim-dap</li>    <li>vimPlugins.nvim-lightbulb</li>    <li>vimPlugins.nvim-lspconfig</li>    <li>vimPlugins.nvim-lsputils</li>    <li>vimPlugins.nvim-treesitter</li>    <li>vimPlugins.nvim-ts-rainbow</li>    <li>vimPlugins.oceanic-next</li>    <li>vimPlugins.popfix</li>    <li>vimPlugins.telescope-nvim</li>    <li>vimPlugins.unite (vimPlugins.unite-vim)</li>    <li>vimPlugins.vim-clap</li>    <li>vimPlugins.vim-floaterm</li>    <li>vimPlugins.vim-pencil</li>    <li>vimPlugins.vim-plug</li>    <li>vimPlugins.vim-smoothie</li>    <li>vimPlugins.vim-snippets</li>    <li>vimPlugins.vimspector</li>    <li>vimPlugins.vimtex</li>    <li>vimPlugins.vista-vim</li>    <li>vimPlugins.zephyr-nvim</li>  </ul></details>

**Comment by jonringer** [comment]
it pulled from the previous review comment, all packages were successful

**Pull request merged**
