### PR TITLE
Add Novena platform support

### PR DESCRIPTION
**Pull request by Jookia**
###### Motivation for this change

This set of patches adds the 'novena' platform, the 'novena' variant and 'novena' u-boot package. With this you can now run NixOS on your Novena! At least as a terminal, there's still a lot more to be done.

Pinging @viric for possible review on this since I've spoken about this before
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Sent from my Novena. ;)

### CODE REVIEW

**Comment by copumpkin** [comment]
https://www.crowdsupply.com/sutajio-kosagi/novena for context

**Comment by Jookia** [comment]
Closing for now- I don't think I'll have time to maintain this.

**Comment by Jookia** [comment]
I'm going to reopen this as I do in fact have time to maintain this.

**Comment by Mic92** [comment]
Do you still want this to be merged?

**Comment by Jookia** [comment]
On Sat, Jun 10, 2017 at 03:21:04PM -0700, Jörg Thalheim wrote:
>    Do you still want this to be merged?

At the moment I don't have a board to test this with, so not at the moment.
Might be worth closing it until I do another one that involves platform-specific
hacks.

**Comment by c0bw3b** [comment]
@Jookia I will close this one for the moment (it's conflicting with recent merges anyway).
But feel free to open a new PR when you have a chance to finalize Novena support. :)

**Pull request closed without merging**
