### PR TITLE
plasma5Packages: restrict platforms

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

Extracted from #227274. Should have close to zero rebuilds.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by alyssais — CHANGES_REQUESTED** [review]
Few, if any, of these are actually Linux-specific.  I'd be very surprised if gruvbox-dark-icons is, for example, and Baloo definitely isn't.  Try using Repology to see if any BSDs have things packaged before marking them as Linux-only.

**Comment by wegank** [comment]
Thanks! I'm marking the platforms according to https://api.kde.org/frameworks/. I'm now only marking BluezQt, ModemManagerQt and NetworkManagerQt as Linux-only, and other frameworks Linux+FreeBSD-only.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 228016` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>19 packages marked as broken and skipped:</summary>
  <ul>
    <li>ajour</li>
    <li>dfilemanager</li>
    <li>kaffeine</li>
    <li>krunner-pass</li>
    <li>krunner-translator</li>
    <li>latte-dock</li>
    <li>libsForQt5.alkimia</li>
    <li>libsForQt5.falkon</li>
    <li>libsForQt5.tokodon</li>
    <li>lightly-qt</li>
    <li>ludusavi</li>
    <li>maia-icon-theme</li>
    <li>plasma-pass</li>
    <li>plasma5Packages.alkimia</li>
    <li>plasma5Packages.falkon</li>
    <li>plasma5Packages.tokodon</li>
    <li>quassel</li>
    <li>quasselClient</li>
    <li>virt-manager-qt</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>libsForQt5.phonon (plasma5Packages.phonon)</li>
    <li>libsForQt5.phonon.dev (plasma5Packages.phonon.dev)</li>
  </ul>
</details>

**Comment by wegank** [comment]
`libsForQt5.phonon` has been marked as broken, so this PR does not trigger new builds.

**Pull request merged**
