### PR TITLE
Add documentation for XFCE

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

Adressing https://github.com/NixOS/nixpkgs/issues/13340

---

I don't know how to test-build the docs. Please tell me.

@garbas pinging you as creator of #13340.

### CODE REVIEW

**Comment by abbradar** [comment]
To build the docs:

`nix-build -A manual.x86_64-linux nixpkgs/nixos/release.nix`

**Comment by matthiasbeyer** [comment]
Does not build for me, but I don't know what the problem is.

**Comment by vcunat** [comment]
```diff
diff --git a/nixos/doc/manual/configuration/xfce.xml b/nixos/doc/manual/configuration/xfce.xml
index d406616bae..ac9b784824 100644
--- a/nixos/doc/manual/configuration/xfce.xml
+++ b/nixos/doc/manual/configuration/xfce.xml
@@ -34,7 +34,7 @@
         XFCE programs are not installed automatically.
         To install them manually (system wide), put them into your
         <literal>environment.systemPackages</literal>-
-    <para>
+       </para>
 
     <para>
         NixOS’s default <emphasis>display manager</emphasis> (the
```

**Comment by matthiasbeyer** [comment]
Applied, thanks.

Tell me if I should rebase and fixup.

**Comment by vcunat** [comment]
I merged a slightly modified version in the meantime.

**Comment by matthiasbeyer** [comment]
Okay, thanks!

**Comment by vcunat** [comment]
It seemed nice.  We can improve later, possibly.

**Pull request closed without merging**
