### PR TITLE
broot: 0.10.2 -> 0.11.8

### PR DESCRIPTION
**Pull request by evanjs**
###### Motivation for this change
[Changes from 0.10.2 -> 0.11.8](https://github.com/Canop/broot/compare/v0.10.2...v0.11.8)
- Add shell completions made available via https://github.com/Canop/broot/commit/16a9cba1910b6d1615e80d70fcad1c0c5cef8be6
- [v0.11.7](https://github.com/Canop/broot/releases/tag/v0.11.7) also fixes a dangerous [bug](https://github.com/Canop/broot/issues/104).
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @magnetophon

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build broot

**Comment by teh** [comment]
It looks like this tool has some hardcoded `/bin` paths [1] which don't work on NixOS.

[1]
https://github.com/Canop/broot/blob/d6d3face3677b133e04a515ef0816603733cf111/src/verb_store.rs#L94

**Comment by manveru** [comment]
0.11.5 is out already :)

**Comment by evanjs** [comment]
> 0.11.5 is out already :)

Gah.  I'll bump this then.
___
Before that, @teh (or anybody with input), what about something like this? 
``` diff
+  postPatch = ''
+    substituteInPlace src/verb_store.rs \
+      --replace '/bin/cp' "${coreutils}/bin/cp" \
+      --replace '/bin/mkdir' "${coreutils}/bin/mkdir" \
+      --replace '/bin/mv' "${coreutils}/bin/mv" \
+      --replace '/bin/rm' "${coreutils}/bin/rm"
+  '';
```

There are hardlinks in the docs as well, but I don't know if we need to worry about those.

**Comment by manveru** [comment]
I'd recommend something like this:
```
  postPatch = ''
    substituteInPlace src/verb_store.rs --replace '"/bin/' '"${coreutils}/bin/'
  '';
```

**Comment by evanjs** [comment]
> I'd recommend something like this:
> 
> ```
>   postPatch = ''
>     substituteInPlace src/verb_store.rs --replace '"/bin/' '"${coreutils}/bin/'
>   '';
> ```

Derp. Good call.

Just the version and hardlinks for now, then?

**Comment by manveru** [comment]
Yeah, it works fine for me so far with this patch.

**Comment by magnetophon** [comment]
lol, we're up to [0.11.6](https://github.com/Canop/broot/releases/tag/v0.11.6) now!

**Comment by evanjs** [comment]
> lol, we're up to [0.11.6](https://github.com/Canop/broot/releases/tag/v0.11.6) now!

That had better be the last update for now 😜

**Comment by magnetophon** [comment]
[No such luck.](https://github.com/Canop/broot/releases/tag/v0.11.7)
This version fixes the dangerous bug #104. People using a previous version must upgrade.

**Comment by evanjs** [comment]
Cleaned, squased, rebased, etc.
Let me know if you guys can think of anything else.
Thanks for keeping me up to date!

**Comment by evanjs** [comment]
Added shell completion scripts per https://github.com/Canop/broot/commit/16a9cba1910b6d1615e80d70fcad1c0c5cef8be6 and bumped to [v0.11.8](https://github.com/Canop/broot/releases/tag/v0.11.8).
Feel free to let me know if there's a cleaner way to determine `$OUT_DIR`.

**Pull request merged**
