### PR TITLE
nixos/https-dns-proxy: system level support for DNS over HTTPS

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Further to #81365.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by NeQuissimus — APPROVED** [review]

**Comment by NeQuissimus** [comment]
Can this be merged?

**Comment by peterhoeg** [comment]
There are some pending items from the linked PR that I haven't gotten around to fixing up yet.

**Comment by peterhoeg** [comment]
This is good to go @pvgoran & @vcunat. This PR addresses the issues raised by @Mic92 on https://github.com/NixOS/nixpkgs/pull/81365

**Comment by vcunat** [comment]
I see no problem at a quick glance.  The only idea is that from the big providers I'd probably personally prefer Quad9 as the first choice.

**Comment by peterhoeg** [comment]
Didn't know of quad9, sure, added.

**Comment by NeQuissimus** [comment]
LGTM. Is there an easy VM test we could provide?

**Comment by vcunat** [comment]
I guess you could configure some resolver service to serve DoH (only, e.g. `services.kresd.listenDoH`) and add some static hints to get content you can query, then add this proxy on top of it and try resolving the content through the proxy.

**Comment by peterhoeg** [comment]
It definitely should ahve a test but I'll only be able to work on that on the weekend.

**Comment by peterhoeg** [comment]
Despite there being no tests, is everyone OK with merging this? As it's new functionality, there should be no regressions.

**Comment by vcunat** [comment]
I'm not against, just not interested.

**Pull request merged**
