### PR TITLE
texlive: fix texlive fonts for xetex

### PR DESCRIPTION
**Pull request by apfelkuchen6**
###### Description of changes
XeTeX relies on the system's font managent tooling to locate fonts. This means that XeTeX was unable to find the fonts distributed with texlive as these weren't installed in paths searched by the system's font configuration.

This PR fixes this ~~for linux~~ by wrapping xetex such that the `FONTCONFIG_FILE` environment value is set to a suitable fontconfig file generated by `makeFontsConf`. This file is almost identical to the one from the fontconfig package and 
`/etc/fonts/fonts.conf ` on NixOS -- it only adds the texlive font directories. In particular this means that all the actual
configuration files in /`etc/fonts/conf.d` are still included and there also is a `/usr/share/fonts` font directory entry for use with non-NixOS linuxes, so it's unlikely that this breaks someone's setup.

~~Darwin remains broken since XeTeX doesn't use fontconfig there.~~

This also exposes texlive's font directory as a passthru-attribute, which makes adding texlive's fonts to the `fonts.fonts.` nixos-option (or symlinking the directory to `~/Library/fonts` on MacOS with home-manager) a lot easier.

As the wrapper uses `--set-default`, devShells can easily override the font directories to add more fonts. For example in the shell
```nix
{ pkgs ? import <nixpkgs> {} }:
let
  texlive = pkgs.texlive.combined.scheme-full;
  systemfontdirs = with pkgs; map toString [ comic-mono crimson ];
in pkgs.mkShell {
    nativeBuildInputs = [ texlive ];
    # used by xetex and mtx-fonts (context)
    FONTCONFIG_FILE = pkgs.makeFontsConf { fontDirectories = systemfontdirs ++ [ texlive.fonts ]; };
    # used by luaotfload (lualatex)
    OSFONTDIR = pkgs.lib.concatStringsSep "//:" systemfontdirs;
}
```
the document
```tex
\documentclass{article}
\usepackage{mwe,fontspec}
\begin{document}
\fontspec{Crimson} \blindtext % "system" font
\fontspec{STIX Two Text} \blindtext % texlive font
\end{document}
```
compiles with both `lualatex` and `xelatex`. (It's a bit unfortunate that luaotfload hardcodes the fontconfig location to `/etc/fonts/fonts.conf` and `/usr/local/etc/fonts/fonts.conf`, so a separate environment variable has to be used, but at least it works).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by veprbl — APPROVED** [review]
Looks good. I don't see why it won't work on darwin.

**Comment by apfelkuchen6** [comment]
After digging a bit more into it, I think that it should probably also work for darwin. 

TeXLive's binary distribution builds XeTeX with the font manager provided by Mac OS's native font framework (from `ApplicationServices`), but since we don't provide this as a build input, it [should fall back to using fontconfig](https://github.com/texlive/texlive-source/blob/master/texk/web2c/configure.ac#L137). 

It would be great if someone with access to a Mac (@xworld21) could confirm.

**Comment by apfelkuchen6** [comment]
> @apfelkuchen6 If you give me the steps, I have an aarch64-darwin system I can test on

That would be great.
If the the following succeeds, it should also work on Darwin:
```
cd $(mktemp -d)
nix --experimental-features 'nix-command flakes' build github:apfelkuchen6/nixpkgs/texlive-xetex-fonts#texlive.combined.scheme-medium
cat > test.tex <<EOF
\documentclass{article}
\usepackage{fontspec}
\setmainfont{TeX Gyre Termes}
\begin{document}
This is a test document.
\end{document}
EOF
./result/bin/xelatex test.tex
```

**Comment by veprbl** [comment]
Should we add a test for this?

**Comment by xworld21** [comment]
> Should we add a test for this?

Bonus points if we have a generic `mkTeXLiveTest` that takes combined scheme, engine, the content of a TeX file, and compiles (with things like `-halt-on-error`, `-interaction-mode=nonstopmode`). There are other tests we can run this way, e.g. hyphenation stuff, I have some of those stashed somewhere.

**Review by xworld21 — APPROVED** [review]
Cool! I tested this in a pure shell, and XeLaTeX works (Darwin x86-64). Great job. I find the hardcoded values in `makeFontsConf` slightly troubling, but if that's what Nixpkgs uses, then it's right to use it here as well.

However, always on Darwin, I am not able to use Lucida Grande. Probably because we are using fontconfig instead of the native solution, and we may have to improve on that. But this PR is only making things better, so let's start from here.

**Comment by xworld21** [comment]
PS: https://github.com/NixOS/nixpkgs/blob/6b843da7083794787d5d098dbabd909dbf26daee/pkgs/development/libraries/fontconfig/make-fonts-conf.xsl#L42-L44
this is probably where `/System/Library/Fonts`, `/Library/Fonts`, `~/Library/Fonts` should be added, guarded with an XSLT parameter so that they are used on Darwin only (list of folders taken from Homebrew's fontconfig).

**Comment by apfelkuchen6** [comment]
> Bonus points if we have a generic mkTeXLiveTest that takes combined scheme, engine, the content of a TeX file, and compiles (with things like -halt-on-error, -interaction-mode=nonstopmode). There are other tests we can run this way, e.g. hyphenation stuff, I have some of those stashed somewhere.

I really like this idea, but not in this PR :).  I have piggy-backed a simple test onto the similar luaotfload-test for now.

**Review by veprbl — APPROVED** [review]

**Comment by veprbl** [comment]
@GrahamcOfBorg build tests.texlive

**Pull request merged**
