### PR TITLE
flowtime: fix build

### PR DESCRIPTION
**Pull request by arthsmn**
## Description of changes

This reverts some parts of [an older PR](https://github.com/NixOS/nixpkgs/pull/272124) that made the app unusable, as well as adding a dependency.

Fixes: https://github.com/NixOS/nixpkgs/pull/272124#issuecomment-1866926457

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pokon548** [comment]
Dig through the original issue further, it looks like it will only breaks on machine without gstreamer.
In fact, both https://github.com/NixOS/nixpkgs/pull/272124 and https://github.com/NixOS/nixpkgs/pull/275906 *works* on my machine, tested using `nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'` or `nix-build . -A flowtime`.
Not sure why this happens. However I will test this pr soon :)

**Comment by arthsmn** [comment]
> Dig through the original issue further, it looks like it will only breaks on machine without gstreamer. In fact, both #272124 and #275906 _works_ on my machine, tested using `nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'` or `nix-build . -A flowtime`. Not sure why this happens. However I will test this pr soon :)

That must be why I haven't gotten this when I made the old PR. Thanks for the clarification!

**Review by CactiChameleon9 — APPROVED** [review]
Tested working on my system :)

**Review by pokon548 — APPROVED** [review]
Result of `nixpkgs-review pr 275906` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flowtime</li>
  </ul>
</details>

Also manually tested binary on ```nixpkgs-review``` environment, works without gstreamer issue.

**Pull request merged**
