### PR TITLE
pythonPackage.eth-utils: 1.2.1 -> 1.4.1 & pythonPackage.eth-typing: 1.3.0 -> 2.0.0

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

Upgrade Python package `eth-utils`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jluttine** [comment]
Added upgrade of `eth-typing` to the same pull request.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build python3Packages.eth-typing pythonPackages.eth-utils python3Packages.eth-utils

**Review by worldofpeace — DISMISSED** [review]
Your commit msg's should be
pythonPackage**s** not pythonPackage

**Comment by worldofpeace** [comment]
Darn didn't correct the pr title :rofl:

**Pull request merged**
