### PR TITLE
poetry: fix build on x86_64-darwin

### LINKED ISSUE #253971: Build failure: poetry
### Steps To Reproduce and Build Logs

```console
[user@system:~]$ nix run nixpkgs#poetry
error: builder for '/nix/store/0l35ir5wsvaxlx533v6ymi8xs9fnisp8-python3.10-poetry-core-1.7.0.drv' failed with exit code 1;
       last 10 log lines:
       > source root is source
       > setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/vendors/pyproject.toml
       > patching sources
       > applying patch /nix/store/b4w2fblzs0xfpmr6wp4abka4cmnipr51-0bdf29e9631fda9436066a07ca8e69a4aa97a31e.patch
       > patching file Makefile
       > patching file src/poetry/core/_vendor/pkgutil_resolve_name.LICENSE
       > patching file src/poetry/core/_vendor/pkgutil_resolve_name.py
       > patching file src/poetry/core/_vendor/vendor.txt
       > Hunk #1 FAILED at 2.
       > 1 out of 1 hunk FAILED -- saving rejects to file src/poetry/core/_vendor/vendor.txt.rej
       For full logs, run 'nix log /nix/store/0l35ir5wsvaxlx533v6ymi8xs9fnisp8-python3.10-poetry-core-1.7.0.drv'.
error: 1 dependencies of derivation '/nix/store/jgsky3npdajsib388vfxfxxkwdn10ifn-python3.10-iso8601-1.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yf4156dv2ad2c3gwbnp2mwc5npx2z5y1-python3.10-pkgconfig-1.5.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p0igifqj08r9jl9fvag5lmr85l7y14yq-python3.10-poetry-plugin-export-1.5.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pqxgl0wrblyy4f707adccb89bm2j26h1-python3.10-pytest-httpserver-1.0.7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bmdi2r0lm0wzhy8paa9yxysp3vgb98gx-python3.10-sh-2.0.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hy3mka6wk0wcq69zkyaybw3np2f7iva2-python3.10-tomlkit-0.12.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d3fprycwhd5j85jrdd4pahyivijiw037-python3.10-faust-cchardet-2.1.19.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kfk82bwlkhwp1m63zig5m9796bkfdp0d-python3.10-python-dotenv-1.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v0a98p9r2bz7k53maya7l3r991slijcb-python3.10-responses-0.23.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ffdpkgnhkcnzysq589za82vnspjq3lnb-python3.10-flit-3.9.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/242bbqry0mf3ygza38b24dwbpp4z1n0w-flit-build-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p9qvvcf931zy8m2wljwymsj02xcwfjld-python3.10-more-itertools-9.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9jmfqbdwidq6gpvijfqiq94z7j1hwbk8-python3.10-jaraco-classes-3.1.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mi2g7nkxys09ly1syrc459dra30949x9-python3.10-jaraco-functools-3.6.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7cgpajy2yz48qqr55sy0cx5lirjk2hcx-python3.10-keyring-24.2.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vaniv9smv7s4jqai9xzlw7m6bb03ia8s-python3.10-tempora-5.5.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vnwwvvwbg99ki9f54lz9dp73nzh7njcj-python3.10-portend-3.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6a1wlayz3ldlx3cla9ac52xwazs6zw0d-python3.10-cleo-2.0.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7cyf8b3iq9c2nkn1ns60v9770a7g47ic-python3.10-clevercsv-0.8.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d8x531qky94q601knzpsykkr16ca39fq-python3.10-deepdiff-6.3.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1dvbj63njl5wyg2q01l534yf7z1f71k8-python3.10-cryptography-41.0.3.drv' failed to build
error: 2 dependencies of derivation '/nix/store/yglfnf17qk1ab5rysxcil2c3n1i5c2cs-python3.10-dnspython-2.4.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y99gkglfj433zb86iyx194q5si02dj3k-python3.10-pyopenssl-23.2.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fky8cyhq1q0pg0f4s4r17hd7i8dm08fb-python3.10-service-identity-23.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r7ssvvy49qp5q80q540d2mfsb3rvqndh-python3.10-email-validator-1.3.1.drv' failed to build
error: 3 dependencies of derivation '/nix/store/sqvxkfhcpimfwc76q7qqzg9iaxjy1g5a-python3.10-trustme-0.9.0.drv' failed to build
error: 2 dependencies of derivation '/nix/store/gxl5dj96qkjzp7pzrwd054m0yal3j8np-python3.10-pydantic-1.10.9.drv' failed to build
error: 2 dependencies of derivation '/nix/store/c6gs85x3dm505p8yfinkdw64iwczhzk5-python3.10-requests-toolbelt-1.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rli1vm4qjy273m5n38vbj62jldkiy7x0-python3.10-inflect-6.0.4.drv' failed to build
error: 2 dependencies of derivation '/nix/store/vfrrwx19pzs4546qnm4yv4mbazvc66c3-python3.10-jaraco-text-3.11.1.drv' failed to build
error: 5 dependencies of derivation '/nix/store/1y8y7npx14vd90601kzi1wpc9z1f2gp8-python3.10-cheroot-9.0.0.drv' failed to build
error: 2 dependencies of derivation '/nix/store/xnv8m2bacpdwfh429bafpp5ww2y5vgra-python3.10-jaraco-collections-4.3.0.drv' failed to build
error: 5 dependencies of derivation '/nix/store/lfhqj0qkmlp0ywrgy2lqrisq5dwyxgn4-python3.10-cherrypy-18.8.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1f9vr9h69ih6pfr6mwv85sn161wa172y-python3.10-cachecontrol-0.13.1.drv' failed to build
error: 8 dependencies of derivation '/nix/store/0xn2584qxcykaji4n8443qba81vvin71-python3.10-poetry-1.6.1.drv' failed to build

[user@system:~]$ nix log /nix/store/0l35ir5wsvaxlx533v6ymi8xs9fnisp8-python3.10-poetry-core-1.7.0.drv
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-build-hook
Using pypaBuildPhase
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing pytest-check-hook
Using pytestCheckPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/9z8f8cqkhbdq6pr4xcmx2c77byk3nfc2-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/vendors/pyproject.toml
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/b4w2fblzs0xfpmr6wp4abka4cmnipr51-0bdf29e9631fda9436066a07ca8e69a4aa97a31e.patch
patching file Makefile
patching file src/poetry/core/_vendor/pkgutil_resolve_name.LICENSE
patching file src/poetry/core/_vendor/pkgutil_resolve_name.py
patching file src/poetry/core/_vendor/vendor.txt
Hunk #1 FAILED at 2.
1 out of 1 hunk FAILED -- saving rejects to file src/poetry/core/_vendor/vendor.txt.rej
```

### Additional context

Only happened to me on Darwin (x86_64).

### Notify maintainers

@jbaum98 @dotlambda

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/xrj5ikp417580r5g9m1shz9dk787szns-source`
```

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
fixes #253971 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @mirkolenz @moonshxne

### CODE REVIEW

**Comment by mirkolenz** [comment]
Thank you for the quick response! Just out of curiosity: Why is an empty list of patches needed here? And why is this not an issue on Linux machines?

**Comment by dotlambda** [comment]
> Why is an empty list of patches needed here? And why is this not an issue on Linux machines?

https://github.com/NixOS/nixpkgs/blob/e72d1a3ac4ed85c4acd33259dc8e551d7c108a72/pkgs/development/python-modules/poetry-core/default.nix#L31-L66

**Comment by dotlambda** [comment]
For some reason `poetry.python.pkgs.deepdiff` fails to build:
```
=================================== FAILURES ===================================
______________________ TestDiffOther.test_repeated_timer _______________________

self = <tests.test_diff_other.TestDiffOther object at 0x1133c97e0>
MockDiffLevel = <MagicMock name='DiffLevel' id='4625369840'>

    @mock.patch('deepdiff.diff.DiffLevel', side_effect=SlowDiffLevel)
    def test_repeated_timer(self, MockDiffLevel):
        t1 = [1, [2]]
        t2 = [1, [3]]

        progress_logger = mock.Mock()
        DeepDiff(t1, t2, log_frequency_in_sec=0.02, progress_logger=progress_logger)
>       assert PROGRESS_MSG.format(0, 0, 0) == progress_logger.call_args[0][0]
E       TypeError: 'NoneType' object is not subscriptable

tests/test_diff_other.py:28: TypeError
```

**Comment by dotlambda** [comment]
For now let's just disable deepdiff's tests.
@NixOS/darwin-maintainers Someone has to get rid of the poetry-core patches or we'll have to mark it broken on x86_64-darwin very soon.

**Pull request merged**
