### PR TITLE
Elasticsearch 7.8.1

### PR DESCRIPTION
**Pull request by fadenb**
###### Motivation for this change

Update to a more recent version of the Elk stack in order to be able to load Kibana dashboards of parsedmarc (#92836).

*Known issues*: I am unable to locate a 7.8.1 compatible version of the search-guard plugin. There seems to be something called search-guard-suite but I am not sure whether this is the same. @offlinehacker you seem to have added it initially, can you provide some guidance?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 96533` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>elasticsearch7</li>
    <li>elasticsearch7-oss</li>
    <li>filebeat7</li>
    <li>heartbeat7</li>
    <li>journalbeat7</li>
    <li>kibana7</li>
    <li>kibana7-oss</li>
    <li>logstash7</li>
    <li>logstash7-oss</li>
    <li>metricbeat7</li>
    <li>packetbeat7</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
ping @apeschar @basvandijk

**Comment by thefloweringash** [comment]
See also https://github.com/NixOS/nixpkgs/pull/114456 for v7.11.1

**Comment by happysalada** [comment]
the elk stack is on 7.10.2 on master. I think this can be closed.
Please re-open if you feel this hasn't been addressed.
(I've got a PR with some fixes which could use some feedback if you are interested https://github.com/NixOS/nixpkgs/pull/136255)

**Pull request closed without merging**
