### PR TITLE
jetbrains: updates

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by raboof** [comment]
Result of `nixpkgs-review pr 108389` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108389` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
11 packages built:
</summary>
<ul>
<li>jetbrains.clion</li>
<li>jetbrains.datagrip</li>
<li>jetbrains.goland</li>
<li>jetbrains.idea-community</li>
<li>jetbrains.idea-ultimate</li>
<li>jetbrains.phpstorm</li>
<li>jetbrains.pycharm-community</li>
<li>jetbrains.pycharm-professional</li>
<li>jetbrains.rider</li>
<li>jetbrains.ruby-mine</li>
<li>jetbrains.webstorm</li>
</ul>
</details>

**Comment by raboof** [comment]
Testing idea-community lightly, didn't notice any obvious problems

**Comment by Gerschtli** [comment]
idea-ultimate (with dwm as window manager) exits with following error, after some interactions:

```
$> idea-ultimate 
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2021-01-05 13:11:38,427 [   2642]   WARN - llij.ide.plugins.PluginManager - Problems found loading plugins:
  The BashSupport (id=BashSupport, path=~/.local/share/JetBrains/IntelliJIdea2020.3/BashSupport, version=1.8.0.202) plugin Plugin 'BashSupport' (version '1.8.0.202') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.6682.168
  The NixIDEA (id=nix-idea, path=~/.local/share/JetBrains/IntelliJIdea2020.3/NixIDEA, version=0.3.0.3) plugin Plugin 'NixIDEA' (version '0.3.0.3') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.6682.168 
2021-01-05 13:11:39,730 [   3945]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=de.espend.idea.php.toolbox.remote.RemoteListenerComponent) 
2021-01-05 13:11:54,188 [  18403]   WARN - tartup.impl.StartupManagerImpl - Activities registered via registerPostStartupActivity must be dumb-aware: org.jetbrains.plugins.scala.lang.psi.impl.toplevel.synthetic.SyntheticClassesListener$$Lambda$2042/0x0000000101c32440@77cd00d 
2021-01-05 13:11:54,327 [  18542]   WARN -                 Symfony-Plugin - missing at least one container file 
[xcb] Unknown sequence number while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: xcb_io.c:153: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
/nix/store/2zjp1i1k6m4drys56cbcbaz0mhxpml3i-idea-ultimate-2020.3.1/idea-ultimate-2020.3.1/bin/idea.sh: line 230: 246753 Aborted                 (core dumped) "$JAVA_BIN" -classpath "$CLASSPATH" ${VM_OPTIONS} "-XX:ErrorFile=$HOME/java_error_in_idea_%p.log" "-XX:HeapDumpPath=$HOME/java_error_in_idea_.hprof" "-Didea.vendor.name=${PRODUCT_VENDOR}" "-Didea.paths.selector=${PATHS_SELECTOR}" "-Djb.vmOptionsFile=$VM_OPTIONS_FILE" ${IDE_PROPERTIES_PROPERTY} -Didea.jre.check=true com.intellij.idea.Main "$@"
```

**Comment by raboof** [comment]
> idea-ultimate (with dwm as window manager) exits with following error, after some interactions

Interesting, I've been using idea-community from this PR (with notion as window manager) for a while and didn't have problems so far - you'd expect them to be pretty similar in how they interact with xcb.

Perhaps we should roll back the ultimate upgrade until someone has time to look into this properly?

**Comment by raboof** [comment]
> I have this issue since 3.0, I just found out

Ah ok

> maybe it is affecting only few people or just me, but I cannot figure out, what is the cause..

Possibly... are you using nixos with home-manager/nix-env or do you install idea system-wide?

**Comment by Gerschtli** [comment]
The setup with said problem is a ubuntu 20.04 with idea installed via home-manager. Another setup of mine with NixOS installed does not have any issues. Maybe it is a problem with xcb, but I do not know anything about it..

**Comment by aespinosa** [comment]
experiencing the same with idea-community as well by just running it directly from `/nix/store/...*idea-community-2020.3.1/bin/idea-community`

This is with Ubuntu 20.04 on WSL2

**Comment by raboof** [comment]
interesting pattern that it's both on Ubuntu 20.04. Since it doesn't seem directly related this PR, perhaps open an issue for it?

I wouldn't know where to begin debugging this, I'm afraid, though...

**Pull request merged**
