### PR TITLE
python.pkgs.werkzeug: 0.14.1 -> 0.15.1

### LINKED ISSUE #33093: Werkzerg reloader crashes due to Nix wrapped scripts
## Issue description

Werkzerg (a python framework; used by Flask for example) has a function that reloads the server while you are developing it.  This crashes on NixOS, since it is wrapped as a shell script:

```
 * Serving Flask app "main"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
  File "/nix/store/ya4r3zvl1abad8rkql804q9slhbp3n5d-python3.6-Flask-0.12.2/bin/flask", line 2
    export PATH=/nix/store/839vm39v1wnb6zw0hn66g834n08735yg-python3-3.6.3/bin:/nix/store/ya4r3zvl1abad8rkql804q9slhbp3n5d-python3.6-Flask-0.12.2/bin:/nix/store/wl6gn1ll6zfxpv3k7a6aq7sdq47f0xzx-python3.6-setuptools-36.4.0/bin${PATH:+:}$PATH
              ^
SyntaxError: invalid syntax
```

Werkzerg tried to reload the app based on `sys.argv[0]`; however, this is mangled by NixOS and does not point to the real python script.

### Steps to reproduce

Using flask (aka. `nix-env -i python3.6-Flask`)

Create a file `main.py`:

```python3
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
    return 'Hello World'
```

Attempt to run it with the reloader:

```
FLASK_APP=main.py flask run --reloader
```

Currently, it will crash with the error as above:

```
 * Serving Flask app "main"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
  File "/nix/store/ya4r3zvl1abad8rkql804q9slhbp3n5d-python3.6-Flask-0.12.2/bin/flask", line 2
    export PATH=/nix/store/839vm39v1wnb6zw0hn66g834n08735yg-python3-3.6.3/bin:/nix/store/ya4r3zvl1abad8rkql804q9slhbp3n5d-python3.6-Flask-0.12.2/bin:/nix/store/wl6gn1ll6zfxpv3k7a6aq7sdq47f0xzx-python3.6-setuptools-36.4.0/bin${PATH:+:}$PATH
              ^
SyntaxError: invalid syntax
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 17.09.2281.b4a0c011e81 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2281.b4a0c011e81"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
fixes #33093

Does this warrant a backport?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @samdroid-apps @teozkr

### CODE REVIEW

**Comment by dotlambda** [comment]
@GrahamcOfBorg eval

@GrahamcOfBorg build python2.pkgs.werkzeug python3.pkgs.werkzeug

**Comment by FRidh** [comment]
> Does this warrant a backport? that requires testing all reverse dependencies

**Comment by dotlambda** [comment]
> > Does this warrant a backport?
> 
> that requires testing all reverse dependencies

I'm not interested in doing that. So I'd say we don't backport unless someone asks us to.

**Comment by dotlambda** [comment]
This breaks octoprint:
```
ImportError: cannot import name cached_property
```
cc @abbradar @peterhoeg

**Comment by peterhoeg** [comment]
That's not a big deal - we can just pin werkzeug for octoprint. Would you mind doing that @dotlambda ?

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python2.pkgs.buildbot-full python3.pkgs.buildbot-full

**Pull request merged**
