### PR TITLE
ns-usbloader: init at 7.0

### LINKED ISSUE #85652: Package request: ns-usbloader
**Project description**
Software for interacting with a Nintendo Switch running custom firmware. Can install homebrew software over USB or the network, as well as send boot payloads.

**Metadata**

* homepage URL: https://developersu.blogspot.com/search/label/NS-USBloader
* source URL: https://github.com/developersu/ns-usbloader
* license: GPL-3.0+
* platforms: unix, linux, darwin,

### PR DESCRIPTION
**Pull request by soupglasses**
## Description of changes

Created a new package ns-usbloader versioned at 7.0.

Closes #85652

## Things done

* Ensured it works with Nintendo Switch hardware correctly.
* Applied an extra patch to ensure the generated `.jar` file is reproducible. May get upstreamed down the line.

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by soupglasses** [comment]
One strange issue i hit when moving this project from my personal tree to nixpkgs was that the `mvnHash` changed. Further, using `applyPatches` of this PR will also change the `mvnHash` and fail to build. I am not sure if this is expected behaviour of `maven.buildMavenPackage` or if there is something funky i need to patch further in `pom.xml`.

**Comment by soupglasses** [comment]
Building it directly against this PR's hash works correctly. So I am unsure what is going on when it gets used as a patch. :thinking:

**Comment by soupglasses** [comment]
Yeah. hmm. There is most definetly something wrong with how its pulling dependencies. Just look at [the OfBorg logs for "ns-usbloader.passthru.tests on aarch64-linux"](https://logs.ofborg.org/?key=nixos/nixpkgs.245931&attempt_id=4b6cf273-382d-41a6-b6d4-a5ab1d40ce39).

```
error: hash mismatch in fixed-output derivation '/nix/store/qidgfnjhiwi9dyiacrcmbc73m6ifi0h5-ns-usbloader-7.0-maven-deps.drv':
         specified: sha256-vXZAlZOh9pXNF1RL78oQRal5pkXFRKDz/7SP9LibgiA=
            got:    sha256-xC+feb41EPi30gBrVR8usanVULI2Pt0knztzNagPQiw=
```

I am not sure what is going on.

**Comment by soupglasses** [comment]
Doing ` nix-build /nix/store/jx6920dp838289g67bwqd5vkwcxf9bf2-ns-usbloader-7.0-maven-deps.drv --check --keep-failed` locally gives back the exact same every time. Leading me to believe that architecture, maven/java versions, or similar changes in input may be at play.

**Comment by soupglasses** [comment]
Putting this into draft due to the fragile nature of `mvnHash`. I have narrowed the first issue down to a changing maven version `3.9.2` vs `3.9.3` to change the internal dependencies in the `-deps` derivation. Read as minus is removed, plus is added, otherwise it is in both.

```
maven-plugins (-36, 39)
maven-resources-plugin (-3.3.0, +3.3.1)
maven-filtering (-3.3.0, 3.3.1)
plexus-utils (-3.3.0, 3.5.0, 3.5.1)
```

**Comment by soupglasses** [comment]
Hmm. Seeing as 13dd515a921667b798a30823b888e9a2135a480b update the `mvnHash` of all `buildMavenPackage`'s in nixpkgs. But im curious for why aarch64 fails.

**Comment by soupglasses** [comment]
Pinned the rest of the dependencies and now maven versions should not matter. Waiting for CI to see if this also helped Aarch64.

**Comment by soupglasses** [comment]
Yeah hmm. Aarch64 is not happy about the missing javafx libs. It seems i might need to fix that too.

`Could not resolve dependencies for project loper:ns-usbloader:jar:7.0: The following artifacts could not be resolved: org.openjfx:javafx-graphics:jar:linux-aarch64:19.0.2.1 (absent), org.openjfx:javafx-base:jar:linux-aarch64:19.0.2.1 (absent), org.openjfx:javafx-controls:jar:linux-aarch64:19.0.2.1 (absent), org.openjfx:javafx-fxml:jar:linux-aarch64:19.0.2.1 (absent): Cannot access redrise (https://repo.redrise.ru/releases) in offline mode and the artifact org.openjfx:javafx-graphics:jar:linux-aarch64:19.0.2.1 has not been downloaded from it before.`

**Comment by soupglasses** [comment]
Gonna pull in @Tillerino and @wegank as both seem to have recent experience with `buildMavenPackage`, as i need advice for how to deal with JavaFX packaging architecture-dependent versions, and how i could pull extra arch's into `mvnHash` correctly.

**Comment by Tillerino** [comment]
Hi soupglasses, I gotta be honest, I just did some legwork surrounding the Maven update. I haven't done anything with architecture-specific packaging yet.

Good call on managing the plugin versions 👍 I have been trying to upstream that for the projects where we had issues with the Maven update. I hope the next one will go smoother.

**Comment by soupglasses** [comment]
Yeah. Outside of limiting the package to x86_64-linux and aarch64-linux with a if statement to swap the mvnHash based on architecture, then adding a comment expressing it's TODO/FIXME status.

I have no ability to test it on other architectures than that. But seems like a good first PR.

**Comment by soupglasses** [comment]
Not a first timer, just changed my handle in the `maintainer-list.nix` :sweat_smile:

**Comment by soupglasses** [comment]
All lights green. This PR should be ready for merging now :)

**Pull request merged**
