### PR TITLE
coq: 8.16.0 → 8.16.1

### PR DESCRIPTION
**Pull request by vbgl**
###### Description of changes

Bugfix release: https://coq.github.io/doc/V8.16.1/refman/changes.html#changes-in-8-16-1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc maintainers (@Zimmi48 @roconnor @thoughtpolice)
ping @CohenCyril

### CODE REVIEW

**Comment by risicle** [comment]
`nixpkgs-review` happy, aarch64-linux

**Comment by CohenCyril** [comment]
FYI: 
```
Error: CompCert requires a version of Coq between 8.12.0 and 8.16.0
```
(https://github.com/coq-community/coq-nix-toolbox/actions/runs/3596762179/jobs/6057979415#step:10:96)

**Comment by risicle** [comment]
Same failure as @CohenCyril on macos 10.15 & nixos x86_64

**Comment by vbgl** [comment]
Fixed. Thanks for testing.

**Review by Zimmi48 — APPROVED** [review]

**Review by CohenCyril — APPROVED** [review]

**Review by jwiegley — APPROVED** [review]

**Pull request merged**
