### PR TITLE
Remove myself from maintainers

### PR DESCRIPTION
**Pull request by DamienCassou**
###### Motivation for this change

I'm not using NixOS/Nixpkgs anymore. This makes me sad, but I was spending way too much time fixing Nixpkgs, packaging and working around problems. Don't get me wrong, I love Nix and NixOS. Please keep going. I hope better times will come and let me come back.

I hope this will remove me from hydra report logs.

### CODE REVIEW

**Comment by vcunat** [comment]
:-(

You may need to do the same for 16.09.

**Comment by vcunat** [comment]
I picked it directly.  There are still a few references of your name on both branches.

**Comment by grahamc** [comment]
I'll miss you, thank you for all your hard work over the past few years.

**Comment by grahamc** [comment]
Do you have any suggestions on people you've noticed taking care of these packages / the gnome ecosystem that I could ping in the future?

**Comment by joachifm** [comment]
That's too bad. To avoid spam, perhaps you'd want to add an entry to the mentionbot blacklist as well?

**Comment by DamienCassou** [comment]
> Do you have any suggestions on people you've noticed taking care of these packages / the gnome ecosystem that I could ping in the future?

sorry, I don't

I will continue to read news from the community. Keep the good work going!

**Comment by vcunat** [comment]
Yes, I think that was the problem; Damien was lately doing most of all the gnome-specific work.

**Comment by DamienCassou** [comment]
> Damien was lately doing most of all the gnome-specific work

not most of it, but still a bit too much compared to the time I have. And I changed job in September which took me some time also.

**Comment by DamienCassou** [comment]
I'm back by the way :-).

**Comment by vcunat** [comment]
So you want to get listed on some `meta.maintainers` again?  I think especially for packages without any maintainers it would be nice...

**Comment by DamienCassou** [comment]
Vladimír Čunát <notifications@github.com> writes:
> So you want to get listed on some `meta.maintainers` again?  I think
> especially for packages without any maintainers it would be nice...

do you have any specific one in mind? Otherwise, I will add myself when
I find packages that need someone and that I'm willing to help.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by vcunat** [comment]
I meant nothing specific.  There's generally low `meta.maintainers` coverage, and this (old) diff also showed you were the only one in most cases.

**Comment by danbst** [comment]
> I'm back by the way :-).

why? :-) Don't get me wrong, I'm excited, but what triggered your return?

**Comment by DamienCassou** [comment]
> why? :-) Don't get me wrong, I'm excited, but what triggered your return?

I never wanted to leave. I joined a new company and had a hard time installing everything I needed in NixOS. I was spending a lot of time improving NixOS instead of learning my new job. Nowadays, I'm more one of the experts than one of the juniors in the company, we have much less things to install, and NixOS got much better!

I might have to go back to Fedora again because it seems NixOS is sucking all my battery power and is making my CPU really hot really fast on my new laptop. In Fedora I will see if I can replicate the problem. I hope to get back to NixOS really soon.

**Comment by danbst** [comment]
@DamienCassou oh noes! Do you have `services.tlp.enable` set? You may also check this https://github.com/NixOS/nixos-hardware/pull/101/files#diff-a48130f1addab5c8712fc73f37aa7f2fR52-R79, as it has some hacks to reduce power drain.

There is also another hack for Intel CPUs, which reduces frequency hardway, which reduces battery usage - https://github.com/NixOS/nixos-hardware/pull/101/files#diff-b3acb2a24fc098d15130f0261a43ed78R38-R50

**Comment by DamienCassou** [comment]
@danbst I do have tlp running. I'm trying your suggestions. It would be great if I could stick with NixOS. Currently, I'm migrating everything I can to home-manager to keep a Nix feeling if I have to go back to Fedora. Is it ok for me to contact you if I have questions about this problem? This thread is not appropriate though. Can I use discourse instead?

**Comment by danbst** [comment]
yes :+1:

**Pull request merged**
