### PR TITLE
D compiler update

### PR DESCRIPTION
**Pull request by dukc**
dmd 2.095.1 -> 2.097.2
ldc 1.25.1 -> 1.27.1

###### Motivation for this change

In #127932 I wanted to make DMD support multiple versions, but that was decided against. However, the pull request was also a regular compiler update and gathered a lot miscellaneous improvements from @SuperSandro2000 . This PR is including those, but without the multi-version scheme. I left the existing version dependencies on the build script though, because @lionello mentioned he wants the user to be able to override the versions himself.

@ThomasMader mentioned he wants DMD and LDC to be based on the same frontend, so I decided to increment LDC too,

###### Things done

Test-compiled and ran a hello world with both compilers

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by lionello — COMMENTED** [review]
Looks good! I'll try it on my machine when I get home.

**Comment by lionello** [comment]
Building LDC gives me lots of warnings like these:
```
ld: warning: building for macOS, but linking in object file (/nix/store/i63sz2d514q68n242p2w72zdrkrgd689-ldc-bootstrap-1.19.0/lib/libdruntime-ldc.a(ti_char.o)) built for free standing
```

**Comment by lionello** [comment]
`dmd` failed with
```
FAILED targets:
- runnable/test15779.d
make: *** [Makefile:208: run_all_tests] Error 1
```

**Comment by dukc** [comment]
> `dmd` failed with [snip]

Ouch. Looks like something platform-specific, as it does not fail for me, and I don't have a Mac. Highly likely it's some DMD regression relating to exception or fibers, as they're what the failing test is handling.

Can you build 2.097.2 manually and compile/run that test file directly?

**Comment by dukc** [comment]
@jbedo updated Sambamba while doing this - anything against?

I still have to fix GtkD/Tilix, then I think this is ready for consideration.

**Comment by dukc** [comment]
GtkD and Tilix compile again, so I think I think I let you review and pull now.

**Review by jbedo — APPROVED** [review]
Sambamba LGTM and tests fine.

**Comment by lionello** [comment]
Sorry for the late update. The failing test `runnable/test15779.d` works fine with locally built dmd, druntime, and Phobos, but the build from this branch keeps failing. I'll have to dig in.

**Comment by lionello** [comment]
This looks like it's a known issue on macOS 11.1+: https://issues.dlang.org/show_bug.cgi?id=21919

**Review by lionello — APPROVED** [review]
LGTM

**Comment by dukc** [comment]
@lionello Doesn't the test failure break MacOS? Or is it something that was broken already?

**Comment by lionello** [comment]
> @lionello Doesn't the test failure break MacOS? Or is it something that was broken already?

That test fails on macOS 11.1+ and as far as I can tell it has been broken forever, including the current DMD in nixpkgs.

**Comment by dukc** [comment]
Aww, too bad for MacOS. But it means it can be fixed separately from this upgrade.

**Comment by PetarKirov** [comment]
> That test fails on macOS 11.1+ and as far as I can tell it has been broken forever, including the current DMD in nixpkgs.

Perhaps we should mark darwin as a bad platform then?

```nix
{
  # ...
  meta = {
    # ...
    badPlatforms = lib.platforms.darwin; # https://issues.dlang.org/show_bug.cgi?id=21919
  };
}
```

Or perhaps we should mark the package as conditionally as broken?

```nix
{
  # ...
  meta = {
    # ...
    # Broken until https://issues.dlang.org/show_bug.cgi?id=21919 is fixed:
    broken = stdenv.hostPlatform.isDarwin ||
      stdenv.targetPlatform.isDarwin;  
  };
}
```
(I didn't mark as broken if `stdenv.buildPlatform.isDarwin`, as the compiler doesn't use Fibers, so building the package itself shouldn't be a problem.)

(It would be better if we could mark as broken only for specific macOS versions.)

**Comment by dukc** [comment]
Tried to reply by Email but it hasn't appeared, so reposting normally.

On 13.9.2021 18.51, Petar Kirov wrote:
> Perhaps we should mark darwin as a bad platform then?
>
> Or perhaps we should mark the package as conditionally as broken?

Better just disable the test I think. The bug is classified only major in D bugzilla, not a blocker. There are probably dozens of issues of this caliber that have surfaced from a system update, this one just happened to hit a test.

**Pull request merged**
