### PR TITLE
nvidia_x11: 390.67 -> 390.77

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by eadwu** [comment]
Not really accurate, latest is 396.51 while 390.77 is the last one with i686 support. Might as well wait for a proper solution to this.

**Comment by ivan** [comment]
Why close? It seems like `nvidia_x11` was tracking the Long Lived Branch version, and 390.77 is a good release.

**Comment by dtzWill** [comment]
:+1: .  I've always had confusion updating nvidia drivers (what "channel" does each follow, is there some testing to be done, is there a reason we can't auto-update these?) but this looks good to me.

And hitting this with linuxPackages_latest here too :3.

**Comment by eadwu** [comment]
The "channels" are noted here https://www.nvidia.com/object/unix.html.

**Comment by vcunat** [comment]
I think bumps after the dot are generally safe, but I'll try to test this PR tomorrow and merge afterwards.

**Review by vcunat — APPROVED** [review]
Runs fine with 4.18 for me.

**Pull request merged**
