### PR TITLE
Buildkite build-hook option

### PR DESCRIPTION
**Pull request by domenkozar**
Forward port https://github.com/NixOS/nixpkgs/pull/32387

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @zimbatm

**Comment by zimbatm** [comment]
@domenkozar what do you use the hooks for? I haven't found them really useful

**Comment by zimbatm** [comment]
the change looks good otherwise

**Comment by zimbatm** [comment]
I should probably share my "install multiple buildkite-agent services on one machine" change

**Comment by domenkozar** [comment]
We use them to bootstrap secrets.

**Comment by zimbatm** [comment]
Interesting. I am currently using the nixops keys for the secrets, but only have 1 project using buildkite.

**Pull request merged**
