### PR TITLE
Add redis-3.0.0-rc2

### PR DESCRIPTION
**Pull request by berdario**
According to [the manual](http://nixos.org/nixpkgs/manual/#sec-versioning), one of the valid cases for having more than one package version in nixpkgs is

> having both the latest stable and latest pre-release version of a package

### CODE REVIEW

**Comment by thoughtpolice** [comment]
Expressions for particular version names normally have the `major.minor` scheme; e.g. instead of `3.nix`, we normally have `3.0.nix` (and then later perhaps `3.2.nix`). Would you mind renaming these? Thanks!

**Comment by berdario** [comment]
Renamed as requested

**Comment by lethalman** [comment]
@berdario you didn't test the change, 3.nix is still called. Also there's an rc3 if you're interested in it.

**Comment by berdario** [comment]
Whoops, you're right...

For now I've done the changes, I'll try to test them soon, hopefully (after, I can squash the commits)

**Comment by lethalman** [comment]
Built locally, thanks.

**Pull request merged**
