### PR TITLE
nixStable: 2.3.12 -> 2.3.14

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change
Changes: https://github.com/NixOS/nix/compare/2.3.12...2.3.14

Since this is a bugfix release that wasn't pushed to `nixpkgs`, I
decided to take care of it.

As it's usually done in `upload-release.pl`[1], I updated the
fallback-paths accordingly and used eval `1678367`[2] for this as it was
the last evaluation of Nix with 2.3.12.

Also added a fallback-path for `aarch64-darwin` as Nix 2.3.14 seems to
support this now[3].

[1] https://github.com/NixOS/nix/blob/2.3-maintenance/maintainers/upload-release.pl
[2] https://hydra.nixos.org/eval/1678367#tabs-still-succeed
[3] https://github.com/NixOS/nix/commit/14262b86cc5825deae095c14553d623af498124c

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
Not sure aarch64-darwin will work with 2.3.12, why can't we bump to 2.3.14?

**Comment by Ma27** [comment]
@domenkozar tbh I don't know. It seems as it was always used the previosu Nix version as fallback, but this might be because `upload-release.pl` created a release AND updated the Nix expression (without waiting for Hydra). In other words: it might be possible to just use 2.3.14 as fallback, but I'd like @edolstra (or somebody else who feels sufficiently qualified) to confirm.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130538` at d0095abc run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>nixui</li>
    <li>ovftool</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/999e343bdf348389e23b12f01108f539">haskellPackages.update-nix-fetchgit</a></li>
    <li><a href="https://gist.github.com/e99819699c1b217718be8c320528dbf8">update-nix-fetchgit</a></li>
  </ul>
</details>
<details>
  <summary>5 packages skipped due to time constraints:</summary>
  <ul>
    <li>crate2nix</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-serve</li>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>44 packages built successfully:</summary>
  <ul>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>dep2nix</li>
    <li>dydisnix</li>
    <li>fusionInventory</li>
    <li>go2nix</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>haskellPackages.hercules-ci-cnix-expr</li>
    <li>haskellPackages.hercules-ci-cnix-store</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.nvfetcher</li>
    <li>hercules-ci-agent</li>
    <li>libnixxml</li>
    <li>nix (nixStable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixStatic</li>
    <li>nixos-generators</li>
    <li>nixos-shell</li>
    <li>nvfetcher</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pythonix</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by edolstra** [comment]
No, `fallback-paths.nix` has always been the most recent version (except that I stopped updating it).

**Comment by Ma27** [comment]
@edolstra @domenkozar I see, updated :) 
Used paths from https://hydra.nixos.org/eval/1687468 for this.

**Pull request merged**
