### PR TITLE
errands: 46.1 -> 46.2

### PR DESCRIPTION
**Pull request by luftmensch-luftmensch**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by luftmensch-luftmensch** [comment]
```
> nix build .#errands
> tree result/
 result
├──  bin
│  ├──  .errands-wrapped
│  └──  errands
├──  nix-support
│  └──  propagated-build-inputs
└──  share
   ├──  applications
   │  └──  io.github.mrvladus.List.desktop
   ├──  dbus-1
   │  └──  services
   │     └──  io.github.mrvladus.List.service
   ├──  errands
   │  ├──  errands
   │  │  ├──  lib
   │  │  │  ├──  sync
   │  │  │  │  ├──  providers
   │  │  │  │  │  ├──  caldav.py
   │  │  │  │  │  └──  nextcloud.py
   │  │  │  │  └──  sync.py
   │  │  │  ├──  animation.py
   │  │  │  ├──  data.py
   │  │  │  ├──  goa.py
   │  │  │  ├──  gsettings.py
   │  │  │  ├──  logging.py
   │  │  │  ├──  markup.py
   │  │  │  ├──  notifications.py
   │  │  │  ├──  plugins.py
   │  │  │  └──  utils.py
   │  │  ├──  utils
   │  │  ├──  widgets
   │  │  │  ├──  shared
   │  │  │  │  ├──  components
   │  │  │  │  │  ├──  boxes.py
   │  │  │  │  │  ├──  buttons.py
   │  │  │  │  │  ├──  controllers.py
   │  │  │  │  │  ├──  dialogs.py
   │  │  │  │  │  ├──  entries.py
   │  │  │  │  │  ├──  header_bar.py
   │  │  │  │  │  ├──  menus.py
   │  │  │  │  │  └──  toolbar_view.py
   │  │  │  │  ├──  task_toolbar
   │  │  │  │  │  ├──  __init__.py
   │  │  │  │  │  ├──  attachments_window.py
   │  │  │  │  │  ├──  datetime_window.py
   │  │  │  │  │  ├──  notes_window.py
   │  │  │  │  │  └──  toolbar.py
   │  │  │  │  ├──  color_selector.py
   │  │  │  │  ├──  datetime_picker.py
   │  │  │  │  ├──  sidebar_item.py
   │  │  │  │  └──  titled_separator.py
   │  │  │  ├──  tags
   │  │  │  │  ├──  tags.py
   │  │  │  │  └──  tags_sidebar_row.py
   │  │  │  ├──  task_list
   │  │  │  │  ├──  task_list.py
   │  │  │  │  └──  task_list_sidebar_row.py
   │  │  │  ├──  today
   │  │  │  │  ├──  today.py
   │  │  │  │  ├──  today_sidebar_row.py
   │  │  │  │  └──  today_task.py
   │  │  │  ├──  trash
   │  │  │  │  ├──  trash.py
   │  │  │  │  └──  trash_sidebar_row.py
   │  │  │  ├──  loading_page.py
   │  │  │  ├──  preferences.py
   │  │  │  ├──  sidebar.py
   │  │  │  ├──  task.py
   │  │  │  └──  window.py
   │  │  ├──  application.py
   │  │  └──  state.py
   │  └──  errands.gresource
   ├──  glib-2.0
   ├──  gsettings-schemas
   │  └──  errands-46.2
   │     └──  glib-2.0
   │        └──  schemas
   │           ├──  gschemas.compiled
   │           └── 󰗀 io.github.mrvladus.List.gschema.xml
   ├──  icons
   │  ├──  hicolor
   │  │  ├──  scalable
   │  │  │  └──  apps
   │  │  │     ├── 󰕙 io.github.mrvladus.List.Devel.svg
   │  │  │     └── 󰕙 io.github.mrvladus.List.svg
   │  │  └──  symbolic
   │  │     └──  apps
   │  │        ├── 󰕙 errands-add-symbolic.svg
   │  │        ├── 󰕙 errands-add-tag-symbolic.svg
   │  │        ├── 󰕙 errands-appearance-symbolic.svg
   │  │        ├── 󰕙 errands-attachment-symbolic.svg
   │  │        ├── 󰕙 errands-calendar-symbolic.svg
   │  │        ├── 󰕙 errands-check-toggle-symbolic.svg
   │  │        ├── 󰕙 errands-click-symbolic.svg
   │  │        ├── 󰕙 errands-clock-symbolic.svg
   │  │        ├── 󰕙 errands-close-symbolic.svg
   │  │        ├── 󰕙 errands-color-symbolic.svg
   │  │        ├── 󰕙 errands-copy-symbolic.svg
   │  │        ├── 󰕙 errands-daytime-morning-symbolic.svg
   │  │        ├── 󰕙 errands-daytime-sunset-symbolic.svg
   │  │        ├── 󰕙 errands-delete-all-symbolic.svg
   │  │        ├── 󰕙 errands-edit-symbolic.svg
   │  │        ├── 󰕙 errands-folder-symbolic.svg
   │  │        ├── 󰕙 errands-info-symbolic.svg
   │  │        ├── 󰕙 errands-lists-symbolic.svg
   │  │        ├── 󰕙 errands-more-symbolic.svg
   │  │        ├── 󰕙 errands-notes-symbolic.svg
   │  │        ├── 󰕙 errands-notification-symbolic.svg
   │  │        ├── 󰕙 errands-priority-set-symbolic.svg
   │  │        ├── 󰕙 errands-priority-symbolic.svg
   │  │        ├── 󰕙 errands-progressbar-symbolic.svg
   │  │        ├── 󰕙 errands-restore-symbolic.svg
   │  │        ├── 󰕙 errands-right-symbolic.svg
   │  │        ├── 󰕙 errands-select-symbolic.svg
   │  │        ├── 󰕙 errands-settings-symbolic.svg
   │  │        ├── 󰕙 errands-share-symbolic.svg
   │  │        ├── 󰕙 errands-sidebar-left-symbolic.svg
   │  │        ├── 󰕙 errands-sidebar-right-symbolic.svg
   │  │        ├── 󰕙 errands-sync-symbolic.svg
   │  │        ├── 󰕙 errands-tag-add-symbolic.svg
   │  │        ├── 󰕙 errands-tag-symbolic.svg
   │  │        ├── 󰕙 errands-theme-dark-symbolic.svg
   │  │        ├── 󰕙 errands-theme-light-symbolic.svg
   │  │        ├── 󰕙 errands-theme-system-symbolic.svg
   │  │        ├── 󰕙 errands-toolbar-symbolic.svg
   │  │        ├── 󰕙 errands-trash-full-symbolic.svg
   │  │        ├── 󰕙 errands-trash-symbolic.svg
   │  │        ├── 󰕙 errands-up-symbolic.svg
   │  │        └── 󰕙 io.github.mrvladus.List-symbolic.svg
   │  └── 󰕙 io.github.mrvladus.List.Source.svg
   ├──  locale
   │  ├──  ar
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  ca
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  cs
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  da_DK
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  de
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  el
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  en_GB
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  es
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  eu
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  fa
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  fr
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  hr
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  hu
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  it
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  ja
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  nl
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  oc
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  pl
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  pt_BR
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  ru
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  tr
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  uk
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  ├──  zh_CN
   │  │  └──  LC_MESSAGES
   │  │     └──  errands.mo
   │  └──  zh_TW
   │     └──  LC_MESSAGES
   │        └──  errands.mo
   └──  metainfo
      └── 󰗀 io.github.mrvladus.List.metainfo.xml
```

**Comment by Misterio77** [comment]
Think the bot glitched out?

@ofborg build errands

**Comment by Misterio77** [comment]
@ofborg eval

**Comment by luftmensch-luftmensch** [comment]
> Think the bot glitched out?
> 
> @ofborg build errands

No idea 😅

**Comment by Misterio77** [comment]
Result of `nixpkgs-review pr 313174` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>errands</li>
  </ul>
</details>

**Review by Misterio77 — APPROVED** [review]

**Review by sund3RRR — APPROVED** [review]

**Pull request merged**
