### PR TITLE
modprobe: install systemd's modprobe options

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
Fix bond0 netdev creation with non-default `mode` value.

Updated the test to verify the fix in both the scripted and networkd world.

Closes: #161281 #161238 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grahamc** [comment]
Okay. This time for real I think this is the best option.

**Comment by mweinelt** [comment]
@ofborg test networking.scripted.bond networking.networkd.bond

**Review by grahamc — APPROVED** [review]

**Review by dasJ — APPROVED** [review]

**Comment by vcunat** [comment]
I bisected `nixosTests.networking.scripted.link` failure to commit `c2147ab6` (from this PR).

**Comment by mweinelt** [comment]
Thanks I didn't notice we had a dummy link test. Will look into it in an hour.

**Comment by mweinelt** [comment]
Fix in #161734.

**Comment by mweinelt** [comment]
The only change here is that dummy0 isnt autocreated anymore. If that causes you problems you need to create one manually like `ip link add dummy0 type dummy`.

Currently on on my phone so I didn't check our your links.

We probably forgot to announce this as a breaking change, I'm sorry for that. Added to my to-do.

**Comment by dhess** [comment]
I guess that would explain it.

**Comment by grahamc** [comment]
Note that before the kernel would auto create the interface when the
module loaded. Obviously the declarative config in NixOS should be
handling that or I would expect it to fail on any subsequent dummy
interfaces. 

On February 26, 2022, GitHub ***@***.***> wrote:
> I guess that would explain it.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/NixOS/nixpkgs/pull/161391#issuecomment-1052279370>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAASXLGFJQ6SK3VTHOJFAEDU5D525ANCNFSM5PB4366Q>.
You are receiving this because your review was requested.Message ID:
***@***.***>

**Comment by dhess** [comment]
It seems I'm not the only one who didn't think the explicit `ip link add` was necessary:

https://github.com/NixOS/nixpkgs/blob/c9fa03136ad26fab9c5d4d62c57fc26e2d5dc9e5/nixos/modules/services/security/hologram-agent.nix#L38

**Pull request merged**
