### PR TITLE
nixosTests.netdata: port to python

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change

#72828 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @cransom

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/74078)

### CODE REVIEW

**Comment by flokli** [comment]
This multiline command looks kinda scary, and it seems it also doesn't work:
```
netdata # > > parse error: Invalid numeric literal at line 1, column 6
netdata # > > parse error: Invalid numeric literal at line 1, column 6
netdata # > > parse error: Invalid numeric literal at line 1, column 6
netdata # > > parse error: Invalid numeric literal at line 1, column 6
netdata # > > parse error: Invalid numeric literal at line 1, column 6
netdata # > > parse error: Invalid numeric literal at line 1, column 6
```

**Comment by filalex77** [comment]
@flokli I hope I fixed it. Thanks for the help!

**Comment by flokli** [comment]
@GrahamcOfBorg test netdata

**Comment by filalex77** [comment]
@flokli I think it's still a problem. Tried to debug manually with `nix-build netdata.nix -A driver` - this command worked just fine. Maybe it's *still* a quoting issue?

**Review by tfc — APPROVED** [review]

**Comment by Lassulus** [comment]
if I run the test and log the response of the curl with:
```
netdata.wait_until_succeeds(f"curl -v {url} >&2")
```

I get this response:
```
netdata # *   Trying ::1:19999...
netdata # * TCP_NODELAY set
netdata # * Connected to localhost (::1) port 19999 (#0)
netdata # > GET /api/v1/data?chart=users.pwrites HTTP/1.1
netdata # > Host: localhost:19999
netdata # > User-Agent: curl/7.67.0
netdata # > Accept: */*
netdata # >
netdata # * Mark bundle as not supporting multiuse
netdata # < HTTP/1.1 404 Not Found
netdata # < Connection: close
netdata # < Server: NetData Embedded HTTP Server v1.18.1
netdata # < Access-Control-Allow-Origin: *
netdata # < Access-Control-Allow-Credentials: true
netdata # < Content-Type: text/plain; charset=utf-8
netdata # < Date: Thu, 28 Nov 2019 21:11:02 GMT
netdata # < Cache-Control: no-cache, no-store, must-revalidate
netdata # < Pragma: no-cache
netdata # < Expires: Thu, 28 Nov 2019 21:11:03 GMT
netdata # < Content-Length: 33
netdata # <
netdata # * Closing connection 0

```

**Review by Lassulus — APPROVED** [review]
tested with nix-review and nix-build.

**Pull request merged**
