### PR TITLE
libgit2: bump for bug fixes as well as security fixes

### PR DESCRIPTION
**Pull request by dtzWill**
Bump pygit2 as well, not tested beyond building.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by qolii** [comment]
@dtzWill, quick question: what is the reason we can't move to 0.27 as default? IIRC, only 0.27 supports `libressl-2.7` and up. Does it break somethings?

**Comment by dtzWill** [comment]
It likely can be made the default, although I'm not sure.

Quick grep suggests libgit2-glib may require the 0.26 version,
but perhaps that should be special-cased.

There may be other packages in similar situation, didn't check closely.

Regardless I'm not aware of a breakage-based reason it can't be default,
only that some packages need older version for presumably API reasons
and can be handled by specifying the 0.26 attribute
(which would be introduced).

Maybe give this a try and submit a PR? :)

**Comment by dtzWill** [comment]
Ping? Not sure if we mean to block or not just checking :)

**Comment by dtzWill** [comment]
Overdue security fixes-- changing the default can be done separately (and sounds good but needs to be tested).

**Pull request merged**
