### PR TITLE
spidermonkey_78: use LLVM 12

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Similar to https://github.com/NixOS/nixpkgs/pull/113213. This avoids having to build multiple LLVM versions for my systems, which is very helpful for platforms without a binary cache (e.g. 32-bit ARM), and we might as well use a newer version anyway.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
Would it cause any issues to just use llvmPackages_latest? (I feel like in a perfect world, llvmPackages and llvmPackages_latest would be the same thing)

**Comment by r-burns** [comment]
Okay sounds reasonable.

Going on a bit of a tangent now but if you need spidermonkey for polkit, I heard there's now a way to set it up to use duktape instead. Been meaning to look into this, would be nice for cacheless platforms.

**Comment by ajs124** [comment]
@r-burns big if true. With that and the next libproxy release, we'd manage to largely get rid of spidermonkey.

If you get around to that for polkit, feel free to ping me for a review.

**Review by r-burns — APPROVED** [review]
Built polkit and libproxy on x86_64-linux

**Review by lostnet — APPROVED** [review]

**Pull request merged**
