### PR TITLE
Added boot.initrd.logCommands and boot.logCommands in order to log the command output from early userspace in stage-1 and stage-2

### PR DESCRIPTION
**Pull request by CMCDragonkai**
By default these options are left as false. No interruption with existing boot even if you switch them on. You still see all userspace messages on the terminal. No extra packages are installed, stage-1 uses the pre-existing busybox tools, and stage-2 uses only coreutils and bash 4.0 features.

Uses the preexisting `/run/log` folder. I judged this folder to be best folder to use (as it is temporary and mounted in RAM). I explored seeing how I can put the logs into journald, but I realised the timing would be off, and there's no way to inject logs at a previous time into journald. At any case, users can do this easily using their own systemd script if necessary.

These 2 options when switched on will log command output to `/run/log/stage-1-init.log` and `/run/log/stage-2-init.log` respectively. They are really useful for debugging issues at early user space unattended, or when you don't have a direct terminal to access early user space, such as when using cloud instances.

The file descriptor 8 and 9 was used in `stage-1-init.sh`, these were chosen somewhat randomly, but they were not occupied file descriptors. The usage of fifo pipe is required in stage 1 because ASH doesn't support process substitution. Also resetting the file descriptors is necessary to prevent kernel panics in stage 1, and for stage 2, just to be consistent.

I tested this and it works on latest 15.09 on bare metal.

### CODE REVIEW

**Comment by edolstra** [comment]
Is there a particular reason to make this an option? Options are bad.

Could this break interactive commands (like asking for a LUKS passphrase)? I guess if they do `isatty` on stdin they should be fine.

Maybe you could pipe to `/dev/kmsg` instead of a file? Then the output *will* appear in the journal, along with timestamps.

**Comment by CMCDragonkai** [comment]
Doesn't break LUKs, I run LUKs as well and the interactive prompt.

Could go into /dev/kmsg, the reason not to, is because these aren't really
kernel messages?

But maybe instead of an option give a file path option instead? As a string
specifically, and empty string means disabling it? What do you think?

Although I'm not sure how to test for that during interpolation, is it
still `-n`?

Beware though, not all file paths is going to be valid, they may require
directory creation.

**Comment by nathan7** [comment]
@CMCDragonkai journald specifically reads from kmsg on startup so you can write pre-journald log output there and still have it included in the journal.

**Comment by CMCDragonkai** [comment]
@nathan7 I know that, but that's not what I'm saying. I'm just saying that these aren't really kernel messages. At any case, giving a path to specify would be better.

I read somewhere that dmesg may be disabled in certain VPSes.

**Comment by nathan7** [comment]
@CMCDragonkai dmesg can be disabled on OpenVZ systems, but in that case I'm not sure you'd use an initrd at all. Also, if you log somewhere else, how do you keep the time ordering between the kernel messages and these?

**Comment by nathan7** [comment]
Also, is there any particular reason we unconditionally include the script fragment? I'd rather have that be conditional on the option.

**Comment by CMCDragonkai** [comment]
These messages are just stored temporarily and when you reboot, the messages disappear. That's why it's in `/run/log` atm.

Or if you're asking in general, the only thing you know is that these messages happened when you booted the current session.

Previously I had added a `sed` and `awk` to add date times, but something didn't work there.

**Comment by CMCDragonkai** [comment]
@nathan7 It follows the structure of the rest of the init scripts. There is no conditional code elsewhere for boolean options.

**Comment by CMCDragonkai** [comment]
Specifying arbitrary file paths for boot.initrd.logPath will need special documentation, as not all paths in initrd is going be remounted into the root filesystem. Only a few are:

```
mount --move /proc $targetRoot/proc
mount --move /sys $targetRoot/sys
mount --move /dev $targetRoot/dev
mount --move /run $targetRoot/run
```

So users do have a choice between `/run` or `/dev/kmsg`.

Going into `kmsg` is however tricky because of empty lines. Sometimes people might echo an empty line for spacing like `echo `. Adding in `sed` is an extra dependency for stage 2. When I tried to do this before this resulted in empty log file. As well. On the other hand, logging a file might be best to preserve the newlines. There's just a lot of complications for such flexibility.

**Comment by edolstra** [comment]
I think using /dev/kmsg is far preferrable. Note that systemd also logs early boot messages to kmsg, so there is precedent. 

Maybe /run/log can be used as a fallback if /dev/kmsg doesn't exist / isn't writable, but I don't think this needs to be configurable.

**Comment by CMCDragonkai** [comment]
@edolstra Ok it's done. Checks if `/dev/kmsg` is writable. and if so, writes to that with `stage-1:` marker. Similar with stage-2.

**Comment by CMCDragonkai** [comment]
You can view logs in general using:

```
sudo journalctl SYSLOG_IDENTIFIER=stage-1-init
sudo journalctl SYSLOG_IDENTIFIER=stage-2-init
```

**Comment by CMCDragonkai** [comment]
Oh I need to add `-r` option to the read command to allow backslashes to be interpreted literally. While it will work in Bash, I'm not sure about ASH. If Busybox's ash is a derivative of dash, then the `-r` option for `read` should be supported no? No manuals say it there's an option like that. Will need to test it tomorrow.

**Comment by edolstra** [comment]
Thanks, merged! However, I've removed the `logCommands` options, thus enabling this unconditionally. It seems to useful not to enable by default. Also, I've changed the log level of the messages to "debug".

**Comment by CMCDragonkai** [comment]
Thanks for merging. However I still need to test the -r option on read. I can submit another PR once I've tested it.

**Comment by CMCDragonkai** [comment]
By the way, I didn't see any changes with the new debug level, what exactly changed there?

**Comment by CMCDragonkai** [comment]
Done, it works: https://github.com/NixOS/nixpkgs/pull/13415

**Pull request closed without merging**
