### PR TITLE
stdenv.mkDerivation: add support for env attrset

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
For `__structuredAttrs`, we want to distinguish regular structured variables from string-coercible variables that will be exported to the environment. The environment variables will be passed to `mkDerivation` as attributes of the `env` attribute set.

To lower the review workload of the `__structuredAttrs` PR, we have decided to make the `env` mechanism available as a vanguard. Until the support for `__structuredAttrs` is implemented, the content of the `env` attrset will be merged into the attrset passed to `mkDerivation`.

The content of the attributes in `env` is checked for validity and conflicts with the rest of `mkDerivation` attributes. The current mechanism should produce the same derivations as the original, thus require no rebuilds.

This change is backwards compatible for now, as Nix does not allow attrsets to be passed to derivation without `__structuredAttrs` enabled, and the current mechanism handles the non-attrsets as before. We reserve the right to require `env` to be attrset in the future.

----

Only the first commit is important, the rest is cherry-picked from #72074.

cc @globin @Ericson2314 @Ma27

### CODE REVIEW

**Comment by FRidh** [comment]
I suggest documenting this part directly before it is forgotten.

**Comment by jtojnar** [comment]
Definitely will add docs before this is merged, just wanted it to get okayed by few people first.

**Comment by jtojnar** [comment]
Looks like it crashes on infinite recursion in stage4 of darwin bootstrapping. Any idea how to reproduce the issue locally on NixOS?

**Comment by jtojnar** [comment]
It appears that the type checking in make-derivation.nix is at fault:

https://github.com/NixOS/nixpkgs/blob/9b0cf4d57e7c62136a684f1b5ca9a9b9a601fede/pkgs/stdenv/generic/make-derivation.nix#L319

In the original PR, it was solved by moving the assert inside `env`, which was lazy (f90ca1e0dabcd6acea84e31ef64d37bdcd07b2ac). Here we are checking it much sooner, since there is no nesting. Maybe mapping the asserts over the values themselves would work but it feels like a hack.

**Comment by jtojnar** [comment]
Hmm, it is not that backwards compatible after all. Derivations are both freely coercible into strings and attrsets and using it that way is pretty common in ruby land:

https://github.com/NixOS/nixpkgs/blob/ced5f4fe34fe1ce9dc18541fd8c4d3ddc7d3b43e/pkgs/development/tools/ronn/default.nix#L7-L10

Let’s try ignoring derivations for that.

**Comment by FRidh** [comment]
That `env` in the ronn expression should probably be moved into a let..in expression.

**Comment by edolstra** [comment]
Checking the validity of `env` at evaluation time seems potentially expensive. Maybe it can be checked at runtime (in the builder)?

**Comment by Ericson2314** [comment]
@edolstra Maybe temporarily, but eval-time checks make refactoring easier and safer (analogous to types), and don't cause mass rebuilds if they need to be changed. I maintain hope we can cache evaluation better (especially with `--pure`) and free ourselves these eval time problems once and for all.

**Review by Ericson2314 — APPROVED** [review]
Looks good to me. I agree its good to merge these (mostly) non-breaking changes to make progress incrementally, or we'll never be able to finish. Thanks again for picking this up!

**Comment by jtojnar** [comment]
I wonder why the `assertMsg`s are printed but the evaluation does not fail.

**Comment by teto** [comment]
anything that helps with __structuredAttrs is ok in my book.

**Review by teto — APPROVED** [review]

**Comment by Artturin** [comment]
env attrset added in https://github.com/NixOS/nixpkgs/pull/175649

**Comment by Artturin** [comment]
Was having lists in env automatically have toString run on them ever considered?

**Pull request closed without merging**
