### PR TITLE
nixos-shell: init at 0.0.1

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

* procrastinating hard during a delayed flight.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by davidak** [comment]
Could you find a name and description that makes more clear what this is? A shell, VM or container are different things. What is the difference to nixos-container?

**Comment by volth** [comment]
I agree, the name is too generic (I have ```nixos-shell``` too among the utilites and it does very different thing: a ```nix-shell``` which takes into account config and overlays from configuration.nix)

**Comment by Mic92** [comment]
Draft for description:

nixos-containers are based on `systemd-nspawn` and is os-level virtualization, which means that no external kernel is used to run the container. In comparison to `nixos-containers` it does not need read and is more adhoc. I called it `nixos-shell` because the semantic is similar to `nix-shell`. It looks for a `vm.nix` in the current directory, but starts a whole virtual machine instead of just setting some environment variables.

**Comment by Mic92** [comment]
nixos-shell also respects overlays for building VMs and the current user profile: https://github.com/Mic92/nixos-shell/blob/master/share/nixos-shell/nixos-shell.nix#L5

**Comment by Mic92** [comment]
Probably I should add container support too.

**Comment by volth** [comment]
BTW, with adding ```sendkey``` and ```takescreenshot``` it could be a more or less interactive alternative to ```test-driver``` (current ```test-driver``` is leaned towards runs on Hydra and not very convenient to make ad-hoc tests)

**Comment by Mic92** [comment]
maybe incorporating: https://docs.python.org/3.6/library/cmd.html
At some point when it comes to argument parsing, some high-level language would be better.

**Comment by Mic92** [comment]
@volth do you have sensible defaults regarding ballooning, the current memory limit is quite low.

**Comment by volth** [comment]
@Mic92 I am using 384MB to run tests, it is enough even for GUI (with IceWM). Some programs (hadoop, etc) needs more and a manual setting.
Big ```-m``` value + ```virtio-balloon``` would be an interesting solution to remove one manual parameter to care about, I have not tested it.

**Comment by Mic92** [comment]
auto ballooning requires some experimental branches of qemu... https://github.com/clearcontainers/vhost-9pfs would be also nice to speedup file sharing.

**Comment by Mic92** [comment]
There are some changes I want to make, before adding this to nixpkgs.

**Pull request closed without merging**
