### PR TITLE
super-slicer: fix build

### LINKED ISSUE #294114: Build failure: super-slicer-beta
### Steps To Reproduce

1. build *super-slicer-beta*

### Build log

```
nh>    Compiling clap_complete v4.4.10
nh>    Compiling subprocess v0.2.9
nh>    Compiling uzers v0.11.3
nh>    Compiling owo-colors v4.0.0
nh>    Compiling timeago v0.4.2
nh>    Compiling clean-path v0.2.1
nh>    Compiling humantime v2.1.0
nh>    Compiling nh v3.5.4 (/build/source)
nh> warning: unused import: `std::os::unix::fs::MetadataExt`
nh>   --> src/clean.rs:16:5
nh>    |
nh> 16 | use std::os::unix::fs::MetadataExt;
nh>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nh>    |
nh>    = note: `#[warn(unused_imports)]` on by default
nh> 
nh> warning: function `home_info` is never used
nh>    --> src/home.rs:126:4
nh>     |
nh> 126 | fn home_info() -> Result<()> {
nh>     |    ^^^^^^^^^
nh>     |
nh>     = note: `#[warn(dead_code)]` on by default
nh> 
super-slicer> make[2]: *** [src/libslic3r/CMakeFiles/libslic3r_cgal.dir/build.make:76: src/libslic3r/CMakeFiles/libslic3r_cgal.dir/MeshBoolean.cpp.o] Error 1
super-slicer> make[1]: *** [CMakeFiles/Makefile2:1116: src/libslic3r/CMakeFiles/libslic3r_cgal.dir/all] Error 2
super-slicer> make: *** [Makefile:156: all] Error 2
error: builder for '/nix/store/s06z0gn59i453i0q4kny91i9mj0f36hk-super-slicer-2.5.59.6.drv' failed with exit code 2;
       last 10 log lines:
       > /build/source/src/libslic3r/MeshBoolean.cpp:184:0:   required from here
       > /build/source/src/libslic3r/MeshBoolean.cpp:150: error: cannot bind non-const lvalue reference of type 'CGAL::SM_Vertex_index&' to an rvalue of type 'boost::iterators::detail::iterator_facade_base<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >::Index_iterator<CGAL::SM_Vertex_index>, CGAL::SM_Vertex_index, std::random_access_iterator_tag, CGAL::SM_Vertex_index, long int, false, false>::reference' {aka 'CGAL::SM_Vertex_index'}
       >   150 |     for (auto &vi : vertices) {
       >       |
       > /build/source/src/libslic3r/MeshBoolean.cpp:155: error: cannot bind non-const lvalue reference of type 'CGAL::SM_Face_index&' to an rvalue of type 'boost::iterators::detail::iterator_facade_base<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >::Index_iterator<CGAL::SM_Face_index>, CGAL::SM_Face_index, std::random_access_iterator_tag, CGAL::SM_Face_index, long int, false, false>::reference' {aka 'CGAL::SM_Face_index'}
       >   155 |     for (auto &face : faces) {
       >       |
       > make[2]: *** [src/libslic3r/CMakeFiles/libslic3r_cgal.dir/build.make:76: src/libslic3r/CMakeFiles/libslic3r_cgal.dir/MeshBoolean.cpp.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:1116: src/libslic3r/CMakeFiles/libslic3r_cgal.dir/all] Error 2
┏━ 1 Errors: ll logs, run 'nix log /nix/store/s06z0gn59i453i0q4kny91i9mj0f36hk-super-slicer-2.5.59.6.drv'.
┃ error: builder for '/nix/store/s06z0gn59i453i0q4kny91i9mj0f36hk-super-slicer-2.5.59.6.drv' failed with exit code 2;
┃        last 10 log lines:
┃        > /build/source/src/libslic3r/MeshBoolean.cpp:184:0:   required from here
error: 1 dependencies of derivation '/nix/store/mb55x2ikcx8k0l2qvyrfmpwnckfs5gcl-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vmiaxcv386g3rpdh6in8plr27sh7ak5r-nixos-system-ThinkPad-24.05.20240306.9df3e30.drv' failed to build
┏━ 1 Errors: 
┃ error: builder for '/nix/store/s06z0gn59i453i0q4kny91i9mj0f36hk-super-slicer-2.5.59.6.drv' failed with exit code 2;
┃        last 10 log lines:
┃        > /build/source/src/libslic3r/MeshBoolean.cpp:184:0:   required from here
┃        > /build/source/src/libslic3r/MeshBoolean.cpp:150: error: cannot bind non-const lvalue reference of type 'CGAL::SM_Vertex_index&' to an rvalue of type 'boost::iterators::detail::iterator_facade_base<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >::Index_iterator<CGAL::SM_Vertex_index>, CGAL::SM_Vertex_index, std::random_access_iterator_tag, CGAL::SM_Vertex_i…
┃        >   150 |     for (auto &vi : vertices) {
┃        >       |
┃        > /build/source/src/libslic3r/MeshBoolean.cpp:155: error: cannot bind non-const lvalue reference of type 'CGAL::SM_Face_index&' to an rvalue of type 'boost::iterators::detail::iterator_facade_base<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >::Index_iterator<CGAL::SM_Face_index>, CGAL::SM_Face_index, std::random_access_iterator_tag, CGAL::SM_Face_index, …
┃        >   155 |     for (auto &face : faces) {
┃        >       |
┃        > make[2]: *** [src/libslic3r/CMakeFiles/libslic3r_cgal.dir/build.make:76: src/libslic3r/CMakeFiles/libslic3r_cgal.dir/MeshBoolean.cpp.o] Error 1
┃        > make[1]: *** [CMakeFiles/Makefile2:1116: src/libslic3r/CMakeFiles/libslic3r_cgal.dir/all] Error 2
┃        > make: *** [Makefile:156: all] Error 2
┃        For full logs, run 'nix log /nix/store/s06z0gn59i453i0q4kny91i9mj0f36hk-super-slicer-2.5.59.6.drv'.
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here

 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos-23.11"`
 - nixpkgs: `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by krntz**
## Description of changes
Added patch fixing build issue after cgal bump in #292492. Fixes #294114

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by krntz** [comment]
Ideally, this would be fixed by making sure the cgal version matches what's used upstream (5.0.0), but I lack the Nix knowledge to do that.

**Comment by cab404** [comment]
@ofborg build super-slicer

**Comment by cab404** [comment]
> Ideally, this would be fixed by making sure the cgal version matches what's used upstream (5.0.0), but I lack the Nix knowledge to do that.

Yeah. usually everyone just throw whatever's available. That's absurd, but that's how it is :(

**Comment by headblockhead** [comment]
This still fails for me?
It also fails in CI: https://github.com/NixOS/nixpkgs/runs/23028884944

**Pull request merged**
