### PR TITLE
Fix converting vam.pluginDictionaries to VimL

### PR DESCRIPTION
**Pull request by rummik**
###### Motivation for this change
Fix a regression that broke outputting attributes on VAM's plugin dictionaries.  This also makes naming a little more clear, and escapes the strings it outputs, fixing a bug in the conversion

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @jonringer

### CODE REVIEW

**Comment by jonringer** [comment]
> Fix a regression that broke outputting attributes on VAM's plugin dictionaries.

is this still an issue? there was another for plugin loading that was merged recently

cc @timokau @evanjs

**Comment by timokau** [comment]
I don't know, I've never really used vam and I'm not familiar with that part of the infrastructure. If you're referring to https://github.com/NixOS/nixpkgs/pull/78385, that's almost certainly irrelevant to this issue.

@rummik is this still relevant?

**Comment by rummik** [comment]
@timokau Sorry for the delay in reply.  The code that handles serialization to VimL wasn't touched in #78385, so I still have been using this in order to have `exec` and `filename_regex` passed to VAM

**Comment by rummik** [comment]
As an example, this is one of the places where I've needed this conversion: [config/neovim.nix#L432-L438](https://github.com/rummik/nixos-config/blob/a623bf2108b8a0ef3925b421a119dce9550f6ebf/config/neovim.nix#L432-L438)

**Review by timokau — CHANGES_REQUESTED** [review]
In that case let's go ahead with this. As I said, I don't know much about vam but @rummik seems to know what they're doing and the diff looks good to me.

Can you prefix your commit message with `vim-utils:`?

**Comment by rummik** [comment]
@timokau Done! :grin:

**Review by timokau — APPROVED** [review]

**Comment by timokau** [comment]
Thanks for taking the care for this! Sorry you had to bring so much patience to the table for your first contribution. Its just an area of the code that not many people are comfortable with.

Welcome to the team :)

**Comment by jonringer** [comment]
@timokau seconded! 

@rummik thank you for putting up with our antics. Hard to give good feedback when (at least I) we lack in context about a particular framework. Hope to see more contributions :)

**Comment by rummik** [comment]
Understandable! xD  Reviewers seem spread pretty thin anyway, so I wasn't really worrying about it :sweat_smile:

**Comment by rummik** [comment]
And thanks as well!

**Pull request merged**
