### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Compare to master: `?compare=1478563`

**Comment by timokau** [comment]
The included texlive upgrade breaks zathura: https://github.com/NixOS/nixpkgs/pull/45432#issuecomment-421626897

**Comment by xeji** [comment]
@timokau zathura was fixed by #46376 , which is in `staging` (but not `staging-next`).

**Comment by xeji** [comment]
Unfortunately this isn't making any progress on Hydra due to low priority: https://hydra.nixos.org/eval/1478706. >6000 queued builds, all on Darwin, and no build run at all for a day now. 
How are we going to get this in shape to be merged?

**Comment by timokau** [comment]
Also should the zathura fix maybe be cherry-picked to staging-next? Its a fix after all. But it would cause a lot of rebuilds.

**Comment by xeji** [comment]
@timokau it would cause another ~13k rebuilds and delay this iteration for several days - just to fix one package.  The point of  `staging-next` is exactly to avoid that and stabilize the build without starting over each time a commit is added...

**Comment by globin** [comment]
FYI, added ce6e72a11cc2f52d6e92224791fe5db7f9e2ecdd to staging, follow-up to the first texlive fix, if that should be considered to be cherry-picked in.

**Comment by xeji** [comment]
Current comparison: https://hydra.nixos.org/eval/1479929?filter=x86_64-linux&compare=1479402

**Comment by xeji** [comment]
A large portion of the new failures are timeouts (kernels and libreoffice) that shouldn't concern us.

**Comment by xeji** [comment]
`vlc` failure on aarch64 is unrelated.

**Pull request merged**
