### PR TITLE
python3Packages.karton-autoit-ripper: init at 1.0.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
AutoIt script ripper for Karton framework

https://github.com/CERT-Polska/karton-autoit-ripper

Related to #81418

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 120742` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.autoit-ripper</li>
    <li>python38Packages.karton-autoit-ripper</li>
    <li>python39Packages.autoit-ripper</li>
    <li>python39Packages.karton-autoit-ripper</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120742` at d8c45d87 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.karton-autoit-ripper</li>
    <li>python39Packages.karton-autoit-ripper</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.autoit-ripper</li>
    <li>python39Packages.autoit-ripper</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@fabaff please take a look why those packages are marked broken.

**Comment by lukegb** [comment]
> @fabaff please take a look why those packages are marked broken.

I think they have a dependency that's marked as broken on aarch64.

**Pull request merged**
