### PR TITLE
Bump linux_rt Kernels to 5.15.73-rt53 and 6.0.5-rt14 for default and latest, respectively.

### PR DESCRIPTION
**Pull request by vifino**
###### Description of changes

Updates linux_rt_default to the current stable train of linux-rt. It has been declared stable on [the linux foundation wiki][1] since 2022-01-11. Version 5.15 matches the current default linux release, it being the latest LTS.

Also updates the linux_rt_latest to the latest development version for the latest released kernel, 6.0, matching the latest packaged linux release, development has presumably moved to 6.1 candidates.

They were pretty out of date, heh.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vifino** [comment]
Could someone please take a look at this?
Maybe one the (active) assigned reviewers? @Ma27 - sorry for the ping - you seem to do some linux kernel related stuff, maybe you can find the time?

**Comment by orivej** [comment]
I'd prefer to keep rt kernels on the longterm branches (see the table at https://www.kernel.org/) because this involves less maintenance (no need to clean up obsolete kernels for a long while), and because the rt patches used to require stabilization of their own (at least I had this impression) and could mature more when longterm. So now is definitely the time to add linux_rt_6_1 and set linux_rt_latest to that version. Then after using it for some time, if all goes well, I'd suggest setting linux_rt_default to 6.1 because it is already linux_default.

**Comment by orivej** [comment]
@vifino, would you like to add linux_rt_6_1 and set linux_rt_latest = linux_rt_6_1?

**Comment by vifino** [comment]
Sure! Thank you for your feedback!

I'll get on that tomorrow if you're not in a hurry. I'll be sure to ping you then. :)

Closing this, though.

**Comment by orivej** [comment]
Thanks!

**Pull request closed without merging**
