### PR TITLE
haskell.compiler: ghc921 -> ghc922

### PR DESCRIPTION
**Pull request by sternenseemann**
https://www.haskell.org/ghc/download_ghc_9_2_2.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build haskell.compiler.ghc922

**Comment by sternenseemann** [comment]
We won't be able to merge this into `master` sadly, as the `ghc-lib-{,parsers,parsers-ex}` for 9.2.1 stop building with 9.2.2. Updating the packages in question on master is probably more trouble than it's worth.

**Comment by schuelermine** [comment]
Why is merging this into master impossible because of that? Wouldn’t making it available as `pkgs.haskell.compiler.ghc922` not break any existing packages?

**Comment by sternenseemann** [comment]
The available package versions are the same for all 5 package sets, we merely pick and choose different ones via overlays for different compiler versions some of the time. For better or worse the entire package set(s) is updated as a unit. This creates the situation where updating GHC 9.2 causes regressions in the 9.2 package set (`ghc-lib*` stops working), but updating the package set would certainly cause regressions in other package sets. There would certainly have been a hack to work around this, but I chose saving some maintainer time over shipping GHC 9.2.2 as quickly as possible in this instance.

In hindsight, it would have been possible to expose an additional `ghc922` package set in addition to an unchanged `ghc921` package set, maybe I'll go down this path the next time around.

If you absolutely need GHC 9.2.2 for something, I would assume — though without testing it  — that the GHC 9.2.2 experience on `haskell-updates` is comparable to the 9.2.1 experience on `master` (albeit lacking the little binary cache `master` has for `aarch64-darwin`).

**Comment by maralorn** [comment]
Also normally we wouldn‘t expect haskell-updates to go without a merge for so long. So the drawback of not doing stuff on master was higher than expected.

**Pull request merged**
