### PR TITLE
ibus-engines.rime: init at 1.4.0

### PR DESCRIPTION
**Pull request by mschuwalow**
###### Motivation for this change
Adds an additional ibus engine.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mschuwalow** [comment]
Thanks @SuperSandro2000! Applied your formatting suggestions. I normally just use `nixfmt` to format my nix code. Do we have something similar we use at nixpkgs?

**Comment by SuperSandro2000** [comment]
> Thanks @SuperSandro2000! Applied your formatting suggestions. I normally just use `nixfmt` to format my nix code. Do we have something similar we use at nixpkgs?

I normally use https://github.com/nix-community/nixpkgs-fmt but it puts ever input on one line or one in each line which does not scale well with big packages.

**Review by SuperSandro2000 — COMMENTED** [review]
Please squash your commits together.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105449` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ibus-engines.rime</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/pull/87735.

**Comment by mschuwalow** [comment]
Ahh, didn't see that one. Feel free to close this one in favor of the other

**Comment by SuperSandro2000** [comment]
Closing in favor of #87735

**Pull request closed without merging**
