### PR TITLE
home-assistant: 2021.2.2 -> 2021.2.3

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/home-assistant/core/releases/tag/2021.2.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112772` at 800fdcfe run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/1f563aff2654f1d35fb48817d3a42625">home-assistant</a></li></li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/e0eb7ab43d9e03122b2b4b01b8e2a882">python37Packages.pymyq</a></li></li>
    <li><a href="https://gist.github.com/83b4729399168d69e4ff5742f04bfb2a">python38Packages.pymyq</a></li></li>
    <li><a href="https://gist.github.com/6b8f38ad7689c6e9c906f43362dffab1">python39Packages.pymyq</a></li></li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 112772` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python37Packages.pymyq</li>
    <li>python38Packages.pymyq</li>
    <li>python39Packages.pymyq</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 112772` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.pymyq</li>
    <li>python38Packages.pymyq</li>
    <li>python39Packages.pymyq</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Did the latter nixpkgs-review comment include the latest force-push? @fabaff

**Comment by fabaff** [comment]
Let me do a re-run.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 112772` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.pymyq</li>
    <li>python38Packages.pymyq</li>
    <li>python39Packages.pymyq</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 112772` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python37Packages.pymyq</li>
    <li>python38Packages.pymyq</li>
    <li>python39Packages.pymyq</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Interesting...two runs of `nix-review pr 112772`:

- libvirt-based setup: https://github.com/NixOS/nixpkgs/pull/112772#issuecomment-777509684
- actual hardware: builder for '/nix/store/1rxw6xfdcscvkx6n5xg9fsra401jiakq-homeassistant-2021.2.3.drv' failed with exit code 1; last 10 log lines:
      app[KEY_BANNED_IPS] = await async_load_ip_bans_config(
  
  tests/components/shell_command/test_init.py::test_do_no_run_forever[pyloop]
    /nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/asyncio/unix_events.py:917: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
      warnings.warn(
  
  -- Docs: https://docs.pytest.org/en/stable/warnings.html
  =========================== short test summary info ============================
  ERROR tests/components/system_log/test_init.py::test_normal_logs[pyloop] - Ru...
  ====== 3027 passed, 1 skipped, 11 warnings, 1 error in 136.04s (0:02:16) =======

```bash
builder for '/nix/store/1rxw6xfdcscvkx6n5xg9fsra401jiakq-homeassistant-2021.2.3.drv' failed with exit code 1; last 10 log lines:
      app[KEY_BANNED_IPS] = await async_load_ip_bans_config(
  
  tests/components/shell_command/test_init.py::test_do_no_run_forever[pyloop]
    /nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/asyncio/unix_events.py:917: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
      warnings.warn(
  
  -- Docs: https://docs.pytest.org/en/stable/warnings.html
  =========================== short test summary info ============================
  ERROR tests/components/system_log/test_init.py::test_normal_logs[pyloop] - Ru...
  ====== 3027 passed, 1 skipped, 11 warnings, 1 error in 136.04s (0:02:16) =======
```

Hmmm, and I thought that both machines are identical.

**Comment by mweinelt** [comment]
Great, more `RuntimeError: Event loop is closed` issues. It makes little sense to blacklist tests one-by-one, as race conditions can creep up in alot of places I guess. I could disable testing `ssdp`, `system_log` and `sun` completely.

Could you try and see if you can reproduce this with fewer xdist jobs, like  `-n 2` or `-n 1`?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 112772` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python37Packages.pymyq</li>
    <li>python38Packages.pymyq</li>
    <li>python39Packages.pymyq</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> Could you try and see if you can reproduce this with fewer xdist jobs, like -n 2 (GHA runners have two cpu threads)?

With `-n 2` the tests are passing for me.

**Comment by mweinelt** [comment]
I expanded on the commit message. The reasoning is that we can more closely replicate the upstreams testing environment this way. I've reenabled previously failing tests that are likely to have been caused by race conditions.

**Review by jonringer — APPROVED** [review]
diff LGTM

```
https://github.com/NixOS/nixpkgs/pull/112772

4 packages built:
home-assistant python37Packages.pymyq python38Packages.pymyq python39Packages.pymyq
```

**Review by fabaff — APPROVED** [review]

**Comment by mweinelt** [comment]
Thanks everyone for reviewing and checking again and again!

**Pull request merged**
