### PR TITLE
linux_5_12: remove

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Motivation for this change
https://lwn.net/ml/linux-kernel/1626791065147152@kroah.com/

###### Things done
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxPackages_latest_hardened.anbox</li>
    <li>linuxPackages_latest_hardened.ixgbevf</li>
    <li>linuxPackages_latest_hardened.mxu11x0</li>
    <li>linuxPackages_latest_hardened.ndiswrapper</li>
    <li>linuxPackages_latest_hardened.openafs</li>
    <li>linuxPackages_latest_hardened.openafs_1_9</li>
    <li>linuxPackages_latest_hardened.phc-intel</li>
    <li>linuxPackages_latest_hardened.r8125</li>
    <li>linuxPackages_latest_hardened.rtl8188eus-aircrack</li>
    <li>linuxPackages_latest_hardened.rtl8723bs</li>
    <li>linuxPackages_latest_hardened.rtl8812au</li>
    <li>linuxPackages_latest_hardened.sch_cake</li>
    <li>linuxPackages_latest_hardened.tbs</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_latest_hardened.amdgpu-pro</li>
    <li>linuxPackages_latest_hardened.nvidia_x11_legacy340</li>
  </ul>
</details>
<details>
  <summary>75 packages built:</summary>
  <ul>
    <li>linuxPackages_latest_hardened.acpi_call</li>
    <li>linuxPackages_latest_hardened.akvcam</li>
    <li>linuxPackages_latest_hardened.apfs</li>
    <li>linuxPackages_latest_hardened.asus-wmi-sensors</li>
    <li>linuxPackages_latest_hardened.batman_adv</li>
    <li>linuxPackages_latest_hardened.bbswitch</li>
    <li>linuxPackages_latest_hardened.bcc</li>
    <li>linuxPackages_latest_hardened.bpftrace</li>
    <li>linuxPackages_latest_hardened.broadcom_sta</li>
    <li>linuxPackages_latest_hardened.can-isotp</li>
    <li>linuxPackages_latest_hardened.chipsec</li>
    <li>linuxPackages_latest_hardened.cpupower</li>
    <li>linuxPackages_latest_hardened.cryptodev</li>
    <li>linuxPackages_latest_hardened.ddcci-driver</li>
    <li>linuxPackages_latest_hardened.digimend</li>
    <li>linuxPackages_latest_hardened.dpdk-kmods</li>
    <li>linuxPackages_latest_hardened.ena</li>
    <li>linuxPackages_latest_hardened.evdi</li>
    <li>linuxPackages_latest_hardened.facetimehd</li>
    <li>linuxPackages_latest_hardened.fwts-efi-runtime</li>
    <li>linuxPackages_latest_hardened.gcadapter-oc-kmod</li>
    <li>linuxPackages_latest_hardened.hid-nintendo</li>
    <li>linuxPackages_latest_hardened.hyperv-daemons</li>
    <li>linuxPackages_latest_hardened.intel-speed-select</li>
    <li>linuxPackages_latest_hardened.isgx</li>
    <li>linuxPackages_latest_hardened.it87</li>
    <li>linuxPackages_latest_hardened.jool</li>
    <li>linuxPackages_latest_hardened.kernel</li>
    <li>linuxPackages_latest_hardened.kvmfr</li>
    <li>linuxPackages_latest_hardened.lttng-modules</li>
    <li>linuxPackages_latest_hardened.mba6x_bl</li>
    <li>linuxPackages_latest_hardened.mbp2018-bridge-drv</li>
    <li>linuxPackages_latest_hardened.mwprocapture</li>
    <li>linuxPackages_latest_hardened.netatop</li>
    <li>linuxPackages_latest_hardened.nvidia_x11</li>
    <li>linuxPackages_latest_hardened.nvidia_x11_beta</li>
    <li>linuxPackages_latest_hardened.nvidia_x11_legacy390</li>
    <li>linuxPackages_latest_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_latest_hardened.nvidiabl</li>
    <li>linuxPackages_latest_hardened.oci-seccomp-bpf-hook</li>
    <li>linuxPackages_latest_hardened.openrazer</li>
    <li>linuxPackages_latest_hardened.perf</li>
    <li>linuxPackages_latest_hardened.ply</li>
    <li>linuxPackages_latest_hardened.r8168</li>
    <li>linuxPackages_latest_hardened.rtl8192eu</li>
    <li>linuxPackages_latest_hardened.rtl8814au</li>
    <li>linuxPackages_latest_hardened.rtl8821au</li>
    <li>linuxPackages_latest_hardened.rtl8821ce</li>
    <li>linuxPackages_latest_hardened.rtl8821cu</li>
    <li>linuxPackages_latest_hardened.rtl88x2bu</li>
    <li>linuxPackages_latest_hardened.rtl88xxau-aircrack</li>
    <li>linuxPackages_latest_hardened.rtlwifi_new</li>
    <li>linuxPackages_latest_hardened.rtw89</li>
    <li>linuxPackages_latest_hardened.sysdig</li>
    <li>linuxPackages_latest_hardened.system76</li>
    <li>linuxPackages_latest_hardened.system76-acpi</li>
    <li>linuxPackages_latest_hardened.system76-io</li>
    <li>linuxPackages_latest_hardened.systemtap</li>
    <li>linuxPackages_latest_hardened.tmon</li>
    <li>linuxPackages_latest_hardened.tp_smapi</li>
    <li>linuxPackages_latest_hardened.turbostat</li>
    <li>linuxPackages_latest_hardened.tuxedo-keyboard</li>
    <li>linuxPackages_latest_hardened.usbip</li>
    <li>linuxPackages_latest_hardened.v4l2loopback</li>
    <li>linuxPackages_latest_hardened.v86d</li>
    <li>linuxPackages_latest_hardened.veikk-linux-driver</li>
    <li>linuxPackages_latest_hardened.vendor-reset</li>
    <li>linuxPackages_latest_hardened.vhba</li>
    <li>linuxPackages_latest_hardened.virtualbox</li>
    <li>linuxPackages_latest_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_latest_hardened.x86_energy_perf_policy</li>
    <li>linuxPackages_latest_hardened.xmm7360-pci</li>
    <li>linuxPackages_latest_hardened.xpadneo</li>
    <li>linuxPackages_latest_hardened.zenpower</li>
    <li>linuxPackages_latest_hardened.zfs (linuxPackages_latest_hardened.zfsUnstable)</li>
  </ul>
</details>

**Comment by TredwellGit** [comment]
`linuxPackages_latest_hardened.amdgpu-pro` and `linuxPackages_latest_hardened.nvidia_x11_legacy340` are broken before this.

**Review by ymatsiuk — COMMENTED** [review]
I'm not using 5.12 hardened anywhere, but I wonder if there is a potential user impact with this downgrade 🤔 Does it make sense to wait for [5.13](https://github.com/anthraxx/linux-hardened/issues/60)?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 133587` at 957f0485 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/2c778d80587afb849557a2b6bf018f71">linuxPackages_latest_hardened.anbox</a></li>
    <li><a href="https://gist.github.com/b7d89814e56db22a67f005ae4b08a305">linuxPackages_latest_hardened.evdi</a></li>
    <li><a href="https://gist.github.com/d10bfd788fd56c0fc3d14ca8efedbdbc">linuxPackages_latest_hardened.mwprocapture</a></li>
    <li><a href="https://gist.github.com/8d9c4fd65065d0ce5eef1a090c31b2eb">linuxPackages_latest_hardened.mxu11x0</a></li>
    <li><a href="https://gist.github.com/8710f0fe213ced58548be839bb8d9983">linuxPackages_latest_hardened.openafs</a> (linuxPackages_latest_hardened.openafs_1_8)</li>
    <li><a href="https://gist.github.com/69449327b7673e2a33257f396206ca12">linuxPackages_latest_hardened.openafs_1_9</a></li>
    <li><a href="https://gist.github.com/122930054374822909383c2d93da2a33">linuxPackages_latest_hardened.rtl8192eu</a></li>
    <li><a href="https://gist.github.com/c41c46f96c1b38ef9980ea1d054329a6">linuxPackages_latest_hardened.rtl8723bs</a></li>
    <li><a href="https://gist.github.com/1a0bf5b7d0add2f93445d2d5095b4a97">linuxPackages_latest_hardened.rtl8812au</a></li>
    <li><a href="https://gist.github.com/6aba7635c01137be4e02710922e0197a">linuxPackages_latest_hardened.rtl8821ce</a></li>
    <li><a href="https://gist.github.com/ccedf2ea3f81070ecd580991c16c6886">linuxPackages_latest_hardened.sch_cake</a></li>
    <li><a href="https://gist.github.com/18df2f82ad048e0594ac4f73e5a69d7e">linuxPackages_latest_hardened.tuxedo-keyboard</a></li>
  </ul>
</details>
<details>
  <summary>40 packages built successfully:</summary>
  <ul>
    <li>linuxPackages_latest_hardened.acpi_call</li>
    <li>linuxPackages_latest_hardened.akvcam</li>
    <li>linuxPackages_latest_hardened.apfs</li>
    <li>linuxPackages_latest_hardened.batman_adv</li>
    <li>linuxPackages_latest_hardened.bcc</li>
    <li>linuxPackages_latest_hardened.can-isotp</li>
    <li>linuxPackages_latest_hardened.cpupower</li>
    <li>linuxPackages_latest_hardened.cryptodev</li>
    <li>linuxPackages_latest_hardened.ddcci-driver</li>
    <li>linuxPackages_latest_hardened.digimend</li>
    <li>linuxPackages_latest_hardened.dpdk-kmods</li>
    <li>linuxPackages_latest_hardened.ena</li>
    <li>linuxPackages_latest_hardened.fwts-efi-runtime</li>
    <li>linuxPackages_latest_hardened.gcadapter-oc-kmod</li>
    <li>linuxPackages_latest_hardened.hid-nintendo</li>
    <li>linuxPackages_latest_hardened.hyperv-daemons</li>
    <li>linuxPackages_latest_hardened.jool</li>
    <li>linux_latest_hardened (linuxPackages_latest_hardened.kernel)</li>
    <li>linuxPackages_latest_hardened.lttng-modules</li>
    <li>linuxPackages_latest_hardened.mba6x_bl</li>
    <li>linuxPackages_latest_hardened.mbp2018-bridge-drv</li>
    <li>linuxPackages_latest_hardened.netatop</li>
    <li>linuxPackages_latest_hardened.oci-seccomp-bpf-hook</li>
    <li>linuxPackages_latest_hardened.openrazer</li>
    <li>linuxPackages_latest_hardened.perf</li>
    <li>linuxPackages_latest_hardened.r8125</li>
    <li>linuxPackages_latest_hardened.r8168</li>
    <li>linuxPackages_latest_hardened.rtl8821cu</li>
    <li>linuxPackages_latest_hardened.rtl88x2bu</li>
    <li>linuxPackages_latest_hardened.rtw88 (linuxPackages_latest_hardened.rtlwifi_new)</li>
    <li>linuxPackages_latest_hardened.rtw89</li>
    <li>linuxPackages_latest_hardened.systemtap</li>
    <li>linuxPackages_latest_hardened.tmon</li>
    <li>linuxPackages_latest_hardened.usbip</li>
    <li>linuxPackages_latest_hardened.v4l2loopback</li>
    <li>linuxPackages_latest_hardened.veikk-linux-driver</li>
    <li>linuxPackages_latest_hardened.vhba</li>
    <li>linuxPackages_latest_hardened.xmm7360-pci</li>
    <li>linuxPackages_latest_hardened.xpadneo</li>
    <li>linuxPackages_latest_hardened.zfs (linuxPackages_latest_hardened.zfsStable ,linuxPackages_latest_hardened.zfsUnstable)</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by TredwellGit** [comment]
A hardened kernel with known vulnerabilities and no future security updates makes little sense.

**Review by ymatsiuk — APPROVED** [review]
I hope the downgrade will not break many people 😉 🤞🏻

**Review by Ma27 — APPROVED** [review]
I have a bit of a headache with backporting a "silent downgrade" (because of `linuxPackages_latest_hardened`), but as you correctly pointed out, we don't really have another choice. Also, it seems as if there's only a single maintainer of these patches, so people who use this should be aware of the risk.

However I think that we should drop the `linuxPackages_latest_hardened`-attribute (on master only) entirely. Then we won't have situations like this in the future where the `_latest` attribute has to point to an older kernel version (which isn't intuitive).

**Comment by Ma27** [comment]
I'd merge this tomorrow and file a follow-up PR which removes linuxPackages_hardened_latest for the reasons I mentioned above. I'll od it in a second PR on purpose as this should probably not be backported.

**Pull request merged**
