### PR TITLE
 coqPackages: fix bignums and equations

### PR DESCRIPTION
**Pull request by CohenCyril**
###### Motivation for this change

The versions for coqPackages bignums and equations were outdated

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by CohenCyril** [comment]
@vbgl could you trigger a build?

**Comment by vbgl** [comment]
@GrahamcOfBorg build coqPackages_8_6.bignums coqPackages_8_7.bignums coqPackages_8_8.bignums coqPackages_8_9.bignums

**Comment by vbgl** [comment]
This broke `category-theory`, didn’t it?

**Comment by CohenCyril** [comment]
> This broke `category-theory`, didn’t it?

yes apparently it did.

**Comment by CohenCyril** [comment]
Hi @vbgl what is the policy for this? should we
-  revert equation to an older version?
- or create a new attribute for the old version and use it in the now-broken package
- or mark the package as broken?
- or another solution?

**Comment by vbgl** [comment]
ping @jwiegley

**Pull request merged**
