### PR TITLE
[WIP] Update nodePackages with node2nix 1.10.0

### PR DESCRIPTION
**Pull request by svanderburg**
###### Motivation for this change

I'm working on updating the NPM packages to be regenerated with node2nix 1.10.0

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Great to see you around! (Thanks a lot for the node2nix contribution btw)
You might be aware of this issue https://github.com/NixOS/nixpkgs/issues/145432
a missing bin for nodePackages built with node16.
since 16 is lts, there are efforts to change the default node version from 14 to 16. My understanding is that the next node2nix version handles node 16 correctly.
Let me know if I can be of any help.
Thanks again!

**Comment by svanderburg** [comment]
@happysalada Yes I've added an option to handle Node.js 16.x out of the box. Some of the stuff that I need seems to work, but we still have to see how well the integration works.

I also intend make the modifications so that we can package for Node.js 16.x. We probably should start with a small set of packages first and then gradually expand it.

**Comment by happysalada** [comment]
Amazing thanks! I think prettier was one of the problematic packages. If it works properly for prettier, then the potential problem might have been fixed.

**Comment by shinzui** [comment]
Hi. Is there anything blocking updating to node2nix 1.10.0?

**Comment by dotlambda** [comment]
This fixes node2nix when using Node.js >= 15, right?
Since electron 14, which is the last version supporting Node.js 14, is now EOL (https://github.com/NixOS/nixpkgs/pull/166825), we should really try to get this merged.
cc @prusnak @teutat3s

**Comment by CMCDragonkai** [comment]
What's blocking this?

**Comment by CMCDragonkai** [comment]
I'm wondering why `node2nix` even on master of nixpkgs (https://github.com/NixOS/nixpkgs/commit/a5774e76bb8c3145eac524be62375c937143b80c) is still `1.9.0` even though it claims to be `1.10.0`.

```
nix-repl> pkgs.nodePackages.node2nix.version
"1.10.0"

nix-repl> node2nix
«derivation /nix/store/ipkkiavdmj2m8m9zxdkjsd8kfxqdj27c-node2nix-1.10.0.drv»

nix-repl> :b node2nix
[62 copied (334.6 MiB), 79.6 MiB DL]

this derivation produced the following outputs:
  out -> /nix/store/nz0fw6vhdfhv45nzlxahp6383p3m9lyj-node2nix-1.10.0
```

But:

```
$ /nix/store/nz0fw6vhdfhv45nzlxahp6383p3m9lyj-node2nix-1.10/bin/node2nix --version
node2nix 1.9.0
$ /nix/store/nz0fw6vhdfhv45nzlxahp6383p3m9lyj-node2nix-1.10/bin/node2nix --help | grep nodejs
  -4, --nodejs-4                Provides all settings to generate expression for usage with Node.js 4.x (default is: Node.js 12.x)
  -6, --nodejs-6                Provides all settings to generate expression for usage with Node.js 6.x (default is: Node.js 12.x)
  -8, --nodejs-8                Provides all settings to generate expression for usage with Node.js 8.x (default is: Node.js 12.x)
  -10, --nodejs-10              Provides all settings to generate expression for usage with Node.js 10.x (default is: Node.js 12.x)
  -12, --nodejs-12              Provides all settings to generate expression for usage with Node.js 12.x (default is: Node.js 12.x)
  -13, --nodejs-13              Provides all settings to generate expression for usage with Node.js 13.x (default is: Node.js 12.x)
  -14, --nodejs-14              Provides all settings to generate expression for usage with Node.js 14.x (default is: Node.js 12.x)
  --pkg-name NAME               Specifies the name of the Node.js package to use from Nixpkgs (defaults to: nodejs)
```

It doesn't even show the `--nodejs-16` option.

**Comment by dotlambda** [comment]
> I'm wondering why `node2nix` even on master of nixpkgs ([a5774e7](https://github.com/NixOS/nixpkgs/commit/a5774e76bb8c3145eac524be62375c937143b80c)) is still `1.9.0` even though it claims to be `1.10.0`.

That's because of the override in [`pkgs/development/node-packages/default.nix`](https://github.com/NixOS/nixpkgs/blob/2627bb20f913f1b3a982758383f7dd3192c7f47f/pkgs/development/node-packages/default.nix#L248).

**Comment by dotlambda** [comment]
My suggestion would be something like this where we don't touch packages that aren't inside `nodePackages`: https://github.com/NixOS/nixpkgs/pull/170722
Note that it breaks their update scripts however.

**Review by freezeboy — APPROVED** [review]
Nice ! thank you

**Comment by ParetoOptimalDev** [comment]
I believe this is blocking [fixing mongosh](https://github.com/NixOS/nixpkgs/issues/187337) and pretty much [all nodejs_16x packages](https://github.com/NixOS/nixpkgs/issues/132456). 

It seems like it was approved but never merged, so this should be low-hanging fruit if the merge conflict isn't too difficult?

**Comment by lilyinstarlight** [comment]
> I believe this is blocking [fixing mongosh](https://github.com/NixOS/nixpkgs/issues/187337) and pretty much [all nodejs_16x packages](https://github.com/NixOS/nixpkgs/issues/132456).
> 
> It seems like it was approved but never merged, so this should be low-hanging fruit if the merge conflict isn't too difficult?

node2nix was already updated in #171195 as I understand it. This PR also regenerates a few of the packages not under `pkgs/development/node-packages`, but that may have already been done in separate PRs as well

I believe there are still issues some issues with node2nix and Node.js 16+ that will need to be fixed in [svanderburg/node2nix](https://github.com/svanderburg/node2nix) first before some of those packages will work correctly. Mostly https://github.com/svanderburg/node2nix/issues/236#issuecomment-1107138813 and https://github.com/svanderburg/node2nix/issues/293 I think

**Comment by winterqt** [comment]
> I believe this is blocking [fixing mongosh](https://github.com/NixOS/nixpkgs/issues/187337) and pretty much [all nodejs_16x packages](https://github.com/NixOS/nixpkgs/issues/132456).

I don't think this is true -- node2nix still cannot output v2 lockfiles.

**Comment by ParetoOptimalDev** [comment]
> > I believe this is blocking [fixing mongosh](https://github.com/NixOS/nixpkgs/issues/187337) and pretty much [all nodejs_16x packages](https://github.com/NixOS/nixpkgs/issues/132456).
> 
> I don't think this is true -- node2nix still cannot output v2 lockfiles.

 My mistake, I'm new to node/javascript on NixOS and just got here by attempting to connect to a mongo server using the mongo cli on nixos :sweat_smile:

**Pull request closed without merging**
