### PR TITLE
vkdt: 0.7.0 -> 0.9.0 

### PR DESCRIPTION
**Pull request by korrat**
Updates `vkdt` to version [`0.9.0`](https://github.com/hanatos/vkdt/releases/tag/0.9.0), including setup for building rust parts of the code.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by korrat** [comment]
Both binaries start, but I ran into issues getting the GUI to work under wayland. Reported upstream at https://github.com/hanatos/vkdt/issues/142

**Comment by paperdigits** [comment]
hey, amazing! thank you for taking the time to do this.

> Both binaries start, but I ran into issues getting the GUI to work under wayland. Reported upstream at [hanatos/vkdt#142](https://github.com/hanatos/vkdt/issues/142)

When you say "both binaries start" do you mean `vkdt` and `vkdt-cli`? We used to get several binaries, one of them was `vkdt-wayland` (for wayalnd) and `vkdt` (for xorg). Not sure why the `vkdt-wayland` binary is no longer produce.

My other question is can we use the `Cargo.lock` file in `src/pipe/modules/i-raw/rawloader-c/Cargo.lock` [seen here](https://github.com/hanatos/vkdt/blob/master/src/pipe/modules/i-raw/rawloader-c/Cargo.lock) or is that lock file not sufficient?

**Comment by korrat** [comment]
> When you say "both binaries start" do you mean vkdt and vkdt-cli?

Exactly. I also tested out the `vkdt-wayland` package which seems to be automatically created.

> My other question is can we use the Cargo.lock file in src/pipe/modules/i-raw/rawloader-c/Cargo.lock [seen here](https://github.com/hanatos/vkdt/blob/master/src/pipe/modules/i-raw/rawloader-c/Cargo.lock) or is that lock file not sufficient?

I tried using the commited `Cargo.lock` with [`fetchCargoTarball`], but that did not work due to the git dependency. Therefore, I switched to `importCargoLock`, but that requires the `Cargo.lock` in `nixpkgs`, as far as I can tell.

**Comment by paperdigits** [comment]
Alright, cool. Do we get this merged, since it seems to work if the GPU drivers work?

**Review by paperdigits — APPROVED** [review]
Approved, thanks.

**Review by ConnorBaker — APPROVED** [review]

**Pull request merged**
