### PR TITLE
pappl: init at 1.0.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
been in the news recently, looks promising

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
cc @marsam

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107009` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pappl</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107009` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>pappl</li>
  </ul>
</details>

```
3 warnings generated.
Compiling job-accessors.c...
In file included from device-usb.c:15:
In file included from ./device-private.h:17:
./base-private.h:43:13: warning: 'strlcpy' macro redefined [-Wmacro-redefined]
#    define strlcpy(dst,src,dstsize) _pappl_strlcpy(dst,src,dstsize)
            ^
/nix/store/r913a0b23i21r8y4x8kgx024gms9lvx9-Libsystem-osx-10.12.6/include/secure/_string.h:104:9: note: previous definition is here
#define strlcpy(dest, src, len)                                 \
        ^
In file included from dnssd.c:15:
In file included from ./pappl-private.h:19:
In file included from ./dnssd-private.h:18:
./base-private.h:43:13: warning: 'strlcpy' macro redefined [-Wmacro-redefined]
#    define strlcpy(dst,src,dstsize) _pappl_strlcpy(dst,src,dstsize)
            ^
/nix/store/r913a0b23i21r8y4x8kgx024gms9lvx9-Libsystem-osx-10.12.6/include/secure/_string.h:104:9: note: previous definition is here
#define strlcpy(dest, src, len)                                 \
        ^
dnssd.c:267:10: error: use of undeclared identifier 'kDNSServiceErr_DefunctConnection'; did you mean 'kDNSServiceFlagsShareConnection'?
    case kDNSServiceErr_DefunctConnection :
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         kDNSServiceFlagsShareConnection
/nix/store/r913a0b23i21r8y4x8kgx024gms9lvx9-Libsystem-osx-10.12.6/include/dns_sd.h:277:5: note: 'kDNSServiceFlagsShareConnection' declared here
    kDNSServiceFlagsShareConnection     = 0x4000,
    ^
1 warning and 1 error generated.
make[1]: *** [../Makedefs:72: dnssd.o] Error 1
make[1]: *** Waiting for unfinished jobs....
1 warning generated.
In file included from job-accessors.c:14:
In file included from ./pappl-private.h:19:
In file included from ./dnssd-private.h:18:
./base-private.h:43:13: warning: 'strlcpy' macro redefined [-Wmacro-redefined]
#    define strlcpy(dst,src,dstsize) _pappl_strlcpy(dst,src,dstsize)
            ^
/nix/store/r913a0b23i21r8y4x8kgx024gms9lvx9-Libsystem-osx-10.12.6/include/secure/_string.h:104:9: note: previous definition is here
#define strlcpy(dest, src, len)                                 \
        ^
1 warning generated.
1 warning generated.
make[1]: Leaving directory '/private/tmp/nix-build-pappl-1.0.0.drv-0/source/pappl'
make: *** [Makefile:28: all] Error 1
```

**Comment by jonringer** [comment]
mac should have support, but I'll just mark linux only for now

**Pull request merged**
