### PR TITLE
rustBuildCrate: properly handle cargo env pragmas with spaces

### LINKED ISSUE #199298: rust: `cargo` and `buildRustCrate` disagree on escaping of `rustc-env` directives (and probably more)
### Describe the bug
At start of Rust crate build, developers can emit various directives in `build.rs` that then impact the rest of the build.

It seems that `cargo` handling of these directives differs from the `buildRustCrate` handling we have when the values contain spaces.

### Steps To Reproduce
Create `build.rs` like below:

```rust
fn main() {
    println!("cargo:rustc-env=SHOULD_BE_THREE_WORDS=first second third")
}
```

Simple `src/main.rs`
```rust
fn main() {
    let should_be_three_words = env!("SHOULD_BE_THREE_WORDS");
    println!("Expecting three words, got: {}", should_be_three_words);
}
```

`Cargo.toml` for completeness

```toml
[package]
name = "nix-rustc-env-escape-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

Create a nix derivation for a create. I'm using `crate2nix` but you can use whatever, as long as it goes via `buildRustCrate` in the end.

```console
$ crate2nix -- generate -f ./Cargo.toml
```

Finally, run both via cargo and via `buildRustCrate` and see the difference.

```console
[nix-develop]$ $(nix-build -I nixpkgs=/home/shana/programming/nixpkgs Cargo.nix -A rootCrate.build  --no-out-link)/bin/nix-rustc-env-escape-repro
Expecting three words, got: first
[nix-develop]$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/nix-rustc-env-escape-repro`
Expecting three words, got: first second third
```

### Expected behavior
The nixpkgs builder should have the same semantics as the cargo one.

### Notify maintainers

Unsure.

### Metadata
nixpkgs 067c3ad6a7963b37d35a1a76b631ac34dc6e6fc7

anything else should be irrelevant here

### PR DESCRIPTION
**Pull request by Fuuzetsu**
There are two problems: first that we end up splitting on spaces in the loop. Even when that is fixed, we still would split on spaces in the `export` inside the loop. We need to guard against both.

Fixes #199298

Confirmed that it fixes the case mentioned in the ticket:

```console
[nix-develop]$ $(nix-build -I nixpkgs=/home/shana/programming/nixpkgs Cargo.nix -A rootCrate.build  --no-out-link)/bin/nix-rustc-env-escape-repro
Expecting three words, got: first second third
```

I think this is going to cause a rebuild of every Rust package even if they were unaffected, not much we can do here.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
Ah, this breaks on multiple variables being present: I guess splitting on spaces is what made it work before. I'll fix the patch.

**Comment by Fuuzetsu** [comment]
> Ah, this breaks on multiple variables being present: I guess splitting on spaces is what made it work before. I'll fix the patch.

Aha, this patch actually prints empty line if nothing matches... Trying to figure out how to get it to work nicely while still producing escaped stuff...

**Comment by Fuuzetsu** [comment]
OK, _now_ I think it's ready. I made a derp with escaping myself so it didn't work if multiple lines were present. I addressed the issue.

**Comment by lblasc** [comment]
I've tested this patch for a week with crate2nix, no problems so far :+1: 

@aanderse can you merge this one ?

**Comment by Fuuzetsu** [comment]
As another data point, we've been running it for 2 weeks on a medium(?) size workspace:

```
[nix-develop]$ cargo tree | wc -l
2958
```

No issues.

**Review by aanderse — APPROVED** [review]
Looks good to me. Thanks everyone!

**Pull request merged**
