### PR TITLE
libusb-compat: fix up the .so so it can find libusb1

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Applications using libusb-compat do not run after
https://github.com/NixOS/nixpkgs/pull/48434 as libusb-compat is no longer able
to find libusb1.

With this in place, g15daemon is running again.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Cc: @Infinisil & @lschuermann who worked on the referenced PR.

**Comment by lschuermann** [comment]
Thanks for pointing this out. Weird that it now requires setting the `RPATH` manually, I could've sworn to have tested libusb-compat with the old PR. However that was 2018, my brain may just confuse some things.

**Review by lschuermann — APPROVED** [review]
However this patch does make sense, I just tested with your `g15daemon` and both libusb-compat and libusb1 propagate through to the `RPATH`. I can't verify the functionality of `g15daemon` itself.

This has my go! I'd like to wait for @Infinisil's comments though.

**Comment by peterhoeg** [comment]
Thanks for looking into this @lschuermann. I'm merging this into staging due to the rebuilds.

**Pull request merged**
