### PR TITLE
callCabal2nix: Passthru deriver

### PR DESCRIPTION
**Pull request by ElvishJerricco**
###### Motivation for this change

When using callCabal2nix or callHackage, it is often useful to debug a failure by inspecting the Nix expression generated by cabal2nix. This can be accessed via this deriver field.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @shlevy

### CODE REVIEW

**Review by shlevy — APPROVED** [review]

**Review by basvandijk — APPROVED** [review]
I occasionally need this myself. So I'm +1.

**Comment by basvandijk** [comment]
Seems to work:

```
$ cat $(nix-store -r $(nix-build -E 'let pkgs = import ./. {}; drv = pkgs.haskellPackages.callHackage "scientific" "0.3.6.2" {}; in drv.deriver'))/default.nix
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
{ mkDerivation, base, binary, bytestring, containers, criterion
, deepseq, hashable, integer-gmp, integer-logarithms, primitive
, QuickCheck, smallcheck, stdenv, tasty, tasty-ant-xml, tasty-hunit
, tasty-quickcheck, tasty-smallcheck, text
}:
mkDerivation {
  pname = "scientific";
  version = "0.3.6.2";
  sha256 = "278d0afc87450254f8a76eab21b5583af63954efc9b74844a17a21a68013140f";
  libraryHaskellDepends = [
    base binary bytestring containers deepseq hashable integer-gmp
    integer-logarithms primitive text
  ];
  testHaskellDepends = [
    base binary bytestring QuickCheck smallcheck tasty tasty-ant-xml
    tasty-hunit tasty-quickcheck tasty-smallcheck text
  ];
  benchmarkHaskellDepends = [ base criterion ];
  homepage = "https://github.com/basvandijk/scientific";
  description = "Numbers represented using scientific notation";
  license = stdenv.lib.licenses.bsd3;
}
```

**Comment by basvandijk** [comment]
@ryantm agree to merge this?

**Comment by ElvishJerricco** [comment]
Is `deriver` too general a name? I could see that namespace being valuable for other derivation related things at some point. Maybe it should be `cabal2nixDeriver`?

**Comment by basvandijk** [comment]
Good point. I wonder if we shouldn't name it: `cabal2nixDerivation` or `cabal2nixDrv` since it evaluates to a path of a .drv file in the nix store.

**Comment by basvandijk** [comment]
Oh you're right of course. I got confused by my own example above.

Then I agree `cabal2nixDeriver` is a good name.

**Comment by basvandijk** [comment]
I also like `cabal2nixOutput` but I don't want to bikeshed this too much so I'm fine with `cabal2nixDeriver`.

**Comment by ElvishJerricco** [comment]
Alright. I've changed it. Anything else before merging?

**Comment by basvandijk** [comment]
Thank you!

**Pull request merged**
