### PR TITLE
xpra: 5.0.9 -> 6.1.2

### PR DESCRIPTION
**Pull request by hxtmdev**
## Description of changes

Update xpra to newest version 6.1.0

- `libfakeXinerama` patch removed as it is [no longer used upstream](https://github.com/Xpra-org/xpra/commit/5cfc9c21fd90d6d5923d399985f9c1c62bdfa4a8) but library left unchanged since it exists in its [own repository](https://github.com/Xpra-org/libfakeXinerama) and may be used / useful elsewhere
- ~`fix-122159.patch` removed as it appears to be obsoleted by an [upstream change](https://github.com/Xpra-org/xpra/commit/8a7ba25020ef93e79c1555e78cf3240087588607)~

I tested seamless mode without sound with an upstream 6.1 client on Debian, **I did not test the module, sound, most other features. Tests in that direction as well as a review of #279974 by people that use it would be appreciated!**

breakages as per nixpkgs-review [unchanged](https://github.com/NixOS/nixpkgs/pull/303930#pullrequestreview-2195180597)
```
2 packages failed to build:
xpraWithNvenc xpraWithNvenc.dist

3 packages built:
run-scaled xpra xpra.dist
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by aqrln** [comment]
> fix-122159.patch removed as it appears to be obsoleted by an [upstream change](https://github.com/Xpra-org/xpra/commit/8a7ba25020ef93e79c1555e78cf3240087588607)

I'm not sure I follow, the linked commit seems to be a purely stylistic change with no change in behaviour

**Comment by hxtmdev** [comment]
> I'm not sure I follow, the linked commit seems to be a purely stylistic change with no change in behaviour

You are very much correct! Not sure how I managed to misread it like that. Thanks!

**Comment by aqrln** [comment]
Result of `nixpkgs-review pr 332295` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>xpraWithNvenc</li>
    <li>xpraWithNvenc.dist</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>run-scaled</li>
    <li>xpra</li>
    <li>xpra.dist</li>
  </ul>
</details>

**Comment by aqrln** [comment]
Sorry I didn't have time to take a look yet, will try to do it asap.

**Comment by hxtmdev** [comment]
Updated to 6.1.1 from 6h ago.

**Comment by hxtmdev** [comment]
updated to 6.1.2

**Review by emilazy — APPROVED** [review]
Sorry for how long this PR has languished. I was reminded of it when noticing that Xpra fails to build on `staging-next` due to the FFmpeg 7 upgrade, so I’m merging this now. There’s a 6.1.3 out now too which I promise to review faster if you do the bump :)

**Pull request merged**
