### PR TITLE
check-meta: use system tuple in platforms

### LINKED ISSUE #60345: meta.platforms is broken
Once upon a time, `meta.platforms` contained more-or-less sensible information:
```
$ nix-env -f channel:nixos-17.09 -qaA geeqie --json | jq .[].meta.platforms
[
  "aarch64-linux",
  "armv5tel-linux",
  "armv6l-linux",
  "armv7l-linux",
  "mips64el-linux",
  "i686-linux",
  "x86_64-linux"
]
```

Now, however, it contains a lot of irrelevant information, and **omits the thing that matters**, namely the platform names (e.g. `x86_64-linux`):
```
$ nix-env -f channel:nixos-19.03 -qaA geeqie --json | jq .[].meta.platforms
[
  {
    "abi": {
      "_type": "abi",
      "name": "gnu"
    },
    "kernel": {
      "_type": "kernel",
      "execFormat": {
        "_type": "exec-format",
        "name": "elf"
      },
      "families": {},
      "name": "linux"
    }
  },
  {
    "abi": {
      "_type": "abi",
      "float": "soft",
      "name": "gnueabi"
    },
    "kernel": {
      "_type": "kernel",
      "execFormat": {
        "_type": "exec-format",
        "name": "elf"
      },
      "families": {},
      "name": "linux"
    }
  },
  {
    "abi": {
      "_type": "abi",
      "float": "hard",
      "name": "gnueabihf"
    },
    "kernel": {
      "_type": "kernel",
      "execFormat": {
        "_type": "exec-format",
        "name": "elf"
      },
      "families": {},
      "name": "linux"
    }
  },
  {
    "kernel": {
      "_type": "kernel",
      "execFormat": {
        "_type": "exec-format",
        "name": "elf"
      },
      "families": {},
      "name": "linux"
    }
  }
]
```

This broke the display of supported platforms at https://nixos.org/nixos/packages.html. It also seems horribly over-engineered to me. (I mean, it's one thing to be able to map platform types to information like executable formats, but it's going rather too far to use that information to *identify* the platform.)

### PR DESCRIPTION
**Pull request by matthewbauer**
Fixes #60345

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by samueldr** [comment]
Just a heads up, since checks failing don't send a notification:

```
attribute 'riscv' missing, at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-2-shlevy.ewr1.nix.ci/pkgs/os-specific/linux/kexectools/default.nix:26:20
```

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Comment by globin** [comment]
Shouldn't you be able to remove lib.systems.forMeta and for-meta.nix with this?

**Comment by matthewbauer** [comment]
Yeah probably ok to do that

**Pull request merged**
