### PR TITLE
nextcloud: 21.0.0 -> 21.0.1

### PR DESCRIPTION
**Pull request by beardhatcode**
###### Motivation for this change
Bump the version,

I also added a comment to quickly get the sha from nextcloud

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by beardhatcode** [comment]
Result of `nixpkgs-review pr 118882` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nextcloud21</li>
  </ul>
</details>

**Comment by beardhatcode** [comment]
Currently runs on my server

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118882` at c3367cc4 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>nextcloud21</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/servers/nextcloud/default.nix:18:5:
```
   |
18 |     installPhase = ''
   |     ^
```
</li>
  </ul>
</details>

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Ported to stable as a6847cb5460b47241eb35d1a6588652411642066.

**Pull request merged**
