### PR TITLE
electrum: 4.0.6 -> 4.0.7

### PR DESCRIPTION
**Pull request by prusnak**
Version update - release notes: https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES

This release also fixes compatibility with dnspython 2.x, so we can drop the overrides

Also cryptography is required instead of pycryptodomex (which is required only for tests now) and ecdsa dependency is dropped completely

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by drewrisinger — APPROVED** [review]
* [x] Diff LGTM
* [x] Commits LGTM
* [x] Builds via ``nix-review``:

```
https://github.com/NixOS/nixpkgs/pull/106459
1 package built:
electrum
```

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106459` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>electrum</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Fails on darwin with:

```
                    except OSError as err:                                                                                                                                                  >                       raise OSError(err.errno, 'error while attempting '                                                                                                                                                        'to bind on address %r: %s'                                                                                                                                                                 % (sa, err.strerror.lower())) from None                                                                                                               E                                     PermissionError: [Errno 1] error while attempting to bind on address ('127.0.0.1', 42898): operation not permitted                                                                                                                                                                                                                                /nix/store/cwrsy4lr71pbs89krkfcwb3s4amc3rjg-python3-3.8.6/lib/python3.8/asyncio/base_events.py:1463: PermissionError                                                                        --------------------------- Captured stderr teardown --------------------------

....

electrum/tests/test_network.py::TestNetwork::test_can_connect_during_backward
electrum/tests/test_network.py::TestNetwork::test_chain_false_during_binary
electrum/tests/test_network.py::TestNetwork::test_fork_conflict
electrum/tests/test_network.py::TestNetwork::test_fork_noconflict
  /nix/store/cwrsy4lr71pbs89krkfcwb3s4amc3rjg-python3-3.8.6/lib/python3.8/asyncio/events.py:81: RuntimeWarning: coroutine 'ignore_exceptions.<locals>.wrapper' was never awaited
    self._context.run(self._callback, *self._args)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED electrum/tests/test_lntransport.py::TestLNTransport::test_loop - Permi...
============ 1 failed, 502 passed, 3 skipped, 4 warnings in 39.40s =============
--- Logging error ---
Traceback (most recent call last):
  File "/nix/store/cwrsy4lr71pbs89krkfcwb3s4amc3rjg-python3-3.8.6/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/nix/store/cwrsy4lr71pbs89krkfcwb3s4amc3rjg-python3-3.8.6/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/nix/store/cwrsy4lr71pbs89krkfcwb3s4amc3rjg-python3-3.8.6/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/private/tmp/nix-build-electrum-4.0.7.drv-0/Electrum-4.0.7/electrum/plugin.py", line 214, in run
    self.on_stop()
  File "/private/tmp/nix-build-electrum-4.0.7.drv-0/Electrum-4.0.7/electrum/util.py", line 357, in on_stop
    self.logger.info("stopped")
Message: 'stopped'
Arguments: ()
```

**Comment by prusnak** [comment]
> Fails on darwin with:

Disabled the offending test in 16b38b07821de532b33aedaf85b45dbbc0a38e39

**Review by ghost — APPROVED** [review]

**Pull request merged**
