### PR TITLE
fnott: 1.5.0 -> 1.6.0

### PR DESCRIPTION
**Pull request by jmbaur**
## Description of changes

fnott added a dbus service file, requiring the use of PKG_CONFIG_DBUS_1_SESSION_BUS_SERVICES_DIR.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by riskygit** [comment]
Hoping this can be merged soon.

**Comment by riskygit** [comment]
@polykernel just tagging you for visibility. this fixes a rendering bug for me.

**Comment by polykernel** [comment]
Thanks for the ping. I did not receive notification for the PR.

**Review by polykernel — APPROVED** [review]
Is there a way to pass the dbus install_dir option to meson directly here instead of going through pkg-config? Otherwise, this looks good to me.

**Comment by jmbaur** [comment]
My meson-foo isn't super strong, is there a way to override this `install_dir` [here](https://codeberg.org/dnkl/fnott/src/branch/master/dbus/meson.build#L7)? If not we could add a patch, but the environment variable seems cleaner in that case.

**Comment by polykernel** [comment]
I did some digging and could not find an easy way to override the `install_dir`. In addition, the dbus package in nixpkgs sets `datadir` to `/etc` so there isn't a way to set the `datadir` option in meson and trigger the default value. I naively thought there must be some nice way to accomplish this but it seems the intended way is indeed passing through a config backend. In which case I agree with you that passing the environment variable is cleaner.

**Comment by pbsds** [comment]
> Thanks for the ping. I did not receive notification for the PR.

It seems you're not a part of the nixpkgs-maintainers team, please post in https://github.com/NixOS/nixpkgs/issues/234293

**Comment by polykernel** [comment]
Thanks for the heads-up. Unfortunately, I can't dedicate as much time as I used to package maintenance and will not be able to uphold the responsibility of being a maintainer in the foreseeable future. I have been inactive with respect to Nixpkgs for more than a year and regret not disclosing the situation earlier. I think it would be best for me to step away from the maintainer role and pass on the baton to other aspiring contributors in the community.

**Pull request merged**
