### PR TITLE
nixos/plasma5: dont set "plasma" to `services.xserver.displayManager.defaultSession`

### LINKED ISSUE #291501: Plasma 5: should not set `services.xserver.displayManager.defaultSession`
## Issue description

Since there were bugs in plasma wayland, we added [this](https://github.com/NixOS/nixpkgs/blob/e3474e1d1e53b70e2b2af73ea26d6340e82f6b8b/nixos/modules/services/x11/desktop-managers/plasma5.nix#L411-L414) in #143673.

However, since plasma wayland seems working fine today, maybe we should remove this workaround.

Also, this might lead to ignorant of session history if I don't misunderstand [this](https://github.com/NixOS/nixpkgs/blob/e3474e1d1e53b70e2b2af73ea26d6340e82f6b8b/nixos/modules/services/x11/display-managers/lightdm.nix#L204C7-L204C103), which is surprising to the user.

### PR DESCRIPTION
**Pull request by SaltyKitkat**
## Description of changes

close #291501

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by LunNova — COMMENTED** [review]
Not sure this is a good idea as there's now nothing to deprioritize plasma (wayland) on plasma 5 when plasma's the only DE enabled.

**Comment by K900** [comment]
What are you trying to do with this and why?

**Comment by SuperSandro2000** [comment]
From the issue:

> However, since plasma wayland seems working fine today, maybe we should remove this workaround.

That isn't true. Plasma 5 Wayland is still buggy and not recommendable. Plasma *6* Wayland is in a usable state.

**Comment by SaltyKitkat** [comment]
Thanks for your attention.
I come with this idea because I found that `services.xserver.displayManager.defaultSession` is set to plasma(x11) as long as I enable plasma desktop. So I have to choose another session every time when sddm choose plasma(x11) as default, which is quite annoying.
After knowing 

> Plasma 5 Wayland is still buggy and not recommendable.

and https://github.com/NixOS/nixpkgs/pull/139657#issuecomment-951426061, I found this is not a good idea, and I will close this.

**Pull request closed without merging**
