### PR TITLE
pulumi-bin: 3.6.0 -> 3.9.0

### PR DESCRIPTION
**Pull request by t0yv0**
###### Motivation for this change

Upgrading pulumi to latest

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by t0yv0** [comment]
CC @austinbutler

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 131979` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Review by austinbutler — APPROVED** [review]

**Comment by Artturin** [comment]
3.9.1 is out

**Comment by mudrii** [comment]
Semes latest Pulumi having an issue with 3.9.x can find libstdc++.so.6 is anybody having the same issue?

```
Diagnostics:                                                                                                           │Activating onFilesChange
  pulumi:pulumi:Stack (infra-devworkspace-main):                                                                       │Activating reloadSystemd
    warning: resource plugin gcp is expected to have version >=5.14.0, but has 5.13.0; the wrong version may be on your│ mudrii@nixos  ~  ossw                                                                                         1282ms
 path, or this may be a bug in the plugin                                                                              │warning: Git tree '/etc/nixos' is dirty
    error: an unhandled error occurred: Program exited with non-zero exit code: 1                                      │building the system configuration...
                                                                                                                       │warning: Git tree '/etc/nixos' is dirty
    Traceback (most recent call last):                                                                                 │updating GRUB 2 menu...
      File "/nix/store/7vl46g758zf3c05fswd2ciwx6nybmsrv-pulumi-3.9.0/bin/pulumi-language-python-exec", line 14, in <mod│activating the configuration...
ule>                                                                                                                   │setting up /etc...
        import pulumi                                                                                                  │reloading user units for mudrii...
      File "/nix/store/zk52v8kb14nlqhlwn24b2rrg0gi1widb-python3-3.9.4-env/lib/python3.9/site-packages/pulumi/__init__.p│setting up tmpfiles
y", line 33, in <module>                                                                                               │the following new units were started: nixos-auto-update.service
        from .config import (                                                                                          │ mudrii@nixos  ~                                                                                                 7.6s
      File "/nix/store/zk52v8kb14nlqhlwn24b2rrg0gi1widb-python3-3.9.4-env/lib/python3.9/site-packages/pulumi/config.py"│
, line 22, in <module>                                                                                                 │
        from . import log                                                                                              │
      File "/nix/store/zk52v8kb14nlqhlwn24b2rrg0gi1widb-python3-3.9.4-env/lib/python3.9/site-packages/pulumi/log.py", l│
ine 22, in <module>                                                                                                    │
        from .runtime.settings import get_engine                                                                       │
      File "/nix/store/zk52v8kb14nlqhlwn24b2rrg0gi1widb-python3-3.9.4-env/lib/python3.9/site-packages/pulumi/runtime/__│
init__.py", line 29, in <module>                                                                                       │
        from .mocks import (                                                                                           │
      File "/nix/store/zk52v8kb14nlqhlwn24b2rrg0gi1widb-python3-3.9.4-env/lib/python3.9/site-packages/pulumi/runtime/mo│
cks.py", line 24, in <module>                                                                                          │
        from . import rpc                                                                                              │
      File "/nix/store/zk52v8kb14nlqhlwn24b2rrg0gi1widb-python3-3.9.4-env/lib/python3.9/site-packages/pulumi/runtime/rp│
c.py", line 29, in <module>                                                                                            │
        from . import known_types, settings                                                                            │
      File "/nix/store/zk52v8kb14nlqhlwn24b2rrg0gi1widb-python3-3.9.4-env/lib/python3.9/site-packages/pulumi/runtime/se│
ttings.py", line 22, in <module>                                                                                       │
        import grpc                                                                                                    │
      File "/nix/store/zk52v8kb14nlqhlwn24b2rrg0gi1widb-python3-3.9.4-env/lib/python3.9/site-packages/grpc/__init__.py"│
, line 23, in <module>                                                                                                 │
        from grpc._cython import cygrpc as _cygrpc                                                                     │
    ImportError: /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libc.so.6: version `GLIBC_2.33' not foun│
d (required by /nix/store/lg104nh0szci8slz5z6494m457jm5y3p-gcc-10.3.0-lib/lib/libstdc++.so.6)                          │
    It looks like the Pulumi SDK has not been installed. Have you run pip install?                                     │
    If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv. 
```

**Comment by t0yv0** [comment]
Tracking in https://github.com/pulumi/pulumi/issues/7754

**Comment by mudrii** [comment]
@t0yv0 above error we encountered when using nix-shell using below shell.nix we couldn't replicate the issue running directly under NixOS 21.05 stable

```
{ pkgs ? import <nixpkgs> {} }:
let
  infraDevWorkspaceEnv = pkgs.poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    python = pkgs.python39;
    overrides = pkgs.poetry2nix.overrides.withDefaults (
      self: super: {
        arpeggio = super.arpeggio.overridePythonAttrs (
          old: {
            buildInputs = (old.buildInputs or [ ]) ++ [ self.pytest-runner ];
          }
        );
	    }
    );
    editablePackageSources = {
      infraDevWorkspace = ./.;
    };
  };
in
pkgs.mkShell {
  buildInputs = [ infraDevWorkspaceEnv pkgs.python39Packages.pip ];
}
```

**Comment by mudrii** [comment]
Using nix flakes @junkangli replicating shell.nix seems to work without any issue with the below flake file

```
{
  description = "A flake using poetry2nix";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs";
  inputs.utils.url = "github:numtide/flake-utils";
  inputs.poetry2nix-src.url = "github:nix-community/poetry2nix";

  outputs = {nixpkgs, utils, poetry2nix-src, self}: utils.lib.eachDefaultSystem (system: 
  let
    pkgs = import nixpkgs { inherit system; overlays = [ poetry2nix-src.overlay ]; };

    infraDevWorkspaceEnv = pkgs.poetry2nix.mkPoetryEnv {
      projectDir = ./.;
      python = pkgs.python39;
      overrides = pkgs.poetry2nix.overrides.withDefaults (
        self: super: {
          arpeggio = super.arpeggio.overridePythonAttrs (
            old: {
              buildInputs = (old.buildInputs or [ ]) ++ [ self.pytest-runner ];
            }
          );
        }
      );
      editablePackageSources = {
        infraDevWorkspace = ./.;
      };
    };
  in {
    devShell = pkgs.mkShell {
      buildInputs = [ infraDevWorkspaceEnv pkgs.python39Packages.pip ];
    };
  });
}
```

**Pull request merged**
