### PR TITLE
python3Packages.fsspec: 2021.07.0 -> 2021.08.1, python3Packages.gcsfs: 2021.07.0 -> 2021.08.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 2021.08.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Hold back till the current `staging-next` is available (aiobotocore~=1.4.0).

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 137276` at ccc1ed0b run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.caffe</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-ml</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.streamz</li>
    <li>python39Packages.stumpy</li>
  </ul>
</details>
<details>
  <summary>45 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/04ece3938ef55f46ec562a6bc907611b">python38Packages.aplpy</a></li>
    <li><a href="https://gist.github.com/1a9078f12324447a6a049dc2ec3cbfb8">python38Packages.asdf</a></li>
    <li><a href="https://gist.github.com/f2d7d6174c4ab01969be4a8565208376">python38Packages.batchgenerators</a></li>
    <li><a href="https://gist.github.com/5c10d813a037a979742daa3b49e71f77">python38Packages.dask</a></li>
    <li><a href="https://gist.github.com/bd51c29099ce43a43364e317177027b5">python38Packages.dask-image</a></li>
    <li><a href="https://gist.github.com/f82cc30882fee252934cd9f3efcd161e">python38Packages.glymur</a></li>
    <li><a href="https://gist.github.com/8b1b684882ad841db1767439b2ef96b5">python38Packages.image-match</a></li>
    <li><a href="https://gist.github.com/bb67e50062f2954b0ed11b52b90087ee">python38Packages.imagecorruptions</a></li>
    <li><a href="https://gist.github.com/3acf9befbe0e518054c86048e146a231">python38Packages.imgaug</a></li>
    <li><a href="https://gist.github.com/6ddecfefcc302058b0d9e8cf3cd10186">python38Packages.pims</a></li>
    <li><a href="https://gist.github.com/a9910b88856c7018f7396e0a29e9da5b">python38Packages.pyfftw</a></li>
    <li><a href="https://gist.github.com/c5eb5110b05d46598954f048c29fa980">python38Packages.pyregion</a></li>
    <li><a href="https://gist.github.com/8fb48f24a7c34892f9f723beba7b3e62">python38Packages.pytest-astropy</a></li>
    <li><a href="https://gist.github.com/11ad378b093b588858df9b6ce68493e9">python38Packages.pytest-astropy-header</a></li>
    <li><a href="https://gist.github.com/5a588577384b75d2a691998cd54c1302">python38Packages.reproject</a></li>
    <li><a href="https://gist.github.com/ae2b4f19e276d168e79086135e9a1f75">python38Packages.s3fs</a></li>
    <li><a href="https://gist.github.com/bcedfb819c2e19fcc94fee49270405bd">python38Packages.scikitimage</a></li>
    <li><a href="https://gist.github.com/d5771f35253da431594df8b11c8adeee">python38Packages.slicedimage</a></li>
    <li><a href="https://gist.github.com/7b757d8209b9d24a56407927aa88e01c">python38Packages.sparse</a></li>
    <li><a href="https://gist.github.com/ce69ec777db763d626fb5d505bc978e8">python38Packages.stytra</a></li>
    <li><a href="https://gist.github.com/69904f8db552c3a31ca57c52c6c5e5e4">python38Packages.sunpy</a></li>
    <li><a href="https://gist.github.com/403ee339f21c1d587cf2e1e41beff1c4">python38Packages.tensorly</a></li>
    <li><a href="https://gist.github.com/00caffeb0d1ca387e71b1878f6de2c52">python39Packages.aplpy</a></li>
    <li><a href="https://gist.github.com/de46847a0b90dd3bb3fa4c2d00886174">python39Packages.asdf</a></li>
    <li><a href="https://gist.github.com/e91d5d2ce839c33dea595a407e8514ea">python39Packages.batchgenerators</a></li>
    <li><a href="https://gist.github.com/7f85316d2414f820c67d9d9b8a8a064a">python39Packages.dask</a></li>
    <li><a href="https://gist.github.com/6604d349afc40b01e7c29c94598d78b2">python39Packages.dask-image</a></li>
    <li><a href="https://gist.github.com/1ac2dce128eed0eded34d084ea0abcaf">python39Packages.glymur</a></li>
    <li><a href="https://gist.github.com/6d98e9f58da901e0a266b70433079e6f">python39Packages.image-match</a></li>
    <li><a href="https://gist.github.com/b93da1107394e52fe17c5821ff1175cc">python39Packages.imagecorruptions</a></li>
    <li><a href="https://gist.github.com/cd0236ae6eba1198dca4d61f14db1d9d">python39Packages.imgaug</a></li>
    <li><a href="https://gist.github.com/4258015f31d520caabeb023d43d55c03">python39Packages.intake</a></li>
    <li><a href="https://gist.github.com/44647057b745e5ab6f7b2803dd33b89c">python39Packages.pims</a></li>
    <li><a href="https://gist.github.com/0af5d7580f2ac3f7e0797bbfc3489afb">python39Packages.pyfftw</a></li>
    <li><a href="https://gist.github.com/31d091d19f0ef77fac0540aaa2aa1a20">python39Packages.pyregion</a></li>
    <li><a href="https://gist.github.com/a71708c23fb100baac24c356e648ff39">python39Packages.pytest-astropy</a></li>
    <li><a href="https://gist.github.com/3741eee17ee4c2a44e43704e8c8d9392">python39Packages.pytest-astropy-header</a></li>
    <li><a href="https://gist.github.com/07753cdc561fb76bbc1e06f63585e27a">python39Packages.reproject</a></li>
    <li><a href="https://gist.github.com/7f05f6174b712343d4e01076ada4b77a">python39Packages.s3fs</a></li>
    <li><a href="https://gist.github.com/9fa26c46d832818cc4f1d9320019e68e">python39Packages.scikitimage</a></li>
    <li><a href="https://gist.github.com/4e994b6d3142e5cf28f71272c0e8ef40">python39Packages.slicedimage</a></li>
    <li><a href="https://gist.github.com/714797682f5e4c735fa59dd255e29a28">python39Packages.sparse</a></li>
    <li><a href="https://gist.github.com/8fb58fe0328ddd98ceb971f55c111344">python39Packages.stytra</a></li>
    <li><a href="https://gist.github.com/17f2b07e7e97a8fe99bb697a655984f2">python39Packages.sunpy</a></li>
    <li><a href="https://gist.github.com/2772014c55ab89f482c528d48b70f54a">python39Packages.tensorly</a></li>
  </ul>
</details>
<details>
  <summary>12 packages skipped due to time constraints:</summary>
  <ul>
    <li>python38Packages.clifford</li>
    <li>python38Packages.dask-glm</li>
    <li>python38Packages.intake</li>
    <li>python38Packages.mask-rcnn</li>
    <li>python38Packages.rl-coach</li>
    <li>python38Packages.spectral-cube</li>
    <li>python39Packages.clifford</li>
    <li>python39Packages.dask-glm</li>
    <li>python39Packages.mask-rcnn</li>
    <li>python39Packages.rl-coach</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>12 packages built successfully:</summary>
  <ul>
    <li>python38Packages.datasets</li>
    <li>python38Packages.fastparquet</li>
    <li>python38Packages.fsspec</li>
    <li>python38Packages.gcsfs</li>
    <li>python38Packages.tokenizers</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.fastparquet</li>
    <li>python39Packages.fsspec</li>
    <li>python39Packages.gcsfs</li>
    <li>python39Packages.tokenizers</li>
    <li>python39Packages.transformers</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 137276` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.clifford</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.rl-coach</li>
    <li>python39Packages.clifford</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.rl-coach</li>
  </ul>
</details>
<details>
  <summary>70 packages failed to build:</summary>
  <ul>
    <li>python38Packages.aplpy</li>
    <li>python38Packages.asdf</li>
    <li>python38Packages.batchgenerators</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.dask</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-glm</li>
    <li>python38Packages.dask-image</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.distributed</li>
    <li>python38Packages.gcsfs</li>
    <li>python38Packages.glymur</li>
    <li>python38Packages.image-match</li>
    <li>python38Packages.imagecorruptions</li>
    <li>python38Packages.imgaug</li>
    <li>python38Packages.intake</li>
    <li>python38Packages.mask-rcnn</li>
    <li>python38Packages.pims</li>
    <li>python38Packages.pyfftw</li>
    <li>python38Packages.pyregion</li>
    <li>python38Packages.pytest-astropy</li>
    <li>python38Packages.pytest-astropy-header</li>
    <li>python38Packages.reproject</li>
    <li>python38Packages.scikitimage</li>
    <li>python38Packages.slicedimage</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.sparse</li>
    <li>python38Packages.spectral-cube</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.stytra</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.tensorly</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.asdf</li>
    <li>python39Packages.batchgenerators</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.dask</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-glm</li>
    <li>python39Packages.dask-image</li>
    <li>python39Packages.dask-ml</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.distributed</li>
    <li>python39Packages.gcsfs</li>
    <li>python39Packages.glymur</li>
    <li>python39Packages.image-match</li>
    <li>python39Packages.imagecorruptions</li>
    <li>python39Packages.imgaug</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.mask-rcnn</li>
    <li>python39Packages.pims</li>
    <li>python39Packages.pyfftw</li>
    <li>python39Packages.pyregion</li>
    <li>python39Packages.pytest-astropy</li>
    <li>python39Packages.pytest-astropy-header</li>
    <li>python39Packages.reproject</li>
    <li>python39Packages.scikitimage</li>
    <li>python39Packages.slicedimage</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.sparse</li>
    <li>python39Packages.spectral-cube</li>
    <li>python39Packages.streamz</li>
    <li>python39Packages.stumpy</li>
    <li>python39Packages.stytra</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.tensorly</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>python38Packages.datasets</li>
    <li>python38Packages.fastparquet</li>
    <li>python38Packages.fsspec</li>
    <li>python38Packages.s3fs</li>
    <li>python38Packages.tokenizers</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.fastparquet</li>
    <li>python39Packages.fsspec</li>
    <li>python39Packages.s3fs</li>
    <li>python39Packages.tokenizers</li>
    <li>python39Packages.transformers</li>
    <li>tts</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 137276` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.clifford</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.rl-coach</li>
    <li>python39Packages.clifford</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.rl-coach</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>python38Packages.gcsfs</li>
    <li>python38Packages.intake</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.streamz</li>
    <li>python39Packages.gcsfs</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.spacy-transformers</li>
  </ul>
</details>
<details>
  <summary>76 packages built:</summary>
  <ul>
    <li>python38Packages.aplpy</li>
    <li>python38Packages.asdf</li>
    <li>python38Packages.batchgenerators</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.dask</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-glm</li>
    <li>python38Packages.dask-image</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.distributed</li>
    <li>python38Packages.fastparquet</li>
    <li>python38Packages.fsspec</li>
    <li>python38Packages.glymur</li>
    <li>python38Packages.image-match</li>
    <li>python38Packages.imagecorruptions</li>
    <li>python38Packages.imgaug</li>
    <li>python38Packages.mask-rcnn</li>
    <li>python38Packages.pims</li>
    <li>python38Packages.pyfftw</li>
    <li>python38Packages.pyregion</li>
    <li>python38Packages.pytest-astropy</li>
    <li>python38Packages.pytest-astropy-header</li>
    <li>python38Packages.reproject</li>
    <li>python38Packages.s3fs</li>
    <li>python38Packages.scikitimage</li>
    <li>python38Packages.slicedimage</li>
    <li>python38Packages.sparse</li>
    <li>python38Packages.spectral-cube</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.stytra</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.tensorly</li>
    <li>python38Packages.tokenizers</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.asdf</li>
    <li>python39Packages.batchgenerators</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.dask</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-glm</li>
    <li>python39Packages.dask-image</li>
    <li>python39Packages.dask-ml</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.distributed</li>
    <li>python39Packages.fastparquet</li>
    <li>python39Packages.fsspec</li>
    <li>python39Packages.glymur</li>
    <li>python39Packages.image-match</li>
    <li>python39Packages.imagecorruptions</li>
    <li>python39Packages.imgaug</li>
    <li>python39Packages.mask-rcnn</li>
    <li>python39Packages.pims</li>
    <li>python39Packages.pyfftw</li>
    <li>python39Packages.pyregion</li>
    <li>python39Packages.pytest-astropy</li>
    <li>python39Packages.pytest-astropy-header</li>
    <li>python39Packages.reproject</li>
    <li>python39Packages.s3fs</li>
    <li>python39Packages.scikitimage</li>
    <li>python39Packages.slicedimage</li>
    <li>python39Packages.sparse</li>
    <li>python39Packages.spectral-cube</li>
    <li>python39Packages.streamz</li>
    <li>python39Packages.stumpy</li>
    <li>python39Packages.stytra</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.tensorly</li>
    <li>python39Packages.tokenizers</li>
    <li>python39Packages.transformers</li>
    <li>tts</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 137276` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.clifford</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.rl-coach</li>
    <li>python39Packages.clifford</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.rl-coach</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>python38Packages.intake</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.streamz</li>
  </ul>
</details>
<details>
  <summary>80 packages built:</summary>
  <ul>
    <li>intensity-normalization (python39Packages.intensity-normalization)</li>
    <li>python38Packages.aplpy</li>
    <li>python38Packages.asdf</li>
    <li>python38Packages.batchgenerators</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.dask</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-glm</li>
    <li>python38Packages.dask-image</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.distributed</li>
    <li>python38Packages.fastparquet</li>
    <li>python38Packages.fsspec</li>
    <li>python38Packages.gcsfs</li>
    <li>python38Packages.glymur</li>
    <li>python38Packages.image-match</li>
    <li>python38Packages.imagecorruptions</li>
    <li>python38Packages.imgaug</li>
    <li>python38Packages.intensity-normalization</li>
    <li>python38Packages.mask-rcnn</li>
    <li>python38Packages.pims</li>
    <li>python38Packages.pyfftw</li>
    <li>python38Packages.pyregion</li>
    <li>python38Packages.pytest-astropy</li>
    <li>python38Packages.pytest-astropy-header</li>
    <li>python38Packages.reproject</li>
    <li>python38Packages.s3fs</li>
    <li>python38Packages.scikitimage</li>
    <li>python38Packages.slicedimage</li>
    <li>python38Packages.sparse</li>
    <li>python38Packages.spectral-cube</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.stytra</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.tensorly</li>
    <li>python38Packages.tokenizers</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.asdf</li>
    <li>python39Packages.batchgenerators</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.dask</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-glm</li>
    <li>python39Packages.dask-image</li>
    <li>python39Packages.dask-ml</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.distributed</li>
    <li>python39Packages.fastparquet</li>
    <li>python39Packages.fsspec</li>
    <li>python39Packages.gcsfs</li>
    <li>python39Packages.glymur</li>
    <li>python39Packages.image-match</li>
    <li>python39Packages.imagecorruptions</li>
    <li>python39Packages.imgaug</li>
    <li>python39Packages.mask-rcnn</li>
    <li>python39Packages.pims</li>
    <li>python39Packages.pyfftw</li>
    <li>python39Packages.pyregion</li>
    <li>python39Packages.pytest-astropy</li>
    <li>python39Packages.pytest-astropy-header</li>
    <li>python39Packages.reproject</li>
    <li>python39Packages.s3fs</li>
    <li>python39Packages.scikitimage</li>
    <li>python39Packages.slicedimage</li>
    <li>python39Packages.sparse</li>
    <li>python39Packages.spectral-cube</li>
    <li>python39Packages.stumpy</li>
    <li>python39Packages.stytra</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.tensorly</li>
    <li>python39Packages.tokenizers</li>
    <li>python39Packages.transformers</li>
    <li>tts</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 137276` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.clifford</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.rl-coach</li>
    <li>python39Packages.clifford</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.rl-coach</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python38Packages.spacy-transformers</li>
    <li>python39Packages.spacy-transformers</li>
  </ul>
</details>
<details>
  <summary>90 packages built:</summary>
  <ul>
    <li>intensity-normalization (python39Packages.intensity-normalization)</li>
    <li>python38Packages.aplpy</li>
    <li>python38Packages.asdf</li>
    <li>python38Packages.batchgenerators</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.dask</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-glm</li>
    <li>python38Packages.dask-image</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.distributed</li>
    <li>python38Packages.fastparquet</li>
    <li>python38Packages.fsspec</li>
    <li>python38Packages.gcsfs</li>
    <li>python38Packages.glymur</li>
    <li>python38Packages.image-match</li>
    <li>python38Packages.imagecorruptions</li>
    <li>python38Packages.imgaug</li>
    <li>python38Packages.intake</li>
    <li>python38Packages.intake-parquet</li>
    <li>python38Packages.intensity-normalization</li>
    <li>python38Packages.mask-rcnn</li>
    <li>python38Packages.parquet</li>
    <li>python38Packages.pims</li>
    <li>python38Packages.pyfftw</li>
    <li>python38Packages.pyregion</li>
    <li>python38Packages.pytest-astropy</li>
    <li>python38Packages.pytest-astropy-header</li>
    <li>python38Packages.reproject</li>
    <li>python38Packages.s3fs</li>
    <li>python38Packages.scikitimage</li>
    <li>python38Packages.slicedimage</li>
    <li>python38Packages.sparse</li>
    <li>python38Packages.spectral-cube</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.stytra</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.tensorly</li>
    <li>python38Packages.thriftpy2</li>
    <li>python38Packages.tokenizers</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.asdf</li>
    <li>python39Packages.batchgenerators</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.dask</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-glm</li>
    <li>python39Packages.dask-image</li>
    <li>python39Packages.dask-ml</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.distributed</li>
    <li>python39Packages.fastparquet</li>
    <li>python39Packages.fsspec</li>
    <li>python39Packages.gcsfs</li>
    <li>python39Packages.glymur</li>
    <li>python39Packages.image-match</li>
    <li>python39Packages.imagecorruptions</li>
    <li>python39Packages.imgaug</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.intake-parquet</li>
    <li>python39Packages.mask-rcnn</li>
    <li>python39Packages.parquet</li>
    <li>python39Packages.pims</li>
    <li>python39Packages.pyfftw</li>
    <li>python39Packages.pyregion</li>
    <li>python39Packages.pytest-astropy</li>
    <li>python39Packages.pytest-astropy-header</li>
    <li>python39Packages.reproject</li>
    <li>python39Packages.s3fs</li>
    <li>python39Packages.scikitimage</li>
    <li>python39Packages.slicedimage</li>
    <li>python39Packages.sparse</li>
    <li>python39Packages.spectral-cube</li>
    <li>python39Packages.streamz</li>
    <li>python39Packages.stumpy</li>
    <li>python39Packages.stytra</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.tensorly</li>
    <li>python39Packages.thriftpy2</li>
    <li>python39Packages.tokenizers</li>
    <li>python39Packages.transformers</li>
    <li>tts</li>
    <li>wavemon</li>
  </ul>
</details>

**Pull request merged**
