### PR TITLE
calibre: make unrar support optional, and bump to latest version

### PR DESCRIPTION
**Pull request by gebner**
As discussed  in #12091, even though the calibre derivation says it is GPLv3, the calibre package contains and builds its own copy of the non-free unrar library.

This PR makes the unrar feature optional.
- If unrarSupport is false (the default), then unrar support is removed [with the same patch that Debian applies](http://sources.debian.net/patches/patch/calibre/2.45.0%2Bdfsg-1/dont_build_unrar_plugin.patch/).  In this case calibre's license is set to gpl3.
- If unrarSupport is true, then calibre is built normally, but the license attribute is set to unfreeRedistributable.

cc @nckx and maintainers @viric @domenkozar @pSub @AndersonTorres

### CODE REVIEW

**Comment by nckx** [comment]
It would be nice if someone could convince upstream to make something this significant properly optional. I'm surprised Debian hasn't. Until then, and assuming you've tested both cases, this patch looks perfect.

(Thanks for not squashing, by the way.)

**Comment by vcunat** [comment]
For the case with `unrarSupport = true`, why not use our unrar instead of the bundled one? (Maybe there *are* good reasons &ndash; I just don't know.)

**Comment by gebner** [comment]
@nckx I have tested both version and they work fine (one can read rar files, the other can't).

@vcunat Calibre links directly to the unrar *library*, and does not use the executable. At the moment, we don't package the unrar library (it's just a `make lib` away though).  But then you'd need to patch calibre even more (it builds unrar together with a python module).  It's doable, but seems a lot of work for a configuration that we do not have as a default, and that upstream is even less likely to support.  However this might make more sense if we find a free replacement for unrar.

**Comment by vcunat** [comment]
Yes, those do sound as good reasons to keep the bundled one.

**Comment by pSub** [comment]
@gebner Thank you!

**Pull request merged**
