### PR TITLE
libomxil-bellagio: Fix -Wstringop-truncation error

### PR DESCRIPTION
**Pull request by dramforever**
Fixes cross on riscv64-linux

*Draft to facilitate testing*

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dramforever** [comment]
Ugh, that's a lot of rebuilds... Should I just include it for some platforms only?

**Comment by SuperSandro2000** [comment]
Why is this only a problem ob riscv SMS not other platforms?

It is better to make patches platform independent otherwise they might be forgotten to be relebased.

**Comment by dramforever** [comment]
Right, after making sure it works I took another look this probably should be a `-Wno` flag like the others already present here.

I still haven't figured out why this is only a problem on riscv64. That's *really* weird.

**Comment by skeuchel** [comment]
This happens on native riscv64 as well
```
gcc -DHAVE_CONFIG_H -I. -I..    -DOMXILCOMPONENTSPATH=\"/nix/store/31dw2698xkdahh0afj0y8m2axkh9f7dh-libomxil-bellagio-0.9.3/lib/bellagio/\" -I../include -Wall -Werror -DCONFIG_DEBUG_LEVEL=0 >
In file included from /nix/store/1d972flg91c7xq21027nvkx2x05ga89b-glibc-2.35-224-dev/include/string.h:535,
                 from omxregister.c:42:
In function 'strncpy',
    inlined from 'showComponentsList' at omxregister.c:110:3,
    inlined from 'main' at omxregister.c:463:9:
/nix/store/1d972flg91c7xq21027nvkx2x05ga89b-glibc-2.35-224-dev/include/bits/string_fortified.h:95:10: error: '__builtin_strncpy' destination unchanged after copying no bytes [-Werror=stringo>
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
For reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1028978

**Comment by dramforever** [comment]
Thanks for the test and reference. Seems it affects a few other non-x86 systems as well. I'll test a bit more and clarify the commit message.

Still I'm unconvinced that a code patch would be better than just un-`-Werror`ing the warning though.

**Comment by skeuchel** [comment]
I've looped over the platforms in `nixpkgs#pkgsCross`. This specific build failure happens in `m68k mips64el-linux-gnuabi64 mipsel-linux-gnu musl-power powernv ppc64 ppc64-musl riscv32 riscv64 s390 s390x`, and the warning doesn't appear for arm and x86 platforms.

I've looked at the header file, and the `strncpy` can't figure out why the warning is thrown and why there would be a difference for platforms. The Debian bug reporter said as much.

Since this change causes a lot of rebuilds you should target the staging branch.
`

**Pull request merged**
