### PR TITLE
hypothesis-python: 3.11.1 -> 3.27.0

### PR DESCRIPTION
**Pull request by va1entin**
###### Motivation for this change
I wanted to update PyNaCl in Nixpkgs, but it's tests require this version of hypothesis. I chose 3.27.0 because that's the earliest one with the features needed by pynacl.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md). - no maintainer, fits otherwise

---

### CODE REVIEW

**Comment by Mic92** [comment]
This PR should go to the `staging` branch first rather then `master` since it rebuilds many packages.

**Comment by va1entin** [comment]
Thanks @Mic92 
I changed the base branch to staging

**Comment by FRidh** [comment]
This change can be merged in a later batch after a Hydra job to check whether builds still succeed.

**Comment by FRidh** [comment]
I've included the changes in https://github.com/NixOS/nixpkgs/pull/34077.

**Pull request closed without merging**
