### PR TITLE
nixos/nix: allow specifying a protocol for a remote-builder when using `pkgs.nixUnstable`

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

When using `nixUnstable` by default, it's possible to specify a protocol for a build-machine (e.g. `ssh-ng`). This PR adds support for that and ensures that this only happens if Nix>=3.0 is used as `nixStable` doesn't support this.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Now checking against Nix 2.4 after https://github.com/NixOS/nix/commit/ac0e24f21b162f99c8e9437c710797820345a7a2 

@edolstra do you think this is good to go then?

**Comment by edolstra** [comment]
Instead of adding a `protocol` field, it might be better to add a `storeURL` field or something like that (as an alternative to `hostName`), to be fully general. Some remote builder protocols might not have a hostname (e.g. IIRC the AWS builder takes an SQS queue name).

**Comment by Ma27** [comment]
@edolstra could you give me an example for that? I'm not sure if that's really a better idea though as this would conflict with things like `sshUser` as well (which means that if you need to specify an alternative protocol for a machine, you'd have to change the full URL).

**Comment by edolstra** [comment]
An example is chroot stores in NixOS containers where `/nix/store` is not writable. In that case the store URL is just a path.

`sshUser` and `sshKey` are obsolete when you specify a full store URL since you can just include them in the URL (e.g. `ssh://user@example.org?ssh-key=/path`).

**Comment by Ma27** [comment]
Just realized that I wrongly assumed that specifying a protocol is only possible on `nixUnstable`. In fact it's sufficient to set `hostName` to e.g. `ssh-ng://hostname`, hence this change isn't needed. Sorry for that, will close it now.

**Pull request closed without merging**
