### PR TITLE
musescore: 4.1.1 -> 4.2.0

### PR DESCRIPTION
**Pull request by schuelermine**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by OmnipotentEntity — APPROVED** [review]
Diff looks good.  Build and launches, opened a test file and it seems to function.  I do have glitchy black borders around the menu drop downs where shadowing ought to be, but I have those in 4.1.1 as well.

**Comment by doronbehar** [comment]
There is a problem with `nixosTests.musescore`. I'm debugging it now. Besides that diff LGTM and CI is green for all other platforms.

**Comment by huantianad** [comment]
We haven't had any further progress with using system libraries since 4.1.1 right?

**Comment by doronbehar** [comment]
> We haven't had any further progress with using system libraries since 4.1.1 right? Otherwise, seems to run fine for me.

I had progress with some of the bundled libraries, and I suggested a PR upstream at:

https://github.com/musescore/MuseScore/pull/19795

However, upstream doesn't seem to care much about it... Do we want to pull my patch to our distribution? I'm not sure... I will note I tested my patch with the Nixpkgs build.

I'm still fighting in fixing the nixosTest... It's a matter of hitting the right keys inside the VM.

**Comment by doronbehar** [comment]
Fixed `nixosTests.musescore`. Besides the dilemma with https://github.com/musescore/MuseScore/pull/19795 , this should be good to go.

**Comment by doronbehar** [comment]
Upstream seems responsive now regarding my system libraries PR. I assume they'll give an extensive review. Let's merge this in the meantime.

**Pull request merged**
