### PR TITLE
unbound 1.5.10 -> 1.6.0

### PR DESCRIPTION
**Pull request by dbalan**
###### Motivation for this change
New release

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
(Rebuild impact is nontrivial due to being a dependency of gnutls; github now shows a few extra commits from master.)

**Comment by joachifm** [comment]
As I recall, it has to do with gnutls using unbound for DANE support, is that something people actually use?

**Comment by vcunat** [comment]
I don't know; I would personally be inclined to push people towards DANE a bit, but I probably can't be really objective.

**Comment by vcunat** [comment]
It does seem probable that noone uses `libgnutls-dane` in nixpkgs yet, even though we're providing it for a long time already.

**Comment by leenaars** [comment]
We use that, with quite some stuff that is on its way ;)

**Comment by leenaars** [comment]
And like @vcunat says: it is the Right Thing for people. Having it in nixpkgs makes it available everywhere fast.

**Comment by vcunat** [comment]
Currently this leads to a surprising dependency of gnutls on openssl :-) libgnutls-dane.so -> libunbound.so -> libssl.so

**Comment by vcunat** [comment]
It will probably be preferable to switch unbound directly to nettle instead of gnutls, especially as gnutls does depend on nettle anyway.  Debian [has done that](https://packages.debian.org/stretch/libunbound2) in testing already.

**Comment by vcunat** [comment]
Ugh, well, it's not so easy as I imagined. The library would probably have to be built separately, and whole unbound seemingly needs more than nettle (libssl.so again on Debian).

**Comment by vcunat** [comment]
It turned out to be not too complicated: https://github.com/NixOS/nixpkgs/pull/23245.

**Pull request merged**
