### PR TITLE
nixos/ipu6: Don't build out-of-tree driver for kernels that have it

### PR DESCRIPTION
**Pull request by shlevy**
## Description of changes

The ipu6 drivers are in-tree as of Linux 6.10, so we can stop building them for newer kernels

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by shlevy** [comment]
@flokli Done

**Comment by flokli** [comment]
@shlevy I was just about to test this out, but unfortunately `v4l2-relayd-ipu6.service` doesn't seem to come up again:

```

× v4l2-relayd-ipu6.service - Streaming relay for v4l2loopback using GStreamer
     Loaded: loaded (/etc/systemd/system/v4l2-relayd-ipu6.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-08-04 16:25:50 EEST; 1min 58s ago
 Invocation: 0e2c6407e7fb490b964a120dc6c3215a
    Process: 69115 ExecStartPre=/nix/store/qhbqvknp0b1a330f4kbkjnq3smij1hbb-unit-script-v4l2-relayd-ipu6-pre-start/bin/v4l2-relayd-ipu6-pre-start (code=exited, status=1/FAILURE)
    Process: 69126 ExecStopPost=/nix/store/zv3qyvvkv82a9dg59261yjzm2c8jrr3i-unit-script-v4l2-relayd-ipu6-post-stop/bin/v4l2-relayd-ipu6-post-stop (code=exited, status=1/FAILURE)

Aug 04 16:25:50 x1 systemd[1]: v4l2-relayd-ipu6.service: Scheduled restart job, restart counter is at 5.
Aug 04 16:25:50 x1 systemd[1]: v4l2-relayd-ipu6.service: Start request repeated too quickly.
Aug 04 16:25:50 x1 systemd[1]: v4l2-relayd-ipu6.service: Failed with result 'exit-code'.
Aug 04 16:25:50 x1 systemd[1]: Failed to start Streaming relay for v4l2loopback using GStreamer.
```

Looking at the logs, maybe the naming did change, or this is otherwise incompatible? How do I test this?

**Comment by matejc** [comment]
For me it fails with:
```
Aug 13 16:10:15 nixcode v4l2-relayd-ipu6-pre-start[15383]: failed to create device: Inappropriate ioctl for device
```
when pre-start is doing:
```shell
v4l2loopback-ctl add -x 1 ....
```

I can also confirm that this produces the same error:
```shell
sudo v4l2loopback-ctl add
```

I have tried to unload and load the v4l2loopback the module and still same issue. Other observations: I do have /dev/video0 to /dev/video32 and all in between for some reason. Also... I am running on kernel 6.10.3

**Comment by matejc** [comment]
We might need to update v4l2loopback https://github.com/umlaeute/v4l2loopback/tags
Our one is 12.7 which is two years back and there has been 3 versions released since then

**Comment by flokli** [comment]
Sent a bump for v4l2loopback https://github.com/NixOS/nixpkgs/pull/334573.

With this, at least the service doesn't crash anymore. If I select the loopback device in the browser, I see the following in the logs:

```
Aug 14 12:06:41 x1 pipewire[3035]: spa.v4l2: '/dev/video0' VIDIOC_REQBUFS Invalid argument
Aug 14 12:06:41 x1 pipewire[3035]: pw.port: 0x55625008def0: negotiate buffers on node: -22 (Invalid argument)
Aug 14 12:06:41 x1 pipewire[3035]: pw.port: 0x55625008def0: state ready -> error (can't negotiate buffers on port)
Aug 14 12:06:41 x1 pipewire[3035]: pw.link: (195.0.0 -> 351.0.0) allocating -> error (can't negotiate buffers on port) (error-ready)
```

The camera still doesn't work, but it feels like a step into the right direction.

**Pull request merged**
