### PR TITLE
gnome.gnome-settings-daemon338: fix build with meson 0.61

### PR DESCRIPTION
**Pull request by bobby285271**
###### Description of changes

This was forgotten during #154837

###### Things done

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build gnome.gnome-calendar gnome.gnome-bluetooth gnome.dconf-editor gnome.devhelp gnome.gitg

**Comment by bobby285271** [comment]
@ofborg build gnome.gnome-boxes gnome.aisleriot gnome.gnome-dictionary gnome.gnome-mahjongg gnome.gnome-music gnome.gnome-notes

**Comment by NickCao** [comment]
Wow that's a lot of breakage! But GNOME 42 should be released in several days, would it be better to wait for it? By several days I mean like 3/19 for the release tarball.

**Comment by bobby285271** [comment]
I am not sure whether the GNOME 42 bump can be merged before the meson bump :crying_cat_face:

**Comment by NickCao** [comment]
The current staging next still need a few days to stabilize, and the next one is also a big one with systemd 250, we would sure have enough time to sort everything out before it hits master.

**Comment by jtojnar** [comment]
Wow, you have done quite a loot of good work here, the changes look good.

Personally, I would be too lazy for that and just revert the Meson strictness until GNOME 42 is available.

**Comment by bobby285271** [comment]
> Personally, I would be too lazy for that and just revert the Meson commit that adds strictness until GNOME 42 is available.

Sounds good. I updated this PR to include only one fix for gsd338, which is definitely not going to have any new release.

**Comment by bobby285271** [comment]
@ofborg build gnome.gnome-settings-daemon338
@ofborg test pantheon

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 164266` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>gnome.gnome-settings-daemon338 (pantheon.gnome-settings-daemon)</li>
    <li>monitor</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-bluetooth</li>
    <li>pantheon.switchboard-plug-keyboard</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>wingpanel-indicator-ayatana</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
I am trying to build gnome-bluetooth against meson with this annotation removed to see if it serves as a workaround: https://github.com/mesonbuild/meson/blob/1be444b4647214dbd9a43084ffbf01ef95a78287/mesonbuild/modules/i18n.py#L154

**Comment by bobby285271** [comment]
Yeah this is what was done in https://github.com/mesonbuild/meson/pull/9445

**Comment by bobby285271** [comment]
https://github.com/mesonbuild/meson/pull/9445/commits/022c0357ae4cd6c1d7e9a0f3a2672ba410a71fa2 applies for me and built gnome.gnome-settings-daemon338 without the fix in this PR (I have a separate `meson_0_61` package in my local branch).

**Comment by jtojnar** [comment]
Oh, nice, that might be even better.

**Comment by bobby285271** [comment]
I decided I will still merge this in a few hours unless objections. Pantheon 7 is not likely going to happen in NixOS 22.05 and I really have no idea when we can get rid of mutter338/gsd338 (https://github.com/elementary/gala/issues/1326) and https://github.com/mesonbuild/meson/commit/022c0357ae4cd6c1d7e9a0f3a2672ba410a71fa2 eventually has to be removed from the patch set. :sweat:

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
