### PR TITLE
KDE PIM Applications

### PR DESCRIPTION
**Pull request by ttuegel**
### Motivation

This adds the KDE PIM applications suite to Nixpkgs.

### Checklist

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

All credit here goes to @vandenoever; the only thing I actually contributed to this work is some housekeeping and finding one or two patches from upstream.

### CODE REVIEW

**Comment by ttuegel** [comment]
I am currently debugging a bad rebase. (Oops!)

The update to KDE Frameworks 5.34 and Applications 17.04.2 also introduced non-trivial changes in the dependencies of certain packages, so I have to debug that also.

**Comment by vandenoever** [comment]
Please let me know when rebase is done so I can test. I assume this should be tested on NixOS unstable.

**Comment by ttuegel** [comment]
@vandenoever This is ready for testing now. I am running it without any ill effects.

**Comment by vandenoever** [comment]
akonadi fails to build:
```
CMake Error at /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SharedMimeInfo (missing: UPDATE_MIME_DATABASE_EXECUTABLE)
  (Required is at least version "0.20")
Call Stack (most recent call first):
  /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/yk2v9qp15989i9pnb7bmik9y3fbly8kk-extra-cmake-modules-5.34.0/share/ECM/find-modules/FindSharedMimeInfo.cmake:74 (find_package_handle_standard_args)
  CMakeLists.txt:108 (find_package)
```

**Comment by ttuegel** [comment]
That's weird, because it's running for me... I had that error earlier due to the bad rebase, but I fixed it... I don't know what's going on, so I'm going to close this pull request and try again.

**Comment by vandenoever** [comment]
For what it's worth, i was using your unadulterated branch with the unstable nixos channel.

**Pull request closed without merging**
