### PR TITLE
python3.pkgs.tensorboardx: 2.5.1 -> 2.6.2

### PR DESCRIPTION
**Pull request by tjni**
## Description of changes

https://pypi.org/project/tensorboardX/

Cleans up a number of patches I added that have now been accepted upstream.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bcdarwin** [comment]
Essentially a duplicate of #248371.

**Comment by tjni** [comment]
I'm sorry I missed that! I'll merge in your changes to meta.

**Comment by bcdarwin** [comment]
Result of `nixpkgs-review` on x86_64 Linux:

```
4 packages marked as broken and skipped:
piper-train piper-train.dist python311Packages.elegy python311Packages.elegy.dist

2 packages failed to build:
python310Packages.elegy python310Packages.elegy.dist

8 packages built:
python310Packages.pytorch-lightning python310Packages.pytorch-lightning.dist python310Packages.tensorboardx python310Packages.tensorboardx.dist python311Packages.pytorch-lightning python311Packages.pytorch-lightning.dist python311Packages.tensorboardx python311Packages.tensorboardx.dist
```

`elegy` is failing because its dependencies are broken, unrelated to this PR.

**Review by bcdarwin — APPROVED** [review]
Diff LGTM.

**Comment by natsukium** [comment]
@ofborg build python310Packages.tensorboardx python311Packages.tensorboardx

**Review by natsukium — APPROVED** [review]
LGTM, thanks everyone!

**Pull request merged**
