### PR TITLE
nixos xfce: fix eval by avoiding package alias

### PR DESCRIPTION
**Pull request by vcunat**
Regressed in cecb014d5d from PR #170952

(no rebuilds)

### CODE REVIEW

**Comment by vcunat** [comment]
Ah, I didn't _really_ read through the context there.

**Comment by SuperSandro2000** [comment]
> I would rather just revert the rename until we have time to discuss that, see [#170952 (comment)](https://github.com/NixOS/nixpkgs/pull/170952#discussion_r862346215).

It fits all the other networkmanager plugins and it does not really matter that it is technically another project, it's just confusing if it uses a different naming scheme.

---

Naming discussions can take forever, so my call is to fix eval right now and later decide how to name networkmanager things. At least right now it is more consistent than before.

**Comment by jtojnar** [comment]
> It fits all the other networkmanager plugins and it does not really matter that it is technically another project, it's just confusing if it uses a different naming scheme.

IMO it is more confusing when the upstream project name is different from the package name.

> Naming discussions can take forever, so my call is to fix eval right now and later decide how to name networkmanager things.

Right, which is why I suggested revert so that the discussion can happen at their own pace.

**Comment by jtojnar** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/171578

**Comment by SuperSandro2000** [comment]
Merged your PR.

**Pull request closed without merging**
