### PR TITLE
shellify: init at 0.10.0.3

### PR DESCRIPTION
**Pull request by danielrolls**
## Description of changes

Add new package shellify. 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Please change your commit message(s) to match the [commit message conventions of nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions)! 

Also, someone from the haskellers has to look over this. I am not confident in this being a valid nixpkgs package :laughing:

**Comment by danielrolls** [comment]
> Please change your commit message(s) to match the [commit message conventions of nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions)!

Apologies, done now.
 
> Also, someone from the haskellers has to look over this. I am not confident in this being a valid nixpkgs package 😆

It's valid in that it builds correctly, contains maintainer information etc. Happy to receive more feedback. Thanks.

**Comment by danielrolls** [comment]
@matthiasbeyer, I'm not sure if this helps or not. This is how I confirmed meta information is correctly specified:

```
nix-repl> builtins.elemAt shellify.meta.maintainers 0
{ email = "daniel.rolls.27@googlemail.com"; github = "danielrolls"; githubId = 50051176; name = "Daniel Rolls"; }
```

I re-added the `6.topic: haskell` to get feedback from a Haskeller as requested.

**Comment by maralorn** [comment]
Hey, thanks!

I don't think you need an extra file for this. Just add the symlink in our configuration-nix.nix also I suggest activating enableSeparateBinOutput in the same override instead of using justStaticExecutables. then in all-packages you can simply use haskellPackages.shellify.bin this way we only build the package in nixpkgs once.

Can you maybe also add a comment why the nix-shellify symlink exists?

**Comment by danielrolls** [comment]
Thanks @maralorn, this all makes sense. It worked and I think looks a lot cleaner now.

**Review by maralorn — APPROVED** [review]
Great. I am not super convinced by the comment or rather fear that this is very undiscoverable or potentially confusing. We don't prefix any other binary in nixpkgs with nix- just to signify that it was installed with nix. But I see your usecase, you are the maintainer and negative fallout is probably tiny.

One last thing: Have you confirmed with nix pathinfo that the closure is indeed small now?

**Comment by danielrolls** [comment]
It looks good. Thanks again @maralorn. I've learn a lot from this PR.
 
```
$ nix path-info .#shellify
evaluating derivation 'git+file:///home/dan/repos/nixpkgs-dr#shellify'/nix/store/zf9bmhyryc3s0h6y0cmkmdsslm5mxq77-shellify-0.10.0.3-bin
$ nix path-info .#haskellPackages.shellify
evaluating derivation 'git+file:///home/dan/repos/nixpkgs-dr#haskellPackages.shellify'/nix/store/zf9bmhyryc3s0h6y0cmkmdsslm5mxq77-shellify-0.10.0.3-bin
$ ls $(nix path-info .#shellify)
bin
```

**Comment by cdepillabout** [comment]
> We don't prefix any other binary in nixpkgs with nix- just to signify that it was installed with nix.

I was wondering about this as well, but the README introduces it as `nix-shellify`: https://github.com/danielrolls/shellify

@danielrolls Why not just change the `.cabal` file to call the executable `nix-shellify`?

**Comment by danielrolls** [comment]
> I was wondering about this as well, but the README introduces it as `nix-shellify`: https://github.com/danielrolls/shellify
> 
> @danielrolls Why not just change the `.cabal` file to call the executable `nix-shellify`?

I tried but cabal seems to use the project name which is a pain to change and has a hyphen. If you can see a way to change the binary name in cabal I agree it would be a better way.

 
> (I've never seen `nix-shellify`, but I think it is a neat idea. You should really write an announcement post on the NixOS discourse when you have in a state where you're happy to share it with people!)

Thank you. I did this but over eagerly before it was easy to download and before the asciinema examples. I'll reply to the post when this is in master. I'm not sure whether it'll bump the post or what the etiquette is there.

**Comment by cdepillabout** [comment]
@danielrolls I sent https://github.com/danielrolls/shellify/pull/6 showing how you can change the executable name in the `.cabal` file.

Also, I think you should definitely bump your post on Discourse.  I imagine more people would want to hear about `nix-shellify`.

**Comment by danielrolls** [comment]
Ok. It's good news/bad news.

**Good news**: Thanks to @cdepillabout's contribution, I've pushed a new version to hackage that renames the binary at source. This simplifies this PR drastically.

**Bad news**: Before bumping my post on Discourse we'll need to wait for the next run of the update-hackage maintenance script, then wait for the merge of haskell-updates to master and then for a nixpkgs-unstable build. It's temping to put the binary rename in for now in a future proof way but I'm guessing you'd all rather merge a simplified PR and wait, hence I pushed the simplifications.

Whatever happens I've learnt a lot and appreciate the fast and really helpful contributions. Everything is re-tested, the commit is squashed, nix path-info looks good. Hopefully I haven't missed  anything and this is good now.

**Comment by maralorn** [comment]
I am also eager to merge the next generation quickly, sadly we are having CI hickups …

**Comment by danielrolls** [comment]
Yes I saw that. I appreciate all you do to provide the CI for us. Thanks for the merge.

**Comment by maralorn** [comment]
Oh, one thing I totally forgot but now remembered, mentioning it for future reference:

Running just `nix pathinfo ./result` you only see the outpath of your build, which is not a terribly useful information.
By "checking the closure with nix pathinfo" I meant either running `nix path-info -r` which lists all dependencies. This should e.g. not list ghc. Or running `nix path-info -Sh` which shows the size of the closure. This is sometimes useful to double check that the Haskell binary really does not contain a reference to a library output, which can e.g. happen with template-haskell …

**Comment by danielrolls** [comment]
@cdepillabout, thank you for the support. As you suggested I reposted on discourse at https://discourse.nixos.org/t/shellify-tool-for-shell-nix-generation/33935.

**Pull request merged**
