### PR TITLE
python311Packages.gradio: 4.40.0 -> 4.41.0

### PR DESCRIPTION
**Pull request by pbsds**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]
LGTM, thanks !

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 334719` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
  </ul>
</details>

**Review by GaetanLepage — CHANGES_REQUESTED** [review]
You need to add `test_dataset_is_updated` to the `disabledTests` on darwin.

**Comment by GaetanLepage** [comment]
```
=========================== short test summary info ============================
FAILED test/test_blocks.py::TestBlocksPostprocessing::test_dataset_is_updated - OSError: Cannot find empty port in range: 7860-7959. You can specify a diff...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
========= 1 failed, 141 passed, 150 deselected, 63 warnings in 19.95s ==========
```

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 334719` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 334719` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 334719` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 334719` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
  </ul>
</details>

**Comment by pbsds** [comment]
i occupied all the ports and was unable to provoke any more on linux, but perhaps the sandbox rendered that exercise moot

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 334719` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 334719` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
This is never ending...
```
=========================== short test summary info ============================
FAILED test/test_client.py::TestAPIInfo::test_layout_components_in_output - OSError: Cannot find empty port in range: 7860-7959. You can specify a diff...
FAILED test/test_client.py::TestAPIInfo::test_layout_and_state_components_in_output - OSError: Cannot find empty port in range: 7860-7959. You can specify a diff...
FAILED test/test_client.py::test_upstream_exceptions - OSError: Cannot find empty port in range: 7860-7959. You can specify a diff...
FAILED test/test_client.py::test_httpx_kwargs - OSError: Cannot find empty port in range: 7860-7959. You can specify a diff...
==== 4 failed, 37 passed, 27 deselected, 37 xfailed, 269 warnings in 11.08s ====
```

**Comment by GaetanLepage** [comment]
Though, I was able to build it successfully after disabling those four.

**Comment by pbsds** [comment]
is that in gradio or gradio-client?

**Comment by GaetanLepage** [comment]
> is that in gradio or gradio-client?

`gradio`

**Comment by GaetanLepage** [comment]
wait... client

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 334719` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review) <details>   <summary>2 packages marked as broken and skipped:</summary>   <ul>     <li>python311Packages.private-gpt</li>     <li>python311Packages.private-gpt.dist</li>   </ul> </details> <details>   <summary>12 packages built:</summary>   <ul>     <li>python311Packages.gradio</li>     <li>python311Packages.gradio-client</li>     <li>python311Packages.gradio-client.dist</li>     <li>python311Packages.gradio-pdf</li>     <li>python311Packages.gradio-pdf.dist</li>     <li>python311Packages.gradio.dist</li>     <li>python312Packages.gradio</li>     <li>python312Packages.gradio-client</li>     <li>python312Packages.gradio-client.dist</li>     <li>python312Packages.gradio-pdf</li>     <li>python312Packages.gradio-pdf.dist</li>     <li>python312Packages.gradio.dist</li>   </ul> </details>

---

Result of `nixpkgs-review pr 334719` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review) <details>   <summary>2 packages marked as broken and skipped:</summary>   <ul>     <li>python311Packages.private-gpt</li>     <li>python311Packages.private-gpt.dist</li>   </ul> </details> <details>   <summary>12 packages built:</summary>   <ul>     <li>python311Packages.gradio</li>     <li>python311Packages.gradio-client</li>     <li>python311Packages.gradio-client.dist</li>     <li>python311Packages.gradio-pdf</li>     <li>python311Packages.gradio-pdf.dist</li>     <li>python311Packages.gradio.dist</li>     <li>python312Packages.gradio</li>     <li>python312Packages.gradio-client</li>     <li>python312Packages.gradio-client.dist</li>     <li>python312Packages.gradio-pdf</li>     <li>python312Packages.gradio-pdf.dist</li>     <li>python312Packages.gradio.dist</li>   </ul> </details>

**Review by GaetanLepage — APPROVED** [review]
All good !
Thanks @pbsds !

**Pull request merged**
