### PR TITLE
cagebreak: 1.7.0 -> 1.7.1

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Motivation for this change

New version with scdoc support.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Hello, @berbiche ! I have taken the liberty of removing the contrib output. It contained a single file with low impact.

If there is some reason to split it, tell me and I will revert the last commit.

**Review by berbiche — APPROVED** [review]
LGTM!

I initially created a different output for contribution stuff to mimic the Sway package and others.
Sway now has a custom `sway-contrib` package.
I suppose if Cagebreak ever start including more things in it's example/contrib folder than it could make sense to split it.

edit: thanks for opening an update PR.

**Comment by berbiche** [comment]
Out of curiosity do you use Cagebreak on one of your systems?
Last I tried they were still too many rough edges for me to make the switch from Sway.

**Comment by AndersonTorres** [comment]
My regular manager is wayfire.
I am testing cagebreak because of nostalgia of Ratpoison, but indeed there are some edges to be trimmed.

**Pull request merged**
