### PR TITLE
librsvg: 2.40.18 -> 2.42.0

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Package update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @jtojnar 
The old version attribute did not correspond to the source tarball.

Tested rebuilding a few applications that required `librsvg` and they seem to work as expected.

### CODE REVIEW

**Comment by jtojnar** [comment]
@GrahamcOfBorg build

**Comment by jtojnar** [comment]
@GrahamcOfBorg build librsvg

**Comment by jtojnar** [comment]
This is pretty unfortunate. Should we wait for https://github.com/NixOS/nixpkgs/pull/33980? Also not sure what is up with darwin.

**Comment by Mic92** [comment]
I don't think this pull request will fix your darwin problems.

**Comment by jtojnar** [comment]
Right, that one is for aarch64.

**Comment by adisbladis** [comment]
@jtojnar Yes I absolutely think we should wait for https://github.com/NixOS/nixpkgs/pull/33980.
I'll look into the darwin issue.

**Comment by adisbladis** [comment]
@GrahamcOfBorg build librsvg

**Comment by jtojnar** [comment]
@GrahamcOfBorg build librsvg

**Comment by jtojnar** [comment]
#34227 indeed fixed Darwin.

**Comment by adisbladis** [comment]
Now that https://github.com/NixOS/nixpkgs/pull/33980 is merged this should be good to go.

@GrahamcOfBorg build librsvg

**Comment by vcunat** [comment]
@GrahamcOfBorg build librsvg

**Review by vcunat — APPROVED** [review]
Sounds good, assuming Darwin succeeds (again).

**Pull request merged**
