### PR TITLE
help2man: fix hash

### PR DESCRIPTION
**Pull request by wizeman**
###### Motivation for this change

The hash appears to have changed.
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by wizeman** [comment]
**Warning:** I've experienced this has failure relatively early when upgrading from the `release-16.03` branch to `release-16.09`, which probably means this may cause a mass rebuild (I'm not sure how to check this locally, considering I'm already doing a mass rebuild for another reason?). If so, this may have to go into the `staging` and `staging-16.09` branches first.

**Comment by Mic92** [comment]
It would be interesting through to know if the content has changed.

**Comment by groxxda** [comment]
The hash was not updated @ https://github.com/nixos/nixpkgs/commit/49cf9b902ac26a7389aae5fe9c5ba5099e721a2a

**Comment by Mic92** [comment]
merged thanks.

**Pull request merged**
