### PR TITLE
wine: add initial pulseaudio support

### PR DESCRIPTION
**Pull request by ikervagyok**
tested it on my machine - don't really know, if/how i should/could test for pulseaudio on the system...
but wine here seems to be only for linux, so it's probably fine (assert in base.nix)

merry gaming season, wine-gamers on nixos,
ikervagyok

### CODE REVIEW

**Comment by the-kenny** [comment]
Maybe we should make this configurable? See similar approaches for ```SDL``` (`all-packages.nix:8305`) and `chromium`.

**Comment by ikervagyok** [comment]
Will look into it! Thanks for the pointers

**Comment by jgillich** [comment]
Just pulling pulse doesn't enable it, right? I don't think making it optional like this is a good idea, pulse users (90%+ anyway) would have to build wine now.

**Comment by ikervagyok** [comment]
@jgillich configure checks for pulse, finds it and enables it - i tested it on my machine ;)
it takes some time to build, but it's worth it - at least for me, as i can listen to music and play starcraft at the same time (on the same soundcard, that is) :D

oh, and btw the build only fails because of a timeout, so i probably didn't break anything (i did only test wine32 though)

**Comment by jgillich** [comment]
What I mean is that depending on libpulse doesn't mean you are forced to use pulse. There are no binary packages when for overriden packages, and like you said building takes a while. IMO, wine should just depend on libpulse without it being an option.

**Comment by ikervagyok** [comment]
i think this is nice - if (hopefully) non-nixos/-linux support is coming sometime soon to this package

**Comment by vcunat** [comment]
@jgillich: this PR enables the support by default (on Linux), if I skimmed it correctly. Why is that in contrary to your desires?

**Comment by bendlas** [comment]
I've test built the patch with current wine-staging, and it works fine for me. Funny thing though: I get a pulseaudio output, even with the former build, as well as concurrent sound output. Anybody else seeing this?

**Comment by ikervagyok** [comment]
@vcunat: it should, if i didn't mess sth up
@bendlas: idk, this patch enabled it for me - maybe there is some special magic in staging... i'll look into staging, if i get the time

**Comment by jgillich** [comment]
@vcunat Oh I'm sorry, totally missed that.

**Comment by jagajaga** [comment]
:+1:

**Comment by bendlas** [comment]
@ikervagyok you're right, seems to be one of the wine-staging patches: https://github.com/wine-compholio/wine-staging/tree/master/patches/winepulse-PulseAudio_Support

+1 on getting this merged

**Comment by bendlas** [comment]
@ikervagyok sorry for getting back late. I can confirm, that, with your change, I can turn off pulseaudio support in wine staging by setting `pulseaudioSupport = false`.

**Pull request merged**
