### PR TITLE
youtube-dl: 2021.05.16 -> 2021.06.06

### PR DESCRIPTION
**Pull request by zowoq**
https://github.com/ytdl-org/youtube-dl/releases/tag/2021.06.06

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Does it still needs backport?

**Comment by Ma27** [comment]
There are fixes for certain extractors, so yes IMHO

**Comment by Ma27** [comment]
I'm a bit upset here that we've stopped so early to not care about `youtube-dl` on a stable NixOS anymore even though each of these releases fixes several extractors. Anyways, I fixed that by porting the last four bumps as 8cf076715b6c155ff8c16410922a790c1484dc8b, 96e68c87e6a042573581a9f903d0f236aa12589d, 551a3436cbffba17559d518a88c3e254f1bc2bf3 & b52409e65eb55d4f75ccf1561f4d87c1a43f7b2f to stable.

**Comment by AndersonTorres** [comment]
@Ma27 seriously? The people here are very quick about porting ytdl, sometimes I barely notice the delay...

**Comment by Ma27** [comment]
I'm talking about no backports since April for ytdl.

**Comment by zowoq** [comment]
I was only doing backports as the cherrypick+test+push was trivial and I'd scripted it for some packages. 

Since the workflow has changed I've stopped doing backports.

As I'm not going to be merging/reviewing backport PRs I won't be adding the label for the automated backport so as to avoid creating a PR that may end up being ignored.

I'd suggest that whoever wants it in stable should be the one who adds the label and deals with the backport PR.

**Pull request merged**
