### PR TITLE
GDM fixes

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

This is a rework of #25621

* disable the GDM wayland mode by default
* fixes the nvidia permission issues

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by zimbatm** [comment]
we are still trying to fix the gnome3-gdm tests

**Comment by teh** [comment]
@zimbatm you might want to be explicit about `true` and `false` because `toString` behaves as follows:

```
nix-repl> toString true
"1"
```

i.e.

```diff
[daemon]
-      WaylandEnable=${toString cfg.gdm.wayland}
+      WaylandEnable=${if cfg.gdm.wayland then "true" else "false"}
       ${optionalString cfg.gdm.autoLogin.enable (
```

**Comment by copumpkin** [comment]
Any idea why it seems to think I'm an owner here?

**Comment by zimbatm** [comment]
I don't know, when I created the issue, a bunch of people were automatically added as reviewers

**Comment by dezgeg** [comment]
Probably because the base branch was incorrect the first time, GitHub though you're proposing to submit every single commit from 17.09 in master.

**Comment by zimbatm** [comment]
anyone with a nvidia card wants to test this?

**Comment by fpletz** [comment]
Should be fine. Thanks!

**Pull request merged**
