### PR TITLE
Ruby: 2.3.6 -> 2.3.7, 2.4.3 -> 2.4.4, 2.5.0 -> 2.5.1

### PR DESCRIPTION
**Pull request by manveru**
###### Motivation for this change

https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-3-7-released/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by zimbatm** [comment]
@GrahamcOfBorg build ruby_2_3 ruby_2_4 ruby_2_5

**Comment by manveru** [comment]
Seems like the darwin failure is:

    linking miniruby
    ld: framework not found Foundation
    clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [Makefile:221: miniruby] Error 1
    builder for '/nix/store/4ffqylmb1ak3zkhl062c4djksdza1sjc-ruby-2.3.7.drv' failed with exit code 2

not sure what's that about

**Comment by LnL7** [comment]
@manveru I guess this version conditional isn't correct. https://github.com/manveru/nixpkgs/blob/f99ded298f5b34437395cc739d52042b4dce3580/pkgs/development/interpreters/ruby/default.nix#L97

**Review by LnL7 — APPROVED** [review]
Sorry for the delay

**Comment by LnL7** [comment]
Backported to 18.03 in 94a3649e4ca.

**Pull request merged**
