### PR TITLE
nixUnstable: Update to 1.9pre4100_4bbcfaf

### PR DESCRIPTION
**Pull request by edwtjo**

### CODE REVIEW

**Comment by copumpkin** [comment]
Seems uncontroversial. Any reason you didn't just push directly?

**Comment by edwtjo** [comment]
Not really, just wanted to make sure updating nix isn't considered bad behaviour :)

**Comment by copumpkin** [comment]
Seems fine to me :+1:

**Comment by edolstra** [comment]
Note that when you update the unstable version to a new tarball on Hydra, you must mark the build as "keep", otherwise it will be garbage-collected eventually. I've done that now.

**Comment by edwtjo** [comment]
@edolstra thank you

**Pull request merged**
