### PR TITLE
docker & docker-machine-xhyve: enable darwin support

### PR DESCRIPTION
**Pull request by periklis**
###### Motivation for this change

Using docker cli client as a pure dependency on darwin is the starting point for a more pure docker support on this platform. The proposed PR makes docker-engine builds depending on platform. This is not a full docker support for darwin, because running the daemon needs either a virtualbox or xhyve based solution.

This packages:
- [x] docker cli
- [x] docker-machine-xhyve

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by NeQuissimus** [comment]
For the heck of it, could you (outside this PR) try Docker v17.11.0-ce-rc4 ?
Might as well make the implementation work with the soon-to-be-released 17.11

**Comment by periklis** [comment]
@NeQuissimus sure, why not :)

**Comment by periklis** [comment]
@NeQuissimus The darwin build for `v17.11.0-ce-rc4` works fine. However, i do not have access to a hydra for linux builds. I can push a second branch for that.

**Comment by NeQuissimus** [comment]
No, no worries, I just wanted to make sure since I usually only test Docker on Linux when I update

**Comment by LnL7** [comment]
@GrahamcOfBorg docker

**Comment by NeQuissimus** [comment]
@grahamc What happened to the borg here?

**Comment by grahamc** [comment]
I just re-triggered evaluation checking again. Are you wondering about the build results or the eval results?

**Comment by NeQuissimus** [comment]
Docker should not be marked as broken...

**Comment by grahamc** [comment]
It turns out all the errors here are from the same problem. something about this PR makes this happen:

> error: Package ‘docker-17.09.0-ce’ in /var/lib/gc-of-borg/.nix-test/mr-est-38dca4e3aa6bca43ea96d2fcc04e8229-31737/pkgs/applications/virtualization/docker/default.nix:190 is not supported on ‘x86_64-linux’, refusing to evaluate.

**Comment by NeQuissimus** [comment]
Oh!

Could we get @GrahamcOfBorg to output this info somehow?

**Comment by grahamc** [comment]
I've been thinking through this a bit. I think yes, I'm a bit worried about sharing secrets about hosts but I think with our Hydra-like safeguards, we should be OK to share them.

**Comment by periklis** [comment]
@NeQuissimus Packaging `docker-machine-xhyve` will take me some time. However we can merge this for start to enable using docker cli als buildInput on darwin.

**Comment by periklis** [comment]
@grahamc Can anybody call for Grahamcofborg to build our PR or maintainers only?

**Comment by LnL7** [comment]
@GrahamcOfBorg build docker

**Comment by grahamc** [comment]
@periklis only about 10 people can call it right now. We're working on making it a wider group though!

**Comment by grahamc** [comment]
Note, though, that it doesn't make sense that Docker is broken on Linux here. Something is wrong with this PR.

**Comment by periklis** [comment]
@grahamc Sure it doesn't make sense to merge something broken. However, if borg is not giving me an useful error message, could somebody put a simple jobset on hydra to find the issue?

**Comment by grahamc** [comment]
I've posted the error message, and the bot has posted the same error message, also see the "Details" link next to "eval-nixos-options" (this is new as of Yesterday.) Hydra won't tell us more, unfortunately.

**Comment by NeQuissimus** [comment]
@periklis This is literally all we have to go on:

(Docker definitely builds on master, not with this PR; I just tried both)

```bash
λ nix-build -A docker --show-trace
error: while evaluating the attribute ‘docker_17_09’ at /home/nequi/dev/nixpkgs/pkgs/applications/virtualization/docker/default.nix:200:3:
while evaluating ‘dockerGen’ at /home/nequi/dev/nixpkgs/pkgs/applications/virtualization/docker/default.nix:11:15, called from /home/nequi/dev/nixpkgs/pkgs/applications/virtualization/docker/default.nix:200:18:
while evaluating ‘mkDerivation’ at /home/nequi/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:15:5, called from /home/nequi/dev/nixpkgs/pkgs/applications/virtualization/docker/default.nix:16:7:
while evaluating ‘addPassthru’ at /home/nequi/dev/nixpkgs/lib/customisation.nix:135:22, called from /home/nequi/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:166:7:
while evaluating anonymous function at /home/nequi/dev/nixpkgs/pkgs/stdenv/generic/check-meta.nix:5:1, called from /home/nequi/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:167:22:
while evaluating ‘throwEvalHelp’ at /home/nequi/dev/nixpkgs/pkgs/stdenv/generic/check-meta.nix:128:19, called from /home/nequi/dev/nixpkgs/pkgs/stdenv/generic/check-meta.nix:194:17:
Package ‘docker-17.09.0-ce’ in /home/nequi/dev/nixpkgs/pkgs/applications/virtualization/docker/default.nix:190 is not supported on ‘x86_64-linux’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.
```

**Comment by periklis** [comment]
hopefully that fixed the evaluation. I tested successfully with `nix-instantiate -A docker --argstr system 'x86_64-linux' --show-trace` on darwin. However, the errors i got were related with the `installPhase` and not with meta as the borg suggested. It would be nice if the borg used `--show-trace` by default.

**Comment by periklis** [comment]
@NeQuissimus Sorry i didn't get the error on the first time and for sure it's not my intention to break our beloved linux users :)

**Comment by NeQuissimus** [comment]
@periklis I am still getting the same error

**Review by LnL7 — COMMENTED** [review]
I suspect you have `allowBroken = true;` in your config.nix that hides the meta problem on your machine. In that case you can use `--argstr config {}` or `:a import <nixpkgs> { config = {}; }` in nix-repl for testing to make sure your local config/overrides don't influence the results.

**Comment by LnL7** [comment]
@GrahamcOfBorg build docker

**Comment by periklis** [comment]
just for the protocol from the irc, the instantiation of the derivation on `x86_64-linux` is fine:
`nix-instantiate -A docker --show-trace --argstr system 'x86_64-linux' `
However, the borg uses the extra option `--option restrict-eval true`. What is the truth now?

**Comment by LnL7** [comment]
@GrahamcOfBorg build docker

**Comment by NeQuissimus** [comment]
Ah, I missed that! Makes sense now... I think this is good to go then?!

**Comment by periklis** [comment]
@NeQuissimus yes let's wait for the borg builds and then i'll push the squashed commits with the fixups.

**Comment by NeQuissimus** [comment]
I think everything has been built, no?

**Review by LnL7 — APPROVED** [review]

**Comment by LnL7** [comment]
was waiting for the eval checks

**Comment by gilligan** [comment]
Is there any documentation that could/should be written for this?

**Comment by NeQuissimus** [comment]
I guess we're not squashing? :D Anyways, things should work fine now

**Comment by periklis** [comment]
@gilligan it can be used like this: https://pewpewthespells.com/blog/setup_docker_on_mac.html

**Comment by gilligan** [comment]
@periklis that’s not documentation though, that is a link to a blog article talking about homebrew stuff ;)

I was wondering if smth could/should be added to the manual about using this.

**Pull request merged**
