### PR TITLE
snapTools.makeSnap: init

### PR DESCRIPTION
**Pull request by grahamc**
Hopefully the docs I wrote explains it!

The result of my Snapcraft.io summit in Montreal.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
This is actually blocked on upstream support (cc @jdstrand). Snap's store validates every path in the package exists, and thinks `/nix/store/foo` does not exist when it does.

**Comment by jdstrand** [comment]
FYI, this is fixed in the review-tools of the store but it isn't in production yet. Feel free to upload to the store and request a manual review and we can manually approve it in the meantime.

**Comment by disassembler** [comment]
Experienced issues in manual review when I had coreutils added into the path of a script:
```
Feedback for version bh9l2dnzvjrkf4lvwrhs2prwhsw78192 (12) upload of jormungandr.

$ snap-review ./ea3h8Lw22pDjjwr4fIOofgj58AnWkwSL_12.snap 
Errors
------
 - lint-snap-v2:external_symlinks
        package contains external symlinks: nix/store/zh1q7yvyaxlcmj3n6g0rrdaq0v73pp90-linux-pam-1.3.1/bin/unix_chkpwd
./ea3h8Lw22pDjjwr4fIOofgj58AnWkwSL_12.snap: FAIL

This error is real:

$ ls -l nix/store/zh1q7yvyaxlcmj3n6g0rrdaq0v73pp90-linux-pam-1.3.1/bin/unix_chkpwd
lrwxrwxrwx 1 jamie jamie 29 Dec 31  1969 nix/store/zh1q7yvyaxlcmj3n6g0rrdaq0v73pp90-linux-pam-1.3.1/bin/unix_chkpwd -> /run/wrappers/bin/unix_chkpwd

/run/wrappers/bin/unix_chkpwd isn't guaranteed to exist out side of the snap (and indeed doesn't in, for example, Ubuntu.
```

Derivation of script is here: https://github.com/input-output-hk/jormungandr-nix/blob/master/default.nix#L136

and building snappy package is here: https://github.com/input-output-hk/jormungandr-nix/blob/master/linux/default.nix

**Comment by grahamc** [comment]
It would be interesting to walk the store paths and verify there are no symlinks to `/run`, and also that the `command`s are executable files.

**Comment by samueldr** [comment]
This PR [broke the manual build](https://hydra.nixos.org/build/95979020/nixlog/1) (I think).

```
[...]
warning: failed to load external entity "../pkgs/build-support/snap/example-hello.nix"
functions/snaptools.xml:41: element include: XInclude error : could not load ../pkgs/build-support/snap/example-hello.nix, and no fallback was found
warning: failed to load external entity "../pkgs/build-support/snap/example-firefox.nix"
functions/snaptools.xml:60: element include: XInclude error : could not load ../pkgs/build-support/snap/example-firefox.nix, and no fallback was found
jing doc-support/result/docbook.rng manual-full.xml
/build/doc/manual-full.xml:13541:98: error: element "xi:include" not allowed here; expected the element end-tag, text or element "abbrev", "accel", "acronym", "alt", "anchor", "annotation", "application", "author", "biblioref", "citation", "citebiblioid", "citerefentry", "citetitle", "classname", "co", "code", "command", "computeroutput", "constant", "coref", "database", "date", "editor", "email", "emphasis", "envar", "errorcode", "errorname", "errortext", "errortype", "exceptionname", "filename", "firstterm", "footnote", "footnoteref", "foreignphrase", "function", "glossterm", "guibutton", "guiicon", "guilabel", "guimenu", "guimenuitem", "guisubmenu", "hardware", "indexterm", "info", "initializer", "inlineequation", "inlinemediaobject", "interfacename", "jobtitle", "keycap", "keycode", "keycombo", "keysym", "lineannotation", "link", "literal", "markup", "menuchoice", "methodname", "modifier", "mousebutton", "nonterminal", "olink", "ooclass", "ooexception", "oointerface", "option", "optional", "org", "orgname", "package", "parameter", "person", "personname", "phrase", "productname", "productnumber", "prompt", "property", "quote", "remark", "replaceable", "returnvalue", "shortcut", "subscript", "superscript", "symbol", "systemitem", "tag", "termdef", "textobject", "token", "trademark", "type", "uri", "userinput", "varname", "wordasword" or "xref"
/build/doc/manual-full.xml:13560:100: error: element "xi:include" not allowed here; expected the element end-tag, text or element "abbrev", "accel", "acronym", "alt", "anchor", "annotation", "application", "author", "biblioref", "citation", "citebiblioid", "citerefentry", "citetitle", "classname", "co", "code", "command", "computeroutput", "constant", "coref", "database", "date", "editor", "email", "emphasis", "envar", "errorcode", "errorname", "errortext", "errortype", "exceptionname", "filename", "firstterm", "footnote", "footnoteref", "foreignphrase", "function", "glossterm", "guibutton", "guiicon", "guilabel", "guimenu", "guimenuitem", "guisubmenu", "hardware", "indexterm", "info", "initializer", "inlineequation", "inlinemediaobject", "interfacename", "jobtitle", "keycap", "keycode", "keycombo", "keysym", "lineannotation", "link", "literal", "markup", "menuchoice", "methodname", "modifier", "mousebutton", "nonterminal", "olink", "ooclass", "ooexception", "oointerface", "option", "optional", "org", "orgname", "package", "parameter", "person", "personname", "phrase", "productname", "productnumber", "prompt", "property", "quote", "remark", "replaceable", "returnvalue", "shortcut", "subscript", "superscript", "symbol", "systemitem", "tag", "termdef", "textobject", "token", "trademark", "type", "uri", "userinput", "varname", "wordasword" or "xref"
make: *** [Makefile:29: validate] Error 1
builder for '/nix/store/xlnk7zwx55yccml3kq718c0ayjlii5hd-nixpkgs-manual.drv' failed with exit code 2
```

**Comment by grahamc** [comment]
Fixed! Thank you, sorry about that :(

**Comment by djmaze** [comment]
Tried to wrap my head around on how this works. You still need a machine running snap in order to build the final snap package, right? So, as snap is not (yet) working on NixOS, you cannot build snap packages on NixOS for now. Which would be quite valuable in order to provide packages for other distributions from a NixOS development machine.

**Pull request merged**
