### PR TITLE
nixos/filesender init

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

Add Filesender package and NixOS service: https://filesender.org/

This is work in progress at the moment, that's why it's a draft PR. I wanted to open it anyway immediately so others can see that it's being worked on and it can be discussed here.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jluttine** [comment]
If I understand correctly, FileSender requires a working installation of SImpleSAMLphp (step 4 in https://docs.filesender.org/v2.0/install/). However, SimpleSAMLphp has a lot of PHP dependencies and they should be installed with Composer: https://simplesamlphp.org/docs/development/simplesamlphp-install-repo It looks like a very deep rabbit hole to me.. I really don't know how to install this kind of PHP beast in NixOS. Any ideas? In addition, there's some npm stuff and I'm not familiar with that either, but probably nixpkgs has better support for that.

Alternatively, if FileSender can be installed without SimpleSAMLphp, that might be a good enough workaround.

I'm a bit stuck now. :confused:

**Comment by monkeyiq** [comment]
You will want to use the latest stable release of SimpleSAMLphp. IIRC it is just a matter of extracting the archive for it. No additional npm install or composer usage required.

There are one or two commands in installation step 4 (from https://docs.filesender.org/v2.0/install/) before the extra suggestions for security starting with "There are some thoughts on updates to your SimpleSAMLphp configuration which may improve security". You might want to skip over the extra security suggestions for an initial build and add them if desired only once you know things are working.

As far as SimpleSAMLphp goes, if you are using apache the config template in filesender distribution at config-templates/apache/filesender.conf will allow the web server to access things if they are in the expected location. So SimpleSAMLphp installation should be close to expanding it to a known location and mv/cp a few files. If you are using the shortcut auth then the username and password information is stored in a config file and you have to touch modules/exampleauth/enable in the simplesamlphp install which might as well be done by the packaging.

**Comment by monkeyiq** [comment]
I am making a move toward allowing simpler local authentication if desired
https://github.com/filesender/filesender/pull/761

This will still use SimpleSAMLphp but will authenticate against hashed passwords from the same database that filesender already needs. I don't have a web interface in FileSender for managing passwords yet, that should drop soon. This setup should become easier over time as I intend to upstream the SimpleSAMLphp module from the above PR.

**Comment by monkeyiq** [comment]
And a web interface for this should soon be merged
https://github.com/filesender/filesender/pull/762

**Comment by JulienMalka** [comment]
This has been implemented in #313473, closing

**Pull request closed without merging**
