### PR TITLE
python310Packages.jaxopt: 0.5.5 -> 0.8.1

### PR DESCRIPTION
**Pull request by bcdarwin**
python310Packages.bambi: 0.10.0 -> 0.12.0
python310Packages.blackjax: 0.9.6 -> 1.0.0
python310Packages.chex: 0.1.82 -> 0.1.83

## Description of changes

Update some packages; unbreaks `python310Packages.bambi`.

Supersedes #240692.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [NA] (Module updates) Added a release notes entry if the change is significant
  - [NA] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by anthonyroussel — COMMENTED** [review]
EDIT: bambi, blackjax and jaxopt builds are failing because of out-of-memory errors on my laptop.

This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 260359` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
28 packages marked as broken and skipped:
</summary>
<ul>
<li>python310Packages.dalle-mini</li>
<li>python310Packages.dalle-mini.dist</li>
<li>python310Packages.distrax</li>
<li>python310Packages.distrax.dist</li>
<li>python310Packages.elegy</li>
<li>python310Packages.elegy.dist</li>
<li>python310Packages.flax</li>
<li>python310Packages.flax.dist</li>
<li>python310Packages.rlax</li>
<li>python310Packages.rlax.dist</li>
<li>python310Packages.treex</li>
<li>python310Packages.treex.dist</li>
<li>python310Packages.vqgan-jax</li>
<li>python310Packages.vqgan-jax.dist</li>
<li>python311Packages.dalle-mini</li>
<li>python311Packages.dalle-mini.dist</li>
<li>python311Packages.distrax</li>
<li>python311Packages.distrax.dist</li>
<li>python311Packages.elegy</li>
<li>python311Packages.elegy.dist</li>
<li>python311Packages.flax</li>
<li>python311Packages.flax.dist</li>
<li>python311Packages.rlax</li>
<li>python311Packages.rlax.dist</li>
<li>python311Packages.treex</li>
<li>python311Packages.treex.dist</li>
<li>python311Packages.vqgan-jax</li>
<li>python311Packages.vqgan-jax.dist</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>python310Packages.bambi: log was empty</li>
  </ul>
</details>
<details>

  <summary>5 packages failed to build and are new build failures:</summary>
  <ul>
<li>python310Packages.bambi.dist: log was empty</li>
<li>python310Packages.blackjax: log was empty</li>
<li>python310Packages.blackjax.dist: log was empty</li>
<li>python310Packages.jaxopt: <a href="https://termbin.com/xg9bf">plain log</a></li>
<li>python310Packages.jaxopt.dist: <a href="https://termbin.com/cmlr">plain log</a></li>
  </ul>
</details>
<details>
<summary>
14 packages built:
</summary>
<ul>
<li>python310Packages.chex</li>
<li>python310Packages.chex.dist</li>
<li>python310Packages.optax</li>
<li>python310Packages.optax.dist</li>
<li>python310Packages.optax.testsout</li>
<li>python311Packages.blackjax</li>
<li>python311Packages.blackjax.dist</li>
<li>python311Packages.chex</li>
<li>python311Packages.chex.dist</li>
<li>python311Packages.jaxopt</li>
<li>python311Packages.jaxopt.dist</li>
<li>python311Packages.optax</li>
<li>python311Packages.optax.dist</li>
<li>python311Packages.optax.testsout</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
python310Packages.blackjax.dist:
<details>


warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/development/python-modules/blackjax/default.nix:5:3:

```
  |
5 | , fetchpatch
  |   ^
```
</details>
python310Packages.blackjax:
<details>


warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/development/python-modules/blackjax/default.nix:5:3:

```
  |
5 | , fetchpatch
  |   ^
```
</details>
python311Packages.blackjax.dist:
<details>

got build log for '/nix/store/cj74aryi8rmc8vjisrs8482qh1dajp1y-python3.11-blackjax-1.0.0-dist' from 'daemon'
When evaluating attribute ‘python311Packages.blackjax.dist’:
warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/development/python-modules/blackjax/default.nix:5:3:

```
  |
5 | , fetchpatch
  |   ^
```
</details>
python311Packages.blackjax:
<details>

got build log for '/nix/store/vbr38qjpbkrw07dabna9a62g742c7qn9-python3.11-blackjax-1.0.0' from 'daemon'
When evaluating attribute ‘python311Packages.blackjax’:
warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/development/python-modules/blackjax/default.nix:5:3:

```
  |
5 | , fetchpatch
  |   ^
```
</details>
</details>

**Comment by bcdarwin** [comment]
Removed extraneous `fetchpatch` from `blackjax`.

Unclear why Hydra is terminating some of the builds.

**Comment by bcdarwin** [comment]
`nixpkgs-review` succeeds for me, unclear why some builds are being terminated for @anthonyroussel.

**Comment by anthonyroussel** [comment]
> `nixpkgs-review` succeeds for me, unclear why some builds are being terminated for @anthonyroussel.

Looks like bambi, blackjax and jaxopt builds are failing on my laptop because of out-of-memory errors. I will run the nixpkgs-review-checks again

**Review by anthonyroussel — APPROVED** [review]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 260359` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
28 packages marked as broken and skipped:
</summary>
<ul>
<li>python310Packages.dalle-mini</li>
<li>python310Packages.dalle-mini.dist</li>
<li>python310Packages.distrax</li>
<li>python310Packages.distrax.dist</li>
<li>python310Packages.elegy</li>
<li>python310Packages.elegy.dist</li>
<li>python310Packages.flax</li>
<li>python310Packages.flax.dist</li>
<li>python310Packages.rlax</li>
<li>python310Packages.rlax.dist</li>
<li>python310Packages.treex</li>
<li>python310Packages.treex.dist</li>
<li>python310Packages.vqgan-jax</li>
<li>python310Packages.vqgan-jax.dist</li>
<li>python311Packages.dalle-mini</li>
<li>python311Packages.dalle-mini.dist</li>
<li>python311Packages.distrax</li>
<li>python311Packages.distrax.dist</li>
<li>python311Packages.elegy</li>
<li>python311Packages.elegy.dist</li>
<li>python311Packages.flax</li>
<li>python311Packages.flax.dist</li>
<li>python311Packages.rlax</li>
<li>python311Packages.rlax.dist</li>
<li>python311Packages.treex</li>
<li>python311Packages.treex.dist</li>
<li>python311Packages.vqgan-jax</li>
<li>python311Packages.vqgan-jax.dist</li>
</ul>
</details>
<details>
<summary>
20 packages built:
</summary>
<ul>
<li>python310Packages.bambi</li>
<li>python310Packages.bambi.dist</li>
<li>python310Packages.blackjax</li>
<li>python310Packages.blackjax.dist</li>
<li>python310Packages.chex</li>
<li>python310Packages.chex.dist</li>
<li>python310Packages.jaxopt</li>
<li>python310Packages.jaxopt.dist</li>
<li>python310Packages.optax</li>
<li>python310Packages.optax.dist</li>
<li>python310Packages.optax.testsout</li>
<li>python311Packages.blackjax</li>
<li>python311Packages.blackjax.dist</li>
<li>python311Packages.chex</li>
<li>python311Packages.chex.dist</li>
<li>python311Packages.jaxopt</li>
<li>python311Packages.jaxopt.dist</li>
<li>python311Packages.optax</li>
<li>python311Packages.optax.dist</li>
<li>python311Packages.optax.testsout</li>
</ul>
</details>

**Review by marsam — APPROVED** [review]

**Pull request merged**
