### PR TITLE
nixos/xfce4-14: add xfce4-volumed-pulse when not using the desktop

### PR DESCRIPTION
**Pull request by symphorien**
xfce4-volumed-pulse is not abandoned, but is superseded by a panel
plugin which is not available when not using the desktop.
Source: https://xfce.org/about/news/?post=1565568000

Fixes the following issue: the volume up and volume down keys would not have any effect.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Commit message should lead-in with `nixos/xfce4-14`.

Can we add a comment that it's a "superfluous additional daemon" that only makes sense to add if we're not using the desktop? Conditional logic might not communicate this down the timeline.

Perhaps in a `let in` have it as `pulseaudioDaemon = ....` with the comment for clarity.

**Comment by worldofpeace** [comment]
I'm in favor of backporting this. IIRC the old module added it.

**Comment by symphorien** [comment]
> Commit message should lead-in with `nixos/xfce4-14`.
> 
> Can we add a comment that it's a "superfluous additional daemon" that only makes sense to add if we're not using the desktop? Conditional logic might not communicate this down the timeline.
> 
> Perhaps in a `let in` have it as `pulseaudioDaemon = ....` with the comment for clarity.

I added a comment. Not `let` because the two alternative are not "homogeneous" in my opinion.

I am also in favor of backporting it. That was a regression for me when upgrading from 19.03.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg test xfce4-14

**Comment by worldofpeace** [comment]
backported in 8244f41f1024c9c5a149ff96be38e6a78671ed53

**Pull request merged**
