### PR TITLE
python312Packages.numpyro: 0.15.2 -> 0.15.3

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: Changelog: https://github.com/pyro-ppl/numpyro/releases/tag/0.15.3

- **python312Packages.numpyro: 0.15.2 -> 0.15.3**
- **python312Packages.numpyro: use pytest-xdist to speed up testing**
- **python312Packages.numpyro: switch to fetchFromGitHub**

cc @fabaff

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 342734` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.flowmc.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 342734` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 342734` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 342734` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.flowmc.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
  </ul>
</details>
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 342734` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 342734` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.flowmc.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 342734` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.flowmc.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
@ofborg build python312Packages.arviz python311Packages.arviz

**Comment by GaetanLepage** [comment]
`arviz` fails on `aarch64-darwin` fails on `aarch64-darwin` by segfaulting during tests.
This is not a regression. When forcing the rebuild on `master` it does the same.
So I guess that it has somehow been built successfully on hydra and cached since then.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 342734` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.flowmc.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Comment by pbsds** [comment]
on 3 machines it broke, on one it succeeded, here are the logs

```
numpyro> FAILED test/contrib/test_enum_elbo.py::test_guide_plate_contraction
numpyro> FAILED test/infer/test_autoguide.py::test_beta_bernoulli[AutoGuideList]
numpyro> FAILED test/infer/test_hmc_util.py::test_gaussian_subposterior[True-consensus]
numpyro> FAILED test/infer/test_mcmc.py::test_SA_chain_gradient_free[2]
numpyro> FAILED test/infer/test_reparam.py::test_loc_scale[1-Normal-1.0-(3, 2)]
numpyro> FAILED test/infer/test_mcmc.py::test_logistic_regression_x64[SA]
numpyro> FAILED test/infer/test_svi.py::test_renyi_nonnested_plates
numpyro> FAILED test/infer/test_svi.py::test_tracegraph_gaussian_chain[5-6000-0.003-0.05-0.6]
numpyro> FAILED test/infer/test_mcmc.py::test_chain[parallel-True]
numpyro> FAILED test/infer/test_autoguide.py::test_autosldais
numpyro> FAILED test/infer/test_autoguide.py::test_logistic_regression[Trace_ELBO-AutoLaplaceApproximation]
numpyro> FAILED test/infer/test_mcmc.py::test_chain[vectorized-False]
numpyro> FAILED test/infer/test_mcmc.py::test_beta_bernoulli_x64[NUTS]
numpyro> FAILED test/infer/test_mcmc.py::test_logistic_regression_x64[AIES]
numpyro> FAILED test/infer/test_hmc_util.py::test_welford_covariance[False-True-True]
```

```
numpyro> FAILED test/infer/test_mcmc.py::test_logistic_regression_x64[BarkerMH]
numpyro> FAILED test/infer/test_svi.py::test_beta_bernoulli[optimizer0-elbo1]
numpyro> FAILED test/infer/test_infer_util.py::test_predictive[True]
numpyro> FAILED test/test_nn.py::test_masks[1-1-6]
numpyro> FAILED test/infer/test_mcmc.py::test_logistic_regression_x64[AIES]
```

```
numpyro> FAILED test/contrib/test_enum_elbo.py::test_guide_plate_contraction
numpyro> FAILED test/infer/test_infer_util.py::test_initialize_model_change_point[init_to_median]
numpyro> FAILED test/infer/test_autoguide.py::test_beta_bernoulli[AutoGuideList]
numpyro> FAILED test/infer/test_hmc_gibbs.py::test_hmcecs_normal_normal[2-50-2-NUTS]
numpyro> FAILED test/infer/test_mcmc.py::test_chain[parallel-False]
numpyro> FAILED test/infer/test_infer_util.py::test_initialize_model_change_point[init_strategy0]
numpyro> FAILED test/infer/test_svi.py::test_vectorized_particle
numpyro> FAILED test/test_handlers.py::test_plate[model_subsample_1]
numpyro> FAILED test/infer/test_autoguide.py::test_autosldais
numpyro> FAILED test/infer/test_svi.py::test_mutable_state[Trace_ELBO-10-False]
numpyro> FAILED test/infer/test_mcmc.py::test_logistic_regression_x64[SA]
numpyro> FAILED test/infer/test_mcmc.py::test_logistic_regression_x64[AIES]
numpyro> FAILED test/infer/test_mcmc.py::test_logistic_regression_x64[ESS]
```

**Comment by pbsds** [comment]
how much of a difference does xdist make?

**Comment by GaetanLepage** [comment]
> how much of a difference does xdist make?

In terms of perf ? Quite a lot actually. I can do a little benchmark if you wish.

**Comment by pbsds** [comment]
well, there doesn't seem to be a pattern to the flakyness, so i'd consider disabling xdist

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review)

- Command: `nixpkgs-review pr 342734`
- Systems: `aarch64-linux`,`x86_64-darwin`,`aarch64-darwin`,`x86_64-linux`

### `aarch64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 14 packages built:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

### `x86_64-darwin`
<details>
  <summary>:fast_forward: 16 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

### `aarch64-darwin`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.flowmc.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 8 packages failed to build:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 16 packages built:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.flowmc.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> well, there doesn't seem to be a pattern to the flakyness, so i'd consider disabling xdist

Sure, I have removed it.

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

- Command: `nixpkgs-review pr 342734`
- Systems: `x86_64-linux`,`aarch64-linux`,`x86_64-darwin`,`aarch64-darwin`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 16 packages built:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.flowmc.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 14 packages built:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 16 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.flowmc.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 8 packages failed to build:</summary>
  <ul>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.corner.dist</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.arviz.dist</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.corner.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
  </ul>
</details>

**Pull request merged**
