### PR TITLE
openttd: add some missing dependencies

### PR DESCRIPTION
**Pull request by YellowOnion**
## Description of changes

taken from here: https://github.com/YellowOnion/OpenTTD-patches/commit/nix-shell

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fpletz** [comment]
@YellowOnion I've rebase your PR and force-pushed since there was an openttd update on master since. Furthermore, there seems more dependencies have been missing according to the cmake configure phase. I've added those. Please review my changes.

`harfbuzz` doesn't seem to be used - at lease the configure phase doesn't complain about it. Do you have more information about that?

**Comment by YellowOnion** [comment]
@fpletz sorry I thought I had my master branch up to date ( or it was extremely bad timing)

cmake complains about harfbuzz, it's part of the icu dependency. lzo support isn't really needed as it's for very old game versions (< v0.3), Documentation doesn't mention Allegro, so I'm somewhat unsure what it's for, and I suspect it's been replaced with SDL, I also have no idea about the other ones you added, I didn't see any complains from cmake here, maybe I'll have a look over it again, but maybe it's a red herring after adding pkg-config, since cmake has it's own detection system.

https://github.com/JGRennison/Upstream-OpenTTD/blob/master/COMPILING.md

**Comment by fpletz** [comment]
Thanks for the insights. I've removed lzo again and agree with allegro. And :+1: for harfbuzz, that seems to the the errors finding "SSE" which is totally obvious. :eyes:

All other dependencies were added since the configure phase was complaining about it. Have another look and if you agree I'll squash the commits and merge. Thanks a lot!

**Review by jcumming — APPROVED** [review]
This is great, thanks!

**Comment by YellowOnion** [comment]
@fpletz oh I think I know what's the difference, I'm running cmake directly in an impure shell, must be getting dependencies from the environment. and then I skimmed over it looking for Yellow errors when I ported to nixpkgs, I suspect dependencies dependencies don't really matter for compiling/linking, just at run time, can't hurt to include though.

**Pull request merged**
