### PR TITLE
fuzzel: refactor configure options

### PR DESCRIPTION
**Pull request by polykernel**
The current configure options exposed emulates the `choices` type of the
SVG and PNG backends from upstream meson_options with a freeform string,
however this is error prone and require accompanying validation which
unnecessarily complicates the derivation. Two alternatives were considered:

1. Splits the possible choices into separate options nad perform assertions to
   ensure only one is selected.
2. Expose a set of sane default configure options, and structure the derivation
   around this subset. Users who wish to customize the choice used can do so
   using `override` or `overrideAttrs`.

Option 1 is not sustainable for large amounts of options which require large
amount of assertions just for ensuring uniqueness of selection, and adds
complexity to the configure phase. Option 2 minimally impairs the customizablity
of the derivation and was chosen in part to address option checking[1].

[1] - https://github.com/NixOS/nixpkgs/pull/141836#discussion_r739910095

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@polykernel please rebase

**Comment by ck3d** [comment]
Can you please rebase

**Comment by polykernel** [comment]
@ck3d done, I also reverted https://github.com/NixOS/nixpkgs/commit/e01c41205234a68a55903e05800e62d0de302e1a as it has been fixed upstream.

**Review by ck3d — APPROVED** [review]
Thanks for the update.

**Pull request merged**
