### PR TITLE
matrix-synapse: 1.12.4 -> 1.13.0, riot-{web,desktop}: 1.6.0 -> 1.6.1

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

Some Matrix-related updates:

* `matrix-synapse`: https://github.com/matrix-org/synapse/releases/tag/v1.13.0
* `riot-web`: https://github.com/vector-im/riot-web/releases/tag/v1.6.1
* `riot-desktop`: https://github.com/vector-im/riot-desktop/releases/tag/v1.6.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by fadenb — APPROVED** [review]

**Review by Ekleog — APPROVED** [review]

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 88171` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
<br>- matrix-synapse
<br>- riot-desktop
</details>

**Review by mweinelt — APPROVED** [review]

**Review by mweinelt — APPROVED** [review]
Quickly tested riot-desktop and seemed fine.

**Comment by blitz** [comment]
I gave riot-desktop a spin and didn't notice any issues.

**Review by blitz — APPROVED** [review]

**Comment by Ma27** [comment]
Ported the `riot-*` updates to stable: 5d12be83a63e471cd64b0947bef04b934992d7e2, 0436b0d8a2484c0fbea8e1712109e9e2a38ca096

Also opened a backport PR for `matrix-synapse` since this the release has some non-trivial changes and I'd prefer to get a review on this first.

**Pull request merged**
