### PR TITLE
WIP: bugzilla nixos module

### PR DESCRIPTION
**Pull request by garbas**
do not merge yet!

i got it working but needs "some" polishing.

TODO:
- [x] mod_perl
- [ ] extend apache nixos configuration with enablePerl option
- [ ] helper module for bugzilla like its done for mediawiki

Example:

```
   services.postgresql.enable = true;
   services.postgresql.package = pkgs.postgresql93;
   services.httpd.enable = true;
   services.httpd.extraSubservices = [
          { serviceType = "bugzilla"; }
   ];



```

[Review on Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/3651)

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@garbas are you using this is any form?

**Comment by offlinehacker** [comment]
I will cleanup this if @garbas will not have time, but expect module to be
part of service abstraction layer i'm working on.

**Comment by garbas** [comment]
sry, i'm busy last months ... it used to work at sprint in ljubljana.
shouldn't be hard to make it work.

**Comment by jagajaga** [comment]
PIng? :)

**Comment by jcumming** [comment]
Do we want bugzilla? ;)

     What's your advice for developers who want to get involved?
     Never admit you know anything about databases, never offer to help configure bugzilla.

https://www.linux.com/news/special-feature/linux-developers/611198-30-linux-kernel-developers-in-30-weeks-alan-cox

**Comment by garbas** [comment]
@jcumming it would be nice way to see if we can make bugzilla easier to install and manage with nix.

**Comment by ocharles** [comment]
What's the status of this PR? If you received the feedback you wanted and there is still more to be done, maybe this should be closed and re-opened when it has progressed?

**Comment by garbas** [comment]
@ocharles +1

**Pull request closed without merging**
