### PR TITLE
rPackages.immunotation: cache external URLs

### PR DESCRIPTION
**Pull request by Kupac**
## Description of changes

Immunotation uses 3 external URL-s, and stores them variables in the package's namespace. Package installation is not possible without internet connection, and skipping load test doesn't help, because this happens _before_ the load test.

I use fetchurl to get those external deps, and replace them in the code with a patch + substituteInPlace.

This should work in the long term for the  two MHC allele lists, but I'm not sure about the geographical region list. We'll have to see how frequently the website changes. I only found the copyright2024 notice problematic, because it could change every year, which means we'd have to update the hash. I think that would still be acceptable. If it's more frequent, we'll have to mark this as broken, I think. 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by b-rodrigues — APPROVED** [review]
builds and loads on aarch64-linux

**Comment by lkupcsik** [comment]
@ofborg build rPackages.immunotation for @jbedo

**Comment by Kupac** [comment]
Ok, this won't work, the hash of hla6006a already changed

**Comment by b-rodrigues** [comment]
Stupid question: could we use an archived page for hla6006a? does the actual data of interest change or is it just the website ?

**Comment by Kupac** [comment]
That could be an option, actually. Normally it is retrieved once, at install time, so it's not that different here. Other possibility could be to retrieve it in .onLoad() but that would require some  more excessive patching.

**Comment by Kupac** [comment]
We could use an archive.org snapshot as a source. There are small changes from time to time, but these probably don't affect the list of valid geographical regions, only some count values, which are not needed by the script at this stage. However, it should be updated once in a while to a new snapshot. I'd prefer to move this whole connection stuff to .onLoad, like in many other packages. I don't see why not. It's just not very straightforward to do in nix.

https://web.archive.org/web/diff/20231207065757/20240205120933/www.allelefrequencies.net/hla6006a.asp

**Pull request closed without merging**
