### PR TITLE
alacritty: fix build on darwin

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
See: https://hydra.nixos.org/build/122547742

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg build alacritty

**Review by cole-h — CHANGES_REQUESTED** [review]
Ah, this is my bad, oops. I forgot that `Alacritty.app` is generated in the `postBuild` using a Makefile (which isn't called with the `--target` flag as `buildRustPackage` now uses). It only worked prior to merging https://github.com/NixOS/nixpkgs/pull/82342 because `releaseDir` was the same as `target/release`...

Maybe we could `sed` that flag into the Makefile, so there aren't two compilations happening? Either way, thanks for catching this.

(I forgot borg does actually build on Darwin if the submitter is a trusted user, which is why I pinged it to build above... oops x2.)

**Comment by marsam** [comment]
no worries :)

>Maybe we could sed that flag into the Makefile, so there aren't two compilations happening?

Thanks, this seems a better solution. 
I manually installed Alacritty.app because modifying the Makefile would get cumbersome

**Review by cole-h — APPROVED** [review]
A much more elegant solution than `sed`ing -- thanks! I had never really looked at the Makefile, so I guess it makes sense that this is relatively easy.

borg is happy, so I'm happy (assuming this works as expected on darwin).

```
[2 built, 76 copied (1050.6 MiB), 298.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/91198
1 package built:
alacritty
```

**Pull request merged**
