### PR TITLE
dolphinEmuMaster: 5.0-11109 -> 5.0-11288

### PR DESCRIPTION
**Pull request by Moredread**
###### Motivation for this change

Bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Moredread** [comment]
cc @MP2E @ashkitten

**Comment by Moredread** [comment]
I guess when reviewing it would make sense to update to the latest master. Feel free to push your update to this PR.

**Comment by ashkitten** [comment]
i'm of the mind that we should try to stay on the monthly updates (after a progress report) since those are more thoroughly tested for the progress report and are less likely to break. it hasn't even been 3 weeks since the last update to this package, so unless there's some change you think is important to include then i think we should wait for the next progress report.

**Comment by Moredread** [comment]
@ashkitten sounds like a good policy, closing the PR

**Pull request closed without merging**
