### PR TITLE
[20.09] .github/workflows/editorconfig.yml: remove

### PR DESCRIPTION
**Pull request by zowoq**
Remove the editorconfig check from release-20.09.

cc @Mic92 @jonringer @worldofpeace

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]

**Comment by worldofpeace** [comment]
@zowoq Can you please explain why we have do this on release branches? I feel like that could get tiresome.

**Comment by jonringer** [comment]
since the normal backport process is to merge into master, should almost all cherry picks from master already be compliant to this? The only exception would be release-only affecting PRs, and even then I think having this isn't detrimental.

**Comment by zowoq** [comment]
Currently master isn't compliant with this check and there is a list of exceptions that also currently aren't checked, unless we're going to backport the change every time one of these errors is fixed I think having this on the release branch will get annoying very quickly.

I'm hoping to get the majority of this work done over the next couple of months so this shouldn't be an issue for the next release.

**Comment by jonringer** [comment]
I see, that sounds fine then.

**Pull request merged**
