### PR TITLE
[python-updates] minor updates (2024-09-29)

### LINKED ISSUE #347628: Update request: pydantic 2.8.2 → 2.9.2
- Package name: pydantic
- Latest released version: 2.9.2

- Current version on the unstable channel: 2.8.2
- Current version on the stable/release channel: 2.6.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@wd15 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by mweinelt**
We are refreshing the python package set in bulk in time before the freeze and the upcoming zero hydra failures campaign.

### CODE REVIEW

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/448.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/460.html

**Comment by fabaff** [comment]
@mweinelt, the `websockets` [update]([b685f4e](https://github.com/NixOS/nixpkgs/pull/345326/commits/b685f4eb538f17e055f0415599a823a64d9ab419)) could have some fallout. If you want to wrap this PR up quickly then please  remove it.

**Comment by mweinelt** [comment]
No need, the current staging-next cycle is ongoing, so we have some time.

**Comment by mweinelt** [comment]
New Python release dropped. :melting_face: 

https://docs.python.org/release/3.12.7/whatsnew/changelog.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/468.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/471.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/484.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/487.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/491.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/493.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/498.html

**Comment by mweinelt** [comment]
`nix-build pkgs/pkgs-lib/tests/default.nix` fails `test-format-yamlAtoms`:

```
--- /build/.attr-1x6zjlwynnphpbrp081y6p3m6wz9jgpsmk5rkz8h12vyp3a3v8nf   2024-10-12 03:11:24.808309896 +0000
+++ /nix/store/vjyhhpkvr6s4vkxkb0jkxbgppwlxaljp-test-format-yamlAtoms   1970-01-01 00:00:01.000000000 +0000
@@ -1,11 +1,11 @@
 attrs:
-  foo: null
+  foo:
 'false': false
 float: 3.141
 list:
-- null
-- null
-'null': null
+- 
+- 
+'null':
 path: /nix/store/xakpn1b34c5rrq97xnmqrmj2bpz2jfv9-formats.nix
 str: foo
 'true': true

Got different values than expected; diff above.
```

The representation of `null` values changed and they're now missing.

I tried reverting remarshal, we did not update pyyaml. No idea where this is failing.

**Comment by mweinelt** [comment]
Extracted the tomlkit/remarshal changes into a dedicated PR. Doing a final rebase and going for the merge.

**Comment by trofi** [comment]
Bisect says 24bf9c5de6f7e7fbc250dcaf7cc938de8743be71 `python3Packages.sphinx: 7.3.7 -> 7.4.7` broke `python3Packages.breathe` on `staging` as:

```
$ nix build --no-link -f. -L python3Packages.breathe
...
python3.12-breathe> =========================== short test summary info ============================
python3.12-breathe> FAILED tests/test_renderer.py::test_render_func - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_typedef - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_c_typedef - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_c_function_typedef - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_using_alias - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_const_func - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_lvalue_func - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_rvalue_func - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_const_lvalue_func - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_const_rvalue_func - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_variable_initializer - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_define_initializer - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> FAILED tests/test_renderer.py::test_render_define_no_initializer - TypeError: expected string or bytes-like object, got 'NoneType'
python3.12-breathe> ================= 13 failed, 8 passed, 1208 warnings in 9.26s ==================
```

**Pull request merged**
