### PR TITLE
upower: 0.99.17 → 0.99.19

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

https://gitlab.freedesktop.org/upower/upower/-/blob/v0.99.19/NEWS

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maxeaubrey** [comment]
Result of `nixpkgs-review pr 177033` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnome.gnome-documents</li>
    <li>pantheon.file-roller</li>
  </ul>
</details>
<details>
  <summary>85 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>chrome-gnome-shell</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-control-center</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cinnamon-session</li>
    <li>cinnamon.cinnamon-settings-daemon</li>
    <li>cinnamon.cjs</li>
    <li>clight</li>
    <li>dropbox-cli</li>
    <li>eiciel</li>
    <li>eolie</li>
    <li>gnome-console</li>
    <li>gnome-photos</li>
    <li>gnome.file-roller</li>
    <li>gnome.gnome-applets</li>
    <li>gnome.gnome-bluetooth</li>
    <li>gnome.gnome-books</li>
    <li>gnome.gnome-boxes</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-disk-utility</li>
    <li>gnome.gnome-flashback</li>
    <li>gnome.gnome-power-manager</li>
    <li>gnome.gnome-session</li>
    <li>gnome.gnome-settings-daemon</li>
    <li>gnome.gnome-settings-daemon338 (pantheon.gnome-settings-daemon)</li>
    <li>gnome.gnome-shell</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-tweaks</li>
    <li>gnome.gnome-user-share</li>
    <li>gnome.gpaste</li>
    <li>gnome.mutter</li>
    <li>gnome.mutter338 (pantheon.mutter)</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>mate.mate-applets</li>
    <li>mate.mate-power-manager</li>
    <li>mate.mate-tweak</li>
    <li>mixxx</li>
    <li>monitor</li>
    <li>nautilus-open-any-terminal</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.file-roller-contract</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-bluetooth</li>
    <li>pantheon.switchboard-plug-keyboard</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>phoc</li>
    <li>phosh</li>
    <li>power-profiles-daemon</li>
    <li>thermald</li>
    <li>tracker-miners</li>
    <li>upower</li>
    <li>vimix-gtk-themes</li>
    <li>waybar</li>
    <li>whitesur-gtk-theme</li>
    <li>wingpanel-indicator-ayatana</li>
    <li>xdg-desktop-portal-gtk</li>
    <li>xfce.xfce4-power-manager</li>
    <li>xfce.xfce4-settings</li>
    <li>xfce.xfce4-weather-plugin</li>
  </ul>
</details>

**Review by amaxine — APPROVED** [review]

**Comment by jtojnar** [comment]
@maxeaubrey What do you think about running the tests with `eatmydata` as [suggested upstream](https://gitlab.freedesktop.org/upower/upower/-/issues/195#note_1422813).

**Comment by maxeaubrey** [comment]
@jtojnar I'm speaking from a lack of familiarity with upower outside of using it, but - I guess it should be ok? If the expectation is that the tests can only run from tmpfs (or reasonably fast and idle disks, I haven't actually managed to get it to fail consistently when throwing it at my build machines), in theory I don't see using eatmydata to be as much of a departure from intention.

Would be nicer if the tests didn't rely on any of this, but I'm not eager to dive into trying to fix them 😅

**Comment by lorenz** [comment]
Could we backport this to 22.05? In 0.99.18 there is an important change regarding upower's polling behavior which fixes an up to 120 second delay displaying the correct battery state. Risk should be low as the API hasn't changed and we don't need to pull in the big refactor in 1.90.

**Pull request merged**
