### PR TITLE
tdesktop: 2.7.4 -> 2.7.5

### LINKED ISSUE #125533: [21.05] tdesktop: 2.7.4 -> 2.7.6 required to remove a segfault on voice message recording
**Describe the bug**
After updating from 20.09 to 21.05, tdesktop got bumped from 2.4.4 to 2.7.4, which segfaults while trying to record voice messages, currently unstable only has 2.7.4 as well, I guess a bump to 2.7.6 is required to fix the issue as per [https://github.com/telegramdesktop/tdesktop/issues/16365](https://github.com/telegramdesktop/tdesktop/issues/16365)

**To Reproduce**
1. Try to record a voice message
2. the application will hang
3. and segfault afterwards, generating a coredump visible from coredumpctl

**Expected behavior**
A voice message should start recording

**Screenshots**
photo_2021-06-03_18-49-46

**Additional context**

**Notify maintainers**
@udf 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.641.5237039cc1e (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05.641.5237039cc1e"`
 - channels(patjaw): `"nixos-unstable-21.05pre288911.65d6153aec8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: tdesktop
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes: https://github.com/NixOS/nixpkgs/issues/125533

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
cc @Keij0 can you test this? 

```
nix-shell -p nixpkgs-review --run nixpkgs-review pr 125538
./results/tdesktop/bin/tdesktop
```

**Comment by Keij0** [comment]
@jonringer is the sha256 correct in your patch? the previous version doesn't have sha256 prefix

**Review by stigtsp — CHANGES_REQUESTED** [review]
The PR title and commit message has the package name misspelled:

tdesktokp -> tdesktop

**Comment by Keij0** [comment]
(Sorry for being kinda noobish, this is my first issue reported and first time trying to work with nixpkgs)

**Comment by jonringer** [comment]
> @jonringer is the sha256 correct in your patch? the previous version doesn't have sha256 prefix

nix can accept 4 different hash formats. previous one was a base-32 sha256, the new one is a base-64 sri hash.

**Comment by Keij0** [comment]
> > @jonringer is the sha256 correct in your patch? the previous version doesn't have sha256 prefix
> 
> nix can accept 4 different hash formats. previous one was a base-32 sha256, the new one is a base-64 sri hash.

Thanks for clarification, I'm cloning nixpkgs, I will test it out and report back here

**Comment by jonringer** [comment]
@stigtsp done :)

**Comment by Keij0** [comment]
@jonringer build fails, attaching log

`builder for '/nix/store/h93lhzqh9i02jl85iijqrivv0wd317qz-telegram-desktop-2.7.5.drv' failed with exit code 1; last 10 log lines:
  [457/912] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/history/view/controls/history_view_voice_record_bar.cpp.o
  FAILED: Telegram/CMakeFiles/Telegram.dir/SourceFiles/history/view/controls/history_view_voice_record_bar.cpp.o 
  /nix/store/35pnk5kwi26m3ph2bc7dxwjnavpzl8cn-gcc-wrapper-10.3.0/bin/g++ -DDESKTOP_APP_DISABLE_CRASH_REPORTS -DDESKTOP_APP_USE_PACKAGED -DDESKTOP_APP_USE_PACKAGED_FONTS -DG_LOG_DOMAIN=\"Telegram\" -DLOTTIE_USE_CACHE -DLOT_BUILD -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WAYLANDCLIENT_LIB -DQT_WIDGETS_LIB -DQT_XKBCOMMON_SUPPORT_LIB -DTDESKTOP_API_HASH=d524b414d21f4d37f08684c1df41ac9c -DTDESKTOP_API_ID=611335 -DTDESKTOP_DISABLE_AUTOUPDATE -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop -ITelegram/Telegram_autogen/include -I../Telegram/SourceFiles -I../Telegram/lib_spellcheck -I../Telegram/ThirdParty/tgcalls -I../Telegram/ThirdParty/libtgvoip -I../Telegram/lib_base -I../Telegram/lib_rpl -I../Telegram/lib_crl -ITelegram/gen -I../Telegram/lib_tl -ITelegram/lib_ui/gen -I../Telegram/lib_ui -I../Telegram/lib_ui/emoji_suggestions -I../Telegram/lib_lottie -I../Telegram/lib_webrtc -I../Telegram/lib_storage -I../Telegram/lib_qr -I../Telegram/ThirdParty/QR/cpp -I../Telegram/lib_webview -I../Telegram/SourceFiles/payments -I../Telegram/ThirdParty/rlottie/inc -I../Telegram/ThirdParty/statusnotifieritem -isystem ../Telegram/ThirdParty/GSL/include -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtCore/5.15.2 -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtCore/5.15.2/QtCore -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtGui/5.15.2 -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtGui/5.15.2/QtGui -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtXkbCommonSupport/5.15.2 -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtXkbCommonSupport/5.15.2/QtXkbCommonSupport -isystem /nix/store/rawg7zhdyc0ca3mw5adrbja4kfcgn8vp-qtwayland-5.15.2-dev/include/QtWaylandClient/5.15.2 -isystem /nix/store/rawg7zhdyc0ca3mw5adrbja4kfcgn8vp-qtwayland-5.15.2-dev/include/QtWaylandClient/5.15.2/QtWaylandClient -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtCore -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/./mkspecs/linux-g++ -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtGui -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtWidgets -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtNetwork -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtDBus -isystem /nix/store/6ypchrs5rjvkrqlzm5xi8iss2s4akjgd-qtbase-5.15.2-dev/include/QtXkbCommonSupport -isystem /nix/store/rawg7zhdyc0ca3mw5adrbja4kfcgn8vp-qtwayland-5.15.2-dev/include/QtWaylandClient -isystem /nix/store/95jq4b7sxq5k718yfp6gf7lhs1k0ccf4-tl-expected-unstable-2019-11-11/share -isystem /nix/store/d9zs9xg86lhqjqni0v8h2ibdrjb57fn4-glib-2.68.2-dev/include/glib-2.0 -isystem /nix/store/dcb3cyba5wl6qimv6vwdpbi0kg0g1nlb-glib-2.68.2/lib/glib-2.0/include -isystem /nix/store/ml5gsps86fgznfqriq9sr3i6ayk0sk0i-glibmm-2.64.5-dev/include/giomm-2.4 -isystem /nix/store/1ihcnyi7va2vql6wm9zlk7ssimhx5gbb-glibmm-2.64.5/lib/giomm-2.4/include -isystem /nix/store/ml5gsps86fgznfqriq9sr3i6ayk0sk0i-glibmm-2.64.5-dev/include/glibmm-2.4 -isystem /nix/store/1ihcnyi7va2vql6wm9zlk7ssimhx5gbb-glibmm-2.64.5/lib/glibmm-2.4/include -isystem /nix/store/jj7g9fz29y1ygram087c7np441daihvg-libsigc++-2.10.6/include/sigc++-2.0 -isystem /nix/store/jj7g9fz29y1ygram087c7np441daihvg-libsigc++-2.10.6/lib/sigc++-2.0/include -isystem /nix/store/d9zs9xg86lhqjqni0v8h2ibdrjb57fn4-glib-2.68.2-dev/include/gio-unix-2.0 -isystem /nix/store/1b2ahzbjq1fqnm7riz1a9s0w3rsnaysy-harfbuzz-2.8.0-dev/include/harfbuzz -isystem /nix/store/vsk1qc1na4izgz461vxkvn655yvarfr7-gtk+3-3.24.27-dev/include/gtk-3.0 -isystem /nix/store/x26skdnbygrryb189ghkk00f419vy9ci-atk-2.36.0-dev/include/atk-1.0 -isystem /nix/store/gp87jysb40b919z8s7ixcilwdsiyl0rp-cairo-1.16.0-dev/include/cairo -isystem /nix/store/qxak159dp4qrmvsck3kjkin4bszbr6ab-gdk-pixbuf-2.42.6-dev/include/gdk-pixbuf-2.0 -isystem /nix/store/c52730cidby7p2qwwq8cf91anqrni6lg-pango-1.48.4-dev/include/pango-1.0 -isystem /nix/store/amryzlagqsnql3wdnhvl43czf9334cwz-openal-soft-1.19.1/include/AL -isystem /nix/store/a5v6ahqg3br6l3v0jrvh9khqmxlh395a-webkitgtk-2.32.1-dev/include/webkitgtk-4.0 -isystem /nix/store/15pc94wg989gib883ngn7r772qjjmnay-libsoup-2.72.0-dev/include/libsoup-2.4 -isystem /nix/store/69ina81ww7rldl4xdqarx2lvghpnwijl-minizip-1.2.11/include/minizip -isystem /nix/store/jxsh87jv7v7xrg05xblryx184pm5jirz-libdbusmenu-qt-0.9.3+16/include/dbusmenu-qt5 -isystem /nix/store/2wf5w1crpvzfggdkn8kjgxqg5c3kiikp-kwayland-5.81.0-dev/include/KF5/KWayland/Client -isystem /nix/store/2wf5w1crpvzfggdkn8kjgxqg5c3kiikp-kwayland-5.81.0-dev/include/KF5 -O3 -DNDEBUG -fPIC -fno-strict-aliasing -pipe -Wall -W -Wno-unused-variable -Wno-unused-parameter -Wno-unused-function -Wno-switch -Wno-comment -Wno-unused-but-set-variable -Wno-missing-field-initializers -Wno-sign-compare -Wno-attributes -Wno-parentheses -Wno-stringop-overflow -Wno-maybe-uninitialized -Wno-error=class-memaccess -Wno-register -std=gnu++17 -Winvalid-pch -include /build/tdesktop-2.7.5-full/build/Telegram/CMakeFiles/Telegram.dir/cmake_pch.hxx -MD -MT Telegram/CMakeFiles/Telegram.dir/SourceFiles/history/view/controls/history_view_voice_record_bar.cpp.o -MF Telegram/CMakeFiles/Telegram.dir/SourceFiles/history/view/controls/history_view_voice_record_bar.cpp.o.d -o Telegram/CMakeFiles/Telegram.dir/SourceFiles/history/view/controls/history_view_voice_record_bar.cpp.o -c ../Telegram/SourceFiles/history/view/controls/history_view_voice_record_bar.cpp
  {standard input}: Assembler messages:
  {standard input}:2776: Warning: end of file not at end of a line; newline inserted
  {standard input}:3172: Error: no such instruction: `_zn3rpl7details17consumer_han'
  g++: fatal error: Terminated signal terminated program cc1plus
  compilation terminated.
  [459/912] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/history/view/controls/history_view_compose_controls.cpp.o
  ninja: build stopped: subcommand failed.
cannot build derivation '/nix/store/0sjw4p2s2i4pwnryhf6mg9sllcc6q7nm-review-shell.drv': 1 dependencies couldn't be built
error: build of '/nix/store/0sjw4p2s2i4pwnryhf6mg9sllcc6q7nm-review-shell.drv' failed

Link to currently reviewing PR:                                                                               
https://github.com/NixOS/nixpkgs/pull/125538

1 package failed to build:
tdesktop

`

I guess the upstream source is broken then?

**Comment by jonringer** [comment]
interesting, both I and ofborg were able to build it.

**Comment by Keij0** [comment]
What could cause it then? I just ran that review command inside of nixpkgs, I don't see a reason for it to fail that way and the tarball should be verified after download, right?

**Comment by jonringer** [comment]
> I don't see a reason for it to fail that way and the tarball should be verified after download, right?

correct, or else you would get a sha mismatch

>  I'll close everything and try to build again, brb

I mean, it looks like it was a concurrency issue. doing `--core 1` for the build should make it more deterministic.

**Comment by udf** [comment]
Builds fine over here, however 2.7.5 does not fix the crash in #125533

**Comment by jonringer** [comment]
> Builds fine over here, however 2.7.5 does not fix the crash in #125533

:(, but thanks for testing

**Comment by Keij0** [comment]
It built for me too after killing firefox and all the things I had running on my machine, but 2.7.5 doesn't fix the issue mentioned in my issue. It seems to occur in the same place, but I can't confirm that until I get the package to build with debug symbols, someone on IRC recommended me to build it like this

`nix-build -E 'with import <nixpkgs> {}; enableDebugging tdesktop'`

but that nix-build command fails like this

`error: anonymous function at /nix/store/idviyxp663y0sn6zprl3bjqjy1lm9mly-nixos-21.05.641.5237039cc1e/nixos/pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix:1:1 called with unexpected argument 'stdenv', at /nix/store/idviyxp663y0sn6zprl3bjqjy1lm9mly-nixos-21.05.641.5237039cc1e/nixos/lib/customisation.nix:69:16`

So I can't really confirm my findings with full confidence.

**Comment by Keij0** [comment]
Could someone help building a package with debug symbols? Maybe the issue lies in tg_owt? It was last bumped with 2.7.1 and it's weird in general, because it's pinned to a commit hash and doesn't have any release tags.

**Comment by Keij0** [comment]
I think that this is the source of our issue, seems our tdesktop build is linked to ffmpeg-4.4 [tg issue link](https://github.com/telegramdesktop/tdesktop/issues/16217)

[here's a patch from gentoo](https://github.com/gentoo/gentoo/commit/1c91884873968997be4b0c954169d04dc839f1db)

Thanks to a friend who uses guix for finding the issue

**Comment by jonringer** [comment]
IIRC, ffmpeg <4.4 have open CVEs against them, so they should be motivated to support it.

**Comment by Keij0** [comment]
That patch is for 2.7.4, maybe we could try it?

**Comment by jonringer** [comment]
sure

**Comment by Keij0** [comment]
Should I open a separate PR for that patch or how should we approach it?

**Comment by jonringer** [comment]
I added it. Try again

**Comment by Keij0** [comment]
Okay, brb, gotta build it :D

**Comment by jonringer** [comment]
I kept around the version bump, I can also revert the bump if the patch fixes the issue

**Comment by udf** [comment]
> I added it. Try again

Seems the patch creates a patch file instead of patching the file, I think you meant to point to https://raw.githubusercontent.com/gentoo/gentoo/1c91884873968997be4b0c954169d04dc839f1db/net-im/telegram-desktop/files/tdesktop-2.7.4-voice-crash.patch instead of the commit that adds that file.

**Comment by jonringer** [comment]
yea.... fun

**Comment by jonringer** [comment]
updated patches, and got rid of all the warnings about missing transitive dependencies of `libsoup`

**Comment by udf** [comment]
Just tested, it doesn't crash for me anymore

**Comment by Keij0** [comment]
Okay, I'll build it again and test for myself as well

**Comment by jonringer** [comment]
should i revert the bump? it's a pre-release, but the changelog looks like they fixed a few other crashes

**Comment by Keij0** [comment]
I can confirm this patch fixes voice message recording, but it seems now that stickers aren't working, but it might just be my internet, @udf could you check this out please?

**Comment by Keij0** [comment]
My bad, I was launching the application through .telegram-desktop-wrapped, not telegram-desktop and that was causing issues, I can confirm it's fully working now.

**Comment by Keij0** [comment]
Thanks for being here guys, it was a blast working with you all :sparkles:

**Pull request merged**
