### PR TITLE
remove some packages marked broken for over 1.5 years

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
Partially automated with this script:
```bash
#!/usr/bin/env nix-shell
#!nix-shell -i bash -p jq -p git
set -eux
cutoffTS=$(date -d "now - 18 months" +%s)
unset NIX_PATH
NIXPKGS_ALLOW_BROKEN=1 NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-env -f . -qaP --json --meta > all_pkgs.json
# idk what meta.position does here, but attrsets.nix is _probably_ wrong
grep -vE '(haskell-modules|node-packages|lib/attrsets.nix)' $(nix-build ./test.nix) | while read f; do
    file=$(cut -d" " -f2 <<< "$f")
    attr=$(cut -d" " -f1 <<< "$f")
    ln=$(grep -n 'broken.*=.*$' "$file" | cut -d: -f1)
    # echo "$file: $ln"
    # [[ "$ln" == "" ]] && continue
    blame=$(git blame -p "$file" -L "$ln,$ln" | tee)
    commit=$(echo "$blame" | head -n1 | cut -d" " -f1)
    author=$(grep -oP "(?<=^author ).*(?=$)" <<< "$blame")
    authorDate=$(date -d "@$(grep -oP "(?<=^author-time ).*(?=$)" <<< "$blame")" --rfc-3339=date)
    commitTS=$(grep -oP "(?<=^committer-time ).*(?=$)" <<< "$blame")
    [[ "$commitTS" > "$cutoffTS" ]] && continue
    commitDate=$(date -d @"$commitTS" --rfc-3339=date)
    git rm "$file"
    git commit -m "$attr: remove after being marked broken for over 18 months

It was marked in commit $commit by $author on $authorDate (commited on $commitDate)"
done
```
###### Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mindavi — APPROVED** [review]
Thanks for the cleanup! Indeed no need to add throws here 👍

**Comment by ajs124** [comment]
idk, tbh. I don't think we backport things like this and the packages are already marked as broken on there, so it's not like they present a security risk or anything.

**Comment by Mindavi** [comment]
Sure

**Comment by klemensn** [comment]
https://github.com/NixOS/nixpkgs/pull/179011 shows that this PR removed `default.nix` but left `*.patch` files behind for `syncthing-gtk`.

There might be more left-overs from this incomplete PR.

**Comment by ajs124** [comment]
oops. Thanks for noticing that. I skimmed to other commits again and I _think_ I got all the files in those.

**Comment by klemensn** [comment]
> oops. Thanks for noticing that. I skimmed to other commits again and I _think_ I got all the files in those.

Assuming that a package removal means removing its `default.nix`, it looks like syncthing-gtk's patch was the only left-over according to this snippet run against latest master:

```
$ git ls-files $(gh pr diff 175961 | lsdiff --strip=1 -i '*/default.nix' | rev | cut -d/ -f2- | rev)
pkgs/applications/networking/syncthing-gtk/paths.patch
```

**Comment by ajs124** [comment]
sadly it isn't always that easy. some packages don't come from/with a `default.nix`, see e.g. 6da0d2b7a642aaa643b002083e5ed1558ecbe335

**Pull request merged**
