### PR TITLE
Delete ruby 1.8

### PR DESCRIPTION
**Pull request by zimbatm**
Ruby 1.8 is now deprecated by everyone and has probably some untracked security issues.

This is a proposal, I don't think that it's doing our user a favour to support it but I understand that it can be a hard decision.

### CODE REVIEW

**Comment by nbp** [comment]
cc @garbas , any idea who should be asked for Ruby questions?

**Comment by garbas** [comment]
i think @cstrahan would be the right person to judge on this one. looks to me we could easily deprecate 1.8

**Comment by matthiasbeyer** [comment]
:+1: I I'm just a normal user though I would support the removal of ruby 1.8. We should do this on unstable only, though, and clearly note this in the release notes of the next release.

**Comment by garbas** [comment]
@zimbatm could you add a line to [changelog](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-unstable.xml)?

**Comment by zimbatm** [comment]
@garbas like this ^ ?

not sure why Travis is unhappy

**Comment by vcunat** [comment]
> not sure why Travis is unhappy

It's some directvnc problem with xlibs, which certainly seems unrelated.

**Comment by garbas** [comment]
@zimbatm tnx ... merged

**Pull request closed without merging**
