### PR TITLE
osmium-tool: 1.12.1 → 1.13.0, libosmium: 2.15.6 → 2.16.0, pyosmium: 3.0.1 → 3.1.0

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change
* osmium-tool: [1.13.0 changelog](https://github.com/osmcode/osmium-tool/releases/tag/v1.13.0)
  * > Now depends on **libosmium 2.16.0** or greater
  * > Has support for PBF **lz4** compression which is enabled by default if the library is found
* libosmium: [2.16.0 changelog](https://github.com/osmcode/libosmium/releases/tag/v2.16.0)
  * Add `-DINSTALL_GDALCPP:BOOL=ON` cmake flag to install `gdalcpp.hpp`
* pyosmium: [3.1.0 changelog](https://github.com/osmcode/pyosmium/releases/tag/v3.1.0)

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
  - osm2pgsql
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by das-g** [comment]
Result of `nixpkgs-review pr 108813` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>libosmium</li>
    <li>osm2pgsql</li>
    <li>osmium-tool</li>
    <li>python37Packages.pyosmium</li>
    <li>python38Packages.pyosmium</li>
    <li>python39Packages.pyosmium</li>
  </ul>
</details>

**Review by das-g — COMMENTED** [review]
> - [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Does it?

While unicode arrows (`→`) might look nicer, [`CONTRIBUTING.md`](https://github.com/NixOS/nixpkgs/blob/9ff1aa8d2ce70fa2c4417eab055d182623f98429/.github/CONTRIBUTING.md#submitting-changes) seems to mandate `->` in commit messages for version changes.

https://github.com/NixOS/nixpkgs/blob/9ff1aa8d2ce70fa2c4417eab055d182623f98429/.github/CONTRIBUTING.md#L14-L20

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108813` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
6 packages built:
</summary>
<ul>
<li>libosmium</li>
<li>osm2pgsql</li>
<li>osmium-tool</li>
<li>python37Packages.pyosmium</li>
<li>python38Packages.pyosmium</li>
<li>python39Packages.pyosmium</li>
</ul>
</details>

**Comment by sikmir** [comment]
> > * [x]  Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
> 
> Does it?
> 
> While unicode arrows (`→`) might look nicer, [`CONTRIBUTING.md`](https://github.com/NixOS/nixpkgs/blob/9ff1aa8d2ce70fa2c4417eab055d182623f98429/.github/CONTRIBUTING.md#submitting-changes) seems to mandate `->` in commit messages for version changes.
> 
> https://github.com/NixOS/nixpkgs/blob/9ff1aa8d2ce70fa2c4417eab055d182623f98429/.github/CONTRIBUTING.md#L14-L20

As far as I see, `→` is used quite often last time (among others by core committers):
```sh
$ git log --all --grep='→' | wc -l
15228
```
So, I guess it's acceptable de facto. @FRidh, @jonringer, @jtojnar what do you think?

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108813` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
6 packages built:
</summary>
<ul>
<li>libosmium</li>
<li>osm2pgsql</li>
<li>osmium-tool</li>
<li>python37Packages.pyosmium</li>
<li>python38Packages.pyosmium</li>
<li>python39Packages.pyosmium</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
Ofborg picked the updates up correctly.

**Pull request merged**
