### PR TITLE
nixos/scion: use RuntimeDirectory instead of StateDirectory

### PR DESCRIPTION
**Pull request by MatthewCroughan**
## Description of changes

This PR doesn't cause any issues for existing deployments if there are any. It's just a re-routing of where the runtime files are placed, to prevent keeping them persistent on the disk.

It was wrong to use `StateDirectory` to keep the `scion-control` and `scion-router` runtime databases on disk for the next run. I observed that doing this means a reboot, or power outage can corrupt the temporary runtime databases for the next service start, leading `scion ping` and other functionality to stop working permanently, since those files are not managed in an atomic manner by the golang code.

This is supposed to be stateless, which is what `RuntimeDirectory` provides, as those dirs get cleaned up on each service start, leaving nothing behind.

You can see in the following `ls` that I've ended up with a 0 byte file `control.trust.db-wal`:

```
[root@t480:/var/lib/private]# ls -lah scion-*
scion-control:
total 178K
drwxr-xr-x 2 scion-control scion   11 Jun 28 18:02 .
drwx------ 9 root          root     9 Jun 28 18:01 ..
-rw-r--r-- 1 scion-control scion  16K Jun 28 18:02 control.beacon.db
-rw-r--r-- 1 scion-control scion  32K Jun 28 18:12 control.beacon.db-shm
-rw-r--r-- 1 scion-control scion  89K Jun 28 18:12 control.beacon.db-wal
-rw-r--r-- 1 scion-control scion  48K Jun 28 18:02 control.path.db
-rw-r--r-- 1 scion-control scion  32K Jun 28 18:13 control.path.db-shm
-rw-r--r-- 1 scion-control scion 974K Jun 28 18:13 control.path.db-wal
-rw-r--r-- 1 scion-control scion 572K Jun 28 18:02 control.trust.db
-rw-r--r-- 1 scion-control scion  32K Jun 28 18:02 control.trust.db-shm
-rw-r--r-- 1 scion-control scion    0 Jun 28 18:02 control.trust.db-wal
```

Which leads to the following failure log on the next service start:

```
Jun 28 17:55:50 t480 scion-control[1960]: 2024-06-28 16:55:50.093142+0000        ERROR               beaconing/writer.go:324        Unable to register segment        {"debug_id": "49dcfbb8", "seg_type": "down", "addr": "17-ffaa:0:1108,CS", "err": {"msg": "resolving SVC address", "cause": "context deadline exceeded", "stacktrace": ["github.com/scionproto/scion/pkg/grpc.(*QUICDialer).Dial github.com/scionproto/scion/pkg/grpc/dialer.go:148", "github.com/scionproto/scion/control/beaconing/grpc.Registrar.RegisterSegment github.com/scionproto/scion/control/beaconing/grpc/register.go:34", "github.com/scionproto/scion/control/beaconing.(*remoteWriter).startSendSegReg.func1 github.com/scionproto/scion/control/beaconing/writer.go:323"]}}
Jun 28 17:55:50 t480 scion-control[1960]: 2024-06-28 16:55:50.093271+0000        ERROR               beaconing/writer.go:110        Unable to register        {"debug_id": "49dcfbb8", "seg_type": "down", "err": {"msg": "no beacons registered", "stacktrace": ["github.com/scionproto/scion/control/beaconing.(*RemoteWriter).Write github.com/scionproto/scion/control/beaconing/writer.go:191", "github.com/scionproto/scion/control/beaconing.(*WriteScheduler).run github.com/scionproto/scion/control/beaconing/writer.go:124", "github.com/scionproto/scion/control/beaconing.(*WriteScheduler).Run github.com/scionproto/scion/control/beaconing/writer.go:109", "github.com/scionproto/scion/private/periodic.(*Runner).onTick github.com/scionproto/scion/private/periodic/periodic.go:213", "github.com/scionproto/scion/private/periodic.(*Runner).runLoop github.com/scionproto/scion/private/periodic/periodic.go:195", "github.com/scionproto/scion/private/periodic.StartWithMetrics.func1 github.com/scionproto/scion/private/periodic/periodic.go:145"], "candidates": 1}}
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
Please add the rationale to the commit message, otherwise it's not clear from the history why that change is made.

**Comment by MatthewCroughan** [comment]
Done @fricklerhandwerk

**Comment by MatthewCroughan** [comment]
According to @matzf this is not supposed to happen, but this kind of error happens in the context of SCIONLab Vagrant deployments all the time, and is documented here https://docs.scionlab.org/content/faq/troubleshooting.html#border-router-fails-to-start

For now, we should keep it as a `RuntimeDirectory` in systemd until it can be demonstrated safe and to not lead to these issues, at which point switching back to `StateDirectory` is simple.

Matzf suggested it could be an issue with service start order, or waiting for interfaces/IPs. But that 0 byte file has me wondering if it's not just an issue in how the upstream code read/writes the files on disk.

**Comment by matzf** [comment]
To clarify, my telediagnosis referred to the somewhat generic error messages in the control service log that you shared (here and in the chat) that indicate some connectivity issues during the SCION path discovery processes. Such failures of the underlying network can occur for any number of reasons; in SCIONLab, starting the router before establishing VPN connection is a particularly frequent case of such a connectivity problem.

Corrupt databases was not at all what I was referring to.
Furthermore, I'm not sure whether a 0 byte write-ahead-log "wal" file is (necessarily) a corrupt database. This could also "just" mean that there have not been any writes to the database since the last checkpoint.
While it's of course not impossible that the files do end up being corrupt, sqlite has an excellent track record for not creating invalid files even on a hard shutdown.
It's quite possible that the information contained in the database is entirely valid, but leads to different behavior which in your case leads to the path discovery not working. Good that you found a workaround for your problem by removing these cache files, even if this might not address the actual cause.

**Comment by MatthewCroughan** [comment]
Continuing conversation in the scion dev channel, there was a mention that there are two sqlite implementations that can be switched between as documented here https://docs.scion.org/en/latest/dev/build.html#options

The two options are "real sqlite from c sources" and "pure golang sqlite". The latter is in use by default and could be less reliable than the C sqlite, leading to the above issues.

So I'm experimenting and testing both implementations to see if this issue still occurs.

**Pull request merged**
