### PR TITLE
kitty: 0.10.1 -> 0.11.2

### PR DESCRIPTION
**Pull request by dtzWill**
Version bump!

https://sw.kovidgoyal.net/kitty/changelog.html

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

In order to test on my 18.03-based NixOS machine I had to also pull in glibcLocales from master;
this is the same issue we're seeing everywhere but here instead of warning causes error.

### CODE REVIEW

**Comment by dtzWill** [comment]
Functionality testing by someone familiar with this would be appreciated!

**Comment by dtzWill** [comment]
cc @jlesquembre

**Comment by jlesquembre** [comment]
@dtzWill tested it with nixos-unstable and it looks good. Thanks!

**Comment by dtzWill** [comment]
Great, thank you!

**Pull request merged**
