### PR TITLE
plex-media-player: 2.40.0.1007 -> 2.55.0.1069 + update script

### PR DESCRIPTION
**Pull request by B4dM4n**
###### Motivation for this change

In the hope that the update process for the `plex-media-player` stays the same as in the last iterations, the update script should make the `fix one hash per build` process much faster.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @kylewlacy

### CODE REVIEW

**Review by kylewlacy — APPROVED** [review]
LGTM! I tested this out with `nix-build -A plex-media-player` and it builds and runs great

(Also, this is my first time seeing an `updateScript` in a package, so for my own reference, this can be run with `nix-shell maintainers/scripts/update.nix --argstr package plex-media-player` within the nixpkgs repo)

**Comment by B4dM4n** [comment]
@kylewlacy `2.43.0.1015` is already out. Should I push the new version before this gets merged?

**Comment by kylewlacy** [comment]
Sure, I'd say go for another version bump

**Comment by B4dM4n** [comment]
Latest version is pushed.

**Review by kylewlacy — APPROVED** [review]
Latest version also looks good!

**Comment by solson** [comment]
Is this PR blocked on anything? I can't seem to build the current nixos-unstable version of this package.

**Comment by B4dM4n** [comment]
The build is currently blocked by #72384.

I'm currently experimenting with building this package with Qt 5.12 to get a working build.
It's not officially supported (see plexinc/plex-media-player#802), but working fine so far.
There are also less graphical glitches when running under wayland.

**Comment by B4dM4n** [comment]
@kylewlacy I pushed the latest upstream version which got released today. It sadly currently doesn't build on master due to the mentioned issue.

If anyone wants to try a Qt 5.12 build, I pushed a branch here:
[B4dM4n:plex-media-player-qt512](https://github.com/NixOS/nixpkgs/compare/master...B4dM4n:plex-media-player-qt512)
```
nix run -f https://github.com/B4dM4n/nixpkgs/archive/plex-media-player-qt512.tar.gz plex-media-player -c plexmediaplayer
```

**Comment by kylewlacy** [comment]
I don't have the ability to merge this PR

**Comment by colemickens** [comment]
This LGTM, thanks for doing it!

**Comment by B4dM4n** [comment]
The next version is out.

I needed to rebase onto master because `update-source-versions` wasn't working on the old branch anymore.

**Comment by johnpyp** [comment]
Any news on when this can be merged?

**Comment by B4dM4n** [comment]
The PR ist ready to be merged at any time.  I'm using the version in this branch via an overlay and there have been no issues so far.

Using the update script to keep track of the upstream releases is painless now and works really well.

Any idea who to ping to get this merged?

**Comment by kylewlacy** [comment]
Okay, so I was added to the NixOS GitHub org, but for some reason I'm still not able to merge this PR... I'm still completely in the dark on how to get this merged in

**Review by kylewlacy — APPROVED** [review]
LGTM

**Comment by Mic92** [comment]
I will have a look at it.

**Comment by Mic92** [comment]
Thanks for keeping this up to date.

**Pull request merged**
