### PR TITLE
zed-editor: 0.135.2 -> 0.136.2

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/zed-industries/zed/releases/tag/v0.136.2

cc @jansol @niklaskorz 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Currently, it fails to build with:

```
...
   Compiling regex-syntax v0.8.2
...skipping...
  running cd "/build/source/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-f8fa9dd3486cd27f/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="/nix/store/9b>

  --- stderr
  thread 'main' panicked at /build/cargo-vendor-dir/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:



  Error configuring OpenSSL build:
      Command: cd "/build/source/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-f8fa9dd3486cd27f/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="/nix/sto>
      Failed to execute: No such file or directory (os error 2)
```

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 313886` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 313886` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 313886` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> Currently, it fails to build with:

Apparently, `perl` is now needed to build openssl.
I added it to `nativeBuildInputs` and the build now succeeds.

**Comment by GaetanLepage** [comment]
The application runs fine on my system.
I simply get an error printed in the terminal warning about the auto-update:
```
[2024-05-23T10:02:20+02:00 ERROR auto_update] auto-update failed: error:error deserializing release
```

I don't think that this is too important.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 313886` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by jansol** [comment]
```console
error: builder for '/nix/store/gf5hnwkm36d8r4l77nz3i8bz2v1fy6fj-zed-0.136.2.drv' failed with exit code 101;
       last 10 log lines:
       > assertion failed: workspace.left_dock().read(cx).is_open()
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       >
       >
       > failures:
       >     zed::tests::test_open_paths_action
       >
       > test result: FAILED. 16 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out; finished in 1.04s
       >
       > error: test failed, to rerun pass `--bin Zed`
       For full logs, run 'nix-store -l /nix/store/gf5hnwkm36d8r4l77nz3i8bz2v1fy6fj-zed-0.136.2.drv'.
```

There's also *a lot* of error messages from passing tests (mainly about not finding svg files for icons and sqlite data insertions?)

**Comment by GaetanLepage** [comment]
> There's also _a lot_ of error messages from passing tests (mainly about not finding svg files for icons and sqlite data insertions?)

What is this snippet ? Doesn't `zed-editor` build on your hardware ?

**Comment by jansol** [comment]
Yeah, that was from trying to build this PR branch with `nix build github:GaetanLepage/nixpkgs/zed#zed-editor` on ubuntu.

**Comment by GaetanLepage** [comment]
> Yeah, that was from trying to build this PR branch with `nix build github:GaetanLepage/nixpkgs/zed#zed-editor` on ubuntu.

It builds fine on my side, I do get the svg uncritical errors.

**Comment by jansol** [comment]
Yeah it's probably some nix-on-not-nixos thing. I vaguely remember running into issue with that with earlier versions too?

**Comment by GaetanLepage** [comment]
Any blocker on this then ?

**Comment by GaetanLepage** [comment]
@ofborg build zed-editor

**Review by supermarin — COMMENTED** [review]
I think you can remove these, was able to build 0.135.2 locally without skipped tests

https://github.com/NixOS/nixpkgs/pull/313886/files#diff-f0279d993d02b9d6008752569726b84fa84ed7a350cd032324ffdd87e2ffb610L129-L135

**Comment by supermarin** [comment]
@GaetanLepage I'm seeing the openssl error on nixos unstable

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 313886` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> I think you can remove these, was able to build 0.135.2 locally without skipped tests

Indeed, works fine :)

**Comment by GaetanLepage** [comment]
> @GaetanLepage I'm seeing the openssl error on nixos unstable

You mean that the package is currently broken on `nixos-unstable` ?

**Comment by supermarin** [comment]
@GaetanLepage ok builds now with `perl` in `nativeBuildInputs`!

**Comment by drupol** [comment]
It's failing on ci/x86_64-linux

**Comment by supermarin** [comment]
> > @GaetanLepage I'm seeing the openssl error on nixos unstable
> 
> You mean that the package is currently broken on `nixos-unstable` ?

I'm running a parallel flake locally to build Zed off of HEAD and seen the same error, so thought I should report until it's properly resolved.

**Comment by supermarin** [comment]
@GaetanLepage looks like some unit tests failed on ci?

**Comment by jansol** [comment]
That's the same test that failed for me on ubuntu -- which curiously enough I'm not getting on nixos-unstable.

**Comment by GaetanLepage** [comment]
> That's the same test that failed for me on ubuntu -- which curiously enough I'm not getting on nixos-unstable.

Indeed, although it builds fine on all my NixOS systems, it seems to fail in both Hydra and non-NixOS hosts... No idea why.
Maybe we should just disable that test.

**Comment by GaetanLepage** [comment]
> Indeed, although it builds fine on all my NixOS systems, it seems to fail in both Hydra and non-NixOS hosts... No idea why.

Actually, I was able to build it just fine on an Ubuntu host.

**Comment by jansol** [comment]
Yeah if it's flaky let's just disable it for now and move on.

**Comment by GaetanLepage** [comment]
> Yeah if it's flaky let's just disable it for now and move on.

Sure. Done.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 313886` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Review by supermarin — APPROVED** [review]

**Pull request merged**
