### PR TITLE
phrasendrescher: 1.0 -> 1.2.2b

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were done:

- built on NixOS
- ran `/nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/bin/pd -h` got 0 exit code
- ran `/nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/bin/pd -h` and found version 1.2.2b
- found 1.2.2b with grep in /nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b
- found 1.2.2b in filename of file in /nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b

cc @bjornfor

### CODE REVIEW

**Comment by Mic92** [comment]
I assume `b` stands for beta.

**Comment by ryantm** [comment]
@mic92 I don't know for sure, but maybe not because there is also a c version http://leidecker.info/projects/phrasendrescher/index.shtml
https://repology.org/metapackage/phrasendrescher/versions

**Comment by Mic92** [comment]
Ok. then it is `openssl` versioning style.

**Comment by Mic92** [comment]
@GrahamcOfBorg build phrasendrescher

**Comment by Mic92** [comment]
That looks fishy:


```console
$ /nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/bin/pd
phrasen|drescher 1.2.2b - the passphrase cracker
Copyright (C) 2008 Nico Leidecker; http://www.leidecker.info
Usage: /nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/bin/pd plugin [options] credentials
Please choose a plugin first or use -h for more help
Available plugins:
cannot open plugin directory /nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/lib/phrasendrescher: No such file or directory
Set the plugin directory in the environment variable PD_PLUGINS if required.
$ find /nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/
/nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/
/nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/share
/nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/share/man
/nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/share/man/man1
/nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/share/man/man1/pd.1.gz
/nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/bin
/nix/store/sifsd5n9sni7d35b32w3n8xm44yg56dd-phrasendrescher-1.2.2b/bin/pd
```

**Comment by samueldr** [comment]
@ryantm, @Mic92 

Right, it looks fishy, took a look at the build, there was a big warning:

```
#########################################################
#  not building plugins                                 #
#  (use --with-plugins if you want to build plugins)    #
#########################################################
``` 

```
diff --git a/pkgs/tools/security/phrasendrescher/default.nix b/pkgs/tools/security/phrasendrescher/default.nix
index 9fbeb3541ca..189190ab0bf 100644
--- a/pkgs/tools/security/phrasendrescher/default.nix
+++ b/pkgs/tools/security/phrasendrescher/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, fetchurl, openssl }:
+{ stdenv, fetchurl, openssl, libssh2, gpgme }:
 stdenv.mkDerivation rec {
   name = "phrasendrescher-${version}";
@@ -9,7 +9,9 @@ stdenv.mkDerivation rec {
     sha256 = "0bkiy9dlc1rqicl7g5sbfhgqlyqms4s66lcawwhhbl9d60y72ghs";
   };
-  buildInputs = [ openssl ];
+  buildInputs = [ openssl libssh2 gpgme ];
+
+  configureFlags = "--with-plugins";
   meta = with stdenv.lib; {
     description = "Cracking tool that finds passphrases of SSH keys";

```

It seems to run better after doing that.

```
~/tmp/nixpkgs/nixpkgs-36661 $ result/bin/pd
phrasen|drescher 1.2.2b - the passphrase cracker
Copyright (C) 2008 Nico Leidecker; http://www.leidecker.info

Usage: result/bin/pd plugin [options] credentials
Please choose a plugin first or use -h for more help
Available plugins:
  http-raw  ssh  enc-file  pkey  mssql

Set the plugin directory in the environment variable PD_PLUGINS if required.
```

**Comment by Mic92** [comment]
@samueldr you can update this pull request then.

**Comment by samueldr** [comment]
@GrahamcOfBorg build phrasendrescher

**Comment by samueldr** [comment]
And now with darwin issues. Will look into it later.

**Comment by ryantm** [comment]
Closing in favor of @r-ryantm doing these.

**Comment by samueldr** [comment]
This one will need a manual intervention; it's not as simple as updating the version + hash.

**Pull request closed without merging**
