### PR TITLE
nixos/ipfs: Add option to disable local port scanning for ipfs daemon

### PR DESCRIPTION
**Pull request by seppeljordan**
###### Motivation for this change

Hi, some hosting services really don't like port scanning. Unfortunately ipfs does this by default. This patch introduces a new option that disables this behavior.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by srhb — CHANGES_REQUESTED** [review]
I suggest this phrasing for the first paragraph:

> Whether to enable local discovery for the ipfs daemon. This will allow ipfs to scan ports on your local network. Some hosting services will ban you if you do this.

For the second paragraph, can you expand on what this means? It's not clear to me whether this means that I'd have to manually take action on some of the files in the dataDir.

**Comment by srhb** [comment]
(Essentially, the second paragraph should explain *what* the user should do in order to change the option after initializing ipfs, at the very least.)

**Comment by seppeljordan** [comment]
@srhb thanks for your feedback. i'll change the phrasing, because I also like yours better.  Also, I found a way to get around the issue mentioned in the second paragraph.

**Review by srhb — APPROVED** [review]

**Comment by srhb** [comment]
Great, this is a much better solution. :)

**Pull request merged**
