### PR TITLE
nodejs: backport all including v18

### PR DESCRIPTION
**Pull request by wmertens**
Adds v18 to 21.11 but does not remove v17 so as not to break dependencies.

Done by copying the master version of the nodejs directory, so other versions get point updates too.

### CODE REVIEW

**Comment by wmertens** [comment]
tests pass but I changed the base to staging without cherrypicking so now I force pushed to just have the one commit

**Comment by wmertens** [comment]
I'm merging since we know it works on prod and test pass.

**Comment by wmertens** [comment]
:man_facepalming: I merged into the wrong branch, I see. @vcunat am I correct in assuming that merging into staging-21.11 isn't that bad, and I can just force-push to remove the merge? I'll create a new PR against staging-next-21.11/

**Comment by vcunat** [comment]
Why do you even want it?  `release-21.11..staging-next-21.11` is empty and `staging-next-21.11..staging-21.11` only contains this change.

**Comment by wmertens** [comment]
I thought that if there's a lot of packages that change, you first have to put it in the staging branch. We're using stable for production and would like to start using nodejs v18...

**Comment by vcunat** [comment]
Yes.  Merging to `staging-21.11` was the right thing to do, I believe.  That's why I don't understand why you write that you pushed to a wrong branch and want to undo that.

**Comment by wmertens** [comment]
Ah ok. It's because i saw that the last time it got merged to release-21.11 it was staging-next-21.11 that was merged.

**Comment by vcunat** [comment]
That's also correct.  Here's a figure: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy  (For stable it's the same, just with "21.11" in the names of the branches.)

**Comment by wmertens** [comment]
Aaah, TIL! I was reading Contributing.md and that wasn't clear. Thank you and sorry for disturbing :)

**Comment by wmertens** [comment]
@vcunat actually - what is the schedule for merging staging into release eventually?

**Comment by vcunat** [comment]
There's normally no schedule; exception is during ZHF for the upcoming release but it's not really possible to plan the timing well.

So when Hydra is free enough, someone will choose to do the iteration &ndash; trigger the rebuilds, wait and check for regressions, wait for necessary fixes and eventually merge.  Chat: https://matrix.to/#/#staging:nixos.org

**Pull request merged**
