### PR TITLE
Update nitrokey-app towards 1.4.2

### PR DESCRIPTION
**Pull request by andigi89**
updated to the current version 1.4.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andigi89** [comment]
I have updated it to 1.4.2. - the nix-build was succesfull as well as starting the nitrokey-app on ./results/bin

**Review by teto — CHANGES_REQUESTED** [review]
you must change the sha256 otherwise it is still installing the older version.

**Comment by andigi89** [comment]
@teto  Well, how can I update/change the sha256?  On my test building it all went done

**Comment by teto** [comment]
just replace one figure by another (a 3 into a 2 for instance) and try to buld it. It should error out and give you the new hash.

**Comment by andigi89** [comment]
@teto - hopefully the new sha256 should work

**Comment by mweinelt** [comment]
Please reconsider your commit message wrt. CONTRIBUTING.md. Also squash your commits together, it's still a single change.

https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

**Review by andigi89 — COMMENTED** [review]
Hopefully done

**Comment by mweinelt** [comment]
No visible change.

**Comment by KaiHa** [comment]
Hello @andigi89, I have created an PR with an update of the nitrokey-app (see #108319).  Thank you for making me aware that an update was overdue.

**Comment by teto** [comment]
you could have force-pushed your branch instead of creating a new PR instead of losing comment records.

**Pull request closed without merging**
