### PR TITLE
tzdata: Use hard- instead of symbol-linking

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

Upstream software parses ${tzdata}/share/zoneinfo files.
Because of the symbolic posix link pointing to the local dir, the upstream software parses the contents of the zoneinfo directory multiple times because it follows symlinks and an error occurs because of this.
This PR changes the posix symlink to a hardlink to have a normal directory for posix like Fedora does.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
I notice that 1f2228cdc10807ed3b7ee0888b5cc8b6800e87b3 changed from hard to soft links citing NAR issues. Is that relevant here?

**Comment by orivej** [comment]
> Because of the symbolic posix link pointing to the local dir, the upstream software parses the contents of the zoneinfo directory multiple times because it follows symlinks and an error occurs because of this.

What software? What error?

**Comment by ThomasMader** [comment]
> What software? What error?

The standard library of the D programming language called Phobos.
I already patched it to not follow symlinks (see https://github.com/ThomasMader/nixpkgs/commit/6e15600b065dfae9c30d6a946ed84b2ba7a334a4#diff-9da5b94b5c73489302d04c387fbbf0c9R91) but wanted to make sure that tzdata has a standard layout before going upstream.
In Commit https://github.com/NixOS/nixpkgs/commit/1f2228cdc10807ed3b7ee0888b5cc8b6800e87b3 is mentioned though that other distributions are using symlinking too.
If that is true this PR can be closed.

**Comment by orivej** [comment]
Ubuntu is using symlinking, but without loops. This is better: https://github.com/NixOS/nixpkgs/pull/31560/commits/e75d458f38fc31837aa4141dca314f27db9ee41d

**Comment by orivej** [comment]
I've pushed my fix to `staging`. GitHub should close this issue when it reaches `master`.

**Comment by orivej** [comment]
@FRidh Thank you, I was considering doing this myself.

**Comment by FRidh** [comment]
@orivej that was github; I merged staging into master.

**Comment by orivej** [comment]
@FRidh My bad, I did not expect staging to be merged to master so soon. But please, configure git with `git config --global merge.ff false` (and `git config --global pull.rebase true`), or at least use `git merge --no-ff` when merging `staging` into `master`, or it messes up the first-parent history and the history tree of the repository. (This effect was described [here](http://devblog.nestoria.com/post/98892582763/maintaining-a-consistent-linear-history-for-git) and [here](https://developer.atlassian.com/blog/2016/04/stop-foxtrots-now/).) I have almost recovered the proper history in fbbda41e05d89325baaefef6fd0a420a1c365d7e.

**Pull request closed without merging**
