### PR TITLE
lib/types: add `number`

### PR DESCRIPTION
**Pull request by ncfavier**
For numbers that can be ints or floats.

### CODE REVIEW

**Comment by infinisil** [comment]
How about instead extending the float type to also accept integers and automatically convert them to floats? Integers are a subset of floats after all

**Comment by pennae** [comment]
we should probably discourage the use of floats in nixos modules due to inaccuracies like https://github.com/NixOS/nix/issues/5733. any float with enough significant digits (more than six) *will* be mutilated, and that can't be a good thing for modules

**Comment by roberth** [comment]
`number` seems too precise. To me the most natural kind of number to be the default kind of number would be the natural numbers, extended with 0: non-negative numbers. How about `numeric`?

If we're going to accept floats, might as well accept the ~complex num~ quaternions ;)

> Integers are a subset of floats after all

64-bit integers are not a subset of 64-bit floats though. This makes the conversion leaky, and we shouldn't do it.

For a real solution (pun not intended) we should add arbitrary precision numbers to Nix. Would be nice not to have float quirks but support all of JSON nonetheless.

**Comment by ncfavier** [comment]
> How about instead extending the float type to also accept integers and automatically convert them to floats? Integers are a subset of floats after all

Had that in mind too, it's probably better. We can add a check to warn/throw on leaky conversions.

The other option is to make `float` accept ints, *without* converting. Strictly speaking it breaks the contract, but practically speaking, would anyone care? As far as I can tell, ints quack like floats except for `isFloat`.

> the natural numbers, extended with 0

Blocked. /j

**Comment by infinisil** [comment]
How about just using `number = either int float`?

**Comment by ncfavier** [comment]
So far the option I'm leaning towards is to make `float`'s check `x: isInt x || isFloat x` (and rename `numbers` to `floats`). Does anyone strongly oppose that?

**Comment by ncfavier** [comment]
Actually yes, me. I don't like having a type of floats that's not a type of floats.

A new type is fine, all that's left is to bikeshed over the name.

I don't think `numeric` says anything different than `number` (if anything we should prefer nouns over adjectives), and I don't think it's reasonable to worry about Nix getting support for numbers outside of ℝ, so I'm still happy with the current state of this PR.

**Comment by ncfavier** [comment]
> How about just using `number = either int float`?

This has ever so slightly different semantics: `mkMerge [ 1 1.0 ]` would fail with `either int float`, but succeed with the current thing.

I think we want it to succeed?

**Comment by roberth** [comment]
> > How about just using `number = either int float`?
> 
> This has ever so slightly different semantics: `mkMerge [ 1 1.0 ]` would fail with `either int float`, but succeed with the current thing.
> 
> I think we want it to succeed?

In JSON these would be different, but in JavaScript they wouldn't.

I think for a `type` that normally preserves the float/int runtime type, it would be surprising for it to ignore that runtime type and make an arbitrary choice.

Comparing floats is a bad idea in the first place, so perhaps we should disallow the merging of float definitions. We might allow ints to be compared, but a partial equivalence relation is perhaps even more surprising than no equivalence at all.

**Comment by ncfavier** [comment]
Ok, `either int float` it is.

**Comment by roberth** [comment]
Could you document the type in `nixos/doc/manual/development/option-types.section.md`?

**Comment by ncfavier** [comment]
Done. I also reorganised things a bit to remove the "Value types" category which is not really a concept.

**Comment by ncfavier** [comment]
Anything left to do here?

**Review by roberth — APPROVED** [review]

**Comment by ncfavier** [comment]
Done, hopefully people can decide for themselves whether the precision loss is acceptable (I suspect it's okay in most cases).

**Review by pennae — APPROVED** [review]

**Review by infinisil — APPROVED** [review]
Looking good!

**Pull request merged**
