### PR TITLE
pythonPackages.fs: fix to make it work on Python3

### PR DESCRIPTION
**Pull request by DamienCassou**
pyfilesystem is supposed to work on Python3 https://github.com/PyFilesystem/pyfilesystem/issues/246

### CODE REVIEW

**Comment by FRidh** [comment]
Looking at the comment I disabled it because of a `SyntaxError`. I don't remember where that error occurred, whether it was in the library or in the tests. If you choose to enable the package for all versions then do please add a slightly more detailed comment than my current one.

**Comment by DamienCassou** [comment]
@FRidh which comment are you referring to? Because my PR removes your comment regarding python3. I also don't get any SyntaxError.

**Comment by FRidh** [comment]
If you enable tests and build with Python 3.5 you get
```
running install tests
E
======================================================================
ERROR: fs (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: fs
Traceback (most recent call last):
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-python3.5-fs-0.5.4.drv-0/fs-0.5.4/fs/__init__.py", line 22, in <module>
    from fs import errors
  File "/tmp/nix-build-python3.5-fs-0.5.4.drv-0/fs-0.5.4/fs/errors.py", line 220
    except ResourceNotFoundError, e:
                                ^
SyntaxError: invalid syntax


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
When importing the package `__init__.py` is run which fails because a module that it loads is not compatible with Python 3.x. This particular problem is easy to fix though, but should be done upstream.

**Comment by willmcgugan** [comment]
How have you installed fs? 2to3 should have fixed that.

**Comment by FRidh** [comment]
We build and install wheels. While the exact steps are slightly different it's basically
`pip setup.py bdist_wheel`
and
`pip install *.whl --no-index --prefix=$out --no-cache`

I have no experience in using six like this, but I saw it is done by adding an argument to `setup()` that 2to3 should be used. Apparently this is being ignored.

**Comment by FRidh** [comment]
@domenkozar any experience with 2to3? setuptools issue perhaps?

**Comment by domenkozar** [comment]
It's probably picking up tests in source code instead of $out

**Comment by FRidh** [comment]
2to3 is run since I can perform the specific import without errors, so it indeed has to do with how we run the tests.

**Comment by FRidh** [comment]
With `${python.interpreter} -m unittest discover -s $out/${python.sitePackages}/fs` I got another weird error. So instead of using unittest I tested with py.test. This test runner was able to find and run most of the tests, but still quite a lot failed. Quite some failed with:
`E       TypeError: a bytes-like object is required, not 'str'`
Then there were some resource specific issues which are to be expected. I think at this point it makes sense to keep the tests disabled for this package.

**Comment by FRidh** [comment]
`fs` is now build for all Python versions, see c44176237af93f4497aaec8e4588ff2e896b0df4

**Pull request closed without merging**
