### PR TITLE
make-derivation: install all outputs

### LINKED ISSUE #24717: Missing man pages for packages with multiple outputs
## Issue description

For packages with multiple outputs the default meta.outputsToInstall is `[ "out" ]` which won't install any documents/man pages required by this. On NixOS this is resolved using the man module as shown in the link below:

  https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/man.nix#L27

On other platforms such as Linux or Darwin, this NixOS option doesn't trigger and the meta.outputsToInstall defaults to `["out"]` which means missing man pages for any package that uses multiple outputs to separate its man pages.

This can be fixed by modifying the meta.outputsToInstall attribute for the specific package, but I feel like this behavior isn't intended and is more of a bug. Patching each package where including manuals makes sense seems like a pain.

### Steps to reproduce

On Darwin/Linux:

    nix-env -i nix
    nix-env --help || man nix-env || echo "Nobody here but us chickens"

## Technical details

* System: darwin x86_64
* Nix version: 1.11.8
* Nixpkgs version: 17.09pre105100.78adf1832f

### LINKED ISSUE #44144: zlib headers are not linked in ~/.nix-profile/include.
## Issue description

I wanted to build from source [`digest`][1], a Haskell package that depends on the usual `zlib` system library. I used `cabal` executable installed via `nix-env` _(from `cabal-install` package)_. I also installed `zlib` in the same fashion, which made the headers and binary library objects available somewhere in `/nix/store`.

As advised in [NixOS wiki][2], I set `export CPATH=~/.nix-profile/include; export LIBRARY_PATH=~/.nix-profile/lib`, but nevertheless `cabal` errored out:

    % cd ~/code/haskell-src/digest
    % cabal new-build
    Build profile: -w ghc-8.2.2 -O1
    In order, the following will be built (use -v for more details):
     - digest-0.0.1.2 (lib:digest) (configuration changed)
    Configuring digest-0.0.1.2...
    cabal: Missing dependency on a foreign library:
    * Missing (or bad) header file: zlib.h
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
    library file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
    If the header file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.

I dug in and discovered that there is no directory `~/.nix-profile/include` at all. I created it and manually simlinked `zlib` headers in. _(To be specific, there are two headers in `zlib`: `zlib.h` & `zconf.h`, and I linked both of them.)_ It solved the problem.

I wonder if these headers could be put in place by default.

### Steps to reproduce

Install `ghc`, `cabal-install`, `zlib`. Download the source for `digest`. Enter the `digest` source directory and say `cabal new-build`.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.56-1-lts, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixpkgs-18.09pre137268.63a865c403c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

[1]: https://hackage.haskell.org/package/digest
[2]: https://nixos.wiki/wiki/Nix_vs._Linux_Standard_Base

### PR DESCRIPTION
**Pull request by matthewbauer**
This confuses users too much and the old behavior to me seems
to have very little benefit. Since it only effect “declarative” installation,
it doesn’t seem helpful to not give every output available. In this case, users
want what would normally be included in the /zlib/ package, not just
one output. Individual packages can still specify what outputs to install
with ```meta.outputsToInstall```.

Fixes #44144
Fixes #24717

### CODE REVIEW

**Comment by matthewbauer** [comment]
@grahamcofborg eval

**Comment by FRidh** [comment]
I think this should be brought up on the mailing list.

**Comment by dezgeg** [comment]
This will regress closure sizes since now anything in `systemPackages` will install the dev outputs and other pointless stuff.

Regarding #44144, compiling outside nix-shell isn't really supported anyway.

As for having manpages installed by `nix-env`, I think nix-env should call into Nixpkgs `buildEnv` (or some new dedicated custom function) to decide what outputs to install. That way you could e.g. disable installation of manpages or info pages based on `~/.nixpkgs/.config.nix`.

**Comment by matthewbauer** [comment]
> This will regress closure sizes since now anything in systemPackages will install the dev outputs and other pointless stuff.

Doesn't systemPackages use ```pathsToLink``` though? I'd bet there is some increase in size but not a huge amount. We can definitely provide a global ```outputsToInstall``` in ```buildEnv``` that the NixOS environment can set to ```[ "out" ]```  or something else for this.

> As for having manpages installed by nix-env, I think nix-env should call into Nixpkgs buildEnv (or some new dedicated custom function) to decide what outputs to install. That way you could e.g. disable installation of manpages or info pages based on ~/.nixpkgs/.config.nix.

Yes, I think for most of us this would be the ideal solution. I still think we would want the default behavior of that function to be *install everything*. Most beginners to Nix will not understand multiple outputs, or pathsToLink, etc. They will just assume Nix(pkgs) does not provide that functionality. I want to make sure we can still provide good support for the ```imperative``` package installation style, even if most NixOS/Nixpkgs contributors are using something else.

**Comment by matthewbauer** [comment]
@GrahamcOfBorg eval

**Comment by dezgeg** [comment]
> Doesn't systemPackages use pathsToLink though? 

It uses `buildEnv` does respect `outputsToInstall`.

> I'd bet there is some increase in size but not a huge amount.

No, it's going to be hundreds of megs if some package's `.dev` pulls in GCC or glibc headers et al.

> I want to make sure we can still provide good support for the imperative package installation style,

For development nearly nothing currently supports that since setup hooks won't be run. And most likely isn't going to be fixed without a major redesign.

**Comment by matthewbauer** [comment]
> For development nearly nothing currently supports that since setup hooks won't be run. And most likely isn't going to be fixed without a major redesign.

This doesn't just apply to headers & libraries. Things like man pages are now frequently missing when someone decides to add a separate output for it. Not everyone is installing their packages through ```systemPackages```. I think it's a bad idea to expect everyone to be doing this, especially when it only is possible when you have root privileges or have set something up like home-manager.

I have added a commit to restore the buildEnv behavior. I agree that it makes sense to only use one output in buildEnv's case because it can be configured to add more outputs by the user.

**Comment by vcunat** [comment]
Ah, cross-link: https://github.com/NixOS/nixpkgs/commit/3342f717da7f660b4695f09034abc175a14fda24#commitcomment-29875048

**Comment by dezgeg** [comment]
If we need to do this without any changes to nix-env we could perhaps retcon `outputsToInstall` to make it only apply to nix-env (i.e. replace all other usages of that in nixpkgs with say, `propagatedUserEnvPackages` except the one in mk-derivation that sets it). But https://github.com/NixOS/nixpkgs/pull/44168#issuecomment-408596701 is still more preferable.

**Comment by matthewbauer** [comment]
> If we need to do this without any changes to nix-env we could perhaps retcon outputsToInstall to make it only apply to nix-env (i.e. replace all other usages of that in nixpkgs with say, propagatedUserEnvPackages except the one in mk-derivation that sets it).

s/propagatedUserEnvPackages/propagatedUserEnvPkgs/

The only usage I found was in buildenv.pl. I would be interested in whether there are any others. Do you think it makes sense to leave the outputsToInstall uses in packages the same?

> But #44168 (comment) is still more preferable.

It's definitely preferable, but could take a long time. The goal for me is to find some solution for #24717 before 18.09 release. If someone wants to step up and create a PR to Nix to use a custom buildEnv, that would be great but I am not counting on it.

Because @vcunat is assigned #24717, I kind of want to see what he thinks of this PR. After the update to have buildEnv calculate outputsToInstall itself, I am hoping it addresses some concerns. This whole thing has been an outstanding issue for too long IMO. I definitely get that things like ```dev```` don't really belong in the profile, but it doesn't seem to hurt too much either if they are.

**Comment by vcunat** [comment]
I haven't noticed extraneous (unused) outputs being downloaded; that would be a bug.

**Comment by matthewbauer** [comment]
Closing in favor of #35884 for now.

**Pull request closed without merging**
