### PR TITLE
gitbutler: 0.12.16 -> 0.13.2

### PR DESCRIPTION
**Pull request by Daholli**
https://github.com/gitbutlerapp/gitbutler/releases/tag/release%2F0.13.0
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Daholli** [comment]
@getchoo @techknowlogick I might need some help with this one, getting some build errors that I don't understand

```bash
building '/nix/store/l7cql4iy503yh5s0fh8vf4m2h04f5ai2-cargo-vendor-dir.drv'...
ln: failed to create symbolic link '/nix/store/l66xlgix7nfdv9p3sx3ck1qmyswyy8m7-cargo-vendor-dir/gix-attributes-0.22.5/akqzgppwk6adz7z32y3mhcm6fydlz9s7-gix-attributes-0.22.5': Permission denied
error: builder for '/nix/store/l7cql4iy503yh5s0fh8vf4m2h04f5ai2-cargo-vendor-dir.drv' failed with exit code 1;
       last 1 log lines:
       > ln: failed to create symbolic link '/nix/store/l66xlgix7nfdv9p3sx3ck1qmyswyy8m7-cargo-vendor-dir/gix-attributes-0.22.5/akqzgppwk6adz7z32y3mhcm6fydlz9s7-gix-attributes-0.22.5': Permission denied
       For full logs, run 'nix log /nix/store/l7cql4iy503yh5s0fh8vf4m2h04f5ai2-cargo-vendor-dir.drv'.
error: 1 dependencies of derivation '/nix/store/zc2qxzysj23f7ny4s4a7qa0309iv9yrq-gitbutler-0.13.0.drv' failed to build
```

heading to bed now, but would appreciate if you guys could give some idea where I should look

**Comment by getchoo** [comment]
It's https://github.com/NixOS/nixpkgs/issues/183344. This is the main reason the package hasn't been updated

Sometimes you are able to dedup these by patching, but I wasn't able to here last time I tried. We may need to wait on https://github.com/NixOS/nixpkgs/pull/282798

**Comment by tomodachi94** [comment]
Closes #335875

**Comment by Rots** [comment]
note that there are newer 0.13.x out already

**Comment by jtojnar** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/355366

**Pull request closed without merging**
