### PR TITLE
Update build phpPackages

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Fixed error:

./configure: line 5836: /usr/bin/file: No such file or directory

Clean-ip build configuration.

cc @etu @aanderse

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Izorkin** [comment]
Updated and rebased.
cc @etu @aanderse @Mic92

**Comment by ajs124** [comment]
For which package(s) does `./configure: line 5836: /usr/bin/file: No such file or directory` actually lead to a build error? Because I think I've seen that a whole bunch of times, but it always seemed like a harmless warning.

**Comment by Izorkin** [comment]
Only removed this warning. How this error affects the building I do not know.

**Comment by etu** [comment]
@Izorkin Sorry, but I don't see the point of this PR if it actually doesn't fix any real error.

If we have a package that is broken due to this, it's worth doing. But this touch so many places to get rid of something that seems to be harmless...

**Comment by Izorkin** [comment]
@etu reakky merge this commit? - https://github.com/NixOS/nixpkgs/pull/75033/commits/bb798c07e16d279c3590f864127509a5ef4201fb

**Comment by etu** [comment]
@Izorkin Since that commit only would add file as an additional dependency to the closure but not actually resolve any issue (that we know of)... I don't see the point of merging it.

**Comment by aanderse** [comment]
I agree with @etu that we should be solving a known problem when we increase closure size.

I would also point out that **many** packages mention a missing `file` executable, so conceivable this is an "issue" (or non issue) with 1 or more build systems. If this is an actual problem which requires solving we should look to solve it tree wide.

**Pull request closed without merging**
