### PR TITLE
maintainers: remove marsam

### PR DESCRIPTION
**Pull request by marsam**
I think that's it. I've been using NixOS for around 10 years, and contributing for +8 years, but it's time for me to say goodbye.

I'm deeply disappointed of the Foundation "neutral" stance in the Andur*l sponsorship.
Their lack of political will and honesty.
They could have resolved it early, but they choose to disregard the petition of nearly 250 contributors,
and (unintentionally?) invite alt-right trolls to brigade our forums.

To me, to my people, to the people in the Global South; this is not another "internet drama".
It's an existential threat.
I understand that it's difficult for people that benefit from Imperialism to acknowledge this,
but it was disheartening to see how Foundation has failed to meet our expectations.

Well, it has been fun 10 years. I met awesome people and I learned a lot.
If any of my contributions was useful to you, please donate to the Palestinian people 🇵🇸 .

Thank y'all!

P.S. I still care(d) for the 24.05 release, and I believe I'm leaving all the stuff that I maintain(ed) in good shape. However, consider all my packages as unmaintained from now on, and feel free to remove them.

### CODE REVIEW

**Review by tomfitzhenry — APPROVED** [review]

**Review by ulrikstrid — APPROVED** [review]
I really hate to see you leave the community, even though we have not interacted that much you've been one of the recognizable names in my ~4 years here.

With that said I reluctantly approve.

**Review by jonringer — APPROVED** [review]
I think you were the first merge a PR of mine to nixpkgs.

Wish you the best. Sad to see you go :(

EDIT: Since people feel that I'm not being sincere, here's some PRs from my early days of nixpkgs

- https://github.com/NixOS/nixpkgs/pull/62232
- https://github.com/NixOS/nixpkgs/pull/63778
- https://github.com/NixOS/nixpkgs/pull/66643
- https://github.com/NixOS/nixpkgs/pull/68703
- https://github.com/NixOS/nixpkgs/pull/67787

2019 was a very different time. Often wish I can go back, still just naive and innocent :(.....

**Comment by imincik** [comment]
@marsam , I am shocked and very sorry you leave. Thank you for all your work. Your contributions to Postgresql packages are very valuable to me. Sad day for me.

**Review by imincik — DISMISSED** [review]
I dream this would really change something.

**Comment by ereslibre** [comment]
@marsam We have crossed here and there. Thank you for all your contributions. I  wish things were different.

**Comment by drupol** [comment]
So sad to see you leave :(

**Comment by happysalada** [comment]
I salute your courage to take a stance and i thank you for the time youve given in helping me debug things that were beyond me and review my PRs.
No matter what happens next, you have had a positive impact on the world, you have made a difference.
Thank you !

**Review by Janik-Haag — APPROVED** [review]
i hope we will meet again.

**Comment by adamcstephens** [comment]
@marsam Thanks for your help when I was getting started.

**Comment by cbleslie** [comment]
Dang.

**Comment by cognivore** [comment]
> I'm deeply disappointed of the Foundation "neutral" stance in the Andur*l sponsorship.

As a European, I am also disappointed in "neutral" stance on that subject!
It should indeed be positive. I don't know if you or your family have lived under occupation, especially russian occupation, but believe me it's not fun and also, quite lethal.

Defense industry—for a while—shall not only be an ethical field to work in, but also something that should be a moral choice for anyone with sufficient competence.
Those who oppose collaborations with defense industry either deliberately, or inadvertently wish death and suffering upon those who live in countries neighbouring russia (and other Europeans).

Thank you for your contributions! I hope it won't take "the hard way" for you will understand that words and flowers can't deter crazy dictators.

**Comment by happysalada** [comment]
Oh wow, i am late to read this but can hardly believe it. You will be missed! I was really inspired by you, thank you again !

**Pull request merged**
