### PR TITLE
uiua: 0.8.0 -> 0.9.5

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

This PR bumps the version of the `uiua` package and its vscode extension.

This is a bigger update with quite a lot of new features and breaking changes
https://github.com/uiua-lang/uiua/releases/tag/0.9.0

There were some extra patch releases
https://github.com/uiua-lang/uiua/releases/tag/0.9.2
https://github.com/uiua-lang/uiua/releases/tag/0.9.3
https://github.com/uiua-lang/uiua/releases/tag/0.9.4
https://github.com/uiua-lang/uiua/releases/tag/0.9.5

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Defelo — APPROVED** [review]

**Comment by TomaSajt** [comment]
Converting to draft until the vscode extension gets a fix (already talked with the developer about it)

**Comment by cafkafk** [comment]
Result of `nixpkgs-review pr 291447` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>uiua</li>
    <li>uiua386</li>
    <li>vscode-extensions.uiua-lang.uiua-vscode</li>
  </ul>
</details>

**Review by cafkafk — APPROVED** [review]
Ty for the bump :)

**Comment by TomaSajt** [comment]
We should probably create an update.sh script and an update-extension.sh script.
update.sh would update the main package and then call update-extension.sh which would update the extension if needed.

**Comment by cafkafk** [comment]
> We should probably create an update.sh script and an update-extension.sh script. update.sh would update the main package and then call update-extension.sh which would update the extension if needed.

Would be cool :+1:

**Review by cafkafk — APPROVED** [review]

**Comment by TomaSajt** [comment]
Just checked it and running `nix-update -u uiua --commit` will only commit the `uiua` version change and not the extension. I'll look into it.
(btw, this is the only place currently in nixpkgs where a vscode-extension is updated in an update script)

**Comment by cafkafk** [comment]
Result of `nixpkgs-review pr 291447` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>uiua</li>
    <li>uiua386</li>
    <li>vscode-extensions.uiua-lang.uiua-vscode</li>
  </ul>
</details>

**Review by cafkafk — APPROVED** [review]

**Review by fpletz — APPROVED** [review]

**Pull request merged**
