### PR TITLE
dut: init at 0-unstable-2024-07-31

### PR DESCRIPTION
**Pull request by errnoh**
## Description of changes

Adding [dut](https://codeberg.org/201984/dut), a disk usage calculator for Linux

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by errnoh** [comment]
Updated version and changed commit message to date of commit instead of hash.

**Comment by errnoh** [comment]
updated PR to latest commit

**Comment by errnoh** [comment]
removed `with lib` from `meta` block

**Review by pbsds — COMMENTED** [review]
codeberg has a more adequate fetcher

<details>
<summary>My proposed patch</summary>

```patch
diff --git a/pkgs/by-name/du/dut/package.nix b/pkgs/by-name/du/dut/package.nix
index 731c7ae81fb3..9010aa1101ea 100644
--- a/pkgs/by-name/du/dut/package.nix
+++ b/pkgs/by-name/du/dut/package.nix
@@ -1,19 +1,19 @@
 {
   stdenv,
   lib,
-  fetchurl,
+  fetchFromGitea,
 }:

-let
-  rev = "041c6f26162c2286776fac246ddbda312da1563d";
-in
 stdenv.mkDerivation {
   pname = "dut";
   version = "0-unstable-2024-07-31";

-  src = fetchurl {
-    url = "https://codeberg.org/201984/dut/archive/${rev}.tar.gz";
-    sha256 = "sha256-4OAZfoftRNWXxm0vGlJOjNxUMvFzUKbfW0fYT2ne6Bk=";
+  src = fetchFromGitea {
+    domain = "codeberg.org";
+    owner = "201984";
+    repo = "dut";
+    rev = "041c6f26162c2286776fac246ddbda312da1563d";
+    hash = "sha256-YrBV5rG9rASI/5pwG3kcHoOvXBHhLJHvFFrvNhmGq2Y=";
   };

   installFlags = [
```

</details>

_How to apply (pick one):_

a. `curl -L "https://gist.github.com/pbsds/a7cfb4549c4e3a7334aae604d11cb874/raw" | git apply`
b. copy the patch above, run `git apply`, paste (typically `ctrl-shift-v`), press enter, then end the input with `ctrl-d`

**Review by pbsds — COMMENTED** [review]
please set meta.platforms, note that darwin currently fails

**Comment by errnoh** [comment]
Thanks for the review @pbsds, incorporated the suggestions.

Minor change to your suggestion: I marked the build `meta.broken` on darwin instead of using `meta.platforms` for it. This was mostly due to some earlier conversations I've had about use of `broken` vs `platforms` but if you insist on one over the another it's not a hill I need to die on :)

**Comment by pbsds** [comment]
Using `broken` is fine and IMO preferred in this case, but `meta.platforms` is still unset. Please consider `platforms = lib.platforms.all;`

`mkDerivation` does not set a default `meta.platforms` like most other builders.

**Comment by errnoh** [comment]
> `mkDerivation` does not set a default `meta.platforms` like most other builders.

Ohh, that's really useful information, thank you. Added `meta.platforms` now.

**Pull request merged**
