### PR TITLE
matrix-synapse: add e-mail delivery regression test

### PR DESCRIPTION
**Pull request by mguentner**
###### Motivation for this change

Adds a regression test for the behavior described in

* https://github.com/twisted/twisted/pull/1225#issuecomment-788560006
* https://github.com/matrix-org/synapse/issues/6211

Should be fixed with #132900

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

CC @Ma27 @fadenb @sumnerevans

### CODE REVIEW

**Comment by jonringer** [comment]
duplicate of #132900

please review the other PR

**Comment by mguentner** [comment]
Thanks, missed that one unfortunately. I will then drop the fixing commits and only leave the regression test in.

**Comment by mguentner** [comment]
Indeed, #132900 @ b07c07bf058da808a2dc77e6c1005b08c28c10be fixes this regression test.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
The test seems fine and btw passes when rebasing current nixpkgs master onto this branch :)

**Comment by mguentner** [comment]
@Ma27 Thanks for the review.

**Pull request merged**
