### PR TITLE
micro: 1.4.1 -> 2.0.3

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by petabyteboy** [comment]
CC @dtzWill

**Comment by Mic92** [comment]
@GrahamcOfBorg build micro

**Comment by petabyteboy** [comment]
micro has some Go dependencies starting from 2.0.0. It seems to be using Go modules, so I can use either buildGoModule or buildGoPackage. Is one of them preferred?

**Comment by Mic92** [comment]
There are different opinions on this. Some people prefer `buildGoModule` for beeing simpler to update. Other prefer `buildGoPackage` because sources are deduplicate across different packages in nix in the binary cache.

**Pull request merged**
