### PR TITLE
imagemagick: 7.1.0-60 -> 7.1.0-61

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Diff: https://github.com/ImageMagick/ImageMagick/compare/7.1.0-60...7.1.0-61

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 215031` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>imagemagick</li>
    <li>imagemagickBig</li>
    <li>imagemagick_light</li>
    <li>perlPackages.ImageMagick</li>
    <li>python310.pkgs.img2pdf</li>
    <li>python310.pkgs.wand</li>
    <li>python311.pkgs.img2pdf</li>
    <li>python311.pkgs.wand</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 215031` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>imagemagick</li>
    <li>imagemagickBig</li>
    <li>imagemagick_light</li>
    <li>perlPackages.ImageMagick</li>
    <li>python310.pkgs.img2pdf</li>
    <li>python310.pkgs.wand</li>
    <li>python311.pkgs.img2pdf</li>
    <li>python311.pkgs.wand</li>
  </ul>
</details>

**Comment by NickCao** [comment]
The nixpkgs-review result does not look quite right, ofborg says rebuild 100-500.

**Comment by dotlambda** [comment]
> The nixpkgs-review result does not look quite right, ofborg says rebuild 100-500.

Building all of them would take too long. I only built a select few.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 215031` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>autotrace</li>
    <li>calligra</li>
    <li>gimpPlugins.exposureBlend</li>
    <li>hackneyed</li>
    <li>invoice2data</li>
    <li>xmonad_log_applet</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>tests.php.overrideAttrs-preserves-enabled-extensions</li>
    <li>tests.php.withExtensions-enables-previously-disabled-extensions</li>
  </ul>
</details>
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>authenticator</li>
    <li>fluffychat</li>
    <li>gimp-with-plugins</li>
    <li>gimpPlugins.gmic</li>
    <li>gnome-decoder</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python311Packages.python-zbar</li>
    <li>utsushi</li>
  </ul>
</details>
<details>
  <summary>296 packages built:</summary>
  <ul>
    <li>abiword</li>
    <li>adapta-gtk-theme</li>
    <li>aether</li>
    <li>almanah</li>
    <li>arc-theme</li>
    <li>arx-libertatis</li>
    <li>asc-key-to-qr-code-gif</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>asymptote</li>
    <li>auto-multiple-choice</li>
    <li>awesome</li>
    <li>ayu-theme-gtk</li>
    <li>ballerburg</li>
    <li>beets (beetsPackages.beets ,beetsPackages.beets-stable)</li>
    <li>beets-unstable (beetsPackages.beets-unstable)</li>
    <li>betterlockscreen</li>
    <li>bisq-desktop</li>
    <li>blockhash</li>
    <li>bombono</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>brasero</li>
    <li>brasero-original</li>
    <li>calibre</li>
    <li>calibre-web</li>
    <li>capitaine-cursors</li>
    <li>cd-hit</li>
    <li>chafa</li>
    <li>ciano</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.iso-flags-png-320x420</li>
    <li>cinnamon.iso-flags-svg</li>
    <li>clevis</li>
    <li>cobang</li>
    <li>coreboot-configurator</li>
    <li>crypto-org-wallet</li>
    <li>cuneiform</li>
    <li>cyan</li>
    <li>dblatexFull</li>
    <li>deliantra-arch</li>
    <li>deliantra-maps</li>
    <li>deliantra-server</li>
    <li>deltachat-desktop</li>
    <li>denemo</li>
    <li>desktopToDarwinBundle</li>
    <li>devede</li>
    <li>diffoscope</li>
    <li>digikam</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>disorderfs</li>
    <li>dmtx-utils</li>
    <li>docbook2odf</li>
    <li>dvd-slideshow</li>
    <li>dvdauthor</li>
    <li>dvdbackup</li>
    <li>dvdstyler</li>
    <li>electrum</li>
    <li>electrum-grs</li>
    <li>electrum-ltc</li>
    <li>emojione</li>
    <li>enigma</li>
    <li>evolution</li>
    <li>evolution-ews</li>
    <li>evolutionWithPlugins</li>
    <li>exactaudiocopy</li>
    <li>faircamp</li>
    <li>fbida</li>
    <li>ffcast</li>
    <li>fgallery</li>
    <li>fim</li>
    <li>findimagedupes</li>
    <li>fontpreview</li>
    <li>foxtrotgps</li>
    <li>fped</li>
    <li>freedroid</li>
    <li>frescobaldi</li>
    <li>geeqie</li>
    <li>gimp (gimpPlugins.gimp)</li>
    <li>gimpPlugins.bimp</li>
    <li>gimpPlugins.farbfeld</li>
    <li>gimpPlugins.fourier</li>
    <li>gimpPlugins.gap</li>
    <li>gimpPlugins.gimplensfun</li>
    <li>gimpPlugins.lightning</li>
    <li>gimpPlugins.lqrPlugin</li>
    <li>gimpPlugins.resynthesizer</li>
    <li>gimpPlugins.texturize</li>
    <li>gimpPlugins.waveletSharpen</li>
    <li>gnome-browser-connector</li>
    <li>gnome-frog</li>
    <li>gnome-keysign</li>
    <li>gnome.gdm</li>
    <li>gnome.gnome-applets</li>
    <li>gnome.gnome-flashback</li>
    <li>gnome.gnome-initial-setup</li>
    <li>gnome.gnome-panel</li>
    <li>gnome.gnome-session</li>
    <li>gnome.gnome-shell</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-tweaks</li>
    <li>gnome.nixos-gsettings-overrides</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>goattracker</li>
    <li>goattracker-stereo</li>
    <li>gopro</li>
    <li>grafana-image-renderer</li>
    <li>grandorgue</li>
    <li>gscan2pdf</li>
    <li>haskellPackages.gi-vips</li>
    <li>haskellPackages.zbar</li>
    <li>healthchecks</li>
    <li>hello-wayland</li>
    <li>hikounomizu</li>
    <li>i3lock-fancy</li>
    <li>i3lock-pixeled</li>
    <li>ikiwiki</li>
    <li>imagemagick</li>
    <li>imagemagickBig</li>
    <li>imagemagick_light</li>
    <li>imaginary</li>
    <li>img2pdf (python310Packages.img2pdf)</li>
    <li>imgproxy</li>
    <li>inkscape</li>
    <li>inkscape-extensions.applytransforms</li>
    <li>inkscape-with-extensions</li>
    <li>iso-flags</li>
    <li>joplin</li>
    <li>k40-whisperer</li>
    <li>kabeljau</li>
    <li>rep (kakounePlugins.rep)</li>
    <li>kitty</li>
    <li>ledger-live-desktop</li>
    <li>libpst</li>
    <li>libsForQt5.libopenshot (plasma5Packages.libopenshot)</li>
    <li>libvisio2svg</li>
    <li>libwmf</li>
    <li>lilypond</li>
    <li>lilypond-unstable</li>
    <li>lilypond-unstable-with-fonts</li>
    <li>lilypond-with-fonts</li>
    <li>linux-doc</li>
    <li>lsix</li>
    <li>luksmeta</li>
    <li>manga-cli</li>
    <li>mars-mips</li>
    <li>mastodon</li>
    <li>mate.caja-extensions</li>
    <li>mate.caja-with-extensions</li>
    <li>mate.mate-utils</li>
    <li>mediainfo-gui</li>
    <li>megapixels</li>
    <li>mendeley</li>
    <li>mgba</li>
    <li>mojave-gtk-theme</li>
    <li>multilockscreen</li>
    <li>netbeans</li>
    <li>nip2</li>
    <li>nixos-icons</li>
    <li>noteshrink</li>
    <li>noto-fonts-emoji</li>
    <li>numix-cursor-theme</li>
    <li>numix-solarized-gtk-theme</li>
    <li>numworks-epsilon</li>
    <li>ocrmypdf (python310Packages.ocrmypdf)</li>
    <li>openshot-qt</li>
    <li>openspades</li>
    <li>optar</li>
    <li>otpclient</li>
    <li>pantheon.elementary-session-settings</li>
    <li>paperless-ngx</li>
    <li>paperwork</li>
    <li>pcb</li>
    <li>pdf2odt</li>
    <li>pdfarranger</li>
    <li>pdfmixtool</li>
    <li>pdfsandwich</li>
    <li>perl534Packages.BarcodeZBar</li>
    <li>perl534Packages.Gtk3ImageView</li>
    <li>perl534Packages.PerlMagick (perl534Packages.ImageMagick)</li>
    <li>perl534Packages.ImageOCRTesseract</li>
    <li>perl534Packages.LaTeXML</li>
    <li>perl536Packages.BarcodeZBar</li>
    <li>perl536Packages.Gtk3ImageView</li>
    <li>perl536Packages.PerlMagick (perl536Packages.ImageMagick)</li>
    <li>perl536Packages.ImageOCRTesseract</li>
    <li>perl536Packages.LaTeXML</li>
    <li>phash</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>photoflow</li>
    <li>php80Extensions.imagick</li>
    <li>php81Extensions.imagick</li>
    <li>php82Extensions.imagick</li>
    <li>pict-rs</li>
    <li>plata-theme</li>
    <li>playonlinux</li>
    <li>pop-gtk-theme</li>
    <li>portmod</li>
    <li>pqiv</li>
    <li>privacyidea</li>
    <li>protonvpn-gui</li>
    <li>pstoedit</li>
    <li>purple-discord</li>
    <li>python310Packages.diagrams</li>
    <li>python310Packages.inkex</li>
    <li>python310Packages.paperwork-backend</li>
    <li>python310Packages.paperwork-shell</li>
    <li>python310Packages.pyocr</li>
    <li>python310Packages.python-zbar</li>
    <li>python310Packages.pyvips</li>
    <li>python310Packages.pyvista</li>
    <li>pywal (python310Packages.pywal)</li>
    <li>python310Packages.pyzbar</li>
    <li>python310Packages.scooby</li>
    <li>python310Packages.segno</li>
    <li>python310Packages.sfepy</li>
    <li>python310Packages.wand</li>
    <li>python311Packages.diagrams</li>
    <li>python311Packages.img2pdf</li>
    <li>python311Packages.inkex</li>
    <li>python311Packages.ocrmypdf</li>
    <li>python311Packages.paperwork-backend</li>
    <li>python311Packages.paperwork-shell</li>
    <li>python311Packages.pyocr</li>
    <li>python311Packages.pyvips</li>
    <li>python311Packages.pywal</li>
    <li>python311Packages.pyzbar</li>
    <li>python311Packages.scooby</li>
    <li>python311Packages.segno</li>
    <li>python311Packages.wand</li>
    <li>recoverjpeg</li>
    <li>rhythmbox</li>
    <li>ripcord</li>
    <li>ripgrep-all</li>
    <li>rubyPackages.rmagick (rubyPackages_2_7.rmagick)</li>
    <li>rubyPackages.ruby-vips (rubyPackages_2_7.ruby-vips)</li>
    <li>rubyPackages_3_0.rmagick</li>
    <li>rubyPackages_3_0.ruby-vips</li>
    <li>rubyPackages_3_1.rmagick</li>
    <li>rubyPackages_3_1.ruby-vips</li>
    <li>sgtpuzzles</li>
    <li>sgtpuzzles-mobile</li>
    <li>shutter</li>
    <li>skribilo</li>
    <li>solfege</li>
    <li>soulseekqt</li>
    <li>sound-juicer</li>
    <li>sparrow</li>
    <li>spring</li>
    <li>springLobby</li>
    <li>stm32cubemx</li>
    <li>swaylock-fancy</li>
    <li>synfigstudio</li>
    <li>systeroid</li>
    <li>t-rec</li>
    <li>tang</li>
    <li>tango-icon-theme</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.ImageMagick</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.MagickWand</li>
    <li>tidal-hifi</li>
    <li>timelapse-deflicker</li>
    <li>tiv</li>
    <li>toppler</li>
    <li>ttygif</li>
    <li>tuxpaint</li>
    <li>twitter-color-emoji</li>
    <li>unigine-heaven</li>
    <li>unigine-sanctuary</li>
    <li>unigine-tropics</li>
    <li>unigine-valley</li>
    <li>urn-timer</li>
    <li>variety</li>
    <li>vcs</li>
    <li>vcv-rack</li>
    <li>vimix-gtk-themes</li>
    <li>vips</li>
    <li>vipsdisp</li>
    <li>whitesur-gtk-theme</li>
    <li>windowmaker</li>
    <li>winhelpcgi</li>
    <li>wl-color-picker</li>
    <li>wpa_supplicant_gui</li>
    <li>wpgtk</li>
    <li>wv</li>
    <li>xfce.xfce4-icon-theme</li>
    <li>xfce.xfce4-windowck-plugin</li>
    <li>xfig</li>
    <li>xscast</li>
    <li>yubikey-manager-qt</li>
    <li>yubikey-personalization-gui</li>
    <li>zbar</li>
  </ul>
</details>

**Pull request merged**
