### PR TITLE
bitwig-studio: 5.2.5 -> 5.2.7, fix Onset and Beat detection

### PR DESCRIPTION
**Pull request by polygon**
Update Bitwig to latest stable release 5.2.7.

I also noticed that Onset and Beat detection got broken in the 5.2-series. The fix is a wrapper script that launches Bitwig in a Bubblewrap environment. This is also part of this PR. All the details as to why this is required are in this discourse thread: https://discourse.nixos.org/t/fixing-permissions-when-program-copies-out-of-nix-store/56705

I've contacted the manufacturer but the interest was rather limited after I mentioned not using Ubuntu. Still, if this ever gets fixed upstream, we can just remove the wrapper again.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by bfortz — APPROVED** [review]

**Comment by bfortz** [comment]
Many thanks! I did not have time to look into that issue yet, but it is a great relief to see it fixed!

**Comment by drupol** [comment]
Thanks!

**Comment by camelpunch** [comment]
This change appears to have broken MIDI input for me. I'll take a look and see what I can find!

**Comment by camelpunch** [comment]
It's definitely bubblewrap and not the upgrade, because running the `-unwrapped` version makes MIDI work again.

It seems I can add `--dev-bind /dev /dev` to the `bwrap` invocation to make MIDI work. I'll get a PR ready.

**Pull request merged**
