### PR TITLE
python311Packages.pygame: 2.6.0 -> 2.6.1

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/pygame/pygame/releases/tag/2.6.1

cc @emilytrau 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
There is only a single test failing:
```
======================================================================
FAIL: test_queue (pygame.tests.mixer_test.ChannelTypeTest.test_queue)
Ensure the Channel.queue() works correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/xmp7j0nrmayqlvqaabhmdhwnw351wzl5-python3.12-pygame-2.6.1/lib/python3.12/site-packages/pygame/tests/mixer_test.py", line 861, in test_queue
    self.assertFalse(channel.get_busy())
AssertionError: True is not false

----------------------------------------------------------------------
Ran 75 tests in 11.849s

FAILED (failures=1, skipped=1, expected failures=2)
```

I am not sure about how to skip it.

**Comment by GaetanLepage** [comment]
> There is only a [single test failing](https://github.com/pygame/pygame/blob/b92c0da9d1b5eba6c813138790fc1ab6cea0252c/test/mixer_test.py#L861):
> 
> ```
> ======================================================================
> FAIL: test_queue (pygame.tests.mixer_test.ChannelTypeTest.test_queue)
> Ensure the Channel.queue() works correctly
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/nix/store/xmp7j0nrmayqlvqaabhmdhwnw351wzl5-python3.12-pygame-2.6.1/lib/python3.12/site-packages/pygame/tests/mixer_test.py", line 861, in test_queue
>     self.assertFalse(channel.get_busy())
> AssertionError: True is not false
> 
> ----------------------------------------------------------------------
> Ran 75 tests in 11.849s
> 
> FAILED (failures=1, skipped=1, expected failures=2)
> ```
> 
> I am not sure about how to skip it.

@illume I am sorry to ping you here, but would do you have an idea why this test could fail ?
Also, if I may, is there a simple way to skip this specific test ?
We run the test suite using `python -m pygame.tests`. I have tried to look at the tag system, but wasn't able to successfully skip this one.
Thank you in advance for your help :)

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 322423`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.pettingzoo</li>
    <li>python312Packages.pettingzoo.dist</li>
    <li>python312Packages.shimmy</li>
    <li>python312Packages.shimmy.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 58 packages built:</summary>
  <ul>
    <li>_20kly</li>
    <li>brutalmaze</li>
    <li>brutalmaze.dist</li>
    <li>endgame-singularity</li>
    <li>endgame-singularity.dist</li>
    <li>frescobaldi</li>
    <li>frescobaldi.dist</li>
    <li>minari (python312Packages.minari)</li>
    <li>minari.dist (python312Packages.minari.dist)</li>
    <li>pysolfc</li>
    <li>pysolfc.dist</li>
    <li>python311Packages.ale-py</li>
    <li>python311Packages.ale-py.dist</li>
    <li>python311Packages.gymnasium</li>
    <li>python311Packages.gymnasium.dist</li>
    <li>python311Packages.minari</li>
    <li>python311Packages.minari.dist</li>
    <li>python311Packages.pettingzoo</li>
    <li>python311Packages.pettingzoo.dist</li>
    <li>python311Packages.pyautogui</li>
    <li>python311Packages.pyautogui.dist</li>
    <li>python311Packages.pygame</li>
    <li>python311Packages.pygame.dist</li>
    <li>python311Packages.pygetwindow</li>
    <li>python311Packages.pygetwindow.dist</li>
    <li>python311Packages.pyrect</li>
    <li>python311Packages.pyrect.dist</li>
    <li>python311Packages.pytmx</li>
    <li>python311Packages.pytmx.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.stable-baselines3</li>
    <li>python311Packages.stable-baselines3.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.ale-py</li>
    <li>python312Packages.ale-py.dist</li>
    <li>python312Packages.gymnasium</li>
    <li>python312Packages.gymnasium.dist</li>
    <li>python312Packages.pyautogui</li>
    <li>python312Packages.pyautogui.dist</li>
    <li>python312Packages.pygame</li>
    <li>python312Packages.pygame.dist</li>
    <li>python312Packages.pygetwindow</li>
    <li>python312Packages.pygetwindow.dist</li>
    <li>python312Packages.pyrect</li>
    <li>python312Packages.pyrect.dist</li>
    <li>python312Packages.pytmx</li>
    <li>python312Packages.pytmx.dist</li>
    <li>python312Packages.skrl</li>
    <li>python312Packages.skrl.dist</li>
    <li>python312Packages.stable-baselines3</li>
    <li>python312Packages.stable-baselines3.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>video2midi</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.pettingzoo</li>
    <li>python312Packages.pettingzoo.dist</li>
    <li>python312Packages.shimmy</li>
    <li>python312Packages.shimmy.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 58 packages built:</summary>
  <ul>
    <li>_20kly</li>
    <li>brutalmaze</li>
    <li>brutalmaze.dist</li>
    <li>endgame-singularity</li>
    <li>endgame-singularity.dist</li>
    <li>frescobaldi</li>
    <li>frescobaldi.dist</li>
    <li>minari (python312Packages.minari)</li>
    <li>minari.dist (python312Packages.minari.dist)</li>
    <li>pysolfc</li>
    <li>pysolfc.dist</li>
    <li>python311Packages.ale-py</li>
    <li>python311Packages.ale-py.dist</li>
    <li>python311Packages.gymnasium</li>
    <li>python311Packages.gymnasium.dist</li>
    <li>python311Packages.minari</li>
    <li>python311Packages.minari.dist</li>
    <li>python311Packages.pettingzoo</li>
    <li>python311Packages.pettingzoo.dist</li>
    <li>python311Packages.pyautogui</li>
    <li>python311Packages.pyautogui.dist</li>
    <li>python311Packages.pygame</li>
    <li>python311Packages.pygame.dist</li>
    <li>python311Packages.pygetwindow</li>
    <li>python311Packages.pygetwindow.dist</li>
    <li>python311Packages.pyrect</li>
    <li>python311Packages.pyrect.dist</li>
    <li>python311Packages.pytmx</li>
    <li>python311Packages.pytmx.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.stable-baselines3</li>
    <li>python311Packages.stable-baselines3.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.ale-py</li>
    <li>python312Packages.ale-py.dist</li>
    <li>python312Packages.gymnasium</li>
    <li>python312Packages.gymnasium.dist</li>
    <li>python312Packages.pyautogui</li>
    <li>python312Packages.pyautogui.dist</li>
    <li>python312Packages.pygame</li>
    <li>python312Packages.pygame.dist</li>
    <li>python312Packages.pygetwindow</li>
    <li>python312Packages.pygetwindow.dist</li>
    <li>python312Packages.pyrect</li>
    <li>python312Packages.pyrect.dist</li>
    <li>python312Packages.pytmx</li>
    <li>python312Packages.pytmx.dist</li>
    <li>python312Packages.skrl</li>
    <li>python312Packages.skrl.dist</li>
    <li>python312Packages.stable-baselines3</li>
    <li>python312Packages.stable-baselines3.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>video2midi</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 12 packages marked as broken and skipped:</summary>
  <ul>
    <li>frescobaldi</li>
    <li>frescobaldi.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.pettingzoo</li>
    <li>python312Packages.pettingzoo.dist</li>
    <li>python312Packages.shimmy</li>
    <li>python312Packages.shimmy.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 19 packages built:</summary>
  <ul>
    <li>_20kly</li>
    <li>endgame-singularity</li>
    <li>endgame-singularity.dist</li>
    <li>pysolfc</li>
    <li>pysolfc.dist</li>
    <li>python311Packages.pettingzoo</li>
    <li>python311Packages.pettingzoo.dist</li>
    <li>python311Packages.pygame</li>
    <li>python311Packages.pygame.dist</li>
    <li>python311Packages.pygetwindow</li>
    <li>python311Packages.pygetwindow.dist</li>
    <li>python311Packages.pyrect</li>
    <li>python311Packages.pyrect.dist</li>
    <li>python312Packages.pygame</li>
    <li>python312Packages.pygame.dist</li>
    <li>python312Packages.pygetwindow</li>
    <li>python312Packages.pygetwindow.dist</li>
    <li>python312Packages.pyrect</li>
    <li>python312Packages.pyrect.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 12 packages marked as broken and skipped:</summary>
  <ul>
    <li>frescobaldi</li>
    <li>frescobaldi.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.pettingzoo</li>
    <li>python312Packages.pettingzoo.dist</li>
    <li>python312Packages.shimmy</li>
    <li>python312Packages.shimmy.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 19 packages built:</summary>
  <ul>
    <li>_20kly</li>
    <li>endgame-singularity</li>
    <li>endgame-singularity.dist</li>
    <li>pysolfc</li>
    <li>pysolfc.dist</li>
    <li>python311Packages.pettingzoo</li>
    <li>python311Packages.pettingzoo.dist</li>
    <li>python311Packages.pygame</li>
    <li>python311Packages.pygame.dist</li>
    <li>python311Packages.pygetwindow</li>
    <li>python311Packages.pygetwindow.dist</li>
    <li>python311Packages.pyrect</li>
    <li>python311Packages.pyrect.dist</li>
    <li>python312Packages.pygame</li>
    <li>python312Packages.pygame.dist</li>
    <li>python312Packages.pygetwindow</li>
    <li>python312Packages.pygetwindow.dist</li>
    <li>python312Packages.pyrect</li>
    <li>python312Packages.pyrect.dist</li>
  </ul>
</details>

**Comment by illume** [comment]
Looks like a timing issue. If the vm it runs on is busy this could happen. This test failure can be ignored.

I’ll take a note to make the test more lenient inside pygame.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
