### PR TITLE
bitwarden_rs: 1.17.0 -> 1.19.0

### PR DESCRIPTION
**Pull request by tobkratz**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

--- 
since #109737 was closed due to new release, this is the updated Version. 
cc @msteen as maintainer
cc @K900 @ryantm

### CODE REVIEW

**Comment by K900** [comment]
Builds and runs fine for me too.

**Review by SuperSandro2000 — COMMENTED** [review]
is that package licensed under gpl3Only or gpl3Plus?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112431` at ff122dd1 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/6cbb86e2789daf0af7adaf07d23eb6c0">bitwarden_rs-mysql</a></li></li>
    <li><a href="https://gist.github.com/a1dbfd7ddc068e3ce9080b43c987d661">bitwarden_rs-postgresql</a></li></li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/76b0c0bae18e5e8985261cc0e62a5d4d">bitwarden_rs</a></li> (bitwarden_rs-sqlite)</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/tools/security/bitwarden_rs/default.nix:43:5:
```
   |
43 |     license = licenses.gpl3;
   |     ^
```
</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112431` at ff122dd1 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/0613f20b6db85bb5ff72b2b161fb43cd">bitwarden_rs</a></li> (bitwarden_rs-sqlite)</li>
    <li><a href="https://gist.github.com/53896718a8a03cce30ffc8e774e6ddb6">bitwarden_rs-mysql</a></li></li>
    <li><a href="https://gist.github.com/5a2fa4a0d7623f22215ef264dd94abf1">bitwarden_rs-postgresql</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/tools/security/bitwarden_rs/default.nix:43:5:
```
   |
43 |     license = licenses.gpl3;
   |     ^
```
</li>
  </ul>
</details>

**Comment by ryantm** [comment]
@tklitschi thanks. The reason I closed it is that's what will cause r-ryantm to regenerate it, but no harm in manually doing it if you like to.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112431` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
</ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>bitwarden_rs (bitwarden_rs-sqlite)</li>
<li>bitwarden_rs-mysql</li>
<li>bitwarden_rs-postgresql</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112431` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>bitwarden_rs (bitwarden_rs-sqlite)</li>
<li>bitwarden_rs-mysql</li>
<li>bitwarden_rs-postgresql</li>
</ul>
</details>

**Comment by ajs124** [comment]
The nixos test is still broken. We can merge this without fixing it, as it's already broken on master, but would be nice if someone could look into that.

**Comment by tklitschi** [comment]
> The nixos test is still broken. We can merge this without fixing it, as it's already broken on master, but would be nice if someone could look into that.

I agree that fixing the test is necessary but should be done in another PR. Maybe I'll find some time next days to have a look.

**Comment by K900** [comment]
Anything stopping this from getting merged? There's some important fixes in this release and also 1.18.

**Comment by tklitschi** [comment]
Fixing the test takes more time than I expected. I also think upgrading now and fix the test later ist the best we can do. 
CC @SuperSandro2000

**Pull request merged**
