### PR TITLE
cc-wrapper: convert cc-wrapper.sh to cc-wrapper.nix

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

This commit converts cc-wrapper.sh into a .nix file consisting of one large string.  This will allow future commits to hoist conditionals out of bash code, into Nix code.  This allows to add or remove conditional code from the cc-wrapper **without causing rebuilds on platforms where the condition is false**.

Although this commit does not change the contents of the resulting `/nix/store/*-cc-wrapper.sh` it does unfortunately change the *hash* of that outpath, because Nix has way too many different hashing schemes.  If you write `./cc-wrapper.sh` you get one hashing scheme; if you write `''${builtins.readFile ./cc-wrapper.sh}''` you get a different one :(

## Also enables

- https://github.com/NixOS/nixpkgs/pull/271339

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build stdenv

^ mainly for darwin

**Review by malt3 — APPROVED** [review]
This looks good to me. But I have to admit that I'm probably not experienced enough to review this change, since it could have far reaching effects. So I would strongly advise for more experienced reviewers to have a look as well!

**Comment by malt3** [comment]
Is the close intentional? Is there anything I can do to help you out with this?

**Comment by katexochen** [comment]
@malt3 I think this PR was closed in in the light of https://github.com/NixOS/nixpkgs/issues/50105#issuecomment-1902682831. While not necessary, Adam chose to closed some of their open PRs (which is of cause okay if they like to do so). If you want to continue this work you could cherry-pick the changes and open a new PR.

**Pull request closed without merging**
