### PR TITLE
nixos/resolvconf: add `::1` as local dns resolver

### LINKED ISSUE #295802: `networking.resolvconf.useLocalResolver`: add `::1` as nameserver as well
### Describe the bug
`networking.resolvconf.useLocalResolver` only adds `127.0.0.1` as a nameserver if it is enabled. 

Could it be made to also set `::1` for IP6? If not, could you make an extra option for that?

This would avoid having to set this under `networking.nameservers` and thus spreading it out to several options or not using `networking.resolvconf.useLocalResolver` at all, which would be a shame in my opinion because the option clearly states what it does and thus is very approachable.

### Notify maintainers
@pallix @Janik-Haag 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0, NixOS, 24.05 (Uakari), 24.05pre596105.0ad13a683344`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Janik-Haag**
## Description of changes

closes #295802

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by picnoir** [comment]
I don't see major any footgun, but I might lack some context :thinking:

**Comment by Janik-Haag** [comment]
> I don't see major any footgun, but I might lack some context 🤔

I don't have more context then you other then asking hexa if it's fine and he said should be (and said how glibc handles it)

**Comment by picnoir** [comment]
Maybe we can stay on the safe side and guard that behind `networking.enableIPv6`?

**Comment by Janik-Haag** [comment]
@picnoir added it.

**Review by picnoir — APPROVED** [review]

**Comment by nbdd0121** [comment]
Nothing seems wrong initially, but apparently according to https://unix.stackexchange.com/questions/441440/how-to-specify-more-than-one-dns-in-resolvconf-conf, resolvconf.conf is a shell script so this means that the later option just overrides `127.0.0.1`.

If IPv6 is supported then the line needs to look like `name_servers='127.0.0.1 ::1'`

**Comment by xzfc** [comment]
This PR broke bind DNS resolving for me, please see #302228.

**Comment by flokli** [comment]
The fix for bind landed, we should still fix this PR here - @nbdd0121 would you mind opening a PR that adds it to the list, as you described?

**Comment by nbdd0121** [comment]
PR opened #302608. I haven't got time to test this, so it would be helpful if someone can test it @Schweber @xzfc .

**Comment by Janik-Haag** [comment]
Hey, sorry that I didn't handle the issue, I was very swamped with other things over the last few days and didn't really have time for nixpkgs :/

**Pull request merged**
