### PR TITLE
stdenv: `runPhase` returns status

### PR DESCRIPTION
**Pull request by mitchallain**
## Description of changes

The [relatively new `runPhase`](https://github.com/NixOS/nixpkgs/pull/230874/files) function in stdenv seems to be the best practice for building packages within a devshell, rather than manually executing sub-commands (e.g., `cmake .. && make`). This creates better consistency between dev workflow and the eventual realized derivation created by `nix build`. 

However, the `runPhase` command obscures any failures which take place within the individual build phases. To fix that problem, this PR installs an ERR trap handler which sets a return value to 1 on the first non-zero exit status. The `errtrace` shell option is also set to pass the new trap handler to any subsequent shell functions, command substitutions, and commands executed in a subshell environment.

My primary motivation was to allow better scripting around `runPhase`, e.g., run phases consecutively only if prior phases succeed, alert on errors. ~However it seems like this would facilitate a change to make `genericBuild` halt on any failed phases, which could be meaningful for CI pipelines. Happy to have that conversation here or in a separate forum. Also would appreciate links to any prior conversations about this behavior within stdenv genericBuild/runPhase.~

(Edit: I have since discovered that stdenv invokes genericBuild with `-e` shell option, causing immediate exit on failure when using e.g., `nix build`. Importantly, `set -e` is not a viable option in the devshell since it causes the devshell to exit on failure.)

I realize this PR has broad impact, despite being relatively low risk. In light of that and [Hyrum's Law](https://www.hyrumslaw.com/), I'm also open to making a flag or separate function so that the return value of `runPhase` is unaffected in current usage.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by FliegendeWurst — CHANGES_REQUESTED** [review]
Seems reasonable. But please target staging instead, changes to stdenv rebuild all packages.

**Review by philiptaron — APPROVED** [review]
This looks right to me and passes the stdenv tests.

**Review by RossComputerGuy — APPROVED** [review]

**Comment by trofi** [comment]
Bisect says 8e1442adb28858e61d893f943f844d0ce688f2e6 `Add return value to runPhase bash function in stdenv` broke `systemdMiniman` in `staging` as:

```
$ nix build --no-link -f. -L systemdMinimal
...
systemd-minimal> Found ninja-1.12.1 at /nix/store/6bmi344xip8d8cp8llbn31w0m0i7v9xr-ninja-1.12.1/bin/ninja
systemd-minimal> mesonConfigurePhase: enabled\ parallel\ building
systemd-minimal> substituteStream() in derivation systemd-minimal-256.8: WARNING: pattern SYSTEMD_CGROUP_AGENTS_PATH doesn't match anything in file 'config.h'
```

**Comment by philiptaron** [comment]
> Bisect says https://github.com/NixOS/nixpkgs/commit/8e1442adb28858e61d893f943f844d0ce688f2e6 `Add return value to runPhase bash function in stdenv` broke `systemdMinimal` in `staging`.

Indeed it did. I'm taking a look, but I welcome all sorts of help.

**Comment by philiptaron** [comment]
I can't see what command is failing! I added a bunch of `set -x` but no indications on what's actually causing the failure in the subshell.

**Comment by trofi** [comment]
If you throw `NIX_DEBUG` in it gives a hint:

```diff
--- a/pkgs/os-specific/linux/systemd/default.nix
+++ b/pkgs/os-specific/linux/systemd/default.nix
@@ -553,0 +554 @@ stdenv.mkDerivation (finalAttrs: {
+  NIX_DEBUG = "7";
```

```
$ nix build --no-link -f. -L systemdMinimal
...
systemd-minimal>  evaling implicit 'postConfigure' string hook
...
systemd-minimal> ++ return 0
systemd-minimal> ++ date +%s
systemd-minimal> + endTime=1733249932
systemd-minimal> + showPhaseFooter configurePhase 1733249919 1733249932
systemd-minimal> + local phase=configurePhase
systemd-minimal> + local startTime=1733249919
systemd-minimal> + local endTime=1733249932
systemd-minimal> + local delta=13
systemd-minimal> + ((  delta < 30  ))
systemd-minimal> + return
systemd-minimal> + '[' configurePhase = unpackPhase ']'
systemd-minimal> + return 1
systemd-minimal> + exitHandler
systemd-minimal> + exitCode=1
systemd-minimal> + set +e
systemd-minimal> + '[' -n '' ']'
systemd-minimal> + ((  1 != 0  ))
systemd-minimal> + runHook failureHook
systemd-minimal> + local hookName=failureHook
systemd-minimal> + shift
systemd-minimal> + local 'hooksSlice=failureHooks[@]'
systemd-minimal> + local hook
systemd-minimal> + for hook in "_callImplicitHook 0 $hookName" ${!hooksSlice+"${!hooksSlice}"}
systemd-minimal> + _logHook failureHook '_callImplicitHook 0 failureHook'
systemd-minimal> + [[ -z 2 ]]
systemd-minimal> + local hookKind=failureHook
systemd-minimal> + local 'hookExpr=_callImplicitHook 0 failureHook'
systemd-minimal> + shift 2
systemd-minimal> + declare -F '_callImplicitHook 0 failureHook'
systemd-minimal> + type -p '_callImplicitHook 0 failureHook'
systemd-minimal> + [[ _callImplicitHook 0 failureHook != \_\c\a\l\l\I\m\p\l\i\c\i\t\H\o\o\k* ]]
systemd-minimal> + _eval '_callImplicitHook 0 failureHook'
systemd-minimal> + declare -F '_callImplicitHook 0 failureHook'
systemd-minimal> + eval '_callImplicitHook 0 failureHook'
systemd-minimal> ++ _callImplicitHook 0 failureHook
systemd-minimal> ++ local def=0
systemd-minimal> ++ local hookName=failureHook
systemd-minimal> ++ declare -F failureHook
systemd-minimal> ++ type -p failureHook
systemd-minimal> ++ '[' -n '' ']'
systemd-minimal> ++ return 0
systemd-minimal> + return 0
systemd-minimal> + '[' -n '' ']'
systemd-minimal> + return 1
```

**Comment by mitchallain** [comment]
Ah. I believe [systemd's derivation](https://github.com/NixOS/nixpkgs/blob/fdd294bc8fb594b6f9f5978671421f5647a47c65/pkgs/os-specific/linux/systemd/default.nix#L657-L659) makes use of `set +e; ...; set -e` to mask possible errors in the configure phase. This approach is caught by the new ERR trap handler introduced in this PR and causes config phase to return non-zero.

I'm not sure how widespread this pattern is (set +e), but a packaging fix which preserves this PR would be to use the more common `|| true` idiom for bash commands that may fail.

Happy to discuss alternatives if this PR is going to generate an untenable number of packaging fixes. (e.g., adding another alias to use in devshell with the ERR trap behavior, `runPhase2`)

**Comment by philiptaron** [comment]
```
$ rg -F 'set +e' -l --sort=path
ci/eval/default.nix
nixos/modules/services/backup/btrbk.nix
nixos/modules/services/mail/spamassassin.nix
nixos/modules/services/misc/ollama.nix
nixos/modules/services/networking/jibri/default.nix
nixos/modules/system/activation/lib/test.sh
nixos/modules/virtualisation/nixos-containers.nix
pkgs/build-support/checkpoint-build.nix
pkgs/build-support/docker/default.nix
pkgs/build-support/fetchpatch/default.nix
pkgs/build-support/rust/build-rust-crate/configure-crate.nix
pkgs/build-support/testers/hasPkgConfigModules/tester.nix
pkgs/by-name/ax/ax25ms/package.nix
pkgs/by-name/da/darling/package.nix
pkgs/by-name/de/devmode/package.nix
pkgs/by-name/fl/fluxcd/update.sh
pkgs/by-name/ni/nixos-install/nixos-install.sh
pkgs/by-name/sc/scion/package.nix
pkgs/development/compilers/factor-lang/factor99.nix
pkgs/development/python-modules/invisible-watermark/tests/cli.nix
pkgs/development/python-modules/semgrep/update.sh
pkgs/misc/my-env/default.nix
pkgs/os-specific/bsd/netbsd/pkgs/mkDerivation.nix
pkgs/os-specific/linux/systemd/default.nix
pkgs/test/build-environment-info/default.nix
pkgs/test/texlive/default.nix
pkgs/top-level/nixpkgs-basic-release-checks.nix
```

It's a list, but not that bad.

**Comment by mitchallain** [comment]
I am more concerned that the expectation of the community is roughly "stdenv invokes the default builder (i.e., `genericBuild`) with the `-e` shell option, and therefore I can suppress the option to suppress failing commands.

Studying this a little more closely after several months, it may be better to make a change which exclusively affects devshells making the runPhase behavior more consistent with `nix build` (which uses `set -e`). I can't work on this immediately, but would suggest a rollback of this commit for now.

**Comment by mweinelt** [comment]
Reverted in https://github.com/NixOS/nixpkgs/commit/41d4a66bba6843f060c41f385fd00f8e89eda0ae so people can continue working on the staging branch.

**Comment by philiptaron** [comment]
Thanks @mweinelt. That's definitely the right call for the present.

Right now (immediately after the 24.05 release) is the right time to consider taking breaking changes to the stdenv, in my view, should we get the nixpkgs tree in shape for them. So I'd like to consider taking this change as first proposed, then rooting out `set +e` in nixpkgs. Open to feedback about how that's the wrong approach, but that's my inclination.

**Comment by mitchallain** [comment]
To further characterize the two options that I proposed here:

Option A: ERR trap handler
- Any pipeline, list, or compound command with a non-zero exit status will trigger the trap handler and set retval nonzero
- Remaining commands in the stdenv phase variable / function may be executed

Option B: subshell with errexit option ([see above reply](https://github.com/NixOS/nixpkgs/pull/330751#issuecomment-2515440734))
- Any pipeline, list, or compound command with a non-zero exit status will cause the subshell to exit (but not the devshell)
- runPhase function can capture the subshell exit status and return that val
- Remaining commands in the phase var / function will _not_ be executed

On further reflection, I'm partial to option B. It's more consistent with [popular CI execution environments](https://circleci.com/docs/configuration-reference/#default-shell-options) and probably a little easier to reason about.

**Pull request merged**
