### PR TITLE
sratom: 0.6.14 -> 0.6.16

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://drobilla.net/2023/10/22/sratom-0-6-16.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
New `sord` was added in https://github.com/NixOS/nixpkgs/pull/263585. Rebased against current `staging`.

**Comment by Artturin** [comment]
FYI the darwin builds fail while in https://github.com/NixOS/nixpkgs/pull/232496 they worked

```
error: builder for '/nix/store/48vgrasry52vmzhvn0gksvmswfx290r3-zix-0.4.2.drv' failed with exit code 1;
       last 10 log lines:
       > [12/58] Compiling C object libzix-0.0.dylib.p/src_system.c.o
       > [13/58] Compiling C object libzix-0.0.dylib.p/src_tree.c.o
       > [14/58] Compiling C object libzix-0.0.dylib.p/src_posix_filesystem_posix.c.o
       > FAILED: libzix-0.0.dylib.p/src_posix_filesystem_posix.c.o
       > clang -Ilibzix-0.0.dylib.p -I. -I.. -I../include -fvisibility=hidden -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -std=c99 -DZIX_NO_DEFAULT_CONFIG -D_DARWIN_C_SOURCE -DHAVE_CLOCK_GETTIME -DHAVE_FILENO -DHAVE_FLOCK -DHAVE_LSTAT -DHAVE_MLOCK -DHAVE_PATHCONF -DHAVE_POSIX_MEMALIGN -DHAVE_REALPATH -DHAVE_SYSCONF -DHAVE_CLONEFILE -DZIX_INTERNAL -MD -MQ libzix-0.0.dylib.p/src_posix_filesystem_posix.c.o -MF libzix-0.0.dylib.p/src_posix_filesystem_posix.c.o.d -o libzix-0.0.dylib.p/src_posix_filesystem_posix.c.o -c ../src/posix/filesystem_posix.c
       > ../src/posix/filesystem_posix.c:61:56: error: call to undeclared function 'fdatasync'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       >   const ZixStatus st0 = zix_posix_status(dst_fd >= 0 ? fdatasync(dst_fd) : 0);
       >                                                        ^
       > 1 error generated.
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/48vgrasry52vmzhvn0gksvmswfx290r3-zix-0.4.2.drv'.
```

**Comment by trofi** [comment]
Aha, that was probably an effect of implicit int declaration warnings turned to errors on `clang-16+`. `zix` will need to adapt upstream. I'll have a look.

**Comment by trofi** [comment]
Filed upstream issue as https://gitlab.com/drobilla/zix/-/issues/3

**Comment by trofi** [comment]
Meanwhile proposed the workaround as https://github.com/NixOS/nixpkgs/pull/268084

**Pull request merged**
