### PR TITLE
pijul: remove

### PR DESCRIPTION
**Pull request by FlorentBecker**
This version is not working, and it is not even a release upstream

###### Motivation for this change

This is not usable software, nor does it represent what the pijul developpers are currently doing.

###### Things done

- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)

---

### CODE REVIEW

**Comment by domenkozar** [comment]
Can't we update pijul instead?

**Comment by FlorentBecker** [comment]
There has not been a public release (yet). I'll package it then.

**Comment by copumpkin** [comment]
@FlorentBecker just FYI, we often package pre-releases and so on. Half of my Nix expressions use fetchFromGitHub with a raw hash revision rather than a tag 😄 either because I want something before the maintainers make a release or because lots of maintainers don't bother doing full releases. It also makes updating an expression trivial when the release finally comes out, since it's usually just a version bump.

**Comment by FlorentBecker** [comment]
As an author of pijul, consider that removal as an experience to see who actually use[d] that prerelease!

**Comment by copumpkin** [comment]
I'm a keen follower of pijul and just want to make sure as many people can experiment with it as possible, with as little work as possible 😄 anyway, I won't package it against your wishes, but I'd obviously prefer to have it in nixpkgs, even if it's not quite "ready" yet.

**Comment by FlorentBecker** [comment]
Consider our [pijul developper's] asses kicked. 😊

**Pull request merged**
