### PR TITLE
wireshark-cli: support cross compile

### PR DESCRIPTION
**Pull request by squalus**
###### Description of changes

Add cross compile support for wireshark-cli.

Tested native amd64 build and the cross build from amd64 -> aarch64.

Tested x86_64-darwin native build.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bjornfor — APPROVED** [review]

**Comment by teto** [comment]
how could I test this on my x86 machine if possible ?

**Comment by bjornfor** [comment]
> > how could I test this on my x86 machine if possible ?
> 
> With `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` in configuration.nix?

Never mind, that's for native compilation.

**Comment by teto** [comment]
but if I want to compile just this package for aarch64-linux and not my whole config ? sry I am not familiar with cross-compiling (but I am interested in wireshark)

**Comment by bjornfor** [comment]
> how could I test this on my x86 machine if possible ?

`nix-build -A pkgsCross.aarch64-multiplatform.wireshark-cli` should do it.

**Comment by teto** [comment]
works for me too but need a rebase

**Review by teto — APPROVED** [review]

**Comment by squalus** [comment]
Rebased, but it looks like cross compile broke in parts of the dependency tree since yesterday,

**Comment by squalus** [comment]
The cross build was broken by the issue described in #167395

**Pull request merged**
