### PR TITLE
libreoffice-{fresh,still}: upgrade and clean

### PR DESCRIPTION
**Pull request by dtzWill**
* libreoffice-still: -> 6.0.6.2
  * (newer than our current 'fresh!')
* libreoffice-fresh: -> 6.1.0.3
  * 6.1.1(.1) is currently pre-release, FWIW
* Use normal gcc, not gcc5
  * dropping 'glibc' from buildInputs fixed this (?)
* remove many fixes/touchups/workarounds/hacks
  * hopefully everything still works for everyone
* disable online update since that seems unlikely to work anyway
* fix autogen/configure invocations
* disable libnumbertext in 6.1.x since not packaged
* drop 'touch solenv/inc/target.mk' as unclear what it was for
  and doesn't seem to be currently needed
* cleanup link gen a bit[1]
* split checks to check phase

[1]
primary motivation was to stop creating links like:

'libreoffice-6.0.5.2/src/-libxslt-1.1.32.tar.gz' -> '/nix/store/503v5hmhm430bld0h078gacmkniwdllr-libxslt-1.1.32.tar.gz'
'libreoffice-6.0.5.2/src/libxslt-1.1.32.tar.gz' -> '/nix/store/503v5hmhm430bld0h078gacmkniwdllr-libxslt-1.1.32.tar.gz'

This is mostly accomplished by simply using the 'md5name' field
which the python script kindly generates for us
(including the use of non-md5 if md5 is not set or empty).

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Complicated package, testing and review appreciated!

### CODE REVIEW

**Comment by dtzWill** [comment]
libreoffice-still has been on 5.x for some time, but I moved to 6.x since that's what is listed here: https://www.libreoffice.org/download/libreoffice-still .  Just wanted to mention the change.

**Comment by dtzWill** [comment]
@GrahamcOfBorg build libreoffice-still libreoffice-fresh

**Review by 7c6f434c — APPROVED** [review]

**Comment by 7c6f434c** [comment]
Thanks. Feel free to add yourself as a maintainer (or not to add, whatever you prefer).

**Comment by dtzWill** [comment]
> So, printing still works without -lcups now?

Sure seems to, at least with -fresh. If there is an environment/setup that is known to be tricky/broken in this way, please LMK or check that it still works! :)

**Comment by dtzWill** [comment]
FWIW there's optional dconf support if that's preferred over gconf, but haven't tried it :).

**Comment by 7c6f434c** [comment]
I think there was a version where it always failed because of library paths. Hopefully it got better by now.

**Pull request merged**
