### PR TITLE
nixos/wireguard: start new peers when they are added

### PR DESCRIPTION
**Pull request by symphorien**
when a new peer is added, it does not modify any active units, because the interface unit remains the same. therefore the new peer is not added until next reboot or manual action.

cc @grahamc @asymmetric @ma27

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Doesn't that mean that the VPN is down for a very short period of time when adding new peers? Shouldn't we make sure that the unit adding a new peer to a VPN is actually started after being added (i.e. deployed)?

**Comment by winterqt** [comment]
> Doesn't that mean that the VPN is down for a very short period of time when adding new peers? Shouldn't we make sure that the unit adding a new peer to a VPN is actually started after being added (i.e. deployed)?

AFAIK, this is the ideal solution, yes.

**Comment by symphorien** [comment]
> Doesn't that mean that the VPN is down for a very short period of time when adding new peers? Shouldn't we make sure that the unit adding a new peer to a VPN is actually started after being added (i.e. deployed)?

yes but I don't know how to do differently. I tried reloadTriggers instead of restartTriggers but systemd refuses to reload this type of units. If you have better suggestions I'm all ears :)

**Comment by winterqt** [comment]
> I tried reloadTriggers instead of restartTriggers but systemd refuses to reload this type of units.

You mean it wouldn't reload the dependent units?

> If you have better suggestions I'm all ears :)

What about something like this: we create an intermediate target that, upon restart, will restart all the peer units, but is only a soft dependency (`After=`) on the main service?

That definitely has flaws but like... maybe someone can work it into something better ;)

**Comment by symphorien** [comment]
> > I tried reloadTriggers instead of restartTriggers but systemd refuses to reload this type of units.
> 
> You mean it wouldn't reload the dependent units?

```
reloading the following units: wireguard-wg0.service
Failed to reload wireguard-wg0.service: Job type reload is not applicable for unit wireguard-wg0.service.
```
> 
> > If you have better suggestions I'm all ears :)
> 
> What about something like this: we create an intermediate target that, upon restart, will restart all the peer units, but is only a soft dependency (`After=`) on the main service?
> 
> That definitely has flaws but like... maybe someone can work it into something better ;)

let me try

**Comment by symphorien** [comment]
looks like it works, but not in the way I expected: nixos-rebuild says:
```
the following new units were started: wireguard-wg0-peer-RI3raw000B0z5mTYbusIz39LmInoAOpQVutTTbtYYHQ\x3d.service                                                                             
```
instead of something like `restarting wireguard-wg0.target`

**Review by RaitoBezarius — APPROVED** [review]
Thank you so much, it solves a big pain point of mine.
Looks good to me.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
> instead of something like restarting wireguard-wg0.target

It's IMHO expected to tell that the service is started. Regarding the target, these are filtered from the output on purpose, see
https://github.com/NixOS/nixpkgs/blob/5ebfb030f60c29ec7b5ac8ce446f3f226d270643/nixos/modules/system/activation/switch-to-configuration.pl#L562-L578

**Pull request merged**
