### PR TITLE
atlassian-{bamboo,confluence,crowd,jira}: rm techknowlogick from maintainers for atlassian packages, nixfmt, move to pkgs/by-name

### PR DESCRIPTION
**Pull request by techknowlogick**
Inspired by https://github.com/NixOS/nixpkgs/pull/353043

I don't use the Atlassian software suite anymore, so this PR primarily is to remove me from maintaining them, but I also formatted them with nixfmt and moved them to pkgs/by-name, too.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — APPROVED** [review]
Thanks, looks good. I’m a bit concerned about the maintenance state, though, given how long these packages have gone without security updates in the past; I am wondering if we should consider dropping them rather than carrying packages into 24.11 that are likely to become vulnerable during its lifespan.

@WilliButz @ciil @megheaiulian Are you still interested in maintaining Atlassian packages?

**Comment by tomodachi94** [comment]
I'm wondering if we should do a call for maintainers on Discourse and Matrix if the above don't respond soon.

**Comment by emilazy** [comment]
I’m sceptical many people are even deploying these in the first place given the past update history.

**Comment by WilliButz** [comment]
>  Are you still interested in maintaining Atlassian packages?

No. I used to operate some of their services with a "server" license in the past, but have had nothing to do with them for over a year now. Atlassian discontinued the "server" license in february this year, made some final releases for them last year. The only on-premises alternative would be their "datacenter" license tier, but that is crazy expensive / not economically viable for smaller to medium-sized companies.

Final "server" releases for software I know:
* Jira 9.12: https://confluence.atlassian.com/jirasoftware/jira-software-9-12-x-release-notes-1319575972.html
* Confluence 8.5: https://confluence.atlassian.com/doc/confluence-8-5-release-notes-1252010185.html
* Crowd 5.2: https://confluence.atlassian.com/crowd/crowd-5-2-release-notes-1295679821.html

> I am wondering if we should consider dropping them rather than carrying packages into 24.11 that are likely to become vulnerable during its lifespan.

I'd be all for this.
In case there really is someone still running some instance based on nixpkgs, I see at least two options for them to continue that (for whatever reason):
a. vendor the expression in their deployment, ideally updating the version to the latest release
b. reference an old nixpkgs relase

> I’m sceptical many people are even deploying these in the first place given the past update history.

Same. I just checked the packaged releases and I'm very suprised to see Jira 9.17.1 and Confluence 9.0.1 packaged on latest nixpkgs master. Neither of those releases are supported with the "server" license (see above), nor are they the latest release (not even patch release). I really hope there is no one running a production "datacenter" instance on those expressions :eyes:

**Comment by emilazy** [comment]
Thanks. Since our packaged versions aren’t the latest releases and seem legally dubious to deploy for users that were previously on the server licence, there’s no real upgrade path for those users, and clearly even if there are any Nix‐using enterprises running the data centre version they’re not putting any resources into maintaining it in Nixpkgs, I think we should move forward with dropping these for 24.11.

@tomodachi94 Are you up for handling that?

**Comment by tomodachi94** [comment]
> @tomodachi94 Are you up for handling that?

You know how much I love dropping unmaintained packages :)

I'll open a PR momentarily, as well as closing this one.

**Comment by tomodachi94** [comment]
Everything is removed now. Thank you for maintaining that stuff :)

**Comment by techknowlogick** [comment]
Thank you @emilazy and @tomodachi94 <3

**Pull request closed without merging**
