### PR TITLE
maturin: 1.7.5 -> 1.7.8

### PR DESCRIPTION
**Pull request by trofi**
Changes:
- https://github.com/PyO3/maturin/releases/tag/v1.7.6
- https://github.com/PyO3/maturin/releases/tag/v1.7.7
- https://github.com/PyO3/maturin/releases/tag/v1.7.8

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by getchoo** [comment]
@ofborg eval

**Comment by getchoo** [comment]
Attempting to run the usual `uv` rebuild resulted the same failure as the previous bumps in #359505

```
Finished maturinBuildHook
buildPhase completed in 10 minutes 6 seconds
Running phase: pythonRuntimeDepsCheckHook
@nix { "action": "setPhase", "phase": "pythonRuntimeDepsCheckHook" }
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for uv-0.4.30-py3-none-linux_x86_64.whl
  + Exception Group Traceback (most recent call last):
  |   File "/nix/store/gdxd1rn8zgjjw08ijghvpazj18n4sjl6-python-runtime-deps-check-hook.py", line 93, in <module>
  |     metadata = get_metadata(args.wheel)
  |                ^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/nix/store/gdxd1rn8zgjjw08ijghvpazj18n4sjl6-python-runtime-deps-check-hook.py", line 58, in get_metadata
  |     metadata = Metadata.from_raw(raw)
  |                ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/nix/store/qnfndbdg0k5s7zb47l5q9h7cszi56gpf-python3.12-packaging-24.1/lib/python3.12/site-packages/packaging/metadata.py", line 701, in from_raw
  |     raise ExceptionGroup("invalid metadata", exceptions)
  | ExceptionGroup: invalid metadata (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/nix/store/qnfndbdg0k5s7zb47l5q9h7cszi56gpf-python3.12-packaging-24.1/lib/python3.12/site-packages/packaging/metadata.py", line 661, in from_raw
    |     metadata_version = ins.metadata_version
    |                        ^^^^^^^^^^^^^^^^^^^^
    |   File "/nix/store/qnfndbdg0k5s7zb47l5q9h7cszi56gpf-python3.12-packaging-24.1/lib/python3.12/site-packages/packaging/metadata.py", line 504, in __get__
    |     value = converter(value)
    |             ^^^^^^^^^^^^^^^^
    |   File "/nix/store/qnfndbdg0k5s7zb47l5q9h7cszi56gpf-python3.12-packaging-24.1/lib/python3.12/site-packages/packaging/metadata.py", line 526, in _process_metadata_version
    |     raise self._invalid_metadata(f"{value!r} is not a valid metadata version")
    | packaging.metadata.InvalidMetadata: '2.4' is not a valid metadata version
    +------------------------------------
 ```
 
Seems this bug is still around. Or maybe we need to bump `packaging` so it can understand this? It's currently [one minor release out of date](https://github.com/pypa/packaging/releases/tag/24.2), but I don't think something like this was added based on the release notes 🤷

**Comment by trofi** [comment]
`0.4.30` looks like a `master` version of `uv`. On `staging` it's `0.5.6`, and that seems to build fine for me:

```
$ nix build --no-link github:NixOS/nixpkgs/pull/363097/head#uv --print-out-paths
/nix/store/l6q9f0rp131wwa0d69ardh12hr56yrsr-uv-0.5.6
```

**Comment by getchoo** [comment]
Ah, I guess cheating with unstable has finally caught up with me 😄 

Rebuilding on aarch64-linux now to confirm

**Review by getchoo — APPROVED** [review]
```console
$ nix-build -A maturin -A uv
/nix/store/71g7w6rfvl51mr5y8qjkbprn09wsid38-maturin-1.7.8
/nix/store/casns9rrvfmkmr2l1wawnlxmji9pijfm-uv-0.5.7
```

**Pull request merged**
