### PR TITLE
latte-dock: build with libsForQt514

### LINKED ISSUE #101756: latte-dock broken after update
**Describe the bug**
After updating between two unstable versions, latte-dock no longer shows open applications. Widgets and pinned applications still display, but will always open a new instance.

**To Reproduce**
1. Install `latte-dock`
2. Start `latte-dock`

**Expected behavior**
I expect latte-dock to show my open applications.

**Screenshots**
image

**Additional context**
None.

**Notify maintainers**
@benley @ysndr

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.1, NixOS, 21.03pre248236.bd017760509 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre248236.bd017760509, unstable-20.09pre239228.bd0e645f024"`
 - channels(leo60228): `"unstable-21.03pre248170.007126eef72"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: latte-dock
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by leo60228**
###### Motivation for this change
Fixes #101756

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101857` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>latte-dock</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101857` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>latte-dock</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by leo60228** [comment]
This seems to have been fixed.

**Pull request closed without merging**
