### PR TITLE
nixos/freshrss: fix freshrss cli flag names in the systemd service

### PR DESCRIPTION
**Pull request by aftix**
The flags for cli parameters were changed from using '-' to '_' between words, except for the `--db-*` flags, for the cli tools. The module was using the FreshRSS cli scripts for the systemd service setting up the FreshRSS configuration, so the freshrss-config service was failing. See https://github.com/FreshRSS/FreshRSS/pull/6028 .

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

@Stunkymonkey 

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
@aftix the docs state the opposite... https://github.com/kasimircash/FreshRSS/blob/edge/cli/README.md#system

**Comment by aftix** [comment]
This is strange, as far as I can tell looking at the upstream repo, you're right in that they're going from _ to -, but i have been consistently getting 

```
FreshRSS error: unknown options: auth-type, base-url, default-user
Usage: reconfigure.php --default_user admin ( --auth_type form --environment production --base_url https://rss.example.net --allow_robots --language en --title FreshRSS --allow_anonymous --allow_anonymous_refresh --api_enabled --db-type mysql --db-host localhost:3306 --db-user freshrss --db-password dbPassword123 --db-base freshrss --db-prefix freshrss_ --disable_update )
```

Every time freshrss-config.service (causing the service to fail) for at least a month now, and this PR fixes it, i'm not sure why.

**Comment by Stunkymonkey** [comment]
are you sure you are using the latest freshrss package? i tried it on `master` and it all worked fine.

**Comment by aftix** [comment]
I was not using the latest, there was an overlay to use the package from nixos-24.05 buried somewhere

**Comment by Stunkymonkey** [comment]
no problem. thanks for investigating your time.

**Pull request closed without merging**
