### PR TITLE
split2flac: removed

### LINKED ISSUE #154555: split2flac: broken (but not developed anymore, remove?)
### Describe the bug
`split2flac` fails to compile on `nixos-unstable` because of a broken Python 2 dependency (`pytest-forked`).

### Additional context
According to the github home page, `split2flac` is not anymore developed and replaced by `unflac`, see https://git.sr.ht/~ft/unflac,

### Notify maintainers
@jfrankenau

### PR DESCRIPTION
**Pull request by dasj19**
###### Motivation for this change
This PR is a direct response to the opened issue https://github.com/NixOS/nixpkgs/issues/154555
I removed split2flac as it is a legacy project with the source archived on github. Furthermore it fails to build due to an indirect python2.7 dependency.

Closes #154555

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by c0bw3b — APPROVED** [review]

**Review by dschrempf — APPROVED** [review]
Thank you! Looks good to me!

**Comment by dasj19** [comment]
@bobby285271 thanks for the heads up. I rebased the branch.

**Comment by ajs124** [comment]
needs another rebase

**Comment by Mindavi** [comment]
Would be nice to get this in

**Comment by Artturin** [comment]
> Would be nice to get this in

you can use the gh command to checkout a pr and then push changes to it

`gh pr checkout 154917`
and then just do normal git things

**Comment by Artturin** [comment]
> Sorry to hijack this, but can one then push stuff to the PR's branch, so in this case to `dasj19:remove-split2flac`? Or how would I change the PR otherwise?

That is only possible if you have write perms in nixpkgs

If you dont then you may create a new pr

**Comment by dasj19** [comment]
Hi guys, sorry for my absence. I just did a rebase. Please merge this PR.

**Pull request merged**
