### PR TITLE
boost171: remove

### PR DESCRIPTION
**Pull request by nagy**
###### Motivation for this change

I suggest to remove `boost171`, since it is not used anywhere in the tree.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
  - [ ] NixOS
  - [ ] macOS
  - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Same for `boost168`

Are there some other packages that can be moved to an X version?
I know there are some like `mysql80` that need an exact version but surely some can be moved off a completely fixed version

**Comment by nagy** [comment]
I was about to bump `percona-xtrabackup_8_0` which also lets us remove `boost170`. I was planning on making one PR at a time which removes them. Be aware, that https://github.com/NixOS/nixpkgs/pull/120259 will also allow us to move forward with boost versions once it gets merged.

**Comment by mikepurvis** [comment]
I'm bummed about this change since boost 1.71 is the version in Ubuntu Focal, so it's a handy benchmark for stuff known to be source-compatible with that:

https://packages.ubuntu.com/focal/libboost-dev

I'm expecting 1.72 will be a fine replacement.

**Comment by nagy** [comment]
> since boost 1.71 is the version in Ubuntu Focal

The software versions in Ubuntu 20.04 hardly match those of the ones in nixpkgs. Do you have a particular example of a package that is only source compatible up to boost 1.71 ?

**Comment by nagy** [comment]
@mikepurvis If it is just about boost you could of course just pull in this particular derivation from an earlier NixOS release like so:

```nix
let
  boost171 = callPackage (import <nixos-21.05/pkgs/development/libraries/boost/1.71.nix>) {
    inherit (buildPackages) boost-build;
  };
in
# ...
```

This calls the old boost with the current nixpkgs dependencies ( I have not tested it ). I initially removed this because no other application was using it. So, it is hard to know what library is being used outside of nixpkgs unless some application within nixpkgs is using it. Maybe we need some guidelines for this in the future.

**Pull request merged**
