### PR TITLE
DESCRIPTION CHANGE ONLY- NO CHECKS NEEDED.

### PR DESCRIPTION
**Pull request by SRGOM**
I feel like there is a scope for tags in meta.
Only edited descriptions.

### CODE REVIEW

**Comment by Yarny0** [comment]
Review per https://nixos.org/nixpkgs/manual/#reviewing-contributions-package-updates

##### Reviewed points

- [x] package name fits guidelines (*no change*)
- [x] package version fits guidelines  (*no change*)
- [x] package build on `x86_64-linux` (*build recipe not changed, evaluates to same hash*)
- [ ] executables tested on ARCHITECTURE (*no executables*)
- [ ] all depending packages build

##### Possible improvements

- While I consider myself a novice in hacking nixpkgs, the commit's message looks a bit sparse to me. I'd recommend "hanazono font: expand package description".
- It appears to me that the title of the pull request should be reworded likewise. The current title gives no hint on the actual pull request's content, so it's easily overlooked when browsing the list of pull requests. However, I'd consider this change to be optional, as the pull request's text will not be recorded in nixpkgs's git history, but the commit will.

##### Comments

- Tested after rebasing onto current nixos-unstable channel (bc94dcf500286495e3c478a9f9322debc94c4304).
- I like this commit. I consider documentation very important.
- Notifying hanazono maintainer: @mathnerd314
- Note that I cannot comment on the correctness of the new description.

**Comment by SRGOM** [comment]
I think a good commit message would be- "[Fonts] Improved hanazono package description". But I think merge can be made such that a new commit message can be added easily.

**Comment by SRGOM** [comment]
I think a good commit message would be- "[Fonts] Improved hanazono package description". But I think merge can be made such that a new commit message can be added easily.

**Comment by Mathnerd314** [comment]
Descriptions from other distros:
* Gentoo: Hanazono font is a Japanese mincho font based on GlyphWiki
* Fedora:
  * Japanese Mincho-typeface TrueType font
  * Hanazono Mincho typeface is a Japanese TrueType font that developed with a support of Grant-in-Aid for Publication of Scientific Research Results from Japan Society for the Promotion of Science and the International Research Institute for Zen Buddhism (IRIZ), Hanazono University. also with volunteers who work together on glyphwiki.org. This font contains 107518 characters in ISO/IEC 10646 and Unicode Standard, also supports character sets: - 6355 characters in JIS X 0208:1997 - 5801 characters in JIS X 0212:1990 - 3695 characters in JIS X 0213:2004 - 6763 characters in GB 2312-80 - 13053 characters in Big-5 - 4888 characters in KS X 1001:1992 - 360 characters in IBM extensions - 9810 characters in IICORE - Kanji characters in GB18030-2000 - Kanji characters in Adobe-Japan1-6
* Debian:
  * Japanese TrueType mincho font by KAGE system and FontForge
  * This font is Japanese KANJI free font. The KAGE system and FontForge are used for the generation of this font. Collected glyph uses all the data registered in glyphwiki. 
* FreeBSD:
  * CJK Mincho-typeface developed by Hanazono University
  * Hanazono Mincho typeface is a CJK TrueType font that developed with a
support of Grant-in-Aid for Publication of Scientific Research Results
from Japan Society for the Promotion of Science and the International
Research Institute for Zen Buddhism (IRIZ), Hanazono University. also
with volunteers who work together on glyphwiki.org.
* Arch: A free Japanese kanji font, which contains about 78,685 characters (and 2 SPACEs) defined in ISO/IEC 10646 standard / the Unicode standard.

I don't think it's correct to call a university-led collection of volunteers (GlyphWiki) a "Japanese foundry". But it does seem that 'kanji' is not correct as the font contains non-kanji characters, so 'CJK font' is more accurate. Overall I'd say it's an improvement but I think the description could still be improved further.

**Pull request closed without merging**
