### PR TITLE
OpenStack (Liberty): Nova, Glance, Neutron, Keystone

### PR DESCRIPTION
**Pull request by domenkozar**
Nova, Glance, Neutron, Keystone (from Liberty release) are packaged.

### CODE REVIEW

**Comment by domenkozar** [comment]
I'm going to wait a few days then merge this. Probably going to fix a few things for Python3, but there isn't much need/support for it.

**Comment by edolstra** [comment]
:beer:

**Comment by domenkozar** [comment]
http://hydra.nixos.org/jobset/nixpkgs/pr-10399

**Comment by domenkozar** [comment]
I've also packaged Glance, Neutron and Keystone. There are quite some transient test failures in packages, the rest looks good. Ready for a review.

**Comment by domenkozar** [comment]
I think the last outstanding bug breaking tests is http://bugs.python.org/issue25320, will check.

**Comment by wmertens** [comment]
<3, excellent timing, wanted to set this up

**Comment by domenkozar** [comment]
All 4 services compile for me on python2.7, merging.

**Comment by wmertens** [comment]
So if I want to have a devstack lookalike, I just enable all 4 services or are there still things missing?

**Comment by domenkozar** [comment]
Currently you can just build each service with `nix-build -A keystone -A glance -A nova -A neutron`, I'll be working this week on modules for each service.

**Comment by domenkozar** [comment]
@wmertens I've added most basic NixOS modules at https://github.com/NixOS/nixpkgs/pull/10839, but I've still not setup the whole cluster yet to be able to give any instructions.

**Pull request merged**
