### PR TITLE
Update Vscode Haskell extensions

### PR DESCRIPTION
**Pull request by jonathanfishbein1**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 138217` at 3a82a801 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>vscode-extensions.haskell.haskell</li>
    <li>vscode-extensions.justusadam.language-haskell</li>
  </ul>
</details>

**Comment by figsoda** [comment]
commit messages are not recognized by ofborg
```diff
- vscode-extension haskell.haskell 1.10 -> 1.61
+ vscode-extension.haskell.haskell: 1.10 -> 1.61
```
```diff
- vscode-extension justusadam.language-haskell 3.2.1 -> 3.40
+ vscode-extension.justusadam.language-haskell: 3.2.1 -> 3.40
```

**Comment by jonathanfishbein1** [comment]
I'm sorry about the incorrectly formatted commit message, I'll make sure to add the colon.  Is there anything else you can suggest for next time too? This was my first PR to nixpkgs and I'm learning as I go!

**Comment by figsoda** [comment]
no need to be sorry
everything else looks good!

**Comment by figsoda** [comment]
can you update the commit messages in this pull request?

**Comment by jonathanfishbein1** [comment]
> can you update the commit messages in this pull request?

What's the best was to go about it?  Should I make two more commits with the updated messages or create a new PR?

**Comment by figsoda** [comment]
`git rebase -i HEAD~2` and edit the commit messages
`git push -f` to force push to this pull request

**Comment by figsoda** [comment]
there should be a `.` instead of a space after  `vscode-extensions`
also my bad, it should be `vscode-extensions` instead of `vscode-extension`

**Review by figsoda — APPROVED** [review]

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 138217` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vscode-extensions.haskell.haskell</li>
    <li>vscode-extensions.justusadam.language-haskell</li>
  </ul>
</details>

**Pull request merged**
