### PR TITLE
libreoffice: Fix invalid desktop files

### LINKED ISSUE #220693: libreoffice: no longer shows up in Gnome applications drawer
Since https://github.com/NixOS/nixpkgs/pull/219166 , the LibreOffice applications no longer show up in the Gnome application drawer.

The `share/applications/*.desktop` do seem to be part of the derivation output, though they refer to a `libreoffice7.3` executable which AFAICS does not exist. Before https://github.com/NixOS/nixpkgs/pull/219166 these desktop files pointed to a `libreoffice` executable, which used to be a symlink to `soffice`, but which also disappeared.

### PR DESCRIPTION
**Pull request by e1mo**
###### Description of changes

Fixes a regression introduced in #219166 by again setting the correct binary name in the Exec filed for the `.desktop` files. The desktop icons for LibreOfice{,Writer,Calc,Base,...} would not show up when searching for them in gnome. `xdg-open super-important-document.odt` would also not open LibreOffice.

This "fix" is quite simple since it just re-adds the specific for loop removed in #219166.

Also fixes #220693 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@doronbehar this should have been moved to the wrapper instead of removed, right?

**Comment by doronbehar** [comment]
Aish, thanks for the fix!

> @doronbehar this should have been moved to the wrapper instead of removed, right?

I'm not sure the wrapper is the right place for this change, as the wrapper currently uses symlinks, and to change these lines in the `.desktop` files you'd have to be a bit more sophisticated in the wrapper and copy the files instead of symlinking.

In general we can rethink how much we want to do in the wrapper and how much in the unwrapped `postInstall`. I think that changes such as this and the rest that is done in the current `postInstall` we can all agree that no matter how you wrap your libreoffice, you will want these fixups to upstream's default `installPhase`. Hence I approve this PR.

Sorry for missing this `substituteInPlace` loop, I think I got the impression that it's not needed anymore, not sure why..

**Review by raboof — APPROVED** [review]
this *looks* good to me, but I don't have a machine with sufficient resources to build libreoffice at hand to test it.

**Comment by 7c6f434c** [comment]
> this looks good to me, but I don't have a machine with sufficient resources to build libreoffice at hand to test it.

This is exactly why I ask if it could be done in the wrapper!

**Comment by e1mo** [comment]
> > this looks good to me, but I don't have a machine with sufficient resources to build libreoffice at hand to test it.
> 
> This is exactly why I ask if it could be done in the wrapper!

Build time is a good point which I totally missed. I have moved the respective action into the wrapper. I'm not sure if this is the most elegant way possible (especially since we now manually handle every folder from the share and will need to update the list for every folder that gets added in the future), but it works and does not cause a rebuild of every LibreOffice version.

**Review by 7c6f434c — APPROVED** [review]

**Comment by 7c6f434c** [comment]
OK, this looks at least no worse than before, and _in the wrapper_ we can iterate cheaply on how the loops are done…

**Comment by raboof** [comment]
Confirmed works! Thanks!

**Pull request merged**
