### PR TITLE
bash,readline80: upgrade bash 4 -> 5, init readline80

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Essentially same as #53628 only rebased to staging
and instead of (temporary?) top-level variants
go ahead and make it the default.

Naturally needs to be tested carefully first!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
This makes it the default, per your suggestion @Mic92 :).

Also looks like my concerns about breakage were warranted, our stdenv's `consumeEntire` seems not to work with this:

```
consumeEntire(): ERROR: Input null bytes, won't process
```

cc stdenv maintainers: @Ericson2314 @matthewbauer

**Comment by Mic92** [comment]
You might want to cherry-pick: https://github.com/NixOS/nixpkgs/pull/53628/commits/26c7c59c0d4cb5c129623c1f7b8a5b42abf5f4a3

**Comment by Mic92** [comment]
Now this one can be rebased.

**Comment by dtzWill** [comment]
See also #54353 FWIW.

**Comment by FRidh** [comment]
@dtzWill should this be closed?

**Comment by FRidh** [comment]
Nothing happening so closing.

**Pull request closed without merging**
