### PR TITLE
warp-terminal: 0.2024.10.29.08.02.stable_02 -> 0.2024.11.12.08.02.stable_02

### PR DESCRIPTION
**Pull request by 4evy**
Changelog: https://docs.warp.dev/getting-started/changelog#id-2024.11.14-v0.2024.11.12.08.02

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by RodEsp — APPROVED** [review]

**Review by JohnRTitor — COMMENTED** [review]
Humm, so no updates for Linux?

**Comment by DontEatOreo** [comment]
Yeah, it seems like this one is only for Darwin for now? 🤔

**Comment by agluck91** [comment]
@DontEatOreo Thanks for catching this update. It looks like the hashes for linux are updated in your commit now as well, do I understand that right?  I am new to nixpkgs and came here to figure out how to make a PR.I talked with the warp team and they said the update should be live for linux now.

**Comment by DontEatOreo** [comment]
> It looks like the hashes for linux are updated in your commit now as well, do I understand that right?

Yep!

> I talked with the warp team and they said the update should be live for linux now

Glad to hear! The update dropped shortly *(or at least my warp got notified shortly after)* after I force-pushed for a second time, so I decided to just force-push again to avoid making another PR

You can look at diff for this PR here: https://patch-diff.githubusercontent.com/raw/NixOS/nixpkgs/pull/354628.diff

**Comment by DontEatOreo** [comment]
Yep, I regularly make PRs for Warp Terminal as well as other macOS software I use, but you and anyone else can feel free to make PRs as well!

**Review by JohnRTitor — APPROVED** [review]
Will merge after eval passes

**Comment by DontEatOreo** [comment]
@JohnRTitor eval passed

**Pull request merged**
