### PR TITLE
go-font: avoid .gitignore and .gitattributes in output

### PR DESCRIPTION
**Pull request by sternenseemann**
These were previously left over in $out, as they weren't matched by `$out/*`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build go-font

**Review by bdd — COMMENTED** [review]
May I recommend switching to `fetchzip` instead and pulling directly from Gitiles instance at googlesource.com?

```diff
diff --git a/pkgs/data/fonts/go-font/default.nix b/pkgs/data/fonts/go-font/default.nix
index 91ecfd29100..caa739efa89 100644
--- a/pkgs/data/fonts/go-font/default.nix
+++ b/pkgs/data/fonts/go-font/default.nix
@@ -1,21 +1,21 @@
-{ lib, fetchgit }:
+{ lib, fetchzip }:
 
 let
   version = "2.010";
-in (fetchgit {
-  name = "go-font-${version}";
-  url = "https://go.googlesource.com/image";
   rev = "41969df76e82aeec85fa3821b1e24955ea993001";
+in (fetchzip {
+  name = "go-font-${version}";
+  url = "https://go.googlesource.com/image/+archive/${rev}/font/gofont/ttfs.tar.gz";
+  stripRoot = false;
+  sha256 = "fYQF6IKZSx2SqS0QS7Y/HrIf5WIv2SHSFM1KbALmspw=";
 
   postFetch = ''
-    mv $out/* .
     mkdir -p $out/share/fonts/truetype
     mkdir -p $out/share/doc/go-font
-    cp font/gofont/ttfs/* $out/share/fonts/truetype
-    mv $out/share/fonts/truetype/README $out/share/doc/go-font/LICENSE
+    mv $out/*.ttf $out/share/fonts/truetype
+    mv $out/README $out/share/doc/go-font/LICENSE
   '';
 
-  sha256 = "dteUL/4ZUq3ybL6HaLYqu2Tslx3q8VvELIY3tVC+ODo=";
 }) // {
   meta = with lib; {
     homepage = "https://blog.golang.org/go-fonts";
```

**Comment by winterqt** [comment]
(I edited the above comment to specify that it's a diff, for syntax highlighting.)

**Comment by sternenseemann** [comment]
@bdd feel free to PR such a change, I personally don't want to do another roundtrip for a minor improvement.

**Review by bdd — APPROVED** [review]

**Pull request merged**
