### PR TITLE
azure-cli-extensions.containerapp: init at 0.3.53

### PR DESCRIPTION
**Pull request by giggio**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Notifying maintainers of `azure-cli`: @katexochen

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by superherointj** [comment]
Consider adding yourself as maintainer of this extension since you are adding it.
And also include meta information to facilitate upkeep, downloadPage, license, etc.

**Comment by superherointj** [comment]
As this extension doesn't need extra package, it should be automatically generated.

This extension seems to exist at [index](https://azcliextensionsync.blob.core.windows.net/index1/index.json).

image

Why this PR isn't being automatically generated?

**Comment by katexochen** [comment]
@giggio please check out the [README](https://github.com/NixOS/nixpkgs/blob/b361c1b6a2edfe68a31aae39243a451a68f71716/pkgs/by-name/az/azure-cli/README.md#adding-an-extension-to-extensions-manualnix) on how to manually add a missing extension. :)
Your commit message should match the current PR title.
Please also add yourself to the maintainers list (see [bullet point 5 here](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions)) and as maintainer of the extension you are adding.

**Comment by giggio** [comment]
@katexochen I have added myself to the maintainers and also updated the commit messages. Thanks for guiding me.

**Review by katexochen — CHANGES_REQUESTED** [review]

**Comment by giggio** [comment]
@katexochen I pushed the updates as requested.
When running `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` I got this error at the end, which I am not sure is something I have to fix, please let me know and I'll work on it:

```
azure-cli-extensions.containerapp azure-cli-extensions.containerapp.dist

error: build log of '/nix/store/mhz2vz92pmg8cz6ziwrx5zrkf5sxqh35-python3.11-containerapp-0.3.53.drv^*' is not available
error: build log of '/nix/store/mhz2vz92pmg8cz6ziwrx5zrkf5sxqh35-python3.11-containerapp-0.3.53.drv^*' is not available
```

**Comment by katexochen** [comment]
> I pushed the updates as requested. When running `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` I got this error at the end, which I am not sure is something I have to fix, please let me know and I'll work on it:
> 
> ```
> azure-cli-extensions.containerapp azure-cli-extensions.containerapp.dist
> 
> error: build log of '/nix/store/mhz2vz92pmg8cz6ziwrx5zrkf5sxqh35-python3.11-containerapp-0.3.53.drv^*' is not available
> error: build log of '/nix/store/mhz2vz92pmg8cz6ziwrx5zrkf5sxqh35-python3.11-containerapp-0.3.53.drv^*' is not available
> ```

Unsure what went wrong on your side, it builds fine for me:

Result of `nixpkgs-review pr 326954` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>azure-cli-extensions.containerapp</li>
    <li>azure-cli-extensions.containerapp.dist</li>
  </ul>
</details>

**Comment by katexochen** [comment]
@giggio were you able to build azure-cli with the extension and tests its functionality?

**Comment by giggio** [comment]
> @giggio were you able to build azure-cli with the extension and tests its functionality? 

@katexochen yes, I actually used it to solve a real problem.

**Review by katexochen — APPROVED** [review]

**Comment by katexochen** [comment]
Thanks, and welcome as nixpkgs maintainer! :)

**Comment by giggio** [comment]
> Thanks, and welcome as nixpkgs maintainer! :)

Thanks! :)

**Pull request merged**
