### PR TITLE
kodi: updates

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
- manual version bumps because i noticed the bot hasn't been updating packages :cry: 
  - ran `nix-shell maintainers/scripts/update.nix --argstr package kodi.packages...` a few times
  - felt regret the bot didn't do it for me

i haven't got around to testing this yet...

ping @andir just in case

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Review by minijackson — APPROVED** [review]
By a quick look at the diff

**Comment by aanderse** [comment]
In the `0.7.3` release of `jellyfin-kodi` the plugin stopped shipping its own version of the `websocket-client` `python` module and started pulling this library in as a dependency: https://github.com/jellyfin/jellyfin-kodi/compare/v0.7.2...v0.7.3

Running this PR introduces the following error:
```
2021-06-21 20:36:43.944 T:385896   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'websocket'
                                                   Traceback (most recent call last):
                                                     File "/nix/store/cbqyg6hzn180yq61v7c5zj0q95dy5mkj-kodi-19.1-env/share/kodi/addons/plugin.video.jellyfin/service.py", line 21, in <module>
                                                       from entrypoint import Service  # noqa: E402
                                                     File "/nix/store/cbqyg6hzn180yq61v7c5zj0q95dy5mkj-kodi-19.1-env/share/kodi/addons/plugin.video.jellyfin/jellyfin_kodi/entrypoint/__init__.py", line 11, in <module>
                                                       from jellyfin import Jellyfin
                                                     File "/nix/store/cbqyg6hzn180yq61v7c5zj0q95dy5mkj-kodi-19.1-env/share/kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/__init__.py", line 10, in <module>
                                                       from .client import JellyfinClient
                                                     File "/nix/store/cbqyg6hzn180yq61v7c5zj0q95dy5mkj-kodi-19.1-env/share/kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/client.py", line 11, in <module>
                                                       from .ws_client import WSClient
                                                     File "/nix/store/cbqyg6hzn180yq61v7c5zj0q95dy5mkj-kodi-19.1-env/share/kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/ws_client.py", line 17, in <module>
                                                       import websocket  # noqa: E402,I201
                                                   ModuleNotFoundError: No module named 'websocket'
                                                   -->End of Python script error report<--
```

I'm at a loss. :thinking:
Is anyone available to look at this?

**Comment by minijackson** [comment]
@aanderse That's weird, I tested your PR and built `kodi.withPackages (p: [ p.jellyfin-kodi ])` without issue. I haven't done any extensive testing of the Jellyfin addon, but the addon could be activated and I could see the settings menu, and could list the users of my own Jellyfin server

**Comment by aanderse** [comment]
@minijackson thanks for testing. Since this is websocket related my assumption would be that the error would only occur if you connected to a `jellyfin` server. Did you connect to a `jellyfin` server, or could you be bothered to test that?

**Comment by minijackson** [comment]
@aanderse from a fresh Kodi install, I can add my server, refresh the whole library, and play a video file.

**Comment by aanderse** [comment]
I blew away my `~/.kodi` directory and everything worked. I'm not sure what to say. It seems `kodi` downloaded some `python` dependencies against my wishes... maybe that was messing with things :man_shrugging: 

I think I need to set my `~/.kodi/addons` directory read-only so it will just let `nixpkgs` manage addons! :angry: 

Thank you very much for your testing @minijackson :heart:

**Comment by aanderse** [comment]
I guess the `jellyfin` error I had mentioned [here](https://github.com/NixOS/nixpkgs/pull/127173#issuecomment-865439469) was more of an issue than I thought. I believe this needs to be fixed before `jellyfin` is going to be usable without having to `rm -rf ~/.kodi`...

**Pull request merged**
