### PR TITLE
maintainers: remove ivar

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

CC @IvarWithoutBones if there's any objections.

I've noticed that Ivar has not participated in any reviews for over a year, and the following queries seem to agree.
[PRs authored by Ivar](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Aivarwithoutbones)
[PRs reviewed by Ivar](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+reviewed-by%3Aivarwithoutbones)

In accordance with the guidelines here: https://github.com/NixOS/nixpkgs/tree/master/maintainers#how-to-lose-maintainer-status
I am creating this PR to remove Ivar from maintainership, pending any response from them within the next week.

This does unfortunately indicate that a fair number of packages have been abandoned.

Overall retirement tracked under #290642

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
CC @NixOS/dotnet would any committers like to be added to the CODEOWNERS? (I believe this is limited to committers based on how GH permissions work.)

**Comment by corngood** [comment]
> would any committers like to be added to the CODEOWNERS for dotnet paths?

If there's no way to do this for the 'team', then you can put me in there.

Thanks for cleaning this up.  The rest looks good to me.

**Comment by eclairevoyant** [comment]
> If there's no way to do this for the 'team', then you can put me in there.

Yeah, the reason I mentioned that only committers can be added is the same reason I can't slap in `@NixOS/dotnet` in there - it'd basically prevent non-committers from joining that team per my understanding. Anyway I've added you in.

**Review by drupol — CHANGES_REQUESTED** [review]
Sorry for being picky, but I would do this PR in 2 commits.

- 1 for removing `ivar`
- 1 for adding `corngood`

**Review by drupol — APPROVED** [review]

**Pull request merged**
