### PR TITLE
nextcloud: 20.0.11 -> 20.0.12, 21.0.3 -> 21.0.4, 22.0.0 -> 22.1.0

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

* https://nextcloud.com/changelog/#20-0-12
* https://nextcloud.com/changelog/#21-0-4
* https://nextcloud.com/changelog/#22-1-0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132920` at 985d9f39 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>nextcloud20</li>
    <li>nextcloud21</li>
    <li>nextcloud22</li>
    <li>nixos-install-tools</li>
  </ul>
</details>

**Comment by Kranzes** [comment]
@Ma27 I wanted to ask if you think it will be a good idea to have it so every nextcloud package with a version bigger than 20 will use PHP8 instead of PHP7, since nextcloud 21 and up support PHP8?

**Comment by Ma27** [comment]
Seems reasonable. We should perhaps do an if/else to decide whether to use php 7.4 or 8 depending on the nextcloud version in the module :)

**Comment by Kranzes** [comment]
I tried doing that but couldn't make up my mind on how to do it, could you please make a PR for that change?

**Review by Kranzes — APPROVED** [review]

**Pull request merged**
