### PR TITLE
gitkraken: 6.4.1 -> 6.5.1

### PR DESCRIPTION
**Pull request by evanjs**
###### Motivation for this change
https://support.gitkraken.com/release-notes/current/#version-651

###### Things done

- use ar instead of dpkg for unpackCmd to avoid attempts by the package
  to change permissions and etc.
- add at-spi2-core dependency
- remove dpkg dependency

Open to comments on the change to the `unpackCmd`.  As far as I can tell, the application seems to work the same as before.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by megheaiulian** [comment]
@evanjs If you want to drop `dpkg` dependency it might also make sense to fetch the `*.tar.gz` file instead of the `*.deb` one.

**Review by megheaiulian — APPROVED** [review]
Tested this and the executable works correctly. If you want to go with the suggestion to fetch `tar.gz` it would be great. Otherwise it can be done in a future update.

**Comment by evanjs** [comment]
``` diff
diff --git a/pkgs/applications/version-management/gitkraken/default.nix b/pkgs/applications/version-management/gitkraken/default.nix
index 83368932e25..73d376396a6 100644
--- a/pkgs/applications/version-management/gitkraken/default.nix
+++ b/pkgs/applications/version-management/gitkraken/default.nix
@@ -1,7 +1,7 @@
 { stdenv, libXcomposite, libgnome-keyring, makeWrapper, udev, curl, alsaLib
 , libXfixes, atk, gtk3, libXrender, pango, gnome3, cairo, freetype, fontconfig
 , libX11, libXi, libxcb, libXext, libXcursor, glib, libXScrnSaver, libxkbfile, libXtst
-, nss, nspr, cups, fetchurl, expat, gdk-pixbuf, libXdamage, libXrandr, dbus
+, nss, nspr, cups, fetchzip, expat, gdk-pixbuf, libXdamage, libXrandr, dbus
 , makeDesktopItem, openssl, wrapGAppsHook, at-spi2-atk, at-spi2-core, libuuid
 , e2fsprogs, krb5
 }:
@@ -15,11 +15,14 @@ stdenv.mkDerivation rec {
   pname = "gitkraken";
   version = "6.5.1";
 
-  src = fetchurl {
-    url = "https://release.axocdn.com/linux/GitKraken-v${version}.deb";
-    sha256 = "1zcbbszz7vnwgd4hxwhbp28gminc3pqk0v7id7jc8ylnbgpiy2bk";
+  src = fetchzip {
+    url = "https://release.axocdn.com/linux/GitKraken-v${version}.tar.gz";
+    sha256 = "0dwjwismv4rfw58801g2ay51h9qrffcxgbl910frd4i530w0y44p";
   };
 
+  dontBuild = true;
+  dontConfigure = true;
+
   libPath = makeLibraryPath [
     stdenv.cc.cc.lib
     curlWithGnuTls
@@ -73,29 +76,24 @@ stdenv.mkDerivation rec {
   nativeBuildInputs = [ makeWrapper wrapGAppsHook ];
   buildInputs = [ gtk3 gnome3.adwaita-icon-theme ];
 
-  unpackCmd = ''
-    mkdir out
-    pushd out
-
-    # manually unpack deb to avoid attempts at changing utime, permissions, etc
-    ar x $curSrc
-    tar -xf data.tar.xz
-    popd
-  '';
-
   installPhase = ''
     runHook preInstall
-    mkdir $out
-    pushd usr
-    pushd share
-    substituteInPlace applications/gitkraken.desktop \
-      --replace /usr/share/gitkraken $out/bin
-    popd
-    rm -rf bin/gitkraken share/lintian
-    cp -av share bin $out/
-    popd
 
+    mkdir -p $out/share/gitkraken/
+    cp -R $src/* $out/share/gitkraken/
+
+    mkdir -p $out/bin
     ln -s $out/share/gitkraken/gitkraken $out/bin/gitkraken
+
+    mkdir -p $out/share/applications
+    cp ${desktopItem}/share/applications/* $out/share/applications/
+
+    substituteInPlace $out/share/applications/gitkraken.desktop \
+      --replace $out/usr/share/gitkraken $out/bin
+
+    mkdir -p $out/share/pixmaps
+    cp gitkraken.png $out/share/pixmaps/gitkraken.png
+
     runHook postInstall
   '';
 
```

Mrm this seems to work, just not sure on the cleanliness

**Comment by megheaiulian** [comment]
That looks good to me and is in fact cleaner that what's being done for the deb version. I think you should commit that.

**Comment by evanjs** [comment]
> That looks good to me and is in fact cleaner that what's being done for the deb version. I think you should commit that.

Sounds good.  Thanks for the review!

**Pull request merged**
