### PR TITLE
Remove Qt 5.3

### PR DESCRIPTION
**Pull request by ttuegel**
This pull request removes Qt 5.3 from Nixpkgs. We have had Qt 5.4 for a long time now, and almost all packages have finally been updated to use it.

I bumped the Qt dependency on the following packages:
- hsqml: build in progress (takes a long time because it needs `qt5Full`)
- mgba: build OK
- linssid: build broken, a vendored dependency seems to be incompatible /cc @bjornfor 

As many are probably now aware, I am currently in the process of updating to Qt 5.5 / KDE Frameworks 5.14. This is the first of several incremental changes resulting from that effort. Qt 5.3 was the last version which had monolithic packages; for Qt >= 5.4, we carry each submodule separately in Nixpkgs. I want to have packages that depend on Qt built with each available version of Qt. This is absolutely necessary for libraries, but it may be nice for other packages, too. To do this, I need all the packages depending on the split Qt packages.

### CODE REVIEW

**Comment by bjornfor** [comment]
Regarding linssid breaking with newer Qt.

* Isn't the fact that linssid depends on qt53 enough to keep qt53 around? (That's part of the cool thing about nix -- multiple versions can (trivially) co-exist.)
* If upstream (linssid) isn't active enough to keep the project working as its dependencies move forward, it can die.

I have no strong opinion and would be OK with the merge. Just wondering how much trouble it would be to keep qt53 around a little longer so that we don't break linssid...

**Comment by ttuegel** [comment]
We can keep Qt 5.3 around, but I wouldn't say it's trivial: the last Hydra build took 3h20m.

It looks like the build problem with LinSSID is with the bundled QWT. However, we have QWT in Nixpkgs and it builds fine with Qt 5.4. This may simply be an issue of upstream not bumping their vendored dependencies. I wonder if we could build it with our QWT instead?

**Comment by ttuegel** [comment]
> However, we have QWT in Nixpkgs and it builds fine with Qt 5.4.

Strike that, our QWT is built with Qt 4 for some bizarre reason.

**Comment by ttuegel** [comment]
OK, we have QWT 6 built with QT 5.4 and LinSSID patched to remove the bundled QWT version.

**Comment by bjornfor** [comment]
@ttuegel: Thanks!

**Pull request merged**
