### PR TITLE
nixos/rss2email: remove unnecessary cfg file indirection to fix test

### PR DESCRIPTION
**Pull request by amesgen**
###### Description of changes

Before this, the NixOS test very often fails due to

```
server # [    7.098331] rss2email-pre-start[844]: cp: cannot create regular file '/var/rss2email/conf.cfg': Permission denied
```

https://hydra.nixos.org/build/197922377/nixlog/1

I think this is due to the config file being read-only after being copied from the Nix store. Usually, systemd-tmpfiles will correct this, but due to the short restart interval in the rss2email NixOS test, this is often not the case.

ZHF https://github.com/NixOS/nixpkgs/issues/199919

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ekleog** [comment]
rss2email used to require a mutable config file in order to execute properly, so the config file needed to be outside the store at the time.

Did you manually check that everything still works fine with this change?

**Comment by amesgen** [comment]
> rss2email used to require a mutable config file in order to execute properly, so the config file needed to be outside the store at the time.

Ah, your upstream issue has been resolved, and it is part of rss2email 3.14: https://github.com/rss2email/rss2email/issues/110

> Did you manually check that everything still works fine with this change?

Yes, the NixOS test here in nixpkgs still works fine, and I also tested it with my private rss2email setup.

**Comment by Ekleog** [comment]
Uhhh welp I had completely forgot this issue had been fixed, shame on me.

Thank you for the PR!

**Comment by Ekleog** [comment]
@ofborg build nixosTests.rss2email

**Pull request merged**
