### PR TITLE
dtc: fix build issues in Darwin

### PR DESCRIPTION
**Pull request by otavio**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — CHANGES_REQUESTED** [review]
`*-darwin` still fails on ofBorg CI, so I expect more fixes would needed before it makes sense to merge.

**Comment by otavio** [comment]
@vcunat Hey, I managed to get it working after a bit of a struggle. It was tough since I didn't have a Darwin target, but everything looks good now.

**Comment by AndersonTorres** [comment]
Lgtm, but no Darwin to test :/

**Comment by vcunat** [comment]
7500 rebuilds reported, so merging by a bit longer way.

**Comment by alyssais** [comment]
The patch to disable the tests [breaks cross-compilation](https://github.com/dgibson/dtc/pull/103#pullrequestreview-1473442177).  But also, why disable the tests instead of fixing them, or at least reporting the failure upstream?

**Comment by otavio** [comment]
@alyssais, unfortunately, I do not possess a Darwin device for testing. If you could offer your assistance, I would greatly appreciate it. I am willing to create a PR and modify the expression accordingly.

**Comment by alyssais** [comment]
I also don't. Perhaps we could just drop the patch, and mark it broken on Darwin? It wouldn't be surprising to me if dtc is not used much on Darwin.

**Pull request merged**
