### PR TITLE
sc-controller: 0.4.0.2 -> 0.4.1

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Regular update

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change (none)
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @orivej

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build sc-controller

**Comment by Mic92** [comment]
@rnhmjoj can you ask for borg access? https://github.com/NixOS/ofborg/pull/92

**Comment by rnhmjoj** [comment]
That makes it build my PR automatically?

**Comment by Mic92** [comment]
and on demand as your liking.

**Comment by rnhmjoj** [comment]
Sounds good, I'll ask tomorrow.

**Pull request merged**
