### PR TITLE
gomobile: init at 20190319-167ebed

### PR DESCRIPTION
**Pull request by pedropombeiro**
###### Motivation for this change

Add the gomobile tool which allows targetting mobile devices with Go.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by PombeirP** [comment]
Not sure what is wrong based on the bot message. How can I reproduce/fix it?

**Comment by samueldr** [comment]
I got a trace for the failure:

```
error: while evaluating anonymous function at /Users/samuel/tmp/ofborg/ofborg/src/outpaths.nix:44:12, called from undefined position:
while evaluating anonymous function at /Users/samuel/tmp/nixpkgs/nixpkgs-PR59018/pkgs/top-level/release-lib.nix:121:6, called from /Users/samuel/tmp/nixpkgs/nixpkgs-PR59018/lib/attrsets.nix:292:43:
while evaluating 'hydraJob' at /Users/samuel/tmp/nixpkgs/nixpkgs-PR59018/lib/customisation.nix:157:14, called from /Users/samuel/tmp/nixpkgs/nixpkgs-PR59018/pkgs/top-level/release-lib.nix:121:14:
while evaluating the attribute 'drvPath' at /Users/samuel/tmp/nixpkgs/nixpkgs-PR59018/lib/customisation.nix:174:13:
while evaluating the attribute 'drvPath' at /Users/samuel/tmp/nixpkgs/nixpkgs-PR59018/lib/customisation.nix:141:13:
while evaluating the attribute 'buildInputs' of the derivation 'gomobile-20190319-167ebed' at /Users/samuel/tmp/nixpkgs/nixpkgs-PR59018/lib/attrsets.nix:194:41:
cannot coerce a function to a string, at /Users/samuel/tmp/nixpkgs/nixpkgs-PR59018/lib/attrsets.nix:194:41
```

It's related to the `meta.platform` attribute.

Of note, it shouldn't really be `unix` unless it is known to build and work on all unices. If you meant "works on Linux and macOS" it would be more prudent to concat linux and darwin's platforms. e.g. `platforms = platforms.linux ++ platforms.darwin;`.

I'm not sure why the `unix` platform fails like that, but using `linux` instead does eval.

**Comment by PombeirP** [comment]
Thanks for the insight @samueldr! will try that

**Comment by PombeirP** [comment]
Hmm, there's still an issue there.

**Comment by samueldr** [comment]
Here are the instructions to run the meta checks locally:

 * https://github.com/NixOS/ofborg/#running-meta-checks-locally

With preliminary testing it looks like it doesn't eval for darwin; it will eval with only linux as a platform, and will not eval with only darwin as a platform. This points towards it not evaluating on darwin.

Preliminary look, `cannot coerce a function to a string` is the kind of error you'll see when trying to use something that's not derivation like a derivation would be used. I'm thinking that `xcodeenv.composeXcodeWrapper` is being misused as `xcodeWrapper`; but I do not know how as I know next to nothing to how Nixpkgs works on Darwin.

**Comment by PombeirP** [comment]
Thanks, you were right, I was using `composeXcodeWrapper` as a function because I wasn't passing the arguments. Fixed.

**Comment by xeji** [comment]
@GrahamcOfBorg build gomobile

**Review by xeji — CHANGES_REQUESTED** [review]
Please fix build failure, see logs. Apparently a patch fails to apply.

**Comment by PombeirP** [comment]
Thanks for the heads up. It's weird that the patch fails to apply, as I'm checking out a precise revision of the source, and this same `gomobile/default.nix` is working on a project I'm working on.

**Comment by PombeirP** [comment]
@GrahamcOfBorg build gomobile

**Comment by PombeirP** [comment]
@GrahamcOfBorg build gomobile

**Comment by PombeirP** [comment]
@GrahamcOfBorg build gomobile

**Pull request closed without merging**
