### PR TITLE
khal: 0.9.10 -> 0.10.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://github.com/pimutils/khal/releases/tag/v0.10.0

* new dep, click-log
* enable tests (pass!)

Release notes mention 'only dateutil < 2.7 is supported',
which may be a problem as ours is currently 2.8.

There's a history of python-dateutil version particularity
in previous releases (such as 0.9.10 upgrading from),
unsure if should override to older or if it's just a suggestion.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by gebner** [comment]
> Release notes mention 'only dateutil < 2.7 is supported', which may be a problem as ours is currently 2.8.

I don't know where that remark comes from.  Upstream even has travis tests with the latest dateutil.  I'm fine with using dateutil 2.8 as long as khal works.

> enable tests (pass!)

They are broken on aarch64.

**Comment by gebner** [comment]
I'm also running into a weird bug:
```
./result/bin/khal calendar                               Thu 28 Mar 2019 12:56:41 PM CET
Traceback (most recent call last):
  File "/nix/store/9a275n04cphzvs2fsiv32nyyi54y1qzm-khal-0.10.0/bin/.khal-wrapped", line 11, in <module>
    sys.exit(main_khal())
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/9a275n04cphzvs2fsiv32nyyi54y1qzm-khal-0.10.0/lib/python3.7/site-packages/khal/cli.py", line 266, in calendar
    multi_calendar_select(ctx, include_calendar, exclude_calendar)
  File "/nix/store/9a275n04cphzvs2fsiv32nyyi54y1qzm-khal-0.10.0/lib/python3.7/site-packages/khal/cli.py", line 165, in build_collection
    'priority': cal['priority'],
  File "/nix/store/0w0py9sa3912782fnir4qi3hwlbnaf0j-python3.7-configobj-5.0.6/lib/python3.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'priority'
```

**Comment by cvoges12** [comment]
@gebner Are you specifying the `timedelta` in the khal config file? I think there may be a slightly unrelated issue since v0.9.9.

**Comment by gebner** [comment]
@cvoges12 No, but I have `type = discover` calendars which are now broken due to recent `priority` feature.  I'll make a PR to the khal repo with a fix tomorrow.

**Comment by gebner** [comment]
Upstream already fixed the issue with `type = discover` calendars in the [0.10.1 release](https://github.com/pimutils/khal/releases/tag/v0.10.1) yesterday.

@dtzWill Could you update the version to 0.10.1 and disable the tests again (maybe only for aarch64?)?

**Pull request merged**
