### PR TITLE
postgresql: support JIT

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

JIT compilation of PostgreSQL queries. Disabled by default for now.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Tested by `EXPLAIN ANALYZE`ing queries with JIT force-enabled.

### CODE REVIEW

**Comment by marsam** [comment]
Please see the discussion in previous attempt https://github.com/NixOS/nixpkgs/pull/124804.
You also need to include a test to verify that JIT works

**Comment by abbradar** [comment]
@marsam Thanks for pointing the prior work up, it was very helpful!

I added an assertion to ensure that `jitSupport` is not used on older PostgreSQL versions and cherry-picked @thoughtpolice's patch to move bitcode to `$out`. It turned out (as shown in my patch before) it's not necessary to use `clangStdenv` -- PostgreSQL can be compiled with GCC while using `clang` only for bitcode generation. This way we also don't have new `stdenv.cc` references, so https://github.com/NixOS/nixpkgs/commit/8caf52331f6a3d8c1ddaf2aa7fd0530c6c748e0f is not necessary.

I also changed recursion scheme for PostgreSQL to a more widely used `let this = ...; in this`. This allows one to override `postgresql` flags in a friendlier way than it was before, when the derivation effectively looked itself up in the package set.

I'm not sure about tests, because adding them would mean also adding `postgresqlJit` to our package set (we don't build it with JIT by default right now). I did test before that JIT works in exactly the same way @andir's tests do. What do you think @marsam?

**Comment by abbradar** [comment]
Actually I re-tested it right now, and it turns out https://github.com/NixOS/nixpkgs/commit/91841ffa74f616f65af5ea5fb421fa534c26acaa breaks JIT.

I also considered https://github.com/NixOS/nixpkgs/pull/124804#issuecomment-864616931, but I'm honestly afraid to do so much (possibly fragile) patching for a feature that's not even enabled by default.

**Comment by abbradar** [comment]
I accidentally noticed that Python uses the same way of getting a self reference as PostgreSQL here: instead of `let self = stdenv.mkDerivation {...}; in self` it receives a `self` argument, which is passed from the surrounding code. In both implementations the `self` is not actually a reference to the same package, but to the package that is defined in an attrset somewhere.

I can't grasp any merits of this implementation; for example, this leads to unexpected results when evaluating, say, `(postgresql.override { jitSupport = true; }).pkgs.postgis`. However I feel it must be something there that I don't see -- what is it?

**Comment by abbradar** [comment]
@marsam I propose to go forward for now and change the recursion implementation -- this will allow `(postgresql.override { jitSupport = true; }).pkgs.postgis`, among other things.

Do you have an opinion on whether/how to implement tests?

**Comment by abbradar** [comment]
@marsam Kind ping -- do you still consider adding `postgresqlJit` to our package set and testing a necessity?

**Comment by abbradar** [comment]
@marsam I'm sorry for the noise, but can you take a quick look? These changes feel low-risk to me given default PostgreSQL build left as is, so I'd just go forward but it feels uncomfortable given you raised the point about testing. If you feel we should build JIT version on Hydra I can add a NixOS test -- my concern is about building a package which most users won't need.

**Comment by RaitoBezarius** [comment]
> @marsam I'm sorry for the noise, but can you take a quick look? These changes feel low-risk to me given default PostgreSQL build left as is, so I'd just go forward but it feels uncomfortable given you raised the point about testing. If you feel we should build JIT version on Hydra I can add a NixOS test -- my concern is about building a package which most users won't need.

Apologies for the delay, can I help you to get this merged?

**Comment by Ma27** [comment]
@RaitoBezarius First of all, I'm also interested in this (in fact I'm using something similar as overlay for my personal infrastructure). Since it doesn't seem that @abbradar is that active these days I'd suggest the following approach:
* rebase to resolve all conflcits
* ensure that it builds fine on darwin (see https://github.com/NixOS/nixpkgs/pull/124804#issuecomment-851026202)
* Reuse the testcases of https://github.com/NixOS/nixpkgs/pull/124804/files#diff-3a42b48b7f16bcd385b7dd58ce1ee44bfa2826cf7218faef19bb034945eda68b
* get some feedback from @marsam if that's OK after that.

I think the increase in closure size is OK since it's just an opt-in feature. However @dasJ do you still use the code from https://github.com/NixOS/nixpkgs/pull/124804#issuecomment-864616931? Perhaps we could use that in here as well to get a bit of closure size reduction.

Do you want to take care of that? Otherwise I can try to do that soonish (though I'm kinda involved with exams these days).

**Comment by dasJ** [comment]
@Ma27 current code:
```
    package = mkOption {
      type = package;
      description = "PostgreSQL package to use";
      default = pkgs.postgresql_13;
      defaultText = "pkgs.postgresql_13";
      # Patch in JIT support if needed
      # See https://github.com/NixOS/nixpkgs/pull/124804#issuecomment-864616931
      apply = x: if cfg.enableJit then (x.overrideAttrs (oA: {
        nativeBuildInputs = (oA.nativeBuildInputs or []) ++ [ pkgs.llvmPackages_latest.llvm pkgs.nukeReferences pkgs.patchelf ];
        configureFlags = (oA.configureFlags or []) ++ [ "--with-llvm" ];
        postPatch = ''
          ${oA.postPatch or ""}

          # Force lookup of jit stuff in $out instead of $lib
          substituteInPlace src/backend/jit/jit.c --replace pkglib_path \"$out/lib\"
          substituteInPlace src/backend/jit/llvm/llvmjit.c --replace pkglib_path \"$out/lib\"
          substituteInPlace src/backend/jit/llvm/llvmjit_inline.cpp --replace pkglib_path \"$out/lib\"
        '';

        # upstream enabled pie, which breaks the build: https://github.com/NixOS/nixpkgs/pull/124188
        hardeningEnable = [];

        postInstall = ''
          ${oA.postInstall or ""}

          # Move the bitcode and libllvmjit.so library out of $lib; otherwise, every client that
          # depends on libpq.so will also have libLLVM.so in its closure too, bloating it
          moveToOutput "lib/bitcode" "$out"
          moveToOutput "lib/llvmjit*" "$out"

          # In the case of JIT support, prevent a retained dependency on clang-wrapper
          substituteInPlace "$out/lib/pgxs/src/Makefile.global" --replace ${pkgs.llvmPackages_latest.stdenv.cc}/bin/clang clang
          nuke-refs $out/lib/llvmjit_types.bc $(find $out/lib/bitcode -type f)

          # Stop out depending on the default output of llvm
          substituteInPlace $out/lib/pgxs/src/Makefile.global \
            --replace ${pkgs.llvmPackages_latest.llvm.out}/bin "" \
            --replace '$(LLVM_BINPATH)/' ""

          # Stop out depending on the -dev output of llvm
          substituteInPlace $out/lib/pgxs/src/Makefile.global \
            --replace ${pkgs.llvmPackages_latest.llvm.dev}/bin/llvm-config llvm-config \
            --replace -I${pkgs.llvmPackages_latest.llvm.dev}/include ""

          # Stop lib depending on the -dev output of llvm
          rpath=$(patchelf --print-rpath $out/lib/llvmjit.so)
          nuke-refs -e $out $out/lib/llvmjit.so
          # Restore the correct rpath
          patchelf $out/lib/llvmjit.so --set-rpath "$rpath"
        '';
      })).override {
        stdenv = pkgs.llvmPackages_latest.stdenv;
      } else x;
    };
```

and yes, that code is running in production ;)

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius First of all, I'm also interested in this (in fact I'm using something similar as overlay for my personal infrastructure). Since it doesn't seem that @abbradar is that active these days I'd suggest the following approach:

Awesome!

> * rebase to resolve all conflcits
> * ensure that it builds fine on darwin (see [postgresql: support JIT compilation for version >= 11 #124804 (comment)](https://github.com/NixOS/nixpkgs/pull/124804#issuecomment-851026202))
> * Reuse the testcases of https://github.com/NixOS/nixpkgs/pull/124804/files#diff-3a42b48b7f16bcd385b7dd58ce1ee44bfa2826cf7218faef19bb034945eda68b
> * get some feedback from @marsam if that's OK after that.

Got it.

> I think the increase in closure size is OK since it's just an opt-in feature. However @dasJ do you still use the code from [#124804 (comment)](https://github.com/NixOS/nixpkgs/pull/124804#issuecomment-864616931)? Perhaps we could use that in here as well to get a bit of closure size reduction.

> Do you want to take care of that? Otherwise I can try to do that soonish (though I'm kinda involved with exams these days).

I cannot take care of anything yet but I am open to reviewing :).

**Comment by Ma27** [comment]
Have a more or less working draft locally, need to check if all extensions are still fine and write something for the release notes. Would file a new PR at some point the next days :)

**Pull request closed without merging**
