### PR TITLE
nixos/writefreely: init

### PR DESCRIPTION
**Pull request by jakehamilton**
###### Description of changes

This PR adds a new NixOS module for running [WriteFreely](https://writefreely.org/) ([`pkgs.writefreely`](https://search.nixos.org/packages?channel=22.05&show=writefreely&from=0&size=50&sort=relevance&type=packages&query=writefreely)).

Example usage (with the default SQLite database):

```nix
{
  services.writefreely = {
    enable = true;
    
    admin.name = "nixos";
    # You can provide an initial password, otherwise the default will be set to "nixos".
    # admin.initialPasswordFile = "/opt/my-initial-admin-pass.txt";
  };
}
```

Example usage (with the MySQL database):

```nix
{
  services.writefreely = {
    enable = true;
    
    admin.name = "nixos";
    # You can provide an initial password, otherwise the default will be set to "nixos".
    # admin.initialPasswordFile = "/opt/my-initial-admin-pass.txt";
    
    database = {
      type = "mysql";
      
      # We can spin up MySQL locally.
      createLocally = true;
      
      # A password is required for WriteFreely to work.
      passwordFile = "/opt/my-db-pass.txt";
    };
  };
}
```

Example usage (with nginx):

```nix
{
  services.writefreely = {
    enable = true;
    
    admin.name = "nixos";
    # You can provide an initial password, otherwise the default will be set to "nixos".
    # admin.initialPasswordFile = "/opt/my-initial-admin-pass.txt";
    
    nginx.enable = true;
  };
}
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ck3d** [comment]
Thanks for your PR. Can you please update to latest master.

**Comment by jakehamilton** [comment]
Hey @ck3d, thanks for letting me know. I'll see if I can find some time to rebase these changes 👍

**Comment by jakehamilton** [comment]
Alright, PR should be updated @ck3d :+1:

**Review by ck3d — APPROVED** [review]
Thanks for the exemplary PR.

**Pull request merged**
