### PR TITLE
samsung-unified-linux-driver_1_00_37: fix build failing due to upstre…

### PR DESCRIPTION
**Pull request by kierdavis**
###### Motivation for this change

This package currently fails to build (see discussion at https://github.com/NixOS/nixpkgs/issues/16238). For example, adding `pkgs.samsung-unified-linux-driver_1_00_37` to `services.printing.drivers` in a NixOS config produces the following log during `nixos-rebuild`:

```
building path(s) ‘/nix/store/sgn1j45d294pki382hhb0y3wph9dkald-samsung-unified-linux-driver-1.00.37’
unpacking sources
unpacking source archive /nix/store/sbq3fbrr6ghafzyblmg1frsr07bqwbxb-UnifiedLinuxDriver-1.00.37.tar.gz
source root is uld
setting SOURCE_DATE_EPOCH to timestamp 1446798741 of file uld/i386/usbresetter
installing
Patching ELF file: x86_64/pstosecps
Patching ELF file: x86_64/rastertospl
Patching ELF file: x86_64/smfpnetdiscovery
	libstdc++.so.6 => not found
builder for ‘/nix/store/9hm3z7flhdgp2dysf7r9v65hi4bkijnr-samsung-unified-linux-driver-1.00.37.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/ilib2s66bx6wzj98l153q48nm87i15kr-cups-progs.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/b1z7zyc3h9zdmmmx7257cbnz2xskmnas-unit-script.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/cpp2bbsisma0fkp4949m7fyfvdn5f93f-unit-cups.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/j92a5ldwaf7wgl14pia95zksh2b5pm8y-system-units.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/i4110pav2l92h7xi5da60ffra9fn8dyq-etc.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/j9bsg14zylkrzz2dgwhhj98bq9nfvrhy-nixos-system-coloris-17.03pre94121.210b3b3.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/j9bsg14zylkrzz2dgwhhj98bq9nfvrhy-nixos-system-coloris-17.03pre94121.210b3b3.drv’ failed
```

This change makes the package less broken. All credit for this change goes to @jokogr (see also: https://github.com/jokogr/nixpkgs/commit/c41e771a388dca6cb5f15edab2fd36fd6f96c8a8).

With this change, printing works on M2875FD and M2675FN models. Scanning not tested yet due to lack of access to Samsung scanning devices.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nckx** [comment]
Thanks! I'll merge after @jokogr's stamp of approval, since the attribution won't be included in the commit.

**Comment by kierdavis** [comment]
Huh, I thought I'd linked the source in the commit message; seems I didn't. I'll go fix that now.

**Comment by kierdavis** [comment]
(in hindsight I should probably have cherry-picked the [original commit](https://github.com/jokogr/nixpkgs/commit/c41e771a388dca6cb5f15edab2fd36fd6f96c8a8) rather than copying and pasting into my own, but I'm not very good at git :P )

**Comment by nckx** [comment]
Seems to build fine on Linux; merging.

**Pull request merged**
