### PR TITLE
lutris 5.7.1 to 5.8.1

### PR DESCRIPTION
**Pull request by JeffLabonte**
###### Motivation for this change
I wanted to get the latest version of Lutris.

###### Things done
Updated the version of Lutris and added me as a maintainer of this package.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
To comply with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) please have the commit message name be of the format
```
<pkg-name>: <subject-line>
```
for more examples, please look at https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

in your case, the commit message should be:
```
lutris: 5.7.1 -> 5.8.1
```

**Comment by JeffLabonte** [comment]
@jonringer This is one of the reasons, I have put this on draft. Lutris is also unable to find vulkan.

**Comment by jonringer** [comment]
there was always a warning, but most games launched fine

**Comment by JeffLabonte** [comment]
@jonringer I am currently using the package to play some of my games, but now it isn't able to access the Vulkan libraries. 

It would have made things easier it would have just given me a warning.

**Comment by jonringer** [comment]
I must not be playing any games using vulkan then

**Pull request closed without merging**
