### PR TITLE
kooha: 1.1.3 -> 1.2.1

### PR DESCRIPTION
**Pull request by austinbutler**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/pull/123454 (which I don't have the power to fix myself), upgrades to latest.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 124222` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>kooha</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@austinbutler Can you take a look at the aarch64 build failure?

**Comment by austinbutler** [comment]
Found https://github.com/NixOS/nixpkgs/issues/116195, but adding `pkg-config` to `depsBuildBuild` results in the same `Pkg-config binary for machine MachineChoice.BUILD not found. Giving up.` error.

**Comment by austinbutler** [comment]
Also tried the fix in https://github.com/NixOS/nixpkgs/pull/112405 with no change.

**Comment by austinbutler** [comment]
Probably should have read the output more carefully, looks like it's probably due to this: https://github.com/NixOS/nixpkgs/issues/88959

**Comment by austinbutler** [comment]
And then the next issue is with `asciidoc`, same failure and fix as https://github.com/NixOS/nixpkgs/pull/112695#issuecomment-800500797. Then after that `gstreamer`.

**Comment by austinbutler** [comment]
Cross compilation seems broken layers deep (or I'm just doing it wrong), so I tried instead going the [QEMU route in the wiki](https://nixos.wiki/wiki/NixOS_on_ARM#Compiling_through_QEMU), and that seems to have worked, although I don't know how to test the output.

**Comment by austinbutler** [comment]
@ofborg eval

**Comment by austinbutler** [comment]
@ofborg build

**Comment by austinbutler** [comment]
Looks like re-running build without any changes worked, so guessing it was a fluke?

**Comment by SuperSandro2000** [comment]
> Looks like re-running build without any changes worked, so guessing it was a fluke?

or some change landed in master in the meanwhile that fixed it.

**Pull request merged**
