### PR TITLE
python312Packages.dulwich: 0.21.7 -> 0.22.1

### PR DESCRIPTION
**Pull request by fabaff**
Changelog: https://github.com/jelmer/dulwich/blob/dulwich-0.22.1/NEWS

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
404

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 306291` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.subunit2sql</li>
    <li>python311Packages.subunit2sql.dist</li>
    <li>rabbitvcs</li>
    <li>rabbitvcs.cli</li>
    <li>rabbitvcs.dist</li>
  </ul>
</details>
<details>
  <summary>144 packages failed to build:</summary>
  <ul>
    <li>breezy (python311Packages.breezy)</li>
    <li>breezy.dist (python311Packages.breezy.dist)</li>
    <li>cabal2nix</li>
    <li>calendar-cli</li>
    <li>calendar-cli.dist</li>
    <li>dep2nix</li>
    <li>devpi-client</li>
    <li>devpi-client.dist</li>
    <li>dvc (python311Packages.dvc)</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>dvc.dist (python311Packages.dvc.dist)</li>
    <li>errands</li>
    <li>errbot</li>
    <li>errbot.dist</li>
    <li>flatpak-builder</li>
    <li>flatpak-builder.doc</li>
    <li>flatpak-builder.installedTests</li>
    <li>flatpak-builder.man</li>
    <li>glanceclient (python311Packages.python-glanceclient)</li>
    <li>glanceclient.dist (python311Packages.python-glanceclient.dist)</li>
    <li>gtg</li>
    <li>heatclient (python311Packages.python-heatclient)</li>
    <li>heatclient.dist (python311Packages.python-heatclient.dist)</li>
    <li>home-assistant-component-tests.caldav</li>
    <li>html5validator</li>
    <li>html5validator.dist</li>
    <li>hydra_unstable</li>
    <li>ironicclient (python311Packages.python-ironicclient)</li>
    <li>ironicclient.dist (python311Packages.python-ironicclient.dist)</li>
    <li>jenkins-job-builder (python311Packages.jenkins-job-builder)</li>
    <li>jenkins-job-builder.dist (python311Packages.jenkins-job-builder.dist)</li>
    <li>klaus (python311Packages.klaus)</li>
    <li>klaus.dist (python311Packages.klaus.dist)</li>
    <li>luarocks-packages-updater</li>
    <li>manilaclient (python311Packages.python-manilaclient)</li>
    <li>manilaclient.dist (python311Packages.python-manilaclient.dist)</li>
    <li>netbox (netbox_3_7)</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>openstackclient (python311Packages.python-openstackclient)</li>
    <li>openstackclient.dist (python311Packages.python-openstackclient.dist)</li>
    <li>poetry</li>
    <li>poetry.dist</li>
    <li>poetryPlugins.poetry-audit-plugin</li>
    <li>poetryPlugins.poetry-audit-plugin.dist</li>
    <li>poetryPlugins.poetry-plugin-up</li>
    <li>poetryPlugins.poetry-plugin-up.dist</li>
    <li>python311Packages.caldav</li>
    <li>python311Packages.caldav.dist</li>
    <li>python311Packages.check-manifest</li>
    <li>python311Packages.check-manifest.dist</li>
    <li>python311Packages.cliff</li>
    <li>python311Packages.cliff.dist</li>
    <li>python311Packages.dulwich</li>
    <li>python311Packages.dulwich.dist</li>
    <li>python311Packages.dvc-gdrive</li>
    <li>python311Packages.dvc-gdrive.dist</li>
    <li>python311Packages.dvc-hdfs</li>
    <li>python311Packages.dvc-hdfs.dist</li>
    <li>python311Packages.dvc-studio-client</li>
    <li>python311Packages.dvc-studio-client.dist</li>
    <li>python311Packages.dvclive</li>
    <li>python311Packages.dvclive.dist</li>
    <li>python311Packages.gto</li>
    <li>python311Packages.gto.dist</li>
    <li>python311Packages.hacking</li>
    <li>python311Packages.hacking.dist</li>
    <li>python311Packages.hg-git</li>
    <li>python311Packages.hg-git.dist</li>
    <li>python311Packages.keystoneauth1</li>
    <li>python311Packages.keystoneauth1.dist</li>
    <li>python311Packages.openstackdocstheme</li>
    <li>python311Packages.openstackdocstheme.dist</li>
    <li>python311Packages.openstacksdk</li>
    <li>python311Packages.openstacksdk.dist</li>
    <li>python311Packages.osc-lib</li>
    <li>python311Packages.osc-lib.dist</li>
    <li>python311Packages.oslo-concurrency</li>
    <li>python311Packages.oslo-concurrency.dist</li>
    <li>python311Packages.oslo-config</li>
    <li>python311Packages.oslo-config.dist</li>
    <li>python311Packages.oslo-context</li>
    <li>python311Packages.oslo-context.dist</li>
    <li>python311Packages.oslo-db</li>
    <li>python311Packages.oslo-db.dist</li>
    <li>python311Packages.oslo-i18n</li>
    <li>python311Packages.oslo-i18n.dist</li>
    <li>python311Packages.oslo-log</li>
    <li>python311Packages.oslo-log.dist</li>
    <li>python311Packages.oslo-serialization</li>
    <li>python311Packages.oslo-serialization.dist</li>
    <li>python311Packages.oslo-utils</li>
    <li>python311Packages.oslo-utils.dist</li>
    <li>python311Packages.python-cinderclient</li>
    <li>python311Packages.python-cinderclient.dist</li>
    <li>python311Packages.python-jenkins</li>
    <li>python311Packages.python-jenkins.dist</li>
    <li>python311Packages.python-keystoneclient</li>
    <li>python311Packages.python-keystoneclient.dist</li>
    <li>python311Packages.python-novaclient</li>
    <li>python311Packages.python-novaclient.dist</li>
    <li>swiftclient (python311Packages.python-swiftclient)</li>
    <li>swiftclient.dist (python311Packages.python-swiftclient.dist)</li>
    <li>python311Packages.scmrepo</li>
    <li>python311Packages.scmrepo.dist</li>
    <li>python311Packages.simplekv</li>
    <li>python311Packages.simplekv.dist</li>
    <li>python311Packages.stestr</li>
    <li>python311Packages.stestr.dist</li>
    <li>python311Packages.tempest</li>
    <li>python311Packages.tempest.dist</li>
    <li>python312Packages.breezy</li>
    <li>python312Packages.breezy.dist</li>
    <li>python312Packages.caldav</li>
    <li>python312Packages.caldav.dist</li>
    <li>python312Packages.check-manifest</li>
    <li>python312Packages.check-manifest.dist</li>
    <li>python312Packages.dulwich</li>
    <li>python312Packages.dulwich.dist</li>
    <li>python312Packages.dvc-studio-client</li>
    <li>python312Packages.dvc-studio-client.dist</li>
    <li>python312Packages.gto</li>
    <li>python312Packages.gto.dist</li>
    <li>python312Packages.hg-git</li>
    <li>python312Packages.hg-git.dist</li>
    <li>python312Packages.klaus</li>
    <li>python312Packages.klaus.dist</li>
    <li>python312Packages.scmrepo</li>
    <li>python312Packages.scmrepo.dist</li>
    <li>python312Packages.simplekv</li>
    <li>python312Packages.simplekv.dist</li>
    <li>reno</li>
    <li>reno.dist</li>
    <li>silver-platter</li>
    <li>silver-platter.dist</li>
    <li>syncall</li>
    <li>syncall.dist</li>
    <li>vcstool</li>
    <li>vcstool.dist</li>
    <li>xandikos</li>
    <li>xandikos.dist</li>
  </ul>
</details>

**Comment by patryk4815** [comment]
```
error: builder for '/nix/store/lbqdv55g154vvy5cwgyxkv877xjvq11c-source.drv' failed with exit code 1;
       last 8 log lines:
       >
       > trying https://github.com/jelmer/dulwich/archive/refs/tags/0.22.1.tar.gz
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       >   0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (56) The requested URL returned error: 404
       > error: cannot download source from any mirror
       For full logs, run 'nix log /nix/store/lbqdv55g154vvy5cwgyxkv877xjvq11c-source.drv'.
error: 1 dependencies of derivation '/nix/store/l4cl1j0f18j2q3w55pazz0bycnznzpcc-python3.11-dulwich-0.22.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mc3vbrgnzrkcxm8ivaxvaylgqdkb3gcf-python3.11-poetry-1.8.2.drv' failed to build
```
@fabaff now it is broken, they have custom "tag" in github `dulwich-0.22.1` not `0.22.1`

**Comment by ShalokShalom** [comment]
Why was this merged?
This seems like a pretty obvious case of .. not merging? 
Because it breaks 144 packages?

**Comment by fabaff** [comment]
My bad, will revert it.

**Comment by ShalokShalom** [comment]
It was already reverted. 
[You approved the reversal. 
](https://github.com/NixOS/nixpkgs/pull/307380)
Who gave you commit rights? 🤨

**Comment by ShalokShalom** [comment]
I thought something should mention something, that someone runs havoc on the repos. 🙄

**Comment by ShalokShalom** [comment]
Sorry, I forgot that the **gold standards** of Nix involve pushing updates that had been not build before, break an entire ecosystem, and then blindly approving reversal of said changes.  

I thought someone should mention that this runs havoc on the repos 🙄

**Comment by ShalokShalom** [comment]
The thing is, that it seems almost impossible to do the right thing anyways. 
With the xz disaster in mind, how would that look like, if an issue is introduced **this way?**

And what is the optimal way going forward? 

Every time I note something that I find to be an issue, 
I make the experience that it is seen to be as a personal threat.

This community has devolved to the point where technical observations are only accepted, if you belong to the small circle of the enlightened.

The people in the community, who are the most dominant in the project, often turn out to reject feedback simply because they feel it makes them look bad.

We are supposed to be a group of computer *scientists* and yet I feel like in a kindergarten, where the strongest kids have taken over and play little dictators. 

I feel that way, I cannot express it without getting ridiculed and gaslight, and all that while I am fully aware, that I am also filled  with incorrect assumptions and mistakes.

But it cant go on like that. We all need to step back, breath, and see that Nix is falling apart. 

No doom speech, just what everyone thinks.

**Comment by vcunat** [comment]
I don't see Nix falling apart, but that's discussed elsewhere: https://discourse.nixos.org/t/nixos-is-not-dying-please-dont-spread-fear-actively/44310

Back to technical: in the staging-next branch (#306080) the 0.21.7 version is [failing a test](https://hydra.nixos.org/build/257960612/nixlog/1/tail), probably due to some other `python3Packages.*` updates.  So some change will be needed there soon, perhaps an update.  (I hoped to merge staging-next into master within a couple days.)

**Comment by fabaff** [comment]
I'm sorry, that I merged this and that it caused issues for people for a short period on `master`.

Should I get a slap on the wrist? I guess so and a reminder to wear my glasses all the time.

**Comment by ShalokShalom** [comment]
Sorry

**Comment by vcunat** [comment]
_(repost, hidden above)_ In the staging-next branch (https://github.com/NixOS/nixpkgs/pull/306080) the 0.21.7 version is [failing a test](https://hydra.nixos.org/build/257960612/nixlog/1/tail), probably due to some other python3Packages.* updates. So some change will be needed there soon, perhaps an update. (I hoped to merge staging-next into master within a couple days.)

**Comment by PerchunPak** [comment]
> (repost, hidden above) In the staging-next branch (https://github.com/NixOS/nixpkgs/pull/306080) the 0.21.7 version is [failing a test](https://hydra.nixos.org/build/257960612/nixlog/1/tail), probably due to some other python3Packages.* updates. So some change will be needed there soon, perhaps an update. (I hoped to merge staging-next into master within a couple days.)

@vcunat Actually it is resolved in 48e9da634f96ba306030ebcebf6fa74ea51672ab, but I cannot find this commit in `staging-next` even though GitHub GUI shows it is in there.

**Comment by vcunat** [comment]
Lost in merge resolutions apparently.  That commit is reachable from `staging-next` (and not from `master` so far).  But master in the meantime changed the expression back and forth, and it was continuously merged to `staging-next`.

I didn't feel like investigating it deep.  It's reapplied now.

**Pull request merged**
