### PR TITLE
beam-modules: fix phase deprecation

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

using the phases attributes is deprecated. An original PR did this for fetch-hex and fetch-rebar-deps, however the behavior changed a bit in which some phases where run
https://github.com/NixOS/nixpkgs/pull/134355/files

This PR removes the added phases that were being run.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
@NixOS/beam I made a mistake and merged a PR a bit fast. You might be interested in reviewing this PR.
Since master is currently broken, I will only wait one day before merging. However, if you have feedback, I'm happy to address it in subsequent PRs or review PRs that you would have.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 134386` at 7fdd117d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>pleroma</li>
  </ul>
</details>
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>elixir_ls</li>
    <li>elvis-erlang</li>
    <li>erlang-ls</li>
    <li>erlfmt</li>
    <li>lfe (lfe_1_3)</li>
    <li>plausible</li>
    <li>rebar3</li>
  </ul>
</details>

**Comment by Stunkymonkey** [comment]
i was surprised to see it merged. Is `dontFixup = true;` really needed? otherwise LGTM.

**Review by DianaOlympos — APPROVED** [review]

**Comment by happysalada** [comment]
@Stunkymonkey yeah it was too early in the morning.
dontFixup = true is more to keep the same behavior as was the original.

@DianaOlympos thank you for the review!

**Comment by Stunkymonkey** [comment]
>  dontFixup = true is more to keep the same behavior as was the original.

i agree, but one of the main arguments, why the phases should be deprecated was,that the `fixup-phase` was missing.

**Pull request merged**
