### PR TITLE
py-spy: 0.3.14 -> 0.3.14-unstable-2024-02-27; fix build, pin python311

### PR DESCRIPTION
**Pull request by kirillrdy**
## Description of changes

pin python to 3.11 to fix build and update to unstable to fix build on darwin

https://github.com/benfred/py-spy/compare/v0.3.14...8dd54929106916a3c961cc57c1172793ce126180

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 325422` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python312Packages.vllm</li>
    <li>python312Packages.vllm.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.kserve</li>
    <li>python311Packages.kserve.dist</li>
    <li>python312Packages.kserve</li>
    <li>python312Packages.kserve.dist</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>py-spy</li>
    <li>python311Packages.ray</li>
    <li>python311Packages.ray.dist</li>
    <li>python312Packages.ray</li>
    <li>python312Packages.ray.dist</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
fix kserve https://github.com/NixOS/nixpkgs/pull/325423

**Review by GaetanLepage — APPROVED** [review]

**Review by natsukium — APPROVED** [review]
We can update it to unstable to fix for darwin.

**Comment by kirillrdy** [comment]
at least  x86_64-darwin passes :-)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 325422` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.kserve</li>
    <li>python311Packages.kserve.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python312Packages.kserve</li>
    <li>python312Packages.kserve.dist</li>
    <li>python312Packages.vllm</li>
    <li>python312Packages.vllm.dist</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>py-spy</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 325422` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python312Packages.vllm</li>
    <li>python312Packages.vllm.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.kserve</li>
    <li>python311Packages.kserve.dist</li>
    <li>python312Packages.kserve</li>
    <li>python312Packages.kserve.dist</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>py-spy</li>
    <li>python311Packages.ray</li>
    <li>python311Packages.ray.dist</li>
    <li>python312Packages.ray</li>
    <li>python312Packages.ray.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 325422` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.kserve</li>
    <li>python311Packages.kserve.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python312Packages.kserve</li>
    <li>python312Packages.kserve.dist</li>
    <li>python312Packages.vllm</li>
    <li>python312Packages.vllm.dist</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>py-spy</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 325422` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.kserve</li>
    <li>python311Packages.kserve.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python312Packages.kserve</li>
    <li>python312Packages.kserve.dist</li>
    <li>python312Packages.vllm</li>
    <li>python312Packages.vllm.dist</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>py-spy</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Comment by kirillrdy** [comment]
@GaetanLepage wow thanks for such prompt response !

I'll leave some time for @SuperSandro2000 to have a look

**Comment by GaetanLepage** [comment]
@ofborg build py-spy

**Pull request merged**
