### PR TITLE
universal-pidff: 0.0.8 -> 0.0.10

### PR DESCRIPTION
**Pull request by DaRacci**
## Things done
https://github.com/JacKeTUs/universal-pidff/releases/tag/0.0.10

This is a very minimal update, no dependency changes and a few new wheels that won't break existing things.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by DaRacci** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.universal-pidff</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 16 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.universal-pidff</li>
    <li>linuxKernel.packages.linux_5_10_hardened.universal-pidff</li>
    <li>linuxKernel.packages.linux_5_15.universal-pidff</li>
    <li>linuxKernel.packages.linux_5_15_hardened.universal-pidff</li>
    <li>linuxKernel.packages.linux_5_4.universal-pidff</li>
    <li>linuxKernel.packages.linux_6_1.universal-pidff</li>
    <li>linuxKernel.packages.linux_6_11.universal-pidff</li>
    <li>linuxKernel.packages.linux_6_1_hardened.universal-pidff</li>
    <li>linuxKernel.packages.linux_6_6.universal-pidff</li>
    <li>linuxKernel.packages.linux_hardened.universal-pidff (linuxKernel.packages.linux_6_6_hardened.universal-pidff)</li>
    <li>linuxKernel.packages.linux_latest_libre.universal-pidff</li>
    <li>linuxKernel.packages.linux_libre.universal-pidff</li>
    <li>linuxKernel.packages.linux_lqx.universal-pidff</li>
    <li>linuxKernel.packages.linux_xanmod.universal-pidff</li>
    <li>linuxKernel.packages.linux_xanmod_latest.universal-pidff (linuxKernel.packages.linux_xanmod_stable.universal-pidff)</li>
    <li>linuxKernel.packages.linux_zen.universal-pidff</li>
  </ul>
</details>

**Review by NickCao — CHANGES_REQUESTED** [review]
hash is not updated.

**Comment by DaRacci** [comment]
Woops, that was what my force push was meant to do, the nixpkgs-review was ran with the correct hash.

**Review by computerdane — APPROVED** [review]

**Comment by NickCao** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352787`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.universal-pidff</li>
    <li>linuxPackages_5_4_hardened.universal-pidff</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 16 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.universal-pidff</li>
    <li>linuxPackages_5_10_hardened.universal-pidff (linuxKernel.packages.linux_5_10_hardened.universal-pidff)</li>
    <li>linuxKernel.packages.linux_5_15.universal-pidff</li>
    <li>linuxPackages_5_15_hardened.universal-pidff (linuxKernel.packages.linux_5_15_hardened.universal-pidff)</li>
    <li>linuxKernel.packages.linux_5_4.universal-pidff</li>
    <li>linuxKernel.packages.linux_6_1.universal-pidff</li>
    <li>linuxPackages_latest.universal-pidff (linuxKernel.packages.linux_6_11.universal-pidff)</li>
    <li>linuxPackages_6_1_hardened.universal-pidff (linuxKernel.packages.linux_6_1_hardened.universal-pidff)</li>
    <li>linuxPackages.universal-pidff (linuxKernel.packages.linux_6_6.universal-pidff)</li>
    <li>linuxPackages_hardened.universal-pidff (linuxPackages_6_6_hardened.universal-pidff)</li>
    <li>linuxPackages_latest-libre.universal-pidff (linuxKernel.packages.linux_latest_libre.universal-pidff)</li>
    <li>linuxPackages-libre.universal-pidff (linuxKernel.packages.linux_libre.universal-pidff)</li>
    <li>linuxPackages_lqx.universal-pidff (linuxKernel.packages.linux_lqx.universal-pidff)</li>
    <li>linuxPackages_xanmod.universal-pidff (linuxKernel.packages.linux_xanmod.universal-pidff)</li>
    <li>linuxPackages_xanmod_latest.universal-pidff (linuxKernel.packages.linux_xanmod_latest.universal-pidff ,linuxPackages_xanmod_stable.universal-pidff)</li>
    <li>linuxPackages_zen.universal-pidff (linuxKernel.packages.linux_zen.universal-pidff)</li>
  </ul>
</details>

**Review by NickCao — APPROVED** [review]

**Pull request merged**
