### PR TITLE
php82: 8.2.8 -> 8.2.9

### PR DESCRIPTION
**Pull request by drupol**
Security release: https://www.php.net/archive/2023.php#2023-08-16-1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
ok... **why** do we not backport PHP releases anymore? Especially if they're security relevant?

**Comment by drupol** [comment]
IIRC, we only backport security release.

**Comment by Ma27** [comment]
Like this one which also was merged without considering a backport?

Also, what's wrong with backporting bugfixes which is usually why patch-level releases are published? And finally, if we skip non-security releases, how shall we apply future security releases (i.e. after 8.2.8 was skipped, how should we apply the fixes from 8.2.9 without backporting 8.2.8 first)?

**Comment by drupol** [comment]
I was about to do it before you commented. I have many open tabs and following many PRs, you were just faster than me on this one.

I'll take care of the backport tomorrow or feel free to do it, I went to bed already.

**Comment by drupol** [comment]
Here we go: #249684

**Comment by etu** [comment]
With PHP... almost every release is a security related release... and even
if it isn't, the next one is. So PHP is always worth to backport :)

**Comment by Ma27** [comment]
@drupol just to avoid any misunderstanding: this was not a timing issue, i.e. I didn't expect you to do this immediately last night.

I'm just quick in pointing out missing backports because I sometimes get the impression (in nixpkgs in general) that stuff that should be backported just isn't.

**Pull request merged**
