### PR TITLE
xfig: 3.2.5b -> 3.2.7a

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
A real classic. I was surprised that the code is still maintained (last version from May 2018).
Resolves the problem of dead links (https://github.com/NixOS/nixpkgs/issues/45076)

###### Things done

- Build `fig2dev` as a seperate derivation
- Removed the custom builder script. New build system is autoconf
- The patches are obsolete

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by markuskowa** [comment]
@ryantm Is it possible to add this package (xfig and fig2dev) to your auto updater? The new version of the derivation is much cleaner.

**Comment by ryantm** [comment]
@markuskowa Neither of these packages are specifically [blacklisted](https://github.com/ryantm/nixpkgs-update/blob/master/src/Blacklist.hs). My auto updater has been trying to update xfig. Here is the [relevant error message](https://gist.github.com/ryantm/ac41cddb2857da6f55abab6ae5037e4c#file-20180817_ups-log-L194-L195) from the last run

Looks like our inclusion of fig2dev hasn't been [picked up by Repology](https://repology.org/metapackage/fig2dev/versions) yet when it is, my bot will try to update it.

**Comment by markuskowa** [comment]
@r-ryantm Thanks for the explanation. If no automatic update appears that means that it failed and needs to be done manually. I'll keep that in mind.

**Comment by ryantm** [comment]
@markuskowa You're welcome. If you want to look up a particular package, you can get a link to the latest logs here: https://github.com/ryantm/nixpkgs-update/issues/62

**Pull request merged**
