### PR TITLE
glfw: 3.2.1 -> 3.3

### PR DESCRIPTION
**Pull request by Twey**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @MarcWeber

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM

```
[18 built, 71 copied (717.9 MiB), 87.2 MiB DL]
https://github.com/NixOS/nixpkgs/pull/70626
11 package were build:
ccextractor embree2 glfw glslviewer goxel idrisPackages.glfw io kitty luxcorerender vcv-rack vlang
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build glfw

**Comment by Marqin** [comment]
@jonringer any ETA when this will land?

**Comment by jonringer** [comment]
I just want to give some time for other maintainers to comment. I'm not super familiar with glfw

**Comment by Moredread** [comment]
vcv-rack overrides the glfw version, so this shouldn't cause a problem there. We might be able to switch to upstream again after this merges though.

**Comment by k0ral** [comment]
I was about to contribute the same change when I noticed this pull-request.
Given that it's been open for a month now, with no reservations from reviewers, would-you-kindly consider merging it ? :)

**Comment by jonringer** [comment]
really  wish there was a !remindme 2 days functionality... too many PRs xD

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM

```
[26 built, 345 copied (4920.8 MiB), 787.9 MiB DL]
https://github.com/NixOS/nixpkgs/pull/70626
11 package were build:
ccextractor embree2 glfw glslviewer goxel idrisPackages.glfw io kitty luxcorerender vcv-rack vlang
```
sorry for the long delay! :(

**Pull request merged**
