### PR TITLE
update aws packages

### PR DESCRIPTION
**Pull request by Artturin**
Supersedes https://github.com/NixOS/nixpkgs/pull/200433

commands run

```sh
nix-update aws-c-auth --commit
nix-update aws-c-common --commit
nix-update aws-c-event-stream --commit
nix-update aws-c-http --commit
nix-update aws-c-mqtt --commit
nix-update aws-c-s3 --commit
nix-update aws-c-compression --commit
nix-update aws-c-aws-c-io --commit
nix-update aws-c-io --commit
nix-update aws-checksums --commit
nix-update aws-crt-cpp --commit
nix-update aws-c-sdkutils --commit
nix-update aws-c-cal --commit
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Currently aws-c-auth fails to build (i enabled the tests because aws-sdk-cpp was failing to build with `undefined reference`)

```
aws-c-auth> [100%] Linking C executable aws-c-auth-tests
aws-c-auth> /nix/store/8qm6sjqa09a03glzmafprpp69k74l4lm-binutils-2.40/bin/ld: CMakeFiles/aws-c-auth-tests.dir/credentials_provider_sts_web_identity_tests.c.o: in function `s_credentials_provider_sts_web_identity_new_destroy_from_cached_config':
aws-c-auth> credentials_provider_sts_web_identity_tests.c:(.text+0x5347): undefined reference to `aws_profile_collection_release'
aws-c-auth> /nix/store/8qm6sjqa09a03glzmafprpp69k74l4lm-binutils-2.40/bin/ld: CMakeFiles/aws-c-auth-tests.dir/credentials_tests.c.o: in function `s_profile_credentials_provider_cached_test':
aws-c-auth> credentials_tests.c:(.text+0x63f7): undefined reference to `aws_profile_collection_release'
aws-c-auth> /nix/store/8qm6sjqa09a03glzmafprpp69k74l4lm-binutils-2.40/bin/ld: credentials_tests.c:(.text+0x6401): undefined reference to `aws_profile_collection_release'
aws-c-auth> /nix/store/8qm6sjqa09a03glzmafprpp69k74l4lm-binutils-2.40/bin/ld: credentials_tests.c:(.text+0x65d8): undefined reference to `aws_profile_collection_release'
aws-c-auth> /nix/store/8qm6sjqa09a03glzmafprpp69k74l4lm-binutils-2.40/bin/ld: ../libaws-c-auth.so.1.0.0: undefined reference to `aws_profile_collection_acquire'
aws-c-auth> collect2: error: ld returned 1 exit status
```

**Comment by Artturin** [comment]
@ofborg build aws-sdk-cpp nix

**Comment by vcunat** [comment]
Anyone's tested darwin?  Hydra hasn't succeeded on x86_64-darwin even after several attempts (so we have no `nix` there).

**Comment by vcunat** [comment]
Oh, it did succeed after some more attempts, so... I don't know.  But generally, the aws-sdk-cpp tests are annoyingly flaky on Hydra.

**Comment by Artturin** [comment]
we can remove the flaky tests

**Comment by vcunat** [comment]
Now's an opportunity: https://hydra.nixos.org/build/217009919

**Pull request merged**
