### PR TITLE
webkitgtk: add darwin support

### PR DESCRIPTION
**Pull request by ryantrinkle**
This makes webkitgtk build on Mac OS

### CODE REVIEW

**Comment by vcunat** [comment]
- Travis suggests evaluation problems that seem valid.
- I think the state in current master after b07e7bfc7b is that even libX11 won't build on darwin.

**Comment by ryantrinkle** [comment]
@vcunat Yes, I think the evaluation issues are real; i'll clear those up.

I'm not sure what to do about libX11 not building on darwin; I noticed that, and so this patch is based on the latest nixpkgs-unstable instead, where libX11 does build.

**Comment by ryantrinkle** [comment]
It looks like the failures now are due the travis instance's disk filling up.

**Comment by ryantrinkle** [comment]
@luigy This may be of interest to you.

**Comment by vcunat** [comment]
I confirm the `tarball` job builds fine; our travis isn't very reliable yet.

**Comment by ryantrinkle** [comment]
@vcunat Anything I should test or do before merging this?  I'm still a bit new to being a committer on this repo.

**Comment by vcunat** [comment]
It would be nice if some darwin-capable contributor took this, as I've never used a darwin machine so I don't know much about such stuff and can't even test building. The other thing is that this probably can't even be built atop master where even libX11 still won't build on darwin...

**Comment by joachifm** [comment]
@ryantrinkle are you still work on this?

**Pull request closed without merging**
