### PR TITLE
nixos-render-docs: add manual html renderer, use it for the nixos manual

### PR DESCRIPTION
**Pull request by pennae**
###### Description of changes

at last! the html renderer for the nixos manual (if `! allowDocBook`). we reproduce the docbook-generated manuals almost exactly (as compared by the manual compare workflow scripts, which run each candidate through html-tidy first to allow for whitespace changes). we also do that in about 10% the time needed by the docbook manual toolchain (realizing a similar speedup to what manpages saw).

there's a good bit of docbook compat code in here, most of which can be either dropped when docbook goes away or formalized as the new (old) nixos manual style.

an epub converter should be not too far off from here, there's already infrastructure in place to allow arbitrary chunking of the input document and as far as we can tell our present epub manual is little more than a more aggressively chunked html manual packed in a zip file.

~~draft because this depends on  #214709 for a couple options rendering internals, but we could extract those and merge this first if someone wants to expedite this.~~

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
Yay! Thanks so much for putting in this huge effort.

It's a lot to review, so I started with trying to build on `x86_64-darwin`.

<details><summary>Build failed</summary>

```shell-session
cd ./doc
nix-build .
```

```log
this derivation will be built:
  /nix/store/jsjk7gqsk463sa4bxp7hjmr3p6sc9nbl-nixpkgs-manual.drv
building '/nix/store/jsjk7gqsk463sa4bxp7hjmr3p6sc9nbl-nixpkgs-manual.drv'...
unpacking sources
unpacking source archive /nix/store/2lqirqf8kcnizf6lrss9fc6n0dsslqdj-doc
source root is doc
patching sources
ln: failed to create symbolic link './doc-support/result/3n4brrn616lgmsbrw5mc3ifmv6iy6n2m-doc-support': Permission denied
/nix/store/32knm2y5g4x541xav6r6y7rhij8cg7lx-stdenv-darwin/setup: line 138: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/jsjk7gqsk463sa4bxp7hjmr3p6sc9nbl-nixpkgs-manual.drv' failed with exit code 1;
       last 6 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/2lqirqf8kcnizf6lrss9fc6n0dsslqdj-doc
       > source root is doc
       > patching sources
       > ln: failed to create symbolic link './doc-support/result/3n4brrn616lgmsbrw5mc3ifmv6iy6n2m-doc-support': Permission denied
       > /nix/store/32knm2y5g4x541xav6r6y7rhij8cg7lx-stdenv-darwin/setup: line 138: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/jsjk7gqsk463sa4bxp7hjmr3p6sc9nbl-nixpkgs-manual.drv'.
```

</details>

**Comment by ncfavier** [comment]
> `ln: failed to create symbolic link './doc-support/result/3n4brrn616lgmsbrw5mc3ifmv6iy6n2m-doc-support': Permission denied`

That definitely looks like a "dirty tree" issue. There's already a `result` symlink there so [this `ln`](https://github.com/NixOS/nixpkgs/blob/aff767f7eafd128672c2cfe5d33bec6d8d98e594/doc/default.nix#L20) interprets `doc-support/result` as a target *directory* rather than a target *filename*, and fails to create a link in that directory because it's in the store.

I *think* this should have been fixed by https://github.com/NixOS/nixpkgs/pull/215121?

**Comment by ncfavier** [comment]
Sorry, accidentally linked my PR to this one so that it closed it...

**Comment by fricklerhandwerk** [comment]
@pennae yeah sorry, I've built the Nixpkgs manual because I followed the wrong manual's instructions. The NixOS manual built works and looks correct on superficial inspection; checked off `x86_64-darwin` in the top post.

**Review by fricklerhandwerk — APPROVED** [review]
Went through the commit messages to follow design decisions, without inspecting the actual code too deeply, only ensuring the gist of each diff matches the intention laid out by the corresponding commit message.

I really like the approach and the result. Thank you so much, it's a great improvement on many fronts, and will enable lots of future work to improve technical coherence and readability of the manuals.

**Comment by fricklerhandwerk** [comment]
@pennae To the best of my knowledge you're the closest to technical maintainers of the NixOS manual now, and I trust your judgement.

@jtojnar opinions?

**Pull request merged**
