### PR TITLE
go_1_22: 1.22.0 -> 1.22.1

### PR DESCRIPTION
**Pull request by katexochen**
## Description of changes

Announcement: https://groups.google.com/d/msgid/golang-announce/Ir1JFYK8TcGRyLV1Ic3dpA%40geopod-ismtpd-4?utm_medium=email&utm_source=footer

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mfrw — APPROVED** [review]

**Comment by kirillrdy** [comment]
@katexochen can you add link to release notes in the commit, something like f4f9d00a45a7757a647f99d165e2800911472b82

**Review by kirillrdy — APPROVED** [review]
Result of `nixpkgs-review pr 293580` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>atlas</li>
    <li>conform</li>
    <li>doc2go</li>
    <li>evcc</li>
    <li>flyctl</li>
    <li>go_1_22</li>
    <li>gptscript</li>
    <li>gtree</li>
    <li>ioq3-scion</li>
    <li>mattermost</li>
    <li>orbiton</li>
    <li>pan-bindings</li>
    <li>tailscale</li>
    <li>telegraf</li>
    <li>trayscale</li>
  </ul>
</details>

**Comment by katexochen** [comment]
Can't be backported, there is no go_1_22 on 23.11.

**Comment by b4rsch** [comment]
when will go_1_22 be on 23.11 or where can i get it?

**Comment by vcunat** [comment]
Policy-wise there's no problem with adding new packages to the active stable branches (i.e. 23.11 now).

**Pull request merged**
