### PR TITLE
vimUtils.packDir: fix build in absence of pname

### LINKED ISSUE #193903: vim plugins built with `vimUtils.buildVimPlugin` require a `pname` attribute
### Describe the bug 

Vim plugins built with `vimUtils.buildVimPlugin` now require a `pname` attribute, because otherwise the evaluation of `vim-utils.nix` will fail with `attribute 'pname' missing`

### Expected behavior
The `name` attribute should be enough

### Notify maintainers
- @teto 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.11, NixOS, 22.11 (Raccoon), 22.11.20220929.c4d0026`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(mangoiv): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by teto**
###### Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/193903

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
sry @MangoIV to cut you off, we still want your PR https://github.com/NixOS/nixpkgs/pull/194065, but I just want to merge a quickfix to get rid of the github notifications.

**Comment by teto** [comment]
@lilyball so that fixed it for you ? (Just looking for one positive answer before merging :) )

**Comment by lilyball** [comment]
@teto It allows my `nix build` to get past evaluating the vim plugins derivation, but I'm running into other issues building my full configuration on current nixpkgs so I can't actually test the results. Still, the diff is pretty trivial.

**Comment by lilyball** [comment]
@teto I fixed my configuration, my existing vim plugin (that just defines `name`) now builds with this PR.

**Comment by SuperSandro2000** [comment]
Next time please ping me when I have another PR that fixes the same thing.

**Pull request merged**
