### PR TITLE
python3Packages.dask: 2.14.0 -> 2.22.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Fix dask for: #94841

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
with exception to `dask`, all other packages were broken

**Comment by teto** [comment]
I started a nixpkgs-review and this breaks datatable. Seems like a daunting task to fix everything though so I see no issue merging this already
```
builder for '/nix/store/208ks10wakrcw1n7cxi0z6s0bdphy29w-python3.7-datatable-0.10.1.drv' failed with exit code 4; last 10 log lines:
  ImportError while loading conftest '/build/datatable-0.10.1/tests/conftest.py'.
  tests/__init__.py:13: in <module>
      from datatable.internal import frame_columns_virtual, frame_integrity_check
  /nix/store/q83m72x8qs0wgc21cj05hv481qxr1mbv-python3.7-datatable-0.10.1/lib/python3.7/site-packages/datatable/__init__.py:24: in <module>
      from .frame import Frame
  /nix/store/q83m72x8qs0wgc21cj05hv481qxr1mbv-python3.7-datatable-0.10.1/lib/python3.7/site-packages/datatable/frame.py:23: in <module>
      from datatable.lib._datatable import Frame
  /nix/store/q83m72x8qs0wgc21cj05hv481qxr1mbv-python3.7-datatable-0.10.1/lib/python3.7/site-packages/datatable/lib/__init__.py:31: in <module>
      from . import _datatable as core
  E   ImportError: cannot import name '_datatable' from 'datatable.lib' (/nix/store/q83m72x8qs0wgc21cj05hv481qxr1mbv-python3.7-datatable-0.10.1/lib/python3.7/site-packages/datatable/lib/__init__.py)
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/9z7bc6bqlwmqzlrhxydzc972lvqz65yl-python3.7-xgboost-0.90.drv' failed to build
note: keeping build directory '/tmp/nix-build-python3.8-datatable-0.10.1.drv-0'
error: --- Error --- nix-daemon
builder for '/nix/store/96k410ck2likby2mcpmp5sh6df6q28lk-python3.8-datatable-0.10.1.drv' failed with exit code 4; last 10 log lines:
  ImportError while loading conftest '/build/datatable-0.10.1/tests/conftest.py'.
  tests/__init__.py:13: in <module>
      from datatable.internal import frame_columns_virtual, frame_integrity_check
  /nix/store/j98mxf1r2hakxvvy94sf0hh4kjq78kdv-python3.8-datatable-0.10.1/lib/python3.8/site-packages/datatable/__init__.py:24: in <module>
      from .frame import Frame
  /nix/store/j98mxf1r2hakxvvy94sf0hh4kjq78kdv-python3.8-datatable-0.10.1/lib/python3.8/site-packages/datatable/frame.py:23: in <module>
      from datatable.lib._datatable import Frame
  /nix/store/j98mxf1r2hakxvvy94sf0hh4kjq78kdv-python3.8-datatable-0.10.1/lib/python3.8/site-packages/datatable/lib/__init__.py:31: in <module>
      from . import _datatable as core
  E   ImportError: cannot import name '_datatable' from partially initialized module 'datatable.lib' (most likely due to a circular import) (/nix/store/j98mxf1r2hakxvvy94sf0hh4kjq78kdv-python3.8-datatable-0.10.1/lib/python3.8/site-packages/datatable/lib/__init__.py)
```

**Comment by jonringer** [comment]
> I started a nixpkgs-review and this breaks datatable. Seems like a daunting task to fix everything though so I see no issue merging this already

it's already broken on master, and has been broken for the past 2 months https://hydra.nixos.org/build/124757737

**Comment by jonringer** [comment]
@costrouc , as most of these are packages that you maintain, do you mind reviewing the changes.

**Comment by costrouc** [comment]
@jonringer I would love to help with this review and also help with in general the scientific/data python stack maintinance. For me the hardest part is knowing how I should and can help with keeping these packages up to date and cleaning them up. Should I just follow e.g. https://hydra.nixos.org/eval/1605243?filter=python38Packages&compare=1605209&full=#tabs-still-fail? What is the way you would recommend way of maintaining? At this point my github notifications are useless since I have way too many notifications (or I just need to be using a better tool for notifications). Also I realize that I contribute a lot of python packages to nixpkgs which does cause a maintenance burden and I would like to help with that.

**Comment by costrouc** [comment]
Result of `nixpkgs-review pr 94894` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
<br>- python37Packages.dask-xgboost
<br>- python37Packages.mask-rcnn
<br>- python38Packages.dask-xgboost
</details>
<details>
  <summary>53 packages built:</summary>
<br>- caffe
<br>- python37Packages.aplpy
<br>- python37Packages.batchgenerators
<br>- python37Packages.caffe
<br>- python37Packages.dask
<br>- python37Packages.dask-glm
<br>- python37Packages.dask-image
<br>- python37Packages.dask-jobqueue
<br>- python37Packages.dask-ml
<br>- python37Packages.dask-mpi
<br>- python37Packages.datashader
<br>- python37Packages.distributed
<br>- python37Packages.glymur
<br>- python37Packages.image-match
<br>- python37Packages.imagecorruptions
<br>- python37Packages.imgaug
<br>- python37Packages.intake
<br>- python37Packages.pims
<br>- python37Packages.pyfftw
<br>- python37Packages.scikitimage
<br>- python37Packages.sparse
<br>- python37Packages.spectral-cube
<br>- python37Packages.streamz
<br>- python37Packages.stumpy
<br>- python37Packages.stytra
<br>- python37Packages.sunpy
<br>- python37Packages.tensorly
<br>- python38Packages.aplpy
<br>- python38Packages.batchgenerators
<br>- python38Packages.caffe
<br>- python38Packages.dask
<br>- python38Packages.dask-glm
<br>- python38Packages.dask-image
<br>- python38Packages.dask-jobqueue
<br>- python38Packages.dask-ml
<br>- python38Packages.dask-mpi
<br>- python38Packages.datashader
<br>- python38Packages.distributed
<br>- python38Packages.glymur
<br>- python38Packages.image-match
<br>- python38Packages.imagecorruptions
<br>- python38Packages.imgaug
<br>- python38Packages.intake
<br>- python38Packages.pims
<br>- python38Packages.pyfftw
<br>- python38Packages.scikitimage
<br>- python38Packages.sparse
<br>- python38Packages.spectral-cube
<br>- python38Packages.streamz
<br>- python38Packages.stumpy
<br>- python38Packages.stytra
<br>- python38Packages.sunpy
<br>- python38Packages.tensorly
</details>

**Comment by jonringer** [comment]
@costrouc we don't have a good mechanism to notify build failures yet

Temporary solution, create a .nix file with the packages you care about, then attempt to build them periodically:
```
$ NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz nix build -f packages.nix
[18.8 MiB DL]
[15:25:30] jon@jon-desktop /home/jon/projects/nixpkgs (bzip2-1.0.8-staging)
$ cat packages.nix
with import <nixpkgs> { };

[
  python3Packages.dask

]
```

**Comment by jonringer** [comment]
this is a significant improvement, going to merge

**Pull request merged**
