### PR TITLE
[WIP] Force no undefined symbols in shared libraries by default

### PR DESCRIPTION
**Pull request by abbradar**
After a [discussion](https://github.com/NixOS/nixpkgs/commit/5471eed63ce770491a93f5c07543ba4ba818a90e) I've tried to add a pass to cc-wrapper to make `ld` fail if there are any undefined symbols in created shared libraries by default. This should have been able to catch problems like fixed in https://github.com/NixOS/nixpkgs/commit/5471eed63ce770491a93f5c07543ba4ba818a90e -- but surprisingly, it didn't. There were no errors on building wxGTK with the fix reverted and `ldd` still shows that several libraries are not linked properly in the output. Of course, `pgadmin` fails to build. I don't have ideas what the problem is at this point ;_;

cc @vcunat

### CODE REVIEW

**Comment by vcunat** [comment]
I don't know. This isn't consistent with my understanding of `man ld`.

**Comment by abbradar** [comment]
Notice that I had to allow undefined symbols for some packages -- so the flag _is_ working somehow.

**Comment by vcunat** [comment]
I don't understand why you updated the bootstrap tools.

**Comment by abbradar** [comment]
It's because it reported undefined symbols in our current bootstrap tools and failed to link. Just reran this:

```
/nix/store/vnyj8bffp8gdq8nsah8r9rhbyq96ynv8-bootstrap-tools/lib/libc.so.6: undefined reference to `_dl_argv@GLIBC_PRIVATE'
/nix/store/vnyj8bffp8gdq8nsah8r9rhbyq96ynv8-bootstrap-tools/lib/libc.so.6: undefined reference to `_dl_find_dso_for_object@GLIBC_PRIVATE'
/nix/store/vnyj8bffp8gdq8nsah8r9rhbyq96ynv8-bootstrap-tools/lib/libc.so.6: undefined reference to `__libc_enable_secure@GLIBC_PRIVATE'
/nix/store/dpaig38lbs1w70c3k7ix9881xscys331-bootstrap-glibc/lib/libdl.so: undefined reference to `_dl_rtld_di_serinfo@GLIBC_PRIVATE'
/nix/store/dpaig38lbs1w70c3k7ix9881xscys331-bootstrap-glibc/lib/libdl.so: undefined reference to `_rtld_global@GLIBC_PRIVATE'
/nix/store/vnyj8bffp8gdq8nsah8r9rhbyq96ynv8-bootstrap-tools/lib/libc.so.6: undefined reference to `__tls_get_addr@GLIBC_2.3'
/nix/store/dpaig38lbs1w70c3k7ix9881xscys331-bootstrap-glibc/lib/libdl.so: undefined reference to `_rtld_global_ro@GLIBC_PRIVATE'
```

**Comment by vcunat** [comment]
It really is more problematic than I assumed.

**Comment by abbradar** [comment]
Well, apart from bootstrap tools update and disabling this for some packages it hasn't caused any problems and I was able to build a large part of my current configuration. However I don't understand why doesn't this catch the wxGTK bug; this should be its primary use case so if it doesn't work we don't have any gain.

**Comment by abbradar** [comment]
Ahh, now I get it. The problem is not that the libraries are not linked; the problem is that we have them listed in `-L`, but _not_ in `-rpath`. So the linker sees no problem -- it finds libraries where pointed, but the resulting library fails to find what's needed.

I think this can only be detected by `ldd` (but I'm not sure). Maybe we also can change `-rpath`-adding algorithm to take them from `-L`s if a path in `-L` is in the Nix store...

**Comment by abbradar** [comment]
From our wrapper it seems that we already do it like this, but filter paths to include only those that contain some library listed in `-l` flags. However, this doesn't work for wxGTK because `X11` and `pango` are not listed! I'm not sure how they are linked to (a linker script?), but avoiding that filtering may help -- I don't see much reason in it anyway, we filter redundant paths with patchelf's `--shrink-rpath` later. What do others think?

**Comment by globin** [comment]
Could you check if #12895 has the same effect? I think bindnow (`ld -z now`) should essentially do the same, i.e. fail hard if there are missing libraries.

**Comment by vcunat** [comment]
No, bindnow forces symbols to resolve during load time, but we would want during *link* time already.

**Comment by copumpkin** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/15004

**Comment by 7c6f434c** [comment]
@abbradar do you still plan to do something here? If yes, I guess it would go to `staging` anyway…

**Comment by abbradar** [comment]
I do, I have returned to this branch during NixCon and plan to continue working on it after I finish some other longstanding branches. 
-- 
Nikolay.

**Comment by dtzWill** [comment]
Overall :+1: for this, friendly ping!

**Comment by teto** [comment]
related ? https://github.com/NixOS/nixpkgs/pull/64540

**Comment by Mindavi** [comment]
Is this still relevant? It seems annoying to have to add that variable to every package you want to build...

**Comment by abbradar** [comment]
This needs to be rebased and updated, and I'm not sure when or if I will return to this. Let's close it; if anyone is willing to pick this up I'll be glad to help too.

**Pull request closed without merging**
