### PR TITLE
WIP: update monero to v0.14.0.2

### PR DESCRIPTION
**Pull request by thedavidmeister**
###### Motivation for this change

this allows monerod to sync blocks again

https://github.com/NixOS/nixpkgs/issues/57210

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by thedavidmeister** [comment]
patch currently fails to apply

```
[thedavidmeister@nixos:~/nixpkgs]$ nix-shell -p nox --run "nox-review pr 57247"
=== Reviewing PR 57247 : WIP: update monero to v0.14.0.2
==> We're in a git repo, trying to fetch it
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
Building in /run/user/1000/nox-review-v10f3mzu: monero monero-gui
Invoking nix-build -A monero -A monero-gui /home/thedavidmeister/.nox/nixpkgs
these derivations will be built:
  /nix/store/ybz1z0fyn2mnxyfc8d1fjgzqa0ihs394-monero-gui-0.14.0.0.drv
building '/nix/store/ybz1z0fyn2mnxyfc8d1fjgzqa0ihs394-monero-gui-0.14.0.0.drv'...
unpacking sources
unpacking source archive /nix/store/9b85lmw4m991r1k70pxn6jv08kim9jv9-source
source root is source
patching sources
applying patch /nix/store/995jvgwy92jsh7ajqmqkh2fqgci0zbv4-move-log-file.patch
patching file main.cpp
Hunk #1 succeeded at 119 (offset 4 lines).
patching file Logger.cpp
Hunk #1 FAILED at 15.
1 out of 1 hunk FAILED -- saving rejects to file Logger.cpp.rej
builder for '/nix/store/ybz1z0fyn2mnxyfc8d1fjgzqa0ihs394-monero-gui-0.14.0.0.drv' failed with exit code 1
error: build of '/nix/store/ybz1z0fyn2mnxyfc8d1fjgzqa0ihs394-monero-gui-0.14.0.0.drv' failed
The invocation of "nix-build -A monero -A monero-gui /home/thedavidmeister/.nox/nixpkgs" failed
```

**Comment by rnhmjoj** [comment]
I have an update ready for monero but I paused is it since I couldn't get the GUI to run, though it builds fine. I'll give it another try soon.

**Comment by thedavidmeister** [comment]
@rnhmjoj aaah ok, i only tested the `monerod` syncing actually, i didn't test all the wallet commands as well, thanks

**Comment by rnhmjoj** [comment]
In the meantime you can grab the updated patch [here](https://github.com/NixOS/nixpkgs/blob/198c554b97fdf3d4122ca155d39ac82e4b170e0c/pkgs/applications/altcoins/monero-gui/move-log-file.patch) and fix the build.

**Comment by thedavidmeister** [comment]
@rnhmjoj yeah patch worked thanks

**Comment by ikervagyok** [comment]
ping https://github.com/NixOS/nixpkgs/pull/57109

**Comment by rnhmjoj** [comment]
The issue with monero-gui seems to be NixOS related: it's not present in stable.
I will be bisecting and try to fix it.

**Review by rnhmjoj — APPROVED** [review]

**Comment by thedavidmeister** [comment]
note to self:

```
export NIXPKGS=`pwd`
nix-build $NIXPKGS -A monero-gui --run-env
monerod
``

**Comment by thedavidmeister** [comment]
works for me with the `monero-wallet-cli` + `monerod`

i needed to upgrade my ledger to firmware `1.5.5` and monero app to `1.2.2` though

**Comment by rnhmjoj** [comment]
After a looong git bisect it appears 8e811ec295424649bd7fca81ec136e2d28bf8230 introduced the issue.
However, simply downgrading Qt with `libsForQt511` doesn't work: the program produces a different error but still doesn't start.

**Comment by thedavidmeister** [comment]
@rnhmjoj ok so potentially an issue with 5.12 with monero gui itself?

**Comment by rnhmjoj** [comment]
Yes, monero-gui requires qt>5.9 but the readme doesn't give an upper bound, so it's possibile 5.12 made some breaking change or regression. However downgrading should work: this makes me think there is something else wrong on the nixpkgs side.

**Comment by thedavidmeister** [comment]
dunno if this is related but when i upgraded the `monero` version in nixpkgs it did not upgrade monerod until i upgraded the `monero-gui` version too

is it possible that qt version needs to be set/downgraded in two places?

**Comment by rnhmjoj** [comment]
I'm not sure i follow, sorry. `monero` doesn't depend on qt, is a cli, only `monero-gui` does.

**Comment by thedavidmeister** [comment]
ok, maybe red herring

**Comment by rnhmjoj** [comment]
Ok, so i just found out this affects other Qt applications as well: I have found a fix.
I'll make a PR soon.

**Review by rnhmjoj — CHANGES_REQUESTED** [review]
@thedavidmeister can you rename the commits to "monero: x -> y"?

**Comment by thedavidmeister** [comment]
@rnhmjoj all 3 of them to the same name?

**Comment by rnhmjoj** [comment]
I'd keep the monerod commit separate as "monero: 0.13.0.4 -> 0.13.0.2" and squash the two monero-gui commits into one "monero-gui: 0.13.0.4 -> 0.14.0.0".

**Comment by rnhmjoj** [comment]
ping

**Comment by thedavidmeister** [comment]
yup, over here #58250

**Pull request closed without merging**
