### PR TITLE
guile-chickadee: init at 0.10.0

### PR DESCRIPTION
**Pull request by chitochi**
## Description of changes

This pull request adds the `guile-chickadee` package.

Chickadee is a game development toolkit for Guile Scheme built on top of SDL2 and OpenGL. Chickadee aims to provide all the features that parenthetically inclined game developers need to make 2D (and eventually 3D) games in Scheme, such as:
- extensible, fixed-timestep game loop
- OpenGL-based rendering engine
- keyboard, mouse, controller input
- REPL-driven development model

If you want to read more, here is the homepage of the project: https://dthompson.us/projects/chickadee.html.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Janik-Haag — CHANGES_REQUESTED** [review]
Hi, Thank you for your contribution! When trying to run the program it erros with: 
image

I also reviewd your code which mostly looks good, there is some formatting mistakes but I don't want to annoy you with too many nitpicks so I just wrote a patch:
```patch
From 5bab52487a4c0da1c3ba7493d52a2e6215cf0037 Mon Sep 17 00:00:00 2001
From: "Janik H." <janik@aq0.de>
Date: Wed, 20 Dec 2023 00:55:47 +0100
Subject: [PATCH] guile-chickadee: patch formatting

---
 pkgs/by-name/gu/guile-chickadee/package.nix | 39 ++++++++++-----------
 1 file changed, 19 insertions(+), 20 deletions(-)

diff --git a/pkgs/by-name/gu/guile-chickadee/package.nix b/pkgs/by-name/gu/guile-chickadee/package.nix
index 32861ac6b234..acf58f5b8a6a 100644
--- a/pkgs/by-name/gu/guile-chickadee/package.nix
+++ b/pkgs/by-name/gu/guile-chickadee/package.nix
@@ -1,20 +1,19 @@
-{
-  lib,
-  stdenv,
-  fetchurl,
-  makeWrapper,
-  guile,
-  pkg-config,
-  texinfo,
-  freetype,
-  libjpeg_turbo,
-  libpng,
-  libvorbis,
-  mpg123,
-  openal,
-  readline,
-  guile-opengl,
-  guile-sdl2,
+{ lib
+, stdenv
+, fetchurl
+, makeWrapper
+, guile
+, pkg-config
+, texinfo
+, freetype
+, libjpeg_turbo
+, libpng
+, libvorbis
+, mpg123
+, openal
+, readline
+, guile-opengl
+, guile-sdl2
 }:
 stdenv.mkDerivation (finalAttrs: {
   pname = "guile-chickadee";
@@ -22,7 +21,7 @@ stdenv.mkDerivation (finalAttrs: {
 
   src = fetchurl {
     url = "https://files.dthompson.us/chickadee/chickadee-${finalAttrs.version}.tar.gz";
-    sha256 = "0x8g0bsvir2z3876ynslfgnmfr5p92ic4666v73526lswnv56bqk";
+    hash = "sha256-Ey9TtuWaGlHG2cYYwqJIt2RX7XNUW28OGl/kuPUCD3U=";
   };
 
   strictDeps = true;
@@ -50,7 +49,7 @@ stdenv.mkDerivation (finalAttrs: {
     guile-sdl2
   ];
 
-  makeFlags = ["GUILE_AUTO_COMPILE=0"];
+  makeFlags = [ "GUILE_AUTO_COMPILE=0" ];
 
   postInstall = ''
     wrapProgram $out/bin/chickadee \
@@ -62,7 +61,7 @@ stdenv.mkDerivation (finalAttrs: {
     description = "Game development toolkit for Guile Scheme with SDL2 and OpenGL";
     homepage = "https://dthompson.us/projects/chickadee.html";
     license = licenses.asl20;
-    maintainers = with maintainers; [chito];
+    maintainers = with maintainers; [ chito ];
     mainProgram = "chickadee";
     platforms = guile.meta.platforms;
   };
-- 
2.42.0

```

Please apply it and squash it into the guile-chickadee: init at 0.10.0 commit. (we want to squash the commit since nixpkgs is trying to have a atomic git history)

**Comment by Janik-Haag** [comment]
I'm still experiencing the before mentioned libmpg123 error :(

**Comment by Janik-Haag** [comment]
I'm still getting the same error as before, I'm guessing this might be a wayland thing?

**Comment by Janik-Haag** [comment]
I'm also using wayland, sway with nixos-unstable on a thinkpad-t480 to be precise. But no idea why it's crashing for me. I also experience a similar crash in another pr were the author is also running sway but doesn't have the error.

**Comment by Janik-Haag** [comment]
Please tell me if I can help you in some way like for example providing a strace of trying to run the binary.

**Review by Janik-Haag — APPROVED** [review]
LGTM!

Sorry for holding this up so long. I didn't quite figure out the problem, but I know that something in my nixos config modifies my path in a way that breaks guile-chickadee. Using a pure shell works so the package is fine.

**Comment by Janik-Haag** [comment]
One last thing, you should mark darwin as broken or mark the package as linux only since the build in the ci is failing, it's good to go afterwards.

**Review by h7x4 — APPROVED** [review]

**Pull request merged**
