### PR TITLE
Remove packages which are no longer required after #116317 in packages that use grpc

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 116531` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
6 packages marked as broken and skipped:
</summary>
<ul>
<li>linuxPackages-libre.sysdig</li>
<li>linuxPackages_4_4.sysdig</li>
<li>linuxPackages_4_9.sysdig</li>
<li>linuxPackages_hardkernel_4_14.sysdig</li>
<li>linuxPackages_hardkernel_latest.sysdig</li>
<li>linuxPackages_latest-libre.sysdig</li>
</ul>
</details>
<details>
<summary>
19 packages built:
</summary>
<ul>
<li>google-cloud-cpp</li>
<li>lightstep-tracer-cpp</li>
<li>linuxPackages.sysdig (linuxPackages_5_4.sysdig)</li>
<li>linuxPackages_4_14.sysdig</li>
<li>linuxPackages_4_19.sysdig</li>
<li>linuxPackages_5_10.sysdig</li>
<li>linuxPackages_5_11.sysdig (linuxPackages_latest.sysdig)</li>
<li>linuxPackages_hardened.sysdig</li>
<li>linuxPackages_latest_hardened.sysdig</li>
<li>linuxPackages_latest_xen_dom0.sysdig</li>
<li>linuxPackages_latest_xen_dom0_hardened.sysdig</li>
<li>linuxPackages_lqx.sysdig</li>
<li>linuxPackages_testing_bcachefs.sysdig</li>
<li>linuxPackages_xen_dom0.sysdig</li>
<li>linuxPackages_xen_dom0_hardened.sysdig</li>
<li>linuxPackages_zen.sysdig</li>
<li>rippled</li>
<li>rippled-validator-keys-tool</li>
<li>sysdig</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
google-cloud-cpp:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/google-cloud-cpp/default.nix:74:5:

```
   |
74 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
</details>

**Review by ghost — APPROVED** [review]
Rippled looks fine to me.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 116531` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
6 packages marked as broken and skipped:
</summary>
<ul>
<li>linuxPackages-libre.sysdig</li>
<li>linuxPackages_4_4.sysdig</li>
<li>linuxPackages_4_9.sysdig</li>
<li>linuxPackages_hardkernel_4_14.sysdig</li>
<li>linuxPackages_hardkernel_latest.sysdig</li>
<li>linuxPackages_latest-libre.sysdig</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>linuxPackages_lqx.sysdig: log was empty</li>
<li>linuxPackages_zen.sysdig: log was empty</li>
  </ul>
</details>
<details>
<summary>
17 packages built:
</summary>
<ul>
<li>google-cloud-cpp</li>
<li>lightstep-tracer-cpp</li>
<li>linuxPackages.sysdig (linuxPackages_5_4.sysdig)</li>
<li>linuxPackages_4_14.sysdig</li>
<li>linuxPackages_4_19.sysdig</li>
<li>linuxPackages_5_10.sysdig</li>
<li>linuxPackages_5_11.sysdig (linuxPackages_latest.sysdig)</li>
<li>linuxPackages_hardened.sysdig</li>
<li>linuxPackages_latest_hardened.sysdig</li>
<li>linuxPackages_latest_xen_dom0.sysdig</li>
<li>linuxPackages_latest_xen_dom0_hardened.sysdig</li>
<li>linuxPackages_testing_bcachefs.sysdig</li>
<li>linuxPackages_xen_dom0.sysdig</li>
<li>linuxPackages_xen_dom0_hardened.sysdig</li>
<li>rippled</li>
<li>rippled-validator-keys-tool</li>
<li>sysdig</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
google-cloud-cpp:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/google-cloud-cpp/default.nix:74:5:

```
   |
74 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
</details>

**Comment by 7c6f434c** [comment]
sysdig module is a complicated thing, as most versions build, the change is fine

**Pull request merged**
