### PR TITLE
Revert "opentelemetry-collector-contrib: 0.110.0 -> 0.112.0"

### PR DESCRIPTION
**Pull request by NickCao**
Reverts NixOS/nixpkgs#351600

The output was empty.

### CODE REVIEW

**Review by zimbatm — APPROVED** [review]
ok, 0.110.0 still works.

Maybe add a postInstallCheck to see if the binary exists?

**Comment by NickCao** [comment]
> Maybe add a postInstallCheck to see if the binary exists?

A version test would be more appropriate.

**Comment by zimbatm** [comment]
something changed in 0.111.0

**Comment by zimbatm** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/357386

**Pull request merged**
