### PR TITLE
kubernetes-helm: 2.15.1 -> 3.0.0

### PR DESCRIPTION
**Pull request by saschagrunert**
##### Motivation for this change

Update helm to the latest release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @rlupton20 @edude03

### CODE REVIEW

**Comment by rlupton20** [comment]
Looks good!

**Comment by saschagrunert** [comment]
@GrahamcOfBorg build kubernetes-helm

**Review by rlupton20 — APPROVED** [review]
Looks good to me.

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
commits LGTM
executables show usage

```
[5 built, 2 copied (71.6 MiB), 66.2 MiB DL]
https://github.com/NixOS/nixpkgs/pull/73351
2 package were build:
helmfile kubernetes-helm
```

expression looks a lot cleaner! :)

**Comment by jonringer** [comment]
@GrahamcOfBorg build helmfile kubernetes-helm

**Pull request merged**
