### PR TITLE
elisp-ffi: init at git 2014-11-03

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by oxij** [comment]
Can you please rewrite this for emacsPackagesNg using melpaBuild in
top-level/emacs-packages.nix? I'd run `make` in `preBuild` and the rest
should be handled by melpaBuild.

**Comment by DamienCassou** [comment]
@oxij I'm trying but gets a strange error:

```
$ nix-build -A emacs24PackagesNg.elisp-ffi
these derivations will be built:
  /nix/store/1idhfzwwm2pgi88mq7i8v3c5saham865-emacs-elisp-ffi-git-2014-11-03.drv
building path(s) ‘/nix/store/pd0apin88sx4rjwsc5sq58lqlmrjjzxq-emacs-elisp-ffi-git-2014-11-03’
unpacking sources
unpacking source archive /nix/store/h680dwbrimdcpm89g6hn85k08bb4s26p-elisp-ffi-eb3d826d68ace9f9a41515ab3820376c0d141634-src
source root is elisp-ffi-eb3d826d68ace9f9a41515ab3820376c0d141634-src
patching sources
configuring
no configure script, doing nothing
building
g++ -std=c++11 -Wall -O2    ffi-glue.cc  -ldl -lffi -lstdc++ -o ffi-glue

;;; elisp-ffi-git

/tmp/nix-build-emacs-elisp-ffi-git-2014-11-03.drv-0/elisp-ffi-eb3d826d68ace9f9a41515ab3820376c0d141634-src/ffi-tests.el -> /tmp/nix-build-emacs-elisp-ffi-git-2014-11-03.drv-0/elisp-ffi-git89PeO/elisp-ffi-git-2014-11-03/ffi-tests.el
/tmp/nix-build-emacs-elisp-ffi-git-2014-11-03.drv-0/elisp-ffi-eb3d826d68ace9f9a41515ab3820376c0d141634-src/ffi.el -> /tmp/nix-build-emacs-elisp-ffi-git-2014-11-03.drv-0/elisp-ffi-git89PeO/elisp-ffi-git-2014-11-03/ffi.el
Built in 0.018s, finished at Thu Nov 12 19:25:03 2015
installing
Parsing tar file...
Parsing tar file...done
Parsing tar file...
Parsing tar file...done
Package does not untar cleanly into directory elisp-ffi-git-2014snapshot11snapshot3/
builder for ‘/nix/store/1idhfzwwm2pgi88mq7i8v3c5saham865-emacs-elisp-ffi-git-2014-11-03.drv’ failed with exit code 255
error: build of ‘/nix/store/1idhfzwwm2pgi88mq7i8v3c5saham865-emacs-elisp-ffi-git-2014-11-03.drv’ failed
```

Here is my non working patch:

```patch
diff --git a/pkgs/top-level/emacs-packages.nix b/pkgs/top-level/emacs-packages.nix
index d36100a..ca6f67e 100644
--- a/pkgs/top-level/emacs-packages.nix
+++ b/pkgs/top-level/emacs-packages.nix
@@ -33,7 +33,7 @@
 
 { overrides
 
-, lib, stdenv, fetchurl, fetchgit, fetchFromGitHub, fetchhg
+, pkgs, lib, stdenv, fetchurl, fetchgit, fetchFromGitHub, fetchhg
 
 , emacs
 , trivialBuild
@@ -99,6 +99,29 @@ let self = _self // overrides;
     };
   };
 
+  elisp-ffi = melpaBuild rec {
+    pname = "elisp-ffi-git";
+    version = "2014-11-03";
+    src = fetchFromGitHub {
+        owner = "skeeto";
+        repo = "elisp-ffi";
+        rev = "eb3d826d68ace9f9a41515ab3820376c0d141634";
+        sha256 = "0w7r56qf2h8wgfs81fc9k8w8949kf2djyhsh8p12dk365nm11n2s";
+    };
+    buildInputs = [ pkgs.libffi ];
+    preBuild = "make";
+    meta = {
+      description = "Emacs Lisp Foreign Function Interface";
+      longDescription = ''
+      This library provides an FFI for Emacs Lisp so that Emacs
+      programs can invoke functions in native libraries. It works by
+      driving a subprocess to do the heavy lifting, passing result
+      values on to Emacs.
+      '';
+      license = publicDomain;
+    };
+  };
+
   agda2-mode = with external; trivialBuild {
     pname = "agda-mode";
     version = Agda.version;
~/nixpkgs $ 
```

**Comment by DamienCassou** [comment]
And there is something different with this package: it contains a binary `ffi-glue`

**Comment by oxij** [comment]
The problem here is with `version` field, melpaBuild doesn't like it.
Also `-git` in the name is not nice.

This seems to work (you might want to change "ffi.el" to "*.el" in
`files`, I'm not sure whenever `ffi-test.el` is actually needed):

diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 16ef3b0..bf15aa0 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -11495,7 +11495,7 @@ let
     external = {
       inherit (haskellPackages) ghc-mod structured-haskell-mode Agda;
       inherit (pythonPackages) elpy;
-      inherit rtags;
+      inherit rtags libffi;
     };
   };
 
diff --git a/pkgs/top-level/emacs-packages.nix b/pkgs/top-level/emacs-packages.nix
index 7fcc5c6..c03898d 100644
--- a/pkgs/top-level/emacs-packages.nix
+++ b/pkgs/top-level/emacs-packages.nix
@@ -458,6 +458,30 @@ let self = _self // overrides;
     };
   };
 
+  elisp-ffi = melpaBuild rec {
+    pname = "elisp-ffi";
+    version = "20141103";
+    src = fetchFromGitHub {
+        owner = "skeeto";
+        repo = "elisp-ffi";
+        rev = "eb3d826d68ace9f9a41515ab3820376c0d141634";
+        sha256 = "0w7r56qf2h8wgfs81fc9k8w8949kf2djyhsh8p12dk365nm11n2s";
+    };
+    buildInputs = [ external.libffi ];
+    preBuild = "make";
+    files = [ "ffi-glue" "ffi.el" ];
+    meta = {
+      description = "Emacs Lisp Foreign Function Interface";
+      longDescription = ''
+      This library provides an FFI for Emacs Lisp so that Emacs
+      programs can invoke functions in native libraries. It works by
+      driving a subprocess to do the heavy lifting, passing result
+      values on to Emacs.
+      '';
+      license = publicDomain;
+    };
+  };
+
   elpy = melpaBuild rec {
     pname   = "elpy";
     version = external.elpy.version;

**Comment by DamienCassou** [comment]
@oxij the `-git` suffix to the name is actually required by nixos contributors guide. And the version must be `YYYY-MM-DD`:

http://nixos.org/nixpkgs/manual/#sec-package-naming:
> If package is fetched from git's commit then the version part of the name must be the date of that (fetched) commit. The date must be in "YYYY-MM-DD" format. Also add "git" to the name - e.g., "pkgname-git-2014-09-23".

**Comment by DamienCassou** [comment]
I pushed a new version where I removed the dashes from the version number but I kept the `-git` name suffix. Tell me if you want me to change that as well.

**Comment by oxij** [comment]
Okay then, looks like it changed since I last read it.

I'm absolutely fine with the current version if that derivation actually
works (I have not tested it, but I hope it will find that `ffi-glue`
binary in elpa directory, I'm too lazy to check).

Now, if that's the case, why would you need the other
`pkgs/applications/editors/emacs-modes/elisp-ffi/default.nix` and its
top-level attribute?

**Comment by DamienCassou** [comment]
I check and everything works (i.e., the binary is found).

The new commit removes the top-level definition. Thanks for noticing it.

**Comment by oxij** [comment]
:+1: and Thank you! then

**Pull request merged**
