### PR TITLE
texlive.bin.dvisvgm: texlive 2.8.1 -> upstream 2.11

### LINKED ISSUE #104847: dvisvgm 2.10.1
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: texlive-dvisvgm.bin
current version: 2.9.1
desired version: 2.10.1

###### Notify maintainers

maintainers: @veprbl 

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

Closes: #104847

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build tests.texlive.dvisvgm

**Comment by veprbl** [comment]
@spacekitteh Can you try this?

**Comment by spacekitteh** [comment]
@veprbl how?

**Comment by veprbl** [comment]
@spacekitteh I thought you could use it the way you describe in https://github.com/NixOS/nixpkgs/issues/104847#issuecomment-733445591 and see if it produces broken svg. I don't know how you use nixpkgs, but perhaps you could use
```
nix-shell -p texlive.bin.dvisvgm -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/9ef277209a5c7151da308244bbabc50b80864453.tar.gz
```
to get dvisvgm from this PR in a new shell environment.

**Comment by spacekitteh** [comment]
Hmm, I'm not sure if this error is due to it being in `nix-shell` or not, but:

```
warning: kpathsea: configuration file texmf.cnf not found in these directories: /nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/bin:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/bin/share/texmf-local/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/bin/share/texmf-dist/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/bin/share/texmf/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/bin/texmf-local/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/bin/texmf-dist/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/bin/texmf/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/share/texmf-local/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/share/texmf-dist/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/share/texmf/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/texmf-local/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/texmf-dist/web2c:/nix/store/f8skxd8hjzyh19l8r4pmvljb108m84nl-texlive-dvisvgm.bin-2.11/texmf/web2c:/nix/texmf-local/web2c:/nix/store:/nix/store/share/texmf-local/web2c:/nix/store/share/texmf-dist/web2c:/nix/store/share/texmf/web2c:/nix/store/texmf-local/web2c:/nix/store/texmf-dist/web2c:/nix/store/texmf/web2c.
WARNING: map file ps2pk.map not found
WARNING: map file pdftex.map not found
WARNING: map file dvipdfm.map not found
WARNING: map file psfonts.map not found
WARNING: none of the default map files could be found
pre-processing DVI file (format version 2)
WARNING: PostScript header file tex.pro not found
WARNING: PostScript header file texps.pro not found
WARNING: PostScript header file special.pro not found
WARNING: PostScript header file color.pro not found
PostScript error: undefined in TeXDict
```

**Comment by spacekitteh** [comment]
I'll try with `texlive.combined.scheme-full`.

**Comment by spacekitteh** [comment]
Yup! It works! <3

**Comment by veprbl** [comment]
And by works it means also addresses the #104847?

**Comment by spacekitteh** [comment]
Yup.

**Comment by spacekitteh** [comment]
\o/

**Pull request merged**
