### PR TITLE
nextcloud27: init

### LINKED ISSUE #237560: Update request: nextcloud 26.0.2 → 27.0.0
- Package name: nextcloud
- Latest released version: [27.0.0](https://github.com/nextcloud/server/releases/tag/v27.0.0)

- Current version on the unstable channel: 26.0.2
- Current version on the stable/release channel: 26.0.2

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Ma27 @bachp @schneefux 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by Ma27**
###### Description of changes

Closes #237560.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by RaitoBezarius — APPROVED** [review]
I'm testing on the top of release-23.05 on my production, on the rest, LGTM. :)

**Comment by RaitoBezarius** [comment]
This is running **FINE** **except** for the memcache locking option where NC27 is saying to me "oh you are locking with database, bad!" for some reason. Did the configuration change?

I run with the following relevant fragment:
```
    caching = {
      redis = true;
      apcu = true;
    };
    extraOptions = {
      redis = {
        host = "/run/redis-nextcloud/redis.sock";
        port = 0;
      };
      memcache = {
        local = "\\OC\\Memcache\\Redis";
        distributed = "\\OC\\Memcache\\Redis";
        locking = "\\OC\\Memcache\\Redis";
      };
    };
```

**Comment by Ma27** [comment]
@RaitoBezarius can you point me to the actual error, please?

Also, why do you have redis & apcu enabled?

**Comment by onny** [comment]
> This is running **FINE** **except** for the memcache locking option where NC27 is saying to me "oh you are locking with database, bad!" for some reason. Did the configuration change?
> 
> I run with the following relevant fragment:
> 
> ```
>     caching = {
>       redis = true;
>       apcu = true;
>     };
>     extraOptions = {
>       redis = {
>         host = "/run/redis-nextcloud/redis.sock";
>         port = 0;
>       };
>       memcache = {
>         local = "\\OC\\Memcache\\Redis";
>         distributed = "\\OC\\Memcache\\Redis";
>         locking = "\\OC\\Memcache\\Redis";
>       };
>     };
> ```

you can use enableRedis too :)

**Comment by Ma27** [comment]
@RaitoBezarius please take a look :)

**Review by dotlambda — CHANGES_REQUESTED** [review]
Please rebase: https://apps.nextcloud.com/apps/qownnotesapi is missing from `27.json`.

**Comment by RaitoBezarius** [comment]
Good to go for me, modulo rebase.

**Comment by Ma27** [comment]
@dotlambda Done!

(Sorry, upon my rebase I spotted the actual conflicts, but not the additions)

**Comment by Ma27** [comment]
OK while I'm at it, I decided to simply add the apps I also use on my own to the list (`maps` is not officially ready for nc27, but `master` already updated - and I tested their latest release on v27 w/ php 8.2 already, so it should change soon).

**Pull request merged**
