### PR TITLE
llvmPackages_19: 19.1.4 -> 19.1.5

### PR DESCRIPTION
**Pull request by paparodeo**
https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.5

https://discourse.llvm.org/t/llvm-19-1-5-released/83455

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by paparodeo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 361678`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>magnetophonDSP.ConstantDetuneChorus</li>
  </ul>
</details>
<details>
  <summary>:x: 6 packages failed to build:</summary>
  <ul>
    <li>emscriptenPackages.libxml2</li>
    <li>emscriptenPackages.libxml2.bin</li>
    <li>emscriptenPackages.libxml2.dev</li>
    <li>emscriptenPackages.libxml2.devdoc</li>
    <li>emscriptenPackages.xmlmirror</li>
    <li>emscriptenPackages.xmlmirror.doc</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 81 packages built:</summary>
  <ul>
    <li>bolt_19</li>
    <li>bolt_19.dev</li>
    <li>bpf-linker</li>
    <li>cargo-llvm-cov</li>
    <li>clang_19</li>
    <li>emscripten</li>
    <li>emscriptenPackages.json_c</li>
    <li>emscriptenPackages.json_c.dev</li>
    <li>emscriptenPackages.zlib</li>
    <li>faust</li>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jack</li>
    <li>faust2jackrust</li>
    <li>faust2jaqt</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>faust2sc</li>
    <li>faustPhysicalModeling</li>
    <li>faustlive</li>
    <li>guitarix</li>
    <li>kapitonov-plugins-pack</li>
    <li>lld_19</li>
    <li>lld_19.dev</li>
    <li>lld_19.lib</li>
    <li>lldb_19</li>
    <li>lldb_19.dev</li>
    <li>lldb_19.lib</li>
    <li>llvmPackages_19.bintools</li>
    <li>llvmPackages_19.bintools-unwrapped</li>
    <li>llvmPackages_19.bintoolsNoLibc</li>
    <li>llvmPackages_19.clang-manpages</li>
    <li>llvmPackages_19.clang-tools</li>
    <li>llvmPackages_19.clang-unwrapped</li>
    <li>llvmPackages_19.clang-unwrapped.dev</li>
    <li>llvmPackages_19.clang-unwrapped.lib</li>
    <li>llvmPackages_19.clang-unwrapped.python</li>
    <li>llvmPackages_19.clangNoCompilerRt</li>
    <li>llvmPackages_19.clangNoCompilerRtWithLibc</li>
    <li>llvmPackages_19.clangNoLibc</li>
    <li>llvmPackages_19.clangNoLibcxx</li>
    <li>llvmPackages_19.clangUseLLVM</li>
    <li>llvmPackages_19.clangWithLibcAndBasicRtAndLibcxx</li>
    <li>llvmPackages_19.compiler-rt</li>
    <li>llvmPackages_19.compiler-rt-no-libc</li>
    <li>llvmPackages_19.compiler-rt-no-libc.dev</li>
    <li>llvmPackages_19.compiler-rt.dev</li>
    <li>llvmPackages_19.libclc</li>
    <li>llvmPackages_19.libclc.dev</li>
    <li>llvmPackages_19.libcxx</li>
    <li>llvmPackages_19.libcxx.dev</li>
    <li>llvmPackages_19.libcxxClang</li>
    <li>llvmPackages_19.libcxxStdenv</li>
    <li>llvmPackages_19.libllvm</li>
    <li>llvmPackages_19.libllvm.dev</li>
    <li>llvmPackages_19.libllvm.lib</li>
    <li>llvmPackages_19.libllvm.python</li>
    <li>llvmPackages_19.libunwind</li>
    <li>llvmPackages_19.libunwind.dev</li>
    <li>llvmPackages_19.lldb-manpages</li>
    <li>llvmPackages_19.lldbPlugins.llef</li>
    <li>llvmPackages_19.llvm-manpages</li>
    <li>llvmPackages_19.mlir</li>
    <li>llvmPackages_19.mlir.dev</li>
    <li>llvmPackages_19.openmp</li>
    <li>llvmPackages_19.openmp.dev</li>
    <li>llvmPackages_19.stdenv</li>
    <li>magnetophonDSP.CharacterCompressor</li>
    <li>magnetophonDSP.CompBus</li>
    <li>magnetophonDSP.LazyLimiter</li>
    <li>magnetophonDSP.MBdistortion</li>
    <li>magnetophonDSP.RhythmDelay</li>
    <li>magnetophonDSP.VoiceOfFaust</li>
    <li>magnetophonDSP.faustCompressors</li>
    <li>magnetophonDSP.pluginUtils</li>
    <li>magnetophonDSP.shelfMultiBand</li>
    <li>mooSpace</li>
    <li>open-music-kontrollers.mephisto</li>
    <li>tambura</li>
  </ul>
</details>

**Review by alyssais — APPROVED** [review]
Diff LGTM.

**Comment by alyssais** [comment]
@qknight @matthewbauer @RaitoBezarius @willcohen looks like Emscripten will need to be updated for this.

**Comment by willcohen** [comment]
Hi @alyssais -- you mean because of libxml2 and xmlmirror or something else? Nothing in the changelog is jumping out at me suspiciously. The emscriptenPackages are pretty finicky (at least until something like https://github.com/NixOS/nixpkgs/pull/217428 reorganizes them, I suppose) and are often broken. emscripten and binaryen both proper made it to their latest releases a few days ago: https://github.com/NixOS/nixpkgs/pull/343743

**Comment by alyssais** [comment]
I just saw from @paparodeo's comment that they fail to build here, and I checked that they are currently building on Hydra.

**Comment by willcohen** [comment]
Gotcha. Okay, I think we're good then -- they were broken on the emscripten bump's nixpkgs-review too (https://github.com/NixOS/nixpkgs/pull/343743#issuecomment-2508806807), but usually work out okay in hydra afterwards. I haven't dug enough to find out why.

**Comment by paparodeo** [comment]
> I just saw from @paparodeo's comment that they fail to build here, and I checked that they are currently building on Hydra.

`emscriptenPackages.libxml2` and `emscriptenPackages.xmlmirror` don't build for me on master and have been broken the past few iterations of updating llvm-19 -- I can't find the hydra attribute

https://github.com/NixOS/nixpkgs/pull/352781#issuecomment-2457538871
https://github.com/NixOS/nixpkgs/pull/357453#issuecomment-2487585266

> If staging-next starts before this is merged, this will cause a staging-next mass rebuild when merged. Might be safer to send it through staging to avoid that.

was hoping this would be merged before the staging-next cycle but will do

**Review by willcohen — APPROVED** [review]

**Comment by alyssais** [comment]
> was hoping this would be merged before the staging-next cycle but will do

It's about to start I think.

**Review by philiptaron — APPROVED** [review]

**Comment by RossComputerGuy** [comment]
That backport doesn't quite look right, shouldn't that be a staging backport?

**Comment by paparodeo** [comment]
> That backport doesn't quite look right, shouldn't that be a staging backport?

the backport is fine. on master this is also fine but there are changes in staging-next that makes llvm-19 the default for both linux and darwin which results in a mass rebuild. see: https://github.com/NixOS/nixpkgs/pull/361678#issuecomment-2517400137

**Pull request merged**
