### PR TITLE
Python fixes

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
#36453 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
@FRidh Should this go into staging or can I merge into master?

**Comment by FRidh** [comment]
@dotlambda these are all minor packages, also judging from the @GrahamcOfBorg output, so therefore master.

**Review by matthiasbeyer — APPROVED** [review]
I approve for the "klaus" package, did not review others.

I would like to see someone else maintaining it, though. I can maintain it until may, so I don't mind merging this with me as maintainer, but from may to 2019 I cannot be maintainer of any nixpkg, so if someone would step up as maintainer, I wouldn't mind! :smile:

**Comment by dotlambda** [comment]
@matthiasbeyer I think https://github.com/ryantm/nix-update will take care of maintaining :D

**Pull request merged**
