### PR TITLE
nixos: warn on missing `stateVersion`

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

The first patch is OCD. The last patch is the part of #35366 everyone agreed upon. The middle one is plumbing.

###### Things done

- [X] It works.
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Can you verify that this would be set in the vms? I belivenit was missing on those configs.

**Comment by oxij** [comment]
> Can you verify that this would be set in the vms? I belivenit was missing on those configs.

You mean VMs? Is there a use case where this warning should not be given? Can you elaborate?
The original thread doesn't mention any such things.

**Comment by oxij** [comment]
Well, building `.vm` attribute should work exactly as before as it uses normal `configuration.nix`. VM tests might generate some warnings, but that could be cleaned up later.

Let's just check, I guess

@GrahamcOfBorg test boot

**Comment by oxij** [comment]
Rebased.

@GrahamcOfBorg test boot

**Comment by matthewbauer** [comment]
Ok sounds good as a warning.

**Comment by oxij** [comment]
Thanks!

**Comment by danbst** [comment]
> The intent is that without stateVersion, you get the behaviour of the latest release, which presumably is not broken.

When doing release upgrades with nixos-rebuild, it is untrue that you get unbroken behavior without `stateVersion`.

To make warning more justified, we can do like this:
1. Each module exports whether it depends on `system.nixos.stateVersion`
```
system.nixos.dependsOnStateVersion = mkIf_isNotOverriden cfg.package [ "services.postgresql.enable" ];
```
(I don't think we can check whether `cfg.package` evaluation depends on `system.nixos.stateVersion`, but if it is overriden in user configuration, then user probably pins it to some concrete version, so he doesn't require setting `system.nixos.stateVersion`)
2. Here we check if `system.nixos.dependsOnStateVersion` is empty. If it is, then no warning - user is aware of all his stateful options or doesn't have stateful options enabled. Otherwise we display list of options that would case disruption on release upgrades and abort evaluation.

**Comment by oxij** [comment]
Sure, we can do that, but I think that's an overkill as it introduces yet another general warning mechanism for a single use case. But if we had more of those, I would be ok with something like that.

As it stands now I'd prefer we go the way I specified above: split `stateVersion` into a bunch of per service options. That way you could migrate your services one by one between releases and we then could do warnings only when the service is enabled with the default warning system.

**Pull request merged**
