### PR TITLE
python2.pkgs.xmpppy: remove + dependent packages

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

- python2-only + unmaintained + network-facing -> let's get rid of it before CVEs are hitting us.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
I will add aliases if everyone is ok with the change in general.
cc @7c6f434c

**Comment by Mic92** [comment]
also includes https://github.com/NixOS/nixpkgs/pull/113931 so that evaluation not breaks.

**Comment by SuperSandro2000** [comment]
> python2-only

If it is python 2 only it shouldn't contain python 3 in the commit message tbh.

**Comment by Mic92** [comment]
> > python2-only
> 
> If it is python 2 only it shouldn't contain python 3 in the commit message tbh.
> 
> > I will add aliases if everyone is ok with the change in general.
> 
> Fine for me. python packages usually do not get one but the top level entries need one.

there are some aliases for the xmpp transports so.

**Review by davidak — APPROVED** [review]
that is resonable

**Comment by davidak** [comment]
@Mic92 you mean an alias so users would get an error that the package was removed, because it's outdated and unmaintained? that seem very useful

i already merged the other pr. please rebase and set this to draft until it's ready to merge

**Comment by Mic92** [comment]
is this it an artificial limitation that you cannot rebase the same branch? @zowoq

**Comment by Mic92** [comment]
aliases added.

**Comment by zowoq** [comment]
> is this it an artificial limitation that you cannot rebase the same branch?

Yes, I only intended for it to be used when changing branches. Rebasing on the same branch [has been requested](https://github.com/NixOS/nixpkgs/pull/110843#issuecomment-780933014), I'm not really in favour of adding it but I've got a couple of errors I'll likely need to fix anyway so I'll take a look.

**Comment by davidak** [comment]
@Mic92 Thanks! Can you also add an alias for jabberbot here?

**Comment by Mic92** [comment]
> @Mic92 Thanks! Can you also add an alias for jabberbot here?

jabberbot is a python package. We only have aliases for packages in all-packages.nix

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 113933` [1](https://github.com/Mic92/nixpkgs-review)

**Review by davidak — APPROVED** [review]

**Comment by bqv** [comment]
Can be reversed? xmpppy no longer py2 only / unmaintained

**Comment by Mic92** [comment]
I think it should be rather added as a new package. It is now setuptools based and has a new source.

**Pull request merged**
