### PR TITLE
python3Packages.iso8601: switch to pytestCheckHook

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change

- Switch to `pytestCheckHook`
- Add license
- Update homepage entry
 
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
The maintainer has been inactive for almost three years. We need a new one.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 120698` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>python3Packages.iso8601</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Looks good

**Comment by davidak** [comment]
Since this does not change the package, it should not break other packages that depend on it.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 120698` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>python3Packages.iso8601</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]

**Pull request merged**
