### PR TITLE
smlnj: 110.79 -> 110.84

### PR DESCRIPTION
**Pull request by nalbyuites**
###### Motivation for this change
Newer binary required for https://www.coursera.org/learn/programming-languages

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build smlnj

**Comment by Mic92** [comment]
@jwiegley do you know why it tries to build on aarch64-linux at all?

**Comment by jwiegley** [comment]
> @jwiegley do you know why it tries to build on aarch64-linux at all? The darwin build was also broken before.

No, I don't.

**Comment by nalbyuites** [comment]
@Mic92 Is there anything else I need to do here or will Hydra pick this up eventually and it will be available on the binary cache?

**Comment by Mic92** [comment]
@nalbyuites it will be only picked up by hydra, when it is merged.
Can you have a look at `manticore`. This got broken by the update.

**Comment by nalbyuites** [comment]
@Mic92 I will take a look at manticore. Could you please let me know which jobset to look under [here](https://hydra.nixos.org/search?query=manticore) to find the job that failed?

**Comment by nalbyuites** [comment]
@Mic92 My bad. I realized that I could do `nix-build -A manticore` on my branch locally and I was [able to reproduce](https://gist.github.com/nalbyuites/c85c82f6827a0e722e1a21613a70f010#file-manticore_build-fail_smlnj-110_84-txt) the build failure. Looking into it.

**Comment by nalbyuites** [comment]
@Mic92 [As pointed out](https://github.com/ManticoreProject/manticore/issues/8#issuecomment-443344386) by manticore developer @kavon, newer SML/NJ does not work is because of a change in MLRISC, which is part of SML/NJ, that was made in SML/NJ 110.81.

I have asked him to ratify if the latest manticore revision is stable enough to use.

**Comment by nalbyuites** [comment]
Manticore: 2018-09-29 (revision 47273c463) is [good to go](https://github.com/ManticoreProject/manticore/issues/8#issuecomment-443446102).

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
