### PR TITLE
Fix mg building on darwin by changing to new upstream

### PR DESCRIPTION
**Pull request by druimalban**
For context, this is for the issue https://github.com/NixOS/nixpkgs/issues/71136.

This PR now sets the upstream to https://github.com/ibara/mg. For context I will leave the original comment (which patched the original upstream using patches from https://github.com/ibara/mg which apply missing header files on darwin) below.

**Original comment:**

I am not happy with this at all. It avoids using libbsd at all on darwin because there are conflicting header files, particularly the header string.h.

Ideally that would be the thing to fix upstream. But in the meantime, this patch should do the trick. This is taken from https://github.com/ibara/mg and the license of the patch is the same as `mg` itself. Homebrew and macports carry https://github.com/ibara/mg. Fink does not package it. Debian and many Linux distributions carry https://github.com/hboetes/mg. NetBSD pkgsrc carries the hboetes version albeit from 2011 (!). Something also relevant, is that MacOS as of MacOS Catalina removed their very old (pre-GPLv3) Emacs from the base operating system, and actually replaced it with a reasonably recent version of `mg`.

The patch declares a header file `apple.h`, which files include if target is darwin (checks for presence of `__APPLE__`). This header file also references the three source files `futimens.c`, `reallocarray.c` and `strtonum.c`. The former and  latter are from https://github.com/ibara/mg. Also of note is that `futimens` was added to macOS as of 10.13, but 10.12 does not have it so it still is necessary to patch it for now. There might be a better way.

From the OpenBSD source tree is `_null.h` and `tree.h`. There is a check so that if `__APPLE__` is present then it will include them from this source tree.

Now, the makefile GNUMakefile will not link against `libbsd` on darwin, by checking the output of uname in much the same way as it did already for FreeBSD. 

I would really appreciate testing on NixOS and other Linux distributions!

This applies to the same version in 19.09 and nixpkgs-unstable.

###### Motivation for this change
This package is not marked as broken, but it is on macOS. It is a generally useful small emacs-like editor. The package in nixpkgs is also quite old, so it makes sense to update it to the most recent release from the upstream source repository.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
Would it make sense to just use ibara/mg to not having to patch it ourself?

**Comment by druimalban** [comment]
> Would it make sense to just use ibara/mg to not having to patch it ourself?

I think so? It removes the dependency on libbsd.

I have just tested it and it works just as fine. Should I push to this PR?

**Comment by Mic92** [comment]
Yes.

**Comment by Mic92** [comment]
@GrahamcOfBorg build mg

**Pull request merged**
