### PR TITLE
treewide: pkgs.pkgconfig -> pkgs.pkg-config, move pkgconfig to alias.nix

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
continuation of #109595

`pkgconfig` was aliased in 2018, however, it remained in
all-packages.nix due to its wide usage. This cleans
up the remaining references to pkgs.pkgsconfig and
moves the entry to aliases.nix.

python3Packages.pkgconfig remained unchanged because
it's the canonical name of the upstream package
on pypi.

cc @siraben  @SuperSandro2000 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
I'm going to ignore the white space check, because I value my sanity when editing 1717 files

**Comment by jonringer** [comment]
this works for files which just add pkg-config as an input, but patching was broken by this

**Comment by siraben** [comment]
@jonringer What command did you run to do this? I did the following to ensure it only affected Nix files.

```ShellSession
$ find pkgs/tools -name "*.nix" -type f -print0 | xargs -0 sed -i '' -E "s#pkgconfig#pkg-config#g"  
```

**Comment by jonringer** [comment]
I did the yolo replace, find + sed to everything. But I've locally reverted almost all of the non .nix changes

**Comment by jonringer** [comment]
i got it down to below 100 rebuilds, one issue is that I have to change chrootenv/default.nix to reference `pkg-config`, however, that directory is referenced as `./.` inside the script which includes the default.nix, so there's no way for me to update the underlying chroot package without causing rebuilds

**Comment by jonringer** [comment]
however, I went from 32k rebuilds, to ~80. Which is reasonable for master

**Review by siraben — APPROVED** [review]
LGTM

**Comment by jonringer** [comment]
I will probably merge this shortly, as treewide PRs bitrot quickly

**Comment by jonringer** [comment]
trying to get to 0 new failures

**Comment by jonringer** [comment]
no new failures

```
https://github.com/NixOS/nixpkgs/pull/109887

1 package marked as broken and skipped:
rapcad

8 packages failed to build:
batctl houdini influxdb2 libjson-rpc-cpp php73Extensions.imagick php74Extensions.imagick php80Extensions.imagick quartus-prime-lite

61 packages built:
appimage-run arduino-ci arduino-cli bitscope.chart bitscope.console bitscope.display bitscope.dso bitscope.logic bitscope.meter bitscope.proto bitscope.server blas-reference clonehero cloudcompare conda dropbox dropbox-cli esphome fahclient flutter flutter-beta flutter-dev hover imagemagick7 imagemagick7Big imagemagick7_light ldgallery left4gore-bin libsForQt5.dxflib libsForQt512.dxflib libsForQt514.dxflib libtensorflow-bin lightworks mate.caja-dropbox paperless pkgconfig pkgconfigUpstream platformio plex portmod python37Packages.SQLAlchemy-ImageAttach python37Packages.Wand python37Packages.fenics python37Packages.goocalendar python38Packages.SQLAlchemy-ImageAttach python38Packages.Wand python38Packages.fenics python38Packages.goocalendar python39Packages.SQLAlchemy-ImageAttach python39Packages.Wand python39Packages.fenics python39Packages.goocalendar radare2-cutter saga sidequest tryton vapoursynth vapoursynth-editor vapoursynth-mvtools vmware-horizon-client zulip
```

**Comment by jonringer** [comment]
whitespace PR: https://github.com/NixOS/nixpkgs/pull/109911

**Comment by jonringer** [comment]
last two failures are from from not meeting `requireFile` requirements
```
https://github.com/NixOS/nixpkgs/pull/109887

1 package marked as broken and skipped:
rapcad

2 packages failed to build:
houdini quartus-prime-lite

46 packages built:
appimage-run arduino-ci arduino-cli bitscope.chart bitscope.console bitscope.display bitscope.dso bitscope.logic bitscope.meter bitscope.proto bitscope.server blas-reference clonehero cloudcompare conda dropbox dropbox-cli esphome fahclient flutter flutter-beta flutter-dev hover left4gore-bin libsForQt5.dxflib libsForQt512.dxflib libsForQt514.dxflib libtensorflow-bin lightworks mate.caja-dropbox pkgconfig pkgconfigUpstream platformio plex python37Packages.fenics python37Packages.goocalendar python38Packages.fenics python38Packages.goocalendar python39Packages.fenics python39Packages.goocalendar radare2-cutter saga sidequest tryton vmware-horizon-client zulip
```

**Comment by jonringer** [comment]
this is annoying, running ofborg locally with `allowAliases = false;` causes alias issues which aren't related to the PR

**Comment by jonringer** [comment]
once ofborg passes, I'm merging

**Review by hmenke — APPROVED** [review]

**Comment by jonringer** [comment]
alright, I think this is in good enough shape. Merging as I want to go to bed, and need to wake up in ~5 hours

**Comment by SuperSandro2000** [comment]
I hope I do not merge a PR which introduces new build failures by using old ofborg evals.

**Pull request merged**
