### PR TITLE
feishin: 0.5.1 -> 0.5.3, build from source

### LINKED ISSUE #287765: Update request: feishin 0.5.1 → 0.5.3
- Package name: feishin
- Latest released version: 0.5.3

- Current version on the unstable channel: 0.5.1
- Current version on the stable/release channel: 0.5.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@onny

-----

Note for maintainers: Please tag this issue in your PR.

---

Version 0.5.1 is using Electron 25, leading to build issues, as it is deprecated. The upstream package has since upgraded to Electron 27. 

There is an issue tracking package regressions with electron 25: https://github.com/NixOS/nixpkgs/issues/265125

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dotlambda**
This currently fails to run with
```
App threw an error during load
Error: Cannot find module 'mpris-service'
Require stack:
- /nix/store/scd452047r76hyp2506zmhvrlv5jgrha-feishin-0.5.3/opt/feishin/resources/app.asar/dist/main/main.js
- /nix/store/pdwgakam5llj22xi7d7vpxbldwgs9inc-electron-unwrapped-27.2.3/libexec/electron/resources/default_app.asar/main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/browser_init:2:116646)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at 77178 (/nix/store/scd452047r76hyp2506zmhvrlv5jgrha-feishin-0.5.3/opt/feishin/resources/app.asar/dist/main/main.js:14:609796)
    at n (/nix/store/scd452047r76hyp2506zmhvrlv5jgrha-feishin-0.5.3/opt/feishin/resources/app.asar/dist/main/main.js:14:805763)
    at 91312 (/nix/store/scd452047r76hyp2506zmhvrlv5jgrha-feishin-0.5.3/opt/feishin/resources/app.asar/dist/main/main.js:14:543748)
    at n (/nix/store/scd452047r76hyp2506zmhvrlv5jgrha-feishin-0.5.3/opt/feishin/resources/app.asar/dist/main/main.js:14:805763)
```
because `mpris-service` is specified as a dependency in https://github.com/jeffvli/feishin/blob/v0.5.3/release/app/package.json.
It would be nice if someone who actually uses the package could pick up the work.

## Description of changes
Diff: https://github.com/jeffvli/feishin/compare/refs/tags/v0.5.1...v0.5.3

Changelog: https://github.com/jeffvli/feishin/releases/tag/v0.5.3

fixes https://github.com/NixOS/nixpkgs/issues/287765
cc @nadir-ishiguro

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by onny** [comment]
This looks nice! So we would need mpris-service packaged? https://github.com/NixOS/nixpkgs/pull/288274

**Comment by dotlambda** [comment]
> This looks nice! So we would need mpris-service packaged? #288274

No, we'd need to add another expression that runs `buildNpmPackage` on the subdirectory.

**Comment by jlbribeiro** [comment]
Hey @dotlambda, thanks for this PR!

Just to keep it up-to-date, **[jeffvli/feishin v0.6.1](https://github.com/jeffvli/feishin/releases/tag/v0.6.1)** has been released.

Notice the release notes mention having downgraded from Electron v27 to **v26** to restore compatibility with macOS 10.13 and 10.14 (https://github.com/jeffvli/feishin/issues/534), but that issue was later re-opened as [that didn't fix it](https://github.com/jeffvli/feishin/issues/534#issuecomment-1999313717):
> I know for sure that Electron v25 works, but we need to find out which version if any v26 will work.

**Comment by nadir-ishiguro** [comment]
Well, that's a bit worrying. Downgrading Electron to support deprecated macOS versions seems like an odd choice to me.

**Pull request closed without merging**
