### PR TITLE
nixos/adguardhome: Fix #154775, add test

### LINKED ISSUE #154775: Adguardhome service fails
## Issue description

I added:
```
services.adguardhome = {
  enable = true;
};
```
to my config and rebuilt. After a few minutes of downloading, it printed this error, and quit:

```
2022/01/12 14:23:54.220384 [info] AdGuard Home, version v0.107.0
2022/01/12 14:23:54.228677 [info] home.upgradeSchema0to1(): called
2022/01/12 14:23:54.228912 [info] deleting /nix/store/36xs8gfxdkfrwl44y4vj2krmscy1a8lf-adguardhome-0.107.0/bin/dnsfilter.txt as we don't need it anymore
2022/01/12 14:23:54.229405 [info] home.upgradeSchema1to2(): called
2022/01/12 14:23:54.229518 [info] deleting /nix/store/36xs8gfxdkfrwl44y4vj2krmscy1a8lf-adguardhome-0.107.0/bin/Corefile as we don't need it anymore
2022/01/12 14:23:54.230035 [info] home.upgradeSchema2to3(): called
2022/01/12 14:23:54.230683 [fatal] dns configuration is not a map
```

I'm running latest nixos-unstable, and the machine is a x86_64-linux, although the same is also happening in `qemu-aarch`.

### Steps to reproduce

Use latest nixos-unstable (currently `b2737d4980a17cc2b7d600d7d0b32fd7333aca88`)

Add the before mentioned code to your config

Rebuild your system

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.12-xanmod1-tt, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(root): `""`
 - channels(nix): `""`
 - nixpkgs: `/nix/store/0gaazn04dikcwqrwrw9y0h4x8rmrn3js-1hdyp90ilq8gksc56dryg991kq3pc9bb-source`
```

Maintainers: @numkem and @iagocq

### PR DESCRIPTION
**Pull request by CRTified**
###### Motivation for this change

AdGuard Home fails to build if `services.adguardhome.settings` is not configured properly (where "properly" depends on the exact version/config schema). This was caused by my PR #152029.

This PR both fixes #154775 which reported this problem, and adds a test so that it won't happen again.

The test contains two cases:
 - Minimal config, where only `services.adguardhome.enable = true;` is set
 - Declarative config, where `services.adguardhome.settings` is used with a minimal configuration

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Pinging @aanderse @lunik1 @rhoriguchi as you all gave feedback on the original PR.

### CODE REVIEW

**Comment by legendofmiracles** [comment]
This should probably be linked to the adguardhome package, so that reviewers can more easily know they should run this.

**Comment by CRTified** [comment]
Like this, @legendofmiracles ? In that case, feedback from @numkem  and @iagocq might make sense, too.

**Comment by legendofmiracles** [comment]
Yup, looks good!

Also, confirmed to fix the issue for me

**Comment by lunik1** [comment]
What will happen in the case where `dns.bootstrap_dns` is defined, but `dns.bind_host` is not (or vice versa). If we know these settings are necessary for a minimally working config, does it make sense to assert both are present if `settings` is not empty?

**Comment by legendofmiracles** [comment]
I haven't played around a lot with adguardhome, but if they're both so critical imo they should be their own options, and not part of a larger settings conglomerate. 

That way it's also easier to check if it's set with an assertion

**Comment by CRTified** [comment]
> What will happen in the case where `dns.bootstrap_dns` is defined, but `dns.bind_host` is not (or vice versa). If we know these settings are necessary for a minimally working config, does it make sense to assert both are present if `settings` is not empty?

@lunik1 In these cases, even building the config will fail - exactly in the same way as in #154775 as it was the same problem. The generated config file has a `checkPhase` where adguard verifies the configuration and fails. 

Maybe an assertion (`settings != {}` and both options missing) would make sense in general, but IIRC a coming release will allow for a list of hosts to bind to and offer an alternative name for that option (iirc it was `bind_hosts`).

Adding an option would also more or less imply setting a sensible default, and I don't like to set a default upstream DNS for *everyone*.

**Comment by legendofmiracles** [comment]
Doesn't adguardhome default to 9.9.9.9? If we also chose that with the new option then that'd be OK imo.

Otherwise I think it's ok to merge as is, a user who only sets one option (already rare enough) can find the explanation by searching for it in the issues tab of nixpkgs - which was my first thought when I had the error.

**Comment by CRTified** [comment]
Running `adguardhome -w /tmp`, going through the setup process and just configuring it to listen on `lo` yields [this config](https://gist.github.com/CRTified/1da87d659fe3f82592f38cb1dd559591).

It defaults to these values with `schema_version` 12:
```yaml
  bind_hosts:
  - 127.0.0.1
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
schema_version: 12
```

If they're the default one way or another, it would be fine for me to use them as default. Nonetheless, it might make the merging-step way harder if we keep them as separate option with a default, as we don't want to override the configured value in all cases.

I'd assume adding the mentioned assertion solves all this, as it prevents an invalid config as in your issue, while also keeping the module definition as simple as possible.

**Comment by CRTified** [comment]
I've added the assertions, please give feedback @legendofmiracles

**Comment by legendofmiracles** [comment]
The assertions seem to work correctly, but once I set the values (nixos test code) the service fails to start with:
```
systemd[1]: Starting AdGuard Home: Network-level blocker...
adguardhome-pre-start[2234]: Traceback (most recent call last):
adguardhome-pre-start[2234]:   File "/nix/store/4d263m2v4clf88dpkig7d5nygp1pixsn-yaml-merge-unstable-2016-02-16/bin/.yaml-merge-wrapped", line 28, in <module>
adguardhome-pre-start[2234]:     file1 = yaml.load(f)
adguardhome-pre-start[2234]: TypeError: load() missing 1 required positional argument: 'Loader'
systemd[1]: adguardhome.service: Control process exited, code=exited, status=1/FAILURE
```

The config file already exists, since the service has been running before.

**Comment by CRTified** [comment]
Interesting. I should probably be able to cover all code paths by simply restarting the service in the second case.

**Comment by rhoriguchi** [comment]
> Running `adguardhome -w /tmp`, going through the setup process and just configuring it to listen on `lo` yields [this config](https://gist.github.com/CRTified/1da87d659fe3f82592f38cb1dd559591).
> 
> It defaults to these values with `schema_version` 12:
> 
> ```yaml
>   bind_hosts:
>   - 127.0.0.1
>   bootstrap_dns:
>   - 9.9.9.10
>   - 149.112.112.10
>   - 2620:fe::10
>   - 2620:fe::fe:10
> schema_version: 12
> ```
> 
> If they're the default one way or another, it would be fine for me to use them as default. Nonetheless, it might make the merging-step way harder if we keep them as separate option with a default, as we don't want to override the configured value in all cases.
> 
> I'd assume adding the mentioned assertion solves all this, as it prevents an invalid config as in your issue, while also keeping the module definition as simple as possible.

Why not just set that as default and merge whatever gets set, that way those settings will always be set and make `settings` default `{}`. Doesn't that solve all issues of validation, since it will be set if the user does not change it and removing is also not possible without explicitly setting a default value do `null` or `{}`?

So something like this:

```nix
defaultSettings = {
    bind_hosts = [ "127.0.0.1" ];
    bootstrap_dns = [ "9.9.9.10" "149.112.112.10" "2620:fe::10" "2620:fe::fe:10" ];
    schema_version = 12;
};

configFile = pkgs.writeTextFile {
    name = "AdGuardHome.yaml";
    text = builtins.toJSON (recursiveUpdate defaultSettings cfg.settings baseConfig);
    checkPhase = "${pkgs.adguardhome}/bin/adguardhome -c $out --check-config";
};
  ```

**Comment by CRTified** [comment]
> Doesn't that solve all issues of validation, since it will be set if the user does not change it and removing is also not possible without explicitly setting a default value to null or {} in the cfg.settings?

No. If you have `mutableSettings = true` and change these settings in the WebUI, they'd be overwritten by the set default value even though the user changed a setting and wants it to be kept.

**Comment by lunik1** [comment]
What if the defaults change in future? The schema version almost certainly will.

**Comment by CRTified** [comment]
> What if the defaults change in future? The schema version almost certainly will.

That's also a problem, but the schema version would be the smallest problem, as that will get upgraded by AdGuard on launch.

**Comment by rhoriguchi** [comment]
@CRTified good point, i didn't think about the mutable case. That could be addressed with a later yaml merge,  but that's a bit overengineerred and the yaml check wouldn't work.

---

@lunik1 probably version 10 schema would be better, since there's an older version of adguard on other release channels.

**Comment by afreakk** [comment]
> The assertions seem to work correctly, but once I set the values (nixos test code) the service fails to start with:
> 
> ```
> systemd[1]: Starting AdGuard Home: Network-level blocker...
> adguardhome-pre-start[2234]: Traceback (most recent call last):
> adguardhome-pre-start[2234]:   File "/nix/store/4d263m2v4clf88dpkig7d5nygp1pixsn-yaml-merge-unstable-2016-02-16/bin/.yaml-merge-wrapped", line 28, in <module>
> adguardhome-pre-start[2234]:     file1 = yaml.load(f)
> adguardhome-pre-start[2234]: TypeError: load() missing 1 required positional argument: 'Loader'
> systemd[1]: adguardhome.service: Control process exited, code=exited, status=1/FAILURE
> ```
> 
> The config file already exists, since the service has ran before, without any settings

This error is related to an issue with yaml-merge (https://github.com/NixOS/nixpkgs/pull/155218)
Not anything to do with this module

**Comment by CRTified** [comment]
Thanks for fixing this, @afreakk . I didn't have the time to fix this so far.

I've also added an additional test case that covers the `yaml-merge` codepath by restarting the service. 
While it does not check the success of `yaml-merge` with changed settings, it does at least check whether `yaml-merge` runs successfully.

This should prevent breakage by `yaml-merge` in the future.

**Comment by CRTified** [comment]
Sorry, I accidentally pulled in your changes.

**Pull request merged**
