### PR TITLE
nixos/transmission: disable downloadDirPermissions by default

### LINKED ISSUE #100074: transmission: download directory creation on zfs filesystems prevents zfs from mounting
**Describe the bug**

transmission creates the download directory in extremely early boot before zfs mounts the filesystems [here](https://github.com/NixOS/nixpkgs/blob/4da09d369baa2200edb9df27fe9c88453b0ea6cf/nixos/modules/services/torrent/transmission.nix#L149).

zfs then fails to mount a pool later with 

```
cannot mount '/somepool': directory is not empty
```

or something similar.

**To Reproduce**
1. use zfs, with secondary pools (from rootfs)
2. set transmission to use download directory in one of said secondary pools
3. boot the system.

**Expected behavior**
transmission should wait for zfs pools to be mounted before attempting any of its initialization actions (especially when I have something like

```
  systemd.services."transmission" = {
    requires = ["zfs-mount.service"];
    after = ["zfs-mount.service"];
  };
```

in my config.

**Notify maintainers**
@ju1m 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 21.03pre244817.fc3766140c4 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre244817.fc3766140c4"`
 - channels(nagisa): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: transmission
```

### PR DESCRIPTION
**Pull request by ju1m**
###### Motivation for this change
Let the user responsible for creating the directories when the defaults are not used.
Fixes #100074 and #147239.

###### Things done
- [X] Disable `downloadDirPermissions` by default
- [X] Use `StateDirectory=` to create the directories used when the default `services.transmission.user == "transmission"` and `services.transmission.home == "/var/lib/transmission"` are kept.
- [X] `nix -L build -f . nixosTests.bittorrent`

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
As long as this fixes things for @monokrome I'm good with it. Diff looks good to me :+1:

**Comment by monokrome** [comment]
Is this blocked or is it waiting on me to say something? This seems like a good change to me :o

**Comment by aanderse** [comment]
> Is this blocked? Like, waiting on me to say something? This seems like a good change to me if so :o

:thinking: Yes...?

@ju1m merge?

**Comment by ju1m** [comment]
@aanderse, sure, please do, I'm not a committer.

**Comment by aanderse** [comment]
Thanks!

**Pull request merged**
