### PR TITLE
obs-studio-plugins.input-overlay: 5.0.0 -> 5.0.4

### PR DESCRIPTION
**Pull request by pinpox**
Diff: https://github.com/univrsal/input-overlay/compare/v5.0.0...v5.0.4

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by keenanweaver** [comment]
Looks like SDL2 was added. https://github.com/univrsal/input-overlay/commit/4d7e7d9592f15f48fb068114bc4c37482599a45e

---

Result of `nixpkgs-review pr 250960` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.input-overlay</li>
  </ul>
</details>

```nix
obs-input-overlay> building '/nix/store/xwc6agx7h3q49prjlwwva5my6y3xgfa3-obs-input-overlay-5.0.4.drv'
obs-input-overlay> qtPreHook
obs-input-overlay> unpacking sources
obs-input-overlay> unpacking source archive /nix/store/sgxdii1b9phxqlcnwhiifyvka0nzn4w4-source
obs-input-overlay> source root is source
obs-input-overlay> patching sources
obs-input-overlay> updateAutotoolsGnuConfigScriptsPhase
obs-input-overlay> configuring
obs-input-overlay> fixing cmake files...
obs-input-overlay> cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/share/doc/input-overlay -DCMAKE_INSTALL_INFODIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/include -DCMAKE_INSTALL_SBINDIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/strip -DCMAKE_RANLIB=/nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/ranlib -DCMAKE_AR=/nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/q58dfz5kx0rf50mqxjqc1i70rgmx6ids-obs-input-overlay-5.0.4
obs-input-overlay> -- The C compiler identification is GNU 12.3.0
obs-input-overlay> -- The CXX compiler identification is GNU 12.3.0
obs-input-overlay> -- Detecting C compiler ABI info
obs-input-overlay> -- Detecting C compiler ABI info - done
obs-input-overlay> -- Check for working C compiler: /nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/gcc - skipped
obs-input-overlay> -- Detecting C compile features
obs-input-overlay> -- Detecting C compile features - done
obs-input-overlay> -- Detecting CXX compiler ABI info
obs-input-overlay> -- Detecting CXX compiler ABI info - done
obs-input-overlay> -- Check for working CXX compiler: /nix/store/n847wr4vj9f3nszbgnqz9n8w3vnnfmcd-gcc-wrapper-12.3.0/bin/g++ - skipped
obs-input-overlay> -- Detecting CXX compile features
obs-input-overlay> -- Detecting CXX compile features - done
obs-input-overlay> -- Found PkgConfig: /nix/store/bhn19xy6sva5vf6nzz5szljdyyvlnrib-pkg-config-wrapper-0.29.2/bin/pkg-config (found version "0.29.2")
obs-input-overlay> -- Checking for one of the modules 'sdl2'
obs-input-overlay> CMake Error at /nix/store/p4yxdhbwfijv7yfakvs6xxsmxwgqxy7g-cmake-3.26.4/share/cmake-3.26/Modules/FindPkgConfig.cmake:894 (message):
obs-input-overlay>   None of the required 'sdl2' found
obs-input-overlay> Call Stack (most recent call first):
obs-input-overlay>   deps/CMakeLists.txt:30 (PKG_SEARCH_MODULE)
obs-input-overlay>
obs-input-overlay>
obs-input-overlay> -- Checking for module 'x11'
obs-input-overlay> --   Found x11, version 1.8.6
obs-input-overlay> -- Checking for module 'xtst'
obs-input-overlay> --   Found xtst, version 1.2.4
obs-input-overlay> -- Looking for XRecordQueryVersion in Xtst
obs-input-overlay> -- Looking for XRecordQueryVersion in Xtst - found
obs-input-overlay> -- Looking for X11/extensions/record.h
obs-input-overlay> -- Looking for X11/extensions/record.h - found
obs-input-overlay> -- Checking for module 'xkbcommon-x11'
obs-input-overlay> --   Found xkbcommon-x11, version 1.5.0
obs-input-overlay> -- Checking for module 'x11-xcb'
obs-input-overlay> --   Found x11-xcb, version 1.8.6
obs-input-overlay> -- Checking for module 'xkbfile'
obs-input-overlay> --   Found xkbfile, version 1.1.2
obs-input-overlay> -- Checking for module 'xt'
obs-input-overlay> --   Found xt, version 1.3.0
obs-input-overlay> -- Checking for module 'xinerama'
obs-input-overlay> --   Found xinerama, version 1.1.5
obs-input-overlay> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
obs-input-overlay> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
obs-input-overlay> -- Found Threads: TRUE
obs-input-overlay> -- Performing Test HAVE_STDATOMIC
obs-input-overlay> -- Performing Test HAVE_STDATOMIC - Success
obs-input-overlay> -- Qt version found: 6
obs-input-overlay> -- Found OpenGL: /nix/store/4psnynr2gp8piqsmpdpas58v5vf7r2dr-libGL-1.6.0/lib/libOpenGL.so
obs-input-overlay> -- Found WrapOpenGL: TRUE
obs-input-overlay> -- Found XKB: /nix/store/48ik6fm41v4sy5hxc6sisdbbqh8f321k-libxkbcommon-1.5.0/lib/libxkbcommon.so (found suitable version "1.5.0", minimum required is "0.5.0")
obs-input-overlay> -- Found WrapVulkanHeaders: /nix/store/gf9wnl5dkdaz8hv51f8h505cs3pm9gws-vulkan-headers-1.3.254/include
obs-input-overlay> -- Configuring incomplete, errors occurred!
error: builder for '/nix/store/xwc6agx7h3q49prjlwwva5my6y3xgfa3-obs-input-overlay-5.0.4.drv' failed with exit code 1;
       last 25 log lines:
       > -- Looking for XRecordQueryVersion in Xtst
       > -- Looking for XRecordQueryVersion in Xtst - found
       > -- Looking for X11/extensions/record.h
       > -- Looking for X11/extensions/record.h - found
       > -- Checking for module 'xkbcommon-x11'
       > --   Found xkbcommon-x11, version 1.5.0
       > -- Checking for module 'x11-xcb'
       > --   Found x11-xcb, version 1.8.6
       > -- Checking for module 'xkbfile'
       > --   Found xkbfile, version 1.1.2
       > -- Checking for module 'xt'
       > --   Found xt, version 1.3.0
       > -- Checking for module 'xinerama'
       > --   Found xinerama, version 1.1.5
       > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
       > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
       > -- Found Threads: TRUE
       > -- Performing Test HAVE_STDATOMIC
       > -- Performing Test HAVE_STDATOMIC - Success
       > -- Qt version found: 6
       > -- Found OpenGL: /nix/store/4psnynr2gp8piqsmpdpas58v5vf7r2dr-libGL-1.6.0/lib/libOpenGL.so
       > -- Found WrapOpenGL: TRUE
       > -- Found XKB: /nix/store/48ik6fm41v4sy5hxc6sisdbbqh8f321k-libxkbcommon-1.5.0/lib/libxkbcommon.so (found suitable version "1.5.0", minimum required is "0.5.0")
       > -- Found WrapVulkanHeaders: /nix/store/gf9wnl5dkdaz8hv51f8h505cs3pm9gws-vulkan-headers-1.3.254/include
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/xwc6agx7h3q49prjlwwva5my6y3xgfa3-obs-input-overlay-5.0.4.drv'.
error: 1 dependencies of derivation '/nix/store/s9wp46jh8k16pagmabq1p740n8b42sp5-review-shell.drv' failed to build
┏━ 1 Errors:
```

**Comment by keenanweaver** [comment]
I really don't know, but my hunch is something in the cmake needs to be modified for it to build. Doesn't seem to be an upstream problem. Hoping someone with much more experience than me chimes in.

**Comment by pinpox** [comment]
> Hoping someone with much more experience than me chimes in.

Ok, I'll wait for further instructions on this then. I have no clue how to proceed currently

**Review by flexiondotorg — APPROVED** [review]
I've tested this locally and it works correctly.

**Pull request merged**
