### PR TITLE
linux: add CONFIG_KEY_DH_OPERATIONS

### PR DESCRIPTION
**Pull request by yorickvP**
###### Motivation for this change

Intel has been working on a [wpa_supplicant replacement that's simpler](https://git.kernel.org/pub/scm/network/wireless/iwd.git/about/) (just released v0.3). It offloads most crypto to the kernel. For some of this (WPS support), CONFIG_KEY_DH_OPERATIONS has to be enabled.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by lukateras — APPROVED** [review]
`iwd` is already in nixpkgs, so reasonable that we would enable options that it relies on.

**Comment by yegortimoshenko** [comment]
Patch that introduced this option: https://github.com/torvalds/linux/commit/ddbb41148724367394d0880c516bfaeed127b52e

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build linux

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build linux

**Pull request merged**
