### PR TITLE
clightning: 23.05.2 -> 23.08

### PR DESCRIPTION
**Pull request by jonasnick**
## Description of changes

change log: https://github.com/ElementsProject/lightning/releases/tag/v23.08

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

CC @jb55 @prusnak

### CODE REVIEW

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
we need to add the clnrest plugin inside the `postPatch =` because we have some error

With the current code there is the following error at runtime https://github.com/ElementsProject/lightning/issues/6637

**Comment by prusnak** [comment]
> we need to add the clnrest plugin inside the `postPatch =` because we have some error

Ok, will wait for update of the PR

**Comment by chrisguida** [comment]
Need to replace this vanilla python hashbang, not sure how to actually do this in the build: https://github.com/ElementsProject/lightning/blob/master/plugins/clnrest/clnrest.py#L1

**Comment by chrisguida** [comment]
shebang updated here https://github.com/NixOS/nixpkgs/pull/253539

clnrest doesn't start, but at least it doesn't take down your whole node now.

we need a better solution for python dependencies.

this seems promising https://github.com/nix-community/poetry2nix

but we'd need to convert clnrest's requirements.txt file into a poetry project

also see: https://github.com/ElementsProject/lightning/issues/6637#issuecomment-1707595266

**Comment by prusnak** [comment]
Merged this PR

Let's deal with the clnrest fixes in https://github.com/NixOS/nixpkgs/pull/253539

**Pull request merged**
