### PR TITLE
zoom-us: init at 2.0.91373.0502

### PR DESCRIPTION
**Pull request by danbst**
Actually, reintroduce after removal (https://github.com/NixOS/nixpkgs/commit/bb99babc5a1c62edd012da5a1ad14cd3fe1abf0a)
and use bundled Qt.

Stepping up as a maintainer

Still, some bugs present (like crash when log-in using Facebook, clear ~/.zoom to recover, bug reported upstream) and I didn't test video (no cam).

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by k0001** [comment]
@danbst I just tried this, it's working for me.

I recommend renaming the executable to `zoom-us` because there already exists another package called `zoom` exposing an executable called `zoom`. Moreover, `zoom-us` was what the executable was called until `zoom-us` package was removed some weeks ago. 

Also, I recommend against just copying all of the top-level contents of the zoom sources to `$out/share`, since there's a lot of noisy garbage there. Could you create a folder `$out/share/zoom` instead and put all of the files in there?

**Review by k0001 — APPROVED** [review]
Works for me!

**Comment by shlevy** [comment]
:confetti_ball:

**Comment by kamilchm** [comment]
Sign in with Google does nothing for me.
Sign in with SSO ends up with error:
```
Qt WebEngine resources not found at /home/levi/Qt5.6.2/5.6/gcc_64/resources. Trying parent directory...
Qt WebEngine resources not found at /home/levi/Qt5.6.2/5.6/gcc_64. Trying application directory...
[0607/214354:FATAL:udev_loader.cc(36)] Check failed: false.
```

**Comment by danbst** [comment]
@kamilchm same for me. :( Let's wait what upstream says about hardcode `/home/levi/Qt5.6.2/...`

**Comment by pshendry** [comment]
👍  Thanks for this, I was 2 hours in to trying to get Zoom running in an Ubuntu VM (crying as my underpowered laptop started compiling VirtualBox in order to use the extension pack for webcam support) before I stumbled upon this, saves me a lot of trouble. `nox zoom` didn't show me anything, not sure why...

**Pull request merged**
