### PR TITLE
nixos/system: socket unit restart logic

### PR DESCRIPTION
**Pull request by griff**
###### Motivation for this change

When only a socket systemd unit is changed nothting is done to restart
the service. This adds logic to stop the service and dependent sockets
and start the sockets again.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
I'm not familiar enough to review this properly, but just a thought: is there a simple way to test/reproduce this behavior? Asking both for myself but also because it'd be nice to have it as a nixos test to avoid regressing.  Thanks for tackling this!

**Comment by Mic92** [comment]
Testing update transition is currently not supported by our test framework.

**Comment by arianvp** [comment]
In theory I think this is a sensible change . Also the choice to only stop the service unit makes sense. I have not looked deeply into the code itself yet because I'm a bit unfamiliar with the activation logic

**Comment by arianvp** [comment]
Let's document very carefully how this behaves though. As currently restart logic is very fragile and underspecified in my opinion (see https://github.com/NixOS/nixpkgs/issues/49528)

**Comment by griff** [comment]
@arianvp if we are changing the activation logic anyway we should also make it testable. I have a pretty simple idea for how this could be done.

We just need to add an option to the activation script that tells it to dry-run and output what it would have done in some data format we can read from perl and then expand [nixos/tests/switch-test.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/switch-test.nix) with tests for the logic.

**Comment by domenkozar** [comment]
We just merged https://github.com/NixOS/nixpkgs/pull/73871, which takes a bit simpler approach. It's the smaller into the same direction.

Feel free to improve upon :)

**Comment by arianvp** [comment]
Thanks for re-opening. remaining isssues are discussed here https://github.com/NixOS/nixpkgs/issues/74899

**Comment by arianvp** [comment]
Having a look at this again.

> When only a socket systemd unit is changed nothting is done to restart
the service. This adds logic to stop the service and dependent sockets
and start the sockets again.

Why would you want to restart the service if the service itself didn't change though?

**Comment by griff** [comment]
@arianvp If you change the ports being listened on or the path of a unix socket and you use socket activation then only the `.socket` unit is changed and for the service to get the new socket it needs to be restarted.

**Comment by flokli** [comment]
@lheckemann how is this related to https://github.com/NixOS/nixpkgs/pull/73871 ?

**Comment by arianvp** [comment]
I disagree this is desired behaviour in call cases and I think the desired effect can already be achieved without modifying our activation logic. 

 If you want the service to never be started without the socket also starting you should set `Requires=mysocket.socket` on your service..

If you want the service to restart everytime the socket restarts you should set `PartOf=mysocket.socket` on the service. 


 However interestingly this will mess with things
because it uses systemd directly to restart the unit which ignores any `stopIfChanged` settings we have in our activaiton logic. Hmpph  (we really should get rid of this `stopIfChanged` stuff in my opinion)...

I'm now not sure what to do here

**Comment by lheckemann** [comment]
@flokli This one is an earlier effort that fpletz and I missed when making that PR (which has now been reverted because it's broken).

**Comment by flokli** [comment]
@arianvp if we consider socket-activated services, and changing listen adresses, we'd need to restart changed `.socket` units on activation.

**Comment by arianvp** [comment]
OH yeh i'm misreading the original PR sorry.

However I still think it doesn't work in all scenarios. Some services that are socket-activated are themselves still added to `multi-user.target`.  This way the socket activaiton logic is only used to enable parallel start up, but not on-demand startup.  This is a valid usecase that some of the sockets that systemd itself ships utilize. So we shouldn't always `stop` the service when the `socket` is restarted

This is also explained in this blog: http://0pointer.de/blog/projects/socket-activation.html

**Comment by lheckemann** [comment]
Not fixed.

**Comment by flokli** [comment]
I'm not sure I understand the description. But if only the `.socket` file is changed (for example due to another `ListenStream=` there, wouldn't it be sufficient to `systemctl restart` the `.socket` unit?

**Comment by lheckemann** [comment]
`systemctl restart nix-daemon` → journal says
```
Oct 12 11:26:27 ordnungsamd systemd[1]: Closed Nix Daemon Socket.
Oct 12 11:26:27 ordnungsamd systemd[1]: Stopping Nix Daemon Socket.
Oct 12 11:26:27 ordnungsamd systemd[1]: nix-daemon.socket: Socket service nix-daemon.service already active, refusing.
Oct 12 11:26:27 ordnungsamd systemd[1]: Failed to listen on Nix Daemon Socket.
```

**Comment by flokli** [comment]
Ah, now this makes more sense. Could the comments in this PR be updated to provide some more insights here?

Also, this only seems to be necessary/working for sockets with a falsy `Accept=` setting (the default). For truthy `Accept=` `.socket` units, services are spawned for each connection (so simply restarting the `.socket` there should be sufficient.

**Comment by arianvp** [comment]
This is desired behaviour.    If the daemon already has an open socket; systemd will not start the `.socket` unit as it's not needed for activation at that point. The daemon is already succesfully listening.

If you want `nix-daemon.service` to restart whenever `nix-daemon.socket` restarts; such that it gets handed a  socket FD with new settings from the `nix-daemon.socket` unit; you should add an explicit `Requires=nix-daemon.socket` to `nix-daemon.service`

this is clearly documented in the man-page

> No implicit WantedBy= or RequiredBy= dependency from the socket to the service is added. This means that the service may be started without the socket, in which case it must be able to open sockets by itself. To prevent this, an explicit Requires= dependency may be added.

I thus think failure to restart sockets should be silently ignored by the activation script.

**Pull request closed without merging**
