### PR TITLE
iproute: copy files in /etc

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Alternative for https://github.com/NixOS/nixpkgs/pull/39536 without recompiling customized version of ```iproute``` and without altering /etc/iproute2 to /run/iproute2

See discussion here https://github.com/NixOS/nixpkgs/pull/39536

cc @teto

### CODE REVIEW

**Comment by andir** [comment]
This looks a lot cleaner to me then the alternative approach (that has been merged by now).

Also it seems to be a lot more friendly to optimizations (when done "the nix way").

What would be really neat would be a test to verify that the custom tables names are indeed working. (A simple `ip route add $someRoute table foo; ip route show table foo;` should be sufficient for the simplest case.)

**Comment by teto** [comment]
It is ok for me !

**Comment by andir** [comment]
@volth anything from your side (besides maybe rephrasing the commit message) that must be done for this to go in?

I think this approach is superior to the one we merged. A changelog entry must probably be (updated?) made for this as well.

**Comment by teto** [comment]
@volth already updated the changelog entry so it should be fine.

**Comment by volth** [comment]
rebased

**Comment by xeji** [comment]
@volth please rebase again so we can get this into 18.09.

**Comment by xeji** [comment]
Sorry to trouble you again, but it should go to staging, I overlooked that...

**Comment by volth** [comment]
@grahamc why did ofborg add ```2.status: merge conflict``` ?

**Comment by FRidh** [comment]
@volth it did not, @xeji did and borg removed it

**Comment by FRidh** [comment]
oh, sorry, nevermind I'm wrong.

**Comment by xeji** [comment]
Sometimes ofborg gets the labels wrong when you change the base of an existing PR...
@grahamcofborg build iproute

**Comment by grahamc** [comment]
The issue I believe is the rebase happened and then the changed base.  the rebase caused a merge conflict and OfBorg maybe doesn’t evaluate on a base change. It probably should.

**Comment by Ericson2314** [comment]
This change modifies the 18.09 release notes, but isn't on `release-18.09` or `staging-18.09`. We should backport it or revert the release notes.

**Comment by Ericson2314** [comment]
This looks good. I'm going to back-port.

**Pull request merged**
