### PR TITLE
mercurial: add withPackages

### PR DESCRIPTION
**Pull request by xavierzwirtz**
###### Motivation for this change

Mercurial ships features in external packages, expecting the end user to install those packages and enable them in their config. This PR adds a `withPackages` function that builds a derivation including mercurial and the supplied packages.

[Mercurial Evolve](https://www.mercurial-scm.org/doc/evolution/) enables safe mutable history for mercurial. 

###### Things done

hg-evolve: init at 9.2.2
mercurial: add withPackages

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danbst** [comment]
is it really required to put evolve into buildInputs? Can't we just use `hg --config extensions.evolve= evolve` inside virtual env or nix-shell?

**Comment by xavierzwirtz** [comment]
Could you give me an example of doing it that way? Adding it to `propagatedBuildInputs` is how the hg-git extension was implemented before it was removed.

**Comment by danbst** [comment]
@xavierzwirtz yeah, I understand. It is definitely easier to use when it is bundled.

```
nix-build -E '
  with import ./. {}; 
  runCommand "${mercurial.name}+ext" { 
    buildInputs = [ xorg.lndir makeWrapper ]; 
  } "
  mkdir $out
  lndir ${mercurial} $out
  wrapProgram $out/bin/hg --prefix PYTHONPATH : ${pythonPackages.hg-evolve}/${python.sitePackages}
  "
'
$ ./result/bin/hg --config extensions.evolve= --help | grep evolve
 evolve        solve troubled changesets in your repository
 evolve        extends Mercurial feature related to Changeset Evolution
```
Maybe a function like `mercurial.withPackages` (similar to `python.withPackages`) would make a generic way to add any new extension packages.

**Comment by xavierzwirtz** [comment]
@danbst how's it look now? I used your code sample to implement `withPackages`.

**Comment by xavierzwirtz** [comment]
Superseded by #81158 and #81157.

**Pull request closed without merging**
