### PR TITLE
python3Packages.pygame: 2.2.0 -> 2.4.0

### PR DESCRIPTION
**Pull request by emilytrau**
###### Description of changes

Changelog [2.3.0](https://github.com/pygame/pygame/releases/tag/2.3.0)
Changelog [2.4.0](https://github.com/pygame/pygame/releases/tag/2.4.0)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by gepbird — CHANGES_REQUESTED** [review]
pygame 2.5.2 was released and merged in https://github.com/NixOS/nixpkgs/pull/271586. Is there any reason to keep 2.4.0?

2.5.2 on master fails to build, could you fix it if 2.4.0 is not needed?
<details><summary>distutils and buildconfig module not found</summary>
<pre>
Traceback (most recent call last):
  File "/build/source/buildconfig/config.py", line 207, in main
    import config_unix as CFG
  File "/build/source/buildconfig/config_unix.py", line 7, in <module>
    from distutils.sysconfig import get_python_inc
ModuleNotFoundError: No module named 'distutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/source/buildconfig/config.py", line 247, in <module>
    main()
  File "/build/source/buildconfig/config.py", line 209, in main
    import buildconfig.config_unix as CFG
ModuleNotFoundError: No module named 'buildconfig'
</pre>
</details>

**Comment by SuperSandro2000** [comment]
> Is there any reason to keep 2.4.0?

If the packages that use it, don't support 2.5. Can we all upgrade them to the newest version?



> distutils and buildconfig module not found

Distutils should only be an issue for python 3.12. Can we fix the other issue?

Also can we drop the old version of SDL2_image? That would be awesome.

**Review by MaxwellDupre — COMMENTED** [review]
Need to resolve conflicts and good idea to get latest version (2.5.2).

**Comment by wegank** [comment]
pygame is indeed at 2.5.2 on master, however. Closing.

**Pull request closed without merging**
