### PR TITLE
factorio-experimental, factorio-headless-experimental: 1.1.5 -> 1.1.6

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

https://forums.factorio.com/93072

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by priegger** [comment]
Tested on x86_64 NixOS, both headless (as NixOS service) and the desktop version. I was able to connect to the server and play a little, so it seems to be fine. Thanks!

**Review by priegger — APPROVED** [review]
I've been using this for ~10 days. Works fine, thanks for the PR!

**Review by nyanotech — APPROVED** [review]

**Comment by lukegb** [comment]
Factorio 1.1.7 is out now. Abandoning this.

**Pull request closed without merging**
