### PR TITLE
tdesktop: 2.9.3 -> 3.0.1

### PR DESCRIPTION
**Pull request by VergeDX**
###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Kranzes — APPROVED** [review]

**Comment by ilya-fedin** [comment]
tdesktop changed the method of loading gtk & webkit2gtk since 2.8.12, but I don't see any changes in the derivation, can you check whether gtk integration and webkit2gtk features are really working? gtk integration can be checked by changing gtk-decoration-layout property or by enabling auto-night mode and setting some gtk theme with `-dark` in the name. webkit2gtk can be checked with `@ShopBot` (by getting an `/invoice` and checking the Webview check, choosing payment method should open a webview window).

**Comment by VergeDX** [comment]
@ilya-fedin
webkit2gtk features not working on my 2.9.3 and @NickCao's 3.0.1 version,
but it seems there is no error log printed, Idk how to debug this yet...

**Comment by ilya-fedin** [comment]
> Idk how to debug this yet

I think you need to just specify path to the library in dlopen call with substituteInPlace

**Comment by udf** [comment]
This seems to work fine:

```diff
  postPatch = ''
    substituteInPlace Telegram/CMakeLists.txt \
      --replace '"''${TDESKTOP_LAUNCHER_BASENAME}.appdata.xml"' '"''${TDESKTOP_LAUNCHER_BASENAME}.metainfo.xml"'

    substituteInPlace Telegram/ThirdParty/libtgvoip/os/linux/AudioInputALSA.cpp \
      --replace '"libasound.so.2"' '"${alsa-lib}/lib/libasound.so.2"'
    substituteInPlace Telegram/ThirdParty/libtgvoip/os/linux/AudioOutputALSA.cpp \
      --replace '"libasound.so.2"' '"${alsa-lib}/lib/libasound.so.2"'
    substituteInPlace Telegram/ThirdParty/libtgvoip/os/linux/AudioPulse.cpp \
      --replace '"libpulse.so.0"' '"${libpulseaudio}/lib/libpulse.so.0"'
+    substituteInPlace Telegram/lib_webview/webview/platform/linux/webview_linux_webkit_gtk.cpp \
+      --replace '"libwebkit2gtk-4.0.so.37"' '"${webkitgtk}/lib/libwebkit2gtk-4.0.so.37"'
   '';

```

**Comment by VergeDX** [comment]
@udf Thanks for your contribution! Changes performed.

**Comment by Kranzes** [comment]
Is this ready to be merged?

**Review by primeos — APPROVED** [review]
The diff LGTM so let's merge it.

Btw the `libwebkit2gtk-4.0.so.37` pattern might break soon due to `.37` but `substituteInPlace` will emit a warning and it's still an improvement over the current situation. Just FYI as something to look out for and that could potentially be improved.

**Comment by ilya-fedin** [comment]
> due to `.37`

Why? :thinking:

**Pull request merged**
