### PR TITLE
dnscrypt-wrapper: remove package and NixOS modules

### PR DESCRIPTION
**Pull request by rnhmjoj**
## Description of changes

Remove dnscrypt-wrapper now that we have a properly supported solution in NixOS (dnsdist).

### CODE REVIEW

**Review by misuzu — APPROVED** [review]

**Comment by rnhmjoj** [comment]
For reference, this

```nix
services.dnsdist =
 { enable = true;
   dnscrypt.enable = true;
   dnscrypt.providerKey = "/path/to/secret.key";
   extraConfig = ''
     # DNS resolver to wrap
     newServer({address="127.0.0.1:53", name="local-bind"})
   '';
 };
```

should be equivalent to

```nix
services.dnscrypt-wrapper =
  { enable = true;
    address = "[::]";
    port = 443;
    providerKey.public = "/path/to/public.key";
    providerKey.secret = "/path/to/secret.key";
  };
```

(except that now the key rotation will be performed much faster, so
dnscrypt-proxy won't complain about insecure defaults)

**Review by SuperSandro2000 — APPROVED** [review]
Next time please don't delete the PR template

**Comment by rnhmjoj** [comment]
Ok, but there's nothing relevant for a package removal in it.

**Comment by SuperSandro2000** [comment]
Technically adding an alias can fail eval and changing the doc can fail its build. So technically that could have been tested.

**Comment by Zocker1999NET** [comment]
I do not know if opening a new issue would be more appropriate, but as this PR is just 3 weeks old:

This PR breaks *evaluating* `nixosTests.dnsdist.dnscrypt` because it removes the file `nixos/tests/dnscrypt-wrapper/secret.key`, which is still referrenced by: https://github.com/NixOS/nixpkgs/blob/6f26c88376a17aaaa37d16d360c974b9fe0049c5/nixos/tests/dnsdist.nix#L67

I discovered this by accident and have no experience with dnscrypt-wrapper & co., so without further research I cannot decide whether the key setting is no longer required or if the secret file is still required for the test.

**Comment by rnhmjoj** [comment]
Thank you! I forgot the file was being shared. IIRC the script will generate a key on the first run, so it's not a strict requirement when just testing it. I will make a PR to fix the evaluation.

**Pull request merged**
