### PR TITLE
nixos/awstats: drop module

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
The `awstats` module has never been maintained after initially added to `nixpkgs` and should be removed, or have someone take ownership of it.

ping @vcunat @griff 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by aristaeus** [comment]
I looked into setting up AWstats a few weeks ago, but after 5 minutes couldn't work out how to use this module. For example, there is no option to specify log locations - I seems like this module assumes you're only serving one website, and that website is using apache.

I was planning to roll my own solution - and have been umming and ahing about pushing it upstream. My main concern was breaking backwards compatibility - but if the alternative is removal then that probably isn't a problem.

So I'd be happy to take ownership of this and do some refactoring to make it more flexible.

**Comment by vcunat** [comment]
IIRC awstats [started](https://github.com/nixos/nixpkgs/commit/6f9fe31b4) as a prototype written for @tohl, but I suspect it's never made it to practical usage.  (And I won't be maintaining it.)

**Comment by aanderse** [comment]
@aristaeus yeah the module isn't complete, makes far too many assumptions, and only works use under fairly limited scope.

I'd love to coordinate with you if you're rewriting this, as my motivation for this PR is changes I'm making to the `httpd` module. I'll ping you in my upcoming `httpd` PR.

Thank you!

**Comment by tohl** [comment]
> prototype written for @tohl, but I suspect it's never made it to

yes, awstats can be removed

**Comment by griff** [comment]
I also never used this module since I was only interested in the mail stats functionality of awstats which this module didn't support and so I have my own local module just for that. So I would be fine with the module being removed.

**Comment by griff** [comment]
@aristaeus If you plan on also supporting mail stats or would be open to getting support for that into your new module I would love to help out with code and comments from my own hacked together module if it means I no longer have to maintain my own module.

**Comment by aristaeus** [comment]
@griff sounds good. Is your config online somewhere?

**Comment by griff** [comment]
@aristaeus it is now [mail-awstats.nix](https://gist.github.com/griff/09e7de290a83528341fddc04ed9d902b).

Please note that it is very hacky and only works for postfix and though there are options for multiple domains it only collects statistics for all the configured postfix domains combined. And if the journald log is very large the first time the hourly service is run it will be very slow because it reads the log twice.

**Comment by aanderse** [comment]
@griff thanks for providing that! @aristaeus any updates on your progress?

**Comment by aristaeus** [comment]
@aanderse Sorry, I've had a busy couple of weeks. My branch is now looking pretty respectable so I'll submit a PR now.

**Comment by aanderse** [comment]
Great, thanks!

**Pull request closed without merging**
