### PR TITLE
freecad: 0.21.2 → 1.0rc2

### LINKED ISSUE #341214: Update request: freecad 0.21.2 → 1.0RC
- Package name: FreeCAD
- Latest released version: 1.0RC
- Current version on the unstable channel: 0.21.2
- Current version on the stable/release channel: 0.21.2
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@viric  
@gebner  
@AndersonTorres

### Relevant notes

* https://blog.freecad.org/2024/09/10/the-first-release-candidate-of-freecad-1-0-is-out/
* https://wiki.freecad.org/FreeCAD_1.0_Development_Cycle
* https://github.com/FreeCAD/FreeCAD/tree/releases/FreeCAD-1-0

<details><summary><b>Expand to see list of minimum supported 3rd party library versions</b></summary>

Screenshot_20240911_120247

</details>
It is unorthodox to request an RC (moving target) build but since there is 3rd party dependency complexity the thought of 'this may be a good moment to start porting FC to 1.0' on nix is relevant. The 1.0 release still has some release blockers. Perhaps the nix build will be ready in time for the 1.0 release if efforts start now? 

Related:  
* #284524

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by srounce**
## Description of changes

Fixes #341214 

Update FreeCAD to latest 1.0 Release Candidate (includes commits for all release candidates). I've had this building for quite some time in [srounce/freecad.nix](https://github.com/srounce/freecad.nix) albeit with a slightly different slimmed down derivation. This PR ports the key changes to the existing Nixpkgs version allowing it to build 1.0RC.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by srounce** [comment]
@GrahamcOfBorg build freecad
@ofborg

**Comment by srounce** [comment]
@AndersonTorres @gebner I suspect there is some cruft in the derivation that could be removed, as there are many more dependencies than in [my freecad.nix flake](https://github.com/srounce/freecad.nix) which contains only what is needed to build plus some optional ones for the features I use. However as I don't use every single feature I'm unsure as to whether some of these dependencies are required by the features that I don't use.

**Review by kirillrdy — APPROVED** [review]
Screenshot from 2024-09-30 07-18-38

**Comment by bjornfor** [comment]
I don't like that the FreeCAD package in nixpkgs was updated from a stable release to an unstable release candidate. Why couldn't the PR be tested here until the final upstream release was made? Or at least add the "rc" version as an additional low-prio package?

What's the plan for the upcoming NixOS release? Ship a release candidate?

**Comment by bjornfor** [comment]
FreeCAD is back on a stable release now: https://github.com/NixOS/nixpkgs/pull/357360 :tada: The release branch is still on 1.0rc2 though.

**Comment by kirillrdy** [comment]
@bjornfor 1.0 has been backported to 24.11 https://github.com/NixOS/nixpkgs/pull/357967

**Comment by bjornfor** [comment]
> @bjornfor 1.0 has been backported to 24.11 #357967

Thanks!

**Pull request merged**
