### PR TITLE
fractal-next: 5.beta2 -> 5.rc1

### PR DESCRIPTION
**Pull request by blitz**
## Description of changes

This PR updates Fractal (next) to their latest release candidate. I've tested it and it seems to work fine!

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by schuelermine** [comment]
Thanks! I will test it myself when I get home (5-6h)

**Comment by adamcstephens** [comment]
This PR worked for me on x86, but version 5 has now been released.

**Comment by schuelermine** [comment]
OK, it works for me. Since Fractal 5 is now released what would you prefer?
→ Merge this, then someone writes a PR for 5
→ Skip this and write a PR for 5 immediately
→ Someone writes a patch for this for 5
→ You update this PR to go to 5

**Comment by blitz** [comment]
I would merge this and then we upgrade it to 5.

**Comment by adamcstephens** [comment]
I would prefer to see this PR updated to the final version of 5, but if @blitz does not want to do so, then someone else should open a new one.

**Comment by linsui** [comment]
https://github.com/NixOS/nixpkgs/pull/269852

**Comment by blitz** [comment]
Thanks @linsui for updating to 5! I'm currently traveling and only have a few minutes here and there, so I'm glad you took this up!

**Pull request closed without merging**
