### PR TITLE
grub2: 2.02 -> 2.04-rc1

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

update version 2.02 which is 2 years old
many fixes since then: http://git.savannah.gnu.org/gitweb/?p=grub.git;a=shortlog

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build grub2

**Comment by NeQuissimus** [comment]
Should this maybe go into staging first?

**Comment by volth** [comment]
> Should this maybe go into staging first?

It does not cause mass rebuild.

If you are about introducing a delay for testing, I could say that it is already in use by other distros (for examle Manjaro LiveCD is using a revision one commit older calling it ```2.03.5```, that last commit is only about changing the version number from 2.03 to 2.04), so we can be sure it is tested by few huderds users.

**Comment by NeQuissimus** [comment]
I've been running with this for a few days, merging it.

**Pull request merged**
