### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by hedning** [comment]
[`enchant`](https://hydra.nixos.org/build/84488057) is somehow broken by the `hunspell` upgrade (reverting fixes the build). Adding `ncurses` also fixes `enchant`, but that's probably not the correct fix (`tinfo` is nowwhere to be found with `hunspell` 1.6.2):
```
/nix/store/j13c9z0z495wxdc97if8z451x53m1j25-binutils-2.30/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
```

**Comment by hedning** [comment]
Updating enchant-1.6 fixed the issue. Pushed directly, hope that's okay.

**Comment by hedning** [comment]
There's something wrong with the tarballs: https://hydra.nixos.org/build/84759686

I'm getting the same problem when trying to build a VM.

Looks like it's connected to the default `pname` changes @Synthetica9

**Comment by Synthetica9** [comment]
@hedning https://github.com/NixOS/nixpkgs/pull/50364

**Comment by hedning** [comment]
[valgrind](https://hydra.nixos.org/build/84945477) seems to fail randomly (I've seen the same failure on staging and trunk a few times now), Tried reproducing the failure locally (with `-j 4`) a bunch of times, but haven't seen a failure yet. Should we just turn off parallel building (it's not a huge build so not a big loss)?

**Comment by Synthetica9** [comment]
I've changed the base branch of https://github.com/NixOS/nixpkgs/pull/50364 from `staging` to `staging-next`, could someone give it a merge?

**Comment by hedning** [comment]
Okay, the main thing blocking staging-next is the `version` assert problem. There's two proposed fixes:

- There's https://github.com/NixOS/nixpkgs/pull/50364 which replaces `version` with `_version` in `nixos-version`'s derivation attrs.

- @matthewbauer made https://github.com/NixOS/nixpkgs/pull/51183 to fix the problem in general with less backward compatibility breakage.

If #51183 is a massive rebuild (not sure how changes to mkDerivation works or if ofBorg picks them up) I'd say we should merge #50364 here first, and wait for the next merge window to add #51183. If it's not a massive rebuild I'd say we go for #51183 directly. Does that sound fair?

**Comment by FRidh** [comment]
I pushed 28e2277305f8c6eeee3f6f773927b956eb903a15 solving the `version` issue so we can merge this now.

**Pull request merged**
