### PR TITLE
python3Packages.zigpy: 0.33.0 -> 0.34.0, python3Packages.bellows: 0.24.0 -> 0.25.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.34.0 and 0.25.0

Change log:
- https://github.com/zigpy/zigpy/releases/tag/0.34.0
- https://github.com/zigpy/bellows/releases/tag/0.25.0

- Related Home Assistant change: https://github.com/home-assistant/core/pull/51765
- Target Home Assistant release: current (only dependency update, no code changes)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Looks like that at least one tests is super slow.

**Comment by mvnetbiz** [comment]
It looks like this breaks `test_new_device_join_and_bind_complex` in zigpy-znp. Does it ever completes tests for you? Mine has frozen a few times, and failed once.

**Comment by mvnetbiz** [comment]
I think it is probably this commit that fixes it, we should wait until zigpy-znp 0.6.0 is tagged to include in this PR. https://github.com/zigpy/zigpy-znp/commit/582cffb68fdf0c5bc14d55efca2a683222d7fed7

**Comment by fabaff** [comment]
> Does it ever completes tests for you?

Not that I recall.

**Comment by mvnetbiz** [comment]
Zigpy znp just released v0.5.2 which should fix the broken tests from this PR IIRC.

**Comment by mweinelt** [comment]
> Zigpy znp just released v0.5.2 which should fix the broken tests from this PR IIRC.

Feel free to file a PR 😄

**Comment by mvnetbiz** [comment]
Never mind, I missed that you already updated everything and fixed the failing test. :+1:

**Pull request closed without merging**
