### PR TITLE
discourse: remove phases

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
#28910

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by talyz** [comment]
This only affects the plugin builder, so the name should be changed to `discourse.mkDiscoursePlugin: remove phases` to reflect that. It also changes the behavior in case the plugin source tree contains a configure script or Makefile; to keep closer to the current one, `dontConfigure` and `dontBuild` should default to `false`.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131106` at c2a1e51a run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>discourseAllPlugins</li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

bundler is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/web-apps/discourse/default.nix:217:5:
```
    |
217 |     buildInputs = [
    |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `replace`.
Near pkgs/servers/web-apps/discourse/default.nix:4:9:
```
  |
4 | , ruby, replace, gzip, gnutar, git, cacert, util-linux, gawk
  |         ^
```
</li>
    <li>warning: unused-argument

Unused argument: `meta`.
Near pkgs/servers/web-apps/discourse/default.nix:56:7:
```
   |
56 |     , meta ? null
   |       ^
```
</li>
    <li>warning: unused-argument

Unused argument: `src`.
Near pkgs/servers/web-apps/discourse/default.nix:58:7:
```
   |
58 |     , src
   |       ^
```
</li>
  </ul>
</details>

**Comment by Stunkymonkey** [comment]
i agree to rename the commit.

but having `dontConfigure` and `dontBuild` set to true i would guess it is not wanted: https://github.com/NixOS/nixpkgs/pull/130194#issuecomment-881969030
> buildPhase is probably a no op. We should only disable it if it is causing problems.

**Comment by talyz** [comment]
They should _default_ to `false` in order to keep the current behavior. If there are configure scripts or Makefiles in the source tree, they most likely shouldn't be used, since that's not how Discourse plugins are fetched and installed, normally; if they exist, they're probably only there as a convenience to the developer and should be ignored.

**Comment by SuperSandro2000** [comment]
> They should default to false in order to keep the current behavior.

to keep the current behaviour they need to default to true so that the files are not used.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by talyz** [comment]
> to keep the current behaviour they need to default to true so that the files are not used.

Indeed, I've updated the comment.

**Review by talyz — APPROVED** [review]

**Pull request merged**
