### PR TITLE
nixos/lib/make-disk-image: Create build products metadata for hydra

### PR DESCRIPTION
**Pull request by mweinelt**
For hydra to expose built images for direct download, listing the relevant files in nix-support/hydra-build-products is required.

This could be useful to reuse our images on the LXD imageserver. https://hydra.nixos.org/build/244751553

```console
$ cat result/nix-support/hydra-build-products
file qcow2-image /nix/store/c8jila306khspz9b4qbfgxvvrvd6w7fx-nixos-disk-image/nixos.qcow2
$ file /nix/store/c8jila306khspz9b4qbfgxvvrvd6w7fx-nixos-disk-image/nixos.qcow2
/nix/store/c8jila306khspz9b4qbfgxvvrvd6w7fx-nixos-disk-image/nixos.qcow2: QEMU QCOW Image (v3), 3638558720 bytes (v3), 3638558720 bytes
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mkg20001** [comment]
Fyi I already run an LXD Image Server under images.mkg20001.io using the lxd-image-server module (config https://gist.github.com/mkg20001/342b8aef64cc2553964a3c8473fe3ee5)

Maybe you could re-use some of that

**Comment by mweinelt** [comment]
The idea is to get this into the upstream image server, so it will have better discoverability, but thanks for your offer.

**Comment by mkg20001** [comment]
Ah, ok

Very nice.

**Comment by adamcstephens** [comment]
Thanks!

**Comment by adamcstephens** [comment]
Can, should, we backport this so we can get VM images for 23.11 up?

**Comment by mweinelt** [comment]
Yeah, we probably should. I don't think it will cause regressions, but we could maybe let it sit for a few days and see what happens on master.

**Pull request merged**
