### PR TITLE
nvidia_x11_vulkan_beta: 455.46.04 -> 470.62.13

### PR DESCRIPTION
**Pull request by ckiee**
###### Motivation for this change
I want to use [`VK_EXT_video_encode_h264`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_video_encode_h264.html)!

cc @baracoder 
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
  - Too many builds (21) for local machine, tested with default `linuxPackages` and with older `linuxPackages_zen`.
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`) (**Note**: Tested on older base nixpkgs rev as my fleet is behind by a month)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by baracoder** [comment]
Builds those packages pass:
```
linuxPackages.nvidiaPackages.vulkan_beta
linuxPackages.nvidiaPackages.vulkan_beta.settings
linuxPackages.nvidiaPackages.vulkan_beta.persistenced
```
and because it Is just an update of a beta package, this should be good to merge

**Comment by Binary-Eater** [comment]
Any reason not to go to `470.62.22` with Vulkan 1.3 support? For the vulkan beta drivers, I think it makes sense to include the patch version number as well in `persistencedVersion` and `settingsVersion`, given how large the changes seem to be among patch versions.

https://developer.nvidia.com/vulkan-driver

**Comment by ckiee** [comment]
It didn't exist when I made this PR and no one seems to care about merging this, so..

**Comment by Binary-Eater** [comment]
If I could, I would after testing :joy:. I updated my response after seeing this PR was opened back in Dec. 2. Overlays are nice......

**Comment by ckiee** [comment]
Personally I just use a [branch](https://github.com/NixOS/nixpkgs/compare/master...ckiee:private) with all my random little patches :P

**Comment by Lassulus** [comment]
nix-review didn't want to build this. but tested manually building pkgs.linuxPackages.nvidia_x11_vulkan_beta on this branch rebased on master and that seemed to build

**Pull request merged**
