### PR TITLE
googleearth: remove

### PR DESCRIPTION
**Pull request by woffs**
it's broken, and even after adjusting the derivation to the currently
available downloads it does not run well for me and it is rather
annoying to adjust the derivation to the moving
google-earth-stable_current source download link

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
This is unfortunate but probably the right way to go. It might be useful in an overlay if someone is willing to maintain it. See also #30539.

/cc @peterhoeg @viric

**Review by matthewbauer — APPROVED** [review]

**Comment by peterhoeg** [comment]
I'm with you guys on this. @viric?

**Comment by matthewbauer** [comment]
One thing I forgot to mention: In general we need to get better at documenting breaking changes like this. I think this should go in rl-1809.xml. If possible it would be great, for someone to add it in as a bullet point (we will probably be looking closer at these in August and September but it's nice to get a start on them.

**Comment by woffs** [comment]
NB: it could also be fixed, I got https://gist.github.com/def74bf9ff71abae05f7dcab12cd91b5 almost running, but maintenance is the main problem I think, with the google download link which changes content and version and must be (automatically?) adapted in nix.

**Pull request merged**
