### PR TITLE
maintainers: remove endocrimes

### PR DESCRIPTION
**Pull request by endocrimes**
Please accept this letter as formal notice of my resignation from the position of "Community Member" at Determinate Systems.

Thank you for giving me the opportunity to work in this position - I have thoroughly enjoyed being frustrated and saddened whenever interacting with the DetSys community. However, I've decided it is time for me to move on to another community that will hopefully be less tolerant of willful hate and sexism.

~Danielle

---

This PR should not be merged before the [board statement](https://discourse.nixos.org/t/board-reviewing-open-items/44095/12?u=endocrimes), where it should hopefully be clearer whether the community really is the collective of like-minded individuals that I thought it was.

### CODE REVIEW

**Review by MostAwesomeDude — APPROVED** [review]

**Review by Xe — APPROVED** [review]

**Comment by ryantm** [comment]
oops, sorry I didn't read that you didn't want this merged.

**Comment by ryantm** [comment]
https://github.com/NixOS/nixpkgs/pull/307119

**Comment by ryantm** [comment]
Okay, I reverted it in that other PR. I'm very sorry, I should have read it more closely.

**Comment by ryantm** [comment]
Let me know if you want me to remake your PR @endocrimes, I feel bad that I closed it and ruined your work.

**Pull request merged**
