### PR TITLE
perlPackages.mod_perl2: fix build on perl-5.34.0, add nixos test

### PR DESCRIPTION
**Pull request by stigtsp**
###### Motivation for this change

#133751

Fixes build problem of `perlPackages.mod_perl2` and `apacheHttpdPackages.mod_perl` on perl-5.34.0, also added nixos test for mod_perl.

- The same mod_perl source is used by `perlPackages.mod_perl2` and `apacheHttpdPackages.mod_perl`, so have applied same patch.
- ~TODO: Needs to be tested.~ Tests written
 
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sternenseemann — APPROVED** [review]
Builds for me, apache with mod_perl seems to work as well.

**Comment by stigtsp** [comment]
@GrahamcOfBorg perlPackages.mod_perl2 perl532Packages.mod_perl2
@GrahamcOfBorg apacheHttpdPackages.mod_perl

**Comment by stigtsp** [comment]
@GrahamcOfBorg perlPackages.mod_perl2 perl532Packages.mod_perl2
@GrahamcOfBorg apacheHttpdPackages.mod_perl

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 133768` at c4095d0e run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built successfully:</summary>
  <ul>
    <li>perl532Packages.GoferTransporthttp</li>
    <li>perl532Packages.libapreq2</li>
    <li>perl532Packages.mod_perl2</li>
    <li>perl534Packages.GoferTransporthttp</li>
    <li>perl534Packages.libapreq2</li>
    <li>perl534Packages.mod_perl2</li>
  </ul>
</details>

**Comment by stigtsp** [comment]
@GrahamcOfBorg test mod_perl

**Comment by stigtsp** [comment]
@GrahamcOfBorg test mod_perl

**Comment by sternenseemann** [comment]
I'd suggest adding `nixosTests.mod_perl` to `passthru.tests` for `perl.pkgs.mod_perl2` and `apacheHttpdPackages.mod_perl`, so the test will be executed by @ofborg CI automatically when someone touches mod_perl2 directly (also should increase discoverability since nixos tests are often overlooked).

**Review by sternenseemann — APPROVED** [review]

**Comment by zakame** [comment]
Result of `nixpkgs-review pr 133768` run on Slackware x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_perl (apacheHttpdPackages_2_4.mod_perl)</li>
    <li>perl532Packages.GoferTransporthttp</li>
    <li>perl532Packages.libapreq2</li>
    <li>perl532Packages.mod_perl2</li>
    <li>perl534Packages.GoferTransporthttp</li>
    <li>perl534Packages.libapreq2</li>
    <li>perl534Packages.mod_perl2</li>
  </ul>
</details>

**Review by zakame — APPROVED** [review]

**Pull request merged**
