### PR TITLE
geoip: set default dir to '/var/lib/geoip-databases'

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Set the default directory to '/var/lib/geoip-databases', the default directory of [geoip-updater](https://github.com/NixOS/nixpkgs/blob/d4e5bb34b76c98adee1d7fc00440adeb6a2a8c13/nixos/modules/services/misc/geoip-updater.nix#L209) service.

It might be not the perfect choice, but
 * current default directory is ```${geoip}/share/GeoIP``` which is in read-only nix store, it has no files nor possibility to put them in.
 * some software just [use the default](https://github.com/varnish/libvmod-geoip/blob/843c02e/src/vmod_geoip.c#L34) and do not allow to customize the geoip directory

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
Won't this (now) clash with the geoipDatabase handling in postInstall? I think perhaps this path should be an argument to the derivation.

**Comment by volth** [comment]
@bjornfor maybe like this? https://github.com/NixOS/nixpkgs/pull/27412/commits/04de1eda1f36c8de48abf091839a47b371cd3e6a

**Comment by bjornfor** [comment]
@volth: No, that's not what I had in mind. I was hoping for a derivation argument, like the existing "geoipDatabase". Even better if the two can be one. So "geoipDatabase" could default to "/var/lib/geoip-databases", but could also be set to a derivation providing databases (like the geoipWithDatabase package does with geolite-legacy).

**Comment by volth** [comment]
@bjornfor I do not see how they could be united into one option, current ```geoipDatabase``` is a build-time option, the source location of database to copy in into nix store (and keep read-only and not updatable), while the new option would be a run-time writable directory.

If ```geoipDatabase``` would default to "/var/lib/geoip-databases", that means at build time, the current version of updateble database would be copied to the nix store (perhaps even with temporary files if if happens to overlap the update process) thus making the ```geoip``` derivation not deterministic.

**Comment by Mic92** [comment]
not if you put it in quotes `"/var/lib/geoip-databases"` vs `/var/lib/geoip-databases`

**Comment by volth** [comment]
@Mic92 sorry, [not "copy", but "symlink"](https://github.com/volth/nixpkgs/blob/04de1eda1f36c8de48abf091839a47b371cd3e6a/pkgs/development/libraries/geoip/default.nix#L20
)
```nix
  postInstall = ''
    DB=${toString geoipDatabase}
    if [ -n "$DB" ]; then
      ln -s $DB/share/GeoIP $out/share/GeoIP
    fi
  '';
```
if ```geoipDatabase``` would be "/var/lib/geoip-databases", ```${geoip}/share/GeoIP``` would be a silly symlink from nix store to "/var/lib/geoip-databases/share/GeoIP"

**Comment by volth** [comment]
if you really wants is as param.... https://github.com/NixOS/nixpkgs/pull/27412/commits/0f2f779f4ada890629c25a8ec4355eeee2de31fc

**Comment by Mic92** [comment]
I think this parameter does not provide additional value. @bjornfor actually I don't why it clashes in the first place. `/var/lib/geoip-databases` was only used, if no database file was passed to this package.

**Comment by volth** [comment]
@Mic92: I think I got the @bjornfor idea: https://github.com/NixOS/nixpkgs/compare/master...be71e3895d171df5656e96dc448350e0248a5e04

**Comment by volth** [comment]
@bjornfor does current PR match your idea?

**Comment by bjornfor** [comment]
Yes.

**Comment by volth** [comment]
Let's merge?

**Comment by bjornfor** [comment]
Applied to master (8b4f5376ff1f1ad6898febe99941bd9a4c890f6b).

**Pull request closed without merging**
