### PR TITLE
python3Packages.ecos: 2.0.7.post1 -> 2.0.8

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 2.0.8

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129028` at db23ef64 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/6ff9afe2e582b387fa41788f40c90447">python38Packages.cvxpy</a></li>
    <li><a href="https://gist.github.com/6b4a0b0c0af88028f444c0f984e54d17">python38Packages.qiskit</a></li>
    <li><a href="https://gist.github.com/41be92be1cc46bf21f2fbe5e33bc5556">python38Packages.qiskit-aer</a></li>
    <li><a href="https://gist.github.com/434c61216e34a3ffad01ca8062f5e7a7">python38Packages.qiskit-aqua</a></li>
    <li><a href="https://gist.github.com/fde3e2ed02db43b5729554d2e2c0499b">python38Packages.qiskit-ibmq-provider</a></li>
    <li><a href="https://gist.github.com/b9a4e3887f81f46b452ea362c01f0c20">python38Packages.qiskit-ignis</a></li>
    <li><a href="https://gist.github.com/7a771a1cbcdcc48412a8505eee0f14d7">python39Packages.cvxpy</a></li>
    <li><a href="https://gist.github.com/7691bf1c440ef9cad947476a33091f79">python39Packages.qiskit</a></li>
    <li><a href="https://gist.github.com/2284530088723894361820146198bceb">python39Packages.qiskit-aer</a></li>
    <li><a href="https://gist.github.com/ffe02474dc03563a0149c6c99f3dd237">python39Packages.qiskit-aqua</a></li>
    <li><a href="https://gist.github.com/2a3c4a5998b50db62bd28ba17320e123">python39Packages.qiskit-ibmq-provider</a></li>
    <li><a href="https://gist.github.com/2dbae126b8844c7ec4e245387bdb59c7">python39Packages.qiskit-ignis</a></li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.ecos</li>
    <li>python39Packages.ecos</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by drewrisinger — APPROVED** [review]
* [x] Diff LGTM
* [x] Commits LGTM
* [x] Build of the package itself succeeds, but downstream packages fail due to ``python3Packages.cvxpy`` test failure (also broken on master)

**Comment by risicle** [comment]
@drewrisinger _is_ `cvxpy` broken on master? Hydra seems happy with it and it builds (on master) locally for me.

Same failure with this PR though.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 129028` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
14 packages built:
</summary>
<ul>
<li>python38Packages.cvxpy</li>
<li>python38Packages.ecos</li>
<li>python38Packages.qiskit</li>
<li>python38Packages.qiskit-aer</li>
<li>python38Packages.qiskit-aqua</li>
<li>python38Packages.qiskit-ibmq-provider</li>
<li>python38Packages.qiskit-ignis</li>
<li>python39Packages.cvxpy</li>
<li>python39Packages.ecos</li>
<li>python39Packages.qiskit</li>
<li>python39Packages.qiskit-aer</li>
<li>python39Packages.qiskit-aqua</li>
<li>python39Packages.qiskit-ibmq-provider</li>
<li>python39Packages.qiskit-ignis</li>
</ul>
</details>

**Pull request merged**
