### PR TITLE
DO NOT MERGE: testing to see if we got assimilated

### PR DESCRIPTION
**Pull request by copumpkin**
Are we the borg?

### CODE REVIEW

**Comment by copumpkin** [comment]
Bump

**Comment by copumpkin** [comment]
Resistance is futile.

**Comment by grahamc** [comment]
bump

**Comment by ahstro** [comment]
I am *super* curious; what is this about?

**Comment by 7c6f434c** [comment]
This is all robo-meta: this PR is about reactions of a bot to this PR.

(Note that the labels were applied by a bot)

**Comment by vyp** [comment]
what is its purpose

**Comment by 7c6f434c** [comment]
Assimilating PRs?

It looks like it can do test builds in some way that is saner than what
TravisCI does, and it seems to be able to label reverse-dependency set
size. Eventually, in the happy bright future it will probably merge by
approval from non-committer package maintainers, but I don't know.

**Comment by copumpkin** [comment]
Yeah, the bot can auto-label PRs with the size of the rebuilds they cause, but can also run builds on demand to alleviate some maintainer work. Hoping to cut down on the pending PRs which has really skyrocketed recently.

**Comment by NeQuissimus** [comment]
This is my new favourite PR :)

Nixpkgs has much room to grow

Borg Baby

**Comment by dtzWill** [comment]
@grahamc is it too late to name your bot [Locutus](http://memory-alpha.wikia.com/wiki/Locutus_of_Borg)? :laughing:

**Comment by grahamc** [comment]
Indeed: https://github.com/locutus and also grahamcofborg will likely retire at some point, to make room for a new borg master...

**Comment by NeQuissimus** [comment]
NixOS Queen ? :D

**Pull request closed without merging**
