### PR TITLE
haskellPackages: update dhall and related packages

### PR DESCRIPTION
**Pull request by sorki**
Tested x86 builds of
- dhall-bash
- dhall-json
- dhall-yaml
- dhall-nix
- dhall-nixpkgs
- dhall-lsp-server
- dhall-openapi

### CODE REVIEW

**Comment by maralorn** [comment]
Excellent! <3

**Comment by maralorn** [comment]
Oh, wait. You manually updated the stackage.yaml. That will get overwritten by our next bump. But because that will be the update to LTS-22, this is an acceptable solution in this case. Just note that we will probably need some kind of fix again then.

**Comment by sorki** [comment]
> Oh, wait. You manually updated the stackage.yaml. That will get overwritten by our next bump. But because that will be the update to LTS-22, this is an acceptable solution in this case. Just note that we will probably need some kind of fix again then.

Good to know! What's the proper way to do that?

**Comment by maralorn** [comment]
Well, it depends. We can make an exception for dhall to exclude it from the stackage list generally. Then we need to modify the regex in the stackage update shell script. Or we do it via manual overrides with _x_y_z attributes in configuration-common.nix

**Pull request merged**
