### PR TITLE
thunderbird, thunderbird-bin: 52.8.0 -> 52.9.0 [Critical security fixes]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Critical security fixes
- Other fixes
https://www.thunderbird.net/en-US/thunderbird/52.9.0/releasenotes/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by coretemp** [comment]
This can be merged as is, but it would be useful if you could introduce a variable with the version, such that size of the diff for the next time this changes is cut in about half. 

I.e. 

```
let thunderbird_version = "52.9.0"; in 
<rest of code>
``` 

(The version should be specified at most once in the whole file.)

**Comment by vcunat** [comment]
@GrahamcOfBorg build thunderbird

**Review by vcunat — APPROVED** [review]
Tested `thunderbird` atop 18.03 for about a day; no regressions.

**Comment by taku0** [comment]
@coretemp sorry for missing your reply. I will fix it at the next update.

**Pull request merged**
