### PR TITLE
Treewide Nix reformat pass 1 [skip treewide]

### PR DESCRIPTION
**Pull request by infinisil**
This is the next step towards accepted NixOS/rfcs#166 after #322512 and #326407, see also https://github.com/NixOS/nixpkgs/issues/322520 and https://github.com/NixOS/nixfmt/issues/153 :tada:.

After final improvements to the official formatter implementation, this commit now performs the first treewide reformat of Nix files using it. This is part of the implementation of NixOS/rfcs#166.

Only "inactive" files are reformatted, meaning only files that aren't being touched by any PR with activity in the past 2 months. This is to avoid conflicts for PRs that might soon be merged. Later we can do a full treewide reformat to get the rest, which should not cause as many conflicts.
    
A CI check has already been running for some time to ensure that new and already-formatted files are formatted, so the files being reformatted here should also stay formatted.

The @NixOS/nix-formatting will approve/merge this PR.

### Verification

The reformatting commit is fully auto-generated by the code in https://github.com/infinisil/treewide-nixpkgs-reformat-script, see the commit message on how to do a complete verification.

## Things done
- [x] Merge and propagate latest nixfmt improvements and fixes
  - [x] Update nixfmt: https://github.com/NixOS/nixpkgs/pull/361875
  - [x] Update the CI-pinned Nixpkgs (master): https://github.com/NixOS/nixpkgs/pull/363585
- [x] Fully automate generation and verification of the formatting commit.
  - [x] Check that `nix-instantiate --parse` doesn't change (add `--arg check true` to the verification build to do that, takes a bunch longer)
- [x] Confirm that there are (almost) no rebuilds (See https://github.com/NixOS/nixpkgs/issues/301014)
  - Can be done separately, non-blocking in https://github.com/NixOS/nixpkgs/pull/326430
- [x] Make a Discourse post: https://discourse.nixos.org/t/nix-formatting-team-treewide-nixpkgs-formatting/56666
- [x] Prepare the same PR for release and staging branches, so that they can be merged at the same time. This ensures that there aren't any problems when backporting PRs or merging staging
  - https://github.com/NixOS/nixpkgs/pull/327796
    - Depends on https://github.com/NixOS/nixpkgs/pull/364004
  - https://github.com/NixOS/nixpkgs/pull/363995
  - https://github.com/NixOS/nixpkgs/pull/363999
  - https://github.com/NixOS/nixpkgs/pull/364000

---

This work is sponsored by [Antithesis](https://antithesis.com/) :sparkles:

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by oxalica** [comment]
I'd say we should block on https://github.com/NixOS/nixfmt/issues/153. There are also many issues about either awkward formatting result or implementation correctness. It's no good to race reformatting everything before that.

> This was done with this script in ~40 seconds

This sounds too long to me. If the whole-repo checking takes too long, it blocks auto-checking in git commit hook.
`fd -e nix --exec-batch nixfmt` takes 1:49.27 (~110s) on my machine and nixfmt is single-threaded. `nixfmt --check` on formatted files takes almost the same time.

**Comment by infinisil** [comment]
@oxalica The reason I'm pushing for this is because there's a lot of churn from people reformatting individual parts on their own, @mweinelt can attest to that. Let's not let perfect be the enemy of good, the formatter works and is unlikely to change drastically. We should definitely block on correctness bugs like https://github.com/NixOS/nixfmt/issues/197 though, this is being worked on :)

Regarding the time it takes for a full format, the solution I'd propose is to use a pre-commit hook that only formats files that were changed. This also nicely aligns with CI only requiring changed files to be formatted. I'd be okay with blocking on that for this PR, I'll add it to the TODO items.

In addition to that, if CI fails, it shows the `nixfmt` command needed to make CI pass, only listing the files that need reformatting, see [here](https://github.com/tweag/nixpkgs/actions/runs/9671086737/job/26681017292).

<details><summary>Alternative: treefmt</summary>

One could also imagine using [treefmt](https://github.com/numtide/treefmt) because it caches results, but this will be slightly problematic when we change the formatter in the future and need to do the same multi-pass approach to avoid merge conflicts. There's going to be times when not the entire codebase is formatted in the same way, and treefmt would mess that up.
</details>

**Comment by oxalica** [comment]
> use a pre-commit hook that only formats files that were changed

That's kinda non-trivial to me, and you need to retrieve file list from `git log` on an unknown number of commits. Would be good to have an example (maybe in README) for copy-paste.

Also I opened https://github.com/NixOS/nixfmt/issues/211 for tracking this.

**Comment by infinisil** [comment]
> That's kinda non-trivial to me, and you need to retrieve file list from `git log` on an unknown number of commits. Would be good to have an example (maybe in README) for copy-paste.

Since it's the pre-commit hook, we only have to worry about the single commit that is being made, so I don't think it will be bad, but I'll see it when I try :laughing:. And we can use a `shellHook` automatically pre-commit hooks upon entering the shell, e.g. https://github.com/cachix/git-hooks.nix also works in that way.

**Comment by Aleksanaa** [comment]
> I'd say we should block on https://github.com/NixOS/nixfmt/issues/153. There are also many issues about either awkward formatting result or implementation correctness. It's no good to race reformatting everything before that.

The good thing here is we can skip formatting if something weird really happens, because it doesn't make subsequent CI check fail.

**Comment by emilazy** [comment]
I’d like to recommend a `pre-push` hook instead of a `pre-commit` one. It would still check all the commits that are to be pushed. The advantage is that it is easier to slice and dice existing commits and make imperfect work‐in‐progress commits to clean up later without having the formatting step get in the way. It also prevents making committing any slower, whereas pushes are already slow. For me, the experience of using a `pre-commit` hook is like having to satisfy a pedantic spell‐checker while trying to get into a flow state writing a stream‐of‐consciousness draft.

Another advantage is that tools like [`git-revise`](https://github.com/mystor/git-revise) cannot necessarily run hooks due to their in‐memory design, which wouldn’t affect a `pre-push` hook; it’s more reliable to do the checks at the actual publication bottleneck.

If you need any help writing an efficient and correct Git hook for this, please ping me.

**Comment by infinisil** [comment]
To make this PR easier to review, I split off the enforcement for new files into https://github.com/NixOS/nixpkgs/pull/326407. So this PR is only for the treewide format now! Also note:
- I added instructions to the [PR description](https://github.com/NixOS/nixpkgs/pull/322537#issue-2373969216) on how the entire contents of this PR can be reproduced, allowing anybody to easily check it
- Some nixfmt fixes should be merged and propagated before this is merged, see the PR description

**Comment by Scrumplex** [comment]
From what I can tell, the treewide reformat script does not take autogenerated files like the ones from nuget2nix into account. As discussed in #325053 formatting these using nixfmt-rfc-style results in a drastic increase in size, while serving little to no purpose.

I think we should standardize on some marker for autogenerated files, at least within Nixpkgs. Alternatively we might want to move away from generated Nix files and rely on JSON/TOML instead.

Related https://github.com/NixOS/nixfmt/issues/91

**Comment by emilazy** [comment]
I think moving from autogenerated Nix files to JSON is a very good idea for multiple reasons (it tends to also improve eval performance as parsing JSON is much faster than parsing Nix). I think that rather than building a complex exclusions system we should take the nudge as an opportunity to move more of what is essentially data into data formats. Code generators that aren’t ready to migrate can add `nixfmt` to their pipelines.

**Comment by PerchunPak** [comment]
> the treewide reformat script does not take autogenerated files like the ones from nuget2nix into account

From https://discourse.nixos.org/t/nix-formatting-team-treewide-nixpkgs-formatting/56666:

> This PR will format all files without recent (specifically, files that are touched by a PR with activity in the last ~2 months) activity to minimise merge conflicts on active PRs.

---

> I think we should standardize on some marker for autogenerated files, at least within Nixpkgs. Alternatively we might want to move away from generated Nix files and rely on JSON/TOML instead.

I saw, some use `@generated` on the first line of a file ([example](https://github.com/python-poetry/poetry/blob/b7cd0b04160df33f7c3a033910520a3078cc3508/poetry.lock#L1)). But you should move to JSON/TOML as it makes parsing generated code easier and faster (JSON parser is faster than Nix parser).

See also https://github.com/NixOS/rfcs/pull/109, https://discourse.nixos.org/t/new-rfc-draft-standardize-updater-scripts-successor-of-rfc-109

**Comment by Atemu** [comment]
The commit message currently assumes that the reader knows what all of this is about. It should probably explain what all of this even is or at least leave breadcrumbs before going into the details of how the reformat was done for historical reference for people looking at it in the git log.

**Comment by liberodark** [comment]
Thank you for your work.

**Comment by infinisil** [comment]
Other than the indirect dependency on https://github.com/NixOS/nixpkgs/pull/364004, this is now ready, along with the backports/staging-versions https://github.com/NixOS/nixpkgs/pull/327796, https://github.com/NixOS/nixpkgs/pull/363995, https://github.com/NixOS/nixpkgs/pull/363999 and https://github.com/NixOS/nixpkgs/pull/364000!

I have a script that can regenerate the commits for all of these PRs fairly quickly, which I'll do whenever a conflict appears.

We have a merge party for this scheduled in 25 minutes in [this Jitsi room](https://meet.zrh.init7.net/nix-formatting), anybody is free to join! :tada:

**Review by adamcstephens — APPROVED** [review]

**Comment by infinisil** [comment]
I walked through the methodology of this work with ~12 people in the merge party call, no complaints, merging! :tada:

**Comment by infinisil** [comment]
Turns out the "reformat everything on master/staging/staging-next together" approach didn't quite work out: master couldn't be automatically merged into staging-next anymore (same for staging-next into staging). Thanks to @wegank for taking care of fixing that by manually doing the staging merge!

**Comment by mightyiam** [comment]
Thanks to the works of inspired, motivated and provided individuals, we can has nice things! Thanks, everyone involved!

**Comment by mightyiam** [comment]
Hey, does anyone want to be a guest on the Full Time Nix podcast and have a long conversation about the process that brought us this PR?

**Comment by trofi** [comment]
I have about 350 local patches against `nixpkgs`. Most of them are conflicting now. Is there a standard way to automatically rebase most of them with formatting applied? Or I'll have to hack up something locally?

**Comment by arianvp** [comment]
There's this which might help: https://github.com/NixOS/nixpkgs/pull/363759

**Comment by Pandapip1** [comment]
> I have about 350 local patches against `nixpkgs`. Most of them are conflicting now. Is there a standard way to automatically rebase most of them with formatting applied? Or I'll have to hack up something locally?

If these are generally applicable PRs, can I suggest that they be sent to nixpkgs? This could have been avoided that way:

> Only "inactive" files are reformatted, meaning only files that aren't being touched by any PR with activity in the past 2 months. This is to avoid conflicts for PRs that might soon be merged. Later we can do a full treewide reformat to get the rest, which should not cause as many conflicts.

**Comment by oxij** [comment]
`git filter-branch` is too slooooow for casual small rebases.

A much simpler way to do merges and rebase after this PR is to use my `nixfmt-mergetool` script for `nixfmt` at https://github.com/NixOS/nixfmt/pull/277

To quote from there:

```
usage: nixfmt-mergetool LOCAL BASE REMOTE MERGED

A `git-mergetool`-compatible merge tool that uses `nixfmt` to merge more
stuff.

This tool rejects all non-`.nix` files, for `.nix` files it simply

- calls `nixfmt` on its first three inputs, followed by
- running `git merge-file` on the same inputs, followed by
- running `nixfmt` on the result.

Put the following to your `~/.gitconfig`:

[mergetool "nixfmt"]
    cmd = nixfmt-mergetool "$LOCAL" "$BASE" "$REMOTE" "$MERGED"
    trustExitCode = true

Then, when `git merge` or `git rebase` fails, run

git mergetool -t nixfmt .
# or, only for some specific files
git mergetool -t nixfmt FILE1 FILE2 FILE3

and some `.nix` files will probably get merged automagically.

Note that files that `git` merges successfully even before `git mergetool`
will be ignored by `git mergetool`.

If you don't like the result, run

git restore --merge .
# or, only for some specific files
git restore --merge FILE1 FILE2 FILE3

to return back to the unmerged state.
```

**Comment by infinisil** [comment]
I'm now working on the full reformat here https://github.com/NixOS/nixpkgs/pull/380990

@oxij Thanks, that's neat! While I think with your script you can end up with issues like https://github.com/NixOS/nixpkgs/pull/363759#discussion_r1876952316, it doesn't hurt to have more possibilities. I've added it to the PRs checklist to consider incorporating it :D

**Pull request merged**
