### PR TITLE
tmatrix: init at 1.0

### PR DESCRIPTION
**Pull request by infinisil**
###### Motivation for this change
Because it's really cool. Nice package, @M4444!

test

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested execution of all binary files (usually in `./result/bin/`)
---

### CODE REVIEW

**Review by ryantm — APPROVED** [review]

**Comment by M4444** [comment]
@Infinisil Thanks for adding this! If you don't mind, I would like to add you to the acknowledgements.
What command does a user need to run to install this package on NixOS?

**Comment by Infinisil** [comment]
@M4444 It will take some time until the package is built and available in the official channels, but after that, `nix-env -f channel:nixpkgs-unstable -iA tmatrix` should work.

**Comment by M4444** [comment]
Ok. Is there a way to follow this somewhere and know when it's out so I know when to add the command to the project description?

**Comment by Infinisil** [comment]
I wish there was! Currently the best I know of is watching nixpkgs-unstable in  http://howoldis.herokuapp.com/ and once it updates, check whether the commit there contains tmatrix. I'll put a comment here when I notice it updated.

**Comment by M4444** [comment]
Got it, thanks.

**Comment by Infinisil** [comment]
@M4444 The channel just updated, `nix-env -f channel:nixpkgs-unstable -iA tmatrix` can now be used to install tmatrix for Nix / on NixOS :)

**Comment by M4444** [comment]
Thanks for the notification! Added the command project description.

**Comment by M4444** [comment]
Just wanted to mention that that CMake now also installs the man page, and the newly added shell completion scripts.

**Comment by M4444** [comment]
Now that the package is in the official channel would it be enough to use `nix-env -iA tmatrix` or `nix-env -i tmatrix` to install it?

**Comment by Infinisil** [comment]
Yup! Though it's `nix-env -iA nixos.tmatrix` on NixOS and `nix-env -iA nixpkgs.tmatrix` on non-NixOS. What works on all Nix systems is `nix-env -f '<nixpkgs>' -iA tmatrix` though.

**Comment by M4444** [comment]
Got it, thanks!

**Pull request merged**
