### PR TITLE
stage-1: create temporary secrets directory in /tmp and not in cwd

### PR DESCRIPTION
**Pull request by h0m1**
###### Motivation for this change

nixos-rebuild boot/switch fails when executed from /nix/store and config.boot.initrd.secrets are used. Its because it creates a directory in the current working directory. 

Fix for [73404](https://github.com/NixOS/nixpkgs/issues/73404)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
cc @mic92 @samueldr

**Comment by antifuchs** [comment]
still important to me

**Review by 0x4A6F — APPROVED** [review]
Deployed systems (x86_64-linux) with `nixos-rebuild`, `krops` and `deploy-rs` with this change successfully.

**Comment by szlend** [comment]
I also tested this change with `deploy-rs`. Is there any chance of backporting this to 20.09? It seems like a pretty inconsequential fix to backport.

**Comment by tolbrino** [comment]
:+1: This fix would indeed be useful.

**Comment by tolbrino** [comment]
:+1:

**Pull request merged**
