### PR TITLE
fetch*: print a trace warning about md5 deprecation

### PR DESCRIPTION
**Pull request by 7c6f434c**
###### Motivation for this change

The issue #4491 seeks to avoid usage of MD5 as a checksum inside NixPkgs.

This change adds a warning to all `fetch*` functions currently capable of processing md5.

In the process, I found `fetchfile` that was unable to handle SHA-256. This is now fixed.
###### Things done
- Tested `test-eval-release.sh` — seems fine.
- A random package (for the record: `libnfnetlink`) affected by the warnings prints a warning but doesn't get a new hash (as intended), i.e. gets fetched from the binary cache.
###### # PR status

This is a small patch that has global and (intentionally) annoying effects.

I think it is fine (given nobody currently objects to removal of MD5 use from NixPkgs), and I intend to merge it myself next week. If there are some suggestions or objections, I will delay the merge (or fix small things before merging)

Cc @domenkozar as the MD5-removal leader

### CODE REVIEW

**Comment by copumpkin** [comment]
Can you use `lib.warn` instead of `builtins.trace`? Otherwise, 👍

**Review by sternenseemann — COMMENTED** [review]
This is a lot of duplicated code. Is there any good way to abstract over the problem to minimize code duplication? Also I think this will be a pain with `nix-env -qa`

**Comment by 7c6f434c** [comment]
Oh, we have `lib.warn`. OK, refactored the string splicing into `lib.fetchMD5warn` using `lib.warn`

`nix-env -qa` seems to print only one warning, the rest is inside non-recursed attrsets.

**Comment by globin** [comment]
Fixed that one occurence to not clutter up nix-env, thanks for pushing this! :+1:

**Comment by 7c6f434c** [comment]
There goes my plan of collecting objections over the weekend.

**Comment by domenkozar** [comment]
@globin @7c6f434c nixpkgs is now blocked due to all md5 packages: http://hydra.nixos.org/build/41815250/nixlog/1/raw

**Comment by 7c6f434c** [comment]
>@globin @7c6f434c nixpkgs is now blocked due to all md5 packages: http://hydra.nixos.org/build/41815250/nixlog/1/raw

Hydra blocks on warnings? That's news to me… Does it block on all 
traces? I have just replaced `lib.warn` with `lib.info` to check.

**Comment by 7c6f434c** [comment]
How interesting. Apparently, `lib` is imported multiple times across NixPkgs (independently in `stdenv`s for different platofrms), so switching off the warning via config would lead to a huge mess.

Hopefully just grepping out the specific warnings will work fine.

**Comment by vcunat** [comment]
Notif.: reverted in e3a873479.

**Comment by copumpkin** [comment]
@edolstra it would be nice if you didn't just sweep in and undo work without talking to people about it. End users who track master should expect some amount of unusual behavior (including warnings) while we work out the kinks, but unanimously killing something without any sort of communication (or underlying urgency) just kills others' drive to contribute to the project.

**Pull request merged**
