### PR TITLE
libupnp: 1.6.20 -> 1.6.21

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

I'm not super familiar with sourceforge, I hope this is not a temporary url.

/cc @grahamc

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bachp** [comment]
Wouldn't it be better to fetch via git? I think that is supported by nix?

**Comment by LnL7** [comment]
That will pull in the entire history, we generally prefer an url. But I can switch if this doesn't work properly.

**Comment by copumpkin** [comment]
Fetching with git is far slower than fetching prebundled archives, since it's `O(all of repo history)` rather `O(requested revision)`. Having said that, I don't know if the sourceforge link is stable so we might be stuck with it.

**Comment by LnL7** [comment]
The sha in the url does match the commit of the `release-1.6.21` tag  [07c03d]

**Comment by grahamc** [comment]
Looks like it might be available via github: https://github.com/mrjimenez/pupnp/issues/14

**Comment by grahamc** [comment]
Graham Christensen <notifications@github.com> writes:

I've merged this in to my roundup-14 branch, to be merged soon.

**Comment by grahamc** [comment]
Thank you!

**Pull request closed without merging**
