### PR TITLE
linux_3_10: 3.10.96 -> 3.10.97

### PR DESCRIPTION
**Pull request by NeQuissimus**
What is the wizardry needed to build 3.10? Neither the previous 3.10.96 nor the new 3.10.97 build for me.

I just get a whole lot of `Error in reading or end of file`

This should be ok, I want to see if Travis has the same errors I am getting.

### CODE REVIEW

**Comment by vcunat** [comment]
I reproduce the problem and so does Hydra: http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.linux_3_10.x86_64-linux

**Comment by vcunat** [comment]
It actually started failing even on 15.09, without bumping the verison: http://hydra.nixos.org/job/nixos/release-15.09/nixpkgs.linux_3_10.x86_64-linux

**Comment by NeQuissimus** [comment]
I found the problem but have absolutely no idea how to fix it:

```
GOT: Prompt: PCI Express Hotplug driver
GOT:   Location:
GOT:     -> Bus options (PCI etc.)
GOT:       -> PCI support (PCI [=y])
GOT:         -> PCI Express support (PCIEPORTBUS [=y])
GOT:   Defined at drivers/pci/pcie/Kconfig:16
GOT:   Depends on: HOTPLUG_PCI [=m] && PCIEPORTBUS [=y]
GOT: 
GOT: 
GOT: 
QUESTION:     PCI Express Hotplug driver, NAME: HOTPLUG_PCI_PCIE, ALTS: M/n/?, ANSWER: y
repeated question:     PCI Express Hotplug driver at /nix/store/xzqksq6iiwd213x77zik4pw3smahn85g-generate-config.pl line 80.

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.
```

We answer "y" but that is not a valid answer to the question. It seems that this will then cause the issue.
Props actually go to this 2011 nix-dev thread:
http://lists.science.uu.nl/pipermail/nix-dev/2011-August/006519.html

**Comment by dezgeg** [comment]
Possibly something like this, although bit hacky: (I have this in our internal nixpkgs fork at work)

````
diff --git a/pkgs/os-specific/linux/kernel/common-config.nix b/pkgs/os-specific/linux/kernel/common-config.nix
index fc54715..701f9a8 100644
--- a/pkgs/os-specific/linux/kernel/common-config.nix
+++ b/pkgs/os-specific/linux/kernel/common-config.nix
@@ -362,7 +362,7 @@ with stdenv.lib;
   X86_MCE y
 
   # PCI-Expresscard hotplug support
-  HOTPLUG_PCI_PCIE y
+  ${optionalString (versionAtLeast version "3.12") "HOTPLUG_PCI_PCIE y"}
 
   # Linux containers.
   NAMESPACES? y #  Required by 'unshare' used by 'nixos-install'
````

**Comment by vcunat** [comment]
Look, @dezgeg just committed a nice work around ;-)

**Pull request closed without merging**
