### PR TITLE
keepassx{,2}: drop

### PR DESCRIPTION
**Pull request by winterqt**
###### Description of changes

Upstream has officially abandoned the project as of 2021 [0], there's been no release since 2016, it uses the EoL Qt 4, and alternatives like KeePassXC exist.

[0]: https://www.keepassx.org/index.html%3Fp=636.html

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
Drafting until I get a chance to fix the eval error.

**Comment by ajs124** [comment]
Looks like you accidentally deleted `pkgs/applications/misc/keepassx/community.nix`, hence the eval error.

Also, it looks like like your change to the `aliases.nix` isn't sorted alphabetically.

See https://github.com/NixOS/nixpkgs/pull/174634/commits/9f29abc007892dc923e1c7893bb219bf7a870721 for a similar change.

**Comment by winterqt** [comment]
Thanks @ajs124, should be good now.

Should I squash the two commits, does it make sense to have separate commits for them?

**Comment by ajs124** [comment]
You seem to have forgotten to add the new directory. That or I'm misreading the diff.

I don't really have an opinion on squashing these, tbh.

**Pull request merged**
