### PR TITLE
citrix_workspace: 23.02.0 -> 23.07.0

### PR DESCRIPTION
**Pull request by michaeladler**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by pmenke-de — APPROVED** [review]
Looks good to me. Can't test it though, as I don't have access to any citrix server anymore.

**Review by Janik-Haag — COMMENTED** [review]
@pmenke-de if you aren't able to test the package anymore and I guess aren't using it you should probably remove your self from the maintainers list.

**Comment by michaeladler** [comment]
Updated (and tested successfully) to 23.07. I'd suggest to merge this since the current download urls are invalid (expired) and at least one user has already contacted me directly regarding this problem.

**Comment by Janik-Haag** [comment]
Result of `nixpkgs-review pr 235593` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>citrix_workspace</li>
    <li>citrix_workspace_23_02_0</li>
  </ul>
</details>

**Comment by Janik-Haag** [comment]
Yes that's why ofborg and nixpkgs-review fail. I started the run in the background and had to leave for a while that's why I didn't answer. Would you consider adding your self as a maintainer?

**Comment by michaeladler** [comment]
I already am :) See https://github.com/NixOS/nixpkgs/commit/8235de6d5c9ef0d904a9fc8c20e017fd7db7092b

**Comment by Janik-Haag** [comment]
ah sorry missed that.

**Comment by michaeladler** [comment]
@Janik-Haag Thanks!

**Pull request merged**
