### PR TITLE
pipenv: add back wrapper

### PR DESCRIPTION
**Pull request by FRidh**
Turns out that when creating a virtualenv, it ignores what has been injected
into `sys.path` with the magical sed expression. Also, `NIX_PYTHONPATH` is
not used.

Likely a subprocess is invoked in which case both are no longer visible.
That's the reason `PYTHONPATH` needs to be used.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @kaali

### CODE REVIEW

**Comment by Kaali** [comment]
I tested this and now we get `ModuleNotFoundError: No module named 'pip._internal.main'` error again (related to #71178). But it does fix the missing `virtualenv` in #71771

**Comment by FRidh** [comment]
Let me guess, you are using `nix-shell`?

**Comment by Kaali** [comment]
> Let me guess, you are using `nix-shell`?

No. I'm installing `pipenv` in my system configuration.

To repeat you can try this `Pipfile`:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
spacy = "~=2.1"

[requires]
python_version = "3.7"
```

One without any dependencies works fine.

**Comment by FRidh** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/71800.

**Pull request closed without merging**
