### PR TITLE
nixos/video: remove obsolete ati modules

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Address: https://github.com/NixOS/nixpkgs/commit/29c7d3c40a167720783641af2f3512506e1b868a#commitcomment-51127009

follow up to: #123602
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123904` at a33648bc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by jonringer** [comment]
first `nixpkgs-review` failed, but running it again passed?

```
https://github.com/NixOS/nixpkgs/pull/123904

1 package blacklisted:
tests.nixos-functions.nixos-test

1 package built:
nixos-install-tools
```

**Review by rnhmjoj — CHANGES_REQUESTED** [review]
This needs to me mentioned in the release notes. Otherwise looks good.

**Comment by jonringer** [comment]
@rnhmjoj added, thanks for review :)

**Review by rnhmjoj — APPROVED** [review]

**Pull request merged**
