### PR TITLE
caddy: Omit `--adapter` from invocations if `null` supplied

### PR DESCRIPTION
**Pull request by dwf**
###### Motivation for this change
Allows specification of Caddy configs in the native JSON format, which allows access to the full range of features without need of any config adapter. The empty string seemed like a natural choice, as the desired behaviour is achieved by omitting the `--adapter` argument.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
We could use null here instead of the empty string. I have to say I don't have a strong opinion either way.

I don't see any problem with the change. Leaving a couple of days for other people to comment.

Feel free to ping me again in case this is forgotten.
Thank you for your contribution!

**Comment by dwf** [comment]
Thanks for the quick review! Happy to go with `null` if that's the convention and/or consensus. I'm on the new side to Nix, so perfectly willing to defer to others on this.

One possibility I'd like some feedback on is then changing the default to `null`. This would preserve existing behaviour with regard to `config`, because we write out a file called `Caddyfile` which would then be interpreted as such. This matches the ergonomics of the underlying package better, I think (only explicitly applying a config adapter if you specify an `--adapter` argument, otherwise deciding between `caddyfile` and JSON based on the filename).

cc @jdheyburn

**Comment by happysalada** [comment]
A warm welcome to the community!

It feels to me null would be more natural, however, I don't have strong feelings, curious what others think about it.

Regarding changing the default, I would probably do it in 2 steps, first merge this PR, then let different test the potentially breaking change (of changing the default).

There are more active people on caddy, I think this should get more attention once holidays are over.

**Comment by jdheyburn** [comment]
Thanks for tagging me!

Since the goal here is to allow for JSON configs to be used, then I think we should omit `--adapter` altogether when `caddyfile` is the adapter since that is the implied adapter to use when one is not specified. Not sure if any other caddy-ers would like to weigh their opinion on this.

IMO I would prefer the default value be `null` (I prefer that syntax), and only specify `--adapter` if the user did. But I agree with the above that this change in particular should be staged, if that is something we want to do. 

> (only explicitly applying a config adapter if you specify an --adapter argument, otherwise deciding between caddyfile and JSON based on the filename).

I like this, Caddy already knows how to parse Caddyfile and JSON configs without explicitly defining adapter - let's keep to that.

**Comment by dwf** [comment]
> I think we should omit --adapter altogether when caddyfile is the adapter since that is the implied adapter to use when one is not specified.

Hmm, not sure I agree with you on that one. IMO it seems a bit surprising to specify a non-null value for `adapter` and not have it used at invocation time, and my read is that the behaviour isn't "use `caddyfile` when none is specified" but "use `caddyfile` when none is specified _and_ the config filename starts with `Caddyfile`.

One other thing that occurred to me (but clearly not in scope for this PR) is that it would be nice if `config` allowed you to in-line JSON, particularly since you can then use `builtins.toJSON` to define it as a nix expression without the user needing to explicitly write to disk. I think the right way to do this would be to 

1. change the filename written by nix to something neutral that does not start with `Caddyfile` (so that it isn't parsed as a Caddyfile by default if `adapter` is null)
2. change the code to accept either `"caddyfile"` or `null` adapters in conjunction with `config`.

Changing the default `adapter` to `null` would then be a breaking change for anyone in-lining a Caddyfile-formatted config as `config`, and probably isn't worth it, but could be considered separately.

**Comment by jdheyburn** [comment]
> Hmm, not sure I agree with you on that one. IMO it seems a bit surprising to specify a non-null value for adapter and not have it used at invocation time

Is a fair point. However when we think about what `--adapter caddyfile` is actually doing under the hood, is the default implied behaviour when it is omitted. I'm not married to it though,  I do agree that if the user specifies something then that's what they should get back. Ultimately I'm not a fan of adapter being defined by default if its not required to run.

> , and my read is that the behaviour isn't "use caddyfile when none is specified" but "use caddyfile when none is specified and the config filename starts with Caddyfile".

I know its existing logic but I'm not a fan of the dependence on filename starting with Caddyfile, but that's a trivial conversation for another time.

**Comment by happysalada** [comment]
@aanderse do you have an opinion on this PR by any chance ?

**Comment by aanderse** [comment]
After reading the [documentation](https://caddyserver.com/docs/config-adapters), reviewing the conversation in this thread, and trying to recall what happened with my initial tests I believe this is what we're all looking for: https://github.com/NixOS/nixpkgs/commit/7556fd748a0ecfa311710aa2a0f07b9ad94a76dc

Note: untested, quickly whipped up in ~5 minutes

**Comment by dwf** [comment]
I finally had a chance to have a closer look at @aanderse's commit, thanks for adding `null` support. My only suggestion would be to write to a file basename other than `Caddyfile` when accepting `config`, and making the `caddy fmt` conditional on `adapter` being set to `caddyfile`; as right now `adapter = null` plus `config` is needlessly restricted to supplying Caddyfile syntax. I'll try and figure that out now.

**Comment by dwf** [comment]
To put it more clearly: I am suggesting that `adapter = null` and `config != null` should imply `config` is treated as JSON by Caddy.

On its own, this would simply add functionality. Changing the default adapter to `null` on top of this would break user configurations where `adapter` is not explicitly specified.

Maybe this is fine: this is an unstable branch, after all. But it would merit a mention in the release notes for 22.05 at least.

**Comment by aanderse** [comment]
I was under the impression that if the filename of the config file is `Caddyfile` then the file is parsed as `caddyfile`. Is that incorrect?

**Comment by dwf** [comment]
Right, I'm saying that if we name the written file something else, like "caddy-config", the user then has the option of _either_
* `null` to parse `config` as JSON,
* `caddyfile` to force Caddyfile syntax evaluation.

This seems strictly better than writing out a file called `Caddyfile`, and then having both `null` and `caddyfile` settings causing `config` being parsed as Caddyfile syntax (and erroring if the user instead supplied JSON).

**Comment by dwf** [comment]
Ack, sorry, I think I confused myself by habitually referring to the stable docs. I see now that the current derivation generates a bunch of Caddyfile syntax, and allows the user to _append_ to that with `extraConfig`. So it's not terribly feasible to just accept JSON there too.

I think your change looks good then, although the documentation of what happens in the `configFile` vs. generated config scenarios could be a bit clearer. I can take a stab at that now.

**Comment by aanderse** [comment]
Awesome!

> I can take a stab at that now.

Greatly appreciated 🙇

**Comment by Sohalt** [comment]
Any updates on this? The changes as implemented by @aanderse in https://github.com/NixOS/nixpkgs/commit/7556fd748a0ecfa311710aa2a0f07b9ad94a76dc lgtm.
Would be nice to get this merged to get JSON working at all.
Afterwards we can think about migrating the current nixos options to use JSON to allow for https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md

**Comment by jdheyburn** [comment]
@Sohalt It's still pending review from the reviewers.

I managed to do config via Nix attributes to then convert to JSON via the below. The source is below too.

- https://github.com/jdheyburn/nixos-configs/blob/main/modules/caddy/default.nix#L118-L150
- https://github.com/NixOS/nixpkgs/issues/153142#issuecomment-1144021283

**Comment by dwf** [comment]
I've incorporated the changes in 7556fd748a0ecfa311710aa2a0f07b9ad94a76dc and rebased against current `master` but haven't actually tested it. Sorry for letting this drop.

**Comment by dwf** [comment]
@aanderse @happysalada @m1cr0man  Anything more needed to get this one over the finish line?

**Comment by happysalada** [comment]
This looks good to me, but I'm a little sleep deprived, so small caveat.

**Pull request merged**
