### PR TITLE
ranger: 1.9.3-unstable-2023-08-23 -> 1.9.4, update script, tag in src, rm with lib

### PR DESCRIPTION
**Pull request by lucasew**
Closes: https://github.com/NixOS/nixpkgs/pull/367654
- **ranger: pin to a version, remove with lib, add update script**
- **ranger: 1.9.3-unstable-2023-08-23 -> 1.9.4**

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12518533828
**Extra args**: ``

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow finished

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12518533828


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368588`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>ranger</li>
    <li>ranger.dist</li>
    <li>vimPlugins.ranger-nvim</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368588`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>ranger</li>
    <li>ranger.dist</li>
    <li>vimPlugins.ranger-nvim</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368588`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>ranger</li>
    <li>ranger.dist</li>
    <li>vimPlugins.ranger-nvim</li>
  </ul>
</details>

**Review by toonn — APPROVED** [review]
LGTM

Don't want to be a maintainer for the package, perchance?

**Review by thiagokokada — APPROVED** [review]

**Comment by lucasew** [comment]
> LGTM
> 
> Don't want to be a maintainer for the package, perchance?

I think it would be very little work. If upstream doesn't mess up with FHS stuff, that depending of the package it's very hard to not to, it would be a very smooth sailing from now on.

r-ryantm sends the PR, you merge using the bot

**Comment by 9ary** [comment]
Sorry for the delayed response, but I've just received this change with 25.05.

This (hopefully unintentionally) undoes #280143, and is a breaking downgrade (ranger crashes on startup with my config because it's now missing sixel support, and I'm sure other things might be broken if other people were relying on the newer version previously packaged here).

1.9.4 was tagged off of the stable branch, which hadn't received any commits since 2019. There is only one meaningful commit in this release, while the previous pin is a snapshot of master, 720 commits ahead of 1.9.3:
- https://github.com/ranger/ranger/compare/v1.9.3...v1.9.4
- https://github.com/ranger/ranger/compare/v1.9.3...38bb8901004b75a407ffee4b9e176bc0a436cb15

The master branch is now over 800 commits ahead of stable as of this writing.

Considering @toonn (in their capacity as upstream) had [previously approved](https://github.com/NixOS/nixpkgs/pull/280143#pullrequestreview-1919587858) of packaging a snapshot of master here, I believe we should revert this downgrade (and preferably backport that to 25.05, to match 24.11), then update unstable to the latest commit.

**Pull request merged**
