### PR TITLE
ydotool: refactor ; nixos/ydotool: init module & nixosTest

### LINKED ISSUE #183659: Add programs.ydotool.enable config option to run required ydotoold daemon
### Describe the bug
`ydotool` requires `ydotoold` to be running in order to be used otherwise it aborts and crashes (see https://github.com/ReimuNotMoe/ydotool/issues/153#issuecomment-1126316333). It would make sense to have a NixOS configuration option in order to automatically configure `ydotoold` to run.

### Steps To Reproduce
```console
$ lldb ydotool type 'This is a test.'
(lldb) target create "ydotool"
Current executable set to 'ydotool' (x86_64).
(lldb) settings set -- target.run-args  "type" "This is a test."
(lldb) process launch
Process 1660480 launched: '/nix/store/p7ibf7viqwhp63szy4jxqba9njf19yf7-ydotool-1.0.1/bin/ydotool' (x86_64)
failed to connect socket: Connection refused
Process 1660480 stopped
* thread #1, name = 'ydotool', stop reason = signal SIGABRT
    frame #0: 0x00007ffff7e4cc1f libc.so.6`__pthread_kill_implementation + 239
libc.so.6`__pthread_kill_implementation:
->  0x7ffff7e4cc1f <+239>: mov    ebp, eax
    0x7ffff7e4cc21 <+241>: neg    ebp
    0x7ffff7e4cc23 <+243>: cmp    eax, 0xfffff000
    0x7ffff7e4cc28 <+248>: mov    eax, 0x0
(lldb) thread backtrace
* thread #1, name = 'ydotool', stop reason = signal SIGABRT
  * frame #0: 0x00007ffff7e4cc1f libc.so.6`__pthread_kill_implementation + 239
    frame #1: 0x00007ffff7e02042 libc.so.6`raise + 18
    frame #2: 0x00007ffff7ded49c libc.so.6`abort + 194
    frame #3: 0x000000000040143c ydotool`main + 636
    frame #4: 0x00007ffff7dee237 libc.so.6`__libc_start_call_main + 103
    frame #5: 0x00007ffff7dee2f5 libc.so.6`__libc_start_main@@GLIBC_2.34 + 133
    frame #6: 0x0000000000401471 ydotool`_start + 33
(lldb)
```

### Expected behavior
Some NixOS module option (perhaps `programs.ydotool.enable`) that automatically configures and runs `ydotool` as a systemd service in the background.

### Notify maintainers
@WilliButz @kraem

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.10, NixOS, 22.11 (Raccoon), 22.11.20220619.0d68d7c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.0pre20220620_16c6c6c`
 - nixpkgs: `/nix/store/1njdlszpc3bchdcwk45c3ndb0nfmwqcr-source`
```

### PR DESCRIPTION
**Pull request by quantenzitrone**
## Description of changes

closes https://github.com/NixOS/nixpkgs/issues/183659

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by OPNA2608** [comment]
Supersedes https://github.com/NixOS/nixpkgs/pull/191911
Closes https://github.com/NixOS/nixpkgs/issues/183659

**Comment by quantenzitrone** [comment]
oh man i should've looked before

**Review by OPNA2608 — COMMENTED** [review]
I would love to get this in, because it'll allow for mouse control in Wayland tests. I've tried this out for Lomiri, and it lets me test some keyboard-unreachable elements.

I really don't feel qualified to judge the correctness of all those service settings however…

**Comment by quantenzitrone** [comment]
@alois31 you added the systemd hardening options on my rimgo module pr so you seem to know some stuff, do you want to review the hardening on this module?

**Comment by quantenzitrone** [comment]
> I really don't feel qualified to judge the correctness of all those service settings however…

TBH I just slapped every hardening option that `systemd-analyze security` suggested on there and checked if ydotool still works. A lot of `nixos-rebuild test` and reading the `systemd.exec` manpage.

**Comment by OPNA2608** [comment]
Maybe a VM test could be written to verify that the module works as expected? Just loading up a VM or app, using the tool to click on something and verifying via console output / pgrep / OCR that something actually happened.

**Comment by quantenzitrone** [comment]
I have not written a VM test yet, so I will have to read a bit of docs first, but it seems like a good idea.

**Comment by quantenzitrone** [comment]
@OPNA2608 do you have an idea how i could check ydotools keypresses reliably?
i tried using showkey, but the output is unreliable and random.

**Comment by quantenzitrone** [comment]
oh wait you think i should do something in a graphical environment?

**Comment by OPNA2608** [comment]
For example yeah (sorry, typo'd earlier). Like using ydotool to click on a starter menu and checking with OCR if any of its contents are  Or just a tty session, sending the inputs for `touch somefile\n` via ydotool and waiting for the file to appear. But I think mouse usage would be more useful in the case of VM tests.

**Comment by alois31** [comment]
> @alois31 you added the systemd hardening options on my rimgo module pr so you seem to know some stuff, do you want to review the hardening on this module?

I used the same approach as you did here, and I'm not familiar with ydotool, so I don't think I can be of any help.

**Comment by quantenzitrone** [comment]
another idea i had was directly `cat`ing the output of `/dev/input/event<number>` and comparing the output to a previously recorded version of that output, but no luck, the output does not seem to be reprodible

**Comment by OPNA2608** [comment]
I was thinking something like this:

<details>
  <summary>Test file</summary>

```nix
import ./make-test-python.nix ({ pkgs, lib, ... }: let
  textInput = "This works.";
in {
  name = "ydotool";

  meta = {
    maintainers = with lib.maintainers; [ OPNA2608 quantenzitrone ];
  };

  nodes = {
    headless = { config, ... }: {
      imports = [
        ./common/user-account.nix
      ];

      users.users.alice.extraGroups = [ "ydotool" ];

      programs.ydotool.enable = true;

      services.getty.autologinUser = "alice";
    };

    x11 = { config, ... }: {
      imports = [
        ./common/user-account.nix
        ./common/auto.nix
        ./common/x11.nix
      ];

      users.users.alice.extraGroups = [ "ydotool" ];

      programs.ydotool.enable = true;

      test-support.displayManager.auto = {
        enable = true;
        user = "alice";
      };

      services.xserver.windowManager.dwm.enable = true;
      services.displayManager.defaultSession = lib.mkForce "none+dwm";

      environment = {
        etc."gui-text".text = textInput;
        systemPackages = with pkgs; [ gnome.zenity ];
      };
    };

    wayland = { config, ... }: {
      imports = [
        ./common/user-account.nix
        ./common/auto.nix
        ./common/x11.nix
      ];

      users.users.alice.extraGroups = [ "ydotool" ];

      programs.ydotool.enable = true;

      test-support.displayManager.auto = {
        enable = true;
        user = "alice";
      };

      programs.miriway.enable = true;
      services.displayManager.defaultSession = lib.mkForce "miriway";

      environment = {
        etc."gui-text".text = textInput;
        systemPackages = with pkgs; [ gnome.zenity ];
      };
    };
  };

  enableOCR = true;

  testScript = { nodes, ... }: ''
    def as_user(cmd: str):
      """
      Return a shell command for running a shell command as a specific user.
      """
      return f"sudo -u alice -i {cmd}"

    def ask_for_input():
      """
      Return a command to spawn a window that asks for input. The input will be sent to /tmp/output.
      """
      return as_user("zenity --entry --text 'Enter input:' > /tmp/output &")

    start_all()

    # Headless
    headless.wait_for_unit("multi-user.target")
    headless.wait_for_text("alice")
    headless.succeed(as_user("ydotool type 'echo ${textInput} > /tmp/output'")) # text input
    headless.succeed(as_user("ydotool key 28:1 28:0")) # text input
    headless.screenshot("headless_input")
    headless.wait_for_file("/tmp/output")
    headless.wait_until_succeeds("grep '${textInput}' /tmp/output") # text input

    # X11
    x11.wait_for_x()
    x11.execute(ask_for_input())
    x11.wait_for_text("Enter input")
    x11.succeed(as_user("ydotool type -f /etc/gui-text")) # text input
    x11.screenshot("x11_input")
    x11.succeed(as_user("ydotool mousemove -a 400 110")) # mouse input
    x11.succeed(as_user("ydotool click 0xC0")) # mouse input
    x11.wait_for_file("/tmp/output")
    x11.wait_until_succeeds("grep '${textInput}' /tmp/output") # text input

    # Wayland
    wayland.wait_for_x()
    wayland.execute(ask_for_input())
    wayland.wait_for_text("Enter input")
    wayland.succeed(as_user("ydotool type -f /etc/gui-text")) # text input
    wayland.screenshot("wayland_input")
    wayland.succeed(as_user("ydotool mousemove -a 350 200")) # mouse input
    wayland.succeed(as_user("ydotool click 0xC0")) # mouse input
    wayland.wait_for_file("/tmp/output")
    wayland.wait_until_succeeds("grep '${textInput}' /tmp/output") # text input
  '';
})

```

</details>

This tests keyboard functionality on terminal, X11 & Wayland, and mouse functionality on X11 & Wayland.

**Comment by OPNA2608** [comment]
@quantenzitrone Bump on the test situation/question, plus there's a changelog merge conflict that needs to be resolved.

**Comment by OPNA2608** [comment]
No problem!

> I didn't want to build miriway (which apparently is not in the binary cache even tho I always rebase my PRs to `nixos-unstable` instead of `master`)

A major dependency of it is currently broken by staging fallout: https://github.com/NixOS/nixpkgs/pull/310091

> I changed the wayland test to use cage

A kiosk-like compositor like that cage seems like a better fit anyway, so it's fine.

**Comment by OPNA2608** [comment]
Using the `cage` test setup doesn't seem to work on aarch64-linux, confirmed on my hardware:
```
wayland: starting vm
mke2fs 1.47.0 (5-Feb-2023)
qemu-system-aarch64: Virtio VGA not available
[hangs indefinitely]
```

Seems to fail on this setting:
https://github.com/NixOS/nixpkgs/blob/01b405c59d6eba8ecd1b6d02b4558b6a2e8437ee/nixos/tests/common/wayland-cage.nix#L10-L12

You could try messing with overriding this setting in the test (I don't know why it's there, maybe it's not needed anymore?), or setting up `cage` without that module.

**Review by OPNA2608 — APPROVED** [review]
Still don't know what all those service settings do, but if systemd thinks it's good & the service still works fine in the VM test, then it can't be *completely* wrong. LGTM.

**Comment by quantenzitrone** [comment]
I mean, if you want to understand the options, you could read the relevant parts of the [systemd.exec(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html)  and [systemd.resource-contro(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html) man pages. 
`systemd-analyze security ydotoold.service` also gives a short explanation for every option that is taken into consideration for the security score.

**Comment by OPNA2608** [comment]
(Merge conflict on release notes again)

**Comment by quantenzitrone** [comment]
(i forgor that i have to `git fetch` before `git rebase`ing)

**Review by OPNA2608 — APPROVED** [review]
(Added a finishing dot to the release notes entry myself, for consistency with the other entries. Just so we don't need another back n forth for such a nit)

**Pull request merged**
