### PR TITLE
cups-toshiba-estudio: fix homepage

### PR DESCRIPTION
**Pull request by alexeymuranov**
Provide an URL that works.

###### Motivation for this change

The URL in `homepage` attribute does not work.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by alexeymuranov** [comment]
By the way, the current version in Nixpkgs is 7.89, while the latest available is 7.94 (2018-08-02).  I do not know how to test it, so i am not going to make a PR for that.

**Comment by jpotier** [comment]
Well, I don't have that printer around anymore. So testing is going to be difficult. I could just up the version and hope it's ok, at the risk of breaking something that works.

**Comment by alexeymuranov** [comment]
@jpotier  I could try to test with e-studio3005AC if you give me detailed instructions.  I am not really familiar with CUPS or nixpkgs, I am just a user of NixOS stable.

**Comment by jpotier** [comment]
Well, I don't have that printer around anymore. So testing is going to be difficult. I could just up the version and hope it's ok, at the risk of breaking something that works.

**Pull request merged**
