### PR TITLE
git: 2.10.1 -> 2.10.2

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Update

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Should this go staging then first?

**Comment by NeQuissimus** [comment]
@grahamc is doing a mass rebuild in #20466, we could just merge this at the same time, save ourselves one giant build cycle?!

**Comment by grahamc** [comment]
Is this actually mass rebuild? All the fetchgits are fixed output. I can put it in my rollup branch, but only want to do that if it is being backported, too. It doesn't seem to have changes demanding backporting.

How about when I merge my rollup, I merge this one?

**Comment by NeQuissimus** [comment]
I thought `git` was always a mass rebuild, maybe I am wrong...

**Comment by FRidh** [comment]
It was a mass rebuild for a short time, see https://github.com/NixOS/nixpkgs/commit/07d12fbef1c59bcd9077de9d2606e7fa811bd93d.

**Comment by grahamc** [comment]
nox shows ti would only rebuild the following (few) things:

```
Building in /tmp/nox-review-ukrk245e: python35Packages.ramlfications nix-exec idea.pycharm-community idea.ruby-mine7 ntopng python27Packages.av rustPlatform.rustRegistry nix-prefetch-hg python35Packages.av heatseeker openmodelica idea.idea-community hydra habitat-sh cabal2nix awesome gitAndTools.git-annex buildkite-agent idea.idea14-community python27Packages.nxt-python gitAndTools.gitSVN python35Packages.pelican qt57.qtwebengine python27Packages.pytest-shutil xprintidle-ng buildbot gitAndTools.gitFull ios-cross-compile rustc python27Packages.git-up gnuradio pfixtools gitAndTools.tig gnuradio-with-packages rabbitvcs python35Packages.pytest-virtualenv python27Packages.klaus pass python35Packages.pytest-shutil rustfmt loc python27Packages.pelican idea.ruby-mine gnuradio-ais vimPlugins.pluginnames2nix idea.idea15-ultimate python27Packages.pyutil python27Packages.setuptoolsTrial megaglest cvs_fast_export buildbot-worker bup idea.ruby-mine8 gnuradio-osmosdr python27Packages.limnoria gitlab python27Packages.pytest-server-fixtures idea.webstorm rustracer python27Packages.ramlfications gnuradio-rds rkt nox python27Packages.setuptools-git hhvm libceph ceph gitAndTools.darcsToGit mercurialFull python27Packages.rpkg python27Packages.hg-git ripgrep dotnetPackages.GitVersionTree inspectrum gibo idea.phpstorm idea.idea-ultimate camlistore cfdyndns go2nix python27Packages.github-cli tvheadend python35Packages.setuptools-git libbladeRF habitat vulkan-loader src rainicorn reposurgeon r10k idea.clion git-cola idea.clion1 qtpass xtitle utox gitAndTools.transcrypt python27Packages.zfec samba4Full buildbot-ui python35Packages.pytest-server-fixtures nix-prefetch-scripts rustracerd gitlab-workhorse bareos gitAndTools.svn2git purple-facebook rofi-pass python27Packages.fedpkg buildbot-full gitMinimal python27Packages.powerline luakit simavr git mercurial gqrx python35Packages.limnoria pbrt python35Packages.powerline git-latexdiff tortoisehg android-studio python27Packages.pytest-virtualenv tahoelafs dolphinEmuMaster idea.webstorm11 snabb idea.pycharm-professional cargo factor-lang idea.webstorm10 matrix-synapse kde4.calligra gitAndTools.git-remote-hg gnuradio-nacl gnuradio-gsm nix-prefetch-git python35Packages.git-up vimPlugins.YouCompleteMe cide gitAndTools.gitFastExport pijul python35Packages.setuptoolsTrial mergerfs gitolite opengrok qgroundcontrol bundix qt5.qtwebengine idea.idea14-ultimate gitAndTools.diff-so-fancy idea.phpstorm10 python27Packages.dulwich gitAndTools.stgit python35Packages.github-cli altcoins.ethabi```

**Comment by NeQuissimus** [comment]
Right, IMO that is a lot. I guess not enough for our definition of "mass" :D
Then let's just merge it...

**Pull request merged**
