### PR TITLE
stork: 1.3.0 -> 1.4.0

### PR DESCRIPTION
**Pull request by chuahou**
###### Motivation for this change

Update to latest release [v1.4.0](https://github.com/jameslittle230/stork/releases/tag/v1.4.0).

Tested:
- `stork build`
- `stork search`
- Running on static site with `stork.js` + `stork.wasm`

<details><summary>Run results</summary>

```
$ ../nixpkgs/result/bin/stork build --input stork/config.toml --output stork/index.st
Success: Index built successfully, wrote 485,403 bytes.
Index stats:
  - 50 entries
  - 9,792 search terms
  - 9,708 bytes per entry
  - 49 bytes per search term

$ ../nixpkgs/result/bin/stork search --index stork/index.st --query beta | head
{
  "results": [
    {
      "entry": {
        "url": "https://chuahou.dev/miso/uni/lc/notes/theories.html",
        "title": "LC, Equational Theories",
        "fields": {}
      },
      "excerpts": [
        {
```

</details>

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
Looks like there is a regression on darwin, can you try to fix the build by adding `darwin.apple_sdk.frameworks.Security` to `buildInputs` (see #143864 as an example, and ofborg will show what is missing if the build is still failing), or disable the darwin build?

**Comment by chuahou** [comment]
@bobby285271 I tried adding it to see what ofborg says. Can't test the Darwin build myself, unfortunately, but the Linux build remains the same.

**Comment by bobby285271** [comment]
https://gist.github.com/GrahamcOfBorg/cbcef5e910b752693cf81f11f2b5691f:

> value is a set while a list was expected

Changing `lib.optionals` to `lib.optional` should fix this. I just try to build this via GitHub Actions: https://github.com/bobby285271/nixpkgs-test/runs/5015640321 And the next failure is:

```
error: linking with `/nix/store/hbjq4yw2w739zhvmdzxv0him6c1xjcjc-clang-wrapper-11.1.0/bin/cc` failed: exit status: 1
  |
  = note: "/nix/store/hbjq4yw2w739zhvmdzxv0him6c1xjcjc-clang-wrapper-11.1.0/bin/cc" "-m64" "-arch" "x86_64" "/private/tmp/nix-build-stork-1.4.0.drv-0/source/target/x86_64-apple-darwin/release/deps/stork-b355b04067a11372.stork.9ec2b307-cgu.0.rcgu.o" "-L" "/private/tmp/nix-build-stork-1.4.0.drv-0/source/target/x86_64-apple-darwin/release/deps" "-L" "/private/tmp/nix-build-stork-1.4.0.drv-0/source/target/release/deps" "-L" "/nix/store/48kk76b0jh8gywrnp14r4nlnil52zvcl-rustc-1.57.0/lib/rustlib/x86_64-apple-darwin/lib" "/nix/store/48kk76b0jh8gywrnp14r4nlnil52zvcl-rustc-1.57.0/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-8fcd115ffa1f34e1.rlib" "-framework" "Security" "-framework" "CoreFoundation" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/nix/store/48kk76b0jh8gywrnp14r4nlnil52zvcl-rustc-1.57.0/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/private/tmp/nix-build-stork-1.4.0.drv-0/source/target/x86_64-apple-darwin/release/deps/stork-b355b04067a11372" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: Undefined symbols for architecture x86_64:
            "_SecTrustEvaluateWithError", referenced from:
                security_framework::trust::SecTrust::evaluate_with_error::h31ec7f025f278d0d in stork-b355b04067a11372.stork.9ec2b307-cgu.0.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have no idea how to fix this as I am also not darwin user :-(

**Comment by chuahou** [comment]
Thanks for testing and reporting the next failure! Unfortunately, looks like we'll have to wait for someone who knows what they're doing with Darwin to come along. In the meantime I'll rollback to before the addition of `Security` to `buildInputs`.

**Comment by ArsenArsen** [comment]
may I request a bump on this? I have a project that relies on stork, so this would be useful

**Comment by chuahou** [comment]
@bobby285271 you previously mentioned possibly disabling the Darwin build, do you think we should do that? That would make any Darwin users after the merge be unable to use this package, right?

Alternatively, do you know anyone who might know what to do to fix this for Darwin we can ping?

**Comment by c0bw3b** [comment]
Ping @NixOS/darwin-maintainers > can someone build this on x64 Darwin?
It needs the `Security` framework at least, possibly more.

**Comment by prusnak** [comment]
The following change fixes the build for `aarch64-darwin`:

``` patch
diff --git a/pkgs/applications/misc/stork/default.nix b/pkgs/applications/misc/stork/default.nix
index b8486fc02bb..52699dfd61e 100644
--- a/pkgs/applications/misc/stork/default.nix
+++ b/pkgs/applications/misc/stork/default.nix
@@ -3,6 +3,8 @@
 , fetchFromGitHub
 , openssl
 , pkg-config
+, stdenv
+, darwin
 }:
 
 rustPlatform.buildRustPackage rec {
@@ -20,7 +22,8 @@ rustPlatform.buildRustPackage rec {
 
   nativeBuildInputs = [ pkg-config ];
 
-  buildInputs = [ openssl ];
+  buildInputs = [ openssl ]
+    ++ lib.optionals stdenv.isDarwin [ darwin.apple_sdk.frameworks.Security ];
 
   meta = with lib; {
     description = "Impossibly fast web search, made for static sites";
```

I am afraid it is not possible to fix the package for x86_64-darwin because the SDK there is stuck on very old version, so let's just use this:

``` patch
diff --git a/pkgs/applications/misc/stork/default.nix b/pkgs/applications/misc/stork/default.nix
index 52699dfd61e..a78ec507f39 100644
--- a/pkgs/applications/misc/stork/default.nix
+++ b/pkgs/applications/misc/stork/default.nix
@@ -30,5 +30,10 @@ rustPlatform.buildRustPackage rec {
     homepage = "https://github.com/jameslittle230/stork";
     license = with licenses; [ asl20 ];
     maintainers = with maintainers; [ chuahou ];
+    # TODO: Remove once nixpkgs uses newer macOS SDK for x86_64-darwin
+    #  note: Undefined symbols for architecture x86_64:
+    #  "_SecTrustEvaluateWithError", referenced from:
+    #  security_framework::trust::SecTrust::evaluate_with_error::he55858ee51118073 in stork-5ae035d54d316055.stork.c9a39ac7-cgu.0.rcgu.o
+    broken = stdenv.isDarwin && stdenv.isx86_64;
   };
 }
```

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 157416` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>stork</li>
  </ul>
</details>

**Comment by siraben** [comment]
@chuahou please apply the patch suggested by @prusnak, the Security framework needs to be imported.

**Comment by chuahou** [comment]
@prusnak @siraben, thank you very much for your help. I've applied the patches to the branch. Please let me know if it will be preferable to squash the commits or rearrange them in any way.

**Review by prusnak — APPROVED** [review]

**Review by c0bw3b — APPROVED** [review]
Result of `nixpkgs-review pr 157416` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stork</li>
  </ul>
</details>

Builds and runs

**Pull request merged**
