### PR TITLE
dontmerge: stdenv: test regression on staging

### PR DESCRIPTION
**Pull request by wegank**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build stdenv

**Comment by wegank** [comment]
@ofborg build stdenv

**Review by ghost — CHANGES_REQUESTED** [review]
The title of this commit is wrong; I don't see any of my commits in here.

**Comment by wegank** [comment]
> The title of this commit is wrong; I don't see any of my commits in here.

I've squashed your commits in the commit that references your PR. I _guess_ it's still OK since this PR is for testing.

**Comment by amjoseph-nixpkgs** [comment]
It's impossible for anybody else to figure out what you've done.

Changing the authorship on other peoples' commits is not OK.

**Comment by wegank** [comment]
Okay, I'll rebase.

**Comment by wegank** [comment]
@ofborg build stdenv

**Comment by amjoseph-nixpkgs** [comment]
I still don't see https://github.com/NixOS/nixpkgs/pull/206907 anywhere in the commit history of this PR, as [you claimed here](https://github.com/NixOS/nixpkgs/pull/209870#issuecomment-1411231385).

As I pointed out, https://github.com/NixOS/nixpkgs/pull/206907 isn't rebased past https://github.com/NixOS/nixpkgs/pull/213185 so there is no way to make a clean comparison without mangling one PR or the other.

That's why we wait for them to once again have a common ancestor.  This will have to happen in order for one of them to merge and the other to be merge-eligible.

**Review by ghost — CHANGES_REQUESTED** [review]
I still don't see https://github.com/NixOS/nixpkgs/pull/206907 anywhere in the commit history of this PR, as [you claimed here](https://github.com/NixOS/nixpkgs/pull/209870#issuecomment-1411231385).

As I pointed out, https://github.com/NixOS/nixpkgs/pull/206907 isn't rebased past https://github.com/NixOS/nixpkgs/pull/213185 so there is no way to make a clean comparison without mangling one PR or the other.

That's why we wait for them to once again have a common ancestor.  This will have to happen in order for one of them to merge and the other to be merge-eligible.

**Pull request closed without merging**
