### PR TITLE
cmake: fix darwin bootstrapping

### LINKED ISSUE #56244: Darwin: `cmake-boot` fails to build on `staging-next`
## Issue description

```
Scanning dependencies of target OSXScriptLauncher
[ 83%] Building CXX object Source/CMakeFiles/OSXScriptLauncher.dir/CPack/OSXScriptLauncher.cxx.o
[ 83%] Linking CXX executable ../bin/OSXScriptLauncher
[ 83%] Built target OSXScriptLauncher
Scanning dependencies of target cmakexbuild
[ 83%] Building CXX object Source/CMakeFiles/cmakexbuild.dir/cmakexbuild.cxx.o
[ 83%] Linking CXX executable ../bin/cmakexbuild
ld: framework not found CoreServices
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Source/CMakeFiles/cmakexbuild.dir/build.make:96: bin/cmakexbuild] Error 1
make[1]: *** [CMakeFiles/Makefile2:2160: Source/CMakeFiles/cmakexbuild.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
builder for '/nix/store/62agbb042zndr5xy2iszq7mlhfwbr9g3-cmake-boot-3.13.4.drv' failed with exit code 2
```

https://hydra.nixos.org/build/89378303

Relevant `staging-next` PR https://github.com/NixOS/nixpkgs/pull/56200

cc @NixOS/darwin-maintainers 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

**NOTE** I only tested the bootstrap cmake at this point, but this might unblock staging-next.

Fixes #56244

/cc @FRidh @vcunat

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Nitpick: what about applying darwin-only patches only on darwin?  That way we won't need to rebuild elsewhere when touching them (in future).

**Comment by LnL7** [comment]
I'm not a fan of conditional patches, but I could make this a darwin only change if we don't want to rebuild linux packages on staging-next right now.

**Comment by vcunat** [comment]
Well, it's perhaps no big deal, as it's darwin that's the significant bottleneck.  If we had linux-specific patches that occasionally change and cause mass darwin rebuilds, that would be different.

**Review by vcunat — APPROVED** [review]
I can't see what to wait for, even in case it weren't perfect.

**Comment by LnL7** [comment]
My build isn't done yet, but no errors so far.

**Comment by vcunat** [comment]
Our bigmac will surely be better for this stuff, and it was idling now anyway.

**Pull request merged**
