### PR TITLE
tox: libtoxcore and assorted tox client updates

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

libtoxcore made breaking changes in 0.2 so we now carry both 0.1 and 0.2 for use by the various clients.

Cc @ehmry  @viric @jgeerds @akaWolf @domenkozar @cleverca22 @obadz 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build toxvpn utox toxic qtox ratox libtoxcore

**Comment by Mic92** [comment]
evaluation error should be fixed.

**Comment by peterhoeg** [comment]
> evaluation error should be fixed.

Indeed @Mic92, I just don't have a mac so it's going to be trial and error from here.

**Comment by Mic92** [comment]
Evaluation errors should not be platform dependent.

**Pull request merged**
