### PR TITLE
vimPlugins.octo-nvim: init at 2022-01-13

### PR DESCRIPTION
**Pull request by sei40kr**
###### Motivation for this change

Add [octo.nvim](https://github.com/pwntester/octo.nvim).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
nixpkgs-review is no longer happy with vim plugins from the looks of it.
Is `vim-addon-vim2nix` now an alias by chance?

```
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/joerg/.cache/nixpkgs-review/pr-155181/build.nix
error: attribute 'vim-addon-vim2nix' missing

       at /home/joerg/.cache/nixpkgs-review/pr-155181/nixpkgs/pkgs/misc/vim-plugins/vim-utils.nix:168:11:

          167|         # back to a string.
          168|         ( knownPlugins.${plugin} // { pname = plugin; })
             |           ^
          169|       else
(use '--show-trace' to show detailed location information)
```

**Comment by teto** [comment]
It is an alias. Let's use the correct attribute ("vim2nix") in pkgs/test/vim/default.nix: 

```
  ### vim tests
  ##################
  vim_with_vim2nix = vim_configurable.customize {
    name = "vim"; vimrcConfig.vam.pluginDictionaries = [ "vim-addon-vim2nix" ];
  };
```

Not sure why it fails though.

**Comment by Artturin** [comment]
@teto could you make a pr?

```
[artturin@nixos:~]$ review 150637 -p help2man
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs staging:refs/nixpkgs-review/0 pull/150637/head:refs/nixpkgs-review/1
$ git worktree add /home/artturin/.cache/nixpkgs-review/pr-150637-3/nixpkgs 13cac624b4277901b55585ef76fea29a9b66b41b
Preparing worktree (detached HEAD 13cac624b42)
Updating files: 100% (29355/29355), done.
HEAD is now at 13cac624b42 Merge staging-next into staging
$ git merge --no-commit --no-ff e68d2cf1284087f39b1ff55b62f656b0d111f352
Automatic merge went well; stopped before committing as requested
error: attribute 'vim-addon-vim2nix' missing

       at /home/artturin/.cache/nixpkgs-review/pr-150637-3/nixpkgs/pkgs/misc/vim-plugins/vim-utils.nix:168:11:

          167|         # back to a string.
          168|         ( knownPlugins.${plugin} // { pname = plugin; })
             |           ^
          169|       else
(use '--show-trace' to show detailed location information)
nix --experimental-features nix-command --system x86_64-linux eval --json --impure --expr (import /nix/store/8hl196mx0rijshxb8408jcc87g45xkhx-nixpkgs-review-2.6.3/lib/python3.9/site-packages/nixpkgs_review/nix/evalAttrs.nix { allowAliases = false; attr-json = /tmp/tmptbocq1mc; }) failed to run, /tmp/tmptbocq1mc was stored inspection
https://github.com/NixOS/nixpkgs/pull/150637 failed to build
```

**Comment by teto** [comment]
@Artturin I can review your PR

**Comment by SuperSandro2000** [comment]
> It is an alias. Let's use the correct attribute ("vim2nix") in pkgs/test/vim/default.nix:
> 
> ```
>   ### vim tests
>   ##################
>   vim_with_vim2nix = vim_configurable.customize {
>     name = "vim"; vimrcConfig.vam.pluginDictionaries = [ "vim-addon-vim2nix" ];
>   };
> ```
> 
> Not sure why it fails though.

nixpkgs-review disabled aliases which always reveals strange bugs.

**Pull request merged**
