### PR TITLE
pidgin-sipe: fix compile issue

### PR DESCRIPTION
**Pull request by reimundklain**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [X] aarch64-linux
  - [X] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bjornfor — COMMENTED** [review]
Please update the commit message to "package: what" and add an explanation to why we'd want to disable dbus.

**Comment by daymien** [comment]
Sry but I'm not sure why we would want to disable dbus. I compared nix log for 22.05 with log form nix-build -A pipe-sipe on 22.11 the difference which leads to the current compiler error. And because there was no explanation why we now need dbus for pidgin-sipe 22.11 I removed the dependency.

Sure a more deeper investigation would be to check why the include doesn't work but for now it compiles and works again as before and I don't know if somebody else desperately looks for dbus support on this package.

nix log 22.05 
`...
checking if Kerberos 5 is available... no
checking for DBUS... no
checking for GLIB... yes
...
`

**Comment by bjornfor** [comment]
> Sorry but I'm not sure why we would want to disable dbus.

You changed the commit message to "[..] fix compile issue" -- that's a perfectly good reason to me :-)

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
Thanks!

**Pull request merged**
