### PR TITLE
phpunit: enable for all platforms

### PR DESCRIPTION
**Pull request by lockejan**
###### Description of changes

Due to a lacking platform declaration, the package was disabled for all platforms.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lockejan** [comment]
Result of `nixpkgs-review pr 226845` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by wegank** [comment]
While the diff looks good, I think the package does build on all platforms without this PR.

**Comment by drupol** [comment]
It does build without this pr indeed.

**Comment by lockejan** [comment]
> While the diff looks good, I think the package does build on all platforms without this PR.

You are right. The flake-input in my project was too old and therefore haven't had phpunit in it. Sorry for the noise.

**Comment by lockejan** [comment]
I think it's still a good idea to add it anyways, as it is wrongly displayed on nix search as `This package is not available on any platform.`

**Comment by wegank** [comment]
Needs rebase.

**Comment by lockejan** [comment]
> Needs rebase.

done (;

**Review by wegank — APPROVED** [review]

**Comment by drupol** [comment]
I'm confused... `phpunit` is on https://search.https://search.nixos.org/packages?channel=unstable&show=phpunit&from=0&size=50&sort=relevance&type=packages&query=phpunit

**Comment by drupol** [comment]
@wegank This PR is not needed, phpunit is already available on [https://search.https://search.nixos.org/packages?channel=unstable&show=phpunit&from=0&size=50&sort=relevance&type=packages&query=phpunit](https://search.https//search.nixos.org/packages?channel=unstable&show=phpunit&from=0&size=50&sort=relevance&type=packages&query=phpunit)

It would have been nice to address my comment before merging it.

**Comment by wegank** [comment]
> I think it's still a good idea to add it anyways, as it is wrongly displayed on nix search as `This package is not available on any platform.`

@drupol I guess you haven't noticed what @lockejan said in the end of the sentence.

**Comment by drupol** [comment]
Fair enough, thanks for the clarification, my mistake.

I'm going to fix this in all the PHP related derivations in https://github.com/NixOS/nixpkgs/pull/225401

**Pull request merged**
