### PR TITLE
timeular: init at 3.4.1

### PR DESCRIPTION
**Pull request by ktor**
###### Motivation for this change
I do have the Timeular dice but up until now I've used third party OSS cli software to send my worklogs. Shout out to 
Kris Buist, author of https://github.com/krisbuist/timeular-zei-linux, you've enabled the ZEI dice for me on NixOS for two years already!! 

I've done all post-editing of timetracks on their Android app that's a little laggy.

Since Timeular has released AppImage version of their desktop app recently I've decided to give it a try. It works flawlessy, is snappy, has nice GUI and connects with the dice without a problem on NixOS. The package could be improved. It doesn't generate `.desktop` file and could probably use appImageTool instead of appimage-run but it works and user does not need to prepare it's own appimage-run overlay with libsecret.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ktor** [comment]
Hi @tilpner , @M-Gregoire I've found you both through the pull request: https://github.com/NixOS/nixpkgs/pull/54696 and figured out you could have good ideas how to package AppImage app better. I've never done that before.

**Comment by tilpner** [comment]
Please do not use appimage-run inside nixpkgs, it is meant exclusively for interactive use.

- All other packages finish their installation at build-time, with appimage-run the application needs to extract on the first execution
- This extraction happens for every user, unnecessarily increasing storage requirements
- There is no garbage collection for the extraction target
- The extraction target is in writable storage, when it could be extracted into the immutable nix store

You should instead use `appimageTools.wrapType2`, which also accepts the `extraPkgs` argument.
[The documentation](https://nixos.org/nixpkgs/manual/#sec-pkgs-appimageTools) might be helpful, and you can reply here if you encounter any trouble with it.

**Comment by ktor** [comment]
hi @tilpner, I've applied your advice. Everything runs smoothly! Thank you!

Do you have an idea how could I make `wrapType2` function to use/reuse desktop file and icons that already packaged within appImage format?

```
'squashfs-root/timeular.desktop' -> '/nix/store/washyzh5mnwjmw6d3sakpb974jl8c8z4-timeular-3.1.1-extracted/timeular.desktop'
'squashfs-root/usr/share/icons' -> '/nix/store/washyzh5mnwjmw6d3sakpb974jl8c8z4-timeular-3.1.1-extracted/usr/share/icons'
'squashfs-root/usr/share/icons/hicolor' -> '/nix/store/washyzh5mnwjmw6d3sakpb974jl8c8z4-timeular-3.1.1-extracted/usr/share/icons/hicolor'
'squashfs-root/usr/share/icons/hicolor/128x128' -> '/nix/store/washyzh5mnwjmw6d3sakpb974jl8c8z4-timeular-3.1.1-extracted/usr/share/icons/hicolor/128x128'
```

**Comment by tilpner** [comment]
@ktor That's a recurring problem, and unfortunately appimageTools doesn't account for desktop files. You can follow the workaround used by e.g. the irccloud package:

https://github.com/NixOS/nixpkgs/blob/dda3d9dc1242c5fd2100236f517f3e52dd551db1/pkgs/applications/networking/irc/irccloud/default.nix#L13-L29

**Comment by ktor** [comment]
hi @tilpner,

the package seems to have it all solved: https://github.com/NixOS/nixpkgs/pull/92799, I'll copy the solution! thx @tfmoraes !!

**Comment by tfmoraes** [comment]
Thanks @ktor! I used the [Joplin-desktop](https://github.com/NixOS/nixpkgs/blob/29062cec8d214013a8e1f944d16e32c36294e0d0/pkgs/applications/misc/joplin-desktop/default.nix) package as base.

**Comment by ktor** [comment]
hi @tilpner @M-Gregoire, package is updated with a desktop file and icon. I've tested the binary to work.

**Comment by ktor** [comment]
hi @tilpner, I've just realized that **irccloud** package example you've provided is exactly the same as the one I've found in pull request #92799, thank you! :)

**Comment by zowoq** [comment]
@ofborg eval

**Pull request merged**
