### PR TITLE
nixos/gitea: Support SMTP without pw in the store

### PR DESCRIPTION
**Pull request by dasJ**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by spacekookie — APPROVED** [review]
This looks really cool :+1:

**Comment by aanderse** [comment]
@GrahamcOfBorg build nixosTests.gitea

**Comment by aanderse** [comment]
@dasJ Thanks for contributing this.

@etu @Ma27 @kolaente @dasJ Someone here must be a `go` programmer, right? Think about how much our `preStart` script could be cleaned up if someone went ahead and finished implementing secret storage as per https://github.com/go-gitea/gitea/issues/4860#issuecomment-502909260 Any takers?

**Comment by dasJ** [comment]
@aanderse you know what would scale a lot better? Something like this:
```
[gitea]
EXTRA_CONFIG_FILES = /var/lib/gitea/secrets.conf,/var/lib/secrets/gitea/smtp.conf
```

**Comment by aanderse** [comment]
@dasJ For sure. That's the title of the issue I just linked, as you have seen. I'm not asking anyone here to join the `gitea` dev team, though. I'm just saying that someone with sufficient `go` experience could probably replicate for other secrets what was done for the one.

But if you're really keen or know someone on the `gitea` team... please do! :laughing:

**Comment by kolaente** [comment]
@aanderse @dasJ As it currently stands, we'll switch to a [different library](https://github.com/spf13/viper) for config file handling rather sooner than later since the one we're using currently (`go-ini`) has issues. While it would absolutly be possible to "quickly hack something together" to load more secrets from files, I would prefer to tackle this once we got rid of `go-ini` to do it properly/for more use cases.

(I'm one of the Gitea devs)

**Review by aanderse — APPROVED** [review]
LGTM :+1:
@dasJ Thanks again!

**Comment by schmittlauch** [comment]
@dasJ I'm a bit surprised that it is possible to supply an SMTP password for the mailer, but no other required configs like the actual SMTP server to use or the username.
Are folks expected to configure this via `services.gitea.extraConfig` or what's the idea here?

**Pull request merged**
