### PR TITLE
Mysql datadir changelog

### PR DESCRIPTION
**Pull request by bachp**
###### Motivation for this change

Document the changes from #25931

###### Things done

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Looks pretty good. Can you clarify the part about how keeping `stateVersion` stable will keep the  directory stable on disk?

**Comment by bachp** [comment]
@grahamc Sorry I forgot about this MR.

I grouped the changes together with the postgresql changes and added a general phrase that these only apply if `stateVersion` is changed.

**Comment by grahamc** [comment]
Thank you!

**Pull request merged**
