### PR TITLE
wabt: fix patch hash

### PR DESCRIPTION
**Pull request by eadwu**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/46764#issuecomment-629623664
There shouldn't be any more updates since the PR was approved.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ekleog** [comment]
Ofborg reports another hash… let's try again?

@ofborg build wabt wabt.passthru.tests

**Comment by Ekleog** [comment]
Nope, wasn't a temporary failure from github -- looks like the sha256 you want is 1nh1ddsak6w51np17xf2r7i0czxrjslz1i4impmmp88h5bp2yjba

**Comment by eadwu** [comment]
Oh my mistake, used `nix-prefetch-url` to fetch the hash, forgot `fetchpatch` doesn't use the same hash. Fixed.

**Comment by Ekleog** [comment]
Checking the darwin build

@ofborg build wabt wabt.passthru.tests

**Comment by Ekleog** [comment]
Looks good! Thank you for the PR :)

**Pull request merged**
