### PR TITLE
nixos/preloadLibraries: init

### PR DESCRIPTION
**Pull request by jonringer**
###### Description of changes

Allow for the generation of /etc/ld-nix.so.preload

Should allow for NixOS upgrades which include a glibc update
to avoid symbol issues from the previous system's libc.

Not sure if nixos/modules/system/activation/top-level.nix is the appropriate location, but happy to move it to a better location.

I do realize this is a hack, which is why it's opt-in. It still doesn't solve the use of stable users getting binaries from unstable with newer symbols. But it does solve the issue of people upgrading their system and it becoming unusable.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
ld.so.preload has caused problems in the past https://github.com/NixOS/nixpkgs/issues/100799#issuecomment-723638972 because an older version can be present at bootup and make switch-to-configuration crash before it has had a chance to update this file to a compatible version of the to-be-booted generation.

**Comment by trofi** [comment]
Does it work for cases when non-native ABI is ran? Like i686 binary of amd64 host or a qemu-emulated binary via binfmt-misc. I suspect at the very least you will get a warning about an attempt to load library from a wrong ABI.

libc.so.6 can't generally be used with an ld.so from different version as they share details of internal structure of glibc. I think this change will break all the glibc-using binaries that are not linked against currently active glibc (while previously they worked and loaded their version of `libc.so.6` that matches their `ld.so`).

Other distributions provide `/lib64/ld-linux-x86-64.so.2`/`/lib64/libc.so.6` for non-hermetic users and ensuring their versions only increase might be less unsafe.

**Comment by jonringer** [comment]
Yea, glibc is a bit of a special case :(

**Comment by yipengsun** [comment]
> libc.so.6 can't generally be used with an ld.so from different version as they share details of internal structure of glibc. I think this change will break all the glibc-using binaries that are not linked against currently active glibc (while previously they worked and loaded their version of `libc.so.6` that matches their `ld.so`).

Suppose I have some long-running process in a `nix develop` environment (say, doing some numerical computation) while I update the system-wide `glibc`. If I enable the `system.preloadLibraries` option, would that break my long-running process in the `nix develop` environment?

**Comment by trofi** [comment]
> > libc.so.6 can't generally be used with an ld.so from different version as they share details of internal structure of glibc. I think this change will break all the glibc-using binaries that are not linked against currently active glibc (while previously they worked and loaded their version of `libc.so.6` that matches their `ld.so`).
> 
> Suppose I have some long-running process in a `nix develop` environment (say, doing some numerical computation) while I update the system-wide `glibc`. If I enable the `system.preloadLibraries` option, would that break my long-running process in the `nix develop` environment?

If your `nix develop` environment happens to pull in different `glibc` version from what you are preloading I would expect it to break right at the application start.

If your `nix develop` application starts at the time when preloaded and linked glibc versions match, then it would start and run fine as preload is redundant and would act as a no-op. Later if system-wide `glibc` updates I would expect any `exec` call from you application to run executables linket against outdated `glibc` (pinned to the environment). They will get an inconsistent preload of old `ld.so` and fresh `libc.so.6`. I would expect crashes.

**Comment by dasJ** [comment]
I guess `nixos/modules/config/` would be a more sensible place for this, next to similar stuff like `malloc.nix`

**Comment by jonringer** [comment]
Yea, I don't think this is a solid solution to the problem I'm trying to address.

Still some, "in these cases, impure and pure environments are clashing, and you will have crashes"

going to close. Thank you everyone for reviewing :)

**Pull request closed without merging**
