### PR TITLE
pythonPackages: fix typo about input argument `disabled`

### PR DESCRIPTION
**Pull request by ShamrockLee**
###### Description of changes

`buildPythonPackage` accepts `disabled` instead of `disable` to throw evaluation error on unsupported Python interpreters. Attempt to access such option as `disable` without the trailing `d` will be ignored silently, with an unexpected environment variable `disable` being injected into the build environment.

This patch fixes those misspelled `disabled` specification.

This is an apparent bug, and the fix should hardly change the output content. Maybe we could backport it to the stable release. ~(I choose to target staging, as 87 packages got rebuilt due to `disable` environment variable being removed.)~

Update: Target the master branch as suggested by @tjni.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ShamrockLee** [comment]
@ofborg build onionshare python3Packages.flask-openid python3Packages.furo python3Packages.graphql-server-core python3Packages.sphinx-basic-ng

**Review by tjni — COMMENTED** [review]
Thank you for fixing these!

1. Can you delete the `disabled = !isPy3k` checks? We don't support Python 2 anymore when we manage packages in nixpkgs, so we can assume it doesn't exist.

2. With this rebuild count, it can directly target `master`.

**Comment by ShamrockLee** [comment]
Updated. Thank you for your reply and patience.

**Review by tjni — APPROVED** [review]
LGTM, thank you!

**Review by Luflosi — APPROVED** [review]

**Comment by ShamrockLee** [comment]
Came back here to resolve merge conflict (due to the version bump of a package), but found even more packages affected by such typo. They are now addressed by this PR.

**Comment by ShamrockLee** [comment]
> 1. Can you delete the disabled = !isPy3k checks? We don't support Python 2 anymore when we manage packages in nixpkgs, so we can assume it doesn't exist.

BTW, `isPy3k` may still be relevant for https://github.com/cachix/nixpkgs-python people.

**Pull request merged**
