### PR TITLE
firefox, firefox-bin: 53.0.3 -> 54.0, firefox-esr: 52.1.2esr -> 52.2.0esr [Critical security fix]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Various security fixes
- Simplified the download button and download status panel
- Added support for multiple content processes (e10s-multi)
- Added Burmese (my) locale

https://www.mozilla.org/en-US/firefox/54.0/releasenotes/

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Played a video on YouTube with firefox, firefox-esr, and firefox-bin.

---

### CODE REVIEW

**Comment by joachifm** [comment]
I wonder about the rebuild impact of at nss/nspr; can those go directly to master?

**Comment by vcunat** [comment]
```
Estimating rebuild amount by counting changed Hydra jobs.
    210 x86_64-darwin
   1549 x86_64-linux
```
(this whole PR)

**Comment by vcunat** [comment]
I believe the rebuild amount is OK, esp. given the security fixes.

**Review by vcunat — APPROVED** [review]
Seems to run OK.

**Pull request merged**
