### PR TITLE
Fix the pip package

### LINKED ISSUE #12190: python3.5-pip is missing bin/pip
I'm using the nixpkgs-unstable channel (nixpkgs-16.03pre74645.1e63074) on Darwin. I installed  python3.5-pip, but the resulting nix package does not contain the pip binary:

```
$ nix-env -i python3.5-pip
installing ‘python3.5-pip-7.1.2’
these paths will be fetched (13.47 MiB download, 87.67 MiB unpacked):
  /nix/store/2qbqm1gnw98x2mbsxl0kq0vgphpgq4i5-python3.5m-setuptools-18.2
  /nix/store/7az2ns2gwlg6jvi60gbn36486ha1hhf5-tcl-8.6.4
  /nix/store/l6gwjripcsa94dh1dcfwd2zr5fn9mh1l-python3-3.5.1
  /nix/store/ln57640j93c869vm6yz8s0h58495jx38-tk-8.6.4
  /nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2
fetching path ‘/nix/store/7az2ns2gwlg6jvi60gbn36486ha1hhf5-tcl-8.6.4’...

*** Downloading ‘https://cache.nixos.org/nar/0jjvrndnyqx6v3jm7s71hf3hvmc1rz1sxm5dad31s9xl2fx1mfmb.nar.xz’ to ‘/nix/store/7az2ns2gwlg6jvi60gbn36486ha1hhf5-tcl-8.6.4’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1878k  100 1878k    0     0  1000k      0  0:00:01  0:00:01 --:--:-- 1001k

fetching path ‘/nix/store/ln57640j93c869vm6yz8s0h58495jx38-tk-8.6.4’...

*** Downloading ‘https://cache.nixos.org/nar/1qwds3zg9zqd02rqkyg5dg52panby1ya5k728r5f1hncwx45z6a7.nar.xz’ to ‘/nix/store/ln57640j93c869vm6yz8s0h58495jx38-tk-8.6.4’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1640k  100 1640k    0     0  1003k      0  0:00:01  0:00:01 --:--:-- 1006k

fetching path ‘/nix/store/l6gwjripcsa94dh1dcfwd2zr5fn9mh1l-python3-3.5.1’...

*** Downloading ‘https://cache.nixos.org/nar/0zp855m8bngcg7qha5l8agv2iwb3j9y8qclhjjwzmh48mpkk2jd0.nar.xz’ to ‘/nix/store/l6gwjripcsa94dh1dcfwd2zr5fn9mh1l-python3-3.5.1’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9924k  100 9924k    0     0  1717k      0  0:00:05  0:00:05 --:--:-- 2238k

fetching path ‘/nix/store/2qbqm1gnw98x2mbsxl0kq0vgphpgq4i5-python3.5m-setuptools-18.2’...

*** Downloading ‘https://cache.nixos.org/nar/03d0ijds3c7fppp8xnr8drf2mgj39d7mp109m15yh4jcvl3qm055.nar.xz’ to ‘/nix/store/2qbqm1gnw98x2mbsxl0kq0vgphpgq4i5-python3.5m-setuptools-18.2’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  346k  100  346k    0     0   358k      0 --:--:-- --:--:-- --:--:--  359k

fetching path ‘/nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2’...

*** Downloading ‘https://cache.nixos.org/nar/1hx9npigd4bwdkwihpmdmq5ly9jrwfhs0xki527f3y94vbj50ar6.nar.xz’ to ‘/nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   336  100   336    0     0    772      0 --:--:-- --:--:-- --:--:--   775

building path(s) ‘/nix/store/7vahkjcq2jk17wpy2pk7g7ln1xpwylfb-user-environment’
created 1624 symlinks in user environment

$ find /nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2
/nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2
/nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2/lib
/nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2/lib/python3.5
/nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2/lib/python3.5/site-packages
/nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2/nix-support
/nix/store/lqc5rcjlj5w72hwf4hwxb3s70v2dg2vf-python3.5-pip-7.1.2/nix-support/propagated-native-build-inputs
```

I see the same problem with python2.7-pip.

### PR DESCRIPTION
**Pull request by abbradar**
Fixes #12190. cc @domenkozar

### CODE REVIEW

**Comment by domenkozar** [comment]
Awesome!

Two comments:

- could you make a PR against `python-wip` branch?
- could you add a comment why ignore installed flag is used for future reference?

**Comment by abbradar** [comment]
I've rebased it, but it doesn't build for me due to unrelated error:

```
ImportError: Start directory is not importable: '/nix/store/3ykhlhc5mg0q28hwn9csbqlpz4xwfjrv-python2.7-setuptools-20.0/lib/python2.7/site-packages/setuptools-20.0-py2.7.egg/setuptools'
builder for ‘/nix/store/d6ziy6p74k06aicnlp9cc39ymzs8b9yl-python2.7-funcsigs-0.4.drv’ failed with exit code 1
```

**Comment by domenkozar** [comment]
Right, that's because of setuptools change we'll have to revert for now. Thanks.

**Comment by abbradar** [comment]
It builds now, indeed -- pushed the branch. Notice that it contains a revert patch now -- should I drop it?

**Comment by FRidh** [comment]
Let's get this in. It would indeed be good to get #12190 fixed. I've updated your commits and pushed it to https://github.com/NixOS/nixpkgs/tree/python-wip
See Hydra at https://headcounter.org/hydra/eval/309903
@domenkozar , could you cancel https://headcounter.org/hydra/build/940765 ?

**Pull request closed without merging**
