### PR TITLE
gnomeExtensions: Auto-update: 82 new, 111 updated, 4 removed

### PR DESCRIPTION
**Pull request by piegamesde**
###### Motivation for this change
Supersedes #126412.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 135066` at ccb35389 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>193 packages built successfully:</summary>
  <ul>
    <li>gnomeExtensions.activity-app-launcher</li>
    <li>gnomeExtensions.add-to-desktop</li>
    <li>gnomeExtensions.add-userhost-to-panel</li>
    <li>gnomeExtensions.advanced-alttab-window-switcher</li>
    <li>gnomeExtensions.air-quality</li>
    <li>gnomeExtensions.all-windows</li>
    <li>gnomeExtensions.alphabetical-app-grid</li>
    <li>gnomeExtensions.alt-tab-only-on-current-workspace</li>
    <li>gnomeExtensions.always-show-titles-in-overview</li>
    <li>gnomeExtensions.always-show-workspace-thumbnails</li>
    <li>gnomeExtensions.animation-tweaks</li>
    <li>gnomeExtensions.app-grid-tweaks</li>
    <li>gnomeExtensions.app-menu-icon-remove-symbolic</li>
    <li>gnomeExtensions.appindicator</li>
    <li>gnomeExtensions.applications-menu</li>
    <li>gnomeExtensions.auto-activities</li>
    <li>gnomeExtensions.auto-move-windows</li>
    <li>gnomeExtensions.autohide-battery</li>
    <li>gnomeExtensions.babar</li>
    <li>gnomeExtensions.better-osd-gnome-40</li>
    <li>gnomeExtensions.bifocals</li>
    <li>gnomeExtensions.big-avatar</li>
    <li>gnomeExtensions.big-sur-status-area</li>
    <li>gnomeExtensions.bing-wallpaper-changer</li>
    <li>gnomeExtensions.block-caribou-36</li>
    <li>gnomeExtensions.bluetooth-battery</li>
    <li>gnomeExtensions.bluetooth-quick-connect</li>
    <li>gnomeExtensions.blur-me</li>
    <li>gnomeExtensions.blur-my-shell</li>
    <li>gnomeExtensions.bottom-panel</li>
    <li>gnomeExtensions.brightness-control-using-ddcutil</li>
    <li>gnomeExtensions.bring-out-submenu-of-power-offlogout-button</li>
    <li>gnomeExtensions.clean-system-menu</li>
    <li>gnomeExtensions.color-picker</li>
    <li>gnomeExtensions.colosseum</li>
    <li>gnomeExtensions.control-blur-effect-on-lock-screen</li>
    <li>gnomeExtensions.coverflow-alt-tab</li>
    <li>gnomeExtensions.cpufreq</li>
    <li>gnomeExtensions.custom-hot-corners-extended</li>
    <li>gnomeExtensions.custom-menu-panel</li>
    <li>gnomeExtensions.customize-ibus</li>
    <li>gnomeExtensions.dark-side-of-gnome</li>
    <li>gnomeExtensions.ddterm</li>
    <li>gnomeExtensions.desk-changer</li>
    <li>gnomeExtensions.desktop-icons-neo</li>
    <li>gnomeExtensions.desktop-icons-ng-ding</li>
    <li>gnomeExtensions.desktop-lyric</li>
    <li>gnomeExtensions.disable-gestures-2021</li>
    <li>gnomeExtensions.disable-workspace-switch-animation-for-gnome-40</li>
    <li>gnomeExtensions.docker-integration</li>
    <li>gnomeExtensions.downfall</li>
    <li>gnomeExtensions.e-ink-mode</li>
    <li>gnomeExtensions.eclipse</li>
    <li>gnomeExtensions.espresso</li>
    <li>gnomeExtensions.executor</li>
    <li>gnomeExtensions.extension-list</li>
    <li>gnomeExtensions.eye-extended</li>
    <li>gnomeExtensions.fedora-linux-updates-indicator</li>
    <li>gnomeExtensions.fixed-ime-list</li>
    <li>gnomeExtensions.floating-dock</li>
    <li>gnomeExtensions.fluorooms-top-bar</li>
    <li>gnomeExtensions.fnlock-switch-thinkpad-compact-usb-keyboard</li>
    <li>gnomeExtensions.focusli</li>
    <li>gnomeExtensions.force-quit</li>
    <li>gnomeExtensions.force-show-osk</li>
    <li>gnomeExtensions.full-battery-indicator</li>
    <li>gnomeExtensions.fullscreen-avoider</li>
    <li>gnomeExtensions.fullscreen-on-new-workspace</li>
    <li>gnomeExtensions.fuzzy-app-search</li>
    <li>gnomeExtensions.gamemode</li>
    <li>gnomeExtensions.gesture-improvements</li>
    <li>gnomeExtensions.gmail-message-tray</li>
    <li>gnomeExtensions.gnome-40-ui-improvements</li>
    <li>gnomeExtensions.gnome-citeurl-search-provider</li>
    <li>gnomeExtensions.go-to-last-workspace</li>
    <li>gnomeExtensions.gsnap</li>
    <li>gnomeExtensions.gtile</li>
    <li>gnomeExtensions.guillotine</li>
    <li>gnomeExtensions.haguichi-indicator</li>
    <li>gnomeExtensions.hibernate-status-button</li>
    <li>gnomeExtensions.hide-activities-button-2</li>
    <li>gnomeExtensions.hide-clock</li>
    <li>gnomeExtensions.hide-panel</li>
    <li>gnomeExtensions.hide-top-bar</li>
    <li>gnomeExtensions.hide-workspace-thumbnails</li>
    <li>gnomeExtensions.home-assistant-extension</li>
    <li>gnomeExtensions.hue-lights</li>
    <li>gnomeExtensions.ibus-tweaker</li>
    <li>gnomeExtensions.ideapad</li>
    <li>gnomeExtensions.ideapad-mode</li>
    <li>gnomeExtensions.improved-osk</li>
    <li>gnomeExtensions.just-perfection</li>
    <li>gnomeExtensions.kernel-indicator</li>
    <li>gnomeExtensions.keyman</li>
    <li>gnomeExtensions.kitchen-timer</li>
    <li>gnomeExtensions.kitsch</li>
    <li>gnomeExtensions.krypto</li>
    <li>gnomeExtensions.kube-config</li>
    <li>gnomeExtensions.launch-new-instance</li>
    <li>gnomeExtensions.light-dict</li>
    <li>gnomeExtensions.lock-keys</li>
    <li>gnomeExtensions.logo-menu</li>
    <li>gnomeExtensions.lunar-calendar</li>
    <li>gnomeExtensions.lyrics-finder</li>
    <li>gnomeExtensions.macbook-battery-percentage-corrector</li>
    <li>gnomeExtensions.material-shell</li>
    <li>gnomeExtensions.messaging-menu</li>
    <li>gnomeExtensions.minimize-all</li>
    <li>gnomeExtensions.miniview</li>
    <li>gnomeExtensions.move-workspace-switcher-popup</li>
    <li>gnomeExtensions.move-ws-switcher-popup</li>
    <li>gnomeExtensions.mumbleping</li>
    <li>gnomeExtensions.mute-spotify-ads</li>
    <li>gnomeExtensions.native-window-placement</li>
    <li>gnomeExtensions.net-speed-simplified</li>
    <li>gnomeExtensions.netspeed</li>
    <li>gnomeExtensions.night-light-slider</li>
    <li>gnomeExtensions.noannoyance</li>
    <li>gnomeExtensions.noannoyance-2</li>
    <li>gnomeExtensions.non-blocking-switcher</li>
    <li>gnomeExtensions.nordvpn-connect</li>
    <li>gnomeExtensions.notification-centerselenium-h</li>
    <li>gnomeExtensions.notification-counter</li>
    <li>gnomeExtensions.notification-timeout</li>
    <li>gnomeExtensions.obmin</li>
    <li>gnomeExtensions.panel-scroll</li>
    <li>gnomeExtensions.panel-world-clock-lite</li>
    <li>gnomeExtensions.password-calculator</li>
    <li>gnomeExtensions.persian-calendar</li>
    <li>gnomeExtensions.persistent-email-notifications</li>
    <li>gnomeExtensions.places-status-indicator</li>
    <li>gnomeExtensions.print-website</li>
    <li>gnomeExtensions.reading-strip</li>
    <li>gnomeExtensions.recent-items</li>
    <li>gnomeExtensions.removable-drive-menu</li>
    <li>gnomeExtensions.remove-app-menu</li>
    <li>gnomeExtensions.replace-activities-text</li>
    <li>gnomeExtensions.round-robin-tab-order</li>
    <li>gnomeExtensions.run-or-raise</li>
    <li>gnomeExtensions.runcat</li>
    <li>gnomeExtensions.screen-lock</li>
    <li>gnomeExtensions.screen-word-translate</li>
    <li>gnomeExtensions.screenshot-window-sizer</li>
    <li>gnomeExtensions.scroll-panel</li>
    <li>gnomeExtensions.settingscenter</li>
    <li>gnomeExtensions.shamsi-calendar</li>
    <li>gnomeExtensions.shortcuts-for-apt</li>
    <li>gnomeExtensions.show-desktop-applet</li>
    <li>gnomeExtensions.shu-zhi</li>
    <li>gnomeExtensions.shutdowntimer</li>
    <li>gnomeExtensions.shutdowntimer-2</li>
    <li>gnomeExtensions.simple-net-speed</li>
    <li>gnomeExtensions.simply-workspaces</li>
    <li>gnomeExtensions.snap-manager</li>
    <li>gnomeExtensions.spin-down-hard-disk</li>
    <li>gnomeExtensions.spotify-artwork-fixer</li>
    <li>gnomeExtensions.switch-two-layouts</li>
    <li>gnomeExtensions.system-action-hibernate</li>
    <li>gnomeExtensions.system-monitor-next</li>
    <li>gnomeExtensions.task-widget</li>
    <li>gnomeExtensions.thanatophobia</li>
    <li>gnomeExtensions.tiling-assistant</li>
    <li>gnomeExtensions.time-awareness</li>
    <li>gnomeExtensions.time-tracker</li>
    <li>gnomeExtensions.timepp</li>
    <li>gnomeExtensions.timezone</li>
    <li>gnomeExtensions.top-bar-organizer</li>
    <li>gnomeExtensions.top-panel-notification-icons</li>
    <li>gnomeExtensions.translate-clipboard</li>
    <li>gnomeExtensions.transparent-top-bar</li>
    <li>gnomeExtensions.transparent-top-panel</li>
    <li>gnomeExtensions.transparent-window-moving</li>
    <li>gnomeExtensions.tray-icons-reloaded</li>
    <li>gnomeExtensions.true-color-invert</li>
    <li>gnomeExtensions.tuned-profile-switcher</li>
    <li>gnomeExtensions.ubuntu-appearance-gnome-40</li>
    <li>gnomeExtensions.umi-coin-rate</li>
    <li>gnomeExtensions.user-id-in-top-panel</li>
    <li>gnomeExtensions.user-themes</li>
    <li>gnomeExtensions.user-themes-x</li>
    <li>gnomeExtensions.vertical-overview</li>
    <li>gnomeExtensions.vertical-window-list</li>
    <li>gnomeExtensions.vitals</li>
    <li>gnomeExtensions.vlan-switcher</li>
    <li>gnomeExtensions.volume-mixer</li>
    <li>gnomeExtensions.wg-indicator</li>
    <li>gnomeExtensions.window-list</li>
    <li>gnomeExtensions.windownavigator</li>
    <li>gnomeExtensions.wireless-hid</li>
    <li>gnomeExtensions.workspace-indicator</li>
    <li>gnomeExtensions.workspaces-bar</li>
    <li>gnomeExtensions.x11-gestures</li>
    <li>gnomeExtensions.you2ber</li>
  </ul>
</details>

**Comment by maralorn** [comment]
@piegamesde. This looks sane. I have no clue though how best to test this. Do you have a way to convince yourself that everything is working right?

**Comment by piegamesde** [comment]
@maralorn I have a VM with all extensions installed but it is more for bug fixing than update testing—there are simply way too many extensions. So the updates are mostly hit-or-miss …

**Comment by maralorn** [comment]
Thx for the PR.

After consideration I deemed this save to merge. The nixpkgs-review report was very helpful.

**Comment by tyrion** [comment]
Hello, has this been backported to 21.05? I tried installing paperwm and material-shell and it says they are incompatible (as reported in #125975 )

Thanks!

**Comment by piegamesde** [comment]
@tyrion No, GNOME support on stable is barely existent. But if you want to put the effort in making a backport PR this close to a new release, feel free.

**Comment by tyrion** [comment]
@piegamesde thanks for the quick reply. I am not sure I have the required knowledge to backport this. What would be your suggestions to get one or two extensions to work? Upgrade the whole system to unstable?

Anyway, I tried to install the correct extension by putting this (I didn't find an other way to access `buildShellExtension`)
 into the systemPackages:

```nix
((callPackage (modulesPath + "../../../pkgs/desktops/gnome/extensions") { }).buildShellExtension {
      "uuid" = "material-shell@papyelgringo";
      "name" = "Material Shell";
      "pname" = "material-shell";
      "description" = "..";
      "link" = "https://extensions.gnome.org/extension/3357/material-shell/";
      "version" = "17";
      "sha256" = "19zniqwksrfxcdw2byqhi8px0bzb28qljzzl0wl2cb8jnm517g6b";
      "metadata" = "..";
    })
```

I can see the extension, but when I turn it on, the gnome session crashes. So I am not sure if this is not the correct way to package/install it, or if there is some other problem.

**Comment by piegamesde** [comment]
> I am not sure I have the required knowledge to backport this.

It's juts git stuff. Checkout the release branch, cherry-pick the changes you want and then make a pull request targeting that branch. (Somebody correct me if I'm wrong)

> What would be your suggestions to get one or two extensions to work?

Simply use the `gnomeExtensions` attribute from a newer attribute set. No need to upgrade the whole system. Note that you may have to switch to `gnome40Extensions` (explicitly stating the version) once unstable has updated to 41. You can also put this into an overlay: `self: super: { gnomeExtensions = pkgsUnstable.gnomeExtensions; }`.

> I didn't find an other way to access buildShellExtension

Interesting, it was forgotten in `all-packages.nix`. Thanks for making me aware, I'll take care of this.

**Comment by tyrion** [comment]
Ok, thanks for the information. I guess I could try to make a PR, however, I should make material-shell work first, because right now it crashes gnome-shell so it wouldn't be too useful to backport it.

**Pull request merged**
