### PR TITLE
kdePackages.accounts-qt: update repo and homepage

### PR DESCRIPTION
**Pull request by jopejoe1**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
This can go directly to master. Also, we should probably update signond and the rest of that stuff along with this.

**Comment by K900** [comment]
Result of `nixpkgs-review pr 306914` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>calligra</li>
    <li>kdePackages.kamoso</li>
    <li>kdePackages.kamoso.debug</li>
    <li>kdePackages.kamoso.dev</li>
    <li>kdePackages.kamoso.devtools</li>
    <li>maui-shell</li>
    <li>trojita</li>
  </ul>
</details>
<details>
  <summary>318 packages built:</summary>
  <ul>
    <li>ayatana-indicator-datetime</li>
    <li>digikam</li>
    <li>kdePackages.accounts-qt (qt6Packages.accounts-qt)</li>
    <li>kdePackages.akonadi</li>
    <li>kdePackages.akonadi-calendar</li>
    <li>kdePackages.akonadi-calendar-tools</li>
    <li>kdePackages.akonadi-calendar-tools.debug</li>
    <li>kdePackages.akonadi-calendar-tools.dev</li>
    <li>kdePackages.akonadi-calendar-tools.devtools</li>
    <li>kdePackages.akonadi-calendar.debug</li>
    <li>kdePackages.akonadi-calendar.dev</li>
    <li>kdePackages.akonadi-calendar.devtools</li>
    <li>kdePackages.akonadi-contacts</li>
    <li>kdePackages.akonadi-contacts.debug</li>
    <li>kdePackages.akonadi-contacts.dev</li>
    <li>kdePackages.akonadi-contacts.devtools</li>
    <li>kdePackages.akonadi-import-wizard</li>
    <li>kdePackages.akonadi-import-wizard.debug</li>
    <li>kdePackages.akonadi-import-wizard.dev</li>
    <li>kdePackages.akonadi-import-wizard.devtools</li>
    <li>kdePackages.akonadi-mime</li>
    <li>kdePackages.akonadi-mime.debug</li>
    <li>kdePackages.akonadi-mime.dev</li>
    <li>kdePackages.akonadi-mime.devtools</li>
    <li>kdePackages.akonadi-notes</li>
    <li>kdePackages.akonadi-notes.debug</li>
    <li>kdePackages.akonadi-notes.dev</li>
    <li>kdePackages.akonadi-notes.devtools</li>
    <li>kdePackages.akonadi-search</li>
    <li>kdePackages.akonadi-search.debug</li>
    <li>kdePackages.akonadi-search.dev</li>
    <li>kdePackages.akonadi-search.devtools</li>
    <li>kdePackages.akonadi.debug</li>
    <li>kdePackages.akonadi.dev</li>
    <li>kdePackages.akonadi.devtools</li>
    <li>kdePackages.akonadiconsole</li>
    <li>kdePackages.akonadiconsole.debug</li>
    <li>kdePackages.akonadiconsole.dev</li>
    <li>kdePackages.akonadiconsole.devtools</li>
    <li>kdePackages.akregator</li>
    <li>kdePackages.akregator.debug</li>
    <li>kdePackages.akregator.dev</li>
    <li>kdePackages.akregator.devtools</li>
    <li>kdePackages.angelfish</li>
    <li>kdePackages.angelfish.debug</li>
    <li>kdePackages.angelfish.dev</li>
    <li>kdePackages.angelfish.devtools</li>
    <li>kdePackages.audiotube</li>
    <li>kdePackages.audiotube.debug</li>
    <li>kdePackages.audiotube.dev</li>
    <li>kdePackages.audiotube.devtools</li>
    <li>kdePackages.calendarsupport</li>
    <li>kdePackages.calendarsupport.debug</li>
    <li>kdePackages.calendarsupport.dev</li>
    <li>kdePackages.calendarsupport.devtools</li>
    <li>kdePackages.discover</li>
    <li>kdePackages.discover.debug</li>
    <li>kdePackages.discover.dev</li>
    <li>kdePackages.discover.devtools</li>
    <li>kdePackages.eventviews</li>
    <li>kdePackages.eventviews.debug</li>
    <li>kdePackages.eventviews.dev</li>
    <li>kdePackages.eventviews.devtools</li>
    <li>kdePackages.falkon</li>
    <li>kdePackages.falkon.debug</li>
    <li>kdePackages.falkon.dev</li>
    <li>kdePackages.falkon.devtools</li>
    <li>kdePackages.grantlee-editor</li>
    <li>kdePackages.grantlee-editor.debug</li>
    <li>kdePackages.grantlee-editor.dev</li>
    <li>kdePackages.grantlee-editor.devtools</li>
    <li>kdePackages.gwenview</li>
    <li>kdePackages.gwenview.debug</li>
    <li>kdePackages.gwenview.dev</li>
    <li>kdePackages.gwenview.devtools</li>
    <li>kdePackages.incidenceeditor</li>
    <li>kdePackages.incidenceeditor.debug</li>
    <li>kdePackages.incidenceeditor.dev</li>
    <li>kdePackages.incidenceeditor.devtools</li>
    <li>kdePackages.kaccounts-integration</li>
    <li>kdePackages.kaccounts-integration.debug</li>
    <li>kdePackages.kaccounts-integration.dev</li>
    <li>kdePackages.kaccounts-integration.devtools</li>
    <li>kdePackages.kaccounts-providers</li>
    <li>kdePackages.kaccounts-providers.debug</li>
    <li>kdePackages.kaccounts-providers.dev</li>
    <li>kdePackages.kaccounts-providers.devtools</li>
    <li>kdePackages.kaddressbook</li>
    <li>kdePackages.kaddressbook.debug</li>
    <li>kdePackages.kaddressbook.dev</li>
    <li>kdePackages.kaddressbook.devtools</li>
    <li>kdePackages.kalarm</li>
    <li>kdePackages.kalarm.debug</li>
    <li>kdePackages.kalarm.dev</li>
    <li>kdePackages.kalarm.devtools</li>
    <li>kdePackages.kdenlive</li>
    <li>kdePackages.kdenlive.debug</li>
    <li>kdePackages.kdenlive.dev</li>
    <li>kdePackages.kdenlive.devtools</li>
    <li>kdePackages.kdepim-addons</li>
    <li>kdePackages.kdepim-addons.debug</li>
    <li>kdePackages.kdepim-addons.dev</li>
    <li>kdePackages.kdepim-addons.devtools</li>
    <li>kdePackages.kdepim-runtime</li>
    <li>kdePackages.kdepim-runtime.debug</li>
    <li>kdePackages.kdepim-runtime.dev</li>
    <li>kdePackages.kdepim-runtime.devtools</li>
    <li>kdePackages.kgpg</li>
    <li>kdePackages.kgpg.debug</li>
    <li>kdePackages.kgpg.dev</li>
    <li>kdePackages.kgpg.devtools</li>
    <li>kdePackages.kio-gdrive</li>
    <li>kdePackages.kio-gdrive.debug</li>
    <li>kdePackages.kio-gdrive.dev</li>
    <li>kdePackages.kio-gdrive.devtools</li>
    <li>kdePackages.kleopatra</li>
    <li>kdePackages.kleopatra.debug</li>
    <li>kdePackages.kleopatra.dev</li>
    <li>kdePackages.kleopatra.devtools</li>
    <li>kdePackages.kmail</li>
    <li>kdePackages.kmail-account-wizard</li>
    <li>kdePackages.kmail-account-wizard.debug</li>
    <li>kdePackages.kmail-account-wizard.dev</li>
    <li>kdePackages.kmail-account-wizard.devtools</li>
    <li>kdePackages.kmail.debug</li>
    <li>kdePackages.kmail.dev</li>
    <li>kdePackages.kmail.devtools</li>
    <li>kdePackages.knotes</li>
    <li>kdePackages.knotes.debug</li>
    <li>kdePackages.knotes.dev</li>
    <li>kdePackages.knotes.devtools</li>
    <li>kdePackages.koko</li>
    <li>kdePackages.koko.debug</li>
    <li>kdePackages.koko.dev</li>
    <li>kdePackages.koko.devtools</li>
    <li>kdePackages.kontact</li>
    <li>kdePackages.kontact.debug</li>
    <li>kdePackages.kontact.dev</li>
    <li>kdePackages.kontact.devtools</li>
    <li>kdePackages.korganizer</li>
    <li>kdePackages.korganizer.debug</li>
    <li>kdePackages.korganizer.dev</li>
    <li>kdePackages.korganizer.devtools</li>
    <li>kdePackages.libgravatar</li>
    <li>kdePackages.libgravatar.debug</li>
    <li>kdePackages.libgravatar.dev</li>
    <li>kdePackages.libgravatar.devtools</li>
    <li>kdePackages.libksieve</li>
    <li>kdePackages.libksieve.debug</li>
    <li>kdePackages.libksieve.dev</li>
    <li>kdePackages.libksieve.devtools</li>
    <li>kdePackages.mailcommon</li>
    <li>kdePackages.mailcommon.debug</li>
    <li>kdePackages.mailcommon.dev</li>
    <li>kdePackages.mailcommon.devtools</li>
    <li>kdePackages.mailimporter</li>
    <li>kdePackages.mailimporter.debug</li>
    <li>kdePackages.mailimporter.dev</li>
    <li>kdePackages.mailimporter.devtools</li>
    <li>kdePackages.mbox-importer</li>
    <li>kdePackages.mbox-importer.debug</li>
    <li>kdePackages.mbox-importer.dev</li>
    <li>kdePackages.mbox-importer.devtools</li>
    <li>kdePackages.merkuro</li>
    <li>kdePackages.merkuro.debug</li>
    <li>kdePackages.merkuro.dev</li>
    <li>kdePackages.merkuro.devtools</li>
    <li>kdePackages.messagelib</li>
    <li>kdePackages.messagelib.debug</li>
    <li>kdePackages.messagelib.dev</li>
    <li>kdePackages.messagelib.devtools</li>
    <li>kdePackages.okular</li>
    <li>kdePackages.okular.debug</li>
    <li>kdePackages.okular.dev</li>
    <li>kdePackages.okular.devtools</li>
    <li>kdePackages.pim-data-exporter</li>
    <li>kdePackages.pim-data-exporter.debug</li>
    <li>kdePackages.pim-data-exporter.dev</li>
    <li>kdePackages.pim-data-exporter.devtools</li>
    <li>kdePackages.pim-sieve-editor</li>
    <li>kdePackages.pim-sieve-editor.debug</li>
    <li>kdePackages.pim-sieve-editor.dev</li>
    <li>kdePackages.pim-sieve-editor.devtools</li>
    <li>kdePackages.pimcommon</li>
    <li>kdePackages.pimcommon.debug</li>
    <li>kdePackages.pimcommon.dev</li>
    <li>kdePackages.pimcommon.devtools</li>
    <li>kdePackages.plasma-browser-integration</li>
    <li>kdePackages.plasma-browser-integration.debug</li>
    <li>kdePackages.plasma-browser-integration.dev</li>
    <li>kdePackages.plasma-browser-integration.devtools</li>
    <li>kdePackages.plasma-desktop</li>
    <li>kdePackages.plasma-desktop.debug</li>
    <li>kdePackages.plasma-desktop.dev</li>
    <li>kdePackages.plasma-desktop.devtools</li>
    <li>kdePackages.plasmatube</li>
    <li>kdePackages.plasmatube.debug</li>
    <li>kdePackages.plasmatube.dev</li>
    <li>kdePackages.plasmatube.devtools</li>
    <li>kdePackages.purpose</li>
    <li>kdePackages.purpose.debug</li>
    <li>kdePackages.purpose.dev</li>
    <li>kdePackages.purpose.devtools</li>
    <li>kdePackages.skanpage</li>
    <li>kdePackages.skanpage.debug</li>
    <li>kdePackages.skanpage.dev</li>
    <li>kdePackages.skanpage.devtools</li>
    <li>kdePackages.spectacle</li>
    <li>kdePackages.spectacle.debug</li>
    <li>kdePackages.spectacle.dev</li>
    <li>kdePackages.spectacle.devtools</li>
    <li>kdePackages.tokodon</li>
    <li>kdePackages.tokodon.debug</li>
    <li>kdePackages.tokodon.dev</li>
    <li>kdePackages.tokodon.devtools</li>
    <li>kdePackages.zanshin</li>
    <li>kdePackages.zanshin.debug</li>
    <li>kdePackages.zanshin.dev</li>
    <li>kdePackages.zanshin.devtools</li>
    <li>kile</li>
    <li>kmymoney</li>
    <li>kphotoalbum</li>
    <li>latte-dock</li>
    <li>libaccounts-glib</li>
    <li>libaccounts-glib.dev</li>
    <li>libaccounts-glib.devdoc</li>
    <li>libaccounts-glib.py</li>
    <li>libsForQt5.accounts-qml-module (plasma5Packages.accounts-qml-module)</li>
    <li>libsForQt5.accounts-qt (plasma5Packages.accounts-qt)</li>
    <li>libsForQt5.akonadi (plasma5Packages.akonadi)</li>
    <li>libsForQt5.akonadi-calendar (plasma5Packages.akonadi-calendar)</li>
    <li>libsForQt5.akonadi-calendar-tools (plasma5Packages.akonadi-calendar-tools)</li>
    <li>libsForQt5.akonadi-calendar-tools.dev (plasma5Packages.akonadi-calendar-tools.dev)</li>
    <li>libsForQt5.akonadi-calendar.dev (plasma5Packages.akonadi-calendar.dev)</li>
    <li>libsForQt5.akonadi-contacts (plasma5Packages.akonadi-contacts)</li>
    <li>libsForQt5.akonadi-contacts.dev (plasma5Packages.akonadi-contacts.dev)</li>
    <li>libsForQt5.akonadi-import-wizard (plasma5Packages.akonadi-import-wizard)</li>
    <li>libsForQt5.akonadi-import-wizard.dev (plasma5Packages.akonadi-import-wizard.dev)</li>
    <li>libsForQt5.akonadi-mime (plasma5Packages.akonadi-mime)</li>
    <li>libsForQt5.akonadi-mime.dev (plasma5Packages.akonadi-mime.dev)</li>
    <li>libsForQt5.akonadi-notes (plasma5Packages.akonadi-notes)</li>
    <li>libsForQt5.akonadi-notes.dev (plasma5Packages.akonadi-notes.dev)</li>
    <li>libsForQt5.akonadi-search (plasma5Packages.akonadi-search)</li>
    <li>libsForQt5.akonadi-search.dev (plasma5Packages.akonadi-search.dev)</li>
    <li>libsForQt5.akonadi.dev (plasma5Packages.akonadi.dev)</li>
    <li>libsForQt5.akonadiconsole (plasma5Packages.akonadiconsole)</li>
    <li>libsForQt5.akregator (plasma5Packages.akregator)</li>
    <li>libsForQt5.akregator.dev (plasma5Packages.akregator.dev)</li>
    <li>libsForQt5.angelfish (plasma5Packages.angelfish)</li>
    <li>libsForQt5.audiotube (plasma5Packages.audiotube)</li>
    <li>libsForQt5.calendarsupport (plasma5Packages.calendarsupport)</li>
    <li>libsForQt5.calendarsupport.dev (plasma5Packages.calendarsupport.dev)</li>
    <li>libsForQt5.discover (plasma5Packages.discover)</li>
    <li>libsForQt5.eventviews (plasma5Packages.eventviews)</li>
    <li>libsForQt5.eventviews.dev (plasma5Packages.eventviews.dev)</li>
    <li>libsForQt5.falkon (plasma5Packages.falkon)</li>
    <li>libsForQt5.gwenview (plasma5Packages.gwenview)</li>
    <li>libsForQt5.incidenceeditor (plasma5Packages.incidenceeditor)</li>
    <li>libsForQt5.incidenceeditor.dev (plasma5Packages.incidenceeditor.dev)</li>
    <li>libsForQt5.kaccounts-integration (plasma5Packages.kaccounts-integration)</li>
    <li>libsForQt5.kaccounts-providers (plasma5Packages.kaccounts-providers)</li>
    <li>libsForQt5.kaddressbook (plasma5Packages.kaddressbook)</li>
    <li>libsForQt5.kalarm (plasma5Packages.kalarm)</li>
    <li>libsForQt5.kamoso (plasma5Packages.kamoso)</li>
    <li>libsForQt5.kdenlive (plasma5Packages.kdenlive)</li>
    <li>libsForQt5.kdepim-addons (plasma5Packages.kdepim-addons)</li>
    <li>libsForQt5.kdepim-runtime (plasma5Packages.kdepim-runtime)</li>
    <li>libsForQt5.kdeplasma-addons (plasma5Packages.kdeplasma-addons)</li>
    <li>libsForQt5.kdev-php (plasma5Packages.kdev-php)</li>
    <li>libsForQt5.kdev-python (plasma5Packages.kdev-python)</li>
    <li>libsForQt5.kdevelop (plasma5Packages.kdevelop)</li>
    <li>libsForQt5.kdevelop-unwrapped (plasma5Packages.kdevelop-unwrapped)</li>
    <li>libsForQt5.kgpg (plasma5Packages.kgpg)</li>
    <li>libsForQt5.kio-gdrive (plasma5Packages.kio-gdrive)</li>
    <li>libsForQt5.kmail (plasma5Packages.kmail)</li>
    <li>libsForQt5.kmail-account-wizard (plasma5Packages.kmail-account-wizard)</li>
    <li>libsForQt5.kmail.doc (plasma5Packages.kmail.doc)</li>
    <li>libsForQt5.kmailtransport (plasma5Packages.kmailtransport)</li>
    <li>libsForQt5.kmailtransport.dev (plasma5Packages.kmailtransport.dev)</li>
    <li>libsForQt5.knotes (plasma5Packages.knotes)</li>
    <li>libsForQt5.koko (plasma5Packages.koko)</li>
    <li>libsForQt5.kontact (plasma5Packages.kontact)</li>
    <li>libsForQt5.korganizer (plasma5Packages.korganizer)</li>
    <li>libsForQt5.kpurpose (plasma5Packages.kpurpose)</li>
    <li>libsForQt5.kpurpose.bin (plasma5Packages.kpurpose.bin)</li>
    <li>libsForQt5.kpurpose.dev (plasma5Packages.kpurpose.dev)</li>
    <li>libsForQt5.libgravatar (plasma5Packages.libgravatar)</li>
    <li>libsForQt5.libgravatar.dev (plasma5Packages.libgravatar.dev)</li>
    <li>libsForQt5.libkdepim (plasma5Packages.libkdepim)</li>
    <li>libsForQt5.libksieve (plasma5Packages.libksieve)</li>
    <li>libsForQt5.libksieve.dev (plasma5Packages.libksieve.dev)</li>
    <li>libsForQt5.mailcommon (plasma5Packages.mailcommon)</li>
    <li>libsForQt5.mailcommon.dev (plasma5Packages.mailcommon.dev)</li>
    <li>libsForQt5.mailimporter (plasma5Packages.mailimporter)</li>
    <li>libsForQt5.mauikit-calendar (plasma5Packages.mauikit-calendar)</li>
    <li>libsForQt5.mbox-importer (plasma5Packages.mbox-importer)</li>
    <li>libsForQt5.merkuro (plasma5Packages.merkuro)</li>
    <li>libsForQt5.messagelib (plasma5Packages.messagelib)</li>
    <li>libsForQt5.messagelib.dev (plasma5Packages.messagelib.dev)</li>
    <li>libsForQt5.okular (plasma5Packages.okular)</li>
    <li>libsForQt5.pim-data-exporter (plasma5Packages.pim-data-exporter)</li>
    <li>libsForQt5.pim-sieve-editor (plasma5Packages.pim-sieve-editor)</li>
    <li>libsForQt5.pimcommon (plasma5Packages.pimcommon)</li>
    <li>libsForQt5.pimcommon.dev (plasma5Packages.pimcommon.dev)</li>
    <li>libsForQt5.plasma-browser-integration (plasma5Packages.plasma-browser-integration)</li>
    <li>libsForQt5.plasma-desktop (plasma5Packages.plasma-desktop)</li>
    <li>libsForQt5.plasma-welcome (plasma5Packages.plasma-welcome)</li>
    <li>libsForQt5.skanpage (plasma5Packages.skanpage)</li>
    <li>libsForQt5.spectacle (plasma5Packages.spectacle)</li>
    <li>libsForQt5.tokodon (plasma5Packages.tokodon)</li>
    <li>libsForQt5.zanshin (plasma5Packages.zanshin)</li>
    <li>lomiri.lomiri</li>
    <li>lomiri.lomiri-session</li>
    <li>lomiri.lomiri-system-settings</li>
    <li>lomiri.lomiri-system-settings-security-privacy</li>
    <li>lomiri.lomiri-system-settings-unwrapped</li>
    <li>lomiri.lomiri-system-settings-unwrapped.dev</li>
    <li>peruse</li>
  </ul>
</details>

**Comment by zowoq** [comment]
These `passthru.updateScript`s don't seem to work which has broken part of the `nixpkgs-update` bot which tries to evaluate all of the `updateScript`s.

```
$ nix-shell maintainers/scripts/update.nix --argstr path libaccounts-glib
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nixpkgs-update-script'
         whose name attribute is located at /home/zowoq/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'shellHook' of derivation 'nixpkgs-update-script'

         at /home/zowoq/nixpkgs/maintainers/scripts/update.nix:223:3:

          222|   '';
          223|   shellHook = ''
             |   ^
          224|     unset shellHook # do not contaminate nested shells

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called with unexpected argument 'rev'

       at /home/zowoq/nixpkgs/pkgs/common-updater/git-updater.nix:6:1:

            5|
            6| { pname ? null
             | ^
            7| , version ? null
```
```
$ nix-shell maintainers/scripts/update.nix --argstr path kdePackages.accounts-qt
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nixpkgs-update-script'
         whose name attribute is located at /home/zowoq/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'shellHook' of derivation 'nixpkgs-update-script'

         at /home/zowoq/nixpkgs/maintainers/scripts/update.nix:223:3:

          222|   '';
          223|   shellHook = ''
             |   ^
          224|     unset shellHook # do not contaminate nested shells

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called with unexpected argument 'rev'

       at /home/zowoq/nixpkgs/pkgs/common-updater/git-updater.nix:6:1:

            5|
            6| { pname ? null
             | ^
            7| , version ? null
```

**Comment by jopejoe1** [comment]
should have ben `rev-prefix` and not `rev` will send a follow up pr.

**Pull request merged**
