### PR TITLE
Upgrade Rust compiler

### PR DESCRIPTION
**Pull request by woehr**
This pull request:
- abstracts common parts of rustc derivations into a function
- consolidates patch necessary for rust to compile on nix
- racer still compiles and runs, albeit specifically against alpha1 so nothing should have changed
- updated master to rust head as of March 1
- add Rust alpha2

All three versions of the rust compiler compile on x86-64. I am setting up an x86 vm now to verify things still compile on it.

### CODE REVIEW

**Comment by jagajaga** [comment]
Wow! I'll check this later. But seems to be cool. 
Btw, please rebase and remove merge commit :)

**Comment by jagajaga** [comment]
Cc @madjar check this too

**Comment by madjar** [comment]
That is neat! I was thinking about dropping all versions but one once we reach 1.0.0, but with the train systems, we way want to always provide two or more concurrent versions.

:+1:

**Comment by woehr** [comment]
This pull request has a single commit now. Everything built successfully on my x86 vm last night too.

Let me know if there is anything else that needs to be done.

**Comment by madjar** [comment]
Thanks @woehr 

Travis says there in an evaluation in travis (in racer, to be precise). I'll take a look on my computer at work tomorrow.

**Comment by woehr** [comment]
I've fixed this and will push a new commit once I confirm everything is building. The problem was that I was building racer locally, and not racerRust. Oops. :grimacing:

**Comment by woehr** [comment]
I think I've finally fixed everything. So, to summarize:
- The git version of racerRust that was in nixpkgs would build with alpha (a downgrade of the compiler version) but not alpha2 (or master)
- Options were add the "old" master a833337 or upgrade racer
- Updated racer to latest commit (Feb 28) which builds with the new rustcMaster
- Rust broke cargo (by making crates starting with hyphens illegal)
- Updated cargoSnapshot
- Needed to change installPhase of cargoSnapshot the bin, etc, lib, share directories were moved into a cargo directory
- Updated racerRust now builds with (new) rustcMaster.

Yay!

**Comment by madjar** [comment]
Wow, that's quite a lot of work! Thanks for all that :+1:

**Pull request merged**
