### PR TITLE
nixos/zrepl: note about systemd unit, add snapshot test

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

###### Description of changes

- Note that pkgs.zrepl installs the upstream unit, and the unit here only defines overrides
- Add a NixOS test to verify working zrepl snapshots
- Volunteer myself as an additional maintainer of zrepl

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

/cc @cole-h @danderson

### CODE REVIEW

**Comment by mdlayher** [comment]
@GrahamcOfBorg test zrepl

**Comment by mdlayher** [comment]
@GrahamcOfBorg test zrepl

**Comment by mdlayher** [comment]
@cole-h my apologies, I had a misunderstanding of how this all worked. The current configuration adapts the upstream unit in the package file, and only overrides are defined in the module here.

I note on my server that the upstream unit is present when I `systemctl cat zrepl`. It wouldn't be a bad idea to revisit some of the TODOs and such, but for the time being my immediate concerns about hardening the unit file are already resolved.

I'll keep this PR around for the new note and tests.

**Review by cole-h — APPROVED** [review]
It's all good, I always forget about `systemd.packages` too haha (and I'm the one who wrote the module!).

Looks good to me -- I'll merge it once I make it to my computer.

**Pull request merged**
