### PR TITLE
tmuxPlugins.catppuccin: unstable-2022-12-14 -> unstable-2023-04-03

### LINKED ISSUE #229075: Update request: tmuxplugin-catppuccin-unstable 2022-12-14 → 2023-04-03
- Package name: tmuxplugin-catppuccin-unstable
- Latest released version: 2023-04-03
- Current version on the unstable channel: 2022-12-14
- Current version on the stable/release channel: -
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@jnsgruk

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by jnsgruk**
###### Description of changes

Update version of tmux catppuccin plugin

Fixes #229075

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 229131` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tmuxPlugins.catppuccin</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]
The diff looks fine.

**Review by figsoda — APPROVED** [review]

**Comment by medv** [comment]
Looks like some nice updates came along allowing us to strip the icons. If you guys are too busy then I can try, but will have to read up on the contrib process first. The change itself looks straightforward though, get some hashes and done?

**Comment by jnsgruk** [comment]
Yep happy to give it a test if you beat me to it, or I'll try and get something together on Mon

**Pull request merged**
