### PR TITLE
osu-lazer-bin: 2023.914.0 -> 2023.924.1

### PR DESCRIPTION
**Pull request by spacefault**
This commit upgrades the osu-lazer-bin package from version 2023.914.0 to 2023.924.1. The changelog and release notes for this upgrade can be viewed here:
https://github.com/ppy/osu/releases/tag/2023.924.1

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [X] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stepbrobd** [comment]
`nixpkgs-review pr 257401` failed on aarch64-darwin:

```shell
$ nixpkgs-review pr 257401
error: hash mismatch in fixed-output derivation '/nix/store/lsphpc3q8n9jdcrrg94wxksgi014i0vc-source.drv':
         specified: sha256-4XpciZ+Wfp5aeeWvs1bILD+1pU+bsrrDfzjt0/rEEH0=
            got:    sha256-ZCTKVad1XArHxTa9nZfrSf6xFd0TNwryw9v+Doehurg=
note: keeping build directory '/private/tmp/nix-build-source.drv-1'
error: 1 dependencies of derivation '/nix/store/dvczphwsra1vcriyxj60qyhly9h4dpbq-osu-lazer-bin-2023.924.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ii74qccayqj10m00jdsb8vcv0nakwsmi-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/257401

1 package failed to build:
osu-lazer-bin
```

Could you try reverting this commit and update again with `update-bin.sh`? `osu-lazer-bin` for darwin machines uses `fetchzip` so they're using [recursive hash](https://github.com/NixOS/nixpkgs/blob/ef8f77d411558688ffa2ec7a11671139f50a7913/pkgs/games/osu-lazer/update-bin.sh#L32C1-L33C1).

**Comment by spacefault** [comment]
@stepbrobd 

Hello!

I have used the script and changed the proper hashes this time. Originally I would manually edit the hashes with the `nix-prefetch-url` command, but from now on I will use these scripts. Also, I apologize for the very long response time. I didn't have access to my computer. For some reason GitHub closed my pull request, but I have reopened it and everything looks fine.

The issues should be resolved now. Could you please take a look at it?
Also I apologize for the original mistake, I am still very new to contributing to nixpkgs.

\- spacefault

**Comment by stepbrobd** [comment]
<details>
<summary>
Result of `nixpkgs-review pr 257401` on aarch64-darwin:

</summary>

- 1 package built

  - osu-lazer-bin

</details>

**Comment by stepbrobd** [comment]
Thanks for the contribution!
Can you squash the three commits into one? It's all good otherwise.

**Comment by spacefault** [comment]
Hello,

Is there a way I can do this through the GitHub website? Or would I have to use Git commands for that.

\- spacefault

**Review by stepbrobd — APPROVED** [review]

**Comment by spacefault** [comment]
Thank you for approving!

**Review by stepbrobd — APPROVED** [review]

**Comment by spacefault** [comment]
Could you please tell me who I should contact to get this merged to the master branch? Also, would it be okay if I added myself as a maintainer in the .nix file?

Once again, thank you for approving the request!

\- spacefault

**Comment by stepbrobd** [comment]
It usually takes couple hours to a week or so for a PR to be merged to master.

To add yourself as a maintainer, see guidelines here:
- https://nixos.org/manual/nixpkgs/stable/#var-meta-maintainers
- https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 257401` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>osu-lazer-bin</li>
  </ul>
</details>

**Pull request merged**
