### PR TITLE
python312: 3.12.0b4 -> 3.12.0rc2; python38: 3.8.17 -> 3.7.18; python39: 3.9.17 -> 3.9.18

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

- python312
https://docs.python.org/3.12/whatsnew/changelog.html#python-3-12-0rc2
Fixes: https://github.com/advisories/GHSA-4j9r-82g6-9mj3

- python38
https://docs.python.org/release/3.8.18/whatsnew/changelog.html
Fixes: https://github.com/advisories/GHSA-4j9r-82g6-9mj3

- python39
https://docs.python.org/release/3.9.18/whatsnew/changelog.html
Fixes: https://github.com/advisories/GHSA-4j9r-82g6-9mj3

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
`nixpkgs-review` reveals no new failures, macos 10.15

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 254221` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>cjdns</li>
    <li>ntfy</li>
    <li>ntfy.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>easyabc</li>
    <li>friture</li>
    <li>friture.dist</li>
    <li>google-cloud-sdk-gce</li>
    <li>klipper-firmware</li>
    <li>klipper-flash</li>
    <li>transifex-client</li>
    <li>transifex-client.dist</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>blackmagic</li>
    <li>crossfire-server</li>
    <li>edgetx</li>
    <li>gcc-arm-embedded</li>
    <li>gcc-arm-embedded-11</li>
    <li>google-compute-engine</li>
    <li>google-compute-engine.dist</li>
    <li>libsForQt5.kdev-python</li>
    <li>monoid</li>
    <li>opentx</li>
    <li>osmscout-server</li>
    <li>proxmark3</li>
    <li>python312</li>
    <li>python312.debug</li>
    <li>python38</li>
    <li>python38.debug</li>
    <li>python38Full</li>
    <li>python38Full.debug</li>
    <li>python39</li>
    <li>python39.debug</li>
    <li>python39Full</li>
    <li>python39Full.debug</li>
    <li>qmk</li>
    <li>qmk.dist</li>
    <li>spidermonkey_78</li>
    <li>spidermonkey_78.dev</li>
    <li>taler-exchange</li>
    <li>taler-merchant</li>
    <li>valhalla</li>
    <li>zeroad</li>
    <li>zeroadPackages.zeroad-unwrapped</li>
  </ul>
</details>

**Comment by natsukium** [comment]
@mweinelt I'm sorry to bother you, but could you please review this PR?

**Comment by mweinelt** [comment]
@ofborg build python38.tests
@ofborg build python39.tests

**Pull request merged**
