### PR TITLE
Update python Werkzeug to 0.10.4

### PR DESCRIPTION
**Pull request by mitchty**
Update python Werkzeug package version to 0.10.4

### CODE REVIEW

**Comment by mitchty** [comment]
Looking at travis' logfile the build timed out, not sure how to force it to retry.

**Comment by FRidh** [comment]
Could you run `nox-review pr 11209` to test whether dependents still work after this change?

**Comment by mitchty** [comment]
@FRidh on OS X didn't get too far with it, but that is likely the OS X side of things really.
https://gist.github.com/886b88087774ec2db7ba

I'll try when I get home tonight on nixos to see if anything changes.

**Comment by domenkozar** [comment]
ping @mitchty

**Comment by mitchty** [comment]
Still building, my nixos laptop is a chromebook, not the speediest of systems. Not sure how to pass along -j or --cores via nox-review but that would speed it up a fair bit as it seems to be rebuilding the world.

**Comment by garbas** [comment]
@mitchty tnx

**Pull request closed without merging**
