### PR TITLE
nixos/wireless: reimplement secrets using ext_password_backend

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Description of changes

This replaces the current implementation (splicing the secrets into the
configuration file using environment variavles) with the new built-in
mechanism `ext_password_backend`.

With some minor syntax changes, it works exactly as before, except the
heavy lifting is done by wpa_supplicant and probably less error-prone.

###### Things done

- [x] Tested via `nixosTests.wpa_supplicant`
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc: @lopsided98

### CODE REVIEW

**Review by pennae — COMMENTED** [review]
while testing these changes we've run into problems. it seems like wpa_supplicant will provide the password from the external file only to the highest priority block for each entry, i.e. the default settings of `fallbackToWPA2` is completely broken.

this is currently not usable at all, and it looks a lot like an upstream bug :(

**Comment by rnhmjoj** [comment]
I made this a draft to prevent accidental merges.

**Comment by lopsided98** [comment]
I found another upstream bug: the external password is not passed to the kernel if 4-way handshake offloading is enabled.

**Comment by lopsided98** [comment]
It doesn't work with WPA3 SAE passwords either.

I have written patches to fix both of these issues, which I'll try to get feedback on upstream:
* https://github.com/lopsided98/hostap/commit/023c17659786fe381312f154cf06663f1cb3607c
* https://github.com/lopsided98/hostap/commit/57e2d036cdb5e19166746cdfa17cf3f8863664a7

**Comment by lopsided98** [comment]
My patches have been accepted upstream. I wonder if @pennae's issue is a different bug, or was caused by the SAE issue I fixed.

**Comment by rnhmjoj** [comment]
I rebased this branch to the latest master. I tried to patch the current wpa_supplicant, but the patches don't apply cleanly and I don't have time to do a backport. So, unless someone does it, this will have to wait for version 2.11.

The good news is that now we have tests checking both WPA2 and WPA3: the tests will pass once wpa_supplicant bugs are fixed and this PR can be merged.

**Comment by dkwo** [comment]
@lopsided98 I tried your two patches (on void linux, on top of wpa_supplicant 2.10): I do get the error
```
wpa_supplicant[1815]: Line 34: failed to parse sae_password '[KEY DATA REMOVED]'.
wpa_supplicant[1815]: Line 34: failed to parse sae_password 'ext:pwd_cia'.
wpa_supplicant[1815]: Line 36: failed to parse network block.
wpa_supplicant[1815]: Failed to read or parse configuration
```
my config file contains
```
network={
	ssid="some-ssid"
	key_mgmt=SAE
	ieee80211w=2
	sae_password=ext:pwd_cia
```
and the file has a line `pwd_cia=the actual password without any quotations etc`. Do you think I'm missing some quotations or similar, or maybe certain characters in the password do not work with this method, or else?

**Comment by lopsided98** [comment]
I don't think it works with the `sae_password` option; you need to use the `psk` option even with WPA3.

**Comment by dkwo** [comment]
Thanks a lot, that works indeed.

**Comment by rnhmjoj** [comment]
2.11 is taking forever, for... reasons.

**Comment by rnhmjoj** [comment]
2.11 is Nixpkgs, I rebased and... it doesn't work.

**Comment by rnhmjoj** [comment]
I should have sorted everything out. If you could re-test with the latest rebase, it would be great.

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg test wpa_supplicant

**Comment by trofi** [comment]
I had a simple setup on one of my `NixOS` machines that run from `nixpkgs/master`:

1. `confignuration.nix` contained `networking.wireless.enable = true;`
2. `/etc/wpa_supplcant.conf` contained a single static network set up: `network={ssid=...,psk=...}`

Today after the reboot I found that my `wifi` is completely broken.

The contents of `/etc/wpa_supplicant.conf` is now just `pmf=1 bgscan="simple:30:-70:3600"` which fails to connect to any networks.

I suspect that commit 89eb93dc3ffda68535d6ee51a7825f1de31ae658 `nixos/wireless: link config to /etc by default` now clobbers user's config.

From what I can see:
- The contents of my original `/etc/wpa_supplicant.conf` just disappeared and booting to the previous generations would not get the `wifi` working. The file is not on dusk anymore.
- `nixos-rebuild switch` did not complain about potential data loss and generation of guaranteed to be invalid config (yes? or there are cases when this new config could work?)

Did I get it right? Or something else clobbered my config? If it's indeed the commit 89eb93dc3ffda68535d6ee51a7825f1de31ae658 is there a chance to get a failsafe assert to be added so that users would not lose their network setup after an upgrade?

**Comment by rnhmjoj** [comment]
> Did I get it right? Or something else clobbered my config? If it's indeed the commit https://github.com/NixOS/nixpkgs/commit/89eb93dc3ffda68535d6ee51a7825f1de31ae658

I changed the module to link the generated configuration to /etc/wpa_supplicant.conf, because otherwise the file is not easily accessible (you'd neet to look at the daemon argv, or inspect the systemd unit). That said, I have no idea what `nixos-rebuild switch` does if a file exists in place of a link it has to create. I just didn't think of this, sorry...

> /etc/wpa_supplicant.conf contained a single static network set up: network={ssid=...,psk=...}

Did that ever work at all? Were you manually starting the wpa_supplicant daemon? AFAIK, without `cfg.allowAuxiliaryImperativeNetworks` NixOS does not look at `/etc/wpa_supplicant.conf` at all.

>  is there a chance to get a failsafe assert to be added so that users would not lose their network setup after an upgrade?

I don't think so... at evaluation time I can't inspect the filesystem to assert the link would overwrite an existing file.
I guess I could create the link from the wpa_supplicant service, instead of using `environment.etc`, but this is more of an issue with the activation script. (if that's really what happened in your case)

**Comment by trofi** [comment]
> > Did I get it right? Or something else clobbered my config? If it's indeed the commit [89eb93d](https://github.com/NixOS/nixpkgs/commit/89eb93dc3ffda68535d6ee51a7825f1de31ae658)
> 
> I changed the module to link the generated configuration to /etc/wpa_supplicant.conf, because otherwise the file is not easily accessible (you'd need to look at the daemon argv, or inspect the systemd unit). That said, I have no idea what `nixos-rebuild switch` does if a file exists in place of a link it has to create. I just didn't think of this, sorry...
> 
> > /etc/wpa_supplicant.conf contained a single static network set up: network={ssid=...,psk=...}
> 
> Did that ever work at all? Were you manually starting the wpa_supplicant daemon? AFAIK, without `cfg.allowAuxiliaryImperativeNetworks` NixOS does not look at `/etc/wpa_supplicant.conf` at all.

No manual `wpa_supplicant` start. The setup worked fine for a few years.

I have another system that did not update yet. It looks like something is copying `/etc/wpa_supplicant.conf` to `/run/wpa_supplicant/wpa_supplicant.conf`:

```
$ systemctl status wpa_supplicant-wlp0s20f3.service
● wpa_supplicant-wlp0s20f3.service - WPA Supplicant instance for interface wlp0s20f3
     Loaded: loaded (/etc/systemd/system/wpa_supplicant-wlp0s20f3.service; enabled; preset: enabled)
     Active: active (running) since Wed 2024-08-07 23:47:17 BST; 1 month 11 days ago
   Main PID: 830 (wpa_supplicant)
        CPU: 8.382s
     CGroup: /system.slice/wpa_supplicant-wlp0s20f3.service
             └─830 wpa_supplicant -iwlp0s20f3 -s -u -Dnl80211,wext -c /run/wpa_supplicant/wpa_supplicant.conf
...
```

All network-relevant `configuration.nix` bits from this not yet updated machine:

```nix
  networking.wireless.enable = true;
  networking.wireless.interfaces = ["wlp0s20f3"];
  networking.useDHCP = false;
  networking.interfaces.wlp0s20f3.useDHCP = true;
```

`/etc/wpa_supplicant.conf` is a manually written local file with two networks defined.

**Comment by rnhmjoj** [comment]
Ah, you're right. The situation is quite messy because there are (were) three ways to configure wpa_supplicant: fully declaratively, mixed declarative/imperative and fully imperatively. The latter has been kind of unnecessary after `networking.wireless.allowAuxiliaryImperativeNetworks` was added, and that's why I forgot about it (also it was not being tested).

I think that commit should be reverted and this deprecated properly, not sure about how, exactly. About nixos overwriting your file, that's apparently how it works... yikes. This should be another issue, if there's not already one open.

**Comment by mrshmllow** [comment]
This appears to of broken `identity`, in other words you can only use secrets for `password`. I cant put wireless stuff in my config without exposing details id rather not

**Comment by ritiek** [comment]
> This appears to of broken `identity`, in other words you can only use secrets for `password`. I cant put wireless stuff in my config without exposing details id rather not

Do we have a resolution for this? I have a similar concern. I'd like to not publish my SSID.

**Comment by mrshmllow** [comment]
> > This appears to of broken `identity`, in other words you can only use secrets for `password`. I cant put wireless stuff in my config without exposing details id rather not
> 
> Do we have a resolution for this? I have a similar concern. I'd like to not publish my SSID.

the example usage mislead me. you can use the substitution for stuff that isn't a Password. However, I'm not sure about ssid. you might have to mkAfter the string to add something custom, not sure

**Comment by rnhmjoj** [comment]
Sorry, but `environmentFile` was never meant to substitute stuff other than secrets, even though it could. See [this](https://discourse.nixos.org/t/wifi-hide-email-identitiy-in-eduroam-config/52548/2?u=rnhmjoj) if want to hide SSIDs and other parts of the configuration.

**Comment by DCsunset** [comment]
I just discovered another issue using this new approach: when using `psk=ext:password` with `sae_password_id`, it failed to connect to the AP. But it works fine if I use `sae_password` with a string (without the external file).

This seems to be an upstream issue, but I just want to mention it here as the previous `environmentFile` approach works in such scenario (and it is a more general approach that is widely used in other modules too)

**Pull request merged**
