### PR TITLE
nixos/jellyfin: add options datadir, cachedir, logdir

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

Add options to specify the datadir, cachedir, and logdir options that Jellyfin takes as command-line parameters.

I removed some copy-pasted systemd options that can break things or cause unexpected behavior.

If you are running jellyfin on the same server that has sensitive information and jellyfin leaks that information that's not something you can blame on not enabling enough systemd options or not understanding how those options work.

If jellyfin breaks your system because it exhausts the space or inodes of /var/lib that is also not something that can be blamed on not enabling enough systemd options. That happens because someone didn't realized which options were significant and which options were security configuration theatre.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
> If you are running jellyfin on the same server that has sensitive information and jellyfin leaks that information that's not something you can blame on not enabling enough systemd options or not understanding how those options work.
> If jellyfin breaks your system because it exhausts the space or inodes of /var/lib that is also not something that can be blamed on not enabling enough systemd options. That happens because someone didn't realized which options were significant and which options were security configuration theatre.

I'm not sure what exactly you are referencing to, e.g. your personal experience or `PrivateUsers` or the `*Mode` + `UMask` options.

Though, please, if there can be constructive information from this snarky (?) comment, elaborate :P

**Comment by RaitoBezarius** [comment]
@ofborg test jellyfin

**Comment by RaitoBezarius** [comment]
I know you don't like it, but could you add `lib.mdDoc` on the options' descriptions please? Thank you!

**Comment by ehmry** [comment]
I'm moving

**Pull request closed without merging**
