### PR TITLE
Updating node packages and adding yaml-language-server

### PR DESCRIPTION
**Pull request by rycee**
##### Motivation for this change

Packaging [yaml-language-server](https://github.com/redhat-developer/yaml-language-server). Unfortunately this required first updating the node packages.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rycee** [comment]
nix-review result:

```
error: build of '/nix/store/s27xjzgf8vq8h7jisvqdny2z6bwyc9dv-env.drv' failed
1 package failed to build:
lumo

28 package built:
antora bitwarden-cli create-cycle-app dat emojione fast-cli gtop hueadm image_optim iosevka joplin lessc pulp python37Packages.jupyterhub python37Packages.jupyterhub-ldapauthenticator python37Packages.oauthenticator python38Packages.jupyterhub python38Packages.jupyterhub-ldapauthenticator python38Packages.oauthenticator sage sageWithDoc shout sloc styx thelounge triton twemoji-color-font wasm-text-gen
```

But apparently lumo already doesn't build.

**Comment by alyssais** [comment]
Is yaml-language-server a program? If so, it should be exposed in all-packages.nix.

**Comment by rycee** [comment]
@alyssais Good point, yes it provides a `yaml-language-server` executable. I've pushed a new version that adds it to `all-packages.nix`.

**Comment by AmandaCameron** [comment]
This'll need a rebase,  but from my understanding of the node stuff in nix, this looks straight-forward enough to merge? Not sure if there's someone who "owns" the node part of nixpkgs who should have been pinged for this?

Not sure if I'm using nix-review wrong or what, but I can't verify if the binary actually runs (and @rycee didn't tick that box)

**Comment by rycee** [comment]
Heh, I entirely forgot about this. I've been using the binary for some time in my own branch and it works well. I'll try a rebase and merge if it builds ok.

**Comment by rycee** [comment]
Rebased to master in 8883371fd116b7a56d22b47ab95e62b41503d756.

**Pull request merged**
