### PR TITLE
staging-next 2023-02-15

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/214010

- - - 
##### Mass breakages
(will be edited in future)
- [x] `python3Packages.aiohttp` fail tests
  On `*-linux` at least.  [aarch64 log](https://hydra.nixos.org/log/sgg5yj8nlyy46qghd03ysymnm7473pwl-python3.10-aiohttp-3.8.3.drv); I did x86_64 locally with the same three tests reported.
  https://github.com/NixOS/nixpkgs/pull/216499/commits/720a248b4479e7748e942fe1b28d3684bd5baaff
- [x] `libdeflate` on `x86_64-darwin` (only)
  https://github.com/NixOS/nixpkgs/pull/216181#issuecomment-1435510711
  #217067
- [x] `ruby_3_0` on `*-darwin` (only)
  [aarch64](https://hydra.nixos.org/build/209780455), same for x86_64 locally.
  #217024
- [x] `ibus` (linux)
  https://hydra.nixos.org/build/209900957  https://hydra.nixos.org/build/209896970
  maintainers: `@ttuegel` `@yanalunaterra`
- [x] `python3Packages.uvloop` on x86_64-darwin (some test failure)
  https://hydra.nixos.org/build/209939576
- [x] `haskellPackages.gi-harfbuzz` ~waiting for upstream~:
  https://github.com/haskell-gi/haskell-gi/issues/396#issuecomment-1439131270
  https://github.com/NixOS/nixpkgs/pull/217111#issuecomment-1445305991
  
Current regression list (detailed):
  https://hydra.nixos.org/eval/1791068?compare=1791059#tabs-now-fail

### CODE REVIEW

**Comment by vcunat** [comment]
Mass breakages (will be edited in future):
- [ ] `python3Packages.aiohttp` fail tests
  On `*-linux` at least.  [aarch64 log](https://hydra.nixos.org/log/sgg5yj8nlyy46qghd03ysymnm7473pwl-python3.10-aiohttp-3.8.3.drv); I did x86_64 locally with the same three tests reported.

**Comment by vcunat** [comment]
Oh, `.aiohttp` has a maintainer: @dotlambda ⬆️

**Comment by alyssais** [comment]
@NickCao @trofi 11b095e8805aa123a4d77a5e706bebaf86622879 (master) and fa0633e7faac4be522850c55854683db71ef6d8f (staging-next) produce a merge conflict.  I could just resolve it, and we keep both changes, but since they both seem to be different solutions for the same issue, maybe we only need to keep one?

**Comment by trofi** [comment]
> @NickCao @trofi [11b095e](https://github.com/NixOS/nixpkgs/commit/11b095e8805aa123a4d77a5e706bebaf86622879) (master) and [fa0633e](https://github.com/NixOS/nixpkgs/commit/fa0633e7faac4be522850c55854683db71ef6d8f) (staging-next) produce a merge conflict. I could just resolve it, and we keep both changes, but since they both seem to be different solutions for the same issue, maybe we only need to keep one?

Yeah, I suggest dropping/reverting the `master` change in `staging-next`.

**Comment by NickCao** [comment]
Just revert my commit on master, the one in staging-next looks better.

**Comment by gador** [comment]
> Mass breakages (will be edited in future):
> 
>     * [ ]  `python3Packages.aiohttp` fail tests
>       On `*-linux` at least.  [aarch64 log](https://hydra.nixos.org/log/sgg5yj8nlyy46qghd03ysymnm7473pwl-python3.10-aiohttp-3.8.3.drv); I did x86_64 locally with the same three tests reported.
> 
>     * [ ]  `libdeflate` on `x86_64-darwin` (only)
>       [libdeflate: 1.8 -> 1.17 #216181 (comment)](https://github.com/NixOS/nixpkgs/pull/216181#issuecomment-1435510711)
> 
>     * [ ]  `ruby_3_0` on `*-darwin` (only)
>       [aarch64](https://hydra.nixos.org/build/209780455), same for x86_64 locally.

@dotlambda  The build of `python3Packages.aiohttp`fails after the `dnspython` upgrade. I haven't been able to figure out why, though

**Comment by alyssais** [comment]
Alright, reverted https://github.com/NixOS/nixpkgs/commit/11b095e8805aa123a4d77a5e706bebaf86622879 but kept 463ab8deaa17d333be2ff7c61bea4e8e664e71cb.

**Comment by mweinelt** [comment]
> * `ruby_3_0` on `*-darwin` (only)
>       [aarch64](https://hydra.nixos.org/build/209780455), same for x86_64 locally.

cc @marsam

**Comment by marsam** [comment]
Fixed `ruby_3_0` in https://github.com/NixOS/nixpkgs/pull/217024

**Comment by fabianhjr** [comment]
Working on an ibus fix

**Comment by fabianhjr** [comment]
Challenge failed :C

If someone else wants to give fixing ibus a try it would be appreciated.

**Comment by ttuegel** [comment]
I'm having a look at ibus.

**Comment by vcunat** [comment]
So, I decided to move the checklist with biggest regressions to the first post and edit in-place, because of practical issues with the UI (like visibility).

We still have at least a few hundred regressed builds.  Apart from the checklist, much of them are various individual python failures, presumably due to pythonPackages updates.

**Comment by mweinelt** [comment]
> * `python3Packages.uvloop` on x86_64-darwin (some test failure)
>       [hydra.nixos.org/build/209939576](https://hydra.nixos.org/build/209939576)

Retried once more on hydra and it built just fine. :disappointed:

**Comment by vcunat** [comment]
Eww, that's really lots of retries, but OK for this iteration I guess.

**Comment by mweinelt** [comment]
Even worse, the tests segfaulted for me via rosetta on the darwin community builder. I have no energy to dig into this right now.

**Pull request merged**
