### PR TITLE
mono: 5 -> 6

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

```
6 packages marked as broken and skipped:
dotnetPackages.ExtCore gdata-sharp monodevelop python38Packages.pythonnet python39Packages.pythonnet ue4

20 packages failed to build:
appindicator-sharp bless dotnetPackages.FSharpAutoComplete dotnetPackages.MonoAddins dotnetPackages.Projekt gio-sharp gnome-sharp gtk-sharp-2_0 gtk-sharp-3_0 gtk-sharp-beans hyena mono-addins notify-sharp pdfmod pinta snapdragon-profiler sparkleshare supertux-editor tomboy webkit2-sharp

135 packages built:
avrdudess boogie bottles btcpayserver ckan convchain dafny dbus-sharp-1_0 dbus-sharp-glib-1_0 dbus-sharp-glib-2_0 dotnetPackages.Autofac dotnetPackages.Deedle dotnetPackages.ExcelDna dotnetPackages.ExcelDnaRegistration dotnetPackages.FSharpCompilerCodeDom dotnetPackages.FSharpCompilerService dotnetPackages.FSharpCompilerTools dotnetPackages.FSharpCore302 dotnetPackages.FSharpCore3125 dotnetPackages.FSharpCore4001 dotnetPackages.FSharpCore4117 dotnetPackages.FSharpData dotnetPackages.FSharpData225 dotnetPackages.FSharpDataSQLProvider dotnetPackages.FSharpFormatting dotnetPackages.Fake dotnetPackages.Fantomas dotnetPackages.FsCheck dotnetPackages.FsCheck262 dotnetPackages.FsCheckNunit dotnetPackages.FsLexYacc dotnetPackages.FsLexYacc706 dotnetPackages.FsLexYaccRuntime dotnetPackages.FsPickler dotnetPackages.FsUnit dotnetPackages.FuzzyLogicLibrary dotnetPackages.GitVersionTree dotnetPackages.MathNetNumerics dotnetPackages.MaxMindDb dotnetPackages.MaxMindGeoIP2 dotnetPackages.MicrosoftDiaSymReader dotnetPackages.MicrosoftDiaSymReaderPortablePdb dotnetPackages.MonoNat dotnetPackages.NDeskOptions dotnetPackages.NUnit dotnetPackages.NUnit3 dotnetPackages.NUnit350 dotnetPackages.NUnitConsole dotnetPackages.NUnitRunners dotnetPackages.NewtonsoftJson dotnetPackages.Nuget dotnetPackages.OpenNAT dotnetPackages.Paket dotnetPackages.RestSharp dotnetPackages.SharpFont dotnetPackages.SharpZipLib dotnetPackages.SmartIrc4net dotnetPackages.StyleCopMSBuild dotnetPackages.StyleCopPlusMSBuild dotnetPackages.Suave dotnetPackages.SystemCollectionsImmutable dotnetPackages.SystemCollectionsImmutable131 dotnetPackages.SystemReflectionMetadata dotnetPackages.SystemValueTuple dotnetPackages.UnionArgParser dotnetbuildhelpers duplicati eventstore foundationdb foundationdb51 foundationdb52 foundationdb60 fsharp fsharp41 github-runner haxePackages.hxcs jackett juniper keepass keepass-keeagent keepass-keefox keepass-keepasshttp keepass-otpkeyprov kodiPackages.steam-launcher lidarr lutris midisheetmusic mono mono5 msbuild nbxplorer omnisharp-roslyn openra openraPackages.engines.bleed openraPackages.engines.playtest openraPackages.mods.ca openraPackages.mods.d2 openraPackages.mods.dr openraPackages.mods.gen openraPackages.mods.kknd openraPackages.mods.mw openraPackages.mods.ra2 openraPackages.mods.raclassic openraPackages.mods.rv openraPackages.mods.sp openraPackages.mods.ss openraPackages.mods.ura openraPackages.mods.yr opentabletdriver osu-lazer pash playonlinux protontricks python-language-server python38Packages.foundationdb51 python38Packages.foundationdb52 python38Packages.foundationdb60 python38Packages.foundationdb61 python39Packages.foundationdb51 python39Packages.foundationdb52 python39Packages.foundationdb60 python39Packages.foundationdb61 radarr ryujinx sonarr steam steam-run steam-run-native steam-tui steamcmd syntex taglib-sharp vscode-extensions.ms-vscode.cpptools wasabibackend wavefunctioncollapse
```

I guess we should make `gtk-sharp-2_0` use `mono5`. Do all depending packages also have to use `mono5` then?

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122759` at 4b0dd792 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages marked as broken and skipped:</summary>
  <ul>
    <li>bless</li>
    <li>dotnetPackages.ExtCore</li>
    <li>gdata-sharp</li>
    <li>monodevelop</li>
    <li>python38Packages.foundationdb51</li>
    <li>python38Packages.foundationdb52</li>
    <li>python38Packages.foundationdb60</li>
    <li>python38Packages.foundationdb61</li>
    <li>python38Packages.pythonnet</li>
    <li>python39Packages.foundationdb51</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>66 packages skipped due to time constraints:</summary>
  <ul>
    <li>boogie (dotnetPackages.Boogie)</li>
    <li>btcpayserver</li>
    <li>ckan</li>
    <li>convchain</li>
    <li>dafny (dotnetPackages.Dafny)</li>
    <li>dbus-sharp-1_0</li>
    <li>dbus-sharp-glib-1_0</li>
    <li>dbus-sharp-glib-2_0</li>
    <li>dotnetPackages.ExcelDna</li>
    <li>dotnetPackages.ExcelDnaRegistration</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>avrdudess</li>
    <li>juniper</li>
    <li>mono</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/omnisharp-roslyn/default.nix:28:3:
```
   |
28 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by Mathnerd314** [comment]
Well, `supertux-editor` is abandoned at this point (there is an in-game editor instead), so it should probably be removed, no point in wasting effort on it.

**Comment by dotlambda** [comment]
> Well, `supertux-editor` is abandoned at this point (there is an in-game editor instead), so it should probably be removed

Would you mind doing that in a PR?

**Comment by Mathnerd314** [comment]
ok ^

**Comment by jraygauthier** [comment]
pythonnet can be updated from 2.4.0 -> 2.5.2. I should take a look at this soon.

**Review by jraygauthier — APPROVED** [review]

**Review by Mathnerd314 — APPROVED** [review]

**Comment by dotlambda** [comment]
@NixOS/nixos-release-managers Should we merge this before 21.05?

**Review by ericdallo — APPROVED** [review]

**Comment by dotlambda** [comment]
> I guess we should make `gtk-sharp-2_0` use `mono5`. Do all depending packages also have to use `mono5` then?

No one addressed this.

**Comment by dotlambda** [comment]
> > I guess we should make `gtk-sharp-2_0` use `mono5`. Do all depending packages also have to use `mono5` then?
> 
> No one addressed this.

Seems to have been fixed by https://github.com/NixOS/nixpkgs/pull/123521.

**Comment by mkg20001** [comment]
@dotlambda There are some breakages in the packages, namely everything that uses Range since Gtk.Range and System.Range collides now. For bless I needed an update to fix it #123532

**Pull request merged**
