### PR TITLE
gitlab: 15.6.0 -> 15.6.1

### PR DESCRIPTION
**Pull request by jslight90**
###### Description of changes

Email I received from GitLab:

> Today we are releasing versions 15.6.1, 15.5.5, 15.4.6 for GitLab Community Edition (CE) and Enterprise Edition (EE).
> 
> These versions contain important security fixes and we strongly recommend that all GitLab installations be upgraded to one of these versions immediately. You can see details in this security release [blog post](https://about.gitlab.com/releases/2022/11/30/security-release-gitlab-15-6-1-released/?utm_medium=email&utm_source=marketo&utm_campaign=security+release+email&utm_content=Nov+30+2022).
> 
> Please forward this alert to appropriate people at your organization and have them subscribe to [Security Notices](https://about.gitlab.com/company/contact/). You can also receive security release blog updates by subscribing to our [security release RSS feed](https://about.gitlab.com/security-releases.xml) or our [RSS feed for all GitLab releases](https://about.gitlab.com/all-releases.xml).
> 
> GitLab releases patches for vulnerabilities in two types of dedicated security releases: a monthly security release, released a week after the feature release (which deploys on the 22nd of each month), and ad-hoc security releases for critical vulnerabilities. For more information, you can visit our [security FAQ](https://about.gitlab.com/security/faq/).
> 
> Sincerely,
> GitLab Security Team

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jslight90** [comment]
Ruby Gems are failing to build with the following error:
```shell
[root@nixos:~/nixpkgs]# nix-build -A pkgs.gitlab
error: attribute 'source' missing

       at /root/nixpkgs/pkgs/development/ruby-modules/bundled-common/functions.nix:88:14:

           87|     inherit ruby;
           88|     inherit (attrs.source) type;
             |              ^
           89|     source = removeAttrs attrs.source ["type"];
(use '--show-trace' to show detailed location information)
```

**Comment by jslight90** [comment]
Looks to be possibly be related to a new Gem dependency regarding `devise-two-factor`:
```shell
[root@nixos:~/nixpkgs/pkgs/applications/version-management/gitlab]# ./update.py update-rubyenv
Downloading /root/.cache/bundix/https_rubygems_org_gems_attr_encrypted-3_2_4_gem from https://rubygems.org/gems/attr_encrypted-3.2.4.gem
/nix/store/byfwpx0vdqrbazqdijzdjyyx0p8wwv61-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix/source.rb:23: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
Authentication is required for rubygems.org.
Please supply credentials for this source. You can do this by running:
 bundle config packages.shopify.io username:password
Skipping attr_encrypted: couldn't fetch hash for attr_encrypted-3.2.4
```

**Comment by jslight90** [comment]
Removing the `attr_encrypted` Gem and the dependency listed by `devise-two-factor` does allow the pkg to build.  Not sure what that change affects.

**Comment by yayayayaka** [comment]
It is a known issue (see https://github.com/NixOS/nixpkgs/pull/197470#issue-1420092301 for context). Our current fix is to manually edit the generated gemset until we figure out a solution.

**Review by dasJ — APPROVED** [review]
Looks very similar to what we did in our downstream repo (which resulted in a working GitLab)

**Comment by dasJ** [comment]
It's unfortunate we cannot directly backport this to 22.05 :/

**Comment by jslight90** [comment]
> It's unfortunate we cannot directly backport this to 22.05 :/

Why not?  I'm currently running this in 22.05 by setting `services.gitlab.packages` to the this commit version.

**Comment by RaitoBezarius** [comment]
Looks good, any reason not to merge this?

**Review by RaitoBezarius — APPROVED** [review]

**Comment by yayayayaka** [comment]
> It's unfortunate we cannot directly backport this to 22.05 :/

I suggest updating gitlab from 15.4.4 to 15.4.6 on release-22.05.

**Comment by onny** [comment]
> Backport failed for `release-22.11`, because it was unable to cherry-pick the commit(s).
> 
> Please cherry-pick the changes locally.
> 
> ```shell
> git fetch origin release-22.11
> git worktree add -d .worktree/backport-203868-to-release-22.11 origin/release-22.11
> cd .worktree/backport-203868-to-release-22.11
> git checkout -b backport-203868-to-release-22.11
> ancref=$(git merge-base 38e591dd05ffc8bdf79dc752ba78b05e370416fa 4ac49afb5bbdf7f46df83a4cc775df68cc903ca6)
> git cherry-pick -x $ancref..4ac49afb5bbdf7f46df83a4cc775df68cc903ca6
> ```

Backport to `release-22.11` would be very nice

**Pull request merged**
