### PR TITLE
opensearch: 2.6.0 -> 2.7.0

### PR DESCRIPTION
**Pull request by shyim**
###### Description of changes

Updates the Opensearch package to the latest version of the 2.7.0.

Removed our patch as the latest version contains the patch https://github.com/opensearch-project/OpenSearch/pull/6956

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
I'm a little confused how this package downloads the `-linux-x64.tar.gz` version and then claims `platforms.unix` support. There's at least one native `.so` in that tarball (`libopensearchknn_*.so`)

**Comment by shyim** [comment]
By just changing the java to our own it works in all platforms, except the ML features which requires that so files. 😅

**Comment by risicle** [comment]
Could you add to `meta`

```
sourceProvenance = with lib.sourceTypes; [
  binaryBytecode
  binaryNativeCode
];
```

then please.

**Comment by risicle** [comment]
Sorry, I should have made it clearer - the `sourceProvenance` attribute needs to be added to the `meta` section.

**Comment by shyim** [comment]
All good I was brain dead :). Fixed :)

**Review by risicle — APPROVED** [review]

**Pull request merged**
