### PR TITLE
paperless-ngx: 1.10.2 -> 1.11.3

### PR DESCRIPTION
**Pull request by e1mo**
###### Description of changes

paperless-ngx 1.11.0
> Notable Changes
> - Feature: frontend paperless mail
> - Feature: Ability to consume mails and eml files
https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.11.0

Other changes seem to mostly consist of bug-fixes or minor improvements. See <https://github.com/paperless-ngx/paperless-ngx/releases> for a full list.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 209591` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>paperless-ngx</li>
<li>python310Packages.imagehash</li>
<li>python39Packages.imagehash</li>
</ul>
</details>

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 209591` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 test built:
</summary>
<ul>
<li>nixosTests.paperless</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
nixosTests.paperless:
<details>

Package is missing a meta section.
If the package is using runCommand please make sure to inherit or create a meta section.

</details>
</details>

**Comment by e1mo** [comment]
> nixosTests.paperless:
> 
> Package is missing a meta section. If the package is using runCommand please make sure to inherit or create a meta section.

A meta section seems to be present when looking at https://github.com/NixOS/nixpkgs/blob/37c6a32f8078d6dd795debadd89e9dc869f28845/nixos/tests/paperless.nix#L3

Could this be some sort of mistake within `nixpkgs-review-checks`?

**Comment by gador** [comment]
@e1mo yeah, I guess so. I'd just ignore it

**Comment by e1mo** [comment]
It seems as if it checks if `meta.description` is present. I'll go file an issue ovr there. https://github.com/SuperSandro2000/nixpkgs-review-checks/blob/13ea8bcf9e62d99530f7bbad0852315dba408f0f/nixpkgs-review-checks-hook#L41

**Review by erikarvstedt — APPROVED** [review]
- [x] `nixosTests.paperless` succeeds on `x86_64-linux`

**Comment by ambroisie** [comment]
@e1mo I had to chase down this MR for 15 minutes, after finding #208261.

Do you think we should document the setup necessary to support the classifier? I think it needs both a configuration for the data, as well as a timer to trigger the training, am I correct?

**Comment by e1mo** [comment]
> a configuration for the data

Yes, paperless (more specifically nltk) requires various datasets to be present. Normally they would be fetched at runtime, but they can also be fetched beforehand as shown in #208261:

<details>
<summary>Code example</summary>

```nix
{ pkgs, config, lib, ...}:

{
services.paperless = let
  nltkDatasets = {
    # Raw data is licensed in most parts as BSD-3 clause with one CC-BY-SA 3 dataset
    # BSD-3: https://github.com/snowballstem/snowball-data/commit/0fe3da19bb818461548f4780815ab323fea606bb
    # CC-BY-SA dataset addition: https://github.com/snowballstem/snowball-data/commit/35999218ecdd19c82fc87f791179d00657007814
    "stemmers/snowball_data" = pkgs.fetchzip { # Roughly 35M in closure size
      pname = "snowball_data";
      version = "2015-02-10";
      url = "https://raw.githubusercontent.com/nltk/nltk_data/ebd75b7b05637d6b70828a15fc458fd9e76a70d0/packages/stemmers/snowball_data.zip";
      hash = "sha256-CjMftTNwAQksVzIom0M7nlAroD5w8Fk64blBNSgZX5k=";
      meta.license = with lib.licenses; [ bsd3 cc-by-nc-sa-30 ];
    };
    # License unclear. Some parts seem to (in part?) originate from https://pypi.org/project/stop-words/
    "corpora/stopwords" = pkgs.fetchzip { # Roughly 85K in final closure size
      pname = "stopwords";
      version = "2016-08-20";
      url = "https://raw.githubusercontent.com/nltk/nltk_data/7d5849ea69b31fe13f03903756835fa2f867a187/packages/corpora/stopwords.zip";
      hash = "sha256-zQf9RnK0yWI1bIEjNEm2hmGubHGeDQN0supIBQGww6c= ";
    };
    # Unable to spot a license for this
    "tokenizers/punkt" = pkgs.fetchzip { # Roughly 35M in closure size
      pname = "punkt";
      version = "2022-07-14";
      url = "https://raw.githubusercontent.com/nltk/nltk_data/1d3c34b4cfd6059986bf4bc604e5929335ab92ff/packages/tokenizers/punkt.zip";
      hash = "sha256-SKZu26K17qMUg7iCFZey0GTECUZ+sTTrF/pqeEgJCos=";
    };
  };
in {
    enable = true;
    # ...
    extraConfig.PAPERLESS_NLTK_DIR = pkgs.linkFarm "nltk_data" nltkDatasets;
    # ...
};
}
```

</details>

> as well as a timer to trigger the training

No, classifier training is handles automatically as part of paperlesses task queue (The classifier runs once every hour).

On one of my instances I'm running with everything enable for the classifier. However, training does not succeed instance, as discussed here: https://github.com/paperless-ngx/paperless-ngx/discussions/2373. Since I don't have that much spare time and energy right now, I have not dug further into this.

**Pull request merged**
