### PR TITLE
[21.11] tsm-client: 8.1.8.0 -> 8.1.13.3 (security update)

### PR DESCRIPTION
**Pull request by Yarny0**
###### Motivation for this change

This backports ~~two~~ ~~four~~ ~~five~~ six commits from https://github.com/NixOS/nixpkgs/pull/138386, effectively updating `tsm-client` to its latest version.  This appears in order as the update contains security critical fixes.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`) (however, tested with current `nixos-21.11` branch, executed within NixOS 21.05 machine)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Yarny0** [comment]
New branch, based on update in https://github.com/NixOS/nixpkgs/pull/138386:

* Rebased onto fresh `release-21.11` (35ed93a9573752ba02eb282d15e702fca5138072)
* Uses `lib.versions` to generate the download URL
* Updated `meta.homepage` as the previous value is now a redirect to the new value

**Comment by Yarny0** [comment]
New branch, based on update in https://github.com/NixOS/nixpkgs/pull/138386:

* Rebased onto fresh `release-21.11` (75f3534c98a00f40f7647fa70db243f008c45ef4)
* Replace deb-based source archive with rpm-based source archive.  This is needed because this update is not published as deb-based archive.
* Update to newest version 8.1.13.1, which hopefully fixes the log4j vulnerability in the `tsm-client` package: [IBM Security Bulletin](https://www.ibm.com/support/pages/node/6527080)

I tested the command line interface (executed on a NixOS 21.05 machine) with a real TSM-server, without any problems.

**Comment by Yarny0** [comment]
I pushed another update due to log4j, backported from https://github.com/NixOS/nixpkgs/pull/138386 .

* update `tsm-client` to yesterday's release 8.1.13.2, which contains further log4j-related fixes according to their security bulletin
* rebase onto fresh `release-21.11` (d3179446efde6bc6f5b01f18438b9131fe8f1741)

Tested the new package to backup files to a TSM server: It works without problems.

**Comment by Yarny0** [comment]
I pushed another update due to log4j, backported from https://github.com/NixOS/nixpkgs/pull/138386 .

* update `tsm-client` to yesterday's release 8.1.13.3, which contains further log4j-related fixes according to their security bulletin
* rebase onto fresh `release-21.11` (8e82ab3a62f308dce3193b2c4e21969dd41f987c)

Tested the new package to backup files to a TSM server: It works without problems.

**Comment by c0bw3b** [comment]
Related to #150288

**Review by c0bw3b — APPROVED** [review]
Result of `nixpkgs-review pr 150590` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>tsm-client</li>
    <li>tsm-client-withGui</li>
  </ul>
</details>

**Pull request merged**
