### PR TITLE
WIP: vscode: patch .desktop file to use absolute files.

### PR DESCRIPTION
**Pull request by moredhel**
###### Motivation for this change

fix to work with Crostini

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions (Crostini)
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by veprbl** [comment]
cc @eadwu

**Comment by eadwu** [comment]
Works fine for `vscode` but this would break `vscode-with-extensions`. 

```diff
diff --git a/pkgs/applications/editors/vscode/with-extensions.nix b/pkgs/applications/editors/vscode/with-extensions.nix
index 88bea0c0809..9ae4e619c71 100644
--- a/pkgs/applications/editors/vscode/with-extensions.nix
+++ b/pkgs/applications/editors/vscode/with-extensions.nix
@@ -67,7 +67,12 @@ runCommand "${wrappedPkgName}-with-extensions-${wrappedPkgVersion}" {
   mkdir -p "$out/share/pixmaps"
 
   ln -sT "${vscode}/share/pixmaps/code.png" "$out/share/pixmaps/code.png"
-  ln -sT "${vscode}/share/applications/${executableName}.desktop" "$out/share/applications/${executableName}.desktop"
+
+  substitute "${vscode}/share/applications/${executableName}.desktop" "$out/share/applications/${executableName}.desktop" \
+    --replace "${vscode}" "$out"
+  substitute "${vscode}/share/applications/${executableName}-url-handler.desktop" "$out/share/applications/${executableName}-url-handler.desktop" \
+    --replace "${vscode}" "$out"
+
   makeWrapper "${vscode}/bin/${executableName}" "$out/bin/${executableName}" ${lib.optionalString (vscodeExtensions != []) ''
     --add-flags "--extensions-dir ${combinedExtensionsDrv}/share/${wrappedPkgName}/extensions"
   ''}
```

**Comment by moredhel** [comment]
@eadwu thanks for the advice, I think I am going to hold out on this PR for the moment while I discuss on #56954 a better solution for Crostini in general.

If you have any thoughts regarding it, then do hop over and let us know 👍

**Comment by worldofpeace** [comment]
I believe this has already been fixed.

**Pull request closed without merging**
