### PR TITLE
cargo-c: 0.8.0 -> 0.8.1

### PR DESCRIPTION
**Pull request by alyssais**
Tested by building a dependent package (rav1e)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by petabyteboy** [comment]
Probably against staging?

**Comment by happysalada** [comment]
I agree here, ofborg marked the number of rebuilds for linux and darwin at more than 5000. It would be good to be against staging.

**Comment by alyssais** [comment]
Yeah, I didn't realise because there's only one package that uses it, but that package is a dependency of ffmpeg so that explains it.

**Comment by happysalada** [comment]
Nothing to build on darwin so I will go ahead and merge this one.

**Pull request merged**
