### PR TITLE
terraform-providers: bump versions

### PR DESCRIPTION
**Pull request by uskudnik**
###### Motivation for this change
Update providers to latest versions. Tested google, google-beta and postgresql 
 # ##### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
A few of these aren't able to build for me:

```
4 package failed to build:
terraform-full terraform-providers.ansible terraform-providers.matchbox terragrunt
```

<details>
 <summary>full log output</summary>

```
builder for '/nix/store/j4lqyqic7nr34is1x5l7dghy0y73pl5w-terraform-provider-ansible-1.0.3.drv' failed with exit code 1; last 10 log lines:
  building
  go/src/github.com/nbering/terraform-provider-ansible/ansible/provider.go:4:2: cannot find package "github.com/hashicorp/terraform/helper/schema" in any of:
        /nix/store/zvi4wy0kzh3iz7db7dl7p7dk1rqf7frj-go-1.12.6/share/go/src/github.com/hashicorp/terraform/helper/schema (from $GOROOT)
        /build/go/src/github.com/hashicorp/terraform/helper/schema (from $GOPATH)
  go/src/github.com/nbering/terraform-provider-ansible/main.go:4:2: cannot find package "github.com/hashicorp/terraform/plugin" in any of:
        /nix/store/zvi4wy0kzh3iz7db7dl7p7dk1rqf7frj-go-1.12.6/share/go/src/github.com/hashicorp/terraform/plugin (from $GOROOT)
        /build/go/src/github.com/hashicorp/terraform/plugin (from $GOPATH)
  go/src/github.com/nbering/terraform-provider-ansible/ansible/provider.go:5:2: cannot find package "github.com/hashicorp/terraform/terraform" in any of:
        /nix/store/zvi4wy0kzh3iz7db7dl7p7dk1rqf7frj-go-1.12.6/share/go/src/github.com/hashicorp/terraform/terraform (from $GOROOT)
        /build/go/src/github.com/hashicorp/terraform/terraform (from $GOPATH)
builder for '/nix/store/9ncb7fknp27hr8lscarwv2rxykjp2yvi-terraform-provider-matchbox-0.3.0.drv' failed with exit code 1; last 10 log lines:
  unpacking sources
  unpacking source archive /nix/store/zfrw6gmn9rfdk09nlnndgz5imcs4jzpy-source
  source root is source
  patching sources
  configuring
  building
  go/src/github.com/coreos/terraform-provider-matchbox/main.go:6:2: cannot find package "github.com/poseidon/terraform-provider-matchbox/matchbox" in any of:
        /build/go/src/github.com/coreos/terraform-provider-matchbox/vendor/github.com/poseidon/terraform-provider-matchbox/matchbox (vendor tree)
        /nix/store/zvi4wy0kzh3iz7db7dl7p7dk1rqf7frj-go-1.12.6/share/go/src/github.com/poseidon/terraform-provider-matchbox/matchbox (from $GOROOT)
        /build/go/src/github.com/poseidon/terraform-provider-matchbox/matchbox (from $GOPATH)
[7/63/74 built (2 failed), 90 copied (1996.1/1996.5 MiB), 414.6 MiB DL] building terracannot build derivation '/nix/store/wqbs8d976ra20qdixzc2l51mzz325ycq-tf-plugin-env.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/jvmw03dwqjh88galgz3nhnyrpl51nl06-terraform-0.11.14.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/y7sfa6xri428c33810gnxvgi6x1i8rbx-terragrunt-0.17.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4h4pi7ak3knad44razjxxrhmln12ycbc-env.drv': 4 dependencies couldn't be built
[70 built (2 failed), 90 copied (1996.1 MiB), 414.6 MiB DL]
error: build of '/nix/store/4h4pi7ak3knad44razjxxrhmln12ycbc-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/64260
4 package failed to build:
terraform-full terraform-providers.ansible terraform-providers.matchbox terragrunt
```

</details>

**Comment by uskudnik** [comment]
Can you try with terraform 0.12 as well?

**Comment by jonringer** [comment]
It looks like those packages have just added dependencies. I'm not too familiar with doing Go packaging with nix, but from the log output you can see that they require new dependencies.

**Comment by uskudnik** [comment]
@jonringer Seems to be good for me, please re-try.

**Comment by Mic92** [comment]
@GrahamcOfBorg build terraform-full

**Pull request merged**
