### PR TITLE
Some cc-wrapper changes to better support darwin and clang

### PR DESCRIPTION
**Pull request by copumpkin**
(a new version of #6237 against master)
- Add a conditional flag for the c++ std lib (will be used in another upcoming pure-darwin PR)
- Build binaries that get linked by our own dyld (someday)
- Automatically add framework directories in the setup hook

### CODE REVIEW

**Comment by copumpkin** [comment]
cc @shlevy, I can haz hydra?

@gridaphobe I didn't want to base it off of #6166 because then my PR's diff view would include all of your stuff as well as mine, and it'd be harder to review. Not sure how best to get the best of both worlds... perhaps a new temporary branch containing both changes to send to hydra?

**Comment by shlevy** [comment]
Let me know when you have a merged branch and I'll make a jobset.

**Comment by copumpkin** [comment]
@shlevy https://github.com/copumpkin/nixpkgs/tree/prs-6254-and-6166

**Comment by shlevy** [comment]
http://hydra.nixos.org/jobset/nixpkgs/prs-6254-and-6166

**Comment by copumpkin** [comment]
Thanks!

**Comment by copumpkin** [comment]
So 29000 packages to build. Does that mean we just take a break for the next couple of weeks? :smile:

**Comment by shlevy** [comment]
Going to merge this into staging, hydra can't handle multiple stdenv rebuilds in parallel.

**Comment by shlevy** [comment]
https://github.com/NixOS/nixpkgs/commit/7a1d132db9508d9831766da5b012d3d55e8c37c1

**Pull request merged**
