### PR TITLE
gcc: update default version to 4.9

### PR DESCRIPTION
**Pull request by Ralith**
Not sure if the changes are complete or correctly executed; mostly I want to start the conversation regarding making the change, and kick off tests. It might also be desirable to switch straight to 5.1, which has improved support for recent iterations of the standard. In particular, 4.9 has partial C++14 support, which 5.1 brings much closer to completion.

### CODE REVIEW

**Comment by edolstra** [comment]
IIRC, there have been a few changes applied to the 4.8 expression that should be propagated to 4.9 (e.g. 06725e95eb7ec557601f7aa38b152762479dc517, a0c60b76ec258ea158bebaea53d6d39055cdf857).

**Comment by shlevy** [comment]
IMO we should switch straight to 5.1, which I was planning to try after the next staging merge.

**Comment by edolstra** [comment]
5.1 seems waaay too bleeding edge for me. Also, we'll have to decide how to deal with the ABI change.

**Comment by shlevy** [comment]
Well, isn't this what staging is for, to test these changes? If it breaks everything, obviously we shouldn't do it, but otherwise what better way to test the bleeding edge of a compiler than by compiling everything?

As for the ABI change, I was planning to see if we can't remove all usages of pre-5 in nixpkgs. If not, we can stick with the old ABI until we can.

**Comment by shlevy** [comment]
OK. I'll try it in a separate branch, then. For what it's worth, I can't remember a single staging merge that wasn't preceded by "let's fix everything that these changes broke", so it doesn't seem like we're actually using staging that way.

**Comment by vcunat** [comment]
Please, try to use staging in the way it was announced. I do believe it's useful for our workflow, as we seem to have quite a lot of mass-rebuild changes that are relatively safe or well-tested already. I know it's tempting to test likely destabilizing changes in there, especially after seeing others doing so occasionally...

**Comment by Mathnerd314** [comment]
GCC 4.9 is the default now, so can this be closed?

**Comment by Ralith** [comment]
I don't see why not.

**Pull request closed without merging**
