### PR TITLE
python3{11,12}Packages.nose: drop

### LINKED ISSUE #326513: python3Packages: get rid of uses of nose
nose is [abandoned upstream](https://nose.readthedocs.io/en/latest/) and has caused us untold headaches recently (admittedly mostly unrelated to the code itself). We’ve stopped the bleeding by getting https://github.com/NixOS/nixpkgs/pull/325968 into staging thanks to the incredible work of @jchv, but it’s still broken on master and we ought to do some tidying up so we’re not dragging this around forever and perhaps even to unblock some stuff on master while the staging cycle progresses. Many packages don’t actually need nose any more, despite us including it in our dependency lists. Active upstreams should have already moved to pytest or something else. Some packages will have patches available; if we’re really feeling generous we could send patches to upstream ourselves. Others may be completely unmaintained packages that we could think about dropping.

@dotlambda has already done some great work on this – see https://github.com/NixOS/nixpkgs/pull/325847, https://github.com/NixOS/nixpkgs/pull/325872, https://github.com/NixOS/nixpkgs/pull/325885, and https://github.com/NixOS/nixpkgs/pull/326164 – but I thought it’d be good to have a master list of all affected packages so we can tackle it collectively.

* [ ] `adafruit-nrfutil`
* [ ] `aws-google-auth`
* [ ] `caffe`
* [ ] `candidates1`
* [ ] `cmake-lint`
* [ ] `gixy`
* [ ] `hydrus`
* [ ] `ledger-autosync`
* [ ] `mackup`
* [ ] `mbutil`
* [ ] `onboard`
* [ ] `openlp`
* [ ] `python3Packages.actdiag`
* [ ] `python3Packages.androguard`
* [ ] `python3Packages.apricot-select`
* [ ] `python3Packages.beaker`
* [ ] `python3Packages.biopandas`
* [ ] `python3Packages.blessings`
* [ ] `python3Packages.blockdiag`
* [ ] `python3Packages.boto`
* [ ] `python3Packages.braintree`
* [ ] `python3Packages.bx-python`
* [ ] `python3Packages.cassandra-driver`
* [ ] `python3Packages.cgroup-utils`
* [ ] `python3Packages.changefinder`
* [ ] `python3Packages.chart-studio`
* [ ] `python3Packages.citeproc-py`
* [ ] `python3Packages.clickhouse-driver`
* [ ] `python3Packages.clustershell`
* [ ] `python3Packages.deform`
* [ ] `python3Packages.django-crontab`
* [ ] `python3Packages.dm-control`
* [ ] `python3Packages.docker`
* [ ] `python3Packages.dodgy`
* [ ] `python3Packages.envs`
* [ ] `python3Packages.expiringdict`
* [ ] `python3Packages.flask-restful`
* [ ] `python3Packages.gocardless-pro`
* [ ] `python3Packages.habanero`
* [ ] `python3Packages.hkdf`
* [ ] `python3Packages.http-ece`
* [ ] `python3Packages.inotify`
* [ ] `python3Packages.isbnlib`
* [ ] `python3Packages.jsonable`
* [ ] `python3Packages.jupyter-contrib-nbextensions`
* [ ] `python3Packages.libgpuarray`
* [ ] `python3Packages.locationsharinglib`
* [ ] `python3Packages.lockfile`
* [ ] `python3Packages.mhcflurry`
* [ ] `python3Packages.mkl-service`
* [ ] `python3Packages.mohawk`
* [ ] `python3Packages.mongoengine`
* [ ] `python3Packages.more-itertools`
* [ ] `python3Packages.mwtypes`
* [ ] `python3Packages.mwxml`
* [ ] `python3Packages.mygpoclient`
* [ ] `python3Packages.nbmerge`
* [ ] `python3Packages.neo`
* [ ] `python3Packages.nose-pattern-exclude`
* [ ] `python3Packages.nose-timer`
* [ ] `python3Packages.nose-warnings-filters`
* [ ] `python3Packages.nose-xunitmp`
* [ ] `python3Packages.nwdiag`
* [ ] `python3Packages.ofxhome`
* [ ] `python3Packages.ofxtools`
* [ ] `python3Packages.para`
* [ ] `python3Packages.paramz`
* [ ] `python3Packages.pastescript`
* [ ] `python3Packages.paver`
* [ ] `python3Packages.pid`
* [ ] `python3Packages.pkutils`
* [ ] `python3Packages.pprintpp`
* [ ] `python3Packages.preggy`
* [ ] `python3Packages.premailer`
* [ ] `python3Packages.prison`
* [ ] `python3Packages.prox-tv`
* [ ] `python3Packages.ptable`
* [ ] `python3Packages.pycdio`
* [ ] `python3Packages.pycontracts`
* [ ] `python3Packages.pydy`
* [ ] `python3Packages.pyexcel-ods`
* [ ] `python3Packages.pyexcel-xls`
* [ ] `python3Packages.pygatt`
* [ ] `python3Packages.pygeoip`
* [ ] `python3Packages.pygogo`
* [ ] `python3Packages.pygtfs`
* [ ] `python3Packages.pylacrosse`
* [ ] `python3Packages.pypass`
* [ ] `python3Packages.pypillowfight`
* [ ] `python3Packages.pyquaternion`
* [ ] `python3Packages.pyrfc3339`
* [ ] `python3Packages.pysrt`
* [ ] `python3Packages.pytest`
* [ ] `python3Packages.python-etcd`
* [ ] `python3Packages.python-fedora`
* [ ] `python3Packages.python-hglib`
* [ ] `python3Packages.python-mapnik`
* [ ] `python3Packages.pytimeparse`
* [ ] `python3Packages.pyutilib`
* [ ] `python3Packages.rauth`
* [ ] `python3Packages.rx`
* [ ] `python3Packages.safe`
* [ ] `python3Packages.sampledata`
* [ ] `python3Packages.scales`
* [ ] `python3Packages.scikit-fuzzy`
* [ ] `python3Packages.selectors2`
* [ ] `python3Packages.seqdiag`
* [ ] `python3Packages.shap`
* [ ] `python3Packages.simplebayes`
* [ ] `python3Packages.spark-parser`
* [ ] `python3Packages.sphinx-rtd-dark-mode`
* [ ] `python3Packages.sqlalchemy-mixins`
* [ ] `python3Packages.stytra`
* [ ] `python3Packages.sure`
* [ ] `python3Packages.svgutils`
* [ ] `python3Packages.telfhash`
* [ ] `python3Packages.tempita`
* [ ] `python3Packages.tissue`
* [ ] `python3Packages.traittypes`
* [ ] `python3Packages.trfl`
* [ ] `python3Packages.uncompyle6`
* [ ] `python3Packages.unicode-slugify`
* [ ] `python3Packages.uvcclient`
* [ ] `python3Packages.vxi11`
* [ ] `python3Packages.webassets`
* [ ] `python3Packages.webhelpers`
* [ ] `python3Packages.weboob`
* [ ] `python3Packages.wsme`
* [ ] `python3Packages.xlwt`
* [ ] `python3Packages.yanc`
* [ ] `python3Packages.yarg`
* [ ] `sasview`
* [ ] `svtplay-dl`
* [ ] `tarsnapper`
* [ ] `zk-shell`

This was generated from staging commit 83881cb6e9b660cbca5241380c031ab2b69d6e1e with the following awful fish one‐liner: `for pkg in (rg -l '\bnose3?\b' | rg -v '/(nose[23]?|cufflinks|enocean|jaconv|annoy|hdmedians|flaky|pycron|snapshottest|grin|ssh-mitm|colour|influxdb)/|(python|cran)-(packages|aliases)\.nix' | sed 's|.*/\([^/]*\)/\([^/]*\)$|\1|'); rg "/$pkg"'[ \n{]' pkgs/top-level/python-packages.nix | awk '{print "python3Packages." $1}'; test $pipestatus[1] = 0 || rg "/$pkg"'[ \n{]' pkgs/top-level/all-packages.nix | awk '{print $1}'; test $pipestatus[1] = 0 || echo "$pkg"; end | sort -u | sed 's/^/* [ ] `/; s/$/`/'`; feel free to edit to update the list.

### PR DESCRIPTION
**Pull request by emilazy**
🎉

This package has been deprecated and unmaintained upstream for almost a decade, has required extensive patching to keep working on new Python versions, will inevitably break again with Python 3.13 dropping 2to3, is lacking a maintainer in Nixpkgs, is now unused in the tree, and has caused us all far too many headaches lately. Let’s put an end to this!

Shout‐outs to @mweinelt and @jchv for dealing with this situation early on, @pyrox0, @Sigmanificient, and @dotlambda for tackling a bunch of packages, and @natsukium for help with reviews. I never thought this would get finished so quickly. We’ve collectively handled almost 1½ packages per day in the three months since I first opened the tracking issue, and sometimes helped move the entire ecosystem forward.

Closes: #326513

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Scrumplex — CHANGES_REQUESTED** [review]
```
pkgs/development/python-modules/mhcflurry/default.nix
```
Pulls in nose still :/

Edit: but it doesn't actually use it

**Comment by emilazy** [comment]
https://github.com/NixOS/nixpkgs/pull/347990 was already merged.

**Comment by Scrumplex** [comment]
The changes in the actual merge https://github.com/NixOS/nixpkgs/commit/8574a14dd82a7669253dcff86d94c40b1204a8e3 and the PR https://github.com/NixOS/nixpkgs/pull/347990/commits/b9a003c52859439c3bf8994b9ed9dda0041233ef are different for some reason

**Comment by emilazy** [comment]
Ah, phew, it’s not quite my fault: the file changed since I started that branch locally and “removed” the nose parameter from that location by moving it further down the file, and the accursed three‐way merge decided that we had made the same change and that therefore it was fine to drop mine. https://github.com/NixOS/nixpkgs/pull/348716 fixes it.

**Comment by emilazy** [comment]
Eval should hopefully be okay now.

**Review by mweinelt — APPROVED** [review]

**Pull request merged**
