### PR TITLE
nix-{delegate,deploy,diff}: add top-level attributes, static

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Promote nix-related tools, make them more readily available for use!

(**note**: due to https://github.com/awakesecurity/nix-deploy/issues/9 `nix-deploy` doesn't build for us yet-- the check marks below apply to nix-delegate only)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pbogdan** [comment]
Perhaps too niche of a use case but in the same spirit `nix-diff` might be worth including as well?

**Comment by dtzWill** [comment]
@pbogdan not too niche IMO, sounds good to me! Thanks for mentioning it! *updates*

**Review by ixmatus — APPROVED** [review]
This is great! Thanks for doing this!

Note that https://github.com/awakesecurity/nix-deploy/pull/10 fixes the issue you reported.

**Comment by ixmatus** [comment]
CC: @Gabriel439

**Comment by ixmatus** [comment]
`nix-diff` is definitely not too niche IMHO. I've been using it extensively in order to prove that specific changes are applied or unchanged and it makes for great proof collateral for those types of verifications.

**Comment by dtzWill** [comment]
Added patch @ixmatus mentioned to fix nix-deploy while at it.

**Comment by ixmatus** [comment]
@dtzWill doh! I forgot to release to hackage. My bad. If I do that then you won't need the patch.

**Comment by ixmatus** [comment]
@dtzWill okay [`nix-deploy-1.0.2`](https://hackage.haskell.org/package/nix-deploy-1.0.2) is published to Hackage

**Comment by dtzWill** [comment]
@ixmatus okay-- dropped that commit, should be working when the next update happens.  Thanks for fixing and making the release!

**Pull request merged**
