### PR TITLE
gitea: 1.22.1 -> 1.22.2

### PR DESCRIPTION
**Pull request by techknowlogick**
Diff: https://github.com/go-gitea/gitea/compare/v1.22.1...1.22.2

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
```
error: hash mismatch in fixed-output derivation '/nix/store/vhvqdpy7a2b882adswvhzmavzw6kkd5g-gitea-1.22.2-go-modules.drv':
         specified: sha256-21jandaU2W57xVYeJF9jUwHsl8nYDYWLdCiAPbbVgzU=
            got:    sha256-H4lP01VJk7E/tvzJ7iXI/hkqFQIisznNlliwFOrOk+k=
```

```
error: hash mismatch in fixed-output derivation '/nix/store/fqcx8dw5d85x1skmkm2mmch7ygwkds3b-gitea-frontend-1.22.2-npm-deps.drv':
         specified: sha256-gXBBiDIIS0aW6qK37HcF0AuJOliblinznRVXoo6DV1s=
            got:    sha256-Sp3xBe5IXys2Qro4x4HKs9dQOnlbstAmtIG6xOOktEk=
```

**Review by Ma27 — CHANGES_REQUESTED** [review]
@techknowlogick did you force-push a release upstream? If not, can you please diff the current state with the state you had when you filed this PR? Would like to have this resolved before merging.

**Comment by SuperSandro2000** [comment]
@Ma27 no, they didn't. The tag on github is from before the commit https://github.com/go-gitea/gitea/releases/tag/v1.22.2

**Comment by techknowlogick** [comment]
@Ma27 nope, it's the expected tag. What's weird is that I'm only getting the hashes in this PR on Darwin, but get different ones on Linux. Sadly I don't have multiple Darwin devices to test this, so I'll switch this PR to use the ones from Linux as Darwin is considered secondary for nixpkgs and I can investigate Darwin later (hopefully it's just something with my device, but that'd be weird cause then my device wouldn't be creating something reproducible)

**Comment by Ma27** [comment]
Thanks for the pointer, will try to reproduce these on Darwin.

**Comment by SuperSandro2000** [comment]
Probably their case insensitive FS again. Try setting proxyVendor to true

**Comment by Ma27** [comment]
That's indeed the case for the Go part:

```
[nix-shell:~/Projects/nixpkgs]$ diffoscope result-{linux,darwin}
--- result-linux
+++ result-darwin
├── stat {}
│ @@ -1,7 +1,7 @@
│  
│    Size: 67        	Blocks: 1          IO Block: 131072 symbolic link
│  Device: 0,34	Access: (0777/lrwxrwxrwx)  Uid: ( 1000/    ma27)   Gid: (  100/   users)
│  
│ -Modify: 2024-09-09 15:01:09.139538140 +0000
│ +Modify: 2024-09-09 15:02:32.101870342 +0000
│   --- result-linux/github.com
├── +++ result-darwin/github.com
│ ├── file list
│ │ @@ -85,15 +85,14 @@
│ │  magiconair
│ │  mailru
│ │  markbates
│ │  mattn
│ │  meilisearch
│ │  mholt
│ │  microcosm-cc
│ │ -microsoft
│ │  miekg
│ │  minio
│ │  mitchellh
│ │  modern-go
│ │  mrjones
│ │  mschoch
│ │  msteinert
│ ├── stat {}
│ │ @@ -1,7 +1,7 @@
│ │  
│ │ +  Size: 152       	Blocks: 11         IO Block: 131072 directory
│ │ -  Size: 153       	Blocks: 11         IO Block: 131072 directory
│ │  Device: 0,35	Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
│ │  
│ │  Modify: 1970-01-01 00:00:01.000000000 +0000
│ │   --- result-linux/github.com/Microsoft
│ ├── +++ result-darwin/github.com/Microsoft
│ │ ├── file list
│ │ │ @@ -1 +1,2 @@
│ │ │ +go-mssqldb
│ │ │  go-winio
│ │ ├── stat {}
│ │ │ @@ -1,7 +1,7 @@
│ │ │  
│ │ │ -  Size: 3         	Blocks: 1          IO Block: 131072 directory
│ │ │ +  Size: 4         	Blocks: 1          IO Block: 131072 directory
│ │ │  Device: 0,35	Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
│ │ │  
│ │ │  Modify: 1970-01-01 00:00:01.000000000 +0000
│ │ ├── stat {}
│ │ │ @@ -1,7 +1,7 @@
│ │ │  
│ │ │ +  Size: 4         	Blocks: 1          IO Block: 131072 directory
│ │ │ -  Size: 3         	Blocks: 1          IO Block: 131072 directory
│ │ │  Device: 0,35	Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
│ │ │  
│ │ │  Modify: 1970-01-01 00:00:01.000000000 +0000
│ ├── stat {}
│ │ @@ -1,7 +1,7 @@
│ │  
│ │ -  Size: 153       	Blocks: 11         IO Block: 131072 directory
│ │ +  Size: 152       	Blocks: 11         IO Block: 131072 directory
│ │  Device: 0,35	Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
│ │  
│ │  Modify: 1970-01-01 00:00:01.000000000 +0000
```

(basically `Microsoft` vs `microsoft`).

So it indeed may be worth a try to do what Sandro suggested.

---

Regarding the frontend part: I couldn't reproduce the original hash on two different Darwin machines.
@techknowlogick do you still have the store-path for hash `sha256-gXBBiDIIS0aW6qK37HcF0AuJOliblinznRVXoo6DV1s=
` in your store? If so, please post the differences ot the current path (can be determined using `diffoscope`).

**Comment by SuperSandro2000** [comment]
> do you still have the store-path for hash `sha256-gXBBiDIIS0aW6qK37HcF0AuJOliblinznRVXoo6DV1s= ` in your store?

By now it is probably in the go cache. When cloning directly, it is known that the results are sometimes different and none deterministic. I don't think we need to invest to much time here especially because we have security fixes in the update.

**Comment by techknowlogick** [comment]
@Ma27, ah yes that makes sense. We switched to the MS-supported MSSQL DB library, and MS does use an upper case M for their GitHub username (and go imports). As for the frontend hash change, I sadly don't have it in my store still as I rather aggressively gc on my darwin device (I need to eventually invest in more drives for my NAS as all of my devices are filling up)

**Comment by SuperSandro2000** [comment]
@Ma27 so? I don't think we get to know what the diff was. I would love to know it, too but since the tag wasn't force pushed, I would attribute it to some flakiness or human error rather than a incident.

**Comment by techknowlogick** [comment]
> human error

Yeah, this is likely the cause. I've had some health things recently, so I haven't been at the top of my game. I think it's probably safe not to have to investigate, although I'd still be willing to aid in any search for how that happened.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Yeah we're still on 1.21 on 24.05.
@techknowlogick does it make sense to patch the issues there?

**Pull request merged**
