### PR TITLE
Update linux version to 6.11

### PR DESCRIPTION
**Pull request by Joelgranados**
Update linuxHeaders to the latest available version of the linuxKernel.

### CODE REVIEW

**Comment by FliegendeWurst** [comment]
Could also update to 6.12 now that it is released.

**Comment by Joelgranados** [comment]
That seems like a good thing to do. I have a couple of questions before I go and change it once more.
1. How does the PR process for this package work? What I don't have clear is what is the criteria for the PR to go into master nix? I can change it now, but in a month and a half, the Linux kernel will have moved again and then we are back in the situation of having to updated it.
2. The PR is against master, but I do not really know if that is the right place to put it. Should I make one for 24.05? the next release? Should it stay on master.
Thx

**Comment by FliegendeWurst** [comment]
I think it should go to staging. Kernel updates usually go to master but this is not really a Kernel package.

There are no maintainers listed for the package so it might be a while before someone merges.

**Comment by fpletz** [comment]
Already updated in staging to 6.12 by #356972.

**Pull request closed without merging**
