### PR TITLE
Allow overriding features

### PR DESCRIPTION
**Pull request by szaffarano**
###### Description of changes

This PR allows overriding crate features, for instance:

```
pkgs.git-credential-keepassxc.override { withNotification = true; withYubikey = true; };
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by szaffarano** [comment]
@fgaz Since you are this package maintainer, I'd appreciate if you take a look :)
Thanks!

**Comment by szaffarano** [comment]
@ofborg @fgaz any news about it?
Thanks

**Comment by fgaz** [comment]
Is there any disadvantage in enabling them all by default?

**Comment by szaffarano** [comment]
> Is there any disadvantage in enabling them all by default?
Hi @fgaz by enabling `strict caller`,  `git-credential-keepassxc` will stop working in non-configured environments (eg., you have to configure the binaries allowed to use it, for instance, git, zsh, fish, etc.).
Also, enabling `notification` will start showing notifications, for instance when someone (eg git) reads a key.

IMHO the second one could be acceptable, but the first one shouldn't be enabled by default.

Thanks!

**Comment by alyssais** [comment]
Please remember to follow the commit message guidelines in CONTRIBUTING.md!

**Comment by fgaz** [comment]
Oops, sorry, I usually check it

**Pull request merged**
