### PR TITLE
Revert "coreutils: 8.32 -> 9.0" for darwin only

### PR DESCRIPTION
**Pull request by happysalada**
This reverts coreutils upgrade just for darwin.

For more information see the details on https://github.com/NixOS/nixpkgs/pull/141684#issuecomment-950678312

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasJ — APPROVED** [review]
Thank you, this is a lot better than downgrading for Linux as well

**Comment by r-burns** [comment]
@happysalada now that we have disabled SEEK_HOLE, would you be able to check if we can un-revert this on darwin? I would myself but I wasn't able to reproduce any of the darwin issues on my end.

**Comment by happysalada** [comment]
@r-burns happy to help, but what is it that needs testing ?
I've tested #139541 on darwin and it all went fine. (that PR uses 9.0 on darwin as well).
Do you mean to give staging-next one last test ?

**Comment by r-burns** [comment]
I'm referring to testing the go/rust issues we didn't notice originally, but you noticed on staging-next that resulted in this revert. I didn't encounter those myself but if you can confirm that they're no longer an issue, we can un-revert this, right?

**Comment by happysalada** [comment]
PR #139541 switches coreutils to version 9.0 for darwin as well. I tested the rust issues on that PR.
Therefore I think this current PR has already been reverted. (unless I'm missing something).

**Comment by happysalada** [comment]
opened a PR, currently testing it
https://github.com/NixOS/nixpkgs/pull/143800

**Pull request merged**
