### PR TITLE
gcc10: fix MinGW build & use local copy of mcfgthread patches

### LINKED ISSUE #107886: GCC 10 doesn't build for any MinGW configuration
**Describe the bug**
`mcfgthread` is [patched into GCC](https://github.com/NixOS/nixpkgs/blob/51ccf2d4badea4d709f8087e3fdb3fff3956d556/pkgs/development/compilers/gcc/10/default.nix#L64-L67) when building for MinGW, however an equivalent GCC 10 patch file doesn't exist. I tried looking for a GCC 10 patch on the master branch of https://github.com/lhmouse/MINGW-packages, but the `mingw-w64-gcc-git` folder that contained the patches no longer exists.

GCC9 is still currently the default on master, but this will break everything under MinGW the next time staging-next is merged to master. See https://github.com/NixOS/nixpkgs/pull/89793.

Support for `mcfgthread` was originally added in https://github.com/NixOS/nixpkgs/pull/73195.

**To Reproduce**
1. `nix-build '<nixpkgs>' -A pkgsCross.mingwW64.buildPackages.gcc10`

```
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download 9000-gcc-10-branch-Added-mcf-thread-model-support-from-mcfgthread.patch from any mirror
```

**Notify maintainers**
@Ericson2314 @Synthetica9 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.2, NixOS, 21.03.git.258134b2335 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre259798.84917aa00bf, nur"`
 - channels(kira): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgsCross.mingw32.buildPackages.gcc10, pkgsCross.mingwW64.buildPackages.gcc10
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by kira-bruneau**
###### Motivation for this change
Fixes #107886.

@Ericson2314 @matthewbauer What do you think of this approach that keeps a local copy? See #107918 for previous discussion.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@Synthetica9

### CODE REVIEW

**Review by matthewbauer — APPROVED** [review]

**Comment by matthewbauer** [comment]
Can you remove "mfcgthreads-patches-repo.nix" as well?

**Comment by MetaDark** [comment]
@matthewbauer Yep, it was already removed. When I was doing a self review I almost missed the change too :sweat_smile:

**Review by Ericson2314 — APPROVED** [review]
LGTM, but can we add a note in the update script saying `master` is force-pushed, hence why we do things this way?

**Review by Ericson2314 — APPROVED** [review]

**Comment by MetaDark** [comment]
@avnik Since https://github.com/NixOS/nixpkgs/pull/107783 was merged before this fix, `mingwSupport` for wine is now broken on master, but it should be okay to enable by default after this is merged.

**Comment by avnik** [comment]
@MetaDark not in next week or two definitely ;) I like to have wine 6.0 released (and merged) first as a next stable.

**Pull request merged**
