### PR TITLE
nixos/keycloak: Revert databaseUsername behavior and document custom local database use

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
Revert the change introduced in #117072: it's broken, since it doesn't configure the proper database username in keycloak when provisioning a local database with a custom username. Its intended behavior is also potentially confusing and dangerous, so rather than fixing it, let's revert to the old one and document how to use a custom local database instead. Also, change the test to make sure this doesn't happen again.

cc @em0lar 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by petabyteboy** [comment]
By using a custom local database, can I use a database with a database name != "keycloak"?

**Comment by talyz** [comment]
No, not currently. This applies to external databases, too - the `keycloak` database name is hard coded. It wouldn't be too hard to add an option for it, though.

**Comment by petabyteboy** [comment]
Okay, so we can still make a second attempt at this new functionality when we have the code to actually configure a custom database name. Sounds good and sorry for the troubles!

**Comment by talyz** [comment]
Yeah, the database name option can certainly be added, but I still don't think it's a good idea to have the provisioned database name and username be custimizable, since there are so many caveats to it. Essentially, you either choose to have something provisioned for you with a strong guarantee that the setup will work, or you set it up yourself and then you're on your own. The people who want / need custom names are probably already be pretty familiar with their database of choice, so setting it up manually should be a piece of cake for them.

**Pull request merged**
