### PR TITLE
nixos/nvidia: drop nvidia-vaapi-driver from 32bit drivers

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

nvidia-vaapi-driver is designed to work with firefox which is 64bit
only. On my system this adds almost 600 MiB closure size.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by abysssol — COMMENTED** [review]
> nvidia-vaapi-driver is designed to work with firefox which is 64bit only

Are you sure that `nvidia-vaapi-driver` has no uses other than Firefox?
According to the [wikipedia article on `VA-API`](https://en.wikipedia.org/wiki/Video_Acceleration_API):

> Video Acceleration API (VA-API) is an [open source](https://en.wikipedia.org/wiki/Open_source) [application programming interface](https://en.wikipedia.org/wiki/Application_programming_interface) that allows applications such as [VLC media player](https://en.wikipedia.org/wiki/VLC_media_player) or [GStreamer](https://en.wikipedia.org/wiki/GStreamer) to use hardware video acceleration capabilities, usually provided by the [graphics processing unit](https://en.wikipedia.org/wiki/Graphics_processing_unit) (GPU).

Maybe try conditionally enabling the 32 bit package instead?

``` nix
hardware.graphics =
  {
    extraPackages = [ pkgs.nvidia-vaapi-driver ];
  }
  // lib.optionalAttrs stdenv.isi686 {
    extraPackages32 = [ pkgs.pkgsi686Linux.nvidia-vaapi-driver ];
  };
```

**Comment by SuperSandro2000** [comment]
> Are you sure that nvidia-vaapi-driver has no uses other than Firefox?

Also gstreamer and vlc is almost certainly 64bit. The only 32 bit applications I know which are frequently used on NixOS are wine and steam.

> Maybe try conditionally enabling the 32 bit package instead?

We don't really support i686 standalone anyway, so there is no real point.

**Comment by Atemu** [comment]
> The only 32 bit applications I know which are frequently used on NixOS are wine and steam.

Those might still be using gstreamer and/or VAAPI internally.

**Review by fpletz — APPROVED** [review]
`nvidia-vaapi-driver` is designed to work with Firefox specifically. It is known to work with recent versions of `mpv` but Chromium will not work. See https://github.com/elFarto/nvidia-vaapi-driver. I think there is no use in having this available on i686.

**Review by abysssol — APPROVED** [review]
> `nvidia-vaapi-driver` is designed to work with Firefox specifically.

> We don't really support i686 standalone anyway, so there is no real point.

Good points.

Though it still seems to me that making `extraPackages32` conditional wouldn't hurt, and could potentially help. But considering that this change is exceedingly unlikely to negatively affect anyone, I now approve.

**Pull request merged**
