### PR TITLE
knot-dns: 3.3.9 -> 3.4.0

### PR DESCRIPTION
**Pull request by vcunat**
https://www.knot-dns.cz/docs/latest/html/migration.html#upgrade-3-3-x-to-3-4-x
https://gitlab.nic.cz/knot/knot-dns/-/releases/v3.4.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vcunat** [comment]
> This version brings DNS/XFR over TLS, DDNS over QUIC and TLS, continuous DNSSEC zone validation, XDP improvements, enhanced RRL, partially asynchronous processing of control commands, and more.

**Comment by vcunat** [comment]
I think we should keep release-24.05 on the 3.3 branch, as it remains maintained upstream for another year.

**Comment by mweinelt** [comment]
```
vm-test-run-prometheus-knot-exporter> knot # [   11.815793] knotd[832]: error: config, file '/nix/store/w9q98saqnyh2kgr4602vzmkvn0lz4nlp-knot.conf', line 9, item 'journal-db', value '/var/lib/knot/journal' (invalid item)
vm-test-run-prometheus-knot-exporter> knot # [   11.821736] knotd[832]: critical: failed to load configuration file '/nix/store/w9q98saqnyh2kgr4602vzmkvn0lz4nlp-knot.conf' (invalid item)

**Comment by vcunat** [comment]
Oh, I forgot that I only ran `knot-dns.tests` after `knot-dns` update, not after the other updates.

**Comment by mweinelt** [comment]
```patch
diff --git a/nixos/tests/prometheus-exporters.nix b/nixos/tests/prometheus-exporters.nix
index 6a4abab7cc12..3d12ff128e26 100644
--- a/nixos/tests/prometheus-exporters.nix
+++ b/nixos/tests/prometheus-exporters.nix
@@ -530,9 +530,6 @@ let
                 global-module: mod-stats
                 dnssec-signing: off
                 zonefile-sync: -1
-                journal-db: /var/lib/knot/journal
-                kasp-db: /var/lib/knot/kasp
-                timer-db: /var/lib/knot/timer
                 zonefile-load: difference
                 storage: ${pkgs.buildEnv {
                   name = "foo";

**Comment by mweinelt** [comment]
And let's add a release note entry for https://www.knot-dns.cz/docs/latest/html/migration.html#upgrade-3-3-x-to-3-4-x.

**Comment by vcunat** [comment]
Are you pushing (some of) this here or should I?  (you should have sufficient permissions)

**Comment by mweinelt** [comment]
> Are you pushing (some of) this here or should I? (you should have sufficient permissions)

Pushed some.

**Comment by vcunat** [comment]
OK.  I just called it 3.4.x, as by the time release happens it surely won't be 3.4.0 anymore.

**Pull request merged**
