### PR TITLE
pcsx2-bin: simplify updateScript

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

* https://github.com/NixOS/nixpkgs/pull/326590#discussion_r1684708244

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Artturin — APPROVED** [review]

**Comment by Artturin** [comment]
Thanks

**Comment by matteo-pacini** [comment]
Thanks for this 🙏🏻 bit of a busy week and didn't have much time to follow up on this

**Comment by matteo-pacini** [comment]
@pbsds Hi, I think we need to investigate on this change I bit - I noticed that since it was pushed r-ryantm has stopped publishing updates for the package?

https://r.ryantm.com/log/pcsx2-bin/

**Comment by pbsds** [comment]
it could be slow, lets give it some more time to see, if it continues to not work i'm happy to merge a revert

**Comment by matteo-pacini** [comment]
@pbsds it ran in the end, but exits with an error: https://r.ryantm.com/log/pcsx2-bin/2024-08-04.log

**Comment by pbsds** [comment]
that error is due to `platforms = [ "x86_64-darwin" ];` while the r-ryantm bot being x86_64-linux. It's simply unable to build `src` which tries to use darwin bash and tools. The fix is to write a different updateScript much like what i did here: https://github.com/NixOS/nixpkgs/pull/331758/commits/886068298f6a318d8bdcc3707972f5b78c56b589

The trick is that it uses `nix-prefetch-url` rather than building `src`

**Comment by matteo-pacini** [comment]
@pbsds Cold you please revert the update script?
The old one should work, as it's inspired from the other one I wrote for `miru`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/mi/miru/update.sh

Miru's one seems to work through r-ryantm:
#331935

**Comment by pbsds** [comment]
The miru one looks good, since it uses `nix-prefech-url` :+1:

This one however did not, and rather used `update-source-version` to implicitly run `nix-build . -A pcsx2-bin.src`.

https://github.com/NixOS/nixpkgs/blob/50773c2ed163efdb46ecb7ac75d1c64d30351f5d/pkgs/by-name/pc/pcsx2-bin/update.sh#L8

Reverting this will not work, please submit a new update script

**Pull request merged**
