### PR TITLE
[WIP] pokerth: init at 1.1.1

### PR DESCRIPTION
**Pull request by matthiasbeyer**
I'm failing here because `qmake` cannot find the boost libs.
I don't know how to fix this, maybe someone can help? 
(afaicr @ttuegel is a qt guy?)

### CODE REVIEW

**Comment by jagajaga** [comment]
There is no `default.nix` for this pkg in your PR.

**Comment by matthiasbeyer** [comment]
:cry: must have missed it on `git add` somehow... sry

**Comment by jagajaga** [comment]
We prefer 2 spaces indentation.

**Comment by jagajaga** [comment]
Take a look at https://github.com/NixOS/nixpkgs/blob/788800e437c4a0a25d95e217540bded68804b25e/pkgs/development/tools/misc/xxdiff/default.nix for example. Just grep for `qmake` in nixpkgs.

**Comment by matthiasbeyer** [comment]
The problem is that it doesn't find the boost libs. I'm not sure how to solve this. The `qmake` part works by now.

**Comment by ttuegel** [comment]
@matthiasbeyer I think you need to pass the `LIB_DIRS` option to `qmake` with the path to Boost.

**Comment by matthiasbeyer** [comment]
@ttuegel Hm, I did that now put it still tells me it cannot find them:

```
Project ERROR: Unable to find boost libraries in PREFIX=/nix/store/dan1jq9q0k9xwyjxpsdpv1kvjgqz67rx-pokerth-1.1.1
```

Actually, this error message looks fishy to me. Why would it search in the store path for pokerth itself?

**Pull request closed without merging**
