### PR TITLE
skypeforlinux: 8.66.0.74 -> 8.68.0.100

### PR DESCRIPTION
**Pull request by mohe2015**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mohe2015** [comment]
Result of `nixpkgs-review pr 112169` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>skype (skypeforlinux)</li>
  </ul>
</details>

**Review by mohe2015 — COMMENTED** [review]
It works.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112169` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>skypeforlinux</li>
</ul>
</details>

**Comment by jraygauthier** [comment]
@SuperSandro2000: I'm not sure I understand why you took @mohe2015 work as you own. Your version has exactly the same content as @mohe2015's, however, only you user appear as the final author of the merged changeset. It seems wrong to me...

**Comment by mohe2015** [comment]
@SuperSandro2000 may it be possible that your merge workflow is broken somehow. The expected thing is e.g. `@FRidh
r-ryantm authored and FRidh committed 16 days ago`. I looked back two weeks and it seems to be the same there for you.

**Comment by mohe2015** [comment]
Just found out that this is just a merge commit and the actual commit is https://github.com/NixOS/nixpkgs/commit/a68229eefbb234864352a9b582432ac480840110

**Comment by jraygauthier** [comment]
@mohe2015: Ok, I see, it even had the "Merge pull request #112169 from mohe2015/skypeforlinux " summary + the original commit as a parent which I apparently failed to notice.

**Comment by mohe2015** [comment]
I still think there is room for improvement like above but I think this applies to more mergers and I also don't know how this works.

**Pull request merged**
