### PR TITLE
markdown-oxide: 0.0.21 → 0.23.1

### PR DESCRIPTION
**Pull request by jukremer**
## Description of changes

@linsui Tried to implement #328893 but it doesn't compile. 

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:1
  |
1 | #![feature(async_closure)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated field `tower_lsp::lsp_types::SymbolInformation::deprecated`: Use tags instead
  --> src/symbol.rs:46:17
   |
46 |                 deprecated: None,
   |                 ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated field `tower_lsp::lsp_types::DocumentSymbol::deprecated`: Use tags instead
   --> src/symbol.rs:119:13
    |
119 |             deprecated: None,
    |             ^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
warning: `markdown-oxide` (bin "markdown-oxide") generated 2 warnings
error: could not compile `markdown-oxide` (bin "markdown-oxide") due to 1 previous error; 2 warnings emitted
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by linsui** [comment]
https://github.com/Feel-ix-343/markdown-oxide/issues/141

**Comment by jukremer** [comment]
> [Feel-ix-343/markdown-oxide#141](https://github.com/Feel-ix-343/markdown-oxide/issues/141)

So we need to wait for the next stable release?

**Comment by linsui** [comment]
You can

1. update to a unstable version
2. apply the commit as a patch
3. set `env.RUSTC_BOOTSTRAP = 1;` to use nightly features.

**Comment by jukremer** [comment]
> You can
> 
> 1. update to a unstable version
> 2. apply the commit as a patch
> 3. set `env.RUSTC_BOOTSTRAP = 1;` to use nightly features.

As the package maintainer, which would you recommend?

**Comment by linsui** [comment]
There is little difference.

**Pull request closed without merging**
