### PR TITLE
libwebp: build with cmake

### LINKED ISSUE #334148: libwebp: install cmake files
Package `ladybird` requires a webp cmake config file. `libwebp` installs its cmake config **only when built with cmake**. Unfortunately switching from configure/make to cmake seems complex or impossible due to the mismatched configure options.

In the meantime [I can patch one in](https://github.com/NixOS/nixpkgs/pull/334149/files#diff-8221d45aaad1c84b8cd381e1c5bdb706c961726b09b5a9ce6b1ab99881218e7eR83).

@ajs124

### PR DESCRIPTION
**Pull request by smancill**
## Description of changes

Replace Autotools build with CMake.

It results in the same output tree plus the CMake configuration files.

Closes #334148.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
You might want to consider including `ninja` in `nativeBuildInputs` for a faster build.

**Comment by smancill** [comment]
It's a small package, it won't make much difference.

**Comment by fgaz** [comment]
Nice! Could you try disabling the workaround in ladybird?

https://github.com/NixOS/nixpkgs/blob/6c31eb9b990446880000e3297f69f4fdee5b69d7/pkgs/applications/networking/browsers/ladybird/default.nix#L78-L85

Also I think this needs to target staging

**Comment by smancill** [comment]
I don't have a Linux machine to test Ladybird.

Once I see this working on master I'll move to stating.

**Comment by fgaz** [comment]
Seems to work!

```command
$ nix build github:smancill/nixpkgs/libwebp-build-with-cmake#ladybird.tests.nixosTest
```

screen

**Comment by smancill** [comment]
@ofborg build imagemagick
@ofborg build gd
@ofborg build skia
@ofborg build libtiff
@ofborg build imlib2

**Comment by smancill** [comment]
> @ofborg build imagemagick @ofborg build gd @ofborg build skia @ofborg build libtiff @ofborg build imlib2

There seem to be no issues when building dependencies.

**Comment by smancill** [comment]
Moved to `staging`.

**Review by fgaz — APPROVED** [review]
Oops, I forgot about this. Looks good, I'll merge later today.

**Comment by fgaz** [comment]
@GrahamcOfBorg eval

**Comment by alyssais** [comment]
Broke pkgsStatic.libwebp. Fix is https://github.com/NixOS/nixpkgs/pull/366566.

**Pull request merged**
