### PR TITLE
palemoon: install icons

### LINKED ISSUE #33770: palemoon: .desktop not executable, doesn't include icon in file.
## Issue description
I installed Pale Moon and I noticed it didn't show up in KDE, I checked the usr/share/applications/palemoon.desktop file and it is missing both the +x bit and the icon name. (Possibly missing the icon itself)

### Steps to reproduce
Install Pale Moon.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.11.0, NixOS, 18.03pre125026.f607771d0f5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre125026.f607771d0f5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Fix #33770 

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using (none)
- [x] Tested execution of all binary files
- [x] Tested the icons are picked up by the DE (xfce at least)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build palemoon

**Comment by Mic92** [comment]
Is darwin also affected by this?

**Comment by rnhmjoj** [comment]
I think the darwin build has always been failing.

**Comment by Mic92** [comment]
Maybe we should disable or mark palemoon as broken then?

**Comment by rnhmjoj** [comment]
Upstream says it's supported so it would be nice if we get it to work. I don't have osx to test it though.

**Pull request merged**
