### PR TITLE
nodejs_20: 20.11.1 -> 20.12.0

### PR DESCRIPTION
**Pull request by marsam**
Changelog: https://github.com/nodejs/node/releases/tag/v20.12.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bradzacher** [comment]
I notice this was merged into `staging` and not `master`.
What's the workflow for promoting this to `master`?

**Comment by jakubm-canva** [comment]
@marsam - is there a timeline to promote to master?

**Comment by marsam** [comment]
Hi, sorry for the delay

>I notice this was merged into staging and not master.

yes, I usually send `nodejs_20` to staging, because building it locally is resource intensive, and it may hurt contributors that use `master` branch. However, security releases always land in `master` first.

>What's the workflow for promoting this to master?

Do you mean the `staging` workflow? I think it's documented in [RFC 26](https://github.com/NixOS/rfcs/blob/master/rfcs/0026-staging-workflow.md) and [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#flow-of-merged-pull-requests). 

>is there a timeline to promote to master?

The previous `staging-next` branch was merged [a couple of days ago](https://github.com/NixOS/nixpkgs/pull/298548). So, I expect this to land in `master` during the week of April 15.

btw, is there anything in this version that could have been better if it landed in `master` first?

**Comment by jakubm-canva** [comment]
There is an important fix that makes the network connections not to fail: https://github.com/nodejs/node/pull/51045
That's pretty much all in it.

**Comment by jakubm-canva** [comment]
@marsam - any updates on the merge to master?

**Comment by vcunat** [comment]
Generally you can use tools like https://nixpk.gs/pr-tracker.html?pr=299327

**Comment by bradzacher** [comment]
That would be great to have a bot auto-post that link for discoverability!

**Pull request merged**
