### PR TITLE
php.packages.platformsh: init at 3.78.0

### PR DESCRIPTION
**Pull request by shyim**
###### Description of changes

Added platform.sh cli to nixpkgs. 

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
Nice, I like the inclusion of the update script !

**Comment by shyim** [comment]
I can add them for all php packages if wanted :)

**Comment by drupol** [comment]
I know there is already a bot which does it automatically if the hosting repository is GitHub.

However, could you, just for my personal knowledge explain in a few words how you trigger that script ?

**Comment by shyim** [comment]
```shell
nix-shell maintainers/scripts/update.nix --argstr package php.packages.platformsh
```

**Comment by shyim** [comment]
As far I know this bot updates them automaticly then https://github.com/ryantm/nixpkgs-update see https://github.com/NixOS/nixpkgs/pull/165470

**Comment by drupol** [comment]
Ok, then the bot uses the script hook your created.

I have the feeling that it's not needed in this case as this project is hosted in Github. Ryantm bot is already able to check Github releases and provides updates automatically.

**Review by etu — CHANGES_REQUESTED** [review]
Hey,

This seems like a great tool to have in Nix, but I would question if it's really a "PHP Package", just because it's "built on PHP" doesn't make it a "PHP Package".

This tool doesn't seem to care if it's running on php74, php80 or php81, Therefore we don't really need to package three different versions of it either.

So I think the main package declaration should belong somewhere else... maybe `pkgs/applications/misc/`. Then it shouldn't be part of `php.packages` either, I think we should put it directly in `pkgs/top-level/all-packages.nix`.

This way it's easier to discover and we only ship one version of it.

**Comment by shyim** [comment]
Totally understandable. I will move it :)

**Pull request closed without merging**
