### PR TITLE
haskellPackages.hercules-ci-*: update

### PR DESCRIPTION
**Pull request by roberth**
## Description of changes

This is an ad hoc update ahead of haskell-updates because of a build issue introduced by https://github.com/NixOS/nixpkgs/pull/312433

I'll take care of any merge conflicts.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by roberth** [comment]
@ofborg build hci hercules-ci-agent cachix

**Comment by maralorn** [comment]
Ah, you are right hercules-ci-agent builds just fine on haskell-updates even though the cachix bump is included there.
I think the haskell-updates branch is in really good shape right now. Maybe we can just merge it quickly instead of doing this high volume fix?
@ncfavier what do you think?

**Comment by ncfavier** [comment]
Sounds good.

**Review by maralorn — CHANGES_REQUESTED** [review]
Since hercules-ci is now fixed on master I suggest not doing this dance.

**Comment by roberth** [comment]
Hmm, branch-off is on Wednesday.
Unless we can merge https://github.com/NixOS/nixpkgs/pull/312934 before that, I'm going to have to do something like this anyway, at least for the `release-24.05` branch.

**Comment by sternenseemann** [comment]
It would be my goal to get that into 24.05. If all fails, it'll just have to be in the first staging iteration for that release.

**Pull request closed without merging**
