### PR TITLE
ligo: 0.53 -> 0.54

### PR DESCRIPTION
**Pull request by ulrikstrid**
###### Description of changes

`bls12-381` and `resto` breaks current LIGO version so needs to go in at the same time, the other packages can go in separately.
~~Opening as draft until 0.54 is tagged~~ 0.54.0 is now released and this is ready to go.

- [x] #197494
- [x] #197507

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mindavi — CHANGES_REQUESTED** [review]
Fix the commit message, otherwise good to go. Are the failing platforms as expected? Maybe should be marked broken?

**Comment by ulrikstrid** [comment]
@Mindavi how are you seeing what platforms are failing? I think it should at least build on these, at least it has built at some point:
- x86_64-linux
- aarch64-darwin
- x86_64-darwin

**Comment by Mindavi** [comment]
I looked at the ofborg logs:
- https://github.com/NixOS/nixpkgs/pull/197508/checks?check_run_id=9125977319
- https://github.com/NixOS/nixpkgs/pull/197508/checks?check_run_id=9126015140

Let's try rebuilding

@ofborg build

**Comment by ulrikstrid** [comment]
I think the failures are fine and I assume they are there already

**Pull request merged**
