### PR TITLE
python312Packages.pyscard: fix build

### LINKED ISSUE #352598: Build failure: pythonPackages.pyscard
### Steps To Reproduce

1. build *python312Packages.pycard*

### Build log

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-build-hook
Using pypaBuildPhase
Sourcing python-runtime-deps-check-hook
Using pythonRuntimeDepsCheckHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing pytest-check-hook
Using pytestCheckPhase
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/maq7s5q6k10y75cjxag1kb8i26kfzj5s-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/tox.ini
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
substituteStream() in derivation python3.12-pyscard-2.1.1: WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'setup.py')
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Executing pypaBuildPhase
Creating a wheel...
* Getting build dependencies for wheel...
/nix/store/nxgx33hs40fc9qrrn3y9g4wv0db8pmhy-python3.12-setuptools-75.1.0/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
running egg_info
creating pyscard.egg-info
writing pyscard.egg-info/PKG-INFO
writing dependency_links to pyscard.egg-info/dependency_links.txt
writing requirements to pyscard.egg-info/requires.txt
writing top-level names to pyscard.egg-info/top_level.txt
writing manifest file 'pyscard.egg-info/SOURCES.txt'
reading manifest file 'pyscard.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.html' under directory 'smartcard/doc'
warning: no files found matching '*.css' under directory 'smartcard/doc'
warning: no files found matching '*.js' under directory 'smartcard/doc'
warning: no files found matching '*.txt' under directory 'smartcard/doc'
adding license file 'LICENSE'
writing manifest file 'pyscard.egg-info/SOURCES.txt'

ERROR Missing dependencies:
	swig
```

### Notify maintainers

@layus 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11.20241029.4e9ddbc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/z7nwbkp1kqj9502mzlqaxy9ijgxz9sah-source`
 ```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by itepastra**
this package got a build failure in 2bdb00de8d93cd17e13096b39fd3fff1807375ed, 
this was because swig got added to the required build-inputs. 
Adding it to the nix build-inputs did not work so I made a replace which fixed it.

closes #352598

ZHF #352882

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by itepastra** [comment]
Hmm, how it is now the `yubikey-manager-qt` package crashes seconds after starting. So there's probably something still wrong

**Comment by Aleksanaa** [comment]
> Adding it to the nix build-inputs did not work so I made a replace which fixed it.

Because you've not packaged https://pypi.org/project/swig/ ? Swig doesn't have python binding itself.

This is not a fix.

**Comment by itepastra** [comment]
I've packaged swig-pypi, the swig bindings for python and used that package for pyscard instead.
It looks like it uses swig correctly in the build now

**Comment by Aleksanaa** [comment]
@natsukium is it needed to keep attribute name the same with pypi name?

**Comment by NickCao** [comment]
Better fix in https://github.com/NixOS/nixpkgs/pull/353230, and upstream issue for yubikey-manager-qt: https://github.com/Yubico/yubikey-manager-qt/issues/366

**Comment by natsukium** [comment]
> is it needed to keep attribute name the same with pypi name?

Yes, the pypi name needs to be adopted and then normalized according to PEP503.

> Attribute names in python-packages.nix as well as pnames should match the library's name on PyPI, but be normalized according to [PEP 0503](https://www.python.org/dev/peps/pep-0503/#normalized-names). This means that characters should be converted to lowercase and . and _ should be replaced by a single - (foo-bar-baz instead of Foo__Bar.baz). If necessary, pname has to be given a different value within fetchPypi.

https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#contributing-guidelines-contributing-guidelines

**Comment by natsukium** [comment]
Regarding swig-pypi, if we want to package it, we should create our own stub like cmake/ninja.

**Comment by itepastra** [comment]
I will make a stub like cmake/ninja for swig if we want to, but this branch isn't needed anymore

**Pull request closed without merging**
