### PR TITLE
xone: init package and module

### PR DESCRIPTION
**Pull request by rhysmdnz**
###### Motivation for this change
This adds a package and a module for [xone](https://github.com/medusalix/xone), a kernel driver for Xbox One and Xbox Series X|S accessories.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JJJollyjim** [comment]
Reviewed and tested build on both stable and latest kernels, lgtm.

**Comment by hpfr** [comment]
For people who want to use `xone` with new controllers and `xpad` with old ones simultaneously, a module option to enable https://github.com/medusalix/xpad-noone might be useful. Not a blocker, but as long as you're hacking on this and all :)

**Comment by kevincox** [comment]
Result of `nixpkgs-review pr 161008` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>linuxPackages.xone (linuxKernel.packages.linux_5_10.xone)</li>
    <li>linuxPackages_hardened.xone (linuxPackages_5_10_hardened.xone)</li>
    <li>linuxKernel.packages.linux_5_15.xone</li>
    <li>linuxPackages_5_15_hardened.xone (linuxKernel.packages.linux_5_15_hardened.xone)</li>
    <li>linuxPackages_latest.xone (linuxKernel.packages.linux_5_16.xone)</li>
    <li>linuxKernel.packages.linux_5_4.xone</li>
    <li>linuxPackages_5_4_hardened.xone (linuxKernel.packages.linux_5_4_hardened.xone)</li>
    <li>linuxPackages_latest-libre.xone (linuxKernel.packages.linux_latest_libre.xone)</li>
    <li>linuxPackages-libre.xone (linuxKernel.packages.linux_libre.xone)</li>
    <li>linuxPackages_lqx.xone (linuxKernel.packages.linux_lqx.xone)</li>
    <li>linuxPackages_testing_bcachefs.xone (linuxKernel.packages.linux_testing_bcachefs.xone)</li>
    <li>linuxPackages_xanmod.xone (linuxKernel.packages.linux_xanmod.xone)</li>
    <li>linuxPackages_zen.xone (linuxKernel.packages.linux_zen.xone)</li>
    <li>xow_dongle-firmware</li>
  </ul>
</details>

**Pull request merged**
