### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Another iteration is here ([docs](https://nixos.org/manual/nixpkgs/stable/#submitting-changes-staging-next-branch)): https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents (soon)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131345` at 859acbc1 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>336 packages marked as broken and skipped:</summary>
  <ul>
    <li>SDL_sixel</li>
    <li>adobe-reader</li>
    <li>adoptopenjdk-hotspot-bin-13</li>
    <li>adoptopenjdk-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-hotspot-bin-13</li>
    <li>adoptopenjdk-jre-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-openj9-bin-13</li>
    <li>adoptopenjdk-jre-openj9-bin-14</li>
    <li>adoptopenjdk-openj9-bin-13</li>
    <li>adoptopenjdk-openj9-bin-14</li>
    <li>airtame</li>
    <li>autotrace</li>
    <li>blastem</li>
    <li>botan</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>ccrtp</li>
    <li>checkinstall</li>
    <li>clang-sierraHack</li>
    <li>clang-sierraHack-stdenv</li>
    <li>clickshare-csc1</li>
    <li>curaByDagoma</li>
    <li>cura_stable</li>
    <li>darwin.CF</li>
    <li>dcraw</li>
    <li>displaycal</li>
    <li>dvd-slideshow</li>
    <li>eagle7</li>
    <li>electron_3</li>
    <li>electron_4</li>
    <li>electron_5</li>
    <li>epsxe</li>
    <li>erlang_basho_R16B02</li>
    <li>eterm</li>
    <li>evilvte</li>
    <li>ffmpeg-sixel</li>
    <li>ffmpeg_2</li>
    <li>ffmpeg_2_8</li>
    <li>ffmpeg_3</li>
    <li>ffmpeg_3_4</li>
    <li>fscryptctl-experimental</li>
    <li>git-dit</li>
    <li>gitin</li>
    <li>globalplatform</li>
    <li>gnash</li>
    <li>gnuradio3_7</li>
    <li>gnuradio3_7Packages.ais</li>
    <li>gnuradio3_7Packages.gnuradio</li>
    <li>gnuradio3_7Packages.gsm</li>
    <li>gnuradio3_7Packages.limesdr</li>
    <li>gnuradio3_7Packages.nacl</li>
    <li>gnuradio3_7Packages.osmosdr</li>
    <li>gnuradio3_7Packages.rds</li>
    <li>go_1_14</li>
    <li>gogoclient</li>
    <li>googleearth-pro</li>
    <li>gppcscconnectionplugin</li>
    <li>gpshell</li>
    <li>grass</li>
    <li>green-pdfviewer</li>
    <li>gtmess</li>
    <li>gvpe</li>
    <li>hadoop</li>
    <li>hadoop_2_7</li>
    <li>hadoop_2_8</li>
    <li>hadoop_2_9</li>
    <li>hplipWithPlugin_3_16_11</li>
    <li>hplip_3_16_11</li>
    <li>ima-evm-utils</li>
    <li>imapproxy</li>
    <li>impressive</li>
    <li>intecture-cli</li>
    <li>invoice2data</li>
    <li>ipsecTools</li>
    <li>jboss</li>
    <li>jfbpdf</li>
    <li>jfbview</li>
    <li>julia</li>
    <li>julia-bin</li>
    <li>julia-lts</li>
    <li>julia-lts-bin</li>
    <li>julia_10</li>
    <li>julia_10-bin</li>
    <li>k2pdfopt</li>
    <li>keyfinder</li>
    <li>libav</li>
    <li>libav_0_8</li>
    <li>libav_11</li>
    <li>libav_12</li>
    <li>libgcrypt_1_5</li>
    <li>libgit2_0_27</li>
    <li>libgroove</li>
    <li>libnats-c</li>
    <li>libsixel</li>
    <li>libvirt_5_9_0</li>
    <li>limesurvey</li>
    <li>linuxPackages_hardkernel_4_14.acpi_call</li>
    <li>linuxPackages_hardkernel_4_14.akvcam</li>
    <li>linuxPackages_hardkernel_4_14.amdgpu-pro</li>
    <li>linuxPackages_hardkernel_4_14.anbox</li>
    <li>linuxPackages_hardkernel_4_14.apfs</li>
    <li>linuxPackages_hardkernel_4_14.asus-wmi-sensors</li>
    <li>linuxPackages_hardkernel_4_14.batman_adv</li>
    <li>linuxPackages_hardkernel_4_14.bbswitch</li>
    <li>linuxPackages_hardkernel_4_14.bcc</li>
    <li>linuxPackages_hardkernel_4_14.bpftrace</li>
    <li>linuxPackages_hardkernel_4_14.broadcom_sta</li>
    <li>linuxPackages_hardkernel_4_14.can-isotp</li>
    <li>linuxPackages_hardkernel_4_14.chipsec</li>
    <li>linuxPackages_hardkernel_4_14.cryptodev</li>
    <li>linuxPackages_hardkernel_4_14.ddcci-driver</li>
    <li>linuxPackages_hardkernel_4_14.digimend</li>
    <li>linuxPackages_hardkernel_4_14.dpdk-kmods</li>
    <li>linuxPackages_hardkernel_4_14.ena</li>
    <li>linuxPackages_hardkernel_4_14.evdi</li>
    <li>linuxPackages_hardkernel_4_14.exfat-nofuse</li>
    <li>linuxPackages_hardkernel_4_14.facetimehd</li>
    <li>linuxPackages_hardkernel_4_14.fwts-efi-runtime</li>
    <li>linuxPackages_hardkernel_4_14.gcadapter-oc-kmod</li>
    <li>linuxPackages_hardkernel_4_14.hid-nintendo</li>
    <li>linuxPackages_hardkernel_4_14.isgx</li>
    <li>linuxPackages_hardkernel_4_14.it87</li>
    <li>linuxPackages_hardkernel_4_14.ixgbevf</li>
    <li>linuxPackages_hardkernel_4_14.jool</li>
    <li>linuxPackages_hardkernel_4_14.kvmfr</li>
    <li>linuxPackages_hardkernel_4_14.lttng-modules</li>
    <li>linuxPackages_hardkernel_4_14.mba6x_bl</li>
    <li>linuxPackages_hardkernel_4_14.mbp2018-bridge-drv</li>
    <li>linuxPackages_hardkernel_4_14.mwprocapture</li>
    <li>linuxPackages_hardkernel_4_14.mxu11x0</li>
    <li>linuxPackages_hardkernel_4_14.ndiswrapper</li>
    <li>linuxPackages_hardkernel_4_14.netatop</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11_beta</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11_legacy340</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_hardkernel_4_14.nvidiabl</li>
    <li>linuxPackages_hardkernel_4_14.openafs</li>
    <li>linuxPackages_hardkernel_4_14.openafs_1_8</li>
    <li>linuxPackages_hardkernel_4_14.openafs_1_9</li>
    <li>linuxPackages_hardkernel_4_14.openrazer</li>
    <li>linuxPackages_hardkernel_4_14.phc-intel</li>
    <li>linuxPackages_hardkernel_4_14.prl-tools</li>
    <li>linuxPackages_hardkernel_4_14.r8125</li>
    <li>linuxPackages_hardkernel_4_14.r8168</li>
    <li>linuxPackages_hardkernel_4_14.rtl8188eus-aircrack</li>
    <li>linuxPackages_hardkernel_4_14.rtl8192eu</li>
    <li>linuxPackages_hardkernel_4_14.rtl8723bs</li>
    <li>linuxPackages_hardkernel_4_14.rtl8812au</li>
    <li>linuxPackages_hardkernel_4_14.rtl8814au</li>
    <li>linuxPackages_hardkernel_4_14.rtl8821au</li>
    <li>linuxPackages_hardkernel_4_14.rtl8821ce</li>
    <li>linuxPackages_hardkernel_4_14.rtl8821cu</li>
    <li>linuxPackages_hardkernel_4_14.rtl88x2bu</li>
    <li>linuxPackages_hardkernel_4_14.rtl88xxau-aircrack</li>
    <li>linuxPackages_hardkernel_4_14.rtlwifi_new</li>
    <li>linuxPackages_hardkernel_4_14.rtw88</li>
    <li>linuxPackages_hardkernel_4_14.rtw89</li>
    <li>linuxPackages_hardkernel_4_14.sch_cake</li>
    <li>linuxPackages_hardkernel_4_14.sysdig</li>
    <li>linuxPackages_hardkernel_4_14.system76</li>
    <li>linuxPackages_hardkernel_4_14.system76-acpi</li>
    <li>linuxPackages_hardkernel_4_14.system76-io</li>
    <li>linuxPackages_hardkernel_4_14.systemtap</li>
    <li>linuxPackages_hardkernel_4_14.tbs</li>
    <li>linuxPackages_hardkernel_4_14.tp_smapi</li>
    <li>linuxPackages_hardkernel_4_14.tuxedo-keyboard</li>
    <li>linuxPackages_hardkernel_4_14.v4l2loopback</li>
    <li>linuxPackages_hardkernel_4_14.v86d</li>
    <li>linuxPackages_hardkernel_4_14.veikk-linux-driver</li>
    <li>linuxPackages_hardkernel_4_14.vendor-reset</li>
    <li>linuxPackages_hardkernel_4_14.vhba</li>
    <li>linuxPackages_hardkernel_4_14.virtualbox</li>
    <li>linuxPackages_hardkernel_4_14.virtualboxGuestAdditions</li>
    <li>linuxPackages_hardkernel_4_14.wireguard</li>
    <li>linuxPackages_hardkernel_4_14.xmm7360-pci</li>
    <li>linuxPackages_hardkernel_4_14.xpadneo</li>
    <li>linuxPackages_hardkernel_4_14.zenpower</li>
    <li>linuxPackages_hardkernel_4_14.zfs</li>
    <li>linuxPackages_hardkernel_4_14.zfsStable</li>
    <li>linuxPackages_hardkernel_4_14.zfsUnstable</li>
    <li>linuxPackages_hardkernel_latest.acpi_call</li>
    <li>linuxPackages_hardkernel_latest.akvcam</li>
    <li>linuxPackages_hardkernel_latest.amdgpu-pro</li>
    <li>linuxPackages_hardkernel_latest.anbox</li>
    <li>linuxPackages_hardkernel_latest.apfs</li>
    <li>linuxPackages_hardkernel_latest.asus-wmi-sensors</li>
    <li>linuxPackages_hardkernel_latest.batman_adv</li>
    <li>linuxPackages_hardkernel_latest.bbswitch</li>
    <li>linuxPackages_hardkernel_latest.bcc</li>
    <li>linuxPackages_hardkernel_latest.bpftrace</li>
    <li>linuxPackages_hardkernel_latest.broadcom_sta</li>
    <li>linuxPackages_hardkernel_latest.can-isotp</li>
    <li>linuxPackages_hardkernel_latest.chipsec</li>
    <li>linuxPackages_hardkernel_latest.cryptodev</li>
    <li>linuxPackages_hardkernel_latest.ddcci-driver</li>
    <li>linuxPackages_hardkernel_latest.digimend</li>
    <li>linuxPackages_hardkernel_latest.dpdk-kmods</li>
    <li>linuxPackages_hardkernel_latest.ena</li>
    <li>linuxPackages_hardkernel_latest.evdi</li>
    <li>linuxPackages_hardkernel_latest.exfat-nofuse</li>
    <li>linuxPackages_hardkernel_latest.facetimehd</li>
    <li>linuxPackages_hardkernel_latest.fwts-efi-runtime</li>
    <li>linuxPackages_hardkernel_latest.gcadapter-oc-kmod</li>
    <li>linuxPackages_hardkernel_latest.hid-nintendo</li>
    <li>linuxPackages_hardkernel_latest.isgx</li>
    <li>linuxPackages_hardkernel_latest.it87</li>
    <li>linuxPackages_hardkernel_latest.ixgbevf</li>
    <li>linuxPackages_hardkernel_latest.jool</li>
    <li>linuxPackages_hardkernel_latest.kvmfr</li>
    <li>linuxPackages_hardkernel_latest.lttng-modules</li>
    <li>linuxPackages_hardkernel_latest.mba6x_bl</li>
    <li>linuxPackages_hardkernel_latest.mbp2018-bridge-drv</li>
    <li>linuxPackages_hardkernel_latest.mwprocapture</li>
    <li>linuxPackages_hardkernel_latest.mxu11x0</li>
    <li>linuxPackages_hardkernel_latest.ndiswrapper</li>
    <li>linuxPackages_hardkernel_latest.netatop</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_beta</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy340</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_hardkernel_latest.nvidiabl</li>
    <li>linuxPackages_hardkernel_latest.openafs</li>
    <li>linuxPackages_hardkernel_latest.openafs_1_8</li>
    <li>linuxPackages_hardkernel_latest.openafs_1_9</li>
    <li>linuxPackages_hardkernel_latest.openrazer</li>
    <li>linuxPackages_hardkernel_latest.phc-intel</li>
    <li>linuxPackages_hardkernel_latest.prl-tools</li>
    <li>linuxPackages_hardkernel_latest.r8125</li>
    <li>linuxPackages_hardkernel_latest.r8168</li>
    <li>linuxPackages_hardkernel_latest.rtl8188eus-aircrack</li>
    <li>linuxPackages_hardkernel_latest.rtl8192eu</li>
    <li>linuxPackages_hardkernel_latest.rtl8723bs</li>
    <li>linuxPackages_hardkernel_latest.rtl8812au</li>
    <li>linuxPackages_hardkernel_latest.rtl8814au</li>
    <li>linuxPackages_hardkernel_latest.rtl8821au</li>
    <li>linuxPackages_hardkernel_latest.rtl8821ce</li>
    <li>linuxPackages_hardkernel_latest.rtl8821cu</li>
    <li>linuxPackages_hardkernel_latest.rtl88x2bu</li>
    <li>linuxPackages_hardkernel_latest.rtl88xxau-aircrack</li>
    <li>linuxPackages_hardkernel_latest.rtlwifi_new</li>
    <li>linuxPackages_hardkernel_latest.rtw88</li>
    <li>linuxPackages_hardkernel_latest.rtw89</li>
    <li>linuxPackages_hardkernel_latest.sch_cake</li>
    <li>linuxPackages_hardkernel_latest.sysdig</li>
    <li>linuxPackages_hardkernel_latest.system76</li>
    <li>linuxPackages_hardkernel_latest.system76-acpi</li>
    <li>linuxPackages_hardkernel_latest.system76-io</li>
    <li>linuxPackages_hardkernel_latest.systemtap</li>
    <li>linuxPackages_hardkernel_latest.tbs</li>
    <li>linuxPackages_hardkernel_latest.tp_smapi</li>
    <li>linuxPackages_hardkernel_latest.tuxedo-keyboard</li>
    <li>linuxPackages_hardkernel_latest.v4l2loopback</li>
    <li>linuxPackages_hardkernel_latest.v86d</li>
    <li>linuxPackages_hardkernel_latest.veikk-linux-driver</li>
    <li>linuxPackages_hardkernel_latest.vendor-reset</li>
    <li>linuxPackages_hardkernel_latest.vhba</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.virtualboxGuestAdditions</li>
    <li>linuxPackages_hardkernel_latest.wireguard</li>
    <li>linuxPackages_hardkernel_latest.xmm7360-pci</li>
    <li>linuxPackages_hardkernel_latest.xpadneo</li>
    <li>linuxPackages_hardkernel_latest.zenpower</li>
    <li>linuxPackages_hardkernel_latest.zfs</li>
    <li>linuxPackages_hardkernel_latest.zfsStable</li>
    <li>linuxPackages_hardkernel_latest.zfsUnstable</li>
    <li>loxodo</li>
    <li>metamorphose2</li>
    <li>mfcl8690cdwcupswrapper</li>
    <li>mrxvt</li>
    <li>mupdf_1_17</li>
    <li>mysocketw</li>
    <li>natron</li>
    <li>neon_0_29</li>
    <li>nomad_0_12</li>
    <li>numatop</li>
    <li>obinskit</li>
    <li>ocropus</li>
    <li>odpdown</li>
    <li>odroid-xu3-bootloader</li>
    <li>openrw</li>
    <li>openssh_gssapi</li>
    <li>openssh_hpn</li>
    <li>openssl_1_0_2</li>
    <li>opentsdb</li>
    <li>oven-media-engine</li>
    <li>ovftool</li>
    <li>pbis-open</li>
    <li>pcsxr</li>
    <li>pdfdiff</li>
    <li>pgadmin</li>
    <li>pig</li>
    <li>plover.stable</li>
    <li>polipo</li>
    <li>proxytunnel</li>
    <li>rainbowstream</li>
    <li>riak</li>
    <li>ring-daemon</li>
    <li>rxvt</li>
    <li>scallion</li>
    <li>scribus</li>
    <li>scyther</li>
    <li>shellinabox</li>
    <li>sipwitch</li>
    <li>softether_4_25</li>
    <li>spark</li>
    <li>staruml</li>
    <li>stepmania</li>
    <li>swftools</li>
    <li>swift</li>
    <li>termplay</li>
    <li>thrift-0_10</li>
    <li>torchat</li>
    <li>tvheadend</li>
    <li>twinkle</li>
    <li>ucommon</li>
    <li>ucommon_openssl</li>
    <li>unicap</li>
    <li>unifi-video</li>
    <li>vdrPlugins.markad</li>
    <li>vdrPlugins.vaapidevice</li>
    <li>vdrPlugins.xineliboutput</li>
    <li>virtuoso</li>
    <li>virtuoso6</li>
    <li>virtuoso7</li>
    <li>volatility</li>
    <li>vp</li>
    <li>vtun</li>
    <li>winpdb</li>
    <li>wraith</li>
    <li>xorg.libAppleWM</li>
    <li>xpdf</li>
    <li>xsw</li>
    <li>zgv</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/7a6daa0a2442b2bd179679225271fba8">haxor-news</a></li>
    <li><a href="https://gist.github.com/4887858d4d12a8a247a8286d85371960">iptraf</a></li>
  </ul>
</details>
<details>
  <summary>38125 packages skipped due to time constraints:</summary>
  <ul>
    <li>AMB-plugins</li>
    <li>AusweisApp2</li>
    <li>CHOWTapeModel</li>
    <li>CoinMP</li>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>EmptyEpsilon</li>
    <li>FIL-plugins</li>
    <li>Fabric (python39Packages.Fabric)</li>
    <li>LAStools</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>162 packages built successfully:</summary>
  <ul>
    <li>alsa-topology-conf</li>
    <li>asciidoc</li>
    <li>at-spi2-atk</li>
    <li>at-spi2-core</li>
    <li>atk (gnome.atk ,gnome2.atk)</li>
    <li>attr</li>
    <li>avahi</li>
    <li>bintools-unwrapped (binutils-unwrapped)</li>
    <li>bitlbee</li>
    <li>bkyml</li>
    <li>cairo (gnome2.cairo)</li>
    <li>clickhouse-cli (python39Packages.clickhouse-cli)</li>
    <li>cups</li>
    <li>daq</li>
    <li>dbus</li>
    <li>dbus-glib</li>
    <li>dconf (gnome.dconf ,xfce.dconf)</li>
    <li>disnix</li>
    <li>dysnomia</li>
    <li>eigen</li>
    <li>expat</li>
    <li>faac</li>
    <li>fftwFloat (fftwSinglePrec)</li>
    <li>file</li>
    <li>flex</li>
    <li>freetype</li>
    <li>gdk-pixbuf (gnome.gdk-pixbuf)</li>
    <li>gobject-introspection (gnome.gobject-introspection)</li>
    <li>gsettings-desktop-schemas (gnome.gsettings-desktop-schemas)</li>
    <li>libgudev (gnome.libgudev)</li>
    <li>pango (gnome2.pango)</li>
    <li>gnuchess</li>
    <li>harfbuzz</li>
    <li>ii</li>
    <li>iputils</li>
    <li>irssi_fish</li>
    <li>json-glib</li>
    <li>kbd</li>
    <li>libGLU (mesa_glu)</li>
    <li>libaom</li>
    <li>libass</li>
    <li>libbluray</li>
    <li>libbytesize</li>
    <li>libcap</li>
    <li>libcap_ng</li>
    <li>libdvdcss</li>
    <li>libdvdread</li>
    <li>libfabric</li>
    <li>libgpgerror</li>
    <li>libgpgerror-gen-posix-lock-obj</li>
    <li>libinput</li>
    <li>libndp</li>
    <li>libotr</li>
    <li>libpfm</li>
    <li>libspotify</li>
    <li>libusb1</li>
    <li>libva</li>
    <li>libva-minimal</li>
    <li>libwacom</li>
    <li>libxkbcommon (libxkbcommon_8)</li>
    <li>libxml2Python</li>
    <li>lispPackages.alexandria</li>
    <li>litecli</li>
    <li>lsb-release</li>
    <li>luaPackages.cjson (lua52Packages.cjson)</li>
    <li>lua5_2 (lua52Packages.lua ,luaPackages.lua)</li>
    <li>mdk4</li>
    <li>minipro</li>
    <li>mmh</li>
    <li>netsurf.buildsystem</li>
    <li>nettools</li>
    <li>nlohmann_json</li>
    <li>nspr</li>
    <li>offrss</li>
    <li>onlykey-cli</li>
    <li>opentracker</li>
    <li>ophis</li>
    <li>perl534Packages.HTTPCookies</li>
    <li>perl534Packages.ParseYapp</li>
    <li>perl534Packages.TimeDate</li>
    <li>piston-cli</li>
    <li>pkg-config</li>
    <li>python38Packages.azure-common</li>
    <li>python38Packages.bootstrapped-pip</li>
    <li>python38Packages.click</li>
    <li>python38Packages.click-repl</li>
    <li>python38Packages.clickhouse-cli</li>
    <li>python38Packages.clintermission</li>
    <li>python38Packages.defusedxml</li>
    <li>python38Packages.flaky</li>
    <li>python38Packages.iso8601</li>
    <li>python38Packages.outcome</li>
    <li>python38Packages.pip</li>
    <li>python38Packages.pipBuildHook</li>
    <li>python38Packages.prompt-toolkit</li>
    <li>python38Packages.pyroma</li>
    <li>python38Packages.pytest-localserver</li>
    <li>python38Packages.ruamel-yaml (python38Packages.ruamel_yaml)</li>
    <li>python38Packages.ruamel-yaml-clib (python38Packages.ruamel_yaml_clib)</li>
    <li>python38Packages.serpent</li>
    <li>python38Packages.setuptools</li>
    <li>python38Packages.simplejson</li>
    <li>python38Packages.sphinxcontrib-devhelp</li>
    <li>python38Packages.wurlitzer</li>
    <li>python39Packages.Babel</li>
    <li>python39Packages.bootstrapped-pip</li>
    <li>python39Packages.cli-helpers</li>
    <li>python39Packages.click-repl</li>
    <li>python39Packages.clintermission</li>
    <li>python39Packages.cython</li>
    <li>python39Packages.freezegun</li>
    <li>python39Packages.hidapi</li>
    <li>python39Packages.ipython_genutils</li>
    <li>python39Packages.iso8601</li>
    <li>python39Packages.libevdev</li>
    <li>python39Packages.libxml2</li>
    <li>python39Packages.pip</li>
    <li>python39Packages.prompt-toolkit</li>
    <li>python39Packages.pycairo</li>
    <li>python39Packages.pygobject3</li>
    <li>python39Packages.pyroma</li>
    <li>python39Packages.pytestCheckHook</li>
    <li>python39Packages.re-assert</li>
    <li>python39Packages.recursivePthLoader</li>
    <li>python39Packages.setuptools</li>
    <li>python39Packages.simplejson</li>
    <li>python39Packages.sphinxcontrib-htmlhelp</li>
    <li>python39Packages.traitlets</li>
    <li>python39Packages.yarl</li>
    <li>ratox</li>
    <li>removeReferencesTo</li>
    <li>ronn</li>
    <li>rrsync</li>
    <li>rsync</li>
    <li>rtmpdump</li>
    <li>rtmpdump_gnutls</li>
    <li>setJavaClassPath</li>
    <li>shared-mime-info</li>
    <li>siproxd</li>
    <li>speexdsp</li>
    <li>unicode-emoji</li>
    <li>usrsctp</li>
    <li>uthash</li>
    <li>vivaldi-widevine</li>
    <li>wayland-protocols</li>
    <li>wayland-scanner</li>
    <li>weechatScripts.weechat-matrix-bridge</li>
    <li>wrapGAppsNoGuiHook</li>
    <li>xkbvalidate</li>
    <li>xorg.libXtst</li>
    <li>xvidcore</li>
    <li>znc</li>
    <li>zncModules.backlog</li>
    <li>zncModules.clientaway</li>
    <li>zncModules.clientbuffer</li>
    <li>zncModules.fish</li>
    <li>zncModules.ignore</li>
    <li>zncModules.palaver</li>
    <li>zncModules.playback</li>
    <li>zncModules.privmsg</li>
    <li>zncModules.push</li>
    <li>zstd</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by vcunat** [comment]
- [ ] [python39Packages.astroid](https://hydra.nixos.org/job/nixpkgs/staging-next/python39Packages.astroid.x86_64-linux) will be blocking NixOS tests/channel.  (It's not well visible in this jobset.)

**Comment by FRidh** [comment]
`zstd` fails to build on darwin, both `aarch64` and `x86_64`, and is a big blocker. Failure is identical https://hydra.nixos.org/build/148574691
cc @NixOS/darwin-maintainers

**Comment by vcunat** [comment]
The `zstd` error seems easy, fortunately.  It should be fixed now.

**Comment by mweinelt** [comment]
Looks like you rolled back the apache-directory-studio update in the latest merge commit.

b17d7516f2b9dcfd22b9e2064167e82d54ae15d7

**Comment by FRidh** [comment]
Merge conflict only showed the desktopitem at a different location, nothing else as far as I could tell.

**Comment by FRidh** [comment]
Should be fixed now.

**Pull request merged**
