### PR TITLE
libvirt: 8.1.0 -> 8.4.0

### PR DESCRIPTION
**Pull request by Kranzes**
-  libvirt: 8.1.0 -> 8.4.0
- python3Packages.libvirt: 8.1.0 -> 8.4.0
- perlPackages.SysVirt: 8.1.0 -> 8.4.0

###### Things done
Tested creating a new virtual machine.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
@ofborg build libvirt

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 170615` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixops_unstable</li>
  </ul>
</details>
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>perl534Packages.SysVirt</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>rubyPackages_3_1.ruby-libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
  </ul>
</details>

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 170615` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>libvmi</li>
  </ul>
</details>
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>haskellPackages.libvirt-hs</li>
    <li>libguestfs</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixops_unstable</li>
    <li>perl532Packages.SysVirt</li>
    <li>perl534Packages.SysVirt</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>rubyPackages.ruby-libvirt (rubyPackages_2_7.ruby-libvirt)</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>rubyPackages_3_1.ruby-libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
  </ul>
</details>

**Review by fufexan — APPROVED** [review]

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 170615` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixops_unstable</li>
  </ul>
</details>
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>perl534Packages.SysVirt</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>rubyPackages_3_1.ruby-libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
  </ul>
</details>

**Review by stigtsp — COMMENTED** [review]
Diff LGTM for `perlPackages.SysVirt`

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.SysVirt

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 170615` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>libvmi</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixops_unstable</li>
  </ul>
</details>
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>haskellPackages.libvirt-hs</li>
    <li>libguestfs</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>perl532Packages.SysVirt</li>
    <li>perl534Packages.SysVirt</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>rubyPackages.ruby-libvirt (rubyPackages_2_7.ruby-libvirt)</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>rubyPackages_3_1.ruby-libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
  </ul>
</details>

**Pull request merged**
