### PR TITLE
aider-chat: add playwright version

### PR DESCRIPTION
**Pull request by happysalada**
## Things done

Add a variant with playwright to make it more convenient to use the full features.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354796`

---
### `x86_64-darwin`

**Comment by KenMacD** [comment]
Was there supposed to be in `input` for this? I see some other packages use code like:

```nix
, extras ? [ "hjson" "json5" "toml" "xml" "yaml" ]
...
  propagatedBuildInputs = with python3.pkgs; [
    ...
  ] ++ lib.attrVals extras optional-dependencies;
...
optional-dependencies = with python3.pkgs; {
    hjson = [ hjson ];
    json5 = [ json5 ];
    toml = [ toml ];
    xml = [ xmltodict ];
    yaml = [ pyyaml ];
  };
```

(That's from https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ji/jinja2-cli/package.nix)

**Comment by happysalada** [comment]
No i didnt want to have an input, just wanted to add the optional dependencies progressively. The project also has a browser set of optional dependencies but i didnt want to try too much, i just added the playwright ones.
Id be happy to take prs for other sets of optional dependencies from the project that i didnt add.

**Comment by johnkferguson** [comment]
Hey, I'm a bit new to `nix` and `home-manager`. How are you supposed to configure this so `aider` has access to `playwright`?

I have `home-manager` setup with:

```nix
packages = with pkgs; [
      aider-chat.withPlaywright
      chromium
      python3Packages.playwright
    ];
```

I've tried it with different combinations of the above, but whenever I invoke the `/web` command within aider, it asks me if I want to install `playwright`. Am I supposed to be setting this up differently? Thanks.

**Comment by happysalada** [comment]
Im on darwin and so i couldnt test this properly since chromium isnt available.
This should work with just adding chromium.
Most likely some environment variable needs to be set in a certain way.
The aider code needs to be checked, its probably trying to do more.
In the 0.65 update to prevent the update prompt it was a matter of setting an environment variable. I imagine its something similar in this casw, but more digging needs to be done.

**Comment by softinio** [comment]
> Hey, I'm a bit new to `nix` and `home-manager`. How are you supposed to configure this so `aider` has access to `playwright`?
> 
> I have `home-manager` setup with:
> 
> ```nix
> packages = with pkgs; [
>       aider-chat.withPlaywright
>       chromium
>       python3Packages.playwright
>     ];
> ```
> 
> I've tried it with different combinations of the above, but whenever I invoke the `/web` command within aider, it asks me if I want to install `playwright`. Am I supposed to be setting this up differently? Thanks.

@johnkferguson Having the same issue, did you solve this? Thanks for help.

**Comment by johnkferguson** [comment]
@softinio No, I was never able to solve it. I can get aider to work, but not with playwright.

**Comment by mjmaurer** [comment]
@softinio @johnkferguson FYI I opened an issue and PR for this: https://github.com/NixOS/nixpkgs/issues/385961

If you're eager, you can just copy over the derivation and use it locally instead of cloning nixpkgs. Here's mine: https://github.com/mjmaurer/infra/blob/main/home-manager/modules/aider/aider-deriv.nix

**Comment by softinio** [comment]
@mjmaurer thank you ! You are awesome.

**Comment by softinio** [comment]
@mjmaurer with your derivation I still get:

image

any thoughts?

**Comment by mjmaurer** [comment]
@softinio as far as I can tell, aider [just uses playwright](https://aider.chat/docs/install/optional.html#enable-playwright) for the `/web` command, which is what my change addresses.

It looks like there's a separate issue for the browser changes: https://github.com/NixOS/nixpkgs/issues/367141

**Comment by softinio** [comment]
> @softinio as far as I can tell, aider [just uses playwright](https://aider.chat/docs/install/optional.html#enable-playwright) for the `/web` command, which is what my change addresses.
> 
> It looks like there's a separate issue for the browser changes: #367141

@mjmaurer got it, I didn't realize that as never used it. Thanks for clarification and thanks for getting the PR done to fix issue. Appreciated the derivation too! Have a great weekend.

**Pull request merged**
