### PR TITLE
nixos/switch-to-configuration: Improve socket handling

### PR DESCRIPTION
**Pull request by dasJ**
We are now restarting sockets as well so things like permission or owner
changes are properly applied when they are changed.

We also stop the service before reloading systemd and restart the socket
instead of the service if `serviceConfig.stopIfChanged` is not set.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dasJ** [comment]
The history of me force-pushing this PR might show how much fun I had but this is now tested on a production server with socket-activated units (no path-activated units I could test with):
1) If the socket was dead previously, it was started on switch
2) If the socket was changed and the service was dead, the socket got stopped and restarted
3) If the socket was changed and the service was active, both were stopped and the socket got restarted
4) If the service was changed and the service was dead, nothing happened
5) If the service was changed and the service was active, both were stopped and the socket got restarted
6) If both were changed and the service was dead, the same as 2) happened
7) If both were changed and the service was active, the same as 5) happened

I explicitly differentiated between getting restarted and getting stopped and started.

cc @arianvp

**Comment by dasJ** [comment]
Slices are now tested as well. It seem slike systemd just aplies the new limits when I change the slice and do `systemctl daemon-reload`.

**Comment by aanderse** [comment]
> If the service was changed and the service was active, both were stopped and the socket got restarted

I was expecting you to say that the service was untouched in this scenario. Isn't one of the benefits of socket activation that the socket can stay up and queue connections while the service restarts?

**Comment by dasJ** [comment]
@aanderse I'm assuming you mean that you expected the socket to stay untouched since stopping the service when it changed makes sense to me.

Yes, that would be great and it also was my initial implementation. This does lead to a race, however. Say we have a socket-activated unit and something that takes ages to stop, like Confluence. We stop the service and Confluence and the service immediately stops while Confluence runs into the 1m30s limit. That gives the socket 1m30s to activate the **old** service because we haven't reloaded systemd at this point since this is done after all services that are to be stopped are stopped.

To make matters a bit less bad, I'm stopping the socket and then restart it as opposed to starting it since that is a couple of seconds earlier.

**Comment by aanderse** [comment]
Ah thanks for the explanation. I hadn't considered that scenario. If you think it worthwhile maybe a quick note in the code would be beneficial.

I'm really glad to see someone working on this script. Thank you!

**Comment by dasJ** [comment]
Is this enough? https://github.com/NixOS/nixpkgs/pull/140668/files#diff-c5a656ad8eb4fd2a44c6523c5cfc4f0b670c231054f9f0533f78702ca06b8764R254

**Comment by roberth** [comment]
> is now tested on a production server

Do test cases exist for the current switch behavior? Will you add new test cases?

This is code is terrifying because of its importance.

The tests should also include a test case that shows that socket activation still works when the socket is unchanged.

You could write a simple echo server that waits for certain file paths to appear at times where the test script needs to control the order of certain events. For example, I think you'll need it to wait before exiting the process on service shutdown.

**Comment by dasJ** [comment]
Related:

image

**Pull request closed without merging**
