### PR TITLE
cudatoolkit_11: cudatoolkit_11_4 → cudatoolkit_11_6

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Description of changes

Been using colmap with this change

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kevincox** [comment]
Result of `nixpkgs-review pr 165021` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>cudnn_8_1_cudatoolkit_11</li>
    <li>cudnn_8_3_cudatoolkit_11</li>
    <li>katagoWithCuda</li>
    <li>python310Packages.cupy</li>
    <li>python39Packages.cupy</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>colmapWithCuda</li>
    <li>cudatoolkit_11 (cudaPackages.cudatoolkit_11)</li>
    <li>forge</li>
    <li>gromacsCudaMpi</li>
    <li>nccl_cudatoolkit_11</li>
    <li>python310Packages.jaxlibWithCuda</li>
    <li>python39Packages.jaxlibWithCuda</li>
    <li>python39Packages.tensorflowWithCuda</li>
  </ul>
</details>

**Comment by samuela** [comment]
This change broke cudnn, cupy, and every other package that depends on those packages including the much of TensorFlow, PyTorch, and JAX ecosystems. Basically lots of things depend on cudnn. I know mistakes happen but next time please cc @NixOS/cuda-maintainers.

Please follow up with a fix bumping cudatoolkit_11 back down to cudatoolkit_11_5, the latest version that is supported by cudnn_8_3. Otherwise, I'll go ahead and revert tomorrow.

**Comment by fabianhjr** [comment]
I apologize, I was not aware of that specific team and missed mentioning, creating PR going back to 11_5.

**Comment by samuela** [comment]
That's alright, just wanted to let you know! Thanks for promptly fixing!

**Comment by kevincox** [comment]
Is it possible to get tests on some of these packages? Or is it too difficult because they require special hardware?

**Comment by SomeoneSerge** [comment]
@kevincox in this particular case no special hardware is required, we could have caught the error just by evaluating the out paths, without actually building the packages

**Comment by samuela** [comment]
> Is it possible to get tests on some of these packages? Or is it too difficult because they require special hardware?

It's possible to build CUDA-related packages on machines without GPUs, just not possible to run them. The challenge tends to be that CUDA-related packages are rather massive, eg. pytorch, tensorflow, etc. But in the spirit of developing tests for these packages I created https://github.com/samuela/cuda-nix-testsuite/, which I'm hoping may improve the process for everyone.

**Comment by kevincox** [comment]
Why didn't nixpkgs-review raise an error then? Does it incorrectly skip packages that went from successful evaluations to unsuccessful evaluations?

**Comment by samuela** [comment]
That's a great question... I have no idea! I've gotten weird results from nixpkgs-review in the past as well. My guess is that it's bc cudnn will mark itself broken if used with an incompatible cudatoolkit version. So it could be that packages were transitively marked broken as a result and not built. Problem being that they shouldn't have switched from working -> broken. 

Another thing I can't explain is why it didn't pick up pytorchWithCuda in your run of nixpkgs-review... I'm truly stumped.

**Pull request merged**
