### PR TITLE
elm: update to latest revs

### PR DESCRIPTION
**Pull request by jgillich**
Some tags were updated with bug fixes. Also fixed update-elm.rb to
include the callPackage argument for release.nix.

### CODE REVIEW

**Comment by abbradar** [comment]
Strange that the script was broken -- I don't remember fixing anything manually. Either way, thanks!

**Comment by domenkozar** [comment]
The version should use the correct formatting, as it's not really `0.16` release.

**Comment by abbradar** [comment]
It's `0.16`, upstream updated it in-place. See for example https://github.com/elm-lang/elm-compiler/tree/0.16, revision is identical to the updated one. Updating tags this way is a bad upstream practice, but that's another question...

**Comment by domenkozar** [comment]
Thanks for the explanation, I'll bug the upstream.

**Pull request merged**
