### PR TITLE
python3Packages.tinycss2, python3Packages.cssselect2: cleanup tests

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

I noticed that #91967 and #91941 both fixed tinycss2's tests in different ways, but did not cause a conflict because they touched different parts of the file. I kept the upstream patch, as it seems like the better solution.

I also noticed that #91364 had, in my opinion, a better fix for cssselect2's tests, but appears to have been superseded by #91941, so I included that patch in this PR as well.

cc @colemickens @misuzu @drewrisinger
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
LGTM, thanks!

**Comment by drewrisinger** [comment]
@GrahamcOfBorg build python37Packages.cssselect2 python38Packages.cssselect2 python37Packages.tinycss2 python38Packages.tinycss2

**Review by drewrisinger — APPROVED** [review]
I have a slight preference to not worrying about code style (i.e. ``flake8, import sort``) when packaging python packages, but not enough to add/maintain specific patches like this. 

* [x] Diff LGTM
* [x] Commits LGTM
* [x] Builds cleanly via ``nix-review``
* [x] Build has built-in tests, no extra tests run.

```
https://github.com/NixOS/nixpkgs/pull/92496
15 packages built:
python37Packages.cairosvg python37Packages.cssselect2 python37Packages.pygal python37Packages.qasm2image python37Packages.tinycss2 python37Packages.weasyprint python37Packages.xml2rfc python38Packages.cairosvg python38Packages.cssselect2 python38Packages.pygal python38Packages.qasm2image python38Packages.tinycss2 python38Packages.weasyprint xml2rfc sourcehut.metasrht
```

**Review by jonringer — APPROVED** [review]
```
https://github.com/NixOS/nixpkgs/pull/92496
2 packages marked as broken and skipped:
python37Packages.qasm2image python38Packages.qasm2image

13 packages built:
python37Packages.cairosvg python37Packages.cssselect2 python37Packages.pygal python37Packages.tinycss2 python37Packages.weasyprint python37Packages.xml2rfc python38Packages.cairosvg python38Packages.cssselect2 python38Packages.pygal python38Packages.tinycss2 python38Packages.weasyprint xml2rfc sourcehut.metasrht
```

**Pull request merged**
