### PR TITLE
Revert "[Backport release-23.05] linux: fix hash for 6.5.2"

### PR DESCRIPTION
**Pull request by delroth**
Reverts NixOS/nixpkgs#254413

This shouldn't have been merged before #254360

### CODE REVIEW

**Comment by delroth** [comment]
```
$ nix-build . -A linux_6_5
these 3 derivations will be built:
  /nix/store/y0vfxnwm3cnqscxih29lk5i112khiksh-linux-6.5.1.tar.xz.drv
  /nix/store/xlgclgpz8pmvf84xagbl1kcsndamjm3r-linux-config-6.5.1.drv
  /nix/store/vj7sr5l363vnxkmqwb5v7axb0ss6y8ny-linux-6.5.1.drv
building '/nix/store/y0vfxnwm3cnqscxih29lk5i112khiksh-linux-6.5.1.tar.xz.drv'...

trying https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.5.1.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  132M  100  132M    0     0  11.4M      0  0:00:11  0:00:11 --:--:-- 12.0M
error: hash mismatch in fixed-output derivation '/nix/store/y0vfxnwm3cnqscxih29lk5i112khiksh-linux-6.5.1.tar.xz.drv':
         specified: sha256-ICfhQFfVaK093BANrfTIhTpJsDEnBHimHYj2ARVyZQ8=
            got:    sha256-I3Zd1EQlRizZKtvuUmcGCP1/P9GDqDslunp7SIPQRRs=
error: 1 dependencies of derivation '/nix/store/vj7sr5l363vnxkmqwb5v7axb0ss6y8ny-linux-6.5.1.drv' failed to build
```

**Comment by alyssais** [comment]
Can we put reasons for reverts in the commit message, please?

**Comment by delroth** [comment]
Sure - with the tradeoff that if this revert wasn't a two-button-clicks operation in the GH web UI I'm not sure I'd have bothered last night vs. just leaving a comment. And the branch's HEAD would have been broken for longer.

**Comment by Ma27** [comment]
fwiw you can edit the message of the merge-commit on merging. Anyways, sorry again for the mess... I'll double-check 6.5 on the other backport PR (and build the src with `--check` now!) just to be sure.

**Pull request merged**
