### PR TITLE
apk-tools: fix build on darwin

### PR DESCRIPTION
**Pull request by siraben**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
Nice, this definitely gets us closer. Unfortunately it looks like there are some bits which are harder to work around, like the `futimens` and `utimensat` calls which require the 10.13 SDK. I think any patches to add macos support should be upstreamed since they'd end up being pretty extensive.

**Comment by siraben** [comment]
For those without darwin machines, here's the build log ATM.

<details>

<summary>Build log</summary>

```
$ nix-build -A apk-tools                                     
these derivations will be built:
  /nix/store/5jr6rvs3xczl9f1q2azs469l5jhijakw-apk-tools-2.10.5.drv
building '/nix/store/5jr6rvs3xczl9f1q2azs469l5jhijakw-apk-tools-2.10.5.drv'...
unpacking sources
unpacking source archive /nix/store/720yapms12br0qfd0px2k9m4h263asiv-apk-tools-2.10.5.tar.xz
source root is apk-tools-2.10.5
setting SOURCE_DATE_EPOCH to timestamp 1582035588 of file apk-tools-2.10.5/test/version.sh
patching sources
configuring
no configure script, doing nothing
building
build flags: -j4 -l4 SHELL=/nix/store/8i9kyqfxhk2s9dzx32x0sgdk7kyx9wjc-bash-4.4-p23/bin/bash CC=cc SBINDIR=\$\(out\)/bin LIBDIR=\$\(out\)/lib LUA_LIBDIR=\$\(out\)/lib/lua/5.3 MANDIR=\$\(out\)/share/man DOCDIR=\$\(out\)/share/doc/apk INCLUDEDIR=\$\(out\)/include PKGCONFIGDIR=\$\(out\)/lib/pkgconfig
  GENERR  libfetch/ftperr.h
  GENERR  libfetch/httperr.h
  CC      libfetch/common.o
  CC      libfetch/ftp.o
  CC      libfetch/http.o
  CC      libfetch/openssl-compat.o
  CC      libfetch/file.o
  CC      libfetch/fetch.o
  AR      libfetch/libfetch.a
/nix/store/ksks2lqixy6d9wxj6gwsd1c9r94ajsaa-cctools-port-949.0.1/bin/ranlib: file: libfetch/libfetch.a(openssl-compat.o) has no symbols
  CC      src/archive.o
  CC      src/blob.o
src/archive.c:480:33: error: too many arguments to function call, expected 3, have 4
                r = mknod(atfd, fn, ae->mode, ae->device);
                    ~~~~~                     ^~~~~~~~~~
/nix/store/qbbl5g6l5kx3zwjmkbcwflrzfrk6by0g-Libsystem-osx-10.12.6/include/sys/stat.h:359:1: note: 'mknod' declared here
int     mknod(const char *, mode_t, dev_t);
^
src/archive.c:513:73: error: too few arguments to function call, expected 6, have 5
                                if (fsetxattr(fd, xattr->name, xattr->value.ptr, xattr->value.len, 0) < 0) {
                                    ~~~~~~~~~                                                       ^
/nix/store/qbbl5g6l5kx3zwjmkbcwflrzfrk6by0g-Libsystem-osx-10.12.6/include/sys/xattr.h:67:1: note: 'fsetxattr' declared here
int fsetxattr(int fd, const char *name, const void *value, size_t size, u_int32_t position, int options);
^
src/archive.c:536:7: error: implicit declaration of function 'utimensat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                r = utimensat(atfd, fn, times, atflags);
                    ^
src/archive.c:536:7: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
4 errors generated.
make[1]: *** [Make.rules:202: src/archive.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Make.rules:288: src/] Error 2
builder for '/nix/store/5jr6rvs3xczl9f1q2azs469l5jhijakw-apk-tools-2.10.5.drv' failed with exit code 2
error: build of '/nix/store/5jr6rvs3xczl9f1q2azs469l5jhijakw-apk-tools-2.10.5.drv' failed
```

</details>

**Comment by siraben** [comment]
@r-burns Is the 10.13 SDK available for use on nixpkgs yet?

**Comment by r-burns** [comment]
Nope, we're still on 10.13. I don't know what the timescale is on the 10.13 update but I know it's nontrivial. I'll open an issue for this and see if I can get some more info.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101125` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>alpine-make-vm-image</li>
    <li>apk-tools</li>
  </ul>
</details>

**Comment by wegank** [comment]
Closed by #191605.

**Pull request closed without merging**
