### PR TITLE
nushell: 0.95.0 -> 0.96.0

### PR DESCRIPTION
**Pull request by 1adept**
## Description of changes

Updated nushell to 0.96.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by xanderio** [comment]
Result of `nixpkgs-review pr 329681` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>nushell</li>
    <li>nushellPlugins.formats</li>
    <li>nushellPlugins.gstat</li>
    <li>nushellPlugins.polars</li>
    <li>nushellPlugins.query</li>
  </ul>
</details>

**Comment by happysalada** [comment]
The change looks good, why did the nixpkgs review fail ?
Ofborg is passing too, this looks good to me

**Comment by 1adept** [comment]
> The change looks good, why did the nixpkgs review fail ? Ofborg is passing too, this looks good to me

It failed because i didn't update the plugins at first. I tried using `nix-update` to update the plugins but it apparently cannot update those because they inherit version from nushell and are therefore always "up to date".

With my latest push and correctly updated plugins it should work now

**Comment by xanderio** [comment]
Result of `nixpkgs-review pr 329681` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>nushell</li>
    <li>nushellPlugins.query</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>nushellPlugins.formats</li>
    <li>nushellPlugins.gstat</li>
    <li>nushellPlugins.polars</li>
  </ul>
</details>

**Comment by xanderio** [comment]
nushell_plugin_query-0.96.0:
```
┃        > error: linking with `/nix/store/k8mrxviw965lv59hqbln3297jwfffm2w-clang-wrapper-16.0.6/bin/cc` failed: exit status: 1
┃        >   |
┃        >   = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/nix/store/8wjjv08wbm62l74xbn6nh3w48xv44hfl-rustc-1.78.0/lib/rustlib/aarch64-appl…
┃        >   = note: ld: library not found for -lcurl
┃        >           clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
┃        >
┃        >
┃        > error: could not compile `nu_plugin_query` (bin "nu_plugin_query") due to 1 previous error
```

For nushell itself there are multiple test failures.
```
test result: FAILED. 1209 passed; 101 failed; 24 ignored; 0 measured; 4 filtered out; finished in 241.09s
```

**Comment by happysalada** [comment]
If there is a pattern for the failed tests we can try to add the pattern to ignore the tests.
If there isnt we can disable check and add a comment saying that too many tests fail for now.

For the query plugin it looks like its missing curl as a dependency. Im not sure how to include curl for a rust project. If you find an example of rust project using curl, you can copy, otherwise we have to figure it out. We can try by adding curl to the dependencies and see if that fixes the issue.

**Comment by 1adept** [comment]
`nixpkgs-review rev update-nushell` successfully build all packages after adding `pkg-config` and `openssl` to the query plugin.

Not sure what to do about the nushell test failures. I didnt see any on my end when building ...?

**Comment by happysalada** [comment]
If ofborg and someone else have the test failures it means they are there.
We should probably just disable the tests for now with a comment on why.

**Comment by 1adept** [comment]
Currently ofberg has 'only' queued the passthru tests for darwin. Isn't there a chance they can still pass ? `passthru`is 
>    tests.version = testers.testVersion {
>     package = nushell;
>    };
so it shouldn't fail or am i seeing it wrong?

How would i continue ? 
Should i disable `doCheck` for all systems or do something like `doCheck = ! stdenv.isDarwin; # Darwin tests fail since 0.96.0` since all other checks/tests apparently pass ?

**Comment by happysalada** [comment]
Yes disabling tests for darwin is the way to go IMO

**Comment by happysalada** [comment]
Thank you !

**Pull request merged**
