### PR TITLE
GHCJS: Fix 8.4 and add 8.6

### PR DESCRIPTION
**Pull request by ElvishJerricco**
###### Motivation for this change

Fixing up the GHCJS stuff. Keeping in line with the main haskellPackages being 8.6

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

P.S.: @peti how can I be automatically notified of GHCJS breaking in the future?

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
Is this `meta.maintainers = [lib.maintainers.elvishjerricco];` all I need to do for notifications when the build breaks?

**Comment by peti** [comment]
Yes, setting `meta.maintainer` will enable e-mail notifications from Hydra.

BTW, I wonder about ghcjs82. Will that build succeed after this PR?

**Review by peti — COMMENTED** [review]
Please resolve the merge conflict.

**Comment by ElvishJerricco** [comment]
8.4 and 8.6 finished. I've added a commit to remove 8.2. Let me know if you'd like me to change that. Otherwise, let's merge this before we have to make merge conflicts by marking them broken again ;)

**Review by peti — APPROVED** [review]
:+1: Very cool, thank you for your efforts!

**Comment by ElvishJerricco** [comment]
@peti can you merge this?

**Pull request merged**
