### PR TITLE
firefox: 87.0 -> 88.0; firefox-esr: 78.9.0esr -> 78.10.0esr

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://www.mozilla.org/en-US/firefox/88.0/releasenotes/
https://www.mozilla.org/en-US/firefox/78.10.0/releasenotes/

https://www.mozilla.org/en-US/security/advisories/mfsa2021-16/
https://www.mozilla.org/en-US/security/advisories/mfsa2021-15/

###### Things done

- Tested on
  - [x] x86_64, X11
  - [x] x86_64, Wayland
  - [ ] aarch64, X11
  - [ ] aarch64, Wayland
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
x86_64, X11 seems to work as well. Although I am seeing a bunch of `ERROR webrender::platform::unix::font] Unable to load glyph: 36` messages on stdout.

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 119862` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>adoptopenjdk-icedtea-web</li>
    <li>firefox-esr-78-unwrapped (firefoxPackages.firefox-esr-78)</li>
    <li>xulrunner (firefox-unwrapped)</li>
    <li>slimerjs</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 119862` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>adoptopenjdk-icedtea-web</li>
    <li>firefox-esr-78-unwrapped (firefoxPackages.firefox-esr-78)</li>
    <li>xulrunner (firefox-unwrapped)</li>
    <li>slimerjs</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Your nixpkgs-review only builds esr?

**Comment by lovesegfault** [comment]
> Your nixpkgs-review only builds esr?

It built `firefox` too, I'm certain since I ran it from the `nixpkgs-review` output. Not sure why only esr is showing in the logs :shrug:

**Pull request merged**
