### PR TITLE
lispPackages: fix darwin builds

### PR DESCRIPTION
**Pull request by babariviere**
###### Motivation for this change

Some packages don't compile on darwin since they require library finishing with `.dylib` extension.

Example: `cl-ffi-gtk-gdk` doesn't compile without this PR.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
So, on macOS: if you build `lispPackages`, there are no new failures (and some of the old go away)?

**Comment by babariviere** [comment]
Apparently. For now, I have only tested with cl-cffi-gtk-gdk because I need it, but I don't know what was the last build results for darwin.

I am currently running nixpkgs-review and I have 310 built packages with 3 fail for now. I am investigating these 3 to see if I can fix those.

**Comment by babariviere** [comment]
Result of `nixpkgs-review pr 124402` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>lispPackages.cl-cffi-gtk</li>
    <li>lispPackages.cl-dbi</li>
    <li>lispPackages.cl-fuse</li>
    <li>lispPackages.cl-fuse-meta-fs</li>
    <li>lispPackages.cl-mysql</li>
    <li>lispPackages.cl-webkit2</li>
    <li>lispPackages.dbd-mysql</li>
    <li>lispPackages.dbd-postgres</li>
    <li>lispPackages.dbd-sqlite3</li>
    <li>lispPackages.dbi</li>
    <li>lispPackages.dbi-test</li>
    <li>lispPackages.query-fs</li>
  </ul>
</details>
<details>
  <summary>308 packages built:</summary>
  <ul>
    <li>clpm</li>
    <li>lispPackages._3bmd</li>
    <li>lispPackages._3bmd-ext-code-blocks</li>
    <li>lispPackages.access</li>
    <li>lispPackages.acclimation</li>
    <li>lispPackages.agutil</li>
    <li>lispPackages.alexandria</li>
    <li>lispPackages.anaphora</li>
    <li>lispPackages.arnesi</li>
    <li>lispPackages.array-utils</li>
    <li>lispPackages.arrows</li>
    <li>lispPackages.asdf-package-system</li>
    <li>lispPackages.asdf-system-connections</li>
    <li>lispPackages.babel</li>
    <li>lispPackages.blackbird</li>
    <li>lispPackages.bordeaux-threads</li>
    <li>lispPackages.buildnode</li>
    <li>lispPackages.buildnode-xhtml</li>
    <li>lispPackages.calispel</li>
    <li>lispPackages.caveman</li>
    <li>lispPackages.cffi</li>
    <li>lispPackages.cffi-grovel</li>
    <li>lispPackages.cffi-toolchain</li>
    <li>lispPackages.cffi-uffi-compat</li>
    <li>lispPackages.chanl</li>
    <li>lispPackages.chipz</li>
    <li>lispPackages.chunga</li>
    <li>lispPackages.circular-streams</li>
    <li>lispPackages.cl-aa</li>
    <li>lispPackages.cl-annot</li>
    <li>lispPackages.cl-anonfun</li>
    <li>lispPackages.cl-ansi-text</li>
    <li>lispPackages.cl-async</li>
    <li>lispPackages.cl-async-repl</li>
    <li>lispPackages.cl-async-ssl</li>
    <li>lispPackages.cl-base64</li>
    <li>lispPackages.cl-cffi-gtk-cairo</li>
    <li>lispPackages.cl-cffi-gtk-gdk</li>
    <li>lispPackages.cl-cffi-gtk-gdk-pixbuf</li>
    <li>lispPackages.cl-cffi-gtk-gio</li>
    <li>lispPackages.cl-cffi-gtk-glib</li>
    <li>lispPackages.cl-cffi-gtk-gobject</li>
    <li>lispPackages.cl-cffi-gtk-pango</li>
    <li>lispPackages.cl-change-case</li>
    <li>lispPackages.cl-cli</li>
    <li>lispPackages.cl-colors</li>
    <li>lispPackages.cl-colors2</li>
    <li>lispPackages.cl-containers</li>
    <li>lispPackages.cl-cookie</li>
    <li>lispPackages.cl-css</li>
    <li>lispPackages.cl-csv</li>
    <li>lispPackages.cl-custom-hash-table</li>
    <li>lispPackages.cl-difflib</li>
    <li>lispPackages.cl-dot</li>
    <li>lispPackages.cl-emb</li>
    <li>lispPackages.cl-environments</li>
    <li>lispPackages.cl-fad</li>
    <li>lispPackages.cl-gobject-introspection</li>
    <li>lispPackages.cl-hooks</li>
    <li>lispPackages.cl-html-diff</li>
    <li>lispPackages.cl-html-parse</li>
    <li>lispPackages.cl-html5-parser</li>
    <li>lispPackages.cl-interpol</li>
    <li>lispPackages.cl-jpeg</li>
    <li>lispPackages.cl-json</li>
    <li>lispPackages.cl-l10n</li>
    <li>lispPackages.cl-l10n-cldr</li>
    <li>lispPackages.cl-libuv</li>
    <li>lispPackages.cl-locale</li>
    <li>lispPackages.cl-markup</li>
    <li>lispPackages.cl-paths</li>
    <li>lispPackages.cl-paths-ttf</li>
    <li>lispPackages.cl-pdf</li>
    <li>lispPackages.cl-postgres</li>
    <li>lispPackages.cl-postgres_plus_local-time</li>
    <li>lispPackages.cl-ppcre</li>
    <li>lispPackages.cl-ppcre-template</li>
    <li>lispPackages.cl-ppcre-unicode</li>
    <li>lispPackages.cl-prevalence</li>
    <li>lispPackages.cl-project</li>
    <li>lispPackages.cl-protobufs</li>
    <li>lispPackages.cl-qprint</li>
    <li>lispPackages.cl-reexport</li>
    <li>lispPackages.cl-slice</li>
    <li>lispPackages.cl-smtp</li>
    <li>lispPackages.cl-speedy-queue</li>
    <li>lispPackages.cl-store</li>
    <li>lispPackages.cl-syntax</li>
    <li>lispPackages.cl-syntax-annot</li>
    <li>lispPackages.cl-syntax-anonfun</li>
    <li>lispPackages.cl-syntax-markup</li>
    <li>lispPackages.cl-syslog</li>
    <li>lispPackages.cl-test-more</li>
    <li>lispPackages.cl-typesetting</li>
    <li>lispPackages.cl-unicode</li>
    <li>lispPackages.cl-unification</li>
    <li>lispPackages.cl-utilities</li>
    <li>lispPackages.cl-vectors</li>
    <li>lispPackages.cl-who</li>
    <li>lispPackages.cl-xmlspam</li>
    <li>lispPackages.cl_plus_ssl</li>
    <li>lispPackages.clack</li>
    <li>lispPackages.clack-handler-hunchentoot</li>
    <li>lispPackages.clack-socket</li>
    <li>lispPackages.clack-test</li>
    <li>lispPackages.clack-v1-compat</li>
    <li>lispPackages.clfswm</li>
    <li>lispPackages.closer-mop</li>
    <li>lispPackages.closure-common</li>
    <li>lispPackages.closure-html</li>
    <li>lispPackages.clsql</li>
    <li>lispPackages.clsql-postgresql</li>
    <li>lispPackages.clsql-postgresql-socket</li>
    <li>lispPackages.clsql-sqlite3</li>
    <li>lispPackages.clsql-uffi</li>
    <li>lispPackages.clss</li>
    <li>lispPackages.cluffer</li>
    <li>lispPackages.clump</li>
    <li>lispPackages.clump-2-3-tree</li>
    <li>lispPackages.clump-binary-tree</li>
    <li>lispPackages.clunit</li>
    <li>lispPackages.clunit2</li>
    <li>lispPackages.clwrapper</li>
    <li>lispPackages.clx</li>
    <li>lispPackages.clx-truetype</li>
    <li>lispPackages.collectors</li>
    <li>lispPackages.colorize</li>
    <li>lispPackages.command-line-arguments</li>
    <li>lispPackages.css-lite</li>
    <li>lispPackages.css-selectors</li>
    <li>lispPackages.css-selectors-simple-tree</li>
    <li>lispPackages.css-selectors-stp</li>
    <li>lispPackages.cxml</li>
    <li>lispPackages.cxml-stp</li>
    <li>lispPackages.dexador</li>
    <li>lispPackages.dissect</li>
    <li>lispPackages.djula</li>
    <li>lispPackages.do-urlencode</li>
    <li>lispPackages.documentation-utils</li>
    <li>lispPackages.drakma</li>
    <li>lispPackages.eager-future2</li>
    <li>lispPackages.enchant</li>
    <li>lispPackages.esrap</li>
    <li>lispPackages.esrap-peg</li>
    <li>lispPackages.external-program</li>
    <li>lispPackages.fare-csv</li>
    <li>lispPackages.fare-mop</li>
    <li>lispPackages.fare-quasiquote</li>
    <li>lispPackages.fare-quasiquote-extras</li>
    <li>lispPackages.fare-quasiquote-optima</li>
    <li>lispPackages.fare-quasiquote-readtable</li>
    <li>lispPackages.fare-utils</li>
    <li>lispPackages.fast-http</li>
    <li>lispPackages.fast-io</li>
    <li>lispPackages.fiasco</li>
    <li>lispPackages.file-attributes</li>
    <li>lispPackages.fiveam</li>
    <li>lispPackages.flexi-streams</li>
    <li>lispPackages.form-fiddle</li>
    <li>lispPackages.fset</li>
    <li>lispPackages.generic-cl</li>
    <li>lispPackages.gettext</li>
    <li>lispPackages.global-vars</li>
    <li>lispPackages.html-encode</li>
    <li>lispPackages.http-body</li>
    <li>lispPackages.hu_dot_dwim_dot_asdf</li>
    <li>lispPackages.hu_dot_dwim_dot_defclass-star</li>
    <li>lispPackages.hu_dot_dwim_dot_stefil</li>
    <li>lispPackages.hunchentoot</li>
    <li>lispPackages.idna</li>
    <li>lispPackages.ieee-floats</li>
    <li>lispPackages.inferior-shell</li>
    <li>lispPackages.introspect-environment</li>
    <li>lispPackages.iolib_dot_asdf</li>
    <li>lispPackages.iolib_dot_base</li>
    <li>lispPackages.iolib_dot_common-lisp</li>
    <li>lispPackages.iolib_dot_conf</li>
    <li>lispPackages.iolib_dot_grovel</li>
    <li>lispPackages.ironclad</li>
    <li>lispPackages.iterate</li>
    <li>lispPackages.jonathan</li>
    <li>lispPackages.jpl-queues</li>
    <li>lispPackages.jpl-util</li>
    <li>lispPackages.kmrcl</li>
    <li>lispPackages.lack</li>
    <li>lispPackages.lack-component</li>
    <li>lispPackages.lack-middleware-backtrace</li>
    <li>lispPackages.lack-util</li>
    <li>lispPackages.let-plus</li>
    <li>lispPackages.lev</li>
    <li>lispPackages.lfarm-client</li>
    <li>lispPackages.lfarm-common</li>
    <li>lispPackages.lfarm-server</li>
    <li>lispPackages.lfarm-ssl</li>
    <li>lispPackages.lift</li>
    <li>lispPackages.lisp-namespace</li>
    <li>lispPackages.lisp-unit2</li>
    <li>lispPackages.local-time</li>
    <li>lispPackages.log4cl</li>
    <li>lispPackages.lparallel</li>
    <li>lispPackages.lquery</li>
    <li>lispPackages.map-set</li>
    <li>lispPackages.marshal</li>
    <li>lispPackages.md5</li>
    <li>lispPackages.metabang-bind</li>
    <li>lispPackages.metatilities-base</li>
    <li>lispPackages.mgl-pax</li>
    <li>lispPackages.misc-extensions</li>
    <li>lispPackages.mk-string-metrics</li>
    <li>lispPackages.moptilities</li>
    <li>lispPackages.more-conditions</li>
    <li>lispPackages.mt19937</li>
    <li>lispPackages.myway</li>
    <li>lispPackages.named-readtables</li>
    <li>lispPackages.net-telent-date</li>
    <li>lispPackages.net_dot_didierverna_dot_asdf-flv</li>
    <li>lispPackages.nibbles</li>
    <li>lispPackages.optima</li>
    <li>lispPackages.osicat</li>
    <li>lispPackages.parenscript</li>
    <li>lispPackages.parse-declarations-1_dot_0</li>
    <li>lispPackages.parse-number</li>
    <li>lispPackages.parser-combinators</li>
    <li>lispPackages.parser_dot_common-rules</li>
    <li>lispPackages.pcall</li>
    <li>lispPackages.pcall-queue</li>
    <li>lispPackages.plump</li>
    <li>lispPackages.postmodern</li>
    <li>lispPackages.proc-parse</li>
    <li>lispPackages.prove</li>
    <li>lispPackages.prove-asdf</li>
    <li>lispPackages.ptester</li>
    <li>lispPackages.puri</li>
    <li>lispPackages.pythonic-string-reader</li>
    <li>lispPackages.quicklisp</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>lispPackages.quri</li>
    <li>lispPackages.rfc2388</li>
    <li>lispPackages.rove</li>
    <li>lispPackages.rt</li>
    <li>lispPackages.s-sql</li>
    <li>lispPackages.s-sysdeps</li>
    <li>lispPackages.s-xml</li>
    <li>lispPackages.salza2</li>
    <li>lispPackages.serapeum</li>
    <li>lispPackages.simple-date</li>
    <li>lispPackages.simple-date-time</li>
    <li>lispPackages.simple-tasks</li>
    <li>lispPackages.smart-buffer</li>
    <li>lispPackages.split-sequence</li>
    <li>lispPackages.sqlite</li>
    <li>lispPackages.static-dispatch</li>
    <li>lispPackages.static-vectors</li>
    <li>lispPackages.stefil</li>
    <li>lispPackages.str</li>
    <li>lispPackages.string-case</li>
    <li>lispPackages.stumpwm</li>
    <li>lispPackages.swank</li>
    <li>lispPackages.swap-bytes</li>
    <li>lispPackages.symbol-munger</li>
    <li>lispPackages.trivia</li>
    <li>lispPackages.trivia_dot_balland2006</li>
    <li>lispPackages.trivia_dot_level0</li>
    <li>lispPackages.trivia_dot_level1</li>
    <li>lispPackages.trivia_dot_level2</li>
    <li>lispPackages.trivia_dot_quasiquote</li>
    <li>lispPackages.trivia_dot_trivial</li>
    <li>lispPackages.trivial-arguments</li>
    <li>lispPackages.trivial-backtrace</li>
    <li>lispPackages.trivial-clipboard</li>
    <li>lispPackages.trivial-cltl2</li>
    <li>lispPackages.trivial-features</li>
    <li>lispPackages.trivial-file-size</li>
    <li>lispPackages.trivial-garbage</li>
    <li>lispPackages.trivial-gray-streams</li>
    <li>lispPackages.trivial-indent</li>
    <li>lispPackages.trivial-macroexpand-all</li>
    <li>lispPackages.trivial-main-thread</li>
    <li>lispPackages.trivial-mimes</li>
    <li>lispPackages.trivial-package-local-nicknames</li>
    <li>lispPackages.trivial-types</li>
    <li>lispPackages.trivial-utf-8</li>
    <li>lispPackages.trivial-with-current-source-form</li>
    <li>lispPackages.type-i</li>
    <li>lispPackages.uax-15</li>
    <li>lispPackages.uffi</li>
    <li>lispPackages.uiop</li>
    <li>lispPackages.unit-test</li>
    <li>lispPackages.unix-options</li>
    <li>lispPackages.unix-opts</li>
    <li>lispPackages.usocket</li>
    <li>lispPackages.usocket-server</li>
    <li>lispPackages.utilities_dot_print-items</li>
    <li>lispPackages.utilities_dot_print-tree</li>
    <li>lispPackages.uuid</li>
    <li>lispPackages.vom</li>
    <li>lispPackages.woo</li>
    <li>lispPackages.wookie</li>
    <li>lispPackages.xembed</li>
    <li>lispPackages.xkeyboard</li>
    <li>lispPackages.xml_dot_location</li>
    <li>lispPackages.xmls</li>
    <li>lispPackages.xpath</li>
    <li>lispPackages.xsubseq</li>
    <li>lispPackages.yacc</li>
    <li>lispPackages.yason</li>
    <li>lispPackages.zpb-ttf</li>
  </ul>
</details>

**Comment by 7c6f434c** [comment]
cl-fuse / cl-fuse-meta-fs / query-fs makes perfect sense (no upstream support for macOS — as an upstream author I can confirm I will surely gratefully accept macOS patches, but as I do not use macOS ever, I won't ever write them)

The rest also seems FFI-needing. Looks like Hydra only builds `lispPackages` on Linux, so cannot easily compare with `master`, but seems natural that these could break.

**Comment by babariviere** [comment]
What's left to fix:

- cl-fuse: gcc is not available + libfuse.dylib not found
- cl-mysql: libmysqlclient.dylib not found (it's in a subfolder, but I can't make it work)
- cl-webkit: webkit does not compile
- cl-cffi-gtk: strange error 

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'C
*** First throw call stack:
(
)
libc++abi: terminating with uncaught exception of type NSException
fatal error encountered in SBCL pid 50224 pthread 0x13dbfe00
```

**Comment by 7c6f434c** [comment]
`cl-fuse`: `gcc` could be passed via overrides, I guess; but there is a bit more of `.so` hardcoding in the CFFI bindings (in `gcc` invocation too, actually)

`cl-mysql`: symlinking might be enough to resolve this… not sure whether `libmysqlclient` is in the different place or CFFI library specification needs fixing.

`webkit`: well, that's indeed not a Lisp topic.

`cl-cffi-gtk-glib`: hmmm. Maybe some system libraries need to be passed? But that's just me pattern matchings things I do not actually understand.

**Comment by babariviere** [comment]
There is already a PR for webkit: https://github.com/NixOS/nixpkgs/pull/123298

I will test it when it will be merged.

**Pull request merged**
