### PR TITLE
Don't run tests when cross-compiling

### PR DESCRIPTION
**Pull request by bgamari**
###### Motivation for this change
A step towards basic cross compilation (see #30882 for the next step).

This only handles a small fraction of cases which will ultimately need to be handled. That being said, it's a large enough fraction to compile everything up to `systemd`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Are there any packages whose check phase works during cross compilation?

**Comment by bgamari** [comment]
Orivej Desh <notifications@github.com> writes:

> Are there any packages whose check phase works during cross compilation?
>
While I can't say "no" with certainty, I would expect they would be the
exception, not the rule.

Another option here would be to unconditionally disable tests when
cross-compiling. However, this seems unappealingly ad-hoc and one of
those things that you will some day come to regret.

**Comment by bjornfor** [comment]
What if the mkDerivation function grew a doCheck parameter which defaulted to true for host builds and false for target builds? It could be overridden per package, but would have correct default value for the common case. I think the problem now is that doCheck is just passed right to the shell. (Or perhaps the same mechanism can be implemented at shell level too.)

**Comment by Ericson2314** [comment]
@bjornfor the problem is the default is always off. This would be easy to fix if the default was always on, in which we'd make it always on just for cross.

**Review by Ericson2314 — APPROVED** [review]
Per the above, I think this is the best we can do for now. It's easy to grep for this sort of thing later if we get better solution.

**Pull request merged**
