### PR TITLE
jetbrains: 2023.1.2 -> 2023.2

### PR DESCRIPTION
**Pull request by dritter**
###### Description of changes

jetbrains.clion: 2023.1.5 -> 2023.2
jetbrains.datagrip: 2023.1.2 -> 2023.2
jetbrains.dataspell: 2023.1.4 -> 2023.2
jetbrains.gateway: 2023.1.3 -> 2023.2
jetbrains.goland: 2023.1.4 -> 2023.2
jetbrains.idea-community: 2023.1.4 -> 2023.2
jetbrains.idea-ultimate: 2023.1.4 -> 2023.2
jetbrains.pycharm-community: 2023.1.4 -> 2023.2
jetbrains.pycharm-professional: 2023.1.4 -> 2023.2
jetbrains.ruby-mine: 2023.1.4 -> 2023.2
jetbrains.webstorm: 2023.1.4 -> 2023.2

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabianhjr — APPROVED** [review]
Built and used Idea Community 2023.2

**Comment by dritter** [comment]
To-Do: seems Like in the meantime a new Version of pycharm* was released. Will Update the pr tomorrow.

**Comment by dritter** [comment]
Result of `nixpkgs-review pr 245566` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Review by niknetniko — APPROVED** [review]
Works for me (tested Intellij Ultimate).

For those interested, I have also created a follow-up PR to bump the JCEF fork in the JetBrains JDK, to ensure the markdown previews etc. keep working: https://github.com/NixOS/nixpkgs/pull/245717.

**Comment by dritter** [comment]
Result of `nixpkgs-review pr 245566` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.dataspell</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Review by x418 — APPROVED** [review]
Been using the resulting `idea-ultimate` on x86_64-linux (while testing https://github.com/NixOS/nixpkgs/pull/245717) and it works without issues.

**Review by Janik-Haag — APPROVED** [review]
LGTM

**Pull request merged**
