### PR TITLE
emacs24macport: remove

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This removes emacs24macport to match the main emacs (which removes emacs24 ~4 months ago.)

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
I don't see a issue/pr about the removal of v24, was there a discussion about it?

**Comment by matthewbauer** [comment]
Here's the commit; https://github.com/NixOS/nixpkgs/commit/01e44ac1f9af1d42ee9b5000426b780f2a03c948

**Comment by LnL7** [comment]
I expected that there would be some people that still want the old version. Note that `emacs24` still exists in the release, I expect there's a group of people that will only notice that change when they upgrade to 17.03

**Comment by joachifm** [comment]
Yay or nay on this?

**Review by LnL7 — APPROVED** [review]

**Pull request merged**
