### PR TITLE
lightly-boehs: init at 0.4.1

### PR DESCRIPTION
**Pull request by ghost**
The fork of Lightly by Boehs actively accepts pull requests while the upstream does not and seems unmaintained.

### CODE REVIEW

**Comment by onny** [comment]
Thank you for your contribution, could you please squash the commits into one with the commit message `lightly-boehs: init at 0.4.1`. Thank you :)

**Comment by HikariNee** [comment]
Done!

**Comment by HikariNee** [comment]
@onny It's ready to be merged now.

**Comment by onny** [comment]
Unfortunately there's one thing missing. The changes to the maintainers list need to be in a separate commit with the title `maintainers: add hikari`. After that its good to go :) Thank you!

**Comment by onny** [comment]
One last thing, please change the commit message to `lightly-boehs: init at 0.4.1` ;)

**Comment by onny** [comment]
Result of `nixpkgs-review pr 230512` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>lightly-boehs</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you for your contribution and welcome to the maintainers list :)

**Comment by HikariNee** [comment]
Thank you! Have a good day.

**Pull request merged**
