### PR TITLE
solc: 0.5.12 -> 0.5.15

### PR DESCRIPTION
**Pull request by asymmetric**
###### Motivation for this change

* Update version.
* Remove patchset for building shared library. See https://github.com/NixOS/nixpkgs/pull/39852#issuecomment-568474864 for a discussion.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @akru @lionello

### CODE REVIEW

**Comment by livnev** [comment]
Tested on nixOS, it builds and works. 👍

**Comment by asymmetric** [comment]
@akru should we remove the `dev` output from 

```nix
  outputs = [ "out" "dev" ];
```
?

**Comment by asymmetric** [comment]
Is there still something to be done or can this be merged?

It introduces some changes that will be useful for all future versions (namely, removing a patch and building shared libraries)

**Comment by sifmelcara** [comment]
LGTM :+1:, built on NixOS

**Pull request merged**
