### PR TITLE
wget2: 1.99.2 -> 2.0.0

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by smancill** [comment]
There is a PR doing the same: #139976

**Comment by smancill** [comment]
I cannot use `nixpkgs-review` to build this, it says "Nothing to be built" (same with the other PR):

```
 nixpkgs-review pr 140090
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/140090/head:refs/nixpkgs-review/1
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), 16.01 KiB | 298.00 KiB/s, done.
From https://github.com/NixOS/nixpkgs
 + 7e4da1d1940...6ff40871c0a refs/pull/140090/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /Users/smancill/.cache/nixpkgs-review/pr-140090/nixpkgs 9a23237031b385945132c8dac7d7ad97ece67408
Preparing worktree (detached HEAD 9a23237031b)
Updating files: 100% (28128/28128), done.
HEAD is now at 9a23237031b Merge pull request #139989 from zhaofengli/bochs-nogui
$ git merge --no-commit --no-ff 6ff40871c0a5873ef510ff10a1edbef327bc6ae6
Automatic merge went well; stopped before committing as requested
Nothing to be built.

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/140090
```

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 140090` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wget2</li>
  </ul>
</details>

**Comment by Ma27** [comment]
Closing, duplicate.

**Comment by SuperSandro2000** [comment]
> There is another PR doing the same: #139976

That also contains the update but misses all the other important and not so important changes.

**Pull request merged**
