### PR TITLE
openrgb-plugin-hardwaresync,openrgb-plugin-effects: init at 0.8

### PR DESCRIPTION
**Pull request by fgaz**
###### Description of changes

Unfortunately openrgb imports a plugin by copying it into its config directory, so this only works until a garbage collection removes its dependencies. I don't see how to fix that without patching upstream. Replacing the imported plugin with a symlink to a static location (such as /etc) of the package works though.
edit: fixed, see comments

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSamus** [comment]
On the latest version, [you can add a plugin path during build time](https://gitlab.com/CalcProgrammer1/OpenRGB/-/merge_requests/1534) with `OPENRGB_EXTRA_PLUGIN_DIRECTORY`.
It's only a single path, but I guess it can be solved with `symlinkJoin`.

**Comment by fgaz** [comment]
Great, I'll add a `withPlugins` attribute or a `plugins` parameter. Too bad it requires rebuilding. I guess I could add a top-level `openrgb-with-all-plugins`

**Comment by fgaz** [comment]
I added a withPlugins attribute

**Comment by fgaz** [comment]
I just added the effect plugin

**Pull request merged**
