### PR TITLE
avalonia-ilspy: fix copyDesktopItems use missing from initial review

### PR DESCRIPTION
**Pull request by AngryAnt**
###### Description of changes

When initially contributed, this package was in review moved to copyDesktopItems. During that I missed that the added use of this was incomplete. This change adds the missing line which sees the desktop item actually copied into place.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by winterqt — CHANGES_REQUESTED** [review]
You should be able to just collapse the definition of the desktop item into the definition of the list, instead of needing an intermediate attribute.

**Comment by AngryAnt** [comment]
> You should be able to just collapse the definition of the desktop item into the definition of the list, instead of needing an intermediate attribute.

Thank you for the suggestion - it worked excellently :) Having moved to implement it immediately and push the update, I am unsure how to address the "Changed requested" status other than the review request I followed up with immediately after.

I am guessing the persistence of this status only serves to further push the PR back in the queue?

**Review by winterqt — APPROVED** [review]

**Comment by winterqt** [comment]
Sorry, not sure how I missed this.

**Comment by AngryAnt** [comment]
No worries - I'm just trying to learn the ropes here :)

**Pull request merged**
