### PR TITLE
open-vm-tools: Add kernel modules for shared folders support

### PR DESCRIPTION
**Pull request by joamaki**
This adds a separate modules package for open-vm-tools in order to support shared folders.

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
@copumpkin

**Comment by copumpkin** [comment]
Thanks for doing this so quickly! My main puzzlement is that it seems odd to have two packages building from the same source tree, one disabling what the other enables. I know you're already sharing the `.src` and `.buildInputs` attributes, but can the two package expressions be unified to the point of just passing in a boolean for whether you want the kernel modules or not? That seems a bit cleaner. Or alternately, is there any downside to always building the kernel modules? I suppose they only really apply to linux guests, and conceivably the rest of the expression could work on other OSes?

**Comment by copumpkin** [comment]
Also, is there a way to just retrieve the patches from wherever they came from rather than incorporating them into our tree?

**Comment by joamaki** [comment]
Valid points. My reasoning behind separating them into two packages was that vmtoolsd and the utilities were not tied to any specific kernel version and we'd be recompiling them for each kernel. However I guess it's not that much extra work and it would be cleaner.

Agreed, I wish there'd be a good source for the patches we could use instead incorporating them. Couple of other expressions are also pulling patches from archlinux so perhaps we should follow the same approach here.

I'll try and clean it up a bit.

**Comment by copumpkin** [comment]
@joamaki it could just end up looking like "if kernel modules boolean then we force the kernel headers expression, otherwise there's no dependency"

**Comment by joamaki** [comment]
Just checked and fetchpatch actually does the normalisation, so it should be ok.

**Comment by Fuuzetsu** [comment]
Oh, maybe that's what I was thinking of in the first place. Nevermind…

**Comment by joamaki** [comment]
Ping. Would this be mergeable?

**Comment by Fuuzetsu** [comment]
See my comment on your commit  I left some time ago about pulling in raw patches from GitHub. Also you add some spurious trailing whitespace which is ugly style wise.

Other than that I see nothing wrong with it provided that it works. @copumpkin can you do the merger, you seem to be in-the-know about this stuff while I'm just leaving general comments.

**Comment by copumpkin** [comment]
Sure, I'll probably try it to make sure it works in the next couple of days. Been quite busy, sorry!

**Comment by jekor** [comment]
I just tested this. The module is available but does not seem to be loaded automatically.

```
[root@dev:~]# lsmod | grep vmhgfs

[root@dev:~]# modprobe vmhgfs
modprobe: FATAL: Module vmhgfs not found.

[root@dev:~]# insmod /nix/store/x8ni1jz6izzpc5mxfr49q8ysrbh4cz4d-open-vm-tools-9.10.0-2476743/lib/modules/3.18.14/fs/vmhgfs/vmhgfs.ko

[root@dev:~]# lsmod | grep vmhgfs
vmhgfs                 44953  0

[root@dev:~]#
```

**Comment by rasendubi** [comment]
(triage) is this waiting for @copumpkin input?

**Comment by copumpkin** [comment]
Getting back to looking at this now. Will post with results in a bit, and possibly just merge after adjusting for current nixpkgs. Sorry this has taken me so long!

Any idea about @jekor's point about it not autoloading though? Does that just need to be added to config?

**Comment by joamaki** [comment]
Heh, don't actually remember at all why the patches were necessary and as I don't actually have a VMware license anymore it'd be great if someone could take this over. @jekor?

**Comment by jekor** [comment]
Recent open-vm-tools no longer uses the vmhgfs kernel module and uses fuse instead. That's the only kernel module I was interested in, so I've created https://github.com/NixOS/nixpkgs/pull/22364 which is working for me.

**Comment by 7c6f434c** [comment]
So, does anyone need this patch anymore if the shared folder work via FUSE? @Fuuzetsu @jeko @joamaki

**Comment by jekor** [comment]
The latest changes in master work for me without this patch.

**Comment by joamaki** [comment]
Closing this one then.

**Pull request closed without merging**
