### PR TITLE
Kernkonzept ham

### PR DESCRIPTION
**Pull request by herrwiese**
###### Motivation for this change

Add ham, a utility for managing big source code projects consisting of multiple, loosely-coupled Git repositories, like the L4Re operating system.

dependencies:
perlPackages.GitVersionCompare: init at 1.004
perlPackages.TestRequiresGit: init at 1.008
perlPackages.SystemCommand: init at 1.119
perlPackages.GitRepository: init at 1.323
perlPackages.XMLMini: init at 1.38
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
@herrwiese How can I test using this tool?

**Comment by volth** [comment]
@GrahamcOfBorg build ham

**Comment by herrwiese** [comment]
Sorry, I accidentally closed the old one.  You can for example test it by checking out mentioned L4Re operating, see [Getting the Fiasco and L4Re sources Using `ham`](https://github.com/kernkonzept/manifest/wiki/BUILDING#getting-the-fiasco-and-l4re-sources-using-ham).

**Comment by worldofpeace** [comment]
Tested it and it worked fine :heavy_check_mark: 

Thank you for contributing @herrwiese and for your patience :sparkles:

**Comment by herrwiese** [comment]
Many thanks!  Is there any chance to get this into release-19.03? If so, what is the procedure (seperate PR with commits rebased on top of branch?)?

**Comment by worldofpeace** [comment]
Yes we always accept new packages to stable releases @herrwiese.

The procedure is outlined in https://nixos.org/nixpkgs/manual/#submitting-changes-stable-release-branches
So just base your pr off `release-19.03` and cherry-pick the commits from master.

**Pull request merged**
