### PR TITLE
Slim down iso_gnome output size

### PR DESCRIPTION
**Pull request by jtojnar**
The iso is now too big for Hydra: https://github.com/NixOS/nixpkgs/issues/141521

```ShellSession
$ nix-build nixos/release.nix -A iso_gnome
[...]
$ du result/
2105304 result/
$ du -h result/
2.1G  result/
```

### CODE REVIEW

**Comment by vcunat** [comment]
The exact accounting for Hydra's limit should be on NAR size, e.g. `nix path-info -s ./result`

**Comment by jtojnar** [comment]
This time I seem to have only scraped few megabytes. Even adding `dev` output to `python3.pkgs.brotliffi` only seems to have saved less than 200 bytes and that is almost a mass rebuild.

**Comment by jtojnar** [comment]
The final size is

```ShellSession
$ nix path-info -Sh /nix/store/dlrbnhgbiarna63ac55g0ffr5afnps1x-squashfs.img
/nix/store/dlrbnhgbiarna63ac55g0ffr5afnps1x-squashfs.img	   2.0G
$ nix path-info -S /nix/store/dlrbnhgbiarna63ac55g0ffr5afnps1x-squashfs.img
/nix/store/dlrbnhgbiarna63ac55g0ffr5afnps1x-squashfs.img	 2142963608
```

I guess we need to increase the limit.

**Comment by jtojnar** [comment]
That is weird, the changes actually seem to increase the image size. On d53d2147eff16f01b2345d4afed2de362979f551, I get

```ShellSession
$ nix path-info -Sh /nix/store/ln8wwyy7l0yqcrgandgcc2x55dv2nad7-squashfs.img
/nix/store/ln8wwyy7l0yqcrgandgcc2x55dv2nad7-squashfs.img	   2.0G

$ nix path-info -S /nix/store/ln8wwyy7l0yqcrgandgcc2x55dv2nad7-squashfs.img
/nix/store/ln8wwyy7l0yqcrgandgcc2x55dv2nad7-squashfs.img	 2140045744
```

**Comment by vcunat** [comment]
Some minor oscillations happen, probably.  Now it fit on master: https://hydra.nixos.org/build/163549101

**Pull request merged**
