### PR TITLE
awscli2: relax flit_core version pin

### LINKED ISSUE #367876: Build failure: awscli2
## Steps To Reproduce

I'm not a nix expert just an user that use it in github action CI/CD using https://github.com/workflow/nix-shell-action

When trying to run this action with `awscli2` since today/yesterday I got a build failure

https://github.com/kha20240826/nix-gaction-awscli/actions/runs/12480564894/job/34831595489

Apparently it is due to some `flit-core` package upgrade not matching the `awscli` requirement

`flit_core (required: ('>=3.7.1', '<3.9.1')) (version installed: 3.10.0)`

## Build log

All logs are available here
https://github.com/kha20240826/nix-gaction-awscli/actions/runs/12480564894/job/34831595489

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by devusb**
Closes https://github.com/NixOS/nixpkgs/issues/367876

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by devusb** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 367979`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>liquidsoap</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>awscli2</li>
    <li>awscli2.dist</li>
  </ul>
</details>

**Comment by benbridts** [comment]
I tried this on aarch64-darwin, and the build succeeds (and `aws version` works)

**Comment by xiaoxiangmoe** [comment]
I tried in latest nixpkgs

```nix
    (pkgs.awscli2.overrideAttrs (oldAttrs: {
      postPatch = ''
        substituteInPlace pyproject.toml \
          --replace-fail 'flit_core>=3.7.1,<3.9.1' 'flit_core>=3.7.1' \
          --replace-fail 'awscrt>=0.19.18,<=0.22.0' 'awscrt>=0.22.0' \
          --replace-fail 'cryptography>=40.0.0,<43.0.2' 'cryptography>=43.0.0' \
          --replace-fail 'distro>=1.5.0,<1.9.0' 'distro>=1.5.0' \
          --replace-fail 'docutils>=0.10,<0.20' 'docutils>=0.10' \
          --replace-fail 'prompt-toolkit>=3.0.24,<3.0.39' 'prompt-toolkit>=3.0.24'
        substituteInPlace requirements-base.txt \
          --replace-fail "wheel==0.43.0" "wheel>=0.43.0"
        # Upstream needs pip to build and install dependencies and validates this
        # with a configure script, but we don't as we provide all of the packages
        # through PYTHONPATH
        sed -i '/pip>=/d' requirements/bootstrap.txt
      '';
    }))
```

and 

```

warning: Git tree '/Users/zhaojinxiang/.config/.nixos-config' is dirty
error: builder for '/nix/store/74ql8cw5hyvahfhzqvcnhnji22hf23jg-awscli2-2.22.13.drv' failed with exit code 1;
       last 25 log lines:
       >         except socket.error as e:
       > >           raise AuthCodeFetcherError(error_msg=e)
       > E           botocore.exceptions.AuthCodeFetcherError: Unable to initialize the OAuth 2.0 authorization callback handler: [Errno 1] Operation not permitted 
       > E            You may use --use-device-code to fall back to the device code flow which does not require the callback handler.
       >
       > awscli/customizations/sso/utils.py:226: AuthCodeFetcherError
       > =============================== warnings summary ===============================
       > tests/unit/customizations/logs/test_startlivetail.py::LiveTailKeyBindingsTest::test_any_key_binding
       >   /nix/store/8zc3wcplydp8gsxms24scpzdca438dk5-python3-3.12.8/lib/python3.12/unittest/mock.py:769: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
       >     def __setattr__(self, name, value):
       >   Enable tracemalloc to get traceback where the object was allocated.
       >   See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
       >
       > tests/unit/customizations/logs/test_startlivetail.py::InteractiveUITest::test_exit
       >   /nix/store/4w9ixw5irrv9y27vqmw6402xqr5a2lq9-python3.12-prompt-toolkit-3.0.48/lib/python3.12/site-packages/prompt_toolkit/key_binding/key_bindings.py:278: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
       >     keys = tuple(_parse_key(k) for k in keys)
       >   Enable tracemalloc to get traceback where the object was allocated.
       >   See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > FAILED tests/unit/customizations/sso/test_utils.py::test_get_auth_code_and_state_timeout - botocore.exceptions.AuthCodeFetcherError: Unable to initialize the OAuth 2....
       > ERROR tests/unit/customizations/sso/test_utils.py::TestAuthCodeFetcher::test_expected_auth_code - botocore.exceptions.AuthCodeFetcherError: Unable to initialize the OAuth 2....
       > ERROR tests/unit/customizations/sso/test_utils.py::TestAuthCodeFetcher::test_error - botocore.exceptions.AuthCodeFetcherError: Unable to initialize the OAuth 2....
       > = 1 failed, 4155 passed, 1 skipped, 2 warnings, 2 errors in 122.37s (0:02:02) ==
       For full logs, run 'nix log /nix/store/74ql8cw5hyvahfhzqvcnhnji22hf23jg-awscli2-2.22.13.drv'.
error: 1 dependencies of derivation '/nix/store/7ghv4l9hd0dlx1yqidqaqcik74vlfgly-home-manager-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i3pm1cspgiv755ymsh9b8rf8by9dbyxy-home-manager-fonts.drv' failed to build
error: 1 dependencies of derivation '/nix/store/phifafciby24qgdv1jz0c245pdqgl49i-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/n2g9j4qxzlp6mhinvfbqi8jf9z0fg0sz-home-manager-generation.drv' failed to build
error: Recipe `home-manager-switch` failed on line 36 with exit code 1
```

**Comment by xiaoxiangmoe** [comment]
I tried in latest nixpkgs

```nix
    (pkgs.awscli2.overrideAttrs (oldAttrs: {
      postPatch = ''
        substituteInPlace pyproject.toml \
          --replace-fail 'flit_core>=3.7.1,<3.9.1' 'flit_core>=3.7.1' \
          --replace-fail 'awscrt>=0.19.18,<=0.22.0' 'awscrt>=0.22.0' \
          --replace-fail 'cryptography>=40.0.0,<43.0.2' 'cryptography>=43.0.0' \
          --replace-fail 'distro>=1.5.0,<1.9.0' 'distro>=1.5.0' \
          --replace-fail 'docutils>=0.10,<0.20' 'docutils>=0.10' \
          --replace-fail 'prompt-toolkit>=3.0.24,<3.0.39' 'prompt-toolkit>=3.0.24'
        substituteInPlace requirements-base.txt \
          --replace-fail "wheel==0.43.0" "wheel>=0.43.0"
        # Upstream needs pip to build and install dependencies and validates this
        # with a configure script, but we don't as we provide all of the packages
        # through PYTHONPATH
        sed -i '/pip>=/d' requirements/bootstrap.txt
      '';
    }))
```

and 

```
 
error: builder for '/nix/store/74ql8cw5hyvahfhzqvcnhnji22hf23jg-awscli2-2.22.13.drv' failed with exit code 1;
       last 25 log lines:
       >         except socket.error as e:
       > >           raise AuthCodeFetcherError(error_msg=e)
       > E           botocore.exceptions.AuthCodeFetcherError: Unable to initialize the OAuth 2.0 authorization callback handler: [Errno 1] Operation not permitted 
       > E            You may use --use-device-code to fall back to the device code flow which does not require the callback handler.
       >
       > awscli/customizations/sso/utils.py:226: AuthCodeFetcherError
       > =============================== warnings summary ===============================
       > tests/unit/customizations/logs/test_startlivetail.py::LiveTailKeyBindingsTest::test_any_key_binding
       >   /nix/store/8zc3wcplydp8gsxms24scpzdca438dk5-python3-3.12.8/lib/python3.12/unittest/mock.py:769: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
       >     def __setattr__(self, name, value):
       >   Enable tracemalloc to get traceback where the object was allocated.
       >   See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
       >
       > tests/unit/customizations/logs/test_startlivetail.py::InteractiveUITest::test_exit
       >   /nix/store/4w9ixw5irrv9y27vqmw6402xqr5a2lq9-python3.12-prompt-toolkit-3.0.48/lib/python3.12/site-packages/prompt_toolkit/key_binding/key_bindings.py:278: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
       >     keys = tuple(_parse_key(k) for k in keys)
       >   Enable tracemalloc to get traceback where the object was allocated.
       >   See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > FAILED tests/unit/customizations/sso/test_utils.py::test_get_auth_code_and_state_timeout - botocore.exceptions.AuthCodeFetcherError: Unable to initialize the OAuth 2....
       > ERROR tests/unit/customizations/sso/test_utils.py::TestAuthCodeFetcher::test_expected_auth_code - botocore.exceptions.AuthCodeFetcherError: Unable to initialize the OAuth 2....
       > ERROR tests/unit/customizations/sso/test_utils.py::TestAuthCodeFetcher::test_error - botocore.exceptions.AuthCodeFetcherError: Unable to initialize the OAuth 2....
       > = 1 failed, 4155 passed, 1 skipped, 2 warnings, 2 errors in 122.37s (0:02:02) ==
       For full logs, run 'nix log /nix/store/74ql8cw5hyvahfhzqvcnhnji22hf23jg-awscli2-2.22.13.drv'.
error: 1 dependencies of derivation '/nix/store/7ghv4l9hd0dlx1yqidqaqcik74vlfgly-home-manager-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i3pm1cspgiv755ymsh9b8rf8by9dbyxy-home-manager-fonts.drv' failed to build
error: 1 dependencies of derivation '/nix/store/phifafciby24qgdv1jz0c245pdqgl49i-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/n2g9j4qxzlp6mhinvfbqi8jf9z0fg0sz-home-manager-generation.drv' failed to build
error: Recipe `home-manager-switch` failed on line 36 with exit code 1
```

**Comment by devusb** [comment]
@xiaoxiangmoe my overlay looks like this, which seems to work
```
    (prev.awscli2.overrideAttrs (old: {
      postPatch =
        old.postPatch
        + ''
          substituteInPlace pyproject.toml \
            --replace-fail 'flit_core>=3.7.1,<3.9.1' 'flit_core>=3.7.1'
        '';
    }))
```
don't have an aarch54-darwin to compare, but per above comments this PR seems to build -- would recommend confirming awscli2 from an earlier nixpkgs commit or 24.11 still works for you.

**Review by fpletz — APPROVED** [review]

**Pull request merged**
