### PR TITLE
staging-next: 21.11 iteration 9 - 2022-04-07

### PR DESCRIPTION
**Pull request by vcunat**
Documentation: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-staging-next-branch

jobset: https://hydra.nixos.org/jobset/nixpkgs/staging-next-21.11
important job: https://hydra.nixos.org/job/nixpkgs/staging-next-21.11/unstable#tabs-constituents

Previous staging-next PR: #162184

### CODE REVIEW

**Comment by vcunat** [comment]
It looks quite good to me, though thousands of darwin builds are still queued: https://hydra.nixos.org/eval/1754231?compare=1753408#tabs-now-fail

In particular, know regressions of zlib update get fixed.

**Comment by vcunat** [comment]
@mweinelt: it looks like some python-related regressions are there, though probably nothing really blocking.

**Comment by mweinelt** [comment]
I've backported a few fixes for the things that looked important. Most of the things are either a) flaky b) darwin sandbox related (like wanting to access `/tmp`), I don't have enough in me to work through those, sorry.

**Comment by vcunat** [comment]
- [ ] python 3.10 regressed on x86_64-darwin: https://hydra.nixos.org/build/172746473  Though hopefully on 21.11 I don't expect it to be important yet.

**Comment by mweinelt** [comment]
Yeah, its getting signal 9, not sure why. @NixOS/darwin-maintainers

**Comment by veprbl** [comment]
> * [ ]  python 3.10 regressed on x86_64-darwin: https://hydra.nixos.org/build/172746473  Though hopefully on 21.11 I don't expect it to be important yet.

Deja vu in #154120

**Comment by vcunat** [comment]
I merged.  The fixes already seem to far outweigh the regressions, especially on x86_64-darwin.

**Pull request merged**
