### PR TITLE
Remove .envrc

### PR DESCRIPTION
**Pull request by toastal**
## Description of changes

https://github.com/NixOS/nixpkgs/commit/f0160baa7af871ec9fed4e9ec6758104e6c8e0a0#commitcomment-143982098

I use this file to work with different environment variables while working with derivations. With this file being tracked, now I am more prone to accidentally commit as well as needing to stash my changes just to get the latest code from `git pull --rebase upstream master`. I strongly feel this file is for personal use & just like you shouldn’t commit your personal editor’s config to the repository, leave this file alone so users can customize it—the ones that want to use direnv can `echo 'use nix' >> .envrc && direnv allow` which does not get in anyone’s way. With the red consent banner pop-up & forced default settings, tracking this file provides a degraded user experience for this project, not an improved one.

https://github.com/NixOS/nixpkgs/pull/322512
https://github.com/NixOS/nixpkgs/pull/322650

These threads are full of objections & similar use cases along with hacky solutions about `.env.*` ignored files. Just because one user says they are fine losing their workflow, does not assume everyone else is. I don’t follow all Nixpkgs threads to join the original discussion since there are thousands, so I don’t notice til things are merged & discussion is over.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mweinelt — DISMISSED** [review]
Same as https://github.com/NixOS/nixfmt/pull/178.

**Comment by Sigmanificient** [comment]
Should the `.direnv` stays in the `.gitignore` for people who use `direnv`?

**Comment by piegamesde** [comment]
FWIW, Lix has implemented a similar workaround: https://git.lix.systems/lix-project/lix/src/branch/main/.envrc

However, I'd argue that this should primarily be fixed upstream, i.e. in direnv itself.

**Comment by infinisil** [comment]
Thanks for the explanation of your use case, indeed I don't think any workaround is fit for this, so again I suggest you add support for a `.envrc.local`, I'd be okay with that.

> And to what benefit? So users don’t have to run nix-shell or have to set up their own, untracked .envrc that they do just once. This doesn’t seem like a value add.

The value comes from users _automatically_ being informed about the shell existing. Without that, most users wouldn't even be aware of it. It also comes with editor integration for a very smooth auto-formatting experience.

And note that even just in public GitHub repos, [over 14k of them](https://github.com/search?q=path%3A%2F%5C.envrc%24%2F&type=code) commit their `.envrc`, so it's not uncommon ;)

**Comment by emilazy** [comment]
For what it’s worth, I think a fairly serious concern that isn’t related to any of these more subjective issues of preference is that if you run `direnv allow` in the Nixpkgs tree and then check out someone’s PR branch in the same directory, they instantly gain arbitrary code execution as your user, bypassing all protections like the build sandbox. The @NixOS/security ping for changes to the relevant files only helps if it’s noticed before someone checks the branch out.

That’s an issue with direnv in general – and I do still use and like it – but Nixpkgs is an especially central target given that it is so popular and that maintainers are constantly dealing with a large number of essentially untrusted pull requests. (You could fairly argue that anyone reviewing Nixpkgs PRs should take greater precautions in general as a result of this, but in practice I suspect almost none do.)

**Comment by emilazy** [comment]
One potential solution would be to provide the relevant shell environment as an export from Nixpkgs and ensure that the `.envrc` does not import any Nix code from inside the tree (i.e., no `shell.nix`). That would require keeping `nixfmt-rfc-style` versions in sync across the release branches, but any attempt to hijack the facility through a PR would trigger another direnv permissions prompt.

**Comment by toonn** [comment]
I use worktrees a lot to work on several things at once, review PRs and such. Often these worktrees are short-lived. Since direnv records consent per path this basically means I get pestered with the warning no matter how many times I (dis)allow.

I really hope an alternative way of informing people how to enable useful tool integrations is found. Preferably one that doesn't force one particular solution among many alternatives, instructions that achieve equivalent behavior using Lorri for example.

**Comment by piegamesde** [comment]
> That’s an issue with direnv in general

I'd argue that this is only an issue with direnv-nix, because direnv generally checks the file for modifications and asks you for re-approval. Only when sourcing stuff from elsewhere (as is done in direnv-nix by default) causes the attack vector you describe.

Since I already advocated for upstream fixes to problems earlier, the mitigation would be to allow to track external files as part of the direnv source for modifications. As prior art, we already have the `watch_file` builtin which at least reloads the shell on modification, we'd need something similar but with the approval baked in. This would still require upholding the invariant that no source code outside of these files gets sources, but which sounds like an acceptable tradeoff to me.

**Comment by infinisil** [comment]
I just noticed somebody [accidentally pushing](https://github.com/NixOS/nixpkgs/commit/d8dd3d5e560bf02c5a3812d9a9530ed338ba1675#diff-d33e979799a45c7c51752e9c8d96a3e452015d1a40b1e4b6ec6a98e92c4d8430) their `.envrc` changes in a PR (got notified as a code owner), which can be seen as an argument in favor of this PR.

**Comment by emilazy** [comment]
> I'd argue that this is only an issue with direnv-nix, because direnv generally checks the file for modifications and asks you for re-approval. Only when sourcing stuff from elsewhere (as is done in direnv-nix by default) causes the attack vector you describe.
> 
> Since I already advocated for upstream fixes to problems earlier, the mitigation would be to allow to track external files as part of the direnv source for modifications. As prior art, we already have the `watch_file` builtin which at least reloads the shell on modification, we'd need something similar but with the approval baked in. This would still require upholding the invariant that no source code outside of these files gets sources, but which sounds like an acceptable tradeoff to me.

Yes. However I don’t think it would be feasible to prompt people for reapproval every time any file involved in the building of a Haskell project like `nixfmt-rfc-style` changes, regardless.

I lean more and more towards going with this PR and only shipping an `.envrc.recommended` after learning about situations like @toonn’s. However, even in that case, my security concerns in https://github.com/NixOS/nixpkgs/pull/325793#issuecomment-2227492940 apply to anyone who takes that recommendation. Therefore, regardless of the outcome of this PR, I strongly recommend doing the following:

1. Ship a `nixpkgs-dev-shell` package in Nixpkgs with the shell environment currently in `shell.nix`; backport it to 24.05 and keep it (and `nixfmt-rfc-style`) in sync across release branches.

2. Remove `shell.nix` so that people aren’t tempted to run it from a potentially‐malicious branch. Don’t export it in `flake.nix`’s `devShells` for the same reason. Document `nix-shell '<nixpkgs>' -A nixpkgs-dev-shell` instead. (Perhaps it could even install a convenience binary to start the shell, so that people can put it in their `environment.systemPackages` if they want.)

3. Make `.envrc{,.recommended}` do `use flake nixpkgs#nixpkgs-dev-shell` / `use nix '<nixpkgs>' -A nixpkgs-dev-shell`. This will use the system Nixpkgs, which is implicitly trusted, and avoid any risk from having a malicious branch checked out. As a bonus, it’ll still be possible to use the development environment even when working on `staging` branches that rebuild the world and would make direnv terribly annoying at present.

**Comment by piegamesde** [comment]
> However I don’t think it would be feasible to prompt people for reapproval every time any file involved in the building of a Haskell project like nixfmt-rfc-style changes, regardless.

I see. To prevent that, we'd have to not only pin the package but the entire Nixpkgs instead, so that only pin bumps re-prompt. Not sure if that's the current plan though

**Review by infinisil — APPROVED** [review]
Alright let's just go ahead with this PR for now. There's some good arguments for this, arguments which only make sense at the scale of Nixpkgs, and it's not hard to just do `echo 'use nix' > .envrc` for those that want it, even though it would be nice not needing to do that.

**Comment by toonn** [comment]
@wolfgangwalther, you should be able to just put it in the parent directory though. While my use case has no acceptable workaround.

From the direnv man page:
> Before  each prompt it checks for the existence of an .envrc file in the
       current and parent directories. If the file exists, it is loaded into  a
       bash  sub-shell  and  all exported variables are then captured by direnv
       and then made available to your current shell, while unset variables are
       removed.

**Comment by toonn** [comment]
Hmm, I see. Then some form of Git setup hook is the only thing that comes to mind. It's a shame (though understandable) that direnv changes the PWD before executing the envrc, that would make your desired behavior possible. It might even be an acceptable upstream feature request to introduce an `INVOCATION_DIR` that contains the path that triggered a particular direnv execution.

But, to be clear, I still disagree your workflow is more impacted than that of others who either don't want to use direnv at all or want their custom envrc file.
You still need to run `direnv allow` for every new worktree (unless you reuse a fixed set of worktree directories but I think it's fair to say we're straying further and further off the common path). Changing that to `cp/ln -s your/canonical/.envrc . && direnv allow` does seem like a reasonable ask.

**Pull request merged**
