### PR TITLE
solc: 0.5.9 -> 0.5.10

### PR DESCRIPTION
**Pull request by sifmelcara**
Update the package.

##### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by sifmelcara** [comment]
Could someone with @GrahamcOfBorg MacOS access help test building on MacOS? Thanks!

**Comment by srhb** [comment]
@GrahamcOfBorg build solc

**Comment by sifmelcara** [comment]
IMO this is ready to be merged

**Comment by xrelkd** [comment]
LGTM! tested locally on NixOS.
Hi, @marsam I think that this PR gets stuck. Could you merge this PR? Thank you!

**Comment by marsam** [comment]
Thanks!

**Pull request merged**
