### PR TITLE
qpdfview: hardcode qmake files

### PR DESCRIPTION
**Pull request by rardiol**
###### Motivation for this change

Fixes compile failure https://nix-cache.s3.amazonaws.com/log/8rhpv2id6l2c1as2n3q15kfzm27l3m0v-qpdfview-0.4.18.drv .
Unfortunately I can't figure out why the commented solution bizarrely doesn't work, which would be better than hard coding the *.pro files. Any guesses?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @7c6f434c

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Maybe `qmakeFlags` is an array at the `preConfigure` time? I haven't looked at the details, but this is my first association.

**Comment by rardiol** [comment]
Yeah, I needed to append as an array and not a blob of text. Thanks.

**Review by Lassulus — APPROVED** [review]
tested with nix-review, opened a pdf file

**Comment by c0bw3b** [comment]
Actually you just needed to escape it to safely pass it to qmake via env shell
Done in 7bb372b664ee48d552c0d3ff798e6aa00d2498bb

**Comment by rardiol** [comment]
just tried commit 7bb372b6, didn't work. I tried escaping the * already, I guess it's evaluated somewhere before it should in another directory and lost.

**Comment by c0bw3b** [comment]
Weird, I did try locally and I could build it with the escape, but it does fail on Hydra... Reverted in 614cf5d00aa87587a9869bfeb0b78ad3f07563b2 anyway.

I was sure similar situation were solved with make flags array trickery (without a shell hook) but..

**Pull request merged**
