### PR TITLE
arm-trusted-firmware: tell Makefile how our C compilers are named

### PR DESCRIPTION
**Pull request by sternenseemann**
## Description of changes

We already did this for `stdenv.cc` via `CROSS_COMPILE`, but neglected `HOSTCC`/`CC_FOR_BUILD` and the `arm-embedded` toolchain.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by lopsided98 — APPROVED** [review]
Cross-compiled all targets, and tested native and cross build of `armTrustedFirmwareTools`.

**Comment by sternenseemann** [comment]
The `HOSTCC` may actually be wrong, I'll look into it soon or rebase it out for now.

**Comment by lopsided98** [comment]
In what way? I was concerned that it wouldn't be expanded correctly, but it seems to. On the other hand, I don't think any of the targets actually use it, and it gets overridden in `armTrustedFirmwareTools`, where we want to build everything for the host platform.

**Comment by sternenseemann** [comment]
@lopsided98 Thanks, you are right! Got confused by precisely that trick. I added an explanatory comment and removed `CC_FOR_BUILD` from the environment of that derivation (just to be safe) in a new commit.

**Review by ghost — APPROVED** [review]
LGTM but I'm currently unable to test this (beyond building it, which I did do).

Something in Binutils 2.39 or 2.40 broke `arm-trusted-firmware`'s wake-from-sleep on RK3399.  Nixpkgs aggressively deletes old binutils -- **except for vendor toolchains,** which I will probably be forced to switch to.

So I haven't been able to rebuild ATF for the last ~year :rage: .  ATF is annoyingly fragile.  I should probably just bite the bullet and accept that I have to use the vendor toolchains like normal people do.  It's kinda sad that that is the only way to pin binutils on nixpkgs.

**Comment by amjoseph-nixpkgs** [comment]
> overriding the binutils version used to build something is a bit finnicky.

I've always wondered why that is so difficult.  Is there some fundamental reason why that is the case?

Being able to `overrideBinutils` the same way we can `overrideCC` is a need that I encounter quite frequently.  I know @RaitoBezarius has a pressing need for it.

**Comment by sternenseemann** [comment]
I don't see a reason why it shouldn't be possible. It's just more finnicky since the bintools wrapper needs to be passed to the cc wrapper.

**Pull request merged**
