### PR TITLE
nixos/plantuml-server: fix

### PR DESCRIPTION
**Pull request by anthonyroussel**
## Description of changes

PlantUML Server was failing since Jetty 12.x upgrade.

Indeed, PlantUML Server does not support Jetty versions higher than 12.x: it has introduced major breaking changes, see
* https://github.com/jetty/jetty.project/releases/tag/jetty-12.0.0
* https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-migration-11-to-12

I added a NixOS test to be notified sooner if this NixOS module breaks again.

Also done:

* Added jetty_11, jetty_12
* Aliased jetty to jetty_12
* Removed `with lib;` notation from plantuml-server module
* Removed allowPlantumlInclude option (ALLOW_PLANTUML_INCLUDE has been removed upstream)
* Updated jetty_12 to 12.0.3
* Added hardening options to plantuml-server SystemD service
* Added myself as maintainer

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by emmanuelrosa — COMMENTED** [review]
Since 11.x.nix and 12.x.nix are largely identical, I think it's worth factoring out the common code:

```
# 11.x.nix
{ lib, stdenv, fetchurl }:

import ./common.nix { 
    inherit lib stdenv fetchurl; 
    version = "11.0.18";
    src = ...;
}

```

```
# common.nix

{ lib, stdenv, fetchurl, version, src }:

stdenv.mkDerivation rec {
    inherit version src;
    ...
}

```

**Comment by anthonyroussel** [comment]
> Since 11.x.nix and 12.x.nix are largely identical, I think it's worth factoring out the common code:
> 
> ```
> # 11.x.nix
> { lib, stdenv, fetchurl }:
> 
> import ./common.nix { 
>     inherit lib stdenv fetchurl; 
>     version = "11.0.18";
>     src = ...;
> }
> ```
> 
> ```
> # common.nix
> 
> { lib, stdenv, fetchurl, version, src }:
> 
> stdenv.mkDerivation rec {
>     inherit version src;
>     ...
> }
> ```

Hello @emmanuelrosa, thanks for the review!
Indeed, I factored the common code in the 11.x.nix and 12.x.nix files into a common.nix file.

**Review by emmanuelrosa — APPROVED** [review]
I tested jetty 11 and 12 and they both worked.
Note, I didn't test plantuml. I'll leave that to the experts.

**Comment by drupol** [comment]
Super cool refactoring!

**Pull request merged**
