### PR TITLE
clonehero: 0.23.2.2 -> 1.0.0.4080

### PR DESCRIPTION
**Pull request by kira-bruneau**
###### Description of changes

Expands on draft PR #228096 to support the latest version of Clone Hero: https://clonehero.net/2022/11/29/v1-release.html

This release also no longer requires any wrappers!! User configured files are now stored in `~/.clonehero` and clonehero now no longer tries to read system fonts from `/usr/share/fonts`, so we don't need the fhs wrapper!

@syboxez

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kira-bruneau** [comment]
Result of `nixpkgs-review pr 229321` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>clonehero</li>
    <li>clonehero.doc</li>
  </ul>
</details>

**Comment by wegank** [comment]
Breaking changes for 23.05 were restricted a few hours ago. Too bad.

**Comment by kira-bruneau** [comment]
> Breaking changes for 23.05 were restricted a few hours ago. Too bad.

😢 Hmm, well I could add a wrapper script back that would keep all the files in the same directory, so then it wouldn't be a breaking change...

now that the wrapper is no longer necessary though, I'd prefer to keep things closer to upstream.

**Comment by syboxez** [comment]
Not sure if symlinking the directory is an option, but that should result in no breaking changes, assuming that ~/.clonehero doesn't already exist.

**Comment by kira-bruneau** [comment]
That could potentially work, but I'm a bit cautious trying to paper over something that's designed to have an explicit migration step. I'm just not sure of all the potential ways that things could go wrong.

I think the safest best would be to copy the files over, but then you have duplicate files between the two folders.

**Pull request merged**
