### PR TITLE
rustPlatform: importCargoLock may accept lockText instead of lockFile as a param

### PR DESCRIPTION
**Pull request by NickCao**
###### Motivation for this change
`importCargoLock` as it is now has a major limitation: due to IFD being disabled in hydra, we have to maintain a copy of `Cargo.lock` for every packaged crate within nixpkgs, which is not easy. However like what we've done with `hackage-packages.nix`, we may automatically generate a combined nix expression of `Cargo.lock` in its text form from all the rust crates packaged into something like `crates-packages.nix`. To accomplish that, we may extend the params of `importCargoLock` to accept a string instead of a path.

backgroud: `nix-prefetch-url` and friends enable us to calculate the hashes of source trees beforehand, however for language specific package managements, such as cargo or go mod, there had been nothing better than inserting a fake hash then parsing the error log. With the introduction of `importCargoLock`, we can calculate a `derivation` beforehand, which is a large step ahead. But unlike a short hash, there's no good way of inserting a `derivation` into generated nix expressions to be tracked by version controls. Meanwhile the language specific locks themselves are easier to tackle with, which motivates this pull request.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxalica** [comment]
> we may automatically generate a combined nix expression of Cargo.lock in its text

In this case, the generated integrated lock file is still a file in nixpkgs. We can just import it. Why is `lockText` required?

**Comment by NickCao** [comment]
> In this case, the generated integrated lock file is still a file in nixpkgs. We can just `readFile` without IFD. Why is `lockText` required?
We have to split the combined lock file into individual ones anyway.

**Comment by andir** [comment]
> `importCargoLock` as it is now has a major limitation: due to IFD being disabled in hydra, we have to maintain a copy of `Cargo.lock` for every packaged crate within nixpkgs, which is not easy. However like what we've done with `hackage-packages.nix`, we may automatically generate a combined nix expression of `Cargo.lock` in its text form from all the rust crates packaged into something like `crates-packages.nix`. To accomplish that, we may extend the params of `importCargoLock` to accept a string instead of a path.

Are you proposing to create the super-set of all our dependencies as a single Cargo.lock file? Why would that be required to be passed as text while we can do a `builtins.readFile` (for files within nixpkgs)?

If such tooling, that you mentioned, already exists: Can you share an example use case?


> But unlike a short hash, there's no good way of inserting a `derivation` into generated nix expressions to be tracked by version controls. Meanwhile the language specific locks themselves are easier to tackle with, which motivates this pull request.

What do you mean by injection a derivation into the generated nix expressions? Do you want to declare additional dependencies outside of the Cargo.lock file?

**Comment by NickCao** [comment]
> Why would that be required to be passed as text while we can do a builtins.readFile (for files within nixpkgs)?

`importCargoLock` uses the passed `lockFile` in two places, the first is parsing packages out of the **text** itself to generate the corresponding FODs, and the second is symlinking the **file** into the vendor directory. We can't split a file into multiple files, can we? In That sense, allow passing in `lockText` instead of `lockFile` makes much sense.

> If such tooling, that you mentioned, already exists: Can you share an example use case?

A prominent use case is [nvfetcher](https://github.com/berberman/nvfetcher), which not only checks the latest versions of projects, but also prefetches the source tree, and generates a `sources.nix` like this:
```nix
# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  butane = {
    pname = "butane";
    version = "v0.11.0";
    src = fetchgit {
      url = "https://github.com/coreos/butane";
      rev = "v0.11.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1s4rkq7mj1lyi8h47jyfy3qygfxhrmpihdy8rcnn55gcy04lm0qc";
    };
  };
  k0sctl = {
    pname = "k0sctl";
    version = "v0.8.4";
    src = fetchgit {
      url = "https://github.com/k0sproject/k0sctl";
      rev = "v0.8.4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "08k0aa73kb4hs4zl8a2nmasag0czmppb2r0s1afj287c2a4ynw73";
    };
  };
}
```
It works perfectly for languages that relies on nix for managing dependencies. But for rust, we still have to fill in a `cargoHash` manually, which makes automated bumps impossible. `importCargoLock` eliminates the need for a `cargoHash`, but it relies on IFD from the source tree. However we may leave the work of IFD to nvfetcher to generate a `sources.nix` like this:
```nix
# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  butane = {
    pname = "butane";
    version = "v0.11.0";
    src = fetchgit {
      url = "https://github.com/coreos/butane";
      rev = "v0.11.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1s4rkq7mj1lyi8h47jyfy3qygfxhrmpihdy8rcnn55gcy04lm0qc";
    };
    cargoLockText = ''
        # This file is automatically @generated by Cargo.
        # It is not intended for manual editing.
        version = 3

        [[package]]
        ...
    '';
  };
}
```
by copying `Cargo.lock` from source trees into a combined file, in this case `sources.nix`. IFD is no longer required, automated bumps work as intended, and there is only one generated/copied file to track.

**Comment by berberman** [comment]
Can we put aside the connections to rust packages in nixpkgs and merge this? Adding such an option shouldn't be considered as harmful, and at least one of its potential use cases would be associated with `nvfetcher`, as @NickCao discussed above.

**Comment by danieldk** [comment]
> `importCargoLock` as it is now has a major limitation: due to IFD being disabled in hydra, we have to maintain a copy of `Cargo.lock` for every packaged crate within nixpkgs, which is not easy.

Do you mean maintaining `Cargo.lock` files within nixpkgs or externally. I think that *within nixpkgs* I would personally prefer per-package `Cargo.lock` files over one large combined `Cargo.lock` file. In the latter case, we'd probably end up with a lot of merge conflicts between PRs.

> However like what we've done with `hackage-packages.nix`, we may automatically generate a combined nix expression of `Cargo.lock` in its text form from all the rust crates packaged into something like `crates-packages.nix`. To accomplish that, we may extend the params of `importCargoLock` to accept a string instead of a path.

If I understand the proposal correctly, you need more than just this additional argument. Currently, the assumption is that all the dependencies in `Cargo.lock` need to be vendored. So if the passed `Cargo.lock` is the union of the `Cargo.lock` files of 100 binary crates, then the vendor directory will contain all versioned dependencies of all those 100 binary crates. Also, we currently check if the `Cargo.lock` of the vendor directory matches with that of the binary crate being built. The build of a binary crate would fail, because the `Cargo.lock` set union wouldn't match the binary crate's `Cargo.lock`.

But it could well be that I misunderstand the proposed extension.

**Comment by danieldk** [comment]
> `importCargoLock` eliminates the need for a `cargoHash`, but it relies on IFD from the source tree.

You can include the `Cargo.lock` file in the repository where you do the `importCargoLock` (which is often the main projects repository), no IFD needed. Sure, if you do something like

```nix
cargoLock = {
  lockFile = ${src}/Cargo.lock;
};
```

Then that's IFD, but if the file is provided in the repository, then this is not an IFD:

```nix
cargoLock = {
  lockFile = ./Cargo.lock;
};
```

**Comment by danieldk** [comment]
> Can we put aside the connections to rust packages in nixpkgs and merge this?

We require proper reviews of changes in nixpkgs. If we extend an API and have to change it later, we break things for a lot of downstream users. API changes should not be taken lightly and should be well thought-out.

**Comment by danieldk** [comment]
> by copying `Cargo.lock` from source trees into a combined file, in this case `sources.nix`. IFD is no longer required, automated bumps work as intended, and there is only one generated/copied file to track.

I am not sure I like big blobs of TOML in Nix strings. Separation of concerns and all that.

Couldn't you store the lockfiles separately (e.g. `broot.lock` for a source with the attribute `broot`) and import that?

I realize that this is currently not usable with `buildRustPackage`, because it does expects a `cargoLock` attribute and passes that to `importCargoLock`. But it may not be too late to consider changing that.

**Comment by NickCao** [comment]
This change do require further consideration, I'm closing this for now. However being able to use a string rather than a path in `importCargoLock` can open up more possibilities, without much drawbacks, it I still see it worth trying.

**Comment by berberman** [comment]
Thank you for your reply @danieldk.

> I am not sure I like the idea of having big blobs of TOML in Nix strings. Separation of concerns and all that.
> 
> Couldn't you store the lockfiles separately (e.g. `broot.lock` for a source with the attribute `broot`) and import that?

Having separate lock files stored does work, but it's not totally suited to our use case with [`nvfetcher`](https://github.com/berberman/nvfetcher). Let me recap it here. Essentially, `nvfetcher` is designed to automatically track upstream updates and run prefetch like [that](https://github.com/NixOS/nixpkgs/pull/124961#issuecomment-851024053). Further, now `nvfetcher` supports calculating `outputHashes` for git dependencies in `cargoLock`. Let's take https://github.com/NixOS/nixpkgs/blob/522a2a222f9529ce94cdc0fe256b11154f97f258/pkgs/build-support/rust/test/import-cargo-lock/git-dependency/Cargo.lock as an example:

```
#nvfetcher.toml
[git-dependency]
src.manual= "522a2a222f9529ce94cdc0fe256b11154f97f258"
fetch.github = "NixOS/nixpkgs"
cargo_lock = "pkgs/build-support/rust/test/import-cargo-lock/git-dependency/Cargo.lock"
```
Here we create a fake package called `git-dependency`, whose src is pointed to a pinned nixpkgs, so we can test calculating `outputHashes` on the lock file mentioned above. The answer of `nvfetcher` is:

```nix
# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  git-dependency = {
    pname = "git-dependency";
    version = "522a2a222f9529ce94cdc0fe256b11154f97f258";
    src = fetchgit {
      url = "https://github.com/NixOS/nixpkgs";
      rev = "522a2a222f9529ce94cdc0fe256b11154f97f258";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0cbj0wmb9xspqgbzszj217s27zwq7gp4hf852v12864qzb8spfyq";
    };
    cargoLock = {
      lockFile = ./pkgs/build-support/rust/test/import-cargo-lock/git-dependency/Cargo.lock;
      outputHashes = {
        "rand-0.8.3" = "0l3p174bpwia61vcvxz5mw65a13ri3wy94z04xrnyy5lzciykz4f";
      };
    };
  };
}

```

This nix expr will be written down to a file `sources.nix`, so we can use it to create package drv, like:

```nix
{ rustPlatform, }:

let sources = import ../sources.nix;
in rustPlatform.buildRustPackage {
  pname = "git-dependency";

  inherit (sources.${pname}) version src cargoLock;

}
```

Obviously this does **not** work, since the value of `lockFile` is invalid - we don't have `Cargo.lock` stored in such path. So the possible fix could be using IFD as you said:

```nix
cargoLock = {
  lockFile = ${src}/Cargo.lock;
};
```

However, we should avoid using IFD as much as possible, so we will have to cpoy `Cargo.lock` to somewhere relative to `sources.nix` during running `nvfetcher`. This could be a workaround, but imagine that you have tons of Rust packages like that to be handled by `nvfetcher`, if we make a copy of each lock file, scattering generated files would be too annoying, i.e. we want to maintain only the `sources.nix`, the monolithic file which contains all we need to create drvs for a set of packages. The `sources.nix` does not need to be much human readable, and having big blobs shouldn't be a big deal - it's generated automatically by a tool. Conversely, maintaining many lock files with `sources.nix` is kind of overhead imho, so with the changes done by this PR is important for us.

I hope you can understant the use case we talk about here, which might be somehow different from the intended one. Although `buildRustPackage` is not put under the project root, we still want to make the use of `cargoLock` to update Rust packages. If you still don't think this PR is a good idea, would it be possible to expose `cargoDeps` in `buildRustPackage`, so that we could implement our version of `importCargoLock`?

**Comment by NickCao** [comment]
@danieldk I tested myself and found that cargo will check wether `Cargo.lock` matches the vendor dir itself. Then what's the point of symlinking `Cargo.lock` into the vendor dir and checking it in `cargoSetupPostPatchHook`?

ref: [cargoSetupPostPatchHook](https://github.com/danieldk/nixpkgs/blob/d3769e43c34fe16a263938c584e6cdc92b18f6d5/pkgs/build-support/rust/hooks/cargo-setup-hook.sh#L45)

**Comment by danieldk** [comment]
> so we will have to cpoy `Cargo.lock` to somewhere relative to `sources.nix` during running `nvfetcher`. This could be a workaround, but imagine that you have tons of Rust packages like that to be handled by `nvfetcher`, if we make a copy of each lock file, scattering generated files would be too annoying, i.e. we want to maintain only the `sources.nix`, the monolithic file which contains all we need to create drvs for a set of packages.

Thanks for the detailed description of your use case. I think the proposed change would be nicer if it would allow passing in the Cargo lock file as a Nix attrset rather than a TOML string. This would offer a more flexible interface and provide well-formedness guarantees. I am not sure if we could make this work easily:

* nvfetcher would have to convert the lock file to Nix.
* Nix currently doesn't have a `toTOML` built-in. So, we'd have to use `builtins.toJSON` plus something like `json2toml` from `remarshal` to generate the lock file in the vendor directory. I am not sure if this roundtrip is lossless.

**Comment by berberman** [comment]
Yeah, allow passing nix attrs would be much nicer. So the blocker here is that there's no easy way to convert nix expr into TOML. But I'm not sure what's going on here - why do we have to re-generate lock files in vendor dir? What are they used for? Is https://github.com/NixOS/nixpkgs/pull/124961#issuecomment-851779687 true?

**Comment by blaggacao** [comment]
In this context, although probably not immediately actionable, I consider it makes sense to be in the knowns of https://github.com/NixOS/rfcs/pull/92

**Pull request closed without merging**
