### PR TITLE
haskell lens: don't run doctests

### PR DESCRIPTION
**Pull request by itcowed**
my proposed solution to #8522

### CODE REVIEW

**Comment by dnhgff** [comment]
hah, wrong change. will fix in a minute

**Comment by dnhgff** [comment]
right, that's the commit i meant to commit

**Comment by jb55** [comment]
:+1: I did the same change to my local nixpkgs after noticing it taking forever.

**Comment by peti** [comment]
Actually, I'd rather not disable the test suite for a package that's as central as lens is. Users who don't want to run it can easily add a `dontCheck` override in `~/.nixpkgs/config.nix` to disable the tests locally, but IMHO the central builds *should* execute those tests.

**Comment by Fuuzetsu** [comment]
‘It runs too long on my machine’ is not a valid justification of skipping it for everyone and this is coming from someone who spent many hours of his life waiting for those very tests to finish.

For the most part, binary caches should deal with this.

**Comment by vcunat** [comment]
You might want to have all builds depend on an unchecked version and add a separate checked version to catch problems on Hydra. That way you can relatively easily satisfy both objectives IMHO.

**Comment by jb55** [comment]
Ah I didn't realize you could set dontCheck in config. That's a much better solution.

**Comment by dnhgff** [comment]
thank you all for your responses. i am closing this at this point as it does not seem desired

**Pull request closed without merging**
