### PR TITLE
Emacspeak add at 44

### PR DESCRIPTION
**Pull request by KoviRobi**
###### Motivation for this change

Adding emacspeak because I wanted to try it out. I have no idea about emacs packages, so someone who knows how those work should review it. Not sure if it is a package, or a standalone executable, as it creakes an "emacspeak" script that calls emacs loading emacs-setup.el

Also could not get either software-dtk working, or linux-outloud, so just have a false assertion

Requires #17021, henced the 2 'commits'
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
@ttuegel may help you with emacs packaging questions.

**Comment by KoviRobi** [comment]
Thank you, @ttuegel the `emacspeak` executable works, but it does not seem to work as a `(require 'emacspeak)`, only as `(load "/nix/...emacspeak-44.0/share/emacs/site-lisp/emacspeak/lisp/emacspeak-setup.el")` though not sure if this is due to emacspeak or my packaging

**Comment by ttuegel** [comment]
@KoviRobi You need to set `EMACSLOADPATH` for the script so it Emacs can find your package.

**Comment by joachifm** [comment]
@KoviRobi are you still working on this?

**Comment by KoviRobi** [comment]
I started working on other stuff, may return to it when I'm looking for an audio interface (because augmented reality glasses are expensive ;) ) but feel free to delete the pull request if you want to

**Comment by c0bw3b** [comment]
@KoviRobi I will close this for now.
Feel free to reopen or come back with a new PR when you get it running. :)

**Pull request closed without merging**
