### PR TITLE
mention-bot: user blacklist

### PR DESCRIPTION
**Pull request by spwhitt**
Introduces a configuration file for mention-bot and blacklists @civodul as requested in #11485. @ip1981

### CODE REVIEW

**Comment by civodul** [comment]
Spencer Whitt <notifications@github.com> skribis:

> Introduces a configuration file for mention-bot and blacklists @civodul as requested in #11485.

Thank you!

(It’s unusual to thank someone for adding you to a black list I guess. :-))

Ludo’.

**Comment by civodul** [comment]
This doesn't seem to work, though.  Could you take a look?

TIA!

Ludo'.

**Comment by spwhitt** [comment]
Sorry about that. @dezgeg pointed out that the problem may be that the comment which I included isn't legal in JSON. I've updated this PR with a commit to remove that comment, which can be merged.

**Comment by civodul** [comment]
Spencer Whitt <notifications@github.com> skribis:

> Sorry about that. @dezgeg pointed out that the problem may be that the comment which I included isn't legal in JSON. I've updated this PR with a commit to remove that comment, which can be merged.

Great, thanks.  I’m eager to see it merged.  ;-)

Ludo’.

**Pull request closed without merging**
