### PR TITLE
linux_testing_bcachefs,bcachefs-tools: 20190209

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
This has been not tested?

**Comment by eadwu** [comment]
I'll rebuild the kernel so that it targets this one, since the only kernel I tested is `linuxPackages_latest` being patched with bcachefs.

**Comment by eadwu** [comment]
Works fine on my setup.

**Comment by Mic92** [comment]
I tried to get the test running for bcachefs, but
it failed to build `nix-build nixos/tests/bcachefs.nix`:
https://gist.github.com/d243d86e85336e5944e12ec8637e37dd

**Comment by eadwu** [comment]
The test fails for 20190123 with the same error `machine# switch_root: can't execute '/nix/store/5fjzgbw2jgwsch45lagv7fmym3kb07pq-nixos-system-machine-19.03.git.633cf42/init': Operation not permitted`.

**Comment by danielfullmer** [comment]
Since this bcachefs kernel is version 4.20, I believe the failed test is a result of this issue: https://github.com/NixOS/nixpkgs/issues/54509

**Pull request merged**
