### PR TITLE
igir: init at 2.0.6

### LINKED ISSUE #239848: Package request: igir
**Project description**

A video game ROM collection manager to help filter, sort, patch, archive, and report on collections on any OS. 

**Metadata**

* homepage URL: https://igir.io/
* source URL: https://github.com/emmercm/igir
* license: gpl3
* platforms: linux

### PR DESCRIPTION
**Pull request by TheBrainScrambler**
## Description of changes

https://igir.io
A video game ROM collection manager to help filter, sort, patch, archive, and report on collections on any OS.

Closes https://github.com/NixOS/nixpkgs/issues/239848

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TheBrainScrambler** [comment]
Um there is something about a conflict, but I don't understand why ...

**Comment by keenanweaver** [comment]
Result of `nixpkgs-review pr 252765` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>igir</li>
  </ul>
</details>

**Review by keenanweaver — APPROVED** [review]
Working great. Thank you very much!

Edit: Looks like a newer version was reccently released https://github.com/emmercm/igir/releases/tag/v1.9.4

**Comment by TheBrainScrambler** [comment]
> Looks like a newer version was reccently released https://github.com/emmercm/igir/releases/tag/v1.9.4

I've updated it

**Comment by keenanweaver** [comment]
Result of `nixpkgs-review pr 252765` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>igir</li>
  </ul>
</details>

**Review by keenanweaver — APPROVED** [review]

**Comment by keenanweaver** [comment]
It's been updated to 2.0.0 now. Jeez. https://github.com/emmercm/igir/releases/tag/v2.0.0

**Comment by TheBrainScrambler** [comment]
> It's been updated to 2.0.0 now. Jeez. https://github.com/emmercm/igir/releases/tag/v2.0.0

Nice, I've updated it again

**Comment by keenanweaver** [comment]
Result of `nixpkgs-review pr 252765` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>igir</li>
  </ul>
</details>

**Review by keenanweaver — APPROVED** [review]

**Review by LeSuisse — APPROVED** [review]
:+1:

**Pull request merged**
