### PR TITLE
llm-ls: init at 0.4.0

### LINKED ISSUE #263181: Package request: llm-ls
**Project description**
https://github.com/huggingface/llm-ls

The goal of llm-ls is to provide a common platform for IDE extensions to be build on. llm-ls takes care of the heavy lifting with regards to interacting with LLMs so that extension code can be as lightweight as possible.

it has extensions for vscode/neovim already. 

I have no feedback on this software at all but seemed like something I want to try. Maybe it doesn't work well enough to get merged in nixpkgs but I would like to try it with codellama in neovim

**Metadata**

* homepage URL: https://github.com/huggingface/llm-ls
* source URL: https://github.com/huggingface/llm-ls
* license: apache2 
* platforms: unix I think

### PR DESCRIPTION
**Pull request by jfvillablanca**
## Description of changes
Resolves https://github.com/NixOS/nixpkgs/issues/263181

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jfvillablanca** [comment]
Result of `nixpkgs-review pr 263320` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>llm-ls</li>
  </ul>
</details>

**Comment by teto** [comment]
thanks for the package: I was able to test it successfully with https://github.com/huggingface/llm.nvim. Seems like it breaks on darwin so maybe make it available only for linux ? Also the file could be moved to pkgs/by-name as recommended at https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#readme

**Comment by jfvillablanca** [comment]
> thanks for the package: I was able to test it successfully with https://github.com/huggingface/llm.nvim. Seems like it breaks on darwin so maybe make it available only for linux ? Also the file could be moved to pkgs/by-name as recommended at https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#readme

initially, i set it like this
```nix
platforms = with platforms; [ linux ];
```
then, per recommendation from the [docs](https://nixos.org/manual/nixpkgs/stable/#var-meta-badPlatforms), i changed it to:
```nix
platforms = with platforms; [ all ];
badPlatforms = with platforms; [ darwin ];
```
however, i'm having trouble making nix build with either one because this is what nix detects as my platform:
`hostPlatform.config = "x86_64-unknown-linux-gnu"`
which isn't part of the list of [targets](https://github.com/NixOS/nixpkgs/blob/master/lib/systems/doubles.nix)

What am I missing here?

**Comment by adisbladis** [comment]
Platforms are already in list form:

``` nix
platforms = with platforms; [ all ];
badPlatforms = with platforms; [ darwin ];
```
->
``` nix
platforms = platforms.all;
badPlatforms = platforms.darwin;
```

**Comment by jfvillablanca** [comment]
> Platforms are already in list form:
> 
> ```nix
> platforms = with platforms; [ all ];
> badPlatforms = with platforms; [ darwin ];
> ```
> 
> ->
> 
> ```nix
> platforms = platforms.all;
> badPlatforms = platforms.darwin;
> ```

Thanks! 😅

**Review by teto — APPROVED** [review]

**Pull request merged**
