### PR TITLE
wakatime: 7.0.4 -> 8.0.2

### PR DESCRIPTION
**Pull request by yurrriq**
###### Motivation for this change

Upgrade to latest version and switch from `buildPythonPackage` to `buildPythonApplication`.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
Acoording to travis, the hash seems to be wrong: https://travis-ci.org/NixOS/nixpkgs/jobs/236475922#L1520

**Comment by yurrriq** [comment]
This happened to me once before. It works on my system. Is it possible there's something wrong with it?

**Comment by yurrriq** [comment]
Can someone sort out the hash issues?

**Comment by joachifm** [comment]
@yurrriq How are you generating the hash?

**Comment by yurrriq** [comment]
`nix-build -A wakatime` and copying from where it says "has hash ... but expected ..."

**Comment by yurrriq** [comment]
Thanks, @orivej!

**Pull request closed without merging**
