### PR TITLE
phpExtensions.opentelemetry: fix builds on Darwin

### LINKED ISSUE #304809: Build failure: phpExtensions.opentelemetry 1.0.2 on MacOS Sonoma
### Steps To Reproduce

1. build opentelemetry extension on MacOS
```
nix build github:r-ryantm/nixpkgs/a399db43527b481d2af275ba058a4dc1d36ed373#php81Extensions.opentelemetry
```

### Build log

```
error: builder for '/nix/store/gsma784mx1iy2sbnbvd2wdxkld1asc3z-php-opentelemetry-1.0.2.drv' failed with exit code 2;
       last 10 log lines:
       >              ~~~~~~~~~~^~~~~~~~~~~
       > /private/tmp/nix-build-php-opentelemetry-1.0.2.drv-1/source/ext/otel_observer.c:231:24: note: remove extraneous parentheses around the comparison to silence this warning
       >         if ((type_mask == IS_UNDEF)) {
       >             ~          ^          ~
       > /private/tmp/nix-build-php-opentelemetry-1.0.2.drv-1/source/ext/otel_observer.c:231:24: note: use '=' to turn this equality comparison into an assignment
       >         if ((type_mask == IS_UNDEF)) {
       >                        ^~
       >                        =
       > 1 error generated.
       > make: *** [Makefile:211: otel_observer.lo] Error 1
       For full logs, run 'nix-store -l /nix/store/gsma784mx1iy2sbnbvd2wdxkld1asc3z-php-opentelemetry-1.0.2.drv'.
```

### Additional context

This occurred after this PR was merged: https://github.com/NixOS/nixpkgs/pull/303437

### Notify maintainers

@drupol 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/avraham.appel/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by drupol**
This PR:

- Should fix https://github.com/NixOS/nixpkgs/issues/304809

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
@avrahamappel Can you please test this PR ?

**Comment by drupol** [comment]
@ofborg build phpPackages.opentelemetry

**Comment by drupol** [comment]
@ofborg build phpExtensions.opentelemetry

**Comment by avrahamappel** [comment]
@drupol Works for me! Thanks!

**Comment by drupol** [comment]
@gaelreyrol Are you OK to merge this "as-is" to unblock the current situation and improve the state in a next iteration PR ?

**Pull request merged**
