### PR TITLE
mercurial: 4.5 -> 4.5.2

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update generated by https://github.com/ryantm/nix-update tools. These checks were done:

- built on NixOS
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/hg -h` got 0 exit code
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/hg --help` got 0 exit code
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/hg help` got 0 exit code
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/hg --version` and found version 4.5.2
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/hg version` and found version 4.5.2
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/..hg-wrapped-wrapped -h` got 0 exit code
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/..hg-wrapped-wrapped --help` got 0 exit code
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/..hg-wrapped-wrapped help` got 0 exit code
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/..hg-wrapped-wrapped --version` and found version 4.5.2
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/..hg-wrapped-wrapped version` and found version 4.5.2
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/.hg-wrapped -h` got 0 exit code
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/.hg-wrapped --help` got 0 exit code
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/.hg-wrapped help` got 0 exit code
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/.hg-wrapped --version` and found version 4.5.2
- ran `/nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2/bin/.hg-wrapped version` and found version 4.5.2
- found 4.5.2 with grep in /nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2
- found 4.5.2 in filename of file in /nix/store/vr3mxrjhmmpqydkd69z3fdc7qjdsafgz-mercurial-4.5.2
- directory tree listing: https://gist.github.com/7a681b5af1e240918913ffd718e9b3e9

cc @edolstra for review

### CODE REVIEW

**Comment by ryantm** [comment]
@GrahamcOfBorg eval

**Comment by volth** [comment]
@GrahamcOfBorg build mercurial

**Comment by dtzWill** [comment]
@GrahamcOfBorg build mercurial

**Comment by 7c6f434c** [comment]
macOS build is often broken but sometimes succeeds: https://hydra.nixos.org/job/nixpkgs/staging/mercurial.x86_64-darwin

This specific build timed out on configd: `building of '/nix/store/yc8sdvyaxhs2djaad0p94614dk3rwwna-configd-osx-10.8.5.drv' timed out after 1800 seconds`

**Pull request merged**
