### PR TITLE
Newtonsoft.Json: 6.0.8 -> 11.0.2

### PR DESCRIPTION
**Pull request by nek0**
###### Motivation for this change

Package was outdated and needed for OpenRA.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nek0** [comment]
this also fixes #44470

**Review by samueldr — CHANGES_REQUESTED** [review]
Thank you for the update!

Is it be possible the first two commits (about vym) and the last commit (about monodevelop) were accidentally added to the branch? They don't seem to be related to `Newtonsoft.Json` changes. (A rebase would probably get rid of your first stow-away commits.)

Purging them from the branch, then squashing/rebasing to master would be necessary to, then, merge this.

* * *

As for the update, it removes a bunch of code (no code is good code), so if it doesn't cause issues elsewhere (to be tested) it'll probably be fine.

**Comment by nek0** [comment]
sry, something went awry...

**Comment by matthewbauer** [comment]
Does this fix the original issue though? We can just cherrypick c6323844e96af9932330f68293c66cc3c2de02e9 onto it if so.

**Comment by nek0** [comment]
yes, it fixes the original issue.

**Pull request closed without merging**
