### PR TITLE
onnxruntime: fix `x86_64-darwin` build

### PR DESCRIPTION
**Pull request by malob**
## Description of changes

Fix build on `x86_64-darwin`.

(ZHF: #309482)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by malob** [comment]
Result of `nixpkgs-review pr 311470` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by malob** [comment]
Result of `nixpkgs-review pr 311470` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by malob** [comment]
Result of `nixpkgs-review pr 311470` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.faster-whisper</li>
    <li>python311Packages.faster-whisper.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.tf2onnx</li>
    <li>python311Packages.tf2onnx.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
    <li>wyoming-faster-whisper</li>
    <li>wyoming-faster-whisper.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>magika (python311Packages.magika)</li>
    <li>magika.dist (python311Packages.magika.dist)</li>
    <li>python311Packages.fastembed</li>
    <li>python311Packages.fastembed.dist</li>
    <li>python312Packages.fastembed</li>
    <li>python312Packages.fastembed.dist</li>
    <li>python312Packages.magika</li>
    <li>python312Packages.magika.dist</li>
  </ul>
</details>
<details>
  <summary>45 packages built:</summary>
  <ul>
    <li>deface</li>
    <li>deface.dist</li>
    <li>onnxruntime</li>
    <li>onnxruntime.dev</li>
    <li>onnxruntime.dist</li>
    <li>piper-phonemize</li>
    <li>piper-tts</li>
    <li>private-gpt</li>
    <li>private-gpt.dist</li>
    <li>python311Packages.chromadb</li>
    <li>python311Packages.chromadb.dist</li>
    <li>python311Packages.insightface</li>
    <li>python311Packages.insightface.dist</li>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.onnxruntime</li>
    <li>python311Packages.onnxruntime.dist</li>
    <li>python311Packages.piper-phonemize</li>
    <li>python311Packages.piper-phonemize.dist</li>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
    <li>python311Packages.pysilero-vad</li>
    <li>python311Packages.pysilero-vad.dist</li>
    <li>python312Packages.chromadb</li>
    <li>python312Packages.chromadb.dist</li>
    <li>python312Packages.insightface</li>
    <li>python312Packages.insightface.dist</li>
    <li>python312Packages.llama-index</li>
    <li>python312Packages.llama-index-cli</li>
    <li>python312Packages.llama-index-cli.dist</li>
    <li>python312Packages.llama-index-vector-stores-chroma</li>
    <li>python312Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python312Packages.llama-index.dist</li>
    <li>python312Packages.onnxruntime</li>
    <li>python312Packages.onnxruntime.dist</li>
    <li>python312Packages.piper-phonemize</li>
    <li>python312Packages.piper-phonemize.dist</li>
    <li>python312Packages.private-gpt</li>
    <li>python312Packages.private-gpt.dist</li>
    <li>python312Packages.pysilero-vad</li>
    <li>python312Packages.pysilero-vad.dist</li>
  </ul>
</details>

**Comment by malob** [comment]
Failed builds for `python31{1,2}Packages.{fastembed,magika}` are unrelated to this fix.

**Comment by wegank** [comment]
I'm not sure why `iconv` is there instead of `libiconv`. Instead of the fix in this PR, would replacing `iconv` with `libiconv` help?

**Comment by malob** [comment]
@wegank, not sure, just tried the first thing that occurred to me and it worked. I'll try using `libiconv`.

**Comment by malob** [comment]
@wegank, alrighty made that change and it worked like a charm. Thanks for the suggestion.

**Pull request merged**
