### PR TITLE
[20.03] llvmPackages_10: init at 10.0.0

### PR DESCRIPTION
**Pull request by DieGoldeneEnte**
###### Motivation for this change
Backport of llvmPackages_10 since Chromium 83 will depend on it.
See https://github.com/NixOS/nixpkgs/pull/83350#issuecomment-605994185

@primeos Do we want to wait until Chromium 83 is released?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
@GrahamcOfBorg build llvm_10

**Review by primeos — APPROVED** [review]
The diff LGTM and the contents of `pkgs/development/compilers/llvm/10` are indeed the same as on master.

As this only adds new attributes there is additionally no chance of any breakage so I see no problem with merging this PR right away.

> @primeos Do we want to wait until Chromium 83 is released?

No need, it would actually best to merge this PR ASAP so that I can backport and test the required Chromium patches (including patches for some dependencies).

Edit: One thing I noticed is that you've already squashed all commits. AFAIK the normal approach would be to cherry-pick them individually, but since all original commit references are there I don't see any problems with this approach (it's probably cleaner anyway and I don't think we have any hard requirements regarding this - apart from the original commit references).

**Comment by primeos** [comment]
@NixOS/backports any objections? If not I'd assume that this is good to go (if the tests pass).

**Comment by primeos** [comment]
@DieGoldeneEnte thank you :)

**Comment by worldofpeace** [comment]
@primeos New packages are usually fine (especially if they're new versions of existing packages). As long as default versions don't change, that has much larger implications.

**Pull request merged**
