### PR TITLE
webcord: 4.1.1 -> 4.2.0

### PR DESCRIPTION
**Pull request by FlafyDev**
###### Description of changes

upgrades webcord: 4.1.1 -> 4.2.0
upgrades the electron version used for webcord: 22 -> 24
electron 22 had issues with requests being blocked after adding any extension. Does not occur on electron 24

Changelog: https://github.com/SpacingBat3/WebCord/compare/v4.1.1...v4.2.0
Release for 4.2.0: https://github.com/SpacingBat3/WebCord/releases/tag/v4.2.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by huantianad** [comment]
It seems upstream has updated to electron 24, should we get that into nixpkgs and use it, or is electron 23 fine?

**Comment by FlafyDev** [comment]
> It seems upstream has updated to electron 24, should we get that into nixpkgs and use it, or is electron 23 fine?

Electron 24 is in master but i don't think it's in unstable yet. If i update this PR to electron 24 I don't think I would be able to build and test it, since master doesn't have a cache and i can't build for that long. 

Please correct me if I got something wrong..

**Comment by huantianad** [comment]
#226271 should be in unstable soon, so hydra should already have it in its cache. I think we should go ahead and go to electorn 24. If you're unable to test it, we can wait until it's in unstable and I can test it myself later too.

**Review by huantianad — APPROVED** [review]
LGTM!

**Pull request merged**
