### PR TITLE
nixos/tailscale: add `state` option

### PR DESCRIPTION
**Pull request by colemickens**
## Description of changes

- add `inMemoryState`

this causes tailscale to make the registration ephemeral. I use this for booting the nixos installer (which auto-runs `sudo tailscale up --qr`), and this ensures that the hostname get reused, instead of suffixed.

Also, it's just nice to not need to manually cleanup tailscale hosts from the admin panel, when I know some are going to be ephemeral by nature anyway.

definitely open to feedback about naming the option.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Princemachiavelli** [comment]
Are the other valid `--state` values of interest? We could set a generic option with a type like:
`with lib.types; oneOf [ null path (strMatching "arn:aws:ssm:[^\s]+") (strMatching "kube:[^\s]+") (enum [ "mem:" ]) ]` to support all of the valid state backends.  The SSM backend seems like it could be useful for anyone using NixOS on AWS.

We could also add an `extraFlags` list option, since ATM custom flags can only be added by redefining the entire `FLAGS` environment variable.

**Comment by colemickens** [comment]
I tried to implement the more flexible `state` option, but the module system is defeating me:

`       error: value is null while a set was expected`

I don't get it, please send help. :pray:

**Comment by Princemachiavelli** [comment]
> I tried to implement the more flexible `state` option, but the module system is defeating me:
> 
> ` error: value is null while a set was expected`
> 
> I don't get it, please send help. 🙏

So if the value is null then just omit the `--state` flag so that it uses the tailscale default (use `lib.optionalString`). There actually is a PR (created around the same time) to add an option to pass extra flags so we'll likely want to merge these efforts.  #289386

**Comment by colemickens** [comment]
> > I tried to implement the more flexible `state` option, but the module system is defeating me:
> > ` error: value is null while a set was expected`
> > I don't get it, please send help. 🙏
> 
> So if the value is null then just omit the `--state` flag so that it uses the tailscale default (use `lib.optionalString`). There actually is a PR (created around the same time) to add an option to pass extra flags so we'll likely want to merge these efforts. #289386

Can you check the diff? That's indeed what I tried to do.

I'll take a look at #289386. While I wouldn't mind having a specific flag, it may be redundant with that PR.

**Comment by Princemachiavelli** [comment]
> Can you check the diff? That's indeed what I tried to do.
> 
> I'll take a look at #289386. While I wouldn't mind having a specific flag, it may be redundant with that PR.

Apologies, read it too fast. The issue was null isn't a type. And Nix doesn't have regex groups like '\s` either but I think this works:
```
with lib.types; oneOf [
     lib.types.path
     (strMatching "^arn:aws:ssm:[^[:space:]]+$")
     (strMatching "^kube:[^[:space:]]+$")
     (enum [ "mem:" null ])
];
```

I don't think it hurts to have the specific flag and `extraDaemonFlags` as long as they work well together.

**Comment by colemickens** [comment]
Thanks, pushed something that seems to work. Updated title.

**Comment by sedlund** [comment]
I was looking to add to FLAGS for tailscaled and trying to add them with systemd.services.tailscaled.environment

but see they are set with serviceConfig.Environment - is there a reason?

**Comment by colemickens** [comment]
This is now redundant from: https://github.com/NixOS/nixpkgs/pull/291907

Use this:

```
services.tailscale = {
  enable = true;
  extraDaemonFlags = [ "--state=mem:" ];
};
```

**Pull request closed without merging**
