### PR TITLE
hp2p: 3.3 -> unstable-2023-10-25

### PR DESCRIPTION
**Pull request by gesperon**
## Description of changes

    Rewrite hp2p in C
    Plotly visualisation is directly generated by hp2p. Python is not required anymore
    CUDA version to test bandwidth between NVIDIA GPU
    hp2p can generate binary output again
    Signals can be use during an hp2p run for generating output
    Print a warning during the run if communication is slow

EDIT: Description of changes above are from upstream hp2p
    Upgraded to master branch because 4.0 causes a a core dump

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Nyabinary** [comment]
The pr title and the commit should be: hp2p: 3.3 -> unstable-2023-10-25 and squashed into one commit :)

**Comment by gesperon** [comment]
> The pr title and the commit should be: hp2p: 3.3 -> unstable-2023-10-25 and squashed into one commit :)

Done. Thank you!

**Comment by Nyabinary** [comment]
Did you add yourself as a maintainer and add yourself to the maintainer list under the maintainer folder?

**Comment by gesperon** [comment]
> Did you add yourself as a maintainer and add yourself to the maintainer list under the maintainer folder?

I upgraded locally to use the new version and pushed the changes so other people don't have to do the same, but I don't really plan to maintain the package.

**Review by bzizou — APPROVED** [review]
It's ok for me, but maybe ask upstream to publish a 4.1 ?

**Comment by gesperon** [comment]
> It's ok for me, but maybe ask upstream to publish a 4.1 ?

They probably have their own release schedule and the amount of commits since 4.0 is pretty short.

**Comment by Nyabinary** [comment]
Need to squash this into one commit

**Comment by gesperon** [comment]
> Need to squash this into one commit

done

**Comment by Artturin** [comment]
@gesperon You only updated the PR title and not the commit message, I squash merged and corrected the commit message but in the future make sure both match.

**Pull request merged**
