### PR TITLE
treewide: Unquote most URLs

### PR DESCRIPTION
**Pull request by dasJ**
> Yes, I'm serious

###### Motivation for this change

Quoted URLs are strings instead of URLs. When using another package as example when writing one of my first packages, it got rejected because URLs shouldn't be quoted.
This PR removes quotes from URLs so nobody uses them as example as I did back then.
I excluded all URLs which contain one of these characters: `$#";(`

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
People intend to move in the opposite direction, see https://github.com/NixOS/nixpkgs/pull/27809#issuecomment-319494507

**Comment by dasJ** [comment]
Oh no

**Comment by dasJ** [comment]
I mean I could just reverse the regexp…

**Comment by dasJ** [comment]
@vcunat The main reason in my opinion is consistency. Having all packages follow the same pattern is a lot less confusing for new users. Of course there an almost infinite

**Comment by dasJ** [comment]
@vcunat The main reason in my opinion is consistency. Having all packages follow the same pattern is a lot less confusing for new users. Of course there is an almost infinite amount of ways you can package software, but IMO we should have some common ground for some parts. Maybe this PR isn't the proper location to discuss this and this is probably not the best time as well, as a new release is pretty close and there is more important stuff to do.
But these inconsistencies and "we'll refactor that one day"-things tend to add up and I always try to fix/refactor/… them ASAP.

**Comment by vcunat** [comment]
Perhaps, but _first_ we need a clear consensus that one of the two variants is preferred ;-)

**Comment by dasJ** [comment]
Yes, I agree with you. What do you think is the proper place for such a discussion? Discourse? IRC? Private Mails? This PR? A RFC?

**Comment by vcunat** [comment]
This thread isn't a bad start, IMHO.  RFC is another option.  We could link to that thread from other places if it seems there are too little eyes.

Consistency: note that we have URLs inside `fetchurl` and similar calls very commonly, and there we often want to interpolate some variables, and that can't be done in the unquoted style ATM.

**Comment by dasJ** [comment]
Yes, I also found that the url type fails for the characters I mentioned above: `$#;(`. While `$` is mostly used when using variables in a URL (which is a legitimate thing to do of course), `#`, `;`, and `(` are used as well. So these URLs would have to be strings (or am I just missing some escaping rules?) meaning that using the URL type will always include inconsistencies.

I haven't found other places where I can link this thread yet, but I'll keep looking :)

**Comment by oxij** [comment]
I vote for doing the reverse. Let me reiterate the arguments against unquoted URIs I liked in the previous discussions:

- simpler nix language EBNF,
- `magnet:abc` should this be a function or a URI?
- Nix can't properly encode all URIs without quotes anyway, as noted above.

**Comment by 7c6f434c** [comment]
And we do need quoted URLs for `src` handling (putting `${version}` inside the URL string is a good idea from the point of view of avoiding sily mistakes), so full unification means either quoted URLs or rejecting useful tools.

**Comment by edolstra** [comment]
While I'm favor of not quoting URLs, this PR causes a lot of code churn for a minor syntactic cleanup, which I think is to be avoided.

(BTW, I don't agree with the sentiment that "People [who?] intend to move in the opposite direction".)

**Comment by oxij** [comment]
@edolstra

> People intend to move in the opposite direction, see #27809 (comment)
> People [who?] intend to move in the opposite direction

Most people who commented in #27809, duh.

**Pull request closed without merging**
