### PR TITLE
nixos/kmonad: init

### PR DESCRIPTION
**Pull request by r-vdp**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by flokli** [comment]
Nice work!

**Comment by sifmelcara** [comment]
Asking for people like me (who already uses flake provided by upstream), does this work exactly the same as upstream's module? https://github.com/kmonad/kmonad/blob/master/nix/nixos-module.nix (at the first glance it seems only syntax is different)

Is anyone working on updating upstream's installation guide? https://github.com/kmonad/kmonad/blob/master/doc/installation.md#nixos

**Comment by r-vdp** [comment]
> Asking for people like me (who already uses flake provided by upstream), does this work exactly the same as upstream's module? https://github.com/kmonad/kmonad/blob/master/nix/nixos-module.nix (at the first glance it seems only syntax is different)
> 
> Is anyone working on updating upstream's installation guide? https://github.com/kmonad/kmonad/blob/master/doc/installation.md#nixos

I think it works the same, but I didn't explicitly compare. There might be minor api differences (different options).

**Comment by slotThe** [comment]
@r-vdp I would've been nice if you'd have given upstream a heads-up before opening this PR, since this breaks the configs of everyone currently using the KMonad flake (lots of options being defines twice)

**Comment by r-vdp** [comment]
> @r-vdp It would've been nice if you'd have given upstream a heads-up before opening this PR, since this breaks the configs of everyone currently using the KMonad flake (lots of options being defines twice)

Right, I never used the upstream module, so I forgot about that.

It should suffice to add a `disabledModules` to the upstream module to avoid the conflicts.

**Comment by AndrewKvalheim** [comment]
Could have at least followed the instructions to mention this the release notes.

**Comment by jian-lin** [comment]
I added a release note here: https://github.com/NixOS/nixpkgs/pull/368834.  Please review.

**Pull request merged**
