### PR TITLE
Fix broken patch to nodejs-4-1 when building on Darwin

### PR DESCRIPTION
**Pull request by utdemir**
This bug was introduced by #9941.

The last hunk on the patch was obsolete, just removed it.

### CODE REVIEW

**Comment by datakurre** [comment]
@gridaphobe @pikajude Any change that you could review that? This did not work for me in a sandboxed build, but resulted:

```
applying patch /nix/store/f60zh4jyq40dhzk7mvb4g653lpjh5sbq-no-xcode.patch
patching file tools/gyp/pylib/gyp/xcode_emulation.py
Hunk #1 succeeded at 446 (offset 144 lines).
Hunk #2 succeeded at 579 (offset 152 lines).
Hunk #3 succeeded at 835 with fuzz 2 (offset 153 lines).
Hunk #4 succeeded at 1043 (offset 169 lines).
configuring
configure flags: --prefix=/nix/store/1g5ahvjvrl9x8a0k328nf9lidcnd1fq4-nodejs-4.1.0 --shared-libuv --shared-libuv-includes=/nix/store/bkws9ba6p1jqnhpyjwf19aa3chhsd8h1-libuv-1.7.5/include --shared-libuv-libpath=/nix/store/bkws9ba6p1jqnhpyjwf19aa3chhsd8h1-libuv-1.7.5/lib --shared-openssl --shared-openssl-includes=/nix/store/xfm39dhb1k3mlv0fkdlq3ahmd2rcw580-openssl-1.0.2d/include --shared-openssl-libpath=/nix/store/xfm39dhb1k3mlv0fkdlq3ahmd2rcw580-openssl-1.0.2d/lib --shared-zlib --shared-zlib-includes=/nix/store/bln24shdm0w3h8dbd3fwc0b17z9vh02k-zlib-1.2.8/include --shared-zlib-libpath=/nix/store/bln24shdm0w3h8dbd3fwc0b17z9vh02k-zlib-1.2.8/lib --without-dtrace 
gyp: No Xcode or CLT version detected!
Error running GYP
creating  ./icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [ '/nix/store/bln24shdm0w3h8dbd3fwc0b17z9vh02k-zlib-1.2.8/include',
                                         '/nix/store/bkws9ba6p1jqnhpyjwf19aa3chhsd8h1-libuv-1.7.5/include',
                                         '/nix/store/xfm39dhb1k3mlv0fkdlq3ahmd2rcw580-openssl-1.0.2d/include'],
                       'libraries': [ '-I/nix/store/bln24shdm0w3h8dbd3fwc0b17z9vh02k-zlib-1.2.8/include',
                                      '-lz',
                                      '-I/nix/store/bkws9ba6p1jqnhpyjwf19aa3chhsd8h1-libuv-1.7.5/include',
                                      '-luv',
                                      '-lpthread',
                                      '-ldl',
                                      '-I/nix/store/xfm39dhb1k3mlv0fkdlq3ahmd2rcw580-openssl-1.0.2d/include',
                                      '-lssl',
                                      '-lcrypto']},
  'variables': { 'asan': 0,
                 'host_arch': 'x64',
                 'icu_small': 'false',
                 'node_byteorder': 'little',
                 'node_install_npm': 'true',
                 'node_prefix': '/nix/store/1g5ahvjvrl9x8a0k328nf9lidcnd1fq4-nodejs-4.1.0',
                 'node_release_urlbase': '',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'true',
                 'node_shared_openssl': 'true',
                 'node_shared_zlib': 'true',
                 'node_tag': '',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'false',
                 'node_use_lttng': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'false',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'python': '/nix/store/5qwi4bbqlq7k6jq9pyh7h425cways9nq-python-2.7.10/bin/python',
                 'target_arch': 'x64',
                 'uv_parent_path': '/deps/uv/',
                 'uv_use_dtrace': 'false',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 0,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 1,
                 'want_separate_host_toolset': 0}}
creating  ./config.gypi
creating  ./config.mk
builder for ‘/nix/store/n35i4z5s08dxaj8fxcb8g04l06fq7fq6-nodejs-4.1.0.drv’ failed with exit code 1
error: build of ‘/nix/store/n35i4z5s08dxaj8fxcb8g04l06fq7fq6-nodejs-4.1.0.drv’ failed
```

**Comment by utdemir** [comment]
@datakurre You're right, that's probably because I have XCode installed and there's still some XCode bits left there.

But I don't really know what that Python script does, I think someone who knows this script can fix this more efficiently (@svanderburg probably).

If the fix for the new problem is easy, it's best to close this pull request; but if the total fix will take time, it's better to have a partially working solution than not-working one in my opinion.

**Comment by datakurre** [comment]
Sounds like I should get my head out of sand and just update the no-xcode patch...

**Comment by utdemir** [comment]
Closing the PR since https://github.com/NixOS/nixpkgs/pull/10126 .

**Pull request closed without merging**
