### PR TITLE
godot_4: 4.2.1-stable -> 4.2.2-stable

### PR DESCRIPTION
**Pull request by superherointj**
godot_4: 4.2.1-stable -> 4.2.2-stable

Release: https://github.com/godotengine/godot-builds/releases/tag/4.2.2-stable

godot_4-export-templates: init 4.2.2-stable

On `pkgs/by-name` check, I found weird to move this to `pkgs/by-name` because I was expecting this to exist at Godot 4 directory. Which also matches Godot 3 structure that already exists.

### CODE REVIEW

**Comment by wegank** [comment]
Nice! I was having a [source-built](https://github.com/wegank/nur-packages/blob/main/pkgs/by-name/go/godot_4-export-templates/package.nix) `godot_4-export-templates` on my side, which is by no means universal...

**Comment by wegank** [comment]
`godot_4-export-templates` has to be moved to pkgs/by-name, however...

**Comment by ulrikstrid** [comment]
Result of `nixpkgs-review pr 305118` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>godot_4</li>
    <li>godot_4-export-templates</li>
    <li>godot_4.man</li>
  </ul>
</details>

**Review by ulrikstrid — APPROVED** [review]
I recall reading somewhere that packaging the export templates was problematic, but I can't find it anymore so I think this is good to go.

**Pull request merged**
