### PR TITLE
Mpd

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
What's the reasoning before new option handling? Ends up in more noise in `all-packages.nix`.

**Comment by ehmry** [comment]
I thought it was confusing that there were defaults on package arguments and in callPackage, and that not all the options were available through 'config.mpd'.

It is more noise, but the default arg function could be generalised so that its not package specific. Part of it is I am interested in using the config argument to nixpkgs more, which I don't see documented.

**Comment by ehmry** [comment]
Perhaps I should close this and create an issue on general package config handling.

**Comment by Fuuzetsu** [comment]
Well, I'd still like to see the version update and the opus + proxy support :)

**Comment by ehmry** [comment]
https://github.com/NixOS/nixpkgs/issues/7446

**Pull request closed without merging**
