### PR TITLE
Additional vim plugin names

### PR DESCRIPTION
**Pull request by paulreimer**
###### Motivation for this change
- `vim-plugin-names` should be sorted (resolved that before adding anything)
- Added some vim plugins that I personally use for development

###### Things done

Not much. Various new plugins appear to be working as they normally do.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
the history is a mess, please see how similar PRs did it. When adding a plugin, the commit should be `vimPlugins.<name>: init at X.Y` so that nixos' bot can pickup some of the changes.

**Comment by paulreimer** [comment]
Should each commit introducing a new plugin include the (re)generated `generated.nix`? Or separate commits?

**Comment by kalbasit** [comment]
> Should each commit introducing a new plugin include the (re)generated `generated.nix`? Or separate commits?

It should include the `generated.nix` file.

**Comment by teto** [comment]
well Ideally you would `git add -p` the added plugin and have the updates for already existing plugins in a separate commit.
To sum up:
1/ a commit that updates existing plugins
2/ a list of commits with each commit adding the plugin: vimPlugins.<NAME>: init at X.Y

**Comment by paulreimer** [comment]
Alright, I've cleaned up the history for the plugins that I added.

So how should I clean up the history for the alphabetization/plugin renaming (which triggered some upgrades from `update.py`)? I can split it up into one commit per (alphabetized) change if that is what is needed for CI.

**Comment by teto** [comment]
Thanks the history looks good as is. 

@GrahamcOfBorg build vimPlugins.vim-flutter vimPlugins.deoplete-lsp vimPlugins.LanguageClient-neovim vimPlugins.deoplete-jedi

**Review by teto — APPROVED** [review]

**Comment by kalbasit** [comment]
@GrahamcOfBorg build vimPlugins.LanguageClient-neovim vimPlugins.file-line vimPlugins.vim-sourcetrail vimPlugins.dart-vim-plugin vimPlugins.vim-textobj-comment vimPlugins.vim-textobj-function vimPlugins.vim-textobj-user vimPlugins.lh-brackets vimPlugins.lh-vim-lib vimPlugins.lightline-ale vimPlugins.sky-color-clock-vim vimPlugins.vim-bufkill vimPlugins.deoplete-lsp vimPlugins.vim-flutter vimPlugins.tcomment_vim vimPlugins.ir_black vimPlugins.DoxygenToolkit-vim

**Pull request merged**
