### PR TITLE
vimPlugins.nvim-treesitter: tree-sitter-smali: init at v0.0.2

### PR DESCRIPTION
**Pull request by ToyVo**
###### Description of changes

update the vim plugin tree-sitter-smali, the existing tarball referenced is no longer available https://github.com/amaanq/tree-sitter-smali/issues/1

###### Things done
ran a darwin rebuild on my dotfiles flake pointed to my branch for nixpkgs

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
please update nvim-treesitter directly instead, this file is generated from nvim-treesitter's lock file. You can update all vim plugins with `pkgs/applications/editors/vim/plugins/update.py` (which can potentially cause other breakages), or manually update only nvim-treesitter [here](https://github.com/NixOS/nixpkgs/blob/af735e7623db2c72d5aa506bcef19fbb946f2b5e/pkgs/applications/editors/vim/plugins/generated.nix#L6480) and run `pkgs/applications/editors/vim/plugins/nvim-treesitter/update.py`

**Comment by ToyVo** [comment]
Ah, sorry was new and did not realize that, I'll pivot to that

**Comment by amaanq** [comment]
ty!

**Comment by ToyVo** [comment]
Huh I cant run the script because there is a 404 at https://github.com/VundleVim/Vundle.vim, I wonder whats going on over there

**Comment by ToyVo** [comment]
https://github.com/community/community/discussions/48173

**Comment by figsoda** [comment]
Related: https://github.com/community/community/discussions/48173

We can go with the alternative solution:

> manually update only nvim-treesitter [here](https://github.com/NixOS/nixpkgs/blob/af735e7623db2c72d5aa506bcef19fbb946f2b5e/pkgs/applications/editors/vim/plugins/generated.nix#L6480) and run `pkgs/applications/editors/vim/plugins/nvim-treesitter/update.py`

I can do that in a new PR if you want help

**Comment by ToyVo** [comment]
Yes please, I do not have the knowledge, I was just trying to fix a local issue

**Comment by figsoda** [comment]
#217799, upstream seems to be using a different [repository](https://git.sr.ht/~yotam/tree-sitter-smali) which is probably why CI was previously failing:

> ..gin-nvim-treesitter-2023-02-19/scripts/check-queries.lua:96: smali (highlights): ...ed-0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 120 for language smali

**Comment by amaanq** [comment]
yeah, smali changed repos recently

**Pull request closed without merging**
