### PR TITLE
gnome-passwordsafe: rename to gnome-secrets, 5.1 -> 6.1

### PR DESCRIPTION
**Pull request by onny**
###### Motivation for this change
Update package to version 6.0 and rename it to gnome-secrets according to upstream changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mvnetbiz** [comment]
Seems to work. I think you should add an entry to pkgs/top-level/aliases.nix, otherwise looks good to me.

**Comment by mvnetbiz** [comment]
There is a 6.1 release with a few bug fixes.

**Comment by onny** [comment]
Cool thank you, fixed it :)

**Comment by bobby285271** [comment]
Please remove `libhandy` from args and buildInputs, and try to use `wrapGAppsHook4` if possible (maybe `substituteInPlace meson_post_install.py --replace "gtk-update-icon-cache" "gtk4-update-icon-cache"` and submit a upstream merge request if necessary).

It will be even nicer to fix the double wrapping :-)

**Comment by onny** [comment]
Thank you @bobby285271 for reviewing. Hope I could fix all the issues but it seems to build and run fine now :)

**Review by bobby285271 — APPROVED** [review]
Not very sure if we need release notes, the package update looks good. builds and launches (The commit message is wrong and needs squash merge, it should be 5.1 -> 6.1).

(Seems that we are going to bring more merge conflicts to staging-next https://github.com/NixOS/nixpkgs/pull/158080#issuecomment-1029686621 :crying_cat_face: )

**Comment by bobby285271** [comment]
@ofborg build gnome-secrets

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 157314` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gnome-secrets</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Changes look good

Builds, works

Tested with existing KeePass DBX.

**Comment by hilaolu** [comment]
Hi, I am new to nix and just migrated from ArchLinux. I just switch from 21.11 to unstable. Secrets works well on 21.11, but it doesn't work under unstable on my machine.

### Steps To Reproduce
Steps to reproduce the behavior:
1. nix-env -iA nixos.gnome-secrets
2. secrets

```
Traceback (most recent call last):
  File "/nix/store/dzf7wmrx3xf7lklbcz35znn9jmjwazxb-gnome-secrets-6.1/bin/.secrets-wrapped", line 67, in <module>
    main()
  File "/nix/store/dzf7wmrx3xf7lklbcz35znn9jmjwazxb-gnome-secrets-6.1/bin/.secrets-wrapped", line 58, in main
    from gsecrets.application import Application
  File "/nix/store/dzf7wmrx3xf7lklbcz35znn9jmjwazxb-gnome-secrets-6.1/lib/python3.9/site-packages/gsecrets/application.py", line 11, in <module>
    from gsecrets.widgets.window import Window
  File "/nix/store/dzf7wmrx3xf7lklbcz35znn9jmjwazxb-gnome-secrets-6.1/lib/python3.9/site-packages/gsecrets/widgets/window.py", line 13, in <module>
    from gsecrets.database_manager import DatabaseManager
  File "/nix/store/dzf7wmrx3xf7lklbcz35znn9jmjwazxb-gnome-secrets-6.1/lib/python3.9/site-packages/gsecrets/database_manager.py", line 9, in <module>
    from pykeepass import PyKeePass
  File "/nix/store/1wlapwnmlz4d54mf93ly07k5sqk1q6b1-python3.9-pykeepass-4.0.1/lib/python3.9/site-packages/pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass, create_database
  File "/nix/store/1wlapwnmlz4d54mf93ly07k5sqk1q6b1-python3.9-pykeepass-4.0.1/lib/python3.9/site-packages/pykeepass/pykeepass.py", line 23, in <module>
    from pykeepass.kdbx_parsing.kdbx import KDBX
  File "/nix/store/1wlapwnmlz4d54mf93ly07k5sqk1q6b1-python3.9-pykeepass-4.0.1/lib/python3.9/site-packages/pykeepass/kdbx_parsing/__init__.py", line 1, in <module>
    from .kdbx import KDBX
  File "/nix/store/1wlapwnmlz4d54mf93ly07k5sqk1q6b1-python3.9-pykeepass-4.0.1/lib/python3.9/site-packages/pykeepass/kdbx_parsing/kdbx.py", line 4, in <module>
    from .kdbx4 import DynamicHeader as DynamicHeader4
  File "/nix/store/1wlapwnmlz4d54mf93ly07k5sqk1q6b1-python3.9-pykeepass-4.0.1/lib/python3.9/site-packages/pykeepass/kdbx_parsing/kdbx4.py", line 6, in <module>
    import argon2
  File "/nix/store/q9p9a13ysp9b8h2yvvcbk0r11v7pvjh3-python3.9-argon2_cffi-21.3.0/lib/python3.9/site-packages/argon2/__init__.py", line 7, in <module>
    from . import exceptions, low_level, profiles
  File "/nix/store/q9p9a13ysp9b8h2yvvcbk0r11v7pvjh3-python3.9-argon2_cffi-21.3.0/lib/python3.9/site-packages/argon2/low_level.py", line 15, in <module>
    from _argon2_cffi_bindings import ffi, lib
ModuleNotFoundError: No module named '_argon2_cffi_bindings'
```

The missing module should have been installed correctly.
```
nix-store -q --references /nix/store/dzf7wmrx3xf7lklbcz35znn9jmjwazxb-gnome-secrets-6.1
/nix/store/4nmqxajzaf60yjribkgvj5j54x9yvr1r-bash-5.1-p12
/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10
/nix/store/06gid39q7h28p1pkvyacczrl6zqbv1cn-python3.9-pycairo-1.20.1
/nix/store/2g610c5xqvikdixylipz01cymp1yb7j4-gdk-pixbuf-2.42.6
/nix/store/nw2gv9l8lzi4scbddbg1vfvivzcpvag3-harfbuzz-3.2.0
/nix/store/s4agfw48asi7n81ajh12l6ghqr7fm9ph-pango-1.50.3
/nix/store/0ccn204v5kds9i08x7plf4x644l6wm87-librsvg-2.52.5
/nix/store/2sqy5gygqi0y49lyvzqch00zs4gmihq4-gettext-0.21
/nix/store/ld9abqmqdghijy10gj8a8rxil2c1lw76-glib-2.70.2-bin
/nix/store/11fs0i9fmfd23vzdgsypfa1csx7rg9kx-glib-2.70.2-dev
/nix/store/2m3rh1fpp2kv4ni96l2n2lgri3rczbk8-python3.9-lxml-4.7.1
/nix/store/88bzhqcsw1qjjm8f40qn1amwm2hmc8h4-python3.9-future-0.18.2
/nix/store/ps5i9522xbad2hv1pzipbz5nbmdkw7lm-python3.9-python-lz4-3.1.12
/nix/store/hd6gvk7nmaw56x66qalwixyh6x6a2jnn-python3.9-construct-2.10.67
/nix/store/hgv0jw22pqy2208d502ljir470pfzlzp-python3.9-pycryptodomex-3.12.0
/nix/store/qd8x2fppvsd9fyk06l359fgi8y4wl0hg-python3.9-six-1.16.0
/nix/store/q9p9a13ysp9b8h2yvvcbk0r11v7pvjh3-python3.9-argon2_cffi-21.3.0
/nix/store/smsd18b7wlsix88dp5hi19cic3d7jb2i-python3.9-python-dateutil-2.8.2
/nix/store/1wlapwnmlz4d54mf93ly07k5sqk1q6b1-python3.9-pykeepass-4.0.1
/nix/store/2anfhzjz6d4n5xx5k5bfc9png6bjxis6-dconf-0.40.0-lib
/nix/store/2kmcrqxy3mw6fhb0sxhky7ci1lg6n22i-expat-2.4.4-dev
/nix/store/7abbl94528ka9xnc3z13vkzvrz4d9678-gobject-introspection-1.70.0
/nix/store/liiwmfbw7rad97cn1hadl5igldnqqxhw-libpng-apng-1.6.37-dev
/nix/store/chwa4ksvdd0adcjghvrafmj1wps76zym-freetype-2.11.1-dev
/nix/store/9d97ngq7sy9mak60gyacc47fp76djjwp-cairo-1.16.0-dev
/nix/store/cc7zlvfsykq0sq3gvs5cvxbga2d181a1-appstream-glib-0.7.18
/nix/store/civp2i2znh80127yx3ic8q1xrwx9jjsr-bzip2-1.0.6.0.2-bin
/nix/store/dqj13hw9rjpi98n9x43awmbfh6gqvxf2-python3.9-pyotp-2.6.0
/nix/store/fa1g725y2kp47zwdxjdkb9cvcavvpc3d-fontconfig-2.13.94-bin
/nix/store/h96is7nx77hifvfilvkcndh8ic3qlk76-python3.9-pygobject-3.42.0
/nix/store/i7c9frxf2gqgx5fcgnsa4fxb0x9v23dr-python3.9-pygobject-3.42.0-dev
/nix/store/kn83mgxdlbv56rk4whv8ns7w7b2h5mw8-python3.9-cffi-1.15.0
/nix/store/nb8h4pd7j7mza8cxyhb37l1z06yyb155-graphene-1.10.6
/nix/store/n9v7sviqj7fm0yhr6dig8n0lfpgpnww9-gtk4-4.6.1
/nix/store/psmby2cfmhafcly52kcfid1k2cjbv9n5-gsettings-desktop-schemas-41.0
/nix/store/qd1i3c2h4cv8lyqkg87fgncydysdsr34-libpwquality-1.4.2
/nix/store/vk3b2g1l7fdw9ii9d2zgb4kgn8h554q6-python3.9-pycparser-2.21
/nix/store/wa5jfadni87z8hpdwy5g80y4kih25q4k-libadwaita-1.0.2
/nix/store/dzf7wmrx3xf7lklbcz35znn9jmjwazxb-gnome-secrets-6.1
```



### Expected behavior
The gnome-secrets window appears. 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.


```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/xsgq8c5pg6lpjils5qvg67crrv6sy247-bash-interactive-5.1-p12-dev
copying path '/nix/store/xsgq8c5pg6lpjils5qvg67crrv6sy247-bash-interactive-5.1-p12-dev' from 'https://mirrors.ustc.edu.cn/nix-channels/store'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.28, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - channels(hilaolu): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bobby285271** [comment]
I think this is broke by Python unstable 2022-01-13 https://github.com/Nixos/nixpkgs/commit/986559bac000f79d1897fe9cbd95225ad8a19417, which introduced the change of https://github.com/hynek/argon2-cffi/releases/tag/21.2.0. Maybe argon2_cffi needs to propagate argon2-cffi-bindings.

**Comment by bobby285271** [comment]
#161248 should fixed this

**Pull request merged**
