### PR TITLE
ladybird: update homepage link

### PR DESCRIPTION
**Pull request by nikita-skakun**
This is a small change updating the homepage link for the Ladybird browser. If you navigate to the previous link, it would redirect you to the new website on the .org domain.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Frontear** [comment]
Hi! Congrats on your first PR!

One small change: please reformat the commit to follow the guidelines in CONTRIBUTING.md

**Review by SigmaSquadron — APPROVED** [review]

**Comment by Frontear** [comment]
I should have probably clarified that I meant the commit itself 😅, not the pr title

**Comment by nikita-skakun** [comment]
@Frontear  How do I update the commit message? Git is something I'm still trying to figure out.

**Comment by Frontear** [comment]
No worries! Since this was only one commit you can just do `git commit --amend` and update the title there, then `git push --force` to have it update here.

**Comment by nikita-skakun** [comment]
Sorry it took so long, first time doing this and wanted to make sure I'm not screwing something up by accident.

**Review by Frontear — APPROVED** [review]

**Comment by Frontear** [comment]
> Sorry it took so long, first time doing this and wanted to make sure I'm not screwing something up by accident.

No worries, welcome to nixpkgs and good job on your first pr!

**Review by honnip — APPROVED** [review]

**Review by tomodachi94 — APPROVED** [review]
Lgtm. Old URL redirects to the new one, and the new URL is referenced in the upstream repository that we use.

**Comment by tomodachi94** [comment]
Merging as trivial, but pinging @fgaz so they know this change occurred.

**Pull request merged**
