### PR TITLE
qt-6/modules/qtbase: add systemdSupport parameter

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

Defaults to `stdenv.isLinux`.  Tested by building `ladybird` with `.override { systemdSupport = false; }`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`: `ladybird`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by NickCao — APPROVED** [review]

**Comment by NickCao** [comment]
Should systemd also be removed from buildInputs when systemdSupport is disabled?

**Comment by amjoseph-nixpkgs** [comment]
> Should systemd also be removed from buildInputs when systemdSupport is disabled?

Yes thank you; I didn't notice that because I have to `.override { systemd=null; }` due to there being a few packages that still don't respect `systemdSupport`.

**Comment by NickCao** [comment]
Notice that udev is also systemd under the hood, better check if that matters.

**Comment by amjoseph-nixpkgs** [comment]
> Notice that udev is also systemd under the hood, better check if that matters.

Ah yes, I keep forgetting about that.  Such a footgun.  Why can't we just call `udev` `udev` anymore...

**Comment by amjoseph-nixpkgs** [comment]
> Notice that udev is also systemd under the hood, better check if that matters.

Fortunately it does not matter in this case.

**Comment by amjoseph-nixpkgs** [comment]
Ping

**Review by NickCao — APPROVED** [review]

**Comment by amjoseph-nixpkgs** [comment]
Resolved merge conflict.

**Review by NickCao — APPROVED** [review]

**Comment by Artturin** [comment]
> > Notice that udev is also systemd under the hood, better check if that matters.
> 
> Ah yes, I keep forgetting about that. Such a footgun. Why can't we just call `udev` `udev` anymore...

because udev was merged in to systemd in 2012

**Comment by amjoseph-nixpkgs** [comment]
> because udev was merged in to systemd in 2012

We refer to:

- both `gcc` and `clang` as `stdenv.cc`
- both `glibc` and `musl` as `libc`
- both `openjdk` and `` as `jdk`
- both `binutils` and `somedarwinthing` as `bintools`
- both `npth` and `gnupth` as `pth`
- both `bash` and `busybox` as `stdenv.shell`

We really ought to have a top-level `udev` which defaults to `systemd`.  Or if it's a branding thing call it `xdev` instead.

There are at least two non-`systemd` packages that provide `udev` implementations.

**Comment by NickCao** [comment]
Calling udev is fine. Selecting different implementations conditionally is being implemented: https://github.com/NixOS/nixpkgs/pull/210276

**Comment by amjoseph-nixpkgs** [comment]
> Selecting different implementations conditionally is being implemented: #210276

Hooray!

**Pull request merged**
