### PR TITLE
syncthing: 1.0.1 -> 1.1.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
Closes https://github.com/NixOS/nixpkgs/issues/57170

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bachp** [comment]
I get:

```
hash mismatch in fixed-output derivation '/nix/store/ir6mad47zs8kh3h1r3vdfkiq7b6w75d6-geoip2-golang':
  wanted: sha256:0v698bzs8lb59cqpsa9cf4sl8rdsvnnmaravhbfn6g6i511ppclr
  got:    sha256:10pvjmbm1wc8xxwqlcfhdj2mciiyfddghmp6jyn7brd4mg65ppy2
```

**Review by xeji — CHANGES_REQUESTED** [review]
Update deps.nix to fix hash mismatches

**Comment by marsam** [comment]
that is odd, I get the same hashes with nix-prefetch-git
```
$ nix-prefetch-git https://github.com/oschwald/geoip2-golang --rev v1.1.0 2>/dev/null
{
  "url": "https://github.com/oschwald/geoip2-golang",
  "rev": "5b1dc16861f81d05d9836bb21c2d0d65282fc0b8",
  "date": "2017-04-23T14:58:58-07:00",
  "sha256": "0v698bzs8lb59cqpsa9cf4sl8rdsvnnmaravhbfn6g6i511ppclr",
  "fetchSubmodules": false
}
```
```
$ nix-prefetch-git https://github.com/oschwald/maxminddb-golang --rev 26fe5ace1c70 2>/dev/null
{
  "url": "https://github.com/oschwald/maxminddb-golang",
  "rev": "26fe5ace1c706491c2936119e1dc69c1a9c04d7f",
  "date": "2017-09-01T06:40:56-07:00",
  "sha256": "1i6d935f3cv9djpjvc2ibh8aps8jqvg454b9pkwg2h98al759ggk",
  "fetchSubmodules": false
}
```

**Comment by xeji** [comment]
I ran `nix-build ~/nixpkgs -A syncthing` on my local checkout of this PR branch as usual without prefetching, and got the same hash mismatches as @bachp.  x86_64-linux here.

I recall seeing similar issues in the past which turned out to be caused by differences of macOS vs linux file systems (case-sensitive vs. non-case-sensitive).  Could this be the cause here? If you have access to both a mac and a linux box you can have a look...

**Comment by marsam** [comment]
Fixed. it happened because vgo2nix called nix-prefetch-git without the `--fetch-submodules` flag https://github.com/adisbladis/vgo2nix/commit/c3cf0554e9c6b721097276c09d0b416b50ae5650

**Comment by xeji** [comment]
Thank you!
@GrahamcOfBorg build syncthing

**Review by xeji — APPROVED** [review]

**Pull request merged**
