### PR TITLE
k3s_1_30: init 1.30.0+k3s1

### PR DESCRIPTION
**Pull request by superherointj**
Release: https://github.com/k3s-io/k3s/releases/tag/v1.30.0%2Bk3s1

Notes:
* I won't be bumping default `k3s` to `k3s_1_30` until it has been properly tested or at least 1-2 weeks have passed by.

CC @euank @Mic92 @wrmilling @yajo

Note: I will get back to this when I have the time. If someone wants to solve this earlier feel free. Sorry about the delay.

### CODE REVIEW

**Comment by superherointj** [comment]
@ofborg build k3s_1_30.passthru.tests.{etcd,single-node,multi-node}

**Comment by superherointj** [comment]
@ofborg build k3s_1_30.passthru.tests.{etcd,single-node,multi-node}

**Comment by wrmilling** [comment]
`etcd` and `single-node` test suites run fine, but getting an error on the `multi-node` test suite: 

```
 last 10 log lines:
       >     driver.run_tests()
       >   File "/nix/store/8xh4acg60sjkaj4mfdd2fncawd9grjw2-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 163, in run_tests
       >     self.test_script()
       >   File "/nix/store/8xh4acg60sjkaj4mfdd2fncawd9grjw2-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 155, in test_script
       >     exec(self.tests, symbols, None)
       >   File "<string>", line 15, in <module>
       >   File "/nix/store/8xh4acg60sjkaj4mfdd2fncawd9grjw2-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 609, in succeed
       >     raise Exception(f"command `{command}` failed (exit code {status})")
       > Exception: command `/nix/store/z5y5j0p5hfm38svsh1rgwkj48wfm54ck-stream-pause | k3s ctr image import -` failed (exit code 1)
       > kill vlan (pid 7)
       For full logs, run 'nix log /nix/store/8z6856n748yhb5z5zmy66d0s2nmla75v-vm-test-run-k3s-1.30.0+k3s1-multi-node.drv'.
```

Packages otherwise build fine on x86_64 and aarch64.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 310692` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>k3s_1_30</li>
  </ul>
</details>

**Comment by superherointj** [comment]
@ofborg build k3s_1_30.passthru.tests.etcd k3s_1_30.passthru.tests.single-node k3s_1_30.passthru.tests.multi-node

**Comment by wrmilling** [comment]
Result of `nixpkgs-review pr 310692` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>k3s_1_30</li>
  </ul>
</details>

Result of `nixpkgs-review pr 310692` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>k3s_1_30</li>
  </ul>
</details>

Test seem to be happy now as well, `etcd`, `singe-node`, and `multi-node`.

**Comment by superherointj** [comment]
I also don't see any failure. As this is a new package version, and we are not bumping the latest tag for the moment. I think we should go ahead with this. I'm just waiting for someone to approve this. So we can proceed.

**Review by euank — APPROVED** [review]
The tests pass for me too, and it seems correct to me!

Thanks!

**Review by wrmilling — APPROVED** [review]
LGTM

**Pull request merged**
