### PR TITLE
Python: Add overrideAttrs attribute aliasing overridePythonAttrs

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
This will make lib.makeOverridable use overridePythonAttrs by default.

Overriding Python packages has some surprising properties unless you use `overridePythonAttrs` and it can be incredibly frustrating to try and find out why that is.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adisbladis** [comment]
@FRidh What kind of tests do you have in mind?

**Comment by FRidh** [comment]
Testing that `buildPythonPackage` is indeed invoked again. One way to assert this is by adding to `propagatedBuildInputs` and testing it has an affect on `requiredPythonModules`, which serves as input to `python.buildEnv`.

**Comment by FRidh** [comment]
cc @alyssais because of https://github.com/NixOS/nixpkgs/pull/46842.

**Comment by adisbladis** [comment]
@FRidh I added a test. Since it's not actually building anything but only asserts attributes I made a new type of test.

**Comment by FRidh** [comment]
@GrahamcOfBorg build python2.tests python3.tests python38.tests

**Comment by FRidh** [comment]
@grahamcofborg build pypy2.tests pypy3.tests

**Review by FRidh — APPROVED** [review]

**Comment by FRidh** [comment]
Let's wait a bit with merging this.

**Comment by alyssais** [comment]
@FRidh yiu don’t think this needs an RFC any more?

**Comment by FRidh** [comment]
Right, I wrote that. I do think it is best we standardize interfaces like these and I see you asked matthewbauer at the time to help with it. Let's write a small RFC and see where that takes us.

**Comment by FRidh** [comment]
RFC proposal https://github.com/NixOS/nixpkgs/pull/46842#issuecomment-600029672

**Review by jonringer — APPROVED** [review]

**Comment by adisbladis** [comment]
Closing, see https://github.com/NixOS/rfcs/pull/67.

**Pull request closed without merging**
