### PR TITLE
 dosbox: use desktopItems machinery;  munt: 2.5.0 -> 2.5.3

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Motivation for this change

- dosbox: use desktopItems machinery

- munt: 2.5.0 -> 2.5.3

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mohe2015** [comment]
@AndersonTorres Please use a better title in the future, at least like `munt: update, dosbox: cleanup` so it's easier to see in the notifications what this is about.

**Comment by AndersonTorres** [comment]
> @AndersonTorres Please use a better title in the future, at least like `munt: update, dosbox: cleanup` so it's easier to see in the notifications what this is about.

Sorry, I forgot that.
However the commit message is complete.

**Comment by OPNA2608** [comment]
I don't think libmt32emu corresponds to the entirety of "Munt", that's why I made it use the `munt_*` tags instead. We could look into splitting up every subproject into its own subpackage since all of them use a different version number & have their own releases, but I think this bump is not correct as-is?

**Comment by AndersonTorres** [comment]
Hum, it explains the confusing webpage.

I was updating dosbox-staging to newest version and it required a new munt package. So I upgraded it.

(OTOH now dosbox-staging does not compile because it fails to find SDL...)

**Comment by OPNA2608** [comment]
All subprojects have their own versions and the subproject releases don't always have the latest code for all the other projects.

For example, this "bump" from `munt_2_5_0` to `libmt32emu_2_5_3` has

- upgraded mt32emu from 2.5.1 (not 2.5.0!) -> 2.5.3
- downgraded the internal munt version from 2.5.0 -> 2.4.0
- downgraded mt32emu_qt from 1.9.0 -> 1.8.0 + WIP changes
- downgraded mt32emu_win32drv from 1.7.0 -> 1.6.0 (we don't build this but that's besides the point)

https://github.com/munt/munt/compare/munt_2_5_0..libmt32emu_2_5_3

**Pull request merged**
