### PR TITLE
libtiff: 4.2.0 -> 4.3.0; adopt

### PR DESCRIPTION
**Pull request by alyssais**
Tested by viewing a TIFF file in imv.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
mmh, this seems to break cross-compilation for libtiff.

<details><summary>build log</summary>

```
[ 34%] Linking C shared library libtiff.so
/nix/store/xha8y6kl52riwlbn866ac7np208iysdn-aarch64-unknown-linux-gnu-binutils-2.35.1/bin/aarch64-unknown-linux-gnu-ld: skipping incompatible /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libm.so.6 when searching for /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libm.so.6
/nix/store/xha8y6kl52riwlbn866ac7np208iysdn-aarch64-unknown-linux-gnu-binutils-2.35.1/bin/aarch64-unknown-linux-gnu-ld: cannot find /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libm.so.6
/nix/store/xha8y6kl52riwlbn866ac7np208iysdn-aarch64-unknown-linux-gnu-binutils-2.35.1/bin/aarch64-unknown-linux-gnu-ld: skipping incompatible /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libm.so.6 when searching for /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libm.so.6
/nix/store/xha8y6kl52riwlbn866ac7np208iysdn-aarch64-unknown-linux-gnu-binutils-2.35.1/bin/aarch64-unknown-linux-gnu-ld: skipping incompatible /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libmvec.so.1 when searching for /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libmvec.so.1
/nix/store/xha8y6kl52riwlbn866ac7np208iysdn-aarch64-unknown-linux-gnu-binutils-2.35.1/bin/aarch64-unknown-linux-gnu-ld: cannot find /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libmvec.so.1
/nix/store/xha8y6kl52riwlbn866ac7np208iysdn-aarch64-unknown-linux-gnu-binutils-2.35.1/bin/aarch64-unknown-linux-gnu-ld: skipping incompatible /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libmvec.so.1 when searching for /nix/store/harm95yj7ag3jrr3chrwyl8kagmplssc-glibc-2.33-45/lib/libmvec.so.1
collect2: error: ld returned 1 exit status
make[2]: *** [libtiff/CMakeFiles/tiff.dir/build.make:723: libtiff/libtiff.so.5.7.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:535: libtiff/CMakeFiles/tiff.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

</details>

Not sure why that is the case though.

(note that I don't want to block on cross-compilation failures, but it's good to keep in mind).

**Comment by alyssais** [comment]
[ffdad3129fb352fc5f7075fe1ff2acee90da90ae](https://gitlab.com/libtiff/libtiff/-/commit/ffdad3129fb352fc5f7075fe1ff2acee90da90ae) is the first bad commit.

**Comment by alyssais** [comment]
Very tempting to just switch back to using autoconf for this package, which does seem to be the recommend method upstream (it's what's mentioned in the README). cc @L-as

**Comment by L-as** [comment]
You'd need to fix headers.patch to make it compatible with autoconf.

**Comment by alyssais** [comment]
Do you expect that to be particularly hard?  In 96d50327bc590822210fae445fa6f3261a8f4642 you say

> This also switches to cmake to simplify the patch.

But I'm curious why it would be simpler with CMake than autotools?

**Comment by L-as** [comment]
Because my brain doesn't work with autoconf.

**Comment by alyssais** [comment]
Switched back to autoconf; tested that freeimage still builds.

**Review by L-as — APPROVED** [review]
LGTM

**Comment by Mindavi** [comment]
Thanks for thinking of cross-compilation :heart:

**Comment by vcunat** [comment]
libtiff regressed on aarch64-darwin: https://hydra.nixos.org/build/147843844

**Comment by vcunat** [comment]
It's hard to do this without an access to a builder for that platform, so I just made it use expression before this PR.  (in commit 07b9fef4703)  Hopefully someone will be able to clean it up later.

**Pull request merged**
