### PR TITLE
plasma-5: 5.15.2 -> 5.15.3

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://kde.org/announcements/plasma-5.15.3.php

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
cc @nyanloutre @bkchr

**Comment by nyanloutre** [comment]
I spotted 5.15.3.2 version for the ones you already updated to 5.15.3.1

**Comment by dtzWill** [comment]
D'oh, hopefully this settles soon...

The 5.15.3.2 updates don't seem to have a mailing list post,
wonder what's going on? :)

**Comment by bkchr** [comment]
What blocks this?

**Comment by dtzWill** [comment]
Nothing, AFAIK! Let's give it a go..

**Comment by vandenoever** [comment]
How long generally before a change in staging goes into master?

**Comment by nyanloutre** [comment]
Also there will probably be a conflict when merging staging and master because of this : #56155

**Comment by vandenoever** [comment]
Would be a shame if the next stable NixOS would not have Plasma 5.15.

**Comment by bkchr** [comment]
I don't understand why is was merged into `staging` at all. We never merged plasma stuff before in staging.

**Comment by dtzWill** [comment]
5.15.4 for whoever wants to run the script.  https://github.com/dtzWill/nixpkgs/commit/d4756c9bfa3d3e790d1847396a4242825d3c2352 if you'd like :heart:.  Sorry about possibly wrong call re:sending to staging.

**Comment by dtzWill** [comment]
5.15.5 for the interested: https://github.com/dtzWill/nixpkgs/commit/3984ac25e8821207e43d1c06a10327c6da9a0a37

(mechanical, but may not work with the update script for another day or however long)

**Pull request merged**
