### PR TITLE
gitkraken: 7.4.1 -> 7.5.0

### PR DESCRIPTION
**Pull request by rhoriguchi**
###### Motivation for this change

GitKraken version [7.5.0](https://support.gitkraken.com/release-notes/current/#version-750) has been released.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by dbirks — APPROVED** [review]
Built and ran on NixOS. Looks good :+1:

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110561` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>gitkraken</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

gitkraken:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern '/nix/store/cyfdlhp29i2mwngz978aqqxdb8xhi43p-gitkraken-7.5.0/usr/share/gitkraken' doesn't match anything in file '/nix/store/cyfdlhp29i2mwngz978aqqxdb8xhi43p-gitkraken-7.5.0/share/applications/gitkraken.desktop'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>

**Comment by rhoriguchi** [comment]
@SuperSandro2000 is [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/gitkraken/default.nix#L93-L94) even needed, the [desktop file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/gitkraken/default.nix#L68-L76) is created manually so there's not really a reason to substitute it?

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 is [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/gitkraken/default.nix?rgh-link-date=2021-01-23T19%3A38%3A09Z#L93-L94) even needed? The [desktop file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/gitkraken/default.nix?rgh-link-date=2021-01-23T19%3A38%3A09Z#L68-L76) is created manually so there's not really a reason to substitute it.

Does not look like it but I am not 100% sure.

**Comment by rhoriguchi** [comment]
> Does not look like it but I am not 100% sure.

After going through a couple of derivations that use `makeDesktopItem` I don't think it isn't necessary. [Example](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/munt/default.nix#L4)

**Comment by evanjs** [comment]
> > Does not look like it but I am not 100% sure.
> 
> After going through a couple of derivations that use `makeDesktopItem` I don't think it isn't necessary. [Example](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/munt/default.nix#L4)
> 
> Edit: Error is gone
> 
> ```
> 1 package built:
> gitkraken
> ```

Yeah, probably an artifact from some other changes that was overlooked. Thanks for checking it out!

**Review by evanjs — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110561` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>gitkraken</li>
</ul>
</details>

**Pull request merged**
