### PR TITLE
iruby: init at 0.3.0

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

iruby kernel for jupyter

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by costrouc** [comment]
Result of `nixpkgs-review pr 94947` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- iruby
</details>

**Comment by costrouc** [comment]
@GrahamcOfBorg build iruby

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 94947 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  - iruby</details>

**Comment by jonringer** [comment]
I'm not a big fan of large deps.nix, but not familiar with a better way

**Comment by costrouc** [comment]
Yeah neither am I. It would be nice if it worked the same way that R and python packages do. But I'm guessing that that is only necessary as the number of packages in the language increases.

**Comment by jonringer** [comment]
I'm not familiar with R, but python packages usually need some "elbow" grease for them to work as a semi-coherent package set.

However, it does enable python packages to not need mutually exclusive deps trees to work.

**Pull request merged**
