### PR TITLE
r-modules: update CRAN, add Bioconductor data packages

### PR DESCRIPTION
**Pull request by jefdaj**
The main change is I added the Bioconductor Annotation and Experiment data repositories. Many of the currently "broken" Bioconductor packages just depend on them, so they can be un-broken soon!

I'm also writing a big shell script (see [here](https://gist.github.com/jefdaj/613bc2fca9a140159263) for current version) that will help test builds of the individual packages and mark them as broken/unbroken, but I think it's cleaner if I put that in a different PR once it's ready. For now, I just checked that rPackages evaluates using `nix-build test-evaluation.nix --dry-run`, and removed a few old packages from `default.nix` that were preventing it.

I also tweaked `generate-r-packages.R` to download using `wget` instead of `nix-prefetch-url` and removed the "s" in some `https://` repository urls because they were causing errors. If that's just my machine though, feel free to remove those changes!

### CODE REVIEW

**Comment by jefdaj** [comment]
Oh, this is a saner subset of all the changes I tried to do at once [here](https://github.com/NixOS/nixpkgs/pull/12145).

**Comment by jagajaga** [comment]
cc @peri

**Comment by jagajaga** [comment]
cc @peti

**Comment by peti** [comment]
This update generates approx. 1300 evaluation errors in http://hydra.cryp.to/jobset/nixpkgs/r-updates.

**Comment by peti** [comment]
jm mmmmmmm m

**Comment by peti** [comment]
Sorry, I didn't mean to close this ... wrong button.

**Comment by jefdaj** [comment]
Looks like they're all of the form "Package ‘r-packagename’ in ‘/nix/store...’ is marked as broken, refusing to evaluate."? I'll see how many I can get rid of. A lot may just depend on a few of the base Bioconductor packages like `Biostrings`. How do I test whether each package will evaluate? So far I've just been testing whether they build successfully but that takes a lot longer so I haven't done the whole set.

**Comment by peti** [comment]
I don't know whether there is an easy way to test evaluation the way Hydra does without actually installing Hydra.

**Comment by jefdaj** [comment]
That's OK, long as I'm not missing something simple. I'll start my script building all of them and see if it takes a long time or if it finds a few broken dependencies in common.

**Comment by peti** [comment]
If if doubt, then just push a new version and ping me, then we can let `hydra.cryp.to` build the PR again.

**Comment by jefdaj** [comment]
Thanks! @peti, I just committed some changes to `default.nix

**Comment by jefdaj** [comment]
On second thought, they probably work because I have 'allowBroken = true` in the script. Which means they'll still break on hydra. I'll try to figure out a way to churn through them all slowly without crashing and remove all the not-actually-broken ones from `default.nix`.

**Comment by peti** [comment]
I've pushed the current state of the PR  to Hydra for building.

**Comment by jefdaj** [comment]
I might have fixed some of them right after you pushed that. Think I got the ~500 that depend on these: EnsembleBase, ggtern, gQTLBas, GWASTools, jomo, lme4, MBESS, openssl, partitions, pathview, pedigreemm, polynom, poppr, RCytoscape, ReporteRs, RTN, sodium, V8, VIM.

**Comment by peti** [comment]
I've pushed 518fd13 for test-building on Hydra.

**Comment by jefdaj** [comment]
Hey, looks pretty good! Down to just a few errors. I'll see if I can fix them each manually today.

**Comment by jefdaj** [comment]
Can you try it now? I think all the build errors were resolved. A couple were just due to me forgetting to pull all the *.nix files from my dev branch.

**Comment by peti** [comment]
Results are at http://hydra.cryp.to/jobset/nixpkgs/r-updates. It's looking pretty good, indeed.

**Comment by jefdaj** [comment]
Cool! I just tried re-building all the packages marked "still failing", and only one (Metab) actually fails on my machine. I marked the broken dependency mzR. Think the rest are just random Hydra errors?

**Comment by peti** [comment]
Huh? Looking at a build log like http://hydra.cryp.to/build/1659871, I see no indication that this might be a "random Hydra error". Certainly, Hydra is not causing that particular failure? How could it?

**Comment by jefdaj** [comment]
To tell the truth I haven't ever looked that deeply into Hydra before. My only contact with it has been merging PRs, and sometimes the automated build will fail even if it's fine. So I assumed some fraction of package builds randomly fail too. Probably shouldn't assume things though!

If there aren't random failures, I suppose there must be some implicit dependency that my machine happens to satisfy, but Hydra doesn't?

Skimming the log files, there are two types of errors. One mentions `bioconductor.org`:

```
** preparing package for lazy loading
Warning in file(filename, "r", encoding = encoding) :
  unable to resolve 'bioconductor.org'
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Error : unable to load R code in package 'packageName'
```

And the other a `system()` call from inside R:

```
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'packageName', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
```

Network access isn't allowed during local or hydra builds, right? So the package shouldn't actually depend on contacting `bioconductor.org`. Some ideas:

* Maybe this is what it looks like when a package requires X to run during the install?
* Missing native dependency for reading a certain type of compiled code?
* Permissions issue? Seems unlikely

I'll try to figure it out in more detail sometime in the next couple days.

**Comment by peti** [comment]
> Network access isn't allowed during local or hydra builds, right?

Right. If you're building in a chroot environment, then there's no network access.

The error

~~~
Error : .onLoad failed in loadNamespace() for 'packageName', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
~~~

looks like the build tries to execute `which` but can't find it (because it's not listed in buildInputs).

**Comment by jefdaj** [comment]
Oh, of course! I always forget that `which` isn't part of `stdenv`. I'll check if that solves most of them later today.

**Comment by jefdaj** [comment]
Never mind, it must be something else. I fixed my script to `nix-build --pure` but still can't reproduce the failures--they succeed whether or not I add `pkgs.which` to `packagesWithNativeBuildInputs`. Tried removing existing entries though, and that does break existing packages as expected.

**Comment by peti** [comment]
`nix-build` has no `--pure` argument. `nix-shell` does, but even there the flag does not do what you seem to believe, i.e. it does *not* enable chroot builds.

**Comment by jefdaj** [comment]
I wondered about that since I couldn't find it documented anywhere. Looks like I wanted `--option build-use-chroot true` instead, right? Enabled that and now everything is failing as it should! (Sounds weird to say) Is it normally enabled by default? I remember setting `useChroot = false` in my global config when first trying Nix because it fixed something I was working on, and maybe I've been subtly messing up all my packages since then. Thanks for pointing it out! Is the difference mainly that chroot is the "proper" way to do it and `--pure` is a less-pure version that's nicer for interactive use because it keeps your `.profile`?

**Comment by jefdaj** [comment]
How does it look now? I think I auto-marked almost everything broken, although there might be one or two packages left that don't build but did on my machine.

**Comment by peti** [comment]
Looks pretty good: http://hydra.cryp.to/jobset/nixpkgs/r-updates! I guess it's time to merge your patches to `master` now. Thank you very much for your efforts!

**Comment by jefdaj** [comment]
Great! Thanks for hand-holding a bit too.

**Pull request merged**
