### PR TITLE
Kernels 2021-11-21

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Should be automatically backportable after #146821 is merged.

**Comment by mweinelt** [comment]
5.14 should be dropped now, because the series is EOL and we are just before the branch-off.

**Comment by Ma27** [comment]
FWIW we frequently drop EOLed kernels on stable releases, so backporting a removal shouldn't be a big deal if necessary.

**Review by fabianhjr — APPROVED** [review]
Booted into 5.15.4 without issues.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
:( 

Going to look into it tomorrow.

**Comment by Ma27** [comment]
The issue was linux_zen btw.

**Comment by Ma27** [comment]
Since noone backported it for a while, I wouldn't start with it now. But since it was updated independently I'd like to raise the question whether this should be part of the update script or not (in the end I'm interested in having a semi-automated backport mechanism).

cc @Mic92

**Comment by Mic92** [comment]
> Since noone backported it for a while, I wouldn't start with it now. But since it was updated independently I'd like to raise the question whether this should be part of the update script or not (in the end I'm interested in having a semi-automated backport mechanism).
> 
> cc @Mic92

I am ok, with having it backported. I just don't any machines with zen kernels on stable so it would be untested from my side.

**Comment by Ma27** [comment]
I don't really mind whether or not it gets backported, but I'd like to not have it interfere with this update-script. So the other option is to exclude zen updates here to make sure these never break the backport-bot.

**Comment by Mic92** [comment]
Ok. How does it interfere with the update-script? We have our own update script for zen.

**Comment by Ma27** [comment]
OK, sorry yesterday's wording was horribly poor, sorry! The issue I see is

* zen kernels are updated on their own, but never backported
* (all?) other kernels are updated in a different PR (i.e. this one) and always backported
* linux_zen: 5.15.2-zen1 -> 5.15.3-zen1 (#146633) was filed after this PR (which has an auto-backport label), linux_zen bump is now part of this PR
* backporting fails because linux_zen bump happened here, but was never ported to stable before.

I see several options:

* perform all updates in a single PR
* modify the auto-update script that is used by @TredwellGit to not touch linux_zen.

I don't have a strong opinion on what we'll do (because I don't use linux_zen), but I'd like to see this solved so that auto-backport PRs work again and I don't have to manually cherry-pick commits again.

**Pull request merged**
