### PR TITLE
nvidia_x11: 470.63.01 → 470.74

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
would you like to be its maintainer?

**Comment by fabianhjr** [comment]
I don't think so, I am waiting for GPU prices to come back down to MSRP to switch to AMD.

Well maybe on the mean time I could be a temp maintainer; will consider it and create a PR to add myself as a maintainer if so.

**Review by kevincox — APPROVED** [review]

**Comment by kevincox** [comment]
Result of `nixpkgs-review pr 138773` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11</li>
    <li>linuxPackages-libre.nvidia_x11</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11</li>
    <li>linuxPackages_latest-libre.nvidia_x11</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>gwe</li>
    <li>python38Packages.TheanoWithCuda</li>
    <li>python39Packages.TheanoWithCuda</li>
    <li>xpraWithNvenc</li>
  </ul>
</details>
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>bumblebee</li>
    <li>geekbench</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_4_4.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11</li>
    <li>linuxPackages.nvidia_x11 (linuxKernel.packages.linux_5_10.nvidia_x11)</li>
    <li>linuxPackages_hardened.nvidia_x11 (linuxPackages_5_10_hardened.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_5_13.nvidia_x11</li>
    <li>linuxPackages_5_13_hardened.nvidia_x11 (linuxKernel.packages.linux_5_13_hardened.nvidia_x11)</li>
    <li>linuxPackages_latest.nvidia_x11 (linuxKernel.packages.linux_5_14.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11)</li>
    <li>linuxPackages_lqx.nvidia_x11 (linuxKernel.packages.linux_lqx.nvidia_x11)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11)</li>
    <li>linuxPackages_xanmod.nvidia_x11 (linuxKernel.packages.linux_xanmod.nvidia_x11)</li>
    <li>linuxPackages_zen.nvidia_x11 (linuxKernel.packages.linux_zen.nvidia_x11)</li>
    <li>mangohud</li>
    <li>nvfancontrol</li>
    <li>primus</li>
    <li>psensor</li>
  </ul>
</details>

**Comment by kevincox** [comment]
The failed to build just looks like non-free.

**Comment by fabianhjr** [comment]
Note, seems like there is a g-sync issue on this latest release that will render some blank frames from time to time (disabling g-sync makes that go away)

**Pull request merged**
