### PR TITLE
swift: 5.4.2 -> 5.5.2

### PR DESCRIPTION
**Pull request by dduan**
Update Swift version.

There are no disruptive changes in Swift 5.5's project setup other than the addition of `swift-crypto`.

I added a helper function to de-duplicate some code.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
I don't use this much anymore, but I'll at least help kick the tires a bit!

As for the change:

Generally LGTM and I like making helpers for the fetching too :).

I kinda liked the version info at the top, so when updating this it's (more) obvious what needs to be checked and easy enough to find.
But since you're volunteering to be a maintainer whatever you think works best sounds good to me.

As a tip, I used to put `passthru = { inherit srcs; }` or similar in `meta` and then build them all in a row with `-Q -k` (I think? -- be quiet (other than the hash error), keep going, maybe `-j1` too to do one at a time so there aren't any interleaved outputs, forget if that's needed) to get it to spit out all the new hashes when bumping versions (evaluating `swift.srcs`).  Might be better way to do this but thought I'd share in case that helps.

Building presently... will poke at the output at least!

Thanks for submitting this and tackling these changes!

**Review by trepetti — CHANGES_REQUESTED** [review]
Thank you for the PR and stepping up to maintain as well @dduan and thank you @dtzWill for the review. I agree that `fetchAppleRepo` is a good addition to `fetchSwiftRelease` for dependencies that do not conform to the standard swift release tag. The only thing I think that needs to be changed is consolidating the dependency version variables at the top again, like @dtzWill said, and leaving that comment so that it is easier to look up those versions for a given release.

**Comment by dduan** [comment]
Thanks for the feedbacks @dtzWill, @trepetti! Looking back, I did a pretty poor job explaining some of the changes in the original patch. I won't make you go through them now. Instead...

...I've added back the centralized versions per your suggestions! And I've also taken the liberty to organize some of the comments throughout the source file to make them appear in better context.

While we were here, I might as well tell you about this [script](https://github.com/dduan/SwiftOnNix) that I intend to use to automate future Swift releases :)

**Comment by trepetti** [comment]
@dduan Nice! That new approach with the centralized versions looks like a great way to organize the dependencies in one structure.

One request: would you be able to rebase and combine these commits and force-push as one commit? The release managers like everything to be easy to run git bisect on for debugging purposes when it comes time to branch off, and they would ideally want to have a single commit `swift: 5.4.2 -> 5.5.2` to bisect on. Once that is done, I will give it a run locally over night to check things (last I checked the building and testing on Swift times out on CI) for final approval.

**Comment by dduan** [comment]
> a single commit

Done @trepetti. Really appreciate your review. I'll be back for the upcoming Swift 5.6 release soon ;P

**Comment by dduan** [comment]
ping :)

I know it's kind of a hassle to build the whole thing locally. Really appreciate it if someone can give it a go tho :)

**Comment by dtzWill** [comment]
I definitely saw the build through and poked at output.  Don't have a recent project to try things out on, but can confirm it builds (and seems to produce same output-ish as before).

**Pull request merged**
