### PR TITLE
gdal-netcdf: GDAL with netCDF format support

### PR DESCRIPTION
**Pull request by bzizou**
Hello,

I added a copy of the GDAL package, with netCDF format support added.

bzizou@killeen:~/nixpkgs$ gdalinfo --formats |grep -i netcdf 
  GMT -raster- (rw): GMT NetCDF Grid Format  
  netCDF -raster- (rw+s): Network Common Data Format

cc @MarcWeber

### CODE REVIEW

**Comment by vbgl** [comment]
Why do you add a new package rather than add (optional) support for netCDF to the existing package ?

**Comment by bzizou** [comment]
Because I'm a dummy newbie :-) I haven't understand yet how to select a package that as the same name of another with "nix-env -i"...

**Comment by vbgl** [comment]
Selecting packages by name is not the best approach. Selecting them by attribute path is safer. The `nox` tool can be helpful. Install `nox` using `nix-env -iA nixpkgs.nox`, then you can use it to *search* a package by name (e.g., `nox gdal`) and install it through its attribute path.

If you want to update your PR (as you state that your commit is bad), feel free to amend it locally and force-push to this branch.

**Comment by bzizou** [comment]
Well thank you!
So, I've amended my commit (and re-tested the resulting package). Hope I'm doing well...

**Comment by bzizou** [comment]
Thank you very much for your help!
- I corrected the optional list and name of the variable
- now, netcdf support is enabled by default into the gdal package, but still may be disabled by netcdfSupport=false.
- by the way, I updated to version 2.0.2

**Comment by vbgl** [comment]
Last bit of nitpicking: the line `netcdfSupport ? true ` states that argument `netcdfSupport` is optional and, if not provided, takes the (default) value `true`. Therefore, there is no need for the change in `all-packages.nix`.

**Comment by bzizou** [comment]
OK, I'm used to remind default values into config files, but this does not seem to be the policy of the `all-packages.nix` file, so I removed the variable from this file.

**Pull request merged**
