### PR TITLE
staging-next 2023-03-16

### LINKED ISSUE #222180: Build failure: python3.pkgs.babel
### Steps To Reproduce

1. `nix build -f . python3.pkgs.babel --rebuild`

### Build log
`curl https://termbin.com/3ctbd`

### Additional context

cebf6aa8fd0da7d70630eb4699ba4f7e6348d6fa commit description mentions this:

>     Some tests required pytz, some tests are just broken two times a year
>     on days when EST is moving from and to daylight saving time.

so it is likely only reproducible sometimes depending on the time of the year

### Notify maintainers
@mweinelt 
### Metadata
nixpkgs master c4d958442734f9a33eacb6a06e4e656b88203d46

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/219444

- - - 
##### Mass breakages
- Fallout from libxcrypt changes:
  - [x] `perlPackages.Authen-Simple` a973339324430  https://hydra.nixos.org/build/213019520
  - [x] `dovecot` #222022 
  - [x] `perlPackages.Plack` #223138
- Fallout from patchelf update, e.g. emacs
  - [x] Plan is to revert the update to `patchelfStable`.
- Misc.: 
  - [x] liblapack issues on x86_64-darwin (e.g. numpy): avoided by rebuilding cb10bd6cb34e5cf093340b14852844dd82de0813
  - [x] `snappy` on x86_64-darwin https://hydra.nixos.org/build/213305017  https://github.com/NixOS/nixpkgs/pull/221461/commits/2a21328f7e0b751c6ec1f2539cb07dc8e85c8e43

##### Fixes

Closes #222180

### CODE REVIEW

**Comment by vcunat** [comment]
@stigtsp: can you look at perl (test) regressions stemming from removal of weak password-hashing algorithms?  (you're in `lib.teams.perl.members`)  In particular I didn't immediately see what to do about https://hydra.nixos.org/build/213476142 (same for all platforms)

**Comment by vcunat** [comment]
It's not a mass failure, but this `qt6.qtwebengine` regression seems suspicious: 
https://hydra.nixos.org/build/213502756
https://hydra.nixos.org/build/213504748
Maintainers: @milahu, @NickCao.  I thought it likely caused by PR #217568 but `enableParallelInstalling = false;` didn't help so I don't really know.

**Comment by NickCao** [comment]
> It's not a mass failure, but this `qt6.qtwebengine` regression seems suspicious: https://hydra.nixos.org/build/213502756 https://hydra.nixos.org/build/213504748 Maintainers: @milahu, @NickCao. I thought it likely caused by PR #217568 but `enableParallelInstalling = false;` didn't help so I don't really know.

Actually its the ffmpeg bump: `QtWebEngine will not be built: Unmodified ffmpeg >= 5.0 is not supported.`

**Comment by stigtsp** [comment]
> @stigtsp: can you look at perl (test) regressions ...

Fix for `perlPackages.Plack`
- https://github.com/NixOS/nixpkgs/pull/223138

**Pull request merged**
