### PR TITLE
KDE Gear 21.04.0

### PR DESCRIPTION
**Pull request by ttuegel**
###### Motivation for this change

- Update KDE Applications 20.12.3 to KDE Gear 21.04.0.
- Change the attribute name from `kdeApplications` to `kdeGear`.

Attn: @NixOS/qt-kde 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I think we should add an alias for kdeApplications.

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Comment by schmittlauch** [comment]
I'd be willing to test some of this, but am not sure whether this is possible from a 20.09 installation. Mixing Qt versions running in parallel is still problematic, isn't it?

**Comment by ttuegel** [comment]
@SuperSandro2000 Is there a way to add a nested alias to `alias.nix`, or do we need to add an alias directly to `qt-packages.nix`.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Is there a way to add a nested alias to `alias.nix`, or do we need to add an alias directly to `qt-packages.nix`?

Not fully sure. Some examples are here https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/aliases.nix#L751 and here https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/aliases.nix#L944

Also I think you missed https://github.com/NixOS/nixpkgs/blob/21.05/pkgs/top-level/all-packages.nix#L17598

**Pull request merged**
