### PR TITLE
Update firefox.syncserver and its dependencies

### PR DESCRIPTION
**Pull request by Nadrieril**
###### Motivation for this change
Update; also fixes compatibility with recent versions of Firefox Android.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]
- commit per package
- can you move the expressions to `python-modules/<package>/default.nix`.

**Comment by Nadrieril** [comment]
@FRidh I'm not sure I understand your first point: do you want one PR per package ?

**Comment by Nadrieril** [comment]
@FRidh Does this look good to you ?

**Comment by FRidh** [comment]
Yep, thanks. Pushed d1e2159638d.

**Comment by FRidh** [comment]
Some other expressions should have actually been moved as well...but..well that's for next time.

**Pull request closed without merging**
