### PR TITLE
libvirt: 7.9.0 -> 7.10.0

### PR DESCRIPTION
**Pull request by Kranzes**
###### Motivation for this change
Updated libvirt and it's related packages

change logs:
- https://libvirt.org/news.html#v7-10-0-2021-12-01
- https://gitlab.com/libvirt/libvirt-python/-/compare/v7.9.0...v7.10.0
-  https://gitlab.com/libvirt/libvirt-perl/-/compare/v7.9.0...v7.10.0

###### Things done
Testing: Successfully created a new NixOS VM.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 148529` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>terraform-full</li>
  </ul>
</details>
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvmi</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixopsUnstable</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>perl534Packages.SysVirt</li>
    <li>python38Packages.guestfs</li>
    <li>python38Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>terraform-providers.libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
  </ul>
</details>

**Comment by Kranzes** [comment]
@SuperSandro2000 Are you able to merge?

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 148529` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>2 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>rubyPackages.ruby-libvirt: log was empty</li>
<li>rubyPackages_3_0.ruby-libvirt: log was empty</li>
  </ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>(rubyPackages_2_7.ruby-libvirt): log was empty</li>
  </ul>
</details>
<details>
<summary>
26 packages built:
</summary>
<ul>
<li>collectd</li>
<li>collectd-data</li>
<li>diffoscope</li>
<li>docker-machine-kvm</li>
<li>docker-machine-kvm2</li>
<li>gnome.gnome-boxes</li>
<li>haskellPackages.libvirt-hs</li>
<li>libguestfs</li>
<li>libvirt</li>
<li>libvirt-glib</li>
<li>libvmi</li>
<li>minikube</li>
<li>minishift</li>
<li>nixopsUnstable</li>
<li>perl532Packages.SysVirt</li>
<li>perl534Packages.SysVirt</li>
<li>python38Packages.guestfs</li>
<li>python38Packages.libvirt</li>
<li>python39Packages.guestfs</li>
<li>python39Packages.libvirt</li>
<li>vagrant</li>
<li>virt-manager</li>
<li>virt-manager-qt</li>
<li>virt-top</li>
<li>virt-viewer</li>
<li>virtlyst</li>
</ul>
</details>

**Pull request merged**
