### PR TITLE
geos: remove 3.11 version, not needed any more

### PR DESCRIPTION
**Pull request by autra**
## Things done

It seems that geos_3_11 is not necessary any more.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Aleksanaa — CHANGES_REQUESTED** [review]
Please add top-level/aliases.nix

**Comment by autra** [comment]
I'm wondering why the @NixOS/geospatial team wasn't mentioned by ofborg... 

Actually, I checked upstream, and all the version from 3.9 up to 3.13 are not yet EOL'd.

I think we should either include all of them, or just the latest (with the exception of 3.9 for django). What is best according to you @NixOS/geospatial? I'll weakly vote for keeping only the latest.

**Comment by willcohen** [comment]
Historically I’ve occasionally had to split off old ones when some other package in nixpkgs couldn’t stay up to date but we didn’t want to hold back the main geos releases — if you can confirm that uses of 3.11 have all been eliminated as dependencies elsewhere, we can certainly remove!

**Comment by autra** [comment]
> Please add top-level/aliases.nix

I've added a "throw" there.

**Review by Aleksanaa — APPROVED** [review]

**Comment by Aleksanaa** [comment]
> if you can confirm that uses of 3.11 have all been eliminated as dependencies elsewhere, we can certainly remove!

Can at least confirm no open dotfiles use it 😁

**Pull request merged**
