### PR TITLE
Luau: installs libraries + headers

### PR DESCRIPTION
**Pull request by thomascft**
## Description of changes

I've added a `.pc` file and made it so the library and headers are included in the package. I had a hard time copying the headers and `.pc` files over to `$out`, so my solution probably isn't perfect. If there's a better way of doing it, feel free to let me know. I also wasn't sure if the libraries should be installed in the `$dev` output instead of the default, but I can change that if it's needed.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by eclairevoyant — COMMENTED** [review]
Thanks for the PR. I've not tested the actual change itself, but I did notice the commit doesn't follow our conventions.

Please make sure to set the commit message (and PR title) as per the guidelines: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions

**Comment by teto** [comment]
could you check  the difference in closure size with `nix path-info -Sh <DRV>` ? headers or libraries sometimes come out into different outputs to minimize closure size.

**Comment by thomascft** [comment]
> could you check the difference in closure size with `nix path-info -Sh <DRV>` ? headers or libraries sometimes come out into different outputs to minimize closure size.
Sure thing!
`nix path-info -Sh .#luau`
`/nix/store/hqv3fpyc2yviarih9bbdxc8rpv4qyi53-luau-0.621	 78.2M`

**Comment by thomascft** [comment]
> could you check the difference in closure size with `nix path-info -Sh <DRV>` ? headers or libraries sometimes come out into different outputs to minimize closure size.

The libraries and headers now output to `$dev`. 
Here's the new `nix path-info -Sh .#luau`
`evaluating derivation 'git+file:///home/thomas/Documents/code/nixpkgs#luau'/nix/store/1qk8rzpmvyyj35zshg8h320kzhp22vcp-luau-0.621	 53.0M`

Anything else I should do?

**Comment by teto** [comment]
@thomascft the installPhase is a "lot" of specific code that I am afraid can break easily. Is upstream reluctant to add pkg-config support ? I dont think it's a very used package so if you put yourself as a maintainer, that would be a bit more reassuring.

**Comment by thomascft** [comment]
I'm not going to be able to commit to maintaining anything right now, so it'll probably be best if I close this PR.

**Pull request closed without merging**
