### PR TITLE
llama-cpp: merge upstream changes

### PR DESCRIPTION
**Pull request by josephst**
## Description of changes

`llama-cpp` upstream has had some recent changes in their `package.nix`, namely [embedding Metal shaders on Darwin to avoid `xcrun` and Xcode dependency](https://github.com/ggerganov/llama.cpp/commit/e190f1fca6f60d80944f9e8709d343a025c4d245) and [renaming cuBlas backend to CUDA](https://github.com/ggerganov/llama.cpp/commit/280345968dabc00d212d43e31145f5c9961a7604). This PR brings those changes into the `llama-cpp` that's packaged in nixpkgs. 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed` (on Darwin aarch64)
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by philiptaron** [comment]
I'll be able to build this on aarch64-darwin tonight if ofBorg doesn't snipe me first.

**Comment by drupol** [comment]
@abysssol Do you think you could have a look at this?

**Comment by abysssol** [comment]
@drupol I took a look at the changes, but I'm afraid I can't offer much insight, as I'm not familiar with llama-cpp (the nix package, the flake, nor the project itself). If you want me to try to figure something specific out, you'll need to be more detailed about what you actually want me to do.

The only thing I can think of is that since [the pr](https://github.com/ggerganov/llama.cpp/pull/6299) renaming `LLAMA_CUBLAS` to `LLAMA_CUDA` is newer than [`release b2481`](https://github.com/ggerganov/llama.cpp/releases/tag/b2481) (the version currently used in the nix package), I think a version update is necessary to get the updated cmake files (and other build files) where the rename is actually implemented. Otherwise `LLAMA_CUDA` probably won't have any effect, due to being used with an outdated version of llama-cpp that doesn't yet support it.
[The pr](https://github.com/ggerganov/llama.cpp/pull/5604) adding support for `LLAMA_METAL_EMBED_LIBRARY` is older than `release b2481`, so it's probably fine.

**Review by josephst — COMMENTED** [review]
Updated to latest upstream package - b2568

**Pull request merged**
