### PR TITLE
[WIP] Home Assistant

### PR DESCRIPTION
**Pull request by fleaz**
###### Motivation for this change
This adds [Home Assistant](http://home-assistant.io/) to NixOS.

Left to do:
- [ ] NixOS module
- [ ] NixOS tests
- [ ] Handling dynamic pip installs
- [ ] Build HA with tests enabled 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
In order to prevent home-assistant from later pulling in dependencies, we could maybe replace the function [install_package()](https://github.com/home-assistant/home-assistant/blob/543e8bb62ed8e8f91d38d486ad2d0cc0727c8ced/homeassistant/util/package.py#L20) by something like
```py
def install_package(package: str, upgrade: bool=True,
                    target: Optional[str]=None,
                    constraints: Optional[str]=None) -> bool:
    return check_package_exists(package)
```
I haven't tested this though.
There also seems to be the option `skip_pip`, e.g. [here](https://github.com/home-assistant/home-assistant/blob/8111e3944c2b5d2bbbf9e147fb0bb856283fea9f/homeassistant/bootstrap.py#L42). I guess it can be triggered using [--skip-pip](https://github.com/home-assistant/home-assistant/blob/4e91e6d103a2bc3922300737775f59749eecb263/homeassistant/__main__.py#L112)

Also, I think there should be an option to specify additional components, which also requires the possibility to specify additional dependencies.

**Review by FRidh — CHANGES_REQUESTED** [review]

**Comment by FRidh** [comment]
The following implements `skip-pip`:
```
diff --git a/pkgs/servers/home-assistant/default.nix b/pkgs/servers/home-assistant/default.nix
index c2ea5c28229..984925bfd7d 100644
--- a/pkgs/servers/home-assistant/default.nix
+++ b/pkgs/servers/home-assistant/default.nix
@@ -19,6 +19,7 @@ python3Packages.buildPythonApplication rec {
   propagatedBuildInputs = with python3Packages; [ astral certifi netifaces pip vincenty webcolors pyyaml yarl
                                                   aiohttp-cors voluptuous async-timeout requests aiohttp jinja2
                                                   pytz chardet setuptools_scm typing git nmap ];
+  makeWrapperArgs = [ "--add-flags --skip-pip" ];
 
 
  #checkInputs = [ python3Packages.pytest python3Packages.sqlalchemy ];

```

`home-assistant` is the opposite of Nix: 
https://github.com/home-assistant/home-assistant/issues/11134#issuecomment-351793248

We may need to find a way to include additional dependencies.

**Comment by FRidh** [comment]
Earlier home-assistant PR https://github.com/NixOS/nixpkgs/pull/19508

**Comment by f-breidenstein** [comment]
@FRidh Thanks for the link to the old PR. I will have a look at it. 

Re. "--skip-pip":
This way HA won't install anything on demand afaik. Every time a user would add a new component to her HA configuration, she would need to read the sourcecode of the activated component to get the list of needed python requirements and write them to the module configuration of her nixos home-assistant package. Not sure if this is very user friendly

@flokli told me about a feature were you can give the application some sort of "virtual environment" so home-assistant would be able to install it's dependencies with pip. Maybe this is better than listing all the requirements per hand?

(I start to think that HA was not the best choice for a first package when you want to learn packaging under NixOS *cough*)

**Comment by dotlambda** [comment]
I've gone ahead and tried running `hass --open-ui` but got many errors about modules that could not be found.
Therefore I packaged
- [netdisco](https://github.com/home-assistant/netdisco),
- [user-agents](https://github.com/selwin/python-user-agents) and last but not least
- [home-assistant-frontend](https://github.com/home-assistant/home-assistant-polymer)

For the last one, I use PyPI and avoid generating any JS, CSS and HTML foo from source.

user-agents depends on [ua-parser](https://github.com/ua-parser/uap-python), whose test I was not able to make run. They require to fetch a submodule but then still some errors occur, e.g.
```
======================================================================
ERROR: _regexes (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: _regexes
Traceback (most recent call last):
  File "/nix/store/4wqa1whb42khic67rv9jgip30nxmaii8-python3-3.6.4/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/nix-build-python3.6-ua-parser-0.7.3.drv-0/ua-parser-0.7.3/ua_parser/_regexes.py", line 8, in <module>
    from .user_agent_parser import (
  File "/tmp/nix-build-python3.6-ua-parser-0.7.3.drv-0/ua-parser-0.7.3/ua_parser/user_agent_parser.py", line 549, in <module>
    from ._regexes import USER_AGENT_PARSERS, DEVICE_PARSERS, OS_PARSERS
ImportError: cannot import name 'USER_AGENT_PARSERS'
```

Plus, I added some already packaged python packages to home-assistant's `propagatedBuildInputs`.

You can find the changes here: https://github.com/NixOS/nixpkgs/compare/master...dotlambda:home-assistant
I'm now able to run `hass --open-ui` without any errors and with `--skip-pip` enabled.

What do you think, @FRidh? Should I make PRs for the 4 new python modules?
I would of course still have to add meta blocks.

**Comment by FRidh** [comment]
@dotlambda how many more packages are going to be added? I mean, `open-ui` is one thing, but what about extra modules? Should we package all of them? Who is going to maintain all these expressions? Did you read https://github.com/NixOS/nixpkgs/pull/19508?

**Comment by dotlambda** [comment]
No, of course we shouldn't package all dependencies.
I think that anyone wanting to use home-assistant should just package all modules they need for their use case. This way, the maintance effort will also be distributed across multiple maintainers.
And then, one can specify those using an argument called `extraBuildInputs`, which can be set using `home-assistant.override { extraBuildInputs = [ ... ]; }` or an equivalent option of the NixOS module.

**Comment by flokli** [comment]
I also think calling home-assistant using `--skip-pip` from its module in combination with a module configuration to specify extra Packages is a good idea.

If the list of packages grows too much, we might do some plugins to packages translation in there, but as a start, this might be enough.

Good to already see some of those packages landing in nixpkgs :-)

It would maybe make sense to put `home-assistant-frontend` behind a `frontendSupport` argument of the package itself (defaulting to true), as it's pretty much the first thing home-assistant wants to start ;-)

**Comment by dotlambda** [comment]
Why did you add `vincenty` to `propagatedBuildInputs`, @f-breidenstein? I think the dependency was removed in 2016: https://github.com/home-assistant/home-assistant/commit/4b0df51b4088c64f1a647f838697d8656b43cf32

**Comment by dotlambda** [comment]
I have created a new version of the derivation for home-assistant, which you can find here: https://github.com/NixOS/nixpkgs/compare/master...dotlambda:home-assistant.
This uses `--skip-pip` and my proposed `extraBuildnputs`.
I added all dependencies listed in `setup.py` as well as those that were not found when running `hass --open-ui`. To avoid depending on `pip`, the appropriate import was removed.
I didn't make the frontend optional as @flokli proposed since `hass_frontend` is imported as soon as `hass` is run, regardless of the arguments.
The main thing that still has to be done is writing a NixOS module.

I hope you don't mind that I kept you as a maintainer, @f-breidenstein.

What do you think, @FRidh?

**Comment by bachp** [comment]
Would it be possible to use a tool to automatically generate nix expressions from home-assistants `requirements_all.txt`? Somthing like https://github.com/johbo/pip2nix.

I guess home-assistant wouldn't be very useful if most of the components are missing dependencies.

**Comment by dotlambda** [comment]
Yes that is possible, @bachp. See https://github.com/garbas/nixpkgs-python. But then, it cannot be included in nixpkgs from my understanding.
I think it is more helpful to include a basic home-assistant package in Nixpkgs, which allows us to write a NixOS module for it. It is very easy to spot missing dependencies because `hass` will print error messages like `ModuleNotFoundError: No module named 'netdisco'`.
Maybe we could add a list of possible `extraBuildInputs` (together with the components that require them) on https://nixos.org/nixos/manual/options.html.

**Comment by f-breidenstein** [comment]
@dotlambda, iirc I packaged everything which was mentioned in the requirements part of the `setup.py` from HA, but yes, it seems like it isn't there anymore.

@all: Sorry for the low amount of input to this discussion from my side, but regarding my limitied knownledge about nix and nixOS, I'm probably not very helpful by packaging such a beast like HA.

**Comment by dotlambda** [comment]
Any thoughts on this, @FRidh?

**Comment by FRidh** [comment]
@dotlambda I think having the following would be good:
- add a `skip-pip ? true` parameter. By default it won't fetch, but if one wants it they can override the expression easily and use that feature.
- add a `extraPackages ? x: []` parameter, which is a lambda like `withPackages` that selects packages from the same package set that is used to build `home-assistant`. One can then add packages to home-assistant by first overriding the python package set, and then overriding the home-asssistant expression to add packages with the lambda. The reason for the lambda is to guarantee a working package set.

**Comment by dotlambda** [comment]
I have started `hass` another time (without an existing configuration) and took note of all components that are loaded:
```
history
recorder
http
frontend
api
websocket_api
system_log
introduction
persistent_notification
updater
group
tts
tts.google
config
logbook
conversation
sun
sensor
sensor.yr
cloud
automation
script
discovery
map
config.script
config.core
config.hassbian
config.customize
config.group
config.automation
```
I think we should include all of their dependencies as listet in https://github.com/home-assistant/home-assistant/blob/master/requirements_all.txt.

**Comment by FRidh** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/34188. Thanks for the work!

**Pull request closed without merging**
