### PR TITLE
[WIP] pythonPackages.fipy: init at 3.3

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

Adding nist package

###### Things done

cc @wd15

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by costrouc** [comment]
@wd15 what other packages are necessary?

 - https://github.com/ktchu/LSMLIB and the python module?
 - gmsh? I packaged pygmsh but it looks like it is a different package?
 - mpi4py?
 - tkinter?

**Comment by FRidh** [comment]
looks good to me so far

**Comment by jonringer** [comment]
you got some merge conflicts, do you mind rebasing and pushing again? :)

**Comment by costrouc** [comment]
@jonringer happy to do that. Still waiting on nist fipy developers to state what packages they would find most useful in the image. The `setup.py` is a bit deceiving.

**Comment by wd15** [comment]
On Fri, Jul 12, 2019 at 5:21 PM Christopher Ostrouchov
<notifications@github.com> wrote:
>
> @wd15 what other packages are necessary.
>
> https://github.com/ktchu/LSMLIB and the python module?

No, LSMLIB is not necessary.

> gmsh? I packaged pygmsh but it looks like it is a different package?

Yes, Gmsh is already part of Nix and FiPy does not require PyGmsh. I
need to see if I can get FiPy working with the version of Gmsh
currently in Nixpkgs. I'll look into this over the next few days.

> mpi4py?

Not currently necessary.

> tkinter?

Yes as Matplotlib doesn't seem to work correctly without this.

Remember that my Python 3 version of a working Nix recipe for FiPy can
be found here, https://github.com/usnistgov/fipy/blob/a34f2f7dc90f54204906ddf0177a3256b7280da3/default.nix

-- 
Daniel Wheeler

**Comment by wd15** [comment]
Also, FiPy's conda-forge recipe is helpful, https://github.com/conda-forge/fipy-feedstock/blob/master/recipe/meta.yaml

**Comment by wd15** [comment]
@costrouc, you can close this now as its been replaced by #65035

**Pull request closed without merging**
