### PR TITLE
CompileDaemon: Init at 2017-03-08

### PR DESCRIPTION
**Pull request by Profpatsch**
- [x] binary executes

### CODE REVIEW

**Comment by Profpatsch** [comment]
fixed the homepage meta attr

**Comment by edolstra** [comment]
Please don't use CamelCase in package names.

**Comment by Profpatsch** [comment]
Thought I’d just use upstream name, will change.

**Comment by Profpatsch** [comment]
@edolstra wait, do you mean the attribute name or the name string?

**Comment by Profpatsch** [comment]
Okay, I just renamed everything.

**Pull request merged**
