### PR TITLE
maintainers: add rypervenche

### PR DESCRIPTION
**Pull request by rypervenche**
I'll be submitting a few font packages upon acceptance. Thanks!

### CODE REVIEW

**Review by Aleksanaa — COMMENTED** [review]
The commit message should be `maintainers: add rypervenche`

**Comment by rypervenche** [comment]
Fixed. Thank you.

**Comment by winterqt** [comment]
It might be a better idea just to do this as a separate commit when you add your first package (you need to update the commit message as well).

**Comment by rypervenche** [comment]
Understood. I misinterpreted "in a separate commit"  [in the wiki](https://wiki.nixos.org/wiki/Nixpkgs/Create_and_debug_packages#Both_source_code_packages_and_binary_packages) as "in a separate PR". I'll go ahead and close this and do it properly.

Thanks!

**Pull request closed without merging**
