### PR TITLE
singularity-tools: create required bind points

### PR DESCRIPTION
**Pull request by jbedo**
###### Motivation for this change

Latest version of singularity requires the creation of /root and two bind points in /etc/. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
I am not familiar with this code. Do you have an example I can test?

**Comment by jbedo** [comment]
Sure, see this [https://gist.github.com/jbedo/c32f6bb93470dc849e4d723c5cda7118](gist). Then try dropping into a shell using singularity after building: 

```
# sudo singularity shell result
WARNING: Non existent bind point (file) in container: '/etc/localtime'
WARNING: Non existent bind point (file) in container: '/etc/hosts'
ERROR  : Base home directory does not exist within the container: /root
ABORT  : Retval = 255
```
BTW, is there any way to tag this code with me as the maintainer? Since I wrote it and am maintaining it, would be nice to do so for clarity.

**Comment by Mic92** [comment]
You should be able to set `meta` the same way as in `stdenv.mkDerivation`:

```
nix-repl> (runCommand "foo" { meta.maintainers = ["foo"]; } "echo test > $out" ).meta.maintainers
[ "foo" ]
```

**Review by Mic92 — APPROVED** [review]
Changes work.

**Comment by Mic92** [comment]
Was this closed intentionally?

**Pull request closed without merging**
