### PR TITLE
Use new early kbd-setting code in initrd and fix layouts from external packages

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

@Profpatsch  reported a bug in my patch https://github.com/NixOS/nixpkgs/pull/16642. Rather than fixing it in the old code, I moved us to the new code from https://github.com/NixOS/nixpkgs/pull/16801 instead and fixed the same problem there. Along with fixing the reported bug, this gives us several advantages over the old code:
- Console is now set only if it really needs to (i.e. it's not a container);
- We support Unicode keymaps in initrd and set console properly;
- We also set colors, if they were specified;
- More modularity.
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

My test plan:
1. Build a VM with this configuration:

```
  i18n.consoleKeyMap = "neo";
  i18n.consoleFont = "ter-v16n";
  i18n.consolePackages = [ pkgs.terminus_font pkgs.kbdKeymaps.neo pkgs.kbdKeymaps.dvp ];
  boot.initrd.kernelModules = [ "fbcon" ];
  boot.earlyVconsoleSetup = true;
```
1. Run it with `QEMU_KERNEL_PARAMS=boot.debug1devices result/bin/run-nixos-vm`;
2. Observe that layout is unconditionally set up;
3. Observe that (if layout supports that) I can change the input language;
4. Observe that font is set up iff `earlyVconsoleSetup` is enabled.

I've run it with following changes:
- `consoleKeyMap`: `neo`, `dvp`, `ruwin_cplk-UTF-8`, not set;
- `earlyVconsoleSetup`: on and off

@Profpatsch, it would be cool to get additional testing from a real user of a layout from an external package! Notice that by default `consolePackages` is set to `with pkgs.kbdKeymaps; [ neo dvp ]` -- that is, if you don't change it you get those layouts installed like before.

### CODE REVIEW

**Comment by Profpatsch** [comment]
That looks very cool, will test with neo soon.

**Comment by Profpatsch** [comment]
Okay, switched my system to the patch; it built and neo was enabled from the LUKS password field.
Don’t know whether the tests will pass, but I guess we’ll see once we merge.

+1 from me @abbradar

**Comment by Profpatsch** [comment]
Okay, ran the test `keymap.nix` and it works again with this patch.

**Comment by abbradar** [comment]
Big thanks for testing! Let's merge then (I usually like to leave a window for feedback but without this patch users' configurations are broken and things seem to work).

**Pull request merged**
