### PR TITLE
python3Packages.httpcore: 0.13.0 -> 0.13.4

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.13.4

Change log: https://github.com/encode/httpcore/releases/tag/0.13.4

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126661` at 7ab6fb68 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages skipped due to time constraints:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python39Packages.teslajsonpy</li>
  </ul>
</details>
<details>
  <summary>69 packages built successfully:</summary>
  <ul>
    <li>datasette (python38Packages.datasette)</li>
    <li>dyndnsc</li>
    <li>lexicon</li>
    <li>python38Packages.PyRMVtransport</li>
    <li>python38Packages.anyio</li>
    <li>python38Packages.authcaptureproxy</li>
    <li>python38Packages.axis</li>
    <li>python38Packages.denonavr</li>
    <li>python38Packages.dependency-injector</li>
    <li>python38Packages.elmax</li>
    <li>python38Packages.entrance</li>
    <li>python38Packages.entrance-with-router-features</li>
    <li>python38Packages.envoy-reader</li>
    <li>python38Packages.fastapi</li>
    <li>python38Packages.ha-philipsjs</li>
    <li>python38Packages.httpcore</li>
    <li>python38Packages.httpx</li>
    <li>python38Packages.ipfshttpclient</li>
    <li>python38Packages.ircrobots</li>
    <li>python38Packages.ismartgate</li>
    <li>python38Packages.json-logging</li>
    <li>python38Packages.jupyter_server</li>
    <li>python38Packages.jupyterlab</li>
    <li>python38Packages.jupyterlab_server</li>
    <li>python38Packages.jupytext</li>
    <li>python38Packages.nbclassic</li>
    <li>python38Packages.pylitterbot</li>
    <li>python38Packages.pytest-httpx</li>
    <li>python38Packages.pytest-sanic</li>
    <li>python38Packages.respx</li>
    <li>python38Packages.sanic</li>
    <li>python38Packages.sanic-auth</li>
    <li>python38Packages.sanic-testing</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.teslajsonpy</li>
    <li>python38Packages.zeep</li>
    <li>python39Packages.PyRMVtransport</li>
    <li>python39Packages.anyio</li>
    <li>python39Packages.authcaptureproxy</li>
    <li>python39Packages.axis</li>
    <li>python39Packages.datasette</li>
    <li>python39Packages.denonavr</li>
    <li>python39Packages.dependency-injector</li>
    <li>python39Packages.elmax</li>
    <li>python39Packages.entrance</li>
    <li>python39Packages.entrance-with-router-features</li>
    <li>python39Packages.envoy-reader</li>
    <li>python39Packages.fastapi</li>
    <li>python39Packages.ha-philipsjs</li>
    <li>python39Packages.httpcore</li>
    <li>python39Packages.httpx</li>
    <li>python39Packages.ipfshttpclient</li>
    <li>python39Packages.ircrobots</li>
    <li>python39Packages.ismartgate</li>
    <li>python39Packages.json-logging</li>
    <li>python39Packages.jupyter_server</li>
    <li>python39Packages.jupyterlab</li>
    <li>python39Packages.jupyterlab_server</li>
    <li>python39Packages.jupytext</li>
    <li>python39Packages.nbclassic</li>
    <li>python39Packages.pylitterbot</li>
    <li>python39Packages.pytest-httpx</li>
    <li>python39Packages.pytest-sanic</li>
    <li>python39Packages.respx</li>
    <li>python39Packages.sanic</li>
    <li>python39Packages.sanic-auth</li>
    <li>python39Packages.sanic-testing</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.zeep</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 126661` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>71 packages built:</summary>
  <ul>
    <li>datasette (python38Packages.datasette)</li>
    <li>dyndnsc</li>
    <li>home-assistant</li>
    <li>lexicon</li>
    <li>python38Packages.PyRMVtransport</li>
    <li>python38Packages.anyio</li>
    <li>python38Packages.authcaptureproxy</li>
    <li>python38Packages.axis</li>
    <li>python38Packages.denonavr</li>
    <li>python38Packages.dependency-injector</li>
    <li>python38Packages.elmax</li>
    <li>python38Packages.entrance</li>
    <li>python38Packages.entrance-with-router-features</li>
    <li>python38Packages.envoy-reader</li>
    <li>python38Packages.fastapi</li>
    <li>python38Packages.ha-philipsjs</li>
    <li>python38Packages.httpcore</li>
    <li>python38Packages.httpx</li>
    <li>python38Packages.ipfshttpclient</li>
    <li>python38Packages.ircrobots</li>
    <li>python38Packages.ismartgate</li>
    <li>python38Packages.json-logging</li>
    <li>python38Packages.jupyter_server</li>
    <li>python38Packages.jupyterlab</li>
    <li>python38Packages.jupyterlab_server</li>
    <li>python38Packages.jupytext</li>
    <li>python38Packages.nbclassic</li>
    <li>python38Packages.pylitterbot</li>
    <li>python38Packages.pytest-httpx</li>
    <li>python38Packages.pytest-sanic</li>
    <li>python38Packages.respx</li>
    <li>python38Packages.sanic</li>
    <li>python38Packages.sanic-auth</li>
    <li>python38Packages.sanic-testing</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.teslajsonpy</li>
    <li>python38Packages.zeep</li>
    <li>python39Packages.PyRMVtransport</li>
    <li>python39Packages.anyio</li>
    <li>python39Packages.authcaptureproxy</li>
    <li>python39Packages.axis</li>
    <li>python39Packages.datasette</li>
    <li>python39Packages.denonavr</li>
    <li>python39Packages.dependency-injector</li>
    <li>python39Packages.elmax</li>
    <li>python39Packages.entrance</li>
    <li>python39Packages.entrance-with-router-features</li>
    <li>python39Packages.envoy-reader</li>
    <li>python39Packages.fastapi</li>
    <li>python39Packages.ha-philipsjs</li>
    <li>python39Packages.httpcore</li>
    <li>python39Packages.httpx</li>
    <li>python39Packages.ipfshttpclient</li>
    <li>python39Packages.ircrobots</li>
    <li>python39Packages.ismartgate</li>
    <li>python39Packages.json-logging</li>
    <li>python39Packages.jupyter_server</li>
    <li>python39Packages.jupyterlab</li>
    <li>python39Packages.jupyterlab_server</li>
    <li>python39Packages.jupytext</li>
    <li>python39Packages.nbclassic</li>
    <li>python39Packages.pylitterbot</li>
    <li>python39Packages.pytest-httpx</li>
    <li>python39Packages.pytest-sanic</li>
    <li>python39Packages.respx</li>
    <li>python39Packages.sanic</li>
    <li>python39Packages.sanic-auth</li>
    <li>python39Packages.sanic-testing</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.teslajsonpy</li>
    <li>python39Packages.zeep</li>
  </ul>
</details>

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/vwam75xi7yfjaw16vfn86gjpy16jq0s6-python3.9-anyio-3.1.0.drv' failed with exit code 1; last 10 log lines:
  running install tests
  no Makefile or custom installCheckPhase, doing nothing
  pythonCatchConflictsPhase
  pythonRemoveBinBytecodePhase
  pythonImportsCheckPhase
  Executing pythonImportsCheckPhase
  Check whether the following modules can be imported: anyio
  pytestCheckPhase
  Executing pytestCheckPhase
  Disabled tests path "--ignore=tests/streams/test_tls.py" does not exist. Aborting
```

**Comment by risicle** [comment]
And on nixos x86_64:

```
10 packages failed to build:
dyndnsc home-assistant python38Packages.entrance python38Packages.entrance-with-router-features python38Packages.json-logging python38Packages.sanic python38Packages.sanic-auth python38Packages.sanic-testing python39Packages.authcaptureproxy python39Packages.teslajsonpy
```

:frowning_face:

**Comment by risicle** [comment]
Hmm I tried again on nixos and had success. Possibly due to some flux in `master`.

**Comment by fabaff** [comment]
> On macos 10.15:

Sorry, I didn't update the darwin part.

**Comment by fabaff** [comment]
Issue with 0.13.4: https://github.com/encode/httpcore/issues/357

**Comment by mweinelt** [comment]
Can we update to 0.13.3 in the meantime?

**Comment by dotlambda** [comment]
> Can we update to 0.13.3 in the meantime?

There is 0.13.5.

**Comment by mweinelt** [comment]
> > Can we update to 0.13.3 in the meantime?
> 
> There is 0.13.5.

https://github.com/encode/httpcore/releases/tag/0.13.6  :grinning:

**Comment by dotlambda** [comment]
Just add that to your Home Assistant PR. I don't think @fabaff will be mad.

**Comment by mweinelt** [comment]
I don't think we really need it, we just don't want 0.13.4, which is buggy as seen above.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 126661 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>71 packages built:</summary>  <ul>    <li>datasette (python38Packages.datasette)</li>    <li>dyndnsc</li>    <li>home-assistant</li>    <li>lexicon</li>    <li>python38Packages.PyRMVtransport</li>    <li>python38Packages.anyio</li>    <li>python38Packages.authcaptureproxy</li>    <li>python38Packages.axis</li>    <li>python38Packages.denonavr</li>    <li>python38Packages.dependency-injector</li>    <li>python38Packages.elmax</li>    <li>python38Packages.entrance</li>    <li>python38Packages.entrance-with-router-features</li>    <li>python38Packages.envoy-reader</li>    <li>python38Packages.fastapi</li>    <li>python38Packages.ha-philipsjs</li>    <li>python38Packages.httpcore</li>    <li>python38Packages.httpx</li>    <li>python38Packages.ipfshttpclient</li>    <li>python38Packages.ircrobots</li>    <li>python38Packages.ismartgate</li>    <li>python38Packages.json-logging</li>    <li>python38Packages.jupyter_server</li>    <li>python38Packages.jupyterlab</li>    <li>python38Packages.jupyterlab_server</li>    <li>python38Packages.jupytext</li>    <li>python38Packages.nbclassic</li>    <li>python38Packages.pylitterbot</li>    <li>python38Packages.pytest-httpx</li>    <li>python38Packages.pytest-sanic</li>    <li>python38Packages.respx</li>    <li>python38Packages.sanic</li>    <li>python38Packages.sanic-auth</li>    <li>python38Packages.sanic-testing</li>    <li>python38Packages.sunpy</li>    <li>python38Packages.teslajsonpy</li>    <li>python38Packages.zeep</li>    <li>python39Packages.PyRMVtransport</li>    <li>python39Packages.anyio</li>    <li>python39Packages.authcaptureproxy</li>    <li>python39Packages.axis</li>    <li>python39Packages.datasette</li>    <li>python39Packages.denonavr</li>    <li>python39Packages.dependency-injector</li>    <li>python39Packages.elmax</li>    <li>python39Packages.entrance</li>    <li>python39Packages.entrance-with-router-features</li>    <li>python39Packages.envoy-reader</li>    <li>python39Packages.fastapi</li>    <li>python39Packages.ha-philipsjs</li>    <li>python39Packages.httpcore</li>    <li>python39Packages.httpx</li>    <li>python39Packages.ipfshttpclient</li>    <li>python39Packages.ircrobots</li>    <li>python39Packages.ismartgate</li>    <li>python39Packages.json-logging</li>    <li>python39Packages.jupyter_server</li>    <li>python39Packages.jupyterlab</li>    <li>python39Packages.jupyterlab_server</li>    <li>python39Packages.jupytext</li>    <li>python39Packages.nbclassic</li>    <li>python39Packages.pylitterbot</li>    <li>python39Packages.pytest-httpx</li>    <li>python39Packages.pytest-sanic</li>    <li>python39Packages.respx</li>    <li>python39Packages.sanic</li>    <li>python39Packages.sanic-auth</li>    <li>python39Packages.sanic-testing</li>    <li>python39Packages.sunpy</li>    <li>python39Packages.teslajsonpy</li>    <li>python39Packages.zeep</li>  </ul></details>

**Pull request merged**
