### PR TITLE
nixos/xone: fixed a typo in the option description

### PR DESCRIPTION
**Pull request by swthorn**
## Description of changes

Fix a typo in the description of xone

## Things done

Fix a typo in the description of xone

### CODE REVIEW

**Review by JohnRTitor — CHANGES_REQUESTED** [review]
Thanks for your contribution to Nixpkgs.
As per [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md), we only accept pull request targeted to the master branch.

Please click "Edit" and change the base branch to `master`. Thanks.

Additionally PR title should be: `nixos/xone: fixed a typo in the option description`

Thanks!

**Review by JohnRTitor — APPROVED** [review]
LGTM

**Comment by h7x4** [comment]
Would you mind editing the commit message to match the PR description as well?

**Comment by JohnRTitor** [comment]
Yep, please do, not sure how did I miss that before approving

**Comment by Artturin** [comment]
merged via squash&merge which allows changing the commit msg

**Pull request merged**
