### PR TITLE
treewide: remove file-wide `with lib;` uses in nixos/modules/programs

### PR DESCRIPTION
**Pull request by acid-bong**
## Description of changes
Following #208242.

~~Additionally fixed a small error in a recently merged module for `soundmodem`.~~
That one was separated into #304811 and merged.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Hum, that's nice and scary!

about soundmodem, put ie in a separate PR.

**Comment by acid-bong** [comment]
And now at least 3 checks fail (I think borgo will fail too)

**Comment by acid-bong** [comment]
Anyway, I'm rebasing this one on top of #304811, let that one be merged first

**Comment by acid-bong** [comment]
Rebased it back on top of `master`, now it's a single-commit PR again

**Comment by acid-bong** [comment]
@wegank merge conflicts resolved

**Comment by flokli** [comment]
This broke zsh, which probably wasn't part of a VM test. Fixed in https://github.com/NixOS/nixpkgs/pull/311292.

**Comment by wegank** [comment]
> Hum, that's nice and scary!

Very true indeed. Thanks, @flokli!

**Comment by Aleksanaa** [comment]
Sorry I may have missed a bit of context, but how did you handle these changes? Completely rely on visual recognition and manual modification, or scripting nix evaluator? Did you do anything to ensure the correctness of the changes?

**Comment by acid-bong** [comment]
@Aleksanaa all edits are done manually (with some macros in vim tho), but i did check it with customized NIX_PATH. I admit that i didn't check it after every edit

**Pull request merged**
