### PR TITLE
black: 18.6b4 -> 18.9b0

### PR DESCRIPTION
**Pull request by pmiddend**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build python36Packages.black python36Packages.pyls-black

**Review by xeji — CHANGES_REQUESTED** [review]
Please fix the test failures.

**Comment by pmiddend** [comment]
Hmm, there is already a PR for pyls-black that fixes the issue. Is there an easy way to incorporate this PR (consisting of three commits apparently) into pyls-black?

**Comment by pmiddend** [comment]
See https://github.com/rupert/pyls-black/pull/6

**Comment by xeji** [comment]
You could `fetchpatch` the commits from the upstream PR author's fork. But I'm not sure it's worth the effort. I would just temporarily disable tests  with `doCheck = false;` with a comment pointing to the upstream PR and a reminder to remove this on the next version bump.

**Comment by pmiddend** [comment]
@xeji Okay, I did that. Seems to work.

**Comment by xeji** [comment]
@GrahamcOfBorg build python36Packages.black python36Packages.pyls-black

**Comment by xeji** [comment]
There still is a test failure for `black` on darwin, but that failure was there before this PR: https://hydra.nixos.org/job/nixpkgs/trunk/python36Packages.black.x86_64-darwin , so let's ignore it for now.

**Review by xeji — APPROVED** [review]

**Pull request merged**
