### PR TITLE
python3.pkgs: fix splice through unsupported hosts 

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

Previously, unless unsupported platforms were allowed, the following would fail to evaluate (from an "x86_64-linux" system):

```nix
pkgsCross.x86_64-freebsd.__splicedPackages.docutils.__spliced.buildHost
```

It shouldn't have, because the `buildHost` package ends up being for Linux.  This broke evaluation of e.g. `pkgsCross.x86_64-freebsd.libdrm`, because it has `docutils` in `nativeBuildInputs`.  `mkDerivation` would try to go through `__spliced.buildHost` on docutils to get to the Linux version, but the check in `ensurePythonModules` would kick in first, triggering the meta check because of the equality check in the implementation of `hasPythonModule`, which would fail because Python is not marked as supported on FreeBSD in Nixpkgs at the moment.  Thus, even though they're not supposed to be, the meta checks would be triggered even though the only attribute being accessed on the unsupported derivation was `__spliced`.

We can fix this by using the same mechanism used to implement the meta checks themselves: `lib.extendDerivation`.  Now, attempting to access `drvPath` or `outPath` on an attribute that fails the validity check will produce the same error as before, but other accesses will be allowed through, fixing splicing.

I've tested evaluation of packages that pass and fail the validity check, and confirmed that the behaviour is still correct.

While I was here, I also simplified the logic in the validity check.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
> but the check in `ensurePythonModules` would kick in first,

https://github.com/NixOS/nixpkgs/blob/de836e3ecd20d3388b488d50933fa19272fa7c53/pkgs/development/interpreters/python/default.nix#L34-L41

> triggering the meta check because of the equality check in the implementation of `hasPythonModule`

https://github.com/NixOS/nixpkgs/blob/76be8d2d04a00e5e2df6fa147dfc4797874edc97/pkgs/development/interpreters/python/python-packages-base.nix#L45

I would love to know why that equality check is there.

Also, testing meta-check-failing derivations for equality against each other shouldn't `throw`, should it?

> the meta checks would be triggered even though the only attribute being accessed on the unsupported derivation was `__spliced`.

Yeah they should only be triggered upon access to `(builtins.derivation drvAttrs).drvPath`, since Nix equality among derivations is implemented by comparing `.outPath`.

**Review by ghost — APPROVED** [review]
LGTM

See also:

- [ ] https://github.com/NixOS/nixpkgs/pull/213096

... which will prevent problems like this in the future.

**Comment by FRidh** [comment]
> I would love to know why that equality check is there.

To avoid mixing Python packages of different interpreter versions.

Applications don't provide a module and so we stop recursing. We also stop recursing when we encounter a Python module but it is not for the same interpreter. The idea here is that, when we would use this with `NIX_PYTHONPATH`, we can have different Python versions in the same build not affecting one another.

**Comment by FRidh** [comment]
> We can fix this by using the same mechanism used to implement the meta checks themselves: `lib.extendDerivation`. Now, attempting to access `drvPath` or `outPath` on an attribute that fails the validity check will produce the same error as before, but other accesses will be allowed through, fixing splicing.

Interesting trick. Could this also fix overriding a package that has `disabled = true` in `pkgs/development/interpreters/python/mk-python-derivation.nix`?

**Review by FRidh — APPROVED** [review]

**Comment by alyssais** [comment]
> Interesting trick. Could this also fix overriding a package that has `disabled = true` in `pkgs/development/interpreters/python/mk-python-derivation.nix`?

Yes, I think it could!

**Pull request merged**
