### PR TITLE
gstreamer: re-enable auto_features

### PR DESCRIPTION
**Pull request by LnL7**
###### Things done

/cc @jtojnar 

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Can you also move the `libunwind` back to `isLinux` section.
And drop it from legacy `gstreamer`.

**Comment by jtojnar** [comment]
And also please use the proper `gst_all_1.gstreamer` commit tag so that borg can build it.

**Review by jtojnar — APPROVED** [review]
yeah, this should do it.

**Comment by jtojnar** [comment]
Let’s see if it fixes https://github.com/NixOS/nixpkgs/issues/63635

@GrahamcOfBorg build gst_all_1.gst-plugins-base

**Comment by LnL7** [comment]
That restores the linux hash to what it was before on master.

**Comment by jtojnar** [comment]
While at it, could you also restore pkgs/development/libraries/gstreamer/legacy/gstreamer/default.nix?

**Comment by LnL7** [comment]
That fix works because it doesn't use meson to build.

**Comment by jtojnar** [comment]
Is that needed though?

**Comment by jtojnar** [comment]
It is not mentioned in the legacy gstreamer build log and is not part of its closure either.

**Review by vcunat — APPROVED** [review]
OK, let's fix this regression fast.

**Comment by vcunat** [comment]
The `unwind` for legacy doesn't seem critical, so I didn't want to wait for that.

**Pull request merged**
