### PR TITLE
bundler: 1.14.6 -> 1.16.1

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
cc @zimbatm @manveru

**Comment by Mic92** [comment]
more rebuilds then I initially expected.

**Comment by Mic92** [comment]
@vcunat you still would not call this a mass rebuild, yes?

**Comment by Mic92** [comment]
changelog: https://github.com/bundler/bundler/blob/master/CHANGELOG.md

**Comment by Mic92** [comment]
@GrahamcOfBorg build r10k

**Comment by Mic92** [comment]
@GrahamcOfBorg build gitlab

**Comment by vcunat** [comment]
Probably.  Depends on the exact number.  IIRC we have ruby used as a build-time tool somewhere deep.

**Comment by Mic92** [comment]
This update is critical and should be backported. Ruby 2.4.0 has a different bundler version then our bundler package. This breaks applications like vagrant.

**Comment by Mic92** [comment]
In case I forget please add this to 18.03.

**Comment by Mic92** [comment]
Reverted again `97fff8d8065e79e89972bc644d88787d7d37edf9` because this is known to break gitlab: https://github.com/NixOS/nixpkgs/pull/30881#issuecomment-340825319

**Pull request merged**
