### PR TITLE
Osmocom: network in the box

### PR DESCRIPTION
**Pull request by Janik-Haag**
###### Description of changes

https://osmocom.org/projects/cellular-infrastructure/wiki/Osmocom_Network_In_The_Box
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Lassulus** [comment]
uh pretty nice
getting an error though:

```
error: attribute 'libosmo-netif' already defined at /home/lass/.cache/nixpkgs-review/pr-227131/nixpkgs/pkgs/top-level/all-packages.nix:22169:3

       at /home/lass/.cache/nixpkgs-review/pr-227131/nixpkgs/pkgs/top-level/all-packages.nix:22175:3:

        22174|
        22175|   libosmo-netif = callPackage ../development/libraries/libosmo-netif { };
             |   ^
        22176|
```

**Comment by Janik-Haag** [comment]
Hm very interesting:
grepping through nixpkgs it's only defined once:
```
rg libosmo-netif                           
pkgs/top-level/all-packages.nix
22009:  libosmo-netif = callPackage ../servers/osmocom/libosmo-netif { };

pkgs/servers/osmocom/osmo-hnbgw/default.nix
8:, libosmo-netif
43:    libosmo-netif

pkgs/servers/osmocom/osmo-msc/default.nix
9:, libosmo-netif
45:    libosmo-netif

pkgs/servers/osmocom/osmo-bsc/default.nix
8:, libosmo-netif
41:    libosmo-netif

pkgs/servers/osmocom/osmo-iuh/default.nix
8:, libosmo-netif
48:    libosmo-netif

pkgs/servers/osmocom/libosmo-sccp/default.nix
8:, libosmo-netif
36:    libosmo-netif

pkgs/servers/osmocom/osmo-bts/default.nix
8:, libosmo-netif
39:    libosmo-netif

pkgs/servers/osmocom/osmo-hnodeb/default.nix
10:, libosmo-netif
45:    libosmo-netif

pkgs/servers/osmocom/osmo-mgw/default.nix
7:, libosmo-netif
38:    libosmo-netif

pkgs/servers/osmocom/osmo-sgsn/default.nix
8:, libosmo-netif
42:    libosmo-netif

pkgs/servers/osmocom/libosmo-netif/default.nix
11:  pname = "libosmo-netif";
16:    repo = "libosmo-netif";
39:    homepage = "https://osmocom.org/projects/libosmo-netif/wiki";
```
but for me it throws the same error when running `nixpkgs-review pr 227131` but `nix-build -A libosmo-netif` works fine and ofborg build also seems to have worked.

**Review by Lassulus — APPROVED** [review]
although nix-review fails for some reason (maybe @Mic92 knows why), all packages build successfully.

**Comment by Lassulus** [comment]
ah we broke nixpkgs eval, the conflict actually comes from this PR already packaging some of the libs and causing a conflict: https://github.com/NixOS/nixpkgs/pull/229369

**Comment by Janik-Haag** [comment]
What should we do to fix it revert this PR, rebase and then remove the duplicate libs?

**Pull request merged**
