### PR TITLE
Improvements for Prosody

### PR DESCRIPTION
**Pull request by sshisk**
###### Motivation for this change

Hi! This is mostly new lua modules for Prosody, for example luadbi, but additionally some changes in NixOS module. It was tested for several months.

###### Things done

Please check what applies. Note that these are not hard requirements but mereley serve as information for reviewers.

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by fpletz — APPROVED** [review]
Code looks fine to me. Thanks especially for splitting the changes nicely into different commits!

I'm going to test these changes why my current prosody installations.

**Comment by sshisk** [comment]
I have fixed invalid argument name for DBI support, `withDBI`, and rebased. Please tell me if I should have pushed it as an extra commit...

**Comment by fpletz** [comment]
That's fine! Just rebase your changes into the appropriate commits like you did. Thanks!

**Comment by florianjacob** [comment]
I'm in the process of moving my prosody server to NixOS, and this looks exactly like what I need. 😄 

@sshisk Do you think you can resolve the current conflicts to get this merged?
If you don't have the time, maybe I can take this over.

**Comment by florianjacob** [comment]
Rebased and conflict-resolved version at https://github.com/NixOS/nixpkgs/pull/31006

**Comment by fpletz** [comment]
Thanks a lot @florianjacob! And @sshisk of course! Let's continue in #31006.

**Pull request closed without merging**
