### PR TITLE
pythonPackages.assimulo: init at 3.0 [WIP] [Help needed]

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

Add Assimulo package: https://jmodelica.org/assimulo/

**EDIT: Ready for review!**

~~This is still work in progress.~~ ~~The build fails at the very end:~~ ~~**EDIT: fixed this error, now tests failing**~~

```
...
removing build/bdist.linux-x86_64/wheel
sortvarnames: failed to compute dependencies because of cyclic dependencies between am, n
sortvarnames: failed to compute dependencies because of cyclic dependencies between am, n
installing
/nix/store/yax21ms90cwr2l4rygd60wfbpfwg5hip-stdenv-linux/setup: line 1307: pushd: dist: No such file or directory
note: keeping build directory '/tmp/nix-build-python3.7-assimulo-3.0.drv-5'
builder for '/nix/store/3jj55c5kdgnsnd4lj4rpmfpkq19gh6cw-python3.7-assimulo-3.0.drv' failed with exit code 1
error: build of '/nix/store/3jj55c5kdgnsnd4lj4rpmfpkq19gh6cw-python3.7-assimulo-3.0.drv' failed
```

~~So apparently `dist` directory is missing for some reason. The build phase doesn't create it as it should, I suppose. Any help would be great!~~

~~Full log: [assimulo.log](https://github.com/NixOS/nixpkgs/files/2842081/assimulo.log)~~

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jluttine** [comment]
For some reason I don't know, `dist` directory seems to be under `build`. So I'll just move it from there. No idea why this is happening but it seems to solve this issue I'm having.

Now it fails on check phase, but I'll continue on that.

**Comment by jluttine** [comment]
Fixed the tests by explicitly going into the correct tests directory and running nosetests there.

This is now building ok and nox review passes. Ready for review and merging. FYI, @FRidh

**Comment by costrouc** [comment]
I think that you will want to build with openblas instead of liblapack and blas. The performance will be much better and this is the pattern that many other packages follow.

**Comment by jluttine** [comment]
Yeah, I would. However, I had a few issues with that when I tried:
- Assimulo wants static versions of the libraries. I wasn't sure how to get a static version of openblas.
- Assimulo expects to find `liblapack.a`, that's hard-coded, as far as I can see. Perhaps removing that with a patch could help.
Given both of these issues, I thought why not just use libblas.a and liblapack.a as they are available. Is there something wrong with them?

**Comment by jluttine** [comment]
Not sure if I could patch it so that it'd use the shared libraries. Could try that if it sounds like something that could potentially work.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by FRidh** [comment]
Nothing happening so closing.

**Pull request closed without merging**
