### PR TITLE
plymouth: 23.360.11 -> 24.004.60

### LINKED ISSUE #280910: Plymouth suddenly omits key-presses on password entry
### Describe the bug
For a few days, when booting my amd computer with plymouth enabled I can't enter my passphrase anymore.
Pushing keys multiple times eventually end up in one key-press being accepted. Booting with `nosplash` instead of `splash` suddenly has no more issues with keyboard entries.

### Steps To Reproduce

NixOS Unstable

1. Setting to `initrd.systemd.enable = true;` and `plymouth.enable = true;`
```nix
  boot = {
	  consoleLogLevel = 0;
	  initrd.compressor = "zstd";
          initrd.systemd = {
            enable = true;
            network.enable = true;
          };
          loader.systemd-boot = { 
            enable = true;
            configurationLimit = 32;
          };
	  initrd.verbose = false;
	  kernelParams = [ "udev.log_level=3" ];
	  plymouth.enable = true;
	  plymouth.theme = "solar";
  };
```

2. Rebooting with a LUKS/ZFS Passphrase
3. Key-presses are omitted

### Expected behavior
Every key I hit will be used.

@cillianderoiste @dasj19 @lilyinstarlight ?@K900? 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.10, NixOS, 24.05 (Uakari), 24.05pre567746.317484b1ead8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(pl): `"nixos"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by arthsmn**
## Description of changes

Closes: https://github.com/NixOS/nixpkgs/issues/280910
Changelog: https://gitlab.freedesktop.org/plymouth/plymouth/-/releases/24.004.60

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by jtojnar** [comment]
Looking at the diff, the only weird thing I noticed is the [call to fontconfig on FHS path](https://gitlab.freedesktop.org/plymouth/plymouth/-/compare/23.360.11...24.004.60?from_project_id=837&straight=false#1c7539d88a4c0699a1a29986f5d5fb6b693fb0f4) but that did not come from this release:

- introduced label-ft plugin: https://gitlab.freedesktop.org/plymouth/plymouth/-/commit/58f4d4f47c52a64c8dbb3cd7257d15f78c2227f4
- added monospace font to label-freetype: https://gitlab.freedesktop.org/plymouth/plymouth/-/commit/cc5e07c6d0278c14fff2fde5b9cc63913419810e

**Comment by arthsmn** [comment]
@jtojnar I made a patch that I think solves the problem, although I'm not that experienced.

**Comment by SuperSandro2000** [comment]
Can we merge this? Without it plymouth is unusable for me.

**Comment by norpol** [comment]
Thank you for the quick action! <3

**Pull request merged**
