### PR TITLE
Bazel: wrap to keep java available at runtime

### PR DESCRIPTION
**Pull request by benley**
###### Motivation for this change

Bazel can't start up unless javac is findable in $PATH or JAVA_HOME is set.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by izuk — APPROVED** [review]

**Review by izuk — APPROVED** [review]

**Comment by layus** [comment]
I also have issues starting when there are no c compiler installed. bazel requires me to add CC=/dev/null to start, even when there are no c/cpp files in the project. Do you observe the same behavior ?

**Comment by benley** [comment]
Yeah, I have run into that too.  I've been doing `nix-shell -p gcc --run "bazel build etc etc etc"` as a temporary workaround.

**Comment by izuk** [comment]
@layus, @benley can you point to a test case for the gcc behavior?

**Comment by layus** [comment]
Just try to run `bazel build sth`. Cannot reproduce. Maybe bazel keeps a link to gcc in its archive and fail when we gc that version of gcc ? I should investigate more. Unable to reproduce at this time. Strange...

**Comment by IreneKnapp** [comment]
Bazel keeps an entire *copy* of gcc in its archive. Also of javac. It's necessary for any packaging solution to ensure that these copies will work as expected, which means making sure the paths they hardcode to their dependencies are the same at run time as they were at build time.

**Comment by benley** [comment]
Bazel still requires an external JVM in order to launch itself though, right?

**Comment by benley** [comment]
But in any case - if bazel copies gcc and java into itself, those will need to be kept as propagated nix dependencies too.

**Comment by IreneKnapp** [comment]
I'm not sure whether it requires an external JVM to launch, or not. I could believe that it doesn't. But as you say, they need to be dependencies either way.

**Pull request merged**
