### PR TITLE
meguca: 2018-05-26 -> 2018-06-11

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
Update meguca, nodePackages: meguca, and easyjson.
Fix password being shown by top.
Fix database permission issue.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Chiiruno** [comment]
Don't pull yet please, I have to fiddle with the node package a little.

**Comment by Chiiruno** [comment]
Ok, ready for merging again.

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build meguca

**Comment by Chiiruno** [comment]
Did it time out of x86_64-linux?
That should have compiled.

**Comment by Chiiruno** [comment]
I guess don't merge in the meantime, I'm going to submit another commit within ~4 days.

**Comment by Chiiruno** [comment]
@yegortimoshenko Should be ready for building and merging again.
I hope you don't mind the ping.

**Comment by Chiiruno** [comment]
cc @matthewbauer @Mic92 @yegortimoshenko

**Comment by Mic92** [comment]
@GrahamcOfBorg build meguca

**Comment by Mic92** [comment]
Did macOS worked before?

**Comment by Chiiruno** [comment]
@Mic92 Yes, however I think the problem may be that I have to add in `libcxx` for Darwin now, for some reason.

**Comment by Mic92** [comment]
@GrahamcOfBorg build meguca

**Comment by Mic92** [comment]
I think it would be acceptable to disable macOS for the time being until we have a real macOS maintainer for that package.

**Comment by Chiiruno** [comment]
I'll just disable building the C++ client, maybe upstream hasn't tested this emscripten code with MacOS.

**Comment by Chiiruno** [comment]
@Mic92 Should be ready for building and merging.

**Comment by Mic92** [comment]
@GrahamcOfBorg build meguca

**Comment by Mic92** [comment]
Does the packages make any sense, if those components are not build on macOS? I would rather ship no packages then a useless one.

**Pull request merged**
