### PR TITLE
python-packages.nix: sort

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
really didn't like that the package set was so disorganized.

Also gets rid of the "why should I sort new packages in an unsorted list " excuse :)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
```
anonymous function at /home/freddy/Code/libraries/nixpkgs/pkgs/applications/video/jellyfin-mpv-shim/default.nix:1:1 called without required argument 'tkinter'
```

Checked with
```
#!/bin/sh

echo "Checking evaluation before committing";
exec nix-env -f . -qaP --meta --json --drv-path --show-trace >/dev/null
```

**Comment by jonringer** [comment]
looks like eval is fixed, and I'm able to build most packages

**Comment by FRidh** [comment]
```
Nothing changed
https://github.com/NixOS/nixpkgs/pull/96850
```

**Comment by FRidh** [comment]
Thanks. Now we can rule with a iron fist again! :stuck_out_tongue:

**Comment by jonringer** [comment]
Had to run the ofborg eval locally to find other other missing packages. I guess `nix-env --json` doesn't deeply evaluate anything.

**Pull request merged**
