### PR TITLE
goxlr-utility: 1.1.1-unstable-2024-08-06 -> 1.1.4

### LINKED ISSUE #352352: Update request: goxlr-utility 1.1.1-unstable-2024-08-06 → 1.1.4
- Package name: goxlr-utility
- Latest released version: 1.1.4

- Current version on the unstable channel: 1.1.1-unstable-2024-08-06
- Current version on the stable/release channel: 1.1.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@errnoh

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by errnoh**
fixes #352352 by updating the package to latest release

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by errnoh** [comment]
@Zombiefleischer can you test that the build works fine for you and add an approval if so :)

**Comment by Zombiefleischer** [comment]
> @Zombiefleischer can you test that the build works fine for you and add an approval if so :)

How can I do this?

**Comment by errnoh** [comment]
Not sure if there's a single perfect answer to that, but here are some options:

1. https://github.com/Mic92/nixpkgs-review?tab=readme-ov-file#usage
2. checkout the branch yourself and do `nix-build -A goxlr-utility`, this results in `./result` that contains the binaries.
3. add it to your `/etc/nixos`, for example by creating `pkgs/goxlr-utility` subdirectory where you have the package and cargo lock file and doing something like this:

```
  services.goxlr-utility = {
    enable = true;
    package = pkgs.callPackage pkgs/goxlr-utility {
      speechd-minimal = pkgs.unstable.speechd-minimal;
      rustPlatform = pkgs.unstable.rustPlatform;
    };
  };
```

(the `speechd-minimal` and `rustPlatform` parameters are only needed in the case that your setup uses NixOS 24.05 in which case `speechd-minimal` is not yet included and `rust` is too old version to build current `goxlr-utility`. The syntax `pkgs.unstable` is not default though and requires additional setup or some other way to refer to unstable branch of nixpkgs)

Options 1 & 2 result only in the binaries and you'd need to kill `goxlr-daemon` and run the compiled one instead. Option 3 also requires killing `goxlr-daemon` but launching `goxlr-launcher` would then start the new daemon properly (as would booting the machine).

**Comment by Zombiefleischer** [comment]
Looks good to me. Approved 👍

**Comment by errnoh** [comment]
@Zombiefleischer sorry to bother you more, but if possible add an approval through the `Files changed` tab `Review Changes` button. That [helps committers to see that PR is already tested and makes it more likely to get merged faster](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#how-can-i-get-a-committer-to-look-at-my-pr)

**Review by Zombiefleischer — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by errnoh** [comment]
@wegank new push with only two changes:
- rebased to current master
- fix the merge conflict caused by path that was changed in 571c71e6f73af34a229414f51585738894211408 (i.e. just pointed the changes to current location instead of old one)

**Comment by errnoh** [comment]
@wegank I take it that the above label change is a request to re-confirm approval from @SuperSandro2000 after the latest commit?

**Pull request merged**
