### PR TITLE
aiosql: 10.1 → 10.2, run more tests, remove pg8000 from propagatedBuildInputs

### PR DESCRIPTION
**Pull request by mitya57**
## Description of changes

- Updated from 10.1 to 10.2. See [diff](https://github.com/nackjicholson/aiosql/compare/refs/tags/10.1...10.2) and [10.2 changelog](https://github.com/nackjicholson/aiosql/releases/tag/10.2).
- Made PostgreSQL tests actually. Previously they were skipped because pg8000 was present, but pytest-postgresql was missing. Also, while I was at it, enabled testing with two more backends: psycopg2 and psycopg3.
- Moved pg8000 from propagatedBuildInputs to checkInputs. Like any other backend, it is an optional dependency and does not need to be propagated. Cc @fabaff — if you had a reason to put it there, please let me know.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
> if you had a reason to put it there, please let me know.

I think the reason was that the `pg8000` adapter is doing thing differently than the other adapters. `pg8000` is imported (https://github.com/nackjicholson/aiosql/blob/10.1/aiosql/adapters/pg8000.py#L6), thus the placement in `propagatedBuildInputs`.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 293718` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>oterm</li>
    <li>oterm.dist</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python311Packages.aiosql</li>
    <li>python311Packages.aiosql.dist</li>
    <li>python311Packages.aiosql.doc</li>
  </ul>
</details>

**Comment by mitya57** [comment]
> I think the reason was that the pg8000 adapter is doing thing differently than the other adapters. pg8000 is imported (https://github.com/nackjicholson/aiosql/blob/10.1/aiosql/adapters/pg8000.py#L6), thus the placement in propagatedBuildInputs.

Thank you for the reference. However, it is imported not at the top level, but inside a function. This means the import will happen only if you explicitly selected the pg8000 backend. And if you did that, you probably have it available anyway.

I think putting pg8000 in propagatedBuildInputs is wrong, since it will make it a dependency of every package using aiosql, and not every package needs that backend.

> 2 packages failed to build:
> * oterm
> * oterm.dist

oterm fails to build with this error:

```
Checking runtime dependencies for oterm-0.1.22-py3-none-any.whl
  - aiosql<10.0,>=9.2 not satisfied by version 10.1
```

There are no backwards-incompatible changes in aiosql 10.0, despite the major version bump. Will it work if I patch that dependency in this PR?

**Comment by fabaff** [comment]
> And if you did that, you probably have it available anyway.

Fair enough. 

> Will it work if I patch that dependency in this PR?

It should. GIve it a try with `pythonRelaxDepsHook`.

**Comment by mitya57** [comment]
> It should. Give it a try with pythonRelaxDepsHook.

Done.

**Pull request closed without merging**
