### PR TITLE
haskellPackages.hnix: unbreak

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

Get hnix working on haskell-updates again. See commit messages.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
Another package that definitely should have a maintainer.

**Comment by sorki** [comment]
It is maintained by couple of people already - one reason I've asked if multiple maintainers per package are allowed but this one (and related) could possibly have @haskell-nix listed as a maintainer (which I'm intentionally pinging here to see who actually gets the ping, sorry for the noise).

**Comment by maralorn** [comment]
Oh, I am sorry. I take that back. I thought it had been broken for a while, but it only broke last night. So there wasn‘t even a maintainer ping yet.

**Comment by sternenseemann** [comment]
ping @NixOS/haskell are you guys happy with this direction? Alternatively we *could* override `relude` and `semialign` hnix takes to newer versions, but I'm not sure if that could cause trouble with propagation.

**Comment by maralorn** [comment]
I share your concern that it will be annoying for downstream users if we override.

**Comment by Anton-Latukha** [comment]
:partying_face: Arrived too late to the party.

@sternenseemann Thanks.


https://github.com/NixOS/nixpkgs/pull/122706#issuecomment-840447881 & https://github.com/NixOS/nixpkgs/pull/122706#issuecomment-840493972 It is interesting, since my main strategy always to go to use overrides. See it as design & package stores misalignment & that out of Stackage overrides can be handled is a automatic manner someday.

But this sort of backporting patching seems interesting.

> I share your concern that it will be annoying for downstream users if we override.

I do not understand why. Please, @maralorn, can you help understand why?

**Comment by maralorn** [comment]
Not users using the hnix binary.

But users who try to build a project that relies on two different libraries, where both use different semialign versions with nix.

In general overrides are not an issue for leaf packages but tend to be problematic for packages which get used as libraries.

After thinking about this I realize that the issue is not as big as I thought. a) when you develop on a project with cabal and install hnix and e.g. relude (with the different version) via your nix-shell cabal will still succeed in finding a working buildplin and b) even better, I think if you build a package with nix that takes relude and hnix as direct dependencies it will, I think, just build the package with the relude passed in via hnix and ignore the different relude passed in directly. It will only be a problem if you really try to combine two packages which have already been compiled with different relude or semialign versions.

**Comment by Anton-Latukha** [comment]
Yes, the question of what deps expose in the env is important. But as we see, indeed - only direct dependencies get exposed & Nix would hide all others.
So far, I do not know about cases or can not imagine how packages (not even module level) compiled with different dependency versions & hard linked by Nix, how those can influence dependent packages that use other hard-linked library.

The main difference between library branches in Haskell is difference in API interface. But that is fully covered by the strong type system & the CPP preprocessor. So this case of compatibility fully is covered by Haskell.

If there can be real problems of misalignment between versions during compilations - then that issue is not raised only for Haskell, as then it touches Nix design & Nixpkgs practise as a whole.

Overall, I can imagine there could be some optimization limitations, if GHC for example `V1Lib.func ... V2Lib.func`, and because they implemented differently - it can not optimize them. But as I understand GHC would use/recieve dependencies code already in precompiled form and library functions used generally would not propagate through transitive package.

So for me it is hard to imagine the case when Haskell library dependency versions metter much. My knowledge of GHC is limited, and there can be some details & cases of such.

While when some out-of-band Nixpkgs package versions are removed - maintainer or itself checks what packages use it, or Nix language explicitly notifies maintainer to remove according overrides, which helps with in-time maintainence.

But I would consider patching as maybe a better practice and would look at the practice of its application. But patches can be left beyound their cause and intruduce side-effects, & in time people can loose the track of causes of why it is there. As I see patches are still not handled structurally, no RFC or functions to help with their maintenance.

Thou, I still evaluating the approaches.

**Comment by sternenseemann** [comment]
The core problem is propagation which is required for haskellPackages. If we override a package which is not just a leaf package to use a different version of a package from what we use in our “blessed” package set then it is possible that propagation causes two different version of the same package appear in the dependency tree of a package.

This is something cabal / GHC doesn't deal with well, so we try to avoid it. In fact the builder we use forbids it:

<https://github.com/NixOS/nixpkgs/blob/65a9923bbb94e4da656eb63f88f3a378be232e02/pkgs/development/haskell-modules/generic-builder.nix#L427-L432>

**Pull request merged**
