### PR TITLE
opensc: take over maintainership

### PR DESCRIPTION
**Pull request by michaeladler**
###### Motivation for this change

@erictapen has [asked me to take over maintainership](https://github.com/NixOS/nixpkgs/pull/133357). I understood that Eric  wants to hand over the maintainership which is why I have omitted him from the maintainer list. If you want to remain in the maintainer list, just let me know and I'll gladly update the PR.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
The maintainers-list edit should be in a separate commit

**Comment by michaeladler** [comment]
@Artturin No problem, I've updated the PR accordingly

**Review by SuperSandro2000 — APPROVED** [review]

**Review by erictapen — APPROVED** [review]
Yes, that's what I meant. You're welcome to take maintainership from me, as I don't even have opensc in my system closure anymore.

Regarding my name and pronouns: I actually never was called Eric at any point in my life, erictapen is just an anagram of a name I used when playing videogames in my youth. But I totally get how you parsed it as a name/surname pair ;)

My real name is Kerstin (she/her).

Thanks for taking maintainership!

**Comment by michaeladler** [comment]
@erictapen Oh, apologies! Nice to meet you Kerstin :)

**Pull request merged**
