### PR TITLE
rocmPackages: use CMake 3.9.2 when building clr

### LINKED ISSUE #305641: Build failure: rocmPackages, rocmPackages_5
### Steps To Reproduce

The build for a lot of ROCm components broke with 6083fb0a158607ce76c1cc0849e89eb35d66cfa7, which updated CMake from 3.29.0 to 3.29.1, basically breaking all of ROCm.
This commit was merged via https://github.com/NixOS/nixpkgs/pull/298979 and recently made its way from staging into unstable in the last few days.

1. `nix build nixpkgs/716b484faececc3cd4570cc612ec9e927427d682#rocmPackages.rccl`

### Build log

The builds for a number of ROCm components now fail with error messages like the following:

```
CMake Error in library/CMakeLists.txt:
  Imported target "hip::device" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

### Additional context

This is possible related to how ROCm uses `CMAKE_INSTALL_<dir>` of CMake incorrectly.
See https://github.com/NixOS/nixpkgs/pull/197838#discussion_r1006537286 and https://github.com/ROCm/rocm-cmake/issues/121 which is linked in that comment thread.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by GZGavinZhao**
Fixes #305641.

## Description of changes

Ensure CMake 3.9.2 is used to build clr, both for ROCm 5 and 6. The changes can be reverted once CMake 3.9.2 lands in unstable, if desired.

I have tested that `rocsparse` (5 and 6), `rocfft` (6), and `composable_kernel` (6) all build.

See #305641 for more details.

cc @mschwaig

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mschwaig — APPROVED** [review]
I have reviewed the code and it looks good to me.
The version hashes match the ones from the update to 3.9.2 at https://github.com/NixOS/nixpkgs/pull/304111, and I have tested that the downloads for the updated source work.

I'm a bit surprised it was really only necessary to change the CMake version used by `clr` and not anywhere else, but your testing seems to confirm that.

That's enough for me to approve this change.

I am currently still running `nixpkgs-review`, to check if this change fixes all of the broken packages, and confirm what you saw in your testing.

Since the build is broken on master anyways, if anyone decides they want to just merge this and not wait for `nixpkgs-review` to finish, go ahead.

**Comment by mschwaig** [comment]
Result of `nixpkgs-review pr 306375` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages marked as broken and skipped:</summary>
  <ul>
    <li>rocmPackages.llvm.flang</li>
    <li>rocmPackages.llvm.flang.doc</li>
    <li>rocmPackages.llvm.flang.info</li>
    <li>rocmPackages.llvm.flang.man</li>
    <li>rocmPackages.migraphx</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>rocmPackages_5.llvm.flang</li>
    <li>rocmPackages_5.llvm.flang.doc</li>
    <li>rocmPackages_5.llvm.flang.info</li>
    <li>rocmPackages_5.llvm.flang.man</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>rocmPackages_5.rocprofiler</li>
  </ul>
</details>
<details>
  <summary>82 packages built:</summary>
  <ul>
    <li>blender-hip</li>
    <li>magma (magma-hip ,magma_2_7_2)</li>
    <li>magma.test (magma-hip.test ,magma_2_7_2.test)</li>
    <li>magma_2_6_2</li>
    <li>magma_2_6_2.test</li>
    <li>opensyclWithRocm</li>
    <li>python311Packages.torchWithRocm</li>
    <li>python311Packages.torchWithRocm.cxxdev</li>
    <li>python311Packages.torchWithRocm.dev</li>
    <li>python311Packages.torchWithRocm.dist</li>
    <li>python311Packages.torchWithRocm.lib</li>
    <li>python312Packages.torchWithRocm</li>
    <li>python312Packages.torchWithRocm.cxxdev</li>
    <li>python312Packages.torchWithRocm.dev</li>
    <li>python312Packages.torchWithRocm.dist</li>
    <li>python312Packages.torchWithRocm.lib</li>
    <li>rocmPackages.clr</li>
    <li>rocmPackages.clr.icd</li>
    <li>rocmPackages.composable_kernel</li>
    <li>rocmPackages.hipblas</li>
    <li>rocmPackages.hipcub</li>
    <li>rocmPackages.hipfft</li>
    <li>rocmPackages.hiprand</li>
    <li>rocmPackages.hipsolver</li>
    <li>rocmPackages.hipsparse</li>
    <li>rocmPackages.llvm.mlir</li>
    <li>rocmPackages.miopen</li>
    <li>rocmPackages.rccl</li>
    <li>rocmPackages.rocalution</li>
    <li>rocmPackages.rocblas</li>
    <li>rocmPackages.rocfft</li>
    <li>rocmPackages.rocmlir</li>
    <li>rocmPackages.rocmlir-rock</li>
    <li>rocmPackages.rocmlir.external</li>
    <li>rocmPackages.rocprim</li>
    <li>rocmPackages.rocprofiler</li>
    <li>rocmPackages.rocr-debug-agent</li>
    <li>rocmPackages.rocrand</li>
    <li>rocmPackages.rocsolver</li>
    <li>rocmPackages.rocsparse</li>
    <li>rocmPackages.rocthrust</li>
    <li>rocmPackages.roctracer</li>
    <li>rocmPackages.rocwmma</li>
    <li>rocmPackages.rpp (rocmPackages.rpp-hip)</li>
    <li>rocmPackages.rpp-cpu</li>
    <li>rocmPackages.rpp-opencl</li>
    <li>rocmPackages_5.clr</li>
    <li>rocmPackages_5.clr.icd</li>
    <li>rocmPackages_5.composable_kernel</li>
    <li>rocmPackages_5.hipblas</li>
    <li>rocmPackages_5.hipcub</li>
    <li>rocmPackages_5.hipfft</li>
    <li>rocmPackages_5.hiprand</li>
    <li>rocmPackages_5.hipsolver</li>
    <li>rocmPackages_5.hipsparse</li>
    <li>rocmPackages_5.llvm.mlir</li>
    <li>rocmPackages_5.migraphx</li>
    <li>rocmPackages_5.miopen (rocmPackages_5.miopen-hip)</li>
    <li>rocmPackages_5.miopen-opencl</li>
    <li>rocmPackages_5.miopengemm</li>
    <li>rocmPackages_5.miopengemm.doc</li>
    <li>rocmPackages_5.mivisionx (rocmPackages_5.mivisionx-hip)</li>
    <li>rocmPackages_5.mivisionx-cpu</li>
    <li>rocmPackages_5.mivisionx-opencl</li>
    <li>rocmPackages_5.rccl</li>
    <li>rocmPackages_5.rocalution</li>
    <li>rocmPackages_5.rocblas</li>
    <li>rocmPackages_5.rocfft</li>
    <li>rocmPackages_5.rocmlir</li>
    <li>rocmPackages_5.rocmlir-rock</li>
    <li>rocmPackages_5.rocmlir.external</li>
    <li>rocmPackages_5.rocprim</li>
    <li>rocmPackages_5.rocr-debug-agent</li>
    <li>rocmPackages_5.rocsolver</li>
    <li>rocmPackages_5.rocsparse</li>
    <li>rocmPackages_5.rocthrust</li>
    <li>rocmPackages_5.roctracer</li>
    <li>rocmPackages_5.rocwmma</li>
    <li>rocmPackages_5.rpp (rocmPackages_5.rpp-hip)</li>
    <li>rocmPackages_5.rpp-cpu</li>
    <li>rocmPackages_5.rpp-opencl</li>
    <li>zluda</li>
  </ul>
</details>

I have some unknown issue with the `rocprofiler` being flaky locally, so this is as good as it gets. LGTM.

**Comment by mschwaig** [comment]
@ulrikstrid do you have time to take a look at this?

I just mentioned this PR on Discourse as well, to spread the review load a bit/in case you are busy.
Thanks for all the reviews.

**Review by ulrikstrid — APPROVED** [review]
I'm okay with this since it unblocks rocm until the cmake update has landed in master

**Comment by mschwaig** [comment]
> I'm okay with this since it unblocks rocm until the cmake update has landed in master

Great, thanks.

**Pull request merged**
