### PR TITLE
deno: 1.46.3 -> 2.0.0, deno_1: init at 1.46.3

### PR DESCRIPTION
**Pull request by 06kellyjac**
## Things done

Updates `deno` to v2
Adds a `deno_1` to hold v1 for now.
Depending on deno's support plans v1 may be removed just before the 24.11 release.

Updated the update scripts to use new Deno v2 interfaces and pull latest
toml dependency from jsr rather than the deno.land registry.

Note: need to double check it's ok to put `deno_1` inside `pkgs/by-name/deno/v1/package.nix`

Note: might wait a bit for the deno v2 announcement blog

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabianhjr** [comment]
> Note: might wait a bit for the deno v2 announcement blog

Even better, an announcement video/live 2 hrs ago! https://www.youtube.com/watch?v=d35SlRgVxT8

**Comment by fabianhjr** [comment]
```
fabian@fabian-desktop ~/D/O/n/main (main)> ls -1 pkgs/by-name/*/*/*/*.nix
pkgs/by-name/au/autoprefixer/tests/simple-execution.nix
pkgs/by-name/ch/changelog-d/tests/basic.nix
pkgs/by-name/cr/criterion/tests/001-version.nix
pkgs/by-name/cu/cue/tests/001-all-good.nix
pkgs/by-name/de/deno/tests/default.nix
pkgs/by-name/do/doctoc/test-generates-valid-markdown/default.nix
pkgs/by-name/el/elvish/tests/expect-version.nix
pkgs/by-name/fa/fastjar/tests/version-fastjar.nix
pkgs/by-name/fa/fastjar/tests/version-grepjar.nix
pkgs/by-name/ga/gancio/plugin-telegram-bridge/default.nix
pkgs/by-name/gn/gnome-bluetooth/1.0/default.nix
pkgs/by-name/gn/gnome-settings-daemon/43/default.nix
pkgs/by-name/ha/haunt/tests/001-test-version.nix
pkgs/by-name/im/implot/demos/default.nix
pkgs/by-name/in/inja/simple-cmake-test/default.nix
pkgs/by-name/in/installShellFiles/tests/install-bin-output.nix
pkgs/by-name/in/installShellFiles/tests/install-bin.nix
pkgs/by-name/in/installShellFiles/tests/install-completion-cmd.nix
pkgs/by-name/in/installShellFiles/tests/install-completion-fifo.nix
pkgs/by-name/in/installShellFiles/tests/install-completion-inference.nix
pkgs/by-name/in/installShellFiles/tests/install-completion-name.nix
pkgs/by-name/in/installShellFiles/tests/install-completion-output.nix
pkgs/by-name/in/installShellFiles/tests/install-completion.nix
pkgs/by-name/in/installShellFiles/tests/install-manpage-outputs.nix
pkgs/by-name/in/installShellFiles/tests/install-manpage.nix
pkgs/by-name/is/isabelle/components/default.nix
pkgs/by-name/is/isabelle/components/isabelle-linter.nix
pkgs/by-name/ki/kikit/solidpython/default.nix
pkgs/by-name/ma/maturin/pyo3-test/default.nix
pkgs/by-name/mi/micro/tests/version.nix
pkgs/by-name/mu/mutter/43/default.nix
pkgs/by-name/na/nanopb/test-message-with-annotations/default.nix
pkgs/by-name/na/nanopb/test-message-with-options/default.nix
pkgs/by-name/na/nanopb/test-simple-proto2/default.nix
pkgs/by-name/na/nanopb/test-simple-proto3/default.nix
pkgs/by-name/ne/needle/nix/default.nix
pkgs/by-name/np/npiet/tests/default.nix
pkgs/by-name/np/npiet/tests/run-test.nix
pkgs/by-name/pr/pretalx/plugins/downstream.nix
pkgs/by-name/pr/pretalx/plugins/media-ccc-de.nix
pkgs/by-name/pr/pretalx/plugins/pages.nix
pkgs/by-name/pr/pretalx/plugins/public-voting.nix
pkgs/by-name/pr/pretalx/plugins/venueless.nix
pkgs/by-name/pr/pretalx/plugins/vimeo.nix
pkgs/by-name/pr/pretalx/plugins/youtube.nix
pkgs/by-name/pr/pretix/plugins/default.nix
pkgs/by-name/pr/pretix/plugins/pages.nix
pkgs/by-name/pr/pretix/plugins/passbook.nix
pkgs/by-name/pr/pretix/plugins/reluctant-stripe.nix
pkgs/by-name/pr/pretix/plugins/stretchgoals.nix
pkgs/by-name/pr/pretix/plugins/zugferd.nix
pkgs/by-name/sa/sanjuuni/tests/run-on-nixos-artwork.nix
pkgs/by-name/sp/spigot/tests/approximation.nix
pkgs/by-name/uc/ucg/tests/simple.nix
pkgs/by-name/wi/windowmaker/dockapps/AlsaMixer-app.nix
pkgs/by-name/wi/windowmaker/dockapps/cputnik.nix
pkgs/by-name/wi/windowmaker/dockapps/default.nix
pkgs/by-name/wi/windowmaker/dockapps/libdockapp.nix
pkgs/by-name/wi/windowmaker/dockapps/wmCalClock.nix
pkgs/by-name/wi/windowmaker/dockapps/wmcube.nix
pkgs/by-name/wi/windowmaker/dockapps/wmsm-app.nix
pkgs/by-name/wi/windowmaker/dockapps/wmsystemtray.nix
pkgs/by-name/xu/xunit-viewer/test/example.nix
pkgs/by-name/zc/zchunk/tests/version.nix
fabian@fabian-desktop ~/D/O/n/main (main)> rg "by-name.*\{ \}" pkgs/top-level/all-packages.nix 
2135:  forgejo-lts = callPackage ../by-name/fo/forgejo/lts.nix { };
3132:  authentik-outposts = recurseIntoAttrs (callPackages ../by-name/au/authentik/outposts.nix { });
7941:  gnome-panel-with-modules = callPackage ../by-name/gn/gnome-panel/wrapper.nix { };
8651:  incus-lts = callPackage ../by-name/in/incus/lts.nix { };
10792:  sshd-openpgp-auth = callPackage ../by-name/ss/ssh-openpgp-auth/daemon.nix { };
19391:  vapoursynth-editor = libsForQt5.callPackage ../by-name/va/vapoursynth/editor.nix { };
23415:  valeStyles = recurseIntoAttrs (callPackages ../by-name/va/vale/styles.nix { });
23868:  hareHook = callPackage ../by-name/ha/hare/hook.nix { };
35641:  gnome-bluetooth_1_0 = callPackage ../by-name/gn/gnome-bluetooth/1.0 { };
35645:  gnome-session-ctl = callPackage ../by-name/gn/gnome-session/ctl.nix { };
35648:  gnome-settings-daemon43 = callPackage ../by-name/gn/gnome-settings-daemon/43 { };
35679:  mutter43 = callPackage ../by-name/mu/mutter/43 { };
36479:  isabelle-components = recurseIntoAttrs (callPackage ../by-name/is/isabelle/components { });
```

Pattern of calling by-name sub-packages/versions seems already in use

**Review by fabianhjr — APPROVED** [review]

**Comment by fabianhjr** [comment]
nit: split into several commits (eg, the move of deno to deno_1 by-name, deno 2 init being separate commits)

**Comment by rawkode** [comment]
hey @06kellyjac ! Looks like you need to run nixfmt 👍🏻

**Comment by 06kellyjac** [comment]
Thanks Fabian.
I've split it into 2 commits but as I've thought about it more I don't really like it.
I think I'll flip it back around so I update the original files in one commit, then in a 2nd commit add deno_1.
Then it also means there won't be a commit where `deno` is missing and probably suites better for cutting out deno_1 just before finalizing 24.11.
Then it'll be 2 commits but fit a bit better IMO.

Less important but I've also changed the dir from `v1` to `1` just to match existing ones a bit more

```
λ fd '^\d' --type d ./pkgs/by-name
./pkgs/by-name/de/deno/1/
./pkgs/by-name/gn/gnome-bluetooth/1.0/
./pkgs/by-name/gn/gnome-settings-daemon/43/
./pkgs/by-name/mu/mutter/43/
```

---

Hi David, long time no see.
Formatting should be addressed now. Just going to make the adjustments above

**Comment by 06kellyjac** [comment]
restructured commits as described above. Formatting checks should pass :pray:

**Comment by 06kellyjac** [comment]
Some context for the PR and why the plan is to drop `deno_1` before 24.11 (or earlier)

image

If you would like to use `deno_1` after it's been dropped from nixpkgs, the power of nix allows you to trivially pull in old packages.
After merging PR dropping `deno_1` I'll provide a snippet which references the oldest commit with `deno_1`

**Review by fabianhjr — APPROVED** [review]

**Comment by fabianhjr** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 347484`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 19 packages built:</summary>
  <ul>
    <li>deno</li>
    <li>deno_1</li>
    <li>era</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>rstudio</li>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
    <li>rstudioWrapper</li>
    <li>silverbullet</li>
    <li>vimPlugins.ddc-filter-matcher_head</li>
    <li>vimPlugins.ddc-filter-sorter_rank</li>
    <li>vimPlugins.ddc-source-lsp</li>
    <li>vimPlugins.ddc-ui-native</li>
    <li>vimPlugins.ddc-ui-pum</li>
    <li>vimPlugins.ddc-vim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.vim-pluto</li>
    <li>windmill</li>
  </ul>
</details>

**Comment by sammypanda** [comment]
thank you :D

**Comment by emilazy** [comment]
We only have two weeks left before the 24.11 freeze, and it sounds like they’re not going to be doing security updates, so I’m going to drop Deno 1 immediately.

**Comment by bradylill** [comment]
Thank you!

Just tested this out and one thing I noticed that I was getting a panic with `inotify`.

I tried a non-nix install with `cargo install deno --locked` as per their [instructions](https://docs.deno.com/runtime/getting_started/installation/#download-and-install) and did not get the same issue.

nix: `deno --version` 
```
deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2
```

non-nix: `deno --version`
```
deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2
```

Backtrace:

```
❯ RUST_BACKTRACE=full deno run -A npm:vite@5.4.8

  VITE v5.4.8  ready in 39 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 2.0.0
Args: ["deno", "run", "-A", "npm:vite@5.4.8"]

thread 'main' panicked at /build/deno-2.0.0-vendor.tar.gz/notify/src/inotify.rs:517:32:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
stack backtrace:
   0:     0x55c0a95dec7b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28f16e8528a6973f
   1:     0x55c0a827eaeb - core::fmt::write::h75b6ef8f7aee1a7c
   2:     0x55c0a95f6b88 - std::io::Write::write_fmt::h973b363e3c6dba24
   3:     0x55c0a95dea59 - std::sys_common::backtrace::print::hf04e3a54197b934a
   4:     0x55c0a95d0b10 - std::panicking::default_hook::{{closure}}::hb3640bfc4d36f569
   5:     0x55c0a95d082e - std::panicking::default_hook::h5661f6cd5eb7129d
   6:     0x55c0a81b7ec6 - deno::setup_panic_hook::{{closure}}::hadc85ed785498550
   7:     0x55c0a95d13ab - std::panicking::rust_panic_with_hook::h3a41910ac9040dcc
   8:     0x55c0a95defb2 - std::panicking::begin_panic_handler::{{closure}}::h4a1c04c4ab6c7070
   9:     0x55c0a95def09 - std::sys_common::backtrace::__rust_end_short_backtrace::h21d2f857d4d898b1
  10:     0x55c0a95d0df6 - rust_begin_unwind
  11:     0x55c0a7adf792 - core::panicking::panic_fmt::hbd29354903ebb815
  12:     0x55c0a7adf525 - core::result::unwrap_failed::hcf443243a02c12f7
  13:     0x55c0a93921f4 - <notify::inotify::INotifyWatcher as notify::Watcher>::watch::h0bb70d8e61a063e2
  14:     0x55c0a8c1cd1e - deno_runtime::ops::fs_events::op_fs_events_open::op_fs_events_open::v8_fn_ptr::h40a96102d9329cbe
  15:     0x55c0aa23f276 - Builtins_CallApiCallbackOptimizedNoProfiling

```

Where this is my `flake.nix` file:
```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/master";
  };

  outputs = { self, nixpkgs }:
  let
    system = "x86_64-linux";
    pkgs =  import nixpkgs { inherit system; config.allowUnfree = true; };
  in
  with pkgs;
  {
    devShells.${system}.default = mkShell {
      packages = [
        deno
      ];
    };
  };
}
```

Is anyone able to reproduce this issue?

**Comment by interroobang** [comment]
I really need this update!

**Pull request merged**
