### PR TITLE
udocker: 1.1.3 -> 1.3.1 and make usable

### LINKED ISSUE #62959: udocker seems to not work
## Issue description

I just discovered `udocker` and i can't use it on NixOS

### Steps to reproduce

Pulling image seems good

```sh
udocker pull alpine
Warning: no engine available and autoinstall disabled
Downloading layer: sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
```

Trying to run image fail because it try to mount some specials folders

```sh
udocker run alpine
Warning: no engine available and autoinstall disabled
Error: invalid host volume path: /lib/modules
```

The [documentation says](https://indigo-dc.gitbooks.io/udocker/doc/user_manual.html):

> `--nosysdirs` prevent udocker from mapping /proc /sys /run and /dev inside the container

Trying without mounting folder fail because it can't find `proot`

```sh
udocker run --nosysdirs alpine
Warning: no engine available and autoinstall disabled
Error: proot executable not found
```

Start a shell with `proot` still fail because it can't find `proot`

```sh
nix-shell --command fish --packages proot
udocker run --nosysdirs alpine
Warning: no engine available and autoinstall disabled
Error: proot executable not found
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.48, NixOS, 19.03.172844.caacbe98ce1 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(pinage404): `"home-manager-19.03, nixos-19.03.172852.5121b483edc, nixos-unstable-19.09pre182256.168d1031af4"`
 - channels(root): `"nixos-19.03.172852.5121b483edc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
Closes #62959

###### Things done

these work
`./result/bin/udocker run archlinux`
`./result/bin/udocker run alpine`
`./result/bin/udocker run fedora`

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132231` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>udocker</li>
  </ul>
</details>

**Comment by siraben** [comment]
```
=================================== FAILURES ===================================
____________ FakechrootEngineTestCase.test_05__get_volume_bindings _____________

self = <test_fakechroot.FakechrootEngineTestCase testMethod=test_05__get_volume_bindings>

    def test_05__get_volume_bindings(self):
        """Test05 FakechrootEngine._get_volume_bindings()."""
        ufake = FakechrootEngine(self.local, self.xmode)
        ufake.opt["vol"] = ()
        status = ufake._get_volume_bindings()
        self.assertEqual(status, ('', ''))
    
        ufake = FakechrootEngine(self.local, self.xmode)
        ufake.opt["vol"] = ("/tmp", "/bin",)
        status = ufake._get_volume_bindings()
>       self.assertEqual(status, ('', '/tmp!/tmp:/bin!/bin'))
E       AssertionError: Tuples differ: ('', '/tmp!/tmp:/usr/bin!/bin') != ('', '/tmp!/tmp:/bin!/bin')
E       
E       First differing element 1:
E       '/tmp!/tmp:/usr/bin!/bin'
E       '/tmp!/tmp:/bin!/bin'
E       
E       - ('', '/tmp!/tmp:/usr/bin!/bin')
E       ?                  ----
E       
E       + ('', '/tmp!/tmp:/bin!/bin')

tests/unit/test_fakechroot.py:152: AssertionError
=============================== warnings summary ===============================
../../../nix/store/115c8s7bvnqyj3vwws5kz1pad0dsnf0d-python3.9-pytest-6.2.4/lib/python3.9/site-packages/_pytest/config/__init__.py:1233
  /nix/store/115c8s7bvnqyj3vwws5kz1pad0dsnf0d-python3.9-pytest-6.2.4/lib/python3.9/site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: collect
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/unit/test_fakechroot.py::FakechrootEngineTestCase::test_05__get_volume_bindings
=================== 1 failed, 393 passed, 1 warning in 2.57s ===================
```

**Comment by siraben** [comment]
Maybe that test should be disabled also.

**Comment by Artturin** [comment]
weird i get no failures, i get the warning though

**Comment by siraben** [comment]
I'm running Nix on CentOS, maybe that's affecting something

**Comment by Artturin** [comment]
check now

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132231` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>udocker</li>
  </ul>
</details>

**Comment by siraben** [comment]
Hm, I still get the same error.

**Comment by Artturin** [comment]
disabled the test

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132231` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>udocker</li>
  </ul>
</details>

**Comment by siraben** [comment]
One more time, maybe it didn't get your fix.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132231` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>udocker</li>
  </ul>
</details>

**Comment by siraben** [comment]
I'm not sure why the test isn't disabling properly:

```
tests/unit/test_dockerlocalfileapi.py ..........                         [ 21%]
tests/unit/test_elfpatcher.py ..................                         [ 25%]
tests/unit/test_execenginecommon.py ...........................          [ 32%]
tests/unit/test_executionmode.py ....                                    [ 33%]
tests/unit/test_fakechroot.py ....F.....                                 [ 36%]
tests/unit/test_filebind.py ........                                     [ 38%]
tests/unit/test_fileutil.py .....................................        [ 47%]
tests/unit/test_geturl.py ........                                       [ 49%]
```

**Comment by Artturin** [comment]
removed the `FakechrootEngineTestCase.` prefix from the disabledTests so now it shouldn't be run

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132231` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>udocker</li>
  </ul>
</details>

**Comment by siraben** [comment]
It works!

```
[nix-shell:~/.cache/nixpkgs-review/pr-132231-4]$ udocker run alpine
Info: creating repo: /home/siraben/.udocker
Info: udocker command line interface 1.3.1
Info: searching for udockertools 1.2.8
Info: installing udockertools 1.2.8
Info: installation of udockertools successful 
Info: downloading layer sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f861aae63beeddb6b
Info: downloading layer sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
  
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING 77057685-3889-3006-924e-fe9f4fa29e22                * 
 *                                                                            * 
 ****************************************************************************** 
 executing: sh
77057685#
```

**Pull request merged**
