### PR TITLE
bcachefs: unstable-2022-01-12 -> unstable-2022-03-09

### PR DESCRIPTION
**Pull request by JJJollyjim**
###### Description of changes

The current bcachefs package has a bug which prevents mounting of encrypted filesystems. I bisected and reported this bug, and it is resolved in the latest upstream commit, to which this PR updates us.

Additionally, I enable parallel building for the bcachefs-tools package (which was convenient in speeding up my dev cycles, I have done ~10 builds on multicore machines and encountered no race conditions).

Finally, I re-enable encrypted filesystems in the NixOS integration test. As the test's shell runs with a systemd-specified private session keyring (i.e. `@s` is not linked to the root user keyring `@u`), the keys (placed in `@u` by `bcachefs unlock`) are not observable to the kernel at mount-time (which only inspects, recursively, `@s`). I now call `keyctl` to link the keyrings together for this ephemeral session.

This should resolve the bcachefs component of #32279.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JJJollyjim** [comment]
@ofborg test bcachefs

**Review by davidak — APPROVED** [review]
Changes look good

I don't fully understand the need for keyctl. @Chiiruno can you have a look?

Not tested. Waiting for ofborg build and test.

@JJJollyjim thanks for the contribution!

**Comment by Madouura** [comment]
LGTM. I was waiting to update it myself for the encryption fix, I didn't realize it's already been done.
I would still wait another week or two though and then update to latest, there's a bunch of snapshot related fixes being done so we should ideally wait for that to smooth out.
Also, could you add a commit removing chiiruno and replacing it with me please? I am Chiiruno and was planning to do so whenever I did another PR updating this.
Also thank you so much for fixing the encryption part of the test, I had no idea we even _could_ fix it on our end.

> Changes look good
> 
> I don't fully understand the need for keyctl. @Chiiruno can you have a look?
> 
> Not tested. Waiting for ofborg build and test.
> 
> @JJJollyjim thanks for the contribution!

I believe keyctl is for this command: ``"keyctl link @u @s",``@https://github.com/NixOS/nixpkgs/pull/163433/files#diff-c85d7eb461bd1a5c0ae27b7d0335981e57f2a0f6f2d078d60a4c1e6f1c394110R23

**Comment by Madouura** [comment]
Also quick note, linux_testing_bcachefs and bcachefs-tools should be separate commits.

**Comment by davidak** [comment]
>I believe keyctl is for this command: `"keyctl link @u @s"`

yes, but why is that needed? `bcachefs unlock` is using a password and no key or something

the documentation does not say to do it. https://bcachefs.org/Encryption/

There is also a change of the disk format that might break things. So we might want to wait for others to test it first.

https://www.patreon.com/posts/new-allocator-63762888?utm_medium=post_notification_email&utm_source=post_link&utm_campaign=patron_engagement

**Comment by JJJollyjim** [comment]
@davidak it's related to the differences in our PAM config compared to other distributions, as well as the systemd keyring isolation thing. There are plenty of contexts in other distros where manual linking will not be required, which I guess is why the docs don't mention it.

The unlock command uses the password to decrypt the key material and write it to @u. The mount command reads recursively from @s, which fails if @s doesn't link to @u.

I don't believe my commit includes the new allocator, so that shouldn't be a blocker on this PR.

**Comment by JJJollyjim** [comment]
Requested changes have been made (split update commits and changed maintainers).

**Comment by davidak** [comment]
@JJJollyjim thanks for the explanation.

Is the key written to the encrypted disk, so it can be decrypted on a different system when you have the password?

**Comment by JJJollyjim** [comment]
Yes. From https://bcachefs.org/Encryption/:

Screen Shot 2022-03-14 at 10 26 00 PM
:

**Review by davidak — APPROVED** [review]
Changes look good

When the tests run successful in ofborg, it could be merged from my side.

@Madouura can have the final decision if we merge now or wait.

**Review by Madouura — APPROVED** [review]
>I don't believe my commit includes the new allocator, so that shouldn't be a blocker on this PR.

In that case, LGTM. I'll probably update it early next month when things smooth out with that then.

**Comment by Madouura** [comment]
Given there's a new on-disk format, this should be the last backport to 21.11 too, further updates should be aimed for 22.05.

**Pull request merged**
