### PR TITLE
pnpm_9: 9.12.2 -> 9.12.3

### LINKED ISSUE #351830: Update request: pnpm 9.12.2 -> 9.12.3
- Package name: pnpm
- Latest released version: 9.12.2

- Current version on the unstable channel: 9.12.2
- Current version on the stable/release channel: 9.7.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

@Scrumplex @gepbird 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by gepbird**
Release: https://github.com/pnpm/pnpm/releases/tag/v9.12.3
Closes https://github.com/NixOS/nixpkgs/issues/351830

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gepbird** [comment]
I'll start nixpkgs-review on this about 5 hours later.

pnpm 10 is coming soon, we already have an alpha release: https://github.com/pnpm/pnpm/releases/tag/v10.0.0-alpha.0
I think we can wait for a stable release with packaging unless some people want to use it earlier.

Also I'll look into bumping pnpm 8 to 9/10 after the nixpkgs release cycle and dropping 8 if it's not required by any package.

**Comment by MisileLab** [comment]
I'm doing nixpkgs-review and daed-pnpm-deps already failed due to hash mismatch
@Mic92

**Comment by dotlambda** [comment]
> daed-pnpm-deps already failed due to hash mismatch

That's also the case in master.

**Comment by gepbird** [comment]
Thanks for also trying nixpkgs-review, I ended up restarting it and waiting it out overnight. No other failures than `dead`.

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351836`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>daed</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 49 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>clash-verge-rev</li>
    <li>en-croissant</li>
    <li>equibop</li>
    <li>equicord</li>
    <li>follow</li>
    <li>gitbutler</li>
    <li>goofcord</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>legcord</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>n8n</li>
    <li>overlayed</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm (pnpm_9)</li>
    <li>podman-desktop</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>surrealist</li>
    <li>syncyomi</li>
    <li>taler-challenger</li>
    <li>taler-merchant</li>
    <li>taler-sync</li>
    <li>taler-wallet-core</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>webcord-vencord</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zenn-cli</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
Merged the daed fix from #352056. So this should now build against master

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351836`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 50 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>clash-verge-rev</li>
    <li>daed</li>
    <li>en-croissant</li>
    <li>equibop</li>
    <li>equicord</li>
    <li>follow</li>
    <li>gitbutler</li>
    <li>goofcord</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>legcord</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>n8n</li>
    <li>overlayed</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm (pnpm_9)</li>
    <li>podman-desktop</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>surrealist</li>
    <li>syncyomi</li>
    <li>taler-challenger</li>
    <li>taler-merchant</li>
    <li>taler-sync</li>
    <li>taler-wallet-core</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>webcord-vencord</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zenn-cli</li>
  </ul>
</details>

**Pull request merged**
