### PR TITLE
cosmic-settings: 1.0.0-alpha.1 -> 1.0.0-alpha.2

### PR DESCRIPTION
**Pull request by ahoneybun**
## Description of changes

It is building and running now but cosmic-icons do not seem to render.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
Try force linking with libwayland, like in xdg-desktop-portal-cosmic.

**Comment by ahoneybun** [comment]
> xdg-desktop-portal-cosmic

the force linking?:

https://github.com/NixOS/nixpkgs/blob/c264e0eb6701dec7e92f29f6b114f88c068e80d2/pkgs/by-name/xd/xdg-desktop-portal-cosmic/package.nix#L58

I think I tried that and it errors out.

**Comment by alyssais** [comment]
Yes.  What error?

**Comment by ahoneybun** [comment]
```
       >   = note: /nix/store/81xsp348yfgmaan9r5055mcdjfw7a8wc-binutils-2.42/bin/ld: cannot find -lEGL: No such file or directory
       >           collect2: error: ld returned 1 exit status
```

**Comment by ahoneybun** [comment]
I suspect I need something else package wise.

**Comment by alyssais** [comment]
Does it actually need to link libEGL, in addition to libwayland-client?  If so, it probably needs libGL.

**Comment by ahoneybun** [comment]
Alright I have it building and running now but cosmic-icons do not seem to render?

**Comment by a-kenji** [comment]
Maybe it needs updated icons: https://github.com/NixOS/nixpkgs/pull/344473 ?

**Comment by ahoneybun** [comment]
> Maybe it needs updated icons: #344473 ?

Maybe? They are all missing like it was before cosmic-icons was added into this packaging.

**Comment by ahoneybun** [comment]
@a-kenji I synced with upstream since the PR was merged but it didn't fix the missing icons issue.

**Comment by a-kenji** [comment]
@ahoneybun Thanks for the heads up, I will check it out too.

**Comment by musjj** [comment]
Any reason why your deleted your repository? Was this superseded by a different PR?

**Comment by ahoneybun** [comment]
Ohhh that's what happened, I messed it up.

**Comment by ahoneybun** [comment]
This replaces it:

https://github.com/NixOS/nixpkgs/pull/350936

**Pull request closed without merging**
