### PR TITLE
sgx_psw,sgx_sdk: 2.16 -> 2.17

### PR DESCRIPTION
**Pull request by rvolosatovs**
###### Description of changes

Upstream update https://github.com/intel/linux-sgx/releases/tag/sgx_2.17. Built on top of 22.05

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rvolosatovs** [comment]
Hmm, interesting, `aesmd` execution fails with:
```
Jul 11 11:33:55 sgx-equinix-demo aesm_service[6322]: Bundle#3 start failed: libsgx_pce_logic.so.1: cannot open shared object file: No such file or directory
Jul 11 11:33:55 sgx-equinix-demo aesm_service[6322]: aesm_service: error: Fail to start service.
```

**Comment by sbellem** [comment]
Hey @rvolosatovs ! I'd like to help move this forward, and perhaps we may as well bump the version to the latest (2.19).

## local builds
I could build the sdk locally, but I am struggling with my environment to test it.

## output of `nixpkgs-review`
Running `nixpkgs-review` yields:

```
3 packages marked as broken and skipped:
sgx-psw sgx-sdk sgx-ssl
```

Full output:


```
$ nix run nixpkgs#nixpkgs-review -- pr 181083
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/181083/head:refs/nixpkgs-review/1
$ git worktree add /home/sylvain/.cache/nixpkgs-review/pr-181083-10/nixpkgs f09cd3b7de97224518dbded5af5fcf857aec1ee5
Preparing worktree (detached HEAD f09cd3b7de9)
Updating files: 100% (35568/35568), done.
HEAD is now at f09cd3b7de9 coqPackages.QuickChick: 1.6.4 → 1.6.5
$ git merge --no-commit --no-ff c843ac2977ea0c701e3fbfbd9764aa9c78eb0f11
Auto-merging pkgs/os-specific/linux/sgx/psw/default.nix
Auto-merging pkgs/os-specific/linux/sgx/sdk/default.nix
Automatic merge went well; stopped before committing as requested

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/181083

3 packages marked as broken and skipped:
sgx-psw sgx-sdk sgx-ssl

$ /nix/store/k6ciawnknm1yxxiwm4pih008rijyn9wh-nix-2.15.1/bin/nix-shell /home/sylvain/.cache/nixpkgs-review/pr-181083-10/shell.nix
```

Running the hardware tests (on my sgx-capable machine) gives me the following:

## hardware tests
I am also struggling with my environment (perhaps) as I get the following when running the hardware tests, not just for this PR but also for the current sgx-sdk version in nixpkgs stable.

```
*** Running test Cxx11SGXDemo-HW ***

Error: Unexpected error occurred.
Enter a character before exit ...
```

/cc @veehaitch

**Comment by sbellem** [comment]
Hey @rvolosatovs I'm sorry, I do not wish to overstep on your work, but the latest release is now v2.19 and I was curious as to what it would take to perform the upgrade, and I ended up opening pull request https://github.com/NixOS/nixpkgs/pull/236815 to upgrade `sgx-sdk` and `sgx-psw` to v2.19.

I'm fine to combine our work if you wish. Besides changing the version numbers and hashes, upgrading to v2.19 (or v2.18) requires some small changes as there's a new dependency that needs to be symlinked.

**Comment by rvolosatovs** [comment]
> Hey @rvolosatovs I'm sorry, I do not wish to overstep on your work, but the latest release is now v2.19 and I was curious as to what it would take to perform the upgrade, and I ended up opening pull request https://github.com/NixOS/nixpkgs/pull/236815 to upgrade `sgx-sdk` and `sgx-psw` to v2.19.
> 
> I'm fine to combine our work if you wish. Besides changing the version numbers and hashes, upgrading to v2.19 (or v2.18) requires some small changes as there's a new dependency that needs to be symlinked.

Hi, thank you for working on this, I do not use the technology myself anymore and don't have capacity to work on this at the moment.
Closing the PR in favor of yours!

**Comment by sbellem** [comment]
> Hi, thank you for working on this, I do not use the technology myself anymore and don't have capacity to work on this at the moment.
> Closing the PR in favor of yours!

Ah ok, thanks for taking the time to respond!

**Pull request closed without merging**
