### PR TITLE
nvidia_x11: 390.77 -> 390.87

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by eadwu** [comment]
http://rglinuxtech.com/?p=2391 proposes a solution for 4.19-rc1 though I personally haven't had success with it.

```nix
patches = lib.optional (lib.versionAtLeast "4.19" (kernel.version or "0")) ./drm_mode_connector.patch;
```

with the following patch

```diff
diff --git a/kernel/nvidia-drm/nvidia-drm-connector.c b/kernel/nvidia-drm/nvidia-drm-connector.c
--- a/kernel/nvidia-drm/nvidia-drm-connector.c
+++ b/kernel/nvidia-drm/nvidia-drm-connector.c
@@ -226,7 +226,7 @@ static int nv_drm_connector_get_modes(struct drm_connector *connector)


     if (nv_connector->edid != NULL) {
-        drm_mode_connector_update_edid_property(
+        drm_connector_update_edid_property(
             connector, nv_connector->edid);
     }

diff --git a/kernel/nvidia-drm/nvidia-drm-encoder.c b/kernel/nvidia-drm/nvidia-drm-encoder.c
--- a/kernel/nvidia-drm/nvidia-drm-encoder.c
+++ b/kernel/nvidia-drm/nvidia-drm-encoder.c
@@ -216,7 +216,7 @@ nv_drm_add_encoder(struct drm_device *dev, NvKmsKapiDisplay hDisplay)

     /* Attach encoder and connector */

-    ret = drm_mode_connector_attach_encoder(connector, encoder);
+    ret = drm_connector_attach_encoder(connector, encoder);

     if (ret != 0) {
         NV_DRM_DEV_LOG_ERR(
```

**Comment by xeji** [comment]
cc maintainer @vcunat

**Comment by eadwu** [comment]
Compiles fine on 4.19.0-rc2 though haven't actually tested this version yet.

**Review by vcunat — APPROVED** [review]
Tested running on 18.09 with 4.18 kernel, and building with 4.19 kernel.

**Comment by vcunat** [comment]
I'm sorry this has been lying here for so long.

**Comment by xeji** [comment]
@vcunat this is really weird: github says  :  "xeji merged commit af3fdb4.." above when it's clearly you who merged this.  Do you see this too?

**Comment by vcunat** [comment]
That's currently a very common GitHub error.  It used to be rarer and I've reported it once or twice to their support, some year or two ago, but...

**Comment by xeji** [comment]
Thanks. That really got me scared for a moment...

**Pull request merged**
