### PR TITLE
Go packages, buildGoPackage

### PR DESCRIPTION
**Pull request by lucabrunox**
Based on PR #4222 , also ported ngrok, didn't test it but the binaries run. cc @iElectric are you fine with this kind of build? 

@ehmry I've added $makeFlags to go install call, maybe improper but it's ok for now I think. Also added go13Packages and go14Packages. Removed the crypto package, confirming it's broken with recent go versions.

Build with `nix-build -A ngrok`.

Packages to port:
- [x] bosun
- [x] pond
- [x] gox
- [x] etcdctl
- [x] gocode
- [x] golint
- [x] gotags
- [x] go-repo-root
- [ ] packer (uses gox)
- [ ] consul (uses ruby in the build)
- [x] etcd
- [x] influxdb-backup
- [x] nsq
- [x] serfdom
- [x] go-mtpfs
- [x] go-bindata
- [x] ngrok
- [x] flannel
- [x] syncthing
- [ ] kubernetes (quite custom build)

### CODE REVIEW

**Comment by iElectric** [comment]
Looks good. Might wanna delete old ngrok expression.

**Comment by ehmry** [comment]
:+1:
I can't say I think go.crypto is very well maintained, so its not a supprise to me.

**Comment by lethalman** [comment]
@ehmry as a result I've also dropped cjdcmd, sorry. At a later attempt maybe :)

**Comment by ehmry** [comment]
Thats ok, it was a test.

**Comment by iElectric** [comment]
Awesome!

**Comment by lethalman** [comment]
Also cc @cstrahan , retained as maintainer. I've decided to keep ngrok in its own directory instead of under goPackages. Now working on porting the other software.

**Comment by offlinehacker** [comment]
Nice, the last thing we would need is go2nix fixed for a new format.

**Comment by lethalman** [comment]
@offlinehacker what should go2nix do? I personally don't want packages to be auto updated.

**Comment by lethalman** [comment]
Just ported pond, which required crypto. So @ehmry it seems to work, it's a different hash though, but at least compiles with go 1.3 :)

**Comment by ehmry** [comment]
@lethalman I'll check it out.

I also think that auto-updating packages would be trouble, but a tool to generate the package expressions would be very useful.

I had a quick and dirty shell script to do that but I don't know how it compares to go2nix.

**Comment by lethalman** [comment]
I'm resolving conflicts between package names using the repo name. E.g. `rcrowley.go-metrics` and `armon.go-metrics`.

**Comment by ehmry** [comment]
Good call

**Comment by lethalman** [comment]
@ehmry indeed giving a repo path and automatically creating the nix expression is handy. I just don't like the way npm packages are updated, for example.

**Comment by lethalman** [comment]
cc @bennofs ported go-mtpfs, hope it's ok for you :)

**Comment by lethalman** [comment]
So packer uses gox, and consul also uses ruby in the build. I would leave them as is for now.

**Comment by lethalman** [comment]
Also I wouldn't touch kubernetes either.

**Comment by lethalman** [comment]
@matejc I've ported syncthing to buildGoPackage, does it look fine to you?

**Comment by bennofs** [comment]
@lethalman no problem, as long as it works :)

**Comment by lethalman** [comment]
Ok so I'm going to merge this in a few days, I will do a quick test of all the packages again. That said, if a ported package doesn't work we can always bring the older version back.

**Comment by lethalman** [comment]
OK let's merge this and see :)

**Comment by wmertens** [comment]
@lethalman I think this is worthy of mentioning in https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-unstable.xml

**Comment by domenkozar** [comment]
I'm using `$ nix-build -A packer|&grep "cannot find package" | sed -E 's/cannot find package "(.*)" in any of:/\1/'| cut -d " " -f 2|sort|uniq` to get a list of buildInputs

**Pull request merged**
