### PR TITLE
bepasty: make it a package again

### PR DESCRIPTION
**Pull request by Lassulus**
this fixes running bepasty with gunicorn, which is needed for
services.bepasty

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
I'm not really sure what the best option is in this case. /cc @FRidh 

The relevant lines from the systemd service:
```nix
        systemd.services."bepasty-server-${name}-gunicorn" = {
          environment = let
            penv = python.buildEnv.override {
              extraLibs = [ bepasty gevent ];
            };
          in {
            BEPASTY_CONFIG = "${server.workDir}/bepasty-${name}.conf";
            PYTHONPATH= "${penv}/${python.sitePackages}/";
          };
          ExecStart = ''${gunicorn}/bin/gunicorn bepasty.wsgi --name ${name} ..."
        };
```

**Comment by FRidh** [comment]
This is an interesting issue. Bepasty is a server, so considered an `application`. The service works by creating and setting the `PYTHONPATH` environment variable, pointing to a a Python env. `buildEnv` will only include libraries and not applications.

I think the solution here is indeed to revert back to `buildPythonPackage`.

@Lassulus can you include a comment stating that `buildPythonPackage` needs to be used with a reference to this PR?

**Comment by dotlambda** [comment]
@FRidh Can you explain why using `buildPythonPackage` solves the problem?

**Comment by FRidh** [comment]
`python.buildEnv` will only include libraries as of 40851a4d26daabf1613c9a79e638aaf9f94b476c.

**Comment by dotlambda** [comment]
I think an inline comment (in the code, not the commit message) would be better. And please add a link to this PR.

**Comment by dotlambda** [comment]
@GrahamcOfBorg build bepasty

**Comment by dotlambda** [comment]
Should this be backported to 18.03?

**Comment by Lassulus** [comment]
@dotlambda yes, please

**Comment by dotlambda** [comment]
Backported in 1092f6d08653c56638bcf038f5daf257f59df605.

**Pull request merged**
