### PR TITLE
gnome3: Add dleyna service

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
dleyna services provide DLNA support for applications.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Rebased and ready to merge.

**Comment by jtojnar** [comment]
I proposed the envvar patch upstream: https://github.com/01org/dleyna-core/pull/50

**Comment by grahamc** [comment]
Thank you for restoring the branch :)

**Comment by grahamc** [comment]
@GrahamcOfBorg build gupnp_av gupnp gupnp_dlna dleyna-core dleyna-connector-dbus dleyna-renderer gnome3.gnome-photos dleyna-server gnome3.gnome-online-minerss gnome3.grilo-plugins

**Pull request merged**
