### PR TITLE
pandoc: add useful patch for nixos manual transformation to CommonMark

### PR DESCRIPTION
**Pull request by blaggacao**
see: https://github.com/jgm/pandoc/pull/7389

for full details.

@jtojnar

### CODE REVIEW

**Comment by sternenseemann** [comment]
I don't think it's a good idea applying a patch that hasn't even been reviewed yet by upstream that changes behavior. If it gets merged, I think fast tracking it from 2.15 (?) seems reasonable.

Also please target `haskell-updates` due to the amount of (haskell) rebuilds.

**Comment by blaggacao** [comment]
> I don't think it's a good idea applying a patch that hasn't even been reviewed yet by upstream that changes behavior. 

I agree, Ideally we only use it for our own docbook to CommonMark transition, only.

**Comment by sternenseemann** [comment]
If it's urgent, we can create a separate attribute for it temporarily?

**Comment by blaggacao** [comment]
> If it's urgent, we can create a separate attribute for it temporarily?

Let's @ryantm or @jtojnar decide. They do the excellent and important job of leading the implementation of RFC72.

**Comment by jtojnar** [comment]
I think it would be nice to have `pandocForManual` derivation tracking latest pandoc version plus unmerged patches.

But first, we will need to come up with a way to package pandoc and its dependencies that is easy to bump while not adding extra load on Haskell team like https://github.com/jtojnar/nixpkgs/tree/pandoc-2.14 would.

**Comment by blaggacao** [comment]
> I think it would be nice to have pandocForManual derivation tracking latest pandoc version plus unmerged patches.

Let's do that. If all this extra stuff for pandoc in your branch it's probably best if you take over.

**Pull request closed without merging**
