### PR TITLE
Trinity on nixos

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Motivation for this change

A new branch for Trinity on NixOS
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
please rebase.

**Comment by AndersonTorres** [comment]
This branch is in par with `master`?

**Comment by grahamc** [comment]
@AndersonTorres I don't think there is reason to create a branch. Why do you think there should be a branch?

**Comment by grahamc** [comment]
@Mic92 see https://github.com/NixOS/nixpkgs/pull/18715/files for the related PR to master.

**Comment by AndersonTorres** [comment]
@grahamc I don't have any special reason to install a new branch, in fact I don't even know why the branch is here :)
Maybe I have made a mistake on a git command, because I customarily use the nixos-master branch as default for pull requests.

Can we then delete this branch?

**Comment by FRidh** [comment]
@AndersonTorres I guess this was a mistake. Let's continue with #18715

**Pull request closed without merging**
