### PR TITLE
python312Packages.numpy_2: 2.0.0 -> 2.0.1

### PR DESCRIPTION
**Pull request by doronbehar**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by doronbehar** [comment]
Since there are no objections and the update is trivial, I'm merging.

**Comment by GaetanLepage** [comment]
It seems like this broke `numba`.
```
building 'numba._helperlib' extension
creating build/temp.linux-x86_64-cpython-312/numba/cext
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -I/nix/store/hj602nhxf56j0avbs8j5l9nfa2ngfvg0-libxcrypt-4.4.36/include -fPIC -I/nix/store/z2snigxrrg03xp3v9p9grp2n8xmgy>
In file included from numba/_helpermod.c:23:
numba/_helperlib.c: In function ‘numba_cpowf’:
numba/_helperlib.c:22:44: error: ‘I’ undeclared (first use in this function)
   22 |     #define _complex_float_ctor(r, i) (r + I * i)
      |                                            ^
numba/_helperlib.c:147:12: note: in expansion of macro ‘_complex_float_ctor’
  147 |     *out = _complex_float_ctor((float) _out.real, (float) _out.imag);
      |            ^~~~~~~~~~~~~~~~~~~
numba/_helperlib.c:22:44: note: each undeclared identifier is reported only once for each function it appears in
   22 |     #define _complex_float_ctor(r, i) (r + I * i)
      |                                            ^
numba/_helperlib.c:147:12: note: in expansion of macro ‘_complex_float_ctor’
  147 |     *out = _complex_float_ctor((float) _out.real, (float) _out.imag);
      |            ^~~~~~~~~~~~~~~~~~~
error: command '/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/gcc' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by GaetanLepage** [comment]
Upstream (closed) issue: https://github.com/numba/numba/issues/9687
Upstream fix (currently in `master`, awaiting for a new release): https://github.com/numba/numba/pull/9683

**Comment by doronbehar** [comment]
In fact, there is a numpy 2.1.0 release which is not compatible even with numba `master`... https://github.com/numba/numba/issues/9708 .

**Pull request merged**
