### PR TITLE
go_1_14: 1.14.14 -> 1.14.15, go_1_15: 1.15.7 -> 1.15.8

### PR DESCRIPTION
**Pull request by terinjokes**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by mdlayher — APPROVED** [review]

**Comment by terinjokes** [comment]
Considering `1.15.7` and `1.14.4` were security releases, should I open a PR to upgrade 20.09 to either those versions or this version?

**Comment by kalbasit** [comment]
> Considering `1.15.7` and `1.14.4` were security releases, should I open a PR to upgrade 20.09 to either those versions or this version?

Yes, we should backport security fixes.

**Comment by terinjokes** [comment]
Are we waiting on anything to get this PR merged?

**Comment by tv42** [comment]
For what it's worth, https://github.com/golang/go/issues/43570 fixed in go-1.15.8 looks pretty nasty. Basically random corruption on anything built with older compilers, and also happens on 64-bit platforms. So, I personally feel nixos 20.09 backport should target go 1.15.8, not 1.15.7; the Go team is pretty meticulous about stable being stable.

**Review by rvolosatovs — APPROVED** [review]

**Comment by zowoq** [comment]
Github won't let me push to this branch so I've split the commit and pushed it to master. 54772e76707fd934ede05aac842dbb758f1356bb 860a644e0d07d769d39c4f89cac8c5d4ca686161

**Comment by zowoq** [comment]
`20.09` backports:
https://github.com/NixOS/nixpkgs/commit/1102357323c55bae65fd67d5d0fd0e26eb29843b
https://github.com/NixOS/nixpkgs/commit/47793f28f41150c89aa971a8dfa6dfa793178916
https://github.com/NixOS/nixpkgs/commit/8dd990ceff13613852b850c8b7d6df38eb8fcbf5
https://github.com/NixOS/nixpkgs/commit/8dd990ceff13613852b850c8b7d6df38eb8fcbf5
https://github.com/NixOS/nixpkgs/commit/5f295d1017f7edd2915f9809b8e29c13809075cb
https://github.com/NixOS/nixpkgs/commit/12614a0bb02edcaa0e1cc841953f8c66ac1e69cc

**Comment by Ma27** [comment]
@zowoq huge changes like this should really go through staging!

Too tired to revert now, but I'll do that tomorrow if nobody else is faster. As it's a critical thing, `staging-next` (and `staging-20.09` is the better choice here).

**Comment by zowoq** [comment]
We've been sending `go` updates to master for months.

**Pull request closed without merging**
