### PR TITLE
aegisub: add support for aarch64-linux

### PR DESCRIPTION
**Pull request by wegank**
###### Motivation for this change

This pull request adds support for more platforms to Aegisub, including aarch64-linux, by using Debian's [patch](https://sources.debian.org/patches/aegisub/3.2.2+dfsg-6/remove-vendor-luajit-dependency.patch/) to remove the vendor luajit dependency in the package. Fully tested on aarch64-linux.

As the Aegisub's website has been [down for one year](https://tracker.debian.org/pkg/aegisub), this pull request also proposes to switch to the official GitHub repository.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
To be honest, I was looking for a new repo. 
Aegisub was forked a time ago, however I couldn't compile it.

**Comment by wegank** [comment]
I still managed to compile from multiple upstream repositories (TypesettingTools/Aegisub, wangqr/Aegisub), their forks just won't work on aarch64-linux...

**Comment by AndersonTorres** [comment]
> their forks just won't work on aarch64-linux...

When you say this, you say "even with the Debian patches"...?

**Comment by wegank** [comment]
It seems to me that luajit has become a hard dependency in the upstream versions. When using luajit on aarch64-linux, Aegisub crashes on startup with the following error:

```
terminate called without an active exception
[2]    533045 IOT instruction (core dumped)  result/bin/aegisub
```

[This](https://gist.github.com/wegank/4499dce41162878bab18a0f5a41a5cb5) is the derivation file that I'm using. Not sure if it will work on x86_64-linux.

**Review by dasj19 — COMMENTED** [review]
1. Please don't leave unnecessary blank lines between dependencies-
2. I initiated a build on x86_64 linux; I'll approve if it succeeds

**Review by dasj19 — APPROVED** [review]
Can confirm that it builds successfully and runs smoothly on linux x86_64

**Pull request closed without merging**
