### PR TITLE
mealie: 1.2.0 -> 1.6.0

### PR DESCRIPTION
**Pull request by anoadragon453**
## Description of changes

This PR updates `mealie` from 1.2.0 -> 1.6.0. See the list of releases along with changelogs for each version here: https://github.com/mealie-recipes/mealie/releases

**Breaking change:** in `mealie` 1.4.0, the `ALLOW_SIGNUP` environment variable is now `false` by default instead of `true`, to improve the default security posture. See the [relevant release notes](https://github.com/mealie-recipes/mealie/releases/tag/v1.4.0).

I added a note about this to the 24.05 release notes. Though I also noticed that mealie was announced in these release notes, yet [has been backported to 23.11](https://github.com/NixOS/nixpkgs/pull/292081). Should the mealie announcement thus be moved to the 23.11 release notes?

This update allowed for removing several workarounds in the package - thanks to @litchipi for their upstreaming efforts!

I've also added myself as maintainer for this package to help with the maintenance burden.

Recommended to review commit-by-commit.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by litchipi — COMMENTED** [review]
Nothing really to say !
Relieved we can get rid of the patches and have finally a very clean packaging :smile: 
Thanks for the work

Did you test it ? I'll try it out soon, will approve once someone (or me) tested the module to check everything is OK :+1:

**Comment by anoadragon453** [comment]
> Did you test it ?

I don't have a system to test it on yet - I'm currently struggling to integrate the package into my own NixOS config. Not due to issues with the package, but other things related to my setup.

I'll keep plugging away at it, otherwise would encourage others to try it in the meantime.

**Comment by anoadragon453** [comment]
This build of `mealie` is now working on my setup (after a separate change to the package; https://github.com/NixOS/nixpkgs/pull/309969) :tada:

**Comment by anoadragon453** [comment]
Mealie happened to release v1.6.0 while this PR was in flight, so I've updated it to point to 1.6.0 now. The new version also works in my setup :tada:

For review, the changes needed between 1.5.1 and 1.6.0 were:

- Update the version number and hash (of course): https://github.com/NixOS/nixpkgs/pull/309671/commits/1bfeb7079b1e88008e2ca7ebc1f97209470ae751
- Add `pyjwt` as a new dependency: https://github.com/NixOS/nixpkgs/pull/309671/commits/8c92b3e076dd7d6f4e744c599114154388de6247
- Remove `python-jose` as a dependency, as it was replaced by `pyjwt` (see https://github.com/mealie-recipes/mealie/pull/3521): https://github.com/NixOS/nixpkgs/pull/309671/commits/193a5fe0edf1be0f15d6eb2f149187f774c698d6

**Comment by litchipi** [comment]
A little things that should maybe be fixed now (that I missed in my first PR I think :sweat:)

BASE_URL should be defaulting to `localhost:$[cfg.mealie.port}`, as it's still using the 8080 port, that causes generated links to be faulty

Otherwise it works well !

**Comment by anoadragon453** [comment]
@litchipi Good spot. Fixed in https://github.com/NixOS/nixpkgs/pull/309671/commits/c2d7d356ba50cb8766a926f89c4b1e0d9375f097.

**Review by litchipi — APPROVED** [review]
LGTM :smiley: 
Thanks for the work

**Pull request closed without merging**
