### PR TITLE
msgpack-cxx: 6.1.1 -> 7.0.0

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353400`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 16 packages built:</summary>
  <ul>
    <li>foundationdb</li>
    <li>foundationdb.debug</li>
    <li>foundationdb.dev</li>
    <li>foundationdb.lib</li>
    <li>foundationdb.pythonsrc</li>
    <li>jami</li>
    <li>msgpack-cxx</li>
    <li>opendht</li>
    <li>opendht.dev</li>
    <li>opendht.lib</li>
    <li>opendht.man</li>
    <li>python311Packages.foundationdb71</li>
    <li>python311Packages.foundationdb71.dist</li>
    <li>python312Packages.foundationdb71</li>
    <li>python312Packages.foundationdb71.dist</li>
    <li>stalwart-mail</li>
  </ul>
</details>

**Comment by emilazy** [comment]
Thanks! Are we sure loosening the FoundationDB bound is safe? It looks like 6.x postdates the original 2022 serialization change by a fair amount. Though since it’s just special‐casing the representation of certain floats I guess it should be handled fine.

**Comment by NickCao** [comment]
> Are we sure loosening the FoundationDB bound is safe?

Well, I don't know, is there a way to test it out?

**Comment by emilazy** [comment]
Well… as I understand it, FoundationDB has a test suite so good that they later went and founded a company about it. But I don’t know if it’s public or not, and we don’t seem to run any kind of tests in our derivation. My assumption is that the bump is probably fine, though, given the limited scope of the breaking change and the fact that in the past FoundationDB had been using versions from before the original breaking change (that was reverted more recently).

More to the point, though, our package is on a version from [May 2023](https://github.com/apple/foundationdb/releases/tag/7.1.32); we’re 402 commits and a whole bunch of versions behind the 7.1 release branch we’re on, and as far as the latest release goes, it seems that they’re up to 7.3. I understand that FoundationDB is meant to be highly robust already, but that still seems somewhat concerning for production use to me; there have been [quite a few bug fixes](https://apple.github.io/foundationdb/release-notes/release-notes-710.html) since our version. I can’t find a support policy but it doesn’t seem like they’re supporting versions older than 7.1 so I assume that the next major release might leave us on an EOL version.

@thoughtpolice Are you still interested in maintaining FoundationDB in NixOS? Do you know if anyone is using it?

**Comment by emilazy** [comment]
After a little more investigation I guess we run a subset of tests that don’t require doctest, maybe? Not clear to me if we still run a substantial number of tests; if we do then it’s probably okay. (I was testing builds on `staging`, where FoundationDB is currently broken for unrelated reasons, so I haven’t gotten around to testing this yet.)

Should still probably work out if the package has a future though.

**Review by emilazy — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353400`

---
### `x86_64-linux`
<details>
  <summary>:x: 10 packages failed to build:</summary>
  <ul>
    <li>foundationdb (foundationdb71)</li>
    <li>foundationdb.debug (foundationdb71.debug)</li>
    <li>foundationdb.dev (foundationdb71.dev)</li>
    <li>foundationdb.lib (foundationdb71.lib)</li>
    <li>foundationdb.pythonsrc (foundationdb71.pythonsrc)</li>
    <li>python312Packages.foundationdb71</li>
    <li>python312Packages.foundationdb71.dist</li>
    <li>python313Packages.foundationdb71</li>
    <li>python313Packages.foundationdb71.dist</li>
    <li>stalwart-mail</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 6 packages built:</summary>
  <ul>
    <li>jami</li>
    <li>msgpack-cxx</li>
    <li>opendht</li>
    <li>opendht.dev</li>
    <li>opendht.lib</li>
    <li>opendht.man</li>
  </ul>
</details>

FoundationDB failure is an existing failure that’s IIRC a GCC 14 thing that I have a patch for locally; I’ll get it sent out.

**Pull request merged**
