### PR TITLE
rfmakecloud: 0.0.18 -> 0.0.21

### PR DESCRIPTION
**Pull request by martinetd**
## Things done

- update rmfakecloud to 0.0.21 (fixes things like compat with latest firmware)
- remove obsolete comment about UI not being built
- add tests

Cc @pacien 

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by pacien — APPROVED** [review]
Diffs looking good to me.
It's very nice to have a test.
Thanks :+1:

**Comment by martinetd** [comment]
>  It's very nice to have a test.

Yeah, always hard for me to test new packages on my machine as it's a pain to replace the running service, it'd be great if we could trust the test.

I only check account creation/login for now, ideally we'd need to have a minimal "pre-existing directory" and verify we can still fetch a pdf from the new server with that but I don't konw how to embed non-trivial test data in nixos tests and I've already spent more time than I should have on this.

The other thing is that the auto-update script doesn't seem to be able to handle rmfakecloud (maybe because the ui is split in a different nix file, or it just doesn't handle yarn?), so we don't get automatic PRs; I'm not quite sure what to do about that but I've subscribed for rmfakecloud updates now so if it's just running a command a couple of times a year I can probably keep doing it.

**Review by tomberek — APPROVED** [review]
built and ran nixos test

Thanks!

**Comment by martinetd** [comment]
Thank you!

Also head's up a 0.0.22 just got out shortly after this was merged that fixes a regression with old remarkable tablet versions

Unfortunately they also update the UI in between, and I can't even get it to build manually on nixos (pnpm build tries to run some randomly downloaded binary apparently...), I hate this all.
I wonder if anyone actually uses the UI on nixos...

**Pull request merged**
