### PR TITLE
vde2: fix build with latest openssl

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/80746

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by andir — COMMENTED** [review]
The project seems to be using wolfssl nowadays: https://github.com/virtualsquare/vde-2/commit/8599321526d0a31925fe55cabbe132b752cb268a

This hasn't landed yet but might as well pick that patch from upstream (if it applies) instead of another downstream patch?


Nitpick: While we touch this the new home of the project is https://github.com/virtualsquare/vde-2. Can you update that?

**Comment by andir** [comment]
Just noticed that if we go with the upstream patch (not really biased at this time) we might want to pick https://github.com/virtualsquare/vde-2/pull/11 as well.

**Comment by worldofpeace** [comment]
> The project seems to be using wolfssl nowadays: virtualsquare/vde-2@8599321
>
> This hasn't landed yet but might as well pick that patch from upstream (if it applies) instead of another downstream patch?

@andir I'm not really familiar with this package, but I do see it being used in the actual python testing driver. Those sound like major changes, not really great for a stable release even if we're still in BETA.

> Nitpick: While we touch this the new home of the project is https://github.com/virtualsquare/vde-2. Can you update that?

I always fix the nits :+1:

**Comment by andir** [comment]
On 15:35 24.02.20, worldofpeace wrote:
> > The project seems to be using wolfssl nowadays:
> > virtualsquare/vde-2@8599321
> >
> > This hasn't landed yet but might as well pick that patch from
> > upstream (if it applies) instead of another downstream patch?
>
> @andir I'm not really familiar with this package, but I do see it
> being used in the actual python testing driver. Those sound like major
> changes, not really great for a stable release even if we're still in
> BETA.

I just thought the upstream patch my be as good as any abitrary
downstream distro patch. We can also use your proposed approach instead.
I really have no hard feelings either way.

**Comment by flokli** [comment]
Let's merge this with archlinux' patches for now. Once the project finished moving to wolfssl, we can do so too.

**Comment by flokli** [comment]
backported to 20.03 in 1a450f03c950e618c47ab8908ab32f02e14c3004, c5e6fbd20399873ad7689840d88175d564b06724.

**Comment by worldofpeace** [comment]
> backported to 20.03 in [1a450f0](https://github.com/NixOS/nixpkgs/commit/1a450f03c950e618c47ab8908ab32f02e14c3004), [c5e6fbd](https://github.com/NixOS/nixpkgs/commit/c5e6fbd20399873ad7689840d88175d564b06724).

Thank you soo much @flokli.

**Pull request merged**
