### PR TITLE
{python{Full,Packages},pypyPackages}: move unversioned aliases to aliases.nix

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

Require in-nixpkgs packages to use versioned names.

:snake: :2nd_place_medal: :chart_with_downwards_trend: 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grahamc** [comment]
Sort of an RFC PR.

**Comment by LnL7** [comment]
Python is part of the darwin stdenv bootstrapping, I think a bit of work is still needed to disambiguate it there.

**Comment by grahamc** [comment]
release.nix evaluates already :man_shrugging:

**Comment by grahamc** [comment]
The above ~180 package updates were done with this in one terminal:

```
while true; do sed -ie 's/python/python2/g' $(nix-env -f . -qaP --no-name --out-path --arg config '{ allowAliases = false; }' 2>&1 | tee /dev/stderr | head -n1 | cut -d' ' -f5  | cut -d: -f1); sleep 1; done
```

and me committing its changes in another terminal, note not all changes are good, so don't just blindly commit. you have to edit patches.

```
for f in $(git status | grep "modified:" | cut -d' ' -f4); do echo "$f"; git add -ip "$f"; echo -n "package name? "; read pname; git commit -m "$pname: python -> python2"; done
```

**Comment by FRidh** [comment]
> Require in-nixpkgs packages to use versioned names.

What do we gain by that? In principle we should have only one version of a package (set), but we indeed choose in some cases to have multiple versions. Would you say that, in case one goes from a single attribute to multiple, the single name should no longer be permitted and a versioned one should *always* be used?

About the `python` to `python2`, I pointed out in earlier PR's that I am against doing it this way, and prefer us to try to migrate it to Python 3 first, and when that is not possible, set it to `python2`. Otherwise we may end up repeating a lot of work.

**Pull request closed without merging**
