### PR TITLE
luajit: fix stack corruption with pcall

### PR DESCRIPTION
**Pull request by lblasc**
###### Motivation for this change

Fix stack corruption with pcalls introduced by #124110
Upstream issue: https://github.com/LuaJIT/LuaJIT/issues/704

I believe this will solve neovim issue: https://github.com/neovim/neovim/issues/14246

In luajit 2.0 issue is not triggered, but it is there, so I've updated it together with 2.1.

*luajit_2_0*

https://github.com/LuaJIT/LuaJIT/compare/44684fa71d8af6fa8b3051c7d763bbfdcf7915d7...c2cfa04231785116d9d198462830f41ef94147c0

*luajit_2_1*
https://github.com/LuaJIT/LuaJIT/compare/5783ba1bf73c53ca56e64ed0c462c62224f0393c...839fb5bd72341d8e67b6cfc2053e2acffdb75567

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — CHANGES_REQUESTED** [review]
The `version` attributes need bumping (like the commit messages say) to avoid possible confusion.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124959` at caafaedc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxPackages_hardkernel_4_14.bcc</li>
    <li>linuxPackages_hardkernel_4_14.bpftrace</li>
    <li>linuxPackages_hardkernel_4_14.sysdig</li>
    <li>linuxPackages_hardkernel_latest.bcc</li>
    <li>linuxPackages_hardkernel_latest.bpftrace</li>
    <li>linuxPackages_hardkernel_latest.sysdig</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/dac583e53b33d75169ab25a0d6d607c2">gimpPlugins.texturize</a></li>
    <li><a href="https://gist.github.com/0fb62607a16ed8a849bcef03ec2a0d76">glimpsePlugins.texturize</a></li>
    <li><a href="https://gist.github.com/8686dbcf302e01ddf3acacb6435a9040">hawkthorne</a></li>
    <li><a href="https://gist.github.com/ff49ccc1bbaaaa832265ccef96895d98">love_0_9</a></li>
    <li><a href="https://gist.github.com/08ee5c1e7486d7d9f5507e3e6baa5150">luajitPackages.digestif</a></li>
    <li><a href="https://gist.github.com/448be6c5081dc6b35e60f5b778384fd5">luajitPackages.ltermbox</a></li>
    <li><a href="https://gist.github.com/7dafddfd8eadf3120672a7d5e730f5b6">luajitPackages.luaffi</a></li>
  </ul>
</details>
<details>
  <summary>98 packages skipped due to time constraints:</summary>
  <ul>
    <li>cgit</li>
    <li>enlightenment.econnman</li>
    <li>enlightenment.efl</li>
    <li>enlightenment.enlightenment</li>
    <li>enlightenment.ephoto</li>
    <li>enlightenment.evisum</li>
    <li>enlightenment.rage</li>
    <li>enlightenment.terminology</li>
    <li>gimp-with-plugins</li>
    <li>gimpPlugins.gap</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>129 packages built successfully:</summary>
  <ul>
    <li>_90secondportraits</li>
    <li>gegl_0_4 (gnome.gegl_0_4)</li>
    <li>gimp (gimpPlugins.gimp)</li>
    <li>gimpPlugins.exposureBlend</li>
    <li>gimpPlugins.farbfeld</li>
    <li>gimpPlugins.fourier</li>
    <li>gimpPlugins.gimplensfun</li>
    <li>gimpPlugins.lightning</li>
    <li>gimpPlugins.lqrPlugin</li>
    <li>gimpPlugins.resynthesizer</li>
    <li>gimpPlugins.waveletSharpen</li>
    <li>glimpse (glimpsePlugins.gimp)</li>
    <li>glimpsePlugins.exposureBlend</li>
    <li>glimpsePlugins.farbfeld</li>
    <li>glimpsePlugins.fourier</li>
    <li>glimpsePlugins.gap</li>
    <li>glimpsePlugins.gimplensfun</li>
    <li>glimpsePlugins.lightning</li>
    <li>glimpsePlugins.lqrPlugin</li>
    <li>glimpsePlugins.resynthesizer</li>
    <li>glimpsePlugins.waveletSharpen</li>
    <li>gnvim</li>
    <li>knot-resolver</li>
    <li>koreader</li>
    <li>love (love_0_10)</li>
    <li>luabind_luajit</li>
    <li>luajit (luajitPackages.lua ,luajit_2_1)</li>
    <li>luajitPackages.alt-getopt</li>
    <li>luajitPackages.ansicolors</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.basexx</li>
    <li>luajitPackages.binaryheap</li>
    <li>luajitPackages.bit32</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.cassowary</li>
    <li>luajitPackages.cjson</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cosmo</li>
    <li>luajitPackages.coxpcall</li>
    <li>luajitPackages.cqueues</li>
    <li>luajitPackages.cyrussasl</li>
    <li>luajitPackages.dkjson</li>
    <li>luajitPackages.fifo</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.inspect</li>
    <li>luajitPackages.ldbus</li>
    <li>luajitPackages.ldoc</li>
    <li>luajitPackages.lgi</li>
    <li>luajitPackages.linenoise</li>
    <li>luajitPackages.ljsyscall</li>
    <li>luajitPackages.lpeg</li>
    <li>luajitPackages.lpeg_patterns</li>
    <li>luajitPackages.lpeglabel</li>
    <li>luajitPackages.lpty</li>
    <li>luajitPackages.lrexlib-gnu</li>
    <li>luajitPackages.lrexlib-pcre</li>
    <li>luajitPackages.lrexlib-posix</li>
    <li>luajitPackages.lua-cmsgpack</li>
    <li>luajitPackages.lua-iconv</li>
    <li>luajitPackages.lua-lsp</li>
    <li>luajitPackages.lua-messagepack</li>
    <li>luajitPackages.lua-resty-http</li>
    <li>luajitPackages.lua-resty-jwt</li>
    <li>luajitPackages.lua-resty-openidc</li>
    <li>luajitPackages.lua-resty-openssl</li>
    <li>luajitPackages.lua-resty-session</li>
    <li>luajitPackages.lua-term</li>
    <li>luajitPackages.lua-toml</li>
    <li>luajitPackages.lua-yajl</li>
    <li>luajitPackages.lua-zlib</li>
    <li>luajitPackages.lua_cliargs</li>
    <li>luajitPackages.luabitop</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luacov</li>
    <li>luajitPackages.luadbi</li>
    <li>luajitPackages.luadbi-mysql</li>
    <li>luajitPackages.luadbi-postgresql</li>
    <li>luajitPackages.luadbi-sqlite3</li>
    <li>luajitPackages.luadoc</li>
    <li>luajitPackages.luaepnf</li>
    <li>luajitPackages.luaevent</li>
    <li>luajitPackages.luaexpat</li>
    <li>luajitPackages.luafilesystem</li>
    <li>luajitPackages.lualogging</li>
    <li>luajitPackages.luaossl</li>
    <li>luajitPackages.luaposix</li>
    <li>luajitPackages.luarepl</li>
    <li>luajitPackages.luarocks</li>
    <li>luajitPackages.luarocks-nix</li>
    <li>luajitPackages.luasec</li>
    <li>luajitPackages.luasocket</li>
    <li>luajitPackages.luasql-sqlite3</li>
    <li>luajitPackages.luassert</li>
    <li>luajitPackages.luasystem</li>
    <li>luajitPackages.luautf8</li>
    <li>luajitPackages.luazip</li>
    <li>luajitPackages.luuid</li>
    <li>luajitPackages.luv</li>
    <li>luajitPackages.luxio</li>
    <li>luajitPackages.lyaml</li>
    <li>luajitPackages.markdown</li>
    <li>luajitPackages.mediator_lua</li>
    <li>luajitPackages.moonscript</li>
    <li>luajitPackages.mpack</li>
    <li>luajitPackages.nvim-client</li>
    <li>luajitPackages.penlight</li>
    <li>luajitPackages.rapidjson</li>
    <li>luajitPackages.readline</li>
    <li>luajitPackages.say</li>
    <li>luajitPackages.std__debug</li>
    <li>luajitPackages.std_normalize</li>
    <li>luajitPackages.stdlib</li>
    <li>luajitPackages.vicious</li>
    <li>luajitPackages.vstruct</li>
    <li>luajitPackages.wrapLua</li>
    <li>luajit_2_0</li>
    <li>minetest (minetestclient_5)</li>
    <li>minetestserver_5</li>
    <li>mrrescue</li>
    <li>neovim-qt</li>
    <li>neovim-qt-unwrapped</li>
    <li>neovim-remote</li>
    <li>neovim-unwrapped</li>
    <li>nvimpager</li>
    <li>orthorobot</li>
    <li>riko4</li>
    <li>sienna</li>
    <li>wrk</li>
    <li>wrk2</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by lblasc** [comment]
@vcunat thanks! missed it, `version` field is now in sync with commit message

**Review by vcunat — APPROVED** [review]
I did some testing (on the almost-identical previous version of the PR).  It would still be nice if someone who experienced the neovim bug could confirm.

**Comment by gebner** [comment]
It's a bit hard to test because the neovim bug isn't deterministic, but I couldn't reproduce it within a few minutes.

**Comment by mjlbach** [comment]
This is also bigger than neovim, as it affects any protected call to LuaJSON's decode which is used by other projects.

**Pull request merged**
