### PR TITLE
vym: 2.6.11 -> 2.7.0

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
Version bump.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @AndersonTorres

### CODE REVIEW

**Comment by dtzWill** [comment]
Added some fixups I've apparently been sitting on since June? Anyway the first installs the vym manpage, the second fixes some strange installation into $out/vym as well as patches around hardcoded references to `/usr`.

As for the PR before those commits: please modify the commit message to adhere to the guidelines... the PR title is the right text :).  I didn't make this change to avoid force-pushing to your branch w/o discussion at least :).

**Comment by MicrosoftTakeover** [comment]
> As for the PR before those commits: please modify the commit message to adhere to the guidelines... 

Sorry about that, I submitted this PR quickly through the website and I'm not sure how to change a commit message via the web interface.

**Comment by dtzWill** [comment]
> Sorry about that, I submitted this PR quickly through the website and I'm not sure how to change a commit message via the web interface.

I don't either, but since I'm already setup to push to the branch it's easy enough to do locally :).

**Comment by dtzWill** [comment]
Let's give @AndersonTorres a chance to take a look, but otherwise LGTM.   Thanks!

**Comment by nek0** [comment]
Please add also `wrapQtAppsHook` in `nativeBuildInputs` or the executable won't run properly. The underlying issue is described in [this manual section](https://hydra.nixos.org/build/96804884/download/1/nixpkgs/manual.html#sec-language-qt).  
Also bear in mind that version 2.7.1 of vym is not intended to be stable at the moment.

**Comment by dtzWill** [comment]
> Please add also `wrapQtAppsHook` in `nativeBuildInputs` or the executable probably won't run properly. The underlying issue is described in [this manual section](https://hydra.nixos.org/build/96804884/download/1/nixpkgs/manual.html#sec-language-qt).

No need for worrying about wrapping ourselves, that's why this uses mkDerivation from the qt set.

From the manual you linked:

> . If you cannot use mkDerivation or mkDerivationWith above, include wrapQtAppsHook 

---

On the other hand,

> Also bear in mind that version 2.7.1 of vym is not intended to be stable at the moment.

That's good to know, and we should probably use the version upstream marks ready and stable :).

If you don't mind, can you link or point me to where they say 2.7.1 isn't ready? Sorry for missing it!

On a whim checked repology.org stats and looks like I'm not the only one who missed the memo: 
https://repology.org/projects/?search=vym
(2.7.1 is packaged by a number of distributions, most popular version depending on how you count it).  So a PSA might be in order depending what we end up using :).

**Comment by nek0** [comment]
> > Please add also `wrapQtAppsHook` in `nativeBuildInputs` or the executable probably won't run properly. The underlying issue is described in [this manual section](https://hydra.nixos.org/build/96804884/download/1/nixpkgs/manual.html#sec-language-qt).
> 
> No need for worrying about wrapping ourselves, that's why this uses mkDerivation from the qt set.
> 
> From the manual you linked:
> 
> > . If you cannot use mkDerivation or mkDerivationWith above, include wrapQtAppsHook

Ok. I'm sorry, if I caused any hassle.
 
> On the other hand,
> 
> > Also bear in mind that version 2.7.1 of vym is not intended to be stable at the moment.
> 
> That's good to know, and we should probably use the version upstream marks ready and stable :).
> 
> If you don't mind, can you link or point me to where they say 2.7.1 isn't ready? Sorry for missing it!
> 
> On a whim checked repology.org stats and looks like I'm not the only one who missed the memo:
> https://repology.org/projects/?search=vym
> (2.7.1 is packaged by a number of distributions, most popular version depending on how you count it). So a PSA might be in order depending what we end up using :).

Concerning that I only have a screenshot of the release notes window, which pops up after starting vym the first time:

vym_unstable

**Comment by dtzWill** [comment]
On Sun, 17 Nov 2019 09:46:33 -0800, rys ostrovid <notifications@github.com> wrote:
> > > Please add also `wrapQtAppsHook` in `nativeBuildInputs` or the executable probably won't run properly. The underlying issue is described in [this manual section](https://hydra.nixos.org/build/96804884/download/1/nixpkgs/manual.html#sec-language-qt).
> > 
> > No need for worrying about wrapping ourselves, that's why this uses mkDerivation from the qt set.
> > 
> > From the manual you linked:
> > 
> > > . If you cannot use mkDerivation or mkDerivationWith above, include wrapQtAppsHook
> 
> Ok. I'm sorry, if I caused any hassle.

Not at all, we're all trying to ensure this works well for everyone :).

> 
> Concerning that I only have a screenshot of the release notes window, which pops up after starting vym the first time:
> 
> vym_unstable


!!

Wow--so I grabbed the update in June
(eep sorry for not seeing it into a PR myself, and sooner!)
so I very likely completely forgot about this message.

I poked at the code repository, and indeed v2.7.0 is tagged
but there's no 2.7.1 tag?? (what code is in that tarball?! haha)

Thanks for bringing this up-- sounds like we should be on 2.7.0!

**Comment by MicrosoftTakeover** [comment]
I should add that when choosing 2.7.1 I just picked the latest version from sourceforge. There was no indication that it was a development version (and there is a folder for development releases that this was not in). I noticed that 2.7.1 only comes as a tarball without releases for Windows, so I assumed it was a minor version that contained a Linux-specific bug fix.

**Comment by nek0** [comment]
I would also suggest using version 2.7.0 for packaging.

**Review by c0bw3b — APPROVED** [review]
Result of `nix-review pr 73483` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package were build:</summary>

  - vym
</details>

---

```console
$ ./results/vym/bin/vym --version
VYM - View Your Mind (c) 2004-2019 Uwe Drechsel 
   Version: 2.7.0
Build date: 2019-04-14
  Codename: Production release
```

**Pull request merged**
