### PR TITLE
nbxplorer: 2.1.46 -> 2.1.49 & btcpayserver: 1.0.5.9 -> 1.0.6.8

### PR DESCRIPTION
**Pull request by nixbitcoin**
###### Motivation for this change

Update nbxplorer and btcpayserver

Note: I had to manually edit `{3E7D4925-0CA6-4A86-87BA-5BD00E5AA4A5} = {1FC7F660-ADF1-4D55-B61A-85C6AB083C33}` out of `btcpayserver.sln` because it was causing

```
/tmp/btcpayserver-src.XXX/btcpayserver.sln(281): Solution file error MSB5023: Error parsing the nested project section in solution file. A project with the GUID "{3E7D4925-0CA6-4A86-87BA-5BD00E5AA4A5}" is listed as being nested under project "{1FC7F660-ADF1-4D55-B61A-85C6AB083C33}", but does not exist in the solution.
```

Maybe @erikarvstedt can take a look

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112319` at 60d22c24 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/2dacdff174b167f9161180d588a90a17">btcpayserver</a></li></li>
    <li><a href="https://gist.github.com/493e5ae3d4f12ef7b638b3df9717cf9c">nbxplorer</a></li></li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/applications/blockchains/btcpayserver/default.nix:29:3:
```
   |
29 |   buildPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/applications/blockchains/nbxplorer/default.nix:29:3:
```
   |
29 |   buildPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/blockchains/btcpayserver/default.nix:43:3:
```
   |
43 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/blockchains/nbxplorer/default.nix:41:3:
```
   |
41 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112319` at 60d22c24 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/d91ef7c0091f0f4ceebe1c90cca303af">btcpayserver</a></li></li>
    <li><a href="https://gist.github.com/1f5b737aa775ed15198154c7d116e758">nbxplorer</a></li></li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/applications/blockchains/btcpayserver/default.nix:29:3:
```
   |
29 |   buildPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/applications/blockchains/nbxplorer/default.nix:29:3:
```
   |
29 |   buildPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/blockchains/btcpayserver/default.nix:43:3:
```
   |
43 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/blockchains/nbxplorer/default.nix:41:3:
```
   |
41 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Review by erikarvstedt — APPROVED** [review]
I'm getting the same `deps.nix` results when running `update.sh` for `nbxplorer` and `btcpayserver` (with the mentioned manual edit).

The package builds and passes the nix-bitcoin VM test suite.
You can run the tests with [this self-contained script](https://gist.github.com/c98d4a0a5d47db247a0ad5592b516b73).

I've [reported the](https://github.com/btcpayserver/btcpayserver/issues/2262) `dotnet restore` bug.

**Comment by nixbitcoin** [comment]
@mmahut @kcalvinalvin @jonringer please merge

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 112319 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>btcpayserver</li>    <li>nbxplorer</li>  </ul></details>

**Pull request merged**
