### PR TITLE
pump.io service: remove

### PR DESCRIPTION
**Pull request by rvl**
###### Motivation for this change

Updating to the recent 1.0.0 release would add a lot of autogenerated npm packages, for a service with few users. We can add this back once there is a good way of generating npm packages without cluttering the main nixpkgs repo.

See also: http://lists.science.uu.nl/pipermail/nix-dev/2016-September/021694.html

A release note commit is forthcoming.

/cc @svanderburg 
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rvl** [comment]
I forgot to request that this be cherry-picked onto the 16.09 branch. :-)

**Comment by ericsagnes** [comment]
Naive question, is there a motivation for a total removal beside the difficulty to upgrade and the few users?

Even if there are few users, removing the service/package will be troublesome for them.

IMHO, removing services or package because there are a few users is not a healthy position.
First, because "few" is subjective as it is hard to have this kind of information, and second because it means that any "impopular" service/package can disappear any day.
That could result in an unreliable image for NixOS.

If we go for a total removal, this should be documented in the release notes as pump.io was part of the 16.03 release.

**Comment by rvl** [comment]
Hi @ericsagnes, thanks for your input. Those are the only two reasons. :-) It wouldn't even be difficult to upgrade the version, but upgrading would impose another lump of bloat on the project repo.

The release notes commit is forthcoming. I was thinking it should link to a git repo with a README.md containing instructions on how to add pump.io to `configuration.nix` as an external project. This way, the users (if any) will have a way to upgrade.

**Comment by ericsagnes** [comment]
For the record, it seems quite easy to integretate pump.io 1.0.0 in the node2nix/nodePackages infrastructure, so it might make sense to replace the current package with that for better maintenance.

**Comment by domenkozar** [comment]
I'll merge this by end of next week if noone upgrades pump.io until then.

**Comment by abbradar** [comment]
I'm +0 on this because I don't feel competent in NodeJS/pump.io but generally it seems wrong to remove a package because of those reasons (as I understand them, which may be wrong!):

* We don't know exact number of users of this package;
* It still works if updated and this is done trivially;
* The only problem is that new tooling generates a very verbose package.

The last point is unfortunate but why should end-user who needs this package care about this kind of bloat? We can leave this package and instead work on improving node2nix's output so that verbosity won't be a point for not including a package to nixpkgs. If it needs non-trivial maintenance work that's of course another matter, but it's only adding a line to a JSON file IIUC...

**Comment by rvl** [comment]
OK, I think these are good arguments for instead pushing the new version, which I will do on the weekend. Something needs to be done -- either upgrade or remove -- because the new version has XSS-related fixes.

For the record, the previous tooling also produces very verbose packages. It's because of a combination of things -- many small npm packages, loose version bounds in npm packages, and (recursively) each dependency of each package having its own private set of dependencies.

**Comment by domenkozar** [comment]
We'll rather bump the version :)

**Comment by rvl** [comment]
Thanks @domenkozar, sorry about the hassle.

**Pull request closed without merging**
