### PR TITLE
glm: 0.9.9.8 -> 1.0.1, opensplat: 1.1.2 -> 1.1.3, fix frogatto's engine's build

### PR DESCRIPTION
**Pull request by jcaesar**
## Description of changes

* glm
  * changelog: [1.0.0](https://github.com/g-truc/glm/releases/tag/1.0.0) [1.0.1](https://github.com/g-truc/glm/releases/tag/1.0.1)
   * The 1.0 "release" seems to have put some features behind "experimental" [gates](https://github.com/g-truc/glm/blob/45008b225e28eb700fa0f7d3ff69b7c1db94fadf/glm/gtx/matrix_decompose.hpp#L24), so a define is necessary to avoid build failures on some dependent packages
    
 * opensplat
   * changelog: [1.1.3](https://github.com/pierotofy/OpenSplat/releases/tag/v1.1.3)
   * The license change corrects an error on my part in the init pr
 * frogatto / anura-engine:
   * The glm update broke its build, but it also already contained an unrelated `-Werror` build failure . Cleanup en passant.
   * I don't plan on testing whether this actually runs
   
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jcaesar** [comment]
Result of `nixpkgs-review pr 308253` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>arrayfire</li>
    <li>forge</li>
    <li>linux-wallpaperengine</li>
    <li>shadered</li>
  </ul>
</details>
<details>
  <summary>15 packages failed to build:</summary>
  <ul>
    <li>EmptyEpsilon</li>
    <li>klipper-firmware</li>
    <li>klipper-flash</li>
    <li>openscad-unstable</li>
    <li>paperwork</li>
    <li>paperwork.dist</li>
    <li>python311Packages.paperwork-backend</li>
    <li>python311Packages.paperwork-backend.dist</li>
    <li>python311Packages.paperwork-shell</li>
    <li>python311Packages.paperwork-shell.dist</li>
    <li>python312Packages.kicad</li>
    <li>python312Packages.pcbnewtransition</li>
    <li>python312Packages.pcbnewtransition.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
  </ul>
</details>
<details>
  <summary>150 packages built:</summary>
  <ul>
    <li>advi</li>
    <li>anbox</li>
    <li>apostrophe</li>
    <li>arx-libertatis</li>
    <li>asymptote</li>
    <li>asymptote.doc</li>
    <li>asymptote.info</li>
    <li>asymptote.man</li>
    <li>asymptote.tex</li>
    <li>avrdude</li>
    <li>avrdudess</li>
    <li>blahtexml</li>
    <li>blahtexml.doc</li>
    <li>bluespec</li>
    <li>bluespec.doc</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>calcmysky</li>
    <li>capture</li>
    <li>cemu</li>
    <li>clementine</li>
    <li>curv</li>
    <li>djv</li>
    <li>dune3d</li>
    <li>fastcap</li>
    <li>fastcap.doc</li>
    <li>frogatto</li>
    <li>gamescope</li>
    <li>gamescope-wsi</li>
    <li>giph</li>
    <li>glm</li>
    <li>glm.doc</li>
    <li>gource</li>
    <li>gscreenshot</li>
    <li>gscreenshot.dist</li>
    <li>horizon-eda</li>
    <li>kicad</li>
    <li>kicad-small</li>
    <li>kicad-testing</li>
    <li>kicad-testing-small</li>
    <li>kicad-unstable</li>
    <li>kicad-unstable-small</li>
    <li>kicadAddons.kikit</li>
    <li>kicadAddons.kikit-library</li>
    <li>kikit</li>
    <li>kikit.dist</li>
    <li>kodiPackages.visualization-fishbmc</li>
    <li>kodiPackages.visualization-goom</li>
    <li>kodiPackages.visualization-matrix</li>
    <li>kodiPackages.visualization-pictureit</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>kodiPackages.visualization-shadertoy</li>
    <li>kodiPackages.visualization-spectrum</li>
    <li>kodiPackages.visualization-starburst</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>libreoffice (libreoffice-still)</li>
    <li>libreoffice-fresh</li>
    <li>libreoffice-fresh-unwrapped</li>
    <li>libreoffice-qt (libreoffice-qt-still)</li>
    <li>libreoffice-qt-fresh</li>
    <li>libreoffice-qt-fresh-unwrapped</li>
    <li>libreoffice-qt-unwrapped (libreoffice-qt-still-unwrapped)</li>
    <li>libreoffice-unwrapped (libreoffice-still-unwrapped)</li>
    <li>logstalgia</li>
    <li>lomiri.lomiri</li>
    <li>lomiri.lomiri-session</li>
    <li>lomiri.qtmir</li>
    <li>lomiri.qtmir.dev</li>
    <li>maim</li>
    <li>mame</li>
    <li>mame-tools (mame-tools.tools ,mame.tools)</li>
    <li>marble-marcher-ce</li>
    <li>mate.mate-gsettings-overrides</li>
    <li>mate.mate-wayland-session</li>
    <li>mir</li>
    <li>mir.dev</li>
    <li>miriway</li>
    <li>mujoco</li>
    <li>ne</li>
    <li>nuweb</li>
    <li>opencomposite</li>
    <li>opencomposite-helper</li>
    <li>openrw</li>
    <li>opensplat</li>
    <li>opensplatWithCuda</li>
    <li>opentx</li>
    <li>pb_cli</li>
    <li>performous</li>
    <li>projectm</li>
    <li>pymol</li>
    <li>pymol.dist</li>
    <li>python311Packages.horizon-eda</li>
    <li>python311Packages.kicad</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.pcbnewtransition</li>
    <li>python311Packages.pcbnewtransition.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.horizon-eda</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
    <li>qmk</li>
    <li>qmk.dist</li>
    <li>recapp</li>
    <li>rofi-screenshot</li>
    <li>screenkey</li>
    <li>screenkey.dist</li>
    <li>shadershark</li>
    <li>slop</li>
    <li>solarus</li>
    <li>solarus-quest-editor</li>
    <li>solarus.dev</li>
    <li>solarus.lib</li>
    <li>stellarium</li>
    <li>superTux</li>
    <li>texliveFull</li>
    <li>texliveFull.info</li>
    <li>texliveFull.man</li>
    <li>texliveMedium</li>
    <li>texliveMedium.info</li>
    <li>texliveMedium.man</li>
    <li>texlivePackages.asymptote</li>
    <li>texlivePackages.asymptote.info</li>
    <li>texlivePackages.asymptote.man</li>
    <li>texlivePackages.asymptote.tex</li>
    <li>texlivePackages.asymptote.texdoc</li>
    <li>tinygo</li>
    <li>unoconv</li>
    <li>vengi-tools</li>
    <li>vite</li>
    <li>vkmark</li>
    <li>wayfire</li>
    <li>wayfirePlugins.firedecor</li>
    <li>wayfirePlugins.focus-request</li>
    <li>wayfirePlugins.wayfire-plugins-extra</li>
    <li>wayfirePlugins.wayfire-shadows</li>
    <li>wayfirePlugins.wcm</li>
    <li>wayfirePlugins.wf-shell</li>
    <li>wayfirePlugins.windecor</li>
    <li>wayfirePlugins.wwp-switcher</li>
    <li>wf-config</li>
    <li>xrgears</li>
    <li>xyce</li>
    <li>xyce-parallel</li>
    <li>xyce-parallel.doc</li>
    <li>xyce.doc</li>
    <li>yaxg</li>
    <li>yosys-bluespec</li>
    <li>zettlr</li>
  </ul>
</details>

----

paperwork is the only real failure. kicad, pcbnewtransition, torchrl, and klipper all also fail on master, so I'll ignore those. What's a bit more mysterious to me is openscad-unstable.
```bash
 env NIXPKGS_ALLOW_UNFREE=1 nix build --max-jobs 2 -vL --json --impure --expr 'let pkgs = import (builtins.getFlake "github:NixOS/nixpkgs/b4710c1ee583250f6b5ad7d9cf7cd58372bd8dca") { system = "x86_64-linux"; }; in pkgs.openscad-unstable.overrideAttrs { version = "change-to-force-rebuild"; }'
```
fails on my machine, but without the `overrideAttrs`, it gets downloaded from cache. Maybe a reproducability issue.

**Comment by smancill** [comment]
Doesn't build on macOS, I'll take a look tomorrow for a solution.

**Comment by jcaesar** [comment]
Ah, I didn't know what I was looking at because there wasn't a red × on the build status. Give me a few days, I'll see if I can fix it.

**Comment by smancill** [comment]
I don't think it will work with your latest change:

```
+    # Avoid failure on mac
+    # /tmp/nix-build-glm-1.0.1.drv-0/source/glm/detail/func_packing.inl:165:3: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
+    #             u.in[1] = detail::toFloat16(v.y);
+    (lib.cmakeFeature "CMAKE_CXX_FLAGS" "-Wno-error")
```

Please revert it and apply this instead:

``` diff
diff --git i/pkgs/development/libraries/glm/default.nix w/pkgs/development/libraries/glm/default.nix
index c26540e842b4..3894db5ab9c8 100644
--- i/pkgs/development/libraries/glm/default.nix
+++ w/pkgs/development/libraries/glm/default.nix
@@ -19,8 +19,12 @@ stdenv.mkDerivation rec {
 
   nativeBuildInputs = [ cmake ];
 
-  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102823
-  env.NIX_CFLAGS_COMPILE = lib.optionalString (stdenv.cc.isGNU && lib.versionAtLeast stdenv.cc.version "11") "-fno-ipa-modref";
+  env.NIX_CFLAGS_COMPILE =
+    # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102823
+    if (stdenv.cc.isGNU && lib.versionAtLeast stdenv.cc.version "11") then "-fno-ipa-modref"
+    # Fix compilation errors on darwin
+    else if (stdenv.cc.isClang) then "-Wno-error"
+    else "";
 
   cmakeFlags = [
     (lib.cmakeBool "BUILD_SHARED_LIBS" false)
```

I just built it on macOS.

**Comment by jcaesar** [comment]
That seems to have worked, I have no idea why. Should I also change the other uses of CMAKE_CXX_FLAGS and CXXFLAGS to NIX_CFLAGS_COMPILE?

**Comment by jcaesar** [comment]
@Scrumplex I believe this is ready for merge. Do you have any comments?

**Review by smancill — APPROVED** [review]

**Comment by Scrumplex** [comment]
Result of `nixpkgs-review pr 308253` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>arrayfire</li>
    <li>forge</li>
    <li>linux-wallpaperengine</li>
    <li>python312Packages.kicad</li>
    <li>python312Packages.pcbnewtransition</li>
    <li>python312Packages.pcbnewtransition.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>shadered</li>
  </ul>
</details>
<details>
  <summary>151 packages failed to build:</summary>
  <ul>
    <li>EmptyEpsilon</li>
    <li>advi</li>
    <li>anbox</li>
    <li>apostrophe</li>
    <li>arx-libertatis</li>
    <li>asymptote</li>
    <li>asymptote.doc</li>
    <li>asymptote.info</li>
    <li>asymptote.man</li>
    <li>asymptote.tex</li>
    <li>avrdude</li>
    <li>avrdudess</li>
    <li>blahtexml</li>
    <li>blahtexml.doc</li>
    <li>bluespec</li>
    <li>bluespec.doc</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>calcmysky</li>
    <li>capture</li>
    <li>cemu</li>
    <li>clementine</li>
    <li>curv</li>
    <li>djv</li>
    <li>dune3d</li>
    <li>fastcap</li>
    <li>fastcap.doc</li>
    <li>frogatto</li>
    <li>gamescope</li>
    <li>gamescope-wsi</li>
    <li>giph</li>
    <li>gource</li>
    <li>gscreenshot</li>
    <li>gscreenshot.dist</li>
    <li>horizon-eda</li>
    <li>kicad</li>
    <li>kicad-small</li>
    <li>kicad-testing</li>
    <li>kicad-testing-small</li>
    <li>kicad-unstable</li>
    <li>kicad-unstable-small</li>
    <li>kicadAddons.kikit</li>
    <li>kicadAddons.kikit-library</li>
    <li>kikit</li>
    <li>kikit.dist</li>
    <li>klipper-firmware</li>
    <li>klipper-flash</li>
    <li>kodiPackages.visualization-fishbmc</li>
    <li>kodiPackages.visualization-goom</li>
    <li>kodiPackages.visualization-matrix</li>
    <li>kodiPackages.visualization-pictureit</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>kodiPackages.visualization-shadertoy</li>
    <li>kodiPackages.visualization-spectrum</li>
    <li>kodiPackages.visualization-starburst</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>libreoffice (libreoffice-still)</li>
    <li>libreoffice-fresh</li>
    <li>libreoffice-fresh-unwrapped</li>
    <li>libreoffice-qt (libreoffice-qt-still)</li>
    <li>libreoffice-qt-fresh</li>
    <li>libreoffice-qt-fresh-unwrapped</li>
    <li>libreoffice-qt-unwrapped (libreoffice-qt-still-unwrapped)</li>
    <li>libreoffice-unwrapped (libreoffice-still-unwrapped)</li>
    <li>lomiri.lomiri</li>
    <li>lomiri.lomiri-session</li>
    <li>lomiri.qtmir</li>
    <li>lomiri.qtmir.dev</li>
    <li>maim</li>
    <li>mame</li>
    <li>mame-tools (mame-tools.tools ,mame.tools)</li>
    <li>marble-marcher-ce</li>
    <li>mate.mate-gsettings-overrides</li>
    <li>mate.mate-wayland-session</li>
    <li>mir</li>
    <li>mir.dev</li>
    <li>miriway</li>
    <li>mujoco</li>
    <li>ne</li>
    <li>nuweb</li>
    <li>opencomposite</li>
    <li>opencomposite-helper</li>
    <li>openrw</li>
    <li>openscad-unstable</li>
    <li>opensplat</li>
    <li>opensplatWithCuda</li>
    <li>opentx</li>
    <li>paperwork</li>
    <li>paperwork.dist</li>
    <li>pb_cli</li>
    <li>performous</li>
    <li>projectm</li>
    <li>pymol</li>
    <li>pymol.dist</li>
    <li>python311Packages.horizon-eda</li>
    <li>python311Packages.kicad</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.paperwork-backend</li>
    <li>python311Packages.paperwork-backend.dist</li>
    <li>python311Packages.paperwork-shell</li>
    <li>python311Packages.paperwork-shell.dist</li>
    <li>python311Packages.pcbnewtransition</li>
    <li>python311Packages.pcbnewtransition.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.horizon-eda</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
    <li>qmk</li>
    <li>qmk.dist</li>
    <li>recapp</li>
    <li>rofi-screenshot</li>
    <li>screenkey</li>
    <li>screenkey.dist</li>
    <li>slop</li>
    <li>solarus</li>
    <li>solarus-quest-editor</li>
    <li>solarus.dev</li>
    <li>solarus.lib</li>
    <li>stellarium</li>
    <li>texliveFull</li>
    <li>texliveFull.info</li>
    <li>texliveFull.man</li>
    <li>texliveMedium</li>
    <li>texliveMedium.info</li>
    <li>texliveMedium.man</li>
    <li>texlivePackages.asymptote</li>
    <li>tinygo</li>
    <li>unoconv</li>
    <li>vengi-tools</li>
    <li>vite</li>
    <li>vkmark</li>
    <li>wayfire</li>
    <li>wayfirePlugins.firedecor</li>
    <li>wayfirePlugins.focus-request</li>
    <li>wayfirePlugins.wayfire-plugins-extra</li>
    <li>wayfirePlugins.wayfire-shadows</li>
    <li>wayfirePlugins.wcm</li>
    <li>wayfirePlugins.wf-shell</li>
    <li>wayfirePlugins.windecor</li>
    <li>wayfirePlugins.wwp-switcher</li>
    <li>wf-config</li>
    <li>xrgears</li>
    <li>xyce</li>
    <li>xyce-parallel</li>
    <li>xyce-parallel.doc</li>
    <li>xyce.doc</li>
    <li>yaxg</li>
    <li>yosys-bluespec</li>
    <li>zettlr</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>glm</li>
    <li>glm.doc</li>
    <li>logstalgia</li>
    <li>shadershark</li>
    <li>superTux</li>
    <li>texlivePackages.asymptote.info</li>
    <li>texlivePackages.asymptote.man</li>
    <li>texlivePackages.asymptote.tex</li>
    <li>texlivePackages.asymptote.texdoc</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
I couldn't figure out which one of these was a direct failure

**Comment by Scrumplex** [comment]
With the following patch, one build failure can be fixed:

```patch
From c42326ba3bf4ee45947d6663cca2e69aa90bb6f7 Mon Sep 17 00:00:00 2001
From: Sefa Eyeoglu <contact@scrumplex.net>
Date: Sun, 12 May 2024 22:27:48 +0200
Subject: [PATCH] EmptyEpsilon: define GLM_ENABLE_EXPERIMENTAL

Signed-off-by: Sefa Eyeoglu <contact@scrumplex.net>
---
 pkgs/games/empty-epsilon/default.nix | 22 ++++++++++++----------
 1 file changed, 12 insertions(+), 10 deletions(-)

diff --git a/pkgs/games/empty-epsilon/default.nix b/pkgs/games/empty-epsilon/default.nix
index 20f4f5855a35..3c9560877081 100644
--- a/pkgs/games/empty-epsilon/default.nix
+++ b/pkgs/games/empty-epsilon/default.nix
@@ -33,7 +33,8 @@ let
     buildInputs = [ sfml libX11 glm SDL2 ];
 
     cmakeFlags = [
-      "-DFETCHCONTENT_SOURCE_DIR_BASIS=${basis-universal}"
+      (lib.cmakeFeature "FETCHCONTENT_SOURCE_DIR_BASIS" "${basis-universal}")
+      (lib.cmakeFeature "CMAKE_CXX_FLAGS" "-DGLM_ENABLE_EXPERIMENTAL")
     ];
 
     meta = with lib; {
@@ -63,15 +64,16 @@ stdenv.mkDerivation {
   buildInputs = [ serious-proton sfml glew libX11 python3 glm SDL2 ninja ];
 
   cmakeFlags = [
-    "-DSERIOUS_PROTON_DIR=${serious-proton.src}"
-    "-DCPACK_PACKAGE_VERSION=${version.emptyepsilon}"
-    "-DCPACK_PACKAGE_VERSION_MAJOR=${major}"
-    "-DCPACK_PACKAGE_VERSION_MINOR=${minor}"
-    "-DCPACK_PACKAGE_VERSION_PATCH=${patch.emptyepsilon}"
-    "-DFETCHCONTENT_SOURCE_DIR_BASIS=${basis-universal}"
-    "-DFETCHCONTENT_SOURCE_DIR_MESHOPTIMIZER=${meshoptimizer.src}"
-    "-DCMAKE_AR=${stdenv.cc.cc}/bin/gcc-ar"
-    "-DCMAKE_RANLIB=${stdenv.cc.cc}/bin/gcc-ranlib"
+    (lib.cmakeFeature "SERIOUS_PROTON_DIR" "${serious-proton.src}")
+    (lib.cmakeFeature "CPACK_PACKAGE_VERSION" "${version.emptyepsilon}")
+    (lib.cmakeFeature "CPACK_PACKAGE_VERSION_MAJOR" "${major}")
+    (lib.cmakeFeature "CPACK_PACKAGE_VERSION_MINOR" "${minor}")
+    (lib.cmakeFeature "CPACK_PACKAGE_VERSION_PATCH" "${patch.emptyepsilon}")
+    (lib.cmakeFeature "FETCHCONTENT_SOURCE_DIR_BASIS" "${basis-universal}")
+    (lib.cmakeFeature "FETCHCONTENT_SOURCE_DIR_MESHOPTIMIZER" "${meshoptimizer.src}")
+    (lib.cmakeFeature "CMAKE_AR" "${stdenv.cc.cc}/bin/gcc-ar")
+    (lib.cmakeFeature "CMAKE_RANLIB" "${stdenv.cc.cc}/bin/gcc-ranlib")
+    (lib.cmakeFeature "CMAKE_CXX_FLAGS" "-DGLM_ENABLE_EXPERIMENTAL")
     "-G Ninja"
   ];
 
-- 
2.44.0
```

I'll have to re-run nixpkgs-review with a reduce amount of parallelization, as it makes my system go OOM (16 logical threads and 32 GB of RAM)

**Comment by jcaesar** [comment]
I'm not sure why ofborg just pinged several people, but I guess I better give a status report
* I'm still investigating one last build failure in tinygo
* Scrumplex patch has fixed the EmptyEpsilon buildfailure (I accidentally ignored it thinking it's some kind of metapackage…)
* (Heads up if you're running `nixpkgs-rewiew`: The torch build requires 72 GiB of memory at `"--build-args=--cores 20"`. (And takes 2 hours on my box))

**Comment by Scrumplex** [comment]
Maybe you should rebase this on staging?
Just make sure to mark the PR as a draft so no one gets pinged while you rebase and then change the merge base on GitHub

**Comment by jcaesar** [comment]
@Scrumplex Seems like that won't be necessary, the remaining failures I saw were all flaky and went away after a few retires. Or is there any other reason this should be on staging?

---

Result of `nixpkgs-review pr 308253` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>arrayfire</li>
    <li>forge</li>
    <li>linux-wallpaperengine</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>shadered</li>
  </ul>
</details>
<details>
  <summary>164 packages built:</summary>
  <ul>
    <li>EmptyEpsilon</li>
    <li>advi</li>
    <li>anbox</li>
    <li>apostrophe</li>
    <li>arx-libertatis</li>
    <li>asymptote</li>
    <li>asymptote.doc</li>
    <li>asymptote.info</li>
    <li>asymptote.man</li>
    <li>asymptote.tex</li>
    <li>avrdude</li>
    <li>avrdudess</li>
    <li>blahtexml</li>
    <li>blahtexml.doc</li>
    <li>bluespec</li>
    <li>bluespec.doc</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>calcmysky</li>
    <li>capture</li>
    <li>cemu</li>
    <li>clementine</li>
    <li>curv</li>
    <li>djv</li>
    <li>dune3d</li>
    <li>fastcap</li>
    <li>fastcap.doc</li>
    <li>frogatto</li>
    <li>gamescope</li>
    <li>gamescope-wsi</li>
    <li>giph</li>
    <li>glm</li>
    <li>glm.doc</li>
    <li>gource</li>
    <li>gscreenshot</li>
    <li>gscreenshot.dist</li>
    <li>horizon-eda</li>
    <li>kicad</li>
    <li>kicad-small</li>
    <li>kicad-testing</li>
    <li>kicad-testing-small</li>
    <li>kicad-unstable</li>
    <li>kicad-unstable-small</li>
    <li>kicadAddons.kikit</li>
    <li>kicadAddons.kikit-library</li>
    <li>kikit</li>
    <li>kikit.dist</li>
    <li>klipper-firmware</li>
    <li>klipper-flash</li>
    <li>kodiPackages.visualization-fishbmc</li>
    <li>kodiPackages.visualization-goom</li>
    <li>kodiPackages.visualization-matrix</li>
    <li>kodiPackages.visualization-pictureit</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>kodiPackages.visualization-shadertoy</li>
    <li>kodiPackages.visualization-spectrum</li>
    <li>kodiPackages.visualization-starburst</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>libreoffice (libreoffice-still)</li>
    <li>libreoffice-fresh</li>
    <li>libreoffice-fresh-unwrapped</li>
    <li>libreoffice-qt (libreoffice-qt-still)</li>
    <li>libreoffice-qt-fresh</li>
    <li>libreoffice-qt-fresh-unwrapped</li>
    <li>libreoffice-qt-unwrapped (libreoffice-qt-still-unwrapped)</li>
    <li>libreoffice-unwrapped (libreoffice-still-unwrapped)</li>
    <li>logstalgia</li>
    <li>lomiri.lomiri</li>
    <li>lomiri.lomiri-session</li>
    <li>lomiri.qtmir</li>
    <li>lomiri.qtmir.dev</li>
    <li>maim</li>
    <li>mame</li>
    <li>mame-tools (mame-tools.tools ,mame.tools)</li>
    <li>marble-marcher-ce</li>
    <li>mate.mate-gsettings-overrides</li>
    <li>mate.mate-wayland-session</li>
    <li>mir</li>
    <li>mir.dev</li>
    <li>miriway</li>
    <li>mujoco</li>
    <li>ne</li>
    <li>nuweb</li>
    <li>opencomposite</li>
    <li>opencomposite-helper</li>
    <li>openrw</li>
    <li>openscad-unstable</li>
    <li>opensplat</li>
    <li>opensplatWithCuda</li>
    <li>opentx</li>
    <li>paperwork</li>
    <li>paperwork.dist</li>
    <li>pb_cli</li>
    <li>performous</li>
    <li>projectm</li>
    <li>pymol</li>
    <li>pymol.dist</li>
    <li>python311Packages.dm-control</li>
    <li>python311Packages.dm-control.dist</li>
    <li>python311Packages.horizon-eda</li>
    <li>python311Packages.kicad</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.paperwork-backend</li>
    <li>python311Packages.paperwork-backend.dist</li>
    <li>python311Packages.paperwork-shell</li>
    <li>python311Packages.paperwork-shell.dist</li>
    <li>python311Packages.pcbnewtransition</li>
    <li>python311Packages.pcbnewtransition.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.horizon-eda</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
    <li>qmk</li>
    <li>qmk.dist</li>
    <li>recapp</li>
    <li>rofi-screenshot</li>
    <li>screenkey</li>
    <li>screenkey.dist</li>
    <li>shadershark</li>
    <li>slop</li>
    <li>solarus</li>
    <li>solarus-quest-editor</li>
    <li>solarus.dev</li>
    <li>solarus.lib</li>
    <li>stellarium</li>
    <li>superTux</li>
    <li>texliveFull</li>
    <li>texliveFull.info</li>
    <li>texliveFull.man</li>
    <li>texliveMedium</li>
    <li>texliveMedium.info</li>
    <li>texliveMedium.man</li>
    <li>texlivePackages.asymptote</li>
    <li>texlivePackages.asymptote.info</li>
    <li>texlivePackages.asymptote.man</li>
    <li>texlivePackages.asymptote.tex</li>
    <li>texlivePackages.asymptote.texdoc</li>
    <li>tinygo</li>
    <li>unoconv</li>
    <li>vengi-tools</li>
    <li>vite</li>
    <li>vkmark</li>
    <li>wayfire</li>
    <li>wayfirePlugins.firedecor</li>
    <li>wayfirePlugins.focus-request</li>
    <li>wayfirePlugins.wayfire-plugins-extra</li>
    <li>wayfirePlugins.wayfire-shadows</li>
    <li>wayfirePlugins.wcm</li>
    <li>wayfirePlugins.wf-shell</li>
    <li>wayfirePlugins.windecor</li>
    <li>wayfirePlugins.wwp-switcher</li>
    <li>wf-config</li>
    <li>xrgears</li>
    <li>xyce</li>
    <li>xyce-parallel</li>
    <li>xyce-parallel.doc</li>
    <li>xyce.doc</li>
    <li>yaxg</li>
    <li>yosys-bluespec</li>
    <li>zettlr</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
> Or is there any other reason this should be on staging?

This PR causes quite a few large rebuilds. I am not sure what the threshold for moving a change to staging usually is, but this one is probably on the edge :D

**Comment by smancill** [comment]
> > Or is there any other reason this should be on staging?
> 
> This PR causes quite a few large rebuilds. I am not sure what the threshold for moving a change to staging usually is, but this one is probably on the edge :D

From the CONTRIBUTING docs:

> As a rule of thumb, if the number of rebuilds is over 500, it can be considered a mass rebuild.

If you agree, I think we can go ahead and merge this.

**Comment by jcaesar** [comment]
> If you agree, I think we can go ahead and merge this.

@Scrumplex I belive this was a question to you.

Can I ask you whether you still think this should be rebased onto staging?

**Comment by Scrumplex** [comment]
Perhaps we can ask one of the ~~elders~~ committers and let them decide. I'd personally rebase changes onto `staging`, if I can't easily test them using `nixpkgs-review` due to the amount of (large) rebuilds

**Comment by jcaesar** [comment]
Superceded by #316573 (merged).

**Pull request closed without merging**
