### PR TITLE
Sway 1.5

### PR DESCRIPTION
**Pull request by primeos**
###### Status

Basic functionality works, but I didn't review the changelogs yet.
Feedback about bugs, possible improvements, etc. is welcome :)

TODOs:
- [x] Test wlroots incompatibilities (rebuilds)
  - All good. Changes: `cage-unstable sway-contrib.grimshot (2020-05-08 → 1.5-rc1) hikari sway (1.4 → 1.5-rc1) sway-contrib.inactive-windows-transparency (1.4 → 1.5-rc1) sway-unwrapped (1.4 → 1.5-rc1) waybar wlroots (0.10.1 → 2020-06-08)`
  - Final `nixpkgs-review` (the `sway-contrib.inactive-windows-transparency` failure is unrelated to this PR):
    ```
    8 packages updated:
    cage-unstable sway-contrib.grimshot (2020-05-08 → 1.5) hikari sway (1.4 → 1.5) sway-contrib.inactive-windows-transparency (1.4 → 1.5) sway-unwrapped (1.4 → 1.5) waybar wlroots (0.10.1 → 0.11.0)
    
    $ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/nix-review/.cache/nixpkgs-review/rev-6ab6fbe7442b037d03121e64babc34daceb275ad/build.nix
    warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
    builder for '/nix/store/blycqf23hysgfxfykca8fh35hcpzz0gl-python3.8-i3ipc-2.1.1.drv' failed with exit code 1; last 10 log lines:
          res = hook_impl.function(*args)
        File "/nix/store/4p440acz02ccpa8w1h9i9dy95k6vvv43-python3.8-pytest-xvfb-1.2.0/lib/python3.8/site-packages/pytest_xvfb.py", line 99, in pytest_unconfigure
          config.xvfb.stop()
        File "/nix/store/4p440acz02ccpa8w1h9i9dy95k6vvv43-python3.8-pytest-xvfb-1.2.0/lib/python3.8/site-packages/pytest_xvfb.py", line 61, in stop
          self._virtual_display.stop()
        File "/nix/store/vym7aglbs81c1rwv9m10n1h2mj0hn3ms-python3.8-PyVirtualDisplay-1.3.2/lib/python3.8/site-packages/pyvirtualdisplay/display.py", line 76, in stop
          self._obj.stop()
        File "/nix/store/vym7aglbs81c1rwv9m10n1h2mj0hn3ms-python3.8-PyVirtualDisplay-1.3.2/lib/python3.8/site-packages/pyvirtualdisplay/abstractdisplay.py", line 318, in stop
          raise XStartError("stop() is called before start().")
      pyvirtualdisplay.abstractdisplay.XStartError: stop() is called before start().
    cannot build derivation '/nix/store/b3r1nr85880izr51i10waixh8j475mgh-sway-inactive-windows-transparency-1.5.drv': 1 dependencies couldn't be built
    cannot build derivation '/nix/store/csc595v9m2m7d4vybhwwk1r0r1a8xi4m-env.drv': 1 dependencies couldn't be built
    [10 built (1 failed), 265 copied (700.6 MiB), 161.1 MiB DL]
    error: build of '/nix/store/csc595v9m2m7d4vybhwwk1r0r1a8xi4m-env.drv' failed
    1 package failed to build:
    sway-contrib.inactive-windows-transparency
    
    7 packages built:
    cage hikari sway sway-contrib.grimshot sway-unwrapped waybar wlroots
    ```
- [x] Wait for the final release and squash the commits

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Elyhaka** [comment]
Tested it for 2 hours:
 - Sway itself: ok
 - Waybar: ok
 - Wofi: ok
 - Mako: ok
 - Wob: ok

As of 1.5-rc1, everything is running smoothly! Going to use it for the next few days and we'll see :).

**Comment by Elyhaka** [comment]
Tested 1.2, still working flawlessly

**Comment by Elyhaka** [comment]
Sway 1.5 got released recently, tried it by modifying your PR locally, everything worked as expected.

**Review by Synthetica9 — APPROVED** [review]
Works for me :+1:

**Comment by primeos** [comment]
Sorry about the delay, I messed up my time management by a few minutes...
@Elyhaka @Synthetica9 huge thanks for your testing :)

**Pull request merged**
