### PR TITLE
Add nvidia_x11 as a dependency in Theano

### PR DESCRIPTION
**Pull request by smatting**
###### Motivation for this change

Fixes issue https://github.com/NixOS/nixpkgs/issues/38850

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by smatting** [comment]
I have no means to test it, so I don't know.

As a comparison, `tensorflow` also seems to work only on linux:
```
  tensorflow = callPackage ../development/python-modules/tensorflow rec {
    cudaSupport = pkgs.config.cudaSupport or false;
    inherit (pkgs.linuxPackages) nvidia_x11;
    cudatoolkit = pkgs.cudatoolkit9;
    cudnn = pkgs.cudnn_cudatoolkit9;
  };
```

**Comment by smatting** [comment]
Should I add the possibility to build the derivation with `nvidia_x11=null`? That way `libcuda.so` should be resolved to a nvidia driver that is not installed with nixos. Following the example from `tensorflow` i'd still leave `nvidia_x11 = pkgs.linuxPackages.nvidia_x11` as a default.

**Comment by FRidh** [comment]
This is good enough for now. Please get rid of the merge, rebase onto master, and make sure you have a commit per package you change.

**Comment by smatting** [comment]
All done.

**Comment by SomeoneSerge** [comment]
Hello! Have you tried the `addOpenGLRunpath` way, instead of linking directly to the hardware-dependent driver?

**Comment by FRidh** [comment]
@SomeoneSerge note this is a merge from several years ago

**Pull request merged**
