### PR TITLE
maintainers/teams: add kodi team

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
- create a `kodi` maintainers team
- applying several excellent suggestions @SuperSandro2000 had mentioned in #116493 :sparkling_heart: 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
Future work:
- rename some packages so naming is consistent? (I think having a `.` in the `pname` is probably undesirable, also see `controllers.*`)
- "properly" (according to upstream) package `kodi`, `kodi-x11`, `kodi-wayland`, and `kodi-gbm`
  - `kodi` should build with `x11Support`, `waylandSupport`, and `gbmSupport`
  - `kodi-x11`, `kodi-wayland`, and `kodi-gbm` should **only** build with the respective options

Do we know anyone who runs `kodi-gbm` and could do some testing? :thinking:

**Comment by titanous** [comment]
When someone has a sec, can they remove me as a maintainer from kodi packages? Thanks!

**Comment by aanderse** [comment]
> When someone has a sec, can they remove me as a maintainer from kodi packages? Thanks!

Can do. Sorry to see you go, but thanks for your work! :cry:

**Comment by aanderse** [comment]
ping @grahamc about creating a `github` team for `kodi`...

**Comment by aanderse** [comment]
I have created the @NixOS/kodi team and invited the members from this PR.

**Pull request merged**
