### PR TITLE
kcl: 0.9.8 -> 0.10.0

### PR DESCRIPTION
**Pull request by selfuryon**
## Description of changes

Update `kcl`, `kclvm` and `kclvm-cli` to the latest version (v0.10.0)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].
@peefy 

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by momeemt** [comment]
Result of `nixpkgs-review pr 345613` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>kcl</li>
    <li>kclvm</li>
    <li>kclvm_cli</li>
  </ul>
</details>

**Comment by momeemt** [comment]
I received the following error when I built this package.

```
exporting https://github.com/kcl-lang/rust-protoc-bin-vendored (rev 53c1f87ffc3027642ea6b822025b1dc699a3135b) into /nix/store/vsf9ga9iy9y50dwg9c4yycd7qylxkmjd-rust-protoc-bin-vendored-53c1f87
Initialized empty Git repository in /nix/store/vsf9ga9iy9y50dwg9c4yycd7qylxkmjd-rust-protoc-bin-vendored-53c1f87/.git/
fatal: unable to access 'https://github.com/kcl-lang/rust-protoc-bin-vendored/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
fatal: unable to access 'https://github.com/kcl-lang/rust-protoc-bin-vendored/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
fatal: unable to access 'https://github.com/kcl-lang/rust-protoc-bin-vendored/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
Unable to checkout 53c1f87ffc3027642ea6b822025b1dc699a3135b from https://github.com/kcl-lang/rust-protoc-bin-vendored.
```

**Comment by selfuryon** [comment]
> OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme

Sorry, I haven't darwin to test, but your error looks like [that](https://github.com/curl/curl/issues/10702) and seems not related to kcl itself, more like to ca-bundle?

**Comment by selfuryon** [comment]
@momeemt Hey! Did you manage to run kcl on your macos?

**Comment by YvanDaSilva** [comment]
@selfuryon @Peefy @momeemt 
I could build locally no issue on darwin. I will update the comment in a bit with the outputs.

**Comment by selfuryon** [comment]
> @selfuryon @Peefy @momeemt I could build locally no issue on darwin. I will update the comment in a bit with the outputs.
> ### aarch64-darwin
> 
> ```
> sysctl kern.version
> kern.version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030
> 
> ./result/bin/kcl --version
> kcl version v0.10.0
> ```
> 
> Just a file to test that binary does something kcl related
> 
> ```
> cat pkgs/by-name/kc/hello.k
> hello = "KCL 0.10.0"
> 
> ./result/bin/kcl pkgs/by-name/kc/hello.k
> hello: KCL 0.10.0
> ```
> 
> #### compilation
> 
> ```
>  git log
> commit 7c0aa0521d0c350b3900eabbaf8a43cdd9ccf414 (HEAD, selfuryon/chore/kcl-update)
> Author: Sergey Yakovlev <selfuryon@pm.me>
> Date:   Tue Oct 1 02:37:16 2024 +0300
> 
>     kcl: 0.9.8 -> 0.10.0
> ...
> 
> export NIXPKGS=/Users/xxxxx/Projects/cloned/nixpkgs
> nix-build $NIXPKGS -A kcl
> ...
> unpacking source archive /nix/store/2wy1ph0zzsapxf3fsl5s6y3cwp2ci3n7-source
> source root is source
> Running phase: patchPhase
> Running phase: updateAutotoolsGnuConfigScriptsPhase
> Running phase: configurePhase
> Running phase: buildPhase
> Building subPackage ./cmd/kcl
> Running phase: checkPhase
> ?       kcl-lang.io/cli/cmd/kcl [no test files]
> Running phase: installPhase
> Running phase: fixupPhase
> checking for references to /private/tmp/nix-build-kcl-0.10.0.drv-0/ in /nix/store/5z0rvlx639in2asmzyxmv6xr59xd7yn2-kcl-0.10.0...
> patching script interpreter paths in /nix/store/5z0rvlx639in2asmzyxmv6xr59xd7yn2-kcl-0.10.0
> /nix/store/5z0rvlx639in2asmzyxmv6xr59xd7yn2-kcl-0.10.0
> 
> > eza -lha --no-user result/bin
> Permissions Size Date Modified Name
> .r-xr-xr-x   71M  1 Jan  1970  .kcl-wrapped
> .r-xr-xr-x  1.4k  1 Jan  1970  kcl
> ```

Thanks!

**Comment by momeemt** [comment]
Result of `nixpkgs-review pr 345613` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>kcl</li>
    <li>kclvm</li>
    <li>kclvm_cli</li>
  </ul>
</details>

**Review by momeemt — APPROVED** [review]
@selfuryon I am really sorry for the very late reply, I missed the mentions. I reinstalled Nix and set up the certificates and it builds fine in my local environment, Thank you for your contribution!

**Comment by selfuryon** [comment]
@NixOS/nixpkgs-merge-bot merge

**Pull request merged**
