### PR TITLE
nixos/usbStorage: apply upstream

### PR DESCRIPTION
**Pull request by bb2020**
## Description of changes
https://github.com/torvalds/linux/commit/24eca2dce0f8d19db808c972b0281298d0bafe99

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
Does this need to be made dependent on the kernel version? I'm becoming more and more convinced this option shouldn't be enabled by default, considering it has needed repeated tweaking.

**Comment by bb2020** [comment]
> Does this need to be made dependent on the kernel version?

No. Changes are already in the current 6.1 kernel.

> I'm becoming more and more convinced this option shouldn't be enabled by default, considering it has needed repeated tweaking.

I presume there is a possibility of data loss if you shutdown your system (and drive) without flushing the SCSI cache.
Although I don't know anyone has ever encountered it.

**Comment by ElvishJerricco** [comment]
> No. Changes are already in the current 6.1 kernel.

We support older kernels than 6.1.

**Comment by ElvishJerricco** [comment]
Ok, the more I look at this and the surrounding kernel patches, the crazier this option is.

1. Now the NixOS option is named incorrectly given that the attr name has changed from `manage_system_start_stop` to `manage_shutdown`.
2. Why is this specific to USB? The kernel patches are for *all* ATA / SCSI drives. But the [original bug report](https://bugzilla.kernel.org/show_bug.cgi?id=205107) *never* figured out why the problem was specific to USB disks.
3. Actually, why are we getting rid of `manage_system_start_stop`? It sounds like both of these attrs do relevant things. Based on [the patch](https://github.com/torvalds/linux/commit/24eca2dce0f8d19db808c972b0281298d0bafe99), it seems like both of these attrs do the exact same thing, except this new one *only* applies during shutdown instead of also during suspend and hibernate.
4. Do other distros do this? I really don't like that we have this thing that's been in flux for a while based on an unresolved upstream bug report that, as far as I can tell, no one actually understands.

**Comment by bb2020** [comment]
Because `scsi` over `usb` is hacky and problems like this occur. For example `discard_granularity` is almost always incorrectly populated. I don't want to touch `suspend` as you can get away with not using `suspend` at all, but you need to use `poweroff`.

I am changing the naming. We can disable this by default, if you prefer.

**Comment by ElvishJerricco** [comment]
@bb2020 You need to use `mkRenamedOptionModule` when renaming an option.

I would prefer for this to be disabled by default.

**Comment by bb2020** [comment]
@ElvishJerricco

**Pull request merged**
