### PR TITLE
WIP: pms: init at 0.42

### PR DESCRIPTION
**Pull request by matthiasbeyer**
WIP, can a go person help me here?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@bjornfor @rvolosatovs @zimbatm you maintain go packages, can you explain what's the error here telling me, please?

**Comment by bjornfor** [comment]
Where's the error? I don't think I maintain any go package, but I'm interested in learning how to (package golang projects with Nix).

**Comment by matthiasbeyer** [comment]
The error is:

```
$ nix-build -A pms
these derivations will be built:
  /nix/store/c03q6swidr4ziqib3z4vhkzs6g23amc1-pms-0.42-go-modules.drv
  /nix/store/fk0dpczhf39qkz13x5y4a2qsih8h7n38-pms-0.42.drv
building '/nix/store/c03q6swidr4ziqib3z4vhkzs6g23amc1-pms-0.42-go-modules.drv'...
unpacking sources
unpacking source archive /nix/store/vmw9qfadynclkyfjihvrb5xizimp2qj0-source
source root is source
patching sources
configuring
building
go mod download: no modules specified (see 'go help mod download')
builder for '/nix/store/c03q6swidr4ziqib3z4vhkzs6g23amc1-pms-0.42-go-modules.drv' failed with exit code 1
cannot build derivation '/nix/store/fk0dpczhf39qkz13x5y4a2qsih8h7n38-pms-0.42.drv': 1 dependencies couldn't be built
error: build of '/nix/store/fk0dpczhf39qkz13x5y4a2qsih8h7n38-pms-0.42.drv' failed
```

**Comment by matthiasbeyer** [comment]
Well, at least on my machine?

**Comment by matthiasbeyer** [comment]
So this is a step forward, but the result is empty after this...

Someone with go experience please!

**Comment by rvolosatovs** [comment]
I'd suggest you:
1 .clone the upstream repository
2. checkout the required version(`0.42`)
3. run `go mod download` in the repository
4. check in all modified/created files (most probably only created `go.sum`)
5. create a patch containing all changes - e.g. `git show > go-modules.patch` on Linux
6. move the patch from `5.` to directory containing this package
7. Change `buildGoPackage` to `buildGoModule`
8. remove `goDeps` and `goPackagePath`
9. add `patches` attr containing the filename of patch from `5.` (e.g.:
```nix
patches = [
	go-modules.patch
];
```

**Comment by matthiasbeyer** [comment]
`go mod download` does not create any files in the repository for me.

**Comment by rvolosatovs** [comment]
There's no `go.sum`?
That's weird.
You can also try `go mod init` and/or `go mod vendor`, but I'm quite sure `go.sum` should have been created.

Are you using the latest `master` commit? Do you see `go.mod` present(I see it's there on `master` https://github.com/ambientsound/pms/blob/master/go.mod)?

**Comment by rvolosatovs** [comment]
If you're using 0.42, then it will not work , because that is not even a Go project. It's seems that last commit is from 2010, so not sure we should merge that in the first place.

**Comment by matthiasbeyer** [comment]
Too much hassle for me, sorry.

**Pull request closed without merging**
