### PR TITLE
bruno: 1.34.2 -> 1.37.0

### PR DESCRIPTION
**Pull request by gepbird**
Releases:
- https://github.com/usebruno/bruno/releases/tag/v1.35.0
- https://github.com/usebruno/bruno/releases/tag/v1.36.0
- https://github.com/usebruno/bruno/releases/tag/v1.36.1 (failed to build due to bad lockfile, fixed in 1.37.0)
- https://github.com/usebruno/bruno/releases/tag/v1.37.0

Added a check for `canvas` dependency as [r-ryantm failed to update](https://r.ryantm.com/log/bruno/2024-12-11.log) failed to build it: upstream keeps adding (https://github.com/usebruno/bruno/commit/cc8f3de8b) and removing (https://github.com/usebruno/bruno/commit/bb18c532da823c6854b7f82bb919462a754c9830 and https://github.com/usebruno/bruno/commit/cef6f8584564881a7745938cde606e4eff475e58) the `canvas` dependency.

~~`bruno` doesn't build on this PR: `next build` wants to download `@next/swc-linux-x64-gnu` for some reason, I won't have the capacity to debug this for a few days, feel free to take this over.~~ This only applies to v1.36.1, v1.36.0 works.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gepbird** [comment]
Between https://github.com/usebruno/bruno/compare/fd22ff89625c88150f4debf1d0b2ff5c200940e0...bb18c532da823c6854b7f82bb919462a754c9830, `@next/swc-...`got removed when updating package-lock.json, so we can't build v1.36.1 and I'm only bumping it to v1.36.0.

I'll wait until another maintainer fixes the lockfiles as that happened many times, but feel free to convince them to not break it over and over again.

**Comment by gepbird** [comment]
There's another issue:

> Error occurred in handler for 'open-file': Error: No handler registered for 'open-file'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87134)
    at WebContents.emit (node:events:518:28)

**Comment by lucasew** [comment]
1.37.0 is out there already

**Comment by gepbird** [comment]
In 1.37.0 they fixed the lockfile, but the "Oops! Something went wrong" runtime issue still persists since 1.35.0

**Comment by lucasew** [comment]
> In 1.37.0 they fixed the lockfile, but the "Oops! Something went wrong" runtime issue still persists since 1.35.0

In the logs it says about a missing Mesa GBM thing. I think it's because they changed how the dynamic loader loads the drivers and I am figuring out what to add to buildInputs to fix that.

**Comment by lucasew** [comment]
I opened a issue about this https://github.com/NixOS/nixpkgs/issues/368379

**Comment by lucasew** [comment]
> In 1.37.0 they fixed the lockfile, but the "Oops! Something went wrong" runtime issue still persists since 1.35.0

Are you using NixOS stable?

**Comment by gepbird** [comment]
@lucasew where did you get that Mesa GBM error message? I don't get it in either the terminal I launch bruno from or in the electron console. I've followed your issue a little and read it was a hardware misconfiguration or using mixed channels.

> Are you using NixOS stable?

Yes (though I'm using nvidia drivers from a previous nixos-unstable version as it is broken for kernel >=6.12)

https://github.com/NixOS/nixpkgs/pull/364971#issuecomment-2558456356 is fixed by disabling telemetry. It's a bit controversial upstream (https://github.com/usebruno/bruno/issues/337), if anyone needs telemetry we can add an option later. 

Bruno works, but it still reports version v1.36.0 instead of v1.37.0, most likely they forgot to update it, it has happened before.

**Comment by lucasew** [comment]
> @lucasew where did you get that Mesa GBM error message? I don't get it in either the terminal I launch bruno from or in the electron console. I've followed your issue a little and read it was a hardware misconfiguration or using mixed channels.


When I launch from the terminal that error appears in the terminal. I didn't test on my Nvidia rig yet tho, that rig has this GBM file.

**Comment by gepbird** [comment]
> When I launch from the terminal that error appears in the terminal. I didn't test on my Nvidia rig yet tho, that rig has this GBM file.

Interesting, can you test it with other electron apps?
I just tried it on my AMD machine and the GUI opens and the app functions correctly, but on startup I have these errors repeated like 40 times:
```
[21976:1228/180704.866308:ERROR:gbm_wrapper.cc(79)] Failed to get fd for plane.: No such file or directory (2)                                                                                                    
[21976:1228/180704.866408:ERROR:gbm_wrapper.cc(262)] Failed to export buffer to dma_buf: No such file or directory (2)                                                                                            
```
It also happens with bruno on master, so it's unrealted to the update.

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 364971`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>bruno-cli</li>
  </ul>
</details>

**Comment by mattpolzin** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 364971`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>bruno-cli</li>
  </ul>
</details>

**Review by mattpolzin — APPROVED** [review]

**Comment by lucasew** [comment]
Interesting

Em sáb., 28 de dez. de 2024 14:33, Mathew Polzin ***@***.***>
escreveu:

**Comment by lucasew** [comment]
Interesting

Screenshot_20241228-143331
Screenshot_20241228-143242

**Review by mattpolzin — APPROVED** [review]

**Review by lucasew — APPROVED** [review]

**Comment by mattpolzin** [comment]
Result of `nixpkgs-review pr 364971` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>bruno-cli</li>
  </ul>
</details>

**Pull request merged**
