### PR TITLE
gbl: fix aarch64-darwin build

### LINKED ISSUE #175087: gbl.aarch64-darwin:
### Steps To Reproduce

https://hydra.nixos.org/build/174775275/nixlog/1

### Build log

```
error: failed to run custom build command for `ring v0.14.6`
(...)
  --- stderr
  /private/tmp/nix-build-gbl-0.3.1.drv-0/gbl-0.3.1-vendor.tar.gz/ring/pregenerated/aesv8-armx-linux64.S:17:17: error: unexpected token in '.section' directive
  .section .rodata
                  ^
```

### Additional context

Issue in upstream 'ring' dependency, already fixed on ring 0.16.6 (https://github.com/briansmith/ring/issues/1063)

### PR DESCRIPTION
**Pull request by raboof**
###### Description of changes

Compilation failed due to an old transitive dependency on 'ring',
https://github.com/briansmith/ring/issues/1063.

fixes #175087

#zhfff

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by raboof** [comment]
Result of `nixpkgs-review pr 175093` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gbl</li>
  </ul>
</details>

**Comment by jiegec** [comment]
Result of `nixpkgs-review pr 175093` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gbl</li>
  </ul>
</details>

**Comment by jiegec** [comment]
Result of `nixpkgs-review pr 175093` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gbl</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
I guess this should be rebased to remove

https://github.com/NixOS/nixpkgs/blob/9833d56c2483c3635339b1636dee61b52e3378fc/pkgs/tools/archivers/gbl/default.nix#L50-L51

Also, s/dac-gmbh/jonas-schievink/g.

**Comment by raboof** [comment]
Result of `nixpkgs-review pr 175093` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gbl</li>
  </ul>
</details>

**Comment by raboof** [comment]
> I guess this should be rebased to remove
> 
> https://github.com/NixOS/nixpkgs/blob/9833d56c2483c3635339b1636dee61b52e3378fc/pkgs/tools/archivers/gbl/default.nix#L50-L51

Well-spotted, updated!

> Also, s/dac-gmbh/jonas-schievink/g.

Thanks! Unfortunate that that archive is _also_ archived already, but indeed I didn't find a more recent fork.

**Pull request merged**
