### PR TITLE
abseil-cpp_202301: init at 20230125.3

### PR DESCRIPTION
**Pull request by tm-drtina**
###### Description of changes

Brings in newer version of abseil-cpp, while keeping the default version where it is now.
There are already multiple versions of this lib, this just adds the latest one.
https://github.com/abseil/abseil-cpp/releases/tag/20230125.3

Used 202206 version as a template

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can we bump the default version? What is the outfall? We don't need another version if there would be no regressions.

**Comment by tm-drtina** [comment]
> Can we bump the default version? What is the outfall? We don't need another version if there would be no regressions.

Jan 2023 release is the first one to drop c++11 support and requires at least c++14.

June 2022 release notes:
> This will be the last release to support C++11. Future releases will require at least C++14.

I can test with the latest version as a default and maybe add deprecation warnings to the older versions? (Maybe keeping 2 versions supported: June 2022 for C++11 and the latest Jan 2023?)

**Comment by SuperSandro2000** [comment]
> maybe add deprecation warnings to the older versions?

We can't do this as ofborg will complain.

Keeping two versions or even three is fine, I just want to avoid another one.

**Comment by tm-drtina** [comment]
I've tracked all usages of the default version and pinned them back to avoid the huge rebuild.

Should we create an issue to unpin them, or should we continue in this PR?
I'll check if some of the pins are easy to remove, but I had quite a lot of issues that seemed unrelated to the change. For example redpanda fails on
> Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
which doesn't really seem related

**Comment by tm-drtina** [comment]
Protobuf is probably the main cause of the huge number of rebuilds
> 1 package added:
>abseil-cpp_202103 (init at 20210324.2)
>
>3368 packages updated:

I've created a draft https://github.com/NixOS/nixpkgs/pull/236328 to try to eliminate some of the older versions

**Comment by tm-drtina** [comment]
I've tried to remove the old versions of abseil, but there are some issues I cannot fix. I'd like to merge this PR as it is (unless someone has issues with that) and resolve the issues in separate PR.

Issues:
- `gprc` pinned to version `abseil-cpp_202206`
- `protobuf3_*` pinned to `abseil-cpp_202103`
Both packages causes massive rebuild (3k+). I can try changing them, but that should be a separate PR and most likely target staging. Unfortunately they keep two old versions in nixpkgs

- `redpanda-server` is broken
Redpanda used old version as well, but according to its' build script it should be on `202206` (see https://github.com/redpanda-data/redpanda/blob/v23.1.10/cmake/oss.cmake.in#LL220-L220 )
I've upgraded it to the correct version, but build is broken: https://github.com/NixOS/nixpkgs/pull/235240 https://github.com/NixOS/nixpkgs/pull/234753 https://github.com/NixOS/nixpkgs/pull/220193

- `dragonflydb` is broken
The build fails on master branch as well. Since there is a lot of patches it's not easy to just upgrade. Also nixpkgs has version `0.1.0`, while latest is `1.4.0`. The issue with pinned version might be resolved by just upgrading.
Also it didn't use the lib, just src, so I've changed the dependency to `fetchFromGithub`.

- `or-tools`
Doesn't compile with `202301`, but works fine with `202206`. So the pin was updated, not removed. Should be able to remove the pin with next update of `or-tools` (we are 2 minor versions behind)


@SuperSandro2000 Would you be happy with this change? I've managed to cut it down to 3 versions and we can remove the oldest one when protobuf unpins

**Comment by happysalada** [comment]
Feel free to ping me in a couple of days if no one else is available to merge. This looks good to me.

**Comment by tm-drtina** [comment]
Result of `nixpkgs-review pr 231286` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python310Packages.distrax</li>
    <li>python310Packages.distrax.dist</li>
    <li>python310Packages.elegy</li>
    <li>python310Packages.elegy.dist</li>
    <li>python310Packages.flax</li>
    <li>python310Packages.flax.dist</li>
    <li>python310Packages.rlax</li>
    <li>python310Packages.rlax.dist</li>
    <li>python310Packages.treex</li>
    <li>python310Packages.treex.dist</li>
    <li>python310Packages.vqgan-jax</li>
    <li>python310Packages.vqgan-jax.dist</li>
    <li>tensorflow-lite</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>redpanda-server</li>
  </ul>
</details>
<details>
  <summary>93 packages built:</summary>
  <ul>
    <li>abseil-cpp (abseil-cpp_202301)</li>
    <li>aitrack</li>
    <li>fcitx5-mozc</li>
    <li>jpsxdec</li>
    <li>kotatogram-desktop</li>
    <li>kotatogram-desktop-with-webkit</li>
    <li>libreoffice (libreoffice-still)</li>
    <li>libreoffice-fresh</li>
    <li>libreoffice-fresh-unwrapped</li>
    <li>libreoffice-qt</li>
    <li>libreoffice-unwrapped (libreoffice-still-unwrapped)</li>
    <li>livecaptions</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>onnxruntime</li>
    <li>onnxruntime.dev</li>
    <li>openroad</li>
    <li>or-tools</li>
    <li>or-tools.python (python310Packages.ortools ,python310Packages.ortools.python)</li>
    <li>paperwork</li>
    <li>paperwork.dist</li>
    <li>piper-train (python310Packages.piper-train)</li>
    <li>piper-train.dist (python310Packages.piper-train.dist)</li>
    <li>piper-tts</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.arviz.dist</li>
    <li>python310Packages.bambi</li>
    <li>python310Packages.bambi.dist</li>
    <li>python310Packages.blackjax</li>
    <li>python310Packages.blackjax.dist</li>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.bsuite.dist</li>
    <li>python310Packages.chex</li>
    <li>python310Packages.chex.dist</li>
    <li>python310Packages.dm-env</li>
    <li>python310Packages.dm-env.dist</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.dm-sonnet.dist</li>
    <li>python310Packages.dm-tree</li>
    <li>python310Packages.dm-tree.dist</li>
    <li>python310Packages.faster-whisper</li>
    <li>python310Packages.faster-whisper.dist</li>
    <li>python310Packages.invisible-watermark</li>
    <li>python310Packages.invisible-watermark.dist</li>
    <li>python310Packages.jaxopt</li>
    <li>python310Packages.jaxopt.dist</li>
    <li>python310Packages.mmcv</li>
    <li>python310Packages.mmcv.dist</li>
    <li>python310Packages.numpyro</li>
    <li>python310Packages.numpyro.dist</li>
    <li>python310Packages.onnxruntime</li>
    <li>python310Packages.onnxruntime.dist</li>
    <li>python310Packages.optax</li>
    <li>python310Packages.optax.dist</li>
    <li>python310Packages.optax.testsout</li>
    <li>python310Packages.paperwork-backend</li>
    <li>python310Packages.paperwork-backend.dist</li>
    <li>python310Packages.paperwork-shell</li>
    <li>python310Packages.paperwork-shell.dist</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymc.dist</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python310Packages.tensorflow-datasets.dist</li>
    <li>python310Packages.tensorflow-probability</li>
    <li>python310Packages.tensorflow-probability.dist</li>
    <li>python310Packages.trfl</li>
    <li>python310Packages.trfl.dist</li>
    <li>python311Packages.blackjax</li>
    <li>python311Packages.blackjax.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.chex</li>
    <li>python311Packages.chex.dist</li>
    <li>python311Packages.dm-env</li>
    <li>python311Packages.dm-env.dist</li>
    <li>python311Packages.dm-tree</li>
    <li>python311Packages.dm-tree.dist</li>
    <li>python311Packages.jaxopt</li>
    <li>python311Packages.jaxopt.dist</li>
    <li>python311Packages.onnxruntime</li>
    <li>python311Packages.onnxruntime.dist</li>
    <li>python311Packages.optax</li>
    <li>python311Packages.optax.dist</li>
    <li>python311Packages.optax.testsout</li>
    <li>python311Packages.ortools (python311Packages.ortools.python)</li>
    <li>python311Packages.paperwork-backend</li>
    <li>python311Packages.paperwork-backend.dist</li>
    <li>python311Packages.paperwork-shell</li>
    <li>python311Packages.paperwork-shell.dist</li>
    <li>telegram-desktop</li>
    <li>unoconv</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>webrtc-audio-processing_1</li>
    <li>ycmd</li>
  </ul>
</details>

**Pull request merged**
