### PR TITLE
all-packages.nix: move defaults to package files continues

### PR DESCRIPTION
**Pull request by oxij**
# What? Why?

A continuation of #55129. This one also integrates a bit of #35374.

# `git log`

- *: move defaults to package file

A bunch of these.

# `nix-instantiate` environment

- Host OS: Linux 4.9, SLNOS 19.03
- Nix: nix-env (Nix) 2.1.3
- Multi-user: yes
- Sandbox: yes
- NIXPKGS_CONFIG:

```nix
{
  checkMeta = true;
  doCheckByDefault = true;
}
```

# `nix-env -qaP` diffs

- On x86_64-linux: noop
- On aarch64-linux: noop
- On x86_64-darwin: noop

/cc @mic92 @ryantm @ericson2314 @infinisil @bendlas @jtojnar @pbogdan @abbradar from git-blame and @7c6f434c from #55129

### CODE REVIEW

**Review by 7c6f434c — APPROVED** [review]
I want to wait for objections, not just for ofborg, but I do like this

**Comment by bendlas** [comment]
I tend towards liking it as well, but don't have any thought out rationale.

cc @volth objected to doing this for chromium, IIRC

**Comment by oxij** [comment]
Well, ofborg, I guess I can just make this a noop.

**Comment by oxij** [comment]
I wonder, what ofborg thinks is a rebuild on darwin? nix-env diff between master and a merge of this and master is empty on my machine.

Anyway, can we merge yet?

**Comment by samueldr** [comment]
ofborg seems to think `direwolf` has changed for darwin. Though it's something that fails to instantiate.

In the GitHub interface, in the list of checks from ofborg, the *Details* link on the **grahamcofborg-eval** line will point to a gist with the list of changed attributes.

> image

 * https://gist.github.com/GrahamcOfBorg/1b330209e4adba893480a7741b19b23e

(There is an annoying bug in GitHub where a merged PR will add a bogus Details link to all lines, even those without a Details page to link to.)

In case you're ever curious what ofborg saw. [This](https://github.com/NixOS/ofborg/blob/344f94bede604849cada1caf65fc667e1d29c107/ofborg/src/tasks/massrebuilder.rs#L203) might be a good place to start checking how it sniffs changes. (Most of the implementation is in [outpathdiff.rs](https://github.com/NixOS/ofborg/blob/344f94bede604849cada1caf65fc667e1d29c107/ofborg/src/outpathdiff.rs).)

**Comment by oxij** [comment]
I see. Thanks! and for pointers.

**Pull request merged**
