### PR TITLE
libftdi1: 1.4 -> 1.5

### PR DESCRIPTION
**Pull request by OPNA2608**
###### Motivation for this change
Extracted from #116826. It was an optional dependency for the packages there and I bumped it because I noticed a newer version, but the amount of rebuilds it caused was too much for my taste. I don't really use any of the packages/functionalities this bump affects but no point in throwing this away either, so here you go.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117242` at a877d65d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages skipped due to time constraints:</summary>
  <ul>
    <li>dvdstyler</li>
    <li>glasgow (python38Packages.glasgow)</li>
    <li>kodi (kodiPackages.kodi)</li>
    <li>kodi-gbm</li>
    <li>kodi-wayland</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.kodi-platform</li>
    <li>kodiPackages.netflix</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>38 packages built successfully:</summary>
  <ul>
    <li>arachne-pnr</li>
    <li>audacious (audaciousQt5)</li>
    <li>avrdude</li>
    <li>avrdudess</li>
    <li>blackmagic</li>
    <li>cadence</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>fbida</li>
    <li>fgallery</li>
    <li>flashrom</li>
    <li>fujprog</li>
    <li>geeqie</li>
    <li>gjay</li>
    <li>icestorm</li>
    <li>indi-3rdparty</li>
    <li>indi-full</li>
    <li>ino</li>
    <li>libftdi1</li>
    <li>libsigrok</li>
    <li>libsigrok-0-3-0</li>
    <li>libsigrokdecode</li>
    <li>lirc (python38Packages.lirc)</li>
    <li>openfpgaloader</li>
    <li>openocd</li>
    <li>paprefs</li>
    <li>phd2</li>
    <li>pulseaudio-hsphfpd</li>
    <li>pulseaudio-modules-bt</li>
    <li>pulseaudioFull</li>
    <li>pulseview</li>
    <li>python38Packages.pylibftdi</li>
    <li>python39Packages.lirc</li>
    <li>python39Packages.pylibftdi</li>
    <li>sd-mux-ctrl</li>
    <li>sigrok-cli</li>
    <li>urjtag</li>
    <li>xineUI</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

swig is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/libraries/libftdi/1.x.nix:35:3:
```
   |
35 |   buildInputs = [ libconfuse ]
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/tools/misc/blackmagic/default.nix:52:3:
```
   |
52 |   buildPhase = "${stdenv.shell} ${./helper.sh}";
   |   ^
```
</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by OPNA2608** [comment]
I've added the bot's suggestion for swig -> nativeBuildInputs and fixed another instance of the includedir path being wrong.

**Comment by risicle** [comment]
Oh, I've just finished testing the earlier push, macos 10.14, linux x86_64 and the failures are all pre-existing.

Also builds happily with python disabled & cpp disabled.

**Review by risicle — APPROVED** [review]
Rechecked, LGTM

**Pull request merged**
