### PR TITLE
gradle: 7-rc-2 -> 7, bumping latest 6.8.3 -> 7

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
###### Motivation for this change

Release of Gradle 7. See:

 - [Release Notes](https://docs.gradle.org/7.0/release-notes.html)
 - [Upgrade Guide](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#changes_7.0)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Please review, @SuperSandro2000 @mstrangfeld

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119352` at da62033a run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>impressive</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/0e231fc086592d388f20eef5dbc53933">frostwire</a></li>
    <li><a href="https://gist.github.com/9e41f5d4a5ef65131f2d5da94b591e8c">ma1sd</a></li>
    <li><a href="https://gist.github.com/a817368fa448eb4ff3d4513f0d953c97">mxisd</a></li>
    <li><a href="https://gist.github.com/e5090b647c72fa9cca2b8963a1671fd4">scenebuilder</a></li>
    <li><a href="https://gist.github.com/d6ef3d98e42199c3726596a00466e243">shattered-pixel-dungeon</a></li>
  </ul>
</details>
<details>
  <summary>5 packages built successfully:</summary>
  <ul>
    <li>gradle (gradle_7)</li>
    <li>gscan2pdf</li>
    <li>jadx</li>
    <li>pdftk</li>
    <li>scenic-view</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/tools/build-managers/gradle/default.nix:48:5:
```
   |
48 |     meta = {
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/build-managers/gradle/default.nix:18:5:
```
   |
18 |     installPhase = ''
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/fixup-phase.md">fixup-phase</a>

`fixupPhase` should not be overridden, use `postFixup` instead.

Near pkgs/development/tools/build-managers/gradle/default.nix:29:5:
```
   |
29 |     fixupPhase = if (!stdenv.isLinux) then ":" else
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by lorenzleutgeb** [comment]
OK, so I took a look at the failures and filed issues.

### `frostwire`

Offending line: https://github.com/frostwire/frostwire/blob/frostwire-desktoap-6.6.7-build-529/common/dependencies.gradle#L2

This will likely go away once Frostbite is updated to a more recent version. Didn't bisect, but the error will not occur on their latest development version, and Nixpkgs lags behind quite a bit.

### `ma1sd`

https://github.com/ma1uta/ma1sd/issues/91

### `mxisd`

Offending line: https://github.com/kamax-matrix/mxisd/blob/6e9601cb3a18281857c3cefd20ec773023b577d2/build.gradle#L91

Same story, since `ma1sd` is a fork of `mxisd`. But `mxisd` [is EOL](https://github.com/kamax-matrix/mxisd/blob/master/EOL.md#end-of-life-notice).

### `scenebuilder`
https://github.com/gluonhq/scenebuilder/issues/356

### `shattered-pixel-dungeon`
https://github.com/00-Evan/shattered-pixel-dungeon/issues/678

**Comment by lorenzleutgeb** [comment]
Since fixing all those will take a while, I pinned them to Gradle 6. Should be good now.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 119352` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>impressive</li>
</ul>
</details>
<details>
<summary>
5 packages built:
</summary>
<ul>
<li>gradle (gradle_7)</li>
<li>gscan2pdf</li>
<li>jadx</li>
<li>pdftk</li>
<li>scenic-view</li>
</ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Review by fgaz — APPROVED** [review]

**Pull request merged**
