### PR TITLE
python2Packages.locustio: remove, unmaintained

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
it was last manually updated 30+ months ago. It's currently broken, and I would rather remove time-wasting packages, then try to polish something no one seems to care about.

- no maintainer
- no license

It seems to be popular https://github.com/locustio/locust but it's not usable in it's current state.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
cc @adisbladis who last updated this in Nov of 2017

**Comment by teto** [comment]
I tried using it 4 months ago and had to package several unmaintainted deps etc. There is a wide choice in this software area so I think it's fine to remove.

**Comment by jonringer** [comment]
I couldn't find an issue where someone desired this to be packaged. Only mentions were for ZHF, in which it seems to always be broken. Removing.

**Comment by Ulexus** [comment]
FWIW, a new locust version was released only 4 days ago, and it is written for python 3:

https://github.com/locustio/locust/releases

**Pull request merged**
