### PR TITLE
syncthing: 0.12.23 -> 0.12.25

### LINKED ISSUE #15633: syncthing needs version bump to fix security issue
See https://github.com/syncthing/syncthing/releases/tag/v0.12.25

### PR DESCRIPTION
**Pull request by dtulig**
fixes #15633

### CODE REVIEW

**Comment by lfam** [comment]
See also https://github.com/NixOS/nixpkgs/pull/15674

If you get your patch working before our, yours should be applied, and we will adapt ours to your changes.

**Comment by dtulig** [comment]
Ah, I missed that #15674 was also updating to 0.12.25. I won't have a chance to look at this for another 8 hours so I'll check in with how the other change is going at that time. Thanks for making me aware of it!

**Comment by fpletz** [comment]
Builds and works fine for me. Merging this now as it fixes a security problem.

**Comment by fpletz** [comment]
Also pushed to release-16.03 branch.

**Pull request merged**
