### PR TITLE
treewide: remove superflous format string when a variable can be used directly

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

Replaces 

```
foo = "${bar}";
```

with

```
foo = bar;
```

when `bar` is of type string.

This very commonly used for `rev = "${version}";` and `repo = "${pname}";`, where `rev = version;` and `repo = pname;` would be enough.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
to no fault of your own: https://github.com/NixOS/nixpkgs/pull/102394/checks?check_run_id=1339322844

**Comment by prusnak** [comment]
> to no fault of your own: https://github.com/NixOS/nixpkgs/pull/102394/checks?check_run_id=1339322844

Not sure what this was about - I forced pushed and I can't seem to be able to read the logs of the older run

**Comment by prusnak** [comment]
I am closing this and will follow up with more complex clean-up PR.

**Comment by prusnak** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/102396

**Pull request closed without merging**
