### PR TITLE
fortune: Revert add an option to let user use offensive 

### PR DESCRIPTION
**Pull request by JuJulius-Pepperwood**
This reverts commit https://github.com/NixOS/nixpkgs/commit/bf09f6c83afefd3c2dae00eeec0802644ceb7456.
    
There is no reason for nixpkgs to enable racism. If someone wants
this, overlays exist. No one is preventing anyone from using their
computer to do whatever they want, but maybe nixpkgs doesn't need a
flag that makes fortune print swastikas.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by azahi** [comment]
> There is no reason for nixpkgs to enable racism.

It's not enabled in Nixpkgs in any capacity, Nixpkgs is merely a package repository/implementation for a Linux distribution. The fact that a package has an **optional** flag which is **not enabled by default** that adds some funny (to some) quotes and messages is not "enabling racism".

> maybe nixpkgs doesn't need a flag that makes fortune print swastikas

Please show an example of a fortune with swastikas in it. The upstream [maintainer](https://github.com/shlomif) mentions in his GitHub bio that he's an Israeli software developer, so I highly doubt that he would be affiliated with swastikas, certainly not in a positive way.

/cc @wmertens @Vonfry (as participants of #172011)

**Comment by JuJulius-Pepperwood** [comment]
> > There is no reason for nixpkgs to enable racism.
> 
> It's not enabled in Nixpkgs in any capacity, Nixpkgs is merely a package repository/implementation for a Linux distribution. The fact that a package has an **optional** flag which is **not enabled by default** that adds some funny (to some) quotes and messages is not "enabling racism".

I agree that it is an optional flag. I respectfully disagree in not enabling racism. Adding a clear path from not racism to racism is enabling it.

> 
> > maybe nixpkgs doesn't need a flag that makes fortune print swastikas
> 
> Please show an example of a fortune with swastikas in it. The upstream [maintainer](https://github.com/shlomif) mentions in his GitHub bio that he's an Israeli software developer, so I highly doubt that he would be affiliated with swastikas, certainly not in a positive way.
I am very, very saddened to hear that he is from Israel.
 
https://github.com/shlomif/fortune-mod/blob/da2fb5c184027d88401ea3f904314df83e5ea904/fortune-mod/datfiles/off/unrotated/atheism#L137
https://github.com/shlomif/fortune-mod/search?q=Adolf+Hitler
> 
> /cc @wmertens @Vonfry (as participants of #172011)

**Comment by JuJulius-Pepperwood** [comment]
> https://github.com/shlomif/fortune-mod/search?q=Adolf+Hitler

GitHub finds only a handful of occurrences for some reason. `grep -rn "Adolf Hitler | wc -l` in the repo returns 58.

**Comment by wmertens** [comment]
🤯😱🤢 I had no idea. The swastika makes it actually illegal in Germany! You can't really claim that it's there for educational or artistic purposes (the only allowed exceptions)

This makes me very sad, I really enjoy the atheist jokes generally speaking.

Could we not patch out the offending fortunes?

**Comment by raphaelr** [comment]
The fortune manpage states:

> Please, please, please request a potentially offensive fortune if and only if you believe,
> deep in your heart, that you are willing to be offended. (And that you'll just quit using -o
> rather than give us grief about it, okay?)

So the current behaviour is correct.

**Comment by JuJulius-Pepperwood** [comment]
For what its worth, the ubuntu response on their side:
https://twitter.com/ubuntu/status/1592842830359461888

>The swastika makes it actually illegal in Germany! 

This got me thinking. Say I am a user of nixpkgs in [Germany](https://en.wikipedia.org/wiki/Bans_on_Nazi_symbols). I like fortune, and I install the default package. One day, there is a cache miss, or I want to update fortune so I run nix-build. In this case, the derivation in nixpkgs realizes the fortune _source archive_ in my nix store, which completely unbeknownst to me includes nazi symbolism.

If my computer is searched for whatever reason by authorities, I am exposed to  _risk_. The risk is that I can end up in a legally involved situation.

Or more importantly, any NixOS server that has built and still builds the default fortune has fetched and holds an archive with nazi symbolism. Is that server in Germany, exposed to German laws? Is that server paid for by a company that doesn't want want to be exposed to such a situation? There is legal and publicity risk now.

Due to all this, I am changing my position. It is irrelevant whether withOffensive is there or not. The nixpkgs recipe must be changed immediately stop fetching from this upstream and fetch from an upstream that doesn't have these in the first place. 
Imo nixpkgs unknowingly stepped into something bad with the source fetching. Let's undo that now, and only then start discussing how bad it actually was, if at all, and in what terms it can be re-introduced.

**Comment by azahi** [comment]
@JuJulius-Pepperwood 

First of all, good find, I was not aware that the package contains a depiction of swastika. That is indeed peculiar.

> I agree that it is an optional flag. I respectfully disagree in not enabling racism. Adding a clear path from not racism to racism is enabling it.

Well, I guess we just have a different perspectives on this matter. I am completely indifferent to these quotes and I don't take any offense in them personally, and even if I took offense, I'd consider it a private matter that I got offended by the text on the screen. I also don't think that the mere existence of racist quotes or words could enable racism. I also know for a fact that it's possible to steal something from someone, but that doesn't make me want to become a thief.

Hopefully this didn't come out as disrespectful, I'm not that well-versed in English.

> I would like to see this filtering done upstream

In that case I believe it would be better to discuss this with upstream. Personally, I think that we should package software with the desire to replicate and follow upstream's intentions (or at least try doing it)... or don't package it at all.

> This got me thinking. Say I am a user of nixpkgs in [Germany](https://en.wikipedia.org/wiki/Bans_on_Nazi_symbols). I like fortune, and I install the default package. One day, there is a cache miss, or I want to update fortune so I run nix-build. In this case, the derivation in nixpkgs realizes the fortune source archive in my nix store, which completely unbeknownst to me includes nazi symbolism.

> If my computer is searched for whatever reason by authorities, I am exposed to risk. The risk is that I can end up in a legally involved situation.

> Or more importantly, any NixOS server that has built and still builds the default fortune has fetched and holds an archive with nazi symbolism. Is that server in Germany, exposed to German laws? Is that server paid for by a company that doesn't want want to be exposed to such a situation? There is legal and publicity risk now.

Given this logic we should remove this package altogether because its tarball can be considered illegal.

Should we also remove other packages that could be considered illegal in other countries? For instance, in my country (Russia) it's [illegal](https://www.consultant.ru/document/cons_doc_LAW_10699/4618fd95c30a6fbe7717ceaebf64f082e735c9ad/) to negatively portray or discredit the Russian Armed Forces (RAF) and RAF's actions (especially regarding the ongoing conflict in Ukraine), you can also [get into trouble](https://www.msk.kp.ru/online/news/4882508/) by promoting or soliciting donations to Ukraine. Should we also remove a plethora of packages that include in them political statements that can somehow negatively portray RAF and/or solicit said donations? What if the word "Nixpkgs" gets banned tomorrow in your country? Should we rename the repository then?

My point is that these things depend entirely on the interpretation of the law. I am no expert in this and I assume you are not either (please correct me if I'm wrong). So let's not make any hasty decisions.

> The nixpkgs recipe must be changed immediately stop fetching from this upstream and fetch from an upstream that doesn't have these in the first place.

We can remove this package from Nixpkgs, I have no objections against that, even though I don't agree with your reasoning. However, I don't think that removing the option will benefit us in this situation at all, and I also don't think that it would be the right thing to do (as explained above).

> Imo nixpkgs unknowingly stepped into something bad with the source fetching. Let's undo that now, and only then start discussing how bad it actually was, if at all, and in what terms it can be re-introduced.

Let's first formalize this and ask the community. I'm willing to help and give my thoughts on this topic if you or someone else could draft an RFC.

**Comment by N-R-K** [comment]
> the nastiness of what's in there voids the usual maintainer guarantee/responsibility/desire to make things configurable.

Which is why it's not enabled by default. If someone *wants* offensive jokes, it's entirely their decision - why assume that you know what the user wants more than they do? It's very condescending.

> The swastika makes it actually illegal in Germany! You can't really claim that it's there for educational or artistic purposes (the only allowed exceptions).

Unless germany has a well defined meaning for "artistic purpose", it leaves a pretty broad door open for jokes/comedy, does it not?

Also as [@azahi already pointed out](https://github.com/NixOS/nixpkgs/pull/201391#issuecomment-1317344323) once you start removing packages because it might be illegal in ${some_country} you'll step into a pretty bad rabbit hole. There are hundreds of countries out there - with plenty of questionable laws.

**Comment by JuJulius-Pepperwood** [comment]
> Hopefully this didn't come out as disrespectful, I'm not that well-versed in English.

No, not at all, I think we are having a great discussion here, respectful, factual and analytical. That is more than I expected, given the touchiness of the subject.

> 
> First of all, good find, I was not aware that the package contains a depiction of swastika. That is indeed peculiar.
> 
> > I agree that it is an optional flag. I respectfully disagree in not enabling racism. Adding a clear path from not racism to racism is enabling it.
> 
> Well, I guess we just have a different perspectives on this matter. I am completely indifferent to these quotes and I don't take any offense in them personally, and even if I took offense, I'd consider it a private matter that I got offended by the text on the screen. I also don't think that the mere existence of racist quotes or words could enable racism. I also know for a fact that it's possible to steal something from someone, but that doesn't make me want to become a thief.
> 

You are right, it is not enabling. I take that back. Still, I think having a flag that among other things enables all the things mentioned so far, is not good. I think we agree at this point that it's not enabling, it's definitely not condoning. It's a presence whose existence can be interpreted in different ways by different people. One of the interpretations is that it makes nixpkgs not-as-welcoming as it could be, and I want it removed so that this interpretation can be squashed. This is the reason ubuntu pulled their equivalent package when it was pointed out to them.

> 
> > I would like to see this filtering done upstream
> 
> In that case I believe it would be better to discuss this with upstream. Personally, I think that we should package software with the desire to replicate and follow upstream's intentions (or at least try doing it)... or don't package it at all.

In principle, I agree on both points. In practice, I have read the blog of the upstream maintainer. He is very open about his views, goals, aspirations. I will not go into detail, here and now is not the place. Feel free to read the maintainer's blog and draw your own conclusions, I have drawn mine, they will not change and if we start discussing such things here we will lose track of what we want to do.

[sidenote: I have snipped a bunch of stuff here, I want to kind of nip the discussion wrt legality. I don't have a legal background, I'm just a programmer who likes nix. I'm not using my real account/name for protection, not subterfuge. I don't want actual nazis to escalate this thread into real life harassment. If you don't like the anonymity, let me know, and I can talk to one of the moderators and they can vouch that I am not doing sockpuppeting or pretending to be someone I am not or anything else.]

> Should we also remove other packages that could be considered illegal in other countries?

This is a reasonable and expected question. My answer is that drawing equivalences and expanding the question to be generally about nixpkgs and legality kind of goes out of scope. I brought up the legality as an argument because of the intersection of laws and swastikas/hitler quotes. For the other cases, the moral/social/political context of what is banned is different, so I reject the notion of equivalence. It might also be worth pointing out that this is not just Germany, but tens of countries across the world that ban nazi symbols in public: https://en.wikipedia.org/wiki/Bans_on_Nazi_symbols.  nixpkgs is not violating any laws, i don't think, but in spirit a lot of countries agree and I am not aware of any that disagree, e.g. countries that make flying nazi flags mandatory.

The notion of precedent is important. We could stop here, merge the removal, with the record saying that this is not a general precedent. It would only be a precedent in the very narrow context of adding new flags or default source fetching of nazi symbols in the fortune package. This will not be a statement about other stuff.

> 
> My point is that these things depend entirely on the interpretation of the law. I am no expert in this and I assume you are not either (please correct me if I'm wrong). So let's not make any hasty decisions.
> 

I am not bringing forth hasty suggestions, I hope. If I may use an analogy, I feel like we are on the first step on a bridge, and it made a weird sound. Let's take a small step back and discuss from the ground whether the bridge is safe to cross.
Removing the package as a whole is a huge step back, I am not proposing that.

From what I see here in this thread, the PR that added the flag was merged without full awareness of what the flag enabled. With the benefit of hindsight, it might never have been merged. Let's undo that and give us space and time to make the decision to add the flag with a more complete context. Which brings us to:

> Let's first formalize this and ask the community. I'm willing to help and give my thoughts on this topic if you or someone else could draft an RFC.

I more than agree. This process will take time, so I very much see it as a prerequisite that we undo the flag addition now and remake the decision with a fuller context and an accepted RFC to guide us.

So with the RFC in mind, I say let's:
- remove the flag, it's contentious and added without the full knowledge of the contents of fortune
- Start the RFC process. Let us discuss what the scope of the RFC should be, legal, moral, very focused on nazi stuff? What do we want to solve?
- Once we have the community consensus and framework, let's revisit this but from the side of merging it again, not removing it.

Are you ok with this?

>Why assume that you know what the user wants more than they do? It's very condescending.
Please refrain from ascribing such intentions. I am trying not to be condescending, I am not telling the users what to do. I have multiple times mentioned that overlays exist to allow users to do what they want. I dislike your tone, please keep things civil and without attaching intents.

**Comment by JuJulius-Pepperwood** [comment]
There is a dimension on what upstream means here, which I did not touch. The upstream nixpkgs uses is not the original source of fortune. The maintainer of it imported the original fortune program and the assets. It is closer to a fork, not the authoritative source of fortune. I believe there is some leeway in using a different upstream, which will have the same core fortune source code and non offensive jokes. It would not be a fork, but the exact same core, different assets, if this makes sense.

**Comment by N-R-K** [comment]
> I have multiple times mentioned that overlays exist to allow users to do what they want.

It's unnecessary additional work.

> I dislike your tone, please keep things civil and without attaching intents.

I had no intention to have a negative tone, but I see now that that's how it came off.

Similarly you may not had any intention to be condescending, but when a packager removes an upstream configuration due to personal/subjective reasons - that's precisely how it comes off. Hopefully that's clear now.

**Comment by reedrw** [comment]
I don't have an opinion either way. I'm just commenting to let you know this PR should be squashed into a single commit.

**Comment by witchof0x20** [comment]
With how trivial it is to override or pull in in non `nixos/nixpkgs` derivations now, I think it's really not too big a deal to remove this.

**Comment by JuJulius-Pepperwood** [comment]
Thank you everyone for your time, for being so kind while being so kind while discussing such a touchy subject. Thanks for all the effort that went here, your suggestions, your kindness, taking the time to read my essays.

I am withdrawing this PR. In light of the above discussions, discoveries and a talk with one of the moderators on matrix, I wish to stop my involvement here. If anyone wishes to continue on the points made here, I have no reason or right to stop anything, I merely got a ball rolling. It seems likely I will find some time some other day to tackle this problem from the perspective of completely removing fortune.

To wit,
The upstream maintainer goes by Shlomi "Rindolf Hitlower" Fish: https://www.shlomifish.org/me/rindolf/#rindolf_aim_very_high_hitlower. The number packages with Hitler quotes and swastikas, whose maintainer goes by an A.H. pun nickname, that I find acceptable is exactly 0.

- My best and gratitude to everyone here

**Pull request closed without merging**
