### PR TITLE
python3Packages.nbconvert: clean up

### PR DESCRIPTION
**Pull request by samuela**
###### Description of changes

General clean up of the nbconvert derivation. In particular, I found that the set of disabled tests could be made smaller, leading to better test coverage.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuela** [comment]
This caused some downstream breakages according to nixpkgs-review. Addressing them now...

**Comment by samuela** [comment]
11 packages failed to build:
python310Packages.atomman python310Packages.augmax python310Packages.einops python310Packages.pydeck python39Packages.atomman python39Packages.modeled python39Packages.phik python39Packages.pydeck python39Packages.robotframework-tools streamlit wolfram-notebook

122 packages built:
ihaskell jupyter opsdroid python310Packages.Nikola python310Packages.Pweave python310Packages.ansible-kernel python310Packages.batchspawner python310Packages.cufflinks python310Packages.dockerspawner python310Packages.folium python310Packages.ipydatawidgets python310Packages.ipympl python310Packages.ipyvue python310Packages.ipyvuetify python310Packages.ipywidgets python310Packages.jupyter python310Packages.jupyter-lsp python310Packages.jupyter-server-mathjax python310Packages.jupyter-sphinx python310Packages.jupyter_server python310Packages.jupyterhub python310Packages.jupyterhub-ldapauthenticator python310Packages.jupyterhub-systemdspawner python310Packages.jupyterhub-tmpauthenticator python310Packages.jupyterlab python310Packages.jupyterlab-git python310Packages.jupyterlab-lsp python310Packages.jupyterlab_launcher python310Packages.jupyterlab_server python310Packages.jupytext python310Packages.kmapper python310Packages.lightparam python310Packages.livelossplot python310Packages.nbclassic python310Packages.nbconflux python310Packages.nbconvert python310Packages.nbdime python310Packages.nbsmoke python310Packages.nbsphinx python310Packages.nix-kernel python310Packages.notebook python310Packages.notedown python310Packages.oauthenticator python310Packages.osmnx python310Packages.papermill python310Packages.potentials python310Packages.qiskit-aer python310Packages.qiskit-finance python310Packages.qiskit-ibmq-provider python310Packages.qiskit-ignis python310Packages.qiskit-nature python310Packages.qiskit-optimization python310Packages.qiskit-terra python310Packages.spyder python310Packages.vega python310Packages.widgetsnbextension python39Packages.Nikola python39Packages.Pweave python39Packages.ansible-kernel python39Packages.augmax python39Packages.batchspawner python39Packages.cufflinks python39Packages.datashader python39Packages.dockerspawner python39Packages.einops python39Packages.elegy python39Packages.folium python39Packages.ipydatawidgets python39Packages.ipympl python39Packages.ipyvue python39Packages.ipyvuetify python39Packages.ipywidgets python39Packages.jupyter python39Packages.jupyter-lsp python39Packages.jupyter-server-mathjax python39Packages.jupyter-sphinx python39Packages.jupyter_server python39Packages.jupyterhub python39Packages.jupyterhub-ldapauthenticator python39Packages.jupyterhub-systemdspawner python39Packages.jupyterhub-tmpauthenticator python39Packages.jupyterlab python39Packages.jupyterlab-git python39Packages.jupyterlab-lsp python39Packages.jupyterlab_launcher python39Packages.jupyterlab_server python39Packages.jupytext python39Packages.kmapper python39Packages.lightparam python39Packages.livelossplot python39Packages.moretools python39Packages.nbclassic python39Packages.nbconflux python39Packages.nbconvert python39Packages.nbdime python39Packages.nbsmoke python39Packages.nbsphinx python39Packages.nix-kernel python39Packages.notebook python39Packages.notedown python39Packages.oauthenticator python39Packages.osmnx python39Packages.papermill python39Packages.potentials python39Packages.qiskit python39Packages.qiskit-aer python39Packages.qiskit-finance python39Packages.qiskit-ibmq-provider python39Packages.qiskit-ignis python39Packages.qiskit-machine-learning python39Packages.qiskit-nature python39Packages.qiskit-optimization python39Packages.qiskit-terra python39Packages.scikit-tda spyder python39Packages.stytra python39Packages.treex python39Packages.vega python39Packages.widgetsnbextension python39Packages.zetup sage sageWithDoc

**Comment by samuela** [comment]
Failures are all pre-existing now. If no one objects I'll go ahead and merge tomorrow.

**Comment by collares** [comment]
Note to self: de161602c5913f3852afc2d71bbadd25e74f9ef6 broke `sage -n`. Will debug tomorrow.

**Comment by collares** [comment]
Other than Sage, I wonder if there are other packages which depend on `widgetsnbextension` expecting to also get `notebook` for free, given that  PyPI package requires it.

**Comment by samuela** [comment]
Yes, IIRC there were some nasty circular dependency issues and this was the cleanest possible solution AFAICT. I guess `sage -n` must not have had tests?

**Pull request merged**
