### PR TITLE
staging-next: 21.11 iteration 8 - 2022-02-28

### PR DESCRIPTION
**Pull request by vcunat**
Documentation: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-staging-next-branch

jobset: https://hydra.nixos.org/jobset/nixpkgs/staging-next-21.11
important job: https://hydra.nixos.org/job/nixpkgs/staging-next-21.11/unstable#tabs-constituents

Previous staging-next PR: https://github.com/NixOS/nixpkgs/pull/158493

### CODE REVIEW

**Comment by wamserma** [comment]
A significant amount of failed packages is due to a timeout in the tests of libsrtp:
https://hydra.nixos.org/build/168366511/nixlog/4/tail
and an OOM in the tests of python3Packages.xmltodict:
https://hydra.nixos.org/build/168326489/nixlog/1/tail

**Comment by vcunat** [comment]
xmltodict: I suspect some risks, but at least for now I simply synced it from `staging-next`

**Review by wamserma — APPROVED** [review]

**Review by jonringer — APPROVED** [review]
was able to build https://github.com/jonringer/nix-test-staging-next/blob/main/test-staging.nix

**Comment by vcunat** [comment]
I believe that we'll be _finally_ able to merge this weekend.  Linux is 90% rebuilt and looking good: https://hydra.nixos.org/eval/1748329?filter=linux&compare=1746152

**Pull request merged**
