### PR TITLE
terminus-font: enable characters variants switching

### PR DESCRIPTION
**Pull request by caadar**
###### Motivation for this change
Terminus font upstream provides patchset for characters variants (see homepage at http://terminus-font.sourceforge.net#variants).

Some alternative variants so common, that e.g. centered tilde is mentioned as "perhaps should be the default".

This PR adds useful ability to switch alternative terminus font variants by Nix.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by veprbl** [comment]
cc @astsmtl

**Comment by caadar** [comment]
May be users should use something like
```nix
  nixpkgs.overlays = [(self: super: {
    terminus_font = super.terminus_font.overrideAttrs (_: {
      patchPhase = super.terminus_font.patchPhase + ''
        patch -p1 -i alt/ge2.diff
        patch -p1 -i alt/ij1.diff
        patch -p1 -i alt/ll2.diff
        patch -p1 -i alt/td1.diff
      '';
    });
  })];
```
and options for Terminus font not needed?

**Comment by caadar** [comment]
Not needed indeed. Just use overlays.

**Comment by jktjkt** [comment]
Just in case someone lands here when looking for these options, I'm posting what actually works for me on `nixpkgs-unstable` today. The way patches are managed has changed, that package doesn't use `patchPhase`, and it's now:

```nix
self: super:
{

  terminus_font = super.terminus_font.overrideAttrs (_: {
      patches = [
        "alt/ll2.diff"
	"alt/td1.diff"
      ];
    });
}
```
It's enough to put that into `~/.config/nixpkgs/overlays/extra-packages/default.nix`.

I think this demonstrates quite nicely that there's *some* churn in these options, so I think adding per-package options is a cleaner option here. Too bad that even these options are apparently totally undocumented...

**Comment by sigprof** [comment]
Note that the override in the [comment above](https://github.com/NixOS/nixpkgs/pull/63724#issuecomment-706126143) is subtly incorrect — it replaces the value of `patches` completely, but the current version of the `terminus_font` package actually has a patch inside, and that patch gets removed by the override.

The correct override should use `(old.patches or [])` to make sure that any Nixpkgs-provided patches are still applied:
```nix
self: super:
{
  terminus_font = super.terminus_font.overrideAttrs (old: {
      patches = (old.patches or []) ++ [
        "alt/ll2.diff"
	"alt/td1.diff"
      ];
    });
}
```

**Pull request closed without merging**
