### PR TITLE
vtk: unbreak on darwin using VTK_VERSIONED_INSTALL

### PR DESCRIPTION
**Pull request by veprbl**
This fixed VTK that was broken on darwin in #158778 with "mv: Argument
list too long".

Reverts: 16a1b346 ('vtk: create versionless symlinks in /lib')
Reverts: 63599248 ('vtk: move headers out of /include/vtk-*')
This partially reverts: 010f6ee3 ('treewide: mark broken for darwin')

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 178291` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages marked as broken and skipped:</summary>
  <ul>
    <li>ants</li>
    <li>c3d</li>
    <li>elastix</li>
    <li>elmerfem</li>
    <li>ezminc</li>
    <li>inkcut</li>
    <li>itk4</li>
    <li>opencascade</li>
    <li>pcl</li>
    <li>python310Packages.dicom2nifti</li>
    <li>python310Packages.enamlx</li>
    <li>python310Packages.mayavi</li>
    <li>python310Packages.pythonocc-core</li>
    <li>python310Packages.vtk</li>
    <li>python39Packages.dicom2nifti</li>
    <li>python39Packages.enamlx</li>
    <li>python39Packages.mayavi</li>
    <li>python39Packages.pythonocc-core</li>
    <li>python39Packages.vtk</li>
    <li>smesh</li>
    <li>vtk</li>
    <li>vtkWithQt5</li>
    <li>vtk_7</li>
    <li>vtk_8</li>
    <li>vtk_8_withQt5</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>f3d</li>
    <li>vtk_9</li>
    <li>vtk_9_withQt5</li>
  </ul>
</details>

**Comment by lheckemann** [comment]
This changes behaviour (no more headers placed directly in `$out/include`, and the option doesn't even have an effect on vtk 8.x and 7.x), and may break rtabmap. cc @ckiee

**Comment by veprbl** [comment]
> This changes behaviour (no more headers placed directly in `$out/include`, and the option doesn't even have an effect on vtk 8.x and 7.x), and may break rtabmap. cc @ckiee

Yes, it reverts the behavior of `vtk_7`, `vtk_8` and `vtk` back to its state before four months ago. Indeed, `VTK_VERSIONED_INSTALL` is only supported by `vtk_9`, but, maybe, in conjunction with switch to it (#178367) it should be satisfactory? I'm not sure how apps are supposed to depend on this behaviour if they unless they don't use cmake and already rely on VTK_VERSIONED_INSTALL (e.g., I saw it's enabled in archlinux).

**Comment by ckiee** [comment]
It seems it does indeed break rtabmap:
```
[ 14%] Linking CXX executable ../../bin/rtabmap-extractObject
/nix/store/cz52w8xf3i1d3xvzpzd9abf7rvpl9017-binutils-2.38/bin/ld: cannot find -lvtkGUISupportQt: No such file or directory
[ 14%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/camera/CameraStereoImages.cpp.o
collect2: error: ld returned 1 exit status
make[2]: *** [tools/ExtractObject/CMakeFiles/extractObject.dir/build.make:182: bin/rtabmap-extractObject] Error 1
make[1]: *** [CMakeFiles/Makefile2:960: tools/ExtractObject/CMakeFiles/extractObject.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by ckiee** [comment]
> Does it not use `${VTK_LIBRARY_DIRS}`? If not, then it's a bug there. https://cmake.org/cmake/help/v3.0/module/FindVTK.html

It doesn't, since it's using QVTK which is apparently different for some unholy reason. Also, that link is [outdated](https://cmake.org/cmake/help/latest/module/FindVTK.html) and it is using the now-recommended `FIND_PACKAGE(VTK)` but that is the non-Qt VTK and `FIND_PACKAGE(QVTK)` does not do the fancy stuff `VTKConfig.cmake` does[^1].

[^1]: Well, it sort of does, `vtkWithQt5`'s `lib/cmake` also has a `VTKConfig` but `vtk` seems to be prioritized for whatever reason.[^2]
[^2]: I have no idea how `vtk` even got into this pile since it's not a direct dependency of `rtabmap`, only `vtkWithQt5` is.

Could we maybe settle on adding a `$out/include/vtk` symlink to `vtk-x.x`? That way patching `rtabmap` will be trivial.

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 178291` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>ezminc</li>
    <li>freecad</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>rtabmap</li>
  </ul>
</details>
<details>
  <summary>46 packages built:</summary>
  <ul>
    <li>ants</li>
    <li>appcsxcad</li>
    <li>c3d</li>
    <li>cloudcompare</li>
    <li>csxcad</li>
    <li>elastix</li>
    <li>elmerfem</li>
    <li>f3d</li>
    <li>gdcm</li>
    <li>horizon-eda</li>
    <li>inkcut</li>
    <li>inkscape-extensions.inkcut</li>
    <li>itk</li>
    <li>itk4</li>
    <li>libsForQt5.qcsxcad (libsForQt515.qcsxcad ,plasma5Packages.qcsxcad)</li>
    <li>libsForQt512.qcsxcad</li>
    <li>libsForQt514.qcsxcad</li>
    <li>mirtk</li>
    <li>mrtrix</li>
    <li>octavePackages.dicom</li>
    <li>opencascade</li>
    <li>openems</li>
    <li>pcl</li>
    <li>python310Packages.dicom2nifti</li>
    <li>python310Packages.enamlx</li>
    <li>python310Packages.gdcm</li>
    <li>python310Packages.mayavi</li>
    <li>python310Packages.python-csxcad</li>
    <li>python310Packages.python-openems</li>
    <li>python310Packages.pythonocc-core</li>
    <li>python310Packages.vtk</li>
    <li>python39Packages.dicom2nifti</li>
    <li>python39Packages.enamlx</li>
    <li>python39Packages.gdcm</li>
    <li>python39Packages.mayavi</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
    <li>python39Packages.pythonocc-core</li>
    <li>python39Packages.vtk</li>
    <li>simpleitk</li>
    <li>smesh</li>
    <li>vtk (vtk_8)</li>
    <li>vtkWithQt5 (vtk_8_withQt5)</li>
    <li>vtk_7</li>
    <li>vtk_9</li>
    <li>vtk_9_withQt5</li>
  </ul>
</details>

**Comment by veprbl** [comment]
Any objections to this?

**Comment by ckiee** [comment]
This solution is more elegant than my original one so I'm good with it.

**Comment by veprbl** [comment]
I can not reproduce the issue seen on ofborg

**Comment by ckiee** [comment]
@ofborg build vtk_9

**Pull request merged**
