### PR TITLE
cups-filters: 1.16.0 -> 1.20.0

### PR DESCRIPTION
**Pull request by layus**

### CODE REVIEW

**Comment by jtojnar** [comment]
https://github.com/OpenPrinting/cups-filters/blob/release-1-20-0/NEWS

**Comment by jtojnar** [comment]
@GrahamcOfBorg eval

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by jtojnar** [comment]
@GrahamcOfBorg eval

**Pull request merged**
