### PR TITLE
secp256k1: init (native lib, and python ffi bindings at 0.12.1)

### PR DESCRIPTION
**Pull request by chris-martin**
This adds the [secp256k1](https://github.com/bitcoin-core/secp256k1) C lib from bitcoin-core, and [the corresponding python wrapper](https://github.com/ludbb/secp256k1-py).

There are no executables provided by either of these packages. I'm adding them because they're dependencies of [pyethereum](https://github.com/ethereum/pyethereum) (which will be coming in another PR).
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"` (new package, there are none)
- [x] Tested execution of all binary files (usually in `./result/bin/`) (there are none)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chris-martin** [comment]
I'm puzzled by the build failure. The `preConfigure` hook doesn't seem to be working on Travis.

**Comment by FRidh** [comment]
I was also able to build it locally, while using `nix.Sandbox`. The script already has a shebang, so instead of using `sh` try `./`.

Furthermore, the Python package is missing a dependency.

**Comment by chris-martin** [comment]
I switched it back to `./autogen.sh`. Now the build error is:

```
/nix/store/zwcvckg82fc7spbjnip73pynxr5pz5xc-stdenv/setup: line 69: ./autogen.sh: Permission denied
```

Still quite confused.

**Comment by FRidh** [comment]
Merged #16463 instead.

**Pull request closed without merging**
