### PR TITLE
vtk: 9.2.6 -> 9.3.1

### PR DESCRIPTION
**Pull request by bcdarwin**
## Description of changes

Routine update.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bcdarwin** [comment]
@ofborg build vtk

**Comment by bcdarwin** [comment]
The x86_64-darwin Hydra build seems to be timing, but unclear to me why.

**Comment by luzpaz** [comment]
Any progress here ?

**Comment by bcdarwin** [comment]
> Any progress here ?

Unfortunately no as I don't have a mac for local testing/debugging.

I thought about trying to revive https://github.com/NixOS/nixpkgs/pull/187016 (which leads to downstream build failures as it stands, and shouldn't merge cleanly any more) in hopes it might help, but same issue with that.

**Comment by bcdarwin** [comment]
I tailed the Hydra logs as it was building and it seems that it simply builds incredibly slowly, rather than hanging, on Darwin.

It'd be quite interesting to see if this reproduces locally as well, i.e. if 9.3.0 builds much more slowly than 9.2.6 on Darwin boxes, and if so, what sort of resource usage differences we see.

**Comment by MatthewCroughan** [comment]
I'm interested in getting this updated, maybe we can bump to 9.3.1 now also?

**Comment by MatthewCroughan** [comment]
Superceded by https://github.com/NixOS/nixpkgs/pull/354855

**Pull request closed without merging**
