### PR TITLE
lspce-module: 1.1.0-unstable-2024-07-14 -> 1.1.0-unstable-2024-08-04

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
@jian-lin this is what I was talking about: just promote lspce-module as a regular package and let `emacsPackages.lspce` concentrate only with "elispy" things.

**Comment by jian-lin** [comment]
Is this draft ready for review?

**Comment by AndersonTorres** [comment]
yes

**Review by adisbladis — COMMENTED** [review]
Does `lspce-module` have any use outside of `emacs.pkgs`? I don't think it should live in `by-name`?

**Comment by jian-lin** [comment]
> Does `lspce-module` have any use outside of `emacs.pkgs`?

I do not think so.

> I don't think it should live in `by-name`?

Agreed.

---

I will add some context.

The motivation of this PR is to make users be able to override `lspce`.

This PR provides one possible implementation.  https://github.com/NixOS/nixpkgs/pull/329709 is another possible implementation.  The code to override `lspce` of these two methods are very similar.

Note that there is yet another implementation: rewriting `lspce` with `finalAttrs`.  This method needs https://github.com/NixOS/nixpkgs/pull/330589.  The code to override `lspce` is much simpler:

```nix
lspce.overrideAttrs (old: {
  lspce-module = old.lspce-module.overrideAttrs (old': {
    ...
  });
})
```

**Comment by AndersonTorres** [comment]
Migrated to  emacsPackages.

**Comment by AndersonTorres** [comment]
Anything else, @jian-lin @adisbladis ?

**Comment by jian-lin** [comment]
A similar question: does `lspce-module` have any use outside of `emacs.pkgs.lspce`?  I do not think it should live in `emacs.pkgs`.  I may change my mind if you give me some examples in other package sets.

**Comment by AndersonTorres** [comment]
In practical terms, it does not. The only package that really needs lspce-module is lspce-elisp itself.

On the other hand:
- it is a good thing to override `lspce-module`
  - because it should not be a mere implementation detail - a postulate of this PR
- for all intents and purposes, `lspce-module` is a package
- overridable packages (if not all packages) are usually reachable from top-level
  - whether if directly (`lspce`) or indirectly (`emacs.pkgs.lspce`)
  - by far this the easiest way of overriding them, [at least for now](https://github.com/NixOS/nixpkgs/pull/296769)

"Not being useful besides lspce-elisp" does not look like a sufficient motivation to avoid the detachment.

**Comment by jian-lin** [comment]
> "Not being useful outside lspce-elisp" does not look like a sufficient motivation to avoid the detachment.

I am not convinced and I still think top-level packages should be useful on it own.

>     * it is a good thing to override `lspce-module`
>       
>       * because it should not be a mere implementation detail - a postulate of this PR

Why should it not be a mere implementation detail?  `lspce-module` being only useful inside `lspce` indicates that `lspce-module` is an implementation detail.

Even as an implementation detail, i.e., non top-level, it can still be overridden.  See https://github.com/NixOS/nixpkgs/pull/329709#issue-2428174740

>     * for all intents and purposes, `lspce-module` is a package

Being a package does not mean being a top-level package.

I think `lspce-module` being a package is caused by limitation of current build helpers.  See bellow for more info.  Ideally, it should not be a package and the module written in Rust can be built inside the `melpaBuild` of `lspce` just like how `emacs.pkgs.rime` builds its module (written in C) inside `melpaBuild`.

>     * overridable packages (if not all packages) are usually reachable from top-level
>       * by far this the easiest way of overriding them

With this PR applied, code to override `lspce` looks like

```nix
final: prev: {
  lspce-module = prev.lspce-module.overrideAttrs { ... };
  lspce = prev.lspce.overrideAttrs {
    inherit (final.lspce-module) version src;
  };
}
```

An alternative PR https://github.com/NixOS/nixpkgs/pull/329709 does not treat `lspce-module` as a top-level package.  With that PR applied, code to override `lspce` looks like

```nix
final: prev: {
  lspce = let lspce-module' = prev.lspce.lspce-module.overrideAttrs { ... }; in
    (prev.lspce.override { lspce-module = lspce-module'; }).overrideAttrs (old: {
    inherit (lspce-module') version src;
    passthru = old.passthru // { lspce-module = lspce-module'; }; # optional
  });
}
```

To be honest, I do not think one code is easier than another.  Both of them are not good because users have to know that `lspce` depends on `lspce-module` and have to change **two** places to achieve the goal of overriding **one** package.

I think the real issue is that currently different build helpers (`rustPlatform.buildRustPackage` and `emacs.pkgs.melpaBuild` here) does not compose, meaning you cannot call `stdenv.mkDerivation` only once when building a package using more than one language.  Well, you can if your two languages are C/C++ and something else.  But that is because `stdenv.mkDerivation` supports C/C++.

> 
> (Unfortunately I can't think about packages with the sole purpose of leveraging other single package)

I do find an example supporting my opinion: [vim-clap](https://github.com/NixOS/nixpkgs/blob/ffeda929060e51f730750b75ca2361d66594fbae/pkgs/applications/editors/vim/plugins/vim-clap/default.nix#L32).

**Comment by AndersonTorres** [comment]
I was elaborating an answer, however it would not be satisfactory.

My objection with your PR is, basically, two things:
- with one hand your are hiding a thing (lspce-module is not reachable from top-level);
- with the other hand you are exposing the same thing (lspce-module is a parameter).

---------------------------

The main problem is what you said, the builders are not composable.
Indeed my impression is that it was never cogitated before.

The examples you provided are not convincing, I should say.

-  vim-clap does not allow overriding `maple`.  Indeed vim-clap is equivalent to the current status quo of lspce-module.
-  `emacs.pkgs.rime` is not exactly built inside melpaBuild. It is overriden in the file `melpa-packages.nix`:

```nix
        rime = super.rime.overrideAttrs (old: {
          buildInputs = (old.buildInputs or [ ]) ++ [ pkgs.librime ];
          preBuild = (old.preBuild or "") +
          (if pkgs.stdenv.isDarwin then
            ''
              export MODULE_FILE_SUFFIX=".dylib"
              make lib
              mkdir -p /tmp/build/rime-lib
              cp *.dylib /tmp/build/rime-lib
            ''
          else
          ''
            make lib
            mkdir -p /build/rime-lib
            cp *.so /build/rime-lib
          '');
          postInstall = (old.postInstall or "") +
          (if pkgs.stdenv.isDarwin then
          ''
            install -m444 -t $out/share/emacs/site-lisp/elpa/rime-* /tmp/build/rime-lib/*.dylib
          ''
          else
          ''
            install -m444 -t $out/share/emacs/site-lisp/elpa/rime-* /build/rime-lib/*.so
          '');
        });
```

  How should `rime` be built if it was not accepted by MELPA?

The best I can think in this situation is to inject `lspce-module` as an extra attribute inside melpaBuild. I will upload an extra commit.

**Comment by jian-lin** [comment]
> * `emacs.pkgs.rime` is not exactly built inside melpaBuild. It is overriden in the file `melpa-packages.nix`

Why is `overrideAttrs` relevant here?  The point is that only one build helper (`melpaBuild`) is used so there is no composability issue.

> How should rime be built if it was not accepted by MELPA?

Create a normal manual elisp package and move what is now in `overrideAttrs` to `melpaBuild`.  That's it.  Nothing special.

<details>
<summary>Example</summary>

```nix
{
  melpaBuild,
  fetchFromGitHub,
  librime,
  dash,
  popup,
  posframe,
}:

melpaBuild {
  pname = "rime";
  version = "1.0.5-unstable-2024-01-30";

  src = fetchFromGitHub {
    owner = "DogLooksGood";
    repo = "emacs-rime";
    rev = "d8c0a99b0282d3e0aca53146789f6864181228e7";
    hash = "sha256-rx9SvIuMVL0Vt1uKbLhxbxTKyftdRp/BVj71hJIyQi4=";
  };

  packageRequires = [
    dash
    popup
    posframe
  ];

  buildInputs = [ librime ];

  preBuild = ''
    make lib
    export RIME_LIB_DIR=$NIX_BUILD_TOP/rime-lib
    mkdir -p $RIME_LIB_DIR
    cp *.so $RIME_LIB_DIR
  '';

  postInstall = ''
    install -m444 -t $out/share/emacs/site-lisp/elpa/rime-* $RIME_LIB_DIR/*.so
  '';

  ignoreCompilationError = false;
}
```

</details>

> The best I can think in this situation is to inject lspce-module as an extra attribute inside melpaBuild.

What is the point of this completely syntactic refactoring?  I fail to see how it improves user experience for overriding.  In this implementation, to override `lspce`, `files` still has to be changed besides `src`, `version` and `lspce-module`.

---

About composability, I find that with some modifications, the rust build helper does compose well with elisp build helpers.  See the rewriting of `lspce` in https://github.com/NixOS/nixpkgs/pull/334476.

**Comment by AndersonTorres** [comment]
> What is the point of this completely syntactic refactoring? I fail to see how it improves user experience for overriding. 

It would be visible to `overrideAttrs` instead of `override`.

**Pull request closed without merging**
