### PR TITLE
drop my maintainership

### PR DESCRIPTION
**Pull request by ghost**
Hi, I'd like to drop my maintainership and membership of the nixpkgs.
It's wonderful to work on nixpkgs and nixos, but nowadays I use GuixSD (which is heavily based on nix and nixos) and don't use those applications anymore (I still use nix for some haskell packages, etc.  but
I don't maintain them).
It's better to let those packages maintained by folks who actually use them.

Thanks!

### CODE REVIEW

**Comment by joachifm** [comment]
If you want to stop receving mention-bot spam, add yourself to https://github.com/NixOS/nixpkgs/blob/master/.mention-bot

**Comment by domenkozar** [comment]
Thank you for all contributions :cake:

**Comment by lethalman** [comment]
Thanks for all, good thing you are still in nix land though :)

**Comment by vcunat** [comment]
Thank you. I picked it to 16.03 as well.
>  It's better to let those packages maintained by folks who actually use them.

Unfortunately, almost all of those packages have no other maintainer set.

**Pull request closed without merging**
