### PR TITLE
arduino: 1.6.9 -> 1.6.12 (second try)

### PR DESCRIPTION
**Pull request by cko**
###### Things done
- [x] Tested using sandboxing
  `nix-env --option build-use-sandbox true -f . -iA arduino`
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

hopefully this one works better than the first one ;-)

### CODE REVIEW

**Review by sternenseemann — APPROVED** [review]
Works for me as well on NixOS! :+1:

**Comment by grahamc** [comment]
I'm not ableto build this:

```
untar-unzip-download:
      [get] Getting: https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/releases/download/v0.8.0/WiFi101-Updater-ArduinoIDE-Plugin-0.8.0.zip
      [get] To: /tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/shared/WiFi101-Updater-ArduinoIDE-Plugin-0.8.0.zip
      [get] Error getting https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/releases/download/v0.8.0/WiFi101-Updater-ArduinoIDE-Plugin-0.8.0.zip to /tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/shared/WiFi101-Updater-ArduinoIDE-Plugin-0.8.0.zip

untar-unzip-checksum:
     [echo] Testing checksum of "shared/WiFi101-Updater-ArduinoIDE-Plugin-0.8.0.zip"
 [checksum] Could not find file /tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/shared/WiFi101-Updater-ArduinoIDE-Plugin-0.8.0.zip to generate checksum for.

BUILD FAILED
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:102: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:627: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:210: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:830: Could not find file /tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/shared/WiFi101-Updater-ArduinoIDE-Plugin-0.8.0.zip to generate checksum for.

Total time: 2 seconds
builder for ‘/nix/store/gsncd51mrpbsfd1dxhw7f21f9v2ljhws-arduino-1.6.12.drv’ failed with exit code 1
error: build of ‘/nix/store/gsncd51mrpbsfd1dxhw7f21f9v2ljhws-arduino-1.6.12.drv’ failed
```

**Comment by cko** [comment]
@grahamc would you mind testing it again?

**Comment by cko** [comment]
@sternenseemann you need to add `nix.useSandbox = true;` to your nixos configuration to enable a fully sandboxed build for this package.

**Comment by sternenseemann** [comment]
@cko what problem does non-sandboxed cause?

**Comment by bjornfor** [comment]
Possibly this PR caused arduino build breakage on Hydra:

https://hydra.nixos.org/build/41847201

**Comment by cko** [comment]
@bjornfor thanks for noticing. See #19435

**Comment by cko** [comment]
@sternenseemann it allows network access while building. So it can download dependencies which are listed in `build/build.xml` but are not explicitly declared in `downloads.nix`, which shouldn't happen.

**Comment by sternenseemann** [comment]
@cko how does it even build on hydra without network access?

**Pull request merged**
