### PR TITLE
ocamlPackages.angstrom 0.14.1 and update of all affected packages (encore, git)

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

angstrom 0.14 (now bugfixed [0.14.1](https://github.com/inhabitedtype/angstrom/releases/tag/0.14.1)) broke some libraries due to an API change, in nixpkgs `encore` and `git` (and indirectly the irmin libraries). Since [encore 0.5](https://github.com/mirage/encore/releases/tag/v0.5) and [git 2.1.3](https://github.com/mirage/ocaml-git/releases/tag/2.1.3) have been released, we can go to angstrom 0.14.1 in nixpkgs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

If this is merged, #90630 can be closed

### CODE REVIEW

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build ocamlPackages.angstrom-lwt ocamlPackages.angstrom-unix ocamlPackages.angstrom-async ocamlPackages.irmin-unix

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build ocaml-ng.ocamlPackages.email_message

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build ocaml-ng.ocamlPackages_4_06.email_message

**Comment by sternenseemann** [comment]
Probably should check if the test skipping for `git` and `git-unix` also works on darwin.

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build ocamlPackages.angstrom-lwt ocamlPackages.angstrom-unix ocamlPackages.angstrom-async ocamlPackages.irmin-unix ocaml-ng.ocamlPackages_4_06.email_message

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.bigarray-overlap

**Comment by vbgl** [comment]
Merged bigarray-overlap as fce108ef60c2518fb84cde47fdefc45424aa9ab1

**Comment by vbgl** [comment]
Merged into master as 2c616aa63895f064ac1b1332a8cf9e7ae3ddbb44

**Pull request closed without merging**
