### PR TITLE
bazel: 0.24.0 -> 0.25.1

### PR DESCRIPTION
**Pull request by kalbasit**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by kalbasit** [comment]
@Profpatsch For some reason `native.bazel_version` is not set, and the rule_nodejs rules are failing because of it. This happens at the `installPhase`. I'm stuck on it, thoughts?

```
DEBUG: /build/bazel_zbwenLNJ/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5:
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /build/bazel_zbwenLNJ/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.
```

They now ship with [rules_nodesjs](https://github.com/bazelbuild/bazel/blob/582b79ef3e2c9c9ae1878eedd2771df11c5f6061/WORKSPACE#L470) included?

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build bazel

**Comment by Profpatsch** [comment]
The problem here is that https://github.com/bazelbuild/bazel/commit/6f52fcaa3eec51f465ebb5c6a2c0e1361de821aa adds a new remote dep, `skydoc`. That is pulled in by the tests we run after the build, but it’s not locally available, so bazel tries to download it.

I’m taking a shot at debugging why the tests pull in the skydoc repository, but maybe it is best to disable the tests for now.

**Comment by Profpatsch** [comment]
It could also have something to do with the `bazel_java_tools` artifact being out of date.
Sadly, @groodt didn’t add a comment where he got the link to the tarball from when he added the artifact, and I have not the slightest idea where to search for it …

**Comment by groodt** [comment]
> Sadly, @groodt didn’t add a comment where he got the link to the tarball from when he added the artifact, and I have not the slightest idea where to search for it …

During `postInstall`, it attempts to run some test builds using the `WORKSPACE`. For `0.24.1` which I helped with, it's here:
https://github.com/bazelbuild/bazel/blob/f092ec388a4b58788285b928c86f0f81561d4be4/WORKSPACE#L120

**Comment by groodt** [comment]
For 0.25.1, looks like the WORKSPACE is more comprehensive and loading a bunch of rules:

```
load("@io_bazel_skydoc//:setup.bzl", "skydoc_repositories")

skydoc_repositories()

load("@io_bazel_rules_sass//:package.bzl", "rules_sass_dependencies")

rules_sass_dependencies()

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")

node_repositories()

load("@io_bazel_rules_sass//:defs.bzl", "sass_repositories")
```

All of those will hydrate files from the internet.

**Comment by kalbasit** [comment]
closing this in favor of #62336

**Pull request closed without merging**
