### PR TITLE
patsy: init at 0.3.0

### PR DESCRIPTION
**Pull request by FRidh**
Built locally. 

As with other packages that I built and installed I wasn't able to import it though. Any idea why?

### CODE REVIEW

**Comment by FRidh** [comment]
> The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

> The build has been terminated.

**Comment by vbgl** [comment]
What do you mean by “able to import it”?

**Comment by FRidh** [comment]
`import patsy` in the python interpreter

**Comment by vbgl** [comment]
You need to set-up an environment in which your package is properly available from the python interpreted. One way to do so is to use `nix-shell`. E.g.:

```
nix-shell -p python34Packages.patsy
```

More details may be found in the [wiki](https://nixos.org/wiki/Development_Environments).

**Comment by FRidh** [comment]
That works with existing packages but does not seem to work with a newly created one such as this one.

What I tried before, is to check out the current nixos-version, add the package definition, and run 'nix-env -f . -iA pkgs.python34Packages.multipledispatch' (example with another package). I can see that the package is built. The dependencies were already in my current environment. And it doesn't matter whether the current environment is the main one, or a nix-shell with python installed from which I build and install the package. I just can't import it.

Another thing I tried was:
```
with import <nixpkgs> {};

buildPythonPackage rec {
    name = "multipledispatch-${version}";
    version = "0.4.8";
   
    src = pkgs.fetchurl {
      url = "https://pypi.python.org/packages/source/m/multipledispatch/${name}.tar.gz";
      md5 = "f0eb0c527cdbe788ca7dcd1511bc49a9";
    };
    
    meta = {
      homepage = "http://github.com/mrocklin/multipledispatch/";
      description = "A relatively sane approach to multiple dispatch in Python.";
      license = licenses.bsd3;
    };
}
```
and then run `nix-shell`. But again, I cannot import the package.

**Comment by FRidh** [comment]
Finally I got it. 

To open a shell with a package based on a local copy of nixpkgs, 
`nix-shell -I nixpkgs=/path/to/nixpkgs -p python34Packages.newpackage python34Packages.pandas`

**Pull request merged**
