### PR TITLE
pythonPackages.wxPython: use buildPythonPackage

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This is an attempt at using `buildPythonPackage` for building `wxPython`.

Building a wheel seems to work. The problem seems to be that `setup.py` is in a different folder, so we change to that folder. However, the wheel is now somewhere else and the `installPhase` looks in the wrong place. Therefore, we need to either override one of the phases, or we modify `buildPythonPackage` to output the wheel in a fixed location. Currently, it outputs it in a folder relative to where `python setup.py bdist_wheel` is run, which is non-standard in this case.

Related issue: #14914

### CODE REVIEW

**Comment by FRidh** [comment]
`wxPython30` works just like before. And `wxpython28` gives
```
wrapping `/nix/store/zbl20prds56bv2yfg9992x2575vi2fn3-python2.7-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/tools/Editra/Editra.pyw'...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/zbl20prds56bv2yfg9992x2575vi2fn3-python2.7-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/nix/store/zbl20prds56bv2yfg9992x2575vi2fn3-python2.7-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
```
At least now it happens already during installation of the package, and not only during runtime.

**Comment by FRidh** [comment]
It seems that wxPython 2.8 is linked to two versions of libgobject:
```
freddy@fr-laptop:/nix/store/zbl20prds56bv2yfg9992x2575vi2fn3-python2.7-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx$ ldd _core_.so | grep libgobject
        libgobject-2.0.so.0 => not found
        libgobject-2.0.so.0 => /nix/store/40pvvzrgmq59av93g6sgycpy16d7sqjj-glib-2.48.0/lib/libgobject-2.0.so.0 (0x00007f9e8d213000)
```
This is not the case with 3.0.

I also tried with a copy of wxPython from the GitHub repo
https://github.com/wxWidgets/wxPython/archive/wxPy-2.8.12.1.tar.gz
but that file seemed to miss a folder
`error: package directory 'wx/lib/agw' does not exist`

**Comment by seschwar** [comment]
The wxPython 2.8 errors aren't related to your changes. It was already broken: #14914.

**Comment by FRidh** [comment]
Yes I am aware of the errors, it is the reason I began with this. It can be fixed without changing to buildPythonPackage, but while I am at it I might as well make the conversion :-)

**Comment by FRidh** [comment]
closing in favor of #15764

**Pull request closed without merging**
