### PR TITLE
Update skarnet packages & add ssl support to s6-networking

### PR DESCRIPTION
**Pull request by Profpatsch**
This should leave all skarnet packages in nixpkgs at their currently latest versions.
`s6-networking` gets `libressl` as additional input, so that it creates two new binaries, `s6-tlsclient` and `s6-tlsserver`.

cc other maintainer @pmahoney

### CODE REVIEW

**Review by pmahoney — APPROVED** [review]
Looks great. Great work on previous patch btw.

Will try to build on darwin if I can find the time today.

**Comment by pmahoney** [comment]
Built (along with all of s6-network's dependencies) and seems to run ok on darwin

**Comment by Profpatsch** [comment]
Very nice, I will merge then.

Out of curiosity: What are you using the skarnet tools for, @pmahoney?

**Comment by pmahoney** [comment]
Nothing at the moment... in previous job was using it for managing local services (on my development machine) and also in a couple places wrapping scripts in ipcserver.

**Pull request merged**
