### PR TITLE
vale-style-{microsoft,google,write-good,proselint,joblint,alex,readability}: init at various

### PR DESCRIPTION
**Pull request by katexochen**
## Description of changes

Adding different style packages for [`vale`](https://search.nixos.org/packages?channel=23.11&show=vale&from=0&size=50&sort=relevance&type=packages&query=vale).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by msanft — APPROVED** [review]

**Comment by marsam** [comment]
Thanks for your contribution!

I was thinking that maybe we could group the styles in a `valeStyles`: https://github.com/marsam/nixpkgs/commit/c33908c1fd6dfa0e95efedb5b54f422141651ac0 (basic implementation)
What do you think?

**Comment by katexochen** [comment]
> I was thinking that maybe we could group the styles in a `valeStyles`: [marsam@c33908c](https://github.com/marsam/nixpkgs/commit/c33908c1fd6dfa0e95efedb5b54f422141651ac0) (basic implementation) What do you think?

Thanks @marsam, looks like a nice idea! Can you add the remaining styles of this PR and open a PR with your suggestion? I'm happy to review. :)

**Comment by katexochen** [comment]
@marsam or do you want me to adapt that pattern in this PR?

**Comment by marsam** [comment]
@katexochen sorry for the delay. I created a PR with my approach https://github.com/NixOS/nixpkgs/pull/301204

**Comment by katexochen** [comment]
Closed in favor of https://github.com/NixOS/nixpkgs/pull/301204

**Pull request closed without merging**
