### PR TITLE
nodePackages: add more coc-nvim extensions

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Adds the coc extensions I needed and does an update of the nodePackages set.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 106621` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>rambox-pro</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>matrix-recorder</li>
  </ul>
</details>
<details>
  <summary>65 packages built:</summary>
  <ul>
    <li>antora</li>
    <li>base16-builder</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>commitizen</li>
    <li>create-cycle-app</li>
    <li>emojione</li>
    <li>epgstation</li>
    <li>etcher</li>
    <li>flood</li>
    <li>gtop</li>
    <li>image_optim</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>lumo</li>
    <li>mastodon-bot</li>
    <li>mirakurun</li>
    <li>n8n</li>
    <li>netlify-cli</li>
    <li>newman</li>
    <li>parity-ui</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>python37Packages.batchspawner</li>
    <li>python37Packages.dockerspawner</li>
    <li>python37Packages.jupyterhub</li>
    <li>python37Packages.jupyterhub-ldapauthenticator</li>
    <li>python37Packages.jupyterhub-systemdspawner</li>
    <li>python37Packages.jupyterhub-tmpauthenticator</li>
    <li>python37Packages.oauthenticator</li>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>ripcord</li>
    <li>slack</li>
    <li>sloc</li>
    <li>teleprompter</li>
    <li>thelounge</li>
    <li>twemoji-color-font</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-snippets</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-tsserver</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.coc-yaml</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
    <li>yaml-language-server</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
So, the editorconfig failure is in some autogen'd files. Can it be ignored?

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 106621` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>dat</li>
    <li>remarkjs</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>matrix-recorder</li>
  </ul>
</details>
<details>
  <summary>68 packages built:</summary>
  <ul>
    <li>airfield</li>
    <li>antora</li>
    <li>base16-builder</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>commitizen</li>
    <li>create-cycle-app</li>
    <li>emojione</li>
    <li>epgstation</li>
    <li>etcher</li>
    <li>flood</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>image_optim</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>lumo</li>
    <li>mastodon-bot</li>
    <li>mirakurun</li>
    <li>n8n</li>
    <li>netlify-cli</li>
    <li>newman</li>
    <li>nixui</li>
    <li>parity-ui</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>python37Packages.batchspawner</li>
    <li>python37Packages.dockerspawner</li>
    <li>python37Packages.jupyterhub</li>
    <li>python37Packages.jupyterhub-ldapauthenticator</li>
    <li>python37Packages.jupyterhub-systemdspawner</li>
    <li>python37Packages.jupyterhub-tmpauthenticator</li>
    <li>python37Packages.oauthenticator</li>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>ripcord</li>
    <li>slack (slack-dark)</li>
    <li>sloc</li>
    <li>teleprompter</li>
    <li>thelounge</li>
    <li>twemoji-color-font</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-snippets</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-tsserver</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.coc-yaml</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
    <li>yaml-language-server</li>
  </ul>
</details>

**Comment by midchildan** [comment]
It's not ideal, but I guess it's easier to add the newlines manually as there's only 6 files that needs fixing.

**Comment by midchildan** [comment]
I think what's bit more problematic is how `util-linux` is replaced with `util-linux`, undoing recent changes made in https://github.com/NixOS/nixpkgs/pull/104776.

This seems to have been fixed in node2nix with https://github.com/svanderburg/node2nix/pull/215, but it's not released yet.

**Comment by lovesegfault** [comment]
> I think what's bit more problematic is how `util-linux` is replaced with `utillinux`, undoing recent changes made in #104776.
> 
> This seems to have been fixed in node2nix with [svanderburg/node2nix#215](https://github.com/svanderburg/node2nix/pull/215), but it's not released yet.

Agreed, maybe we need to ask @svanderburg for a new release to be cut?

**Comment by lovesegfault** [comment]
This will have to wait on a new node2nix.

**Pull request closed without merging**
