### PR TITLE
Remove Echo Nolan from maintainers

### PR DESCRIPTION
**Pull request by enolan**
I'm not using Nix anymore.

### CODE REVIEW

**Comment by peti** [comment]
Why does this patch remove `raskin` from the list of maintainers of `nspluginwrapper`?

**Comment by peti** [comment]
Also, please remove yourself from `pkgs/applications/networking/browsers/mozilla-plugins/flashplayer-11/default.nix`, too.

**Comment by enolan** [comment]
My bad. Fixed.

**Comment by cillianderoiste** [comment]
Thanks @enolan.

**Comment by vcunat** [comment]
Bye!

**Pull request merged**
