### PR TITLE
python312: 3.12.2 -> 3.12.3; python311: 3.11.8 -> 3.11.9

### LINKED ISSUE #303020: Update request: python3 3.11.8 -> 3.11.9, python312 3.12.2 -> 3.12.3
- Package name: python3, python312
- Latest released version: 3.11.9, 3.12.3

- Current version on the unstable channel: 3.11.8, 3.12.2
- Current version on the stable/release channel: 3.11.8, 3.12.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---
@FRidh 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by mweinelt**
https://docs.python.org/release/3.12.3/whatsnew/changelog.html
https://docs.python.org/release/3.11.9/whatsnew/changelog.html

## Things done

- Built on platform(s) (python311.tests, python312.tests)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc
https://docs.python.org/release/3.12.3/whatsnew/changelog.html

### CODE REVIEW

**Comment by mweinelt** [comment]
aarch64-linux

```
/nix/store/7iyf4mc2041i82ahki4w5b98ndm1f8pc-import-requests
/nix/store/ly6ziq5pgrxqsdrqsggfv590icfbf5z6-python-gdb
/nix/store/xck49n3dlcgldgpi1wcwax8vr7pkv9mj-python3-3.11.9-site-prefix-mypy-test
/nix/store/yrp96f5nrhb8b7qnn3kr5l87rj8cxaw3-python3-3.11.9-tests-nixenv
/nix/store/6dl5h3cnpk7b2xrn96mdqpj6lw69vnqw-python3-3.11.9-tests-nixenv-venv-copies
/nix/store/6ilgxb7rldcjsyfrbci07ww4r2iqff63-python3-3.11.9-tests-nixenv-venv-links
/nix/store/64y7jain67kb62003l6byqadckrw475j-python3-3.11.9-tests-nixenv-virtualenv-copies
/nix/store/s3wqldc7v9w465dm6397rj795gdg1haz-python3-3.11.9-tests-nixenv-virtualenv-links
/nix/store/bxy5is49cvggzravsxn8m7vk9705pgpa-check-meta-pkg-config-modules-for-python3-3.11.9
/nix/store/ar3ijw7gcnxb9vvk4p586q2qz4zydc24-python3-3.11.9-tests-plain
/nix/store/s6dqnbgay3r8bpp62rrawb5vxvbwvzxf-python3-3.11.9-tests-plain-venv-copies
/nix/store/sm2mz1m9mcr7zb5ix7aii24d4rmcd07c-python3-3.11.9-tests-plain-venv-links
/nix/store/h4xizvn4fpx1xw8c234zd5m7hpzmycb5-python3-3.11.9-env
/nix/store/q525zsvwkhxj5q1mwa8h759i2vh89v1z-python3.11-setuptools-69.1.1
/nix/store/gbh7d8xsa39750jfyvk7kzy6miqzw14x-python3-3.11.9-tkinter-test
/nix/store/anjplzmbgrx32r4xijbr6h34gxkxy8m2-import-requests
/nix/store/ghf7fczhcm1k5dhqms5n8djclvl5hisr-python-gdb
/nix/store/97r6gs1rqipx8c50q4vn37q1psdsilmd-python3-3.12.3-site-prefix-mypy-test
/nix/store/nl0362b49nypwlq1i0jg3lw6vn80gbc7-python3-3.12.3-tests-nixenv
/nix/store/6zpvmkzkmk8lkppq0phhqc31jz5clccc-python3-3.12.3-tests-nixenv-venv-copies
/nix/store/a985qm9kx71msgbazw02g0p0cnhxhz36-python3-3.12.3-tests-nixenv-venv-links
/nix/store/z8cy00xb0hmy8gv696ps36pcmznzvg2q-python3-3.12.3-tests-nixenv-virtualenv-copies
/nix/store/b575ibihvahzpzyjmqjd5bgrchxy7wrg-python3-3.12.3-tests-nixenv-virtualenv-links
/nix/store/kpc4rb4id723pw82dmmvim1r315f5s7p-check-meta-pkg-config-modules-for-python3-3.12.3
/nix/store/b0s09dmlm7svhd8cd93w9mwv4xh89rax-python3-3.12.3-tests-plain
/nix/store/c3r3dgx3qpcazs4mjim6q6z0i99cbpap-python3-3.12.3-tests-plain-venv-copies
/nix/store/wi01qzx1n4fyjqbww6gjlpy4ih3ih971-python3-3.12.3-tests-plain-venv-links
/nix/store/swphm41vjd3qiblfsmdvfy941919zd5q-python3-3.12.3-env
/nix/store/fzvx0b6qln0cdl7z7y6xwi16bkgq6jgb-python3.12-setuptools-69.1.1
/nix/store/ngd6y5l6b5ys1j40j0lgvjajna9ivk96-python3-3.12.3-tkinter-test

**Comment by natsukium** [comment]
Tests for 3.11.9 fail on aarch64-darwin.
I don't know if there is a problem with this bump yet.
https://github.com/NixOS/nixpkgs/pull/301257#issuecomment-2042757531

**Comment by mweinelt** [comment]
x86_64-linux

```
/nix/store/h3ahma2drg42z9p3kpxmra87b3xckjih-import-requests
/nix/store/fyxglgdn5mif99ivcmr3j63c7g74qd9d-python-gdb
/nix/store/pnwz8yw15kydw3cz31yi27jgna41dy7s-python3-3.11.9-site-prefix-mypy-test
/nix/store/k9dsz42nwj2ak017k9zf6hhvvzps846m-python3-3.11.9-tests-nixenv
/nix/store/5mlf7i1kfhwika1ibf10wglbafphjnwj-python3-3.11.9-tests-nixenv-venv-copies
/nix/store/dicmdi1xk9b0wrv2gxajpwxhc6ia6i2q-python3-3.11.9-tests-nixenv-venv-links
/nix/store/dgqa2ka55sli2pxlb732krd6n675wai2-python3-3.11.9-tests-nixenv-virtualenv-copies
/nix/store/v46xf0x7s9hlci6b8kgdgc7hz8hmgg34-python3-3.11.9-tests-nixenv-virtualenv-links
/nix/store/zd9br2zsdhqkrhn1xj0iqbx112ziy3y1-check-meta-pkg-config-modules-for-python3-3.11.9
/nix/store/vx76m7r0zsdkrbk4kd761fjwk9n65rf3-python3-3.11.9-tests-plain
/nix/store/ivhvnpdbm1vl2swn219iqmiqcgr1djqb-python3-3.11.9-tests-plain-venv-copies
/nix/store/1vcv5zrxidajva72nnp88wykssvvr3yk-python3-3.11.9-tests-plain-venv-links
/nix/store/bxbns7nwq6d92649qgfgj87wbi39zkfn-python3-3.11.9-env
/nix/store/y84m2vsql1bj830nyynsypsbf5jlwm1x-python3.11-setuptools-69.1.1
/nix/store/0y14sy369h6fjxf6cycp9irw9n9451sj-python3-3.11.9-tkinter-test
/nix/store/j3g999yj5vmz9675vlh5idpf9mgg3rxw-import-requests
/nix/store/f5m34p8czg7i50f2vvnhcfv4k2iqzzqh-python-gdb
/nix/store/kxi126g57pils01jx01a2vd9nqyl5fsb-python3-3.12.3-site-prefix-mypy-test
/nix/store/39q8hb00lq3p45asrd1nlqmpvajsqdf7-python3-3.12.3-tests-nixenv
/nix/store/6yazad93rw2kqpd0wjfryq0br4dws0zz-python3-3.12.3-tests-nixenv-venv-copies
/nix/store/d5wqvhb0i27k42s2lg0947sx4fdv35ls-python3-3.12.3-tests-nixenv-venv-links
/nix/store/al22y9db9w32y947l2ilvkrz2n409vxa-python3-3.12.3-tests-nixenv-virtualenv-copies
/nix/store/lvdm2smsi0lwxz7b6cwgdbsp1kll8486-python3-3.12.3-tests-nixenv-virtualenv-links
/nix/store/4chnnnbb2cn5ljwg66j4f80a4708gi9s-check-meta-pkg-config-modules-for-python3-3.12.3
/nix/store/jccjvr320ppp2145amr5mwm73dbma310-python3-3.12.3-tests-plain
/nix/store/cgyc0sm03yz2xbcabc5aix0dncx529pk-python3-3.12.3-tests-plain-venv-copies
/nix/store/49r4cymbvkqj9sw74h3jv09chkl8lpqf-python3-3.12.3-tests-plain-venv-links
/nix/store/iqfbrbbxdphvjq00yqd3pcvgci02phgj-python3-3.12.3-env
/nix/store/siw0157qqz3n8nldkb5pgqr0m2rsz9d1-python3.12-setuptools-69.1.1
/nix/store/nqx0p8641c3v7i2821byb0kx1v1v2944-python3-3.12.3-tkinter-test

**Comment by natsukium** [comment]
> Tests for 3.11.9 fail on aarch64-darwin. I don't know if there is a problem with this bump yet. [#301257 (comment)](https://github.com/NixOS/nixpkgs/pull/301257#issuecomment-2042757531)

Looks like it's already broken in staging regardless of this change.

**Review by natsukium — APPROVED** [review]

**Comment by mweinelt** [comment]
I think I have seen that test failure before, but failed to debug it and gave up. Wondering why I didn't disable it back then.

**Comment by mweinelt** [comment]
aarch64-darwin

```
/nix/store/b2x9djlhvp2mnychfmlivk0kbkygifa9-python3-3.11.9-site-prefix-mypy-test
/nix/store/0b5v4ql68i5azlm28a0n2v6s8y1n916g-python3-3.11.9-tests-nixenv
/nix/store/db1d30g58xdh0slzm75zliybi0ixh5vb-python3-3.11.9-tests-nixenv-venv-copies
/nix/store/wf8kac85rzh83ly982as569d79b40q3d-python3-3.11.9-tests-nixenv-venv-links
/nix/store/532g9fp3slr25y0yabgjb230mn0ncqaw-check-meta-pkg-config-modules-for-python3-3.11.9
/nix/store/ghjvghrav33aiprr2rpp3i0y69717j2z-python3-3.11.9-tests-plain
/nix/store/g512zmfm75j1sbzw37y557cn6m0k3ak9-python3-3.11.9-tests-plain-venv-copies
/nix/store/94bdsrlf09i42ci7ag78c73rsfcr7d8c-python3-3.11.9-tests-plain-venv-links
/nix/store/h1734wvdf5dfd6y7h75f1zhrbxsixja1-python3-3.11.9-env
/nix/store/k6jjwyd6pz6626qsmy7ql16kkd5h1zn3-python3.11-setuptools-69.1.1
/nix/store/8skbxbhi4ym07dgpvc8j0xvx31j0i74f-python3-3.11.9-tkinter-test
/nix/store/ij792jg5qz11pl6p2ywv53hs50ff739a-python3-3.12.3-site-prefix-mypy-test
/nix/store/6gr8lvf2dv9rpyp18pc5rd4rqlmzrc4f-python3-3.12.3-tests-nixenv
/nix/store/ib6q2kxf32y2zrbza4zfb1lvmz58fi7c-python3-3.12.3-tests-nixenv-venv-copies
/nix/store/c9vlnj1zqxkxkf5zk1kx1k36p48xjy0n-python3-3.12.3-tests-nixenv-venv-links
/nix/store/pjqx5a4593dfy8j9f7ljifhrdbsl6jc2-check-meta-pkg-config-modules-for-python3-3.12.3
/nix/store/5jmnaa646dj5z2f1cxskkkwa0nk2rk5k-python3-3.12.3-tests-plain
/nix/store/iwgwzak1szmdqzy5a75i5ixdn4ghapfd-python3-3.12.3-tests-plain-venv-copies
/nix/store/7qnv3rdg8rs8v007fp72jijzp2px5kiq-python3-3.12.3-tests-plain-venv-links
/nix/store/rmxbsb6s2z0xsbkki117yywfcfdgcvxn-python3-3.12.3-env
/nix/store/yy6i8987zs1qpfvknfmbx07y8jxs0718-python3.12-setuptools-69.1.1
/nix/store/086bfmf8lcl4b8n2m3w5dzlv7cpjpgj6-python3-3.12.3-tkinter-test

**Comment by mweinelt** [comment]
x86_64-darwin

```
/nix/store/qh2y7krgq6fzmj90vyy0d16s10adam9q-python3-3.11.9-site-prefix-mypy-test
/nix/store/pcmpvzry1yzqdif62swx0ayvaiqiizyc-python3-3.11.9-tests-nixenv
/nix/store/x7gff9kqh78mysd3m17k0r3hpq5mfw8v-python3-3.11.9-tests-nixenv-venv-copies
/nix/store/2r7vqsmkl629q0xpc64j8ng5sx5qipna-python3-3.11.9-tests-nixenv-venv-links
/nix/store/bxm662ip59grd8i2fmzl9zz9w7y038cr-check-meta-pkg-config-modules-for-python3-3.11.9
/nix/store/d8w9mfzdk18hplr97hq5b9nj5ndl1p4d-python3-3.11.9-tests-plain
/nix/store/366s2vkhkzv5n7b18bqdrbryjb7bwmq5-python3-3.11.9-tests-plain-venv-copies
/nix/store/fspjh3mm3x23bxkf82ygbaw1g4590df7-python3-3.11.9-tests-plain-venv-links
/nix/store/7iqgbisw2gi39z3n34x59dps2wfsf8fl-python3-3.11.9-env
/nix/store/wcpr46j2bqjrbzj819h7f4av9kzjmmpk-python3.11-setuptools-69.1.1
/nix/store/k7h4l1g1ilfbnpyk7nwmjdba2d55yrn7-python3-3.11.9-tkinter-test
/nix/store/4phmnwjy9fs8zyjwavyy0llsqpv5hn31-python3-3.12.3-site-prefix-mypy-test
/nix/store/qr7vb55c1p3p4mdqb60lm706gdg4x5y7-python3-3.12.3-tests-nixenv
/nix/store/rz7qcsj8x82f7alb89w4rrld1n5zbw47-python3-3.12.3-tests-nixenv-venv-copies
/nix/store/gassc2ik1fc48dqqa9p0jg909bqci8p4-python3-3.12.3-tests-nixenv-venv-links
/nix/store/k8bx9mkmvvj9q4bidqfljxhmilani0iq-check-meta-pkg-config-modules-for-python3-3.12.3
/nix/store/dmr87hsb3ha19pw8m6bx61zqkv18fkqg-python3-3.12.3-tests-plain
/nix/store/ppiwss39w24vz07y1jy8lixz2p5wq62g-python3-3.12.3-tests-plain-venv-copies
/nix/store/3fsb6xgybnndm28ikzrg3yvwykqxcfnr-python3-3.12.3-tests-plain-venv-links
/nix/store/l1ls5y0jxichc7vcs2x4maqx1x229sfd-python3-3.12.3-env
/nix/store/0kz4qfcgwrvsva1h8al13z20q488z8m5-python3.12-setuptools-69.1.1
/nix/store/1s27lc4dcbpq135dlbwzlc3scxk29lia-python3-3.12.3-tkinter-test
```

**Comment by SuperSandro2000** [comment]
Do you think the passthru.tests disable commit for darwin can be reverted together with #302385?

**Pull request merged**
