### PR TITLE
monero-gui: fix missing qml imports

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Fix the currently broken monero-gui.
needs #57247 

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
Can you rebase this on current master such that #57210 is included?

**Comment by rnhmjoj** [comment]
Done.

**Comment by Infinisil** [comment]
I get this when I start it:
```
2019-03-26 23:33:59,733 INFO  [default] Page size: 4096
2019-03-26 23:34:01.830	    7f69f527cc40	WARN 	frontend	src/wallet/api/wallet.cpp:367	app startd (log: /home/infinisil/.cache/monero-project/monero-core/monero-wallet-gui.log)
2019-03-26 23:34:01.853	    7f69f527cc40	WARN 	frontend	src/wallet/api/wallet.cpp:367	Qt:5.12.0 | screen: 2560x1440 - dpi: 96.2922 - ratio:0.849972
2019-03-26 23:34:06.665	    7f69f527cc40	WARN 	frontend	src/wallet/api/wallet.cpp:367	QQmlApplicationEngine failed to load component
2019-03-26 23:34:06.665	    7f69f527cc40	WARN 	frontend	src/wallet/api/wallet.cpp:367	qrc:/main.qml:1544 Type WizardMain unavailable
qrc:/wizard/WizardMain.qml:264 Type WizardWelcome unavailable
qrc:/wizard/WizardWelcome.qml:30 module "QtQuick.XmlListModel" is not installed

2019-03-26 23:34:06.665	    7f69f527cc40	ERROR	frontend	src/wallet/api/wallet.cpp:371	Error: no root objects
```

**Comment by rnhmjoj** [comment]
It works for me: it must be picking it up somewhere in my PATH.
I'll check forr other missing dependencies.

**Comment by rnhmjoj** [comment]
Ok, done. It now seems to run in a clean environment.

**Comment by rnhmjoj** [comment]
Thank you!

**Pull request merged**
