### PR TITLE
stm32cubemx: 5.3.0 -> 5.6.1

### PR DESCRIPTION
**Pull request by dramaturg**
###### Motivation for this change

Upgrade a package to latest release

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wucke13** [comment]
LGTM, but I did not test.

**Comment by dramaturg** [comment]
> LGTM, but I did not test.

@wucke13 I ran it and walked through a small timing setup. No issues with that.

Can you mark the PR as reviewed then?

**Review by wucke13 — APPROVED** [review]

**Comment by justin-gerhardt** [comment]
Why are the manual build steps necessary? The [Arch AUR version](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=stm32cubemx) of this package uses a version derived url from ST.
I've created my own version of the update using that url and everything seems to work fine.
2370ca0b26983762b5fd71ea041d4b205836ca1b

**Comment by dramaturg** [comment]
My best guess is @wucke13 did it this way because when downloading this you have to accept a license agreement.
Some nix packages require a license agreement flag to be set - could we do the same here?

**Comment by justin-gerhardt** [comment]
The license provided with the zip does generally permit redistribution, so ST is presumably fine with people not going though the license/auth flow. My guess would be @wucke13 wasn't aware the package could be downloaded without signing in and therefore made the process manual.

**Comment by wucke13** [comment]
@justin-gerhardt Exactly, I wasn't aware. Would you like to make a PR with your changes? It sounds promising not having to download stuff manually.

**Pull request closed without merging**
