### PR TITLE
octave: build with gl2ps

### LINKED ISSUE #38459: octave: abort when printing figure to pdf
## Issue description
When saving a plot figure to pdf in Octave, the program panics and aborts

### Steps to reproduce
```
$ octave --no-gui
octave:1> t = linspace(0,1);
octave:2> x = power(abs(t), 1/3);
octave:3> plot(t,x);
octave:4> print -dpdf output.pdf
warning: print.m: epstool binary is not available.
Some output formats are not available.
warning: called from
    __print_parse_opts__ at line 385 column 9
    print at line 315 column 8
error: gl2ps_print: support for gl2ps was unavailable or disabled when Octave was built
terminate called after throwing an instance of 'octave::execution_exception'
panic: Aborted -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
[1]    14326 abort      octave --no-gui
```
Reproducible with both `octave` and `octaveFull` from `nixos-unstable`. If the GUI is used, the program exits with signal 6.

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 17.09.2873.4c3c0e824aa (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2873.4c3c0e824aa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

### PR DESCRIPTION
**Pull request by tmplt**
###### Motivation for this change
Resolves #38459

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @raskin

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build octave octaveFull

**Comment by Tmplt** [comment]
Is anything blocking this PR or can it be merged?

**Comment by 7c6f434c** [comment]
As is it seems to make `octave` marked as broken. Am I missing something in the ofBorg report?

**Comment by tmplt** [comment]
On 20-10-2019 22:41, Michael Raskin wrote:
>Am I missing something in the ofBorg report?
Am I? @GrahamcOfBorg reports all checks passed.

**Comment by 7c6f434c** [comment]
@tmplt Expand the list — there are three neutral checks, and if you look into details, you see that the attributes are not built because the evaluation complains there is a broken dependency.

**Comment by tmplt** [comment]
On 21-10-2019 12:33, Michael Raskin wrote:
>there are three neutral checks, and if you look into details, you see that the attributes are not built because the evaluation complains there is a broken dependency.
I see that now, but I can't get the bot's web interface to show the full
log. Has it expired?

**Comment by 7c6f434c** [comment]
>On 21-10-2019 12:33, Michael Raskin wrote:
>>there are three neutral checks, and if you look into details, you see that the attributes are not built because the evaluation complains there is a broken dependency.
>I see that now, but I can't get the bot's web interface to show the full
>log. Has it expired?

Hm, probably

**Comment by tmplt** [comment]
Can someone command a retry so that I can check the logs before they
expire?

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build octave octaveFull

**Comment by tmplt** [comment]
Jotting down for later: darwin fails because qt4 is no longer supported on that platform; I don't get why aarch64 fails with `Package ‘octave-5.1.0’ in [...] is not supported on ‘aarch64-linux’, refusing to evaluate.`, because `platforms = linux ++ darwin`.

**Comment by 7c6f434c** [comment]
@ofborg build build octave octaveFull

**Pull request merged**
