### PR TITLE
frab: 2016-12-28 -> 2019-03-22

### PR DESCRIPTION
**Pull request by manveru**
###### Motivation for this change

This has been marked broken for too long.

I went ahead and refactored the service a bit to current ruby standards.
Also added a test that should make sure future breakage is found earlier and I can notice when it happens.

I don't personally use frab, but I also can't stand broken ruby apps in nixpkgs, so I'd appreciate if someone who wants to use it could give it a quick test-drive.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by manveru** [comment]
Also, pinging @fpletz since he did the initial package.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build frab

**Comment by 0x4A6F** [comment]
@manveru Please rebase.

**Comment by Mic92** [comment]
We decided to remove this package https://github.com/NixOS/nixpkgs/pull/106601

**Pull request closed without merging**
