### PR TITLE
edk2: 201911 -> 202011

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105582` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>OVMF</li>
    <li>OVMF-CSM</li>
    <li>OVMF-secureBoot</li>
    <li>edk2</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105582` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>OVMF-CSM</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>OVMF</li>
    <li>OVMF-secureBoot</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>edk2</li>
  </ul>
</details>

OVMF*:

```
clang-9: error: argument unused during compilation: '-nostdlibinc' [-Werror,-Wunused-command-line-argument]
clang-9: error: argument unused during compilation: '-nostdlibinc' [-Werror,-Wunused-command-line-argument]
make: *** [GNUmakefile:346: /private/tmp/nix-build-OVMF-202011.drv-0/edk2/Build/OvmfX64/RELEASE_CLANGPDB/X64/MdePkg/Library/BasePerformanceLibNull/BasePerformanceLibNull/OUTPUT/PerformanceLib.obj] Error 1
make: *** [GNUmakefile:346: /private/tmp/nix-build-OVMF-202011.drv-0/edk2/Build/OvmfX64/RELEASE_CLANGPDB/X64/MdePkg/Library/UefiDriverEntryPoint/UefiDriverEntryPoint/OUTPUT/DriverEntryPoint.obj] Error 1
clang-9: error: argument unused during compilation: '-nostdlibinc' [-Werror,-Wunused-command-line-argument]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/private/tmp/nix-build-OVMF-202011.drv-0/edk2/Build/OvmfX64/RELEASE_CLANGPDB/X64/MdePkg/Library/BasePerformanceLibNull/BasePerformanceLibNull]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/private/tmp/nix-build-OVMF-202011.drv-0/edk2/Build/OvmfX64/RELEASE_CLANGPDB/X64/MdeModulePkg/Library/UefiBootManagerLib/UefiBootManagerLib]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/private/tmp/nix-build-OVMF-202011.drv-0/edk2/Build/OvmfX64/RELEASE_CLANGPDB/X64/MdePkg/Library/UefiDriverEntryPoint/UefiDriverEntryPoint]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/private/tmp/nix-build-OVMF-202011.drv-0/edk2/Build/OvmfX64/RELEASE_CLANGPDB/X64/MdePkg/Library/BasePeCoffGetEntryPointLib/BasePeCoffGetEntryPointLib]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/private/tmp/nix-build-OVMF-202011.drv-0/edk2/Build/OvmfX64/RELEASE_CLANGPDB/X64/MdePkg/Library/DxeServicesTableLib/DxeServicesTableLib]


build.py...
 : error F002: Failed to build module
        /private/tmp/nix-build-OVMF-202011.drv-0/edk2/MdePkg/Library/BasePerformanceLibNull/BasePerformanceLibNull.inf [X64, CLANGPDB, RELEASE]

- Failed -
Build end time: 16:18:52, Dec.01 2020
Build total time: 00:00:10
```

**Comment by petabyteboy** [comment]
Thanks! Can you test if the previous version built fine on darwin?

**Review by arcnmx — APPROVED** [review]
> Built OVMF.fd and booted something with it in qemu

looks good here too

**Comment by petabyteboy** [comment]
Seems like darwin was already broken: https://hydra.nixos.org/build/128912603

**Pull request merged**
