### PR TITLE
llvm7

### LINKED ISSUE #46805: Package LLVM 7
Gotta cache 'em all 😁

A big benefit is that it finally includes a fully functional `dsymutil` for Darwin. I might even be tempted to make it the default and skip 6.

### PR DESCRIPTION
**Pull request by dtzWill**
Patches for darwin and musl need fixing,
and of course general testing :).

Fixes #46805.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
This can all be squashed :).

**Comment by dtzWill** [comment]
Also fixes #46854 .

**Comment by dtzWill** [comment]
Fixing hashes shortly...

**Comment by andrewrk** [comment]
Thanks for being on top of this, @dtzWill!

**Comment by dtzWill** [comment]
FWIW, I think mostly this needs a Darwin tester, possibly someone to fixup the codesign patch but that might be something "anyone" can do.

That said, having any actual in-tree users might help determine if things work or not :).

**Review by LnL7 — COMMENTED** [review]
The darwin clang build fails with

```
Scanning dependencies of target clangd
[ 98%] Building CXX object tools/extra/clangd/tool/CMakeFiles/clangd.dir/ClangdMain.cpp.o
[100%] Linking CXX executable ../../../../bin/clangd
ld: library not found for -latomic
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/extra/clangd/tool/CMakeFiles/clangd.dir/build.make:109: bin/clangd] Error 1
make[1]: *** [CMakeFiles/Makefile2:8044: tools/extra/clangd/tool/CMakeFiles/clangd.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by dtzWill** [comment]
Err :/. No idea why that'd be happening, don't suppose that's a "add darwin.libatomic as buildInput" sort of thing? Wishful thinking :).

Rough that it happened at 98% hehe.

Don't mean to be useless but not sure what to suggest for that.
* Maybe disable clangd? :/
* Determine why libatomic isnt available (or why searched for if atomics are provided under a different lib name)?

I think compiler-rt has atomics, so maybe that's not being found or plumbed in properly...?

Thanks for giving it a go, sorry about the result!

**Comment by dtzWill** [comment]
Possibly relevant: https://github.com/llvm-mirror/compiler-rt/commit/e8b47a537f4c849e66e450dadddfbfe03d1f06fd ?

May be useful to compare logs and build results against 6....

**Comment by orivej** [comment]
`libatomic` is a gcc library. Clang default is to be built to use it on Linux, and to be built with `compiler-rt` on other OSes. This is configurable with CMake option `CLANG_DEFAULT_RTLIB` at build time, and with the command line argument `-rtlib` at run time.

**Comment by LnL7** [comment]
@dtzWill I've use clangd, so I'd prefer to keep it 😄. But I didn't spend any time on it yet, could be easy to fox.

**Comment by dtzWill** [comment]
Fwiw using mess built with this currently, nothing exploded yet ;).

Might end up merging without Darwin support, let that get handled when someone with ability and interest finds it worth investigating.  I expect it to be relatively simple TBH, but I'm excited for llvm7 goodness on master in the meantime :D.

**Comment by andrewrk** [comment]
> Might end up merging without Darwin support

no complaints here; I have no use case for darwin support of llvm7 and I'm sure someone who does can pick up the work from here.

**Comment by dtzWill** [comment]
@GrahamcOfBorg build llvm_7

**Comment by dtzWill** [comment]
I've been using mesa built with this-- so other than Darwin touchups I think this is good-to-go.

Nothing depends on this yet, so merging so folks can test and projects can give it a try :).

Apologies for any issues, can't promise I can fix them but please cc me if you encounter anything looking like a packaging problem.  Thanks!

**Pull request merged**
