### PR TITLE
linux_latest: 5.13.13 -> 5.14

### PR DESCRIPTION
**Pull request by alyssais**
I will be doing some further work to update some out-of-tree modules, etc., but will not be blocking this PR for anything out-of-tree.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xaverdh** [comment]
Note this will cause a merge conflict with staging-next either there or in this pr, depending on timing (not a huge issue though)

**Comment by fabianhjr** [comment]
Built and booted, for nvidia proprietary driver users an upgrade is required to 470.63.01 available in NixOS/nixpkgs#136205

**Review by NeQuissimus — APPROVED** [review]

**Review by Atemu — CHANGES_REQUESTED** [review]
Please mark newly failing modules as broken on this version.

**Comment by Atemu** [comment]
Result of `nixpkgs-review pr 136150` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>196 packages marked as broken and skipped:</summary>
  <ul>
    <li>linux-libre</li>
    <li>linuxPackages-libre.acpi_call</li>
    <li>linuxPackages-libre.akvcam</li>
    <li>linuxPackages-libre.amdgpu-pro</li>
    <li>linuxPackages-libre.anbox</li>
    <li>linuxPackages-libre.apfs</li>
    <li>linuxPackages-libre.asus-wmi-sensors</li>
    <li>linuxPackages-libre.batman_adv</li>
    <li>linuxPackages-libre.bbswitch</li>
    <li>linuxPackages-libre.bcc</li>
    <li>linuxPackages-libre.bpftrace</li>
    <li>linuxPackages-libre.broadcom_sta</li>
    <li>linuxPackages-libre.can-isotp</li>
    <li>linuxPackages-libre.chipsec</li>
    <li>linuxPackages-libre.cryptodev</li>
    <li>linuxPackages-libre.ddcci-driver</li>
    <li>linuxPackages-libre.digimend</li>
    <li>linuxPackages-libre.dpdk-kmods</li>
    <li>linuxPackages-libre.ena</li>
    <li>linuxPackages-libre.evdi</li>
    <li>linuxPackages-libre.facetimehd</li>
    <li>linuxPackages-libre.fwts-efi-runtime</li>
    <li>linuxPackages-libre.gcadapter-oc-kmod</li>
    <li>linuxPackages-libre.hid-nintendo</li>
    <li>linuxPackages-libre.isgx</li>
    <li>linuxPackages-libre.it87</li>
    <li>linuxPackages-libre.ixgbevf</li>
    <li>linuxPackages-libre.jool</li>
    <li>linuxPackages-libre.kernel</li>
    <li>linuxPackages-libre.kvmfr</li>
    <li>linuxPackages-libre.lttng-modules</li>
    <li>linuxPackages-libre.mba6x_bl</li>
    <li>linuxPackages-libre.mbp2018-bridge-drv</li>
    <li>linuxPackages-libre.mwprocapture</li>
    <li>linuxPackages-libre.mxu11x0</li>
    <li>linuxPackages-libre.ndiswrapper</li>
    <li>linuxPackages-libre.netatop</li>
    <li>linuxPackages-libre.nvidia_x11</li>
    <li>linuxPackages-libre.nvidia_x11_beta</li>
    <li>linuxPackages-libre.nvidia_x11_legacy340</li>
    <li>linuxPackages-libre.nvidia_x11_legacy390</li>
    <li>linuxPackages-libre.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages-libre.nvidiabl</li>
    <li>linuxPackages-libre.oci-seccomp-bpf-hook</li>
    <li>linuxPackages-libre.openafs</li>
    <li>linuxPackages-libre.openafs_1_8</li>
    <li>linuxPackages-libre.openafs_1_9</li>
    <li>linuxPackages-libre.openrazer</li>
    <li>linuxPackages-libre.phc-intel</li>
    <li>linuxPackages-libre.r8125</li>
    <li>linuxPackages-libre.r8168</li>
    <li>linuxPackages-libre.rtl8188eus-aircrack</li>
    <li>linuxPackages-libre.rtl8192eu</li>
    <li>linuxPackages-libre.rtl8723bs</li>
    <li>linuxPackages-libre.rtl8812au</li>
    <li>linuxPackages-libre.rtl8814au</li>
    <li>linuxPackages-libre.rtl8821au</li>
    <li>linuxPackages-libre.rtl8821ce</li>
    <li>linuxPackages-libre.rtl8821cu</li>
    <li>linuxPackages-libre.rtl88x2bu</li>
    <li>linuxPackages-libre.rtl88xxau-aircrack</li>
    <li>linuxPackages-libre.rtlwifi_new</li>
    <li>linuxPackages-libre.rtw88</li>
    <li>linuxPackages-libre.rtw89</li>
    <li>linuxPackages-libre.sch_cake</li>
    <li>linuxPackages-libre.sysdig</li>
    <li>linuxPackages-libre.system76</li>
    <li>linuxPackages-libre.system76-acpi</li>
    <li>linuxPackages-libre.system76-io</li>
    <li>linuxPackages-libre.systemtap</li>
    <li>linuxPackages-libre.tbs</li>
    <li>linuxPackages-libre.tp_smapi</li>
    <li>linuxPackages-libre.tuxedo-keyboard</li>
    <li>linuxPackages-libre.v4l2loopback</li>
    <li>linuxPackages-libre.v86d</li>
    <li>linuxPackages-libre.veikk-linux-driver</li>
    <li>linuxPackages-libre.vendor-reset</li>
    <li>linuxPackages-libre.vhba</li>
    <li>linuxPackages-libre.virtualbox</li>
    <li>linuxPackages-libre.virtualboxGuestAdditions</li>
    <li>linuxPackages-libre.xmm7360-pci</li>
    <li>linuxPackages-libre.xpadneo</li>
    <li>linuxPackages-libre.zenpower</li>
    <li>linuxPackages-libre.zfs</li>
    <li>linuxPackages-libre.zfsStable</li>
    <li>linuxPackages-libre.zfsUnstable</li>
    <li>linuxPackages_5_14.anbox</li>
    <li>linuxPackages_5_14.ixgbevf</li>
    <li>linuxPackages_5_14.mxu11x0</li>
    <li>linuxPackages_5_14.ndiswrapper</li>
    <li>linuxPackages_5_14.phc-intel</li>
    <li>linuxPackages_5_14.r8125</li>
    <li>linuxPackages_5_14.rtl8723bs</li>
    <li>linuxPackages_5_14.sch_cake</li>
    <li>linuxPackages_5_14.tbs</li>
    <li>linuxPackages_5_14.zfs</li>
    <li>linuxPackages_5_14.zfsStable</li>
    <li>linuxPackages_5_14.zfsUnstable</li>
    <li>linuxPackages_latest-libre.acpi_call</li>
    <li>linuxPackages_latest-libre.akvcam</li>
    <li>linuxPackages_latest-libre.amdgpu-pro</li>
    <li>linuxPackages_latest-libre.anbox</li>
    <li>linuxPackages_latest-libre.apfs</li>
    <li>linuxPackages_latest-libre.asus-wmi-sensors</li>
    <li>linuxPackages_latest-libre.batman_adv</li>
    <li>linuxPackages_latest-libre.bbswitch</li>
    <li>linuxPackages_latest-libre.bcc</li>
    <li>linuxPackages_latest-libre.bpftrace</li>
    <li>linuxPackages_latest-libre.broadcom_sta</li>
    <li>linuxPackages_latest-libre.can-isotp</li>
    <li>linuxPackages_latest-libre.chipsec</li>
    <li>linuxPackages_latest-libre.cryptodev</li>
    <li>linuxPackages_latest-libre.ddcci-driver</li>
    <li>linuxPackages_latest-libre.digimend</li>
    <li>linuxPackages_latest-libre.dpdk-kmods</li>
    <li>linuxPackages_latest-libre.ena</li>
    <li>linuxPackages_latest-libre.evdi</li>
    <li>linuxPackages_latest-libre.facetimehd</li>
    <li>linuxPackages_latest-libre.fwts-efi-runtime</li>
    <li>linuxPackages_latest-libre.gcadapter-oc-kmod</li>
    <li>linuxPackages_latest-libre.hid-nintendo</li>
    <li>linuxPackages_latest-libre.isgx</li>
    <li>linuxPackages_latest-libre.it87</li>
    <li>linuxPackages_latest-libre.ixgbevf</li>
    <li>linuxPackages_latest-libre.jool</li>
    <li>linuxPackages_latest-libre.kernel</li>
    <li>linuxPackages_latest-libre.kvmfr</li>
    <li>linuxPackages_latest-libre.lttng-modules</li>
    <li>linuxPackages_latest-libre.mba6x_bl</li>
    <li>linuxPackages_latest-libre.mbp2018-bridge-drv</li>
    <li>linuxPackages_latest-libre.mwprocapture</li>
    <li>linuxPackages_latest-libre.mxu11x0</li>
    <li>linuxPackages_latest-libre.ndiswrapper</li>
    <li>linuxPackages_latest-libre.netatop</li>
    <li>linuxPackages_latest-libre.nvidia_x11</li>
    <li>linuxPackages_latest-libre.nvidia_x11_beta</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy340</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy390</li>
    <li>linuxPackages_latest-libre.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_latest-libre.nvidiabl</li>
    <li>linuxPackages_latest-libre.oci-seccomp-bpf-hook</li>
    <li>linuxPackages_latest-libre.openafs</li>
    <li>linuxPackages_latest-libre.openafs_1_8</li>
    <li>linuxPackages_latest-libre.openafs_1_9</li>
    <li>linuxPackages_latest-libre.openrazer</li>
    <li>linuxPackages_latest-libre.phc-intel</li>
    <li>linuxPackages_latest-libre.r8125</li>
    <li>linuxPackages_latest-libre.r8168</li>
    <li>linuxPackages_latest-libre.rtl8188eus-aircrack</li>
    <li>linuxPackages_latest-libre.rtl8192eu</li>
    <li>linuxPackages_latest-libre.rtl8723bs</li>
    <li>linuxPackages_latest-libre.rtl8812au</li>
    <li>linuxPackages_latest-libre.rtl8814au</li>
    <li>linuxPackages_latest-libre.rtl8821au</li>
    <li>linuxPackages_latest-libre.rtl8821ce</li>
    <li>linuxPackages_latest-libre.rtl8821cu</li>
    <li>linuxPackages_latest-libre.rtl88x2bu</li>
    <li>linuxPackages_latest-libre.rtl88xxau-aircrack</li>
    <li>linuxPackages_latest-libre.rtlwifi_new</li>
    <li>linuxPackages_latest-libre.rtw88</li>
    <li>linuxPackages_latest-libre.rtw89</li>
    <li>linuxPackages_latest-libre.sch_cake</li>
    <li>linuxPackages_latest-libre.sysdig</li>
    <li>linuxPackages_latest-libre.system76</li>
    <li>linuxPackages_latest-libre.system76-acpi</li>
    <li>linuxPackages_latest-libre.system76-io</li>
    <li>linuxPackages_latest-libre.systemtap</li>
    <li>linuxPackages_latest-libre.tbs</li>
    <li>linuxPackages_latest-libre.tp_smapi</li>
    <li>linuxPackages_latest-libre.tuxedo-keyboard</li>
    <li>linuxPackages_latest-libre.v4l2loopback</li>
    <li>linuxPackages_latest-libre.v86d</li>
    <li>linuxPackages_latest-libre.veikk-linux-driver</li>
    <li>linuxPackages_latest-libre.vendor-reset</li>
    <li>linuxPackages_latest-libre.vhba</li>
    <li>linuxPackages_latest-libre.virtualbox</li>
    <li>linuxPackages_latest-libre.virtualboxGuestAdditions</li>
    <li>linuxPackages_latest-libre.xmm7360-pci</li>
    <li>linuxPackages_latest-libre.xpadneo</li>
    <li>linuxPackages_latest-libre.zenpower</li>
    <li>linuxPackages_latest-libre.zfs</li>
    <li>linuxPackages_latest-libre.zfsStable</li>
    <li>linuxPackages_latest-libre.zfsUnstable</li>
    <li>linuxPackages_latest.anbox</li>
    <li>linuxPackages_latest.ixgbevf</li>
    <li>linuxPackages_latest.mxu11x0</li>
    <li>linuxPackages_latest.ndiswrapper</li>
    <li>linuxPackages_latest.phc-intel</li>
    <li>linuxPackages_latest.r8125</li>
    <li>linuxPackages_latest.rtl8723bs</li>
    <li>linuxPackages_latest.sch_cake</li>
    <li>linuxPackages_latest.tbs</li>
    <li>linuxPackages_latest.zfs</li>
    <li>linuxPackages_latest.zfsStable</li>
    <li>linuxPackages_latest.zfsUnstable</li>
    <li>linux_latest-libre</li>
  </ul>
</details>
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_5_14.amdgpu-pro (linuxPackages_latest.amdgpu-pro)</li>
    <li>linuxPackages_5_14.nvidia_x11 (linuxPackages_latest.nvidia_x11)</li>
    <li>linuxPackages_5_14.nvidia_x11_beta (linuxPackages_latest.nvidia_x11_beta)</li>
    <li>linuxPackages_5_14.nvidia_x11_legacy340 (linuxPackages_latest.nvidia_x11_legacy340)</li>
    <li>linuxPackages_5_14.nvidia_x11_legacy390 (linuxPackages_latest.nvidia_x11_legacy390)</li>
    <li>linuxPackages_5_14.nvidia_x11_vulkan_beta (linuxPackages_latest.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_5_14.rtw88 (linuxPackages_5_14.rtlwifi_new ,linuxPackages_latest.rtlwifi_new ,linuxPackages_latest.rtw88)</li>
    <li>linuxPackages_5_14.virtualboxGuestAdditions (linuxPackages_latest.virtualboxGuestAdditions)</li>
    <li>linuxPackages_5_14.xmm7360-pci (linuxPackages_latest.xmm7360-pci)</li>
  </ul>
</details>
<details>
  <summary>94 packages built:</summary>
  <ul>
    <li>bpftools</li>
    <li>linuxPackages-libre.cpupower</li>
    <li>linuxPackages-libre.hyperv-daemons</li>
    <li>linuxPackages-libre.intel-speed-select</li>
    <li>linuxPackages-libre.perf</li>
    <li>linuxPackages-libre.ply</li>
    <li>linuxPackages-libre.tmon</li>
    <li>linuxPackages-libre.turbostat</li>
    <li>linuxPackages-libre.usbip</li>
    <li>linuxPackages-libre.x86_energy_perf_policy</li>
    <li>linuxPackages_5_14.acpi_call (linuxPackages_latest.acpi_call)</li>
    <li>linuxPackages_5_14.akvcam (linuxPackages_latest.akvcam)</li>
    <li>linuxPackages_5_14.apfs (linuxPackages_latest.apfs)</li>
    <li>linuxPackages_5_14.asus-wmi-sensors (linuxPackages_latest.asus-wmi-sensors)</li>
    <li>linuxPackages_5_14.batman_adv (linuxPackages_latest.batman_adv)</li>
    <li>linuxPackages_5_14.bbswitch (linuxPackages_latest.bbswitch)</li>
    <li>linuxPackages_5_14.bcc (linuxPackages_latest.bcc)</li>
    <li>linuxPackages_5_14.bpftrace (linuxPackages_latest.bpftrace)</li>
    <li>linuxPackages_5_14.broadcom_sta (linuxPackages_latest.broadcom_sta)</li>
    <li>linuxPackages_5_14.can-isotp (linuxPackages_latest.can-isotp)</li>
    <li>linuxPackages_5_14.chipsec (linuxPackages_latest.chipsec)</li>
    <li>linuxPackages_5_14.cpupower (linuxPackages_latest.cpupower)</li>
    <li>linuxPackages_5_14.cryptodev (linuxPackages_latest.cryptodev)</li>
    <li>linuxPackages_5_14.ddcci-driver (linuxPackages_latest.ddcci-driver)</li>
    <li>linuxPackages_5_14.digimend (linuxPackages_latest.digimend)</li>
    <li>linuxPackages_5_14.dpdk-kmods (linuxPackages_latest.dpdk-kmods)</li>
    <li>linuxPackages_5_14.ena (linuxPackages_latest.ena)</li>
    <li>linuxPackages_5_14.evdi (linuxPackages_latest.evdi)</li>
    <li>linuxPackages_5_14.facetimehd (linuxPackages_latest.facetimehd)</li>
    <li>linuxPackages_5_14.fwts-efi-runtime (linuxPackages_latest.fwts-efi-runtime)</li>
    <li>linuxPackages_5_14.gcadapter-oc-kmod (linuxPackages_latest.gcadapter-oc-kmod)</li>
    <li>linuxPackages_5_14.hid-nintendo (linuxPackages_latest.hid-nintendo)</li>
    <li>linuxPackages_5_14.hyperv-daemons (linuxPackages_latest.hyperv-daemons)</li>
    <li>linuxPackages_5_14.intel-speed-select (linuxPackages_latest.intel-speed-select)</li>
    <li>linuxPackages_5_14.isgx (linuxPackages_latest.isgx)</li>
    <li>linuxPackages_5_14.it87 (linuxPackages_latest.it87)</li>
    <li>linuxPackages_5_14.jool (linuxPackages_latest.jool)</li>
    <li>linux_5_14 (linuxPackages_5_14.kernel ,linux_latest)</li>
    <li>linuxPackages_5_14.kvmfr (linuxPackages_latest.kvmfr)</li>
    <li>linuxPackages_5_14.lttng-modules (linuxPackages_latest.lttng-modules)</li>
    <li>linuxPackages_5_14.mba6x_bl (linuxPackages_latest.mba6x_bl)</li>
    <li>linuxPackages_5_14.mbp2018-bridge-drv (linuxPackages_latest.mbp2018-bridge-drv)</li>
    <li>linuxPackages_5_14.mwprocapture (linuxPackages_latest.mwprocapture)</li>
    <li>linuxPackages_5_14.netatop (linuxPackages_latest.netatop)</li>
    <li>linuxPackages_5_14.nvidiabl (linuxPackages_latest.nvidiabl)</li>
    <li>linuxPackages_5_14.oci-seccomp-bpf-hook (linuxPackages_latest.oci-seccomp-bpf-hook)</li>
    <li>linuxPackages_5_14.odp-dpdk</li>
    <li>linuxPackages_5_14.openafs (linuxPackages_5_14.openafs_1_8 ,linuxPackages_latest.openafs ,linuxPackages_latest.openafs_1_8)</li>
    <li>linuxPackages_5_14.openafs_1_9 (linuxPackages_latest.openafs_1_9)</li>
    <li>linuxPackages_5_14.openrazer (linuxPackages_latest.openrazer)</li>
    <li>linuxPackages_5_14.perf (linuxPackages_latest.perf)</li>
    <li>linuxPackages_5_14.pktgen</li>
    <li>linuxPackages_5_14.ply (linuxPackages_latest.ply)</li>
    <li>linuxPackages_5_14.r8168 (linuxPackages_latest.r8168)</li>
    <li>linuxPackages_5_14.rtl8188eus-aircrack (linuxPackages_latest.rtl8188eus-aircrack)</li>
    <li>linuxPackages_5_14.rtl8192eu (linuxPackages_latest.rtl8192eu)</li>
    <li>linuxPackages_5_14.rtl8812au (linuxPackages_latest.rtl8812au)</li>
    <li>linuxPackages_5_14.rtl8814au (linuxPackages_latest.rtl8814au)</li>
    <li>linuxPackages_5_14.rtl8821au (linuxPackages_latest.rtl8821au)</li>
    <li>linuxPackages_5_14.rtl8821ce (linuxPackages_latest.rtl8821ce)</li>
    <li>linuxPackages_5_14.rtl8821cu (linuxPackages_latest.rtl8821cu)</li>
    <li>linuxPackages_5_14.rtl88x2bu (linuxPackages_latest.rtl88x2bu)</li>
    <li>linuxPackages_5_14.rtl88xxau-aircrack (linuxPackages_latest.rtl88xxau-aircrack)</li>
    <li>linuxPackages_5_14.rtw89 (linuxPackages_latest.rtw89)</li>
    <li>linuxPackages_5_14.stdenv</li>
    <li>linuxPackages_5_14.sysdig (linuxPackages_latest.sysdig)</li>
    <li>linuxPackages_5_14.system76 (linuxPackages_latest.system76)</li>
    <li>linuxPackages_5_14.system76-acpi (linuxPackages_latest.system76-acpi)</li>
    <li>linuxPackages_5_14.system76-io (linuxPackages_latest.system76-io)</li>
    <li>linuxPackages_5_14.system76-power</li>
    <li>linuxPackages_5_14.systemtap (linuxPackages_latest.systemtap)</li>
    <li>linuxPackages_5_14.tmon (linuxPackages_latest.tmon)</li>
    <li>linuxPackages_5_14.tp_smapi (linuxPackages_latest.tp_smapi)</li>
    <li>linuxPackages_5_14.turbostat (linuxPackages_latest.turbostat)</li>
    <li>linuxPackages_5_14.tuxedo-keyboard (linuxPackages_latest.tuxedo-keyboard)</li>
    <li>linuxPackages_5_14.usbip (linuxPackages_latest.usbip)</li>
    <li>linuxPackages_5_14.v4l2loopback (linuxPackages_latest.v4l2loopback)</li>
    <li>linuxPackages_5_14.v86d (linuxPackages_latest.v86d)</li>
    <li>linuxPackages_5_14.veikk-linux-driver (linuxPackages_latest.veikk-linux-driver)</li>
    <li>linuxPackages_5_14.vendor-reset (linuxPackages_latest.vendor-reset)</li>
    <li>linuxPackages_5_14.vhba (linuxPackages_latest.vhba)</li>
    <li>linuxPackages_5_14.virtualbox (linuxPackages_latest.virtualbox)</li>
    <li>linuxPackages_5_14.x86_energy_perf_policy (linuxPackages_latest.x86_energy_perf_policy)</li>
    <li>linuxPackages_5_14.xpadneo (linuxPackages_latest.xpadneo)</li>
    <li>linuxPackages_5_14.zenpower (linuxPackages_latest.zenpower)</li>
    <li>linuxPackages_latest-libre.cpupower</li>
    <li>linuxPackages_latest-libre.hyperv-daemons</li>
    <li>linuxPackages_latest-libre.intel-speed-select</li>
    <li>linuxPackages_latest-libre.perf</li>
    <li>linuxPackages_latest-libre.ply</li>
    <li>linuxPackages_latest-libre.tmon</li>
    <li>linuxPackages_latest-libre.turbostat</li>
    <li>linuxPackages_latest-libre.usbip</li>
    <li>linuxPackages_latest-libre.x86_energy_perf_policy</li>
  </ul>
</details>

These 9, especially the nvidia one. There are lots of nvidia users on _latest and an eval-time error is preferrable here.

**Comment by fabianhjr** [comment]
Hey @Atemu, nvidia does build on 5.14 with a more recent version which is already available and merge pending: #136205

**Comment by Atemu** [comment]
The nvidia drv should declare that fact in its `meta.broken`.

**Comment by alyssais** [comment]
I had https://github.com/NixOS/nixpkgs/pull/136171 open to mark some modules incompatible.  I only tested free modules though — I think it can be left to users of the proprietary modules to maintain those expressions.

**Pull request merged**
