### PR TITLE
haskellPackages: fix `regenerate-hackage-packages.sh`, and `Cabal_3_12_1_0`

### PR DESCRIPTION
**Pull request by peterbecich**
## Description of changes

Fix `./maintainers/scripts/haskell/regenerate-hackage-packages.sh`
and some additions for Cabal and Cabal-syntax 3.12

This also fixes `Cabal`; this succeeds:
```
nix build .#haskellPackages.Cabal_3_12_1_0
```

Hackage index not updated.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by peterbecich** [comment]
Guessing, this might be fixed by removing 
https://github.com/NixOS/nixpkgs/blob/af5b395b5ca41c51269ec3b6a1d5f53374c2fa02/pkgs/development/haskell-modules/configuration-hackage2nix/stackage.yaml#L789

Then `crypton-connection_0_4_1` will be replaced with `crypton_connection`.

**Comment by peterbecich** [comment]
Is `ofborg-eval` dependent on `crypton-connection` 0.4.0?
https://gist.github.com/GrahamcOfBorg/2f560c707f1b1eb8bdbf618129f362ef#file-output-path-comparison-L145-L146

**Comment by turion** [comment]
I'm maybe misunderstanding, but it seems like this PR doesn't touch `./maintainers/scripts/haskell/regenerate-hackage-packages.sh` at all?

**Comment by maralorn** [comment]
The problem is, that that script does not work if there are to heinous eval errors. (Not sure which are a problem and which aren’t. :D )

**Comment by peterbecich** [comment]
On this line of the `ofborg-eval` output https://gist.github.com/GrahamcOfBorg/2f560c707f1b1eb8bdbf618129f362ef#file-output-path-comparison-L145-L147 it refers to `crypton-connection_0_4_0`.

However, `..._0_4_0` is nowhere in my branch; it's correctly updated to `..._0_4_1`. Is this error referring to a different repository?

**Comment by maralorn** [comment]
Well the message says "The branch this PR will merge in to does not cleanly evaluate"

**Comment by peterbecich** [comment]
@turion you're correct, I meant that I modified other files and `regenerate-hackage-packages.sh` succeeds now. Right now on `haskell-updates`, `./maintainers/scripts/haskell/regenerate-hackage-packages.sh` fails to complete.

**Comment by peterbecich** [comment]
@maralorn is it possible to run `ofborg-eval` locally so I can investigate further?

**Comment by maralorn** [comment]
@peterbecich I don’t know. It doesn’t matter. It’s not a blocker on merging this. This PR trys to fix evaluation. Would be stupid not merge it because the branch it is supposed to merge into does not evaluate cleanly.

**Comment by sternenseemann** [comment]
Has been addressed, thanks! Note that deviating from Stackage (i.e. deleting constraints in stackage.yaml) is generally not an option.

**Comment by peterbecich** [comment]
@maralorn can we add a CI job that checks 
```
./maintainers/scripts/haskell/regenerate-hackage-packages.sh
```
exits successfully with 0 status?

**Comment by maralorn** [comment]
We have that more or less.

Our CI is hydra. And the eval error which was the problem here appeared in the eval error tab here: https://hydra.nixos.org/jobset/nixpkgs/haskell-updates#tabs-errors

**Comment by peterbecich** [comment]
Please see this issue

> Build failure: haskellPackages.cabal-install on haskell-updates
> https://github.com/NixOS/nixpkgs/issues/328765

**Comment by JohnRTitor** [comment]
> Well the message says "The branch this PR will merge in to does not cleanly evaluate"

This just means that the base branch is broken and you need to rebase your branch.

**Pull request closed without merging**
