### PR TITLE
nixos/release-notes: mention length of release support

### PR DESCRIPTION
**Pull request by vcunat**
I took the date for 19.03 from the announcement:
https://discourse.nixos.org/t/nixos-19-03-release/2652

- [x] Assured whether relevant documentation is up to date

### CODE REVIEW

**Comment by vcunat** [comment]
I suspect the information is difficult to find otherwise.  #61694 might be one instance.

**Review by c0bw3b — APPROVED** [review]

**Review by samueldr — APPROVED** [review]

**Comment by zimbatm** [comment]
Since this needs to be repeated for each release, this needs to be added to the release checklist/template (do we have one?)

**Comment by worldofpeace** [comment]
> Since this needs to be repeated for each release, this needs to be added to the release checklist/template (do we have one?)

I guess that we be somewhere in https://nixos.org/nixos/manual/index.html#ch-releases

**Comment by vcunat** [comment]
AFAIK the practice so far is to copy the last file and remove any non-repeating content :-)

**Pull request merged**
