### PR TITLE
planner: making Gantt and Resource Usage views usable

### PR DESCRIPTION
**Pull request by amiloradovsky**
###### Motivation for this change

Gnome Planner couldn't be used to edit the diagrams, now it can.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

There was an issue, at least on my (stable) system, with the background in Gantt and Resource Usage views.
Due to apparently a bug with some drawing primitives, the background of the views was totally black -- unusable.
Solved by setting the dashed lines' width to 1 (from 0).
Now at least the grid is shown properly -- diagrams are visible.

### CODE REVIEW

**Comment by rasendubi** [comment]
Would you like to submit your patches upstream?

We should limit custom patches in nixpkgs unless they fix security issues or nix-related ones.

**Comment by amiloradovsky** [comment]
The bug appears to be NixOS-specific: about a year ago I installed Planner on Arch and haven't noticed anything similar, yet the patches there seem unrelated to any such issue.

https://www.archlinux.org/packages/community/x86_64/planner/

Earlier I also noticed similar strange behavior with e.g. xsetroot -mod on NixOS, but not on Arch. So it seems to be a low-level drawing, maybe even X11-related, bug specific to NixOS.
Identifying which one exacly would be nice, but until then...

**Comment by amiloradovsky** [comment]
Hah! Just noticed that just changing `line_width` from 0 to 1 solves the problem too:
perhaps somewhere there is devision by zero or something, while the 0 is probably used to mean a default.

**Comment by amiloradovsky** [comment]
Opened a pull request upstream, since it may indeed be worth not just for Nix(OS).

- https://github.com/GNOME/planner/pull/3

**Comment by rasendubi** [comment]
The fact the bug appears on NixOS does not automatically mean it's NixOS-specific. It might be reproducible on other systems as well (just not Arch). NixOS does not have its custom graphic libraries, so the issue does not seem to be NixOS-specific to me.

Furthermore, I've tested planner on both `master` and `release-16.09` branches, and can't reproduce the issue. What's your exact nixpkgs version?

The most probable cause is the wrong version of the underlying dependency, which is best solved by updating this dependency version (if it's not already updated as I don't see the issue).

From [the documentation for `GdkCapStyle`](http://www.manpagez.com/html/gdk2/gdk2-2.24.24/gdk2-Graphics-Contexts.php#GdkCapStyle) I can deduce zero-width lines are perfectly valid:
> GDK_CAP_NOT_LAST
> 
> the same as GDK_CAP_BUTT for lines of non-zero width. for zero width lines, the final point on the line will not be drawn.

I would like to see the response from the planner team as they may shed the light on this.

**Comment by amiloradovsky** [comment]
I agree, "specific" wasn't quite right term. I meant that it seemed to happen due to some conditions which may only exist on Nix OS or something with similar features (multiple versions of packages routinely present on the same system and reachable simultaneously).

The channel was 16.03 with Gnome 3 desktop enabled in the configuration; since Planner didn't exist there yet, it was installed via `nix-env --file <current-nixpkgs> --install planner` -- yes, that's probably not very common setup.
Then I upgraded to 16.09 and installed Planner as usual, and indeed the totally black background disappeared; but I noticed there is no dashed lines anymore... So it probably works just because someone already "redirected" the dashed line-style to the solid one, right in the libraries.

Still, I have few thoughts on this whole situation

- that mix of versions shouldn't cause such a problems (the isolation is not perfect)
- the "stock" version of Planner works without the patches just because dashed lines were disabled altogether in the supporting libraries
- zero-width lines as such aren't a robust concept in CG: these aren't exactly *lines* -- they are *stripes*, but zero-width stripes may indeed be called line *segments*, although it means they must be *invisible*
- just because zero width *can* cause such a problems, even in some rare combinations of versions, it shouldn't be used, especially since one-pixel width is okay and should still behave as intended
- BTW, the fact that the documentation doesn't exclude `0` as an allowed value doesn't yet mean to me that it is "perfectly valid" -- rather that the interface isn't perfect. Here's another "incident" with dashed lines...

http://tex.stackexchange.com/questions/210125/tikz-zero-width-line-with-dashed-line#210126

Now I'm going to close the PR and thank you for your attempts to reproduce the issue.
Gnome Planner team seems to hate GitHub; I don't know, maybe I'll try to ask for their (re)view later.

**Pull request closed without merging**
