### PR TITLE
Update apacheHttpdPackages

### PR DESCRIPTION
**Pull request by anthonyroussel**
## Description of changes

Update all Apache modules.
And add passthru.updateScript when possible.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by anthonyroussel** [comment]
@ofborg build apacheHttpdPackages

**Comment by anthonyroussel** [comment]
@ofborg build apacheHttpdPackages.mod_ca apacheHttpdPackages.mod_crl apacheHttpdPackages.csr apacheHttpdPackages.mod_ocsp apacheHttpdPackages.mod_perl apacheHttpdPackages.mod_pkcs12 apacheHttpdPackages.mod_python apacheHttpdPackages.mod_scep apacheHttpdPackages.mod_spkac apacheHttpdPackages.mod_tile apacheHttpdPackages.mod_timestamp apacheHttpdPackages.mod_dnssd

**Comment by dirkx** [comment]
Redwax side (mod_ca, timestamp, pkcs, etc) all look good, including version bump.

**Review by dirkx — APPROVED** [review]
All good. And branch/build tested

**Comment by anthonyroussel** [comment]
Unfortunately looks like Redwax Apache Modules are no more released on https://redwax.eu/dist/rs/ neither on [Bitbucket server](https://source.redwax.eu/projects/RS/repos/mod_ca/browse) (no Git tags)

For example:

* mod_ca latest version for https://redwax.eu/dist/rs/ is 0.2.3
* mod_ca latest version for Git tags on [Bitbucket](https://source.redwax.eu/projects/RS/repos/mod_ca/browse) is 0.2.3
* but mod_ca latest version on [Bitbucket](https://source.redwax.eu/projects/RS/repos/mod_ca/browse) according to Git history is 0.2.4

So we have to consider these as un-released until a Git tag is pushed for these versions.
It's too difficult to maintain versioning without tags.

**Comment by anthonyroussel** [comment]
Fixed aarch64-darwin build for apacheHttpdPackages.mod_timestamp

**Review by risicle — APPROVED** [review]
Awesome. `nixpkgs-review` reveals no new failures, macos 12 x86_64, nixos x86_64 & aarch64-linux. `nixosTests.mod_perl` passes.

**Pull request merged**
