### PR TITLE
staging-next 2023-09-28

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/255658
- - - 
##### Mass breakages
(will be edited based on progress)
- [x] `nix` and others on darwin: [link below](#issuecomment-1744455146)
- [x] `curl` fallout on darwin
  https://github.com/NixOS/nixpkgs/pull/260378#issuecomment-1761246397
  fixed enough as of 108f00eaae57d8fa66f, I hope.

### CODE REVIEW

**Comment by doronbehar** [comment]
Would it be OK to push here a scipy update @mweinelt ? Or in a separate PR? It's `1.11.2 -> 1.11.3`, shouldn't introduce incompatibilities for dependent packages.

**Comment by vcunat** [comment]
Yes, we're really early into rebuilding, so as usual it will be OK to add more medium-rebuild stuff for a couple days.   (mainly avoid stdenv rebuilds)  But please, don't "over-use" it.

**Comment by doronbehar** [comment]
Sorry for the two commits, I should have tested scipy builds after the naive version update... Now it does.

**Comment by vcunat** [comment]
- [ ] `nix` won't build on `*-darwin` (the default even)
  https://hydra.nixos.org/build/237037805/nixlog/3/tail

**Comment by yu-re-ka** [comment]
borgbackup fails tests on x86_64-linux

**Comment by RaitoBezarius** [comment]
> borgbackup fails tests on x86_64-linux

This is happening on master.

**Comment by vcunat** [comment]
There are still thousands (!) of regressed builds:
https://hydra.nixos.org/eval/1800057?compare=1800043#tabs-now-fail

At a quick glance mostly leaf builds (unusual to have so many), often looking related to python-updates or go upgrade.

**Comment by fabianhjr** [comment]
<details>
<summary>Solving conflict</summary>

```
diff --cc pkgs/development/python-modules/django-redis/default.nix
index 63a3519eb745,4036e345a475..000000000000
--- a/pkgs/development/python-modules/django-redis/default.nix
+++ b/pkgs/development/python-modules/django-redis/default.nix
@@@ -30,8 -30,8 +30,16 @@@ buildPythonPackage 
    src = fetchFromGitHub {
      owner = "jazzband";
      repo = "django-redis";
++<<<<<<< HEAD
 +    rev = "refs/tags/${version}";
 +    hash = "sha256-eX9rUUvpkRrkZ82YalWn8s9DTw6nsbGzi1A6ibRoQGw=";
++||||||| 5103716b448a
++    rev = version;
++    hash = "sha256-eX9rUUvpkRrkZ82YalWn8s9DTw6nsbGzi1A6ibRoQGw=";
++=======
+     rev = version;
+     hash = "sha256-m7z3c7My24vrSSnyfDQ/LlWhy7pV4U0L8LATMvkfczc=";
++>>>>>>> origin/master
    };
  
    postPatch = ''
diff --cc pkgs/development/python-modules/einops/default.nix
index 14e8b5ec9c6d,03c67d7ce527..000000000000
--- a/pkgs/development/python-modules/einops/default.nix
+++ b/pkgs/development/python-modules/einops/default.nix
@@@ -3,12 -3,9 +3,25 @@@
  , chainer
  , fetchFromGitHub
  , hatchling
++<<<<<<< HEAD
 +, jupyter
++||||||| 5103716b448a
++, jupyter
++, keras
++  #, mxnet
++=======
++>>>>>>> origin/master
  , nbconvert
++<<<<<<< HEAD
++, nbformat
++||||||| 5103716b448a
 +, nbformat
++, nose
++=======
++>>>>>>> origin/master
  , numpy
  , parameterized
 +, pillow
  , pytestCheckHook
  , pythonOlder
  }:
@@@ -31,12 -28,9 +44,25 @@@ buildPythonPackage rec 
  
    nativeCheckInputs = [
      chainer
++<<<<<<< HEAD
 +    jupyter
++||||||| 5103716b448a
++    jupyter
++    keras
++    # mxnet (has issues with some CPUs, segfault)
++=======
++>>>>>>> origin/master
      nbconvert
++<<<<<<< HEAD
++    nbformat
++||||||| 5103716b448a
 +    nbformat
++    nose
++=======
++>>>>>>> origin/master
      numpy
```
</details>

<details>
<summary>with</summary>

```
diff --cc pkgs/development/python-modules/django-redis/default.nix
index 63a3519eb745,4036e345a475..000000000000
--- a/pkgs/development/python-modules/django-redis/default.nix
+++ b/pkgs/development/python-modules/django-redis/default.nix
@@@ -30,8 -30,8 +30,8 @@@ buildPythonPackage 
    src = fetchFromGitHub {
      owner = "jazzband";
      repo = "django-redis";
 -    rev = version;
 +    rev = "refs/tags/${version}";
-     hash = "sha256-eX9rUUvpkRrkZ82YalWn8s9DTw6nsbGzi1A6ibRoQGw=";
+     hash = "sha256-m7z3c7My24vrSSnyfDQ/LlWhy7pV4U0L8LATMvkfczc=";
    };
  
    postPatch = ''
diff --cc pkgs/development/python-modules/einops/default.nix
index 14e8b5ec9c6d,03c67d7ce527..000000000000
--- a/pkgs/development/python-modules/einops/default.nix
+++ b/pkgs/development/python-modules/einops/default.nix
@@@ -3,12 -3,9 +3,10 @@@
  , chainer
  , fetchFromGitHub
  , hatchling
- , jupyter
  , nbconvert
- , nbformat
  , numpy
  , parameterized
 +, pillow
  , pytestCheckHook
  , pythonOlder
  }:
@@@ -31,12 -28,9 +29,10 @@@ buildPythonPackage rec 
  
    nativeCheckInputs = [
      chainer
-     jupyter
      nbconvert
-     nbformat
      numpy
      parameterized
 +    pillow
      pytestCheckHook
    ];
  
```
</details>

**Comment by fabianhjr** [comment]
Tested building both, einops had an issue were jupyter contrary to cc340c1b11d3da1057c4e7352bbc55694cc0e308 message was being used for the test phase, added it back.

**Comment by vcunat** [comment]
@Madouura might know what can be done about the rocm breakage:
https://hydra.nixos.org/build/236770928#tabs-buildsteps

**Comment by vcunat** [comment]
> There are still thousands (!) of regressed builds:

If someone could at least see what parts to revert to avoid most of the regressions, I think that would be helpful.  I dislike blocking for a long time, as it blocks security fixes among other things.  Identified risky changes could be moved out of the normal process, e.g. even get a separate Hydra jobset.

**Comment by fabianhjr** [comment]
Hi, is there a shortlist failed builds with most dependents like https://zh.fail.

Could take a look to a couple of regressions but don't know with which to start/which would have the most impact.

**Comment by fabianhjr** [comment]
https://github.com/NixOS/nixpkgs/pull/259643

Hi @NickCao, 5.3.0 was is staging-next and the bump from 5.3.0 to 5.4.0 did cause a merge conflict ( https://github.com/NixOS/nixpkgs/pull/257792#issuecomment-1751933671 ) but the revert (https://github.com/NixOS/nixpkgs/pull/259643) would be merged into staging-next so the update would be gone from both the main branch and staging-next as per the automatic merge workflow. UnU

Fortunately there was a conflict that caused manual review and kept the 5.4.0 version in staging-next during the merge.

**Comment by Madouura** [comment]
> @Madouura might know what can be done about the rocm breakage: https://hydra.nixos.org/build/236770928#tabs-buildsteps

Looks like a couple of the `clang-unwrapped` tests are failing.
You can just delete them in `postPatch` or let it break because #258328 is ready for review and deprecates 5.4.4.

**Comment by vcunat** [comment]
> Hi, is there a shortlist failed builds with most dependents like https://zh.fail/.

Yes, linked from the top of every staging-next PR: https://malob.github.io/nix-review-tools-reports/

But in this case there does not seem anything interesting in there.  The failures are individual builds or small groups, except for `nix` on darwin mentioned above.

**Comment by FRidh** [comment]
I'd like to update python 3.11 to 3.11.6 in https://github.com/NixOS/nixpkgs/pull/259943. This would however be a mass-rebuild when this is merged. Is it reasonable to merge 3.11.6 into master now? It would mean you would get a full rebuild here again.

**Comment by vcunat** [comment]
Please don't.  If it's sufficiently safe, I'd rather defer to ship it together e.g. with the high-severity curl fix announced for Wednesday.  (Though I'm not sure how exactly it will happen for master/unstable, as we still have thousands of regressed builds of staging-next in comparison with master.)

**Comment by Madouura** [comment]
Does ``torchWithRocm`` build properly on this PR?
It was missing ``setuptools`` for python3.11 in https://github.com/NixOS/nixpkgs/pull/258328#issuecomment-1752121616.
Is this a general issue with python-3.11 or specific to ``torchWithRocm``?

**Comment by fabianhjr** [comment]
solved merge conflict with python-modules/lit

**Comment by vcunat** [comment]
The failing rocm build is fixed in staging-next now, surely thanks to merging that upgrade.

**Comment by tobim** [comment]
`curl` fails on `aarch64-darwin` with (config.log):
```
configure:23076: checking for connect in libraries
configure:23104: clang -o conftest -Qunused-arguments -O2 -Wno-pointer-bool-conversion -Werror=partial-availability   -framework CoreFoundation -framework CoreServices conftest.c   >&5
ld: framework not found CoreServices
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
configure:23104: $? = 1
```

This diff fixes it, but I can't test `x86_64-darwin`:
```diff
diff --git a/pkgs/tools/networking/curl/default.nix b/pkgs/tools/networking/curl/default.nix
index c99f09e7f93a..e9d032736336 100644
--- a/pkgs/tools/networking/curl/default.nix
+++ b/pkgs/tools/networking/curl/default.nix
@@ -26,6 +26,8 @@
 , zlibSupport ? true, zlib
 , zstdSupport ? false, zstd
 
+, darwin
+
 # for passthru.tests
 , coeurl
 , curlpp
@@ -70,6 +72,10 @@ stdenv.mkDerivation (finalAttrs: {
 
   nativeBuildInputs = [ pkg-config perl ];
 
+  buildInputs = lib.optionals stdenv.isDarwin [
+    darwin.apple_sdk.frameworks.CoreServices
+  ];
+
   # Zlib and OpenSSL must be propagated because `libcurl.la' contains
   # "-lz -lssl", which aren't necessary direct build inputs of
   # applications that use Curl.
```

**Comment by vcunat** [comment]
Well, we have some time, as Hydra's darwin builders will be fully occupied by `staging-next-23.05` for at least one day, probably more.

**Comment by vcunat** [comment]
Thanks.  I confirmed that on x86_64-darwin it failed and the diff fixed it, so I pushed it with you as author.

**Comment by vcunat** [comment]
Uh, while at least `stdenv` got fixed by that, `python3` won't even evaluate on darwin now due to that fix...

**Comment by tobim** [comment]
Patching it this way was no good. Now there is a cyclic dependency from: curl -> apple_sdk -> cpio -> fetchurl -> curl.

I don't understand how it is possible to build curl right now.

**Comment by vcunat** [comment]
Well, stuff that is needed to build the final stdenv is **not** built by the final stdenv.  That's always been so.  The final package set uses those from some earlier phase of bootstrapping.

**Comment by reckenrode** [comment]
I took a look at it briefly this morning, but I’ll be able to look at the curl issue more this evening EDT.

**Comment by vcunat** [comment]
I should post here as well I guess:

https://github.com/curl/curl/commit/6ab7e1990bd548059f08c471d20537bca13c67b6  might be a candidate for (temporary) revert.  But presumably that was a useful change...

**Comment by reckenrode** [comment]
I found a fix for the curl issue. I made it so curl can build against SDK frameworks now without needing special patching, so if it requires other frameworks in the future, just adding them shouldn’t cause any problems.

**Comment by collares** [comment]
@joelmo Just a heads-up: A bunch of `rpy2` tests are failing because the "postPatch" environment variable contains newline characters and `rpy2` does not sanitize them before processing envvars (see https://github.com/rpy2/rpy2/pull/1037#issuecomment-1764468418).

**Comment by vcunat** [comment]
- [ ] One of `spamassassin`'s tests fails sometimes.  I see the same even in past months sometimes (i.e. not new in this PR): https://hydra.nixos.org/job/nixpkgs/staging-next/spamassassin.x86_64-linux/all
Maybe just drop the test if noone feels like investigating?  Maintainers: @alyssais, @qknight.

**Comment by alyssais** [comment]
> * Upstream I see no open bugs on that test.  [The last one](https://bz.apache.org/SpamAssassin/show_bug.cgi?id=8068) sounds fixed in our current version.

The "fix" was to add a 1 second sleep, which is probably just not enough sometimes.  Let's just diasble the test.

**Pull request merged**
