### PR TITLE
wt3: 3.3.11 -> 3.4.0, wt4: 4.0.5 -> 4.1.0

### PR DESCRIPTION
**Pull request by WilliButz**
###### Motivation for this change
New releases for [wt3](https://github.com/emweb/wt/releases/tag/3.4.0) and [wt4](https://github.com/emweb/wt/releases/tag/4.1.0)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested all pkgs that depend on this change
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
> ../src/include/../common/classes/fb_atomic.h:521:2: error: #error AtomicCounter: implement appropriate code for your platform!

(see the aarch-64 build at https://logs.nix.ci/?key=nixos/nixpkgs.65944&attempt_id=771fda62-66c0-48ae-8a28-f9dfafe2a48f)

Unless there's somewhere a pending, unreleased fix, I'd exclude aarch64 for now, right?

**Review by Ma27 — APPROVED** [review]
Build and tested locally. The change seems fine, however we should discuss what to do with `aarch64` before merging this :)

**Comment by WilliButz** [comment]
> Unless there's somewhere a pending, unreleased fix, I'd exclude aarch64 for now, right?

Do you mean excluding it from the supported platforms? If so, I think we shouldn't do that because it's a transitive build error:
```
builder for '/nix/store/bdbdr1nrifsx4pgnx72ydgrf8dyai8v6-firebird-2.5.7.27050-0.drv' failed with exit code 2
cannot build derivation '/nix/store/98ryhrfm8zz08bqs7jxmwim0c395fi9p-wt-3.4.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4i58dmnkj3jl8hl4iqqisp5pps090d34-wt-4.1.0.drv': 1 dependencies couldn't be built
```

**Comment by Ma27** [comment]
Ouch, I forgot that (in constrast to e.g. Hydra) all build outputs are written to a single log...

According to their installation page (https://www.webtoolkit.eu/wt/doc/reference/html/InstallationUnix.html) it doesn't seem as they miss the support of several platforms. Let's wait until `firebird` gets fixed on aarch64 :+1:

**Pull request merged**
