### PR TITLE
qemu: 5.0.0 -> 5.1.0

### PR DESCRIPTION
**Pull request by misuzu**
###### Motivation for this change
https://wiki.qemu.org/ChangeLog/5.1

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
@GrahamcOfBorg test boot

**Comment by alyssais** [comment]
@misuzu you beat me to it by 15 minutes! :D

I see this is marked as a draft — is there anything you still want to before it’s ready?

**Comment by alyssais** [comment]
@GrahamcOfBorg build qemu

**Comment by misuzu** [comment]
> @misuzu you beat me to it by 15 minutes! :D
> 
> I see this is marked as a draft — is there anything you still want to before it’s ready?

Just wanted to make sure it works on x86-64. Had no issues on aarch64.

**Comment by alyssais** [comment]
misuzu writes:

>> I see this is marked as a draft — is there anything you still want to before it’s ready?
>
> Just wanted to make sure it works on x86-64. Had no issues on aarch64.

rc3 worked for me, and I think this should be basically unchanged code
wise (plus the NixOS tests work), so I think this should be good :)

**Review by alevy — APPROVED** [review]
Tested today on NixOS and works for me

**Pull request merged**
