### PR TITLE
python312Packages.chromadb: 0.5.7 -> 0.5.11

### PR DESCRIPTION
**Pull request by fabaff**
Diff: https://github.com/chroma-core/chroma/compare/refs/tags/0.5.7...0.5.11

Changelog: https://github.com/chroma-core/chroma/releases/tag/0.5.11

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 345372` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python311Packages.chromadb</li>
    <li>python311Packages.chromadb.dist</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python312Packages.chromadb</li>
    <li>python312Packages.chromadb.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Looks like `langchain-chroma` needs an update too.

**Comment by sarahec** [comment]
Result of `nixpkgs-review pr 345372` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages marked as broken and skipped:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python311Packages.chromadb</li>
    <li>python311Packages.chromadb.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python312Packages.chromadb</li>
    <li>python312Packages.chromadb.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
  </ul>
</details>

**Comment by sarahec** [comment]
I'll push out the needed langchain updates this afternoon.

You also have a flaky test at chromadb/test/proto/test_utils.py::test_retry_interceptor

**Comment by sarahec** [comment]
`langchain-chroma` is current at 0.1.4 (PR #341921)

**Comment by sarahec** [comment]
You need #345803 and then you'll pass all tests on Darwin.

**Comment by fabaff** [comment]
Uff, more failing tests

```text
error: builder for '/nix/store/fvad1rlcb3sxsx98l798ni2jjrazkshz-python3.11-langchain-chroma-0.1.4.drv' failed with exit code 1;
       last 10 log lines:
       > tests/integration_tests/test_vectorstores.py:257: ValueError
       > ============================= slowest 5 durations ==============================
       > 0.67s call     tests/integration_tests/test_vectorstores.py::test_chroma_with_persistence
       > 0.11s call     tests/integration_tests/test_vectorstores.py::test_chroma
       > 0.01s call     tests/integration_tests/test_vectorstores.py::test_chroma_update_document
       > 0.01s call     tests/integration_tests/test_vectorstores.py::test_chroma_search_filter
       > 0.01s call     tests/integration_tests/test_vectorstores.py::test_chroma_async
       > =========================== short test summary info ============================
       > FAILED tests/integration_tests/test_vectorstores.py::test_chroma_update_document - ValueError: The truth value of an array with more than one element is ambig...
       > =================== 1 failed, 26 passed, 3 skipped in 1.55s ====================
```

**Comment by sarahec** [comment]
> Uff, more failing tests

This error is a side-effect of the async test not being called properly (fixed by the PR).

Rebase onto master and you should be fine.

**Comment by sarahec** [comment]
Turns out that the langchain repo's integration tests fail the same way outside nixos:
```sh
        # Assert that the updated document is returned by the search
        assert output == [Document(page_content=updated_content, metadata={"page": "0"})]
    
>       assert new_embedding == embedding.embed_documents([updated_content])[0]
E       ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

tests/integration_tests/test_vectorstores.py:257: ValueError
======================================================================= warnings summary ========================================================================
tests/integration_tests/test_vectorstores.py::test_chroma_async
  /Users/seclark/development/langchain/.devenv/state/venv/lib/python3.11/site-packages/_pytest/python.py:148: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
  You need to install a suitable plugin for your async framework, for example:
    - anyio
    - pytest-asyncio
    - pytest-tornasync
    - pytest-trio
    - pytest-twisted
    warnings.warn(PytestUnhandledCoroutineWarning(msg.format(nodeid)))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== slowest 5 durations ======================================================================
0.07s call     tests/integration_tests/test_vectorstores.py::test_chroma
0.03s call     tests/integration_tests/test_vectorstores.py::test_chroma_with_persistence
0.01s call     tests/integration_tests/test_vectorstores.py::test_chroma_update_document
0.01s call     tests/integration_tests/test_vectorstores.py::test_reset_collection
0.01s call     tests/integration_tests/test_vectorstores.py::test_chroma_search_filter_with_scores
==================================================================== short test summary info ====================================================================
FAILED tests/integration_tests/test_vectorstores.py::test_chroma_update_document - ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
====================================================== 1 failed, 24 passed, 4 skipped, 1 warning in 0.78s =======================================================
```

I'm willing to call `test_chroma_update_document` a bad test and plan on disabling it.

**Comment by sarahec** [comment]
Result of `nixpkgs-review pr 345372` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages marked as broken and skipped:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python311Packages.chromadb</li>
    <li>python311Packages.chromadb.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python312Packages.chromadb</li>
    <li>python312Packages.chromadb.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
  </ul>
</details>

**Comment by sarahec** [comment]
Looks like you are good to merge.

**Review by sarahec — APPROVED** [review]
LGTM

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 345372` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.chromadb</li>
    <li>python311Packages.chromadb.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python312Packages.chromadb</li>
    <li>python312Packages.chromadb.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]

**Pull request merged**
