### PR TITLE
fetchs3: allow to name the derivation output

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

The default output name is "foo" which is not very descriptive. To avoid
rebuilds this is kept as the default but one can now pass an optional
name attribute to change it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by copumpkin** [comment]
Wow, I'm the worst. I doubt anyone _wants_ it to be `foo`. I don't rely on it, and if nobody else is using it in `nixpkgs`, it seems like a safe bet to just take out the default. I feel bad for leaving that in by accident!

**Comment by zimbatm** [comment]
@copumpkin what do you think of using baseNameOf s3url as the default instead? I want to keep a default to avoid breaking back-compat. IMO it's being used outside of nixpkgs in private repositories.

**Comment by dtzWill** [comment]
lmao.  It happens! No worries :).  But LOL :grin:

**Comment by basvandijk** [comment]
Nice! TIL that `fetchs3` is in nixpkgs. At LumiGuide I've been using the following for some time:

```nix
{
  fetchS3 = {path, sha256, accessKeyId, secretAccessKey, region}:
    previous.runCommand (baseNameOf path) {
      inherit path;
      AWS_ACCESS_KEY_ID     = accessKeyId;
      AWS_SECRET_ACCESS_KEY = secretAccessKey;
      AWS_DEFAULT_REGION    = region;
      outputHashMode = "flat";
      outputHashAlgo = "sha256";
      outputHash     = sha256;
    } ''${final.awscli}/bin/aws s3 cp "s3://$path" "$out"'';
}
```

I'll be replacing that with `fetchs3`. But first a few issues need to be fixed:

* If I specify `credentials` but don't specify `session_token` I get the following error:
```
error: attribute 'session_token' missing, at 
nixpkgs/pkgs/build-support/fetchs3/default.nix:16:25
```

we should probably define `credentialAttrs` as follows:

```nix
let
  credentialAttrs = stdenvNoCC.lib.optionalAttrs (credentials != null) (with credentials; {
    AWS_ACCESS_KEY_ID = access_key_id;
    AWS_SECRET_ACCESS_KEY = secret_access_key;
    AWS_SESSION_TOKEN = session_token ? null;
  });
in 
```

* I see that the `region` argument is not used. Shouldn't the following environment variable be set: `AWS_DEFAULT_REGION = region;`?

**Comment by zimbatm** [comment]
@basvandijk thanks, integrated your feedback. Wanna try it out?

**Comment by basvandijk** [comment]
Thanks. I successfully executed a command like:
```
$ nix-build -E 'let pkgs = import ./. {}; in pkgs.fetchs3 {s3url = "s3://xxx"; sha256="xxx"; region = "eu-central-1"; credentials = {access_key_id=xxx; secret_access_key=xxx;};}'  
```

**Comment by copumpkin** [comment]
Nice, thanks! I only use temporary credentials which is how I missed the accidentally required session token 😄

**Comment by copumpkin** [comment]
Also, I think the region argument here just dictates which regional endpoint you hit with `GetBucketLocation`, right? After it knows what region your bucket is in, it'll just use that regardless of what you specify.

**Review by copumpkin — APPROVED** [review]
Anyway, this all looks great, thanks!

**Comment by copumpkin** [comment]
One last thing though: in my use case, I don't have a multi-user store so I don't care about the .drvs containing my credentials (and as I said, they're temporary, so it doesn't even matter), but some might find it unexpected that their credentials are in the .drv. Some might prefer `impureEnvVars` for that reason. Do any of you care or shall we just put this in like this for now?

**Comment by zimbatm** [comment]
sounds good, threw in a preferLocalBuild for the good form as well

**Comment by zimbatm** [comment]
hmm, getting "fatal error: An error occurred (400) when calling the HeadObject operation: Bad Request" when using the impureEnvVars

**Comment by zimbatm** [comment]
I will just get rid of it for now. If you pass them as attributes then it's already in the nix store as build inputs anyways.

**Comment by copumpkin** [comment]
Oh, one thing I noticed with `impureEnvVars` in the past is that they always set an env var even if it's unset in the parent context (in which case it's set to empty). An empty session token will probably screw you up. In the past I've had to explicitly unset empty variables. Should probably be fixed in Nix 😄

**Comment by zimbatm** [comment]
yeah that's a weird design decision, I don't expect impureEnvVars to touch the environment :)

**Comment by zimbatm** [comment]
also pushed as 7a37ed59a40b32c4b7f3b15a4e55c473802bdf76 in release-18.03

**Pull request merged**
