### PR TITLE
nixosTests.consul: init

### PR DESCRIPTION
**Pull request by nh2**
###### Motivation for this change

Add a NixOS test for `consul`

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

FYI `consul` maintainers: @pradeepchhetri @vdemeester @nh2

CC @flokli and #72828

### CODE REVIEW

**Comment by nh2** [comment]
@GrahamcOfBorg test consul

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Please call your test in `all-tests.nix`.

**Comment by Ma27** [comment]
@NixOS/ofborg  test consul

**Comment by nh2** [comment]
> Please call your test in `all-tests.nix`.

Looks like @Ma27 did it for me, thanks!

**Review by worldofpeace — DISMISSED** [review]

**Comment by flokli** [comment]
This didn't fail on my machine. 

@GrahamcOfBorg test consul

**Comment by nh2** [comment]
Can I see the previous ofborg failure somehow? If there's a race I'd like to fix it.

**Comment by flokli** [comment]
@nh2 it should be in one of the "tabs" at https://logs.nix.ci/?key=nixos/nixpkgs.74006&attempt_id=dfe01f03-d0d3-4a82-93c6-1d7c42c5cbae.

**Comment by nh2** [comment]
@flokli Thanks, I found it: https://logs.nix.ci/?attempt_id=f102aeb5-eac3-453c-a49f-55378c84cd27&key=nixos%2Fnixpkgs.74006

Is the URL scheme documented somewhere I could bookmark?

**Comment by flokli** [comment]
I assume attempt_id is a UUID, and key owner/repo.prnumber, but I don't think it's more documented than that: https://github.com/NixOS/ofborg/blob/da348bdacce16cdd84f15b46e0b57deb1731a3c0/ofborg/src/tasks/githubcommentposter.rs#L179

**Comment by nh2** [comment]
I've pushed a fix for the test failure, should be non-racy now.

@GrahamcOfBorg test consul

**Comment by flokli** [comment]
Nice, thanks!

**Pull request merged**
