### PR TITLE
luaPackages: add vicious module

### PR DESCRIPTION
**Pull request by makefu**
vicious is a module for creating widgets on window managers.
This commit adds the library and a wrapper lua file for easy importing.

I use the library with the awesome window manager via luaModules:

```
services.xserver.windowManager.awesome.luaModules = [
  pkgs.luaPackages.vicious
];
```

### CODE REVIEW

**Comment by jagajaga** [comment]
Please rename commits name as it said in `CONTRIBUTING.md`

**Comment by makefu** [comment]
@jagajaga i tried to follow `CONTRIBUTING.md` , the commit name states the package (luaPackages) and the change (addition of a a new entry). 
`git logpkgs/top-level/lua-packages.nix` only shows a very diverse commit history. 
What would be the correct commit name in that case?

**Comment by makefu** [comment]
The commit should look like this?

**Comment by makefu** [comment]
Is this the correct way of naming a package under luaModules?

**Comment by lethalman** [comment]
@makefu it's ok, but it cannot be merged. Perhaps you are using an old nixpkgs for this PR.

**Comment by makefu** [comment]
i used the unstable channel for the commit and i will rebase onto master

**Pull request merged**
