### PR TITLE
prefetch-npm-deps: add retry

### PR DESCRIPTION
**Pull request by XYenon**
###### Description of changes

Add retry to `prefetch-npm-deps`. Avoid `buildNpmPackage` always failing in an unstable network environment
Snipaste_2023-06-19_00-55-00

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by lilyinstarlight — COMMENTED** [review]
Thank you for this!

I was cooking up a PR to change ureq out for minreq or isahc too, because it seemed the flakiness was mostly due to internal problems with ureq (and even with network trouble minreq did just fine where ureq didn't), but this is probably a good idea to have anyway

Could you also make the hosted git URL tarball download use the same retry logic?

**Comment by XYenon** [comment]
> Thank you for this!
> 
> I was cooking up a PR to change ureq out for minreq or isahc too, because it seemed the flakiness was mostly due to internal problems with ureq (and even with network trouble minreq did just fine where ureq didn't), but this is probably a good idea to have anyway
> 
> Could you also make the hosted git URL tarball download use the same retry logic?

I have changed it for that.

**Review by lilyinstarlight — COMMENTED** [review]
One more thing and this broadly looks okay for now: could you also make it `cargo clippy` clean and run `cargo fmt`?

Thanks again!

Edit: looks like clippy is concerned about the size of the `Result` return. You could switch it to `anyhow::Result<Response>` which should help that. Tbh though I kinda want to get rid of ureq, so I'm fine to just ignore that clippy nit until we redo it anyway

**Review by lilyinstarlight — APPROVED** [review]
This will probably get removed when we refactor to use another request library (which would ideally have at least connection error retry logic built-in), but this is acceptable for now. Thank you!

**Pull request merged**
