### PR TITLE
Add generated documentation for library functions

### PR DESCRIPTION
**Pull request by tazjin**
This adds generated documentation using [nixdoc](https://github.com/tazjin/nixdoc) for some of the library functions in `<nixpkgs>.lib`. It is part of my NixCon 2018 hackathon project.

A [rendered view is available](https://storage.googleapis.com/files.tazj.in/nixdoc/manual.html#sec-functions-library-debug) for your viewing pleasure. :eyes: 

This PR previously included the changes to documentation comments, but those have been moved to #49383, see [this comment](https://github.com/NixOS/nixpkgs/pull/49275#issuecomment-433832744) for why.

The documentation files can be generated by installing `nixdoc` (available in `master`) and running:

```
# in nixpkgs/doc:
nixdoc -c 'strings' -d 'String manipulation functions' -f ../lib/strings.nix  > functions/library/strings.xml
nixdoc -c 'trivial' -d 'Miscellaneous functions' -f ../lib/trivial.nix  > functions/library/trivial.xml
nixdoc -c 'lists' -d 'List manipulation functions' -f ../lib/lists.nix  > functions/library/lists.xml
nixdoc -c 'debug' -d 'Debugging functions' -f ../lib/debug.nix > functions/library/debug.xml
nixdoc -c 'options' -d 'NixOS / nixpkgs option handling' -f ../lib/options.nix  > functions/library/options.xml
```

Some notes & caveats:

* functions returning other functions via currying currently have incorrect function argument annotations, as there is no easy way to distinguish between arguments for the returned function and arguments for the library function
* the manual index becomes pretty large with these functions included. I discussed with @grahamc that it may be sensible to move these function docs to an appendix
* due to the manual override functionality implemented after tazjin/nixdoc#14 the manual build prints a whole bunch of warnings for missing files. There may be a way to suppress those ...

### CODE REVIEW

**Comment by tazjin** [comment]
Oh, and before I forget it - shoutout to @jD91mZM2 for writing `rnix`, which made this relatively easy to implement by preserving comments in the AST representation!

**Comment by joachifm** [comment]
Very nice :) Is it feasible to generate the docs during the build instead of checking them into the repo?

**Comment by grahamc** [comment]
Unfortunately not, @joachifm -- nixdoc requires unstable rust features which we can't get without using the beta rust compiler, and we almost certainly don't want to make that a blocker for releasing.

This looks _fabulous_ -- way to go @tazjin!

**Comment by tazjin** [comment]
@joachifm Eventually we'd like to do that, but as Graham mentioned the `nixdoc` tool currently depends on nightly Rust because one of the dependencies (the Nix parser, in fact) does.

The required features are going to stabilise not too far in the future, at which point we could add it to the automatic manual generation. An alternative approach is removing the use of unstable features from that lib and its dependencies, which @Mic92 has [started doing](https://gitlab.com/jD91mZM2/arenatree/merge_requests/1). 

Either way, for now just checking in the generated files already gets us quite far!

**Comment by tazjin** [comment]
@jD91mZM2 Awesome, thank you! Would you consider publishing the stable-compatible `rnix` and `arenatree` to crates.io?

It seems like `rustPlatform.buildRustPackage` chokes on git-dependencies and `carnix` chokes on Gitlab repositories (it shan't be easy!).

**Comment by tazjin** [comment]
As you can see above there's now a PR for adding `nixdoc` to `nixpkgs` using stable Rust. I still would prefer to get pre-generated docs checked in now, so we can deal with building a fully automated pipeline later on.

**Comment by Mic92** [comment]
@tazjin you should be able build git dependencies now with buildRustPackage since https://github.com/NixOS/nixpkgs/pull/46362

**Comment by tazjin** [comment]
@Mic92 I used `buildRustCrate` now and it works fine.

**Comment by tazjin** [comment]
Added docs for `lib.options` and `lib.debug` on the flight back to Oslo :)

There are some slightly unclear things in both of those, so it'd be appreciated if someone could do a second pass - but we can do that in a followup PR.

**Comment by Mic92** [comment]
@tazjin is this ready to merge?

**Comment by tazjin** [comment]
It's ready technically, I'll just make more PRs when I cover the other files.

Two notes:

1. The manual index becomes quite large after merging, @grahamc suggested that we could move it to an appendix - I don't know how that works though.

2. It'd probably be nice if someone read over the doc strings I modified and gave a thumbs up/down, but those are also easy to improve upon later.

**Comment by grahamc** [comment]
What do you think about this strategy for merging:

1. split this in to two PRs: one for the .nix file updates, and one for the generated docs
2.  backport the .nix updates to 18.09
3. create a new PR for docs generation for master
4. create a new PR for docs generation for 18.09 (generated separately, I think?)

Ideally the "update generated docs" step would be a make target in the Makefile, not called by default.

Before merging the generated docs, I'd like to do a rendered display for people to look at.

**Comment by tazjin** [comment]
> Before merging the generated docs, I'd like to do a rendered display for people to look at.

Oh, I forgot to mention this - I publish [rendered docs here](https://storage.googleapis.com/files.tazj.in/nixdoc/manual.html#sec-functions-library-debug) at the moment.

----

> split this in to two PRs: one for the .nix file updates, and one for the generated docs

Works for me. I'd make a new PR for the `.nix` updates and extract them out of this one. I'd keep this as the PR for docs generation in `master`.

For the 18.09 PR I suppose the steps are something like:

1. Check out `18.09` branch.
2. Generate docs in there.
3. PR to that branch.

Correct? Or is that branch no longer in use?

---

> Ideally the "update generated docs" step would be a make target in the Makefile, not called by default.

Lets do this as the next step, we can discuss a little bit what the best workflow is but for now I just want to get Some Docs :tm: in.

**Comment by tazjin** [comment]
Changes to Nix-files have been removed from this PR, they are now in #49383.

**Comment by grahamc** [comment]
Working on making it an appendix. One maybe long-term project is to fix the code examples with absolute function names, so

```
mod 11 10
=> 1
mod 1 10
=> 1
```

becomes

```
lib.trivial.mod 11 10
=> 1
lib.trivial.mod 1 10
=> 1
```

this might be part of a larger effort to improve the examples, though, like adding titles and splitting shared examples in to two?

Also, what is the status of splitting the input with the output, for testable doc comments?

**Comment by tazjin** [comment]
> One maybe long-term project is to fix the code examples with absolute function names

You mean by actually updating the doc comments to look like that, or via some spooky rewriting?

> Also, what is the status of splitting the input with the output, for testable doc comments?

It depends on me writing a proper parser for the doc comments. Currently it's a somewhat advanced string-splitter that works well with the existing format, but it should be a bit more flexible. I'll probably start looking into it this evening.

**Comment by tazjin** [comment]
I've rebased this and regenerated all the docs above (there were a handful of new functions).

@grahamc When do you think we can get this merged?

**Comment by Infinisil** [comment]
This looks awesome! One suggestion I have is to put the commands to regenerate these files somewhere in the repo. Maybe also somehow make sure that they get run before a channel update.

**Comment by Infinisil** [comment]
I'd be fine with just a simple `Readme.md` with the instructions you have at the top of this PR for now, nothing too sophisticated. Just so this is captured *somewhere* and people don't need to find this PR to update it.

**Comment by tazjin** [comment]
An alternative approach is in [this commit](https://github.com/tazjin/nixpkgs/commit/d43bd3af921049ca3278b94d0ff58cf188a7af8b). Instead of checking in the generated files it updates the manual build process to generate them, which is not too difficult.

Currently due to the way this works the list of files that needs to be documented is specified twice (once for generation of the doc XML, and once in another XML file to include the generated files). I think this is a very small price to pay for now though. Thoughts?

**Comment by tazjin** [comment]
@Mic92 Agree, and @Infinisil does, too. I'm closing this PR in favour of the other one.

**Pull request closed without merging**
