### PR TITLE
add more vim plugins and update

### PR DESCRIPTION
**Pull request by lovesegfault**
added:
ayu-theme/ayu-vim
dcharbon/vim-flatbuffers
gentoo/gentoo-syntax
nfnty/vim-nftables
qnighy/lalrpop.vim
tbodt/deoplete-tabnine
uarun/vim-protobuf

###### Motivation for this change
Some of the plugins I use were missing

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @andir @gilligan

### CODE REVIEW

**Comment by jonringer** [comment]
This might be a little tedious, but it helps with git history to follow https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs

Do one commit to update the current plugins, then do a commit for each plugin you're adding :)

the commits should look like:
```
vimPlugins: update
vimPlugins.ayu-vim: init at <ver>
....
```

it's tedious, but if a given commit needs to be reverted or cherry-picked, then it becomes a lot easier

**Comment by lovesegfault** [comment]
@jonringer On it :)

**Comment by lovesegfault** [comment]
@jonringer all fixed up :)

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
commits LGTM

```
[37 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/71954
18 package were build:
vimPlugins.ayu-vim vimPlugins.coc-snippets vimPlugins.deoplete-tabnine vimPlugins.fugitive-gitlab-vim vimPlugins.gentoo-syntax vimPlugins.lalrpop-vim vimPlugins.syntastic vimPlugins.tagbar vimPlugins.vim-airline vimPlugins.vim-better-whitespace vimPlugins.vim-flatbuffers vimPlugins.vim-gitgutter vimPlugins.vim-nftables vimPlugins.vim-pandoc vimPlugins.vim-protobuf vimPlugins.vim-snippets vimPlugins.vim-visual-multi vimPlugins.vimtex
```

**Comment by lovesegfault** [comment]
Thanks @jonringer !

**Pull request merged**
