### PR TITLE
Update pip tools

### PR DESCRIPTION
**Pull request by mmlb**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jonringer** [comment]
To adhere to CONTRIBUTING, you will probably want to squash the two commits into one

**Comment by mmlb** [comment]
Hey @jonringer, that isn't quite the case. CONTRIBUTING.md doesn't state anything on it but does refer to the  nixpkgs-manual, and the manual states

> Make commits of logical units.

I believe this is what I've done.

**Comment by jonringer** [comment]
I always took it as atomic "package changes" that all correlated to a given change. This way, all changes can easily be reverted if needed.

**Comment by mmlb** [comment]
I thought that may be the case too, but then I don't see why not just let the commits be while in the PR state and then "squash and merge"

**Comment by zimbatm** [comment]
In that specific case I think it was fine to just push changes until it works and use the squash button at the end. Having separate commits helped me with the review as well.

**Comment by mmlb** [comment]
yep `git rebase -i` ftw. A better pr/diff viewer also helps a lot. I'm partial to reviewable.io myself since it doesn't try to take over the development model like gerrit does.

**Pull request merged**
