### PR TITLE
root: 6.32.02 -> 6.32.04

### PR DESCRIPTION
**Pull request by guitargeek**
root: 6.32.02 -> 6.32.04

### CODE REVIEW

**Comment by veprbl** [comment]
Thanks. This looks good. I usually advocate against use of `USE` flags (no pun intended). In practice, doing `root.override { enableRoofit = true; }` is not simpler in terms of cognitive load or more robust than `root.overrideAttrs (old: { cmakeFlags = old.cmakeFlags ++ [ "-Droofit=ON" ]; })`. Unless we plan to use those flags, let's get rid of them (e.g. enable by default).

**Comment by guitargeek** [comment]
Hi @veprbl, that's a great suggestion, thanks a lot! It works just as well as my proposal with the `useRoofit` and `useTmva` input. Very very nice! Like this, I can use a nix enviroment with a RooFit-less ROOT build as a base for RooFit developments without compiling all the rest of ROOT.

That will also be a big help for students that don't have a laptop powerful enough to build all of ROOT.

One thing I'm still trying to figure out, and maybe you have an idea too: what if I have the artifacts from `root.overrideAttrs (old: { cmakeFlags = old.cmakeFlags ++ [ "-Droofit=OFF" ]; })`, can I transfer is also to a different machine without rebuilding ROOT?

**Comment by veprbl** [comment]
> That will also be a big help for students that don't have a laptop powerful enough to build all of ROOT.
> 
> One thing I'm still trying to figure out, and maybe you have an idea too: what if I have the artifacts from `root.overrideAttrs (old: { cmakeFlags = old.cmakeFlags ++ [ "-Droofit=OFF" ]; })`, can I transfer is also to a different machine without rebuilding ROOT?

Yes, this is a good question. What I do for myself, is I have a "builders" option setup in nix config on my less-powerful machines. It's described in https://nix.dev/manual/nix/2.18/advanced-topics/distributed-builds and will work seamlessly as long as you have a network connection.

If you want to initiate the transfers manually from a builder machine, you could issue something like `nix-build -E 'with import <nixpkgs> {}; root.overrideAttrs (old: { cmakeFlags = old.cmakeFlags ++ [ "-Droofit=OFF" ]; })' -o ./result` and `nix copy --to ssh://mylaptop ./result`.

**Comment by guitargeek** [comment]
Awesome, thanks! Looks like it can work for me too!

By the way, I have made another change to the configuration flags, enabling `mathmore`. Probably the package was always meant to be built with it, because GSL is already one of the inputs. It's just that since ROOT 6.30, it's not enable by default anymore, so we have to do it manually.

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 334647` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>hepmc3</li>
    <li>ns-3</li>
    <li>python311Packages.hepmc3</li>
    <li>python312Packages.hepmc3</li>
    <li>root</li>
    <li>xfitter</li>
    <li>yoda-with-root</li>
  </ul>
</details>

**Pull request merged**
