### PR TITLE
build-support/php: prevent the creation of symlinks

### PR DESCRIPTION
**Pull request by drupol**
The origin of this PR is the following PR: https://github.com/NixOS/nixpkgs/pull/254817

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by etu — CHANGES_REQUESTED** [review]
I'm thinking this is the wrong approach, I think we should go in the direction of #254817 and use makeWrapper or makeBinaryWrapper instead. That should be easy to use in the loop.

Why is this the wrong approach? A lot of of programs may depend on `__DIR__` or similar to find the files location and include files based on that... which won't work if the file is copied.

**Review by etu — APPROVED** [review]
Seems to work for me... on Linux.

I'm thinking that this PR fixes #254817 if it works on macOS as well.

So I'd like to ping @avrahamappel for testing

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 255156` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>adminer</li>
    <li>php81Packages.composer</li>
    <li>php82Packages.composer</li>
    <li>php83Packages.composer</li>
    <li>phpactor</li>
    <li>pixelfed</li>
    <li>vimPlugins.phpactor</li>
  </ul>
</details>

**Comment by avrahamappel** [comment]
Works well! Thanks @drupol!

**Pull request merged**
