### PR TITLE
foot: 1.17.2 -> 1.18.1

### PR DESCRIPTION
**Pull request by wahjava**
- switch to finalAttrs pattern

## Description of changes

https://codeberg.org/dnkl/foot/releases/tag/1.18.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by donovanglover — DISMISSED** [review]
Result of `nixpkgs-review pr 331804` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>foot</li>
    <li>foot.debug</li>
    <li>foot.terminfo</li>
    <li>foot.themes</li>
  </ul>
</details>

**Comment by donovanglover** [comment]
Looks like ofborg is failing from xtgettcap: https://logs.ofborg.org/?key=nixos/nixpkgs.331804&attempt_id=e484f682-f258-4e0f-991f-8e96577560dc

**Review by sternenseemann — CHANGES_REQUESTED** [review]
Add `-Dwerror=false` to `mesonFlags` which should alleviate the ofborg failure (probably best done in a separate commit). The clang unused args warning is a bit of a nuisance with the werror by default packages…

**Comment by sternenseemann** [comment]
Can you also revert the switch to `finalAttrs`? It is misleading here since the whole idea is to have stuff that is independent of overrides by default (the stimulus file) to save on rebuilds. Consequently, we need to have `version` in the `let` and we gain nothing by using `finalAttrs` except confusing people who've read the source and are wondering why overriding source doesn't change the stimulus stuff.

**Comment by alyssais** [comment]
1.80.1 is out now

**Review by sternenseemann — APPROVED** [review]

**Pull request merged**
