### PR TITLE
Openldap module declarative contents

### PR DESCRIPTION
**Pull request by Ekleog**
This PR allows to declaratively set the contents of the LDAP database. I've tested it on my machine by replacing the stock module with the post-PR one, and it appears to work.

### CODE REVIEW

**Comment by Ekleog** [comment]
cc @domenkozar @Mic92 for the last few changes to this module, hopefully it can still get in before 18.03 :)

**Comment by Mic92** [comment]
```
services = {
+    openldap = {
+      enable = true;
+      declarativeContents = ''
+        dn: dc=example,dc=org
+        objectClass: domain
+        dc: example
+      '';
+    };
```

results in:


```
Mar 03 17:51:50 turingmachine systemd[1]: Starting LDAP server...
Mar 03 17:51:50 turingmachine openldap-pre-start[28809]: Available database(s) do not allow slapadd
Mar 03 17:51:50 turingmachine systemd[1]: openldap.service: Control process exited, code=exited status=1
Mar 03 17:51:50 turingmachine systemd[1]: openldap.service: Failed with result 'exit-code'.
Mar 03 17:51:50 turingmachine systemd[1]: Failed to start LDAP server.
```

What else is required?

**Comment by Ekleog** [comment]
Is `services.openldap` supposed to work without a configuration file? (the one generated is empty if `extraConfig` is empty)

It works for me with this (ie. keeping the same `extraConfig` as before and adding the `declarativeContents`):
```nix
{
  services.openldap = {
    enable = true;
    urlList = [ "ldap://127.0.0.1:389/" ];
    extraConfig = ''
      include ${pkgs.openldap}/etc/schema/core.schema
      include ${pkgs.openldap}/etc/schema/cosine.schema
      include ${pkgs.openldap}/etc/schema/inetorgperson.schema
      include ${pkgs.openldap}/etc/schema/nis.schema
  
      database bdb
      suffix dc=gaspard,dc=ninja
      directory /var/db/openldap
      rootdn cn=root,dc=gaspard,dc=ninja
      rootpw [...]
      index cn,sn,uid pres,eq,approx,sub
      index objectClass eq
    '';
    declarativeContents = ''
      dn: dc=gaspard,dc=ninja
      objectClass: domain
      dc: gaspard
     
      dn: ou=users,dc=gaspard,dc=ninja
      objectClass: organizationalUnit
      ou: users
     
      # ...
    '';
  };
}
```

**Comment by Mic92** [comment]
@GrahamcOfBorg test openldap

**Comment by Mic92** [comment]
test worked locally.

**Comment by Ekleog** [comment]
Thanks! :)

**Pull request merged**
