### PR TITLE
Fix id mismatches

### PR DESCRIPTION
**Pull request by joachifm**

### CODE REVIEW

**Comment by iElectric** [comment]
fixes #3727

**Comment by joachifm** [comment]
My script missed the fact that tomcat uid/gid were not the same ... fixed now.

**Comment by edolstra** [comment]
Do we actually need statically assigned uids/gids for many of these? For instance, the uid for `nscd` can also be assigned dynamically by `update-users-groups.pl`.

**Comment by joachifm** [comment]
@edolstra what determines whether a static uid/gid is "needed"? (I don't quite get why any of it is defined up-front, except where necessary to refer to an id before the system is fully initialised, I suppose).

**Comment by peti** [comment]
A static id is needed when the corresponding software uses that uid/guid to store files to the disk that ought to be interchangeable with other systems. Processes that have a separate uid for privilege separation but never store anything on the hard drive, however, probably don't need a statically assigned id.

**Comment by edolstra** [comment]
I would add uids that do get written to disk but won't be shared with other systems (e.g. the `nscd` disk cache).

**Comment by joachifm** [comment]
@peti @edolstra that makes sense, thank you for the information.

**Comment by joachifm** [comment]
Anyway, pruning the list of static ids seems to me a greater undertaking. I suggest merging this PR as a short-term fix and that a separate issue be created to track the pruning (following the criteria outlined above).

**Comment by thoughtpolice** [comment]
Sideline note: FWIW, grsecurity ID is *not* unused - see https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/grsecurity/default.nix#L16 for example. AFAIK, the problem here is IDs are a NixOS only concept while the package builder needs to know a GID ahead of time to compile the kernel with `GRKERNSEC_PROC_GID`; hence this awful hack.

It's probably better to note that GID is completely reserved even if it is not mentioned syntactically.

**Comment by joachifm** [comment]
@thoughtpolice grsecurity is marked as unused only on the uid side, the gid is there. There is no grsecurity *user*, right?

**Comment by joachifm** [comment]
To be clear, I say that a uid is "unused" if a group exists that has no corresponding user and vice versa for gids. You're right that "reserved" might be clearer. My reasoning was that "unused" implies "reserved", given the informal id number assignment rules.

**Comment by joachifm** [comment]
Is there any interest in this at all/something I need to fix? I'd be happy to help with pruning the list of ids as well, but would need some guidance. I've made an initial list of candidates, but apart from some obvious ones, I'm just not familiar with most of the services in question to make an informed decision. Otherwise, feel free to close this.

**Comment by iElectric** [comment]
+1 for merging

**Comment by jraygauthier** [comment]
After upgrading to *15.09*, I get the following error when performing `nixos-rebuild switch`:
 
~~~
warning: not applying UID change of user ‘ntp’
~~~

Thrown from: <https://github.com/NixOS/nixpkgs/blob/788800e437c4a0a25d95e217540bded68804b25e/nixos/modules/config/update-users-groups.pl#L166>


From `nixos/modules/misc/ids.nix` I can see its value is `ntp = 179;`.

It was changed by <https://github.com/NixOS/nixpkgs/pull/6722/files>. Its uid
was formerly `3` and `179` was free.

My current entry in `/etc/passwd` is:

~~~
ntp:x:3:65534:NTP daemon user:/var/lib/ntp:/run/current-system/sw/bin/nologin
~~~

and no other entry map to `179`.

Anyone (@joachifm) knows how this can be fixed?. Note that my config has
`mutableUsers = false;`.

**Comment by domenkozar** [comment]
It's a warning, not an error. You can modify uid yourself, but you'll also have to change permissions on your filesystem.

**Comment by jraygauthier** [comment]
@domenkozar: I see that it is a warning but only because this is a lucky case an no other
service were assigned the `uid = 3`.  I would have expected that with `mutableUsers = false`
these information would have been handled in a declarative fashion. Is there any reason why
it shouldn't? Because after subsequent updates, this warning could well end up an error if
not fixed.

**Comment by domenkozar** [comment]
iirc it does handle uids declaratively, but it leaves existing entries mutable (otherwise you'd get into a lot of manual work).

**Comment by jraygauthier** [comment]
Ok. Thanks for the quick answer.

**Pull request merged**
