### PR TITLE
valgrind: 3.16.1 -> 3.17.0

### PR DESCRIPTION
**Pull request by tollb**
Version 3.17.0 contains support for sched_getattr and sched_setattr.
This fixes an issue where the following messages can be logged:

    WARNING: unhandled amd64-linux syscall 315

See: https://bugs.kde.org/show_bug.cgi?id=369029

In addition to the version bump, this commit enables doCheck (as the
tests now pass) and provides a separate pname and version.

The upstream 3.17.0 also reorganized the output, placing the
default.supp file in libexec rather than lib. The postInstall hook was
adjusted accordingly.

A patch file which has not been used since upgrade to 3.15.0 in 2019
was also removed.

###### Motivation for this change
Fix above-mentioned issue, as well as other fixes and enhancements.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Note: testing of binaries was cursory with the exception of valgrind.
cc @edolstra as maintainer

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@tollb please rebase manually on staging

**Comment by tollb** [comment]
Thanks @symphorien and @SuperSandro2000. I am in the process of rebasing. I'm trying to rebuild/test on staging and it is taking a while....

**Comment by tollb** [comment]
Sorry about all of the review requests... They were added automatically when I changed the branch from master to staging. I'm not sure how to clear them.

**Comment by tollb** [comment]
As a note, I encountered the above-mentioned valgrind message "WARNING: unhandled amd64-linux syscall 315" while working with a program that uses the pango library. The pango library was updated in 1.48.3 to "Do costly fontconfig calls in threads". See: https://github.com/GNOME/pango/blob/1.48.3/NEWS.

The warning can be seen with valgrind 3.16.1 and pango 1.48.4 as found in a recent nixos-unstable:

```
$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/e1f8852faac7638e88d5e8a5b9ee2a7568685e3f.tar.gz -p pango -p valgrind --run "valgrind pango-list" >/dev/null
==467965== Memcheck, a memory error detector
==467965== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==467965== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==467965== Command: pango-list
==467965==
--467965-- WARNING: unhandled amd64-linux syscall: 315
--467965-- You may be able to write your own handler.
--467965-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--467965-- Nevertheless we consider this a bug.  Please report
--467965-- it at http://valgrind.org/support/bug_reports.html.
==467965==
==467965== HEAP SUMMARY:
==467965==     in use at exit: 798,534 bytes in 19,125 blocks
==467965==   total heap usage: 35,869 allocs, 16,744 frees, 4,282,916 bytes allocated
==467965==
==467965== LEAK SUMMARY:
==467965==    definitely lost: 139,264 bytes in 544 blocks
==467965==    indirectly lost: 167,665 bytes in 6,645 blocks
==467965==      possibly lost: 1,092 bytes in 4 blocks
==467965==    still reachable: 487,745 bytes in 11,899 blocks
==467965==         suppressed: 0 bytes in 0 blocks
==467965== Rerun with --leak-check=full to see details of leaked memory
==467965==
==467965== For lists of detected and suppressed errors, rerun with: -s
==467965== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

The warning does not occur with valgrind 3.16.1 and pango 1.45.5 found in a recent nixos-20.09:

```
$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/59b8d9cf24e9fcf10341a0923c9bdca088dca8c8.tar.gz -p pango -p valgrind --run "valgrind pango-list" >/dev/null
==467617== Memcheck, a memory error detector
==467617== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==467617== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==467617== Command: pango-list
==467617==
==467617==
==467617== HEAP SUMMARY:
==467617==     in use at exit: 782,902 bytes in 19,015 blocks
==467617==   total heap usage: 35,755 allocs, 16,740 frees, 4,220,243 bytes allocated
==467617==
==467617== LEAK SUMMARY:
==467617==    definitely lost: 139,360 bytes in 545 blocks
==467617==    indirectly lost: 167,713 bytes in 6,646 blocks
==467617==      possibly lost: 1,420 bytes in 20 blocks
==467617==    still reachable: 474,145 bytes in 11,802 blocks
==467617==                       of which reachable via heuristic:
==467617==                         length64           : 224 bytes in 5 blocks
==467617==                         newarray           : 1,568 bytes in 18 blocks
==467617==         suppressed: 0 bytes in 0 blocks
==467617== Rerun with --leak-check=full to see details of leaked memory
==467617==
==467617== For lists of detected and suppressed errors, rerun with: -s
==467617== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

The warning should be resolved with an update to valgrind 3.17.0, as provided in this PR.

cc fyi for pango development: @7c6f434c @jtojnar

**Comment by tollb** [comment]
Updated to address a conflict introduced after PR was filed. NOTE: OfBorg test on darwin seems to have stalled.

**Review by trofi — APPROVED** [review]

**Pull request merged**
