### PR TITLE
youtrack: 2022.3.65371 -> 2023.1.17582

### PR DESCRIPTION
**Pull request by leona-ya**
###### Description of changes

https://www.jetbrains.com/youtrack/whatsnew/

Since JetBrains has deprecated JAR packaging (we used that),
I changed the packaging to use the included ZIP (JetBrains Launcher), renamed the `youtrack` package to `youtrack_2022_3` and add a new package `youtrack_2023_1`. The module uses state paths by major version now and requires manual update as (1) we can't ensure that any migration script can do this automatically (2) YouTrack may requires a new license if a user updates (3) A major update requires manual interaction anyways.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by yu-re-ka — CHANGES_REQUESTED** [review]
As the migration is a manual process (even with the migration script it requires clicking through a setup wizard), the new version should be added as a new package, and then the default package is selected based on `config.system.stateVersion`.
Simlar to postgres, users should perform the manual upgrade(s) by [making backups, ] setting the `services.youtrack.package = pkgs.youtrack_2023_1` and then taking care of the state migration.

**Comment by yu-re-ka** [comment]
Ideally the state directory would be postfixed by a version, in case future upgrades are necessary.

**Comment by leona-ya** [comment]
> and then taking care of the state migration.

I'm not sure what the best way for this is. For postgres this is easy as there's `pg_upgrade` and loads of documentation with scripts. I would like to provide something similar to allow easy upgrades. As far as I understand your comment, this should not be part of the module, but is there some point in the docs? Additionally at least I don't like the upstream way (at least for the upgrade 2022.3 -> 2023.1) to make a backup and then restore it in the new installer.

**Comment by yu-re-ka** [comment]
> Additionally at least I don't like the upstream way (at least for the upgrade 2022.3 -> 2023.1) to make a backup and then restore it in the new installer.

but that's exactly how the migration path for new postgres major version works

**Comment by leona-ya** [comment]
wtf github closed this PR, continues in #254214

**Pull request closed without merging**
