### PR TITLE
nixos networking module: resolvconf + dnsmasq

### PR DESCRIPTION
**Pull request by ts468**
- keep /etc/resolv.conf static when using dnsmasq
- make resolvconf restart dnsmasq after an update

### CODE REVIEW

**Comment by ts468** [comment]
Any objections against that change?

**Comment by lethalman** [comment]
cc @edolstra

**Comment by edolstra** [comment]
I would prefer to have /etc/resolv.conf managed consistently, i.e., via resolvconf.

**Comment by ts468** [comment]
Could you maybe help me to understand your concerns? I thought the idea of having dnsmasq in the loop is to have a static /etc/resolv.conf that points to dnsmasq only, and then only update dnsmasq with resolvconf?

**Comment by ts468** [comment]
@edolstra I still think that this PR improves the current implementation when using dnsmasq to resolve DNS queries locally. If you don't have any strong objections I would go ahead and merge the PR in the next days.

**Comment by edolstra** [comment]
I don't understand what this change does. What does it mean to "keep /etc/resolv.conf static"?

**Comment by ts468** [comment]
The desired configuration is that `/etc/resolv.conf` should point to `dnsmasq`, and then `dnsmasq` gets updated by `resolvconf`.

Currently, `resolvconf` updates `dnsmasq` _and_ `/etc/resolv.conf`. `libc=NO` should stop that.
`dnsmasq_restart=...` makes sure `dnsmasq` actually reloads the new DNS settings provided by `resolvconf`.

An example where it is not desirable to write new nameservers into `/etc/resolv.conf` with `resolvconf` directly are, for example, VPN connections into a private network. When `dnsmasq` is receiving the updates from `resolvconf`, then the added DNS server can be bound to the private domain to only be queried for the private domain of the VPN. All other DNS traffic is still forwarded normally through the local network. Unfortunately, a setup like that is not possible within `/etc/resolv.conf` directly.

**Comment by ts468** [comment]
@edolstra Just as I don't know how github works, do you automatically get all messages that are written in a PR that you are a participant of, or do I have to `at` you explicitly in a message?

**Comment by wkennington** [comment]
This behavior is working fine for me even before your change. Dnsmasq uses
inotify to determine when to reload /etc/dnsmasq-resolv.conf after
resolvconf writes to it. My resolv.conf currently and also seems to only
contain `nameserver 127.0.0.1`

**Comment by ts468** [comment]
@wkennington Thanks, I didn't know that dnsmasq uses inotify. But I've also got `domain ...` and `search ...` entries in `/etc/resolv.conf` that `resolvconf` is including for my VPN connections. What would be the disadvantage of setting `libc=NO`?

**Comment by wkennington** [comment]
Is that not more inline with the behavior you expect when using a dhcp
client. As far as I'm aware, if you prevent those from being set, then you
are breaking dhcp setting the default search domain as I don't think
dnsmasq adds it back in.

**Comment by ts468** [comment]
@wkennington Thanks for your help! How do I prevent `resolvconf` from adding search domains for private interfaces then? I've got the option of adding a domain with the `expand-hosts` option in dnsmasq, but I don't know of a way how to get rid of a domain that is included in `/etc/resolv.conf`. Does it mean I should patch `resolvconf` instead?

**Comment by wkennington** [comment]
I'll look into this more but I'm pretty sure that is something you have to
live with unless you want to disable writing to /etc/resolv.conf entirely
and possible breaking some things. You could do this in your own configs
but I don't think this is a sane default.

**Comment by ts468** [comment]
Thanks for your feedback and efforts so far! I've removed the default values from the PR and introduced a simple hook into `resolvconf.conf` instead. Would that be OK?

**Comment by ts468** [comment]
The changes shouldn't hurt anyone, so merging the PR.

**Pull request merged**
