### PR TITLE
mu: enable AOT native-comp for emacs lisp

### PR DESCRIPTION
**Pull request by jian-lin**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Make sense, but any chance we can move this out into a separate hook and just call that? I’m sure there are other emacs packages that would benefit from this.

**Comment by jian-lin** [comment]
> any chance we can move this out into a separate hook and just call that?

Good idea, I will wait for #194279 to be merged first.

> I’m sure there are other emacs packages that would benefit from this.

Are there? To the best of my knowledge, mu is the only package. Could you list a few?

**Comment by jian-lin** [comment]
> Are there? 

Indeed, there are many packages like mu4e.

```console
rg emacs -t nix --glob '!pkgs/applications/editors/emacs' --glob '
!pkgs/build-support/emacs' --glob '!nixos' --glob '!test'
```

I am working on it.

**Comment by peterhoeg** [comment]
Even our regular emacs packages (under `emacsPackages`) require nativecomp so they should simply use the same hook/helper.

**Comment by jian-lin** [comment]
> Even our regular emacs packages (under emacsPackages) require nativecomp

They have infra for native comp since https://github.com/NixOS/nixpkgs/commit/a7cb8e36ac17526ffc2255c9c48c94be675c4d67, not a hook though.

> they should simply use the same hook/helper

Yeah, that is also a good idea.

I will mark this as draft to prevent it from being merged.

**Comment by jian-lin** [comment]
I give up make a setup hook for native-comp because I cannot figure out how to put everything needed by native-comp into a hook, e.g. [these two lines](https://github.com/NixOS/nixpkgs/blob/9bb7ee9867037d75ed05af89b10fba8330bc3786/pkgs/build-support/emacs/generic.nix#L73-L75). I will leave that for future contributors.

I make native-comp conditionally depend on `emacs.nativeComp`.

I suggest we merge this for now and transfer it to a hook when the hook is implemented.

**Comment by chvp** [comment]
> I give up making a setup hook for native-comp because I cannot figure out how to put everything needed by native-comp into a hook, e.g. [these lines](https://github.com/NixOS/nixpkgs/blob/9bb7ee9867037d75ed05af89b10fba8330bc3786/pkgs/build-support/emacs/generic.nix#L71-L75). I will leave that for future contributors.

Is this not already solved in a general way by the current emacs infrastructure/emacs-overlay. All my emacs packages (except `mu4e`) are AOT-compiled already, and I can't imagine someone added AOT compilation to all those packages seperately.

**Comment by jian-lin** [comment]
> Is this not already solved in a general way by the current emacs infrastructure/emacs-overlay.

No and emacs-overlay is not involved here.

> All my emacs packages (except mu4e) are AOT-compiled already

Let me explain some details.

Currently, only [elisp packages][1], which are built using [elpaBuild][2], [melpaBuild][3] or [trivialBuild][4], enable AOT native-comp after my [pr][5]. This is because only these three builders run native-comp in the [postInstall][6]. As a result, mu4e does not do AOT native-comp.

> I can't imagine someone added AOT compilation to all those packages seperately.

Yeah, the infra of emacs needs some improvement to do it the right way. One possible way is to make [native-comp][6] a hook, as @peterhoeg says.

Unfortunately, it seems few people care about native-comp in emacs. Almost all [recent][5] [native-comp][7] [related][8] [prs][9] are all from me. As I said, I tried to make native-comp a hook, but fails. I would appreciate it if someone could improve the emacs infra. mu4e is the last piece I care for native-comp, so here is this pr.

[1]: https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/editors/emacs/elisp-packages
[2]: https://github.com/NixOS/nixpkgs/blob/d2cfe468f81b5380a24a4de4f66c57d94ee9ca0e/pkgs/applications/editors/emacs/elisp-packages/elpa-packages.nix#L35
[4]: https://github.com/NixOS/nixpkgs/blob/d2cfe468f81b5380a24a4de4f66c57d94ee9ca0e/pkgs/top-level/emacs-packages.nix#L81
[3]: https://github.com/NixOS/nixpkgs/blob/d2cfe468f81b5380a24a4de4f66c57d94ee9ca0e/pkgs/top-level/emacs-packages.nix#L85
[6]: https://github.com/NixOS/nixpkgs/blob/d2cfe468f81b5380a24a4de4f66c57d94ee9ca0e/pkgs/build-support/emacs/generic.nix#L79
[5]: https://github.com/NixOS/nixpkgs/pull/176780
[7]: https://github.com/nix-community/emacs-overlay/pull/252
[8]: https://github.com/NixOS/nixpkgs/pull/194279
[9]: https://github.com/NixOS/nixpkgs/pull/194278

**Comment by peterhoeg** [comment]
I am truly sorry to leave you hanging like this. I absolutely think there is value in your work - I just haven't had tiem to do anything about it.

**Comment by jian-lin** [comment]
Oh, I misunderstood. Let's reopen it and give it some more time.

**Comment by LiGoldragon** [comment]
Unless emacs *absolutely requires' the elisp files, the nativeComp outputs should go in their own derivations. Lean emacs deploys. Easier to think about and modularize. Just a thought. I might implement something and will let you know if I do.

**Comment by peterhoeg** [comment]
In principle that makes sense, but is there really a usecase for emacs
without the natively compiles files?

**Comment by bhankas** [comment]
Just so it doesn't get forgotten to sands of time, @peterhoeg can we do something about this? Anybody else who might be able to review if you're busy?

**Comment by peterhoeg** [comment]
My apologies. I will take the time to do what is needed during this coming week.

**Comment by LiGoldragon** [comment]
> In principle that makes sense, but is there really a usecase for emacs without the natively compiles files?

I was thinking more about emacs without the elisp files

**Comment by bhankas** [comment]
ping @peterhoeg ! Apologies if I'm being annoying, but I'd quite like to see this merged. If Peter is busy, can @adisbladis take a look?

**Comment by adisbladis** [comment]
While it would indeed be better to solve in a hook or other central location it's OK to have a workaround until then.

**Comment by jian-lin** [comment]
FYI, I made a follow-up [PR](https://github.com/NixOS/nixpkgs/pull/253438) to package mu4e as a separate Emacs lisp package.

**Pull request merged**
