### PR TITLE
python310: init at 3.10a1

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Add next pre-release build

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build python310.pkgs.setuptools
@GrahamcOfBorg build python310Packages.pip

**Comment by jonringer** [comment]
tests fail due to python310 not being able to install from a wheel. 

I think this this commit is pretty uncontroversial, and it will make future updates easier

#100389 will remain open until the python ecosystem can install wheels

**Comment by FRidh** [comment]
Are you watching my screen?! I was just looking again into this and the upstream CPython issue.

**Comment by uri-canva** [comment]
This doesn't work on macOS: https://hydra.nixos.org/job/nixpkgs/trunk/python310.x86_64-darwin/all

Unfortunately if you try to install `python3` on macOS it tries to install this now, rather than `python3-3.9.0` which works.

**Comment by jonringer** [comment]
python3 should still point to python38 .... https://github.com/NixOS/nixpkgs/blob/2deeb58f49480f468adca6b08291322de4dbce6b/pkgs/top-level/all-packages.nix#L10402

unless you have an overlay. But that's not nixpkgs, that's your local machine at that point.

**Comment by uri-canva** [comment]
Yes, `nix-env --install --attr nixpkgs.python3` installs `python38`, but `nix-env install python3` installs `python3-3.10.0a1`. Also `nix-env -u` will try to upgrade both `python3-3.9.0` and `python3-3.8.6` to `python3-3.10.0a1`.

**Comment by jonringer** [comment]
oh.... nix-env.... 

python310 isn't really meant to be used... and can't even install wheels atm due to upstream issues.

**Comment by jonringer** [comment]
also, I don't have mac hardware, so a darwin contributor will need to contribute a working darwin build. I can mark this as a linux only to avoid it failing to build. But now that ofborg doesn't build darwin builds, the only "feedback" is hydra. And even then that's a particularly slow iteration loop

**Comment by uri-canva** [comment]
If it's not meant to be used, it's probably an issue that affects Linux as well, on distributions other than nixos: if I run `nix-env --install python3` on ubuntu I'll also get `python3-3.10.0a1`, and it sounds like even though it builds correctly, it doesn't function correctly.

**Comment by jonringer** [comment]
personally, I don't use nix-env for this case, and many others.....

**Comment by jonringer** [comment]
for python, or any tool really, you should always pin something "up until" the next breaking change. python has breaking changes between minor versions, so getting the latest isn't what you want.

Really the issue is with nix-env's trying to imply desired behavior.

**Comment by jonringer** [comment]
I view nix-env as, "similar to other package managers", but misses the mark on why nix is great. Almost to the point that people should avoid using it for package installation.

**Comment by FRidh** [comment]
@uri-canva the first thing to learn about `nix-env` is, don't ever use `nix-env -i`, but always `nix-env -iA`.

**Pull request merged**
