### PR TITLE
[WIP] Update Azure sdk

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Author for #60435 hasn't been heard from for almost a month. 

Had to pin azure-storage for nixops_1_6_1.

Eventually I hope to fix the `pythonPackages.azure`, as it's currently horribly broken. Also hope to restore proper support for azure in nixops (but that will be much later)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jonringer** [comment]
Unfortunately the `azure-mgmt` doesn't include the latest major bumps of the packages, so I had to revert them back to the previous versions

**Comment by jonringer** [comment]
quoted url's and rebased off master to avoid merge conflicts

**Comment by jonringer** [comment]
@FRidh what's your opinion on making a `buildAzurePythonPackage` and `buildAzureMgmtPythonPackage` where I make all the namespace changes generically over the packages. Getting really tired of all the postPatch and postInstall hooks.

**Comment by kalbasit** [comment]
Are you planning to include all the changes from #60435?

**Comment by FRidh** [comment]
@jonringer please write a function to perform `overridePythonAttrs` instead. That way we can guarantee that overriding will still work. Downside is that your overrides take precedence over what is in the original expression.

Has upstream considered fixing their namespace packages?

**Comment by jonringer** [comment]
@kalbasit eventually yes

@FRidh AFAIK, upstream is waiting for python2 to be phased out and then they can remove their `azure-nspkg` "work-around"

for the buildHelpers, I was thinking I can do something to the effect of a pass thru function which would default the postInstall and postPatch phases similar to:

pkgs/top-level/python-packages.nix
```
  buildAzurePythonPackage =
    let
      # remove python2 vs python3 namespace hacks
      postPatch' = ''
        sed '/azure-namespace-package/d' setup.py
        rm -f azure_bdist_wheel.py
      '';
      postInstall' = (if isPy3k then ''
        rm -f "$out/lib/${python.sitePackages}"/azure/__init__.py
      '' else ''
        echo "__import__('pkg_resources').declare_namespace(__name__)" > "$out/lib/${python.sitePackages}"/azure/__init__.py
      '');
    in
      { postPatch ? postPatch'
      , postInstall ? postInstall', ...}@attrs:
        buildPythonPackage attrs;
```

**Comment by jonringer** [comment]
There would be a similar function for the `azure-mgmt-*` packages as well

**Comment by jonringer** [comment]
Also, for the packages that have a high major version than what the `azure` meta package has, I was think of moving those expression under the `python-modules/azure/` directory and then just adding the latest to the python-packages.nix

**Comment by kalbasit** [comment]
@jonringer I applied all the changes in #60435 and rebased it off of master. Can you please give that PR a try, I'd like to get this merged soon if possible.

I like the idea of having a common overlay we can apply to all packages, can this PR be built on top of #60435 once it lands on master to DRY up the code?

**Comment by jonringer** [comment]
I can once i get home. Just on lunch right now.

**Comment by kalbasit** [comment]
> I can once i get home. Just on lunch right now.

I will keep an eye out for your comment then. Bon Appetit!

**Comment by jonringer** [comment]
closing in favor of #71797

**Pull request closed without merging**
