### PR TITLE
python310Packages.rapidfuzz: 2.14.0 -> 2.15.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Diff: https://github.com/maxbachmann/RapidFuzz/compare/refs/tags/v2.14.0...v2.15.0

Changelog: https://github.com/maxbachmann/RapidFuzz/blob/refs/tags/v2.15.0/CHANGELOG.rst

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by GaetanLepage — CHANGES_REQUESTED** [review]
The changes made in jiwer have already been merged in https://github.com/NixOS/nixpkgs/pull/224953.
Please, rebase this PR so as to leave only the rapidfuzz update.

**Review by GaetanLepage — APPROVED** [review]
LGTM !

**Comment by wegank** [comment]
```
12 packages failed to build:
paperwork paperwork.dist python310Packages.paperwork-backend python310Packages.paperwork-backend.dist python310Packages.paperwork-shell python310Packages.paperwork-shell.dist python311Packages.paperw
ork-backend python311Packages.paperwork-backend.dist python311Packages.paperwork-shell python311Packages.paperwork-shell.dist truvari truvari.dist

74 packages built:
adl anime-downloader anime-downloader.dist apostrophe atomic-operator atomic-operator.dist ibus-engines.uniemoji ledger-autosync ledger-autosync.dist paperless-ngx poetry poetry.dist poetryPlugins.po
etry-audit-plugin poetryPlugins.poetry-audit-plugin.dist poetryPlugins.poetry-plugin-up poetryPlugins.poetry-plugin-up.dist puddletag puddletag.dist pynitrokey pynitrokey.dist python310Packages.autof
aiss python310Packages.autofaiss.dist python310Packages.cleo python310Packages.cleo.dist python310Packages.fire python310Packages.fire.dist python310Packages.fuzzywuzzy python310Packages.fuzzywuzzy.d
ist python310Packages.jiwer python310Packages.jiwer.dist python310Packages.levenshtein python310Packages.levenshtein.dist python310Packages.nkdfu python310Packages.nkdfu.dist python310Packages.rapidf
uzz python310Packages.rapidfuzz.dist python310Packages.syncedlyrics python310Packages.syncedlyrics.dist python310Packages.thefuzz python310Packages.thefuzz.dist trytond trytond.dist python310Packages
.videocr python310Packages.videocr.dist python311Packages.autofaiss python311Packages.autofaiss.dist python311Packages.cleo python311Packages.cleo.dist python311Packages.fire python311Packages.fire.d
ist python311Packages.fuzzywuzzy python311Packages.fuzzywuzzy.dist python311Packages.jiwer python311Packages.jiwer.dist python311Packages.levenshtein python311Packages.levenshtein.dist python311Packa
ges.nkdfu python311Packages.nkdfu.dist python311Packages.rapidfuzz python311Packages.rapidfuzz.dist python311Packages.syncedlyrics python311Packages.syncedlyrics.dist python311Packages.thefuzz python
311Packages.thefuzz.dist python311Packages.trytond python311Packages.trytond.dist python311Packages.videocr python311Packages.videocr.dist spotdl spotdl.dist sublime-music sublime-music.dist ulaunche
r ulauncher.dist
```

**Review by wegank — APPROVED** [review]

**Review by GaetanLepage — APPROVED** [review]
Good

**Comment by mweinelt** [comment]
Paperwork builds for me.

**Pull request merged**
