### PR TITLE
CuboCore.packages: added

### PR DESCRIPTION
**Pull request by dan4ik605743**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dan4ik605743 — COMMENTED** [review]
Everything works fine.
image
image

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 142380` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
22 packages built:
</summary>
<ul>
<li>CuboCore.coreaction</li>
<li>CuboCore.corearchiver</li>
<li>CuboCore.corefm</li>
<li>CuboCore.coregarage</li>
<li>CuboCore.corehunt</li>
<li>CuboCore.coreimage</li>
<li>CuboCore.coreinfo</li>
<li>CuboCore.corekeyboard</li>
<li>CuboCore.corepad</li>
<li>CuboCore.corepaint</li>
<li>CuboCore.corepdf</li>
<li>CuboCore.corepins</li>
<li>CuboCore.corerenamer</li>
<li>CuboCore.coreshot</li>
<li>CuboCore.corestats</li>
<li>CuboCore.corestuff</li>
<li>CuboCore.coreterminal</li>
<li>CuboCore.coretime</li>
<li>CuboCore.coretoppings</li>
<li>CuboCore.coreuniverse</li>
<li>CuboCore.libcprime</li>
<li>CuboCore.libcsys</li>
</ul>
</details>

**Comment by dan4ik605743** [comment]
> i

ok

**Comment by dan4ik605743** [comment]
> This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
> 
> Result of `nixpkgs-review pr 142380` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
>  22 packages built:

ok

**Comment by dan4ik605743** [comment]
I will make backporting when my first PR will be examined in 21.05 (#144643), and then I'm not there in the number of Maintainers not recorded, you need to be push, then I will make backporting.

**Comment by SuperSandro2000** [comment]
Please create the PR manually and cherry pick the relevant commit.

**Comment by dan4ik605743** [comment]
> Please create the PR manually and cherry pick the relevant commit.

I told me you need my first PR Push, because there is Maintainer-List there.

**Comment by dan4ik605743** [comment]
@SuperSandro2000 check my pr #144643

**Comment by SuperSandro2000** [comment]
The maintainer addition needs first to be in master and then it can be cherry-picked by anyone into a backport PR.

I usually don't merge backports because I am always on unstable on my personal machine and don't know how the state of stable is and if certain required features are already there.

**Comment by dan4ik605743** [comment]
> The maintainer addition needs first to be in master and then it can be cherry-picked by anyone into a backport PR.
> 
> I usually don't merge backports because I am always on unstable on my personal machine and don't know how the state of stable is and if certain required features are already there.

Well, well, I still created pr, everything is correct there like. Let's wait like push and I will create on this backport.

**Pull request merged**
