### PR TITLE
nixos/userborn: fix username typo

### PR DESCRIPTION
**Pull request by aanderse**
## Things done

i _think_ this is a typo... apologies if i have misunderstood!

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Redirect this to Master branch.

**Comment by aanderse** [comment]
yeah, oops... made commit from web ui and didn't notice the branch 😅

will wait to hear back from @nikstur first

**Comment by Shawn8901** [comment]
Isn't the username taken ATM from the attr maps key? See line 99.
If you want to take the name attribute inside the users attr. It's called "name".

"Name" is predefined with the attra key, when undefined.

So that should fix a thing if someone is doing the following 

``` 
users.users.foo = { 
         name = "bar"; 
        ....
};
```
Which does not make a lot sense (to me) but would be possible according docs ( https://github.com/NixOS/nixpkgs/blob/bc947f541ae55e999ffdb4013441347d83b00feb/nixos/modules/config/users-groups.nix#L91 )

**Comment by Shawn8901** [comment]
So  as far as I can see that should fix a thing if someone is doing like

```
users.users.foo = {
   name = "bar";
   ....
 };
```
Atm it should create a folder called "foo" for a user named "bar", which might be not the desired result.

To I find the scenario of that mixing quite strange.

**Comment by aanderse** [comment]
yes, this is a pattern in nixos, you understand correctly

**Comment by nikstur** [comment]
Thanks! Yeah I think what you're doing is correct. Please re-direct to master and we can merge.

**Comment by aanderse** [comment]
thanks for confirming @nikstur!

and i will mention i started using this on a little side project i am working on for fun... it is awesome! every bit as fantastic as i hoped it would be when you announced it
keep up the great work you have been doing ❤️

**Review by Aleksanaa — APPROVED** [review]

**Review by nikstur — APPROVED** [review]

**Pull request merged**
