### PR TITLE
[19.09] Backport rng improvements

### PR DESCRIPTION
**Pull request by kmcopper**
###### Motivation for this change
Backports many rng improvements in master back down to the stable channel.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers
cc @c0bw3b @JohnAZoidberg @r-ryantm @teto

### CODE REVIEW

**Review by bjornfor — COMMENTED** [review]
Please use `git cherry-pick -x ...` to get the commit reference of the original commit into the git history.

**Review by c0bw3b — COMMENTED** [review]
What exactly doesn't work with current `rngd` on r19.09 that would warrant a backport?

**Comment by Mic92** [comment]
some context: https://github.com/NixOS/nixpkgs/pull/73007#issuecomment-552644750

**Comment by kmcopper** [comment]
I figured the rng bias security improvement, adding jitterentropy, general bug fixes, and no apparent breaking changes were good enough to backport. Feel free to correct me if I am wrong I am unclear with the nix backports policy but I feel it's good enough to warrant a backport of anything as long as it doesn't break anything else.

**Comment by Mic92** [comment]
We have 20.03 now.

**Pull request closed without merging**
