### PR TITLE
Move various packages out of gnome scope

### PR DESCRIPTION
**Pull request by jtojnar**
## Description of changes

We have been slowly disbanding it since it offers little benefit.

Extracted from https://github.com/NixOS/nixpkgs/pull/319535

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - nixosTests.{gnome,gnome-xorg,cinnamon,pantheon}
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by doronbehar — APPROVED** [review]
Diff and commits look good, and I'm not against this change, but I don't fully understand the motivation for it.

**Comment by jtojnar** [comment]
Mainly, the consensus of GNOME maintainers a long time ago was that the scope is more trouble than it’s worth:

- Overlays are even harder (`overrideScope` required).
- Referring to non-leaf packages outside the scope is annoying – `callPackage` can only inject the scope, and overriding the dependencies requires modifying the scope.
- Attributes already have `gnome-` as prefix so it would be duplicated in the scope name.
- Selection criteria are unclear – should this just be core package set?
- Upstream package status is fluent – what should we do if an app becomes a part of core, what if it gets removed?
- Main benefit was ability to update all GNOME packages at once but we still needed to do libraries like GLib or GTK manually. Nowadays we use [predicate matching on `updateScript` name](https://github.com/NixOS/nixpkgs/blob/517d8466ca9e858f12ba1a99c5e6ae355dbc45c1/maintainers/scripts/update.nix#L165) but there is still room for improvement (e.g. adding tags).

**Comment by doronbehar** [comment]
OK then, I fully support this PR.

**Comment by jtojnar** [comment]
libgnome-secret done separately since it is more involved: https://github.com/NixOS/nixpkgs/pull/321785

**Comment by doronbehar** [comment]
I tend to like how there the PR is split to multiple commits - makes reviewing easier.

**Comment by linsui** [comment]
Why are some packages still kept in gnome scope? And I thought we should add some aliases?

**Comment by jtojnar** [comment]
It is lot of work so I am doing it in waves – more will be come later (help appreciated). Aliases should have been added – if I missed any we should fix that.

**Comment by linsui** [comment]
Ah, sorry, I forgot that I disabled allowAliases. :facepalm:  it takes me some time to figure out which packages are moved and fix all of them.

**Pull request merged**
