### PR TITLE
rubyfmt: avoid failing upon warning

### LINKED ISSUE #320722: Build failure: rubyfmt
### Steps To Reproduce

Happens on all platforms.

1. build rubyfmt

### Build log

```
...
  linking ruby
  make[2]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  make[1]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  make[1]: Entering directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  *** Following extensions are not compiled:
  fiddle:
        Could not be configured. It will not be installed.
        /private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout/ext/fiddle/extconf.rb:73: missing libffi. Please install libffi or use --with-libffi-source-dir w>
        Check ext/fiddle/mkmf.log for more details.
  openssl:
        Could not be configured. It will not be installed.
        /private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout/ext/openssl/extconf.rb:101: OpenSSL library could not be found. You might want to use --with-open>
        Check ext/openssl/mkmf.log for more details.
  *** Fix the problems, then remove these directories and try again if you want.
  make[1]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'

  --- stderr
  + cp enc/jis/props.h.blt enc/jis/props.h
  parse.c:9130:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
      int yynerrs = 0;
          ^
  1 warning generated.
  bigdecimal.c:7161:18: warning: variable 'prec' set but not used [-Wunused-but-set-variable]
      SIGNED_VALUE prec;
                   ^
  ripper.c:10310:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
      int yynerrs = 0;
          ^
  1 warning generated.
  1 warning generated.
  thread 'main' panicked at librubyfmt/build.rs:90:5:
  could not extract arch from rbconfig.rb
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Notify maintainers

cc @bobvanderlinden 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.31, NixOS, 24.11 (Vicuña), 24.11.20240612.57d6973`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/dydg48djlykksz8cxq0xjplyxpa9pvf4-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bobvanderlinden**
## Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/320722

The build was failing because there were unused variables. These were introduced by upgraded dependencies. We don't want to be bothered by such warnings in the future, so this removes the `#![deny(warnings, missing_copy_implementations)]` annotation.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 322233` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rubyfmt</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 322233` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>rubyfmt</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 322233` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rubyfmt</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> Result of `nixpkgs-review pr 322233` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

```
  linking ruby
  make[2]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  make[1]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  make[1]: Entering directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  *** Following extensions are not compiled:
  fiddle:
        Could not be configured. It will not be installed.
        /private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout/ext/fiddle/extconf.rb:73: missing libffi. Please install libffi or use --with-libffi-source-dir with libffi sou>
        Check ext/fiddle/mkmf.log for more details.
  openssl:
        Could not be configured. It will not be installed.
        /private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout/ext/openssl/extconf.rb:101: OpenSSL library could not be found. You might want to use --with-openssl-dir=<dir> >
        Check ext/openssl/mkmf.log for more details.
  *** Fix the problems, then remove these directories and try again if you want.
  make[1]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'

  --- stderr
  + cp enc/jis/props.h.blt enc/jis/props.h
  parse.c:9130:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
      int yynerrs = 0;
          ^
  1 warning generated.
  bigdecimal.c:7161:18: warning: variable 'prec' set but not used [-Wunused-but-set-variable]
      SIGNED_VALUE prec;
                   ^
  ripper.c:10310:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
      int yynerrs = 0;
          ^
  1 warning generated.
  1 warning generated.
  thread 'main' panicked at librubyfmt/build.rs:90:5:
  could not extract arch from rbconfig.rb
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by GaetanLepage** [comment]
@bobvanderlinden do you think you could fix the build on darwin ?

**Comment by bobvanderlinden** [comment]
> do you think you could fix the build on darwin ?
Sorry, I already worked on a possible solution, but I couldn't find a good way to test it for darwin and got distracted :sweat_smile::disappointed: I have pushed the change. Could you give it a try?

**Comment by GaetanLepage** [comment]
> Sorry, I already worked on a possible solution, but I couldn't find a good way to test it for darwin and got distracted 😅😞 I have pushed the change. Could you give it a try?

No worry !
Unfortunately I see no improvement:
```
  make[2]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout/ext/ripper'
  make[2]: Entering directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  revision.h unchanged
  config.status: creating ruby-runner.h
  linking ruby
  make[2]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  make[1]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  make[1]: Entering directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'
  *** Following extensions are not compiled:
  fiddle:
        Could not be configured. It will not be installed.
        /private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout/ext/fiddle/extconf.rb:73: missing libffi. Please install libffi or use --with-libffi-source-dir w>
        Check ext/fiddle/mkmf.log for more details.
  openssl:
        Could not be configured. It will not be installed.
        /private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout/ext/openssl/extconf.rb:101: OpenSSL library could not be found. You might want to use --with-open>
        Check ext/openssl/mkmf.log for more details.
  *** Fix the problems, then remove these directories and try again if you want.
  make[1]: Leaving directory '/private/tmp/nix-build-rubyfmt-0.10.0.drv-0/source/librubyfmt/ruby_checkout'

  --- stderr
  + cp enc/jis/props.h.blt enc/jis/props.h
  parse.c:9130:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
      int yynerrs = 0;
          ^
  1 warning generated.
  bigdecimal.c:7161:18: warning: variable 'prec' set but not used [-Wunused-but-set-variable]
      SIGNED_VALUE prec;
                   ^
  ripper.c:10310:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
      int yynerrs = 0;
          ^
  1 warning generated.
  1 warning generated.
  thread 'main' panicked at librubyfmt/build.rs:90:5:
  could not extract arch from rbconfig.rb
```

**Comment by SuperSandro2000** [comment]
Lets first fix linux. We can fix darwin in another PR.

**Pull request merged**
