### PR TITLE
elixir: 1.5.1 -> 1.5.2

### PR DESCRIPTION
**Pull request by djgoku**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Thank you for contributing to Nixpkgs! Could you read [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) and change the commit message to `elixir: 1.5.1 -> 1.5.2`? This helps us separate package updates from other kinds of changes, and estimate severity of the update at a glance.

**Comment by djgoku** [comment]
So it looks like this has already been merged in master, but this does add a comment on how to generate the sha256 for contributors in the future.

**Comment by orivej** [comment]
Oops, indeed it has been updated in #31259. The comment is not particularly useful since you (1) can always update the version, alter the hash a bit, try to build the package and copy the hash from the hash mismatch error, (2) can often update the version and compute the hash with e.g. `nix-prefetch-url '<nixpkgs>' -A elixir.src`, and adding a comment about this generic technique into that file would be out of place.

**Comment by djgoku** [comment]
Yeah, it was more for future me or contributor to be able to contribute instead of fumbling around to figure our how the hash is created.

Ahh I didn't know about: `nix-prefetch-url '<nixpkgs>' -A elixir.src` I am going to close this.

**Pull request closed without merging**
