### PR TITLE
treewide: remove unused occurence of fetchFromGitHub argument

### PR DESCRIPTION
**Pull request by isabelroses**
## Description of changes

https://github.com/NixOS/nixpkgs/issues/313981

These files were left unchanged due to them calling other files with the `fetchFromGitHub` arg.
```
"pkgs/servers/foundationdb/default.nix"
"pkgs/games/fteqw/default.nix"
"pkgs/development/compilers/zig/0.11.nix"
"pkgs/development/compilers/zig/0.12.nix"
"pkgs/development/compilers/zig/0.10.nix"
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by Sigmanificient** [comment]
Result of `nixpkgs-review pr 314910` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by Sigmanificient — APPROVED** [review]
0 rebuilds!

**Review by uncenter — APPROVED** [review]

**Review by cafkafk — APPROVED** [review]
After this gets merged, it should probably be added to `.git-blame-ignore-revs`, ty for noticing and fixing this :D

**Comment by Sigmanificient** [comment]
> After this gets merged, it should probably be added to `.git-blame-ignore-revs`, ty for noticing and fixing this :D

Maybe the whole list of commits from #313981 should gets git blame ignored

**Comment by cafkafk** [comment]
> > After this gets merged, it should probably be added to `.git-blame-ignore-revs`, ty for noticing and fixing this :D
> 
> Maybe the whole list of commits from #313981 should gets git blame ignored. In that case, it might be better to deal with it once the whole issue is done?

I don't see why they would need to be tied together to be honest, i think it's much better to just get it done as it comes. Let's move that discussion to the issue thou, I don't think it should block this.

**Pull request merged**
