### PR TITLE
houdini: 20.5.370 -> 20.5.445

### PR DESCRIPTION
**Pull request by permahorse**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thiagokokada** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 361799`

**Review by thiagokokada — APPROVED** [review]

**Comment by wrvsrx** [comment]
Why make houdini-runtime as a fixed-output derivation?

**Comment by pedohorse** [comment]
why fixed-output:
the contents of houdini-runtime is result of self-extraction of installer provided by the vendor. It does not depend on anything except that installer.
When it was not a fixed-output derivation - every time you updated your system you needed to rebuild houdini-runtime from original installer archive, and that archive was being garbage collected all the time - so that all caused a bunch of inconveniences, and took way too much space, since the installer archive is 2+ GB, and houdini-runtime is similarly 2+ GB, and you don't want multiples of them for each system rebuild, especially since they are the same.

**Comment by wrvsrx** [comment]
I need an older version of houdini. Now I need to set `outputHash = null` to `overrideAttrs`.

It doesn't make much inconviniences, but it feels strange to set `outputHash` for a local build result.

**Comment by wrvsrx** [comment]
Besides, is houdini running well on your side? I found houdini can't run after https://github.com/NixOS/nixpkgs/pull/363168. Would you like to check my fix https://github.com/NixOS/nixpkgs/pull/370461

**Comment by pedohorse** [comment]
oh my, that's no good.
how come i was not notified about that PR, even though i'm set as maintainer on houdini package??

also for older versions - I'm maintaining this flake, it makes things very easy: https://github.com/pedohorse/houdini-nix

**Pull request merged**
