### PR TITLE
ocaml-bitstring: git -> 2.0.4

### PR DESCRIPTION
**Pull request by maurer**
Google Code no longer supports git cloning. We could restore this
revision by exporting the repository to github and working from there,
but barring a request for it, we can just use the released version.

### CODE REVIEW

**Comment by maurer** [comment]
See #15558

**Comment by vbgl** [comment]
Please revert.

See #8291. Bitstring-2.0.4 is broken in OCaml-4.02.

So this commit turns a package that cannot be built into a package that can be built but should not be used.

**Comment by fpletz** [comment]
@vbgl Ah, sorry, I thought that would fail. Reverted: afa69e14dbc63792f541e2b6b2a8eca8e429c342

**Comment by maurer** [comment]
Oh, I'd forgotten that the released version was broken on new OCaml. Using `fetchzip` should be fine for now as a little more stopgap, the only projects I know of using bitstring have announced their intention to move to `ppx_bitstring`, so this really only needs to work a bit longer.

@vbgl Do you want to put up your patch as a PR, or should I do it?

**Comment by vbgl** [comment]
Merged in 10767521a05bccab5d8a001383ab3ef3e8ec3344

**Pull request merged**
