### PR TITLE
argon2_cffi: 19.2.0 -> 20.1.0

### PR DESCRIPTION
**Pull request by alexbakker**
###### Motivation for this change

A newer version is available.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 99932` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
12 packages marked as broken and skipped:
</summary>
<ul>
<li>etesync-dav</li>
<li>mailman</li>
<li>python37Packages.fastapi</li>
<li>python37Packages.mailman</li>
<li>python37Packages.mailman-hyperkitty</li>
<li>python37Packages.qasm2image</li>
<li>python37Packages.skein</li>
<li>python38Packages.fastapi</li>
<li>python38Packages.mailman</li>
<li>python38Packages.mailman-hyperkitty</li>
<li>python38Packages.qasm2image</li>
<li>python38Packages.skein</li>
</ul>
</details>
<details>

  <summary>54 packages failed to build and are new build failures:</summary>
  <ul>
<li>devpi-client: log was empty</li>
<li>devpi-server: log <a href="https://termbin.com/0fl1">https://termbin.com/0fl1</a></li>
<li>python27Packages.ldaptor: log <a href="https://termbin.com/5vlw">https://termbin.com/5vlw</a></li>
<li>python27Packages.privacyidea-ldap-proxy: log was empty</li>
<li>python37Packages.Nikola: log was empty</li>
<li>python37Packages.colorcet: log was empty</li>
<li>python37Packages.cufflinks: log was empty</li>
<li>python37Packages.datashader: log was empty</li>
<li>python37Packages.dockerspawner: log was empty</li>
<li>python37Packages.hbmqtt: log <a href="https://termbin.com/g1fdb">https://termbin.com/g1fdb</a></li>
<li>python37Packages.holoviews: log was empty</li>
<li>python37Packages.hvplot: log was empty</li>
<li>python37Packages.intake: log was empty</li>
<li>python37Packages.ipydatawidgets: log was empty</li>
<li>python37Packages.kmapper: log was empty</li>
<li>python37Packages.nbclient: log <a href="https://termbin.com/ed3q">https://termbin.com/ed3q</a></li>
<li>python37Packages.nbsmoke: log was empty</li>
<li>python37Packages.papermill: log was empty</li>
<li>python37Packages.privacyidea: log was empty</li>
<li>python37Packages.qiskit: log was empty</li>
<li>python37Packages.qiskit-aer: log was empty</li>
<li>python37Packages.qiskit-aqua: log was empty</li>
<li>python37Packages.qiskit-ibmq-provider: log was empty</li>
<li>python37Packages.qiskit-ignis: log was empty</li>
<li>python37Packages.qiskit-terra: log was empty</li>
<li>python37Packages.runway-python: log was empty</li>
<li>python37Packages.scikit-tda: log was empty</li>
<li>python37Packages.stytra: log was empty</li>
<li>python37Packages.vega: log was empty</li>
<li>python38Packages.Nikola: log was empty</li>
<li>python38Packages.colorcet: log was empty</li>
<li>python38Packages.cufflinks: log was empty</li>
<li>python38Packages.datashader: log was empty</li>
<li>python38Packages.dockerspawner: log was empty</li>
<li>python38Packages.hbmqtt: log <a href="https://termbin.com/bmoj">https://termbin.com/bmoj</a></li>
<li>python38Packages.holoviews: log was empty</li>
<li>python38Packages.hvplot: log was empty</li>
<li>python38Packages.intake: log was empty</li>
<li>python38Packages.ipydatawidgets: log was empty</li>
<li>python38Packages.kmapper: log was empty</li>
<li>python38Packages.nbclient: log <a href="https://termbin.com/r2qj">https://termbin.com/r2qj</a></li>
<li>python38Packages.nbsmoke: log was empty</li>
<li>python38Packages.papermill: log was empty</li>
<li>python38Packages.privacyidea: log was empty</li>
<li>python38Packages.qiskit: log was empty</li>
<li>python38Packages.qiskit-aer: log was empty</li>
<li>python38Packages.qiskit-aqua: log was empty</li>
<li>python38Packages.qiskit-ibmq-provider: log was empty</li>
<li>python38Packages.qiskit-ignis: log was empty</li>
<li>python38Packages.qiskit-terra: log was empty</li>
<li>python38Packages.runway-python: log was empty</li>
<li>python38Packages.scikit-tda: log was empty</li>
<li>python38Packages.stytra: log was empty</li>
<li>python38Packages.vega: log was empty</li>
  </ul>
</details>
<details>
<summary>
69 packages built:
</summary>
<ul>
<li>jupyter</li>
<li>mitmproxy (python38Packages.mitmproxy)</li>
<li>octoprint</li>
<li>python27Packages.argon2_cffi</li>
<li>python27Packages.passlib</li>
<li>python37Packages.alerta-server</li>
<li>python37Packages.ansible-kernel</li>
<li>python37Packages.argon2_cffi</li>
<li>python37Packages.batchspawner</li>
<li>python37Packages.ipympl</li>
<li>python37Packages.ipyvue</li>
<li>python37Packages.ipyvuetify</li>
<li>python37Packages.ipywidgets</li>
<li>python37Packages.jupyter</li>
<li>python37Packages.jupyter-sphinx</li>
<li>python37Packages.jupyterhub</li>
<li>python37Packages.jupyterhub-ldapauthenticator</li>
<li>python37Packages.jupyterhub-systemdspawner</li>
<li>python37Packages.jupyterhub-tmpauthenticator</li>
<li>python37Packages.jupyterlab</li>
<li>python37Packages.jupyterlab-git</li>
<li>python37Packages.jupyterlab_launcher</li>
<li>python37Packages.jupyterlab_server</li>
<li>python37Packages.lightparam</li>
<li>python37Packages.mitmproxy</li>
<li>python37Packages.nbdime</li>
<li>python37Packages.nix-kernel</li>
<li>python37Packages.notebook</li>
<li>python37Packages.notedown</li>
<li>python37Packages.oauthenticator</li>
<li>python37Packages.passlib</li>
<li>python37Packages.pg8000</li>
<li>python37Packages.pykeepass</li>
<li>python37Packages.sentry-sdk</li>
<li>python37Packages.trytond</li>
<li>python37Packages.widgetsnbextension</li>
<li>python38Packages.alerta-server</li>
<li>python38Packages.ansible-kernel</li>
<li>python38Packages.argon2_cffi</li>
<li>python38Packages.batchspawner</li>
<li>python38Packages.ipympl</li>
<li>python38Packages.ipyvue</li>
<li>python38Packages.ipyvuetify</li>
<li>python38Packages.ipywidgets</li>
<li>python38Packages.jupyter</li>
<li>python38Packages.jupyter-sphinx</li>
<li>python38Packages.jupyterhub</li>
<li>python38Packages.jupyterhub-ldapauthenticator</li>
<li>python38Packages.jupyterhub-systemdspawner</li>
<li>python38Packages.jupyterhub-tmpauthenticator</li>
<li>python38Packages.jupyterlab</li>
<li>python38Packages.jupyterlab-git</li>
<li>python38Packages.jupyterlab_launcher</li>
<li>python38Packages.jupyterlab_server</li>
<li>python38Packages.lightparam</li>
<li>python38Packages.nbdime</li>
<li>python38Packages.nix-kernel</li>
<li>python38Packages.notebook</li>
<li>python38Packages.notedown</li>
<li>python38Packages.oauthenticator</li>
<li>python38Packages.passlib</li>
<li>python38Packages.pg8000</li>
<li>python38Packages.pykeepass</li>
<li>python38Packages.sentry-sdk</li>
<li>trytond (python38Packages.trytond)</li>
<li>python38Packages.widgetsnbextension</li>
<li>qutebrowser</li>
<li>radicale (radicale3)</li>
<li>radicale2</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.jupyterhub-systemdspawner:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python37Packages.jupyterhub:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern ''npm', 'run', 'lessc', '--'' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python37Packages.nbdime:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python37Packages.pg8000:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.jupyterhub-systemdspawner:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.jupyterhub:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern ''npm', 'run', 'lessc', '--'' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python38Packages.nbdime:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.pg8000:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by tomberek** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 99932` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>ihaskell</li>
<li>python27Packages.ldaptor</li>
<li>python27Packages.privacyidea-ldap-proxy</li>
<li>python37Packages.qasm2image</li>
<li>python37Packages.skein</li>
<li>python38Packages.qasm2image</li>
<li>python38Packages.skein</li>
</ul>
</details>
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.jupyterlab-git: log was empty</li>
<li>python37Packages.nbdime: log was empty</li>
<li>python38Packages.jupyterlab-git: log was empty</li>
<li>python38Packages.nbdime: log was empty</li>
  </ul>
</details>
<details>
<summary>
128 packages built:
</summary>
<ul>
<li>cura</li>
<li>devpi-client</li>
<li>devpi-server</li>
<li>etesync-dav</li>
<li>gns3-gui</li>
<li>gns3-server</li>
<li>jupyter</li>
<li>mailman</li>
<li>mitmproxy (python38Packages.mitmproxy)</li>
<li>octoprint</li>
<li>python27Packages.argon2_cffi</li>
<li>python27Packages.passlib</li>
<li>python37Packages.Nikola</li>
<li>python37Packages.alerta-server</li>
<li>python37Packages.ansible-kernel</li>
<li>python37Packages.argon2_cffi</li>
<li>python37Packages.batchspawner</li>
<li>python37Packages.colorcet</li>
<li>python37Packages.cufflinks</li>
<li>python37Packages.datashader</li>
<li>python37Packages.dockerspawner</li>
<li>python37Packages.fastapi</li>
<li>python37Packages.hbmqtt</li>
<li>python37Packages.holoviews</li>
<li>python37Packages.hvplot</li>
<li>python37Packages.intake</li>
<li>python37Packages.ipydatawidgets</li>
<li>python37Packages.ipympl</li>
<li>python37Packages.ipyvue</li>
<li>python37Packages.ipyvuetify</li>
<li>python37Packages.ipywidgets</li>
<li>python37Packages.jupyter</li>
<li>python37Packages.jupyter-sphinx</li>
<li>python37Packages.jupyterhub</li>
<li>python37Packages.jupyterhub-ldapauthenticator</li>
<li>python37Packages.jupyterhub-systemdspawner</li>
<li>python37Packages.jupyterhub-tmpauthenticator</li>
<li>python37Packages.jupyterlab</li>
<li>python37Packages.jupyterlab_launcher</li>
<li>python37Packages.jupyterlab_server</li>
<li>python37Packages.kmapper</li>
<li>python37Packages.lightparam</li>
<li>python37Packages.mailman</li>
<li>python37Packages.mailman-hyperkitty</li>
<li>python37Packages.mitmproxy</li>
<li>python37Packages.nbclient</li>
<li>python37Packages.nbsmoke</li>
<li>python37Packages.nix-kernel</li>
<li>python37Packages.notebook</li>
<li>python37Packages.notedown</li>
<li>python37Packages.oauthenticator</li>
<li>python37Packages.papermill</li>
<li>python37Packages.passlib</li>
<li>python37Packages.pg8000</li>
<li>python37Packages.privacyidea</li>
<li>python37Packages.pykeepass</li>
<li>python37Packages.qiskit</li>
<li>python37Packages.qiskit-aer</li>
<li>python37Packages.qiskit-aqua</li>
<li>python37Packages.qiskit-ibmq-provider</li>
<li>python37Packages.qiskit-ignis</li>
<li>python37Packages.qiskit-terra</li>
<li>python37Packages.runway-python</li>
<li>python37Packages.scikit-tda</li>
<li>python37Packages.sentry-sdk</li>
<li>python37Packages.stytra</li>
<li>python37Packages.trytond</li>
<li>python37Packages.vega</li>
<li>python37Packages.widgetsnbextension</li>
<li>python38Packages.Nikola</li>
<li>python38Packages.alerta-server</li>
<li>python38Packages.ansible-kernel</li>
<li>python38Packages.argon2_cffi</li>
<li>python38Packages.batchspawner</li>
<li>python38Packages.colorcet</li>
<li>python38Packages.cufflinks</li>
<li>python38Packages.datashader</li>
<li>python38Packages.dockerspawner</li>
<li>python38Packages.fastapi</li>
<li>python38Packages.hbmqtt</li>
<li>python38Packages.holoviews</li>
<li>python38Packages.hvplot</li>
<li>python38Packages.intake</li>
<li>python38Packages.ipydatawidgets</li>
<li>python38Packages.ipympl</li>
<li>python38Packages.ipyvue</li>
<li>python38Packages.ipyvuetify</li>
<li>python38Packages.ipywidgets</li>
<li>python38Packages.jupyter</li>
<li>python38Packages.jupyter-sphinx</li>
<li>python38Packages.jupyterhub</li>
<li>python38Packages.jupyterhub-ldapauthenticator</li>
<li>python38Packages.jupyterhub-systemdspawner</li>
<li>python38Packages.jupyterhub-tmpauthenticator</li>
<li>python38Packages.jupyterlab</li>
<li>python38Packages.jupyterlab_launcher</li>
<li>python38Packages.jupyterlab_server</li>
<li>python38Packages.kmapper</li>
<li>python38Packages.lightparam</li>
<li>python38Packages.mailman</li>
<li>python38Packages.mailman-hyperkitty</li>
<li>python38Packages.nbclient</li>
<li>python38Packages.nbsmoke</li>
<li>python38Packages.nix-kernel</li>
<li>python38Packages.notebook</li>
<li>python38Packages.notedown</li>
<li>python38Packages.oauthenticator</li>
<li>python38Packages.papermill</li>
<li>python38Packages.passlib</li>
<li>python38Packages.pg8000</li>
<li>python38Packages.privacyidea</li>
<li>python38Packages.pykeepass</li>
<li>python38Packages.qiskit</li>
<li>python38Packages.qiskit-aer</li>
<li>python38Packages.qiskit-aqua</li>
<li>python38Packages.qiskit-ibmq-provider</li>
<li>python38Packages.qiskit-ignis</li>
<li>python38Packages.qiskit-terra</li>
<li>python38Packages.runway-python</li>
<li>python38Packages.scikit-tda</li>
<li>python38Packages.sentry-sdk</li>
<li>python38Packages.stytra</li>
<li>trytond (python38Packages.trytond)</li>
<li>python38Packages.vega</li>
<li>python38Packages.widgetsnbextension</li>
<li>qutebrowser</li>
<li>radicale (radicale3)</li>
<li>radicale2</li>
</ul>
</details>

**Review by tomberek — APPROVED** [review]
Do we want to go through `staging`?

**Comment by SuperSandro2000** [comment]
> Do we want to go through `staging`?

Python builds quite fast so this is not required.

**Pull request merged**
