### PR TITLE
openafs: 1.8.8.1 → 1.8.9pre1

### PR DESCRIPTION
**Pull request by andersk**
###### Description of changes

This is needed for new Linux kernel support.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by spacefrogg** [comment]
Please create it as an override to the stable package or as a second package. I know the pressure that comes from the slow OpenAFS release schedule from sore experience, but I am still not in favour of solely providing a beta version. At least at our place, AFS is critical infrastructure.

**Comment by spacefrogg** [comment]
@andersk Are you still interested in this PR?

**Comment by spacefrogg** [comment]
> Yes, but it seems you aren’t?

I am confused. I left clear expectations in my previous comment to which I never got a reaction.

> 
> My experience has been that OpenAFS prereleases from the stable branch are at least as reliable as the previous final releases. Ubuntu 18.04 LTS and 20.04 LTS both package OpenAFS prereleases to this day. Meanwhile, with Linux 6.1 being released imminently and [expected](https://lore.kernel.org/lkml/Yz%2FZWBeNZvKenEVM@kroah.com/) to become the next LTS kernel, it’s going to be pretty silly to ship an OpenAFS version that doesn’t even support our default kernel.

Yes, and I ride this exact problem for almost 20 years now. Every 10 or so years, my <favourite-linux-distro> leaps ahead with shiny new default kernels biting my infrastructure, because openafs development just cannot keep up with it. BUT, in those years, I also got bitten twice by messups in prereleases.

Thus my expectations: Please, go ahead and make a separate derivation for the pre-release. Just don't make it the only one available. I know, that I (and everyone else who needs to run openafs stable releases) need to take care that my servers run older kernels for some time. Well, so be it.

> (I do have to wonder, if your infrastructure is so critical that something with a prerelease label can’t be allowed on it, what it’s doing running `nixos-unstable`…?)

This confuses me completely. No one is running servers on nixos-unstable. Would we have merged this PR when you first requested it, the prerelease version would be the only one available in the current nixos release. This is exactly, what I am trying to avoid.

**Comment by andersk** [comment]
Closing in favor of #206653.

**Pull request closed without merging**
