### PR TITLE
dduper: Updated btrfs patch

### LINKED ISSUE #220681: Build failure: dduper (fast deduplication for btrfs // 22.11 channel)
### Steps To Reproduce

1. boot from 22.11 live image (plasma)
2. nix-shell -p dduper

### Build log 

```
these 3 derivations will be built:
  /nix/store/5r6x6l5627ghy7g9s7jdkggvrhh5xnfh-btrfs-progs-6.0.1.drv
  /nix/store/d3scj8as1irnd78x6sp76mx8v1w95z87-python3-3.10.8-env.drv
  /nix/store/j0n4s6wzmi86pfnhd1a5ff06a4s5kv47-dduper-0.04.drv
these 3 paths will be fetched (5.57 MiB download, 31.18 MiB unpacked):
  /nix/store/9a689z75m6s3hy609jprz599zdij9pgb-blas-3-dev
  /nix/store/fpkv5ikjh04pdk4qlw3jkd686ywx6jq0-lapack-3-dev
  /nix/store/k4wgywqvi8l9xly61vn99l4qx2c58k78-python3.10-numpy-1.23.3
copying path '/nix/store/9a689z75m6s3hy609jprz599zdij9pgb-blas-3-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/fpkv5ikjh04pdk4qlw3jkd686ywx6jq0-lapack-3-dev' from 'https://cache.nixos.org'...
building '/nix/store/5r6x6l5627ghy7g9s7jdkggvrhh5xnfh-btrfs-progs-6.0.1.drv'...
unpacking sources
unpacking source archive /nix/store/wyvf20yybrz9vvjmw3fbqpvc0nzb46ar-btrfs-progs-v6.0.1.tar.xz
source root is btrfs-progs-v6.0.1
setting SOURCE_DATE_EPOCH to timestamp 1667590324 of file btrfs-progs-v6.0.1/config/install-sh
patching sources
applying patch /nix/store/gjhhppksyzqmkdk3x2qc9ymrg6z50izs-0001-Print-csum-for-a-given-file-on-stdout.patch
patching file Makefile
Hunk #1 FAILED at 157.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
patching file cmds/commands.h
Hunk #1 succeeded at 139 with fuzz 2 (offset -1 lines).
patching file cmds/inspect.c
Hunk #1 succeeded at 698 (offset 2 lines).
patching file cmds/inspect-dump-csum.c
error: builder for '/nix/store/5r6x6l5627ghy7g9s7jdkggvrhh5xnfh-btrfs-progs-6.0.1.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/j0n4s6wzmi86pfnhd1a5ff06a4s5kv47-dduper-0.04.drv' failed to build
```

### Additional context

Fails directly.

### Notify maintainers
@Thesola10 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 22.11 (Raccoon), 22.11.1137.dac57a4eccf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(nixos): `""`
 - channels(root): `"nixos-22.11.1137.dac57a4eccf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Thanks!

### PR DESCRIPTION
**Pull request by Thesola10**
This fixes #220681

###### Description of changes

Updated the `btrfs-progs` patch in the `dduper` build derivation

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
Is this 22.11-specific? If not, this should go to master first.

**Comment by Thesola10** [comment]
Master was already fixed with an even newer patch, this is specific to 22.11

**Review by Atemu — CHANGES_REQUESTED** [review]
Result of `nixpkgs-review pr 220698` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>dduper</li>
  </ul>
</details>

**Comment by Atemu** [comment]
Disregard that, my nixpkgs-review was apparently misconfigured.

**Review by Atemu — APPROVED** [review]

**Pull request merged**
