### PR TITLE
lldb_14: fix broken python3 site-packages and lua5_3

### PR DESCRIPTION
**Pull request by patryk4815**
###### Description of changes
This should fix issue https://github.com/NixOS/nixpkgs/issues/166604
And I fixed lua install dir also :)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by patryk4815** [comment]
@ofborg build lldb_8 lldb_9 lldb_10 lldb_11 lldb_12 lldb_13 lldb_14

**Comment by LunNova** [comment]
Would it be worth adding the lua files to installCheckPhase too?

**Comment by patryk4815** [comment]
@LunNova Ok I will add :)

**Comment by LunNova** [comment]
Result of `nixpkgs-review pr 207863` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>jucipp</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>lldb (lldb_14 ,llvmPackages_14.lldb ,llvmPackages_latest.lldb)</li>
    <li>lldb_10 (llvmPackages_10.lldb)</li>
    <li>lldb_11 (llvmPackages.lldb ,llvmPackages_11.lldb)</li>
    <li>lldb_12 (llvmPackages_12.lldb)</li>
    <li>lldb_13 (llvmPackages_13.lldb)</li>
    <li>lldb_8 (llvmPackages_8.lldb ,vscode-extensions.llvm-org.lldb-vscode)</li>
    <li>lldb_9 (llvmPackages_9.lldb)</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
  </ul>
</details>

**Comment by patryk4815** [comment]
@LunNova Added lua check :)

**Review by LunNova — APPROVED** [review]

**Comment by patryk4815** [comment]
@ofborg build lldb_14

**Pull request merged**
