### PR TITLE
Add callCabal2Nix to haskell packages

### PR DESCRIPTION
**Pull request by 3noch**
This is long overdue. I see it everywhere in people's source code but it's not in nixpkgs (yet). Ref #19958.

I'm sure there all sorts of ways to improve this to make it suitable for inclusion in nixpkgs. But I wanted to get the ball rolling.

### CODE REVIEW

**Comment by 3noch** [comment]
cc @ElvishJerricco

**Comment by peti** [comment]
That function seems somewhat inferior to the `hackage2nix` function located some ~10 lines of code above it in `pkgs/development/haskell-modules/default.nix`.

**Comment by ElvishJerricco** [comment]
It's used to call packages that aren't on Hackage. For example, pulling something from github and using cabal2nix on it. I use it in the default.nix of my projects so that I don't have to keep manually doing cabal2nix on my cabal file.

**Comment by 3noch** [comment]
@peti I think you're right. I could copy `hackage2nix` and get rid of the dependency on Hackage, or I could refactor it to support both use cases. Do you have a preference?

**Comment by peti** [comment]
Re-factoring it to offer a more powerful API (i.e. one that can process local files) seems like the better solution to me.

**Comment by 3noch** [comment]
@peti What do you think of this?

**Comment by peti** [comment]
Yes, that patch looks fine! One minor nitpick: other functions use the spelling `hackage2nix`, i.e. the "nix" bit isin all lower-case, so I'd prefer the spelling `callCabal2nix` over `callCabal2Nix` for the sake of consistency. Does that make sense?

**Comment by 3noch** [comment]
@peti I noticed that myself. I'll change it.

**Comment by 3noch** [comment]
Done.

**Comment by peti** [comment]
Merged to `haskell-updates` for testing in http://hydra.nixos.org/jobset/nixpkgs/haskell-updates. This patch will make it into `master` within a day or two -- assuming that nothing breaks. :-)

**Pull request closed without merging**
