### PR TITLE
nixos/tasks/network-interfaces: Assign mac to new wlan interface instead of underlying one

### PR DESCRIPTION
**Pull request by johnjameswhitman**
###### Motivation for this change

#121398 has a longer explanation, but the gist is that the `networking.wlanInterfaces.<name>.mac` option seems intended to set the mac address on the new `<name>` interface, but currently instead sets it on the parent / underlying interface specified in `networking.wlanInterfaces.<name>.device`. This change sets the specified `mac` on the new `<name>` interface rather than the underlying one.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) (I couldn't find tests for `networking.wlanInterfaces`)
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"` (I got the following output: _No diff detected, stopping review..._).
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by rnhmjoj — CHANGES_REQUESTED** [review]
Looks good beside the test being flaky.
Also please squash the commits into a single one when you're done.

**Comment by johnjameswhitman** [comment]
Thanks for the review @rnhmjoj. QQ on running the tests...I've been doing the following from the root of the checked-out repo on my local machine:
```sh
nix-build -I nixpkgs=. nixos/tests/networking.nix --arg networkd false
```
Is there a better way to run the tests, and is passing `-I` necessary?

**Comment by rnhmjoj** [comment]
The `-I` flag is not necessary, but the command is correct.
Alternatively, you can use of the `nixosTests` attribute and run just this test case:

`nix-build -A nixosTests.networking.scripted.wlanInterface`

**Comment by johnjameswhitman** [comment]
@rnhmjoj this is my first commit to nixpkgs, so it looks like I need approval -- are you able to do that or is there someone else I can tag?

**Comment by rnhmjoj** [comment]
The approval thing is just for running the CI scripts, but yes I have commit access.

Can you squash the commits into a single one? If you've never done this before:

1. First, clean up the history (especially get rid of the merge commits, which will otherwise mess up the next operation) with `git rebase master`
2. Squash your commits into a single one with `git rebase HEAD~5`.
    1. Your text editor will come up, replace the word `pick` with `squash` in all but the first line.
    2. Replace `pick` with `reword` in the first line.
    3. Save and quit.
3. The editor will open again, this time prompting to change the commit message. I'd give it the same title as of the pull request, but try to keep it under 50 characters, otherwise it will be cut and the overflow put into the description.

**Review by rnhmjoj — APPROVED** [review]

**Comment by rnhmjoj** [comment]
Thank you!

**Pull request merged**
