### PR TITLE
python3Packages.preprocess-cancellation: fix build

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
closes #171190 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by zhaofengli — APPROVED** [review]
I'm fine either way. If you want to throw a PR upstream go ahead.

**Comment by dotlambda** [comment]
Btw, the version information is missing: `result/lib/python3.9/site-packages/preprocess_cancellation-0.0.0.dist-info`.

**Comment by dotlambda** [comment]
> I'm fine either way. If you want to throw a PR upstream go ahead.

It's your call, you're the maintainer.

**Comment by zhaofengli** [comment]
> Btw, the version information is missing: `result/lib/python3.9/site-packages/preprocess_cancellation-0.0.0.dist-info`.

That's what I meant when I said that PEP 621 metadata needs to be added in #171190. To have a fully "correct" build with setuptools, you also need to add the dependencies to pyproject.toml.

**Review by zhaofengli — CHANGES_REQUESTED** [review]
~~Just tested, and this PR produces an empty package that's not usable. After you fix it, we should probably have a `pythonImportsCheck`.~~

Nevermind, I had some other stray changes. Please ignore this.

**Comment by dotlambda** [comment]
> > Btw, the version information is missing: `result/lib/python3.9/site-packages/preprocess_cancellation-0.0.0.dist-info`.
> 
> This needs to be fixed

I honestly don't understand what the problem is: https://github.com/kageurufu/cancelobject-preprocessor/blob/8f717dc1595638338ba41f37ee99a2946ee48751/pyproject.toml#L3

**Comment by zhaofengli** [comment]
> I honestly don't understand what the problem is: https://github.com/kageurufu/cancelobject-preprocessor/blob/8f717dc1595638338ba41f37ee99a2946ee48751/pyproject.toml#L3

It's Poetry-specific metadata, not PEP 621 metadata read by setuptools. Add the following to `pyproject.toml` and it results in `preprocess_cancellation-0.2.0.dist-info`:

```
[project]
name = "preprocess_cancellation"
version = "0.2.0"
```

**Comment by dotlambda** [comment]
So the synonyms listed under https://peps.python.org/pep-0621/#version don't work?

**Comment by zhaofengli** [comment]
> So the synonyms listed under https://peps.python.org/pep-0621/#version don't work?

I think those are mentioned as background for standardization. Setuptools understands its own `[tool.setuptools]` in previous versions.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 171200` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>moonraker</li>
<li>python310Packages.preprocess-cancellation</li>
<li>python39Packages.preprocess-cancellation</li>
</ul>
</details>

**Pull request merged**
