### PR TITLE
emacsPackages.mu4e: init at 1.10.7

### PR DESCRIPTION
**Pull request by jian-lin**
## Description of changes
Please see commit messages for more info.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Looks very good, but I currently do not have time to check it out. Anyone else to try it out?

**Comment by chvp** [comment]
> Looks very good, but I currently do not have time to check it out. Anyone else to try it out?

I'm planning on it this evening.

**Comment by azazak123** [comment]
Hello! I am not entirely sure why my review was requested. Unfortunately, I barely have any knowledge of emacs and its packages. However, I have tested PR with nixpkgs-review, and I hope it will be useful.

Result of `nixpkgs-review pr 253438` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>emacsPackages.mu4e</li>
    <li>lbdb</li>
    <li>mu</li>
    <li>mu.mu4e</li>
  </ul>
</details>

**Comment by jian-lin** [comment]
Oops, my bad.  I requested three maintainers of `mu` for review and after I typed antono GitHub suggested you.  Actually, that maintainer should be @antono.

**Review by chvp — APPROVED** [review]
Tried this out, works nicely.

**Pull request merged**
