### PR TITLE
[Backport release-22.11] qtile: add more options to NixOS module and expose unwrapped package

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

Manual backport of #220450 to `release-22.11`, as requested in https://github.com/NixOS/nixpkgs/pull/220450#issuecomment-1485005891

Qtile version was not bumped and the change should be backwards compatible for any existing uses of `pkgs.qtile`, `pkgs.qtile.unwrapped`, and the `services.xserver.windowManager.qtile` NixOS options

cc: @arjan-s 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ivan** [comment]
This broke the manual in the release-22.11 branch:

```
at@dev:/home/at/code/system/nixpkgs/nixos/doc/manual# make
nix-build ../../release.nix \
        --attr manualGeneratedSources.x86_64-linux \
        --out-link ./generated
[...]
building '/nix/store/52d62nbfs1haf5c1p4cjxwps73fd2x8a-options.json.drv'...
Traceback (most recent call last):
  File "/nix/store/vqb0s6db0cqm8k5z70nz97sap21zdf8i-mergeJSON.py", line 206, in convertMD
    option['description'] = convertString(name, option['description']['text'])
  File "/nix/store/vqb0s6db0cqm8k5z70nz97sap21zdf8i-mergeJSON.py", line 190, in convertString
    rendered = md(text)
  File "/nix/store/9gqz4917549knl2r140mqfgjbghim04r-python3-minimal-3.10.9-env/lib/python3.10/site-packages/mistune/markdown.py", line 65, in __call__
    return self.parse(s)
  File "/nix/store/9gqz4917549knl2r140mqfgjbghim04r-python3-minimal-3.10.9-env/lib/python3.10/site-packages/mistune/markdown.py", line 50, in parse
    result = self.block.render(tokens, self.inline, state)
  File "/nix/store/9gqz4917549knl2r140mqfgjbghim04r-python3-minimal-3.10.9-env/lib/python3.10/site-packages/mistune/block_parser.py", line 274, in render
    return inline.renderer.finalize(data)
  File "/nix/store/vqb0s6db0cqm8k5z70nz97sap21zdf8i-mergeJSON.py", line 127, in finalize
    return "".join(data)
  File "/nix/store/9gqz4917549knl2r140mqfgjbghim04r-python3-minimal-3.10.9-env/lib/python3.10/site-packages/mistune/block_parser.py", line 293, in _iter_render
    yield method(children)
  File "/nix/store/vqb0s6db0cqm8k5z70nz97sap21zdf8i-mergeJSON.py", line 60, in not_supported
    raise NotImplementedError("md node not supported yet", name, args, **kwargs)
NotImplementedError: ('md node not supported yet', 'block_html', ('<option>x11</option> or <option>wayland</option>.',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/vqb0s6db0cqm8k5z70nz97sap21zdf8i-mergeJSON.py", line 333, in <module>
    json.dump(convertMD(unpivot(options)), fp=sys.stdout)
  File "/nix/store/vqb0s6db0cqm8k5z70nz97sap21zdf8i-mergeJSON.py", line 217, in convertMD
    raise Exception(f"Failed to render option {name}: {str(e)}")
Exception: Failed to render option services.xserver.windowManager.qtile.backend: ('md node not supported yet', 'block_html', ('<option>x11</option> or <option>wayland</option>.',))
error: builder for '/nix/store/52d62nbfs1haf5c1p4cjxwps73fd2x8a-options.json.drv' failed with exit code 1;
       last 10 log lines:
       > NotImplementedError: ('md node not supported yet', 'block_html', ('<option>x11</option> or <option>wayland</option>.',))
       >
       > During handling of the above exception, another exception occurred:
       >
       > Traceback (most recent call last):
       >   File "/nix/store/vqb0s6db0cqm8k5z70nz97sap21zdf8i-mergeJSON.py", line 333, in <module>
       >     json.dump(convertMD(unpivot(options)), fp=sys.stdout)
       >   File "/nix/store/vqb0s6db0cqm8k5z70nz97sap21zdf8i-mergeJSON.py", line 217, in convertMD
       >     raise Exception(f"Failed to render option {name}: {str(e)}")
       > Exception: Failed to render option services.xserver.windowManager.qtile.backend: ('md node not supported yet', 'block_html', ('<option>x11</option> or <option>wayland</option>.',))
       For full logs, run 'nix log /nix/store/52d62nbfs1haf5c1p4cjxwps73fd2x8a-options.json.drv'.
error: 1 dependencies of derivation '/nix/store/vk899pgq8gxll7mp65wn34vm8hdk2237-options.xml.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lnp3z71jpnljr0d2z1lz7b51x9saifa9-options-docbook.xml.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ff7f40n6lk8y9gbxx6x7fjj4203srm8d-generated-docbook.drv' failed to build
make: *** [Makefile:28: generated] Error 1
```

**Comment by lilyinstarlight** [comment]
Apparently ofborg only evaluates the manual build. Not actually try to build it. Ugh, I'll fix

**Comment by lilyinstarlight** [comment]
Should be fixed by #224143 and I've made a note to test manual build for PRs with NixOS option changes in the future

**Comment by lilyinstarlight** [comment]
Also it looks like docs are supposed to get built by a GitHub Action for all PRs ... targetting `master` (I knew I thought they were supposed to be built on PRs)

I'll probably fix that Action to build for PRs targetting `release-*` branches too so that we don't have trouble like this again

**Pull request merged**
