### PR TITLE
matrix-appservice-irc: 0.38.0 -> 1.0.0

### PR DESCRIPTION
**Pull request by gdamjan**
* This release drops support for Node 16. The minimum required version is now 18+.
* Moved from NPM to Yarn

https://github.com/matrix-org/matrix-appservice-irc/releases/tag/1.0.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gdamjan** [comment]
there are some optimizations possible, according to the [Dockerfile](https://github.com/matrix-org/matrix-appservice-irc/blob/1.0.0/Dockerfile#L34-L40) once the project is built, only `./lib/`, `./public/` (for the widget), `package.json`, `app.js` and `config.schema.yml` are needed.

ps.
do we need to add `libfreebindfree.so` too?

**Comment by h7x4** [comment]
You have a bit of a weird error here. I think it's the following:
Even though it looks better to reuse `pname` for the source fetcher, `mkYarnPackage` uses the source' `package.json` to define a bunch of settings, and it creates a weird catch 22 loop. I would just change it back to not reusing pname in the source. It's probably the easiest way to avoid this, unless you want to go mess with https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/yarn2nix-moretea/yarn2nix/default.nix

**Comment by gdamjan** [comment]
we were discussing on `#nodejs:nixos.org` about a different approach, using `stdenv.mkDerivation` directly and forgoing `mkYarnPackage`.

an example is here
https://gist.github.com/gdamjan/08901abe49baadf083034e93ed32ccbe

Let's discuss which is better!?

**Comment by gdamjan** [comment]
> I would just change it back to not reusing pname in the source.

did that change, but didn't help with the ofborg-eval failure. I was explained that `yarnLock = src + "/yarn.lock";` creates an IFD (import from derivation) and that's a no-no.

**Comment by gdamjan** [comment]
overriden by #246188

**Pull request closed without merging**
