### PR TITLE
haskellPackages.cryptonite: fix compilation with avx

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
I think cryptonite is already building on the `haskell-updates` branch.  Is it building right now without avx, is that why this patch is needed?  Do you have a personal overlay where you enable avx for all of nixpkgs?

**Comment by SuperSandro2000** [comment]
> Is it building right now without avx, is that why this patch is needed? Do you have a personal overlay where you enable avx for all of nixpkgs?

yes and yes. I am setting nixpkgs.config.gcc.arch to skyflake and in all haskell packages I am using this was the only build failure.

**Comment by cdepillabout** [comment]
I'd like to wait until the cryptonite maintainer replies to https://github.com/haskell-crypto/cryptonite/pull/373 before merging this in.

It is not clear to me the ramifications of this change (or why it was changed originally).

**Comment by SuperSandro2000** [comment]
@trofi already commented on the idea of the fix a while ago https://github.com/haskell-crypto/cryptonite/issues/347#issuecomment-855393136

**Comment by cdepillabout** [comment]
As far as I can tell, trofi isn't a maintainer of cryptonite?

**Comment by cdepillabout** [comment]
I don't feel comfortable merging a change to a widely-used crypto library in Haskell without at least the upstream maintainer commenting on it.

Although cryptonite is somewhat known for having slow reviews of PRs...

**Comment by SuperSandro2000** [comment]
@cdepillabout so nothing really happened in two months and there are more and more people that need this patch. What do we do?

**Comment by sternenseemann** [comment]
> @cdepillabout so nothing really happened in two months and there are more and more people that need this patch. What do we do?

A lot of upstream projects don't include a patch for something downstream users “need” – our patching should be within reason.

**Comment by SuperSandro2000** [comment]
What are we doing now that the repository is archived for a crypto those security relevant package?

**Comment by someplaceguy** [comment]
> What are we doing now that the repository is archived for a crypto those security relevant package?

It probably makes sense to replace cryptonite with [crypton](https://github.com/kazu-yamamoto/crypton), which is a fork that appears to be maintained:

https://old.reddit.com/r/haskell/comments/14245q8/crypton_is_forked_from_cryptonite_with_the/jn36k6s/

Although crypton probably still has the same issue as cryptonite, so I guess a new issue should be filed.

**Comment by sternenseemann** [comment]
Hackage has the ability to deal with an unmaintained package. We'll just have to see what happens.

**Pull request closed without merging**
