### PR TITLE
ibus-engines.table: 1.9.20 -> 1.9.21

### PR DESCRIPTION
**Pull request by laMudri**
###### Motivation for this change
Regular update, except for the change to config format mentioned in the release notes.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Needs rebasing

**Comment by laMudri** [comment]
Is there a practical way to do this with changes to the changelog?

**Comment by joachifm** [comment]
IMO it makes sense to make these changes separately

**Comment by laMudri** [comment]
Which changes, and how could they be separate? The update is a fairly major one, which requires the note in the changelog. It doesn't make sense to separate them.

**Comment by joachifm** [comment]
I took your question to mean that you wanted a way to avoid conflicts.  If you insist on keeping the changes in the same commit, there appears to be no way around resolving the conflict, i.e. rebase ...

**Comment by laMudri** [comment]
Splitting this into two commits isn't going to change the fact that it's vulnerable to conflicts in the release notes. I'd be happy to rebase, but won't that create a new commit each time I do? If the extra commits are fine, I'll just do it.

**Comment by joachifm** [comment]
The rebase creates a new changeset, so does not entail superflous commits (perhaps you're thinking of merging master into the PR branch?).  You will need to force-push the branch after rebasing, however.

I generally disagree that you necessarily need to check in both the bump and the changelog to master at the same time.  The changelog pertains to the next NixOS release; to my mind, preparing that changelog is a separate concern from ordinary package bumps.
People running NixOS from random checkouts must be expected to read the git log (which I think is the appropriate medium for incompatibility notices).  In that sense, splitting things up does help, because it doesn't block updating a package due to conflicts in (what I consider) an unrelated piece of the repo (the NixOS changelog).

If you want to solve the underlying problem of incompatible edits, maybe propose per-package changelogs/warnings or something.  Some mechanism for delivering important info pertaining to package updates to end-users apart from the git log would be great, but that seems outside the scope of this PR.

**Comment by laMudri** [comment]
Aah, okay, I understand what you're intending now. I'll make those changes to this PR shortly...

**Comment by laMudri** [comment]
Sorry, I didn't test this thoroughly enough. I suggest reverting, unless a quick fix for #56621 can be done.

**Comment by joachifm** [comment]
@laMudri if a short-term fix turns out to be impossible, please submit a revert PR & I'll be happy to merge it. I suppose it needs to be reverted from the upcoming release branch as well (I've not checked if it's in there)

**Comment by jtojnar** [comment]
Is it just executables (no loadable modules)? Then adding `wrapGAppsHook` should work.

**Comment by laMudri** [comment]
@jtojnar It is just executables, but I tried adding `wrapGAppsHook` to `nativeBuildInputs` but it didn't solve the issue. Possibly `gconf` is involved too, though it's difficult to find the time to work it out right now.

**Comment by jtojnar** [comment]
Is the error still the same? I can see that adding `wrapGAppsHook` to `nativeBuildInputs` includes the GSettings schema path in the wrapper and that there are `gschemas.compiled` so everything looks fine.

**Pull request merged**
