### PR TITLE
plaso: init at 20230311

### PR DESCRIPTION
**Pull request by JayRovacsek**
This pull request includes a range of dependencies as new python package additions to support plaso deployment at most recent versions.
Further to these packages, a minor fix has been applied against `pyxattr` so that it may be built on darwin hosts successfully

###### Description of changes

Plaso, or super timeline all the things, is a Python-based engine used by several tools for automatic creation of timelines. Plaso default behavior is to create super timelines but it also supports creating more [targeted timelines](http://blog.kiddaland.net/2013/02/targeted-timelines-part-i.html).
Homepage: https://github.com/log2timeline/plaso

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [X] aarch64-linux
  - [X] x86_64-darwin
  - [X] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  -  [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests) - a small number of tests/checks are disabled but limited in scope for this pull request
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. (`x86_64-linux`, `aarch64-darwin` and `aarch64-linux`. `x86_64-darwin` is pending)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Alizter** [comment]
Result of `nixpkgs-review pr 224579` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>194 packages built:</summary>
  <ul>
    <li>bup</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>diffoscopeMinimal</li>
    <li>diffoscopeMinimal.dist</li>
    <li>diffoscopeMinimal.man</li>
    <li>git-annex (haskellPackages.git-annex)</li>
    <li>git-annex-metadata-gui</li>
    <li>git-annex-metadata-gui.dist</li>
    <li>git-annex.doc (haskellPackages.git-annex.doc)</li>
    <li>glusterfs</li>
    <li>libvmi</li>
    <li>python310Packages.acstore</li>
    <li>python310Packages.acstore.dist</li>
    <li>python310Packages.artifacts</li>
    <li>python310Packages.artifacts.dist</li>
    <li>python310Packages.dfdatetime</li>
    <li>python310Packages.dfdatetime.dist</li>
    <li>python310Packages.dfvfs</li>
    <li>python310Packages.dfvfs.dist</li>
    <li>python310Packages.dfwinreg</li>
    <li>python310Packages.dfwinreg.dist</li>
    <li>python310Packages.dtfabric</li>
    <li>python310Packages.dtfabric.dist</li>
    <li>python310Packages.flor</li>
    <li>python310Packages.flor.dist</li>
    <li>python310Packages.git-annex-adapter</li>
    <li>python310Packages.git-annex-adapter.dist</li>
    <li>python310Packages.libbde-python</li>
    <li>python310Packages.libbde-python.dist</li>
    <li>python310Packages.libcreg-python</li>
    <li>python310Packages.libcreg-python.dist</li>
    <li>python310Packages.libesedb-python</li>
    <li>python310Packages.libesedb-python.dist</li>
    <li>python310Packages.libevt-python</li>
    <li>python310Packages.libevt-python.dist</li>
    <li>python310Packages.libevtx-python</li>
    <li>python310Packages.libevtx-python.dist</li>
    <li>python310Packages.libewf-python</li>
    <li>python310Packages.libewf-python.dist</li>
    <li>python310Packages.libfsapfs-python</li>
    <li>python310Packages.libfsapfs-python.dist</li>
    <li>python310Packages.libfsext-python</li>
    <li>python310Packages.libfsext-python.dist</li>
    <li>python310Packages.libfsfat-python</li>
    <li>python310Packages.libfsfat-python.dist</li>
    <li>python310Packages.libfshfs-python</li>
    <li>python310Packages.libfshfs-python.dist</li>
    <li>python310Packages.libfsntfs-python</li>
    <li>python310Packages.libfsntfs-python.dist</li>
    <li>python310Packages.libfsxfs-python</li>
    <li>python310Packages.libfsxfs-python.dist</li>
    <li>python310Packages.libfvde-python</li>
    <li>python310Packages.libfvde-python.dist</li>
    <li>python310Packages.libfwnt-python</li>
    <li>python310Packages.libfwnt-python.dist</li>
    <li>python310Packages.libfwsi-python</li>
    <li>python310Packages.libfwsi-python.dist</li>
    <li>python310Packages.liblnk-python</li>
    <li>python310Packages.liblnk-python.dist</li>
    <li>python310Packages.libluksde-python</li>
    <li>python310Packages.libluksde-python.dist</li>
    <li>python310Packages.libmodi-python</li>
    <li>python310Packages.libmodi-python.dist</li>
    <li>python310Packages.libmsiecf-python</li>
    <li>python310Packages.libmsiecf-python.dist</li>
    <li>python310Packages.libolecf-python</li>
    <li>python310Packages.libolecf-python.dist</li>
    <li>python310Packages.libphdi-python</li>
    <li>python310Packages.libphdi-python.dist</li>
    <li>python310Packages.libqcow-python</li>
    <li>python310Packages.libqcow-python.dist</li>
    <li>python310Packages.libregf-python</li>
    <li>python310Packages.libregf-python.dist</li>
    <li>python310Packages.libscca-python</li>
    <li>python310Packages.libscca-python.dist</li>
    <li>python310Packages.libsigscan-python</li>
    <li>python310Packages.libsigscan-python.dist</li>
    <li>python310Packages.libsmdev-python</li>
    <li>python310Packages.libsmdev-python.dist</li>
    <li>python310Packages.libsmraw-python</li>
    <li>python310Packages.libsmraw-python.dist</li>
    <li>python310Packages.libvhdi-python</li>
    <li>python310Packages.libvhdi-python.dist</li>
    <li>python310Packages.libvmdk-python</li>
    <li>python310Packages.libvmdk-python.dist</li>
    <li>python310Packages.libvsgpt-python</li>
    <li>python310Packages.libvsgpt-python.dist</li>
    <li>python310Packages.libvshadow-python</li>
    <li>python310Packages.libvshadow-python.dist</li>
    <li>python310Packages.libvslvm-python</li>
    <li>python310Packages.libvslvm-python.dist</li>
    <li>python310Packages.plaso</li>
    <li>python310Packages.plaso.dist</li>
    <li>python310Packages.pytsk3</li>
    <li>python310Packages.pytsk3.dist</li>
    <li>python310Packages.pyxattr</li>
    <li>python310Packages.pyxattr.dist</li>
    <li>python311Packages.acstore</li>
    <li>python311Packages.acstore.dist</li>
    <li>python311Packages.artifacts</li>
    <li>python311Packages.artifacts.dist</li>
    <li>python311Packages.dfdatetime</li>
    <li>python311Packages.dfdatetime.dist</li>
    <li>python311Packages.dfvfs</li>
    <li>python311Packages.dfvfs.dist</li>
    <li>python311Packages.dfwinreg</li>
    <li>python311Packages.dfwinreg.dist</li>
    <li>python311Packages.dtfabric</li>
    <li>python311Packages.dtfabric.dist</li>
    <li>python311Packages.flor</li>
    <li>python311Packages.flor.dist</li>
    <li>python311Packages.git-annex-adapter</li>
    <li>python311Packages.git-annex-adapter.dist</li>
    <li>python311Packages.libbde-python</li>
    <li>python311Packages.libbde-python.dist</li>
    <li>python311Packages.libcreg-python</li>
    <li>python311Packages.libcreg-python.dist</li>
    <li>python311Packages.libesedb-python</li>
    <li>python311Packages.libesedb-python.dist</li>
    <li>python311Packages.libevt-python</li>
    <li>python311Packages.libevt-python.dist</li>
    <li>python311Packages.libevtx-python</li>
    <li>python311Packages.libevtx-python.dist</li>
    <li>python311Packages.libewf-python</li>
    <li>python311Packages.libewf-python.dist</li>
    <li>python311Packages.libfsapfs-python</li>
    <li>python311Packages.libfsapfs-python.dist</li>
    <li>python311Packages.libfsext-python</li>
    <li>python311Packages.libfsext-python.dist</li>
    <li>python311Packages.libfsfat-python</li>
    <li>python311Packages.libfsfat-python.dist</li>
    <li>python311Packages.libfshfs-python</li>
    <li>python311Packages.libfshfs-python.dist</li>
    <li>python311Packages.libfsntfs-python</li>
    <li>python311Packages.libfsntfs-python.dist</li>
    <li>python311Packages.libfsxfs-python</li>
    <li>python311Packages.libfsxfs-python.dist</li>
    <li>python311Packages.libfvde-python</li>
    <li>python311Packages.libfvde-python.dist</li>
    <li>python311Packages.libfwnt-python</li>
    <li>python311Packages.libfwnt-python.dist</li>
    <li>python311Packages.libfwsi-python</li>
    <li>python311Packages.libfwsi-python.dist</li>
    <li>python311Packages.liblnk-python</li>
    <li>python311Packages.liblnk-python.dist</li>
    <li>python311Packages.libluksde-python</li>
    <li>python311Packages.libluksde-python.dist</li>
    <li>python311Packages.libmodi-python</li>
    <li>python311Packages.libmodi-python.dist</li>
    <li>python311Packages.libmsiecf-python</li>
    <li>python311Packages.libmsiecf-python.dist</li>
    <li>python311Packages.libolecf-python</li>
    <li>python311Packages.libolecf-python.dist</li>
    <li>python311Packages.libphdi-python</li>
    <li>python311Packages.libphdi-python.dist</li>
    <li>python311Packages.libqcow-python</li>
    <li>python311Packages.libqcow-python.dist</li>
    <li>python311Packages.libregf-python</li>
    <li>python311Packages.libregf-python.dist</li>
    <li>python311Packages.libscca-python</li>
    <li>python311Packages.libscca-python.dist</li>
    <li>python311Packages.libsigscan-python</li>
    <li>python311Packages.libsigscan-python.dist</li>
    <li>python311Packages.libsmdev-python</li>
    <li>python311Packages.libsmdev-python.dist</li>
    <li>python311Packages.libsmraw-python</li>
    <li>python311Packages.libsmraw-python.dist</li>
    <li>python311Packages.libvhdi-python</li>
    <li>python311Packages.libvhdi-python.dist</li>
    <li>python311Packages.libvmdk-python</li>
    <li>python311Packages.libvmdk-python.dist</li>
    <li>python311Packages.libvsgpt-python</li>
    <li>python311Packages.libvsgpt-python.dist</li>
    <li>python311Packages.libvshadow-python</li>
    <li>python311Packages.libvshadow-python.dist</li>
    <li>python311Packages.libvslvm-python</li>
    <li>python311Packages.libvslvm-python.dist</li>
    <li>python311Packages.plaso</li>
    <li>python311Packages.plaso.dist</li>
    <li>python311Packages.pytsk3</li>
    <li>python311Packages.pytsk3.dist</li>
    <li>python311Packages.pyxattr</li>
    <li>python311Packages.pyxattr.dist</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>qemu_xen (qemu_xen_4_15)</li>
    <li>qemu_xen.debug (qemu_xen_4_15.debug)</li>
    <li>qemu_xen.ga (qemu_xen_4_15.ga)</li>
    <li>qubes-core-vchan-xen</li>
    <li>xen (xenPackages.xen-vanilla ,xenPackages.xen_4_15-vanilla ,xen_4_15)</li>
    <li>xen-slim (xenPackages.xen-slim ,xenPackages.xen_4_15-slim ,xen_4_15-slim)</li>
  </ul>
</details>

**Comment by JayRovacsek** [comment]
Thanks @Alizter ! Would it help if I were to run the same across `aarch` linux and darwin also?
I can utilise an x86 darwin device also, it'll just take me some time to update and refresh my environment on it

**Comment by JayRovacsek** [comment]
Result of nixpkgs-review pr 224579 run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

3 packages marked as broken and skipped:
qemu_full qemu_xen qemu_xen_4_15

168 packages built:
python310Packages.acstore python310Packages.acstore.dist python310Packages.artifacts python310Packages.artifacts.dist python310Packages.dfdatetime python310Packages.dfdatetime.dist python310Packages.dfvfs python310Packages.dfvfs.dist python310Packages.dfwinreg python310Packages.dfwinreg.dist python310Packages.dtfabric python310Packages.dtfabric.dist python310Packages.flor python310Packages.flor.dist python310Packages.libbde-python python310Packages.libbde-python.dist python310Packages.libcreg-python python310Packages.libcreg-python.dist python310Packages.libesedb-python python310Packages.libesedb-python.dist python310Packages.libevt-python python310Packages.libevt-python.dist python310Packages.libevtx-python python310Packages.libevtx-python.dist python310Packages.libewf-python python310Packages.libewf-python.dist python310Packages.libfsapfs-python python310Packages.libfsapfs-python.dist python310Packages.libfsext-python python310Packages.libfsext-python.dist python310Packages.libfsfat-python python310Packages.libfsfat-python.dist python310Packages.libfshfs-python python310Packages.libfshfs-python.dist python310Packages.libfsntfs-python python310Packages.libfsntfs-python.dist python310Packages.libfsxfs-python python310Packages.libfsxfs-python.dist python310Packages.libfvde-python python310Packages.libfvde-python.dist python310Packages.libfwnt-python python310Packages.libfwnt-python.dist python310Packages.libfwsi-python python310Packages.libfwsi-python.dist python310Packages.liblnk-python python310Packages.liblnk-python.dist python310Packages.libluksde-python python310Packages.libluksde-python.dist python310Packages.libmodi-python python310Packages.libmodi-python.dist python310Packages.libmsiecf-python python310Packages.libmsiecf-python.dist python310Packages.libolecf-python python310Packages.libolecf-python.dist python310Packages.libphdi-python python310Packages.libphdi-python.dist python310Packages.libqcow-python python310Packages.libqcow-python.dist python310Packages.libregf-python python310Packages.libregf-python.dist python310Packages.libscca-python python310Packages.libscca-python.dist python310Packages.libsigscan-python python310Packages.libsigscan-python.dist python310Packages.libsmdev-python python310Packages.libsmdev-python.dist python310Packages.libsmraw-python python310Packages.libsmraw-python.dist python310Packages.libvhdi-python python310Packages.libvhdi-python.dist python310Packages.libvmdk-python python310Packages.libvmdk-python.dist python310Packages.libvsgpt-python python310Packages.libvsgpt-python.dist python310Packages.libvshadow-python python310Packages.libvshadow-python.dist python310Packages.libvslvm-python python310Packages.libvslvm-python.dist python310Packages.plaso python310Packages.plaso.dist python310Packages.pytsk3 python310Packages.pytsk3.dist python310Packages.pyxattr python310Packages.pyxattr.dist python311Packages.acstore python311Packages.acstore.dist python311Packages.artifacts python311Packages.artifacts.dist python311Packages.dfdatetime python311Packages.dfdatetime.dist python311Packages.dfvfs python311Packages.dfvfs.dist python311Packages.dfwinreg python311Packages.dfwinreg.dist python311Packages.dtfabric python311Packages.dtfabric.dist python311Packages.flor python311Packages.flor.dist python311Packages.libbde-python python311Packages.libbde-python.dist python311Packages.libcreg-python python311Packages.libcreg-python.dist python311Packages.libesedb-python python311Packages.libesedb-python.dist python311Packages.libevt-python python311Packages.libevt-python.dist python311Packages.libevtx-python python311Packages.libevtx-python.dist python311Packages.libewf-python python311Packages.libewf-python.dist python311Packages.libfsapfs-python python311Packages.libfsapfs-python.dist python311Packages.libfsext-python python311Packages.libfsext-python.dist python311Packages.libfsfat-python python311Packages.libfsfat-python.dist python311Packages.libfshfs-python python311Packages.libfshfs-python.dist python311Packages.libfsntfs-python python311Packages.libfsntfs-python.dist python311Packages.libfsxfs-python python311Packages.libfsxfs-python.dist python311Packages.libfvde-python python311Packages.libfvde-python.dist python311Packages.libfwnt-python python311Packages.libfwnt-python.dist python311Packages.libfwsi-python python311Packages.libfwsi-python.dist python311Packages.liblnk-python python311Packages.liblnk-python.dist python311Packages.libluksde-python python311Packages.libluksde-python.dist python311Packages.libmodi-python python311Packages.libmodi-python.dist python311Packages.libmsiecf-python python311Packages.libmsiecf-python.dist python311Packages.libolecf-python python311Packages.libolecf-python.dist python311Packages.libphdi-python python311Packages.libphdi-python.dist python311Packages.libqcow-python python311Packages.libqcow-python.dist python311Packages.libregf-python python311Packages.libregf-python.dist python311Packages.libscca-python python311Packages.libscca-python.dist python311Packages.libsigscan-python python311Packages.libsigscan-python.dist python311Packages.libsmdev-python python311Packages.libsmdev-python.dist python311Packages.libsmraw-python python311Packages.libsmraw-python.dist python311Packages.libvhdi-python python311Packages.libvhdi-python.dist python311Packages.libvmdk-python python311Packages.libvmdk-python.dist python311Packages.libvsgpt-python python311Packages.libvsgpt-python.dist python311Packages.libvshadow-python python311Packages.libvshadow-python.dist python311Packages.libvslvm-python python311Packages.libvslvm-python.dist python311Packages.plaso python311Packages.plaso.dist python311Packages.pytsk3 python311Packages.pytsk3.dist python311Packages.pyxattr python311Packages.pyxattr.dist

**Comment by JayRovacsek** [comment]
Result of `nixpkgs-review pr 224579` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

<details><summary>6 packages marked as broken and skipped:</summary><p>

- libvmi
- qemu_xen
- qemu_xen.ga
- qemu_xen_4_15
- qemu_xen_4_15.ga
- qubes-core-vchan-xen

</p></details>

<details><summary>10 packages failed to build:</summary><p>

- git-annex
- git-annex-metadata-gui
- git-annex-metadata-gui.dist
- git-annex.doc
- python310Packages.git-annex-adapter
- python310Packages.git-annex-adapter.dist
- python311Packages.git-annex-adapter
- python311Packages.git-annex-adapter.dist
- qemu_full
- qemu_full.ga

</p></details>

<details><summary>173 packages built:</summary><p>

- bup
- diffoscopeMinimal
- diffoscopeMinimal.dist
- diffoscopeMinimal.man
- glusterfs
- python310Packages.acstore
- python310Packages.acstore.dist
- python310Packages.artifacts
- python310Packages.artifacts.dist
- python310Packages.dfdatetime
- python310Packages.dfdatetime.dist
- python310Packages.dfvfs
- python310Packages.dfvfs.dist
- python310Packages.dfwinreg
- python310Packages.dfwinreg.dist
- python310Packages.dtfabric
- python310Packages.dtfabric.dist
- python310Packages.flor
- python310Packages.flor.dist
- python310Packages.libbde-python
- python310Packages.libbde-python.dist
- python310Packages.libcreg-python
- python310Packages.libcreg-python.dist
- python310Packages.libesedb-python
- python310Packages.libesedb-python.dist
- python310Packages.libevt-python
- python310Packages.libevt-python.dist
- python310Packages.libevtx-python
- python310Packages.libevtx-python.dist
- python310Packages.libewf-python
- python310Packages.libewf-python.dist
- python310Packages.libfsapfs-python
- python310Packages.libfsapfs-python.dist
- python310Packages.libfsext-python
- python310Packages.libfsext-python.dist
- python310Packages.libfsfat-python
- python310Packages.libfsfat-python.dist
- python310Packages.libfshfs-python
- python310Packages.libfshfs-python.dist
- python310Packages.libfsntfs-python
- python310Packages.libfsntfs-python.dist
- python310Packages.libfsxfs-python
- python310Packages.libfsxfs-python.dist
- python310Packages.libfvde-python
- python310Packages.libfvde-python.dist
- python310Packages.libfwnt-python
- python310Packages.libfwnt-python.dist
- python310Packages.libfwsi-python
- python310Packages.libfwsi-python.dist
- python310Packages.liblnk-python
- python310Packages.liblnk-python.dist
- python310Packages.libluksde-python
- python310Packages.libluksde-python.dist
- python310Packages.libmodi-python
- python310Packages.libmodi-python.dist
- python310Packages.libmsiecf-python
- python310Packages.libmsiecf-python.dist
- python310Packages.libolecf-python
- python310Packages.libolecf-python.dist
- python310Packages.libphdi-python
- python310Packages.libphdi-python.dist
- python310Packages.libqcow-python
- python310Packages.libqcow-python.dist
- python310Packages.libregf-python
- python310Packages.libregf-python.dist
- python310Packages.libscca-python
- python310Packages.libscca-python.dist
- python310Packages.libsigscan-python
- python310Packages.libsigscan-python.dist
- python310Packages.libsmdev-python
- python310Packages.libsmdev-python.dist
- python310Packages.libsmraw-python
- python310Packages.libsmraw-python.dist
- python310Packages.libvhdi-python
- python310Packages.libvhdi-python.dist
- python310Packages.libvmdk-python
- python310Packages.libvmdk-python.dist
- python310Packages.libvsgpt-python
- python310Packages.libvsgpt-python.dist
- python310Packages.libvshadow-python
- python310Packages.libvshadow-python.dist
- python310Packages.libvslvm-python
- python310Packages.libvslvm-python.dist
- python310Packages.plaso
- python310Packages.plaso.dist
- python310Packages.pytsk3
- python310Packages.pytsk3.dist
- python310Packages.pyxattr
- python310Packages.pyxattr.dist
- python311Packages.acstore
- python311Packages.acstore.dist
- python311Packages.artifacts
- python311Packages.artifacts.dist
- python311Packages.dfdatetime
- python311Packages.dfdatetime.dist
- python311Packages.dfvfs
- python311Packages.dfvfs.dist
- python311Packages.dfwinreg
- python311Packages.dfwinreg.dist
- python311Packages.dtfabric
- python311Packages.dtfabric.dist
- python311Packages.flor
- python311Packages.flor.dist
- python311Packages.libbde-python
- python311Packages.libbde-python.dist
- python311Packages.libcreg-python
- python311Packages.libcreg-python.dist
- python311Packages.libesedb-python
- python311Packages.libesedb-python.dist
- python311Packages.libevt-python
- python311Packages.libevt-python.dist
- python311Packages.libevtx-python
- python311Packages.libevtx-python.dist
- python311Packages.libewf-python
- python311Packages.libewf-python.dist
- python311Packages.libfsapfs-python
- python311Packages.libfsapfs-python.dist
- python311Packages.libfsext-python
- python311Packages.libfsext-python.dist
- python311Packages.libfsfat-python
- python311Packages.libfsfat-python.dist
- python311Packages.libfshfs-python
- python311Packages.libfshfs-python.dist
- python311Packages.libfsntfs-python
- python311Packages.libfsntfs-python.dist
- python311Packages.libfsxfs-python
- python311Packages.libfsxfs-python.dist
- python311Packages.libfvde-python
- python311Packages.libfvde-python.dist
- python311Packages.libfwnt-python
- python311Packages.libfwnt-python.dist
- python311Packages.libfwsi-python
- python311Packages.libfwsi-python.dist
- python311Packages.liblnk-python
- python311Packages.liblnk-python.dist
- python311Packages.libluksde-python
- python311Packages.libluksde-python.dist
- python311Packages.libmodi-python
- python311Packages.libmodi-python.dist
- python311Packages.libmsiecf-python
- python311Packages.libmsiecf-python.dist
- python311Packages.libolecf-python
- python311Packages.libolecf-python.dist
- python311Packages.libphdi-python
- python311Packages.libphdi-python.dist
- python311Packages.libqcow-python
- python311Packages.libqcow-python.dist
- python311Packages.libregf-python
- python311Packages.libregf-python.dist
- python311Packages.libscca-python
- python311Packages.libscca-python.dist
- python311Packages.libsigscan-python
- python311Packages.libsigscan-python.dist
- python311Packages.libsmdev-python
- python311Packages.libsmdev-python.dist
- python311Packages.libsmraw-python
- python311Packages.libsmraw-python.dist
- python311Packages.libvhdi-python
- python311Packages.libvhdi-python.dist
- python311Packages.libvmdk-python
- python311Packages.libvmdk-python.dist
- python311Packages.libvsgpt-python
- python311Packages.libvsgpt-python.dist
- python311Packages.libvshadow-python
- python311Packages.libvshadow-python.dist
- python311Packages.libvslvm-python
- python311Packages.libvslvm-python.dist
- python311Packages.plaso
- python311Packages.plaso.dist
- python311Packages.pytsk3
- python311Packages.pytsk3.dist
- python311Packages.pyxattr
- python311Packages.pyxattr.dist

</p></details>

**Comment by JayRovacsek** [comment]
Apologies for the close - was not intentional based on a branch rename

**Comment by AndersonTorres** [comment]
Can you learn how to contribute first?

Do you really think this badly written jumbo pull request minimally fits CONTRIBUTING.md as you checkmarked?

**Pull request closed without merging**
