### PR TITLE
tzdata: copy leap-seconds.list to derivation output; hare: patch tzdata's hardcoded paths

### PR DESCRIPTION
**Pull request by onemoresuza**
### tzdata

copy leap-seconds.list to derivation output

Some packages, for instance, hare, rely on the leap-seconds.list for its
timekeeping requirements[1].

[1]: https://harelang.org/distributions/

### hare

patch tzdata's hardcoded paths

Hare relies on tzdata's leap-seconds.list for timekeeping[1] [2], however, its
paths are for the FHS. This pull request patches them to be compliant
with the nix.

[1]: https://lists.sr.ht/~sircmpwn/hare-distributions/%3CCKB9HRGYXORK.A6V2HBE01VD5%40taiga%3E
[2]: https://harelang.org/distributions/

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onemoresuza** [comment]
[`ofborg-eval`](https://gist.githubusercontent.com/GrahamcOfBorg/6af0fd2dd0c3dffab197069b26631f89/raw/9b1453e7b199372b475739a27fcdfce310ab50bd/ofborg-eval-lib-tests) reports the following errors:

> error: 1 dependencies of derivation '/nix/store/cx0v7fvlp4lfp47g7vgzjbpxia302g3f-nix-2.17.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/imwqkmwjnpj8haxfmi1swlwi0l75wv3f-nix-2.18.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1cd9dxflng7n89vz2zb9xy9xpi4ypq8p-lib-path-tests.drv' failed to build
error: 2 dependencies of derivation '/nix/store/0gngv85cd440dwa9mhq77nvfq74ly6gi-nixpkgs-lib-tests-nix-2.17.1.drv' failed to build
error: 2 dependencies of derivation '/nix/store/z3rjx50n5yfbysqaldvfbp7q3swi8faj-nixpkgs-lib-tests-nix-2.18.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2b31380a0nij6mjs0g41sm6vbkx677y5-nixpkgs-lib-tests-nix-2.3.16.drv' failed to build
error: 3 dependencies of derivation '/nix/store/k3x1n2x1yy71z5kh1b3q6ak45iqjd4dk-nixpkgs-lib-tests.drv' failed to build

However, I do not see how the [addition of the leap-seconds.list file](https://github.com/NixOS/nixpkgs/pull/264922/files#diff-c9ae9a410f9eec99aa5e223364eeae5fede84eb2cf060f83794412d1b8a3bd51R62) would be able to cause them.

**Comment by onemoresuza** [comment]
But are these failed to build dependencies related to the changes introduced by
this pr or could it be just mere coincidence, @eclairevoyant?

**Comment by eclairevoyant** [comment]
due to the mass rebuilds, can you make the PR against staging?

**Comment by onemoresuza** [comment]
Sure. I'll also add myself as the maintainer for `harec`, since it was
orphaned:

https://github.com/NixOS/nixpkgs/pull/265034

**Comment by onemoresuza** [comment]
Moved the PR's base to `staging`.

**Comment by eclairevoyant** [comment]
Contributing.md has some more context on how to prevent this in the future, but this will mass ping everybody if kept open. Closing to prevent that. Please feel free to create a new PR against staging, don't reply here or mention this PR, but I'll keep an eye out for the new PR.

**Pull request closed without merging**
