### PR TITLE
[19.03] borgbackup: 1.1.9 -> 1.1.10

### PR DESCRIPTION
**Pull request by herrwiese**
###### Motivation for this change

Update to current minor version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-
conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

### CODE REVIEW

**Comment by markuskowa** [comment]
Is there a particular motivation for back porting (e.g. security issue, severe bugs)?

**Comment by herrwiese** [comment]
@markuskowa It's a bug-fix release, so it'll depend on your definition of "severe", I guess.  Somebody please explain to me the meaning of "stable release" here: Even minor-upgrade only when air is on fire?  My understanding would be that "upgrade to a more recent minor version" would be okay resp. worthwhile, as upstream might be reasonable (I wouldn't have PR'ed for a major version upgrade in most cases, though, for obvious reasons).

**Comment by markuskowa** [comment]
I guess the policy on back ports is not really fixed. The nixpkgs manual does not clarify it and the [PR for RFC 29] (https://github.com/NixOS/rfcs/pull/29/files) was closed. This one [here](https://gist.github.com/grahamc/c60578c6e6928043d29a427361634df6) may serve as a guideline. In my reading a patch level update should not be automatically back ported unless it contains security bug fixes, the present version is broken, or has bugs that impairs it functionality. Someone saying "this patch level update fixes an annoying little bug" would be good enough for me. As part of the review process it is legitimate to ask why something should be back ported.  A link to the change log (or to the original PR on master) would also help here to judge what bugs are actually fixed.

@grahamc Do you have any comment on patch level update back ports?

**Comment by herrwiese** [comment]
Okay, thanks.  The changelog is [here](https://github.com/borgbackup/borg/blob/1.1.10/docs/changes.rst#version-1110-2019-05-16).  As I'm intending to have a borg server running on the internet™, the point about hanging servers on certain extract operations _sounded_ relevant to me.  For reasons of "intend" I cannot claim to be directly affected, though.

**Comment by markuskowa** [comment]
@GrahamcOfBorg test borgbackup

**Review by markuskowa — APPROVED** [review]

**Pull request merged**
