### PR TITLE
qtpass: 1.2.1 -> 1.2.3

### PR DESCRIPTION
**Pull request by dtzWill**
Patch no longer needed (seems to be already applied, and notes mention).

###### Motivation for this change

https://github.com/IJHack/QtPass/releases/tag/v1.2.3
https://github.com/IJHack/QtPass/releases/tag/v1.2.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
do you know if it fixes the problem where entries are listed but empty once you click on them ? Anyway it's been unusable for months for me so any update is welcome.

**Comment by dtzWill** [comment]
On Thu, 21 Mar 2019 19:30:23 -0700, Matthieu Coudron <notifications@github.com> wrote:
> do you know if it fixes the problem where entries are listed but empty once you click on them ? Anyway it's been unusable for months for me so any update is welcome.

Couldn't say, don't use this actively myself!

Maybe it's stil bugged, not sure :3.

**Comment by dotlambda** [comment]
> Anyway it's been unusable for months for me so any update is welcome.

In that case, this should be backported.

**Comment by hrdinka** [comment]
Tested locally, thanks! :+1:

I'll backport it within the next day (it's currently rebuilding QT…).

@teto I never had this problem, maybe something is wrong with your config

**Comment by samueldr** [comment]
Backported

[release-19.03 89cecf30d77] qtpass: 1.2.1 -> 1.2.3
 Date: Thu Mar 21 15:13:18 2019 -0500
 2 files changed, 4 insertions(+), 22 deletions(-)

**Pull request merged**
