### PR TITLE
Provide rustc-1.0.0-beta as the default rust package

### PR DESCRIPTION
**Pull request by RumataEstor**

### CODE REVIEW

**Comment by jagajaga** [comment]
If we have beta, maybe remove alpha?

**Comment by RumataEstor** [comment]
I thought there was a reason behind two alpha versions made available, so decided not to remove any of them.

**Comment by jagajaga** [comment]
I think it's good to remove them.

**Comment by instantepiphany** [comment]
@RumataEstor Of course just after I made my own pull request I saw you had already made one. Is that patch needed for beta? rustc-1.0.0-beta compiled fine on my machine without it.

**Comment by RumataEstor** [comment]
@instantepiphany I didn't check without the patch. It may be very well not necessary. I just copied alpha2 and fixed that to build successfully on my machine.

**Comment by instantepiphany** [comment]
I don't actually know what the patch does - if it was used to fix a build error for the alphas then you could probably remove it, but if it was to fix errors when actually running the compiler with user code then it should probably stay.

**Comment by jagajaga** [comment]
So remove alpha and check working without patch. And then force push.

**Comment by instantepiphany** [comment]
@RumataEstor I will close my pull request, if you want to go ahead and remove the alpha version and try it without the patch.

**Comment by RumataEstor** [comment]
Sorry for the delay, was too busy on work.

I did remove alphas.

I took a look on the patch and and it seems like it might be needed to ensure that produced binaries don't depend on the environment they are run at. We definitely want the binaries to depend on the environment they were built against, not the one they are run in.

Therefore I don't think it is safe to remove that patch.

**Pull request merged**
