### PR TITLE
kde-frameworks: 5.94 -> 5.95

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Description of changes

There's an annoying bug in 5.94 that breaks system installed plasma themes.

Currently building.

Cc: https://github.com/NixOS/nixpkgs/pull/177027 & https://github.com/NixOS/nixpkgs/pull/173794

@hamburger1984 @teams/qt-kde

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build libreoffice-qt

**Comment by peterhoeg** [comment]
Try this with plasma 5.24 and frameworks 5.94 (or later) and notice there are no plasma themes:

```
$ plasma-apply-desktoptheme –list-themes
You have the following Plasma themes on your system:
```

While you can toggle between light and dark, the plasma desktop themes list is blank. With 5.93 you see all the system-installed plasma themes.

**Comment by SuperSandro2000** [comment]
@peterhoeg we are missing a few commits from https://github.com/NixOS/nixpkgs/pull/173794/commits

**Comment by peterhoeg** [comment]
> we are missing a few commits from <https://github.com/NixOS/nixpkgs/pull/173794/commits>

I don’t understand what you are trying to say here. Do you mean that PR 173794 is still not yet complete and additional changes are required for it to work?

**Comment by hamburger1984** [comment]
> @peterhoeg we are missing a few commits from https://github.com/NixOS/nixpkgs/pull/173794/commits
> 
> Going to merge this or the other framework PR together with the gear update.

I'm just rebasing https://github.com/NixOS/nixpkgs/pull/173794 (the plasma 5.25 beta PR) on master. It contained the updated wayland protocol version but that has already been merged into master. Is there anything else, we need here?

**Comment by hamburger1984** [comment]
> we are missing a few commits from <https://github.com/NixOS/nixpkgs/pull/173794/commits>
> I don’t understand what you are trying to say here. Do you mean that PR 173794 is still not yet complete and additional changes are required for it to work?

That PR is still in draft, because the actual 5.25 release did not happen, yet. But it is usable. I'm daily driving 5.25 beta for some time now and it's nice :-)

**Comment by peterhoeg** [comment]
> That PR is still in draft, because the actual 5.25 release did not happen, yet.

Sure, my question was regarding the “missing a few commits from” that I didn’t understand.

> But it is usable. I’m daily driving 5.25 beta for some time now and it’s nice :-)

I’ve been daily driving KDE since v4.0 - yeah, it’s gotten a lot nicer! ;-)

**Comment by SuperSandro2000** [comment]
> I don’t understand what you are trying to say here. Do you mean that PR 173794 is still not yet complete and additional changes are required for it to work?

The other PR had 7 commits and touched 11 files. I am assuming we still need those changes.

**Comment by peterhoeg** [comment]
> The other PR had 7 commits and touched 11 files. I am assuming we still need those changes.

If by “The other PR”, you are referring to 173794, then sure - that’s for plasma 5.25. This PR is for frameworks 5.95.

So yes, we need them both.

**Comment by SuperSandro2000** [comment]
🤦🏼 oh, yeah. I thought we updated the same program group here. Sorry!

**Pull request merged**
