### PR TITLE
libvirt: add qemu to PATH for libvirtd

### PR DESCRIPTION
**Pull request by erosennin**
###### Motivation for this change

`libvirtd` requires `qemu-img` to manage disk images.

If `qemu-img` is not found by `libvirtd`, attempting to create a `qcow2` image fails with this error:

```
$ cat >/tmp/vol.xml <<EOF
<volume>
  <name>test</name>
  <capacity>1000</capacity>
  <target>
    <format type="qcow2"/>
  </target>
</volume>
EOF
$ virsh -c qemu:///system vol-create --pool default --file /tmp/vol.xml
error: Failed to create vol from /tmp/vol.xml
error: internal error: creation of non-raw file images is not supported without qemu-img.
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
The ```qemu``` dependency was removed in https://github.com/NixOS/nixpkgs/pull/32370 because usually ```qemu-kvm``` is used together with ```libvirtd``` (```qemu-kvm``` package is reduced version of ```qemu``` which is able to emulate only host architecture, without tons of mips/arm/powerpc emulators included in ```qemu``` package).

If you enable libvirt by adding  ```virtualisation.libvirtd.enable = true``` into ```configuration.nix``` you'll get ```qemu-img``` on $PATH

**Comment by volth** [comment]
Although, libvirtd is having difficulties finding ```qemu-img``` even if it is on $PATH: https://github.com/NixOS/nixpkgs/issues/33246
I'll have a look

**Comment by erosennin** [comment]
How about splitting `qemu-img` into a separate package then? It does not depend on QEMU and supports almost every virtual disk format in existence. There can be so many use cases where it can be useful without QEMU.

**Comment by volth** [comment]
> How about splitting qemu-img into a separate package then?

That is a good idea too, ```qemu-img``` is used by some nix tools too, which do not require full ```qemu```

Regarding the ```libvirtd``` case: it seems redundant and confusing that the $PATH is constructed in two places - in the wrapper and in the module, the wrapper could be completely removed and ```[ iptables iproute pmutils numad numactl ]``` moved to the module.

**Comment by volth** [comment]
@erosennin may we close it in favor of a simple fix https://github.com/NixOS/nixpkgs/pull/34052 and postpone the big refactoring (say until upgrade to libvirt-4.0.0 which has been released today - it would require some testing anyway) ?

**Comment by erosennin** [comment]
@volth Sure.

**Pull request closed without merging**
