### PR TITLE
minimal-bootstrap.musl: init at 1.2.4

### PR DESCRIPTION
**Pull request by emilytrau**
## Description of changes

I've spent probably a week of work trying to get glibc 2.16 to build and have ended up unsuccessful due to the age and complexity of the build system. After finally giving up and trying musl the build pretty much worked instantly >.>. I think it might be necessary to give up on a glibc bootstrap and switch. Future work can go back and replace glibc 2.2 with an older version of musl and remove some of the hacks that it caused.

Related #227914

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
I think that if at the end we end up with bootstrap tools that can be plugged in to the existing stdenv bootstrap then musl should be ok.

**Comment by emilytrau** [comment]
To clarify I'd like to switch to using musl internally in minimal-bootstrap. If the final bootstrap-tools artifact will require glibc for compatibility that can be added too.

**Comment by Artturin** [comment]
👍 Thats what I meant

**Comment by Ericson2314** [comment]
Actually I think is better. I don't think we should have libraries in the bootstrap tools; only statically linked tools. For example, the fist thing we should build is libgcc/compiler-rt. This will work with my longterm goal of making the native and cross boostrapping match.

**Pull request merged**
