### PR TITLE
oraclejdk: remove redundant asserts

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

remove redundant asserts as discussed in https://github.com/NixOS/nixpkgs/pull/32314
@dezgeg

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg eval

**Comment by Mic92** [comment]
do you know where the evaluation errors are coming from?

**Comment by volth** [comment]
a bug in CI script?

**Comment by dezgeg** [comment]
````
anonymous function at /var/lib/gc-of-borg/.nix-test-rs/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/grahamc-zoidberg/pkgs/applications/networking/browsers/firefox/wrapper.nix:1:1 called without required argument ‘supportsJDK’
````
Firefox wrapper is actually using the `supportsJDK` variable. Probably the usage can just be removed, I think.

**Comment by grahamc** [comment]
@volth: 

> a bug in CI script?

It is super important to me to fix any bugs in the CI system as quickly as possible. It is an up-hill battle to convince people that after years of TravisCI, the current one isn't bad. If you find one, please open an issue at https://github.com/grahamc/ofborg and I'll look at it immediately.

The current problem is:

> anonymous function at pkgs/applications/networking/browsers/firefox/wrapper.nix:1:1 called without required argument ‘supportsJDK’, at lib/customisation.nix:74:12

**Pull request merged**
