### PR TITLE
fmt_8: 8.0.1 -> 8.1.1

### PR DESCRIPTION
**Pull request by Artturin**
nixpkgs-wayland waybar needs this
and nixpkgs waybar will need this

https://github.com/Alexays/Waybar/commit/36aa22189bb0c4cf5f916d89298a39ed730018b8

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
```
error: builder for '/nix/store/jgq730pr61g7fajgakwjfgsj5qd0mpib-pc-ble-driver-4.1.4.drv' failed with exit code 2;
       last 10 log lines:
       >       |                               ^~~~~~~~~
       > /build/source/src/common/transport/uart_transport.cpp:318:31: error: 'sleep_for' is not a member of 'std::this_thread'
       >   318 |             std::this_thread::sleep_for(DELAY_BEFORE_READ_WRITE);
       >       |                               ^~~~~~~~~
       > make[1]: *** [CMakeFiles/Makefile2:397: CMakeFiles/nrf_ble_driver_obj_sd_api_v6.dir/all] Error 2
       > make[1]: *** [CMakeFiles/Makefile2:241: CMakeFiles/nrf_ble_driver_obj_sd_api_v3.dir/all] Error 2
       > make[2]: *** [CMakeFiles/nrf_ble_driver_obj_sd_api_v2.dir/build.make:1868: CMakeFiles/nrf_ble_driver_obj_sd_api_v2.dir/src/common/transport/uart_transport.cpp.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > make[1]: *** [CMakeFiles/Makefile2:163: CMakeFiles/nrf_ble_driver_obj_sd_api_v2.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/jgq730pr61g7fajgakwjfgsj5qd0mpib-pc-ble-driver-4.1.4.drv'.
error: 1 dependencies of derivation '/nix/store/f37cf724ngz31mvngj0absvbfsvi8gch-python3.9-pc-ble-driver-py-0.16.3.drv' failed to build
error: builder for '/nix/store/m2jyrdd6kwcna2kvshnnds63frx61398-nanodbc-2.13.0.drv' failed with exit code 2;
       last 10 log lines:
       > make[2]: *** Waiting for unfinished jobs....
       > 2 errors generated.
       > make[2]: *** [test/CMakeFiles/mysql_tests.dir/build.make:76: test/CMakeFiles/mysql_tests.dir/main.cpp.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > make[1]: *** [CMakeFiles/Makefile2:624: test/CMakeFiles/vertica_tests.dir/all] Error 2
       > make[1]: *** [CMakeFiles/Makefile2:468: test/CMakeFiles/postgresql_tests.dir/all] Error 2
       > make[1]: *** [CMakeFiles/Makefile2:390: test/CMakeFiles/mysql_tests.dir/all] Error 2
       > make[1]: *** [CMakeFiles/Makefile2:546: test/CMakeFiles/sqlite_tests.dir/all] Error 2
       > make[1]: *** [CMakeFiles/Makefile2:312: test/CMakeFiles/mssql_tests.dir/all] Error 2
       > make: *** [Makefile:146: all] Error 2
       For full logs, run 'nix log /nix/store/m2jyrdd6kwcna2kvshnnds63frx61398-nanodbc-2.13.0.drv'.
error: 1 dependencies of derivation '/nix/store/771jyc47wvcar1l3lg40f6n69rbyyjx7-irods-4.2.11.drv' failed to build
error: 2 dependencies of derivation '/nix/store/akinfswbr63fgx6jnclp3cdbqb34jhk8-irods-icommands-4.2.11.drv' failed to build
error: builder for '/nix/store/1pik0gq5hqy2s6ijqmvks9wawjapbph4-hal-hardware-analyzer-3.3.0.drv' failed with exit code 1;
       last 10 log lines:
       > [131/722] Building CXX object plugins/vhdl_parser/CMakeFiles/vhdl_parser.dir/src/vhdl_parser.cpp.o
       > /build/source/plugins/vhdl_parser/src/vhdl_parser.cpp: In member function 'bool hal::VHDLParser::construct_netlist(hal::VHDLEntity&)':
       > /build/source/plugins/vhdl_parser/src/vhdl_parser.cpp:1290:37: warning: loop variable 'it' creates a copy from type 'const std::pair<const std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >' [-Wrange-loop-construct]
       >  1290 |                     for (const auto it : slave_net->get_data_map())
       >       |                                     ^~
       > /build/source/plugins/vhdl_parser/src/vhdl_parser.cpp:1290:37: note: use reference type to prevent copying
       >  1290 |                     for (const auto it : slave_net->get_data_map())
       >       |                                     ^~
       >       |                                     &
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/1pik0gq5hqy2s6ijqmvks9wawjapbph4-hal-hardware-analyzer-3.3.0.drv'.
error: builder for '/nix/store/mgg736l4nip46cclq74fdvhy19y52i69-openroad-2.0.drv' failed with exit code 2;
       last 10 log lines:
       > [ 85%] Linking CXX static library psm.a
       > cd /build/source/build/src/psm/src && /nix/store/glq7agqbd4fg6lmc2pwh75malh1bvdbw-cmake-3.22.3/bin/cmake -P CMakeFiles/psm.dir/cmake_clean_target.cmake
       > cd /build/source/build/src/psm/src && /nix/store/glq7agqbd4fg6lmc2pwh75malh1bvdbw-cmake-3.22.3/bin/cmake -E cmake_link_script CMakeFiles/psm.dir/link.txt --verbose=1
       > /nix/store/9izhv7bayzj8sr7m5n7c4qw1qk2fhq9s-binutils-2.38/bin/ar qc psm.a CMakeFiles/psm.dir/CMakeFiles/psm.dir/pdnsimTCL_wrap.cxx.o CMakeFiles/psm.dir/psm-tclInitVar.cc.o CMakeFiles/psm.dir/node.cpp.o CMakeFiles/psm.dir/gmat.cpp.o CMakeFiles/psm.dir/ir_solver.cpp.o CMakeFiles/psm.dir/get_power.cpp.o CMakeFiles/psm.dir/get_voltage.cpp.o CMakeFiles/psm.dir/pdnsim.cpp.o CMakeFiles/psm.dir/MakePDNSim.cpp.o
       > /nix/store/9izhv7bayzj8sr7m5n7c4qw1qk2fhq9s-binutils-2.38/bin/ranlib psm.a
       > cd /build/source/src/psm && /build/source/etc/find_messages.py > /build/source/src/psm/src/../messages.txt
       > make[2]: Leaving directory '/build/source/build'
       > [ 85%] Built target psm
       > make[1]: Leaving directory '/build/source/build'
       > make: *** [Makefile:139: all] Error 2
       For full logs, run 'nix log /nix/store/mgg736l4nip46cclq74fdvhy19y52i69-openroad-2.0.drv'.
error: 6 dependencies of derivation '/nix/store/k7sygkclizhbf2fns6jfhgn85v1yim1f-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ygx61hsab0nyd0n5y7a8n5hi9q5xyw8n-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/179584

3 packages marked as broken and skipped:
libsForQt512.plasma-vault libsForQt514.plasma-vault lizardfs

6 packages failed to build:
hal-hardware-analyzer irods irods-icommands openroad pc-ble-driver python39Packages.pc-ble-driver-py
```


Result of `nixpkgs-review pr 179584` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.plasma-vault</li>
    <li>libsForQt514.plasma-vault</li>
    <li>lizardfs</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>hal-hardware-analyzer</li>
    <li>irods</li>
    <li>irods-icommands</li>
    <li>openroad</li>
    <li>pc-ble-driver</li>
    <li>python39Packages.pc-ble-driver-py</li>
  </ul>
</details>
<details>
  <summary>68 packages built:</summary>
  <ul>
    <li>ananicy-cpp</li>
    <li>bear</li>
    <li>bottles</li>
    <li>cherrytree</li>
    <li>coeurl</li>
    <li>contour</li>
    <li>cryfs</li>
    <li>easyeffects</li>
    <li>far2l</li>
    <li>fmt_8</li>
    <li>folly</li>
    <li>furnace</li>
    <li>gerbera</li>
    <li>gnss-sdr</li>
    <li>gnuradio</li>
    <li>gnuradioMinimal (gnuradio3_9Minimal)</li>
    <li>gnuradioPackages.gnuradio (gnuradio3_9Packages.gnuradio)</li>
    <li>kodi (kodiPackages.kodi)</li>
    <li>kodi-gbm</li>
    <li>kodi-wayland</li>
    <li>kodiPackages.a4ksubtitles</li>
    <li>kodiPackages.archive_tool</li>
    <li>kodiPackages.iagl</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.inputstream-ffmpegdirect</li>
    <li>kodiPackages.inputstream-rtmp</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.kodi-platform</li>
    <li>kodiPackages.libretro</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-mgba</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>kodiPackages.netflix</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>kodiPackages.pvr-iptvsimple</li>
    <li>kodiPackages.steam-controller</li>
    <li>kodiPackages.vfs-libarchive</li>
    <li>kodiPackages.vfs-sftp</li>
    <li>libsForQt5.plasma-vault (libsForQt515.plasma-vault ,plasma5Packages.plasma-vault)</li>
    <li>mangohud</li>
    <li>mariadb_107</li>
    <li>mariadb_108</li>
    <li>micromamba</li>
    <li>mtxclient</li>
    <li>nheko</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-aer</li>
    <li>python310Packages.qiskit-finance</li>
    <li>python310Packages.qiskit-ibmq-provider</li>
    <li>python310Packages.qiskit-ignis</li>
    <li>python310Packages.qiskit-nature</li>
    <li>python310Packages.qiskit-optimization</li>
    <li>python310Packages.vowpalwabbit</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-finance</li>
    <li>python39Packages.qiskit-ibmq-provider</li>
    <li>python39Packages.qiskit-ignis</li>
    <li>python39Packages.qiskit-nature</li>
    <li>python39Packages.qiskit-optimization</li>
    <li>python39Packages.vowpalwabbit</li>
    <li>spdlog (spdlog_1)</li>
    <li>vowpal-wabbit</li>
    <li>waybar</li>
    <li>wdt</li>
    <li>yuzu-ea</li>
    <li>yuzu-mainline</li>
  </ul>
</details>


the openroad failure is new @trepetti

**Comment by trepetti** [comment]
As best I can tell, HAL, iRODS and OpenROAD all have logging functionality that depends on some behavior in spdlog compiled against fmt 8.0 regarding how checks are done on whether a type is formattable. Strange that a minor version bump would break it.

For reference the failure is: 
```
/nix/store/dhi96y231nkzg6585d4srpqd2ax28i5l-fmt-8.1.1-dev/include/fmt/core.h:1728:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
fmt-8.1.1-dev/include/fmt/core.h:1728:7: error: static assertion failed: C>
 1728 |       formattable,
      |       ^~~~~~~~~~~
```

I would not consider this blocking from the perspective of OpenROAD, since it is overdue for a version bump anyway. Will see if that solves the issue. I cannot speak for the other packages, though.

**Comment by Artturin** [comment]
Found https://github.com/gabime/spdlog/issues/2264

will you try bumping openroad? a contributor to it said
> I would recommend taking any version which shows green CI
in `https://github.com/The-OpenROAD-Project/OpenROAD/issues/205#issuecomment-972976171`

**Comment by risicle** [comment]
FWIW this _was_ a new failure for HAL.

No stable release has support for fmt 8.1 yet, so I guess I'll have to override its version.

**Pull request merged**
