### PR TITLE
nixos/infinoted: Abstract over libinfinity version

### PR DESCRIPTION
**Pull request by gkleen**
###### Motivation for this change
The NixOS service referred to `infinoted-0.6` which broke with the bump to `0.7.1`.

###### Things done
Instead of hardcoding `0.6` we now `passthru` the relevant version and use it to generate the name of the executable.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
Looks good to me, but why does this package use a different binary name for different versions?

Edit: You need to remove those 7 other commits though, they don't seem to do anything.

**Comment by pngwjpgh** [comment]
@Infinisil Upstream has the binary named differently every minor version (presumably so they can coexist in `/usr/bin` or something)

**Review by infinisil — CHANGES_REQUESTED** [review]
Needs to be a single commit

**Comment by pngwjpgh** [comment]
@Infinisil, did some aggressive squashing.

**Review by infinisil — APPROVED** [review]
I like the sound of that, LGTM :)

**Pull request merged**
