### PR TITLE
[backport] nixos-rebuild: support sudo + --target-host

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change
I'd like to use `nixos-rebuild --target-host` with normal user and sudo instead of using root. Backport that feature from master branch to release-19.09. Also bring the related and dependent commit "nixos-rebuild: Fix target-host using fish".

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by bjornfor** [comment]
Waiting for feedback / merge of https://github.com/NixOS/nixpkgs/pull/71849.

**Comment by bjornfor** [comment]
https://github.com/NixOS/nixpkgs/pull/71849 was merged, please comment if this is OK or not to backport.

**Comment by drewrisinger** [comment]
Can you link PRs that this backports? Other than #71849

**Comment by bjornfor** [comment]
I don't know an easy way to do that. (But the commits are there, what do you need the PRs for?) Also, I think by now this PR is not going to be merged. (The new release is out already.)

**Comment by drewrisinger** [comment]
I was asking for PRs to double-check that they made it to a release/approved version (i.e. that they're not on some orphaned branch and so shouldn't make their way to a release). If you're ok with this not getting backported, then please close the PR.

**Comment by bjornfor** [comment]
Github shows the branches that contain the commit (if any) just below the commit message. Or use 'git branch --contains COMMIT'.

**Pull request closed without merging**
