### PR TITLE
sublime-merge: 1116 -> 2020; sublime-merge-dev: 1115 -> 2011

### PR DESCRIPTION
**Pull request by victorluft**
###### Motivation for this change
Upstream changelogs:
[stable](https://www.sublimemerge.com/download)
[dev](https://www.sublimemerge.com/dev)

libGL was added to buildInputs/rpath as it is used in Sublime Merge 2.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zookatron** [comment]
I ran the new version through various tests on my machine and these changes look good to go! Thanks for the pull request, @victorluft . 

Not that big of a deal, but is there any reason why [the new libGL inclusion here](https://github.com/NixOS/nixpkgs/pull/88952/commits/6fa1ca2631b6a9ca0a82d68b1ad5f8768f191191#diff-db31abc09e70bc1c9c18be5b45b0d43eR43) needs to be conditional...? Is it really likely that the version is ever going to be < 2000 after this is merged in? Even if it was it doesn't seem like it would cause a problem to have libGL included anyway?

**Comment by victorluft** [comment]
Probably not; I figured there's a chance somebody might for some reason want to override with a previous version, but I'm happy to un-conditional it if preferred.

**Comment by zookatron** [comment]
I can see the logic for allowing overrides if it was a library removal or something, but since it's just the addition of a new library it shouldn't prevent anyone from overriding without issues even without the conditional. I think it's best to keep the change simple and remove the conditional.

**Comment by victorluft** [comment]
Makes sense. Done!

**Review by zookatron — APPROVED** [review]
I ran the new version through various tests on my machine and these changes look good to go!

**Pull request merged**
