### PR TITLE
[23.11] nextcloud29: init at 29.0.0, nextcloud28: 28.0.4 -> 28.0.5, nextcloud27: 27.1.8 -> 27.1.9

### PR DESCRIPTION
**Pull request by Ma27**
## Description of changes
Backport of #306595 minus breaking changes.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jtrees** [comment]
I'm a bit surprised to see NC 29 in the backport. Is that normal procedure for nixpkgs?

**Comment by Ma27** [comment]
It gives people a longer window to upgrade.
Remember that the default won't change, i.e. it remains nextcloud28 on 23.11, but you can exchange it with nextcloud29.
And backporting _new_ packages (this fits the definition IMHO) is allowed.

**Comment by risicle** [comment]
Check-cherry-picks "failure" understandable.

**Comment by Ma27** [comment]
@risicle yeah only a portion is reasonable to backport. Do you prefer to remove the 'cherry picked from'-part of the commit?

**Comment by risicle** [comment]
No I think it's fine. I have a PR #305628 to suppress hard-failures on warnings, but it has some issues of its own due to github jankiness.

**Comment by philipwilk** [comment]
image
Seems broken

**Comment by Ma27** [comment]
Which nixpkgs rev?
Also, as indicated by the error message, your data directory has uid 1000 as owner, but nextcloud seems to be 994. Why?

**Comment by philipwilk** [comment]
So I've just checked the data dir and it was indeed owned by my user instead of nextcloud, chown-ing the entire thing to nextcloud fixed it.
Bit confused why every previous version didn't complain about this but whatever.

**Pull request merged**
