### PR TITLE
haskell: added darwin frameworks for stack and halive

### PR DESCRIPTION
**Pull request by LnL7**

### CODE REVIEW

**Comment by peti** [comment]
Could you please add a comment that explains what `Cocoa` is and why it needs to be added?

**Comment by retrry** [comment]
@peti it seems that stack requires that to build on Darwin (I'm using Mac OS X 10.11)
```
In-place registering stack-0.1.6.0...
Preprocessing executable 'stack' for stack-0.1.6.0...
[1 of 2] Compiling Paths_stack      ( dist/build/autogen/Paths_stack.hs, dist/build/stack/stack-tmp/Paths_stack.o )
[2 of 2] Compiling Main             ( src/main/Main.hs, dist/build/stack/stack-tmp/Main.o )
Linking dist/build/stack/stack ...
ld: framework not found Cocoa
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
builder for ‘/nix/store/0v6015iji5045icay4yina1vm8w3g3dc-stack-0.1.6.0.drv’ failed with exit code 1
error: build of ‘/nix/store/0v6015iji5045icay4yina1vm8w3g3dc-stack-0.1.6.0.drv’ failed
```

**Comment by peti** [comment]
What bothers me is that http://hackage.haskell.org/package/stack-0.1.6.0/stack.cabal never mentions `Cocoa`, and I'd like to understand why it is required anyways during linktime.

**Comment by peti** [comment]
https://github.com/NixOS/nixpkgs/pull/10653 is probably related to this change. @pikajude, do you by any chance know what causes some Haskell packages to depend on `Cocoa` even though their Cabal file doesn't mention that library anywhere, i.e. `stack`?

**Comment by LnL7** [comment]
It's related to fsnotify for filesystem changes. I thought only halive depended on that but it looks like stack does aswell.

**Pull request merged**
