### PR TITLE
emacs: 26.3 -> 27.1

### PR DESCRIPTION
**Pull request by adisbladis**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by DamienCassou** [comment]
Result of `nixpkgs-review pr 95169` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
<br>- aerc
<br>- afew
<br>- agdaPackages.iowa-stdlib
<br>- alot (python38Packages.alot)
<br>- astroid
<br>- cedille
<br>- haskellPackages.notmuch
<br>- idutils
<br>- lieer
<br>- meli
<br>- muchsync
<br>- neomutt
<br>- notmuch
<br>- notmuch-addrlookup
<br>- python27Packages.notmuch
<br>- python37Packages.alot
<br>- python37Packages.notmuch
<br>- python38Packages.notmuch
</details>
<details>
  <summary>20 packages built:</summary>
<br>- agda (agdaPackages.agda)
<br>- agdaPackages.agda-prelude
<br>- agdaPackages.cubical
<br>- agdaPackages.standard-library
<br>- auctex
<br>- cask
<br>- cflow
<br>- cscope
<br>- emacs (emacs26)
<br>- emacs-nox (emacs26-nox)
<br>- framac
<br>- gcl
<br>- gcl_2_6_13_pre
<br>- mozart2
<br>- mu
<br>- pydb
<br>- recutils
<br>- rtags
<br>- supercollider_scel
<br>- why3
</details>

**Comment by DamienCassou** [comment]
@adisbladis This patch seems to break notmuch tests. There are some recent commits in [Notmuch repository](https://git.notmuchmail.org/git?p=notmuch;a=log) (especially those from Jonas) that could fix the issues.

**Comment by magnetophon** [comment]
Emacs 27 breaks some modes/packages.
I tried to install emacs 26, but got:
```
nix-env -iA nixos.emacs26
installing 'emacs-27.1'
```

**Comment by DamienCassou** [comment]
Result of `nixpkgs-review pr 95169` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
<br>- agdaPackages.iowa-stdlib
<br>- cedille
<br>- idutils
</details>
<details>
  <summary>35 packages built:</summary>
<br>- aerc
<br>- afew
<br>- agda (agdaPackages.agda)
<br>- agdaPackages.agda-prelude
<br>- agdaPackages.cubical
<br>- agdaPackages.standard-library
<br>- alot (python38Packages.alot)
<br>- astroid
<br>- auctex
<br>- cask
<br>- cflow
<br>- cscope
<br>- emacs (emacs26)
<br>- emacs-nox (emacs26-nox)
<br>- framac
<br>- gcl
<br>- gcl_2_6_13_pre
<br>- haskellPackages.notmuch
<br>- lieer
<br>- meli
<br>- mozart2
<br>- mu
<br>- muchsync
<br>- neomutt
<br>- notmuch
<br>- notmuch-addrlookup
<br>- pydb
<br>- python27Packages.notmuch
<br>- python37Packages.alot
<br>- python37Packages.notmuch
<br>- python38Packages.notmuch
<br>- recutils
<br>- rtags
<br>- supercollider_scel
<br>- why3
</details>

**Comment by DamienCassou** [comment]
@magnetophon: This is a bug in nixpkgs: `emacs26` is indeed Emacs 27. Please report it and CC @adisbladis.

**Comment by magnetophon** [comment]
@DamienCassou I thought this is the most appropriate place to report it.
Should I make a separate issue?

**Comment by turboMaCk** [comment]
Ah I see I'm not alone who hit this. Issue created.

**Pull request merged**
