### PR TITLE
azure-cli: 2.55.0 -> 2.56.0

### PR DESCRIPTION
**Pull request by katexochen**
## Description of changes

`azure-cli` is currently broken, likely after
https://github.com/NixOS/nixpkgs/pull/279138
https://github.com/NixOS/nixpkgs/pull/279143
(somewhat suspicious that it built on the PR?)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by katexochen** [comment]
Currently tests fail:
```
=========================== short test summary info ============================
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_cloud_is_registered - AssertionError: False is not true
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_active_cloud_name_default - AssertionError: 'AzureCloud' != 'TestCloud'
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_clouds_concurrent - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_known_clouds - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_modify_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_remove_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_switch_active_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureGermanClo...
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_with_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_without_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_list_show_preview_extension - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_preview_extension_by_default - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_update_extension_with_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
========== 12 failed, 236 passed, 3 deselected, 22 warnings in 3.67s ===========
```

**Comment by AkechiShiro** [comment]
I'm aware of these test issue however I haven't managed to find the root cause yet, reverting both PRs you mentioned allow the test to pass ?
I'll try that in order to check.

**Comment by katexochen** [comment]
> I'm aware of these test issue however I haven't managed to find the root cause yet, reverting both PRs you mentioned allow the test to pass ? I'll try that in order to check.

No, test failure seems to be caused the update.
I'v reverted the PRs on master: builds
I'v cherry-picked the update commit on top: test failure

**Comment by AkechiShiro** [comment]
@katexochen have you noticed that on master currently 2.55.0 does not build anymore ?

It seems some runtime dependencies are missing for some azure-mgmt packages.

Notably msrest. I think that's one issue.

But it's not related to the failing tests.

**Comment by katexochen** [comment]
> @katexochen have you noticed that on master currently 2.55.0 does not build anymore ?

Yes, that's the failure I mentioned in the description od this PR,  caused by the 2 mentioned PRs and fixed by the first commit of this PR.

**Comment by katexochen** [comment]
> @katexochen have you noticed that on master currently 2.55.0 does not build anymore ?

Yes, that's the failure I mentioned in the description od this PR,  caused by the 2 mentioned PRs and fixed by the first commit of this PR.

**Comment by AkechiShiro** [comment]
I can't seem to figure out the issue that is making the test failing, right now, it seems so weird.

For the same dependencies, 2.55.0 tests are passing but 2.56.0 is not, both tests are the same, how the heck ? And I doubt `azure-cli` would get released with broken tests.

I believe the `azure-cli` tests have been passing test for this release, however I can't access the detailed build logs : https://github.com/Azure/azure-cli/pull/28121/checks?check_run_id=20112571131 so I'm really not sure what's changing the behavior's result for this release.

**Comment by AkechiShiro** [comment]
I disabled the python pytests and the CLI does build and the self-test works, should we disable them for now and wait for an anwser upstream as I fear that upstream might not rely on their test but most likely the `az self-test` output.

But I need to investigate further.

What do you think about this @katexochen ?

**Comment by katexochen** [comment]
I rebased to include the changes from https://github.com/NixOS/nixpkgs/pull/281213 and added ignores for the [two test files that previously failed](https://github.com/NixOS/nixpkgs/pull/281183#issuecomment-1892560630).
azure-cli-core seems to build now, but the azure-cli self-check fails:

```
Running CLI self-test.

Loading all commands and arguments...
Error occurred loading commands!

The command failed with an unexpected error. Here is the traceback:
No module named 'azure.mgmt.compute.v2023_09_01'
Traceback (most recent call last):
  File "/nix/store/2kx3ab6hfqk5rbhk76bnliygmin7isvn-python3.11-knack-0.11.0/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/build/azure-cli-2.56.0-src/src/azure-cli/azure/cli/command_modules/profile/custom.py", line 183, in check_cli
    raise ex
  File "/build/azure-cli-2.56.0-src/src/azure-cli/azure/cli/command_modules/profile/custom.py", line 178, in check_cli
    create_invoker_and_load_cmds_and_args(cmd.cli_ctx)
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/file_util.py", line 74, in create_invoker_and_load_cmds_and_args
    invoker.commands_loader.load_arguments()
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    cmd.load_arguments()  # this loads the arguments via reflection
    ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/nix/store/2kx3ab6hfqk5rbhk76bnliygmin7isvn-python3.11-knack-0.11.0/lib/python3.11/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 282, in arguments_loader
    arguments = self.load_getter_op_arguments(self.getter_op_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 70, in load_getter_op_arguments
    op = self.get_op_handler(getter_op_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kj31f6d9d7swbl8f6981wniabmcjf4r4-python3.11-azure-cli-core-2.56.0/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/asiphbpiy2gmidfm3xbwcikayhs66289-python3-3.11.7/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.compute.v2023_09_01'
```

**Comment by katexochen** [comment]
> I disabled the python pytests and the CLI does build and the self-test works

@AkechiShiro did you just disable the pytests of `azure-cli-core`?

**Comment by AkechiShiro** [comment]
No I disabled the whole pytests for the package but we should try and disable only those the azure-cli-core and see if that still builds (it should) I think we can move forward that way, while waiting some clarification on what's going on upstream.

**Comment by katexochen** [comment]
> you're missing a bump for the az-mgmt-compute dependency that's why the self-test of the cli are failing.

Thanks, I indeed missed that (and another bump). Should work now.

> Something must be wrong with how pytests are being run.

Yes, but I still don't have a clue what's wrong with them.

**Comment by AkechiShiro** [comment]
Did you check this comment : https://github.com/Azure/azure-cli/issues/28191#issuecomment-1902879710 from upstream ?

It seems something is wrong with the pytest in Python.

**Comment by katexochen** [comment]
> Did you check this comment : https://github.com/Azure/azure-cli/issues/28191#issuecomment-1902879710 from upstream?

Saw it, but I don't get it.

**Comment by katexochen** [comment]
@AkechiShiro are those tests a blocker, or can we proceed with this PR and fix the tests when we figured it out?

**Comment by katexochen** [comment]
@AkechiShiro do you have time for a review, so we can get this merged?

**Comment by AkechiShiro** [comment]
@katexochen I'll try and find time to review it, this week-end, if I cannot, I'll let you know as soon as possible

So far, my understanding is that testing this PR shows :
- self-test of the CLI passes
- pytest are also green besides the ones that were added to be ignored.

Do you agree ?

**Comment by katexochen** [comment]
> I'll try and find time to review it, this week-end, if I cannot, I'll let you know as soon as possible

Thanks! :)

> So far, my understanding is that testing this PR shows :
> - self-test of the CLI passes
> - pytest are also green besides the ones that were added to be ignored.
> 
> Do you agree ?

Yes, exactly.

**Review by AkechiShiro — APPROVED** [review]
I did give it a try quickly and the CLI seems to work, I believe it's alright if we merge however an extra pair of eyes or just testing more thoroughly the CLI would be nice, I haven't been able to investigate further why the python tests are failing.

**Comment by malt3** [comment]
Result of `nixpkgs-review pr 281183` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>azure-cli</li>
    <li>azure-cli.dist</li>
  </ul>
</details>

**Review by malt3 — APPROVED** [review]
I tested basic functionality of the CLI including creating VMs on Linux x86_64.

**Pull request merged**
