### PR TITLE
xfce4-dev-tools: add hook properly

### PR DESCRIPTION
**Pull request by Artturin**
###### Description of changes
envHooks+= shouldn't be used

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
Trying to understand the need for this PR:

[`xfce4-dev-tools`](https://gitlab.xfce.org/xfce/xfce4-dev-tools) is a set of autoconf macros and scripts to augment app build systems. Generally it is used as a build time dependence. Therefore the `xdtEnvHook` setup hook, which  just sets the environment variable `ACLOCAL_PATH` (to take into account the macros provided by the package), is needed only at build time and should be set with `addEnvHooks "$hostOffset"`.

Is that right?

**Comment by Artturin** [comment]
> Trying to understand the need for this PR:
> 
> [`xfce4-dev-tools`](https://gitlab.xfce.org/xfce/xfce4-dev-tools) is a set of autoconf macros and scripts to augment app build systems. Generally it is used as a build time dependence. Therefore the `xdtEnvHook` setup hook, which just sets the environment variable `ACLOCAL_PATH` (to take into account the macros provided by the package), is needed only at build time and should be set with `addEnvHooks "$hostOffset"`.
> 
> Is that right?

AFAIU we use `hostOffset` because we want to add `share/aclocal` from buildInputs to `ACLOCAL_PATH`

a example
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/automake/setup-hook.sh

a commit which removed `envHooks+=`'s from nixpkgs (see also the linked PR)
https://github.com/NixOS/nixpkgs/commit/046f091e0d9853a81ce4d484a75cfa1b5fc9347d

**Comment by Ericson2314** [comment]
If the setup hook is standalone in native build inputs, then you want target offset. If it's part of another build input then you want host offset.

**Comment by romildo** [comment]
Result of `nixpkgs-review pr 173065` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>xfce.xfce4-embed-plugin</li>
    <li>xfce.xfce4-hardware-monitor-plugin</li>
    <li>xfce.xfce4-namebar-plugin</li>
    <li>xfce.xfce4_embed_plugin</li>
    <li>xfce.xfce4_hardware_monitor_plugin</li>
    <li>xfce.xfce4_namebar_plugin</li>
    <li>xmonad_log_applet_xfce</li>
  </ul>
</details>
<details>
  <summary>60 packages failed to build:</summary>
  <ul>
    <li>lightdm_gtk_greeter</li>
    <li>pragha</li>
    <li>xfce.catfish</li>
    <li>xfce.exo</li>
    <li>xfce.garcon</li>
    <li>xfce.gigolo</li>
    <li>xfce.libxfce4ui (xfce.libxfce4ui_gtk3)</li>
    <li>xfce.libxfce4util</li>
    <li>xfce.mousepad</li>
    <li>xfce.orage</li>
    <li>xfce.parole</li>
    <li>xfce.ristretto</li>
    <li>xfce.terminal (xfce.xfce4-terminal ,xfce.xfce4terminal)</li>
    <li>xfce.thunar (xfce.thunar-bare ,xfce.thunar-build ,xfce.thunarx-2-dev)</li>
    <li>xfce.thunar-archive-plugin</li>
    <li>xfce.thunar-dropbox-plugin</li>
    <li>xfce.thunar-media-tags-plugin</li>
    <li>xfce.thunar-volman (xfce.thunar_volman)</li>
    <li>xfce.tumbler</li>
    <li>xfce.xfburn</li>
    <li>xfce.xfce4-appfinder (xfce.xfce4_appfinder)</li>
    <li>xfce.xfce4-battery-plugin (xfce.xfce4_battery_plugin)</li>
    <li>xfce.xfce4-clipman-plugin (xfce.xfce4_clipman_plugin)</li>
    <li>xfce.xfce4-cpufreq-plugin (xfce.xfce4_cpufreq_plugin)</li>
    <li>xfce.xfce4-cpugraph-plugin (xfce.xfce4_cpugraph_plugin)</li>
    <li>xfce.xfce4-datetime-plugin (xfce.xfce4_datetime_plugin)</li>
    <li>xfce.xfce4-dev-tools (xfce.xfce4_dev_tools)</li>
    <li>xfce.xfce4-dict</li>
    <li>xfce.xfce4-dockbarx-plugin (xfce.xfce4_dockbarx_plugin)</li>
    <li>xfce.xfce4-eyes-plugin (xfce.xfce4_eyes_plugin)</li>
    <li>xfce.xfce4-fsguard-plugin (xfce.xfce4_fsguard_plugin)</li>
    <li>xfce.xfce4-genmon-plugin (xfce.xfce4_genmon_plugin)</li>
    <li>xfce.xfce4-i3-workspaces-plugin</li>
    <li>xfce.xfce4-mailwatch-plugin (xfce.xfce4_mailwatch_plugin)</li>
    <li>xfce.xfce4-mpc-plugin (xfce.xfce4_mpc_plugin)</li>
    <li>xfce.xfce4-netload-plugin (xfce.xfce4_netload_plugin)</li>
    <li>xfce.xfce4-notes-plugin (xfce.xfce4_notes_plugin)</li>
    <li>xfce.xfce4notifyd (xfce.xfce4-notifyd)</li>
    <li>xfce.xfce4panel (xfce.xfce4-panel ,xfce.xfce4panel_gtk3)</li>
    <li>xfce.xfce4-panel-profiles</li>
    <li>xfce.xfce4-power-manager (xfce.xfce4_power_manager ,xfce.xfce4_power_manager_gtk3)</li>
    <li>xfce.xfce4-pulseaudio-plugin (xfce.xfce4_pulseaudio_plugin)</li>
    <li>xfce.xfce4-screensaver</li>
    <li>xfce.xfce4-screenshooter</li>
    <li>xfce.xfce4-sensors-plugin (xfce.xfce4_sensors_plugin)</li>
    <li>xfce.xfce4session (xfce.xfce4-session)</li>
    <li>xfce.xfce4settings (xfce.xfce4-settings)</li>
    <li>xfce.xfce4-systemload-plugin (xfce.xfce4_systemload_plugin)</li>
    <li>xfce.xfce4taskmanager (xfce.xfce4-taskmanager)</li>
    <li>xfce.xfce4-timer-plugin (xfce.xfce4_timer_plugin)</li>
    <li>xfce.xfce4-verve-plugin (xfce.xfce4_verve_plugin)</li>
    <li>xfce.xfce4volumed_pulse (xfce.xfce4-volumed-pulse)</li>
    <li>xfce.xfce4-weather-plugin (xfce.xfce4_weather_plugin)</li>
    <li>xfce.xfce4-whiskermenu-plugin (xfce.xfce4_whiskermenu_plugin)</li>
    <li>xfce.xfce4-windowck-plugin (xfce.xfce4_windowck_plugin)</li>
    <li>xfce.xfce4-xkb-plugin (xfce.xfce4_xkb_plugin)</li>
    <li>xfce.xfconf</li>
    <li>xfce.xfdashboard</li>
    <li>xfce.xfdesktop</li>
    <li>xfce.xfwm4</li>
  </ul>
</details>

**Review by romildo — APPROVED** [review]

**Comment by Artturin** [comment]
i'll have to investigate this some more

**Comment by Artturin** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>catfish</li>
    <li>xfce.thunar-bare</li>
    <li>xfce.xfce4-embed-plugin</li>
    <li>xfce.xfce4-hardware-monitor-plugin</li>
    <li>xfce.xfce4-namebar-plugin</li>
    <li>xmonad_log_applet_xfce</li>
  </ul>
</details>
<details>
  <summary>60 packages built:</summary>
  <ul>
    <li>lightdm_gtk_greeter</li>
    <li>pragha</li>
    <li>xfce.catfish</li>
    <li>xfce.exo</li>
    <li>xfce.garcon</li>
    <li>xfce.gigolo</li>
    <li>xfce.libxfce4ui</li>
    <li>xfce.libxfce4util</li>
    <li>xfce.mousepad</li>
    <li>xfce.orage</li>
    <li>xfce.parole</li>
    <li>xfce.ristretto</li>
    <li>xfce.thunar</li>
    <li>xfce.thunar-archive-plugin</li>
    <li>xfce.thunar-dropbox-plugin</li>
    <li>xfce.thunar-media-tags-plugin</li>
    <li>xfce.thunar-volman</li>
    <li>xfce.tumbler</li>
    <li>xfce.xfburn</li>
    <li>xfce.xfce4-appfinder</li>
    <li>xfce.xfce4-battery-plugin</li>
    <li>xfce.xfce4-clipman-plugin</li>
    <li>xfce.xfce4-cpufreq-plugin</li>
    <li>xfce.xfce4-cpugraph-plugin</li>
    <li>xfce.xfce4-datetime-plugin</li>
    <li>xfce.xfce4-dev-tools</li>
    <li>xfce.xfce4-dict</li>
    <li>xfce.xfce4-dockbarx-plugin</li>
    <li>xfce.xfce4-eyes-plugin</li>
    <li>xfce.xfce4-fsguard-plugin</li>
    <li>xfce.xfce4-genmon-plugin</li>
    <li>xfce.xfce4-i3-workspaces-plugin</li>
    <li>xfce.xfce4-mailwatch-plugin</li>
    <li>xfce.xfce4-mpc-plugin</li>
    <li>xfce.xfce4-netload-plugin</li>
    <li>xfce.xfce4-notes-plugin</li>
    <li>xfce.xfce4-notifyd</li>
    <li>xfce.xfce4-panel</li>
    <li>xfce.xfce4-panel-profiles</li>
    <li>xfce.xfce4-power-manager</li>
    <li>xfce.xfce4-pulseaudio-plugin</li>
    <li>xfce.xfce4-screensaver</li>
    <li>xfce.xfce4-screenshooter</li>
    <li>xfce.xfce4-sensors-plugin</li>
    <li>xfce.xfce4-session</li>
    <li>xfce.xfce4-settings</li>
    <li>xfce.xfce4-systemload-plugin</li>
    <li>xfce.xfce4-taskmanager</li>
    <li>xfce.xfce4-terminal</li>
    <li>xfce.xfce4-timer-plugin</li>
    <li>xfce.xfce4-verve-plugin</li>
    <li>xfce.xfce4-volumed-pulse</li>
    <li>xfce.xfce4-weather-plugin</li>
    <li>xfce.xfce4-whiskermenu-plugin</li>
    <li>xfce.xfce4-windowck-plugin</li>
    <li>xfce.xfce4-xkb-plugin</li>
    <li>xfce.xfconf</li>
    <li>xfce.xfdashboard</li>
    <li>xfce.xfdesktop</li>
    <li>xfce.xfwm4</li>
  </ul>
</details>

**Comment by Artturin** [comment]
the hook is not liking cross

```
$ nix build ".#pkgsCross.aarch64-multiplatform.xfce.libxfce4util" --keep-going
libxfce4util-aarch64-unknown-linux-gnu> unpacking sources
libxfce4util-aarch64-unknown-linux-gnu> unpacking source archive /nix/store/syfqkvkqvd5yhc7l1p9m6i3d06vvwf6r-source
libxfce4util-aarch64-unknown-linux-gnu> source root is source
libxfce4util-aarch64-unknown-linux-gnu> patching sources
libxfce4util-aarch64-unknown-linux-gnu> xdtAutogenPhase
libxfce4util-aarch64-unknown-linux-gnu> /nix/store/v71fb0j342fsac86wprd55di1r32iy39-xfce4-dev-tools-aarch64-unknown-linux-gnu-4.16.0-dev/nix-support/setup-hook: line 9: /nix/store/8ngw8bkg9hy9zx22475m6cj6hc9ajafr-xfce4-dev-tools-aarch64-unknown-linux-gnu-4.16.0/bin/xdt-autogen: cannot execute binary file: Exec format error
```

**Comment by Artturin** [comment]
though thats not a regression

**Comment by romildo** [comment]
Result of `nixpkgs-review pr 173065` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>lightdm_gtk_greeter</li>
    <li>xfce.thunar-bare</li>
    <li>xfce.xfce4-embed-plugin</li>
    <li>xfce.xfce4-hardware-monitor-plugin</li>
    <li>xfce.xfce4-namebar-plugin</li>
    <li>xmonad_log_applet_xfce</li>
  </ul>
</details>
<details>
  <summary>59 packages built:</summary>
  <ul>
    <li>pragha</li>
    <li>xfce.catfish</li>
    <li>xfce.exo</li>
    <li>xfce.garcon</li>
    <li>xfce.gigolo</li>
    <li>xfce.libxfce4ui</li>
    <li>xfce.libxfce4util</li>
    <li>xfce.mousepad</li>
    <li>xfce.orage</li>
    <li>xfce.parole</li>
    <li>xfce.ristretto</li>
    <li>xfce.thunar</li>
    <li>xfce.thunar-archive-plugin</li>
    <li>xfce.thunar-dropbox-plugin</li>
    <li>xfce.thunar-media-tags-plugin</li>
    <li>xfce.thunar-volman</li>
    <li>xfce.tumbler</li>
    <li>xfce.xfburn</li>
    <li>xfce.xfce4-appfinder</li>
    <li>xfce.xfce4-battery-plugin</li>
    <li>xfce.xfce4-clipman-plugin</li>
    <li>xfce.xfce4-cpufreq-plugin</li>
    <li>xfce.xfce4-cpugraph-plugin</li>
    <li>xfce.xfce4-datetime-plugin</li>
    <li>xfce.xfce4-dev-tools</li>
    <li>xfce.xfce4-dict</li>
    <li>xfce.xfce4-dockbarx-plugin</li>
    <li>xfce.xfce4-eyes-plugin</li>
    <li>xfce.xfce4-fsguard-plugin</li>
    <li>xfce.xfce4-genmon-plugin</li>
    <li>xfce.xfce4-i3-workspaces-plugin</li>
    <li>xfce.xfce4-mailwatch-plugin</li>
    <li>xfce.xfce4-mpc-plugin</li>
    <li>xfce.xfce4-netload-plugin</li>
    <li>xfce.xfce4-notes-plugin</li>
    <li>xfce.xfce4-notifyd</li>
    <li>xfce.xfce4-panel</li>
    <li>xfce.xfce4-panel-profiles</li>
    <li>xfce.xfce4-power-manager</li>
    <li>xfce.xfce4-pulseaudio-plugin</li>
    <li>xfce.xfce4-screensaver</li>
    <li>xfce.xfce4-screenshooter</li>
    <li>xfce.xfce4-sensors-plugin</li>
    <li>xfce.xfce4-session</li>
    <li>xfce.xfce4-settings</li>
    <li>xfce.xfce4-systemload-plugin</li>
    <li>xfce.xfce4-taskmanager</li>
    <li>xfce.xfce4-terminal</li>
    <li>xfce.xfce4-timer-plugin</li>
    <li>xfce.xfce4-verve-plugin</li>
    <li>xfce.xfce4-volumed-pulse</li>
    <li>xfce.xfce4-weather-plugin</li>
    <li>xfce.xfce4-whiskermenu-plugin</li>
    <li>xfce.xfce4-windowck-plugin</li>
    <li>xfce.xfce4-xkb-plugin</li>
    <li>xfce.xfconf</li>
    <li>xfce.xfdashboard</li>
    <li>xfce.xfdesktop</li>
    <li>xfce.xfwm4</li>
  </ul>
</details>

**Review by romildo — APPROVED** [review]
Looks good. Although I do not cross compile.

**Comment by Artturin** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/199769 which will switch to makeScopeWithSplicing

**Pull request closed without merging**
