### PR TITLE
rust-bindgen-kernel: init at 0.56.0

### PR DESCRIPTION
**Pull request by a-kenji**
This PR includes an override for the `rust-bindgen` package.
This is part of an effort to include rust modules with kernel `5.20`.
This explicit version is needed for kernel compatibility currently.

More information:
- https://discourse.nixos.org/t/help-wanted-packaging-linux-kernel-with-rust-support/19988
- https://www.phoronix.com/scan.php?page=news_item&px=Rust-For-Linux-5.20-Possible
- https://github.com/blitz/nixpkgs/tree/rust-kernel
- https://github.com/Rust-for-Linux/rust-out-of-tree-module

cc @blitz 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
should it live inside linuxPackages_xx in case later kernel releases depend on different versions ?

**Comment by a-kenji** [comment]
I think that is a good idea! Are the changes what you had in mind?

**Comment by alyssais** [comment]
Thanks for your work on Rust in Linux in Nixpkgs! I think this should be drafted until we know for sure that Rust is actually even going to make it into 5.20 (i.e. until it shows up in an rc), and that it's still required.  Otherwise, it might be obsolete before it ever ends up being requir.d

**Comment by alyssais** [comment]
Rust support has now been merged upstream.  The documentation says:

> A particular version of the Rust toolchain is required. Newer versions may or may not work because the kernel depends on some unstable Rust features, for the moment.

So I think we should treat the kernel the same as Firefox and Thunderbird, which are in a similar situation.  i.e., we should try building with the latest version of Rust tools, and only repackage older versions of the tools if that runs into problems.  Once the first 6.1 rc is out, we can bump linux-testing and start trying to get Rust support working.

**Comment by a-kenji** [comment]
It seems I closed this pr a bit prematurely,
`bingen`: `v0.56.0` seems to still be a prerequisite.

**Pull request closed without merging**
