### PR TITLE
rustc: 1.36.0 -> 1.37.0

### PR DESCRIPTION
**Pull request by bkchr**
Based on https://github.com/NixOS/nixpkgs/pull/66714

###### Motivation for this change

New rust release.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
@bkchr thank you, can we have this open against ``staging``, as this is a pretty large mass rebuild, please?

**Comment by bkchr** [comment]
Okay, I will need to clean up the pr after changing the base :D

**Comment by basvandijk** [comment]
Note that `rustc-1.37` is already in staging: https://github.com/NixOS/nixpkgs/pull/66686

**Comment by bkchr** [comment]
Yeah, just saw this.. Searched github 3 times and the pr never showed up...

**Pull request closed without merging**
