### PR TITLE
[19.09] [backport] chromium: 79.0.3945.88 -> 79.0.3945.117

### PR DESCRIPTION
**Pull request by mebubo**
Backport #77299 (not yet merged to master) to 19.09.

https://chromereleases.googleblog.com/2020/01/stable-channel-update-for-desktop.html

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
Let's await #77299 having landed.

**Comment by primeos** [comment]
Update: https://github.com/NixOS/nixpkgs/pull/77299 is merged and already in `nixos-unstable` by now.

@flokli should we merge this PR first or directly test https://github.com/NixOS/nixpkgs/pull/78603? And do you know if we have a "standardized" (working) procedure for Chromium backports (e.g. are backports usually fine when they're fine on master or do we have to re-run all/some tests)?

@mebubo just a quick FYI: Please cherry-pick with the `-x` option, if possible, to reference the commit from `master`.

**Comment by primeos** [comment]
Closing this PR as I've just merged https://github.com/NixOS/nixpkgs/pull/78584 and we should therefore focus on https://github.com/NixOS/nixpkgs/pull/78603 now.

**Comment by mebubo** [comment]
> @mebubo just a quick FYI: Please cherry-pick with the `-x` option, if possible, to reference the commit from `master`.

Thanks for the hint @primeos, I'll be using it :)

**Pull request closed without merging**
