### PR TITLE
Update keepass238

### PR DESCRIPTION
**Pull request by joncojonathan**
keepass: from 2.37 to 2.38 

Deletion of unnecessary patch files.

Apologies, changes to `all-packages.nix` are also in PR https://github.com/NixOS/nixpkgs/pull/34358.  I'm not sure why it's in this PR given it's not in this commit (into a now branch).  I am not experienced enough with Git, so I don't know why this occurred or how to resolve.

###### Motivation for this change

Update to Keepass latest version.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build keepass

**Comment by disassembler** [comment]
You can run `git rebase -i master` and delete the line with the commit you don't want and save/quit the editor, then `git push -f <remote> <branch>`

**Comment by joncojonathan** [comment]
@disassembler thanks for the advice.  I've sorted that and this should now only include the 3 files I was after.

**Comment by joncojonathan** [comment]
@GrahamcOfBorg build keepass

**Comment by Mic92** [comment]
Thanks!

**Comment by svsdep** [comment]
Why that deleted patches are considered unnecessary? In the comments in package definition file it is clearly stated that without them Keepass won't find any installed plugins defined by `plugins` option.

**Comment by joncojonathan** [comment]
@svsdep - I received an error during build and asked what the error meant.  I was advised it meant the patch was no longer valid, so I removed the patch.  I'll confess to not being experienced at the language in question, or at NixOS derivations.  Clearly my actions caused a problem and for that I apologise.

**Comment by svsdep** [comment]
@joncojonathan no problem, I fixed it as I know C#. Just asked you about it cause I wanted to know the reason behind it. Patches became outdated as in 2.38 the code for loading plugins was changed a bit.

**Pull request merged**
