### PR TITLE
quaternion-git: init at 0.0.9.4-rc3

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

The whole matrix ecosystem is evolving quite quickly, so we have to introduce both the 0.4 and 0.5 releases of libqmatrixclient in order to be able to try out the new quaternion versions.

The default library version stays at 0.4.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build quaternion quaternion-git

**Comment by matthewbauer** [comment]
I think it is usually best to keep just one version of an application at a time. We usually just want released software in Nixpkgs (although exceptions are possible)

**Comment by peterhoeg** [comment]
> We usually just want released software in Nixpkgs (although exceptions are possible)

In general I agree with you. But you do have some pieces of software that move so quickly that having multiple versions makes sense. This would be one of those (imho).

**Comment by peterhoeg** [comment]
@matthewbauer , do you have strong reservations about this particular ```-git```package? If not, I'll go ahead and merge this in a few days.

**Pull request merged**
