### PR TITLE
dillinger: init at 2017-10-08 with module and minimal test

### PR DESCRIPTION
**Pull request by WilliButz**
###### Motivation for this change
Adds the markdown editor web-app [dillinger](https://dillinger.io)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by Ma27 — COMMENTED** [review]
Building the package and running the test works fine on my machine :)

**Review by matthewbauer — CHANGES_REQUESTED** [review]
Merge conflict

**Comment by WilliButz** [comment]
@matthewbauer I just rebased this on the current master but dillinger is based on [`nodejs-4_x`](https://github.com/joemccann/dillinger/blob/9581db83096a29948c7059bb421fd27e23f4f7f8/package.json#L41) which has already been deprecated. I built this with nodejs-6_x and it still seems to run fine.
I'm not sure if I should either use node 6 or close the PR for now and hope that some day dillinger will use nodejs 6 by default.

**Comment by Ma27** [comment]
I think that as the README stated that Node v4+ should be fine (see https://github.com/joemccann/dillinger/tree/9581db83096a29948c7059bb421fd27e23f4f7f8#installation)

@WilliButz besides the test have you confirmed the *basic* functionality of the software? (in this case it should be fine, between NodeJS 4 and 6 aren't too much breaking changes that could cause an issue for us)

As this seems to be a NodeSource powered product (which uses NSolid, see https://nodesource.com/products/nsolid and I don't know anything about this ecosystem except what I just read) I'm not sure how easy it is to perform platform bumps or maintain compatibility among several platforms...

**Pull request closed without merging**
