### PR TITLE
gazebo: remove

### PR DESCRIPTION
**Pull request by puzzlewolf**
###### Motivation for this change
The packages `gazebo{6,7}(-headless)` have had a broken dependency `sdformat` since 2016 66b6c2ce015eda95d9fe89052880fce52a7632c6. They were not marked as broken themselves, but of course they don't build either.
[Searching](https://github.com/NixOS/nixpkgs/search?q=gazebo&unscoped_q=gazebo&type=Issues) for "gazebo" in this repo results in many unrelated issues where they annoyingly turn up as a dependent packages which failed to build.

There are no dependencies for these packages, I think it's safe to remove them.
@pxc 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by puzzlewolf** [comment]
@therealpxc, @acowley, @breakds, @akru I saw your comments in https://github.com/NixOS/nixpkgs/issues/11713. What's your opinion on this? https://github.com/NixOS/nixpkgs/issues/11713 sounds like you have moved your ROS packages elsewhere.

**Comment by therealpxc** [comment]
I haven't used Gazebo in a long time. Removing these and pulling me off the maintainers list seems fair to me.

The others used them more recently, so their input is probably more important.

**Comment by acowley** [comment]
Being broken for that long is a pretty good indicator that it should be removed. Hopefully someone looking to get it working again can find the git history to have a starting place. Thank you for taking action on this!

**Comment by akru** [comment]
Ok, agree.

**Comment by puzzlewolf** [comment]
Thank you all for your answers!

@therealpxc: Ok, I'll remove `pxc` from `maintainer-list.nix`, and from the packages where you are listed as maintainer. 
I noticed that `ignition.transport` is broken since 2018, so I'll remove that package too.
Do you think it makes sense to keep `genromfs`, `ignition-math` and `qgroundcontrol` around?

**Comment by puzzlewolf** [comment]
`ignition-math` is only useful for `gazebo`. It makes no sense to keep it, outdated as it is.

**Comment by lopsided98** [comment]
I have working versions of Gazebo in [my nixpkgs fork](https://github.com/lopsided98/nixpkgs/commits/nix-ros), which I maintain as part of my [project for ROS support in Nix](https://github.com/lopsided98/nix-ros-overlay).

I have begun to upstream some of the dependencies (see #85983), and will hopefully be able to create PRs for the rest over the next few weeks.

I'm also willing to take over maintenance of QGroundControl as I use it regularly.

**Comment by breakds** [comment]
Sorry I wasn't paying enough attentions to the github notifications and late to the thread. Thank you for taking care of the broken package. Also I am really grateful about @lopsided98 's work, which should work for people who want to use Gazebo or other ROS packages in Nix.

**Pull request merged**
