### PR TITLE
nextcloud: 21.0.7 -> 21.0.8, 22.2.3 -> 22.2.4, 23.0.0 -> 23.0.1

### PR DESCRIPTION
**Pull request by yayayayaka**
###### Motivation for this change
Bumping nextcloud to the latest versions.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 157270` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>nextcloud21</li>
    <li>nextcloud22</li>
    <li>nextcloud23</li>
  </ul>
</details>

**Review by bachp — APPROVED** [review]
Sucessfully deployd and tested 23.0.1

**Comment by Ma27** [comment]
@TredwellGit please elaborate why you added a `security`-label here.

**Review by Ma27 — APPROVED** [review]

**Comment by TredwellGit** [comment]
https://nextcloud.com/changelog/
>We strongly recommend to stay up to date with Nextcloud to keep your data safe. The minor releases fix security issues that are found through, for example, our HackerOne program. Not doing so can put your data at risk. Update timely and don't run unmaintained Nextcloud versions. Privacy does not exist without security.
Our security policy is to publicize CVE's about 3 weeks after public availability of a new minor release. Administrators can then learn more about the vulnerabilities fixed and determine if their systems might have been vulnerable. As malicious actors are at this point more able to determine attack vectors, it is important to have updated before the CVE's are published.

**Comment by TredwellGit** [comment]
It is not listed as an RC: https://github.com/nextcloud/server/tags

**Comment by ajs124** [comment]
[Their wiki](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) says ":warning: 23.0.1, 22.2.4 and 21.0.8 have been put on hold.", whatever that means.

**Pull request merged**
