### PR TITLE
rustc: 1.53.1 -> 1.54.0

### PR DESCRIPTION
**Pull request by alyssais**
Tested builds of fd and firefox on x86_64-linux.

I'll need a Darwin user to test that fd builds.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
Built `fd` on `x86_64-darwin`.

**Comment by vcunat** [comment]
This probably broke [cargo-c](https://hydra.nixos.org/build/149344453) and maybe other builds.

**Comment by kevincox** [comment]
I bisected and found that it is in fact the source of the cargo-c breakage. This breaks a huge number of packages, basically anything graphical or that deals with fonts. We should probably revert until we can fix cargo-c.

**Comment by Mic92** [comment]
Maybe upgrading helps? https://github.com/lu-zero/cargo-c/releases/tag/v0.9.2

**Comment by kevincox** [comment]
Yeah, I was thinking I would try that first.

**Comment by kevincox** [comment]
The new version builds. Fixing forward in https://github.com/NixOS/nixpkgs/pull/133988

**Comment by alyssais** [comment]
If cargo-c is to be a blocker for Rust updates going forward, please add
it to the comment in the Rust version info file, which currently
mentions Firefox, Thunderbird, and fd.

**Pull request merged**
