### PR TITLE
 Revert "python: gym: 0.15.3 -> 0.15.4" 

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
noticed it was broken, froze/renamed it to prevent accidental bumpage

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

failures broken on master
```
[6 built (8 failed), 116 copied (608.5 MiB), 83.3 MiB DL]
error: build of '/nix/store/8jaxndxgs52ymddx8ac66333gygmlyd4-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/77049
4 package failed to build:
python37Packages.baselines python37Packages.rl-coach python38Packages.baselines python38Packages.rl-coach

5 package built:
python27Packages.gym python37Packages.gym python37Packages.roboschool python38Packages.gym python38Packages.roboschool
```

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build python27Packages.gym python37Packages.gym python37Packages.roboschool python38Packages.gym python38Packages.roboschool

**Comment by FRidh** [comment]
Please add an assert instead, that will be more effective.

**Comment by jonringer** [comment]
This is intended to prevent the pypi update script from targeting this. Even with an assert, this file will be updated. The other option would be to do FetchFromGitHub

**Comment by FRidh** [comment]
Yes but it would fail on eval, that way it would be clear. When updating I often take all nix files, so this would not help.

**Comment by jonringer** [comment]
the file may be passed to the update script, but the update script skips files which has `fetchFromGitHub` in it: https://github.com/NixOS/nixpkgs/blob/15695df474eb60766f2d8a3768ec6211ec453b62/pkgs/development/interpreters/python/update-python-libraries/update-python-libraries.py#L242

**Comment by jonringer** [comment]
bump @FRidh 

what do you think about using fetchFromGitHub?

**Comment by jonringer** [comment]
update in #80024 makes this unnecessary

**Pull request closed without merging**
