### PR TITLE
[20.09] pythonPackages.bcrypt: use 3.1.x for python older than 3.6

### PR DESCRIPTION
**Pull request by mvnetbiz**
###### Motivation for this change
Backport of #97996
ZHF: #97479 
cc @NixOS/nixos-release-managers
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
When backporting changes, please follow https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes.

Namely, you should be doing `git cherry-pick -x <rev>` from a commit that has already landed in master. If the branches have diverged, you may alter the commit or add another commit to ensure that the package is able to still evaluate and build

**Comment by mvnetbiz** [comment]
I think I must have copy pasted wrong. I did get it right this time correct?

**Comment by mvnetbiz** [comment]
I think I had forgotten `-x` in cherry-pick @jonringer

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/98222
1 package marked as broken and skipped:
python27Packages.junos-eznc

1 package failed to build:
python27Packages.trackpy

34 packages built:
mysql-workbench poretools python27Packages.Fabric python27Packages.ansible python27Packages.awkward python27Packages.bcrypt python27Packages.bkcharts python27Packages.docker python27Packages.drms python27Packages.duckdb python27Packages.flammkuchen python27Packages.flask-bcrypt python27Packages.imbalanced-learn python27Packages.ldaptor python27Packages.mapsplotlib python27Packages.moto python27Packages.ncclient python27Packages.pandas python27Packages.paramiko python27Packages.passlib python27Packages.privacyidea-ldap-proxy python27Packages.pwntools python27Packages.pysftp python27Packages.pytest-ansible python27Packages.robotframework-sshlibrary python27Packages.scp python27Packages.seaborn python27Packages.sshtunnel python27Packages.uproot python27Packages.uproot-methods python27Packages.vega_datasets python27Packages.vidstab python27Packages.yfinance syncthing-gtk
```

**Pull request merged**
