### PR TITLE
Vaultwarden 1.30.0

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

Passkeys!

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]
Deployed on my system. Haven't checked yet passkeys because firefox is lagging behind updating the extension.

**Comment by mweinelt** [comment]
Looks like the update script needs an update as well. But even with the changes below the bw_web_builds fod hash remains empty.

```patch
diff --git a/pkgs/tools/security/vaultwarden/update.nix b/pkgs/tools/security/vaultwarden/update.nix
index c2c03413cc43..82aef630e919 100644
--- a/pkgs/tools/security/vaultwarden/update.nix
+++ b/pkgs/tools/security/vaultwarden/update.nix
@@ -8,18 +8,19 @@
 , gnugrep
 , gnused
 , jq
+, yq
 }:
 
 writeShellScript "update-vaultwarden" ''
-  PATH=${lib.makeBinPath [ curl git gnugrep gnused jq nix nix-prefetch-git nix-update ]}
+  PATH=${lib.makeBinPath [ curl git gnugrep gnused jq yq nix nix-prefetch-git nix-update ]}
 
   set -euxo pipefail
 
   VAULTWARDEN_VERSION=$(curl --silent https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest | jq -r '.tag_name')
   nix-update "vaultwarden" --version "$VAULTWARDEN_VERSION"
 
-  URL="https://raw.githubusercontent.com/dani-garcia/vaultwarden/''${VAULTWARDEN_VERSION}/docker/Dockerfile.j2"
-  WEBVAULT_VERSION=$(curl --silent "$URL" | grep "set vault_version" | sed -E "s/.*\"v([^\"]+)\".*/\\1/")
+  URL="https://raw.githubusercontent.com/dani-garcia/vaultwarden/''${VAULTWARDEN_VERSION}/docker/DockerSettings.yaml"
+  WEBVAULT_VERSION=$(curl --silent "$URL" | yq -r ".vault_version")
   old_hash=$(nix --extra-experimental-features nix-command eval -f default.nix --raw vaultwarden.webvault.bw_web_builds.outputHash)
   new_hash=$(nix --extra-experimental-features nix-command hash to-sri --type sha256 $(nix-prefetch-git https://github.com/dani-garcia/bw_web_builds.git --rev "v$WEBVAULT_VERSION" | jq --raw-output ".sha256"))
   sed -e "s#$old_hash#$new_hash#" -i pkgs/tools/security/vaultwarden/webvault.nix
```

**Comment by SuperSandro2000** [comment]
We should really add the required nginx location code in another PR.

**Comment by K900** [comment]
You just need to proxy everything to the same backend now, not sure it warrants the extra setup (though I wouldn't be opposed to it)

**Comment by K900** [comment]
Drafting until I figure out what's up with the tests.

**Comment by SuperSandro2000** [comment]
I think selenium is broken

```
subtest: use the web interface to sign up, log in, and save a password
server: must succeed: PYTHONUNBUFFERED=1 test-runner | systemd-cat -t test-runner
server # Traceback (most recent call last):
server #   File "/nix/store/jdm5chqkmh3z0wbip7r165fas3bfg1y4-python3-3.11.5-env/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
server #     path = SeleniumManager().driver_location(options) if path is None else path
server #            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server #   File "/nix/store/jdm5chqkmh3z0wbip7r165fas3bfg1y4-python3-3.11.5-env/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 78, in driver_location
server #     args = [str(self.get_binary()), "--browser", browser]
server #                 ^^^^^^^^^^^^^^^^^
server #   File "/nix/store/jdm5chqkmh3z0wbip7r165fas3bfg1y4-python3-3.11.5-env/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 57, in get_binary
server #     if not path.is_file() and os.environ["CONDA_PREFIX"]:
server #                               ~~~~~~~~~~^^^^^^^^^^^^^^^^
server #   File "<frozen os>", line 679, in __getitem__
server # KeyError: 'CONDA_PREFIX'
server # 
server # The above exception was the direct cause of the following exception:
server # 
server # Traceback (most recent call last):
server #   File "/run/current-system/sw/bin/test-runner", line 11, in <module>
server #     driver = Firefox(options=options)
server #              ^^^^^^^^^^^^^^^^^^^^^^^^
server #   File "/nix/store/jdm5chqkmh3z0wbip7r165fas3bfg1y4-python3-3.11.5-env/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
server #     self.service.path = DriverFinder.get_path(self.service, options)
server #                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server #   File "/nix/store/jdm5chqkmh3z0wbip7r165fas3bfg1y4-python3-3.11.5-env/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
server #     raise NoSuchDriverException(msg) from err
server # selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
server # 
```

**Comment by K900** [comment]
Yeah, looks like it's fixed on staging-next, so I might just wait for that.

**Comment by K900** [comment]
Fixed the permission error in the test, Selenium is broken and should be fixed on staging-next.

**Comment by K900** [comment]
Verified the tests pass when rebased on staging-next, so going to just merge this.

**Comment by mweinelt** [comment]
Looks like we need `SystemConfiguration on darwin now.

https://hydra.nixos.org/build/240147348

**Comment by K900** [comment]
https://github.com/NixOS/nixpkgs/pull/266243

**Pull request merged**
