### PR TITLE
morgen: 3.5.9 -> 3.6.3

### PR DESCRIPTION
**Pull request by Jegp**
This PR upgrades Morgen from 3.5.9 -> 3.6.2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by felbinger** [comment]
Rename PR + commit to: `morgen: 3.5.9 -> 3.6.2`

**Comment by Jegp** [comment]
Thank you for the pointer @felbinger . Anything else that should be done?

**Comment by felbinger** [comment]
Not from my point of view, but I'm not that experienced

**Comment by Jegp** [comment]
I'm a little confused about the process here. I'm happy to help though.

**Comment by Jegp** [comment]
The newest version is now 3.6.3, so I'll close this PR.

**Comment by felbinger** [comment]
You could have just amended your commit and force push it...

**Comment by Jegp** [comment]
I don't understand the workflow here and the branch has been standing for three weeks, so I closed it to avoid having too many open PRs. I'll open a new PR. In the meantime, can you point me to a place where I can understand the PR flow better? If the PR isn't addressed within a weeks time, it doesn't make sense to upload the changes because a new version will already be out.

**Comment by felbinger** [comment]
I've seen everything from a month to a year, until a "ready" pr has been merged.

It's your job to keep the pr up to date. In this case this means to keep updating the version in the file itself, pr title and commit message (simply amend your commit). More complex pull requests, especially those with release note changes, need to be rebased with the master branch, to fix merge conflicts, before the occur.

Sometime, someone will check your pr occasionally. He will test if your changes break the build of another package (see nixpkgs-review), if the changes in the software (in this case the new version) work and if the quality of the nix code is acceptable.

**Pull request closed without merging**
