### PR TITLE
python-packages py: 1.4.24 -> 1.4.30

### PR DESCRIPTION
**Pull request by FRidh**
Splitting up #9254 . Makes it hopefully easier to debug.

### CODE REVIEW

**Comment by FRidh** [comment]
This should succeed as soon as python-fedora is marked broken, or fixed. #9260

**Comment by mdorman** [comment]
This should also fix #9261

**Comment by vbgl** [comment]
This package has been concurrently updated by 9f9f1db6e554aaa21b2f5dc8cf0ef33656bec025.

**Comment by lethalman** [comment]
what............. wrong author in my commit, sorry @edwtjo :S should have been @FRidh

**Comment by edwtjo** [comment]
@lethalman perhaps I should start signing :)

**Pull request closed without merging**
