### PR TITLE
dune_3: 3.6.2 -> 3.7.0

### PR DESCRIPTION
**Pull request by marsam**
###### Description of changes

https://github.com/ocaml/dune/releases/tag/3.7.0
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.ocaml-lsp

**Review by vbgl — CHANGES_REQUESTED** [review]
This breaks the `fiber` package.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 216897` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>liquidsoap</li>
  </ul>
</details>
<details>
  <summary>64 packages built:</summary>
  <ul>
    <li>acgtk</li>
    <li>anders</li>
    <li>beluga</li>
    <li>coccinelle</li>
    <li>comby</li>
    <li>coqPackages.addition-chains</li>
    <li>coqPackages.coqeal</li>
    <li>coqPackages.coqide</li>
    <li>coqPackages.gaia-hydras</li>
    <li>coqPackages.goedel</li>
    <li>coqPackages.hydra-battles</li>
    <li>coqPackages.mathcomp-word</li>
    <li>coqPackages.multinomials</li>
    <li>coqPackages.serapi</li>
    <li>coqPackages.topology</li>
    <li>coqPackages.zorns-lemma</li>
    <li>cvehound</li>
    <li>dune-release</li>
    <li>dune_3</li>
    <li>easycrypt</li>
    <li>eff</li>
    <li>flitter</li>
    <li>flow</li>
    <li>framac</li>
    <li>fstar</li>
    <li>google-drive-ocamlfuse</li>
    <li>haxe (haxe_4_2)</li>
    <li>haxePackages.format</li>
    <li>haxePackages.heaps</li>
    <li>haxePackages.hlopenal</li>
    <li>haxePackages.hlsdl</li>
    <li>hxcpp (haxePackages.hxcpp)</li>
    <li>haxePackages.hxcs</li>
    <li>haxePackages.hxjava</li>
    <li>haxePackages.hxnodejs_4</li>
    <li>haxe_4_0</li>
    <li>haxe_4_1</li>
    <li>jackline</li>
    <li>libbap</li>
    <li>ligo</li>
    <li>obelisk</li>
    <li>ocamlformat (ocamlformat_0_24_1)</li>
    <li>ocamlformat_0_19_0</li>
    <li>ocamlformat_0_20_0</li>
    <li>ocamlformat_0_20_1</li>
    <li>ocamlformat_0_21_0</li>
    <li>ocamlformat_0_22_4</li>
    <li>ocamlformat_0_23_0</li>
    <li>ocsigen-i18n</li>
    <li>opam-installer</li>
    <li>opam2json</li>
    <li>orpie</li>
    <li>python310Packages.bap</li>
    <li>python311Packages.bap</li>
    <li>reason</li>
    <li>sail-riscv-rv32</li>
    <li>sail-riscv-rv64</li>
    <li>satysfi</li>
    <li>sks</li>
    <li>soupault</li>
    <li>stog</li>
    <li>vscode-extensions.chenglou92.rescript-vscode</li>
    <li>wayland-proxy-virtwl</li>
    <li>why3</li>
  </ul>
</details>

**Comment by marsam** [comment]
Updated the `fiber` package to use the new repository. Thanks!

**Review by vbgl — APPROVED** [review]

**Pull request merged**
