### PR TITLE
Fixes cargo-edit

### PR DESCRIPTION
**Pull request by Gerschtli**
###### Motivation for this change

`cargo-edit` was tagged as broken. This PR allows build again.
Uses `carnix` instead of `buildRustPackage`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Gerschtli** [comment]
@GrahamcOfBorg build cargo-edit

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build cargo-edit

**Comment by Gerschtli** [comment]
@matthewbauer can you help me with fixing these builds?

**Comment by matthewbauer** [comment]
I'm going to need to let someone else review this. I don't know enough about carnix to really review it.

@GrahamcOfBorg build cargo-edit

**Comment by Gerschtli** [comment]
@P-E-Meunier do you have any idea? you seem very involved in carnix in nixpkgs

**Comment by xeji** [comment]
@GrahamcOfBorg build cargo-edit

**Comment by Gerschtli** [comment]
Seems good to me. Dont know what to do with the timeout on aarch64-linux

**Comment by xeji** [comment]
`rustc` builds  for aarch64 typically time out on our ofborg machines, nothing to worry about. We'll see what happens on hydra.

**Comment by matthewbauer** [comment]
This is breaking the tarball:

https://hydra.nixos.org/build/75272616/nixlog/1

**Comment by xeji** [comment]
fixed in 0046d4239767f7586eafa1a9c503ad97f1edb542

**Pull request merged**
