### PR TITLE
nixos/paperless-ngx: fix module 1.10.2

### LINKED ISSUE #207965: paperless: scheduler service can't start, "Unknown command: 'qcluster'"
### Describe the bug

Since 6c7ee71a3669b1f944caf08ba7d3289fcfe2377d which updated `paperless-ngx` from 1.9.2 to 1.10.2, the scheduler service can't be started, the error reported in the logs is:

```text
Unknown command: 'qcluster'
Type 'manage.py help' for usage.
```

### Steps To Reproduce
1. enable `services.paperless.enable`
2. use `systemctl status` or `journalctl -u` to see error as above in the logs 

### Expected behavior

The service starts succesfully

### Notify maintainers

* Module maintainers: 
  * @erikarvstedt 
  * @Flakebi 
* Package maintainers:
  * @erikarvstedt 
  * @lukegb 
  * @gador 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0, NixOS, 23.05 (Stoat), 23.05.20221225.fad51ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.0pre20221223_3dbf9b5`
 - channels(aroemer): `"nixpkgs-21.11"`
 - channels(nmelzer): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by leona-ya**
###### Description of changes

With the update to paperless-ngx to 1.10.2 (#206835) the task queue of paperless-ngx was changed to celery. This broke the NixOS module.

fixes #207965

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by leona-ya** [comment]
Currently the NixOS test fails but I don't understand why. I tried this on my instance and it works...

**Comment by elohmeier** [comment]
I think management of the NLTK data files should be added as well, see e.g. https://github.com/paperless-ngx/paperless-ngx/pull/2129/files for the upstream docker image changes they decided to do. We could fetch the NLTK data files using `fetchzip` and populate the `PAPERLESS_NLTK_DIR` env var accordingly.

**Comment by NobbZ** [comment]
`master` fails as well after 20 minutes… So as the test doesn't seem to block advancing the channels (we probably wouldn't have this problem if it would), we could as well remove it…

**Comment by leona-ya** [comment]
@NobbZ the test fails on master because paperless-ngx is broken there. In #206835 the package was updated without the NixOS module update. This PR updates the NixOS module, so the test _should_ work. Therefore the test should be fixed.

**Comment by leona-ya** [comment]
@elohmeier Good idea. I would add that as an optional parameter later.

**Comment by NobbZ** [comment]
I am aware that paperless is broken there.

And as the tests are failing, channels shouldn't have advanced. Or we can remove the tests as irrelevant. 

Thats what I wanted to say…

**Comment by leona-ya** [comment]
Ah, sorry I misread your post. The NixOS test could have prevented merging the package update PR. Therefore I think the test is relevant in general. We could disable the test for now because it's more important to fix `master` (and could add NLTK support in another PR)

**Comment by SuperSandro2000** [comment]
> And as the tests are failing, channels shouldn't have advanced.

Only a subset of the tests block channel advancing. paperless should surely not be one of them.

**Comment by NobbZ** [comment]
Which I totally understand, though why does the test exist at all then? It is obviously neither checked when merging, nor when advancing, so why take the burden of maintanance?

**Comment by SuperSandro2000** [comment]
We should definitely add it to passthru and fix it.

**Comment by babariviere** [comment]
Just seeing this PR. Sorry for the update of paperless-ngx. I should have checked that it would work with the module. Will be more careful next time. And thanks for fixing it!

**Comment by ambroisie** [comment]
I think there is a missing dependency on `redis-paperless.service` for `paperless-task-queue.service`.

**Comment by leona-ya** [comment]
@ambroisie That should be okay i think. `paperless-task-queue` is started by `paperless-scheduler` and this service starts after `redis-paperless`

**Comment by ambroisie** [comment]
@leona-ya that seems surprising, I had an issue due to the missing dependency when `nixos-rebuild switch`ing after updating my nixpkgs input.

Will have to see if it happens again in the future.

**Pull request merged**
