### PR TITLE
freeplane: 1.9.5 -> 1.9.14

### PR DESCRIPTION
**Pull request by maxhbr**
###### Description of changes

bump version of freeplane.

They are currently missing the latest tags on their repo (see https://github.com/freeplane/freeplane/issues/274) so this PR changes to pinning to commit hash for now.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
I suggest putting the following in the let block and referencing them 
 ```
grade = gradle_6
jdk = jdk11
```

**Comment by maxhbr** [comment]
Good hint, I extracted it (and other stuff) to the let block.

The upstream project now has a tag for the release, but they tagged something that does compile but contains inconsistencies (see https://github.com/freeplane/freeplane/issues/274#issuecomment-1079651804). They tagged the wrong / a bad commit.

**Comment by maxhbr** [comment]
They might be right with their tag, but it fails to launch for me ... -> DRAFT

**Comment by maxhbr** [comment]
This PR is now fixed and green.

**Review by charles-dyfis-net — APPROVED** [review]
Builds and runs correctly; changes are reasonable.

**Pull request merged**
