### PR TITLE
linuxPackages.rtl8821cu: switch to a more maintained fork

### PR DESCRIPTION
**Pull request by moni-dz**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fortuneteller2k** [comment]
@ofborg build linuxPackages_5_12.rtl8821cu

**Comment by fortuneteller2k** [comment]
@ofborg build linuxPackages_5_12.rtl8821cu

**Comment by fortuneteller2k** [comment]
@ofborg build linuxPackages_5_12.rtl8821cu

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123636` at e27ab84f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxPackages-libre.rtl8821cu</li>
    <li>linuxPackages_4_4.rtl8821cu</li>
    <li>linuxPackages_4_9.rtl8821cu</li>
    <li>linuxPackages_hardkernel_4_14.rtl8821cu</li>
    <li>linuxPackages_hardkernel_latest.rtl8821cu</li>
    <li>linuxPackages_latest-libre.rtl8821cu</li>
    <li>linuxPackages_testing_bcachefs.rtl8821cu</li>
    <li>linuxPackages_xanmod.rtl8821cu</li>
  </ul>
</details>
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/ba2a97cb3a64b7e1c98bc3d96c12c9a2">linuxPackages.rtl8821cu</a> (linuxPackages_5_10.rtl8821cu)</li>
    <li><a href="https://gist.github.com/c30ee4ee4e12d1cd3f2aaa49538af87a">linuxPackages_4_14.rtl8821cu</a></li>
    <li><a href="https://gist.github.com/65a95e98bcc04073a9bc23e5a51c32ad">linuxPackages_4_19.rtl8821cu</a></li>
    <li><a href="https://gist.github.com/649a01d16eada01f47c1f932341bd6b4">linuxPackages_5_11.rtl8821cu</a> (linuxPackages_latest.rtl8821cu)</li>
    <li><a href="https://gist.github.com/d0492c38051b40bb4a929f9a10645c65">linuxPackages_5_12.rtl8821cu</a></li>
    <li><a href="https://gist.github.com/46f7d957fc1f24bf930746187592bf81">linuxPackages_5_4.rtl8821cu</a></li>
    <li><a href="https://gist.github.com/0cf9a21c3083342ac960348286898e06">linuxPackages_hardened.rtl8821cu</a></li>
    <li><a href="https://gist.github.com/97587b8f0b57c5a4a1834ec3d1692fc8">linuxPackages_latest_hardened.rtl8821cu</a></li>
    <li><a href="https://gist.github.com/c099cc21fb78632e5e72717006ff712c">linuxPackages_lqx.rtl8821cu</a></li>
    <li><a href="https://gist.github.com/999bd5db9a1e0d074d3b79298dc46151">linuxPackages_zen.rtl8821cu</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by fortuneteller2k** [comment]
changing source to https://github.com/morrownr/8821cu for a hopefully working aarch64 variant

**Comment by fortuneteller2k** [comment]
ZHF: #122042

**Review by jonringer — APPROVED** [review]
LGTM

cc @contrun

**Review by contrun — APPROVED** [review]
LGTM

**Review by mweinelt — APPROVED** [review]

**Pull request merged**
