### PR TITLE
rubyPackages: remove global v8 pinning

### PR DESCRIPTION
**Pull request by WilliButz**
###### Motivation for this change
The motivation behind this is the failing build of `v8_3_16_14` on aarch64-linux, which causes gitlab to fail (https://github.com/NixOS/nixpkgs/pull/68550#issuecomment-548604681) because it depends on ruby packages that depend on the broken v8 version because of an old version pinning.
The only ruby package that does not build with the latest v8 is `therubyracer` and it is not referenced by any other expression.

This removes the global pinning of v8 to 3.16.14 and also removes the
unreferenced package 'therubyracer'.
**edit**: This now also removes the no longer referenced v8 version 3.16.14 and limits the supported platforms of v8 version 3.14 to x86_*-linux

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

- [x] Successfully ran nix-review:

Result of `nix-review` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>5 package were build:</summary>

  - gitlab
  - gitlab-ee
  - rubyPackages_2_4.libv8
  - rubyPackages_2_5.libv8
  - rubyPackages_2_6.libv8
</details>

ping @flokli

### CODE REVIEW

**Comment by flokli** [comment]
Very nice! Can we also update meta for the v8_3* packages, so it's clear they don't work on aarch64?

**Comment by WilliButz** [comment]
@flokli I agree. At least for 3.14 it seems to much of a hassle to get it to build on aarch64 and we can now even remove 3.16.14, because no other package references it after the removal of `therubyracer` (which I didn't notice before).

**Review by flokli — APPROVED** [review]

**Comment by flokli** [comment]
We should probably backport the ruby v8 change (or something only applying for gitlab, don't know what could break) into 19.09, to fix GitLab there on aarch64, too.

**Comment by alyssais** [comment]
therubyracer may not be referenced elsewhere, but it’s used by a large number of Rails applications — I suspect everybody using NixOS to do Rails development would complain if we dropped build support for it.

**Comment by zimbatm** [comment]
source: https://rubygems.org/gems/therubyracer

Looking at the repo is doesn't seem maintained anymore. The last release was in January 2017.
Maybe we can drop it, especially since there are no projects in nixpkgs to exercise it. Users can always provide their own gemConfig if they really want to keep using therubyracer in their project.

**Comment by alyssais** [comment]
> Looking at the repo is doesn't seem maintained anymore. The last
> release was in January 2017.

Ah, didn't realise that.  I guess we've moved on.

In that case, dropping is fine with me.

**Comment by zimbatm** [comment]
I remember that `execjs` was used to select the JS evaluator engine and you could switch from `therubyracer` to just invoking `nodejs`, which is what most people do nowadays probably.

**Comment by WilliButz** [comment]
Ah I noticed that the project seemed to be no longer maintained. Sorry for not mentioning it above :/

**Pull request merged**
