### PR TITLE
qgnomeplatform: 0.8.4 → 0.9.1

### PR DESCRIPTION
**Pull request by bobby285271**
Not tested but open an early draft to avoid duplicate work...

### Debug

```
$ QT_LOGGING_RULES="qt.qpa.qgnomeplatform*=true" some-application
```

Specifically, if cursor theme not working on Qt apps, then you might mess up one of the following:

```
$ echo $XCURSOR_THEME
$ cat ~/.local/share/icons/default/index.theme
$ cat ~/.icons/default/index.theme
```

Specifically, if you have unexpected mixed light/dark view, try restart the app

### To test

Still testing... I guess, we need to test a matrix of:

- GNOME Wayland, GNOME X11, Cinnamon, Pantheon, random other desktop
- Qt5 app, Qt6 app
- QT_STYLE_OVERRIDE is adwaita, QT_STYLE_OVERRIDE is adwaita-dark, none
- Adwaita, Adwaita-dark, random light theme, random dark theme as GTK theme
- No support `org.freedesktop.appearance.color-scheme`, no preference, prefer light, prefer dark

? :upside_down_face: 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
Observations:

### GNOME

`QT_LOGGING_RULES="qt.qpa.qgnomeplatform*=true"` says `xdg-desktop-portal` backend is used.

A matrix of no-preference, prefer-dark color scheme & Adwaita, Adwaita-dark gtk theme with no QT_STYLE_OVERRIDE set:

|  |  |  | 
|---|---|---|---|

However, when setting `QT_STYLE_OVERRIDE=adwaita` under prefer-dark color scheme and Adwaita gtk theme, things seem to mess up, you have to use `QT_STYLE_OVERRIDE=adwaita-dark` or unset the variable to make the entire view go dark.



### Cinnamon

`QT_LOGGING_RULES="qt.qpa.qgnomeplatform*=true"` says GSettings backend is used, I saw https://github.com/FedoraQt/QGnomePlatform/blob/0.9.1/src/common/gnomesettings.cpp#L85

In Cinnamon 5.8 when changing appearance, [both GTK theme and dark mode preference](https://github.com/linuxmint/cinnamon/commit/0f9ef1688556e61413e56419e50e59812eae5a11) will update. With a first look things sound good, but looking at the logs only gtk-theme gsetting property change are detected, and after restarting fcitx5-config-qt was messed up like the previous screenshot. I might do a Fedora Cinnamon installation later to confirm this, but I don't think it knows `org.x.apps.portal`. A workaround is manually `gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'`

### Xfce

GSettings backend is used.

Having no xdg-desktop-portal-xapp installed, I got `qt.qpa.qgnomeplatform: Could not find color scheme  ""` warnings on both Qt5, Qt6 apps. Things look the simplest here. When GTK theme contains "-dark", prefer dark theme (shown in the debug outputs) will be true.

**Comment by bobby285271** [comment]
Ah forgot to test Pantheon...

### Pantheon

GSettings backend is used.

elementary provides gtk.css & gtk-dark.css for each of their themes, and does not have theme which has `-dark` in its name. And it use `io.elementary.settings-daemon.prefers-color-scheme` to manage color scheme, so fcitx5-config-qt is always light for me unless I start to set `QT_STYLE_OVERRIDE`.



---

I think I would consider (at least) the cinnamon one as a blocker, since the default experience is not good :upside_down_face:

**Comment by bobby285271** [comment]
Reproduced on Fedora, [filed an issue](//github.com/FedoraQt/QGnomePlatform/issues/147).

**Comment by bobby285271** [comment]
Looking at [FedoraQt/QGnomePlatform#145 (comment)](//github.com/FedoraQt/QGnomePlatform/pull/145#issuecomment-1645221710), custom Qt theming removal should happen "next week", though I am not sure how Fusion will behave here.

**Comment by lilyinstarlight** [comment]
By the way, this bump seems to fix cursor issues with Qt apps on Wayland when using adwaita-dark for me (I'm on Sway but several months ago, my cursors started showing really small on Qt windows)

**Comment by bobby285271** [comment]
`qt.style = "adwaita";` for gsettings backend (non-GNOME) and `qt.style = "none";` for xdg-desktop-portal backend (GNOME) seem to look good on the desktops I've tested ("always light" is probably better than the "messed up" view :upside_down_face:). If we assume nobody is going to play with this env on these desktops this actually can be acceptable to me.

**Comment by bobby285271** [comment]
> cursor issues with Qt apps on Wayland

Is that just Qt6 apps or all Qt apps? I saw at least https://github.com/FedoraQt/QGnomePlatform/commit/5fe754e510a6700c766302b15931a421d2658f46 and https://github.com/FedoraQt/QGnomePlatform/commit/d0d8f412de8f3e06e146b6c36f78a6311bd9a0ec. I personally am okay to fetchpatch these two first since I am not sure if I want to land this PR :upside_down_face:

**Comment by lilyinstarlight** [comment]
> Is that just Qt6 apps or all Qt apps? I saw at least [FedoraQt/QGnomePlatform@5fe754e](https://github.com/FedoraQt/QGnomePlatform/commit/5fe754e510a6700c766302b15931a421d2658f46) and [FedoraQt/QGnomePlatform@d0d8f41](https://github.com/FedoraQt/QGnomePlatform/commit/d0d8f412de8f3e06e146b6c36f78a6311bd9a0ec). I personally am okay to fetchpatch these two first since I am not sure if I want to land this PR

After doing some quick testing, it looks like it's just Qt6 apps. So it's possible it might have started happening a few months ago because the apps I used might have updated from Qt5 to Qt6 around that time

**Comment by bobby285271** [comment]
- #248053

**Comment by bobby285271** [comment]
I just noticed there is https://github.com/FedoraQt/QAdwaitaDecoration now, looking at https://fedoraproject.org/wiki/Changes/NoCustomQtThemingForWorkstation#Scope hopefully this will be the "Upstream some of the QGnomePlatform features to Qt upstream" :joy:

**Pull request closed without merging**
