### PR TITLE
bcachefs: 2022-03 -> 2022-04

### PR DESCRIPTION
**Pull request by Madouura**
###### Description of changes

Various fixes.
If you are having trouble installing from a USB drive, use ``keyctl link @u @s`` before ``bcachefs unlock /dev/sdX`` and ensure you are not using bcachefs on the unstable channel if you are on stable. There seems to be some incompatibility in systemd between the two channels, and using bcachefs from the unstable channel seems to pull whatever is causing that.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 167968` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>34 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_testing_bcachefs.anbox</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ena</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ixgbevf</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.mxu11x0</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ndiswrapper</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.openafs_1_9</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.phc-intel</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.r8125</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8188eus-aircrack</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8723bs</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8812au</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtlwifi_new</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtw88</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.sch_cake</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.tbs</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.xmm7360-pci</li>
    <li>linuxPackages_testing_bcachefs.anbox</li>
    <li>linuxPackages_testing_bcachefs.ena</li>
    <li>linuxPackages_testing_bcachefs.ixgbevf</li>
    <li>linuxPackages_testing_bcachefs.mxu11x0</li>
    <li>linuxPackages_testing_bcachefs.ndiswrapper</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy340</li>
    <li>linuxPackages_testing_bcachefs.openafs_1_9</li>
    <li>linuxPackages_testing_bcachefs.phc-intel</li>
    <li>linuxPackages_testing_bcachefs.r8125</li>
    <li>linuxPackages_testing_bcachefs.rtl8188eus-aircrack</li>
    <li>linuxPackages_testing_bcachefs.rtl8723bs</li>
    <li>linuxPackages_testing_bcachefs.rtl8812au</li>
    <li>linuxPackages_testing_bcachefs.rtlwifi_new</li>
    <li>linuxPackages_testing_bcachefs.rtw88</li>
    <li>linuxPackages_testing_bcachefs.sch_cake</li>
    <li>linuxPackages_testing_bcachefs.tbs</li>
    <li>linuxPackages_testing_bcachefs.xmm7360-pci</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_testing_bcachefs.openafs (linuxKernel.packages.linux_testing_bcachefs.openafs ,linuxPackages_testing_bcachefs.openafs_1_8)</li>
  </ul>
</details>
<details>
  <summary>79 packages built:</summary>
  <ul>
    <li>bcachefs-tools</li>
    <li>linux_testing_bcachefs (linuxPackages_testing_bcachefs.kernel)</li>
    <li>linuxPackages_testing_bcachefs.acpi_call (linuxKernel.packages.linux_testing_bcachefs.acpi_call)</li>
    <li>linuxPackages_testing_bcachefs.akvcam (linuxKernel.packages.linux_testing_bcachefs.akvcam)</li>
    <li>linuxPackages_testing_bcachefs.apfs (linuxKernel.packages.linux_testing_bcachefs.apfs)</li>
    <li>linuxPackages_testing_bcachefs.asus-ec-sensors (linuxKernel.packages.linux_testing_bcachefs.asus-ec-sensors)</li>
    <li>linuxPackages_testing_bcachefs.asus-wmi-sensors (linuxKernel.packages.linux_testing_bcachefs.asus-wmi-sensors)</li>
    <li>linuxPackages_testing_bcachefs.batman_adv (linuxKernel.packages.linux_testing_bcachefs.batman_adv)</li>
    <li>linuxPackages_testing_bcachefs.bbswitch (linuxKernel.packages.linux_testing_bcachefs.bbswitch)</li>
    <li>linuxPackages_testing_bcachefs.broadcom_sta (linuxKernel.packages.linux_testing_bcachefs.broadcom_sta)</li>
    <li>linuxPackages_testing_bcachefs.can-isotp (linuxKernel.packages.linux_testing_bcachefs.can-isotp)</li>
    <li>linuxPackages_testing_bcachefs.chipsec (linuxKernel.packages.linux_testing_bcachefs.chipsec)</li>
    <li>linuxPackages_testing_bcachefs.cpupower (linuxKernel.packages.linux_testing_bcachefs.cpupower)</li>
    <li>linuxPackages_testing_bcachefs.cryptodev (linuxKernel.packages.linux_testing_bcachefs.cryptodev)</li>
    <li>linuxPackages_testing_bcachefs.ddcci-driver (linuxKernel.packages.linux_testing_bcachefs.ddcci-driver)</li>
    <li>linuxPackages_testing_bcachefs.dddvb (linuxKernel.packages.linux_testing_bcachefs.dddvb)</li>
    <li>linuxPackages_testing_bcachefs.digimend (linuxKernel.packages.linux_testing_bcachefs.digimend)</li>
    <li>linuxPackages_testing_bcachefs.dpdk (linuxKernel.packages.linux_testing_bcachefs.dpdk)</li>
    <li>linuxPackages_testing_bcachefs.dpdk-kmods (linuxKernel.packages.linux_testing_bcachefs.dpdk-kmods)</li>
    <li>linuxPackages_testing_bcachefs.evdi (linuxKernel.packages.linux_testing_bcachefs.evdi)</li>
    <li>linuxPackages_testing_bcachefs.facetimehd (linuxKernel.packages.linux_testing_bcachefs.facetimehd)</li>
    <li>linuxPackages_testing_bcachefs.fwts-efi-runtime (linuxKernel.packages.linux_testing_bcachefs.fwts-efi-runtime)</li>
    <li>linuxPackages_testing_bcachefs.gcadapter-oc-kmod (linuxKernel.packages.linux_testing_bcachefs.gcadapter-oc-kmod)</li>
    <li>linuxPackages_testing_bcachefs.hid-nintendo (linuxKernel.packages.linux_testing_bcachefs.hid-nintendo)</li>
    <li>linuxPackages_testing_bcachefs.hyperv-daemons (linuxKernel.packages.linux_testing_bcachefs.hyperv-daemons)</li>
    <li>linuxPackages_testing_bcachefs.intel-speed-select (linuxKernel.packages.linux_testing_bcachefs.intel-speed-select)</li>
    <li>linuxPackages_testing_bcachefs.isgx (linuxKernel.packages.linux_testing_bcachefs.isgx)</li>
    <li>linuxPackages_testing_bcachefs.it87 (linuxKernel.packages.linux_testing_bcachefs.it87)</li>
    <li>linuxPackages_testing_bcachefs.jool (linuxKernel.packages.linux_testing_bcachefs.jool)</li>
    <li>linuxPackages_testing_bcachefs.kvdo (linuxKernel.packages.linux_testing_bcachefs.kvdo)</li>
    <li>linuxPackages_testing_bcachefs.kvmfr (linuxKernel.packages.linux_testing_bcachefs.kvmfr)</li>
    <li>linuxPackages_testing_bcachefs.liquidtux (linuxKernel.packages.linux_testing_bcachefs.liquidtux)</li>
    <li>linuxPackages_testing_bcachefs.lttng-modules (linuxKernel.packages.linux_testing_bcachefs.lttng-modules)</li>
    <li>linuxPackages_testing_bcachefs.mba6x_bl (linuxKernel.packages.linux_testing_bcachefs.mba6x_bl)</li>
    <li>linuxPackages_testing_bcachefs.mbp2018-bridge-drv (linuxKernel.packages.linux_testing_bcachefs.mbp2018-bridge-drv)</li>
    <li>linuxPackages_testing_bcachefs.mwprocapture (linuxKernel.packages.linux_testing_bcachefs.mwprocapture)</li>
    <li>linuxPackages_testing_bcachefs.netatop (linuxKernel.packages.linux_testing_bcachefs.netatop)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_beta (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_beta)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy390 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy390)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy470 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470)</li>
    <li>linuxPackages_testing_bcachefs.nvidiabl (linuxKernel.packages.linux_testing_bcachefs.nvidiabl)</li>
    <li>linuxPackages_testing_bcachefs.openrazer (linuxKernel.packages.linux_testing_bcachefs.openrazer)</li>
    <li>linuxPackages_testing_bcachefs.perf (linuxKernel.packages.linux_testing_bcachefs.perf)</li>
    <li>linuxPackages_testing_bcachefs.ply (linuxKernel.packages.linux_testing_bcachefs.ply)</li>
    <li>linuxPackages_testing_bcachefs.r8168 (linuxKernel.packages.linux_testing_bcachefs.r8168)</li>
    <li>linuxPackages_testing_bcachefs.rr-zen_workaround (linuxKernel.packages.linux_testing_bcachefs.rr-zen_workaround)</li>
    <li>linuxPackages_testing_bcachefs.rtl8189es (linuxKernel.packages.linux_testing_bcachefs.rtl8189es)</li>
    <li>linuxPackages_testing_bcachefs.rtl8192eu (linuxKernel.packages.linux_testing_bcachefs.rtl8192eu)</li>
    <li>linuxPackages_testing_bcachefs.rtl8814au (linuxKernel.packages.linux_testing_bcachefs.rtl8814au)</li>
    <li>linuxPackages_testing_bcachefs.rtl8821au (linuxKernel.packages.linux_testing_bcachefs.rtl8821au)</li>
    <li>linuxPackages_testing_bcachefs.rtl8821ce (linuxKernel.packages.linux_testing_bcachefs.rtl8821ce)</li>
    <li>linuxPackages_testing_bcachefs.rtl8821cu (linuxKernel.packages.linux_testing_bcachefs.rtl8821cu)</li>
    <li>linuxPackages_testing_bcachefs.rtl88x2bu (linuxKernel.packages.linux_testing_bcachefs.rtl88x2bu)</li>
    <li>linuxPackages_testing_bcachefs.rtl88xxau-aircrack (linuxKernel.packages.linux_testing_bcachefs.rtl88xxau-aircrack)</li>
    <li>linuxPackages_testing_bcachefs.sysdig (linuxKernel.packages.linux_testing_bcachefs.sysdig)</li>
    <li>linuxPackages_testing_bcachefs.system76 (linuxKernel.packages.linux_testing_bcachefs.system76)</li>
    <li>linuxPackages_testing_bcachefs.system76-acpi (linuxKernel.packages.linux_testing_bcachefs.system76-acpi)</li>
    <li>linuxPackages_testing_bcachefs.system76-io (linuxKernel.packages.linux_testing_bcachefs.system76-io)</li>
    <li>linuxPackages_testing_bcachefs.systemtap (linuxKernel.packages.linux_testing_bcachefs.systemtap)</li>
    <li>linuxPackages_testing_bcachefs.tmon (linuxKernel.packages.linux_testing_bcachefs.tmon)</li>
    <li>linuxPackages_testing_bcachefs.tp_smapi (linuxKernel.packages.linux_testing_bcachefs.tp_smapi)</li>
    <li>linuxPackages_testing_bcachefs.turbostat (linuxKernel.packages.linux_testing_bcachefs.turbostat)</li>
    <li>linuxPackages_testing_bcachefs.tuxedo-keyboard (linuxKernel.packages.linux_testing_bcachefs.tuxedo-keyboard)</li>
    <li>linuxPackages_testing_bcachefs.usbip (linuxKernel.packages.linux_testing_bcachefs.usbip)</li>
    <li>linuxPackages_testing_bcachefs.v4l2loopback (linuxKernel.packages.linux_testing_bcachefs.v4l2loopback)</li>
    <li>linuxPackages_testing_bcachefs.v86d (linuxKernel.packages.linux_testing_bcachefs.v86d)</li>
    <li>linuxPackages_testing_bcachefs.veikk-linux-driver (linuxKernel.packages.linux_testing_bcachefs.veikk-linux-driver)</li>
    <li>linuxPackages_testing_bcachefs.vendor-reset (linuxKernel.packages.linux_testing_bcachefs.vendor-reset)</li>
    <li>linuxPackages_testing_bcachefs.vhba (linuxKernel.packages.linux_testing_bcachefs.vhba)</li>
    <li>linuxPackages_testing_bcachefs.virtio_vmmci (linuxKernel.packages.linux_testing_bcachefs.virtio_vmmci)</li>
    <li>linuxPackages_testing_bcachefs.virtualbox (linuxKernel.packages.linux_testing_bcachefs.virtualbox)</li>
    <li>linuxPackages_testing_bcachefs.virtualboxGuestAdditions (linuxKernel.packages.linux_testing_bcachefs.virtualboxGuestAdditions)</li>
    <li>linuxPackages_testing_bcachefs.vmm_clock (linuxKernel.packages.linux_testing_bcachefs.vmm_clock)</li>
    <li>linuxPackages_testing_bcachefs.x86_energy_perf_policy (linuxKernel.packages.linux_testing_bcachefs.x86_energy_perf_policy)</li>
    <li>linuxPackages_testing_bcachefs.xone (linuxKernel.packages.linux_testing_bcachefs.xone)</li>
    <li>linuxPackages_testing_bcachefs.xpadneo (linuxKernel.packages.linux_testing_bcachefs.xpadneo)</li>
    <li>linuxPackages_testing_bcachefs.zenpower (linuxKernel.packages.linux_testing_bcachefs.zenpower)</li>
    <li>linuxPackages_testing_bcachefs.zfs (linuxKernel.packages.linux_testing_bcachefs.zfs ,linuxPackages_testing_bcachefs.zfsStable ,linuxPackages_testing_bcachefs.zfsUnstable)</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Changes look good

Builds, tests succesfull

2 kernel modules fail to build, but that's probably unrelated

**Comment by davidak** [comment]
@Madouura what about the failed arm test?

https://github.com/NixOS/nixpkgs/pull/167968/checks?check_run_id=5953412333

**Comment by Madouura** [comment]
> @Madouura what about the failed arm test?
> 
> https://github.com/NixOS/nixpkgs/pull/167968/checks?check_run_id=5953412333

I'm not really sure, it seems to be happening in ``nixosTests.bcachefs``.
If it happens again, perhaps we should remove ARM from the supported platforms for this package for a while until we can confirm it's fixed?

**Comment by davidak** [comment]
That sounds good. I have no way to test it on arm64. Maybe someone want to contribute with testing and fixing potential issues.

**Pull request merged**
