### PR TITLE
netbsd.compat: Fix cross compilation

### LINKED ISSUE #135332: netbsd.compat cannot be cross-compiled
### Describe the bug
`netbsd.compat` cross-compilation is broken. The package appears to cross-compile successfully, but produces native object files for the build system's architecture rather than the host system. This causes downstream failures when cross-compiling libs which depend on libnbcompat.

### Steps To Reproduce

On an x86_64 builder:
```
> nix-build . -A pkgsCross.muslpi.netbsd.compat
> readelf -h result/lib/libnbcompat.a
<snip>
File: result/lib/libnbcompat.a(rec_utils.lo)
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          1112 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         12
  Section header string table index: 11
```

### Expected behavior
libnbcompat should produce libraries for the host platform

### Additional context
netbsd.compat is a dependency of netbsd.fts, which is used as a compatibility shim when compiling for musl platforms, because musl libc does not have builtin fts support.

I plan to switch our toplevel fts to use musl-fts until this is resolved. A number of other musl-focused distros use musl-fts for this purpose: https://repology.org/project/musl-fts/versions.

### Notify maintainers
@Ericson2314 

### Metadata

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: netbsd.compat
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

Fix  #135332

The second commit is WIP. I suppose there is some scope creep here, but I got rid of the DESTDIR hack we had for installing headers. The problem is for some reason this flattened the installation so that headers from `netbsd.headers` that should be in subdirs are not.

`netbsd.compat` and `pkgsCross.aarch64-multiplatform.netbsd.compat` however build fine.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ericson2314** [comment]
Going to be, should have already. Anyone spot anything with that headers issue (`pkgsCross.x86_64-netbsd.netbsdCross.headers` for example) it would be much appreciated! I must admit I rather not back out of the mission creep because I will need it for FreeBSD anyways.

**Comment by Ericson2314** [comment]
OK this works now. The commit messages have a bit more info, too.

**Comment by alyssais** [comment]
@OfBorg build pkgsCross.muslpi.libselinux

**Comment by Ericson2314** [comment]
@alyssais it failed with
```
error: libselinux.so.1 uses VFP register arguments, /nix/store/[...]/lib/libnbcompat.a(strncasecmp.o) does not
```
So while we are cross compiling it, I guess float-abi got overridden somehow?

**Comment by Ericson2314** [comment]
OK It built successfully now.

**Comment by Ericson2314** [comment]
Anything else to do?

**Comment by r-burns** [comment]
Works great, thank you!

I don't know anything about netbsd's build system but the changes look good to me. Looks like there are a lot of rebuilds on darwin, happy to run some tests if anything in particular needs a closer look.

**Comment by alyssais** [comment]
Haven't had a chance to look in detail, but looks fine in a skim so I'm happy for this to be merged if it fixes the problem

**Pull request merged**
