### PR TITLE
rPackages.pbdZMQ: use zeromq from nixpkgs instead of vendored copy

### PR DESCRIPTION
**Pull request by moni-dz**
###### Description of changes

fails with
```
  CXXLD    src/libzmq.la
Undefined symbols for architecture arm64:
  "_R_registerRoutines", referenced from:
      R_init_libzmq(_DllInfo*) in src_libzmq_la-zzz.o
  "_R_useDynamicSymbols", referenced from:
      R_init_libzmq(_DllInfo*) in src_libzmq_la-zzz.o
ld: symbol(s) not found for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```
before this change

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fortuneteller2k** [comment]
Result of `nixpkgs-review pr 241051` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Review by jbedo — CHANGES_REQUESTED** [review]
These changes are not darwin specific. I checked the package and they vendor zeromq and revert to it when not found during build. You ran into problems with this on darwin because their vendoring is broken on darwin. We should fix this more generally though, since we don't want to use the vendored copy. Can you include pkg-config and zeromq for all architectures?

**Comment by fortuneteller2k** [comment]
> These changes are not darwin specific. I checked the package and they vendor zeromq and revert to it when not found during build. You ran into problems with this on darwin because their vendoring is broken on darwin. We should fix this more generally though, since we don't want to use the vendored copy. Can you include pkg-config and zeromq for all architectures?

Done.

**Review by jbedo — APPROVED** [review]

**Comment by jbedo** [comment]
Sorry, one last nit: update commit message to match and note it resolves darwin build issues in the body.

**Pull request merged**
