### PR TITLE
oama: init at 0.14

### PR DESCRIPTION
**Pull request by Melkor333**
## Description of changes

[Oama](https://github.com/pdobsan/oama) is a tool to do OAuth2 on the command line for various command line tools like Mail, Calendar, etc.
It integrates with Gnome keyring or can use GPG to encrypt the secret and can renew the token.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Can you try to move the new package into the directory `pkgs/by-name/oa/oama`? Would be good to have all new packages in there

**Comment by Melkor333** [comment]
> Can you try to move the new package into the directory `pkgs/by-name/oa/oama`? Would be good to have all new packages in there

Done. I just don't know how to fix the CI check which says that I call it wrongly (If I need to do that).

**Comment by onny** [comment]
I guess you'll have to remove the entry in `all-packages.nix` altogether. Only put the package in `pkgs/by-name` and rename the dependency directly to `http2_3_0_3`

**Comment by Melkor333** [comment]
I had to add a redirect. Just using `http2_3_0_3` and `warp_3_3_30` caused `warp` build to fail with:
```
Configuring warp-3.3.30...
CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:368:14 in Cabal-3.10.3.0:Distribution.Simple.Utils
Error: Setup: Encountered missing or private dependencies:
http2 >=3.0 && <5
```

Found the solution on [discord](https://discourse.nixos.org/t/haskell-project-with-private-dependency-that-should-come-from-another-haskellpackage-causes-encountered-missing-or-private-dependencies/26742/2).

Also bumped the version as I just saw a new release from yesterday :)

**Comment by maralorn** [comment]
@Melkor333 Sorry, we didn’t notice this PR. (To get attention by the "right" maintainers it helps to add the haskell label or tag the haskell team.) At this point I think #335989 is a bit nicer structured. But maybe you and aidalgol @Melkor333 can coordinate on how to proceed. (My suggestion would be to build on #335989 but enter both of you as maintainers.

**Comment by Melkor333** [comment]
Nah it's fine, I already badly maintain the packages I do.. :) I'll just close this one

**Pull request closed without merging**
