### PR TITLE
Update emacs2nix and update-melpa.el

### PR DESCRIPTION
**Pull request by kennyballou**
###### Motivation for this change

Emacs packages sourced from GitLab have not been building since they are downloaded using incorrect addresses.  This change uses the GitLab API path for downloading archives.

###### Things done

Tested changes by running the `update-melpa` script in the `pkgs/applications/editors/emacs-modes` directory, checked the output of `emacs-geiser/geiser` and other known GitLab emacs packages to ensure the warnings about unable to download were removed from the resulting JSON file.  I am *not* submitting updates to the JSON file as I'm **not** confident this is the correct procedure for updating it.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by mattchrist — APPROVED** [review]
LGTM. I can confirm this fixes the update-melpa script to be able to fetch projects from Gitlab.com again.

**Comment by mattchrist** [comment]
For context, the issue this PR fixes affects the following Emacs packages:
```
fennel-mode
geiser
geiser-chez
geiser-chibi
geiser-chicken
geiser-gambit
geiser-guile
geiser-mit
geiser-racket
gif-screencast
ligo-mode
mixed-pitch
modus-themes
oer-reveal
org-re-reveal
python-mode
recomplete
spell-fu
undo-fu
undo-fu-session
xref-rst
zotero
```

Once this is merged, re-running the 'update-melpa' script and merging a PR with the updated 'recipes-archive-melpa.json' will make these packages accessible again.

**Comment by spacekitteh** [comment]
bump?

**Comment by kennyballou** [comment]
At this state, what needs to be done to get this merged?

**Comment by mattchrist** [comment]
@kennyballou I wish I knew. I reviewed and approved, and cross-posted into discource's "already reviewed" thread. This is the first nixpkgs PR I've reviewed, so maybe I'm missing something.

It looks like maybe it still needs approval from @adisbladis.

**Comment by mattchrist** [comment]
@danieldk pinging you as suggested in [discourse](https://discourse.nixos.org/t/decision-making-2-0-1-0-1/12851/2). I reviewed and approved this PR 5 days ago and it appears stalled. Can you help move this forward? Thanks!

**Comment by danieldk** [comment]
@mattchrist thanks for pining me! I'll have a look.

**Comment by danieldk** [comment]
Thanks and sorry for the long wait!

**Pull request merged**
