### PR TITLE
nixos-rebuild: Fix broken `-I` option

### PR DESCRIPTION
**Pull request by andersk**
Commit 617a1a6e5778df81efceffa656988e38bd293b1c (#341402) broke this.

Cc @elikoga

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
This improves the situation but doesn't quite resolve it. The `nixos-rebuild-target-host` nixos test has been failing for some time now, but it's the only one that seems to use `nixos-rebuild -I`. This PR allows it to progress to a certain point, but it still fails on the `-I` handling rather than where it's been failing for months now. Specifically:

```
deployer # error: invalid SSH host name '-I'
```

**Comment by andersk** [comment]
I use `nixos-rebuild -I` on one of my systems and this works for me. Even if this only fixes the immediate regression from #341402 two days ago, without addressing a separate longer-term problem, it’s still worth merging.

**Comment by ElvishJerricco** [comment]
@andersk I think all that needs to be different here is moving `-I` back to where it was before, where it's only added to `extraBuildFlags` and not `copyFlags`. I also think this is a bug in the `nix-copy-closure` man page, which says that it supports `-I` when it clearly doesn't.

If this suggestion doesn't work for you then I'll merge this as is, but I'd like to make that little change if you don't mind.

**Comment by andersk** [comment]
@ElvishJerricco Sure, changed.

**Comment by danwdart** [comment]
Thanks! But... How would we address a system which has a broken version of `nixos-rebuild` without using `nixos-rebuild`?

**Comment by andersk** [comment]
@danwdart You can use `nix run -- github:NixOS/nixpkgs/master#nixos-rebuild`.

**Comment by ElvishJerricco** [comment]
@andersk I *strongly* recommend against using nixpkgs master in the general case.

@danwdart As with any bad nixos upgrade, you can rollback your system. `nixos-rebuild --rollback switch`

**Comment by danwdart** [comment]
Aha.. I constantly forget that Nix is so powerfuil! Thanks

**Pull request merged**
