### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
perl5.30.1-IPC-System-Simple-1.25 fails, cc @volth https://hydra.nixos.org/build/111420639

**Comment by FRidh** [comment]
The failing perl package can be fixed on master.

**Comment by volth** [comment]
> perl5.30.1-IPC-System-Simple-1.25 fails, cc @volth https://hydra.nixos.org/build/111420639

but.. there should `1.26`

`nix-build -E '(import (builtins.fetchTarball https://github.com/NixOS/nixpkgs/archive/staging.tar.gz) {}).perlPackages.IPCSystemSimple'`
does work and downloads `1.26` from `cache.nixos.org`

**Comment by volth** [comment]
And even your 1.25 link https://hydra.nixos.org/build/111420639 shows success

**Pull request merged**
