### PR TITLE
[22.05] firefox-unwrapped: 104.0.2 -> 105.0; firefox-esr-102-unwrapped: 102.2.0esr -> 102.3.0esr

### PR DESCRIPTION
**Pull request by mweinelt**
Backport #191990

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
 0:18.85(B ERROR: Rust compiler 1.60.0 is too old.(B(B
 0:18.85(B (B(B
 0:18.85(B To compile Rust language sources please install at least(B(B
 0:18.85(B version 1.61.0 of the 'rustc' toolchain (or, if using nightly,(B(B
 0:18.85(B at least one version newer than 1.61.0) and make sure it is(B(B
 0:18.85(B first in your path.(B(B

**Comment by wizeman** [comment]
I got this error:
```
0:10.65(B ERROR: Rust compiler 1.60.0 is too old.(B(B
 0:10.65(B (B(B
 0:10.65(B To compile Rust language sources please install at least(B(B
 0:10.65(B version 1.61.0 of the 'rustc' toolchain (or, if using nightly,(B(B
 0:10.65(B at least one version newer than 1.61.0) and make sure it is(B(B
 0:10.65(B first in your path.(B(B
 0:10.65(B (B(B
 0:10.65(B You can verify this by typing 'rustc --version'.(B(B
 0:10.65(B (B(B
 0:10.65(B If you have the 'rustup' tool installed you can upgrade(B(B
 0:10.65(B to the latest release by typing 'rustup update'. The(B(B
 0:10.65(B installer is available from https://rustup.rs/(B(B
 0:10.65(B (B(B
*** Fix above errors and then restart with "./mach build"
```

**Review by vcunat — APPROVED** [review]
Both work for me.  So far, at least.

**Comment by vcunat** [comment]
The build times really are long nowadays.

**Comment by wizeman** [comment]
`firefox-unwrapped` works for me, thanks!

**Comment by mweinelt** [comment]
> The build times really are long nowadays. (since profiling, I presume)

Two builds & profiling in between. Before pgo it was ~21 minutes for me. WIth pgo it's ~52 minutes.

**Pull request merged**
