### PR TITLE
azure-cli: move to by-name, nixfmt

### PR DESCRIPTION
**Pull request by superherointj**
azure-cli: move to by-name, nixfmt

* move from top-level to by-name
* run nixfmt on nix files (but not on automated file): extensions-manual.nix, package.nix, python-packages.nix
  I have not included `extensions-generated.nix` at this point in time.

Goal here is minimalist, to just establish a minimal base for a subsequent refactor.

CC @katexochen @obreitwi

### CODE REVIEW

**Comment by katexochen** [comment]
AFAIK it's currently not encouraged to manually format with the new formatter.

Message from the [Nix Formatting matrix room yesterday](https://matrix.to/#/!JHmxsrPoybcbBVDSjm:numtide.com/$HYfZLjTMt_WVGDpaycC_-wTYYzKD8dcqcZveECRLkWU?via=nixos.org&via=matrix.org&via=nixos.dev): 
>  I think the cost of people trying to manually format things everywhere is larger than ...

If you insist on formatting anyway, the formatting commit should be added to `.git-blame-ignore-revs`. See https://github.com/NixOS/nixpkgs/pull/322537 for the treewide formatting effort.

Moving to by-name looks good to me.

**Comment by emilazy** [comment]
FWIW: The treewide format PR won’t touch files that have had open PRs in the past while, and will enforce formatting changed files on every new PR. So it wouldn’t reformat this file now, and it would actually enforce doing what @superherointj did here. The message you quoted was in the context of whether to hold off on doing mass reformats before the formatter exactly matches the RFC formatting guidelines, as an argument for reformatting as much of the tree ASAP as possible; see e.g. https://github.com/NixOS/nixpkgs/pull/322537#issuecomment-2197286445. There’s already been a lot of small‐scale formatting and I’m not sure it makes sense to add every single commit to `.git-blame-ignore-revs`. That said, it might be best to any include any further refactoring in this PR rather than touching the files just for mechanical changes?

**Comment by katexochen** [comment]
>  I’m not sure it makes sense to add every single commit to .git-blame-ignore-revs

@emilazy I really think we should add it, git blame gives a lot of helpful info for packages of this size.

**Comment by emilazy** [comment]
Ah, I missed just how big this is :) It may be a good idea, then. Though I wonder how well `git blame` works even then with the combination of a move and big reformat; `.git-blame-ignore-revs` isn’t perfect in my experience.

**Comment by superherointj** [comment]
The repo will be formatted *anyway*. Which can cause breakages, for example, update scripts (#310700).
We are better knowing how things are actually going to be.

I will add the commit to `.git-blame-ignore-revs` then.

**Review by katexochen — APPROVED** [review]

**Review by eclairevoyant — APPROVED** [review]

**Pull request merged**
