### PR TITLE
cpython: 3.9.6 -> 3.9.7; 3.8.11 -> 3.8.12; 3.7.11-> 3.7.12; 3.6.14 -> 3.6.15; 3.10.0-rc1 -> 3.10.0

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://docs.python.org/release/3.9.7/whatsnew/changelog.html#changelog
https://docs.python.org/release/3.8.12/whatsnew/changelog.html#changelog

https://docs.python.org/release/3.6.15/whatsnew/changelog.html#python-3-6-15-final
https://docs.python.org/release/3.7.12/whatsnew/changelog.html#python-3-7-12-final

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@ofborg build python38.tests python39.tests

**Review by jonringer — APPROVED** [review]
diff LGTM

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 136254 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>python38Packages.requests</li>    <li>python39Packages.requests</li>  </ul></details>

**Comment by bergkvist** [comment]
By merging this PR - the following issue will be resolved: https://github.com/NixOS/nixpkgs/issues/105038

> [bpo-44689](https://bugs.python.org/issue44689): ctypes.util.find_library() now works correctly on macOS 11 Big Sur even if Python is built on an older version of macOS. Previously, when built on older macOS systems, find_library was not able to find macOS system libraries when running on Big Sur due to changes in how system libraries are stored.

Both Python 3.8.12 and Python 3.9.7 contain this patch (https://github.com/python/cpython/pull/27251).

**Comment by mweinelt** [comment]
Two more updates.

python36.tests won't run because our numpy version requires at least python37.

**Comment by FRidh** [comment]
Note 3.6 will be [EOL 2021-12](https://www.python.org/dev/peps/pep-0494/#and-beyond-schedule), and will thus need to be removed for NixOS 21.11.

I suggest changing the package to something else than `numpy` such as `py` or `setuptools`.

**Comment by jonringer** [comment]
> Note 3.6 will be [EOL 2021-12](https://www.python.org/dev/peps/pep-0494/#and-beyond-schedule), and will thus need to be removed for NixOS 21.11.
> 
> I suggest changing the package to something else than `numpy` such as `py` or `setuptools`.

Since python36 is essentially deprecated at this point (no longer being recursed into for derivations), I think it's okay to verify that `requests` still builds, and call it good. Very few people should be using python36 at this point

**Comment by jonringer** [comment]
unfortunately, python36Packages.requests seems to fail because of a failure in pytest-xdist

**Comment by mweinelt** [comment]
> bpo-43124: Made the internal putcmd function in smtplib sanitize input for presence of \r and \n characters to avoid (unlikely) command injection.

**Comment by mweinelt** [comment]
Working on removing Python 3.6 now, since we are nearing the release (8 weeks).

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by mweinelt** [comment]
That's it, no more references to `python36Packages`.

**Comment by mweinelt** [comment]
@GrahamcOfBorg build python39.tests python38.tests python37.tests

**Comment by trofi** [comment]
Bisect says d003f75d7888cd92993107b5a1d6e3a8d340bf68 "python39: 3.9.6 -> 3.9.7" it broke `python3Packages.argh` tests:

```
=========================== short test summary info ============================
FAILED test/test_integration.py::test_invalid_choice - assert False
FAILED test/test_integration.py::test_explicit_cmd_name - assert False

_____________________________ test_invalid_choice ______________________________

    def test_invalid_choice():
        def cmd(args):
            return 1

        # root level command

        p = DebugArghParser()
        p.add_commands([cmd])

>       assert run(p, 'bar', exit=True).startswith('invalid choice')
E       assert False
E        +  where False = <built-in method startswith of str object at 0x7fffe89b72d0>('invalid choice')
E        +    where <built-in method startswith of str object at 0x7fffe89b72d0> = "argument {cmd}: invalid choice: 'bar' (choose from 'cmd')".startswith
E        +      where "argument {cmd}: invalid choice: 'bar' (choose from 'cmd')" = run(DebugArghParser(prog='py.test', usage=None, description=None, formatter_class=<class 'argh.constants.CustomFormatter'>, conflict_handler='error', add_help=True), 'bar', exit=True)

test/test_integration.py:380: AssertionError
```

**Comment by trofi** [comment]
Filed another upstream report at https://github.com/aio-libs/aiohttp/issues/6066

**Pull request merged**
