### PR TITLE
rarcrack: init at 0.2

### PR DESCRIPTION
**Pull request by davidak**
works on NixOS 15.09, Ubuntu 14.04 and darwin (OS X 10.9.5)

:+1: ready to merge :)

### CODE REVIEW

**Comment by jgillich** [comment]
p7zip is packaged, the actual 7zip only works on Windows.

**Comment by davidak** [comment]
@jgillich i searched for 7zip and found nothing. thank you!

**Comment by davidak** [comment]
it needs `file` as a dependency, i added it but it don't work. file alone works.

```
[davidak@nixos:~/Downloads]$ file test.rar 
test.rar: RAR archive data, vf,

[davidak@nixos:~/Downloads]$ rarcrack test.rar 
RarCrack! 0.2 by David Zoltan Kedves (kedazo@gmail.com)

INFO: detected file type: 
ERROR: Couldn't detect archive type
```

it works when you set type manually. (on NixOS)

**Comment by jgillich** [comment]
You need to either add `file` to `PATH` using `makeWrapper`, or patch the path in the source code.

**Comment by davidak** [comment]
the source code has no special path. from `rarcrack.h`: `const char CMD_DETECT[] = "file -i -b %s"; //this command return what is the file mime type`

shouldn't it be enough to have it as an input on the first line like unrar etc?

**Comment by davidak** [comment]
also don't work :/

**Pull request merged**
