### PR TITLE
electron_31: init at 31.4.0, electron: bump default version to v31, electron-chromedriver_31: 31.3.0 -> 31.4.0

### LINKED ISSUE #325428: Package request: electron_31
Cross platform desktop application shell

**Metadata**

* homepage URL: https://electronjs.org/
* source URL: https://github.com/electron/electron
* license: MIT
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by teutat3s**
## Description of changes
Huge thanks to @yu-re-ka for providing these patches.

Also switches the default electron version to 31. The plan is to backport only the new version without touching the default for NixOS 24.05.

Fixes https://github.com/NixOS/nixpkgs/issues/325428.

Pinging @travisbhartwell @manveru for maintainer update.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by teutat3s** [comment]
Result of `nixpkgs-review pr 333907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>bilibili</li>
    <li>bitwarden-directory-connector</li>
    <li>redisinsight</li>
    <li>threema-desktop</li>
  </ul>
</details>
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>antimatter-dimensions</li>
    <li>blockbench</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>chatd</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron (electron_31)</li>
    <li>electron-bin (electron_31-bin)</li>
    <li>electron-chromedriver (electron-chromedriver_31)</li>
    <li>fcast-receiver</li>
    <li>freetube</li>
    <li>goofcord</li>
    <li>headset</li>
    <li>itch</li>
    <li>jitsi-meet-electron</li>
    <li>koodo-reader</li>
    <li>mattermost-desktop</li>
    <li>mqtt-explorer</li>
    <li>nix-tour</li>
    <li>obsidian</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>proton-pass</li>
    <li>protonmail-desktop</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>r2modman</li>
    <li>revolt-desktop</li>
    <li>ride</li>
    <li>sharedown</li>
    <li>siyuan</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>thedesk</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>vesktop</li>
    <li>vieb</li>
    <li>webtorrent_desktop</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

**Comment by gigamonster256** [comment]
Sick, I need electron 31 for a project i'm working on and the broken update.py was tripping me up. I got as far as updating the depot_tools to read the new DEPS format but didn't have enough time to get the new builtin condition variables working.

**Comment by SuperSandro2000** [comment]
> * bitwarden-directory-connector

Can you pin this program to electron 30 to fix the build? Would that also fix the other build failures?
I don't really have time currently to look into that

**Comment by teutat3s** [comment]
These builds are already failing on latest `nixos-unstable` (with `electron_30`):
- bilibili (hash mismatch)
- bitwarden-directory-connector https://hydra.nixos.org/build/269172640
- redisinsight (`ModuleNotFoundError: No module named 'distutils'`)
- threema-desktop https://hydra.nixos.org/build/269178821/nixlog/1

**Comment by SuperSandro2000** [comment]
I'll fix the bitwarden directory connector then. The gyp in there wants to use distutils.

**Comment by teutat3s** [comment]
Looks like redisinsight has a similar gyp error.

**Comment by teutat3s** [comment]
Result of `nixpkgs-review pr 333907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>bilibili</li>
    <li>bitwarden-directory-connector</li>
    <li>redisinsight</li>
    <li>threema-desktop</li>
  </ul>
</details>
<details>
  <summary>54 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>antimatter-dimensions</li>
    <li>blockbench</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>chatd</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron (electron_31)</li>
    <li>electron-bin (electron_31-bin)</li>
    <li>electron-chromedriver (electron-chromedriver_31)</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>fcast-receiver</li>
    <li>freetube</li>
    <li>goofcord</li>
    <li>headset</li>
    <li>itch</li>
    <li>jitsi-meet-electron</li>
    <li>koodo-reader</li>
    <li>mattermost-desktop</li>
    <li>mqtt-explorer</li>
    <li>nix-tour</li>
    <li>obsidian</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>proton-pass</li>
    <li>protonmail-desktop</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>r2modman</li>
    <li>revolt-desktop</li>
    <li>ride</li>
    <li>sharedown</li>
    <li>siyuan</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>thedesk</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>vesktop</li>
    <li>vieb</li>
    <li>webtorrent_desktop</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

**Comment by emilylange** [comment]
Note: `electron_29` will get EOLed soon (#335850) and at least two packages that want to bump their `electron_29` to `electron_31` are blocked by this PR here (#330137 and #335737).

**Comment by yayayayaka** [comment]
Result of `nixpkgs-review pr 333907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>bilibili</li>
    <li>redisinsight</li>
    <li>threema-desktop</li>
  </ul>
</details>
<details>
  <summary>55 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>antimatter-dimensions</li>
    <li>bitwarden-directory-connector</li>
    <li>blockbench</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>chatd</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron (electron_31)</li>
    <li>electron-bin (electron_31-bin)</li>
    <li>electron-chromedriver (electron-chromedriver_31)</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>fcast-receiver</li>
    <li>freetube</li>
    <li>goofcord</li>
    <li>headset</li>
    <li>itch</li>
    <li>jitsi-meet-electron</li>
    <li>koodo-reader</li>
    <li>mattermost-desktop</li>
    <li>mqtt-explorer</li>
    <li>nix-tour</li>
    <li>obsidian</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>proton-pass</li>
    <li>protonmail-desktop</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>r2modman</li>
    <li>revolt-desktop</li>
    <li>ride</li>
    <li>sharedown</li>
    <li>siyuan</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>thedesk</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>vesktop</li>
    <li>vieb</li>
    <li>webtorrent_desktop</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

**Review by yayayayaka — APPROVED** [review]
thanks!

**Pull request merged**
