### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@peti GHC 8.6.5 fails on staging-next. Could you have a look?
https://hydra.nixos.org/build/92947674

**Comment by FRidh** [comment]
cc @basvandijk for GHC

**Comment by peti** [comment]
> 8.6.5 fails on staging-next.

I re-started https://hydra.nixos.org/build/92947674 and now it succeeds. It appears the problem is some transient phenomenon related to parallel building, i.e. a race condition in GHC's build system.

**Comment by FRidh** [comment]
llvm 7 failure on aarch
https://hydra.nixos.org/build/92951911

**Comment by matthewbauer** [comment]
@fridh we're seeing two issues with the new macOS stuff:

- https://hydra.nixos.org/build/92964363
- https://hydra.nixos.org/build/92930990

I'll have some time this weekend to work on it

**Comment by LnL7** [comment]
There's also a problem with llvm 7.1 on darwin, blocking rustc. Since the queue is completely empty I would propose to merge both #60849 and #60912 first.

**Comment by FRidh** [comment]
@LnL7 go for it

**Comment by FRidh** [comment]
Afterwards I do want to merge this with master so we can go to the next batch of updates (staging).

**Comment by FRidh** [comment]
Merged #60912 into staging-next but not #60849; to do a full linux rebuild as well seems a bit extreme.

**Pull request merged**
