### PR TITLE
new package: heroku-toolbelt

### PR DESCRIPTION
**Pull request by mirdhyn**
Adding heroku-toolbelt package (+ myself as maintainer)

### CODE REVIEW

**Comment by jagajaga** [comment]
Have you tested it locally?

**Comment by vcunat** [comment]
Would you coordinate with #6964?

**Comment by mirdhyn** [comment]
I tested it locally and currently using it.

**Comment by Fuuzetsu** [comment]
#6964 and #6649 both need rebasing as well as coming to agreement which one is to be merged

**Comment by Fuuzetsu** [comment]
Closed in favour of #6964

**Pull request closed without merging**
