### PR TITLE
zoekt: fix homepage url

### PR DESCRIPTION
**Pull request by Sigmanificient**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by kirillrdy — APPROVED** [review]

**Comment by AndersonTorres** [comment]
Lemme adopt this!

**Comment by Sigmanificient** [comment]
> Lemme adopt this!

go ahead, I wanted to adapt it, but i couldn't update it.

On latest commit: 
> `go: go.mod requires go >= 1.22 (running go 1.21.10; GOTOOLCHAIN=local)`

When changing to `buildGo122Module`, i get another failure:
```
error:
       … while calling a functor (an attribute set with a '__functor' attribute)

         at /home/sigmanificient/nixpkgs/lib/customisation.nix:264:13:

          263|     in if missingArgs == {}
          264|        then makeOverridable f allArgs
             |             ^
          265|        # This needs to be an abort so it can't be caught with `builtins.tryEval`,

       … while evaluating a branch condition

         at /home/sigmanificient/nixpkgs/lib/customisation.nix:148:7:

          147|     in
          148|       if isAttrs result then
             |       ^
          149|         result // {

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called with unexpected argument 'buildGoModule'

       at /home/sigmanificient/nixpkgs/pkgs/tools/text/zoekt/default.nix:1:1:

            1| { lib
             | ^
            2| , buildGo122Module
```

**Comment by kirillrdy** [comment]
> > Lemme adopt this!
> 
> @AndersonTorres go ahead, I wanted to adapt it, but i couldn't update it. Do you want me to add you in this pr?
> 
> On latest commit:
> 
> ```
> go: go.mod requires go >= 1.22 (running go 1.21.10; GOTOOLCHAIN=local)
> ```
> 
> When changing to `buildGo122Module`, i get another failure:
> 
> ```
> error:
>        … while calling a functor (an attribute set with a '__functor' attribute)
> 
>          at /home/sigmanificient/nixpkgs/lib/customisation.nix:264:13:
> 
>           263|     in if missingArgs == {}
>           264|        then makeOverridable f allArgs
>              |             ^
>           265|        # This needs to be an abort so it can't be caught with `builtins.tryEval`,
> 
>        … while evaluating a branch condition
> 
>          at /home/sigmanificient/nixpkgs/lib/customisation.nix:148:7:
> 
>           147|     in
>           148|       if isAttrs result then
>              |       ^
>           149|         result // {
> 
>        (stack trace truncated; use '--show-trace' to show the full trace)
> 
>        error: function 'anonymous lambda' called with unexpected argument 'buildGoModule'
> 
>        at /home/sigmanificient/nixpkgs/pkgs/tools/text/zoekt/default.nix:1:1:
> 
>             1| { lib
>              | ^
>             2| , buildGo122Module
> ```

@Sigmanificient you should change buildGo122Module in all-packages.nix as per

https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#changing-implicit-attribute-defaults

**Comment by Aleksanaa** [comment]
```
nix-repl> buildGoModule == buildGo122Module
true
```

No, your fork is probably outdated

**Comment by Sigmanificient** [comment]
@Aleksanaa @kirillrdy I'll let @AndersonTorres update it then

**Comment by Sigmanificient** [comment]
@AndersonTorres Have Fun!

**Pull request merged**
