### PR TITLE
Various crystal improvements

### LINKED ISSUE #131268: Crystal broken on darwin/macOS (not just 0.32.x)
### Describe the bug
From macOS/darwin I cannot build the `crystal` package.

### Steps To Reproduce
1. Get a Mac or find someone with a Mac :D
2. Ensure you are on the `nixpkgs-unstable` channel.
3. Execute `nix-shell -p crystal`.
4. Observe the package being broken.

Here's my output:
```sh
$ nix-shell -p crystal
error: Package ‘crystal-0.32.1’ in /nix/store/z18rhsp1qlh56kgrfjzv9k5ad1hy9brz-nixpkgs-21.11pre303315.16105403bdd/nixpkgs/pkgs/development/compilers/crystal/default.nix:212 is marked as broken, refusing to evaluate.

a) To temporarily allow broken packages, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_BROKEN=1

b) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

### Expected behavior
I expect `crystal` 1.0 to install. That it seems to be installing 0.32.1 is surprising to me.

### Additional context
I have looked around for current and prior issues regarding this, but didn't see any. My apologies if I've missed something obvious in my notes below. My Nix knowledge is still in its infancy.

[This line](https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/development/compilers/crystal/default.nix#L279) suggests to me that 1.0 is installed by default, but [this line](https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/development/compilers/crystal/default.nix#L218) seems to be what is being executed (0.32 being unable to install on macOS). [This comment](https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/development/compilers/crystal/default.nix#L28-L31) indicates some version chaining might be going on, but I might be grasping at straws.

My understanding is the `binary` attribute is sort of being derived in a chained fashion, but the derivation is configured such that the most recent version provides the overrides. So I wouldn't expect there to be any problems with this package since I have not indicated to install 0.32.x.

I have also tried `nix-shell -p crystal_1_0`. It provides the same messages re: 0.32.1.

Running the commands again with `NIXPKGS_ALLOW_BROKEN=1` does start a build, but again it tries to build 0.32.1. This ultimately fails with the same reason listed in the [derivation's comment for breaking 0.32.x](https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/development/compilers/crystal/default.nix#L217). Using `crystal_1_0` produces the same behavior.

### Notify maintainers
@david50407 @fabianhjr @manveru @peterhoeg 

@SuperSandro2000's [commit](https://github.com/NixOS/nixpkgs/commit/2ab8b31520fd5d2384e2a81b3bb358ffc1f7a747) has put in the relevant line, but I don't think this is the cause. Without it I'd still encounter a failure, just later.

### Metadata

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/hsp7hzwkfqf5vx898a6xbqn0122axry2-DarwinTools-1
  /nix/store/j2n24ws0w3956cqq6c311ks42q22c75j-nix-info
copying path '/nix/store/hsp7hzwkfqf5vx898a6xbqn0122axry2-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/j2n24ws0w3956cqq6c311ks42q22c75j-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(logan): `"home-manager"`
 - channels(root): `"nixpkgs-21.11pre303315.16105403bdd, home-manager"`
 - nixpkgs: `/Users/logan/.nix-defexpr/channels/nixpkgs`
```

I'm taking best guess on the attributes.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: crystal shards oq
# a list of nixos modules affected by the problem
module:
```
### Appreciation

Thanks everyone for maintaining this project! Nix controls my entire local setup, and there's no going back to manual installs again :)

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change

darwin builds were broken for all above 0_32
because 0_32 was marked broken and thus broke the dependency chain
Should close #131268

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
opinions on removing old crystal versions?

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131808` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>oq</li>
    <li>thicket</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>ameba</li>
    <li>crystal (crystal_1_0)</li>
    <li>crystal2nix</li>
    <li>crystal_0_36</li>
    <li>icr</li>
    <li>lucky-cli</li>
    <li>mint</li>
    <li>scry</li>
    <li>shards (shards_0_15)</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> opinions on removing old crystal versions?

I don't think that is a problem if they are unused.

**Comment by siraben** [comment]
Build failures on darwin:

- `oq` http://ix.io/3yo5
- `thicket` http://ix.io/3yo6

**Comment by Artturin** [comment]
merging in 2 days if there are no objections

**Comment by fabianhjr** [comment]
No objections here, LGTM but can't test macOS unbreaking.

**Comment by siraben** [comment]
Reviewing again tonight (UTC -5) on macOS.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131808` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>ameba</li>
    <li>crystal (crystal_1_0)</li>
    <li>crystal2nix</li>
    <li>crystal_0_36</li>
    <li>icr</li>
    <li>lucky-cli</li>
    <li>mint</li>
    <li>oq</li>
    <li>scry</li>
    <li>shards (shards_0_15)</li>
    <li>thicket</li>
  </ul>
</details>

**Comment by siraben** [comment]
```
$ nix log /nix/store/dhr9b6rpnbl6lwz6q9nr02mmzgp9q4f3-crystal-0.36.1.drv | ix
http://ix.io/3zwQ
```

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131808` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>ameba</li>
    <li>crystal (crystal_1_0)</li>
    <li>crystal2nix</li>
    <li>crystal_0_36</li>
    <li>icr</li>
    <li>lucky-cli</li>
    <li>mint</li>
    <li>oq</li>
    <li>scry</li>
    <li>shards (shards_0_15)</li>
    <li>thicket</li>
  </ul>
</details>

**Comment by siraben** [comment]
Might be a spurious error (impurity?). Re-running.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131808` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>ameba</li>
    <li>crystal (crystal_1_0)</li>
    <li>crystal2nix</li>
    <li>crystal_0_36</li>
    <li>icr</li>
    <li>lucky-cli</li>
    <li>mint</li>
    <li>oq</li>
    <li>scry</li>
    <li>shards (shards_0_15)</li>
    <li>thicket</li>
  </ul>
</details>

**Comment by Artturin** [comment]
The rm is run here 
https://github.com/NixOS/nixpkgs/blob/3c041ff9302b9350affe09a1ad87e6352b40d41b/pkgs/development/compilers/crystal/default.nix#L106

**Comment by abathur** [comment]
I ran nixpkgs-review on this per request from @siraben on matrix

<details><summary>log</summary>

```console
$ nixpkgs-review pr 131808
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/131808/head:refs/nixpkgs-review/1
remote: Enumerating objects: 8903, done.
remote: Counting objects: 100% (4017/4017), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 8903 (delta 3984), reused 3998 (delta 3977), pack-reused 4886
Receiving objects: 100% (8903/8903), 7.89 MiB | 1.91 MiB/s, done.
Resolving deltas: 100% (6267/6267), completed with 1129 local objects.
From https://github.com/NixOS/nixpkgs
   78230d1c42c..16483464441  master                -> refs/nixpkgs-review/0
   b7387c5cf46..3c041ff9302  refs/pull/131808/head -> refs/nixpkgs-review/1
$ git worktree add /Users/abathur/.cache/nixpkgs-review/pr-131808/nixpkgs 16483464441212d6b0c213c01dc06747d38831ea
Preparing worktree (detached HEAD 16483464441)
Updating files: 100% (27917/27917), done.
HEAD is now at 16483464441 Merge pull request #136022 from hercules-ci/fetcher-testing
$ git merge --no-commit --no-ff 3c041ff9302b9350affe09a1ad87e6352b40d41b
Auto-merging pkgs/top-level/all-packages.nix
Auto-merging pkgs/applications/version-management/git-and-tools/thicket/default.nix
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going -f /Users/abathur/.cache/nixpkgs-review/pr-131808/build.nix
error: builder for '/nix/store/dhr9b6rpnbl6lwz6q9nr02mmzgp9q4f3-crystal-0.36.1.drv' failed with exit code 2;
       last 10 log lines:
       > build flags: -j4 -l4 SHELL=/nix/store/j4bf4z7zrd461r4bjiwsrnzc5am0jv9a-bash-4.4-p23/bin/bash CRYSTAL_CONFIG_VERSION=0.36.1 all docs
       > Using /nix/store/m3r89fg3h2w21x0zspg9kz89vl9wirq8-llvm-10.0.1-dev/bin/llvm-config [version=10.0.1]
       > clang++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/nix/store/m3r89fg3h2w21x0zspg9kz89vl9wirq8-llvm-10.0.1-dev/include -std=c++14 -stdlib=libc++  -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
       > clang -fPIC    -c -o src/ext/sigfault.o src/ext/sigfault.c
       > ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
       > CRYSTAL_CONFIG_LIBRARY_PATH="" CRYSTAL_CONFIG_BUILD_COMMIT="" SOURCE_DATE_EPOCH="1632229840" ./bin/crystal build --release --single-module --threads 4  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
       > ./bin/crystal: line 156: crystal: command not found
       > ./bin/crystal: /nix/store/ajd56xc2z5ri9gsxp8zmd5ga14nj7rah-crystal-binary-0.36.1/bin/crystal: /usr/bin/env: bad interpreter: Operation not permitted
       > ./bin/crystal: line 167: /nix/store/ajd56xc2z5ri9gsxp8zmd5ga14nj7rah-crystal-binary-0.36.1/bin/crystal: Undefined error: 0
       > make: *** [Makefile:122: .build/crystal] Error 1
       For full logs, run 'nix log /nix/store/dhr9b6rpnbl6lwz6q9nr02mmzgp9q4f3-crystal-0.36.1.drv'.
error: 1 dependencies of derivation '/nix/store/nsjvx003d0qh696b8jsap3kvpl2rwxix-crystal-1.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b4izsp2a0c5z928bqaplb4aqrr08raqx-lucky-cli-0.26.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0n9vx94jwi9j0nd8xr3sbgbzfaxa3lvw-shards-0.15.0.drv' failed to build
error: 2 dependencies of derivation '/nix/store/z2h74lzn1b2y54igpsrcphldvw49vsip-ameba-0.14.3.drv' failed to build
error: 2 dependencies of derivation '/nix/store/519ibzhhc6x32ccc2pvfrghsgan6sk39-crystal2nix-0.1.1.drv' failed to build
error: 2 dependencies of derivation '/nix/store/0w05nl5qsi28yrdr7n3xifr6ncd8nqzn-icr-unstable-2021-03-14.drv' failed to build
error: 2 dependencies of derivation '/nix/store/7lc1wm3aln7c7dgb0fs1xkrz6i1vbf6i-mint-0.14.0.drv' failed to build
error: 2 dependencies of derivation '/nix/store/cnbdqjpffhngpxfy9j8l5bja5lic40jg-oq-1.3.0.drv' failed to build
error: 2 dependencies of derivation '/nix/store/m3rz1kfigkm4y9qfrk86yasf58ad9yc4-scry-0.9.1.drv' failed to build
error: 2 dependencies of derivation '/nix/store/grrmlfsixgynwrcmpq56y6mi2s2fnxv2-thicket-0.1.5.drv' failed to build
error: 11 dependencies of derivation '/nix/store/i2ymx76pa80hb9649iv8h3f4mahlj0mb-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/131808

11 packages failed to build:
ameba crystal crystal2nix crystal_0_36 icr lucky-cli mint oq scry shards thicket

error: build log of '/nix/store/z2h74lzn1b2y54igpsrcphldvw49vsip-ameba-0.14.3.drv' is not available
error: build log of '/nix/store/9zw09wgngl1s8fn722w946ly2707pra9-ameba-0.14.3' is not available
error: build log of '/nix/store/nsjvx003d0qh696b8jsap3kvpl2rwxix-crystal-1.0.0.drv' is not available
error: build log of '/nix/store/l4bxmlbgisrgc10c5hjh3cgh58jzg29m-crystal-1.0.0' is not available
error: build log of '/nix/store/519ibzhhc6x32ccc2pvfrghsgan6sk39-crystal2nix-0.1.1.drv' is not available
error: build log of '/nix/store/n09mavaz12fv2cp4gsz13bvczs8bmdxw-crystal2nix-0.1.1' is not available
$ nix-shell /Users/abathur/.cache/nixpkgs-review/pr-131808/shell.nix
```

**Comment by Artturin** [comment]
@abathur send the log of the build
If you dont have nix log then start a nix shell with nixUnstable
```
nix log /nix/store/dhr9b6rpnbl6lwz6q9nr02mmzgp9q4f3-crystal-0.36.1.drv```

**Comment by abathur** [comment]
I've updated the original comment to add this

**Review by manveru — APPROVED** [review]
LGTM

**Comment by Artturin** [comment]
Continuing troubleshooting in the `Nix on macOS channel` on matrix
https://matrix.to/#/!lheuhImcToQZYTQTuI:nixos.org/$6xj00TcytHth3UrvsUCSZS9Rh_05pcFeQKaSwei2yKU?via=matrix.org&via=mtr.ceph3.us&via=nixos.dev

**Comment by Artturin** [comment]
Issue should be solved

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131808` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>ameba</li>
    <li>crystal (crystal_1_0)</li>
    <li>crystal2nix</li>
    <li>crystal_0_36</li>
    <li>icr</li>
    <li>lucky-cli</li>
    <li>mint</li>
    <li>oq</li>
    <li>scry</li>
    <li>shards (shards_0_15)</li>
    <li>thicket</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131808` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>ameba</li>
    <li>crystal2nix</li>
    <li>icr</li>
    <li>lucky-cli</li>
    <li>mint</li>
    <li>oq</li>
    <li>scry</li>
    <li>shards (shards_0_15)</li>
    <li>thicket</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>crystal (crystal_1_0)</li>
    <li>crystal_0_36</li>
  </ul>
</details>

**Comment by Artturin** [comment]
Logs?

**Comment by toonn** [comment]
Ran `nixpkgs-review pr 131808 -p shards`, here's the `shards.log`.
[shards.log](https://github.com/NixOS/nixpkgs/files/7232214/shards.log)

**Comment by Artturin** [comment]
i couldn't find a source for why upstream doesn't recommend `--no-debug` so i readded it

**Pull request merged**
