### PR TITLE
nixos/nextcloud: Add support for caddy webserver

### PR DESCRIPTION
**Pull request by onny**
###### Description of changes

This PR adds support for caddy webserver. Everything should work as before but with this you'll be able to choose between Nginx and Caddy as a web server:
```
services.nextcloud = {
  enable = true;
  webserver = "caddy";
}
```

- [x] Update tests
- [x] Update release notes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
I'm pretty sure in the past the maintainers explicitly rejected supporting multiple web servers due to the already complex module code.

**Comment by onny** [comment]
> I'm pretty sure in the past the maintainers explicitly rejected supporting multiple web servers due to the already complex module code.

Maybe we can merge this as an exception? UwU ^^

**Comment by Ma27** [comment]
Sorry, but I'll remain opposed to the proposed change:

* maintaining HTTP routing for several webservers shifts an additional maintenance workload towards the Nextcloud maintainers that I'm not willing to take. Yes, we also support e.g. multiple database systems here, but in contrast to what the HTTP server is supposed to do it's a rather trivial thing IMHO (to be clear, it's already non-trivial on certain occasions to keep the nginx config working for several majors, so this is not about laziness from my side).
* there's some documentation in the manual on how to configure nextcloud with an alternative reverse proxy using httpd as example. This is also supposed to work with caddy instead.
* speaking of httpd, httpd and nginx are the most popular reverse-proxies/webservers out there and we already decided against directly implementing httpd support into the module, so I don't see any reason why we should make an exception now for an even less popular one (even though I acknowledge that there are fair reasons for caddy to be used).
* Finally, if we want to make our services modules independent of a reverse proxy (which is needed in case of e.g. php/phpfpm applications), we should do it as suggested in https://github.com/NixOS/nixpkgs/issues/22067 by implementing a "global" solution rather than blowing up every single module.

Hence I'm closing, from my PoV that's all to say about it. If there are some reasons you feel that haven't been addressed here, feel free to leave a comment anyways!

**Comment by onny** [comment]
Is someone still interested in using Caddy as a webserver, I added a practical configuration example to the NixOS wiki https://nixos.wiki/wiki/Nextcloud#Use_Caddy_as_webserver

**Comment by Alper-Celik** [comment]
thanks for pointers @onny , tho your config deviates from upstream config in some place like some security options and such.

tbf config isnt that hard and if mainainers have changed their mind i would like to contribute and maintain a caddy config for the nextcloud module. even if maintainers still dont want it i think i might extract and do a more comperhensive nextcloud caddy nixos module that follows upstream nginx config more closely.

also it is kinda intresting how nextcloud-aio project uses caddy in front of httpd instead.

also i wonder would using franken php be possible or prefferable tho i am really inexperienced on php side of things.

also i will convert my collabara online config to caddy too i think so i might try creating a pr for it too. 

my current state of it : https://github.com/Alper-Celik/MyServers/blob/rpi5-caddy/rpi5/nextcloud.nix#L81

refeences i used:
- @onny 's config https://github.com/onny/nixos-nextcloud-testumgebung/blob/c3fdbf165814d403a8f8e81ff8e15adcbe7eadd0/nextcloud-extras.nix#L131
- upstream nginx config https://docs.nextcloud.com/server/33/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx

**Pull request closed without merging**
