### PR TITLE
vdirsyncer: 0.16.7 -> 0.16.8

### PR DESCRIPTION
**Pull request by DamienCassou**
###### Motivation for this change

Fix the broken vdirsyncer and update it to latest stable version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by DamienCassou** [comment]
Result of `nixpkgs-review pr 91918` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
<br>- python37Packages.vdirsyncerStable
<br>- vdirsyncerStable (python38Packages.vdirsyncerStable)
</details>

**Comment by loewenheim** [comment]
`❯ nix-shell -p nixpkgs-review --run "nixpkgs-review pr 91918"` fails on my computer:

```
=========================== short test summary info ============================
  FAILED tests/system/cli/test_sync.py::test_create_collections - hypothesis.er...
  ===== 1 failed, 370 passed, 115 skipped, 1841 warnings in 78.89s (0:01:18) =====
  make: *** [Makefile:62: test] Error 1
builder for '/nix/store/7hag97771kypmh1g56brsvnvrgjrgx3i-python3.8-vdirsyncer-0.16.8.drv' failed with exit code 2; last 10 log lines:

  tests/unit/sync/test_status.py::test_legacy_status[SqliteStatus]
    /nix/store/dilqhyr1nljs1xsn7237qr65j3z8kjs0-python3.8-hypothesis-5.11.0/lib/python3.8/site-packages/hypothesis/extra/pytestplugin.py:170: HypothesisDeprecationWarning: tests/unit/sync/test_status.py::test_legacy_status[SqliteStatus] uses the 'new_status' fixture, which is reset between function calls but not between test cases generated by `@given(...)`.  You can change it to a module- or session-scoped fixture if it is safe to reuse; if not we recommend using a context manager inside your test function.  See https://docs.pytest.org/en/latest/fixture.html#sharing-test-data for details on fixture scope.
      note_deprecation(msg % (fx.argname,), since="2020-02-29")

  -- Docs: https://docs.pytest.org/en/latest/warnings.html
  =========================== short test summary info ============================
  FAILED tests/system/cli/test_sync.py::test_create_collections - hypothesis.er...
  ==== 1 failed, 370 passed, 115 skipped, 22760 warnings in 269.58s (0:04:29) ====
  make: *** [Makefile:62: test] Error 1
cannot build derivation '/nix/store/j5niwjlini18smddzywpjwvpwrkprrls-env.drv': 2 dependencies couldn't be built
[0 built (2 failed)]
error: build of '/nix/store/j5niwjlini18smddzywpjwvpwrkprrls-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/91918
2 packages failed to build:
python37Packages.vdirsyncerStable vdirsyncerStable
```

I might be doing something wrong.

**Comment by DamienCassou** [comment]
@loewenheim can you please tell me what your system is?

**Comment by loewenheim** [comment]
Sorry, of course.

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.48, NixOS, 20.03.2411.30fb4e1e206 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"home-manager-20.03, nixos-20.03.2411.30fb4e1e206"`
 - channels(loewenheim): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by DamienCassou** [comment]
Thank you @loewenheim. If you try several times, do you always get the same error message? Can you please try with `nix-build --keep-failed` and send me the test logs?

**Comment by loewenheim** [comment]
Strange, checking out the PR and running `nix-build` works fine:

```
❯ git log
commit 0a8e6ae5093552a471c8e1027227d7d3988424b7 (HEAD -> vdirsyncer, refs/nixpkgs-review/1)
Author: Damien Cassou <damien@cassou.me>
Date:   Wed Jul 1 09:15:51 2020 +0200

    vdirsyncer: 0.16.7 -> 0.16.8

…
```

```
❯ nix-build -A vdirsyncerStable --keep-failed -I .
/nix/store/i0s6mhrfhwiswgvax6zi2jl0mj9728cm-python3.8-vdirsyncer-0.16.8
```
But `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 91918"` still fails. Apparently it tries to build `vdirsyncerStable` wtih Python 3.7, maybe that's the issue?

**Comment by DamienCassou** [comment]
@loewenheim Can you please try the 2 expressions below, one for 3.7 and one for 3.8?

- `nix-build https://github.com/NixOS/nixpkgs/archive/0a8e6ae5093552a471c8e1027227d7d3988424b7.tar.gz -A python37Packages.vdirsyncerStable`
- `nix-build https://github.com/NixOS/nixpkgs/archive/0a8e6ae5093552a471c8e1027227d7d3988424b7.tar.gz -A python38Packages.vdirsyncerStable`

They both work for me.

**Comment by loewenheim** [comment]
Yeah, the first one fails for me.
```
=================================== FAILURES ===================================
___________________________ test_create_collections ____________________________
tests/system/cli/test_sync.py:276: in test_create_collections
    reason='This test inexplicably fails')
/nix/store/4wj26hranp62j09cazrssmkkq2zfwzyr-python3.7-hypothesis-5.11.0/lib/python3.7/site-packages/hypothesis/core.py:643: in execute_once
    % (test.__name__, text_repr[0])
/nix/store/4wj26hranp62j09cazrssmkkq2zfwzyr-python3.7-hypothesis-5.11.0/lib/python3.7/site-packages/hypothesis/core.py:848: in __flaky
    raise Flaky(message)
E   hypothesis.errors.Flaky: Hypothesis test_create_collections(subtest=inner, collections={'\x05',
E    '\t',
E    "\n\U00018f66\x1d'\U000fd929\U000db061,\U00057d1e\x11",
E    '\x0f+\x05\x0e\U000c8223\x1f',
E    '\x0f\U000bf788\U000da5ef',
E    '\x1d&\U000494fa\r\U000b1fd6)\n',
E    '\x1d\U000ee1e2\U000dbe05\U000b917e',
E    '\x1f\x1c',
E    ') \U000b2729\U000ffb17\U0009e7d9\x13 ',
E    '͋𑪘\x010',
E    'ᢑ\U0002fc09\U000fa73b\x04\U0006e46d$',
E    '𑵂\x06𣗷',
E    '\U00037cb7\U000e9d6e\x02\U0008c1ff\x11\U00011fe6\x07\x0f$\U00067cdb\U0004a4c1"#𗚻\n\x0e',
E    '\U00057595',
E    '\U00065dcb\U0001d29f\U00096a05\U0006f139\U000e9154\U00095f2a\U000d963a\U0007edd7%\U00094f02',
E    '\U000c942a\U0009b03f\U000d5cec\U0001bb65\U0008f2f4,',
E    '\U000d0953\x14\U000c4c72\U000a7533',
E    '\U000e4200\U00055ef9',
E    '\U0010c072\U000ea6b7$\U0004ab9d\U000a8bd0\x17\U000bad5e\x08\U000a740e\U0009f85b\t\x16\U000b83fa'}) produces unreliable results: Falsified on the first call but did not on a subsequent one
```

**Comment by marsam** [comment]
@GrahamcOfBorg build vdirsyncerStable

**Comment by DamienCassou** [comment]
Result of `nixpkgs-review pr 91918` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
<br>- python37Packages.vdirsyncerStable
<br>- vdirsyncerStable (python38Packages.vdirsyncerStable)
</details>

**Comment by DamienCassou** [comment]
@loewenheim can you please test the new commit?

@marsam thank you for your changes to this PR.

**Comment by loewenheim** [comment]
`nix-build https://github.com/NixOS/nixpkgs/archive/318fd31ee96aca1b5c67050ca0dd119d398c3d.tar.gz -A python37Packages.vdirsyncerStable`

and

`nix-build https://github.com/NixOS/nixpkgs/archive/318fd31ee96aca1b5c67050ca0dd119d398c3d.tar.gz -A python38Packages.vdirsyncerStable`

both work for me now.

**Pull request merged**
