### PR TITLE
zathura: 0.4.5 -> 0.4.7

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
fix https://github.com/NixOS/nixpkgs/pull/100441#issuecomment-726762347

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
actually, doesn't fix the problem. But this problem has been identified here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237770

**Comment by jonringer** [comment]
@timokau the pdf-mupdf extension wasn't linking against anything, I fixed that

**Review by timokau — APPROVED** [review]
Looks  good to me, thank you!

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/103727
1 package built:
zathura
```

**Comment by delroth** [comment]
It turns out that this was probably the wrong fix: see #237199 which addresses the actual root cause of that issue.

Yes, about 3 years late with that comment, not sure if you want to follow up on this or leave it to the current maintainers :-)

**Pull request merged**
