### PR TITLE
valhalla: 3.1.0 -> 3.4.0

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Diff: https://github.com/valhalla/valhalla/compare/3.1.0...3.4.0

Changelog: https://github.com/valhalla/valhalla/blob/3.4.0/CHANGELOG.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Thra11 — CHANGES_REQUESTED** [review]
Unfortunately, osmscout-server doesn't yet support valhalla 3.4 (See [here](https://github.com/rinigus/osmscout-server/issues/418) and [here](https://github.com/rinigus/osmscout-server/tree/master/data)). Since osmscout-server is currently the only package in nixpkgs which uses valhalla, I have kept valhalla at 3.1 until it supports 3.4 (in theory, osmscout-server supports valhalla 3.2.1, but I've only tried updating to 3.4 so far).

**Comment by dotlambda** [comment]
Valhalla is currently broken on master. This PR would at least fix valhalla while leaving osmscout-server broken.

**Comment by Thra11** [comment]
I would rather have valhalla visibly broken in hydra than osmscout-server less-visibly broken because it crashes on startup. The problem is that #247563 was merged without proper testing (darwin supports a limited subset of packages, and it was only tested on darwin).

I am working on getting osmscout-server to support valhalla 3.4.0. In the meantime, I would suggest either reverting #247563 until it can be merged without breaking things or just waiting.

**Comment by dotlambda** [comment]
Do you know which commit between 3.1.0 and 3.4.0 fixes the build of valhalla with libspatialite 5.1.0? Maybe we could apply that as a patch.

**Review by Thra11 — APPROVED** [review]
In combination with #250142, this looks good to me.

**Review by Thra11 — APPROVED** [review]
I guess if we want to be super pedantic, the osmscout-server commit should precede the valhalla commit, since the osmscout-server change makes it possible to use valhalla 3.4.0, but still works with valhalla 3.1.0. However, since they're both already broken, it's not super important as long as they both end up fixed when the PR is merged.

**Pull request merged**
