### PR TITLE
nixos/libvirtd: adds support for swtpm

### PR DESCRIPTION
**Pull request by baloo**
###### Motivation for this change

The purpose is to provide VMs running on libvirt the capability to run with TPM support.
swtpm itself has been merged with #113362

This PR is not enough to get a good UX for TPM support.

swtpm is finicky about it's configuration.
The way I'm currently running libvirt is like that:
```
let
  issuer = pkgs.writeText "issuer.key" ''
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----
  '';

  cert = pkgs.writeText "issuer.pem" ''
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
  '';

  swtpm_localca_config = pkgs.writeText "swtpm-localca.conf" ''
    certserial=/var/lib/libvirt/swtpm/serial
    statedir=/var/lib/libvirt/swtpm
    signingkey=${issuer}
    issuercert=${cert}
  '';

  swtpm_config = pkgs.writeText "swtpm_setup.conf" ''
    create_certs_tool=${swtpm}/share/swtpm/swtpm-localca
    create_certs_tool_config=${swtpm_localca_config}
    create_certs_tool_options=${swtpm}/etc/swtpm-localca.options
  '';

  swtpm' = pkgs.stdenv.mkDerivation {
    name = "swtpm-wrappers";
    buildInputs = [ pkgs.makeWrapper ];
    buildCommand = ''
      mkdir -p $out/bin
      makeWrapper ${swtpm}/bin/swtpm_setup "$out/bin/swtpm_setup" \
         --add-flags "--config=${swtpm_config}"
      for executable in swtpm swtpm_ioctl swtpm_bios swtpm_cert swtpm_cuse
      do
        ln -s "${swtpm}/bin/$executable" "$out/bin/$executable"
      done
      mkdir -p "$out/share"
      ln -s '${swtpm}/share/man' "$out/share/"
    '';
  };
in {
  virtualisation.libvirtd = {
    enable = true;
    qemuOvmf = true;

    tpmSupport = true;
    tpmPackage = swtpm';
  };
}
```
But that sounds like a ton of work for the end-user.
Any idea is most welcome.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by baloo** [comment]
For a bit more context and motivation of this change:
https://github.com/baloo/reproducibility-lab#lab-requirements

**Comment by peterhoeg** [comment]
Wouldn't it be *much* easier to have `swtpm` look in a predefined global location (such as `/etc`) if it doesn't already do, and then use the module to write the configuration in there? You wouldn't have to do all the wrappers then.

**Comment by Informatic** [comment]
Is issuer/signer really needed to be declared in nix? Seems like swtpm issuer/signer keys are autogenerated on first `swtpm_setup` use, and just the default config file needs to be fixed to not point at `/nix/store` path which needs to be writable. (also `gnutls` needs to be present in `$PATH`)

https://github.com/Informatic/nixpkgs/commit/c58feab12c8365a49470aac0892aa27655e148b8 seems to work for me (pulled into nixos 20.09, with `swtpm` added to `systemd.services.libvirtd.path`)

**Comment by baloo** [comment]
@Informatic that's a good point, any chance you could send a PR for your swtpm patch?

**Comment by Luflosi** [comment]
All changes proposed in this PR seem to have been implemented in #141242 and #142032. The options are now called `virtualisation.libvirtd.qemu.swtpm.enable` and `virtualisation.libvirtd.qemu.swtpm.package`.
Please reopen this PR if I missed something.

**Pull request closed without merging**
