### PR TITLE
opera:	46.0.2597.39	->	48.0.2685.52

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

minor update

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg opera

**Comment by NeQuissimus** [comment]
I can't run this...

```
λ ./result/bin/opera   

** (opera:7057): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[1107/073537.947118:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/qf58dxl5ddi0q4rqmsl8yq1ymrkjqhhf-opera-48.0.2685.52/lib/x86_64-linux-gnu/opera/opera_sandbox is owned by root and has mode 4755.
#0 0x000001cbca87 <unknown>
#1 0x000001cd1c01 <unknown>
#2 0x000002ce62c1 <unknown>
#3 0x000000f67351 <unknown>
#4 0x000000f66816 <unknown>
#5 0x000000f66d2d <unknown>
#6 0x000000c132c5 <unknown>
#7 0x000000c198b9 <unknown>
#8 0x00000078d976 <unknown>
#9 0x000001cb6afe <unknown>
#10 0x000001cb742d <unknown>
#11 0x000002cf2e77 <unknown>
#12 0x000001cb60b2 <unknown>
#13 0x0000004294ec OperaMain
#14 0x62e044b72560 __libc_start_main
#15 0x000000428860 <unknown>

[1107/073537.981282:INFO:opera_paths.cc(388)] Directory /etc/.config/opera created succesfully.
[1]    7057 abort      ./result/bin/opera
```

**Comment by Mic92** [comment]
Looks similar to the chromium setuid wrapper. We have a nixos module for that.

**Comment by NeQuissimus** [comment]
Oh yeah, I forgot that Opera and Chrome are basically the same now...

**Comment by NeQuissimus** [comment]
@volth Can you replace the tabs with spaces in the commit message?

**Comment by volth** [comment]
This works for me without any wrappers, on July 2017 master.
Were the any changes?

**Comment by Mic92** [comment]
@NeQuissimus does your kernel have username-spaces enabled?

**Comment by NeQuissimus** [comment]
It does not, if that's the only issue, it's all good.

**Pull request merged**
