### PR TITLE
zigbee2mqtt: clean up & update script improvements

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
These are changes I still had lying around since I last worked on the package.

I failed to update it to a recent version (>1.20.0) since it now wants to use `npm` to build the project at runtime: https://github.com/Koenkk/zigbee2mqtt/blob/master/index.js#L43-L57

In the meantime I've migrated my personal setup to use OCI containers. I don't know how to continue any other way.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sweber83** [comment]
@mweinelt 
Is the only problem, which prevents us to get to a current version the newly introduced typescript compilation?
If that's the case, we can solve the problem without too much work.
When zigbee2mqtt is started, it first looks for a specific file in the `dist` folder and only continues to run the build script, if the file is not found.
All we have to do is call `npm run build` in the `postInstall` hook.
Since the `typescript` package is part of the dev dependencies, we also have to pass the `--development` flag to node2nix.
I already implemented this here: https://github.com/sweber83/nixpkgs/commit/003b89ea6604e38992843adba03f5e743c66ea2b

What I'm having trouble with, is the update script.

The first problem is, that the `nix eval` subshell, which is used to determine the current package version, errors with this message: "error: '(with import ../../.. {}; zigbee2mqtt.version)' is not a valid URL"
I can get it to work if I pass the flags `--impure --raw --expr`, but I'm not sure if this is the way to go.

The second problem is with the node env.
If I use the node-env from nixpkgs, I get the error "called without required argument 'writeShellScript".
I'm not sure what to do, except use the local node-env.

Do you have any tips on how to handle these issues?

**Comment by sweber83** [comment]
I just saw, that you already solved the `nix eval` issue.

**Comment by sweber83** [comment]
I went ahead and started with your changes here, and applied the commit, which adds the build step on top.
Now I get a new (to me) error.
This time it's from `update-source-version`.
The message reads 
```
error: undefined variable 'outPath'

       at «string»:1:86:

            1| with (let tree = import ./.; in if builtins.isFunction tree then tree {} else tree); outPath
             |                                                                                      ^
```

**Comment by mweinelt** [comment]
It does error out like this, but check `git diff`. It does update version and hash.

**Comment by sweber83** [comment]
Yes, it indeed does.
I'll open a new PR for version 1.22.1.

**Pull request merged**
