### PR TITLE
cemu: 2.0-36 -> 2.0-39

### PR DESCRIPTION
**Pull request by lasers**
###### Description of changes

Version bump. https://github.com/cemu-project/Cemu/compare/v2.0-36...v2.0-39

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lasers** [comment]
Friendly ping @NickCao

**Comment by NickCao** [comment]
It now tries dlopen libgamemode at runtime, shall we patch that to absolute path: https://github.com/cemu-project/Cemu/blob/eda4cf4b241d56c5c16f6aa4d135b8a269676a76/dependencies/gamemode/lib/gamemode_client.h#L190

**Comment by lasers** [comment]
Sorry. I'm a nix noob. I tried this.
```diff
diff --git a/pkgs/applications/emulators/cemu/default.nix b/pkgs/applications/emulators/cemu/default.nix
index 4a2b846..19dc659 100644
--- a/pkgs/applications/emulators/cemu/default.nix
+++ b/pkgs/applications/emulators/cemu/default.nix
@@ -23,7 +23,7 @@
 , wayland
 , wxGTK32
 , zarchive
-
+, gamemode
 , vulkan-loader
 
 , nix-update-script
@@ -80,6 +80,7 @@ stdenv.mkDerivation rec {
     "-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG"
     "-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG"
     "-DENABLE_VCPKG=OFF"
+    "-DENABLE_FERAL_GAMEMODE=ON"
 
     # PORTABLE:
     # "All data created and maintained by Cemu will be in the directory where the executable file is located"
@@ -92,6 +93,7 @@ stdenv.mkDerivation rec {
     rm -rf dependencies/imgui
     ln -s ${imgui}/include/imgui dependencies/imgui
     sed 's/\(EMULATOR_VERSION_SUFFIX\).*experimental.*/\1 "-${tag} (experimental)"/' -i src/Common/version.h
+    substituteInPlace dependencies/gamemode/lib/gamemode_client.h --replace "libgamemode.so.0" "${gamemode.lib}/lib/libgamemode.so.0"
   '';
 
   installPhase = ''

```
I then enabled Feral GameMode in Cemu... and relaunched... Started a game... I got...
```
❯ ./cemu/bin/cemu 

(cemu:210477): Gtk-CRITICAL **: 07:09:26.706: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
GameMode ERROR: D-Bus error: Could not call method 'RegisterGame' on 'com.feralinteractive.GameMode': The name com.feralinteractive.GameMode was not provided by any .service files
```

**Comment by NickCao** [comment]
You may have to enable the gamemoded service: `programs.gamemode.enable = true;`

**Comment by lasers** [comment]
I don't see cemu complaining about lack of gamemode and I got `gamemoded` running. I assume it's working.

**Review by NickCao — APPROVED** [review]

**Pull request merged**
