### PR TITLE
glib: fix build on aarch64-darwin

### PR DESCRIPTION
**Pull request by JohnRTitor**
## Description of changes

Fixes build on aarch64-darwin as a followup to #321913.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
@ofborg build glib

My aarch64-darwin builder is currently building bison 😅

**Comment by vcunat** [comment]
We need this for `staging-next`, but you included many commits from `staging-next..staging`.

**Comment by vcunat** [comment]
And your rebuilding everything is exactly because of that.

**Comment by kalbasit** [comment]
I just started building glib on my mac, it'll probably take a while. Do you indent to change the base? Should I cancel and wait for you to rebase?

**Comment by JohnRTitor** [comment]
Should be fine now.

**Comment by JohnRTitor** [comment]
@ofborg build glib

**Review by kalbasit — APPROVED** [review]
The build went great on my mac.

**Review by vcunat — APPROVED** [review]

**Review by trofi — APPROVED** [review]

**Review by jtojnar — APPROVED** [review]
Thanks, probably no need to wait for ofborg since this was already confirmed by a hu-man

**Comment by vcunat** [comment]
It failed there
```
292/341 glib:gio / gsocketclient-slow                                          ERROR             1.73s   killed by signal 6 SIGABRT
```
but probably just an overloaded builder?

**Comment by vcunat** [comment]
Ah no, a sandboxing issue, more likely.
```
GLib-GIO:ERROR:../gio/tests/gsocketclient-slow.c:231:test_connection_failed: assertion failed (local_error == (g-io-error-quark, 39)): Could not connect to localhost: Can't assign requested address (g-io-error-quark, 0)
```

My check was on a machine with defaults (without sandboxing).

**Comment by JohnRTitor** [comment]
Built for me. 
```
johnrtitor@darwin01 ~ % nix build "github:nixos/nixpkgs/refs/pull/322988/merge#glib" --print-out-paths
/nix/store/4dgdwdnc1fl1fi8r4bjylwgm5lcdzahs-glib-2.80.3-bin
```

**Pull request merged**
