### PR TITLE
rw: init at 1.0

### PR DESCRIPTION
**Pull request by dtzWill**
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
> Failure on x86_64-darwin (full log)

https://github.com/macports/macports-ports/commit/03c5aa332d9b62cfeda5fa5e7cf848e82aae506f#diff-b9ba10475be4170003c9abc6de63d1a2

Is there a good way to indicate required OSX version? (cc @NixOS/darwin-maintainers, @Ericson2314)

Would be nice to not have to mark it as known-"broken" on Darwin! :)

**Comment by copumpkin** [comment]
@dtzWill unfortunately not; instead of creating separate platforms for new releases, we opted (for ease of maintenance mostly) to homogenize the macOS platforms by papering over their differences. I think we currently do our best to look like 10.11, which means that `clock_gettime` isn't available. At some point we'll probably drop support for 10.11 and start pretending to be 10.12 or maybe even 10.13, and then this will work, but for now I think it'll be broken, unless you really want it to be available in nixpkgs, in which case you can hack around the limitation in this one derivation.

**Comment by matthewbauer** [comment]
We might be able to hack it in without updating. It's actually pretty simple and lots of things use clock_gettime.

https://opensource.apple.com/source/Libc/Libc-1158.1.2/gen/clock_gettime.c.auto.html
https://opensource.apple.com/source/Libc/Libc-1158.1.2/include/time.h.auto.html

**Comment by LnL7** [comment]
I don't think we can because libSystem/Libc are impure. We explicity only reexport specific symbols so builds on 10.13 work on a 10.10 machine and the other way around.

**Comment by matthewbauer** [comment]
Ok that complicates things a bit. Has anyone looked into making Libc pure? The xcbuild stuff could make it possible now.

**Comment by copumpkin** [comment]
@matthewbauer yes, lots, but it's pretty hard, and parts of it are fundamentally impure because they're an unstable interface to a changing kernel.

Basically, libSystem comprises (among many others):

- Libc (libsystem_c.dylib)
- Xnu's libsystem_kernel.dylib

And Libc is the thing we could conceivably make pure, if we could avoid relying on specifics of libsystem_kernel.dylib. Having said that, the Libc build is a bit of a monster, and I've put some work into it in the past, but even with the native xcodebuild it's pretty tricky.

There's another intermediate "solution" here, which is that the libSystem.dylib we have right now that only reexports symbols doesn't have to limit itself to only reexporting symbols, and could actually contain a nontrivial implementation of functions not reexported, like `clock_gettime`. But having said that, I'd be wary of getting into the business of writing and maintaining our own libc functions 😄

**Comment by dtzWill** [comment]
Fascinating discussion/details, thanks!

Erm, I feel I should know how but.. anyone know how to best express "try to build everywhere other than darwin"? Is conditionally setting "broken" the way to go...? (cc @Ericson2314, JIC :))

**Comment by Ericson2314** [comment]
Yes I think conditionally setting broken is the way to go, especially since it's *supposed" to work there.

**Comment by dtzWill** [comment]
> Yes I think conditionally setting broken is the way to go, especially since it's *supposed" to work on Darwin.

Great, thanks!

**Comment by copumpkin** [comment]
Thanks!

**Pull request merged**
