### PR TITLE
Fixes and improvements for cross-building to Windows

### PR DESCRIPTION
**Pull request by aszlig**
Contains a few fixups of the things that went broken since release 14.04 and also contains cleanups, particularly the removal of the old and unmaintained mingw32.

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @garbas

**Comment by anderspapitto** [comment]
@aszlig is this branch in a functional state (are you using it personally)? I'd like to play around with cross-building some stuff on nixos, and this seems to be the best starting point I can find.

**Comment by aszlig** [comment]
@anderspapitto: It's more or less in a functional state but I was trying to build webkit and qt which still fail in this state. But feel free to play around with it and/or fix it up some more, because I'm not sure when I'm going to get back to work on this branch.

**Comment by vcunat** [comment]
This doesn't seem important to be in the next release, as the releases are NixOS-centric...

**Comment by garbas** [comment]
@aszlig would it be possible to make this PR dont trigger mass rebuild on linux/darwin. then we could easily merge it.

**Comment by aszlig** [comment]
@garbas: This would mean a complete re-work of this branch and I currently don't have a project where I need to cross-build for Windows, so feel free to cherry-pick fixes if you encounter them.

**Comment by vcunat** [comment]
Hmm, it seems you haven't fixed `bash.crossDrv` build...

**Comment by vcunat** [comment]
Is this still WIP? It seems it might be in merge-able state (to staging).

**Comment by aszlig** [comment]
@vcunat: I didn't pick up on this and I don't currently have anything to cross-build to Windows, so I'm closing this for now.

**Pull request closed without merging**
