### PR TITLE
memo: 0.4 -> 0.5

### PR DESCRIPTION
**Pull request by mrVanDalo**
###### Motivation for this change

Version Bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build memo

**Comment by tkerber** [comment]
This seems to have [broken the tarball](https://hydra.nixos.org/build/78901153/nixlog/1). I guess it doesn't like aliases?

**Comment by xeji** [comment]
Interesting, thanks for catching this. Looks like the  `eval-release.nix` check doesn't provide aliases. Not sure if this is a bug or feature. Fixed in 26210f556af7e598eb10f14ebe4445a724e85c56 .

**Comment by mrVanDalo** [comment]
@xeji @tkerber  will create a fix for it today.

**Comment by xeji** [comment]
No need, I already fixed it, see comment above.

**Comment by mrVanDalo** [comment]
Oh yeah :D

**Pull request merged**
