### PR TITLE
yabai: 5.0.2 -> 5.0.3

### PR DESCRIPTION
**Pull request by moni-dz**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cpick** [comment]
5.0.4 is out.  If I can figure out how to generate the sha256 format used in the source I'll submit an updated patch.

**Comment by utkarshgupta137** [comment]
You can replace the sha256 with an empty string or `sha256-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` & update the version. `nix-build` will then fail & give you the correct SHA.

**Comment by mokrinsky** [comment]
@cpick 
```sh
$ sha256sum yabai-v5.0.4.tar.gz
c7dcb6a179d4815d1ada3b66c30f5301d9dd2befd986d8ee9744b39a011994a2  yabai-v5.0.4.tar.gz
$ nix hash to-base64 --type sha256 "c7dcb6a179d4815d1ada3b66c30f5301d9dd2befd986d8ee9744b39a011994a2"
x9y2oXnUgV0a2jtmww9TAdndK+/Zhtjul0SzmgEZlKI=
```
then add `sha256-` prefix to this one and it will work.

(also, since I already calculated checksum for archive installation... checksum for github one is `sha256-TCY0EvP0+2+U1k9kYIi8jMt4mj3ZRaQPsb1wtU3Z2U4=`)

**Comment by v3s1e** [comment]
5.0.4 is [here](https://github.com/NixOS/nixpkgs/pull/229949)

**Pull request closed without merging**
