### PR TITLE
python3Packages.aiofiles: enable tests

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Enable tests

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 135518` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>home-assistant</li>
    <li>theharvester</li>
  </ul>
</details>
<details>
  <summary>58 packages built:</summary>
  <ul>
    <li>datasette (python39Packages.datasette)</li>
    <li>dyndnsc</li>
    <li>esphome</li>
    <li>gns3-server</li>
    <li>matrix-commander</li>
    <li>mirage-im</li>
    <li>opsdroid</li>
    <li>pantalaimon</li>
    <li>platformio</li>
    <li>python38Packages.adb-shell</li>
    <li>python38Packages.aiofiles</li>
    <li>python38Packages.androidtv</li>
    <li>python38Packages.datasette</li>
    <li>python38Packages.datasette-template-sql</li>
    <li>python38Packages.dependency-injector</li>
    <li>python38Packages.entrance</li>
    <li>python38Packages.entrance-with-router-features</li>
    <li>python38Packages.envoy-reader</li>
    <li>python38Packages.fastapi</li>
    <li>python38Packages.ha-philipsjs</li>
    <li>python38Packages.ismartgate</li>
    <li>python38Packages.json-logging</li>
    <li>python38Packages.matrix-nio</li>
    <li>python38Packages.pure-python-adb</li>
    <li>python38Packages.pyinsteon</li>
    <li>python38Packages.pytest-sanic</li>
    <li>python38Packages.respx</li>
    <li>python38Packages.sanic</li>
    <li>python38Packages.sanic-auth</li>
    <li>python38Packages.sanic-testing</li>
    <li>python38Packages.slowapi</li>
    <li>python38Packages.starlette</li>
    <li>python38Packages.yalexs</li>
    <li>python39Packages.adb-shell</li>
    <li>python39Packages.aiofiles</li>
    <li>python39Packages.androidtv</li>
    <li>python39Packages.datasette-template-sql</li>
    <li>python39Packages.dependency-injector</li>
    <li>python39Packages.entrance</li>
    <li>python39Packages.entrance-with-router-features</li>
    <li>python39Packages.envoy-reader</li>
    <li>python39Packages.fastapi</li>
    <li>python39Packages.ha-philipsjs</li>
    <li>python39Packages.ismartgate</li>
    <li>python39Packages.json-logging</li>
    <li>python39Packages.matrix-nio</li>
    <li>python39Packages.pure-python-adb</li>
    <li>python39Packages.pyinsteon</li>
    <li>python39Packages.pytest-sanic</li>
    <li>python39Packages.respx</li>
    <li>python39Packages.sanic</li>
    <li>python39Packages.sanic-auth</li>
    <li>python39Packages.sanic-testing</li>
    <li>python39Packages.slowapi</li>
    <li>python39Packages.starlette</li>
    <li>python39Packages.yalexs</li>
    <li>wapiti</li>
    <li>weechatScripts.weechat-matrix</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`home-assistant` should be fixed now.

**Comment by risicle** [comment]
Fails on macos 10.15:

```
builder for '/nix/store/6r2dz17p6ahmkaaavl5mg2ygxksk85m8-python3.9-aiofiles-0.7.0.drv' failed with exit code 1; last 10 log lines:
              return
      
          try:
  >           result = self.fn(*self.args, **self.kwargs)
  E           OSError: [Errno 38] Socket operation on non-socket
  
  /nix/store/ha9svlp7cbvgibrz773nfrjn6phgfqyw-python3-3.9.6/lib/python3.9/concurrent/futures/thread.py:52: OSError
  =========================== short test summary info ============================
  FAILED tests/test_os.py::test_sendfile_file - OSError: [Errno 38] Socket oper...
  ======================== 1 failed, 167 passed in 4.47s =========================
```

**Comment by risicle** [comment]
https://github.com/Tinche/aiofiles/issues/88 I'd suggest just skipping it on darwin.

**Pull request merged**
