### PR TITLE
python310Packages.jupyterlab_server: run tests

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Diff: https://github.com/python-openapi/openapi-core/compare/refs/tags/0.17.1...0.18.0

Changelog: https://github.com/python-openapi/openapi-core/releases/tag/0.17.2
           https://github.com/python-openapi/openapi-core/releases/tag/0.18.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I merged the `openapi-core` part immediately, as you're maintainer and it's better to have something than a build failure, even if someone wanted to comment on that.

**Comment by natsukium** [comment]
Is it the jupyterlab_server refactor left?
openapi-core doesn't seem to be related anymore.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 247814` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.jupyterlab-lsp</li>
    <li>python310Packages.jupyterlab-lsp.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.jupyterlab-lsp</li>
    <li>python311Packages.jupyterlab-lsp.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
  </ul>
</details>
<details>
  <summary>37 packages failed to build:</summary>
  <ul>
    <li>manim</li>
    <li>manim.dist</li>
    <li>python310Packages.bambi</li>
    <li>python310Packages.bambi.dist</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python310Packages.elegy</li>
    <li>python310Packages.elegy.dist</li>
    <li>python310Packages.encodec</li>
    <li>python310Packages.encodec.dist</li>
    <li>python310Packages.layoutparser</li>
    <li>python310Packages.layoutparser.dist</li>
    <li>python310Packages.pdfplumber</li>
    <li>python310Packages.pdfplumber.dist</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymc.dist</li>
    <li>python310Packages.treex</li>
    <li>python310Packages.treex.dist</li>
    <li>python310Packages.unstructured-inference</li>
    <li>python310Packages.unstructured-inference.dist</li>
    <li>python310Packages.vector</li>
    <li>python310Packages.vector.dist</li>
    <li>python310Packages.vega</li>
    <li>python310Packages.vega.dist</li>
    <li>python311Packages.encodec</li>
    <li>python311Packages.encodec.dist</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.layoutparser.dist</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.pdfplumber.dist</li>
    <li>python311Packages.unstructured-inference</li>
    <li>python311Packages.unstructured-inference.dist</li>
    <li>python311Packages.vega</li>
    <li>python311Packages.vega.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
    <li>wolfram-notebook</li>
  </ul>
</details>
<details>
  <summary>130 packages built:</summary>
  <ul>
    <li>cantor (libsForQt5.cantor ,plasma5Packages.cantor)</li>
    <li>ihaskell</li>
    <li>jupyter</li>
    <li>jupyter.dist</li>
    <li>labplot</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.ansible-kernel.dist</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.arviz.dist</li>
    <li>python310Packages.augmax</li>
    <li>python310Packages.augmax.dist</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.batchspawner.dist</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.dockerspawner.dist</li>
    <li>python310Packages.einops</li>
    <li>python310Packages.einops.dist</li>
    <li>python310Packages.experiment-utilities</li>
    <li>python310Packages.experiment-utilities.dist</li>
    <li>python310Packages.jupyter</li>
    <li>python310Packages.jupyter-contrib-core</li>
    <li>python310Packages.jupyter-contrib-core.dist</li>
    <li>python310Packages.jupyter-contrib-nbextensions</li>
    <li>python310Packages.jupyter-contrib-nbextensions.dist</li>
    <li>python310Packages.jupyter-nbextensions-configurator</li>
    <li>python310Packages.jupyter-nbextensions-configurator.dist</li>
    <li>python310Packages.jupyter.dist</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-systemdspawner.dist</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python310Packages.jupyterhub.dist</li>
    <li>python310Packages.jupyterlab</li>
    <li>python310Packages.jupyterlab-git</li>
    <li>python310Packages.jupyterlab-git.dist</li>
    <li>python310Packages.jupyterlab.dist</li>
    <li>python310Packages.jupyterlab_launcher</li>
    <li>python310Packages.jupyterlab_launcher.dist</li>
    <li>python310Packages.jupyterlab_server</li>
    <li>python310Packages.jupyterlab_server.dist</li>
    <li>python310Packages.jupytext</li>
    <li>python310Packages.jupytext.dist</li>
    <li>python310Packages.k-diffusion</li>
    <li>python310Packages.k-diffusion.dist</li>
    <li>python310Packages.mkdocs-jupyter</li>
    <li>python310Packages.mkdocs-jupyter.dist</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python310Packages.nbdime</li>
    <li>python310Packages.nbdime.dist</li>
    <li>python310Packages.nikola</li>
    <li>python310Packages.nikola.dist</li>
    <li>python310Packages.nix-kernel</li>
    <li>python310Packages.nix-kernel.dist</li>
    <li>python310Packages.notebook</li>
    <li>python310Packages.notebook.dist</li>
    <li>python310Packages.notedown</li>
    <li>python310Packages.notedown.dist</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.oauthenticator.dist</li>
    <li>python310Packages.phik</li>
    <li>python310Packages.phik.dist</li>
    <li>python310Packages.pymoo</li>
    <li>python310Packages.pymoo.dist</li>
    <li>python310Packages.qgrid</li>
    <li>python310Packages.qgrid.dist</li>
    <li>python310Packages.xarray-einstats</li>
    <li>python310Packages.xarray-einstats.dist</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-kernel.dist</li>
    <li>python311Packages.augmax</li>
    <li>python311Packages.augmax.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.einops</li>
    <li>python311Packages.einops.dist</li>
    <li>python311Packages.experiment-utilities</li>
    <li>python311Packages.experiment-utilities.dist</li>
    <li>python311Packages.jupyter</li>
    <li>python311Packages.jupyter-contrib-core</li>
    <li>python311Packages.jupyter-contrib-core.dist</li>
    <li>python311Packages.jupyter-contrib-nbextensions</li>
    <li>python311Packages.jupyter-contrib-nbextensions.dist</li>
    <li>python311Packages.jupyter-nbextensions-configurator</li>
    <li>python311Packages.jupyter-nbextensions-configurator.dist</li>
    <li>python311Packages.jupyter.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.jupyterlab</li>
    <li>python311Packages.jupyterlab-git</li>
    <li>python311Packages.jupyterlab-git.dist</li>
    <li>python311Packages.jupyterlab.dist</li>
    <li>python311Packages.jupyterlab_launcher</li>
    <li>python311Packages.jupyterlab_launcher.dist</li>
    <li>python311Packages.jupyterlab_server</li>
    <li>python311Packages.jupyterlab_server.dist</li>
    <li>python311Packages.jupytext</li>
    <li>python311Packages.jupytext.dist</li>
    <li>python311Packages.mkdocs-jupyter</li>
    <li>python311Packages.mkdocs-jupyter.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>python311Packages.nbdime</li>
    <li>python311Packages.nbdime.dist</li>
    <li>python311Packages.nikola</li>
    <li>python311Packages.nikola.dist</li>
    <li>python311Packages.nix-kernel</li>
    <li>python311Packages.nix-kernel.dist</li>
    <li>python311Packages.notebook</li>
    <li>python311Packages.notebook.dist</li>
    <li>python311Packages.notedown</li>
    <li>python311Packages.notedown.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>python311Packages.qgrid</li>
    <li>python311Packages.qgrid.dist</li>
    <li>quarto</li>
    <li>sage</li>
    <li>sageWithDoc</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]
CI is all green and the change seems fine.

**Pull request merged**
