### PR TITLE
python312Packages.nvidia-ml-py: 12.555.43 -> 12.560.30

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 346660`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bentoml</li>
    <li>python311Packages.bentoml.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python312Packages.bentoml</li>
    <li>python312Packages.bentoml.dist</li>
    <li>python312Packages.vllm</li>
    <li>python312Packages.vllm.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 6 packages failed to build:</summary>
  <ul>
    <li>python311Packages.kserve</li>
    <li>python311Packages.kserve.dist</li>
    <li>python311Packages.scalene</li>
    <li>python311Packages.scalene.dist</li>
    <li>python312Packages.kserve</li>
    <li>python312Packages.kserve.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 18 packages built:</summary>
  <ul>
    <li>nvitop</li>
    <li>nvitop.dist</li>
    <li>openllm</li>
    <li>openllm.dist</li>
    <li>python311Packages.gpustat</li>
    <li>python311Packages.gpustat.dist</li>
    <li>python311Packages.nvidia-ml-py</li>
    <li>python311Packages.nvidia-ml-py.dist</li>
    <li>python311Packages.ray</li>
    <li>python311Packages.ray.dist</li>
    <li>python312Packages.gpustat</li>
    <li>python312Packages.gpustat.dist</li>
    <li>python312Packages.nvidia-ml-py</li>
    <li>python312Packages.nvidia-ml-py.dist</li>
    <li>python312Packages.ray</li>
    <li>python312Packages.ray.dist</li>
    <li>scalene (python312Packages.scalene)</li>
    <li>scalene.dist (python312Packages.scalene.dist)</li>
  </ul>
</details>

---
### `aarch64-linux`

---
### `x86_64-darwin`

---
### `aarch64-darwin`

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 346660`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bentoml</li>
    <li>python311Packages.bentoml.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python312Packages.bentoml</li>
    <li>python312Packages.bentoml.dist</li>
    <li>python312Packages.vllm</li>
    <li>python312Packages.vllm.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 24 packages built:</summary>
  <ul>
    <li>nvitop</li>
    <li>nvitop.dist</li>
    <li>openllm</li>
    <li>openllm.dist</li>
    <li>python311Packages.gpustat</li>
    <li>python311Packages.gpustat.dist</li>
    <li>python311Packages.kserve</li>
    <li>python311Packages.kserve.dist</li>
    <li>python311Packages.nvidia-ml-py</li>
    <li>python311Packages.nvidia-ml-py.dist</li>
    <li>python311Packages.ray</li>
    <li>python311Packages.ray.dist</li>
    <li>python311Packages.scalene</li>
    <li>python311Packages.scalene.dist</li>
    <li>python312Packages.gpustat</li>
    <li>python312Packages.gpustat.dist</li>
    <li>python312Packages.kserve</li>
    <li>python312Packages.kserve.dist</li>
    <li>python312Packages.nvidia-ml-py</li>
    <li>python312Packages.nvidia-ml-py.dist</li>
    <li>python312Packages.ray</li>
    <li>python312Packages.ray.dist</li>
    <li>scalene (python312Packages.scalene)</li>
    <li>scalene.dist (python312Packages.scalene.dist)</li>
  </ul>
</details>

---
### `aarch64-linux`

---
### `x86_64-darwin`

---
### `aarch64-darwin`

**Comment by sarahec** [comment]
Result of `nixpkgs-review pr 346660` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bentoml</li>
    <li>python311Packages.bentoml.dist</li>
    <li>python311Packages.kserve</li>
    <li>python311Packages.kserve.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python312Packages.bentoml</li>
    <li>python312Packages.bentoml.dist</li>
    <li>python312Packages.kserve</li>
    <li>python312Packages.kserve.dist</li>
    <li>python312Packages.vllm</li>
    <li>python312Packages.vllm.dist</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>openllm</li>
    <li>openllm.dist</li>
    <li>python311Packages.gpustat</li>
    <li>python311Packages.gpustat.dist</li>
    <li>python311Packages.nvidia-ml-py</li>
    <li>python311Packages.nvidia-ml-py.dist</li>
    <li>python312Packages.gpustat</li>
    <li>python312Packages.gpustat.dist</li>
    <li>python312Packages.nvidia-ml-py</li>
    <li>python312Packages.nvidia-ml-py.dist</li>
  </ul>
</details>

**Review by sarahec — APPROVED** [review]
LGTM

**Comment by GaetanLepage** [comment]
> Result of `nixpkgs-review pr 346660` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

Weird, when running `nixpkgs-review` on my side, it tries to build `python3Packages.circus` and fails (hangs forever + failing tests).

**Comment by sarahec** [comment]
> Weird, when running `nixpkgs-review` on my side, it tries to build `python3Packages.circus` and fails (hangs forever + failing tests).

Weird. python312Packages.circus @0.18.0 downloads from Hydra. Also works for 3.11. I don't see any dependencies that would trigger a rebuild based on your PR.

(I'm a little annoyed that the circus derivation built from PyPi instead of source.)

**Comment by GaetanLepage** [comment]
> Weird. python312Packages.circus @0.18.0 downloads from Hydra. Also works for 3.11. I don't see any dependencies that would trigger a rebuild based on your PR.

Actually, I forced the rebuild of `circus` on the `master` branch and I face the same error (i.e. tests hanging and failing).
So, it's currently not buildable from the darwin builders...

**Comment by GaetanLepage** [comment]
Anyway, this is not a regression, so this PR can just move forward.

**Comment by sarahec** [comment]
>  it's currently not buildable from the darwin builders...

I was able to build on aarch64-darwin without any trouble (in a sandbox). I also tested changing it to a source build (from Github) and it worked fine. It even passes nixpkgs-review. 

On the other hand, nothing in nixpkgs seems to use it, the source repo is sorely neglected, and there is no maintainer on our end, so I decided to not check in the source-driven build.

**Comment by GaetanLepage** [comment]
`circus` flakiness fixed in #346824.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
