### PR TITLE
binaryen: 109 -> 111

### PR DESCRIPTION
**Pull request by willcohen**
###### Description of changes

In an attempt to backport https://github.com/WebAssembly/binaryen/pull/5378 and https://github.com/WebAssembly/binaryen/pull/5391, upstream has diverged enough from what's in nixpkgs that a lot of manual merge conflict resolutions would be necessary, which requires rebuilding a lot of the wasm2js test case outputs. This might grow to be frustrating as time goes on.

As noted by #206005, emscripten is blocked by https://github.com/NixOS/nixpkgs/pull/194634, but this PR bumps binaryen forward from 109 to 111 (plus upstream backports) separately.

@RaitoBezarius 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by willcohen** [comment]
This PR will not work unless additional work is done to backport the binaryen bumps to emscripten. @RaitoBezarius I'll try that out a little and see if it can either go here or possibly sneak in to #206005 (unless that's getting merged in the near future!)

**Comment by willcohen** [comment]
Result of `nixpkgs-review pr 209122` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2jack</li>
    <li>faust2jaqt</li>
    <li>faust2lv2</li>
    <li>open-music-kontrollers.mephisto</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>tinygo</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>binaryen</li>
    <li>emscripten</li>
    <li>faust (faust2)</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jackrust</li>
    <li>faust2ladspa</li>
  </ul>
</details>

**Comment by willcohen** [comment]
Result of `nixpkgs-review pr 209122` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>faustStk</li>
    <li>magnetophonDSP.ConstantDetuneChorus</li>
  </ul>
</details>
<details>
  <summary>29 packages built:</summary>
  <ul>
    <li>binaryen</li>
    <li>emscripten</li>
    <li>faust (faust2)</li>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jack</li>
    <li>faust2jackrust</li>
    <li>faust2jaqt</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>faustPhysicalModeling</li>
    <li>faustlive</li>
    <li>guitarix</li>
    <li>kapitonov-plugins-pack</li>
    <li>magnetophonDSP.CharacterCompressor</li>
    <li>magnetophonDSP.CompBus</li>
    <li>magnetophonDSP.LazyLimiter</li>
    <li>magnetophonDSP.MBdistortion</li>
    <li>magnetophonDSP.RhythmDelay</li>
    <li>magnetophonDSP.VoiceOfFaust</li>
    <li>magnetophonDSP.faustCompressors</li>
    <li>magnetophonDSP.pluginUtils</li>
    <li>magnetophonDSP.shelfMultiBand</li>
    <li>mooSpace</li>
    <li>open-music-kontrollers.mephisto</li>
    <li>tambura</li>
    <li>tinygo</li>
  </ul>
</details>

**Comment by willcohen** [comment]
@RaitoBezarius looks like even old emscripten works with the updated binaryen, so this shouldn't conflict with the emscripten PR!

**Comment by RaitoBezarius** [comment]
Do we still want to proceed with this one @willcohen ? (some merge conflicts)

**Comment by willcohen** [comment]
Yes — will rebase in the next day or two!

**Comment by willcohen** [comment]
@RaitoBezarius should be ready to go!

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius should be ready to go!

Reviewing on my side on x86_64-linux and aarch64-linux, if good, I will merge it.

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 209122` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>faustStk</li>
    <li>magnetophonDSP.ConstantDetuneChorus</li>
  </ul>
</details>
<details>
  <summary>29 packages built:</summary>
  <ul>
    <li>binaryen</li>
    <li>emscripten</li>
    <li>faust (faust2)</li>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jack</li>
    <li>faust2jackrust</li>
    <li>faust2jaqt</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>faustPhysicalModeling</li>
    <li>faustlive</li>
    <li>guitarix</li>
    <li>kapitonov-plugins-pack</li>
    <li>magnetophonDSP.CharacterCompressor</li>
    <li>magnetophonDSP.CompBus</li>
    <li>magnetophonDSP.LazyLimiter</li>
    <li>magnetophonDSP.MBdistortion</li>
    <li>magnetophonDSP.RhythmDelay</li>
    <li>magnetophonDSP.VoiceOfFaust</li>
    <li>magnetophonDSP.faustCompressors</li>
    <li>magnetophonDSP.pluginUtils</li>
    <li>magnetophonDSP.shelfMultiBand</li>
    <li>mooSpace</li>
    <li>open-music-kontrollers.mephisto</li>
    <li>tambura</li>
    <li>tinygo</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 209122` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>faustStk</li>
  </ul>
</details>
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>binaryen</li>
    <li>emscripten</li>
    <li>faust (faust2)</li>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jack</li>
    <li>faust2jackrust</li>
    <li>faust2jaqt</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>faustPhysicalModeling</li>
    <li>guitarix</li>
    <li>kapitonov-plugins-pack</li>
    <li>open-music-kontrollers.mephisto</li>
    <li>tinygo</li>
  </ul>
</details>

**Comment by willcohen** [comment]
Thank you!

**Pull request merged**
