### PR TITLE
watchman: 2023.01.30.00 -> 2023.08.14.00

### PR DESCRIPTION
**Pull request by aaronjheng**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bryango** [comment]
Can #248660 be addressed along the way? I tried moving some `{nativeBuild,build}Inputs` around but failed to shrink the closure...

**Comment by aaronjheng** [comment]
@bryango Right now I don't think we need to do anything. `boost` is required for running watchman. On the other hand, `gcc` is for building watchman. If you install `watchman` from binary cache, `gcc` is not needed.

> [The upstream binary](https://github.com/facebook/watchman/releases) is tiny, with a size < 10 M.

I guess it's static linking.

**Comment by bryango** [comment]
> `gcc` is for building watchman. If you install `watchman` from binary cache, `gcc` is not needed.

I thought so but no, gcc still ends up in the _output_ closure. I did install the package from binary cache. Maybe it comes from some propagated build inputs?

I couldn't identify its origin, but I'm certain it's only required by watchman in my system. 

> > [The upstream binary](https://github.com/facebook/watchman/releases) is tiny, with a size < 10 M.
> 
> I guess it's static linking.

Indeed, but when there is such a storage overhead, should we consider static linking ourselves? Or is there a nixpkgs policy against it? (Sorry I'm a noob...

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64

**Comment by tjni** [comment]
I also double checked that it builds on x86_64-darwin via Rosetta 2, so I'm not sure what was flaky on CI.

**Pull request merged**
