### PR TITLE
Remove obsolete patch for Hedgehog on ghc-8.8.1

### PR DESCRIPTION
**Pull request by utdemir**
###### Motivation for this change

The patch was referring to a file in `master` branch which got [removed][1] since now the upstream compiles with GHC 8.8.1.

[1]: https://gitlab.haskell.org/ghc/head.hackage/commit/f7d0cf4c7e7f0440c1986232e86cf36710dabbd8

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @peti

### CODE REVIEW

**Comment by utdemir** [comment]
Also, not in scope of this PR; but I think referring to `master` branches on the other patches might be a mistake when we can easily depend on a specific revision of `head-hackage` repository.

**Comment by cdepillabout** [comment]
@GrahamcOfBorg build haskell.packages.ghc881.hedgehog

**Comment by cdepillabout** [comment]
@utdemir Thanks for this fix!

@peti ofborg succeeded, so I think this should be good to be merged in.

**Comment by peti** [comment]
> Also, not in scope of this PR; but I think referring to `master` branches on these patches might be a mistake when we can easily depend on a specific revision of `head-hackage` repository.

**Pull request merged**
