### PR TITLE
tree-sitter: 0.22.5 -> 0.22.6

### PR DESCRIPTION
**Pull request by MangoIV**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by MangoIV** [comment]
Neovim-nightly needs this. 

cc @Profpatsch

**Comment by MangoIV** [comment]
it appears I'm missing a bunch of grammars, will amend.

**Comment by polarmutex** [comment]
already a prev PR for tree-siter #310162

**Comment by MangoIV** [comment]
I swear I searched the list. This also updates the grammars.

**Comment by Gerg-L** [comment]
I think this should be targeting staging because it triggers 8K+ rebuilds on my nixpkgs-review

**Review by Gerg-L — APPROVED** [review]

**Comment by Parsifa1** [comment]
There seems to be a problem with `cargohash` and it won't build on my device
CI also [failed](https://garnix.io/build/R0dGJbqg)

image

**Comment by Gerg-L** [comment]
<https://github.com/Parsifa1/nix-config/blob/master/overlay.nix#L12> feel like it's this

**Comment by Parsifa1** [comment]
> [Parsifa1/nix-config@`master`/overlay.nix#L12](https://github.com/Parsifa1/nix-config/blob/master/overlay.nix?rgh-link-date=2024-07-30T20%3A24%3A47Z#L12) feel like it's this EDIT: probably not fenix seems to not clobber any default rust packages. I would try removing all overlays though


It seems to be a problem with neovim overlay, thank you :)

**Pull request merged**
