### PR TITLE
rustc: 1.40.0 -> 1.41.0

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change

New rustc version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
x86_64-linux builds fine.

**Comment by bkchr** [comment]
Locally firefox also builds for me.

**Comment by Mic92** [comment]
Does firefox uses this rust version at all?

**Comment by Mic92** [comment]
cc @alyssais Could you run `nix-review -p fd 79148` on macOS?

**Comment by Mic92** [comment]
@GrahamcOfBorg build fd

**Comment by FRidh** [comment]
By merging now we could get it in before branch-off. If there are issues we can always revert.

**Comment by LnL7** [comment]
My darwin build just finished, looks good.

**Pull request merged**
