### PR TITLE
python3Packages: Fix and document the removal of the local `.overrideAttrs` attribute

### PR DESCRIPTION
**Pull request by ShamrockLee**
This PR cleans up the leftover of #333670.

After #333670, `buildPythonPackage` and `buildPythonApplication` no longer apply `lib.makeOverridable` themselves and no longer provide `.override` and `.overrideDerivation` of the returning package.

For Python packages provided by Nixpkgs, the local `.override` attribute is almost always shadowed by the one provided by `callPackage`, and so does the `.overrideDerivation` attribute.  I didn't find any use of the local `override` in Nixpkgs, but @trofi reported the evaluation failure of `python3Packages.pythonCatchConflictsHook.tests.catches-conflict-multiple-chains` due to the loss of the local `overrideDerivation`.

This PR uses `lib.overrideDerivation` instead of the `overrideDerivation` attribute to fix the evaluation of `python3Packages.pythonCatchConflictsHook.tests.catches-conflict-multiple-chains` and document the removal of the `buildPython*`-generated local `overrideDerivation` attribute in the release note.

Update: As the Nixpkgs 24.11 branch-off is made, this PR should be backported onto the `release-24.11` branch once it is merged.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
The change fixes the eval failures for that attribute for me. Thank you!

But I'm afraid I found another eval failure:

```
$ nix-instantiate -A python3Packages.scikit-image.tests.all-tests
error: attribute 'override' missing
       at /tmp/z/nixpkgs/pkgs/development/python-modules/scikit-image/default.nix:160:19:
          159|     passthru.tests = {
          160|       all-tests = self.override { doCheck = true; };
             |                   ^
          161|     };
```

It bisects down to the same 58bfe741230877e32be930a581bd2f89980b40d5 `buildPython*: Deprecate and remove (buildPython* { ... }).override`. Worth fixing it as well?

**Comment by ShamrockLee** [comment]
@trofi I'll fix it as well.

Would you mind sharing how you found those evaluation errors in `<pkg>.tests`? The nixpkgs-review PR (Mic92/nixpkgs-review#397) to examine them hasn't been merged yet.

**Comment by trofi** [comment]
> @trofi I'll fix it as well.
> 
> Would you mind sharing how you found those evaluation errors in `<pkg>.tests`? The nixpkgs-review PR ([Mic92/nixpkgs-review#397](https://github.com/Mic92/nixpkgs-review/pull/397)) to examine them hasn't been merged yet.

I'm using this script: https://github.com/trofi/nixpkgs-overlays/blob/main/lib/all-attrs-iter.bash and run it as:

```
$ ./all-attrs-iter.bash -I nixpkgs=~/n --arg maxDepth 4 --arg verbose 3 --arg ignoreDrvAttrs false
```

`~/n` contains `nixpkgs` from `staging` branch. The caveat is that I have a bunch of patches against `nixpkgs` to skip other known eval failures.

**Comment by trofi** [comment]
Tested the attribute evaluation against the current branch state. All good now. Thank you!

**Comment by ShamrockLee** [comment]
@trofi, could you officially approve this PR using the GitHub Review? This would make the approval more visible.

**Review by trofi — APPROVED** [review]

**Comment by ShamrockLee** [comment]
As the Nixpkgs 24.11 branch-off is made, this PR should be backported onto the `release-24.11` branch once it is merged.

**Comment by ShamrockLee** [comment]
Cc: @natsukagami

**Comment by natsukagami** [comment]
@natsukium 👋

**Comment by ShamrockLee** [comment]
> @natsukium 👋

Oops! Sorry for bothering and thank you for the redirection.

**Review by natsukium — APPROVED** [review]
Sorry for the missing. LGTM, thanks.

**Pull request merged**
