### PR TITLE
matrix-conduit: 0.6.0 -> 0.7.0

### PR DESCRIPTION
**Pull request by Kladki**
## Description of changes
https://gitlab.com/famedly/conduit/-/releases/v0.7.0

First time contributing to nixpkgs ~~but I don't know how to make conduit build with the updated rocksdb~~.
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by tamara-schmitz** [comment]
I got this compile error when building your branch locally:

```
   Compiling rust-rocksdb v0.24.0
error[E0425]: cannot find function `rocksdb_wait_for_compact` in crate `ffi`
    --> /build/cargo-vendor-dir/rust-rocksdb-0.24.0/src/db.rs:1759:27
```

Is this just me?

**Comment by tamara-schmitz** [comment]
Also your commit does not appear to be based on f7709cf1b33a050044bde96d66d22f8472fd080c which explicitly sets the rocksdb version to 8.3.

The build error that I saw comes from the Rocksdb version being too old. The Flake in the Conduit repo uses version 9.1.1 and there was a version bump of RocksDB right before the v.0.7.0 release:

https://gitlab.com/famedly/conduit/-/commit/61cb186b5b3e245f05928c54456489ca465c3437

So RocksDB needs to be updated as a dependency.

**Comment by tamara-schmitz** [comment]
So this PR depends on #255763

**Comment by Kladki** [comment]
There is already a merge request bumping rocksdb that was merged: https://github.com/NixOS/nixpkgs/pull/305974

**Comment by Kladki** [comment]
Builds should work now.

**Comment by tamara-schmitz** [comment]
yup. no more build errors for me

**Comment by tamara-schmitz** [comment]
ping @piegamesde hellooo, could you spare some time to look at this pr please?

**Comment by piegamesde** [comment]
Sorry, I switched to conduwuit and have no proper way to test it besides "it builds"

**Comment by ulrikstrid** [comment]
I'm deploying this right now, I will try to be faster reviewing next time, feel free to tag me

**Review by ulrikstrid — APPROVED** [review]
Diff looks good and I'm now running 0.7.0 and have confirmed it works in chats

**Review by superherointj — APPROVED** [review]
Works for me.

**Pull request merged**
