### PR TITLE
tts: 0.4.2 -> 0.5.0

### PR DESCRIPTION
**Pull request by mweinelt**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
Executing pipInstallPhase
/build/source/dist /build/source
Processing ./TTS-0.5.0-cp39-cp39-linux_x86_64.whl
Requirement already satisfied: coqpit in /nix/store/93f3zbaqhgd8pw6f30yknv1cqask02yg-python3.9-coqpit-0.0.14/lib/python3.9/site-packages (from TTS==0.5.0) (0.0.14)
Requirement already satisfied: matplotlib in /nix/store/9g0d6j5wqnglva453nmyk1ks9n1hmsbr-python3.9-matplotlib-3.5.1/lib/python3.9/site-packages (from TTS==0.5.0) (3.5.1)
Requirement already satisfied: jieba in /nix/store/k0ybyym8n253dja2anapzzdiv4qla7hm-python3.9-jieba-0.42.1/lib/python3.9/site-packages (from TTS==0.5.0) (0.42.1)
Requirement already satisfied: inflect in /nix/store/y20j3mswiz4cr98qd4s206956amklfga-python3.9-inflect-5.3.0/lib/python3.9/site-packages (from TTS==0.5.0) (5.3.0)
Requirement already satisfied: webrtcvad in /nix/store/g4p4paavi91ydjqmrwiv1ksh87nhkhbw-python3.9-webrtcvad-2.0.10/lib/python3.9/site-packages (from TTS==0.5.0) (2.0.10)
Requirement already satisfied: tqdm in /nix/store/b8maphcanpc77sbb64xdg9b7j2npv9gi-python3.9-tqdm-4.62.3/lib/python3.9/site-packages (from TTS==0.5.0) (4.62.3)
Requirement already satisfied: mecab-python3 in /nix/store/cfjwwn0fhxf1c79l7fjjqjnhs48z3rwf-python3.9-mecab-python3-1.0.4/lib/python3.9/site-packages (from TTS==0.5.0) (1.0.4)
Requirement already satisfied: cython in /nix/store/qvnzadwl84zk9n84pyw46ll9m5nnvbk5-python3.9-Cython-0.29.24/lib/python3.9/site-packages (from TTS==0.5.0) (0.29.24)
Requirement already satisfied: torch in /nix/store/hk1vbrni06niazz3g98zf6vg3731fhls-python3.9-pytorch-1.9.0/lib/python3.9/site-packages (from TTS==0.5.0) (1.9.0)
Requirement already satisfied: pyworld in /nix/store/8ia12xih945g26iqf6dlm6dbbacfbx1w-python3.9-pyworld-0.3.0/lib/python3.9/site-packages (from TTS==0.5.0) (0.3.0)
Requirement already satisfied: gdown in /nix/store/nqwhpjfnaiyhccpa8f8pl4jnmj8xrj00-gdown-4.2.0/lib/python3.9/site-packages (from TTS==0.5.0) (4.2.0)
Requirement already satisfied: soundfile in /nix/store/4pj877v03scgr6b2irg7a2gkgcjcy3hj-python3.9-soundfile-0.10.3.post1/lib/python3.9/site-packages (from TTS==0.5.0) (0.10.3.post1)
Requirement already satisfied: numpy in /nix/store/wch23ab3h4bhf9lpjhhs6mgs9mcmh5wj-python3.9-numpy-1.21.4/lib/python3.9/site-packages (from TTS==0.5.0) (1.21.4)
Requirement already satisfied: pandas in /nix/store/pibnq49h8xd33z54d4j7ycdv4xgabcif-python3.9-pandas-1.3.4/lib/python3.9/site-packages (from TTS==0.5.0) (1.3.4)
Requirement already satisfied: numba in /nix/store/xj9nkqki4xim1fq421ymmpck5q11s9qc-python3.9-numba-0.54.1/lib/python3.9/site-packages (from TTS==0.5.0) (0.54.1)
Requirement already satisfied: tensorboardX in /nix/store/mg73h9bmvsdcjqj29ahfqsw93ysi2rf7-python3.9-tensorboardx-2.4/lib/python3.9/site-packages (from TTS==0.5.0) (2.4)
Requirement already satisfied: torchaudio in /nix/store/yickqfzqrdwa904ip9ny27lqlzslkm3j-python3.9-torchaudio-0.10.0/lib/python3.9/site-packages (from TTS==0.5.0) (0.10.0+cu113)
Requirement already satisfied: flask in /nix/store/lx89vl46dbrizd8i0ndclj9cvc4hbbd0-python3.9-Flask-2.0.2/lib/python3.9/site-packages (from TTS==0.5.0) (2.0.2)
Requirement already satisfied: pyyaml in /nix/store/qpxjvij39nrs1zaha9fsb8sbcpa90w7g-python3.9-PyYAML-6.0/lib/python3.9/site-packages (from TTS==0.5.0) (6.0)
Requirement already satisfied: fsspec>=2021.04.0 in /nix/store/xhq2pvw5jx4yycamhi7im9119s7zaggn-python3.9-fsspec-2021.10.1/lib/python3.9/site-packages (from TTS==0.5.0) (2021.10.1)
Requirement already satisfied: unidic-lite==1.0.8 in /nix/store/j2hxcfpjs3swx0lj3cwrgnbjzai0v3fn-python3.9-unidic-lite-1.0.8/lib/python3.9/site-packages (from TTS==0.5.0) (1.0.8)
Requirement already satisfied: pypinyin in /nix/store/ckmk3balymwdv1yj2hnbq38v97x90v84-python3.9-pypinyin-0.44.0/lib/python3.9/site-packages (from TTS==0.5.0) (0.44.0)
Requirement already satisfied: scipy>=0.19.0 in /nix/store/62ni5xy88b90mlv94jpdd2dmwwn99b6j-python3.9-scipy-1.7.3/lib/python3.9/site-packages (from TTS==0.5.0) (1.7.3)
Requirement already satisfied: librosa in /nix/store/y9rrx6yvnmyr45ggqzzg5y2nj0v0wz02-python3.9-librosa-0.8.1/lib/python3.9/site-packages (from TTS==0.5.0) (0.8.1)
Requirement already satisfied: gruut in /nix/store/05z3nn3j1h4bz2ing5z0w370iik0q613-python3.9-gruut-2.2.0/lib/python3.9/site-packages (from TTS==0.5.0) (2.2.0)
Requirement already satisfied: pysbd in /nix/store/426napc4vmvpvbqa8zvkk3xgwp7kw3a2-python3.9-pysbd-0.3.4/lib/python3.9/site-packages (from TTS==0.5.0) (0.3.4)
Requirement already satisfied: umap-learn in /nix/store/b0hhymss0lsf91ws108f0fvcdk5sxn9d-python3.9-umap-learn-0.5.2/lib/python3.9/site-packages (from TTS==0.5.0) (0.5.2)
Requirement already satisfied: anyascii in /nix/store/f9x1zaqxmpspajy7qaxh676jfp79naxv-python3.9-anyascii-0.3.0/lib/python3.9/site-packages (from TTS==0.5.0) (0.3.0)
Requirement already satisfied: click>=7.1.2 in /nix/store/nckfzfxmw7ywdzzsp1h06w8k94ryc7m5-python3.9-click-8.0.3/lib/python3.9/site-packages (from flask->TTS==0.5.0) (8.0.3)
Requirement already satisfied: Jinja2>=3.0 in /nix/store/50x9wnqbggbkfcli4c6y4hrflli2xi9d-python3.9-Jinja2-3.0.3/lib/python3.9/site-packages (from flask->TTS==0.5.0) (3.0.3)
Requirement already satisfied: itsdangerous>=2.0 in /nix/store/03x4ryw83lbjy2wbkpwi0lcp2x6x61fi-python3.9-itsdangerous-2.0.1/lib/python3.9/site-packages (from flask->TTS==0.5.0) (2.0.1)
Requirement already satisfied: Werkzeug>=2.0 in /nix/store/mnxcjiwcm6yi8507z6vklyw4fi5c9hvg-python3.9-werkzeug-2.0.2/lib/python3.9/site-packages (from flask->TTS==0.5.0) (2.0.2)
Requirement already satisfied: filelock in /nix/store/pk4a1dl1gcsmxa3nvpkgzy6m9yrfg8vg-python3.9-filelock-3.3.0/lib/python3.9/site-packages (from gdown->TTS==0.5.0) (3.3.0)
Requirement already satisfied: beautifulsoup4 in /nix/store/n6zh9akxns6las8xxlnlww5gbx1fllxz-python3.9-beautifulsoup4-4.10.0/lib/python3.9/site-packages (from gdown->TTS==0.5.0) (4.10.0)
Requirement already satisfied: requests[socks] in /nix/store/rig6npd9sd45ashf6fxcwgxzm7m4p0l3-python3.9-requests-2.26.0/lib/python3.9/site-packages (from gdown->TTS==0.5.0) (2.26.0)
Requirement already satisfied: six in /nix/store/1dm9ndgg56ylawpcbdzkhl03fg6777rr-python3.9-six-1.16.0/lib/python3.9/site-packages (from gdown->TTS==0.5.0) (1.16.0)
Requirement already satisfied: jsonlines~=1.2.0 in /nix/store/hd90xzdsb28x4bi30i5n232bg00mnl1c-python3.9-jsonlines-1.2.0/lib/python3.9/site-packages (from gruut->TTS==0.5.0) (1.2.0)
Requirement already satisfied: num2words<1.0.0,>=0.5.10 in /nix/store/0xzwkb6mih125p6klfsv38y079x233nr-python3.9-num2words-0.5.10/lib/python3.9/site-packages (from gruut->TTS==0.5.0) (0.5.10)
Requirement already satisfied: gruut-lang-en in /nix/store/103ff6sx3paxr3gcxpy7gmfd8722pl5s-python3.9-gruut-lang-en-2.2.0/lib/python3.9/site-packages (from gruut->TTS==0.5.0) (2.0.0)
Requirement already satisfied: python-crfsuite~=0.9.7 in /nix/store/120569ppkm5s2hmyax69gbc13jchv55m-python3.9-python-crfsuite-0.9.7/lib/python3.9/site-packages (from gruut->TTS==0.5.0) (0.9.7)
Requirement already satisfied: gruut-ipa~=0.12.0 in /nix/store/gv5f5pdgjrk0lgwkpg6vvqyb7k1c7gy2-python3.9-gruut-ipa-0.12.0/lib/python3.9/site-packages (from gruut->TTS==0.5.0) (0.12.0)
Requirement already satisfied: networkx<3.0.0,>=2.5.0 in /nix/store/fjmhgdjrvc7q7y3y56lhc800rj3vkgi4-python3.9-networkx-2.6.3/lib/python3.9/site-packages (from gruut->TTS==0.5.0) (2.6.3)
Requirement already satisfied: dateparser in /nix/store/w64g1k95ri9n6frjiziqdvhy9gdf6mv4-python3.9-dateparser-1.1.0/lib/python3.9/site-packages (from gruut->TTS==0.5.0) (1.1.0)
Requirement already satisfied: Babel<3.0.0,>=2.8.0 in /nix/store/rkghmghfr3jxf2wlsys1gnvgdxbpk6pg-python3.9-Babel-2.9.1/lib/python3.9/site-packages (from gruut->TTS==0.5.0) (2.9.1)
Requirement already satisfied: decorator>=3.0.0 in /nix/store/prq5gfwzs8sy5w0758c3j2p4ahiql3j7-python3.9-decorator-5.1.0/lib/python3.9/site-packages (from librosa->TTS==0.5.0) (5.1.0)
Requirement already satisfied: joblib>=0.14 in /nix/store/r3gi7hfh3lxaf4di3jw8cxx72nwk5zrh-python3.9-joblib-1.1.0/lib/python3.9/site-packages (from librosa->TTS==0.5.0) (1.1.0)
Requirement already satisfied: audioread>=2.0.0 in /nix/store/fj1a24x0lx48v3n0hxbf2sgn3aaq5p59-python3.9-audioread-2.1.9/lib/python3.9/site-packages (from librosa->TTS==0.5.0) (2.1.9)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /nix/store/5vfvk37mbyfx4qxcz8frvpvxp42f8hxd-python3.9-scikit-learn-1.0.2/lib/python3.9/site-packages (from librosa->TTS==0.5.0) (1.0.2)
Requirement already satisfied: packaging>=20.0 in /nix/store/gy3pnc7bpff1h4ylhrivs4cjlvmxl0dk-python3.9-packaging-20.9/lib/python3.9/site-packages (from librosa->TTS==0.5.0) (20.9)
Requirement already satisfied: resampy>=0.2.2 in /nix/store/fc9dzlhfkmvgwvwqx2z8lkxdmhi0b5rk-python3.9-resampy-0.2.2/lib/python3.9/site-packages (from librosa->TTS==0.5.0) (0.2.2)
Requirement already satisfied: pooch>=1.0 in /nix/store/9gj4brr04j0wqsvnhqalr14k4fdp6135-python3.9-pooch-1.5.2/lib/python3.9/site-packages (from librosa->TTS==0.5.0) (1.5.2)
Requirement already satisfied: setuptools in /nix/store/w1lsr2i37fr0mp1jya04nwa5nf5dxm2n-python3.9-setuptools-57.2.0/lib/python3.9/site-packages (from numba->TTS==0.5.0) (57.2.0.post0)
Requirement already satisfied: llvmlite<0.38,>=0.37.0rc1 in /nix/store/bm91icwn447r4h6g9mj3mi03wdirlw4k-python3.9-llvmlite-0.37.0/lib/python3.9/site-packages (from numba->TTS==0.5.0) (0.37.0)
Requirement already satisfied: cffi>=1.0 in /nix/store/ig2bdwmplvs6dyg07fdyh006ha768jh1-python3.9-cffi-1.15.0/lib/python3.9/site-packages (from soundfile->TTS==0.5.0) (1.15.0)
Requirement already satisfied: cycler>=0.10 in /nix/store/w1isgqzffs2pzj9312mbjgk8qjnvbcih-python3.9-cycler-0.11.0/lib/python3.9/site-packages (from matplotlib->TTS==0.5.0) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /nix/store/5fism0m4a19lqla9nx6i58fzfkr318yk-python3.9-fonttools-4.26.2/lib/python3.9/site-packages (from matplotlib->TTS==0.5.0) (4.26.2)
Requirement already satisfied: python-dateutil>=2.7 in /nix/store/prbmd3abzxry9rh6gc8aclcdszs1jd0s-python3.9-python-dateutil-2.8.2/lib/python3.9/site-packages (from matplotlib->TTS==0.5.0) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /nix/store/igmbvlfi6n7gxf8yf3xa8jgp5jnh3lk3-python3.9-kiwisolver-1.3.2/lib/python3.9/site-packages (from matplotlib->TTS==0.5.0) (1.3.2)
Requirement already satisfied: pyparsing>=2.2.1 in /nix/store/803ffb21rv4af521pplb72zjm1ygm9kk-python3.9-pyparsing-2.4.7/lib/python3.9/site-packages (from matplotlib->TTS==0.5.0) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /nix/store/gdk7w7mj34r2jifl483hpz65kcfh27di-python3.9-Pillow-8.4.0/lib/python3.9/site-packages (from matplotlib->TTS==0.5.0) (8.4.0)
Requirement already satisfied: pytz>=2017.3 in /nix/store/zbp0p651wxfkj9l3800zk425dmf7ad3j-python3.9-pytz-2021.3/lib/python3.9/site-packages (from pandas->TTS==0.5.0) (2021.3)
Requirement already satisfied: protobuf>=3.8.0 in /nix/store/yvrxljpavz1rrqn19qs654abj4ckd00s-python3.9-protobuf-3.19.0/lib/python3.9/site-packages (from tensorboardX->TTS==0.5.0) (3.19.0)
Requirement already satisfied: typing-extensions in /nix/store/j3nf4jlx6dvz73r3vby641faavkbp2xl-python3.9-typing_extensions-3.10.0.2/lib/python3.9/site-packages (from torch->TTS==0.5.0) (3.10.0.2)
INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of tensorboardx to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyyaml to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyworld to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pysbd to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pypinyin to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mecab-python3 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of soundfile to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numba to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of librosa to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of jieba to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of inflect to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of gruut to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of gdown to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cython to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of coqpit to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of anyascii to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of fsspec to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of unidic-lite to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of tts to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install torchaudio==0.10.0+cu113 and tts==0.5.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    tts 0.5.0 depends on torch
    torchaudio 0.10.0+cu113 depends on torch==1.10.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
builder for '/nix/store/19mvg20hv2scq1ywn1d3x2kqqnmq53f6-tts-0.5.0.drv' failed with exit code 1
```

**Comment by mweinelt** [comment]
Builds for me, untested. Please review.

**Comment by Mic92** [comment]
Yep, `tv` still sounds similar weird: https://dl.thalheim.io/TSlTPnBA9wOPWpuYkhCfWA/tv.wav

**Comment by davidak** [comment]
@Mic92 they don't consider that a bug :grimacing: 

https://github.com/coqui-ai/TTS/issues/484

**Comment by Mic92** [comment]
@davidak I am now just using a different model: https://github.com/Mic92/dotfiles/blob/master/nixos/eve/modules/tts.nix#L7

**Pull request merged**
