### PR TITLE
linux: Backports linux kernel 4.17 to 18.03

### PR DESCRIPTION
**Pull request by samueldr**
###### Motivation for this change

`linuxPackages_latest` [was (understandably) downgraded from 4.16 to 4.14, since the 4.16 series isn't supported anymore](https://github.com/NixOS/nixpkgs/commit/298e170b36b79f4c6b19816a7abbf8392a490840).

The commit message was:

> It would be nice to have 4.17, but ATM it won't build;
> some changes in the (shared) kernel config would be needed.

Here I have backported with cherry-picked conflict-resolved the relevant commits to make 4.17 build for 18.03, and the relevant updates. Do tell if keeping the whole commit history cherry-picked is too much.

###### Testing done

I am currently dogfooding the use of 4.17 on 18.03 with this branch on my machine.

I don't know of NixOS tests that test `linuxPackages_latest`. I don't know either if one of tests can be used to test another kernel.

I have not tested most packages depending on the kernel, except the default settings [+ VirtualBox](https://github.com/NixOS/nixpkgs/pull/43237).

###### Things done

- ✔️ Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - ✔️ NixOS
   - 🆖 macOS
   - ❌ other Linux distributions
- ❓ Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- ❌ Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- 🆖 Tested execution of all binary files (usually in `./result/bin/`)
- ✔️ Determined the impact on package closure size (by running `nix path-info -S` before and after) **new package, closure sizes goes from 0 to 66304848**.
- ✔️ Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
Seems OK.

**Comment by vcunat** [comment]
Thanks, I haven't noticed the first commit you picked and gave up too soon, assuming noone would want such a new kernel on 18.03.

/cc @NeQuissimus: for backports of _future_ 4.17 bumps.

**Comment by Baughn** [comment]
There are definitely some who would. Keep in mind, some of the hardware support for Ryzen/Zen CPUs (working around the C-state bug, etc.) was only mainlines in 4.17.

**Comment by vcunat** [comment]
Ah, right.  I even have an occasionally problematic Ryzen on 18.03 :-)  but I think I'm mostly hitting those compilation crashes and not the C-state problem.

- [ ] the hardened config will need some cherry-picking: https://hydra.nixos.org/job/nixos/release-18.03/nixpkgs.linux_latest_hardened.x86_64-linux

**Comment by Baughn** [comment]
The compilation crashes were due to marginal CPUs that have been recalled... you should talk to AMD, they'll let you swap it for a new one.

**Comment by vcunat** [comment]
I had heard that, and I'll do that in the end, I guess.  (I assume I'll have to go through the seller where it might be difficult to explain.)  I had long been hoping for a fix in firmware or similar.

**Pull request merged**
