### PR TITLE
dotnetCorePackages.dotnet_9: init at 9.0.0-preview.1

### PR DESCRIPTION
**Pull request by corngood**
This is based on #190129, and adds both source and binary packages for .NET 9.0 preview 1.

FYI @NixOS/dotnet 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
Result of `nixpkgs-review pr 290636` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>dotnetCorePackages.aspnetcore_9_0</li>
    <li>dotnetCorePackages.dotnet_9.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_9.runtime</li>
    <li>dotnetCorePackages.dotnet_9.sdk</li>
    <li>dotnetCorePackages.dotnet_9.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_9.sdk.packages</li>
    <li>dotnetCorePackages.dotnet_9.vmr</li>
    <li>dotnetCorePackages.runtime_9_0</li>
    <li>dotnetCorePackages.sdk_9_0</li>
  </ul>
</details>

**Comment by corngood** [comment]
This should be ready to go now.  FYI @GGG-KILLER

**Review by GGG-KILLER — APPROVED** [review]

**Comment by GGG-KILLER** [comment]
Looks good to me @corngood, can't exactly test it right now, but the code looks fine

**Comment by GGG-KILLER** [comment]
Result of `nixpkgs-review pr 290636` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>dotnetCorePackages.aspnetcore_9_0</li>
    <li>dotnetCorePackages.dotnet_9.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_9.runtime</li>
    <li>dotnetCorePackages.dotnet_9.sdk</li>
    <li>dotnetCorePackages.dotnet_9.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_9.sdk.packages</li>
    <li>dotnetCorePackages.dotnet_9.vmr</li>
    <li>dotnetCorePackages.runtime_9_0</li>
    <li>dotnetCorePackages.sdk_9_0</li>
  </ul>
</details>

**Review by GGG-KILLER — APPROVED** [review]
LGTM, code is okay and have done the following tests successfully:
- [x] Built and ran app with binary sdk;
- [x] Ran binary built app with binary runtime;
- [x] Ran binary built app with source-built runtime;
- [x] Built and ran app with source-built sdk;
- [x] Ran source-built app with source-built runtime;
- [x] Ran source-built app with binary runtime;

**Comment by GGG-KILLER** [comment]
@corngood might've found an issue with ASP.NET Core:

```console
$ dotnet publish -r linux-x64 -c Release
MSBuild version 17.10.0-preview-24101-01+07fd5d51f for .NET
Restore complete (0.5s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  tmpzCCcN succeeded with warnings (0.5s) → bin/Release/net9.0/linux-x64/publish/
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/sdk/9.0.100-preview.1.24101.1/Sdks/Microsoft.NET.Sdk.Web/analyzers/cs/Microsoft.AspNetCore.Analyzers.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/sdk/9.0.100-preview.1.24101.1/Sdks/Microsoft.NET.Sdk.Web/analyzers/cs/Microsoft.AspNetCore.Mvc.Analyzers.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/packs/Microsoft.NETCore.App.Ref/9.0.0-preview.1.24080.9/analyzers/dotnet/cs/Microsoft.Interop.ComInterfaceGenerator.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/packs/Microsoft.NETCore.App.Ref/9.0.0-preview.1.24080.9/analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/packs/Microsoft.NETCore.App.Ref/9.0.0-preview.1.24080.9/analyzers/dotnet/cs/Microsoft.Interop.LibraryImportGenerator.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/packs/Microsoft.NETCore.App.Ref/9.0.0-preview.1.24080.9/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/packs/Microsoft.NETCore.App.Ref/9.0.0-preview.1.24080.9/analyzers/dotnet/cs/System.Text.RegularExpressions.Generator.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/packs/Microsoft.AspNetCore.App.Ref/9.0.0-preview.1.24081.5/analyzers/dotnet/cs/Microsoft.AspNetCore.App.Analyzers.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/packs/Microsoft.AspNetCore.App.Ref/9.0.0-preview.1.24081.5/analyzers/dotnet/cs/Microsoft.AspNetCore.Components.Analyzers.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/packs/Microsoft.AspNetCore.App.Ref/9.0.0-preview.1.24081.5/analyzers/dotnet/roslyn4.4/cs/Microsoft.Extensions.Logging.Generators.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/packs/Microsoft.AspNetCore.App.Ref/9.0.0-preview.1.24081.5/analyzers/dotnet/roslyn4.4/cs/Microsoft.Extensions.Options.SourceGeneration.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]
    CSC : warning CS9057: The analyzer assembly '/nix/store/wg2spyh6p3yr4sij5rvx9hk2brgk4fa5-dotnet-sdk-9.0.100-preview.1.24101.1/sdk/9.0.100-preview.1.24101.1/Sdks/Microsoft.NET.Sdk.Razor/source-generators/Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/ggg/Git/NixOS/nixpkgs/tmpzCCcN/tmpzCCcN.csproj]

Build succeeded with warnings in 1.3s
```

this seems to happen both on the binary and source-build.

**Comment by corngood** [comment]
@GGG-KILLER thanks for testing.  I wrote a test for aspnetcore (see #290636), but I wasn't able to reproduce those warnings.  Can you tell me about the project you're publishing there?

**Comment by GGG-KILLER** [comment]
> @GGG-KILLER thanks for testing.  I wrote a test for aspnetcore (see #290636), but I wasn't able to reproduce those warnings.  Can you tell me about the project you're publishing there?

I pretty much just did the following:

    dotnet new webapi
    dotnet restore --force
    dotnet build
    dotnet publish -r linux-x64 -c Release

**Comment by corngood** [comment]
Hmm, I couldn't reproduce it.  Could also be something in $HOME (e.g. ~/.nuget)?

P.S. The test I added I uses the `web` instead of `webapi` template, because the latter has some dependencies on non-sdk stuff:

```
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0-preview.1.24081.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
```

**Comment by corngood** [comment]
Sorry, I put the wrong link to the new tests above.  It's #294070.

**Comment by GGG-KILLER** [comment]
I believe this is ready to merge, is there anything we're waiting on?

**Comment by corngood** [comment]
No, I think it's good.  It's just new packages again, so pretty low risk.

There's a problem with building dotnet_8 on x86_64-darwin (#294088), which will likely happen to this one as well, but there's no reason to hold this up.

**Pull request merged**
