### PR TITLE
nixos.ipfs: Fix startup after unclean shutdown.

### LINKED ISSUE #135684: ipfs profile apply hangs after some unclean shutdowns.
### Describe the bug

ipfs-pre-start hangs on `ipfs config profile apply local-discovery` on startup.

### Steps To Reproduce

```nix
	services.ipfs = {
		enable = true;
		enableGC = true;
		apiAddress = "/unix/run/ipfs-api.sock";
		gatewayAddress = "/unix/run/ipfs-gateway.sock";
		extraFlags = [
			"--enable-namesys-pubsub"
		];
		extraConfig = {
			# We don't actually want or need CORS but go-ipfs uses this to do referrer and origin checks.
			API.HTTPHeaders."Access-Control-Allow-Origin" = [
				"https://ipfs.${config.deployment.targetHost}"
			];
		};
	};
```

??? sometimes (quite often) it hangs on startup.

### Expected behavior

IPFS starts up successfully.

### Additional context

Startup can be forced via `gdb --batch --eval-command 'call exit(0)' --pid $(pgrep ipfs)`

There were no migrations that needed to be run.

### Notify maintainers

@fpletz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(kevincox): `""`
 - channels(root): `"nixos-21.05pre272380.f6b5bfdb470"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: 
- services.ipfs
```

### PR DESCRIPTION
**Pull request by kevincox**
Fixes https://github.com/NixOS/nixpkgs/issues/135684

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
How do you trigger the unclean shutdown ?

**Comment by kevincox** [comment]
SIGKILL. In my case this is often sent automatically by systemd after a hung instance fails to quit gracefully.

**Review by fufexan — APPROVED** [review]

**Comment by happysalada** [comment]
If I understand correctly,
- Sometimes you want to shut down ipfs (with `systemctl stop ipfs` ?), however ipfs takes a little too long to respond, so systemd sends it a kill signal.
- When trying to restart the service after an unclean shutdown ipfs hangs. This PR aims at enabling start after an unclean shutdown.

The root cause of why ipfs fails to stop gracefully is still to be figured out, correct?
Also if we want to test this and be sure that the shutdown will be aggressive, it's better to use `pkill ipfs`, correct? Just in case a systemctl stop shuts it down gracefully on our machine.

**Comment by kevincox** [comment]
In my case this is frequently caused by ipfs hanging. I am trying to figure out why it is getting stuck upstream in https://github.com/ipfs/go-ipfs/issues/8409. 

But unclean shutdowns can happen for any number if reasons, OOM kills, hard power off... One important fact is that the current NixOS module doesn't handle this gracefully. We need to solve this. 

I'm not 100% sure about this solution, still testing it out, but we do need something.

**Comment by L-as** [comment]
Isn't this entirely an upstream problem?

**Comment by L-as** [comment]
I doubt NixOS users are the only people with this problem.

**Comment by kevincox** [comment]
See https://github.com/ipfs/go-ipfs/issues/8407#issuecomment-915266567

Upstream doesn't seem very interested in solving the problem. We can switch this in for the proposed flag if it ever gets added but basically their stance is that since we have the API socket open (systemd socket activation will hold the unix or IP socket open and queue requests while we start up) it is reasonable that `ipfs config profile apply` hangs. There are some legitimate complex scenarios here that makes this difficult if not impossible to handle automatically.

So basically unless upstream does something to help out we have 2 main options:

1. Disable socket-activation and socket passing.
2. Implement this.

I much prefer the second option because socket activation provides a large number of features such as parallel startup, hitless restarts and gives us more control over the socket.

I agree that NixOS probably isn't the only distro to hit this issue, anyone who tries to do this type of configuration on startup will likely have the same problem. But until upstream fixes the problem this is the best we can do IIUC.

**Review by L-as — APPROVED** [review]
Doesn't seem like there is any better solution than this then.

**Comment by kevincox** [comment]
I've tested this for a while now, it appears that this allows graceful restarts. I'll keep my eyes open for a more "official" API but this will have to do for now.

**Pull request merged**
