### PR TITLE
[WIP] Separate NixOS lib and nixpkgs lib

### PR DESCRIPTION
**Pull request by ericsagnes**
###### Motivation for this change

This was motivated by this [comment](https://github.com/NixOS/nixpkgs/pull/18142#issuecomment-249539602).

The ultimate goal of this PR is to be able to include NixOS lib functions in an easy manner for custom projects, eg `with import <nixpkgs/nixos>; lib....`.
An other objective is to have a clearer separation between nixos and nixpkgs functions.

Until now, only nixpkgs had a lib, and NixOS related functions were part of this lib, directly called via `imports` (eval-config) or directly defined in files (test related functions).

For a better separation and cleaner namespaces, this PR create a new lib to nixos, that can be called with `with import <nixpkgs/nixos/lib>; ...` or `with import <nixpkgs/nixos>; lib....` and move the functions that has nothing to do with nixpkgs in the nixos library.

This is a work in progress, and this aims to be as much backward compatible as possible.
### nixpkgs lib side

`options`, `types`, `modules` have moved to nixos lib, but each file (`lib/options.nix`, ...) is still present to not break any direct imports (eg, `import <nixpkgs/lib/options.nix>`) that users might have in their setups.

The nixos lib, can be accessed via the `lib.nixos` namespace. So if options functions must be used in nixpkgs context, they can be accessed with `lib.nixos.options`.
Note that there is no trace of usage of options, types and modules in the nixpkgs only source, so the new namespace _should_ not break things.
### nixos lib side

A lib top level attribute was added to ./nixos that can be used with "with import <nixpkgs/nixos>; lib..." or "with import <nixpkgs/nixos/lib>;".
This lib includes previous nixpkgs lib `options`, `types` and `modules`.
The nixpkgs lib is in the namespace `lib.nixpkgs` **AND** at top-level.

This is the `lib` that is used in the module system, so having nixpkgs lib at top level is required to not break modules code that expect nixpkgs lib functions to be accessible from lib.

---

This is in early state and will require more extensive testing to be sure nothing break it is much backward compatible as possible before being mergeable.

In current state, this can build the manual and a simple config via VM.

Feedback is welcomed.

---

cc @edolstra

### CODE REVIEW

**Comment by ericsagnes** [comment]
Any opinions on this?

**Comment by vcunat** [comment]
The idea at least seems good to me, but I haven't done much nixos/\* stuff, so better if someone else looks at it as well.

**Comment by nbp** [comment]
I think this change would have made sense when nixpkgs and NixOS were in separated repository.
I honestly do not recall why I chose nixpkgs lib over adding a new one to NixOS back then, probably because we were already heavily using nixpkgs/lib.

**Comment by ericsagnes** [comment]
> I think this change would have made sense when nixpkgs and NixOS were in separated repository.

As it was only linked in the description and easy to miss, bellow is the quote from @edolstra comment that motivated this PR:

> I don't think we should move the NixOS testing stuff to the non-NixOS part of Nixpkgs. They're NixOS-specific after all.

I do agree with that, but I think that it could be useful to have some NixOS specific functions easily available from external projects, like testing related functions.

Making a NixOS specific library that could be imported with `import <nixpkgs/nixos> {}; lib.callTest` felt like a good solution for this.
In this process, it made sense to also move NixOS specific parts of the nixpkgs lib to that library.

I hope this can help to clarify the motivation.

**Comment by aneeshusa** [comment]
I've found the module system nice to be able to use outside of NixOS, for example in defining a user environment (see https://github.com/rycee/home-manager for instance), so I'd like to see it continue to be available from the main Nixpkgs `lib`. I don't see it as being NixOS specific.

**Comment by ericsagnes** [comment]
I have totally forgot about this one.

I agree that it is easy to use nix lib from outside of nixpkgs, and I do that in a few of my personal projects.
The main goal of this PR was to have a cleaner organization of libs with a new `lib.nixos` namespace.
And also to have a cleaner `lib` available in nixos modules to avoid #19899 like problems.

Anyway, closing as this has been open for too long.
Will reopen if someone is interested by this.

**Pull request closed without merging**
