### PR TITLE
perlPackages: fix meta and fix build with perl-5.26

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

fix build

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build perlPackages.CHI perlPackages.ClassMakeMethods perlPackages.ClassMethodMaker

**Comment by xeji** [comment]
Looks like the fix for CHI doesn't work.

**Comment by volth** [comment]
> Looks like the fix for CHI doesn't work.

@xeji the fix is for ```perl-5.26``` only (nixpkgs is using ```perl-5.24```) so it should not break the tests. "Unescaped left brace in regex is deprecated, passed through in regex" is a warning in ```perl-5.24``` and a fatal error in ```perl-5.26```, so no wonder the warning is printed.

Broken tests seem irrelevant, perhaps something else break them (it works well locally but I am not on the cutting edge ```master```, will check again after upgrade)

**Comment by volth** [comment]
Hm, works for me on ```x86_64-linux``` with the recent ```staging```.

**Comment by volth** [comment]
@GrahamcOfBorg build perlPackages.CHI

**Comment by volth** [comment]
Nothing changed, just rebased.

**Comment by xeji** [comment]
It's magic :joy:

**Pull request merged**
