### PR TITLE
python3Packages.nixpkgs-pytools: init at 1.0.0

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

nixpkgs-pytools has been added to the nix-community! https://github.com/nix-community/nixpkgs-pytools

Adding a release to nixpkgs to make it easier to use.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc: @makefu

### CODE REVIEW

**Comment by costrouc** [comment]
@GrahamcOfBorg build python3Packages.nixpkgs-pytools

**Review by makefu — CHANGES_REQUESTED** [review]
add `python3.pkgs.nixpkgs-pytools` to `top-level/default.nix` as well as this is more a cli tool than a python library.

Running `$(nix-build -A python3.pkgs.nixpkgs-pytools)/bin/python-package-init nixpkgs-pytools --version 1.0.0` results in https://gist.github.com/makefu/91f34bbf91c7cc9a52b47a8eb87cb294 which is damn close to this PR (a good thing!)

Changelog can be found at https://github.com/nix-community/nixpkgs-pytools/blob/master/CHANGELOG.md

**Comment by costrouc** [comment]
Thanks for adding a changelog I will make sure to use that. Also will add to top-level to make it a cli tool as well.

**Comment by costrouc** [comment]
@GrahamcOfBorg build python3Packages.nixpkgs-pytools

**Comment by makefu** [comment]
@GrahamcOfBorg build nixpkgs-pytools

**Review by makefu — APPROVED** [review]
LGTM

**Review by dotlambda — APPROVED** [review]
Works like a charm. Thanks a lot for writing this helpful script @costrouc!

**Pull request merged**
