### PR TITLE
serioussam: init at 1.10.6b

### PR DESCRIPTION
**Pull request by TheBrainScrambler**
## Description of changes

Open source game engine version developed by Croteam for Serious Sam Classic.
(This runs Serious Sam: The First Encounter and Serious San: The Second Encounter. Those are proprietary FPS games. The engine is libre but the assets are not)

### Old stuff no longer relevant
I'm making this as a draft because I need help on it. I am hit by this odd bug https://github.com/tx00100xt/SeriousSamClassic/issues/17. However I still don't know if it is caused by the nix derivation or by my computer. So I need someone else who builds this package and runs it to see if your graphics are also messed up like mine.

Note that this is also kind of half-assed, I didn't give an explanation for the assets and didn't fully try The Second Encounter, I only tried Serious Sam: The First Encounter. The Second Encounter isn't even correctly patched and certainly doesn't run. So only test The First Encounter.

Instructions:
- Get this nix code the way you like and build it, nixpkgs-review might be the easiest way
- Somehow copy everything from https://github.com/tx00100xt/SeriousSamClassic/tree/main/SamTFE in `~/.local/share/Serious-Engine/serioussam`. See https://github.com/tx00100xt/SeriousSamClassic/issues/17#issuecomment-1676404784
- Copy assets into `~/.local/share/Serious-Engine/serioussam`. See https://github.com/tx00100xt/SeriousSamClassic/#running-the-game for the list of files required.
- Run result/bin/serioussam
- Now a window should have appeared. Wait until you hear music and press Left Click on your mouse. You should now see a demo where someone says "Here comes trouble". Report to me if the demo looks normally or if it is messed up like [this](https://user-images.githubusercontent.com/34945377/260311882-1d8494c0-d002-49f3-bd88-76843b398ae8.png)

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tx00100xt** [comment]
>
>Report to me if the demo looks normally or if it is messed up like [this](https://user-images.githubusercontent.com/34945377/260311882-1d8494c0-d002-49f3-bd88-76843b398ae8.png)
>
Everything looks fine
https://github.com/tx00100xt/SeriousSamClassic/issues/17#issuecomment-1752153502

**Comment by tx00100xt** [comment]
> @TheBrainScrambler


Good day. I recently made an update: [Hotfix]( https://github.com/tx00100xt/SeriousSamClassic/releases)
You can use the [1.10.6](https://github.com/tx00100xt/SeriousSamClassic/releases/tag/1.10.6) tag that includes all fixes.

**Comment by TheBrainScrambler** [comment]
> > @TheBrainScrambler
> 
> Good day. I recently made an update: [Hotfix](https://github.com/tx00100xt/SeriousSamClassic/releases) You can use the [1.10.6](https://github.com/tx00100xt/SeriousSamClassic/releases/tag/1.10.6) tag that includes all fixes.

Yes, I noticed, updated this PR and said I updated 4 days ago :p

https://github.com/NixOS/nixpkgs/pull/249156#issuecomment-1769103087

So again thanks for the fix ! Graphics still don't work for me though. Must be my computer.

**Comment by tx00100xt** [comment]
Hello.
There is an error in the default.nix file. Checksums do not match.
>unpacking source archive /build/v1.10.6.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/rvfrs7xfkj8f2svc9hky4smlbqnfyal4-source.drv':
         specified: sha256-6qmzpbFD4N0DDY66DC5vJWkO5SyTbZ6KNZh7R/+PltQ=
            got:    sha256-cAuld8msbKKVCslvgh71MSH57IivZ1l6agYIcCoDgQc=
error: 1 dependencies of derivation '/nix/store/fca1spd75mc24fvadj8p2qf7ifmcyw90-serioussam-1.10.6.drv' failed to build
>

To make it easier, I made the archive with fix's. Before that, I tested everything on a virtual machine, made patches to search for the libvorbisfile library. Result on video: (click on the picture to watch the video)
[Watch the video](https://youtu.be/w25xcUeHX-4)
Archive in attachment.
[serioussam.tar.gz](https://github.com/NixOS/nixpkgs/files/13491569/serioussam.tar.gz)

**Comment by TheBrainScrambler** [comment]
When I try to build it doesn't work with version 1.10.6b, probably because you didn't make a release for that one but only a tag. Did it work for you ?

For the checksum sorry I must have forgotten to change it before building to test my changes. A classic noob trab in nixpkgs.

But why did you need to patch the source code to make it search for libvorbis ? It already works by adding it to the LD_LIBRARY_PATH env var. Since these kind of things are things related to Nix, I don't think we should patch the source code if we can avoid it. Though I would need the advice of someone more experienced with nixpkgs than me about this.

**Comment by tx00100xt** [comment]
> When I try to build it doesn't work with version 1.10.6b, probably because you didn't make a release for that one but only a tag. Did it work for you ?
>
Yes, everything works with the 1.10.6b tag. Building without release.
> But why did you need to patch the source code to make it search for libvorbis ? It already works by adding it to the LD_LIBRARY_PATH env var. Since these kind of things are things related to Nix, I don't think we should patch the source code if we can avoid it. Though I would need the advice of someone more experienced with nixpkgs than me about this.
>
I didn't know the sound worked. After the build was interrupted due to a checksum, I simply started making a new package.

There are no fundamental changes between version v1.10.6 and tag 1.10.6b. There are only commits for BSD platforms. The tag was made for them.

I think since the sound works, the simplest and most correct solution is to fix the checksum in the existing package.

**Comment by TheBrainScrambler** [comment]
> > When I try to build it doesn't work with version 1.10.6b, probably because you didn't make a release for that one but only a tag. Did it work for you ?
> 
> Yes, everything works with the 1.10.6b tag. Building without release.

Lol I know why now. I didn't see that there is no "v" before the tag. I was trying to fetch v1.10.6b instead of 1.10.6b. Works now.

> > But why did you need to patch the source code to make it search for libvorbis ? It already works by adding it to the LD_LIBRARY_PATH env var. Since these kind of things are things related to Nix, I don't think we should patch the source code if we can avoid it. Though I would need the advice of someone more experienced with nixpkgs than me about this.
> 
> I didn't know the sound worked. After the build was interrupted due to a checksum, I simply started making a new package.

Ah ok then I will just keep my fix instead because it doesn't require a separate patch.

> There are no fundamental changes between version v1.10.6 and tag 1.10.6b. There are only commits for BSD platforms. The tag was made for them.
> 
> I think since the sound works, the simplest and most correct solution is to fix the checksum in the existing package.

My mistake, I corrected it on my side but forgot to push it. Now I've also updated to 1.10.6b.

Now that I've corrected the checksum, I've realized that I must have been still using an old version of serioussam instead of version 1.10.6, so I've restested it, and ... It works now ! Graphics work properly and I can finally play the game ! So this graphics bugs must have been in the older version. 1.10.6b works too of course. Not sure which one, but probably the one before, 1.10.5.

Also regarding this addition in the `meta.longDescription`
>       Please note that when installing the game on a system, all content of the original game is
>       required (including directories: Controls, Data, Demos, Help, and so on) in directories
>         ~/.local/share/Serious-Engine/serioussam(se).
I had already said above where to copy assets for each game, and gave links to where you list the exact assets required. So what was the point of this addition ?

**Comment by tx00100xt** [comment]
> I had already said above where to copy assets for each game, and gave links to where you list the exact assets required. So what was the point of this addition ?
>
When installing a game on the system, all resources are needed. When installing the game locally, the gro files and the levels directory are enough, since the repository already has some of the resources.
Reminder for users to copy everything.


> It works now ! Graphics work properly and I can finally play the game ! So this graphics bugs must have been in the older version. 1.10.6b works too of course. Not sure which one, but probably the one before, 1.10.5.
>
Great!
There were a lot of changes between versions 1.10.5 and 1.10.6.
This probably had an effect.

**Comment by TheBrainScrambler** [comment]
> When installing a game on the system, all resources are needed. When installing the game locally, the gro files and the levels directory are enough, since the repository already has some of the resources.
> Reminder for users to copy everything.

No, it works for me with only the resources you mention in
https://github.com/tx00100xt/serioussamclassic#running-the-game
so with only the gro files, the Levels and the Help directories.

The game automatically generates the other resources.

**Comment by tx00100xt** [comment]
> so with only the gro files, the Levels and the Help directories. The game automatically generates the other resources.
>
It will work - yes.
But in the Scripts directory there are additional settings for the game, and in the Controls directory there are presets for keyboard settings. Without them there are simply fewer opportunities. In principle, there will only be a basic set, which is in 1_00c.gro

**Comment by TheBrainScrambler** [comment]
> I wrote the code for placing files in .local/share/Serious-Engine/serious sam. These files are not copied there by the game. New ones are just being created. [tx00100xt/SeriousSamClassic@0c83418](https://github.com/tx00100xt/SeriousSamClassic/commit/0c8341884992a06910a685b64c44f43e31fe4a0e) When you created the issue. You copied all these files yourself. [tx00100xt/SeriousSamClassic#17 (comment)](https://github.com/tx00100xt/SeriousSamClassic/issues/17#issuecomment-1676443555)

Ah thanks a lot for this, indeed I copied everything, that's why it was working ... I confused myself because I tried before to move my `.local/share/Serious-Engine/serioussam` directory somewhere else, then created a new one with only the files in https://github.com/tx00100xt/serioussamclassic#running-the-game and because it just ran I thought this was indeed how I did. And then when you said that for examples demos would be missing I tested this with my serioussam folder which has all the assets ... Anyway I've tried again with a serioussam that has only the files of https://github.com/tx00100xt/serioussamclassic#running-the-game and indeed the demos are missing. Sorry about this confusion.

> > Since in `meta.longDescription` I'm linking to your README where you list all the required files you just have to update that list of required files.
> 
> Yes, I've done it before. There is an indication in the readme that you need to copy everything. So you can just refer to it. https://github.com/tx00100xt/SeriousSamClassic#install-the-game-in-system-usrbinusrlibusrshare
> 
> > Note: If the game does not find the data on the recommended paths, then it will independently perform a search. Please note that when installing the game on a system, all content of the original game is required (including directories: Controls, Data, Demos, Help, and so on) in directories /usr/share/serioussam(se) or ~/.local/share/Serious-Engine/serioussam(se), depending on the directory you select. You can see a more detailed description in the [Wiki](https://github.com/tx00100xt/SeriousSamClassic/wiki/How-to-building-a-package-for-Debian-or-Ubuntu.md#game-resources).

Ah indeed thanks. I really have a problem with distinguishing a local install from a system install. Will update the `meta.longDescription` with the proper link.

**Comment by tx00100xt** [comment]
> EDIT: done, what do you think of it ? I linked to https://github.com/tx00100xt/SeriousSamClassic/wiki/How-to-building-a-package-for-Debian-or-Ubuntu.md#game-resources

Yes. Everything is fine.

**Comment by arianvp** [comment]
Please see CONTRIBUTING.md on how to change base branch without mass pinging people. I'm closing this now to avoid spam.

**Pull request closed without merging**
