### PR TITLE
python311Packages.scs: relax floating point precision for linux test

### PR DESCRIPTION
**Pull request by ghost**
workaround for: https://github.com/bodono/scs-python/issues/81 with upstream patch https://github.com/bodono/scs-python/pull/82

after the update to scipy 1.12 the test_solve_feasible fails on linux with 1 of the 185 floating point values not being equal to 4 decimal places. relax the check to only check 3 decimal places.

build failures related to python311Packages.osqp failing
https://hydra.nixos.org/build/247560486
https://github.com/osqp/osqp-python/issues/121

Result of `nixpkgs-review pr 284299` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.blackjax</li>
    <li>python311Packages.blackjax.dist</li>
    <li>python311Packages.cvxpy</li>
    <li>python311Packages.cvxpy.dist</li>
    <li>python311Packages.jaxopt</li>
    <li>python311Packages.jaxopt.dist</li>
    <li>python311Packages.qpsolvers</li>
    <li>python311Packages.qpsolvers.dist</li>
    <li>python311Packages.qutip</li>
    <li>python311Packages.qutip.dist</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python311Packages.scs</li>
    <li>python311Packages.scs.dist</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by a-n-n-a-l-e-e** [comment]
> Result of `nixpkgs-review pr 284299` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 12 packages failed to build:

related to python311Packages.osqp failing
https://hydra.nixos.org/build/247560486

**Comment by a-n-n-a-l-e-e** [comment]
failures in osqp after scipy update seem significant. https://hydra.nixos.org/build/247560486
opened issue: https://github.com/NixOS/nixpkgs/issues/284308
moving this to draft as could be scipy issue.

**Review by doronbehar — COMMENTED** [review]
Looks good and legitimate to me. Thanks for working on this! ~~Why is this a draft?~~ Oh I see why.. I think this could be good to go.

**Comment by a-n-n-a-l-e-e** [comment]
> Looks good and legitimate to me. Thanks for working on this! ~Why is this a draft?~ Oh I see why.. I think this could be good to go.

after seeing the failures in https://github.com/osqp/osqp-python/issues/121 i thought i'd hold off for a few days and see if anyone responds to the bug reports. the underling implementations of these packages are c/c++/fortran libraries. in the modules scipy seems to be used just to do sparse matrix conversions -- but the tests use it to compare output from the underlying libs. unclear if failures are due to bugs in the unit tests triggered by the update or problems with scipy 1.12

**Comment by doronbehar** [comment]
I understand. Yes let's give the upstreams a bit of time to investigate these issues.

**Pull request merged**
