### PR TITLE
balena-cli: init at <Updating>

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

Add [balena-cli](https://github.com/balena-io/balena-cli) - a CLI tool to manage [balena](https://balena.io/)'s devices and apps.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
Apparently, their updates are rather frequent, so this package should have it's own `./generate.sh` script that will do it all, only for this package. This will reduce the probable merge conflicts of updating it among too many other node packages. I'm converting to draft as the current, newer build fails with:

```
npm ERR! syscall chmod
npm ERR! path /nix/store/2m8cziwx735scqdqs81081z4dwxyxzqi-node_balena-cli-12.14.18/lib/node_modules/balena-cli/bin/balena
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/nix/store/2m8cziwx735scqdqs81081z4dwxyxzqi-node_balena-cli-12.14.18/lib/node_modules/balena-cli/bin/balena'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-09-06T08_41_48_435Z-debug.log
```

**Comment by doronbehar** [comment]
Now it's working.

**Comment by Lassulus** [comment]
somethings odd here

**Comment by doronbehar** [comment]
DAMN, so many people got subscribed. Sorry. Now I used `cherry-pick` instead of `rebase` and I hope it's fine.

**Review by jonringer — COMMENTED** [review]
is there a way to just update the global node packages, instead of having a 12k application-specific deps file?

**Comment by doronbehar** [comment]
> is there a way to just update the global node packages, instead of having a 12k application-specific deps file?

484K* :laughing: :

```
$ du -csh pkgs/development/tools/balena-cli
484K
```

It is possible, but [their releases](https://github.com/balena-io/balena-cli/releases) are so frequent, so I'm not sure how to handle this - putting it in the general `nodePackages` set would mean the updates it'll receive will be very infrequent. OTH, I'm not installing this tool imperatively via `npm -g install` because it is compiled.

Maybe we should improve the nodePackages ecosystem so it wouldn't be that hard to get changes into Nixpkgs. IDK.

**Comment by jonringer** [comment]
I think in a year-or-two, we might just be using flakes for applications like this. So that nixpkgs is small and stable. And then just opt-in to flakes that have large dependency sets.

**Comment by doronbehar** [comment]
I'll close this as it seems not suitable for nixpkgs with their release model and our nodejs system. In the future this project will be available using the flake https://gitlab.com/doronbehar/nixNodeJSPkgs .

**Pull request closed without merging**
