### PR TITLE
caprine-bin: 2.55.5 -> 2.58.0

### PR DESCRIPTION
**Pull request by n3oney**
## Description of changes

Changelog: https://github.com/sindresorhus/caprine/compare/v2.55.5...v2.58.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@ShamrockLee

### CODE REVIEW

**Comment by ShamrockLee** [comment]
Tested execution on x86_64-linux (NixOS) and examined the .desktop file 
by eyeball. LGTM!

Thank you for bringing the update and fixing the window splitting! Let's 
backport it to the stable branch also to fix the `caprine-bin` there, 
once this package proves to work on both Linux and MacOS.

**Review by khaneliman — APPROVED** [review]
Tested on x86_64-linux, works and actually makes Caprine usable on my computer now.

**Review by ShamrockLee — APPROVED** [review]

**Comment by khaneliman** [comment]
@drupol This one is verified working and fixes some major issues in current release.

**Comment by khaneliman** [comment]
Gonna spin up my x86_64-darwin real quick, actually just to double check.

**Comment by n3oney** [comment]
No need to thank me, I just bumped a package 😅

**Comment by ShamrockLee** [comment]
@n3oney BTW, most people implement their changes on a separate branch other than `master` inside their fork. It makes things easier because:
1.  It makes multitasking easier. You could work on multiple changes with feature branches instead of the master branch.
2.  People may track the feature branch in order to use / test the package before the PR get merged. A feature branch makes it less ambiguous, and people get notified when the branch is deleted, while the master-branch-based workflow moves onto the next PR silently.

**Pull request merged**
