### PR TITLE
home-assistant: 2021.4.1 -> 2021.4.2

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/home-assistant/core/releases/tag/2021.4.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabaff — COMMENTED** [review]
So far from `nix-review`:

```bash
[...]
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
builder for '/nix/store/xjy0d2plc8m5kps6qc2kj9mgzclglkih-python3.8-pykodi-0.2.5.drv' failed with exit code 1; last 10 log lines:
  adding 'pykodi-0.2.5.dist-info/top_level.txt'
  adding 'pykodi-0.2.5.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Finished executing setuptoolsBuildPhase
  installing
  Executing pipInstallPhase
  /build/pykodi-0.2.5/dist /build/pykodi-0.2.5
  Processing ./pykodi-0.2.5-py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement jsonrpc-websocket>=3.0.0 (from pykodi)
  ERROR: No matching distribution found for jsonrpc-websocket>=3.0.0
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 118943` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.pykodi</li>
    <li>python39Packages.pykodi</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.zha-quirks</li>
    <li>python39Packages.zha-quirks</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118943` at 668c5889 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/c2b557e9e5409f4b7e963ea700b23647">python38Packages.pykodi</a></li>
    <li><a href="https://gist.github.com/4cab77564351566b1ba6222f8ed917a9">python39Packages.pykodi</a></li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.zha-quirks</li>
    <li>python39Packages.zha-quirks</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by mweinelt** [comment]
Yup, I apparently forgot to build `python3Packages.pykodi`. It had a rather long dependency chain that needed updates, so for good measure we now have kodi component tests.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 118943` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.jsonrpc-async</li>
    <li>python38Packages.jsonrpc-base</li>
    <li>python38Packages.jsonrpc-websocket</li>
    <li>python38Packages.pykodi</li>
    <li>python38Packages.zha-quirks</li>
    <li>python39Packages.jsonrpc-async</li>
    <li>python39Packages.jsonrpc-base</li>
    <li>python39Packages.jsonrpc-websocket</li>
    <li>python39Packages.pykodi</li>
    <li>python39Packages.zha-quirks</li>
  </ul>
</details>

**Pull request merged**
