### PR TITLE
Ipython updates

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Just a bunch of package updates I had lying around

### CODE REVIEW

**Comment by FRidh** [comment]
I don't think this will work because notebook 4.2 depends on `entrypoint`, which is the reason I went after flit/wheel installing :-)

**Comment by zimbatm** [comment]
The notebook was working for me when I ran it locally but let's get the other PR done first anyways.

**Comment by FRidh** [comment]
I checked again. It's the latest `nbconvert` that needs `entrypoint`: https://pypi.python.org/pypi/nbconvert/4.2.0

**Comment by FRidh** [comment]
pushed nbconvert in 3853d1e97fa1dde244d73cb5d6c48d110660412d

**Pull request merged**
