### PR TITLE
python310Packages.accelerate: 0.19.0 -> 0.21.0

### PR DESCRIPTION
**Pull request by natsukium**
Diff: https://github.com/huggingface/accelerate/compare/refs/tags/v0.19.0...v0.21.0

Changelog: https://github.com/huggingface/accelerate/releases/tag/v0.21.0

python311Packages.tensorflow can't be built now, and some downstream packages also fail to build.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
The change looks good, but if this break tensorflow, do we have to update it as well ?

**Comment by natsukium** [comment]
Maybe, no. See #244660

However, it seems to be incompatible with torch except for x86_64-linux.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 245802` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain.dist</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python310Packages.accelerate</li>
    <li>python310Packages.accelerate.dist</li>
    <li>python310Packages.k-diffusion</li>
    <li>python310Packages.k-diffusion.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
    <li>python310Packages.manifest-ml</li>
    <li>python310Packages.manifest-ml.dist</li>
    <li>python310Packages.peft</li>
    <li>python310Packages.peft.dist</li>
    <li>python311Packages.accelerate</li>
    <li>python311Packages.accelerate.dist</li>
    <li>python311Packages.manifest-ml</li>
    <li>python311Packages.manifest-ml.dist</li>
    <li>python311Packages.peft</li>
    <li>python311Packages.peft.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>

**Comment by happysalada** [comment]
@natsukium the PR you referenced has been approved, I think it's just a matter of time before it gets merged.
Should we merge this and make an update of langchain and k-diffusion in a separate PR ?

**Comment by natsukium** [comment]
I added a patch.
Since k-diffusion and langchain are unrelated to this update, it should be possible to merge it if ofborg passes.

**Comment by happysalada** [comment]
here is the failure on darwin
```
  >     return func(data, *args, **kwargs)
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > FAILED tests/test_state_checkpointing.py::CheckpointTest::test_can_resume_training - RuntimeError: torch_shm_manager at "/nix/store/8l1xa08wbcf7rlksk7c1xmwrqwxz...
       > FAILED tests/test_state_checkpointing.py::CheckpointTest::test_can_resume_training_with_folder - RuntimeError: torch_shm_manager at "/nix/store/8l1xa08wbcf7rlksk7c1xmwrqwxz...
       > FAILED tests/test_state_checkpointing.py::CheckpointTest::test_with_scheduler - RuntimeError: torch_shm_manager at "/nix/store/8l1xa08wbcf7rlksk7c1xmwrqwxz...
       > = 3 failed, 90 passed, 106 skipped, 10 deselected, 4 warnings in 70.98s (0:01:10) =
       > /nix/store/zrm711fiq97106vl9skqbm3wjd8zb7dr-stdenv-darwin/setup: line 1607: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/bf2q58j2d0xn1anq8pz4b4nb8by0qqi8-python3.10-accelerate-0.21.0.drv'.
```
(this is for x86_64 darwin, but I suspect it should be the same for aarch64.)
Should we just disable those tests for darwin ?

**Pull request merged**
