### PR TITLE
python3Packages.manga-ocr: init at 0.1.11

### LINKED ISSUE #233897: Package request: manga-ocr
**Project description**

It is a python library to help decode chinese/japanese characters.
It's used in 2 software I am interested in 
- https://github.com/ripose-jp/Memento/ (PR at https://github.com/NixOS/nixpkgs/pull/230786)
- https://github.com/blueaxis/Poricom a manga reader

There is a demo of its capabilities here https://kha-white.github.io/manga-demo/ and I think it's unique in terms of features and is useful for japanese learners.

Ideally we could convert the project to poetry to help with packaging beforehand

**Metadata**

* homepage URL: https://github.com/kha-white/manga-ocr
* source URL: https://github.com/kha-white/manga-ocr
* license: apache 2
* platforms: unix, linux, darwin, ...

### PR DESCRIPTION
**Pull request by Laurent2916**
###### Description of changes

https://github.com/kha-white/manga-ocr
cannot run tests as loading the ocr model requires internet to download weights from huggingface hub

Fixes #233897 
Requires #235798

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
hi, my approach was to convert the project to poetry first https://github.com/teto/manga-ocr/tree/poetry to make packaging easier with poetry2nix. I can enter the shell but now I have to provide cuda libraries and am short on time so can't test.

**Comment by Laurent2916** [comment]
Hi @teto !

Converting the project to poetry is a great idea, and I'd love to help.
I simply wanted to try and package the software "as is" :)

Also, did you try running the OCR on CPU ? I personally have my GPU disabled and it works just fine !

**Comment by Laurent2916** [comment]
Oh, I also check your fork but I couldn't see your modifications, did you commit them ?

**Comment by teto** [comment]
ha indeed seems like I forgot to push ^^' will do so later. I felt like I couldn't test the OCR without the cuda packages, have you done anything special to run OCR on CPU ?

**Comment by Laurent2916** [comment]
Nope, I didn't do anything special.
As my GPU is disabled, the program loads (and runs) the model on the CPU as per the following:
https://github.com/kha-white/manga-ocr/blob/ba1b0d94a8ef6676b618ba4e5ffe8ce2ab655270/manga_ocr/ocr.py#L18-L25

**Comment by Laurent2916** [comment]
I'm able to use the OCR using the following commands:
```bash
$ nix shell github:Laurent2916/nixpkgs/manga-ocr#python3Packages.manga-ocr nixpkgs#slurp nixpkgs#grim
$ mkdir /tmp/manga-ocr-images/
$ manga_ocr --read_from=/tmp/manga-ocr-images --force_cpu=True &
2023-08-18 20:25:28.047 | INFO     | manga_ocr.ocr:__init__:13 - Loading OCR model from kha-white/manga-ocr-base
/nix/store/vqwl9q29aq5wrhmbjj4aqkdi9245yn81-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/models/vit/feature_extraction_vit.py:28: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
2023-08-18 20:25:31.345 | INFO     | manga_ocr.ocr:__init__:22 - Using CPU
2023-08-18 20:25:31.790 | INFO     | manga_ocr.ocr:__init__:29 - OCR ready
2023-08-18 20:25:31.795 | INFO     | manga_ocr.run:run:108 - Reading from directory /tmp/manga-ocr-images

$ slurp -d | grim -g - /tmp/manga-ocr-images/screencap.png
2023-08-18  20:25:40.985 | INFO     | manga_ocr.run:process_and_write_results:30 - Text recognized in 0.420 s: おはようございます
```

Everything seems to be fine, are you able to run the OCR on CPU @teto ?

**Comment by teto** [comment]
@Laurent2916 sry for not answering. I have a bit of time to test if you could rebase ?

**Comment by Laurent2916** [comment]
(Ooops, closed the issue by pushing zero commits, my bad)
I rebase the branch + updated the version from v0.1.10 to v0.1.11

**Comment by teto** [comment]
sry for the wait. I copied to the clipboard the first example of https://github.com/kha-white/manga-ocr?tab=readme-ov-file#examples and rang
`manga_ocr -w toto.txt` and toto.txt contained the transcript. So fantastic. I am eager to test this in conjonction with memento/poricom

**Pull request merged**
