### PR TITLE
pythonPackages.pykeepass: 4.0.0 -> 4.0.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
This seems to break gnome-passwordsafe:
```
$ gnome-passwordsafe
Traceback (most recent call last):
  File "/nix/store/sdkbx46iiaqdhq42asbhd1rfcp5sbwfp-gnome-passwordsafe-5.0/bin/..gnome-passwordsafe-wrapped-wrapped", line 48, in <module>
    from passwordsafe.application import Application
  File "/nix/store/sdkbx46iiaqdhq42asbhd1rfcp5sbwfp-gnome-passwordsafe-5.0/lib/python3.8/site-packages/passwordsafe/application.py", line 12, in <module>
    from passwordsafe.main_window import MainWindow
  File "/nix/store/sdkbx46iiaqdhq42asbhd1rfcp5sbwfp-gnome-passwordsafe-5.0/lib/python3.8/site-packages/passwordsafe/main_window.py", line 12, in <module>
    from passwordsafe.create_database import CreateDatabase
  File "/nix/store/sdkbx46iiaqdhq42asbhd1rfcp5sbwfp-gnome-passwordsafe-5.0/lib/python3.8/site-packages/passwordsafe/create_database.py", line 8, in <module>
    from passwordsafe.unlock_database import KeyFileFilter, UnlockDatabase
  File "/nix/store/sdkbx46iiaqdhq42asbhd1rfcp5sbwfp-gnome-passwordsafe-5.0/lib/python3.8/site-packages/passwordsafe/unlock_database.py", line 13, in <module>
    from pykeepass.exceptions import (
  File "/nix/store/7sd2g5rzzjhxc029lyqa5igp7nbgkhh6-python3.9-pykeepass-4.0.1/lib/python3.9/site-packages/pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass, create_database
  File "/nix/store/7sd2g5rzzjhxc029lyqa5igp7nbgkhh6-python3.9-pykeepass-4.0.1/lib/python3.9/site-packages/pykeepass/pykeepass.py", line 16, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/nix/store/z5sfdahas777yzz7q3p1llzdsrr47q2g-python3.9-lxml-4.6.3/lib/python3.9/site-packages/lxml/__init__.py)
```

**Comment by dotlambda** [comment]
Never mind, the above was just an issue with `nix-shell` (because I used `nixpkgs-review`).

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124122` at 17baa1a9 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built successfully:</summary>
  <ul>
    <li>gnome-passwordsafe</li>
    <li>passExtensions.pass-import</li>
    <li>python38Packages.pykeepass</li>
    <li>python39Packages.pykeepass</li>
    <li>qutebrowser</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 124122` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>gnome-passwordsafe</li>
    <li>passExtensions.pass-import</li>
    <li>python38Packages.pykeepass</li>
    <li>python39Packages.pykeepass</li>
    <li>qutebrowser</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
