### PR TITLE
mpd on darwin

### PR DESCRIPTION
**Pull request by mk0x9**
[libjack2](https://hydra.nixos.org/job/nixpkgs/trunk/libjack2.x86_64-darwin) and [libpulseaudio](https://hydra.nixos.org/job/nixpkgs/trunk/libpulseaudio.x86_64-darwin) doesn't build on darwin at this moment.

Also there happens [something nasty](https://github.com/NixOS/nixpkgs/issues/8880#issuecomment-122641080) with exceptions and boost headers (mpd builds with exceptions disabled by default but somehow boost headers ignore that). So I've enabled exceptions back, anyway if something will be thrown process will abort.

### CODE REVIEW

**Comment by lethalman** [comment]
If they don't build temporarily, then set those pulseaudioSupport and jackSupport to false in your own system.

**Comment by mk0x9** [comment]
@lethalman pulseaudio and jack doesn't build not only on my system, but at hydra too. AFAIR pulseaudio doesn't work at darwin at all yet.

https://hydra.nixos.org/job/nixpkgs/trunk/libjack2.x86_64-darwin
https://hydra.nixos.org/job/nixpkgs/trunk/libpulseaudio.x86_64-darwin

**Comment by mk0x9** [comment]
And this doesn't break darwin experience, because mpd contains mature OS X sound system support.

Anyway, problems isn't in pulseaudio and jack, there is something wonky with boost and c++ exceptions. If only someone with darwin and c++ knowledge could look into it.

**Comment by gridaphobe** [comment]
Perhaps it would be better to add the flags to `all-packages.nix` instead, eg

```
mpd = callPackage ../servers/mpd {
     aacSupport    = config.mpd.aacSupport or true;
     clientSupport = config.mpd.clientSupport or false;
     ffmpegSupport = config.mpd.ffmpegSupport or true;
     opusSupport   = config.mpd.opusSupport or true;
     jackSupport = !stdenv.isDarwin;
     pulseaudioSupport = !stdenv.isDarwin;
};
```

**Comment by gridaphobe** [comment]
Also, according to https://github.com/jackaudio/jack2/issues/29, jack must be built with `xcodebuild` on osx, which we can't do at the moment. @copumpkin and @pikajude were looking into a replacement a long time ago but IIRC it turned out to be very difficult..

**Comment by zimbatm** [comment]
@mk0x9 can you move the flags in the function parameters instead ? Disabling jack and pulseaudio on OSX is fine.

**Comment by zimbatm** [comment]
It's better to have a working mpd than something perfect

**Pull request merged**
