### PR TITLE
hplip: 3.23.8 -> 3.24.4, fix dependencies

### PR DESCRIPTION
**Pull request by alois31**
## Description of changes

Release notes: https://sourceforge.net/p/hplip/news/2024/06/hplip-3244-release-notes/

Added support for following new devices:

-    HP OfficeJet 8120 All-in-One series
-    HP OfficeJet Pro 8120 All-in-One series
-    HP OfficeJet 8130 All-in-One series
-    HP OfficeJet Pro 8130 All-in-One series
-    HP OfficeJet Pro 9720 Series
-    HP OfficeJet Pro 9730 Series

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnAZoidberg** [comment]
Have you tried to run it?

**Comment by alois31** [comment]
I did not yet have anything to print again. The programs that are affected by the changed dependencies (using PyQt and dbus) launch now.

**Comment by alois31** [comment]
Just noticed I still had an old base branch with Python 3.11, and of course it still doesn't build against 3.12 (failed to eval before):

```
hplip> libtool: compile:  gcc "-DPACKAGE_NAME=\"HP Linux Imaging and Printing\"" -DPACKAGE_TARNAME=\"hplip\" -DPACKAGE_VERSION=\"3.24.4\" "-DPACKAGE_STRING=\"HP Linux Imaging and Printing 3.24.4\"" -DPACKAGE_BUGREPORT=\"3.24.4\" -DPACKAGE_URL=\"\" -DPACKAGE=\"hplip\" -DVERSION=\"3.24.4\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBDL=1 -DHAVE_PTHREAD_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_UINT32_T=1 -DHAVE_LIBHPIP=1 -DHAVE_LIBHPIP=1 -DDISABLE_IMAGEPROCESSOR=1 -DHAVE_LIBCRYPTO=1 -DHAVE_LIBNETSNMP=1 -DHAVE_NET_SNMP_NET_SNMP_CONFIG_H=1 -DHAVE_LIBAVAHI=1 -DHAVE_LIBAVAHI_CLIENT=1 -DHAVE_LIBAVAHI_COMMON=1 -DHAVE_AVAHI_CLIENT_CLIENT_H=1 -DHAVE_AVAHI_COMMON_MALLOC_H=1 -DHAVE_CUPS_CUPS_H=1 -DHAVE_LIBUSB_1_0_LIBUSB_H=1 -DHAVE_PYTHON3_12_PYTHON_H=1 -DHAVE_DBUS=1 -I. -Iip -Iio/hpmud -Iscan/sane -Iprnt/hpijs -Icommon/ -I -Iprotocol/discovery -I/nix/store/00a8vfaapyibrfs2ir8py4aj5b4n5vqa-libusb-1.0.27-dev/include/libusb-1.0 -DCONFDIR=\"/nix/store/1wh3p3chc6l1xmds0xpk83fmc9sw4pib-hplip-3.24.4/etc/hp\" -c io/mudext/hpmudext.c  -fPIC -DPIC -o .libs/hpmudext_la-hpmudext.o
hplip> io/mudext/hpmudext.c:28:10: fatal error: Python.h: No such file or directory
hplip>    28 | #include <Python.h>
hplip>       |          ^~~~~~~~~~
hplip> compilation terminated.
```

**Comment by alois31** [comment]
Pinned to 3.11 because actually fixing this right now seems to be a mess.

**Review by JohnAZoidberg — COMMENTED** [review]
> I did not yet have anything to print again. The programs that are affected by the changed dependencies (using PyQt and dbus) launch now.

Thanks!

Sounds like a simple change from the release notes.
So if the basics run, I think we should be good.
I tried to run some command as well (without a printer).

**Comment by SuperSandro2000** [comment]
Please rebase on master

**Review by arthsmn — APPROVED** [review]

**Pull request merged**
