### PR TITLE
Updates mono, fsharp and monodevelop

### PR DESCRIPTION
**Pull request by vbgl**
Removes monodoc, f-spot and gtk-sharp-1.
Adds gnome-sharp, a dependency of monodevelop.

I could build and run monodevelop. And with it build and run a C# hello world.

This probably needs more testing. Anyone interested ?

### CODE REVIEW

**Comment by devhell** [comment]
@vbgl I might, or might not be an idiot, but I'm unable to actually run a project within monodevelop. 

When running monodevelop a red circle appears on the top right of the status window that, when clicked on, says: "A platform service implementation has not been found." Pressing on the shiny Play Button results in the Error Console simply stating that "Build canceled". Expected behavior would be that a terminal opens where the program run (i.e., hello world with a Console.ReadLine(); to stop it from closing).

I'm not very good at debugging IDEs, so if there's anything I can help with let me know. I very much appreciate it that you have packaged mono/monodevelop for NixOS ;-)

**Comment by bluescreen303** [comment]
devhell <notifications@github.com> writes:

> @vbgl I might, or might not be an idiot, but I'm unable to actually run a project within monodevelop. 
>
> When running monodevelop a red circle appears on the top right of the
> status window that, when clicked on, says: "A platform service
> implementation has not been found." Pressing on the shiny Play Button
> results in the Error Console simply stating that "Build
> canceled".

I had the same issue after trying it out.
I installed mono, monodevelop and fsharp.

However, after checking preferences (in monodevelop) to see if it was
able to find mono (it was), clicking on play again did the trick for me.

No fsharp integration for monodevelop yet though :(

**Comment by devhell** [comment]
@bluescreen303 Thanks for the info. The output is now "Build successful" (after checking in the monodevelop preferences that mono is found). However, when starting monodevelop the error message persists, and pushing the Play button simply results in the project being built, but there is no output whatsoever (this is in debug mode, even with breakpoints set).

I tried the same code in monodevelop on Archlinux, and monodevelop behaves as expected. I'd be very grateful for any pointers, as I'm rather dependent on monodevelop to do work for my University. :(

**Comment by vbgl** [comment]
Thanks guys for testing. That’s true that monodevelop packaging is far from perfect. Unfortunately, I do not know what the errors messages mean and how to address these issues.

**Comment by thoughtpolice** [comment]
Does the `mono` update to `3.8.0` also update the needed copy of LLVM? It'll probably need to be updated; I'll snoop around for what the release version might be.

**Comment by devhell** [comment]
@vbgl The monodevelop version you packaged is a bit old AFAICT, so maybe it would help to update to the latest version? Just a thought...

**Pull request merged**
