### PR TITLE
python3: 3.6 -> 3.7

### PR DESCRIPTION
**Pull request by dirn**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pSub** [comment]
I changed the base to staging as this is a mass-rebuilt.

**Comment by dirn** [comment]
Thanks. Let me know if there are any additional changes that need to be made.

**Comment by dotlambda** [comment]
We'll still have to wait quite some time until upstream maintainers have made their packages Python 3.7-compatible.

**Comment by FRidh** [comment]
We won't make this change until 19.03 because there is not enough package compatibility yet.

Note I'm away on holidays and may be unresponsive. Tuesday I should be back.

**Comment by dotlambda** [comment]
I don'y have any numbers, but I tried compiling some stuff once and e.g. found an incompatibility in SQLAlchemy, whis is one of the bigger players: https://bitbucket.org/zzzeek/sqlalchemy/issues/4291/test-failures-with-python-37
PyYAML also comes to mind: https://github.com/yaml/pyyaml/issues/193.
I think there are many more examples, these are just two major ones I came across when testing packages I frequently use.

**Comment by orivej** [comment]
OK, so pyyaml breaks because it ships a `.c` file generated by an old Cython, and sqlalchemy tests break because Python 3.7 generates a deprecation warning for `inspect.formatargspec`. Such issues may affect just a few packages.

**Comment by dirn** [comment]
On the bright side PyYAML seems to be fixed. https://github.com/yaml/pyyaml/issues/193#issuecomment-402889151

**Pull request closed without merging**
