### PR TITLE
uhd: 3.10.2.0 -> 3.10.3.0

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
Version update. Includes fix to build against boost 1.66 (see https://github.com/NixOS/nixpkgs/issues/33549 and https://github.com/NixOS/nixpkgs/pull/33552)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lukeadams** [comment]
Looks good! Only thing is the `uhdImagesName` wasn't bumped:
```diff
From e42c827e2a7bb212ee0ac17e2d082734806a92f5 Mon Sep 17 00:00:00 2001
From: Luke Adams <luke.adams@belljar.io>
Date: Thu, 1 Feb 2018 11:52:16 -0600
Subject: [PATCH] bump uhd images version

---
 pkgs/development/tools/misc/uhd/default.nix | 11 ++++++-----
 1 file changed, 6 insertions(+), 5 deletions(-)

diff --git a/pkgs/development/tools/misc/uhd/default.nix b/pkgs/development/tools/misc/uhd/default.nix
index 8f7ef254cf8..25796561f71 100644
--- a/pkgs/development/tools/misc/uhd/default.nix
+++ b/pkgs/development/tools/misc/uhd/default.nix
@@ -17,7 +17,7 @@ stdenv.mkDerivation rec {
   src = fetchFromGitHub {
     owner = "EttusResearch";
     repo = "uhd";
-    rev = "release_003_010_003_000";
+    rev = "release_003_010_003_000"; # Also bump `uhdImagesName` below
     sha256 = "1aj8qizbyz4shwawj3qlhl6pyyda59hhgm9cwrj7s5kfdi4vdlc3";
   };
 
@@ -31,11 +31,12 @@ stdenv.mkDerivation rec {
   # Build only the host software
   preConfigure = "cd host";
 
-  # Firmware images are downloaded (pre-built)
-  uhdImagesName = "uhd-images_003.007.003-release";
+  # Firmware images are downloaded (pre-built) from:
+  # http://files.ettus.com/binaries/images/
+  uhdImagesName = "uhd-images_003.010.003.000-release";
   uhdImagesSrc = fetchurl {
-    url = "http://files.ettus.com/binaries/maint_images/archive/${uhdImagesName}.tar.gz";
-    sha256 = "1pv5c5902041494z0jfw623ca29pvylrw5klybbhklvn5wwlr6cv";
+    url = "http://files.ettus.com/binaries/images/${uhdImagesName}.tar.gz";
+    sha256 = "198awvw6zsh19ydgx5qry5yc6yahdval9wjrsqbyj51pnr6s5qvy";
   };
 
   postPhases = [ "installFirmware" ];
-- 
2.15.1
```


May be helpful to add the following to prevent this issue in the future:
```nix
let
  uhdVer = "003_010_003_000";
in
...
  src = fetchFromGitHub {
    rev = "release_${uhdVer}";
  ...
  uhdImagesName = "uhd-images_${lib.replaceStrings ["_"] ["."] uhdVer}-release";
```
Or wherabouts

**Comment by markuskowa** [comment]
Please correct me if I am overlooking something here but the firmware seems to have a release scheme?
In http://files.ettus.com/binaries/maint_images/archive/ uhd-images_003.007.003-release is the latest version. There is a newer one in http://files.ettus.com/binaries/maint_images/ (uhd-images_003.008.001-release.zip). Should we bump the firmware to 003.008.001 instead?

**Comment by markuskowa** [comment]
Thanks for the patch. The fw version and the host tools version are now locked to each other.

**Comment by lukeadams** [comment]
Awesome!

I got emailed about 9c6a17c5243d785c345a681ada4f0a4e9227953d since you referenced it in your issue. I need to test this weekend but pinning the boost version may cause gnuradio building to fail as it uses latest boost. If so this pr may want to revert that commit?

**Comment by markuskowa** [comment]
Hydra can build gnuradio again with pinning boost to 1.65 (https://hydra.nixos.org/build/68382505). I will rebase this PR and revert it back to default boost version (1.66), since nox-review could build it successfully.

CC @fpletz

**Pull request merged**
