### PR TITLE
ci/eval: Also count added packages as rebuilds

### PR DESCRIPTION
**Pull request by infinisil**
This is also what ofborg does, discovered by @FliegendeWurst after https://github.com/NixOS/nixpkgs/pull/359704

## Things done
- [x] Tested: https://github.com/tweag/nixpkgs/pull/106#event-15499084817

---

This work is funded by [Tweag](https://tweag.io) and [Antithesis](https://antithesis.com/) :sparkles:

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by philiptaron — APPROVED** [review]
Yep.

**Comment by philiptaron** [comment]
Silvan, are you collecting languages you've written load-bearing production code in? 😜

**Comment by infinisil** [comment]
Haha I guess so! I feel like `jq` hits a good spot where it's interpreted (so not needing compilation like nixpkgs-vet), not arcane (such as bash), and made for processing (unlike Nix). I'd be happy to merge a rewrite in Nix though, that's definitely more approachable :smile:

**Comment by paparodeo** [comment]
https://github.com/NixOS/nixpkgs/pull/362028

should have added a darwin rebuild but it did not.

**Comment by paparodeo** [comment]
> Haha I guess so! I feel like `jq` hits a good spot where it's interpreted (so not needing compilation like nixpkgs-vet), not arcane (such as bash), and made for processing (unlike Nix). I'd be happy to merge a rewrite in Nix though, that's definitely more approachable 😄

FWIW I did implement this in sql using duckdb (duckdb is handy to do sql things on csv and json files, among other things)
https://github.com/paparodeo/nixpkgs/blob/304c7f072a1de4f52d099e78808ae72c1327d3d0/ci/eval/compare.sql#L1
tho not sure if worth pursuing further as while easier for me to deal with not sure if it is for others.

**Comment by infinisil** [comment]
For future reference: https://github.com/NixOS/nixpkgs/pull/362844

**Pull request merged**
