### PR TITLE
Rust updates

### PR DESCRIPTION
**Pull request by retrry**
###### Motivation for this change
Updated rust, cargo and rustfmt to their latest versions. Marked exa and tokei as broken as updating isn't enough for them to compile. Pinging maintainers: @ehegnes for exa and @gebner for tokei.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]
I don't like that exa and tokei are broken, but having the newest rustc and cargo matters more to me, personally.

**Comment by rushmorem** [comment]
Builds fine. Thanks!

**Comment by gebner** [comment]
I have updated and fixed tokei, but I couldn't get exa to work, see #18002 and #18947.

**Comment by ehegnes** [comment]
@gebner I will try my hand at fixing the `exa` package today. This might require working with its developer. I'll update here with a progress report later.

**Pull request merged**
