### PR TITLE
gnum4: set platforms=all; it works on Windows

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

 it works on Windows

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build pkgs.pkgsCross.mingwW64.gnum4

**Comment by volth** [comment]
Just curious, what could be an example of a system which
 * runs Nix
 * is not Unix not Windows
 * cannot run M4

**Comment by Infinisil** [comment]
@matthewbauer Unless we know it doesn't work on certain other platforms, I think `all` is alright.

**Comment by volth** [comment]
And well, we do not have (yet) "x86_64-windows" among platforms.
only "x86_64-cygwin"
But ```pkgs.pkgsCross.mingwW64.gnum4``` is not cygwin

**Comment by matthewbauer** [comment]
That's alright with me, it's more of a nitpick than anything. I do think it can be useful to be specific here though. The only use case outside of "unix" and "windows" that we have right now is cross compiling to "embedded" systems like avr (avr-none) and arm-embedded (arm-none). gnum4 might work in those cases but it's untested.

**Comment by volth** [comment]
deprecating of ```platforms.all``` might have some sense.
At least grepping ```<nixpkgs>``` for "windows" or "avr" would reveal the already ported and checked packages.
There are some packages with ```platforms.all``` which fail on Windows (```gnused``` and ```gnused``` as examples)

**Comment by volth** [comment]
The only useful case for ```platforms.all``` would remain "pkgs/data/*"

**Comment by Infinisil** [comment]
Oh, I guess the commit message wasn't current anymore, that's alright

**Pull request merged**
