### PR TITLE
deepin.deepin-screenshot: remove (has been archived upstream)

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

It has been deprecated (migrated to `deepin-screen-recorder` after v20).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
`deepin-screen-recorder` isn't packaged, and when removing packages we usually provide a message in `aliases.nix`, pointing users to alternatives.

Simply removing it without anyone else reviewing this PR is probably not what should happen usually. I was quite confused seeing `deepin.deepin-screenshot` just disappeared, and even more when the suggested alternative isn't in nixpkgs.

Do you plan to introduce `deepin-screen-recorder` to nixpkgs, or what's the plan forward?

Also cc @worldofpeace for the deepin ecosystem.

**Comment by romildo** [comment]
> Do you plan to introduce `deepin-screen-recorder` to nixpkgs, or what's the plan forward?

Yes, `deepin-screen-recorder` introduction to nixpkgs is planned.

**Comment by asdf8dfafjk** [comment]
I haven't tried deepin-screen-recorder but I am going to assume its going to be much more heavy than deepin-screenshot. Unless screenshot was actually broken, I don't see why it was removed at all. 

Also, I (with my limited knowledge) fail to see an adversarial model where it would be considered "insecure" to use deepin-screenshot.

To top it all, it's probably always best to wait for a replacement and then delete, and at least please get a review.

**Comment by romildo** [comment]
I am sorry I have deleted it without a review :)

The situation now is that deepin is replacing its applications by new ones and the old ones are not being developed anymore.

Most of deepin packages in nixpkgs are more than one year old and they are getting **broken**. Fixing them would mean updating to the new versions. But the new versions released by upstream focus on new implmentations, using a new design and they are still buggy.

It seems that packaging deepin desktop and applications has become impracticable now, as discussed [here](https://github.com/NixOS/nixpkgs/issues/94870), and there is a [PR](https://github.com/NixOS/nixpkgs/pull/96610) to remove them.

**Comment by asdf8dfafjk** [comment]
Thank you for so much work you do on NixOS :-)

**Pull request merged**
