### PR TITLE
bkcrack: init at 1.5.0

### PR DESCRIPTION
**Pull request by erdnaxe**
###### Description of changes

bkcrack is useful in some Capture-the-Flag security challenges.

Might be linked with https://github.com/NixOS/nixpkgs/issues/81418.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasj19 — COMMENTED** [review]
Tested with nix-review. Builds and runs fine but I noticed this:
```
bkcrack --help
bkcrack 1.5.0 - 1980-01-01
```
Does upstream specifically set the date to 1980? or is this a build issue?

**Comment by erdnaxe** [comment]
> Does upstream specifically set the date to 1980? or is this a build issue?

Date is fixed to 1980-01-01 for reproducibility during build. Should I patch the code to remove the build date from the version string?

**Comment by dasj19** [comment]
oh ok. However I don't really know what advice to give you, I have not come across a similar issue during my time packaging. If it were for me to decide I would keep the upstream release date as the build time, but that might not be what nixpkgs people would want. Try asking on discourse, or wait for another reviewer to show.

**Review by urandom2 — APPROVED** [review]
nah, that fixed date string is really standard; I would have expected it to be 1970-01-01, but it is not worth fixing or patching.

**Pull request merged**
