### PR TITLE
lightningcss: 1.19.0 → 1.20.0

### PR DESCRIPTION
**Pull request by toastal**
Release notes lightningcss’s proprietary code forge: https://github.com/parcel-bundler/lightningcss/releases/tag/v1.20.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
Fails to build for me:
```
ightningcss> failures:
lightningcss> 
lightningcss> ---- bundler::tests::test_bundle stdout ----
lightningcss> thread 'bundler::tests::test_bundle' panicked at 'assertion failed: `(left == right)`
lightningcss>   left: `"@supports (foo: bar) or (color: red) {\n  .b {\n    color: green;\n  }\n}\n\n.a {\n  color: red;\n}\n"`,
lightningcss>  right: `"@supports (color: red) or (foo: bar) {\n  .b {\n    color: green;\n  }\n}\n\n.a {\n  color: red;\n}\n"`', src/bundler.rs:1101:5
lightningcss> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lightningcss> 
lightningcss> 
lightningcss> failures:
lightningcss>     bundler::tests::test_bundle
lightningcss> 
lightningcss> test result: FAILED. 98 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.14s
lightningcss> 
lightningcss> error: test failed, to rerun pass `--lib`
error: builder for '/nix/store/29phqhqhrsnxnapdd2xk30r2fgwq5gb8-lightningcss-1.20.0.drv' failed with exit code 101;
```
x86_64-linux
Is this test non-deterministic ?

**Comment by toastal** [comment]
> nondeterministic

Unsure. I had it build successfully on two AMD Zen3 x86_64 machines though.

**Comment by toastal** [comment]
Reverified on both of my machines rebasing with the default nixpkgs branch. Still no build or test issues.

**Comment by toastal** [comment]
@ofborg build lightningcss

**Comment by toastal** [comment]
@symphorien Can you try again? ofborg and myself have not had issues building for the last 2 months.

**Comment by symphorien** [comment]
It now builds for me. Certainly it's not deterministic.

**Pull request merged**
