### PR TITLE
botan2: 2.18.1 -> 2.19.2

### PR DESCRIPTION
**Pull request by mweinelt**
https://botan.randombit.net/news.html#version-2-19-2-not-yet-released

Don't let the release notes fool you, they clearly tagged 2.19.2 on 2022/06/03.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by viraptor** [comment]
Result of `nixpkgs-review pr 185999` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>biboumi</li>
    <li>keepassxc</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>botan2</li>
    <li>kea</li>
    <li>monotone</li>
    <li>rnp</li>
    <li>softhsm</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Rebased onto master, given the low rebuild count.

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 185999` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>biboumi</li>
    <li>botan2</li>
    <li>corectrl</li>
    <li>kea</li>
    <li>keepassxc</li>
    <li>monotone</li>
    <li>rnp</li>
    <li>softhsm</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
What about https://github.com/NixOS/nixpkgs/pull/179301??

**Pull request merged**
