### PR TITLE
ddclient: 3.8.3 -> 3.9.0

### LINKED ISSUE #26691: Cloudflare not supported by ddclient configuration
## Issue description

ddclient has support for Cloudflare but the current configuration in nixpkgs doesn't enable it. First, ddclient definition should add `perlPackages.JSONAny` to `buildInputs`. Second, Cloudflare uses `zone` argument and I'm wondering if that could be supported nicely in nixpkgs too.

#### Missing build inputs

Add this to `configuration.nix` and put some proper values to `domain`, `username` and `password`:
```
services.ddclient = {
  enable = true;
  domain = "mydomain.com";
  server = "www.cloudflare.com";
  username = "my@email.com";
  password = "myapikey";
  protocol = "cloudflare";
};
```

This will result in the following error for `ddclient.service`:
```
ddclient[4274]: FATAL:    Error loading the Perl module JSON::Any needed for cloudflare update.
```

This can be fixed by adding `perlPackages.JSONAny` to `buildInputs` of `ddclient`.

#### Missing zone in configuration

Now, one will get the following error:
```
ddclient[8074]: WARNING:  skipping host: mydomain.com: 'zone=' is an invalid fully qualified host name.
```

That is, one would need to add `zone=mydomain.com` in the ddclient configuration. This can be done with `extraConfig="zone=mydomain.com"`. However, each different high-level domain uses a different zone, so basically one will end up with using `extraConfig` for all zones and domains to get it working:
```
domain="";
extraConfig=''
zone=mydomain1.com
mydomain1.com
zone=mydomain2.com
mydomain2.com
```

I don't see any easy way to have "nicer" support for this in nixpkgs. If you have any ideas, please comment.

But at least the build inputs should be fixed, right?

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
# nixos-version
17.09.git.34e35df (Hummingbird)
```

* Nix version: (run `nix-env --version`)

```
# nix-env --version
nix-env (Nix) 1.11.9
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.09.git.34e35df896M"
```

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

```
# grep build-use-sandbox /etc/nix/nix.conf
build-use-sandbox = true
```

### PR DESCRIPTION
**Pull request by uvNikita**
###### Motivation for this change
This release fixes cloudflare protocol usage by switching to a new api
version. See release notes: https://sourceforge.net/p/ddclient/news/2018/08/ddclient-390-released.
Partially fixes #26691.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by uvNikita** [comment]
Yes, the old version was failing to update cloudflare without `JSONAny`. So I added build input as suggested in the linked issue, but then I got an error regarding usage of an old API. After upgrade, I tried to remove `JSONAny` and it worked without any issues. Here is the exact packageOverride I have in my configuration:
```
      nixpkgs.config.packageOverrides = super: let self = super.pkgs; in {
        ddclient = super.ddclient.overrideAttrs (
          oldAttrs: rec {
            name = "ddclient-${version}";
            version = "3.9.0";
            src = super.fetchurl {
              url = "mirror://sourceforge/ddclient/${name}.tar.gz";
              sha256 = "0fwyhab8yga2yi1kdfkbqxa83wxhwpagmj1w1mwkg2iffh1fjjlw";
            };
            patches = [];
            buildInputs = oldAttrs.buildInputs ++ (with super.perlPackages; [ DataValidateIP ]);
          }
        );
      };
```

**Comment by uvNikita** [comment]
@c0bw3b according to ddclient [changelog](https://github.com/ddclient/ddclient/blob/02c983a991531f5bb1637701b9d0c399094bba29/ChangeLog#L10), they are switch from JSON::Any to JSON:PP in the new release. This explains why it works without having JSONAny package in buildInputs.

**Comment by c0bw3b** [comment]
Ah! Nice catch. I guess we should add `JSONPP` to the build inputs list of Perl packages then?

**Comment by uvNikita** [comment]
For some reason, cloudflare updates work for me without this dependency, but since it's clearly listed in [README](https://github.com/ddclient/ddclient/blob/master/README.md) file, I added it to build inputs as well.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build ddclient

**Comment by benpye** [comment]
Would this be a candidate for a backport to 18.09?

**Pull request merged**
