### PR TITLE
keepass-keepassrpc: init at 1.7.3.1

### PR DESCRIPTION
**Pull request by svsdep**
###### Motivation for this change
Repackaged as the name was confusing and there is a dedicated repository
for this plugin, ready to use and with the fresh plugin version.
Left an alias to an old package name.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by svsdep** [comment]
@GrahamcOfBorg build keepass-keepassrpc

**Comment by grahamc** [comment]
@GrahamcOfBorg build keepass-keepassrpc

**Comment by svsdep** [comment]
Locked to `x86_64-linux` platform as it is linux-only and `mono` doesn't support `aarch64-linux` platform.

**Comment by svsdep** [comment]
Should I also add `assert stdenv.system == "x86_64-linux";` for build bots not to try to build it on unsupported platforms, or specifying correct `platforms` is enough?

**Comment by fpletz** [comment]
That's fine. Hydra won't try to build but @GrahamcOfBorg is not there yet. :)

**Pull request merged**
