### PR TITLE
beam/fetchMixDeps: disable --only flag when mixEnv is empty

### PR DESCRIPTION
**Pull request by superherointj**
beam/fetchMixDeps: disable --only flag when mixEnv is empty

* mixEnv being empty will include all dependencies.

* Brief documenting because it's useful for loading tests dependencies.
  * I'm a bit unsure about how to document this... Still thinking.
  * (Actually, tests should be documented in Elixir.)

### CODE REVIEW

**Review by bclaud — APPROVED** [review]
Tested here with one Phoenix app and worked as intended.

Previously, to be able to fetch all deps, I had to override the installPhase with the following code
```sh
    installPhase = ''
      runHook preInstall
      mix deps.get
      find "$TEMPDIR/deps" -path '*/.git/*' -a ! -name HEAD -exec rm -rf {} +
      cp -r --no-preserve=mode,ownership,timestamps $TEMPDIR/deps $out
      runHook postInstall
      ''; 
```

Thank you very much!

**Comment by happysalada** [comment]
Thank you !

**Comment by superherointj** [comment]
@happysalada Hi.

I'm sorry to inform you there is an issue in this patch I proposed.

As it is, when `fetchMixDeps` is executed without `mixEnv` argument. In installPhase, env vars are as:
> MIX_ENV => prod
> mixEnv => 
Which causes default behavior to include all dependencies and not just `prod`.
Still knowing this, I couldn't properly figure out why this is going on, because:
* `attrs` (which included mixEnv) is merged to attrs. I suppose, mixEnv should be there and with `prod` value. Odd isn't it? I'm missing something.

I'm not proposing a solution yet. Just letting you about this.

**Comment by happysalada** [comment]
Good catch !

**Pull request merged**
