### PR TITLE
antlr4_x.runtime.cpp: fix build error due to sourceRoot missing source prefix

### LINKED ISSUE #197985: antlr-runtime-cpp build issue affecting nixos rebuild
### Steps To Reproduce

1. build *antlr-runtime-cpp-4.9.3*

which is part of the following dependency tree:

```
error: 1 dependencies of derivation '/nix/store/mfnq7cznmx3fvm80kgp7w8xdh88sf2yw-python3.10-afdko-3.9.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6l5gap4df3q3j28xbbf4by6vm958c7qg-python3.10-nototools-0.2.17.drv' failed to build
error: 2 dependencies of derivation '/nix/store/cd42pjz1vhviwr35n72h1v8rhsb96yns-python3-3.10.7-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pqn7g4509lk83rq0506n817r9ml5djgh-noto-fonts-emoji-2.038.drv' failed to build
error: 1 dependencies of derivation '/nix/store/97pf9f4zjxa46qaazvsd8fwdip4y32ip-fc-cache.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gdwfanr8gcqijkya8ix9xfdhzfhlhswg-xserver.conf.drv' failed to build
error: 2 dependencies of derivation '/nix/store/2kjldlxvxq1lba3y1s1jz5hrcsvsvglh-fc-00-nixos-cache.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lhzjj5s6cwalrlwxscyqp9mb9bxgwj5k-unit-display-manager.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1mg8jnri4ad67q18c2qrxg3pgbpz6w0d-fontconfig-conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y6q37nlpnybm84ck2b642j8a41jlgjwv-fontconfig-etc.drv' failed to build
error: 2 dependencies of derivation '/nix/store/3y0kc6wqgcddfcxv4yfkn56fad71bbsl-abstractions-fonts.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d0afah2klcgfxxfc1m81bzi9j8k8dpda-apparmor.d.drv' failed to build
```
 

### Build log

```
building '/nix/store/rkzbl90775l062v6bhn9va8b3siwqdkv-antlr-runtime-cpp-4.9.3.drv'...
unpacking sources
unpacking source archive /nix/store/mkmp5f1hh81m4gpfi3gw6sjjk204yqlw-source
source root is runtime/Cpp
chmod: cannot access 'runtime/Cpp': No such file or directory
error: builder for '/nix/store/rkzbl90775l062v6bhn9va8b3siwqdkv-antlr-runtime-cpp-4.9.3.drv' failed with exit code 1

```

### Additional context

Reverting 83b0d09f1c0988883af87a3e469c51d1a6c12444 fixes the build issue

### Notify maintainers

@workflow / @Technius 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.5, NixOS, 22.11 (Raccoon), 22.11.git.9fcfa4400aa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos, nixos-small"`
 - channels(fabian): `"home-manager, nixos-19.03-19.03, nixos-19.09-19.09, nixos-20.03-20.03, nixos-20.09-20.09, nixos-21.05-21.05, nixos-21.11-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by LunNova**
Fixes #197985

Patch from @NickCao https://github.com/NixOS/nixpkgs/issues/197985#issuecomment-1292843789

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Does this also affect the other versions? Didn't have time to check.

**Comment by LunNova** [comment]
Running a review run now to check it's good for all of them

**Comment by LunNova** [comment]
Result of `nixpkgs-review pr 198002` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>deltachat-desktop</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>luaformatter</li>
    <li>noto-fonts-emoji</li>
    <li>python310Packages.afdko</li>
    <li>python310Packages.nototools</li>
    <li>python39Packages.afdko</li>
    <li>python39Packages.nototools</li>
    <li>twitter-color-emoji</li>
  </ul>
</details>

**Comment by LunNova** [comment]
nixpkgs-review doesn't pick up all the 4.x runtime versions so tested manually with `nix shell .#antlr4_8.runtime.cpp .#antlr4_9.runtime.cpp .#antlr4_10.runtime.cpp .#antlr4_11.runtime.cpp` and they all build.

Added a missing alias for antlr4_10 in all-packages so could actually test it.

**Review by NickCao — APPROVED** [review]

**Review by fabianhjr — APPROVED** [review]
Tested and works! TY for making the merge request

**Comment by winterqt** [comment]
Can you please specify in the commit message that the source root fix only affects the runtime, and not the main antlr packages themselves?

(Unless you think the commit message is fine as-is, in which case, we can leave it. I figured I'd bring it up, though.)

LGTM otherwise, though.

~~Also: ideally we'd have some convention for `antlr-4.x`-like specifiers in commit messages (since we use underscores for these usually), but since we don't, I suppose it's good enough in terms of clarity.~~

**Comment by LunNova** [comment]
Reworded first commit @winterqt

**Review by winterqt — APPROVED** [review]
Much better, thanks.

Waiting on OfBorg.

**Comment by winterqt** [comment]
@ofborg build antlr4.runtime.cpp

**Pull request merged**
