### PR TITLE
python3Packages.pillow: 9.3.0 -> 9.4.0

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/python-pillow/Pillow/releases/tag/9.4.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build python3Packages.pillow

**Comment by mweinelt** [comment]
Fails on aarch64-darwin due to gfortran, that's not new though.

**Comment by wegank** [comment]
Looks good on aarch64-darwin on master:

```
$ nix-build -A python3Packages.pillow
/nix/store/a1p11w4pzrk6hly5ynp47dwlaw18f0m6-python3.10-pillow-9.4.0
```

**Comment by charmoniumQ** [comment]
I'm not sure where to document this. It's not a bug (existing pillow will work fine), just note for next time.

Our approach of patching `setup.py` won't work for Pillow>=9.5.0.

In [this commit](https://github.com/python-pillow/Pillow/commit/04cf5e2cfc5dc1676efd9f5c8d605ddfccb0f9ee), they interpret the value of `lib_root` and `include_root` as a _list_ of directories, not just a directory. The patch we have here fails silently, because strings are iterable, so it passes each letter on to `_add_directory(library_dirs, "a")`, which silently rejects paths that don't exist. The symptom is that Pillow can't find zlib.

`poetry2nix` reuses the Nixpkgs `preConfigure` on 9.5.0 source; that's how I experienced this error.

The solution is to change
```
-    libinclude = pkg: ''"${pkg.out}/lib", "${pkg.dev}/include"'';
+    libinclude = pkg: ''(["${pkg.out}/lib"], ["${pkg.dev}/include"])'';
```
but there is a less hacky solution than patching the source (imo). `setup.py` dutifully respects environment variables `C_INCLUDE_PATH` and `LIBRARY_PATH`, so we could populate those with colon-separated /nix/store/paths.

[pinging maintainers (y'all might find this useful)]: @goibhniu @prikhi @SuperSandro2000

**Pull request merged**
