### PR TITLE
waveterm: init v0.7.6

### PR DESCRIPTION
**Pull request by Marin-Kitagawa**
## Description of changes

This commit adds a new package: Waveterm with version 0.7.6. This also addresses the issue (package request) #280566 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Where's the commit initing you as maintainer?

**Comment by Marin-Kitagawa** [comment]
@JohnRTitor It's the very first one

**Comment by JohnRTitor** [comment]
You need to actually modify https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix

See https://github.com/NixOS/nixpkgs/commit/76a55aafc1bf1b1cce70749a99ac173ae745ffd4 as an example commit

**Comment by ElrohirGT** [comment]
Thank you @Marin-Kitagawa ! You beat me to it 🥇 .

I tried cloning your repo and testing the package on my Mac with:
```
nix-build -A waveterm
```

But it couldn't found waveterm... How would I go about testing if this derivation works?

**Comment by Marin-Kitagawa** [comment]
From within the repo
```sh
cd ./pkgs/applications/terminal-emulators/waveterm
nix-build default.nix
```

or

```sh
cd ./pkgs/applications/terminal-emulators/waveterm
nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
```

**Comment by ElrohirGT** [comment]
Tried on my M1 Mac and it fails... Here's the complete log:
```
this derivation will be built:
  /nix/store/8hbgzijgag9yws96hign55h59qgynl6l-waveterm-0.7.6.drv
building '/nix/store/8hbgzijgag9yws96hign55h59qgynl6l-waveterm-0.7.6.drv'...
Running phase: unpackPhase

7-Zip (z) 23.01 (arm64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
 64-bit arm_v:8 locale=en_US.UTF-8 Threads:8 OPEN_MAX:1048576, ASM

Scanning the drive for archives:
1 file, 235140532 bytes (225 MiB)

Extracting archive: /nix/store/kvsb4dri9x3b8vrmrkd680nzgbm0ma8i-Wave-darwin-universal-0.7.6.dmg
         
4.apfs
WARNINGS:
There are data after the end of archive

--
Path = /nix/store/kvsb4dri9x3b8vrmrkd680nzgbm0ma8i-Wave-darwin-universal-0.7.6.dmg
Type = Dmg
Physical Size = 235140532
Method = Copy Zero2 ZLIB CRC
Blocks = 649
----
Path = 4.apfs
Size = 815717376
Packed Size = 235093621
Comment = disk image (Apple_APFS : 4)
Method = Copy Zero2 ZLIB CRC
--
Path = 4.apfs
Type = APFS
WARNINGS:
There are data after the end of archive
Physical Size = 815714304
Tail Size = 3072
Name = Wave 0.7.6-universal.apfs
ID = 9755c9ad66a643fba6ac7e965d8ac7b5
Cluster Size = 4096
Created = 2024-06-15 00:31:58.750708096
Modified = 2024-06-15 00:32:05.018548805
Comment = 
{
block_size: 4096
fs_index: 0
volume_name: Wave 0.7.6-universal
vol_uuid: 7df71ec31cc34922b74b896cd720229e
incompatible_features: CASE_INSENSITIVE
fs_alloc_count: 159677
num_files: 117
num_directories: 159
num_symlinks: 15
num_other_fsobjects: 0
Num_Attr_Streams: 331
num_snapshots: 0
total_blocks_alloced: 162313
total_blocks_freed: 2688
unmounted: 2024-06-15 00:32:05.018549680
last_modified: 2024-06-15 00:32:05.016064388
formatted_by: newfs_apfs (2236.120.10.0.1)
  timestamp: 2024-06-15 00:31:58.750708096
  last_xid: 2
modified_by[0]: apfs_kext (2236.120.10.0.1)
  timestamp: 2024-06-15 00:32:05.018548805
  last_xid: 9

}

Everything is Ok                                                            

Archives with Warnings: 1

Warnings: 1
Folders: 159
Files: 117
Alternate Streams: 331
Alternate Streams Size: 676552
Size:       652740992
Compressed: 235140532
chmod: cannot access 'Waveterm.app': No such file or directory
error: builder for '/nix/store/8hbgzijgag9yws96hign55h59qgynl6l-waveterm-0.7.6.drv' failed with exit code 1;
       last 10 log lines:
       > Archives with Warnings: 1
       >
       > Warnings: 1
       > Folders: 159
       > Files: 117
       > Alternate Streams: 331
       > Alternate Streams Size: 676552
       > Size:       652740992
       > Compressed: 235140532
       > chmod: cannot access 'Waveterm.app': No such file or directory
       For full logs, run 'nix log /nix/store/8hbgzijgag9yws96hign55h59qgynl6l-waveterm-0.7.6.drv'.
```

**Comment by ElrohirGT** [comment]
I found the problem! Turns out you need to change the `sourceRoot` attribute to `Wave.app`. Now it unpacks and installs correctly. The only problem I have now is that when I try to run the program from `result/Applications` it says it's corrupted...
image


This happened to me before when I tried packaging Wave. I couldn't find other way that worked excepto for making the derivation `impure` and unpacking it like this: 
```
unpackPhase = ''
          runHook preUnpack

          # Since the .dmg is using APFS we can't use undmg.
          # I also tried to use _7zz but it corrupts the .app.
          /usr/bin/hdiutil attach $src
          cp -r "/Volumes/Wave ${version}-universal/Wave.app" .
          /usr/bin/hdiutil detach "/Volumes/Wave ${version}-universal"

          runHook postUnpack
        '';
```

After this changes I can successfully run the app from finder in the `result/Applications` folder after building the derivation.

**Comment by JohnRTitor** [comment]
Is `hdiutil` available on nixpkgs? CC @DontEatOreo if there are any other solution

**Comment by DontEatOreo** [comment]
> Is `hdiutil` available on nixpkgs?

Sadly no...

I'm not sure how this should be fixed. A workaround is to right-click and click open; then you will be allowed to actually open the program

image

*(macOS moment...)*

**Comment by DontEatOreo** [comment]
I saw the project is open source and it's written in Go, shouldn't we at least try to build it from source for Linux?

**Comment by ElrohirGT** [comment]
> I saw the project is open source and it's written in Go, shouldn't we at least try to build it from source for Linux?

[I was doing just that](https://github.com/ElrohirGT/nixpkgs/tree/feat/Add-waveterm-to-nix) but Marin beat me to the PR! My current progress is this, the linux config is [obtained from this thread](https://github.com/NixOS/nixpkgs/issues/280566#issuecomment-2054207556) I just merged it with the MacOS that worked for me.

(package.nix)
```nix
{
  lib,
  fetchurl,
  stdenvNoCC,
  fetchYarnDeps,
  mkYarnPackage,
  makeWrapper,
  copyDesktopItems,
  fetchFromGitHub,
  buildGoModule,
  breakpointHook,
  electron-bin,
  makeDesktopItem,
}: let
  pname = "waveterm";
  info = lib.importJSON ./info.json;
  genMeta = tag-version: {
    changelog = "https://github.com/wavetermdev/waveterm/releases/tag/v${tag-version}";
    description = "An Open-Source, AI-Native, Terminal Built for Seamless Workflows";
    homepage = "https://github.com/wavetermdev/wavetermn";
    license = lib.licenses.asl20;
    mainProgram = pname;
    platforms = lib.platforms.unix;
  };

  darwin = let
    version = info.darwin.version;
  in
    stdenvNoCC.mkDerivation (
      finalAttrs: {
        inherit pname version;
        meta = genMeta version;

        src = fetchurl {
          inherit (info.darwin) hash;
          url = "https://dl.waveterm.dev/releases/Wave-darwin-universal-${version}.dmg";
        };

        sourceRoot = ".";

        unpackPhase = ''
          runHook preUnpack

          # Since the .dmg is using APFS we can't use undmg.
          # I also tried to use _7zz but it corrupts the .app.
          /usr/bin/hdiutil attach $src
          cp -r "/Volumes/Wave ${version}-universal/Wave.app" .
          /usr/bin/hdiutil detach "/Volumes/Wave ${version}-universal"

          runHook postUnpack
        '';

        installPhase = ''
          runHook preInstall

          mkdir -p $out/Applications
          cp -r *.app $out/Applications
          chmod +x $out/Applications/*.app

          runHook postInstall
        '';
      }
    );

  linux = let
    version = info.linux.version;
    src = fetchFromGitHub {
      owner = "wavetermdev";
      repo = pname;
      rev = "v${version}";
      sha256 = info.linux.hash;
    };
    wavesrv = buildGoModule {
      inherit version src;
      preBuild = ''
        # go: 'go mod vendor' cannot be run in workspace mode. Run 'go work vendor' to vendor the workspace or set 'GOWORK=off' to exit workspace mode.
        # https://github.com/NixOS/nixpkgs/issues/203039
        export GOWORK="off";
      '';
      pname = "${pname}-wavesrv";
      modRoot = "./wavesrv";
      vendorHash = "";
      doCheck = false; # Currently fails at comp_test.go:91: comp-fail: ls f[*] + [foo bar] => [ls foo\ bar [*]] expected[ls 'foo bar' [*]]
    };
    waveshell = buildGoModule {
      inherit version src;
      preBuild = ''
        # go: 'go mod vendor' cannot be run in workspace mode. Run 'go work vendor' to vendor the workspace or set 'GOWORK=off' to exit workspace mode.
        # https://github.com/NixOS/nixpkgs/issues/203039
        export GOWORK="off";
      '';
      pname = "${pname}-waveshell";
      modRoot = "./waveshell";
      vendorHash = "";
    };
    electron = electron-bin;
  in
    mkYarnPackage rec {
      inherit pname src version;
      meta = genMeta version;

      packageJSON = "${src}/package.json";

      env.ELECTRON_SKIP_BINARY_DOWNLOAD = "1";

      offlineCache = fetchYarnDeps {
        yarnLock = "${src}/yarn.lock";
        hash = "";
      };

      nativeBuildInputs = [
        makeWrapper
        copyDesktopItems
        breakpointHook
      ];

      buildPhase = ''
        runHook preBuild

        pushd deps/${pname}
        node_modules/.bin/webpack --env prod
        popd

        runHook postBuild
      '';

      postBuild = ''
        pushd deps/${pname}

        mkdir ./bin
        cp ${wavesrv}/bin/cmd ./bin/wavesrv.amd64
        mkdir ./bin/mshell
        cp ${waveshell}/bin/waveshell ./bin/mshell/mshell-v0.6-linux.amd64

        yarn --offline run electron-builder \
          --dir \
          -l \
          -p never \
          -c electron-builder.config.js \
          -c.electronDist=${electron}/libexec/electron \
          -c.electronVersion=${electron.version}

        popd
      '';

      installPhase = ''
        runHook preInstall

        # resources
        mkdir -p "$out/share/lib/${pname}"
        cp -r ./deps/${pname}/make/*-unpacked/{locales,resources{,.pak}} "$out/share/lib/${pname}"

        # icons
        #install -Dm644 ./deps/${pname}/static/Icon.png $out/share/icons/hicolor/1024x1024/apps/${pname}.png

        # executable wrapper
        makeWrapper '${electron}/bin/electron' "$out/bin/${pname}" \
          --add-flags "$out/share/lib/${pname}/resources/app.asar" \
          --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \
          --inherit-argv0

        runHook postInstall
      '';
      # Do not attempt generating a tarball for contents again.
      # note: `doDist = false;` does not work.
      distPhase = "true";

      desktopItems = [
        (makeDesktopItem {
          name = pname;
          exec = pname;
          icon = pname;
          desktopName = "Wave Terminal";
          genericName = "waveterm";
          comment = meta.description;
          categories = ["System"];
          startupWMClass = pname;
        })
      ];
    };
in
  if stdenvNoCC.isDarwin
  then darwin
  else linux
```

(info.json)
```
{
  "linux": {
    "hash": "sha256-cHjBH6oijoAhdk2Ty1sl2GFXUUhfoToTuDUl5VuwKWU=",
    "version": "0.7.6"
  },
  "darwin": {
    "hash": "sha256-b75eQnUteQ767+crVe+gWfBf7PrrEjoNFVTx8s/jTXM=",
    "version": "0.7.6"
  }
}
```

I don't have a linux! So I can't really test it out, but accroding to the [original author it works](https://github.com/NixOS/nixpkgs/issues/280566#issuecomment-2054207556), just needs to setup the hashes!

**Comment by JohnRTitor** [comment]
That's, if you can conquer scripthaus

**Comment by ElrohirGT** [comment]
> I'm not sure how this should be fixed. A workaround is to right-click and click open; then you will be allowed to actually open the program

Can confirm, this opens the application successfully!

**Comment by ElrohirGT** [comment]
> That's, if you can conquer scripthaus

hahahaha I tried, but in the end followed the same route ErngWong took, translating the commands in scripthaus to  the native nix building blocks .

**Comment by DontEatOreo** [comment]
Can't we just do `if stdenvNoCC.isDarwin then info.darwin.version else info.linux.version` for `meta`? So it becomes

```nix
meta = {
  changelog = "https://github.com/wavetermdev/waveterm/releases/tag/v${
    if stdenvNoCC.isDarwin then info.darwin.version else info.linux.version
  }";
  description = "An Open-Source, AI-Native, Terminal Built for Seamless Workflows";
  homepage = "https://github.com/wavetermdev/wavetermn";
  license = lib.licenses.asl20;
  mainProgram = pname;
  platforms = lib.platforms.unix;
};
```

**Comment by ElrohirGT** [comment]
> Can't we just do `if stdenvNoCC.isDarwin then info.darwin.version else info.linux.version` for `meta`? So it becomes

I'm on board with this change, don't really have any complaints about it.

**Comment by S1M1S** [comment]
Seems like the failing check is because

**Comment by Th1nkK1D** [comment]
Look like v0.8 just got released https://waveterm.hashnode.dev/introducing-the-new-wave-terminal-v08

**Pull request closed without merging**
