### PR TITLE
nixos/ipfs: improve how the commandline flags are generated

### PR DESCRIPTION
**Pull request by Luflosi**
###### Description of changes
Use `concatStringsSep " "` instead of relying on the exact way in which `toString` formats a list, similar to what was suggested and then implemented in https://github.com/NixOS/nixpkgs/pull/156706#discussion_r795867283.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pennae** [comment]
since the args end up in a systemd Exec directive and contain user-specified strings we'd suggest dropping the concatenation and running the list through [`utils.escapeSystemdExecArgs`](https://github.com/NixOS/nixpkgs/blob/cb79bef94ebe76ef1d97db6f98fa4b998c7758f2/nixos/lib/utils.nix#L66) where it's used in the unit instead. not sure whether that can break existing configs that rely on systemd interpolations though. :slightly_frowning_face:

**Comment by Luflosi** [comment]
Thanks for the suggestion, I didn't know about `utils.escapeSystemdExecArgs`. Strangely, the only place, where it appears in Nixpkgs is in some documentation, the definition itself and in a test. IPFS is the first actual NixOS module to use this function.

**Comment by pennae** [comment]
yeah, we added it only recently. haven't gotten around to properly auditing modules for it yet.

**Comment by Luflosi** [comment]
When you do get around to it, I suggest changing the i2pd module first as it will be one of the easiest.

**Comment by pennae** [comment]
upon looking at the file history some more it seems that this *hasn't* been done in shell before. would still say escaping is, in general, a good idea, but it might also break existing configurations that rely on systemd interpolating extraFlags in the service ExecStart. :slightly_frowning_face: no idea how likely that is in practice, but is should probably be mentioned in the changelog anyway.

**Comment by Luflosi** [comment]
Is this a good changelog entry?

**Comment by pennae** [comment]
yeah, that sounds good.

**Comment by Luflosi** [comment]
Thanks!

**Pull request merged**
