### PR TITLE
buildbot: 1.4.0 -> 1.8.1

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Update all of buildbot to 1.8.0 (the master package had previously been updated to 1.5.0), and make it build again.

###### Things done

~~I also disabled buildbot's tests due to some failures. These failures were not caused by the upgrade to 1.7.0, but already occurred with 1.4.0. They are likely due to an upgrade of a dependency. I tried to bisect, but buildbot was previously broken because some of its dependencies failed to build, so I could not figure out when the tests started to fail.~~

I ran the NixOS tests and they passed.
 

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
cc @nand0p @ryansydnor

**Comment by lopsided98** [comment]
1.7.0 has been released, so this PR now updates buildbot to this version.

**Comment by lopsided98** [comment]
1.8.0 has been released, so this PR now updates buildbot to this version.

A change to SQLite broke sqlalchemy-migrate, which was causing the tests to fail. This PR includes an update of sqlalchemy-migrate to 0.12.0 which fixes the issue. Therefore buildbot's tests have been re-enabled.

**Comment by veprbl** [comment]
@GrahamcOfBorg build python2Packages.buildbot python2Packages.buildbot-full
@GrahamcOfBorg build python3Packages.buildbot python3Packages.buildbot-full
@GrahamcOfBorg test buildbot

**Comment by veprbl** [comment]
@lopsided98 Can you please update this to at least 1.8.1. That would fix https://github.com/buildbot/buildbot/wiki/CRLF-injection-in-Buildbot-login-and-logout-redirect-code then

**Comment by veprbl** [comment]
@lopsided98 Yes, I had the same idea.

@GrahamcOfBorg build python2Packages.buildbot python2Packages.buildbot-full
@GrahamcOfBorg build python3Packages.buildbot python3Packages.buildbot-full
@GrahamcOfBorg test buildbot

**Review by veprbl — APPROVED** [review]
Thank you!

**Pull request merged**
