### PR TITLE
libtensorflow: 1.9 -> 1.14.0

### PR DESCRIPTION
**Pull request by yorickvP**
This also changes it to a from-source build.

###### Motivation for this change

Update, also convert to built-from-source package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

This still needs testing everywhere. The linux build without cuda compiled one time. I can't test on darwin.

---
cc: @basvandijk

### CODE REVIEW

**Comment by basvandijk** [comment]
@GrahamcOfBorg build libtensorflow

**Comment by FRidh** [comment]
Should close https://github.com/NixOS/nixpkgs/pull/47025 when this is merged.

**Comment by yorickvP** [comment]
I'm working on the haskell package: https://github.com/tensorflow/haskell/pull/244

**Review by Profpatsch — CHANGES_REQUESTED** [review]
I’m not extremely excited about having to maintain multiple versions of bazel.

Can you please put the renaming file action into a separate commit, so that I can see the differences in `generic.nix`?

**Comment by yorickvP** [comment]
I've updated to 1.14.0-rc1, which does compile with bazel 0.26.1. Not ideal but probably better than including another bazel version.

**Comment by yorickvP** [comment]
I'm working on cuda support now.

**Review by Profpatsch — APPROVED** [review]

**Comment by yorickvP** [comment]
Cuda support compiles now.

**Comment by Profpatsch** [comment]
cc @basvandijk

**Comment by timokau** [comment]
I wish I had seen this before starting to work on https://github.com/NixOS/nixpkgs/pull/63616! Lots of good work here. We should merge the libtensorflow derivation with the tensorflow wheel build. Probably best to build both at the same time and then split it, to save build time.

**Comment by yorickvP** [comment]
I updated this to 1.14.0 final. @timokau that seems to have some good changes. Using system libraries might help a lot with our dynamic linking problems! Any ideas about how to do the multiple build outputs if this is built for multiple python versions?

**Comment by timokau** [comment]
Its probably not easy, maybe not even desirable to do this with multiple outputs. It would be possible to build multiple different bazel targets and put them in different outputs. That would add some complexity however and would always force everyone who wants to build one to build all of them.

**Comment by yorickvP** [comment]
Superseded by #64716

**Pull request closed without merging**
