### PR TITLE
rofi-games: init at 1.10.2

### LINKED ISSUE #301374: Package request: Rofi-games
**Project description**
A rofi plugin which adds a mode that will list available games for launch along with their box art. Requires a good theme for the best results. 

**Metadata**

* homepage URL: https://github.com/Rolv-Apneseth/rofi-games
* source URL: https://github.com/Rolv-Apneseth/rofi-games
* license: gpl2.0
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

Closes: https://github.com/NixOS/nixpkgs/issues/301374
Related: https://github.com/Rolv-Apneseth/rofi-games/issues/19

This PR adds 1 package: `rofi-games`
- the package builds a rofi plugin: (the .so file)
- and it also includes the recommended rofi themes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by aikooo7** [comment]
Result of `nixpkgs-review pr 301397` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rofi-games</li>
  </ul>
</details>

**Review by lolbinarycat — APPROVED** [review]

**Review by aikooo7 — APPROVED** [review]

**Comment by wineee** [comment]
Can we use 'just' to install ?  there are some '/usr' path need patch
https://github.com/Rolv-Apneseth/rofi-games/blob/e4dca5222133c7c8956c42cc58b6dd27d5e8656c/justfile#L17

**Comment by TomaSajt** [comment]
Nixpkgs has a custom way of installing rofi plugins:

if you don't have `home-manager`, then you can change
```nix
environment.systemPackages = [
  ...
  pkgs.rofi
];
```
to
```nix
environment.systemPackages = [
  (pkgs.rofi.override { plugins = [ pkgs.rofi-games ]; })
];
```
but you might also need to manually set the theme in a config file or when calling rofi

It's a bit easier if you have `home-manager`:
Add this to your home manager config:
```nix
programs.rofi = {
  enable = true;
  theme = "games-default";
  plugins = [ pkgs.rofi-games ];
};
```

Obviously `pkgs.rofi-games` doesn't yet exist on `master`, only on this PR, so you might need to use overlays, or any other method.

I haven't tested what I've written here, but should be correct.

**Comment by Aleksanaa** [comment]
I don't quite understand how it remains binary compatible with rofi. For example, rofi and rofi-wayland are currently incompatible, so all libraries written in C need to be built again with rofi-wayland instead of rofi as a dependency. But this package does not introduce any additional dependencies. The rofi-mode it relies on also doesn't seem to have anything to do with a build of rofi.

**Comment by Aleksanaa** [comment]
Got a solution.

**Comment by Aleksanaa** [comment]
```nix
  # Get rofi version from justfile to ensure abi compatibility
  preBuild = ''
    export RUSTFLAGS+="$(${lib.getExe just} --evaluate RUSTFLAGS)"
  '';

  nativeBuildInputs = [
    pkg-config
    rofi
  ];
```

Isn't pretty, though... You can also use just to control the build process.

**Comment by TomaSajt** [comment]
> ```nix
>   # Get rofi version from justfile to ensure abi compatibility
>   preBuild = ''
>     export RUSTFLAGS+="$(${lib.getExe just} --evaluate RUSTFLAGS)"
>   '';
> 
>   nativeBuildInputs = [
>     pkg-config
>     rofi
>   ];
> ```
> 
> Isn't pretty, though... You can also use just to control the build process.

Thanks, I'll push a commit shortly which just uses `just` and patches the `justfile`

**Comment by Aleksanaa** [comment]
`just` should have some command line options to edit or override those args. Will look into it tomorrow.

**Comment by TomaSajt** [comment]
> `just` should have some command line options to edit or override those args. Will look into it tomorrow.

The build phase only calls `just` with the `justFlags` as the inputs.
https://github.com/NixOS/nixpkgs/blob/97d675f41172e88f1339513eaff0b84f996e6230/pkgs/by-name/ju/just/setup-hook.sh#L7

However, `justFlags` is used in all other phases too, which would mean that the install phase would do `just build install`, which is weird

**Review by jtbx — APPROVED** [review]

**Comment by Rolv-Apneseth** [comment]
Hey, not sure if anything needs to be done on this end, but just wanted to give a heads up that I have since pushed some changes to `rofi-games`. Probably the only one that matters for this PR is support for a user config file at `$XDG_CONFIG_HOME/rofi-games/config.toml`.

**Comment by TomaSajt** [comment]
> Hey, not sure if anything needs to be done on this end, but just wanted to give a heads up that I have since pushed some changes to `rofi-games`. Probably the only one that matters for this PR is support for a user config file at `$XDG_CONFIG_HOME/rofi-games/config.toml`.

Thanks for the heads up!

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
