### PR TITLE
chromium,chromedriver,electron: use sri hashes instead of sha256 everywhere

### PR DESCRIPTION
**Pull request by networkException**
## Description of changes

This pull request removes `sha256` entries in `upstream-info.nix` and `info.json` and replaces them with sri hashes in `hash` fields. This pull request also changes the update scripts accordingly.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilylange** [comment]
@wegank why did you merge this so fast and not wait for both chromium and electron maintainers?

**Comment by wegank** [comment]
> @wegank why did you merge this so fast

Emmm, because the author didn't ask for a review of any teams and this PR doesn't have any rebuilds according to ofborg.

> and not wait for both chromium and electron maintainers?

I'll note this for the next time.

**Comment by emilylange** [comment]
Alright, fortunately, this does not merge-conflict with #262557.

It will make backporting slightly more annoying, though.
But `23.11` is more or less around the corner, so /shrug.

Not as bad as I imaged.
And thank you a lot for your quick response! @wegank :)

**Comment by networkException** [comment]
> because the author didn't ask for a review of any teams

I guess I shouldn't have assumed ofborg would ping people properly 😅

**Comment by yayayayaka** [comment]
@emilylange Thanks for the hint. I will update the electron stuff in #262557 and #262136 accordingly.

**Pull request merged**
