### PR TITLE
network-manager: replace hardcoded path to ping

### PR DESCRIPTION
**Pull request by peterhoeg**
This chance fixes the hardcoded path to /usr/bin/ping which fixes things on NixOS but partially breaks network-manager on non NixOS.
###### Things done:
- [X] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### More

Fixes issue #14103 

cc @abbradar

### CODE REVIEW

**Comment by abbradar** [comment]
I think I have a solution that satisfies both worlds -- as what user does NM usually run? If it's root or someone with raw network packet privileges, we can just replace path to ping in Nix store because we don't need SUID bit. For me at least it runs as root.

**Comment by abbradar** [comment]
Sadly I haven't seen those `ping` error messages. I suppose you can reproduce this -- could you try to replace hardcoded path with `${inetutils}/bin/ping` and see if it works?

Also, please rename commit to "network-manager: replace path to ping` (per our guidelines).

**Comment by abbradar** [comment]
Thanks! Did this work?

**Comment by peterhoeg** [comment]
I'm closing this for now until I have cleaned up the branch. Will then reopen.

**Pull request closed without merging**
