### PR TITLE
python3Packages.sphinx-serve: init at 1.0.1

### PR DESCRIPTION
**Pull request by FlorianFranzen**
###### Motivation for this change

sphinx-serve was missing from nixpkgs

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120045` at c5c9e0e7 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.sphinx-serve</li>
    <li>python39Packages.sphinx-serve</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/development/python-modules/sphinx-serve/default.nix:13:0:
```
   |
13 |     description = "Spawns a simple HTTP server to preview your sphinx documents";
   | ^
```
</li>
  </ul>
</details>

**Comment by FlorianFranzen** [comment]
Fixed test handling based on @r-rmcgibbo feedback.

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Does this package contain a binary which could use a top level entry?

**Comment by FlorianFranzen** [comment]
> Does this package contain a binary which could use a top level entry?

@SuperSandro2000 Indeed it does, but I refrained from exposing it, because sphinx itself also has no top level entry. But I can change that too. to be consistent.

**Comment by SuperSandro2000** [comment]
> Indeed it does, but I refrained from exposing it, because sphinx itself also has no top level entry. But I can change that too, to be consistent.

Then we should probably add one for both to make it easier to find those binaries/scripts.

**Comment by FlorianFranzen** [comment]
@SuperSandro2000 Ok, done. Added each in a separate commit.

**Pull request merged**
