### PR TITLE
[22.11] mastodon: 4.0.2 -> 4.0.3

### PR DESCRIPTION
**Pull request by erictapen**
###### Description of changes

[Changelog](https://github.com/mastodon/mastodon/releases/tag/v4.0.3)

As we didn't backport the 4.1.x releases, this should be applied to the stable channel.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Izorkin — APPROVED** [review]

**Comment by Izorkin** [comment]
@GrahamcOfBorg test mastodon

**Comment by Izorkin** [comment]
Problem with cert-ca:
```
ca # [   10.867997] step-ca[917]: 2023/03/20 20:15:24 net/http/server.go:3228: http: TLS handshake error from [::1]:43994: EOF
```

**Comment by Izorkin** [comment]
Backport this PR? - https://github.com/NixOS/nixpkgs/pull/202839 and https://github.com/NixOS/nixpkgs/pull/202857

**Comment by erictapen** [comment]
@Izorkin I'd rather not, agree with https://github.com/NixOS/nixpkgs/pull/202857#issuecomment-1327569607 here

**Pull request merged**
