### PR TITLE
pcsx2-bin: 1.7.5919 -> 2.1.17, derivation improvements

### PR DESCRIPTION
**Pull request by matteo-pacini**
## Description of changes

- Upgraded to latest available version
- @AndersonTorres removed dependency on `pcsx2`, and changed the name to `pcsx2-bin`
    - Update bot and script are failing -  [looks like a platform mismatch between the two derivations](https://r.ryantm.com/log/pcsx2-bin/2024-07-13.log)
    - Because of this change, I've added the missing `meta` bits from the `pcsx2` derivation
- QOL improvements:
    - Made `platforms` more readable
    - Removed `bin/pcsx2-qt` wrapper  for Darwin, as it doesn't make much sense

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matteo-pacini** [comment]
@NixOS/darwin-maintainers tested on `aarch64-darwin` via Rosetta, would be grateful if anyone could test this on `x86_64-darwin` 🙏🏻

**Comment by afh** [comment]
Result of `nixpkgs-review pr 328620` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pcsx2-bin</li>
  </ul>
</details>

**Review by afh — COMMENTED** [review]
Thanks for this @matteo-pacini.

While I'm okay with this being merged as is, I have a slight preference over shared meta attributes with pcsx2 and I'm not sure I understand the motivation to remove that.
Can you elaborate a bit please?

**Comment by matteo-pacini** [comment]
@afh sure! `pcsx2-bin` is a darwin-only derivation now, whilst `pcsx2` is linux-only.

The update scripts - regardless of being executed on my local device, or via the update bot @r-ryantm - fail because we import `pcsx2` as a requirement to build `pcsx2-bin` (because we need the `meta` attributes from it).
So we import a linux-only derivation whilst being on a darwin builder.

To avoid this, I chose to remove this requirement.

**Review by afh — APPROVED** [review]
That makes a lot of sense, @matteo-pacini, thanks for the explanation. Maybe @AndersonTorres has ideas on how to address this.

From my end it's a 🙂 👍

**Review by AndersonTorres — APPROVED** [review]

**Comment by AndersonTorres** [comment]
> (because we need the meta attributes from it)

This is a bit strange. Since, at least in theory, Nix is lazy *and* this is not building PCSX2 source, but merely grabbing pcsx2.meta (a thing that does not trigger building), the error should not happen.

Maybe the usage of `lib.inspect.*` is triggering some bug? I think it deserves some investigation...

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/326590#discussion_r1684708244

**Comment by AndersonTorres** [comment]
> [#326590 (comment)](https://github.com/NixOS/nixpkgs/pull/326590#discussion_r1684708244)

Well, it does not look like a blocking issue to me.

**Comment by pbsds** [comment]
* https://github.com/NixOS/nixpkgs/pull/329752

**Pull request merged**
