### PR TITLE
grafana-loki: init at 0.1.0

### PR DESCRIPTION
**Pull request by WilliButz**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS (x86_64-linux & aarch64-linux)
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mmahut** [comment]
Thank you for this package. Do you mind adding this as a service as well maybe?

**Comment by WilliButz** [comment]
@mmahut I have a module and test almost ready for upstreaming and will do that in the next days, but I wanted to get the package out of the way first, because this is as simple as a package gets :)

**Review by mmahut — APPROVED** [review]
Awesome, looking forward for testing it. The binary itself is working fine.

- [X] reviewed the diff and commit messages
- [X] made sure ofBorg build succeeded for all applicable platforms
- [X] run nix-review without any failures
- [X] run and tested the binaries

**Comment by Ma27** [comment]
Built and tested locally :+1:

**Comment by Ma27** [comment]
@WilliButz thanks!

**Pull request merged**
