### PR TITLE
newsbeuter: patch memory leak

### PR DESCRIPTION
**Pull request by ericsagnes**
upstream issue: https://github.com/akrennmair/newsbeuter/issues/119
upstream commit: https://github.com/akrennmair/newsbeuter/pull/213/commits

### CODE REVIEW

**Comment by ericsagnes** [comment]
Travis is complaining about a wrong hash for the patch:

````
trying https://github.com/akrennmair/newsbeuter/commit/cdacfbde9fe3ae2489fc96d35dfb7d263ab03f50.patch

output path ‘/nix/store/7i17b7ds73j4bkay5d4nx425apsbpkwx-cdacfbde9fe3ae2489fc96d35dfb7d263ab03f50.patch’ should have sha256 hash ‘1qi71w893llrknrm0vbxlc1bpvxlqgbs3b23a4cwv53j1vf0qz0x’, instead has ‘1lhvn63cqjpikwsr6zzndb1p5y140vvphlg85fazwx4xpzd856d9’
````
but it is building fine locally and, `nix-prefetch-url` give the right hash
```
nix-prefetch-url https://github.com/akrennmair/newsbeuter/commit/cdacfbde9fe3ae2489fc96d35dfb7d263ab03f50.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2654    0  2654    0     0   2697      0 --:--:-- --:--:-- --:--:--  2697
path is ‘/nix/store/7i17b7ds73j4bkay5d4nx425apsbpkwx-cdacfbde9fe3ae2489fc96d35dfb7d263ab03f50.patch’
1qi71w893llrknrm0vbxlc1bpvxlqgbs3b23a4cwv53j1vf0qz0x
````
Am I missing something or is it just a Travis problem?

**Comment by jgillich** [comment]
Travis has network issues all the time. I'm getting the same as you, would probably suffice to restart the build.

**Comment by ericsagnes** [comment]
@jgillich I see, thanks for the information.

**Comment by vcunat** [comment]
I'm getting the same hash as Travis does. Let me guess: you used `nix-prefetch-url` to get the hash because you didn't know that `fetchpatch` normalizes its output?

**Comment by ericsagnes** [comment]
@vcunat Thanks for fixing and yes, didn't know that `fetchpatch` normalizes its output.
What is the correct way to get the hash of a `fetchpatch` url?
The derivation was building fine on my machine with `1qi71w...`, so I am wondering why it didn't complain about the hash being different. Do you know what is the cause?

**Comment by vcunat** [comment]
There is no easy way except to run `fetchpatch`.

It didn't complain because it used no network during build. The results of fixed-output are content-addressed &ndash; you provided hash of the plainly-fetched file and it was in nix store already because you pre-fetched it.

**Comment by ericsagnes** [comment]
I see, it make sense.
Thanks for the explanation.

**Pull request closed without merging**
