### PR TITLE
Expose kernel version in toplevel

### PR DESCRIPTION
**Pull request by xaverdh**
###### Motivation for this change
This came up in https://github.com/NixOS/nixpkgs/pull/105910.
Currently in several places code extracts the kernel version from the kernel symlink in toplevel. This pr instead exposes it directly in a file "kernel-version" in toplevel.
This allows to use the actual kernel version (for example with `rc` suffix) rather than the name of the subdirectory of `lib/modules`.
Also said directory may not exist (e.g. if the kernel is compiled without modules), so the old way introduced some complexity which exposing the version this way avoids. 
The boot loader code will still want to support old generations for some time, so it has to fall back to the old behavior.
I adjusted `systemd-boot`, but my perl is not fluid enough, so I didn't touch the `install-grub` script; help is appreciated here.
Also `install-grub` appears to conflate the nixos version and the kernel version somehow?

This is WIP, because I first want to get some feedback, if that is a good approach at all.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xaverdh** [comment]
cc @lheckemann

**Comment by xaverdh** [comment]
>  Also install-grub appears to conflate the nixos version and the kernel version somehow?

So in particular the perl code will not care about the `modules` directory unless `nixos-version` if set, which it always is since https://github.com/NixOS/nixpkgs/commit/e3879fe365e539004942870b0757169cf757600f (Apr 2012)

**Comment by lheckemann** [comment]
Sorry for only just looking at this, what's the advantage of this over looking at the version in the linux kernel store path, i.e. 
```python
    kernel_dir = os.path.dirname(os.path.realpath("%s/kernel" % generation_dir))
    kernel_version = re.match(".*?-([0-9].*)", kernel_dir).group(1)
```
(plus error checking)?

**Comment by xaverdh** [comment]
> 


> Sorry for only just looking at this, what's the advantage of this over looking at the version in the linux kernel store path, i.e.
> 
> ```python
>     kernel_dir = os.path.dirname(os.path.realpath("%s/kernel" % generation_dir))
>     kernel_version = re.match(".*?-([0-9].*)", kernel_dir).group(1)
> ```
> 
> (plus error checking)?

right that should work, and is a lot simpler!

**Pull request closed without merging**
