### PR TITLE
kaniko: init at 1.9.1

### LINKED ISSUE #216542: Package request: kaniko
**Project description**

kaniko is a tool to build container images from a Dockerfile, inside a container or Kubernetes cluster

**Metadata**

homepage URL: [https://github.com/GoogleContainerTools/kaniko](https://github.com/GoogleContainerTools/kaniko)
source URL: [https://github.com/GoogleContainerTools/kaniko](https://github.com/GoogleContainerTools/kaniko)
license: [Apache-2.0 license](https://github.com/GoogleContainerTools/kaniko/blob/main/LICENSE)
platforms: Linux

### PR DESCRIPTION
**Pull request by superherointj**
kaniko: init at 1.9.1

Release: https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.9.1

fixes #216542

### CODE REVIEW

**Comment by matthewpi** [comment]
Result of `nixpkgs-review pr 216654` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>kaniko</li>
  </ul>
</details>

**Review by bryanasdev000 — APPROVED** [review]
LGTM.

**Comment by bryanasdev000** [comment]
Sorry to comment after merge, but restricting to linux platform would be nice, as I do not think darwin will build it (based on ofborg logs).

**Comment by superherointj** [comment]
> as I do not think darwin will build it

Want to make a PR? (So I review/merge it.)

**Comment by bryanasdev000** [comment]
> > as I do not think darwin will build it
> 
> Want to make a PR? (So I review/merge it.)

Will be afk from PC for some time. Maybe later.

**Pull request merged**
