### PR TITLE
maintainers: add GPG key fingerprint for user `kevincox`

### PR DESCRIPTION
**Pull request by kevincox**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by drupol — DISMISSED** [review]
The commit message would be better if it would be `maintainers: add GPG key fingerprint for user kevincox`

**Comment by drupol** [comment]
I would also keep attributes sorted alphabetically.

**Comment by kevincox** [comment]
Every other `keys =` in the file is the last attribute. I think it is best to match the convention.

**Comment by kevincox** [comment]
Conformity also has benefits navigating the codebase. I don't think that a small PR to add some data is the place to discuss changing a convention. If we want to change a convention is makes sense to do that independently of any data change and to do it all at once so that consistency is maintained. So I think we should merge this according to the existing convention and we can discuss changing the convention separately on its own merits.

**Comment by drupol** [comment]
I appreciate your points on conformity and the timing for discussing convention changes. My suggestion for alphabetical sorting aimed at consistency, not changing conventions. It's been a common practice in my reviews for clarity and hasn't been an issue sop far.

I respect your stance. Let's keep this PR aligned with your ideas, and we can discuss any potential changes in a separate conversation.

However, I'll pass on merging this PR to maintain objectivity. Looking forward to continuing our collaboration and discussions on improving `nixpkgs`.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
