### PR TITLE
mercurial: 5.6 -> 5.8, oxidize

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

* Mercurial 5.8 is out. And so was 5.7.
* Add Rust support (for Linux, only, since there are dire warnings about it on other platforms). This speeds up some operations.
* Adds re2 for speedier regex evaluation.
* Compile the translations that are provided.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
      - Before: `/nix/store/q4xydpsb37149dl7xxvwp456c58x6hwb-mercurial-5.6         113840224`
      - After: `/nix/store/q3z0h1mwsyxi3kd77j65f8b9mawppga7-mercurial-5.8         131381528`
      - --> ~20MB increase
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121611` at 53ddf53f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/70706bf109283b70331935ba03ad0860">haskell-language-server</a></li>
    <li><a href="https://gist.github.com/fe4231d59ffb37184d31c5323028c1f2">haskellPackages.ghcide</a></li>
    <li><a href="https://gist.github.com/85dc899f7742fa77d722ada436668c1f">haskellPackages.haskell-language-server</a></li>
    <li><a href="https://gist.github.com/c96a2c35eda4ac8c87b2592c50dda9b5">haskellPackages.hls-class-plugin</a></li>
    <li><a href="https://gist.github.com/d5c2681cec8a729a1f54c5afa3530658">haskellPackages.hls-eval-plugin</a></li>
    <li><a href="https://gist.github.com/916ca8141fefd371bd0197ccaee7fe3d">haskellPackages.hls-explicit-imports-plugin</a></li>
    <li><a href="https://gist.github.com/3dc2baae1e566c225d6a6737c6d4a300">haskellPackages.hls-haddock-comments-plugin</a></li>
    <li><a href="https://gist.github.com/447376275084b87a671c0a6e77041c58">haskellPackages.hls-hlint-plugin</a></li>
    <li><a href="https://gist.github.com/c4519a2a49ab06cdee80e6c5ce38f963">haskellPackages.hls-retrie-plugin</a></li>
    <li><a href="https://gist.github.com/59dccc7b6663ad8ba1c07263d4fe93a5">haskellPackages.hls-splice-plugin</a></li>
    <li><a href="https://gist.github.com/46130951d92d5ea78df575e990b450c8">haskellPackages.hls-tactics-plugin</a></li>
    <li><a href="https://gist.github.com/3189a6dfd81caeb82d3246acb21b1a5f">haskellPackages.retrie</a></li>
    <li><a href="https://gist.github.com/dab4129ee9088c2caa1f688de78552e3">tortoisehg</a></li>
  </ul>
</details>
<details>
  <summary>25 packages built successfully:</summary>
  <ul>
    <li>bumpver</li>
    <li>cabal2nix</li>
    <li>dep2nix</li>
    <li>devpi-client</li>
    <li>dune-release</li>
    <li>git-cinnabar</li>
    <li>git-remote-hg</li>
    <li>hound</li>
    <li>hydra-unstable</li>
    <li>mbed-cli</li>
    <li>mercurial (python38Packages.mercurial)</li>
    <li>mercurialFull</li>
    <li>nbstripout</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>patroni</li>
    <li>powerline (python38Packages.powerline)</li>
    <li>python38Packages.hglib</li>
    <li>ydiff (python38Packages.ydiff)</li>
    <li>python39Packages.hglib</li>
    <li>python39Packages.mercurial</li>
    <li>python39Packages.powerline</li>
    <li>python39Packages.ydiff</li>
    <li>sourcehut.hgsrht</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by lukegb** [comment]
`haskellPackages.retrie` is indeed broken - the Rust implementation appears to not quite handle hg status with an hg ignore and --include correctly.

**Comment by lukegb** [comment]
Result of `nixpkgs-review pr 121611` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>bumpver</li>
    <li>cabal2nix</li>
    <li>dep2nix</li>
    <li>devpi-client</li>
    <li>dune-release</li>
    <li>git-cinnabar</li>
    <li>git-remote-hg</li>
    <li>haskell-language-server</li>
    <li>hound</li>
    <li>hydra-unstable</li>
    <li>mbed-cli</li>
    <li>mercurial (python38Packages.mercurial)</li>
    <li>mercurialFull</li>
    <li>nbstripout</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>patroni</li>
    <li>powerline (python38Packages.powerline)</li>
    <li>python38Packages.hglib</li>
    <li>ydiff (python38Packages.ydiff)</li>
    <li>python39Packages.hglib</li>
    <li>python39Packages.mercurial</li>
    <li>python39Packages.powerline</li>
    <li>python39Packages.ydiff</li>
    <li>sourcehut.hgsrht</li>
    <li>tortoisehg</li>
  </ul>
</details>

**Comment by lukegb** [comment]
Result of `nixpkgs-review pr 121611` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mbed-cli</li>
  </ul>
</details>
<details>
  <summary>34 packages built:</summary>
  <ul>
    <li>bumpver</li>
    <li>cabal2nix</li>
    <li>dep2nix</li>
    <li>devpi-client</li>
    <li>dune-release</li>
    <li>git-cinnabar</li>
    <li>git-remote-hg</li>
    <li>haskell-language-server</li>
    <li>haskellPackages.ghcide</li>
    <li>haskellPackages.haskell-language-server</li>
    <li>haskellPackages.hls-class-plugin</li>
    <li>haskellPackages.hls-eval-plugin</li>
    <li>haskellPackages.hls-explicit-imports-plugin</li>
    <li>haskellPackages.hls-haddock-comments-plugin</li>
    <li>haskellPackages.hls-hlint-plugin</li>
    <li>haskellPackages.hls-retrie-plugin</li>
    <li>haskellPackages.hls-splice-plugin</li>
    <li>haskellPackages.hls-tactics-plugin</li>
    <li>haskellPackages.retrie</li>
    <li>hound</li>
    <li>mercurial (python38Packages.mercurial)</li>
    <li>mercurialFull</li>
    <li>nbstripout</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>powerline (python38Packages.powerline)</li>
    <li>python38Packages.hglib</li>
    <li>ydiff (python38Packages.ydiff)</li>
    <li>python39Packages.hglib</li>
    <li>python39Packages.mercurial</li>
    <li>python39Packages.powerline</li>
    <li>python39Packages.ydiff</li>
    <li>sourcehut.hgsrht</li>
  </ul>
</details>

**Comment by sternenseemann** [comment]
cc @maralorn (haskell-language-server breaks)

**Comment by sternenseemann** [comment]
Can't reproduce the haskell failures, more context?

```
lukas@wolfgang ~/s/n/nixpkgs ((35e57e81…))> nix-build -A haskellPackages.retrie -A haskellPackages.haskell-language-server
/nix/store/j840s67acpwdncdacijp4n1ls9xcyqmx-retrie-1.0.0.0
/nix/store/4240zg7m33c6zw74lm09mlk241f7kmz0-haskell-language-server-1.0.0.0
```

**Review by sternenseemann — APPROVED** [review]

**Comment by maralorn** [comment]
If hls still builds this is fine from my point of view. Thx!

**Pull request merged**
