### PR TITLE
ocaml-modules: fix naming: "_" -> "-"

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by ts468** [comment]
Hi, I'm trying to unify the naming of ocam-modules. As far as I understand, no underscores should be used.

@ericbmerritt, @vbgl, I think a few of your packages are affected. Could you please comment on the suggested PR? Many thanks!

**Comment by ericbmerritt** [comment]
@ts468 I have no problem with that in general. I think I only used them for
the packages I created because that was the style that was there already.
@vbgl may have more insight.

**Comment by ericbmerritt** [comment]
@ts468. One thing that I think we should talk about is that the underscore
is actually part of the package name in each of these cases. What is the
drive for using dashes instead?

Eric

**Comment by jagajaga** [comment]
What's the reason to do so?

**Comment by ts468** [comment]
The motivation to unify the naming of ocam modules is coming from my attempt to merge a larger set of new ocaml modules, PR #5529. It might be that I misunderstood Eelco's comment in #5529, but thought that dashes would be preferred to underscores.

I'm not pushing for dashes or underscores, I just think we should agree on one scheme. :) E.g, having the 'ocaml_' hierarchy prefix separated by '_' would make a lot of sense as well. Do you know what the rule is for Haskell, Python and all the other packages?

**Comment by vcunat** [comment]
Naming guidelines [are documented](http://nixos.org/nixpkgs/manual/#sec-package-naming) and say we want to be close to upstream naming, which is typically dashes. However, mass rename is always controversial, as it would break code of people depending on those modules.

**Comment by ts468** [comment]
Would be nice to add a warning like the one suggested in #9456 for the ocaml module aliases as well at some point.

**Comment by vcunat** [comment]
Well, first we must agree on a technical way how to detect when to show such warnings. I posted a suggestion in there...

**Comment by vbgl** [comment]
This PR is a failure. Please revert it.

The naming scheme is still random and unpredictible (`js_of_ocaml` vs. `erm-xml` vs. `ocaml_lwt` vs. `ocaml-cairo`). The naming scheme is still undocumented.

If you don’t like underscore, you should file bugs upstream: `erm_xml` is the name of the OCaml library. Bad name? maybe. But please do not change it randomly when naming the nixpkgs attribute path.

**Comment by ts468** [comment]
What's a better suggestion of getting a uniform naming scheme for ocaml modues then? I mean a naming scheme where one doesn't have to guess whether it is underscore or dash and where simple scripts can operate on the module names. I wouldn't care about a consistent naming scheme if I wouldn't have run into trouble already with the current package names.

It seems to me as nixpkgs would be moving towards dashes, and so I used that for the ocaml names as well. Changing the names upstream does not really seem realistic, or?

It's correct that as of now not all ocaml module names are converted and so it might be still random and unpredictable. But as the old names are still available it should not matter too much. It's planed to rename the other ocaml modules step by step.

**Comment by vbgl** [comment]
What trouble have you run into?

Uniform naming scheme suggestion: keep the name of the library, so that you can use the same identifier in your `default.nix` and in your `.merlin` files (for instance); and the same identifier in your `nix-shell` and `ocamlfind` invocations. Therefore: `type_conv` and `asn1-combinators`. You’ll need more rules when there are several versions of one library and several libraries with the same name (e.g., `deriving`).

**Comment by ericbmerritt** [comment]
I have to say I strongly agree with @vbgl. The name of the  standard should be defined by the name of the library.

**Comment by ts468** [comment]
The origin of my initiative is that I have a script that converts RPM specification files to nix package definitions. The RPM specifications used dashes for naming ocaml modules, as do DEB files and the macports repository. Of course that's not an argument as, e.g., Arch Linux is using the original package name.

Do you know how if there is a nixpkgs specific naming convention for a large collection like, e.g., all the Haskell packages? Maybe the same could be adapted for ocaml as well. If it's simply upstream names, then I declare defeat and I'm very sorry for all the trouble! ;)

**Comment by vcunat** [comment]
Haskell currently uses Hackage names exactly as they are, e.g. ```"3dmodels" = callPackage ...```, [link to docs](http://nixos.org/nixpkgs/manual/#how-to-install-haskell-packages). I currently used the same way with TeX, as I couldn't find a way how to transliterate sensibly names starting with digits (except for adding some prefix, but I find that ugly as well).

Actually, I don't see a problem in using two attribute-naming systems at once &ndash; one as aliases to the other. It might help people that are used to RPM/DEB (a large fraction Linux installations).

**Comment by ts468** [comment]
@vcunat, thanks for the reference about the Haskell naming, and for suggesting a compromise. But I'm afraid that having two names becomes a mess very quickly, so I'm more leaning towards reverting the PR. @vbgl, @ericbmerritt, you would prefer to have upstream names over a universal, e.g., dash based naming convention, right? I'll find a way to work with upstream names as well, I guess. ;)

**Pull request merged**
