### PR TITLE
docker service: make storage driver optional

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Comment by bjornfor** [comment]
This is similar to https://github.com/NixOS/nixpkgs/pull/10100, but less complete.

**Comment by bjornfor** [comment]
Alternative fix in master (5f17aeb4035057deb1840372f5a0a33098ce1e82) and release 15.09 (ab0a464e4b04773d48f14cf4cbb934eca3ef465c).

**Comment by offlinehacker** [comment]
Why did you make devicemapper default. Docker knows automatically which
Driver to select in some cased, for example if running on btrfs it will
select btrfs and devicemapper bad default anyway, overlayfs is bettet.
Please fix.

V ned., 4. okt. 2015 2:38 pop. je oseba Bjørn Forsman <
notifications@github.com> napisala:

**Comment by offlinehacker** [comment]
This essentially breaks all my deploynents where i'm using btrfs.

V ned., 4. okt. 2015 3:51 pop. je oseba Jaka Hudoklin <
jakahudoklin@gmail.com> napisala:

**Comment by lethalman** [comment]
@offlinehacker ah it chooses at runtime too? Didn't know. But shouldn't you be explicitly defining the storage driver instead of docker guessing it?

**Comment by bjornfor** [comment]
@offlinehacker: Then please make it optional again. I only made it fixed because it was discussed in PR https://github.com/NixOS/nixpkgs/pull/10100 and I was down-voted. (I also didn't know that docker had different defaults depending on context.)

**Comment by bjornfor** [comment]
Uhm, this makes me re-consider my first thoughts about reverting 9bfe92ecee3359576093cfb534adbec13dcbd580 and just focus on fixing the NixOS VM tests...

**Comment by offlinehacker** [comment]
I don't know why we need this option. What's wrong with Driver automaticaly
choosen by docker. It chooses Driver by priority: aufs, btrfs, zfs,
devicemapper, overlay, vfs.

V ned., 4. okt. 2015 3:58 pop. je oseba Bjørn Forsman <
notifications@github.com> napisala:

**Pull request closed without merging**
