### PR TITLE
Add package: mpdscribble

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This adds "mpdscribble"

Shall I add an appropriate NixOS service as well (Would include this into this PR, but not into the commit, of course)?

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
In 5078d49248e29bacd442fac889123c2c0a68e13e , builds fine but not tested beyond `--help`.

>Shall I add an appropriate NixOS service as well (Would include this into this PR, but not into the commit, of course)?

If you wish to do so then go for it and please open a separate PR for it.

**Comment by matthiasbeyer** [comment]
Huh, closed?

**Comment by Fuuzetsu** [comment]
Yes, put the patch on master so GitHub didn't pick up as merge.

**Comment by matthiasbeyer** [comment]
Is this the actual policy? I don't like that... but well, I can't do anything against it, of course.

**Comment by Fuuzetsu** [comment]
No, it's not a policy, I just happened to be applying some other stuff and grabbed it with it. Most people just press the button.

**Comment by jagajaga** [comment]
Why you don't like it? :)

**Comment by matthiasbeyer** [comment]
@jagajaga Because you (not you in person, but the person who does the merge) does not give the credit to the contributor. It's not that I'm a karma whore or something, but it is a thing that matters to me. I like to say "hey, I committed this to a project and they applied it, so I was successfull with a contribution" - it is reputation for me.

**Comment by jagajaga** [comment]
As you can see in commits history, the author of the commit is you. Even it 
was added manually.

**Comment by matthiasbeyer** [comment]
@jagajaga Yes, but github does not recognize this. And most people don't mess around with history but look at github profiles (especially Head-Hunters)!

I don't care this much about the NixOS patches, though! I benefit from them and that is what counts for me! I would be really pissed if the kernel people wouldn't give credit,... but they don't have the problem that github does not recognize the patches as merged! So, never mind! I'm fine!

**Comment by jagajaga** [comment]
If you do contribute to open source to get you name, you are doing it wrong. IMO.

**Comment by matthiasbeyer** [comment]
I don't do it to get a name in the community. But it is a nice side effect! I, personally, do it because I care about software I use and I want to improve the experience for everyone!

**Comment by Fuuzetsu** [comment]
GitHub still recognises your commit, it shows you commited to the project and you get 1 contribution added. The only difference from that point of view is that your PR shows as ‘Closed’ instead of ‘Merged’.

**Comment by matthiasbeyer** [comment]
Jup, and that's what annoys me.

**Pull request closed without merging**
