### PR TITLE
mautrix-signal: 0.6.3 -> 0.7.0

### PR DESCRIPTION
**Pull request by frederictobiasc**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by frederictobiasc** [comment]
Release notes suggest there may be changes to the config file. I'll check for necessary module updates before marking this as ready.

**Comment by niklaskorz** [comment]
Fails to start for me:

```
Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Initializing bridge built_at=0001-01-01T00:00:00Z go_version=go1.22.5 name=mautrix-signal version=0.7.0+dev.unknown
Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Initializing libsignal version:0.55.1 component=libsignal file=rust/bridge/ffi/src/logging.rs line=106 target=signal_ffi::logging
Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Starting bridge
Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Database is up to date current_version=16 db_section=main latest_known_version=16 oldest_compatible_version=9
Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Starting Matrix connector
Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Database is up to date current_version=6 db_section=matrix_state latest_known_version=6 oldest_compatible_version=3
Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Starting HTTP listener address=[::]:29328
Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Database is up to date current_version=15 db_section=crypto latest_known_version=15 oldest_compatible_version=15
Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   FTL Failed to start bridge error="failed to start Matrix connector: the supplied account key is invalid"
Aug 31 16:56:04 korz-tech systemd[1]: mautrix-signal.service: Main process exited, code=exited, status=1/FAILURE
```

**Review by niklaskorz — CHANGES_REQUESTED** [review]
```diff
diff --git a/modules/mautrix-signal.nix b/modules/mautrix-signal.nix
index 932665c..f070f56 100644
--- a/nixos/modules/services/matrix/mautrix-signal.nix
+++ b/nixos/modules/services/matrix/mautrix-signal.nix
@@ -50,6 +50,10 @@ let
         time_format = " ";
       };
     };
+    double_puppet = {
+      servers = {};
+      secrets = {};
+    };
   };

 in
@@ -105,7 +109,7 @@ in
         File containing environment variables to be passed to the mautrix-signal service.
         If an environment variable `MAUTRIX_SIGNAL_BRIDGE_LOGIN_SHARED_SECRET` is set,
         then its value will be used in the configuration file for the option
-        `login_shared_secret_map` without leaking it to the store, using the configured
+        `double_puppet.secrets` without leaking it to the store, using the configured
         `homeserver.domain` as key.
       '';
     };
@@ -206,7 +210,7 @@ in
         ${pkgs.yq}/bin/yq -s '.[0].appservice.as_token = .[1].as_token
           | .[0].appservice.hs_token = .[1].hs_token
           | .[0]
-          | if env.MAUTRIX_SIGNAL_BRIDGE_LOGIN_SHARED_SECRET then .bridge.login_shared_secret_map.[.homeserver.domain] = env.MAUTRIX_SIGNAL_BRIDGE_LOGIN_SHARED_SECRET else . end' \
+          | if env.MAUTRIX_SIGNAL_BRIDGE_LOGIN_SHARED_SECRET then .double_puppet.secrets.[.homeserver.domain] = env.MAUTRIX_SIGNAL_BRIDGE_LOGIN_SHARED_SECRET else . end' \
           '${settingsFile}' '${registrationFile}' > '${settingsFile}.tmp'
         mv '${settingsFile}.tmp' '${settingsFile}'
         umask $old_umask
```

**Comment by niklaskorz** [comment]
> Fails to start for me:
> 
> ```
> Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Initializing bridge built_at=0001-01-01T00:00:00Z go_version=go1.22.5 name=mautrix-signal version=0.7.0+dev.unknown
> Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Initializing libsignal version:0.55.1 component=libsignal file=rust/bridge/ffi/src/logging.rs line=106 target=signal_ffi::logging
> Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Starting bridge
> Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Database is up to date current_version=16 db_section=main latest_known_version=16 oldest_compatible_version=9
> Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Starting Matrix connector
> Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Database is up to date current_version=6 db_section=matrix_state latest_known_version=6 oldest_compatible_version=3
> Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Starting HTTP listener address=[::]:29328
> Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   INF Database is up to date current_version=15 db_section=crypto latest_known_version=15 oldest_compatible_version=15
> Aug 31 16:56:04 korz-tech mautrix-signal[232817]:   FTL Failed to start bridge error="failed to start Matrix connector: the supplied account key is invalid"
> Aug 31 16:56:04 korz-tech systemd[1]: mautrix-signal.service: Main process exited, code=exited, status=1/FAILURE
> ```

I believe this might have something do to with the newly introduced `encryption.pickle_key` parameter

**Review by Ma27 — CHANGES_REQUESTED** [review]
Please split formatting in its own commit if you insist on it. It makes reviewing needlessly harder if you always have to check if you're having a formatting-only change, a behavioral change or both.

**Comment by frederictobiasc** [comment]
> We should set the default value to `encryption.pickle_key = "mautrix.bridge.e2ee"` if `system.stateVersion` is 24.05 or older.

Why do you think should do that? Current users do not need to take any action, because mautrix-signal migrates pre-0.7.0-configurations.
In case a user wants to migrate their config to the new standard, they get the diff between the default config and their migrated config and put this into their module configuration.

> For 24.11 and newer, we can't rely on the current behavior. Right now, the default value is set to `generate`. This will break when the user updates their mautrix-signal config as this will override the previously generated config and discard the generated pickle key. I think our options are:
>     1. Setting the default value to `encryption.pickle_key = ""`. This will results in a panic when mautrix-signal starts: https://github.com/mautrix/go/blob/79391515ed64f4c39490e39ae694ee9f25a2aee6/bridgev2/matrix/crypto.go#L70

I think we should do that and update the information in the manual accordingly.

>     2. Allow the user to set a `MAUTRIX_SIGNAL_PICKLE_KEY` in their environment variable file that then overrides the value in the same way we are already doing with the double puppet secrets.

Users can already do that since the `preStart` script executes envsubst on the settings file. Nothing to do here.

**Comment by frederictobiasc** [comment]
> Please split formatting in its own commit if you insist on it. It makes reviewing needlessly harder if you always have to check if you're having a formatting-only change, a behavioral change or both.

done

**Comment by niklaskorz** [comment]
@frederictobiasc You're correct about envsubst of course, so that'll work fine. Please apply the changes from https://github.com/NixOS/nixpkgs/pull/337534#pullrequestreview-2273882035 so double puppeting continues to work.

**Comment by frederictobiasc** [comment]
> @frederictobiasc You're correct about envsubst of course, so that'll work fine. Please apply the changes from [#337534 (review)](https://github.com/NixOS/nixpkgs/pull/337534#pullrequestreview-2273882035) so double puppeting continues to work.

done

**Review by Ma27 — APPROVED** [review]
The package change looks good.
The module change looks reasonable, but I haven't tested it since my setup is older than the NixOS modules and I never bothered to migrate.

About the migration for encryption: I might've found an issue in the upgrade instructions, but first need to talk the authors since I'm not sure about the security implications. Since that's an issue about 0.6.3 and not about 0.7.0 it's not a blocker for this PR though.

**Comment by niklaskorz** [comment]
Testing the latest module changes right now

**Review by niklaskorz — APPROVED** [review]

**Pull request merged**
