### PR TITLE
xfce: update most packages

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

- common-updater: change default development version check to false
- xfce.exo: 0.12.8 -> 0.12.11
- xfce.exo: add support for gtk2, besides gtk3
- xfce.gigolo: 0.5.0 -> 0.5.1
- xfce.parole: 1.0.4 -> 1.0.5
- xfce.thunar: 1.8.9 -> 1.8.14
- xfce.tumbler: 0.2.7 -> 0.2.8
- xfce.xfburn: 0.6.1 -> 0.6.2
- xfce.xfce4-battery-plugin: 1.1.2 -> 1.1.3
- xfce.xfce4-clipman-plugin: 1.4.3 -> 1.6.1
- xfce.xfce4-cpugraph-plugin: 1.0.5 -> 1.1.0
- xfce.xfce4-dict-plugin: remove
- xfce.xfce4-dict: 0.8.2 -> 0.8.3
- xfce.xfce4-embed-plugin: update meta and buildInputs
- xfce.xfce4-eyes-plugin: 4.4.4 -> 4.5.0
- xfce.xfce4-fsguard-plugin: 1.0.2 -> 1.1.1
- xfce.xfce4-genmon-plugin: 3.4.0 -> 4.0.2
- xfce.xfce4-hardware-monitor-plugin: update meta
- xfce.xfce4-icon-theme: update gtk dependency and add license
- xfce.xfce4-mailwatch-plugin: remove broken status
- xfce.xfce4-mpc-plugin: 0.4.5 -> 0.5.2
- xfce.xfce4-netload-plugin: 1.3.1 -> 1.3.2
- xfce.xfce4-netload-plugin: odd minor version number is not unstable
- xfce.xfce4-notes-plugin: 1.7.7 -> 1.8.1
- xfce.xfce4-notifyd: 0.4.4 -> 0.6.0
- xfce.xfce4-panel: 4.14.0 -> 4.14.3
- xfce.xfce4-power-manager: 1.6.5 -> 1.6.6
- xfce.xfce4-pulseaudio-plugin: 0.4.2 -> 0.4.3
- xfce.xfce4-screenshooter: 1.9.5 -> 1.9.7
- xfce.xfce4-sensors-plugin: 1.2.6 -> 1.3.92
- xfce.xfce4-session: 4.14.0 -> 4.14.2
- xfce.xfce4-settings: 4.14.0 -> 4.14.3
- xfce.xfce4-systemload-plugin: 1.1.2 -> 1.2.3
- xfce.xfce4-taskmanager: 1.2.2 -> 1.2.3
- xfce.xfce4-terminal: 0.8.8 -> 0.8.9.2
- xfce.xfce4-timer-plugin: 1.6.0 -> 1.7.0
- xfce.xfce4-vala-panel-appmenu-plugin: 0.6.94 -> 0.7.3
- xfce.xfce4-weather-plugin: 0.8.10 -> 0.10.1
- xfce.xfce4-windowck-plugin: 0.4.4 -> 0.4.6
- xfce.xfdashboard: 0.7.5 -> 0.7.7
- xfce.xfdesktop: 4.14.1 -> 4.14.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
@GrahamcOfBorg build xfce.exo xfce.gigolo xfce.parole xfce.thunar xfce.tumbler xfce.xfburn xfce.xfce4-battery-plugin xfce.xfce4-clipman-plugin xfce.xfce4-cpugraph-plugin xfce.xfce4-dict xfce.xfce4-eyes-plugin xfce.xfce4-fsguard-plugin xfce.xfce4-genmon-plugin xfce.xfce4-mpc-plugin xfce.xfce4-netload-plugin xfce.xfce4-notes-plugin xfce.xfce4-notifyd xfce.xfce4-panel xfce.xfce4-power-manager xfce.xfce4-pulseaudio-plugin xfce.xfce4-screenshooter xfce.xfce4-sensors-plugin xfce.xfce4-session xfce.xfce4-settings xfce.xfce4-systemload-plugin xfce.xfce4-taskmanager xfce.xfce4-terminal xfce.xfce4-timer-plugin xfce.xfce4-vala-panel-appmenu-plugin xfce.xfce4-weather-plugin xfce.xfce4-windowck-plugin xfce.xfdashboard xfce.xfdesktop

**Comment by romildo** [comment]
@GrahamcOfBorg build xfce.exo xfce.gigolo xfce.parole xfce.thunar xfce.tumbler xfce.xfburn xfce.xfce4-battery-plugin xfce.xfce4-clipman-plugin xfce.xfce4-cpugraph-plugin xfce.xfce4-dict xfce.xfce4-embed-plugin xfce.xfce4-eyes-plugin xfce.xfce4-fsguard-plugin xfce.xfce4-genmon-plugin xfce.xfce4-hardware-monitor-plugin xfce.xfce4-icon-theme xfce.xfce4-mailwatch-plugin xfce.xfce4-mpc-plugin xfce.xfce4-netload-plugin xfce.xfce4-notes-plugin xfce.xfce4-notifyd xfce.xfce4-panel xfce.xfce4-power-manager xfce.xfce4-pulseaudio-plugin xfce.xfce4-screenshooter xfce.xfce4-sensors-plugin xfce.xfce4-session xfce.xfce4-settings xfce.xfce4-systemload-plugin xfce.xfce4-taskmanager xfce.xfce4-terminal xfce.xfce4-timer-plugin xfce.xfce4-vala-panel-appmenu-plugin xfce.xfce4-weather-plugin xfce.xfce4-windowck-plugin xfce.xfdashboard xfce.xfdesktop

**Comment by romildo** [comment]
@GrahamcOfBorg build xfce.exo xfce.gigolo xfce.parole xfce.thunar xfce.tumbler xfce.xfburn xfce.xfce4-battery-plugin xfce.xfce4-clipman-plugin xfce.xfce4-cpugraph-plugin xfce.xfce4-dict xfce.xfce4-embed-plugin xfce.xfce4-eyes-plugin xfce.xfce4-fsguard-plugin xfce.xfce4-genmon-plugin xfce.xfce4-hardware-monitor-plugin xfce.xfce4-icon-theme xfce.xfce4-mailwatch-plugin xfce.xfce4-mpc-plugin xfce.xfce4-netload-plugin xfce.xfce4-notes-plugin xfce.xfce4-notifyd xfce.xfce4-panel xfce.xfce4-power-manager xfce.xfce4-pulseaudio-plugin xfce.xfce4-screenshooter xfce.xfce4-sensors-plugin xfce.xfce4-session xfce.xfce4-settings xfce.xfce4-systemload-plugin xfce.xfce4-taskmanager xfce.xfce4-terminal xfce.xfce4-timer-plugin xfce.xfce4-vala-panel-appmenu-plugin xfce.xfce4-weather-plugin xfce.xfce4-windowck-plugin xfce.xfdashboard xfce.xfdesktop

**Review by jD91mZM2 — APPROVED** [review]
I don't really the the appmenu plugin anymore and should remove myself as a maintainer, but I mean yeah, the changes look good!

**Comment by worldofpeace** [comment]
@GrahamcOfBorg test xfce

**Review by worldofpeace — DISMISSED** [review]
LGTM, ran every default program in a VM.

**Comment by worldofpeace** [comment]
Actually, how are we going to handle migration for https://github.com/NixOS/nixpkgs/pull/85318/commits/eb19356524763a01d7d5536b3bb9b93df7ca1173 ?

**Comment by worldofpeace** [comment]
I also thing we removed gtk2 from exo already https://github.com/NixOS/nixpkgs/pull/85318/commits/dd8c3333875784ba32dc83af718c66297c84fbce. gtk2 support is going to be removed anyways IIRC, and we're going to release 20.09 with a new version of XFCE.

**Comment by romildo** [comment]
> Actually, how are we going to handle migration for [eb19356](https://github.com/NixOS/nixpkgs/commit/eb19356524763a01d7d5536b3bb9b93df7ca1173) ?

Maybe just throw  message:

``` nix
  xfce4-dict-plugin = throw "xfce4-dict-plugin is now part of xfce4-dict.";
```

**Comment by romildo** [comment]
> I also thing we removed gtk2 from exo already [dd8c333](https://github.com/NixOS/nixpkgs/commit/dd8c3333875784ba32dc83af718c66297c84fbce). gtk2 support is going to be removed anyways IIRC, and we're going to release 20.09 with a new version of XFCE.

Some XFCE applications and plugins still uses gtk2. Some other core components (`xfce4-panel`, `libxfce4ui`) still enable it for that reason. Why do not enable it too for `exo`, so that some plugins can be built?

With the next XFCE release we expect the definitive remove of gtk2, though.

**Comment by worldofpeace** [comment]
> > I also thing we removed gtk2 from exo already [dd8c333](https://github.com/NixOS/nixpkgs/commit/dd8c3333875784ba32dc83af718c66297c84fbce). gtk2 support is going to be removed anyways IIRC, and we're going to release 20.09 with a new version of XFCE.
> 
> Some XFCE applications and plugins still uses gtk2. Some other core components (`xfce4-panel`, `libxfce4ui`) still enable it for that reason. Why do not enable it too for `exo`, so that some plugins can be built?
> 
> With the next XFCE release we expect the definitive remove of gtk2, though.

Hmm, I guess we can just clean it up when they release.

**Comment by worldofpeace** [comment]
> > Actually, how are we going to handle migration for [eb19356](https://github.com/NixOS/nixpkgs/commit/eb19356524763a01d7d5536b3bb9b93df7ca1173) ?
> 
> Maybe just throw message:
> 
> ```nix
>   xfce4-dict-plugin = throw "xfce4-dict-plugin is now part of xfce4-dict.";
> ```

Sounds good, there's an alias section in xfce/default.nix

**Review by worldofpeace — APPROVED** [review]
Squash the fixup and merge is fine :+1:

**Pull request merged**
