### PR TITLE
python312Packages.onnx: clean up dependencies

### LINKED ISSUE #348847: Build failure: python312Packages.onnx
### Steps To Reproduce

1. build python312Packages.onnx as a part of immich-machine-learning

### Build log

<details>
<summary>Build log</summary>
-- Download and build Abseil from https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz
[ 11%] Creating directories for 'abseil-populate'
[ 22%] Performing download step (download, verify and extract) for 'abseil-populate'
-- Downloading...
   dst='/build/source/.setuptools-cmake-build/_deps/abseil-subbuild/abseil-populate-prefix/src/20230125.3.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz'
-- Retrying...
-- Using src='https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz'
CMake Error at abseil-subbuild/abseil-populate-prefix/src/abseil-populate-stamp/download-abseil-populate.cmake:162 (message):
  Each download failed!

    error: downloading 'https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz' failed
          status_code: 6
          status_string: "Could not resolve hostname"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  shutting down connection #0

          --- LOG END ---
          error: downloading 'https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz' failed
          status_code: 6
          status_string: "Could not resolve hostname"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  shutting down connection #0

          --- LOG END ---
          error: downloading 'https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz' failed
          status_code: 6
          status_string: "Could not resolve hostname"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  shutting down connection #0

          --- LOG END ---
          error: downloading 'https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz' failed
          status_code: 6
          status_string: "Could not resolve hostname"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  shutting down connection #0

          --- LOG END ---
          error: downloading 'https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz' failed
          status_code: 6
          status_string: "Could not resolve hostname"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  shutting down connection #0

          --- LOG END ---
          error: downloading 'https://github.com/abseil/abseil-cpp/archive/refs/tags/20230125.3.tar.gz' failed
          status_code: 6
          status_string: "Could not resolve hostname"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  shutting down connection #0

          --- LOG END ---

make[2]: *** [CMakeFiles/abseil-populate.dir/build.make:100: abseil-populate-prefix/src/abseil-populate-stamp/abseil-populate-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/abseil-populate.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

CMake Error at /nix/store/24gbi6mcw4c6jgzai9aaxx9qi2rxdb09-cmake-3.29.6/share/cmake-3.29/Modules/FetchContent.cmake:1714 (message):
  Build step for abseil failed: 2
Call Stack (most recent call first):
  /nix/store/24gbi6mcw4c6jgzai9aaxx9qi2rxdb09-cmake-3.29.6/share/cmake-3.29/Modules/FetchContent.cmake:1854:EVAL:2 (__FetchContent_directPopulate)
  /nix/store/24gbi6mcw4c6jgzai9aaxx9qi2rxdb09-cmake-3.29.6/share/cmake-3.29/Modules/FetchContent.cmake:1854 (cmake_language)
  CMakeLists.txt:250 (FetchContent_Populate)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/build/source/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 309, in <module>
    setuptools.setup(
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
    self.run_command(cmd)
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
    self.run_command("build")
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "setup.py", line 246, in run
    self.run_command("cmake_build")
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/nix/store/l6vlavpj6wzcihb1qmrh1xh8wh22cmfb-python3.12-setuptools-72.1.0/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "setup.py", line 217, in run
    subprocess.check_call(cmake_args)
  File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/slflwdf69f5x21amc4zac5dpa8gk7kc5-python3.12-cmake-3.29.6/bin/cmake', '-DPYTHON_INCLUDE_DIR=/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/include/python3.12', '-DPYTHON_EXECUTABLE=/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/bin/python3.12', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-312-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '-DONNX_BUILD_TESTS=ON', '-DCMAKE_INSTALL_LIBDIR=lib', '-DONNX_USE_PROTOBUF_SHARED_LIBS=ON', '-Dgoogletest_STATIC_LIBRARIES=/nix/store/m8i80frc3qbb0d9ifh3mvfwkd4yvz790-gtest-1.15.2/lib/libgtest.a', '-Dgoogletest_INCLUDE_DIRS=/nix/store/k7kwvbr8l81wiw3fi5sydpfsylqbniw0-gtest-1.15.2-dev/include', '/build/source']' returned non-zero exit status 1.

</details>

### Additional context

This was triggered as dependency of immich-machine-learning, so currently on the unstable branch of nixpkgs, immich is broken.

### Notify maintainers

@acairncross

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.13, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dotlambda**
fixes https://github.com/NixOS/nixpkgs/issues/348847
closes https://github.com/NixOS/nixpkgs/pull/348873

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Titaniumtown — APPROVED** [review]
This PR also works. I do like the other changes made in this PR as well.

**Review by Titaniumtown — APPROVED** [review]

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 348902` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.tf2onnx</li>
    <li>python311Packages.tf2onnx.dist</li>
    <li>rocmPackages.migraphx</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>rocmPackages_5.mivisionx</li>
    <li>rocmPackages_5.mivisionx-cpu</li>
    <li>rocmPackages_5.mivisionx-hip</li>
    <li>rocmPackages_5.mivisionx-opencl</li>
    <li>rocmPackages_6.migraphx</li>
    <li>rocmPackages_6.mivisionx</li>
    <li>rocmPackages_6.mivisionx-cpu</li>
    <li>rocmPackages_6.mivisionx-hip</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>rocmPackages_5.migraphx</li>
  </ul>
</details>
<details>
  <summary>56 packages built:</summary>
  <ul>
    <li>deface</li>
    <li>deface.dist</li>
    <li>easyocr (python312Packages.easyocr)</li>
    <li>easyocr.dist (python312Packages.easyocr.dist)</li>
    <li>exo</li>
    <li>exo.dist</li>
    <li>immich-machine-learning</li>
    <li>immich-machine-learning.dist</li>
    <li>python311Packages.easyocr</li>
    <li>python311Packages.easyocr.dist</li>
    <li>python311Packages.fastembed</li>
    <li>python311Packages.fastembed.dist</li>
    <li>python311Packages.ffcv</li>
    <li>python311Packages.ffcv.dist</li>
    <li>python311Packages.insightface</li>
    <li>python311Packages.insightface.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.onnx</li>
    <li>python311Packages.onnx.dist</li>
    <li>python311Packages.onnxconverter-common</li>
    <li>python311Packages.onnxconverter-common.dist</li>
    <li>python311Packages.onnxmltools</li>
    <li>python311Packages.onnxmltools.dist</li>
    <li>python311Packages.onnxruntime-tools</li>
    <li>python311Packages.onnxruntime-tools.dist</li>
    <li>python311Packages.pytorch-pfn-extras</li>
    <li>python311Packages.pytorch-pfn-extras.dist</li>
    <li>python311Packages.skl2onnx</li>
    <li>python311Packages.skl2onnx.dist</li>
    <li>python311Packages.sparsezoo</li>
    <li>python311Packages.sparsezoo.dist</li>
    <li>python311Packages.tinygrad</li>
    <li>python311Packages.tinygrad.dist</li>
    <li>python312Packages.fastembed</li>
    <li>python312Packages.fastembed.dist</li>
    <li>python312Packages.insightface</li>
    <li>python312Packages.insightface.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.onnx</li>
    <li>python312Packages.onnx.dist</li>
    <li>python312Packages.onnxconverter-common</li>
    <li>python312Packages.onnxconverter-common.dist</li>
    <li>python312Packages.onnxmltools</li>
    <li>python312Packages.onnxmltools.dist</li>
    <li>python312Packages.onnxruntime-tools</li>
    <li>python312Packages.onnxruntime-tools.dist</li>
    <li>python312Packages.pytorch-pfn-extras</li>
    <li>python312Packages.pytorch-pfn-extras.dist</li>
    <li>python312Packages.skl2onnx</li>
    <li>python312Packages.skl2onnx.dist</li>
    <li>python312Packages.sparsezoo</li>
    <li>python312Packages.sparsezoo.dist</li>
    <li>python312Packages.tinygrad</li>
    <li>python312Packages.tinygrad.dist</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]
Changes LGTM.

Our `onnxruntime` depends on onnx 1.16.0 (see https://github.com/microsoft/onnxruntime/blob/v1.18.1/cmake/deps.txt#L39), while the latest version depends on onnx 1.16.1 (see https://github.com/microsoft/onnxruntime/blob/v1.19.2/cmake/deps.txt#L39)

But as it seems to build it's probably okay.

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 348902`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 14 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.tf2onnx</li>
    <li>python311Packages.tf2onnx.dist</li>
    <li>rocmPackages.migraphx</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>rocmPackages_5.mivisionx</li>
    <li>rocmPackages_5.mivisionx-cpu</li>
    <li>rocmPackages_5.mivisionx-hip</li>
    <li>rocmPackages_5.mivisionx-opencl</li>
    <li>rocmPackages_6.migraphx</li>
    <li>rocmPackages_6.mivisionx</li>
    <li>rocmPackages_6.mivisionx-cpu</li>
    <li>rocmPackages_6.mivisionx-hip</li>
  </ul>
</details>
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>rocmPackages_5.migraphx</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 56 packages built:</summary>
  <ul>
    <li>deface</li>
    <li>deface.dist</li>
    <li>easyocr (python312Packages.easyocr)</li>
    <li>easyocr.dist (python312Packages.easyocr.dist)</li>
    <li>exo</li>
    <li>exo.dist</li>
    <li>immich-machine-learning</li>
    <li>immich-machine-learning.dist</li>
    <li>python311Packages.easyocr</li>
    <li>python311Packages.easyocr.dist</li>
    <li>python311Packages.fastembed</li>
    <li>python311Packages.fastembed.dist</li>
    <li>python311Packages.ffcv</li>
    <li>python311Packages.ffcv.dist</li>
    <li>python311Packages.insightface</li>
    <li>python311Packages.insightface.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.onnx</li>
    <li>python311Packages.onnx.dist</li>
    <li>python311Packages.onnxconverter-common</li>
    <li>python311Packages.onnxconverter-common.dist</li>
    <li>python311Packages.onnxmltools</li>
    <li>python311Packages.onnxmltools.dist</li>
    <li>python311Packages.onnxruntime-tools</li>
    <li>python311Packages.onnxruntime-tools.dist</li>
    <li>python311Packages.pytorch-pfn-extras</li>
    <li>python311Packages.pytorch-pfn-extras.dist</li>
    <li>python311Packages.skl2onnx</li>
    <li>python311Packages.skl2onnx.dist</li>
    <li>python311Packages.sparsezoo</li>
    <li>python311Packages.sparsezoo.dist</li>
    <li>python311Packages.tinygrad</li>
    <li>python311Packages.tinygrad.dist</li>
    <li>python312Packages.fastembed</li>
    <li>python312Packages.fastembed.dist</li>
    <li>python312Packages.insightface</li>
    <li>python312Packages.insightface.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.onnx</li>
    <li>python312Packages.onnx.dist</li>
    <li>python312Packages.onnxconverter-common</li>
    <li>python312Packages.onnxconverter-common.dist</li>
    <li>python312Packages.onnxmltools</li>
    <li>python312Packages.onnxmltools.dist</li>
    <li>python312Packages.onnxruntime-tools</li>
    <li>python312Packages.onnxruntime-tools.dist</li>
    <li>python312Packages.pytorch-pfn-extras</li>
    <li>python312Packages.pytorch-pfn-extras.dist</li>
    <li>python312Packages.skl2onnx</li>
    <li>python312Packages.skl2onnx.dist</li>
    <li>python312Packages.sparsezoo</li>
    <li>python312Packages.sparsezoo.dist</li>
    <li>python312Packages.tinygrad</li>
    <li>python312Packages.tinygrad.dist</li>
  </ul>
</details>

**Pull request merged**
