### PR TITLE
rewind-ai: init at 1.5284-15284.1-dcd0176-20240504

### PR DESCRIPTION
**Pull request by 4evy**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by paparodeo — COMMENTED** [review]
a few minor comments:

- using `finalAttrs.pname` in the script is not correct as the package attribute name and paths will not change if pname is overridden, which will then cause things to break.
- the attriburtes parts, build_number and commit_hash don't need to be part of the derivation
- xmlstarlet can extract values from the xml using a path which can be easier to read then regular expressions
- awk can be used to get the commitHash from the url by splitting the url at `-` and `.` and taking the 2nd to last entry
- i am not sure, but i don't think there is a guarantee that the update script will run at the root of nixpkgs

<details><summary>suggested-changes.diff</summary>

```diff
diff --git a/pkgs/by-name/re/rewind-ai/package.nix b/pkgs/by-name/re/rewind-ai/package.nix
index f77230cc5f2b..e112909131f9 100644
--- a/pkgs/by-name/re/rewind-ai/package.nix
+++ b/pkgs/by-name/re/rewind-ai/package.nix
@@ -3,10 +3,10 @@
   stdenvNoCC,
   fetchzip,
   writeShellApplication,
-  curl,
-  gnugrep,
-  gnused,
   common-updater-scripts,
+  curl,
+  gawk,
+  xmlstarlet,
 }:
 
 stdenvNoCC.mkDerivation (finalAttrs: {
@@ -17,16 +17,13 @@ stdenvNoCC.mkDerivation (finalAttrs: {
   # dcd0176 (commit hash)
   # 20240504 (pub date)
   version = "1.5284-15284.1-dcd0176-20240504";
-  parts = lib.filter (part: part != "") (
-    lib.concatLists (
-      map (part: if builtins.isList part then part else [ part ]) (builtins.split "-" finalAttrs.version)
-    )
-  );
-  build_number = builtins.elemAt finalAttrs.parts 1;
-  commit_hash = builtins.elemAt finalAttrs.parts 2;
 
   src = fetchzip {
-    url = "https://updates.rewind.ai/builds/main/b${finalAttrs.build_number}-main-${finalAttrs.commit_hash}.zip";
+    url = let
+      buildNumber = lib.elemAt (lib.splitString "-" finalAttrs.version) 1;
+      commitHash  = lib.elemAt (lib.splitString "-" finalAttrs.version) 2;
+    in
+      "https://updates.rewind.ai/builds/main/b${buildNumber}-main-${commitHash}.zip";
     hash = "sha256-Y7iAYHH/msZoXFzAZHJb6YoDz5fwMPHJx1kg7TqP5Gw=";
   };
 
@@ -44,27 +41,31 @@ stdenvNoCC.mkDerivation (finalAttrs: {
   # Wait at least 3 days since the last pub_date (you will find the date at the end of the version number)
   # Example: 20240504 would be 2024/05/04, and that would mean that we want to check no earlier than on 2024/05/07 for any updates
   passthru.updateScript = lib.getExe (writeShellApplication {
-    name = "${finalAttrs.pname}-update-script";
+    name = "rewind-ai-update-script";
     runtimeInputs = [
-      curl
-      gnugrep
-      gnused
       common-updater-scripts
+      curl
+      gawk
+      xmlstarlet
     ];
     text = ''
+      xml_get () {
+          echo "$update_xml" | xmlstarlet sel -t -v "$1"
+      }
+
       update_url="https://updates.rewind.ai/appcasts/main.xml"
 
       update_xml=$(curl -s "$update_url")
 
-      version_base=$(echo "$update_xml" | grep -oP '(?<=<sparkle:shortVersionString>)[^<]+')
-      url=$(echo "$update_xml" | grep -oP '(?<=enclosure url=").+?(?=")')
-      pub_date=$(echo "$update_xml" | grep -oP '(?<=<pubDate>)[^<]+')
-      commit_id=$(echo "$url" | sed -n 's~.*/b[0-9.]*-main-\([a-zA-Z0-9._-]*\)\.zip~\1~p')
-      build_number=$(echo "$url" | sed -n 's~.*/b\([0-9.]*\)-main-.*\.zip~\1~p')
+      version_base=$(xml_get "/rss/channel/item/sparkle:shortVersionString")
+      url=$(xml_get "/rss/channel/item/enclosure/@url")
+      pub_date=$(xml_get "/rss/channel/item/pubDate")
+      commit_id=$(echo "$url" | awk -F '-|\\.' '{ print $(NF - 1) }')
+      build_number=$(xml_get "/rss/channel/item/sparkle:version")
       formatted_pub_date=$(date -d "$pub_date" +"%Y%m%d")
 
       full_version="''${version_base}-''${build_number}-''${commit_id}-''${formatted_pub_date}"
-      update-source-version "${finalAttrs.pname}" "$full_version" --version-key=version --file=./pkgs/by-name/re/${finalAttrs.pname}/package.nix --print-changes
+      update-source-version "rewind-ai" "$full_version" --version-key=version --file=./pkgs/by-name/re/rewind-ai/package.nix --print-changes
     '';
   });
 
```

**Comment by DontEatOreo** [comment]
Thanks a lot for the review and suggestions! I just have a question about the `xml_get()` part. Will calling that function make `curl` fetch that URL each time it's called, or will it use the initially set variable? I'm asking this since as described in the comment above, the `updateScript` has a very harsh limit on update checks, so ideally, we only ever want to call it once.

**Comment by DontEatOreo** [comment]
> i am not sure, but i don't think there is a guarantee that the update script will run at the root of nixpkgs

I also did test the `updateScript` with your suggestions with `nix-shell ./maintainers/scripts/update.nix` and it works!

**Comment by paparodeo** [comment]
> Thanks a lot for the review and suggestions! I just have a question about the `xml_get()` part. Will calling that function make `curl` fetch that URL each time it's called, or will it use the initially set variable?

it will use the set variable so curl is only called once.

**Review by paparodeo — APPROVED** [review]

**Pull request merged**
