### PR TITLE
ghc: add 8.8.4 (copied from 8.8.3)

### PR DESCRIPTION
**Pull request by ggreif**
###### Motivation for this change

https://www.haskell.org/ghc/blog/20200715-ghc-8.8.4-released.html

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build haskell.compiler.ghc884

**Review by peti — APPROVED** [review]
:+1:

**Comment by cdepillabout** [comment]
@ggreif Thanks for always sending these GHC updates.

I was able to build `haskell.compiler.ghc884`, as well as `haskell.packages.ghc884.lens` on my x86 NixOS system, so I think this should be good to be merged in.

Once you take it off `Draft`, ping me and I'll merge it in.

Also, would you be willing to backport this to the `release-20.03` branch?

**Comment by ggreif** [comment]
@cdepillabout I have taken this out of draft. I'll look for an example of a `20.03` backport and follow on.

@peti Enjoy your vacation.

**Pull request merged**
