### PR TITLE
Mptcp kernel updates

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change
0.94 was updated twice and 0.95 branch was released yesterday https://github.com/multipath-tcp/mptcp/releases/tag/v0.95

I did some cleanup (added a shared structured config)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
@layus

**Review by layus — APPROVED** [review]
Eyeballed the code, LGTM.

**Comment by layus** [comment]
It would be nice if we could have a simple nixos test for mptcp.

I have it mostly working, but for some reason mptcp is not detected by amiusingmptcp.de

here is my code

```nix
# mptcp.nix

{pkgs, ...}:
{
  imports = [ ./minimal.nix ];

  boot.kernelPackages = pkgs.linuxPackages_mptcp;

  environment.systemPackages = [
    pkgs.jshon
    pkgs.curl
  ];
  programs.bash.interactiveShellInit = with pkgs; ''
    amiusingmptcp() { ${curl.bin}/bin/curl 'http://amiusingmptcp.de/v1/check_connection' -qs | ${jshon}/bin/jshon -e proc -e mptcp; }
  '';

  virtualisation.qemu.networkingOptions = [
    # Replace virtio, otherwise mptcp is bypassed
    "-nic user,model=e1000"
    #"-net nic,netdev=user.0,model=virtio"
    #"-netdev user,id=user.0\${QEMU_NET_OPTS:+,$QEMU_NET_OPTS}"
  ];
}
```

```nix
# ./minimal.nix

{pkgs, lib, ...}:
{
  # Allow ssh
  services.openssh.enable = true;

  # Setup ssh key for root
  users.mutableUsers = false;
  users.extraUsers.root.password = "root";
  users.extraUsers.root.openssh.authorizedKeys.keyFiles = [
    ~/.ssh/id_ecdsa.pub
  ];

  #programs.zsh.enable = true;
  #users.defaultUserShell = "/var/run/current-system/sw/bin/zsh";

  # Disable X libs as this is a headless server
  environment.noXlibs = lib.mkDefault true;

  environment.systemPackages = [ pkgs.rxvt_unicode.terminfo ];

  # Define keymap for Qemu
  i18n = {
    consoleFont = "lat9w-16";
    consoleKeyMap = "be-latin1";
    defaultLocale = "en_US.UTF-8";
  };
}
```

```sh
nix-build ../nixpkgs/nixos -A vm -Q -I nixos-config=$PWD/mptcp.nix --show-trace
```

The issue is most probably with the `virtualisation.qemu.networkingOptions` where we need a proper interface emulation for mptcp to kick in.
If you manage to get this working, we would at least get some confidence that everything is working.

At the moment, I can affirm that your PR builds a working linux kernel :-).

**Comment by teto** [comment]
oh that's great ! I've wanted to write a test for a long time but I can't get the time.
https://github.com/NixOS/nixpkgs/pull/59342 might force me to. 

curling ttp://amiusingmptcp.de might not be reliable enough as proxies/middleboxes can block MPTCP. That's maybe what happens in your case ? You could check your network with tracebox (a UCL software).

**Comment by teto** [comment]
to check I would be thinking of capturing MPTCP traffic with tshark (which has `mptcp` filter).

**Comment by teto** [comment]
Merging this. Currently writing a test for nixos.

**Comment by layus** [comment]
> curling ttp://amiusingmptcp.de might not be reliable enough as proxies/middleboxes can block MPTCP. That's maybe what happens in your case ? You could check your network with tracebox (a UCL software).

It already dropped all mptcp headers when reaching eth0. It is most probably linked to qemu netdev emulation. I know for sure that virtio does not work (obviously) but the commands have changed since my last test years ago.

**Pull request merged**
