### PR TITLE
libvarlink: init at 22

### LINKED ISSUE #131750: libvarlink: varlink impl in C
**Project description**

https://github.com/varlink/libvarlink

Kanshi uses it now, by default, it'd be good if we had it in nixpkgs.

**Metadata**

* homepage URL: https://github.com/varlink/libvarlink
* source URL: https://github.com/varlink/libvarlink
* license: APL2
* platforms: linux (??)

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
Closes #131750

###### Things done

Should i mess with `outputs`? 
Package structure
```tree
 tree result
result
├── bin
│   └── varlink
├── include
│   └── varlink.h
├── lib
│   ├── libvarlink.so -> libvarlink.so.0
│   ├── libvarlink.so.0
│   └── pkgconfig
│       └── libvarlink.pc
└── share
    ├── bash-completion
    │   └── completions
    │       └── varlink
    └── vim
        └── vimfiles
            └── after
                ├── ftdetect
                │   └── varlink.vim
                ├── ftplugin
                │   └── varlink.vim
                └── syntax
                    └── varlink.vim
```

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by blitz** [comment]
I would also suggest:

```nix
  passthru = {
    updateScript = nix-update-script {
      attrPath = pname;
    };

    tests = {
      version = testVersion {
        package = libvarlink;
        command = "varlink --version";
      };
    };
  };
```

**Review by blitz — APPROVED** [review]
Looks good. :+1: for enabling the tests. See my comment about allowing auto-updates and adding a version test.

**Comment by Artturin** [comment]
the package already has its own tests and r-ryantm updates packages withhout a passthru too https://github.com/NixOS/nixpkgs/pull/130908

**Comment by blitz** [comment]
> the package already has its own tests and r-ryantm updates packages withhout a passthru too #130908

The update via repology metainformation only works if other repos package the update first. Are you aware of any "Best Practices" around update script usage?

Regarding the test: How would anything know what binary to execute to do the version check?

**Comment by Artturin** [comment]
> Regarding the test: How would anything know what binary to execute to do the version check?

https://github.com/ryantm/nixpkgs-update/blob/6bf8249627dea7c0dc4a6127e0fea5e553866374/src/Check.hs#L101

> The update via repology metainformation only works if other repos package the update first. Are you aware of any "Best Practices" around update script usage?

i asked ryantm
screenshot_2021-07-31_18-14-55_653906170

**Pull request merged**
