### PR TITLE
cachix: 1.7 -> 1.7.3

### PR DESCRIPTION
**Pull request by domenkozar**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by maralorn — APPROVED** [review]

**Comment by drupol** [comment]
Do you know if this PR is the reason of the new builds failure at https://hydra.nixos.org/build/260099410 ?

**Comment by maralorn** [comment]
Sounds likely. That is exactly why we prefer changes to Haskell packages to go haskell-updates.

**Comment by drupol** [comment]
@maralorn Is there anything I can do to fix the build failure?

**Comment by sternenseemann** [comment]
Revert the PR.

**Comment by drupol** [comment]
> Revert the PR.

OK, I'll ask it differently. Is there anything I can do to fix the issue and avoid reverting?

**Comment by maralorn** [comment]
Well I think this will need a patch for hercules-ci to become cachix 1.7.3 compatlble. I don’t see an issue about that here: https://github.com/hercules-ci/hercules-ci-agent
We can ask @roberth nicely if he can provide a fix quickly, but being asked for a patch while master is already being blocked by your build failure without any prior notice is certainly not pleasant.

**Comment by drupol** [comment]
@roberth Let me know if you prefer to revert this instead and I'll take care of it tomorrow morning.

**Comment by domenkozar** [comment]
Uhh, my bad. I'll add hercules-ci to the release notes for testing and make a patch tomorrow morning.

**Comment by maralorn** [comment]
Small correction. Apparently this is not a channel blocker like I said before.

**Comment by roberth** [comment]
Master builds with 1.7.3. I'm making a release.

**Comment by roberth** [comment]
Actually agent 0.10.2 should also build with cachix 1.7.3, but 0.10.3 and its deps have stability improvements.
Should we update those now? `haskell-updates` is about 4 days young, so I don't suppose we want to wait for that.

**Pull request merged**
