### PR TITLE
nixosTests.fancontrol: fix test; clean up module

### PR DESCRIPTION
**Pull request by evils**
###### Motivation for this change
ZHF: #122042
@NixOS/nixos-release-managers

###### Things done

fix test by not waiting for the service (the service is not expected to keep running, can't do a fancontrol config for a VM?)
clean up module (added `lm_sensors` group and `fancontrol` user, removed default config (a config is required, no default can be guessed))
added myself as maintainer to both the test and the module

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
LGTM

```
[nix-shell:~/.cache/nixpkgs-review/pr-122074]$ nix-build ./nixpkgs/ -A nixosTests.fancontrol
/nix/store/j99i7i1by3bxv1nlhhd02ndgyc5k8v4y-vm-test-run-fancontrol
```

**Comment by mlvzk** [comment]
This new `User` and `Group` setting broke my configuration. It was failing with `Error: file hwmon3/pwm1 doesn't exist`

**Comment by evils** [comment]
i get similar failures once in a while
especially on kernel changes
i suspect there's something making the available end-points (`hwmon3/pwm1` in this case) not very stable
so far i've been able to get around it by either trying nixos-rebuild again, or going through `pwmconfig` again

i don't think it's due to the user & group stuff
but it is an issue i've encountered sporadically

**Comment by jonringer** [comment]
could be that there should be another `users.users.fancontrol` and related group entry. Just to ensure that those uid and gid get generated.

**Comment by evils** [comment]
hmm, turns out i was just running with a broken fancontrol service...
i'm investigating further
currently i suspect it's lacking access to the `/sys/devices` endpoints it uses to control stuff

*shudders at the discovery this is just bash scripts*

**Comment by evils** [comment]
@mlvzk i've opened #123324 to revert that breaking change, thanks for pointing it out

**Pull request merged**
