### PR TITLE
 linux: allow for interpreter to be truncated

### PR DESCRIPTION
**Pull request by eadwu**
###### Motivation for this change
Now just give me a few hours to compile using this specific patch taken from the git repository instead of my own.

Based off https://github.com/NixOS/nixpkgs/pull/55763, though I don't think `linux_testing_bcachefs` needs to be patched, as it's still based upon 4.20.0.

Resolves https://github.com/NixOS/nixpkgs/issues/53672.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @NeQuissimus @grahamc @dtzWill

### CODE REVIEW

**Review by NeQuissimus — APPROVED** [review]

**Comment by eadwu** [comment]
`4.20.8` boots and `nixos-rebuild switch` runs fine for me.

**Comment by grahamc** [comment]
@NeQuissimus would you like to backport to 18.09 as well?

**Comment by NeQuissimus** [comment]
On it

**Comment by NeQuissimus** [comment]
9c78f68e2889f8f3f85c98d86f91dc0d36465522 c4b10f83476029bc9095c66244f12b43780d3b00

**Comment by NeQuissimus** [comment]
hmm, there are old kernels in stable, I have to try them out

**Comment by grahamc** [comment]
The kernel bumps were reverted on stable

**Comment by NeQuissimus** [comment]
I think I have it all figured out now

**Pull request merged**
