### PR TITLE
qtwebkit: fix build for darwin x86

### PR DESCRIPTION
**Pull request by willcohen**
###### Motivation for this change

`qtwebkit` has been broken on hydra for a while: https://hydra.nixos.org/build/165378793

It appears to have been fixed with https://github.com/qtwebkit/qtwebkit/issues/976

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by willcohen** [comment]
Queueing up a test with `nixpkgs-review` locally.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 156809` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages marked as broken and skipped:</summary>
  <ul>
    <li>brewtarget</li>
    <li>cb2bib</li>
    <li>foxitreader</li>
    <li>goldendict</li>
    <li>libsForQt5.full</li>
    <li>libsForQt5.qt5.qtwebkit</li>
    <li>libsForQt514.full</li>
    <li>libsForQt514.qt5.qtwebkit</li>
    <li>libsForQt515.full</li>
    <li>libsForQt515.qt5.qtwebkit</li>
    <li>lsd2dsl</li>
    <li>phantomjs2</li>
    <li>python310Packages.pyqt5_with_qtwebkit</li>
    <li>python39Packages.pyqt5_with_qtwebkit</li>
    <li>sleepyhead</li>
  </ul>
</details>

**Comment by willcohen** [comment]
Result of `nixpkgs-review pr 156809` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt514.full</li>
    <li>libsForQt515.full</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>brewtarget</li>
    <li>foxitreader</li>
    <li>goldendict</li>
    <li>libsForQt5.full</li>
    <li>python310Packages.pyqt5_with_qtwebkit</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>cb2bib</li>
    <li>libsForQt5.qt5.qtwebkit</li>
    <li>libsForQt514.qt5.qtwebkit</li>
    <li>libsForQt515.qt5.qtwebkit</li>
    <li>lsd2dsl</li>
    <li>phantomjs2</li>
    <li>python39Packages.pyqt5_with_qtwebkit</li>
    <li>sleepyhead</li>
  </ul>
</details>

**Comment by willcohen** [comment]
@siraben are those breakages on arch related to this? I’m inclined to still suggest merging since at least it unbreaks on x86.

**Comment by willcohen** [comment]
Mentioning @prusnak and @veprbl as this is not dissimilar in spirit to #150293.

**Comment by prusnak** [comment]
> @siraben are those breakages on aarch64 related to this?

Essentially the whole Qt is broken on aarch64-darwin at the moment. Not related to this PR.

**Comment by willcohen** [comment]
@veprbl I know that the build just timed out, so at the least I can offer that this branch rebased to master still results in:
```
$ nix-build $NIXPKGS -A qt512.qtwebkit      
/nix/store/ympd68208zsp7ckpd6y0ybcccmm6wa96-qtwebkit-5.212.0-alpha4
```

**Comment by willcohen** [comment]
Many thanks!

**Pull request merged**
