### PR TITLE
environment: add qt6 plugin prefix to profileRelativeSessionVariables

### PR DESCRIPTION
**Pull request by NickCao**
###### Description of changes
This helps qt 6 to find plugins (imput methods, for example) installed in profiles. We patched qt 5 to derive plugin paths from PATH for the same thing.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
A better approach might be adding this to the qt app wrapper, together with the removal of qt 4, would eliminate QT_PLUGIN_PATH from the global variables.

**Comment by NickCao** [comment]
cc @milahu @ttuegel

**Review by ttuegel — CHANGES_REQUESTED** [review]
> We patched qt 5 to derive plugin paths from PATH for the same thing.

This was a horrible mistake that has caused nothing but pain. We should make sure that Qt 6 packages are pure.

**Comment by NickCao** [comment]
> This was a horrible mistake that has caused nothing but pain. We should make sure that Qt 6 packages are pure.

However input methods is a thing crucial to those who need it, and without a unified API for them, Qt plugins is the only way to make them work. Qt do have support for ibus bundled, but for the rest like fcitx5, there's no such luck. Another choice can be adding these as a dep of wrapQtAppsHook, given that they normally have a small closure size.

**Comment by ttuegel** [comment]
> However input methods is a thing crucial to those who need it, and without a unified API for them, Qt plugins is the only way to make them work.

Input methods won't even work as plugins: every time there is a new Qt release, this will break every installed program. As a temporary measure to get fcitx working, you could add that plugin _only_ to `QT_PLUGIN_PATH` when fcitx is enabled.

**Comment by NickCao** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/174218 as a temporary fix.

**Pull request closed without merging**
