### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thefloweringash** [comment]
Darwin stdenv seems broken:
```
❯ nix-build https://github.com/nixos/nixpkgs/archive/staging-next.tar.gz -A stdenv
[...]
output '/nix/store/3j0j0i9n8dqi8pj8zn73mc62708rakj5-bootstrap-stage2-stdenv-darwin' is not allowed to refer to the following paths:
  /nix/store/qvv2xw5da22lfgbj1zq4hhvh286i74f7-brotli-1.0.9-lib
error: build of '/nix/store/hx3521a727a73g127garwgxxrwqlp3r5-bootstrap-stage2-stdenv-darwin.drv' on 'ssh://illumination@flash.cons.org.nz' failed: output '/nix/store/3j0j0i9n8dqi8pj8zn73mc62708rakj5-bootstrap-stage2-stdenv-darwin' is not allowed to refer to the following paths:
  /nix/store/qvv2xw5da22lfgbj1zq4hhvh286i74f7-brotli-1.0.9-lib
builder for '/nix/store/hx3521a727a73g127garwgxxrwqlp3r5-bootstrap-stage2-stdenv-darwin.drv' failed with exit code 1
```

PR here: #115498

**Comment by FRidh** [comment]
aarch64 blocker https://hydra.nixos.org/build/138750030

**Comment by mweinelt** [comment]
manual waiting for werkzeug fix. https://github.com/NixOS/nixpkgs/pull/115564.

**Comment by FRidh** [comment]
modemmanager failure related to libqmi-glib
```
configure: error: Couldn't find libqmi-glib >= 1.26.0. Install it, or otherwise configure using --without-qmi to disable QMI support.
builder for '/nix/store/ck5mfd3n51mqlmclv206ids1ll1daiiy-modem-manager-1.14.10.drv' failed with exit code 1
```
https://hydra.nixos.org/build/138722971 cc @jtojnar

**Comment by jtojnar** [comment]
Sorry about that, did not realize this is already in staging-next so only pushed the fix to staging https://github.com/NixOS/nixpkgs/commit/6eed4a89f6feaa0797418626619562ec287c7ed6.

**Comment by FRidh** [comment]
urllib3 tests disabled entirely. Upstream recognizes they are flaky, not much we can do about it.

Note we don't have any urllib3 for Python 2 anymore, and thus nixops does not build.

**Comment by FRidh** [comment]
Overriding pytest (or pytestCheckHook) broke the Python 2 builds of packages, because they now get an incompatible version.

**Comment by FRidh** [comment]
go 1.16 build failure blocks staging-next https://hydra.nixos.org/build/138728621
cc @NixOS/golang

**Comment by tomberek** [comment]
How does one determine/decide if the staging-next branch is "deemed of sufficiently high quality" per RFC?

**Comment by FRidh** [comment]
RFC does not define any criteria.
Typically, what is checked is:
- https://hydra.nixos.org/job/nixpkgs/staging-next/unstable is green
- amount of failures < N, where N can change over time as the set grows. Looking at last month, the failures were at best around 4000.
- if more failures, there are likely important failures in one or more of the sub package sets

NixOS is unfortunately not tested on Hydra.

**Comment by FRidh** [comment]
cc @NixOS/darwin-maintainers @r-burns libtiff seems to fail on darwin. https://hydra.nixos.org/build/138840562

**Comment by thefloweringash** [comment]
> cc @NixOS/darwin-maintainers @r-burns libtiff seems to fail on darwin. https://hydra.nixos.org/build/138840562

Quick PR: https://github.com/NixOS/nixpkgs/pull/116520

**Comment by bobrik** [comment]
LAPACK fix for Darwin: #116579.

**Comment by vcunat** [comment]
(x86_64-)darwin is suffering from a mass regression due to [python38Packages.lxml](https://hydra.nixos.org/build/138859711)

**Comment by Kloenk** [comment]
> (x86_64-)darwin is suffering from a mass regression due to [python38Packages.lxml](https://hydra.nixos.org/build/138859711)

Got a potential fix over on the apple-silicon branch. Not worked on/with x86 yet, so also did not test it on x86. If I understand it correctly MacOSX-SDK has to be replaced with just sdk, but I'm not sure. 

https://github.com/Kloenk/nixpkgs/commit/d14cd7b237fc878f9fab44506291b26e11b1765e

**Comment by bobrik** [comment]
#116669 fixes `python38Packages.lxml`.

**Comment by FRidh** [comment]
There are still many failures for darwin. Please check https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents for the most important ones to fix.

**Pull request merged**
