### PR TITLE
citra: update to 2020-03-28

### PR DESCRIPTION
**Pull request by marius851000**
###### Motivation for this change
A recent update to citra added some interesing functionallity for rom-hacking (dynamic patch to the game file system)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Checked it work with some game and homebrew, including testing the specific part I need.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by rnhmjoj — CHANGES_REQUESTED** [review]
This need to be wrapped with `wrapQtAppsHook`. See this issue for details #65399 
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by petabyteboy** [comment]
I would suggest to go ahead with the update as it doesn't make the situation worse than before. I would open a new PR to fix the wrapping issue then.

**Comment by marius851000** [comment]
I will try to use wrapQtAppsHook. Sorry for not having noticied the older PR. Will commit once it finish compiling.

**Comment by marius851000** [comment]
I added wrapQtAppsHook in nativeBuildInputs, and I didn't see any difference. So I'm totally ok to let @petabyteboy do what he need with this, and accept this PR as is.

**Comment by rnhmjoj** [comment]
PR #83193 fixes the issue with Qt and appears to have been well tested. The fact it's building a slightly older revision is probably not important, so unless you are against I'm going to merge that one.

**Comment by marius851000** [comment]
I'm totally okay about you merging the older update @rnhmjoj (this revision also have the function I'm looking for).

**Comment by rnhmjoj** [comment]
Thank you, I merged the other PR an will do a backport soon.

**Pull request closed without merging**
