### PR TITLE
haskellPackages.kmonad: mark as broken on darwin

### PR DESCRIPTION
**Pull request by slotThe**
## Description of changes

Related: https://github.com/NixOS/nixpkgs/pull/304640

I don't have access to MacOS, so I don't know how to actually test this (help? :)), but the error seemed obvious enough.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
Darwin specific overrides should go to `configuration-darwin.nix` which is unconditionally applied there.

**Comment by sternenseemann** [comment]
This change does appear to result in a linker failure on darwin.

**Comment by slotThe** [comment]
Well that's very confusing… I suppose wrt https://github.com/NixOS/nixpkgs/pull/304640 we can just mark this package as broken on darwin for the time being.

**Comment by slotThe** [comment]
@sternenseemann since I don't really have a way to test this, the sanest solution seems to be to just mark the package as broken on darwin for now.

**Comment by maralorn** [comment]
wfm

**Comment by sternenseemann** [comment]
Technically, it supports darwin… we just haven't set it up right.

**Comment by maralorn** [comment]
Yeah, the old semantic struggle that we can’t trivially mark packages broken based on platform …

**Pull request merged**
