### PR TITLE
Extract files one at a time from all-cabal-hashes

### PR DESCRIPTION
**Pull request by ElvishJerricco**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
@shlevy Didn't know if I should update `all-cabal-hashes` along with this, so I left it at the version it was at in `release-17.03`.

**Comment by grahamc** [comment]
Hmmm a PR to release-17.03? 17.03 hasn't been supported for 4 months now.

**Comment by ElvishJerricco** [comment]
Just acting on this request: https://github.com/NixOS/nixpkgs/pull/31333#issuecomment-351451030

**Comment by shlevy** [comment]
@grahamc Is it a problem to merge things back so long as users know they have to do the work themselves to keep it secure and up-to-date?

**Comment by grahamc** [comment]
Hmm not sure. Has any attempt been made to ensure the requester knows 17.03
is no longer supported?

**Comment by shlevy** [comment]
@grahamc I told them when I worked there 😉

**Comment by ElvishJerricco** [comment]
Will this be merged?

**Comment by orivej** [comment]
@mightybyte Do you need this? Could you share a bit on why you'd rather not switch to 17.09?

**Comment by shlevy** [comment]
@ElvishJerricco Is Takt aware that 17.03 is unmaintained and may miss critical security updates if they don't support them themselves? If so then I think we can merge your changes.

**Comment by ElvishJerricco** [comment]
@mightybyte thoughts?

**Comment by mightybyte** [comment]
Yes, this would be very useful for us.  Switching to 17.09 has not proven to be trivial.  Also, less than a year of official support for major releases is not great when it comes to supporting mission-critical codebases.

**Pull request merged**
