### PR TITLE
fq: 0.0.4 -> 0.0.6

### PR DESCRIPTION
**Pull request by siraben**
###### Description of changes
https://github.com/wader/fq/pull/189

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 165213` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>fq</li>
  </ul>
</details>

**Comment by siraben** [comment]
@wader build failure with log

```
Building subPackage ./dev
text/template/parse
text/template
github.com/wader/fq/dev
# github.com/wader/fq/dev
dev/tmpl.go:36:6: main redeclared in this block
        /private/tmp/nix-build-fq-0.0.6.drv-0/source/dev/fuzzbytes.go:12:6: previous declaration
```

**Comment by wader** [comment]
> @wader build failure with log
> 
> ```
> Building subPackage ./dev
> text/template/parse
> text/template
> github.com/wader/fq/dev
> # github.com/wader/fq/dev
> dev/tmpl.go:36:6: main redeclared in this block
>         /private/tmp/nix-build-fq-0.0.6.drv-0/source/dev/fuzzbytes.go:12:6: previous declaration
> ```

Could it be that nix builds packages `./...` (all sub packages)? possible to change it to just build `.`? There are some go-files in `dev` and `doc` that are dev-time tools and example code so not used to at build-time. I guess in the current 0.0.4 build a `dev` binary will gets built also as there was only one go-file with a main function in the dev-directory?

Alternatively we could add ignore build tag somehow but could maybe be a bit inconvenient with IDE:s etc.

Any other possibilites?

**Comment by wader** [comment]
And thanks for updating the nix package!

**Comment by siraben** [comment]
@wader fixed

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 165213` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fq</li>
  </ul>
</details>

**Comment by wader** [comment]
🥳   think `.` should be fine, don't think i will producing additional executables anytime soon :)

**Pull request merged**
