### PR TITLE
xstatic-jquery-ui: 1.11.0.1 -> 1.12.0.1

### PR DESCRIPTION
**Pull request by makefu**
###### Motivation for this change

Fix security vulnerability in package, in accordance with #21142

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [NA] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Huh ... that is it? I didn't do it, out of fear of dependency hell :P

**Comment by Mic92** [comment]
Thanks!

**Comment by Mic92** [comment]
maybe this is also required in the release branch?

**Comment by grahamc** [comment]
I'll cherry-pick shortly

**Comment by makefu** [comment]
@grahamc only bepasty-server depends on xstatic-jquery-ui.
I tested building and executing bepasty-server and the webui worked fine (web console showed no issues). Also, i checked if the correct jquery-ui file gets send by the server.

Not sure if jquery-ui is bundled in other nix packages though ;)

**Pull request merged**
