### PR TITLE
radarr: 0.2.0.1504 -> 3.0.2.4552

### PR DESCRIPTION
**Pull request by andreisergiu98**
Inspired by https://github.com/NixOS/nixpkgs/pull/105356. I also changed the license to  gpl3-only, since I didn't find any note specifying version 3 or later being used.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by purcell — CHANGES_REQUESTED** [review]
This breaks Darwin support unfortunately:
```
./result/bin/Radarr
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/nix/store/qq2adyldcdzcbllmhyqg4mvn21vmgwv7-radarr-3.0.2.4552/share/radarr-3.0.2.4552/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, specify the appropriate framework in /nix/store/qq2adyldcdzcbllmhyqg4mvn21vmgwv7-radarr-3.0.2.4552/share/radarr-3.0.2.4552/Radarr.runtimeconfig.json.
```
The previous revision worked fine. Unsure how to resolve the issue though sorry.

**Comment by andreisergiu98** [comment]
I think it's working now, but I had to drop i686.

**Comment by purcell** [comment]
Yeah, that starts up on Darwin now. No idea how to judge whether it's best in the long term to go for the platform-specific binaries or mono though, particularly with regard to automatically-created version-update PRs.

**Comment by andreisergiu98** [comment]
Your concerns did bother me too. I will make some tests to see if the mono build is still working, if it is should I create a different PR?

I was thinking of other ways to circumvent this and I think we could:
- build from source - I don't really know how to do it yet :))), and I don't know if there are other downsides to this besides making the definition more complex, which is reason enough not to do it.
- standard multi release definitions - I was thinking maybe we could create a standard way to fetch multiple releases, one that could be picked up by the bot.

**Comment by purcell** [comment]
I can't really say what would be best. Perhaps @ryantm has some thoughts, since his bot is often the one making updates to these derivations.

**Comment by ryantm** [comment]
Generally we prefer to build from src if possible, even if it makes the derivation more complicated. 

As for the updates, the standard way to deal with derivations like that is to make a `passthrough.updateScript` and then r-ryantm will call that when trying to update it.

**Comment by purcell** [comment]
Makes sense, thanks @ryantm.

**Comment by andreisergiu98** [comment]
I ended up using `updateScript`. The NuGet made building from source complicated and I found it easier to create a script.
I looked up how other packages are using it, and came up with this. I am not entirely sure if it's working and I couldn't test this part `currentVersion=$(nix eval --raw '(with import ../../.. {}; radarr.version)')`.

I also tested the mono build, it's working for now, but same with Jackett there is a persistent deprecation warning.

**Comment by SuperSandro2000** [comment]
Please squash the commits together.

**Comment by andreisergiu98** [comment]
Done! I squashed commits together and I installed nix on my system so I could test the script. It updates the derivation correctly. 

@ryantm so after the script modifies the derivation **r-ryantm** will handle everything else right? I am asking because I found some scripts that also created commit messages.

I think this should be everything. Merge? :D

**Pull request merged**
