### PR TITLE
python3Packages.shamir-mnemonic: 0.1.0 -> 0.2.0

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- version update
- included also smaller cleanup of the cousin mnemonic package

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 1000101** [comment]
@GrahamcOfBorg build pythonPackages.shamir-mnemonic python3Packages.mnemonic

**Comment by 1000101** [comment]
@GrahamcOfBorg build pythonPackages.shamir-mnemonic pythonPackages.mnemonic

**Comment by 1000101** [comment]
@GrahamcOfBorg build python3Packages.shamir-mnemonic python3Packages.mnemonic

**Comment by prusnak** [comment]
@GrahamcOfBorg build python3Packages.shamir-mnemonic python3Packages.mnemonic

**Comment by prusnak** [comment]
@GrahamcOfBorg build pythonPackages.mnemonic

**Comment by 1000101** [comment]
Result of `nixpkgs-review pr 111741` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>electron-cash</li>
    <li>electrum</li>
    <li>electrum-ltc</li>
    <li>hwi (python38Packages.hwi)</li>
    <li>keepkey_agent (python38Packages.keepkey_agent)</li>
    <li>ledger_agent (python38Packages.ledger_agent)</li>
    <li>python37Packages.hwi</li>
    <li>python37Packages.keepkey</li>
    <li>python37Packages.keepkey_agent</li>
    <li>python37Packages.ledger_agent</li>
    <li>python37Packages.libagent</li>
    <li>python37Packages.mnemonic</li>
    <li>python37Packages.shamir-mnemonic</li>
    <li>python37Packages.trezor</li>
    <li>python37Packages.trezor_agent</li>
    <li>python38Packages.keepkey</li>
    <li>python38Packages.libagent</li>
    <li>python38Packages.mnemonic</li>
    <li>python38Packages.shamir-mnemonic</li>
    <li>python38Packages.trezor</li>
    <li>trezor_agent (python38Packages.trezor_agent)</li>
    <li>python39Packages.keepkey</li>
    <li>python39Packages.mnemonic</li>
    <li>python39Packages.shamir-mnemonic</li>
    <li>python39Packages.trezor</li>
  </ul>
</details>

**Review by 1000101 — APPROVED** [review]

**Pull request merged**
