### PR TITLE
ventoy-bin: 1.0.51 -> 1.0.56

### PR DESCRIPTION
**Pull request by lxwntr**
Version bump

Closes #138094
Closes #141548

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
I have mixed feelings about removing the GUI, i personally dont need it and i know most people dont, but at the same time people will want it.

**Comment by lxwntr** [comment]
The GUI tool is now included (with options to disable certain variants), however I've ran into a problem on NixOS were the included GUI wrapper is unable to auto-detect what GUI type to use (manual selection is fine).

Tested and working:
ventoy-gui --gtk2
ventoy-gui --gtk3
ventoy-gui --qt5

Working on Fedora+Nix but not NixOS:
ventoy-gui

I will investigate how to solve this.

**Comment by lxwntr** [comment]
The upstream GUI wrapper looks for /etc/ld.so.cache to detect what UI toolkit to use, this fails on NixOS. As a workaround a default is now set based on the configured options passed to the nix file. Now everything works on my systems.

**Comment by Kranzes** [comment]
Hey I will test it in a bit, thanks for all your work on this!

**Review by Artturin — CHANGES_REQUESTED** [review]

**Pull request merged**
