### PR TITLE
xmpp-client: init at dc9d6be

### PR DESCRIPTION
**Pull request by codsl**
Add the one and only xmpp-client. How has anyone been able to live without it?

### CODE REVIEW

**Comment by jgillich** [comment]
Yet another client for a dying protocol, finally! :p

**Comment by codsl** [comment]
@jgillich maybe #11979 is more to your liking. :)

**Comment by jagajaga** [comment]
@jgillich xmpp will live forever.

**Comment by devhell** [comment]
I agree, xmpp will live forever. :)
Could you, @codsl please update the PR according to our contribution guidelines? Thanks! :)

**Comment by codsl** [comment]
@devhell Seems like I'm overlooking something. Could you give me a hint?

**Comment by jagajaga** [comment]
@codsl please add version. As a field and as a name's part.

**Comment by jgillich** [comment]
@codsl What is the status of this and #11979? :)

**Comment by fpletz** [comment]
#12407

**Pull request closed without merging**
