### PR TITLE
pinentry: add GNOME frontend

### PR DESCRIPTION
**Pull request by jtojnar**
This pull request introduces GNOME 3 frontend for pinentry, `pinentry_gnome`. Because `gnupg` depends on `pinentry` and `pinentry_gnome` depends on `gnupg` via `gcr`, I had to modify `gcr` to prevent building GUI. I also added libsecret dependency for caching passwords.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
As previously, the `gnupg-agent` accesses incorrect path when I try to sign something:

```
gpg-agent[15706]: can't connect to the PIN entry module '/usr/bin/pinentry-gnome3': IPC connect call failed
```

<details>
<summary markdown="1">I am installing <code>gnupg</code> with <code>pinentry_gnome</code>.</summary>
Using the following override

```nix
{
  nixpkgs.config.packageOverrides = {
    gnupg = gnupg.override {
      pinentry = pinentry_gnome;
    };
  };
}
```

I see this when building:

```
[...]
Default pinentry:  /nix/store/i1sjd69zjgpy04z7jda0m2g65wdd8hbw-pinentry-1.0.0/bin/pinentry
[...]
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\"/nix/store/krdf8zvqwx90h0lskg1kd82k3y5bafvw-gnupg-2.1.21/share/locale\" -DGNUPG_BINDIR="\"/nix/store/krdf8zvqwx90h0lskg1kd82k3y5bafvw-gnupg-2.1.21/bin\"" -DGNUPG_LIBEXECDIR="\"/nix/store/krdf8zvqwx90h0lskg1kd82k3y5bafvw-gnupg-2.1.21/libexec\"" -DGNUPG_LIBDIR="\"/nix/store/krdf8zvqwx90h0lskg1kd82k3y5bafvw-gnupg-2.1.21/lib/gnupg\"" -DGNUPG_DATADIR="\"/nix/store/krdf8zvqwx90h0lskg1kd82k3y5bafvw-gnupg-2.1.21/share/gnupg\"" -DGNUPG_SYSCONFDIR="\"/nix/store/krdf8zvqwx90h0lskg1kd82k3y5bafvw-gnupg-2.1.21/etc/gnupg\"" -DGNUPG_LOCALSTATEDIR="\"/nix/store/krdf8zvqwx90h0lskg1kd82k3y5bafvw-gnupg-2.1.21/var\""  -DGNUPG_DEFAULT_PINENTRY="\"/nix/store/i1sjd69zjgpy04z7jda0m2g65wdd8hbw-pinentry-1.0.0/bin/pinentry\""      -I/nix/store/5kx4d0zwj2236ng23kw2ws7z4qfqz2bz-libgcrypt-1.7.8-dev/include -I/nix/store/35pds3b8fv4bviaspmm7a5qfwplw5c0r-libgpg-error-1.27-dev/include -I/nix/store/b5rln46cxmsjcl0mbxmxa7ldmah918d8-libassuan-2.4.3-dev/include -I/nix/store/35pds3b8fv4bviaspmm7a5qfwplw5c0r-libgpg-error-1.27-dev/include -I/nix/store/6z896znj5ih72m5knawz2xw1vmpin3c4-libksba-1.3.5-dev/include -I/nix/store/35pds3b8fv4bviaspmm7a5qfwplw5c0r-libgpg-error-1.27-dev/include -I/nix/store/b5rln46cxmsjcl0mbxmxa7ldmah918d8-libassuan-2.4.3-dev/include -I/nix/store/35pds3b8fv4bviaspmm7a5qfwplw5c0r-libgpg-error-1.27-dev/include -DWITHOUT_NPTH=1 -Wall -Wno-pointer-sign -Wpointer-arith  -g -O2 -c -o libcommon_a-mapstrings.o `test -f 'mapstrings.c' || echo './'`mapstrings.c
[...]
```
</details>

**Comment by ttuegel** [comment]
> As previously, the gnupg-agent accesses incorrect path when I try to sign something:

Yes, you have to set the path in `$HOME/.gnupg/gpg.conf` or `$HOME/.gnupg/gpg-agent.conf`. Just overriding the `pinentry` attribute is not going to change the path in `gnupg`; you would have to patch `gnupg` to do that.

**Review by fpletz — APPROVED** [review]

**Comment by jtojnar** [comment]
@ttuegel Oh, I forgot I have created `$HOME/.gnupg/gpg-agent.conf` when I have been using Arch. After deleting the file, the GNOME pinentry is recognized correctly.

Now, do you have any idea why Travis Darwin build fails?
```
clang++ -DHAVE_CONFIG_H -I. -I..  -I/nix/store/cl2v73fvsmschkrhmxllddhdml76r6aj-libsecret-0.18.5-dev/include/libsecret-1 -I/nix/store/m4ppjkkda89wfkgsdky62ffd5hp0zqv1-glib-2.52.1-dev/include/glib-2.0 -I/nix/store/07ynsgd6v3rbg8llpp80h40nhmh894ak-glib-2.52.1/lib/glib-2.0/include -I/nix/store/ss1jg7g9k96v9bakxlls7diwkxrk6pqx-libassuan-2.4.3-dev/include -I/nix/store/k9xcjc4d1c3lh41s6yagdwdvnf7w71s3-libgpg-error-1.27-dev/include -I/nix/store/k9xcjc4d1c3lh41s6yagdwdvnf7w71s3-libgpg-error-1.27-dev/include  -I.. -I../secmem  -I../pinentry -Wall -DQT_SHARED -I/nix/store/vqdnc4x1qvdlmggkpnvh15rqdc6wbw06-qt-4.8.7/include -I/nix/store/vqdnc4x1qvdlmggkpnvh15rqdc6wbw06-qt-4.8.7/include/QtGui -I/nix/store/vqdnc4x1qvdlmggkpnvh15rqdc6wbw06-qt-4.8.7/include -I/nix/store/vqdnc4x1qvdlmggkpnvh15rqdc6wbw06-qt-4.8.7/include/QtCore -g -O2 -c -o pinentrydialog.o pinentrydialog.cpp

In file included from pinentrydialog.cpp:25:

./pinentrydialog.h:28:10: fatal error: 'QDialog' file not found

#include <QDialog>
```

**Review by bendlas — APPROVED** [review]
Just built it. Works fine and fixes a problem for me, that the gtk2 version has.

**Comment by Ma27** [comment]
just built it locally. Seems to work :-)

**Comment by jtojnar** [comment]
Rebased.

It looks like it previously built `pinentry_qt` on Darwin successfully just because the qt4 target was not enabled due to invalid configure argument. Should I limit the platforms to just linux for `pinentry_qt`?

**Comment by fpletz** [comment]
This breaks the gpg-agent user service for me. It seems there is some dbus stuff missing that the gnome3 version needs. Reverted 3f7e3db74426f658b4625505d262c1f7b288606d for now.

**Comment by jtojnar** [comment]
@fpletz Could you provide some more details (desktop environment, journal log, configuration.nix)? I am unable to reproduce it.

**Comment by fpletz** [comment]
On 17.09 with the revert reverted, I can reproduce this issue on my system

Here is the relevant portion from the journal:

```
Dec 16 01:11:57 yolovo systemd[19988]: Started GnuPG cryptographic agent and passphrase cache.
Dec 16 01:11:57 yolovo gpg-agent[19997]: gpg-agent (GnuPG) 2.2.3 starting in supervised mode.
Dec 16 01:11:57 yolovo gpg-agent[19997]: using fd 3 for std socket (/run/user/1000/gnupg/S.gpg-agent)
Dec 16 01:11:57 yolovo gpg-agent[19997]: using fd 4 for ssh socket (/run/user/1000/gnupg/S.gpg-agent.ssh)
Dec 16 01:11:57 yolovo gpg-agent[19997]: listening on: std=3 extra=-1 browser=-1 ssh=4
Dec 16 01:12:06 yolovo gpg-agent[19997]: No $DBUS_SESSION_BUS_ADDRESS found, falling back to curses
Dec 16 01:12:06 yolovo gpg-agent[19997]: Failed to lookup password for key s/162F8C3CF3C122E6E5A694519EE2006322D9B3F5 with secret service: Cannot autolaunch D-Bus without X11 $DISPLAY
Dec 16 01:12:06 yolovo gpg-agent[19997]: failed to unprotect the secret key: No such file or directory
Dec 16 01:12:06 yolovo gpg-agent[19997]: failed to read the secret key
Dec 16 01:12:06 yolovo gpg-agent[19997]: ssh sign request failed: No such file or directory <Pinentry>
```

The relevant settings from my NixOS config:

```
    services.xserver = {
      desktopManager.default = "none";
      desktopManager.xterm.enable = false;
      windowManager.default = "i3";
      windowManager.xmonad.enable = false;
      windowManager.xmonad.enableContribAndExtras = false;
      windowManager.i3.enable = true;
      displayManager.slim.enable = true;
  };


  programs.gnupg.agent.enable = true;
  programs.gnupg.agent.enableSSHSupport = true;
```

**Pull request merged**
