### PR TITLE
treewide: mass rebuild noop cleanups

### LINKED ISSUE #43547: binutils and gcc manpages hidden by wrappers
## Issue description

The `gcc` and `bin-utils` wrappers don't expose the underlying derivations' `man` outputs.

### Steps to reproduce

1. `nix run nixpkgs.binutils.man -c man ld`
2. Notice that the manpage is not found

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.14, NixOS, 18.03.132646.08d245eb31a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.12pre5788_e3013543`
 - channels(root): `"nixos-18.03.132646.08d245eb31a, nixpkgs-18.09pre142651.95a8cb3ade1"`
 - channels(ben): `"nixpkgs-18.03pre126020.931a0b8be80"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

First patch is the first patch of #46115 (which should also close #43547 again, but without the "controversial" second patch of #46115), second patch is a fixed edited version of #46127, the rest are trivial noop changes that cause mass rebuilds.

###### Things done

- [X] Trivial.
- [X] All touched packages still build.
- [X] Running on top of this for a month without issues.

/cc @Ericson2314

### CODE REVIEW

**Review by 7c6f434c — APPROVED** [review]
I want to give time for opinions, but LGTM.

**Review by xeji — APPROVED** [review]
LGTM

**Comment by oxij** [comment]
ping

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
Thanks!!

**Pull request merged**
