### PR TITLE
staging-next-23.11 iteration 7 - 2024-04-04

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important job: https://hydra.nixos.org/job/nixpkgs/staging-next-23.11/unstable#tabs-constituents
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next-23.11
  https://hydra.nixos.org/jobset/nixos/staging-next-23.11-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next-23.11 PR: https://github.com/NixOS/nixpkgs/pull/293976
- - - 
##### Significant breakages
(will be edited based on progress)

### CODE REVIEW

**Comment by vcunat** [comment]
- [ ] `python3Packages.eventlet` regressed in tests, blocking very many builds
  https://hydra.nixos.org/build/255402898/nixlog/1/tail
  /cc maintainer @SuperSandro2000
  BTW, [recent tags](https://github.com/eventlet/eventlet/tags) mention some security fixes.

**Comment by SuperSandro2000** [comment]
Hydra is not loading the logs for me currently but I blindly guess we need https://github.com/NixOS/nixpkgs/commit/9db042bf9e22b485f7071ba8093a78a67f8b2889

**Comment by vcunat** [comment]
```
=========================== short test summary info ============================
FAILED tests/greenio_test.py::TestGreenSocket::test_full_duplex - tests.TestIsTakingTooLong: 1
FAILED tests/greenio_test.py::TestGreenSocket::test_invalid_connection - AssertionError: Readers: Listener FdListener('read', 17, <built-in method s...
FAILED tests/greenio_test.py::TestGreenSocket::test_nonblocking_accept_mark_as_reopened - AssertionError: Readers: Listener FdListener('read', 17, <built-in method s...
FAILED tests/greenio_test.py::TestGreenSocket::test_raised_multiple_readers - AssertionError: Readers: Listener FdListener('read', 17, <built-in method s...
FAILED tests/greenio_test.py::TestGreenSocket::test_recv_into_timeout - AssertionError: Readers: Listener FdListener('read', 17, <built-in method s...
ERROR tests/greenio_test.py::TestGreenSocket::test_full_duplex - AssertionError: Readers: Listener FdListener('read', 17, <built-in method s...
= 5 failed, 562 passed, 120 skipped, 18 deselected, 1163 warnings, 1 error in 43.69s =
```

**Comment by vcunat** [comment]
Ah, thanks, indeed.  I picked that patch, so it builds at least.  You (anyone) could consider whether the security fixes need addressing, but that's mostly an independent thing.

**Comment by vcunat** [comment]
- [ ] `gdal` regressed a few tests on *-darwin (retried) and quite a few packages depend on it
  https://hydra.nixos.org/build/255521404/nixlog/4/tail
  https://hydra.nixos.org/build/255375799/nixlog/6/tail
  /cc e.g. maintainer @imincik

**Comment by vcunat** [comment]
I don't think there's anything worth blocking on, really.

**Pull request merged**
