### PR TITLE
python312: 3.12.3 -> 3.12.4

### LINKED ISSUE #317910: Update request: python312 3.12.3 -> 3.12.4
- Package name: python312
- Latest released version: 3.12.4

- Current version on the unstable channel: 3.12.3
- Current version on the stable/release channel: 3.12.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@mweinelt 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by natsukium**
https://docs.python.org/release/3.12.4/whatsnew/changelog.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mweinelt** [comment]
Tests are looking good on all platforms.

**Comment by vcunat** [comment]
I think the 24.05 backport was merged too soon.  We'd now be getting this in `nixos-24.05` before `nixos-unstable`, but that's not great, as experience shows that even patch-level bumps of python break things commonly.  (fortunately 3.12 is not the default python version at least)

The first regression we see now is [sphinx](https://hydra.nixos.org/build/263315767) (checked locally that the python bump itself triggered that).

**Comment by vcunat** [comment]
Another one:
- [ ] `.pydantic-core` https://hydra.nixos.org/build/263292352

**Comment by vcunat** [comment]
I assume I'll revert the 24.05 backport for now?

**Comment by mweinelt** [comment]
Taking a look.

**Comment by mweinelt** [comment]
Okay, I think I've got fixes for all three packages ready. Ideally we'd manage them in staging first, but now that we are here, we might as well deal with them.

**Comment by vcunat** [comment]
I suppose, if we seem to have enough manpower to fix these, we can try keeping it in this `staging-next-24.05` iteration.  The advantage of stable staging is that there's typically much less noise than in `staging-next`.

**Comment by vcunat** [comment]
- [ ] `.makefun`
- [ ] `.mashumaro`

**Comment by mweinelt** [comment]
Found issues for makefun and twisted, ended up disabling those tests. Creating an issue for mashumaro, since I assume they fixed the issue in one version, then introduced other issues, because they were testing with Python 3.12.3, not 3.12.4.

**Comment by vcunat** [comment]
It was a lot, but almost all regressions should've been addressed by now:
https://hydra.nixos.org/eval/1807186?filter=python312Packages&compare=1807119#tabs-now-fail

**Pull request merged**
