### PR TITLE
nixos/dhcpcd: harden and run as unprivileged user 

### PR DESCRIPTION
**Pull request by rnhmjoj**
## Description of changes

These changes replace the dhcpcd privsep mode with a combination of POSIX capabilities and systemd security features that allow to fully run dhcpcd as an unprivileged user. See the commit messages for why I think this is an improvement.

There are a couple of backward incompatibilities, but most users shouldn't notice any difference.

## Things done

- [x] Tested via `dhcpcd.tests`
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I re-created the PR because I messed up the staging rebase, as usual.

### CODE REVIEW

**Comment by Mindavi** [comment]
Why is the move from /var/db to /var/lib done?

**Comment by rnhmjoj** [comment]
Fixed merge conflicts.

**Comment by rnhmjoj** [comment]
Fixed more merge conflicts.

**Comment by rnhmjoj** [comment]
Fixed yet another merge conflict. 

(These treewide cosmetic changes are becoming annoying)

**Comment by aanderse** [comment]
hey @rnhmjoj :wave: 

awesome change, thanks for the work

is it a problem if we keep the `enablePrivSep` logic for the package? some people (like me) are using this package on systems which aren't nixos so dropping that logic might cause some problems, depending on their setup

**Comment by rnhmjoj** [comment]
> awesome change, thanks for the work
Thank you!

> is it a problem if we keep the enablePrivSep 

No, of course not: I can make another PR to bring back the option. I'm just not sure whether to wait for the changes to reach master, or do another one targeting staging.

**Comment by aanderse** [comment]
let's wait, no immediate rush on this :+1:

thank you so much @rnhmjoj!

**Comment by vcunat** [comment]
FYI, this clashes with https://github.com/NixOS/nixpkgs/pull/208780
(right now in merge from master to staging-next)

**Comment by SuperSandro2000** [comment]
Why was this PR even targetting staging? 500 rebuilds is not so much.

**Comment by rnhmjoj** [comment]
It was much higher during the first iteration: https://github.com/NixOS/nixpkgs/pull/276919. Probably some important package dropped resolvconf as a dependency.

**Comment by rnhmjoj** [comment]
So, what do we do? Izorkin's PR was first (sorry I missed it), but I think this one has more features (removes root, avoids privsep that doesn't work in hardened profile, adds a resolvconf test) and I had already announced it on discourse.
Should I fix the conflict in staging with another PR?

cc @Izorkin

**Comment by Izorkin** [comment]
Maybe try comparing the sandbox parameters with each other and make changes. Your PR is missing some parameters.
I would also like to keep the `enablePrivSep` parameter in dhcpcd. Only the `graphene-hardened` memory allocator is not supported in recent versions:
https://github.com/NixOS/nixpkgs/pull/346938

**Comment by vcunat** [comment]
Oh, I see them merged together now:
```bash
git show 956f9243c06ba48e484d6e3f469e4756cbd04e5e
```

**Comment by rnhmjoj** [comment]
> Maybe try comparing the sandbox parameters with each other and make changes. Your PR is missing some parameters.

Thank you, will do.

> I would also like to keep the enablePrivSep parameter in dhcpc

Yeah, removing it was not a good idea, I was already planning on bringing it back.

**Comment by Izorkin** [comment]
> Yeah, removing it was not a good idea, I was already planning on bringing it back.

Maybe try revert commit a432668 in staging-next branch?

**Comment by rnhmjoj** [comment]
Thanks to @K900 for doing the merging, everything looks fine, I'll just remove the duplicate release note.
I think the only real difference between the two sets of options were the `ProtectProc` and `Umask`: I run the tests on staging-next and DHCP + resolvconf seems to be still ok.

**Comment by Izorkin** [comment]
@rnhmjoj missing parameter `ProcSubset`.

**Comment by K900** [comment]
`ProcSubset=all` is the default.

**Comment by Izorkin** [comment]
> `ProcSubset=all` is the default.

Ok, thanks.

**Comment by Izorkin** [comment]
Have you tried adding the `CapabilityBoundingSet` parameter?
```
  CapabilityBoundingSet = [ "CAP_NET_ADMIN" "CAP_NET_RAW" "CAP_NET_BIND_SERVICE" ];
```

**Comment by rnhmjoj** [comment]
From my understading of capabilities, that is only useful if the service is running as root and you want to restrict it. In this case it's already unpriviliged and the only capabilities it has are the one given in AmbientCapabilities. Anyway, I still don't understand what you're trying to achieve.

**Comment by Izorkin** [comment]
Capabilites without `CapabilityBoundingSet`:
```
CapInh: 0000000000203500
CapPrm: 0000000000003400
CapEff: 0000000000003400
CapBnd: 000001f3f5fcffff
CapAmb: 0000000000003400
```

Capabilites with `CapabilityBoundingSet`:
```
CapInh: 0000000000003400
CapPrm: 0000000000003400
CapEff: 0000000000003400
CapBnd: 0000000000003400
CapAmb: 0000000000003400
```

The `CapabilityBoundingSet` parameter further limits the processes.

**Comment by uninsane** [comment]
`NoNewPrivileges = true` has the effect of restricting `CapInh` to be <= `CapPrm` in all of the places in which `CapInh` is actually _used_. i.e. try making a setcap binary for one of the bits that are in `CapInh` but not `CapPrm`. it won't actually grant those caps, so in _effect_ the two capability sets you show are equivalent, given NoNewPrivileges.

i don't think there's much harm in setting CapabilityBoundingSet, but if you trust that the capability system behaves as described, there's no need.

see: `man PR_SET_NO_NEW_PRIVS` and `man capabilities` (in the section for `Inheritable`)

**Comment by Izorkin** [comment]
There are errors in the logs of the dhcpcd service:
```
(e-dhcpcd)[761]: dhcpcd.service: Failed to set up mount namespacing: /run/resolvconf: No such file or directory
(e-dhcpcd)[761]: dhcpcd.service: Failed at step NAMESPACE spawning /nix/store/yr3ywvhmbcpd6w2hm0jbgj09y7saij6g-migrate-dhcpcd: No such file or directory
```
and
```
dhcpcd[910]: /nix/store/waiskclr9v15ws56hb33n82wyixgp6pz-openresolv-3.13.2/sbin/.resolvconf-wrapped: line 945: /run/resolvconf/metrics/0001002 enp1s0.dhcp: Permission denied
```

**Comment by rnhmjoj** [comment]
I can reproduce it with `nixosTests.networking.scripted.dhcpSimple`. The first error seems to be a race condition: it looks like systemd is trying to set up the sandbox while `resolvconf.service` hasn't run yet. I'm not sure about the second error, however /etc/resolv.conf file seems to be populated correctly.

**Comment by vcunat** [comment]
Yes, that test is blocking the `nixos-unstable` channel now.
https://hydra.nixos.org/build/274843085#tabs-buildsteps

**Comment by mweinelt** [comment]
Can we revert and revisit later now that a blocking test case has been identified and no clear path forward has been presented?

**Comment by corngood** [comment]
I'm using dhcpcd with dnsmasq and getting:

```
dhcpcd[2881]: /nix/store/waiskclr9v15ws56hb33n82wyixgp6pz-openresolv-3.13.2/sbin/.resolvconf-wrapped: line 945: /run/resolvconf/metrics/0001002 enp4s0.dhcp : Permission denied
dhcpcd[2916]: /nix/store/waiskclr9v15ws56hb33n82wyixgp6pz-openresolv-3.13.2/libexec/resolvconf/dnsmasq: line 166: /etc/dnsmasq-conf.conf: Read-only file system
dhcpcd[2916]: /nix/store/waiskclr9v15ws56hb33n82wyixgp6pz-openresolv-3.13.2/libexec/resolvconf/dnsmasq: line 174: /etc/dnsmasq-resolv.conf: Read-only file system
```

This one is actually breaking because it can't write the dnsmasq config.

I'll try to get it working by porting what it does for resolv.conf to these files.

**Comment by corngood** [comment]
Something like this maybe?

```
diff --git a/nixos/modules/config/resolvconf.nix b/nixos/modules/config/resolvconf.nix
index 0d56ccf85d4c..6cdd193a2034 100644
--- a/nixos/modules/config/resolvconf.nix
+++ b/nixos/modules/config/resolvconf.nix
@@ -114,6 +114,14 @@ in
         '';
       };
 
+      outputFiles = lib.mkOption {
+        type = lib.types.listOf lib.types.path;
+        default = [ "/etc/resolv.conf" ];
+        description = ''
+          Files written by resolvconf updates
+        '';
+      };
+
     };
 
   };
@@ -150,8 +158,9 @@ in
 
         script = ''
           ${lib.getExe cfg.package} -u
-          chgrp -R resolvconf /etc/resolv.conf /run/resolvconf
-          chmod -R g=u /etc/resolv.conf /run/resolvconf
+          files=(${lib.escapeShellArgs cfg.outputFiles})
+          chgrp -R resolvconf "''${files[@]}"
+          chmod -R g=u "''${files[@]}"
         '';
       };
 
diff --git a/nixos/modules/services/networking/dhcpcd.nix b/nixos/modules/services/networking/dhcpcd.nix
index afc977583594..71a193fe22ce 100644
--- a/nixos/modules/services/networking/dhcpcd.nix
+++ b/nixos/modules/services/networking/dhcpcd.nix
@@ -250,7 +250,7 @@ in
             Restart = "always";
             AmbientCapabilities = [ "CAP_NET_ADMIN" "CAP_NET_RAW" "CAP_NET_BIND_SERVICE" ];
             ReadWritePaths = [ "/proc/sys/net/ipv6" ]
-              ++ lib.optionals useResolvConf [ "/etc/resolv.conf" "/run/resolvconf" ];
+              ++ lib.optionals useResolvConf ([ "/run/resolvconf" ] ++ config.networking.resolvconf.outputFiles);
             DeviceAllow = "";
             LockPersonality = true;
             MemoryDenyWriteExecute = true;
diff --git a/nixos/modules/services/networking/dnsmasq.nix b/nixos/modules/services/networking/dnsmasq.nix
index 633e37ad25e9..f185f566ee63 100644
--- a/nixos/modules/services/networking/dnsmasq.nix
+++ b/nixos/modules/services/networking/dnsmasq.nix
@@ -133,6 +133,11 @@ in
         dnsmasq_conf=/etc/dnsmasq-conf.conf
         dnsmasq_resolv=/etc/dnsmasq-resolv.conf
       '';
+
+      outputFiles = [
+        "/etc/dnsmasq-conf.conf"
+        "/etc/dnsmasq-resolv.conf"
+      ];
     };
 
     systemd.services.dnsmasq = {
```

**Comment by rnhmjoj** [comment]
> I'm using dhcpcd with dnsmasq and getting:

Can you share your config so I can test this setup?

**Comment by corngood** [comment]
> Can you share your config so I can test this setup?

I think `services.dnsmasq.enable = true` is sufficient.  You want to make sure you're hitting this bit in the dnsmasq module:

```
    networking.resolvconf = lib.mkIf cfg.resolveLocalQueries {
      useLocalResolver = lib.mkDefault true;

      extraConfig = ''
        dnsmasq_conf=/etc/dnsmasq-conf.conf
        dnsmasq_resolv=/etc/dnsmasq-resolv.conf
      '';
```

**Comment by rnhmjoj** [comment]
Yes, please.

**Comment by Shados** [comment]
@rnhmjoj seems like it also needs`"/proc/sys/net/ipv4"` added to `ReadWritePaths`? Without that, my IPV4-only setup fails like so:
```
Oct 25 16:27:32 fracture systemd[1]: Starting DHCP Client...
Oct 25 16:27:32 fracture dhcpcd[2651]: dhcpcd-10.0.6 starting
Oct 25 16:27:32 fracture dhcpcd[2653]: dev: loaded udev
Oct 25 16:27:32 fracture dhcpcd[2653]: enp1s0: if_init: Read-only file system
Oct 25 16:27:32 fracture dhcpcd[2653]: enp1s0: if_init: Read-only file system
Oct 25 16:27:32 fracture dhcpcd[2653]: no valid interfaces found
Oct 25 16:27:32 fracture dhcpcd[2653]: no valid interfaces found
Oct 25 16:27:48 fracture dhcpcd[2653]: received SIGTERM, stopping
Oct 25 16:27:48 fracture dhcpcd[2653]: dhcpcd exited
```

Also, even with that added:
```
Oct 25 16:27:54 fracture dhcpcd[2969]: /nix/store/waiskclr9v15ws56hb33n82wyixgp6pz-openresolv-3.13.2/sbin/.resolvconf-wrapped: line 945: /run/resolvconf/metrics/0001002 enp1s0.dhcp: Permission denied
```

It appears the metrics sub-directory doesn't have the group and permissions needed to enable this:
```
shados@fracture[~] λ ls -lah /run/resolvconf
total 0
drwxrwxr-x  4 root resolvconf  80 Oct 25 16:27 .
drwxr-xr-x 33 root root       920 Oct 25 16:27 ..
drwxrwxr-x  2 root resolvconf  80 Oct 25 16:27 interfaces
drwxr-xr-x  2 root root        60 Oct 25 16:25 metrics
```

**Comment by rnhmjoj** [comment]
> seems like it also needs"/proc/sys/net/ipv4" added to ReadWritePaths?
I haven't seen this one before, strange. It looks correct: it appers to be writing to `/proc/sys/net/ipv4/conf/%s/promote_secondaries`.

> Oct 25 16:27:54 fracture dhcpcd[2969]: /nix/store/waiskclr9v15ws56hb33n82wyixgp6pz-openresolv-3.13.2/sbin/.resolvconf-wrapped: line 945: /run/resolvconf/metrics/0001002 enp1s0.dhcp: Permission denied

This one is puzzling, because it's resolvconf itself that is creating the file (if you look at line 945) and the directory is writable. I still haven't figured out whats going on exactly. Anyway, if you have a single interface metrics don't matter.

**Comment by Shados** [comment]
> This one is puzzling, because it's resolvconf itself that is creating the file (if you look at line 945) and the directory is writable.

The `/run/resolvconf/metrics` directory has `root` as group, and also isn't group- or other-writeable, and dhcpcd doesn't run as root.

But yes, the metrics issue isn't problematic for my use-cases currently, which is good for me.

**Comment by rnhmjoj** [comment]
> The /run/resolvconf/metrics directory has root as group, and also isn't group- or other-writeable, and dhcpcd doesn't run as root.

The source of the incorrect permissions was the network-setup script invoking `resolvconf` as root. I have found a simple solution using POSIX ACLs, see #351225.

**Comment by nfroger** [comment]
Hello, I don't really understand the reason for this change but this breaks dynamic hostname fetching with DHCP.

**Comment by rnhmjoj** [comment]
If you can describe me a bit your setup and how it fails with hardening, I can try to help.
I guess dhcpcd doesn't have the permission to change the hostname.

Anyway, the reason for this change is that dhcpcd is a demon with root privileges, network access, written in a memory unsafe language, which is quite a combination. It has a built-in security mechanism to mitigate this, but it caused some issues, so it's better to use systemd to isolate it. By default the daemon has limited permissions, which is fine for a majority of users.

**Comment by nfroger** [comment]
I understand but this was utterly frustrating to stumble across because I don't believe my use-case is rare at all (cloud VMs or anything that uses network boot) and I would have had expected more thorough testing of the basic features of a DHCP client after such a breaking change.

Anyway, I managed to fix this with the following:
```
  systemd.services.dhcpcd = {
    serviceConfig = {
      ProtectHostname = lib.mkForce false;
      SystemCallFilter = lib.mkBefore [ "sethostname" ];
      AmbientCapabilities = [ "CAP_SYS_ADMIN" ];
    };
  };
```
Let me know if this makes sense to you and I can make a PR.

This took even more time to debug because yet another breaking change happened in #359571 which has a side effect of changing the default hostname from `localhost` to `nixos`, and dhcpcd only changes the hostname if it is `localhost` or `localhost.localdomain`. So now adding `env force_hostname=YES` to dhcpcd's config is also needed to fetch the hostname with DHCP. An alternative would be to specify the new default hostname of NixOS in dhcpcd's derivation using the `--with-default-hostname` configure flag but I'm not sure if it's the best solution.

**Comment by rnhmjoj** [comment]
Sorry, but the basic features are configuring addresses, routes and nameservers, which is what is been tested in NixOS. Your use case may not be rare, but I personally never used it, nor anyone else that maintains NixOS networking tests...

I don't think CAP_SYS_ADMIN is acceptable, at least not by default: it's so overloaded that's basically running as root again.

**Comment by rnhmjoj** [comment]
The host name is being set from a shell hook, so it be to fix both issues:

1. use sudo or polkit to allow running `hostname`
2. add "nixos" as a default hostname

**Comment by nfroger** [comment]
I'm not sure it's that easy. I'm not very familiar with polkit but from what I understand I don't think we can use it here because NixOS doesn't use systemd-hostnamed. I'm guessing sudo is one way to go but that means we have to patch the hook or wrap hostname.

**Pull request merged**
