### PR TITLE
open-vm-tools: fix build with glib 2.68

### PR DESCRIPTION
**Pull request by jshholland**
Also apply nixpkgs-format.

###### Motivation for this change

Fix failing build, see e.g. https://hydra.nixos.org/build/142620456

###### Things done

- [z] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jshholland** [comment]
Fix comes from https://github.com/vmware/open-vm-tools/issues/500 and will be included in the next release.

**Comment by jshholland** [comment]
Oh, also:
ZHF: #122042
@NixOS/nixos-release-managers

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122805` at 4c6418cf run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>open-vm-tools</li>
    <li>open-vm-tools-headless</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

rpcsvc-proto is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/virtualization/open-vm-tools/default.nix:64:3:
```
   |
64 |   buildInputs = [ fuse glib icu libdnet libmspack libtirpc openssl pam procps rpcsvc-proto xercesc ]
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/virtualization/open-vm-tools/default.nix:48:5:
```
   |
48 |     (fetchpatch {
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/open-vm-tools/default.nix:113:5:
```
    |
113 |     license = licenses.gpl2;
    |     ^
```
</li>
  </ul>
</details>

**Comment by jshholland** [comment]
Updated with suggestions from @r-rmcgibbo

**Comment by jshholland** [comment]
Oops, I missed #122183 - my bad.

**Pull request closed without merging**
