### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
I removed `pkgs/development/python-modules/azure-cli-core/default.nix` from master (no longer needed for azure-cli package), you can delete changes to it here

**Comment by jonringer** [comment]
to help move stabilization along, I reverted the conflicting changes, preferring master changes

**Comment by ajs124** [comment]
This seems to have broken `python3.pkgs.deprecated`. It was only a minor bump, but [fails to build](https://hydra.nixos.org/build/107540902).

**Comment by worldofpeace** [comment]
Hi @terlar @ajs124.

If a package is failing to build and you identified that a staging-next merged introduced it, could you open an issue? When it comes to python packages, there's frequent breakages on unstable.

**Comment by jtojnar** [comment]
Fido has been already fixed in https://github.com/NixOS/nixpkgs/pull/74816

**Comment by jtojnar** [comment]
Fixed python3Packages.deprecated in 9fe1b95c3d6

**Pull request merged**
